### ISSUE TITLE
[amp-gist][validator][test] Fix validator/test

### ISSUE THREAD

**Issue by levidurfee** [ampproject/amphtml#10001]
## What's the issue?

`amp-gist` isn't passing validator tests ran by `amp-by-example` repo.

## How do we reproduce the issue?

[travis-ci](https://travis-ci.org/ampproject/amp-by-example/builds/243902984) test results.

Tests should also include `data-file` attribute.

**Comment by honeybadgerdontcare** [comment]
Hey, sorry this isn't working as expected. According to the [validation](https://github.com/ampproject/amphtml/blob/master/extensions/amp-gist/validator-amp-gist.protoascii#L33) for amp-gist `data-file` is required to be an empty string (`value: ""`).

If this is supposed to be a url then `value_url` can be used instead. If it's supposed to be anything then no `value` should be set in the validator protoascii.

BTW, all `data-` attributes are automatically allowed by the validator. Maybe it's best just to remove `data-file` from the validator-amp-gist.protoascii. If there requirements for what it should be, what are they? I can help craft what is necessary for validation.

/cc @aghassemi

**Comment by levidurfee** [comment]
I intended `data-file` to allow any valid filename as a string. I agree that it's best to remove `data-file` from `validator-amp-gist.protoascii`.

Updated [validator-amp-gist.protoascii](https://github.com/levidurfee/amphtml/blob/amp-gist-validator/extensions/amp-gist/validator-amp-gist.protoascii) and [test-amp-gist.js](https://github.com/levidurfee/amphtml/blob/amp-gist-validator/extensions/amp-gist/0.1/test/test-amp-gist.js).

If those look good I'll create a PR.

**Comment by honeybadgerdontcare** [comment]
Validator change looks good, but I'd remove the comment about it as it's not necessary (line 31)
