### ISSUE TITLE
Failure in test-example-validation

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#10008]
[Unit and integration test breakages](https://travis-ci.org/ampproject/amphtml/jobs/243865808) on master seemingly due to #9997:

> Chrome 59.0.3071 (Linux 0.0.0) example autosuggest.amp.html should validate FAILED
	AssertionError: expected 'DISALLOWED_ATTR [src] amp-list\nEXTENSION_UNUSED amp-bind' to equal ''
	    at /home/travis/build/ampproject/amphtml/test/integration/test-example-validation.js:120:37 <- /tmp/57e74a45ba6487b46c25745bb825b639.browserify:209513:38

/to @Gregable

**Comment by kul3r4** [comment]
This is also impacting websites like [iene.it](https://www.iene.mediaset.it/) which is using this binding to amp-list src.

**Comment by choumx** [comment]
Actually this is probably caused by #9742. The DISALLOWED_ATTR is caused by the accidental [removal of a few lines](https://github.com/ampproject/amphtml/pull/9742/files#diff-a17ce4927fbb7859b6c703250cd885edL48) and EXTENSION_UNUSED seems related to the new `requires_extension`. 

I'll add the missing test cases to `validator-amp-list.html` which would've helped catch the first issue. 

@Gregable, can we revert (GitHub and google3)?

**Comment by Gregable** [comment]
It looks like a bad merge, I went through the files just now and this was the only issue I could fine.

I don't think we can revert at this point. It's 2 weeks worth of changes, and is already live in various releases. I'll make an immediate change to github though.

We should also debug why travis didn't catch this earlier if it's breaking now.
