### ISSUE TITLE
AdSense/Doubleclick Fast Fetch SERP ifi should reset when user swipes back to page

### ISSUE THREAD

**Issue by keithwrightbos** [ampproject/amphtml#10000]
Steps to reproduce:

- Load page in SERP viewer with at least one slot
- Ad Request will have ifi=1 for first slot which triggers pageview accounting
- User swipes away and swipes back.  First slot will not report ifi > 1 causing pageview to be lost

Delayed fetch uses master frame for ifi accounting which is destroyed when swiping away and thus does not have this issue.  Fast Fetch must be modified so that onResumeCallback resets ifi counter:
https://github.com/ampproject/amphtml/blob/master/ads/google/a4a/utils.js#L165

cc/ @ampproject/a4a

**Comment by keithwrightbos** [comment]
Sadly despite this being the 10k issue, I am closing it in favor of #10004 as it appears that amp-analytics does not send a duplicate pageview event if a user swipes back so the fix is to ensure Delayed Fetch does not trigger pageview accounting on ad requests.

**Comment by bradfrizzell** [comment]
![image](https://user-images.githubusercontent.com/4276992/27257657-bd3e13c6-53ac-11e7-9ee7-d0d1ed9806a2.png)
congratulations!!
