### ISSUE TITLE
[A11Y] [Web] Focus is not set on Lightbox when opened

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#10005]
STEPS TO REPRODUCE:
Open https://ampstart.com
Navigate to Templates tab
Using chromevox, navigate to article
Navigate to view templates button and click

ACTUAL RESULTS:
Using chromevox, navigate view templates button and select. Pop up will appear with template sample. Focus is not oriented on the pop up template and is still set on the background page.

EXPECTED RESULTS:
User focus is set on pop up template.

ATTACHMENT:
Please see the video in the link below for reference.

https://drive.google.com/open?id=0BwUNSMCBrCB4VzNtTXFoemxzcjg

Copied from - https://github.com/ampproject/ampstart/issues/412

**Comment by aghassemi** [comment]
dup of https://github.com/ampproject/amphtml/issues/4892
