### ISSUE TITLE
Intent To Implement: Adding Nielsen marketing cloud analytics config to amp-analytics

### ISSUE THREAD

**Issue by peterbaran** [ampproject/amphtml#10012]
## Implement tracking pixel of Nielsen Marketing Cloud for amp-analytics tag

For ease of use for publishers using AMP and Nielsen Marketing Cloud analytics, so the external configuration doesn't have to be used
We'll generate the Patch that can be reviewed then

**Comment by lannka** [comment]
@peterbaran looking forward to your PR. let me know if you have any questions.
