### ISSUE TITLE
Click to play broken on IE11 Win 7/8.1

### ISSUE THREAD

**Issue by p2er** [ampproject/amphtml#10014]
## What's the issue?

Click to play does not hide poster image and play button on IE11 Win 7/8.1. Video does not start and does not become visible. Play button and poster image remain visible. Error occurs:

SCRIPT438: Object doesn't support property or method 'includes'
File: v0.js, Line: 218, Column: 154

## How do we reproduce the issue?

1. Open https://ampbyexample.com/advanced/click-to-play_overlay_for_amp-video/ with IE11
2. Click play button
3. Poster and play button still visible
4. Video not started

## What browsers are affected?

IE11 on Windows 7/8.1 (possibly also windows 10)

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1496877433269 https://ampbyexample.com/advanced/click-to-play_overlay_for_amp-video/

<img width="1764" alt="error" src="https://user-images.githubusercontent.com/12771905/27293972-43748fb2-5518-11e7-9909-f490bc193b88.png">

**Comment by cramforce** [comment]
@aghassemi Could you take a look? We might need to polyfill https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes?v=control
