### ISSUE TITLE
Percy test appears flaky with three dots on visual diff

### ISSUE THREAD

**Issue by honeybadgerdontcare** [ampproject/amphtml#10022]
Several PRs are getting the same visual diff issue and causes me to think it may be a flaky test with percy.

Examples:
https://percy.io/ampproject/amphtml/builds/256910
https://percy.io/ampproject/amphtml/builds/256713
https://percy.io/ampproject/amphtml/builds/256555
https://percy.io/ampproject/amphtml/builds/256464
https://percy.io/ampproject/amphtml/builds/255472

More can be found at:
https://percy.io/ampproject/amphtml

**Comment by rsimha-amp** [comment]
@honeybadgerdontcare, I noticed this, searched for an existing issue, didn't find one, and filed #10024, only to find out that you had filed this a few seconds before me :)

**Comment by cramforce** [comment]
@rsimha-amp Waiting for `window.onload` will help. To make it more robust you will need something like this code from `performance-impl.js`:

```js
this.resources_.getResourcesInRect(
        this.win, rect, /* isInPrerender */ false)
        .then(resources => Promise.all(resources.map(r => r.loadedOnce())))
```

**Comment by rsimha-amp** [comment]
I believe there's a way to have percy/capybara wait for a particular CSS element to be visible on a page before taking a snapshot. Will take a look.

http://www.rubydoc.info/github/jnicklas/capybara#asynchronous-javascript-ajax-and-friends

**Comment by cramforce** [comment]
@rsimha-amp I don't think AMP has a clear signal, but it would be OK to add one.

**Comment by rsimha-amp** [comment]
25 straight green Percy builds so far, since #10078 was merged. Looks like the fix worked. Will keep an eye for more timing related failures.

**Comment by rsimha-amp** [comment]
100+ green runs in a row. Consider this fixed.
