### ISSUE TITLE
Banners loading on demand?

### ISSUE THREAD

**Issue by systemaddict** [ampproject/amphtml#1003]
Hi

We want to switch to AMP HTML but we're worried about programmatic income. Do Adsense (and Google DFP) load differently than on a "normal" page using asynchronous load? Do they load on demand (when inview)?

If on demand, could we possibly isolate the banner code and try it before starting a proper implementation?

**Comment by cramforce** [comment]
Ads are currently loaded

- when in view
- or as part of normal resource loading
- when no other ad is loading
- and the user is not currently scrolling
- and has scrolled at least once.

This may change over time.

**Comment by rudygalfi** [comment]
cc @kashyapnitin

**Comment by systemaddict** [comment]
Thanks. Programmatic earnings are extremely sensitive to load time, so it will be interesting to see if the overall performance boost can somehow augment a potential slower ad load.
