### ISSUE TITLE
Google carrusel refreshes ads but it doesn't do a pageview

### ISSUE THREAD

**Issue by rafaguerrero** [ampproject/amphtml#10038]
## What's the issue?
I'm seeing some inconsistencies in the AdR/PV from my website in the AMP version. 
After some debugging I've seen that if a user is browsing through the google carrusel and goes to an already seen article the pageview is not being triggered.

## How do we reproduce the issue?
- Search for something in google from a mobile. Ex: andro4all
- Click on an AMP article from the carrusel. You'll see that the pageview is done.
- Swipe to another article. Again we can see that the pageview is also being done.
- Swipe back to the previous article. In here the ads do refresh but the pageview it's not there.

## What browsers are affected?
As far as I can see it's in all browsers.

**Comment by cramforce** [comment]
Over to Vamsee.

This is definitely working as intended, but maybe it should be changed :)

**Comment by keithwrightbos** [comment]
This is a duplicate of #10004  I was actually waiting for verification that we believe not counting a pageview for ads in this case is the correct behavior.
