### ISSUE TITLE
Relative video path broken on IE11 Win 8.1

### ISSUE THREAD

**Issue by p2er** [ampproject/amphtml#10035]
## What's the issue?

Videos do not load on IE11 Win 8.1 if path is not static, e.g. src="/video/tokyo.mp4"

For erros see sceenshot.
![ie_11_wind81_video_bug](https://user-images.githubusercontent.com/12771905/27328757-87e5dbce-55b3-11e7-859a-717ee8a48bbf.png)
 

## How do we reproduce the issue?

1. Open https://ampbyexample.com/components/amp-video/ on IE11 Win 8.1
2. Videos do not load and error occurs

## What browsers are affected?

IE11 Win 8.1, works on IE11 Win 7

## Which AMP version is affected?

cdn.ampproject.org/v0.js:409 Powered by AMP ⚡ HTML – Version 1496877433269 https://ampbyexample.com/components/amp-video/

**Comment by aghassemi** [comment]
@p2er, so far I have not been able to repo in Win 8.1 / IE11 and video plays fine (see screenshot for versions)
![huu1ps1hvum](https://user-images.githubusercontent.com/2099009/27409034-3c8e6fa6-5694-11e7-89f2-27e2e918f68c.png)

Could we try a few things on your end?
1- Ensure issue is still reproduces for you.
2- Try with InPrivate mode, does it repro there? (Wanna make sure plugins are not interfering)
3- Can you try https://ampbyexample.com/components/amp-audio/ and https://ampbyexample.com/components/amp-pinterest/ to see if it repros there?

Thanks!

**Comment by p2er** [comment]
1. Issue does still occur
2. Tested with inPrivate mode
3. Audio does also show an error. Message reads: Unsupported audio type or broken file path. Pinterest seems to work just fine even though one illegal statement pops up in the console: Illegal replacement of the protocol:  QUERY_PARAM(gclid)​​​

Video:
![ie_11_wind81_video_bug](https://user-images.githubusercontent.com/12771905/27422881-129532b0-5730-11e7-90b6-89c9c44331d9.png)

Audio:
![ie_11_wind81_audio_bug](https://user-images.githubusercontent.com/12771905/27422892-1cbbd230-5730-11e7-9a3b-5c060ef0e6c6.png)

Pinterest:
![ie_11_wind81_pinterest](https://user-images.githubusercontent.com/12771905/27422906-26bbeb3a-5730-11e7-9ce9-14302c913078.png)

This is a dedicated testing PC without plugins. I've added the system information on the left hand side. I'll double check the problem on the IE11 Win81 virtual machine provided by Microsoft: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by p2er** [comment]
Works in VM with Version 11.0.14. I'll try to update the local machine.
<img width="1108" alt="ie_11_wind81_v11 0 14" src="https://user-images.githubusercontent.com/12771905/27426859-4a93fea0-573d-11e7-9cdf-48c2dd165afc.png">

**Comment by p2er** [comment]
I double checked on IE11 Win7 and Win10. No Problem on both machines with updated browsers. Problem seems to be version related and browser is not up to date on IE8.1 machine. Sorry for bothering you guys.

**Comment by aghassemi** [comment]
Glad it was resolved. Thanks for following up to find the root cause.
