### ISSUE TITLE
No error message when amp-iframe within fixed position container doesn't render

### ISSUE THREAD

**Issue by derekcecillewis** [ampproject/amphtml#10033]
## What's the issue?

An `amp-iframe` within a container that uses `position: fixed` will not render. Upon failing to render, no error message is displayed in the console. Additionally, this behavior is not documented anywhere.

## How do we reproduce the issue?

http://jsbin.com/geqotuc/edit?html,output
http://output.jsbin.com/geqotuc

## What browsers are affected?

All browsers

## Which AMP version is affected?

1496877433269

**Comment by cramforce** [comment]
This has nothing to do with `amp-iframe`. It appears that fixed containers (surprisingly to me) have an inherent width of 0 even if their display is block. Adding `width: 100%` to the div fixes it
http://output.jsbin.com/gefavam/quiet

**Comment by cramforce** [comment]
I'm somewhat inclined to close this issue, although we might want to work on the debuggability of stuff like this.

**Comment by kennydurkin** [comment]
@cramforce This certainly does have to do with `amp-iframe`. If you modify @derekcecillewis's original code to use a regular `iframe` instead, the content will render without needing a `width: 100%` property added.

`amp-iframe` | `iframe`
--- | ---
<img width="957" alt="screen shot 2017-06-20 at 11 32 44 am" src="https://user-images.githubusercontent.com/5722340/27341863-8249bd18-55ac-11e7-86a2-94f9a8bcafa5.png"> | <img width="737" alt="screen shot 2017-06-20 at 11 31 53 am" src="https://user-images.githubusercontent.com/5722340/27341856-7db9115e-55ac-11e7-8d84-1da4bbd4e4fd.png">

Although you're right that adding `width: 100%` fixes the issue when using an `amp-iframe`, this is divergent behavior from a regular `iframe` and should be documented somewhere.

**Comment by cramforce** [comment]
@kennydurkin The `amp-iframe` is a red-herring. `amp-image` would behave the same. This is an interaction with `layout=responsive` and the browser behavior for fixed positioned element.

The documentation would basically be "Be aware that fixed positioned elements do not have inherent width. Hence if you put responsive elements into them, they will also have zero width."

**Comment by derekcecillewis** [comment]
Thanks for the clarification. +1 for improved debuggability. Perhaps a warning from the validator for elements that are not commonly zero-width (or nested and zero-width) would be an improvement.

**Comment by dereklewis** [comment]
It may be a good idea to create a tag for issues like these that are common stumbling blocks and compile them into a doc or something?
