### ISSUE TITLE
Whitelist amp-youtube from AMP ads spec 

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#10044]
We were overly restrictive when we created the AMP ad format spec and blocked amp-youtube inside AMP ads.
https://github.com/google/amphtml/blob/master/extensions/amp-a4a/amp-a4a-format.md#amp-extensions-and-builtins

GWD has legitimate use cases for using amp-youtube inside ads. Please whitelist amp-youtube from the AMP ads spec.

**Comment by honeybadgerdontcare** [comment]
Once #10057 hits production, also need to update [markdown](https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/amp-a4a-format.md#amp-extensions-and-builtins).

**Comment by honeybadgerdontcare** [comment]
This is now live in prod.
