### ISSUE TITLE
Sidebar mask seems remaining after side bar is closed. 

### ISSUE THREAD

**Issue by jhlee127** [ampproject/amphtml#10041]
## What's the issue?
When '#link' is appended by clicking hash anchor link ("a href=#link"), and you opened sidebar and closed it by touching empty space, it seems like amp sidebar mask is still on top of the screen and thus preventing from clicking any elements on the screen. If I scroll the page, then I can click things on the screen. It seems to happen only on ios Safari.

## How do we reproduce the issue?

1.Append hash link at the end of the url. For example, https://www.example.com/page1#jumpToHere
#JumpToHere must exists.
2.Open sidebar and close it by touching empty space.
3.If you trying to click any element on the screen. you will realize that something is on top of the screen. Thus, can't click any elements.

## What browsers are affected?
ios Safari

Thank you

**Comment by jridgewell** [comment]
What do you mean by "touching empty space"? Does that mean clicking on the mask to dismiss the sidebar?

Using https://ampbyexample.com/components/amp-sidebar/#setup and following your directions, everything seems to work.

**Comment by jhlee127** [comment]
Yes, Click on the mask to dismiss the sidebar.
Try it using iPhone real device. It is also happening on the link you provided.

1. Go to the link https://ampbyexample.com/components/amp-sidebar/#setup using iPhone.
2. Scroll to the top.
3. Open sidebar
4. Dismiss the sidebar by clicking on the mask.
5. try to open sidebar again.

**Comment by addy5** [comment]
Can re-open this issue, noticing this is still happening under the same conditions as the OP?
