### ISSUE TITLE
AMP.navigateTo throws "Unknown AMP action"

### ISSUE THREAD

**Issue by ciampo** [ampproject/amphtml#10040]
Hello,

we're trying to use the `AMP.navigateTo` action as per the documentation, but it looks like the AMP v0 runtime is not up to date with the docs, and we get `Uncaught Error: Unknown AMP action  navigateTo​​​`

Any chance we can get an up to date version of the runtime?

Thanks,
Marco

**Comment by choumx** [comment]
@ciampo Thanks for filing the issue. The PR that implements the feature was merged last week, so you should expect it to be in dev-channel this week and production next week.

**Comment by ciampo** [comment]
Thanks for your quick answer.

However, it would be helpful if the docs flagged the `navigateTo` action as `not available yet`
