### ISSUE TITLE
Code example for Iframe viewability doesn't work

### ISSUE THREAD

**Issue by ciampo** [ampproject/amphtml#10042]
I've been trying to get the Iframe viewability APIs working inside an `<amp-iframe>` by following the code snippet in the [amp-iframe docs](https://github.com/ampproject/amphtml/blob/bbf2aca64c2ca1fe4eca03b00adcb566d5389ff8/extensions/amp-iframe/amp-iframe.md#iframe-viewability)

After several attempts where I couldn't receive any update, I found the corresponding [test fixture](https://github.com/ampproject/amphtml/blob/218b224af375ef8c9856f1bfeb8b617a094527a2/test/fixtures/served/iframe-intersection.html), copy-pasted the code, and got it working.

The code snippets in the docs seem to have a few problems:
- the `send-intersections` message is not posted to `window`, but to `parent` instead
- the `window.context.location.origin` call in the `message` errors
- the `message` event listener defines a `const listener` function that appears to be never called

**Comment by bpaduch** [comment]
@camelburrito - Can you check out the code sample, as you originally introduced it.

**Comment by camelburrito** [comment]
@zhouyx can you take a look ?

**Comment by bpaduch** [comment]
@zhouyx  - ping.

**Comment by zhouyx** [comment]
Sorry for the late reply. I'll take a look

**Comment by zhouyx** [comment]
@ciampo Thanks for filing the issue. I tried to use the InOb inside iframe and found:

> the send-intersections message is not posted to window, but to parent instead

In our example case, we assume the `postMessage` script is in the created iframe, where `window.parent` is the top window. I'll add a note to postMessage to the AMP window. 

> the window.context.location.origin call in the message errors

I agree it doesn't make sense to check `event.data.origin != window.context.location.origin` here. And `window.context` is not applicable to iframe. I'll remove the check.

> the message event listener defines a const listener function that appears to be never called

True, I'll remove

**Comment by zhouyx** [comment]
@ciampo I created #10042 to improve the documentation.
