### ISSUE TITLE
Re-enable amp-bind integration tests on Saucelabs

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#10053]
```
Chrome 45.0.2454 (Windows 7 0.0.0) amp-bind with <amp-state> "before each" hook for "should not loop infinitely if updates change its src binding" FAILED
	Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
..............................
Edge 15.15063.0 (Windows 10 0.0.0) amp-bind with <amp-list> "before each" hook for "should NOT change src when new value uses an invalid protocol" FAILED
	Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
............................
Chrome 59.0.3071 (Windows 7 0.0.0) amp-bind with <amp-video> "before each" hook for "should change alt when the alt attribute binding changes" FAILED
	Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
............................
Safari 9.1.2 (Mac OS X 10.11.6) amp-bind with <amp-iframe> "before each" hook for "should support binding to src" FAILED
	timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
Safari 9.1.2 (Mac OS X 10.11.6) amp-bind with <amp-list> "before each" hook for "should support binding to src" FAILED
	timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.

**Comment by rsimha-amp** [comment]
Still flaky: https://travis-ci.org/ampproject/amphtml/builds/245881991

**Comment by choumx** [comment]
I think `amp-bind` tests don't run on Saucelabs with Justin's change. These are the errors in the build above (hard to read w/o colors):

> Safari 9.1.2 (Mac OS X 10.11.6) error page "before each" hook for "should show the body in error test" FAILED
	Failed to find errors.

> Safari 9.1.2 (Mac OS X 10.11.6) test extensions loading in multiple orders one extension, extension loads first, all scripts in header FAILED
	Timeout waiting for elements to start loading.

> Chrome Mobile 44.0.2403 (Android 6.0.0) amp-pixel amp-pixel integration test "before each" hook for "should keep referrer if no referrerpolicy specified" FAILED
	Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.

**Comment by choumx** [comment]
Changing this issue to track re-enabling of amp-bind integration tests on Saucelabs.

**Comment by choumx** [comment]
Browser-specific flakiness in `<amp-form>` integration test:
- This only affects Edge and Safari 9, but is fine on Chrome, Firefox and Safari 10.
- Not caused by a race with AmpFormService registration.
- Might have to do with expected user errors.

**Comment by choumx** [comment]
These tests are running on SL.
