### ISSUE TITLE
amp-recaptcha shell extension integration test

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#10059]
Follow on from #9678. Once the full extension is implemented. We should do integration tests.

cc @jasti

**Comment by torch2424** [comment]
cc @lannka let's use this existing issue to track an integration test for recaptcha.

If you would be so kind, I know you said you wanted to share how you think we should do an integration test, so documenting here would be great if you have the time 😄 

Also, I think we can add this integration test after we get users testing it out in experimental, just in case we need to make changes.
