### ISSUE TITLE
travis_start_sauce_connect failed

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#10052]
```
Extracting Sauce Connect
Waiting for Sauce Connect readyfile
20 Jun 19:14:08 - Sauce Connect 4.4.7, build 3628 a0f5d6a -dirty
20 Jun 19:14:08 - Using CA certificate bundle /etc/ssl/certs/ca-certificates.crt.
20 Jun 19:14:08 - Using CA certificate verify path /etc/ssl/certs.
20 Jun 19:14:08 - Starting up; pid 5633
20 Jun 19:14:08 - Command line arguments: sc-4.4.7-linux//bin/sc -i 23659.2 -f sauce-connect-ready-31662 -l /home/travis/sauce-connect.log 
20 Jun 19:14:08 - Log file: /home/travis/sauce-connect.log
20 Jun 19:14:08 - Pid file: /tmp/sc_client-23659.2.pid
20 Jun 19:14:08 - Timezone: UTC GMT offset: 0h
20 Jun 19:14:08 - Using no proxy for connecting to Sauce Labs REST API.
20 Jun 19:14:08 - Started scproxy on port 39021.
20 Jun 19:14:08 - Please wait for 'you may start your tests' to start your tests.
20 Jun 19:15:15 - error querying from https://saucelabs.com/rest/v1/amphtml/tunnels/398f2d5b713346c0a646f0670bcbdd52. HTTP status: 504 Gateway Time-out
20 Jun 19:15:15 - Sauce Connect could not establish a connection.
20 Jun 19:15:15 - Please check your firewall and proxy settings.
20 Jun 19:15:15 - You can also use the sc --doctor to launch Sauce Connect in diagnostic mode.
20 Jun 19:15:15 - Goodbye.
readyfile not created
~/build/ampproject/amphtml
The command "eval travis_start_sauce_connect " failed. Retrying, 2 of 3.
```

**Comment by rsimha-amp** [comment]
https://status.saucelabs.com/ doesn't suggest any outages. I've restarted the failed jobs on master to see if this is a transient error.

**Comment by rsimha-amp** [comment]
Aha, there is an outage according to https://status.saucelabs.com

> Investigating - We are having intermittent failures with our web interface, starting tunnels, and our REST API. We are investigating. 
> Jun 20, 13:00 PDT

Closing this for now. I'll reopen this if the outage is over and we're still having trouble connecting.

In the meantime, there will be redness on master :(

**Comment by rsimha-amp** [comment]
Update: 

> Update - Our service continues to have difficulties loading pages of the web interface, starting tunnels, and responding to requests using our REST API. We’re taking remedial action. 
> Jun 20, 13:40 PDT

**Comment by rsimha-amp** [comment]
Fixed.

> Resolved - Our services have fully recovered and are operational. All users of Sauce Connect should restart their tunnels now. 
> Jun 20, 14:08 PDT

> Monitoring - Our services are recovering. We are monitoring them closely. 
> Jun 20, 13:56 PDT

Green in https://travis-ci.org/ampproject/amphtml/jobs/245114887
