### ISSUE TITLE
AMP Shadow with amp-ad and amp-user-notification

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#10075]
When using amp-ad in combination with amp-user-notification in a PWA (both React and Polymer), ads are not loading.
 
Reproducing the error in Polymer
Sample  [here](https://news-amp-1ec10.firebaseapp.com/article/chrome/3-reasons-why-chromebooks-might-be-good)

 
![error](https://user-images.githubusercontent.com/820891/27397811-7c9741c0-56af-11e7-9117-ef415df5975d.png)
 
Reproducing the error in React
Sample [here](https://news-amp-react.firebaseapp.com/content/1.amp.html), and I got:
![react-error](https://user-images.githubusercontent.com/820891/27397825-8ef4ba0a-56af-11e7-92da-bc215eda583a.png)

 

 

 
AMP in a PWA without any framework just using AMP Shadow:

It works when type of ad is a9, sample [here](https://news-amp-shadow.firebaseapp.com/articles/1.html).
It works when type of ad is doubleclick, sample [here](https://news-amp-shadow.firebaseapp.com/articles/2.html).

@rudygalfi FYI

**Comment by jasti** [comment]
Probably need @dvoytenko's help for this but assigning to @lannka incase he is able to debug.

**Comment by rudygalfi** [comment]
Could we consider investigating this a bit during the current sprint and working on it next sprint?

**Comment by jasti** [comment]
@dvoytenko would you be able to help please?

**Comment by dvoytenko** [comment]
Yes
