### ISSUE TITLE
Logos not showing up in Google search carousel, structured data is valid.

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#10077]
We've got several sites where the logos are no longer showing up in search results and the name is inconsistent (sometimes it take the top level name key from structured data sometimes it takes publisher.name).  

![image](https://user-images.githubusercontent.com/524856/27402766-a4a60d64-567c-11e7-8f25-2d7926146449.png)

AMP bench results for page http://ampbench.appspot.com/validate?url=http%3A%2F%2Famp.kob.com%2Falbuquerque-news%2Fcajete-fire-85-percent-contained%2F4519659%2F

**Comment by jridgewell** [comment]
@jpettitt: These are Google Search issues, please report at https://goo.gl/utQ1KZ.

**Comment by jpettitt** [comment]
Figured it out - where do I file bugs for the structured data validator?  (it says things are ok even if robots.txt is blocking bot from loading the images).  This is inconsistent behavior as the page image (blocked by the same robots.txt) is appearing.

**Comment by jridgewell** [comment]
Likely the same Google forum, I'm not actually sure.
