### ISSUE TITLE
Add new "Device Category" variable

### ISSUE THREAD

**Issue by SchnWalter** [ampproject/amphtml#10082]
## What's the issue?

I would like to submit a feature request for a new "Device Category" [variable](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#device-and-browser).

It would be nice to have a "Device Category" with `desktop`, `tablet` and `mobile` as variables (and maybe more? `braile`?).  Google Analytics has a way to determine the "Device Category", but I'm not sure how that works or how reliable it is.

## Why this new variable?

This variable could be useful in various situations, for example, a `${deviceCategory}` variable would allow loading of different `amp-analytics` configuration JSON.  And once you can serve different analytics configuration you could have different `verticalBoundaries` for mobiles and desktops (the 10% scroll boundary means nothing on Full HD displays but it is huge on mobiles).

```
<amp-analytics config="https://example.com/analytics.config.json?device=${deviceCategory}"></amp-analytics>
```

**Comment by lannka** [comment]
@SchnWalter is there kinda industry-wise standard of this categorization? Some analytics vendor might go into one level deeper including the OS info. 

Most likely, these are all derived from user agent string, so I think it should be the analytics vendor's job to categorize them in what ever way they like.

**Comment by SchnWalter** [comment]
I'm not aware of anything on those lines, as far as I know ,this is something esoteric, some sort of black magic performed by the analytics vendors and  you can find some libraries that try to attempt such a thing, but it is prone to a lot of errors and updates over time.

I was hoping for a variable like this in order to have control over various things, but I guess that I could use the viewport size in some sort. Any ideas how I could control the settings for `<amp-analytics>` based on the viewport width?

Thank you for your feedback. I think that we can close this.

Have a great weekend,
Walter S.

**Comment by lannka** [comment]
@SchnWalter can you just send the [viewport width](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#viewport-width) along with the analytics pings? What extra client logic you want to have for different width?

**Comment by SchnWalter** [comment]
I was hoping to have different Page Scroll boundaries depending on the screen width (which in also affects the total height of the page).

For example, triggering an event for every 15% of the page the user has scrolled doesn't really make sense on desktop... but with long content, it sure helps on mobile devices.

If for example, the `media` attribute would control which `amp-analytics` component is used, then you would see something like this (just look at the `verticalBoundaries` section):

#### For devices up to a width of 799px
```
<amp-analytics type="VENDOR" media="(max-width: 799px)"><script type="application/json">
{
  "vars": {
    "account": "UA-XXXXXX-X",
  },
  "triggers": {
    "trackPageview": {
      "on": "visible",
      "request": "pageview"
    },
    "trackPageScroll": {
      "on": "scroll",
      "scrollSpec": {
        "verticalBoundaries": [
          15,
          30,
          45,
          60,
          75,
          90
        ]
      },
      "request": "event",
      'sampleSpec': {
        'sampleOn': '${clientId(cookieName)}',
        'threshold': 1
      },
      "vars": {
        "eventCategory": "Page Scroll",
        "eventAction": "Scroll",
        "eventLabel": "Scrolled to ${verticalScrollBoundary}%"
      }
    }
  }
}
</script></amp-analytics>
```

#### For devices with a width of 800px or larger
```
<amp-analytics type="VENDOR" media="(min-width: 800px)"><script type="application/json">
{
  "vars": {
    "account": "UA-XXXXXX-X",
  },
  "triggers": {
    "trackPageview": {
      "on": "visible",
      "request": "pageview"
    },
    "trackPageScroll": {
      "on": "scroll",
      "scrollSpec": {
        "verticalBoundaries": [
          25,
          50,
          75
        ]
      },
      "request": "event",
      'sampleSpec': {
        'sampleOn': '${clientId(cookieName)}',
        'threshold': 1
      },
      "vars": {
        "eventCategory": "Page Scroll",
        "eventAction": "Scroll",
        "eventLabel": "Scrolled to ${verticalScrollBoundary}%"
      }
    }
  }
}
</script></amp-analytics>
```

**Comment by lannka** [comment]
Would you think of any other triggers that will find this useful?
Otherwise, I think this can be an enhancement to the scrollSpec.

Also, is the value to save some pings? From analytics' perspective, we can generate same report without the proposed new spec.

**Comment by lannka** [comment]
Closing this for now, since the discussion went in different direction. @SchnWalter if you think a `media` selector in amp-analytics is helpful, please open a separate proposal.
