### ISSUE TITLE
amp-iframe sporadically doesn't load page

### ISSUE THREAD

**Issue by keepitsimple** [ampproject/amphtml#10088]
I found a weird bug. I did a bunch of tests and I use similar amp-iframe calls on other pages of the site and it works right. But the *same* code for amp-iframe doesn't work on this particular page.

**The problem is amp-iframe doesn't load iframe it just shows placeholder. I tried to use different src sources include external sites; but it doesn't mater**

Steps to reproduce: 
1. Open m.domino.com via mobile browser of mobile view in Google Chrome
2. Click on the "domino" logo (it has drop down) in the header
3. Click back button on the opened page (https://ma.domino.com/content/select)

This page uses absolutely similar AMP-IFRAME code which works on other pages.

**Comment by jridgewell** [comment]
This is a CSS issue:

- `<amp-iframe layout=fill>` implies the iframe will take the space of its parent
- The parent element only has a `height`, but no `width`
- So, the iframe collapses (0 width)
- The placeholder is rendered, which has a defined width and height (so it shows)

**Comment by keepitsimple** [comment]
Thank you!
