### ISSUE TITLE
Per-committer Sauce Tokens

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#10086]
We might be able to alleviate the SauceLabs strain by using per-committer (at least per-core-committer) Sauce tokens.

When it's a PR build, based on who commits, we use their tokens to run integration tests. When it's a branch build, we can use the official tokens, etc.

**Comment by cramforce** [comment]
@rsimha-amp Would there be a way for the saucelabs integration to pick a JWT token based on the github user name and fall back to the default for everyone else?

**Comment by rsimha-amp** [comment]
@cramforce, from reading https://saucelabs.com/pricing, my initial feeling is that it's difficult, but technically possible to do this: 

1. Everyone on the team will first need to:
a. Purchase an individual plan ($149 / month)
b. Encrypt their token
c. Check it into a common file containing everyone's token
2. `pr-check.js` can then programmatically look up which JWT token to use for a given PR.

I'm happy to do the stuff in 2, but I wonder if there's an easier way around 1 without each person on the team having to buy a plan and set it up.

**Comment by jridgewell** [comment]
Can't each person just use an open-source token?

**Comment by rsimha-amp** [comment]
Open source tokens should work. https://saucelabs.com/beta/signup/OSS/None

It will still need everyone to create a token and add it to a file, but it's a one time thing.

**Comment by cramforce** [comment]
@rsimha-amp Do you want to add the first token and than we can crowdsource the rest?

**Comment by rsimha-amp** [comment]
Update: I've been hacking away at this problem for a while today, and ran into various issues.

1. All scripts that we can possibly run on travis are run *after* JWT initialization is done, so adding the per-user logic to a script in `before_install`will not work.
2. The way to determine the committer's email address on a local git branch is `git log -1 $TRAVIS_COMMIT --pretty="%cE"`. Unfortunately, for Travis PRs, the value I'm seeing printed out is `noreply@github.com`.
3. Assuming we figure out a solution to 2, it might be possible in theory to put the logic in `.travis.yml`, but I'm not convinced this will elegantly scale for all google-internal committers.
4. It seems like it should be possible to skip token encryption via JWT, and simply use an obfuscated (but not encrypted) token for each user.

I'll continue investigating this next week in the hope that I find a workable solution to use a per-user token. Right now, item 4 above seems the most promising.

/cc @erwinmombay @cramforce @jridgewell @choumx

**Comment by rsimha-amp** [comment]
Per Sauce labs, from a ticket we've opened with them:

> The VM pool is common for all our users and you should not notice any difference when tests are run from different accounts

This could mean that there's little to no advantage to be gained from pursuing the idea in this issue. I'll update this thread with the resolution from the sauce labs ticket. Meanwhile, @cramforce, it should still be possible to implement item 4 above, so let me know if you think it's worth putting in place anyway.

**Comment by rsimha-amp** [comment]
I just tested this in https://travis-ci.org/ampproject/amphtml/jobs/248019758, and it looks like the overridden sauce tokens in #10116 are not persisting. I think the env vars set by the `node` process isn't visible to the subsequent sauce connect process. Investigating.

**Comment by rsimha-amp** [comment]
I managed to properly export the per-user credentials correctly, and unfortunately, they now won't work for PRs because they aren't set up with JWT.

From https://docs.travis-ci.com/user/sauce-connect/:

> due to security restrictions, the Sauce Labs addon is not available on pull request builds unless you use the JWT Addon

I'm going to change the way we store the sauce access key from base 64 encoded to `travis encrypt`ed. 

There is hope :)

**Comment by rsimha-amp** [comment]
Unfortunately, this seems to have hit a dead end, since Travis doesn't support dynamically setting a JWT secure key. See https://github.com/travis-ci/travis-ci/issues/8007#issuecomment-313196927

**Comment by jridgewell** [comment]
Why do we need a JWT key?

**Comment by rsimha-amp** [comment]
@jridgewell https://github.com/ampproject/amphtml/issues/10086#issuecomment-311768408

**Comment by cramforce** [comment]
@rsimha-amp Could you roll back the code and the credentials related to the non-JWT approach?

**Comment by rsimha-amp** [comment]
Reopening this to see if https://blog.travis-ci.com/2017-09-12-build-stages-order-and-conditions lets us do what we want.

**Comment by rsimha-amp** [comment]
That was a dead end, as were a few other approaches. This is essentially impossible due to a combination of https://github.com/travis-ci/travis-ci/issues/8007 and https://github.com/travis-ci/travis-ci/issues/7223. We can't use a non-JWT means of setting up per-user sauce labs tokens, and Travis' JWT implementation supports exactly one token called `SAUCE_ACCESS_KEY`, which prevents us from declaring multiple secrets and using one of them.
