### ISSUE TITLE
Allow amp-animation in the AMP ad spec 

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#10093]
amp-animation is allowed to be used in an AMP page but doesn't validate when used as an ad. Can we please whitelist it and update markdown when in prod?

CC @Gregable @ampproject/a4a

**Comment by honeybadgerdontcare** [comment]
@gregable fyi we usually remove html_format for cases where it is intended for both formats. if you don't get to it by end of next week I'll look into it.

**Comment by Gregable** [comment]
This is fixed. I'll update the issue when it's released.
