### ISSUE TITLE
Create lint rule that enforces that object literal shape passed to dict

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#10094]
Lets create a lint rule that requires that `dict` is called without argument or with an object literal that has all keys quoted.

Good: `dict()`, `dict({'test': true})`
Bad: `dict()`, `dict({test: true})`
Bad: `dict()`, `dict(nonObjectLiteralExpression)`

**Comment by erwinmombay** [comment]
first 2 cases should be super easy to implement, 3rd case where its a reference is a bit more difficult if theres multiple indirection
