### ISSUE TITLE
Text coloring in Travis logs no longer works

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#10117]
Logs from PR run (with colored text): https://travis-ci.org/ampproject/amphtml/jobs/245941759
Logs from when the same PR was merged to master (no colored text): https://travis-ci.org/ampproject/amphtml/jobs/245989731

I just filed a [bug](https://github.com/travis-ci/travis-ci/issues/7967) in the `travis-ci` repository. This is for tracking on the `ampproject/amphtml` side.

**Comment by faceyspacey** [comment]
Having the same issue.

**Comment by rsimha-amp** [comment]
This is now fixed on the Travis side.
