### ISSUE TITLE
using input-debounced or change events got event.value null when the input is type search

### ISSUE THREAD

**Issue by mauricionr** [ampproject/amphtml#10135]
## What's the issue?

I was trying to use `input-debounced` or `change` events but the `event.value` is always null when the input is `[type="search"]`.

I don't know if this issue is a bug or a feature request

## How do we reproduce the issue?

In this repo https://github.com/mauricionr/pwamp

Thanks!

**Comment by aghassemi** [comment]
@mauricionr looks like a bug to me. Not sure what makes `[type=search]` special, we will investigate.

**Comment by mauricionr** [comment]
@aghassemi the documentaion said that a few types are currently supported

https://github.com/ampproject/amphtml/blob/master/spec/amp-actions-and-events.md#input-elements

this other type make a better user exeprience on mobile.

i guess the other types also should support these events

types like

`[type="tel"]`
`[type="number"]`
`[type="email"]`
`[type="search"]`
`[type="date"]`
`[type="datetime"]`

what do you think?

Thanks!

**Comment by cvializ** [comment]
I am able to reproduce. Initial inspection shows that it's a bind issue, but I wasn't able to find anything after a quick look. I can keep looking, and @choumx maybe you can look too and see if your bind expertise notices anything that might cause `type="search"` to give a null value while `type="text"` gives the correct value.

**Comment by ericlindley-g** [comment]
Pinging this for @choumx

**Comment by choumx** [comment]
Sorry just saw this. Needs to be whitelisted in `action-impl.js`. Quick fix coming up. 😃
