### ISSUE TITLE
Make test-example-validation.js hermetic

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#10154]
To avoid breakages (and catch offending bugs earlier) due to validator releases, e.g. #10152.

Context: https://github.com/ampproject/amphtml/blob/5bb8318aefabd4238965494b82cc05a770def122/test/integration/test-example-validation.js#L21

/cc @Gregable @cramforce

**Comment by rsimha-amp** [comment]
Looks like #9002 was opened to cover the same use case. @choumx, I'll assign it to you and let you dupe one, or fix both with your PR :)
