### ISSUE TITLE
Validator mistakenly states amp-bind is an unused import in autosuggest.amp.html

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#10152]
In the `test/integration/test-example-validation.js` test, the test fails with the following error

```
Chrome 58.0.3029 (Mac OS X 10.12.5) example autosuggest.amp.html should validate FAILED
    AssertionError: expected 'EXTENSION_UNUSED amp-bind' to equal ''
```

but that page does use bind. It appears that this is an issue with the validator.

**Comment by keithwrightbos** [comment]
This is preventing merging.  Could we temporarily disabled the test?

**Comment by choumx** [comment]
Including an `<amp-state>` element fixes the error, though this shouldn't be necessary. 

Also filed #10154 to make this test fetch the local validator build instead of from the CDN.

**Comment by Gregable** [comment]
My understanding is that all `amp-bind` uses require an `<amp-state>` as the initial state. Is that incorrect?

**Comment by Gregable** [comment]
Regarding the test, we can't do much about it if it's using the deployed validator, so I would disable until #10154 is fixed.

**Comment by Gregable** [comment]
Created https://github.com/ampproject/amphtml/pull/10159 as a fix, as I understand it.

**Comment by Gregable** [comment]
Closing. I'll update the issue when it's released.
