### ISSUE TITLE
Feature Request: Add touch class to body for touch enabled devices.

### ISSUE THREAD

**Issue by gurmukhp** [ampproject/amphtml#10157]
## What's the issue?

It's currently not possible to change the layout of a component dependant on the device supporting touch or not. 
Adding a class to the body like 'touch-enabled' would solve this.

```
// Touch enabled components have a red background color.
.touch .content-module {
  background-color: red;
}

// Non-touch enabled components have a blue background color.
.content-module {
  background-color: blue;
}
```

**Comment by jridgewell** [comment]
We have a `.amp-mode-mouse` and a `.amp-mode-touch` class on the body. Is there a problem with these?

**Comment by gurmukhp** [comment]
Thanks Justin, I wasn't aware that was already implemented. :)
