### ISSUE TITLE
Feature request: Expando

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#1017]
A way to click/tap on a button and expose some content that's hidden from view by default. Also, can this trigger an async request to fetch the content that would be populated, including sizing information?

**Comment by maxhartshorn** [comment]
+1 This would be a great feature to have. I've seen this on HuffPo, QZ, NYT, and we're currently  implementing it on our site. Typically there are related links served below a "Read More" button. Giving users who are on the fence about reading an article a chance to "bail" into related content seems to be a good way to drive recirculation on mobile.

**Comment by ds0001** [comment]
:+1: This would be great to have parity with our current NYT mobile web implementation.

**Comment by Nemo64** [comment]
One thing to consider is that this might also allow for pulldown/drawer menus as they are common in the mobile web.

What I would also wish for is the capability to toggle 2 elements at the same time to switch between 2 content areas.... like before/after images.

It might also be needed to jump to the expanded element after the toggle is activated.

Another thing this element might need to cover is an accordion. Basically that every expanded element in a group collapses when another one opens, roughly similar to the [Bootstrap accordion](http://getbootstrap.com/javascript/#collapse-example-accordion).

Also: when will resources inside the collapsed content be loaded? They might be placed far apart (not sure why anyone would do that but depending on the implementation it might be possible and someone will do it). I suggest when the toggle link/element itself is inside the view but after ever other visible resource is loaded. It might be even more complicated than that but it might also be not worth optimizing (don't know).

**Comment by stephanfowler** [comment]
:+1: to this proposal. For reasons [detailed here](https://github.com/ampproject/amphtml/issues/827), this seems to provide a missing building block for expandable menus. (Which in our case need to make an async request for their content.)

**Comment by Markenson** [comment]
+1

**Comment by rudygalfi** [comment]
I would say this is partially addressed by #1849 (amp-accordion). Obviously there are many directions to go with enhancements, but I'll call out two things already mentioned in this thread to figure out if we should open separate tracking issues for them:

* Ability to dynamically fetch the data to be displayed when an amp-accordion header is clicked (just filed #3459 to cover this)
* After reaching the end of some text, there's a (possibly overlaid) button that invites the user to "Read More". Upon clicking on this, more text is displayed and the button goes away. It's similar to how amp-accordion works, yet different. I'd like to know if amp-accordion will indeed cover this. If yes, we should introduce a good example on ampbyexample.com to demonstrate the pattern. If not, we should think if this is possibly covered by #3459 or needs to be considered separately. @ericlindley-g

**Comment by rudygalfi** [comment]
@ericlindley-g owns the next follow up here. Maybe it makes the most sense to close this and open up the ABE issues stated above?

**Comment by ericlindley-g** [comment]
Never followed up on this, but ABE has that example at the link below, so we should be all set: https://ampbyexample.com/components/amp-accordion/
