### ISSUE TITLE
AMP Youtube Customisation.

### ISSUE THREAD

**Issue by imparvez** [ampproject/amphtml#10189]
`amp-youtube` provide us with the basic look and feel of youtube video on our AMP pages. 
Is there any way where we can implement 'Click-to-play' icon on youtube video, the same we can see in 'Click to play overlay for amp video'
https://ampbyexample.com/advanced/click-to-play_overlay_for_amp-video/

This UX feature is a new ongoing trend and beautifies the content pages also.

**Comment by SchnWalter** [comment]
It should work exactly the same.

**Comment by SchnWalter** [comment]
Here's a quick example I've created from the one you have sent.

http://plnkr.co/edit/2AWYzAnJsUstBQzueVyx?p=preview

You might want to ad an extra fade-in animation to the `<amp-youtube>` element so that it doesn't get loaded before the "preview" image.

**Comment by aghassemi** [comment]
@imparvez We are considering to support custom overlays for `start` and `end` states (see https://github.com/ampproject/amphtml/issues/8971#issuecomment-298061119) to make click-to-play UX easier to implement ( and enable custom overlay when video ends, paused, etc...).

For now, @SchnWalter's approach should work.

**Comment by imparvez** [comment]
@aghassemi we've used amp-youtube site wide now, implementing `amp-video` is kinda re-work to do on each template, which is a prime reason for emphasizing more on `amp-youtube`.
