### ISSUE TITLE
AMP error reporting for publishers

### ISSUE THREAD

**Issue by tiendt** [ampproject/amphtml#10199]
AMP runtime generates 2 types of errors:
Dev errors, which are to be fixed by AMP project. 
User errors, which are to be fixed by publishers, such as a mis-config of an AMP component etc. 

Both errors right now are reported back to AMP project’s own server for debugging purpose. Dev errors are checked during our release process, and user errors are generally paid less attention as we are not really the designed audience. 

As of today, we’re seeing a QPS of 250/s for user errors at peak time from valid AMP pages served on CDN. Here is the graph with a sampling rate of 1/100, and here is the top error messages. However, as of now, publishers are fully blind about those errors, though they belong to them. 
This doc is proposing a way for publishers to collect those user errors so that they can detect and fix bugs earlier. This will overall help publishers to make higher quality AMP pages hence improve the whole ecosystem.

**Comment by lannka** [comment]
See former discussions: #6415
