### ISSUE TITLE
Allow for Printing of AMP Page

### ISSUE THREAD

**Issue by jessanastasio** [ampproject/amphtml#10191]
Having support for an `amp-print` component that triggers `window.print();` would be extremely useful. (this may not seem useful for mobile, but for sites that are entirely AMP the print button would be great for desktop)

**Comment by aghassemi** [comment]
Sounds good to me. We may expose this as an action (`AMP.print()`) instead of a new component however.

**Comment by jessanastasio** [comment]
awesome!!

**Comment by mrjoro** [comment]
hi @jessanastasio; @aghassemi mentioned that you were thinking about taking on this issue; thanks!  I've invited you to join the AMP Project on GitHub; once you accept that we can assign this issue to you.

Let us know if you need any help getting started.

**Comment by jessanastasio** [comment]
thanks @mrjoro! just accepted the invite and forked the project - you can go ahead and assign the issue to me 👍

**Comment by jridgewell** [comment]
Closed by #10319

**Comment by SchnWalter** [comment]
I was looking into the PR and I think that `onbeforeprint` event should also be dealt with.

Using a print shortcut `CTRL+P` or clicking on a menu option `File -> Print`, you will print a page that has no lazy-loaded components (all `amp-img` tags are missing). Binding to an event that happens before the print itself, might allow the loading of lazy-loaded components.

Thanks for the feature.
