### ISSUE TITLE
amp-bind: Binding to amp-img[src] also requires [srcset] on cache

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#10207]
When using amp-bind for changing the `src` value of `amp-img`, the page does not work on cache, probably because the cache can't change the src file name, this happens also when using absolute URLs.
In order to replicate open: 
[amp version](https://chiara-ampbyexample.appspot.com/amp-bind-url-images.html)
[cached version](https://chiara--ampbyexample-appspot-com.cdn.ampproject.org/c/s/chiara-ampbyexample.appspot.com/amp-bind-url-images.html)

@choumx @ericlindley-g  FYI

**Comment by kul3r4** [comment]
Update on this:
I updated the samples above by binding on srcset as well (more than src) and it works on cache. Will update the documentation.

**Comment by choumx** [comment]
Strange, that shouldn't be necessary. Thanks for reporting this.

**Comment by bandral0** [comment]
having the same issue, amp-bind is not updating amp-img for cached version, but works on non-cached version.
Is this still an ongoing issue?

**Comment by choumx** [comment]
@bandral0 Should be fixed. Do you have a link to a test page?

**Comment by bandral0** [comment]
https://www.google.ca/amp/s/trustedpros.ca/amp/on/toronto/basement-renovations - if you click on the "Get a Quote" the captcha image below should change to the set image

e.g 
"<a class="get-quote" on="tap:AMP.setState({user_company: 'GTA Siding &amp; Aluminum ', user_id: '137945', claim_class: 'claim-text-hide', verification_token: '188153C0-17AB-4C6F-8CEF-F3CFE85AB759', captcha_image: '**https://trustedpros.ca/images/verify-img/09yaroxv58lgu11y.jpg'**}),req-a-quote">Get a Quote</a>"

**Comment by choumx** [comment]
Seems to work for me. I see the captcha image:
```html
```

**Comment by bandral0** [comment]
The image which is visible is the default image but it should load the image which is set via amp-bind ==> AMP.setState

Below is the code to set AMP state for “captcha_image”
<a class="get-quote" on="tap:AMP.setState({user_company: 'GTA Siding &amp; Aluminum ', user_id: '137945', claim_class: 'claim-text-hide', verification_token: '188153C0-17AB-4C6F-8CEF-F3CFE85AB759', captcha_image: 'https://trustedpros.ca/images/verify-img/17omsx352amsazpe.jpg'}),req-a-quote">Get a Quote</a>

It works fine when you visit the amp page directly. i.e https://trustedpros.ca/amp/on/toronto/basement-renovations

Another example, if you look at the image the green highlighted part is the image which should appear (set via AMP.setState) but the image marked in red (which is default) is appearing instead.

[cid:image001.png@01D4BD7E.6FCE3160]


On Tue, Feb 5, 2019 at 5:35 PM William Chou <notifications@github.com<mailto:notifications@github.com>> wrote:

Seems to work for me. I see the captcha image:

**Comment by choumx** [comment]
Ah, it's the same root issue as OP. This happens because there's no `[srcset]` binding. The amp-img's `src` attribute is changing as expected, but the browser ignores it in favor of `srcset`:

> When binding to [src], make sure you also bind to [srcset] in order to make the binding work on cache.

https://www.ampproject.org/docs/reference/components/amp-bind#element-specific-attributes

We should change amp-img to remove `srcset` attribute when mutating `src` if there's no `[srcset]` binding.

**Comment by bandral0** [comment]
That fixed it, thanks a lot!

**Comment by choumx** [comment]
Related: #11470. Looks like this regressed #16404.
