### ISSUE TITLE
amp-video with track generate a crossdomain error

### ISSUE THREAD

**Issue by djavet** [ampproject/amphtml#10209]
## What's the issue?
I want to play a video with subtitle and receive a crossdomain error on <track> despite Access-Control-Allow-Origin:* when I load the page. 
The video plays, but not the subtitles.

## How do we reproduce the issue?
Go on https://gamp.silium.ch/video-crossorigin.html

1. load the page
2. Open the console and look at the error:
Text track from origin 'https://media-acp.swissinfo.ch' has been blocked from loading: Not at same origin as the document, and parent of track element does not have a 'crossorigin' attribute. Origin 'https://gamp.silium.ch' is therefore not allowed access.

## What browsers are affected?
Tested on Chrome Version 59.0.3071.115 (Official Build) (64-bit)

## Which AMP version is affected?
 Version 1498686280171 https://gamp.silium.ch/video-crossorigin.html
It never worked
![capture](https://user-images.githubusercontent.com/5485253/27741730-60e1228a-5db6-11e7-81c6-48d41c854be6.PNG)

**Comment by aghassemi** [comment]
Thanks for reporting this @djavet. Prioritized.

**Comment by mrsufgi** [comment]
maybe adding crossorigin="anonymous" to the video HTML element could help,
I'll try fixing it and post my findings asap :)

**Comment by aghassemi** [comment]
@mrsufgi I think we can just expose `crossorigin` as an attribute on `amp-video` (requires validation rule changes) and propagate it to the underlying `video` then it is up to the publisher to set it properly (they may want to set it with `use-credentials` or `anonymous` depending on their use-case)

**Comment by aghassemi** [comment]
@djavet fix will be in production in 2 weeks. You would need to add `crossorigin` attribute to your `amp-video` tags to make it work then.

**Comment by djavet** [comment]
Brillant! Thank you. Impatient to test it. Doesn't the version of JavaScript change?

**Comment by aghassemi** [comment]
Version stays the same, AMP does continuous releases on a single version.
