### ISSUE TITLE
TypeError: Cannot call method 'replace' of undefined

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#10227]
Error rate is high, happening in latest canary: 1498863866481
```
TypeError: Cannot call method 'replace' of undefined
    at https://cdn.ampproject.org/rtv/001498863866481/v0.js:89:51
    at https://cdn.ampproject.org/rtv/001498863866481/v0.js:25:87
```
```js
export function extractClientIdFromGaCookie(gaCookie) {
  return gaCookie.replace(/^(GA1|1)\.[\d-]+\./, '');
}
```

**Comment by aghassemi** [comment]
@lannka We are either hitting the 10000 timeout which would result in an `undefined` for `cid.get` (we should return `''` in the `catch` I believe) or somehow `getExternalCid_` is returning `undefined`. I don't think it is related to optout, if user is opted out, we always return empty string.

**Comment by aghassemi** [comment]
for now reverting 1% back to the version without cid but keeping optin canary until we can look into this issue (cid stuff should not have caused new errors)
