### ISSUE TITLE
Carousel doesn't support auto height

### ISSUE THREAD

**Issue by lucanovera** [ampproject/amphtml#10238]
## What's the issue?

I'm trying to create a carousel of news items but the carousel requires fixed height and the text inside the items is dynamic and height varies. I also tried using simply a "overflow: x" but then the images don't load because they're outside the viewport when the page loads.

## How do we reproduce the issue?

An example of what i'm trying to develop.
http://jsbin.com/qeyobofujo/edit?html,output

## What browsers are affected?

All.

## Which AMP version is affected?

All.

## Related
#5226
#5977

**Comment by aghassemi** [comment]
@lucanovera please subscribe to https://github.com/ampproject/amphtml/issues/6906 which is the same feature request.


Closing as dup of https://github.com/ampproject/amphtml/issues/6906
