### ISSUE TITLE
[Question] What's the easiest way to update AMP Cache for one page

### ISSUE THREAD

**Issue by mauricionr** [ampproject/amphtml#10239]
I'm trying to update the cache for one page, it's really needed gerenerate a RSA key?

the update-ping don't update the cache?

my first try was `https://cdn.ampproject.org/c/s/myamppage/amp`
and the second try was `https://example-com.cdn.ampproject.org/c/s/example.com/p/amp?amp_action=flush`

Thanks!

**Comment by aghassemi** [comment]
@mauricionr  Have you tried `https://cdn.ampproject.org/update-ping/c/s/myampsite.com/amppage` ? `update-cache` requests signature but `update-ping` does not.

**Comment by mauricionr** [comment]
@aghassemi i've tried with this one `https://cdn.ampproject.org/update-ping/c/s/myampsite.com/amppage`
and i got redirected to `https://cdn.ampproject.org/c/s/myampsite.com/amppage`

how long take to update?

the docs said this approach will return status 204 but i got 200

**Comment by mauricionr** [comment]
@aghassemi i got 204, but i'm still getting cached content in the search results

```
curl -i https://example-com.cdn.ampproject.org/update-ping/c/s/example.com/amp
HTTP/1.1 204 No Content
Content-Type: text/html; charset=ISO-8859-1
X-Content-Type-Options: nosniff
Date: Mon, 03 Jul 2017 19:13:04 GMT
Server: sffe
Content-Length: 0
X-XSS-Protection: 1; mode=block
Alt-Svc: quic=":443"; ma=2592000; v="39,38,37,36,35"
```

what's the diff bettewen `update-cache` and `update-ping`?

**Comment by aghassemi** [comment]
Number of `update-ping` requests you can make it limited but `update-cache` allows for higher request rates because the requests are signed.

Also AFAIK, neither should take more than 4-5 minutes before cache is update.

**Comment by mauricionr** [comment]
weird @aghassemi, is taking more than 4-5 minutes :thinking:

**Comment by honeybadgerdontcare** [comment]
It'd be helpful to have an actual example of what you're seeing (stale cache) and what you wish you were seeing (fresh cache or origin). If you don't want to post it here, could you provide it in a PM over [slack](https://amphtml.slack.com/)?

/cc @Gregable since I'm mostly OoO

**Comment by honeybadgerdontcare** [comment]
@mauricionr could you message me on slack with the url

**Comment by mauricionr** [comment]
Thanks @honeybadgerdontcare i will send a PM!

**Comment by mauricionr** [comment]
@honeybadgerdontcare sorry the delay, i've sent a PM to you!

**Comment by honeybadgerdontcare** [comment]
Thanks for the url. Opened b/63304047 internally for tracking.

**Comment by mauricionr** [comment]
@honeybadgerdontcare we change our cache control approach and the cache was updated

Thanks!!

**Comment by mauricionr** [comment]
Thanks @aghassemi

**Comment by ashishindiwork** [comment]
@mauricionr i have same issue can you please provide me url for update google amp cache. i have used the same urls as per above discussion, but now page is not showing in amp now error is showing "sorry, this page is not valid AMP HTML"  Thanks

**Comment by ashishindiwork** [comment]
@aghassemi Can you please help me to update amp cache with fresh content of page. ???

**Comment by honeybadgerdontcare** [comment]
@ashishindiwork You may want to look at https://developers.google.com/amp/cache/update-cache.

**Comment by ashishindiwork** [comment]
@honeybadgerdontcare  Its returning  HTTP/1.1 204 No Content error.

**Comment by honeybadgerdontcare** [comment]
@ashishindiwork What is returning 204? The link I sent you or something else?

**Comment by ashishindiwork** [comment]
If i had used  
curl -i https://example-com.cdn.ampproject.org/update-ping/c/s/example.com/amp 

Can you send me link for update cache with fresh content

**Comment by atakancelik** [comment]
Okey, I resolved. İf you want read solution in this document : https://medium.com/@atakancelik/amp-cache-update-afd15f98a45a

**Comment by Gregable** [comment]
If anyone reads this older thread, the `update-ping` API mentioned above no longer exists. All update-cache requests must be signed. This is to protect the site owner from certain classes of DOS attacks.
