### ISSUE TITLE
Requirement of amp-form extension for input

### ISSUE THREAD

**Issue by ruborg** [ampproject/amphtml#10233]
## What's the issue?

Documentation for `amp-form` component (https://www.ampproject.org/docs/reference/components/amp-form) states 

> The amp-form extension MUST be loaded if you're using `<form>` or **any input tags**, otherwise your document will be invalid!

(My emphasis on "any input tags") 

This appears not to be true. If I include an `input` element without a `form` element and without including the `amp-form` extension, the page is still reported as valid. Is the documentation wrong, or should such a document be invalid?

## How do we reproduce the issue?

The AMP runtime reports the page below as valid. It has an `input` tag, but does not include the `amp-form` extension.
https://ruadhan.com/amp/amp-form-test.html#development=1

```
<!doctype html>
<html ⚡>
  <head>
    <meta charset="utf-8">
    <script async src="https://cdn.ampproject.org/v0.js"></script>
    <link rel="canonical" href="https://ruadhan.com/amp/amp-form-test.html" />
    <title>AMP Form test</title>
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>

  </head>
  <body>

  Text input: <input type="text" name="q" value="hi there!" >

  </body>
</html>
```

## What browsers are affected?
All

## Which AMP version is affected?
AMP version: 1498863866481

**Comment by aghassemi** [comment]
You are correct @ruborg, use of `input` for semantic purposes without requiring submission through `form` is valid without `amp-form`. PR for doc update is out.
