### ISSUE TITLE
AMP symbol

### ISSUE THREAD

**Issue by nikant25** [ampproject/amphtml#10232]
Hi,
Perhaps you can use the AMP symbol as entity = `&#9889;` or `&#x26a1;` . Instead of the images that you are applying now. 
Regards, 
Nikolaj Antonov 
nikant25@gmail.com

**Comment by techhtml** [comment]
I don't understand about this.
What is your issue?

**Comment by nikant25** [comment]
Currently, the W3 validator reports the error of the volt sign ⚡ that you are applying. If you apply the same sign as **[UTF-8 Miscellaneous Symbols](https://www.w3schools.com/charsets/tryit.asp?deci=9889)** this error is canceled. In addition, as a symbol, it will load faster than as an image.

**Comment by aghassemi** [comment]
@nikant25 Use of ⚡ is totally optional. You can use the word `amp` (e.g. `<html amp>`) instead.
