### ISSUE TITLE
Redirect from 'https://stats.g.doubleclick.net..' has been blocked by CORS policy

### ISSUE THREAD

**Issue by echopi** [ampproject/amphtml#10244]
## What's the issue?

Redirect from 'https://stats.g.doubleclick.net..' has been blocked by CORS policy
## How do we reproduce the issue?
1. visit: https://cdn.ampproject.org/c/s/m.aliexpress.com/amp/price/red-bottom-high-heels_price.html
2. go devtool console to see google analytics error

```
red-bottom-high-heels_price.html:1 Redirect from 'https://stats.g.doubleclick.net/r/collect?v=1&aip=1&t=dc&_r=3&tid=UA-17640202-1&cid=24sU-61UJpZnzyhNRRAPy4_PwpOW26rnpuWI50_s_PmDXzixuAPFhTYvCx_mJp0t&jid=0.8321475819421984&_v=a1&z=0.831045831653922' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'null' is therefore not allowed access.
```

**Comment by jasti** [comment]
Think this is related to GA. Over to @avimehta.

**Comment by jasti** [comment]
@avimehta would you be the right person to look at this? Also adding @lannka for comment.

**Comment by avimehta** [comment]
I am the right person for this bug but I can't reproduce the bug yet. Which browser are you seeing the issue on? Please also specify the version number.

**Comment by echopi** [comment]
@avimehta try this link: https://www.google.com.hk/amp/s/m.aliexpress.com/amp/popular/shoes-women-heels.html

**Comment by avimehta** [comment]
Still can't reproduce the error. I tried following things: 

In normal and incognito chrome, 
1. Opened dev tools, 
1. Started device emulation
1. Went to the page listed
1. Waiting for hits to go to GA.

No errors in dev console.

 It would be helpful to see find out which browser @echopi is seeing the error on.

**Comment by echopi** [comment]
It's Chrome Canary on desktop, sorry for not providing the browser info.

**Comment by avimehta** [comment]
Opened https://bugs.chromium.org/p/chromium/issues/detail?id=746687 for chrome. Will wait for their response. I could repro the issue in Chrome Canary with http://test.zoinks.in/xhr_chrome.html but could not reproduce it in Chrome stable. Also, the error does not show up in Firefox or Edge so this is likely a chrome specific thing.

If Chrome says that this is WAI, I can look at fixing this on GA side.
