### ISSUE TITLE
One item invisible on hover of the menu

### ISSUE THREAD

**Issue by zahiribishi** [ampproject/amphtml#10259]
*You have a bug in menu
![bug](https://user-images.githubusercontent.com/15115833/27859146-18d9c53a-6178-11e7-9d09-ed3fcf3105db.png)

**Comment by aghassemi** [comment]
Thanks for the report @zahiribishi . I moved the bug to amoproject.org's own github repo here: https://github.com/ampproject/docs/issues/598
