### ISSUE TITLE
Add a component to support floating comments

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#10258]
Similarly to [https://medium.com/@owencm/designing-great-uis-for-progressive-web-apps-dd38c1d20f7](https://medium.com/@owencm/designing-great-uis-for-progressive-web-apps-dd38c1d20f7) where you can highlight a word, click and a popup is shown, would this be possible in an AMP page in a scenario where you want to be able to create a comment by clicking on text?

amp-bind could help by showing / hiding a form, but this would need:

- capability the position of the element via amp-bind
- a way of calculating the new position 

@ericlindley-g @aghassemi Do you have any thoughts on this?

**Comment by ericlindley-g** [comment]
Sounds interesting — @kul3r4, where in the link can I find the interaction? (not sure I understanding it yet)

**Comment by kul3r4** [comment]
Open the medium article, then double click on any word, a popup appears suggesting comments or twitter and couple of other things.

**Comment by ericlindley-g** [comment]
Ah, thanks! /cc @choumx for visibility.  Would be curious to hear from @aghassemi and/or @choumx  about feasibility and tradeoffs here.

**Comment by aghassemi** [comment]
Here is what I believe we need to have to support this:
[ ] - `selectionchange` event (polyfill of https://developer.mozilla.org/en-US/docs/Web/Events/selectionchange )
[ ] - `amp-tooltip` that can be positioned relative to a given `element` or `SelectionRange`.
