### ISSUE TITLE
Design Review 2017-07-19 (roots, video docking, floating audio controls)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#10264]
The AMP Project holds weekly engineering [design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md).  **We encourage everyone in the community to participate in these design reviews.**

Time: Wednesdays @ [1pm Pacific](https://www.google.com/?#q=1pm+pacific+in+local+time)
Location: [Video conference via Google Hangouts](https://hangouts.google.com/hangouts/_/google.com/amp-eng-desrev)

If you are interested in bringing your design to design review, read the [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md) and add a link to your design doc by the Monday before your design review.

When attending a design review please read through the designs *before* the design review starts.  This allows us to spend more time on discussion of the design.

If you are unable to make the 1pm Pacific time due to time zone issues but you have a design you would like to present please make a note of that and we will try to find a time that works.

**Comment by choumx** [comment]
I'd like to discuss some thoughts on our services API and AMP embeds (aka AMP Roots, originally proposed by @dvoytenko).

https://docs.google.com/document/d/1RjyGFXUfIudrwFmfHWhsMwprOtgDIO4chyo4cNhQ_Tc/edit#heading=h.ydr456a07ivp

**Comment by wassgha** [comment]
Me and @aghassemi  will take a brief moment to get approval form the community for the naming of some of the features we've been working on https://docs.google.com/presentation/d/1DA5yGv9VgIPg9asx847D9Mr4i_hU5EBWrX_S7LYOEu0/edit#slide=id.g22a2658cb9_0_0

**Comment by cramforce** [comment]
I will be out due to a conflict. Bad scheduling that I missed to correct :/

**Comment by choumx** [comment]
### AMP Roots

- will: motivated by implementing amp-bind for FIE
- will: also, Kevin merged 40 PRs improving services and regretfully ended up with net increase in LOC
- dima: only a handful of services should be shared. history, vsync, resources, etc.
- dima: these shared services are also pretty heavyweight, others like "actions" are performance-trivial
- ali: is it worthwhile to have API to distinguish FIE vs parent, e.g. for history?
- dima: hard to say, especially for viewport. what does viewport mean in FIE?
- dima: we could have explicit APIs for fallback, e.g. getSharedService()
- will: next steps, plan out incremental changes to get us to better state
- dima: this is important, we should start soon

### Video docking

- add "dock" attribute with manual/always options
- optional snap-corner
- dima: specify [flex] start/end at top/bottom?
- ali: should be ok to flip in RTL like sidebar
- dima: dock by default?
- wassim: yea, dock: "always". default is "manual" which docks when video is playing
- ali: prefix attribute values with "video" to leave room for common attrs later on
- dima: what's snap-policy? for use with snap-element
- dima: scale? e.g. min 50%
- wassim: should be able to specify, 50% of desktop is large

### Floating audio controls

- wassim: current issue is interaction with sticky ads and other fixed-position UI
- dima: use configurable "offset"

### Video docking (continued)

- fullscreen on rotate? i.e. landscape -> fullscreen
- dima: enable by default?
- wassim: can't fullscreen anything but videos on iOS
- ali: won't add attrs until other 3P providers add support
- ali: unlikely video providers have "go-to-fullscreen" API
- dima: what about fullscreen videos with no "controls" attr?
- dima: start with changes to amp-video and research
- sriram: can we go back to PiP after fullscreen?
- dima: not possible.
- ali: has to be proper full-screen, not lightbox-fullscreen
- sriram: scaling?
- dima: annoying to have two types of "full-screen"
