### ISSUE TITLE
[amp-img] - Loading fails when the element goes from display: none to block

### ISSUE THREAD

**Issue by WillDonohoe** [ampproject/amphtml#10262]
## What's the issue?

If an amp-img is (or in a container) which is `display: none`, and during runtime the element display is set to anything other than none, the amp-img will fail to load.

The markup looks like the following when the image should be visible:

    <amp-img layout="responsive" src="/path/to/image.png" width="500" height="500" class="i-amphtml-element i-amphtml-layout-responsive i-amphtml-layout-size-defined">
        <i-amphtml-sizer style="display: block; padding-top: 100%;"></i-amphtml-sizer>
    </amp-img>

## What is expected?

As a developer, I expect the image to load when AMP detects when the image is visible within the viewport. This includes when an image goes from `display: none` to `display: block`.

## How do we reproduce the issue?

Create an `<amp-img>` element on the page and set the style to `display: none`. Once the page has loaded, set the display property to block. Notice that the image fails to render.

See codepen example [here](https://codepen.io/willdonohoe/pen/awKgVO)

**Comment by aghassemi** [comment]
We don't fully support changing the visibility of an element through css selector yet. Instead, you can use the `hidden` attribute and the AMP `show()` or `toggleVisibility()` actions. Please see http://codepen.io/aghassemi/pen/JWmNoB

**Comment by WillDonohoe** [comment]
Thanks for your prompt reply, unfortunately this won't fix our use-case as we need to toggle the view of an element without a click. However, we'll look into alternative solutions if it is not supported right now

**Comment by dev-drprasad** [comment]
My use case is also same. have to show image on hover. Hi @WillDonohoe, Do you have any workaround for this ??

**Comment by WillDonohoe** [comment]
Hey @dev-drprasad, no the scope of our project changed slightly and we didn't need this anymore. It might be worth playing with a few CSS properties to toggle the visibility of it. I'm not sure how AMP decides on which elements are visible or not. It's a bit of a hack, but maybe absolutely positioning the hover image over the original and toggle the opacity on hover might give you the right effect.

**Comment by sryze** [comment]
How are we supposed to have dropdowns with images inside that open on hover? Is this not supported at all?

**Comment by PHCCorso** [comment]
For anyone looking for a solution, I managed to work around this by hiding my images using:

```css
.your-image {
    position: absolute;
    opacity: 0;
    pointer-events: none;
}
```
You can then revert the changes to make the image show up again:

```css
.your-image {
    position: initial;
    opacity: 1;
    pointer-events: all;
}
```
