### ISSUE TITLE
Rubicon Ad tag not rendering in amp-ad but rendering via vanilla GPT

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#1026]
I've created two test pages two show the difference :

1. A [plain GPT based page](https://github.com/jasti/amp-ads-testing/blob/master/troubleshooting/Rubicon/rubicon.non-amp.html) that is requesting a single Rubicon Ad that is being trafficked in DFP as a third party ad.
2. An [amp-ad based page] (https://github.com/jasti/amp-ads-testing/blob/master/troubleshooting/Rubicon/rubicon.amp.html) that is requesting the same single Rubicon Ad that is trafficked in DFP as a third party ad.

1 renders, but 2 doesn't. Any thoughts?

**Comment by cramforce** [comment]
This is most likely a very DFP specific thing. Probably best to compare the ad requests and see what is different. I validated that no ad is rendered, so it isn't a CSS problem or similar.

**Comment by jasti** [comment]
Thanks, Rubicon tag had an insecure script loading. Switching the tag from http://ads.rubiconproject.com/ad/7470.js to https://ads.rubiconproject.com/ad/7470.js worked.


```javascript
<!--  Begin Rubicon Project Tag -->
<!--  Site: Vox.com_MWEB_RFM   Zone: High Tier ROS -  $1.15   Size: Medium Rectangle  -->
<script language="JavaScript" type="text/javascript">
rp_account   = '7470';
rp_site      = '42506';
rp_zonesize  = '331336-15';
rp_adtype    = 'js';
rp_smartfile = '[SMART FILE URL]';
rp_inventory = {
				entry_group:'%%PATTERN:entry_group%%',
				affiliation:'%%PATTERN:affiliation%%'
				};
</script>
<script type="text/javascript" src="http://ads.rubiconproject.com/ad/7470.js"></script>
<!--  End Rubicon Project Tag -->

```
