### ISSUE TITLE
upgrade to babel 6

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#1027]
blocker: https://phabricator.babeljs.io/T6724

**Comment by erwinmombay** [comment]
relevant bug, but not blocker: https://phabricator.babeljs.io/T2892

**Comment by rudygalfi** [comment]
@erwinmombay Still blocked?

**Comment by erwinmombay** [comment]
shouldn't be anymore, found a workaround but haven't finished the work yet. will try to wrap it up soon

**Comment by adelinamart** [comment]
Is this still blocked?

**Comment by erwinmombay** [comment]
yes, still blocked. closing for now
