### ISSUE TITLE
Support/Remove media attr in source tags

### ISSUE THREAD

**Issue by jmadler** [ampproject/amphtml#103]
The media attribute in <source> tags is functionally equivalent to the CSS media selector.  It should either be removed, or noted as supported in documentation.

**Comment by jmadler** [comment]
Is this still relevant?

**Comment by dvoytenko** [comment]
Which elements does this apply to?

**Comment by dvoytenko** [comment]
I can see that it's supported for `amp-video` and `amp-audio`. I don't think this applies to anything else in our case. So, I'm closing the issue.
