### ISSUE TITLE
FR: ability to drag carousel on desktop

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#10313]
Functionality request from designers working on new AMP Start templates (will also be nice for those making responsive AMPs in general)

/cc @spacedino  @camelburrito @aghassemi

**Comment by camelburrito** [comment]
This is  not Feasible on carousels with iframes/embeds

**Comment by wassgha** [comment]
@camelburrito could be possible using transparent overlays like we do for autoplay and drag/drop in the video manager, no?
@ericlindley-g I think this could be generalized to making the gesture recognizer support desktop (mouse events as well as touch events)

**Comment by ericlindley-g** [comment]
@wassgha  — definitely intrigued! Are you thinking of this as something that developers would implement for their AMP pages, or as something to integrate into particular AMP components or framework (or both?). 

Would this approach intercept touch/click events?

**Comment by wassgha** [comment]
Nevermind, I mistakenly thought `amp-carousel` used the `gestureRecognizer` for its swipe-to-scroll logic but it turns out it has its own implementation. Both `amp-carousel` and `gestureRecognizer` currently only listen for touch events, so if possible, it would be great to have them support mouse events as well.

**Comment by camelburrito** [comment]
We sort of have a gesture recognizer already on the runtime. It's a matter of exposing it . Again carousel is already complicated.

@wassgha no transparent overlay would not work , it was the first approach we tried for carousel . Video is a simpler subset of what carousel supports . 

Let's talk about it tomorrow and get some closure

**Comment by sparhami** [comment]
Our current thinking is to not support mouse dragging for changing slides for desktop. Perhaps we could have some visual treatment that tells users that they can use "shift + mousewheel" to horizontally scroll. Perhaps some sort of overlay on hover?

@andrewwatterson Any thoughts on this?

**Comment by sparhami** [comment]
Closing this as we do not have any plans to support swiping via dragging on desktop. For amp-carousel 0.2, we use a regular scrolling container. This allows users on laptops to swipe the carousel using a trackpad (two fingers left/right on MacOS).

/cc @nainar
