### ISSUE TITLE
amp-analytics (GA) firing erratically

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#10325]
Repro case:

Open this page http://www.diffen.com/difference/Cappuccino_vs_Latte?ampver in a new incognito window in Chrome iPhone emulation - 

No analytics ping in the network tab.

Reload the page and I see a ping to https://www.google-analytics.com/r/collect initiated by amp-analytics

If the incognito window has opened any other amp page, even another site you see the ping.  This happens even if browser cache is off and I clear all the local storage between pages, it must be a new window to get it to happen.

On Safari desktop I never see the ping regardless of prior page loads.

Note: I can’t reproduce it on any of our pages but we have multiple amp analytics tags on our pages which may be a factor.  It appears to be a solid repro on the diffen page.

**Comment by avimehta** [comment]
@jpettitt what are you searching for in the devtools network tab?

When I do this in a new window and search for collect, I see a ping to `doubleclick.net` which is initiated by `google-analytics.com/r/collect` (hover over initiator link). That seems to tell me that there is a ping being sent it just doesn't show up in dev tools. 

Can you take a look and let me know. Here's a screenshot of what I see: https://goo.gl/photos/D2xsmoFegTQtbyK66

**Comment by jpettitt** [comment]
Weird it just became intermittent for me - 5 tries in a row it worked as expected.  On the 6th, and now consistently (new incognito every time)  I get this

![image](https://user-images.githubusercontent.com/524856/28032966-39539894-6561-11e7-9550-66039c2522f9.png)

Note the initiator is 'collect'

On a reload I get 
![image](https://user-images.githubusercontent.com/524856/28033012-640b5892-6561-11e7-8476-dec306d02bc2.png)

Note there are now 2 pings - the one from collect and one from amp-analytics.  The amp one hits the google-analytics endpoint then 302's to doubleclick as expected.

**Comment by avimehta** [comment]
The first screenshot is exactly what I see. If you hover over collect, you'll see the hit that was sent to `google-analytics.com`. 

I investigated safari further. Same as chrome, devtools seems to show hits going to doubleclick but not the ones going to google-analytics.com. Unfortunately, I can't find a way to see the initiator in safari. 

Given that `googleanalytics` config sends hits only to `google-analytics.com` and doubleclick only comes into picture after the request response is received from `google-analytics.com`, I think it is safe to say that the data reaches GA.

It would be worth creating a smaller repro for chrome and Safari bug reports. Will work on that as soon as I get some bandwidth.

**Comment by jpettitt** [comment]
Why is it behaving differently on some loads? That's a very odd behavior difference given that cache is off and local storage purged.  Is some state being save that we're not seeing?

**Comment by avimehta** [comment]
I think I have an answer for intermittent repro. 

In a new incognito window:
1. Open Dev tools (Inspector window)
2. Navigate to http://www.diffen.com/difference/Cappuccino_vs_Latte?ampver
3. Open Network tab
4. Verify requests

> In this case, you'll see one request go out to doubleclick. 

Do Step 3 before Step 2. 

> In this case, you'll see two requests go out.

This clearly looks like a chrome bug. Unfortunately, I can't reproduce it with a very small repro page. Not sure what is triggering this bug on the diffen page.

**Comment by jridgewell** [comment]
It's probably the 302 redirect. I remember we had an issue before where it wouldn't show at all, not it might only show if you're on Network tab.

**Comment by jpettitt** [comment]
Interesting - once the network tab has been open once you see the 302.  If you don't open the network tab, even with dev tools open, you can reload as many times as you like and the first time you open the network tab you won't see the 302.  So definitely a red herring / Chrome issue.

**Comment by jridgewell** [comment]
Old chrome issue is https://bugs.chromium.org/p/chromium/issues/detail?id=675789 (from https://github.com/ampproject/amphtml/issues/6740). Could you open another Chrome bug for this new case?

**Comment by avimehta** [comment]
@diffen I am working on your other bug report internally but don't have much to report yet. This bug is not related to the mismatch in numbers you see in your reports.

The issue in this bug is purely a debugging thing and rest assured, the data is reaching GA.
