### ISSUE TITLE
Broken links on various pages

### ISSUE THREAD

**Issue by avimehta** [ampproject/amphtml#10335]
https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/integrating-analytics.md contains a link to a page that is titled "Deep Dive: Tracking users across origins". 

Unfortunately, I can't find the page that was supposed to be at https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/cross-origin-tracking.md. 

Not sure when it was removed.

**Comment by jridgewell** [comment]
/to @rudygalfi, since he [did it](https://github.com/ampproject/amphtml/pull/7433).

**Comment by mauricionr** [comment]
why this link  https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/cross-origin-tracking.md was removed?

Thanks :smile:

**Comment by jridgewell** [comment]
It was just moved to https://github.com/ampproject/amphtml/blob/master/spec/amp-managing-user-state.md.
