### ISSUE TITLE
Scroll event flicker on position:fixed element in Safari

### ISSUE THREAD

**Issue by liuhelen10** [ampproject/amphtml#10343]
Although it seems that this issue has been [addressed in the past](https://hackernoon.com/amp-ios-scrolling-and-position-fixed-redo-the-wrapper-approach-8874f0ee7876), I'm still encountering a bad flicker on scroll on a `position: fixed` element in Safari on my iPhone 6 (haven't tested on any other mobile iOS devices). This issue is not present on desktop (Chrome and Safari), iPhone emulation mode on desktop Chrome or Safari, or on mobile Android.

To reproduce, visit https://www.google.com/amp/s/www.lyft.com/amp/driving-jobs on a mobile iOS device. Observe that the header "bounces" around on scroll.

Note that the header behaves as expected (i.e. there is no flicker) when visiting the amp page directly at https://www.lyft.com/amp/driving-jobs.

The `header` element on the page has the following applied CSS styles:
```
z-index: 600;
position: fixed;
width: 100%;
display: block;
```
I'm downloading https://cdn.ampproject.org/v0.js in the document `head`.

I dug into the [source code](https://github.com/ampproject/amphtml/blob/master/src/service/fixed-layer.js) briefly but I was unable to find anything that indicates that this should be broken. It seems that this code should be handling the `position: fixed` issue. Please advise. Thanks!

**Comment by cramforce** [comment]
@dvoytenko Could you take a look?

**Comment by jridgewell** [comment]
I'm looking into it now.

**Comment by dvoytenko** [comment]
@jridgewell Let me know if you need help. The most likely reason: for some reason AMP vetoed transfer to fixed layer, which is very possible since the rules are pretty strict: https://github.com/ampproject/amphtml/blob/master/src/service/fixed-layer.js#L331 + some rules about selectors as well. W/o fixed layer hack, fixed elements would be at mercy of iOS Safari w.r.t flicker. 

If we still do transfer and it flickers - then we need to see.

**Comment by jridgewell** [comment]
Closed by https://github.com/ampproject/amphtml/pull/10366.

**Comment by liuhelen10** [comment]
Thanks for addressing so quickly! Has this fix been deployed to prod already? @jridgewell

**Comment by jridgewell** [comment]
No, we'll canary test it tomorrow and probably release a prod patch later this week.

**Comment by liuhelen10** [comment]
Hi @jridgewell , I'm still seeing this issue on prod. Looks like [the fix](https://github.com/ampproject/amphtml/pull/10366) was reverted at some point? Any updates here?

**Comment by jridgewell** [comment]
Yes, my fix caused several more issues with scrolling. I'm working on a new solution (actually, the 3rd attempt), but it's complicated by the header not having an explicit `top: 0px` style.

**Comment by cramforce** [comment]
@jridgewell Is there something @liuhelen10 could do to resolve the issue on their side? (independent of the larger fix)

**Comment by jridgewell** [comment]
Adding `top: 0px`. 😄 

The code I'm working on now is a full-proof method of detecting `top: auto` (or implicit auto) styles, which'll allow us to extend to non-zero pixel-distances in the future.
