### ISSUE TITLE
Validator: support shadow slots

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#10345]
See https://developers.google.com/web/fundamentals/getting-started/primers/shadowdom

An example:

```
<slot name="abc">
  ...
</slot>
```

The `slot` element is much like a `div`. All global attributes are allowed, such as `id` and `on`. The only specific attribute to `slot` element is the optional `name` attribute.

**Comment by Gregable** [comment]
Only allowed in AMP, not AMP4ADS.

**Comment by powdercloud** [comment]
What about the slot attribute? I see it there on the page... Is it needed as well?

**Comment by powdercloud** [comment]
Also it would be useful to have a more complete example of how it's going to be used in AMPHTML. E.g., I see the example in the doc under "Flattened DOM tree" (https://developers.google.com/web/fundamentals/getting-started/primers/shadowdom#lightdom) but there are obviously other things that aren't allowed either, e.g. putting some custom element name (in the example "better-button") that's not known to the validator.
So I'd like a more complete example for the test please...

**Comment by dvoytenko** [comment]
The `slot` attribute is not strictly needed at this time, so I'd rather skip. You can see an example here: https://github.com/ampproject/amphtml/pull/10346/files#diff-40013838fcacfcd8aaef22101639e190

> but there are obviously other things that aren't allowed either, e.g. putting some custom element name (in the example "better-button") that's not known to the validator.

Not sure I understand this point. Could you clarify? The name of the element is `slot`, so it can't be named anything else...

**Comment by powdercloud** [comment]
Cool. I was just looking for a complete example and was referring to a snippe tin the shadowdom primer. I'm happy with wahtever is needed.
Please note that the content tag is currently also disallowed, but it's used in the example you're pointing at. Should we allow it? If so, should the select attribute on a content tag be allowed?
(https://developer.mozilla.org/en-US/docs/Web/HTML/Element/content).

**Comment by dvoytenko** [comment]
I see. Yeah, outside of AMP the app would use the `slot` attribute. Structurally it'd look like this:

```
<div class="host">
  #shadow-root <
     AMP IS HERE. Our validator rules apply.
     <body>
       <slot name="slot1">
          This is shown if no slot can be filled.
       </slot>
     </body>
  >
  <div slot="slot1">
     This will replace slot[name=slot1] in the AMP doc.
   </div>
</div>
```

**Comment by dvoytenko** [comment]
RE: `content` tag. This has been deprecated and I'd be in favor of not allowing it at this time.

**Comment by dvoytenko** [comment]
Thanks for the fast turnaround!

**Comment by Gregable** [comment]
This should be live in validation in about an hour.
