### ISSUE TITLE
Move CID hash generation into worker

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1035]
More concretely we should generate a binary for https://github.com/ampproject/amphtml/blob/master/third_party/closure-library/sha384-generated.js that can live in a worker and performs signature generation in response to messages.

Eventually we'd have an API like

```JS
return new Promise((resolve) => {
  cyptoWorker.postMessage('sha384', messageToSign);
  cryptoWorker.onmessage = function(response) {
    if (response.type == 'sha384' && response.messageToSign == messageToSign) { // or use a message index
      resolve(response.digest)
    }
  };
});
```

and then get a message event back with the signed

**Comment by erwinmombay** [comment]
@cramforce is sha384-generated.js currently built with amp.js/v0.js ?

**Comment by cramforce** [comment]
No, and it won't be. It'll be build into amp-analytics and while other components will be able to use it, it'll only work if amp-analytics is on the page.

**Comment by cramforce** [comment]
CC @jridgewell Might be a good project to get started in AMP. Talk to you later!

**Comment by cramforce** [comment]
Switched to async API
