### ISSUE TITLE
cross origin tracking

### ISSUE THREAD

**Issue by mauricionr** [ampproject/amphtml#10375]
## What's the issue?

I'm trying to implement cross origin tracking. i saw the broken link in this issue #10335  and i saw the file removed here https://github.com/ampproject/amphtml/pull/7433
exist any recipe in how to implement the cross origin tracking?

## How do we reproduce the issue?

setup amp container in analytics and implement  in a amp page

```html
    <amp-analytics config="https://www.googletagmanager.com/amp.json?id=GTM-EUR35AZ&gtm.url=${config.webstore_url}/${data.product.slug}/p" data-credentials="include">
      <script type="application/json">
      {
        "vars": {
          "gaTrackingId": "UA-123456789-1"
        }
      }
      </script>
    </amp-analytics>
```

when the user goes to the cart a new session is started

**Comment by mauricionr** [comment]
i've asked in amp4discuss on slack

**Comment by mauricionr** [comment]
nobody on slack :cry:

**Comment by jridgewell** [comment]
The original file was just moved to https://github.com/ampproject/amphtml/blob/master/spec/amp-managing-user-state.md.

**Comment by mauricionr** [comment]
Thanks @jridgewell
