### ISSUE TITLE
${documentReferrer} is empty when document.referrer is “https://www.google.com/”

### ISSUE THREAD

**Issue by mattrohland** [ampproject/amphtml#10374]
Looking through the AMP documentation (https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#document-referrer) is appears that the `${documentReferrer}` variable should reflect the JS `document.referrer`.

While `${documentReferrer}` appears to return the correct value for other domains (like: www.twitter.com, t.co, linkedin.com, etc.) when the page's `document.referrer` value is "https://www.google.com/" `${documentReferrer}` is empty.

I couldn't find any documentation indicating that the www.google.com domain carried any additional caveats. Is this a bug or expected behavior?

----

For some context, this behavior was observed after implementing the "adobeanalytics_nativeConfig" approach provided by Adobe: https://marketing.adobe.com/resources/help/en_US/sc/implement/accelerated-mobile-pages.html

**Comment by cramforce** [comment]
Could you file this as an issue here:
https://github.com/ampproject/amphtml/issues/new

Definitely not intended.

**Comment by mattrohland** [comment]
> Could you file this as an issue here:
> https://github.com/ampproject/amphtml/issues/new

@cramforce I believe that is what I did?

**Comment by cramforce** [comment]
LOL, yes. I was confused by Github having changed the email addresses for notifications :)

**Comment by cramforce** [comment]
To @lannka while @zhouyx is out.

**Comment by lannka** [comment]
@mattrohland do you have a page that we can reproduce the issue?

**Comment by mattrohland** [comment]
It turns out that the documentation provided by Adobe was not followed precisely in our implementation (https://marketing.adobe.com/resources/help/en_US/sc/implement/accelerated-mobile-pages.html).

Stripping out a lot of the noise, the following code was in use in our implementation:

```html
<amp-analytics type="adobeanalytics_nativeConfig">
    <script type="application/json">
        {
            "requests": {
                "base": "https://${host}",
                "iframeMessage": "${base}/amp/iframe.html?page-referrer=${documentReferrer}"
            },
            "vars": {
                "host": "www.example.com",
                "documentReferrer" : "{{meta.Referer}}"
            },
            "extraUrlParams": {}
        }
    </script>
</amp-analytics>
```

Inclusion of the `vars.documentReferrer` entry deviated from Adobe's documentation and appears to be the culprit. Once that extra value was removed referrals for "https://www.google.com/" started to work correctly.

```diff
"vars": {
     "host": "aas.gannettdigital.com",
-     "uaid": "{{config.Public.amp.uaid}}",
-     "documentReferrer" : "{{meta.Referer}}"
+     "uaid": "{{config.Public.amp.uaid}}"
},
"extraUrlParams": {
```

This was an implementation issue on our end not a bug in AMP.

**Comment by lannka** [comment]
@mattrohland since you get that far, it will be appreciated if  you could file a bug against adobe folks :-)
