### ISSUE TITLE
Autoplay video paused by the pause action continues playing after re-entering viewport

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#10382]
Should be a quick fix to set the `userInteractedWithAutoplay_` flag

**Comment by aghassemi** [comment]
@cvializ  might be dup of https://github.com/ampproject/amphtml/issues/9055

**Comment by cvializ** [comment]
Looks like you're right, thanks! I noticed this behavior when implementing video analytics and I missed that issue when I was looking for duplicates.
