### ISSUE TITLE
amp-form doesn't get rendered inside amp-list

### ISSUE THREAD

**Issue by zhangsu** [ampproject/amphtml#10390]
## What's the issue?

amp-form placed inside the Mustache template of an amp-list gets sanitized and stripped out.

## How do we reproduce the issue?

Open an AMP HTML page containing the following:

```html
  <amp-list src="https://ampbyexample.com/json/examples.json">
    <template type="amp-mustache">
      <div>
        {{title}}
      </div>
      <form method="post"
            action-xhr="https://ampbyexample.com/comments/{{title}}"
          target="_top">
        <input type="text" name="content">
        <input type="submit" value="Add comment">
      </form>
    </template>
  </amp-list>
```

Inspect the rendered HTML and find that `<form>` is completely stripped out of the rendered list items.

@choumx

**Comment by aghassemi** [comment]
@choumx this is dup of https://github.com/ampproject/amphtml/issues/9768, let's clone one of them.

**Comment by choumx** [comment]
Closing in favor of #9768.
