### ISSUE TITLE
FR: amp-img loading state

### ISSUE THREAD

**Issue by 10xjs** [ampproject/amphtml#10396]
The `amp-img` component does not currently provide any way to target elements that are currently loading. The motivating use-case is to add a css opacity fade transition to the img when it loads.

A generic solution would be to have amp add a class or an attribute to `amp-img` that can be targeted with a css selector.

```html
<style>
  amp-img img {
    transition: opacity 0.5s;
  }

  amp-img[loading] img {
    opacity: 0;
  }
</style>

**Comment by aghassemi** [comment]
@10xjs Good FR.

a hackish workaround (no guarantee it won't break later) is using an empty placeholder and adjacent CSS selectors to target loading (relying on the behaviour that placeholder will be visible during loading). You can find a demo here: https://codepen.io/aghassemi/pen/WOBoOE?editors=1010 

/cc @ericlindley-g

**Comment by aghassemi** [comment]
@10xjs `amp-animation` (still experimental and in development) will also support this use-case. `amp-animation` waits for items to load then applies any transition you like. You can also do scrollbound transitions for images ( such as faides in when scrolled into view) see demo here: https://s.codepen.io/aghassemi/debug/NgJEaV

**Comment by ericlindley-g** [comment]
+1 This would add a nice bit of polish (and we could think about adding a default fade in, but would have to weigh any tradeoffs, and be good to hear from the community about that :)

**Comment by aghassemi** [comment]
Closing in favor of the blurry image placeholder project that's launching soon.
