### ISSUE TITLE
AMP Uncategorized Errors On Structured Data Testing Tool

### ISSUE THREAD

**Issue by techleadzwpteam** [ampproject/amphtml#10400]
I have facing  Uncategorized  Errors while I am checking my AMP Site into  Structured Data Testing Tool.

Please have a look: http://www.screencast.com/t/dIH9J05jhP

 Currently I have removed the curl code from the site.

Please guide how should I removed that error 

https://search.google.com/structured-data/testing-tool#url=www.girpropertyclaims.com%2Famp

 **I need to fixed this Asap.**

**Comment by jridgewell** [comment]
You have two objects in the json-ld field. Delete the first one (with `ampUrls` and `urlErrors`).
