### ISSUE TITLE
Allow PUT, PATCH and DELETE for amp-form

### ISSUE THREAD

**Issue by zhangsu** [ampproject/amphtml#10408]
Currently, [the only allowed HTTP verbs](https://github.com/ampproject/amphtml/blob/master/src/service/xhr-impl.js#L63) (specified in the `method` attribute) for `amp-form` (with `action-xhr`) is GET and POST. Can we enable PUT, PATCH and DELETE as well? These are most commonly mapped to whole-message update, partial update and deletion of resources in RESTful APIs.

@choumx

**Comment by aghassemi** [comment]
@zhangsu HTML `form` only allows `GET` and `POST`, if AMP allows this, it would only be for `xhr-action`.

**Comment by zhangsu** [comment]
Yes, I mentioned this in the OP that this should only apply if `action-xhr` is specified. Thanks!

**Comment by ikriser** [comment]
Any updates on this? I also would like this feature.

**Comment by cvializ** [comment]
No updates yet, this issue is prioritized but we haven't been able to assign it yet. Thanks for sharing your interest!

**Comment by eduardogoncalves** [comment]
Any updates on this? I also would like this feature.
