### ISSUE TITLE
[AMP Banner] - The button of app "Medium" has status "Installed" in the Play store

### ISSUE THREAD

**Issue by wildflowertester** [ampproject/amphtml#10417]
## What's the issue?
Issue: The button of app "Medium" has status "Installed" in the Play store before user tried to install it.  (The video of this issue could be provided if needed)

## How do we reproduce the issue?
1. Open the browser and clean the cache
2. Place AMP Cache  in viewer sandbox links
3. Tap on the AMP -banner 
4. Wait for downloading of Play store page. Do not tap on any types of browsers.
5. Observe the button of app "Medium" -It has name "Installed" (not Download)- WAI?
6. Type on "InstallED"-button and then on "InstaLL"-button
7. The app Successfully installed. You can find it in apps mode.

## What browsers are affected?
- Chrome 59.0.3071.125
- Firefox 54.0.1

(The video of this issue could be provided if needed)

What device type?
- Samsung Galaxy S5 (OS 5.0)

**Comment by muxin** [comment]
I don't have a samsung but I tested on a Nexus 5X. Cannot repro. It's probably not related to amp but an operating system level bug. Closing this since it's not related to amp runtime.
