### ISSUE TITLE
[AMP Banner] - The tapping on amp-banner redirected user to the medium.com

### ISSUE THREAD

**Issue by wildflowertester** [ampproject/amphtml#10419]
## What's the issue?
Issue: The button of app "Medium" has status "Installed" in the Google store before user tried to install it. (The video of this issue could be provided if needed)

## How do we reproduce the issue?

1. Open the browser and clean the cache
2. Place AMP sandbox link to amp test input box and click "RUN TEST"
4. Click "Preview search result", and open the search result link
5. Tap on the AMP -banner (View in ...)
4. Tap on actual browser from proposed. 
5. Observe the medium.com page.

## What browsers are affected?
-Chrome 59.0.3071.125
- Firefox 54.0.1

What device type?
Samsung Galaxy S5 (OS 5.0)

**Comment by muxin** [comment]
dup of https://github.com/ampproject/amphtml/issues/10417
