### ISSUE TITLE
[AMP Banner] - The AMP banner does not appear

### ISSUE THREAD

**Issue by wildflowertester** [ampproject/amphtml#10415]
## What's the issue?
Issue:
The AMP banner does not appear. (I can provide a video if needed)

## How do we reproduce the issue?

1. Clear the cache
2. Go to the sandbox link
3. Observe the issue (banner does not appear)

## What browsers are affected?
- Stock 2.1.34.33-1_100500_43695
- Opera 42.7.2246.114996

What device type?
- Samsung Galaxy S5 (OS 5.0)

## Which AMP version is affected?

Is this a new issue? Or was it always broken? Paste your AMP version. You can find it in the browser dev tools.

**Comment by aghassemi** [comment]
/to @muxin couple of reported issue today, setting a p1, can you see if there is a regression in the newest prod?

**Comment by wildflowertester** [comment]
The same issue was observed on 
- Samsung Galaxy Note 5  (OS 6.0.1) - Chrome 59.0.3071.125
- Samsung Galaxy Note 5  (OS 6.0.1) - Stock 5.4.00-75
- Samsung Galaxy Note 5  (OS 6.0.1) - Opera 42.7.2246.114996

**Comment by muxin** [comment]
On android chrome, for standalone page, it is intended not to show amp-app-banner because the default chrome banner might show up.

Not sure about stock or opera yet.

**Comment by muxin** [comment]
Lowering the P level since chrome's behavior is correct.

**Comment by Raji2** [comment]
The same issue was observed on Stock browser in 2 different devices

Browser :Stock
1.Galaxy S4/ Android version:4.4.2 / KOT49H
2.Samsung Jelly Bean /Android Version:4.3 / Build:JSS15

**Comment by muxin** [comment]
Thanks for filing the issue.

The problem is in our code we couldn't differentiate chrome/stock/opera. If the following `this.canShowBuiltinBanner_` is `true`, we hide the `amp-app-banner`
```js
const isChromeAndroid = platform.isAndroid() && platform.isChrome();
this.canShowBuiltinBanner_ = !isProxyOrigin(this.win.location) &&
        !viewer.isEmbedded() && isChromeAndroid;
```
We hide the `amp-app-banner` intentionally for non-embedded android chrome. But Stock and Opera also looks like chrome. Identifying Opera is easy but I'm not sure about stock browser

Let me investigate more...
