### ISSUE TITLE
AMP Banner Opens Play Store when app is installed in Opera

### ISSUE THREAD

**Issue by Wleyba** [ampproject/amphtml#10425]
What's the issue?
Tapping AMP Banner opens Play Store instead of opening AMP article even when App Medium is already installed.  Applies to both AMP Cache and Embed in viewer sandbox links.

How do we reproduce the issue?
1. Open Opera browser
2. Place AMP Cache or Embed in viewer sandbox links
3. Tap on AMP Banner View In
4. Observe Play Store page opens

What browsers are affected?
Opera ver 42.7
Nexus 6P N ver 7.1.2

**Comment by muxin** [comment]
Actually both play store and the app itself were opened. Opera in android somehow still executes the timeout block (play-store-link) when opening up the app-deep-link. Not happening in other browsers so lowering the P level.

**Comment by aghassemi** [comment]
deduping with https://github.com/ampproject/amphtml/issues/6411
