### ISSUE TITLE
Opera app-banner does not respond to tapping in iOS10

### ISSUE THREAD

**Issue by testengineer9** [ampproject/amphtml#10420]
## What's the issue?
Nothing happen when tapping on the app-banner in browser Opera. Please see screen capture video, Opera_iOS10.m4v.zip.
[Opera_iOS10.m4v.zip](https://github.com/ampproject/amphtml/files/1146550/Opera_iOS10.m4v.zip)

# How do we reproduce the issue?
1. Open the following URL link with Opera browser in iOS10
    https://ampbyexample.com/components/amp-app-banner/
2. Tap on "VIEW IN APP" button on the app-banner.

## What browsers are affected?
iPhone6 (iOS v10.3.1)
Opera v14.0.0104835

**Comment by wildflowertester** [comment]
The same was observed on Samsung Galaxy S5 (OS 5.0)
- Stock 2.1.34.33-1_100500_43695

**Comment by testengineer9** [comment]
The "VIEW IN APPS" button also has not been seen on Chrome (v59) and Firefox(v7.5) in iPhoneSE (iOS v9.2.1).
![ios9_app-banner](https://user-images.githubusercontent.com/30087065/28188819-5623ce98-67d8-11e7-859e-165f4d739eb6.PNG)

**Comment by muxin** [comment]
Confirmed repro on **IOS Opera**: "view in app" button actually shows up but tapping on it won't redirect.

**Comment by muxin** [comment]
This one is really difficult to debug (IOS Opera), marking it blocked.

**Comment by aghassemi** [comment]
Closing as stale
