### ISSUE TITLE
"Cannot Open Page" message pops up before app store

### ISSUE THREAD

**Issue by testengineer9** [ampproject/amphtml#10427]
## What's the issue?
A "Cannot Open Page" message pops up when tapping "VIEW IN APP" button, app store comes up after a second latter. Note: this happen when the app has not been installed in the device.

[error_message_firefox_ios10](https://user-images.githubusercontent.com/30087065/28190204-9e1352e0-67de-11e7-8301-6b6666f013e2.PNG)

Screenshot video,
[Firefox_iOS10.zip](https://github.com/ampproject/amphtml/files/1146801/Firefox_iOS10.zip)

## How do we reproduce the issue?
1. Open FireFox with the following link,
2. Tap on "VIEW IN APP" button in the app-banner, a "Cannot Open Page" message pops up before App Store. 

## What browsers are affected?
iPhone6 (iOS v10.3.1)
FireFox (v7.5)

**Comment by muxin** [comment]
This is unfortunately the way it is for this situation. When the app is not installed on the device, we still try to open the app-deep-link first, then try the install-app-link.
