### ISSUE TITLE
amp-ad adsense warning

### ISSUE THREAD

**Issue by ashrafpro** [ampproject/amphtml#10431]
Hi,
I get 3 warnings whenever I use adsense within my page
adsense code:
`<amp-ad width=300 height=600 type="adsense" data-ad-client="ca-pub-12345678901234567" data-ad-slot="1234567890"></amp-ad>`

I added the script last thing before closing the head
`<script async custom-element="amp-ad" src="https://cdn.ampproject.org/v0/amp-ad-0.1.js"></script>`

`The resource https://d-40757339831036881616.ampproject.net/1499807487098/frame.html was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
nw.php:1 The resource https://3p.ampproject.net/1499807487098/f.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
nw.php:1 The resource https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.`

is there a cure?

**Comment by jridgewell** [comment]
You can safely ignore these errors.
