### ISSUE TITLE
amp-access NUMERIC expression should support negative numbers

### ISSUE THREAD

**Issue by andytuba** [ampproject/amphtml#10461]
## What's the issue?

The [amp-access grammar definition for NUMERIC](https://github.com/ampproject/amphtml/blob/c44a48fbb1dbd0de0b5a9e20f8f69bb920705dde/extensions/amp-access/0.1/access-expr-impl.jison#L24) only supports numbers >= 0.

```
error.js:151 Authorization failed: : Parse error on line 1:
some_numeric_value = -1
----------------------^
Expecting 'NAME', 'STRING', 'NUMERIC', 'TRUE', 'FALSE', 'NULL', got 'INVALID'​​​
```

## How do we reproduce the issue?

Set up an amp page which imports `amp-access` and contains
`<span amp-access="some_numeric_value = -1" />`
Authorization should return `{ some_numeric_value: 1 }` or some value that's not `-1`

Note console error and `amp-access-hide` is not set on the `span`.

## What browsers are affected?

Tested in Chrome 59 OS X.

## Which AMP version is affected?

amp 1499807487098
amp-access-0.1

**Comment by dvoytenko** [comment]
Thanks for the report! I'm scheduling it for this milestone.
