### ISSUE TITLE
Dynamic resizing of `amp-iframe` based on source URL bucket list

### ISSUE THREAD

**Issue by wassgha** [ampproject/amphtml#10467]
As @aghassemi mentioned in #9838 , adapters can be created to map resize messages from various embeddable websites to `amp-iframe`'s resize message which would dynamically resize the iframe based on its content. 

Thanks to the efforts of @jpettitt , we created a bucket list of websites that our users would like to support, and the results of investigating whether they provide any kind of post message that we can adapt:

- [ ] Google Docs / Slides / Forms 

> No message provided, opened an issue b/63535685

- [ ] Storify
> Verified, sends a resize message. Example:
> ```
> MessageEvent {isTrusted: true, data: "
> {
> "method":"resize",
> "value":6809,
> "sourceName":"sacb…-relievers-sean-doolittle-ryan-madson-traded-to"}", 
> origin: "http://storify.com", 
> lastEventId: "", 
> source: Window…
> }
> ```

- [x] Datawrapper 

> Implemented native amp resize message

- [ ] Disqus Comments
> Doesn't support iframe embeds per se, official tutorial [here](https://github.com/disqus/disqus-install-examples/tree/master/google-amp) recommends creating another page that loads disqus and when embedded as an `amp-iframe` it takes care of resizing itself.
- [ ] Giphy

>  Doesn't send messages but has a "responsive" embed mode where the content fits the `iframe`'s heigh which kind of solves the problem

- [ ] Video Players that don't have an amp extension (although easy to predict since most are 16:9)

Thanks to @jpettitt  for compiling the list.

**Comment by aghassemi** [comment]
related to https://github.com/ampproject/amphtml/issues/9838

**Comment by jpettitt** [comment]
Datawrapper.de just confirmed that their embeds now send a blind an AMP compatible resize request.  Existing embeds will need to be republished to pick up the change, anything published going forward will work by simply converting the `iframe` to an `amp-iframe` without the need for any on page JS.

**Comment by wassgha** [comment]
That's great news :) ! Thank you

**Comment by aghassemi** [comment]
deduping with https://github.com/ampproject/amphtml/issues/22714
