### ISSUE TITLE
Scroll to an id tag on another page

### ISSUE THREAD

**Issue by jkaliski** [ampproject/amphtml#10464]
There is a button on my index.html page which has a link to a section(id ="example2") on page2 - href="page2.html#example2".  Pressing the button results in scrolling to the section on page2 and afterwards an immediate scroll back to the top of the page.  Any ideas on how to solve this issue?

**Comment by jridgewell** [comment]
Are these amp pages? Can you give us a link?

**Comment by jkaliski** [comment]
Thanks Justin! I found the culprit in my code, it works now!
