### ISSUE TITLE
Default `animateScrollIntoView()` speed to a dynamically calculated speed

### ISSUE THREAD

**Issue by wassgha** [ampproject/amphtml#10463]
As mentioned by Ali in #10398, the default duration for `animateScrollIntoView()` in `viewport-impl` should probably be based off a formula that relates the distance to be scrolled to the duration of the animation. 
An example would be `abs(elementTop - scrollHeight) / 2`.
The speed also needs to be bounded so that the animation isn't too fast or too slow.
Ideally use whatever Chrome is using for their native implementation (https://bugs.chromium.org/p/chromium/issues/detail?id=243871)

**Comment by aghassemi** [comment]
related to https://github.com/ampproject/amphtml/issues/7626
