### ISSUE TITLE
Support XHR mocking in describes.js

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#10477]
- Add a dead-simple way to stub/mock `Window.fetch` when using describes.

Related: https://github.com/ampproject/amphtml/issues/10128#issuecomment-311496211 and #9338

Internal discussion: `https://groups.google.com/a/google.com/d/msg/amphtml-eng/YKxMVlpQ6xA/fj3KS3FDAQAJ`

/cc @lannka @taymonbeal @jridgewell @rsimha-amp

**Comment by taymonbeal** [comment]
Feature request likely to help ensure correctness: This should be on by default, and if a test doesn't declare any expectations for XHRs, then any XHR made during that test should cause it to fail. Tests that need to make real XHRs should have to explicitly opt out, and this should be unusual.

**Comment by choumx** [comment]
@Raphaeljunior expressed interest in this.

**Comment by choumx** [comment]
One thing to note about Taymon's request is that a Sinon mock/expectation doesn't appear to support multiple `withArgs()`: https://github.com/sinonjs/sinon/issues/1193

This means that barring a custom solution, a stub may be the best we can do for now (unless you'd like to contribute that feature to Sinon 😄 ).

**Comment by taymonbeal** [comment]
I thought the plan was to use the third-party library [fetch-mock](http://www.wheresrhys.co.uk/fetch-mock/).

**Comment by choumx** [comment]
@jridgewell suggested it as an option but I'm not familiar with it. Certainly something to consider.

**Comment by taymonbeal** [comment]
I've been exploring the API and I'm pretty happy with it. It easily expresses most of what we want to do, and provides nice integration points if we want to add anything more. The only difficult part (which I wasn't able to figure out on my own) is how to make it play nice with our build system, as it doesn't use ES6 modules.

**Comment by Raphaeljunior** [comment]
On it. Let me start the reading.

**Comment by taymonbeal** [comment]
One issue I've just observed is that fetch-mock doesn't seem to distinguish CORS requests from non-CORS ones. Not sure if I would expect this to be a problem in practice or not.

**Comment by taymonbeal** [comment]
This is also true of other features that change the request headers but are controlled through init options rather than by directly setting them, such as credentials.

This might be fixable by overriding the right things, if we wanted to.

**Comment by jridgewell** [comment]
Wouldn't you deny or accept CORS requests manually?

**Comment by taymonbeal** [comment]
I mean that if the code under test is supposed to specify `mode: 'cors'` but doesn't then a test written using the fetch-mock API won't catch the bug.

**Comment by Raphaeljunior** [comment]
@choumx  After some reading I think Sinon would be the better option. Though fetch-mock has a good api it will not play well with our build system. It doesn't use ES 6 and it doesn't play well with karma.

**Comment by jridgewell** [comment]
Sinon can't be used because it doesn't mock `fetch` at all, only XHRs.

**Comment by Raphaeljunior** [comment]
Can't we stub out fetch the way we stub out methods?

**Comment by jridgewell** [comment]
That's what we currently do, we're looking for something that's a bit more ergonomic.

**Comment by taymonbeal** [comment]
I'm going to take another look at seeing how hard it would be to hack the Sinon fake server to support `fetch`. It'd sure be nice if we could use the same framework we already use.

In the meantime, [a possible way around the fetch-mock problems](https://www.npmjs.com/package/chai-fetch-mock).
