### ISSUE TITLE
No-fill behavior for amp-fx-flying-carpet

### ISSUE THREAD

**Issue by outoftime** [ampproject/amphtml#10471]
The `amp-fx-flying-carpet` component is cool, but it doesn’t seem to have any no-fill behavior—meaning that if you put an ad in it and the ad request doesn’t fill, you just have a big, blank interscroller.

It seems like this could work similarly to `amp-sticky-ad`, where the container is aware of the fill status of the ad itself, and collapses if the ad doesn’t fill (assuming as always that the layout of the currently-visible content isn’t affected).

**Comment by jridgewell** [comment]
It will (try to) collapse if the add calls `#noContentAvailable`. See https://github.com/ampproject/amphtml/issues/3338, and https://github.com/ampproject/amphtml/pull/3721.

**Comment by coreybyrnes** [comment]
@outoftime I found this ticket when trying to debug this exact issue.

1. A new ticket has been opened to try to solve this: https://github.com/ampproject/amphtml/issues/19297

2. Calling `context.noContentAvailable` from within a DFP ad in the hopes of forcing the collapse of the flying-carpet component is failing for me - yielding a "Uncaught DOMException: Blocked a frame with origin "https://tpc.googlesyndication.com" from accessing a cross-origin frame." @jridgewell @zhouyx should I open a new ticket for this?

**Comment by zhouyx** [comment]
@coreybyrnes Regarding 2. Is there another issue opened for that? I knew @bradfrizzell is on it right?

**Comment by coreybyrnes** [comment]
@zhouyx re:2 @bradfrizzell was able to help me resolve this today... the following chunk renders a no-fill in the ad slot and will hide the amp-ad and component container (if present):

`<script type="text/javascript">
if (!window.context) {
	window.addEventListener('amp-windowContextCreated', () => {
		window.context.noContentAvailable();
	});
	
	ampContextScript = document.createElement('script');
	ampContextScript.src = 'https://3p.ampproject.net/'+window.AMP_CONTEXT_DATA.ampcontextVersion+'/ampcontext-v0.js';
	document.head.appendChild(ampContextScript);
}
</script>`
