### ISSUE TITLE
validator user_agent

### ISSUE THREAD

**Issue by elisei** [ampproject/amphtml#10472]
Hello in our project we use the user_agent check for content delivery amp. However in validation testing is not captured the corresponding and accurate view of information which user agent is being used.

**Comment by elisei** [comment]
To complement the doubt, tests done in the same domain in 2 google test tools:

https://validator.ampproject.org/#url=https%3A%2F%2Fwww.cristaisaquarius.com.br
Result: PASS

https://search.google.com/test/amp?utm_source=wmx&utm_medium=link&utm_campaign=wmx-agg&id=N2AfhzVgCr_f8_b4yq2PSQ
Result: Fail

What is the right tool for the test?

**Comment by jridgewell** [comment]
Testing it, it seems to make two requests:

1. `User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)`
2. Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)

Either way, this is a Google specific question and should be ask here: https://goo.gl/utQ1KZ
