### ISSUE TITLE
Integrate code coverage

### ISSUE THREAD

**Issue by taymonbeal** [ampproject/amphtml#10480]
As I make API changes within A4A that sometimes require reworking tests and deleting ones that no longer make sense, it'd be nice to have a good picture of which parts of the code are still covered by tests. Can there be a gulp command that runs the tests and produces a coverage report? We might also consider integrating something like Code Climate or Coveralls in order to use this as a code health metric (but this is less important than just being able to get coverage information at all).

**Comment by danielrozenberg** [comment]
@rsimha I believe this was added as part of our CI, correct? I'm closing this, reopen if I'm wrong :)

**Comment by rsimha** [comment]
Correct, this is done. We now have a dashboard at https://codecov.io/gh/ampproject/amphtml/branch/master, and you can generate a local code coverage report by running `gulp test --a4a --coverage`, for example
