### ISSUE TITLE
Intent to implement: Brightcove player embed

### ISSUE THREAD

**Issue by mister-ben** [ampproject/amphtml#1048]
This proposed [`amp-brightcove` component](https://github.com/BrightcoveOS/amphtml/tree/brightcove/extensions/amp-brightcove) would embed a responsive Brightcove player in an iframe. This single component would support publishers using either Brightcove's Video Cloud or Perform products.

Attributes specifying the publisher's account, player and video ids determine the embed url that will be used.

Example:

```html
<amp-brightcove
    data-account="12345"
    data-player="default"
    data-embed="default"
    data-video-id="54321"
    layout="responsive"
    width="480" height="270">
</amp-brightcove>
```
The above would yield `https://players.brightcove.net/12345/default_default/index.html?videoId=54321`.

The component supports a pause postMessage event to pause the video.

**Comment by dvoytenko** [comment]
@mister-ben Is this something you'd like to take a stab at?

**Comment by mister-ben** [comment]
Certainly. I've put a working example together at https://github.com/BrightcoveOS/amphtml/tree/brightcove/extensions/amp-brightcove

**Comment by cramforce** [comment]
LGTM

**Comment by dvoytenko** [comment]
Looks great. I have a few comments that would be easier to discuss in PR. Thanks!

**Comment by mister-ben** [comment]
Thanks. Closing in favour of PR #1052. Look forward to your feedback.

**Comment by dvoytenko** [comment]
Let's keep this open until we merge the PR.

**Comment by mister-ben** [comment]
Thanks for the feedback on the PR. I think I've addressed those issues.

**Comment by mister-ben** [comment]
Thanks for merging the PR! Do merged extensions eventually get added to the CDN hosting at cdn.ampproject.org?

**Comment by cramforce** [comment]
We typically do weekly releases (thursday) but @erwinmombay might do one later today.

**Comment by erwinmombay** [comment]
yep, i will be doing a release in a couple of minutes.

**Comment by dvoytenko** [comment]
One quick note - the validator rules have not been updated yet. The release will happen, but there will be errors in console. See #1079. This will allow anyone to experiment freely and hopefully the validator will be updated shortly.

**Comment by mister-ben** [comment]
Great, I see it on the CDN now. Thanks!

**Comment by mister-ben** [comment]
Just a couple more questions, around the validator.

- Can the component be used on production pages today, or do publishers need to wait until the validator is updated? For example, would this negatively affect page rankings?
- How often is the validator updated, typically?

**Comment by dvoytenko** [comment]
@mister-ben 

> Can the component be used on production pages today, or do publishers need to wait until the validator is updated? For example, would this negatively affect page rankings?

Yes. Unfortunately, they have to wait. But they can definitely experiment, try things, provide feedback, etc.

> How often is the validator updated, typically?

We will try to do this by the end of this week. We are currently in the process of streamlining the release cycle for validator. Eventually we hope to get the updated at nearly the same time, but not there quite yet.

**Comment by mister-ben** [comment]
Great. Thanks for the info and making this a painless process.
