### ISSUE TITLE
Reduce verbosity of `gulp test` logs

### ISSUE THREAD

**Issue by rsimha-amp** [ampproject/amphtml#10482]
Several tests run on Travis have extremely verbose logs in the passing case. Reduce the log spew, while retaining the ability to see logging in case of errors.

**Comment by rsimha-amp** [comment]
Sauce labs logs could do with some love.

**Comment by rsimha-amp** [comment]
With the changes above, here is what logs look like:

Native terminal app on macos:
![](https://user-images.githubusercontent.com/26553114/28429949-a541c6f0-6d4c-11e7-96a4-bf85b76af1c7.png)

Native terminal app on linux:
![](https://user-images.githubusercontent.com/26553114/28430135-5b4d63dc-6d4d-11e7-80f3-7e9f8b64d5b1.png)

Travis logs in a browser on macos:
![](https://user-images.githubusercontent.com/26553114/28430217-b0c6df8c-6d4d-11e7-9d44-332e53a10887.png)

Travis logs in a browser on linux:
![](https://user-images.githubusercontent.com/26553114/28430185-95a5f634-6d4d-11e7-8641-c07bc7523f4e.png)

Travis logs in a browser on ios:
![](https://user-images.githubusercontent.com/26553114/28430344-2bfb785c-6d4e-11e7-8f31-a0d7f74be8df.png)

**Comment by lannka** [comment]
This is awesome!

Shall we also make local tests less verbal? Especially when a test failed, it will start to print one line for each following test, then you have 5k lines to scroll back in terminal to see the original failure. 

Or, if possible, a summary with failure details at the end of the test can be an alternative solution.

I might open a separate issue for this request, but just want to have some early feedback from you here.

**Comment by rsimha-amp** [comment]
@lannka, can do. Let's use this issue. Can you give me more details about exactly what you want to see on the screen when you're running tests while developing? For `gulp test`? For `gulp test --integration`? For `gulp test --files`? There's now a new mode `gulp test --testnames` that lists every test that's being run. I left the local development logs alone because I didn't want to disrupt what everyone is used to, but if you feel this could help you, I'm happy to make the changes.

**Comment by choumx** [comment]
In think what's being shown on Travis now would be great for local dev: dot matrix, "summary" and "failed tests" (if any) sections.

**Comment by lannka** [comment]
+1

**Comment by rsimha-amp** [comment]
@choumx @lannka, SGTM. Note that if we switch to showing a summary at the end, you'll have to wait until the end of a test run to see the summary. In some cases, this may delay when you see that a particular test has failed, but it's trivial to hone in on the failures you care about by using `--files`. PR coming up.

**Comment by lannka** [comment]
@rsimha-amp would errors be printed immediately after a failure?

**Comment by rsimha-amp** [comment]
@lannka, no, errors are only printed at the end with the `super-dots` reporter + `mocha` summary, or with the full `mocha` reporter.

`super-dots` + `mocha` summary:
<img width="1234" alt="screen shot 2017-07-20 at 3 04 35 pm" src="https://user-images.githubusercontent.com/26553114/28434375-0983d8b4-6d5d-11e7-929c-6a1298cccd8b.png">

`mocha` with full logging:
<img width="1258" alt="screen shot 2017-07-20 at 3 02 56 pm" src="https://user-images.githubusercontent.com/26553114/28434337-f375b830-6d5c-11e7-8046-6f3b99ac41fc.png">

**Comment by lannka** [comment]
@rsimha-amp all is great
just one thing with the `--files` flag. we lost immediate feedback when running saucelabs tests locally.
See: https://gist.github.com/lannka/6aac5552a6aa1c100f99afa2d79dcfee

**Comment by rsimha-amp** [comment]
Validator could use some fixes here.
