### ISSUE TITLE
Linter doesn't pick up extra semicolons

### ISSUE THREAD

**Issue by bradfrizzell** [ampproject/amphtml#10499]
Steps to reproduce: 

1. Add a second semicolon at the end of any line. 
2. Run `gulp lint`
3. Observe no lint error.

**Comment by rsimha-amp** [comment]
I believe this is obsolete.

**Comment by rsimha-amp** [comment]
Perhaps not!

**Comment by bradfrizzell** [comment]
Thanks Raghu! You are just closing issue after issue of mine this week!!! Very much appreciated :D :D
