### ISSUE TITLE
 AMP Viewer: Issue with `position:fixed` header

### ISSUE THREAD

**Issue by eike-hass** [ampproject/amphtml#10497]
## What's the issue?

In the AMP viewer in Google search results the `position:fixed` header of our app is offset by the viewers titlebar height.
As per communication with @sebastianbenz: ping @dvoytenko 

## How do we reproduce the issue?

Find a video attached:
https://gfycat.com/gifs/detail/FrighteningGreedyDassierat

## What browsers are affected?

Chrome 59.0.3071.125 on Google Pixel XL (Android 7.1.2), other devices seemed ok

## Which AMP version is affected?

We will follow up with this information

**Comment by jridgewell** [comment]
This was [broken](https://github.com/ampproject/amphtml/pull/10366) in the latest canary. We've since [fixed](https://github.com/ampproject/amphtml/pull/10436), and this will be patched into canary before it's pushed to prod.
