### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded for iframe with very large srcdoc

### ISSUE THREAD

**Issue by adamsilverstein** [ampproject/amphtml#10495]
We are seeing a "Uncaught RangeError: Maximum call stack size exceeded" error in chrome stable and dev, on this page:

https://fivethirtyeight.com/features/the-warriors-are-in-the-goat-debate-but-they-blew-their-chance-to-end-it/amp/

We use amp-iframes to display complex tabular data, and the existing non-amp tables are passed to the iframe in the iframe via srcdoc property. This works well, except for this post which has a very large dataset. Removing the table in staging fixed the issue in my testing.

Possible related: https://github.com/ampproject/amphtml/issues/7476

**Comment by adamsilverstein** [comment]
Thanks @jridgewell! How long until this fix makes it to production? when can we test that the issue is resolved?

**Comment by adamsilverstein** [comment]
Oh, looks like its already resolved, no longer seeing the issue on our post. Thanks again.

**Comment by jridgewell** [comment]
It'll likely hit canary testing today, with it going to prod next week. Did the `srcdoc` get smaller?

**Comment by adamsilverstein** [comment]
no, actually I misspoke, our issue persists.

**Comment by adamsilverstein** [comment]
verified resolved in chrome 59 stable, thanks again.
