### ISSUE TITLE
Attribute 'on' inside <option> tag

### ISSUE THREAD

**Issue by jacobovidal** [ampproject/amphtml#10492]
I am trying to use an event when an users taps on an specific option inside a `<select>` element but the attribute on doesn't work for `<option>` tags, example:

```
<select name="country" id="country" required >
    <option value="UK">United Kingdom</option>
    <option value="ES" on="tap.mobile.hide">Spain</option>
</select>
<input type="text" id="mobile" name="mobile">
```

Is this normal behaviour or Is this an issue? 

I am asking this because on the [documentation](https://github.com/ampproject/amphtml/blob/master/spec/amp-actions-and-events.md#element-specific-events) says tap event works on any elements.

Last question, Is there any other option to launch an event when user selects specific options inside a form?

Thank you!

**Comment by aghassemi** [comment]
@jacobovidal , `tap` won't work on options inside `select`, for your use-case, I suggest using `change` event with [amp-bind](https://ampbyexample.com/components/amp-bind/) to dynamically hide/show items based on selection. 

I created a sample here: https://codepen.io/aghassemi/pen/jwooJZ?editors=1111 
```
<script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>
```

```
<select on="change:AMP.setState({selectedCountry:event.value})" name="country" id="country" required >
  <option value="UK">United Kingdom</option>
  <option value="ES">Spain</option>
</select>
    
<input [class]="selectedCountry == 'ES' ? 'hide' : ''" type="text" id="mobile" name="mobile">
```

Hope this help. Closing the issue, feel free to reopen if you need further assistant.
