### ISSUE TITLE
amp-imgur needs to correct the iframe url of imgur embed

### ISSUE THREAD

**Issue by envieme** [ampproject/amphtml#10490]
amp-imgur extension sets  iframe.src = 'https://imgur.com/a/' in line 82 but it should be 'https://imgur.com/' as adding /a/ returns error not found from imgur server.

**Comment by aghassemi** [comment]
@techhtml Some imgur Ids don't work with the `/a/` in the URL, some do. Doesn't seem to be related to "album" vs "single" either. For instance `uRLxX` works with `/a/ in the Url but `TmetrI9` doesn't. Not sure what dictates this scheme and how we can detect which Url to use.

**Comment by techhtml** [comment]
I changed the link will `imgur/{data-id}/embed` will works well.
basically imgur create that embedding URLs.

I do some tests and send PR.

**Comment by kevinhq** [comment]
Can someone here update the docs there: https://www.ampproject.org/docs/reference/components/amp-imgur ?

It still mention to use `data-imgur-id="f462IUj"` while it should be `data-imgur-id="a/f462IUj"`

**Comment by techhtml** [comment]
@kevinhq Did you have some problems when using amp-imgur?
Please file a issue, than I will check it.
