### ISSUE TITLE
Feature Request: 'domain:none' option on amp-analytics in order to test from local host

### ISSUE THREAD

**Issue by doc-tongue** [ampproject/amphtml#10491]
## What's the issue?
Test GA from localhost

**Comment by avimehta** [comment]
@doc-tongue amp-analytics should work on localhost without any changes. By default, amp-analytics finds the top most domain to write cookies on. For localhost, it'll write the cookies to `localhost` and path: `/`.

If running on localhost is not working, can you post the repro steps for what you are running, what you expect to see and what you are seeing instead?

**Comment by avimehta** [comment]
closing the issue. please reopen if needed.
