### ISSUE TITLE
Incorrect Invalid Page Warning in Google Search Results

### ISSUE THREAD

**Issue by macaqueio** [ampproject/amphtml#10494]
If you search https://www.google.co.uk/search?q=Buddy+Holly+Signed+Single&oq=Buddy+Holly+Signed+Single and select the presleycollectibles.com page from the search results it renders an error page "Sorry this page is not valid AMP HTML" with the option to go to the main site.

However, the page is valid and always has been so I am not sure why this error is showing. There are a few other pages on the same site, which also show as being invalid in the search results but test as valid. Any ideas?

**Comment by jridgewell** [comment]
There seems to be a redirect from the URL we have (https://presleycollectibles.com/store/buddy-holly-peggy-sue-78rpm-10-inch-single/amp/) to a non-AMP page https://presleycollectibles.com/store/buddy-holly-hand-signed-peggy-sue-10-inch-single/. Forwarding it to the AMP page https://presleycollectibles.com/store/buddy-holly-hand-signed-peggy-sue-10-inch-single/amp should fix this.

**Comment by macaqueio** [comment]
The redirect is correct because the URL of the page has been updated and so has the site map for the site and the amp html link in the head of the standard html page. But the old url is still cached in Google search results and throws the error. It would appear the site owner has done everything correctly. Is this expected behaviour?

**Comment by jridgewell** [comment]
This is a Google Search specific question, not AMP. Try asking in the Google forum? https://goo.gl/utQ1KZ
