### ISSUE TITLE
amp-bind crashes IE 11 with "Argument not optional"

### ISSUE THREAD

**Issue by 10xjs** [ampproject/amphtml#10522]
## What's the issue?

In IE 11 amp-bind crashes on initial load. `Argument not optional` is thrown here: https://github.com/ampproject/amphtml/blob/3b8c24b4dcd4aa6f8f026e9634d53d0ed8b50dd3/extensions/amp-bind/0.1/bind-impl.js#L400

This is triggered when amp-bind tries to initialize on the `body` element. (`body` is the first argument of `createTreeWalker` here)

![image](https://user-images.githubusercontent.com/1074748/28346352-64449604-6be5-11e7-8d91-3dc36a90551a.png)

## How do we reproduce the issue?

Visit https://ampbyexample.com/components/amp-bind/preview/#development=1 

If this is a feature request you can use this section to point to a prototype/mockup that will help us understand the request.

## What browsers are affected?

![image](https://user-images.githubusercontent.com/1074748/28346401-c0216966-6be5-11e7-9006-9e3457887b3a.png)

## Which AMP version is affected?

Discovered on version 1499807487098

**Comment by choumx** [comment]
Looks like the same issue as: https://github.com/webcomponents/webcomponentsjs/issues/556

Thanks for the report. Working on a fix now.
