### ISSUE TITLE
amp-pinterest ignores `data-height="tall"`

### ISSUE THREAD

**Issue by chenryhen** [ampproject/amphtml#10531]
## What's the issue?

`data-height="tall"` is not changing the how the Pinterest button renders.

## How do we reproduce the issue?

In the AMP playground, if you change the Pinterest button code to
```
<amp-pinterest height="28" width="56"
      data-do="buttonPin"
      data-url="https://ampbyexample.com/"
      data-media="https://ampbyexample.com/img/amp.png"
      data-description="amp-pinterest in action"
      data-height="tall" >
    </amp-pinterest>
```
per the documentation: https://www.ampproject.org/docs/reference/components/amp-pinterest
You see this
<img width="399" alt="screenshot 2017-07-19 14 09 46" src="https://user-images.githubusercontent.com/5115651/28382504-5bedd446-6c8c-11e7-8517-b59365843ef4.png">

Similarly, if you try to create a large round button:
```
 <amp-pinterest height="32" width="32"
      data-do="buttonPin"
      data-url="https://ampbyexample.com/"
      data-media="https://ampbyexample.com/img/amp.png"
      data-description="amp-pinterest in action"
      data-height="tall" data-round="true" >
    </amp-pinterest>
```
You get this:
<img width="368" alt="screenshot 2017-07-19 14 13 47" src="https://user-images.githubusercontent.com/5115651/28382563-884219e4-6c8c-11e7-9f5f-3c68f50df21f.png">

## What browsers are affected?

Testing on latest Chrome, MacOS 10.12.6

## Which AMP version is affected?
AMP 1499807487098

**Comment by levidurfee** [comment]
hi @chenryhen ! 

Thank you for submitting this issue. I'll be looking into it this weekend. I'll let you know what I find or if I have any questions :)

**Comment by levidurfee** [comment]
@chenryhen , would you mind trying something for me?

If you change your `data-height` attribute to `data-tall`, then the value _should be_ `true`, but I think it'll work with anything in there.

I was looking at the [docs](https://www.ampproject.org/docs/reference/components/amp-pinterest) for this component and it does say `data-height`. However I don't see anything in the code that uses `data-height`.

When you get a chance, please let me know if that works for you.

**Comment by chenryhen** [comment]
@levidurfee that works! Thanks

**Comment by levidurfee** [comment]
That is great news, @chenryhen ! Thank you for taking the time to try that.

I'll check to see I should create a pull request for the other things I noticed while looking into this.

/cc @aghassemi

**Comment by aghassemi** [comment]
@levidurfee Thanks for looking into this.
