### ISSUE TITLE
Return the status of a Percy build in pr-check.js

### ISSUE THREAD

**Issue by rsimha-amp** [ampproject/amphtml#10536]
This would allow us to flag failing `master` builds on Travis CI

**Comment by rsimha-amp** [comment]
Update: We now have an API from Percy for querying a build's status. However, blocking failing builds on `master` and release branches would require us to use separate baselines for each branch. Currently, we can only block releases if we create PRs on the release branch, and I don't believe we do this. Still investigating alternatives.

/cc @cramforce

**Comment by rsimha-amp** [comment]
If we create a PR for each release branch as part of the release workflow, Percy has native support for choosing a different baseline than the one used on master for release branches, based on when they were branched off. This will solve the problem of features being in master but not in a release branch, and will give us the ability to block a release via Travis if visual tests fail.

So it comes down to creating a PR for each release branch, something I don't think we do today. I wonder if  one of https://github.com/uiureo/github-pr-release or https://github.com/motemen/git-pr-release could be used to generate a PR as part of the release workflow.

/cc @erwinmombay @choumx for comment.

**Comment by rsimha-amp** [comment]
Ping @erwinmombay @choumx: Still waiting on your input re: creating a PR for each release.

**Comment by choumx** [comment]
I'm supportive if creating the PRs are mostly automated.

**Comment by erwinmombay** [comment]
you can create a PR with a single line of curl, the problem is having to clean it up etc since this is the only reason why we would create the PR

**Comment by rsimha-amp** [comment]
Step 1 is complete. We now have a way to retrieve the status of a Percy build at https://amphtml-percy-status-checker.appspot.com/status?build_id=XXXXXX. On to the next steps.
