### ISSUE TITLE
Implementation of VideoInterface for gfycat-amp player

### ISSUE THREAD

**Issue by koshka** [ampproject/amphtml#10537]
Autoplaying gfycat-amp videos should be paused when out of viewport.

Was mentioned in #6863

**Comment by koshka** [comment]
@aghassemi I think you requested this feature in #6863
Does this issue needs to be assigned to me or tagged before I make a pull request?

**Comment by aghassemi** [comment]
@koshka Assigned. If you have any questions about implementing video-interface, please ping me on Slack or GitHub. 
`amp-youtube.js` and `amp-brid-player.js` have a good reference implementation of the video-interface.

**Comment by koshka** [comment]
@aghassemi thank you. Can you please review this PR #10583 or assign someone?

**Comment by aghassemi** [comment]
@koshka Thanks for the PR. I assigned to myself. Will review soon.

**Comment by aghassemi** [comment]
Implemented in #10583
