### ISSUE TITLE
Add info about percy in contributors guide

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#10540]
We should 

- explain how people can get access to percy (for now: google form to submit email?)
- what to do if there is a failure.

**Comment by rsimha-amp** [comment]
Good idea. I've already added a small blurb to `DEVELOPING.md`, and will add more details soon.

**Comment by rsimha-amp** [comment]
@cramforce, I wrote up a new section on visual diff tests in DEVELOPING.md and sent you #10581 for review. I've also created a google form to accept requests for access to the percy snapshots.

**Comment by rsimha-amp** [comment]
It turns out we need to provide installation instructions.
