### ISSUE TITLE
(chore) Port services to have independent factory files and implementation.

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1055]
In particular we'd like to do this for all services that are always eagerly loaded in the main JS binary. Because then extensions do not redundantly load the implementations – which will decrease their JS size.

Services are just files that use the "src/service.js" module and typically have a somethingFor method.
# 1039 does this for the history service and all other services should be converted in exactly the same way.

The current list of services are: 
- ~~viewer.js~~
- ~~viewport.js~~
- ~~vsync.js~~
- ~~history.js~~
- document-info.js
- platform.js
- ~~resources.js~~
- preconnect.js
- ~~url-replacements.js~~
- ~~xhr.js~~
- ~~action.js~~

Some may now require explicit installation in amp.js, so we make sure they are really always installed there.

**Comment by erwinmombay** [comment]
@AaronCritchley is interested on working on this one.

**Comment by cramforce** [comment]
Great. Lets do it one or 2 services at a time for PRs. Just comment the once you have in-flight here.

**Comment by cramforce** [comment]
We should also remove the export of viewer and viewport from runtime.js when this is done.

**Comment by dvoytenko** [comment]
Those exports are due to the viewer integration. But certainly cleanup is due.

**Comment by cramforce** [comment]
Ah, cool. lets leave them
