### ISSUE TITLE
gulp check-types did not catch mistake.

### ISSUE THREAD

**Issue by bradfrizzell** [ampproject/amphtml#10580]
@keithwrightbos had a type error in the Doubleclick fast fetch launch PR that was not caught by check-types.

This is the line in question: https://github.com/google/amphtml/blob/55a1c902333ef8322bb3a814362911fc89c2e987/extensions/amp-ad-network-doubleclick-impl/0.1/doubleclick-a4a-config.js#L101

branches should be an array of strings, not an object, as per: https://github.com/ampproject/amphtml/blob/master/src/experiments.js#L55

Not sure why the type checker did not catch this, but it seems like it should have.

**Comment by bradfrizzell** [comment]
Marked as P1 because if check-types didn't catch this, presumably there's other instances it's missing too that we just haven't stumbled across.

**Comment by choumx** [comment]
Closure doesn't appear to enforce missing generics. Here's a [simple example on their sandbox app](http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B!Object%253Cstring%252C%2520boolean%253E%257D%2520a%250A%2520*%252F%250Afunction%2520foo(a)%2520%257B%257D%250A%250A%252F**%2520%2540type%2520(!Object)%2520*%252F%250Avar%2520x%2520%253D%2520%257B%257D%253B%250Afoo(x)%253B%250A%250A%252F**%2520%2540type%2520(!Object%253Cstring%252C%2520string%253E)%2520*%252F%250Avar%2520y%2520%253D%2520%257B%257D%253B%250Afoo(y)%253B%250A%250A).

```js
/** @param {!Object<string, boolean>} a */
function foo(a) {}

/** @type (!Object) */
var x = {};
foo(x); // No type warning for missing generic type.

/** @type (!Object<string, string>) */
var y = {};
foo(y); // Type warning for mismatched generic type.
```

We can avoid this either by typecasting the input object or refactoring the API e.g. use a custom object instead.

/cc @erwinmombay
