### ISSUE TITLE
Pinterest social button does not have image_url set up

### ISSUE THREAD

**Issue by njuljsong** [ampproject/amphtml#10592]
## What's the issue?
When I include `amp-social-share-0.1.js` to display share buttons in AMP content, I find that Pinterest button does not correctly include the `image_url` parameter,  the pop up window does not show any image, and I cannot share the content.

## How do we reproduce the issue?
To reproduce, just go to `https://ampbyexample.com/components/amp-social-share/`, click the red Pinterest button, in the pop up window, there is no image showing up, and when you click the `Save` button to save this content in Pinterest, it pops up an error saying: `You need to upload an image or provide the 'image_url' parameter`

## What browsers are affected?

All browsers? Some specific browser? What device type?
All

## Which AMP version is affected?
AMP ⚡ HTML – Version 1500510703681
And this javascript file is involved: `"amp-social-share" src="https://cdn.ampproject.org/v0/amp-social-share-0.1.js"`

**Comment by njuljsong** [comment]
@aghassemi Thanks for the quick fix. Also please fix this doc: https://www.ampproject.org/docs/reference/components/amp-social-share#pre-configured-providers

**Comment by aghassemi** [comment]
Done, docs being updated in PR #10593

**Comment by njuljsong** [comment]
Thanks @aghassemi, Super efficient!
I'll just close it as fixed.
