### ISSUE TITLE
amp-list: Error when items attribute includes array index

### ISSUE THREAD

**Issue by gilbox** [ampproject/amphtml#10613]
## What's the issue?

Using an array index in the items attribute does not work. For example, `items="foo.x"` works but `items="foo.0.x"` does not.

## How do we reproduce the issue?

I created an endpoint that returns the following data at the url `/x`:

```
{"foo":[{"x":[{"name":"bar"},{"name":"baz"}]}]}
```

Then I added the following `amp-list`:

```
        <amp-list
          width="auto"
          height="100"
          layout="fixed-height"
          src="/x"
          items="foo.0.x"
        >
          <template type="amp-mustache">
            <div>
              <div>{'{{name}}'}</div>
            </div>
          </template>
        </amp-list>
```

Which resulted in the error:
```
Response must contain an array at "foo.0.x". amp-list
```

![image](https://user-images.githubusercontent.com/2136203/28546701-8c2cd90c-7080-11e7-9601-2087fabd8e07.png)

## What browsers are affected?

tested on chrome

## Which AMP version is affected?

```
Powered by AMP ⚡ HTML – Version 1500510703681
```

**Comment by robinpokorny** [comment]
Currently, only simple object nesting is supported.

The reason is this line: https://github.com/ampproject/amphtml/blob/master/src/json.js#L100, since `hasOwnProperty` will return *false* for an array and any index.

I'm not sure if such behaviour would be desired.

**Comment by jridgewell** [comment]
That's not quite right, `#hasOwnProperty` will return `true` for array indices. The issue is that `<amp-list>` expects an array, and you've selected an individual item of the array.

**Comment by gilbox** [comment]
@jridgewell 

> you've selected an individual item of the array.

That is incorrect, I've selected this value:

```
[{"name":"bar"},{"name":"baz"}]
```

Anyway, I opened a [PR](https://github.com/ampproject/amphtml/issues/10627) to fix this.

**Comment by robinpokorny** [comment]
@jridgewell, I don't think this is the case.

There is an array at the path `foo.0.x`. This syntax, or similar like `foo[0].x`in [_.get](https://lodash.com/docs/4.17.4#get), could easily be supported. The question is if it should. I'd say yes since sometimes one cannot control the JSON output.

You are right, about `hasOwnProperty`, in fact, an array does not pass the [isObject](https://github.com/ampproject/amphtml/blob/master/src/json.js#L98)

**Comment by jridgewell** [comment]
I see, thanks for looking into it. I'm fine with supporting array indices.
