### ISSUE TITLE
Strip cache specific query params from URLs for use by analytics

### ISSUE THREAD

**Issue by ericfs** [ampproject/amphtml#10624]
The URLs for the AMP Cache may have extra query parameters like amp_js_v that is not part of the original URL and are not needed for analytics. 

Related internal issue: b/63635218

cc @dvoytenko

**Comment by rudygalfi** [comment]
Internal issue resolved. Closing this.

**Comment by rudygalfi** [comment]
@ericfs It seems like `usqp` params for the AMP Cache are still showing up - see #12137. Was the scope of work in this issue intended to remove it from appearing in AMP analytics variables like AMPDOC_URL?

**Comment by ericfs** [comment]
I'm not super familiar with the details of AMP analytics, but I think removing it from those variables makes sense. usqp is a parameter that is added by the viewer to communicate to the cache so it should not be propagated to any publisher facing analytics.

**Comment by rudygalfi** [comment]
I agree with the principle that viewer-specific variables should not get propagated through. Is usqp the only case (and we just didn't catch it / handle it) or are there others?

**Comment by flaviori** [comment]
Yeah it should be stripped same as amp_js param.
One of the goals of the usqp is in fact to group multiple cache parameters in one, so that it's actually easier to handle.

Another one would be amp_lite I think.
