### ISSUE TITLE
Use the newly proposed `scroll-boundary-behavior` for `amp-sidebar`, `amp-lightbox` 

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#10623]
Proposed CSS standard `scroll-boundary-behavior` allows developers to decide the browser's behavior once a scroller has reached its full extent.

When launched, we should use it on `amp-sidebar` and `amp-lightbox` to prevent overscrolling of the parent body (using `contain`)

https://www.chromestatus.com/feature/5734614437986304
https://github.com/w3c/csswg-drafts/issues/769
https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/txdySyr-mb0/tPQJZvJiBw
https://wicg.github.io/scroll-boundary-behavior/AJ

/cc @dvoytenko

**Comment by cramforce** [comment]
CC @dvoytenko

**Comment by dvoytenko** [comment]
We should just do it.

**Comment by rudygalfi** [comment]
Rolling forward to H2 October milestone. Please correct if needed.

**Comment by cathyxz** [comment]
This is good in Chrome and Edge, but not implemented in Safari.

**Comment by dvoytenko** [comment]
@cathyxz Have we deployed this though?

**Comment by cathyxz** [comment]
Nope, sorry. I meant that the `scroll-boundary-behavior` attribute lives in Chrome, but not Safari in case we want to implement it.

**Comment by jridgewell** [comment]
Re: b/118645457. In the meantime, can we fix this behavior for scrollable lightbox? Something similar to the 1px scrollTop hack we do for [iOS embed viewport](https://github.com/ampproject/amphtml/blob/5e6b429319e5d6efb74d483732759c3ea20b8679/src/service/viewport/viewport-binding-ios-embed-wrapper.js#L288-L303).

**Comment by aghassemi** [comment]
@jridgewell We do that already https://github.com/ampproject/amphtml/blob/master/extensions/amp-lightbox/0.1/amp-lightbox.js#L482 b/118645457 happens regardless of scrollable lightbox.

**Comment by jridgewell** [comment]
You're only applying it in scrolling-up direction. You need to apply it to the scrolling-down direction, too.

**Comment by aghassemi** [comment]
@jridgewell  Runtime doesn't do the bottom either  https://github.com/ampproject/amphtml/blob/5e6b429319e5d6efb74d483732759c3ea20b8679/src/service/viewport/viewport-binding-ios-embed-wrapper.js#L296 because it is expensive to do. Probably fine for lightbox though. I will give it a try

**Comment by katsar0v** [comment]
Any update?
