### ISSUE TITLE
`class` attribute binding improvements

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#10622]
Discussion issue to consider improvements for binding to `class` attribute and make it easier to add/remove/toggle dynamic classes, specially when combined with a list of static classes.

### Current ways of binding to `class`
1- `<div class="static class" [class]="dynamicVar1 dynamicVar2 + 'static class'">`
2- `<div class="static class" [class]="dynamicClassArray.join[' '] + 'static class'">`
3- `<div class="static class" [class]="condition ? 'dynamicClass1' : 'dynamicClass2' + 'static class'">`

**Issue** here is mostly around the need to repeat `static class` part in both `class` and `[class]`

### Possible improvements
1- Expose `elem.addClass(class)` , `elem.removeClass(class)` , `elem.toggleClass(class)`  as AMP Actions separate from `amp-bind`
2- Expose a new `addition` syntax in `amp-bind` that would elimiminate the need to repeat the static classes. For instance:
`<div class="static class" [class+]="dynamicVar1 dynamicVar2">`

/to @choumx 
/cc @camelburrito @sebastianbenz @ericlindley-g

**Comment by choumx** [comment]
Thanks for filing this! 

Another option is to add a special variable (`this`?) that returns the initial value of the property:
```html
<div [class]="this + 'dynamicVar1 dynamicVar2'"></div>
```
This would avoid ambiguity in cases where both `[class]` and `[class+]` bindings exist (at the cost of overriding a custom var with the same name).

**Comment by aghassemi** [comment]
@choumx very interesting idea. Having access to the previous value of the attribute you are binding to can be useful in other cases too like `amp-list src="foo.com" [src]="this + '?q=` + search"` I like it :)

**Comment by aghassemi** [comment]
@choumx I guess we need to clarify if `this` is the previous value or original value. In both of our example it is the `original`. `previous` could be useful too but probably our of scope for the problem in hand here. Maybe `initialValue` as the name? (same name as `Array.reduce()` API)

**Comment by sebastianbenz** [comment]
+1 for having a way to access the initial value and removing the need to duplicate the initial state. I'm not a fan of using `this` either, it makes things too confusing (except maybe `this.src`). 

I'm also in favor of being able to toggle a class via action (see [this question](https://stackoverflow.com/questions/45239075/amp-easy-way-to-toggle-a-css-class/45242350?noredirect=1#comment77473521_45242350) on SO). The current approach feels a bit too complicated, in particular, because you need to encode the id into the state variable, which is then repeated three times: 

```
<button on="tap:AMP.setState({heading1Class: heading1Class ? '' : 'active'})">Toggle</button>
<h1 id="heading1" [class]="heading1Class">Hello</h1>
```

**Comment by choumx** [comment]
Merging with #10622.

**Comment by jimmyko** [comment]
The current approach to handle classes is very tedious because you need to store the classes in amp-state. It will be a lot of amp-state data if you want to have such class manipulations on multiple elements in one page.

Why this feature request is closed without much following up?
