### ISSUE TITLE
amp-image: Placeholder fails to hide when unsupported source is supplied

### ISSUE THREAD

**Issue by WillDonohoe** [ampproject/amphtml#10646]
## What's the issue?

In our template we are using WebP and falling back to PNG as recommended by the documentation: https://www.ampproject.org/docs/reference/components/amp-img

We also have a custom placeholder which is visible when the image is loading. However on browsers that do not support WebP, the placeholder fails to disappear when the fallback image loads.

## How do we reproduce the issue?

Please see the attached [codepen](https://codepen.io/willdonohoe/pen/oeXYNx).

1) Open the codepen above in Chrome
2) Open dev tools and turn on network throttling
3) Refresh and notice the loading placeholder (Yellow square) appears while loading and disappears when the image appears
4) Open the same page in Safari (Or a browser which does not support WebP)
5) Notice that the placeholder remains on the screen when the fallback image is loaded.

Note: This issue is not visible when using opaque images, as the fallback image appears over the top of the loader. However our fallback is transparent and therefore the loader can be seen underneath.

## Expected behaviour

`amp-image` should hide the placeholder if the image is not supported.

**Comment by torch2424** [comment]
Was able to reproduce, looking into this now
