### ISSUE TITLE
Design Review 2017-08-16 (modify browser history w/ amp-bind, templates outside of amp-form, custom form validation w/ amp-bind)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#10652]
The AMP Project holds weekly engineering [design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md).  **We encourage everyone in the community to participate in these design reviews.**

Time: Wednesdays @ [1pm Pacific](https://www.google.com/?#q=1pm+pacific+in+local+time)
Location: [Video conference via Google Hangouts](https://hangouts.google.com/hangouts/_/google.com/amp-eng-desrev)

If you are interested in bringing your design to design review, read the [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md) and add a link to your design doc by the Monday before your design review.

When attending a design review please read through the designs *before* the design review starts.  This allows us to spend more time on discussion of the design.

If you are unable to make the 1pm Pacific time due to time zone issues but you have a design you would like to present please make a note of that and we will try to find a time that works.

**Comment by choumx** [comment]
Bumped from last design review: 

- Modify browser history with `amp-bind` via `AMP.pushState()`: https://github.com/ampproject/amphtml/issues/9128#issuecomment-320332045

**Comment by cvializ** [comment]
Bumped from last time:

amp form external templates, amp-form render in template

**Comment by mrjoro** [comment]
browser history with AMP.pushState

- Malte: this is a really cool idea
- support for changing the location/URL?
  - in first version it wouldn't actually change the location/URL (that would be in V1)
  - viewer interaction wouldn't be easy for this part (since it denies serving documents that aren't in the search document); does it matter that it's the same origin? no, that doesn't help us
  - we could explore signing the URLs for this case
  - could ship where it updates the URL when a standalone page but it doesn't update the URL if it's in the viewer; Malte's fine with launching that way
  - amp-bind does not run on page load so you can't do anything to update the state based on that; it can also be problematic if your push state doesn't fully reflect what your query params do; can we instead serialize the state change to the query strong?
- Dima: from UX point of view attaching too many may be problematic
  - typically browser history depth max is 50; behavior is undefined in those cases (typically just replace state), so either we need a hard limit or we do something smarter, perhaps even limit it to 2
  - shouldn't we just add replaceState at the same time?  (which could help developers avoid too big of a stack)
  - one use case is pagination where you go forward many pages and want to be able to click back through pages
- v0.5: change current history service to support forward and back & differentiating branching changes
- when you press something in the UI that semantically undoes the stack from (e.g. open a dialog and then click cancel); you don't want back to open the dialog again; we handle this kind of stuff with sidebar ourselves but once we give developers the chance to add stuff to the history stack then we need to let them get rid of it

**Comment by mrjoro** [comment]
amp form external templates, amp-form render in template

- instead of template prefix we have a template-selector
- any reason not to use classes instead of a selector?  wanted it to be as flexible as possible
- check out what we do with binder (for bind), e.g. with submit success we can re-render a template?  no, but you can bind the text of an element to a response... but if you could render it to a template would that solve this problem?
  - to receive an action it'd need to be in an AMP element
  - form submit should be a high trust action
  - could also use amp-list; amp-list traditionally gets data via XHR but could also get local data--bind the state to an expression that points to whatever you set on form submit
  - instead of the form referring to elements that might change, could have those elements refer to the form
  - should we put the attribute on the template?  that would be harder because we'd need to change the validator
- these other ideas are great, but for this we took the approach of addressing the use case of "I want my template to be outside of the form" but keep doing the same way forms are using templates today--a bit more of a declarative way rather than amp bind
  - in that case have the existing "submit-success" point to the form id (if value isn't specified look for a parent form, if it's specified point to the form)

**Comment by mrjoro** [comment]
custom form validation prompts with amp-bind

- seems like a natural extension of the existing design
- should the events bubble?
  - hard because individual elements of the form may be valid but the form may be invalid
  - maybe the form event is just the logical AND of all of the individual elements
