### ISSUE TITLE
Design Review 2017-08-09 (font-display swap, amp-visibility-observer, amp-date-display and -countdown, amp-form state templates)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#10651]
The AMP Project holds weekly engineering [design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md).  **We encourage everyone in the community to participate in these design reviews.**

Time: Wednesdays @ [1pm Pacific](https://www.google.com/?#q=1pm+pacific+in+local+time)
Location: [Video conference via Google Hangouts](https://hangouts.google.com/hangouts/_/google.com/amp-eng-desrev)

If you are interested in bringing your design to design review, read the [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md) and add a link to your design doc by the Monday before your design review.

When attending a design review please read through the designs *before* the design review starts.  This allows us to spend more time on discussion of the design.

If you are unable to make the 1pm Pacific time due to time zone issues but you have a design you would like to present please make a note of that and we will try to find a time that works.

**Comment by aghassemi** [comment]
Continuation of:
`<amp-date-countdown>`
`<amp-date-display>`
https://docs.google.com/presentation/d/1awrUB2oEZsEC77SteYay0MabAOgGPPDelovtB9nikxk/edit#slide=id.g1f19f58a49_0_51

**Comment by cramforce** [comment]
I'd like to discuss making `font-display: swap` the default in AMP. See

- https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display
- https://css-tricks.com/really-dislike-fout-font-display-optional-might-jam/

**Comment by aghassemi** [comment]
`amp-visibility-observer`: https://github.com/ampproject/amphtml/pull/10818
`amp-date-display`: https://github.com/ampproject/amphtml/issues/10385
`amp-date-countdown`: https://github.com/ampproject/amphtml/issues/10837

**Comment by cvializ** [comment]
If there's time, I have a quick design for #7118 to enable `amp-form` state templates outside of the form body.

**Comment by choumx** [comment]
If time allows:
- Modify browser history with `amp-bind` via `AMP.pushState()`: https://github.com/ampproject/amphtml/issues/9128#issuecomment-320332045

**Comment by aghassemi** [comment]
(consolidated presentation for my stuff: https://docs.google.com/presentation/d/1mFRHhJ11bcrsWV4Wq_OEjG1PerMeU0Rk-OpzCD7-6Wo/edit#slide=id.g24332ce565_0_80)

**Comment by dvoytenko** [comment]
@cramforce RE: font-display

1. (Maybe) make `body {font-display: swap}` as default in `amp.css`. This is what it'll be on the origin.
2. On cache, rewrite `body {font-display: optional}` and all selectors that do `font-family: X` also add `font-display: auto`.

This way, the likely case where icon and logo fonts are used will be worked around.

**Comment by robinpokorny** [comment]
About date parsing in JS in [MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#ECMAScript_5_ISO-8601_format_support):

> Where the string is ISO 8601 date only, the UTC time zone is used to interpret arguments. If the string is date and time in ISO 8601 format, it will be treated as local.

**Comment by dvoytenko** [comment]
@aghassemi Few points of feedback:

1. This is amazing
2. But, need to think events vs streams/state machines
3. The same object can interpolate progress of several concepts: intersectionRatio:[min, 1] and [1, min] vs scroll[0, 1] and [1, 0].

**Comment by dvoytenko** [comment]
@cvializ Few points of feedback:

1. Cool
2. But, let's consider activating templates via binder

**Comment by camelburrito** [comment]
NOTES

using `font-display: swap` - to  swap custom fonts when the font is available

  `font-display: swap` - shows fallback font immediately - and when network loads then swaps the font. 

- Default behavior (implicit swap)- wait 3 secs and show fallback
- Explicit swap (via css) means the wait period does not exist (100ms).
- Safari 10 went from infinite timeout to 3s

**Advantages**:

- Good for initial page paint metric

**Disadvantages:**

- Triggers a whole page relayout
- FOUC

**Suggestions:** 

Inject font display swap from JS/cache as an optin experiment - @cramforce 

**Q:** Can we estimate how much relayout happens with/without cache ? 
**A:** Chrome does not tell you when it shows the page , hard to get metrics

**Comment by cramforce** [comment]
Quick update: The things discussed regarding `font-display` cannot be implemented, because it is a `@font-face` property and not a regular styling property.

**Comment by dvoytenko** [comment]
@cramforce Can we still rewrite `@font-face {}` that are inline in the document's `<style>` and those fonts that are delivered via our CDNs? E.g. `https://fonts.googleapis.com/css?family=Georgia&display=optional`? We could start simply with the 10 most common used family names - those that we know are not icon fonts.

**Comment by aghassemi** [comment]
@camelburrito @dvoytenko  Regarding supporting horizontal axis and therefore needing to extend `ratio` `margin` to include left/right: I am thinking allow an attribute to specify the axis the component works for instead of taking 4 values. This way, the `amp-visibility-observer` can be locked to an axis (which is probably the desired common behaviour) and the numbers would just switch meaning ( top/bottom to left/right ). Flexbox-style naming such as start/end would make this clear.

@dvoytenko I've been thinking about the stream discussions we have. My proposal is this: Keep the syntax as is (given using  event/action syntax is more composable and consistent) instead of intorducing `sync` attributes. _BUT_, behind the scene, we can actually _upgrade_ the connection between the source and the target as soon as the first event is received, since now we have handles to both sides and can design a protocol to move the communication out of the event channel and into its own custom channel). WDYT?
