### ISSUE TITLE
Clarifications re: experiments

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#1065]
A question and few requests regarding AMP experiments.

Question: Is changing the settings at https://cdn.ampproject.org/experiments.html == using the console to  do `AMP.toggleExperiment('experiment-name')`? If so, why does it seem like these are out of sync for me?

Requests:

[1] https://github.com/ampproject/amphtml/blob/master/tools/experiments/README.md says

> Experiments UI is a available at:
> https://cdn.ampproject.org/experiments.js

but it should say:

> Experiments UI is a available at:
> https://cdn.ampproject.org/experiments.html

[2] More info regarding the dev channel is not properly linked from https://cdn.ampproject.org/experiments.html. It should link to:

> https://github.com/ampproject/amphtml/blob/master/DEVELOPING.md#amp-dev-channel-experimental

**Comment by dvoytenko** [comment]
I fixed (1) and (2) in #1069.

Which URL are you trying to call `AMP.toggleExperiment` on? The experiment control is per-domain. The `experiments.html` page enables it for `cdn.ampproject.org`. `AMP.toggleExperiment` enables it for the current domain.

**Comment by rudygalfi** [comment]
@dvoytenko Thanks for the fixes!

The URL was theguardian.com. Your explanation makes sense and answers my question.

I think [the docs](https://github.com/ampproject/amphtml/blob/master/tools/experiments/README.md) can be better. Something like:

> An experiments UI is a available at to enable or disable content served from https://cdn.ampproject.org:
> https://cdn.ampproject.org/experiments.html
> 
> For content served from any other domain, experiments can be toggled in the devtools console when [development mode](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#amp-runtime) is enabled using:
>```AMP.toggleExperiment('experiment name')```

**Comment by dvoytenko** [comment]
#1070 is assigned to you for review.
