### ISSUE TITLE
Fixed element adds miscalculated top property

### ISSUE THREAD

**Issue by raisaveuc** [ampproject/amphtml#10664]
## What's the issue?
I have an element with position:sticky, and the following properties are added:
i-amphtml-fixedid="F2"
style="top:calc(0px)"

Similar to problem described below:
https://stackoverflow.com/questions/44789713/amp-injecting-undesired-styles-style-top-calc0px-when-using-amp-social-s

In my CSS for the sticky-positioned element, I set top: 5rem. I tried this also with a more explicit pixel value (80px) but the top: value still resolves to calc(0px)

Oddly, I can prevent the style from being added to the sticky-positioned element if I add a negative margin-top to the element. So for now my solution is:
{
    position: sticky;
    top: var(--wide-navbar-height); /* resolves to 5rem. Also tried this with explicit px value */
    margin-top: -1px;
  }

Bug request:
It would be great if the added class would calculate the correct top: element for sticky-positioned elements, or if we had the option to turn off an option to add these properties.

## How do we reproduce the issue?

1. Pull from latest commit of ampstart: https://github.com/ampproject/ampstart/pull/562
2. Open e-commerce template blog listing: http://localhost:8000/templates/e-commerce/blog-listing.amp.html#development=1
3. Observe that aside.commerce-blog-sidebar has top: style overridden by incorrect top:calc(0px)

If this is a feature request you can use this section to point to a prototype/mockup that will help us understand the request.

## What browsers are affected?
Checked Chrome, Safari, but probably all

## Which AMP version is affected?

Version 1500510703681

**Comment by jridgewell** [comment]
I don't see a sticky element in the e-commerce example. Can you link to another page?

**Comment by raisaveuc** [comment]
The style is defined in .commerce-side-panel
https://github.com/raisaveuc/ampstart/blob/256285641bf97af99c8e3e8793532aab2a30c55b/css/templates/e-commerce/page.css#L219

The sticky container is here, in the right side panel:
https://amp-ecommerce-qa.firebaseapp.com/templates/e-commerce/blog-listing.amp

However, it now appears that the top position is being properly calculated. When I remove the margin-bottom hack from .commerce-side-panel and let AMP do the top calculation, the position now resolves to "top: calc(80px)" from the 5rem I defined in CSS.

Has the issue been fixed that quickly? :)

**Comment by jridgewell** [comment]
Are you using canary? I've been working on FixedLayer stuff for the past week (https://github.com/ampproject/amphtml/pull/10560), so that probably fixed it.
