### ISSUE TITLE
Better document development and testing workflows involving in-development and experiment-enablable features

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#1066]
There should be a page that provides best practices and guidelines relating to how to work with features that are partially built and under development and those that can be enabled via experiments. (These may be one and the same!)

- What are the common flows and use cases related to turning on experiments to test a new feature?
- Should you do testing only locally or is it ok to deploy to prod in some limited ways? How would that look?
- To test or develop something, should you bring up the whole stack, or target against the prod runtime version? How do you know which to do?
- How should you approach validation (see #1064)?
- What is the cycle for runtime releases, experiments being launched (going to on by default), validation being caught up to features? Does feature being launched == validation is in place?

**Comment by Meggin** [comment]
I'm currently working on a simple experimental page under reference in ampproject.org that can be a starting point for these docs.

I've also created an issue to add an intro table to each tag that covers a number of high level features, including availability, and availability would link off to this experimental page, explaining that that means.

The intro tables will be a benefit on more levels than handling experimental status, but it also means that we can switch 'availability' to focus on whatever version control model we might end up with, should experimental flagging change in the future: https://github.com/ampproject/amphtml/issues/1473

**Comment by rudygalfi** [comment]
https://www.ampproject.org/docs/reference/experimental.html addresses this

/cc  @Meggin
