### ISSUE TITLE
Amp-Analytics - feature ability to trigger multiple GA Event tags on page load

### ISSUE THREAD

**Issue by grantkemp** [ampproject/amphtml#10667]
## What's the issue?
We would like to trigger multiple analytics events on page load via GTM

This can be done via hardcode but not via GTM
```
<amp-analytics type="googleanalytics">
            <script type="application/json">
                {
                    "vars": {
                        "account": "UA-XXXXXX-4"
                    },
                    "extraUrlParams": {
                        "cd1": "name",
                        "cd2": "colour",
                        "pagePath": "https://www.example.com"
                    },
                    "triggers": {
                        "myEvent1" : {
                            "on": "visible",
                            "request": "event",
                            "vars": {
                                "eventCategory": "eventTracking",
                                "eventAction": "eventAction1"
                            }
                        },
                        "myEvent2" : {
                            "on": "visible",
                            "request": "event",
                            "vars": {
                                "eventCategory": "eventTracking",
                                "eventAction": "eventAction2"
                            }
                        }
                    }
                }
            </script>
        </amp-analytics>
```

Briefly describe the bug/feature request.
We currently use GTM to log visits to a page for key brands.  Sometimes there are multiple brands on a particular page and we need to trigger multiple events. 
We wold like to use a custom Variable - which is made up of an array of brands and trigger an event for each brand to enter this into the analytics.

**Comment by grantkemp** [comment]
Thanks @jridgewell .  In addition to above ( and thought about this on the train home) - I also noticed that in order to create the above feature - we should ideally at some stage be moving the Custom Dimensions parameters to sit within the Event object as theoretically each even could have its own set of custom dimensions ( if we follow the Measurement Protocol API) . 

As a short term goal we can keep the Custom Dims in the extra Url params - but maybe that part is a discussion for another Git

**Comment by jeffjose** [comment]
@grantkemp Any updates here?

**Comment by lannka** [comment]
It will be a GTM feature requirement. Can you ask their customer support?
