### ISSUE TITLE
Mobile Chrome's address bar doesn't hide when scrolling up on an AMP page served by the AMP cache

### ISSUE THREAD

**Issue by stefan-all3dp** [ampproject/amphtml#10676]
## What's the issue?

The address bar of Android Mobile Chrome doesn't hide when scrolling up on an AMP page served by Google's AMP cache. It seems that all AMP pages served by the Google AMP cache are affected. I tested it on a Moto G3 Plus.

## How to reproduce the issue?

1. Open e.g this URL with Chrome on an Android Smartphone (not a simulator): https://www.google.com/amp/s/www.engadget.com/amp/2017/07/27/crystals-reusable-transparent-electrical-conductors/
2. If the address bar is visible, proceed with step 3. Otherwise scroll up until the address bar appears.
3. Scroll down. Now, the AMP cache URL bar is hiding but Chrome's address bar doesn't hide anymore. This doesn't happen on AMP pages not served by the Google AMP cache.

## Which AMP version is affected?

I guess it's not an AMP issue, but an issue regarding the implementation of the AMP cache URL bar.

## Screenshot
![screenshot_20170727-210452](https://user-images.githubusercontent.com/11058574/28687649-694344da-730f-11e7-940f-fe8e2000e4e6.png)

**Comment by jridgewell** [comment]
This is with presenting iframes as the "full page". I believe we're waiting on implementation of `rootScroller` that will allow the header to appear/disappear the based on the iframe's scrolling.

**Comment by dvoytenko** [comment]
Correct. This will just work once root scroller is implemented by Chrome. See https://github.com/bokand/NonDocumentRootScroller
