### ISSUE TITLE
amp-social-share email recipient

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#10679]
### Motivation

Several requests have been made to add a recipient field to `<amp-social-share type="email">`. A good usecase for this is to provide feedback to the publisher, using `info@publisher.com` as the address the email is being sent to.

Normally, we'd tell people to use a normal `mailto:` `<a>` element, but there are several issues with mailto links on iOS Safari in the embedded Viewer that are specifically handled by `<amp-social-share>`. Thus, we should add `recipient` to `<amp-social-share type="email">` configuration.

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.  (If you [join the AMP Project](https://goo.gl/forms/T65peVtfQfEoDWeD3) we'll be able to assign this issue to you after you've claimed it.)
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] [Sign the Contributor License Agreement](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#contributor-license-agreement) before creating a Pull Request.  (If you are contributing code on behalf of a corporation start this process as early as possible.)
- [ ] Add `recipient` to the [email configuration](https://github.com/ampproject/amphtml/blob/46ba0938521ea0ee51f97dcdf2c25771406d63c8/extensions/amp-social-share/0.1/amp-social-share-config.js#L67-L70). This should default to the empty string `''`.
- [ ] Append `${recipient}` to the [shareEndpoint](https://github.com/ampproject/amphtml/blob/46ba0938521ea0ee51f97dcdf2c25771406d63c8/extensions/amp-social-share/0.1/amp-social-share-config.js#L66).
- [ ] Update [documentation](https://github.com/ampproject/amphtml/blob/master/extensions/amp-social-share/amp-social-share.md#pre-configured-providers) to include the new `data-param-recipient` param.
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review).  Mention `closes Issue <this issue number>` in the description.
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

### Questions?

If you have questions ask in this issue or on your Pull Request (if you've created one) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

**Comment by akonchady** [comment]
I would like to take this one. Would be my first.

**Comment by cvializ** [comment]
Yes this one is available. If you haven't already, [join the AMP Project](https://goo.gl/forms/T65peVtfQfEoDWeD3) and we will assign the issue to you. Thanks!!

**Comment by akonchady** [comment]
@cvializ I have filled up the form. Please add me.

**Comment by cvializ** [comment]
I think the form takes some time to update. Feel free to begin working on the issue and we'll assign you when the user list updates

**Comment by akonchady** [comment]
@cvializ Sure.
