### ISSUE TITLE
amp-animation: support tilt as a ticker

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#10687]
Essentially tie the progress of an `<amp-animation>` with the tilt value on a particular axis.

Before doing this, we find a few real use-cases and see if the UX that results from this handles those cases.

/cc @dvoytenko

**Comment by 10xjs** [comment]
@ericlindley-g This one of the potential approaches that I suggested for building a 3D VR experience in AMP.

**Comment by ericlindley-g** [comment]
Thanks for flagging this, @10xjs. This is something I discussed w/ the Eng team but couldn't find a viable implementation path. Coincidentally, we made some great progress on a related project that made this much more feasible.

@aghassemi , you may remember the AMP Start museum template that had the really nice UI of a kind of virtual space. It's technically something that we were working on, but might be a nice first example to take as a use case?

**Comment by aghassemi** [comment]
yeah, should be possible to build Paranoma / 360 image viewers with this. Museum template is a great use-case to validate this feature!

**Comment by aghassemi** [comment]
amp-orientation-observer has been launched
