### ISSUE TITLE
Visual diff tests need to include prod/canary config

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#10682]
Visual diff test only test again `gulp build & gulp serve` page, which means it does not test with the experimental flag. 

Discovered through #10656. [percy build link](https://percy.io/ampproject/amphtml/builds/298150)

For example here: A feature with experimental flag 'flag-test' brings a breaking css change. We won't be able to discover that when we launch the feature by toggling 'flag-test' in prod-config. Current test can only discover visual differences after we remove experimental flag 'flag-test' in our code when the feature is stable. This is too late.

Talked to @rsimha-amp. He proposed two ways to fix this. 

1. Serve both configs (canary/prod) from one build and serve cycle, and add tests for both configs
2. Add two separate builds and have two separate percy runs for each PR. (not the best use of resources though)

cc @cramforce

**Comment by rsimha-amp** [comment]
cc @erwinmombay to help figure out what it would take to build the prod and canary amp runtime with one build command, and serve both of them from the same server instance.

**Comment by erwinmombay** [comment]
does it make sense to merge canary and prod configs and always have any field with truthy win out?

**Comment by cramforce** [comment]
Experiments can be in conflict. I think it makes more sense to run tests twice.

**Comment by rsimha-amp** [comment]
I chatted offline with @choumx and came up with a plan to `gulp build` once, but `gulp serve` twice with two different configs, and run two sets of visual tests as part of a single Percy build. Working on it.

Notes:
1. Just one `gulp build`, since it's time consuming
2. Run prod and canary visual tests as part of a single Percy build (to let the PR blocking mechanism work as designed)

**Comment by cramforce** [comment]
The config could be triggered by query param, no?

**Comment by erwinmombay** [comment]
yes, configs can also be triggered by query param

**Comment by rsimha-amp** [comment]
@cramforce @erwinmombay @choumx I figured out an easier way to serve the prod and canary configs with just a single `gulp build` and a single `gulp serve`. It involved calling `gulp prepend-global` with `--canary` and `--prod` after launching the server, but prior to fetching the runtime. I also added a `--remove` flag to `gulp prepend-global`, which will remove any prepended config that might be in the target file. With this, I was able to generate snapshots in one shot.

Let me know if this approach sounds good to you. I'm assuming it's sufficient to add the config to just `amp.js` to switch between prod and canary, correct?

**Comment by erwinmombay** [comment]
that sounds good to me. my only question is which config do we use? 

also for the hash/param approach you'd need to set it to "  "allow-url-opt-in": ["pump-early-frame"]," field so we can't just turn it on through that unfortunately

**Comment by erwinmombay** [comment]
nvm you do it twice once for each config

**Comment by rsimha-amp** [comment]
Yep, I'm generating the entire set of snapshots once for each config in `['prod', 'canary']`
