### ISSUE TITLE
Illegal constructor errors on new Event

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#10709]
This looks to be caused by #10401.

The error example (see p/15995817803022808594):

```
TypeError: Illegal constructor
    at c.b.dispatchCustomEvent (https://cdn.ampproject.org/rtv/001501280976562/v0.js:182:400)
    at https://cdn.ampproject.org/rtv/001501280976562/v0.js:186:358
    at https://cdn.ampproject.org/rtv/001501280976562/v0.js:15:87
```

This appears to be directing straight to https://github.com/ampproject/amphtml/blob/53925edd2d389e526fc43533dae83c527260a014/src/custom-element.js#L1106

Currently only affecting canary, which is supposed to hit PROD early next week. Please either rollback or adjust accordingly.

**Comment by choumx** [comment]
Thanks for catching this. Looks like all the reports are from Internet Explorer (`jse=IE`) which means the polyfill isn't being installed correctly in some cases. Let's rollback for now.

**Comment by choumx** [comment]
Looks good so far. Haven't seen any of these errors in the [patched canary](https://github.com/ampproject/amphtml/releases/tag/1501383761781) today.
