### ISSUE TITLE
amp-tracking broken in AMP shadow 

### ISSUE THREAD

**Issue by p2er** [ampproject/amphtml#10717]
## What's the issue?

amp-tracking and amp-user-notification throws error if used in amp-shadow:
error.js:163 No ampdoc found for [object HTMLDocument]  

## How do we reproduce the issue?

1. Open https://p2er.github.io/amp-articleslider/ampshadow-tracking.html#development=1
2. Open console to see error for amp-tracking and amp-user-notification
3. Open https://p2er.github.io/amp-articleslider/ampshadow-tracking-slide.html#development=1
4. Open console to see that nested AMP page is valid

## What browsers are affected?

Tested on Chrome, but most likely all browsers.

## Which AMP version is affected?

Powered by AMP ⚡ HTML shadows – Version 1501206447946

**Comment by dvoytenko** [comment]
@p2er `amp-user-notification` has been fixed by the #10659 and should be in Canary later this week. But could you please confirm what `amp-tracking` means?

**Comment by p2er** [comment]
Sorry, I meant amp-analytics.

**Comment by dvoytenko** [comment]
@p2er Cool. I think the #10659 then would fix both issues. But, @cvializ could you please check?

**Comment by cvializ** [comment]
Sure, that PR looks like it'll fix both issues, but I can verify that

**Comment by p2er** [comment]
@cvializ any timing on when the fix will become available and amp-analytics will work again in amp-shadow?

**Comment by cvializ** [comment]
I have verified that your above issue is fixed in the canary, so it should be available once the canary is promoted to production later this week, probably Thursday.

**Comment by cvializ** [comment]
The fix has shipped and I don't see the errors in the console. Let us know if you notice this again, but for now I will mark it closed. Thanks for your help!
