### ISSUE TITLE
I've found bug in case-studies page on 

### ISSUE THREAD

**Issue by richaz** [ampproject/amphtml#10713]
## What's the issue?

I've found bag in case-studies page on https://www.ampproject.org/docs/create/. The bag is that Page Not Found. This file does not exist and there was no index.html found in the current directory or 404.html in the root directory. There is screenshot about it http://joxi.ru/Grq1M0RuQELNEr

## How do we reproduce the issue?

You can easily reproduce bag by following to https://www.ampproject.org/docs/create/

## What browsers are affected?

Chrome Browser 59.0.3071.115. Desktop Version on MacBook Pro 2016

My contact azat.success@gmail.com

**Comment by aghassemi** [comment]
@richaz  Thanks for reporting. Can you share where you saw a link that points to this URL? 
/cc @bpaduch

**Comment by bpaduch** [comment]
Issue was on this page: https://www.ampproject.org/case-studies/e-commerce/ in the footer.  I've fixed it.  Thanks!
