### ISSUE TITLE
amp-image won't render after resize in carousel with media attribute

### ISSUE THREAD

**Issue by p2er** [ampproject/amphtml#10718]
## What's the issue?

amp-image won't render content if media attribute criteria is met after resizing, if used in carousel.

## How do we reproduce the issue?

1. Open https://p2er.github.io/amp-articleslider/carousel-image-media.html#development=1
2. Change window width > 500 px and reload
3. Image large is visible
4. Change window width < 500 px 
5. Image large is hidden and image small won't become visible. Carousel is empty.
6. Reload. Image small is visible

## What browsers are affected?

Tested on Chrome, but most likely all browsers.

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1501206447946

## Intention

Desktop and mobile images should be able to receive different resources, e.g. different image formats. Would also apply if mobile should see image and desktop/tablet viewport would see video. Also used if srcset attribute can not provide same condition as media attribute, e.g. media="(min-width: 768px), (orientation: landscape)

**Comment by techhtml** [comment]
This only happen when use in `amp-carousel` extensions.
Maybe some codes are block `amp-img`'s original action.

**Comment by p2er** [comment]
That is correct

**Comment by camelburrito** [comment]
@p2er - not sure if you tried the sizes attribute - https://www.ampproject.org/docs/guides/responsive/art_direction#sizes


@jridgewell - i am pretty sure scenarios like this used to work at some point. Not sure what causes these kinds of issues. Is the only solution to do a vsync/mutate on `onLayoutMeasure` ?

**Comment by techhtml** [comment]
@camelburrito I had used `sizes` attribute on my test and It happened same.

**Comment by dvoytenko** [comment]
@camelburrito @jridgewell It looks like carousel blocks remeasures due to "owner" setup. One option to address this is to implement `isRelayoutNeeded() {return true}` in the carousel and call `this.scheduleLayout(currentSlide)` from the `layoutCallback`. This is a bit of an unfortunate side-effect of owners. The good news is that, if I read it right, `isRelayotNeeded() {return true}` is already done. So, we just need to do `scheduleLayout(currentSlide)` part.

@camelburrito Could you PTAL?

**Comment by camelburrito** [comment]
@dvoytenko - would it not be simple to do ?
```js
this.mutateElement(() => {
  this.showSlide(index);
});
```

**Comment by dvoytenko** [comment]
@camelburrito Probably no b/c it will miss the actual size change. I do think a straightforward `scheduleLayout` will be the most appropriate and most efficient.

**Comment by camelburrito** [comment]
@dvoytenko even with `isRelayoutNeeded` returning `true`, i don't see layout callback being triggered on resize. Is there something that i am missing?

**Comment by dvoytenko** [comment]
@camelburrito Hmm. It looks like it is triggered. We may need to debug this together.

**Comment by jridgewell** [comment]
Fixed by #10831
