### ISSUE TITLE
Create a new `amp-util-date` component

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#10710]
_NOTE: **Design to be reviewed** in AMP Design Review Meeting on Wednesday Aug 2 first. See #10650 to join the meeting_

### Background
AMP HTML restricts use of JavaScript which means some dynamic functionality such as current date/time needs to be exposed through [Extended Components](https://www.ampproject.org/docs/reference/components). 

### Requirements
We like to create a new extended component `amp-util-date` that would display the current date/time given a Date Format. 

For now we would only support very simple formats to avoid loading large Date Formatting JS libraries such as [Moment.js](https://momentjs.com/) or poly-filling JS Intl API, however later we may support more complex formats.

There are various use cases for this component such as:
### Copyright year
```
copyright @<amp-util-date format="YYYY" ><amp-util-date>`

-> copyright @2017
```
### Shipping time (3-day shipping in this example)
```
You item will arrive by:
 <amp-util-date format="m/d"  offset="259200"><amp-util-date>`
// offset would add/subtract seconds from now. 259200 = 3-days in seconds

-> You item will arrive by: 8/30
```

#### format: 
A small subset of formats with the same syntax as [Moment.js](https://momentjs.com/). 
For now we will only support:

Format  | Example
--- | ---
YYYY     | 2017
M     | 8
D     | 28
H     | 20
m     | 45
s     | 20

**Defaults to**:  `YYYY-M-D H:m:s`
#### offset
A value in seconds that will be added or subtracted from the date.

### Implementation Strategy:
- [ ] Create a new Amp Extension. [amp-timeago](https://github.com/ampproject/amphtml/tree/master/extensions/amp-timeago) can be used as a good reference.
- [ ] Use JS's `Date` object to create `now` and add value of `offset` to it.
- [ ] Use simple string replacement on the `format` to get the final result
- [ ] replace the `innerText` of the component with the result.
- [ ] add tests, validation rules, documentation file 
- [ ] add example usage in `examples` folder
- [ ] if you like, also submit a PR for [AmpByExample](https://github.com/ampproject/amp-by-example)

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] Read up on [How to build an AMP extension](https://docs.google.com/document/d/19o7eDta6oqPGF4RQ17LvZ9CHVQN53whN-mCIeIMM8Qk)
- [ ] Follow the **Implementation strategy** from above.
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review).  Mention `closes Issue #10710` in the description.
- [ ] Assign @aghassemi as the reviewer
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

### Questions?

If you have questions ask in this issue or on your Pull Request (mentioning @aghassemi) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

**Comment by techhtml** [comment]
This is awesome1

**Comment by jpettitt** [comment]
**Feature requests**

Please can we have optional params for the following:

1. `data-locale` - a value to pass to `dateObj.toLocaleString() `  (will need to be carefully sanitized)
2. `data-stamp-seconds` - unix epoch (seconds since ...) time stamp 
3. `data-stamp-milliseconds` -  JavaScript timestamp (ms since ...) 

This would allow together this would allow specifying a date that will appear in the users language in the users current timezone.

Also specifying a base date will be required to make the shipping time example work (otherwise the arrival date would always be three days in the future)

**Comment by aghassemi** [comment]
Thanks @jpettitt . Hoping we can expose most of `Intl.DateTimeFormat` functionality with this component but I haven't tested to see how complete the current state of `Intl.DateTimeFormat` is for browsers that claim to have support, and the footprint / quality of available polyfills. 

Ideally we can rely on  `Intl.DateTimeFormat` for most cases and only load the polyfill on-demand for older browsers. Other libraries that have good i18n and timezone support like moment.js have a pretty large foot print.

**Comment by aghassemi** [comment]
Didn't get enough time to go through the design, will be presenting next design review: https://docs.google.com/presentation/d/1awrUB2oEZsEC77SteYay0MabAOgGPPDelovtB9nikxk/edit#slide=id.g1f19f58a49_0_51

**Comment by aghassemi** [comment]
Closing in favor of https://github.com/ampproject/amphtml/issues/10837
