### ISSUE TITLE
Actions: Provide valueAsNumber instead of casting value

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#10729]
We currently support accessing the value of `<input>` elements in actions via `event.value`, e.g.

```html
<!-- Sets variable `foo` to the input[type="range"] element's value on change. -->
<input type="range" on="change:AMP.setState({foo: event.value})"></input>
```

In some cases, the `event.value` is helpfully cast to `Number`: https://github.com/ampproject/amphtml/blob/e430b19ef36154ae6839d5904196ad40263fa85b/src/service/action-impl.js#L268

This is a weird special case and is unintuitive since it diverges from the browser API. Instead, let's _not_ cast `event.value` and instead provide [`valueAsNumber`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement).

- [ ] Remove `Number()` cast on `target.value` in `ActionService#addInputDetails_()`.
- [ ] Set `detail['valueAsNumber']` in the same function.
- [ ] Add corresponding unit test to test-action.js.

Note: IE doesn't seem to support either `valueAsNumber` so a workaround will be needed.

/to @blueyedgeek Now that you've completed a GFI, this is a good "second" issue that's related to amp-bind. Please let me know if you have any questions!

**Comment by choumx** [comment]
@mrjoro Can you invite @blueyedgeek as a collaborator to amphtml? Then I can assign him this issue.

**Comment by blueyedgeek** [comment]
@choumx, pending the time I am given collaborator status, can I go ahead and start working on this issue?

**Comment by mrjoro** [comment]
@blueyedgeek it looks like an invite was already sent out; you should be able to accept it on the [ampproject page](https://github.com/ampproject).  Let me know (here or on Slack) if you're having troubles.

And I'd say you can feel free to start working on this even before it gets assigned to you.  Thanks for taking on a post-GFI project! :)

**Comment by blueyedgeek** [comment]
@choumx, on your list of things to do, the second item is stated as:

`Set detail['valueAsNumber'] and detail['valueAsDate'] in the same function.`

My questions are:

* Is there a need to set `detail[valueAsDate]` as this is only supported for inputs with a type of `date`?
* If `detail[valueAsDate]` should be added, would this also involve adding an extra conditional to check for inputs with a type of `date`?
* For inputs with a type of `range`, won't changing the key being used in  `detail` from `value` to `valueAsNumber` cause breaking changes? Shouldn't only the expression on the right and side be changed? 

```javascript
detail['value'] = target.valueAsNumber
```
Rather than
```javascript
detail['valueAsNumber'] = target.valueAsNumber
```

Seeing as IE doesn't support `valueAsNumber` or `valueAsDate`, wouldn't it be more pragmatic to leave things as they are now?

**Comment by choumx** [comment]
@blueyedgeek Thanks for the input.

> Is there a need to set detail[valueAsDate] as this is only supported for inputs with a type of date?

We should, at a minimum, mimic browser support for this property. There is more than one date-related input type -- search for `valueForDate`: https://html.spec.whatwg.org/multipage/input.html#states-of-the-type-attribute

> If detail[valueAsDate] should be added, would this also involve adding an extra conditional to check for inputs with a type of date?

Yes, but for all date-related input types (see above).

> For inputs with a type of range, won't changing the key being used in detail from value to valueAsNumber cause breaking changes?

Yes, but an internal tool (`cookbook/492126`) shows that there aren't any valid AMP pages using this functionality so I think we're ok. 

> Seeing as IE doesn't support valueAsNumber or valueAsDate, wouldn't it be more pragmatic to leave things as they are now?

It may be. 😄  IMO, the less we diverge from browser behavior the better. Also, it may be convenient for developers to have `valueAsDate`. But I'm open to being convinced otherwise.
