### ISSUE TITLE
Support running _some_ integration tests on IE11

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#10731]
We've had a few IE11 bugs, e.g. amp-bind, amp-ad, amp-carousel: https://github.com/ampproject/amphtml/issues?utf8=%E2%9C%93&q=is%3Aissue%20IE%2011

Those bug fixes don't have any regression protection since [we don't run Saucelabs tests on IE11](https://github.com/ampproject/amphtml/blob/4a9419322d1fa42e6a65c77dd2c35d32bc5a659b/build-system/tasks/runtime-test.js#L69). 

Let's fix that by supporting IE11 on Saucelabs and allow certain tests to opt-in (**disabled by default**). 

/cc @erwinmombay @rsimha-amp

**Comment by choumx** [comment]
OTOH, this problem will fix itself once IE market share becomes negligible. 🤷‍♂️

**Comment by rsimha-amp** [comment]
Fix ready for review at #11030

**Comment by rsimha-amp** [comment]
We now have about a dozen tests enabled and passing on IE 11. More tests may now opt in to being run on IE by adding `enableIe()` to the `describe().configure().run()` chain.
