### ISSUE TITLE
Experiment toggling is not sticky between different .js files on the same pageview

### ISSUE THREAD

**Issue by tlong2** [ampproject/amphtml#10739]
Currently the experiment toggles are "cached" using a global variable defined at the file level: https://github.com/ampproject/amphtml/blob/master/src/experiments.js#L44. This means that for experiments using a simple traffic fraction, toggles determined in amp.js would not be correlated with an experiment toggle determined in amp-ad.js (for example).

The toggles should be cached on a window property so that they are synchronized across all .js files on a given pageview.

**Comment by tlong2** [comment]
Just to clarify that by ".js file" here I mean a final compiled .js binary that is loaded by a page (not every .js file in the source code).

**Comment by lannka** [comment]
This is a known issue: #8970

You can make the toggles global for now. We have a plan to make it a service.

Let's close this and track over there.
