### ISSUE TITLE
Allow access to checkbox/radio value on amp-bind event

### ISSUE THREAD

**Issue by waynepurtonsmith** [ampproject/amphtml#10758]
## What's the issue?

It seems that you cannot access the value of a checkbox or a radio input when using amp-bind. You can only access the `checked` property, accessing the value always returns `null`. There is no way to get it, according to the [actions and events documentation](https://github.com/ampproject/amphtml/blob/master/spec/amp-actions-and-events.md#input-elements)

After checking #10135 and [along with this PR](https://github.com/ampproject/amphtml/pull/10336). The checkbox/input are excluded from the `value` property.

## How do we reproduce the issue?

I think it is important to keep them included, take this snippet for example:

    <input type="radio" name="group" value="members" on="change:AMP.setState({ people: { type: event.value }})" /> Members
    <input type="radio" name="group" value="guests" on="change:AMP.setState({ people: { type: event.value }})" /> Guests

The above snippet won't work, however, if an AMP template is statically or dynamically generated, but a value is known, this is a workaround:

    <input type="radio" name="group" value="members" on="change:AMP.setState({ people: { type: (event.checked) ? 'members' : null }})" /> Members
    <input type="radio" name="group" value="guests" on="change:AMP.setState({ people: { type: (event.checked) ? 'guests' : null }})" /> Guests

Whichever radio input was clicked on, the `people.type` state will never be `null` since the change event will fire the event listener.

## What browsers are affected?

All browsers and devices

## Which AMP version is affected?
Version 1501620723679

**Comment by choumx** [comment]
Thanks for filing this issue. Seems like a reasonable request -- we'll fix soon.
