### ISSUE TITLE
Demo for 'Stack with bind Ad' is not working

### ISSUE THREAD

**Issue by imashishks** [ampproject/amphtml#10751]
The demo for 'Stack with binf Ad' in the experimental section of amp by example page is not working.
https://ampbyexample.com/amp-ads/experimental_ads/stack_with_bind_ad/preview/

**Comment by cvializ** [comment]
@choumx any ideas?

**Comment by cvializ** [comment]
Resolved on slack: https://amphtml.slack.com/archives/C0ADR0A0K/p1501692529630950

> @taymonbeal: Can confirm that `<amp-bind>` is not allowed in AMP HTML for Ads at this time.

**Comment by choumx** [comment]
Please file bugs in for ABE in https://github.com/ampproject/amp-by-example.

The "amp-bind is not upgraded yet" error on that page should've been fixed with #9395. Looks like ABE is serving an old copy of the runtime at `amp-ads.firebaseapp.com/dist/amp.js`. I'll follow up with ABE folks.
