### ISSUE TITLE
Unable to setState on submit-success

### ISSUE THREAD

**Issue by zhangsu** [ampproject/amphtml#10755]
## What's the issue?

The following use of amp-form and setState

```html
  <form method="post"
      action-xhr="<redacted>"
      on="submit-success:AMP.setState({foo: 'bar'})">
    <input type="text" name="content">
    <input type="submit" value="Reply">
  </form>
```

 generates an error:

```
Trust for 'setState' (2) insufficient (min: 100).​​​
```

Is this WAI?

## What browsers are affected?

All browsers

## Which AMP version is affected?

New issue in AMP version 1501206447946.

**Comment by choumx** [comment]
Thanks for the report. I can't repro on latest canary/prod -- probably caused by version skew between `v0.js` and `amp-form-0.1.js`. In hindsight, shouldn't have arbitrarily increased enum value of `ActionTrust.HIGH` in #10166. Please clear cache and try again.

**Comment by zhangsu** [comment]
Uhh this was totally due to version skew. Thanks William!
