### ISSUE TITLE
The attribute 'custom-validation-reporting' in tag 'FORM [method=POST]' is set to the invalid value 'interact-and-submit'

### ISSUE THREAD

**Issue by bluell** [ampproject/amphtml#10773]
## What's the issue?

I'm building the AMP form, and I'm get the below issue from AMP validator.
The attribute 'custom-validation-reporting' in tag 'FORM [method=POST]' is set to the invalid value 'interact-and-submit'.
And then I checked the code below:
https://cdn.ampproject.org/v0/amp-form-0.1.js
```javascript
switch (b) {
  case "as-you-go":
    return new Ua(a);
  case "show-all-on-submit":
   return new V(a);
  case "show-first-on-submit":
    return new U(a)
}
```
I didn't find anything about "interact-and-submit", I don't know is this the bug or version problem.
Please suggest, thanks in advance.

## How do we reproduce the issue?

Please refer: http://jsbin.com/ravakef/edit?html,output
If I use "interact-and-submit", it will not work.
I found this option from document: https://www.ampproject.org/docs/reference/components/amp-form#reporting-strategies

## What browsers are affected?

All.

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1501620723679

**Comment by cvializ** [comment]
Hi! Sorry about that, it looks like we added the docs before the feature was in production. Since it was recently merged it won't be available for ~2 weeks.

Additionally it looks like there needs to be a validator change made to support `interact-and-submit`, which was missed in the #10700. This issue can remain to track the validator change.

**Comment by shahfahad-10p** [comment]
Any update on this? Even though I can see 'interact-and-submit' in the switch case now, but the error is still there.
