### ISSUE TITLE
when open side bar, click in menu item to scroll to an element and them close side bar the page scroll up

### ISSUE THREAD

**Issue by mauricionr** [ampproject/amphtml#10770]
## What's the issue?

when open side bar, click in menu item to scroll to an element and them close side bar the page scroll up

## How do we reproduce the issue?

here [Demo](https://mauricionr.github.io/demos/issues/10770/)

1. Open side bar
2. go to language
3. close side bar
## What browsers are affected?

i guess all

## Which AMP version is affected?

i guess all versions

**Comment by mauricionr** [comment]
with this [approach](https://github.com/mauricionr/mauricionr.github.io/pull/2/files) i got a different behavior, but master has another behavior

**Comment by jridgewell** [comment]
@aghassemi here's another history popstate issue with sidebar.

**Comment by aghassemi** [comment]
changing to p1, this bug totally defeats the whole point of page nav links in sidebar all together.

**Comment by aghassemi** [comment]
@camelburrito @torch2424 do either of you guys cycles to fix this bug? (Essentially sidebar scrolls the main page back to top when closed)

**Comment by camelburrito** [comment]
This is something that MK attempted to fix (I thought he fixed it). I don't think we will have cycles looking into it.

**Comment by aghassemi** [comment]
@mauricionr Looks like links in sidebar have some special logic for handling in-page navigation which requires presence of `href="#id"` on `a` tags. If you add `href` in addition to the smooth-scroll action call, that should fix your issue. (it has the side benefit of properly updating the Url as well). See https://output.jsbin.com/jolebur for a sample.

Let me know if you still have concerns with this issue.

**Comment by torch2424** [comment]
Currently working on improving this in the documentation, to make things more clear.

**Comment by mauricionr** [comment]
Ok :smile: 

but i must put the `href`?

Nicee @torch2424 :tada: 

may i close or keep open this issue?

**Comment by mauricionr** [comment]
thanks @aghassemi

**Comment by aghassemi** [comment]
np. closing the issue
