### ISSUE TITLE
FR: amp-ima-video add support for non-linear ads

### ISSUE THREAD

**Issue by shawnbuso** [ampproject/amphtml#10780]
This can be added to the IMA Launch project. Non-liner ads will only work on Android (they're not supported on iPhone), so first we should talk about whether or not it makes sense to support them if they won't work on iPhone. If so, then we need to tweak a number of things (how controls work, showing/hiding the ad container on play/pause) to make them work.

**Comment by torch2424** [comment]
Assigning to myself as I've been owning amp-ima-video. If anyone needs updates/desires this feature, feel free to mention me while this is in our backlog.
