### ISSUE TITLE
Object.values is undefined

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#10788]
Object.values is not supported

https://github.com/ampproject/amphtml/blame/master/extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js#L337

@keithwrightbos can you evaluate priority. seeing errors on canary but i dont know that code path well enough to evaluate

ill update the linter/conformanceconfig to not allow it

**Comment by lannka** [comment]
@ampproject/a4a can someone take a look at this. the build is planned to go to prod today. but I think it needs to fixed. let me know if you think otherwise.

**Comment by jonkeller** [comment]
Looking. FYI Keith is on vacation this week.
Please let me know if concrete steps to reproduce are known.

**Comment by jonkeller** [comment]
https://github.com/ampproject/amphtml/pull/10836
