### ISSUE TITLE
Local gulp fails to load local copy of JS on proxied page

### ISSUE THREAD

**Issue by keithwrightbos** [ampproject/amphtml#10804]
Steps to reproduce:

- modify local file
- start gulp
- go to proxied publisher page (e.g.  localhost:8000/proxy/amp.cnn.com/cnn/2017/05/11/politics/donald-trump-time-combative/index.html?amp_js_v=9)

Local served JS is ignored in favor of CDN unversioned files.

**Comment by jridgewell** [comment]
It's the `<link as=script rel=preload>` optimization we applied. Our old url replacement only matched the first (the `<link>` now), and didn't match the later `<script>`.
