### ISSUE TITLE
AMP Ads Data Loading Strategy on AdSense Error

### ISSUE THREAD

**Issue by fletc3her** [ampproject/amphtml#10817]
## What's the Issue?

I get a JavaScript error in the console when I use the new "data-loading-strategy" parameter in an amp-ad tag with the "adsense" type. I get the same error if I use either the newer integer value for this parameter or the older "prefer-views-over-viewability" value.

## Steps to Reproduce

Place the following code in a valid AMP document with appropriate client and ad slot.

````
<amp-ad class="adsbygoogle" height=280 layout="fixed-height" type="adsense" data-loading-strategy="0" data-ad-client="ca-pub-xxxxxxxx" data-ad-slot="xxxxxxxx"></amp-ad>
````

The following error appears in the JavaScript console (Chrome).

````
Error: Unknown attribute for adsense: loadingStrategy.
    at A (f.js:14)
    at p.adsense (f.js:105)
    at xa (f.js:11)
    at Id (f.js:219)
    at window.draw3p (f.js:221)
    at frame.html:9
(anonymous) @ f.js:10
````

## What browsers are affected?

Tested on desktop in Chrome and Safari with both reporting similar errors.

## Which AMP version is affected?

Version 1501620723679

This seems to be a new issue. I was using the parameter before without an error.

**Comment by jasti** [comment]
It's possible @zhouyx or @jridgewell worked on the switch to integer value.

**Comment by lannka** [comment]
it was me made it an integer. but i guess the attribute never worked for AdSense.

**Comment by jasti** [comment]
@lannka was there an update on this?
