### ISSUE TITLE
main amp script may not need to be async

### ISSUE THREAD

**Issue by Nemo64** [ampproject/amphtml#10814]
The `amp-boilerplate` is there to hide the content until the main amp script is loaded. It also requires a `<noscript>` to show the content when js isn't available. (a scenario which is hard to support properly in amp btw)

_Why not make the main amp script load synchrones?_

It would eliminate the need for the boilerplate which would also eliminate the initial flash of nothingness until the amp script is loaded.

I created a little test case here: http://coordinator-noises-25015.netlify.com/
I build a page with a few amp components to make it work like a more busy page.

If you switch between the 2 async pages you sometimes have a flash of white between them.
If you look at the 2 sync pages, this does not happen. The same is with the 2 sync pages without boilerplate.

So here is how the async page loads (with cpu slowdown):
![bildschirmfoto 2017-08-05 um 13 44 37](https://user-images.githubusercontent.com/1749936/28995397-80256fb8-79e8-11e7-82fe-22de51c1a7a2.png)
The first frame is already loaded at about 540ms but the thing is: it is a white page. Even worse, the browser had to calculate the layout for a page that is never visible (maybe a concern if multiple pages a preloaded in search results or similar). The actual page is only visible at about 1000ms. The browser even felt the need to relayout the page a second time until it finally rendered the real page.

So let's look at the synchrones load:
![bildschirmfoto 2017-08-05 um 13 42 45](https://user-images.githubusercontent.com/1749936/28995427-3fccd734-79e9-11e7-9b81-49e342e01d1f.png)
The initial frame is rendered at about 820ms but the thing is: It is a complete frame, amp has already initialized the layout and the first frame the browser renders is actually usable. All the other components are still loaded async and executed after the initial frame has rendered. You also see that the rendering time is cut in half. Sure it's only 60 vs 120 ms but my test-page is fairly simple with very few styles.

I can think of a few problems with this. Mainly that the document might be loaded in chunks. But I think that is already handled by amp using the custom element api. If the browser does not support that api, then the amp script could set the body invisible itself without the need of a boilerplate because it is already loaded when the body starts parsing.

Amp components could probably also get simpler because they can rely on the fact that the main script is already there if they load.

Maybe I'm overlooking something but I can't find a reason to have the main amp script asynchrones. Sure: page speed tests will complain about a synchrones script in the head of the doc but making it async and then delay showing the page until it loads isn't going to make the page appear faster for the user.

**Comment by cramforce** [comment]
@Nemo64 Good observation. AMP originally used a sync main script. The reason to make it async is to trick the browser into feeling able to match fonts and download them before JS runs if JS takes a while. Our tests showed this to be a very significant win.

We have a change rolling out to the AMP Cache that can for many pages remove the boilerplate and have the page render independent of the JS. This gives the best of both worlds.

The AMP cache also started inserting a preload script like
`<link rel=preload as=script href=v0.js>`

This makes the main script high priority instead of low priority that is used by browsers for async scripts. One thing I'm doing right now is ask browser vendors to allow web devs to override priority over the heuristic.

Thanks for your post. I'll close the issue, but very happy to discuss more!!!

**Comment by Nemo64** [comment]
Actually fonts were the reason I even noticed.
I experimented with amp-font and a fallback font. Every time I accessed my page, It showed the fallback font for a split second, even when cached. I then attempted to to hide the page until the font are loaded but that felt completely wrong because I'd have 2 styles which hide the page until it is ready and it wouldn't work without javascript because `noscript>style` isn't allowed outside the boilerplate. This problem did not exist when loading the main amp and amp-font synchrones. But I haven't thought about font's not loading until They are used somewhere.

The most frustrating thing is that I tried to make my pages work without javascript and they feel a lot faster without javascript simply because the pages don't flash white on load.

**Comment by cramforce** [comment]
@Nemo64 Right, the white-flash is one of the big benefits of SSR.

I can bring up an API to avoid the white-flash again on web components standards boards. It is really annoying.

**Comment by Nemo64** [comment]
If I understand correctly, the only reason the script needs to be async is that the browser _sorta_ renders the page so that it detects the correct fonts to download before the javascript has been executed, right?

If you are already going the stretch to propose new standards, wouldn't it make more sense to better define how the browser detects which fonts it needs? A heuristic readahead (like it's already done to look for other resources to load) could solve that. Sure, it would be a pretty complicated readahead because it would have to understand css. But the big advantage would be that it would benefit every page.

**Comment by cramforce** [comment]
@Nemo64 I certainly would welcome a better mechanism for font loading. In fact, Edge does eagerly download them, but all other browsers need agree on waiting for download until first layout.

AMP's goal is to be fast in current browsers and we haven't found a better way to reconcile things.

I really wish there was a better mechanism.
