### ISSUE TITLE
FR: expand accordion programmatically

### ISSUE THREAD

**Issue by mauricionr** [ampproject/amphtml#10821]
## What's the issue?

Expand accordion section programmatically

will be awesome one action like this, scroll to an accordion section and expand it

`on="tap:tabreview.scrollTo,tabreview.expand"`

Thanks!

**Comment by aghassemi** [comment]
@mauricionr Turned your request into a Great First Issue: https://github.com/ampproject/amphtml/issues/10826

**Comment by mauricionr** [comment]
thanks @aghassemi :smiley:
