### ISSUE TITLE
Allow amp-iframe to set amp-bind state on parent

### ISSUE THREAD

**Issue by devvercer** [ampproject/amphtml#10828]
## What's the issue?

Feature request.

Inside an amp-form I want to create a custom "coordinate input" component that lets a user pan an embedded Google Map and the current latLng is sent as a form input.

I hoped I could use amp-iframe and amp-bind and when the map moves, call something like:

postMessage({
  sentinel: 'amp',
  type: 'set-state',
  state: {
    lat: theMapLat,
    lng: theMapLng,
  }
}, '*' );

My form would have something like this:

<input type="hidden" name="lat" [value]="lat"/>

**Comment by aghassemi** [comment]
related https://github.com/ampproject/amphtml/issues/9074

**Comment by choumx** [comment]
Closing in favor of #9074.
