### ISSUE TITLE
amp-analytics should have mandatory nodisplay layout, much like amp-font

### ISSUE THREAD

**Issue by powdercloud** [ampproject/amphtml#1082]
I noticed that the recently contributed amp-analytics.js says: isLayoutSupported(layout) { return true; }
I don't think that's cool, it's too loose and means that any layout can be attached to this tag, but that kind of makes no sense because an analytics thing doesn't really have a layout - or does it?
If the analytics engine creates a single pixel, then it should be FIXED, like amp-pixel. This means it should be registered in src/layout.js as an element with natural dimensions.
Otherwise, if it doesn't have any pixels, I think it should go like amp-font, so that means it will have layout=nodisplay required on the tag (as in, users will have to write it).
If there should be some nodisplay default, then it probably needs to be registered in src/layout.js, much like the natural dimensions. But that mechanism doesn't exist yet. I'd go for the explicit layout=nodisplay for consistency with amp-font.
@dvoytenko @avimehta

**Comment by avimehta** [comment]
amp-pixel creates pixels for some of the config settings (it uses xhr or sendBeacon if allowed). Thus it sounds like FIXED is the way go.

@dvoytenko: Are you okay with having code related to extensions in src/layout.js? If yes, I can send a PR to do that. Another solution would be to have the extensions register the fixed size through some API. Not sure how useful that would be though. 

Suggestions?

**Comment by dvoytenko** [comment]
It doesn't sound like this is about `amp-pixel`, but rather `amp-analytics`. Indeed it should have `layout=nodisplay` or, in other words, `isLayoutSupported()` should always return `false`, not `true`. But it looks to me that validator currently enforces `nodisplay`. Or am I wrong?

With that in mind I don't see why we should have any code in `src/layout.js` - can you explain?

**Comment by powdercloud** [comment]
Yes, I'm talking about amp-analytics.
I think the way it goes in the validator is that there is no supported_layout defined for amp-analytics (look for `# <amp-analytics>` in https://github.com/ampproject/amphtml/blob/master/validator/validator.protoascii), so that means the validator does not validate layout, width, height, sizes. It also means that it doesn't allow any of these attributes, not even layout=nodisplay.
Should I make it so that layout=nodisplay is required? It's a simple spec change.
Note that the example provided here ...
https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md
... does not have layout=nodisplay set, so it would become invalid.
Also happy to come by and we can talk through this to see what's the best choice, e.g., somehow making nodisplay the default or understanding it better in some other way. I do think that amp-font and amp-analytics ought to behave similar in that regard though, and amp-font does have layout=nodisplay required: look for `# <amp-font>` here https://github.com/ampproject/amphtml/blob/master/validator/validator.protoascii and witness that it defines one supported layout, the nodisplay layout.

**Comment by powdercloud** [comment]
Also /cc: @Gregable.

**Comment by avimehta** [comment]
One thing to note is that the tag does not work when layout is set to
nodisplay. I'll need to figure out why and fix that before you can make
that change...

**Comment by sriramkrish85** [comment]
do not override
`isLayoutSupported` in amp-analytics, i think that would fix it.

**Comment by avimehta** [comment]
@cramforce I think you fixed this. no?

**Comment by jridgewell** [comment]
> I think you fixed this. no?

I [don't think](https://github.com/ampproject/amphtml/blob/dee430c3d0e0a95a16192f70dfadecdd74e3809e/extensions/amp-analytics/0.1/amp-analytics.js#L42-L44) so.

**Comment by cramforce** [comment]
What I did is make sure that it would never actually be visible.

**Comment by rudygalfi** [comment]
@jridgewell @cramforce Can this be closed?

**Comment by avimehta** [comment]
Nope. This is not fixed yet. If someone can take it up, feel free to. I'll
get to it otherwise..

**Comment by rudygalfi** [comment]
Just combing through old issues and was wondering about addressing this?

It seems low priority but let me know if anyone disagrees.

**Comment by dvoytenko** [comment]
They've been in `nolayout` for some time. I'm afraid we can't change them back now.

**Comment by adelinamart** [comment]
Is there still any work required for this issue?
