### ISSUE TITLE
is amp-facebook post responsive?

### ISSUE THREAD

**Issue by muchukotavijay** [ampproject/amphtml#10846]
## What's the issue?

amp-facebook post is non-responsive and but, amp-facebook embed video is responsive. Is there any specific reason.

## How do we reproduce the issue?
navigate to the below web page and resize the window.
https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-facebook%2Fsource%2F

## What browsers are affected?

all browsers.

## Which AMP version is affected?

Always broken (Not sure)

**Comment by jridgewell** [comment]
This is because the embedded content is not resizable for posts. Video's, however, embed a resizable video element so we can support responsive.
