### ISSUE TITLE
<amp-analytics> Inline or remote config should not overwrite vendor transport settings​​​

### ISSUE THREAD

**Issue by mauricionr** [ampproject/amphtml#10842]
I've deployed my GTM solution following this example https://github.com/mauricionr/amp-config-example/blob/6d13ea5543e2b5fbd45e24eb7f5edbfa5e738241/index.js#L11

today I've noticed that i'm getting this error and never happen before

`Inline or remote config should not overwrite vendor transport settings​​​`

```HTML
    <amp-analytics 
      config="${data.uri}/amp.json?id=GTM-12345678&gtm.url=${config.webstore_url}/${data.product.slug}/p" 
      data-credentials="include" type="googleanalytics">
    </amp-analytics>
```

Thanks!

**Comment by jasti** [comment]
CC @avimehta

**Comment by zhouyx** [comment]
Yes we introduced this recently. The idea is that the analytics vendor has the best knowledge on what transport method is supported and should not be overwritten with inline or remote config. 
@mauricionr Is there a reason why you want to change the default `transport` config?

**Comment by avimehta** [comment]
This happens when GTM is used and `type="googleanalytics"` are specified at the same time. GTM needs to support multiple analytics vendors and hence needs to use a transport mechanism that is supported by a majority of vendors. 

Using GTM along with `type="googleanalytics"` is not wrong but is unneeded for most users. 

@mauricionr Does your setup work without using the `type` attribute?

**Comment by mauricionr** [comment]
@zhouyx @avimehta i will test and let you know!!

Thansk for the response!

**Comment by rudygalfi** [comment]
Blocking #7096 until we get more information on this issue

**Comment by kul3r4** [comment]
I have also seen this error with other analytics beyond Google Analytics and GTM.
For example:
[https://www.iene.mediaset.it/](https://www.iene.mediaset.it/)
gets the errors, and analytics looks like:

```
<amp-analytics type="webtrekk" class="i-amphtml-element i-amphtml-layout-fixed i-amphtml-layout-size-defined i-amphtml-layout" style="width: 1px; height: 1px; display: none;" aria-hidden="true"><script type="application/json">{
  "transport": { "beacon": false, "xhrpost": false, "image": true },
  "vars": { "trackDomain": "mediasetitalia01.wt-eu02.net", "trackId": "769396664005295", "contentId": "CANONICAL_URL", "pageCategory1": "mediaset", "pageCategory2": "mediaset-web", "pageCategory3": "mediaset-web-mediaset.it - programmi", "pageCategory4": "mediaset-web-mediaset.it - programmi-iene", "pageCategory5": "mediaset-web-mediaset.it - programmi-iene-homepage", "pageParameter1": "no-refresh", "pageParameter2": "TITLE" },
  "triggers": { "trackPageview": { "on": "visible", "request": "pageview", "vars": { "pageParameter3": "homepage-amp", "pageParameter4": "", "pageParameter5": "offline", "pageParameter6": "no-loggato" } } }
}</script></amp-analytics>
```

**Comment by lannka** [comment]
@mauricionr a kind ping, did you try removing `googleanalytics`. 

Meantime, we can rephrase this error message to clarify that it's not breaking anything. And suggest them to remove `type` attribute if they are using GTM.

**Comment by rudygalfi** [comment]
Sounds like we determined we can't move forward with this? @zhouyx please confirm.

**Comment by zhouyx** [comment]
Yes. Sounds like at the time it is really difficult for us to apply the restrictions. Decide not to move forward.
