### ISSUE TITLE
Ability to have lightbox open on load

### ISSUE THREAD

**Issue by devkr** [ampproject/amphtml#10848]
Having an open lightbox on load is useful for announcements or warnings when the page loads. Can we have a way of achieving this?

**Comment by bjalford** [comment]
The AMP user notification component (https://github.com/ampproject/amphtml/blob/master/extensions/amp-user-notification/amp-user-notification.md) can be used for your use cases and potentially more flexible - dismissable, trackable etc?

Auto opening lightboxes could lead to back UX - think of those add that cover content when loading a page.

**Comment by devkr** [comment]
After giving user notification a closer look, I have to agree. I can style it to make it look like a lightbox and set it to always show and get the same effect. Thank you very much.

**Comment by AashishAli** [comment]
how did you set it to always show ? can you please help me as well
