### ISSUE TITLE
Amphtml tag reference

### ISSUE THREAD

**Issue by elisei** [ampproject/amphtml#10856]
We are served content amp based on 2 processes:

- Visualization of the mobile template when user agent is a mobile.

- In the html, for desktop, version the "amphtml" is referenced with a paramame example site.com?amp=1

However in the console of the webmaster tools the references of consultation for the AMP consider only the absolute url, with this it does not reach the version AMP and of the error.

Complementing:

In addition to delivering the version of the amplifier when the user-agent is mobile, it is also accessible to the amplifier version in any user-agent, as long as it has the "? Amp=true" parameter in the url

**Comment by jridgewell** [comment]
So what is the issue here?

**Comment by elisei** [comment]
Validation via webmaster tools...

**Comment by jridgewell** [comment]
Without a url, there's nothing we can debug here. If it's a webmaster tools problem, this should be on the Google forums: goo.gl/utQ1KZ

**Comment by elisei** [comment]
No problem follow the url:
Pass https://www.cristaisaquarius.com.br/?amp=1
Faill https://www.cristaisaquarius.com.br/

**Comment by jridgewell** [comment]
You're not including a `<link rel="amphtml" href="cristaisaquarius.com.br/?amp=1">` in the desktop version, so the crawler has no idea the amp version is there. All it sees in the (inavlid) amp desktop site.

**Comment by elisei** [comment]
In fact it is yes:
https://drive.google.com/file/d/0B_ecWdHCBMticXpVNGxmWmVvZFk/view?usp=sharing
The problem is also include the https protocol?

**Comment by jridgewell** [comment]
Sorrry, I didn't explain clearly. When you visit https://www.cristaisaquarius.com.br/ with a mobile user agent, it doesn't include the `rel=amphtml` link and the page itself is a broken AMP page.

**Comment by elisei** [comment]
Now I understand, only the info of the "mobile page" is broken, I do not see this break.

Sorry for the many questions, but I'm really in the dark!
