### ISSUE TITLE
Consider Exposing Some video-related events with AMP's on-syntax

### ISSUE THREAD

**Issue by mr-sonj** [ampproject/amphtml#1085]
I've tried add attribute onended="run();" , but it not working?. 

Edited - @mkhatib:
This combined with other triggers could allow for example to close a dialog box when the video is done. 

``` html
<amp-lightbox id="vid1">
  <amp-video on="ended:vid1.close"></amp-video>
</amp-lightbox>
```

Or allow auto advancing to next slide in carousel if/when #5210 is supported:

``` html
<amp-carousel id="video-carousel">
  <amp-video on="ended:video-carousel.next"></amp-video>
  <amp-video on="ended:video-carousel.next"></amp-video>
  <amp-video on="ended:video-carousel.go(0)"></amp-video>
</amp-carousel>
```

**Comment by dvoytenko** [comment]
No "on*" attributes are allowed in AMP and no custom javascript. Could you please describe what you would like to do on video end in your use case?

**Comment by mr-sonj** [comment]
I want to count the number of iterations video, then add source video new

**Comment by dvoytenko** [comment]
Let me try to repeat it: you'd like to run a video for a few iterations and then set a new video source?

**Comment by mr-sonj** [comment]
yes

**Comment by adelinamart** [comment]
Is this still required?

**Comment by mkhatib** [comment]
Funny - I was just chatting with @aghassemi about this - my understanding he wanted to expose these events yes.

**Comment by aghassemi** [comment]
Closing as dup of https://github.com/ampproject/amphtml/issues/8971 which has more discussions around this topic
