### ISSUE TITLE
amp-visibility-spy

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#10861]
Supports interactions where the styling of one element is dependent on the visibility of another (e.g. menu items get an underline when their corresponding section is in view)

(breaking this issue out of https://github.com/ampproject/amphtml/issues/2911)

/cc @aghassemi  for any additional details

**Comment by aghassemi** [comment]
@ericlindley-g Similar to https://github.com/ampproject/amphtml/issues/10862  we have all the mechanism's to make this possible, only thing to worry about is preventing abuse.

I was thinking whether we can make `amp-selector.Select` action LowTrust and any arbitrary CSS change can be abused.

Maybe we can have a **_safe_**  `AMP.setStyle` action that is LowTrust and only allows limited set of CSS properties ( `color`, `background-color`, `opacity` ??? ). @choumx @dvoytenko  thoughts?

**Comment by dvoytenko** [comment]
Yes, the unlimited CSS option would definitely affect the performance very negatively. We can approach this in a very targeted way, e.g. an extension where `<nav>` items are highlighted by the currently visible section. Going through an open-ended bind protocol would be hard on performance. It'd also be hard to make it work correctly. E.g. a lot of times, it's not only one element updated, but several in concert. In case of nav, one link is highlighted and the previous one is unhighlighted.

**Comment by aghassemi** [comment]
`amp-position-observer` + `setLowTrustStyle()` deduping with #13973
