### ISSUE TITLE
trigger visibility of a fixed element based on scroll position (potentially scroll position of other elements)

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#10862]
Extracting https://github.com/ampproject/amphtml/issues/2911 into separate issues for tracking

Use cases include
- A footer bar that appear after you pass the end of the article text
- A footer with an ad unit that only appear once you scroll down the page. (yes I know this would be a fixed ad unit, a policy change).
- Other elements that appear in side margins to select next/prev article after the user has scrolled the initial article.

/cc @aghassemi , I think some of these would already be supported by scrollbound amp-animation, but are they all?

**Comment by aghassemi** [comment]
@ericlindley-g With the new redesign and thanks to @choumx's TrustLevel framework, pretty much anything we allow with LowTrust user actions can be tied to visibility.

Now, we probably don't want `show(), hide()` actions to be LowTrust in all cases but we can special case and allow it if target is `positioned fixed` (Runtime has mechanisms for detecting fixed elements).

From your perspective, is it okay to allow display of any `fixed` element to be LowTrust? It's true that it won't cause content shift but can still obstruct content. It is essentially same as opening a `amp-lightbox` or `sidebar`.

We can be smarted too, we can only allow it of the fixed element's size is < X (e.g. maybe only allow if area if fixed element is < 50% of viewport area.. or similar)
