### ISSUE TITLE
Support validation of amp-analytics

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#1087]
https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md

@avimehta to confirm `script` situation.

**Comment by rudygalfi** [comment]
@dvoytenko Can you clarify your ask of @avimehta re: the `script` situation?

**Comment by dvoytenko** [comment]
@rudygalfi see #1081

**Comment by avimehta** [comment]
We'll be shortly changing the amp-analytics tag to host all the config
inside a script tag. I think dima is talking about that.

Avi

**Comment by dmitrymotorin** [comment]
@dvoytenko Can we make a release with non-valid analytics at our articles? Or it will be better to wait for validator update? Thank you.

**Comment by avimehta** [comment]
waiting would be better imho. the tag itself is under experiments currently so shouldn't be used in production.

**Comment by Gregable** [comment]
How much do we want validated on this? Do we need anything except for a new allowed `<amp-analytics>` tag with an optional? child `<script type="application/json">` tag? Specifically, do we want to validate any of the json.

**Comment by cramforce** [comment]
@Gregable presence only. The actual format is still heavily evolving and will also always contain custom args that are not possible to validate.

**Comment by rudygalfi** [comment]
Fixed yesterday
