### ISSUE TITLE
Feature: amp-animation trigger "element-visible" 

### ISSUE THREAD

**Issue by p2er** [ampproject/amphtml#10880]
## What's the issue?

Often teaser grids or content sections use a simple animation to animate content as it becomes visible in the viewport, e.g. fade in with translation from bottom to final position. Other content, like graphs could profit from the same mechanic as they could animate their bar height/width as they become visible to draw the user attention to a specific topic in the viewport. 

## How do we reproduce the issue?

1. Create custom visibility animation
```
<amp-animation id="anim1" layout="nodisplay"
    trigger="visibility">
  ...
</amp-animation>
```
2. Trigger animation on element visible state change
2.1 Could either be a configured as on attribute on amp-element
```
<amp-img id="elem1" layout="responsive" with="100" height="100"
    on="visible:anim1.start>
  ...
</amp-img>
```

2.2 Or as trigger on amp-animation 
```
<amp-animation id="anim1" layout="nodisplay"
    trigger="elem1.visibility">
  ...
</amp-animation>
```

3. Happy designers

Adding this trigger should be fairly easy, since element visibility is calculated anyway to trigger loading. The same trigger on elements could also be used with amp-bind to set classes and start the animation with css. 

## What browsers are affected?

All browsers.

## Which AMP version is affected?

Upcoming.

**Comment by aghassemi** [comment]
@p2er timely! See PR in review: https://github.com/ampproject/amphtml/pull/10818 specifically take a look at the description of the PR and the documentation: https://github.com/aghassemi/amphtml/blob/c98203d6626308cc5200ddfe93bf5224a3b0e5fc/extensions/amp-position-observer/amp-position-observer.md
The API is low-level but is meant to handle this use-case in addition to similar cases (hence the low-level nature of it to allow)

**Comment by aghassemi** [comment]
Closed by https://github.com/ampproject/amphtml/pull/10818. It will be in Dev Channel tomorrow afternoon under an experimental flag. 

@p2er your feedback will be very appreciated. Couple of resources to get started:
https://github.com/ampproject/amphtml/blob/master/extensions/amp-position-observer/amp-position-observer.md

https://github.com/ampproject/amphtml/blob/master/examples/amp-position-observer.amp.html

**Comment by p2er** [comment]
@aghassemi would you like feedback as tickets here, like: https://github.com/ampproject/amphtml/issues/11350

Or would you like general feedback to be posted in a specific slack channel? I've created a amp-position-observer channel for now: https://amphtml.slack.com/messages/C763Y9MMK
