### ISSUE TITLE
Shadow AMP: different behaviour in Chrome & Firefox when manipulating elements under shadow root

### ISSUE THREAD

**Issue by ruborg** [ampproject/amphtml#10881]
## What's the issue?
I'm trying to implement the AMP in PWA pattern described in the AMP docs here:
https://www.ampproject.org/docs/guides/pwa-amp/amp-in-pwa

I am able to embed an AMP document within a non-AMP document with Shadow AMP library.

However, I'd like to add a click handler to anchor links in the AMP doc, so that I can catch the click, and load the next document into the PWA shell, just like the first AMP document.

So I attach a click handler, and it works in FF, but Chrome does not allow me to manipulate any of the elements in the shadow tree that was created by AMP Shadow library.

Here's a jsbin:

https://jsbin.com/nuduwit/edit?html

## How do we reproduce the issue?

In FF desktop: load the jsbin here: https://output.jsbin.com/nuduwit

You should see something like this:

```
 This is the shell!
## Page 1 ##
(link to) page 2
```
If you click the page 2 link, you will see

```
 This is the shell!
## Page 2 ##
(link to) page 1
```

Note that `This is the shell!` is output, whenever you follow the link on either page. This represents the PWA app shell or chrome. It's rendered in the parent, non-AMP page.

Now, load same page in Chrome: https://output.jsbin.com/nuduwit

it should look the same as above:
```
 This is the shell!
## Page 1 ##
(link to) page 2
```
Now click the link to page 2. This time you will only get:
```
## Page 2 ##
(link to) page 1
```
The browser loads page 2 directly, instead of Shadow AMP loading it within PWA app shell because the click handler was not attached because Chrome doesn't seem to see the elements in the Shadow DOM attached by Shadow AMP

## Expected behaviour ##
Chrome & FF behave the same
Chrome can access shadow elements & attach event handler

## What browsers are affected?
Chrome Desktop (Mac OS)  60.0.3112.90 (Official Build) (64-bit)
Chrome for Android (58.0.3029.83) (Android 6.0.1)

## Which AMP version is affected?
Powered by AMP ⚡ HTML shadows – Version 1502408222412

**Comment by ruborg** [comment]
Update:

After playing around with the issues a bit more, it looks like you can get at elements in the shadow doc like this in FF

    var el = document.getElementById("navLink");

Whereas in Chrome you need to be more specific:

    var el = docContainer.shadowRoot.getElementById("navLink");

So, it doesn't  really look like an AMP issue after all. Apologies!

**Comment by cvializ** [comment]
Cool, TIL! Thanks for opening an issue and sharing what you learned : )
