### ISSUE TITLE
Migrate the use of user().error() to this.user().error()

### ISSUE THREAD

**Issue by tiendt** [ampproject/amphtml#10897]
## **What's the issue**
The plan is to eliminate user().error() call, and instead using:
`this.user().error(),` or:
`this.ampdoc().user().error()`

## **Initial problem**

- I'm working on the [user-error-reporting project](https://docs.google.com/document/d/1V3YCd8s8QhrZPaQwjN1vkmQtL2wZhz14N3ZB3NzGzfE/edit#heading=h.xg3w3mqw13t3), which reports user errors to publishers so that they can act upon. 
- In order to exclude errors generated from iframe embed, we agreed to pass in a base-element whenever calling user() (see A4A errors in the doc): 
                          `user(this).error()`. 
- Currently, I'm having an {Element} passed in (see [isFromEmbed](https://github.com/ampproject/amphtml/blob/master/src/log.js)). The element is now optional.
- In the end, we'd want to use {BaseElement} instead of {Element}, and make it a required param when using user(). 
- However, base-element.js and log.js will have circular dependency if I introduce base-element in my code in log.js: `element.ownerDocument.defaultView != ampdoc.win`. In addition, not every class/file has a base element to pass around.

## **Possible approach**

- In base-element.js, introduce another user() field:
`user() {
       return user(this.element);
}`
This would eliminate the circular dependency.
- Also introduce similar user() field in amp-doc, so that whenever base-element is not available, we can use amp-doc to check:
`this.ampdoc().user().error()`

## **Discuss**

- This will change everyone's use of user() and possibly coding style (passing by ampdoc, etc.). Therefore we're looking for everyone's opinion on this design.

**Comment by tiendt** [comment]
@lannka @jridgewell @aghassemi @dvoytenko 
I'd like to hear your opinions about this!

**Comment by erwinmombay** [comment]
ill have to check if this affects DCE

**Comment by cramforce** [comment]
Is this only about `error()` as opposed to other logging levels? In that case DCE might be irrelevant.

**Comment by lannka** [comment]
To summarize the problem: we want to be able to tell which `ampdoc` the error message is from, so that we can exclude A4A errors from reporting (they will be noise to developers).

To do that, we need all the usages of `user().error()` to get a hold of a `BaseElement` or `AmpDoc`, which sometimes can be a bit annoying. It means even in a util class, if we want to print user error or do user assert, we have to pass in `BaseElement` or `AmpDoc` in.

Let us know if you guys have better idea, or you have a big concern about this. This is currently blocking @tiendt's work.

**Comment by cramforce** [comment]
![LGTM](https://camo.githubusercontent.com/c13eeb81b1485ccc0d2b248f19360c7ba2419167/687474703a2f2f6a756e6b796172642e64616d6f776d6f772e636f6d2f353633)

**Comment by tiendt** [comment]
Does anyone else have objections about this? Thank you.

**Comment by jridgewell** [comment]
I'd strongly favor using the `ampDoc` instead of elements, since most services will already have access to an `ampDoc`. IE, `CustomElement` has a `#ampDoc` property already (and before it's set, you can't get it any other way).

But, overall looks fine.

**Comment by dvoytenko** [comment]
`ampdoc.user()` is definitely fine. `element.user()` is mostly a shortcut, but we need to see if we ever have user errors before element is attached to DOM, where ampdoc is not available. I don't know if any global services send user errors. Hopefully not.

**Comment by jridgewell** [comment]
Sorry, what I meant was passing in `ampDoc` and not some `BaseElement` instance.

```js
// Good
user(this.ampdoc).error(...)

// Probably bad, I don't want to pass around an element through deep call chains
user(element).error(...)

**Comment by aghassemi** [comment]
LGTM. I also prefer having it at ampdoc level.

**Comment by dvoytenko** [comment]
I'm ok with just `ampdoc`. Though it'd look very much like our current service lookups where we allow both. So not sure if it'd really make much difference. But otherwise - sure, let's run with `ampdoc` at this time.

**Comment by lannka** [comment]
sorry for joining late. @jridgewell we can't pass any Class we define to log.js, if at meantime we also want to do logging in the impl of that Class. That's a circular dependency.

That's to say, we can't pass neither `AmpDoc` nor `BaseElement` to `user(..)` function. So that leaves us `baseElement.user().error()` or `ampdoc.user().error()` the best options. As @dvoytenko pointed out, they're just convenient helper methods.

**Comment by dvoytenko** [comment]
@tiendt correctly pointed out that we cannot yet switch fully to ampdoc until migration of FIE to ampdoc is complete. So, for now we need to keep API of `user(element)` and have a custom service lookup, based on frameElement there.

**Comment by lannka** [comment]
@dvoytenko the `this.user()` helper method can hide the detail (whether passing in element or ampdoc)  away from the caller code, which will ease the later migration once the ampdoc change is done.

**Comment by dvoytenko** [comment]
It can be built as `this.user()`, but not as `this.ampdoc.user()` since `ampdoc` is not fine-grained enough at this point. My point is simply that we cannot currently use `ampdoc` as a key.

**Comment by lannka** [comment]
@dvoytenko yep, we're on the same page. the work is partially blocked.

**Comment by dvoytenko** [comment]
@lannka That's the way to unblock it is to provide a special service lookup via embed window. This would be similar to `getExistingServiceInEmbedScope`.
