### ISSUE TITLE
Collapse empty ads in situation where iframe resizing is allowed

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1089]
If we are allowed to resize the iframe of the ad and there is no ad to serve, remove the ad from the page.

CC @kashyapnitin

**Comment by ds0001** [comment]
:+1:

**Comment by sriramkrish85** [comment]
Does this need animation?

**Comment by cramforce** [comment]
No.

**Comment by sriramkrish85** [comment]
We only collapse if there is no placeholder right?

**Comment by cramforce** [comment]
Right

**Comment by sriramkrish85** [comment]
@cramforce we dont support resizing on amp-ad iframes yet, should I implement resizing support as well?

**Comment by cramforce** [comment]
Yes, but sync with Dima. He might have a pending CL. Doing this special
case is a good first step, though.

**Comment by sriramkrish85** [comment]
adding @dvoytenko to the conversation

**Comment by dvoytenko** [comment]
Yeah, let's roll it in this PR. Most of the implementation is already done in the `custom-element.js` - which just need to trigger it.
