### ISSUE TITLE
Allow password (and other) input type in amp-form

### ISSUE THREAD

**Issue by JoeNimble** [ampproject/amphtml#10902]
## What's the issue?

amp-form does not currently allow type="password" for input fields. Preventing any sort of secure text field entry for forms.  

This is a fairly common feature of forms and shouldn't effect performance at all. There has never been an official response as to why it was disallowed in the first place as seen in https://github.com/ampproject/amphtml/issues/3348

It would be good to see an open discussion on revising the validation rules.

**Comment by techhtml** [comment]
I think `type=button` also allow in input elements.

**Comment by cvializ** [comment]
Login flows were a non-goal of the original `amp-form` implementation. Theoretically there is no reason why we cannot allow password fields in an amp form, but it will take careful security review and possibly some restrictions around which kinds of action URLs are allowed to receive password data.

**Comment by joshcp** [comment]
Other input types that would be valuable include `type="tel"`, `type="number"`, `type="email"`, etc. These activate different (more appropriate) keyboards on mobile phones, which is often a better user experience. (see [Mobile Input Types](http://mobileinputtypes.com/) for ref.)

**Comment by cramforce** [comment]
@joshcp Those should be whitelisted already. If they aren't that should be changed.

Password is a different deal. It won't generally work well in AMP (because of autofill being an origin property) and we need to at least consider phishing risk.

**Comment by cramforce** [comment]
Clarifying: This is implemented as a blacklist
https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii#L2886

@joshcp So all those are allowed.

**Comment by mario-lorenzen** [comment]
@cramforce Will the password input be implemented in the future? We are currently (mis)using the input type text for password for our freemium model, e.g. https://www.shz.de/sport/fussball/kopf-hoch-dino-so-wurschtelt-sich-der-hsv-in-die-relegation-id19250156-amp.html

**Comment by cramforce** [comment]
@mario-lorenzen I'd say: Yes, it will be. Just subject to prioritization of the work.
