### ISSUE TITLE
Add meta-data example for OpenGraph (i.e. Facebook) syndication

### ISSUE THREAD

**Issue by pbakaus** [ampproject/amphtml#1092]
The folder at https://github.com/ampproject/amphtml/tree/master/examples/metadata-examples does not have any examples of OpenGraph meta-data. OpenGraph is required to properly share things on platforms such as Facebook.

**Comment by Francis47** [comment]
OpenGraph meta-data seems to validate fine

**Comment by bpaduch** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
