### ISSUE TITLE
Add meta-data example for Twitter (Twitter card)

### ISSUE THREAD

**Issue by pbakaus** [ampproject/amphtml#1093]
The folder at https://github.com/ampproject/amphtml/tree/master/examples/metadata-examples does not have any examples of Twitter card meta-data. Twitter cards are required to properly share things on Twitter.

**Comment by niallkennedy** [comment]
Google has mentioned Schema.org markup is required for inclusion in its AMP-specific search carousel.

What would you like to specify for content summary markup indexed by other social networks? Other than just webmaster best practices, how should this information fit within the AMP project?

**Comment by nahuelange** [comment]
Sharing an amphtml link is not supported by twiter atm ? It seems that twitter doesn't take care about ld+json metadatas for twitter cads.
Should we add twitter cards metadatas? What's the best practice ?
What about other social networks like facebook?

**Comment by cramforce** [comment]
Please add Twitter cards. I believe Facebook follow the canonical URL and
uses metadata from there, but best to test yourself!

**Comment by jridgewell** [comment]
Closed by #4411.
