### ISSUE TITLE
amp-facebook does not resize and ignores width and height 

### ISSUE THREAD

**Issue by p2er** [ampproject/amphtml#10939]
## What's the issue?

amp-facebook does not apply the actual dimensions set with width and height. When scaled down the post is simply cut off and does not support responsive behaviour.
   
## How do we reproduce the issue?

1. Open: https://ampbyexample.com/components/amp-facebook/#basic-usage
2. Reduce window width
3. Post content and text is cut off

## What browsers are affected?

All browsers.

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1502819823157

**Comment by ericlindley-g** [comment]
Thanks for the heads up — I'm guessing the component was originally committed by a non-FB-affiliated contributor?

**Comment by aghassemi** [comment]
yes, but rendering is mostly handled by FB SDK. We just need to find the right parameter to pass to their SDK (if they support responsive width, which I suspect they do).

/cc @levidurfee @techhtml in case either of you are interested in this.

**Comment by techhtml** [comment]
It seems problem with Facebook resizing.
I tried to fix it.

**Comment by aghassemi** [comment]
@techhtml Thanks! They have this `data-width` parameter which may help. I wonder if we need to set that to something (`100%`? `adaptive`?) to tell them not to fix the width.

**Comment by p2er** [comment]
@aghassemi @techhtml Any indication on when the issue might get resolved?

**Comment by aghassemi** [comment]
@p2er We are doing a FixIt week next week, I will add it to the list, if @techhtml doesn't get to it by then.

**Comment by aghassemi** [comment]
Unfortunately FB SDK does not support this for posts (they do for comments). Bug here: https://developers.facebook.com/bugs/883532718489752/ 

I asked them if they plan to fix this.

Root-cause of problem is FB "fixes" the width at "load time" and never updates it on resize. They also don't have a way of setting with to 100% so it takes containers width.

**Comment by aghassemi** [comment]
Doesn't look like FB is planning to fix this (https://developers.facebook.com/support/bugs/883532718489752/?disable_redirect=0). Closing on our end as well.
