### ISSUE TITLE
CORS errors on Google Analytics redirect to Doubleclick

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#10952]
We're seeing CORS errors when the GA ping redirects to doublclick - 

![image](https://user-images.githubusercontent.com/524856/29387484-0fb8170c-8295-11e7-997c-9f3a78c283ef.png)

![image](https://user-images.githubusercontent.com/524856/29387529-3da08bae-8295-11e7-827f-8af7b63ba334.png)

This is happening on multiple publisher sites.

Example urls:
http://amp.wesh.com/article/alleged-patrol-car-beating-leads-to-arrest/10018778
http://grubstreet.relaymedia.com/amp/2017/08/long-island-restaurant-named-after-billy-joels-venice.html
https://www.vice.com/amp/en_us/article/59zmyk/someone-blew-up-a-7-eleven-microwave-trying-to-warm-urine-vgtrn

**Comment by jasti** [comment]
@avimehta @keithwrightbos could you please take a look?

**Comment by avimehta** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=746687#c1. Chrome has fixed this in dev build but not in Beta yet.

**Comment by jasti** [comment]
Closing since it's a Chrome bug.
