### ISSUE TITLE
Amp-font: Unhandled Promise Rejection

### ISSUE THREAD

**Issue by NataliaLKB** [ampproject/amphtml#1095]
When trying out amp-font, I receive an error:

![image](https://cloud.githubusercontent.com/assets/8774970/11654983/d733af2e-9da1-11e5-85b7-0321e7306b68.png)

The font works fine when used regularly (just using` font-face`).

Is this an error you could help me with? The test page is [here](http://www.thegulocal.com/australia-news/postcolonial-blog/2015/jul/21/enduring-controversy-bp-sponsorship-ignites-new-row-over-british-museums-indigenous-exhibition/amp#development=1)

**Comment by cramforce** [comment]
Thanks for the report! Assigning to @sriramkrish85

**Comment by sriramkrish85** [comment]
@NataliaLKB , You are seeing this error because the font takes too long to download (default is 3s), if you want you can set a timeout attribute > 3000 and see if it loads. 

I will send a PR soon that will have an warning (rather than an error) that is easy to read.

**Comment by cramforce** [comment]
Yes, making this a warning sounds good. And lets spell out exactly what
happened.

**Comment by sriramkrish85** [comment]
@NataliaLKB - Made a console.warn - to give some useful message. Let me know if you are able to get the font to load after increasing your timeout. Closing this issue for now. Feel free to re-open if required.

**Comment by NataliaLKB** [comment]
@sriramkrish85 thanks so much for taking a look. 

The first thing I tried is increasing the timeout to 10s (10000). Loading the font through `font-face` seems to be instantaneous, certainly not 10s. Unfortunately it still doesn't work. For good measure I also tried it with 100s and no joy.

Can you think of anything else to try, or that I may have done wrong?

**Comment by sriramkrish85** [comment]
@NataliaLKB , you will have to use the 

    on-error-remove-class
    on-error-add-class
    on-load-remove-class
    on-load-add-class
to be able to use amp-font efficiently 

You can take a look at examples/font.amp.html for usage and give it another shot, or ping me a gist of what you are trying and i would be happy to take a look.

**Comment by NataliaLKB** [comment]
@sriramkrish85 currently on the page referenced above I have:

```
<amp-font layout="nodisplay"
    font-family="Guardian Egyptian Web"
    timeout="100000"
    on-load-add-class="guardian-egyptian-loaded"
    on-load-remove-class="guardian-egyptian-loading"
    on-error-remove-class="guardian-egyptian-loading"
    on-error-add-class="guardian-egyptian-missing">
 </amp-font>
```

**Comment by NataliaLKB** [comment]
Here is the test page: http://www.theguardian.com/australia-news/postcolonial-blog/2015/jul/21/enduring-controversy-bp-sponsorship-ignites-new-row-over-british-museums-indigenous-exhibition/amp

**Comment by sriramkrish85** [comment]
@NataliaLKB , thanks for the link to help debug the issue. I have pushed a fix. You should be good now (I also saw that this was already working on mobile safari without my fixes. My fixes would make this more stable.)

**Comment by erwinmombay** [comment]
we need to do a release btw if we want them to receive the fix.

**Comment by erwinmombay** [comment]
@NataliaLKB latest release should be out within the hour https://github.com/ampproject/amphtml/releases

**Comment by NataliaLKB** [comment]
That is great! Thank you so much!

**Comment by NataliaLKB** [comment]
Just tested it out, and it works great now.

Thank you :smile:
