### ISSUE TITLE
amp-sticky-ad goes on top of image lightbox on iOS

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#10964]
Visit www.washingtonpost.com/amphtml/politics/trumps-lack-of-discipline-leaves-new-chief-of-staff-frustrated-and-dismayed/2017/08/16/9aec8e16-82b8-11e7-82a4-920da1aeb507_story.html on Safari/iOS

Find the image carousel and click on an image, notice sticky ad is on top of the lightbox.

It's fine in non-iOS cases.

**Comment by zhouyx** [comment]
I can't reproduce with an iOS simulator. More context here?

**Comment by aghassemi** [comment]
Repros on iOS 10.3.3, iPhone 6s I have

**Comment by lannka** [comment]
Can you give a screenshot? Could it be related to #12306 ?

**Comment by aghassemi** [comment]
@lannka Can't repro anymore on phone (10.2) or simulator (10.0)

Closing.
