### ISSUE TITLE
amp-brightcove and ads served via DFP

### ISSUE THREAD

**Issue by dcilibiu** [ampproject/amphtml#1097]
Hello.
I have an issue with some ads. On the main article the ads are displaying on videos but on amp version the ads are not visible.
I've followed the way BC is added to the page but pre-roll ads served via DFP are not showing.
Are they supported? I should be doing something special to activate this feature?
Thank you.

**Comment by mister-ben** [comment]
It should "just work", as it does [here](http://solutions.brightcove.com/bclifford/demo/player/amp.html) with a DFP sample ad. Make sure that the player configuration contains all the all settings. If you rely on modifying the ad settings in an in-page script on regular HTML pages, that wouldn't work here. Do you have an example page?

**Comment by cramforce** [comment]
One frequent problem is with non-HTTPS creatives.

**Comment by cramforce** [comment]
@dcilibiu Did you check whether HTTP creatives might have been the issue?
