### ISSUE TITLE
Feature: AMP URL decoration for outgoing clicks

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#10997]
It's common for certain query params to be "passed on" to subsequent URLs when a user clicks on any link in the AMP page. AMP allows page authors to do this using URL variable substitutions but that's often cumbersome. Also, in some cases like the 'gclid' param, it makes sense to automatically pass on the url param & value to the subsequent page so Google Analytics conversion tracking works as expected. 

It makes sense to allow such a feature to pass along any URL param that the page author wishes, but it might make sense for an analytics vendor to opt in doing the same. (e.g. the GA amp-analytics could opt-in to decorate all outgoing URLs with GCLID) - pending privacy concerns.

CC @rudygalfi @avimehta @lannka @michaelkleber

**Comment by jasti** [comment]
Implemented for GA in last sprint.

**Comment by sk1llfull** [comment]
@jasti Is there any documentation/example how to decorate outgoing links with GCLID, etc?

**Comment by dougscher** [comment]
I would also like to find some documentation on this added feature
