### ISSUE TITLE
Use Google CID API with custom API key

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#10998]
This is to allow any developer to register and use Google CID API in AMP for better user tracking.

**Comment by lannka** [comment]
@Gregable @cramforce what string format should I use for a sanity check of the api key?

**Comment by cramforce** [comment]
I don't think anything can be done really. It is just an opaque string.

**Comment by rudygalfi** [comment]
@lannka Is this closed by #11046? Seems like it, so I'll do that.
