### ISSUE TITLE
amp form not support bootstrap frameword

### ISSUE THREAD

**Issue by phuduc88** [ampproject/amphtml#11005]
I have a issue when convert current website mvc to amp app google
Current website using bootstrap framework but when convert amp google not include bootstrap framework in the  project
Please help me

**Comment by phuduc88** [comment]
Current  website 
http://bacthoitrang.vn

**Comment by aghassemi** [comment]
@phuduc88 All CSS in AMP must be inlined within a `<style amp-custom>` tag and AMP enforces a 50k limit plus a few other restrictions. Please see https://www.ampproject.org/docs/guides/responsive/style_pages for details
