### ISSUE TITLE
AMP adsense in the middle of blogger post

### ISSUE THREAD

**Issue by TamerMobarak** [ampproject/amphtml#11014]
We need an AMP code or that shows adsense units in the middle of Blogger posts with the ability to determine after how many paragraphs the Ad appears.
I searched for it but I couldn't get any help.
Here is ascript that needs to be modified for AMP 
` <div id='adsense-mohamed'><data:post.body/></div>
<div id='adsense-algandy'>
AD CODE HERE
</div>
<script type='text/javascript'>
function insertAfter(addition,target) {
var parent = target.parentNode;
if (parent.lastChild == target) {
parent.appendChild(addition);
} else {
parent.insertBefore(addition,target.nextSibling);
}
}
var adscont = document.getElementById(&quot;adsense-algandy&quot;);
var target = document.getElementById(&quot;adsense-mohamed&quot;);
var linebreak = target.getElementsByTagName(&quot;br&quot;);
if (linebreak.length &gt; 0){
insertAfter(adscont,linebreak[1]);
}
</script>`

**Comment by jridgewell** [comment]
See [`<amp-auto-ads>`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-auto-ads/amp-auto-ads.md).
