### ISSUE TITLE
Refused to execute inline script

### ISSUE THREAD

**Issue by bluesuiter** [ampproject/amphtml#11020]
I am facing this issue on my website. Issues appear in the console exactly after the page loaded. Can you please explain why it is appeared.

Refused to execute inline script because it violates the following Content Security Policy directive: `"script-src blob: https://cdn.ampproject.org/rtv/ https://cdn.ampproject.org/v0.js https://cdn.ampproject.org/v0/ https://cdn.ampproject.org/viewer/"`. Either the 'unsafe-inline' keyword, a hash ('sha256-nNAB7wzHoZ2H2aPXc92gTFy5PUJbI0DgcTKKke1IAME='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by jridgewell** [comment]
AMP forbids using non-AMP javascript on the page.
