### ISSUE TITLE
Track click events on amp-facebook-like

### ISSUE THREAD

**Issue by chris-hinds** [ampproject/amphtml#11023]
### Feature Request

I have implemented the amp-facebook-like plugin and wish to track user clicks on the facebook like button.

The amp-analytics plugin has the ability to listen for click events, but does not work with the facebook like button. My guess is because this button is buried deep within an iframe.

## How do we reproduce the issue?

NA

## What browsers are affected?

All browsers

**Comment by jridgewell** [comment]
> My guess is because this button is buried deep within an iframe.

Exactly. We'll have to see if the facebook SDK will send some sort of postMessage after liking.

**Comment by hindsc52** [comment]
yeah, that sounds like the only way. Any sort of timeframe on when these feature requests get looked into?

**Comment by aghassemi** [comment]
Looks simple enough to be a Great First Issue for community contribution.

@hindsc52 If you are interested in contributing this feature, getting started with AMP is well-documented and straightforward: See https://bit.ly/helpamp

/cc @levidurfee @techhtml if case you are interested in this.

**Comment by hindsc52** [comment]
@aghassemi going to try and allocate some time on this in the coming weeks.

**Comment by rudygalfi** [comment]
Did we figure out if the SDK gives a postMessage confirmation of the like event?

**Comment by hindsc52** [comment]
@rudygalfi I've not had a chance to look into this yet.
