### ISSUE TITLE
Session breaks in Google Analytics when user navigates from CDN proxy to pub origin

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#11028]
If user visit from `example-com.cdn.ampproject.org` to `example.com`, the referrer on the 2nd page has domain of `example-com.cdn.ampproject.org`. Google Analytics will reset session because it's considered as a different domain.

Setting the referrer to null in this case will fix the issue because it forces Google Analytics to take it as same domain referrer.

/cc @avimehta @cramforce

**Comment by jridgewell** [comment]
Does this supersede https://github.com/ampproject/amphtml/issues/7184?

**Comment by avimehta** [comment]
Yes, It's the same core issue. Op top of #7184, this change also excludes referrers from cache domains to their origin domains.
