### ISSUE TITLE
Nominating wassgha to be a core committers in AMP

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#11037]
@cramforce, @dvoytenko, @jridgewell: I like to nominate @wassgha to be a core committer in AMP. 

@wassgha has contributed many well-written PRs to AMP (https://github.com/ampproject/amphtml/pulls/wassgha) and continues to do so as a community contributor now. He is also the owner to several important Media-related features in AMP.

@wassgha has shown his dedication and interest in making AMP better for everyone, and I believe promoting him to a core committer would be to the benefit of AMP open-source project and the community.

**Comment by jridgewell** [comment]
👍

**Comment by dvoytenko** [comment]
👍

**Comment by cramforce** [comment]
![LGTM](https://camo.githubusercontent.com/c13eeb81b1485ccc0d2b248f19360c7ba2419167/687474703a2f2f6a756e6b796172642e64616d6f776d6f772e636f6d2f353633)

**Comment by cramforce** [comment]
Write access granted.

**Comment by cramforce** [comment]
Added to Master mergers group.

@wassgha please don't break anything :)

**Comment by wassgha** [comment]
Thank you!! :))

**Comment by cramforce** [comment]
@wassgha Please add yourself here https://github.com/ampproject/amphtml/blob/master/GOVERNANCE.md#list-of-core-committers
