### ISSUE TITLE
Byte order marks in AMP docs.

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#11031]
Just wanted to confirm whether it is expected that the AMP cache rejects byte order marks.

It currently leads to the whole document being mis-parsed (So a bunch of errors, instead of pointing at the culprit). Meanwhile the JS validator does not catch the issues.

**Comment by pietergreyling** [comment]
Planned [AMPBench](https://github.com/ampproject/ampbench) feature: [Add detection for byte order marks (BOM) in AMP docs #27](https://github.com/ampproject/ampbench/issues/27)

**Comment by cramforce** [comment]
@pietergreyling Awesome!

Meanwhile this issue should be closed. Byte order marks are now accepted, but definitely still discouraged.
