### ISSUE TITLE
3q player endpoints are down

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#11032]
`<amp-3q-player>` uses `https://playout.3qsdn.com/c8dbe7f4-7f7f-11e6-a407-0cc47a188158?autoplay=false&amp=true ` as endpoint, however the URL seems to be down which means the component is completely broken.

Test were skipped in https://github.com/ampproject/amphtml/pull/11034, they needed to be unskipped after this is fixed.

see https://codepen.io/aghassemi/pen/eErqBL for repro

**Comment by aghassemi** [comment]
@JuliusThms did anything change with 3Q endpoints or are you experiencing temporary issues?

**Comment by JuliusThms** [comment]
@aghassemi Temporary issue with dns in the us. should be fixed.

**Comment by aghassemi** [comment]
Thanks @JuliusThms , working now.
