### ISSUE TITLE
Add hidden attribute for all form elements

### ISSUE THREAD

**Issue by waynepurtonsmith** [ampproject/amphtml#11048]
## What's the issue?
It seems that AMP still ~blacklists~ does not allow the `hidden` attribute for all form elements (`<input />`, `<select>`, `<option>` and `<textarea>`)

Form elements can be disabled using the `disabled` attribute, but in certain cases, I'd like to hide form elements with the `hidden` attribute when it's not needed. I use amp-bind for disabling elements based on expressions.

The `hidden` attribute is [widely supported](http://caniuse.com/#feat=hidden) by mobile devices

Example snippet:

    <label>Employment status</label>
    <select on="change:AMP.setState({ employment: { status: this.value } })">
      <option value="ue">Unemployed</option>
      <option value="pt">Part-time</option>
      <option value="ft">Full-time</option>
    </select>

    <input type="text" [hidden]="employment.status != 'ue'" placeholder="What is your job title?" />

## Which AMP version is affected?
Version 1503095301111

**Comment by aghassemi** [comment]
/to @cvializ 
I don't see any issue with updating validator rules to support `hidden` on `input` (it is supported on other elements), @Gregable, WDYT?

We should also make sure `amp-bind` supports binding to `hidden` attribute everywhere, @choumx

**Comment by aghassemi** [comment]
@waynepurtonsmith, thanks for filing. As a workaround, you should be able to bind to `class` to handle your use-case until this feature is supported.

**Comment by cvializ** [comment]
I agree this should be allowed. @waynepurtonsmith Where do you see the hidden attribute blacklisted? I am not seeing any validator code or configuration forbidding it in the open source validator.

**Comment by honeybadgerdontcare** [comment]
@cvializ It's [here](https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii#L3432): hidden is allowed as a global attribute on any element, but must not have a value set.

**Comment by cvializ** [comment]
Thanks! I saw that, but that does not blacklist `hidden`. It looks like the `[hidden]` attribute for bind causes a validation error and not `hidden` itself, so this request seems to actually be to add support for `hidden` to bind.

**Comment by waynepurtonsmith** [comment]
@cvializ I think I used the word 'blacklisted' too strongly here, I should have said 'not supported' 😅
