### ISSUE TITLE
XHR: attempted to fetch %s before viewer was visible //pagead2.googlesyndication.com/getconfig/ama?client=ca-pub-

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#11044]
> XHR: attempted to fetch %s before viewer was visible //pagead2.googlesyndication.com/getconfig/ama?client=ca-pub-

We started to see errors on production, which might be from this [line of code](https://github.com/ampproject/amphtml/blob/master/extensions/amp-auto-ads/0.1/amp-auto-ads.js#L90).

@tlong2 @wjfang

**Comment by jridgewell** [comment]
Taking this.

**Comment by zhouyx** [comment]
@jridgewell I saw a error logs "Error: preconnect without defaultView". Is the issue related? 
go/amp-error/CJHdjOfT26mDsQE

**Comment by jridgewell** [comment]
No, that's related to https://github.com/ampproject/amphtml/issues/16105
