### ISSUE TITLE
documentHeight events not fired for viewer integration on iframe resize

### ISSUE THREAD

**Issue by peterjosling** [ampproject/amphtml#11051]
## What's the issue?
documentHeight events aren't emitted from the viewer integration script on iframe resize (e.g. from device rotation)

## How do we reproduce the issue?
1. Set up a frame channel on an AMP document using the latest open source viewer integration script
2. Listen for documentHeight events
3. Load a document. Events will be received as the document loads (at least two)
4. Rotate the phone. The iframe will resize and the height of the document will change. No event will be received.

## What browsers are affected?
Tested on Safari on iOS 10 and Chrome Beta 61

## Which AMP version is affected?
1503095301111

**Comment by muxin** [comment]
@chenshay Could you take a look?

**Comment by peterjosling** [comment]
I've worked out this isn't a problem with the viewer integration - it does handle resize events correctly and send messages with the updated height.

However we aren't getting messages when rotating a device from portrait to landscape because when we rotate the content becomes smaller than the iframe height (viewport), and documentHeight is calculated from scrollHeight which doesn't change.

I can see that documentHeight was initially calculated from contentHeight to handle this exact case, but it was reverted before it was merged (https://github.com/ampproject/amphtml/pull/7327/commits/ac741f6d448305570659d0eae3c11c9049ae0fef) - what was the reason for this?

**Comment by jridgewell** [comment]
Thanks for doing the research. Are you looking for resize events on the size of the iframe alone? I don't believe that's the intended usecase for `documentHeight`.

**Comment by peterjosling** [comment]
No, we're just looking at when the phone is rotated, resizing the iframe because the viewport has rotated.

**Comment by jridgewell** [comment]
Can't you listen for that on your end? `documentHeight` is specifically for the scroll height of the content, not for the display area the content has.

**Comment by peterjosling** [comment]
So I think I was wrong about `documentHeight` events being sent correctly. If you load up `examples/viewer.html` and start resizing the browser width the scroll width of the document will change, but `documentHeight` events aren't sent consistently with each resize event.

**Comment by peterjosling** [comment]
Thanks! 😄 What's the release process like for AMP? When will the change make it into docs served from the cache?

**Comment by jridgewell** [comment]
Things go live to production the second Tuesday from the merge date (we have a rolling 1 week canary process, deploys on Tuesdays).
