### ISSUE TITLE
AMP in React Js

### ISSUE THREAD

**Issue by jeenamanuel** [ampproject/amphtml#11050]
How can  i implement AMP in my  react application.. Is it possible?
when am trying a bundle.js file is creating and it shows an error that script tag is not allowed. So  am not able to create a valid amp page

**Comment by choumx** [comment]
You can embed AMP pages into your React app via AMP's special "shadow" runtime, `shadow-v0.js`. See a [sample React component](https://github.com/ampproject/amp-publisher-sample/tree/master/amp-pwa/src/components/amp-document).

Also check out the [entire sample React app](https://github.com/ampproject/amp-publisher-sample/tree/master/amp-pwa) and a [live demo](https://choumx.github.io/amp-pwa/).

**Comment by jeenamanuel** [comment]
is it possible from client side? without using server side rendering

**Comment by cramforce** [comment]
Here is an article from Reddit how they implemented AMP with React https://redditblog.com/2016/09/20/amp-and-reactredux/

This will require server side rendering.
