### ISSUE TITLE
Google AMP Search Showing "Sorry this page is Not valid AMP HTML" Error

### ISSUE THREAD

**Issue by nishukadian** [ampproject/amphtml#11053]
Hello,

We are Facing an AMP Issue on www.Jansatta.com and Need your Help. Google AMP SERP Shows "Sorry, this is not a Valid AMP HTML" Error.

Stories is Indexed in Google AMP SERP but when we click on Story, google show's  "Sorry, this is not a Valid AMP HTML"

We Test our AMP Pages HTML Code Through AMP Test - Google Search Console and AMP Validator Tool. ​I​t Show​'s Valid HTML
https://search.google.com/test/amp
https://validator.ampproject.org/

Here's One URL as a Example

Story url: www.jansatta.com/technology-news/phone-gadget/nokia-6-mobile-phone-first-online-sale-will-be-begins-shortly-at-amazon-india-www-amazon-com-buy-now-know-price-specifications-here/410276/

AMP Url: www.jansatta.com/technology-news/phone-gadget/nokia-6-mobile-phone-first-online-sale-will-be-begins-shortly-at-amazon-india-www-amazon-com-buy-now-know-price-specifications-here/410276/

Google AMP SERP URL: https://www.google.co.in/amp/www.jansatta.com/technology-news/phone-gadget/nokia-6-mobile-phone-first-online-sale-will-be-begins-shortly-at-amazon-india-www-amazon-com-buy-now-know-price-specifications-here/410276/lite/

It will work fine for first 5 minutes once the story Published then it show's "Sorry, this a valid amp html" error. this will happen only with August Post's. July Post's are working fine.

Need Your help to solve the Issue.

**Comment by nishukadian** [comment]
Please help its Urgent

**Comment by nishukadian** [comment]
Nobody to answer my question ?

**Comment by jridgewell** [comment]
Please open this on the [Google AMP forums](https://goo.gl/utQ1KZ), this Github project is only for issues with the opensource JS library.

**Comment by cramforce** [comment]
Could it be that the document starts with a BOM? (Byte order mark) This has recently been discovered as a difference between server side and JS validator.

**Comment by pravinagham** [comment]
Don't know but how to check BOM?

**Comment by cramforce** [comment]
Inspect the first byte of the response. It should be your doctype, if it is a different byte, you likely have a BOM.

**Comment by pietergreyling** [comment]
Planned [AMPBench](https://github.com/ampproject/ampbench) feature: [Add detection for byte order marks (BOM) in AMP docs #27](https://github.com/ampproject/ampbench/issues/27)
