### ISSUE TITLE
Limit history changes in AMP?

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#11071]
Should we limit the size of browser history that can be added on an AMP page?

@dvoytenko:
> Concerned with this scenario: user clicks in SRP, taps N times and then it's too hard to find the way back. Normally back button closes the doc and returns back to SRP after a tap or two. Making it N taps will still be ok, as long as there's some limit. 

@choumx:
> Don't users have the large "X" button in the top left to return to SRP? I'm not sure we should install a general constraint to accommodate a single AMP surface (SRP), especially as we push AMP embeds, AMP as canonical, etc.

Context: https://github.com/ampproject/amphtml/pull/10904#discussion_r134348999

/cc @dvoytenko @rudygalfi @ericlindley-g

**Comment by jridgewell** [comment]
Long pressing the back usually presents a concise list of pages to go back to.

**Comment by rudygalfi** [comment]
Would it make sense to introduce a way for the developer to specify which actions push onto the stack (or which ones should not)?

If there's explicit intent on the part of the developer and user, then I think it's reasonable to have no limit.

**Comment by dvoytenko** [comment]
@jridgewell In many/most of cases on mobile, pressing back button doesn't show anything.

@choumx "X" button is ok, but I'd really like to preserve some notion of predictability for hardware back button. Whichever sensible limit is good.

@rudygalfi Browsers themselves have limits. Usually 50 history entries max.

**Comment by choumx** [comment]
I think @jridgewell means browser back buttons. For example, Safari and Chrome iOS support long press. Not sure what happens on Android.

> If there's explicit intent on the part of the developer and user...

All of the ways to modify history require explicit developer intent. "Explicit" user intent is more subjective, but at minimum it requires a user gesture.

**Comment by dvoytenko** [comment]
In case of history display, all platforms (if they do that) still display a limited set, e.g. 5-10 at most and I'd bet a user cannot really understand anything deeper than 3-4. Also, keep in mind the WebView use cases as well.

**Comment by ericlindley-g** [comment]
To get a sense of the goal here: What are either the worst-case or highest-probability scenarios that we'd avoid by limiting history entries?  (I'm inclined to just fall back on platform constraints, but may not have a good idea of the risk yet)

**Comment by choumx** [comment]
One that comes to mind is an image carousel that push a new history entry when advancing to the next image (quite common and very annoying). However, this is acceptable IMO since a pub can already circumvent a constraint by using page navigations and N AMP pages.

**Comment by dvoytenko** [comment]
Yes, @choumx 's example is a very good one. I basically always assume that carousels out in the wider world don't work b/c of this and have a natural avoidance even though it's a good UX in many cases. In AMP we've been conscious from day 1 to keep the history stack shallow. At the very least, definitely something like this should not be possible. E.g. user presses a key and it issues multiple events that each push history. E.g. if somehow duplicate submits in a form a possible - that could quickly get from manageable to totally broken state.

**Comment by ericlindley-g** [comment]
That example makes sense — would be frustrating to have a lot of clicks to get back to the previous page. As a counter-example, I would offer use case of a product search/sort/filter interface implemented with amp-bind and amp-list for each of the three mechanisms. If I understand the mechanism correctly, here the user might easily build up an extensive history stack where many of the entries are valuable to be able to return to—and we may find that this is becomes a common pattern for e-comm sites. For this reason I recommend allowing at least a large history stack, if there's a cap at all.

Another question would be if we wanted to limit the ability to push multiple history states at once — that seems like a sensible limitation in most cases, but I'm not sure it's a common enough case to warrant implementing such a limit unless it's very low effort.

WDYT? Anything we're not taking into account?

**Comment by choumx** [comment]
> Another question would be if we wanted to limit the ability to push multiple history states at once

This actually already exists as part of #8678. Only a single `AMP.setState` or `AMP.pushState` may be invoked per action event.

**Comment by choumx** [comment]
So it looks like majority consensus is recommending no limit on history changes. Feel free to reopen and we can engage more folks in this discussion.
