### ISSUE TITLE
Some validator instances accept BOMs and some don't

### ISSUE THREAD

**Issue by namratakwwm** [ampproject/amphtml#11080]
Google AMP Search Showing "Sorry this page is Not valid AMP HTML" Error on AMP Pages.

Our website is also facing the same issue, the only change we have done recently is migrated to HTTPS. Before migration it used to work fine.

Please help with the issue.

Story URL: https://www.filmfare.com/photos/farhan-akhtar-and-diana-penty-promote-lucknow-central-at-a-popular-reality-tv-show-23291.html
AMP URL: https://m.filmfare.com/photos/farhan-akhtar-and-diana-penty-promote-lucknow-central-at-a-popular-reality-tv-show-23291.amp

**Comment by jridgewell** [comment]
Is your site somehow related to https://github.com/ampproject/amphtml/issues/11053?

**Comment by cramforce** [comment]
Could it be that the document starts with a BOM? (Byte order mark) This has recently been discovered as a difference between server side and JS validator.

**Comment by pravinagham** [comment]
How to check if my link has BOM?

**Comment by namratakwwm** [comment]
No we are not related to #11053

**Comment by Gregable** [comment]
It seems OK now.

**Comment by pravinagham** [comment]
It's working now. Thanks
