### ISSUE TITLE
Fast Fetch CSI for failed crypto verification

### ISSUE THREAD

**Issue by taymonbeal** [ampproject/amphtml#11090]
It would be useful to have data on how often this fails.

**Comment by glevitzky** [comment]
I added something along these lines here: https://github.com/ampproject/amphtml/pull/10953.

**Comment by taymonbeal** [comment]
Hmm, we still have that. @keithwrightbos, is this sufficient?

**Comment by jasti** [comment]
Seems like it is merged, so closing.
