### ISSUE TITLE
Retire container layout?

### ISSUE THREAD

**Issue by powdercloud** [ampproject/amphtml#1109]
@dvoytenko I think you mentioned container layout today, but I don't recall whether we're planning to remove it or use it in the future. It seems it's not used for now by any of the amp builtins or by the extensions.
Apart from simplifying the code, removing it could help provide better error messages, because it serves as the fallback when no width, height, layout are given. If we made FIXED the default, then the error would be "better put some width and height". With CONTAINER being the default, it's "can't use container here".
I'm OK with leaving it in, just figured I'd ask in case you have a status / opinion on it and I forgot. Thanks.

**Comment by dvoytenko** [comment]
It's not currently used, but we are not ready to make a decision on it yet.

**Comment by Meggin** [comment]
+1 to making default FIXED.

**Comment by dvoytenko** [comment]
I actually think that we'd err on the side of making default `nodisplay`.

**Comment by Gregable** [comment]
Would it be worth having different defaults for different elements? `<amp-pixel>` could default to `nodisplay` while `<amp-img>` could default to `fixed`, for example.

**Comment by dvoytenko** [comment]
It's marginally possible, but it is possible. The issue is that the layout has to be fully constructed even if, say, `amp-analytics` script has not downloaded yet. So this would mean that we'd have to map all default layouts in core.

**Comment by powdercloud** [comment]
Another choice is to make the default UNKNOWN / UNSUPPORTED etc. Then perhaps the error can say "either specify some layout or width/height/etc so we can infer it". This is very close to the status quo, except that our error message currently says "you're trying to use the implied container layout which isn't supported by this tag" (no tag actually supports it). We'd basically rename CONTAINER into what it is in practice.
Btw I think amp-analytics in particular has some extra complexities/inconsistencies currently (https://github.com/ampproject/amphtml/issues/1082).

**Comment by ericlindley-g** [comment]
Putting this in M2, but flag if you think it should be resolved sooner

**Comment by powdercloud** [comment]
The recently added amp-accordion uses CONTAINER, so there's less of a point here for the original issue. I'll close this for now, if anyone wants to keep discussing you may always reopen it - especially new ideas that make our error messages less confusing or makes the markup simpler are good. Thanks!
