### ISSUE TITLE
Ad left aligned

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#11113]
https://www.recode.net/platform/amp/2017/8/27/16212552/uber-ceo-dara-khosrowshahi
![recode](https://user-images.githubusercontent.com/2366341/29774764-ba29a770-8bd0-11e7-8198-a087c8078a0d.png)

CC @ampproject/a4a

**Comment by lannka** [comment]
seems an old issue due to multi-size config: #7548
which we believed the best solution is for pub to use a better CSS to fix this issue on their own.
