### ISSUE TITLE
Tracking services including

### ISSUE THREAD

**Issue by dmitrymotorin** [ampproject/amphtml#1111]
Hi guys,
We've a few tracking services such as:
- viglink
- google tag manager
- facebook events
- goroost
- chartbeat
Would it be the right way to include these tracking services via script async or will it be implemented as amp tags in future?

**Comment by cramforce** [comment]
CC @rudygalfi

**Comment by rudygalfi** [comment]
You will not be able to run these directly as you would on a non-AMP page, even using script async. It will need to be handled via the amp-analytics tag (#871).

The way amp-analytics is set up, you can either use "vendor labels" or you can do all of the configuration ad hoc by defining the relevant attributes, including where the ping goes.

We expect that Chartbeat will be available via the vendor label scheme (source: https://amphtml.wordpress.com/2015/12/09/continued-momentum-for-the-amp-project/) but you may need to investigate the ad hoc approach to support the others, or ask them about their plans for supporting AMP.
