### ISSUE TITLE
amp-timeago: will not validate if special chars are used

### ISSUE THREAD

**Issue by piscis** [ampproject/amphtml#11116]
## What's the issue?

The validation of the amp-timeago fails in google search console (https://search.google.com/test/amp)  but it passes in the amp validator (https://validator.ampproject.org/) when special chars are used inside of the amp-timeago tags.

This bug currently prevents some of our french translations are being indexed by google. It does not mater if we encode the letters in to the coresponding HTML entities.

## How do we reproduce the issue?

1. Open google search console: https://search.google.com/test/amp
2. Enter URL: https://amptest-znxflwoinv.now.sh
3. It displays (screenshot):
    Not a valid AMP page
    Invalid AMP pages will not have AMP-specific features in Google search results
    The mandatory text (CDATA) inside tag 'amp-timeago' is missing or incorrect.

<img width="903" alt="screen shot 2017-08-28 at 20 23 19" src="https://user-images.githubusercontent.com/326163/29787532-94425106-8c2f-11e7-84a1-f34ad4663ea3.png">

## What browsers are affected?

All

## Which AMP version is affected?

latest

**Comment by jridgewell** [comment]
Thanks for the bug report. Passing this to @Gregable

**Comment by honeybadgerdontcare** [comment]
Tracked internally as https://b.corp.google.com/issues/65119801

**Comment by honeybadgerdontcare** [comment]
We've got a fix in, but it'll take a couple weeks to get to production.
