### ISSUE TITLE
AMP validator forbids the "vector-effect" attribute for SVG elements.

### ISSUE THREAD

**Issue by jpgirard** [ampproject/amphtml#11128]
## What's the issue?
I need to use the vector-effect attribute for my SVG elements (vector-effect="Non-scaling stroke"):
          &lt;svg viewBox="0 0 193 128">
            &lt;ellipse cx="50%" cy="50%" rx="92" ry="59.5" vector-effect="non-scaling-stroke"></ellipse>
          &lt;/svg>
The AMP validator displays this error:
 The attribute 'vector-effect' may not appear in tag 'ellipse'.

## How do we reproduce the issue?
Use the svg element above in an AMP document, and check it with the validator .

## What browsers are affected?
Validator

## Which AMP version is affected?
AMP ⚡ HTML – Version 1503591987101

**Comment by honeybadgerdontcare** [comment]
@jpgirard I don't see 'inner-radius' within your sample code above. Could you provide an explicit sample?

**Comment by jpgirard** [comment]
I pasted the wrong error, I fixed it in the description:
 The attribute 'vector-effect' may not appear in tag 'ellipse'.

**Comment by Gregable** [comment]
@dvoytenko Dima, if you are OK with this, we can add it quickly.

**Comment by Gregable** [comment]
Surprisingly, this attribute isn't documented in the [MDN SVG docs](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute)

**Comment by dvoytenko** [comment]
@Gregable Yes. Let's add. This is part of 1.2 spec. Not on MDN for some reason...

**Comment by honeybadgerdontcare** [comment]
This will be in production in a couple of weeks.
