### ISSUE TITLE
Responsive iframes on iOS do not size correctly (workaround included)

### ISSUE THREAD

**Issue by poscar** [ampproject/amphtml#11133]
## What's the issue?

Responsive iframes are not sized correctly on iOS causing embedded video players to be scrollable and clipped due to content being sized larger than the container.

## How do we reproduce the issue?

1. Go to the JSBin [here](https://output.jsbin.com/wucoroseha) on a 4.7" iPhone iOS Safari: 
2. Scroll down to the first video iframe embed.
3. Observe how the embed is sized incorrectly, and you can actually scroll the video player within iframe.

### Inspecting Desktop Safari simulating an iPhone 6S
Observe the differences between the container dimensions and the contained iframe.
![screen shot 2017-08-30 at 9 10 54 am](https://user-images.githubusercontent.com/128726/29880238-4291aca2-8d75-11e7-859d-f449d1550be4.png)
![screen shot 2017-08-30 at 9 10 40 am](https://user-images.githubusercontent.com/128726/29880242-44cff28a-8d75-11e7-888e-a6c1e05b132a.png)

### Inspecting iOS Safari on 4.7" iPhone 7
Observe the differences between the container dimensions and the contained iframe.
![screen shot 2017-08-30 at 9 04 55 am](https://user-images.githubusercontent.com/128726/29880266-58ca8e58-8d75-11e7-852c-423f0714509d.png)
![screen shot 2017-08-30 at 9 04 38 am](https://user-images.githubusercontent.com/128726/29880267-5b217694-8d75-11e7-8a75-faae026bcd24.png)

## What browsers are affected?

Tested Safari on a 4.7" iPhone 7 with iOS 10.3.3(14G60)

## Which AMP version is affected?

`Powered by AMP ⚡ HTML – Version 1503591987101`

## Workaround:

Adding the following CSS rule seems to fix the problem:
```
  iframe.i-amphtml-fill-content {
    height: 0;
    max-height: 100%;
    max-width: 100%;
    min-height: 100%;
    min-width: 100%;
    width: 0;
  }
```

As can be observed in the JSBin [here](https://jsbin.com/labojanedi).

**EDIT** the workaround above doesn't validate, but this one does:
```
  .amp-active {
    iframe {
      height: 0;
      max-height: 100%;
      max-width: 100%;
      min-height: 100%;
      min-width: 100%;
      width: 0;
    }
  }
```

**Comment by jridgewell** [comment]
@KrzysztofPrzygoda Your gist and jsbin contain far too many extraneous bits for me to understand the differences.

**Comment by KrzysztofPrzygoda** [comment]
@jridgewell It can't be simpler than [this JSBin](https://jsbin.com/zefileq/edit?html,css,output). In short: you need 2 containers - one as a boundary (fixed size) and second as a scrolling area. Any further explanations I've covered in CSS comments.

**Comment by jridgewell** [comment]
Now I understand.

The issue with this approach is that the iframe's resizes to the full size of the document it contains. This breaks position-fixed elements inside the iframe (for instance, change the `div.pre-content.heading-holder` to use `position:fixed; top: 0px;`) since the document's viewport is equal to the document's size, not the viewport's size.

This is a much more difficult problem to solve (it requires a lot of JS and DOM hacks) than getting the iframe's document to be scrollable (requires a scrollable `<body>` and `-webkit-overflow-scrolling: touch`).

**Comment by digitalmaniak** [comment]
The workaround worked like a charm. I've been having this issue for some time. Thank you so much for this ^____^

**Comment by yursile** [comment]
Have you resolve this problem, My iframe still can't  be scrolled.

**Comment by GabeChurch** [comment]
This is an awesome fix, I have been attempting to resolve this maddening issue for some-time

**Comment by MRBalbuena** [comment]
What this solution proposed in [StackOverslow](https://stackoverflow.com/questions/23083462/how-to-get-an-iframe-to-be-responsive-in-ios-safari)

`iFrame {
  width: 1px;
  min-width: 100%;
}`
