### ISSUE TITLE
Fixed positioned elements with bottom + transition-duration or transition-delay get pushed off the page

### ISSUE THREAD

**Issue by acusti** [ampproject/amphtml#11132]
## What's the issue?

When applying `position: fixed;` to an element and using `bottom` to position it (I tried with a lot of different `bottom` values and the result was the same), if the element has a non-0 `transition-duration` or `transition-delay`, the element gets `style="top: calc(71880.9px);"`, where `71880.9px` depends on browser viewport size but is consistently a very large value which moves the element entirely off screen, rendering it invisible.

## How do we reproduce the issue?

Here are demos with a reduced test case:

With `transition-duration: 1ms` applied to the element: https://codepen.io/acusti/pen/LjXOON?editors=1000
With `transition-delay: 1ms` applied to the element: https://codepen.io/acusti/pen/ZJVGvv?editors=1000
Without `transition-duration` (the control): https://codepen.io/anon/pen/VzqKYW?editors=1000

## What browsers are affected?

Confirmed on Chrome, Safari, and Firefox

## Which AMP version is affected?

Version 1503591987101

I first noticed this around a month ago, but only dug in to figure out the reduced test case yesterday.

**Comment by jridgewell** [comment]
Looking into this.
