### ISSUE TITLE
AMP forms incompatible with IE 11

### ISSUE THREAD

**Issue by JoeNimble** [ampproject/amphtml#11149]
## What's the issue?
form submission is failing on IE11 with the following error:
`Response must contain the AMP-Access-Control-Allow-Source-Origin header`
`Form submission failed: Error: Response must contain the AMP-Access-Control-Allow-Source-Origin header​​​ _reported_`

the following headers ARE present in the response
```
Request Method:POST
Status Code:200 

access-control-allow-credentials:true
access-control-allow-origin:[our domain]
access-control-expose-headers:AMP-Redirect-To
access-control-expose-headers:AMP-Access-Control-Allow-Source-Origin
amp-access-control-allow-source-origin:[our domain]
amp-redirect-to:[page on our domain]
```
this is happening even on the non-cached version of the page

## How do we reproduce the issue?
try the following page in IE vs Chrome
https://joenimble.github.io/amp-form-example/ 

Setup a post amp-form, with an end point on the same domain,
respond with similar headers as above,
try it on Internet Explorer,
check the console for errors

## What browsers are affected?

IE 11.1593.14393.0

## Which AMP version is affected?

v0 (Version 1504040004635)

**Comment by jridgewell** [comment]
Do you have a link?

**Comment by cvializ** [comment]
I noticed that your headers are all lower-case. Does this error still occur when you use the correct capitalization for the header names and values?

**Comment by JoeNimble** [comment]
@cvializ headers are using correct capitalization, it just shows lower-cased in the inspector.
@jridgewell sorry for the delay, I've just made a simple example that repros the issue: https://joenimble.github.io/amp-form-example/

**Comment by cvializ** [comment]
I can't reproduce. In IE11 on Windows 10 and Windows 8.1 it submits and navigates as expected without adding an error to the console. Are there any other details you can provide to help me reproduce the issue?
![ie11](https://user-images.githubusercontent.com/2363700/30091236-7126c6fe-926d-11e7-8fe1-d1503b902ffa.gif)

**Comment by JoeNimble** [comment]
@cvializ weird. what version of IE are you running? I always get:
![f0f540f32a465d017eda1a5233f168d3](https://user-images.githubusercontent.com/10679867/30091991-b6ccb38e-92ff-11e7-985f-77b9ecbd8fc9.gif)
I've also replicated this on browserstack Windows 10, 8, 7 with all versions of IE11 available

**Comment by cvializ** [comment]
I'm using SauceLabs to test the behavior in IE. It looks like their version is 11.103.10586.0
<img width="244" alt="screen shot 2017-09-06 at 2 00 31 pm" src="https://user-images.githubusercontent.com/2363700/30134409-de8d44b8-930b-11e7-8b49-6fc6c51f3b44.png">

**Comment by JoeNimble** [comment]
Confirm it's not a caching problem. Are you able to try on BrowserStack or locally? For what ever strange reason, the problem does not exist on SauceLabs. I haven't been able to download the EXACT versions that SauceLabs uses for Win 8.1/10 but I did manage to get versions very close to - both older and newer - which get the errors.

**Comment by cvializ** [comment]
I used our physical windows machine and I am able to reproduce at your URL. It looks like the actual native `XMLHttpRequest.prototype.getAllResponseHeaders` isn't even returning the `AMP-Access-Control-Allow-Source-Origin` header.

**Comment by jridgewell** [comment]
You've specified two `Access-Control-Expose-Headers` headers, and IE11 is only using the first. Concatenate the two with a comma:

```
Access-Control-Expose-Headers=AMP-Redirect-To,Amp-Access-Control-Allow-Origin
```

**Comment by JoeNimble** [comment]
@jridgewell @cvializ, my bad. Thanks for the help
