### ISSUE TITLE
Add support for built-in (platform) variables to amp-analytics

### ISSUE THREAD

**Issue by btownsend** [ampproject/amphtml#1116]
Implement support for the list of amp-analytics built-in variables described in #871

Built-in variables will be expressed in amp-analytics config objects using the same placeholder syntax already used for trigger.vars and config.vars.  For example, `${domain}`.

In the event a built-in variable identifier conflicts with a trigger or config var identifier, the lookup precedence is trigger var > config var > built-in > url-replacement.

**Comment by btownsend** [comment]
Note that there is some overlap in values provided by built-in variables and values provided by `UrlReplacements` substitutions, which amp-analytics also supports (e.g. `${domain}` vs. `DOMAIN`).

I think this should be fine (so that a publisher may choose to consistently use ${} syntax if desired) but the implementation should be consistent (e.g. `${domain}` will also resolve to `UrlReplacements.DOMAIN` etc.)

**Comment by dvoytenko** [comment]
Syntax aside I'd like to make sure that we have the same variables where makes sense and that they are resolved by the same codepath. E.g. UrlReplacement.CANONICAL_HOST is the same as `${canonical_host}`.

**Comment by btownsend** [comment]
Agreed that expansions of equivalent vars (e.g. `${title}` and `TITLE`) should share the same code. 
Considering two alternatives:
  1. `AnalyticsPlatformVars.expand('${title}')` delegates to `UrlReplacements.expand('TITLE')`

  2. Add functions to `document-info.js` and have both `AnalyticsPlatformVars` and `UrlReplacements` delegate to it.

Thoughts?

**Comment by dvoytenko** [comment]
I think to start with, simply delegating to UrlReplacements is good. We may reconsider it later, but I think it'll get us going for now. Currently UrlReplacements is used for amp-pixel, amp-list and now amp-analytics. The documentation is here: https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md

But the ultimate goal is to make it serve all of these cases very well.
