### ISSUE TITLE
animation: Run amp-animation only as selected elements are scrolled into view

### ISSUE THREAD

**Issue by afilbert** [ampproject/amphtml#11167]
## What's the issue?

I'm trying to use `amp-animation` possibly along with `amp-position-observer` to slightly animate post elements in a theme. I want them to animate as they scroll into view. There will be an arbitrary amount of them at different places on the page, especially given the responsive design. 

The trouble I'm having is that I'm targeting general `.post-item` selectors in the `"animations": [...]` definition. That works great the first time something with a `.post-item` class scrolls into view, especially with `index()` for dynamic delay, but it triggers the animation for all other `.post-item` elements on the page (regardless of their position relative to the viewport). So the end result is that I see the animation for the first viewable posts, but all the others down the page are already through with their animation by the time I scroll down to them. 

`amp-position-observer` appears to only target specific `ids` at the moment. That means there needs to be an observer and animation for every post (or section of posts) I have on the page.

## How do we reproduce the issue?

1. Use a generic selector like `.post`.
2. Position a few elements with `class="post"` near the top and also bottom of a page, separated by content or a spacer.
3. Position an `amp-position-observer` to trigger the animation on the top `.post` element.
4. You should see the top animate as expected, but scrolling down reveals that the animation has already run its course on the bottom `.post` element. This is true whether using `enter:` or `scroll:` for the `on` action.

Here's a link to my example, where you can see the conditions list above: https://landseeampstart-exp.firebaseapp.com/templates/land-see/land-see.amp

## Browsers/AMP Version

Browsers:

I've tested latest (as of 9/03/17) versions of Safari, Firefox, and Chrome web browsers.

AMP Version:

Here are the includes in my ampstart project:

`https://cdn.ampproject.org/v0.js`
`https://cdn.ampproject.org/v0/amp-animation-0.1.js`
`https://cdn.ampproject.org/v0/amp-position-observer-0.1.js`

**Comment by afilbert** [comment]
I experimented with different approaches and ran into similar obstacles.

Creating `amp-position-observer`s dynamically seems to trigger the animation regardless of the `on` action.  I used `amp-accordion` with sections generated via mustache, specifically:

```
  {{#accordion}}
    <div class="accordion center items-center">
      <amp-accordion layout="container" disable-session-states class="amp-accordion">
        {{#section}}
        <section {{expanded}} class="{{classes}}">
          <h3 class="max-width-4 mx-auto">{{title}}</h3>
          <div class="accordion-content max-width-4 mx-auto">
            <amp-position-observer
              target-id="{{id}}"
              on="enter:postSlideIn.start"
              layout="nodisplay">
            </amp-position-observer>
            <ul id="{{id}}" class="list-reset m0 p0 center flex justify-center">
            {{#land-see-post}}
              <li class="post-item mr2 {{post-classes}}">
                <a href="{{post-url}}">{{> ./partials/image.snip.html}}</a>
                <a class="post-category" href="{{post-category-url}}">{{post-category}}</a>
                <h4 class="pt1"><a href="{{post-url}}">{{post-title}}</a></h4>
                <p class="pt1 pb3">{{post-copy}}</p>
              </li>
            {{/land-see-post}}
            </ul>
          </div>
        </section>
        {{/section}}
      </amp-accordion>
    </div>
  {{/accordion}}
```
`{{section}}` is an array of objects. So multiple `amp-position-observer`s are created, one for each accordion section. My first attempt didn't use `target-id`, but I added it to see if I could get things working.

Also, triggering on [visibility](https://www.ampproject.org/docs/reference/components/amp-animation#trigger-attribute) without an `amp-position-observer` does trigger the animation... but it applies whether the `.post-item` elements are actually within the viewport or not.

The animation results are already present on page load with each approach.

**Comment by Cheecherngho799** [comment]
Ho Chee Cherng

2017年9月4日 上午11:40，"Aron Filbert" <notifications@github.com>写道：

**Comment by afilbert** [comment]
As mentioned on the AMP #general Slack channel, I'm looking for a way to target many elements with a common selector and experience the triggered `amp-animation` on each _as they scroll into view_. This approach would significantly reduce complexity, particularly with dynamically generated and responsive content.

Perhaps an alternative approach is to attach a CSS class to elements as they scroll into view. This would eliminate much of the animation and observer markup that I'm currently using.

**Comment by aghassemi** [comment]
Hi @afilbert 

Sorry for the late reply ( was mostly Out of office ).
This should be possible by creating an `amp-animation` instance for each `amp-position-observer` instance (instead of a single `amp-animation` with a class selector). Could you give it a try and let me know if still an issue?

Note: Making these use-cases easier to code is definitely something we like to do by providing syntax-sugar component (like parallax) so I will keep this issue open,however initial focus has been on having a low-level API that can handle a wide range of use-cases however.

**Comment by afilbert** [comment]
No worries, @aghassemi. Thanks for the feedback! I felt using multiple copies of virtually the same animation/observer might be working harder than I needed, but it sounds like that's an acceptable approach for now. I can work with that. :)

**Comment by aghassemi** [comment]
Handled by `amp-position-observer`

ton of examples here: https://codepen.io/collection/nMJYrv/
