### ISSUE TITLE
new action event request: input-throttled

### ISSUE THREAD

**Issue by codecvlt** [ampproject/amphtml#11175]
Hi there, I have a use case where I'm using ```<input type='range' on="change: ...">``` to control an amp-animation. I want to be able to seek the animation while the user is dragging the slider. Currently it seems this is not possible, and the change event only fires after the user has stopped dragging the slider. 

I understand that firing "change" every time value changes could be bad for performance, but perhaps a throttled version of the change event could be a good compromise.

Thoughts?

**Comment by cvializ** [comment]
I think the existing `input-debounced` event could fit your use-case. Use it just like `change`:
```html
<input type="range" on="input-debounced:...">
```
Note that this is debounced, not throttled. The event is triggered 300ms after the user stops moving the slider, not every 300ms while the user is moving the slider.

**Comment by codecvlt** [comment]
input-debounced will not work for me since i need the event to fire as the user is moving the slider.

**Comment by jridgewell** [comment]
This would be a good GFI issue.
