### ISSUE TITLE
Amp for UCBrowser

### ISSUE THREAD

**Issue by supernoze** [ampproject/amphtml#11195]
**Please only file bugs/feature requests for AMP here.**
Please add amp for ucbrowser since it is the most popular browser in asia.

**Comment by cramforce** [comment]
We already support UC. Updated docs accordingly. In practice UC doesn't support automated testing and so support is more of a best effort thing. If you have concrete problems please report them.

**Comment by yajiv185** [comment]
@cramforce document still not showing UC browser. Why is that?
![capture12](https://user-images.githubusercontent.com/15910976/37815295-45d78948-2e94-11e8-9750-c73b04ab276b.PNG)

**Comment by cramforce** [comment]
We updated the official spec here. See https://github.com/dvdyakonov/amphtml/commit/2c93a410813cffde5cd9b757c06898c3bf66cc66 The screenshot is from the docs, right?

Need to update that docs as well. CC @pbakaus @bpaduch

**Comment by yajiv185** [comment]
Yes screenshot is from [here](https://www.ampproject.org/support/faqs/supported-browsers).
