### ISSUE TITLE
Support for size fluid

### ISSUE THREAD

**Issue by juanchaur1** [ampproject/amphtml#11198]
Is there any reason why amp-ad support multi sizes and doesn't support fluid?

**Comment by glevitzky** [comment]
Fluid is somewhat more complicated than multi-size, however an implementation for fluid is currently underway. We expect to start a beta for it sometime later this month.

**Comment by juanchaur1** [comment]
@glevitzky thanks for the feedback!

**Comment by honeybadgerdontcare** [comment]
This is now valid in production.
