### ISSUE TITLE
Lightbox 2.0: caption transition polish

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#11215]
Updating this issue to track all animation polish requirements associated with the Lightbox caption: 

1. Right now the lightbox caption transition duration is always 500 ms, but it would be nice to adjust it depending on the caption content height.
2. No exit transition
3. The caption mask should only be sized to the height of the caption, but it's currently sized to mask out the entire image. 
4. Text description can get into a situation where it disappears but doesn’t come back if you double click it fast enough or spam clicks.

**Comment by cathyxz** [comment]
Relatedly, there's also a bug regarding the caption mask, which I'm filing here instead of as a separate issue. It should only be sized to the height of the caption, but it's currently sized to mask out the entire image. A light gradient fading to the text might also be nice.

**Comment by cathyxz** [comment]
> The caption mask should only be sized to the height of the caption, but it's currently sized to mask out the entire image.

This seems like bad UX, so not implemented. But it is easy to go either way.
