### ISSUE TITLE
`gulp check-types` broken on Travis due to the presence of `_JAVA_OPTIONS`

### ISSUE THREAD

**Issue by rsimha-amp** [ampproject/amphtml#11210]
This fails on the new trusty machines on Travis.

Steps:
1. `export _JAVA_OPTIONS="-Xmx2048m -Xms512m"` (used on Travis)
2. `gulp clean && gulp check-types`

Result:
```
Error compiling ./3p/iframe-transport-client-lib.js
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
```

EDIT: This is likely due to the old version of `gulp-closure-compiler` we're using. Skip down to https://github.com/ampproject/amphtml/issues/11210#issuecomment-327990926

**Comment by rsimha-amp** [comment]
This was discovered via #11203, and is blocking the fix in #11206

**Comment by rsimha-amp** [comment]
assigning to @jonkeller and @alanorozco in the hope that one of you knows what's going on

**Comment by jonkeller** [comment]
I am familiar with this file and will look when I get off the bus

**Comment by jonkeller** [comment]
Hmm...https://travis-ci.org/ampproject/amphtml/jobs/272980280 restarted and failed with:

Error compiling **./3p/ampcontext-lib.js**
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m

But other times it fails on ./3p/iframe-transport-client-lib.js

**Comment by rsimha-amp** [comment]
@erwinmombay, does [this](https://stackoverflow.com/questions/43398795/maven-compilation-fails-with-error-static-interface-methods-are-not-supported-in) look similar to what's going on here?

**Comment by jonkeller** [comment]
I notice that on my Mac, the default values are:
```
    uintx InitialHeapSize                          := 268435456                           {product}
    uintx MaxHeapSize                              := 4294967296                          {product}
```
This is from:
```
java -XX:+PrintFlagsFinal -version | grep HeapSize
```

So the args -Xmx2048m -Xms512m are reducing, not increasing, compared to default _on this particular machine_.

If I do "unset _JAVA_OPTIONS" and then repeat the gulp command from the earlier comment, it works fine. 

But, puzzlingly, if I do "export _JAVA_OPTIONS="-Xmx4g -Xms2g", which should be a no-op, and repeat the gulp command, it fails.

**Comment by jonkeller** [comment]
It seems like it fails any time _JAVA_OPTIONS is set to anything. For instance:
export _JAVA_OPTIONS="-Dfoo=bar"

I'm also concerned that export _JAVA_OPTIONS="-showversion" causes:
```
Picked up _JAVA_OPTIONS: -showversion
Unrecognized option: -showversion
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

That's a standard option listed by "java -h".

**Comment by jonkeller** [comment]
So, at this point I'm curious to know what is setting _JAVA_OPTIONS, and if we could just remove it? What are the other ways in which Trusty differs from the previous env?

At this point, since it works without the _JAVA_OPTIONS, doesn't work regardless of what _JAVA_OPTIONS is set to, and the file that it fails on changes seemingly randomly, I don't believe that this is actually caused by a problem with the content of iframe-transport-client-lib.js

Please ping me if there is more I can do.

**Comment by rsimha-amp** [comment]
@jonkeller, thanks for investigating. I've raised this with the Travis folks at https://github.com/travis-ci/travis-ci/issues/8315#issuecomment-327951718. Feel free to comment there if you have more to add.

**Comment by rsimha-amp** [comment]
Looks like the version of `gulp-closure-compiler` we use is outdated. The npm page for the compiler (https://www.npmjs.com/package/gulp-closure-compiler) points to a github repository (https://github.com/steida/gulp-closure-compiler) that was last updated more than 2 years ago, and is no longer accessible.

**Comment by rsimha-amp** [comment]
And there are no fixes or updates imminent from `gulp-closure-compiler`. See [this cached bug](https://webcache.googleusercontent.com/search?q=cache:Ni_GBjMUitQJ:https://github.com/steida/gulp-closure-compiler/issues/33+&cd=3&hl=en&ct=clnk&gl=us) :/

**Comment by rsimha-amp** [comment]
@erwinmombay: There is hope here: https://www.npmjs.com/package/google-closure-compiler#using-the-gulp-plugin. I'm going to see if we can migrate the closure compiler we use to `google-closure-compiler`.

**Comment by rsimha-amp** [comment]
There's also `google-closure-compiler-js`, which is pure javascript. https://github.com/google/closure-compiler-js.

**Comment by rsimha-amp** [comment]
This is now being tracked by #11229 (look there for future updates).

**Comment by rsimha-amp** [comment]
After #10791, we now use a new closure compiler based on the old version of `gulp-closure-compiler` we were using. See #11206 for the solution for the JVM memory pool issue.
