### ISSUE TITLE
Lightbox 2.0: find the proper icons for gallery view and picture view

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#11214]
<img width="342" alt="screen shot 2017-09-07 at 2 47 44 pm" src="https://user-images.githubusercontent.com/3897214/30186872-39e6d65a-93dc-11e7-92d0-6b23579593c0.png">
<img width="342" alt="screen shot 2017-09-07 at 2 46 27 pm" src="https://user-images.githubusercontent.com/3897214/30186873-39e940a2-93dc-11e7-9d53-6d76d8ee7122.png">

**Comment by cathyxz** [comment]
@spacedino do you know what icons are appropriate to use?

**Comment by cathyxz** [comment]
Closed by https://github.com/ampproject/amphtml/pull/13074
