### ISSUE TITLE
Problems displaying content with amp on iPhone

### ISSUE THREAD

**Issue by fuenkchen** [ampproject/amphtml#11226]
## What's the issue?

We’ve been using AMP at NZZ in Zurich for a while now, but only recently we’ve run into an issue with our quizzes with AMP on iOS (and only iOS).

Here’s an example of an article with an embedded quiz: https://www.nzz.ch/amp/zuerich/aktuell/nzz-quiz-was-wissen-sie-ueber-winterthur-ld.1307248. 

Basic html is rendered on server-side, client-side scripts are loaded via system.js. 
The DOM elements are loaded correctly but are not being displayed on iOS, instead just the blue rectangle (which you see on desktop/other mobile devices as well, but just as background) is shown.

## How do we reproduce the issue?

1. Open the above mentioned URL on a desktop browser or on any mobile device except iOS based devices. Then you see, what a quiz should like, here is a screenshot too:
<img width="589" alt="screen shot 2017-09-08 at 14 34 20" src="https://user-images.githubusercontent.com/4837884/30211854-da37ae42-94a2-11e7-9b97-7b807070f0c9.png">
2. Open the same url on a iOS based device, e.g. iPhone7 and you will see just the blue background rectangle, like:
<img width="306" alt="screen shot 2017-09-08 at 14 56 07" src="https://user-images.githubusercontent.com/4837884/30212589-e2bb9a08-94a5-11e7-9c07-21d0bbc9a008.png">

## What browsers are affected?

It seems to be independent of the browser, we tested it with safari, twitter in-app browser and chrome. But the problem just occurs on iOS based devices.

## Which AMP version is affected?

Amp version we use is 1504119607313.

Thanks for having a look into it!

**Comment by jridgewell** [comment]
This is a bug inside an iframe (the iframe isn't AMP, the page is). So it's not anything we've done.

The error was easy enough to spot, though. The `div.q-quiz-element-container.q-quiz__cover.s-color-primary-1.q-quiz-element-container--is-active` has a `width: 4.545454545454546%` inline style set on it. Commenting that out make the content visible.
