### ISSUE TITLE
Upgrade to a newer closure compiler

### ISSUE THREAD

**Issue by rsimha-amp** [ampproject/amphtml#11229]
[Recent changes](https://blog.travis-ci.com/2017-08-29-trusty-image-updates) to Travis ([restrictions](https://docs.travis-ci.com/user/build-environment-updates/2017-09-06/) on the JVM memory pool size) have [broken](https://github.com/travis-ci/travis-ci/issues/8315#issuecomment-327951718) `gulp-closure-compiler`, the closure compiler used to build the AMP runtime.

Moreover, the compiler version we use is outdated, and the [npm page](https://www.npmjs.com/package/gulp-closure-compiler) points to a [github repository](https://github.com/steida/gulp-closure-compiler) that was last updated more than 2 years ago and is no longer accessible, with [no fixes imminent](https://webcache.googleusercontent.com/search?q=cache:Ni_GBjMUitQJ:https://github.com/steida/gulp-closure-compiler/issues/33+&cd=3&hl=en&ct=clnk&gl=us).

Since we need to use a custom Java par to build the AMP runtime (to allow for code splitting), and since a pure JS compiler is about 2x slower, we are left with one choice: Migrating to `google-closure-compiler`  (see [npm page](https://www.npmjs.com/package/google-closure-compiler) and [github page](https://github.com/google/closure-compiler-npm)) and using its [gulp plugin](https://www.npmjs.com/package/google-closure-compiler#using-the-gulp-plugin).

This bug is meant to track the migration to the new compiler.

Originally discovered via #11203
Related issues: #11210, https://github.com/travis-ci/travis-ci/issues/8315

**Comment by erwinmombay** [comment]
PR for CC update https://github.com/ampproject/amphtml/pull/10791

**Comment by rsimha-amp** [comment]
@erwinmombay  I noticed that #10791 wasn't able to get us back to the new Travis image. Can you comment on what's left to be done? Is there any hope for making #11232 work? Or is that a lost cause?

**Comment by rsimha-amp** [comment]
This issue was fixed by #10791. See #11206 for the solution for the JVM memory pool issue.
