### ISSUE TITLE
immediate unannounced no. of setStage() limitation on Events

### ISSUE THREAD

**Issue by bhavyasaggi** [ampproject/amphtml#11224]
We brought up a AMP page live on production this week and today it started failing, producing an Error:
`One state action allowed per event.`

I immediately looked into it and found that 
`setState({foo: 'bar'}) | Requires amp-bind. Merges an object literal into the bindable state. See more details.When used with multiple actions, subsequent actions will wait for setState() to complete before invocation. Only a single setState() is allowed per event.`
under `https://github.com/ampproject/amphtml/blob/master/spec/amp-actions-and-events.md#special-targets`

The error was being thrown because it was because i was using 'setState()' twice on the "form-submit-success" event of form element. 
[ I was using `<script async if="data.layoutData.ampJs['amp-bind']" custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>` ]

A sudden change brought about a change in traffic and these kind of sudden uninformed changes might be cause a lot of trouble later if the page was cached and served.
Is there any way to mitigate sudden changes? some milestone/snapshot amp modules that could be released for more stable functionality.

PS: [ `Powered by AMP ⚡ HTML – Version 1504119607313` ]

**Comment by jridgewell** [comment]
I don't understand what you're asking for here. It seems you added a second `setState` call in the same action, but that has no effect on traffic (it's not a validation error).

**Comment by bhavyasaggi** [comment]
Sorry if I failed to portray my problem.
For my AMP pages, I had put two `setStage()` calls on my form's `submit-success` event and it was working flawlessly last week.
But today I found that form was failing, and throwing `One state action allowed per event.` in the console.

I checked on the `https://github.com/ampproject/amphtml/blob/master/spec/amp-actions-and-events.md#special-targets` and it had a new line appended stating that `Only a single setState() is allowed per event.` [git history stated that the line was appended about a week ago]

This was totally unannounced and caused my AMP page to break, making me do a immediate fix.
Hence, I wished to inquire if there was some milestone or snapshots which will save my page from breaking in the future.

**Comment by jridgewell** [comment]
I see what you saying now. Passing to @choumx.

**Comment by choumx** [comment]
@bhavyasaggi Thanks for filing this and my sincere apologies about the breaking change. We'll do our best to avoid them in the future and announce necessary changes with ample warning. 

For this specific issue, you can combine the two `AMP.setState` calls into one by merging the object params. For example:

```html
<button on="tap:AMP.setState({foo: 123}), AMP.setState({bar: 456})">

<!-- Combine the object params into one. -->
<button on="tap:AMP.setState({foo: 123, bar: 456})">
```

**Comment by csabakos** [comment]
> For this specific issue, you can combine the two AMP.setState calls into one by merging the object params.

@choumx That is true, however this is not always the case:
```
<button on="tap:AMP.setState({foo: null}), AMP.setState({foo: {bar: 123}})">
```
cannot be combined into a single `AMP.setState()` expression and since `AMP.setState()` always deep merges.

Please consider reopening or creating a variant of `AMP.setState()` that does not deep merge.
