### ISSUE TITLE
Provide client library of Google CID API for non-AMP page

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#11239]

**Comment by lannka** [comment]
It's launched a while ago: [here](https://github.com/google/amp-client-id-library)

**Comment by jg-rc** [comment]
@lannka @rudygalfi  is this client library still active ? i tried requesting an api key, but it wasn't possible.

**Comment by rudygalfi** [comment]
@jg-rc we are shifting away from the Client ID API in favor of [AMP Linker](https://github.com/ampproject/amphtml/issues/16737)
