### ISSUE TITLE
`event.value` is `null` for <textarea> `change` event

### ISSUE THREAD

**Issue by zhangsu** [ampproject/amphtml#11234]
## How do we reproduce the issue?

1.
    ```html
    <textarea on="change:AMP.setState({foo: event.value})"></textarea>
    ```
2. Type in the text area and lose focus.

3. Call `AMP.printState()` in the console.

4. The `foo` state is set to `null`, even though the textarea value is non-empty.

## What browsers are affected?

Only tested on Chrome.

## Which AMP version is affected?

Only tested with 1504119607313.

**Comment by jridgewell** [comment]
Don't know if this is a form bug or a bind bug. /to @cvializ and @choumx

**Comment by choumx** [comment]
Just a simple change needed in `action-impl.js`. We probably should make the whitelisted properties more robust.
