### ISSUE TITLE
Add clientId support to amp-analytics

### ISSUE THREAD

**Issue by btownsend** [ampproject/amphtml#1124]
The clientId API (`src/cid.js`) requires parameters that specify the client id's namespace and consent. 

We need a way to express these parameters in amp-analytics configuration blocks, and need to determine when and how consent is presented.

**Comment by cramforce** [comment]
I'm working on this, but one thing you can think about already:

It'll be asynchronous (exposed as a promise), so your code needs to be able to handle that.
