### ISSUE TITLE
Allow whitelisted custom fonts to have <link> outside the <head> to reduce render blocking

### ISSUE THREAD

**Issue by travismo123** [ampproject/amphtml#11249]
## What's the issue?
`<link>` for whitelisted fonts needs to be in the `<head>` but this causes render blocking, especially on PageSpeed Insights.
`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">`

<img width="1238" alt="screen shot 2017-09-08 at 3 39 24 pm" src="https://user-images.githubusercontent.com/12947178/30234072-d6d05554-94ae-11e7-809f-c2c639646a84.png">

## How do we reproduce the issue?
Place `<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">` or any other whitelisted CSS outside of `<head>`. You will get a validation error of 
"The parent tag of tag 'link rel=stylesheet for fonts' is 'body', but it can only be 'head'."

## What browsers are affected?
All browsers?

## Which AMP version is affected?
Latest

**Comment by cramforce** [comment]
We could allow this, however, font stylesheets in AMP are not render blocking. PageSpeed insights is simply wrong. See https://github.com/ampproject/amphtml/blob/master/src/font-stylesheet-timeout.js#L58 for details.

I'm inclined to close this. We aren't here to make PSI happy. We are here to make users happy.

**Comment by Gregable** [comment]
Technically, link elements must be in the document head. From [HTML5 Spec -> The link element](https://www.w3.org/TR/html5/single-page#the-link-element):

```
If the rel attribute is used, the element is restricted to the head element.
```

However, we don't enforce this consistently, and clearly neither do browsers. I don't know if there is any practical advantage to requiring this in the head. Perhaps the network connections get set up slightly earlier, but it would seem to me to be rather minor.

**Comment by Gregable** [comment]
My conclusion is that I'm fine with whatever @cramforce decides here.

**Comment by cramforce** [comment]
Given that there is no technical reason to do this beside making PSI happy, we won't do it.

It would be more complicated than allowing the link tag in the body. We'd need to require a matching preload tag in the head to get good performance.
