### ISSUE TITLE
Make the actual "value" of <textarea> bindable

### ISSUE THREAD

**Issue by zhangsu** [ampproject/amphtml#11246]
## What's the issue?

`<textarea>` DOM elements don't have a `value` attribute, so its value cannot be bound using `<textarea [value]>`. The only thing closest to binding `<textarea>` value is the `[text]` binding. However, `[text]` only works if the `textarea` hasn't been polluted yet (no characters have been entered into the text area).

## How do we reproduce the issue?

1.
    ```html
    <textarea [text]="foo"></textarea>
    <button on="tap:AMP.setState({foo: 'bar'})"></button>
    ```

2. Type in the text area and lose focus.

3. Click on the button.

4. The text area content didn't change to `bar`.

What works is as follows (with the same AMP HTML):

1. Without typing anything into the text area, click on the button.

2. Text area content changed to `bar`.

## What browsers are affected?

Only tested on Chrome.

## Which AMP version is affected?

Only tested with 1504119607313.

**Comment by choumx** [comment]
Fixed by #11719.
