### ISSUE TITLE
Components in Shadow DOM fail with errors in Desktop and Mobile Safari

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#11266]
<img width="813" alt="screen shot 2017-09-11 at 2 18 18 pm" src="https://user-images.githubusercontent.com/2363700/30297329-4a341e64-96fc-11e7-8fd9-4a5e5de471fd.png">

**Comment by dvoytenko** [comment]
Relevant Safari bug: https://bugs.webkit.org/show_bug.cgi?id=103393
