### ISSUE TITLE
Intent-To-Implement: Support for VK.COM Posts and Polls

### ISSUE THREAD

**Issue by bonifaty** [ampproject/amphtml#11288]
I am planning to implement extensions for http://vk.com widgets, full list of widgets available for websites can be found here https://vk.com/dev/widgets_for_sites

As a priority I want to focus on Post and Poll AMP extension.

Approach
-----------

I am going to use approach similar to Twitter and Facebook:
* Add new third party system **vk.js**
* Add new **amp-vk** extension for VK Posts and **amp-vk-poll** for VK Polls
* Using callback from vk.com API update dimensions of VK Widgets (similar to Facbook / Twitter). That's because our posts have variable height!

Questions
------------
1. As well as Twitter, Facebook and Github, the VK posts have variable height hence it's required to use **context.updateDimensions** method. There is a whitelist of 3p vendors in 3p/integration.js:
`if (embedType === 'facebook' ||
      embedType === 'twitter' ||
      embedType === 'github') {
    // Only make this available to selected embeds until the
    // generic solution is available.
    win.context.updateDimensions = triggerDimensions;
  }`
Can I also pop 'vk' into this list?

2. Every AMP tag with 3p is restricted to separate iframe hence all 3p resources are loaded each time, e.g. for 4 **<amp-vk />** tags AMP loads 4 integration.js files - please see screenshot attached
<img width="1612" alt="screen shot 2017-09-13 at 20 09 43" src="https://user-images.githubusercontent.com/6319386/30390701-a73460b4-98bf-11e7-81d8-f7f8129c7249.png">

 I guess this was mentioned by [Reddit extension author](https://github.com/ampproject/amphtml/issues/5062#issue-177505689) Is there a better (more efficient) way to handle multiple amp tags on single page?

3. Is it correct that my tag can't interact with AMP page itself? i.e. I can't add any popups / dialogs on AMP page itself? only inside my amp-tag?

**Comment by aghassemi** [comment]
cool, LGTM

1- yes, that's fine.
3- you can, your 3P script running in the iframe and communicate with your amp extension through postMessages and your AMP extension runs as 1P in AMP. That being said, the component still needs to adhere to AMP's UX principles such as no popups without explicit user-action.

**Comment by jridgewell** [comment]
Closed by #11299.
