### ISSUE TITLE
AMP-ACCESS and AMP-LIVE-LIST revalidation issues

### ISSUE THREAD

**Issue by QES** [ampproject/amphtml#11295]
**Please only file bugs/feature requests for AMP here.**

## What's the issue?

I am implementing an AMP-ACCESS paywall and as part of the offering removing adverts for subscribers.  I also use AMP-LIVE-LIST to update the pages in a number of ways, if the update includes an advert or other element that should by hidden by AMP-ACCESS the element appears/re-appears on the page until manually refreshed.

I'm not sure if this is the expected behaviour.

## How do we reproduce the issue?

Version 1) We have a blogging environment our standard system adds an advert after three live updates and then every 7 additional blog posts, when the update occurs with the included advert the advert is shown to a user even though their amp-access status is for such units to be hidden. Other such elements on the page have been hidden.

Version 2)  Out home page has 40 news items on it they are held in an amp-list-live so that when there are new items they are added automatically when a new item occurs any hidden adverts within the 40 news items are then shown to users.

In both cases the advert units (the units I wish to hide/show with the amp-access) are inside the amp-live-list unit.  Elements outside the amp-live-list unit are not affected but those pulled in as part of an update are not set to the correct status.

If this is considered a bug then I can provide more details and code / html examples.

## What browsers are affected?

All tested Chrome / Safari / Desktop / Mobile

## Which AMP version is affected?

Version  1505341213754 I have only just looked at amp-access

**Comment by dvoytenko** [comment]
Thanks for the report. I will fix this.

**Comment by QES** [comment]
hi @dvoytenko if you need any more please let me know

**Comment by dvoytenko** [comment]
Fix in review: #11308.
