### ISSUE TITLE
Support video-interface and autoplay for amp-vimeo.

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#11319]
Should be fairly similar to `<amp-dailymotion>` if Vimeo has an API into this.

**Comment by wassgha** [comment]
From my research on the Vimeo API, "playing" the video will automatically make it enter fullscreen on mobile (simulates the old iOS behavior). This prevents autoplay and video docking.

**Comment by aghassemi** [comment]
yeah : ( https://vimeo.com/forums/topic:268198 https://vimeo.com/forums/feature_requests/topic:100233 

> For a consistent user experience with the Vimeo Player, we do not allow autoplay or inline playback on mobile, and for the immediate future will always require the user to initiate playback. Apologies for the trouble!

I don't get it.

**Comment by aghassemi** [comment]
https://github.com/ampproject/amphtml/pull/15326 good enough.
