### ISSUE TITLE
I2I: Make <amp-auto-ads> insert ads in between paragraphs

### ISSUE THREAD

**Issue by jingtang10** [ampproject/amphtml#11313]
At the moment amp-auto-ads only uses fixed placements (https://github.com/ampproject/amphtml/blob/b1e053cc0cc504add3a3011c8bd40952441898f5/extensions/amp-auto-ads/0.1/placement.js#L240) to create banner ads. We'd like to extend the functionality of amp-auto-ads to create ads in between consecutive paragraphs. This requires the following changes on a high-level:

1) create a new placement type to represent placements between consecutive paragraphs
2) create a new ad strategy (https://github.com/ampproject/amphtml/blob/master/extensions/amp-auto-ads/0.1/ad-strategy.js) that applies such placements from the auto ads config. Crucially, the new strategy will only inject ads between consecutive paragraphs. All existing constraints (ad spacing, etc) should be respected.

And the following network-specific (adsense) changes:
1) create a new data-auto-format value 'aia' (https://github.com/ampproject/amphtml/blob/b1e053cc0cc504add3a3011c8bd40952441898f5/extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js#L142) that will dictate the ad width/height for these new ads
2) create a new 'fa' param (https://github.com/ampproject/amphtml/blob/b1e053cc0cc504add3a3011c8bd40952441898f5/extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js#L217) that will come from a network specific attribute, sent over in the auto ads config.

@charliereams @tlong2 @wjfang @dvoytenko @lannka

**Comment by lannka** [comment]
Can you clarify what is "paragraph" here? Is it text surrounded by `<p>`, or is it text separated by line breaks in the same text node?

Is this something supported in non-AMP world? If so, maybe a help center doc might explain things better.

**Comment by jingtang10** [comment]
Thanks Hongfei. Paragraphs are indeed defined as text surrounded by <p> currently. Worth noting that paragraphs will be sent from the network as placements in the auto ads config. This means networks can implement their definitions of paragraph, and what the extension would do is to find consecutive paragraphs given the config.

This also means the extension is doing relatively light work. It doesn't need to analyse the DOM heavily and identify paragraphs; it looks for paragraph placements in a similar way it looks for other auto ads placements.

This is not a product launched in non-AMP world. But I can provide update here as soon as more information is publicly available.

**Comment by dvoytenko** [comment]
This sounds good to me, in general. Would you like to schedule this for Design Review?

**Comment by jasti** [comment]
Thanks @jingtang10 - @mrjoro, any chance we can schedule this for design review next week?

**Comment by mrjoro** [comment]
Looks like next week is currently free; @jingtang10 please add a comment on the [design review issue](https://github.com/ampproject/amphtml/issues/11181) to claim a spot. :)

**Comment by jpettitt** [comment]
I may not make the DR so here are some thoughts

You'll probably need to define a minimum word count that defines what a real paragraph is.  Otherwise if a user makes a list using <p> tags you'll end up with far more ads than you expected.  We do this server side and the logic we use is that if a paragraph doesn't meet the word count minimum then we move to the next one and ad it's word count until we reach the minimum.  20 words works well as a default.

A paragraph itself should be defined by a selector for example `div.content > p`

You'll want a "max ads" value so that you don't put more than your ad provider permits.

**Comment by mrjoro** [comment]
@jingtang10 were you still interested in bringing this to a design review or do you have any other updates?

**Comment by lannka** [comment]
Closing now for inactivity.
