### ISSUE TITLE
Google Analytics Real-time doesn't work with AMP

### ISSUE THREAD

**Issue by skydry** [ampproject/amphtml#11327]
## What's the issue?

Google Analytics Real-time does not show real-time visitor on AMP:

<img width="298" alt="screen shot 2017-09-19 at 09 52 22" src="https://user-images.githubusercontent.com/32090571/30581412-4d0690fc-9d20-11e7-88fe-366df6e3298b.png"> 

## How do we reproduce the issue?

1. Include AMP analytics script in head before the AMP script:
```
<script async custom-element="amp-analytics" 
    src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>
```
2. Include ```amp-analytics``` to body:
```
<amp-analytics type="googleanalytics">
<script type="application/json">
{
  "vars": {
    "account": "UA-XXXXX-Y"
  },
  "triggers": {
    "trackPageview": {
      "on": "visible",
      "request": "pageview"
    }
  }
}
</script>
</amp-analytics>
```
3. Visit the page (either from a browser and device where you are logged in with the same account as in Google Analytics or from a different browser and device where you are not logged in, such as your phone); I tested only accessing the page directly, so not the Google cached version

4. Check Google Analytics Real-time

## What browsers are affected?

Mobile: Chrome, Safari
Desktop: Chrome, Safari and Firefox

## Which AMP version is affected?

Version 1505341213754

**Comment by SchnWalter** [comment]
Your code seems to be valid, did you make sure you are using the right `account` number?

For me it works just fine on a couple of websites.

**Comment by skydry** [comment]
Thanks for checking and yes, I use the right account number, I just looked again. This is strange.

**Comment by skydry** [comment]
Today, it works. It seemed that Google Analytics needed one day to calibrate or something.
