### ISSUE TITLE
amp-sticky-ad not render on Android 

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#11340]
`<amp-sticky-ad>` not render in viewer (Android). 
related to [fixed layer](https://github.com/ampproject/amphtml/blob/master/src/service/fixed-layer.js#L566
). Element top offset with viewer header paddingTop seems to be the reason. 

Example:  <amp-sticky-ad> with clientRect {left: 0, right: 350, top:678, bottom: 732}. Viewer header has padddingTop of 54px. When added to fixed layer, <amp-sticky-ad> will has a clientRect of {left:0, right:350, top:678+54=732, bottom:732}. Runtime will skip layout request to the child <amp-ad> element, because it has a height 0. 

One straightforward fix would be to not offset top position for `<amp-sticky-ad>`

cc @jridgewell @cramforce @lannka

**Comment by jridgewell** [comment]
Demo page please?

**Comment by zhouyx** [comment]
https://www.google.com/amp/s/www.washingtonpost.com/amphtml/world/europe/russian-navy-launches-barrage-of-cruise-missiles-in-drills/2017/09/19/3456d2c8-9d53-11e7-b2a7-bc70b6f98089_story.html

Does anyone object an extra check for `(element.tagName=='AMP-STICKY-AD')` before trying to offset `element.position.top`?

**Comment by jridgewell** [comment]
It needs to be offset in iOS.

Strangely, the measurements line up for me. What browser?

**Comment by zhouyx** [comment]
I am able to reproduce in Chrome emulator Android. But for `<amp-sticky-ad>` all user care is that it align to the bottom of a page, why would its top needs to be offset?

**Comment by cramforce** [comment]
I think you might chase a red-herring and there is no problem.

The `amp-sticky-ad` has `bottom:0!important`, so none of the other calculations matter (but lets investigate why we set top when the original position did not have top set).

**Comment by zhouyx** [comment]
@cramforce. But setting its `top` position, element height value can be affected. For example I found clientRect to be `{left: 0, right:350px, top:732px, bottom:732px}`. Element height was measured to be 0, which was the root cause to ad not rendering.

**Comment by cramforce** [comment]
Yeah, that is bad. I couldn't repo. There might be a bug. Adding top is probably because the "cannot distinguish from auto" bug in Chrome that @dvoytenko was chasing.

**Comment by dvoytenko** [comment]
Fixed layer should never touch `amp-sticky-ad`'s top position. Why would it offset it?

**Comment by jridgewell** [comment]
It was part of my fixed position testing. Something about fixed-bottoms needed the top offset, I'm looking into my manual test cases now.

**Comment by zhouyx** [comment]
I found fixed-layer add attribute `style="top: calc(XXXpx);` to `<amp-sticky-ad> `
![image](https://user-images.githubusercontent.com/5419904/30619418-258ba984-9d54-11e7-933f-e0c1a0c167eb.png)

Seems to come from this line https://github.com/ampproject/amphtml/blob/master/src/service/fixed-layer.js#L566

**Comment by zhouyx** [comment]
A first attempt to fix the issue: #11342. Let me know if there's any concern.

**Comment by jridgewell** [comment]
Tracked it down to the `bottom: 0px !important` (specifically, the `!important`). This is breaking the "auto top" (as in, explicitly `top: auto`, or only bottom-fixed) detection code.

When we detect that an element is auto top, we don't set the top value on it. But because the bottom is forced to be 0px in stylesheet, the auto detection broke, and we thought it _was_ a top-fixed.

**Comment by dvoytenko** [comment]
Did you try `style.bottom = auto !important`? Normally we don't allow b/c it could lead to messy overrides, but this case is very specific and we set values here very temporarily.

**Comment by jridgewell** [comment]
Confirmed fixed in latest production.

**Comment by zhouyx** [comment]
🎉
