### ISSUE TITLE
amp-animation broken in AMP shadow since it is required to be child of `<body>`

### ISSUE THREAD

**Issue by p2er** [ampproject/amphtml#11350]
## What's the issue?

If a valid AMP page with amp-animation is used as AMP shadow document an error will occur:
`amp-animation is only allowed as a direct child of <body> element. This restriction will be removed soon.`

And:
```
log.js:319 Uncaught (in promise) Error: failed to build: amp-animation#4: amp-animation is only allowed as a direct child of <body> element. This restriction will be removed soon. _reported_
    at xa.f.assert (log.js:319)
    at Vb.push.f.t.buildCallback (amp-animation.js:79)
    at custom-element.js:751
    at Promise (<anonymous>)
    at HTMLElement.Sg.b.build (custom-element.js:750)
    at Hg.f.build (resource.js:316)
    at Vi (resources-impl.js:585)
    at Ui (resources-impl.js:527)
    at yi.f.upgraded (resources-impl.js:646)
    at HTMLElement.Sg.b.Pc (custom-element.js:688)
```

This will result in missing animations in the embedded AMP page. Very sad, since amp-position-observer animations might require elements to be initially hidden for animations like fade-in. 

## How do we reproduce the issue?

1. Open: https://p2er.github.io/amp-articleslider/ampshadow-position-observer.html
2. Scroll down
3. Image does not fade in 

## What browsers are affected?

Tested with Chrome. Potentially all browsers.

## Which AMP version is affected?

Powered by AMP ⚡ HTML shadows – Version 1505341213754

**Comment by aghassemi** [comment]
closing in favour of https://github.com/ampproject/amphtml/issues/11522. Fix in https://github.com/ampproject/amphtml/pull/11523
