### ISSUE TITLE
[FR] amp-accordion 'collapse others' option

### ISSUE THREAD

**Issue by AndrewKGuan** [ampproject/amphtml#11359]
Need to be able to trigger collapsing of other expanded menu items when expanding a new item in the accordion.  For example, if the accordion contains items [A (expanded), B (collapsed), C (collapsed)],  when B is clicked on, the accordion's new state should be [A (collapsed), B (expanded), C (collapsed)].  Also if C is clicked, the new state should be [A (collapsed), B (collapsed), C (expanded)]

This is very important to improve UX by preventing any long menus from spilling over multiple screens when explored on.

Ideally, an additional flag such as "amp-accordion collapse-others" should help.

**Comment by camelburrito** [comment]
CC @ericlindley-g

**Comment by cnabar** [comment]
Other partners are requesting for smoother animation for expand collapse. Checking if any update on this one

**Comment by ericlindley-g** [comment]
Thanks @cnabar — no update yet, but will take the request into account for prioritization. Let us know if any developers out there would be interested in contributing either feature directly!

**Comment by nainar** [comment]
@camelburrito - is it ok if I take this on?

**Comment by camelburrito** [comment]
sure go ahead !
