### ISSUE TITLE
amp-ima-video: Support extra video analytics params

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#11356]
Currently `amp-ima-video` has [partial support](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-video-analytics.md#common-variables) for `video-analytics` to get full-support, it needs to implement the following optional parts of the `video-interface`: (anything else @cvializ?)

- [ ] `getPlayedRanges`
- [ ] `getDuration`
- [ ] `getCurrentTime`

/to @shawnbuso 
/cc @jasti

**Comment by shawnbuso** [comment]
For duration and currentTime can we just return those values as they pertain to the content video? The video and ads are separate streams, so if you e.g. have a 10 second ad at the 30 second mark you'd see the currentTime increase for the first 30 seconds, then we'd just report 30 over and over again for 10 seconds, then it would go back to increasing once the content resumed.

**Comment by jasti** [comment]
Yes, I think the expectation for analytics here is just for content. So the behavior makes sense.

**Comment by shawnbuso** [comment]
OK cool, and for getPlayedRanges do I just need to track what the user has and has not watched?

**Comment by aghassemi** [comment]
For `getPlayedRanges`, browser already tracks and exposes it under the `played` property on the html5 video element, just needs simple adapting: See https://github.com/ampproject/amphtml/blob/master/extensions/amp-video/0.1/amp-video.js#L370
