### ISSUE TITLE
Throw error when using npm to install

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#11364]
To prevent our `package.json` from getting out of sync with our `yarn.lock`.

Part of the `preinstall` script should be to check that the user is using yarn to install, not npm.

**Comment by choumx** [comment]
We already have [this presubmit check](https://github.com/ampproject/amphtml/blob/d66ccb38a2a1f09506dade9806103a07d11ffd47/build-system/pr-check.js#L386). Insufficient?

**Comment by rsimha-amp** [comment]
That check will kick in only when someone uploads a PR that updates `package.json` and not `yarn.lock`. It doesn't ensure that the user actually used `yarn` to install dependencies in the first place.

Something like https://github.com/AndersDJohnson/use-yarn and https://github.com/AndersDJohnson/danger-yarn-lock might be useful in enforcing `yarn` at the CLI level.

**Comment by jridgewell** [comment]
Yes, because we lose the dependency version guarantees after cloning the project and installing.

**Comment by choumx** [comment]
True, but that's a different issue than described in OP. 😛

**Comment by rsimha-amp** [comment]
Original presubmit check on Travis has been updated to run `yarn check --integrity`, and running `npm install` during local development will now throw an error and instruct you to run `yarn`.
