### ISSUE TITLE
Add "validate fragment" API to validator

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#1137]
We need a "validate fragment" API. Or, ideally, it'd be even nicer if we had a separate entry point binary with only this API - this way we should be able to DCE unrelated stuff.

**Comment by Gregable** [comment]
DCE?

**Comment by dvoytenko** [comment]
Dead-code-elimination. comes for free with Closure compiler.

**Comment by adelinamart** [comment]
What's the status here?

**Comment by dvoytenko** [comment]
This is, for now, connected to the a4a validation. The question is whether we can do this kind of validation cheaply on the client side.

@Gregable @powdercloud Did we get to run webworker experiments and such on this?

**Comment by dvoytenko** [comment]
Closing as a duplicate of #1156.

**Comment by powdercloud** [comment]
@dvoytenko Yes I am still working on making client side validation cheaper. There's some progress for sure, but also there's still room; I'm trying to make it so the validator instantiates fewer objects.

**Comment by adelinamart** [comment]
@powdercloud do you have a different issue opened for this/

**Comment by powdercloud** [comment]
@adelinamart not at the moment. Since it's mostly me working on it at the moment I figured I can get away with it? :-)

**Comment by adelinamart** [comment]
@powdercloud  :) Let's have an open issues for it so we can track the work you are doing. Thanks

**Comment by powdercloud** [comment]
@adelinamart https://github.com/ampproject/amphtml/issues/7420 OK :-)
