### ISSUE TITLE
Whitelist Material Design Icons CDN

### ISSUE THREAD

**Issue by iplanwebsites** [ampproject/amphtml#11376]
It's not currently possible to include these popular material design icons. 
These are integrated into some CSS framework like Bulma - which is a neat JS-less framework that fits AMP ideology pretty well.

 Project info: https://materialdesignicons.com/
 CSS: //cdn.materialdesignicons.com/2.0.46/css/materialdesignicons.min.css

**Comment by aghassemi** [comment]
/to @cramforce @ericlindley-g for decision. 
Seems similar to FontAwesome that we allow, except it is ~3x the size (85k vs 30k)

**Comment by cramforce** [comment]
LGTM

**Comment by jridgewell** [comment]
This is just a validator change, right?

**Comment by honeybadgerdontcare** [comment]
@jridgewell I believe it will require a CSP update as well.

**Comment by cramforce** [comment]
Yep. @camelburrito did this recently for typekit.

**Comment by honeybadgerdontcare** [comment]
While this is in github, it will take 2-3 weeks for it to be in production for the validator.
