### ISSUE TITLE
amp-form in amp-mustache won't render

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#11388]
To whom it may concern:

I use tag - "amp-list" to fetch some dynamic data and try to render them by amp-mustache.
It's kind of trick which form tag won't render if I put form tag inside the template.
(try to do some xhr stuff)

I thought it should be render just like amp-img in template.

I wonder it is an issue or it was prohibited to put form in template.

Have a nice day.

Paul

**Comment by cvializ** [comment]
Duplicate of #9768. Hoping to get to that one soon : )
