### ISSUE TITLE
Feature: Allowing any source-origin access to static config for AMP-Analytics

### ISSUE THREAD

**Issue by lintal** [ampproject/amphtml#11389]
# What's the issue?
We are hitting an issue for our use-case where the [AMP CORS requests requirements](https://www.ampproject.org/docs/reference/components/amp-analytics#loading-remote-configuration) block access to a static JSON config file hosted for AMP-Analytics.
The information contained in this file is not private in any way and could easily be determined/inferred through other means = there is no reason or benefit to us why access to this information should be restricted just for AMP-Analytics.

We would like to find a way to lift/bypass/disable the requirement for the "AMP-Access-Control-Allow-Source-Origin" HTTP Header for this type of scenario.

## Use-case:
We syndicate content through many different partner websites (domains) and, as part of the contractual agreement we have with them, they agree to implement analytics tracking code reporting back to us.

## Intent
We would like to use AMP-Analytics with a custom vendor configuration defined, so the tracking destination / metrics etc can be adjusted centrally.
Ideally, the JSON configuration content will be static and hosted in an AWS S3 bucket.

For example, on a partner website: http://my-partner.com/path/to/amp/page
the partner will implement the following code:

`<amp-analytics config="https://our-domain.com/path/to/analytics-config.json">
    ...
</amp-analytics>`

We want to keep this configuration centralised as we will be switching Analytics provider in the near future.
Using a configuration hosted separately, this can be updated without updating every website connected to it.

## Issue
We cannot set the "AMP-Access-Control-Allow-Source-Origin" required by the [AMP-CORS-Requests spec](https://github.com/ampproject/amphtml/blob/master/spec/amp-cors-requests.md) without compute resource which incurs additional cost.
As the source origin is external to us, AMP currently will block the request to the config file without this header being set.

----
Any input on this matter will be appreciated and/or any ideas regarding a solution to this within AMP.
If further information is required, please let me know.

Thanks & BR
Alex

**Comment by cramforce** [comment]
Seems reasonable for config requests without credentials.

**Comment by lintal** [comment]
Hi All

Given this ticket was dropped out of the October H2 sprint when it ended, is there any way to know when this can get picked back up?
How can we assist to progress this ticket forward and/or to include this in another sprint?
Do tickets not roll-forward into the next sprint if they aren't completed?

Thanks
Alex

**Comment by jridgewell** [comment]
We reprioritize every sprint, so it might not be added to the new spring. If you're interested in working on this yourself, it should be a simple change.

**Comment by cramforce** [comment]
CORS is required to be able to read the response.
lets remove the AMP CORS requirement when no credential access is requested.

**Comment by lannka** [comment]
@cramforce I have 2 related questions:
- why browser enforce CORS rules when request does not contain credential (need to understand if AMP CORS needs to respect that).
- after the CURLS launch, is AMP CORS still needed?

**Comment by cramforce** [comment]
CORS is needed without credentials because reading content on other origins isn't allowed on the web by default.

We still need it after CURLS launch due to an oversight of missing the schema in the origin. We could get rid of it only for HTTPS source origin docs.

**Comment by lannka** [comment]
> We still need it after CURLS launch due to an oversight of missing the schema in the origin. We could get rid of it only for HTTPS source origin docs.

You meant for pages on origins with different schema:
```
https://amp.example.com/
http://amp.example.com/
```

Will have the same `origin` on cache server:
```
https://amp-example-com.cdn.ampproject.org/
```

hence pub server will not know if the page is from http or https.

**Comment by cramforce** [comment]
Right. @dvoytenko and I discussed that we could move towards "It was HTTPS unless we tell you otherwise"

**Comment by lannka** [comment]
> ... because reading content on other origins isn't allowed on the web by default.

Given that, I think we should still have AMPCORS when request has no credential. We can disable AMPCORS for amp-analytics explicitly though, like what Yuxuan did in her PR: #12787.

> Right. @dvoytenko and I discussed that we could move towards "It was HTTPS unless we tell you otherwise"

Right, that can simplify CORS integrations for pubs that treat the 2 schema the same.
