### ISSUE TITLE
Page offline

### ISSUE THREAD

**Issue by chimura** [ampproject/amphtml#11384]
The following is offline:
https://www.ampproject.org/pt_brdocs/guides/author-develop/responsive/control_layout

**Comment by bpaduch** [comment]
I'm not sure where you discovered that link, but the link is incorrect and those docs are online at https://www.ampproject.org/pt_br/docs/guides/responsive/control_layout.

**Comment by chimura** [comment]
I discovered that link through this page: https://www.ampproject.org/pt_br/docs/tutorials/create/presentation_layout

When I click "Como controlar o layout" it leads to a 404. But thanks for the correct link.
