### ISSUE TITLE
extensions/amp-auto-ads/0.1/test/test-placement.js fails when run under chai 4

### ISSUE THREAD

**Issue by rsimha-amp** [ampproject/amphtml#11399]
Chai 4 isn't checked in yet, but I'm going to have to disable part of this test to let the rest continue to run after the chai upgrade.
```
  placement
     
      placeAd
        ● should place an ad with i-amphtml-layout-awaiting-size class
          Chrome 61.0.3163 (Linux 0.0.0)
        AssertionError: expected false to be true
            at /tmp/extensions/amp-auto-ads/0.1/test/test-placement.js:336:57 <- /tmp/bc650a4f057f6efc0c69ee3a1b8ab3ea.browserify:1375:85
            at <anonymous>
```
See #11390

**Comment by rsimha-amp** [comment]
@dvoytenko, assigning to you based on the `git log` of this file. Please reassign if needed.

**Comment by tlong2** [comment]
@rsimha-amp do you have any indication if this was flakey before the switch to chai 4? If not. any ideas why chai 4 would cause it to become flakey?

**Comment by rsimha-amp** [comment]
@tlong2 Some tests used to silently pass in spite of errors due to invalid assertions or the failure to clean up the global sandbox. With chai 4, we have more robust error detection and reporting.

I had to be aggressive with disabling failing tests while upgrading. If you see that this test now passes with no changes, feel free to re-enable.

**Comment by tlong2** [comment]
OK thanks. Will take a look.
