### ISSUE TITLE
Change transport for top100-analytics

### ISSUE THREAD

**Issue by arealit** [ampproject/amphtml#11406]

**Comment by aghassemi** [comment]
@arealit could you please provide more details

**Comment by arealit** [comment]
@aghassemi changed transport settings for top100 counter in extensions/amp-analytics/0.1/vendors.js: set all types except image to false. All this changes are in linked PR.

What other details do you want?

**Comment by aghassemi** [comment]
@arealit I missed the linked PR you were sending to fix it. I assumed you were just raising a bug in AMP.
