### ISSUE TITLE
PHP Notice: Undefined Variable

### ISSUE THREAD

**Issue by divemasterza** [ampproject/amphtml#11432]
Log records a PHP Notice:  
`Undefined variable: output in ../wp-content/plugins/accelerated-mobile-pages/pagebuilder/modules/blurb.php on line 2`

Environment:
Apache 2.4.27 + PHP 7.0.23

Steps to reproduce:
Always present

Plugin version 0.9.62

**Comment by camelburrito** [comment]
@amedina - do you have any clue of what this is ?

**Comment by jridgewell** [comment]
This is a Wordpress bug.
