### ISSUE TITLE
amp-form and amp-bind process order

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#11454]
Hi:

I try to use amp-bind in tag - "input" to dynamic modify its value.

Please check the following code

```
<form id="myForm" method="post" action-xhr="action.php" target="_top">
    <input type="text" name="act" value="normal" [value]="data.value"  />
    <a on="tap:AMP.setState({data:{value:'modify'}}),myForm.submit">submit</a>
</form
```
I expect the request will send **input[value="modify"]** when I press the tag - "a", but looks like the submit action run faster than data binding (the input's value is still **normal**).

I wonder is it an issue or it should be prohibited to do this kind data binding when submit.

Have a nice day.

Paul

**Comment by choumx** [comment]
Hi Paul, thanks for reporting this. This should work -- I'll investigate soon.

**Comment by meistudioli** [comment]
Hello, William:

I wonder how long will this release to prod ?
Or do i need to change version or anything to make it work ?

Paul

**Comment by choumx** [comment]
The change is in dev channel right now and should be in prod next Tuesday.

**Comment by meistudioli** [comment]
Cool, thx a lot.
