### ISSUE TITLE
Fixed positioned elements have their transitions overwritten on mobile

### ISSUE THREAD

**Issue by acusti** [ampproject/amphtml#11453]
## What's the issue?

When an element is given `position: fixed`, on mobile Safari (and maybe other mobile browsers / platforms?), any transitions on that element get overwritten by `transition: none !important`.

## How do we reproduce the issue?

I threw together a quick demo with a `<button>` element and a simple `translate-y` transition on hover. Visit the demo on a mobile device and tap the blue square to trigger the transition (you can tap the Reset button to make the browser stop applying the `:hover` styles).

Here’s the demo with AMP (no transition):
https://codepen.io/acusti/debug/VMPrGb

Here’s the demo without AMP (transitions):
https://codepen.io/acusti/debug/ZXLOJd

## What browsers are affected?

At least mobile Safari, possible other mobile browsers.

## Which AMP version is affected?

This is a recent regression (last few days); we have existing pages with fixed elements with transitions that were transitioning on mobile previously. I confirmed it while using version 1506041909031.

**Comment by dvoytenko** [comment]
@jridgewell I'm setting this to P1 b/c it's reported as a regression.

**Comment by jridgewell** [comment]
Filed https://bugs.webkit.org/show_bug.cgi?id=177684. Fix incoming.
