### ISSUE TITLE
Facing issue with AMP Carousel

### ISSUE THREAD

**Issue by tlstechtesting** [ampproject/amphtml#11465]
We are facing issue with the Carousel. Works correctly when used separately, but creates some issue while used with other AMP scripts. Image is not changing on clicking the forward navigation, it only works on double clicking the navigation. The same issue is with autoplay.

**Comment by camelburrito** [comment]
@tlstechtesting - Hey Thanks for reaching out to us!. Can you provide us elaborate steps and a URL to help us understand what is going on.

**Comment by tlstechtesting** [comment]
Hi, I have located the issue. The issue is with the RTL direction as we are using this in Hebrew site. I have fixed it now.
