### ISSUE TITLE
amp-img add some attribute in Google AMP Cache

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#11470]
Hi:

I try to use amp-bind in *amp-img* to dynamic change its source.

```
<amp-img
    layout="responsive"
    width="375"
    height="375"
    src="img/yau/main.jpg"
    [src]="status.lightbox">
</amp-img>

<a on="tap:AMP.setStatus({status:{lightbox:'img/yau/new-main.jpg'}})">
    change image source
</a>
```

It really works well until I check the Google AMP Cache.
The **amp-img** doesn't change its source when I click **<a>** in Google AMP Cache page.

I found the Cache server add some attribute **srcset** when it cache the page, such as

```
<amp-img
    [src]=status.lightbox
    height=375
    layout=responsive
    src=/i/s/blog.lalacube.com/mei/img/yau/main.jpg 
    srcset="/ii/w390/s/blog.lalacube.com/mei/img/yau/main.jpg 390w, /ii/w820/s/blog.lalacube.com/mei/img/yau/main.jpg 820w, /ii/w1200/s/blog.lalacube.com/mei/img/yau/main.jpg 1200w"
    width=375>
</amp-img>
```

The data binding is useless when  the attribute **srcset** occured .

I wonder is it an issue or should I add [srcset] data binding in my amp-img.

Have a nice day.

Paul

**Comment by choumx** [comment]
Thanks for reporting this.
