### ISSUE TITLE
amp-img: detect aspect ratio mismatch in JS and apply object-fit:contain (unless author has specified a different object-fit)

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#11476]
Distorted images have been an issue in AMP, they are normally due to wrongly specified width/height attributes that do not match the natural aspect ratio of the image.

We did some work back in 2016 that handled a big chunk of these issues in `amp-carousel` if they got the aspect ratio wrong.
See https://github.com/ampproject/amphtml/issues/4811 and https://github.com/ampproject/amphtml/pull/4839 

However these efforts only handle the issues in carousel and only in certain cases (e.g. if `amp-img` is a the slide itself and not nested in another slide).

One potential fix for this that expands the fix beyond carousel and handles more error cases includes:
1- Detect natural ratio (doable cheaply in JS after images loads)
2- Compare with specified ratio
3- If mismatch AND author has not defined a `object-fit` other than default, auto-apply `object-fit: contain`. 

Brainstorming is needed to make sure this is backward compatible before implementation.

/cc @ericlindley-g @dvoytenko @camelburrito

**Comment by dvoytenko** [comment]
I wonder if we can find a lower-priority way to always set `object-fit: contain` if it's not already overwritten? If not, we can do `getComputedStyle()['object-fit'] != initial`

**Comment by aghassemi** [comment]
similar suggestion came up here (from a year ago): https://github.com/ampproject/amphtml/issues/4988#issue-176821182 with concern of being potentially a breaking change. We can revisit and write down places this might be a breaking change and see if that's acceptable.

**Comment by dvoytenko** [comment]
I think we could try this out under an experiment and see. For ease to resolve this, we could also create an additional attribute `<amp-img object-fit="...">` to allow anyone to restore the status-quo quickly.
