### ISSUE TITLE
AMP-Social-Share Webview with replace 

### ISSUE THREAD

**Issue by gui-poa** [ampproject/amphtml#11473]
## What's the issue?
The new API (web share) is not working with amp-social-share (data-mode=replace) when is loaded with webview.

e.g: Google News Stand

## How do we reproduce the issue?

Load a page that is using amp-social-share with data-mode=replace into a webview. As I can't debug in this scenario is difficult to help.

## What browsers are affected?

Chrome Mobile 61+ (webview Google News Stand)

## Which AMP version is affected?

New
1506372648650

**Comment by aghassemi** [comment]
@bellini Does it render but not do anything when clicked?

**Comment by aghassemi** [comment]
related: https://bugs.chromium.org/p/chromium/issues/detail?id=765923

**Comment by bellini** [comment]
@aghassemi Yes. It renders but there is no action.

**Comment by aghassemi** [comment]
Blocked by https://bugs.chromium.org/p/chromium/issues/detail?id=765923 and based on discussions on that Chrome bug thread there doesn't seem to be any decent alternative to detecting Web Share until that bug is fixed.

**Comment by gui-poa** [comment]
As we have a lof of people coming from Google News Stand, we are going to remove this feature on the AMP pages. Web Share API is working fine on non-amp docs. Thanks for your attention.

**Comment by gui-poa** [comment]
Actually this is a serious bug in the web share api & webview. It doesn`t matter if is AMP or non-amp doc. It doesnt work. Thanks for your attention.
