### ISSUE TITLE
amp-img: Make "caption" UX of lightbox 2.0 available on individual `amp-img` as well

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#11477]
Essentially lightbox 2.0 has very nice "caption" UX, @camelburrito suggested we bring the same UX to a single `amp-img` as well. 

I really like this as it bring consistent caption UX to images regardless of where they are (single image, inside an inline carousel, inside a lightbox carousel).

/cc @ericlindley-g @spacedino

**Comment by ericlindley-g** [comment]
Intriguing! What of the mechanic do you propose would carry over? (tap to toggle hide/show? scrolling inside of image itself?)

**Comment by aghassemi** [comment]
Needs more thinking but at least for images inside in-line carousel, I think it makes sense to have the exact same UX.

**Comment by ericlindley-g** [comment]
I think I agree — some of the UX has to do with different scrims and behaviors on scroll (some UI anchoring to the top of the screen in lightbox while the caption scrolls under it), so I think it would be helpful to be really precise about the behavior here.

**Comment by wassgha** [comment]
Solving this would unblock #10134 (essentially, where to put more advance `amp-img` features without cluttering the basic `amp-img` code)

**Comment by aghassemi** [comment]
`amp-inline-gallery` will have caption support.
