### ISSUE TITLE
amp-shadow converts custom-template to custom-element when moving scripts

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#11492]
The standalone document includes `amp-mustache` correctly, using the `custom-template` attribute, but when the document is used inside a shadow root, the framework moves the script element using `custom-element` instead. This could be a bug.

[standalone document](https://www.vializ.me/amp/projects.amp.html)
<img width="696" alt="screen shot 2017-09-29 at 9 47 09 am" src="https://user-images.githubusercontent.com/2363700/31026422-3f6d810c-a4fb-11e7-9e86-c0cfbac1acab.png">

[shadow document](https://www.vializ.me/projects) 
<img width="696" alt="screen shot 2017-09-29 at 9 46 53 am" src="https://user-images.githubusercontent.com/2363700/31026420-3c3566a8-a4fb-11e7-9f12-ab03737aa7d6.png">

/cc @dvoytenko

**Comment by dvoytenko** [comment]
Definitely undesirable. Let's fix.

**Comment by sparhami** [comment]
This appears to have been fixed with #13163
