### ISSUE TITLE
<amp-analytics> console errors from Fast Fetch

### ISSUE THREAD

**Issue by taymonbeal** [ampproject/amphtml#11499]
The error message is `"on" and "request" attributes are required for data to be collected.`. It comes from the `<amp-analytics>` element that's built by Fast Fetch when the ad server sends an `X-Ampanalytics` header. Configs like this that we've seen have been missing the `request` field for some triggers.

**Comment by glevitzky** [comment]
Is there a simple repro case I can look at?

**Comment by omeryounus** [comment]
it is also showing for video amp analytics....
 "triggers": {
     "myVideoPlay": {
    "on": "video-play",
    "request": "event",
    "selector": "#myVideo"
  },
	"videoSpec": {
}
