### ISSUE TITLE
layout attribute no longer validates

### ISSUE THREAD

**Issue by fsencinas** [ampproject/amphtml#1151]
The layout attribute no longer validates on major media tags (img, video...)
Is this attribute deprecated?

**Comment by powdercloud** [comment]
Thank you for saying hi! No, the layout attribute is not deprecated. However, we updated the checker so it catches more violations of the layouts spec, e.g., previously we (accidentally allowed) amp-img without width and height, but now it'll say something along the lines of "implied layout CONTAINER invalid".

Can you please provide some example which isn't working for you?

**Comment by dvoytenko** [comment]
@fsencinas yes, please send the examples. The errors we previously only reported as warnings on the client-side, are now reported as errors in the validator. Let's see some examples of your errors.

**Comment by dvoytenko** [comment]
@fsencinas thanks for the report. I think I found the issue - there's a regression in some of the cases. I will fix it in a bit.

**Comment by dvoytenko** [comment]
Should be fixed in about an hour. Apologies for confusion.

**Comment by fsencinas** [comment]
OK, lo of thanks @dvoytenko.
Now seems to be fixed.

Sorry for my late reply.
