### ISSUE TITLE
event.valueAsNumber returns null for select

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#11513]
Accordion to the [docs](https://github.com/ampproject/amphtml/blob/master/spec/amp-actions-and-events.md#input-elements) `select` change events should support `event.valueAsNumber`, but it returns null.

```
<select on="change:AMP.setState({product: {quantity: event.valueAsNumber}})"> => quantity is null
```

 [Codepen](https://codepen.io/powlo/pen/PJjGXa?editors=1000) to reproduce and see also [this thread](https://stackoverflow.com/questions/46488110/amp-how-to-get-event-valueasnumber-for-select) on SO.

**Comment by choumx** [comment]
Apologies, the docs are incorrect. `valueAsNumber` is supported on `HTMLInputElement`, not `HTMLSelectElement`. We can extend it to include `<select>` elements too (and diverge from W3C spec) or update the docs to avoid confusion.
