### ISSUE TITLE
Update amp-story documentation

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#11530]
We should update [`amp-story.md`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/amp-story.md) to conform to the format that we normally use for READMEs (e.g. [`amp-carousel.md`](https://www.ampproject.org/docs/reference/components/amp-carousel))

**Comment by bpaduch** [comment]
I'll take care of this as I'm updating and reforming the documentation so it renders correctly in ampproject.org.
