### ISSUE TITLE
Remove usages of `innerHTML` where possible

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#11545]
We're currently using `innerHTML` in some places in the [amp-story extension](https://github.com/ampproject/amphtml/tree/master/extensions/amp-story); we should instead use `createElement`/`appendChild` to mitigate future risks where we move from using static templates to dynamic ones including publisher-specified data.

- [x] SVG icons (#11610)
- [ ] `extensions/amp-story/0.1/amp-story-page.js: loadingScreen./*OK*/innerHTML = LOADING_SCREEN_CONTENTS_TEMPLATE;`
- [ ] `extensions/amp-story/0.1/system-layer.js: this.root_./*OK*/innerHTML = TEMPLATE;`

**Comment by dvoytenko** [comment]
A big group of these are `<svg>` icons. We should just try to move them all via CSS.
