### ISSUE TITLE
FR: amp-iframe allow="geolocation"

### ISSUE THREAD

**Issue by ruborg** [ampproject/amphtml#11541]
## What's the issue?

Currently it's possible to use geolocation within an `amp-iframe`. However, this will soon stop working on cross-origin iframes (i.e. every `amp-iframe`) as per: https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes

This page outlines the solution for regular iframes: 
`<iframe src="https://example.com" allow="geolocation"> </iframe>`

It seems like this would be an easy fix for `amp-iframe`

**Feature request:** 
Support `allow="geolocation"` in `amp-iframe`

**Comment by cramforce** [comment]
Lets do this with allowed values `geolocation` and `payment`. We can add others as there is demand.

**Comment by ruborg** [comment]
Will `allow="payment"` offer same functionality as `allowpaymentrequest` attribute?

**Comment by cramforce** [comment]
@ruborg Yeah, it is indeed less important since `allowpaymentrequest` already exists (vs. the backward-incompatible changes).

**Comment by Gregable** [comment]
What would be the validator attributes?

`<amp-iframe allowgeolocation ...>`
and
`<amp-iframe allowpayment ...>`

?

**Comment by cramforce** [comment]
Just allow="geolocation". We should probably allow the 2 existing values we
allow into the new syntax allow="geolocation payment fullscreen"

**Comment by Gregable** [comment]
Will do. Do we also want to mark the old format attributes (`allowfullscreen`) as deprecated warnings in validation?

**Comment by cramforce** [comment]
For now only Chrome supports the new syntax. If anything we should probably warn if one version is missing.

**Comment by Gregable** [comment]
Doesn't the amp-iframe code manage the mapping? Should it not add the correct attributes to the underlying iframe?

**Comment by cramforce** [comment]
Interesting point. We could introduce a polyfill, yeah.

I'd like to let this super new spec settle a bit first though.

**Comment by Gregable** [comment]
Validator changes are live.
