### ISSUE TITLE
FR: analytics event trigger for amp-carousel item only when it's visible for the first time

### ISSUE THREAD

**Issue by micyeung** [ampproject/amphtml#11542]
## Issue
Right now, as a carousel loops through the items, an item will get repeatedly shown and repeatedly fired, which will count as multiple impressions in analytics.
https://github.com/ampproject/amphtml/blob/master/extensions/amp-carousel/amp-carousel-analytics.md

## Feature Request
Can we have an analytics event trigger for amp-carousel to fire only when an item is visible for the first time?

**Comment by jasti** [comment]
CC @rudygalfi

**Comment by zhang-90** [comment]
Although the business requirements for the first occurrence of elements in `amp-carousel` were temporarily implemented by using the` visible` event, but relative to the number of elements in `amp-carousel`, I had to The current expectation is that there is an event that supports `amp-carousel` for the first time, or the` visible` event supports the group selector at the same time to get the element in the group's `index`

**Comment by camelburrito** [comment]
the only events that get fired on repeated slide changes are `amp-carousel-change`, `amp-carousel-next`, `amp-carousel-prev`

**Comment by zhang-90** [comment]
I know, but what we need is that the elements in `amp-carousel` send the analysis data only at the first occurrence

**Comment by camelburrito** [comment]
@zhang-90 which events(names) are you referring to?

**Comment by zhang-90** [comment]
`amp-carousel-change`, `amp-carousel-next`, `amp-carousel-prev`Will continue to send analysis of data, so desperately selected the `visible` event

**Comment by jeffjose** [comment]
Closing in favor of #12298
