### ISSUE TITLE
Link manipulation (DOM-based)

### ISSUE THREAD

**Issue by Jun3P4rk** [ampproject/amphtml#11562]
## What's the issue?
I found some DOM-based link manipulation vulnerabilities on the amp-mustache-0.1.js
These vulnerabilities arise when a client-side script reads data from a controllable part of the DOM (the URL) and processes this data in an unsafe way. 

## How do we reproduce the issue?
https://cdn.ampproject.org/v0/amp-mustache-0.1.js
line: 53, 76, 1679, 1693

[amp-mustache-0.1.js: read from self.location and passed to the 'href' property of a DOM element]
line: 53 and 76
…
        function N(b) {
            var a;
            ka || (ka = self.document.createElement("a"), oa = self.UrlCache || (self.UrlCache = Object.create(null)));
            var c = oa[b];
            if (c) return c;
            var d = ka;
            d.href = b;
            d.protocol || (d.href = d.href);
            var f = {
                href: d.href,
                protocol: d.protocol,
                host: d.host,
                hostname: d.hostname,
                port: "0" == d.port ? "" : d.port,
                pathname: d.pathname,
                search: d.search,
                hash: d.hash,
                origin: null
            };
            "/" !== f.pathname[0] && (f.pathname = "/" + f.pathname);
            if ("http:" == f.protocol && 80 == f.port || "https:" == f.protocol && 443 == f.port) f.port = "", f.host = f.hostname;
            f.origin =
                d.origin && "null" != d.origin ? d.origin : "data:" != f.protocol && f.host ? f.protocol + "//" + f.host : f.href;
            var p = f,
                k = p;
            return a ? k : oa[b] = k
        }

        function qa(b) {
            "string" == typeof b && (b = N(b));
            return ja.test(b.origin)
        }
…

## Which AMP version is affected?
An attacker may be able to use the vulnerability to construct a URL that, if visited by another application user, will modify the target of links within the response. An attacker may be able to leverage this to perform various attacks like a redirecting to an arbitrary external URL to induce a phishing attack.

**Comment by aghassemi** [comment]
@Jun3P4rk this is report generated by a auditing tool? 

The code in question is our UrlParsing method. It uses `<a>` to do parsing but does not actually display the `<a>` tag and dismisses it after). 

If you can provide more details of what you like us to do with this issue, it would be appreciated.

**Comment by Jun3P4rk** [comment]
@aghassemi thanks for the response.
Actually, I couldn't make a payload for this issue. 
Just curious, Can it be ignored if it's not shown and dismiss even though the URL of links set dynamically?

**Comment by aghassemi** [comment]
@Jun3P4rk I don't know what tool generated this report. Could you provide more information on what tool generated this and what the purpose of it is?

**Comment by Jun3P4rk** [comment]
@aghassemi 
You really wonder what tool I used. :)
fyi, https://portswigger.net/knowledgebase/issues/details/00501001_linkmanipulationreflecteddombased

And this is the purpose of the security review for one of my company's web project with the amp.

**Comment by aghassemi** [comment]
I see. Yes you can ignore this warning from the tool, it is a false-positive.

**Comment by aghassemi** [comment]
Closing the issue, feel free to reopen if you still have concerns. Thanks.

**Comment by Jun3P4rk** [comment]
@aghassemi thanks for your help.
