### ISSUE TITLE
Images located on cdn.ampproject.org fail to load from requests by html pages located on cache.

### ISSUE THREAD

**Issue by medicalspanw** [ampproject/amphtml#11569]
## What's the issue?
HTML requests an image using <amp-img scr="URL" ....
When the HTML page is located on the AMP Cache, it successfully loads images located on the web host and FAILS to load images located on the AMP Cache. In contrast, the original page located on the web host successfully loads images located on either the the web host or the AMP Cache.

PROBLEM:
Pages located on AMP Cache fail to load images located on AMP Cache.

Briefly describe the bug/feature request.

## How do we reproduce the issue?
Please check out the following web page and its cache copy"
http://www.medicalspanw.com/index.html
https://www-medicalspanw-com.cdn.ampproject.org/c/www.medicalspanw.com/index.html

line 402 requests an image located at: http://www.medicalspanw.com/pictures/hero/EveningHero1600.jpg

(This image appears when requested by either location of index.html.)

line 413 requests an image located at:
https://www-medicalspanw-com.cdn.ampproject.org/i/www.medicalspanw.com/pictures/hero/ChinHero1600.jpg

(This image appears when requested by the web host version of index.html and fails to appear when requested by the cdn.ampproject.org version.)

Note that these images are part of a carousel that displays only when the screen is greater than 500 pixels wide.

Note that the images and pages were uploaded to cdn.ampproject using the following example linux shell command.
curl https://cdn.ampproject.org/update-ping/c/www.medicalspanw.com/index.html;
curl https://cdn.ampproject.org/update-ping/i/www.medicalspanw.com/pictures/hero/ChinHero1600.jpg;

wget https://www-medicalspanw-com.cdn.ampproject.org/i/www.medicalspanw.com/pictures/hero/ChinHero1600.jpg; downloads the page.

The browser command https://www-medicalspanw-com.cdn.ampproject.org/c/www.medicalspanw.com/index.html successfully loads the page.

## What browsers are affected?
unknow. Using chromium. This is probably not a browser related problem.

All browsers? Some specific browser? What device type?

## Which AMP version is affected?

    <script async src="https://cdn.ampproject.org/v0.js"></script>

Is this a new issue? Or was it always broken? Paste your AMP version. You can find it in the browser dev tools.

**Comment by aghassemi** [comment]
@medicalspanw on your origin, the images are pointing to a previously cached version of some images on `cdn.ampproject.org`. Please point them to your own hosted images. 

I am not sure if we want to support origin pointing to cached CDN resources. @honeybadgerdontcare ?

**Comment by honeybadgerdontcare** [comment]
Yes, that is correct. Origin should not be pointing at cached CDN resources.
