### ISSUE TITLE
The relative link property fails when made by calls from/to pages located on cdn.ampproject.org.

### ISSUE THREAD

**Issue by medicalspanw** [ampproject/amphtml#11573]
**Please only file bugs/feature requests for AMP here.**
The relative link property fails when made by calls from/to pages located on cdn.ampproject.org. 

Assume page source.html contains the following relative html link: <a href='destination.html'>.

If source.html is located at mylocaldirectory, the browser will process this relative link to open the page located at: file:///mylocaldirectory/destination.html.

If source.html is located as www.mydomain.com, the browser will process this relative line to open the page located at http://www.mydomain.com/destination.html.

Assume that http://www.mydomain.com/source.html and http://www.mydomain.com/destination.com are respectively uploaded to http://www-mydomain-com.cdn.ampproject.org/c/www.mydomain.com/source.html and http://www-mydomain-com.cdn.ampproject.orc/c/www.mydomain.com/destination.html. The browser will process the href="destination.html" by serving the page located at http://www.mydomain.com/destination.html, versus the page located at http://www-mydomain-com.cdn.ampproject.org/c/www.mydomain.com/destination.html.

There appears to be an ugly work around, which is to absolute references versus relative.

## What's the issue?

Briefly describe the bug/feature request.

## How do we reproduce the issue?

If this is a bug please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else.  Then provide step-by-step instructions for reproducing the issue:
The file located at http://www.medicalspanw.com/index.html has been uploaded to http://www-medicalspanw-com.cdn.ampproject.org/c/www.medicalspanw.com/index.html.

line 409 is an absolute link reference that pulls up the cdn.ampproject.org version of the requested page.
line 420 is a relative link. If this link is clicked from the cdn.ampproject.ofg version, the web host version is provided versus the cdn.ampproject.org version.

Note that these links are incorporated into a carousel and the carousel display just for screen widths wider that 500px.

If this is a feature request you can use this section to point to a prototype/mockup that will help us understand the request.

## What browsers are affected?
Chromium

All browsers? Some specific browser? What device type?

## Which AMP version is affected?
    <script async src="https://cdn.ampproject.org/v0.js"></script>
Is this a new issue? Or was it always broken? Paste your AMP version. You can find it in the browser dev tools.

**Comment by aghassemi** [comment]
similar to #11569 , nothing in the original AMP page should point to AMP CDN. Aside from images, there are other issues in that page that still point to AMP CDN which is not correct including:

`cdnAmpUrl` and `<a>` hrefs
