### ISSUE TITLE
SVG and element feFlood

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#11586]
#We have an `<svg>` that uses these statement:

`<feFlood result="flood" flood-color="#000" flood-opacity=".859"/>`
`<feFlood result="flood" flood-color="#0379C4" flood-opacity=".333"/>`

These statements are generated by Inkscape.

But the AMP validator reports: The tag 'feflood' is disallowed.

Can `feFlood` be whitelisted?

/jay gray

**Comment by honeybadgerdontcare** [comment]
@dvoytenko Dima, if you are OK with this?

**Comment by jaygray0919** [comment]
@dvoytenko @honeybadgerdontcare 

any concerns with whitelisting `<feFlood>`?

FYI, our SVG without `<feFlood>` works ok in Chrome but sucks in Mozilla.
Rhetorically - why are these two browsers soooo different?! - they are diverging - not converging.
The new FireFox (56) is breaking a lot of previously working stuff.
argh!

**Comment by honeybadgerdontcare** [comment]
@dvoytenko created #11609 if this is fine with you.

**Comment by dvoytenko** [comment]
SGTM

**Comment by honeybadgerdontcare** [comment]
It'll be live in prod in two weeks or so.

**Comment by jaygray0919** [comment]
TY; we'll deploy the SVG and then re-validate in 2 weeks.
