### ISSUE TITLE
amp-list unable to resize when inside element height changes

### ISSUE THREAD

**Issue by ukvaddi** [ampproject/amphtml#11604]
## What's the issue?

we have different pages on our website. Few pages might have banner/image on top of page and few doesn't have. we created a banner/image using <amp-list>(basically <amp-list> with <amp-img> inside it). It is working fine in the pages where we have banner/image, but we have an extra space in the pages where we do not have banner/image. It is because of <amp-list> height behavior. Our requirement is to hide the <amp-list> or occupy the space of <amp-list> by other elements in the web page when there is no banner/image present.

**Comment by aghassemi** [comment]
De-duping in favor of #10230.

**Comment by ukvaddi** [comment]
Binding will works on user action. But in our web site we should resize amp-list on the page load itself. Our case "src" of amp-list will never change, but we should resize based on json response. Do you have examples on this case?

**Comment by aghassemi** [comment]
@ukvaddi `amp-list` does resize on page load automatically **IF** it is not in or above the viewport. To prevent content shifting, AMP only resizes when doing so does not have negative side-effects or is a result of user-interaction. See https://www.ampproject.org/docs/reference/components/amp-list#specifying-an-overflow on how to handle cases where resize is rejected by AMP.

**Comment by ukvaddi** [comment]
Thanks. But the above example also indicates that the overflow can be handled on some user action(please correct me if I am wrong). our requirement is to resize the amp-list when there are no child elements present in amp-list. This should happen on page load. we are not dependent on any user action for this workflow.
