### ISSUE TITLE
Feature request - Firebase Authentication

### ISSUE THREAD

**Issue by eshwarenm** [ampproject/amphtml#11603]
Requesting a component or any solution to use Firebase-based authentication (including Google Login / FB Login etc.. ) more natively with AMP. 

Use cases include: using this authentication to call for restricted / subscribers only content.

**Comment by dvoytenko** [comment]
@eshwarenm Could you direct me to some links to docs for Firebase that are most relevant to this request? And/or can you elaborate in a bit more detail how you see this working?

**Comment by jc275** [comment]
Firebase auth REST API
https://firebase.google.com/docs/reference/rest/auth/

Currently requires POST rather than GET requests, so either amp-access authorization needs to add support for POST or firebase auth needs to add support for GET.

**Comment by dvoytenko** [comment]
@88kbbq, @jc275, @eshwarenm AMP only allows open-sourced code deployed as a 1p code, including dependencies.

However, RE: Firebase authentication. Typically AMP doesn't deal much with authentication, instead relying on some authorization mechanisms. Authentication is supported via a 1p login popups. This would appear to be fully supported by AMP now. Do you some additional features that would be helpful? E.g. possibly some credential propagation? Or anything else?

**Comment by dvoytenko** [comment]
Closing this due to some compatibility/clarity on this issue. Please chime back in with more details to re-open.
