### ISSUE TITLE
Allow amp-bind state to be triggered on amp-sidebar events

### ISSUE THREAD

**Issue by JamesIves** [ampproject/amphtml#11606]
## What's the issue?

I would like to be able to toggle `amp-bind` state whenever `amp-sidebar` events get fired. Something like this would be ideal:

```
<amp-sidebar
  on="sidebar.close:AMP.setState({currentState: 'close'})></amp-sidebar>
```

Currently I'm using `amp-bind` to toggle a set of classes on the sidebar component that keep my desktop and amp experiences the same. Right now I'm opening the amp-sidebar component with a button like so:

`<button on="tap:AMP.setState({currentState: 'open'}),sidebar.toggle">Open</button>`

The problem is that when the amp-sidebar component is opened the overlay allows for the user to click anywhere on the page outside of the sidebar to close the sidebar, therefore removing the classes that were initially obtained through the state cannot be toggled off. Allowing the user to set AMP state when the sidebar event is fired would solve this problem, otherwise I have to use a bunch of z-index properties to achieve the same effect which is not ideal. 

Another possible solution would be to allow tap events to be set on the `.i-amphtml-sidebar-mask` element/class.

**Comment by choumx** [comment]
Thanks for filing this issue. Related: #11606
