### ISSUE TITLE
amp-story: Experiment with fading over black (background)

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#11614]
Lets experiment with doing a super fast fade over the background (color). So mostly a fade over black. Just before calling request fullscreen and after we entered fullscreen, so that the screen would typically be just black when fullscreen is entered.

**Comment by prateekbh** [comment]
just to understand, everything quickly goes dark(black) before fullscreen is requested and when the screen is in fullscreen it is back to normal?

Like an overlay on screen going from opacity 0 to 1 to back to 0?

**Comment by newmuis** [comment]
That's what I understood from the original report.

This will be slightly tricky as it may cause us to always fade between pages, which I'm not sure was the original intention.  For example, on iOS Safari where requestFullscreen is a no-op, how will we tell when to do this and when not to do this?

**Comment by newmuis** [comment]
I'm not sure this is desirable anymore, without fullscreen behavior.

/cc @hongwei1990 any thoughts?

**Comment by newmuis** [comment]
Checked off-thread with @hongwei1990; we don't want this anymore, since we're not doing this fullscreen transition.
