### ISSUE TITLE
Make variable substitution accept whitespace after comma

### ISSUE THREAD

**Issue by jonkeller** [ampproject/amphtml#11616]
Make it accept:
SOME_FUNC(foo, bar) // with a space
Currently only accepts:
SOME_FUNC(foo,bar) // no space

Changes necessary in these two locations:
https://github.com/ampproject/amphtml/blob/master/src/service/url-replacements-impl.js#L915
https://github.com/ampproject/amphtml/blob/master/src/service/variable-source.js#L244

**Comment by calebcordry** [comment]
Hello Jon, we are potentially reworking this logic to do nested url filtering #2198. Something like `hash(lowercase(clientId(_ga)))`

If we are allowing this space, but not denoting string input with something like a quote it could be difficult to distinguish what is a syntax type space vs. an intended space input. Happy to hear your thoughts on this.

**Comment by jonkeller** [comment]
Sure, if there's a reason to go back to not allowing it, that is fine with
me. I just found it a minor annoyance when writing configs - I would
instinctively add a space as though I were calling a function in
JavaScript, etc. But your reason carries far more weight than that :)

Cc clawr since he has a documentation PR on the same.

**Comment by calebcordry** [comment]
Thanks for the input. I agree it does seem intuitive. My intention it to keep it if reasonable.
