### ISSUE TITLE
amp-bind: Don't write non-primitive attribute values

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#11629]
/to @choumx 

Steps to reproduce: 
1. Run the dev server
2. Open the amp-bind amp-list example: http://localhost:8000/examples/bind/list.amp.html
3. Click 'Show other fruit', which binds an array to the identifier `src`
4. Open the inspector and inspect the amp-list element
5. Its `src` attribute became `http://localhost:8000/examples/bind/[object%20Object],

The binding applies and renders correctly, but 404 and fetch errors will fill the console.

**Comment by choumx** [comment]
Thanks for reporting this. I couldn't repro the 404/fetch errors. Are you seeing XHRs after clicking the "Show other fruit" button?

Either way, we probably shouldn't update element attributes to non-primitives.

**Comment by cvializ** [comment]
You're welcome! It was making the request in the first form on this page for some reason, I didn't investigate very far. Maybe it has something to do with the mixed content error as well?

https://www.squareyards.com/micro/bhutani_alphathum_in_noida/index-amp.php

<img width="548" alt="screen shot 2017-10-10 at 1 26 12 pm" src="https://user-images.githubusercontent.com/2363700/31408824-a9840a40-adbe-11e7-9d75-b7727462dc9b.png">

**Comment by choumx** [comment]
Ahh, got it. It happens after you select a country and un-hides the amp-list (which fires the XHR on layout). Doesn't happen on subsequent country selections. Yea I'll fix this.

**Comment by choumx** [comment]
Related: #12837 and #12850.

**Comment by choumx** [comment]
Bumping to P1.
