### ISSUE TITLE
!important amp-story system styling

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#11645]
Many styles within the `amp-story` component are not intended to be overwritten, but can be accidentally overwritten depending on publisher styles.  We should `!important` all styles that are not intended to be overwritten.

**Comment by prateekbh** [comment]
cc: @alanorozco @newmuis @choumx

As far as i can tell, all in `amp-story.css` should be important right?

**Comment by newmuis** [comment]
Styles in both `amp-story.css` and `amp-story-desktop.css` are affected, but it's not *all* styles in those files.  Some of these styles are allowed to be overridden, so there will need to be some amount of care taken not to break any existing stories with this change.  But, I think we can take a careful look during review to ensure this.

**Comment by prateekbh** [comment]
how do i know which ones are allowed to be changed? is there a doc or design docs which tells what a user can change

**Comment by newmuis** [comment]
No :(

I just commented on #11832 with which ones are currently allowed to be changed, as well as a proposal for a practice that will let us determine which ones are allowed to be changed in the future.

**Comment by prateekbh** [comment]
@newmuis yes yes, the proposal sounds fantastic. It makes everything super clear and easy to understand for future enhancement as well. I'll make the necessary changes

**Comment by alanorozco** [comment]
This is not necessary as AMP validates `.i-amphtml-...` out of author styles.

Reopening as to revert later.

**Comment by newmuis** [comment]
It forbids using those selectors, but not styling those elements.  For example:

```
<div class="i-amphtml-example">This text is black</div>
```

Even if the runtime specifies `.i-amphtml-example { color: black; }`, the publisher can still override with by setting the `color` for `div`, or `body`, or....
