### ISSUE TITLE
Refactor amp-story system-layer to use CSS grid

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#11640]
In order to support different UIs, we'll need to move the system layer icons around without having re-parenting them.  Using a CSS grid implementation of the system layer will help this.

**Comment by prateekbh** [comment]
can you be a little more descriptive about the use case?
i see that there are `i-amphtml-story-ui-right` and `i-amphtml-story-ui-left`. But `i-amphtml-story-ui-left` never becomes visible. 

cc: @alanorozco @newmuis @choumx

**Comment by newmuis** [comment]
I think what I was thinking of was refactoring this to get rid of `i-amphtml-story-ui-right` and `i-amphtml-story-ui-left` entirely.  And also getting rid of the duplicate implementations of e.g. the fullscreen button.  For example, we could do:
![stamp system layers with css grid](https://user-images.githubusercontent.com/1651960/32058729-6860f13c-ba38-11e7-9fce-7353200a1b29.png)

Then, each of these elements can just be e.g. a flat list inside of the system layer DOM element.

**Comment by prateekbh** [comment]
couple of questions: 
a.) I don't see dev logo/button/share/3dots implemented in system-layer.js, are they yet to be implemented?

b.) why do i always get mobile view on desktop as well? do i need to do to enable desktop?
<img width="1431" alt="screen shot 2017-10-26 at 9 02 57 pm" src="https://user-images.githubusercontent.com/5960497/32062104-1f0d92ca-ba91-11e7-8254-d8482728158f.png">

**Comment by newmuis** [comment]
(a) Looks like this may have regressed; I'll file an issue to investigate, but the nice thing about the CSS grid implementation is that it should be easy to add things to this later.
(b) Yes, you'll need to enable the `amp-story-desktop` experiment.

**Comment by prateekbh** [comment]
okay m kinda using css-grid for first time so excuse my noob questions. But as far as I get it if I declare columns they'll be thr irrespective of content is present or not.

e.g. in your image, if fullscreen and 3 dots are not present Sharing button will still be present 80px away from right and will not auto shift to right end. right?
is that what we want?

sample image: 
<img width="416" alt="screen shot 2017-10-27 at 3 08 56 am" src="https://user-images.githubusercontent.com/5960497/32078325-3007bbf4-bac4-11e7-8552-76bca8359ddf.png">

**Comment by newmuis** [comment]
Good point.  We can make them larger cells (similar to the `i-amphtml-story-ui-left` and `i-amphtml-story-ui-right` that we already have) and put multiple icons in the same cell.  Then use CSS to define how the icons flow within the cell.

**Comment by prateekbh** [comment]
but wouldn't the problem of reparenting in case of desktop/mobile still exist?

**Comment by newmuis** [comment]
Yes, but it's entirely handled in CSS, by simply overriding the `grid-area` attribute.  The simplest way to imagine it (in my head, anyway) is having "trays" of icons like we have in the existing implementation.

Say mobile has `left` and `right`; then desktop could have `top-left`, `top-center`, `top-right`, `bottom-left`, `bottom-center`, `bottom-right`.  We already have separate CSS for our two existing breakpoints, and they could define these grids accordingly.  Then, we simply set the `grid-area` on each of the elements, e.g.

```
.fullscreen-btn {
  grid-area: right;
}

[desktop] .fullscreen-btn {
  grid-area: bottom-right;
}
```

Especially if we decide to add more breakpoints (e.g. tablet, or something really large like for Chromecasting to TVs), this should be much more flexible.

**Comment by prateekbh** [comment]
oh i tried this with the assumption that multiple icons can be put in same tray using same `grid-area` values but apparently that's not how it works. All the icons sharing same grid-area stack on top of each other.

Thats what you were suggesting right? Or did I mis understood?

**Comment by newmuis** [comment]
You understood correctly, but I was just wrong about how multiple items in the same `grid-area` works 😞 

I don't have a quick fix off the top of my head; maybe we can deprioritize this for now since it's internal-facing only

**Comment by newmuis** [comment]
I think we have since determined that this is both not possible and not a good idea :smile:  Thanks for looking into it Prateek!
