### ISSUE TITLE
Add enter fullscreen button to amp-story if user has exited fullscreen

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#11646]
Right now, if the user manually exits fullscreen, we don't force them back into fullscreen when they navigate to the next page. However, since there is no "enter fullscreen" button, there is no way for the user to get back into fullscreen mode after they have manually exited it.

**Comment by prateekbh** [comment]
Question: does the first time fullscreen also be triggered by this new button?

**Comment by newmuis** [comment]
Not in the current experience.

We automatically push the user into fullscreen when they advance to the next page of the story, so the current UX does not initially have an enter fullscreen button.  But the desired behavior is that once the user has exited fullscreen, we add (or unhide) a fullscreen button.

**Comment by prateekbh** [comment]
Wouldn't it be better to show the `enterFullscreen` button from the very beginning?
It decreases the surprise element(suddenly a button starts appearing after a certain action).
