### ISSUE TITLE
[Master feature] Support RTL for amp-story

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#11647]
Right now, everything is designed as LTR.  This is a cover bug for enabling RTL support.  We should consider the story to be RTL if:

1. Any ancestor of the story element has its `dir` attribute set to `"rtl"`
2. Failing that, the `direction` property of its computed style is `"rtl"`
3. Failing that, `document.dir` is set to `"rtl"`

If none of these are true, we should consider the story as LTR.  We can calculate this once per story, at build time.

- [x] Navigation areas of the screen should be flipped (i.e. tapping the left side of the screen will advance to the next page; the right side of the screen will go back to previous)
- [x] Keyboard keys should be flipped (left arrow for next; right arrow for previous)
- [x] System layer UI elements should be flipped (the buttons normally in the top right should be in the top left, and vice versa), on desktop and mobile
- [ ] Bookend UI elements should be flipped
- [ ] `amp-story-consent` UI elements should be flipped
- [x] Share menu UI elements should be flipped
- [ ] Info dialog UI elements should be flipped
- [ ] Hint layer UI elements should be flipped
- [ ] Any icons indicating directionality based on reading direction (as opposed to, say, handedness) should be flipped

**Comment by aghassemi** [comment]
@newmuis @choumx Could we consider move this to P1/P2? Another market this has come up is Japan.

**Comment by morsssss** [comment]
This is harder no doubt... but would it be worth creating another issue to enable vertical instead of horizontal?  At least one major language group expects that :)

**Comment by erwinmombay** [comment]
i want to read my manga :)

**Comment by newmuis** [comment]
The visual diff tests added in #17110 show that many of the templated UIs need some love in RTL:

![issue_rtl_bookend](https://user-images.githubusercontent.com/1651960/43329854-995b1f4a-918f-11e8-9cba-95726e35a227.jpeg)
![issue_rtl_consent](https://user-images.githubusercontent.com/1651960/43329855-9967bb42-918f-11e8-883e-d01a27986f08.jpeg)
![issue_rtl_info_dialog](https://user-images.githubusercontent.com/1651960/43329856-99749024-918f-11e8-93b2-05f09ea8243c.jpeg)

The share menu actually looks okay:

![rtl_share_menu](https://user-images.githubusercontent.com/1651960/43329913-b6fb77ca-918f-11e8-8c8c-ed1fc7abb5f1.jpeg)

**Comment by Enriqe** [comment]
Yep, the share menu was just fixed in #17098 alongside the system layer. I am working on the remaining templated UIs. Thanks for including RTL in the visual diffs!
