### ISSUE TITLE
amp-story breaks with invalid page IDs

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#11650]
We do not validate the IDs of `<amp-story-page>` elements, but `querySelector` does not support all forms of IDs.  I'd like to figure out what other AMP components that are dependent on IDs are doing here and match their behavior.

**Comment by prateekbh** [comment]
i found this thing `value_regex` https://github.com/ampproject/amphtml/blob/e2f0f4c9126bac89a98e65722c8eede1a11b8285/extensions/amp-web-push/validator-amp-web-push.protoascii#L42

will this suffice our need here?


cc: @alanorozco @newmuis @choumx

**Comment by newmuis** [comment]
Yeah, we could come up with a regex that we deem valid for page IDs.  I'm not sure if there's a standard for what `querySelector` supports?  Or if this is a browser quirk that some browsers disallow `querySelector` for IDs starting with numbers?

**Comment by choumx** [comment]
Why not use `Document#getElementById` instead of `scopedQuerySelector`? Validation won't cover whitespace transformation: https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector#Notes

**Comment by newmuis** [comment]
This now no longer happens since we implemented our own `getPageById_(...)` using `findIndex` over the array of pages.
