### ISSUE TITLE
amp-social-share twitter background color doesn't match brand guidelines

### ISSUE THREAD

**Issue by theaemarie** [ampproject/amphtml#11651]
## What's the issue?

It seems that the background color used for the twitter social share might not be correct. Page 8 of [this brand guidelines doc](https://about.twitter.com/content/dam/about-twitter/company/brand-resources/en_us/Twitter_Brand_Guidelines_V2.0.pdf) from twitter specifies the blue color should be `#1DA1F2`.

## How do we reproduce the issue?

1. Include twitter logo on page `<amp-social-share type="twitter"></amp-social-share>`
2. Background color used in class `.amp-social-share-twitter` is `#55acee`

## What browsers are affected?

All browsers, all devices

## Which AMP version is affected?

Using AMP ⚡ HTML – Version 1507083985898

**Comment by aghassemi** [comment]
@theaemarie Great catch, thanks for reporting it. Fix here: https://github.com/ampproject/amphtml/pull/11654
