### ISSUE TITLE
no suitable amp element to achieve this type of menu

### ISSUE THREAD

**Issue by markgarel17** [ampproject/amphtml#11675]
**Please only file bugs/feature requests for AMP here.**

## What's the issue?

**No amp element to achieve this type of menu function, even the staff here at AMPRoadshow have no current solution. and asked me to upload a new issue.**

Briefly describe the bug/feature request.

**as you could see in the screenshot.
Google Adwords row.

Google Adwords is an inline link, and the small arrow on the far right is its dropdown button.
Once you've tapped the dropdown it shows it's submenu, tap it again to hide.

I've tried using amp-accordion to achieve this function, but the problem is I can't inline it.
tried amp-selector but the it's hacky and the submenu button moves which i prefer to stay in place.

is there any element that is similar to amp-accordion but can be used inline?
how can i achieve this look and feel using AMP?**

![image](https://user-images.githubusercontent.com/13176158/31528155-7252f048-b01d-11e7-9f83-1307f8883935.png)

![image](https://user-images.githubusercontent.com/13176158/31528176-9cc36aec-b01d-11e7-9f71-2ccf83b18f12.png)

went to google amp hackathon in Sydney and AMPRoadshow2017 but found no solution or better alternatives.

we have a lot of client websites with this type of menu. we couldn't proceed with AMP unless we could replicate the same look and feel of their websites.

**Comment by aghassemi** [comment]
@markgarel17 combinations of `amp-accordion`, `position absolute div` and `AMP.toggleVisibility` action should be able to handle this.

Asking this on Stackoverflow may land you some sample code from the community

**Comment by markgarel17** [comment]
@aghassemi thank you for the idea.
although using position absolute and z-index is hacky, this did the job.

looks like we need to wait a bit more until there's a better solution.
using a roundabout way to fix a simple 2 inline element, this definitely doesn't go under best practices.
not good for a website trying to climb in the rankings.

Thank you for responding quickly. looking forward to the development of this project.
