### ISSUE TITLE
Intent to implement: Outstream unit for for amp-brid-player

### ISSUE THREAD

**Issue by pedjoni8** [ampproject/amphtml#11680]
Outstream unit implementation for amp-brid- player extension.

Implementation and example page at:
[https://github.com/pedjoni8/amphtml/tree/outstream/extensions/amp-brid-player](url)

**Comment by aghassemi** [comment]
Closed by https://github.com/ampproject/amphtml/pull/11694

**Comment by seomaz** [comment]
it's possible to collapse the element <amp-brid-player> when the ad ends ?
