### ISSUE TITLE
AMP custom content based on country [for affiliate marketing]

### ISSUE THREAD

**Issue by MKDan** [ampproject/amphtml#11684]
How to show content based on user geographic location. This is very handy for affiliate marketing. Google AMP pages lack this support. So, a person who is from India clicks the affiliate link for the USA.

**Comment by aghassemi** [comment]
@MKDan Existing request for this feature: https://github.com/ampproject/amphtml/issues/826 

Currently aside from `amp-iframe`, `amp-list` and other components that talk to your origin, there isn't much support.

Closing as dup of https://github.com/ampproject/amphtml/issues/826
