### ISSUE TITLE
amp-analytics about "video-*" event not filred on amp-youtube 

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#11692]
Hi:

I try to use amp-analytics to collect video interaction. I apply **amp-youtube>** tag to implement youtube video in my page and add **video-played**, **video-pauseed**, **video-ended** on trigger, but these events  don't fired when video play / pause / end.

Here comes my code.

```
<body>
    
<amp-analytics type="googleanalytics">
    <script type="application/json">
        {
            "vars": {
                "account": "UA-74300583-2",
                "documentGroup": "itemPage",
                "level1Id": "25464",
                "level2Id": "2092097693",
                "level3Id": "2092097697",
                "level4Id": "none",
                "level5Id": "none",
                "level6Id": "none",
                "merchandiseId": "100132105311"
            },
            "extraUrlParams": {
                "cg1": "${documentGroup}",
                "cd1": "${level1Id}",
                "cd2": "${level2Id}",
                "cd3": "${level3Id}",
                "cd4": "${level4Id}",
                "cd5": "${level5Id}",
                "cd6": "${level6Id}",
                "cd7": "${merchandiseId}"
            },
            "triggers": {
                "pageview": {
                    "on": "visible",
                    "request": "pageview"
                },
                "videoPlayed": {
                    "on": "video-played",
                    "request": "event",
                    "selector": "#yt-player",
                    "vars": {
                        "eventCategory": "${documentGroup}",
                        "eventAction": "video",
                        "eventLabel": "played"
                    }
                },
                "videoPaused": {
                    "on": "video-paused",
                    "request": "event",
                    "selector": "#yt-player",
                    "vars": {
                        "eventCategory": "${documentGroup}",
                        "eventAction": "video",
                        "eventLabel": "paused"
                    }
                },
               "videoEnded": {
                    "on": "video-ended",
                    "request": "event",
                    "selector": "#yt-player",
                    "vars": {
                        "eventCategory": "${documentGroup}",
                        "eventAction": "video",
                        "eventLabel": "ended"
                    }
                }
            }
        }
    </script>
</amp-analytics>

<amp-youtube
    id="yt-player"
    data-videoid="Y5zj3dwNxJw"
    layout="responsive"
    width="480" height="270" autoplay data-param-rel="0" data-param-showinfo="0"></amp-youtube>

</body>
```

Have a nice day.

Paul

**Comment by cvializ** [comment]
Hi Paul, I am not able to reproduce this on a test page. I notice you specify the top level fields `"vars"` and `"triggers"`, but you don't specify any `"request"` fields that correspond to the `"request"` property of the triggers. Did you intentionally omit those in your sample code?

e.g.
 
```json
{
  "requests": {
    "event": "https://www.example.com/analytics/video?c=${eventCategory}&a=${eventAction}&l=${eventLabel}"
  },
  "triggers": {
    "videoPlayed": {
      "on": "video-played",
      "request": "event",
      "selector": "#yt-player",
      "vars": {
        "eventCategory": "${documentGroup}",
        "eventAction": "video",
        "eventLabel": "played"
      }
    }
  }
}

```

**Comment by meistudioli** [comment]
Hi, @cvializ :

I use **type="googleanalytics"**, there is no need to set "request".
Check the following link:
[Adding Analytics to your AMP pages](https://developers.google.com/analytics/devguides/collection/amp-analytics/)

Here also comes my demo page, please scroll about vertical 50% position and you will see the amp-youtube.
[demo page](https://blog-lalacube-com.cdn.ampproject.org/c/s/blog.lalacube.com/mei/yahoo_auction_amp.html)

Thanks for concern this issue and have a nice day.

Paul

**Comment by cvializ** [comment]
Ah thank you for the clarification and the link to your document. I investigated some more and it looks like our docs have a mistake. The correct name for the event is `video-play`, not `video-played`. Does the event fire if you use `"on": "video-play"`? We will fix the documentation soon and track it with this issue.

**Comment by cvializ** [comment]
(and video-ended is not supported by amp-youtube)

**Comment by meistudioli** [comment]
hi, @cvializ :

Thanks for fixed the document. It can works well after I changed the event name.

※ [AMP Video analytics](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-video-analytics.md)

Have a nice day.

Paul

**Comment by cvializ** [comment]
You're welcome Paul, glad it works for you now : )
