### ISSUE TITLE
amp-form does not update fieldset with user-invalid

### ISSUE THREAD

**Issue by devvercer** [ampproject/amphtml#11691]
The test page below shows a form containing a single fieldset with a single input[type=text]. When the input is invalid it is marked as user-invalid and so is the form but the fieldset is marked user-valid.

https://codepen.io/vercer/pen/aLRKpd

**Comment by aghassemi** [comment]
@devvercer We used to support this but dropped it to be consistent with the standards and the way browsers behave. Not planning to add it back.

From: https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement

> HTMLFieldSetElement.checkValidity()
> Always returns true because `<fieldset>` objects are never candidates for constraint validation.

See Also: https://github.com/ampproject/amphtml/issues/4317

**Comment by devvercer** [comment]
Ok thanks for the response.  Perhaps the docs should be updated to reflect
this:

"amp-form also propagates these to ancestors fieldsets and form."

I wonder if the class user-valid should not be added at all to fieldset if
it is not useful?

**Comment by cvializ** [comment]
Thanks for reporting this! Yes we should update the docs so no one is confused in the future.
