### ISSUE TITLE
Chrome Extension: Move between caches

### ISSUE THREAD

**Issue by jamesshannon** [ampproject/amphtml#11690]
## What's the issue?

The chrome extension should allow you to move between various caches and the canonical. Right now if you're on a cache and click the action button you go to canonical. However, you should be able to choose where to go, including to other caches.

For example, from the canonical, you should be able to go to the ampproject cache, the ampproject google viewer cache (which appears to have different content) and even other 3rd party caches.

This would allow you to easily see what the caches are serving, and to test things that might be different in the cache (e.g., analytics). 

AMP cache URLs are publicly published so this is really just  a shortcut for building the URL yourself.

**Comment by aghassemi** [comment]
@jamesshannon thanks for the feature request. The extension is not staffed so unlikely we will get to it anytime soon. Contributions would be very welcomed!

**Comment by jamesshannon** [comment]
Ok. So it sounds to me like this is something that would, theoretically, be accepted?

I see three possible objections from your perspective, and wanted to ensure they weren't blockers to you accepting a PR.

1. Linking directly to the cached version(s), which the extension doesn't do today. I wasn't sure if that was strategic or not.

2. "Support" of 3rd party caches (e.g., twitter's) through acknowledgement that they exist and linking to them. My plan would be to include the obvious one or two and make it extensible enough that others could add caches if they want. 

3. I don't know anything about opera extensions so this would be chrome-only.

My team uses this extension pretty regularly, and this could help in debugging.

**Comment by aghassemi** [comment]
I don't see any issues with these points. Thanks for checking first. Extension is there to help dev debug and this sounds like a useful feature. I am all for it.

**Comment by honeybadgerdontcare** [comment]
@jamesshannon Feel free to send any PRs to me as I wrote the extension but am not actively working on it ATM.

**Comment by jamesshannon** [comment]
SGTM. I opened up the code, saw the all the Polymer code, and got a bit scared. I'll dig into this when I have more time.

**Comment by Gregable** [comment]
Closing issue as there is no plan for the AMP team to resolve.
