### ISSUE TITLE
Add "page is hidden" bool to unlayoutCallback()

### ISSUE THREAD

**Issue by jonkeller** [ampproject/amphtml#11701]
Currently, unlayoutCallback() is used to indicate that the element itself has been hidden yet the page remains visible, and also that the whole page has been hidden. There's no way to differentiate between the two cases. Amp Analytics now needs to do so:

The amp-analytics element gets un-laid-out after 1 second, causing a call to unlayoutCallback().

But, AMPAnalytics now offers "iframe transport" which involves creating child object(s), which we should clean up responsibly when the user swipes to another page in the carousel. We want to do that when the page is torn down, *not* just when the amp-analytics element itself gets hidden.

**Comment by aghassemi** [comment]
@jonkeller `viewer.isVisible()` (`viewer = Services.viewerForDoc(doc);`) should give you whether page is visible or not. Would this handle your case?

**Comment by jridgewell** [comment]
Ha, I didn't think of doing that manually. That should work fine, just do any early return false if not visible and isIframeTransport:

```js
unlayoutCallback() {
  if (!viewer.isVisible() && this.isIframeTransport) {
    // prevent unlayout, will happen later when page is unloaded
    return false;
  }

  // continue on...
}

**Comment by jonkeller** [comment]
Awesome, thanks, Ali!
