### ISSUE TITLE
amp-selector inside amp-form gives exception

### ISSUE THREAD

**Issue by devvercer** [ampproject/amphtml#11707]
## What's the issue?

I have an amp-selector inside an amp-form to segment the form fields. when I click on a "section" this exception is thrown:

form-validators.js:290 Uncaught TypeError: a.checkValidity is not a function
    at U.push.f.l.onInteraction (form-validators.js:290)
    at U.push.f.U.onInteraction (form-validators.js:370)
    at U.push.f.l.onBlur (form-validators.js:297)
    at HTMLFormElement.<anonymous> (amp-form.js:255)

## How do we reproduce the issue?

I made a demo https://codepen.io/vercer/pen/aLRKpd

Click on the two inputs alternately and the exception is thrown in the console.

## What browsers are affected?

Chrome (latest)

## Which AMP version is affected?

I think this just started today!?

**Comment by camelburrito** [comment]
@devvercer - i think per spec , you will need to give an option some value - `option="somevalue"`, may be even try an empty string. Can you check if that is the issue?

**Comment by devvercer** [comment]
I've updated the example pen above and it still throws the exception.

**Comment by cvializ** [comment]
I investigated and discovered that the `amp-selector [option]` divs trigger a blur event, and the custom validator listens for blur events and expects that any target element is an input with a `checkValidity` method. This would probably happen for any non-input element with a `tabindex` set inside a form with `custom-validation-reporting`.

https://github.com/ampproject/amphtml/blob/master/extensions/amp-form/0.1/form-validators.js#L290

Adding a check that the element has a `checkValidity` method fixes the error. Also not using the `custom-validation-reporting` attribute prevents the error from appearing.

I'll make a PR with the fix.

**Comment by devvercer** [comment]
Great nice work!
