### ISSUE TITLE
amp-sticky-ad's amp-ad is not centered in the Google AMP viewer

### ISSUE THREAD

**Issue by ehmorris** [ampproject/amphtml#11702]
## What's the issue?

Within the Google AMP viewer, `amp-sticky-ad`'s `amp-ad` child is not centered [[screenshot](https://user-images.githubusercontent.com/654275/31631167-d90fee56-b286-11e7-8ecc-c9e5899a0736.png)].

Outside of the viewer, it is centered [[screenshot](https://user-images.githubusercontent.com/654275/31631168-d91c250e-b286-11e7-99a4-1391e34f53ce.png)].

I'd expect both instances to be centered.

## How do we reproduce the issue?

1. Navigate to https://www.google.com/amp/s/ampbyexample.com/components/amp-sticky-ad/ on an iOS device (this reproduces on iOS 10 and 11.)
2. Navigate to https://ampbyexample.com/components/amp-sticky-ad/ on an iOS device.
3. Note that on the first url, the ad is not centered, but is on the second url.

I noticed one large difference: the iFrame which is a direct child of the `amp-ad` element has a width and height in the broken Google AMP viewer version, but not in the non-AMP-viewer version:

<img width="1808" alt="screen shot 2017-10-16 at 3 39 10 pm" src="https://user-images.githubusercontent.com/654275/31631743-a4fbb486-b288-11e7-8502-a650a6c3ea2d.png">

*(left is Google AMP viewer, right is non-AMP-viewer)*

The bodies of the ads within this iFrame are also significantly different.

## What browsers are affected?

iOS 10 and 11 Safari.

## Which AMP version is affected?

At least 1507083985898 (my current version) and up.

**Comment by zhouyx** [comment]
I am able to reproduce this. taking a look.

**Comment by ehmorris** [comment]
As a temporary fix, applying `margin: auto` to `<amp-ad>` fixes the centering issue in the inspector, and is AMP valid.

**Comment by zhouyx** [comment]
Thanks for filing this issue! We found the root cause for this bug. Already tracked internally, should be able to see the fix soon.

**Comment by ehmorris** [comment]
I can no longer reproduce the bug. Thanks!
