### ISSUE TITLE
Document how to use CLIENT_ID in URLs

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1172]
Waiting for the user notification work to land, to document this.

**Comment by rudygalfi** [comment]
pinging @cramforce to see if there's an update here or if this can be closed

**Comment by erwinmombay** [comment]
related https://github.com/ampproject/amphtml/issues/1510 

also we have some docs on client_id in https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md
