### ISSUE TITLE
Error: a.json is not a function

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#11738]
https://github.com/ampproject/amphtml/blob/master/extensions/amp-app-banner/0.1/amp-app-banner.js#L384

https://github.com/ampproject/amphtml/blob/master/extensions/amp-user-notification/0.1/amp-user-notification.js#L202

sample UA's:
Mozilla/5.0 (Linux; Android 5.1.1; SM-J320F Build/LMY47V; de-de) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Mobile Safari/537.36 Puffin/6.1.4.16005AP 
Mozilla/5.0 (Linux; Android 4.1.2; SHV-E160L Build/JZO54K; vi-vn) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 Puffin/6.1.4AP Chrome/59.0.2623 
Mozilla/5.0 (Linux; Android 7.1.1; Lenovo K8 Note Build/NMB26.54-71; en-us) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 Puffin/6.1.4AP Chrome/59.0.2623

**Comment by lannka** [comment]
Is it still a thing?
