### ISSUE TITLE
Extension validation doesn't simulate mobile device

### ISSUE THREAD

**Issue by jamesshannon** [ampproject/amphtml#11741]
https://m.crateandbarrel.com/amp/furniture/sofas/1#development=1

works fine on mobile, but if the request comes from desktop it redirects to a non-AMP:

https://www.crateandbarrel.com/amp/furniture/sofas/1#development=1

validator.ampproject.org handles this properly (probably by setting the UA to a mobile UA):

![the_amp_validator](https://user-images.githubusercontent.com/761381/31740418-29340248-b406-11e7-9361-294829ae095e.png)

But the chrome extension seems to be pulling the non-AMP version, probably because it gets served a redirect: 

![sofas__couches_and_loveseats___crate_and_barrel](https://user-images.githubusercontent.com/761381/31740518-7466b7a6-b406-11e7-9969-c535ba466936.png)

**Comment by honeybadgerdontcare** [comment]
The extension framework exists within the browser itself, not within DevTools. So any simulation done in DevTools does not apply to extensions. At least I haven't seen it work. The source code for the extension is [open sourced](https://github.com/ampproject/amphtml/tree/master/validator/chromeextension). If you find a way to get the user agent from DevTools within the extension then you're welcome to submit a PR and assign to me (I wrote the extension).

**Comment by jamesshannon** [comment]
I should have mentioned explicitly that I see this as pretty low impact, as (AFAICT) it only affects those servers that deliver different content to different UAs. But I wanted to log it for the record.

And I don't think the issue is devtools, but instead the validator web service, which I presume is server to server. Since you're suggesting that the extension makes the request itself (rather than asking validator.ampproject.org to make the request) then it seems only a matter of changing the UA for that request, which [appears to be doable](https://stackoverflow.com/questions/21090733/changing-user-agent-in-xmlhttprequest-from-a-chrome-extension).

FWIW, it looks like validator.ampproject sends:

`Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MTC19V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.81 Mobile Safari/537.36 (compatible; validator.ampproject.org) AppEngine-Google; (+http://code.google.com/appengine; appid: s~amp-validator)`

Which I could have probably found in the source, but I used a [web service](https://validator.ampproject.org/#url=https%3A%2F%2Fwww.whatismybrowser.com%2Fdetect%2Fwhat-is-my-user-agent).

So it would probably make the most sense to use a UA similar to that.

**Comment by honeybadgerdontcare** [comment]
Yes, the webui does spoof the UA to be mobile. The chrome extension does not do that. It sends the UA of the browser, so when one is in DevTools it still sends the UA of the browser it's running in.

**Comment by honeybadgerdontcare** [comment]
So then the choice is, does the extension always spoof to some UA or use the UA of the browser. Perhaps this is something that could be configurable within the extension itself.

**Comment by Gregable** [comment]
I'd prefer that the extension use the browser's UA, so that we are more likely to be looking at the same document in the main browser frame as the extension is looking at. If there is a difference, I think it would be very confusing to a user.

**Comment by jamesshannon** [comment]
Maybe that's why Honey was pointing out devtools integration?

Just to be clear, the extension is not always using the browser's UA today. Even when the UA has been changed (at least in mobile emulation mode, but probably also in explicit-UA-setting mode) the extension seems to use the default UA.

I just confirmed that `navigator.userAgent` returns the  UA being sent in requests (including when UA is manually configured in Dev Tools. So I think that it's just a matter of grabbing that and using it in the WebRequest API to update the extension's requests.

**Comment by Gregable** [comment]
I think I misunderstood then. @honeybadgerdontcare , would it be straightforward to use the `navigator.userAgent` in the request?

**Comment by honeybadgerdontcare** [comment]
The extension does nothing fancy regarding what is sent with the request. I'll do some testing to see if we can use navigator.userAgent if this is indeed the desired behavior.

**Comment by jamesshannon** [comment]
I've already done some testing. It's not super easy, as you can't directly set the UA. Instead you need to use webRequest, capture the request (blocking-ly), and then update the UA as appropriate. Since the XHR is done in the background then the tab needs to send the UA in the message (which isn't hard).

IMO, setting the background's XHR UA to the same value as what the tab is configured for is desired.

**Comment by honeybadgerdontcare** [comment]
It sounds like you're on the way to have this implemented. Want to send a PR?

**Comment by jamesshannon** [comment]
I will. I'm not quite ready for a PR yet as I was having problems changing the headers. I need to re-look at it with a fresh set of eyes this week and clean up the code. The [working branch is here](https://github.com/ampproject/amphtml/compare/master...jamesshannon:extension-set-ua-to-request?expand=1), though.

**Comment by jamesshannon** [comment]
@honeybadgerdontcare How often does the extension get released? This was blocking something important (a peer bonus ;) ).

**Comment by honeybadgerdontcare** [comment]
@jamesshannon It gets released when there are changes. Just noticed your PR hasn't been reviewed or merged. I'll get to that now. I moved some files around in a recent change so you'll need to resolve those conflicts. Sorry about that.

**Comment by jamesshannon** [comment]
Too many merge conflicts. I'm going to have to revisit this in the future.

**Comment by honeybadgerdontcare** [comment]
I could go ahead and lift your changes in if you're okay with that.

**Comment by jamesshannon** [comment]
If you have an efficient way of doing that, go ahead. My attempt at rebasing introduced a bunch of issues, and I ended up having to manually re-add all my changes based on my original PR... then ran into renamed files.
