### ISSUE TITLE
amp-story analytics initial page event

### ISSUE THREAD

**Issue by acorretti-comscore** [ampproject/amphtml#11754]
With the new `amp-story` component there is a new analytics event introduced, `story-page-visible`.

Most analytics vendors have been triggering page view measurements via the `visible` event.

In an attempt to implement story page view measurements, we're facing a situation where two events are fired on the initial story page load: the page _visible_ event, followed by the story's first _story-page-visible_ event.

Question is: How can we, analytics vendors, keep the `visible` trigger we have right now in place to measure all page views, and just listen for `story-page-visible` events other than the first story page's?

**Comment by newmuis** [comment]
AFAIK, the `visible` and `story-page-visible` events are semantically a bit different.  `visible` is fired whenever the DOM element becomes visible, whereas `story-page-visible` is fired when the page actually becomes the active page of the story.  In theory, it's possible for the DOM element to be visible without the page being active (e.g. in our experimental desktop view), so the DOM elements for inactive pages will have had the `visible` event fire, but not the `story-page-visible` event.

/cc @alanorozco to make sure I didn't miss anything

**Comment by acorretti** [comment]
Right, so adding a bit of background here in regards to analytics we'll be measuring story-pages as regular page views, as it's traditionally been done for pieces changing substantial portions of screen content in response to user actions.

As an analytics vendor, we'll now just ignore the first story-page view event if it's too close to the page `visible` view event.

It would be very interesting for us to have a way to tell if an `amp-story` is a page's main content -shown in first place-, so that the first story-page view event can be disabled.

**Comment by newmuis** [comment]
The `standalone` attribute on an `amp-story` tag indicated that it is the only content within the document (aka the "main content").

**Comment by acorretti** [comment]
Can that be read by `amp-analytics` vendors? It would be wonderful.

**Comment by alanorozco** [comment]
I'm not completely sure that adding the `standalone` attribute to the event payload would be the best way to go. 

As the standalone story lives in the same place as the analytics config, I believe one could simply encode this information as part of the endpoint URL payload. 

@rudygalfi for input.

**Comment by newmuis** [comment]
Closing this, since it can be worked around on the publisher side, since they have knowledge of whether or not the story is `standalone`.

Feel free to re-open if you feel the need is not adequately addressed.
