### ISSUE TITLE
amp-twitter remove source querystring

### ISSUE THREAD

**Issue by gui-poa** [ampproject/amphtml#11770]
## What's the issue?
If the editor puts some querystring in the href element on twitter the element does not load.

e.g:
https://twitter.com/ItsDavePaulson/status/920851761182793728?ref_src=twsrc%5Etfw

<blockquote class="twitter-tweet" data-lang="pt">
	<p class="text" dir="ltr" lang="en">
		Lol <a href="https://twitter.com/katyperry?ref_src=twsrc%5Etfw">@katyperry</a>&#39;s flying planet stage got stuck in Nashville and she had to jump into the crowd <a href="https://t.co/p3aYrYlQbF">pic.twitter.com/p3aYrYlQbF</a>
	</p>
	&mdash; Dave Paulson (@ItsDavePaulson) <a href="https://twitter.com/ItsDavePaulson/status/920851761182793728?ref_src=twsrc%5Etfw">19 de outubro de 2017</a>
</blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

## How do we reproduce the issue?

http://amp.purepeople.com.br/noticia/pane-em-equipamento-surpreende-katy-perry-em-show-veja-reacao-da-cantora_a199747/1

I think the same problem is occuring on other embeds too (facebook  for sure).

**Comment by aghassemi** [comment]
@gui-poa technically `tweetid` needs to be the pure tweet number without any extras. That being said, last week we made `amp-twitter` more reliant to these misconfigurations ( #11685 ) and it will now handle your case, but you may start getting warnings. I still highly recommend finding out why editor puts query string on tweetid and fixing it there as well.
