### ISSUE TITLE
Version regex in documentation incorrect

### ISSUE THREAD

**Issue by sethyates** [ampproject/amphtml#1177]
In the [Specification](https://www.ampproject.org/docs/reference/spec.html) [here](https://www.ampproject.org/docs/reference/spec.html#extended-templates) and [here](https://www.ampproject.org/docs/reference/spec.html#extended-components):

> The script URL must start with “https://cdn.ampproject.org” and must follow a very strict pattern of “/v\d+/[a-z-]+-(latest|\d+|\d+-\d+).js”

However, this regex doesn't properly match the example given

    <script async custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.1.js"></script>

Looks like it should be:

> /v\d+/[a-z\-]+-(latest|\d+|\d+\.\d+).js

And is the "amp-" prefix not required for the script?

**Comment by cramforce** [comment]
Ha, I thought we had fixed this. The amp- prefix is definitely not required.

**Comment by cramforce** [comment]
@pbakaus Just FMI: At what schedule/non-schedule do we currently push changes from AMP-master to the docs site/repo?

**Comment by pbakaus** [comment]
We currently don't have a set schedule, it's all manual. How often do you think it's worth deploying? I'll prepare one now together with Erwin in any case.

**Comment by cramforce** [comment]
We should eventually align it with our weekly pushes. We are going to change a bit over time how we release. Right now basically once a week.

**Comment by pbakaus** [comment]
Works for me. @erwinmombay
