### ISSUE TITLE
Intent To Implement: PubExchange content recommendation widget

### ISSUE THREAD

**Issue by pubexchange** [ampproject/amphtml#11771]
Adding support for [PubExchange](https://www.pubexchange.com) content recommendation widget for amp-embed. PubExchange will submit a pull request using this fork: [https://github.com/pubexchange/amphtml](https://github.com/pubexchange/amphtml)

Here is an example of a PubExchange widget on [Southern Living](http://www.southernliving.com):
<img width="886" alt="pubexchange-on-southern-living" src="https://user-images.githubusercontent.com/15114422/31826913-6a89e562-b584-11e7-86a7-fbf513cfb110.png">

**Comment by jasti** [comment]
Thanks, look forward to PR.

**Comment by pubexchange** [comment]
Do you know if the Pull Request is being delayed based on something I need to do?
https://github.com/ampproject/amphtml/pull/11823

**Comment by jasti** [comment]
@zhouyx  could you please take a look? thx.

**Comment by mrjoro** [comment]
Looks like this was added in #11823.  Please reopen if there's anything left to do here.
