### ISSUE TITLE
Allow amp-bind to work with amp-brightcove custom data

### ISSUE THREAD

**Issue by bjalford** [ampproject/amphtml#11772]
amp-bind: Binding to [data-param-custom-params] on <AMP-BRIGHTCOVE> is not allowed.​​​ 

Is there any reason we can't use bind to change the custom params on the amp-brightcove with bind?

**Comment by choumx** [comment]
No, just need to add mutation support to `amp-brightcove.js` and whitelist the attributes in `bind-validator.js` and `validator-main.protoascii`.
