### ISSUE TITLE
Consider using preload for Safari 11

### ISSUE THREAD

**Issue by jonkeller** [ampproject/amphtml#11786]
Safari supports preload, beginning with v11: http://caniuse.com/#feat=link-rel-preload
But, preconnect.js polyfills for Safari (all versions): https://github.com/ampproject/amphtml/blob/78b17216c8066818a528a76df27c2254eb69aea5/src/preconnect.js#L244

Investigate if we can start to use this polyfill only for Safari <= 10.

**Comment by jonkeller** [comment]
Doing this should fix #6900

**Comment by jonkeller** [comment]
Note the two occurrences of this in extensions/amp-a4a/0.1/test/test-amp-a4a.js - that's what's breaking in #6900.
```
          expect(doc.querySelector('link[rel=preload]' +
           '[href="https://fonts.googleapis.com/css?family=Questrial"]'))
             .to.be.ok;
```

**Comment by jridgewell** [comment]
First, this has to do with `preconnect`, not `preload`. The linked polyfill is only used when `preconnect` is not supported.

Which means, when iOS Safari 11.3 ships (which supports `preconnect`), the polyfill won't be used. Everything will work as intended. https://github.com/ampproject/amphtml/blob/78b17216c8066818a528a76df27c2254eb69aea5/src/preconnect.js#L267-L269
