### ISSUE TITLE
[FR] Expose invalid and valid events on input elements

### ISSUE THREAD

**Issue by devvercer** [ampproject/amphtml#11782]
## Feature Request.

Form exposes events "valid" and "invalid" and I would like these to also be exposed on contained <input> elements.

## Use case

I have a form that is divided into several sections (using amp-accordion) that are hidden by default until the user expands them. If there is an invalid field in the section I would like to highlight the section header.

```
<amp-accordion>
<section [class]="blahClass">
  <header>blah</header>
  <input on="invalid:AMP.setState({blahClass : 'invalid'}) name="foo" required/>
</section>
... more sections...
</amp-accordion>
```

**Comment by aghassemi** [comment]
@devvercer They are already exposed as `validation` event on `form`. Please see https://www.ampproject.org/docs/reference/components/amp-form#events for details.

**Comment by aghassemi** [comment]
Closing the issue, feel free to reopen if solution does not satisfy your use-case.

**Comment by choumx** [comment]
One problem with exposing these events on `input` is the fact that validity of an `input` can conflict or be out of sync with the validity of the `form`. 

You can use descendant CSS selectors to style children of valid or invalid forms.

**Comment by devvercer** [comment]
@aghassemi The events on form do not allow this use case as there is no way to know which section contains the invalid field so it can be highlighted.

@choumx descendant selectors will not allow the correct section only to be styles.

**Comment by devvercer** [comment]
@choumx Do you mean e.g. an input could be invalid while the form remains valid (or vise versa)?

As long as they are eventually consistent, sync would not be a problem?

**Comment by choumx** [comment]
> descendant selectors will not allow the correct section only to be styles.

Why not? `user-valid` and `user-invalid` CSS classes are added to valid and invalid inputs, respectively. https://www.ampproject.org/docs/reference/components/amp-form#classes-and-css-hooks
