### ISSUE TITLE
AMP-experiment and Optimize reporting

### ISSUE THREAD

**Issue by MBonifazi** [ampproject/amphtml#11785]
## What's the issue?

Google Optimize does not record any data when measuring AMP-experiment
# 
We started to use the [AMP-experiment](https://www.ampproject.org/docs/reference/components/amp-experiment) for A/B tests and wanted to take advantage of the Optimize algorithm to measure them.

After following this guide:
https://developers.google.com/optimize/devguides/amp-experiments

- We could successfully trigger and style any of the variations via AMP-experiment.

- See the experiment running in Optimize.

Unfortunately no data has been recorded.

## How do we reproduce the issue?

Following: https://developers.google.com/optimize/devguides/amp-experiments on any AMP page.

A static page is available at this URL with a running AMP-experiment
https://www.irishtimes.com/static/amp-static/it-amp--experiment.html

## What browsers are affected?

All browsers

## Which AMP version is affected?

https://cdn.ampproject.org/v0.js

**Comment by aghassemi** [comment]
@MBonifazi I recommend asking this on [Optimize Community Forum](https://www.en.advertisercommunity.com/t5/Google-Analytics/ct-p/Google_Analytics) instead.
