### ISSUE TITLE
Intent to Implement: Behavioral Patterns

### ISSUE THREAD

**Issue by miquelferrandiz** [ampproject/amphtml#11818]
## Background

Units such as advertisements or email modals can unintentionally provide a poor user experience if displayed among page content while the user is actively consuming content. This can be especially true with the increased prevalence of rich-media ads alongside static content, which are often distracting and intrusive.

At BounceX, we’ve found that waiting to display these until after certain behavioral patterns have occurred - primarily those that indicate disengagement with page content - improves user experience and thus likelihood of interacting with the unit. This improves the overall AMP experience as well as the economics of a single user on an AMP page for the page owner.

## Proposal

Ability to detect user behaviors such as scroll direction / speed, cursor gestures, combine them into patterns, and use them as event handlers. 

Primary application of these behavioral pattern event handlers will be to display ad or email units when the user has finished engaging with content, rather than displaying immediately on pageload.

### Simple Example

This example indicates how amp-behavioral-pattern could be used to display an amp-iframe after the user scrolls at least 50% of the way through content, then scrolls rapidly back to the top. This is a common behavioral pattern that indicates a user is finished reading content.

In this example, the amp-iframe would be positioned immediately below the navbar, making it visible at the moment of disengagement but not interruptive to the user’s experience.

This also relies on amp-bind to change the unit height once the behavior pattern is matched.

```javascript
<amp-behavior-pattern id=”fast-upscroll-top”>
        <script type="application/json">
		{
			"scroll": {
				"direction": "down",
				"min-amount": "50",
			        "max-amount": "100"
			},
			"scroll": {
				"direction": "up",
				"min-amount": "0",
			        "max-amount": "10",
			        "speed": "100",
			}
		}
        </script>
</amp-behavior-pattern>

<amp-state id="top-unit-state">
        <script type="application/json">
	        {
	                "collapsed": {
                               "pixels": "0px"
                        },
      			"expanded": {
	        	        "pixels": "300px"
      			}
    		}
        </script>
</amp-state>

<amp-iframe 
        width="100%" 
        height="0px"
        [height]=”top-unit-state[height].pixels”
        on="fast-upscroll-top:AMP.setState({"height":"expanded"})">

	<!--some content-->

</amp-iframe>
```

## Additional Details

Behaviors are assessed in the order that they are configured in each amp-behavior-pattern component. In the example provided, the user must first scroll between 50 and 100% of the way down the screen; then, scrolling up to between 0 and 10% of the way from the top will trigger an event call on the behavioral pattern.

### Supported Behaviors

Combinations of the following behaviors can be used to detect disengagement behaviors. Some behaviors require configuration parameters which are listed accordingly.

**scroll**: user scrolls through page content 
- direction: Upwards or downwards
- min-amount: upper bound of window that user must be scrolled to. Measured in % of total page height.
- max-amount: lower bound of window that user must be scrolled to. Measured in % of total page height.
- speed: scroll speed in pixels per millisecond

**inactivity**: time elapses without any user input, after which this behavior will match in the pattern
- min-duration: number of seconds to wait

**reactivity**: time elapses without any user input; upon next user input, this behavior will match in the pattern
- min-duration: number of seconds to wait

**hover**: user hovers on a certain element with their mouse cursor
- element-id: ID of element to detect hover on
- min-duration: minimum amount of time user must hover on element

**input-end**: user finishes typing in an input field; determined by some amount of time elapsing after their last inputted character
- element-id: ID of input field
- min-duration: seconds that must elapse after last input

**backbutton**: user clicks on browser back button
**tab-unfocus**: user focuses off of current tab

**Comment by rudygalfi** [comment]
cc @ericlindley-g @aghassemi @jasti

**Comment by jasti** [comment]
@miquelferrandiz thanks for the ITI. 
What are all the possible iframes UXs? (e.g. showing an interstitial, shifting content down to accommodate new content, etc) Some examples from non-AMP pages would be really helpful.

**Comment by ericlindley-g** [comment]
Chiming in a bit late with a couple thoughts:

If I understand correctly, this is a request to collect data (full list in "supported behaviors" aboive), in order to determine a level of "disengagement" sufficient enough to display ads that disrupt the experience of engaged readers, like blocking modals.

+1 to Vamsee's ask to catalog the behaviors that are on the table to be deemed acceptable (I wouldn't think that AMP would allow blocking modals, but there may be a compelling case for some UIs in the right user context)

If there are acceptable UIs like this, another question would be: who would determine the state of "engagement", and how would that be done? I don't think third-parties would be allowed to determine the state of (dis)engagement in a black box, but I could imagine a mechanic where a transparent heuristic is implemented in the AMP runtime, that could then grant permission to a limited set of elements that ensure good UX (i.e. no multiple modals that have to each be closed, etc)

**Comment by miquelferrandiz** [comment]
@jasti sure, here are a few examples geared for mobile. Let me know if desktop is of interest as well:

[Exit Modal](http://www.cnn.com/world/?qbxtest619615
) - will activate upon detecting the following disengagement behaviors:

- read through the article, then scroll back up the page
- press the browser back button

We've also run similar modal insertions on the reactivity and inactivity triggers.

[Upscroll, Shift Content Down](http://www.cnn.com/2017/11/20/africa/zimbabwe-military-takeover-strangest-coup/index.html#qbxtest589437
) - will activate upon detecting the following disengagement behaviors:

- scroll down through article, then back to top of page

[End of article, Insert Inline](http://www.cnn.com/2017/11/20/africa/zimbabwe-military-takeover-strangest-coup/index.html#qbxtest642024) - will activate on the following disengagement behaviors:

- scroll to end of article

We've also run similar inline insertions on the reactivity trigger, essentially showing an ad inline with content when the user returns to it.

@ericlindley-g - I am happy to provide direction on what is considered engagement / disengagement. Much of the work we do at BounceX is focused on understanding engagement levels based on user behavioral patterns, and we've spent several years collecting data, analyzing it, and running tests based on our findings. Let me know what information I can provide here.

**Comment by jasti** [comment]
@miquelferrandiz Unfortunately interstitials (anything that blocks primary content on the page) and resizing without explicit user action are disallowed in AMP for user experience reasons. 
https://github.com/ampproject/amphtml/blob/master/ads/README.md#ad-resizing

Specifically for End of article, Insert Inline - @ericlindley-g may have an opinion on how/ if it's possible to implement it using infinite scroll as long as it doesn't reflow user visible content on the page.

**Comment by ericlindley-g** [comment]
Good call on thinking about infinite scroll in this context — we're working on supporting infinite scroll for documents (so a new one loads as you near the end of the first one). You could imagine inserting an ad between each set of two documents (again, as long as it doesn't obstruct or reflow content on the page). However, this mechanic would likely be supported for all ad types, and be independent of the type of engagement pattern demonstrated by the user (unless there are other ideas for how this could work).

**Comment by jasti** [comment]
Closing for now due to inactivity. @miquelferrandiz please reopen if you'd like to discuss this issue further. Thanks.

**Comment by miquelferrandiz** [comment]
Hi @jasti - I see, what is explicit user action defined as here?

@ericlindley-g thanks, that makes sense for end of article. That said, seems like a specific implementation for what would ideally be a more general feature; how would this be adapted to other positions on the page, or other combinations of behavioral patterns?

**Comment by jasti** [comment]
@miquelferrandiz  "explicit user action" means an action where we don't need to infer if a user *might* choose to interact with the an element. More specifically, a click/ touch.

**Comment by miquelferrandiz** [comment]
@jasti understood, thanks for clarifying.

@ericlindley-g - any thoughts on how we might be able to adapt the infinite scroll approach to other locations on the page or other combos of behavioral patterns?

**Comment by ericlindley-g** [comment]
@miquelferrandiz No real ideas on my end that accord with AMP's UX guarantees (content doesn't jump around or block other user content without user interaction). The only thing I could think of is either a refresh of existing ads or addition of new ads or CTAs above the current viewport, so they'd be visible when the user scrolls back up, but wouldn't affect the current viewport at any time—but I'm not sure the payoff would be worth implementing the feature there.
