### ISSUE TITLE
Invalid URL protocol 'fb:' for attribute 'href' in tag 'a'.

### ISSUE THREAD

**Issue by AbdulSamadKt** [ampproject/amphtml#11824]
I got an html tag error on Google webmaster tools when I link to my Facebook page using this structure "fb://page/id" on my amp based website.

The error shows **Invalid URL protocol 'fb:' for attribute 'href' in tag 'a'**. Please help me to solve the issue. Can you whitelist Facebook links which using the structure "fb://page/id"? 

The advantage of using <a href="fb://page/my-id">Facebook</a> is when someone click on the link from mobile browser, it opens Facebook app instead of open the link in browser.

Thank you so much

**Comment by Gregable** [comment]
Is there a facebook public document somewhere describing what the fb://
protocol URLs are for?

I tried to find one just now, but only see references to it being an
internal API for the facebook app itself.

**Comment by dvoytenko** [comment]
Aren't http protocol works just the same? Also, what's the fallback when native app is not there?

/cc @cvializ

**Comment by cvializ** [comment]
Yeah the official documentation on this is either non-existent or difficult to find, for fb and whatsapp. And the official docs from iOS and Android that I can find seem to indicate that plain HTTP links should deep link if the app is installed. I vote to close as WAI

**Comment by Gregable** [comment]
Closing this issue unless we can find a documentation link provided for the protocol.
