### ISSUE TITLE
amp-analytics should be allowed as a sibling of amp-story

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#11836]
We should update the validator so that amp-analytics can still be used as a child of <body> when the document is a standalone amp-story.

**Comment by rudygalfi** [comment]
cc @newmuis

**Comment by rudygalfi** [comment]
@alanorozco Can you confirm that things work OK if amp-analytics is nested inside of amp-story?

We can decide to leave things as-is and possibly relax later for multi-story cases (because this definitely doesn't make sense for multi-story).

**Comment by newmuis** [comment]
We should verify this works before developer preview.  Once verified, this can just be closed.

**Comment by newmuis** [comment]
Verified in an existing document that the analytics pings are being sent when `<amp-analytics>` is embedded as a child of `<amp-story>`, by using the network tab of Chrome DevTools.
