### ISSUE TITLE
amp-story-desktop does not enforce that inactive pages are shown offscreen

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#11849]
We normally push pages offscreen for prerendering, but `amp-story-desktop` allows some of these pages to actually be onscreen, as we translate them by a fixed amount to push them offscreen.  As a result, the user can see a pile of inactive pages at the right of their screen, if their window is big enough or their resolution is high enough:

![screen shot 2017-10-17 at 10 42 35 am](https://user-images.githubusercontent.com/1651960/32174723-02d95f6a-bd59-11e7-8a88-f7738ce03bf2.png)

We should find a way to ensure that the pages actually get offscreen and not just a fixed distance away.

**Comment by dvoytenko** [comment]
@newmuis @choumx would you mind assigning this issue a milestone?

**Comment by prateekbh** [comment]
how do i reproduce this on my mac?

**Comment by newmuis** [comment]
I'm thinking zooming out in the browser might do it?  Or use/emulate a higher resolution screen, perhaps?

**Comment by prateekbh** [comment]
I wasn't able to see the stacked cards but I see we translateY to achieve something similar.

https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/0.1/amp-story.css#L190

is this what we are looking to change also, will a simple change to 100vh suffice to fix this bug?

**Comment by newmuis** [comment]
I think the `translateY` works because it's only used in the non-desktop (mobile) UI, where 100% of the parent is equal to 100vh.

I'm not sure where we do the x-axis positioning in the desktop UI; @cvializ do you know?

**Comment by cvializ** [comment]
I think for the non-zoomed case it didn't need vertical repositioning, so I didn't add anything special for that. It would be in the `amp-story-desktop.css`.

To hide the stack after the next card, you should be able to add `opacity: 0` to the rule:
```css
[desktop] amp-story-page[active] + amp-story-page ~ amp-story-page {}
```

**Comment by newmuis** [comment]
It's worth checking out whether the core runtime actually fetches resources for things that have no opacity or visibility.  If not, then we'll need to stick to translation offscreen.
