### ISSUE TITLE
Handle screen orientation changes for amp-story

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#11844]
`amp-story` is best viewed in portrait mode, for mobile form factor devices.  We should show a placeholder screen in landscape orientation on mobile devices:

![mock of placeholder screen](https://user-images.githubusercontent.com/1651960/32172575-79d25236-bd52-11e7-81fb-43c754ba0f15.png)

**Comment by newmuis** [comment]
Note that this should only be done for `amp-story` components that have the `standalone` attribute.

**Comment by dvoytenko** [comment]
@newmuis @choumx would you mind assigning this issue a milestone?

**Comment by prateekbh** [comment]
QQ: `amp-story` has a max-width associated with it which makes the overlay difficult. Do you think we should move it to `amp-story-page` and bookend and other elements separately?

**Comment by newmuis** [comment]
I think now that the desktop experience is the default, we can just remove that max-width/height.  It was meant to be a temporary measure anyway.

**Comment by prateekbh** [comment]
cool, it makes stuff on ipad pretty wierd

**Comment by newmuis** [comment]
Then we should file and fix those separately; there shouldn't be an experience that is centered in the middle of an otherwise blank page
