### ISSUE TITLE
Lock screen orientation to portrait on mobile devices for amp-story standalone

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#11845]
For `amp-story` components with the `standalone` attribute, we should lock the screen orientation to portrait on browsers that support it.  See https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/Managing_screen_orientation

**Comment by dvoytenko** [comment]
@newmuis @choumx would you mind assigning this issue a milestone?
