### ISSUE TITLE
Create a responsive desktop version of the amp-story bookend

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#11847]
A responsive desktop UI for `amp-story` was introduced in #11714; we should also convert the bookend to a desktop UI.

Mocks TBD

**Comment by dvoytenko** [comment]
@newmuis @choumx would you mind assigning this issue a milestone?

**Comment by newmuis** [comment]
Looks like @alanorozco actually already did this.   Thanks Alan!
