### ISSUE TITLE
Polish amp-story-desktop experiment

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#11848]
- [x]  Pages should be vertically centered (currently have a `112px` top/bottom margin, which is not necessarily vertically centered.
- [x] Share button should have `background-color: rgba(255, 255, 255, 0.2)` instead of `background-color: rgba(255, 255, 255, 0.25)`
- [x] Share button should have `color: #fff` (currently inherits black color)
- [x] Share button should have `font-size: 12px` instead of `font-size: 16px`
- [x] There should be an overlay that has `background-color: rgba(0, 0, 0, 0.15)` above the background images of the story (perhaps this can go inside `i-amphtml-story-background-container` with a higher z-index than the `i-amphtml-story-background` images themselves?)
- [x] Page aspect ratio should be fixed at 9:16
- [x] System layer icons can be increased in size from `40px` to `56px`
- [x] Progress bar segments should have rounded corners
- [x] Progress bar segments should be spaced `4px` apart
- [x] The page should never be scrollable horizontally or vertically
- [x] There should be gradients on all four sides: behind the top header, behind the bottom bar, behind everything to the left of the current page, and behind everything to the right of the current page

**Comment by prateekbh** [comment]
>Progress bar segments should have rounded corners

Can you plz explain this?

currently it looks like this
<img width="380" alt="screen shot 2017-10-31 at 9 00 41 pm" src="https://user-images.githubusercontent.com/5960497/32232673-955738d2-be7e-11e7-849d-0b1278fd4c77.png">

**Comment by prateekbh** [comment]
plz mark 2,3,4 as done

**Comment by newmuis** [comment]
@prateekbh Can you mention which PR fixes 2, 3, and 4?

**Comment by prateekbh** [comment]
#11863 fixes it

**Comment by newmuis** [comment]
>Progress bar segments should have rounded corners

@prateekbh This means that both `i-amphtml-story-page-progress-bar` and `i-amphtml-story-page-progress-value` should have the correct `border-radius` (and `i-amphtml-story-page-progress-bar` should probably also have `overflow: hidden`)

**Comment by prateekbh** [comment]
> The page should never be scrollable horizontally or vertically

@newmuis for this point, does our this solution suffice?
https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/0.1/amp-story.js#L171

**Comment by newmuis** [comment]
I believe so, yes.

**Comment by prateekbh** [comment]
Can you please mark 1, 5, 7, 8, 9, 10 as marked bu the PR #11886

**Comment by dvoytenko** [comment]
@newmuis @choumx would you mind assigning this issue a milestone?

**Comment by prateekbh** [comment]
#11909 fixed number 6. please mark it

**Comment by newmuis** [comment]
@prateekbh fixed the last one with #11951
