### ISSUE TITLE
Blacklist `on` attribute for <amp-story standalone>

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#11855]
The AMP actions/events system would allow developers to override performance and usability constraints that are baked into AMP story (e.g. playing offscreen videos, navigating to external URLs, submitting form data, etc.)

I think we should consider preventing this entirely; a naive way of doing so would be to blacklist the `on` attribute in validation.

Open to thoughts; /cc @choumx @dvoytenko @alanorozco @prateekbh

**Comment by choumx** [comment]
Disallowing `on` attribute SGTM.

**Comment by newmuis** [comment]
@chenshay Is it possible for us to blacklist this for the entire document if the document contains an `<amp-story standalone>` element?  In other words, not just for descendants of `amp-story`, but even if publishers put it on `<body>`, it should be invalid if there is an `<amp-story standalone>` in the document?

If that's not possible (or if that is difficult), we can also just do this for direct or indirect descendants of `<amp-story standalone>`.

**Comment by dvoytenko** [comment]
@newmuis @chenshay would you mind assigning this issue a milestone?

**Comment by Gregable** [comment]
Why would we not want to have the runtime handle this instead (or in addition)? The `on` attribute has no meaning in HTML, only to the runtime.

**Comment by newmuis** [comment]
The only reason is to give publishers a heads up that what they're doing is illegal, rather than silently failing.  We can call this out in development mode, but it seems less likely that such an error would be seen.

**Comment by newmuis** [comment]
@bpaduch once #12757 goes in, you won't be able to use [AMP actions and events](https://github.com/ampproject/amphtml/blob/master/spec/amp-actions-and-events.md) with `amp-story`.  What's the right way to document that?  A note on the actions/events docs that says "not compatible with amp-story"?  Or a note on the amp-story docs that says "not compatible with actions/events"?

**Comment by bpaduch** [comment]
I would suggest both to cover both angles.

**Comment by newmuis** [comment]
This won't be able to get in before the developer preview; my suggestion is to update the documentation first, and enforce it later.

**Comment by choumx** [comment]
Related: #13192 adds a document-level whitelist for actions with a `<meta>` tag in the document head. Perhaps we can use a blank whitelist and enforce that at the validator level (not sure if such a validator rule exists yet though).

**Comment by newmuis** [comment]
Can we update the whitelist?  Because we could also dynamically insert a blank whitelist at runtime.

**Comment by choumx** [comment]
Racy and the error message will probably be confusing, but doable. A separate amp-story-only solution might be more developer-friendly.
