### ISSUE TITLE
Add a screen that indicates that the user's browser is unsupported by amp-story

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#11853]
`amp-story` does not yet support all browsers that AMP generally supports.  Until we achieve parity, we should add a screen that tells a user if they are using an unsupported browser by checking the features we need with [@supports](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports) or [CSS.supports](https://developer.mozilla.org/en-US/docs/Web/API/CSS/supports) or the appropriate checks for whichever JavaScript functionality we depend on.

Mocks TBD

**Comment by choumx** [comment]
Which browsers are not supported and which features are they lacking? We should publicly document this in `amp-story.md`.

**Comment by newmuis** [comment]
We don't have this list, but `amp-story` does use some fairly cutting edge features:

- [CSS Grid](https://caniuse.com/css-grid)
- [Web Audio API](caniuse.com/audio-api)

**Comment by dvoytenko** [comment]
@newmuis @choumx  would you mind assigning this issue a milestone?

**Comment by newmuis** [comment]
Currently, our supported browser list looks like:

- Android Chrome: 57+
- Android Stock Browser: 62+
- Android Samsung Browser: 6.2+
- Android UC Browser: <unsupported>
- iOS Safari: 10.3+
- iOS Chrome: 57+
