### ISSUE TITLE
Media playback is not always tied to user gesture

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#11856]
When automatically advancing (e.g. after a fixed amount of time) between two `amp-story-page` components that both contain media, the media does not always play on the second page, depending on the browser.

My guess is that this is because there is no gesture tied to the advancement, so the browser does not consider the media `play()` invocation to have been caused by a user gesture.  Perhaps there's a way for us to hold onto the user's previous gesture to tie that gesture to the call to `play()`?

/cc @aghassemi @choumx @prateekbh @alanorozco

**Comment by aghassemi** [comment]
Reusing an existing "blessed" tag is a workaround that YouTube uses. Would only work for `amp-video`, amp-audio` and there will be implications on dynamically changing `src` regarding reploading.

Another option might be on the first user-interaction `play` is called on ALL media in all pages but immediately paused. This should bless them for a subsequent `play` call. One issue with this is that iOS can only keep certain number of videos in paused state (hardware specific number).

**Comment by newmuis** [comment]
Thanks @aghassemi!  Only working for `amp-audio` and `amp-video` should be fine.

Can you elaborate on the implications?  Are you saying once we've "blessed" a media element by playing it, changing its source will "unbless" it?

Playing (and subsequently pausing) all videos also sounds like it could work, although I'm not sure how iOS implements its cap.  e.g. if we have 10 pages (each with 1 video) and iOS caps at 5 videos, we would certainly want to make sure that the current page and its closest 4 neighboring pages are the 5 videos that actually get kept, not the last 5 videos in the story.

**Comment by aghassemi** [comment]
@newmuis yes changing source of an already bless tag won't unless it and it can keep playing content without new user interaction required. Big drawback of this approach is not being able to do preloading.

Not sure how iOS behaves when it reaches the max, I assume it would unload based on a first-played-first-evicte approach but definitely worth testing.

**Comment by dvoytenko** [comment]
@newmuis @aghassemi would you mind assigning this issue a milestone?

**Comment by newmuis** [comment]
I created https://jsfiddle.net/avx2te23/4/ to test having pausing the video element initially, then subsequently playing it after a delay (which is analogous to what happens in the auto-advance case in the `amp-story` extension).

Tested Mac OS Chrome 61.0.3163.100 and Android Chrome 62.0.3202.73 and it looks so far like `muted autoplay` is enough to bless the video.  I will continue to test other browsers, and if this works, we can modify the extension to only try to play `autoplay` videos (which semantically makes sense anyway) and update the documentation accordingly.

**Comment by newmuis** [comment]
Additionally works on iOS Safari 10.0.3 and Android Firefox 56.0

**Comment by newmuis** [comment]
Oddly, `<video>` tags don't show up for me at all on UC Browser 11.0.0.1016 Android pf139 or Samsung Internet Browser Beta (version 6.2.01.7)

**Comment by newmuis** [comment]
Let's try this as an approach.  For the time being, since user interaction is not possible within `<amp-story-page>` elements, we can actually validate that all `<amp-audio>`and `<amp-video>` elements have the `autoplay` attribute specified (filed #12067 for the validator change).  We can also change the runtime to only attempt to play `autoplay` media (this issue will track the change to the `amp-story` extension).  We can relax the validator restriction later, if we decide to allow videos that can have interaction.

@aghassemi can you verify that `amp-video` will automatically add `playsinline` and `muted` if `autoplay` is specified?  And `amp-audio` will automatically add `muted`?

**Comment by newmuis** [comment]
Okay, as a quick update: The `autoplay` attribute helps because `amp-video` will use that to mute the underlying `video` by default.  This, however, does not help in the case of unmuted videos.

Per @aghassemi's suggestion, we can call `play()` on all videos when the user taps the unmute icon, and subsequently `pause()` any videos that shouldn't be playing.  This will bless them for future automatic playback.

However, we don't want to require that ALL media elements exist in memory all the time.  We can instead keep a pool of these media elements and swap them in/out of the DOM.  We can perhaps start off with a fixed-size pool; as an optimization we might be able to calculate the size of the pool at build time, based on how many media elements would be needed to load a page and preload subsequent pages.

**Comment by newmuis** [comment]
Put together this [JsFiddle](https://jsfiddle.net/4dv8a9cc/5/) to test out the maximum video limitation on iOS Safari.

Looks like the `.error` property gets set to `MEDIA_ERR_DECODE` for videos that are created beyond the limit.  It also looks like it is last-played first-evicted (i.e. on my device, where the limit is 16 videos, when the 17th video is added, it immediately fails, and so on, leaving the first 16 videos intact).
