### ISSUE TITLE
Show equalizer icon on amp-story videos containing sound

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#11857]
The audio icon *is* sometimes displayed even though the page *does not* have audio, and the audio icon is sometimes *not* displayed even though the page *does* have audio.

The definition we're using for whether the page has audio is found in [page-element.js](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/0.1/page-element.js#L300) (copied below):

```
mediaElement.mozHasAudio ||
        Boolean(mediaElement['webkitAudioDecodedByteCount']) ||
        Boolean(mediaElement.audioTracks && mediaElement.audioTracks.length);
```

This is not foolproof and doesn't work cross-browser.  We can instead use a `ScriptProcessorNode` in [audio.js](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/0.1/audio.js) and check when audio is actually being produced by some source on the page, and display the icon at that time.  At that time, we can also add a `has-audio` attribute or CSS class to the page so that we don't have to recalculate this.

**Comment by dvoytenko** [comment]
@newmuis would you mind assigning this issue a milestone?

**Comment by choumx** [comment]
@sanjsanj Feel free to give it a go! Let me know if you have any questions.

**Comment by sanjsanj** [comment]
Awesome, cheers @choumx !

**Comment by sanjsanj** [comment]
@newmuis I've had a look at the `ScriptProcessorNode` but can't see how to use it to detect if audio is being played.  I'll continue to research it and the WebAudio API but if you have any guidance for me that would be very helpful please!

Also do you know in what circumstances the icon wasn't functioning correctly?

**Comment by sanjsanj** [comment]
@choumx I'm not able to figure this one out on my own and not managed to get any advice on how to approach it either.  Probably best to unassign it from me for the timebeing.  If I have a brainwave or do get some suggestions then I'd be happy to have another go but it's probably best left to someone that has more experience with the workings of the WebAudio API and its implementation here.

**Comment by choumx** [comment]
@sanjsanj Sorry about the lack of communication! You're right that the premise is to use `WebAudio` to detect if sound is playing, but this may require some refactoring. The reporter is on leave until the new year so let me find a different issue for you. Thanks for being proactive and for your continued contributions! 👍

**Comment by newmuis** [comment]
This can track adding the equalizer icon to the video; the data of whether the video actually contains sound can be tracked in #11940.

**Comment by newmuis** [comment]
Closing this because there is no additional work to be done in `amp-story`; use #15571 to track this being supported by `amp-video` for videos without controls.
