### ISSUE TITLE
Support enabling AMP experiments for visual diff tests

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#11854]
Enabling AMP experiments in the JS of the bootstrapped test does not seem to be working, and the test also does not seem to return true for `getMode().test`, so the experiment check cannot be bypassed this way in code.  These issues are blocking #11682.

Is there a framework-supported way to enable an AMP experiment before executing a visual diff test?

**Comment by dvoytenko** [comment]
@newmuis would you mind assigning this issue a milestone?

**Comment by rsimha-amp** [comment]
@newmuis We run `gulp build` and `gulp serve` before running the visual tests for PRs, while we run `gulp dist --fortesting` and `gulp serve` before running them on `master`.

I just took a look at `src/mode.js` and noticed that `test` relies on `IS_DEV`, which might be set to `false` when we merely do `gulp build`. This could be why you're not seeing the right mode in your test page.

Could you try this locally by running `gulp dist` and see if the correct mode is returned? If so, we might need to change the way we build before running visual tests.

**Comment by rsimha-amp** [comment]
@erwinmombay I think we need to expose a way to make `IS_DEV` true with `gulp build`, either via a flag, or by default. Can you think of any reason for not doing so?

**Comment by rsimha-amp** [comment]
Scratch the above. There is already a supported way of setting `localDev` to `true` via `gulp build --fortesting`. Updating documentation and `pr-check.js` should do the trick.

@newmuis I assume `localDev == true` is a sufficient trigger to enable your experiment, correct?

**Comment by newmuis** [comment]
The more I think about it, I think we really should have support for the experiments themselves, rather than relying on mode.  Ideally, we could even set up visual diff tests for the experiment-disabled behavior and the experiment-enabled behavior separately.  For `amp-story`, these both have UIs that we would want to keep from regressing.

**Comment by rsimha-amp** [comment]
Gotcha.

@newmuis Can you elaborate on which experiment you'd like to enable, what you already tried (that didn't work), and what kind of mechanism you're envisioning (that's independent of `mode`)? 

@erwinmombay Do you know if there's a way to enable an AMP experiment today after running `gulp build`?

**Comment by newmuis** [comment]
For enabling the experiment independently of `mode`, I tried:

- [Toggling the `amp-story` experiment in `<body>`](https://github.com/ampproject/amphtml/pull/11682/commits/3bd9ad343ce63fb68daf2ace64404f0b5f03d116)
- [Toggling the `amp-story` experiment in `<head>`](https://github.com/ampproject/amphtml/pull/11682/commits/960b99f33c9d2041ec8a8ac9d17d33018123ec1f)
- [Manually setting the value of the experiment cookie in `<head>`](https://github.com/ampproject/amphtml/pull/11682/commits/3a499972f21d894a43734a4ac768fea602ca1fca)

Ideally, one of these would just work, but I would also be fine with specifying an array of experiment names in the [visual-tests.json](https://github.com/newmuis/amphtml/blob/master/test/visual-diff/visual-tests.json) that has Capybara set the experiment cookies.  For example:

```
{
  "url": "examples/visual-tests/amp-story/amp-story.amp.html",
  "name": "amp-story",
  "loading_complete_css": [
    ".i-amphtml-story-standalone"
  ],
  "experiments": [
    "amp-story",
    "amp-story-desktop",
    "-unwanted-experiment"
  ]
}
```

**Comment by rsimha-amp** [comment]
Gotcha. Fix coming up via the functionality in https://github.com/teampoltergeist/poltergeist#manipulating-cookies.

**Comment by rsimha-amp** [comment]
With #12110, it's now possible to selectively enable experiments from `visual-tests.json` for each test page.

**Comment by danielrozenberg** [comment]
For posterity: this feature has been removed. You can set the experiment for a single page using a `<meta>` tag in your document. See: https://www.ampproject.org/docs/reference/experimental#enable-an-experiment-for-a-particular-document

See rationale for removing this feature in https://github.com/ampproject/amphtml/pull/17139#issuecomment-409022374
