### ISSUE TITLE
Whitelist additional attributes on amp-story-grid-layer direct children

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#11851]
#11753 adds new attributes that can appear on direct children of `amp-story-grid-layer`.  In the validator, these attributes should be treated the same way as the existing `grid-area` attribute.  The new attributes are:

- align-content
- align-items
- align-self
- justify-content
- justify-items
- justify-self

**Comment by dvoytenko** [comment]
@newmuis would you mind assigning this issue a milestone?

**Comment by Gregable** [comment]
Validator changes are live everywhere.
