### ISSUE TITLE
Allow prerendering videos in the runtime

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#11868]
## Prerender mode
Runtime currently does not load any `<amp-video>` sources on prerender. This needs to change.

1- `amp-video` to append src or any `<source>` that point to a cache URL to the <video> tag during prerender.
We’ll check the presence of amp-orig-src to check if the video is cached
This is already invalid, so that’s good.
Poster is already rewritten.

2- `amp-video` to set preload attribute to auto IF 
Not explicitly set by the author AND
Step one above resulted in either src or at least one `<source>` to be set during prerender.
Because there could be a race condition between the layout and rendering callbacks. Why could we have a problem?

If there is a 404 error during prerender (e.g. cache not ready), runtime WILL NOT follow through origin but will remember which ones 404-ed.

## Render mode
During `layoutCallback()` amp-video need to:
1- Append any non-cached `<source>` to the `<video>`
2- Replace any 404-ed cached src and `<source>` with the original URL.
3- Keep monitoring cached Urls for 404s as there is no guarantee 404 would happen between prerender and render modes.

**Comment by aghassemi** [comment]
@choumx unlikely I get to this this week. moving to next sprint. If there is a big urgency, please let me know.
