### ISSUE TITLE
amp-story should require at least one amp-story-page

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#11870]
`<amp-story>` currently requires one child; its allowed children are currently `<amp-story-page>`, `<amp-analytics>`, and `<amp-pixel>`.  Since we don't validate the type of the child, technically this is a valid story:

```html
<amp-story standalone>
  <amp-pixel src=""></amp-pixel>
</amp-story>
```

If it's reasonable, we should enforce that `<amp-story>` has at least one `<amp-story-page>` as a child.

**Comment by Gregable** [comment]
We can implement, but can you give some more context?

Even if implemented, this would still be valid:

```
  <amp-story standalone>
    <amp-story-page id=id>
      <amp-pixel src=""></amp-pixel>
    </amp-story-page>
  </amp-story>
```

I don't think that the validator can successfully catch all versions of an empty document.

**Comment by newmuis** [comment]
Yep, that's fine.  To me, what you've posted is an empty story.  The original report is an invalid story.  It's analogous to a physical magazine or book with no pages (not even a cover), vs. a magazine that just has blank pages in it.

**Comment by newmuis** [comment]
This is done.
