### ISSUE TITLE
can we customize datepicker calendar design in amp (Google AMP) ? 

### ISSUE THREAD

**Issue by pratikvc** [ampproject/amphtml#11879]
In different android versions, different browser, the design of Datepicker calendar seems to be different. 

**To be more specific : can we have same design of Datepicker calendar in all browser and all android versions.**

Please check screenshots below:

![92f66b72cb5e9c5819c0ddc6604ecec0a56bcf859012e9520a pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/28097130/32226162-cb9e3bea-be6d-11e7-911b-37f1dc52857e.jpg)

![259ca0accd3cf7c5a80fcceefa39a63720b0b611103ecfefbb pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/28097130/32226165-cccba638-be6d-11e7-8c4d-cdd5af680c72.jpg)

![611a3aebfc88fa887007b6555b1fedcdf5b3d79b6b70be6e28 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/28097130/32226168-ce1b0808-be6d-11e7-999f-ea3e69f37bb5.jpg)

![f0299ca31c930e858054ca9c7754b24cbfe49ee603993a8913 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/28097130/32226172-cf531c9c-be6d-11e7-88a3-edf8521c42ec.jpg)

**Comment by cvializ** [comment]
Great question, and thank you for your feature request! We already have issue #6469 tracking our custom date picker effort, so I will close this issue as a duplicate.
