### ISSUE TITLE
Share buttons do not wrap if beyond viewport width

### ISSUE THREAD

**Issue by bpaduch** [ampproject/amphtml#11898]
In amp-story, when there are more share buttons than viewport width, the buttons do not wrap, and either are cut off or do not display on the screen.

Example: 6th button beyond screen width

![amp-story-share-buttons](https://user-images.githubusercontent.com/1012254/32290999-2938f9c6-bf12-11e7-9087-209c7b053cb3.png)

Example: Narrow screen, button cut off
![amp-story-share-buttons-narrow-screen](https://user-images.githubusercontent.com/1012254/32291137-8ec64db6-bf12-11e7-9957-77d57bfb06b3.png)

**Comment by dvoytenko** [comment]
@newmuis @choumx would you mind assigning this issue a milestone?

**Comment by newmuis** [comment]
This is actually intentional; the region is scrollable.  We should make that more apparent in the UI though.  @alanorozco can you follow up?

**Comment by alanorozco** [comment]
This is WAI. Will follow-up with UXD.

**Comment by hongwei1990** [comment]
Hey guys, I already emailed Alan. Please reference my screenshot here for the design solution. The last icon was designed to cut off and only shows 16px. Based on our recent user testing, users did scroll to see more options. We will run user testing for the new bookend design; I will follow up here if we need to treat the UI differently. 
<img width="1632" alt="screen shot 2017-11-15 at 1 58 57 pm" src="https://user-images.githubusercontent.com/33703058/32862529-36f403ac-ca0d-11e7-827e-27d66bf58b94.png">
