### ISSUE TITLE
Run the validator integration test against the checked in version

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1189]
We should leave the current test in place, but also run against the checked in version.

**Comment by Gregable** [comment]
I'm not sure I understand. We run the test on every commit, currently. Not sure if the travis bot is doing so automatically, but we're doing so manually.

**Comment by cramforce** [comment]
Currently the test runs against the production validator. Need to also run against head.

Specifically I'm talking about this test
https://github.com/ampproject/amphtml/blob/master/test/integration/test-example-validation.js
Should have been more specific.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
