### ISSUE TITLE
[Question] Why limit data structure for amp-list?

### ISSUE THREAD

**Issue by mauricionr** [ampproject/amphtml#11904]
Why limit data structure for amp-list? why every response should start with:

```JSON
{
"items": []
}
```
i'm consuming 3d party service and the response from this service is
```JSON
{
"top": [],
"middle": [],
"bottom": []
}
```

if i cannot use `amp-list`, it's possible to use `amp-state` + `amp-mustache` + `amp-carousel`?
or
if i cannot use `amp-list`, it's possible to use `amp-state` + `amp-mustache` + `amp-list`?

*i don't have acess to create an endpoint in the server and parse the data structure*

Thanks!

**Comment by choumx** [comment]
Thanks for your question Mauricio. `amp-list` supports an optional `items` attribute which you can use to specify which sub-state of the JSON response to render with.

Another option is to use `amp-state` to fetch JSON and `amp-list` to render it (with a `[src]` binding) as you mention.

**Comment by mauricionr** [comment]
could you provide an example @choumx ?

**Comment by choumx** [comment]
Docs for `items` attribute: https://www.ampproject.org/docs/reference/components/amp-list#items-(optional)

Example that has `[src]` binding with `amp-list`: https://github.com/ampproject/amphtml/blob/master/examples/bind/list.amp.html

**Comment by mauricionr** [comment]
Thanks @choumx !!

**Comment by bjalford** [comment]
@choumx any way of access the sharecount in this format? 

https://graph.facebook.com/?id=https://www.standard.co.uk/news/london/man-vs-food-london-restaurant-which-boasts-of-making-diners-vomit-at-their-table-angers-neighbours-a3678091.html

{
   "share": {
      "comment_count": 0,
      "share_count": 61
   },

**Comment by choumx** [comment]
Have you tried the `items` attribute I mentioned above?

```html
<amp-list items="share_count">
```
