### ISSUE TITLE
validator: template attribute required for <amp-story-grid-layer>?

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amphtml#11910]
There's a contradiction between how the validator processes the `<amp-story-grid-layer>` component, and the docs:

- the validator [requires the `template` attribute](https://github.com/ampproject/amphtml/blob/0f543a6dbc049f043498956555a98513994b61b0/extensions/amp-story/validator-amp-story.protoascii#L89)
- the docs [say it is optional](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/amp-story.md#template-optional)

**Comment by flaviori** [comment]
Just to clarify, template is a required attribute and there is no such thing such as template="custom" or similar, right? i.e., one has to necessarily pick one of the existing ones e.g., fill, vertical etc.

**Comment by choumx** [comment]
@flaviori That is correct. Closing since this was fixed with #12032.
