### ISSUE TITLE
SVG symbols do not display in amp-shadow on webkit

### ISSUE THREAD

**Issue by mattwomple** [ampproject/amphtml#11914]
## What's the issue?

SVG symbols do not display in iOS browsers when an AMP page is displayed using `AMP.attachShadowDoc()`. The symbols display fine in Chrome on Android.

## How do we reproduce the issue?

I've created a minimal example of an AMP page that displays an SVG symbol: [svg-in-amp.html](https://android.cmphys.com/temp/svg-in-amp.html). This page displays correctly in Chrome 61 on both Android 7.1 and iOS 10.3.3, as well as Safari 10 on iOS 10.3.3.

I've created another minimal example of the same AMP page above loaded using `AMP.attachShadowDoc()`: [svg-in-amp-shadow.html](https://android.cmphys.com/temp/svg-in-amp-shadow.html). The SVG symbol displays correctly in Chrome 61 on Android, but does not display in either Chrome 61 or Safari 10 on iOS 10.3.3.

## What browsers are affected?

- Safari on iOS: Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1
- Chrome on iOS: Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/61.0.3163.73 Mobile/14G60 Safari/602.1

## Which AMP version is affected?

1508896929494

**Comment by cvializ** [comment]
This is a Safari bug which applies to SVGs using the `<use>` tag, like your example. 
https://bugs.webkit.org/show_bug.cgi?id=174977 

I was able to get the SVG to render by using the SVG markup directly without using `<use>`. It's not ideal but it will work until the Safari bug is resolved.

**Comment by cvializ** [comment]
Closing since this issue ended up not being a problem with AMP and cannot be resolved by AMP
