### ISSUE TITLE
Provide amp-ima-video option to request ad on interaction instead of on page load

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#11916]
The default behavior of the amp-ima-video component is to request an ad on the AMP page load which has a negative effect of being counted as 'code served' even if there is no impression. 
We should build an non-default option to request the ad only after the user has interacted with the AMP page. 
An interaction is counted as: 
a) If the user begins to scroll the page 
b) If the user stays on the page even without scrolling for more than 3 seconds after the AMP page is finished loading.

We could have provided this option to request the ad only after the user clicks on the play button but that might be too slow from a user experience stand point and might cause significant bounce. 

CC @shawnbuso @aghassemi Thoughts?

**Comment by shawnbuso** [comment]
Seems reasonable. Does AMP currently provide something that tells me if the user interacted with the page (according to the requirements you listed)?

**Comment by jasti** [comment]
@zhouyx implemented the same thing for stick ads. Could you help please?

**Comment by jasti** [comment]
ping @zhouyx

**Comment by zhouyx** [comment]
Hey @shawnbuso 
Yes runtime provides few functions that you can use.

> a) If the user begins to scroll the page

Viewport [onScroll] 
(https://github.com/ampproject/amphtml/blob/master/src/service/viewport/viewport-impl.js#L517), can help detecting if user scroll the page. 

> b) If the user stays on the page even without scrolling for more than 3 seconds after the AMP page is finished loading.

To understand it better. @jasti What's the definition for AMP page finished loading? As every AMP component has been loaded, or runtime scheduling being idle for 3 seconds, or simply the page being visible for 3 seconds?

**Comment by shawnbuso** [comment]
Thanks for the info!

@jasti re: onScroll, do we want to request ads when the users scrolls no matter where the video player is, or only once the video is scrolled into the frame? If the latter, can you point me to some code I can re-use for that? I imagine that exists since we use it for things like video autoplay.

Also, ping @jasti for @zhouyx's question above.

**Comment by jasti** [comment]
Sorry for the delay.
@zhouyx I was suggesting it to be 'the earliest time we can, but not interfering the scheduler' - Closest is ' runtime scheduling being idle for 3 seconds'.
@shawnbuso The former. Just like sticky ads. Most video players are in the first viewport anyway.
