### ISSUE TITLE
AmpProject.org AMP Ad documentation 404s

### ISSUE THREAD

**Issue by bradfrizzell** [ampproject/amphtml#11917]
The following link on the AMP docs 404s: https://www.ampproject.org/docs/guides/ads/ads_getting_started 

To reproduce: 
1. Go to [Serving Ads on Amp](https://www.ampproject.org/docs/guides/ads_on_amp)
2. Click on "getting started"

**Comment by erwinmombay** [comment]
probly an issue for https://github.com/ampproject/docs/issues instead?

**Comment by bpaduch** [comment]
Looking into it and rerunning build; suspecting it's related to Grow - https://github.com/grow/grow/issues/629.

**Comment by bpaduch** [comment]
Thanks for reporting this!
Fixed for now; built with Grow 3.9.
