### ISSUE TITLE
amp-story: Migrate task tracking to GitHub

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#11927]
Now that `amp-story` is public, we should start using standard GitHub workflows for roadmap/milestone/sprint/task tracking. This will increase transparency and help answer questions like "when is analytics support coming? (#11924)".

Currently, all related tasks are labeled as `AMP Story` in the "Active Non-Sprint Tracked" milestone.

/cc @rudygalfi @newmuis @adelinamart @mrjoro

**Comment by camelburrito** [comment]
@choumx - can you add an assignee?

**Comment by choumx** [comment]
Fine. 😄

**Comment by newmuis** [comment]
Migrated to https://github.com/ampproject/amphtml/projects/35?card_filter_query=is%3Aopen
