### ISSUE TITLE
amp-story analytics variables in vendor-requests.json

### ISSUE THREAD

**Issue by acorretti** [ampproject/amphtml#11924]
Are `amp-story` variables _pageId_ and _pageIndex_ available as variables in the `vendor-requests.json` test file, in amp-analytics?

If so, under which handles? One would expect them to be `_page_id_` and `_page_index_`.

**Comment by choumx** [comment]
Thanks for reporting this Alfonso. Analytics support is currently planned to be a fast follow after dev preview. Stay tuned!

**Comment by choumx** [comment]
Correction: basic analytics support for `amp-story` is already available. Use `STORY_PAGE_ID` and `STORY_PAGE_INDEX` (#11528). 

Looks like we don't have public documentation for these yet. /cc @alanorozco
