### ISSUE TITLE
amp-story: Progress bar broken in dev channel

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#11921]
Progress bar always empty when navigating between pages.

Reproducible on canary (1509573857630). Not reproducible on prod (1508896929494).

/to @alanorozco @prateekbh

**Comment by prateekbh** [comment]
can you pull and check on master? this was fixed in yesterday's PR

**Comment by choumx** [comment]
@prateekbh Which PR?

**Comment by prateekbh** [comment]
https://github.com/ampproject/amphtml/pull/11897/files

**Comment by choumx** [comment]
Verified this was fixed by #11897. Need to cherry-pick this into current canary.
