### ISSUE TITLE
[Flying Carpet] Fallback not working as expected

### ISSUE THREAD

**Issue by raul782** [ampproject/amphtml#11925]
## What's the issue?

Using the fallback option for this extension `amp-fx-flying-carpet` doesn't work as expected.
I'd expect that if the ad is not loaded, the fallback option is displayed which doesn't happen.
Additionally if this gets fixed, I'd expect the fallback doesn't inherit the behavior of the above extension (the scrolling animation effect) and is rendered according to height of the fallback ad.

## How do we reproduce the issue?
Reduced test case:
http://jsbin.com/viqukusixi/edit?html,output

Steps to reproduce the issue:

1. Create a `amp-fx-flying-carpet` widget
2. inside the main container, add a fallback <amp-ad>, in the example above, I used an amp-img
3. If the initial <amp-ad> is not loaded, an empty space is displayed, while I should expect the fallback <amp-ad> to be rendered and without the scrolling behavior.

## What browsers are affected?

Tested on Chrome, Safair, Firefox on MacOS, Linux

## Which AMP version is affected?
AMP version: 1508896929494
I think this might have been broken for a while.

**Comment by jridgewell** [comment]
Hm, so right now, the flying carpet has no concept of a fallback because the carpet itself always "loads". I could easily see this extended to the collapsing behavior (carpets collapse when the ad fails to load) and making it display the fallback instead of collapsing.

This is a pretty simple change, would you like to make the PR?

**Comment by raul782** [comment]
Hi @jridgewell,

Yes please that would be great.

**Comment by raul782** [comment]
Hi @jridgewell, 
If you have time please let me know how can I help by creating a PR

Thanks!

**Comment by jridgewell** [comment]
Sorry about that:

1. We need to update [`#visibileChildren_`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.js#L181-L195) to exclude Elements with a `fallback` attribute from the count (`return false` for them).
2. We need to update [`#collapsedCallback`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.js#L162-L172) to check if we have a fallback when we've run out of "visible" children:
    ```js
      if (this.totalChildren_ == 0) {
        if (this.getFallback()) {
          this.toggleFallback(true);
        } else {
          return this.attemptCollapse().catch(() => {});
        }
      }
