### ISSUE TITLE
amp-iframe allow="microphone"

### ISSUE THREAD

**Issue by maxime-michel** [ampproject/amphtml#11937]
## What's the issue?

There is no `allow="microphone"` option for `amp-iframe`, yet it is going to be a necessary argument to the `iframe` itself soon:

> [Deprecation] getUserMedia (microphone) usage in cross-origin iframes is deprecated and will be disabled in M64, around January 2018. To continue to use this feature, it must be enabled by the embedding document using Feature Policy, e.g. <iframe allow="microphone" ...>. See https://goo.gl/EuHzyv for more details.

## How do we reproduce the issue?

1. access www.accordersaguitare.com with Chrome
2. open the Console and see the message

## What browsers are affected?

Firefox doesn't warn about this. Safari doesn't even support `iframe allow="microphone"` yet, see: https://bugs.webkit.org/show_bug.cgi?id=167430

## Which AMP version is affected?

1508896929494

**Comment by aghassemi** [comment]
related https://github.com/ampproject/amphtml/issues/11541

**Comment by maxime-michel** [comment]
Thanks!
