### ISSUE TITLE
Add documentation for Facebook Pixel

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#11932]
Facebook pixel support was added in #9449. We need to also include documentation here: https://github.com/ampproject/docs/blob/master/content/docs/guides/analytics_amp/analytics-vendors.md

cc @eduardogoncalves, who authored the pull request cited above.

**Comment by dvoytenko** [comment]
@rudygalfi pls triage

**Comment by rudygalfi** [comment]
Submitted PR cc @bpaduch @zhouyx @jasti
