### ISSUE TITLE
amp validator rejects [tooltip]

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#11947]
amp validator rejects [tooltip] with the following message:
  `The attribute 'tooltip' may not appear in tag 'span'.`
The CSS is applied as follows:

```
<p>
Beginning text <span tooltip='tool-tiptext'><a href='http://en.wikipedia.org/wiki/example'>Example</a></span> ending text.
</p>

```

```
[tooltip]:before {
    content: attr(tooltip);
    position: absolute;
    opacity: 0;
    transition: all 0.15s ease;
    padding: 10px;
    color: #333;
    border-radius: 10px;
    box-shadow: 2px 2px 1px silver;    
}

[tooltip]:hover:before {
    opacity: 1;
    background: #0379C4;
    color: #fff;
    line-height: 150%;
    font-size: 14px;
    margin-top: -50px;
    margin-left: 20px;    
}

[tooltip]:not([tooltip-persistent]):before {
    pointer-events: none;
}
```

Is there a problem with this structure? Am I missing the documentation that warns against this use?

If not, would you white-list this CSS structure on AMP Validator?

/jay gray

**Comment by choumx** [comment]
The issue is that `tooltip` is not a valid HTML or AMP attribute for `<span>`. Try replacing this with a CSS class instead. If you need to use custom attributes, prefix them with [`data-`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#attr-dataset).
