### ISSUE TITLE
FR: More flexible height-change requests

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#11945]
When an AMP component makes a resize request:

- Queue for resize
- If the user isn't scrolling:
--   And if the bottom of amp-list is in the viewport: 
---     wait until it isn't anymore, then resize and correct scroll accordingly (e.g. if the viewport is below amp-list)
--   If the bottom of amp-list is not in the viewport: just resize at will

Primary use case to support is a container-like layout for amp-list, where it can resize with good UX in more cases

Continuation of: https://github.com/ampproject/amphtml/issues/10230#issuecomment-342215212

**Comment by choumx** [comment]
Also we should make sure resize requests in fixed layer work reasonably: https://github.com/ampproject/amphtml/issues/10230#issuecomment-342259777

**Comment by lswang1618** [comment]
--- wait until it isn't anymore, then resize and correct scroll accordingly (e.g. if the viewport is below amp-list)

^doesn't this mean that whatever is in the viewport can move around without user interaction?

**Comment by aghassemi** [comment]
@lswang1618 if we correct for scrolling properly (Chrome has actually started doing this recently under their [Scroll Anchoring initiative](https://blog.chromium.org/2017/04/scroll-anchoring-for-web-developers.html)), it won't be noticed by the user.

**Comment by samouri** [comment]
I think we can close this now that [we support container layout](https://github.com/ampproject/amphtml/pull/27911) for `<amp-list>`
