### ISSUE TITLE
amp-story: Bookend triggers prematurely

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#11949]
Appears that bookend is triggering with 3 story pages left. Ping me for the sample document.

/to @alanorozco

**Comment by flaviori** [comment]
I believe this was caused by the presence of amp-analytics inside amp-story, which was treated as a page, but it has now been fixed right? However, there is a separate bug around the bookend currently.

**Comment by choumx** [comment]
@flaviori Yes this was fixed.
