### ISSUE TITLE
Confuse about link[rel="amphtml"]  

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#11955]
To whom it may concern:

I have already done my AMP page stuff and try to publish it.

According the following document
[Prepare for discovery](https://www.ampproject.org/docs/tutorials/create/prepare_for_discovery)

I should add **link[rel="amphtml"]** to my non-AMP page and add **link[rel="canonical"]** to my AMP page.

Here comes my question, what if I have different web address to server mobile and desktop device. 

Such as:
  *https://www.example.com/document.html (for desktop)
  *https://m.examole.com/document.html (for mobile)

Should I add **link[rel="amphtml"]** to both of them or just desktop version ?

Have a nice day.

Paul

**Comment by aghassemi** [comment]
@meistudioli Please see https://productforums.google.com/forum/#!topic/webmasters/fFQJC2m0OHs for a detailed answer to your question.

Also the same Webmaster forum is the best place to ask questions regarding Google search integration with AMP.

Closing the issue, please feel free to reopen if your question is not fully answered.

**Comment by meistudioli** [comment]
Hi, @aghassemi:

Thanks for helping. 

Paul
