### ISSUE TITLE
amp-youtube: "No cookie" option

### ISSUE THREAD

**Issue by saitho** [ampproject/amphtml#11956]
## What's the issue?

In some cases it might be necessary to embed a YouTube video without cookies (legal reasons et cetera). There is a way to embed the YouTube player without cookies with a special embed URL – you just have to add "-nocookie" between youtube and .com.
E.g. https://www.youtube-nocookie.com/embed/jpyHTTtddUo?enablejsapi=1

## Implementation proposal

- Add a new property "credentials" similarly to https://www.ampproject.org/docs/reference/components/amp-list#credentials-(optional)
- Add a new private method "getEmbedUrl()" that when this new property...
  - is not set: returns the URL that currently used (default)
  - is set: return the nocookie-url: https://www.youtube-nocookie.com/embed/${encodeURIComponent(this.videoid_ || '')}?enablejsapi=1
- use "getEmbedUrl()" in method getVideoIframeSrc_() (line 156 of current code)
- add property to documentation and update validation rules

## What browsers are affected?

None, as this is a new feature.

## Which AMP version is affected?

None, as this is a new feature.

**Comment by aghassemi** [comment]
@saitho Thanks, good feature to add. Would you be interested in contributing this feature by sending a PR? AMP is fairly streamlined for quick external contributions. If you are interested, checkout https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md to get started.

**Comment by saitho** [comment]
I already thought about that. :)

**Comment by aghassemi** [comment]
@sahirsait for the attribute, let's use `credentials` with values of `omit` and `include` instead of `nocookie`.(with default of `include`). This will align better with `amp-list` which already has such a mode.

**Comment by saitho** [comment]
That makes sense. I changed the name in the issue text.
