### ISSUE TITLE
AMP Pages UCBrowser GA PageViews not tracking

### ISSUE THREAD

**Issue by ashishdots** [ampproject/amphtml#11954]
We are running a eCommerce aggregator portal on WEB and WAP both. Recently we have migrated whole WAP pages to AMP. After migration, the GA sessions for UC Browser has been decreased by almost 95%. We have figured out some of the devices which are not sending the pageview event however the website is working fine in all other browsers. Any help to debug UC Browser for pageview event for AMP would be greatly appreciated.

Thanks,
Ashish

**Comment by rudygalfi** [comment]
Taking this off the 3P Ads & Analytics project. We should investigate to see if it's an issue on AMP side or UC Browser side.

**Comment by zhouyx** [comment]
Hey @ashishdots I just tested our ampproject.org page in UC browser. I saw the pageview pinged correctly. I am closing this for now, Please feel free to reopen if there's more information. Thanks.
