### ISSUE TITLE
No preview picture in NewsArticle with AMP 

### ISSUE THREAD

**Issue by 123michi19** [ampproject/amphtml#11958]
Hi,

No picture available in the news article. The logo as a picture is working fine. URL for the main picture is alright. It's an valid amp document (tested by the amp validator). 

<img width="253" alt="ampstructureddata" src="https://user-images.githubusercontent.com/33457773/32499872-10972fa2-c3d4-11e7-934a-5d135866a775.png">

That's the used code for the news article / structured data:

`   <script type="application/ld+json">{
"@context": "http://schema.org",
"@type": "NewsArticle",
"description": "In der letzten Staffel musste Daryl Dixon viel einstecken: Seine Freunde wurden vor seinen Augen getötet, wofür er sich selbst die Schuld gab, und er wurde von Negan gefangen genommen und gefoltert. Doch nun habe Dixon genug und werde sich für alles rächen, wie Norman Reedus (Triple9) im Interview mit Entertainment Weekly verriet. ",
"headline": "The Walking Dead - Staffel 8: Daryl würde jeden töten",
"author": "Sky",
"datePublished": "25 October, 2017",
"image": {
"@type": "imageObject",
"url": "http://www.sky.de/next/static/img/TWD-Staffel8-Daryl-Dixon-Sky-News-171025-16-9.jpg",
"height": "360",
"width": "696"
},
"publisher": {
"@type": "Organization",
"name": "Sky",
"logo": {
"@type": "imageObject",
"url": "http://www.sky.de/static/img/sky_17-03_logo-l_retina.png"
}      
}}
  
         
</script>`

Thx for your help

**Comment by honeybadgerdontcare** [comment]
@123michi19 could you share the amp document url?

**Comment by 123michi19** [comment]
@honeybadgerdontcare  Yes of course. 

http://www.sky.de/web/redaktion/static/amp/film-news-the-walking-dead-staffel-8-daryl-wuerde-jeden-toeten-151557.html

**Comment by honeybadgerdontcare** [comment]
@aghassemi This isn't cache related but carousel related. All images are fine in [cache version](https://www-sky-de.cdn.ampproject.org/c/s/www.sky.de/web/redaktion/static/amp/film-news-the-walking-dead-staffel-8-daryl-wuerde-jeden-toeten-151557.html).

**Comment by aghassemi** [comment]
@123michi19 You see seeing this image in preview part of https://search.google.com/test/amp ? If so, that preview always says "Your Image" and not the actual image.

**Comment by rudygalfi** [comment]
There was an internal issue. This should work now if you try again.

**Comment by 123michi19** [comment]
Thanks for your help, it works fine now :)
