### ISSUE TITLE
Expose standard UrlReplacements to the URL of an amp-iframe.

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1196]
This would e.g. allow sending the current referrer to the iframe.

Tasks
- in amp-iframe.js add dependency on url-replacements.js
- expand the iframe's URL using that service before setting it on the iframe.

**Comment by cramforce** [comment]
@mkhatib Would you be interested in taking this on? Similar to the `data-param-` bug you are currently working on.

**Comment by mkhatib** [comment]
Yes I can work on this. I assume this will only be also used for normal src not srcdoc, right?

**Comment by cramforce** [comment]
Yes

**Comment by sriramkrish85** [comment]
@mkhatib have you started on this?

**Comment by mkhatib** [comment]
@sriramkrish85 not yet no. Was planning to start today.

**Comment by mkhatib** [comment]
@cramforce I have the code for this ready, should I send another PR or just squash the change with the #1537  PR?

**Comment by rudygalfi** [comment]
It looks like #1537 is ready to merge. If you'd prefer to squash, bring it up on #1537 before someone merges. Else, separate PR.

**Comment by cramforce** [comment]
Decided that we will not do this.

**Comment by jpettitt** [comment]
@cramforce - can you elaborate on why this didn't happen?  It would have been quite helpful.

**Comment by cramforce** [comment]
Primary reason is that some use cases where this is useful like analytics should use a more specialized method instead.
