### ISSUE TITLE
amp-iframe how to aling center

### ISSUE THREAD

**Issue by dldl53** [ampproject/amphtml#11960]
does someone know how to align an amp-iframe in the middle of the page?
If I add it to a div with { text-align: center; } in the style in the header of my  amp-html page , it doesn't work

**Comment by aghassemi** [comment]
@dldl53 Since AMP is HTML, you can use various available approaches on the web to do layouts. 
For instance, you can use `margin: auto` to center a `div` and put the `amp-iframe` inside that div.
See https://codepen.io/aghassemi/pen/ZapVpq?editors=1001 for a sample.

**Comment by aghassemi** [comment]
Closing the issue as it is not AMP-related and hopefully the code snippet above can guide you.
