### ISSUE TITLE
Add warning to validator for use of useSameDomainRenderingUntilDeprecated and remote.html with DoubleClick

### ISSUE THREAD

**Issue by bradfrizzell** [ampproject/amphtml#11970]
Delayed fetch is being deprecated for DoubleClick on March 29 2018. See https://github.com/ampproject/amphtml/pull/11918 and https://github.com/ampproject/amphtml/issues/11834

We'd like to add 2 warning outputs to the AMP validator:

1. The AMP validator should warn that the attribute useSameDomainRenderingUntilDeprecated will no longer be supported on doubleclick amp-ad tags as of March 29 2018. 
Definition of flag: https://github.com/ampproject/amphtml/blob/master/ads/google/doubleclick.md#temporary-use-of-usesamedomainrenderinguntildeprecated-until-march-29-2018
2. Should warn if remote.html is in use, and the only amp-ad tags on the page are all doubleclick. this.win.document.querySelector('meta[name=amp-3p-iframe-src]')) returns the remote.html element, so if it is defined, remote.html is 'in use'

**Comment by Gregable** [comment]
Quick thoughts. 

This isn't typically the type of message we would consider using the validator for. It's not a "will soon become an error" type of warning, as we probably will not want to invalidate a document for incorrectly configured ads.

We don't currently have any validator rules that work similarly to what you are proposing. We don't parse json in the validator, for example. Both of these warnings would require significant work.

**Comment by bradfrizzell** [comment]
That's fine, we can skip adding this. Thanks for the quick response.
