### ISSUE TITLE
Adwords version of amp-call-tracking

### ISSUE THREAD

**Issue by sucharithav** [ampproject/amphtml#11973]
Would be nice to have an adwords-specific version of amp-call-tracking (https://support.google.com/adwords/answer/6095883) that abstracts away call tracking URL generation. This is an option:

<amp-call-tracking type="googleadwords">
  <script type="application/json">  
      "vars": { 
          "googleConversionId": <conversion id>,
          "googleConversionLabel": <conversion label>,
          "fallbackNumber": <fallback number>
       }
  </script>
  <a href="tel:123456789">+1 (23) 456-789</a>
</amp-call-tracking>

Where the call tracking URL generated would look something like this: https://www.googleadservices.com/pagead/conversion/<conversion_tracking_id>/wcm?ak=<conversion_tracking_id>&cl=<conversion_label>&fb=<fallbacknumber>&mode=1 (mode=1 so the endpoint can return a json for AMP)

**Comment by sucharithav** [comment]
cc @jasti

**Comment by sucharithav** [comment]
The example should look like: (had to escape the amp-call-tracking tag)

&lt; amp-call-tracking type="googleadwords"&gt;
  <script type="application/json">  
      "vars": { 
          "googleConversionId": <conversion id>,
          "googleConversionLabel": <conversion label>,
          "fallbackNumber": <fallback number>
       }
  </script>
  &lt;a href="tel:123456789">+1 (23) 456-789&lt;/a>
&lt;/amp-call-tracking&gt;

**Comment by rudygalfi** [comment]
Can anyone weigh in on the priority of this? cc @lswang1618

**Comment by lannka** [comment]
Is the proposal here to support a different config format? I'm actually wondering if a JSON config is any easier than writing a URL.

**Comment by lannka** [comment]
Discussed offline. The solution will be for AdWords to provide a code snippet for users to copy-paste.
