### ISSUE TITLE
Make presubmit check on cookie smarter

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#11978]
See https://github.com/ampproject/amphtml/pull/11968#issuecomment-342676012

**Comment by rsimha-amp** [comment]
Remove existing checks of this sort: https://github.com/ampproject/amphtml/blob/master/build-system/tasks/presubmit-checks.js#L363
Add a check of this sort: https://github.com/ampproject/amphtml/blob/master/build-system/conformance-config.textproto#L181
