### ISSUE TITLE
AMP Cache remove JSON-LD data

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#11981]
To whom it may concern:

I use ping update to make AMP cache do update stuff and I found my HTML content about **JSON-LD**  will be trimmed in AMP cache.

Here comes my *ampUrl* & *cdnAmpUrl*
* [ampUrl](https://blog.lalacube.com/item/100347591196)
* [cdnAmpUrl](https://blog-lalacube-com.cdn.ampproject.org/c/s/blog.lalacube.com/item/100347591196)

I wonder is this an issue ot not ?

And what  if I like to share my website to publish, which one is better between **ampUrl** and **cdnAmpUrl** ?

Have a nice day.

Paul

**Comment by aghassemi** [comment]
@meistudioli has always removed metadata. It should not be impacting you.  

For sharing, please either share Canonical Url or the AmpUrl. never CdnAmpUrl

**Comment by meistudioli** [comment]
ok. thanks.
