### ISSUE TITLE
Analytics: visibilitySpec to config percentage thresholds

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#11986]
### Overview ###
Amp Analytics support visible trigger. And enable a user to config the visible event via `visibilitySpec`. 
`visibilitySpec` looks like. Note: all attributes are optional
```
'visibilitySpec': {
  'visiblePercentageMin': 50,
  'visiblePercentageMax': 80,
  'totalTimeMin': 3000,
  'totalTimeMax': 5000,
  'continousTimeMin': 1000,
  'continousTimeMax': 1500,
}
```
This visibleSpec is limited to single visible event trigger. And there can be an easier way to multiple config visibility events without duplicating the spec several times.
People want a way to easily config multiple visible events with single `visibleSpec`

### Config multiple visible event ###
Given that time settings are more likely to be shared, we can introduce an new array of `visiblePercentage` other than old `visiblePercentageMin` and `visiblePercentageMax`
The new `visiblePercentage` array can use an array of tuples, similar to Python ranges
For example:
```
{
  'visiblePercentage': [[0, 55], [50, 10],
}
```

// Will not use this format
Given that time settings are more likely to be shared, we can introduce an array to the `visiblePercentageMin` and `visiblePercentageMax`.
The new `visiblePercentageMin` and `visiblePercentageMax` can be two arrays of same size.
For example:
```
{
  'visiblePercentageMin': [0, 55],
  'visiblePercentageMax': [50, 100],
}
```
This will be transformed to 
```
{
  'visiblePercentageMin': 0,
  'visiblePercentageMax': 50,
}
and
{
  'visiblePercentageMin': 55,
  'visiblePercentageMax': 100,
}
```
To further extend the usage, configs below should also be supported
```
{ 
  'visiblePercentageMin': 0,
  'visiblePercentageMax': [50, 100],
}
```
And a `visiblePercentageIncrement` keyword, that enable user to define incremental visible percentage easily
```
{
  'visiblePercentageIncrement': 10,
  'visiblePercentageMin': 50,
  'visiblePercentageMax': 100,
}
```
Note that `visiblePercentageIncrement` needs to align with our minimal threshold which is 5% now.

**Comment by zhouyx** [comment]
Maybe something like the native InOb threshold is better
For example threshold [0, 10, 20, 30]

**Comment by adelinamart** [comment]
@zhouyx to break this in 3 and assign accordingly

**Comment by zhouyx** [comment]
https://github.com/ampproject/amphtml/issues/11873#issuecomment-342974876
