### ISSUE TITLE
AMP carousel custom prev/next buttons

### ISSUE THREAD

**Issue by TheodorGosden** [ampproject/amphtml#12009]
I would like to have a way to make a custom prev/next button in AMP. This is because I would like the prev/next buttons below the carousel (before and after the dots). Currently, I can style it all I want as long as I don't overflow the carousel.

Then I thought, I could just make the buttons my self, and then make a tap:#my-carousel.goToNextSlide. But that, unfortunately, doesn't exist.
![screen shot 2017-11-10 at 11 09 59](https://user-images.githubusercontent.com/19152803/32653479-589b9ba4-c608-11e7-9c28-a201adf8f365.png)

**Comment by aghassemi** [comment]
@TheodorGosden You can build this using `amp-bind`, please see https://ampbyexample.com/advanced/image_galleries_with_amp-carousel/#linking-carousels-with-amp-bind for an example that ties `amp-caoursel` with a `thumbnail selector`. Your case is a bit different but the fundamentals are the same.

**Comment by aghassemi** [comment]
Closing this issue, feel free to reopen if you run into bugs while building this with `amp-bind`.
