### ISSUE TITLE
[Question]Why sometimes amp page open inside installed pwa and sometimes not?

### ISSUE THREAD

**Issue by mauricionr** [ampproject/amphtml#12000]
I have an pwa in my android and sometimes amp page open inside the pwa, and sometimes not?

What is the correct behavior?

Thanks!

**Comment by aghassemi** [comment]
@mauricionr do you have a sample Url for us to test?
/cc @dvoytenko 
/to @cvializ

**Comment by mauricionr** [comment]
i will send to you guys an recorded demo, and provide the url if needed! Thanks

**Comment by mauricionr** [comment]
sent!

**Comment by cvializ** [comment]
Where was this sent to?

**Comment by aghassemi** [comment]
Closing the issue since discussed on Slack

**Comment by aloha202** [comment]
Hey guys, i have a related question
I've got a pwa and i want to open it from another application using the url like mypwascheme:http://my.test.host/mypage

But i have no idea what should i use for the scheme part

Any ideas?
Thanks in advance

**Comment by cvializ** [comment]
Hello! I think a general question like this would be more appropriate on a dedicated forum or QA discussion site like StackOverflow. If you have an AMP related question, feel free to open a new issue so we can track that discussion separately from existing issues.
