### ISSUE TITLE
An AMP4ADS document using style[amp-keyframes] doesn't validate

### ISSUE THREAD

**Issue by heather162** [ampproject/amphtml#12004]
## What's the issue?

An AMP4ADS document using style[amp-keyframes] doesn't validate.

The error is
"The parent tag of tag 'style amp-custom (AMP4ADS)' is 'body', but it can only be 'head'."

## How do we reproduce the issue?

Add <style amp-keyframes></style> as the last tag in the document body on the default ad at https://validator.ampproject.org/#htmlFormat=AMP4ADS

## What browsers are affected?
N/A

## Which AMP version is affected?
N/A

It looks like the validator just needs to allow style[amp-keyframes] for AMP4ADS.

**Comment by honeybadgerdontcare** [comment]
Currently <style amp-keyframes> is only available on AMP documents and not AMP4ADS documents.

/to @chenshay @jasti

**Comment by Gregable** [comment]
I'm pretty sure this is an oversight and not intended.

Created https://github.com/ampproject/amphtml/pull/12015 to fix, but will confirm with @dvoytenko before mergint.

**Comment by Gregable** [comment]
https://github.com/ampproject/amphtml/pull/12015 fixes this, but it'll be a couple weeks before this makes it out to production.

**Comment by Gregable** [comment]
This fix is live everywhere.
