### ISSUE TITLE
Bookend Schema documentation is incorrect

### ISSUE THREAD

**Issue by gmac** [ampproject/amphtml#12003]
@choumx Bookend schema documentation (found here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/amp-story.md#bookend-json-endpoint) is incorrect. The schema should be:

```
{
  "related-articles": {
    "More to Read": [
      {
        title: "My friends, this is India [...]",
        url: "http://a-publisher.com/india"
        image: "./media/b1.jpg"
      },
      {
        title: "A wonderful weekend with Tenturi",
        url: "http://a-publisher.com/tenturi"
        image: "./media/b2.jpg"
      },
      ...
    ],
  }
}
```

This is an important piece of documentation for third-party developers.

**Comment by choumx** [comment]
Thanks for following up on this. We actually already have a fix out in #11984. Will be merged soon.
