### ISSUE TITLE
Chrome Extension: Extension stays broken if validator.js not loaded

### ISSUE THREAD

**Issue by jamesshannon** [ampproject/amphtml#12019]
The extension wasn't working for me. Went through a bunch of debugging and made it to the background.js page, which was saying that the amp object is undefined (line 248: `const validationResult = amp.validator.validateString(doc);`). Network tab showed that when trying to download this there was an ERR_CONNECTION_REFUSED. I've been doing a lot of traveling recently, so I guess that I some point the extension started up and I didn't have internet.

This is somewhat brittle, as a momentary internet glitch caused the extension to be effectively broken until it's restarted (and there's no clear way to know this).

There should either be a note when hovering over the action button, or the background should try to redownload, or to do a network-then-cache strategy.

**Comment by aghassemi** [comment]
@jamesshannon  assigning to you since we are not actively working on the extension.
/cc @honeybadgerdontcare
