### ISSUE TITLE
<amp-analytics> amp-form-submit not firing

### ISSUE THREAD

**Issue by jamesshannon** [ampproject/amphtml#12010]
I'm trying to track outbound clicks (click-tracking) and also outbound form redirects and having issues with amp-form-submit(-success).

[Test page][1] with [<amp-analytics> code][2] copied from both ampbyexample forms page, the analytics page, and also the [amp-form#analytics-triggers page][3].

I'm seeing the pageview ping, plus my click event on the select button, but no amp-form-submit ping. No errors in the console about parsing the amp-analytics config.

![download](https://user-images.githubusercontent.com/761381/32660369-88fd41b6-c5f0-11e7-99c7-879e4f29672f.png)

  [1]: http://jsbin.com/yuwared/edit?html
  [2]: http://jsbin.com/yuwared/edit?html
  [3]: https://www.ampproject.org/docs/reference/components/amp-form#analytics-triggers

**Comment by cvializ** [comment]
I am able to reproduce. Will investigate.

**Comment by rudygalfi** [comment]
Should we include in H2 Nov sprint?

**Comment by cvializ** [comment]
Potentially

**Comment by jamesshannon** [comment]
In the meantime, can you think of any workarounds offhand?

Attaching a change event to the select didn't do any good (for analytics), and neither did amp-form-submit. Though I didn't try amp-form-submit-success. I assume that's not working, either?

**Comment by cvializ** [comment]
I notice that your `"trackFormSubmit"` block is not inside the `"triggers"`. The event does fire if I move that into the `"triggers"` block.

**Comment by jamesshannon** [comment]
Good catch. But you were able to reproduce this morning, right? Or did you just catch this yourself?

I did a preliminary test and it seems to be working.

**Comment by cvializ** [comment]
I repro'd on your example, and discovered the above when trying a local repro. Sorry for any confusion
