### ISSUE TITLE
Documentation/validator mismatch for amp-ad-exit

### ISSUE THREAD

**Issue by heather162** [ampproject/amphtml#12022]
## What's the issue?

The documentation for amp-ad-exit says that all layouts are supported because the extension is hidden but the validation spec for amp-ad-exit does not allow the layout attribute to be present with any value.

## How do we reproduce the issue?

Add an amp-ad-exit tag with a layout attribute to an A4A document and then try to validate the document.

## What browsers are affected?
N/A

## Which AMP version is affected?
N/A

**Comment by jasti** [comment]
@clawr @Gregable Could you PTAL? Thanks.

**Comment by clawr** [comment]
I guess the right thing to do is allow "nodisplay". Not specifying should still be ok too. I'll make the change.

**Comment by lannka** [comment]
@clawr are you still on it?
