### ISSUE TITLE
 Attribute 'href' may not appear in tag 'span'

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#12024]
Similar to: https://github.com/ampproject/amphtml/issues/8928

getting an error on these types of statements:
```
<dl class=''>
<dt class=''>Concepts</dt>
<dd id='1700000000100045' class=''>
<span typeof='schema:Person'>
<span property='schema:identifier' href='https://example.io/identifier/1700000000100045'></span>
<span property='schema:url' href='http://dblp.uni-trier.de/pers/hd/a/person'></span>
</span>
</dd>
</dl>

```
HEAD looks like this:
```
<html
  amp
  lang='en-us'
  prefix='schema: http://schema.org/'
>

```
the above is standard schema.org declarations and valid on Google Structure Data Testing Tool.

/jay gray

**Comment by Gregable** [comment]
@jaygray0919 Do you have any pointers to references on this? I'd like to understand which tags it should be supported on and what it is for.

Re: 8928, that was an SVG parsing question, so I don't think this is an extension of that request exactly.

**Comment by jaygray0919** [comment]
@Gregable have a look here:

[Source](https://ontomatica.io/amp/amp_schema_test/
)

[GSDTT](https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fontomatica.io%2Famp%2Famp_schema_test%2F)


[AMP validator](https://validator.ampproject.org/#url=https%3A%2F%2Fontomatica.io%2Famp%2Famp_schema_test%2F)

/jay

**Comment by Gregable** [comment]
Sorry I was unclear. I'm looking for a reference on the `href` attribute as used in a `<span>` tag, not an example. A document stating what this means and on which tags it's supported. Does it include only `<span>` for example

The SDTT not complaining doesn't mean much. It also doesn't complain about a literal `<foo>` tag.

**Comment by jaygray0919** [comment]
Here is @Person defines by schema.org.
http://schema.org/Person
See RDFa examples at the bottom, example #2.
Is that what you meant?
/jay

**Comment by Gregable** [comment]
Right, but I don't see an example here using `<span href=...>`. I'm trying to understand if that's a valid schema.org markup or not. If so, what are the tags for which the `href` attribute has meaning in schema.org markup.

**Comment by jaygray0919** [comment]
From the above page, here is a "close match" using <link>
```
<div vocab="http://schema.org/" typeof="MusicEvent">
      <div property="location" typeof="MusicVenue">
        <meta property="name" content="Chicago Symphony Center"/>
        <link property="sameAs" href="http://en.wikipedia.org/wiki/Symphony_Center"/>
        <meta property="address" content="220 S. Michigan Ave, Chicago, Illinois, USA"/>
      </div>
      <div property="offers" typeof="Offer">
        <link property="url" href="/examples/ticket/12341234"/>
        <meta property="priceCurrency" content="USD" />$
        <meta property="price" content="40"/>40.00
        <link property="availability" href="http://schema.org/InStock"/>
      </div>
</div>
```

in our case, we set the vocab in `<html>` using `prefix='schema: https://schema.org'` rather than assigning a vocab to `<div>`.
the grammar then allows us to assign types and properties to `<html elements>`.
it's true that the example above uses `<link>`, but, in schema.org world and in RDFa world, we're allowed to apply types and properties to `<div>`, `<span>`, `<p>` etc.

GSDTT is the 'authority' that validates the correctness of both the syntax and semantics.
The W3C authority is https://www.w3.org/2012/pyRdfa/Validator.html

our original examples is properly parsed as an RDF 'triple' - meaning that we can see in both 'harvesters' that the representation means the same as the source document.

i'll check to see if we achieve the same result using `<link>` rather than `<span>`.
is it your current position that we must use `<link>` in a statement when identifying the resource that defines the statement?

/jay

**Comment by Gregable** [comment]
Hi Jay, sorry in advance for the delays in responding this week due to us holidays.

The "etc" in "`<div>`, `<span>`, `<p>` etc" is the primary concern. `href` has browser behavioral meaning in a variety of tags in HTML (`a`, `area`, `base`, and `link` currently, plus some `svg` tags and amp custom elements). It also can be used to execute javascript (ex: `<a href="javascript:alert(1)">`). 

I am cautious about adding global support for the attribute on all tags. I would prefer to limit it to known inert use cases (`<link property=... href=...>` is fine and already allowed).

It's unclear to me if the linked validator is seeing your `<span href=>` as valid RDFa or is ignoring it as HTML as per the comments: "The validator does not analyze the HTML/XML content itself.". It seems to parse the attribute even if I add it as `<foo property='schema:url' href='http://dblp.uni-trier.de/pers/hd/a/person'>` which suggests to me that this is not terribly strict.

**Comment by jaygray0919** [comment]
Thanks for update @Gregable ; we'll check to see if `<link property=... href=...` produces the same semantic results as our proposal. Be back to you.
/jay

**Comment by jaygray0919** [comment]
@Gregable Testing indicates that using `<link property=''>` or `<span property=''>` produces identical "machine-readable" (semantic) results. Since AMP rejects using an `href` on `<span>`, we'll use `<link property='' href=''>` instead of `<span>`. And the term "link" better represents the purpose of the statement than does "span", so we're good with that.

thanks for you help here greg.

**Comment by Gregable** [comment]
Thanks for the update.
