### ISSUE TITLE
All AMP examples in the site are false

### ISSUE THREAD

**Issue by nazaninbinesh** [ampproject/amphtml#12025]
Hello
As I checked www.ampproject.org, all the main case studies which are introduced for using AMP technology in mobile version are false , there was no AMP version .
would you please give me some information about what is going on? Is the information in the site is fake?
Best Regards
Nazanin Binesh

**Comment by rudygalfi** [comment]
@nazaninbinesh Can you please support your claims with some specific details on what you think the issues are? Otherwise, there's no information to act on, so I would need to close this.
