### ISSUE TITLE
amp-img - add a new layout mode "intrinsic"

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#12020]
Currently `amp-img` !== `img` in several key respects.

`amp-img` has no intrinsic size so a responsive `amp-img` in a floated div will be 0x0.  A regular html `img` will inflate to it's intrinsic size or it meets a constraint like `max-width` or `max-height`.  This can't be fixed with `min-width` because it has a higher priority than `max-width`.

Additionally it's currently impossible to make `amp-img` responsive in both height and width.

The new `intrinsic` layout will correct both of these and make `amp-img` behave like a regular `img` while still maintaining the "no jump on load" philosophy.

Typically a bare image tag without height and width will initially render 0x0 until the browser has loaded the image and determined it's size at which time the page must be repainted with the actual size.  The new intrinsic mode removes this jump behavior by including a transparent `svg` as a data url in the document.  This allow the browser to know the size of the image at page load time.  When the AMP run time loads the actual image it's pinned to the `svg` sizing element.

In [this codepen](https://codepen.io/jpettitt/pen/zPZpjL) the top image is rendered in the same way as `amp-img` but uses an `svg` instead of a `div` as a sizing space holder.  The result is an image that is responsive in both width and height, works with `float` and doesn't jump on page load.

`height` and `width` will still be required but they will only be used to set the `svg` size where they will determine both the aspect ratio and the unconstrained size of the image.

Open question: browser compatibility? It has been tested on chrome, firefox, and safari, we'll need to make sure it works on the other supported browsers (edge?)

cc @aghassemi @cramforce

**Comment by jridgewell** [comment]
How is this different from a responsive amp-img?

**Comment by jpettitt** [comment]
A responsive `amp-img `will render 0x0 in a float requiring additional css glue to fix, of then this require a manual fix as it's next to impossible to auto convert.  The new mode will behave like a regular image, rendering as large as possible up to it's actual size or any css imposed constraints. This will make auto converting existing themes much easier.

**Comment by jridgewell** [comment]
Wow, I should have read better. Sorry.

**Comment by bpaduch** [comment]
@jpettitt  - this also seems to happen for "fill"  because it doesn't have an intrinsic size, yes?
