### ISSUE TITLE
AMP cache is not invalidated.

### ISSUE THREAD

**Issue by AkashHC13** [ampproject/amphtml#12045]
## What's the issue?

https://www-thequint-com.cdn.ampproject.org/i/s/www.thequint.com/images/thequint_amp.png
gives a 404. 

However 
https://www-thequint-com.cdn.ampproject.org/i/s/www.thequint.com/images/thequint_amp.png?foo=bar 
gets me the image.

Original logo url is https://www.thequint.com/images/thequint_amp.png

**Comment by aghassemi** [comment]
@Gregable @honeybadgerdontcare thoughts on why this happens?

**Comment by honeybadgerdontcare** [comment]
Could be that when the url without the query params was requested in the cache the image was a 404 and the cache hasn't updated it yet due to various potential reasons.

@AkashHC13 can you share the url this image is linked to? Are those pages not showing the image?

**Comment by AkashHC13** [comment]
@honeybadgerdontcare Yes, those pages were not showing the image. However, looks like its working fine now. Any idea how?

**Comment by honeybadgerdontcare** [comment]
@AkashHC13 I did an update-ping request for that image and that instructs the cache to look for the file again. The better version of update-ping is [update-cache](https://developers.google.com/amp/cache/update-cache) but that can only be done by the domain hosting the content.
