### ISSUE TITLE
Success message is incongruent with icon in Story Runtime checks

### ISSUE THREAD

**Issue by bpaduch** [ampproject/amphtml#12040]
Related to https://github.com/ampproject/amphtml/pull/11627#issuecomment-343974929

The "successful" messages in the Developer Logs for AMP stories provides mixed signals between the green check icon and the language of the message. 
- Green = good
- Language of message = "Don't do this"

![amp-story-log-message-confusion](https://user-images.githubusercontent.com/1012254/32744872-efae7f70-c87e-11e7-8116-f66a717b5155.png)

In the above example, the page is completely correct and performant, but that's hard to tell.  

Possible remedies:

1) If "success", don't show any message.
2) If "success", change language of message so that's it positively-oriented. For example: "Video **is**  portrait orientation", "Video size is optimal (less than 720p)", etc.

**Comment by sanjsanj** [comment]
@newmuis Is this available to be picked up please?  I've had 1 GFI merged in and could have a look at this.
