### ISSUE TITLE
amp-list: add resizable flag

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#12042]
When amp-list content (or `src`) get's updated via amp-bind, the updated content might no longer fit into the available space (either too large or too small). It'd be great to have a `resizable` flag for amp-list that would resize the amp-list to fit it's content, when it's content is updated via amp-bind.  Effectively changing the layout from whatever was initially defined to a container layout.

```
<amp-list height="56" layout="fixed-height" resizable src="amp-list-resize-few.json" [src]="listSrc">
```

A sample use case would be items being removed from a shopping cart that is rendered via amp-list.

Here is an example that demonstrates the problem: https://amp-live-list-form.glitch.me/amp-list-resize.html

//@choumx @ericlindley-g

**Comment by jaygray0919** [comment]
We have exactly this problem with a number of `amp-list` `amp-mustache` instances where the `src` document is updated daily.

the "source" of `src` data is a client-side `ajax` `JSONP` script that reads HTTPS/CORS data from different servers. We then have to save that output to an `amp-list`. New data overwrites existing data so we don't have to change the AMP document. But the size of the data changes each time we pipeline the new data.

Ideally, we would like to run the equivalent of the JSONP script in an `amp-bind` `amp-list` `amp-mustache` combo.

/jay gray

**Comment by choumx** [comment]
Good idea. We're already planning to do this in #10230. Closing as dupe.

Any opinion on whether this should be the new default behavior or opt-in?

**Comment by sebastianbenz** [comment]
Thanks, I didn't see the other issue. I think it needs to be opt-in.
Otherwise you might break existing implementations that rely on the current
behavior.

**Comment by choumx** [comment]
I agree. 👍
