### ISSUE TITLE
amp-selector: `[selected]` attribute with `amp-bind` conflicts with manual selection

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#12056]
If `selected` attribute of `amp-selector` is changed view bind, and then manually via tap, the binding stops working.

I believe this is because the manual tap does not update the `selected` attribute so `bind` on the next updates does not believe it is actually changing the value and therefore does not mutate.

/cc @camelburrito

**Comment by djavet** [comment]
Full sample code here: https://codepen.io/aghassemi/pen/jaLrjR

**Comment by aghassemi** [comment]
closing in favour of https://github.com/ampproject/amphtml/issues/12058, root cause is deeper than `amp-selector`

**Comment by aghassemi** [comment]
worked around added to  https://codepen.io/aghassemi/pen/jaLrjR
