### ISSUE TITLE
amp-bind: Need a way to invalidate "previousValue" for a boundProperty.

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#12058]
Some components like `amp-selector` may have other ways of changing the value of a property (e.g. a manual tap changes the `selected` attribute). The issue is `amp-bind` relied on previously calculated value to decide whether something has changed or not before mutating, so we need a way for a component to purge the `previousValue`.

Example:

```
    <amp-selector [selected]="selectedTab" role="tablist" layout="container" class="ampTabContainer">
        <div role="tab" class="tabButton" selected option="a">Tab one</div>
        <div role="tabpanel" class="tabContent">Tab one content... </div>
        <div role="tab" class="tabButton" option="b">Tab two</div>
        <div role="tabpanel" class="tabContent">Tab two content... </div>
        <div role="tab" class="tabButton" option="c">Tab three</div>
        <div role="tabpanel" class="tabContent">Tab three content... </div>
    </amp-selector>

    <button on="tap:AMP.setState({selectedTab: 'c'})">Select tab 3</button>
```

Here the button mutates `[selected]` attribute to select the third tab, however each tab is also tappable, so if user changes the selected tab via tap, the next click on the button does not select tab 3 since in the eye of `bind` nothing has changed. `amp-selector` needs a way of informing `bind` that the previous value it has cached is not correct.

(For this particular case there work around is to add `on="select:AMP.setState({selectedTab: event.targetOption})"` to manually inform `bind` as well. So not a big priority, it may come up again with other components that internally can change the value of attribute though.)

**Comment by choumx** [comment]
Thanks for filing this issue. You're right that amp-bind only has visibility over bindings and adding a `select` event trigger would work. I'm not sure that automatically changing bind variables without an event/action is the right solution though since I think implicit behavior can be very confusing. 

Let's use this issue to track other instances of this as they pop up.

**Comment by choumx** [comment]
Closing this since we haven't seen any other similar feedback. Please reopen if you feel strongly.
