### ISSUE TITLE
AMP-YOUTUBE: Error: Cannot read property 'contentWindow' of null

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#12063]
Error: Cannot read property 'contentWindow' of null
at contentWindow (https://raw.githubusercontent.com/ampproject/amphtml/1510180045130/extensions/amp-youtube/0.1/amp-youtube.js:334)

**Comment by rcebulko** [comment]
This is actually a problem with the underlying amp-ima-video extension, which validates the availability of the content window, THEN waits for a promise to resolve, THEN tries to use the content window.

**Comment by rsimha** [comment]
This probably needs to be reassigned @ampproject/wg-ui-and-a11y

**Comment by rcebulko** [comment]
I have a PR fixing this already; see link above.
