### ISSUE TITLE
Opera 49 Desktop (Mac) ad blocking blocks ALL AMP JS widgets

### ISSUE THREAD

**Issue by QES** [ampproject/amphtml#12066]
## What's the issue?

When using Opera 49 on desktop the default is to use its add blocker, that stops any AMP JS elements loading and pages are not loaded.

I'm not sure this is something that the amphtml project can solve but it is something that should communicated to the Opera team in as many ways as possible.  I have also submitted a bug report to Opera.

## How do we reproduce the issue?

Use Opera desktop on a site such as https://amp.sportsmole.co.uk

The page displays without images or any other formatting elements.

## What browsers are affected?

Opera Desktop 49

## Which AMP version is affected?

Current version

**Comment by jridgewell** [comment]
Whoo EasyList. Maybe related to https://github.com/ampproject/amphtml/issues/12065? /cc @kenrick95

**Comment by jridgewell** [comment]
It appears sportsmole ran afoul of EasyList:

```txt
! https://github.com/easylist/easylist/blob/46c27697cbe766330dffc891b9e8e648076e6d7e/easylist/easylist_specific_block.txt

|https://$script,third-party,domain=100percentfedup.com|activistpost.com|addictinginfo.com|alfonzorachel.com|allenbwest.com|allenwestrepublic.com|allthingsvegas.com|americansublime.com|askmefast.com|auntyacid.com|barbwire.com|beforeitsnews.com|bestfunnyjokes4u.com|bighealthreport.com|bipartisan.report|bipartisanreport.combreaking911.com|boredomtherapy.com|breathecast.com|bugout.news|bulletsfirst.net|buzzlamp.com|celebrity-gossip.net|cheatsheet.com|clashdaily.com|classicalite.com|collapse.news|comicallyincorrect.com|conservativebyte.com|conservativeintel.com|conservativetribune.com|conservativevideos.com|constitution.com|coviral.com|cowboybyte.com|craigjames.com|creepybasement.com|crossmap.com|cyberwar.news|dailyfeed.co.uk|dailyheadlines.net|dailyhealthpost.com|dailysurge.com|damnlol.com|dccrimestories.com|deneenborelli.com|digitaljournal.com|eaglerising.com|earnthenecklace.com|enstarz.com|evil.news|faithit.com|fitnessconnoisseur.com|foreverymom.com|freedom.news|freedomdaily.com|freedomforce.com|freedomoutpost.com|genfringe.com|girlsjustwannahaveguns.com|glitch.news|godfatherpolitics.com|gopocalypse.org|gosocial.co|groopspeak.com|guardianlv.com|guns.news|gymflow100.com|hallels.com|hautereport.com|headcramp.com|healthstatus.com|hellou.co.uk|hispolitica.com|hngn.com|honesttopaws.com|hypable.com|ifyouonlynews.com|infowars.com|instigatornews.com|janmorganmedia.com|jobsnhire.com|joeforamerica.com|juicerhead.com|justdiy.com|kdramastars.com|keepandbear.com|kpopstarz.com|lastresistance.com|latinpost.com|legalinsurrection.com|liberty.news|libertyalliance.com|libertyunyielding.com|lidblog.com|medicine.news|mentalflare.com|millionpictures.co|minutemennews.com|moneyversed.com|musictimes.com|myscienceacademy.org|natural.news|naturalblaze.com|naturalnews.com|naturalsociety.com|natureworldnews.com|newser.com|newseveryday.com|newsthump.com|oddee.com|opednews.com|parentherald.com|patriotoutdoornews.com|patriottribune.com|patriotupdate.com|pickthebrain.com|pitgrit.com|politicaloutcast.com|politichicks.com|practicallyviral.com|profitconfidential.com|quirlycues.com|rantlifestyle.com|realfarmacy.com|realmomsrealreviews.com|realtytoday.com|redhotchacha.com|redmaryland.com|returnofkings.com|reviveusa.com|rightwingnews.com|robotics.news|shark-tank.com|shedthoselbs.com|skrillionaire.com|slender.news|sonsoflibertymedia.com|spectator.org|sportsmole.co.uk|stevedeace.com|stupid.news|supercheats.com|techconsumer.com|technobuffalo.com|techtimes.com|theblacksphere.net|theboredmind.com|thecountrycaller.com|thefreethoughtproject.com|thegatewaypundit.com|thelastlineofdefense.org|thelibertarianrepublic.com|themattwalshblog.com|thepoke.co.uk|therealside.com|theviralmob.com|tinypic.com|tosavealife.com|traileraddict.com|truththeory.com|twisted.news|universityherald.com|usherald.com|valuewalk.com|vampirediaries.com|vcpost.com|victoriajackson.com|videogamesblogger.com|viralnova.com|viralthread.com|visiontoamerica.com|westernjournalism.com|whatzbuzzing.com|winningdemocrats.com|wnd.com|woundedamericanwarrior.com|xtribune.com|youngcons.com|youthhealthmag.com
```

So, AMP is being blocked, _all_ third party scripts from sportsmole are being blocked.

**Comment by QES** [comment]
Thanks now to get off that list, but why does an adblocker block AMP components?

**Comment by jridgewell** [comment]
It's not blocking the AMP components exactly. It's blocky any script that has a source that's not the same domain. So, you're loading v0.js from `cdn.ampproject.org`, which isn't `sportsmole.co.uk`, so blocked.

**Comment by jridgewell** [comment]
As kind of a cool workaround, all pages loaded from Google Search will work since they're being hosted by the CDN. So, https://www.google.com/amp/s/amp.sportsmole.co.uk/football/crystal-palace/news/hodgson-loftus-cheek-can-make-world-cup_312021.html doesn't have the same script blocking that `sportsmole.co.uk`'s origin domain does.

**Comment by QES** [comment]
Hi @jridgewell that is interesting so in the case of these kind of ad blockers they need to whitelist cdn.ampproject.org OR can one use a CNAME to map cdn.ampproject.org to (in this case to cdn.sportsmole.co.uk - not sure if that is valid).

Of course the one problem with the google cache that you link to is that it is a single page that works and all links break as they are back on the main site and that is a function of the way that the cache works.

I know there is a project to allow publishers to perform the same flattening within their own cache.
