### ISSUE TITLE
Implement "halves" template for amp-story-grid-layer

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#12078]
A FR has come in for a `halves` template that splits the screen into two equal sections, stacked vertically.  This is akin to the `thirds` template, but with two sections instead of three.

Not sure if there's a better name for this; perhaps one that implies the vertical orientation of the sections.

**Comment by diaryofdiscoveries** [comment]
@newmuis I'd like to make my first contribution. Is this open? Is this a good one for me to pick up?

**Comment by newmuis** [comment]
Sure! Thanks for the contribution!

@gmajoulet may be a good person to review the code

**Comment by diaryofdiscoveries** [comment]
Thank you @newmuis. Will do @gmajoulet and thanks for the pointer.
