### ISSUE TITLE
Cannot navigate to bookend page

### ISSUE THREAD

**Issue by bpaduch** [ampproject/amphtml#12086]
With the [recent changes to bookend behavior](https://github.com/ampproject/amphtml/pull/12021), I cannot navigate to the bookend page, even though the progress indicator indicates a remaining page.

Example - https://bap-amp-001.appspot.com/

Might be a regression.

**Comment by newmuis** [comment]
/to @alanorozco Can you take a look?

**Comment by alanorozco** [comment]
@newmuis

Caused by a lack of foresight on my part when responding to PR review. In short, I need to remove an `important` clause. Sending fix soon.

**Comment by bpaduch** [comment]
@alanorozco - Thanks for the fix.  When will this be available in the build?  Right now, the app still can't navigate to bookend.

**Comment by newmuis** [comment]
This should go out in the next AMP cut.  I think that will go out to `dev-channel` on Nov. 28.
