### ISSUE TITLE
Google Speed - AMP CSS Grid

### ISSUE THREAD

**Issue by greghuet** [ampproject/amphtml#12097]
Hi,

Following the presentation from the AMP in Paris last week, we are working on a full responsive site in AMP using CSS and grid placement. Also this is all working well so far as you can see here on our test page:
[http://amp.mio-oroscopo-del-giorno.com/index_grid.php](url)

We are doing some tests using Google Speed to see the performances based on Google solution. Here is the direct link:
[https://developers.google.com/speed/pagespeed/insights/?hl=fr&url=http%3A%2F%2Famp.mio-oroscopo-del-giorno.com%2Findex_grid.php&tab=desktop](url)

As you can see, the previews are totally wrong for the mobile and desktop version of the site. Then I decieded to test the ampproject.org site:
[https://developers.google.com/speed/pagespeed/insights/?hl=fr&url=https%3A%2F%2Fwww.ampproject.org%2Ffr%2Fcontribute%2F](url)

Here too, we see that the previews are also wrong. Is this issue known ?

Also, could someone confirm that CSS grid integration is working properly for AMP pages for a responsive layout?

**Comment by aghassemi** [comment]
Hi,

I am not sure why pagespeed preview's are wrong. Migth be that they are using an older version of browser to render. Their support forum is here: https://groups.google.com/forum/#!forum/pagespeed-insights-discuss I suggest asking there.

As for AMP and CSS Grid: As long as the browser supports CSS Grid (not all do), there shouldn't be any issues using it in AMP.

**Comment by greghuet** [comment]
Thank you very much for your answer, I hope this will help others also developping their sites using AMP / Grid responsive design ;0
