### ISSUE TITLE
Consider sending data- attributes to amp-iframe

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1209]
This would make certain use case more idiomatic, instead of using programmatic URL construction. Basically we'd just add all the data-attributes to the URL as query string arguments.

At this point I'm not 100% convinced it is a good idea and it is also less ideal for more advanced parameters. One use case is passing CSS into the iframe, which is still awkward via a URL argument.

**Comment by cramforce** [comment]
I think we should forward all attributes named

`data-param-foo` as `?foo` in the query string of the iframe.

**Comment by jpettitt** [comment]
+1 for the `data-param-foo` approach.

**Comment by mkhatib** [comment]
How does this behave in case of using `srcdoc`? Do we just append the params to the computed `dataUri`? or do we not pass `data-param-*` in that case?

**Comment by cramforce** [comment]
@mkhatib No support for srcset I'd say. This is just a convenience for URL generation anyway.

**Comment by mkhatib** [comment]
That's what I thought and that's what I have in place for the PR.

**Comment by ericlindley-g** [comment]
@mkhatib Any updates on this?

**Comment by mkhatib** [comment]
The pull request is ready to be merged. Any notes on the PR? #1537
