### ISSUE TITLE
Validator rejects aria-current="page" on a span. Correct?

### ISSUE THREAD

**Issue by weeblrpress** [ampproject/amphtml#12096]
## What's the issue?

If an aria-current="page" is added to a span, as can now happen with WordPress + Yoast SEO, the AMP validator invalidates the page with a `The attribute 'aria-current' may not appear in tag 'span'` error message. 

[EDIT]: I looked up https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii and it appears that aria-current is simply not whitelisted.

## How do we reproduce the issue?

On a WordPress install, using Yoast SEO, a page that has pagination will cause this error. Can also be reproduced by adding the aria-current attribute to any element I think.

## Which AMP version is affected?

Tested as of 2017-11-17

**Comment by aghassemi** [comment]
@weeblrpress  fix sent. will be in production in about 3 weeks.
