### ISSUE TITLE
Builtin PWA code to add offline CSS class to document?

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#12091]
Issue to track investigating the effort involved in adding simple offline detection to an AMP document. Ideally just by including an extension.

**Comment by QES** [comment]
This I think would be a great addition to AMP,  PWA is a great idea but what sets AMP apart is that it is a set of libraries that can be loaded with simple JSON elements to make changes and alterations to the way things work.  Having a similar set of tools for limited PWA elements - offline caching would be a great additon.
