### ISSUE TITLE
Add an option to fail on warnings during gulp validation

### ISSUE THREAD

**Issue by pmendelski** [ampproject/amphtml#12114]
Please make it possible to fail on validation warnings with `gulp-amphtml-validator`.

Right now it is impossible to fail on validation warnings. Example:
```js
const ampValidator = require('gulp-amphtml-validator'); // version: "^1.0.1"

gulp.task('validate', ['build:html'], () => {
  return gulp.src('./dist/**/*.html')
    .pipe(ampValidator.validate())
    .pipe(ampValidator.format())
    .pipe(ampValidator.failAfterError());
})

// task is successful and there are no validation messages
```

Please make `gulp-amphtml-validator` configurable.

**Comment by powdercloud** [comment]
I believe this would need to be done in https://github.com/ampproject/amphtml/blob/master/validator/gulpjs/index.js. E.g., maybe something like failAfterWarningOrError(), similar to failAfterError()?
@sebastianbenz does this sound ok to you, or other ideas?
I'm thinking it's relatively straight forward and reasonable to do this, just figure it's good to ask before going ahead. And if anyone else wants to do it, cool. :-)

**Comment by sebastianbenz** [comment]
failAfterWarningOrError sounds good. Feel free to create a PR (but I can do it as well).

**Comment by powdercloud** [comment]
Sending https://github.com/ampproject/amphtml/pull/12257.

**Comment by Gregable** [comment]
It looks like we can mark this as closed. Please reopen if I'm missing something.

**Comment by sebastianbenz** [comment]
Now published to NPM as well: https://www.npmjs.com/package/gulp-amphtml-validator

**Comment by pmendelski** [comment]
Thanks
