### ISSUE TITLE
AMP Validator: removing the word "just" from documentation

### ISSUE THREAD

**Issue by adactio** [ampproject/amphtml#12115]
Hi,

The AMP Validator currently contains instructions inside an HTML comment.
<https://validator.ampproject.org/>

The comment reads:

> This is the minimum valid AMP HTML document. **Just** type away here and the AMP Validator will re-check your document on the fly.

Suggested change—remove the word "just":

> This is the minimum valid AMP HTML document. Type away here and the AMP Validator will re-check your document on the fly.

The reasoning is outlined here: <http://bradfrost.com/blog/post/just/>

> “Just” makes me feel like an idiot. “Just” presumes I come from a specific background, studied certain courses in university, am fluent in certain technologies, and have read all the right books, articles, and resources. “Just” is a dangerous word.

Cheers,

Jeremy

**Comment by aghassemi** [comment]
@adactio Thanks for the suggestion. /to @Gregable

**Comment by honeybadgerdontcare** [comment]
We'll remove the word "just".

**Comment by honeybadgerdontcare** [comment]
This has now been released.

**Comment by adactio** [comment]
Thank you muchly!
