### ISSUE TITLE
AMP analytics is not accounting about 60% of pageviews at Google Analytics

### ISSUE THREAD

**Issue by pisrael** [ampproject/amphtml#12137]
[plano-oi.html.txt](https://github.com/ampproject/amphtml/files/1489119/plano-oi.html.txt)
## What's the issue?

AMP analytics is not accounting about 60% of page views for the page https://melhorplano.net/planos-oi. The AMP page uses amp-bind and it has a **single code for desktop and mobile** using AMP.

The code of the page was replaced by an AMP version at 25th of October. We instantly noticed a big drop in Google Analytics numbers of pageviews. To further investigate it, we have compared the pageviews and entrances in the page measured by Google Analytics and compared with the proportion of clicks on search results measured by the Search Console. The only source of visitors to the page come from organic search results.

Before AMP:
- Page views / Search clicks = 1.4
- Entrances / Search clicks = 1.01

After AMP
- Page views / Search clicks = 0.6
- Entrances / Search clicks = 0.39

The main issue we've noticed is the drop from 1.01 of entraces / search click to 0.39. As the only source of traffic to the page is organic search, it makes sense that of every click on the page in a search result translate to one entrance to the website through the target page. So, it makes sense for this proportion to stay near 1.0. Therefore, it seems that we losing the measurement on google analytics of almost 60% of the visitors in the page.

Digging deeper, we noticed that the Google Analytics drop is specially on mobile devices. The desktop measurements stayed more or less constant.

The number of clicks measured by Search Console has slightly increased through the period analysed.

* AMP verification for the page is ok.
* There is no error logged using https://melhorplano.net/planos-oi#development=1
* When debugging a mobile browser thru a remote debugger, the calls to GA api seems correct

## How do we reproduce the issue?

HTML of the page at the time of this writing is attached (planos-oi.html.txt).

## What browsers are affected?

We have seen the drop in all browsers for mobile devices, for all browser versions.

## Which AMP version is affected?

AMP version at amp-version="1510180045130"

Could it be an issue related to the combination of amp-bind and amp-analytics?

**Comment by rudygalfi** [comment]
@zhouyx @avimehta Could you investigate?

**Comment by avimehta** [comment]
@pisrael I noticed that one of the hits being sent from the page is as follows: 

`https://www.google-analytics.com/r/collect?v=1&_v=a1&ds=AMP&aip&_s=1&dt=Planos%20Oi%3A%20Controle%20a%20partir%20de%2034%2C90%20e%20P%C3%B3s-pago%20a%20partir%20de%2084%2C90&sr=400x1040&_utmht=1511218509410&cid=amp-bKXhjGIgOzcTTqniMkEcZhPs8EU4C9GRJzs5Vt_ZvN1Esl_shJm_4vAshWsAN8DS&tid=UA-67086253-3&dl=https%3A%2F%2Fmelhorplano.net%2Fplanos-oi%3Fusqp%3Dmq331AQGCAEYASAB&dr=https%3A%2F%2Fwww.google.com%2F&sd=24&ul=en-us&de=UTF-8&t=pageview&jid=0.181229221496495&_r=1&a=6225&z=0.6526476296324502`

In this hit, `dl` is set to `https://melhorplano.net/planos-oi?usqp=mq331AQGCAEYASAB`. I am not sure that the parameter `usqp` is but are you ignoring the parameter in your calculations? Is the parameter significant or should it be ignored?

**Comment by pisrael** [comment]
Hi @avimehta, I believe you've got it! Considering this query parameter `usqp` in the calculations, the proportion of "Entrances" / "Search clicks" becomes 0.97, which is a pretty reasonable number. 

I don't know why AMP is placing this query param on the hit. We don't use it internally.

If this is something that AMP uses for internal accounting, would it make sense to comment that on the documentation of amp-analytics (https://www.ampproject.org/docs/reference/components/amp-analytics) or in other relevant documentation?

Thanks for the insight :)

**Comment by avimehta** [comment]
@pisrael this is probably a bug somewhere in the pipeline. 

@rudygalfi @zhouyx Do you know if viewer is appending this parameter to the location? We might need to strip it before `AMPDOC_URL` is substituted.

**Comment by rudygalfi** [comment]
Regarding `usqp =mq331AQCCAE`: This triggers an experiment that optimizes delivery on the Google AMP Cache. It will go eventually when that experiment is over, but new similar instances of the usage of the parameter may appear in the future. [see: https://groups.google.com/d/msg/amphtml-discuss/-_X2D-OdA7A/EqRNrlT6AgAJ]

It definitely should be ignored if possible. I'm not sure if the right fix would be to account for this on the data processing side or to strip it from `AMPDOC_URL`. cc @cramforce @honeybadgerdontcare

**Comment by honeybadgerdontcare** [comment]
@rudygalfi I thought this was resolved, maybe we need to reopen? See #10624

**Comment by avimehta** [comment]
@rudygalfi It will have to be removed on AMP side for smooth flow. Analytics vendors don't know which variables are important to customers and which are not. Customers know which params are important but can't follow every platform change with a setting change to ignore a param. In general, if the platform is introducing a param, it would be easier and simpler for it to clean it up.

**Comment by pisrael** [comment]
From the point of view of the consumer of analytics it can be hard to understand the metrics correctly if you are unaware of those URLs. In our case, we were holding the rollout of AMP to several pages until we had fixed / clarified how to evaluate the metrics correctly. If it's something that cannot be changed, my suggestion would be to comment it on the amp-analytics documentation, so that other vendors can better understand how to filter it out.

**Comment by cramforce** [comment]
I'm +1 of removing it from the URL as exposed to Analytics. I've asked pubs if they wanted that and there was no clear signal, so I guess we can make a decision :)

**Comment by lannka** [comment]
Discussed offline, ultimately, any cache provider should name those as AMP specific URL params 
(starts with `amp_`, like `amp_js_v`), which will be automatically ignored for reporting.

For now, to quickly and temporarily fix the issue, we will strip off `usqp` param. Expected code change [here](https://github.com/ampproject/amphtml/blob/master/src/url.js#L361).
