### ISSUE TITLE
Use spec-compliant async decoding API

### ISSUE THREAD

**Issue by chrishtr** [ampproject/amphtml#12131]
The HTML spec for declarative async decoding of images has been updated the new syntax is:

<img src=... decoding=async> :  Prefer async decoding
<img src=... decoding=sync> : Prefer async decoding
<img src=... > : User agent decides

AMP pages currently use the <img src=... async> notation, which is no longer the correct syntax.
Safari has already been updated to the new syntax.

AMP pages should update their syntax or the async attribute will have no effect.

Reference: https://github.com/whatwg/html/pull/3221

**Comment by aghassemi** [comment]
related #9465
