### ISSUE TITLE
optoutOfCid does not prevent analytics firing, it just sets cid to empty.

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#12130]
copied from https://github.com/ampproject/amphtml/issues/10663#issuecomment-345522034 by @p2er 

optoutOfCid does no longer stop amp-analytics or prevent amp-analytics initialization after reload. I've build a simple demo to elaborate:

open: https://p2er.github.io/amp-articleslider/amp-analytics-optout.html#development=1
Clear previous analytics optin: localStorage.setItem('amp-store:'+location.origin, '');
Reload
Click "I accept" button in amp-user-notification overlay
See google analytics tracking requests in network panal
Click "Optout of CID and tracking." button
Navigate in amp-carousel to trigger tracking events
See new google analytics tracking requests in network panel (should no longer happen, since user used optout)
Reload
Does not show amp-user-notification overlay
Shows pageview tracking requests (shouldn't be able to initialize amp-analytics after optout)
The optout is even written into the local storage data, but does not seem to have any effect on amp-analytics anymore.
atob(localStorage.getItem('amp-store:'+location.origin));
shows
"{"vv":{"amp-user-notification:amp-user-notification":{"v":true,"t":1511102520471},"amp-cid-optout":{"v":true,"t":1511102520470}}}"

/to @zhouyx @rudygalfi setting to P0 as it looks like a regression.

**Comment by zhouyx** [comment]
This is expected and not a regression. After opt out of CID, we DO set all cid to empty. 

Right now we don't support user opt out of analytics tracking. As say, it can only be achieved by using amp-user-notification to opt in to analytics tracking, no vice versa. 

Opt out of analytics tracking can be a future feature request. I'll lower priority to P3.

**Comment by rudygalfi** [comment]
As @zhouyx said, this is working as intended. From this issue, we can extract a feature request, which is being tracked at #10663.
