### ISSUE TITLE
Integrate Viralize on Google AMP AdNetwork

### ISSUE THREAD

**Issue by canemacchina** [ampproject/amphtml#12148]
Hi,

I work for Viralize (viralize.com) and we would like to integrate our player into your ad network list.
Can I start coding and open a pull request (linked to this issue) or do I have to do something else before?

Thanks!
Lorenzo

**Comment by aghassemi** [comment]
@canemacchina Thanks for interest in adding your network. Please follow https://github.com/ampproject/amphtml/tree/master/3p#ads for guidance.
