### ISSUE TITLE
<amp-form> submit action fails on iOS devices, when served from cache

### ISSUE THREAD

**Issue by bhavyasaggi** [ampproject/amphtml#12149]
When the amp-page is cached and is served by Google, then the 'submit' event on the form fails to respond to appropriate events on IOS devices.
E.g.
[Is google cached amp-page](https://www.google.co.in/amp/s/www.makaan.com/lite/pune-residential-property/buy-property-in-pune-city)
[Is the amp version hosted by us](https://www.makaan.com/lite/pune-residential-property/buy-property-in-pune-city)

To Reproduce:
1. Open the above Google-cached amp-page on an iOS device.
2. Press 'Connect Now' on any of the listing.
3. Provide a valid/generic phone number
4. Press 'Connect Now'
5. Notice that it throws an error 'phone number not valid'
-- 
6. Open the page hosted by us on our version on an iOS device.
7. Press 'Connect Now' on any of the listing.
8. Provide a valid/generic phone number
9. Press 'Connect Now'
10. Notice that it proceeds successfully.

PS: The URL used in post of the form is same and responds without any bias. All CORS based issues are already resolved.

PPS: Following is a snippet of the code:
`<form id="amp-lead-stage1-form" class="amp-lead-content" method="post" action-xhr="/amp/apis/nc/lead/submit" target="_top" on="submit: amp-lead-stage1-invalidPhone.hide;
				submit-success:
				AMP.setState({leadEnquiry_data:{stage1:event.response.data}}),
				amp-lead-stage1.hide,
				amp-lead-stage2.show,
				amp-lead-stage2-OtpOnCall-button.show,
				amp-lead-stage2-OtpOnCall-notif-wait.hide,
				amp-lead-stage2-OtpOnCall-success.hide,
				amp-lead-stage2-OtpOnCall-error.hide,
				amp-lead-stage2-resendOtp-button.show,
				amp-lead-stage2-resendOtp-notif-wait.hide,
				amp-lead-stage2-resendOtp-success.hide,
				amp-lead-stage2-resendOtp-error.hide,
				amp-lead-stage3.show;
				submit-error:
				AMP.setState({leadEnquiry_data:{stage1:{isVerificationRequired:'true'}}}),
				amp-lead-stage1.show,
				amp-lead-stage1-invalidPhone.show,
				amp-lead-stage2.hide,
				amp-lead-stage2-OtpOnCall-button.show,
				amp-lead-stage2-OtpOnCall-notif-wait.hide,
				amp-lead-stage2-OtpOnCall-success.hide,
				amp-lead-stage2-OtpOnCall-error.hide,
				amp-lead-stage2-resendOtp-button.show,
				amp-lead-stage2-resendOtp-notif-wait.hide,
				amp-lead-stage2-resendOtp-success.hide,
				amp-lead-stage2-resendOtp-error.hide,
				amp-lead-stage3.hide;">`

> Tested on chrome, firefox, safari browsers  with [Powered by AMP ⚡ HTML – Version 1510180045130 ] and the issue persists

> The Issue is present since 20-Nov-2017

**Comment by cvializ** [comment]
After initial investigation I think it is a problem with the headers of the response from the `action-xhr` URL, not a problem with the cache. 

<img width="1000" alt="screen shot 2017-11-28 at 1 47 05 pm" src="https://user-images.githubusercontent.com/2363700/33345881-af3766bc-d442-11e7-8523-6aaf2b3c4b69.png">

The message invalid phone number appears because that message is shown if the request fails for any reason, not just if the phone number is invalid.

I believe the server logic for the response is sending two URLs in the value of the `Access-Control-Allow-Origin` header. Can you verify that the correct headers are sent by the server when the form is submitted from the cache in iOS Safari?

**Comment by bhavyasaggi** [comment]
We followed the response header specification as described in [here](https://github.com/ampproject/amphtml/blob/master/spec/amp-cors-requests.md#ensuring-secure-responses).

Following is a snippet of the request & response header for a iOS device simulated on Google Chrome:

Response Header
> Accept-Ranges:bytes
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:https://www-makaan-com.cdn.ampproject.org
Access-Control-Expose-Headers:AMP-Access-Control-Allow-Source-Origin
Age:0
AMP-Access-Control-Allow-Source-Origin:https://www.makaan.com
Connection:keep-alive
Content-Encoding:gzip
Content-Type:application/json; charset=utf-8
Date:Wed, 29 Nov 2017 06:23:35 GMT
Server:nginx/1.10.3
Set-Cookie:user_enquiry_info={"name":"","email":"","phone":9876543210}; Path=/
Transfer-Encoding:chunked
Vary:Accept-Encoding,X-Mobile
Via:1.1 varnish-v4
X-Cache:MISS
X-Varnish:12494836

Request Header
> Accept:application/json
Accept-Encoding:gzip, deflate, br
Accept-Language:en-GB,en-US;q=0.9,en;q=0.8
Cache-Control:no-cache
Connection:keep-alive
Content-Length:2407
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryMctpAoaENDTH8iPI
Cookie:XCP=9b407925-609f-4407-9d18-937f6af5a237; websiteversion=new; GA_SOURCE_ACTUAL="(direct)"; GA_MEDIUM_ACTUAL="(none)"; LANDING_PAGE="https://www.makaan.com/"; USER_FROM="(direct)"; USER_MEDIUM="(none)"; USER_FROM_PPC=FALSE; iris_id=3a7f01de-17ae-496e-abd3-df627cb6a669; connect.sid=s%3AjR7zbNlBgn-VULf_vXmMzBMz28Cs3eDO.Z4HjQhIcebcc1wd9kPtYE6TdsbBSBbFDqRnAM2zkNKY; AMP_TOKEN=AHTRwNOhiv4nDafUhzbSBX9qqhrwKRwU0dLghofZE4fukB59wCdgXdvWW6QXrm7Wg_v4SnrOyKhevHHrgHXEsNjV; G_ENABLED_IDPS=google; _ga=GA1.2.amp-crD06tZtR_qEFpidm6M1Uz_JbXGi-U0AbPITQRkayLl7li1CL8Z8ltvWoJoqJRs7; _gid=GA1.2.768457239.1511933116; USER_IP=10.0.0.44; REF_URL="https://www.makaan.com/"; user_enquiry_info={"name":"","email":"","phone":9876543210}; amplitude_idmakaan.com=eyJkZXZpY2VJZCI6IjM2Nzk1NjQ3LTNiOWYtNGI4Zi04MzkzLTYyNDc4ZmJiMTNjMlIiLCJ1c2VySWQiOm51bGwsIm9wdE91dCI6ZmFsc2UsInNlc3Npb25JZCI6MTUxMTkzMzExNTU4MiwibGFzdEV2ZW50VGltZSI6MTUxMTkzNjU5NzIzMiwiZXZlbnRJZCI6MTI4LCJpZGVudGlmeUlkIjoyLCJzZXF1ZW5jZU51bWJlciI6MTMwfQ==
Host:www.makaan.com
Origin:https://www-makaan-com.cdn.ampproject.org
Pragma:no-cache
Referer:https://www-makaan-com.cdn.ampproject.org/v/s/www.makaan.com/lite/pune-residential-property/buy-property-in-pune-city?amp_js_v=0.1&usqp=mq331AQGCAEYASAB
User-Agent:Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1

**Comment by cvializ** [comment]
The iOS Simulator on macOS gives a different error than an actual iOS device. 
<img width="563" alt="screen shot 2017-11-29 at 9 56 42 am" src="https://user-images.githubusercontent.com/2363700/33390717-a390cda4-d4eb-11e7-9bcd-2ac8b68e14cd.png">

If you change the value of the `Access-Control-Allow-Origin` header to `*` does it solve the problem? I don't recommend this as a solution, only a troubleshooting step.

**Comment by bhavyasaggi** [comment]
Thanks for the suggestion of trying iOS simulator on OS X (Safari)
We finally made it work, but here are some of the findings which might prove useful to someone who encounters it in future.

1. <amp-form> sends  cookies with the post request from google's cache to our website, [making it a CORS request]. This causes the 'credentials' flag to be set true implicitly.
Because of this, the response must contain "`Access-Control-Allow-Credential`" header set as `true`.
And because of the standard, when '`Access-Control-Allow-Credential`' response header is set, the value of '`Access-Control-Allow-Origin`' can not be '`*`'.

2. Apple has totally disabled third-party cookies, and the error manifests itself in form a of a CORS error. To mitigate this, we removed the '`Set-Cookie`' response header.

3. Apple systems also expects a singleton value of '`Access-Control-Allow-Origin`', but we had an extra comma(`,`) [which is a common delimiter in the response headers] towards the end of it.
-- While Chrome and similar systems took it as the valid value by removing comma(,), meanwhile Safari and iOS did not and took the entire string with comma(,) as the '`Access-Control-Allow-Origin`' response header's value.
-- Chrome does not show the comma at the end in the web-inspector in parsed more, but when seen as raw, there was a comma(,) at end of '`Access-Control-Allow-Origin`' response header.

To give more appropriate insight, here is a snapshot of before and after of our response header

Response header before
> Accept-Ranges:bytes
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:https://www-makaan-com.cdn.ampproject.org,
Access-Control-Expose-Headers:AMP-Access-Control-Allow-Source-Origin
Age:0
AMP-Access-Control-Allow-Source-Origin:https://www.makaan.com
Connection:keep-alive
Content-Encoding:gzip
Content-Type:application/json; charset=utf-8
Date:Wed, 29 Nov 2017 06:23:35 GMT
Server:nginx/1.10.3
Set-Cookie:user_enquiry_info={"name":"","email":"","phone":9876543210}; Path=/
Transfer-Encoding:chunked
Vary:Accept-Encoding,X-Mobile
Via:1.1 varnish-v4
X-Cache:MISS
X-Varnish:12494836

Response header after
> Accept-Ranges:bytes
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:https://www-makaan-com.cdn.ampproject.org
Access-Control-Expose-Headers:AMP-Access-Control-Allow-Source-Origin
Age:0
AMP-Access-Control-Allow-Source-Origin:https://www.makaan.com
Connection:keep-alive
Content-Encoding:gzip
Content-Type:application/json; charset=utf-8
Date:Wed, 29 Nov 2017 06:23:35 GMT
Server:nginx/1.10.3
Transfer-Encoding:chunked
Vary:Accept-Encoding,X-Mobile
Via:1.1 varnish-v4
X-Cache:MISS
X-Varnish:12494836

Thank you for the help.
Also I'd like if there could be some way in `<amp-form>` requests that way we could not send the cookies with the request so that the '`Access-Control-Allow-Origin`' response header could be set as `*` for CORS requests ?
If not, I'd like to suggest it as a feature.

**Comment by cvializ** [comment]
I'm glad I could help, and thank you for sharing what you learned so it could help others in the future : ) Right now there is no way to configure sending the cookie with the request. If you'd like, feel free to open a feature request issue.
