### ISSUE TITLE
Intent To Implement: Embed Ventuno Player

### ISSUE THREAD

**Issue by ventunodev** [ampproject/amphtml#12144]
We would like to build a custom component that would allow our publishers to embed **Ventuno Player*** in their AMP Pages.
  We will use our embed player internally to playback media. The embed player will look something like this: 
 https://web.ventunotech.com/embed/vtnEmbed.html?pType=ep&pubKey={publisher_id}&slot={slot_id}&pTitle={article_title}&pURL={article_page_url}&pMeta={article_meta}

***Ventuno Player** is a custom HTML5 video player that we provide to our publishers. To know more about Ventuno, please visit our [site](http://www.ventunotech.com/in/).

  The amp markup will look like : 
```
  <amp-ventuno-player layout="responsive" width="640" height="360"
	data-player="ep" // Player Type
	data-pubid='{publisher_id}' // Ventuno Provided Publisher Id
	data-slotid='{slot_id}' // Ventuno Provided Slot Id
	data-title='{article_title}' // Article Title. In case the publisher wants videos based on the article meta 
	data-url='{article_page_url}' // Canonical URL of the article. In case the publisher wants videos based on the article meta
	data-meta='{article_meta}'> // Article keywords.  In case the publisher wants videos based on the article meta
  </amp-ventuno-player>
```
We will be starting development of the component soon. It would be nice if you could tell us if anything has to be changed.

**Comment by aghassemi** [comment]
@ventunodev LGTM, looking forward to the PR.

You also need a `postMesssage` API for your player than can be used to implement the [video-interface](https://github.com/ampproject/amphtml/blob/master/src/video-interface.js).

The video-interface is a common API that AMP expects all video players to implement. This allows AMP to treat all video players the same and to use it to provide common UX across players such as autoplay, dockable videos, managing playback across players, etc... The interface is fairly straightforward: common methods and events such as `play`, `pause`, `muted`, etc..

Please look at [amp-youtube.js](https://github.com/ampproject/amphtml/blob/master/extensions/amp-youtube/0.1/amp-youtube.js) for a reference implementation which uses `postMessage` to do the communication between the AMP component and the iframed video player to implement the interface. 

[amp-brid-player](https://github.com/ampproject/amphtml/blob/master/extensions/amp-brid-player/0.1/amp-brid-player.js) is another good reference for a layer that implements the interface.

**Comment by ventunodev** [comment]
@aghassemi 
Thanks for the info. We have setup a very rudimentary `postMessage` API for our player.
We will take a look at those extensions as well.

**Comment by aghassemi** [comment]
Closing since PR is open but inactive.
