### ISSUE TITLE
amp-list inside amp-form inside amp-shadow does not work on Firefox

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#12151]
Using amp-list inside AMP form on Firefox does not show any data.
You can reproduce the problem by looking at:
[Favorite Button sample](https://ampbyexample.com/advanced/favorite_button/)

If you open the sample on Chrome, you should see an heart shape on which you can click to favorite content.
If you open the sample on Firefox, the heart is not visible.

@sebastianbenz FYI

**Comment by aghassemi** [comment]
Phew! it's not `amp-list` just the SVG icon for the button doesn't work in FF. re-routed to https://github.com/ampproject/amp-by-example/issues/1015 

@kul3r4

**Comment by kul3r4** [comment]
@aghassemi Thanks for looking into that! That was an unfortunate coincidence that we were using svg. However Repubblica is still having this problem on Firefox and they are not using svg.
Take a look at this: [https://rep.repubblica.it/pwa/generale/2017/11/20/news/merkel_in_crisi-181657611/](https://rep.repubblica.it/pwa/generale/2017/11/20/news/merkel_in_crisi-181657611/)

Scroll down and there is a section "Vota questo articolo". Stars are showing when loading on Chrome, but not when loading on Firefox.

**Comment by kul3r4** [comment]
Actually, I think this may be related to the Polymer shell.
Try the [autosuggest sample](https://amp-by-example-staging.appspot.com/polymer/detail/advanced/autosuggest/)  where the autosuggest AMP is embedded. In there I cannot see the list of cities being populated.

**Comment by aghassemi** [comment]
/to @cvializ 
In firefox in the embeed case, I see a "template not found" error in `amp-list`
I believe problem lies somewhere with `maybeFindTemplate_` code.

**Comment by kul3r4** [comment]
@cvializ what's the status on this?

**Comment by cvializ** [comment]
It is difficult to reproduce on the https://amp-by-example-staging.appspot.com/polymer/detail/components/amp-list link because there are CORS errors. I will try to repro in a local Polymer demo.

**Comment by cvializ** [comment]
I will verify that this is fixed next week when the optin canary goes out.

**Comment by kul3r4** [comment]
@justforfun FYI

**Comment by kul3r4** [comment]
@justforfun I can see the voting on Firefox, snapshot attached 
![firefox-voting](https://user-images.githubusercontent.com/820891/34776412-b7dd94a6-f60e-11e7-843e-135bb4ccbf97.png)
