### ISSUE TITLE
gulp lint is not picking up custom rules

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#12157]
custom rules defune in `build-system/eslint-rules` don't seem to be picked up when `gulp lint` is executed.

We have a custom rule for `TODO` or `spread operator` but having those in the code still pass the lint.

/to @rsimha-amp @erwinmombay

**Comment by aghassemi** [comment]
never mind, Visual Studio does not pick it up, gulp lint does.

**Comment by rsimha-amp** [comment]
This issue will become relevant once we update the version of eslint we use. I'll post an update at that time

**Comment by rsimha-amp** [comment]
@aghassemi I was able to update eslint to the latest version. Perhaps that might fix the visual studio scenario?

**Comment by rsimha-amp** [comment]
This will be fixed in #13474
