### ISSUE TITLE
[feature requests] preload attribute for amp-audio

### ISSUE THREAD

**Issue by gustavopaes** [ampproject/amphtml#12166]
## What's the issue?
amp project could implement preload attribute for amp-audio. Today the browser make some downloads unnecessarily in most of cases.

https://www.w3schools.com/tags/att_audio_preload.asp

**Comment by nainar** [comment]
Hi, I am claiming this issue.

**Comment by gustavopaes** [comment]
At AMP Validator, I am getting following message:
```The attribute 'preload' may not appear in tag 'amp-audio'.```

Is it avaliable to use?

**Comment by honeybadgerdontcare** [comment]
@gustavopaes This change is not yet live for validation. It will probably be another week or two.
