### ISSUE TITLE
Short AMP docs sending wrong documentHeight

### ISSUE THREAD

**Issue by peterjosling** [ampproject/amphtml#12172]
Hey, running into an issue with short AMP docs (smaller than the height of the viewport) and documentHeight messages. documentHeight is calculated using scrollHeight instead of the height of the content, so in this case you get a height value which is taller than the actual height of the content.

I can see that this case was originally handled when documentHeight events were implemented (https://github.com/ampproject/amphtml/commit/ac741f6d448305570659d0eae3c11c9049ae0fef), but this change was reverted before the PR was merged. Is there a reason for this? Would it be possible to add this behaviour back in?

**Comment by jridgewell** [comment]
No reason that I know of. Would you submit a PR to fix?
