### ISSUE TITLE
Add support for sound effects in amp-story

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#12175]
We could add support for playing sound effects that are tied to transitions in `amp-story`.  One proposal to achieve this is to expose an attribute like `animate-in-sfx` that takes a named preset of a sound effect to play, or potentially a URL of a sound effect to play.  For example:

```html
<amp-story-page>
  <amp-story-grid-layer template="vertical">
    <p id="line1" animate-in="fly-in-left" animate-in-duration="3s" animate-in-sfx="whoosh">
      This example is…
    </p>
    <strong id="line2" animate-in="fly-in-left" animate-in-after="line1" animate-in-sfx="kablam">
      AWESOME!
    </strong>
  </amp-story-grid-layer>
</amp-story-page>
```

/cc @alanorozco @cramforce

**Comment by cramforce** [comment]
Could this be a feature of `amp-animation` instead (or first before we add sugar like in your proposal). I think we may need improved granularity.

One thing to consider: Delegate playback to viewer which might be able to play sound on first slide.
