### ISSUE TITLE
Add support for looping animations in amp-story

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#12174]
Right now, we support entrance transitions via the `animate-in` property on descendants of `amp-story-grid-layer`.  We should consider specification changes that also allow publishers to create animations that loop for the duration of the time that the user is on the `amp-story-page`.

For example, we could have something like ```html<div class="spinner" animate="rotate" animate-duration="2s">```, where duration controls how long a single iteration of the animation is.

Alternatively, we could figure out how to effectively open up usage of `<amp-animation>` within stories, but I suspect this will be challenging, since it is not aware of the constraints that `<amp-story>` adds.

/cc @alanorozco

**Comment by newmuis** [comment]
Maybe we can leverage the API from [`<marquee>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/marquee)?  The relevant attributes:

> `loop`
> Sets the number of times the marquee will scroll. If no value is specified, the default value is −1, which means the marquee will scroll continuously.
> 
> `behavior`
> Sets how the text is scrolled within the marquee. Possible values are `scroll`, `slide` and `alternate`. If no value is specified, the default value is `scroll`.

Maybe we can modify `behavior` to encapsulate whether we play the animation forwards or alternating forwards, then backwards.

**Comment by alanorozco** [comment]
(I don't even care about the technical details, **let's bring `<marquee>` back**.)

How does `behavior` apply in this case?

**Comment by newmuis** [comment]
Imagine I specify `animate-in="zoom-in" animate-in-duration="5s"`.  This will slowly zoom the image in over the course of 5 seconds.  Assuming we want to loop the animation, what happens at the 5 second mark?

- The image jumps back to its fully zoomed out state, to start zooming in again
- The image zooms back out over the course of (another) 5 seconds, back to its original state, then starts zooming in again

We could put names to these strategies (or others) and accept them as values of `behavior`.

**Comment by alanorozco** [comment]
Oh, I see. I was under the impression that looped animations would use a different API than `animate-in`.

My only concern is that by reusing the attribute we won’t be able to combine entrance + looping with different presets, assuming that’s something we want to do.

**Comment by newmuis** [comment]
Valid concern.  I'll hash it out with @hongwei1990

**Comment by alanorozco** [comment]
> combine entrance + looping with different presets

...then again that behavior can be composed by nesting two elements and assigning each preset respectively. So maybe it's a non-issue, as long as we document it.
