### ISSUE TITLE
Keep versions of AMP build tools and dev dependencies up to date

### ISSUE THREAD

**Issue by rsimha-amp** [ampproject/amphtml#12181]
In addition, set up an automated means of periodically rolling forward the versions in `package.json` and `yarn.lock`

/cc @cramforce

**Comment by rsimha-amp** [comment]
After the above PRs are all merged, all dependencies in the AMP toolchain will be at their latest versions.

We can then look into using https://github.com/integration/greenkeeper and https://github.com/greenkeeperio/greenkeeper-lockfile to keep the dependencies rolling forward.

**Comment by erwinmombay** [comment]
I can't seem to install it to "ampproject/amphtml" and only allows me to install greenkeeper on my personal projects (i might not have enough access on the parent org)

**Comment by rsimha-amp** [comment]
Thanks. Let's wait for @cramforce to help with this.

**Comment by cramforce** [comment]
The new integration now needs write access to code. We need to check whether that is OK security wise.

**Comment by rsimha-amp** [comment]
@cramforce @erwinmombay See the section titled "Github Integrations" at https://blog.greenkeeper.io/greenkeeper-2-0-release-da8f8f476c88

It appears that Greenkeeper only needs access to our metadata files (`package.json`, `.travis.yml`, and likely `yarn.lock`). I wonder if we can restrict access to just those files via the Github Integrations API (https://github.com/blog/2226-build-an-integration-for-github)

**Comment by cramforce** [comment]
I checked and they are whitelisted. Should now be configured.

**Comment by rsimha-amp** [comment]
@cramforce Thanks.

For Travis CI integration of `greenkeeper-lockfile`, we'll need to add a token called `GH_TOKEN`, either to https://travis-ci.org/ampproject/amphtml/settings, or to `.travis.yml` after encrypting it.

See https://github.com/greenkeeperio/greenkeeper-lockfile#setup

If you can generate and send me the `GH_TOKEN` internally, I can encrypt it and add it to `.travis.yml`.

**Comment by rsimha-amp** [comment]
For posterity, here are the installation steps for greenkeeper:

https://greenkeeper.io/docs.html#installation

**Comment by rsimha-amp** [comment]
@cramforce @erwinmombay `greenkeeper` and `greenkeeper-lockfile` are now enabled and acrtive for ampproject/amphtml. See https://account.greenkeeper.io/account/ampproject

We're currently using a `GH_TOKEN` with only `public_repo` access. Now, it's wait and watch until the next dependency gets updated, at which point we should expect an automatically generated PR that updates `package.json` and `yarn.lock`.

We can close this bug once that happens, and we're satisfied that all went well.

**Comment by rarkins** [comment]
@rsimha-amp It's perhaps a little late, but would you consider [Renovate](https://github.com/apps/renovate) for this purpose? 

It comes with native support for lock file generation - including immediate `yarn.lock` regeneration any time there is a conflict or the file is out of date with `master`. This means you don't need to worry about putting a GitHub token on your CI either. 

It also supports a feature for scheduled "maintaining" of `yarn.lock` even if the dependencies in `package.json` hasn't had changes, e.g. the lock file can be regenerated weekly to ensure it's kept fairly up to date and doesn't lag behind released patches.

Finally, it supports customisable grouping and scheduling, one example could be that you group all `karma`-related packages into one PR and only update them monthly, to reduce the amount of "noise" on the repository. Another example is to group together all `babel` packages every time if they are being published together from the same monorepo anyway. 

Renovate is currently in use by some other pretty big orgs on GitHub like @angular, @mozilla and @yarnpkg; I would be happy to help set it up and ensure it's configured as you need it. And in case it wasn't obvious from its description, it's an open source product and completely free GitHub App (including for private repositories and organizations).

**Comment by rarkins** [comment]
You can see an example of a Renovate PR here: https://github.com/algolia/react-instantsearch/pull/835

Note how:
- It groups multiple package updates into a single PR *and* single commit
- The lock file update is also included in the single commit

If a new version of those packages is released, then that PR will be updated *in place* without needing any human intervention. The branch will be rebased/regenerated in such a way that there will still be just one commit there, with whatever is the latest version available.

Here is another PR in the same repository that helps illustrate this a little: https://github.com/algolia/react-instantsearch/pull/831

The PR was actually created with v3.0.1 initially, but it was appropriate to update to. v3.0.2 was subsequently published and the PR was updated, but you still see just a single commit that can be easily rebase merged onto your master branch.

**Comment by rarkins** [comment]
@cramforce @rsimha-amp I am quite shocked and disappointed to see my relevant/on-topic suggestions to this thread deleted here. I took a long time to write these suggestions for the project and have no way to recover them myself. What is the justification for this censorship in a public project and does Google's governance cover deleting user comments at any time without justification?

@cramforce if you have GitHub email notifications enabled you should still be able to see the original content and how it was relevant to this - still open - issue.

Note: these comments were posted prior to me discovering the token security leak and had nothing to do with that topic.

What I see is this:

![image](https://user-images.githubusercontent.com/6311784/34903200-bf79ac52-f82c-11e7-8532-81f6868b9fcd.png)

**Comment by rsimha** [comment]
Update: We now use Renovate to keep our dependencies up to date.
