### ISSUE TITLE
Always show amp-story audio icon until #11857 is fixed

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#12190]
Right now, the audio icon's appearance is unreliable due to #11857.  Until this issue is fixed, we should just always show the audio icon.

**Comment by sanjsanj** [comment]
@choumx As I attempt to work on the [issue](https://github.com/ampproject/amphtml/issues/11857) to fix the audio check for media in amp-story should I do this too?

I could hypothetically just `return true;` in the `hasAudio()` method for MediaElements Class in amp-story.

https://github.com/ampproject/amphtml/blob/9cd8a42d2477640ccf2639cca56670592df2366f/extensions/amp-story/0.1/page-element.js#L300-L305

**Comment by choumx** [comment]
Sure, that should work! Thanks @sanjsanj.
