### ISSUE TITLE
Amp-analytics - Google Internal parameter ( USQP) is being sent with page views

### ISSUE THREAD

**Issue by grantkemp** [ampproject/amphtml#12198]
Component : Amp-analytics using Google Tag Manager
## What's the issue?
Currently we are seeing Google's internal parameter for their Testing versions being passed to AMP -Analytics tag manager instances. This results in urls which look like 
`/page?usqp=mq331AQGCAEYACAB` being tracked alongside `/page`. 
This creates a higher cardinality with the analytics data and requires clean up on the analytics side via a filter or cleaning up outside of GA.
Briefly describe the bug/feature request.
Please can you automatically filter these parameters before they get logged via GTM to GA

## How do we reproduce the issue
It seems to be inconsistent - it is encountered on pages which are being tested by google ( roughly 50% of visits to that Page)

If this is a bug please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else.  Then provide step-by-step instructions for reproducing the issue:
- Not possible

## Which AMP version is affected?
Amp- Analytics using GTM
Version - 1510180045130
![image](https://user-images.githubusercontent.com/751115/33179535-a8d645f2-d061-11e7-8f40-c3f6759719cf.png)

Solution: 
Its possible to log the page path directly / filter it in the amp -analytics component before its sent to GA.

**Comment by aghassemi** [comment]
@grantkemp Please see https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/amphtml-discuss/JzD_7rH7nmo/uT9zaUaCAAAJ for details and related discussions.

/to  @zhouyx  @rudygalfi   
/cc @cramforce

**Comment by cramforce** [comment]
Active discussion in #12137
