### ISSUE TITLE
amp-maps

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#12209]
similar to vendor-specific video components: provides default placeholder and potentially does additional resource management for embedded maps like Google Maps (needs understanding of what other map embeds might be needed)

/cc @aghassemi

**Comment by aghassemi** [comment]
Related ( https://github.com/ampproject/amphtml/issues/11985 )
Closing https://github.com/ampproject/amphtml/issues/11985 in favor of this.

**Comment by aghassemi** [comment]
We likely need to take the video player approach and do `amp-x-map` as API and feature set is different across map providers. We could implement a common interface across them if needed similar to video-interface.

**Comment by joshcp** [comment]
Evaluating options for including maps in a travel-related website. Glad to see this is already an open feature request. Following!

**Comment by ericlindley-g** [comment]
@dbarcosb and @joshcp — glad to hear this would help!  Are you able to share what map providers and features are required for the travel sites you have in mind? I ask because the likely path is to make a separate component for each map provider (e.g. amp-google-maps), and each required feature may need an implementation in the API.

Thanks!

**Comment by dbarcosb** [comment]
The map we have in mind is from Google Maps. Google Maps Static API is currently used to create the image placeholder and when the user taps on it, the map is created with Google Maps JavaScript API. This option lets us customize maps with our own places of interests and icons. Thanks!

**Comment by Pateriack** [comment]
+1 for this! 

amp-story-page-attachment does not allow for amp-iframes, but it would likely allow for something like this. A big help for my use case!

Has there been any design or implementation work done on this one yet? @aghassemi

**Comment by aghassemi** [comment]
@Pateriack this is not prioritized from out end since `amp-iframe` handles it. I see the point about more restrict formats like `amp-story` and `amp 4 email` needing this.

@newmuis thought on priority of supporting maps in amp-story?

**Comment by newmuis** [comment]
I would say this is actually reasonably high priority for us.  As [announced at AMP Conf](https://youtu.be/i7Br9GmpQWs?t=1003), Google is focusing on providing travel stories experiences, which would lead me to reasonably expect a drastic increase in travel stories (which I would expect may want to use maps).

**Comment by charlessyms** [comment]
I'd like to get in on this too. I've recently implemented Places API with autocomplete on my main website to prompt users with locations when they are entering pick-up location. Unable to implement this on AMP but feel it should be fairly easy. Please!

**Comment by newmuis** [comment]
@nainar we have a contributor who's interested in contributing this, if we have the product nailed down.  Do you think we're in a good place to do this?

**Comment by Malvoz** [comment]
@aghassemi 

> We likely need to take the video player approach and do `amp-x-map` as API and feature set is different across map providers.

The W3C [Maps For HTML Community Group](https://www.w3.org/community/maps4html/) is iterating over use cases and requirements for standardizing maps on the web - while not complete - the draft report lists [capabilities](https://maps4html.org/HTML-Map-Element-UseCases-Requirements/#map-viewers) (of a potential native map viewer) required for [the use cases](https://maps4html.org/HTML-Map-Element-UseCases-Requirements/#use-cases) and which frameworks currently support each capability and to what extent, perhaps you'd find it helpful.
