### ISSUE TITLE
Support for styling loading states

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#12212]
More and more AMP features allow loading of external data. It should be possible to react to these loading states in CSS. Examples:

- `amp-list` is loading
- `amp-list` is loading after the `src` was changed with `amp-bind`
- `amp-form` is submitting.
- …?

Some of these likely already expose their state to CSS, but I'm wondering whether we need a unified approach and potentially some ABE content.

**Comment by ericlindley-g** [comment]
+1

This is planned as part of the element-level infinite scroll work (to load more product listing cards, for instance, based on a server call), and agreed that this should be generalized to support all of these cases.

**Comment by aghassemi** [comment]
Related #10802 

`form submitting`  support was added a few months ago ( https://github.com/ampproject/amphtml/pull/9442 ) but contained (similar to other form states) to a child element.

**Comment by cramforce** [comment]
Would this also make sense for cases like changing the src of an image and showing a loading indicator until the new image has loaded.
