### ISSUE TITLE
AMP.setState not working on amp-youtube PLAY event

### ISSUE THREAD

**Issue by SoleSS** [ampproject/amphtml#12210]
Steps to reproduce problem:

add amp-youtube object
add any other object <amp-img src=... [class]="objClass">
add on event to amp-youtube
but when you click play button of youtube object - nothing happens... (on="tap:..." - works perfect)

```
<amp-youtube
                    on="play:AMP.setState({prom: 'hidden'})"
                    data-param-controls=0 data-param-rel=0 data-param-showinfo=0 data-videoid="SOME VIDEO ID" layout="responsive" width="1200" height="550"></amp-youtube>

<div class="width-100pc block-overlay top-20pc absolute" [class]="prom">SOME TEXT</div>
```

idea is: on play button click hide all elements which are positioned above video and of course on pause\end of video elements have to be returned to unhidden state... (with on="pause... event)

**Comment by aghassemi** [comment]
@SoleSS There is no `play` event exposed on `amp-youtube`. https://github.com/ampproject/amphtml/issues/8971 is the feature request for it however until we can reliability confirm that the `play` event is based on a user-interactin ( e.g. not `autoplay` ) it will not be allowed to `setState` regardless.

As mentioned on #12165 , you can use a custom overlay to capture the first tap to hide your container. See  https://ampbyexample.com/advanced/click-to-play_overlay_for_amp-video/  for a sample.

**Comment by aghassemi** [comment]
Closing in favor of https://github.com/ampproject/amphtml/issues/8971
