### ISSUE TITLE
AMP Ads Load Slowly and have Very LOW CPM 

### ISSUE THREAD

**Issue by TamerMobarak** [ampproject/amphtml#12216]
**I notice a GREAT Fall in my adsense Revenue on my blogger website after I tried the AMP ad form and I also notice that Ads load slowly much after the page load.
How can we tell Google that they must solve this problem, as it makes the whole AMP project "In Vain".**

**Comment by jasti** [comment]
@TamerMobarak sorry to hear that. I've reached out internally to the Blogger team for help and I'd also recommend you do the same by reaching out to Blogger support.
