### ISSUE TITLE
Feature Request: Multiple Columns on AMP Carousel Slide

### ISSUE THREAD

**Issue by zongm** [ampproject/amphtml#12224]
Hi, the current slide seems only support 1 slide column at a time; would love to have multiple columns supported so that the desktop version can have multiple columns not: just like this
https://stackoverflow.com/questions/46213545/show-multiple-column-on-amp-carousel

The stackoverflow workaround:
```
<amp-carousel height="300" layout="fixed-height" type="slides">
    <div>
      <div class="blue-box"> 1 </div>
      <div class="red-box"> 2 </div>
      <div class="green-box"> 3 </div>
      <div class="yellow-box"> 4 </div>
    </div>
    <div>
      <div class="blue-box"> 5 </div>
      <div class="red-box"> 6 </div>
      <div class="green-box"> 7 </div>
      <div class="yellow-box"> 8 </div>
    </div>
    <div>
      <div class="blue-box"> 9 </div>
      <div class="red-box"> 10 </div>
      <div class="green-box">11 </div>
      <div class="yellow-box"> 12 </div>
    </div>
  </amp-carousel>
```
The workaround on stackoverflow would have multiple columns shown on desktop; however, the mobile one will only navigate the top level columns, exactly 1, 5 and 9 columns. Is there any way to make all columns work in mobile with the stackoverflow workaround? or any better way to make it work for both desktop and mobile? Appreciated.

**Comment by aghassemi** [comment]
related: https://github.com/ampproject/amphtml/issues/4626

@zongm as a workaround, you can have two carousels, one for mobile and one for desktop and use `media` attribute to hide/show the one that is a match.

/cc @ericlindley-g : essentially a "responsive carousel FR"

**Comment by aghassemi** [comment]
new version of `amp-carousel` which is in development #20595 will have this feature.
