### ISSUE TITLE
Please turn on 2FA

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#12226]
Hello members of the ampproject GitHub org. We'd like to turn on 2 factor authentication as a requirement for membership. Please turn it on for your account soonish. Independent of AMP that is a good idea anyway. More info https://github.com/blog/1614-two-factor-authentication

@kito00, @040medien, @bpeebles, @abhinavralhan, @harquail, @takaakitalks, @duromano, @sebaperez, @amplesample, @paulanthony, @nzukoski, @rooftopninja, @rajkumarsrk, @epeetz, @felipk, @mhc-gh, @blueyedgeek, @sahirsait, @darxector, @ampsauce, @martinkotynek, @rgthree, @arealenydn, @comscorethomas, @gcovato, @plaub, @cypherlou, @amoad-amoe, @luizcruz, @wjfang, @kbnaik, @lswang1618, @mikepmtl, @rannazhou, @parisholley, @lisaychuang, @jonlim91, @bonifaty, @nkapser, @cecileey, @mkhatib, @socialmkhan, @sidval, @kesslerkoh, @hhumphrey84, @bpaduch, @mattiades, @danbrown1113, @indieisaconcept, @vineetsagar7, @tabajarareis, @techhtml, @gaer87, @ui-xp, @rikiverma, @asmaldone, @jaycribas, @wapo-adops, @nikhilmadan, @simonpain-ffx, @dvdyakonov, @suzyhay, @marcopulina, @renebaudisch, @dublinranch, @pdelgadorodriguez, @rachcurrie, @jamiequiocho, @ovishnepolsky, @powdercloud, @dotandads, @yskoh, @itaykinnrot, @dspattison-google, @adriaan-pelzer, @michaelschultheiss, @gvsboy, @zhoresh, @xuanli, @kakadiadarpan, @lisamayo, @morsssss, @anand-venkatraman, @jaboc83, @kentbrew, @rooke, @subhankar-panda, @purplebabar, @tomremo, @shalabi, @akonchady, @kashyapnitin, @ukmelrogers, @adelinamart, @adrianoam, @timbrockman, @steffenanders, @omar-a-toma, @filijs, @jacintocorral, @xunuo, @weessaam, @ashbressler, @theandyyu, @juliabeizer, @simonhogstromronbol, @juanlizarazo, @ruborg, @joshuaherman, @pearson82, @jessicanorthrop, @sanju2015, @mobusi-ads, @imparvez, @ampprojectbot, @peakpg, @oseydel, @weherr, @drewroberts, @johncantwell, @e2corporation, @eduardogoncalves, @jeffehobbs, @pymossy, @edlea-g, @amphtml-team, @letsila, @rhapsodyai, @dejno, @arpoohsan, @andrewsfg, @johnluther, @mattludwig, @esboyd, @geniee-amp, @isublimity, @bigced, @jasonaaronwilson, @mkendall07, @teleservizi, @yieldmo-rao, @ampwafflebot, @frazjp65, @kolhar730, @oikwsat, @adamthomas, @tjslater, @goldencrystal, @emestud, @fadysamirsadek, thomas, @tjslater, @goldencrystal, @emestud, @fadysamirsadek,

**Comment by aghassemi** [comment]
For anyone removed from the project due to lack of 2FA, please enable 2 factor authentication for your account and follow this [link to request to join again.](https://docs.google.com/forms/d/e/1FAIpQLSeF1PN4Ee7Ke5Hvn4uN_oznV3isr-tfFg7cFRLX2F2OJGhXpw/viewform?c=0&w=1)

Closing the issue as it has been implemented.
