### ISSUE TITLE
amp-story: Unexpected loading dots on desktop

### ISSUE THREAD

**Issue by hongwei1990** [ampproject/amphtml#12228]
**Please only file bugs/feature requests for AMP here.**

## What's the issue?

Loading three dots appear on the "previous" and "next" page. (And the dots looked broken)
 

## How do we reproduce the issue?
We should hide loading status for the "previous" and "next" page preview on desktop 

cc: @alanorozco @newmuis @choumx @prateekbh

**Comment by newmuis** [comment]
#12604 obsoletes the loading dots entirely, in favor of more aggressive preloading of video.

**Comment by prateekbh** [comment]
i am not sure if this can be closed now

**Comment by newmuis** [comment]
I'll close when #12604 is merged and confirm the loading dots no longer show.

**Comment by newmuis** [comment]
#12604 is now merged.
