### ISSUE TITLE
Increase priority of ads to 1 when loaded within a PWA

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#12232]
All of AMP's scheduling constraints need not apply when inside of a PWA because of the benefits that a PWA offers. 
Specifically, for a site like https://m.mynet.com/ it's worth relaxing the ad load constraints because it's on the publisher origin.

**Comment by zhouyx** [comment]
cc @calebcordry

**Comment by lannka** [comment]
@jasti can you explain the PWA benefit that makes ad scheduling meaningless?
And also, why shall we relaxing ad load on pub origin ?

**Comment by jasti** [comment]
This came from a discussion with @dvoytenko. It doesn't make ad scheduling meaningless. It just reduces the need for AMP to tightly orchestrate the ad lifecycle since PWAs, on average, have better performance than your average web page. 

Ad load on pub origin should be a publisher choice - otherwise, the alternate option is to do 'dirty' AMP - which could make things worse.

**Comment by dvoytenko** [comment]
I agree with @jasti. Three thoughts on my part why this could be ok:

1. PWA is performance-attractive setup. Service workers help a lot and soft navigation saves CPU and bandwidth.
2. In the multi-origin case, pages and ads for different origins fight with each other over resources, but PWA only concerns the same origin. There's a clear motivation to make ad load to be sensible.
3. PWAs have other means of showing ads outside AMP that are worth for performance. So, even with more aggressive priority we are probably still do less work in comparison.

**Comment by calebcordry** [comment]
There is a pending PR implementing this behavior. Note: this is checking to see if the site is using the shadow amp binary which, while is what is suggested, not everyone is doing. I asked around and this seems the best decision as the people not doing this aren't going to get all the advantage of `PWAMP` anyway, and may not see the benefit of increased priority. 

I am going to cc/ @pbakaus so he can chime in if he wants to explain more eloquently.

**Comment by jasti** [comment]
@calebcordry since detection is hard, I wonder if we could do this for anything that's not served from the Google cache. @dvoytenko thoughts?

**Comment by calebcordry** [comment]
That seems like a simple bit of logic to write if we choose to do it that way. My only thought is that checking for the shadow amp may encourage users to write their PWA + AMP apps using the suggested structure.

I will defer to someone else to make a decision about how we are defining what is a PWA. Is it just having a service worker vs. having the same origin vs. using the shadow binary? etc.

**Comment by dvoytenko** [comment]
I don't see a problem doing this for shadow case only. Again, big part of my reasoning is that shadow API gives a lot of performance benefits vs other options, so it could relax some constraints in return.

**Comment by calebcordry** [comment]
It seems as though there are really two separate discussions happening here. 

1. Should we increase priority when publishers are using the suggested `PWAMP` implementation with the shadow binary etc. Everyone seems to agree this is a good idea because of the performance benefits of this method.

2. Should we make the same exception for publishers who are hosting amp pages on their own domain?

Since there seems to be a consensus around #1, and this PR changes the priority in this context, I am going to close this issue. I am have opened a new issue #12656 to continue discussion around #2.
