### ISSUE TITLE
amp-analytics[type=googleanalytics] encoding

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#12243]
To whom it may concern:

I use amp-analytics[type=googleanalytics] to send GA beacon and I have some chinese text content filled in custom dimension.

such as the following  sample code:
```javascript
<amp-analytics type="googleanalytics">
    <script type="application/json">
        "vars": {
            "account": "UA-74300583-2",
            "documentGroup": "itemPage",
            "merchandiseId": "100347591196",
            "level1Id": "1234567890-1",
            "level2Id": "1234567890-2",
            "level3Id": "1234567890-3",
            "level4Id": "1234567890-4",
            "level5Id": "1234567890-5",
            "level6Id": "1234567890-6",
            "level1Name": "中文分類測試-1",
            "level2Name": "中文分類測試-2",
            "level3Name": "中文分類測試-3",
            "level4Name": "中文分類測試-4",
            "level5Name": "中文分類測試-5",
            "level6Name": "中文分類測試-6"
        },
        "extraUrlParams": {
            "cg1": "${documentGroup}",
            "cd1": "${level1Id}",
            "cd2": "${level2Id}",
            "cd3": "${level3Id}",
            "cd4": "${level4Id}",
            "cd5": "${level5Id}",
            "cd6": "${level6Id}",
            "cd7": "${level1Name}",
            "cd8": "${level2Name}",
            "cd9": "${level3Name}",
            "cd10": "${level4Name}",
            "cd11": "${level5Name}",
            "cd12": "${level6Name}",
            "cd13": "${merchandiseId}"
        },
        "triggers": {
            "pageview": {
                "on": "visible",
                "request": "pageview"
            }
        }
    </script>
</amp-analytics>
```

Notice the **level1Name** ~ **level6Name**, these are chinese content. I check the beacon content when page refresh and I found the parameter **cd7** ~ **cd12** will encode the content. So Google Analytics report will collect the encoded data and hard to recognize.

You can also click the following link to check it.
[Demo page](https://tw.bid.yahoo.com/amp/item/100347591196)

Have a nice day.

Paul

**Comment by lannka** [comment]
Seems to me another double encoding bug. Let me dig into it.

**Comment by meistudioli** [comment]
hi, @lannka:

Thx for helping. May I know when this fixed will release on prod ?

Paul

**Comment by lannka** [comment]
This will go to canary release next week, where you can test by opt-in canary. One week after that, it will hit prod.

**Comment by meistudioli** [comment]
hi, @lannka:

I chceked my GA report and found this double encoding issue happen again. Looks like code had been rollback.

Could you reopen this issue or should I need to apply a new  issue for this ?

Have a nice day.

Paul
