### ISSUE TITLE
Investigate ui abuse of amp-user-notification

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#1224]
@dvoytenko is concerned about maximum height etc. so we need to figure out what the best way to prevent user abuse.

Related:
https://github.com/ampproject/amphtml/issues/902
https://github.com/ampproject/amphtml/pull/1178

**Comment by dvoytenko** [comment]
My main concern here is actually ensuring that dismiss button is always visible and clickable.

**Comment by erwinmombay** [comment]
@dvoytenko is it worthwhile to measure that ensure visibility etc on the runtime?

**Comment by dvoytenko** [comment]
Yeah, we determined in other projects that this is no longer a concern.
