### ISSUE TITLE
Investigate parallel fetching vs the queued approach on multiple amp-user-notification components

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#1225]
Related:
https://github.com/ampproject/amphtml/pull/1178

**Comment by ericlindley-g** [comment]
@erwinmombay can you say what user-facing benefit this provides?

**Comment by erwinmombay** [comment]
@ericlindley-g currently i don't see anything user facing benefit as there is almost always just 1 amp-user-notification component
