### ISSUE TITLE
Intent to Implement: amp-access multiple auth provider support

### ISSUE THREAD

**Issue by kushal** [ampproject/amphtml#12264]
After the discussion in #2916 and additional discussion offline, we'd like to implement support for having multiple amp-access providers. This could be for orthogonal needs (Provider A unlocks the `beer` elements on the page and Provider B unlocks the `donut` elements on the page) or for overlapping needs (either Provider C or Provider D can unlock the `cheese` elements on the page) by providing an array instead of a single object in the `amp-access` element.

```
<script id="amp-access" type="application/json">
[
 { ... access1 ... },
 { ... access2 ... },
]
</script>
```

Each access object would have the same `authorization`, etc. fields as the current implementation, but we would add an additional field `namespace` which is required for each block if there is an array. Two blocks may not have the same `namespace` value.

 ```
{
  ...
  namespace: 'authprovider1'
}
```

In login links and amp-access conditionals, namespaces could then be used. 

```
<a on="tap:amp-access.foo.login">Log in to foo</a>
...
<section amp-access="authprovider1.foo">
...
</section>
```

To support cases where for performance reasons AMP might not want to wait for all auth providers to return if only one affirmative response is needed, we propose running applyAuthorization_ on the DOM immediately after each authorization response. As a result, 

```
<section amp-access="authprovider1.allowed OR authprovider2.permitted">
...
</section>
```

should become visible as soon as either response is available.

I'm not super familiar with the `amp-access` implementation, so please alert me if this path is likely to encounter any dragons!

**Comment by dvoytenko** [comment]
LGTM
