### ISSUE TITLE
amp-font not recognizing loaded font on iOS

### ISSUE THREAD

**Issue by hctom** [ampproject/amphtml#12262]
We are running a project that serves AMP pages with a custom icon font. This font is preloaded via `<amp-font>` element like this:

```
<amp-font
  layout="nodisplay"
  font-family="icons"
  timeout="5000"
  on-load-add-class="icon-font-loaded"
  on-load-remove-class="icon-font-loading"
  on-error-add-class="icon-font-missing"
  on-error-remove-class="icon-font-loading"></amp-font>
```

The corresponding font face style looks like this:

```
@font-face {
  font-family: "icons";
  font-style: normal;
  font-weight: normal;
  src: url(https://example.com/path/to/fonts/icons.eot?cachebust=20507#iefix) format("embedded-opentype"), 
    url(https://example.com/path/to/fonts//icons.woff2?cachebust=77756) format("woff2"),
    url(https://example.com/path/to/fonts//icons.woff?cachebust=77756) format("woff"),
    url(https://example.com/path/to/fonts//icons.ttf?cachebust=52423) format("truetype"),
    url(https://example.com/path/to/fonts//icons.svg?cachebust=92330#icons) format("svg");
}
```

Using an Android device with Chrome everything works fine when accessing the AMP pages and the icon font is displayed (thus `.icon-font-loaded` class is added to the `<html>` element correctly as implied by the `<amp-font>` element). When using an iOS device (tested in Chrome and Safari), this class never gets added to the `<html>` element, only `.icon-font-loading` is added initially and stays there forever.

Is this a known bug, or are we doing something wrong?

Used AMP version: 1510956201635

Thanks in advance & I appreciate your feedback/help.

**Comment by aghassemi** [comment]
@cramforce Anything ideas off the top of your head? (if not, I will investigate). tl;dr: `icon-font-loaded` state is never reached in iOS

**Comment by cramforce** [comment]
No idea on top of my head. iOS 11 should have full support for the font loading API. Last time I played with it, it actually had fewer bugs than Chrome.

**Comment by sparhami** [comment]
I wasn't able to reproduce this on iOS 11. Perhaps this only occurs on iOS 9 or 10?

It seems a bit odd that the loading class would remain as the the timeout should eventually trigger even if using the font loading fallback.

**Comment by aghassemi** [comment]
deduping with #22623
