### ISSUE TITLE
Links through ampstart-input option don't work on Phone browsers

### ISSUE THREAD

**Issue by bronsonoquinn** [ampproject/amphtml#12266]
## What's the issue?

When I click my client's AMP page through google and then choose an option from the lightbox menu, it will time out and I'll get an AMP error message that says "Can't open page."

## How do we reproduce the issue?

1. While on a phone, run a Google search on "escape rooms" and search for the first AMP page at breakoutgames.com, or go to this URL:
https://www.google.com/amp/s/breakoutgames.com/amp/escape-rooms/
2. At the top, there's a red div with the text "Your Location: Choose". Tap on that and choose any location.
3. Wait a few seconds.
4. You will be redirected to an AMP error screen.

Important: This only works while using a phone. If I am using a browser's developer tools and choose a phone view in the Device Toolbar, it goes to the correct URL. In fact, all other links work correctly, it's only when I access them through the lightbox.

Here's an example of my code:
```
<div class="pad">
    <h2 class="center py4 h2override">Choose your location.</h2>
    <p class="center">
        <select class="lightboxselect ampstart-input" on="change:AMP.navigateTo(url=event.value)">
            <option  value="#"> - Choose a location - </option>
            <option  value="https://breakoutgames.com/birmingham/">AL - Birmingham</option>
            ...
        </select>
    </p>
</div>
```

## What browsers are affected?

This bug has occurred on Chrome and Safari on the iPhone 5 as well as Chrome on the iPhone 8.

## Which AMP version is affected?

Version 1510956201635

**Comment by bronsonoquinn** [comment]
I've changed the syntax to use amp-list instead, and I get the same problem:
```
<amp-list width="auto" height="29" layout="fixed-height" src="cities.json">
    <template type="amp-mustache">
        <select id="cities" on="change:AMP.navigateTo(url=event.value)" target="_blank">
            <option value="">- Choose a location -</option>
            {{#cities}}
            <option value="{{url}}">{{name}}</option>
            {{/cities}}
        </select>
    </template>
</amp-list>
```
I think either "change" or "navigateTo" are timing out. All of the URLs are https and on the same domain, by the way, but they aren't heading to AMP pages.

Hopefully that additional information helps.
Thanks!

**Comment by aghassemi** [comment]
@camelburrito could you please triage this? Thanks.

**Comment by camelburrito** [comment]
@aghassemi - This is an amp-form issue. Could be related to - https://github.com/ampproject/amphtml/issues/12327

**Comment by aghassemi** [comment]
@camelburrito unlikely, issue was reported 6 days ago.

**Comment by camelburrito** [comment]
Yeah still an amp-form issue (I tried it and was not able to repro on IOS 11 chrome and Safari)

**Comment by cvializ** [comment]
Do you know of a way to make the popup reappear after selecting initially?

**Comment by cvializ** [comment]
I notice you also have two elements with `id="locSelect"`

**Comment by aghassemi** [comment]
Testing with http://amphtml-nightly.herokuapp.com/examples/standard-actions.amp.html which has the same navigation drop-down as the sample above. It works in iOS 10.2.2 Safari/Chrome

Closing for now. Please feel free to reopen if still and issue (please include iOS version when reopening)
