### ISSUE TITLE
After the page loads, open the amp-lightbox after 3 seconds. how can i do this

### ISSUE THREAD

**Issue by mgunalp** [ampproject/amphtml#12273]
<amp-lightbox id="lightbox" layout="nodisplay">
    <p>
      <button on="tap:lightbox.close" class="lightbox-close-button">
          Close Lightbox
      </button>
    </p>
    <p>
      <amp-img src="https://lh3.googleusercontent.com/pSECrJ82R7-AqeBCOEPGPM9iG9OEIQ_QXcbubWIOdkY=w300-h200-no" width=300 height=200></amp-img>
    </p>
    <p class="lightbox-text">
      Lorem ipsum dolor sit amet, has nisl nihil convenire et, vim at aeque inermis reprehendunt. Propriae tincidunt id nec, elit nusquam te mea, ius noster platonem in. Mea an idque minim, sit sale deleniti apeirian et. Omnium legendos tractatos cu mea. Vix in stet dolorem accusamus. Iisque rationibus consetetur in cum, quo unum nulla legere ut. Simul numquam saperet no sit.
    </p>
  </amp-lightbox>

**Comment by lannka** [comment]
Do you mean to have an unsolicited pop-up? AMP does not allow that.

**Comment by aghassemi** [comment]
@mgunalp You can't by design. AMP does not allow lightbox to be opened without an explicit user interaction to prevent bad user experiences such as interstellars.
