### ISSUE TITLE
Actions AMP button not working

### ISSUE THREAD

**Issue by mgunalp** [ampproject/amphtml#12277]
**this code not working, can you help me?**

`<button on="tap:popUp.show,toggle-class('.popUpBox', 'popUpBox2')">OPEN</button>`

**error code**
url.js:345 Invalid action definition in <button on=​"tap:​popUp.show,toggle-class('.popUpBox', 'popUpBox2')​" class=​"i-amphtml-error">​…​​ : [ tap:popUp.show,toggle-class('.popUpBox', 'popUpBox2') ] ; unexpected token [(]
Xd @ url.js:345
(anonymous) @ viewer-impl.js:167
f.assert @ log.js:325
qh @ template-impl.js:226
nh @ custom-element.js:1620
lh @ custom-element.js:1360
f.trigger @ custom-element.js:1272
(anonymous) @ custom-element.js:1140
log.js:319 Uncaught Error: Invalid action definition in button: [tap:popUp.show,toggle-class('.popUpBox', 'popUpBox2')] ; unexpected token [(]​​​

**Comment by choumx** [comment]
I believe `toggle-class` is not a valid action. See the list of valid actions here: https://github.com/ampproject/amphtml/blob/master/spec/amp-actions-and-events.md

You can use `amp-bind` to toggle CSS classes on elements instead: https://github.com/ampproject/amphtml/blob/master/extensions/amp-bind/amp-bind.md
