### ISSUE TITLE
Intent to Implement: Cuelinks Extension

### ISSUE THREAD

**Issue by jimishjoban** [ampproject/amphtml#12278]
Hello Team,

We would like to allow our publishers monetize the content in their AMP Pages. The Cuelinks Extension will allow publishers to simply mention their Publisher ID and all their outbound links will be automatically monetized. More about Cuelinks here:

https://www.cuelinks.com/native-advertising-products#cuelinks

To explain further, We work with over 30,000 publishers in India (Mostly Bloggers, News websites etc). If they have any outbound links, Lets say https://www.flipkart.com/

Our JS would keep a track of all Anchor tags in the document and would automatically convert them to

https://linksredirect.com/?pub_id={publisher_id}&url=http%3A%2F%2Fwww.flipkart.com%2F

This conversion would only happen when the visitor clicks on the link or copies the link, allowing publisher to make revenue for their content. The conversion only for our Merchant partners.

The implementation syntax would look something like this:

<amp-cuelinks-extension data-pubid="">
<script type="application/json">
{  .. some config.. }
</script>
</amp-cuelinks-extension>

Regards

Team Cuelinks

**Comment by lannka** [comment]
should it be an vendor specific extension, or can be a generic outgoing URL decoration extension?

@cramforce @rudygalfi @aghassemi  what do you think?

**Comment by cramforce** [comment]
Yes, this should be implemented as a generic extension with a vendor profile.

**Comment by jimishjoban** [comment]
Would this generic extension also support basic analytics like tracking impressions etc... as that is some information, we give back to publishers ..?

**Comment by cramforce** [comment]
I think that can be achieved through extension analytics (where the extension would contribute `amp-analytics` configuration based on its configuration). CC @zhouyx 

I should clarify what a generic extension would do: Exactly the same as a non-generic extension, but it would rely on configuration to e.g. generate the URLs that are specific to a particular service. `amp-social-share` is a good example for this. `amp-ad` and `amp-analytics` are more complex examples for the same pattern.

**Comment by mrjoro** [comment]
Is this request still active?

**Comment by jimishjoban** [comment]
Hi,

yes, we are waiting for generic extension with a vendor profile to help our AMP publishers. 

If there is anything i can help with, do let me know :)

**Comment by rudygalfi** [comment]
It seems like ownership of the generic extension is unresolved. @lannka Does the AMP linker work help out with this?

**Comment by zhouyx** [comment]
Sounds to me that the new introduced link rewriter can help here.
