### ISSUE TITLE
Facebook pixel standard events parameter issues

### ISSUE THREAD

**Issue by kevinlisota** [ampproject/amphtml#12275]
Using the recent documentation for the amp-analaytics facebookpixel commited by @rudygalfi and @zhouyx, I'm seeing issues with the resulting calls to Facebook.

I am seeing two issues here. One is that AMP is needlessly sending unset optional parameters to Facebook. The other is that some parameters seem to be missing for certain event types.

Let me explain the issue by comparing the resulting POST requests sent to facebook on a normal website using the FB JS SDK and then show what happens for a similar configuration in AMP.

In addition to pageview tracking with the FB pixel, we use ViewContent to send content categories to Facebook.

On our webiste, we use the FB JS SDK and make a call like this:
```
fbq('track', 'ViewContent', {
content_category: 'My Category'
});
```
This results in a POST request to Facebook that looks like this:
`https://www.facebook.com/tr/?id=123456&ev=ViewContent&cd[content_category]=My Category`

We are trying to use the new facebook pixel capabilities in AMP to achieve the same thing. Here is the JSON config for amp-analytics

```
<amp-analytics type="facebookpixel" id="facebook-pixel">
    <script type="application/json">
    {
      "vars": {
        "pixelId": "123456"
      },
      "triggers": {
        "trackPageview": {
          "on": "visible",
          "request": "pageview"
        },
        "trackViewContent": {
          "on": "visible",
          "request": "eventViewContent",
          "vars": {
            "content_category": "My Category"
          }
        }
      }
    }
    </script>
</amp-analytics>
```

The resulting POST request to Facebook from AMP is this:

`https://www.facebook.com/tr?noscript=1&ev=ViewContent&id=451545185034187&cd[value]=&cd[currency]=&cd[content_name]=&cd[content_type]=&cd[content_ids]=`

You'll see that it is sending all sorts of empty parameters to FB. Most of the standard event parameters for Facebook pixel are optional. I think AMP probably shouldn't send the empty ones.

Also, content_category is missing for ViewContent and is not being sent in the example above, yet it is a supported parameter and clearly shown in the FB pixel documentation.

**Comment by lannka** [comment]
The 2 problems can be addressed using a custom config:

```
<amp-analytics type="facebookpixel" id="facebook-pixel">
    <script type="application/json">
    {
      "requests": {
        "customEventViewContent": "${base}&ev=ViewContent&id=${pixelId}"
      },
      "vars": {
        "pixelId": "123456"
      },
      "triggers": {
        "trackViewContent": {
          "on": "visible",
          "request": "customEventViewContent",
          "extraUrlParams": {
            "cd[content_category]": "My Category"
          }
        }
      }
    }
    </script>
</amp-analytics>
```

Let me know if it does not work.

**Comment by stephengardner** [comment]
@lannka I do not understand how you used ${base} in this context without first defining it.
Could you elaborate on this, please?  I didn't know that was possible.

**Comment by zhouyx** [comment]
@stephengardner `${base}` is defined from the `facebookpixel` config [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/vendors/facebookpixel.js#L23),
