### ISSUE TITLE
FR: Auto-scroll-to when the viewer opens

### ISSUE THREAD

**Issue by kaylareedhanson** [ampproject/amphtml#12286]
**Feature Request:**

If user sets the fragment of the AMP url to the ID of an element on the page, scroll to that element when the viewer opens.

For example, when passing the fragment of "foobar1", scroll to the element on the page with id "foobar1", similar to how browsers implement scroll-to using fragments. (eg http://foo.com/#bar scrolls to element with id "bar" on the page).

Ideally, this scheme could be more flexible than just identifiers, also maybe supporting query-selectors or text-snippet-matching somehow.

**Comment by aghassemi** [comment]
@kakadiadarpan This should work already on origin AMP urls. (example: `https://www.ampproject.org/docs/tutorials/create/basic_markup#required-mark-up` )

Where you thinking this should also work with Google.com's viewer Urls? (e.g. `https://www.google.com/amp/s/www.ampproject.org/docs/tutorials/create/basic_markup#required-mark-up`)

Curious what your use-case is, these viewer-based Urls are not normally shared barely something user would manually add "#..." to. Are you linking to these Urls?

/cc @rudygalfi

**Comment by rudygalfi** [comment]
My belief was that fragment handling worked as expected, even inside of viewers like the one used on Google Search*. Is there a reproducible case you can point us to that doesn't work?

Note that the Google Search viewer does use fragments for message-passing, so I believe the fragment gets encoded. This means you can't expect to just add a fragment to a viewer URL and have it work.

**Comment by kakadiadarpan** [comment]
@aghassemi I guess you were trying to tag @kaylareedhanson

**Comment by kaylareedhanson** [comment]
My use case involves a carousel of links to different scroll targets on a target amp page. So, for example, on my page following links would all be available, and all would be open the viewer:
amp.foo.com/ 
amp.foo.com/#bar1
amp.foo.com/#bar2
amp.foo.com/#bar3

The viewer does work correctly when opening a single URL with a fragment. When you open the viewer with href="amp.foo.com/#bar1" it does the navigation. However, it only does this the first time you open the viewer. Subsequent clicks to the same viewer with a different #fragment don't change scroll position. So this flow does not work:
click "bar1" link > close viewer > click "bar2" link

Also, when loading via viewer with a data-amp-cdn URL it does not work, due to the message passing in the fragment. This would be nice to have.

I believe this would also need to work nicely with [share tracking](https://github.com/ampproject/amphtml/issues/3135), though I am less familiar with how that gets used in practice.

**Comment by rudygalfi** [comment]
@kaylareedhanson Thanks for the additional details. Just to confirm, when you mentioned the carousel the very first time ("My use case involves a carousel of links") are you referring to a carousel in Google Search or a carousel you've implemented on your own page?

Also, do you have a live page URL (along with any relevant search queries) you could share that demonstrates the behavior?

**Comment by rudygalfi** [comment]
Closing this out as I'm not clear on what the next step here is. If there's any more details or further action needed, please re-open!
