### ISSUE TITLE
Should the amp-user-notification component do a GET or POST request to the `data-show-if-href` url

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#1228]
Got feedback from @dvoytenko on this (quote: a POST without user action is generally suspicious). 

Currently I switched the request to a POST so that we're able to transmit the json data `{ ampUserId, 
elementId }` to the server and it can determine wether to show the notification to the current visitor or not.

The alternative is to switch back to a `GET` request and transmit the data as query params.

/cc @dvoytenko @cramforce for input

**Comment by dvoytenko** [comment]
Additional thing that `GET` buys us is that we can inject query parameters via URL substitutions: https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md

I don't know if this is useful.

**Comment by erwinmombay** [comment]
@cramforce unless you have any objections, i'll switch this to a `GET` with the query params `elementId` and `ampUserId` keys.
