### ISSUE TITLE
amp-iframe allow="vr"

### ISSUE THREAD

**Issue by mikeduarte** [ampproject/amphtml#12282]
## What's the issue?

amp validator complains about allow="vr" 

> The attribute 'allow' in tag 'amp-iframe' is set to the invalid value 'vr'

## How do we reproduce the issue?

1. Add allow="vr" to an amp-iframe

## What browsers are affected?

Chrome 62+

## Which AMP version is affected?
1510956201635

**Comment by lannka** [comment]
Is allow="vr" a new web standard? can you kindly point me to the official proposal/doc?

**Comment by lannka** [comment]
@honeybadgerdontcare do you recall why do we validate the `allow` attribute for `amp-iframe`. I don't see pass down this `allow` attribute to the child iframe.

**Comment by honeybadgerdontcare** [comment]
@lannka See #11953 regarding `allow`.

**Comment by mikeduarte** [comment]
@lannka https://developers.google.com/web/updates/2017/09/webvr-origin-trial-chrome-62
and
https://support.matterport.com/hc/en-us/community/posts/115008279147-Updates-to-WebVR-New-iFrame-Attribute-allow-vr

Thanks!

**Comment by lannka** [comment]
@honeybadgerdontcare thanks for the pointer. that's the PR can unblock this
