### ISSUE TITLE
Lightbox 2.0 Demo for UX Review

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#12288]
Create an example that contains all of the following: 
- picsum.photos image assets
- inline carousel
- some with no desc, short desc, normal desc, some with ridiculously long descriptions
- different image ratios (landscape and portrait) and one that fills the viewport.
- a video
- an ad
- a tweet

https://amp-cathyxz.herokuapp.com/test/manual/amp-lightbox-viewer-demo.amp.html
https://amp-cathyxz.herokuapp.com/test/manual/amp-lightbox-carousel-demo.amp.html

Assign to @cathyxz

**Comment by aghassemi** [comment]
Closed by https://github.com/ampproject/amphtml/pull/12314 right? @cathyxz

**Comment by cathyxz** [comment]
I'm reopening this to use it to track feedback from the next UX Review if you don't mind. =)
