### ISSUE TITLE
FR: Carousel: Fine-grained slide controls

### ISSUE THREAD

**Issue by jamesshannon** [ampproject/amphtml#12289]
We should provide fine-grained controls of the carousel for not-quite-carousel use cases. The following come to mind:

* Control swipability and arrow keys
* Enable / disable the above for both forward and backward movement 

While swipable / arrow keys  and automatic bi-directionality make sense for traditional carousels there are use cases that make sense to use amp-carousel but aren't a traditional carousel. 

The immediate use case is to provide for a multi-pane form like [this](https://www.templatemonster.com/blog/tutorial-jquery-sliding-registration-form/). The link or submit button on each pane would advance to the next pane (with goToSlide()) but you don't want the user to be able to move to the next pane themselves. (However, it might make sense to allow the user to move backwards.)

**Comment by aghassemi** [comment]
@jamesshannon We are thinking of adding a different component (along the lines of `amp-pages`) for these use-cases).

That being said, @sebastianbenz is working on an example that uses `amp-bind` and other features to do what you are looking for. It is under development, but you can see the work-in-progress here: https://github.com/ampproject/amp-by-example/pull/1019/files 

I just created a new bug to capture the need for `amp-pages` and will close this issue in favour of https://github.com/ampproject/amphtml/issues/12329

**Comment by sebastianbenz** [comment]
@jamesshannon [here](https://amp-by-example-sebastian.appspot.com/samples_templates/multi_page_checkout_flow/preview/) is a first demo
