### ISSUE TITLE
video-ended trigger fires twice

### ISSUE THREAD

**Issue by lexandera** [ampproject/amphtml#12299]
In AMP Ads we are seeing analytics triggers bound to video-ended fire twice. The first time they fire before video-session, and then again after it. Transport mode (image/xhrpost) does not appear to matter.

Our trigger spec:
```
    "triggers": {
        "5a26947ff37cb": {
            "on": "video-ended",
            "request": "5a26947ff3a14",
            "vars": {
                "name": "ampVideoEnded"
            },
            "selector": "#video-35"
        }
    },
```

**Comment by rudygalfi** [comment]
cc @jasti

**Comment by cvializ** [comment]
@lexandera, which video extension is producing the analytics?

**Comment by lexandera** [comment]
@cvializ It happens on amp-video. You can see a simple example here: https://ads.celtra.com/9372da39/a4a.html?placementId=5b1a1bf0 Look for the requests containing name=ampVideoEnded.

**Comment by cvializ** [comment]
It should be fixed in production when the release containing that merge is released. Typically this takes about 2 weeks.
