### ISSUE TITLE
Unique session IDs for amp-analytics

### ISSUE THREAD

**Issue by lexandera** [ampproject/amphtml#12297]
We would like to be able to group all events tracked using amp-analytics into a session, mainly for the purpose of being able to extract unique events from the log. Right now we see for example that an element has been clicked twice, but we have no way of knowing if those two clicks were generated by two separate people, or if a single person clicked the element two times.

We tried generating unique values using something like "${timestamp}-${random}-${random}", but the variables get re-evaluated for every request, while we would need a fixed value to be reported for every event reported during the same ad impression.

**Comment by lannka** [comment]
Does ["Page View ID"](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#page-view-id) meet your needs?

Note that this random value has low entropy, so you might want to use together with clientId.

**Comment by lannka** [comment]
Closing this for now. Let me know if you want something else.

**Comment by lexandera** [comment]
What do AMP ads see as pageViewIds? Is this the same ID as the parent page view ID, or do ads get their own IDs? Same for clientId? I'm thinking we could be able to generate a value that's unique enough by combining ad id (our value), pageViewId, clientId and parent page URL.

As ads can serve on any page and not just on one domain, we need a value that's globally unique for at least a 1hr window.

**Comment by lannka** [comment]
> What do AMP ads see as pageViewIds? Is this the same ID as the parent page view ID, or do ads get their own IDs? 

Same ID as the page.

> Same for clientId?

Different Client IDs are generated for different "scope"s, where "scope" is just a string name defined by either analytics vendor (in vendors.js) or ad networks (in ads/_config.js).

See how can ads get those IDs: https://github.com/ampproject/amphtml/blob/master/ads/README.md#available-information

> As ads can serve on any page and not just on one domain, we need a value that's globally unique for at least a 1hr window.

Are you talking about ads written in AMP or ads served on AMP? I'm a bit confused because you were first talking about having the session ID in `amp-analytics`.

**Comment by lexandera** [comment]
I'm talking about ads written in AMP (A4A) and we use amp-analytics to do all the tracking.

**Comment by lannka** [comment]
I see. In that case, you should be able to use `PAGE_VIEW_ID` (a random number for each page view) and `CLIENT_ID(your_scope)` (a random string persisted in browser storage) macro in your amp-analytics pings.

**Comment by lexandera** [comment]
Thanks. Will try this.
