### ISSUE TITLE
Make amp-user-notification order display deterministic

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#1229]
Currently, the order of the notification being shown is in the order of when the component registers and since the registration and invocation of `buildCallback` on a component is not deterministic a publisher developer is not able to control the order of the notifications correctly.

**Comment by ericlindley-g** [comment]
@erwinmombay Just checking—is there any update on this, or did we just punt on it for now?

**Comment by erwinmombay** [comment]
@ericlindley-g punting for now, *unlikely* to have more than 1, but should definitely be fixed somewhere down the line imo.

**Comment by erwinmombay** [comment]
since this is unlikely to happen, closing.
