### ISSUE TITLE
Sticky ad breaking on canonical AMP page

### ISSUE THREAD

**Issue by bradfrizzell** [ampproject/amphtml#12306]
Not sure if this is affecting any non-canonical pages, have only found this so far on one publisher site. 

Sticky ad is stickying to top of page instead of bottom when scrolling, and overwriting publisher page menu 

## How do we reproduce the issue?
1. Emulate mobile 
2. Navigate to https://m.mynet.com/hacker-kurbani-olmayin-2018de-bunlara-cok-dikkat-edin-haber-3537373 (a canonical amp site)
3. Note sticky ad at bottom of viewport 
4. Scroll down page 1+ viewports.
5. Refresh page
6. Note that sticky ad now fills at top of page, instead of bottom. Bottom sticky stays empty.

**Comment by lannka** [comment]
I saw amp-sticky-ad element is assigned `top: calc(0px)` which believe is from the [fixed-layer.js](https://github.com/ampproject/amphtml/blob/master/src/service/fixed-layer.js#L581)

@jridgewell what's your experience on this?

**Comment by jridgewell** [comment]
This seems to be a bad interaction between "page already scrolled so show sticky ad" and offsetTop calculation when the element is `display: none`. I think I can account for this in FixedLayer.

**Comment by jridgewell** [comment]
Yah, looks like we just need to check for `display: none` on the element, and skip adding styles to it.

I wonder why the display isn't triggering another pass in FixedLayer, though?

**Comment by dvoytenko** [comment]
`display:none` on the element or the document? I don't think element-based fixed-layer passes are scheduled per element automatically. Somewhere update should be called by the element itself.
