### ISSUE TITLE
null is not an object (evaluating 'this.Y.removeAll')

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#12304]
Looks like dispose is somehow called more than once in `visibility-model.js`.

/cc @zhouyx

**Comment by jonkeller** [comment]
Thanks Carlos!
Do you have steps to reliably reproduce?

**Comment by cvializ** [comment]
I do not, but I do have an error log https://pantheon.corp.google.com/errors/5037054784839623411

**Comment by jonkeller** [comment]
That'll do perfectly. Thanks!

**Comment by lannka** [comment]
Looking at the code, it could only happen if `dispose` is executed twice. I'm not sure if that should happen @dvoytenko .

For now, let's add an `if` protection, and a TODO for further investigation.

**Comment by zhouyx** [comment]
There's a bug here:
https://github.com/ampproject/amphtml/blame/master/extensions/amp-analytics/0.1/visibility-model.js#L353
Basically any trigger with a time constraint could fail. `SetTimeout()` here could execute after visibility has met and `eventResolver_` set to null. We should not `refresh_` in this case.

**Comment by jonkeller** [comment]
Looking...
