### ISSUE TITLE
Latest update broke XHR Post requests

### ISSUE THREAD

**Issue by nathandh8** [ampproject/amphtml#12323]
Earlier today (European time) all our AMP forms using XHR started failing. 

Our server endpoint that handles the form input shows that no POST data is received. We have not made any changes to our codebase recently.  We believe this error is caused by a recent change on AMP's side?

We have temporarily disabled AMP on our website, so I can't post a live example.

**Comment by mikeduarte** [comment]
@nathandh8 I just test some of our forms that use XHR and they seem to be working fine.

**Comment by teksteshqip** [comment]
I confirm that AMP POST forms using XHR are not working.

Example: Try to rate here:
https://www.teksteshqip.com/dhurata-dora

I haven't made any changes.

**Comment by aghassemi** [comment]
We have rolled back the release and working on a fix. Please see https://github.com/ampproject/amphtml/issues/12327 for updates. 

Sorry for the trouble, closing this issue as dup of https://github.com/ampproject/amphtml/issues/12327
