### ISSUE TITLE
<amp-video> requires "poster" attribute if within <amp-story>

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amphtml#12320]
The `amp-video` component [requires the "poster" attribute if nested within `amp-story`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-video/validator-amp-video.protoascii#L128).

However, the `amp-video` docs [do not mention this requirement](https://www.ampproject.org/docs/reference/components/amp-video#poster).

**Comment by aghassemi** [comment]
@honeybadgerdontcare @alanorozco @bpaduch, any plans/ideas on how to document the differences between STAMP and AMP when it comes to these different requirements?

**Comment by bpaduch** [comment]
I don't believe the `amp-video` doc should include this requirement.  It's only relevant in AMP stories, and so that restriction will/should be in the amp-story spec and any associated docs - like the tutorial and guide.

**Comment by aghassemi** [comment]
sgtm. Closing the issue.

**Comment by ithinkihaveacat** [comment]
I think this should be fixed in the validator somehow, or at least that the error message should be improved. Right now, if producing an amp-story, and `poster` (or `autoplay`) is omitted, the validator complains that "The tag 'amp-video' may not appear as a descendant of tag 'amp-story'" which is not useful:

![screen shot 2017-12-19 at 3 10 03 pm](https://user-images.githubusercontent.com/51244/34163546-e9357c5e-e4ce-11e7-8f82-896a6459712c.png)

Example source:

```html
<!DOCTYPE html>

<html amp>
<head>
  <meta charset="utf-8">
  <link rel="canonical" href="https://example.com/" />
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script async custom-element="amp-story" src="https://cdn.ampproject.org/v0/amp-story-0.1.js"></script>
  <script async custom-element="amp-video" src="https://cdn.ampproject.org/v0/amp-video-0.1.js"></script>
  <title>Foo</title>
  <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
</head>
<body>
  <amp-story standalone="" id="stamp-story">
    <amp-story-page id="page0">
      <amp-story-grid-layer template="fill">
        <!-- to make valid, add the "poster" and "autoplay" attributes below -->
        <amp-video layout="fill" src="foo.mp4"></amp-video>
      </amp-story-grid-layer>
    </amp-story-page>
  </amp-story>
</body>
</html>
```
