### ISSUE TITLE
image-lightbox ignores `object-fit` of original image during transition

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#12324]
When `amp-image-lightbox` ( and the new lightbox 2.0 ) transition an image, they create a clone, the clone however does not copy over the value of `object-fit` of the original image which can cause scaling issues during transition.

see https://codepen.io/explotter/pen/QOPwEd 

/to @cathyxz Something to consider fixing at least for the new version.

**Comment by aghassemi** [comment]
cc @salihyasinseker , as discussed on Slack, for a work-around I suggest making sure the `amp-img` is `layout=responsive` or `fixed` with correct width/height, instead of using `object-fit` to scale the image.

**Comment by gctommy** [comment]
@aghassemi — Still looking for a solution for this. On some pages, we display a lot of external images with unknown dimensions, so getting the width/height would be slow and not ideal.

**Comment by aghassemi** [comment]
@gctommy The new `amp-lightbox-gallery` which is experimentally available now and is slotted for launch soon has this issue resolved.

**Comment by cathyxz** [comment]
Yup! @gctommy  The proposed way currently to work around this is to use `amp-lightbox-gallery`. The way it's handled is we use a fade in transition if the width/height of the `amp-img` is different from the natural width / height of the image. This way it no longer looks broken. The FR to have this transition nicely is tracked in https://github.com/ampproject/amphtml/issues/13039--we're still exploring a good way to achieve that. Closing this issue for now, but feel free to comment or reopen if you feel that a port of this stopgap is necessary for `<amp-image-lightbox>`.
