### ISSUE TITLE
Travis CI build fails. Test are broken on Mobile Safari 11.0.0

### ISSUE THREAD

**Issue by monetizer101** [ampproject/amphtml#12344]
Hi guys,

I'm trying to add a new ad-network but I am having an issue with the pull request. 
https://github.com/ampproject/amphtml/pull/12343

The Travis CI build fails and It looks like that test are broken on Mobile Safari 11.0.0 (iOS 11.0.0)
https://travis-ci.org/ampproject/amphtml/jobs/312858075

```
Mobile Safari 10.0.0 (iOS 10.0.0) ERROR
  TypeError: undefined is not an object (evaluating 'window.ampTestRuntimeConfig.saucelabs')
  at /tmp/test/_init_tests.js:199:4 <- /tmp/c529a80165071359f4b5319edfc92f01.browserify:75464

07 12 2017 09:21:14.185:ERROR [reporter.sauce]: ✖ Test Errored
Mobile Safari 10.0.0 (iOS 10.0.0) ERROR
  TypeError: undefined is not an object (evaluating 'window.ampTestRuntimeConfig.saucelabs')
  at /tmp/test/_init_tests.js:199:4 <- /tmp/c529a80165071359f4b5319edfc92f01.browserify:75464
```

**Comment by choumx** [comment]
Weird error. Looks like Travis build on that PR is fine. Did you restart it?

**Comment by argosk** [comment]
Now, all checks have passed. Thanks, guys.
