### ISSUE TITLE
amp-bind: Multiple args in closure functions e.g. reduce()

### ISSUE THREAD

**Issue by tbaik** [ampproject/amphtml#12349]
## What's the issue?

The `Array.reduce` function in an amp-bind expression currently only allows one parameter (the callback function) to be passed in. There should be support for the second parameter (initial value) as well.

One can prepend an initial value to an array before using the reduce function but having the second parameter is more ideal.

## How do we reproduce the issue?
```[1, 2, 3].reduce((x, y) => x + y)``` is OK.
```[1, 2, 3].reduce((x, y) => x + y, 0)``` is not accepted.

## What browsers are affected?

All browsers

## Which AMP version is affected?

Latest.

CC: @jmarkoff & @sebastianbenz

**Comment by choumx** [comment]
Agree that would be better. For prioritization: are there cases where a workaround doesn't exist?

**Comment by tbaik** [comment]
@choumx I have been able to get around this with the mentioned workaround for all of my cases so far! I imagine it works for all other cases as well.

**Comment by command3r** [comment]
Hi there, I believe this along with operands limit on expressions, make it impossible or very hard to `reduce` into another array which is useful for state management of state/arrays.

**Comment by choumx** [comment]
@command3r Do you have an example you can share?

**Comment by rizalpascual** [comment]
@choumx, Our use case needs this one to be fixed:
[1, 2, 3].reduce((x, y) => x + y, 0) is not accepted.

We use that approach to sum/total the items of our array.
e.g.

<span [text]="' $' + shoppingCart.items.map((item, index) => item.price).reduce((x, y) => x + y, 0)"></span>

Is there a workaround to avoid the validation issue. Our use case needs the array to be empty initally.

Thanks.
