### ISSUE TITLE
Maximum number of bindings reached (2000). Additional elements with bindings will be ignored.

### ISSUE THREAD

**Issue by SoleSS** [ampproject/amphtml#12346]
https://morozko.tv/site/group

i have 8 (4 visible\4 hidden) auto-suggest dropdowns (made according to your example), each using the same src. according to https://www.ampproject.org/ru/docs/reference/components/amp-list 
"AMP batches XMLHttpRequests (XHRs) to JSON endpoints, that is, you can use a single JSON data request as a data source for multiple consumers (e.g., multiple amp-list elements) on an AMP page. For example, if your amp-list makes an XHR to an endpoint, while the XHR is in flight, all subsequent XHRs to the same endpoint won't trigger and will instead return the results from the first XHR."

there has to be only 1 request to backend from all dropdowns (as i understand), but in practice each dropdown makes a request. Moreover i have 2000+ items in json, so after filling the first field all others stop to work with message: "Maximum number of bindings reached (2000). Additional elements with bindings will be ignored."

i tried to place all names in setState and call new object from amp-list, but it appered that amp-list can't use setState data.
```

                            <div class="hide form-group field-orderform-childname4" [class]="(fourChildren == true ? 'form-group field-orderform-childname4' : 'hide')">
                                <label class="control-label">Имя четвертого ребенка</label>

  <div class="dropdown-wrap">
    <div class="product-search select-wrap full-width">
      <div class="search-container1">
        <input name="OrderForm[childname4]" type="hidden" [value]="childname4Id">
        <input id="mobile-query4" name="query" autocomplete="off" placeholder="Выберите имя из списка" type="text" class="search-box"
            on="input-debounced:AMP.setState({ query: event.value, inputText4: event.value, autosuggest: event.value, comboExpanded: true}), mobile-autosuggest4-list.show"
          [value]="inputText4 || ''" value="">

<!--        <button on="tap:mobile-autosuggest4-list.toggleVisibility, AMP.setState({ comboExpanded: !comboExpanded })" class="search-submit" type="button">
          <i [class]="comboExpanded ? 'arrow-up' : 'arrow-down'" class="arrow-down"></i>
        </button>-->

      </div>
        <amp-list class="autosuggest-box" single-item items="." layout="fixed-height" height="350" src="<?= str_replace('http://', '//', Yii::$app->urlManager->hostInfo).Url::toRoute(['/json/names', 'male' => '-1']) ?>" id="mobile-autosuggest4-list" hidden>
          <template type="amp-mustache">
             <amp-selector class="dropdown-selector" keyboard-select-mode="focus" layout="container" on="select:AMP.setState({
                                            query: '',
                                            inputText4: event.targetOption.split(',')[1],
                                            childname4Id: event.targetOption.split(',')[0],
                                            comboExpanded: false,
                                            trackUrl4: 'https://dmdata.info-tech.pro/wizard/audio-iframe?id='+event.targetOption.split(',')[0]
                                        }),
                                        mobile-autosuggest4-list.hide">
               {{#items}}
            <div class="select-option no-outline lvl2" [class]="'select-option no-outline lvl2 ' + (query == null || '{{lowerTitle}}'.indexOf(query.toLowerCase()) >= 0 ? '' : 'hidden')"
              role="option" tabindex="0" on="tap:mobile-autosuggest4-list.hide" option="{{id}},{{title}}">{{title}}</div>
                {{/items}}
               </amp-selector>
          </template>
        </amp-list>

    </div>
  </div>

```

**Comment by choumx** [comment]
Thanks for filing this issue. The binding limit is meant to keep AMP pages that using `amp-bind` fast and responsive.

Is it possible to change your JSON API to return fewer items? I think hundreds to thousands of autocomplete suggestions is probably too many. 

Many large sites only display up to 10 autocomplete suggestions: https://ux.stackexchange.com/questions/56126/how-many-search-suggestion-should-i-display

**Comment by SoleSS** [comment]
well, i think no... user have to choose available name from list (named greeting service) so the list would be long enough. the only way that looks for me is to make a suggestion list on server side, but how to pass params of input?

**Comment by SoleSS** [comment]
moreover: system works even with that limits, but only in first dropdodwn list, the second and overs becomes useless after filling the first one.

**Comment by SoleSS** [comment]
as far as i can see: core problem is not in the list length, but it NOT REUSING of previous XHR data.

i have shorten the list (only female names) - i was able to fill 2 of for dropdowns, third - showed error (but they all use the same endpoint)

**Comment by SoleSS** [comment]
and anyway - there has to be a way to clear bindings after filling the field (in case there will be 1 male and 1 female fields 1100+1100 different names)

**Comment by choumx** [comment]
> the only way that looks for me is to make a suggestion list on server side, but how to pass params of input?

You can pass the params by adding a `[src]` binding to the `amp-list` element containing the autocomplete suggestions. This ABE sample shows how to do it: https://ampbyexample.com/advanced/autosuggest/

> there has to be a way to clear bindings after filling the field (in case there will be 1 male and 1 female fields 1100+1100 different names)

The bindings will be cleaned up once the amp-list children are removed on auto-suggest updates. The example above has this behavior.

**Comment by SoleSS** [comment]
I have used that example, strctly speaking it was copied from there... and it's working...
but only for 1 or 2 fields... on 3rd - binding exception appears.

https://morozko.tv/site/group - my project
just paste in 1st dropdown block: Александр (remove few last synbols) and submit autosuggested row
do the same for 2nd and 3rd blocks - on the 3rd autosuggest will stop working
(all 3 blocks use the same endpoint, so there is no need for dynamic src)

**Comment by SoleSS** [comment]
> You can pass the params by adding a [src] binding to the amp-list element containing the autocomplete suggestions. This ABE sample shows how to do it: https://ampbyexample.com/advanced/autosuggest/

Thanks! that solved the issue...

**Comment by choumx** [comment]
Great, glad it worked for you. 👍
