### ISSUE TITLE
amp-instagram data-caption not displaying correctly

### ISSUE THREAD

**Issue by luiscruz09** [ampproject/amphtml#12356]
## What's the issue?

Started using amp-instagram component from amp library: https://www.ampproject.org/docs/reference/components/amp-instagram

There is an issue rendering the post data caption, It gets cut and does not display content correctly. See this example:  https://screencast.com/t/UsgGovrSTs

*Sometimes issue gets solved when there is a screen resize: https://screencast.com/t/h8PIsZuFcU8W

## How do we reproduce the issue?

Use the following codepen example to reproduce the issue: https://codepen.io/lcruz09/pen/yPdMqg

Steps:
1- Enter the previous codepen link
2- Change codepen view to a mobile layout
3- Notice how post data caption is not displaying or is cut 

Notice that amp-instagram tag has the data-captioned property which causes the issue being reported.

## What browsers are affected?
All

## Which AMP version is affected?

https://cdn.ampproject.org/v0.js
https://cdn.ampproject.org/v0/amp-instagram-0.1.js

**Comment by teknotica** [comment]
Hi 👋 

We are experiencing content being cut off in our `amp-instagram` as well. We noticed that the _caption_ is showing ok, however the next piece of content (comments line) is the one cut off.

When trying the following code:

```
<amp-instagram data-shortcode="CODE_HERE"
  data-captioned
  width="1"
  height="1"
  layout="responsive">
</amp-instagram>
```
We got this output in our pages. We have decided to hide the captions for now.

Is there a way to work around this? Thanks in advance!

<img width="594" alt="cut-off" src="https://user-images.githubusercontent.com/354494/35399054-4cedd726-01eb-11e8-94ca-4def57130b9b.png">

**Comment by aghassemi** [comment]
@teknotica A fix was submitted today and will be in production in couple of weeks. Meanwhile as a work around you can try to guess a better width/height aspect ratio for the embed so the initial size is correct. For this particular photo, `width="1" height="1.45"` seems to work.

**Comment by teknotica** [comment]
@aghassemi thanks for the heads up. We will wait for the fix in the next release then. Thanks again 🙌
