### ISSUE TITLE
Polyfill position:sticky for browsers that don't support it

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#12368]
/cc @aghassemi

**Comment by nainar** [comment]
Just curious: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/position) states that position:sticky is supported on Chromium (Chrome, Opera namely), Safari, Edge, Firefox. 

Is this to ensure compatibility with IE? And potentially browsers based on old versions of the Chromium codebase?

**Comment by aghassemi** [comment]
Agree with @nainar, browser's we officially support have position:sticky implemented. IE is best effort anyway.

@ericlindley-g Did this request come from a particular partner?

**Comment by ericlindley-g** [comment]
@aghassemi this came up as a result of talking w/ developers in e-comm, but I think they found a workaround, so this is a more general request for the ecosystem (and low priority)

**Comment by aghassemi** [comment]
support is good enough at this point: https://caniuse.com/#feat=css-sticky
