### ISSUE TITLE
`amp-facebook` video looks strange on mobile and browser's mobile mode

### ISSUE THREAD

**Issue by bin16** [ampproject/amphtml#12370]
## What's the issue?

On (some) mobile phone, (and chrome browser's reponsive mode) `amp-facebook embed as video` has a purple bar above the video player, so that  bottom part of the video is missed(include the video control utils).

### Chrome 62.0 / Android 8.0.0 / OnePlus A3000
![image](https://user-images.githubusercontent.com/11701531/33755979-45fa382a-dc2e-11e7-8c8c-65a9d597cbaf.png)

### Firefox Nighty 59.0a1 / Android 8.0.0 / OnePlus A3000
![image](https://user-images.githubusercontent.com/11701531/33755995-5980ce72-dc2e-11e7-9395-3699ecbfab0b.png)

### Edge 1.0.0.1270 / Android 8.0.0 / OnePlus A3000
![image](https://user-images.githubusercontent.com/11701531/33755986-4d23ff28-dc2e-11e7-9ce3-a2d2b9cd6718.png)

## How do we reproduce the issue?

1. Open [amp-facebook from ampproject.org](https://www.ampproject.org/docs/reference/components/amp-facebook) on mobile phones. Chrome desktop's responsive mode is ok. Firefox Quantum 58.0b5 (64-bit) can't reproduce.

2. Just see that facebook video player, there should be a purple bar above the video. As a result, part of the video is invisible.

## What browsers are affected?

- Chrome 62.0 / Android 8.0.0 / OnePlus A3000
- Firefox Nighty 59.0a1 / Android 8.0.0 / OnePlus A3000
- Edge 1.0.0.1270 / Android 8.0.0 / OnePlus A3000
- Chrome  61.0.3163.79 (Official Build) beta (64-bit) / Ubuntu 17.04

## Which AMP version is affected?

<https://cdn.ampproject.org/v0/amp-facebook-0.1.js>

**Comment by aghassemi** [comment]
Yikes, thanks for reporting. Likely FB's SKD changed and we need to adopt or it's a FB bug.

**Comment by bin16** [comment]
https://developers.facebook.com/bugs/353698218434489/

**Comment by aghassemi** [comment]
Thanks @bin16

**Comment by aghassemi** [comment]
FB fixed the bug. Closing
