### ISSUE TITLE
Proposing to re-add the deleted file validator_gen_md.py

### ISSUE THREAD

**Issue by kienstra** [ampproject/amphtml#12371]
## What's the issue?

It would be really helpful to re-add the deleted file [validator/validator_gen_md.py](https://github.com/ampproject/amphtml/pull/10830/commits/9c0220f1ca5c6ee8cf3e0b63afe245cd6fc38a5e#diff-b607fc1ff2a2e4f9b5f008d2055446daL1). It was deleted in [this commit](https://github.com/ampproject/amphtml/pull/10830/commits/9c0220f1ca5c6ee8cf3e0b63afe245cd6fc38a5e), with the message 
>"We aren't actively developing this and it's crufty. Let's remove it for now and if we choose to revive it, the code will still be there.

It's understandable to delete unused code.

But this file can help the [AMP WordPress plugin](https://github.com/Automattic/) in generating a file of AMP's allowed tags and attributes. That repo's [Issue #804](https://github.com/Automattic/amp-wp/issues/804) depends on this [deleted file](https://github.com/ampproject/amphtml/pull/10830/commits/9c0220f1ca5c6ee8cf3e0b63afe245cd6fc38a5e#diff-b607fc1ff2a2e4f9b5f008d2055446daL1). 

That plugin uses this repo in order to generate the [file that validates](https://github.com/Automattic/amp-wp/pull/823/files#diff-a761ebd1d4f764d95add0829d1378635) AMP tags and attributes. But we now need to manually make a commit to revert the [deletion](https://github.com/ampproject/amphtml/pull/10830/commits/9c0220f1ca5c6ee8cf3e0b63afe245cd6fc38a5e) of `validator_gen_md.py` in order to generate that file.

## How do we reproduce the issue?

1. In a WordPress environment, clone the plugin [amp-wp](https://github.com/Automattic/amp-wp/pull/823) to `plugins/`.
2. Follow the steps on this [amp-wp pull request](https://github.com/Automattic/amp-wp/pull/823), entitled "Steps To Manually Run Script." These create that plugin's PHP file that validates AMP tags and attributes.
3. Observe that "Step 7" involves making a commit to this [amphtml](https://github.com/ampproject/amphtml) repo, to revert the [deletion](https://github.com/ampproject/amphtml/pull/10830/commits/9c0220f1ca5c6ee8cf3e0b63afe245cd6fc38a5e) of `validator_gen_md.py`.
4. On making that commit, and following all of the steps, the build succeeds.

This is proposing to only re-add [validator_gen_md.py](https://github.com/ampproject/amphtml/pull/10830/commits/9c0220f1ca5c6ee8cf3e0b63afe245cd6fc38a5e#diff-b607fc1ff2a2e4f9b5f008d2055446daL1), not any other file in the commit that deleted it.

## What browsers are affected?

This is browser-agnostic, as it only involves the creation of a PHP file, using Python scripts.

## Which AMP version is affected?

This has only been an issue since this [August 7th commit](https://github.com/ampproject/amphtml/pull/10830/commits/9c0220f1ca5c6ee8cf3e0b63afe245cd6fc38a5e#diff-b607fc1ff2a2e4f9b5f008d2055446daL1) removed `validator_gen_md.py`. At that time, the [Spec Version was 456](https://github.com/ampproject/amphtml/blob/52e45e4a9d407cb038fec025023a854c085fbea2/validator/CHANGELOG.md).

**Comment by Gregable** [comment]
Hmm, I don't want to break wordpress, but reading a markdown file to parse the validator rules is probably not the right solution to wordpress. Reading the machine-readable protoascii file should be how this is approached. Would it be possible to accomplish this in another way?

**Comment by kienstra** [comment]
**Closing**
*Thanks For Investigating*

Hi @Gregable,
Thanks for looking at this, and sorry for the delay in replying. [Weston Ruter](https://github.com/westonruter) found that the `validator_gen_md` file [is no longer needed](https://github.com/Automattic/amp-wp/pull/892/commits/17f63acee38204ddf1f5057d2fd0fa1f1ca66a61#diff-942ce31bf727845b901140281c0278a1L339), so I'm closing this issue. 

Thank you!
