### ISSUE TITLE
[Master Feature] Implement support for publisher served ads in AMP Stories

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#12381]
This feature will enable a publisher to hardcode an ad story page inside an AMP Story until more ad servers support delivery of ads for AMP Stories. 

- System Ad Overlay
- Support Ad Story Page + Web Landing Page Paradigm
- Support Ad Story Page + AMP Story (also useful for sponsored content type of advertising)
- Implement Call to Action Support for Ad Story Page (including out-link support)
- Validator support for above
- Implement placement algorithm 
- Never render the ad if the ad hasn't fully loaded
- Implement configuration options for ad placement
- Documentation for tagging
- Add support for internal health and ad served and placement volume
- Ad internal analytics to track health and usage

**Comment by lannka** [comment]
We propose to 
- introduce a new extension `<amp-story-auto-ads>` to schedule ad and manage the lifecycle of an ad.
- reuse `<amp-ad type="custom">` to inline ad templates and let publisher to serve their own ads.
