### ISSUE TITLE
Issue with 3p iframe remote file

### ISSUE THREAD

**Issue by omeryounus** [ampproject/amphtml#12403]
## What's the issue?
When adding the remote.html file in the amp page. It gives the following error. 
log.js:325 Error: Non-whitelisted 3p type for custom iframe: ima-video​​​
    at na.g.assert (log.js:319)
    at window.draw3p (integration.js:816)
    at remote.html?1512677960104:30

For the <amp-video> tag, it is working fine.

Example url for remote.html file:
https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/amp/remote.html

## How do we reproduce the issue?
1. Step 1 to reproduce
Add remote.html file in the header 

2. Step 2 to reproduce
Add the <amp-ima-video>

## What browsers are affected?
All browsers 

## Which AMP version is affected?
0.1
Is this a new issue? Or was it always broken? Paste your AMP version. You can find it in the browser dev tools.
It is AMP comparability issue with 3p iframe loading

**Comment by lannka** [comment]
the `remote.html` is configured to only accept amp-ad type=['doubleclick', 'taboola'].
type=ima-video​​​ is not accepted.

see this line: https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/amp/remote.html#L155
