### ISSUE TITLE
AMP pages no longer valid due to head tag evaluation

### ISSUE THREAD

**Issue by p2er** [ampproject/amphtml#12405]
## What's the issue?

The amp head tag validation is very strict and results in invalid AMP pages for formerly valid AMP pages. Limits the use of certain tags. Also missing documentation about the allowed tags. Only states that a certain tag is not allowed in that configuration without reference to fixing the problem. Providing a generic link to https://www.ampproject.org/docs/reference/spec#html-tags is not helpful. 

## How do we reproduce the issue?

1. open https://ampbyexample.com/components/amp-fx-flying-carpet/#development=1
2. see validation error: The attribute 'crossorigin' may not appear in tag 'link rel='. 

## What browsers are affected?

All browsers.

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1512677960104 https://ampbyexample.com/components/amp-fx-flying-carpet/#development=1

**Comment by choumx** [comment]
Validation appears successful for me on that page:

> Powered by AMP ⚡ HTML – Version 1512677960104 
... 
AMP validation successful.

I don't see `link[crossorigin]` on that page either and there haven't been any [recent changes to that ABE page](https://github.com/ampproject/amp-by-example/blob/master/src/20_Components/amp-fx-flying-carpet.html). I also can't find when `crossorigin` was ever allowed for the `link rel=` spec in validator-main.protoascii.

Are you seeing this error on any other pages?

**Comment by p2er** [comment]
I can confirm that I no longer see the issue on specified page. I still hat the Tab open in Firefox. The Tag causing the issue was `<link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin="">`
The tag was underneath `<script async="" custom-element="amp-selector" src="https://cdn.ampproject.org/v0/amp-selector-0.1.js"></script>` and above `<script async="" custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>`

I guess you could consider this issue as resolved. Never the less it would still be nice to have a informative link as part of this error message to show which tags are allowed and wich forbidden. So that you would not have to dig into the repo and check the validator configuration, but instead would be able to check a definitive guideline to see if you can find an alternative for the tag one would like to use.
