### ISSUE TITLE
Intent to Implement: amp-embeddable

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#1241]
# Overview
AMP pages lend themselves to being framed and embedded in full desktop browser pages however there are couple of major limitations.   

1. Resize - There is no way for the framing page to know how long to make the framed article leading to ugly scroll bars or truncated content.
1. Security - controlling framing with http `x-frame-options` is binary, yes or no.  More granular control is needed.

## amp-embedable

Intent to implement an `amp-embeddable` extension.  It will have two main elements.  

1. If it detects that the page has been framed it will send a message to the parent requesting resize every time the page length changes following the same message format as [amp-iframe](https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md).  A companion stub library will be provided for embedding pages to use if they don't already handle amp-iframe messages.
1. An optional json data block defining allowed embedding domains. If the page is framed and the `location.referer` domain is not a permitted embedder the page will be replaced by a placeholder image.  This is not meant to be a highly secure solution as the frame could be sandboxed with scripting disabled, it does however give some degree of control.

If the extension does not detect framing it will no-op.

Full specification to follow.  

### Open questions, comments requested.

1. How to manage the allowed framers list - whitelist? blacklist? both?  wildcards?  regex?
1. Exact behaviors on detection of disallowed frame. 
1. Should a `<noscript>` element be provided to disable readability if scripting is blocked?

**Comment by cramforce** [comment]
@jpettitt Thanks for the intent to implement! A few comments:

We already have pretty sophisticated "viewer integration" support ([AMP code](https://github.com/ampproject/amphtml/blob/master/src/service/viewer-impl.js), [example viewer](https://github.com/ampproject/amphtml/blob/master/examples/viewer.html)) that handles the parent frame communication you are looking for. This needs to be documented better, but it will do many things that you'd like to do. This is not currently using the same protocol as we use for child-iframe resizing. Maybe it should. It has some very sophisticated and partly unfinished logic inside of it. Mostly to

- make scrolling in Safari not suck
- allow the URL bar in Chrome to scroll away

Both of these points are a topic for ongoing concern for us.

On the security aspects of your issue: Would you mind elaborating a bit on the use case you have in mind before we go into implementation? From a philosophical POV "AMP Viewers" (we call viewers the platforms that integrate AMP content) are like web browsers and the content should not be able to control which web browser shows it. On the other hand there is a valid concern of iframing by malicious parties. 

One more thing to consider in the proposal is non-web integrations. Native web views might neither provide a referrer (or can chose them) nor even have a parent frame, even though the effect is the same. A general solution would need to handle this as well.

I think, rather than having this mechanism in AMP "userland", it would be better to establish clear guidelines as to what an AMP viewer must do and must not do (Such as XX% of the page is used for content, clear attribution of authorship, etc. and then have this enforced by AMP proxies for all content).

**Comment by jpettitt** [comment]
The viewer stuff is rather opaque.   I'm sure I missed some things, how does the AMP page tell the parent how long it wants to be?  I grepped for postMessage and can't find where it messages it's requested size.   Why not use the amp-iframe interface - that way an AMP page could embed another AMP page which would allow "endless" page type features where additional stories are added seamlessly as the user scrolls to the bottom of the one they are reading.  

On the security side I think the assumption that AMP viewers will be friendly, conform to guidelines, is not realistic.  I agree webview windows in apps are an issue but they fall into the same category and browsers with malicious extensions, you can't control the environment and noting you can do on the page or server really defends against them because they can appear any way they choose.  similarly a malicious proxy could strip or manipulate amp pages, these issues are not fixable in code, they require lawyers :-) 

However there is a clear business case for embedding articles on non-mobile sites. It offers a controlled syndication with all the elements publishers care about (branding, data/analytics, ads) traveling with the content and with enforced content integrity.  The http side x-frame-options is a blunt instrument that offers little control.  Control would be possible to implement at the server/proxy level with referer checking but that precludes using basic CDN's and requires smart proxies, something that won't happen as AMP rolls down to self hosted wordpress and the like.  Putting it into an amp extension allows publishers a degree of flexibility as to where their content can, and can't be embedded while retaining the ability to serve fast from a dumb CDN.

Does that make sense?

**Comment by dvoytenko** [comment]
I'll provide more context on sizing/scrolling.

We currently recommend the following layout/parameters for embedding AMP documents:

1. The Viewer provides the layout/size for the AMP iframe to cover the whole viewport. The most typical layout is `position=absolute` and `top/left/bottom/right = 0`. This is the recommendation and you can do something different, as long as you understand the issues described below. This does mean that the parent page has to disable its own scrolling while the AMP document is showing. The Viewer has an option to overlay the AMP iframe with its own header and other overlays are possible as well.
2. Scrolling is configured simply by using `scrolling=yes` on the iframe.

Here's why we recommend this layout/parameters:

1. The first reason for the full viewport layout (as opposed to sizing the iframe by the document's height) is to enable the fullscreen mode. This is not the same as the browser full screen mode, but simply a mode where the viewer hides its header and the AMP document has the full web page to work with. This is how AMP lightboxes work. We may still switch to browser fullscreen mode, but currently, with the incomplete browser support, popups and custom animations/gestures, we erred on the side of just working this around with the full-viewport layout. Viewers, however, can use `requestFullscreen` API if they choose to do so.
2. The second reason for the full viewport layout is preservation of `position=fixed` in AMP documents. If we were to size the AMP iframe by the document's height, we'd essentially kill it. We, however, wanted to preserve it and, more or less, make it work the same way as in standalone documents.
3. We rely on iframe scrolling (`scrolling=yes`). That, however, doesn't work on mobile Safari (https://bugs.webkit.org/show_bug.cgi?id=149264) and it's drastically exacerbated by the https://bugs.webkit.org/show_bug.cgi?id=106133. Thus we employ some significant workarounds that are thoroughly documented in the code (viewport.js).

Our goal, as part of AMP, is not only make an efficient runtime for running web content pages, but also ensure that they are embeddable seamlessly in as many environments as possible. In other words an embedded AMP document should function very much like a standalone AMP document. The recommendations above are the best tradeoffs we found in the current generation of browsers. We, however, are actively working with browser vendors to improve some of these issues.

We experimented quite a bit with sizing the AMP iframe by the document's height, indeed the code is still in there and can be tried. It's not documented given that we do not recommend it, but I can send over the instructions if desired. Perhaps you could describe us your use case in some detail?

**Comment by jpettitt** [comment]
I'd love to the the instructions.

Right now I can see two uses cases although I'm sure there are others.

1) People are going to figure out that AMP documents are embeddable pretty quickly and you'll start seeing them framed on desktop sites.  This opens up a whole raft of issues around licensing and publisher control of where their content ends up that it would be nice to address.  I could see using (abusing) the paywall support to manage some of those issues but I'd have to think it through some more.

2) The case I'm interested in is endless pages.  A way of stacking multiple amp pages in some sort of viewer framework to allow an endless scroll (think Quartz).  If I get the viewer resize info I may be able to achieve what I want with that.

**Comment by dvoytenko** [comment]
/cc @rudygalfi on embedding, consent, etc. Paywall, however, will NOT be circumventable via iframes.

The endless pages use case we thought through. Unfortunately, given the state of iframes and scrolling/resizing, it'd be very difficult to achieve correctly. Instead we were considering an option where one could inject the "next" article straight into the AMP document. This would only be allowed for two documents for the same publisher. However, I assume there could be an option where a viewer translates the next document from the bottom that would feel very much like scrolling.

**Comment by jpettitt** [comment]
Closing this, will revisit later when the viewer is documented.
