### ISSUE TITLE
Bug [validator]: Mandatory style (js enabled) opacity 0 

### ISSUE THREAD

**Issue by RaedsLab** [ampproject/amphtml#1242]
It looks like when I try to properly format my HTML code like this : 
```html 
    <style>
        body {
            opacity: 0
        }
     </style>
    <noscript>
        <style>
            body {
                opacity: 1
            }
        </style>
    </noscript>
```

The validator outputs an error even though it is 100% equivalent to :

```html
<style>body {opacity: 0}</style><noscript><style>body {opacity: 1}</style></noscript>
```
 Which passes.

**Comment by cramforce** [comment]
This is a somewhat known issue. @Gregable Is it on the current roadmap to switch to a CSS parser to validate the boilerplate?

**Comment by RaedsLab** [comment]
@cramforce my bad if this is a known issue, I tried to look for it in the Issues but without any luck.

**Comment by cramforce** [comment]
@RaedsLab More like: I knew this was an issue :) Thanks for the report. We'll use it to track progress on this, although I can't promise immediate fixes. Probably better to not format for a while.

**Comment by Gregable** [comment]
This variant is deprecated, so we won't be doing anything to support this version beyond the current state.
