### ISSUE TITLE
amp-video-analytics: VIDEO_STATE doesn't work within mparticle eventAttributes_Values

### ISSUE THREAD

**Issue by garmoshka-mo** [ampproject/amphtml#12427]
When attempting to use any `VIDEO_STATE` with two arguments (any values) - exception appears:
```
log.js:319 Uncaught Error: Could not find an element with id="undefined" for VIDEO_STATE: null​​​
    at pa.f.assert (log.js:319)
    at pa.f.assertElement (log.js:344)
    at impression.js:150
    at url-replacements-impl.js:375
    at String.replace (<anonymous>)
    at hf (url-replacements-impl.js:361)
    at gf.f.expandUrlAsync (url-replacements-impl.js:188)
    at gf.f.expandAsync (url-replacements-impl.js:166)
    at requests.js:99
    at <anonymous>
```

Tested on minimal AMP setup (taken from AMP examples).
Attaching example: [example.html.zip](https://github.com/ampproject/amphtml/files/1552612/example.html.zip)

**Comment by garmoshka-mo** [comment]
In example this source:
```
                "eventAttributes_Keys":[
                    "A",
                    "B"],
                "eventAttributes_Values":[
                    "VIDEO_STATE(video1,autoplay)",
                    "autoplay"
                ]
```

Results in: (See parameters passed to mparticle server in Developer tools, "Network" tab)
```
attrs_k:A,B
attrs_v:(video1,autoplay),autoplay
```

**Comment by aghassemi** [comment]
@lannka does parameter variable substitution work inside `vars` values for `amp-analytics`? `VIDEO_STATE` is just a variabl substitution function. looks like params are not being passed to it in this case from amp-analytics.

/cc @cvializ

**Comment by lannka** [comment]
this is a bug. I'm coming up with a fix shortly.
