### ISSUE TITLE
Throw dev error if CORS headers don't support AMP Cache 

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#12433]
To help publishers catch AMP CORS errors in development.

`b/125944172`

**Comment by choumx** [comment]
/to @alabiaga Aaron, would you mind working on this?

**Comment by alabiaga** [comment]
I spoke to @gregable about this offline and will capture some of the ideas generated in a doc. Thanks.

**Comment by alabiaga** [comment]
cc\ @ithinkihaveacat 

Michael, I spoke to @sebaperez  who has written the amp-cache-url tool and he mentioned you've written something for this. Do you mind sharing.

**Comment by alabiaga** [comment]
Michael has written https://github.com/ithinkihaveacat/ampbench/tree/amp-toolbox-linter which simulates amp-cache CORS requests. It would be nice to have something built in locally in our gulp server or even a chrome extension/service work which will simulate similar requests, I'll look into this. But for the short term solution, I think a combination of adding his tool to the [amp-toolbox](https://github.com/ampproject/amp-toolbox) and some text in our existing validator process to note to publishers that valid amp pages also need to go through CORS testing would be a good step to providing pubs with more visibility about this process.

**Comment by ithinkihaveacat** [comment]
You probably mean to mention @sebastianbenz ;-).

**Comment by alabiaga** [comment]
@ithinkihaveacat fixed. thanks

**Comment by alabiaga** [comment]
cc\ @gregabl

**Comment by Gregable** [comment]
That seems like a good choice for the effort / impact.

**Comment by alabiaga** [comment]
closing issue. Went with the additional msg related to publishing amp docs in validator message.

**Comment by choumx** [comment]
FYI this is also less relevant now that we're moving most of AMP CORS (#22136).
