### ISSUE TITLE
ampprojectbot: Don't automatically add PRs to milestones

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#12434]
Currently, PRs seem to be auto-added to the "Pending Triage" milestone. Then they get pinged regularly for not being triaged. We should constrain that behavior to `type:issue`.

Not sure if this is the right project/component. 

/to @adelinamart

**Comment by adelinamart** [comment]
ah, I see. It seems that as far as the API is concerned, every pull request is an issue, but not every issue is a pull request. So the only way to differentiate is to check if the object will include a 'pull_request' key. I'll try to fix this these days.

**Comment by choumx** [comment]
Great thanks!
