### ISSUE TITLE
AMP html apply for any static website?

### ISSUE THREAD

**Issue by pratikjoshi5** [ampproject/amphtml#1244]
Hello,

AMP html apply for any static website?   or its apply only for article publishing website?

**Comment by cramforce** [comment]
@pratikjoshi5 Definitely any static website. Having said that we are aware that there are some things missing right now to make AMP suitable for certain use cases (e.g. we really need a good menu component). Mid- to long-term AMP will support more use cases.

**Comment by pratikjoshi5** [comment]
Where to write AMPhtml code.  Is within same code at write for desktop site?

**Comment by cramforce** [comment]
Answered in your separate issue.

**Comment by luangch** [comment]
Issue mentioned above. [Where to write AMPhtml code. Is within same code at write for desktop site? #1247](https://github.com/ampproject/amphtml/issues/1247)
