### ISSUE TITLE
amp-story: Improve viewer -> story transition

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#12454]
There are two loading indicators displayed during page load -- one from SRP and one from amp-story. There are several strategies to improve the UX for different surfaces. 

/cc @flaviori

**Comment by choumx** [comment]
@hongwei1990 has the latest mocks. High-level strategy is to (A) require availability of background/poster image before display and (B) allow page navigation while video is loading.

Current proposal: 
1. Remove amp-story's "3-dot" loading page
2. Delay "document-ready" viewer signal until the first page's background/poster image is ready
3. If first page has a video, show a small spinner on bottom right of page while it's loading
4. Swap small spinner for an equalizer animation once video finishes loading

**Comment by newmuis** [comment]
#12604 handles the first item from the list above (removing the "3-dot" loading page)

**Comment by choumx** [comment]
`go/amp-story-performance` has a mock and more detailed suggestions FYI.

**Comment by newmuis** [comment]
The second item is tracked in #12769, although we fake this in #12842 by simply showing a blank document until the poster is ready.

The third item is tracked in #12775.

The fourth item is tracked in #11857.

Closing this issue, to defer to the other work already in progress.
