### ISSUE TITLE
Support image-map in <amp-img>

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#12455]
Helpful to build AMP native seat pickers instead of relying on amp-iframe

**Comment by aghassemi** [comment]
Seat picker use-case is now handled by `amp-pan-zoom` and `svg` + `amp-list`. 

Closing this FR for now, if other use-cases come up that may require image map, please feel free to reopen.

**Comment by Joelsz** [comment]
@aghassemi Here's a use case for this.

Basically we have a dynamic system for banners where it's an image and usually links to a set URL, however, if there are multiple links in one banner (buttons etc.) we create the links with area maps on top of the image.

In AMP we are not able to do this.

Think it's a good enough use case to add support?
