### ISSUE TITLE
Indicate page validity as part of local gulp proxy serving

### ISSUE THREAD

**Issue by keithwrightbos** [ampproject/amphtml#12463]
There has been numerous times when attributes or meta tags have been introduced as part of PRs but not added to the validator whitelist.  Part of the reason is that local testing via gulp proxy works as expected as there is no validation.  Would be ideal if part of proxying would be to run the JS validator (can be async to serving page) to indicate if and why the page fails validation.

**Comment by keithwrightbos** [comment]
Also add presubmit check that all pages served from examples are valid AMP.

**Comment by choumx** [comment]
Adding `#development=1` loads the JS validator at runtime.

**Comment by rsimha** [comment]
@keithwrightbos Does `#development=1` address the need here?

**Comment by rsimha** [comment]
Closing as stale. Please reopen if the suggestion above doesn't work.
