### ISSUE TITLE
Button does not appear if Facebook Like button's URL contains numbers and dashes

### ISSUE THREAD

**Issue by YoshinoriKobayashi** [ampproject/amphtml#12464]
Hi!
Button does not appear if Facebook Like button's URL contains numbers and dashes

For example NG pattern
https://xxxxxx/column/160824-6/amp
https://xxxxxx/column/666-666/amp

For example OK pattern
https://xxxxxx/column/naturak-6/amp
https://xxxxxx/column/natural-hi/amp
https://xxxxxx/column/666666/amp

Thank you!

**Comment by eduardogoncalves** [comment]
@YoshinoriKobayashi  Hi, I tested, and it's working, can you check the source code of this page?
https://www.testesmegadivertidos.com.br/teste/16_amigoempromocao-quais-amigos-estao-em-promocao-na-sua-loja-virtual.html
```
<amp-facebook-like width=200 height=29
    layout="fixed"
    data-layout="button_count"
	data-size="large"
    data-href="https://www.testesmegadivertidos.com.br/teste/16_amigoempromocao-quais-amigos-estao-em-promocao-na-sua-loja-virtual.html">
</amp-facebook-like>


```

You must add this in header:
```
<script async custom-element="amp-facebook-like" src="https://cdn.ampproject.org/v0/amp-facebook-like-0.1.js"></script>

```

**Comment by eduardogoncalves** [comment]
![image](https://user-images.githubusercontent.com/4308648/34007969-90b60ea8-e0e2-11e7-8d0b-9fb261733f75.png)

**Comment by YoshinoriKobayashi** [comment]
@aghassemi  @eduardogoncalves Thank you!(*^^*)
Like Button does not appear, URL is a combination of numbers and hyphens

For example NG pattern
https://xxxxxx/column/160824-6/amp
https://xxxxxx/column/666-666/amp

This is chekc point.
**160824-6**
**666-666**

I want you to see the next test page.
All but the data-href and URL are the same page.

NG pattern
https://swiftbg.github.io/swiftbook/amp/160824-6/
https://swiftbg.github.io/swiftbook/amp/naturak-6/

OK pattern
https://swiftbg.github.io/swiftbook/amp/160824-6/amp/
https://swiftbg.github.io/swiftbook/amp/344-hb/
https://swiftbg.github.io/swiftbook/amp/344-hb/amp/
https://swiftbg.github.io/swiftbook/amp/naturak-6/amp/
https://swiftbg.github.io/swiftbook/amp/natural-hi/
https://swiftbg.github.io/swiftbook/amp/natural-hi/amp/

Thank you.

**Comment by eduardogoncalves** [comment]
@YoshinoriKobayashi, please check your code and remove the highlighted part.
![image](https://user-images.githubusercontent.com/4308648/34039318-c7d57870-e16d-11e7-8115-22590d1855f7.png)

Your typing: data-href="https://www.facebook.com/https://swiftbg.github.io/swiftbook/amp/naturak-6/"
You should type: data-href="https://swiftbg.github.io/swiftbook/amp/naturak-6/"

It's working, check: http://www.testesmegadivertidos.com.br/debug/amp/

**Comment by YoshinoriKobayashi** [comment]
@eduardogoncalves 
OH no! I'm sorry! m(_ _)m  I success when I updated it!
Very Very Thank you!

**Comment by eduardogoncalves** [comment]
@aghassemi I believe you can close this one.

**Comment by aghassemi** [comment]
Thanks for your help @eduardogoncalves
