### ISSUE TITLE
Support `alt` on `<amp-pinterest>`, if not provided use the "title" from the pin data

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#12478]
Unlike `amp-instagram`, we render the `img` for `<amp-pinterest>` and therefor we can support `alt`.

Pin data also contains a `title` which we can set as `alt` if no `alt` is provided from the component

**Comment by nainar** [comment]
Just wanting to confirm the issue. 
Re:title we should set the `title` to `alt` if no `title` is provided?
Or we should set `alt` to `title` if no `title` is provided?

The issue title and description seem to be conflicting. Thank you!

**Comment by aghassemi** [comment]
@nainar not doing anything with `title` attribute on `amp-instagram`. We would expose a new `alt` attribute on `amp-instagram`, it set, we would propagate it to the `img`. If not set, I was thinking we could use some of the data that comes back from pinterest API about the image and use that as the `alt`. `title` is one of the data fields that pinterest API returns as of the data for the PIN. I think it make a decent fallback for `alt`, it is at least better than nothing :)

**Comment by nainar** [comment]
Thanks for the explanation, claiming this issue!
