### ISSUE TITLE
Support cross origin preconnect

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#12483]
I was surprised to see that preconnect with crossorigin flag doesn't validate, e.g.:

```
<link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
```

Am I missing something?

//cc @cramforce

**Comment by cramforce** [comment]
Currently we don't allow any `link-rel-preconnect` as far as I'm aware. Or did we start allowing them and only strip them?

In that case we should totally start allowing crossorigin there.

CC @Gregable

**Comment by sebastianbenz** [comment]
This is valid:  `<link rel="preconnect" href="https://fonts.gstatic.com/" >`

**Comment by cramforce** [comment]
yeah, while writing the comment I realized we changed this.

We should totally add the attribute. Assigning to @Gregable but @sebastianbenz if you want to just send a PR that would possibly be faster since it is such a simple change.

**Comment by cramforce** [comment]
PS: Hoping for some time in 2018 where this attribute won't be needed in terms of performance anymore.

**Comment by sebastianbenz** [comment]
Took a quick look at how the validator schema works. @Gregable am I right that I need to define a new rule for `link=preconnect` to make sure that `crossorigin` is only allowed in this context? Or is there a simpler way?

**Comment by honeybadgerdontcare** [comment]
@sebastianbenz This is [where you may want to put it](https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii#L140), but it may deserve it's own tagspec if we only want `crossorigin` on `link rel=preconnect`. See the [rel=stylesheet](https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii#L230) as where we already allow `crossorigin`.

**Comment by cramforce** [comment]
I think we can allow it on all `link` elements independent of `rel`.

**Comment by honeybadgerdontcare** [comment]
This is now live in production.
