### ISSUE TITLE
amp-instagram don't work correct on iOS

### ISSUE THREAD

**Issue by seomaz** [ampproject/amphtml#12489]
The instagram embed don't rendered correct, you can check on https://ampbyexample.com/components/amp-instagram/

Open on iOS

**Comment by aghassemi** [comment]
@seomaz, testing on iOS 11.2, it seems to render correctly. Could you please provide a screenshot and version of iOS you are seeing this issue on?

**Comment by seomaz** [comment]
@aghassemi  its seem to work now, thanks
