### ISSUE TITLE
Access to call tracking number outside of amp-call-tracking tag

### ISSUE THREAD

**Issue by CptWiggles** [ampproject/amphtml#12493]
## What's the issue?

We have cases where the phone number dynamically assigned via amp-call-tracking needs to be passed to a partner via a link or as part of form data. Currently, the call tracking number is only used within the context of the amp-call-tracking tag and we would like to have it available in the larger scope of the page.

I constructed a work around using amp-bind but it does not work in all use cases. If the first action the user performs is clicking on a link that needs a phone number embedded then the amp-bind expressions have not been evaluated and the user does not have a phone number in the link. This method also generates an additional request from the client to retrieve the phone number a second time (the first time being the amp-call-tracking request).

## How do we reproduce the issue?

Assigning an id to the call-tracking configuration and adding the ability to retrieve those numbers for URL substitution or use in analytics.

```
<amp-call-tracking config="https://example.com/calltracking.json" id="primaryNumber">
  <a href="tel:123456789">+1 (23) 456-789</a>
</amp-call-tracking>
```

```
<a href="https://external-example.com/?phone_number=CALL_TRACKING_NUMBER(primaryNumber)" data-amp-replace="CALL_TRACKING_NUMBER">Continue here</a>
```

## What browsers are affected?

All browsers

## Which AMP version is affected?

1512677960104

**Comment by rudygalfi** [comment]
@lannka This might be a good GFI.
