### ISSUE TITLE
Track input field engagement with amp-analytics

### ISSUE THREAD

**Issue by CptWiggles** [ampproject/amphtml#12494]
## What's the issue?

The current functionality provided by amp-analytics meets most of our goals but doesn't provide a means for tracking if a user engaged with a form field that requires text entry. For fields that do not require text entry, the current click trigger meets our needs. We would like to see a `on` option added to amp-analytics that would fire when a user started entering text into a text, tel, email, or password type field. We are not interested in the value entered into the field, and would only want to receive the name to indicate that the field was interacted with.

## How do we reproduce the issue?

Add an `interact` value for the `on` configuration to an amp-analytics trigger that will fire when the user first starts adding text to a field matching the configured selector.

```
"triggers": {
  "formInteraction": {
    "on": "interact",
    "request": "request",
    "selector": "#form-field1"
  }
}
```

## What browsers are affected?

All browsers

## Which AMP version is affected?

1512677960104

**Comment by lannka** [comment]
sounds like browser `focus` event is what you want to capture?

**Comment by jeffjose** [comment]
@CptWiggles Did @lannka's solution work for you?

**Comment by lannka** [comment]
I suggest we implement a generic DomEvent triggering in amp-analytics.
Another use case can be: #7508

/cc @zhouyx

**Comment by zhouyx** [comment]
There's a list of related requests to track dom event. 
The issues I know: #7508 #12494 #18280 #17878

If there's not one created already, I am going to create an I2I issue for this. cc @jeffjose for prioritization input.
