### ISSUE TITLE
JS Libraries 

### ISSUE THREAD

**Issue by mbougarne** [ampproject/amphtml#1250]
Hi,

I'm really sorry, I'm just wondering if I can use the js libraries like jquery or bootstrap? 

Thanks

**Comment by cramforce** [comment]
- JS libraries: NO
- CSS libraries: Yes.

Bootstrap should just work.

**Comment by mbougarne** [comment]
If there's no JS libraries there's no soul.

Thank You

**Comment by cramforce** [comment]
What would you like to build?
