### ISSUE TITLE
Feature request: Add more option for keyCode value in the event input-throttled

### ISSUE THREAD

**Issue by buihoanghai** [ampproject/amphtml#12518]
Hi, currently I'm working on search suggestion component. Im finding a solution for when the suggestion box is expanded the user enable use keyboard arrows( up, down) for selecting. I think we can not done it without having event.keyCode value in keydown event for element input.
I check the file [https://github.com/ampproject/amphtml/blob/master/src/service/action-impl.js](action-impl.js)   
My  idea is change the event listener from input to keydown.
```

const throttledInput = throttle(this.ampdoc.win, event => {
        const target = dev().assertElement(event.target);
        this.trigger(target, name, /** @type {!ActionEventDef} */ (event),
            ActionTrust.HIGH);
}, DEFAULT_THROTTLE_INTERVAL); 
this.root_.addEventListener('keydown', event => {
        const deferredEvent = new DeferredEvent(event);
        this.addTargetPropertiesAsDetail_(deferredEvent);
        throttledInput(deferredEvent);
      });
```

and in function addTargetPropertiesAsDetail_ add the keyCode value

```
  if (event.keyCode !== undefined) {
        detail['keyCode'] = event.keyCode;
    }

```

I still not built the development environment yet so I havent tested yet. But it's good if we can add more value like this.

**Comment by cathyxz** [comment]
@buihoanghai I think what you want (navigate on keypress) is already doable with the existing `amp-list` + `amp-bind`. There's an example on the travel template on ampstart here: https://ampstart.com/templates/travel/travel.amp. 

In particular, this section: 

```
<input list="locations" type="text" name="query" on="
  change:AMP.setState({
  fields_query: event.value,
  fields_query_live: event.value,
  fields_query_edited: query_query != event.value
  });
  input-debounced:AMP.setState({
  fields_query_live: event.value
  });
  " value="" [value]="fields_query">

<amp-list layout="flex-item" src="/api/places?types=(regions)&types=(cities)&input=" [src]="'/api/places?types=(regions)&types=(cities)&input=' + fields_query_live">
    <template type="amp-mustache">
      <datalist id="locations">
        {{#predictions}}
        <option value="{{description}}">
       {{/predictions}}
       </option></datalist>
    </template>
</amp-list>
```

**Comment by choumx** [comment]
If I understand correctly, I think OP wants to use keyboard (up/down arrows) to navigate the autosuggest list.

**Comment by cathyxz** [comment]
Yes, and that does work in the AMPStart example. Maybe my copied code block isn't sufficiently precise. I'll churn up a codepen.

**Comment by buihoanghai** [comment]
Hi @cathyxz  it's is good example. Unfortunately I can not using datalist tag here. You can see here https://iprice.sg/compare/apple-iphone-8/.

**Comment by buihoanghai** [comment]
Hi @cathyxz it's good example. Unfortunately I can not use it. Due to I need using template for the suggestions. You can see here https://iprice.sg/compare/apple-iphone-8/ in the top banner.

**Comment by cathyxz** [comment]
Here's a minimal [codepen](https://codepen.io/cathyxz/pen/rpeZdY/). Unfortunately yes it does rely on datalist for the keyboard navigation. Oh well. Deferring to @cvializ.

**Comment by cvializ** [comment]
This could be a good generalization and a complement to #10947

**Comment by caroqliu** [comment]
Hi there,

The new `amp-autocomplete` component supports arrow key navigation through items so reasonably resolves your search suggestion usage here. I'm going to go ahead and close this issue with the recommendation that you switch to the new component, but please feel free to let us know if you are still experiencing any problems implementing the feature you had in mind. Thanks!
