### ISSUE TITLE
Create meta tag for allowing local http sites during testing only

### ISSUE THREAD

**Issue by cch2000** [ampproject/amphtml#1252]
Allowing whitelisting local http sites is very convenient for testing. We should create a meta tag that itself is invalid AMP and thus cannot be deployed to production.

**Comment by dvoytenko** [comment]
Should we just do it under `development=1`?

**Comment by cramforce** [comment]
That doesn't help security wise because it is subject to downgrade attack.
I think allowing it only if the meta tag is present and the AMP itself is
on HTTP is OK.

**Comment by src-code** [comment]
I'd like to see something like this implemented soon - right now testing pre-production environments other than localhost that aren't terminating https is rather difficult, especially when substitutions like `SOURCE_HOST` aren't returning the port number (I'm planning to submit a pull for that one...)

**Comment by adelinamart** [comment]
Do we still need this? Thanks

**Comment by src-code** [comment]
@adelinamart I think so.  The substitutions I referenced above don't really help, since they're encoded and thus can't be used when setting the host portion of a url.

**Comment by dvoytenko** [comment]
I agree. This would be very helpful.

**Comment by adelinamart** [comment]
@dvoytenko are we planning to prioritize this anytime soon?Thanks

**Comment by dvoytenko** [comment]
This sounds useful, but I still see it as a p3.

**Comment by Gregable** [comment]
Is this still useful? (I think yes).

What are we whitelisting when this meta tag is present? (I think: allowing relative URLs in the validator in the handful of places where relative URLs are disallowed. Anything else?)

**Comment by honeybadgerdontcare** [comment]
#16616 introduces the ability to turn off validation with `#validate=0` on the query string when in developer mode. If that doesn't fully address this issue, then please reopen with why it doesn't.
