### ISSUE TITLE
Automatically scale content to fit responsively

### ISSUE THREAD

**Issue by bpaduch** [ampproject/amphtml#12548]
An AMP story designed for mobile looks fine on a mobile device and in mobile emulators in Chrome; however, when viewed in Chrome in the Desktop viewer (when browser width > 1024), the viewer resizes the story page and makes the content overflow.  This appears for the page that uses the "thirds" template, where the text that overflows is in the "lower-third".

![textoverflow-issue-in-desktopviewer](https://user-images.githubusercontent.com/1012254/34223502-8eecc1a2-e58d-11e7-8405-a1d6df627b72.png)

Live story at: https://bap-amp-001.appspot.com/
Expected: Text to resize to fit screen frame, like other pages do.

Chrome: Version 63.0.3239.84 (Official Build) (64-bit), Mac OS
Note: Looks fine in Safari

**Comment by alanorozco** [comment]
Fixed by #12901

**Comment by aghassemi** [comment]
Closing since fixed by #12901
