### ISSUE TITLE
append to amp-list

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#12540]
Feature request to have the ability to append new content to amp-list, rather than refreshing the entire contents via change in src attribute with amp-bind.

may be something that has to get implemented anyway for element-level infinite scroll (?)

@choumx @aghassemi

**Comment by choumx** [comment]
Interesting. Do you have a real world use case in mind for this? Curious what the data source is etc.

**Comment by ericlindley-g** [comment]
I've gotten this request from developers for things like lists of products and other lists of items in a grid. Most of them want infinite scroll as the ultimate goal, but this feature would be a more elegant way to append than the current more complex approaches (chained forms; chained amp-list + amp-bind)

**Comment by choumx** [comment]
Related: Kevin did some explorations awhile ago to do append/delete for the canonical "to-do list" use case. https://github.com/ampproject/amphtml/issues/7379#issuecomment-290105127

**Comment by aghassemi** [comment]
de-duping in favour of https://github.com/ampproject/amphtml/issues/13575 which has more technical discussions in regards to the same functionality.
