### ISSUE TITLE
amp-analytics: "Error: The string did not match the expected pattern."

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#12563]
> Error: The string did not match the expected pattern.
at (https://raw.githubusercontent.com/ampproject/amphtml/1513710425594/extensions/amp-analytics/0.1/analytics-root.js:215)

See `pantheon/CL-En8rq46nq2AE`.

/to @zhouyx

**Comment by zhouyx** [comment]
@choumx Do you have more information on this?  I can't access the url or `pantheon/CL-En8rq46nq2AE`.

**Comment by jridgewell** [comment]
```
Error: The string did not match the expected pattern.
    at https://raw.githubusercontent.com/ampproject/amphtml/1513979839742/extensions/amp-analytics/0.1/analytics-root.js:215:13
```

**Comment by zhouyx** [comment]
Can repro in Safari. 
`SyntaxError (DOM Exception 12): The string did not match the expected pattern` happens when `querySelect` with invalid selector. 
Will fix by throwing user error.
