### ISSUE TITLE
amp-analytics: "Error: null is not an object" 

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#12562]
> Error: null is not an object (evaluating 'a.Z.fire')
fire (https://raw.githubusercontent.com/ampproject/amphtml/1513710425594/extensions/amp-analytics/0.1/visibility-model.js:151)

See `pantheon/CP-gteCAgtLC1gE`.

/to @zhouyx

**Comment by zhouyx** [comment]
Should have fixed by #12657
