### ISSUE TITLE
amp-bind error when using dashes in class names

### ISSUE THREAD

**Issue by chauek** [ampproject/amphtml#12570]
I am getting error when using classes with dashes:

    <div id="ampSearchOverlay" class="amp-search-overlay-hidden"
       [class]="status.search-overlay-shown ? 'amp-search-overlay' : 'amp-search-overlay-hidden'">

But when using camelcase it is fine:

    <div id="ampSearchOverlay" class="ampSearchOverlayHidden"
       [class]="status.searchOverlayShown ? 'ampSearchOverlay' : 'ampSearchOverlayHidden'">

Error I am getting:

    amp-bind: Default value for [class] does not match first expression result (amp-search-overlay-hidden).

**Comment by choumx** [comment]
Thanks for your question @chauek. The issue is that, like in JS, dashes are not valid chars for variable names. So the first expression is being parsed as `status.search - overlay - shown`. Hope that helps!
