### ISSUE TITLE
INVALID_ATTR_VALUE src=

### ISSUE THREAD

**Issue by palrakeshkumar** [ampproject/amphtml#1258]
AMP validation had errors.

http://localhost:8000/#development=1:25:4 INVALID_ATTR_VALUE src=

How to resolve this.

**Comment by dvoytenko** [comment]
@palrakeshkumar could you please send the fragment of the document that causes the error? It looks like line 25 is indicated in the error message.

**Comment by Gregable** [comment]
@palrakeshkumar this error indicates that a tag on line 25, column 4 has a src attribute with an empty value. Something like `<tag src>` or `<tag src=''>`. The tag is like a `<script>` tag, which must have very specific src attribute values. See the [spec](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#scrpt) for more details.

Does that help?

**Comment by rsmything** [comment]
How can i fix it?

validator.js:208 http://192.168.1.198:3000/ru:2:8 INVALID_ATTR_VALUE src=/assets/application-859cd81611d82dccdc79ffa5680c19daa707658ea158de14ca49fd129bd7f44b.js (see https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#scrpt)

**Comment by Gregable** [comment]
@rsmything , author javascript is not allowed on AMP documents. See https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#html-tags. You'll need to remove that tag to fix this error.
