### ISSUE TITLE
amp auto-ads not working

### ISSUE THREAD

**Issue by kamurj** [ampproject/amphtml#12614]
Hello, I am having trouble finding the cause why adsense auto ads will not load on my amp pages. As far as I can tell the required code was added to the head and body section of the amp pages and while other ads load fine the auto ads don't.

Here are some example urls. Thank you for your help and feedback.

https://www.enotalone.com/forum/amp.php?t=539953
https://www.enotalone.com/forum/amp.php?t=544906

**Comment by lannka** [comment]
I got this in the error log:
> amp-auto-ads config xhr failed: SyntaxError: Unexpected end of JSON input​​​

@tlong2 could you take a look?

**Comment by kamurj** [comment]
Lannka I think that happens when viewed from a none mobile device?

**Comment by tlong2** [comment]
Hi,

AMP Auto Ads for AdSense is currently in a beta phase so the option to turn it on within the AdSense UI is not available to all AdSense accounts yet. If the client-side code is implemented without it being enabled in AdSense, then no configuration will be served and the error you see would occur.

We're working hard to make it available to everyone soon and I'll update this bug again once it is. Sorry for the inconvenience.

**Comment by kamurj** [comment]
Thank you.

**Comment by lannka** [comment]
Closing this now, and we can further discuss the 2nd issue in #16599
