### ISSUE TITLE
TBD: Resizing with multiple elements clustered at the bottom.

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#1262]
See for example: https://www.theguardian.com/australia-news/postcolonial-blog/2015/jul/21/enduring-controversy-bp-sponsorship-ignites-new-row-over-british-museums-indigenous-exhibition/amp#development=1

Here, there are several amp-list at the bottom. Depending on the loading order they fight for resize events and this can lead to some of them not resized and instead forcing overflow.

**Comment by cramforce** [comment]
We should probably render resizable templates pretty eagerly.
