### ISSUE TITLE
amp-analytics visibility triggers throws error

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#12633]
"Error: null is not an object (evaluating 'a.Z.fire')" from [release 1513710425594](https://github.com/ampproject/amphtml/releases/tag/1513710425594)

Looking at `visibility-model.js` , very likely the `onTriggerObservable_.fire()` gets called in one of the `eventPromise_` resolution block after setting `onTriggerObservable_ = null` in the `dispose()` function.

/cc @jonkeller @zhouyx @keithwrightbos 

It seems to be related to the previously reported bug #12304 , which was not completely fixed.

**Comment by jonkeller** [comment]
I agree.

We protect against using the null reference in https://github.com/ampproject/amphtml/pull/12547/files and https://github.com/ampproject/amphtml/pull/12308/files (both merged, but not until the broken build was built)

But we have not yet solved the issue of *why* we get there after a dispose(). Perhaps we are leaving a timer running, but I have not verified that yet.

**Comment by lannka** [comment]
Fixed.
