### ISSUE TITLE
Dynamic CSS Classes: UserAgents

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#1263]
> a very small hard coded list of important user agents (Twitter, Facebook, Pinterest web view browser detection). Maybe a few more.
> Re: https://github.com/ampproject/amphtml/pull/1253#issuecomment-167876528

Following up on https://github.com/ampproject/amphtml/pull/1253.

**Comment by dvoytenko** [comment]
Are these already not covered via referrer? Or is the goal to set them up via viewer?

**Comment by jridgewell** [comment]
I'm not sure what the `referrer` is set as when using the Facebook (etc) app, but I do know they set the `userAgent` to include `FBAV`. With that, we can tell this is coming from a Facebook Viewer.

**Comment by jridgewell** [comment]
It doesn't look like the Twitter app sets the user agent... :disappointed: 

| Service | UA Identifier |
| --- | --- |
| Facebook | FBAV |
| Instagram | Instagram |
| Pinterest | Pinterest |
| Twitter | it just looks like a normal Safari / Chrome UA |

**Comment by cramforce** [comment]
@jridgewell Most likely Twitter always (sigh) goes through t.co for referrer attribution.

**Comment by jridgewell** [comment]
> goes through t.co for referrer attribution

Yup, but we won't be able to tell the difference between the a user who uses the app or is using the system browser on twitter.com.

**Comment by jridgewell** [comment]
Seems recent versions of the Twitter app now include "Twitter[X]" in the UA. :smile:
