### ISSUE TITLE
amp-bind [class] binding on svg tags do not work

### ISSUE THREAD

**Issue by tbaik** [ampproject/amphtml#12635]
## What's the issue?

Trying to use the `[class]` binding on an svg tag to change the className for `amp-bind` does not change the `class` attribute.

## How do we reproduce the issue?

Here's a JSFiddle: https://jsfiddle.net/4c1k685s/1/

## What browsers are affected?

All Browsers

## Which AMP version is affected?

1513979839742

@choumx

**Comment by choumx** [comment]
Fixed by #12643.
