### ISSUE TITLE
Media playing on inactive story pages

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#12655]
## What's the issue?

On desktop, the video on page 3 starts playing before it's active, and stops playing when it becomes active.

## How do we reproduce the issue?

1. On desktop, open a multi-page STAMP.
2. Navigate from the cover to page 2
3. BAD: the video on page 3 is already playing
4. Navigate to the next page
5. BAD: The video stops playing

## What browsers are affected?

Desktop

**Comment by newmuis** [comment]
I think #12604 will fix this?  Once `MediaPool` is the only code managing these videos, it should understand when to pause/play them.

/cc @alanorozco since he's been looking into `MediaPool` stuff in my absence

**Comment by newmuis** [comment]
#12604 appears to have fixed this
