### ISSUE TITLE
Choose a specific slide in <amp-carousel> at page load based on query parameters

### ISSUE THREAD

**Issue by eric30** [ampproject/amphtml#12659]
## What's the issue?
I was asked if it's possible to choose a specific slide in <amp-carousel> based on the query parameter / anchor in the URL. Check out these pages:

https://campaign.simpleskincare.tw/Kind-to-Skin/#product_1 
https://campaign.simpleskincare.tw/Kind-to-Skin/#product_2 
https://campaign.simpleskincare.tw/Kind-to-Skin/#product_3

It dynamically decides which slide is going to be shown in the JS when the page gets loaded, and it's currently not possible with AMP.

## How do we reproduce the issue?
By visiting links above ;)

## What browsers are affected?
All

## Which AMP version is affected?
1513979839742

**Comment by cathyxz** [comment]
Seems like an extension of https://github.com/ampproject/amphtml/issues/12591 ?

**Comment by eric30** [comment]
Yup, similar to #12591. Thanks for pointing that out.

**Comment by jamesshannon** [comment]
It's implicit in this and #12591 but we the carousel should be able to update the URL too.

This should support query params (as per the title of the FR), fragments (which is what this FR is actually asking for), **and also** URL rewrites (using the [history API](https://developer.mozilla.org/en-US/docs/Web/API/History)). 

Updating the URL query params or fragment will require something a bit more sophisticated than bind.

**Comment by AcidRaZor** [comment]
Any progress on this?
