### ISSUE TITLE
Responsive amp-carousel

### ISSUE THREAD

**Issue by brunofcb** [ampproject/amphtml#1267]
I'm just wondering if there's any possibility to do a responsive amp-carousel. I've been trying to find a solution using CSS, but when you declare width and height inline, it overrides the CSS. Are there any plans to develop something similar to layout="responsive" which is available only for amp-img?

**Comment by dvoytenko** [comment]
@brunofcb there are two types of carousel: slides and a scrolling carousel. Which one are you trying to make responsive? They work slightly differently...

**Comment by brunofcb** [comment]
Slides

**Comment by dvoytenko** [comment]
Slides should support `layout=responsive` - most of elements support responsive layout. There's an example in this page:

https://github.com/ampproject/amphtml/blob/master/examples/everything.amp.html

Scrolling carousel, unfortunately, doesn't yet support `layout=responsive`, but slides should be all good.

**Comment by brunofcb** [comment]
Thanks very much @dvoytenko. It works perfectly!!!

**Comment by dvoytenko** [comment]
Sounds great! I will close this issue then. We have a separate issue somewhere that asks to make layout rules more explicit in the documentation.

**Comment by maxhartshorn** [comment]
Is there any plan to make the `type=carousel` responsive in the future? I don't see this feature being of much use if it is not at least partially responsive

**Comment by brunofcb** [comment]
@maxhartshorn If you check the previous comments, you will see that amp-carousel is only responsive for type=''slides". I don't know if there's any plan to make all types of carousel responsive.

**Comment by dvoytenko** [comment]
@maxhartshorn @brunofcb Correct, only `type=slides` carousels can take `layout=responsive` which preserves aspect ratio. However, the non-slides carousel accepts `layout=fixed-height` which resizes carousel horizontally to the available space while keeping the height. This is more applicable to scrollable carousels.

We'd like to support `layout=responsive` for all carousels. But the problem we ran into so far is that we only can express aspect ratio layout via width in CSS. But non-slides carousel require us to work off height. This is somewhat of a drawback in HTML/CSS. Similar to how IMG has `sizes` that expresses width, but nothing similar to it for height.

**Comment by maxhartshorn** [comment]
Thanks @dvoytenko for the explanation!

**Comment by dandv** [comment]
See #1531 for previous work on this.
