### ISSUE TITLE
Validator workaround for tools that need to specify an attribute value

### ISSUE THREAD

**Issue by bpaduch** [ampproject/amphtml#12675]
Encountered the following validation error **"The attribute 'autoplay' in tag 'amp-story >> amp-video' is set to the invalid value 'true'."** for an AMP Story.

When using React, [React defaults HTML attributes without a value as `true`](https://reactjs.org/docs/jsx-in-depth.html#props-default-to-true) (for example, if `autoplay` is present, React default it to `"autoplay=true"`), which matches HTML behavior . However in AMP, for attributes that don't need a value, any value specified, including 'true', throws an error. This applies to the autoplay and a few other similar attributes (e.g., the "standalone" attribute in "<amp-story standalone>").

For context, for these attributes that would generally have no value because the value has no meaning in html, the validator explicitly prohibits any value other than empty string "" and the attribute name e..g, `"autoplay=autoplay"` or `"standalone=standalone"`. The reasoning behind this rule is that `"autoplay=false"` or `"autoplay=no"` wouldn't make sense because the presence of the attribute itself with any value does in fact enable autoplay, so to avoid confusion all values are prohibited by the validator.

**Workaround**: Tools like React need to always include a value, so the `"attribute=attribute"` workaround is allowed by the validator for this reason.

Logging issue to document this issue and workaround.

**Comment by ithinkihaveacat** [comment]
https://www.ampproject.org/docs/reference/validation_errors#invalid-property-value might be a good place to document this, and should probably be updated anyway, since it's a bit misleading to say that the "fix" is to "Correct the invalid property value" in the case of valueless attributes.

Perhaps say something like:

> If you're attempting to output a valueless attribute (for example, an `<amp-video>`'s attribute such as `autoplay`, `controls` or `loop`), but your HTML build process is generating a default (but invalid) value such as `true` (React, for example, will produce `<amp-video autoplay="true" ...>` [by default](https://reactjs.org/docs/jsx-in-depth.html#props-default-to-true)), the workaround is simply to arrange for the attribute's name to be output as the value. For example, `<amp-video autoplay="autoplay" ...>`.

**Comment by bpaduch** [comment]
will look @ in: Q1/Q2
