### ISSUE TITLE
Resolve preact + react-dates incompatibility

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#12677]
The `date-range-picker`'s `onFocusChange` behavior is strange when used with `preact`, but works correctly with `react`. To get the size benefits of `preact`, we would prefer to find the root cause and open a PR on the `react-dates` project to make the behavior match for either library.
  
/cc @cramforce @kristoferbaxter

**Comment by aghassemi** [comment]
Closed by #12784
