### ISSUE TITLE
Sticky Ad sometimes appears on the top 

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#12697]
Doesn't repro all the time but @jpettitt was able to trigger it in a few tries. See attached image.
![screenshot from 2018-01-04 11-33-27](https://user-images.githubusercontent.com/2366341/34684683-c2b1ac24-f45a-11e7-980f-f44b87c1f1c1.png)

**Comment by jridgewell** [comment]
This should have been fixed by https://github.com/ampproject/amphtml/pull/12449, which is in Canary at the moment. Are you able to reproduce in a canary build?

**Comment by jpettitt** [comment]
Haven't seen this recently, closing. Will reopen if it happens again.
