### ISSUE TITLE
Video source fails to load with <source> element

### ISSUE THREAD

**Issue by bpaduch** [ampproject/amphtml#12706]
Specifying `<source>` instead of `src` for an `<amp-video>` in an AMP Story results in following errors:

**Failed to load because no supported source found**

![video-error](https://user-images.githubusercontent.com/1012254/34689338-21f880ea-f483-11e7-9f86-955d5c6ff603.png)

This works:
```
<amp-story-grid-layer template="fill">
  <amp-video autoplay loop
      src="assets/rabbit.mp4"
      width="720" height="1280"
      poster="assets/rabbit.jpg"
      layout="responsive">
  </amp-video>
</amp-story-grid-layer>
```

This doesn't:

```
<amp-story-grid-layer template="fill">
<amp-video autoplay loop
      width="720" height="1280"
      poster="assets/rabbit.jpg"
      layout="responsive">
    <source src="assets/rabbit.mp4" type="video/mp4">
</amp-video>
</amp-story-grid-layer>
```

Note: I tested the amp-video code alone, in an AMP page, and it works correctly.

**Comment by ithinkihaveacat** [comment]
Are you on dev-channel? Stable had a bug that sounds somewhat similar.

**Comment by bpaduch** [comment]
If you mean, have I enabled "dev-channel" on the [Experiments](https://cdn.ampproject.org/experiments.html) page.  Yes.  I have also disabled dev channel, and the same issue occurs.

**Comment by bpaduch** [comment]
Nevermind ... it's working now.
