### ISSUE TITLE
Tap on anchor elements inside amp-lightbox element doesn't work

### ISSUE THREAD

**Issue by YukiYamashina** [ampproject/amphtml#1274]
I try to create web page with a menu button, tapping which opens a menu window, using AMP HTML. amp-lightbox is used to show such a window, something like
```
<amp-lightbox id="open-menu" layout="no display">
  <nav><ul>
    <li><a href="//www.google.com/">Google</a></li>
  </ul></nav>
</amp-lightbox>

<button on="tap:open-menu">MENU<button>
```
Although the "click" does work (jump to a href page), "tap" does not work (the window close and no jump). Is it possible to fix this such that tap events on anchor element inside an amp-lightbox element trigger a jump to a href page?

[Here is an example page](http://yukiyamashina.com/playground/amp.html) (tap "MENU" at top right corner and tap some menu).

**Comment by rudygalfi** [comment]
Since #1327 was merged, is this resolved?

**Comment by sriramkrish85** [comment]
yes :)
