### ISSUE TITLE
Annotate Function declarations using lowercase 'function' instead of 'Function'

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#1275]
difference between {function()} and {Function}. The latter is an instance type and is nullable by default. function(...) should be used instead of Function whenever possible because it provides more type information about its parameters and return value.

unless we do 
var x = new Function(), we should always use lowercase 'functions' in typedefs and annotations.

**Comment by Lillian-wang** [comment]
Hi @camelburrito, I am looking into this bug. So I will update the JS docs for the file in the AMP project. Other than the third_party folder, are there any other folders I should make sure to avoid touching?
Thanks!

**Comment by camelburrito** [comment]
You would be only modifying code annotation (JS docs), so you can touch anything. When you are done run `gulp type-check` to make sure there are no type check errors ! Thanks for fixing.

**Comment by adelinamart** [comment]
this was fixed accordingly to the PR.
