### ISSUE TITLE
[amp-list] fallback workaround under HTTP Status Code as 200

### ISSUE THREAD

**Issue by leonalicious** [ampproject/amphtml#12755]
I have read the [documentation]([https://www.ampproject.org/docs/reference/components/amp-list#placeholder-and-fallback]) of `<amp-list>` and issue [#9860](https://www.ampproject.org/docs/guides/responsive/placeholders)

And I realize, the `<div fallback>` will only be trigged if the HTTP Status Code returned error, so, I am asking are there any **workaround** which I can use to display "No Data Matched" based on the **length of array returned as 0**,  and HTTP Status Code returned as 200.

**Comment by aghassemi** [comment]
This should be possible if your JSON data is a single item which itself has an array of items. Then normal conditional mustache templates can be used to render based on the length of the array.

@sebaperez @kul3r4 Do you have a snippet anywhere that does something similar?

**Comment by kul3r4** [comment]
We don't but that would be a nice thing to have!

**Comment by aghassemi** [comment]
@leonalicious Please see the sample added by @kul3r4: https://github.com/ampproject/amp-by-example/pull/1124
