### ISSUE TITLE
Allow <noscript>

### ISSUE THREAD

**Issue by Nemo64** [ampproject/amphtml#1279]
Amp pages won't work without JavaScript because all custom tags (like `<amp-img>`) will silently fail and, depending on the stylesheet, become big blocks of nothing or disappear entirely.

The validator prohibits the use of `<noscript>` outside the document head. This prevents a basic fallback or at least a notice that JavaScript is required.

I could accept the answer that amp pages simply won't work without JavaScript since such users won't get to those pages anyways (assuming a normal version of the page exists), however the `<noscript>` tag in the document head would be pointless then, wouldn't it?

I suggest to allow `<noscript>` in any context and allow some normally prohibited elements like `<img>` or `<style>` inside of them. Maybe even suggestions in the documentation on how to implement fallbacks.

**Comment by cramforce** [comment]
Should be allowed!

And, indeed `noscript img` should be allowed (and likely video, audio). Not so sure about `noscript style`

**Comment by Gregable** [comment]
Good point. So far I have, for newly allowed descendants of `<noscript>`:

* img
* video
* audio

Any other allowed tags we should add back in?

I agree with @cramforce that `<style>` is unnecessary. One can have style rules which only apply to tags inside your `<noscript>` section.

**Comment by cramforce** [comment]
@Gregable The main reason to allow style is to e.g. hide a feature outside `noscript` that doesn't work without JS, but which is not needed to read the page. We can live without for now and see how far that gets us.

List seems fine to me.

**Comment by Gregable** [comment]
Ah, makes sense. Thanks for the clarification.

**Comment by Nemo64** [comment]
The only other element I can think of is an `<iframe>`. I could live without it though.

The most important element is `<img>` (and `<picture>`? maybe?)

**Comment by Gregable** [comment]
This is now live, `<noscript>` is allowed in the document body, and `<img>`, `<video>`, and `<audio>` tags are allowed as descendant tags of the `<noscript>` tag. The others are left out for now, but feel free to raise the issue if you feel that you need them.
