### ISSUE TITLE
Wrong post tap UI reaction in amp-story header

### ISSUE THREAD

**Issue by hongwei1990** [ampproject/amphtml#12827]
## What's the issue?

Speaker icon post-tap UI reaction is wrong.  Full system header gets highlighted in gray post-tap. It should show a dark circle highlight behind the speaker icon.   

## What browsers are affected?
Mobile iOS browser only 

cc: @alanorozco @newmuis @choumx @prateekbh

![1071515792137_ pic](https://user-images.githubusercontent.com/33703058/34899087-9f826870-f7ab-11e7-9d40-7ffd62c5ba3c.jpg)

**Comment by newmuis** [comment]
@hongwei1990 The screenshot here is what I see, which does not have the header highlighted in gray.  Is this the correct behavior?

**Comment by newmuis** [comment]
I misconstrued the issue here: tapping on the header itself (not the audio icon) turns the entire header dark gray on iOS only.
