### ISSUE TITLE
Small customizations related AMP module in magento

### ISSUE THREAD

**Issue by techzotezo** [ampproject/amphtml#12831]
Hi,
We are using Plumrocket AMP module for magento.
link is here https://store.plumrocket.com/accelerated-mobile-pages-magento-extension.html
We are using affliate system there where partner can login and can see product details page and category pages.

Is it possible to see only nonamp pages after partner login.

That is after partner login it will display only non amp pages.

How to do that?

Thanks,
Dwaipayan

**Comment by aghassemi** [comment]
@techzotezo I don't believe anyone in this repo can answer your question as it is specified to a particular integration of the AMP technology. Please contact the plugin author for this questions.
