### ISSUE TITLE
Move user notification to the bottom of the screen by default

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1283]
This avoids all the "above logo" problems. Should be overridable, of course.

**Comment by erwinmombay** [comment]
suggesting to use the property `position` to override. @dvoytenko you see any problem with that property? let me know. thanks.

**Comment by cramforce** [comment]
Just `bottom: 0`, no?

**Comment by erwinmombay** [comment]
@cramforce oh right, forgot we got rid of !important.
