### ISSUE TITLE
Feature request - Allow goToSlide  to accept a var

### ISSUE THREAD

**Issue by mikeatkinsonthesecond** [ampproject/amphtml#12838]
## What's the issue?
It would be useful if goToSlide could accept a variable, so I can programatically send visitors to a specific slide

**Comment by aghassemi** [comment]
@mikeatkinsonthesecond Thanks. de-duping with https://github.com/ampproject/amphtml/issues/12659

**Comment by aghassemi** [comment]
duplicate of https://github.com/ampproject/amphtml/issues/12659
