### ISSUE TITLE
<amp-list>'s src attribute gets changed dynamically in error

### ISSUE THREAD

**Issue by micyeung** [ampproject/amphtml#12837]
Using an `amp-list` in combination with `amp-form` in a "Show More" pattern similar to the [demo in AMP by Example](https://ampbyexample.com/samples_templates/product_page/preview/), we find that the `src` attribute in `amp-list`  gets dynamically changed to a meaningless URL like the following: 
https://ampbyexample.com/samples_templates/product_page/preview/[object%20Object],[object%20Object],[object%20Object],[object%20Object],[object%20Object],[object%20Object],[object%20Object],[object%20Object],[object%20Object]

This results in a meaningless request being sent to the server. 
For large e-commerce sites, this can add up to a **huge additional load** to the server.

## How do we reproduce the issue?
Go to https://ampbyexample.com/samples_templates/product_page/preview/, scroll down to the list, Click "Show More". Notice the URL change in `src` in `amp-list`.

See steps in the attached GIF.
![amp-list](https://user-images.githubusercontent.com/9668639/34974581-c9ac50a0-fac8-11e7-87af-3e48a6c1bf0d.gif)

**Comment by kul3r4** [comment]
@micyeung are you sure the URL requests are those you see in the code? I was expecting the network calls in the Chrome console and I don't see those parameters there

**Comment by mrjoro** [comment]
I'm seeing the same thing that @kul3r4 sees in this example page--the src attribute of the amp-list updates with those "[object Object]"s, but the XHRs that are made go to the more_related_products_page as specified in the amp-list form action.

I am curious why we're updating the src in that way.

**Comment by aghassemi** [comment]
Although `src` is changing, it is actually not triggering a network request (since it is local state binding from the result of the form submit).

@choumx This case is using local state binding but `src` value of the `amp-list` is also being updated. For debugging and cosmitic purposes, we may want to skip updating the `src` in DOM when local binding is used.

**Comment by aghassemi** [comment]
Created https://github.com/ampproject/amphtml/issues/12850 for the smaller issue that `src` is changed to meaningless value. 

Closing this issue for https://github.com/ampproject/amphtml/issues/12850

**Comment by aghassemi** [comment]
@choumx So can this actually cause 404's if `amp-list` is layedout after a mutation with locale state?

**Comment by choumx** [comment]
@aghassemi I believe yes.
