### ISSUE TITLE
AMP Snowplow - support for IANA timezone

### ISSUE THREAD

**Issue by miike** [ampproject/amphtml#12830]
## What's the issue?

Snowplow AMP analytics expects a IANA time zone code to be present in the `tz` parameter however AMP passes in a time zone offset using `getTimezoneOffset()` rather than a time zone code.

## How do we reproduce the issue?

No steps required to reproduce.

## What browsers are affected?

All

## Which AMP version is affected?

Any AMP versions as this is [vendor specific](https://github.com/ampproject/amphtml/blob/3aaf01028e1cdcaa94fd5875ecce6e31acf04a4a/extensions/amp-analytics/0.1/test/vendor-requests.json#L244).

AMP doesn't currently support sending IANA timezone codes - should it?

cc @alexanderdean

**Comment by alexanderdean** [comment]
Thanks for raising @miike! Is there any appetite from the AMP Project to expose a `getTimezoneCode()`?

**Comment by zhouyx** [comment]
Thanks for raising the question. 

@miike @alexanderdean Could you briefly explain your use case here? Why timezone code instead of timezone offset is required? Is it because of daylight time? Thanks.

**Comment by alexanderdean** [comment]
Hi @zhouyx - Snowplow is an analytics platform, so we are interested in capturing as precise information about an event's time as possible:

* Given a time zone and a UTC time, you can know the offset - and therefore the local time
* Given a local time and an offset, you can know UTC time, but you do not know which time zone you’re in (because multiple timezones have the same offset)

So from an analytics perspective, offset is lower precision than TZ code.

HTH, Alex

**Comment by rudygalfi** [comment]
Is this data provided by the browser or are libraries needed? If the implementation is a wrapper around some browser-provided data, I think this seems reasonable.

**Comment by alexanderdean** [comment]
It's library-based - `require('jstimezonedetect').jstz.determine().name()` should do it.

**Comment by miike** [comment]
There's also `Intl.DateTimeFormat().resolvedOptions().timeZone` natively but with the caveat that browser support is a [little spotty](https://caniuse.com/#search=internationalization).

**Comment by zhouyx** [comment]
I don't think we should go with using the library. As a first step, we can provide the timezone code information in supported browser. @alexanderdean @miike would that help?
@rudygalfi what do you think?

**Comment by alexanderdean** [comment]
I think that sounds good!

**Comment by zhouyx** [comment]
close and track in #13044
