### ISSUE TITLE
isLocalDev applied 2 minutes after serving is confusing

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#12852]
The way `localDev` is currently set is at the end of the build during the write to dist/amp.js: 
```
[14:12:05] Enabled local development mode in dist/amp.js
[14:12:05] Wrote prod AMP config to dist/amp.js
```
This happens about 2 minutes after we start serving files locally, which results in extension developer confusion because during those 2 minutes, any extensions loading other extensions will try to load them from our CDN instead of localhost. 

Suggesting that we either print something to this effect in logs right before serving to localhost (please wait for the build to finish), serve after the build finishes, or write amp.js before building any of the extensions.

**Comment by rsimha-amp** [comment]
I like the idea of applying the config to `amp.js` as soon as it is feasible to do so, instead of after all extensions are built.

**Comment by rsimha-amp** [comment]
It turns out that it's non-trivial to Insert `enablelocaltesting()` soon after `amp.js` is built, since it's done in parallel within `compile()`. See 

https://github.com/ampproject/amphtml/blob/master/gulpfile.js#L296

**Comment by rsimha-amp** [comment]
Meanwhile, it's worth exploring whether we can call `gulp serve` after the first full build completes when `gulp` runs `gulp serve` and `gulp watch`.

**Comment by rsimha-amp** [comment]
It turns out that `gulp` version `4.0.0` supports running tasks in series via `gulp.series`. See https://github.com/gulpjs/gulp/blob/master/docs/API.md#gulpseriestasks

PR coming up to upgrade `gulp` to `4.0.0`, and to update all our tasks to use the new API.

**Comment by rsimha-amp** [comment]
@cathyxz This should be a lot better with #12882 and #12900. Let me know if you see anything else that's broken.
