### ISSUE TITLE
add a css build file in manual testing to diff postcss/cssnano output

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#1285]
when merging version updates for anything postcss/cssnano related we don't know if the css output has changed in any way (besides reading the changelog). we need to be able to at least see the difference easily.

**Comment by rudygalfi** [comment]
@erwinmombay Can you update on this and push to M1/2 if needed?

**Comment by erwinmombay** [comment]
@rudygalfi marking as M2

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
