### ISSUE TITLE
The mandatory text (CDATA) inside tag 'head > style[amp-boilerplate]' is missing or incorrect.

### ISSUE THREAD

**Issue by Itsathere** [ampproject/amphtml#12866]
My error is attached below
![capture](https://user-images.githubusercontent.com/16954075/35048517-54f83cd2-fbc3-11e7-9adb-e4f98f09892d.PNG)

Below is my source code. I have copied it from [amp](https://www.ampproject.org/docs/tutorials/create/basic_markup)

<!DOCTYPE html>
<html amp lang="en">
<head>
    <meta charset="utf-8">
    <script async src="https://cdn.ampproject.org/v0.js"></script>
    <title>Hello, AMPs</title>
    <link rel="canonical" href="https://www.buywineusa.com">
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <script type="application/ld+json">
        {
        "@context": "http://schema.org",
        "@type": "NewsArticle",
        "headline": "Open-source framework for publishing content",
        "datePublished": "2015-10-07T12:02:41Z",
        "image": [
        "logo.jpg"
        ]
        }
    </script>
    <style amp-boilerplate>
        body {
            -webkit-animation: -amp-start 8s steps(1,end) 0s 1 normal both;
            -moz-animation: -amp-start 8s steps(1,end) 0s 1 normal both;
            -ms-animation: -amp-start 8s steps(1,end) 0s 1 normal both;
            animation: -amp-start 8s steps(1,end) 0s 1 normal both;
        }

        @-webkit-keyframes -amp-start {
            from {
                visibility: hidden;
            }

            to {
                visibility: visible;
            }
        }

        @-moz-keyframes -amp-start {
            from {
                visibility: hidden;
            }

            to {
                visibility: visible;
            }
        }

        @-ms-keyframes -amp-start {
            from {
                visibility: hidden;
            }

            to {
                visibility: visible;
            }
        }

        @-o-keyframes -amp-start {
            from {
                visibility: hidden;
            }

            to {
                visibility: visible;
            }
        }

        @keyframes -amp-start {
            from {
                visibility: hidden;
            }

            to {
                visibility: visible;
            }
        }
    </style>
    <noscript>
        <style amp-boilerplate>
            body {
                -webkit-animation: none;
                -moz-animation: none;
                -ms-animation: none;
                animation: none;
            }
        </style>
    </noscript>
</head>
<body>
    <div>
	<h1>Welcome to the mobile web</h1>
    </div>
</body>
</html>

I am new for amp. Kindly help me with the error.

**Comment by orballo** [comment]
I had this same issue and it was because my code was formatted, using the code as it's on the web (respecting white space) worked for me.

**Comment by choumx** [comment]
@Itsathere Does using the verbatim boilerplate fix your issue?

**Comment by Itsathere** [comment]
Still getting one error. Trying to resolve it.

**Comment by Itsathere** [comment]
I have resolve this issue. Thanks for your valuable time.
