### ISSUE TITLE
AMP-story video playing slide early on mobile

### ISSUE THREAD

**Issue by matthewgcallahan** [ampproject/amphtml#12889]
## What's the issue?
Autoplay videos will play one slide before they are in view. This is most noticeable once a video has been unmuted, but appears to happen regardless of whether it is muted or not. 

May be a question for @newmuis or @ithinkihaveacat 

## How do we reproduce the issue?
1. Navigate to an amp-story with a video. 
2. Navigate to video slide (e.g. slide 3)
3. Unmute video. 
4. Advance two more slides. (slide 5)
5. Move back one slide (slide 4) — at this point audio should be heard from slide 3 (may take a moment before playback starts)
6. Advance back to slide 3. It should still be playing audio without starting over. Seems as if on slide activation it should restart video.
7. Return to slide 1.
8. Advance to slide 2 — again the audio should be playing.  

## What browsers are affected?
iOS Safari, iOS Chrome, Android Chrome

**Comment by newmuis** [comment]
This should have been fixed by rolling forward MediaPool (#12604), but that change hasn't rolled out to dev-channel yet.  I'll verify the fix once [1516232329194](https://github.com/ampproject/amphtml/releases/tag/untagged-3e57d73ac6c17c49bbee) hits canary.

**Comment by newmuis** [comment]
This is working at HEAD, but we're still waiting on a prod release that contains the fix.  The fix is in canary.
