### ISSUE TITLE
geo: URI protocol not recognized

### ISSUE THREAD

**Issue by ATrogolo** [ampproject/amphtml#12888]
Hi, 
I found an issue related to **geo:** URI Scheme protocol [Geo_URI_scheme](https://en.wikipedia.org/wiki/Geo_URI_scheme), a W3C standard. 
In my AMP pages I have some links which allow to open a navigation app installed on mobile devices: 
```html
<a target="_blank" href="geo:?q=24, Corso Mortara 10149 Torino (TO)" data-ssxl="Navigatore" data-ga-category="BUTTON" data-ga-event="ONCLICK" data-ga-label="Navigatore"
<div class="nav-arrow"></div>
<div class="nav-label">Navigatore</div>
</a>
```
In Google Search Console an error is raised about this: 
` URL protocol "geo" is not valid for attribute "href" in tag "a" `

Could you fix this error? 

Thanks, 
Andrea

**Comment by gilbertococchi** [comment]
Test page where it's possible to review the error: https://m.paginegialle.it/amp/pizzerie/san-zeno-naviglio/pizzeria-la-rocchetta#development=1

**Comment by aghassemi** [comment]
Any thoughts on adding `geo:` to the list? I can't think any security issues with it.

**Comment by Gregable** [comment]
I see no problems with it. That's a neat URI scheme too, I've never heard of it.

@ATrogolo , do you know of any comprehensive list of W3C URI Schemes? I would like to make sure we cover as many as possible.
