### ISSUE TITLE
How to convert before designed MVC5 application in AMP and MVC5 application designed with bootstrap and jquery.

### ISSUE THREAD

**Issue by manishlaur** [ampproject/amphtml#12884]
Hi,
i inform you that i have tried many time to convert before designed MVC5 application in AMP and which is designed with bootstrap and jquery. AMP have limited features so it is difficult for me.
so please guide me.

Thanks
Manish Kumar

**Comment by aghassemi** [comment]
@manishlaur AMP is just a subset of HTML with some restrictions and works with any technology, including MVC, that generates HTML.

This bug tracker is for issue related to AMPHTML library itself. Please use other channels suck as Slack or Stackoverflow to get guidance from the community regarding your needs.
