### ISSUE TITLE
Switching an experiment to "off" asks you if you want to enable the experiment.

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#1288]
To reproduce:
1. Go to https://cdn.ampproject.org/experiments.html.
2. Toggle an experiment to 'on'. Accept the confirmation dialog.
3. Toggle an experiment to 'off'. The dialog should show like it does in this screenshot where it asks if you want to enable the experiment:
<img width="632" alt="screen shot 2016-01-04 at 2 29 58 pm" src="https://cloud.githubusercontent.com/assets/3888212/12102475/cdf1f052-b2ef-11e5-96e2-23008c3b9c04.png">

Expected behavior is to use the term "disable" or use something neutral to the state like "Do you want to toggle the experiment ${experiment name}?"

**Comment by cramforce** [comment]
To @dvoytenko
