### ISSUE TITLE
amp-carousel arrows disappear

### ISSUE THREAD

**Issue by izebaKK** [ampproject/amphtml#12887]
## What's the issue?

After few clicks on amp-carousel right arrow, when I come to the last slide (image), both right and left arrows disappear and I can not return to the first slide anymore. 

## How do we reproduce the issue?

You can check the first example on https://www.ampproject.org/docs/reference/components/amp-carousel. After clicking right arrow few times, both arrows disappear.

## What browsers are affected?

I tried Firefox and Chrome on PC.

## Which AMP version is affected?

I've noticed this issue today and I know that few days ago everything was working good.
- amp-carousel-0.1 is script version

**Comment by eike-hass** [comment]
we can reproduce this issue on 
- OSX 10.11.5 with Chrome 63 and Firefox ESR 52.5
- Windows 10 with Edge 16

**Comment by aghassemi** [comment]
Thanks for the report. This bug impacts carousels on desktop. We are working on it and fix roll out a fix to production soon.

**Comment by izebaKK** [comment]
It is still not working good... When I "scroll" to the last slide and then go back one slide arrows disappear again (same example- https://www.ampproject.org/docs/reference/components/amp-carousel)

**Comment by cvializ** [comment]
Thank you for checking so promptly. However the fix has not yet gone to production.

**Comment by abasse** [comment]
We need to get this fixed asap!
Our production site is broken and we receive a lot of customer complaints.

**Comment by aghassemi** [comment]
@abasse, others: Apologies for the issue. The fix will roll out to production within the next hour.

**Comment by KorvinSzanto** [comment]
It looks like this may have regressed. In the latest chrome these arrows disappear after a couple clicks.

**Comment by jamesshannon** [comment]
@aghassemi, @cvializ  Not reproducible on desktop, but reproducible on [ABE](https://ampbyexample.com/components/amp-carousel/) on mobile emulation and mobile device.

**Comment by cvializ** [comment]
@jamesshannon on mobile, carousels without the `controls` attribute hide their arrow buttons after a few seconds, so that looks like expected behavior.

@KorvinSzanto if you are still seeing incorrect behavior, please open a new issue detailing the exact behavior you're seeing and the steps to reproduce. That will help us a lot in tracking and fixing any new bug.

**Comment by KorvinSzanto** [comment]
I'm not able to replicate this issue anymore with the same test I was using before. I'm thinking either something was fixed or this issue was due to some odd combination of components that I'm not using any more.

**Comment by izebaKK** [comment]
This issue is active again! Arrows are hiding on desktop after few clicks.

**Comment by aghassemi** [comment]
@izebaKK What version number/Browser are you seeing this on? Testing with https://ampbyexample.com/components/amp-carousel/ with version 1535566825959 everything seems fine. Only time I see arrows disappearing in desktop is after reaching the end of carousel when there is no more items which is intended.

**Comment by izebaKK** [comment]
I tried with Chrome Version 69.0.3497.81 and also with Microsoft Edge 42.17134.1.0.
Usually I manage to reach the end of carousel, but then I can't go back because both arrows disappear. Sometimes I can go back for one slide and then  left arrow disappear (and right doesn't show).
I'm also testing https://ampbyexample.com/components/amp-carousel/ (version 1535566825959)

**Comment by aghassemi** [comment]
@izebaKK do you mind sharing a video? Is the laptop you are using a touch-enabled one by any chance? I still have not been able to reproduce on Chrome 69, Canary 71 and Safari on my laptop.

/to @nainar to triage further.

**Comment by izebaKK** [comment]
[amp-carousel-video.zip](https://github.com/ampproject/amphtml/files/2363165/amp-carousel-video.zip)
Sorry for waiting. Here is the video. And yes, laptop has touchscreen. I've also tried on another PC without touchscreen and everything works fine there...
