### ISSUE TITLE
<amp-sidebar> partially hidden under the <g-fixed-header>

### ISSUE THREAD

**Issue by ryuran** [ampproject/amphtml#12891]
Hello

## What's the issue?

Top of amp-sidebar element is most of the time hidden under the amp header.

<img width="301" alt="capture d ecran 2018-01-18 a 18 04 28" src="https://user-images.githubusercontent.com/1309340/35110864-22a505b4-fc7a-11e7-9022-8f467e100e93.png">

## How do we reproduce the issue?

If this is a bug please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else.  Then provide step-by-step instructions for reproducing the issue:

1. Go To a amp page width en sidebar in google context (ex: https://www.google.fr/amp/m.20minutes.fr/amp/a/2200643 )
2. Click on the menu button to open `<amp-sidebar>`

## What browsers are affected?

All browsers (I think)

## Which AMP version is affected?

I think it was always broken?
AMP ⚡ HTML – Version 1516233619606

**Comment by jridgewell** [comment]
Looking into this now. It's definitely #12449.

**Comment by jridgewell** [comment]
Sorry @ryuran, we had a rollback last night due to an unrelated bug. We've redeployed this morning, it should be fixed again.
