### ISSUE TITLE
AMP-story video not playing subsequent videos once unmuted

### ISSUE THREAD

**Issue by matthewgcallahan** [ampproject/amphtml#12890]
## What's the issue?
Once an autoplay video has been unmuted on an amp-story, any subsequent autoplay videos do not play. 

## How do we reproduce the issue?
1. Navigate to an amp-story with multiple videos
2. Advance to first video
3. Unmute first video 
4. Navigate to next video  — the video should display the first frame of the video, but not play it.

## What browsers are affected?
iOS Safari, iOS Chrome, Android Chrome

**Comment by newmuis** [comment]
This should have been fixed by rolling forward MediaPool (#12604), but that change hasn't rolled out to dev-channel yet.  I'll verify the fix once [1516232329194](https://github.com/ampproject/amphtml/releases/tag/untagged-3e57d73ac6c17c49bbee) hits canary.

**Comment by newmuis** [comment]
This is working at HEAD, but we're still waiting on a prod release that contains the fix.  The fix is in canary.

**Comment by newmuis** [comment]
Note: this is still broken on iOS; tracked separately in #12976.
