### ISSUE TITLE
Confirm whether the consent should be blocking for analytics

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#1291]
FWIU, consent currently blocks analytics. However, this is not what publishing industry does today. Any way we can confirm this?

/cc @cramforce

**Comment by cramforce** [comment]
I don't understand this. Whether a publisher gets consent for doing anything is optional now and in the decision of the publisher. If not that is a bug. It needs to be documented as optional.

**Comment by dvoytenko** [comment]
Erwin, could you please confirm? I might be reading the code wrong.

**Comment by erwinmombay** [comment]
current capabilities are:
- show notification (blocks until confirmation/dismissal)
- dont show notification (doesn't block and passes through the `ampUserId` to whatever requested it from the notification service)

@dvoytenko i believe the scenario you are looking for is the "dont block but also show the notification", correct? (we currently don't support this)

**Comment by cramforce** [comment]
```js
this.set_('CLIENT_ID', (data, opt_name, opt_userNotificationId) => {
      let consent = Promise.resolve();

      // If no `opt_userNotificationId` argument is provided then
      // assume consent is given by default.
      if (opt_userNotificationId) {
        consent = userNotificationManagerFor(this.win_).then(service => {
          return service.get(opt_userNotificationId);
        });
      }

      return cidFor(this.win_).then(cid => {
        return cid.get(opt_name, consent);
      });
    });
```

`opt_userNotificationId` is optional. If you don't want to block on it, just don't specify it. Or am I missing something?

**Comment by dvoytenko** [comment]
@erwinmombay : yes, exactly. I'm looking for a way to NOT block analytics, but still show notification. Really just asking if it's possible now or not - not stating it.

**Comment by cramforce** [comment]
@dvoytenko doing `"CLIENT_ID(foo-bar)"` should do it

**Comment by cramforce** [comment]
Basically if you want to show a notification and don't block on it, you just show a notification and tell nobody that you did.

**Comment by erwinmombay** [comment]
@cramforce so right now if they do `"CLIENT_ID(foo-bar)"` it won't block, but also won't show the notification (since its been resolved asap, and that promise is what keeps the notification ui around). if that shoudn't be case ill fix and track here. if that should be an "option", let me know.

**Comment by dvoytenko** [comment]
@cramforce , that's currently also my reading, but according to @erwinmombay :

> i believe the scenario you are looking for is the "dont block but also show the notification", correct? (we currently don't support this)

**Comment by dvoytenko** [comment]
@erwinmombay that's what I'm trying to confirm based on our discussion. I currently don't see this in code - it'd appear whether or not CID was requested or notification via CID has no bearing on whether the notification is shown. I.e. the notification should always be shown (based on XHR). Could you please confirm?

**Comment by cramforce** [comment]
@erwinmombay Yeah, the notification should always show if the tag for it was included and the HTTP call for it says "Show". This should not depend on any one consumer actually requesting consent.

As I said before that is the more important case. We don't expect many pubs to use the second arg to CLIENT_ID, but it is important that they can.

**Comment by erwinmombay** [comment]
@cramforce if i'm understanding correctly. so literally they would use `foo-bar` as the value? (not an actual analytics client), that works. (which would show the notification and not block anything)

**Comment by cramforce** [comment]
```html
<amp-user-notification
    layout=container
    id="amp-user-notification1"
    data-show-if-href="http://localhost:8000/api/notification"
    data-dismiss-href="http://localhost:8000/api/notification">
    This site uses cookies to personalize content.
    <a href="">Learn more.</a>
   <button on="tap:amp-user-notification1.dismiss">I accept</button>
</amp-user-notification>
```

to work by itself without any client id to reference `amp-user-notification1`

**Comment by erwinmombay** [comment]
haha yeah, i don't know why i got hung up on the var substitution end. thanks.

**Comment by dvoytenko** [comment]
Ok. I'm closing this then.
