### ISSUE TITLE
window.context is undefined (AmpContext)

### ISSUE THREAD

**Issue by Adventive** [ampproject/amphtml#12927]
## What's the issue?
`context` empty

<img width="1440" alt="error_messaging78_debug" src="https://user-images.githubusercontent.com/34548005/35170487-71306818-fd2e-11e7-9367-dbbdb58d263c.png">
<img width="1426" alt="error_messaging78" src="https://user-images.githubusercontent.com/34548005/35170488-713ebdbe-fd2e-11e7-8af7-b333804c623d.png">
<img width="668" alt="error_messaging78_callstack" src="https://user-images.githubusercontent.com/34548005/35170543-a69dff7e-fd2e-11e7-9712-cc3a9293d561.png">

## How do we reproduce the issue?
- gulp
  - no --host config
- run secondary server 
  - load amp from localhost
- open new tab and click on it
  - click back on amp tab

## What browsers are affected?
- all browsers

## Which AMP version is affected?
- version: 1516393161691

**Comment by choumx** [comment]
https://github.com/ampproject/amphtml/blob/720cc01bcb9d255fa6a74113dd98cfca5d0c748e/3p/messaging.js#L78

**Comment by lannka** [comment]
@Adventive `win.context` is somehow reset to empty object after your script gets loaded [here](https://github.com/ampproject/amphtml/blob/master/ads/adventive.js#L31)

Could you please take a look?

**Comment by Adventive** [comment]
@lannka 
Closing as it seems the issue was on our end. Our apologies.
