### ISSUE TITLE
How to use css and js file in amp project

### ISSUE THREAD

**Issue by Itsathere** [ampproject/amphtml#12947]
**The attribute 'href' in tag 'link rel=stylesheet for fonts' is set to the invalid value**

**Only AMP runtime 'script' tags are allowed, and only in the document head.**

## What's the issue?

I am new for amp implementation into html and getting error on linking css and js file into amp-html pages 

## How do we reproduce the issue?

When I add css/js file in amp-html and run then I am getting lot of error related to css and js file.

I can't add bootstap.min.css/font-awesome.css/sweetalert.css etc into style like below because it's huge code 
<style amp-custom>
//bootstap.min.css/font-awesome.css/sweetalert.css code here
</style>

So, what's alternate option for that.

> rel values registered on microformats.org are allowed. If a rel value is missing from our whitelist, please submit an issue. stylesheet and other values like preconnect, prerender and prefetch that have side effects in the browser are disallowed. There is a special case for fetching stylesheets from whitelisted font providers.

In css I am getting 

> The attribute 'href' in tag 'link rel=stylesheet for fonts' is set to the invalid value

 error and In js file I am getting 

> Only AMP runtime 'script' tags are allowed, and only in the document head.

error

I have tried to use complete link url of css/jss it also doesn't work. What to do?

**Comment by aghassemi** [comment]
@ldthorne 

Only inlined CSS ( inside `<style amp-custom>` ) is allowed in AMP. Also note that there are several other restrictions such as limit on the size (50K) and others restrictions. Please see https://www.ampproject.org/docs/guides/responsive/style_pages for more details.

You can also checkout https://ampstart.com/ for an alternative, more AMP-friendly CSS framework.
