### ISSUE TITLE
[Feature request] Renovate

### ISSUE THREAD

**Issue by rarkins** [ampproject/amphtml#12946]
Consider installing the App "Renovate" for automated dependency updates.

Design doc: https://docs.google.com/document/d/1eWj9ehY2KlqcrGirJQtS1djpIkkoz8nOlcLD07sUwGQ/edit?usp=sharing

Summary:

- [x] Full project coverage
- [x] Lock files that "just work" (no double commit, no Travis CI config or token)
- [x] Google CLA bot approves
- [x] Git and lock file conflict resolution
- [x] Back-ported fixes after major releases
- [x] Newer dependency versions automatically replace existing PR versions
- [x] Test time reduction
- [x] Dependency grouping
- [x] PR scheduling

Cc @erwinmombay @rsimha-amp

**Comment by rarkins** [comment]
Copy/pasting @mrjoro's design review minutes from https://github.com/ampproject/amphtml/issues/12552#issuecomment-361079593:

*copy/paste start*

#### Renovate

- fork mode ("Forking Renovate")
   * GreenKeeper has a legitimate reason for write access to repo because it adds labels to PR; this was done to avoid impersonation (not impersonating a commit, but someone creating an account called "Greenkeeper" with different characters)
   * Renovate does request permission for write access to issues to label their own PRs
design doc has details on exactly which permissions are asked for and why
   * Malte's a fan of the forking mode
- doesn't trigger a PR build & a push build
- switchover cost
   * very quick to install it as an app
   * there's an onboarding PR (configure renovate) with a preview; you can also add config (e.g. send all PRs to someone)
- Raghu: there are some clear advantages to this
- a followup meeting will be scheduled to discuss

*copy/paste end*

Cc @rsimha-amp @erwinmombay

**Important clarification**: "write" access to the repository *code* is not necessary to add labels or status checks to PRs. 

Renovate can apply its own label(s) and a status check verify message when in Forking Mode too as the permissions for this are granted as part of Issues and Pull Request read/write, not code read/write.

Has the internal/private followup meeting requested by @cramforce happened yet?

**Comment by rsimha-amp** [comment]
> Has the internal/private followup meeting requested by @cramforce happened yet?

It's scheduled for later this week.

**Comment by rarkins** [comment]
@rsimha-amp could you update me with the results?

**Comment by rarkins** [comment]
@cramforce would you consider running Renovate on the four `package.json` files that are current uncovered? i.e. configure it to not run on `./package.json` but instead on the remaining files?

**Comment by cramforce** [comment]
Its an interesting idea. Will chat with Raghu about it!

**Comment by rsimha-amp** [comment]
I just looked for the other `package.json` files.

```
./validator/nodejs/package.json
./validator/package.json
./validator/gulpjs/package.json
./validator/webui/package.json
./extensions/amp-viewer-integration/0.1/messaging/package.json
./package.json
./build-system/tasks/package.json
```
- The one in `extensions/amp-viewer-integration/0.1/messaging` is something we publish, and has no dependencies to maintain.
- The one in `build-system/tasks` is unused and can be deleted.
- This leaves us with the four in `validator/`, which are owned by the Validator team. IIUC, the code in `validator/` is developed internal to Google, and periodically merged to Github, so I'm not sure how the dependency versions are updated, or if it's required that the versions be updated manually. Adding @Gregable and @powdercloud to see if dependency maintenance is something they're interested in.

**Comment by powdercloud** [comment]
@rsimha-amp For the validator package dependencies, we could probably update them some. But I don't think it's a good idea to automate it, it'll just create churn / conflicts / busy work for us. Better to do this when needed or when it's easy. Also, all four package.json files are used.

**Comment by rsimha-amp** [comment]
Thanks @powdercloud. In that case, we have all the coverage we need right now.

**Comment by rsimha** [comment]
Update: @rarkins Thanks for sending us the design doc and going through the design review last quarter. FYI, we're now using Renovate on https://github.com/ampproject/docs.

**Comment by rarkins** [comment]
Hi @rsimha, thanks - I was really excited to see that pop up in my GitHub feed yesterday. 

FYI, I set up a "mirror" fork of this main amphtml project a while back to test Renovate on, because I could see that there still seems to be a large number of out of date dependencies here.

I call it a mirror because it is a fork that syncs automatically with the ampproject/amphtml `master` branch once a day, which then allows Renovate to generate PRs with the same details as if it were running on the main repository. 

You can see that there are 20+ PRs listed here: https://github.com/renovate-mirrors/amphtml/pulls

You can actually use this "mirror" repository already to create PRs yourself for the main amphtml project using the following approach:

1. Open a mirror PR you're interested in, e.g. https://github.com/renovate-mirrors/amphtml/pull/10
2. Click on the branch name that's just below the PR title, e.g. `renovate/express-4.x`. It will take you to a URL like https://github.com/renovate-mirrors/amphtml/tree/renovate%2Fexpress-4.x
3. Click on the "Compare" button, it should take you to a URL like https://github.com/ampproject/amphtml/compare/master...renovate-mirrors:renovate/express-4.x which is comparing the mirror's PR branch to the main project's master
4. Click the Create Pull Request button to create a PR to the *main* repository with yourself as author

Obviously the above is not as convenient as if Renovate was running on the main repo itself, but I still hope it will be a useful way to fill in some dependency updates which are otherwise missing.

**Comment by rsimha** [comment]
Renovate is now running for the root `package.json` in `ampproject/amphtml`. See #16237

The packages in `validator/` are currently updated manually, but I'll look into automating that at some point in the future.
