### ISSUE TITLE
Make an amp analytics variable that gives size of creative's document

### ISSUE THREAD

**Issue by jonkeller** [ampproject/amphtml#12954]
${availableScreenHeight}, ${screenHeight}, ${viewportHeight}, and ${scrollHeight}, and their corresponding widths, do not give that. See https://screenshot.googleplex.com/KU92ARFLLwq - in this case, the ad is 300x400. Would like a way to get that into an amp-analytics request.

${elementWidth} and ${elementHeight} give the size of the amp-ad element. But if the ad that fills the slot is smaller than the available space, it still gives the size of the slot. We want the size of the creative document. There is no reason for the ad to know that it doesn't completely fill the slot.

**Comment by jonkeller** [comment]
Seems like what we want is (from the point of view of the amp-analytics tag): getParentWindowFrameElement(this.element, getTopWindow(this.win)).clientHeight;

**Comment by lannka** [comment]
Can you take a look at code [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/requests.js#L78)
```js
 this.urlReplacementService_ = Services.urlReplacementsForDoc(ampdoc);
```
it is always using the replacement service for the parent doc.
we might change it to
```
 this.urlReplacementService_ = Services.urlReplacementsForDoc(ampAnalyticsElement);
```

**Comment by jonkeller** [comment]
@lannka Even with that change, we are still ending up [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/visibility-manager.js#L707) where ```this.embed.host``` is hard-coded. I think maybe that should be ```const rootElement = dev().assertElement(getParentWindowFrameElement(ampAnalyticsElement, this.ampdoc.win));```
