### ISSUE TITLE
Allow reporting errors via the AMP Viewer

### ISSUE THREAD

**Issue by raywainman** [ampproject/amphtml#12950]
## What's the issue?

We would like to propagate errors to clients that embed an AMP Viewer by passing them through the post message channel. The AMP Viewer can opt into receiving errors by broadcasting a new capability called 'errorReporting'.

This change would facilitate monitoring and reporting of errors.

## Proposed change

Currently, errors are reported to a server endpoint in [src/error.js](https://github.com/ampproject/amphtml/blob/master/src/error.js#L261). This change would propose ALSO reporting these errors to the post message channel if the viewer is opted in.

There would be a few additional restrictions:
-This should only be allowed for single document viewer.
-The viewer must be trusted.
-The viewer must have the `errorReporter` capability.
-The document must be opted-in for error interception, this can be done by adding an additional attribute called `report-errors-to-viewer` to the `<html>` tag.

The error format sent to the viewer is exactly the same as the format sent to the server.

**Comment by choumx** [comment]
From design review (#12939), @cramforce suggested that we can loosen the restrictions to non-trusted viewers and multi-document (shadow) AMP docs. We can follow up when there is another consumer of this API.

**Comment by lannka** [comment]
Didn't get chance to attend the review.

Is this something we can do via [amp-analytics error trigger](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md#error-trigger)?

**Comment by choumx** [comment]
@lannka Didn't know about that, thanks for the pointer. I believe we want to forward non-user errors as well with access to the fine-grained error details e.g. stack trace. I'll follow up on the exact requirements internally.
