### ISSUE TITLE
Add performance metrics support to amp-analytics

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#1295]
Offshoot from #871.

We would like to augment the AMP Analytics framework to include performance metrics. Full spec and details to be added in this place later, but this could include things like:

* time to render above the fold
* time to render whole page
* server side time

Any additional ideas are appreciated!

cc @cramforce @avimehta @btownsend

**Comment by avimehta** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/PerformanceTiming lists the available performance metrics. Given that most of them are timestamps, I propose that we calculate duration from them and make the calculated durations available.

proposal for metrics and how they are calculated:

pageLoadTime = loadEventStart - navigationStart
dnsTime = domainLookupEnd - domainLookupStart
tcpConnectTime = connectEnd - connectStart
serverResponseTime = responseStart - requestStart
pageDownloadTime = responseEnd - responseStart
redirectTime = fetchStart - navigationStartStart;
domInteractiveTime = domInteractive - navigationStart;
contentLoadTime = domContentLoadedEventStart - navigationStart;

cc @btownsend
