### ISSUE TITLE
Allow amp-live-list IDs to be sorted ascending

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#12952]
## What's the issue?

amp-live-list takes timestamps on its children to determine their ordering. This feature request proposes allowing the sort order to be specified by an attribute so that it can either be ascending or descending. The default would be descending, which is currently supported.

cc @erwinmombay who may have some comments on the design

**Comment by ericlindley-g** [comment]
Related: https://github.com/ampproject/amphtml/issues/5396

**Comment by rudygalfi** [comment]
Closing in favor of #5396.
