### ISSUE TITLE
amp-iframe same-origin error cannot be avoided when streaming AMP page with amp-shadow

### ISSUE THREAD

**Issue by mattwomple** [ampproject/amphtml#12964]
## What's the issue?

When using `AMP.attachShadowDocAsStream()` as described in the [shadow doc API](https://github.com/ampproject/amphtml/blob/master/spec/amp-shadow-doc.md), there's no way to avoid the inclusion of `amp-iframe` elements that point to the same origin as where the shadow document is being loaded. Then, even before setting the `visibilityState` of the shadow document to `visible`, errors are recorded in the console concerning amp-iframe:

> Origin of &lt;amp-iframe&gt; must not be equal to container

Would it be possible to delay the generation of `amp-iframe` same-origin src errors until the `visibilityState` is set to `visible`? This would give me an opportunity to remove/alter the amp-iframe before it shows. I'm open to other suggestions about how to handle this as well.

## How do we reproduce the issue?

1. Create a page at _amp.example.com_ that includes an `amp-iframe` pointing to _www.example.com_
2. At _www.example.com_, create a PWA that loads pages from _amp.example.com_ using the streaming API (`attachShadowDocAsStream`).
3. Load the PWA and notice the error quoted above in the console.

## What browsers are affected?

Tested on the following browsers:

- Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Mobile Safari/537.36
- Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1

## Which AMP version is affected?

1516337355291

**Comment by choumx** [comment]
I see, this isn't specific to the AMP Shadow Doc API. I suppose you could create a third subdomain but that's not great. Related: #8545

**Comment by aghassemi** [comment]
Closing as dup of #8545 as there will be a single solution for both.

**Comment by timbur** [comment]
@aghassemi ETA on the solution?
