### ISSUE TITLE
Fix Getting Started guides release documentation

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#12977]
### First Timers Only
We know figuring out the process for contributing to an open source project can be intimidating, so we created this issue as a way for you to learn the ropes.  (If you feel comfortable contributing to open source projects or have any experience with git & GitHub, please leave this issue for someone else.)

This issue fixes documentation and is intended to help people who have never used git or GitHub get familiar with them.

### What you will need to know

Not much!  This issue involves fixing some of our documentation which will get you familiar with using git & GitHub.

### Motivation

We have a lot of documentation to help AMP contributors and users, but sometimes it gets out of date.  This issue will update some of our out-of-date documentation (and make it more resilient to future changes).

### The bug

Our Getting Started guides ([end-to-end](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#see-your-changes-in-production) and [quick start](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md#see-your-changes-in-production)) are intended for people getting started with contributions to AMP.  These guides have brief sections describing our release process to let people know when their contributions will be live in production, but this information is out of date.  We would like to update this documentation to be more current and resilient to future changes.

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this issue if you plan on starting work in the next day or so.  (If you [join the AMP Project](https://goo.gl/forms/T65peVtfQfEoDWeD3) we'll be able to assign this issue to you after you've claimed it.)
- [ ] See the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.  For this bug it is not necessary to [build AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server) (but you may want to do that anyway just to see what it's like).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] Using the [instructions in the Getting Started guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them), edit `contributing/getting-started-e2e.md` and `contributing/getting-started-quick.md`.  *Note that it is possible to make changes to these files using the GitHub UI, but for this issue please go through the exercise of getting and editing the code via git.*
- [ ] Edit the "See your changes in production" sections of both guides.
  - [ ] In the End-to-end guide, update the paragraph that starts "In general we cut a release."  Instead of listing specific days we now want to convey the more general point that AMP is pushed to production after undergoing some testing and that it takes about 1-2 weeks for a change to be live for all users.  Link to the [release schedule](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md) docs for people who want to know more specific details.
  - [ ] In the Quick Start guide make a similar change to the bullet point that starts "Barring any issues"
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Sign the Contributor License Agreement](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#contributor-license-agreement) before creating a Pull Request.  (If you are contributing code on behalf of a corporation start this process as early as possible.)
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review) and mention @mrjoro in a comment.  Mention `closes Issue 12977 ` in the description.
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged and it will be immediately live for all AMP contributors to benefit from.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  

Thanks, and we hope to see more contributions from you soon.

### Questions?

If you have questions ask in this issue or on your Pull Request (if you've created one) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

**Comment by mcginnis92** [comment]
Hello! I'd like to claim this issue if it is still available. Thanks!

**Comment by mrjoro** [comment]
Thanks @mcginnis92!  I've invited you to become a member of AMP Project so we can assign this issue to you officially, but feel free to start working on it.

Please let me know if you have any questions.

**Comment by mrjoro** [comment]
Thanks for making the AMP documentation better @mcginnis92!

We'd love to have your help with other fixes/additions to AMP.  If you're interested take a look through our [open issues](https://github.com/ampproject/amphtml/issues) and feel free to claim anything that looks interesting.  I'm also happy to help you find one; you can reach me on the [AMP Slack](https://docs.google.com/a/google.com/forms/d/e/1FAIpQLSd83J2IZA6cdR6jPwABGsJE8YL4pkypAbKMGgUZZriU7Qu6Tg/viewform?fbzx=4406980310789882877) (I'm mrjoro there as well).
