### ISSUE TITLE
build-system/exec.js : getOutput returns invalid object

### ISSUE THREAD

**Issue by Galphimbl** [ampproject/amphtml#12971]
## What's the issue?

build-system/exec.js : getOutput  returns object with stdout === null && stderr === null

node -v
v8.9.4

yarn -v
1.3.2

gulp -v
[11:31:54] CLI version 3.9.1

## How do we reproduce the issue?

1. clone https://github.com/Galphimbl/amphtml
2. run "yarn install" or "gulp"

**Comment by rsimha-amp** [comment]
@Galphimbl Can you talk about where you are using `getStdout`? Is this being run as part of `build-system/check-package-manager.js` (which is run before `yarn`), or are you calling it somewhere else?

The recommended version of `node` for AMP development is `v6`. Could you try running `nvm install 6` followed by `yarn` to see if the issue still repros?

**Comment by rsimha-amp** [comment]
I just switched to your versions and am not seeing the error. What OS are you running on? How are you calling the command? (`getOutput` inherits the `stdout` and `stderr` from the parent process)

![image](https://user-images.githubusercontent.com/26553114/35361190-675c9ba0-012e-11e8-8f2b-b41c778c15d4.png)

**Comment by Galphimbl** [comment]
my OS is windows 10.
Version: 1703
OS Build: 15063.850
System type: 64-bit operation system, x64-based processor

same issue on `node v6.12.3`
`getOutput `run as part of `build-system/check-package-manager.js`.
![yarn](https://user-images.githubusercontent.com/23402404/35379358-82622e84-01be-11e8-9588-adcbc0be9ac9.png)

i can comment `preinstall` script and install all dependencies, but `gulp` also use this in `build-system\tasks\update-packages.js:30:30`
![gulp](https://user-images.githubusercontent.com/23402404/35379372-93c4731c-01be-11e8-869b-e2ca03699b2f.png)

**Comment by rsimha-amp** [comment]
@Galphimbl Looks like we were starting a posix-only shell. #13156 should fix this.

**Comment by rsimha-amp** [comment]
@Galphimbl let me know if the fix works on windows.
