### ISSUE TITLE
Autosuggest not working properly for same query

### ISSUE THREAD

**Issue by Kishan08** [ampproject/amphtml#12970]
I'm playing with the Autosuggest example [here](https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fadvanced%2Fautosuggest%2Fsource%2F). And found some issues.

## What's the issue?

Suppose I want to search for 'California' in City input box. When I write a query like 'ca', it'll shows all the cities that contains word 'ca', now after removing the query from input box if i again try to search with the same query ['ca'] then it doesn't show any result in amp-selector component. But if I modify it like 'ca' **wait for a second and then enter** 'l', then it shows cities with matching word. This happens every time when I try to search with same query.

## How do we reproduce the issue?

Here's a [GIF](http://gph.is/2G6TYbj) for the reference.

## What browsers are affected?

Latest version of Chrome and Firefox.

## Which AMP version is affected?

Version 1516337355291

**Comment by Kishan08** [comment]
Any update?

**Comment by buihoanghai** [comment]
It's not a bug. It's a feature. :). Currently they used input-debounce event for the example. The debounce time is 300ms. if have any changes when time end it will fire the event. If change to input-throttled event this issue will be fixed. But it's a big deal here

**Comment by Kishan08** [comment]
Aha, thanks for the suggestion. Will close the issue.
