### ISSUE TITLE
Add support for getting URL parameters from URL and passing along using amp-analytics

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#1299]
Offshoot from discussion in #871.

> Is there a way to pull parameters out of the URL?
Example: foo.com/section/page.html?a=5#b=3. We'd know there's a parameter a with a value of 5 or that the anchor portion says b=3

**Comment by avimehta** [comment]
I want to start working on this but before I do that, Will this ever happen? @cramforce do you use/modify the amp doc URL that is opened inside the viewers?

@rudygalfi: I tried to find a few examples of cases where the URL had any parameters but did not find any. Do you know which publishers require this? I saw that buzzfeed adds a #.<string> to it's pages after page-load but that will not be possible in AMP.

**Comment by cramforce** [comment]
Adding the # is a separate thing. When we are inside viewer we remove the fragment, otherwise we make no modification. `location.href` should have the full URL.

**Comment by rudygalfi** [comment]
To expand on what @cramforce said, a publisher might construct the link with specific parameters and share it to social media.

Here's an example of a Washington Post article's URL when clicked on from Facebook: https://www.washingtonpost.com/news/early-lead/wp/2016/01/26/a-dog-accidentally-ran-a-half-marathon-and-adorably-isnt-the-first-to-do-so/?tid=sm_fb. While that's a non-AMP page, it's very reasonable to expect an AMP equivalent with similar parameters (https://www.washingtonpost.com/amphtml/news/early-lead/wp/2016/01/26/a-dog-accidentally-ran-a-half-marathon-and-adorably-isnt-the-first-to-do-so/?tid=sm_fb).

Washington Post should be able to set up something like a pageview trigger that would get the tid param and pass the value (or maybe the full `tid=sm_fb`) in a hit request.

**Comment by avimehta** [comment]
just to be clear, based on @rudygalfi's comment, this feature will work in non-viewer scenarios but not inside the viewer because the viewer would have removed the fragment and `location.hash` part would be empty and location.url will not contain the hash.

**Comment by avimehta** [comment]
@rudygalfi please assign this to @cory-work

**Comment by rudygalfi** [comment]
I can't make assignments outside the org (I think?) but I cleared the assignee.

**Comment by rudygalfi** [comment]
Note that #1746 covers the query params in the original request (?...)
Fragment part of URL is still open (#...)

**Comment by avimehta** [comment]
Since there are is no fragment support in the pipeline for now, do you wanna close this and/or change priority to not be high and milestone to be M2+?

**Comment by rudygalfi** [comment]
Support for fragment params has been moved to #2139. Closing this.
