### ISSUE TITLE
AMP doesn't allow <Input Type="file">

### ISSUE THREAD

**Issue by RasBaba** [ampproject/amphtml#13006]
AMP doesn't allow <Input Type="file">, but if i eliminate it from a form to upload file like zip, avi or simply txt, doc, how can a user send them?

"Input Type="file" is the automatic string of a form to send files, how it should be replaced?

**Comment by aghassemi** [comment]
@RasBaba This is somethign we are planning to add soon (few months). Please subscribe to the existing feature request here: https://github.com/ampproject/amphtml/issues/9791

**Comment by aghassemi** [comment]
Closing as dup of https://github.com/ampproject/amphtml/issues/9791

**Comment by RasBaba** [comment]
Thanks very much
