### ISSUE TITLE
Local storage API

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#1301]
AMP Local Storage API is intended to be used for consent and access systems. It's meant to supplant LocalStorage API and make it available in all different embedding scenarios, including 3rd party iframes.

**API**

API itself mirrors LocalStorage API (https://developer.mozilla.org/en-US/docs/Web/API/Storage) closely with the following methods:
- getItem
- setItem
- removeItem

One big difference from LocalStorage APIs is that all calls are asynchronous.

**Implementation**

AMP Runtime can utilize either LocalStorage API or the corresponding AMP Viewer API if LocalStorage is not available. The reasons why LocalStorage API may not be available could be due to incognito mode or 3rd party iframes.

If neither LocalStorage nor Viewer storage are available, the AMP Storage API will be considered as unavailable.

The storage is per original (canonical) origin. The maximum storage size per origin is capped (for instance) at 2K.

AMP Runtime will encrypt the storage blob when Viewer-based implementation is used. WebCrypto will be used for encryption. If WebCrypto is not available, Viewer-based storage will be considered unavailable.

**Comment by chrisptang** [comment]
Hi guys, it seems like we still lack of LocalStorage API support in AMP. So are we planning to implement this API or not?

**Comment by BosenY** [comment]
How do I use localstorage now? Is it not supported yet?
