### ISSUE TITLE
is there a amp cdn instead of cdn.ampproject.org?

### ISSUE THREAD

**Issue by minicase** [ampproject/amphtml#13029]
is there a amp cdn instead of cdn.ampproject.org?
because of china 's great firewall ,my website users can't reach google's servers.

how to get https://cdn.ampproject.org/v0.js with a mirror cdn server?

**Comment by mauricionr** [comment]
Cloud Flare https://www.cloudflare.com/?

**Comment by choumx** [comment]
https://amp.cloudflare.com/ is a well known one.
