### ISSUE TITLE
Support variable substitution for timezone code

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#13044]
### First Timers Only
We know figuring out the process for contributing to an open source project can be intimidating, so we created this issue as a way for you to learn the ropes.  (If you feel comfortable contributing to open source projects, please leave this issue for someone else.)

### What you will need to know
- Some familiarity with JavaScript

### Background
[How AMP support variable substitutions in various features](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md)
[Internationalization API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl)

### Motivation
When first implemented the variable substitution feature, we didn't add support to timezone code, because we think timezone offset is sufficient. 

Some publishers however would like to collect timezone code, because it provides more precise information about an event's time. 

Ref Issue #12830 

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] Search for an existing substitute variable that we support.  (For example: [BROWSER_LANGUAGE](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#browser-language)).  Follow the implementing strategy of it and find all files that needs to be changed.
- [ ] Keep in mind that not all [browsers support](https://caniuse.com/#search=internationalization) `Internationalization API`.
- [ ] Do some manual test and sanity check to make sure everything works.
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] You may also need to add unit test to `test-url-replacements.js`.
- [ ] Document the new supported variable to `amp-var-substitutions.md`.
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review) and request a code review from me (@zhouyx).  Mention `Fixes #13044 ` in the description.
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

### Questions?

If you have questions ask in this issue or on your Pull Request (if you've created one) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

**Comment by Manugal** [comment]
Hi,
I am a new contributor on GitHub and I would like to take care of this issue.

Best Regards,
Emanuele

**Comment by zhouyx** [comment]
Hi @Manugal Thanks for contributing.

To test the change manually you can start a local server with our gulp server. And then create your own page that has a [`<amp-pixel>`](https://github.com/ampproject/amphtml/blob/master/builtins/amp-pixel.md) component. Then you can configure your `<amp-pixel>` component to send a request that contains the timezone code information you added. To check the value, you can inspect your page and monitor the outgoing network requests. 

Please let me know if this answer your questions. Thanks.

**Comment by Manugal** [comment]
Ok, thanks.

Which is the fallback string that I have to use in case of Internationalization API is not defined?

**Comment by Manugal** [comment]
Sorry for the previous Pull Request, but I had to close it because the CLA was signed by a different user. I apologize for that.

**Comment by zhouyx** [comment]
>Which is the fallback string that I have to use in case of Internationalization API is not defined? Would it be fine to return an empty string?
Yes, an empty string is good. 

No worry. So I'll be reviewing #13896 Please let me know when it's ready for review.

**Comment by Manugal** [comment]
Hi @zhouyx 
the PR #13896 is ready to be reviewed.

**Comment by zhouyx** [comment]
Thanks @Manugal 🎉 🎉 🎉
