### ISSUE TITLE
Lightbox 2.0: name the component and clean up experimental flags

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#13051]
Figure out what we want to name the lightbox 2.0 component, and gate it behind a single properly named experimental flag. Some candidates are: 
- amp-lightbox-gallery
- amp-lightbox-viewer
- amp-gallery

If nobody has any opinions, we're going with `<amp-lightbox-gallery>`. 
Demo here: http://amphtml-nightly.herokuapp.com/test/manual/article-with-lightbox-2.0-gallery.amp.html

**Comment by choumx** [comment]
Are we sure we want a new extension name and not just increment the version for `amp-lightbox`?

**Comment by alanorozco** [comment]
In the past, there's been confusion when discussing the `amp-lightbox` element because of `amp-image-lightbox`. (see @choumx's comment right above me 🙂)

Presumably `amp-image-lightbox` is not going away for at least a while, so now there would be three components that could get confused between each other!

I prefer `amp-gallery` since it doesn't add to the ambiguity.

**Comment by cathyxz** [comment]
@alanorozco @choumx 
So the discussion here was that eventually when we are okay with bumping the version number, the current `amp-lightbox` will be renamed to `amp-modal`, and this component (currently named `amp-lightbox-gallery` will be renamed to `amp-lightbox`. After `amp-lightbox-gallery` launches, we are going to deprecate `amp-image-lightbox` (which means keep the code, but drop it from our documentation and direct current / future users to use `amp-lightbox-gallery` instead). 

The primary reasoning here is that we have now established 'lightbox' as a vocabulary that indicates the experience of opening up something in fullscreen and shimming the background. Thus this new component is going to remain in that same vein until we bump our version number.
