### ISSUE TITLE
Refused to display 'url' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'

### ISSUE THREAD

**Issue by jgsojo** [ampproject/amphtml#13056]
## What's the issue?
We have a button that navigates to a new url from the same domain, using AMP.navigateTo(url='...'). When clicking on this button, the following error is displayed on developer tools console:

*Refused to display 'urlFromSameDomain' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.*

## How do we reproduce the issue?

This is the complete code of the button:
`<button on="tap:AMP.navigateTo(url='urlFromSameDomain')">Test button</button>`

To reproduce:
1. Enter in one of our pages served from the Google AMP Cache: https://www.google.es/amp/s/www.exampleurl.com/1
2. Click on the mentioned button with the following tap event: on="tap:AMP.navigateTo(url='www.exampleurl.com/2')

When the page is **not served from the Cache, it works properly.**

## What browsers are affected?
All browsers with iOS devices, tested on multiple versions of iPhone 6 and iPhone X.

## Which AMP version is affected?
The issue is new because it is a new feature. 
AMP version: 
*Powered by AMP ⚡ HTML – Version 1516833286380*

**Comment by choumx** [comment]
Ugh, this should be navigating the window's top instead of the window itself. We should also extract this logic into a shared location.

**Comment by aghassemi** [comment]
@choumx some viewer's have the capability to navigate for the doc. See how `amp-app-banner` does the navigate to: https://github.com/ampproject/amphtml/blob/80b5d2a853d1ed8d1380e067413788a844664b68/extensions/amp-app-banner/0.1/amp-app-banner.js

**Comment by choumx** [comment]
Thanks for the pointer. I think we're going to handle A2A navigations separately: #12496

This action should behave similarly to `<a>`. IIRC, the original issue is that normal links don't work in a `<select>` dropdown.

Also, we probably should mirror the URL var substitution behavior for `<a>` tags too. Currently there's no whitelisting required. 😓
