### ISSUE TITLE
in-a-box (with AMP host): Position observer seems to be broken

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#13078]
Visit manual/amp-animation/scrollbound-embeds.amp.html
Note that the second test for in-a-box does not work.
Note that in the case above the host is AMP. 

The non-AMP host version seems to be fine: scrollbound-inabox.non.amp.html 

/o @zhouyx

**Comment by zhouyx** [comment]
It's not broken. When running `gulp` `amp-inabox.js` is not compiled and that's why the second test is not working. Works fine for me when running with `gulp --with_inabox`. Let me add a note to the testing page

**Comment by aghassemi** [comment]
@zhouyx @rsimha-amp  is there an issue with compiling inabox with default `gulp` target?

**Comment by rsimha-amp** [comment]
@aghassemi none that I'm aware of. This seems like expected behavior, doesn't it? (If a file needs to be added to the default build, it'll have to be done in `gulpfile.js`.)

**Comment by aghassemi** [comment]
yeah unless this adds significant amount of time to the build process or somehow breaks the release process, we should include it in my opinion.

**Comment by zhouyx** [comment]
The build time is already quite long. I actually think it's good to keep building inabox binary and shadow binary separate from default build

**Comment by rsimha-amp** [comment]
Currently, we don't build `inabox` when `watch` is true (applicable to `gulp` and `gulp watch`): https://github.com/ampproject/amphtml/blob/master/gulpfile.js#L351

**Comment by aghassemi** [comment]
ok, not a big deal. documentation is a good step toward making this more obvious. I approved the PR. Feel free to close the issue.
