### ISSUE TITLE
Change validator output in Chrome Dev Tools to use only human readable strings

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1307]
This would essentially be a layer on top of the validator that takes string like `INVALID_ATTR_VALUE` and changes them to "Invalid HTML attribute value:". At some point this would also be the point where we introduce i18n to these messages.

@jmadler How important do you find this?
CC @Gregable @rudygalfi

**Comment by rudygalfi** [comment]
@Gregable Can you confirm if this was taken care of?

**Comment by Gregable** [comment]
@rudygalfi confirmed

**Comment by rudygalfi** [comment]
Thanks, closing the issue.
