### ISSUE TITLE
Intent To Implement: Adding Treasure Data to amp-analytics

### ISSUE THREAD

**Issue by nurse** [ampproject/amphtml#13096]
This is an intent to implement a new vendor in amp-analytics: Treasure Data.

I'll follow up with a new PR to support this.

**Comment by kzk** [comment]
@rudygalfi @zhouyx Hi, we signed CLA. I know you're busy reviewing other PRs, but can I ask you to take a look at https://github.com/ampproject/amphtml/pull/13097 ?
