### ISSUE TITLE
Intent to implement: amp-yotpo - support for Yotpo's onsite widgets

### ISSUE THREAD

**Issue by billykov** [ampproject/amphtml#13105]
Hi AMP team!

Yotpo helps brands collect and leverage UGC in the form of reviews, photos and Q&A throughout the buyer journey to increase trust, social proof and sales.

Yotpo mainly serves eCommerce stores who embed our widgets on their site, as parts of their stores. Yotpo is growing rapidly and currently serving 300K stores.

Having the AMP plug-in will enable our partners to provide their users super fast experience while reviewing a product, asking a question or viewing a product picture. 

We took a look at Facebook Comments implementation and would also like to progress with a thin AMP layer around our widget wrapped by an amp iFrame as a first step before implementing a whole new light version of our widgets.

The implementation should be easy to use and look like:
```HTML
<amp-yotpo
       width="550"
       height="700"
       layout="responsive"
       data-app-key="liSBkl621ZZsb88tsckAs6Bzx6jQeTJTv8CDf8y5"
       data-widget-type="MainWidget"
       data-product-id="9408616206"
       data-name="hockey skates"
       data-url="https://ranabram.myshopify.com/products/hockey-skates"
       data-image-url="https://www.ampproject.org/static/img/logo-og-image.jpg"
       data-descriptipn="skates"
       data-yotpo-element-id="1">
</amp-yotpo>
```

This should yield our main reviews widget:
![image](https://user-images.githubusercontent.com/2109088/35512517-ae2f3186-0508-11e8-9d56-4252e685cccf.png)

**Comment by billykov** [comment]
Hey @choumx,
Thanks for the tag!

What are the next steps here, is there anything required from us at this point?

**Comment by choumx** [comment]
You can present this I2I at our weekly design review if you'd like, though I think it may be straightforward enough to directly implement. Please reference this I2I in your pull request(s). @aghassemi can help with code review.

**Comment by billykov** [comment]
@choumx if that is the case, I think we'll progress with our PR.
Thanks!

**Comment by aghassemi** [comment]
API mostly looks good to me. Just one suggestion: `data-image-url` -> `data-image-src` unless that's what is called in your API that your customers are familiar with.

**Comment by IdoMor** [comment]
@choumx,
Is there a way to get the original site url?
When using window.location.href we receive the iframe url

**Comment by choumx** [comment]
Retrieving the AMP page URL from within the iframe? Can you create the PR so we can see the context?

**Comment by IdoMor** [comment]
@choumx, 
We had created a PR.
https://github.com/ampproject/amphtml/pull/14521

As you will see, we are loading our widget's JS using AMP.
In the JS, we are interesting to know the actual URL in which the widget is loaded from.

Unfortunately, when loading the widget in the AMP example, the URL refers to the Iframe URL and not for the actual URL.

My question is, is there some bast practice in which we can query the Actual URL from within the widget's JS?

**Comment by mrjoro** [comment]
It looks like amp-yotpo was added in #14521.  Please reopen this (or open a new issue) if there is more to track.
