### ISSUE TITLE
ClientID: Support viewer:getClientId in addition to publisher:getClientId

### ISSUE THREAD

**Issue by ericfs** [ampproject/amphtml#13118]
In addition to [publisher:getClientId](https://github.com/ampproject/amphtml/blob/39ffc2c40933b12f4b5b85f38b89141e9f71ad64/src/service/cid-api.js#L24), add support for calling viewer:getClientId.

This should only be done when an AMP document is served from the AMP Cache and when the containing Viewer is not responsible for calling the CID API.

Internal: b/72373408

/cc @lannka

**Comment by RJSumi** [comment]
This will actually use a new endpoint, cache:getClientId.
