### ISSUE TITLE
Canonical Sharing: add an ampshare parameter to the hash fragment

### ISSUE THREAD

**Issue by ericfs** [ampproject/amphtml#13116]
Internal: b/72388029

In order to support extraction of the canonical URL by a parent App that can only access the location, the Canonical URL that should be used for sharing needs to be added to the location as a parameter in the hash fragment.

**Comment by choumx** [comment]
Sounds like the runtime needs to share the canonical URL with the viewer, but isn't hash fragment used for viewer to document communication? I'm missing something clearly.

**Comment by ericfs** [comment]
It's only used for viewer->document initialization. After that it should be safe to change.

**Comment by choumx** [comment]
Fixed by #14224.
