### ISSUE TITLE
Create a generic way to make CID generation depend on a user notification

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1313]
I think something like

`<amp-analytics data-consent-id="some-id">` may work and we'd need the same for ads like
`<amp-ad data-consent-id="some-id">`

This would be needed in all cases where the user doesn't directly specify the CLIENT_ID URL interpolation.

**Comment by erwinmombay** [comment]
@cramforce would the value still be needed on the url on requests? (if so how do we know where to place it?)

**Comment by cramforce** [comment]
Good question :)

I think we may need to invent some relatively hacky mechanism to do it. It is easy on the ads side because there the cid service is called programmatically.

**Comment by erwinmombay** [comment]
@cramforce do we also need this for `amp-ad`?

**Comment by cramforce** [comment]
I already did.
