### ISSUE TITLE
tap:my-lightbox.close reloads the page

### ISSUE THREAD

**Issue by nha** [ampproject/amphtml#13141]
## What's the issue?

Bug: a `tap` `close` event inside a lightbox reloads the page instead of just closing the lightbox.

## How do we reproduce the issue?

1. Step 1: copy the content of https://gist.github.com/nha/3f0e51cebf5838350301a378e99998d5
2. Step 2: paste on the [playground](https://ampbyexample.com/playground/)
3. scroll to the bottom, click on the "Open lightbox" button
4. click on the "X" close button

Here is what I get:

![screen shot 2018-01-30 at 16 01 20](https://user-images.githubusercontent.com/1968291/35576445-e37b2d8a-05d6-11e8-92ae-51edc00eb11c.png)

Instead, the popup should close and the viewport should stay at the bottom.

## What browsers are affected?

Tested on Chrome Version 63.0.3239.132 (Official Build) (64-bit), probably others

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1516833286380

**Comment by aghassemi** [comment]
@nha this happens because of the empty `href` on the close `a` tag (empty href = relative Url to the same page). I recommend using a `button`. If you must use `a`, please set the href to `#`.

Hope this helps.
