### ISSUE TITLE
AMP bind macro tag does not accept the attribute name

### ISSUE THREAD

**Issue by rajesh1158** [ampproject/amphtml#13172]
## What's the issue?
The tag `amp-bind-macro` does not support the attribute `name`.

## Briefly describe the bug/feature request.
I was following the examples in https://www.ampproject.org/docs/reference/components/amp-bind related to amp bind macro and found out that I cannot use the attribute `name`.

## How do we reproduce the issue?
Go to the link https://www.ampproject.org/docs/reference/components/amp-bind, scroll to the section named `Defining macros with amp-bind-macro` and then try that example.

## What browsers are affected?
All browsers, all devices

## Which AMP version is affected?
Version 1516850240342

## What worked for me?
I used an `id` attribute instead of the `name` attribute and then I was able to get the example working.

Please fix this.

**Comment by choumx** [comment]
The documentation is inaccurate -- it should be `id` not `name`. Sorry about that.
