### ISSUE TITLE
optionally "inline" contents of amp-iframe for AMP served from origin

### ISSUE THREAD

**Issue by cpapazian** [ampproject/amphtml#13186]
We have some javascript that we run from an amp-iframe. However, there are limitations on what javascript can run inside a sandboxed iframe, so for AMPs served directly to users from our origin, we simply append an extra script tag. 

It would be nice if AMP were able to support this use case, so that we could serve valid AMPs without these tradeoffs. 

FWIW, javascript in question is used for authentication/tracking and is not user visible.

**Comment by choumx** [comment]
I think we likely won't add this since we prioritize first-class support over workarounds. May I ask why does `amp-iframe` or preferably `amp-analytics` not suit your use case?

**Comment by cpapazian** [comment]
The missing capabilities are with `amp-access` in this case. We use 3rd party SDK's (Facebook and Google, primarily) to automatically log users that have connected accounts. If the `amp-access` login flow could integrate with 3rd party providers to provide a seamless login, that would be great! 

However, even with that use case solved, there will always be a case for custom code. `amp-iframe` is a nice compromise that allows a sandboxed environment for custom scripts to run from AMPs served from the AMP cache. _There is no need for these compromises when the page is served directly from our origin_.

In our autologin use case, we are not able to integrate with the Facebook SDK, since it does not run from sandboxed iframes. The obvious solution is to just add the custom javascript to the page for requests to users from our origin. This results in invalid AMP HTML, which requires special handling for bot/non-bot users, which leads to fragility.

We'd like to serve the same, valid, AMP content all the time, but right now, that hurts our ability to deliver a personalized experience users.

**Comment by choumx** [comment]
Thanks for the detailed response! 👍 

> If the amp-access login flow could integrate with 3rd party providers to provide a seamless login, that would be great!

I believe that this isn't out of the question. Here's a similar FR for Firebase auth: #11603

/cc @dvoytenko

> However, even with that use case solved, there will always be a case for custom code. amp-iframe is a nice compromise that allows a sandboxed environment for custom scripts to run from AMPs served from the AMP cache. There is no need for these compromises when the page is served directly from our origin.

It's a good point. I think that abstractly we view `amp-iframe` as an edge case/escape hatch rather than a general purpose solution. The ultimate goal is to have AMP support almost all reasonable use cases while still upholding our UX and design principles. 

> We'd like to serve the same, valid, AMP content all the time, but right now, that hurts our ability to deliver a personalized experience users.

Absolutely. We'd love to work with you to achieve this by adding new functionality to AMP.

/cc @rudygalfi

**Comment by cpapazian** [comment]
Thanks! I can add the FR requests for the `amp-access`/autologin stuff. 
> It's a good point. I think that abstractly we view amp-iframe as an edge case/escape hatch rather than a general purpose solution. 

I totally agree with this. And I think the existence of an escape hatch like `amp-iframe` is a strength of AMP.

My point is that the escape hatch should provide as much of an escape as possible. When there is an important feature, publishers are going to continue to choose custom scripts + invalid AMPs over the abstract.

**Comment by cpapazian** [comment]
If I understood this morning's presentation correctly, [amp-toolbox-optimzer](https://github.com/ampproject/amp-toolbox/tree/master/optimizer) should solve this problem nicely.
