### ISSUE TITLE
amp-carousel doesn't display text after images

### ISSUE THREAD

**Issue by davidreghay** [ampproject/amphtml#1318]
If you place inside an amp-carousel a series of div containers with amp-imgs inside of them and text following the images, images display in the carousel but the text does not.  Inspecting the document shows that the text is still in the DOM and I cannot find any CSS rules that would hide the text but it is clearly absent from the actual view in the browser.

**Comment by dvoytenko** [comment]
@davidreghay do you think you could include a sample for us to troubleshoot?

**Comment by davidreghay** [comment]
Sorry, I missed your response until now!  The specific sample is proprietary code (on an employer's server) but within the next few days I will attempt to reproduce independently.  If successful I'll include a sample here.  Thank you!

**Comment by dvoytenko** [comment]
@davidreghay Here are couple of ideas how to combine images and text in the carousel:

http://jsbin.com/mucifob/edit?html,css,output

I'll close this bug for now, but please reopen if you have any issues.

**Comment by davidreghay** [comment]
@dvoytenko  Thanks this looks really great!
