### ISSUE TITLE
Support messaging out of iframe for analytics events

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#13196]
## What's the issue?

From #12607 via @p2er:

An iframe might have to load additional tracking scripts which might impact the page/iframe performance. The duplicate implementation of tracking and unnecessary load of additional scripts might easily be avoided if the iframe could postMessage to the AMP page, where AMP-analytics could then execute a predefined trigger to handle the calls.

## How do we reproduce the issue?

1. build simple amp page with amp-analytics trigger predefined
2. include amp-iframe in page
3. build simple iframe content page with post message implementation to trigger tracking event on link/button click
4. click button/link inside iframe
5. fire tracking request on AMP page prior to link navigation

**Comment by zhouyx** [comment]
If I understand this correctly, tracking prior to link navigation is hard to do without the support of `beacon`. Basically we can't control browser behavior after page navigation and it's very likely browser will not send out the tracking request.

**Comment by rudygalfi** [comment]
@zhouyx That's a good point. I would think about this FR more generally like there's no navigation. For example, what if you click a button inside an iframe and you want to track that event using AMP analytics in the master page.

**Comment by zhouyx** [comment]
Tracking button click should work! But I wonder what's iframe's incentive to support this?

**Comment by rudygalfi** [comment]
First-party iframe use cases are easy to consider, although they are also the easiest to solve in other ways. Consider:

A publisher creates an interactive feature using non-AMP HTML. They want to include it inside the AMP version of the article. They host the interactive feature on a standalone page that is iframed inside of the AMP page. The publisher wants to collect data via AMP analytics for when a reader clicks buttons in the interactive content.

**Comment by zhouyx** [comment]
I see. Thanks.

**Comment by AndrewKGuan** [comment]
This feature is super useful.

- Publishers can continue using their existing analytics js tags to generate values (VisitorID, etc.) and pass them up to the parent amp from a self-hosted 1st-p iframe page.  Such as the adobeanalytics_nativeConfig[https://marketing.adobe.com/resources/help/en_US/sc/implement/accelerated-mobile-pages.html](url) 

- Interactive widgets loaded inside an iframe (very popular for car brands to locate dealerships on a map) to pass values (results from user interaction) for updating AMP contents, for example update the zip code inside an amp form.

Thanks!

**Comment by tygavin** [comment]
@AndrewKGuan Agreed.. For your use case:

"Publishers can continue using their existing analytics js tags to generate values (VisitorID, etc.) and pass them up to the parent amp from a self-hosted 1st-p iframe page."   

We would want any AMP Analytics events to be "blocked" until it they get a message back from the iframe that contains the Visitor ID.  This "master" Visitor ID would be required for any tracking event..

Do we expect that this use case will be possible?

**Comment by zhouyx** [comment]
@tygavin Your request sounds like a different feature request. To block `<amp-analytics>` or `<amp-pixel` with certain events. Could you please create a new feature request for that, and describe your detail requirements. So that we can track and prioritize issues separately. Thank you.
