### ISSUE TITLE
Possible to load and execute Ads/Js from every source

### ISSUE THREAD

**Issue by dannylinden** [ampproject/amphtml#1319]
the current "adtech" ad implementation make it possible to load Ads from every host, its not a real validation to check prefix and folder only!?

```
export function adtech(global, data) {
  const src = data.src;
  validateSrcPrefix('https:', src);
  validateSrcContains('/addyn/', src);
  writeScript(global, src);
}
```

Demo:
http://dannylinden.de/amp/ad-test.amp.html#development=1
![bildschirmfoto 2016-01-06 um 21 17 44](https://cloud.githubusercontent.com/assets/5121876/12153748/e6307e9a-b4bb-11e5-9663-e100788c2ac6.png)

**Comment by cramforce** [comment]
Yes, we kind of don't care since we consider ads hostile anyway, so people might as well load their stuff from where ever they want.

We also support loading the iframes from arbitrary origins
https://github.com/ampproject/amphtml/blob/master/builtins/amp-ad.md#running-ads-from-a-custom-domain
