### ISSUE TITLE
Removal of amp-babel.js

### ISSUE THREAD

**Issue by alabiaga** [ampproject/amphtml#13191]
After babel upgrade to 6, amp-babel.js is likely no longer needed as it was only applicable when pulling in babel helpers which are no longer there.

1. delete amp-babel.js (https://github.com/ampproject/amphtml/blob/master/src/amp-babel.js)
2. Replace references to it in gulp file with just amp.js

**Comment by choumx** [comment]
amp-shadow-babel.js is in the same boat. /cc @erwinmombay

**Comment by erwinmombay** [comment]
closed via #13213
