### ISSUE TITLE
Enable main AMP page to present consent dialog and forward state into iframe

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#13197]
## What's the issue?

From #12607 via @p2er:

It is not reasonable to expect the iframed page to present the consent UI. Therefore, the AMP page needs to handle this by either blocking the iframe or informing it that it cannot perform its own tracking within.

**Comment by tygavin** [comment]
Be sure to handle the case where my visitor has already "opted in" to analytics on my domain and I don't need/want to present consent UI again when they arrive on a Google AMP page served up by google.com cache domain.  Doing a 'double consent' step defeats the purpose of AMP HTML which is to deliver content faster.  It also seems strange that google.com cookies are now responsible for my website's user consent choices.

One solution (that would likely make publishers very happy) would be a feature to block google.com cache from serving up my site content -- then the page will always know the current consent information contained in the 1st party domain cookie.

https://github.com/ampproject/amphtml/issues/2959

https://stackoverflow.com/questions/40964194/how-to-disable-amp-caching-from-google-search

**Comment by lannka** [comment]
This will be solved by proposal: #15290.

@tygavin It's unsafe for a platform to serve content from a random cache. `amp-consent` component solves your problem by doing an XHR to collect consent state from your own endpoint before showing the dialog.

**Comment by tygavin** [comment]
Thanks for the reply.  Just to be clear, I'm not saying it is "unsafe to serve content from random cache", I'm saying it is "unnecessary to serve any content from google cache."  (And if you could stop google from caching your content you get more security ownership of your users/content.)
