### ISSUE TITLE
url fragment to open lightbox

### ISSUE THREAD

**Issue by nha** [ampproject/amphtml#13208]
## What's the issue?

feature request: have a URL fragment that triggers a tap action

## Use case

We display user comments on a lightbox. We would like for them to be able to follow a link from the lightbox content (ex. my-url/article-123#open-comments-lightbox) and come back to the comments using the browser back arrow.

In this case we think this captures the user intent more precisely.

**Comment by aghassemi** [comment]
server-side solutions as discussed in https://github.com/ampproject/amphtml/issues/17486 are the right approach.
