### ISSUE TITLE
Div on event error

### ISSUE THREAD

**Issue by fedgrant** [ampproject/amphtml#13215]
I am trying to attach a tap event to a div. I have the following snippet.

```
<div class="scroller" on="tap:description.scrollTo(duration=500, position=top)">
  <svg id="svg-icon-scroller" width="574px" height="574px" viewBox="0 0 574 574" version="1.1" xmlns="http://www.w3.org/2000/svg">
    <polygon fill="#FFFFFF" points="242.230044 0 344.159764 0 344.159764 342.046041 495.160004 342.046041 292.832713 573.99967 79 342.452068 242.374538 342.452068"></polygon>
  </svg>
</div>
```
this snippet gives me the error

```
The parent tag of tag 'FORM > DIV [submit-success]' is 'body', but it can only be 'form'.
```

According to the documentation, the tap event can be used on any element. Also when I switch the snippet to

```
<button class="scroller" on="tap:description.scrollTo(duration=500, position=top)">
  <svg id="svg-icon-scroller" width="574px" height="574px" viewBox="0 0 574 574" version="1.1" xmlns="http://www.w3.org/2000/svg">
    <polygon fill="#FFFFFF" points="242.230044 0 344.159764 0 344.159764 342.046041 495.160004 342.046041 292.832713 573.99967 79 342.452068 242.374538 342.452068"></polygon>
  </svg>
</button>
```
I don't receive the error. How do I properly attach the event to the div element?

Easiest way to test this is to dump the strings into https://validator.ampproject.org/. I have been trying to make sense of what I think is the correct spec [here]( https://github.com/ampproject/amphtml/blob/b685a0780a7f59313666225478b2b79b463bcd0b/validator/validator-main.protoascii) and it seems like it is saying that divs are required to have a form element as a parent, which doesn't seem right.

**Comment by aghassemi** [comment]
@fedgrant The validator error is misleading and is being fixed. What you are missing is `role=button` and `tabIndex=0` on that `div` (which is enforced for accessibility)
/cc @honeybadgerdontcare

**Comment by honeybadgerdontcare** [comment]
Thanks @aghassemi, I was just about to reply. Sorry for the misleading error message. We have it resolved for the next validator release which should come next week.

**Comment by aghassemi** [comment]
@fedgrant Hope that helps, closing the issue. Feel free to reopen if your issue is not resolved.

**Comment by fedgrant** [comment]
That worked. Thanks very much for the quick reply.
