### ISSUE TITLE
Add Tealium as an analytics vendor with iframe support

### ISSUE THREAD

**Issue by tygavin** [ampproject/amphtml#13226]
## What's the issue?

(1) This is a request for a Tealium entry in analytics "vendors.js" file

(2) I think we'll need a similar hack that other analytics vendors have in order to allow clients to run  javascript in an iframe.  I believe this allows for client-side first party cookies that will persist when the user later visits the normal (non-AMP) web site.  This protects for the case when google cache hosts AMP pages in their domain (and cannot create 1st party cookies.)  Hopefully this understanding is correct.

It looks like the important stuff for other vendors is seen at the bottom of this file: https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/vendors.js

ANALYTICS_CONFIG['infonline']['triggers']['pageview']['iframe' +
/* TEMPORARY EXCEPTION */ 'Ping'] = true;

ANALYTICS_CONFIG['adobeanalytics_nativeConfig']
    ['triggers']['pageLoad']['iframe' +
      /* TEMPORARY EXCEPTION */ 'Ping'] = true;

ANALYTICS_CONFIG['oewa']['triggers']['pageview']['iframe' +
/* TEMPORARY EXCEPTION */ 'Ping'] = true;

(3) I'm not sure if Adobe's "pageLoad" or Infonline's "pageview" is the best trigger.  I'm guessing our client's implementation will be similar to Adobe's.  I would appreciate feedback and recommendation for best practice.  To copy the Adobe pattern, it would look like this..

  'tealium_native': {
    'triggers': {
      'pageLoad': {
        'on': 'visible',
        'request': 'iframeMessage',
      },
    },
  },

(4) For a longer-term enhancement.. I think a lot of this complexity and iframe hacks could be avoided if AMP pages allowed analytics or Tag Management (TMS) vendor to just run javascript.  Any plans for that?  This is a specific kind of JS that doesn't modify page content (fires pixels/beacons client-side) and waits for page to render before running.  For example, browser renders content, wait 1.5 seconds, then runs the TMS vendor JS.  I think this would also require a "don't allow google.com to serve these pages" flag to allow for setting 1st party cookies.

## How do we reproduce the issue?

This is not an issue, but a request for a new integration that copies the above vendors' (infoonline, adobe, oewa) behavior for the purposes of using tealium.

## What browsers are affected?

All.

## Which AMP version is affected?

All.

**Comment by lannka** [comment]
/cc @rudygalfi 

@tygavin the iframe analytics is deprecated. those exists only for legacy reasons.
have you considered implement your tracking solution using amp-analytics? Like how Google Tag Manager did: https://support.google.com/tagmanager/answer/7086920?hl=en

**Comment by tygavin** [comment]
@lannka Thank you for your reply. Yes, we have an AMP Analytics option as well that is documented here: https://community.tealiumiq.com/t5/Mobile-Libraries/Tealium-for-AMP/ta-p/13720

However, we are in the same position as Adobe in that we need to offer our enterprise clients both options.  Reasons for this is documented here:

https://marketing.adobe.com/resources/help/en_US/sc/implement/accelerated-mobile-pages.html

Of course, we can suggest they use "adobeanalytics_nativeConfig" but it is a little cleaner to say "tealium_native" instead. :-)  Thus, we are making the request for the similar entry.

**Comment by calebcordry** [comment]
@lannka did we come to any sort of conclusion on this?

**Comment by zhouyx** [comment]
Closing because there's no update. Please feel free to reopen if there's still request.
