### ISSUE TITLE
Allow for event to trigger arbitrary amp-analytics request

### ISSUE THREAD

**Issue by jamesshannon** [ampproject/amphtml#13233]
E.g.

`on="tap:ampAnalyticsRequest('pageview')`

Maybe also something to provide a specific variable. Like:

`on="tap:ampAnalyticsRequest('pageview', 'pageName')`

**Comment by zhouyx** [comment]
Hi @jamesshannon could you be more specific on what type of events you want to trigger the analytics request?
AMP supports `click` event to trigger any analytics request, a sample config would look like
```
{
  'requests': {
    'anyrequest': 'https://example.com/a'
   },
  'triggers': {
     'name': {
       'on': 'click',
       'selector': '${querySelector to the element}',
       'request': 'anyrequest'
     } 
  }
}
```

**Comment by jamesshannon** [comment]
This idea came up with a partner who's implementing "advanced content-style carousels" (i.e., the carousel and its slides are the primary content on the page, and therefore really important to get right).  They want to track slide views.

I suggested the click trigger as a workaround, but I don't think it's ideal:

1) Not very scalable. Publishers generally want to fire off events at arbitrary times, and the list of triggers is somewhat limited. Generally, I think an action would be useful.

Specifically for carousels:
2) While there might be own-code next/previous buttons which you've added and can add a selector against, the slides can also be changed by changed by AMP-added buttons which the selector would need to target appropriately, and also can be swiped, which I don't think there's a trigger for.
3) From the click trigger it's not trivial to know the slide number. You don't just want "clicked next" but instead "viewed slide 12". In carousels which loop, the next button might effectively go backward (to the first slide).

For this usecase, a trigger would be like:

`on="slideChange:ampAnalyticsPing('pageview', URL + 'slide-' + event.index)"`

**Comment by rudygalfi** [comment]
Agree with @zhouyx to use amp-analytics triggers like `click` or `pageview`. Full documentation can be found at https://www.ampproject.org/docs/reference/components/amp-analytics#triggers.

Please re-open this if it doesn't fully address your concern.

**Comment by rudygalfi** [comment]
Closed too soon. Didn't see latest update.

**Comment by rudygalfi** [comment]
For carousel analytics, please take a look at: https://github.com/ampproject/amphtml/blob/master/extensions/amp-carousel/amp-carousel-analytics.md

**Comment by jamesshannon** [comment]
One note is that it's not clear that some components add their own triggers. The [amp-analytics triggers section](https://www.ampproject.org/docs/reference/components/amp-analytics#triggers) is the logical place to look for this and lists `access-*` and  `video-*` triggers. So it wasn't clear that there were `carousel-*` triggers or, today, `form-*` triggers. In the case of `form-*` you need to go to the `<amp-form>` docs. In the case of carousel, the `<amp-carousel>` docs don't mention the word analytics or trigger. 

Recommendation: Have a section on `amp-analytics#triggers` that generally points out "component enabled triggers", and then link to the appropriate pages. Include *all* components which have amp-analytics integration.

**Comment by rudygalfi** [comment]
cc @jeffjose for docs updates. That's helpful feedback; thanks!
