### ISSUE TITLE
Font-size relative on `html` element fail on safari iOs in amp context

### ISSUE THREAD

**Issue by ryuran** [ampproject/amphtml#13234]
## What's the issue?

Font-size relative on `html` element fail on safari iOs in amp context.

<img width="524" alt="capture d ecran 2018-02-02 a 10 58 34" src="https://user-images.githubusercontent.com/1309340/35727397-432f5714-0808-11e8-9e44-1e080fce7a7b.png">

It is explained by double html element.

## How do we reproduce the issue?

1. Make a amp page with css `html {font-size: 50%}` 
2. Go to this page in google amp context with safari on iPhone
3. Font-size is reduced to 25% instead of 50% on android devices

## What browsers are affected?

Safari iOs

## Which AMP version is affected?

I don’t know if it's old or not

AMP ⚡ HTML – Version 1516850240342

**Comment by aghassemi** [comment]
@ryuran This is an unfortunate side effect of a work-around we have to do in iOS. If you are interested why we have 2 `html` tags in Safari, please see https://hackernoon.com/amp-ios-scrolling-and-position-fixed-redo-the-wrapper-approach-8874f0ee7876 

As a workaround, please move your CSS to `<body>`.

**Comment by ryuran** [comment]
@aghassemi I use this css as workaround
```css
html:not([⚡]){
  font-size: inherit
}
```
