### ISSUE TITLE
Some stories allow scrolling

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#13230]
Seen intermittently

**Comment by gmajoulet** [comment]
Is there any specific device/story to reproduce it? Haven't seen this one on iOS. I'm wondering if it might be a style added by publishers, that would override ours.

**Comment by newmuis** [comment]
This is report is actually incorrect.  The behavior is caused by being in an AMP viewer that scrolls (and thus allows the browser bar to be hidden).  There's no code in the runtime causing this.
