### ISSUE TITLE
Timeout pixel that fires if the RTC vendor doesn't respond on time

### ISSUE THREAD

**Issue by monish-chhadwa** [ampproject/amphtml#13264]
## What's the issue?

Since we are not present on the client, we cannot identify the number of instances we failed to return our RTC response within 1000ms or within any custom timeout specified by the publisher

## Requirements

1. Pixel that hits our servers if our RTC call timed out
2. Parameters that are sent to the RTC call are also expected in the timeout pixel
3. It would be great if we can get back the response targeting as well in the timeout pixel
4. We can also have one pixel for all timed out requests on a page, if that's feasible

**Comment by bradfrizzell** [comment]
Hey @monish-chhadwa 

This is on our roadmap for RTC. Is this something that's blocking your current implementation? I can look into expediting if needed.
