### ISSUE TITLE
Amp validator in chrome developer tools re-requests html

### ISSUE THREAD

**Issue by jeffkaufman** [ampproject/amphtml#13269]
## What's the issue?

The validator requests the page HTML a second time.  If a page is doing a 50-50 amp-vs-html A/B test, then 25% of the time the validator will evaluate a straight HTML page as if it is AMP.  When this happens, it reports validation errors that make no sense, because if you click through to the HTML source the problem is not there.

## How do we reproduce the issue?

Visit https://www.jefftk.com/maybeamp#development=1 in Chrome [1]

1. Open Developer Tools > Network
2. Check "Disable cache" if it's not already checked
3. Open Developer Tools > Console
4. Refresh the page a few times until you see validation errors: ![tmp1](https://user-images.githubusercontent.com/262566/35825527-2235cf9c-0a84-11e8-8706-77bc20924634.png)
5. Click on one of the validation errors (in this case the first one) and see that the html in the sources pane that it shows is valid amp and doesn't have the problems the validator is objecting to: ![tmp2](https://user-images.githubusercontent.com/262566/35825578-50c23530-0a84-11e8-990b-02c4f2becb16.png)

Alternatively, if "Disable Cache" is unchecked you can get the same behavior with "Ctrl+Shift+R".

[1] This is configured with:

```
http {
  ...
  split_clients $msec $amp {
    50% ".amp";
    * "";
  }
  server {
    ...
    rewrite ^/maybeamp$ /maybeamp$amp last;
  }
```

Half the time it will give you a valid AMP page, the other half of the time it will give you plain HTML instead.

## What browsers are affected?

I see this in Chrome Developer Tools on Desktop; don't know about other browsers.

## Which AMP version is affected?

`Powered by AMP ⚡ HTML – Version 1516850240342`

I don't know if this ever worked.

**Comment by honeybadgerdontcare** [comment]
This is expected behavior. The extension needs the original unaltered html so it requests it on it's own.

**Comment by honeybadgerdontcare** [comment]
I see this is not about the extension but about validation as a whole. Are you saying 25% of the time validation is wrong? Or that 25% of the time it may get an invalid response from the server?

**Comment by jeffkaufman** [comment]
I'm using stock Chrome Developer tools, so I don't believe an extension is involved?

I have a 50-50 A/B test set up on this page, so half of requests will get AMP and half won't.  If I load  https://www.jefftk.com/maybeamp#development=1 and get an AMP response, the validator will trigger a duplicate request.  Half the time this request will receive the non-amp version of the page, in which case the validator will see this non-amp response and report spurious errors.

If the developer tools validator ran on the same html used in the sources page, this would work correctly: every time the validator triggered (from seeing an AMP main page) it would correctly see that the page was valid AMP.

**Comment by honeybadgerdontcare** [comment]
Unfortunately the validator doesn't have access to the source page. The document has already been altered by the AMP Runtime. This is why it requests the source again.
