### ISSUE TITLE
🔥🐛🐤 Error: undefined is not an object (evaluating 'f.send')

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#13275]
```
Error: undefined is not an object (evaluating 'f.send')
at send (https://raw.githubusercontent.com/ampproject/amphtml/1517433808572/extensions/amp-analytics/0.1/amp-analytics.js:725)
```

**Comment by erwinmombay** [comment]
@lannka can you evaluate priority of this. thanks

**Comment by lannka** [comment]
Seems a new bug in canary. Reproduced here:
https://inc42-com.cdn.ampproject.org/v/s/inc42.com/features/startup-fintech-startups-2018/amp/?amp_js_v=0.1

**Comment by erwinmombay** [comment]
changing to p0

**Comment by erwinmombay** [comment]
@zhouyx im ok with patching canary. you're on duty anyways :P hahaha
