### ISSUE TITLE
Introduce new URL macro `PAGE_VIEW_ID_64`

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#13282]
### First Timers Only
We know figuring out the process for contributing to an open source project can be intimidating, so we created this issue as a way for you to learn the ropes.  (If you feel comfortable contributing to open source projects, please leave this issue for someone else.)

### What you will need to know
- Some familiarity with JavaScript

### Background
[How AMP support variable substitutions in various features](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md)
[RandomValue API](https://developer.mozilla.org/en-US/docs/Web/API/RandomSource/getRandomValues)

### Motivation
See issue #12674 

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] Search for the existing substitute variable `PAGE_VIEW_ID`. Look for all its occurrences through out the repo.
- [ ] Follow the same way how `PAGE_VIEW_ID` was introduced, introduce the new variable named `PAGE_VIEW_ID_64`. Use `GetRandomValues` API as the source of randomness.
- [ ] The GetRandomValues API has a pretty good [browser coverage](https://caniuse.com/#feat=getrandomvalues), but still it's good to provide a fallback. Check out how [existing code](https://github.com/ampproject/amphtml/blob/master/src/service/cid-impl.js#L497) that handles the problem. You might want to move the code to `crypto-impl.js` for reuse.
- [ ] Do some manual test and sanity check to make sure everything works, via an amp-pixel example in `amp-pixel.amp.html`.
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] You may also need to add unit test to `test-url-replacements.js`.
- [ ] Document the new supported variable to `amp-var-substitutions.md`.
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review) and request a code review from me (@lannka).  Mention `Fixes #13282 ` in the description.
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

### Questions?

If you have questions ask in this issue or on your Pull Request (if you've created one) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

**Comment by Arthanari** [comment]
Hi @lannka ,

I am Artha. I am pretty new to Github and would like to take up this task. I will get started at 6 PM EST today.

Let me know if i need to look into anything else for this task.

Thanks.
https://www.linkedin.com/in/arthanaric/

**Comment by lannka** [comment]
thanks @Arthanari, let me know if you have any questions.

**Comment by yskoh** [comment]
Hi @lannka,
Is this issue still open? 
If so, I'd like to work on it :)

**Comment by lannka** [comment]
you can try here first. or, there other options via Slack or Google group: https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#discussion-channels

**Comment by calebcordry** [comment]
Hello @Arthanari are you still working on this PR? Please let us know if you have any questions.

**Comment by gremz** [comment]
@calebcordry I'd like to take this over if @Arthanari isn't planning on completing this.
Thanks,
Greg

**Comment by calebcordry** [comment]
Hello @gremz, that would be awesome! Let me know if you have any questions.

@Arthanari I am assuming you have moved on to other things. Please ping me if this is not the case.

**Comment by Arthanari** [comment]
@calebcordry hi yes i have moved on to other things, i cudn't get my hands on this one. so i am NOT planning on working on this anymore. @gremz all the best.

**Comment by lannka** [comment]
hi @gremz do you still plan to work on this?

**Comment by gremz** [comment]
Hello, I still do. I started but was caught up in other work. I looks to resume this soon.

**Comment by lannka** [comment]
hi @gremz please let me know if you are still on it. we have some users are asking for this feature. So we want to get it prioritized.

**Comment by zhouyx** [comment]
@gremz Any update on this? Thanks

**Comment by matthieuberger** [comment]
@lannka @zhouyx as  there is no news from @gremz, I plan to move on this one

**Comment by lannka** [comment]
Thanks @matthieuberger ! Let us know if you need any help!
