### ISSUE TITLE
Limit UrlCache, make it an LRU.

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#13280]
### What you will need to know
- Basic Javascript

### Background
We have a utility method called `parseUrl` in [url.js](https://github.com/ampproject/amphtml/blob/master/src/url.js) that is used to parse a Url string.

This method caches the result of a parse so not to repeat for the same given Url however the cache used for this is unlimited which is no ideal.

### Useful Hints
The fix involved changing the cache map to be an `LRU (Least Recently Used)` cache with a large capacity (`100`).

Fortunately we have an implementation of LRU cache in [lru-cache.js](https://github.com/ampproject/amphtml/blob/master/src/lru-cache.js) which we can use here.

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.  (If you [join the AMP Project](https://goo.gl/forms/T65peVtfQfEoDWeD3) we'll be able to assign this issue to you after you've claimed it.)
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] [Sign the Contributor License Agreement](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#contributor-license-agreement) before creating a Pull Request.  (If you are contributing code on behalf of a corporation start this process as early as possible.)
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review).  Mention @aghassemi and `closes Issue #13280` in the description. 
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

### Questions?
If you have questions ask @aghassemi in this issue or on your Pull Request (if you've created one) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

**Comment by lannka** [comment]
FYI, there is an LRU implemented in utils/lru-cache.js for you to reuse

**Comment by jridgewell** [comment]
While you're at it, make the LRU's cache a prototype-less object. 😉

**Comment by cjdeleon62** [comment]
@aghassemi I would like to take a shot at this issue if it is free.

**Comment by aghassemi** [comment]
@cjdeleon62 Thanks! Assigned to you.

**Comment by cjdeleon62** [comment]
@aghassemi awesome! I'll start working on it tonight 👍

**Comment by cjdeleon62** [comment]
Hi @aghassemi, this is my first time contributing to this repo and I just have a question about the unit tests. Some are consistently failing because they are trying to match the updated scrollTop values and the difference between the actual and expected is off by decimal places. Just wondering if this is only happening to me or is this expected to flake sometimes?

**Comment by aghassemi** [comment]
@cjdeleon62 they are flakes. If your own newly written tests pass, I recommend submitting a PR. All tests would run again on Travis as part of the PR and they are less flaky than localhost runs.

**Comment by cjdeleon62** [comment]
@aghassemi okay, that is good to know, will submit a PR soon. Thanks!

**Comment by cjdeleon62** [comment]
#13892

**Comment by aghassemi** [comment]
Closed by #13892
