### ISSUE TITLE
amp-ad: Use JSON for configuration

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#13289]
One of the insights from today's V8 Memory meeting was that using large object literals as dictionaries is much more memory intensive than initiating them from JSON strings.

Using object literals: 143,400b
Using JSON.parse: 40,208b
70% savings!

**Comment by lannka** [comment]
amp-analytics/0.1/vendors.js is a huge object. are you saying we can save memory by changing the file to a JSON string, then JSON.parse the string at runtime?

Do we know how much is the extra CPU cost for the JSON parsing?

**Comment by jridgewell** [comment]
> are you saying we can save memory by changing the file to a JSON string, then JSON.parse the string at runtime

Yah. I literally wrapped it in 

```js
export const X = JSON.parse(`{
  ...
}`)
```

> Do we know how much is the extra CPU cost for the JSON parsing?

I'd doubt it be much, JSON parsing has been heavily optimized.

**Comment by lannka** [comment]
let's track it together with amp-analytics #13288

**Comment by mathiasbynens** [comment]
> Do we know how much is the extra CPU cost for the JSON parsing?

JSON is much easier to parse than JavaScript, so if anything I’d expect the CPU cost to decrease rather than increase. (Of course, the JS containing the JSON still has to be parsed — I’m assuming it’s easier to parse within the context of a string literal than outside of it.)
