### ISSUE TITLE
New Url Replacement Macros Need Documentation

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#13299]
## What's the issue?

We have implemented a new feature that allows resolution of nested macros in url replacement. e.g. `BASE64(TOUPPERCASE(CLIENT_ID(__ga))`

This new functionality (currently in experimental phase) needs to be well documented. There does not appear to be any existing documentation for the previous experiment.

see #2198 for background

**Comment by lannka** [comment]
Tracked here instead: #13371
