### ISSUE TITLE
amp-story: animations can be annoying if revisiting a page

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amphtml#13293]
The need to wait for an animation to complete can be annoying if attempting to rapidly switch between  pages (because you missed something on the previous page, for example, or just want to read over something again). This is particularly annoying if you can't find the right page--for every candidate page, you need to wait for the animation to complete.

One potential fix is to disable animations if the page has already been viewed. (Although this might be unexpected too.)

**Comment by newmuis** [comment]
I think we have decided that we don't want this; pages are always animated as a unit.
