### ISSUE TITLE
[needs ux] Lightbox Animation duration and curves

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#13314]
Enter / Exit transition time is not constant, feels “fast” when opener image is in the middle of viewport and feels “slow” when image is at the bottom of the viewport.

**Comment by ericlindley-g** [comment]
Thanks for filing! Let me know if there's anything I need to do here (including prioritizing in the UX tracker—I'll assume that this is part of general polish back and forth between you two and has similarly low effort to other polish tweaks unless I hear otherwise)

**Comment by cathyxz** [comment]
@ericlindley-g just expect to prioritize this in the UX tracker maybe in 2 sprints time. We have other more pressing things like the API to discuss for the next sprint.

**Comment by cathyxz** [comment]
A first pass for this was done in https://github.com/ampproject/amphtml/pull/14162. Waiting for further UX feedback.
