### ISSUE TITLE
Remove a4a experiment code from src/experiments.js

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#13315]
None of it has to do with the main binary's experiment implementations.

- [slowButAccuratePrng](https://github.com/ampproject/amphtml/blob/14e352a628261124a702c2700e069a8f36a8c8ee/src/experiments.js#L337-L350)
- [RANDOM_NUMBER_GENERATORS](https://github.com/ampproject/amphtml/blob/14e352a628261124a702c2700e069a8f36a8c8ee/src/experiments.js#L352-L362)
- [selectRandomItem](https://github.com/ampproject/amphtml/blob/14e352a628261124a702c2700e069a8f36a8c8ee/src/experiments.js#L364-L372)
- [randomlySelectUnsetExperiments](https://github.com/ampproject/amphtml/blob/14e352a628261124a702c2700e069a8f36a8c8ee/src/experiments.js#L374-L414)
- [getExperimentBranch](https://github.com/ampproject/amphtml/blob/14e352a628261124a702c2700e069a8f36a8c8ee/src/experiments.js#L416-L427)
- [forceExperimentBranch](https://github.com/ampproject/amphtml/blob/14e352a628261124a702c2700e069a8f36a8c8ee/src/experiments.js#L429-L443)

**Comment by lannka** [comment]
@jridgewell I don't see the description matching the title. Could you clarify?
