### ISSUE TITLE
amp-story: <amp-img> within template="fill" does not fill if child of <div>

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amphtml#13322]
This code:

```html
<amp-story-grid-layer template="fill">
  <div>
    <amp-img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABlBMVEX/AAD///9BHTQRAAAAAWJLR0QB/wIt3gAAAAd0SU1FB+ICBhY6C2IjxKYAAAAKSURBVAjXY2AAAAACAAHiIbwzAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDE4LTAyLTA2VDIyOjU4OjExKzAwOjAwbXCAoAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAxOC0wMi0wNlQyMjo1ODoxMSswMDowMBwtOBwAAAAASUVORK5CYII="
      width="1" height="1" layout="responsive"></amp-img>
  </div>
</amp-story-grid-layer>
```

Produces:

![127 0 0 1_8080_cnn-drones html nexus 5x](https://user-images.githubusercontent.com/51244/35889558-f59cbbd8-0b93-11e8-8fd3-95210070ea00.png)

Expected:

![127 0 0 1_8080_cnn-drones html nexus 5x 1](https://user-images.githubusercontent.com/51244/35889565-fbf27b44-0b93-11e8-9407-2c5a2698c5c9.png)

(The problem is somehow caused by the empty `<div>`; removing it fixes the problem.)

**Comment by newmuis** [comment]
I would expect this to mean the `div` should be full-bleed, and the contents of the `div` are sized according to styles and the `layout` attribute.

**Comment by ithinkihaveacat** [comment]
Ah, my misunderstanding then. Thanks!
