### ISSUE TITLE
Toggle next / prev buttons on <amp-lightbox-gallery>

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#13357]
### What you will need to know
- Basic Javascript
- HTML attributes (`element.setAttribute()`, `element.removeAttribute()`)
- A little bit of CSS

### Background
`<amp-lightbox-gallery>` implementation [here](https://github.com/ampproject/amphtml/blob/14e352a628261124a702c2700e069a8f36a8c8ee/extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js), enables users to open an image in an immersive fullscreen "lightbox" experience. Under the hood, it uses `<amp-carousel>` implementation [here](https://github.com/ampproject/amphtml/blob/d21a8f9729f888de1cf037aef2f26981a494f1c0/extensions/amp-carousel/0.1/base-carousel.js), with `type="slides"` to enable swiping between different images. 

### The Feature Request
When the lightbox is open, you can tap the screen to toggle the controls on and off. By controls, we mean the close button, the gallery / slide button, and the text description. 

Controls Off: 
<img width="393" alt="screen shot 2018-02-07 at 3 29 18 pm" src="https://user-images.githubusercontent.com/1528181/35947250-c6fecbda-0c1b-11e8-88da-4d9dfb2a9eb2.png">

Controls On: 
<img width="388" alt="screen shot 2018-02-07 at 3 30 46 pm" src="https://user-images.githubusercontent.com/1528181/35947276-e981ccd4-0c1b-11e8-922f-01146d449938.png">

In addition to these controls, we also have a next and prev button, but on mobile, they currently only "hint". They show up and disappear after 4 seconds. 

<img width="385" alt="screen shot 2018-02-07 at 3 29 34 pm" src="https://user-images.githubusercontent.com/1528181/35947293-03b616fa-0c1c-11e8-9d69-ce5b092f5a51.png">

**We want to change the behavior of toggling controls on Lightbox so that all the controls including next and prev are toggled at the same. time.** 

### Hints
- `<amp-carousel>` [documentation here](https://github.com/ampproject/amphtml/blob/d21a8f9729f888de1cf037aef2f26981a494f1c0/extensions/amp-carousel/amp-carousel.md) has an optional `controls` attribute that specify whether or not controls show show up. You'll notice some [fancy css](https://github.com/ampproject/amphtml/blob/d21a8f9729f888de1cf037aef2f26981a494f1c0/extensions/amp-carousel/0.1/amp-carousel.css#L50) that toggles the visibility of buttons based on that attribute. 
- `<amp-lightbox-gallery>` has a function called [`toggleControls`](https://github.com/ampproject/amphtml/blob/7ca49a954f10d3ed531f015c144161410f950921/extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js#L521). 
- You can test `<amp-lightbox-gallery>` using the manual test located at http://localhost:8000/test/manual/article-with-lightbox-2.0-gallery.amp.html, which loads after you build and run the repository with `gulp`. Full setup instructions are below. 

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.  (If you [join the AMP Project](https://goo.gl/forms/T65peVtfQfEoDWeD3) we'll be able to assign this issue to you after you've claimed it.)
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] [Sign the Contributor License Agreement](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#contributor-license-agreement) before creating a Pull Request.  (If you are contributing code on behalf of a corporation start this process as early as possible.)

- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review).  Mention @cathyxz and `closes Issue #13357` in the description. 
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

### Questions?
If you have questions ask @cathyxz in this issue or on your Pull Request (if you've created one) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

**Comment by inidaname** [comment]
Hello
I will like to take this up if it still open

**Comment by cathyxz** [comment]
Yay! @inidaname feel free to take this up by all means. Also feel free to ping me on slack (czhu) if you have questions. =)

**Comment by cathyxz** [comment]
Nicely done! Closed by #13654. 

FYI @inidaname, if your PR states "closes #13357", it will automatically close this issue. =)
