### ISSUE TITLE
Customizable conditional triggers

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#13354]
amp-analytics provides for a specific set of events that can cause analytics requests to be made. While this covers a lot of popular use cases, there are at least two imaginable ways it can not support what one is looking to do:

1. You might want a completely new kind of trigger event. For example, some amp-bind state value being reached.

2. You want to generally trigger and event, but hold it back in case some condition isn't met.

This feature request covers case #2. For example, say you have a `timer` trigger going off every 5 seconds. As part of the request on that `timer` trigger you send the value of the viewport using INCREMENTAL_ENGAGED_TIME. However, you do NOT want to capture this event if the value of INCREMENTAL_ENGAGED_TIME is zero. There should be a way to define the trigger and also define a boolean expression for whether or not it gets blocked.

**Comment by cwisecarver** [comment]
@zhouyx I am able to work on this again now. I looked into the `REPLACE` functionality that you mentioned in your email.

> We don't support this pattern in AMP right now. But maybe the new added macros `REPLACE` can help with this. 
> I am thinking that you can use a regex to find any `incremental_engaged_time` greater than 0 and replace it with a string start with `inc=${the number}`. 

> However FYI the new marcos are still under experiment flag. You may toggle on 'url-replacement-v2' flag to test with it. We haven't documented this feature, but you may refer to code here

Am I correct that this implementation would still send the heartbeat every time that the timer fired, just without the `inc=${the number}` in the URL?

**Comment by cwisecarver** [comment]
@rudygalfi @zhouyx Any word on this? What we're trying to avoid is firing the unnecessary HTTP requests. We could filter the `inc=0` on our side without too much trouble but if we can find a way around using battery or data that would be our preferred approach.

**Comment by cwisecarver** [comment]
@rudygalfi @zhouyx We had a request from a customer about the status on this. Any word yet?

**Comment by cschieffer** [comment]
Hello, I'm from Slate Magazine. We're very interested in this ticket too. Looking forward to an update!

**Comment by zhouyx** [comment]
Hi @cwisecarver @cschieffer 
The feature SGTM. We are open to a design proposal. However we can't prioritize implementation on our side at this time. Would you be interested in proposing something and contributing! Please let me know, thanks!

**Comment by cwisecarver** [comment]
@zhouyx In the [comment above](https://github.com/ampproject/amphtml/issues/13354#issuecomment-367436183) I asked a question about the implementation you suggested. You asked me not try attempt another solution until I'd looked into the `REPLACE` macro. If my assumption is correct, which I asked you to confirm, then the `REPLACE` macro wouldn't actually solve our problem so we'd have to go forward with a conditional trigger. I'm happy to try and write that code and contribute it. I just wanted to, before I started down a path, to confirm that my understanding of the function of the `REPLACE` macro was correct. 

If there's a simpler solution I'd rather use that. I just don't want to send pointless HTTP requests and waste people's data and battery.

**Comment by zhouyx** [comment]
@cwisecarver That's correct. even with the `REPLACE` macro, the heartbeat will be sent everytime, just w/o the inc=#{number}. 

Another possible solution is to batch request. However it still won't give you the feature of conditional trigger.

**Comment by cschieffer** [comment]
Hi @cwisecarver @zhouyx checking in again on this. Is there a way forward?

Thanks,
Chris

**Comment by msukmanowsky** [comment]
@rudygalfi it seems like conditional triggers are the preferred way to go here. Is this something that is on the roadmap at all (or could be) in the next month or two?

If not, we can try to investigate adding it but may need a bit of guidance.

**Comment by cwisecarver** [comment]
@rudygalfi Just bumping Mike's question. Any chance this will be on the team's radar soon or should we start working on this feature?
