### ISSUE TITLE
how to insert amp-form script ?

### ISSUE THREAD

**Issue by mountin** [ampproject/amphtml#13367]
Hello
 how is it possible to install AMP form and input script like
<script async custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js"></script>
in HEAD tag?

thanks

**Comment by aghassemi** [comment]
@mountin Please see https://ampbyexample.com/components/amp-form/ for some samples.

**Comment by mountin** [comment]
thank you but what about AMP plugin for Wordpress ?

**Comment by aghassemi** [comment]
@mountin For Workpress related questions, I suggested asking on Wordpress forum, folks on the core side of AMP are not too familiar with all integration points to be able to help in all cases. 
/cc @amedina Where is the best place to ask questions regarding AMP + Wordpress?
