### ISSUE TITLE
Support more features in AMP.navigateTo()

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#13385]
The `AMP.navigateTo()` action doesn't support some navigational features that `<a>` tags do, e.g. custom protocols and URL replacements. Perhaps it should?

**Comment by cpapazian** [comment]
one thing that would be interesting in both regular `<a>` and `navigateTo()` would be the ability to specify android intent and other custom deeplink URLs in a way that could take the mobile OS into account. 

We have found ways to get these to work, but it would be great if the platform supported them.

**Comment by choumx** [comment]
@cpapazian Interesting, can you provide an example of what you'd like?

**Comment by choumx** [comment]
IIRC, the issue was the inability to support both iOS and Android deep-link URLs in a single anchor. I believe Chris's workaround was to use amp-access to detect the platform and render the appropriate deep-link at runtime.

**Comment by cpapazian** [comment]
yup. that worked pretty well for us. we're hoping to migrate some of that markup that doesnt' require android intent:// links to the new [linker-id-forwarding](
https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/linker-id-forwarding.md).
