### ISSUE TITLE
Testing amp pages for Performance

### ISSUE THREAD

**Issue by atishaybaid** [ampproject/amphtml#13398]
Hi,

What is the best way to test amp page performance, I have tried with lighthouse and page speed insides, both don't provide satisfactory results for amp pages.
My amp pages are validated however i wish to check  ,if i can improve the page performance.
url:m.timesofindia.com/amp_business

**Comment by aghassemi** [comment]
@atishaybaid If you find any particular performance issues with AMP framework please file a bug. Overall, AMP designed in a way that you can not make you page slow and therefore there isn't much you can do to speed it up either. If there are perf issues, we would need to handle them in the framework.
