### ISSUE TITLE
Specification clarification

### ISSUE THREAD

**Issue by weeblrpress** [ampproject/amphtml#13407]
Hi

I am implementing the updated guidelines for json-ld page image information -
 696px to 1200px, min 800,00px, etc (https://developers.google.com/search/docs/data-types/article)

I find a contradiction in terms:

> Only a marked-up image that directly belongs to the article should be specified.

I understand this as "only images visible to the visitor, inside the current page". But then:

> For best results, provide multiple high-resolution images (minimum of 800,000 pixels when multiplying width and height) with the following aspect ratios: 16x9, 4x3, and 1x1.

And the example is:

```
{
  "@context": "http://schema.org",
  "@type": "NewsArticle",
  "image": [
    "https://example.com/photos/1x1/photo.jpg",
    "https://example.com/photos/4x3/photo.jpg",
    "https://example.com/photos/16x9/photo.jpg"
   ]
  }
```

Are we supposed, for "best results", to have a square, 4:3 and 16:9 versions of images to be used as page image visible on each AMP page?

Surely I'm missing something?

Rgds

Yannick

**Comment by aghassemi** [comment]
@weeblrpress For question related to AMP in Google Search, please try the [AMP category in the Webmaster Central Help Forum](https://productforums.google.com/forum/#!topicsearchin/webmasters/category$3Aaccelerated-mobile-pages-amp)

**Comment by weeblr** [comment]
Hi @aghassemi 

For the record, I discussed the matter with Dave Besbris at AMPConf in Amsterdam, and the outcome is as follow:

- the image has to be present on the page
- but it's best to offer alternate versions with different aspect ratio
- and that's sort of loosely enforced anyway

I guess that is consistent with the accuracy of the documentation :)

**Comment by aghassemi** [comment]
@weeblr thanks for sharing your findings here.
