### ISSUE TITLE
Source maps are no longer working.

### ISSUE THREAD

**Issue by ryanmcgrail95** [ampproject/amphtml#13403]
## What's the issue?

Source maps are not working in browser debuggers. On Chrome, the files appear empty, and on Firefox, 404 errors are displayed instead of code. 

## How do we reproduce the issue?

Navigate to google.com in a mobile/responsive view and locate a news story with AMP enabled. If you then visit this page and view the JavaScript sources, you should be able to find the GitHub filesystem duplicated under [story]/raw.githubusercontent.com. All of the files are listed, along with their proper names, but every file is blank.

## What browsers are affected?

I tested multiple browsers across two systems, and all were affected.

### Chrome OS:
- Chrome, Version 63.0.3239.140 (Official Build) (64-bit)

### Ubuntu:
- Chrome, Version 64.0.3282.140 (Official Build) (64-bit)
- Firefox Quantum, 58.0.1 (64-bit)

## Which AMP version is affected?

This issue started on Feb. 7, sometime in the middle of the day, and continues to occur on the current version, 1518049180919.

**Comment by jridgewell** [comment]
We forgot to publish the release (/cc @zhouyx), so the github urls were broken. It's fixed now.

**Comment by ryanmcgrail95** [comment]
Thanks!
