### ISSUE TITLE
Switch `gulp test` to use headless Chrome

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#13402]
Right now `gulp test` pops a Chrome window and runs all the tests in an epileptic flash of rapidly changing `<iframe>`s. Since the Chrome window is not headless the user risks interrupting the test accidentally. e.g., imaging you start running the test in your terminal, switch to another window and begin typing. A few seconds later a Chrome window opens, takes focus (depending on your OS,) and you just modified the results because you thought you're typing on the other window that just lost focus…

I propose we default to `--headless` Chrome, unless the user passes `--noheadless` or `--watch`. Are there any benefits to leaving the tests “headfull”?

**Comment by aghassemi** [comment]
@danielrozenberg @rsimha This is done right? Closing.
