### ISSUE TITLE
Passing along URL parameters to amp-iframe.

### ISSUE THREAD

**Issue by javiergarzac** [ampproject/amphtml#13419]
Hello. 

Found there is no way to pass along URL parameters from the AMP page (i.e. `https://www.google.com/amp/s/...?campaign=123`) down to the amp-iframe component.

Marketing team wants to sponsor an AMP page. They add parameters to the sponsored AMP page to know the visit was from a campaign. We want to show specific content in the amp-iframe if the visit was paid or organic, but currently there is no way to know that if parameters are not passed along.

**Comment by aghassemi** [comment]
This has come up a few times https://github.com/ampproject/amphtml/pull/10884 and the decision has been not to allow variable substitution on `amp-iframe`'s `src`.

@cramforce Considering this use-case and the fact that two-way messaging @choumx is working on will allow this anyway, should we reconsider?

**Comment by choumx** [comment]
IIUC, the proposed two-way communication is gesture-driven and won't have access to URL vars.

**Comment by Adventive** [comment]
@javiergarzac 
As per `amp-iframe` documentation:
```markdown
The attribute behaves mainly like on a standard iframe with one exception: the #amp=1
fragment is added to the URL to allow source documents to know that they are
embedded in the AMP context. This fragment is only added if the URL specified by src
does not already have a fragment.
```
So you can pass in those variables via the url hash and re-parse within the iframe.
``` javascript
((win, body, hash) => {
    hash = hash.split("&").map(x => x.split("=")).reduce((o, a) => {
        o[a[0]] = a[1];
        return o;
    }, {});
    let campaign = hash.campaign;
})(window, document.body, window.location.hash.substr(1));
```

**Comment by choumx** [comment]
I don't think that'll work without supporting `QUERY_PARAM` variable substitutions on `amp-iframe[src]`. 

> We want to show specific content in the amp-iframe if the visit was paid or organic

Is there a way to render this content without `amp-iframe`? E.g. `amp-list` supports URL variable substitutions and is lighter weight than an iframe.

**Comment by rudygalfi** [comment]
Closing since #10884 is tracking.

**Comment by nonacc** [comment]
variable substitutions doesn't work on amp-iframe[src]
