### ISSUE TITLE
Add `open` and `close` events to `amp-lightbox`

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#13420]
### What you will need to know
- Javascript
- HTML/DOM

### Background
[amp-lightbox](https://www.ampproject.org/docs/reference/components/amp-lightbox) is a component that displays its children in a full-viewport overlay.

`amp-lightbox` is opened and closed via `open()` and `close()` [AMP Actions](https://github.com/ampproject/amphtml/blob/master/spec/amp-actions-and-events.md#amp-lightbox)

We like to add two new events `lightboxOpen` and `lightboxClose` to the component that would fire AFTER lightbox is FULLY visible or invisible. 

### Hints
We did a very similar fix for `amp-sidebar` in [this PR](https://github.com/ampproject/amphtml/pull/12505) which can be used as reference. 

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.  (If you [join the AMP Project](https://goo.gl/forms/T65peVtfQfEoDWeD3) we'll be able to assign this issue to you after you've claimed it.)
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] [Sign the Contributor License Agreement](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#contributor-license-agreement) before creating a Pull Request.  (If you are contributing code on behalf of a corporation start this process as early as possible.)
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review).  Mention @aghassemi and `closes Issue #13420` in the description. 
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

### Questions?
If you have questions ask @aghassemi in this issue or on your Pull Request (if you've created one) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

**Comment by inidaname** [comment]
I will like to take this up

**Comment by inidaname** [comment]
@aghassemi I need your guide been trying to replicate #12505, will be glad if you can give me a little direction

**Comment by aghassemi** [comment]
@inidaname  Thanks for taking this on!

You essentially want to dispatch a `lightboxClose` event in the `finalizeClose_` method of `amp-lightbox` and a `lightboxOpen` event in the `finalizeOpen_` method.

**Comment by cathyxz** [comment]
Closed by #13578
