### ISSUE TITLE
The mandatory text (CDATA) inside tag 'noscript &gt; style[amp-boilerplate]' is missing or incorrect.

### ISSUE THREAD

**Issue by bizimunda** [ampproject/amphtml#13427]
Dear Sir,
I have no idea why I'm getting this message.
When I check my website on your validation system it validates my page but I get error message from your "search console"
The mandatory text (CDATA) inside tag 'noscript &gt; style[amp-boilerplate]' is missing or incorrect.
The mandatory text (CDATA) inside tag 'head &gt; style[amp-boilerplate]' is missing or incorrect.

Here is my url: http://hochzeitsfotografffm.de/
And if you check my url on your browser http://hochzeitsfotografffm.de/#development=1 it says AMP validation successful.

Please help me.
Thx

**Comment by choumx** [comment]
It looks like that page is no longer AMP. ☹️ I remember another developer had issues with line breaks/whitespace in the boilerplate. Try copy-pasting the boilerplate directly from the minimal AMP doc on validator.ampproject.org. 

Please reopen this issue if you're still having problems. Hope this helps!
