### ISSUE TITLE
Tests not running because expect isn't assert

### ISSUE THREAD

**Issue by jeffkaufman** [ampproject/amphtml#13422]
There are ~26 test uses of `expect(condition)` that should either be `assert(condition)` or `expect(thing).with.long.series.of.dots`.  Since `expect(false)` will not fail a test, these appear to be real tests but in fact will never fire.  Here are the ones I see:

* ads/google/a4a/test/test-utils.js
    * `expect(truncUrl.indexOf(TRUNCATION_PARAM.name) != -1)`
* extensions/amp-a4a/0.1/test/test-amp-a4a.js
    * `expect(a4a.adPromise_)`
    * `expect(a4a.adPromise_)`
* extensions/amp-a4a/0.1/test/test-real-time-config-manager.js
     * `expect(fetchJsonStub.calledWith(url))`
* extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
     * `expect(impl.win.experimentBranches[CORRELATOR_CLEAR_EXP_NAME] !== undefined)`
     * `expect(impl.win.experimentBranches[CORRELATOR_CLEAR_EXP_NAME] === undefined)`
     * `expect(impl.win.experimentBranches[CORRELATOR_CLEAR_EXP_NAME] === undefined)`
     * `expect(impl.win.experimentBranches[CORRELATOR_CLEAR_EXP_NAME] === undefined)`
     * `expect(Date.now() - startTime >= 1000)`
     * `expect(Date.now() - startTime <= 50)`
     * `expect(Date.now() - startTime <= 50)`
     * `expect(Date.now() - startTime <= 50)`
* extensions/amp-ad/0.1/test/test-concurrent-load.js
     * `expect(Date.now() - start >= 1000)`
     * `expect(Date.now() - start <= 50)`
* extensions/amp-sidebar/0.1/test/test-amp-sidebar.js
     * `expect(sidebarElement.classList.contains('i-amphtml-overlay'))`
* extensions/amp-video/0.1/test/test-amp-video.js
     * `expect(sources[0], s1)`
     * `expect(sources[1], s2)`
     * `expect(sources[0], cached)`
* test/functional/test-ads-config.js
     * `expect(keys[i] < keys[i + 1])`
* test/functional/test-custom-element.js
     * `expect(build.calledOnce)`
     * `expect(build.calledOnce)
* validator/engine/validator_test.js
     * `expect(disallowedDomain !== 'whatever.ampproject.org')`

**Comment by jeffkaufman** [comment]
I'm planning to submit a PR that switches them to proper uses of `expect`.

**Comment by jeffkaufman** [comment]
I ran into one of these on my own, found several more with primitive grepping, and then wrote a hacky script to find the rest:

```
import fileinput
state = 'start'
parens = 0
in_quotes = ''
debugging_lines = []
for line in fileinput.input():
  prev = ''
  for i, c in enumerate(line):
    if state == 'start':
      if line[i + 1 - len(' expect('):i + 1] == ' expect(':
        state = 'expect'
        parens += 1
    elif state == 'expect':
      if in_quotes:
        if c == in_quotes and prev != '\\':
          in_quotes = ''
      else:
        if c in ["'", '"']: 
          in_quotes = c
        elif c == '(':
          parens += 1
        elif c == ')':
          parens -= 1
          if not parens:
            state = 'dot'
      if c == '\n':
        debugging_lines.append(line)
    elif state == 'dot':
      if not c.strip():
        if c == '\n':
          debugging_lines.append(line)
        continue
      if c != '.':
        print('Bad expect at %s:%s:\n%s%s%s^' % (
            fileinput.filename(), fileinput.filelineno(),
            ''.join(debugging_lines), line, ' '*(i-1)))
      state = 'start'
      debugging_lines = []
    prev = c
```

It has a few false positives, in places where we have a helper function that returns `expect(foo)` with the idea that the caller will do `helper(...).stuff.in.english`.

I wonder whether this is something chai could catch by default?  When you call `expect` chai could add it to a list of active expectations, then when the expectation chain resolves chai could remove it from the list.  Any active expectations at the end of the test are an error.

**Comment by rsimha-amp** [comment]
Nice issue, @jeffkaufman!

A simple fix would be to add https://www.npmjs.com/package/eslint-plugin-chai-expect to our list of `.eslint` checks to detect the misuse of `expect`. I believe `chai-expect/missing-assertion` is the rule we want in this case.

Happy to work with you on PRs to detect / fix these errors.
