### ISSUE TITLE
Add a reset function to components that puts them back into the pre-layout state

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1343]
E.g. when a document is swiped away, we'd like to keep it around (so it is easy to get back and scroll position is maintained), but reduce memory usage and potential CPU usage as much as possible. This task is about, for selected components, reset them into a non-rendered state, so the resources they are using can be released.

We have an existing callback `documentInactiveCallback` upon which such work can be done. We currently use this primarily to turn off videos. This, however, might not even be desired if the only thing that happened was switching to a different tab. So, maybe we want to differentiate between swiping (and similar actions) VS. just moving to a different tab.
- I think we probably want to create a new lifecycle method, so that only work specific to "unmounting" is performed.
- We can migrate individual components one by one. Lets start with `amp-ad` and `amp-iframe`. We'd revert them into the state pre layoutCallback (in practice we remove the iframes) and re-show their fallbacks (if present).
- Youtube we probably want to keep (to maintain state on timeline), but stateless components like instagram or twitter can easily unmounted and only rendered again if needed.
- Then, should the document become visible again, we'd call `layoutCallback` again if appropriate.
- Since we now support some forms of resizing we should include some kind of placeholder div that keeps the existing size the same (if needed), so that if we restore the doc the number of resizings is kept to a minimum.

**Comment by jridgewell** [comment]
How about a `documentLostFocusCallback` or `documentBlurCallback` for when the tab itself has changed? This would leave the `documentInactiveCallback` for when the viewer switches to a new page.

**Comment by cramforce** [comment]
I'd rather be explicit and make it the opposite of `layoutCallback`. Maybe `unlayoutCallback` or `conserveResourceCallback`. Then the framework can decide when to call it.

@ericfs mentioned that it would be a good idea to only do this when we have some indication that the user is idle.

**Comment by jridgewell** [comment]
> Maybe `conserveResourceCallback`

I think that's the right one, I want to discourage modifying the layout sizes.

> @ericfs mentioned that it would be a good idea to only do this when we have some indication that the user is idle.

I'm not sure I like that idea. There's no reason to think that the user isn't listening to music / "lyric" video with the page in the background, or even with the device locked. It'd annoy the crap out of me to have my music stop every few seconds.

**Comment by cramforce** [comment]
I think we should separate the concepts of "tab is in background" and "AMP user is now viewing a different doc in the same viewer". The latter is like navigating away. By default on the web a video stops at that point. First thing is to be able to separate them.

**Comment by adelinamart** [comment]
Is this still being worked on?

**Comment by jridgewell** [comment]
Completed in https://github.com/ampproject/amphtml/pull/1637.
