### ISSUE TITLE
Support for Broadstreet Ads (Pull Request is In)

### ISSUE THREAD

**Issue by katzgrau** [ampproject/amphtml#13444]
Hey everyone, first of all, fantastic job with the AMP project. I know that managing a major open source project is tough, I've done it as well. Secondly, I'm sorry to open an issue for this, but I didn't really know of any other way to raise this.

I run a smaller adserver called Broadstreet, and we've had a PR (#12475) for integration for about two months, but it doesn't seem to have been noticed/picked up at all despite its simplicity.

We have a number of publishers who have requested AMP support for months. I've told them support is in the queue but I'm starting to worry because they're getting anxious, which is in turn making us anxious.

Is there a chance this can be prioritized to some degree? I'd imagine all it needs is a review. The PR is pretty much a tailored version of other simple adserver AMP integrations.

https://github.com/ampproject/amphtml/pull/12475

Thank you!

**Comment by aghassemi** [comment]
Closed by #12475
