### ISSUE TITLE
amp-bind: Links break when mutating between hash and non-hash

### ISSUE THREAD

**Issue by mdiblasio** [ampproject/amphtml#13446]
@cramforce 

## What's the issue?

Clicking on the following link on an AMP page results in a broken AMP page when viewing in the Google AMP Viewer (only) in a Safari browser (only):

`<a on="tap:AMP.setState({showErrors: true})"
   class="searchButtonLink"
   [href]="searchForm.locationsUrlSegment && searchForm.dateUrlSegment && searchForm.paxNumber ? 'https://m.cheapoair.com/remotesearchhandler.aspx?t=f&tt=2' + searchForm.paxUrl + '&class='+searchForm.cabinClassUrlSegment+'&fpAffiliate=MobileFlightHomeDeals&from=' + searchForm.FromCityCode + '&to=' + searchForm.ToCityCode + '&fromDt=' + searchForm.departDate + '&toDt=' + searchForm.returnDate: '#'"
   href="#">
  <span class="ampstart-btn caps"
        id="search">Search</span>
</a>`

![r04vatm77nh](https://user-images.githubusercontent.com/17748781/36108541-135dd6e2-0feb-11e8-866b-c4cf370e8b26.png)

This may be a bug in the cache rewrite in relation to amp-bind.

## How do we reproduce the issue?

Can no longer be produced as AMP pages have been taken down. 

## What browsers are affected?

All Safari browsers when viewing **from the Google AMP Viewer**

**Comment by choumx** [comment]
This isn't clearly spelled out in the [cache modifications spec](https://github.com/ampproject/amphtml/blob/master/spec/amp-cache-modifications.md#anchor-tags-must-have-a-target-of-_blank-or-_top), but the cache probably doesn't add `target=_top` to `<a>` tags if it's a hash-link. Since amp-bind can change a hash link to a non-hash link, it should also change the `target` (if served from CDN).

**Comment by cramforce** [comment]
I think what needs to happen is that `amp-bind` needs to add/remove the `target=_blank` when a link changes from or to `#`.

**Comment by choumx** [comment]
Yes, but if the link had `target=_top` we should preserve that, right?

**Comment by cramforce** [comment]
You may not be able to tell whether it originally had `target=_top`. Certainly if it has it and the `href` is `#`
