### ISSUE TITLE
AMP-IMAGE-LIGHTBOX activate: Unsupported element: IMG​​​

### ISSUE THREAD

**Issue by seomaz** [ampproject/amphtml#13443]
The amp-img-lightbox it stopped working, when you click the element, this log appear: "AMP-IMAGE-LIGHTBOX activate: Unsupported element: IMG​​​"

You can test here: https://www.cibercuba.com/noticias/2018-02-11-u73624-e73624-s27065-habla-director-vivir-cuento-estos-son-problemas-podrian

I see the error in ampbyexample.com too: https://ampbyexample.com/components/amp-image-lightbox/

click the first image

AMP version: 1518203063064

Browser Chrome Versión 63.0.3239.132 (Build oficial) (64 bits) (MAC OSX)

**Comment by seomaz** [comment]
its ok now!

**Comment by cathyxz** [comment]
Hi @seomaz thank you for reporting this bug! It was patched by https://github.com/ampproject/amphtml/pull/13440.
