### ISSUE TITLE
Polymer2.0 conflict Firefox - CustomElementRegistry

### ISSUE THREAD

**Issue by serchserch** [ampproject/amphtml#13450]
AMP causes error when Polymer webcomponents-hi-sd-ce.js tries to overwrite `CustomElementRegistry`

```html
<script async src="https://cdn.ampproject.org/v0.js"></script>
.
.
.
<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
```

https://github.com/ByPrice/shop/blame/master/index.html#L28

![image](https://user-images.githubusercontent.com/2801648/36120322-707e40f6-1008-11e8-9f24-9b06f7f885f8.png)

`Tested using Firefox Quantum 58.0.1 (64-bits) for macOS High Sierra 10.13.3`

[Live test](http://kernel.company/) (is a fork of [shop example](https://github.com/Polymer/shop) but with the amp library)

**Comment by cvializ** [comment]
Hello @serchserch! What are you trying to accomplish? `v0.js` must only be included in valid AMP documents, and this document violates the AMP validation requirements by including external scripts and is missing the ⚡️attribute on the HTML tag. Are you trying to use AMP in a PWA?

**Comment by cvializ** [comment]
I'm going to close this since it does not look like the document provided is an AMP document, and AMP documents do not allow external libraries. If you are trying to use a PWA shell, you will need to use AMP shadow. If I am mistaken, feel free to comment and we can reopen!
