### ISSUE TITLE
Pass dynamic DFP Key-Values in amp-ad tag

### ISSUE THREAD

**Issue by rquilliet** [ampproject/amphtml#13451]
Hi,
The idea would be to attach key-values dynamically generated by a Javascript code located in the header of the page.
Let's say we define a JS function called generateDynamicValue() in the header of a page.
Then I would like to be able to pass the result of this function in the targeting part of the amp-ad tag:

<amp-ad
      height="250"
      width="300"
      data-slot="/121212121/mytest/dynakv"
      json='{"targeting":{"mykey":generateDynamicValue()}}'>
</amp-ad>

Is that already possible? If not, is there an existing feature request?
Thanks for your help!
Remi

**Comment by lannka** [comment]
@rquilliet AMP does not allow custom javascript code in header of the page. Can you give a concrete example what dynamic value do you want to pass along with the amp-ad tag?

/cc @jasti

**Comment by jasti** [comment]
One way to do this is by adding your own RTC endpoint: https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/rtc-documentation.md

**Comment by rquilliet** [comment]
Thanks @jasti and @lannka 

@lannka : the idea would be to pass a random value as a key-value targeting in the amp-ad tag. One potential (and useful) use case would be to split traffic based on that value and perform AB tests.

@jasti - I've looked at your documentation - not sure I get it completely.
Would that mean that I should first define my JS function in the file where the getCustomRealTimeConfigMacros() function is located?

/** @override */
getCustomRealTimeConfigMacros() {
  return {
    'MYMACRO': generateDynamicValue()
  }
}

Thanks for your help @jasti 

Remi

**Comment by jasti** [comment]
@bradfrizzell do we have publisher integration examples for RTC?

**Comment by bradfrizzell** [comment]
@jasti This is the [Publisher Implementation Guide](https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/rtc-publisher-implementation-guide.md)

@rquilliet  I don't believe there should be any need to run experiments this way. If you need to run an experiment within DFP, you can already do this directly in DFP https://support.google.com/dfp_premium/answer/6333031?hl=en

If this does not work for you, can you explain a little more why you need to do this from the clientside?

**Comment by rquilliet** [comment]
@bradfrizzell thks for the links
basically I want to be able to run custom experiments (like with lots of setups running at the same time), applying very different floors or deal prices or any other change)
do you think there would be any other way of doing it client-side?
thks again

**Comment by rquilliet** [comment]
Flow would be the following:
1/ at page load, a JS function placed in the header would run
2/ and the result of this function would be added as a key-value in the ad
call sent to DFP

Does this make sense?

Remi

2018-05-15 16:57 GMT+02:00 bradfrizzell <notifications@github.com>:

**Comment by rquilliet** [comment]
@bradfrizzell @lannka 
Hi all,
Just wanted to check if the workflow described above made sense for you guys? 
If so, do you see a way to use AMP tags to implement it?
Thanks for your help,
Remi

**Comment by philooo2** [comment]
+1 on this

being able to target AMP pages from admanage/dfp is a must have function for us.

without it I don't see how we can control ads on our AMP pages ?

**Comment by jasti** [comment]
@rquilliet could you explain why RTC is not a good fit for you?
https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/rtc-publisher-implementation-guide.md

**Comment by everlovingvijay** [comment]
Is there a way to pass PHP echo function in the AMP targeting parameter. Idea to pass key value of URL, POST ID and Category from the wordpress AMP page:

Sample code:

<amp-ad width=300 height=250
    type="doubleclick"
    data-slot="/21687966607/KontroKultura_AMP2_NOGADS"
    data-multi-size-validation="false"
    rtc-config='{
      "vendors": {
           "criteo": {"NETWORK_ID": "8317", "LINE_ITEM_RANGES": "0..20:0.01"}
       },
      "timeoutMillis": 2000}'
    json='{"targeting":{"URL": ["**<?php echo $_SERVER['REQUEST_URI']; ?>**"], "POSTID": ["<?php the_ID(); ?>"], "CATEGORY": ["<?php foreach((get_the_category())as$category){echo $category->cat_name.''; } ?>"]}}'>
</amp-ad>

**Comment by PsychodelEKS** [comment]
Same here, for stat reports purposes we want to distinguish "first" and "refresh" requests on the ad manager slot. It would be great, if some sort of placeholder processing was added to json.targeting and one could use %refreshCount% (counter value) or %isRefreshRequest% (0/1 value) to pass the data to ad manager through key-value mechanism.
```amp-ad-network-doubleclick-impl.js``` already has that private property ```refreshCount_``` which can be used for that.

**Comment by sankalpsans** [comment]
Refreshed ad is a very legitimate use case for this.
