### ISSUE TITLE
Testing multiple conditions using amp-bind-macro fails for some unknown reason.

### ISSUE THREAD

**Issue by nickrenfo2** [ampproject/amphtml#13452]
## What's the issue?

When I test individually against a couple filters I set up through amp-bind-macro, they work fine. However, when I test against them both at the same time, an error "unsupported function" appears, and the page breaks.

## How do we reproduce the issue?

Check out [this codepen](https://codepen.io/nickrenfo2/pen/wyeqWX#development=1) for a live example. Alternatively, the code from the HTML section of that codepen can be placed on the [amp-by-example playground](https://ampbyexample.com/playground/#development=1) and the same results can be seen.

The error I'm speaking of is the following: 

`amp-bind: Expression evaluation error in "'status' + (offerPassesFilters(10) ? '' : ' bad')". offerPassesFilters is not a supported function`

The error should appear in the console immediately, but if it does not, move slider just above the green box (red box if the error is thrown).

## What browsers are affected?

All browsers

## Which AMP version is affected?

AMP ⚡ HTML – Version 1518441587106

**Comment by choumx** [comment]
Thanks for creating that codepen. Not obvious to me at first glance what's wrong -- will investigate.

**Comment by choumx** [comment]
Ah, the problem is `offerPassesFilter` is silently ignored since it exceeds the maximum expression size. The errors should be forwarded to the user -- I'll fix that. 

Note that the expression size calculation includes the size of referenced macros.
