### ISSUE TITLE
amp-story : swiping down should close the story

### ISSUE THREAD

**Issue by wassgha** [ampproject/amphtml#13470]
## What's the issue?

[Feature Request] I believe it is more natural to close the story when the user swipes down on it (currently refreshes the page instead)

Needs UX Review @spacedino

**Comment by newmuis** [comment]
Thanks for the report @wassgha!  Is this when coming from Google search?  What would you expect this to do on origin?  We can always use `history.back()`, but that may have unintended consequences.

Also /cc @hongwei1990 since we've had this discussion before :smile:

**Comment by wassgha** [comment]
I don't think this should be implemented on `amp-story` but rather on the google search amp viewer (assuming we can capture gestures on the whole screen through the viewer, which might be the case). I am not sure how stories are currently viewed on google search but ideally, users would be able to drag down the whole viewer to go back to the search page (similar to the UX we currently have for switching between multiple amp pages to the left/right in the viewer so the gestures problem might already be solved).

**Comment by QES** [comment]
I showed an amp-story to a colleague who thought the lack of any swipe interactions odd.  Why no left / right swipe to next previous.  

I assume there is a reason for this but curious because it doesn’t seem intuitive.

However for close I would have thought a push (swipe) up the screen would be a better close gesture.

**Comment by jshmllr** [comment]
@QES "Why no left / right swipe to next previous." —> because you have to deal with the swipe back/forward gestures of mobile Safari.

**Comment by QES** [comment]
@jshmllr don't disagree but this is what people asked also if you look at Google's AMP Cache it does a left and right swipe between stories.

**Comment by jwold** [comment]
Wanted to drop in my feedback from having used the stories for the past few months. On iOS the left/right tapping feel natural enough, you get used to it pretty quickly without feeling a need to swipe. 

The back button at the bottom of Safari works as expected, taking you back to your search results. 

As far as the swipe down action, when I tried it I didn't feel like it was expected for any interaction. It's not one I'm used to using (on iOS at least) for trying to close out something. Maybe this is more of an Android situation?

**Comment by newmuis** [comment]
Since every viewer will need to implement this independently, tracking this bug here might not make sense.  I have communicated this to folks at Google, who can track the implementation of this for each Google property independently.
