### ISSUE TITLE
srcset for amp-video / workaround?

### ISSUE THREAD

**Issue by martinmakesitwork** [ampproject/amphtml#13485]
Hi guys.

I have two different animation videos for a site. 
The first one has a vertical format (espacially for mobile devices in portrait), the second a horizontal format.  Which one should be displayed depends on the width of the screen. With amp-img i can use srcset´s to realize this. But how can i solve it with video?

Best regards

**Comment by aghassemi** [comment]
I suggest having two different amp-video tags and using "media" attribute on them to select the right one for the right screen size.

**Comment by ewagstaff** [comment]
When I try this method, the video does get the "hidden-by-media-query" class, but it's set to autoplay (per AMP Story spec) and it plays despite being hidden. This leads to a kind of stadium effect where the audio of both videos plays slightly offset.

Ideally, hidden video would be prevented from playing altogether.
