### ISSUE TITLE
Animated GIFs included via `<amp-img>` and `<amp-anim>` should be reencoded as videos as an AMP Cache optimization 

### ISSUE THREAD

**Issue by tomayac** [ampproject/amphtml#13492]
Animated GIFs can get [huge](https://twitter.com/henrihelvetica/status/963649435254259713). It would be great if the AMP Cache reencoded huge (*ToDo: determine the threshold*) animated GIFs included via `<amp-img>` and `<amp-anim>` into videos. Safari Technology preview now also accepts video as the source of an image, which might help ([background article](https://calendar.perfplanet.com/2017/animated-gif-without-the-gif/)).

Related Issue: https://github.com/ampproject/amphtml/issues/30

Update: replaced "modern browsers" with "Safari Technology Preview".

**Comment by RReverser** [comment]
@tomayac "Modern browsers" might be a bit overstatement - it's implemented only in Safari and not even sure if it got out of Technology Preview branch.

**Comment by simevidas** [comment]
@RReverser It did not. Expected in Safari 11.1 sometime next month. 

Fwiw, `<video src="gif.mp4" muted autoplay loop playsinline></video>` is a pretty good replacement for animated GIFs.

**Comment by tomayac** [comment]
**Note:** not saying this should be implemented as `img[src$=".mp4"]`, just saying it might be _one_ option, apart from the `video` rewrite from @simevidas's [comment](https://github.com/ampproject/amphtml/issues/13492#issuecomment-365822727) above.

Chrome folks are tracking "video in images" as https://crbug.com/791658. General developer feedback on the idea seems positive ([Twitter search](https://twitter.com/search?f=tweets&vertical=default&q=img%20src%20mp4%20safari&src=typd), @brucelawson's [blog post](http://www.brucelawson.co.uk/2018/video-as-the-new-gif-in-safari/)).

**Comment by aghassemi** [comment]
One issue to keep in mind is that iOS has hardware limit (anywhere between 4-16) on number of videos it can autoplay (this is due to decoding on hardware) So a GIF heavy page can quickly run into autoplay not working. There are workarounds for this but we don't have them in AMP yet (we do have them in AMP Story through complicated use of a MediaPool)

**Comment by Gregable** [comment]
Closing bug as this is an AMP Cache specific. That project is tracking at `b/113542531`
