### ISSUE TITLE
Horizontal swipe gesture for amp-story

### ISSUE THREAD

**Issue by markfinst** [ampproject/amphtml#13490]
Currently, when horizontally swiping AMP Story the "hint" overlay is shown suggesting to use tap instead. ( https://github.com/ampproject/amphtml/blob/d8df163c1598ba2cfe76a5d833ad0a294febf73a/extensions/amp-story/0.1/amp-story-hint.css ).

Can you please elaborate what is the reason of disabling swipe feature? Or it's planned for future release?

Thank you.

**Comment by QES** [comment]
Totally agree the first thing colleagues commented on when I made a test story

https://amp.sportsmole.co.uk/stories/

**Comment by choumx** [comment]
I believe we found that tapping is more intuitive in user testing (and avoids conflation with OS-level gestures). /cc @hongwei1990
