### ISSUE TITLE
Question: how to deal with amp cdn blocking ?

### ISSUE THREAD

**Issue by ahmadmarafa** [ampproject/amphtml#13507]
First , im really sorry for posting a question .

my country blocked amp cdn . 
so how i can deal with this ? 
is there any way to check if amp js is loaded or not ?

**Comment by aghassemi** [comment]
If JS does not load, your page will get displayed after a 5second time out.

Unfortunately I don't thing there is a good answer to your question. If CDN is blocked, you would need to host the JS yourself which of course makes tour AMP pages invalid but you can always use AMP as simply a framework.
