### ISSUE TITLE
amp-story bookend

### ISSUE THREAD

**Issue by QES** [ampproject/amphtml#13505]
The example in the docs at https://www.ampproject.org/docs/reference/components/amp-story#bookend-json-endpoint show a bookend with wrapping share icons (#13455) but also in the "More to Read" there is reference to time and URL which don't seem to appear in the JSON description as options.

```
{
  "share-providers": {
    "email": true,
    "twitter": true,
    "tumblr": true,
    "facebook": {
      // Facebook requires an `app_id` param
      "app_id": "MY_FACEBOOK_APP_ID"
    }
  },
  "related-articles": {
    "More to Read": [
      {
        "title": "My friends, this is India [...]",
        "url": "http://a-publisher.com/india",
        "image": "./media/b1.jpg"
      },
      {
        "title": "A wonderful weekend with Tenturi",
        "url": "http://a-publisher.com/tenturi",
        "image": "./media/b2.jpg"
      },
      ...
    ]
  }
}
```

Are there other features and options in the bookend.json that aren't yet described in the documentation?

My example is at https://amp.sportsmole.co.uk/stories/

![image](https://user-images.githubusercontent.com/249748/36260401-430e0946-1259-11e8-893a-3ca55d7a94bb.png)

There doesn't seem to be a way to change amp.sportsmole.co.uk to sportsmole.co.uk in the description or add a time of publication in the available options?

**Comment by ithinkihaveacat** [comment]
That's correct, time/date for the "more to read" section in the bookend is not supported; the only fields supported right now are [title, URL and image](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/0.1/bookend.js#L91-L110). I guess datetime it was in a prototype!

**Comment by QES** [comment]
Thanks - that is how I read it but saw an example that showed something else.

**Comment by ithinkihaveacat** [comment]
No problem, that's understandable! If you're interested in that feature you can create a feature request in this repo. (Or even implement.)
