### ISSUE TITLE
Support noarchive meta tag to discourage third parties hosting / caching AMP content.

### ISSUE THREAD

**Issue by omarreiss** [ampproject/amphtml#13508]
## What's the issue?

Briefly describe the bug/feature request.

One of the main concerns people seem to have with AMP is that AMP Pages can be cached and hosted by third parties, most famous example being Google [AMP Cache](https://developers.google.com/amp/cache/). This is a matter of ownership of content. There should be a way to prohibit or discourage third parties from hosting my content. This is nothing new. We have `noindex`, `nofollow` etc. in part for exactly these kinds of reasons.

How about we just introduce a new metatag:

`<meta name=robots content='nohost'>`
or
`<meta name=robots content='nocache'>`

If search engines / social platforms would simply respect this tag, I think we'd be in a much better place! I realize this might not be AMP specific. But since this problem seems to surface hard with regard to AMP, I figured I'd just open an issue here so we can get a discussion started.

## Which AMP version is affected?

As far as I can see, this is new.

**Comment by omarreiss** [comment]
I realize there is actually already `noarchive` for this purpose exactly. Is this supported for AMP? http://noarchive.net/meta/

**Comment by aghassemi** [comment]
@omarreiss If you like to use AMP simply as a JS framework and not get into AMP cache, you can simply omit the :zap: in `<html>` to make your page invalid AMP.

**Comment by aghassemi** [comment]
Closing the issue, please feel free to reopen if previous answer is not satisfactory.

**Comment by jdevalk** [comment]
So the way to exclude yourself from caching is by not using the standard? That feels _very_ odd to me.

**Comment by cramforce** [comment]
The ⚡️does nothing else, but opt-into participation in the AMP ecosystem. Leaving it out is the way to go to avoid caching, embedding, etc.

**Comment by jdevalk** [comment]
The fact that you can't opt out of caching without opting out of other features is what we're questioning here...

**Comment by cramforce** [comment]
@jdevalk The other features this opts out of rely on caching (mostly for privacy reasons).

What features of AMP are you specifically referring to?

**Comment by jdevalk** [comment]
Search highlights and everything related to that. I don't see how privacy is affected by this.

**Comment by cramforce** [comment]
@jdevalk Google Search's AMP implementation relies on privacy-preserving pre-rendering (both for performance and swiping in carousels) that allows rendering a page without the publisher of the page knowing that it happens until the user actually goes to the page. This is ensured by only serving content from the cache until the moment the user goes to the page.
