### ISSUE TITLE
Documentation for layout="fill" should mention position: relative

### ISSUE THREAD

**Issue by sryze** [ampproject/amphtml#13506]
The documentation for `layout="fill"` doesn't say a lot and can make someone think that just using that attribute alone will make the element fill its parent, whereas in reality it fills the element with `position: realtive`. I think that this should be mentioned in the docs.

**Comment by aghassemi** [comment]
Correct, parent must be `relative` or `absolute`
/to @bpaduch

**Comment by bpaduch** [comment]
will look @ in: Q1/Q2
