### ISSUE TITLE
Fatal error: Can't use function return value in write context in

### ISSUE THREAD

**Issue by ComputerGirl** [ampproject/amphtml#13514]
After just updated your plugin got this error:

Fatal error: Can't use function return value in write context in /..../wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 4709

Could not access anything had to manually delete plugin through C-panel.

**Comment by aghassemi** [comment]
@ComputerGirl Could you please file your issue on https://github.com/Automattic/amp-wp since it is Wordpress related? Unfortunately folks on this GitHub project are not familiar enough to help with Wordpress plugin issues.

Thanks!
