### ISSUE TITLE
Change background color of fixed div onscroll

### ISSUE THREAD

**Issue by martinmakesitwork** [ampproject/amphtml#13519]
Hi guys!

We have a fixed header on our site that has a transparent background.
When i scroll down 100vh it should get a white background. 
How can i achieve this? Is there a possibilty with amp or an only css solution?

Thank you a lot for answers!

**Comment by martinmakesitwork** [comment]
The solution could be something like that - but is it possible to change the background color as well?

https://codepen.io/aghassemi/pen/GOEWEz

**Comment by cathyxz** [comment]
I think `background-color` isn't one of the currently supported CSS properties. Per [amp-animation doc](https://github.com/ampproject/amphtml/blob/aee8968eb4592e2e0ac506a928acc8781daa89b8/extensions/amp-animation/amp-animation.md). 

The currently supported properties to animate are: 
- opacity
- transform
- visibility
- 'offsetDistance'

Maybe you could have a div that's purely the background color and toggle its opacity?

**Comment by martinmakesitwork** [comment]
yeah i´ve done it like that. Thank You!
