### ISSUE TITLE
Add amp-analytics config from an extension? / I2I for new vendor

### ISSUE THREAD

**Issue by kushal** [ampproject/amphtml#13526]
We have an extension (amp-access-scroll) that has corresponding analytics endpoints that should be added if and only if the extension is present. It'd be great if this could just be configured from our extension, is that something you've thought about?

If not, we'd still love to go ahead and send a vendors PR to make integration easier for our partners. We have the following configuration
```
"requests": {
   "scroll": "https://connect.scroll.com/amp/analytics?rid=ACCESS_READER_ID&cid=CLIENT_ID(cid-fallback-cookie)&o=SOURCE_URL&c=CANONICAL_URL&d=AUTHDATA(scroll.scroll)&v=AUTHDATA(scroll.visitId)&s=${totalEngagedTime}"
},
 "triggers": {
   "trackInterval": {
     "on": "timer",
     "timerSpec": {
        "interval": 15,
        "maxTimerLength": 7200
      },
     "request": "scroll"
   }
 }
```

**Comment by dvoytenko** [comment]
/to @zhouyx could you pls advise on how to auto-register analytics for amp-access-scroll extension? Notice that "scroll" refers to brand name, not scrolling.

**Comment by zhouyx** [comment]
@kushal We allow an extension to use `<amp-analytics>` to collect data. Please take a look at our doc https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-components-analytics.md and let me know. Thanks!

**Comment by kushal** [comment]
This looks promising! Just so I understand, I would add `trackInterval` to the `useAnalyticsInSandbox` whitelist, and then use that method? And `useAnalyticsInSandbox` would report document-wide events and have access to `ACCESS_READER_ID`, `SOURCE_URL`, etc?

**Comment by zhouyx** [comment]
@kushal I just realized that you want to collect `timer` event. Right now we only support `visible` and `hidden` event for analytics in extension. But I don't why the reason to not support `timer`. Before that could you please [submit a feature request](https://github.com/ampproject/amphtml/issues/new) first. 

After that, you can use the `useAnalyticsInSandbox(this.element, configPromise);` API. With a static config, what you can do is to pass in a resolved promise with the config you have. 

Please note that not all vars can be accessible. We have a whitelist [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/sandbox-vars-whitelist.js) for supported vars. 

Let me know if you have any question. Thanks.

**Comment by zhouyx** [comment]
@kushal 
`totalEnagedTime` seems to contain user information. We will need a privacy review in order to add it to the whitelist. 
To your second question. I think an `<amp-access>` will still be used right? Could you provide me an example on how your extension will be used? Thanks

**Comment by kushal** [comment]
@zhouyx 
- Got it. What's the process for that privacy review? Is that a feature request? Pull request? Can I do that at the same time as adding the `timer` event?
- Yes, <amp-access> is used, but it's not really "ours." Is the idea that the element passed into `useAnalyticsInSandbox` is just a hook for detecting when it loads?  https://github.com/ampproject/amphtml/blob/master/examples/scroll.amp.html shows an example.

**Comment by zhouyx** [comment]
@rudygalfi for the privacy review.

**Comment by kushal** [comment]
Thanks! We'd also be interested in `scrollTop` and `scrollHeight` which I think will also require review?

**Comment by kushal** [comment]
Also, I tried using `useAnalyticsInSandbox` with the amp-access element, but it seems to fail on signals() being not defined, since it's just a script tag. Just to be clear, I want analytics on _the entire document_, I just want to enable them wherever my access extension is used (and my extension has no real corresponding element). @zhouyx

**Comment by kushal** [comment]
ping! we're also fine just adding this as an analytics vendor if that's the path of least resistance.

**Comment by rudygalfi** [comment]
Could you provide more detail on how `totalEngagedTime` contains user info?

**Comment by zhouyx** [comment]
Hi @kushal 
The amp-access case is a very special use case, given that you will be collecting analytics data from the parent document, not just within certain extension element. 
In general, we think it's a valid use case for you to collect data with few prerequisites. 

- Publisher should be able to enable/disable data collecting of your extension
- Publisher should be able to block analytics by user consent
- All collected data should be clearly documented

**Comment by kushal** [comment]
Thanks @zhouyx !
- Although our extension is tied to a contractual relationship which makes the analytics mandatory, we can add a disable ability just in case.
- At a technical level, what we would we do for the user consent piece?
- Also at a technical level, what element should we use when calling `useAnalyticsInSandbox`?
- Would the documentation to update be README.md?

As I said, we're really fine just adding a vendor instead if doing it this way is too much out of the norm.

**Comment by zhouyx** [comment]
@kushal 
> Although our extension is tied to a contractual relationship which makes the analytics mandatory, we can add a disable ability just in case.

Yes, I can see an opt-out is the correct way to go. 

> At a technical level, what we would we do for the user consent piece?

You need to take some config from json and include the value when creating `<amp-analytics>`. something like. @dvoytenko for amp-access config clarification. 
```
"scroll":  {
  "analytics": true/false //true by default
  "consentId": "abc...."
}
```

> Also at a technical level, what element should we use when calling useAnalyticsInSandbox?

As mentioned, `<amp-access>` case is very specially and sandbox analytics may not apply. You can simply create your own method by creating an `<amp-analytics>` component and append to parent document.

> Would the documentation to update be README.md?

Yes

> As I said, we're really fine just adding a vendor instead if doing it this way is too much out of the norm.

NO, I think this sounds reasonable. However I want to point out two things before  you go ahead and implement this. 

- It's possible that a publisher never includes analytics script to their page. There could be a delay on fetching the analytics script. 
- By inserting `<amp-analytics>` component yourself, it is not possible for a publisher to override your config. For example adding an extra param to the request is not possible. A single id can be supported via your `<amp-access>` config. Would this be a problem?

**Comment by kushal** [comment]
@zhouyx 

Great, this mostly sounds fine!
- Can you clarify what you mean by "a single id can be supported"?
- Could we just get the `data-consent-notification-id` from the existing amp-analytics element, if any, somehow?
- It sounds like your proposal would be to do something like `insertAnalyticsElement` but with sandbox false and appended to....head?

Overall, you make a good point about the lack of flexibility around extra params, etc. In theory we could support the same via amp-access config, but it will be clunkier, and I will think more before we commit.

Thank you so much for working through this with us!

**Comment by zhouyx** [comment]
Hi @kushal 

> Can you clarify what you mean by "a single id can be supported"?

I think we share the same thought here. In theory you can support as many vars (note: not extra params) via amp-access config. But it might be clunky. A single `id` sounds reasonable to add to amp-access config, for example the `visitId` in your example`v=AUTHDATA(scroll.visitId)`, but maybe not 20 of them : )

> Could we just get the data-consent-notification-id from the existing amp-analytics element, if any, somehow?

No. It is possible that different amp-analytics elements are bind to different consent notification id. And a heads up: we will be supporting a new consent collection flow that may require an attribute different that `data-consent-notification-id`. For your case, the best way to do is to ask publisher for notification id. 

> It sounds like your proposal would be to do something like `insertAnalyticsElement` but with sandbox false and appended to....head?

Exactly! Will append to document body. 

Cool! Please let us know what do you think and what's the decision here. Thanks.

**Comment by kushal** [comment]
Hi @zhouyx 

I think at this point we're leaning towards just doing this as a vendor, but wanted to double check two things.
- We are only planning to add our analytics for users who are logged into our site and we have a relationship with. Does that get us out of needing to support consent?
- It seems like in theory extra params could be passed in through amp-access config if we went that route, just curious why that wouldn't work.

Thanks!

**Comment by kushal** [comment]
I went ahead and sketched a commit for each approach which will hopefully also help highlight issues with either 

https://github.com/kushal/amphtml/commit/1390208fead55cc452a0514b22eeef3e6a08517d

https://github.com/kushal/amphtml/commit/4afa185513451f65a1d2c2bf7a69a7bbec0bf0b5

**Comment by kushal** [comment]
Hi @zhouyx 

Just wanted to make sure this is on your radar. My preference is to go with the automatic apporach, assuming you think it looks generally okay and is unlikely to break in the future. Otherwise we are fine with the vendor approach.

Thanks!

**Comment by kushal** [comment]
cc @rudygalfi, too

**Comment by zhouyx** [comment]
@kushal Apology for the late response! 

I've looked at both of your PR. 

1. Given that you are not adding extra params to your example, will you be expecting extra params with requests?

2. As you mentioned in one of the PR, are you planning to only send that after user log in? I am not very familiar with how log in works with `<amp-access>` @dvoytenko? I am worrying that the vendor approach may not be able to satisfy your need here. 
@kushal Please confirm with your desired behaviors. 

Thanks.

**Comment by zhouyx** [comment]
@dvoytenko when will the amp access authorization finish? See [comment](https://github.com/kushal/amphtml/commit/4afa185513451f65a1d2c2bf7a69a7bbec0bf0b5#r28659354)

**Comment by kushal** [comment]
@zhouyx I understand you're slammed, thank you for picking this back up!

1. We are not currently adding extra params, but we're worried about boxing ourselves in if we need them later. However, it seems like we can just pass through from amp-access config?

2. Yes, this is only for logged in users. In the vendor approach, this is done via this line https://github.com/ampproject/amphtml/pull/14471/files#diff-43075fef96144a4f898edb8d18aae69aR2052

We're still open to either approach, although we'd need to put together a formal PR if we go the automatic route.

**Comment by zhouyx** [comment]
> Yes, this is only for logged in users. In the vendor approach, this is done via this line https://github.com/ampproject/amphtml/pull/14471/files#diff-43075fef96144a4f898edb8d18aae69aR2052

The behavior is different,  because the start point for `maxTimerLength ` is different in two cases. For vendor approach: the order is  page load > analytics layout > start timer.
For inserting analytics element approach, the start point is user log in > inserting analytics > analytics layout > start timer

**Comment by kushal** [comment]
Ah, interesting! I don't think we feel strongly about the difference, though.

**Comment by kushal** [comment]
@zhouyx I went ahead and opened #14760 in addition to #14471 and we can merge either. If you have the time to review it, our preference remains for the automatic approach in #14760 unless I misunderstand the extraParams issue, or if there is some other risk of regression or privacy challenge. Thanks!
