### ISSUE TITLE
amp-twitter widget doesn't support Moments

### ISSUE THREAD

**Issue by Dreen** [ampproject/amphtml#13521]
## What's the issue?

Twitter Moments are collections of tweets with some extra data on top of them. A moment has a tweet ID, just like a normal tweet, so they should be pulled by `<amp-twitter>` widget.

## How do we reproduce the issue?

The basic code for the widget renders empty space and then some links from tweets in the moment.

```
<script async custom-element="amp-twitter" src="https://cdn.ampproject.org/v0/amp-twitter-0.1.js"></script>

...

<amp-twitter width=486 height=657
layout="responsive"
data-tweetid="964127561461780480">
<a class="twitter-moment" href="https://twitter.com/i/moments/964127561461780480?ref_src=twsrc%5Etfw">McDonald's slims down the Happy Meal menu by removing cheeseburgers</a>
</amp-twitter>
```

A fallback is displayed when provided, indicating some sort of internal error happens, though I am not aware how to see it.

## What browsers are affected?

All

## Which AMP version is affected?

All

**Comment by nainar** [comment]
This would be a great good first issue!

@Dreen would you like to work on it? Below are some notes that should help you get started!

### What you will need to know
Twitter has a [JavaScript API ](https://dev.twitter.com/web/embedded-moments/javascript-create
) that allows you to create moments as well. Files you will need to modify are either files in `extensions/amp-twitter/` or `3p/twitter.js`

### The bug
Currently you need a `data-tweetID` to create a Tweet. However, now you can have either a `data-tweetID` or a `data-momentID` as mandatory attributes. 

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.  (If you [join the AMP Project](https://goo.gl/forms/T65peVtfQfEoDWeD3) we'll be able to assign this issue to you after you've claimed it.)
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] [Sign the Contributor License Agreement](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#contributor-license-agreement) before creating a Pull Request.  (If you are contributing code on behalf of a corporation start this process as early as possible.)
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).

- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review).  Mention `closes Issue <this issue number>` in the description.
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).
Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

### Questions?
Please feel free to reach out to me!
