### ISSUE TITLE
amp-bind white-listed functions not working on IE

### ISSUE THREAD

**Issue by rangarajanr** [ampproject/amphtml#13528]
## What's the issue?
[white-listed functions](https://www.ampproject.org/docs/reference/components/amp-bind#white-listed-functions) of amp-bind do not work on IE (in this example, it was the function - String split)

## How do we reproduce the issue?

1. Open this in Internet Explorer (ex: IE 11) - https://codepen.io/anon/pen/VQrOOy
2. Change the selection to Option 2
3. See the console error in dev tools (screenshot attached)

## What browsers are affected?
IE

![iebug](https://user-images.githubusercontent.com/35853184/36328297-99b60fa6-132f-11e8-9509-2e412b1671aa.png)

**Comment by choumx** [comment]
Thanks for reporting this. Looks like function names are problematic for IE11: http://www.ecma-international.org/ecma-262/6.0/#sec-setfunctionname
