### ISSUE TITLE
Document what AMP prerendering means

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1353]
What the properties and guarantees are.

This would be helpful to have in many discussions and a good doc for new AMP developers (people working on AMP, not with AMP).

**Comment by erwinmombay** [comment]
+1

**Comment by rudygalfi** [comment]
cc @jmadler

**Comment by flaviori** [comment]
Just checking, was there any progress on this that hasn't been documented here yet?

**Comment by bpaduch** [comment]
@cramforce - Can you elaborate?  Is this more than the general info at [loads pages in an instant](https://www.ampproject.org/learn/how-amp-works#load-pages-in-an-instant)? If there are specific properties and guarantees, where can I find those details?

**Comment by cramforce** [comment]
I think that is basically it, but it would be good to iterate on it a bit. Maybe @pbakaus has a text somewhere that is a bit more coherent than my mumbling.

**Comment by pbakaus** [comment]
I sadly don't have a better write up, but maybe makes sense to steal some stuff from https://amphtml.wordpress.com/2017/01/13/why-amp-caches-exist/ as well.

**Comment by flaviori** [comment]
In addition to speed/CPU/data benefits mentioned in [Load pages in an instant](https://www.ampproject.org/learn/how-amp-works#load-pages-in-an-instant), it would also be good to mention how AMP correctly handles privacy related mechanisms in prerendering mode e.g., no tracking/analytics/no ads etc.

**Comment by adelinamart** [comment]
Any updates here?Thanks

**Comment by bpaduch** [comment]
will look @ in: Q2
