### ISSUE TITLE
Firefox bug: Audio disabled for AMP-JWPLAYER video

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#13537]
Carrying over issues filed by QA from AMP by Example repo:

Description: Audio disabled for second video_AMP-JWPLAYER

Steps to Reproduce:

Launch Firefox
Go to https://ampbyexample.com/
Tap on 'AMP-JWPLAYER' under Components
Tap on second video
Observed Result: Audio disabled for second video.
Expected Result: Audio should be audible as expected.

Environment:
Device: Samsung SM-G900H
Version: 5.0
Browser: Firefox
Version: 57.0.4

Related: https://github.com/ampproject/amp-by-example/issues/1050#issuecomment-365899444

/cc @aghassemi

**Comment by aghassemi** [comment]
@ericlindley-g Not much we can do here. It is most likely an issue with that video using an audio track format not supported by FF. Regardless, it is a JWPlayer issue. The component is just an iframe. /to @pablos1

**Comment by aghassemi** [comment]
Closing since we can not fix it ourselves. @pablos1 could you please follow up with jwplayer team?
