### ISSUE TITLE
Adsense matched content unit parameters on <amp-ad>

### ISSUE THREAD

**Issue by seomaz** [ampproject/amphtml#13541]
The adsense matched content unit need these parameteres to be customize
    ` data-matched-content-ui-type`
   `  data-matched-content-rows-num`
     `data-matched-content-columns-num`
Adsense `<amp-ad>` does not allow these parameters.

thanks!

**Comment by davisshaver** [comment]
@seomaz Can you provide some more information on this ticket? I don't believe the plugin implements `amp-ad` directly so this could be done through customizing template files.

**Comment by jasti** [comment]
@tlong2 @keithwrightbos is this something the tagging team looking into?

**Comment by lannka** [comment]
@keithwrightbos @tlong2 a kind ping
