### ISSUE TITLE
Issue regarding "<varaible> is not defined; returning null" warning

### ISSUE THREAD

**Issue by sryze** [ampproject/amphtml#13543]
## What's the issue?

There is no way to define a default value for a global state variable via `<amp-state>`, only for named states, so when accessing a global state property you get a warning in development mode like this:

```
query is not defined; returning null.
```

## How do we reproduce the issue?

See the autosuggest example on AMP by Example:

https://ampbyexample.com/advanced/autosuggest/#development=1

You will see the following warnings in the browser console:

```
 query is not defined; returning null.
 showDropdown is not defined; returning null.
 query is not defined; returning null.
 log.js:162 Default value for <AMP-LIST [src]="query ?
                 autosuggest.endpoint + query :
                 autosuggest.emptyAndInitialTemplateJson"> does not match first result ([object Object]). We recommend writing expressions with matching default values, but this can be safely ignored if intentional.
```

I was following this example to create my own autocomplete experience based on it but I'm facing these variable not defined warnings.

## What browsers are affected?

All.

## Which AMP version is affected?

1518441587106

**Comment by Syntaf** [comment]
Is there any reason you want to use a global state variable, and not just define a state? E.g.

```html
  <amp-state id="globalState">
    <script type="application/json">
      {
        "property1": "Text",
        "property2": false
      }
    </script>
  </amp-state>
```

Then within your events, you simply set the global state:

```html
<button on="tap:AMP.setState({ globalState: { property1: 'Success!' }})>
  Click Me!
</button>
```

**Comment by choumx** [comment]
That message is meant to be a helpful hint for figuring out the value of an expression and can be safely ignored. There are probably better ways to convey this without implying that something is broken.

**Comment by sryze** [comment]
OK, thanks for the explanation. For me warnings mean "something might be broken" so I always try to get rid of them or keep their count minimal. Otherwise if some new real warning appears it becomes easy to miss.

I ended up moving variables from the global state to my own state and referencing them though that state using `setState` like @Syntaf. I didn't think of nesting parameters of `setState` this way before. 

But it's kind of strange that you can modify global state via `setState` but can't initialize it.
