### ISSUE TITLE
amp-kaltura player does not play on firefox (endlessly buffers). potentially just iOS

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#13540]
from: https://github.com/ampproject/amp-by-example/issues/1122#issuecomment-365237367

Video buffering forever and not playing in  components amp kaltura player  card in IOS 10.3.3 mobile
Steps to reproduce:
1.Launch FireFox
2.Go to https://ampbyexample.com/
3.Click on the hamburger menu
4.Tap on "Components"
5.Tap on "amp kaltura player"
6.Observe buffering video forever in example box and not playing
Observer result: Next page arrows are hiding on click
Expected result: Next page arrows to be enabled to navigate next page and shoudnt hide on clicking
ENVIRONMENT DETAILS:
-FireFox 10.4
-Device Model= MN312LL/A IPhone 6Splus
-Android OS version = 10.3.3
![img_0150 2](https://user-images.githubusercontent.com/35077268/34898624-011f1cde-f7a9-11e7-9286-24c90d3975f1.PNG)

/cc @aghassemi

**Comment by aghassemi** [comment]
Not much we can do about this. It is either an issue with Kaltura itself or that particular video not being encoded properly. 

@itaykinnrot

**Comment by aghassemi** [comment]
Closing the issue since it is not something we can fix. @itaykinnrot could you please follow up internally with Kaltura team?
