### ISSUE TITLE
Replace magic numbers in overrides of getPriority() with constants and rename method to getLayoutPriority()

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#13555]
Currently extensions that override the getPriority() method use magic numbers (e.g., [amp-state.js](https://github.com/ampproject/amphtml/blob/9b101fa000b7dc911073cacdf3ccafb187c2012d/extensions/amp-bind/0.1/amp-state.js#L33) returns `1`.)

These values aren't clear, we should change them into constants. We use values between 0–2, with 3 being added in PR #13409, in 12 files. I propose the following names:
PRIORITY_NORMAL = 0;
PRIORITY_LOW = 1;
PRIORITY_LOWER = 2;
PRIORITY_LOWEST = 3;

**Comment by danielrozenberg** [comment]
Both are legit, question is whether we want them to be descriptive or prescriptive :)

**Comment by cramforce** [comment]
I like descriptive.

**Comment by danielrozenberg** [comment]
@cramforce and just to make sure we're on the same page, the descriptive one is what @choumx suggested? :)

**Comment by cramforce** [comment]
Yes :)
