### ISSUE TITLE
Ideas for what we'd like to do in AMP v-next

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1356]
We currently serve v0. When we increment the major version, we can make breaking changes. What should those be?
## Simplify core
- Move `amp-ad` and `amp-pixel` and `amp-video` into extension. Reduces size penalty on pages that don't need them and allows them to be versioned independently.
## CSS changes
- Disallow in-page scrolling: #1377
## Element changes
- Make poster in `amp-video` mandatory, so we always have something to prerender.
- Make fallback for iframe mandatory.

**Comment by erwinmombay** [comment]
@dvoytenko when can we deprecate the original slides code?

**Comment by cramforce** [comment]
That is somewhat independent, as extensions have their own version.

**Comment by dvoytenko** [comment]
Yes, original slides should be completely independent. However, I think we can remove them at any point since we've already removed them in validator, I believe. Might be worth verifying that and maybe check how many documents still use it.

**Comment by rudygalfi** [comment]
Since it's a year later and this was basically a discussion, I'll hand this off to @cramforce to determine if we want to close this out and track v1 ideas some other way.

cc @adelinamart

**Comment by cramforce** [comment]
Lets keep this open until we ship v1. It is quite remarkable, that

- we did a few things in the original issue without breaking backward compat
- how little we added over time. I've not forgotten about this issue.

**Comment by aghassemi** [comment]
1/4 done :) I am sure there are a lot more than 3 more things we want for v1. I am closing this, it can still be referenced when thinking about v1.
