### ISSUE TITLE
[discussion] amp-lightbox-gallery support: CSS API, content support, captions

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#13565]
CSS API
-
Start with all restrictions in place: remove "!important" styles as compelling use cases come up in the wild

Tradeoff: less flexibility in short term / potentially less adoption by folks who see restrictions as a barrier to use; better backward-compatibility for any changes in the future; fast/easy to make changes as they come up

CONTENT SUPPORT
-
INITIAL LAUNCH
- Images and videos
incl: `<amp-image>`, `<amp-instagram>`,	`<figure>`,	`<amp-anim>`, `<amp-video>`, `<amp-[video-vendor]>`, `<amp-facebook data-embed-as="video">`

SOON AFTER
- Ads

LATER
- Social embeds
- Arbitrary AMPHTML

CAPTION SUPPORT
-
Launch with optimized text-only support
Enhance later with support for arbitrary AMPHTML content (different option in API)

**Comment by ericlindley-g** [comment]
/cc @cathyxz @aghassemi @spacedino   

This is a proposal bringing together some of the outstanding decision points from our conversations about the lightbox-gallery. Would be worth discussing in person ( @cathyxz — I forget what the state of video is now w/r/t content support), but thought it would be useful to get something on GitHub to track.

**Comment by cathyxz** [comment]
I think we can close this now that we've resolved this discussion via the lightbox weeklies and have basically got to QA/launching point.
