### ISSUE TITLE
Add rule that ads need to report the creative they loaded to page

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1357]
We want to use this to enable attribution of runtime performance to the loaded ads.

**Comment by ds0001** [comment]
:+1: was there dialogue elsewhere about this? was just looking into an issue with regards to this.

**Comment by cramforce** [comment]
@ds0001 No real discussion. We were just looking into our performance measurements and throught it would be nice to add this info as one dimension.

@rudygalfi Would be interesting to also add this to general analytics. My issue was meant to mostly address our internal perf statistics.

**Comment by ds0001** [comment]
@cramforce ah got it then I will :-1: to net out my vote :)

**Comment by cramforce** [comment]
@ds0001 Were you looking to get it into analytics? I think that is a great idea. This ticket is mostly about making the info available to the page. We can then report it to all places we'd like :)

**Comment by rudygalfi** [comment]
Agree that having the perf data related to analytics would be great too.

@cramforce Could you clarify how you see the rule being enforced for both the ads and analytics cases?

For analytics, would the reporting be at the level of specific measurements or events, a specific endpoint the data is getting sent to, something else?

**Comment by cramforce** [comment]
The rule will just be a sentence in our docs. We enforce through code review.

Analytics could gather the results and make them available as a variable for reporting.
