### ISSUE TITLE
Write contributor-facing documentation for amp-story

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#13579]
This is a broad issue to cover a lot of things:

Priority | Category | Item
-- | -- | --
P0 | General | General: Overview
P0 | General | General: Design Principles
P0 | General | General: Table of Contents
P1 | Localization | Localization: Deprecating a string
P1 | Localization | Localization: Updating a string
P1 | Localization | Localization: Injecting the service
P1 | Localization | Localization: Using a string translation
P1 | Localization | Localization: Testing using pseudolocales
P1 | StoreService | StoreService: Overview
P1 | StoreService | StoreService: Adding a new property
P1 | StoreService | StoreService: Retrieving a value (one-off)
P1 | StoreService | StoreService: Listening for changes
P1 | StoreService | StoreService: callToInitialize
P1 | Pages | Page navigation: switchTo steps
P1 | Analytics | Analytics: Injecting the service
P1 | Analytics | Analytics: Adding a new trigger
P1 | Analytics | Analytics: Adding a new variable
P1 | UI | HTML templating
P1 | UI | CSS file organization
P1 | UI | Adding a new system UI component
P1 | UI | UI Types
P2 | MediaPool | MediaPool: Problem statement (iOS video limit)
P2 | MediaPool | MediaPool: Problem statement (blessing audio)
P2 | MediaPool | MediaPool: Problem statement (cancelling downloads)
P2 | MediaPool | MediaPool: Life of a media element
P2 | MediaPool | MediaPool: Default media
P2 | MediaPool | MediaPool: Media tasks
P2 | Bookend | Bookend: Components system
P2 | Bookend | Bookend: History state
P2 | Pages | Page navigation: Progress bar
P2 | Pages | Page navigation: PageAdvancement
P2 | Pages | Page navigation: History state
P2 | Embedded Components | Embedded Components: Overview
P2 | Embedded Components | Embedded Components: Config spec
P2 | Embedded Components | Embedded Components: Adding a new component
P2 | General | haxx.md
P2 | Animations | Animation presets
P2 | Pages | Distance attribute and positioning

**Comment by newmuis** [comment]
Updated with a more comprehensive list.  I think this is something we should start on soon.

**Comment by CrystalOnScript** [comment]
@newmuis - can you cross out whats been documented from the table? Thanks!

**Comment by newmuis** [comment]
Done! (nothing has been documented 😟)

**Comment by CrystalOnScript** [comment]
Hahahahaha, thanks for the update!😂

**Comment by newmuis** [comment]
@ampproject/wg-stories this is a great reminder for us to take a look at contributor-facing documentation.  I don't know that the areas that I outlined above are the correct ones, but if you have ideas, please add them!  We should find the right way to make meaningful progress on this list.
