### ISSUE TITLE
Unmuting a story does not always work

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#13588]
On iOS, unmuting a story does not always work. Clicking the unmute button does not play the sound.

Very easy to repro using an iPhone 5.

**Comment by matthewgcallahan** [comment]
We've been hearing some reports of this as well

**Comment by gmajoulet** [comment]
More testing revealed that it actually works, but it's (very) slow. I could find cases where it took more than five seconds using an iPhone 5.

Current flow is:
1. Bless all story media elements
2. Unmute current page media elements

A better flow could be:
1. Bless current page media elements
2. Play current page media elements
3. Bless other elements
