### ISSUE TITLE
Its possible use another custom elements?

### ISSUE THREAD

**Issue by aikt** [ampproject/amphtml#1359]
Hi!,

Sorry for my english,

My question is: Its possible use another custom elements in AMP?,

I searching for menu left panel with pure css, but in all pages with tutorials, to open the menu, its necesary the pseudo-element :checked, so in the restrictions of AMP, the input and label is prohibited, and i searched for another solutions, and i find custom elements, its the reason for the question.

Thanks.

**Comment by cramforce** [comment]
We're planning to add an extension for this. See #827
