### ISSUE TITLE
Add API to expose font events via CSS classes.

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#136]
See https://www.filamentgroup.com/lab/font-events.html and discussion
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/pcu-format-wg/K3eJeAKoqJM/WDiUMEFgAgAJ

**Comment by cramforce** [comment]
Dupe.

**Comment by rudygalfi** [comment]
Was this closed by #648?

**Comment by dvoytenko** [comment]
Yes
