### ISSUE TITLE
Amp validator validates the html but search console shows critical issue 

### ISSUE THREAD

**Issue by the-mj** [ampproject/amphtml#13629]
I have an amp page purely based on the amp project template. 
The amp vaildator validates the amp page perfectly but the search console reports show that the page has "critical" issue. More specifically, the User Authored custom java script issue.
AMP TEST: https://search.google.com/test/amp?id=A_6NemxnbUpdu9kLwpwDaA 
The validator should not validate such page in the first place. 
On examining the page more carefully the so-called custom script is injected after the closing html tag (at the hosting server's end). 

I humbly request the devs to look into this wholeheartedly and not close it unnecessarily.

**Comment by aghassemi** [comment]
@the-mj , you would need to configure your hosting service not to inject JS into your AMP pages as that makes them invalid.

**Comment by the-mj** [comment]
@aghassemi thank you for responding. I talked with the guys at yahoo small business hosting. 
They said the script is a tracking script injected in every page hosted on their platform. That means it is by default and I cannot reconfigure that. Is there a possibility that amp project can allow the custom scripts from np.lexity.com 

I mean if it doesn't affect the performance it is doable, right? It will definitely help A LOT of websites to take advantage of the "speed and rich features" that appear on the Google search results. 

Inability to get amp pages indexed just because of inflexibility of some makes me feel that I am unfair to my client.

The amp pages was probably the only way to help my client's business get a better ranking on Google.

**Comment by choumx** [comment]
Unfortunately, we can't make an exception here. Yahoo can support AMP by injecting an `amp-analytics` tag instead: https://www.ampproject.org/docs/reference/components/amp-analytics

/cc @rudygalfi
