### ISSUE TITLE
Conflicts of interest and the AMP Project

### ISSUE THREAD

**Issue by ldstevens** [ampproject/amphtml#13623]
Yesterday I attempted to get some answers to pertinent questions regarding AMP here: #13597. (For background this came from earlier discussion in #13457, and that spawned #13600 & #13603.)

Since then I've been reflecting on @cramforce's [response](https://github.com/ampproject/amphtml/issues/13597#issuecomment-367525276), particularly:

> We were worried about the web not existing anymore due to native apps and walled gardens killing it off. We wanted to make the web competitive. We saw a sense of urgency and thus we decided to build on the extensible web to build AMP instead of waiting for standard and browsers and websites to catch up. I stand behind this process. I'm a practical guy.

I’ve also been reflecting on the AMP 2018 keynote where @cramforce outlined AMP's vision as "a project, [to] create a strong, user-first open web forever." Another presenter also said "Now, we've seen so much success with AMP [...] that we feel confident in saying that AMP is the right core technology to build your site with."

My summary of this is that, in short, despite walled gardens coming and going in the past (Compuserve, AOL et al), Google felt they/the web were existentially sufficiently threatened this time around that they embarked on a project to re-imagine the web as an open source project under their control which will "create a strong, user-first open web forever" and that people who build websites should consider building their sites entirely with AMP, Google's open source technology. The keynote also outlined the many verticals AMP is expanding into (and beyond with email), so the thrust of this seems to be: All AMP, in any vertical, forever, with preferential treatment in Google's products (Search, Gmail). (@cramforce if this is not accurate please correct me at length, as I and many others would appreciate the clarity.)

This brings me to the clear conflict of interest at the heart of AMP: to "make the web competitive" is really to "make Google competitive" with Facebook et al. Given the web isn't a corporate entity -- it has users and community, not staff and shareholders -- it has no intrinsic need to "compete" with anything, but Google does, and thus a conflict of interest exists. 

Therefore, decisions made by Googlers for AMP, whether its AMP Stories, or AMP for Email, or other AMP-related features that have yet to be invented or announced, come with the considerable baggage of Google's corporate interests. 

Now, conflicts of interest are hardly unknown in tech or other industries, e.g. science, medicine, financial services, and the media (to name a few) all need to navigate them. This is because if you have a financial interest in something, people are rightly suspicious of actions taken, especially when that interest is not disclosed. History tells us that humans with a financial incentive -- however benevolent their professed motives -- will more often than not act in accordance with their own self-interest, and Google is no exception to the entirety of human history in this regard. 

Indeed, Google has a history of professing to keep a 'church and state' separation between organic search and ads for just this reason: it allows the pursuit of commercial interests while maintaining trust in the "pure" side of the business. Therefore there's nothing necessarily surprising or novel about a conflict of interest arriving, the question is simply whether it is acknowledged and handled appropriately, as failure to do so leads to, at best, compromised and tainted decision making. 

My concern here is what, if any, 'church and state' division exists regarding the AMP Project and Google management. 

Therefore I'd like to ask the following questions:

1. **Past discussion:** What internal discussions, if any, have been held regarding the conflicts of interest that are self-evident in Google’s creation and implementation of AMP?

2. **Disclosure:** What steps will the AMP project take to disclose current and future conflicts of interest? How will Google's AMP team disclose what Google's management and other teams have contributed to AMP feature development, and the financial incentive either they have personally (e.g. performance bonuses) or Google has corporately through their implementation? (E.g. "We hope to attract people away from Facebook and other social apps to make more money through search advertising and our advertising display network.")

3. **Picking winners:** When Google "blesses" AMP implementations with preferential treatment in Search or other products (Gmail) they effectively create a defacto standard out of their own technology that, given their monopoly position, makes any competing technology uncompetitive. What process does Google follow in making determinations about what therefore "succeeds" in the marketplace? Will these deliberations be public? Will AMP-style blessing ever be open to non-Google technologies?

4. **Internal conflicts:** When a conflict arises between Google's business demands for AMP, and what the technical team or wider community see as appropriate for AMP, how will the AMP Project handle and resolve the dispute? To date, has their been any instances where Google's businesses interests and the AMP Project's interests have not aligned? How was this resolved?

5. **Recusal, removal, and mitigation:** Finally, given the [various methods](https://en.wikipedia.org/wiki/Conflict_of_interest#Mitigation) of resolving conflicts of interest beyond mere disclosure, will the AMP Project consider any further work on whether Google’s staff with conflicts of interest (e.g. performance bonuses) should remove or recuse themselves from AMP discussion and implementation when a conflict arises? 

Given the extraordinary ambition of the AMP projects (any vertical, all AMP, forever), I feel it is incredibly important that these matters are addressed thoroughly and transparently.

Thank you.

**Comment by cramforce** [comment]
My [response from yesterday](https://github.com/ampproject/amphtml/issues/13597#issuecomment-367525276) is largely relevant here. Given [that previous issue](https://github.com/ampproject/amphtml/issues/13597) and other comments, I judge this issue as an instance of [sea lioning](https://en.wikipedia.org/wiki/Sea_lioning) and will consequently close this issue and lock it for further comments. Please see our [code of conduct](https://github.com/ampproject/amphtml/blob/master/CODE_OF_CONDUCT.md) for additional context.

I know this action can be interpreted as looking bad on the project and by extension Google, but I will value the health of this project and its regular contributors over optics any day. As written in [my comment from yesterday](https://github.com/ampproject/amphtml/issues/13597#issuecomment-367525276) I think that the conversation itself is important and I'm always available on the internets.
