### ISSUE TITLE
amp-youtube remove source querystring

### ISSUE THREAD

**Issue by gui-poa** [ampproject/amphtml#13634]
## What's the issue?
As happened in amp-twitter (already solved: https://github.com/ampproject/amphtml/issues/11770) the youtube's video does not work when the URL has a quetrystring.

"The attribute 'data-videoid' in tag 'amp-youtube' is set to the invalid value 'aNi1jjtFdao?rel=0' "

## How do we reproduce the issue?
https://www.terra.com.br/amp/diversao/geek/lutadora-dos-maiores-seios-dos-games-volta-a-soulcalibur,2f324103ed7722ff4b04960df2f6fea9hm8ple3n.html

**Comment by cathyxz** [comment]
@gui-poa out of curiosity, is there a reason that you must add query strings to the `data-videoid` attribute? =) 

The API was originally designed to [take a clean video-id only without query strings](https://www.ampproject.org/docs/reference/components/amp-youtube).

**Comment by gui-poa** [comment]
Actualy we import content from many sources/publishers. I don't know why they use it.

But I found a good use case here: the start time video.
<amp-youtube data-videoid="Y9ugii4tBis?start=179" height="270"...
