### ISSUE TITLE
feature request: amp-audio events for reacting to playback state changes like pausing or reaching an end of the file

### ISSUE THREAD

**Issue by HitoriSensei** [ampproject/amphtml#13653]
## Motivaion

I'm creating a site that plays audio with <amp-audio/>, but I need to react to the state of the media, when it is paused, played, has reached an end and when the current play position changes.

For position updates, event similar to the low precision timeUpdate from amp-video is good enough.

## The Feature request
state change/timeUpdate events for amp-audio

## Contribution
I would prefer the feature to be added by current owners of amp-audio @aghassemi @wassgha if possible (since I haven't dipped into amp code myself yet), but if not, I can contribute to the component myself, I would just like to get a green light to do so.

**Comment by aghassemi** [comment]
@HitoriSensei Adding those events is fine, but they have to be low-trust events which means they can not trigger most actions such as `setState` (they can only low-trust actions). `timeUpdate` is low-trust as well.

If this still helps you with your use-case and given other priorities, it would be great if you can take a stab at it. I will be available on Stack and GitHub to help and looking at https://github.com/ampproject/amphtml/issues/13420 which has detailed instructions on how to contribute to AMP for a fairly similar feature should help you get started.

**Comment by aghassemi** [comment]
de-duping for #20070
