### ISSUE TITLE
amp-playbuzz the Show More button is on top instead of bottom

### ISSUE THREAD

**Issue by shaibo10** [ampproject/amphtml#13661]
## amp-playbuzz the Show More button style

The button is stick to the top of the item, it should be on the bottom, it looks bad when the item is above the fold

1. go to a page with an amp-playbuzz scroll to amp-playbuz component
2. after the iframe is displayed, you will see the button in a wrong placement

[example](https://s3.amazonaws.com/playbuzz-cdn/amp/amp-playbuzz-bug-example.html)
[screenshot](https://s3.amazonaws.com/playbuzz-cdn/amp/amp-playbuzz-style-bug.png)

**Comment by aghassemi** [comment]
@shaibo10 Looks like you have a fix for it already, could you please send that to us as a PR and cc me and @buzzdan?
Thanks!

**Comment by shaibo10** [comment]
It's an old fix, It merged to my master in a mistake, I'll test it and then
I'll make a PR

בתאריך 26 בפבר' 2018 22:14,‏ "Ali Ghassemi" <notifications@github.com> כתב:

**Comment by cathyxz** [comment]
Addressed by #13687
