### ISSUE TITLE
Official CDN for Font Awesome 5 has changed

### ISSUE THREAD

**Issue by cryogenic-ric** [ampproject/amphtml#13685]
Font Awesome is whitelisted via https://maxcdn.bootstrapcdn.com host.
I cannot find the latest releases (v5.x.x) anywhere on the above host.

The [Official](https://fontawesome.com/get-started/web-fonts-with-css) CDN link is: https://use.fontawesome.com/releases/v5.0.7/css/all.css

**Comment by aghassemi** [comment]
/to @Gregable Looks like we need to whitelist `https://use.fontawesome.com` as well.

**Comment by concept-id** [comment]
hi, is there a plan to whitlist `pro.fontawesome.com` too?

**Comment by samuelcolvin** [comment]
@concept-id I don't think that's necessary, we have font awesome pro and our dedicated CDN is at `https://use.fontawesome.com/xxx.js`.

**please** can you get `use.fontawesome.com` whitelisted, currently fontawesome 5 both pro and standard are unusable with amp.

**Comment by samuelcolvin** [comment]
So apparently `use.fontawesome.com` is already whitelisted, just not documented.

**Comment by mlwilkerson** [comment]
See also: #15100

**Comment by samuelcolvin** [comment]
Thanks, sorry for my mistake above on `pro.`

**Comment by Appie7** [comment]
This really helped me out guys thanks.
