### ISSUE TITLE
AMP-Carousel buttons with event swiper coordination, have bug?

### ISSUE THREAD

**Issue by aikt** [ampproject/amphtml#1369]
Hello,

I 'm testing the amp-carousel with the attributes controls and type=slides, and in the version Desktop the operation is fine, but in Mobile (Iphone 5), when i use swipe to direction right, the button left not appear of disabled to enabled, but when i click the button right, the left works, and the coordination of slides its different between button and swiper, for example, i swipe to final slide and the button right is enabled, so i click the button and the carousel move to the second slide.

So my question is if there is any solution on the subject.
Thanks.

**Comment by cramforce** [comment]
Assigning to @erwinmombay for triage.

**Comment by erwinmombay** [comment]
currently working on this on https://github.com/ampproject/amphtml/pull/1360

**Comment by erwinmombay** [comment]
@aikt so you swiped to the last slide and the "button right" is shown? do you happen to have a video element on the last slide?

we currently have a bug where we think we are on desktop if you click play on a video. also, is it possible for you to share a demo or a link to your page? that would greatly help me figure out your issue and the possible bug you are seeing.

**Comment by aikt** [comment]
@erwinmombay 

Yes, i have a list for the bugs what im tested and i share the url for example -> ( https://jsbin.com/zunuyokege/1/edit?html,output ) :

1. In the final slide, when i click the button right, the carousel move to the first slide.
2. When swipe to the final slide, the button right is yet enabled, this happens similar when you swipe to the first slide the left button is enabled ).
3. When the left button is enabled and your swipe to the first slide, and click the left button, the carousel move to the final slide.

Note: Actually, to fix my problem for the bug to mobile, in the CSS i put in the element amp-carousel, the property " pointer-events : none; ", this stop the event swiper and only allows me the interaction with the buttons, because my project need to work like that.

Thanks.

**Comment by erwinmombay** [comment]
@aikt thanks for the demo and detailed list! looking more into it

**Comment by erwinmombay** [comment]
should be fixed through #1360 let us know if you still see the issue and feel free to reopen.
