### ISSUE TITLE
DISALLOWED_TAG amp-user-notification

### ISSUE THREAD

**Issue by justforfun** [ampproject/amphtml#1370]
AMP validation fails whenever an <amp-user-notification> is added to the page.
This is the error message that is shown:
DISALLOWED_TAG amp-user-notification

Here:
https://justforfun.github.io/examples-amp/amp-notify.html#development=1
To create this page I simply cloned the git example page:
https://github.com/ampproject/amphtml/blob/d2d8106ae67d9fc80694e2da08e42ef634bfb80b/examples/user-notification.amp.html
What am I missing?

**Comment by cramforce** [comment]
Not missing anything. It always takes a while for changes to become available to the validator.

@erwinmombay Did you get the validator updated?

**Comment by rudygalfi** [comment]
This should be fixed now.
