### ISSUE TITLE
How to Add validation in single date picker

### ISSUE THREAD

**Issue by Sitanderkumar** [ampproject/amphtml#13711]

**Comment by cvializ** [comment]
Hi @Sitanderkumar, could you give a little more detail about what you're trying to accomplish? Are you referring to form validation https://www.ampproject.org/docs/reference/components/amp-form#custom-validations ?

**Comment by Sitanderkumar** [comment]
Hi,

i have one form widget there i have implemented this single date picker for selecting return and depart date which cannot be black for initiating search. If i add required on another input attribute its working fine but not with the single date picker.

**Comment by cvializ** [comment]
The date picker API is changing after #13643 that will make this possible and should be available experimentally in a few weeks. I'll close this for now since that should resolve your problem. Thanks for opening this issue!
