### ISSUE TITLE
Typo in amp-iframe documentation 

### ISSUE THREAD

**Issue by pdxbmw** [ampproject/amphtml#1372]
There's a small typo under [Iframe Click-To-Play](https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md#iframe-click-to-play):

*  It is possible to have an `amp-iframe` appear on the top of a document when the ~~amp-ifame~~ `amp-iframe` has a `placeholder` element as shown in the example below.

**Comment by cramforce** [comment]
@sriramkrish85 Could you fix? Tx!
