### ISSUE TITLE
GA being remove when a a4a it's loaded

### ISSUE THREAD

**Issue by eduardcotmrf** [ampproject/amphtml#13734]
In a non-amp website like www.periodistadigital.com (mobile version) we load ads using doublick third-party creatives (https://support.google.com/dfp_premium/answer/1746123?hl=en).

When a creativity that it's amp4ds loads, our analytics breaks cause it changes the ga variable in window.

1. We load analytics the standard way:
  https://developers.google.com/analytics/devguides/collection/analyticsjs/

2. I know that it's  amp4ads creativity because I see this scripts in the head of the page:

`<script src="https://cdn.ampproject.org/rtv/011518441587106/amp4ads-host-v0.js"></script>`

3. The creativity it's doing something strange, after being loaded I can see this in the console:
![screen shot 2018-03-01 at 10 21 31](https://user-images.githubusercontent.com/23262331/36836679-5621ec46-1d3a-11e8-941a-8f3adb2158bb.png)

It has trasformed our ga function into the regexp: `/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/`.

This is important and could be affecting a lot of publishers.

Why is the a4a creativity modifying standard 'ga' window variable?

**Comment by TimoRuetten** [comment]
We are facing the same problem so we had to remove adsense for now.

**Comment by lannka** [comment]
All AMP vars in amp4ads-host-v0.js are leaked to window object. We need a function wrapper to namespace it.

How was it done for v0.js? I thought closure compiler would automatically do it? @erwinmombay

**Comment by lannka** [comment]
Found the reason. Here is the fix: #13960

/cc @keithwrightbos @bradfrizzell

**Comment by lannka** [comment]
FYI, this will be out on canary for testing today, and roll out to prod next week.

**Comment by eduardcotmrf** [comment]
We noticed that our AMP canonical websites were working fine but all of our non-AMP canonical websties were afected by this bug and lost a lot of pageviews.

Every time a a4a ad loaded basically broke our ga metrics.

Thanks for fixing the problem as it had a huge impact on metrics for all publisher loading a4a ads.
