### ISSUE TITLE
expose AD_START and AD_END events in video analytics

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#13753]
1- trigger analytics events for them in video-manager
2- document the new events in video analytics documentation.

/cc @shawnbuso @jasti

**Comment by zhouyx** [comment]
Is this related to amp-ima-video?

**Comment by aghassemi** [comment]
mostly for `amp-ima-video` but any player can dispatch those events. Right now they are just normal DOM custom events that get dispatched, we would just need to make them also Analytics events.

**Comment by zhouyx** [comment]
Thanks. Sounds like a new trigger type that we can add to the existing video analytics triggers.

**Comment by Madagar** [comment]
Would be great to have this feature.
