### ISSUE TITLE
Null reference error in Internet Explorer 10

### ISSUE THREAD

**Issue by sryze** [ampproject/amphtml#13768]
## What's the issue?

When I open my AMP page in Internet Explorer 10 it doesn't fully load because of:

```
SCRIPT5007: Unable to get property 'prototype' of undefined or null reference 
v0.js, line 477 character 390
```

## How do we reproduce the issue?

1. Use code from the [Hello World](https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fintroduction%2Fhello_world%2Fsource%2F&mode=Responsive) example
2. Put it in hello-world.html
3. Run a web-server (e.g. `php -S 0.0.0.0:9000` from same directory)
4. Open http://localhost:9000/hello-world.html in IE 10

## What browsers are affected?

Internet Explorer 10 and probably 9. It's working fine in IE 11.

## Which AMP version is affected?

1519771395920

**Comment by Adventive** [comment]
Just as a note:

> In general we support the latest two versions of major browsers like Chrome, Firefox, Edge, Safari and Opera.
see [supported browsers](https://www.ampproject.org/support/faqs/supported-browsers)

**Comment by sryze** [comment]
Yeah, I saw that after creating the issue. I made a PR that seems to fix this, at least the page mostly loads with it: https://github.com/ampproject/amphtml/pull/13779.

**Comment by nainar** [comment]
Hi @sryze! Thank you so much for sending through the PR. I have assigned the issue to you and will take a look at the PR inline. 

Also @Adventive is right - support for browsers like IE10 - is best effort but since the fix and the issue aren't adding security issues and low risk - we are happy to accept the PR. :)
