### ISSUE TITLE
Disable sync-xhr in amp-iframe/amp-ad

### ISSUE THREAD

**Issue by RByers** [ampproject/amphtml#13766]
## What's the issue?

Chrome 65+ [allows](https://www.chromestatus.com/feature/5154875084111872) synchronous XHR to be disabled.  Blocking the UI thread on the network is a perf anti-pattern and so should probably not be allowed in AMP documents or embeds.

## How do we reproduce the issue?

1. Create an amp page with an amp-iframe to a site doing a sync-xhr
2. View in the top stories carousel
3. Observe jank if you try to swipe when the sync-XHR occurs (especially on a slow network - use throttling in devtools to emulate).

## What browsers are affected?

Chrome for now, but at TPAC all other browsers [indicated](https://github.com/WICG/interventions/issues/62) a desire to add this feature as a first step of trying to phase-out sync-xhr.

## Which AMP version is affected?

All

/cc @clelland @cramforce with whom this has been discussed offline.

**Comment by cramforce** [comment]
I think we should launch this for `amp-ad` and `amp-iframe`.

@lannka Could you take this on?

**Comment by cramforce** [comment]
to @jastiv for prioritization.

**Comment by jasti** [comment]
Given current commitments, it looks like we'll tackle this in the second half of April. 
CC @zhouyx

**Comment by cramforce** [comment]
I'll try to implement on my flight back from Australia. I'll implement behind an experiment and then we can see how we can ship it.

**Comment by jasti** [comment]
@cramforce did you have a chance to look at this? If not, we can probably reassign to someone on the ads team.

**Comment by cramforce** [comment]
Turned this on in canary 5 minutes ago in #16524

Implementation in #14481

**Comment by cramforce** [comment]
Shipping this with our next prod release. Let's see how it goes :)

**Comment by cramforce** [comment]
Shipped yesterday 🎉
