### ISSUE TITLE
Always overwrite target attribute for amp-story-cta-layer a to _top

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#13775]
Any `<a>` tags descending from `<amp-story-cta-layer>` should have their `target` attribute set/rewritten to `_top`in the `AmpStoryCtaLayer` `buildCallback()`.

**Comment by calebcordry** [comment]
So, we are currently using `_blank` in ads until we work out `pageHistoryStack` stuff. 🤔

**Comment by Enriqe** [comment]
What do you think @newmuis ? Should we still use `_top`?

**Comment by calebcordry** [comment]
Whats the timeline for this? I will be working on the page history stuff this sprint, so it might be a non-issue.

Race condition? 😎

**Comment by newmuis** [comment]
+1, we should definitely still use `_top`, but it's fine to just wait until the history stuff gets in so that we don't need to do any extra work.

**Comment by newmuis** [comment]
We may not need to use `_top` specifically here, but what I mean is that outlinks should definitely override this property to have a consistent experience.  Still determining whether `_top` or `_blank` might be better.

**Comment by jonsherrard** [comment]
Hello @newmuis!

Could this possibly be configurable, I can already think of use cases where I'd want both?

I can understand why you'd not want to use `_self` or `_parent`, but I think a choice between `_top` or `_blank` would be really helpful in userland.

Thanks for all your work on this project by the way - really love stories as a format.

Ciao for now!

x

**Comment by newmuis** [comment]
We'd like (at least initially) to ensure a consistent user experience across pages and across stories.  It is something that may be able to be relaxed over time, if we're careful about how we do it.

@jonsherrard can you explain your use cases a bit to give a better understanding of how you would use this?
