### ISSUE TITLE
URL replacements in <a> don't work for "open in new tab"

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#13772]
Context: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/amphtml-discuss/pzC2_HVmYZY

**Comment by lannka** [comment]
I'm confused by code in [anchor-click-interceptor.js](https://github.com/ampproject/amphtml/blob/master/src/anchor-click-interceptor.js) and [navigation.js](https://github.com/ampproject/amphtml/blob/master/src/service/navigation.js)

it might not be related to the bug, but the code should be consolidated.

**Comment by choumx** [comment]
Huh, didn't know that existed. Definitely should be de-duped. Thanks!

**Comment by alabiaga** [comment]
fixed in #15045
