### ISSUE TITLE
Floating point rounding errors on cached version of page from HTML whitespace sanitization

### ISSUE THREAD

**Issue by jasonsturges** [ampproject/amphtml#13806]
## What's the issue?

AMP cache version of our page suffers from math floating point rounding errors.

HTML rendered from [our AMP page](https://www.magazine.store/the-magnolia-journal/amp/) lists product prices as: $29.99 and $20.00

However, [Google's cached version of our AMP page](https://www.google.com/amp/s/www.magazine.store/the-magnolia-journal/amp/) seems to suffer from floating point rounding errors, changing prices to: $27.990000000000002, and $20.0

| [Our AMP Page](https://www.magazine.store/the-magnolia-journal/amp/) | [Google's AMP Page Cache](https://www.google.com/amp/s/www.magazine.store/the-magnolia-journal/amp/) |
| -------------- | --------------- |
| ![www magazine store_the-magnolia-journal_amp_ iphone 7](https://user-images.githubusercontent.com/1213591/36994109-af6a514c-2075-11e8-83ea-ba4a38a32de7.png) | ![www google com_amp_s_www magazine store_the-magnolia-journal_amp_ iphone 7](https://user-images.githubusercontent.com/1213591/36993795-a5f7ac46-2074-11e8-8cd4-9d34703da9ec.png) |

The only thing I can think of is AMP's HTML sanitization process, where perhaps a parser is interpreting these values as floating point numbers in an attempt to remove whitespace?

From [Google AMP Cache documentation](https://developers.google.com/amp/cache/overview) on HTML sanitization:

> Whitespace inside tags is stripped.

If you look at [our AMP markup](https://www.magazine.store/the-magnolia-journal/amp/), there's whitespace in the element:
```
<span itemprop="price" class="selectionPrice">
                                            27.99</span>
```

What's also interesting is that Google's AMP page cache still has the whitespace:
```
<span class="selectionPrice" itemprop="price">
                                            27.990000000000002</span>
```

## How do we reproduce the issue?

Our Non-AMP page, with `amphtml` meta reference:
https://www.magazine.store/the-magnolia-journal/

Our AMP page version:
https://www.magazine.store/the-magnolia-journal/amp/

Compare that to Google's cached version of the page:
https://www.google.com/amp/s/www.magazine.store/the-magnolia-journal/amp/

Otherewise, the only steps I can think of to reproduce this is to place a numerical value inside an element with whitespace, and view the rendered result after Google's HTML sanitization process:

```
    <span>
        1.99</span>
```

## What browsers are affected?

All browsers

## Which AMP version is affected?

Pages affected have just been released to AMP

**Comment by aghassemi** [comment]
@honeybadgerdontcare, we don't sanitize textNodes, specially parse numbers, do we?

This may be an issue with origin servers responding differently to cache UA than user or maybe at the time of cache the value of wrong.

**Comment by jasonsturges** [comment]
@aghassemi This site doesn't have any special logic per user agent, and the front-end code explicitly formats for prices:

JSPF fragment:
```
<span itemprop="price" class="selectionPrice">
    <fmt:formatNumber type="currency"
                      pattern="##0.00;"
                      value="${selectionItem.listPriceAmount}"/>
</span>
```

Though I realize it's a stretch, but I do not believe there is any possible way for the page to render this value unless JSTL format number is in error.

**Comment by honeybadgerdontcare** [comment]
I am unable to reproduce this issue. We don't do anything special with whitespace within text nodes of the body and we don't do anything with regard to numerics. If an example could be made the consistently reproduced this, then please reopen.

My example show 27.99 appearing just fine on both origin and cache:
http://astute-city-159523.appspot.com/files/floating.html
https://astute--city--159523-appspot-com.cdn.ampproject.org/c/astute-city-159523.appspot.com/files/floating.html

**Comment by jasonsturges** [comment]
@honeybadgerdontcare Appreciate your isolation attempt to replicate the issue, but I'm confused as why there could be discrepancy.

Still on that same page, 20.00 is being transformed to 20.0

| AMP Page | Google Cache |
| ------------- | -------------- |
| https://www.magazine.store/the-magnolia-journal/amp/
![image](https://user-images.githubusercontent.com/1213591/38393108-680bffca-38ef-11e8-8c83-2d2806056c94.png) | ![image](https://user-images.githubusercontent.com/1213591/38393158-a222e0ca-38ef-11e8-95cc-4a9b1a308fee.png) |

There's no logic for user agent on this site.

Any recommendation for further debugging?  Are there curls that mimic AMP crawl; or, any way to execute a segment of this project that creates the cache?
