### ISSUE TITLE
AMP validator fails with `The attribute 'referrerpolicy' may not appear in tag 'a'` 

### ISSUE THREAD

**Issue by alex-magana** [ampproject/amphtml#13824]
## What's the issue?
AMP Validator reports the following when you set a `referrerpolicy` on an anchor tag `<a>`.
`The attribute 'referrerpolicy' may not appear in tag 'a'`

**Example**
```
<a href="http://example.com/page.html" referrerpolicy="unsafe-url"></a>
```

Briefly describe the bug/feature request.

## How do we reproduce the issue?
**Sample Page**
`https://a-referrer.000webhostapp.com/`

**Steps**
1. Add a referrer policy to the anchor tag. 

**Example**
```
<a href="http://example.com/page.html" referrerpolicy="unsafe-url"></a>
```

## What browsers are affected?
The page was viewed on Google Chrome version 64.0.3282.186 (Official Build) (64-bit)

## Which AMP version is affected?
Version 1519771395920

>> Is this a new issue? 
Support for the `referrerpolicy` attribute was requested on,
https://github.com/ampproject/amphtml/issues/3949,
and delivered in,
https://github.com/ampproject/amphtml/pull/3973

**Comment by honeybadgerdontcare** [comment]
`referrer-policy` is allowed on `amp-iframe` per #3973. @aghassemi do we also want to add it to anchor tags?

**Comment by aghassemi** [comment]
@honeybadgerdontcare I don't see any issue with supporting `referrerpolicy` on `a`. We already support for `amp-iframe`, `amp-img` and `amp-pixel`.
