### ISSUE TITLE
Allow client id consumers to opt-in to setting a fallback cookie

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1382]
Currently when a document is read on a non-proxy origin, reading the client id will only fallback to the cookie of the name of the client id scope.

We should allow the consumer of the id to say "go ahead and set a value to that cookie" if it is not present.

CC @rudygalfi

**Comment by rudygalfi** [comment]
"allow the consumer of the id" --> Is this strictly tied to the `type` attribute? There should be a way to do this even if you're not using a vendor (with a config in the repo), right?

**Comment by cramforce** [comment]
I think it needs to be configurable. We **could** make it the default, but I think some sites might to prefer setting cookies to some magic value themselves.

**Comment by dvoytenko** [comment]
Reassigning to @cramforce to triage with analytics.

**Comment by rudygalfi** [comment]
#1385 seems to indicate this is still open for analytics. Can anyone speak to status of this issue?
