### ISSUE TITLE
amp-carousel issue after recovering from display:hidden

### ISSUE THREAD

**Issue by shreeshkatyayan** [ampproject/amphtml#13822]
## What's the issue?

I am developing a product landing page, only using AMP base JS and Carousel plugin. In the page, I populate list of products programmatically via AJAX request and it works fine. On product selection, I add display = none to the parent element. Now, the initial state is recovered to enable user to choose product again from the carousel. After this, in mobile devices if we swipe back or forth to the next/previous card, it throws following error:

```
Attempting to access a non-existant slide
    de @	element-service.js:76
    (anonymous) @	viewer-impl.js:178
    f.error @	log.js:237
    ua @	slidescroll.js:567
    Y @	slidescroll.js:601
    (anonymous) @	slidescroll.js:493
    Ok @	viewport-impl.js:500
    f.Wg @	viewport-impl.js:448
    requestAnimationFrame (async)
    Mk @	viewport-impl.js:434
    f.Ma	@	viewport-impl.js:434
    f.run @	viewport-impl.js:304
    f.mutate @	viewport-impl.js:320
    W @	slidescroll.js:485
    (anonymous) @	slidescroll.js:435
    Promise.then (async)		
    X @	slidescroll.js:434
    (anonymous) @	slidescroll.js:369
    (anonymous) @	resources-impl.js:1574
    setTimeout (async)		
    f.delay @	resources-impl.js:1574
    push.f.f.aa @	slidescroll.js:362
```

## How do we reproduce the issue?

Steps to reproduce: 
1. Switch to mobile view on chrome debugger
2 .Navigate to https://latest.lybrate.com/dr-reddys-econorm-probiotic/p/econorm-sachet?version=new
3. Select a product
4. Tap on back button on form
5. Try to swipe on product selection > Error throws

## What browsers are affected?

Tested just on chrome. Will update when test on others. Still a feature under-development

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1519771395920

**Comment by cathyxz** [comment]
Sorry, misclick. I'm having trouble finding the `<amp-carousel>` on your webpage. Could you paste a stable link or a codepen with the repro?

**Comment by nainar** [comment]
Hi @shreeshkatyayan, 

Please file this issue again with a stable link/codepen. Closing this since the bug is stale
Thank you and sorry for the inconvenience!
