### ISSUE TITLE
amp-analytics breaks in amp-shadow

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amphtml#13841]
## What's the issue?

The use of the amp-analytics component inside a in other respects valid AMP document throws errors ("No ampdoc found for [object HTMLElement]") as soon as it is appended via AMP.attachShadowDoc. This is similiar and possibly related to #10717 but sadly not reproducable with the provided isolated test cases.

## How do we reproduce the issue?

The issue can be seen on the following page: https://www.bmw.com/en/bmw-models/techdata/i3.pwa.html#development=1. The page opens the PWA shell that embeds the document available under https://www.bmw.com/en/bmw-models/techdata/i3.shadowcontent.html

## What browsers are affected?

In Chrome this only throws an error but still works, in Internet Explorer 11 though it breaks on the error and does not render the shadow document at all.

## Which AMP version is affected?

Tested with 1519771395920

**Comment by matthias-erl** [comment]
Let me know if there is anything I can support you with ;)

**Comment by danielrozenberg** [comment]
@matthias-erl I noticed that you have an `<amp-analytics>` component both in `i3.shadowcontent.html` (where it should be) and in `i3.pwa.html`, which if I understand correctly is only for the shell. The shell should not be built using AMP compontents, and I believe its that "outer `<amp-analytics>` that's throwing the error (the inner one successfully triggers and POSTs, as can be seen in the Network tab of dev tools)

Could this be what you're seeing?

**Comment by danielrozenberg** [comment]
@matthias-erl ping on my previous question

**Comment by sparhami** [comment]
Some thoughts after taking a quick look at the PWA version:

I see two `<amp-analytics>` elements within the main document. I don't think `shadow-v0.js` is intended to support having the main document itself be an AMP document.  I think there are currently a few rough edges with using `v0.js` and attaching shadow documents, but that is something we are working through.

`<amp-analytics>` does not apply across shadow DOM boundaries and I do not believe there are currently any plans to make it do so. You can have an `<amp-analytics>` inside the shadow doc and that should work though.

I'd like to understand the use case here a bit better here. Is the `<amp-analytics>` in the main document intended to apply to the header or to the nested shadow doc (or both)? Can the outer `<amp-analytics>` elements be place into the shadow document? Is the plan to have the outer document (the PWA) be an AMP document itself?

**Comment by matthiasrohmer** [comment]
Thanks @danielrozenberg and @sparhami for taking a look, I totally forgot about this and the client seems to have as well. 😅 Please excuse me coming back to you so late.

I think you have spotted our error: somewhere along our template inheritance-chain the PWA and AMP templates get mixed up and therefore the `<amp-analytics>` nodes end up in the PWA - where they don't belong and aren't needed. Something that doesn't happen for the normal article template as you can see in: https://www.bmw.com/en/design/pebble-beach-concours-delegance.pwa.html#development=1 where then https://www.bmw.com/en/design/pebble-beach-concours-delegance.shadowcontent.html#development=1 brings the needed tracking nodes in.

I am going to fix the corrupted inheritance and will let you know if it fixes the error, but most certainly it will. Once again thanks for poking us in the right direction!

**Comment by sparhami** [comment]
No problem. I think AMP could have a better error message than saying "no ampdoc found". Perhaps we can have a more informative error message when trying to use AMP elements in the main doc when using `shadow-v0.js`.

**Comment by sparhami** [comment]
Created #17889 to figure out how to give a more informative error message.
