### ISSUE TITLE
AMP Blog is hard to read

### ISSUE THREAD

**Issue by ayumihamsaki** [ampproject/amphtml#13854]
Went to read an article in the AMP blog and it's so hard to read, see screenshot:

![1](https://user-images.githubusercontent.com/17784082/37107406-2bd29cc8-222c-11e8-8a88-be916b3010cc.png)

Can't you just add some nicer CSS to make it readable, for example see here:

![2](https://user-images.githubusercontent.com/17784082/37107451-408009f8-222c-11e8-8bb8-9c14502c57f9.png)

All I did was do this for example:

OLD Style:

```
body, .card, .post-detail .post-content p em, .post-detail .post-content p em a {
    font-size: 20px;
    line-height: 28px;
}
.post-detail .post-content p, .post-detail .post-content li {
    letter-spacing: 0;
}
```

NEW Style:

```
body, .card, .post-detail .post-content p em, .post-detail .post-content p em a {
    font-size: 1rem;
    line-height: 28px;
}
.post-detail .post-content p, .post-detail .post-content li {
    letter-spacing: 0;
    text-align: justify;
}
td {
	padding: 10px;
}
```

Blog page I am talking about is found here: https://www.ampproject.org/latest/blog/faster-ads-with-render-on-idle/

(I'm just giving a brief example, just suggesting someone go over the blog and update all the responsive css and make it better)

**Comment by jridgewell** [comment]
@bpaduch @pbakaus: Who owns the blog? I can't find a repo for it.

**Comment by bpaduch** [comment]
Imported from Wordpress - original WP article here: https://amphtml.wordpress.com/2018/03/05/faster-ads-with-render-on-idle/

**Comment by bpaduch** [comment]
Closing this issue and rolling it up into the AMP Blog Wordpress initiative [here](https://github.com/ampproject/docs/issues/132).
