### ISSUE TITLE
<amp-ad> over https results in mixed-content requests dist.3p from http

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#13869]
I don't know if this is related to https://github.com/ampproject/amphtml/issues/7038, but in my lightbox ads tests, I'm noticing strange behavior of `<amp-ad>` over https. 

Demo URL here: https://amp-cathyxz.herokuapp.com/test/manual/amp-lightbox-gallery-launch.amp.html

Observe that in the test carousel titled `Lightbox Carousel Ad Support Test`, the second slide in the carousel is an amp-ad. Under https, it does not load, and the js console emits the following warnings: 

```
preconnect.js:226 Mixed Content: The page at 'https://amp-cathyxz.herokuapp.com/test/manual/amp-lightbox-gallery-launch.amp.html' was loaded over HTTPS, but requested an insecure resource 'http://amp-cathyxz.herokuapp.com/dist.3p/current/frame.max.html'. This request has been blocked; the content must be served over HTTPS.
preconnect.js:226 Mixed Content: The page at 'https://amp-cathyxz.herokuapp.com/test/manual/amp-lightbox-gallery-launch.amp.html' was loaded over HTTPS, but requested an insecure resource 'http://amp-cathyxz.herokuapp.com/dist.3p/current/integration.js'. This request has been blocked; the content must be served over HTTPS.
```

Observe that if you access the same url over http, that same `<amp-ad>` does load. 
HTTP url here: http://amp-cathyxz.herokuapp.com/test/manual/amp-lightbox-gallery-launch.amp.html

The ad in question is the one on [ABE](https://ampbyexample.com/components/amp-ad/): 

```
    <amp-ad width="300"
      height="250"
      type="a9"
      data-aax_size="300x250"
      data-aax_pubname="test123"
      data-aax_src="302">
```

Is there some configuration that I'm missing for `<amp-ad>`? 
The source for that page is here: https://github.com/ampproject/amphtml/blob/bd11528e577bba4eac639eef4e9e3b1075bdce90/test/manual/amp-lightbox-gallery-launch.amp.html

**Comment by zhouyx** [comment]
As talked offline. Please set AMP_CONFIG.thirdPartyUrl: to use `https` instead of `http`
