### ISSUE TITLE
Error forwarding: Document format and send minimal set

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#13867]
For `report-errors-to-viewer` feature, we should:
1. Only send the minimal subset of parameters required
2. Document this minimal subset format somewhere
3. Add a regression test

/cc @raywainman @zhangsu

**Comment by alabiaga** [comment]
@raywainman @zhangsu Can you provide some input as to subset of the error report data would be desired. eg. of this data set..

 data['v'] // runtime version
 data['m'] // message.replace(USER_ERROR_SENTINEL, '');
 data['bt'] // binary type.
 data['iem'] // is embdedded
 data['rvu'] // resolvedViewerUrl;
 data['mso'] // messagingOrigin;
 data['jse'] // detectedJsEngine;
 data['exps'] // experiments enabled
 data['args'] // error.args);
 data['s'] // error.stack;
 data['r'] //self.document.referrer;
 data['ae'] // accumulatedErrorMessages
 data['fr'] // self.location.originalHash || self.location.hash;
 and etc...

please see getErrorReportData for more details https://github.com/ampproject/amphtml/blob/master/src/error.js#L380

**Comment by zhangsu** [comment]
Thanks Aaron. Currently we only use the following fields:

```
"m"  
"a"  
"s"  
"el" 
"v"  
"jse"
```

Let's start with that.
