### ISSUE TITLE
CORS error with Google Tag Manager

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#13879]
Reported by  _Tyler G_ via email:

I'm having some trouble getting remote config to work for amp-analytics.

Here's the sample page I'm testing on:  http://usdev-amp.businessinsider.com/why-barbara-corcorans-wrong-about-rich-kids-2014-12?abc=gah

I'm trying to integrate a GTM AMP container onto this test page, and I've found to add:

```
<amp-analytics config="https://www.googletagmanager.com/amp.json?id=GTM-...>m.url=SOURCE_URL" data-credentials="include">
    <script type="application/json">
    {
    "vars": {
      "gaTrackingId": "..."
    }
    }
    </script>
</amp-analytics>
```

However this is giving me a CORS issue because its trying to access googletagmanager.com from another domain.

I've read through the docs here: https://github.com/ampproject/amphtml/blob/master/spec/amp-cors-requests.md#verify-the-cors-origin-header  but it just confused me a bit further, because I don't know how to adjust this request since it happens automatically by having the amp-analytics tag on the page.   

Another option is to host the amp.json on our domain, though then I'm not sure how it pulls the latest config from the GTM container.    I should mention in the long run we are trying to use client_id as well, and am curious to know if there's a way to read this from the cookie without having to host amp.json on our own domain.

**Comment by tyler-g** [comment]
thank you for looking into this

**Comment by zhouyx** [comment]
#13005 was fixed. @tyler-g Could you confirm that the issue still exist? I tested with the example page provided http://usdev-amp.businessinsider.com/why-barbara-corcorans-wrong-about-rich-kids-2014-12?abc=gah, and was able to get the GTM config correctly. 

Please let us know if the issue still exist. And if there's an example page to reproduce the issue. Thanks!

**Comment by lannka** [comment]
Closing for now. Feel free to reopen if you still see the problem.

**Comment by dijs** [comment]
I am still seeing this issue (or something very similar) here.

https://www.google.com/amp/s/pwa.moovweb.com/guides/analytics.amp
