### ISSUE TITLE
Mustache template HTML attributes not allowed by amp validation

### ISSUE THREAD

**Issue by AndrewKGuan** [ampproject/amphtml#13882]
Hi,
it seems to be a valid use case:

    {{#options}}
    <option value="{{value}}" {{selected}}>{{name}}</option>
    {{/options}}

But the amp validator doesn't like it, it throws an error:
Mustache template syntax in attribute name '{{selected}}' in tag 'option'.

In fact, if one whats to use a json to render any arbitrary combinations of element attributes, the validation will fail.  For example: <div id="myDiv" {{**extra_attributes**}}></div>, this is not kosher to amp validation.

**Comment by AndrewKGuan** [comment]
Anyone?

**Comment by choumx** [comment]
Sorry for the delay! Calculation of attribute name is explicitly disallowed in amp-mustache for security reasons: https://www.ampproject.org/docs/reference/components/amp-mustache

> Calculate attribute name. E.g. <div =something> is not allowed.

Instead you can try something like:

```html
{{#options}}
<option value="{{value}}" selected="{{selected}}">{{name}}</option>
{{/options}}
```

**Comment by dylanfpaul** [comment]
@choumx You're example where you go `selected="{{selected}}"` I don't think this applies for all attributes. Some attributes seem to be unaffected by this and are stripped from the resulting markup. Would you be able to point me to a list of attributes that can be dynamically set via variables, and ones that can't?
