### ISSUE TITLE
FR: Handlebars.js templating

### ISSUE THREAD

**Issue by AndrewKGuan** [ampproject/amphtml#13891]
Now there's no way to output the loop index or keys using mustache.
Use case:
```
{{#products}}
<input type="radio" id="{{productId}}" name="quickview" value="{{productId}}"
on='change:quickView_Carousel.goToSlide(index={{@index}})'>
<label for="{{productId}}">{{productName}}</lable>
{{/products}}
```
I'm sure there are many more use cases for having access to the loop index(for arrays) and keys(for objects)

**Comment by aghassemi** [comment]
Agree it would be useful. We currently use https://github.com/janl/mustache.js which does not have builtin support for this. 

/to @choumx 
/cc @lannka @Gregable

**Comment by choumx** [comment]
[Handlebars-like syntax](https://handlebarsjs.com/reference.html) e.g. `@index` is out of scope for `amp-mustache`. This doesn't preclude implementing an `amp-handlebars` extension in the future.

The Mustache-idiomatic way to do this is add an `index` property to the objects in your array of items.

**Comment by AndrewKGuan** [comment]
Hi William, 
thanks for your suggestion.
I think it would be easier for developers to adopt AMP if it could provide this kind of convenience without sacrificing AMP's performance.  To be honest, a lot of front-end dev teams in industrial sized enterprises don't have a say on how to change their json endpoints, let alone to tell another team to make changes just because they need to do an indexed loop.

**Comment by choumx** [comment]
Thanks for the feedback. Didn't mean to seem dismissive and sorry if it came across that way. 

I'll reopen and leave this as a FR for `<amp-handlebars>` template type.

**Comment by AndrewKGuan** [comment]
Thanks William! I really appreciate that.

**Comment by choumx** [comment]
```
willchou$ ls -al | grep handlebars
-rw-r--r--@  1 willchou  eng       75312 Jun 27 12:59 handlebars.min-v4.0.11.js
-rw-r--r--@  1 willchou  eng       22720 Jun 27 12:58 handlebars.min-v4.0.11.js.gz

willchou$ ls -al | grep mustache
-rw-r--r--@  1 willchou  eng        9528 Jun 27 12:58 mustache.min.js
-rw-r--r--@  1 willchou  eng        2827 Jun 27 12:58 mustache.min.js.gz
```

Interestingly, handlebars is almost 10x as large as mustache. More than half of this is the [template compiler](https://handlebarsjs.com/precompilation.html) which compiles template HTML to a special string. We'd need a new cache transformation use it.

**Comment by leonalicious** [comment]
hey @AndrewKGuan , maybe you can try out something like [this](https://aemsite.github.io/ampdemo/amp-mustache-get-index.html)

I agree that `amp-mustache` should be `logic less` and we should keep it simple as it is.

> Interestingly, handlebars is almost 10x as large as mustache. More than half of this is the template compiler which compiles template HTML to a special string. We'd need a new cache transformation use it.

Interesting to find out that the size of `handlebar` is 10x larger than `mustache`, but anyway, I think it is reasonable to provide `amp-handlebar` and leave the option for developer to choose, either they want to use something big but more rich in term of functions (amp-handlebar) or small and logic less (amp-mustache), thoughts please?

/cc: @cathyxz @aghassemi @choumx

**Comment by choumx** [comment]
We're still planning to add this eventually, just haven't gotten around to it yet.

**Comment by mkonikov** [comment]
Would love to see this implemented

**Comment by morsssss** [comment]
Just adding a +1 to this! Using mustache means outputting exactly the right JSON from APIs - which is not possible for many real-world use cases. And some really basic use cases - like comparisons to things that aren't true and false - aren't possible with mustache unless we decide to implement lambda functions. Which is probably a lot harder :)
