### ISSUE TITLE
"aria-label" and "aria-hidden" is not correctly interpreted

### ISSUE THREAD

**Issue by djavet** [ampproject/amphtml#13893]
## What's the issue?
"aria-label" and "aria-hidden" is not correctly interpreted

## How do we reproduce the issue?
1. Add in the code an aria-hidden:  <i class="user fas fa-user" aria-hidden="true"></i>
2. open your chrome browser and look at the interpreted code in dev console
3. Code is rendered like: <i class="user fas fa-user" aria-hidden>
4. Same with <div class="logo" aria-label="my string for arial">...</div> is rendered <div class="logo" aria-label>...</div>

## What browsers are affected?
Chrome IOS, annd Windows, Safari IOS

## Which AMP version is affected?
Version  #1519774160068

**Comment by djavet** [comment]
![capture1](https://user-images.githubusercontent.com/5485253/37199632-7fe8b43a-2382-11e8-962b-71f6065a1333.PNG)
![capture2](https://user-images.githubusercontent.com/5485253/37199634-7fffff8c-2382-11e8-88aa-877eb3fb16cd.PNG)

**Comment by aghassemi** [comment]
@djavet Thanks for reporting! Unfortunate bug. working on a fix now.

**Comment by djavet** [comment]
Thx for the feedback!

**Comment by djavet** [comment]
Brillant !
Thank you.

Dom

Le sam. 10 mars 2018 à 00:23, Ali Ghassemi <notifications@github.com> a
écrit :
