### ISSUE TITLE
amp-carousel: in Chrome it is easy to do double-slide swipes and  slides can still get stuck half-way

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#13903]
Might be regression of https://github.com/ampproject/amphtml/pull/13290, it is worse than what it used to be in Chrome and better in iOS

**Comment by cvializ** [comment]
I am not able to reproduce on an Android device Samsung J2 Prime / Chrome 65. Is there an example document where this was reported to be happening?

**Comment by aghassemi** [comment]
@cvializ Good news! I had "Experimental web Features" enabled on my chrome and that was messing this up.

Phew!

Closing the issue, thanks for investigating.
