### ISSUE TITLE
Amp story transition button not working

### ISSUE THREAD

**Issue by babakhoo** [ampproject/amphtml#13900]
I tried to work with amp story via https://www.ampproject.org/docs/design/visual_story
My webserver app is chromebeat.com and no problem of hosting.
by lunching 'peps-completed.html' from the source file, I see the first page correctly and the button in the right for going to the next page.
Unfortunately clicking the buttons doesnt change the page or do any action.

**Comment by babakhoo** [comment]
sorry it was not a correct place

**Comment by babakhoo** [comment]
Dear choux,
I got this issue on my laptop, sorry I don't have a host now.

**Comment by choumx** [comment]
Thanks for the update. Please reopen this issue if you have a way to repro it.
