### ISSUE TITLE
How to share a YouTube video with a specific start and end time on AMP ?

### ISSUE THREAD

**Issue by asfarmed** [ampproject/amphtml#13916]
Hi 
How to share a YouTube video with a specific start and end time on AMP ?

**Comment by cathyxz** [comment]
I think you can just pass in `start` and `end` params via `data-param-start` and `data-param-end`. 
E.g. 

```
  <amp-youtube width="480" 
               height="270"
               layout="fixed"
               data-param-start="10"
               data-param-end="15"
               data-videoid="lBTCB7yLs8Y">
  </amp-youtube>
```

Sample codepen here: https://codepen.io/cathyxz/pen/XEbBgK

**Comment by cathyxz** [comment]
Closing this issue as resolved. Feel free to reopen if there are further issues.
