### ISSUE TITLE
AMP-sidebar show up on larger screens

### ISSUE THREAD

**Issue by sensaetions** [ampproject/amphtml#13922]
When using AMP-sidebar, the layout required is `nodisplay`. This works great and as expected on smaller screens. But how can I make it so that the sidebar is shown on larger breakpoints? I understand AMP pages are meant for mobile/small screens. But if we're going to use this for a fully responsive site, is it possible and how would we adapt the AMP-sidebar code so that it displays the sidebar at specific breakpoints? Do I need to have 2 separate menus?

Thanks in advance?

**Comment by jpettitt** [comment]
You could use `amp-bind` to control your sidebar by adding/removing classes which would then let you use a media query to force it open on wider screens.  See the "slightly more complex example" on this page https://www.ampproject.org/docs/reference/components/amp-bind

**Comment by cathyxz** [comment]
Another design pattern I've seen is on wider screens, having the menu be in the top bar instead of the side bar. For an example, see the Land and See template here: https://ampstart.com/templates. You could show / hide that based on a media query.

**Comment by aghassemi** [comment]
@sensaetions `amp-sidebar` supports break-point specific `toolbars`. See https://ampstart.com/components#navigation for a sample. You should be able to setup the toolbar to be vertical instead of horizontal with normal CSS mimicking an open-sidebar.

**Comment by aghassemi** [comment]
Closing per comment above.
