### ISSUE TITLE
How to make date-picker fit the small screen

### ISSUE THREAD

**Issue by Jade05** [ampproject/amphtml#13947]
As below, date-picker can't fit the small screen well, such as iphone 5. What should i do to make it performance well? Thank you.

![666666](https://user-images.githubusercontent.com/5029635/37326993-81da2f30-26cf-11e8-9668-82bda37dcab4.png)

**Comment by aghassemi** [comment]
@lswang1618 @cvializ

**Comment by cvializ** [comment]
You can pass the `day-size` attribute and make it smaller than the default https://www.ampproject.org/docs/reference/components/amp-date-picker#day-size
You may want to change the `min-height` of the `.DayPicker_transitionContainer` css class to fit the smaller size due to #13897
