### ISSUE TITLE
Add a LOW-trust `setStyle()` action that only allows non-disruptive styles changes

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#13973]
Currently `amp-animation` is the only way to do this from LOW trust events but it is sort of hacky and undiscoverable to create an animation and play it just to change visibility of an item for instance. `amp-bind` is, by design, not triggerable via LOW trust event.

I believe the following should be allowed to be changes via low-trust actions:
- `visibility`
- `display` of `position: fixed/sticky`
- `transform`
- `opacity`
- ???

/cc @ericlindley-g  @choumx @leonalicious

**Comment by jridgewell** [comment]
`transform` cause style recalc, so it's not very low priority. 

`display` and `opacity` are used to see if a resource is being used, so they also incur runtime costs.

**Comment by aghassemi** [comment]
@jridgewell are changes to `opacity` and `display` auto-detected with layers or we need to signal? ( I guess same with `transform` as it can move something out of view)

**Comment by jridgewell** [comment]
No mutations are auto-detected, everything has to send a signal to layers.

**Comment by aghassemi** [comment]
would signalling layers every rAF be too much? we have low trust events that can trigger every raf (`position-observer`).

**Comment by jridgewell** [comment]
Depending on the layering, absolutely. Say you were to mutate the `transform` of an element in the root layer. Now everything must be invalidated an remeasured.

**Comment by aghassemi** [comment]
I see. Looks like we may need a more granular control over what events can run what actions than just low/high trust.

**Comment by aghassemi** [comment]
this would be nice
