### ISSUE TITLE
Question: Are Resource Hints link rel-tags allowed or not now?

### ISSUE THREAD

**Issue by ayumihamsaki** [ampproject/amphtml#13989]
I am a bit confused here and just need to double check something, are Resource Hints link rel-tags allowed now in amp-html or not? I have read in past issues that some are allowed now and some pass in Validator also. I would like to get confirmation, before I update my amp-html pages.

The way I see it as follows:

1. rel=subresource = Dead don't use
2. rel=prefetch = Can use now
3. rel=dns-prefetch = Can use now
4. rel=preconnect = Can use now
5. rel=prerender = Can use now
6. X-DNS-Prefetch-Control = Can NOT USE
7. Hint probability = Can NOT USE
8. Preload = Can NOT USE

The results from Validator Test is below:

![untitled](https://user-images.githubusercontent.com/17784082/37420525-e50c6ffc-27ae-11e8-9175-967ca206de50.png)

I look forward to comments and please let me know if I am wrong or not with my list. Also if I am right then the following link maybe needing to be updated: https://github.com/ampproject/amphtml/blob/c44a48fbb1dbd0de0b5a9e20f8f69bb920705dde/spec/amp-html-format.md#cust

(Where it says: "rel values registered on microformats.org are allowed. If a rel value is missing from our whitelist, please submit an issue. stylesheet and other values like preconnect, prerender and prefetch that have side effects in the browser are disallowed. There is a special case for fetching stylesheets from whitelisted font providers.")

**Comment by honeybadgerdontcare** [comment]
We're going to allow `as` attribute with `rel=preload` per #13977 and we're also going to allow `http-equiv=x-dns-prefetch-control` per #13928.

**Comment by ayumihamsaki** [comment]
@honeybadgerdontcare Thanks for quick reply, I guess that just leaves the documentation needing to be updated.

**Comment by aghassemi** [comment]
Thanks all, closing the issue as it seems question has been resolved.
