### ISSUE TITLE
Add Full Support for Dublin Core meta-tags

### ISSUE THREAD

**Issue by ayumihamsaki** [ampproject/amphtml#13993]
Hi,

Dublin Core is also part of the [MicroFormats Spec](http://microformats.org/wiki/existing-rel-values#Dublin_Core) and the AMP Project claims to support all the tags etc. with MicroFormats2. I have done a check with the issues and Dublin Core has been added to the AMP project white list but when I did a quick test it fails as you need to add `scheme` attribute, below is the test in Validator:

![untitled](https://user-images.githubusercontent.com/17784082/37422852-23cfcd38-27b4-11e8-90c0-42c09a3734ee.png)

I request `scheme` attribute to be added to the whitelist.

Thanks.

**Comment by Gregable** [comment]
This fix is live.
