### ISSUE TITLE
Proposal: Use `mustache` as template language in amp-story

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#13992]
Our current templating [approach is problematic](https://github.com/ampproject/amphtml/issues/13906).

Benefits:

- Easily statically analyzable.
- Familiar (akin to HTML).
- We can easily plug-in a basic build step (we would *not* do runtime template interpretation).

/cc @newmuis @kristoferbaxter @choumx @jridgewell

**Comment by newmuis** [comment]
Closing this in favor of using the static HTML helper from #14623.
