### ISSUE TITLE
mandatory_atleastoneof attribute spec

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#14006]
Nice-to-have: validate that an element has one or more attributes in a given list. Similar to `mandatory_oneof: "['foo', 'bar']"` but would allow both attributes `foo` and `bar` to exist. 

Name suggestions: `mandatory_atleastoneof`, `mandatory_oneoformore`

Current workaround is to duplicate the tag spec. Context: https://github.com/ampproject/amphtml/issues/12372#issuecomment-372814132

**Comment by alin04** [comment]
How about: `mandatory_anyof`

**Comment by alin04** [comment]
This was merged in https://github.com/ampproject/amphtml/pull/17026

**Comment by choumx** [comment]
Thanks for implementing this!
