### ISSUE TITLE
How to set/change CSS properties from amp-list response

### ISSUE THREAD

**Issue by vamshi5889** [ampproject/amphtml#14018]
Good day All,

Currently I'm working on creating a Product Listing Page (E-Commerce) with AMP. 

As part of this i have a requirement of showing variant options of each product as shown in the picture below (color boxes),
![image](https://user-images.githubusercontent.com/31621020/37465348-e7f7dd0a-2880-11e8-8f5b-dac5cdb0c6f7.png)

I'm getting the color codes (Ex. **#0000FF** for blue) in the response. But i don't know how to set that color code as **background-color** to that boxes because, AMP doesn't support inline styles.

Is there a way to achieve this? Let me know if you need more clarification on the problem i'm facing.

Any help would be really appreciated.
@choumx 

Thanks,
Vamshi

**Comment by vamshi5889** [comment]
I also tried to use SVG's but amp-mustache is blocking SVGs and below is the thread tracked for that.
https://github.com/ampproject/amphtml/issues/1156

**Comment by aghassemi** [comment]
@vamshi5889 Supporting `inline-style` is in the works by @alabiaga as we speak. See https://github.com/ampproject/amphtml/issues/11881 for details.

Until that feature lands, only work-around I can think of is enumerating all possible color values you could have in CSS (if HEX is truly arbitrary then you are out of luck) and setting the class in `amp-list`

**Comment by aghassemi** [comment]
Closing this issue as dup of  #11881.

**Comment by vamshi5889** [comment]
@aghassemi 
I got the work-around you are talking about and will be waiting for the inline feature.

Thanks for the quick response
