### ISSUE TITLE
Hiding elements with data-hide for amp-instagram | feature request

### ISSUE THREAD

**Issue by InDesignWeTrust** [ampproject/amphtml#14012]
The only controllable data attribute seems to be Captions. Can we see more control such as hiding the .Header class?

The amp-instagram embed is broken down really simply. And of course there is no way to select anything.

Will we see this soon? All I want is the ability to hide '.Header'.

**Comment by aghassemi** [comment]
@InDesignWeTrust Thanks for telling us your feature request. Sounds good to me and should be easy to add. Is this something you might be interested in contributing to AMP? We have streamlined contributions setup and guidelines to get started quickly. Here are some step by step details if you like to tackle this:

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.  (If you [join the AMP Project](https://goo.gl/forms/T65peVtfQfEoDWeD3) we'll be able to assign this issue to you after you've claimed it.)
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] [Sign the Contributor License Agreement](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#contributor-license-agreement) before creating a Pull Request.  (If you are contributing code on behalf of a corporation start this process as early as possible.)
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review).  Mention @aghassemi and `closes Issue #14012` in the description. 
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

**Comment by sparhami** [comment]
The content of `<amp-instagram >`is rendered using an embed API from Instagram itself. Since the iframe is a different domain, `<amp-instagram>` cannot change the content inside, other than what the API Instagram exposes.

While the API `<amp-instagram>` uses is slightly different than this one: https://www.instagram.com/developer/embedding/#oembed, they seem to expose similar functionality.  Unfortunately, the only thing exposed seems to be controlling whether or not to show the caption. As a result, I do not think it is possible to hide the header.

**Comment by aghassemi** [comment]
Thanks for investigating @sparhami.

@InDesignWeTrust closing the issue as infeasible until Instagram exposes which API.
