### ISSUE TITLE
amp-ad[type=["adsense"] doesn't work

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#14011]
To whom it may concern:

Hi, I used amp-ad[type=["adsense"] to display an AD section. It used to display an AD section as usual but doesn't  work for these days.

Here comes my code

```
<amp-ad
    class="sponsor"
    type="adsense"
    width="300"
    height="250"
    layout="responsive"
    data-ad-client="ca-pub-5044513083705534"
    data-ad-slot="2765695881">
</amp-ad>
```

You can click the following link and scroll to check it out.
[Demo page](https://blog.lalacube.com/mei/yahoo_mall_item_amp.php?merchandiseId=p0164145230006)

Paul

**Comment by keithwrightbos** [comment]
Hello, this appears to be an AdSense configuration issue.  I suggest you contact support there directly.
