### ISSUE TITLE
amp-img not getting rendered inside amp-list with empty state

### ISSUE THREAD

**Issue by shubagarwal** [ampproject/amphtml#14046]
I am implementing an amp-list containing amp-img with src from amp-state. Following is the code:

```
<amp-state id="cars" [src]="'/api/cars/?id=' + (carId || '')">
    <script type="application/json">
        []
    </script>
</amp-state>
```

```
<amp-list id="car-list" layout="fixed-height" src="cars" [src]="cars" height="0" [height]="200 * cars.length" items=".">
    <template type="amp-mustache">
        <li>
            <h4 class="margin-bottom10">
                <a target="_blank" href="{{Url}}" class="carName">{{CarName}}</a>
            </h4>
            <div class="carThumb">
                <a class="imgholder" target="_blank" href="{{Url}}">
                    <amp-img layout="responsive" width="50" height="50" src="{{HostUrl}}{{^HostUrl}}https://img.cdn.com/{{/HostUrl}}300x300{{ImgPath}}{{^ImgPath}}/grey.gif{{/ImgPath}}" />
                </a>
            </div>
        </li>
    </template>
</amp-list>
```
When I am setting the carId here, the array gets bound in amp-state and the list is rendered. In this list, the carName is visible, but the amp-img is not getting rendered (img tag not getting added in amp-img). What could be the possible reason for this?

I have tried defining the amp-state without empty array like following:

```
<amp-state id="cars" [src]="'/api/cars/?id=' + (carId || '')">
</amp-state>
```
In this case, image is getting rendered but I am getting following error in cosole related to amp-list:

`log.js:162 New renderItems_, continuing render pass...`

What is the cause of this error? What is the correct way to implement this?

**Comment by choumx** [comment]
Oops, that shouldn't be an error. 

I think the general problem is that `amp-list` doesn't wait for `amp-state` to fetch before rendering. You should change `amp-list` to directly fetch the results you want:

```html
<amp-list id="car-list" [src]="'/api/cars/?id=' + (carId || '')">
```

To avoid duplicating this expression, try storing it in an `amp-bind-macro`. 

Related: #11998
