### ISSUE TITLE
I am not able to send AMP carousel in Gmail

### ISSUE THREAD

**Issue by KhushbuAjmera** [ampproject/amphtml#14047]
Can you please explain step by step to send AMP carousel in Gmail. I am refering this link https://www.ampproject.org/docs/reference/components/amp-carousel
I am sending following code in gmail:-

<!doctype html>
<html 4email>
<head>
  <meta charset="utf-8">
  <title>My AMP EMAIL</title>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script async custom-element="amp-carousel" src="https://cdn.ampproject.org/v0/amp-carousel-0.1.js"></script>
  <style amp4email-boilerplate>body{visibility:hidden}</style>
  <style amp-custom>
    h1 {
      margin: 1rem;
    }
  </style>
</head>
<body>
  <h1>Hello, I am an AMP EMAIL!</h1>
    <amp-carousel id="carousel-with-preview"
    width="450"
    height="300"
    layout="responsive"
    type="slides">
    <amp-img src="https://www.w3schools.com/bootstrap/ny.jpg"
      width="450"
      height="300"
      layout="responsive"
      alt="apples"></amp-img>
    <amp-img src="https://www.w3schools.com/bootstrap/chicago.jpg"
      width="450"
      height="300"
      layout="responsive"
      alt="lemons"></amp-img>
    <amp-img src="https://www.w3schools.com/bootstrap/la.jpg"
      width="450"
      height="300"
      layout="responsive"
      alt="blueberries"></amp-img>
  </amp-carousel>
  <div class="carousel-preview">
    <button on="tap:carousel-with-preview.goToSlide(index=0)">
      <amp-img src="https://www.w3schools.com/bootstrap/ny.jpg"
        width="60"
        height="40"
        alt="apples"></amp-img>
    </button>
    <button on="tap:carousel-with-preview.goToSlide(index=1)">
      <amp-img src="https://www.w3schools.com/bootstrap/chicago.jpg"
        width="60"
        height="40"
        alt="lemons"></amp-img>
    </button>
    <button on="tap:carousel-with-preview.goToSlide(index=2)">
      <amp-img src="https://www.w3schools.com/bootstrap/la.jpg"
        width="60"
        height="40"
        alt="blueberries"></amp-img>
    </button>
  </div>
</body>
</html>

But it is not working for me.

Can you guide me step by step if i am missing anything?
Do i need to do any setting?

**Comment by KhushbuAjmera** [comment]
I am stuck in sending carousel AMP mail in gmail. My email is working in AMP playground without any errors, and even working properly in browsers. 
But It is not working in gmail. I am trying hard to implement this example:-
https://www.ampproject.org/docs/reference/components/amp-carousel

Can you guide me where i am missing.

**Comment by choumx** [comment]
Gmail's AMP support is not widely available yet. You can sign up for developer preview here: https://gsuite.google.com/campaigns/index__amp-for-email.html

**Comment by mukulgupta21** [comment]
@choumx The link doesn't redirect to the developer preview page anymore. Do you know the right URL for getting developer access?

**Comment by choumx** [comment]
I think the developer preview is closed now due to a large amount of sign-ups. Keep an eye out for the public beta!
