### ISSUE TITLE
Amp-carousel - allow 2 items to loop

### ISSUE THREAD

**Issue by bjalford** [ampproject/amphtml#14049]
Currently the amp-carousel wont loop when only 2 items in carousel (requires 3+) . Is there a reason it can't be reduced so two items could loop?

**Comment by cathyxz** [comment]
Genius. ^^
I did not think of that.

**Comment by nainar** [comment]
Related to #5164

**Comment by cathyxz** [comment]
Closing this as a dupe of #5164
