### ISSUE TITLE
[Master feature] amp-lightbox-gallery

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#14057]
Feature description:

Currently it's possible to link together amp-image-lightbox or amp-lightbox with amp-carousel, to create a seamless immersive experience for viewing media. However, it's labor-intensive to get that right, and there are a number of barriers to really optimizing that experience for users. This feature is to create a trivial-to-implement, full featured immersive experience for viewing media like images and videos. For example, users can tap on an inline image in the page image (or button to trigger the same experience)—the image expands to full screen with a black scrim behind it, and overlayed affordances to exit the view, to view a related caption, to trigger a grid view to access other media in a given group/carousel in the same immersive view, or to hide the overlays to just view the complete media item.

/cc @cathyxz, can you include links in a list below this line of text to all the GitHub issues/PRs relating to the implementation (or as an alternative, linking via GitHub's built in mechanism by commenting or similar)? Thanks!

Related issues:

Related PRs:

**Comment by aghassemi** [comment]
Fully launched by https://github.com/ampproject/amphtml/pull/15183
