### ISSUE TITLE
gulp lint error when using both --files and --fix

### ISSUE THREAD

**Issue by jonkeller** [ampproject/amphtml#14081]
1. Make an indentation error in a JS source file
2. gulp lint --files=path/to/that/file.js --fix
3. Instead of fixing that file, it creates a new file in the current directory with the same filename, that has the indentation fixed. So you then have to do mv ./file.js path/to/that/file.js in order to get the desired behaviour.

**Comment by rsimha** [comment]
@jonkeller Are you running `gulp lint` from the `amphtml` root directory?

**Comment by jonkeller** [comment]
Yes, I was.
I'm not doing much AMP stuff these days, so if nobody else is seeing this,
feel free to just close.

**Comment by rsimha** [comment]
@jonkeller This is definitely worth fixing. Most people just run `gulp lint --fix` (without `--files`), which works as desired.
