### ISSUE TITLE
only 3 amp-img alone shown in Mozilla firefox.

### ISSUE THREAD

**Issue by elangodhilipan** [ampproject/amphtml#14097]
In my page i'm having the more number of featured images using amp-img tag. but it's rendering the only 3 alone. other thing are not rendered in mozilla firefox 45.0.2. do we have any restriction like that. but it's working fine in chrome. pls help me to Fix this

**Comment by aghassemi** [comment]
@elangodhilipan Could you provide a test page?
Please note that in general we support the latest two versions of major browser, Firefox 45 was released two years ago and latest version of Firefox is 52.

**Comment by elangodhilipan** [comment]
@aghassemi Found a root cause and fix this issue. we are using the amp-img tag without hight and width. now i set the height and width for each amp-img tag. now it's working perfect. thanks for your reply.
