### ISSUE TITLE
document/implement a way for a none amp page to use amp elements

### ISSUE THREAD

**Issue by Nemo64** [ampproject/amphtml#1409]
Basically: not every site is going to be completely amp*(lified?)*. Let's say the detail pages of a Blog are valid amp pages but the index page cannot be an amp page. Either one must drop all amp elements or make the index page an invalid amp page. Both solutions aren't that great. Dropping the amp elements may result in an inconsistent experience and double implementation of elements like carousel.

What I suggest is a planned/documented way to include and use amp elements without the page being completely valid amp-html. I suggest dropping the amp attribute in the `<html ⚡>` element. There should probably still be a validation to ensure correct execution but restrictions like not using javascript should be dropped.

**Comment by cramforce** [comment]
We cannot officially support this. E.g. many optimizations in AMP rely on AMP knowing where everything is on a page and when those positions change. That cannot be known on a general non-AMP web page.
