### ISSUE TITLE
implement alternative to <details> element

### ISSUE THREAD

**Issue by Nemo64** [ampproject/amphtml#1410]
Html5 specifies the [`<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) Element. It isn't [widely supported](http://caniuse.com/#feat=details) and it doesn't look that great, but it is common to have functionality like the [bootstrap collapse](http://getbootstrap.com/javascript/#collapse) on a site.

I suggest an amp element that'll work similar.

```
<amp-details>
    <summary>Click here to see more.</summary>
    <p>This Text isn't initially visible.</p>
</amp-details>
```

This element may simply toggle an css class and let animations and other effects be handled by the author stylesheet (with a simple default stylesheet for `display: none` and `display: block` maybe.)

**Comment by cramforce** [comment]
CC @rudygalfi 
Definitely worth considering. We may, however, build more low level toggling capability.

**Comment by rudygalfi** [comment]
Does #1017 cover this? These seem like similar requests (although this one is much more specific on emulating the <details> element).

**Comment by Nemo64** [comment]
@rudygalfi it seems like it would. I mentioned the `<details>` element because it technically already covers this issue but is a little limited in terms of browser support, styling and usage.

**Comment by rudygalfi** [comment]
Closing since we implemented `amp-accordion` in #1017.

**Comment by westonruter** [comment]
I've opened https://github.com/ampproject/amphtml/pull/18440 to support the `details` element. I couldn't find a stated reason for why it isn't allowed, even though `amp-accordion` is more powerful.

**Comment by cramforce** [comment]
@Gregable pinged me about this. Indeed, I cannot see any conceivable reason why this shouldn't be allowed. Only real downside is non-support in Edge.

**Comment by westonruter** [comment]
I see `details` is marked as being high priority to implement in Edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/status/detailssummary/?q=details

Even so, in Edge support can be done at the author level via some CSS and with an `open` being controllable with `amp-bind`.

**Comment by cramforce** [comment]
Yeah, and it certainly isn't a reason not to support it in AMP.
