### ISSUE TITLE
Add ability to conditionally choose CSS based on experiment group

### ISSUE THREAD

**Issue by istian11** [ampproject/amphtml#14117]
## What's the issue?

When running an AMP experiment, would it be possible to conditionally select from a set of
`<style amp-custom>` tags based on the experiment group? That would allow us to remove unrendered CSS from the page and maximize the amount of used CSS. Currently, we have to remove potentially useful CSS in order to support divergent experiences (in experiment) and stay under the 50K CSS limit.

## How do we reproduce the issue?

This issue comes into play when using the <amp-experiment> element to conduct user experiments.

## What browsers are affected?

All browsers.

## Which AMP version is affected?

The current version is: 1520462477230

**Comment by istian11** [comment]
Looking at the implementation of amp-experiment.js - would it be possible to mutate elements in the `<head>` (i.e., style) in the buildCallback() function?

**Comment by aghassemi** [comment]
/cc @rudygalfi @lannka 

@istian11 Are you suggesting we allow multiple `<style amp-custom>` tags where 50K limit applies to each tag but combination can exceed the 50K limit?

**Comment by istian11** [comment]
@aghassemi The question was more - would it be possible to have multiple `<style amp-custom>` tags (ex. one per experiment group, each with the full 50K limit) and then have the amp-experiments' `buildCallback()` select only one to be parsed? This way, we would not waste computation on needless CSS on the page. Currently, it seems like we need to include all of the CSS needed for the control experience, plus any other variants. In the case of a major change in design or experience, this can lead to a large amount of unused CSS.

**Comment by lannka** [comment]
Instead of bloating a single AMP page with many CSS variations, I'm thinking if this should be an A/B experiment feature in Cache. 

For example, each variation of a page uses URL param or meta tags on the pages to inform the Cache how they like the traffic to be distributed.

@cramforce

**Comment by cramforce** [comment]
Yeah, I think we need a full page A/B testing solution. Just the CSS doesn't make much sense.

**Comment by lannka** [comment]
Sounds like a big project. Shall we approach the Cache team?

**Comment by cramforce** [comment]
It is kind of already on our radar. CC @rudygalfi

**Comment by rudygalfi** [comment]
cc @jeffjose 

@cramforce I just want to confirm: Do you think the cache is the right layer to solve this?

**Comment by cramforce** [comment]
Either AMP Cache or Google Search. L:et's discuss trade-offs offline.

**Comment by lannka** [comment]
Closing this for now as we think it's not a good idea to use amp-experiment for a full page A/B testing.
