### ISSUE TITLE
Support A/B testing (experiments for content)

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#1411]
Provide a way for a publisher to set up experiments in which content on the page is changed according to an experiment group a reader is placed in.

This is forked from an idea proposed in https://github.com/ampproject/amphtml/issues/945#issue-117257061:

> In the future a-b testing can be implemented [using dynamic CSS classes] as well, where we define a way to express rules for how to add such classes and publishers can say e.g. "add test-group-a for 10% of users" or a similar expression.

cc @cramforce @jridgewell

**Comment by rudygalfi** [comment]
@lannka moving this over to you

**Comment by lannka** [comment]
All work done.

**Comment by Gregable** [comment]
Validator rules are live in the AMP Cache and Google Search. They will be live in the developer tools in an hour or two.

**Comment by rudygalfi** [comment]
Woot! Thanks for the update @Gregable.

**Comment by dandv** [comment]
For SEO purposes, here's the documentation on [AMP A/B testing](https://www.ampproject.org/docs/reference/components/amp-experiment). Note that `<amp-experiment>` doesn't show up among Google searches for "AMP A/B testing".

**Comment by cramforce** [comment]
Filed https://github.com/ampproject/amphtml/issues/10421
