### ISSUE TITLE
Don't see empty ads being collapsed

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#1412]
As per https://github.com/ampproject/amphtml/issues/1089 and https://github.com/ampproject/amphtml/pull/1265 

"The amp-ad tag will be collapsed (set to display: none) if the ad sends a message that the ad slot cannot be filled and AMP determines that this operation can be performed without affecting the user's scroll position."

However,

Live page : https://dfp-amp-testing-1185.appspot.com/amp_tests/playground/dfp-iframe-collapse.html

There are two ads on the page. The first one is above the fold (the legit one that returns an ad) and the other one that is in the bottom of the page (before the last set of dummy text) that won't return an ad.

To make sure that the scroll position is not affected by the below ad, I also tried to simulate some lag by adding in some text and a dummy image.

This image highlights this as well : 
https://drive.google.com/file/d/0BzVPXRfYXIOCVWtPTm1teUdBU1U/view?usp=sharing

Thoughts?

**Comment by cramforce** [comment]
The feature isn't fully rolled out yet. Could you go to https://cdn.ampproject.org/experiments.html and opt into "Dev Channel" and then see whether it starts working?

**Comment by jasti** [comment]
Done & works great! CC @kashyapnitin

**Comment by jasti** [comment]
Do you have a GA date for the feature?

**Comment by cramforce** [comment]
Probably tomorrow. Although the heuristic when to update is still subject to some tuning.
