### ISSUE TITLE
Consider modifying AMP Analytics variable htmlAttr to allow collection of element.tagName

### ISSUE THREAD

**Issue by jonkeller** [ampproject/amphtml#14154]
From customer discussions, it is currently anticipated that htmlAttr's CSS selector will be used to specify a single tag type. For instance: ${htmlAttr(img,src,decoding)}

But, there is no reason why this must be so. For instance, it would be possible to specify ${htmlAttr(".someClass",clientWidth)} and apply the CSS class "someClass" to elements of various tag types. In this case, it may be desirable to do something like ${htmlAttr(".someClass",clientWidth,tagName)} to discern the tag types of the returned elements. But, since tagName is not an attribute per se, this would require a small code change.

**Comment by lannka** [comment]
simply adding `tagName` might introduce conflict. We might end up doing something like:

${htmlAttr(.someClass,attr:clientWidth,tagName,innerHTML)}

**Comment by zhouyx** [comment]
Do we still need this? Any update

**Comment by lannka** [comment]
obsolete requirement
