### ISSUE TITLE
<amp-carousel> changes slides randomly on device orientation change in iPhone Chrome

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#14151]
Consistently repros on iOS Chrome (not apparent in Safari). 
Rotate the device from portrait to landscape, slide changes randomly without user swiping or other user interaction. Rotate the device back, the slide changes back. In `<amp-lightbox-gallery>`, rotating the device to landscape mode will cause it to go into hyperspeed autoplay mode.

**Comment by aghassemi** [comment]
to be verified with carousel v2

**Comment by nainar** [comment]
This can't be reproduced with carousel v0.2. Reopen if needed.
