### ISSUE TITLE
Google Analytics AMP Client ID API should support all subdomains

### ISSUE THREAD

**Issue by jamesshannon** [ampproject/amphtml#14156]
The [AMP Client ID API has some subdomain limitations](https://support.google.com/analytics/answer/7486764?hl=en#limitations):

> When AMP pages are published on a different origin from other non-AMP pages you want to use with the Client ID API, the origin of the AMP page and the origin of the non-AMP pages must follow specific rules in order for the Client ID API to work: the host components of both the AMP origin and the canonical origin must be equal, ignoring all m., amp., and www. component prefixes in either host.

This causes issues for some use cases, specifically publishers who split their content amongst branded subdomains. For example, science.howstuffworks.com and auto.howstuffworks.com. This page, served from the AMP cache:

https://science-howstuffworks-com.cdn.ampproject.org/c/s/science.howstuffworks.com/amp/nature/climate-weather/black-ice.htm

Links to other subdomains.

Client ID should work across all subdomains, or be whitelistable by AMP team, or configurable by the developer or GA admin.

(The GA PM suggested that I start with the AMP team for approval / discussion, though I suspect that the GA team will be responsible for actual development.)

**Comment by rudygalfi** [comment]
This is a limitation that we want to remove in the future. No timeline available to say yet. cc @Gregable

**Comment by lannka** [comment]
@Gregable I guess your new proposal would solve this issue?

**Comment by Gregable** [comment]
We hope to resolve this in the future. The constraint to work through is that we don't want `account1.example-shared-host.com` to be required to share identifiers with `account2.example-shared-host.com`.
