### ISSUE TITLE
[FR] Add action to defer/control A2HS dialog

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#14163]
Our recommendation is to [defer Chrome's A2HS](https://developers.google.com/web/fundamentals/app-install-banners/#defer_or_cancel) until after a positive user interaction. This is currently not possible in AMP. It'd be nice to support this via an action, e.g.:

```
<fom on="submit:AMP.showAddToHomescreen()">...</form>
```

If an AMP page uses the showAddToHomescreen action, the A2HS prompt will automatically be deferred until the action is invoked. The action will have no effect if the A2HS prompt has not been triggered yet. If the action is not used, the A2HS prompt will show as before.

We might want to consider providing an option to disable A2HS as well.

**Comment by aghassemi** [comment]
@sebastianbenz So in addition to the action, I assume we need some sort of `meta` tag or doc-level config somewhere to say we should defer A2HS, is that correct?

**Comment by ericlindley-g** [comment]
/cc @danielrozenberg 

This feature sounds great. Can this be done purely in AMP or would it need cooperation from the Chrome browser?

**Comment by aghassemi** [comment]
Based on the [link](https://developers.google.com/web/fundamentals/app-install-banners/#defer_or_cancel) @sebastianbenz send out, looks like it is doable already. 

The approach is pretty interesting IMO, it essentially cancels the browser's prompt just before it is shown and holds a reference to the prompt handle. Later when user interacts, it manually calls `prompt` on the handle.  Interesting pattern!

**Comment by jamesshannon** [comment]
@aghassemi To your question to sebastian, you could either:
a) Have the meta tag / config somewhere, or
b) Decide to defer based on the existence of `AMP.showAddToHomescreen()` which seems to be the suggestion in the OP.

(a) seems much cleaner to me. It would also allow for the outright disabling of the prompt.

**Comment by aghassemi** [comment]
Agree with (a) being a better solution. (b) has some performance implications and seems a bit of magic. (a) will also automatically support the use-case of disabling A2HS altogether as well.

**Comment by sebastianbenz** [comment]
+1 to a)
Ali Ghassemi <notifications@github.com> schrieb am Mi. 21. März 2018 um
20:04:

**Comment by dominickng** [comment]
[Chrome's A2HS maintainer here]

I'll note that sometime in the future, this will become the required pattern for A2HS in Chrome for Android: developers must listen for the `beforeinstallprompt` event, and call `prompt()` on it with a user gesture to show a modal add to home screen prompt (the same prompt as shown via the 3 dot menu). So this seems like a positive development to ensure AMP compatibility with add to home screen.

**Comment by ithinkihaveacat** [comment]
@dominickng Is the `beforeinstallprompt` event re-fired on every page load if `prompt()` is not called? I don't think it will be possible for AMP to save that event across navigations, so if Chrome doesn't re-grant permission, there's a chance it will be lost if the user navigates to a new page.
