### ISSUE TITLE
All of AMP's internal `style` changes should change to setProperty and use !important priority

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#14178]
This is already needed some some components such as amp-story set `!important` in their CSS and will be needed when we allow `inline-style`.

This would require a change to `setStyle` utility (and an audit to make sure all places use `setStyle` instead of doing `element.style[property]`)

/cc @choumx @alabiaga @newmuis

**Comment by jaygray0919** [comment]
when will AMP allow `inline-style`? That's a significant change and would help with, for example, setting a column width for a specific column in a specific table.

**Comment by choumx** [comment]
@jaygray0919 You can follow #14072 to track progress.

**Comment by jridgewell** [comment]
> will be needed when we allow inline-style.

Allowing inline styles should not require any new uses of `!important`.

> This would require a change to setStyle utility (and an audit to make sure all places use setStyle instead of doing element.style[property])

`element.style.prop` and `element.style.prop = 'x'` should already be forbidden.

**Comment by jridgewell** [comment]
Additionally, I'm worried about browser bugs that we'll encounter with this.

For instance, when I [fixed](https://github.com/ampproject/amphtml/pull/11344) a bug with `FixedLayer`'s [interaction](https://github.com/ampproject/amphtml/issues/11340) with `<amp-sticky-ad>`'s `top: 0 !important`, we got a new [bug](https://github.com/ampproject/amphtml/issues/11453) in Safari we can't directly unset `transition: X !important` to go back to the stylesheet value. Instead you have to set it to a non-important valid value, then unset that.

```js
document.body.style.setProperty('transition', '1ms', 'important')

// Cannot directly unset
document.body.style.setProperty('transition', '');
document.body.style.transition; // => 1ms
document.body.style.setProperty('transition', '', 'important');
document.body.style.transition; // => 1ms

// Set to valid non-important
document.body.style.setProperty('transition', 'none');
document.body.style.transition; // => none

// Now unset
document.body.style.setProperty('transition', '');
document.body.style.transition; // => ''

**Comment by alabiaga** [comment]
@jridgewell  Yes, I saw that usage in fixed layer. I reverted the new usage of !important from #14424. Thanks 

> element.style.prop and element.style.prop = 'x' should already be forbidden.

Is this true? the following usage in amp-story-grid-layer.js was not caught

element.style[propertyName] = attribute.value;

and i also tried linting with the following 

`element.style.width` = ...

and it was not flagged..thus this PR #14547. Let me know if i am missing something? Thanks.

**Comment by alabiaga** [comment]
@jridgewell 

nvm. found it.

[15:23:09] Starting 'presubmit'...
[15:23:16] Found forbidden: "style.width = " in extensions/amp-story/0.1/amp-story-grid-layer.js:151:13
[15:23:16] Use setStyle instead!
[15:23:16] ==========
[15:23:20] Please remove these usages or consult with the AMP team.

a presubmit check. A lint check would catch it faster. Thanks
