### ISSUE TITLE
amp-ima-video with hls

### ISSUE THREAD

**Issue by taniabarreira** [ampproject/amphtml#14197]
Hi, 

it's possible run amp-ima-video with mimetype='application/x-mpegURL'?
I try, but show me the message:
"Cannot play media. No decoders for requested formats: application/x-mpegURL"

code for test:
<amp-ima-video id='myVideo' width='640' height='360' layout='responsive'
  data-tag='https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator='
  data-poster='https://ampbyexample.com/img/ima-poster.jpg'>
  <source src='https://amsrr.streaming.mediaservices.windows.net/ed988365-cfb4-4909-93ff-f96530874bc2/rfm_rocky_salteadore78022ab9.ism/manifest(format=m3u8-aapl)' type='application/x-mpegURL'>
</amp-ima-video>

thanks

**Comment by taniabarreira** [comment]
code for test:
<amp-ima-video id='myVideo' width='640' height='360' layout='responsive'
  data-tag='https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator='
  data-poster='https://ampbyexample.com/img/ima-poster.jpg'>
  <source src='https://amsrr.streaming.mediaservices.windows.net/ed988365-cfb4-4909-93ff-f96530874bc2/rfm_rocky_salteadore78022ab9.ism/manifest(format=m3u8-aapl)' type='application/x-mpegURL'>
</amp-ima-video>

**Comment by aghassemi** [comment]
@taniabarreira You would need to use `"application/vnd.apple.mpegurl"` as content type. Make sure to also provide a fallback MP4 for platforms that don't support HLS. See https://ampbyexample.com/components/amp-video/#hls for a sample (it is for `amp-video` but `amp-ima-video` would behave the same)
