### ISSUE TITLE
amp-carousel issues with flex-layout 

### ISSUE THREAD

**Issue by TidyFire** [ampproject/amphtml#14239]
## What's the issue?
issue A.
amp-carousel type="slides" does not scroll out of view on iOS, except when grabbed from controls or when zoomed in. Page scrolling is affected. In this use case the carousel sits at the top of the page and the issue makes the rest of the page unreachable, except if you figure it out and grab from either the right or left arrow control and scroll the page from there. Page scrolling is also possible by grabbing the thumbnail carousel of type="carousel" below the main carousel of type="slides". The only element with z-index is the page header. Hence stacking should not cause this behavior.

issue B. (possibly related)
When scrolling down the images imported using amp-img are often times not loaded. Sometimes tapping on them forces them to load (possibly through focus event?), but sometimes they still won't load. Perhaps this is a scroll position related issue. Hence mentioning it in this context might help in investigating. amp-imgs and amp-youtube inside the carousel always load when the carousel is positioned at the top of the page.

Additional comments: when amp-carousel or amp-youtube with autoplay is at the top of the page, they load as expected and autoplay works. However, if they are positioned outside of first view, autoplay exhibits same behavior as the amp-imgs outside of view: sometimes not starting and/or loading. This is not reproducible with the currently available page as the carousel containing the youtube video is at the top of the page, but could be easily reproduced by placing some placeholder content before the carousel and make it render out of first view. This further supports the assumption of scroll/view position parameters being at the root of these issues.

## How do we reproduce the issue?

issue A.
1. Go to: https://tulipiippu.com/bioSydan-54-kWh/ (or similar product page in that domain)
2. scroll down the page using a non-iOS device
3. repeat with an iOS device or Xcode simulator for iOS to confirm

issue B.
Load the page and reload it a few times if the amp-imgs are showing. The issue should manifest itself with any browser/device in a few (typically less than five) page loads. Tap on the empty image position where it says "NAPAUTA" if you see one, to observe the forced load behavior (not always taking place).

## What browsers are affected?

issue A.
Issue observed with iOS Safari on iPad and Xcode iOS 11.2 simulator for all device types. Other browsers on iOS not tested, but possibly affected as well. Issue confirmed to not exist with Safari on MacOS, Chrome, Edge, Android browser etc.

issue B.
All browsers and devices.

## Which AMP version is affected?

1521658019509

**Comment by TidyFire** [comment]
Any updates on this?

**Comment by aghassemi** [comment]
/to @nainar for triage. First time I've heard of such bug.

**Comment by nainar** [comment]
Hi 

Took a look at this issue:
Both problems are caused by the same issue which is setting a child `<div>` on the `<body>` element to be `position:fixed`, this breaks scrolling on iOS. This is also the reason why everything inside this div (your carousels) isn't loading as the AMP resource manger doesn't know when to load images.

To fix the first issue of not being able to scroll, you can add the following to your `<div>`: `-webkit-overflow-scrolling: touch`. However to fix your image loading problem you would have to stop marking this div as a fixed position container. 

Just to understand things better on our end is there a reason you were marking a parent div container of all content as `position:fixed`?

**Comment by TidyFire** [comment]
Hi, and many thanks nainar. The position:fixed was a legacy of an older off-canvas menu design. I have now experimentally changed it to use positioned flex-layout instead. There are no fixed elements in the page layout anymore, which did fix the iOS scrolling issue, sort of. The image loading and amp-youtube autoplay issues remain. When the amp-youtube video is scrolled up from the amp-carousel, autoplay fails. Not all the time, but sometimes, manifesting the issue just like the image loading one. Both are scroll position-related, I would presume.

UX issue is obvious with the images not being loaded. With amp-youtube autoplay there is a somewhat more complex problem: if the user wants to play the amp-youtube video manually, it requires two clicks, first of which changes the focus context, and prevents page scrolling from the amp-youtube element. Now, the video is not playing and the page appears frozen, as if it has no content below the carousel. This is why autoplay is so important here.

Now that the image load/amp-youtube autoplay issue is not caused by fixed-position ancestors, what could be the underlying problem?

**Comment by TidyFire** [comment]
Hi, I’m wondering why the topic was closed as it was never resolved. The image loading issue is an especially severe one and the attempted fix removing fixed-position elements all together	did not have any effect while the problem remains the same on this part. Should I open a new case for this, or is it just that solution will in any case not be sought after?

Thanks,
Tapani

**Comment by aghassemi** [comment]
Apologies, forgot to link the relevant issue. 

In short, these `position:fixed` issues are all caused by gymnastics AMP has to play to get around iOS's nested scrolling bugs. We have since made many fixes in Webkit code that would allow us to remove these hacks and the Webkit fixes are launching in iOS soon. 

https://github.com/ampproject/amphtml/issues/22220 tracks the progress there and when done, this issue will also be resolved.

**Comment by TidyFire** [comment]
Thanks for the link Ali, but that does not go into solving the current state of my issue, because there are no fixed elements in the layout anymore after the first attempt to solve the problems. Perhaps the title was wrong because the scrolling problem is no longer there, but the image loading issue still remains, regardless of removing all fixed elements. The current layout implementation uses in part display:flex as a way to have the exact same layout without fixed elements, but there are position: relative elements still in there, to be precise. Yet images fail to load and video fails to autoplay. Not always, but still quite consistently.

Best Regards,
Tapani

**Comment by aghassemi** [comment]
Thanks @TidyFire Do you have a Url to share with us that shows the problem?

**Comment by TidyFire** [comment]
Yes of course. The same link that's there for issue A (https://tulipiippu.com/bioSydan-54-kWh/) can be used for issue B as well. You can also use for example https://tulipiippu.com/pellettituli/ and scroll that. It's a bit longer page with more images. You'll see that background images are always loaded, but the small side-images are often left unloaded with the placeholder text "NAPAUTA" remaining there until the user follows the suggestion and clicks on the image. That usually results in all images of the page starting to download, regardless of which images empty position is clicked.

**Comment by TidyFire** [comment]
Correction: clicking anywhere around the page with empty images starts the download up to that, but scrolling further down the remaining images are not always loaded at the end of the page, and the second click in that case does nothing, and the last images are never loaded.
