### ISSUE TITLE
amp-date-picker (date range) shows Null when start date is selected

### ISSUE THREAD

**Issue by rangarajanr** [ampproject/amphtml#14243]
## What's the issue?
The amp-date-picker component shows Null when start date is selected in the date range mode.
You can see this in the AMpByExample page as well
https://ampbyexample.com/components/amp-date-picker/#date-range-picker

## How do we reproduce the issue?
https://ampbyexample.com/components/amp-date-picker/#date-range-picker
In the date range picker, select a start date and the validation text at the bottom continues to read "You picked Null as start date and null as end date".

**Comment by cvializ** [comment]
Should be fixed now. Thanks for reporting!
