### ISSUE TITLE
amp-live-list poll requests can return a disk cache version.

### ISSUE THREAD

**Issue by DavidCramer** [ampproject/amphtml#14278]
## What's the issue?

In certain server configurations, the polled request gets cached by the browser, making each each following request return the cached copy.
<img width="706" alt="screen shot 2018-03-28" src="https://user-images.githubusercontent.com/307466/38030471-fdd3851c-3298-11e8-9fef-15a6c218ebae.png">

## How do we reproduce the issue?

You can try it here: https://dev-ampconfdemo.pantheonsite.io/2018/02/06/are-you-there-lebron-its-me-lebron-a-superstars-ultimate-pep-talk/
If you post a comment before the first request, you'll see a `New Comments` button.
But if you post a Comment after the first poll, it will keep using the initial cached request.

## What browsers are affected?

All browsers.

## Which AMP version is affected?

Not new. since about 1521675336754 - currently not working on 1521658019509

**Comment by jpettitt** [comment]
I can't reproduce on Chrome desktop.

**Comment by erwinmombay** [comment]
@DavidCramer i can repro. I'm taking a look

**Comment by westonruter** [comment]
I should think that that the `amp-live-list` XHR should be issued with `Cache-Control: must-revalidate` perhaps to prevent this from happening?

**Comment by DavidCramer** [comment]
Another simple solution is to have something like `amp_last_check=_timestamp_` added to the poll call. This should solve the caching issue on multiple environments.

**Comment by erwinmombay** [comment]
@DavidCramer the fix caused a

**Comment by westonruter** [comment]
@erwinmombay the issue was just observed on canonical. Forcing `Cache-Control: must-revalidate` in the XHR could be a solution?

**Comment by conwaydev** [comment]
Was just affected by this, are there any work arounds? Heres the headers my page was setting:

![Screen Shot 2019-10-29 at 9 30 28 AM](https://user-images.githubusercontent.com/1868805/67779264-63221e80-fa32-11e9-90c6-f28698606bce.png)

and I can see I was getting disk cache in the network request tab (when disable caching was unchecked):

![Screen Shot 2019-10-29 at 9 30 57 AM](https://user-images.githubusercontent.com/1868805/67779319-7634ee80-fa32-11e9-89c6-c72670a5dd9d.png)
