### ISSUE TITLE
amp-install-serviceworker is not triggering install via iframe within the AMP Cache

### ISSUE THREAD

**Issue by kschmidtdev** [ampproject/amphtml#14288]
## What's the issue?

When viewing an AMP-valid document that contains a configured `amp-install-serviceworker` tag through the AMP Cache, the iframe creation based on `data-iframe-src` is not triggered.

## How do we reproduce the issue?

1. Visit https://progressive--web--scaffold--staging-amp--mobify-com.cdn.ampproject.org/c/s/progressive-web-scaffold-staging.amp-mobify.com/eye-of-newt.html with a mobile user agent
2. Observe in the network tab that no requests related to the service worker install are made (https://staging.merlinspotions.com/sw.html is not requested)
3. Observe no errors in the JS console, nor messages that would occur when SW installation is triggered
4. Observe in the "Application" section of the Chrome DevTools that no service worker install has taken place

Observed on macOS Chrome Version 65.0.3325.162 (Official Build) (64-bit) using a "Pixel 2" user agent via Chrome DevTools 'device toolbar'

## Which AMP version is affected?

The live version as of 2018/04/28 - this was previously working

**Comment by danielrozenberg** [comment]
The new fix for #12473 is in canary. We double checked that the canary doesn't "re-break" this and looks like it works. Thanks again for reporting this issue!

**Comment by kschmidtdev** [comment]
@danielrozenberg Thank you for following up!
