### ISSUE TITLE
amp-mathml component does not size properly in ios/safari in some instances 

### ISSUE THREAD

**Issue by adamsilverstein** [ampproject/amphtml#14282]
### The amp-mathml component does not resize properly after the formula renders, for some formulas in ios/safari  ###

The amp-mathml component renders MathML formulas inline. Behind the scenes, this component renders the formula supplied in the `data-formula` attribute using MathJax. The code waits for the rendering to complete, then resizes the container to match the size of the rendered formula (https://github.com/ampproject/amphtml/blob/9b101fa000b7dc911073cacdf3ccafb187c2012d/3p/mathml.js#L64-L67).

We use this component for AMP pages on FiveThirtyEight.com and one formula we have live in production does not render in safari - on ios or safari desktop. The formula in question does render correctly on android devices and in chrome. Here is the failing formula source possibly useful for a test: `<amp-mathml inline="" layout="container" data-formula="\[4\cdot 10^{69}\]"></amp-mathml>`

## How do we reproduce the issue?

The failing formula is available in production at this URL: https://fivethirtyeight.com/features/are-you-the-perfect-yahtzee-player/amp/ Scroll to the bottom of the page, the last paragraph that begins with _For extra credit,_ you will see the formula rendering chrome, but not safari.

## Screenshots ##

**In chrome** (and android devices) you can see the formula:

![chrome](https://cl.ly/0o3T3w2f0o18/[16ebbe83ac2a569fd7e08425e5c35d21]_Image%202018-03-28%20at%2011.17.44%20AM.png)

**In safari/ios devices**, the formula fails to resize, note the 1 px width:

![](https://cl.ly/3G2C2o0m1x14/[d9bd988af690b11259220f39a2c14d4a]_Image%202018-03-28%20at%2011.20.44%20AM.png)

**manually changing the width**, I see that the formula has actually rendered, its just not showing:

![](https://cl.ly/2j1j0W0y3l1L/[2daf2045d87bc35c649692dec87a1b54]_Image%202018-03-28%20at%2011.22.48%20AM.png)

### Initial Debugging ###

debugging, I see that after the formula renders, the code correctly calls `context.requestResize` with the correct element size (47x16):

![](https://cl.ly/3s3r240T3T3Y/Image%202018-03-28%20at%2011.27.14%20AM.png)

Triggering a postMessage:
![](https://cl.ly/3S272K1l2D1V/Image%202018-03-28%20at%2011.28.49%20AM.png)

The resize itself is what seems to fail, This call fails:

https://github.com/ampproject/amphtml/blob/9b101fa000b7dc911073cacdf3ccafb187c2012d/extensions/amp-mathml/0.1/amp-mathml.js#L61

I haven't quite gotten to the bottom of why the call fails, possibly this is an ios/safari bug?

## What browsers are affected?

ios and mac osx safari, safari developer edition. tested safari 11 and 10 on browserstack devices and both failed. android devices tested work fine, as do chrome browsers.

note that only this formula shows a problem, other formulas render (and resize) correctly in safari/ios.

## Which AMP version is affected?

This is a new issue because the amp-mathml tag is a new feature. Until this was available, we rendered our math formulas in full width amp-iframes. We are now auditing pages containing formulas and this one popped out as failing. we have many other inline formulas now rendered as amp-mathml components including other small formulas like this one, not certain what is unique about this formula that causes it to fail.

**Comment by adamsilverstein** [comment]
Here is an AMP-bin that includes the formula, testing this in safari you will see the for paragraph has the collapsed formula, the second paragraph works fine. Both work fine in chrome.

https://ampb.in/#-L963FSlqSi6acgizdjQ

**Comment by adamsilverstein** [comment]
@aghassemi Do you think this issue is AMP related, or an upstream bug with webkit? Wondering if you have seen any similar issues with other AMP components. Happy to try opening an issue on the webkit repo where I suspect the issue may be.

**Comment by aghassemi** [comment]
@adamsilverstein Interesting! I haven't done a full investigation (on vacation) but I have a feeling it is a race between the `setStyle` in `buildCallback` and `changeSize` in `layoutCallback`. Do you mind giving the following a try:

put the `changeSize` call inside a `mutateElement` block. 

If my intuition if correct, that should resolve it by ensuring `changeSize` is never overridden by the initial width/height

**Comment by adamsilverstein** [comment]
@aghassemi thanks for the suggestion, i'll give that a try. Enjoy your vacation!

**Comment by jaygray0919** [comment]
@adamsilverstein Adam, i'm not quite tracking this new information.

Would you share an example if you are able to align the `inline` MathML with other text in a `<p>`?

The inability to `inline` align is messing up several of our `amp-mathml` documents, such as:
  https://afdsi.org/test/amp_mathml_1/

/jay gray

**Comment by adamsilverstein** [comment]
@jaygray0919 Not exactly sure what the alignment issue you are having is or if our approach solves it. Are you talking vertical alignment with text when displayed inline?

Check this page we have quite a bit of inline formulas here: https://fivethirtyeight.com/features/how-do-you-like-these-rectangles/amp/ - my colleague did the css part if you need more explaination there I can ask.

**Comment by adamsilverstein** [comment]
@aghassemi I gave that a shot in https://github.com/ampproject/amphtml/compare/master...adamsilverstein:fix/mathml-rendering-issue  without any noticeable change. I added the failing test case as well, so if you open the example in that branch in safari you will see the failed render. Please take a look whenever you are back and have some availability. 

Thanks!

**Comment by jaygray0919** [comment]
@adamsilverstein Success.
We put our `<amp-mathml>` in a `<span>` and use your `.amp-formula{width:-webkit-fit-content;width:-moz-fit-content;width:fit-content}`

no more `<sup>`

Thanks to your CSS colleague

/jay gray

**Comment by jaygray0919** [comment]
here's what it looks like now:  https://afdsi.org/test/amp_mathml_1/

as intended. TY for the CSS.

/jay

**Comment by adamsilverstein** [comment]
@jaygray0919 - Good to hear, still haven't figured out why some specific formulas don't render properly, but hope to look at this again once @aghassemi has a chance to review

**Comment by jaygray0919** [comment]
@adamsilverstein we've run into another problem. On our site, this displays properly:
  `<span class="amp-formula"><amp-mathml layout="container" data-formula="\[x\]"></amp-mathml></span>`

But the inline version does not:
  `<span class="amp-formula"><amp-mathml inline="" layout="container" data-formula="\[x\]"></amp-mathml></span>`

On `fivethirtyeight`, we see it working, but it fails on our site. This is a head-scratcher.

**Comment by adamsilverstein** [comment]
@aghassemi when you have a moment, I would appreciate any other ideas you may have for resolving this issue! Happy to try to dig in further if you aren't sure where the issue might be.

**Comment by jaygray0919** [comment]
@adamsilverstein @aghassemi we also want to help improve mathML support, so please tell us what we can do. the post about `\[x\]` is vexing - it displays properly on all mobile browser, but does not display on any desktop browser. Go figure ...

**Comment by jaygray0919** [comment]
Thank you Ali @aghassemi and Adam @adamsilverstein - the modification corrected the problem we had with `\[x\]` which is now correctly rendered here: https://afdsi.org/test/amp_mathml_1/
