### ISSUE TITLE
Sizes should support "calc()" expressions

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#1428]

**Comment by Nemo64** [comment]
a suggestion: Couldn't the `sizes` attribute be converted into a stylesheet?

`sizes="(max-width: 639px) calc(100vw - 30px), calc(50vw - 15px)"` would then be:
```
#elementId { width: calc(50vw - 15px); }
@media (max-width: 639px) {
    #elementId { width: calc(100vw - 30px); }
}
```
That would remove the need to check media queries in javascript.

**Comment by dvoytenko** [comment]
@Nemo64 Yep, this is the most likely implementation here.

**Comment by dvoytenko** [comment]
Stylesheet spun off into #3077.
