### ISSUE TITLE
Allow setting dynamic style on AMP HTML element

### ISSUE THREAD

**Issue by niutech** [ampproject/amphtml#14297]
I want to make a progress bar, which will have its width (progress) from the `style` attribute:

```
<div class="bar">
  <div class="bar-item" style="width: 25%;"></div>
</div>
```

The workaround would be to use `data-width="25%"` and CSS3 [`attr(data-width %)`](https://caniuse.com/css3-attr) method, but it is not supported by any browser.

I suppose the support for `style` is underway in #11881 but is there another solution for now?

**Comment by niutech** [comment]
I found another workaround using `<table>` and `<td width="25%">`, as you can see in [AMP Spectre CSS Framework](https://github.com/niutech/amp-spectre/).

**Comment by choumx** [comment]
Glad you found a workaround! As you mentioned, this is covered by #11881. Closing as dupe.
