### ISSUE TITLE
New variable for INFOnline AMP-Analytics

### ISSUE THREAD

**Issue by ghost** [ampproject/amphtml#14302]
INFOnline extends the measurement tag with an additional variable ("privacy setting") "ps".
Currently the variables "st", "co", "cp" and "url" are available:
https://www.ampproject.org/docs/ads_analytics/analytics-vendors#infonline-/-ivw

The new variable "ps" must be defined with a privacy setting (more information is available in our customer documentation).

**Comment by nainar** [comment]
cc @zhouyx

**Comment by lannka** [comment]
@martinzorn so do you want to update the configuration and introduce `ps`?

**Comment by martinzorn** [comment]
@lannka yes, our customers need "ps" as a new variable, so the configuration needs an update

**Comment by lannka** [comment]
@martinzorn I see. Feel free to send a PR to update this.

**Comment by calebcordry** [comment]
This user has closed their account. If this is still being worked on feel free to reopen. Closing for now.
