### ISSUE TITLE
want to become a Publishers - to earn from my blogs

### ISSUE THREAD

**Issue by CHENNAIBALA** [ampproject/amphtml#14375]
i want to become publisher to earn from Ad networks especially from Google.
i own 10 blogs having combined traffic of about 25000 visitors per day.
how to get added to earn from mobile pages?

thanks
BALA

**Comment by newmuis** [comment]
Hello, using AMP doesn't require being added to anything; you can get started using the documentation from https://www.ampproject.org/learn/overview/.
