### ISSUE TITLE
Refactor resources manager to a manageable size

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1438]
I think we can start by maybe splitting the mutate/resize VS. layout concern?

The file is too large to understand. And it needs a diagram :)

**Comment by dvoytenko** [comment]
I'd like to switch it to simply manage tasks and move all implementations out.

**Comment by adelinamart** [comment]
Is this still relevant?

**Comment by jridgewell** [comment]
This'll be taken care of as part of the Layers refactor.

**Comment by adelinamart** [comment]
@jridgewell  You are are working on this? what's the issue that refers to 'layers refactor'? Thanks

**Comment by jridgewell** [comment]
https://github.com/ampproject/amphtml/issues/3434
