### ISSUE TITLE
Hidden Parts of Images with <amp-image-lightbox>

### ISSUE THREAD

**Issue by IamAlta** [ampproject/amphtml#14385]
**## What's the issue?**
Cutting Off Image with <amp-image-lightbox. 
It seems that i-amphtml-sizer is _one culprit and returning a too low padding-top percentage.
Increase the percentage, the image is okay vertically, but is still cut off to the right (see below). So, there must be something else going on.

**## How do we reproduce the issue?**
A **bug**. Public URL.
  
**TEST PAGE WITH TALL IMAGE**
https://www.gardecor.com/amp.demoGithub.php
i-amphtml-sizer original padding-top is 109.6% on a 919px wide browser.
In developer tools, change the padding-top to 189% and the image shows okay.

**TEST PAGE WITH SQUARE IMAGE**
https://www.gardecor.com/amp.demoGithub-SQIMG.php
The caption is cut off.
This can work but the image is too short for a quality image to present to users. (I have tens of thousands of images to reprocess if there is no remedy.)

While you're looking at this issue, can you please offer a fix for the following:
Notice the the right is cut off. This demo has a shadow that isn't showing on the right.

**## What browsers are affected?**
Desktop: Chrome, IE, Firefox
Tablet: Samsung Android 4.4.2
Haven't tested smartphones or other tablets.

**## Which AMP version is affected?**
AMP ⚡ HTML – Version 1522350285886
Always broken.

I love what you've done so far and look forward to having this fixed.
Make it a wonderful day! You ALL deserve it.

**Comment by cathyxz** [comment]
Hi @IamAlta, thanks for reporting! Sorry, I'm a bit confused by the title of your bug vs. what you're describing. 

In your demo urls, I'm not observing that any of the images are cut off when opened in the `<amp-image-lightbox>`. They are all showing as filling the viewport in their natural aspect ratio. 
I am observing that in your test page with tall image, the tall image is being cut off while being displayed in the `<amp-carousel>`. Some of the captions are also not displaying inside the `<amp-carousel>`. 

Are you trying to correctly size `<amp-img>` with layout responsive in `<amp-carousel>` or are you trying to crop/hide parts of images opened inside `<amp-image-lightbox>`?

**Comment by IamAlta** [comment]
Hi @cathyxz,
That was fast!
I am not trying to crop, just display the full image.
After I got your reply, it sent me in a new direction of thinking and I found the issue. The width/height params for the <amp-carousel> tag were taken from the last thumbnail, not the primary image.

Thanks! You can close this :)

**Comment by IamAlta** [comment]
Hi @cathyxz,
Oh, but wait a minute. The thumbnails get distorted when I click on one and it shows up.
Is there a fix for that?

**Comment by cathyxz** [comment]
Based on your code here: https://www.gardecor.com/amp.demoGithub.php
It seems like the current implementation that I'm seeing has the same width / height values specified for all`<amp-img>`s in the `<amp-carousel>`. But on inspection, their natural widths and heights are not the same. I don't know what you mean by the thumbnails getting distorted, but if you're talking about the `<amp-img>` inside `<amp-carousel>` being distorted, it is probably because their width and height values are set incorrectly. 

```
<amp-carousel id="carousel-with-preview" width="411" height="700" layout="responsive" type="slides">
   <figure class="overflow-hidden right">
     <amp-image-lightbox id="primimg449" layout="nodisplay"></amp-image-lightbox>
     <amp-img src="/media/images/product_xlarge/sc-5329F2BLg.jpg?image=10" width="411" height="700" class="border shadow" tabindex="0" layout=responsive alt="Tall Regatta Bubbler" on="tap:primimg449" role="button"></amp-img>
     <figcaption class="h7 center bold">Tap to enlarge</figcaption>
  </figure>
  <figure class="overflow-hidden right">
     <amp-image-lightbox id="primimg2107" layout="nodisplay"></amp-image-lightbox>
     <amp-img src="/media/images/gallery/sc-5329F2B-galleryLg.jpg?image=11" width="411" height="700" class="border shadow" tabindex="0" layout=responsive alt="Tall Regatta Bubbler" on="tap:primimg2107" role="button"></amp-img>
     <figcaption class="h7 center bold">Tap to enlarge</figcaption>
  </figure>
  <figure class="overflow-hidden right">
     <amp-image-lightbox id="primimg374" layout="nodisplay"></amp-image-lightbox>
     <amp-img src="/media/images/gallery/sc-5329F2B-gallery2Lg.jpg?image=12" width="411" height="700" class="border shadow" tabindex="0" layout=responsive alt="Tall Regatta Bubbler" on="tap:primimg374" role="button"></amp-img>
     <figcaption class="h7 center bold">Tap to enlarge</figcaption>
  </figure>
   </amp-carousel>

```
By the way, you should only need one `<amp-image-lightbox>` element. You should be able to set all of the on="tap:uniqueLightboxId" to the id of the same `<amp-image-lightbox>`.

**Comment by IamAlta** [comment]
Hi @cathyxz,
Thank you for your time. After your explanations and questions, I think I understand it now.
Phew! I'm glad it wasn't amp and just how the code was written.

**Comment by cathyxz** [comment]
No worries. For questions like this, feel free to send in a codepen and ping us on slack. You may get faster responses there. =)

**Comment by IamAlta** [comment]
Hi @cathyxz,
There seems to be something odd with the enlarging of the image once it's in the lightbox - it doesn't work for the third thumbnail, the one on the far right. I tried it with 4 thumbnails and the last 2 didn't work. Only the first two thumbnails, when put into the lightbox will enlarge.

Demo
https://www.gardecor.com/amp.demoGithub.php

Do this
Click the middle thumbnail and it shows up in the i-amphtml-slides-container.
Click it and lightbox works - it gets larger.
Close it (click outside the image).

Then, click the right thumbnail and it shows in the i-amphtml-slides-container.
Click the image in i-amphtml-slides-container and watch what happens. 
It disappears for me. 

Click another thumbnail and I see a black screen.

Any ideas on that?

**Comment by IamAlta** [comment]
All ok!
