### ISSUE TITLE
amp-date-picker: can't set initial-start-date value as expected

### ISSUE THREAD

**Issue by Jade05** [ampproject/amphtml#14408]
Description:

When i use amp-date-picker with fullscreen property， I can't set initial-start-date and initial-end-date value as expected.

![date-picker-issue](https://user-images.githubusercontent.com/5029635/38301459-2972eb4c-3832-11e8-9f2e-c6f1e22ed42e.png)

![date-picker-i-2](https://user-images.githubusercontent.com/5029635/38301462-2e74177e-3832-11e8-9c68-0ac159463bb0.png)

As shown above, the dates (4th Apr and 5th Apr) are not chosen in the page though initial-start-date and initial-end-date have been set.

**Comment by cvializ** [comment]
Looks like a missed requirement. I am not sure how this specific feature should work in the context of a cached AMP document, since setting the initial start date to a specific date would keep it that way on the cache until the document is invalidated. I may add it to the JSON API instead.
