### ISSUE TITLE
Adding syntax highlight element

### ISSUE THREAD

**Issue by caraya** [ampproject/amphtml#14425]
I am using AMP via Wordpress and the wp-amp plugin. I use Prism.js (via plugin) to do syntax highlight. This works in the regular Wordpress render but not when used through AMP. 

In amphtml/#2412 @cramforce mentions that this should be done server side. We still need the tool to do so, either in the amp cache or via an element that caches the JS and CSS for the fences. 

Using amp-gist (amphtml/#8580) is not an option as some of my posts have 15 or more code examples. The plugin website closed an issue requesting syntax highlighting (amp-wp/#972)

**Comment by westonruter** [comment]
The solution is to use a WordPress plugin that does server-side highlighting via PHP instead of client-side highlighting via JS. I don't see there being anything required on the AMP side. See https://github.com/Automattic/amp-wp/issues/972#issuecomment-378709345

**Comment by caraya** [comment]
My case uses Wordpress. Other users may or may not. The solution is still needed whether in Wordpruoyor not... Until there is a solution that works throughout potential ecosystems particularly if you want to claim parity with non-amp content.

**Comment by cramforce** [comment]
I wouldn't be opposed to adding this if the highlighting does nothing but add color.

**Comment by watilde** [comment]
As some people mentioned that there are some workarounds, but I was wondering the same idea.

**Comment by aghassemi** [comment]
doing this client-side is borderline against AMP UX principles. I don't think we would develop such extension. SSR is the right, performant approach.

**Comment by caraya** [comment]
If that's the case, @aghassemi, can you provide a solution or pointers to such a solution?

**Comment by aghassemi** [comment]
@caraya any syntax highlighting tool that can run server-side would do. Actually Prism.js can do that and they even mention AMP as one of the cases where SSR is needed"

from: https://prismjs.com/
> If you want to use Prism on the server or through the command line, Prism can be used with Node.js as well. This might be useful if you're trying to generate static HTML pages with highlighted code for environments that don't support browser-side JS, like <a href="https://www.ampproject.org/">AMP pages

**Comment by westonruter** [comment]
If using PHP on your site, you can use highlight.php: https://github.com/scrivo/highlight.php

**Comment by caraya** [comment]
@aghassemi  OK, whatever. 

It says it can't be done but not how. I'll keep looking and work trying to figure out how.  

@westonruter This is not for PHP or WordPress.
