### ISSUE TITLE
Allow apikey.pub to be placed on paths/subdirectories e.g. https://example.com/path/

### ISSUE THREAD

**Issue by mfahadi** [ampproject/amphtml#14422]
## What's the issue?

For cache update to work one must have a public key on site with this exact location on site `https://example.com/.well-known/amphtml/apikey.pub`

The address of our site is like `https://example.com/path/`, the `example.com` domain points to another site and the `/path` is deployed separately. So in this scenario how can I update/refresh cache as I cannot host the public key at the location required by Google.

I would like to host the key at this address, `https://example.com/path/.well-known/amphtml/apikey.pub`

[Cache-Update link](https://developers.google.com/amp/cache/update-cache)

Asked this [question ](https://stackoverflow.com/q/49616219/3105612)on stackoverflow but did not get any info so posting here.

## How do we reproduce the issue?

Host a site on a path or sub directory and try to update cache by hosting public key on a location on a path like `https://example.com/path/.well-known/amphtml/apikey.pub`

## What browsers are affected?

Browser does not matter.

## Which AMP version is affected?

AMP version does not matter.

**Comment by Gregable** [comment]
Closing bug as this is an AMP Cache specific. That project is tracking at `b/113541052`
