### ISSUE TITLE
<amp-social-share> module doesn't work now

### ISSUE THREAD

**Issue by ayumihamsaki** [ampproject/amphtml#14442]
Hello,

I had this module installed for over a year now all working fine and now it is not working due to someone changing the Javascript file found here:

https://github.com/ampproject/amphtml/blob/master/extensions/amp-social-share/0.1/amp-social-share.js

Someone has changed the css in the Javascript file to say: `display: none;`

Is it possible for someone to change it back to: `display: inline-block;` then it will work again.

See here on a production website (Error):

![error](https://user-images.githubusercontent.com/17784082/38385070-caf66cc4-3908-11e8-80e7-0ac825b4c610.png)

See here on a production website (No Error):

![working](https://user-images.githubusercontent.com/17784082/38385065-c5ff7ad0-3908-11e8-90ac-1a29ff0c837c.png)

Note: CSS coming from the "element.style" so its definitely being served from the Javascript module.

**Comment by nainar** [comment]
Hi just looking at the history of the commits to the page: https://github.com/ampproject/amphtml/commits/master/extensions/amp-social-share/0.1/amp-social-share.js the change was made over a year ago. Could you provide a demo link so that we can triage it better?

**Comment by newmuis** [comment]
For native sharing (`type="system"`), the component is hidden on platform where native sharing is not supported:

**Comment by ayumihamsaki** [comment]
@nainar @newmuis Thank you for your replies.

I still got the meta-tag in the background saying:

`origin-trial data-feature="Web Share" data-expires="2017-04-17"`

I think the problem is that I am using Google Canary and it crashed and so I had to reinstall it, but I have not turned on the experiment to run it in the Google Canary Browser.

However, there is an issue with you setting the Javascript up like that, because I am using a fallback url written in PHP Laravel. My basic setup does this:

1. Test to see if the device is an Andriod Mobile Device Browser and run the normal Web Share API.
2. If not then use a Fallback URL which goes to Twitter Share Page.

The issue is that you can not turn off the Web Share API like that for the following two reasons:

1. The Web Share API uses Fallback URL's which is stated in the Spec.
2. Adding a CSS wraper to turn off the display none is not working as the Javascript module is overriding it.

Link to CanIuse webshare: https://www.caniuse.com/#search=web%20share

Because support is so bad still for WebShare API. I really ask to remove the display: none and allow Fallback URL's.

Let me know your thoughts on this.

p.s. I rather not share my website url for now. But if it will help this issue I can share the link to the amp part of the website though it is an adult website. So this is my reason for not sharing a link straight away.

**Comment by ayumihamsaki** [comment]
Hi,

I think I might put a wrapper around the `<amp-social-share>` and only display it when a user loads an Android device. But I feel this is not the ideal solution as `<amp-social-share>` is currently blocking the Fallback URL from working by setting a `display:none;` and also the extra code to create the wrapper I feel will not work when Google caches the amp webpage(s) on their CDN.

~ Will leave this issue for the experts here to decide and if you decide not to change the module code, then please feel free to close this issue, thanks.

**Comment by ayumihamsaki** [comment]
Closing this issue, as I looked into the code and I was using an outdated version of the `<amp-social-share>`
