### ISSUE TITLE
New extension: image slider

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#1445]
The thing described here: http://www.poynter.org/2014/whats-the-deal-with-buzzfeeds-slide-things/258436/

**Comment by rudygalfi** [comment]
@ericlindley-g I think we should prioritize this as part of our data journalism workstream.

**Comment by ericlindley-g** [comment]
Agreed—will keep that in mind as those priorities take shape

**Comment by luigi** [comment]
I'd like to try implementing this. At Vox Media, here's what our version of this looks like:

http://www.theverge.com/2017/2/22/14703712/tesla-supercharger-growth-model-usa-canada-mexico

**Comment by ericlindley-g** [comment]
Hey @luigi  — sorry we missed your comment here!

FYI that @alannawalton is working on this feature here: https://github.com/ampproject/amphtml/pull/10559

Might be worth sync'ing to get on the same page w/r/t requirements & ability to customize

@aghassemi @rudygalfi for visibility

**Comment by ericlindley-g** [comment]
@luigi  — do you have any details about what aspects of the interaction you'd like to be able to customize (like the dividing line), or anything that might not be obvious from checking out the interaction in the link?

Thanks!

**Comment by cathyxz** [comment]
This has been done with the launch of `<amp-image-slider>`.
