### ISSUE TITLE
Validator error when using custom URI schemes

### ISSUE THREAD

**Issue by jamescridland** [ampproject/amphtml#14486]
This issue is about custom url schemes, similar to #4242, #4094, #4784 and #5071.

The validator throws an error when linking to a shared calendar (using the webcal:// scheme).
It also throws an error when linking to a specific podcast app (using the breaker:// scheme).

The errors are similar to:

`Invalid URL protocol 'webcal:' for attribute 'href' in tag 'a'.`

It looks as if similar schemes have been added to a whitelist. Webcal, certainly, would appear to be a contender for that.

Alternatively, I've discovered a relatively simple workaround is to link to a 301 redirect. Thus [https://podnews.net/protocol-switch/webcal:/podnews.net/events/ical](https://podnews.net/protocol-switch/webcal:/podnews.net/events/ical) will pass the validator, and will also work - as long as the OS understands the scheme, of course. In the case of webcal://, it's supported by Windows, OSX, iOS, and Chrome OS. (Little green robot operating systems, sadly, must go without.)

**Comment by honeybadgerdontcare** [comment]
We do [whitelist](https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii#L1528) some commonly seen protocols. Are you interested in having `webcal` and `breaker` added to that whitelist?

**Comment by jamescridland** [comment]
I think webcal would make sense to whitelist, given it is relatively well used.

I'd leave breaker up to you; I can't really think it works to have every single strange app's random protocols whitelisted. I don't quite know why you're whitelisting, to be honest - but there we are... :)
