### ISSUE TITLE
amp-date-picker: "Layout not supported: fill" error occurs on some browsers

### ISSUE THREAD

**Issue by Jade05** [ampproject/amphtml#14484]
#### Environment：
win7 chrome62

#### Desription:
amp-date-picker throws an error with "Layout not supported: fill" on some browsers. 
![filled](https://user-images.githubusercontent.com/5029635/38462275-de964f8c-3b16-11e8-8a03-570a749254db.png)

I use amp-date-picker like the following: 
```html
<amp-lightbox id='datelb' layout='nodisplay' scrollable>
  <div class='icon-common-close lightbox-close'
    on='tap:datelb.close'
    role
    tabindex='0'></div>
  <div id='bs-date'>
    <amp-date-picker id='range-date-picker'
      class='date-picker'
      on='
        activate: datelb.open;
        deactivate: datelb.close;
        select:AMP.setState({
          date: {
            selectedStartDate: event.dates[0].date,
            selectedEndDate: event.dates[event.dates.length - 1].date,
            nights: event.dates.length > 1 ? event.dates.length - 1 : 0
          }
        })'
      format='Y-MM-DD'
      week-day-format='dd'
      month-format='MMM'
      layout='fill'
      fullscreen
      orientation='verticalScrollable'
      locale='<%- dateData.locale %>'
      type='range'
      initial-start-date='<%- dateData.checkin %>'
      initial-end-date='<%- dateData.checkout %>'
      number-of-months='12'>
    </amp-date-picker>
  </div>
</amp-lightbox>
```

You can visit [our web](https://m.trip.com/) directly to check. Thank you.

**Comment by cvializ** [comment]
I cannot reproduce today. Are you still able to reproduce?

**Comment by Jade05** [comment]
@cvializ 

Yes. 
According to our testing, this error can't be reproduced on chrome of mac but windows. The Enviroment is chrome62, win7.

When it is ok, the date can open expectedly

![s1](https://user-images.githubusercontent.com/5029635/38848029-594e5c84-4237-11e8-94de-662554eeb1f8.png)

or,
![f1](https://user-images.githubusercontent.com/5029635/38848050-79fef9d4-4237-11e8-82dc-79f3fbf93a89.png)

It seems layout="fill" is set unsuccessfully.

**Comment by cvializ** [comment]
I do see consistently see incorrect behavior in the "flights" page in Chrome 62 / Windows 7. I could not reproduce in Chrome 63 , 64 or 65. However AMP's browser support policy is the previous two major versions of modern browsers, and Chrome 62 is no longer supported. If you see the incorrect behavior in a supported version of Chrome we can reopen this. Thanks for reporting and providing the detailed description!

**Comment by Jade05** [comment]
@cvializ Thanks. The problem has been solved.

**Comment by cvializ** [comment]
Ah excellent, Service Workers can be tricky that way. Thanks for the follow up!
