### ISSUE TITLE
amp-state cannot change the input property value

### ISSUE THREAD

**Issue by Alucelx** [ampproject/amphtml#14514]
## What's the issue?
while i use amp-state and bind a state property on input:text's value, first i input some words, then i click the button to clean the word, but it dosent work.

## How do we reproduce the issue?

open the test url <a>http://jsbin.com/bavacujohu/edit?html,output<a> and follow the steps
1. input any words in input:text or click `Set state` button;
2. click `Get Property value` and `Get Attribute value` to compare;
3. click the `Clear` button to clear the text and you cannot see any change with the action;
4. click `Get Property value` and `Get Attribute value` to compare again;

## What browsers are affected?

chrome 60, simulate as mobile device

## Which AMP version is affected?

AMP version maybe is v0.1 that i get in docs of ampproject.org.

**Comment by choumx** [comment]
Must be a bug -- thanks for reporting this. You can try replacing with a whitespace char instead in the meantime.

**Comment by dnlnav** [comment]
having the same issue, whether `state.var` is an empty string or a whitespace char
