### ISSUE TITLE
Fetch all resources from same origin as v0.js when self-hosting

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amphtml#14527]
AMP loads some JS resources dynamically. For example, in some cases the runtime loads `https://cdn.ampproject.org/rtv/011522422854768/v0/amp-crypto-polyfill-0.1.js` even though this resource is not directly referenced from the AMP itself via `<script src="...">`.

The location of this resource seems to be hardcoded to `https://cdn.ampproject.org/`—even if `v0.js` is self-hosted (e.g. at `https://example.com/amp/v0.js`), it is retrieved from `cdn.ampproject.org`. (The location may be configurable via `AMP_CONFIG`, but I'm not sure what to change this to, or how to modify it at build time.)

It would be helpful if this file were retrieved from the same origin as `v0.js`, and also if the URL was not "versioned" unless `v0.js` itself is. Changing this behavior would support use cases such as rendering AMP files completely offline (no unexpected network requests), various AMP SSR setups, and enabling 3P AMP caches.

**Actual behavior:**

Resources are retrieved from `cdn.ampproject.org`, even if `v0.js` is hosted elsewhere.  (Example: "Fetch as Google" in Google Search console; this may load `amp-crypto-polyfill-0.1.js` since Googlebot apparently doesn't support some crypto features.)

**Expected behavior:**

All resources are retrieved from same origin as `v0.js`.

**Comment by mattwomple** [comment]
I missed this issue when I created #24927. I have two PRs that aim to address this issue.

- PR #25026 brings amphtml's extension URL generation in-line with amp-toolbox/optimizer.
- PR #25028 adds support for updating AMP.config.urls in singleDoc mode.

The topic is planned for discussion in design review #25447.

**Comment by ithinkihaveacat** [comment]
@mattwomple https://github.com/ampproject/amphtml/issues/25137 is another example of a resource being loaded dynamically by the runtime. (Might be addressed by your fixes.)
