### ISSUE TITLE
amp-img with layout intrinsic renders with wrong aspect ratio

### ISSUE THREAD

**Issue by auxsoft** [ampproject/amphtml#14524]
## What's the issue?

It seems that an amp-img with layout=intrinsic has a wrong aspect ratio.

## How do we reproduce the issue?
https://codepen.io/anon/pen/XEOQmo

In this example the image is 31x31 but renders 31x35

## What browsers are affected?
I tested on desktop Chrome and Firefox.

## Which AMP version is affected?
Version 1522422854768

I think the svg img sizer should have block display. This solves the problem:

`
.i-amphtml-intrinsic-sizer {
    max-width: 100%;
    display: block;
}
`

**Comment by aghassemi** [comment]
I think `i-amphtml-intrinsic-sizer` class needs a `display:block`

**Comment by jpettitt** [comment]
Agree - adding it.
