### ISSUE TITLE
Range type amp-date-picker: cann't keep the selected state when choosing a larger date

### ISSUE THREAD

**Issue by Jade05** [ampproject/amphtml#14569]
Hi, when i use amp-date-picker with range type, I find a little thing that can be improved.

For example,

#### When i choose 1st May and 10th May, the area from 1st May to 10th May is marked selected as below:

![date1](https://user-images.githubusercontent.com/5029635/38658898-9214ea7e-3e59-11e8-89a4-0b35803e3403.jpg)

#### Then, if I choose 30th Apr(a smaller date), the previous selected dates keep selected :

![date3](https://user-images.githubusercontent.com/5029635/38659000-fc4864e8-3e59-11e8-8c8e-4a482c652871.jpg)

#### But if 11th May(a larger date) is selected instead, the previous selected dates are cancelled.

![date2](https://user-images.githubusercontent.com/5029635/38659075-51c1ea0c-3e5a-11e8-9813-45cc1f1a07e9.jpg)

It is not a bug but we hope the interaction can keep consistency :）or it seems confused. Thanks.

**Comment by cvializ** [comment]
I did a small repro and, at least at this point, the behavior you describe is what's implemented. I have a demo at https://ampb.in/#-LFZ8j5Wc1Qvx6HtxNJ4 that shows if you click on the end date, you can choose an end date farther in the future and select a larger range. I will close this issue for now. Thank you for reporting!
