### ISSUE TITLE
gulp test --files does not work for test/functional/test-cid

### ISSUE THREAD

**Issue by RJSumi** [ampproject/amphtml#14562]
## What's the issue?

Using the --files flag for test/functional/test-cid produces spurious unit test breakages.  .only works, but gives a much slower startup time.

## How do we reproduce the issue?

gulp test --files=test/functional/test-cid.js --watch

## What browsers are affected?

N/A

## Which AMP version is affected?

This is a testing issue; no specific version of AMP is affected.

**Comment by choumx** [comment]
I don't experience this locally. Also you can use `--nobuild` for unit tests for a much faster run.

**Comment by rsimha** [comment]
Also, can you post a gist of the spurious unit test breakages? How slow is the startup time, and where does it look like it's waiting? Are you fully synced to `HEAD`? (There have been a bunch of test infra changes over the past couple days.)

**Comment by rsimha** [comment]
Closing this. Please reopen if issues persist after you try what's in https://github.com/ampproject/amphtml/issues/14562#issuecomment-380930563
