### ISSUE TITLE
Story-level background-audio should be paused during advertisements

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#14572]
Whenever an advertisement is active, story-level background audio should be paused.  Once the advertisement is no longer active, the background audio may be resumed.

/cc @jasti

**Comment by jasti** [comment]
I guess this is already not working in publisher served ads? i.e the audio continues to play even during the ad?

**Comment by newmuis** [comment]
I haven't tested this, but don't recall any code to handle this being written, so I think you are correct.

**Comment by calebcordry** [comment]
working on a fix in #14869
