### ISSUE TITLE
Write documentation for upgrading amp-story to new version

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#14573]
There will be format specification differences between versions 0.1 and 1.0 of amp-story.  Although [amp-story.md](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/amp-story.md) should always have complete documentation for the latest version, we should also consider writing documentation specifically targeted at those already using 0.1 who wish to upgrade to 1.0.

**Comment by Enriqe** [comment]
can be closed by #15465
