### ISSUE TITLE
Fail/warn on tests that use `allowConsoleError` but don't actually call `console.error`

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#14587]
Followup to #7381. Now that we fail (or for now, warn) on tests that call `console.error` without expecting it, we should prevent test writers from being overzealous with `allowConsoleError(() => { … });` - this method should fail or warn on the test if the code inside it does _not_ call `console.error`.

This can help us avoid tests that technically pass, but do nothing, because the code behind them is failing in a different way than just expecting a console error

**Comment by rsimha** [comment]
Good call on filing this. There are several tests that don't really need `allowConsoleError`, and this should help weed out the unnecessary uses.

Search https://gist.github.com/rsimha/1fd65d747250f8e84531432eb5e740b9 for `contains an "allowConsoleError" block that didn't result in a call to console.error`.
