### ISSUE TITLE
amp-sticky-ad sticky is not working with html

### ISSUE THREAD

**Issue by NithishReddy** [ampproject/amphtml#14608]
custom html in  amp-sticky-ad is not working after google update it's amp-sticky-library, before update it's working fine.
`<amp-sticky-ad layout="nodisplay">
  <amp-ad width="0" height="200" type="doubleclick" layout="responsive">
            <div>
                Sticky ad
            </div>
        </div>
    </div>
  </amp-ad>
</amp-sticky-ad>`

Any help?

**Comment by jpettitt** [comment]
`amp-sticky-ad` can only have one child element which must be `amp-ad` you can however use `:before` or `:after` CSS to add tag text above or below the `amp-ad` tag.

````CSS
    amp-sticky-ad:after {
      content: 'Hello World';
    }
````

![image](https://user-images.githubusercontent.com/524856/38815273-67ac1734-4148-11e8-9f6a-b638432ca40d.png)
