### ISSUE TITLE
amp-ad data-enable-refresh does not work in Safari

### ISSUE THREAD

**Issue by lgrrealag** [ampproject/amphtml#14612]
Enabling ad refresh on a sticky ad works fine with Chrome on Android, however it does not work appear to with Safari and Chome on iOS.

<amp-sticky-ad layout="nodisplay">
	<amp-ad width=320 height=50
		type="doubleclick"
		data-slot="doubleclick-ad-slot"
		data-enable-refresh="30">
	</amp-ad>
</amp-sticky-ad>

In Chrome on Android the ad slot refreshes every 30 seconds with a new ad. In Safari the ad loads once and never refreshes.

Is this feature just not available on Safari on iOS yet?

How do we reproduce the issue?
This appears on all the bottom sticky ads on https://amptest.realagriculture.com
Visiting using Safari should reproduce this or Chrome on iOS. Chome visitors on Android see a refreshed ad slot.

What browsers are affected?
Safari, iOS and Mac desktop, Chrome iOS.

Which AMP version is affected?
Powered by AMP ⚡ HTML – Version 1522422854768

**Comment by lannka** [comment]
+ @glevitzky to take a look
