### ISSUE TITLE
Is it possible to add method play on <amp-audio>

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#14629]
To whom it may concern:

I like to add some sound effect when some element has been tapped.  I wonder is it possible to add method play on &lt;amp-audio&gt;, so I could take control when to play it.

Sample code:
```
<amp-audio id="sound-like" layout="nodisplay" src="sound/likeit.mp3" preload>
    <source type="audio/mpeg" src="sound/likeit.mp3">
</amp-audio>

<a class="trigger_for_play" on="tap:sound-like.play">Do some sound effect.</a>
```

Thanks for replying.

Paul

**Comment by rudygalfi** [comment]
Re-assigning to some folks who may be able to say whether this is possible today or could take this as a feature request.

**Comment by nainar** [comment]
We have 2 events play/pause for `<amp-audio>` - Documentation here: https://www.ampproject.org/docs/interaction_dynamic/amp-actions-and-events#amp-audio

**Comment by meistudioli** [comment]
@nainar :

Thank you so much.
