### ISSUE TITLE
[Layers] amp-lightbox > amp-accordion > amp-img do not load if the accordion isn't expanded by default

### ISSUE THREAD

**Issue by dis-aster-ous** [ampproject/amphtml#14642]
## What's the issue?

When nesting an amp-img within an amp-lightbox and amp-accordion (`<amp-lightbox>` -> `<amp-accordion>` -> `<amp-img>`), the image will not be loaded if the accordion is closed by default. However, if the accordion defaults to `expanded`, the image will be rendered.

## How do we reproduce the issue?

To see the images in their unloaded state:
1. Visit https://genius.com/amp/Drake-nice-for-what-lyrics
2. Open any annotation
3. Click the Contributors accordion (example text: "Genius Annotation **3 contributors**")
4. Observe that user avatars do not load

<img width="370" alt="screen shot 2018-04-16 at 2 01 16 pm" src="https://user-images.githubusercontent.com/6699823/38826747-b39f7074-417e-11e8-92b2-736621b1c6db.png">

To see images load:
1. Follow the above steps
2. Close the annotation lightbox, making sure to leave the contributor accordion open
3. Re-open the annotation
4. Observe the avatars properly rendered

<img width="372" alt="screen shot 2018-04-16 at 2 01 25 pm" src="https://user-images.githubusercontent.com/6699823/38826766-c323072c-417e-11e8-834c-9ed071a7af0e.png">

If you watch the DOM while following these steps, you'll notice that the `<img>` tag nested within `<amp-img>` doesn't appear until that second time opening the lightbox. This appears to be related to https://github.com/ampproject/amphtml/issues/3586

## What browsers are affected?

Confirmed in (but not necessarily limited to) Chrome 65 and iOS Safari 11

**Comment by jridgewell** [comment]
For now, this is a bug with accordion not laying out its children.

**Comment by yk1979** [comment]
I'm having the same problem.
I think it might be occured as amp-lightbox has a "scrollable" attribute, but not sure...
https://github.com/ampproject/amphtml/blob/master/extensions/amp-lightbox/0.1/amp-lightbox.js#L355-L364
