### ISSUE TITLE
Stylesheet for Google Fonts not validating

### ISSUE THREAD

**Issue by 88kbbq** [ampproject/amphtml#1464]
For `<link rel="stylesheet" href="https://fonts.googleapis.com/earlyaccess/notosanstc.css" type="text/css">`

INVALID_ATTR_VALUE rel=stylesheet (see https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#canon)

**Comment by 88kbbq** [comment]
The fonts.googleapis.com should validate.

**Comment by cramforce** [comment]
It should. The markup in your original issue looks a bit weird. Could you
link to maybe a jsbin.com with your actual markup?

**Comment by 88kbbq** [comment]
It's on a test site pos.88k.com.tw.

**Comment by 88kbbq** [comment]
If there a question about the fonts URI, check out https://www.google.com/fonts/earlyaccess

**Comment by cramforce** [comment]
Looks like we need to whitelist the earlyaccess path. Probably fine to allow all paths on the host.

CC @Gregable @powdercloud

**Comment by 88kbbq** [comment]
Thank you cramforce. Finally, some foreign language fonts there on Google Fonts Early Access. Just curious, when I have an issue, generally how long does it take to address/fix?

**Comment by Gregable** [comment]
The earlyaccess path has been whitelisted in the validator.
