### ISSUE TITLE
Iframe 600px/75% is too restrictive for our use-case

### ISSUE THREAD

**Issue by LennardF1989** [ampproject/amphtml#1466]
A colleague of mine is currently reworking the corporate website to also serve AMP pages. It's been quite some work, but we managed and the result is pretty neat.

One thing we do not like is the iframe position restriction however, and since the error told use to present a use-case, here I am :stuck_out_tongue:

Our corporate-site uses Vimeo for showcasing customer products and the like. The content above these videos is usually short and straight to the point, as such, the Vimeo iframe is at a position around the 400px, 200px "too small" to pass the iframe validation.

I downloaded my own copy of the iframe JS file, and modified the 600 to 400, which works, but will obviously fail other validations.

It would be really great if this hard value of 600px becomes configurable between a certain range. I can understand that the validation-rule prevents phishing techniques and the like, but its just annoying for embedding media.

**Comment by amphtml-team** [comment]
Please take a look at the placeholder documentation for amp-iframe. It
allows for placement on any part of the page so long as a meaningful
placeholder is specified.

**Comment by LennardF1989** [comment]
That's even better! I'll forward this to my frontend-man and report back with the results :smiley:
