### ISSUE TITLE
Seeing several instances of errors from src/utils/video.js

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#14675]
@aghassemi Can you comment on whether this is expected? It's the top reported error from last week.

```
Error: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
    at https://raw.githubusercontent.com/ampproject/amphtml/1523640267934/src/utils/video.js:57:20
    at https://raw.githubusercontent.com/ampproject/amphtml/1523640267934/src/utils/video.js:57:14
    at self (https://raw.githubusercontent.com/ampproject/amphtml/1523640267934/src/utils/function.js:36:26)
    at https://raw.githubusercontent.com/ampproject/amphtml/1523640267934/src/utils/video.js:92:4
    at https://raw.githubusercontent.com/ampproject/amphtml/1523640267934/src/service/video-manager-impl.js:884:4
    at videoVisibilityChanged_ (https://raw.githubusercontent.com/ampproject/amphtml/1523640267934/src/service/video-manager-impl.js:1868:8)
    at getScrollTop (https://raw.githubusercontent.com/ampproject/amphtml/1523640267934/src/service/viewport/viewport-impl.js:490:34)
    at measurePromise (https://raw.githubusercontent.com/ampproject/amphtml/1523640267934/src/service/viewport/viewport-impl.js:448:13)
```

**Comment by alanorozco** [comment]
It looks like some tests that should be skipped, aren't. Issue likely introduced by #14213, but could have been there previously given the `console.error` changes to our tests.

**Comment by aghassemi** [comment]
@rsimha It is expected, that code tries to do support detection by calling a WebAPI method which may print error. We might be able to put a try-catch around it, not sure if that would suppress the error or not ( depends on whether browser is throwing or just console logging)

**Comment by aghassemi** [comment]
@alanorozco Could you look into it? it is the `The request is not allowed by the user agent ` method

**Comment by rsimha** [comment]
@alanorozco These are logs from canary, not test failures.

@aghassemi SGTM, will leave it to your team to figure out how to silence this.
