### ISSUE TITLE
Make XHR service only do requests after first visible by default

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#14685]
We currently have the wrong default in terms of privacy. It'd be better to opt-into the more dangerous behavior than opting out from it.

**Comment by jridgewell** [comment]
I [advocated](https://github.com/ampproject/amphtml/pull/9350#discussion_r116655597) for this originally, but @dvoytenko shot me down.

**Comment by cramforce** [comment]
We can obviously make all existing call sites opt into the old default behavior. I don't see how changing the default should be a problem.

**Comment by dvoytenko** [comment]
My recommendation was to always throw an error pre-visibility for XHR requests to origins different from the document's (or Cache's). My reason was that doing XHR pre-visibility is most likely an error and putting it into waiting state would hide the symptoms. 

This was however at the time where we tried to find all violations and address them at the source. I'm totally fine changing this behavior now.

**Comment by jridgewell** [comment]
We can both log an error and wait for visible?

**Comment by dvoytenko** [comment]
I really do think at this time, waiting for visibility right inside the XHR is fine.

**Comment by jridgewell** [comment]
Passing to @alabiaga.

**Comment by zhouyx** [comment]
We can definitely avoid the privacy leak [bug](https://github.com/ampproject/amphtml/pull/14656) I made before with waiting for visibility inside XHR 😄
