### ISSUE TITLE
Cannot use amp-list in amp-carousel

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#14689]
Here is an `amp-list` that features a Wikipedia image
  https://afdsi.org/test/amp_list_wikidata_1/

However, when placed in an `amp-carousel`, it fails
  https://afdsi.org/test/amp_list_wikidata_1_carousel/

We've looked at
  https://github.com/ampproject/amphtml/issues/10706
and
  https://github.com/ampproject/amphtml/issues/4405#issuecomment-318204399
  
But we can't use the work around because we are not loading an array of images for a carousel.
Instead, we are loading a specific image for a specific carousel slide.

Are we doing something wrong?

If no, is there a solution here?

/jay gray

**Comment by jaygray0919** [comment]
Thank you John @jpettitt 

BTW, we also have you to thank for the `items` parser that enables us to walk-the-wikidata-tree
there is one problem with the parsing routine that we'll open as a separate issue.

Thanks again for the amp-list in amp-carousel solution

/jay

**Comment by miguelmayo** [comment]
This is not possible as amp-list does not work in combination with amp-carousel

**Comment by jaygray0919** [comment]
@miguelmayo we use amp-list with amp-carousel. What issues do you see?

**Comment by miguelmayo** [comment]
@jaygray0919 Could you please send me a link to a working demo? Thanks!

**Comment by jaygray0919** [comment]
Here is a sample: https://afdsi.org/test/amp_list_home_carousel/ this page is a draft - not a production page and will be removed in the future. also it does not include the image positioning solutions used in another page. but it does demonstrate the solution form @jpettitt

**Comment by miguelmayo** [comment]
I see you make it work, it doesn't for me, JSON data is coming from WordPress API, you have a mustache loop inside the carousel that I can't make it work, thank you!

**Comment by jaygray0919** [comment]
Post your example so we can see the differences. Otherwise the discussion is abstract.
