### ISSUE TITLE
Expose device viewport size on rendering amp-ad

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#1468]
Provide the ability for the ad creative code to resize itself to the device width when needed & when the ad is not in user view.

**Comment by ds0001** [comment]
:+1:

**Comment by ds0001** [comment]
we ended up solving our ad resize issues with ```layout="responsive"```
see: 
https://github.com/ampproject/amphtml/blob/2a6187d61c03ae69016c1b1ae7ae6242253fcc99/validator/testdata/feature_tests/amp_layouts.html

**Comment by jasti** [comment]
Looks like we are all set here. Closing.
