### ISSUE TITLE
Document/list dynamically-generated components

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amphtml#14692]
The upcoming `<amp-geo>` component (see #14280) is dynamically generated by the server, based on the user agent's IP. (The constant [`{{AMP_ISO_COUNTRY_HOTPATCH}}`](https://github.com/ampproject/amphtml/blob/7ff090b9022cfedc5973e3d8edd991686a5d57c6/extensions/amp-geo/0.1/amp-geo.js#L60) is replaced at delivery time by a string representing the country code of the user.)

This behavior can break systems that self-host or otherwise use copies of the AMP JS libraries (either by separately building the source, or by proxying the libraries from `cdn.ampproject.org`)--in this case, if this library is not given special treatment, the incorrect country code may be returned.

(Self-hosting the AMP JS libraries is common in systems that automatically optimize AMP. AMP Caches also need to identify components that have this property.)

/cc @jpettitt

**Comment by ithinkihaveacat** [comment]
Created a PR to add this to `amp-cache-guidelines.md` but probably also should be mentioned somewhere else? (Self-hosters are unlikely to find this.)

**Comment by jpettit** [comment]
@jpettitt the mention was meant for you....

And pick a different username! 😛

**Comment by ithinkihaveacat** [comment]
Sorry @jpettit, and thanks!

**Comment by ithinkihaveacat** [comment]
A similar sort of list, for comparison: the [list of render blocking elements](https://github.com/ampproject/amphtml/blob/master/src/render-delaying-services.js#L27).

**Comment by jpettitt** [comment]
@ithinkihaveacat I've been using "jpettitt" since before the internet was invented and I'm kinda attached to it so I think I'll keep it. 😛

**Comment by jpettit** [comment]
According to your twitter you have been using the Internet since before I was born.  I suppose you get a pass.
