### ISSUE TITLE
Treatment for clashing amp-fx presets to the same element?

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#14697]
Currently we have the following types of presets for amp-fx (either in design, inflight or launched phases):
* Scroll dependent
  * parallax
  * fade-in-scroll
* Scroll triggered
  * fade-in
  * fly-in-bottom
  * fly-in-top
  * fly-in-left
  * fly-in-right

Allowing a mix of scroll dependent/scroll triggered animations seems fine. You can fly in from the bottom and then be locked into a scroll dependent fade in as the user scroll. 

However, some of these presets clash heavily against each other. Example:
* parallax and fly-in-{bottom,top} - These are both performing translation operations along the Y axis on the element.
* X and X-scroll - E.g. fade-in and fade-in-scroll. These can lead to some not pleasing animations. 

We can treat these in one of the following ways:
* Accept the first input and ignore the second one.
* Ignore the entire animation.

I am of the opinion that we do want to layout something on the screen and so we should accept the first input and ignore the second, since ignoring the animation can lead to the element being in the wrong space where it has no context. (An invisible header for example.) We should regardless throw a console error.

cc @aghassemi @ericlindley-g

**Comment by ericlindley-g** [comment]
Really good point — I also vote for this option of accepting the first input, clearly documenting this behavior in the .md, and throwing a warning in the console (though others should correct me if there's a better practice for console warnings).

FWIW, there's a third option, which would be to invalidate the page and make no guarantees for how it will function, but I think the above is a better developer experience.

**Comment by nainar** [comment]
By invalidate the whole page do you mean via the validator? We discussed using the validator to check for this. Turns out a) the validator doesn't currently support this and b) like you said that wouldn't make a good developer experience. We should perform at a best effort level.

**Comment by cathyxz** [comment]
Best effort + documentation in bold +1. =)
