### ISSUE TITLE
New Amp Story Ad Call to Action: "Listen Now" & "Subscribe Now"

### ISSUE THREAD

**Issue by jp-washpost** [ampproject/amphtml#14727]
## What's the issue?

We want to be able to promote podcasts and other audio inside of our house ad inventory on Amp Story ads. Can we include a **"Listen Now"** and **"Subscribe Now"** call to actions in ads to give us more flexibility around promoting podcasts (and other subscription-based products).

Relevant part of ad spec:
https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/amp-story-ads.md#cta-ad

**Comment by jasti** [comment]
@calebcordry would you be able to send a quick PR for this please?
