### ISSUE TITLE
Validator Errors should output instructions on how to 'regold' output files.

### ISSUE THREAD

**Issue by Gregable** [ampproject/amphtml#14735]
Thanks to @powdercloud's change, validator files can now be 'regolded' by running a simple `build.py` command. We should add documentation on how to run this in https://github.com/ampproject/amphtml/blob/master/contributing/component-validator-rules.md and make sure that the related test failures spit out a link to this doc.

**Comment by honeybadgerdontcare** [comment]
`gulp validator --update_tests`
or directly inside `validator` directory as `python build.py --update_tests`
https://github.com/ampproject/amphtml/blob/master/validator/build.py#L715
