### ISSUE TITLE
Add intro tables to the AMP tag markdown files

### ISSUE THREAD

**Issue by Meggin** [ampproject/amphtml#1473]
Add a simple intro table to each AMP tag that includes: Description, Availability, Validation, Examples, and optional, Learn More (not all AMP tags will have more information at the start of it's release).

* Description will be a brief sentence introducing the tag.

* Availability will be Stable or Experimental for now, but could change to proper version control should this happen in the future. Experimental status will link to new experimental page that will include complete table of experimental APIs, and what it means to be experimental, how to work with experimental tags, how to move a tag out of experimental state.

* Validation will list any validations that apply to the tag. I really like this one. Thanks, Erwin, for the inspiration.

* Examples will link to any examples out there specifically for the tag. Examples could also link up to use cases, once available.

* Optional Learn More will link to related docs. I'm sort of tempted to combine examples and learn more together into Related Docs.

FYI... check out similar table in chrome.extensions APIs: https://developer.chrome.com/extensions/alarms

**Comment by Meggin** [comment]
Adding in another comment based on discussion with Rudy to also include required scripts in table for extended components.

**Comment by rudygalfi** [comment]
Closed via #2048
