### ISSUE TITLE
Find unused (dead) class fields

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#14742]
I found in #14739 two unused class fields:

```js
class Example {
  constructor() {
    this.field_ = something(window);
  }
}
```

Even though these private fields were not being accessed at all, they were still present in the v0.js:

```js
function Xk(a) {
  this.A = gd(window);
}
```

Bytes add up. We can detect things like this, and lint them out.

**Comment by rsimha** [comment]
@jridgewell Reopening this issue, since we still have a couple dozen warnings for the `amphtml-internal/unused-private-field` rule that are preventing it from being made into an error.

https://travis-ci.org/ampproject/amphtml/jobs/532446854#L316

**Comment by rsimha** [comment]
Tooling is in place to detect this. All that's left to do is remove instances of this from the runtime.

**Comment by choumx** [comment]
I think this can be closed now that the lint rule is an error.

**Comment by rsimha** [comment]
> I think this can be closed now that the lint rule is an error.

A possible cleanup task: See if any of the `@protected` class fields in #22626 are unnecessary, and if so, delete them.
