### ISSUE TITLE
Select within amp-sidebar loses focus due to CSS rules

### ISSUE THREAD

**Issue by shishirm** [ampproject/amphtml#14757]
## What's the issue?

This video helps explain the issue at hand -> https://www.youtube.com/edit?o=U&video_id=eAszaiH_M0w

Basically, there is an amp-sidebar with a select on the inside. There is an arrow animation that is created on the select to indicate the drop down being open v/s closed. In order to animate, a "focus" property in CSS is applied on the select.

If I click on the select to see the options, the amp-script tries to refocus almost immediately which makes the list of entries disappear almost instantaneously even without any clicks. This seems like a bug wherein it is not possible to select an option.

Is this a valid issue or is there a workaround to allow for these kinds of animations with focus.

## How do we reproduce the issue?

This sample page can be used to reproduce the issue above. -> https://mshishir1.herokuapp.com/shop/amp_new6.html#development=1

## What browsers are affected?

All browsers

## Which AMP version is affected?

All versions should be affected. This was seen in the following version -> 1524001085966

**Comment by cathyxz** [comment]
@shishirm we're on a 2 week release schedule, so the fix should hit production approximately 2 weeks after merging to master.
