### ISSUE TITLE
Validator rejects relative URLs in <amp-story bookend-config-src>

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amphtml#14765]
In https://github.com/ampproject/amphtml/pull/14192, the validator was changed to reject relative `bookend-config-src` URLs. Can this be changed back? A few reasons:

- Reducing the number of options available to developers makes this feature more difficult to deploy. (Often it is inconvenient to determine, at story construction time, how/where a document will be exposed to the internet.)
- It's inconsistent with `<amp-list src>`, which [allows relative URLs](https://github.com/ampproject/amphtml/blob/671ec47dfd728d22b52d73580769f7319a8c5a12/extensions/amp-list/validator-amp-list.protoascii#L58). (Admittedly there is a commenting saying this will be changed "at a future date", but that commit was made 2 years ago, and it seems unlikely that changing this will be possible now given the number of AMP documents in existence.)
- (Minor reason) it makes a number of existing stories invalid, such as https://www.vox.com/2018/4/3/17188308/me-too-sexual-harassment-sexual-assault (@gmac FYI).

/cc @choumx @newmuis

**Comment by choumx** [comment]
I figured we might as well do this during the 1.0 bump to avoid special-casing more URLs for rewriting at the cache level. However, allowing relative URLs might fall under the "Developer Experience > Ease of Implementation" dictum per [AMP design principles](https://www.ampproject.org/about/amp-design-principles/).

/cc @honeybadgerdontcare

**Comment by ithinkihaveacat** [comment]
Do we have a document explaining how to decide whether a URL should be absolute or not? If other components are going to need to switch to absolute URLs at some point, then I agree a breaking 1.0 release is a good time to change `<amp-story>`, but the rules at the moment seem a bit arbitrary. I imagine something like `<amp-img src>` will always support absolute URLs?

**Comment by choumx** [comment]
Thanks David!

**Comment by honeybadgerdontcare** [comment]
Yes, amp-story allows relative URLs for the attribute `src` in tag `amp-story-bookend`. This is live in the validator.

**Comment by bpaduch** [comment]
Hmm, is the `amp-story-bookend` tag new (not in docs)?

What about the [`bookend-config-src`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/amp-story.md#bookend-config-src-optional) attribute in the `amp-story` tag, will it allow relative URLs?  Same question for the [new meta attributes](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/amp-story.md#42018-new-metadata-requirements) (like, `poster-square-src`)  that I asked about [here](https://github.com/ampproject/amphtml/issues/11989#issuecomment-384774059).

**Comment by honeybadgerdontcare** [comment]
`bookend-config-src` is currently rewritten in the AMP Cache, so it's purely a matter of making a change to validator-amp-story.protoascii to allow relative URLs.

`background-audio`, `publisher-logo-src`, `poster-landscape-src`, `poster-portrait-src` and `poster-square-src` are currently not being rewritten in the AMP Cache. If relative URLs are to be allowed for them, then the AMP Cache change needs to happen first. I haven't heard if we want to do that for this set of attributes.

**Comment by newmuis** [comment]
@bpaduch We're working on a new version of the amp-story spec which changes the `bookend-config-src` attribute on the `<amp-story>` tag to a `src` attribute on the `<amp-story-bookend>` tag (as a child of `<amp-story>`).  We're working on finalizing the details before updating docs.

@honeybadgerdontcare I tend to agree that it doesn't seem like our users are distinguishing between when relative vs. absolute URLs are expected, and other AMP components have set the precedent that we shouldn't need to.  So, I'd love for us to figure out how to support both absolute and relative URLs "everywhere"

**Comment by honeybadgerdontcare** [comment]
Relative URLs are coming for `background-audio`, `publisher-logo-src`, `poster-landscape-src`, `poster-portrait-src` and `poster-square-src`. This will go live in 1-2 weeks.
