### ISSUE TITLE
Simplify AMPCORS spec

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#14789]
With template ads and story ads, more and more servers are required to integrate AMPCORS. However, the current [AMPCORS spec](https://github.com/ampproject/amphtml/blob/master/spec/amp-cors-requests.md) wasn't trivial to follow, which caused many back-and-forth, wasting time. /cc @calebcordry @jasti 

AMPCORS was introduced before the CURLS launch, at the time when all AMPs from different publishers were served from a single cache domain: cdn.ampproject.org. So `__amp_source_origin` URL param was introduced together with a custom HTTP response header `AMP-Access-Control-Allow-Origins` to do another round of security check in AMP runtime in addition to browser’s own CORS check.

After CURLS launch, every publisher domain is assigned a unique cache domain, such as: example-com.cdn.ampproject.org. Theoretically AMP CORS is not needed anymore, however with one caveat that the URL schema is not reflected in the cache domain name.

Nevertheless, given most of the time both http and https of a same domain is controlled by the same party, and treated the the same. So those sites should be able to simplify their CORS integration with AMP.

**Proposed new runtime behavior**
- Keep sending `__amp_source_origin` param in every request. This is mainly to not break legacy servers. New sites can simply ignore this param. This param can also be used by sites that do want to differentiate the access via http or https. In that case, if they want to block an access from http to https, they simply skip writing the `Access-Control-Allow-Origin` header.
- The existency of `AMP-Access-Control-Allow-Origin` header in response indicates a legacy server. Fallback to the legacy AMPCORS check in that case. Otherwise, let browser to handle the CORS check.

**Proposed server integration**
- Sites who don't differentiate traffic from http or https (supposedly 99% of the chances), can completely skip the AMPCORS integration. Instead, they just do the standard CORS header `Access-Control-Allow-Origin: example-com.cdn.ampproject.org`. The origin is read from request header and verified. No custom headers needed.
- Sites who do want to differentiate traffic from http or https, they will read the exact traffic origin from URL param `__amp_source_origin`. To reject an access, simply skip writing the CORS header  `Access-Control-Allow-Origin`.

**Comment by cramforce** [comment]
@dvoytenko 
I think we can and should do this for documents that were served over HTTPS.

**Comment by lannka** [comment]
Discussed in design review.

To avoid potential vulnerability for http sites (described below), we decided to only turn off AMPCORS for HTTPS traffic (source origin is HTTPS).

---- potential vulnerability for http sites
Compromised http sites (for example victim of BGP attack) could have injected malicious code in the AMP Cache page at caching time. Turning off AMP CORS on those pages would enable requests made through HTTPS, and hence spread the attack to HTTPS server.

**Comment by lannka** [comment]
Thinking twice, if such vulnerability exists for http sites, only doing a client side AMPCORS check is not helping much. 

If a compromised HTTP cache page is sending a mutation request to HTTPS server, and if the server does not check `__amp_source_origin`, then the mutation request will be handled. Client AMPCORS check is only blocking the response to be seen.

@cramforce what you think?

**Comment by lannka** [comment]
OK, revised version now is:

For publishers who only host AMPs on HTTPS, they can skip AMPCORS on non-mutation APIs.

So I guess this becomes much less exciting. Any publishers who have a mutation API will need to read and understand the whole AMP CORS article. And even if they don't have a mutation API at the moment, they have to remember that they will need to come back once they plan to add one.

I'm now hesitant, shall we still proceed?

**Comment by cramforce** [comment]
They don't have to understand it, they only have to understand the query param.

**Comment by cramforce** [comment]
One more thing:

**Comment by lannka** [comment]
Regardlessly, can we deprecate the custom header `AMP-Access-Control-Allow-Origin`? If publishers want to reject a request, they can simply not write the standard `Access-Control-Allow-Origin` header, or just reject the request completely.

Was it there due to some browser compatibility issue? Is it still a concern?

**Comment by cramforce** [comment]
The header ensures that sites don't forget to check the query string, since requests break if they forget.

**Comment by dvoytenko** [comment]
We can only remove query param and header in unison: if one exists, so should the other. Perhaps we can revisit the idea of prefixing http origins. See https://docs.google.com/document/d/1Oo2LPjP5UQ7-C09oVO4JuPNfJ-7leOKrDQVpC0riE4E/edit for details.

**Comment by lannka** [comment]
Given all the restrictions, I don't think it's that worthy to do it now.
