### ISSUE TITLE
Fixed layer: Support per-element opt-in for transfer to fixed layer

### ISSUE THREAD

**Issue by jerimiahwelch** [ampproject/amphtml#14788]
## What's the issue?

Feature Request: Stable fixed elements in iOS amp search results

As you are aware, the amp framework currently has a workaround of moving fixed elements that meet certain criteria to a pseudo-fixed element in iOS google search results. However, this has a few disadvantages:

1. Fixed elements shown in the main body after page load display in a juttery way. See video below.
2. Moving elements to this fixed layer takes processing time on startup.
3. Elements in this psuedo-fixed element do not update with amp-bind state changes. 
4. Not all fixed elements are moved, so DOM structure and layering of fixed elements becomes unpredictable.
5. Fixed layers are difficult to quickly and accurately test before publishing the site.

## Summary of Needs
During our eCommerce projects, we are running into situations where we would like to show fixed elements on the page after page load. We are finding ourselves needing to ensure that modals, sidebars, persistent buy buttons, filtering options, or help/chat buttons work together and are visually consistent with our client's mobile sites.

In summary, our main needs regarding fixed elements are:
1. Fixed elements that don't jutter
2. Predictible fixed element layering
3. A stable DOM for CSS Rules
4. Amp-bind working properly in fixed elements
5. Fast initial load times

Our preference is create fixed elements with more universal tools like css, amp-bind, and amp-list instead of working with specialized amp-components for fixed elements on the page. 

## Potential Solutions

1. One potential solution for fixed element jutter in iOS (our preference, perhaps the simplest) is to remove the !important restriction on this rule:

```
html.i-amphtml-ios-embed.i-amphtml-ios-overscroll,
html.i-amphtml-ios-embed.i-amphtml-ios-overscroll>#i-amphtml-wrapper{
	-webkit-overflow-scrolling:touch!important
}
```
This would allow us to specify -webkit-overflow-scrolling:auto instead so that fixed elements will no longer jutter. The benefits of relaxing this rule can be seen here: https://www.youtube.com/watch?v=gAFD_wS0wg4 

Stable fixed elements, reliable z-index layering, consistent UI, and faster page load times are higher priorities than momentum scrolling for many of our clients. This solution lets the browser fix the problem with CSS instead of adding more javascript. Also, this approach ensures that amp-bind will work in fixed elements.

2. Another potential solution (suggested by others before) is to allow developers to specify which elements should go in the pseudo-fixed element and what the z-index of that element should be. This has processing disadvantages at runtime. Also, we would also not be able to move elements that depended on amp-bind into this element because they wouldn't update properly in GSR. 

3. A third alternative is to allow initial coding of amp pages so that the amp runtime doesn't need to expensively rearrange the page on page load. Just load the iOS edge case solution everywhere. This is both declarative and will allow faster load times for amp pages not preprocessed on the google CDN.
```
<iframe id="ampViewer">
  <html>
    <html>
       <body id="scrollableThings">
       </body>
    </html>
    <body id="fixedStuffGoesHere">
      <div id="modal"></div>
      <div id="chatBtn"></div>
      <div id="ampDoesntHaveToTestIfiAmFixed"></div>
    <body>
  </html>
</iframe>
```

## What browsers are affected?

All mobile Safari browsers in Google Search Results

## Which AMP version is affected?

This has always been an issue.

**Comment by aghassemi** [comment]
Thanks for the detailed bug report @jerimiahwelch and laying out possible solutions! I am assigning to @jridgewell to move this forward.

**Comment by jridgewell** [comment]
Oo, seem to have missed this since it was posted late on Friday. Reviewing it now.

**Comment by jerimiahwelch** [comment]
Justin,

> First, what's GSR?

Sorry about the acronym - GSR = "Google Search Results"

Splitting this into two different bugs is fine with me.

> Allowing pages to take away inertia scrolling seems like we'd be regressing even further.

I was hoping for a quick solution, but the reason I included a list of needs was so that you could find creative solutions that meet the needs. 

However, if it comes down to a choice between fixed element jutter and intertial scrolling, we would choose stable fixed elements. Juttery fixed elements are very noticeable while not having inertial scrolling is a more subtle thing to notice. We are certainly getting criticized for juttery elements on iOS.

> We're hopeful that this won't be the case in iOS 11. 

We still have a large portion of our audience on iOS 9 and iOS10. I would prefer not to ignore them.

> We have an open issue to unify the various iOS viewport hacks, so the iframe'd viewport is always used in iOS

I applaud your push for consistency and testability on that thread.

**Comment by jerimiahwelch** [comment]
Should I start a separate bug for amp-bind not updating fixed elements in iOS Google Search Results?

**Comment by jerimiahwelch** [comment]
Perhaps this is helpful:

Our first attempt to solve this problem involved creating a single, full-screen fixed element that contained all of the "fixed" elements on the page as absolutely positioned children. Our hope was that this parent fixed container would get moved to the "pseudo-fixed" element in iOS. However, it wasn't moved because it 1) was transparent and 2) was over 300px high. 

If there was a way we could flag a fixed parent element and promise that it is the only fixed element that needs moved, the amp runtime would only have to worry about positioning one element relative to the Viewer's header bar. We could layer our fixed layers and have a stable DOM. The amp-runtime could run more quickly on startup.

**Comment by jridgewell** [comment]
> However, if it comes down to a choice between fixed element jutter and intertial scrolling, we would choose stable fixed elements. Juttery fixed elements are very noticeable while not having inertial scrolling is a more subtle thing to notice. We are certainly getting criticized for juttery elements on iOS.

/cc @cramforce, @dvoytenko, who'll need to make this decision.

> We have an open issue to unify the various iOS viewport hacks, so the iframe'd viewport is always used in iOS

I'm getting internal bug reports about this too, I'll reprioritize to see if we can go this way.

> Should I start a separate bug for amp-bind not updating fixed elements in iOS Google Search Results?

That'd be great. 😃

> Our hope was that this parent fixed container would get moved to the "pseudo-fixed" element in iOS.

That might have captured all click events...

> However, it wasn't moved because it 1) was transparent and 2) was over 300px high.

Maybe we can see about loosening the transfer restrictions?

**Comment by cramforce** [comment]
To @dvoytenko :)

**Comment by dvoytenko** [comment]
All,

> However, it wasn't moved because it 1) was transparent and 2) was over 300px high.

I think it's fine to remove some of these restrictions, but we should be careful. Perhaps the this option is better:

> Allow for publishers to add an attribute signaling which elements should be moved to a pseudo-fixed container.

I.e. we could add an attribute `trasfer-fixed` and default it to `auto` with current rules. And define `true`/`false` to control it directly.

> Remove the important from `-webkit-overflow-scrolling:touch!important`

This is hard to swallow since the iOS scrolling is very complicated. Did anyone check what's the actual behavior for this now? Last time I checked, the non-inertia scrolling was really really bad on iOS. Not sure where iOS 11 is now. If it's improving on iOS, I could advise a way or two to do something like this. So, please someone concern.

> Authoring amp pages with the iOS pseudo-fixed structure to begin with so fixed elements don't need to be scanned for and moved.

It'd seem to me that this can partially be achieved now?

Ultimately, we could go here from iOS 11. If the fixed transfer is no longer needed - the best path would be to:

a. Remove transfer completely from iOS 11
b. Start removing restrictions before iOS 9/10 and possibly consider allowing non-inertia scrolling on opt-in.

**Comment by jerimiahwelch** [comment]
Here is a video showing Inertial Scrolling(left) vs non-Inertial Scrolling (right) on iOS 9 and iOS10 in Google Search Results amp-viewer.

https://www.youtube.com/watch?v=gAFD_wS0wg4

If you expand the video to high quality, you can see the css rule applied to each page.

Scrolling in iOS 11 google search results amp-viewer currently behaves like the phone on the right in the video. You can sample scrolling on different iOS devices using this page:

https://www.google.com/amp/s/amp.docusearch.com/how-to-find-a-social-security-number-online.html

**Comment by cramforce** [comment]
I'm confused. Do we have inertial scrolling turned on, or not? I believe we do; and it should behave the same as regular body scrolling as of iOS 11.

**Comment by jridgewell** [comment]
> Do we have inertial scrolling turned on, or not? it should behave the same as regular body scrolling as of iOS 11.

We do, and it does.

But iOS 11 still uses non-inertia scrolling for inner boxes by default.

**Comment by jridgewell** [comment]
> I.e. we could add an attribute trasfer-fixed and default it to auto with current rules. And define true/false to control it directly.

I'm ok with this route.

> This is hard to swallow since the iOS scrolling is very complicated. Did anyone check what's the actual behavior for this now?

It's the same as before, still **sucks**.

> Ultimately, we could go here from iOS 11. If the fixed transfer is no longer needed - the best path would be to:

Testing with the more [expensive page](https://www.google.com/amp/s/amp.docusearch.com/how-to-find-a-social-security-number-online.html), it seems #11900 is incorrect and the transfer is still needed in iOS 11. 😞

**Comment by jerimiahwelch** [comment]
Any progress on this?

**Comment by erwinmombay** [comment]
This issue seems to be in  Pending Triage for awhile. @jridgewell Please triage this to an appropriate milestone.

**Comment by eveyiyuan** [comment]
Hi! I was wondering if there are any updates on the issue and what solutions are we exploring!

**Comment by choumx** [comment]
From the options listed here: https://github.com/ampproject/amphtml/issues/14788#issuecomment-385047162

> 2. Allow for publishers to add an attribute signaling which elements should be moved to a pseudo-fixed container.
> 3. ...
> 4. Loosening fixed layer transfer restrictions.

Option 4 (#16049) had to be partially rolled back. It's probably too late/brittle to modify our heuristic for automagically transferring fixed elements. 

Renamed this issue to track the work for option 2 which we can still do.

**Comment by choumx** [comment]
@jridgewell Do we have public documentation describing these quirks with fixed/sticky position elements on iOS? I'm wondering if we build this API, how would publishers know to use it?

**Comment by jridgewell** [comment]
No, there's no documentation yet. And no, I don't think most publishers would be able to understand when to use the opt-in/out, or why it would be necessary.

**Comment by choumx** [comment]
Then documenting it sounds like a good first step. It'd be easier to find than this issue.

**Comment by milestribble** [comment]
@choumx Just checking in for an update. Am I understanding that there is an in-production, undocumented method to opt-out of transferring fixed position elements or is the API itself still being developed? Thanks in advance.

**Comment by choumx** [comment]
The API itself is being developed and this issue tracks that work. 

I was wondering where to put the documentation of this API once implemented.

**Comment by morsssss** [comment]
Thanks for letting me know about this!

Like @jridgewell , I'm not sure how this would be documented or how developers would know how to use it... that is, if it fixes #17452. In that case, of course, a developer would simply expect that a menu that animates down from the top would always simply work.

**Comment by choumx** [comment]
Today there's a console warning every time the runtime modifies a fixed-position element. 

We'd probably extend that to say you can explicitly specify what behavior you want for an element instead of relying on the runtime's automagic.

**Comment by morsssss** [comment]
That would help! Though sadly most developers won't notice the console warning.

I guess it would help if we could also document the problem, pinpointing the circumstances under which it happens. Developers will still be surprised much of the time, but we'll do what we can!

**Comment by choumx** [comment]
> most developers won't notice the console warning

Huh, is that so? How do you know?

**Comment by morsssss** [comment]
Just from personal experience... most people that work with AMP aren't that
experienced with AMP, and it takes a while for most people to notice that
there are helpful notices in the Console.

**Comment by jridgewell** [comment]
Closing this, since iOS 13 has fixed the scroll issues that required transfer.

**Comment by cramforce** [comment]
Is FixedLayer deactivated in iOS13?

**Comment by dvoytenko** [comment]
Transfer is deactivated.
