### ISSUE TITLE
Add web+mastodon: to whitelist for custom protocols

### ISSUE THREAD

**Issue by startef** [ampproject/amphtml#14793]
Just like whatsapp: and the others, I would like to suggest to add web+mastodon:// (used by https://github.com/tootsuite/mastodon) to the whitelist for custom protocols.

Basically the same request as https://github.com/ampproject/amphtml/issues/3727 for threema back then.

Cheers
JP

**Comment by Gregable** [comment]
Will add.

**Comment by Gregable** [comment]
Fixed and live.
