### ISSUE TITLE
Google Translate support

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#14794]
We would like to add Google Translate support to our AMP pages
An AMP iframe technique will not work
Please consider extending the AMP JavaScript libraries to associate the following with a list-box on an AMP page
```
<div id="google_translate_element"></div>
<script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
}
</script>
<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
```

/jay gray

**Comment by jaygray0919** [comment]
here's a good example:
  https://www.openlinksw.com/
/jay

**Comment by cvializ** [comment]
Thanks. Looks like you can use a URL to translate documents like: https://translate.google.com/translate?sl=en&tl=es&js=y&ie=UTF-8&u=https%3A%2F%2Fwww.nyt.com and change the urlencoded URL at the end to be your URL. We could probably implement this as a demo with amp-bind rather than as a dedicated component.

**Comment by jaygray0919** [comment]
The URL technique might be a bit of work as we'll need to set the URL for each 'source:target' pair.
In the case of the Google Translate JavaScript, we only need to initialize the page on which the Translate button appears.

And the URL technique looks a bit different, with the translation "pairs" at the top of the page.

Nevertheless, a small step is better than no step. And we have a list of target languages, so setting the 'source:target' pairing is straight forward.

Also, we plan to edit the source (en-US) to optimally translate to the target languages.
So, realistically, we start with a small number of pairs for $HOME and work from there.

/jay

**Comment by jaygray0919** [comment]
This would be a good UI:
  https://www.ampproject.org/

Upon selecting the target language from the list, load the translated page.
We could use your URL technique above for each link in the list-box.
But we'd like to avoid the 'source:target' pairing that appears above the NYT page example.
That extra element does not appear in the Google Translate button technique.
Instead, the selected language is the parent item in the list box; i.e.
  https://www.ampproject.org/fr/

/jay

**Comment by babakbelur1819** [comment]
<a expr:href='&quot;https://translate.google.com/translate?hl=en&amp;sl=id&amp;tl=en&amp;u=&quot; + data:blog.url' itemprop='url' rel='nofollow noopener' target='_blank' title='Translate'><span itemprop='name'>Translate</span></a>

This Your Solutions

**Comment by jaygray0919** [comment]
TY @babakbelur1819 - will test this week and be back to you with progress/results

**Comment by jaygray0919** [comment]
@babakbelur1819 the AMP Validator throws this error message: `The attribute 'expr:href' may not appear in tag 'a'.` 

Any other ideas about how to achieve "Translate" in an AMP document?

**Comment by cvializ** [comment]
The `data:` and `expr:` prefixes are specific to the Blogger platform. I believe you can append the URL of your AMP document manually and it will work.

**Comment by jaygray0919** [comment]
@cvializ Carlos, that almost worked. Here is a sample:
  https://afdsi.org/test/amp_lightbox_tooltip_3/
The string is set to translate English (en) to Spanish (es).
But the following 'bleeds thru" from the HTML
  `body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}`
**and** it gets translated to boot!

The process does ignore the `lorem ipsum`, but successfully translated the tooltip content.

Am I doing something that causes the pass-thru of HTML code? It's wrapped in a <section> and a <div> so it's fairly well isolated.

**Comment by jaygray0919** [comment]
Thank you @babakbelur1819 for the essential code. I'll post back a final working example.

**Comment by cvializ** [comment]
That looks like a bug in the translator : / That same bug is occurring with `ampbyexample.com` but the header bar hides it.

**Comment by jaygray0919** [comment]
ok, we're gonna use it and tolerate the bleed until it gets repaired. it's too valuable a service NOT to use it, and it helps us edit our en-US to better translate to other languages - short sentences, unambiguous words, no vernacular ...

**Comment by jaygray0919** [comment]
As always thanks for your help Carlos.

**Comment by babakbelur1819** [comment]
style amp-boilerplate = 'amp-boilerplate' from AMP and no effect, indeed in the Google translate page there are some displays that do not support. 

I have not found another solution to support all AMP templates
