### ISSUE TITLE
amp-date-picker is not efficient enough

### ISSUE THREAD

**Issue by Jade05** [ampproject/amphtml#14796]
Hi, I find amp-date-picker performs slowly on some devices. For example, when the user clicks a date, the date is selected after a 3~4 seconds delay.

You can watch the video [here](https://drive.google.com/file/d/1zmBUvAt_iunKThcVcdYB4OiL4lNr0tV8/view). We record it in Safari iPhone6. And you can experience it over our [website](https://m.trip.com)——https://m.trip.com.

**Comment by StevenX911** [comment]
marked

**Comment by erwinmombay** [comment]
This issue hasn't been  updated in awhile. @cvializ Do you have any updates?

**Comment by caroqliu** [comment]
Dedup with #18345
