### ISSUE TITLE
FR: Support FCM Javascript API for sending web push notifications

### ISSUE THREAD

**Issue by micyeung** [ampproject/amphtml#14802]
The FCM Javascript SDK greatly simplifies the process of working with web push notifications - a consistent client-side SDK helps with receiving notifications across Firefox, Chrome, and Opera, and a unified POST endpoint abstracts away the complexity with sending messages to clients on those browsers.
https://firebase.google.com/docs/cloud-messaging/js/client

There have been some good case studies with websites using FCM.js to drive user engagement. 
https://firebase.google.com/docs/cloud-messaging/js/case-studies

`<amp-web-push>` in its current form operates at a lower level than (and is incompatible with) FCM.js.

**Comment by gui-poa** [comment]
There are a lot of publishers using FCM and getting more and more AMP pageviews. I believe this is a key issue to eliminate barriers between AMP and non-amp pages.

@micyeung did you use a workaround in the meantime?

**Comment by aghassemi** [comment]
Good one to keep track for ecom @nainar

**Comment by gui-poa** [comment]
Hi, @aghassemi and @nainar. Do you have any updates on this? :)

**Comment by gui-poa** [comment]
Hi, all.

Just to say that we've just released our push notification's subscription on AMP pages thanks to a fix from @demianrenzulli  [https://github.com/ampproject/amphtml/issues/19023](url), allowing the scope parameter. :)

Currently the button it's opening a popup to load the FCM javascript files. Waiting for this feature also.

At the end of the article:
https://www.google.com/amp/s/www.terra.com.br/amp/noticias/tecnologia/netflix-pode-perder-28-dos-assinantes-quando-disney-for-lancado,2122cfc5ce54802f7132998305a995674r2birqj.html

Have a great weekend!
