### ISSUE TITLE
Rendering issue in iOS Google app

### ISSUE THREAD

**Issue by tomayac** [ampproject/amphtml#14824]
Steps to reproduce:

1) Open the Google app. 
2) Search for “pedidos ya grido” ([search link](https://www.google.pt/search?q=pedidos%20ya%20grido)).
3) Click through to the AMP result, notice the weird cropping (see screenshot below).
4) The issue does *not* seem to occur when the page is loaded directly ([deep link](https://www.pedidosya.com.ar/cadenas/grido/amp)).
5) The issue likewise seems *not* to occur on Safari directly. 

![97423305-146b-43ff-af85-94a25fa02712](https://user-images.githubusercontent.com/145676/39180173-79872998-47b6-11e8-84c0-2be6563e8ef8.png)

**Comment by ithinkihaveacat** [comment]
I can reproduce with iGSA, however not with Chrome or Firefox Focus. So I think the problem is somewhere in iGSA's viewer/wrapper rather than WkWebView.

**Comment by tomayac** [comment]
Thanks, @ithinkihaveacat, confirming this is not `WKWebView` but Google app specific. Changed title and steps to reproduce accordingly.

**Comment by cramforce** [comment]
Please file in b/ component `164566`

**Comment by tomayac** [comment]
@sbenz has tracked this as #78497541.
