### ISSUE TITLE
Whitelist FontAwesome Pro

### ISSUE THREAD

**Issue by fabsn182** [ampproject/amphtml#14829]
FontAwesome introduced a CND-hosted version of the pro-package - url format: `https://pro.fontawesome.com/releases/v5.0.10/css/all.css`. So can you please whitelist pro.fontawesome.com as host in `<link rel="stylesheet">`?

**Comment by ericlindley-g** [comment]
/to @aghassemi : do you know the process to whitelist a font provider?

**Comment by lannka** [comment]
Might follow how we did before: https://github.com/ampproject/amphtml/issues/3749

**Comment by aghassemi** [comment]
/to @gregcrogers It is mostly a validator change.

**Comment by aghassemi** [comment]
@honeybadgerdontcare pointed out this might have already been done and I verified that `  <link href="https://pro.fontawesome.com/releases/v5.0.10/css/all.css" rel="stylesheet">` validates.
