### ISSUE TITLE
How can I update the state with response data in AMP-form?

### ISSUE THREAD

**Issue by kamranuddin** [ampproject/amphtml#14820]
<form method="post"  action-xhr="/shop/1" " target="_top" on="submit-success:AMP.pushState({ currentPage: currentPage+1 })">  
                   
         <div submit-success  >     
                <template type="amp-mustache">
                        {{respData}}                     
                 </template>
           </div>                    

      <div submit-error>      
               <template type="amp-mustache">    
                   {{respData}}                    
            </template>                  
     </div>                  
          </form>  
How and where I update the state with "respData"? I try to update it with "currentPage" but there I think I cannot access the response data (respData). How can I do that?

**Comment by danielrozenberg** [comment]
Hi @kamranuddin - this is not the best forum to ask this type of questions, this is to report bugs in AMP or request features. Your best bet is to ask your question in [StackOverflow](http://stackoverflow.com/questions/tagged/amp-html) with the tag #amp-html, or try out [Slack channel](https://docs.google.com/a/google.com/forms/d/e/1FAIpQLSd83J2IZA6cdR6jPwABGsJE8YL4pkypAbKMGgUZZriU7Qu6Tg/viewform)

Given that, I believe that for your case `{{respData}}` needs to be populated in the error response from the server to be usable in that part of the template. See this doc page for more details: https://www.ampproject.org/docs/reference/components/amp-form#success/error-response-rendering
