### ISSUE TITLE
plugin for CKEditor to produce amp-validated html

### ISSUE THREAD

**Issue by irvin** [ampproject/amphtml#14823]
## What's the issue?

Our website uses CKEditor as our content editor interface on backends, but it produced non-cleaning HTML that needs a manual conversion to make it amp-compatible. We wrote a giant Regex to doing it, but it would be better to have an official plugin to introduce CKEditor to avoid some attributions, and/or checking on the fly to see if the content is AMP compatible. 

## How do we reproduce the issue?

Try CKEditor and grab the produced HTML to validate that it's not compatible.
https://ckeditor.com/ckeditor-5-builds/

## What browsers are affected?

All browsers

## Which AMP version is affected?

N/A

**Comment by danielrozenberg** [comment]
@jpettitt this looks like a partnership issue, similar to what we have with WordPress. Care to weigh in?

**Comment by jpettitt** [comment]
This is really something for the CKEditor authors. @irvin have you reached out to them?

**Comment by jpettitt** [comment]
I'm closing this since it's not something  we can do on the ampproject side.
