### ISSUE TITLE
fix and unskip amp-brid-player tests

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#14833]
amp-brid-player is broken due to a bug in their embed html.
<img width="100%" alt="screen shot 2018-04-24 at 09 00 11" src="https://user-images.githubusercontent.com/2363700/39200307-abe8ebf8-47a0-11e8-8ae1-0347d0d3aa3c.png">

**Comment by erwinmombay** [comment]
This issue hasn't been  updated in awhile. @cvializ Do you have any updates?
