### ISSUE TITLE
Babel error seen during `gulp build` due to size of `react-dates/bundle.js`

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#14831]
```
Note: The code generator has deoptimised the styling of "/home/travis/build/ampproject/amphtml/third_party/react-dates/bundle.js" as it exceeds the max of "500KB".
```

**Comment by cvializ** [comment]
This should be fine, since that bundle is already minified. It would be nice to get rid of it though. I'm working on a few ways to reduce bundle size and they should resolve this.

Is this causing any misbehavior elsewhere, or is it just adding to the noise?

**Comment by rsimha** [comment]
Just noise for now. I opened this issue because the error might be indicative of bloat that we can get rid of.

**Comment by rsimha** [comment]
This also needs to be fixed during `gulp dep-check` and `gulp test`.
