### ISSUE TITLE
Anchor links issue

### ISSUE THREAD

**Issue by canonicalized** [ampproject/amphtml#1484]
How come amphtml does not support anchor links within a page?
I have a very long article that needs a table of contents: https://canonicalized.com/prestashop-vs-woocommerce-what-is-the-bottom-line/amp/
The anchor links are not working even with the full link specified. 
My amp html is valid

**Comment by cramforce** [comment]
@canonicalized Did you test in Firefox? It is working for me in Chrome. We had an issue with Firefox and just fixed it, but that version did not yet roll out.

**Comment by canonicalized** [comment]
Yes, I tested it only on Firefox. Thank you @cramforce
