### ISSUE TITLE
Should amp-geo be render blocking?

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#14846]
@jridgewell says it should because it will cause issues with layers and the class changes amp-geo makes will cause a page re-layout. @cramforce initially said no during design.

**Comment by jridgewell** [comment]
We're adding CSS classes to the body element, which can completely rearrange the page.

At the very least, this needs to invalidate the layers cache of the entire document.

**Comment by cramforce** [comment]
I thought we'd leave it non-blocking and see how much of an issue it would be.

We should also try to SSR it soon.

**Comment by jpettitt** [comment]
@jridgewell what if anything do we need to add to place nice with layers?

**Comment by jridgewell** [comment]
You'll have to call `BaseElement#mutateElement`, passing in `document.body` as the `opt_element` param.

**Comment by jpettitt** [comment]
solved by `amp-geo-pending` #15229
