### ISSUE TITLE
Karma tests disconnect when running tests on Safari

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#14848]
When running the tests on Travis for my PR #14679, I'm getting: Test disconnected because Safari 11.0.1 is not generating any test output for 2 minutes. https://travis-ci.org/ampproject/amphtml/jobs/369330113#L725 Note that it eventually reports a success in L728.

Have tried running it several times and the problems seems to persist.

**Comment by rsimha** [comment]
I see several console errors being printed during Safari runs. Probably related? https://travis-ci.org/ampproject/amphtml/jobs/369330113#L826-L883

**Comment by rsimha** [comment]
https://support.saucelabs.com/hc/en-us/articles/225104707-Karma-Tests-Disconnect-Particularly-When-Running-Tests-on-Safari contains several workarounds, but we already have them in place.

**Comment by rsimha** [comment]
Let's see if #14759 fixes this.

**Comment by rsimha** [comment]
Another PR that could potentially improve things is #13818

**Comment by rsimha** [comment]
@Enriqe Seems like your tests were run on a version of `master` that's 6 days old. Can you rebase and re-run?

**Comment by Enriqe** [comment]
@rsimha sorry about that. Rebased and re-ran. Waiting for results.

**Comment by rsimha** [comment]
Seems like this is a widespread problem on Safari, where even passing runs are idling for several minutes: https://travis-ci.org/ampproject/amphtml/jobs/370751738#L2053

**Comment by Enriqe** [comment]
#14679 is now green. Thanks!

**Comment by rsimha** [comment]
The `hostname` change to `127.0.0.1` is playing badly with some of our tests that use a hard-coded value for `localhost`.

**Comment by cathyxz** [comment]
Seeing timeouts and disconnects here in https://travis-ci.org/ampproject/amphtml/jobs/393858309 and some recent failures on master this week.
