### ISSUE TITLE
Graduate amp-analytics from experimental

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#1485]
Remove code for experiment to make the feature enabled by default.

**Comment by rudygalfi** [comment]
Fixed by #1487

**Comment by rudygalfi** [comment]
Did we need to remove from https://cdn.ampproject.org/experiments.html as part of this?

cc @dvoytenko

**Comment by dvoytenko** [comment]
Yes. This should have been done in the same PR. Obviously now it needs to be completed.

**Comment by avimehta** [comment]
will send out another PR.

**Comment by rudygalfi** [comment]
Latest issue resolved by #1504.
