### ISSUE TITLE
Request for new element-{top, left, bottom, right} macro

### ISSUE THREAD

**Issue by carsugar** [ampproject/amphtml#14863]
It would be useful to have macros for positioning that simply give the top, left, bottom, and right of the element relative the the screen in addition to the elementX, elementY, elementWidth, and elementHeight macros.  This would allow standard positioning to be sent instead of waiting to calculate bottom and right once the currently available macros have been filled in.

**Comment by carsugar** [comment]
Checking in on the status of this issue.  Let me know if there are any plans to add such macros.

**Comment by aghassemi** [comment]
@carsugar To make sure I understand correctly, this is a request for `top, left, bottom, and right` to be available in `amp-analytics` is that correct?

**Comment by carsugar** [comment]
Yes, that's right.  Thanks!

**Comment by jeffjose** [comment]
This sounds reasonable to me. @lannka thoughts/

**Comment by zhouyx** [comment]
@carsugar Not sure I understand the request correctly, What are the coordinates relative to to? The `top` `left` position relative to viewport or document?

**Comment by jaygle** [comment]
The coordinates should be relative to the browser viewport.  (I'm taking over this request from @carsugar).

**Comment by zhouyx** [comment]
@jaygle If so, the value is constantly changing when user scroll the page? Wonder when do you want the value to be measured?

**Comment by jaygle** [comment]
They should be calculated dynamically when the visibility event is triggered and the URL with the macro is being requested.
