### ISSUE TITLE
Option on flying carpet to disable scroll if ad inside is same size as window

### ISSUE THREAD

**Issue by bjalford** [ampproject/amphtml#14861]
Goal:

Use flying carpet to display ad that can be either MPU or double MPU. When double MPU then flying carpet woks as is, when single MPU it's displayed as is not inside flying carpet i.e. no scroll

How can this be achieved?

**Comment by jridgewell** [comment]
Passing over to @jasti.

**Comment by jasti** [comment]
We'll need to do some supporting multi-size for flying carpet. However, that isn't a priority right now. Please feel let us know if you are able to contribute to the feature. Moving to backlog for now.
