### ISSUE TITLE
Expose amp-consent states to 3p iframes

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#14877]
With `amp-consent`,  AMP elements can be configured to be blocked at build time to wait for user interaction with the consent dialog.

The consent state is readable by extensions, but not yet accessible from within iframes, use cases includes `amp-ad` and `amp-iframe`.

Here we propose additions to the window.context API: 

- context.initialConsentState
- context.getConsentStateAsync() // the state can change

/cc @keithwrightbos @jasti

**Comment by jasti** [comment]
Thanks. @lannka please link to master issue from next time.
Master Issue: https://github.com/ampproject/amphtml/issues/13716

**Comment by rudygalfi** [comment]
@lannka Are there any updates on this?

**Comment by lannka** [comment]
This is all done.

**Comment by deekshithraop** [comment]
Hi @lannka , How does amp-ad extensions access `consentString` and `consentRequired` values  documented here[https://github.com/ampproject/amphtml/blob/master/extensions/amp-consent/amp-consent.md#response]. I can only see `sharedData` and `initialConsentState` available in `context` object

**Comment by deekshithraop** [comment]
Hey @jasti, can you help with that query?
