### ISSUE TITLE
amp-bind: Support bindings on fixed layer elements

### ISSUE THREAD

**Issue by jerimiahwelch** [ampproject/amphtml#14888]
## What's the issue?

Amp-bind not updating fixed layers on iOS devices in Google Search Results amp-viewer iFrame

This is an offshoot of this bug https://github.com/ampproject/amphtml/issues/14788
/cc @choumx
/cc @jridgewell

## How do we reproduce the issue?

1. Using x-code simulator, open any iOS device
2. Using Safari, go to this url: https://search.google.com/test/amp?utm_source=gws&utm_medium=onebox&utm_campaign=suit&id=Xi_JN62F_UmbaoGEOB8-ww&view=search-preview
3. Click on "Preview Result"
4. Click on the result
5. Click on the "Make Everything Green" button

In the image below, Actual behavior is on the left, Expected behavior is on the right:

![ampbindnotupdatingfixedlayersiniosgooglesearchresultsiframe](https://user-images.githubusercontent.com/1224514/39280232-f71394ee-48b2-11e8-8bfe-4e16e0128e63.png)

Note: We would love to be able to visit a single URL to test this type of condition instead of manually following the steps above.

## What browsers are affected?

Safari

## Which AMP version is affected?

We believe this has always been a problem

Thank you for taking a look at this,
Jerimiah

**Comment by choumx** [comment]
We just need to scan the fixed layer container as well as the document body.

**Comment by jerimiahwelch** [comment]
Any updates on a timeline for fixing this?

**Comment by choumx** [comment]
Planning to work on this this week. Thanks for your patience.

**Comment by jerimiahwelch** [comment]
Thank you for the update. We look forward to using amp-bind in fixed elements.
