### ISSUE TITLE
amp-story: Remove Unused Private Fields

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#14883]
There's a bunch of unused private fields in the AMP Story code. Rather than do them all myself, I'm assigning this to you all:

1. `gulp lint`
2. Look for any "Unused private" warnings
3. Either annotate appropriately, or remove the unused private.
4. Profit!

Note, this is just a warning now, but it will be promoted to an error shortly.

A lot of them are very easy: #14881, #14882, etc.

Part of #14761.

**Comment by gmajoulet** [comment]
Thanks. I'm on it
