### ISSUE TITLE
Add timer trigger for amp-analytics

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#1489]
Offshoot from #871.

We'd like to add a timer trigger that fires a specified request on a regularly scheduled interval.

**Comment by rudygalfi** [comment]
@breauxc Is this something you think you could help us add?

**Comment by breauxc** [comment]
@rudygalfi: Yes, we'd be happy to take this piece on.

**Comment by rudygalfi** [comment]
@breauxc That's excellent, thanks!

cc @avimehta @btownsend who architected amp-analytics and can help with any questions / design thinking specific to the AMP implementation.

Just wanted to check: Do you think you'll submit this independently of your other active Intent to Implement (#1436), which adds the Chartbeat config?

**Comment by breauxc** [comment]
That's right. @britice and I are both getting up to speed wrt the contribution guidelines now, and will be looking to tackle both issues (independently) this sprint. We'll reach out if we have any questions. Thanks!

**Comment by rudygalfi** [comment]
Closed by #1702
