### ISSUE TITLE
 i-amphtml-sizer under amp-iframe

### ISSUE THREAD

**Issue by reyesemf** [ampproject/amphtml#14928]
We are having problems with an amp-iframe, in this case an i-amphtml-sizer is being generated as the first child.
The i-amphtml-sizer is added with a padding-top equal to the parent's height (but in percentage) which generates a huge white space below the content of the amp-iframe.

Here I leave the example:

![captura de pantalla de 2018-04-27 14-59-23](https://user-images.githubusercontent.com/26515490/39377798-cb3bfc28-4a2c-11e8-98aa-921865a26df6.png)

**Comment by jpettitt** [comment]
This is how it's supposed work. The sizer creates a fixed aspect ratio box and the iframe is pinned to it using absolute positioning.  If you are seeing a lot of white space it's probably because you have a similar padding on an element that wraps the frame.

**Comment by blerimkrosi** [comment]
Hello, can you help me how to change it to 44%, I don´t know were is located this code!
![44](https://user-images.githubusercontent.com/5637169/53031728-b5577c80-346d-11e9-9fe7-776d293ab500.PNG)
![60](https://user-images.githubusercontent.com/5637169/53031729-b5f01300-346d-11e9-8b8f-39b4dc556429.PNG)

**Comment by amitchauhan5991** [comment]
Hello, can you help me how to remove it  **i-amphtml-sizer** padding
![amp](https://user-images.githubusercontent.com/53036123/61437848-ad87ff80-a95b-11e9-99f0-2d4eb3101445.PNG)
****

**Comment by rahuljs** [comment]
@blerimkrosi this issue is happening due to an incorrect image size declaration.
