### ISSUE TITLE
Expose viewer data to amp-analytics

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#1493]
amp-analytics currently has support for the DOCUMENT_REFERRER substitution. This request covers exposing viewer data like the name to amp-analytics so that a publisher could know the viewing context for the page. For instance, consider a user who does the following:

(a) Sees a link on Google clicks on it, opening an article on pub.com.
(b) While reading the article in (a), clicks on another link to a page but stays within the Google viewing context.

At the end of (a) we'd want to have DOCUMENT_REFERRER = google.com and VIEWER = Google. At the end of (b) we'd want to have DOCUMENT_REFERRER = pub.com and VIEWER = Google.

**Comment by rudygalfi** [comment]
cc @jridgewell @erwinmombay who I discussed this with

**Comment by philwills** [comment]
Just to give another motivating example, if a user opens an AMP page in an app which uses AMP rendering like Nuzzel, I wouldn't expect any DOCUMENT_REFERRER to be set, but knowing the VIEWER would be useful.

**Comment by R-O-P** [comment]
Looks like viewer is the same as what you intended to implement initially called "runtime_id".
See : https://github.com/ampproject/amphtml/issues/871

**Comment by avimehta** [comment]
This sounds good to me. Can get this done soonish. @cramforce Is there a single place in codebase where all viewers are supposed to customize settings? I think I saw something in viewer-impl.js but not sure if that is the right place to put an identifier for the viewer.

**Comment by stephanfowler** [comment]
Has there been progress - here or elsewhere - towards being able to identify `viewer` / `runtime_id` / similar? (Even if limited to Google apps such as Newsstand etc.)

**Comment by dvoytenko** [comment]
@stephanfowler Yes. `VIEWER` var from https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#viewer should do that job.
