### ISSUE TITLE
Status Update 2018-04-30

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#14944]
If you are contributing to the AMP Project open source community, please use this issue to provide updates regarding the status of the projects you are responsible for and what you will be working on next.

**Comment by lannka** [comment]
## Ads & Analytics

#### Past sprint:
- amp-consent: MVP launched
- amp-consent: amp-geo integration PR merged
- story ads: fixed a couple of bugs for ad network support 
- template ads: AMP Cache support verified
- amp-analytics config-rewriter proposal 
- proposal to simplify AMPCORS 

#### Next sprint
- amp-consent: ads and analytics integration
- amp-consent: Client ID API opt-out
- amp-consent: Support non-AMP consent flow
- story ads: DFP end-to-end working demo
- story ads: amp-analytics support of life cycle reporting

**Comment by rsimha** [comment]
## Infrastructure

#### Past sprint:
- Investigated Sauce labs / Karma failures (temporarily skipped Safari)
- Percy timeouts were due to exceeding quota (mitigation coming up)
- Number of console.errors in tests down from 804 to 779
- Eliminated `yarn` warnings during first time install

#### Next sprint
- Fix for Sauce failures on Safari 
- Mitigations for slowness / flakiness on Travis / Percy / Sauce Labs
- Tests with `console.error` will start failing (locally) this week

**Comment by aghassemi** [comment]
## UI

### What's done!
* ✨`input type=password` now allowed in AMP https://github.com/ampproject/amphtml/pull/14533 (pending validation rollout)
* ✨ `rotate-on-fullscreen` for amp video players is experimentally available: #14655 
* 🌷Better default style for `amp-date-picker` https://github.com/ampproject/amphtml/pull/14701
* 🐛 Fix for `amp-sidebar`'s focus issue: https://github.com/ampproject/amphtml/issues/14757
* 🐛 Fix for `amp-accordion`'s tap sub-targets: https://github.com/ampproject/amphtml/issues/14627
* 🐛 iOS Fix for `autofocus` in `amp-lightbox`: https://github.com/ampproject/amphtml/issues/13332

### What's next?
* Full launch of `amp-fx=fade-in` and `amp-fx=fade-in-scroll`
* Experimental launch of `amp-fx=fly-in`
* Experimental launch of video docking
* Experimental launch of infinite scroll for `amp-list`
* Working toward allowing `input type="file"` and input masking

**Comment by newmuis** [comment]
## amp-story

### What's done!
- Version 1.0 forked from 0.1 (but not yet ready for use)
- New bookend JSON API (also not yet ready for use)
- Translations are available (based on the `lang` attribute)
- Bugfixes for the ads experience
- CTA layers now disallowed on the first page of stories

### What's next?
- Integration with `amp-consent`
- New bookend DOM element (`<amp-story-bookend>`), components, and documentation
- Domain dialog for AMP viewers
- New embed mode for embedding platforms that already provide sharing
