### ISSUE TITLE
Opacity syntax, HTTPS vs HTTP, layout="responsive"

### ISSUE THREAD

**Issue by ElenaOrel** [ampproject/amphtml#1496]
MS Visual studio is adding ";" automatically to css
I had a problem with
<style>body{opacity:0;}</style><noscript><style>body{opacity:1;}</style></noscript>
until I realized I need to delete ";" (comma)
<style>body{opacity:0}</style><noscript><style>body{opacity:1}</style></noscript>
Also:
<style>body{opacity:0;}</style><noscript><style>body{opacity:1;}</style></noscript>

Also:
 <link href='http://fonts.googleapis.com/css?family=Elsie' rel='stylesheet' type='text/css'> will not work.
It should be:
 <link href='https://fonts.googleapis.com/css?family=Elsie' rel='stylesheet' type='text/css'>
HTTPS, not HTTP - Why?

Also:
https://www.ampproject.org/docs/get_started/create/include_image.html
It would be useful to mention
layout="responsive"

**Comment by dvoytenko** [comment]
@Gregable are we close to being able to validate CSS for boilerplate with more flexibility? Or did we decide not to do that?

**Comment by ElenaOrel** [comment]
Microsoft Visual Studio (I am using VS 2015) - is adding ";"  for css style for a single selector at the end (automatically).
That is why I had a problem to figure out the "MANDATORY_CDATA_MISSING_OR_INCORRECT error" 
for
 body {opacity: 0;}.
Also, the 
links for referring google fonts have been deleted from my post.
I was trying to say: 
fonts.googleapis.com should be with https, not with http.
Is it on my end, or it is a requirement?

**Comment by cramforce** [comment]
@ElenaOrel You can wrap things in ` quotes to get code to show up unchanged.

To answer your HTTPS question: Yes, for all resources except images and your own fonts (which AMP can proxy), AMP requires HTTPS, because AMP is designed to be embeddable into pages that are  hosted on HTTPS.

**Comment by Gregable** [comment]
@dvoytenko we added a regex with a bunch of allowed whitespace for the *new* boilerplate. Still waiting for rollout for that, I suspect later this week. However, it's still a hack. We haven't had any time to work on the css parser, so no progress towards a real solution here. Things like ordering will still matter.

**Comment by dvoytenko** [comment]
@Gregable Are there additional simple steps possible with semicolons and such?

**Comment by Gregable** [comment]
We can make this as complex as a regular expression will allow, but any changes at this point will take awhile to roll out.

**Comment by ElenaOrel** [comment]
I was expecting to see a smaller font size to fit 50x50 (I tried different dimensions).
For some reason the amp-fit-text behaved as a regular div.
'<amp-fit-text width="50" height="50" layout="responsive"
                      max-font-size="52">
            Lorem ipsum dolor sit amet, has nisl nihil convenire et, vim at aeque
            inermis reprehendunt.  Lorem ipsum dolor sit amet, has nisl nihil convenire et, vim at aeque
            inermis reprehendunt.  Lorem ipsum dolor sit amet, has nisl nihil convenire et, vim at aeque
            inermis reprehendunt.  Lorem ipsum dolor sit amet, has nisl nihil convenire et, vim at aeque
            inermis reprehendunt.  Lorem ipsum dolor sit amet, has nisl nihil convenire et, vim at aeque
            inermis reprehendunt.  Lorem ipsum dolor sit amet, has nisl nihil convenire et, vim at aeque
            inermis reprehendunt.
        </amp-fit-text>'

And, my first AMP has been released...
It is not clear where I would find the new release information at:
https://www.ampproject.org
Currently it is 'https://cdn.ampproject.org/v0.js', and there is no obvious "version" info on the site.
Thank you!

**Comment by dvoytenko** [comment]
@ElenaOrel could you share a link to your page or a smaller excerpt as a jsbin?

**Comment by ElenaOrel** [comment]
Sure!
The page:
http://primeedge.com/index_amp.html

https://developers.google.com/speed/pagespeed/insights/?hl=en&utm_source=wmx&utm_campaign=wmx_otherlinks&url=http%3A%2F%2Fprimeedge.com%2Findex_amp.html

87 / 100 Speed
after I eliminated the reference to the fonts.googleapis.com (69/100)

A minor detail:
Minify JavaScript for the following resources to reduce their size by 717B (2% reduction).
Minifying https://cdn.ampproject.org/v0.js could save 717B (2% reduction) after compression.

I am working very carefully with images (please consider me an expert - www.featurepics.com ) - but I am curious how much we need to sacrifice to speed up? 

I am on you side - we need to address the "data limit" issue, just trying to understand how possibly we can eliminate javascripts for "not-static" pages?

It is a good start, but the initiative should be  extended to all of us who have "interactive pages".

So far - I have seen so many examples of using images that are not suitable for the web...

If google is concerned about:
Minify JavaScript for the following resources to reduce their size by 717B - 
 - just let me know if the quality of images should be resized to 1% - nobody will notice the difference.

I have checked some of your image examples... 
If it is an amp page - what is the reasonable image size? 
Should we go above 800px?

**Comment by dvoytenko** [comment]
@ElenaOrel re: amp-fit-text. I don't see any instances in the http://primeedge.com/index_amp.html. Is this the right document?

RE: speed index and compression issues - would you mind spinning it off into a separate issue so that someone else can address it separately?

**Comment by ElenaOrel** [comment]
Sorry:
http://files.featurepics.com/index_amp2.html

I was expecting divs with the specified dimensions. Thank you for all your help!

**Comment by dvoytenko** [comment]
@ElenaOrel This case looks simple. You just need to add:
```
  <script async custom-element="amp-fit-text" src="https://cdn.ampproject.org/v0/amp-fit-text-0.1.js"></script>
```
You can find more info here: https://github.com/ampproject/amphtml/blob/master/extensions/README.md

**Comment by ElenaOrel** [comment]
Great! Thanks a lot!

**Comment by Gregable** [comment]
Closing. We've made several improvements to the boilerplate matching, and this is referring to the deprecated boilerplate.
