### ISSUE TITLE
`toggleLoading()` does not honor `isLoadingEnabled()`

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#14972]
Loading indicators should only be allowed for some elements as can be seen [here](https://github.com/ampproject/amphtml/blob/master/src/layout.js#L298) and [here](https://github.com/ampproject/amphtml/blob/master/src/layout.js#L98) in layout.js

However, we are currently forcing all elements to allow the loading indicator as can be seen [here](https://github.com/ampproject/amphtml/blob/master/src/base-element.js#L728) in base-element.js

This is is a bug. This is why we see the loading indicator for[ facebook-* elements](https://ampbyexample.com/components/amp-facebook/) even though they aren't whitelisted.

cc @jridgewell

**Comment by jridgewell** [comment]
This looks to be coming from https://github.com/ampproject/amphtml/pull/13782.

/cc @aghassemi.

**Comment by aghassemi** [comment]
@nainar @jridgewell that function is not called if `isLoadingEnabled_` returns `false`. I can't repro the issue. `amp-facebook` is not showing loading icon (as intended until #14974) and attributes such as `noloading` which also impact the return of `isLoadingEnabled_`  seem to work as well for me on latest release.

**Comment by jridgewell** [comment]
The element itself can call it. Clear your caches and refresh.

**Comment by nainar** [comment]
Re: the loading indicator, following is a screenshot taken on ABE on prod. Could you try clearing your browser's cache? That seemed to do the trick for @jridgewell.

<img width="610" alt="screen shot 2018-04-30 at 12 28 00 pm" src="https://user-images.githubusercontent.com/7919520/39450136-24e13686-4c7f-11e8-8c40-b98618c5acbc.png">

**Comment by nainar** [comment]
Tangent: This issue explains why prod allows the loader but doesn't explain why master doesn't show a loader element unless I whitelist the elements individually. 

I have checked out master and the loader for facebook-* elements only shows up when I whitelist the components. This obviously worked when I submitted the PR but doesn't anymore! 😱
