### ISSUE TITLE
validator --update_tests does not seem to work

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#14989]
Based on @alanorozco's findings, the `UPDATE_VALIDATOR_TEST` environment that gets set in Python does not stick when the `node` process runs.

/to @honeybadgerdontcare

**Comment by alanorozco** [comment]
Just a note: this occurs in my Linux workstation as well.

**Comment by Gregable** [comment]
OK, I can't reproduce. Neither can anyone else I've talked to. So, I'm closing this issue.

There is one minor fix regarding changes that modify a specific test file that will get pushed out soon, but in general this seems to work.

**Comment by Gregable** [comment]
Please reopen if you run into this issue.

**Comment by aghassemi** [comment]
@Gregable This still happens to me in both of the following scenario:
1- updating the `.html` tests file with an existing `.out` file ( `.out` does not get updated )
2- removing the `.out` file first ( `.out` file does not get generated )

I am testing with latest master in Mac running `gulp validator --update_tests`


@alanorozco Does this still happen to you?

**Comment by alanorozco** [comment]
@aghassemi I wasn't able to reproduce the issue.
