### ISSUE TITLE
FR: AMP-STICK-AD and Media settings to change advert depending on device

### ISSUE THREAD

**Issue by QES** [ampproject/amphtml#15004]
Hi,

I have been looking at using AMP-STICKY-AD to display a fixed advert to the bottom of the page this works well but my AMP site is viewed on both mobile phones and tablets and I would like to use media tags to display a different advert sizes depending on the device.

This works BUT in validation says that you can ONLY have one AMP-STICKY-AD on a page.

OR if you place the check inside the AMP-STICKY-AD then it says that you can ONLY have AMP-AD inside AMP-STICKY-AD (and doesn't work).

It would be useful to either allow the use of CSS to activate different AMP-STICKY-AD elements example 1 - ie allow multiple sticky ad elements below OR to Allow underneath the AMP-STICKY-AD  some more CSS based control (example 2).

I think example 1 makes more sense.

One other thing I noticed with AMP-STICKY-AD is that its Z-INDEX level is 10 which is quite low and easy to end up with elements on a page that have a higher Z-INDEX level and that need to be moved to a lower Z-INDEX.

Example 1:
```
<div amp-access="NOT access.noadvert"><span class="Mobile">
	<amp-sticky-ad layout="nodisplay">
	amp-ad code for 300x50 advert
</amp-sticky-ad></span></div>
<div amp-access="NOT access.noadvert"><span class="Tablet">
	<amp-sticky-ad layout="nodisplay">
	amp-ad code for 728x90 advert
</amp-sticky-ad></span></div>
<div amp-access="NOT access.noadvert"><span class="Tablet970">
	<amp-sticky-ad layout="nodisplay">
	amp-ad code for 970x90 advert
</amp-sticky-ad></span></div>
```
Example 2
```
<div amp-access="NOT access.noadvert">
   <amp-sticky-ad layout="nodisplay">
        <span class="Mobile">
 	      amp-ad code for 300x50 advert
         </span>
         <span class="Tablet">
 	      amp-ad code for 728x90 advert
         </span>
         <span class="Tablet970">
 	       amp-ad code for 970x90 advert
         </span>
    </amp-sticky-ad>
</div>
```

**Comment by jasti** [comment]
@QES thanks for filing the feature request! We'll try to get this prioritized within the quarter.

**Comment by jimmyko** [comment]
We have a similar issue and would like to have multiple <amp-sticky-ad> on page with a different value on the media attribute.

Here is an example of my use case.
```html
<amp-sticky-ad
  layout="nodisplay"
  media="(max-width: 929px) and (min-width:729px)">
  <amp-ad
    width="728"
    height="90">
  </amp-ad>
</amp-sticky-ad>

<amp-sticky-ad
  layout="nodisplay"
  media="(max-width: 728px)">
  <amp-ad
    width="320"
    height="50">
  </amp-ad>
</amp-sticky-ad>
```
