### ISSUE TITLE
[amp-consent] inconsistent styling 

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#15011]
Dismissing the amp-consent flow adds `top: calc(0px);` to amp-consent. This causes the postPromptUi to behave differently based on whether the dialog has been dismissed or the page has been reloaded.

After dismissing:

<img width="416" alt="screen shot 2018-05-02 at 15 52 42" src="https://user-images.githubusercontent.com/380472/39527093-e1c65f4a-4e20-11e8-9744-70d5dfd6bda3.png">

After reload:

<img width="416" alt="screen shot 2018-05-02 at 16 05 07" src="https://user-images.githubusercontent.com/380472/39527781-9de8a3b2-4e22-11e8-9ab2-3aaea220b388.png">

**Comment by sebastianbenz** [comment]
//cc @jasti @zhouyx

**Comment by zhouyx** [comment]
@sebastianbenz Thanks for filing this. Here's what I found. Putting `height=100vh` adds `top: calc(0px);` to the position fixed parent element and it never gets removed. Note this only happens, with `height=100vh`... I guess you can quickly fix the bug on your side by add `top: auto` to the `<amp-consent>` component, I'll also add it to the element by default to fix the bug. Thanks.

**Comment by zhouyx** [comment]
Talked to @aghassemi. It is the runtime that applies `top: calc(0px)` to fixed layer element. I'll let you know once we figure out a good way to fix this. Thanks.
