### ISSUE TITLE
Support for additional substitution variables in amp-analytics

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#1503]
suggested by @msukmanowsky:
- [ ] availScreenWidth = screen.availWidth
- [ ] availScreenHeight = screen.availHeight
- [ ] colorDepth = screen.colorDepth

suggested by @avimehta:
- [ ] documentEncoding
- [ ] userLanguage

**Comment by avimehta** [comment]
@rudygalfi Add the analytics tag here? Also maybe make this a tracking bug of all the variables we need to add to `amp-analytics`? I have a couple of vars of my own that GA would like to add: `documentEncoding` and `userLanguage`.

**Comment by rudygalfi** [comment]
@avimehta Added the suggested vars at the top of the issue.

**Comment by avimehta** [comment]
if @msukmanowsky is working on this, that is great. If not, I can take this up.

**Comment by msukmanowsky** [comment]
Not tackling this one any time soon @avimehta, sorry.
