### ISSUE TITLE
AMP-ANALYTICS: macro BACKGROUND_STATE callback not getting invoked

### ISSUE THREAD

**Issue by camdunne** [ampproject/amphtml#15037]
Bug Fix Request

## What's the issue?
Issue seems to occur with amp-ad, but works fine with amp-video.

For example the same vendor config is used in both cases:
1. 'examples/fake_amp_ad_with_iframe_transport.html':
<img width="1440" alt="screen shot 2018-05-02 at 10 33 09 pm" src="https://user-images.githubusercontent.com/22266951/39557922-e281e21e-4e58-11e8-91dd-29630bb29353.png">
2. 'examples/analytics.amp.html':
<img width="1440" alt="screen shot 2018-05-02 at 11 02 08 pm" src="https://user-images.githubusercontent.com/22266951/39558472-e576887c-4e5c-11e8-898f-7bd411e9c586.png">

The only difference is 1. uses an amp-ad tag and 2. uses an amp-video tag.

The BACKGROUND_STATE macro, when used from vendors.js with transport iframe, it returns a string 'BACKGROUND_STATE' and not a '0' or '1' as expected. However, I did notice that the callback in 'src/service/url-replacements-impl.js'
`this.set('BACKGROUND_STATE', function () {
      return _services.Services.viewerForDoc(this.ampdoc).isVisible() ? '0' : '1';
    })`
does not get called (by placing a debugger inside the function, and the debugger doesnt break), and so the macro has no way to populate. 

Also, I noticed that the other two background related macros are located in: 'extensions/amp-analytics/0.1/visibility-manager.js' with in the VisibilityManager class.

## How do we reproduce the issue?
1. run `gulp` in your terminal
2. use the example amp page and open in your browser: http://localhost:8000/examples/analytics-vendors.amp.html
3. update '/extensions/amp-ad-network-fake-impl/0.1/data/fake_amp_ad_with_iframe_transport.html': delete the json within the amp-analyytics script tag and replace with an empty object literal.
4. Add the following to the json object in  './extensions/amp-analytics/0.1/vendors.js' : 
`  'example-3p-vendor': {
    'transport': {
      'iframe': 'http://localhost:8000/examples/analytics-iframe-transport-remote-frame.html',
    },
    'requests': {
      'pageView': 'backgroundState=${backgroundState}',
    },
    'triggers': {
      'pageView': {
        'on': 'visible',
        'request': 'pageView',
      },
    },
  },`
5. update line 37 in 'examples/analytics-iframe-transport-remote-frame.html' to be just `if (url) {`
6. verify output is 'BACKGROUND_STATE' as shown in image above.

**Comment by camdunne** [comment]
issue was resolved when `BACKGROUND_STATE` was added to `WHITELISTED_VARIABLES` in `./extensions/amp-a4a/0.1/a4a-variable-source.js`

**Comment by zhouyx** [comment]
@camdunne Thank you for the investigation. #16254 has been merged to fix this issue.
