### ISSUE TITLE
Freewheel Ad Network

### ISSUE THREAD

**Issue by jgladden** [ampproject/amphtml#15041]
The Freewheel Ad network does not appear to be supported yet. I am working on porting a client site  and they do not have the option of swapping ad networks. I am considering, until amp supports freewheel, using the amp-iframe. I noticed in the documentation it is not recommended for serving ads but I do not see any other viable approach? Are there any options beyond telling my client they are out of luck and filing a request for this feature?

**Comment by jasti** [comment]
@jgladden requesting Freewheel to add support is the right way to go.

**Comment by jgladden** [comment]
In the interim (or if my client can not get freewheel onboard) could i add a function to the amp-3p-iframe-src remote.html draw3p call to createElement('iframe') then src it to the ad on our server? It seems an ugly, very convoluted approach in comparison to just src'ing the ad from amp-iframe but I am guessing would be supported?

**Comment by lannka** [comment]
@jgladden amp-iframe is not recommended to do ads, but can be a temporary solution (runtime doesn't force what content is loaded in amp-iframe). But again, asking for official support is the ultimate way.
