### ISSUE TITLE
video-players: Support autoplay based on network connection type

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#15065]
Using https://developer.mozilla.org/en-US/docs/Web/API/Network_Information_API on supported browsers we should be able to restrict autoplay to wifi only.

If browser does not support NetInfo API, then it should not autoplay IMO (since idea is to be conservative with data here)

/to @alanorozco , WDYT?
/cc @ericlindley-g

**Comment by ericlindley-g** [comment]
To make sure I understand:

Is the proposal to limit autoplay for all videos in AMP to only those cases where the runtime is able to confirm that the user is on WiFi?

Thinking through the UX ramifications (this is great for anyone who's very judicious about data; but sometimes users want to have a video autoplay, even when on a data plan), as well as business impact to consider (engagement, monetization — incentives to adopt proper components as opposed to dropping videos into an iframe). I'd like us to take this to design review before implementing.

**Comment by alanorozco** [comment]
@ericlindley-g Not for all videos, it's a [new mode](https://docs.google.com/document/d/1vC3y8Hi4cHVlkva1RMre5NabzIPkCwajmIbIUwoeCbI/edit) that page authors can enable.

**Comment by ericlindley-g** [comment]
Thanks for clarifying (I should have looked at the issue title before commenting :)

That sounds great!

**Comment by aghassemi** [comment]
@leonalicious @andreyMakahov If you can share a particular UX you want to achieve, it will help shape the discussion. There are various approaches we can take here: Having this feature be integrated with video or have it be generic or integrate with `amp-user-notification`. Also knowing other use-cases it may help ( e.g. would it make sense for connection type to feed into lazy loading factors in https://github.com/ampproject/amphtml/issues/21497 ?)

**Comment by andreyMakahov** [comment]
Sure. Here is the screenshot of design we want to show for users who use data:
<img src="https://user-images.githubusercontent.com/5758614/54797054-97a84d80-4c8d-11e9-8c20-d6937e0555fb.png" data-canonical-src="https://user-images.githubusercontent.com/5758614/54797054-97a84d80-4c8d-11e9-8c20-d6937e0555fb.png" width="300" height="300" />

From picture you can see that we need to show dark overlay and warning message.

I think the logic should be in amp-video component. If browser does not support Network Information API let us just do nothing.

**Comment by aghassemi** [comment]
Thanks for the screenshots @andreyMakahov, very helpful!

My thinking is to combine this feature with a separate "support click-to-play" overlay feature we have wanted. Each would be useful by its own and combined it would let you create the UX you want, here is the idea:

```
<amp-video autoplay="(wifi-only | wifi-or-unknown | always)" src="">
   <div click-to-play-overlay style="opacity:0.6; background-color: #444">
       <div="play-icon"></div>
       <div You are not in wifi status, click video play to continue>
   </div>
</amp-video>
```

`autoplay="(wifi-only | wifi-or-unknown | always)"` controls `autoplay`. : 
   - `wifi-only` only if network connection is known to be WiFi. 
   - `wifi-or-unknown` autoplays it WiFi or we can not determine.
   - `wifi-or-unknown` always autoplays (unless of course if user has disabled it through browser)

`click-to-play-overlay` will be displayed unless video starts autoplaying.

Thoughts?

/cc @alanorozco @nainar

**Comment by nainar** [comment]
Notes from in person sync:
- The message on click to play overlay should be more generic

**Comment by andreyMakahov** [comment]
@aghassemi Thank you for sharing your idea. I would like to clarify is it possible to separate this feature with autoplay option? Because we still want user to click on click-to-play-overlay first to play video. We are not going to use autoplay.

**Comment by nainar** [comment]
Adding some other use cases:
1. Don't scope it to just auto-play for video. For e.g. in the ads case, we'd like to fallback to an image if the user is on a poor connection
2. Improve precision of non-wifi connections - e.g. 3G Fast, 3G Slow etc. 


All of this would need [`navigator.connection`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/connection) which returns a [NetworkInformation](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation) object which isn't supported on most browsers. 

@aghassemi is there a way to do this other than `navigator.connection`?

**Comment by wassgha** [comment]
@nainar are we ok with implementing this for `autoplay` for now until the other use cases are designed or do we want to do everything at once?
