### ISSUE TITLE
Firefox fires focus events whose target is the entire page and not an element

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#15079]
I get an assert error [here](https://github.com/ampproject/amphtml/blob/master/src/focus-history.js#L47) on Firefox (macOS, Windows) from the [lightbox sample article](https://github.com/ampproject/amphtml/blob/master/test/manual/article-with-lightbox-2.0-gallery.amp.html) (localhost & heroku) whenever you try to click on an image to open the lightbox. Sometimes clicking on the page will trigger a focus event that breaks the assert with a target that is the entire document. Tabbing through the page will also trigger this. 

- [x] Add a hack so we stop throwing useless dev asserts in FF. 
- [ ] File FF bug on bugzilla.

**Comment by aghassemi** [comment]
closing per #15081
