### ISSUE TITLE
Custom sharing parameters are broken in v1.0 bookend spec

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#15087]
We normally allow publishers to specify custom parameters, like so:

```javascript
{
  "share-providers": {
    "email": true,
    "twitter": {
      "text": "This is custom share text that I would like for the Twitter platform"
    },
    "facebook": {
      "app_id": "1234567890"
    }
  }
  "related-articles": {
    ...
  }
}
```

But translating this to the 1.0 format:

```javascript
{
  "bookend-version": "v1.0",
  "share-providers": [
    "email",
    {"provider": "twitter", "text": "This is custom share text that I would like for the Twitter platform"},
    {"provider": "facebook", "app-id": "1234567890"},
  ],
  "components": [
    ...
  ]
}
```

The custom `text` parameter is not honored for the Twitter platform.  The Facebook `app-id` parameter does appear to work.  Generally, we should honor any parameters specified by just passing them through to `<amp-social-share>` as attributes, with `data-param-` prepended (e.g. the `text` field becomes the `data-param-text` attribute).  This is handled in [`buildProviderParams`](https://github.com/ampproject/amphtml/blob/ae0bb2afdad6f454cb8c19eb3482cca3b47d9f01/extensions/amp-story/0.1/amp-story-share.js#L104-L118) for the v0.1 bookend.

**Comment by ewagstaff** [comment]
Just worked around this issue -- it does work in the 1.0 format if app_id key is used with an underscore, not a hyphen.

E.g. {"provider": "facebook", "app_id": "1234567890"}
