### ISSUE TITLE
amp-list sort is reset to default after reload page

### ISSUE THREAD

**Issue by Boudybuilder** [ampproject/amphtml#15086]
https://ampbyexample.com/samples_templates/product_browse_page/preview/

Set SORT "Price low to high", refresh page and see that select still low to high but amp list items sorted different. How to fix it? Maybe it must be used selected value in src of amp-list. But how?

**Comment by choumx** [comment]
#12360 should fix this. Though I can't exactly repro this on Chrome (select value is not preserved after refresh) @Boudybuilder Which browser are you using?

/cc @aghassemi

**Comment by choumx** [comment]
Closing as dupe.
