### ISSUE TITLE
`<amp-position-observer>` can't trigger actions on `<amp-animation>` in different document

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#15094]
E.g.  
If we add an `<amp-position-obersver>` in the main doc and add an `<amp-next-page>` with an `<amp-animation>` to the document, the `<amp-position-obersver>` can't trigger events on the `<amp-animation>` as they belong in separate docs. The `ActionService` associated with `<amp-position-obersver>` will not find the element to target in the shadowRoot.

Related to: #14860 

cc @aghassemi

**Comment by aghassemi** [comment]
@nainar assigning to you for now, but as discussed, please log your findings and transfer to @danielrozenberg as needed.

**Comment by sparhami** [comment]
Hmm, is this not working as expected? I would assume that you would want only an `<amp-position-observer>` in the nested document to affect elements within the document.

The issue in #14860 seems to make more sense to me, where a position observer within the document is not affecting elements within the same document.
