### ISSUE TITLE
Please whitelist pro.fontawesome.com

### ISSUE THREAD

**Issue by mlwilkerson** [ampproject/amphtml#15100]
Please whitelist `pro.fontawesome.com`. This is required for Font Awesome 5 Pro subscribers to use our Pro CDN.

Note: `use.fontawesome.com` is still the correct URL for our Font Awesome 5 Free CDN.
So, both `use.` and `pro.` need to be whitelisted.

—Mike, on the Font Awesome dev team

**Comment by Gregable** [comment]
Are the paths the same as use.fontawesome.com? We currently whitelist fonts matching the regular expression:
```
https://use\.fontawesome\.com/releases/v([0-9]+\.?)+/css/(all|brands|solids|fontawesome)\.css
```

**Comment by mlwilkerson** [comment]
@Gregable I see a couple of mistakes in that regex for our Free CDN. And there would be a few differences for the Pro CDN.

**Free CDN**
Two mistakes:
1. `solids` should be `solid` (singular)
2. missing `regular`

So, corrected, it would be:

`(all|brands|solid|regular|fontawesome)`

**Pro CDN**

An example:
```
https://pro.fontawesome.com/releases/v5.0.12/css/solid.css
```

The options for the filename at the end are:
`(all|brands|solid|regular|light|fontawesome)`

---
These above are only for loading Font Awesome 5 using our [Webfonts with CSS](https://fontawesome.com/get-started/web-fonts-with-css) method. We also have a new [SVG with JS method](https://fontawesome.com/get-started/svg-with-js), which uses just JavaScript to render SVG elements—no font files.

Would AMP developers be able to add the necessary `<script>` tags for that? If so, it would entail a different whitelist pattern, since it's sourcing JS instead of linking to CSS.

**Comment by Gregable** [comment]
I'd leave that question to @cramforce, but I suspect the answer is no since that means the font's won't be part of the browser's preload scan.

In the meantime, I'll fix the regular expression for the non-JavaScript path.

**Comment by cramforce** [comment]
yeah, we have no way to support JS based font loading.

**Comment by mlwilkerson** [comment]
To clarify, I don't think we're talking about JS based font loading, just loading JS that finds `<i>` elements in the DOM and replaces them with `<svg>` elements. Not possible in AMP?

**Comment by cramforce** [comment]
It would need a new AMP extension. But that sounds like it makes the client do a lot of work for something that could be done server side.

**Comment by mlwilkerson** [comment]
Server-side rendering is also a valid scenario for us, but we also support animations and such that are data bound, which happens client side.

So, if making a new AMP extension is a Thing, that may be what we should explore. We already have what may be analogous components for use in other frameworks like React, Ember, Angular and Vue.

**Comment by Gregable** [comment]
The whitelist has been updated.

**Comment by mlwilkerson** [comment]
Thank you.

**Comment by JTLR** [comment]
Hi, I am using an older version of FontAwesome (4.7) which gets supplied at this URL: `https://use.fontawesome.com/{random string of 10 letters and numbers}.css`
Is it possible for this to be whitelisted also?

**Comment by erwinmombay** [comment]
cc @Gregable to triage @JTLR 's request

**Comment by Gregable** [comment]
Happy to implement, but @cramforce for approval of the change.

**Comment by cramforce** [comment]
Ship it.

**Comment by Gregable** [comment]
Resolved.
