### ISSUE TITLE
Optimize amp-story resource loading depending on network capabilities

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#15103]
Inspired by #15065, we can use the [Network Information API](https://developer.mozilla.org/en-US/docs/Web/API/Network_Information_API) to determine the quality of the user's connection, which can allow us to optimize resource loading.

More concretely, it might be worth experimenting with the size of the [MediaPool](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/1.0/media-pool.md) on different connection types and speeds.

/cc @gmajoulet

**Comment by gmajoulet** [comment]
Optimizing the resource loading based on the user's connection would indeed be amazing.
However, I'm not really sure about how much we can rely on the network information API. While it can be used to determine whether we want to load content upon user interaction or automatically, to be respectful of their data plan, using WiFi doesn't mean it is a good connection.
Ie: Airports/public WiFi, or that guest house WiFi in the Philippines jungle that wouldn't let me send a Whatsapp message

I believe we could rely on other metrics to estimate the effective bandwidth. HTML audio and video have properties like ``bytesReceived`` and ``downloadTime`` that can be used to estimate the bandwidth.
Or a mix of all these techniques :))

https://wiki.whatwg.org/wiki/Video_Metrics#bytesReceived

**Comment by newmuis** [comment]
FYI the network information API also includes speed information and ping latency

**Comment by gmajoulet** [comment]
Yep let's keep this one open as we're still working on it, until we create a better (and up to date) ticket.
