### ISSUE TITLE
Add analytics hover trigger

### ISSUE THREAD

**Issue by Arik-Cappsool** [ampproject/amphtml#15114]
In order to create heat maps for AMP pages (desktop..), It would be great to have an hover trigger.
I will need to configure the hover duration:

If a div was hovered more than 500ms, send an event with x.y coordinates.  

"vars": {
  "id1": "#div1",
  "id2": "#div2"
},
"triggers": {
  "divHover": {
    "on": "hover",
    "selector": " ${id1}, ${id2}",
    "request": "event",
    "vars": {
      "eventId": "hover"
    }
  }
}

**Comment by zhouyx** [comment]
cc @lannka @jeffjose

**Comment by zhouyx** [comment]
cc @jeffjose Idea on supporting hover over? 
Also this could be part of the support browser event project.
