### ISSUE TITLE
amp-image-lightbox Remove the top, left, etc.  !important 

### ISSUE THREAD

**Issue by IamAlta** [ampproject/amphtml#15116]
## What's the issue?
REQUEST TO remove the css styling so we can adjust it to fit our layout. 
E.g., our graphics artist wants space around the image, not butted up against the margins. 
Also, to accommodate images that are not quite as large as the screen x or y and have them centered in the amp-image-lightbox.
I tried putting a container around amp-image-lightbox but it doesn't work.

Here are the styles I believe may be interfering for amp-image-lightbox
top: 0 !important;
left: 0 !important;
bottom: 0 !important;
right: 0 !important;
margin: 0 !important;
padding: 0 !important;

## How do we reproduce the issue?

n/a

## What browsers are affected?

All browsers

## Which AMP version is affected?
Powered by AMP ⚡ HTML – Version 1525381599226

**Comment by IamAlta** [comment]
Oh, while you're at it, allow the person to expand the amp-lightbox-image with their fingers. Or, is there a setting for that?

**Comment by jaygray0919** [comment]
Have a similar issue. We have buffer images with space (top, bottom, left, right) to position them in the same location for amp-carousel `slides`. It's similar to the technique used on carousel-intensive sites where black borders are added to images to correct for their irregular shape (particular 'vintage' photos). Sometimes that buffering causes problems when used in amp-image-lightbox. The ideal is to set a `class` for regular (and irregular) images to place them as-desired in an amp-carousel and amp-image-lightbox.

**Comment by cathyxz** [comment]
`<amp-image-lightbox>` isn't intended for that, give it two weeks for `<amp-lightbox-gallery>` to launch. =) 

You should be able to style the `<amp-image-viewer>` component that lives inside of `<amp-lightbox-gallery>` in the same way that you style your images in `<amp-carousel>`.

**Comment by cathyxz** [comment]
Closing this since it will be solved by https://github.com/ampproject/amphtml/pull/15183.
