### ISSUE TITLE
Add built-in vendor configuration for SimpleReach Analytics

### ISSUE THREAD

**Issue by devdazed** [ampproject/amphtml#1511]
## Objective

To implement SimpleReach vendor configuration.  

## Proposed Vendor Configuration
```html
<amp-analytics type="parsely">
<script type="application/json">
{
  "vars": {
    "pid": "AABBCCDDEEFF001122334455"
  }
}
</script>
</amp-analytics>
```

### Additional Event Sources Requested

SimpleReach tracks the time-on-site and user engagement in several different ways. In order to support our full suite of analytics we would require the following event sources in addition to those provided:

* **Timer event** - This is an event that should be configurable to trigger a request at a certain interval.  In our case no shorter than once every 5 seconds.
* **Scroll Event** -This is an event that fires when a one of the quartiles of the page comes into view, (25%, 50%, 75%, 100%) to show how far a user has scrolled.

**Comment by rudygalfi** [comment]
@devdazed Is this an intent to implement?

**Comment by rudygalfi** [comment]
Also, would you be willing to submit a pull request for scroll triggers as discussed in #1490?

**Comment by devdazed** [comment]
Yes, this is an intent to implement. I am still discussing with my team, how involved #1490 is, will get back to you on what we find.
