### ISSUE TITLE
SVG support in mustache templates

### ISSUE THREAD

**Issue by alabiaga** [ampproject/amphtml#15123]
Track the effort to support SVG in amp mustache templates. As mentioned and discussed in this issue #1156 

- assess DOMPurify integration or adopt similar logic in amp mustache. This is just usage in templates
- assess future work to integrate similar logic into the validator for usage outside of templates.

**Comment by jaygray0919** [comment]
We presented a related problem in the AMP Slack channel: https://amphtml.slack.com/archives/C9HPA6HGB/p1525688074000027

We need SVG inline support for src="" because we will use `amp-mustache` to assign an amp-custom-CSS-element to a class in the SVG document. We can't do this if the SVG is external to the amp document.

**Comment by alabiaga** [comment]
@jaygray0919 Yes we are working on getting this to work. Thanks for comments.

**Comment by alabiaga** [comment]
As discussed with the runtime team yesterday, @jridgewell suggested we just add the svg tag and svg related tags and attributes to the caja html sanitizer...which is somewhat inline with what Gabor was already suggesting though he'd prefer we reuse the existing validation rules we generate via proto; which is still what we are aiming to do in the long term, so that we don't need to maintain two sets of rules. This seems to be the best solution with the least changes..rather than integrating the entirety of DomPurify or even a snippet of it. I also started creating/modifying rules in our existing set of svg validation rules so that svg validation outside of mustache templates and inside amp mustache templates match.

\cc @honeybadgerdontcare 
\cc @molnarg 
\cc @jridgewell

**Comment by choumx** [comment]
It would be great to fix a Caja issue from 2015 (https://github.com/google/caja/issues/1797), but I wouldn't underestimate the difficulty of this endeavor. Are you planning to contribute this upstream to the `caja` library?
