### ISSUE TITLE
Consider linting max-len for comments

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#15127]
Comments over 80 columns don't trigger errors or warnings during `gulp lint`.  We could consider making that happen.

Links are already (separately) allowed via the `ignoreUrls` option specified [here](https://github.com/ampproject/amphtml/blob/master/.eslintrc#L70).

**Comment by rsimha** [comment]
There are 454 lint errors in our code when I run `max-len` on comments. The default `--fix` doesn't work.

Need a way to automatically rewrap comments before we an enable an 80 column restriction on comments.

**Comment by rsimha** [comment]
Ended up using this: https://github.com/stkb/Rewrap

Fix available for review in #15247
