### ISSUE TITLE
Improve blurred background performance by using CSS painters

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#15146]
Leveraging the [Houdini spec](https://developers.google.com/web/updates/2016/05/houdini), the responsibility of drawing a blurred background could be offloaded from the main thread [by using a CSS painter.](https://css-houdini.rocks/background-properties)

/cc @newmuis

**Comment by newmuis** [comment]
We decided to go the other way and drop support for the background, since it can't reliably be supported cross-browser yet (in a performant way).
