### ISSUE TITLE
amp-sidebar.js

### ISSUE THREAD

**Issue by Dnk33** [ampproject/amphtml#15154]
Hello!

I have issue in my website from the amp-sidebar.js , so from this case, Continue button is not working in "Login" and "Register" ( https://www.turshop.ro/autentificare )

What should i do in this case?

**Comment by jpettitt** [comment]
Your page is not valid amp, it has external scripts and does not have the AMP core runtime. AMP components are not tested or guaranteed to work outside valid AMP pages.  See https://www.ampproject.org for documentation on how to build and validate your AMP pages.
