### ISSUE TITLE
Add amp-bind to list of 'allowed AMP extensions and builtins' for Amp Ads

### ISSUE THREAD

**Issue by robmurtagh** [ampproject/amphtml#15168]
## What's the issue?

[`amp-bind`](https://ampbyexample.com/components/amp-bind/) is currently not available in the list of [allowed AMP extensions and built-ins](https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/amp-a4a-format.md#allowed-amp-extensions-and-builtins) for Amp Ads (aka A4A). Without this feature the possibility to create lightweight, interactive ads is severely limited.

Could it please be added as an allowed extension?

**Comment by choumx** [comment]
@lannka @keithwrightbos Let me know if I can help with this.

**Comment by keithwrightbos** [comment]
I have no concerns with this if @lannka agrees.  I'll put together a quick PR.

**Comment by robmurtagh** [comment]
Amazing, thanks all for the quick resolution!

Should the README be updated? I may have just missed it in the PR
