### ISSUE TITLE
AMP Html <a target=“_blank”> not working on iphone safari browser to go new window

### ISSUE THREAD

**Issue by ziyed** [ampproject/amphtml#15189]
**Please only file bugs/feature requests for AMP here.**

## What's the issue?

Recently i am developing a progressive web app with Accelerated Mobile Pages (AMP). There i have to add anchor link with target="_blank" so that a user click on that link will be redirected to a new window with anchor location.

`<a href="External_Url"  rel="external" target="_blank">Click</a>`

Its working fine on Android browser but target="_blank" totally not working on iPhone Safari browser. I know this can be solved by javascript but here at AMP we can not use any Javascript due to convention.

Is there any suggestion to make the new window working on iPhone Safari browser on AMP html anchor click with target="_blank".

NOTE: I have configured "In New Tab" on iPhone Safari Settings too.

## How do we reproduce the issue?

On AMP html, create a anchor link with target="_blank". its open the anchor url to new window on Android browser but not working on iPhone Safari browser

`<a href="External_Url"  rel="external" target="_blank">Click</a>`

## What browsers are affected?

iPhone/iPod Safari Browser only

## Which AMP version is affected?

I am working with latest amp version

**Comment by jpettitt** [comment]
I just tried this on a couple of sites and it's working for me.  Can you provide an example link?  What iOS/Safari version?

**Comment by ziyed** [comment]
Hi jpettitt,

Thanks for your reply. IOS version 11

Example link:

1) go to this link: https://amp.bedroomvillas.com/listing?q=usa

2) Click on View details button of any property tiles.

On ios 11 devices safari it doesn't open the links on new tab rather it is loading target site on same page.

Please suggest?

Thanks

**Comment by jpettitt** [comment]
I can reproduce on safari desktop.  Tagging P0, standby.

**Comment by jpettitt** [comment]
After a bit more digging ...

The example page fails even if you remove the `target="_blank"`.  Further all the other test cases I've checked (both synthetic and live production sites) works intended. 

The issue here seems to be related to the redirect in the target url. It's failing 401 and that's leaving Safari in a weird state.
![image](https://user-images.githubusercontent.com/524856/39933054-c00ff258-54f6-11e8-8596-be2d2d257860.png)

If you can give us a reproducible case that doesn't involve the redirect failing please feel free to reopen this.

**Comment by ziyed** [comment]
Hi jpettitt,

I think this is not for authorization. Here i have checked and found its redirecting to self instead to _blank on iPhone Safari browser only. All other browser working it properly. Here i have authorize access and still site redirecting to self instead of blank.

We have solved it another site with **window.open()** but here at AMP we can not use any javascript. Is there anything can amp provide to solve this issue. for example having target="_blank" link will redirect to new window with url using AMP javascript .

Please suggest.

Thanks

**Comment by jpettitt** [comment]
Please build and post a simple stand alone test case that shows the problem.

**Comment by ziyed** [comment]
Hi jpettitt,

Thanks for your response, I have find out the problem. This is happening on Safari browser only due to Mixed content issue. Main web App is serving through HTTPS while some of the inner content link those are targeted as blank are HTTP. the Latest Safari browser block this type of mixed content.
