### ISSUE TITLE
Update cache return 403. Clear cache public key

### ISSUE THREAD

**Issue by kalan2001** [ampproject/amphtml#15190]
## What's the issue?

I need your help, please.

I think an 404 has been cached instead of our current key. How could I clean this, please?
 - https://www.abc.es/.well-known/amphtml/apikey.pub
 - https://www.lavozdigital.es/.well-known/amphtml/apikey.pub

If I request AMP version I've got an 404 Status Code
 - https://www-abc-es.cdn.ampproject.org/r/s/www.abc.es/.well-known/amphtml/apikey.pub
 - https://www-lavozdigital-es.cdn.ampproject.org/r/s/www.lavozdigital.es/.well-known/amphtml/apikey.pub

Our code is working with other domains, like:
https://sevilla.abc.es/.well-known/amphtml/apikey.pub
https://sevilla-abc-es.cdn.ampproject.org/r/s/sevila.abc.es/.well-known/amphtml/apikey.pub

I think we tested before our public key was avalaible. Sorry :(

Thanks!

**Comment by honeybadgerdontcare** [comment]
@aghassemi I don't think they're on github yet, but will pass along.

**Comment by juliantoledo** [comment]
Hi everyone,

The team is currently investigating this issue, we will keep you updated as we make progress.

Regards,
Julian

**Comment by kalan2001** [comment]
Hi

I tried to invalidate the key by update-ping (it is deprecated) and it has worked.

Try to invalidate the AMP URL of the key https://www-lavozdigital-es.cdn.ampproject.org/r/s/www.lavozdigital.es/.well-known/amphtml/apikey.pub

The request would be
curl -XGET https://www-lavozdigital-es.cdn.ampproject.org/update-ping/r/s/www.lavozdigital.es/.well-known/amphtml/apikey.pub -v

Thanks
