### ISSUE TITLE
amp-next-page: Allow for "swipe" mode instead of "scroll"

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#15193]
Would be nice to allow `amp-next-page` have different modes of loading the next article. For instance, `swipe` to next article on mobile but `scroll` on desktop (sort of like how bmw.com does this)

/cc @ericlindley-g @peterjosling @emarchiori

**Comment by ericlindley-g** [comment]
+1 to supporting this use-case somehow.

An alternative to a component would be to support it on origin via PWA (and maybe making that easier with templates or other tools), and support it in AMP viewers as a viewer feature. 

One consideration is how we think of user intent and data use: e.g. amp-next-page only fetches more content when the user gets to the bottom of the page, whereas this feature would immediately have to fetch at least one more page of content automatically

**Comment by manjunathkundar** [comment]
Any updates on this?

**Comment by aghassemi** [comment]
Not currently planned. We are revisiting amp-next-page in Q2 however and will keep this FR in mind.
