### ISSUE TITLE
getExternalCid_ returns null when opted out of API instead of using localStorage

### ISSUE THREAD

**Issue by ericfs** [ampproject/amphtml#15202]
https://github.com/ampproject/amphtml/blob/55a1285fbcfb96f2723472e88519f5e1babfb69d/src/service/cid-impl.js#L236

This should not return null but should instead get the CID from localStorage

**Comment by msukmanowsky** [comment]
@ericfs will this be deployed to all users this Tuesday (May 15) or next (May 22)?
