### ISSUE TITLE
Conditionally block rendering of <amp-ad> based directly on <amp-geo> results

### ISSUE THREAD

**Issue by NAlexPear** [ampproject/amphtml#15227]
## What's the issue?

While we prepare for GDPR compliance with AMP, our team would like to altogether disable the rendering of some ads based on user location. While the `amp-consent` integration has helped, we would still like to disable some ads for EEA users _regardless_ of consent. The idea is to have have three tiers of AMP users around the globe:

1. **EEA readers that have not given consent**: no tracking/analytics/ads enabled
2. **EEA readers that have given consent**: tracking/analytics enabled, no (or reduced) ads enabled
3. **Everybody else**: all tracking/analytics/ads enabled without need for consent.

## How do we reproduce the issue?

The current `amp-ad` implementation is tied to [`data-block-on-consent`](https://www.ampproject.org/docs/reference/components/amp-consent#blocking-behaviors) for any sort of delayed render. This works well for our analytics in cases 1 and 2 above, but does not work for our ads.

## Possible implementations:

1. `<amp-consent>` could use a `rejectForGeoGroup` config property that immediately rejects a single consent group (of multiple) when a user visits the page from a subset of countries. This would, of course, require multiple consents.
2. `<amp-ad>` and other similar components could expose a `data-block-on-geo-group` attribute _a la_ `data-block-on-consent`.

**Comment by jpettitt** [comment]
See also #15229

**Comment by NAlexPear** [comment]
@jpettitt that's a good point that the visibility of the ads could potentially be toggled with a feature like #15229.

To clarify, though, I think the concern outlined in this issue (despite my use of "rendering", which might be a bit confusing) is that we'd like to disable any service of ads in the same way that `data-block-on-consent` currently works.

**Comment by jpettitt** [comment]
@NAlexPear regular `amp-ad` elements with `display: none` do not trigger any resource calls, I'm still confirming that's also true if RTC is enabled..

**Comment by jpettitt** [comment]
#15229 merged yesterday and will be in the next dev channel (Canary) release and barring weirdness in prod a week after that. I'm closing this issue as resolved.
