### ISSUE TITLE
Is there a roadmap/timeline for when experimental things will be merged into the released version?

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#1522]
I'm specifically wondering about responsive/slides amp-carousel, it works great as an experiment fails on the release version.  [edit - this is in prod I just misread the doc]

Beyond the specific case it would be really nice to have some sort of dashboard of things in progress and when they are expected to go live.  We're working on sites that want to be live when the Google news carousel goes live and we need to know what version to validate against.

Did I just miss a list of merged experiments with status, timeline someplace?

**Comment by erwinmombay** [comment]
@jpettitt theres definitely been some requests about a feature dashboard and status. although we dont have plans of a dashboard, we are planning on adding a status (and maybe an eta?) of canary/validation on our document page (www.ampproject.org/docs).

/cc @Meggin @cramforce

**Comment by dvoytenko** [comment]
@erwinmombay and @jpettitt Did I miss some pull requests? I believe responsive slides have been out in PROD for a long time now.

@jpettitt could you please send us a link to a document that fails?

**Comment by jpettitt** [comment]
@dvoytenko sorry you're right, my bad, it is in prod, I misread the doc as the not supporting responsive being global not just the type=carousel.

The bigger question of some sort of what's going live when is still something I'd like to see.

**Comment by dvoytenko** [comment]
@jpettitt We are approaching it from two different directions: (1) we will improve documentation of what's experimental, where we are waiting for validator to catch up, etc. (2) we will be reducing lag between this phases and make it predictable.

**Comment by erwinmombay** [comment]
@dvoytenko @jpettitt we are tracking it here https://github.com/ampproject/docs/issues/6
