### ISSUE TITLE
amp-iframe with placeholder still shows loading indicator

### ISSUE THREAD

**Issue by mjangda** [ampproject/amphtml#1523]
If you have an `amp-iframe` with a `placeholder` that doesn't fill the iframe size, the loading indicator is still visible, which isn't great visually.

### Screenshot

![amp-iframe-placeholder](https://cloud.githubusercontent.com/assets/86105/12504340/6762a548-c0aa-11e5-9609-fb2f5a8ef765.png)

### Code sample

http://codepen.io/mjangda/pen/XXVvRo 

To reproduce, you need to set the iframe src to a URL that takes some time to load. Easy way to test is by pointing it to a script with a `sleep`.

**Comment by dvoytenko** [comment]
`placeholder` itself doesn't cancel loading indicator. But you can add `noloading` attribute to the element in question which will cancel loading indicator.
