### ISSUE TITLE
Does amp-form disallow 'submit-success' in div tag?

### ISSUE THREAD

**Issue by IamAlta** [ampproject/amphtml#15253]
## What's the issue?
Clarification needed on instructions.

This page https://www.ampproject.org/docs/reference/components/amp-form
shows 

    <div submit-success>
      <template type="amp-mustache">
        Success! Thanks {{name}} for subscribing! Please make sure to check your email {{email}}
        to confirm! After that we'll start sending you weekly articles on {{#interests}}<b>{{name}}</b> {{/interests}}.
      </template>
    </div>

When I programmed this on mysite with #development=1 in the url, the browser console says,
    https://example.com/mypage:961:0 The attribute 'submit-success' may not appear in tag 'div'.

## How do we reproduce the issue?
See above

## What browsers are affected?

On recent Firefox developer edition. Haven't tested other browsers.

## Which AMP version is affected?

Version 1525461683159

**Comment by AcidRaZor** [comment]
I have the same issue. This is because you have the form inside an amp-list. So I assume mustache get's confused. I had to resort to take out those messages on my form, because I need amp-list to be able to display already filled in user information. Binding to just the amp-state doesn't allow you to show form values (especially if you have a multi-page questionnaire, their solution is to shove everything into one page, which is crap in my opinion)

**Comment by IamAlta** [comment]
@AcidRaZor 
Please look at the page I referred to. There is no amp-list mentioned.

    <form ...>
      <fieldset>
        ...
      </fieldset>
      <div submit-success>
    <template type="amp-mustache">
      Success! Thanks {{name}} for subscribing! Please make sure to check your email {{email}}
      to confirm! After that we'll start sending you weekly articles on {{#interests}}<b>{{name}}</b> {{/interests}}.
    </template>
    </div>
     <div submit-error>
    <template type="amp-mustache">
      Oops! {{name}}, {{message}}.
    </template>
    </div>
    </form>

**Comment by cvializ** [comment]
Hmm it sounds like you have the the `<div submit-success>` tag outside of the `<form>` tag. Is that correct? If that's the case, you need to use the `template` attribute and link a `<template id="my-id">` with the form's success and error templates.

```
<template type="amp-mustache" id="submit_success_template">
  Success! Thanks {{name}} for subscribing! Please make sure to check your email {{email}}
  to confirm! After that we'll start sending you weekly articles on {{#interests}}<b>{{name}}</b> {{/interests}}.
</template>
<template type="amp-mustache" id="submit_error_template">
  Oops! {{name}}, {{message}}.
</template>

<form ...>
  <fieldset>
  ...
  </fieldset>
  <div submit-success template="submit_success_template"></div>
  <div submit-error template="submit_error_template"></div>
</form>
```

If you can share more of your exact markup or a live demo, that helps us greatly in figuring out any issues you have.

**Comment by IamAlta** [comment]
Hi @cvializ,
Thank you, The submit-success was inside the form tag. 
The form diverts to a new page anyway. I'll keep this in mind for others that we may need it for. Your solution has information that I was unaware of and will keep it in mind.
