### ISSUE TITLE
Amp Example for facebook not working

### ISSUE THREAD

**Issue by SivaRaman24** [ampproject/amphtml#1525]
In examples facebook.amp.html page was not working because of the following resource is missing
"NetworkError: 404 Not Found - https://cdn.ampproject.org/v0/amp-facebook-0.1.js"

**Comment by cramforce** [comment]
It'll take a couple weeks for this to work and then a couple more weeks to
validate.

**Comment by SivaRaman24** [comment]
Okay thanks for the information @cramforce

**Comment by cramforce** [comment]
We'll update the GH docs. If isn't obvious right now that this is not
expected to actually work yet. Sorry about that.

**Comment by cramforce** [comment]
Updated docs.
