### ISSUE TITLE
data-block-on-consent not blocking Google Safeframe

### ISSUE THREAD

**Issue by samanthamorco** [ampproject/amphtml#15264]
## What's the issue?

Google Safeframe is not blocked by data-block-on-consent before a consent gate is passed.

My team and I are preparing our sites for GDPR and we do not want any ad tracking before the consent gate is passed. We're using the Ghostery tool to check what trackers exist on a page. My understanding of Safeframe is that this is a communication between page content and iframe ads, which means it is collecting and passing data. If this is incorrect and Safeframe is not collecting data, please correct my understanding.

## How do we reproduce the issue?
It seems to be happening in the amp-consent playground where an amp-ad is:
See the below screenshot:
<img width="796" alt="screen shot 2018-05-14 at 11 33 19 am" src="https://user-images.githubusercontent.com/7397089/40007925-05f6ba96-576c-11e8-9cfe-9be037d30b20.png">

Safeframe is still popping up on the Ghostery tracker on Google Chrome in incognito mode, before the consent gate has been passed.

## What browsers are affected?
I've only checked Google Chrome so far.

**Comment by jpettitt** [comment]
Related to #13716, possibly related to #15235

**Comment by rudygalfi** [comment]
@zhouyx Can you confirm if #15269 will address this. If so, let's close this out and track updates there.

**Comment by zhouyx** [comment]
@samanthamorco Thanks for filing this. 
This is a bug introduced from https://github.com/ampproject/amphtml/pull/14938#discussion_r187726114. We are working on a fix. 
Closed in favor of #15269
