### ISSUE TITLE
Issue with running ads from a custom domain

### ISSUE THREAD

**Issue by NataliaLKB** [ampproject/amphtml#1526]
There seems to be an issue when following [these guidelines](https://github.com/ampproject/amphtml/blob/master/builtins/amp-ad.md#running-ads-from-a-custom-domain). 

All iframes on the page seem to be affected. Amp-twitter for example is broken. Specifically the iframe it creates. 

Here is a screenshot of how amp-twitter is being affected:
![image](https://cloud.githubusercontent.com/assets/8774970/12513608/90b00a8c-c116-11e5-88e2-40d3e1a81f08.png)

Here is the example page:
https://www.theguardian.com/books/booksblog/2016/jan/20/the-best-music-to-listen-to-while-reading-or-is-it-sacrilege/amp

cc @kenlim @stephanfowler

**Comment by cramforce** [comment]
This happens when opted into canary release. You can fix this on your side by amending the

`if (!(/^\d+$/.test(v))) return;`

in remote.html to be

if (!(/^\d+(-canary)?$/.test(v))) return;

We will update the documentation.

**Comment by cramforce** [comment]
@NataliaLKB Could you confirm that this fixed things for you?

**Comment by NataliaLKB** [comment]
Will be able to confirm momentarily

**Comment by NataliaLKB** [comment]
Unfortunately it doesn't seem to have solved the problem, any other ideas?

**Comment by cramforce** [comment]
Looking at https://www.theguardian.com/books/booksblog/2016/jan/20/the-best-music-to-listen-to-while-reading-or-is-it-sacrilege/amp I now see one add loading, but there seems to be a JS error in your own Krux related code. Could that be the problem?

**Comment by NataliaLKB** [comment]
I will check with that team, as it does seem to be an error there. Thanks @cramforce . Will close this issue.
