### ISSUE TITLE
Animations do not run on iOS for AMP4ADs ('A4A') served via DFP

### ISSUE THREAD

**Issue by robmurtagh** [ampproject/amphtml#15260]
## What's the issue?

When serving an AMP4ADs ('A4A') via Double Click for Publishers, the `amp-animation` component works as expected on desktop, but on iOS the animations do not run.

## How do we reproduce the issue?

- Viewing [DEPRECATED LINK]() on desktop you should see two adverts, both animating.
- Viewing the same link on iOS, you will see the first advert animating and the second advert not animating.

## Details of reproducible case

The reproducible case serves the following two adverts:
- [The scrollbound animation ad from AMP by Example](https://ampbyexample.com/amp-ads/advanced_ads/scrollbound_animation_ad/)
- A stripped down version using 'visibility' trigger

This points towards there possibly being an issue with the animation triggering. However, I have also tested with `on:` triggers prompted by clicking on a `div`, and it is still broken.

The first advert is the only A4A animation I have seen working properly when served via Doubleclick for Publishers, hence why I've included it in the repro.

All other Doubleclick for Publisher settings are identical for both ads.

I've included the AMPHTML for both ads at the bottom of this issue.

I'm having difficulty doing any meaningful debugging inside the advert iframe when using Safari remote debugging on iPhone. No error messages are logged to console or anything straightforward like that. Any pointers on debugging would be really helpful.

## What browsers are affected?

Chrome and Safari are affected. I haven't tested others.

## Which AMP version is affected?

Issue is occurring for AMP ⚡ HTML – Version 1525461683159. I haven't tested others.

## Reference: reproducible ad 1

- [The scrollbound animation ad from AMP by Example](https://ampbyexample.com/amp-ads/advanced_ads/scrollbound_animation_ad/)
```javascript
<!doctype html>
<html amp4ads lang="en">
  <head>
    <meta charset="utf-8">
  <title>Scrollbound Lightbox Ad</title>
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <script async src="https://cdn.ampproject.org/amp4ads-v0.js"></script>
    <script async custom-element="amp-animation" src="https://cdn.ampproject.org/v0/amp-animation-0.1.js"></script>
    <script async custom-element="amp-position-observer" src="https://cdn.ampproject.org/v0/amp-position-observer-0.1.js"></script>

    <style amp4ads-boilerplate>body{visibility:hidden}</style>
    <!-- ## Summary-->
    <!--
    Sample AMPHTML ad using [amp-position-observer](https://www.ampproject.org/docs/reference/components/amp-position-observer),
    and [amp-animation](https://www.ampproject.org/docs/reference/components/amp-carousel) to create an interactive ad.
    -->
    <!-- ## Styling -->
    <!--
    This is an advanced example that requires some styling to make it look and function properly.
    The styling designed here is responsive and will work with various ad sizes.
    -->
    <style amp-custom>
      /* Main element that contains the creative. */
      .root-container {
        background: #000;
        color: #fff;
        font-family: 'Roboto', sans-serif;
        font-size: 12px;
        overflow: hidden;
        width: 340px;
        height: 240px;
        position: relative;
        margin: 0 auto;
        display: block;
      }
      /* Position the footer absolutely, at the bottom of the container. */
      .footer {
        background: #000;
        font-size: 12px;
        padding: 8px;
        text-transform: uppercase;
        display: flex;
        align-items: center;
        color: #fff;
        z-index: 2;
        position: absolute;
        left: 0;
        bottom: 0;
        right: 0;
      }
      .footer-logo {
        border-right: 1px solid #fff;
        padding: 0 8px 0 0;
        margin: 0 8px 0 0;
      }
      .logo-img {
        display: block;
      }
      .stretch {
        flex: 1;
      }
      .button {
        text-transform: uppercase;
        padding: 8px;
        color: #fff;
        display: inline-block;
        background-color: #2979ff;
        text-decoration: none;
      }
      .button:active {
        background-color: #92bbff;
      }
      /* Basic cards styling */
      .cards-container {
        position: absolute;
        z-index: 1;
        left: 0;
        right: 0;
      }
      .card {
        width: 100%;
        overflow: hidden;
        position: relative;
      }
      /* Change position of the expand button for the middle card */
      .card-gauges .expand-button {
        left: 90px;
        top: 50px;
      }
      .learn-more a:active {
        background-color: #f0f0f0;
      }
    </style>
  </head>
  <body>
    <!-- ## Animations -->
    <!--
    The animations are implemented using [amp-animation](https://www.ampproject.org/docs/reference/components/amp-animation) which is an AMP component that uses [Web Animations API](https://www.w3.org/TR/web-animations/) to support both __time__ and __scroll__ based animations.
    -->
    <amp-animation id="adAnim" layout="nodisplay">
      <script type="application/json">
        {
          "duration": "1s",
          "fill": "both",
          "direction": "alternate",
          "animations": [
            {
              "selector": "#cardsContainer",
              "keyframes": [
                { "transform": "translateY(0)" },
                { "transform": "translateY(-384px)"}
              ]
            }
          ]
        }
      </script>
    </amp-animation>
    <!--
    **Slide cards opposite to scroll direction**:
    The ad initially shows the top-most card. As the document scrolls, the other two cards are revealed.

    To achieve that, we define 4 keyframes. Between 0% and 10% of viewport, the first card is displayed. Between 10% and 90%, the cards container will vertically translate to -384 pixels, which is the negative of double as each card's height. When reaching this point, the third card will be fully displayed. Between 90% and 100%, the same position is kept.
    -->

    <!-- ## Scrollbound Animations -->
    <!--
    The scrollbound animations are implemented using [amp-position-observer](https://www.ampproject.org/docs/reference/components/amp-position-observer) which is an AMP component that
    Monitors the position of an element within the viewport as a user scrolls, and dispatches enter, exit and scroll events that can be used with other components
    -->
    <amp-position-observer
      intersection-ratios="1"
      viewport-margins="10vh"
      on="scroll:adAnim.seekTo(percent=event.percent)"
      layout="nodisplay">
    </amp-position-observer>

      <!-- ## Banner markup -->
     <div class="root-container">
      <div class="footer">
        <div class="footer-logo">
          <amp-img src="https://ampbyexample.com/img/car-logo.png"
              width="72"
              height="32"
              layout="fixed"
              alt="Howdy"
              class="logo-img"></amp-img>
        </div>
        <div class="stretch">The All-New WX-S R5</div>
        <a href="https://ampbyexample.com/" target="_blank" class="button">
          Learn more
        </a>
      </div>

      <!-- ## Cards -->
      <div class="cards-container" id="cardsContainer">
        <div class="card card-seats">
          <amp-img src="https://ampbyexample.com/img/car-seats.jpg"
              width="340"
              height="192"
              layout="responsive"
              alt="Ergonomic Leather Seats"
              class="a-carousel-img"></amp-img>
        </div>
        <div class="card card-gauges">
          <amp-img src="https://ampbyexample.com/img/car-gauges.jpg"
              width="340"
              height="192"
              layout="responsive"
              alt="Sport Gauge Cluster"
              class="a-carousel-img"></amp-img>
        </div>
        <div class="card card-engine">
          <amp-img src="https://ampbyexample.com/img/car-engine.jpg"
              width="340"
              height="192"
              layout="responsive"
              alt="Tuned Engine"
              class="a-carousel-img"></amp-img>
        </div>
      </div>
    </div>
  </body>
</html>
```

## Reference: reproducible ad 2

- A stripped down version using 'visibility' trigger
```javascript
<!DOCTYPE html>
<html amp4ads>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,minimum-scale=1">
    <style amp4ads-boilerplate>body{visibility:hidden}</style>
    <script async src="https://cdn.ampproject.org/amp4ads-v0.js"></script>
    <script async custom-element="amp-animation" src="https://cdn.ampproject.org/v0/amp-animation-0.1.js"></script>
    <style amp-custom>      
        .root-container {
            background: #000;
            color: #fff;
            font-family: 'Roboto', sans-serif;
            font-size: 12px;
            overflow: hidden;
            width: 320px;
            height: 480px;
            position: relative;
            margin: 0 auto;
            display: block;
          }
        .rectangle {
            background-color: orange;
            height: 480px;
            width: 160px;
        }
    </style>
</head>
<body>
    <amp-animation id="adAnim" layout="nodisplay" trigger="visibility">
        <script type="application/json">
            {
              "duration": "1s",
              "fill": "both",
              "direction": "alternate",
              "animations": [
                {
                  "selector": "#theRectangle",
                  "keyframes": [
                    { "transform": "translateY(0)" },
                    { "transform": "translateY(-384px)"}
                  ]
                }
              ]
            }
        </script>
    </amp-animation>
    <div class="root-container">
        <div class="rectangle" id="theRectangle"></div>
    </div>
</body>
</html>
```

**Comment by aghassemi** [comment]
@robmurtagh Thanks for reporting. Could you add what version of iOS and device you see impacted? On iOS 11.4 beta it seems to be working.

**Comment by robmurtagh** [comment]
Thanks @aghassemi. The issue is on iOS 11.3.1, but was also on the previous iOS version (I assume 11.2). Issue occurs on at least iPhone 6 and 8.

To confirm on desktop the second ad animates as below (gif has a low frame rate, it's smooth in real life):

![desktop](https://user-images.githubusercontent.com/5772846/40045518-712851d8-5822-11e8-8689-9930fc36d58e.gif)

But on mobile the animation never starts and you just have:

![img_2268](https://user-images.githubusercontent.com/5772846/40045618-b5e766b0-5822-11e8-8570-3b1042f7d9a8.png)

To check, you see this fixed on iOS 11.4 beta?

Thanks again for looking into it

**Comment by robmurtagh** [comment]
Hi @aghassemi. Just to let you know, I downloaded iOS 11.4 beta, and am still seeing the same non-animation issue as above. Might help investigations.

**Comment by robmurtagh** [comment]
Hey @aghassemi. Did you get a chance to check this one? Intrigued to hear if it worked on your device?

**Comment by mitjak** [comment]
I can confirm we are having a similar issue on iOS. Not working on iPhone X 11.3.1, iPhone 6S 10.3.2 and desktop Safari. It's working fine on Android and desktop Chrome.

Here'e a test page that we're using: https://campaigns-celtra-com.cdn.ampproject.org/c/s/campaigns.celtra.com/a4a/static/dfp3p.html

**Comment by jasti** [comment]
Thanks for the report, @robmurtagh. 
@lannka @keithwrightbos FYI

**Comment by aghassemi** [comment]
I have narrowed it down to:
the `play()` call failing on the WebAnimation polyfill when target is in a same origin `iframe` in Safari.

Investigating more soon.

@mitjak @robmurtagh Has this ever worked for you before (on the same version of Safari)? Based on the code, I can't se this being a regression (unless regressed due to a new Safari version)

**Comment by aghassemi** [comment]
@dvoytenko in case you have seen this before.

**Comment by aghassemi** [comment]
(only `play` calls seems to fail, updating currentTime works fine which explains why scrollbound animations wors). Unfortunately looks like this is related to the web-animation polyfill.)

**Comment by robmurtagh** [comment]
@aghassemi I've only tried with the current version of AMP so unfortunately can't help on whether this is a regression. I also noticed there were no visibility triggered animations in [the examples](https://ampbyexample.com/amp-ads/#amp-ads/introduction), so I don't think they could help establish a regression either.

**Comment by mitjak** [comment]
@aghassemi Looking through our test logs I can't find any test cases that would cover this. It is entirely possible that it isn't a regression.

**Comment by dvoytenko** [comment]
@aghassemi Hmm. No, not familiar. We tested a4a case thoroughly though, so it could be a regression. `/a4a/` endpoint should help with debugging it.

**Comment by robmurtagh** [comment]
Hey @aghassemi, any progress on this one? Like you say, it seems that generally the `seekTo` calls work, while `restart` etc doesn't. When you talk about web-animation polyfill, you mean [web-animations/web-animations-js](https://github.com/web-animations/web-animations-js) right?
