### ISSUE TITLE
amp-list: Performance investigation

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#15272]
From some partner feedback on AMP Roadshow APAC, we should investigate the performance of `amp-list` and `amp-mustache`. 

Specifically, we should ensure that it's competitive vs. the unideal `amp-iframe` escape hatch.

Internal tracking: `b/110545268`

**Comment by kristoferbaxter** [comment]
When you say performance... do you mean creation, updates, for small or large lists? All categories or a subset?

**Comment by choumx** [comment]
Initial render latency. Shouldn't be imprecise about performance, I know. 😄

**Comment by choumx** [comment]
Observations:
- The vast majority of CPU latency on initial render is due to the amp-bind interaction. 
- amp-mustache-0.2 is 40% smaller than amp-mustache-0.1 which helps.

Ideas:
1. Allow opt-out: add `binding="always|refresh|no"` attribute to amp-list
2. Make the scanning more efficient: add DOM diffing to amp-list re-renders to avoid reprocessing unchanged markup (@jridgewell MutationObserver won't work here)
3. Make the actual scanning faster: amp-list itself can detect bindings during sanitization to avoid use of `TreeWalker` entirely

(1) is underway in #16833.

**Comment by choumx** [comment]
I'm prototyping (3) right now and it appears to be 1.5 to 3x faster in some quick and dirty testing.

**Comment by choumx** [comment]
(3) implemented in #17229.

**Comment by choumx** [comment]
(2) is being implemented in #17000, though it won't help with bind scanning. 

Closing now that we have a better understanding of performance bottlenecks and improvements are being implemented.
