### ISSUE TITLE
Intent to Implement: amp-embed

### ISSUE THREAD

**Issue by nitzanvolman** [ampproject/amphtml#1527]
The specific need is to allow amp-ad code to be re-used in a scenario where amp-ad will not be semantically accurate, such as content recommendations.

**Comment by nitzanvolman** [comment]
As a suggestion:
Perhaps we can leverage the alias ability suggested in #1517 
and add an `<amp-ambed>` tag to the builtins as an alias to `<amp-ad>`

**Comment by rudygalfi** [comment]
Can this be closed out given #1607 was merged?
