### ISSUE TITLE
[INFRA] Missing ability to add a class after a timeout for visual-tests

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#15280]
Currently in visual-tests you can add a class to elements on [load/error](https://github.com/ampproject/amphtml/blob/master/examples/visual-tests/font.amp/font.amp.html#L99-L102).

There needs to be a way to add a class after some time has expired (`on-timeout-add-class`)

cc @rsimha @aghassemi

**Comment by rsimha** [comment]
@choumx @jridgewell can comment on whether it makes sense to (and if so, how to) add this test-only functionality to the runtime.

**Comment by nainar** [comment]
Usecase for this: For animations, taking a screenshot on load time isn't useful. If you are animating opacity, all you get is an empty container. Being able to take a screenshot at some point during the animation (even the end) is more helpful in identifying regressions.

**Comment by jridgewell** [comment]
Isn't timeout covered by the `on-error-X`?

**Comment by jridgewell** [comment]
I don't understand what this has to do with `<amp-font>`?

**Comment by nainar** [comment]
Nothing, I need this for animations. The link to font visual test was to just show an example of on-{load/error}-add-class in use.

**Comment by jridgewell** [comment]
> Currently in visual-tests you can add a class to elements on load/error.

This was an `amp-font` specific feature built into the extension.

> Nothing, I need this for animations.

What extension would define this?

**Comment by nainar** [comment]
I didn't realize that was extension specific thought that it was testing specific. 

I need it for `<amp-fx>` components.

**Comment by jridgewell** [comment]
I think this should be built there, then.

**Comment by nainar** [comment]
👍 - closing this bug then.
