### ISSUE TITLE
Interfaces should not have return statements

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#15293]
Linter complains when interface methods lack a return statement. The purpose of the interface is to annotate, its methods should not have bodies.

Failing job (other errors as well):
https://travis-ci.org/ampproject/amphtml/jobs/378987178

See `src/video-interface.js`

**Comment by rsimha** [comment]
I think we can mitigate this by using `eslint-plugin-jsdoc`, which is more sophisticated than the built in `valid-jsdoc`
