### ISSUE TITLE
Relative types should be valid

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#15295]
Linter complains about a "syntax error", when there isn't one:

src/service/video-manager-impl.js
![image](https://user-images.githubusercontent.com/254946/40032758-5f3abe7a-57aa-11e8-9d4b-63b2673a06a4.png)

**Comment by rsimha** [comment]
Nice catch. The built in `eslint` rule `valid-jsdoc` is not good enough. We should replace it with `eslint-plugin-jsdoc`, which doesn't flag that as an error.

This will be fixed by #15294.
