### ISSUE TITLE
Inline function types should have its return value read in linter

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#15296]
Linter complains when the following type class is set:

`src/service/video-manager-impl.js`

![image](https://user-images.githubusercontent.com/254946/40032883-cb3ba8a0-57aa-11e8-9dd0-d4e92a568f95.png)

**Comment by rsimha** [comment]
Nice catch. The built in `eslint` rule `valid-jsdoc` is not good enough. We should replace it with `eslint-plugin-jsdoc`, which doesn't flag that as an error.

This will be fixed by #15294.
