### ISSUE TITLE
demo viewer integration code must buffer messages if actual viewer code is not ready to receive message

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#1530]

**Comment by ericfs** [comment]
Doesn't it already do that?

https://github.com/ampproject/amphtml/blob/master/src/service/viewer-impl.js#L543

**Comment by erwinmombay** [comment]
@ericfs , i think we need one the other direction. ill clarify that i need to make this change in our demos mostly since this is going to be viewer related code.

Right now, visibility changes can get dropped if the viewer posted a message and the viewer code in amp.js has not started listening yet.

**Comment by cramforce** [comment]
In that case you may need a way to ask for viewability info.

**Comment by dvoytenko** [comment]
I think asking for whatever might have changed is rather cumbersome. "I'm ready to receive" is pretty common. I think we may already have it in other viewers implemented as well.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
