### ISSUE TITLE
How to integrate intentMedia third party service on AMP project

### ISSUE THREAD

**Issue by ziyed** [ampproject/amphtml#15301]
Recently i am developing an AMP project where i need to add intentMedia ( https://intentmedia.com ) third party service to track user record. This third party is totally based on javascript platform. Were i need to set or modify IntentMediaProperties, a global javascript variable based on user activities. 

I have tried it through amp-iframe component but could not achieved the goal. 

So how  i can integrate intentMedia service on AMP project?

## What's the issue?

Unable to integrate intentMedia ( https://intentmedia.com )  third party service on AMP project due to limitation of javascript support. How i can integrate intentMedia service on AMP Project? 

Any suggestion please...

## What browsers are affected?

All browsers

## Which AMP version is affected?

Version 1525461683159

**Comment by AcidRaZor** [comment]
You should be using the amp-analytics component and Google Tag Manager

Here is an example of my implementation that does Facebook and Google Analytics in one go:

```
<amp-analytics config="https://www.googletagmanager.com/amp.json?id=YOURGTM_CODE_HERE&gtm.url=SOURCE_URL" data-credentials="include" data-amp-replace="QUERY_PARAM"><script type="application/json">
		{
			"vars":{"custom_value": "QUERY_PARAM(custom_value_from_query_string)"}      
		}
	</script></amp-analytics>	
```

Google Tag Manager supports intentMedia

**Comment by ziyed** [comment]
Hi AcidRazor,

Thanks for the reply. I just not only send data to endpoint rather i need to dig much more that. i  need to execute and call all of these ( **Exit Unit**, **Overlay Unit**, **on page ads**, **rail unit** etc  )  services of intentMedia based on user activities. I need to trigger all these functionalities of intentMedia on User end based on user queries. I need to write values at ` window.IntentMediaProperties` and also retrieve data from there too but not in as a json value.

Please suggest. 

Thanks,
Ziyed

**Comment by AcidRaZor** [comment]
I know, and Google Tag Manager will help. I also showed you an example of how to pass data for everything to trigger. Please go to Google Tag Manager and see it's power.

**Comment by jpettitt** [comment]
Your best bet is to reach out to Intent Media and ask them if they have an AMP implementation.  You will not be able to run their (or any other) javascript on am AMP page.

**Comment by jpettitt** [comment]
Closing as infeasible. 

It may be possible for Intent Media to build an amp-analytics config, however it's not something the amp core team can do.  In the event that they do decide to implement it please create an "intent to implement" issue.
