### ISSUE TITLE
Bookend images are not loading if the bookend is too long.

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#15313]
## What's the issue?

When the bookend is too long, images at the bottom are not loading. I suspect it's because the runtime loads images based on the body scroll position, but the bookend implement its own scroll.

## How do we reproduce the issue?

1. Add a lot of articles to the bookend
2. Scroll
3. EXPECTED: bottom images should be visible
3. BAD: only the first images are loaded

**Comment by Enriqe** [comment]
Chatting offline it seemed that it was just an issue coming from the image provider service.

**Comment by gmajoulet** [comment]
We had an offline chat: it looks like the ``layoutCallback`` of ``amp-img`` is never called, causing the image to never load.
This could be caused by the runtime optimizing the loaded resources: the bookend scrolls in its own div and not in the body, so runtime can't know these images became visible.

**Comment by gmajoulet** [comment]
For what it's worth, it's actually just because the scroll happens in a div that's not the body, not because of the shadow root : )

**Comment by newmuis** [comment]
Maybe let's just use `<img>` instead of `<amp-img>` in the bookend?  My guess is it's not a huge loss.
