### ISSUE TITLE
Fix JsDoc related lint warnings - round 1

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#15312]
Let's fix the following for round 1:

- [x] cid*.js
- [x] 3p/
- [x] extensions/amp-ad/
- [x] extensions/amp-analytics/
- [x] extensions/amp-story-auto-ads/
- [x] extensions/amp-sticky-ad/

Tip to run lint on selected files:
```
gulp lint --files=a.js,b.js,c.js
```

Please reply to this thread if you start work on any of them.

**Comment by lannka** [comment]
I'm taking care of the `cid*.js` now.

**Comment by lannka** [comment]
I'm taking amp-analytics.

**Comment by calebcordry** [comment]
amp-story-auto-ads will be fixed with my incoming PR today

**Comment by lannka** [comment]
taking 3p/

**Comment by zhouyx** [comment]
@calebcordry Can we close this?

**Comment by calebcordry** [comment]
Yep, sorry I forgot about this.
