### ISSUE TITLE
No Ability To Pick Starting Index for <amp-carousel>

### ISSUE THREAD

**Issue by johnnyshankman** [ampproject/amphtml#1532]
This is a request for the ability to pass the starting index into an `<amp-carousel>`

I believe this line could be the trick
https://github.com/ampproject/amphtml/blob/master/extensions/amp-carousel/0.1/slides.js#L56

If we defaulted to 0 but pulled in the element's value for `data-index` instead when possible, devs could choose the starting index of a slide. 

This is an extremely common use case and I'm surprised it's not already a feature.

Right now the only option is to change the order of the `<amp-carousel>`'s children in the markup.

**Comment by johnnyshankman** [comment]
The context for this is that on my page I have multiple images. All of them, on tap, trigger a lightbox containing a slideshow. It would save a lot of time + space to have one slideshow with all of the slides in it, and then on tap I simply pass in the starting index.

Right now I'm forced to have a 1-1 relationship between lightbox-carousels and images.

**Comment by rudygalfi** [comment]
:+1: Good suggestion

**Comment by johnnyshankman** [comment]
Thank you! Hope to see this feature soon :)
It'll save my pages a *ton* of extra markup!

**Comment by johnnyshankman** [comment]
@rudygalfi any update on this?

**Comment by rudygalfi** [comment]
@ericlindley-g Will AMP Bind help this (note the very related #3128)?

**Comment by camelburrito** [comment]
@rudygalfi @johnnyshankman , we have added a method called goToSlide which will take you to a particular slide index on tap. This should go in prod with tomorrows release and we will update the documentation. 

If you are curious you can take a look at our manual test example here 
https://github.com/ampproject/amphtml/blob/master/test/manual/gallery.amp.html#L54
(use it for looking at the API, this is not meant to be example code)

soon ampbyexample.com will have excellent examples.

**Comment by ericlindley-g** [comment]
@johnnyshankman 

As @camelburrito says, you should be able to achieve the interaction you need by using the goToSlide method to advance a single carousel in the lightbox to the image clicked from the lightbox inlined on the page. 

I should note that we're also working on updates to `amp-image-lightbox` (/cc @aghassemi ), which will address your particular use-case more concisely, by allowing you to define groups of items for the lightbox (including a quick way to do this for amp-carousel). So, with little additional markup, you would be able to enable swiping between either the images from the carousel in the lightbox context.
