### ISSUE TITLE
<amp-auto-ads> suddenly response error with no more ads served

### ISSUE THREAD

**Issue by irvin** [ampproject/amphtml#15338]
## What's the issue?

This seems like a problem resulted from Adsense but not AMP side?

With no any change on our auto-ads implement, amp-auto-ads suddenly broken since yesterday with impression and income drop to around zero, the console shows below error message.

```
log.js:162 No anchor element found
log.js:162 unable to fulfill ad strategy  
```

## How do we reproduce the issue?

Open test page with Chrome mobile simulator (this error limit to mobile only)

Test page: https://womany.net/articles/3838/amp
(You can randomly switch article id between 1 to 10000 to see the problem on different articles. We have around 8k valid pages online.)

## What browsers are affected?

All mobile.

## Which AMP version is affected?

1525461683159, it was all fine 36 hours before.

**Comment by AcidRaZor** [comment]
The actual error is "amp-auto-ads config xhr failed: SyntaxError: Unexpected end of JSON input"
Your config file has changed/doesn't work.

**Comment by irvin** [comment]
@AcidRaZor that's typical response for adsense amp-auto-ads implement to response on desktop. You can get reported error if you open it with chrome RWD simulate mode.

**Comment by irvin** [comment]
Seems that it's been resolved on yesterday. Thanks.
