### ISSUE TITLE
<amp-analytic> type=comScore running with error message

### ISSUE THREAD

**Issue by irvin** [ampproject/amphtml#15336]
## What's the issue?

- implement type=comscore with amp-analytic get error:

```
Response unparseable or failed to send image request https://sb.scorecardresearch.com/b?c1=2&c2=27118713&cs_pv=6872&c12=amp-JzhWfR-lndaDdIkdutrrNA&rn=0.5595445010501083&c8=%E8%83%83%E7%97%9B%E4%B8%8D%E8%A6%81%E6%85%8C%EF%BC%8C%E5%9B%9B%E6%8B%9B%E6%90%9E%E5%AE%9A%E9%AC%A7%E8%84%BE%E6%B0%A3%E7%9A%84%E8%83%83%EF%BC%81%EF%BD%9C%E5%A5%B3%E4%BA%BA%E8%BF%B7%20Womany&c7=http%3A%2F%2Fwomany.net%2Fread%2Farticle%2F3838&c9=&cs_c7amp=https%3A%2F%2Fwomany.net%2Farticles%2F3838%2Famp
```

- test page: https://womany.net/articles/3838/amp#development=1 with settings: 
```
<amp-analytics type="comscore">
<script type="application/json"> {"vars": { "c2": "27118713" }}</script>
</amp-analytics>
```

- I had verified c2 is correct, and the request url (`sb.scorecardresearch.com/b...`) will response with Status Code: `204 No Content`

## How do we reproduce the issue?

open page : https://womany.net/articles/3838/amp#development=1

## What browsers are affected?

verified with Chrome / Firefox

## Which AMP version is affected?

1525461683159, it's my new trial so prior version can be confirm to work.

**Comment by jpettitt** [comment]
It's a warning you can safely ignore. What's happening is the comscore vendor config in amp-analytics is set to use `image` transport but comscore is returning 204 (no-content).  This is more of an annoyance than anything else, comscore still gets the data, you get get a console warning.  I'm not sure if switching to `beacon` transport would fix this.

**Comment by vipin08** [comment]
I got the same problem, my old HTML URL like 

URL: https://sb.scorecardresearch.com/p?c1=2&c2=xxxxxxxx&cv=2.0&cj=1

In AMP see URL is wrong /b if I change /p it working...

URL: https://sb.scorecardresearch.com/b?c1=2&c2=xxxxxx&cs_pv=xxx&c12=.....
