### ISSUE TITLE
Implement embed-size-denied

### ISSUE THREAD

**Issue by sriramkrish85** [ampproject/amphtml#1533]
signal back ads/iframes when we couldn't expand on their embed-resize request. Send a postMessage with embed-size-denied (when the runtime can't resize)so that they can provide their own overflow element within and repeat request on tap. In that case AMP will definitely allow size change due to user action.

This would be useful for both: iframes and ads

CC @dvoytenko, @cramforce

**Comment by dvoytenko** [comment]
We may also want to have the opposite message: `embed-size-changed` or such. This is because we automatically resize when an element gets focused.

**Comment by sriramkrish85** [comment]
how about we give them a callback in this function 
https://github.com/ampproject/amphtml/blob/master/3p/integration.js#L144

```
function triggerResizeRequest(width, height, callback) {
  nonSensitiveDataPostMessage('embed-size', {
    width: width,
    height: height,
  });
  // observe for embed-size-denied and embed-size-changed and 
  callback(status);
}
```

**Comment by dvoytenko** [comment]
Here, it'd probably have to have two callbacks: one for success and one for denied. But I'm not sure it'd be actually convenient here. These kind of callbacks might be just easier to subscribe to once and keep the listener.
