### ISSUE TITLE
Add support for developers to quickly test their changes locally before pushing them to GitHub

### ISSUE THREAD

**Issue by kristoferbaxter** [ampproject/amphtml#15369]
## What's the issue?

Travis is getting congested with builds containing linting errors. This is making it more difficult to get changes published.

Idea: Add an optional (disabled by default) `pre-push` hook that lints only the files change in a commit. If there is a failure, the push doesn't continue until the linting errors are resolved. This would allow frequent contributors to be more confident their changes will not fail during linting on Travis.

**Comment by rsimha** [comment]
I'm adding a `--local-changes` mode to `gulp lint` that will make it easy to lint just the files that your branch has touched.

We could in theory add a `git` pre-push hook, but I'm hesitant to make it mandatory.

/cc @jridgewell

**Comment by kristoferbaxter** [comment]
> We could in theory add a git pre-push hook, but I'm hesitant to make it mandatory.

Agree with not making it mandatory: it could be a no-op by default, and enabled via configuration.

**Comment by kristoferbaxter** [comment]
I've found Husky pretty valuable here too: https://www.npmjs.com/package/husky

**Comment by rsimha** [comment]
Reopening this because I'm going to add a `--local-changes` mode to `gulp test` as well, and then expose an opt-in `pre-push` hook.

**Comment by rsimha** [comment]
Reopening for `pre-push` hook.

**Comment by rsimha** [comment]
This is now fixed. If you're interested in running a `pre-push` hook before `git push`, you can enable it by running `./build-system/enable-git-pre-push.sh`.
