### ISSUE TITLE
A4A: Remove parseUrl usage

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#15375]
Hi @ampproject/a4a 

I'm moving URL parsing from an import into a AMP Doc service. Your usage in https://github.com/ampproject/amphtml/blob/a07137e6bbe3de880b4e5026a24d29d214e32300/ads/google/a4a/utils.js#L355-L383 will break.

I honestly have no idea what that function is trying to do, so I don't know how to refactor it for you. But, you can use `Services.viewerForDoc(nodeOrDoc)` to grab the new URL service if you want to keep everything the same.

**Comment by jridgewell** [comment]
Part of https://github.com/ampproject/amphtml/issues/14753.

**Comment by keithwrightbos** [comment]
Its attempting to string the protocol off of urls as we're only interested in sending the hostname.  I can change to use regexp.
