### ISSUE TITLE
add a 'paused' visibility state

### ISSUE THREAD

**Issue by ericfs** [ampproject/amphtml#1538]
When an document is swiped in the viewer, it is still visible in the window, but it also shouldn't be considered fully visible. For example, it would be good to pause videos.

The viewer will still send hidden to mean that the doc is completely hidden to the user.

**Comment by cramforce** [comment]
Tracked at Google in issue 26746276

**Comment by jridgewell** [comment]
Closed by https://github.com/ampproject/amphtml/pull/2212.
