### ISSUE TITLE
amp-list allow multiple keyed templates

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#15396]
`amp-list` should allow multiple templates which are keyed and the JSON data can decide (per row) which template should be used to render.

Rough suggestion for the API:
```
<amp-list width="auto"
  height="100"
  layout="fixed-height"
  src="/json/examples-empty.json"
  class="m1">
  <template id="text-template" type="amp-mustache">
    {{title}} - {{description}}
  </template>

  <template id="image-template" type="amp-mustache">
    <amp-img alt={{title}} src={{image_url}}></amp-img>
  </template>
</amp-list>
```

```
{
 "items": [
   {
     "title": "item 1",
     "description": "this is item 1",
     "amp-template-id": "text-template"
   },
   {
     "title": "item 2",
     "image_url": "img/pic.jpg",
     "amp-template-id": "image-template"
   }
 ]
}
```

# Questions
- What's the default template for items that don't return a template id?  first one? the one without id? (what if there is none or more than 1?)
- `amp-list` can have an external template that is referenced by Id as well, we want to allow that here as well? (e.g. search scope is whole document)
```
<template id=one>
<template id=two>
<amp-list>
  ...
</amp-list>
```
/cc @choumx @ericlindley-g

**Comment by jpettitt** [comment]
Won't be at design review. I think defaulting to the first template makes sense.  That's what already happens in the current single template case.

**Comment by aghassemi** [comment]
@choumx Good point. This essentially just adds `switch` functionality to something that already supports `if else`. Maybe exposing a more powerful templating system is the right approach here as you mentioned. I will put this on hold  and explore that option instead.
