### ISSUE TITLE
Create Material Components component for AMP

### ISSUE THREAD

**Issue by pbakaus** [ampproject/amphtml#15393]
MDC, short for Material Design Components, is a theme framework that implements popular components from the Material Design language. Here's the repo for the web version: https://github.com/material-components/material-components-web, and here's the [component catalogue](https://material-components.github.io/material-components-web-catalog/#/).

![image](https://user-images.githubusercontent.com/43004/40191725-28acf198-59b7-11e8-9c03-d8b44ec4a349.png)

An open question is how to actually do it: MDC requires both some lightweight JS and CSS. Ideally the CSS would be highly cached and not count toward the 50KB limit, but also ideally it would load synchronously so there's no FOUC.

Maybe a good discussion topic for the next eng design meeting?

**Comment by aghassemi** [comment]
Not something AMP Core should do. Organic community or MD team are the right group to implement this.
