### ISSUE TITLE
Add title and amp-bind state to history events sent to viewer

### ISSUE THREAD

**Issue by josh313** [ampproject/amphtml#15401]
Currently, the history events that are sent to the viewer only include the stackIndex and URL fragment. This should be expanded to also include the title and amp-bind state. The initial page title is sent via the documentLoaded message, but as of #14564, the page can now change its title via amp-bind, so we should notify the viewer of those changes via the history events. Sending the amp-bind state to the history events is useful because it allows the viewer to maintain history across different AMP pages if the page used AMP-to-AMP navigation and then the user clicked the browser back to go to the original page.

**Comment by choumx** [comment]
Fixed by #15436.
