### ISSUE TITLE
Add ability to collapse elements on rejected consent

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#15407]
Feature request:  add `data-collapse-on-consent-insufficient` and `data-collapse-on-consent-unknown`

Intended behavior is to avoid a hole in the page layout when consent gated elements are suppressed by user rejection or user dismissing the consent dialog.  Both flags would only apply after an initial consent dialog display had been accepted / rejected / dismissed.

Related to #13716

**Comment by lannka** [comment]
Shall we just always try the collapse, instead of offering an option?

**Comment by jpettitt** [comment]
Publisher may way to leave the placeholder

**Comment by lannka** [comment]
We can treat it the same way as "ads no fill" or "image not loaded", which has a predefined precedence of `fallback` and `collapse`. For ads, it is:
```
collapse > user provided fallback > default fallback
```

If we do want to give publisher to have difference precedence order, we should make it not specific to consent.

**Comment by jpettitt** [comment]
What about other elements - would we do the same thing?  (video players and iframes can both be in consent scope)

**Comment by zhouyx** [comment]
Each element has their own collapse logic. but from what I know most of them don't collapse. 

We tried to apply fallback when user reject. But there's some implementation details that prevent us from doing that in v1 : ) Basically element can override their own fallback logic, which is difficult for runtime to handle if element's buildCallback fails.

**Comment by jpettitt** [comment]
This is where having a `.consent-*` css class withe the current consent state on `<body>` would make life a lot easier.
