### ISSUE TITLE
amp-story: Add trigger in amp-analytics when the "tap to go to the next page" user edu overlay appears

### ISSUE THREAD

**Issue by vinaymahag** [ampproject/amphtml#15420]
## What's the issue?
Add a trigger in amp-analytics when the user education overlay appears.  Today the overlay appears when swiping horizontally.

**Comment by lannka** [comment]
Are we able to reuse the existing "visible" trigger?

**Comment by newmuis** [comment]
We should add this in our new education system.

cc @gmajoulet
