### ISSUE TITLE
Implement forbidden dependency tests

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1542]
This would allow us to prevent surprises where e.g. an extension depends on some file that is always in core (e.g. extension never depends on a core service).

Maybe we can get browserify to output the module dep graph and query that.

**Comment by cramforce** [comment]
Lets bring this back. #2973 for why this is important.

Ideally we identify files that must only be on core and automatically fail if an extension depends on them. Simpler, but also important is that we fail if an extension depends on another extension.

**Comment by erwinmombay** [comment]
@cramforce got it, complete forgot about the task. should we have a whitelist of allowed modules/files to be imported (like the facade's around the services)?

**Comment by cramforce** [comment]
Ideally we make get a module graph out of browserify (or whatever) and can run queries on it. Basically say: "The graph must not have a path from this file to this file"

**Comment by erwinmombay** [comment]
closed by https://github.com/ampproject/amphtml/pull/2976
