### ISSUE TITLE
`getViewerUrl` is it dead?

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#15425]
I don't see any usage of `viewer-impl.js:getViewerUrl()` method in our codebase other than tests. Is it dead?

/cc @dvoytenko @brandondiamond

**Comment by dvoytenko** [comment]
It looks like instead the `getResolvedViewerUrl` is in use.

**Comment by lannka** [comment]
@dvoytenko seems `getViewerUrl()` is just the promise version of  `getResolvedViewerUrl()`, which guarantees a url replacement from Viewer to be done first. 

I saw no direct user of `getViewerUrl()` in the code base, and  `getResolvedViewerUrl()` being used by 2 places:

- amp-access/login-dialog.js
- error reporting js

seems we would not be able to change the error.js usage, because it needs a sync call. can you take a look at the usage in amp-access/login-dialog.js? If it also does not need the promise version, we can start to remove dead code.

**Comment by dvoytenko** [comment]
@lannka Both of these cases have to rely on sync version of the `getViewerUrl`:

- login-dialog.js: must call `window.open()` synchronously to avoid popup blockers.
- error.js must issue an error ping asap to ensure it's sent before the page may be closed.

**Comment by lannka** [comment]
ok, then seems we don't have usage for the async method. I'll go ahead and remove it.

Let me know if you see a problem.

**Comment by erwinmombay** [comment]
This issue doesn't have a category which makes it harder for us to keep track of it. @torch2424 Please add an appropriate category.

**Comment by torch2424** [comment]
Oops, I think this was closed by #17404 . Can we close this @lannka ? I think you made a follow up issue for the refactor correct?
