### ISSUE TITLE
How to serve/load AMP extensions for any project on local dev?

### ISSUE THREAD

**Issue by AdsonCicilioti** [ampproject/amphtml#15434]
With the clear goal of developing a development environment (localhost).

The first idea is to give a clone of this entire repository and load the extensions directory path. This is an easier and dirty way. I would like your opinion if there is a better way and if the option of having the AMO extensions locally is good for the development phase.

Additional: at night I'm developing in a horrible place to connect to the internet. It would be great to have the extensions and the main AMP locally.

**Comment by jpettitt** [comment]
if you clone the repo, run `yarn` to install the dependencies then `gulp serve` you will have a local server on port 8000 with unminified copies of the local files including any new code.  It will automatically rewrite the JS file urls to the local copies.  See https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md and https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md

**Comment by jpettitt** [comment]
Closing as invalid because it already exists.

**Comment by AdsonCicilioti** [comment]
Yarn with Nodejs v10 in Windows Dont work.
