### ISSUE TITLE
[FR] hidden input can't trigger amp-form validation 

### ISSUE THREAD

**Issue by AndrewKGuan** [ampproject/amphtml#15437]
Now with amp-bind working with <input type="hidden" [value]="myAMPState" required>, it'd be nice if it could trigger form validation error on submit.

**Comment by cvializ** [comment]
Unfortunately it looks like the HTML spec forbids hidden inputs from affecting validation.

> [4.10.5.1.1 Hidden state (type=hidden)](https://html.spec.whatwg.org/multipage/input.html#hidden-state-(type=hidden))
> Constraint validation: If an input element's type attribute is in the Hidden state, it is barred from constraint validation.
> The following content attributes must not be specified and do not apply to the element: accept, alt, checked, dirname, formaction, formenctype, formmethod, formnovalidate, formtarget, height, list, max, maxlength, min, minlength, multiple, pattern, placeholder, readonly, **required**, size, src, step, and width.

We try to match the behavior of the HTML spec, so AMP will probably not implement validating `required` for `input[type=hidden]`.
