### ISSUE TITLE
Flag for strict linting

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#15433]
Having things fail on Travis but not locally kinda sucks. We should add a flag that will use strict linting locally.

**Comment by rsimha** [comment]
`gulp lint --local-changes` already does this.

The only exception is when you change the lint rules themselves, in which case we default to running the linter on all files in warning mode.

Does this work for you?

**Comment by rsimha** [comment]
Note that you can also use `gulp lint --files=<glob>`, which runs lint on the files in the <glob> in error mode.

What files are you editing?

**Comment by rsimha** [comment]
Seems like you're talking about https://travis-ci.org/ampproject/amphtml/jobs/380843162#L662.

You could've run `gulp lint --local-changes` to catch this before pushing.

I'm adding a `pre-push` hook in #15369, which will give you the option to run this before a push.
