### ISSUE TITLE
How to scroll in amp-lightbox to mobile?

### ISSUE THREAD

**Issue by aikt** [ampproject/amphtml#1544]
Hi,

I testing amp-lightbox, so i have a button to open the box, in this box i have a menu vertical, but is very large in height, i put in the css overflow-y: scroll to element (.-amp-fill-content ), in the desktop its works fine, but in iphone 5 or samsung mobile, dont work, any idea to fix this?.

Thanks, sorry for my english.

**Comment by dvoytenko** [comment]
@aikt - yes, we can fix this. We will have to add `scrollable` attribute or something like that to the lightbox element. There's a lot going on to enable scrolling without glitches, on iOS especially. However, this is a bit different from the intent of lightbox. Could you please describe your use case in a bit more detail? Perhaps we're missing an extension...

**Comment by 88kbbq** [comment]
Yes, I'm having a similar issue #1463. I really wish there was either some inline javascript allowed, like a small 20kb snippet before the closing body tag. The next best thing would be some common menu functionality, like dropdown menus, hamburger-styel menus, etc. So far, there is no easy way to introduce unobtrusive mobile navigation on small device screens.

**Comment by dvoytenko** [comment]
@88kbbq I don't think adding 20Kb of JS would be very helpful for scrolling - it's rather hard to set up correctly for all intended use cases.

/cc @rudygalfi for menus, hamburgers, etc.

**Comment by rudygalfi** [comment]
Menu is on our roadmap: https://github.com/ampproject/amphtml/issues/827

**Comment by cramforce** [comment]
Can this be closed? I think we could consider a more generic modal dialog, but scrolling is definitely beyond the scope of `amp-lightbox`.

**Comment by dvoytenko** [comment]
I got an impression that this is specifically about creating a menu.
