### ISSUE TITLE
AMP Shadows + Geolocation-based Consent Flow

### ISSUE THREAD

**Issue by jlcara** [ampproject/amphtml#15440]
## What's the issue?
Geolocation-based Consent Flow not loading in AMP Shadows (AMP in PWA)

## How do we reproduce the issue?

I converted my site to AMP in PWA as explained in [https://codelabs.developers.google.com/codelabs/amp-pwa-workbox/](https://codelabs.developers.google.com/codelabs/amp-pwa-workbox/)

Then I added Geolocation-based Consent Flow following [https://ampbyexample.com/user_consent/geolocation-based_consent_flow/](https://ampbyexample.com/user_consent/geolocation-based_consent_flow/)

After that i got this error in the Console: 
dom.js:786 requires <amp-geo> to use promptIfUnknownForGeoGroup

## What browsers are affected?
Chrome 66.0.3359.181 (Build oficial) (64 bits)

## Which AMP version is affected?
AMP ⚡ HTML shadows – Version 1526498116488

**Comment by jpettitt** [comment]
Can you post an example url?  

That error typically happens when `amp-geo` is missing or misconfigured.  If `amp-geo` is working you should see geo related classes on the `body` of the rendered page.

Assuming a valid and `amp-geo` config try switching to the dev channel at https://cdn.ampproject.org/experiments.html and see if it works there.

**Comment by jpettitt** [comment]
Is there a link to a public facing page we can look at?

**Comment by jlcara** [comment]
No, I deployed my site as AMP **as** PWA. So I can't help you with that.

**Comment by jpettitt** [comment]
Without a reproducible test case (or the url of your production site) there is not much we can do.

**Comment by joselanderosmrf** [comment]
we have the same issue. It seems that on services we are looking for service `"geo"`:
https://github.com/ampproject/amphtml/blob/a2121779d508f56c7da891979ddb0d73334c084b/src/services.js#L475
but in the list of services geo is registered as `"amp-geo"`

**Comment by jpettitt** [comment]
`geo` is the name of the service.  It explicitly registered as that.  

```JS
 getElementServiceIfAvailable(win, 'geo', 'amp-geo', true);
```

Is saying get me the service called `geo` from the extension called `amp-geo` which is correct.

Where are you seeing the service registered as `amp-geo`?  Do you have a repro case?

**Comment by joselanderosmrf** [comment]
I found the issue, the problem is that in amp-consent we are looking for the geo service in the window and in shadow this service is registered on the element/ampdoc not on the window. I fixed it on our fork and it seems to be working fine on both nonshadow and shadow so I have submitted the pr.

**Comment by jpettitt** [comment]
Thanks, much appreciated.
