### ISSUE TITLE
[Feature Request] Credential Managment and Web Auth 

### ISSUE THREAD

**Issue by AhsanE** [ampproject/amphtml#15454]
## What's the issue?

The Credential Management API is not allowed from an iframe as only top level context can utilize it. AMP should provide a way to use the Credential Management API from amp-access, so platforms can use Web Auth, which is a part of Credential Management API for one click signup or signin. 

## How do we reproduce the issue?
https://developer.mozilla.org/en-US/docs/Web/API/Credential_Management_API

## What browsers are affected?

All browsers.

## Which AMP version is affected?
all

**Comment by jpettitt** [comment]
This would not be possible for AMP because AMP is designed to be embeddable and as such is served in an `iframe` in contexts where a viewer is in use (eg google search).

**Comment by AhsanE** [comment]
Is this not going to be possible even if the upcoming Signed Web Packages become a standard? Why would the page need be inside an ` iframe` after that?

**Comment by iwoak** [comment]
Hi @jpettitt, we have a large usage of amp canonical on both mobile and desktop on our premium site https://rep.repubblica.it. So, if we could use Credential Management API with AMP (amp-subscriptions) would enable us to develop autologin between site and native mobile apps. This would be a great thing for us!

**Comment by jpettitt** [comment]
I'll take another look.  @dvoytenko @cramforce WDYT?

**Comment by cramforce** [comment]
Super important to support this well. While there may be challenges to support in on AMP caches, I think we just need a strong fallback story, similar to fallbacks for browsers that don't support the API.
