### ISSUE TITLE
amp-state: "Viewer must be visible" when opening link

### ISSUE THREAD

**Issue by trvanhai4** [ampproject/amphtml#15450]
## What's the issue?

I got this error: _Viewer must be visible before mutation_ when trying to fetch remote state while opening a link in a new tab.

## How do we reproduce the issue?

We want to fetch remote state and also open a new tab with an anchor. Please try running this _https://gist.github.com/trvanhai4/3631b110c6bbfa35bbb93892dd7286df_ on AMP playground: _https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-bind%2Fsource%2F&mode=iPhone+7_.

## What browsers are affected?

- The error happens on Chrome Version 66.0.3359.181 (Official Build) (64-bit) and Safari Version 11.1 (13605.1.33.1.4)
- It's not happen on Firefox 59.0.3 (64-bit)

## Which AMP version is affected?

AMP ⚡ HTML – Version 1526498116488

**Comment by jpettitt** [comment]
What are you trying to achieve?  It looks like you want the link to open a new tab and mutate `amp-state`.

**Comment by trvanhai4** [comment]
@jpettitt Yes, I want to do that, opening a new tab and also calling an ajax to update amp-state!

**Comment by choumx** [comment]
Thanks for reporting this. Should be a straightforward fix.

**Comment by choumx** [comment]
This is an [interaction with AMP viewers](https://github.com/ampproject/amphtml/blob/master/extensions/amp-viewer-integration/integrating-viewer-with-amp-doc-guide.md) to ensure that we avoid sending network requests while the AMP document is in "prerender" mode (which has privacy concerns).

The AJAX should be called if the page is not embedded (no viewer) or when the page has been visible once.

**Comment by trvanhai4** [comment]
Hi @choumx; Do we have any updates on this ticket?

**Comment by trvanhai4** [comment]
Hi @choumx; Could you guide us on the root cause of the issue then we can process with a PR as this is a blocker for us.

**Comment by choumx** [comment]
@trvanhai4 Sorry about the delay. Will fix this week.
