### ISSUE TITLE
Handling paginated content

### ISSUE THREAD

**Issue by pierrefar** [ampproject/amphtml#1546]
Hello

I can't find any support for paginated AMP content. The [HTML standard](https://html.spec.whatwg.org/#sequential-link-types), supported by [Google indexing](https://support.google.com/webmasters/answer/1663744?hl=en) and others, is to use link elements with rel=next and rel=prev.

This usage of <link> is explicitly disallowed for AMPs as per [AMP HTML spec](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md).

**Comment by dvoytenko** [comment]
I don't think they are explicitly disallowed. Could you pls clarify where you see that?

/cc @cramforce @Gregable

**Comment by cramforce** [comment]
Here is the full list of allowed rel values. `next` and `prev` and in there. We should update the docs accordingly.

**Comment by jridgewell** [comment]
@cramforce: Did you mean to link to the allowed `rel` values?

**Comment by cramforce** [comment]
@jridgewell Yeah, sorry. Forgot to paste.
