### ISSUE TITLE
"Enabled" trigger in analytics not consistently disabling trigger

### ISSUE THREAD

**Issue by cwisecarver** [ampproject/amphtml#15463]
## What's the issue?

Parse.ly heartbeats are sometimes firing with zero incremental engaged time. This should be impossible since the enabled property of the trigger is set to getIncrementalEngaged time and a zero response should evaluate to false-y and therefor not be triggered. It is definitely not happening all the time. When incremental engaged time was first released without the `enabled` property on the trigger we saw a much larger increase in traffic. 

This leads me to believe that something in the conditional trigger isn't working cross-browser properly or that it's some sort of race condition where the enabled property of the trigger is being fired and coming back true but it's getting reset before the heartbeat actually fires and is sending 0 incremental engaged time.

## How do we reproduce the issue?

Here are some sample urls we've seen the issue occur on.

- http://people.com/royals/royal-wedding-prince-charles-reception-speech/amp/?xid=amprecirc2
- https://nypost-com.cdn.ampproject.org/v/s/nypost.com/2018/05/20/possible-yankees-call-ups-after-clint-frazier-gets-the-bad-news/amp/?amp_js_v=0.1&usqp=mq331AQGCAEYASgB
- https://www-cnbc-com.cdn.ampproject.org/v/s/www.cnbc.com/amp/2018/05/20/muellers-office-said-to-plan-wrapping-up-trump-probe-by-september.html?amp_js_v=0.1
- https://www-express-co-uk.cdn.ampproject.org/v/s/www.express.co.uk/news/royal/963005/Meghan-Markle-Prince-Harry-honeymoon-doomed-destination-royal-wedding/amp?amp_js_v=0.1&usqp=mq331AQGCAEYASgB
- https://www-newyorker-com.cdn.ampproject.org/v/s/www.newyorker.com/culture/culture-desk/review-john-mulaneys-high-achiever-comedy-in-kid-gorgeous/amp?amp_js_v=0.1&usqp=mq331AQGCAEYASgB
- https://www.gala.fr/l_actu/news_de_stars/video-apres-pippa-middleton-le-fessier-de-la-meilleure-amie-de-meghan-attire-tous-les-regards_415495?amp
- https://people-com.cdn.ampproject.org/v/people.com/royals/prince-harry-meghan-markle-wedding-portraits-released/amp/?amp_js_v=0.1&usqp=mq331AQGCAEYASgB
- http://people.com/royals/royal-wedding-meghan-markle-suits-costar-rick-hoffman-gushes-other-worldly-experience/amp/?xid=amprecirc2
- https://uproxx.com/hitfix/deadpool-2-deathstroke-dc-marvel-teen-titans/amp/
- https://www.cnbc.com/amp/2018/05/20/muellers-office-said-to-plan-wrapping-up-trump-probe-by-september.html
- https://www-self-com.cdn.ampproject.org/v/s/www.self.com/story/vagina-changes-after-birth/amp?amp_js_v=0.1&usqp=mq331AQGCAEYASgB
- https://amp-history-com.cdn.ampproject.org/v/amp.history.com/news/10-famous-korean-war-veterans?amp_js_v=0.1&usqp=mq331AQGCAEYASgB
- https://m-viva-co-id.cdn.ampproject.org/v/s/m.viva.co.id/amp/berita/nasional/1038570-ada-suara-gemuruh-keras-muncul-di-gunung-merapi?amp_js_v=0.1&usqp=mq331AQGCAEYASgB
- https://www-dailystar-co-uk.cdn.ampproject.org/v/s/www.dailystar.co.uk/news/latest-news/704105/royal-wedding-meghan-markle-prince-harry-doria-ragland-windsor-thomas-markle/amp?amp_js_v=0.1&usqp=mq331AQGCAEYASgB
- https://m-huffingtonpost-es.cdn.ampproject.org/v/s/m.huffingtonpost.es/amp/2018/05/17/fotos-asi-es-la-casa-que-han-comprado-pablo-iglesias-e-irene-montero_a_23437214/?amp_js_v=0.1&usqp=mq331AQGCAEYASgB
- http://amp.timeinc.net/cyclingweekly/news/product-news/need-clutch-rear-derailleur-380721?source=dam
- https://www.telegraph.co.uk/news/2018/05/21/royal-wedding-latest-news-meghan-markle-prince-harry-head-home/amp/
- https://amp-timeinc-net.cdn.ampproject.org/c/amp.timeinc.net/time/5284832/empty-seat-at-the-royal-wedding
- https://www.cnbc.com/amp/2018/05/21/us-china-trade-focus-on-structural-changes-not-deficit.html
- https://people-com.cdn.ampproject.org/v/people.com/royals/saturday-night-live-mocks-royal-wedding-reception/amp/?amp_js_v=a1&amp_gsa=1

## What browsers are affected?

Here are some of the user agents. They appear to be limited iOS and Android. I only saw one desktop user agent and it was Edge.

Mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
Mozilla/5.0 (iPhone; CPU iPhone OS 11_3_1 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) GSA/49.0.195456936 Mobile/15E302 Safari/604.1
Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_6 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0 Mobile/15D100 Safari/604.1
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1
Mozilla/5.0 (iPhone; CPU iPhone OS 11_3_1 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) CriOS/66.0.3359.122 Mobile/15E302 Safari/604.1
Mozilla/5.0 (Linux; Android 8.0.0; SM-G950U Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.158 Mobile Safari/537.36
Mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E302
Mozilla/5.0 (Linux; Android 8.0.0; SM-G955U Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.158 Mobile Safari/537.36
Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_5 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0 Mobile/15D60 Safari/604.1
Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_1 like Mac OS X) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0 Mobile/15C153 Safari/604.1
Mozilla/5.0 (Linux; Android 7.0; SM-G930F Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.158 Mobile Safari/537.36
Mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) GSA/49.0.195456936 Mobile/15E216 Safari/604.1
Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_2 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0 Mobile/15B202 Safari/604.1
Mozilla/5.0 (Linux; Android 8.0.0; SM-N950U Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.158 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 8.0.0; SM-G950F Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.158 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 7.0; SM-G935F Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.158 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 7.0; SM-G930V Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.158 Mobile Safari/537.36
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.0 Mobile/14F89 Safari/602.1
Mozilla/5.0 (Linux; Android 8.1.0; Pixel Build/OPM4.171019.016.B1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.158 Mobile Safari/537.36
Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_6 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Mobile/15D100 Flipboard/4.2.7

## Which AMP version is affected?

It started happening after the release on 2018.05.08.

**Comment by cwisecarver** [comment]
https://github.com/ampproject/amphtml/pull/14716 is the PR that enabled incremental engaged time without firing zero heartbeats.

**Comment by lannka** [comment]
@cwisecarver I found the root cause and had a fix.

**Comment by cwisecarver** [comment]
Thanks @lannka. I can’t believe I didn’t catch that initially. Sorry for the trouble. Thanks for the fix.

**Comment by lannka** [comment]
@cwisecarver you're welcome. the fix will go to canary later today, so you can do some more test. It will hit prod next Tuesday.

**Comment by cwisecarver** [comment]
I tested it on an Android device running the Google News app, hitting AMP pages, watching with mitmproxy and saw no `inc=0` heartbeats.
