### ISSUE TITLE
Google indexes my API defined in amp-list

### ISSUE THREAD

**Issue by AcidRaZor** [ampproject/amphtml#15487]
Hi guys, recently launched my AMP pages, and noticed some keywords that I used to look up to see where I rank, popped up with a direct link to my API that was used in amp-list??

I added a disallow to my robots.txt, but I have never had a bot index me when I use an API to access data. 

it looks like the search engine ignores amp-list and treats it as a normal href to follow and indexes it? This will be a very bad experience for my users AND google considering they'll just see a bunch of json data.

Is there someone that can slap around someone else on the search engine team to explain this behavior please? Maybe someone missed something (or if I missed something in the docs, please feel free to label me n00b) 

Thanks!

**Comment by aghassemi** [comment]
Hi @AcidRaZor, I suspect the returned `content-type` for the JSON endpoint might be wrong. Do you have a Url we can take a look at? I don't know whether crawler tries to index your endpoint on amplist or not (I suspect not) but even if it did, it would not be indexing `content-types` that are `application/json` or similar.

**Comment by AcidRaZor** [comment]
Thanks @aghassemi . I see the API developer didn't set the correct content-type for the end-points. This does sound like a good reason why Google would index the page, but as I mentioned, the only links to the API is used by amp-list, nowhere do we do a href= as a normal hyperlink the bot could follow like a user.

Now to go API Developer hunting with my trusty cross-bow ;)
