### ISSUE TITLE
Add ability sample triggers based on a sampleSpec.

### ISSUE THREAD

**Issue by avimehta** [ampproject/amphtml#1550]
See details of spec in https://github.com/ampproject/amphtml/issues/1550#issuecomment-188527377

**Comment by rudygalfi** [comment]
Seeking clarification on this: What would the underlying event tie be? Randomly per page view, per click, per whatever?

**Comment by avimehta** [comment]
That's an open question. GA has historically done sampling based on clientId. If we can get that, that would be best. Otherwise, per pageview would have to do... I am open to listening for more requests, suggestions.

**Comment by avimehta** [comment]
@rudygalfi assign this to me?

**Comment by avimehta** [comment]
Thinking of implementing it as follows:

```
"triggers": {
  "sampledRequest": {
⋮
   "sampleSpec": { 
      "trait": "${clientId}",
      "threshold": 1
    }
⋮
  }
}
```

@btownsend  what do you think? This allows for sampling based on `RANDOM` and `CLIENT_ID`  vars.

**Comment by btownsend** [comment]
The structure looks fine to me. Agree that "trait" is not a great name.

Can you clarify how you'll transform the trait value into a number that can be evaluated against the threshold?

**Comment by avimehta** [comment]
Could call it criterion/criteria but they are more complicated words.

I am planning to calculate a [SHA384](https://en.wikipedia.org/wiki/Secure_Hash_Algorithm) of the expanded trait and using the lower index to do sampling. [SHA384](https://github.com/ampproject/amphtml/blob/master/third_party/closure-library/sha384.js)  is easily available in AMP and already used for client ids.

**Comment by avimehta** [comment]
@cramforce do you see any issues with this?

**Comment by cramforce** [comment]
I think this looks good.

Recently Chrome fixed its issues with distribution of `Math.random()`, but  using a crypto hash is certainly safer. The hashing itself it quite expensive and would be unnecessary if we know the value came from a crypto hash anyway, but this is probably fine.

**Comment by avimehta** [comment]
Thanks. Just to clarify, I need some kind of hash. If there is a cheaper hashing function available in AMP, I would be happy to use that instead of more expensive sha384.

I basically need to convert the string into a number so that I can do sampling based on that.
