### ISSUE TITLE
cdn data:image/svg+xml; url failing

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#1555]
[not sure where to file bugs against the CDN ...]

I've been testing some amp-carousel code, it works fine on our CDN, passes the validatior, it also passes the validatior and displays on cdn.ampproject.org except that the svg's for the next/prev are being blocked by cors.

`Refused to load the image 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="#fff" viewBox="0 0 18 18"><path d="M15 8.25H5.87l4.19-4.19L9 3 3 9l6 6 1.06-1.06-4.19-4.19H15v-1.5z" /></svg>' because it violates the following Content Security Policy directive: "default-src *". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.`

**Comment by cramforce** [comment]
@jpettitt Is this a good test case for your problem? It works for me in Chrome and Safari https://cdn.ampproject.org/c/output.jsbin.com/puzuwu/quiet

**Comment by cramforce** [comment]
Ah, Firefox fails. Did you see it failing anywhere else?

**Comment by cramforce** [comment]
Never mind. See it in Chrome.

**Comment by cramforce** [comment]
Will get fixed on our end

**Comment by cramforce** [comment]
This should now work again.
