### ISSUE TITLE
amp-geo doesn't create groups for unknown countries

### ISSUE THREAD

**Issue by QES** [ampproject/amphtml#15554]
Looking at amp-geo as part of my GDPR work I was trying to show something to people outside of the EEA, I have a amp-geo that looks like:

```
<amp-geo layout="nodisplay" class="sm_geo" >
	<script type="application/json">
			{
			  "ISOCountryGroups": {
				"eea": [ "at", "be", "bg", "cy", "cz", "de", "dk", "ee", "es", "fi", "fr",
				"gb", "uk", "gr", "hr", "hu", "ie", "is", "it", "li", "lt", "lu", "lv", "mt", "nl",
				"no", "pl", "pt", "ro", "se", "si", "sk"],
				"main": [ "at", "be", "bg", "cy", "cz", "de", "dk", "ee", "es", "fi", "fr",
				"gb", "uk", "gr", "hr", "hu", "ie", "is", "it", "li", "lt", "lu", "lv", "mt", "nl",
				"no", "pl", "pt", "ro", "se", "si", "sk", "us", "ca", "ng", "ke", "za", "ua"],
      				"other": [ "unknown" ]
			  }
			}
	</script>
</amp-geo>
```
I have used Opera and its VPN code to be in a different location and I can see the BODY element showing

<body style="opacity: 1; visibility: visible; animation: none;" class="amp-mode-mouse amp-geo-group-main amp-iso-country-ua">

But when I remove us from the list of main countries the "other" flag is not set.

ALan

**Comment by jpettitt** [comment]
That's expected behavior.    `unknown` means we couldn't determine the country for the IP address.  This lets you decide if you want to treat un-located users as in or out of any given group.  There is no mechanism to says 'it didn't match any group'.

How important is this?  We could have the geo script add `amp-geo-nogroup` if the array of matched groups is empty.

**Comment by QES** [comment]
Thanks John - that all makes sense.  I think the problem is the examples confuse by having 'unknown' given a name that looks like a default when it isn't the default is set in the css https://www.ampproject.org/docs/reference/components/amp-geo

amp-geo-nogroup would do the trick

the :not work around might well solve the problem - thanks for the idea.
