### ISSUE TITLE
Wordpress embed does not work well in AMP

### ISSUE THREAD

**Issue by ceejothomas** [ampproject/amphtml#15552]
## What's the issue?

When an article embeds another article in wordpress, the embedded article does not well in AMP. In desktop browsers it shows correctly as an embed but in AMP the entire embedded articles loads in a small windows in the original article. This causes issues in display as well as shows wrong traffic data in google analytics
![amp embed issue](https://user-images.githubusercontent.com/28773536/40467848-04e17882-5f49-11e8-8b9b-9c02faeb22b1.png)

## How do we reproduce the issue?
AMP url ( Please check on mobile devices - Android - Chrome )

This is a malayalam language site 

http://www.azhimukham.com/india-new-karanataka-swearing-in-ceremony-build-opposition-unity-for-2019-election/amp/

This the desktop url which works fine

http://www.azhimukham.com/india-new-karanataka-swearing-in-ceremony-build-opposition-unity-for-2019-election/

## What browsers are affected?

Chrome on Android 

## Which AMP version is affected?

It has always been like this since wordpress launched the embed feature more than a year back

**Comment by jpettitt** [comment]
This is a bug in the Wordpress amp implementation you are using.   Please file a bug against that plugin on the Wordpress plugins site.
