### ISSUE TITLE
Expose access-related events and variables to analytics

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#1556]
Expose the following events from AMP Access system to AMP Analytics:
`amp-access-auth-received` `amp-access-pingback-sent`, `amp-access-login-started`, `amp-access-login-success`, `amp-access-login-failure`

Expose values for AUTHDATA. e.g. ampAccessAuthdata.subscriber_id would give a subscriber_id provided via AUTHDATA.

cc @dvoytenko @ashwinlimaye

**Comment by dvoytenko** [comment]
Partial implementation in #1890.

**Comment by georgecrawford** [comment]
This issue is now closed - is there any update for the docs at https://github.com/ampproject/amphtml/blob/master/extensions/amp-access/amp-access-analytics.md, which refer to this issue?

**Comment by rudygalfi** [comment]
The documentation was updated here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-access/amp-access-analytics.md#access-analytics-variables

**Comment by georgecrawford** [comment]
Thanks. I was referring to this passage:
> An integration with amp-analytics is under development and can be tracked on Issue #1556. This document will be updated when more details on the integration are available.
which implies that we should check this (closed) ticket for updates. Perhaps that's no longer relevant?

Do you have a roadmap or an ETA for when access analytics will become fully supported, and no longer require an experiments flag?

Thanks

**Comment by amphtml-team** [comment]
+Rudy, Dima can you say when the access analytics support will be launched?

**Comment by rudygalfi** [comment]
We're hoping to get this out next week (first week of March).

**Comment by georgecrawford** [comment]
Hi. I see the reader has been updated to remove the experiment flag. Is amp-access-analytics now live across the board?

**Comment by georgecrawford** [comment]
Typo above: *readme*

**Comment by ashwinlimaye** [comment]
Yes, it is live now
