### ISSUE TITLE
Build the equalizer icon for videos without controls

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#15571]
The equalizer icon seems like it should be shown on any video with the `autoplay` attribute.  Right now, it is only shown on videos with the `autoplay` and `controls` attributes *both* specified.  Is there a way to enable this for `autoplay` videos without controls?

Note: if this seems like a breaking change, I wonder if we can build it but hide it by default, and allow showing it with CSS?

/cc @alanorozco

**Comment by aghassemi** [comment]
fixed by https://github.com/ampproject/amphtml/pull/15967 🎉
