### ISSUE TITLE
amp-list error reading json

### ISSUE THREAD

**Issue by jlcara** [ampproject/amphtml#15582]
## What's the issue?

I'm converting a Google SpreadSheet to JSON and publishing it on Amazon S3. See the file [here ](https://s3.amazonaws.com/jlcaraseo.com/amp/1GEIOkpEZlm--C5KEE3Tns8rsVZdDValWCYJrCkD-3Xw.json).

I got from different places that it's a valid JSON, but when using "amp-list" it gets an error.

I'm not able to get rid off of the double quotes around the JSON object. It seems to be saving the string with those quotes .

## How do we reproduce the issue?

1. Copy this snippet

        <amp-list width="auto" height="100" layout="fixed-height" src="https://s3.amazonaws.com/jlcaraseo.com/amp/1GEIOkpEZlm--C5KEE3Tns8rsVZdDValWCYJrCkD-3Xw.json" class="m1">
        <template type="amp-mustache" id="amp-template-id">
          <div><a href="{{url}}">{{title}}</a></div>
        </template>
        </amp-list>

2. Go to: [https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-list%2Fsource%2F&mode=Responsive](https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-list%2Fsource%2F&mode=Responsive)

3. Replace the body tag with the snippet

4. Check dev tools error:

`Response must contain an array at " items ". <amp-list width=​"auto" height=​"100" layout=​"fixed-height" src=​"https:​/​/​s3.amazonaws.com/​jlcaraseo.com/​amp/​1GEIOkpEZlm--C5KEE3Tns8rsVZdDValWCYJrCkD-3Xw.json" class=​"m1 i-amphtml-element i-amphtml-layout-fixed-height i-amphtml-layout-size-defined i-amphtml-layout i-amphtml-error" aria-live=​"polite" style=​"height:​ 100px;​">​…​</amp-list>​`

## What browsers are affected?

Tested on Chrome last version

## Which AMP version is affected?

1527021682973

**Comment by jlcara** [comment]
Solved on the Google Scripts side :)

**Comment by modernwarfareuplink** [comment]
Also, If you are processing a json instead of list you could use. @jlcara 
<amp-list **items="." single-item** ......>
...
</amp-list>
