### ISSUE TITLE
AMP Project support for Google One Tap

### ISSUE THREAD

**Issue by SteCQ** [ampproject/amphtml#15584]
Are their plans to support Google One Tap, or even general support for social sign on? This would be a major step in enabling AMP pages to act as very effective conversion landing/splash pages.

**Comment by rudygalfi** [comment]
This is referring to https://developers.google.com/identity/one-tap/web/overview

As of this point there are no plans yet, but we'll investigate it.

**Comment by myupchar** [comment]
I am also interested as lack of it has really dropped our user registration numbers
