### ISSUE TITLE
Allow RTC call-outs to be made when user rejects amp-consent

### ISSUE THREAD

**Issue by oliverfernandez** [ampproject/amphtml#15588]
The current RTC implementation in Doubleclick does not make the RTC call-outs when an `amp-consent` component is present, the `amp-ad` contains the attribute `data-block-on-consent` and the user rejects the consent.

The proposal is to allow RTC calls when user rejects the consent, sending to the RTC endpoint a query param with the consent status. The values  would be the same `UNKNOWN`,  `SUFFICIENT`, `INSUFFICIENT` or `UNKOWN_NOT_REQUIRED` depending on the user choice

This would allow, for example, a server side header bidding with non personalized ads

**Comment by keithwrightbos** [comment]
This is fine however the publisher must explicitly opt-in to this behavior change either across all RTC call-outs or one by one via the a new sendRegardlessOfConsentState option.  Examples given:

`rtc-config='{
            "vendors": {
              "vendorA": {"SLOT_ID": "1", "sendRegardlessOfConsentState":true},
              "vendorB": {"PAGE_ID": "2"},
              "vendorC": {"SLOT_W": "320", "SLOT_H": "50"}          
              },
            "URLs": [
              {"url": "https://www.AmpPublisher.biz/targetingA", "sendRegardlessOfConsentState": true},
              "https://www.AmpPublisher.biz/targetingB"
            ],
            "timeoutMillis": 750}'`

OR:

rtc-config='{
            "vendors": {
              "vendorA": {"SLOT_ID": "1"},
              "vendorB": {"PAGE_ID": "2"},
              "vendorC": {"SLOT_W": "320", "SLOT_H": "50"}          
              },
            "URLs": [
              "https://www.AmpPublisher.biz/targetingA",
              "https://www.AmpPublisher.biz/targetingB"
            ],
            "timeoutMillis": 750, "sendRegardlessOfConsentState": true}'

**Comment by oliverfernandez** [comment]
Would the consent result sent via query param? Following your example, something like

`https://www.AmpPublisher.biz/targetingB?consent=SUFFICIENT`

**Comment by keithwrightbos** [comment]
Yes we can provide this and make it available to any fast fetch enabled, ad network that may choose to implement RTC in the future (currently Doubleclick is the only one to do so) by making it a part of https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/0.1/real-time-config-manager.js#L148 in the same manner that TIMEOUT is defined as a macro.
