### ISSUE TITLE
Status Update 2018-05-28

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#15600]
If you are contributing to the AMP Project open source community, please use this issue to provide updates regarding the status of the projects you are responsible for and what you will be working on next.

**Comment by aghassemi** [comment]
## UI

### ✨ New Component/Features (available in production releases in 1-2 weeks)
1) `amp-lightbox-gallery:` Displays a lightbox gallery. It is launched and out of experiment. [Documentation](https://www.ampproject.org/docs/reference/components/amp-lightbox-gallery), [Sample](https://ampbyexample.com/components/amp-lightbox-gallery/)<img alt="File upload example" src="https://user-images.githubusercontent.com/2099009/40563200-cc167f86-6018-11e8-8be0-95b6c55fc138.png" width="200">
2) `amp-fx-collection="fade-in"` and `amp-fx="fade-in-scroll":` Allows for easy-to-use fade-in effects on any element. They are fully launched and out of experiment. [Documentation](https://www.ampproject.org/docs/reference/components/amp-fx-collection), [Sample](https://ampbyexample.com/components/amp-fx-collection/)
3) `input type=file` is available for use now. It is restricted to `POST` forms. [Documentation](https://www.ampproject.org/docs/reference/components/amp-form#inputs-and-fields) <img alt="File upload example" src="https://user-images.githubusercontent.com/2363700/39726453-ead6bbde-5203-11e8-8d63-0b9778fdb9a0.gif" width="200">
- `amp-3d-gltf`: Displays 3D models that are in gITF format.  [Documentation](https://github.com/ampproject/amphtml/blob/master/extensions/amp-3d-gltf/amp-3d-gltf.md), [Sample](http://amphtml-nightly.herokuapp.com/examples/amp-3d-gltf.amp.html)
### 🐛 Bug Fixes

### What's next?
- `general maintenance:` is the focus for short term.
- `amp-content-viewer:` #13602: New component to allow zoom/pan for SVGs and potentially other elements.
- `amp-video-iframe:` https://github.com/ampproject/amphtml/issues/8524: New component that allows implementation of `video-interface` by arbitrary iframed players so they can get the benefits such as autoplay, docking, etc...
- `infinite scroll:` for `amp-list` https://github.com/ampproject/amphtml/issues/14060: New feature on `amp-list` that allows for `load-more` and `infinite scroll` use-cases.
- `input-masking`: https://github.com/ampproject/amphtml/issues/14745 Allows for automatically inserting expected characters and spaces in a given form input.

**Comment by jpettitt** [comment]
### `amp-geo`

- Added  support `amp-geo-pending` class to allow CSS control of elements while amp-geo is loading. #15244
- Added `amp-geo-no-group` class when no group is matched. #15554
- Fixed GB/UK country code error #15390 
- Thanks to @gmajoulet who made `amp-geo` robust against uppercase config. #15532 
- Also thanks to @joselanderosmrf who fixed `amp-geo` in shadow amp #15440
- Made `amp-geo` play nice with layers #15226

Next:
- Additional `amp-geo` features

**Comment by aghassemi** [comment]
## UI

### ✨ New Component/Features (available in production releases in 1-2 weeks)
- `amp-lightbox-gallery:` Displays a lightbox gallery. It is launched 🎉 and out of experiment mode. [Documentation](https://www.ampproject.org/docs/reference/components/amp-lightbox-gallery), [Sample](https://ampbyexample.com/components/amp-lightbox-gallery/)<div><img alt="File upload example" src="https://user-images.githubusercontent.com/2099009/40563200-cc167f86-6018-11e8-8be0-95b6c55fc138.png" width="200"></div>
- `amp-3d-gltf`: Displays 3D models that are in gITF format. (Contribution by @mixtur) [Documentation](https://github.com/ampproject/amphtml/blob/master/extensions/amp-3d-gltf/amp-3d-gltf.md), [Sample](http://amphtml-nightly.herokuapp.com/examples/amp-3d-gltf.amp.html) <div><img alt="File upload example" src="https://user-images.githubusercontent.com/2099009/40566626-7999cfde-6026-11e8-8962-1d8d00e7e3c0.gif" width="200"></div>
- `amp-fx-collection="fade-in"` and `amp-fx="fade-in-scroll":` Allows for easy-to-use fade-in effects on any element. They are fully launched and out of experiment. [Documentation](https://www.ampproject.org/docs/reference/components/amp-fx-collection), [Sample](https://ampbyexample.com/components/amp-fx-collection/) <div><img alt="File upload example" src="https://user-images.githubusercontent.com/2099009/40566810-51787298-6027-11e8-9f93-a1aa245a69a7.gif" width="200"></div>
- `amp-bodymoving-animation:` Now supports scrollbound animations (Thanks @jessepinho) [Sample](https://codepen.io/aghassemi/pen/jxvzzq)  <div><img alt="File upload example" src="https://user-images.githubusercontent.com/2099009/40567711-64dcece8-602b-11e8-8a3d-37b5d2b9cb64.gif" width="200"></div>
- `input type=file` is available for use now. It is restricted to `POST` forms. [Documentation](https://www.ampproject.org/docs/reference/components/amp-form#inputs-and-fields)
- `rotate-to-fullscreen:` Allows rotation of the phone to take a video to fullscreen. It is now supported on `amp-ima-video` in addition to `amp-video` [Documentation](https://github.com/ampproject/amphtml/blob/master/spec/amp-video-interface.md#rotate-to-fullscreen), [Sample](https://ampbyexample.com/advanced/video_rotate_to_fullscreen_with_hint/)
- `amp-accordion animate:` The new `animate` attribute on `amp-accordion` allows expand/collapse actions to animate the height of the section.
- `amp-facebook:` Now supports `data-order-by` attribute.

### ✨ New Experimental Features
- `amp-next-page` now available as a [doc-level optin](https://github.com/ampproject/amphtml/blob/3a06c99f259b66998b61935a5ee5f0075481bfd2/tools/experiments/README.md#enable-an-experiment-for-a-particular-document). [Documentation](https://github.com/ampproject/amphtml/blob/106bafa2be210a33b0389e13a7245e6aa2d40351/extensions/amp-next-page/amp-next-page.md)
- `amp-fx-collection="fly-in"` experimentally available under flag `amp-fx-fly-in` [Documentation](https://github.com/ampproject/amphtml/blob/106bafa2be210a33b0389e13a7245e6aa2d40351/extensions/amp-fx-collection/amp-fx-collection.md#fly-in-bottom-fly-in-left-fly-in-right-fly-in-top-experimental)


### 🐛 Bug Fixes
- `amp-lightbox-gallery:` Now does not show nav or gallery controls if there is only one item. #15475
- `amp-twitter`: Now resizes to placeholder/fallback when tweet is deleted/unavailable #15542
- `amp-reddit`:  Now resizes dynamically when needed #15530
- `amp-date-picker:` Dropshadow no longer cut off https://github.com/ampproject/amphtml/pull/15412
- `validator`: `gulp validator --update_tests` now works to update validator test output.

### What's next?
- `general maintenance:` is the focus for short term.
- `amp-video-iframe:` https://github.com/ampproject/amphtml/issues/8524: New component that allows implementation of `video-interface` by arbitrary iframed players so they can get the benefits such as autoplay, docking, etc...
- `infinite scroll:` for `amp-list` https://github.com/ampproject/amphtml/issues/14060: New feature on `amp-list` that allows for `load-more` and `infinite scroll` use-cases.
- `input-masking`: https://github.com/ampproject/amphtml/issues/14745 Allows for automatically inserting expected characters and spaces in a given form input.
- `amp-content-viewer:` #13602: New component to allow zoom/pan for SVGs and potentially other elements. 
<div><img alt="File upload example" src="https://user-images.githubusercontent.com/2099009/40567866-2751e44a-602c-11e8-9bb8-da615e96b47a.gif" width="200"></div>

**Comment by mrjoro** [comment]
## STAMP
contact: @newmuis 

### What was accomplished

- Bookend components completed
- amp-story-consent is launched
- amp-geo works in stories
- Changes to user education triggering
- Set default language when none is specified
- Can now hide audio icon for stories w/o audio (thanks @aghassemi and @alanorozco!)

### What's next

- Ability to pause stories
- Improved testing for amp-story-page
- Optional post-consent UI for amp-story-consent
- Documentation for new bookend
- RTL investigation
- Investigating image blur integration
- Responsive styling eng design
- Configurable desktop eng design
- Change MediaPool to unblock video refactor

**Comment by mrjoro** [comment]
## Runtime
contact: @choumx 

### What was accomplished

- Integrated DOMPurify
- Made amp-list initial render faster
- amp-bind: Rebalanced complexity limits, data-amp-bind-* attributes
- Two-way iframe messaging: launched and unlaunched 
- New onMeasureChanged callback

### What's next

- Binary size: URL parsing service
- New viewer capability: SSR for <amp-mustache> templates
- Web worker security sandbox
- Help out with 1-pass CC

### Lessons learned

- Err on the side of bringing things to design review for sanity checking

**Comment by mrjoro** [comment]
## AMP Script
contact: @kristoferbaxter 

### What was accomplished

- CSSStyleDeclaration
- React Testing

### What's next
- Element Properties

**Comment by mrjoro** [comment]
## UX
contact: @spacedino 

### What was accomplished

- Launched light-box-gallery + ABE’s
- Keep working on infinite scroll / rotating video  / amp-fx all / loading states / date picker

### What's next

- Keep working on infinite scroll / rotating video  / amp-fx all / loading states

### Lessons learned

- Problem framing is soooo useful, and also time consuming.
