### ISSUE TITLE
Validator is broken in canary

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1561]
Seeing some more errors on https://www.ampproject.org/#development=1

**Comment by cramforce** [comment]
Kind of suspecting that this might be related to closure compiler changes.

**Comment by powdercloud** [comment]
Which error specificially doesn't make sense to you?
I think some of the ones I see there will go away once we release the Javascript (@-webkit-keyframes).

**Comment by cramforce** [comment]
@powdercloud You need to go to https://cdn.ampproject.org/experiments.html and opt into "dev-channel" to see the JS errors.

**Comment by powdercloud** [comment]
Ah, I thought this was some problem with the validator. So yes, I see a bunch of Javascript errors now that I've opted in, but I think they come from the runtime, probably (v0.js etc).

**Comment by erwinmombay** [comment]
correct me if i'm wrong but closure compiler has no namespace with top level module and has everything on global correct?  `v0.js` and `validator.js` seem to be colliding in the global namespace now (since we just switched v0.js to use closure compiler too)

**Comment by cramforce** [comment]
Lets add `--output_wrapper="(function() { %output% })()"` the validator build to fix. We can stage that through the canary process.

**Comment by powdercloud** [comment]
Ah - you're saying we (as in, the validator) need to follow the advice here, yes?
https://code.google.com/p/closure-compiler/wiki/FAQ#When_using_Advanced_Optimizations,_Closure_Compiler_adds_new_var

**Comment by erwinmombay** [comment]
@cramforce sgtm. will submit the change to you and @powdercloud after some testing.

**Comment by erwinmombay** [comment]
so for some reason 
`--output_wrapper="(function() { %output% })()"` doesnt work but  `"--output_wrapper='(function (){ %output% }).call(this)'"` does

**Comment by erwinmombay** [comment]
@cramforce @powdercloud https://www.ampproject.org/#development=1 seems to be working now

**Comment by erwinmombay** [comment]
closing, please open if you see anything different.
