### ISSUE TITLE
the content of amp-list can't be shown integrallty when opened in amp-lightbox 

### ISSUE THREAD

**Issue by Jade05** [ampproject/amphtml#15627]
Environment：
Safari (iPhone; CPU iPhone OS 11_2_6 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko)

Description:

the content of amp-list can't be shown integrallty when opened in amp-lightbox.

You can watch the video [here](https://drive.google.com/file/d/1noMrcC7kUELLTrwsSu9JqcuW4DnboLC2/view).  You can test it with this url——https://www.google.com/amp/s/m.trip.com/m/hotels/shanghai-hotels-list-2/.

**Comment by aghassemi** [comment]
@Jade05 , looking at the code, I don't see `amp-lightbox` being used, I see `position:fixed` elements being shows/hidden. Please switch to using `amp-lightbox` for any overlay, it has special logic to handle AMP's lazy-loading, hiding viewer addressbar and accessibility features.

**Comment by aghassemi** [comment]
Closing the issue for now, please reopen if switching to `amp-lightbox` does not resolve your issue.

**Comment by Jade05** [comment]
I am sorry. we changed the implementation while fixing the problem. But  the language selection panel is   still implemented with amp-lightbox.

![test22](https://user-images.githubusercontent.com/5029635/40719256-98242a08-6445-11e8-86d3-52e82a3a3fc8.png)

![test11](https://user-images.githubusercontent.com/5029635/40719260-9a258a4a-6445-11e8-87c4-89d273f32581.png)
