### ISSUE TITLE
Add support to SMART Ad server

### ISSUE THREAD

**Issue by lec-sdiallo** [ampproject/amphtml#1562]
Is that support in your plans ?

**Comment by cramforce** [comment]
@kashyapnitin Do you know?

@lec-sdiallo If you have a contact with them, probably best to invite them to this thread!

**Comment by lec-sdiallo** [comment]
Asked to SMART what's going on, they replied that they're working on it (see https://github.com/ampproject/amphtml/pull/1704) and they'll communicate to their customer estimated time of delivery

**Comment by kashyapnitin** [comment]
SMART is supported now - https://github.com/ampproject/amphtml/blob/master/ads/smartadserver.md

so i think this should be closed.

**Comment by kashyapnitin** [comment]
Closing the issue. Please reopen if you think it needs any further work.
