### ISSUE TITLE
Amp-consent not working as expected in Safari iOS 10 

### ISSUE THREAD

**Issue by amnaaskari** [ampproject/amphtml#15636]
## What's the issue?
For Safari in iOS 10 - the 'tap' event/action is not working nor is the standard consent workflow. Therefore, the user is stuck with a pop up which they can't close which isn't ideal. 

## How do we reproduce the issue?

If you load up any URL that uses amp consent e.g. https://ampbyexample.com/user_consent/advanced_user_consent_flow/, on a simulator or actual iOS mobile device with iOS 10 - you should be able to reproduce the issue. 

## What browsers are affected?

iOS 10 Safari

## Which AMP version is affected?

All

**Comment by zhouyx** [comment]
Thanks for filing the issue. I'll investigate. @choumx Any ideas?

**Comment by choumx** [comment]
Can't repro on iOS Simulator 10.3.1. @amnaaskari Which iOS 10 version are you running?

**Comment by lannka** [comment]
I repro'd the issue on iOS Simulator 10.0 via SauceLabs

**Comment by choumx** [comment]
Looks like #15548 might fix it. Currently in canary.

**Comment by lannka** [comment]
#15548 is not handling it correctly. Will need a fix.

**Comment by lannka** [comment]
<img width="640" alt="screen shot 2018-05-30 at 9 48 43 am" src="https://user-images.githubusercontent.com/8496897/40735293-a4c97dc2-63ef-11e8-96c6-bb40d84c337b.png">

This is the console error after #15548

**Comment by amnaaskari** [comment]
@choumx was experiencing it on 10.1 and all versions of iOS 9. I think its affecting a lot of versions below iOS 11. Have a feeling it has to do with how the accept/reject events are transmitted in controlling the css of the pop up - because when you click accept or reject, the post consent UI shows up, and on refreshing the page nothing shows up which means consent has been recorded. Thanks all for working on this, much appreciated!

**Comment by zhouyx** [comment]
This is an issue for safari with version older than 10.3 It's affecting 15% of safari user, I suggest we label this p0 and patch the fix #15671 
@jridgewell

**Comment by nygellyndley** [comment]
Can I ask, will this be going out under the normal release schedule, or is there any intention to push this out a bit sooner?

**Comment by zhouyx** [comment]
The fixed was patched to prod. Confirmed fix in prod.
