### ISSUE TITLE
Mocha silently skips tests when an async error is thrown

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#15658]
@jpettitt reported this while running the following test:

https://github.com/ampproject/amphtml/blob/97847f23b36b5004a63bdc94f35700bfb48c5ac4/extensions/amp-user-notification/0.1/test/test-amp-user-notification.js#L80-L88

The error at the end of the test gets thrown asynchronously, by which time the test has completed. So Mocha makes it look like the test has passed, but the thrown error prevents it from running subsequent tests.

See https://github.com/mochajs/mocha/issues/3223 and https://github.com/mochajs/mocha/pull/3257 for more info on why this is a mocha problem.

**Comment by rsimha** [comment]
From looking at the mocha documentation at https://mochajs.org/#asynchronous-code, I wonder if these tests should be calling `done()` in order to get mocha to wait until the error is thrown.

**Comment by rsimha** [comment]
Another theory: Here are the last few lines of `buildCallback()`. Notice that `userNotificationManagerPromise` is being created, but not returned. I wonder if this explains the async behavior that's tripping up mocha.

https://github.com/ampproject/amphtml/blob/acc1927661eec3e7bea03456971c2cb7f83ffe4d/extensions/amp-user-notification/0.1/amp-user-notification.js#L165-L172

**Comment by zhouyx** [comment]
Found the same issue with amp-iframe test as well.

**Comment by zhouyx** [comment]
For `test-amp-iframe`
https://github.com/ampproject/amphtml/blob/1c555f2bb22382fc383d3710c722a26967e29d17/extensions/amp-iframe/0.1/amp-iframe.js#L165-L177

Looks like user().assert calls `reportError` which will rethrow an async error. I am stubbing the `#reportError` function to fix this.

**Comment by rsimha** [comment]
Seems like several AMP tests do asynchronous stuff (like throwing errors), but don't correctly use the done() callback to indicate that the asynchronous tasks have completed. I'm looking for a centralized way to detect such anti-patterns, and isolate / fail tests that contain them.

**Comment by rsimha** [comment]
After some investigation, it turns out that functions like `user().error` and `user().assert` call `reportError`, which asynchronously throws the same error that we're throwing during tests when `console.error` is called.

One potential fix for this issue is to stub out `reportError` during tests at times when `console.error` will throw an error. This means the normal `reportError` behavior is restored inside `allowConsoleError` blocks, where `console.error` will not throw an error.

**Comment by choumx** [comment]
I can probably help here since I'm familiar with describes. What's the question?

**Comment by rsimha** [comment]
@zhouyx brought up the possibility of describes using an inner context, with separate console and error instances.

**Comment by choumx** [comment]
IIUC, I don't think shadowing globals is generally a good idea. We should just use standard testing mechanisms e.g. stubbing.

**Comment by zhouyx** [comment]
@choumx Here's what I found yesterday. 

We stub `window.console` before every test. However every test is using the same global window. Even we call sandbox.restore after a test, an async error from it can still results in the failure of its following test. This is flaky and hard to debug I think. Given some of the unit tests are designed to test error cases. We need to make sure that async errors from those tests are well scoped within their context. 

Using `done()` callback would be able to solve that problem. But the issue here is that we won't be able to know when to call that in the async test environment.

**Comment by rsimha** [comment]
This is still happening.

**Comment by rsimha** [comment]
This is still an issue. See https://github.com/mochajs/mocha/issues/94 for reference.

**Comment by dvoytenko** [comment]
I think our best bet to resolve this issue in the intermediate-term is by setting up our test runner to intercept the `error` and `unhandledrejection` window event handlers. We can record them and clearly log when they happen. We can add `expectUnhandledError(matcher)` to skip the known errors that we expect. At the very least this should prevent us from being completely in the blind why something has got stuck. At a maximum this could give us a path to prevent "stuck" states for tests.
