### ISSUE TITLE
Getting different behavior between local gulp lint and travis. 

### ISSUE THREAD

**Issue by bradfrizzell** [ampproject/amphtml#15664]
Just rebased my feature branch against current master head, and I am still seeing this.

Here's the[ travis failures](https://travis-ci.org/ampproject/amphtml/jobs/385386318)

This is the [pull request](https://github.com/ampproject/amphtml/pull/15595)

Locally, I see no lint issues, but travis shows multiple lint errors.

**Comment by rsimha** [comment]
Those are all legitimate errors. Are you running `gulp lint --local-changes`? You should see the same errors. Note that when you run `gulp lint` (as is done for Travis `master` builds), we only show warnings, because there are numerous existing errors in the code base.

**Comment by bradfrizzell** [comment]
Right, I realize those were legit errors, I was more concerned as to why they were not showing up locally. I tried both running `gulp lint` and `gulp lint --local-changes` and didn't see them either time. I'll try that script and see if it helps

**Comment by bradfrizzell** [comment]
Reopening for now. I tried the following and still getting 0 lint errors locally: 

- `gulp lint`
- `gulp lint --fix`
- `gulp lint --local-changes`
- `gulp lint --local-changes --fix`
- Ran ./build-system/enable-git-pre-push.sh then added a blank line change, then tried pushing

In all cases, I got 0 local lint errors

**Comment by rsimha** [comment]
I see that the branch from which your PR is originating is `https://github.com/ampproject/amphtml/tree/frizz-rtc-refactor`. That feels wrong, because IIRC, PRs must originate from a branch on a fork of `ampproject/amphtml`. So in your case, I'd have expected the PR to come from a branch with a URL like `https://github.com/bradfrizzell/amphtml/tree/rtc-refactor`

**Comment by bradfrizzell** [comment]
PRs don't have to originate from a fork, or at least there's nothing stopping them from originating from branches directly on this fork. That's what I (and I think others on my team) do

**Comment by rsimha** [comment]
Unable to repro this. Please reopen with logs and repro steps if you're still seeing this.

**Comment by rsimha** [comment]
@bradfrizzell @keithwrightbos @taymonbeal This issue stems from the fact that your local `master` branch isn't being kept up to date, which breaks the logic here:

https://github.com/ampproject/amphtml/blob/601b7d760eabf854dea447fc3958e74a5ea5afd6/build-system/git.js#L24-L30

To solve this, you can have your local `master` branch track `upstream/master`, as described in our dev docs, and thereby keep it up to date. Then, whenever you create a branch, you can branch it off of `master` and not `upstream/master`. Instructions [here](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#pull-the-latest-changes-from-the-amphtml-repository). Let us know if this solves your problem.

**Comment by rsimha** [comment]
Closing since there's nothing left to do here.
