### ISSUE TITLE
embed-ready and embed-size messages sent from amp-iframe not working

### ISSUE THREAD

**Issue by pvdspek** [ampproject/amphtml#15665]
## What's the issue?

The `amp-iframe` component can no longer send `embed-ready` and `embed-size` messages when the iframe content has been loaded and rendered. 

This issue was introduced with #9074 which requires every message sent from an iframe to origin from a user-gesture. However, this behaviour doesn't match with previous behaviour. Existing code now fails with a `"message" event may only be triggered from a user gesture.` error.

Also it's not in line with the documentation, which states the `embed-ready` message may be sent to signal the iframe content has loaded,  and the `embed-size` message may be sent to request an iframe resize (typically when the iframe content has rendered). 

There is a clear use-case to be able to send `embed-ready` and `embed-size` messages after the iframe content has loaded, instead of depending on a user-gesture. 

The `embed-ready` and `embed-size` messages should be excepted from the user-gesture origin requirement for messages sent from an amp-iframe.

## How do we reproduce the issue?

This sample example defines an `amp-iframe` with initial height 400. The iframe content is eventually 200px high and requests an iframe resize using the `embed-size` message. The message fails with a `"message" event may only be triggered from a user gesture.` error.

main.html:
```
<amp-iframe width="600" height="400" layout="responsive" sandbox="allow-scripts" src="iframe-content.html" resizable>
  <div overflow tabindex=0 role=button aria-label="Read more">Read more</div>
</amp-iframe>
```

iframe-content.html:
```
<html>
<head>
  <title>Sample AMP code embed</title>
  <meta name="robots" content="noindex">
  <style>
    body { margin: 0; padding: 0; }
    body > .content { position: absolute; top: 0; left: 0; right: 0; bottom: 0; margin: 0; padding: 0; }
  </style>
</head>
<body>
  <div class="content">
    <div style="background-color: red; width: 200px; height: 200px;"></div>
  </div>
  <script type="text/javascript">
    window.addEventListener('load', function() {
      window.parent.postMessage({
        sentinel: 'amp',
        type: 'embed-size',
        height: document.body.scrollHeight
      }, '*');
    });
  </script>
</body>
</html>
```

## What browsers are affected?

All browsers.

## Which AMP version is affected?

Broken in version 1527021682973. This issue was introduced with PR #11395.

**Comment by aghassemi** [comment]
/to @choumx Issue is likely from #11395 but the flag is off, so not sure what's happening.

**Comment by choumx** [comment]
Looks like the error is a red herring. There are two message listeners and the two-way messaging listener is also picking up the `embed-size` message and displaying that error message, but the original listener will handle the request correctly. In either case, `iframe-messaging` is now disabled so you shouldn't get that error message anymore anyways.

I also actually can't repro the bug with the provided example (with or without `iframe-messaging` enabled). What might be the problem is silent failure if the parent and iframe have the same origin. This would cause messages from the iframe to be treated as `origin == "null"`, which will be ignored by the main page.

**Comment by pvdspek** [comment]
@choumx Thanks for you clarification. I can confirm it's a red herring. 

Although I was using `allow-same-origin` and getting the iframe content from a different domain, the resize was not working because of the rules around the iframe being inside the viewport. The documentation does not clearly specify what those rules are, and I was misled by the error messages appearing on the console.

**Comment by choumx** [comment]
Yea, adding `allow-same-origin` causes AMP to impose different constraints. More details here: https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md

We could probably spell this out more clearly and/or display helpful runtime warnings, sorry about the confusion. Documentation pull requests are very welcome! 😄
