### ISSUE TITLE
amp-youtube generating CORS errors 

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#1566]
Opening issue per @cramforce 

We're seeing cors errors using the amp-youtube extension - this on both prod and experimental channels.  

![image](https://cloud.githubusercontent.com/assets/524856/12562177/a24f7d38-c358-11e5-9c1c-f565996ff28a.png)

**Comment by cramforce** [comment]
So, this is somewhat working as intended, but obviously very confusing. We make these requests to force Safari to open a connection (because it does not natively support `<link rel=preconnect>`. This works perfectly fine if you get a CORS error :)

My question: Is this too confusing? I don't really know how to fix it without making Safari slower again.

**Comment by jpettitt** [comment]
So you're loading a 404 page to force a server tcp/ssl connection? Neat trick.  If it's a Safari thing why are you doing it in Chrome?  

Perhaps if you loaded https://www.youtube.com/amp_preconnect_polyfill_safe_to_ignore_cors_error  :-) and didn't do it on chrome.  Still a kludge but at least when people look at the console log they won't waste time chasing an error that isn't there.

**Comment by cramforce** [comment]
@jpettitt It is not specific to youtube, but the other URL is probably good :)

Oh, you saw this in Chrome? That is a bug!

**Comment by jpettitt** [comment]
Yes Safari generates a slightly different error, the cors stuff plus some invalid css

![image](https://cloud.githubusercontent.com/assets/524856/12591207/86a74142-c41b-11e5-8752-eaa33e71bd4e.png)

**Comment by cramforce** [comment]
@jpettitt Could it be that you had Safari UA emulation on when you were testing in Chrome?

We need to do UA detection to figure out whether we need the Safari polyfill because there is no way to feature test this.

**Comment by jpettitt** [comment]
Doh!  I tried it in Samsung emulation too (SIII) but on further exploration it seems to be emulation specific,  but not unique to Apple emulations.  Pure chrome doesn't do it right now but I'm getting other errors that may be masking things.

**Comment by cramforce** [comment]
It would be expected in all browsers with Safari in their user agent. I'll close for now. Maybe we can remove this when iOS 10 comes out :)
