### ISSUE TITLE
Not all fixed DOM will be calculated 

### ISSUE THREAD

**Issue by Jade05** [ampproject/amphtml#15661]
I find a very strange phenomenon. Not all fixed DOM will be calculated. 

the below is calculated successfully:

![1](https://user-images.githubusercontent.com/5029635/40713063-c445a198-6431-11e8-9114-4e100c73da3a.png)

this one is not calculated unsuccessfully:

![2](https://user-images.githubusercontent.com/5029635/40713125-e8040f7a-6431-11e8-96e9-b4bbd35f9f6c.png)

this will cause problems when the page is opened with amp cache. How can i make every fixed DOM calculated successfully? Thank you.

**Comment by jridgewell** [comment]
@Jade05: I need a demo page to debug this.

**Comment by aghassemi** [comment]
Thanks @Jade05
