### ISSUE TITLE
amp-story auto-advance continues advancement while in background tabs

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#15675]
Repro steps:
1. Open a story with auto-advance and outlinks (e.g. https://posts.google.com/share/1he6RhZ-/3ickR4)
2. Click on an outlink
3. Wait a while..... 
4. Go back to the other tab

Actual result:
5. The story was advancing all along!  This causes the user to miss pages.

Expected result:
5. The story should be paused while it is in the background.

**Comment by newmuis** [comment]
We should now just be able to enable the `PAUSED_STATE` in the `pauseCallback` of `amp-story`, and disable it in the `resumeCallback`.

**Comment by gmajoulet** [comment]
Closed by #16811
