### ISSUE TITLE
AMP.navigateTo() has stopped working

### ISSUE THREAD

**Issue by DannySaltire** [ampproject/amphtml#15684]
## What's the issue?

`AMP.navigateTo()` has stopped working.

Console logs `Uncaught TypeError: Cannot read property 'length' of undefined` , originating from a Polyfill for `String.prototype.startsWith`.

## How do we reproduce the issue?

Here's [a jsfiddle](https://jsfiddle.net/k0f58c06/), copied out of the [standard actions example](https://github.com/ampproject/amphtml/blob/master/examples/standard-actions.amp.html).

Steps to reproduce
1. Click on the "google.com" button, or change the select box

## What browsers are affected?

Every browser I've tested: Chrome, Firefox, Mobile Chrome, Mobile Safari

## Which AMP version is affected?

I'm seeing it in AMP Version 1527203409437. Last time I can be certain I saw this action work was on 16 May 2018.

**Comment by aghassemi** [comment]
(rolling back 1527203409437 until this is patched)
