### ISSUE TITLE
bad message in pre-push hooks git push -n still runs verification

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#15709]
**"You keep using that flag, it does not mean what you think it means"**

pre-push hooks show this misleading message

`Running pre-push hooks. (Run git push --no-verify or git push -n to skip them.)`

However `-n` is already reserved for dry run in git.  `git push -n` run the pre-push hooks but does not actually push.

**Comment by rsimha** [comment]
Good catch, not sure what I saw that made me think `-n` would work.

**Comment by rsimha** [comment]
Hmm... I wasn't dreaming. See https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-commit.html

<img width="597" alt="" src="https://user-images.githubusercontent.com/26553114/40802408-ce512678-6515-11e8-8ccb-7f00f98f5816.png">

**Comment by jpettitt** [comment]
Weird `git push --help` says

```
       -n, --dry-run
           Do everything except actually send the updates.
```

**Comment by rsimha** [comment]
Yeah, weird. In any case, since `-n` doesn't work like `--no-verify`, so we shouldn't be suggesting that it does.

**Comment by rsimha** [comment]
After re-reading it two times, I realised that `-n` is `--no-verify` for `git commit` hooks, not `git push` hooks >_<
