### ISSUE TITLE
The amp-list example is not working on local builds

### ISSUE THREAD

**Issue by chenting0615** [ampproject/amphtml#15716]
## What's the issue?

The amp-list example does not render correctly in localhost

## How do we reproduce the issue?

=> Load the amp-list page : http://localhost:8000/examples/amp-list.amp.html
=> You will see this:
<img width="590" alt="screen shot 2018-05-31 at 1 01 07 pm" src="https://user-images.githubusercontent.com/3374595/40805991-eca115c0-64d4-11e8-91df-1e48b38785b2.png">

with this console:
<img width="804" alt="screen shot 2018-05-31 at 1 01 14 pm" src="https://user-images.githubusercontent.com/3374595/40806028-0dfbfbd6-64d5-11e8-8371-1ca1a1b3af50.png">
 

If this is a feature request you can use this section to point to a prototype/mockup that will help us understand the request.

## What browsers are affected?
Chrome, Version 66.0.3359.181

**Comment by aghassemi** [comment]
(This only impacts local development, not a  production issue).

I can see why this is happening (https://github.com/ampproject/amphtml/blame/master/src/runtime.js#L871 checks for `custom-element` but mustache uses `custom-template`) I am not sure why this regressed however, it definitely used to work few weeks ago.

@erwinmombay @rsimha Anything changed with regards to internal versioning recently?

**Comment by aghassemi** [comment]
I am seeing different internal version between runtime and the extension ( and I am just running `gulp` not `gulp build --extension..`)

**Comment by aghassemi** [comment]
(actually with the same version it still fails. I will investigate that part)
