### ISSUE TITLE
Attributes are being removed when rendering amp-mustache template

### ISSUE THREAD

**Issue by bmadzar** [ampproject/amphtml#15721]
## What's the issue?

**On the dev-channel build**
`amp-list` is stripping out certain attributes when rendering an `amp-mustache` template that are not stripped out on the production build. (Not sure if the problem is related to `amp-list` or `amp-mustache`)

## How do we reproduce the issue?

1. Have an `amp-list` referencing an `amp-mustache` template.
2. The `amp-list` loads correctly, however some of the attributes are getting stripped off of tags in the template, including `input[name]`, `li[on]`, `p[on]`. We use these to allow the user to interact with the list, e.g. delete items.

The document passes AMP validation. The only change between the working and non-working setups is toggling the `dev-channel` flag.

## What browsers are affected?

Tested in Chrome 67 and Firefox 52.

## Which AMP version is affected?

Works in (prod) 1527203409437, broken in (dev) 1527787993802.

**Comment by choumx** [comment]
Thanks for the report @bmadzar. Probably related to `svg-in-mustache` experiment. Investigating.

**Comment by choumx** [comment]
Looks like `on` attributes are being sanitized by DOMPurify since it thinks `"tap:foo.bar"` is a URL due to the colon character. Our unit tests didn't catch this because we only test that `<a on="tap">` is output (without colon). 😢 

@bmadzar `input[name]` appears to work for me, can you double-check this? Also please let me know what other attributes are problematic. Thank you!

**Comment by choumx** [comment]
Sanitizing `input[name="id"]` is a DOM clobbering security feature in our sanitizer library. Is it possible for you to workaround this?

**Comment by bmadzar** [comment]
I can work around it; the application is still in development so nothing depends on the API yet.

Is this a new change? The DOM clobbering behavior does not seem to be present on prod and I can't find mention of it in the docs. I am now concerned that breaking changes like this will get rolled out in the future without us knowing. Is there documentation around planned, breaking changes?

**Comment by choumx** [comment]
Good question. It's a new sanitizer that's wrapped under a dev-channel-only experiment. Depending on measured impact, we'll either release this feature under a version bump or broadcast the breaking change widely. Thanks for reporting this again!
