### ISSUE TITLE
Does amp-access have dependency on amp-analytics?

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#15723]
According to the [documentation of amp-access](https://github.com/ampproject/amphtml/blob/master/extensions/amp-access/amp-access.md), it requires amp-analytics extension to be loaded.

Many extensions required amp-analytics for CID functionality, but not anymore after migrating CID to core. 

@dvoytenko is the dependency still needed?

/cc @sebastianbenz @calebcordry

**Comment by dvoytenko** [comment]
I don't believe it's needed anymore
