### ISSUE TITLE
Incorrect description of amp-install-serviceworker on docs?

### ISSUE THREAD

**Issue by AndrewKGuan** [ampproject/amphtml#15735]
On this doc [https://www.ampproject.org/docs/reference/components/amp-install-serviceworker](https://www.ampproject.org/docs/reference/components/amp-install-serviceworker) it says:

> This ServiceWorker runs whenever the AMP file is served from the origin where you publish the AMP file. The ServiceWorker will not be loaded when the document is loaded from an AMP cache.

Is that statement correct?

**Comment by choumx** [comment]
Technically yes, though "will not be loaded" is a bit confusing since "loaded" may be conflated with installation. We should say:

> The ServiceWorker will not run on documents served from an AMP cache.

/cc @danielrozenberg @bpaduch

**Comment by danielrozenberg** [comment]
Maybe something a bit more explicit:
> On documents served from an AMP cache, the ServiceWorker will be installed in the background but will not execute or affect the page's behavior until the user navigates to the origin domain where you publish the AMP file.

**Comment by shishirm** [comment]
Would it be helpful to clarify that the install phase will be executed which means if any assets are setup to be pre-cached, they will indeed be downloaded and then the service worker will wait to run until the navigation to the origin domain?
