### ISSUE TITLE
FR: AMP-LIST timed refresh

### ISSUE THREAD

**Issue by QES** [ampproject/amphtml#15780]
AMP-LIST is a great way to get data into a page, and there is now a way to manually refresh the data but I think it would be useful to have a way to refresh it automatically.

We have ended up with amp-live-list (which refreshes the page automatically) and amp-list which gets a specified data source but can't refresh it.

An example would be the ability to update a section of page with data that changes regularly - but unlike amp-list list which reloads the whole page (or server side filtered) this can get a JSON file and use amp-mustache to refresh small amounts of data on an otherwise constant page.

consistent with amp-live-list adding 

data-poll-interval="15000" 

would be the best way to do this.

**Comment by aghassemi** [comment]
related https://github.com/ampproject/amphtml/issues/11686
/cc @ericlindley-g

**Comment by aghassemi** [comment]
We are thinking about allowing `push` (#11686) for `amp-list` as polling has performance issues.

**Comment by ericlindley-g** [comment]
This sounds promising—could there be an easy way to re-use some of the experience of amp-live-list (complete with user-initiated updates, so we don't need to worry about resizing issues)?

**Comment by QES** [comment]
I think using some of the ideas in amp-live-list in amp-list to allow for the best of both with using amp-list to collect data and setting it to refresh or allow some kind of push notification or other polling initiatives would be very useful.

One of the uses I have for amp-list is to load a widget with a bunch of latest updates at the moment the user has to request a refresh but having a way to poll for changes or reload /  refresh automatically would make the functionality and usability better.

You can see an example here https://amp.sportsmole.co.uk/live-scores/ the live videprinter element with the refresh button is a live list data feed.
