### ISSUE TITLE
AMP-AD as a fallback doesn't work as expected

### ISSUE THREAD

**Issue by LucasRosaWP** [ampproject/amphtml#15789]
## What's the issue?

AMD-AD used as a fallback doesn't work as described here: https://www.ampproject.org/docs/reference/components/amp-ad#no-ad-available.

WPMedia AMP-AD tags, used as a flllback, do not render ads when DoubleClick fails out of viewport.
AMP-AD tag is collapsed and the fallback is not used.
What's important, DoubleClick's fallback works when the tag fails in a viewport.

The docs say: _**If there is no fallback element available**, the amp-ad element is collapsed_ 

Example tags usage:
`<amp-ad width="300" 
        height="250" 
        type="doubleclick"
        data-slot="/89844762/Mobile_Sportowefakty.wp.pl_x03_art_amp"
        data-loading-strategy="0">  
  <amp-ad fallback="" 
          width="300" 
          height="250" 
          type="wpmedia" 
          data-slot="3" 
          data-bunch="235726" 
          data-sn="sportowefakty_mobile" data-slots="1,3,5,6,11,12,15">
  </amp-ad>
</amp-ad>`

## How do we reproduce the issue?

Issue can be found here: https://m.sportowefakty.wp.pl/amp/pilka-nozna/755828/michal-kolodziejczyk-a-teraz-powinny-wjechac-traktory-komentarz

1. Watch for DC ads
2. Scroll up and down for a few times
3. Refresh page view and watch for missing BTF ads (no fallbacks)

The display of DC ads depends on many factors (capping, retargeting), so a multiple refresh may be required.

## What browsers are affected?

All browsers.

## Which AMP version is affected?

Current.

**Comment by keithwrightbos** [comment]
This is working as intended as fallback was not meant to mediate to other ad networks.  Instead, I recommend you configure Doubleclick to return wpmedia's standard ad tag as the creative when other demand does not fill (via new line item and/or creative).  Please contact Doubleclick support for assistance with such a configuration.
