### ISSUE TITLE
update-cache API: Invalid PEM key on one subdomain, success on another using same key

### ISSUE THREAD

**Issue by retty-brenton** [ampproject/amphtml#15786]
## What's the issue?
I am running into an issue when trying to use the `update-cache` API. Originally I ran my script calling `update-cache` when the apikey.pub was invalid (Content-Type was not correct). I fixed everything I could on my side and waited a week for it to update while testing every few days, but it still returns 403 Invalid PEM key.

Since I was out of ideas about what could be wrong with the apikey.pub, I decided to try another subdomain I hadn't used at all for testing to see if it reacted any differently. The unused subdomain returned 200 OK without any issues on the first try, which leads me to believe it's probably caching a bad key (or not updating the key) and not an error with the generated URLs (see below for URLs and code used to generate URLs).

I've confirmed that the headers, contents of the key, etc are the same using curl on all of the corresponding key URLs for each request, so there shouldn't be anything different on our end when requesting the apikey.pub for amp.retty.me vs user.retty.me.

## How do we reproduce the issue?

Key URL: http://amp.retty.me/.well-known/amphtml/apikey.pub
Bad URL 1 (Update https://amp.retty.me/r/100000451100/): https://amp-retty-me.cdn.ampproject.org/update-cache/c/s/amp.retty.me/r/100000451100/?amp_action=flush&amp_ts=1528078792&amp_url_signature=brCFTYvvP_bYpqpUxOGI7D12PCT54L65tHP45NtCNA6PckljLzZUU1uAna23mTyk5JlxQE56cxqQBhskg6bAgm3L4dGYEGB3RXSFyBX1hkmvfvUdVb1N2dVxOR5DzuQdKp4FjidJ1Ae5RTb2okzBqxOSP6XJDLnMXmgIon2w-xN1Mh4fC0qQpvLzZX9bugktL48CNLrjbRE8dB275ZQIjT98Tx8sy11GVwbCE0mgjNtbrIkz4rU-dhC3XkPtthWTgICkur7Ner5s3R6KXUIf5Xe_NMk6zE-7ScAOg388oo3ykC51MjGu5Vv1Bpm3xRwAXqmY__PRsLulyVZN0BI4nA==
Returns `403 Invalid PEM key. That’s all we know.`

Key URL: http://retty.me/.well-known/amphtml/apikey.pub
Bad URL 2 (Update https://retty.me/restaurant/100000451100/amp): https://retty-me.cdn.ampproject.org/update-cache/c/s/retty.me/restaurant/100000451100/amp?amp_action=flush&amp_ts=1528081509&amp_url_signature=LDH1-nCyimTUcCQoMJJnpl8lRkY--fpug7xx1s9tlPdYnj_baNTB_GUB1sMxRTva7a8O7SXLKCJq_DCQb860BtaAHqfGL_GVBxh2hPMHIzSdpBetmfxKuWBrvj3yZZctnlu7FKMVa-5tPIoyE6F0brkG9rajZk4X2e9KiN9fZ1MymCXqfOB-Y5OP22_U7IMldayX8Yl_YCNSrpXRp0cE5PZdzeLYVHFYvTngSRZ2d6jb11-hIqtTM8EQJJKghmuNTZu5WM6okAjAjZjPtKwf6i97YJQDQPme90S4Oi23336t8rMFIOxWdgZuZ2Z4s1-TUY8OXxnByBzI2cbQ4KAU8Q==
Returns `403 Invalid PEM key. That’s all we know.`
 
Key URL: http://user.retty.me/.well-known/amphtml/apikey.pub
Good URL (Update https://user.retty.me/restaurant/100000451100/amp): https://user-retty-me.cdn.ampproject.org/update-cache/c/s/user.retty.me/restaurant/100000451100/amp?amp_action=flush&amp_ts=1528081423&amp_url_signature=bSbMn0oQAZ0zOBBQ1fGaSapn0NhlUkQslau3ac98yav3cMB9sljSUmcunwwCPLWBYfLfyIwnhrGZ4BY-4b7RzlavmFOi-izNcntW2143ItRVp_9nPn5XKTdnXFSTEIu9aU7RLaCdgSLiDkFupT7sHdcFBuenoMrDghFQrbPcrFp3qBfEpMmHoYxhhMFFOidkAfQgPDg-_sSNuJFCdJdZToKooGLAPjaWKtwbflebCIG1smuuTXTAG1uETZfFFrjNEYLi9GyGgG64tfFvqcqbGYFsE9Y8gWOYMZ0uAvYcFqFezoFskqMSyDSJ8U2a8CNIFI0tmblRFPZ55mno19v3Bw==
Returns `200 OK` when run soon after creating, otherwise it returns `URL signature timestamp expired: amp_ts=2018-06-03T20:03:43-07:00 now=2018-06-03T20:09:34.388531095-07:00` once it expires.

Code:
```
import base64
import requests
import subprocess
import time

CACHES_URL = "https://cdn.ampproject.org/caches.json"

amp_page_url = "https://user.retty.me/restaurant/100000451100/amp"

r = requests.get(CACHES_URL)
caches = r.json().get('caches', [])

for cache in caches:
    update_domain = cache.get('updateCacheApiDomainSuffix', None)

    if not update_domain:
        continue

    amp_domain = requests.utils.urlparse(amp_page_url).netloc
    amp_path = requests.utils.urlparse(amp_page_url).path

    update_url_base = "/update-cache/c/s/%s%s?amp_action=flush&amp_ts=%d" % (amp_domain, requests.utils.quote(amp_path), int(time.time()))
    print(update_url_base)

    with open("url.txt","wb") as urltxt:
        urltxt.write(update_url_base.encode('ascii'))

    signed_digest_proc = subprocess.Popen(
        ['openssl', 'dgst', '-sha256', '-sign', 'apikey.priv', '-out', 'signature.bin', 'url.txt'],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE
    )
    signed_digest_proc.communicate()

    verify_signed_digest_proc = subprocess.Popen(
        ['openssl', 'dgst', '-sha256', '-verify', 'apikey.pub', '-signature', 'signature.bin', 'url.txt'],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE
    )
    verify_result, _ = verify_signed_digest_proc.communicate()
    verify_result = verify_result.decode('ascii').strip()

    if verify_result != "Verified OK":
        print("Couldn't verify generated signature:", verify_result)
        exit(1)

    update_signature = open("signature.bin","rb").read()
    update_signature_base64 = base64.urlsafe_b64encode(update_signature).decode('ascii')

    final_update_url = "https://%s.%s%s&amp_url_signature=%s" % (amp_domain.replace(".", "-"), update_domain, update_url_base, update_signature_base64)
    print(final_update_url)

    r2 = requests.get(final_update_url)
    print(r2)
```

## What browsers are affected?

All browsers.

## Which AMP version is affected?

AMP Project server side API.

**Comment by polaris-** [comment]
Just an update: I've been testing every few days still, and nothing has changed in the 3-ish weeks since first encountering this issue. The API key being cached by the server just isn't updating it seems. In that case, if you mess up once it becomes impossible to use the update-cache API unless you change subdomains which isn't a feasible option for everyone.

**Comment by retty-brenton** [comment]
Just an update: I've been testing every few days still, and nothing has changed in the 3-ish weeks since first encountering this issue. The API key being cached by the server just isn't updating it seems. In that case, if you mess up once it becomes impossible to use the update-cache API unless you change subdomains which isn't a feasible option for everyone.

**Comment by Gregable** [comment]
Closing bug as this is an AMP Cache specific. That project is tracking at `b/113542335`
