### ISSUE TITLE
Race condition causes amp-consent to fail to find amp-geo

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#15782]
A very specific race condition can cause `amp-consent` to fail with the error `requires <amp-geo> to use promptIfUnknownForGeoGroup`.

This only happens if the js loads in a specific order : `amp-consent` then `v0` then `amp-geo`.  

Typically this happens if `amp-consent` is in cache and `v0` and `amp-geo` are not in cache.  What looks to be happening is:

1. `amp-consent` runs first, pushes itself onto the AMP object.
1. `v0.js` loads and calls the `buildCallback()` of `amp-consent`
1. `amp-consent` calls `Services.geoForDocOrNull()` which finds it way to `getElementServicePromiseOrNull()` .
1. `getElementServicePromiseOrNull()` calls `dom.waitForBodyPromise()` and waits.
1. `v0.js` stubs out the as yet unloaded `amp-geo` also calling  `dom.waitForBodyPromise()` but critically this happens after `amp-consent` has called it.
1. The body Promise resolves and `amp-consent` fails to `waitForExtensionIfStubbed()` becasue it's run before `v0.js` got a chance to stub the `amp-geo`

Repro:  

1. Find a page that uses `amp-geo` and `amp-consent` 
1. Clear browser cache
1. Prime `amp-consent.js` into browser cache by loading it in another tab.
1. Load the target page.
1. If v0.js loads before amp-geo,js it will fail.

This is highly dependent on the order of scripts in `<head>` and the the timing of the stubbing elements which happens multiple times during startup.

For this to happen `amp-consent` needs to load and register itself before `v0` runs, and `v0` needs to execute before the `body` tag  has been parsed and before the script line containing `amp-geo` has been read.

When this happens `v0` doesn't stub `amp-geo` on it's first pass because it hasn't seen it yet, it does catch it after body is loaded but the order of waiting for the body is such that `amp-consent` runs before `v0` stubs `amp-geo`.

Speculation: this happens more than I would expect because of browser cacheing strategy.  `v0` is large and ends up in disk cache, `amp-consent` is small and in memory cache, `amp-geo` has a short cache lifetime and so it more likely to be a miss.

**Comment by jpettitt** [comment]
cc @jridgewell @dvoytenko

**Comment by jpettitt** [comment]
The underlying issue is that `stubElementsForDoc()` is called by the runtime in the callback for `adoptShared()` by which time `adoptShared()` has installed all the preregistered extensions.

Quick fix is to wait a micro-task in `waitForExtensionIfStubbed()` so that anything else waiting on body promise gets a chance to run before we look for the stubbed extensions.   Longer term we might want to look at refactoring runtime to make sure that `stubElementsForDoc()` is always the first thing waiting on the body promise.

**Comment by src-code** [comment]
@jpettitt @jridgewell @dvoytenko @zhouyx I'm still seeing this error on Yahoo UK AMP pages via the Google Search carousel, as of this morning (v1528247370025):

![amp-geo-error](https://user-images.githubusercontent.com/60631/41117103-eeff9776-6a40-11e8-887d-ab8a1e3618ec.jpeg)

https://www.google.co.uk/amp/s/www.yahoo.com/amphtml/gma/woman-punched-police-officer-nj-beach-shares-her-141803889--abc-news-topstories.html

Seems to happen pretty consistently if I refresh the page, maybe 1 out of every 10 successfully shows the amp-consent prompt.

**Comment by src-code** [comment]
In my case I have cache disabled while dev tools is open.  Enabling cache seems to fix the issue, so this would primarily affect new users I imagine.

**Comment by choumx** [comment]
After some digging, I think `stubbedElements` is scoped to the JS file that includes it, not the window. This means that each AMP binary will have its own `stubbedElements`.

I think this means that `element-service#waitForExtensionIfStubbed` will never actually wait unless you call it from the same file that elements are registered (v0.js).

**Comment by Rzial** [comment]
Hi, I'm having this same issue on my PWA but not on the web served AMP. Maybe this is somehow related (#15440)? (shadow-v0.js v011528416097273)
