### ISSUE TITLE
How to redirect the date-picker to the current date/month after clearing the selected date by tapping on the clear option in AMP project

### ISSUE THREAD

**Issue by shawkivai** [ampproject/amphtml#15792]
## What's the issue?
Unable to redirect to the current date/month after clearing the selected date by tapping on the clear option in AMP project. After clearing the selected dates when tapping on the input field the datepicker doesn't open in the current month rather than it opens the previous selected month.
Here I am using the Lightbox date picker.

Please help me to solve the issue.....................

## What browsers are affected?
All browsers

## Which AMP version is affected?
Version 1525461683159

**Comment by cvializ** [comment]
We should add an AMP action for this behavior on the amp-date-picker element.

**Comment by shawkivai** [comment]
Can you please tell me which action should we use for this purpose!!!
I have tried various action but can't find the real one.
Thanks

**Comment by cvializ** [comment]
It is not yet implemented, but it will be very soon!

**Comment by shawkivai** [comment]
Thanks a lot. This action is required for many developers. We are looking forward to use the action for datepicker as soon as possible.
Thanks for your co-operation.

**Comment by cvializ** [comment]
This behavior was merged in https://github.com/ampproject/amphtml/pull/16168 and it will go into canary this week and be in production next week. Thank you for reporting!

**Comment by cvializ** [comment]
Not yet, it is still continuing through our canary and production process. We stick to the process to ensure that any hidden bugs are caught before new code is served to all users.

**Comment by shawkivai** [comment]
Please let me know when the action is updated at production. We need it badly.
Thanks in advance.

**Comment by cvializ** [comment]
Looks like it's in production now https://ampb.in/#-LGVzlYZH2IQWWn2ZbhY

**Comment by shawkivai** [comment]
I didn't get any changes after using .today action for current day & .today(offset=1) action for tomorrow.
Can you please help which things i should add to my project after adding these actions in amp-datepicker!!
Thanks.

**Comment by shawkivai** [comment]
I have tested the action (.today) for the current date & (.today(offset=1)) for tomorrow but i didn't get any changes. If it is in production i should receive the update.
Thanks
