### ISSUE TITLE
amp-3d-gltf: problems with validator rules

### ISSUE THREAD

**Issue by mixtur** [ampproject/amphtml#15793]
## What's the issue?

Validator complains
- when alpha=true
- on every camel-cased attribute

## How do we reproduce the issue?
I tried to add sample for amp-by-example and stumbled upon this 

this html claimed to be broken
```html
<amp-3d-gltf layout="fixed"
             width="320"
             height="240"
             alpha="true"
             antialiasing="true"
             autoRotate="true"
             enableZoom="false"
             src="https://webgears-3d.github.io/3d-gltf-static/m/DamagedHelmet.glb"></amp-3d-gltf>
```
errors:
```
components/amp-3d-gltf/source/index.html:43:2 The attribute 'alpha' in tag 'amp-3d-gltf' is set to the invalid value 'true'. (see https://www.ampproject.org/docs/reference/components/amp-3d-gltf)
components/amp-3d-gltf/source/index.html:43:2 The attribute 'autorotate' may not appear in tag 'amp-3d-gltf'. (see https://www.ampproject.org/docs/reference/components/amp-3d-gltf)
components/amp-3d-gltf/source/index.html:43:2 The attribute 'enablezoom' may not appear in tag 'amp-3d-gltf'. (see https://www.ampproject.org/docs/reference/components/amp-3d-gltf)
```

**Comment by mixtur** [comment]
For alpha I just wrote wrong rule.
Need help with other attributes.

**Comment by aghassemi** [comment]
@honeybadgerdontcare, could you please help @mixtur fix https://github.com/ampproject/amphtml/blob/master/extensions/amp-3d-gltf/validator-amp-3d-gltf.protoascii ? I wonder if case-sensitivity has something to do with these failure.

Let's ensure the validator test is updated here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-3d-gltf/0.1/test/validator-amp-3d-gltf.html as well.

**Comment by Gregable** [comment]
I believe this can be closed then.
