### ISSUE TITLE
feature request add GET params for `amp-app-banner` when build link to app store

### ISSUE THREAD

**Issue by abdelbolanos-cbc** [ampproject/amphtml#15803]
Hi,

We use the `amp-app-banner` component to allow our users to install or open our CBC apps from AMP. This feature is specifically about tracking the number of installs.  

Is it possible to add extra params when AMP builds the URL that goes to the store to install the app? These extra params could be campaign params for tracking the source, like:

Android: https://play.google.com/store/apps/details?id=ca.cbc.mobile.android.cbcnewsandroidwebview&referrer=utm_source%3DAMP

iOS: https://itunes.apple.com/app/apple-store/<app-id>?pt=63436&ct=AMP&mt=8 

Looking at the source code of `amp-app-banner` https://github.com/ampproject/amphtml/blob/master/extensions/amp-app-banner/0.1/amp-app-banner.js
It looks like we might be able to use functions like:
`parseManifest_` (Android)  and `parseIosMetaContent_` (iOS)

But we would need a way to get extra params from manifest.json in Android and for iOs from the <meta> tag. Is that possible? Is our approach correct? 

Many thanks

**Comment by aghassemi** [comment]
@abdelbolanos-cbc We might be able to add params to the links when we render them, but `amp-app-banner` falls back to native app install banners on [Anroid](https://developers.google.com/web/fundamentals/app-install-banners/native)/[iOS](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html) when it can. We have no control over those Urls.

Do you know of parameters that native smart app banners support for your use-case? I am worried about adding features that native smart app banners don't support given whether AMP version or native shows up is dependents on who the AMP page is being viewed and embedded.

**Comment by abdelbolanos-cbc** [comment]
Hi @aghassemi, thanks for the reply. Actually we are more interested in the URL that AMP has control because when users get to AMP from Google results is more common to see the webview banner (AMP viewer context). 
Looking at native app banner I have some recommendation:

iOS: Based on [iOS app banner native](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html) there is no attribute for provide a url for install the app, but if we could add one attribute that could work for our AMP (grab the content from the parser function) could be good. Something like:
`<meta name="apple-itunes-app" content="app-id=myAppStoreID, affiliate-data=myAffiliateData, app-argument=myURL" amp-param="pt=63436&ct=AMP&mt=8">`

Android manifest.json: I noticed that the url for Google app store is been built using the `id` in the `related_applications` in the json file. I wonder if is possible to use `url` instead of `id`[ reference](https://developer.mozilla.org/en-US/docs/Web/Manifest#prefer_related_applications) to take the user to install the app. This way any campaign or tracking info can be added to the `url`. Like:
`
"related_applications": [
    {
      "platform": "play",
      "id": "ca.cbc.mobile.android.cbcnewsandroidwebview",
      "url": "https://play.google.com/store/apps/details?id=ca.cbc.mobile.android.cbcnewsandroidwebview&referrer=utm_source%3DAMP"
    }
  ]
`
I understand your point about 
> ` I am worried about adding features that native smart app banners don't support`
But right now nothing exists for tracking app installs. If you agree that is better something than nothing then you will see the benefit of this feature. Is hard to know the impact of products if we cannot measure them. Thanks again.

**Comment by aghassemi** [comment]
@abdelbolanos-cbc Thanks for the details. In that case I assume, when Url is customized, you prefer AMP to show its version of app banner and not display the system one, even when possible. Is that assumption correct?

**Comment by abdelbolanos-cbc** [comment]
Hi @aghassemi,
I am not saying that AMP should force show its version of app banner when URL is customized( but now you say that, it's not a bad idea). What I meant is when AMP shows its version of app banner (#webview=1), I prefer to use the URL field to point to the "play store" and not the url that is being built inside AMP using the "id" of the application (at least for Android).
Thanks

**Comment by abdelbolanos-cbc** [comment]
Hi team,
any update on this?
Thanks

**Comment by aghassemi** [comment]
deduping with https://github.com/ampproject/amphtml/issues/6411
