### ISSUE TITLE
amp-video: Transition from poster to first frame is not seemless

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#15802]
There is a blank white frame between poster of an `amp-video` going away and first frame of video showing up. Specially in the case of `autoplay` this becomes fairly noticeable. although on iOS it seems to be fairly seamless, on Chrome it is very obvious. 

Worth investigating why this is happening on Chrome and if there is anything we can do. We may need to wait for a different event before hiding the placeholder.

repro:
- Go on tasty.co on Chrome / Mobile

@alanorozco

**Comment by alanorozco** [comment]
Closed by #15957
