### ISSUE TITLE
AutoSuggest not working on AMP Cache URL and iOS User Agent (Chrome/Safari)

### ISSUE THREAD

**Issue by gilbertococchi** [ampproject/amphtml#15828]
Hi all, we've noticed a weird with issue with AutoSuggest not working on iOS User Agent on this Cache URL for some reason:

https://www.google.com/amp/s/www.ilmeteo.it/notizie/meteo-anche-oggi-rischio-supercelle-vediamo-dove-colpiranno-mappe-e-video/amp

Both on iOS Mobile Safari and Chrome Desktop via emulating iPhone UA the autocomplete CORS requests do not trigger, example: https://www.ilmeteo.it/portale/ac_amp.php?q=meteo&__amp_source_origin=https%3A%2F%2Fwww.ilmeteo.it

I cannot see any console error and/or warning but I can see it working fine on https://www.google.it/amp/s/ampbyexample.com/advanced/autosuggest/  (City) field.

Can somebody tell what is wrong with this page?

<img width="1540" alt="screen shot 2018-06-05 at 11 17 20" src="https://user-images.githubusercontent.com/329023/40966918-0dbc56bc-68b2-11e8-8fc8-d0ba1d78e4e5.png">

blob:https://www-ilmeteo-it.cdn.ampproject.org/33dd5536-af56-41b0-8e1d-50d51145174a

Thanks
Gilberto

**Comment by gilbertococchi** [comment]
@tomayac, @antoinebish, @martinschierle, @Pocamus51270

**Comment by tomayac** [comment]
Some more detail as to where the error occurs:

![screen shot 2018-06-05 at 11 25 53](https://user-images.githubusercontent.com/145676/40967526-7e14a3c8-68b3-11e8-9fd2-b6eb4f4d9e38.png)

The formatted Blob file contents:

[https-::www-ilmeteo-it.cdn.ampproject.org:0a0dd754-eafd-40d5-853e-e23a4374b544-formatted.js.txt](https://github.com/ampproject/amphtml/files/2071713/https-.www-ilmeteo-it.cdn.ampproject.org.0a0dd754-eafd-40d5-853e-e23a4374b544-formatted.js.txt)

The console warning reads: *"query is not defined; returning null."*

**Comment by aghassemi** [comment]
I can repro. Likely has something to do with fixed layer + form/bind. 
/to @cvializ for initial investigation.

**Comment by aghassemi** [comment]
setting to P1 for investigation

**Comment by cvializ** [comment]
I am able to reproduce. Initial investigation shows that the `amp-list` is not removing its `hidden` CSS class in response to the AMP action `show`. The element's expand method is getting called, but the class is not removed. More investigation is needed.

**Comment by gilbertococchi** [comment]
Hi all, I can see a note on #16130 that should fix this issue but I can still reproduce the same issue on Canary (iOS Safari).

**Comment by aghassemi** [comment]
@gilbertococchi #16130 is not in production yet. It will be by July 10th. (likely 3rd)
