### ISSUE TITLE
fixed small size image ignored and resize

### ISSUE THREAD

**Issue by nzcage** [ampproject/amphtml#1582]
Using `<amp-img>` with fixed small size (e.g. 18x12 px) makes image larger.
I use external stylesheet as well as `width` & `height` attr inside `<amp-img>`

**Comment by dvoytenko** [comment]
Could you please share the code snippet or a link to reproduce?

**Comment by nzcage** [comment]
Sure. http://www.wwwsitus.com.
I attempt to my own blog. It's still there with bigger size.

**Comment by dvoytenko** [comment]
Thanks! I see the issue. It conflicts with padding defined elsewhere. We will fix this.

**Comment by nzcage** [comment]
I rechecked my work and it's my fault ( I add padding at the image through class selector `en` :D ). sorry to trouble you. I was not thorough. Thanks for your reply. I guess this is not a bug, right?

**Comment by dvoytenko** [comment]
I see. Correct. I will close then.
