### ISSUE TITLE
amp-access-tempalte filters actions

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#15834]
## Steps to reproduce

Define an `on` action inside an `amp-access-template`.

```
  <template amp-access-template type="amp-mustache">
      <button on="tap:myLightbox.show" role="button" tabindex="1">Press</button>
  </template>
```

Actual behavior: the on action is removed when the template is rendered.
Expected behavior: the on action is rendered

//cc @dvoytenko  @aghassemi

**Comment by aghassemi** [comment]
@sebastianbenz Do you have the `svg-in-mustache` experiment on by any chance? Might be just https://github.com/ampproject/amphtml/pull/15820 (which are all under experiment flag and should not impact production)
/cc @choumx

**Comment by sebastianbenz** [comment]
No, I haven't got the svg-in-mustache experiment enabled.

**Comment by sebastianbenz** [comment]
Yup - just verified it. It's only a problem in dev channel.

**Comment by choumx** [comment]
#15820 fixes this.
