### ISSUE TITLE
Extend amp-layout to support "absolute" posititions

### ISSUE THREAD

**Issue by cpapazian** [ampproject/amphtml#15837]
Since [inline styles](https://github.com/ampproject/amphtml/issues/11881) is going to enforce a hard cap on CSS/styles, we will still have the maintenance issue of styling based on content sizes potentially breaking validation. Adding an "absolute" positioning option to `<amp-layout>` (and other AMP elements that provide a `layout=` option, would allow decoupling of style and layout, allowing tighter scrutiny of CSS/style, while maintaining flexible options for dynamically generating layout. This would extend the "fixed" layout, adding the ability to provide top, left, bottom, right, and (maybe?) z-index as attributes, which would be rendered as an inline style on the amp-layout dom element, as is currently done for "fixed" (and other) layouts.

**Comment by cpapazian** [comment]
@aghassemi we discussed this at i/o. you suggested that a special case would be redundant, since the inline styles restriction is being dropped. since it looks like that change is being nerfed, this feature would be useful to us. happy to provide a diff if this sounds reasonable.

**Comment by aghassemi** [comment]
We should discuss this in a Design Review, given that it requires adding 5 more attributes (4 positions and z-index) and that CSS (inline or page level) handles this, I am not sure if it is worth adding to the API.

**Comment by jpettitt** [comment]
Yeah it seems like it would be a lot slower to render attributes to CSS via JS than just including the CSS.  In the case where it's pre-rendered in the cache it would increase the CSS size anyway.   If the argument about CSS size is valid (a whole other argument) then doing this doesn't really get us anything and in fact makes it slower in non cache cases.

**Comment by aghassemi** [comment]
no plans for this, if anything we should extend the limit of CSS/Style
