### ISSUE TITLE
DoubleClick ads don't collapse on Firefox with Tracking Protection on

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#15843]
Steps to reproduce:
1. Download this [gist](https://gist.github.com/danielrozenberg/2c60562524528caec9dc3ef34ea5ab93) and run a local server
2. Turn on Firefox's Tracking Protection (either through the settings, by opening a private browsing window, or clicking on the logo to the left of the URL bar and selecting tracking protection)
3. The ad, which doesn't exist, should collapse, but amp-ad's code crashes at some point because Tracking Protection stops the browser from loading doubleclick.net URLs

**Comment by keithwrightbos** [comment]
Can you elaborate on what you mean by "amp-ad's code crashes"?  If the CORS XHR request to get the ad response is blocked, we attempt to fetch the ad using an iframe GET (<iframe src=ad request>) as its possible there was an intermittent network error.  We currently do not attempt to collapse if the iframe request also fails (we only attempt to collapse if XHR CORS response is valid and indicates no fill).

**Comment by danielrozenberg** [comment]
Yeah, this is exactly it. It's trying to load the ad as an iframe and then it doesn't collapse as you described

**Comment by jasti** [comment]
We should probably do this across all networks. Reassigning to @lannka.

**Comment by cramforce** [comment]
I don't think this is possible. As in: We have no way to know generically that a request failed.

DoubleClick could probably invest in detecting this if they'd like to improve the experience of people using ad blockers.

**Comment by calebcordry** [comment]
Closing this based on the last comment. Feel free to reopen if we have an AMP side way to make this experience better.
