### ISSUE TITLE
Dailymotion embed doesn't work in Chrome using amp-iframe

### ISSUE THREAD

**Issue by okeul** [ampproject/amphtml#1585]
Currently it's not possible to show Dailymotion video in Chrome but it works in Firefox.

Example : http://codepen.io/okeul/pen/YwZmgo

Chrome 47.0.2526
Firefox 41.0.2 & 43.0.4
OSX 10.8.5 & 10.10.4

**Comment by rudygalfi** [comment]
Let's use this issue to track the FF/Chrome inconsistency. amp-iframe should work in this context. Opened #1588 for tracking a new DailyMotion component.

**Comment by cramforce** [comment]
I'm all for a dedicated dailymotion embed.
From some casual testing I'm not sure we can fix the Chrome issue. See http://output.jsbin.com/bejeze for a non-AMP page (just a naive iframe) with the same problem. Maybe this is the wrong URL for them?

**Comment by okeul** [comment]
Thanks for your quick answer ! 

@cramforce : You're almost right, there is a problem with https & dailymotion. It works in http but not in https :
Example for a no-AMP page : http://codepen.io/okeul/pen/qboMRQ

**Comment by johnnyshankman** [comment]
So currently there is no solution for Dailymotion, as HTTPS is unreliable as a `src` even for regular `<iframe>` tags?

**Comment by johnnyshankman** [comment]
Can confirm that the same <amp-iframe> that does not work in Chrome works just fine in iOS9 Safari.

**Comment by johnnyshankman** [comment]
Looks to me like it's an issue with Flash inside of the iframe maybe? 

On my mobile device it seems to be working because it's forcing an HTML5 fallback player instead of the flash player. Anyone else see this happening?

**Comment by okeul** [comment]
@johnnyshankman : That can be right, it's the same for me. It works on my mobile with Dailymotion & https (AMP & no-AMP).

Android 6.0.1 / Chrome 47

**Comment by cramforce** [comment]
Yes, flash will not work inside `amp-iframe`.

A specific amp embed for dailymotion or AOL would not have this limitation.

**Comment by cramforce** [comment]
Could somebody contact dailymotion and/or AOL whether they e.g. support a URL param to opt out of the flash player?

**Comment by okeul** [comment]
I tried to reach the technical support of Dailymotion. I haven't received any responses yet.

**Comment by zeno** [comment]
Hi guys, we are in contact with Google and working on a specific `amp-dailymotion` component.

**Comment by zeno** [comment]
See #2017.

**Comment by jridgewell** [comment]
Closed by #2017, pending #1732 to pass validation.
