### ISSUE TITLE
Prioritize amp-release / canary builds on Travis

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#15851]
From pushing an `amp-release` or `canary` build to it finishing takes 4+ hours, and this is after canceling all other queued builds on master. The only remaining way to make this go faster is to go cancel all the other PR builds, which is... not very nice. There doesn't seem to be an obvious way to do this in Travis (or even Circle), but it would be nice if we could have builds for branches named `amp-release` or `canary` take precedence over other builds without the on-duty canceling everyone else's PR build. Otherwise we'll have to budget 2 days for each release so the build can run overnight. 

A minor optimisation would be to not build jobs that only involve doc changes. These currently also try to build on master and take up a VM for a full hour, which doesn't make a lot of sense.

**Comment by cathyxz** [comment]
It was a push build. https://travis-ci.org/ampproject/amphtml/jobs/388454977. I canceled it, but it was trying to run `gulp build`. Oh well, I will close this issue since it's part of #13380 already.

**Comment by rsimha** [comment]
Yeah. This isn't ideal, but I'm not sure how we can prioritize builds without native support from Travis. Thanks for filing this issue.
