### ISSUE TITLE
amp-img not load inside img

### ISSUE THREAD

**Issue by godforger** [ampproject/amphtml#15862]
## What's the issue?

`amp-img` not load inside img

## How do we reproduce the issue?

You can see my issue in this public URL: [https://hightech.fm/amp/2018/06/05/smart](https://hightech.fm/amp/2018/06/05/smart)

![bug](https://user-images.githubusercontent.com/10621751/41050919-5e4451be-69bd-11e8-8ca4-307e2bbed3c8.png)

## What browsers are affected?
Chrome 66, firefox 60

##  Which AMP version is affected?
Version 1527809694656

**Comment by aghassemi** [comment]
@godforger The parent `div class=icon` for `amp-img` in your markup does not have a predefined size. When using  `layout=responsive` the component fills the `width` of the parent but when parent itself does not have a size, it becomes meaningless.

You have a few options:
1- Make sure the parent `div` has a `width` (either through explicit `width` in CSS or using flexbox, grid, etc..)
2- Use `layout=fixed` for `amp-img`
3- Use `layout=intrinsic` for `amp-img`

**Comment by aghassemi** [comment]
Closing the issue per comment above.
