### ISSUE TITLE
✨ FR Validator should reject invalid <script type="application/json">

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#15888]
Invalid JSON in amp component makes pages behave in unexpected and invalid ways.  This is a feature request to add JSON validation to the validator and to treat as invalid any AMP page with bad ` <script type="application/json">` tags.

**Comment by newmuis** [comment]
`amp-consent` and `amp-story` would benefit from this too.

**Comment by jpettitt** [comment]
and `amp-analytics`

**Comment by aghassemi** [comment]
+1

**Comment by Gregable** [comment]
This was implemented a while ago by @honeybadgerdontcare 

See example output in https://github.com/ampproject/amphtml/blob/master/extensions/amp-geo/0.1/test/validator-amp-geo.out
