### ISSUE TITLE
javascript source map on cdn.ampproject.org refers to "http://localhost:8000/"

### ISSUE THREAD

**Issue by bquinn** [ampproject/amphtml#1589]
The [Javascript source map on the AMP CDN](https://cdn.ampproject.org/v0.js.map) refers to `http://localhost:8000/` which breaks source view in the Chrome web inspector / developer console.

It's not a big issue by any means but it would be nice it it were fixed!

**Comment by cramforce** [comment]
The question is: What would be a better value?

How is it broken?

**Comment by bquinn** [comment]
Actually I noticed that in my local build it's fine - all the references in the map file are relative. But in the CDN version at https://cdn.ampproject.org/v0.js.map all references use `http://localhost:8000/` - so I guess the issue is fixed and we just need to update the CDN!

**Comment by cramforce** [comment]
They use different build methods. If you have the local server running it works, right?

What is the failure you are seeing?

**Comment by bquinn** [comment]
Yes if I have the local sever running it works. I was just trying to examine the source directly from the CDN (via a BBC example page) without running the local server.

Are you planning to include the map file and full source on the CDN for the final build? Otherwise it may be worth just leaving out the reference to the map file in the final version to avoid 404 errors for developers as happened [when JQuery stopped including source files] (http://stackoverflow.com/questions/18365315/jquerys-jquery-1-10-2-min-map-is-triggering-a-404-not-found).

But then you were probably going to do that anyway!

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please verify first whether the feature proposal is still relevant.

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
