### ISSUE TITLE
Discussion - how to handle errors in service promises.

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#15909]
# Scenario

`amp-geo` provides a service `geo`.  In order to prevent a race condition it creates the service promise as soon as the JS loads and well before it's had a chance to parse it's config.  If there is a config error what should it do?

##  Just throw

Call `user().assert()` and be done.  The upside of this is it's simple the downside is anything waiting on the service promise just hangs.  This is the current state of play.

## Reject

Reject the service promise.  This has the advantage that the consuming extension can catch and make a decision about how to handle the error.  Fails 'safe' if the consumer doesn't `catch()` the error. Allows for meaningful error messages:

`[amp-user-notification] geo service error: Error: [amp-geo] Syntax error, unable to parse JSON`

The downside is that if nothing is waiting on the promise you also get an uncaught promise error.

## Resolve with error status and throw

Resolving the promise with an error status (but not an Error object) allows consuming services to handle the error and still logs it.  Downside the consumer has to know how to handle the error status, it doesn't fail safe.

This feels like something we should have a standard way of handling. Thoughts?

//cc @dvoytenko @cramforce @jridgewell @lannka @zhouyx @kbax @rudygalfi @aghassemi @choumx

**Comment by choumx** [comment]
Option 3: Use a class to wrap the `geo` JSON "service" which won't fail instantiation, and instead expose the JSON config through a function. I think this is closer to the model of existing services -- all of which are JS classes rather than primitives (AFAIK).

**Comment by aghassemi** [comment]
I think this is essentially what Will is suggesting, what I was thinking is:

```
Services.geoForDocOrNull(doc).then( geoService => {
});
```

The `promise` returned from `Services.geoForDocOrNull(doc)` is always resolved. But `geoService` will be `null` if instantiation fails for any reason, including bad JSON.

**Comment by jpettitt** [comment]
basically option three resolve with error status (null`) and throw.
