### ISSUE TITLE
Tracking events in PWA that uses "AMP as data source for your PWA"  logic

### ISSUE THREAD

**Issue by ingoingoingo** [ampproject/amphtml#15912]
We are using the "AMP as data source for your PWA" method promoted by @pbakaus to load pages of our Wordpress Page into out React SPA PWA.
It works great and saved us a lot of time.
At the GoogleIO I confrontend @rudygalfi with my following problem and he asked me to put this here. 

Issue:
We a struggeling with properly tracking the user behaviour of those pages in Google Analytics. 
Tracking inside the PWA can be done easly. When we hit a page view that uses the "AMP as data source for your PWA" we can track the Page Impression. Based on the API response in the PWA when fetching the page we can fill up our analytics with all the needed data.

What we can´t do is: Track any events happening on the AMP page that is loaded inside the PWA in the context of the PWA.

We even do use different URLs when the page is viewed in AMP mode and when used inside the PWA (since we are just using it as a datasource).

I would be happy to get some ideas on how to achieve proper event tracking of the PWAMP model.

Thank you very much.

**Comment by zhouyx** [comment]
to @jeffjose to triage.
