### ISSUE TITLE
Add amp-giphy extension

### ISSUE THREAD

**Issue by cogell** [ampproject/amphtml#1591]

**Comment by pribeh** [comment]
Any update on this? Thanks

**Comment by rudygalfi** [comment]
No updates from me. Does anyone know someone and Giphy who we could get to comment?

**Comment by pribeh** [comment]
https://github.com/Giphy/GiphyAPI/issues/90

**Comment by timfrietas** [comment]
Hey guys,

Tim, Product Manager at Giphy here!  I am closing out the ticket on our Github Issues because we fold feature requests into our product backlog and use Issues just for bugs.

I must confess I know little about AMP; if someone wants to bring me up to speed on what you're proposing either here or via email at tim@giphy.com I am happy to chat about it!

**Comment by pribeh** [comment]
Hey Tim, some of the others can probably speak better about AMP probably. But, suffice to say, it's a standard of html/css/js for efficient page loading which Google has put out to get web publications to support mobile devices better. Google even caches a copy of the page and loads it into a mobile carousel via their mobile web search results. The trick is here that iframes and javascript often need some help implementing at this point. I'm not actually sure what's required to support Giphy at the moment but my publication certainly uses your embed service a lot.

**Comment by jridgewell** [comment]
Ping @rudygalfi, could you reach out to @timfrietas?

**Comment by rudygalfi** [comment]
Hey @timfrietas -- @pribeh summed it up pretty well. If you haven't seen our project site yet, you can visit https://www.ampproject.org to learn more about AMP.

From a developer standpoint, one of the key things to know about AMP is that custom JS is not allowed on an AMP page unless it's built as an AMP extension (i.e. a web component) in this open-source repo.

It's not an exact comparison, but what we'd be looking to do here is something similar to what video player vendors like Brightcove have done to enable their video players to be supported in AMP: https://ampbyexample.com/components/amp-brightcove/

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please verify first whether the feature proposal is still relevant.

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)

**Comment by rudygalfi** [comment]
Putting this into https://github.com/ampproject/amphtml/projects/17 and closing while we wait for implementation from Giphy.
