### ISSUE TITLE
submit input is not sended

### ISSUE THREAD

**Issue by KnoellMarketing** [ampproject/amphtml#15919]
`<input type="submit" name="button" value="x">Send me</input>`
ist not sended in amp-form by clicking the button (rest of "normal" inputs like textearea, select and input=text are sended)

**Comment by cvializ** [comment]
Looks like this behavior is spec'd by the standard, so let's make sure we implement it!

**Comment by aghassemi** [comment]
Closing as dup of https://github.com/ampproject/amphtml/issues/16461
