### ISSUE TITLE
AOL Video Not Embeddable due to Sandbox & Flash Incompatibility

### ISSUE THREAD

**Issue by johnnyshankman** [ampproject/amphtml#1592]
Working `iframe`:

```
<iframe
  width=512 
  height=288
  sandbox="allow-scripts allow-same-origin"
  frameborder="0"
  src="https://embed.5min.com/PlayerSeed/?sid=1890&playList=519353534">
</iframe>
```

Not working with `amp-iframe`:

```
<amp-iframe
  width=512 
  height=288
  sandbox="allow-scripts allow-same-origin"
  layout="responsive"
  frameborder="0"
  src="https://embed.5min.com/PlayerSeed/?sid=1890&playList=519353534">
  <amp-img layout="fill" src="image.jpg" placeholder></amp-img>
</amp-iframe>
```

Instead it produces a blank iframe.

Here is what it looks like with the iframe on top of the amp-iframe:

![screen shot 2016-01-26 at 2 29 32 pm](https://cloud.githubusercontent.com/assets/6632701/12592173/4672b4c6-c439-11e5-948d-67af5445540f.png)

The page is completely valid when using the `<amp-iframe>` and this same approach has worked for Vimeo and Ooyala.

Documentation for the src of the iframe:
http://help.aolonnetwork.com/hc/en-us/articles/204275675-How-to-Implement-a-Player-Grab-code-in-an-iFrame

**Comment by johnnyshankman** [comment]
Extremely similar to this issue: https://github.com/ampproject/amphtml/issues/1585

The `<amp-iframe>` renders just fine in iOS9 Safari.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
