### ISSUE TITLE
Progress bar on top of the content in the desktop bookend.

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#15927]
Progress bar is on top of the content in the ``1.0`` desktop bookend, and hurts the readability.

![image](https://user-images.githubusercontent.com/1492044/41166791-28822daa-6b0f-11e8-846d-bdec3db83b5d.png)

**Comment by sanjsanj** [comment]
@gmajoulet Is this ticket available to be picked up please?

We could simply `display:none` on the `aside.i-amphtml-story-system-layer` if the bookend is active.  The system-layer element also contains system-layer-buttons for mobile and share-pills for desktop that sit above the bookend.

**Comment by gmajoulet** [comment]
Update: Actually the `system-layer` is not on top of the bookend, even if it looks like it.

@sanjsanj: We'll make sure this bug is solved this week, thanks for looking into it!
