### ISSUE TITLE
Add CSI Ping for unscheduled elements in viewport

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#15945]
As part of the Layers migration, we should add a new CSI ping for the number of unscheduled (layout) elements in viewport. We might be able to get away with using `isInViewport` to count the elements in viewport, or we can fall back to an `IntersectionObserver` if that's not reliable enough.

Either way, get the count, then filter out any resources that are already scheduled for layout (or already laid out).

We can use this metric for both Resources code and Layers code, to make sure that we don't get many more unscheduled elements when running Layers.

**Comment by erwinmombay** [comment]
This is a high priority issue but it hasn't been updated in awhile. @jridgewell Do you have any updates?

**Comment by jridgewell** [comment]
This was abandoned in favor of manual testing.
