### ISSUE TITLE
Upgrade amp-carousel (type="slides") to get rid of vsync

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#15940]
The full background on why is a deep dive talk that @jridgewell gave called "Vsync Considered Harmful". The TLDR is we're now upgrading all references of vsync as follows: 
```
VSync#measure
BaseElement#measureElement
VSync#mutate
BaseElement#mutateElement
VSync#run
BaseElement#measureMutateElement
```

We still need to do this for `<amp-carousel>` type slides, in the file [slidescroll.js](https://github.com/ampproject/amphtml/blob/master/extensions/amp-carousel/0.1/slidescroll.js).

**Comment by aghassemi** [comment]
@cathyxz since all issues should have an assignee, adding you for now. Delegate when time comes.

**Comment by sparhami** [comment]
I'm guessing the usage in base-carousel should change as well? https://github.com/ampproject/amphtml/blob/a492b487bf2432eb424bc8537f52dac391538c64/extensions/amp-carousel/0.1/base-carousel.js#L184

**Comment by cathyxz** [comment]
Yup!

**Comment by cathyxz** [comment]
I think this has been done already.
