### ISSUE TITLE
Add an option to amp-next-page to allow a non-cdn URL (dynamic content)

### ISSUE THREAD

**Issue by mpatnode** [ampproject/amphtml#15956]
The amp-next-page component always rewrites the URL for the next page to point to the CDN.   This eliminates the ability to dynamically choose content.   Given the pages are cached in the CDN, forcing the decision of what the "next" page is at AMP code render time is very restrictive.

One simple solution may be to respect fully qualified URLs, and only rewrite relative URLs to point to the current CDN.

Otherwise a "dynamic-content" option for the component or some such.

**Comment by cathyxz** [comment]
cc @aghassemi @peterjosling

**Comment by peterjosling** [comment]
Always rewriting was a bug, fixed in #15831 which should hit canary today.

This still requires that the content is served from the same domain, so documents served from the cache can only request other documents from the cache.

**Comment by mpatnode-si** [comment]
Understood, so that's precisely the nature of the request.   While I'm happy for the actual content to come from the cache/CDN, I want to call back to my live server to decide what that content will be.

**Comment by peterjosling** [comment]
Would being able to load the config from an endpoint on your own server work for your use case? So allowing `<amp-next-page src="https://example.com/next-page.json">`

**Comment by mpatnode-si** [comment]
Nice! We'll give that a shot.

**Comment by peterjosling** [comment]
Sorry, to clarify: that isn't possible yet, but that's the kind of syntax I'm thinking about using to implement it.
