### ISSUE TITLE
Header and/or link missing in STAMP privacy info

### ISSUE THREAD

**Issue by tingyiwei** [ampproject/amphtml#15968]
For some STAMP documents, header "View on original domain" and/or link "More about AMP results" are missing.

![image](https://user-images.githubusercontent.com/36043989/41258905-cd4f2d0a-6d9f-11e8-9a32-a36378cbc724.png)

![image](https://user-images.githubusercontent.com/36043989/41258849-8fd5783a-6d9f-11e8-90c5-3e2e42bbfb2c.png)

**Comment by tingyiwei** [comment]
One more thing is that click on canonical url directs to 404.

**Comment by newmuis** [comment]
@tingyiwei do you have an example where the canonical 404s?

**Comment by tingyiwei** [comment]
It seems not working for all results from Visual Stories carousel testing on IOS chrome and I've optin dev channel.
![image](https://user-images.githubusercontent.com/36043989/41670154-800cfdb8-7481-11e8-9f42-83d5a018dd7b.png)

https://www.washingtonpost.com/graphics/2018/local/amp-stories/restaurant-wage-tipping-explainer-initiative-77/
https://www.washingtonpost.com/world/worldviews/2018/06/14/amp-stories/why-was-londons-grenfell-tower-fire-so-significant/
