### ISSUE TITLE
<amp-video> does not prerender, even with cached sources

### ISSUE THREAD

**Issue by sparhami** [ampproject/amphtml#15965]
## What's the issue?

`<amp-video>`'s `prerenderAllowed` function will always returns false, causing it to never be prerendered.

The flag that is used for `prerenderAllowed` is set in the `buildCallback` here: https://github.com/ampproject/amphtml/blob/10ccab24d5f734d2b473833582dedf66dd42930b/extensions/amp-video/0.1/amp-video.js#L175

But the `buildCallback` does not run during the prerender phase if `prerenderAllowed` returns `false`: https://github.com/ampproject/amphtml/blob/3a3440eb5d15faf1b1e26f757662298d047178c3/src/service/resources-impl.js#L561-L563

One thought is to move the `isPrerenderAllowed_` flag into the constructor, but this is not ideal because that checks child elements, and:

> The element's attributes and children must not be inspected, as in the non-upgrade case none will be present, and relying on upgrades makes the element less usable.

https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance

In AMP, it looks like we have access to the children in the constructor. Does not seem like a good idea to be looking at them though.

**Comment by aghassemi** [comment]
@sparhami Currently only AMP-Stories served through cache can trigger `amp-video` prerender mode. That's the only time `hasAnyCachedSources_` returns `true`.

**Comment by aghassemi** [comment]
Oh I see what's happening here. Probably just having the default value of ` this.isPrerenderAllowed_ ` be `true` will solve this. `BuildCallback` would later update it and second time it is queries for `layoutCallback`, it would be the right value.

**Comment by aghassemi** [comment]
@sparhami Prerender logic seems to be running fine here: https://www-washingtonpost-com.cdn.ampproject.org/v/s/www.washingtonpost.com/graphics/2018/opinions/amp-stories/king-trump/?amp_js_v=0.1#visibilityState=prerender let's figure out why that's happening. I am not too sure the `resource.prerenderAllowed()` is the one overriden from custom classes. Might be `preupgrade`.

**Comment by sparhami** [comment]
Hmm, I don't seem to see an `<amp-video>` in the link you have above.

From what I traced through using dev tools, the resource prerenderAllowed seems to be here: https://github.com/ampproject/amphtml/blob/37e5339092d08e0e2147e6249c43b8cf9f367e57/src/service/resource.js#L652-L654
Which goes here: https://github.com/ampproject/amphtml/blob/0026d56f986048e6c3d61e6a69ca24d14fae7172/src/custom-element.js#L905-L907

I originally found this by modifying examples/viewer.html, changing the second page in the viewer to amp-video.amp.html and putting a breakpoint in the `buildCallback`. After looking at the build schedule function, I tried out changing the prerenderAllowed to true, and noticed the `buildCallback` was called.

> Oh I see what's happening here. Probably just having the default value of this.isPrerenderAllowed_ be true will solve this. BuildCallback would later update it and second time it is queries for layoutCallback, it would be the right value.

That seems to work as expected (`buildCallback` is called, but not `layoutCallback`). I can try to put together a PR and figure out how to have a test make sure it keeps working in the future. It does feel a bit strange having the `prerenderAllowed` result change between build and layout, but if an integration test can cover it, shouldn't be a problem.

**Comment by aghassemi** [comment]
@sparhami looks like this is a regression: https://github.com/ampproject/amphtml/pull/12322 @choumx before #12322 we used to build all components (regardless of `isPrerenderAllowed` since that flag was mostly about `layout`) up to a certain threshold. Now we only build the ones that have `isPrerenderAllowed` set to true. I don't think `isPrerenderAllowed` should play a role in whether `buildCallback` is called or not, we should build components in DOM order up to the limit.

**Comment by choumx** [comment]
Ah, good catch. I don't think reverting #12322 is right either since we still don't want to waste prerender build quota on elements that are *never* prerendered. We just need to support elements that may be conditionally prerenderable.
