### ISSUE TITLE
Is AMP.pushState support for URL setting just like history.pushState ?

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#15978]
To whom it may concern:

I wonder is AMP.pushState support for URL setting just like history.pushState ?

```
<button on="
    tap:AMP.pushState({foo: '123'}, 'Title', '/foo')
">Set 'foo' to 123 & change URL</button>
```

Paul

**Comment by choumx** [comment]
Hey Paul, thanks for the feature request. This is covered under "V1" of this proposal: https://github.com/ampproject/amphtml/issues/9128#issuecomment-320332045

Most of this work was recently merged in #15436. Should be straightforward to extend the `AMP.pushState` action.

**Comment by meistudioli** [comment]
Hi, William:

Cool! So exciting to hear this. Do developers need to change anything to adopt it ?

such as amp component lib:
```
https://cdn.ampproject.org/v0/amp-bind-0.1.js
```

Paul

**Comment by choumx** [comment]
Yes, you would need `amp-bind` to use this. Merging with #9128.
