### ISSUE TITLE
amp-video should support m3u8 URLs

### ISSUE THREAD

**Issue by ssaux** [ampproject/amphtml#1597]
right now it mirrors the video HTML element which doesn't. Ideally, both should support m3u8 URLs, but having just amp-video support it would still be a valuable enhancement.

**Comment by rudygalfi** [comment]
I'm unfamiliar with m3u8 other than understanding it's a way to do livestreaming.

To address your request, we'd have to consider whether we introduce capability to amp-video that goes beyond the HTML spec. In a way, it's desirable to have a straightforward mapping of <video> ==> <amp-video>.

Can you talk about how m3u8 normally gets used on sites if not through the <video> element?

**Comment by ssaux** [comment]
Rudy,
   Rather than my rehashing info on m3u8, you may want to start here https://en.wikipedia.org/wiki/M3U. I think it can be used by players to select the best video stream given the device's capabilities. However, you're right that the html video element doesn't support it. You can see an example of what a m3u8 URL delivers (it delivers a text file) with this URL http://streaming.hearstdigitalstudios.com/jukin/564248167765623f7d00007a_1447184413.m3u8
As you can see from the contents, it has further instructions with the codex and resolution for each. Players can then choose the most appropriate for the situation. In effect it enables responsiveness.

M3u8 also enabled live streaming. Apple is big on m3u8 in IOS. See: https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/StreamingMediaGuide/DeployingHTTPLiveStreaming/DeployingHTTPLiveStreaming.html

Note that while trying to open the m3u8 URL I provided in chrome results in a download, in Safari, it plays.

I understand the bit about the video HTML element not supporting these and therefore deciding not to support it in amp-video, although if not supporting it in the video element was an oversight, then  it would just add insult to injury.

Hope this help.
Stephane.

**Comment by peternofelt** [comment]
@rudygalfi any official update/status on this? I saw that it to M but curious to know if its a priority. 

The upside of m3u8 is that its a fairly responsive streaming protocol without much overhead on the server side, the client gets the streaming options and is able to delegate from there.

JWPlayer has strong m3u8 support, if you're looking for a comparison.

**Comment by peternofelt** [comment]
@rudygalfi I assume this is still backlogged?

**Comment by rudygalfi** [comment]
Yes, haven't been able to prioritize this yet. Pull requests welcome. :)

**Comment by adelinamart** [comment]
Is this still relevant?

**Comment by rudygalfi** [comment]
Yep, let's keep this open.

**Comment by rudygalfi** [comment]
@aghassemi I'm shifting this over to you, but I'm not sure of next steps. Perhaps prioritization discussion between us and @ericlindley-g ?

**Comment by aghassemi** [comment]
I believe m3u8 is part of the HLS architecture. Supporting MPEG-DASH for adative streaming makes more sense in AMP than HLS since Chrome has also picked DASH over HLS ( https://bugs.chromium.org/p/chromium/issues/detail?id=54198, https://bugs.chromium.org/p/chromium/issues/detail?id=109652 ).

Closing this in favor of #7744
