### ISSUE TITLE
Urgent Please help : Maximum number of bindings reached (1000). 

### ISSUE THREAD

**Issue by leonalicious** [ampproject/amphtml#15980]
hey guys, we are hitting this error message 
![image](https://user-images.githubusercontent.com/4065175/41292747-079f4e2c-6e86-11e8-90ab-07783a3aebed.png)

Steps to reproduce the error:
1. Please visit : [https://m.aliexpress.com/wholesale/dress.html](https://m.aliexpress.com/wholesale/dress.html) 
2. Open up the `Refine`
3. Choose `Ship To` from the list, select any country and should be hitting the `maximum bindings` within 1 or 2 selections.

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/4065175/41293627-682071b6-6e88-11e8-916f-a0ac9a7dffff.gif)

This `Ship To` Country List is a combination of 2 lists:
1. we use Java foreach to render for the `Popular Country List`.
2. we then use `amp-list` to fetch and render the remaining Country List based on Alphabetical Orders.
Here is our coding (copy from page source alt + cmd + U) ：

````js
<amp-list credentials="include" layout="fixed-height" src="https://m.aliexpress.com/api/countries/sorted" height="400" width="auto" items="data">
    <template type="amp-mustache">
        <p class="ship-to-title country-category">{{group}}</p>
        {{#countryList}}
        <div class="category-box">
            <p role="button" tabindex="-1" 
             on="tap: AMP.setState({
                refineState: {
                    shipToCountry: '{{code}}'
                },
                shipTo: '{{name}}'
            }),ship-to-wrap.hide, category-wrap.show, attribute-syn.hide, attribute-asyn.show, other-refine-wrap.show, form-filter.submit">
                <span>
                    <span [class]="'{{code}}' ? 'country-flag mright c_{{code}}' : ''"></span>
                    <span>{{name}}</span>
                </span>
                <input type="radio" name="shipTo">
                <span class="radio-button" [class]="(refineState.shipToCountry == '{{code}}') ? 'radio-button active' : 'radio-button'"></span>
            </p>
        </div>
        {{/countryList}}
    </template>
</amp-list>
````
It is just a simple `amp-list` which fetches data and render with `amp-mustache`.

FYI, we are a global website aims to deliver goods to our buyer across the world, and this filter `Ship To` really means a lot to us and our buyers, really do appreciate your guys assistance on this ASAP. Thank you guys.

@choumx @aghassemi

**Comment by aghassemi** [comment]
/to @choumx (let's patch along with https://github.com/ampproject/amphtml/issues/15907)
/cc @adelinamart @cathyxz

**Comment by choumx** [comment]
This was released in [RTV 1527809694656](https://github.com/ampproject/amphtml/releases/tag/1527809694656) ~12 days ago on 5/31. The behavior changed in #15517 as a fix for #11434.

#15519 should fix this. Other things to investigate include why we aren't seeing these in our error logging and how to make these errors more meaningful on complex pages.

@leonalicious When did you start seeing this issue? Have those pages changed in the last couple weeks?

**Comment by leonalicious** [comment]
hey, thank you for the prompt reply, the business logic of the `refine` part has not been updated since February so as the code.
I only found this error today, I read the changelog of #15517 and this caught my attention 
`Rework 1000 binding limit to only apply to initial DOM scan`

based on it, i notice if i am new to the page, and i go directly and select `Ship To`, the error triggered. However, if i go and play around with other Refine properties first, such as few rounds of Category and Attributes selection, and lastly go and select `Ship To`, everything just works fine. My gut feeling is telling me something is going on with that changes.

**Comment by choumx** [comment]
Thanks for the explanation. Based on the context, I'm going to downgrade to P1. I have a potential fix coming up and I'll make sure it gets into canary cut today for testing.

**Comment by leonalicious** [comment]
OMG, I might be wrong ! 

anyway, looking forward to the solution, please get us updated on this. Thx in advanced !

**Comment by leonalicious** [comment]
![image](https://user-images.githubusercontent.com/4065175/41349786-94695024-6f43-11e8-91ff-da596dd27467.png)
![image](https://user-images.githubusercontent.com/4065175/41349823-ae1ec26a-6f43-11e8-93a5-a1cfa10864b9.png)
 
are there any ways we might get notified with this also ?

**Comment by choumx** [comment]
This may help: https://www.ampproject.org/docs/reference/components/amp-analytics#error-trigger

**Comment by choumx** [comment]
What did you mean by "I might be wrong"?

**Comment by leonalicious** [comment]
There are things I don't know , so I might be wrong with my wild understanding on the changes . You know better for sure.
