### ISSUE TITLE
I want to get the height of the element。

### ISSUE THREAD

**Issue by 340236524** [ampproject/amphtml#16009]
I have tried many ways to get the height of elements, but always continue to integrate / Travis Ci/PR - Travis CI construction failed.

**Comment by lannka** [comment]
Can you provide a link to those failures?

**Comment by 340236524** [comment]
I want to get the height of the current element after the element is loaded, but amp seems to be limiting this way.

**Comment by choumx** [comment]
How/where are you measuring the element? From a PWA or another AMP component? 

Do you have a link to a sample reproduction that we can inspect?

**Comment by 340236524** [comment]
I want to get the height of rendered elements, and then I can judge.

for example
if（document.querySelector('.view-more-text').clientWidth  <= 150）{ }
else { }；

This way of reflux is forbidden, but I do need it， I hope you can help me.

**Comment by lannka** [comment]
I see, you hit our presubmit check. No worry, you can still send out the PR, and we can take a look if the use of clientWidth is legitimate for an exemption.

**Comment by choumx** [comment]
Closing. Let's follow up on your PR instead: #16139
