### ISSUE TITLE
[amp-animation] `animation` attribute does not work with subtargets

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#16015]
Problem: `subtargets` are not applied when another animation is referenced.

For example:

```
<amp-animation layout="nodisplay" id="myAnimation">
<script type="application/json">
{
  "animation": "myOtherAnimation",
  "subtargets": [
    {
      "selector": ":nth-child(2n+1)",
      "--scale": "1.5"
    }
  ]
}
</script>
</amp-animation>
  
  <amp-animation layout="nodisplay" id="myOtherAnimation">
<script type="application/json">
{
  "--scale": "0.5",
  "selector": ".target",
  "duration": "1s",
  "keyframes": {"transform": "scale(var(--scale))"},
  "fill": "forwards"
}
</script>
</amp-animation>
```

https://jsbin.com/jixubesinu/edit?html,output

**Comment by ericlindley-g** [comment]
Side-note: @aghassemi  Do we have a good category for animation-related items? Should we start a new one?

**Comment by aghassemi** [comment]
for now presentation works would be nice to have more labels though. cc @adelinamart since based on what I know adding new labels break some automation code.

**Comment by adelinamart** [comment]
If you use 'Category: ' format should be fine. I will advise not to have too many labels though and try to group under bigger categories.
