### ISSUE TITLE
Exempt non-regular contributors from the burden of paying off technical debt (e.g. the new JSDoc requirements)

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#16024]
Contributions from non-core contributors should be exempt from our new "pay the technical debt for changed files" rules. It is causing a lot of friction in getting their PRs merged and non-AMP core members should not be responsible to fix our technical debt just because they touched a particular file.

- We already know the author
- GitHub has REST API to get members of a list
- We should exclude PRs from anyone who is not inside https://github.com/orgs/ampproject/teams/google or maybe even https://github.com/orgs/ampproject/teams/runtime

**Comment by rsimha** [comment]
Thanks for filing this. I completely agree that non-core team members shouldn't be saddled with paying off our technical debt.

**Comment by mrjoro** [comment]
I'd lean against using a list of members of a particular company or a particular sub-part of the project as the set of people who these rules should apply to.

It looks like this issue is trying to address a couple of points:
- Those who are responsible for the technical debt on the project (i.e. long term contributors) should pay it.
- We want to make it easy for new contributors to contribute without being forced to pay some of the long term technical debt.

The "master mergers" list seems like the list that will best capture this, as we generally add people to "master mergers" once they've gotten a few PRs in and demonstrated an understanding of the code base.

My sense is that the main people missing from this list that we might want to include are contributors who have committed to being long-term contributors to AMP (typically because their employer is paying them to do so) but who do not yet have sufficient experience in AMP to warrant being on the "master mergers" list.  We can handle these cases more manually, with the expectation from their TL/reviewers that handling this debt is part of their onboarding.

**Comment by kristoferbaxter** [comment]
The core issue here could be described as a conflict between development velocity and code cleanliness/maintenance. Ideal answers normally do not lie at either end of this spectrum, but satisfy most of the underlying desires of both positions.

### ESLint and JSDoc requirements are reported as warnings

As a result, there are a relatively high number of hidden issues in the current master branch with no clear path to resolving the items they are flagging. As a maintainer this makes consistency of the code less optimal, and reduces the likelyhood codemods or similar will work as expected.

Additionally, as a new contributor the patterns are not cleanly enforced across the codebase making it less clear what pathway should be used to solve a problem.

### Newly converted warnings to errors reduce development velocity

When new rules are introduced as errors, the impact to velocity is significant. Breaking builds for new rules should be considered a last resort – especially for ongoing PRs that started before the rule was introduced.

### Given the desires, is there a pattern or process that can assist?

Believe there is, with incremental automatic conversion of newly introduced warnings to errors.
#### New Rule is added to codebase, as a warning.
- Submitter for the new rule is now the owner of the rule.
- The rule owner has 30 days to remove all warning instances.
- Frequent contributors in specific subsections (for instance @aghassemi in UI) would be expected to assist when there are questions or implementation concerns for a specific component.
#### Rule is automatically converted to an error 30 days after introduction
- Rule will now break master builds when the error is encountered
- Rule Owner is responsible for being "on-call" to assist with breakages during conversion

**Comment by rsimha** [comment]
> - Submitter for the new rule is now the owner of the rule.
> - The rule owner has 30 days to remove all warning instances.

@kristoferbaxter The intent has always been to move newly added rules from warning mode to error mode once a large enough percentage of violations have been fixed.

However, it is often times infeasible for one person to fix all instances in which a rule is violated. For example, the rule that requires that our JSDoc be complete and correct (~800 instances left, down from ~1600 originally), or the rule that requires all tests to account for the errors encountered during execution (~250 instances left, down from ~800 originally).

**Comment by kristoferbaxter** [comment]
> @kristoferbaxter The intent has always been to move newly added rules from warning mode to error mode once a large enough percentage of violations have been fixed.

The danger here is without a timeline, the warnings persist for a very long time and the unintended patterns can get repeated without awareness.

> However, it is often times infeasible for one person to fix all instances in which a rule is violated. For example, the rule that requires that our JSDoc be complete and correct (~400 instances left, down from ~1600 originally), or the rule that requires all tests to account for the errors encountered during execution (~350 instances left, down from ~800 originally).

Makes complete sense, however without something to push forward the initiative it's easy for these larger changes to fall by the wayside. An owner doesn't necessarily need to change all the places the error is occuring, but can work with authors who frequently contribute to an area to ensure they are covering the issues within the thirty day window.

**Comment by rsimha** [comment]
> Makes complete sense, however without something to push forward the initiative it's easy for these larger changes to fall by the wayside.

There is a mechanism in place to push things forward. When checks are run on PR and `master` builds, you're right that numerous warnings are seen. However, if a PR were to modify a file today, the warnings in that file are surfaced as errors. This way, as more files are touched, more rule violations are fixed, and more technical debt is paid off.

The purpose of this discussion is to lift the "fix while you edit" burden off of those who are occasional contributors. Hope this makes sense.

**Comment by aghassemi** [comment]
For new rules that impact a small subset of code, I agree the rule owner should do the refactoring. 
For rules that impact a larger surface and infeasible for rule owner to do,  "fix while you edit" is a decent option but it has its drawbacks. Aside from the work needed to put make sure burden doesn't fall on non-regular contributions, it makes code reviewers harder as well. Recent PRs have been a mix of unrelated refactoring and actual changes instead of self-containing.

What we did for the initial type-check, which works out over the long-run, was having a `flag` per extension that disabled the new rule, then we were incentivized and planned to fix each extension and remove the flag until they were all done. Maybe we can take a similar approach moving forward?

**Comment by rsimha** [comment]
I've removed all strict lint checks. `gulp lint` will simply use the settings in `.eslintrc`.

**Comment by prateekbh** [comment]
#16377 fixes all the jsDocs error, and re-enables the checks to errors.
