### ISSUE TITLE
amp-carousel: support `randomize` attribute

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#16026]
- Other names: `shuffle` ? 
- Distribution should be uniform
- Knuth algorithm instead of brute force should be used.

Rational behind the feature:
- UX data shows first few items in the carousel ( and by large the first item ) gets the most views. There are many scenarios where publisher may want to shuffle their carousel to get equal views across different slides to overcome this user bias.

/cc @ericlindley-g  @philkrie

**Comment by aghassemi** [comment]
thoughts for carousel 2? @nainar @andrewwatterson

**Comment by aurbanczik** [comment]
Is there a possibility to randomise the image order in amp-carousel ?
Thank you !
