### ISSUE TITLE
Problem of merge request

### ISSUE THREAD

**Issue by 340236524** [ampproject/amphtml#16038]
I asked for a merger, but there was a problem. The following error is not my code. Now I need your help.
![image](https://user-images.githubusercontent.com/35321877/41401924-9bdaed26-6ff3-11e8-91fa-8d7face77c76.png)

**Comment by jpettitt** [comment]
Looks like a test flake, what is the PR number?

**Comment by 340236524** [comment]
Swallowing more than 78KB, but I wrote very little code. I need your help now.
![image](https://user-images.githubusercontent.com/35321877/41575609-e81cc5d6-73b5-11e8-9233-65cb42999bd3.png)

**Comment by 340236524** [comment]
Swallowing more than 78KB, but I wrote very little code. I need your help now.
![image](https://user-images.githubusercontent.com/35321877/41575786-a963a3f4-73b6-11e8-8ca2-791a5ca734a8.png)
