### ISSUE TITLE
GDPR Geolocation-based consent flow

### ISSUE THREAD

**Issue by MarcellusMusic** [ampproject/amphtml#16034]
## What's the issue?
Geolocation-based consent message displaying on both EU & US browsers rather than only EU.

## How do we reproduce the issue?

1. Append custom country codes to the url:

- EU: https://marcelluslong.com/amp/#amp-geo=de

- non-EU: https://marcelluslong.com/amp/#amp-geo=us

HTML: http://jsbin.com/cixoruliko/edit?html,output

## What browsers are affected?

Safari, Chrome, and Firefox.

## Which AMP version is affected?

Version 1528841168349

**Comment by zhouyx** [comment]
Hi @MarcellusMusic Thank you for filing the issue.

This is not a bug. Please note that `#amp-geo=xxx` only works in testing environment. To see the difference, please opt into our dev-channel or use an vpn service. Thank you!
