### ISSUE TITLE
Error: "Cannot read property 'create' of undefined"

### ISSUE THREAD

**Issue by keithwrightbos** [ampproject/amphtml#16052]
Steps to reproduce:

- emulate mobile and go to page that include amp-ad fast fetch network that returns AMP creative which is preferentially rendered (e.g. https://m-wikihow-com.cdn.ampproject.org/v/s/m.wikihow.com/Delete-Messages-on-Facebook-Messenger?amp=1&amp_js_v=0.1)
- console log will report the following error although there does not appear to be a breakage in terms of creative interaction (can still click and relevant pings fire).

Uncaught TypeError: Cannot read property 'create' of undefined
    at new tj (v0.js:42)
    at new Af (document-register-element.node.js:294)
    at document-register-element.node.js:284
    at Wb (document-register-element.node.js:291)
    at Ql (amp-img.js:152)
    at Il.f.installExtensionsInChildWindow (vsync-impl.js:438)
    at friendly-iframe-embed.js:209

**Comment by keithwrightbos** [comment]
Not sure I'm the best person for this issue given its likely a low-level AMP core problem and perhaps related to https://github.com/ampproject/amphtml/issues/15759?

**Comment by dev-drprasad** [comment]
same problem

**Comment by nikse** [comment]
I'm still seeing this issue constantly in a lot of my articles. could it be affecting ad views?

urls: 
https://www.inverse.com/amp/article/49479-why-do-elephants-have-wrinkled-cracked-skin
https://www.google.com/amp/s/www.inverse.com/amp/article/49479-why-do-elephants-have-wrinkled-cracked-skin

<img width="1196" alt="screen shot 2018-10-02 at 1 42 40 pm" src="https://user-images.githubusercontent.com/1050982/46366451-15798d80-c649-11e8-9212-ca8979470520.png">

**Comment by jridgewell** [comment]
@nikse: It won't affect views. The error in this case is because a polyfill is trying to re-polyfill, so when it fails it continues to be ok.

**Comment by nikse** [comment]
Interesting, thanks for the quick response. We've actually noticed an ad fill issue since early september and digging in to everything we can to see what the issue could possibly be, which led me here. Unfortunately it is proving to be extremely difficult to figure out what is happening. I've tried manually looking at the ad responses but can't see anything. Any advice? Thought this issue might be causing some problems, but I guess not

**Comment by jridgewell** [comment]
Do you have a reproduction page? I'm not able to look into why ads don't fill, but I can investigate up to the point where AMP decides to inject the iframe. After that, it's up to the bidding process and normal 3p ads code.

**Comment by nikse** [comment]
Awesome thank you! It really seems to be happening on any of our amp article pages, like this one

direct link: https://www.inverse.com/amp/article/49498-kyrie-irving-flat-earth-apology-education
google cache link: https://www.google.com/amp/s/www.inverse.com/amp/article/49498-kyrie-irving-flat-earth-apology-education

**Comment by jridgewell** [comment]
Chrome? Safari? iOS?

**Comment by nikse** [comment]
sorry about that. i am seeing this in chrome, either emulating an iphone or just loading up the non google cache link in desktop mode

Google Chrome is up to date
Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by jridgewell** [comment]
Ok, so `layoutCallback` is being called appropriately. But, when it tries to render the iframe, it's apparently already `isCollapsed`. Can you file a new issue and tag @lannka?

**Comment by nikse** [comment]
yup! thanks a lot
