### ISSUE TITLE
🌸 Cherry pick request for #16043 into #16025 (Pending)

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#16050]
Issue #16043
PR #16048
Release Issue #16025
Target release: 1528909142235 (canary)
Build: https://travis-ci.org/ampproject/amphtml/builds/392406046

# Reasons
#16043 is a regression between current prod (1528391646530) and current pending canary (1528909142235) which prevents ads from loading inside PWAs

**Comment by cramforce** [comment]
Approved.

This isn't really a P0. It just must be fixed before the canary gets released.

**Comment by danielrozenberg** [comment]
To be fair I marked it as P1, @adelinamart wanted it as a P0 :)

**Comment by adelinamart** [comment]
It needed to be solved based on the P0 guidelines, so it's P0 :)
