### ISSUE TITLE
AMP Stories: Publisher Served Ad CTA button hidden in Firefox

### ISSUE THREAD

**Issue by AutadeJS** [ampproject/amphtml#16064]
## What's the issue?
In AMP stories, the CTA button in Publisher Served Ad doesn't display in Firefox. 

## How do we reproduce the issue?
Check this in latest version of Firefox:
https://ampbyexample.com/stories/monetization/publisher_served/preview/embed/
In this AMP story example, look for ad. You won't see CTA button in the ad, while you'll see one when you check on Chrome and Edge.

**Comment by newmuis** [comment]
Thanks for the report @AutadeJS!  I'll take a look.

/cc @calebcordry

**Comment by newmuis** [comment]
Looks like somehow the transition isn't happening in Firefox.

**Comment by calebcordry** [comment]
Did some digging, this has to do with differences in how browsers handle animations on styles set with `!important`.  Apparently, in Chrome styles defined in `@keyframes` will take precedence over `!important` but in Firefox they will not. I working on a solution.

**Comment by calebcordry** [comment]
closed by #16103. Let me know if you are still seeing this issue once this fix hits production. Thanks!
