### ISSUE TITLE
Non-visible amp-story-pages not pushed far enough offscreen

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#16067]
The pages that are not the current page, next page, or previous page should all be off-screen.  We do this by pushing them to the extreme left/right of the viewport.

(1) They are not pushed far enough off the screen for sufficiently wide screens (which I think can be fixed by using viewport units instead of percentages):
![screen shot 2018-06-15 at 11 13 32 am](https://user-images.githubusercontent.com/1651960/41475642-576af16e-708d-11e8-87fe-b87b01a9054f.png)

(2) I think they should be above/below the viewport, to capitalize on the runtime's resource loading.  I thought this was the case, but I think this may have changed.

**Comment by sanjsanj** [comment]
Hey @newmuis !  Is this ticket available to be picked up please?
I think I could probably do the CSS part anyway!

**Comment by newmuis** [comment]
Yes, absolutely!  Thanks @sanjsanj!

**Comment by sanjsanj** [comment]
@newmuis Awesome!  Am I updating v 0.1 and 1.0 of the CSS or just 1.0?

**Comment by newmuis** [comment]
If the fix is simple, I think we can update 0.1 and 1.0; if it seems like it's complex, I think it's okay to just do 1.0.
