### ISSUE TITLE
Create /version CDN endpoint to replace /version.txt

### ISSUE THREAD

**Issue by bjalford** [ampproject/amphtml#16068]
Canary version: 001528841168349
live version: 011528841168349
https://cdn.ampproject.org/v0/version.txt:   1528841168349

AMP-Optimizer gets that v0 value and pads with 0 but not with the 1?

The means optimizer is always using canary.

**Comment by andreban** [comment]
The AMP version endpoint (https://cdn.ampproject.org/v0/version.txt) is returning `1528841168349`. On AMP toolbox, we pad with zeros up to 15 chars, generating `001528841168349 `.

The current AMP runtime used by the AMP Cache is: `https://cdn.ampproject.org/rtv/011528841168349/v0.js`

It seems that the version endpoint is returning the wrong version.

This also has the side effect that, when 001528841168349 is used, it sets canary: 1 on the `AMP_CONFIG`, which is triggering #15834.

**Comment by sebastianbenz** [comment]
//cc @Gregable @honeybadgerdontcare

**Comment by honeybadgerdontcare** [comment]
@erwinmombay

**Comment by lannka** [comment]
The first 2 digits are used to indicate the stage: canary, prod, with different experiment flags.

Depend on what you want to do with the version ID, you may or may not these digits.

@erwinmombay

**Comment by sebastianbenz** [comment]
Context is this API: https://github.com/ampproject/amp-toolbox/tree/master/runtime-version

which is no longer working correctly. Have we got a list somewhere of the different flags? 

So the correct way to determine prod and canary is to pad the value returned by: https://cdn.ampproject.org/v0/version.txt with:

* **00**1529106593171 for canary
* **01**1529106593171 for prod

Is that correct?

**Comment by jridgewell** [comment]
> can correct me if im wrong, but i think we're trying to create a new endpoint that actually exposes the current prod/canary versions to be used by our error reporting server.

Yes. I'll be designing a `/version` endpoint to return the current RTV version.

> 001529106593171 for canary
011529106593171 for prod

That is true by default, but the prefixes are arbitrary and **do** change. We just released a production build that's prefixed by `03`.

> The AMP version endpoint (https://cdn.ampproject.org/v0/version.txt) is returning 1528841168349. On AMP toolbox, we pad with zeros up to 15 chars, generating 001528841168349.

`https://cdn.ampproject.org/v0/version.txt` is not an official endpoint. It's there just as a byproduct of the build. Further, the version it uses is the AMP version, which is not the RTV version that the CDN uses. RTVs are the arbitrarily prefixed versions.

**Comment by Gregable** [comment]
Closing bug as this is an AMP Cache specific. That project is tracking at `b/113541052`
