### ISSUE TITLE
Analytics calls after pageload event

### ISSUE THREAD

**Issue by Mohit-3** [ampproject/amphtml#16065]
I am trying to execute analytics call post pageload event on AMP pages. AMP analytics makes image pixel call which are page load blocking and intermittently taking longer time. This time gets add up in pageload time of AMP page. 

I do not see load anywhere in trigger options, Available options are....

triggers": {
      "trackPageview": {
        "on": "visible",  _`(on (required) The event to listen for. Valid values are render-start, ini-load, click, scroll, timer, visible, hidden, user-error, access-*, and video-*)`_
        "request": "pageview"
      },

**Comment by lannka** [comment]
`on: "visible"` is what you probably want. 

feel free to reopen, if it does not work for you case.

**Comment by Mohit-3** [comment]
I have tried on: "visible", but pixels always fire before page load and blocks pageload event..

**Comment by Mohit-3** [comment]
@lannka , I am not able to reopen this thread, Can you please do it on my behalf. 

I have already tried on: "visible", but pixels always fire before page load and blocks pageload event..

**Comment by zhouyx** [comment]
Reopen per @Mohit-3 request

Close #16307

**Comment by zhouyx** [comment]
Copied my comment from #16307 

Trying to understand here. Are you using the <amp-pixel> component or the <amp-analytics> component? And when you mentioned "pixels always fire before page load and blocks pageload event." where did you get the page load event?

**Comment by Mohit-3** [comment]
@zhouyx 

I am using below code on amp page for custom pixel. 

<amp-analytics>
<script type="application/json">
{
  "requests": {
    "pageview": "URL......"
  },
  "triggers": {
    "trackPageview": {
      "on": "visible",
      "request": "pageview"
    }
  },
  "transport": {
      "beacon": false,
      "xhrpost": false,
      "image": true
  }
}
</script>
</amp-analytics>

Other than this I have segment and GA pixels also on page. All these pixels intermittently fires before page load. Attached screenshot shows the same.
![pixel image](https://user-images.githubusercontent.com/40291982/42312848-f1b931f0-805e-11e8-9722-d3c5ab41fba8.jpg)

I monitor the page load time in chrome dev tool. I have Newrelic configured on application which also provides page load time and individual call details on a page.

**Comment by zhouyx** [comment]
@Mohit-3 Thank you for the information. 

From what I understand, this is due to the behavior of the browser provided load event. It fires when all dependent resources have finished loading. This is different for page viewable. In AMP's case, pageview can indeed happens before page load event. Meanwhile user can actually interact with the page before page load event, because most logics are not render blocking. 

As said, AMP provides `pageview` event instead of `load` event, because in this case `pageview` can describe the event better, we believe the important metric is when the user start consuming content, instead of finishing loading of all dependent resources in background.

Could you let us know if `pageview` events work for you? And what is your use case?  Thank you. 

to @lannka who has more knowledge on the `load` event

**Comment by Mohit-3** [comment]
@zhouyx , @lannka 

Thank you for your time.

My end goal is to improve the performance of AMP pages. I have AMP pages for google adwards and those are taking around 3 seconds to load. Most of the time is taken by pixels and that is the reason I want to move them post pageload.

I am using Newrelic to monitor the performance of application and it captures pageload time (does not capture pageview). Is there a way to fire pixels post pageload always in AMP.

**Comment by lannka** [comment]
@Mohit-3 sorry for my mis-understanding.

Are you using to amp-analytics, one with your in-house solution and one with Newrelic?

In that case, are you able to turn your in-house solution to use "transport: xhr"? Which should not be blocking the pageload event. 

Alternatively, you could put `${pageLoadTime}` macro in your in-house analytics request, so the request is sent after the pageload.

**Comment by Mohit-3** [comment]
Thank you @lannka and @zhouyx for your time. 

Yes I am using amp-analytics for segment.io, in-house pixel and Newrelic?

In actual, my in house pixel is a post ajax call but for some reason it does not work if I set  "transport": { "xhrpost": true }. Any help would be appreciated here.

${pageLoadTime} macro has worked for me and thank you so much for suggesting this. I would prefer to use "transport: xhr" as it will fix the issue with segment.io also.

**Comment by lannka** [comment]
Hi @Mohit-3 can you clarify what did not work for `xhrpost`? Did it still block the pageload event? Can you share a demo page that reproduce the issue?

**Comment by Mohit-3** [comment]
This problem is resolved now. I have converted in house pixel to xhrpost and moved segment.io to post pageload. Thank you so much @lannka and @zhouyx for your help. I am closing this ticket
