### ISSUE TITLE
Fix all ads & analytics tests that were silently passing

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#16076]
To address #14406 
Let's go through the tests the ads & analytics team owns, and fix silently fail tests.
Please add tests that's missing here. 

- [x] cid related tests
- [ ] amp-ad related tests
- [ ] amp-analytics related tests
- [ ] amp-story-auto-ads related tests
- [x] amp-sticky-ad related tests
- [x] amp-consent related tests
- [ ] InOb/PosOb related tests

Please reply to this thread if you start work on any of them.

**Comment by lannka** [comment]
I'm taking the cid related tests

**Comment by zhouyx** [comment]
Will work on this after #16916 is merged

**Comment by zhouyx** [comment]
Can be closed by #17213
