### ISSUE TITLE
🌸 Cherry pick request for 16081 into 15992 (Approved)

### ISSUE THREAD

**Issue by bradfrizzell** [ampproject/amphtml#16083]
*GitHub issue your cherry pick is fixing:*

Issue #16081

*PR that you are requesting a cherry pick for:*
PR #16077

*[Type: Release](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) issue for the release build you are requesting a cherry pick into:*

Release Issue #15992

*Is this request for a cherry pick into a canary or a production release?*
*(If you are requesting a cherry pick into a production release you may need to file a separate cherry pick request for the current canary as well.  See the [cherry pick documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-picks).)*

Unversioned Prod - this only affects canonical traffic so only need to cherry pick into unversioned prod. 

*Why does this issue meet the [cherry pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?  Be specific.*

This issue is impacting 100% of Canonical Doubleclick Fast Fetch traffic.

**Comment by bradfrizzell** [comment]
@keithwrightbos @jeffkaufman

**Comment by cramforce** [comment]
Approved.

**Comment by bradfrizzell** [comment]
@adelinamart

**Comment by adelinamart** [comment]
this is done
