### ISSUE TITLE
google-document-embed

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#16090]
is `google-document-embed` operational?

https://github.com/ampproject/amphtml/blob/master/examples/google-document-embed.amp.html

not seeing an experiment activation option here:

https://cdn.ampproject.org/experiments.html

the lib is accessible:

https://cdn.ampproject.org/v0/amp-google-document-embed-0.1.js

but we see this error in Chrome

Refused to execute script from 'https://cdn.ampproject.org/rtv/001529106593171/v0/amp-google-document-embed-0.1.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

/jay gray

**Comment by aghassemi** [comment]
@jaygray0919 It is on DevChannel. Will be in prod ( still under experimental flag ) later this week. 

To see a demo:
- enable DevChannel here: https://cdn.ampproject.org/experiments.html
- visit: http://amphtml-nightly.herokuapp.com/examples/google-document-embed.amp.html
- Toggle Dev Console, do `AMP.toggleExperiment('amp-google-document-embed', true);` and reload the page

**Comment by jaygray0919** [comment]
TY
