### ISSUE TITLE
video: Autoplay pauses too early

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#16108]
autoplaying videos now seem to pause as soon as less than half is out of viewport, they used to pause when more than half was out of viewport. Setting to P1 since a regression.

/to @alanorozco

**Comment by aghassemi** [comment]
(would be nice to get the fix in this week's canary)

**Comment by alanorozco** [comment]
Quick regression check shows that this has been the behavior for a while, so no regression found. PR to reduce required visibility ratio to 50%.

**Comment by aghassemi** [comment]
lowers to P3, I was wrong.

@spacedino What do you think about changing the `autoplay` threshold to `50%` instead of current `70%?` Best place to view the current behavior is www.tasty.co. It just pauses too early in my opinion and starts too late.
