### ISSUE TITLE
Not possible to test amp-geo in dev mode

### ISSUE THREAD

**Issue by mpaw** [ampproject/amphtml#16117]
## What's the issue?

According to the `Debugging` section of the `amp-geo` documentation here:
https://www.ampproject.org/docs/reference/components/amp-geo

You should be able to spoof the region by setting `#amp-geo=XX`. This will only work in dev mode or if your hostname is `localhost`. I am running the amp page locally and it will not go into dev mode when using `localhost`. Is there any other way to trigger dev mode locally so that `amp-geo` can be tested?

![image](https://user-images.githubusercontent.com/5834637/41558182-ff0022a0-730d-11e8-91ce-d91d6d49f887.png)

## How do we reproduce the issue?

1. Run AMP page on `localhost` port `80` (or any other port)
2. Add `#amp-geo=XX` with the two letter country code
3. The page does not pick up the geo override

## What browsers are affected?

Tested on Chrome but shouldn't matter

## Which AMP version is affected?

`1529106593171`

**Comment by mpaw** [comment]
I was able to test it by turning on the `dev-channel`. Using `localhost` as your hostname when the `dev-channel` is enabled makes no difference. It still worked on another domain I have pointing to `localhost`

The documentation here should probably be updated
> For security reasons, to prevent sharing of geo-spoofing urls, this feature is only available to users who have enabled the Dev Channel or who are testing locally (i.e., the hostname is localhost).

As just setting your hostname to `localhost` does not work.

**Comment by choumx** [comment]
Try adding `#development=1` to the URL.

**Comment by jpettitt** [comment]
Documentation bug - In this context `localhost` it means that the AMP js files are being served from localhost via `gulp serve`. I'll submit a PR to update the doc.  In other use cases, including content served from `localhost` the `dev-channel` approach will work.
