### ISSUE TITLE
♻️Opting out of url-encoding should be better.

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#16126]
Instead of whitelisting macros that should not be encoded, we should have a more sophisticated mechanism in `amp-analytics` that keeps base urls from being encoded.

Related to #15966 

Fix this during fix it 💪

**Comment by calebcordry** [comment]
Upon further investigation it appears this is a very hard problem. The use case looks something like this:
```js
{
  requests: {
    base: 'ANCESTOR_ORIGIN'
  },
  triggers: {
    on: 'foo',
    request: 'base'
  }
```
The idea is that a user wants to send a ping to a dynamic domain. This is a problem without the whitelist because something like `https://www.example.com` will get `encodeURIComponent` called on it resulting in `https%3A%2F%2Fwww.example.com`

My original thought was that we could check for various protocols at the beginning of the string and just never encode them. This almost works except for if we have a url like `https://example.com/foo/bar/` we should not encode any of the `/`. 

Right now we have no mechanism to tell us where these forward slashes come from. We could potentially introduce something into the analytics config in the future to handle this case, but it would be a large change.

**Comment by zhouyx** [comment]
Any update on this?

**Comment by calebcordry** [comment]
This is solved by @jonathantyng-amp 's work 🎉
