### ISSUE TITLE
amp-fx="fade-in fly-in-bottom" invalid, but showed as a valid example

### ISSUE THREAD

**Issue by filipecavalc** [ampproject/amphtml#16121]
## What's the issue?

![image](https://user-images.githubusercontent.com/15673929/41562368-b804be00-7322-11e8-8891-11c15f9438d8.png)

![image](https://user-images.githubusercontent.com/15673929/41562412-e15ec804-7322-11e8-97e9-76cdde4fef23.png)

## How do we reproduce the issue?

https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-fx-collection%2Fsource%2F check the code and error here.

## Which AMP version is affected?

latest version i think

**Comment by nainar** [comment]
Hi @filipecavalc, 

In the case of `amp-fx="fly-in-*"` the feature hasn't hit production yet, will probably hit prod in a few weeks (available under experimental on production though.)

Seems like validation changes for fade-in/fade-in-scroll haven't landed yet. Checked https://validator.ampproject.org/ and the validator isn't caught up there yet.

**Comment by niveshameex** [comment]
yes
