### ISSUE TITLE
Disable / fix flaky visual tests

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#16133]
See https://percy.io/ampproject/amphtml/builds/797668 for example

Of the ~20 failures, several are likely due to components with dynamic content. They should either be fixed or disabled.

See https://percy.io/ampproject/amphtml for full list of builds

**Comment by danielrozenberg** [comment]
More flakes from @aghassemi in #16228:
https://percy.io/ampproject/amphtml/builds/809266
https://percy.io/ampproject/amphtml/builds/808654
https://percy.io/ampproject/amphtml/builds/809472

**Comment by danielrozenberg** [comment]
I'd like to hold on with this until `--puppeteer` (#16390) becomes the default, so as not to have to maintain two versions of the code
