### ISSUE TITLE
amp-accordion does not allow media attribute

### ISSUE THREAD

**Issue by haensl** [ampproject/amphtml#16143]
## What's the issue?

AMP documentation specifies

> All AMP elements support the media attribute. 

https://www.ampproject.org/docs/reference/common_attributes#media

However, AMP validation complains about the `media` attribute not being allowed in combination with `amp-accordion` and refers to the `amp-accordion` documentation. This documentation unfortunately contains no mention of the `media` attribute not being allowed with this tag.

## How do we reproduce the issue?

I created a JSFiddle for the basic case, but it does not show validation messages. To see the validation error, copy the markup from the fiddle into a HTML file and serve it while appending `#development=1` to the URL.

https://jsfiddle.net/9rfbcwv3/3/

![screen shot 2018-06-19 at 13 50 22](https://user-images.githubusercontent.com/12875760/41595616-c7b0a828-73c7-11e8-85e6-5f54a303908e.png)

## What browsers are affected?

Tested in Chrome Version 67.0.3396.87 (Official Build) (64-bit) and Safari Version 11.1.1 (13605.2.8) on macOS High Sierra Version 10.13.5 (17F77).

## Which AMP version is affected?

Version 1529106593171

**Comment by AcidRaZor** [comment]
I see where the confusion comes in, but if you look at the amp-accordion documentation (and validation rules) you will see that "media" isn't a common attribute. If you look around the documentation even further, you will notice online certain media components has access to that attribute as well. To me this isn't a functionality issue, more of a documentation issue.

However, as a solution, don't forget the power of CSS and the normal "class" attribute. Assign a class to your amp-accordion, and then:

```
.myclass { width:50% }
@media (max-width:650px;){
     .myclass { width:100% }
}
```

The above should apply a width of 50% if the max-width isn't 650, else 100% width is applied.

**Comment by haensl** [comment]
The problem is that I am unable to hide/not render the accordion. Since it has `display: block !important;` on it. But I need to hide it above a certain width.

**Comment by bpaduch** [comment]
Yes, it appears the documentation is incorrect and that amp-accordion doesn't support the `media` attribute.  If a component's validator includes `extended-amp-global` attributes, then it supports media.  It doesn't look like amp-accordion every support `media` queries and I don't expect it will.

@cathyxz - do you know of a solution to @haensl's issue?

In the meantime, I'll correct the docs.

**Comment by aghassemi** [comment]
Let's fix the component to allow `media` instead of documentation fix. no reasons it should't support it, just a bug.

**Comment by cathyxz** [comment]
Media queries are supported at the `custom-element` level, which means that theoretically `amp-accordion` should be able to support this behaviour fairly easily. It might just be an oversight in the validation spec of amp-accordion.

**Comment by cathyxz** [comment]
I see that a race condition occurred while I was typing, but yes--it's a bug and we can fix it.

**Comment by haensl** [comment]
The media query indeed seems to work, but validation does not.
