### ISSUE TITLE
Support for IAB Framework & oil.js as CMP

### ISSUE THREAD

**Issue by Waschnick** [ampproject/amphtml#16140]
We are building a free and open source Consent Management Provider (CMP) called oil.js, you can find everything on Github: https://github.com/as-ideas/oil

We would like to integrate oil.js with AMP.

Is it possible to direclty use the purposes (not only block/no-block) from the [IAB Framework](http://advertisingconsent.eu/)?

**Comment by jasti** [comment]
Hey @CanardSauvage, yes, we welcome new CMP contributions that support the IAB implementation. @zhouyx @lannka to recommend eng design that integrates with amp-consent.

**Comment by zhouyx** [comment]
Hi @CanardSauvage. Thank you for bringing this up!

We are working on adding support for IAB implementation with the `<amp-consent>` component. This is one of the master features in our roadmap. 

The initial version of the design is for you to have something like 
```
<amp-consent type='oil'></amp-consent>
```
And the the CMP can customize its own UI, and consent collecting flow. AMP will provide APIs for you to handle storage.


A few questions I would love to hear feedback from you: 

1. How do you decide what vendors/purposes to ask for consent? Remotely or from client config?
2. Will you be supporting vendors that are not in the IAB vendor lists. For example publishers' in house iframes?
3. With your CMP `<amp-consent type='oil'>`, do you expect a publisher to retag their ad vendors that's within the IAB vendor lists?
4. What's your fallback strategy if the user reject or only partially accept consents?

**Comment by jasti** [comment]
@CanardSauvage, have you had a chance to look at @zhouyx's questions?  We are working on supporting the IAB implementation for all CMPs and want to make sure we consider your input. Thanks!

**Comment by jasti** [comment]
@Waschnick Quick ping about above.

**Comment by zhouyx** [comment]
Hello AMP has added support for CMP to integrate. Please refer to https://github.com/ampproject/amphtml/blob/master/extensions/amp-consent/integrating-consent.md for more information. And please let us know if there's any question. Thank you
