### ISSUE TITLE
Validator for "heights" rules

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#1616]
The new "heights" attribute is part of the `layout=responsive` ecosystem. It's developed in https://github.com/ampproject/amphtml/pull/1331

The rules are very similar to `sizes` attribute:
1. If `layout` is not specified and `heights` attribute is specified - implied layout is `responsive`
2. `heights` attribute can only be specified for elements with `layout=responsive` - input or implied
3. The format of the `heights` attribute is the same as `sizes` with a single exception that `%` are allowed as values (not sure we actually validate content of `sizes` attribute).

**Comment by rudygalfi** [comment]
@powdercloud Is this all done?

/cc @dvoytenko

**Comment by Gregable** [comment]
Not quite. It's available in the javascript messages, but has not rolled out to search carousel selection yet.

**Comment by powdercloud** [comment]
At this point quite sure it's out everywhere, so closing this issue.
