### ISSUE TITLE
Update the `copy-abe-visual-test-pages.sh` script to merge new ABE pages

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#16162]
Currently the script generates a copy-paste-able chunk of JSON that can be placed inside the `test/visual-diff/visual-tests` file, however the existing ABE tests might have more configuration changes (e.g., `{"flaky": true}` or `{"experiments": [...]}`) that we risk not noticing when generating a PR to add new ABE pages.

The script should ideally not replace those existing tests.

**Comment by rsimha** [comment]
Reference: https://github.com/ampproject/amphtml/pull/16158#issuecomment-398550793
