### ISSUE TITLE
amp-list refreshing again while clicking on any button outside the amp-list

### ISSUE THREAD

**Issue by ziyed** [ampproject/amphtml#16172]
## What's the issue?

I have developed an AMP site where i have used dynamic pagination on amp-list pulling data from endpoint. I have added multiple query string value on [src] of amp-list which is not same as src. I also have some other buttons and functionality outside the amp-list with different activities. The problem is that, while amp-list loaded its content first time and i have clicked on any other button outside the amp list, for example to show/hide a div the amp-list loading again due to [src] and it is trying to execute [src] link again though i have not request to change amp-list yet by clicking on pagination next button.

Here i have added a sample code from AMP example and added a button to show/hide a div. So for the very first time when amp-list content loaded and i clicked on the button outside the amp-list, amp-list content loaded again.

Sample Code link:  https://github.com/ziyed/amp-code/blob/master/index.html

I have multiple query string on amp-list [src] to manage my features and I need to stop amp-list content load again while click on any outside button of amp-list.

any suggestion please

## How do we reproduce the issue?

Here i am giving step-by-step instructions for reproducing the issue:

1. Run the code from my github account
2. while amp-list content fully loaded, click on **Show/Hide Div**
3. amp-list reload again though i did not click on next pagination button yet

## What browsers are affected?

All browsers

## Which AMP version is affected?

1529449959701

**Comment by aghassemi** [comment]
@ziyed On `setState` all expressions get reevaluated. You have `[src]` bound to `pageNumber` variable but there is no initial value for `pageNumber` so when it gets reevaluated it becomes null. Note that this issue does not happen after you go to the next page since at that point `pageNumber` has a value. 

Solution is to make sure `pageNumber` is initialized to the correct value in amp-state or check whether it is null or not in the `src` expression.

**Comment by ziyed** [comment]
Hi @aghassemi ,

Thank you for your comment.

I have updated pageNumber with a default value but still amp-list loading for the first time.

Yes, it will be ok when go to next page and i know that. This is also informed you that on my project I have lot more dynamic variable set to [src].

Is there any way not to load again for the first time or this is not possible on AMP yet?

Thanks,
Ziyed

**Comment by aghassemi** [comment]
@ziyed If you initial `src` == initial `[src]`, it won't refresh. So just change `src="https://ampbyexample.com/advanced/paged_list/search?page=1"`

Here is a sample of your code that works: https://codepen.io/aghassemi/pen/NzMNXw?editors=1000

**Comment by ziyed** [comment]
@aghassemi thanks for the reply,

I have fixed the problem. There was a problem in '/' but not in state variable. my project is now ok and working well. Thanks Ziyed
