### ISSUE TITLE
Support unquoted attribute value in viewport

### ISSUE THREAD

**Issue by meharald** [ampproject/amphtml#1618]
As indicated by the Chrome AMP verifier Version 1453851070468

works
\<meta name=viewport content="width=device-width,minimum-scale=1,initial-scale=1">

does not work
\<meta name=viewport content=width=device-width,minimum-scale=1,initial-scale=1>

**Comment by Gregable** [comment]
Agreed, we should fix this.

**Comment by rudygalfi** [comment]
@Gregable Any update on this?

**Comment by Gregable** [comment]
This has not been fixed.

**Comment by Gregable** [comment]
This is fixed.
