### ISSUE TITLE
Introduce a new experiment flag to disable web-animation polyfill if native is supported

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#16190]
Currently we install the web-animation polyfill regardless of native support because there might be features missing even in native implementations (https://github.com/ampproject/amphtml/pull/10412). 

With Safari coming on board, we should experiment with not installing the polyfill if native support is there and see how things turn out and work with native implementation folks to fix any compat issues.

@alancutter @addyosmani Do you know if there are spec tests that we can see how the [polyfill](https://github.com/web-animations/web-animations-js) vs Chrome vs Safari do with respect to implementing the spec?

/cc @kristoferbaxter @nainar

**Comment by aghassemi** [comment]
Few pointers: 
- https://bugs.webkit.org/show_bug.cgi?id=186518 List of missing features from Webkit's implementation
- Similar list for Blink: https://bugs.chromium.org/p/chromium/issues/list?can=2&q=%22Web+Animations%3A+Implement%22&colspec=ID+Pri+M+Stars+ReleaseBlock+Component+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=ids

**Comment by aghassemi** [comment]
we should lazily polyfill

**Comment by erwinmombay** [comment]
@ampproject/wg-performance this might not be feasible but might be possible to lazily load the polyfill. check with @alanorozco
