### ISSUE TITLE
Bookend does not support letters of European alphabet with accents

### ISSUE THREAD

**Issue by davidegiulietti** [ampproject/amphtml#16199]
## What's the issue?
In the bookend, the title of the story, shown on top, does not support the letter with accents (e.g. "á").

Briefly describe the bug/feature request.
To have it fixed for all the letters with accents, basically all the letters of the European alphabet.

## How do we reproduce the issue?
Please go to one of the following stories:
https://es.fifa.com/worldcup/visual-stories/rafa-marquez-y-una-historia-5-estrellas/
https://de.fifa.com/worldcup/visual-stories/spate-tore-ein-trend-in-russland/
https://fr.fifa.com/worldcup/visual-stories/buts-tardifs-et-decisifs-en-russie/

If this is a bug please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else.  Then provide step-by-step instructions for reproducing the issue:
Please go to one of the following stories:
https://es.fifa.com/worldcup/visual-stories/rafa-marquez-y-una-historia-5-estrellas/
https://de.fifa.com/worldcup/visual-stories/spate-tore-ein-trend-in-russland/
https://fr.fifa.com/worldcup/visual-stories/buts-tardifs-et-decisifs-en-russie/

1. Step 1 to reproduce
Please go to one of the following stories:
https://es.fifa.com/worldcup/visual-stories/rafa-marquez-y-una-historia-5-estrellas/
https://de.fifa.com/worldcup/visual-stories/spate-tore-ein-trend-in-russland/
https://fr.fifa.com/worldcup/visual-stories/buts-tardifs-et-decisifs-en-russie/

2. Step 2 to reproduce
Reach the bookend (it is shown in a mobile view only, not on desktop)

If this is a feature request you can use this section to point to a prototype/mockup that will help us understand the request.

## What browsers are affected?
All

All browsers? Some specific browser? What device type?
All

## Which AMP version is affected?
The current one

Is this a new issue? Or was it always broken? Paste your AMP version. You can find it in the browser dev tools.
No idea

![bug_letter_with_accent_amp](https://user-images.githubusercontent.com/40442252/41684916-927892f8-74e7-11e8-92c1-ac063aabc52f.png)

**Comment by Enriqe** [comment]
Sure, I'll take a look

**Comment by Enriqe** [comment]
@davidegiulietti I'm looking at the `jsonLd` story metadata in the stories that you linked, and I can see that in the `headline` title, the characters are already encoded incorrectly.

![image](https://user-images.githubusercontent.com/5449100/41688114-bc4704b8-74b8-11e8-9a71-06baa882bde5.png)


Can you verify that in the metadata section (found in the `<script type="application/ld+json">` tag under `<head>`) of your AMP Stories , the `headline` value has the right characters?

**Comment by davidegiulietti** [comment]
Hi @Enriqe, thanks for the analysis, I'll check internally with our developer and let you know. Davide
