### ISSUE TITLE
E2E testing infra

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#16198]
We should evaluate tools such as https://www.cypress.io/ and Selenium for proper E2E testing.

Currently our integration testing framework still relies on iframes inside Mocha and although they are closer to blackbox testing than our functional and unit test, they still lack ability to test in the viewer, in cache and the environment is not completely realistic due to the iframe.

/to @rsimha 
/cc @cathyxz @kristoferbaxter

**Comment by rsimha** [comment]
@esthkim is going to pick up this work.

**Comment by rsimha** [comment]
This can be closed out with thanks to @estherkim and @cvializ.
