### ISSUE TITLE
"-latest.js" alias depends on compilation order

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#16191]
Assuming we want to retain the current semantics of the `-latest.js` alias, we should prevent the scenario where:

```js
declareExtension('amp-foo', ['2.0', '1.0'], ...)
``` 

...results in `amp-foo-latest.js` is the same as `amp-foo-1.0.js`.

/to @rsimha

**Comment by choumx** [comment]
Addendum: When developing locally, the contents of `amp-foo-latest.js` depends on which code version was last rebundled. 

For example, run `gulp --extensions=amp-mustache`. Now, after serving...
- If you modify a file in amp-mustache/0.1/, then `amp-mustache-latest.js` contains 0.1.
- If you modify a file in amp-mustache/0.2/, then `amp-mustache-latest.js` contains 0.2.

**Comment by rsimha** [comment]
Fixed by #21190
