### ISSUE TITLE
Form attributes are being stripped in amp-mustache templates

### ISSUE THREAD

**Issue by bmadzar** [ampproject/amphtml#16215]
## What's the issue?

Similar to #15721 , the values of certain form-related attributes are getting stripped out when rendering `<amp-mustache>` templates:

- form[verify-xhr]
- span[visible-when-invalid]
- span[validation-for]

## How do we reproduce the issue?

Include a `<form>` in your amp-mustache template. Include the custom amp-form attributes of `verify-xhr` and amp-form validation using `visible-when-invalid` and `validation-for`.

`verify-xhr` seems to be stripped regardless of whether `custom-validation-reporting` is present or not.

## What browsers are affected?

Tested on Chrome 67 and Firefox 52.

## Which AMP version is affected?

Using (prod) AMP 1529449959701. The `verify-xhr` attribute used to work, though I cannot remember what AMP release we were using at the time. We've just added the validation messages so I'm not sure if they ever worked.

**Comment by aghassemi** [comment]
I don't see any of these in the purifier rules. Need to be added. (Note: `verify-xhr` has special rules and domain blacklist).

/to @cvializ
