### ISSUE TITLE
Serving non-personalized ads to all EEA users and personalized for rest are working?

### ISSUE THREAD

**Issue by zaletskyi** [ampproject/amphtml#16210]
Hi @zhouyx, 

How can I test if serving non-personalized ads to all EEA users and personalized for rest are working? 
Does it have to save something in local storage for EEA users?

  ```
<amp-geo layout="nodisplay">
    <script type="application/json">
      {
        "ISOCountryGroups": {
          "eea": ["at", "be", "bg", "cy", "cz", "de", "dk", "ee", "es", "fi", "fr", "gb", "gr", "hr", "hu", "ie", "is", "it", "li", "lt", "lu", "lv", "mt", "nl", "no", "pl", "pt", "ro", "se", "si", "sk"],
          "world": ["unknown"]
        }
      }
    </script>
  </amp-geo>

<amp-consent id="myUserConsent" layout="nodisplay">
  <script type="application/json">
     {
      "consents": {
        "eu-consent": {
          "promptIfUnknownForGeoGroup": "eea"
        }
      },

     "policy": {
      "default": {
        "waitFor": {
          "eu-consent": []
        },

        "timeout": {
          "seconds": 0,
          "fallbackAction": "reject"
        }
      }
     }
   }
  </script>
</amp-consent>

 <amp-sticky-ad layout="nodisplay">
        <amp-ad data-block-on-consent="default" data-npa-on-unknown-consent="true" width=320 height=50 type="adsense" data-ad-client="ca-pub-xxxxx" data-ad-slot=""></amp-ad>
</amp-sticky-ad>
```
Maybe you have any live example.

I read this article: https://support.google.com/dfp_premium/answer/7678538 But it looks like it has some errors. 

Thanks.

**Comment by zhouyx** [comment]
@zaletskyi For the config your provided. (serving non-personalized ads to all EEA users). AMP doesn't save the state in localStorage. We made this decision because we believe in this case, the choice is not made directly by user, and should not be saved. 

Unfortunately I don't believe we have a live example for "Serving non-personalized ads to all EEA users". cc @jasti

**Comment by jasti** [comment]
This was tested internally by the DoubleClick team. Could you please reach out to the DoubleClick support team to make sure it works as expected? CC @keithwrightbos

**Comment by zaletskyi** [comment]
Thank you @zhangsu @jasti

**Comment by zaletskyi** [comment]
Thank you But how I could check how auto reject consent for EEA users works? Cuz wit this code I didn't have anything saved in local storage.
