### ISSUE TITLE
Check for minimum node version in gulp

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1622]
We require node 4.0 or newer.

A problem might be that gulp might completely fail to start up. Not sure how to best handle that.

**Comment by erwinmombay** [comment]
@cramforce we could certainly add a post install script to run after npm install?

**Comment by cramforce** [comment]
Good idea. Or could package.json enforce it declaratively?

**Comment by jridgewell** [comment]
We can set `engines` in [package.json](https://docs.npmjs.com/files/package.json#engines)

**Comment by erwinmombay** [comment]
we do currently set engine requirement on package.json https://github.com/ampproject/amphtml/blob/master/package.json#L7

**Comment by jridgewell** [comment]
Oh, for dev. React uses [`devEngines`](https://github.com/facebook/react/blob/master/package.json#L45-L48), a [`postinstall`](https://github.com/facebook/react/blob/master/package.json#L56) and [check-dev-engines](https://github.com/facebook/fbjs/blob/master/scripts/node/check-dev-engines.js).

**Comment by cramforce** [comment]
CC @paul-matthews
