### ISSUE TITLE
greenkeeper did not update lock file yet passed the CI build

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#16223]
https://github.com/ampproject/amphtml/pull/16195 broke master recently.
It did not update the `lock` file (it should have) and yet Travis was green for it, so it got merged.

**Comment by aghassemi** [comment]
I think the fact that Travis build was green for it is a P1.

**Comment by rsimha** [comment]
I agree this is bad.

The build cop doc mentions that one must check to make sure the lockfile was updated, and covers the case of why Travis is green for the first commit (the first push build updates the lockfile, the first PR build does nothing). The PR should never have been merged.

In any case, we're looking to move off of greenkeeper, so this should be fixed soon. Meanwhile, let's keep this issue open.

**Comment by rsimha** [comment]
This is the push build that was supposed to update the lockfile: https://travis-ci.org/ampproject/amphtml/jobs/394724098

Looks like something went wrong while running the `greenkeeper-lockfile-update` process, and yet it did not fail.

**Comment by aghassemi** [comment]
I see. Thanks for the details. Lowered the priority since it is known and documented.
