### ISSUE TITLE
🌸Cherry pick request for 16218 into 16178 (Approved)

### ISSUE THREAD

**Issue by keithwrightbos** [ampproject/amphtml#16239]
GitHub issue your cherry pick is fixing:

Issue #16218

PR that you are requesting a cherry pick for:
PR #16238

Type: Release issue for the release build you are requesting a cherry pick into:

Release Issue #16178

Is this request for a cherry pick into a canary or a production release?
(If you are requesting a cherry pick into a production release you may need to file a separate cherry pick request for the current canary as well. See the cherry pick documentation.)

Canary

Why does this issue meet the cherry pick criteria? Be specific.

This issue is causing ad requests to be lost for 1% of doubleclick traffic on pubs using prefer viewability over views.

**Comment by zhouyx** [comment]
to @cramforce

**Comment by zhouyx** [comment]
to @dvoytenko : )

**Comment by dvoytenko** [comment]
Approved

**Comment by zhouyx** [comment]
completed
