### ISSUE TITLE
Validation erros with amp-facebook

### ISSUE THREAD

**Issue by okeul** [ampproject/amphtml#1624]
`amp-facebook` displays well but there is an error in AMP validator :

![capture d ecran 2016-01-27 a 22 29 05](https://cloud.githubusercontent.com/assets/6248074/12629037/3dfa4008-c546-11e5-8202-5ea761f689bb.png)

Did I miss something or there is a real bug ?

example : http://output.jsbin.com/pinapa#development=1

**Comment by cramforce** [comment]
Maybe a bit hard to miss, but it is documented here
https://github.com/ampproject/amphtml/blob/master/extensions/amp-facebook/amp-facebook.md#-amp-facebook

It always takes a while before new components start to validate.

**Comment by okeul** [comment]
Ok thank you :-)

It's maybe a good idea to add this mention in this page : 
https://www.ampproject.org/docs/reference/extended/amp-facebook.html

**Comment by cramforce** [comment]
@erwinmombay Do you know when we last pushed this? Must have been before we updated the docs.

@okeul Will be fixed. They are the same doc, just older and prettier rendering :)
