### ISSUE TITLE
amp-form Request header field AMP-Same-Origin is not allowed by Access-Control-Allow-Headers in preflight response

### ISSUE THREAD

**Issue by lealff** [ampproject/amphtml#16245]
added a amp-form in my page and input keywords to search, the page should  jump to a new page but the result as below error:

Failed to load https://m.ecer.com/sale-led: Request header field AMP-Same-Origin is not allowed by Access-Control-Allow-Headers in preflight response.

what should I do?

**Comment by aghassemi** [comment]
@lealff Looks like your HTTP response includes `AMP-Same-Origin` header. It should not, that header is sent by AMP and does not need to be included in the response back (maybe your server is mirroring all sent headers.

https://www.ampproject.org/docs/fundamentals/amp-cors-requests may help as well.

Stackoverflow (https://stackoverflow.com/questions/tagged/amp-html) would be a better resource for questions like this where GitHub would be good for bugs and feature requests.
