### ISSUE TITLE
Pinterest : embedUser & embedBoard ?

### ISSUE THREAD

**Issue by okeul** [ampproject/amphtml#1626]
`amp-pinterest` works well to display Pinterest widget or Pin It button.

What supports is provided for profile (embedUser) or board (embedBoard) ?

**Comment by cramforce** [comment]
CC @kentbrew @zackargyle

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please verify first whether the feature proposal is still relevant.

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
