### ISSUE TITLE
Analytics calls after pageload event #16065 - reopen

### ISSUE THREAD

**Issue by Mohit-3** [ampproject/amphtml#16307]
I am trying to execute analytics call post pageload event on AMP pages. AMP analytics makes image pixel call which are page load blocking and intermittently taking longer time. This time gets add up in pageload time of AMP page.

I do not see load anywhere in trigger options, Available options are....

triggers": {
"trackPageview": {
"on": "visible", (on (required) The event to listen for. Valid values are render-start, ini-load, click, scroll, timer, visible, hidden, user-error, access-*, and video-*)
"request": "pageview"
},

I have already tried on: "visible", but pixels always fire before page load and blocks pageload event..

**Comment by zhouyx** [comment]
Hi @Mohit-3 

Correct, there's no page load event. But the page visible event should serve for that purpose. 

>I have already tried on: "visible", but pixels always fire before page load and blocks pageload event..

Trying to understand here. Are you using the `<amp-pixel>` component or the `<amp-analytics>` component? And when you mentioned "pixels always fire before page load and blocks pageload event." where did you get the page load event?
