### ISSUE TITLE
Adsense active view viewable

### ISSUE THREAD

**Issue by dmitrymotorin** [ampproject/amphtml#1630]
Hi guys,
We've converted our HTML page with ads into AMP HTML including amp adsense blocks. AMP HTML page pass validator.
But... We got less active view viewable on adsense. The basic HTML was 60% of active view viewable and AMP HTML bring it to 0.4%
Where we need to check and how to explain this issue?

**Comment by cramforce** [comment]
@dmitrymotorin Do you have a sample page where you were seeing the issue? Also I'm wondering when you made the measurements? We only turned on viewability in AMP very recently.

**Comment by dmitrymotorin** [comment]
Sample page: http://womanitely.com/things-say-men/
Measurements was made two days ago at adsense analytics reports.

**Comment by cramforce** [comment]
@dmitrymotorin We took a look and it seems fine now. As I said we just recently turned this on, so it is probably best if you try measure again with today's data. I will close this issue, but please reopen if the issue persists!

**Comment by cramforce** [comment]
Quick update! This is actually not working end to end. I will reping this issue when it is expected to full work.

**Comment by dmitrymotorin** [comment]
@cramforce Thank you a lot!

**Comment by rudygalfi** [comment]
This should work as of Monday, 2/8.

**Comment by cramforce** [comment]
@dmitrymotorin Could you report back on your metrics?

**Comment by dmitrymotorin** [comment]
@cramforce Page: http://womanitely.com/things-say-men/amp-list/
3 adsense ads on the page.
Inline Top content: 32.93%
Inline Middle content: 51.30%
Page Bottom: 80.05%
