### ISSUE TITLE
AMP Cache IP range

### ISSUE THREAD

**Issue by carlosabalde** [ampproject/amphtml#1632]
Hi,

Let's assume that all AMP contents in some site will always have an associated canonical non-AMP URL. According to the AMP Access spec, I assume the right thing to do in the server side would be denying access to the AMP contents to all IP addresses except the ones in the AMP Cache range.

Is this a correct assumption? If so, are those IP ranges already known? Are some exclusions (e.g. Google Bot) required?

Thanks!

**Comment by cramforce** [comment]
I let @dvoytenko give a more specific answer, but in general I wanted to clarify that with AMP you cannot expect all user traffic to go through the proxy. Some AMP platforms may send users directly to the AMPs on your server. The amp-access protocol is designed to work in both scenarios.

**Comment by carlosabalde** [comment]
Let's assume AMP Access running in 'client' mode: if users are allowed to fetch AMP contents directly from my server, the paywalled sections are not going to be obscured. I though it was guaranteed that those sections will always arrive obscured to the client side (thanks to AMP Cache proxing the requests). Am I missing something here?

**Comment by cramforce** [comment]
When running in 'client' mode the initial state of a page is up to you. Client specifically refers to the server serving the document doing no transformation at all. I'd recommend to not obfuscate initially, but that is entirely up to you.

For server mode you will need to do IP based serving I believe.

**Comment by carlosabalde** [comment]
From the AMP Access spec, describing the 'client' option:

> [...] AMP Cache returns the document to the Reader with some sections obscured using Access Content Markup. The AMP Runtime calls the Authorization endpoint and uses the response to either hide or show different sections as defined by the Access Content Markup. [...]

My assumptions about this are:

1. My server serves AMP contents including some paywalled sections to AMP Cache.

2. AMP Cache obfuscates paywalled sections in AMP contents.

3. AMP Runtime fetches obscured versions of AMP contents from the AMP Cache and it uses the authorization end-point to decide what sections to show. Those paywalled sections to be displayed are de-obfuscated by the AMP Runtime.

So, the question is: assuming I want to use the 'client' option, can I rely on AMP contents including paywalled sections are always going to arrive obscured to the client side (thanks to the AMP Cache proxing content delivery)? Perhaps I'm not correctly understanding the meaning of 'obscured sections' in the AMP spec?

**Comment by cramforce** [comment]
The client solution only does client-side obfuscation. The data is always present and can e.g. be reached with Chrome DevTools. Whether the doc is first open and obscures itself when your call comes back OR starts closed and does the opposite is up to you.

The server solution does the filtering on the server (AMP cache) and only delivers content to users after it has been determined they are allowed to see it.

**Comment by carlosabalde** [comment]
Thanks. Now is clear. I was assuming that the AMP Cache was also used in the 'client' solution and that it was in charge of doing the obfuscation.

**Comment by dvoytenko** [comment]
@carlosabalde Few answers:

##### First, on Cache IP range.
This is only relevant for server-side solution. We will confirm and publish the IP range.

One thing to note is that server-side solution will not arrive for some time. However, the client-side solution is already in canary and ready to be tested with. I'd recommend starting internally with client-side solution. Both client and server solutions are completely compatible. Then server-side solution will be a single parameter switch if you choose to do so.

##### Serving paywalled content to Cache vs non-Cache
(Notice that this is only relevant to the server solution)

I'd recommend to do what you'd typically do for indexing robots. As a rule, the full content is given to indexer, but the authorization flow is executed for other requests. With AMP Access you'd likely want to do the same. When the request comes from Cache, you'd give the full content, but for other requests you'd run the normal authorization flow that you already do - e.g. you'd return a partial or a complete document depending on the user's profile.

This is one of the reasons why client-side solution is significantly easier to implement. However, as I mentioned above, both solutions are completely compatible and you can start with one and switch to the other.

**Comment by carlosabalde** [comment]
Thanks for the explanations @dvoytenko. Just a couple of comments, just to check I'm not mussing anything here

**I don't think switching to the server-side solution will be a single parameter switch**. That depends a lot on how paywalling is implemented in the publisher side and how the AMP Access client-side solution is integrated. On the client-side solution the publisher can rely on session cookies to identify authenticated users when implementing the authorization and pingback endpoints. Session cookies are going to be available in both endpoints. However, in the server-side solution session cookies are not going to be available (at least when calling to the authorization enpoint). Therefore, switching from the client to server solution requires some changes in the authorization component in order to bind session and reader identifiers. The simplicity of this task depends a lot on the paywall solution used by the publisher. I can think about certain paywalling strategies where supporting this session-RID binding required by the server solution is not trivial.

**I don't think the suggested approach to serve paywalled content to Cache vs non-Cache is useful for some common paywalling scenarios**. When serving paywalled contents to non-Cache clients you cannot run the normal authorization flow used for non-AMP contents. For example, a metered access control solution cannot run the normal authorization flow during delivery of an AMP content (e.g. grant access and consume one credit of quota, increase some server-side metrics, update some server side rate-limiters, etc.) because a later call to the pingback endpoint will be triggered and the side effects executed during the delivery of the content would be executed twice.

Obviously this depends a lot on the internals of the paywall and the side-effects executed during pingback, but I think the general rule should be different: both in the client and in the server solution serve AMP contents skipping the access control logic in order to avoid execution of duplicated side effects during pingback calls.

**Comment by dvoytenko** [comment]
@carlosabalde, you are correct, but not quite.

The client/server switch is simple in the markup and format. However, you are correct, the big difference is in the publisher-side implementation. However, in-house, where security constraints can be ignored, the server-side solution should be testable to a large percent via client-side solution.

The big issue: READER_ID/session binding. Both client and server solutions have to employ it. You are correct, session cookies will arrive in the client solution and they could be of a big help. However, you won't be able to set them in all cases due to 3rd party restrictions. Especially in the case of iOS Safari. Unfortunately the space where session cookies may or may not be available is too fragmented and depends on platform, browser, whether or not the user has visited your site before. Thus the only reliable way is to use READER_ID in all cases and only use session cookies for additional session binding when available.

**Comment by dvoytenko** [comment]
@carlosabalde, to answer the question about IP range, you can use the same approach as recommended for indexing bots via a reverse DNS lookup as described here:

https://support.google.com/webmasters/answer/80553?hl=en

**Comment by carlosabalde** [comment]
Thanks @dvoytenko, the information about RID-SID binding also in client mode has been very useful.
