### ISSUE TITLE
amp-ad causing pages to hang for multiple seconds

### ISSUE THREAD

**Issue by jessanastasio** [ampproject/amphtml#16334]
## What's the issue?

I use `amp-ad` on my page and have been seeing some strange behavior. On Chrome desktop specifically I very often see my page be fully white before content loads in for seconds and while the page is white ad network requests are being sent out. In the performance tab of Chrome shows it recalculating styles and updating the layer tree over and over again - I have no clue why this might be happening or how to debug/avoid it.

<img width="855" alt="screen shot 2018-06-20 at 4 08 50 pm" src="https://user-images.githubusercontent.com/5924733/41876621-67b93d34-789c-11e8-8345-e8e8cec7788d.png">

## How do we reproduce the issue?

If you go to tasty.co on Chrome desktop and click around to different recipes (it isn't super predictable) but within a few clicks you will see the page completely hang for seconds

I also saved the profile from the performance tab that saves into .json to see the exact strange behavior (which I'm unable to attach here)

## What browsers are affected?

Have only reproduced on desktop Chrome

## Which AMP version is affected?

`amp-version="1529449959701"`

**Comment by aghassemi** [comment]
@lannka anything we can do for bad ads?

**Comment by jessanastasio** [comment]
I wonder if using a placeholder for `amp-ad` would be helpful in this situation 🤔 https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad/amp-ad.md#placeholder

**Comment by calebcordry** [comment]
I took a quick look and I was able to repro fairly easily. I haven't tried to debug but leaving stack trace here for future reference. It appears to only be happening on certain creatives.

![image](https://user-images.githubusercontent.com/16087874/41924303-7f6d526c-791e-11e8-971c-09b9db918614.png)

**Comment by jessanastasio** [comment]
I know this is pending triage and there are a bunch of other priorities/bugs but I wonder if anyone has tips for me to debug this more on my own 🤔this makes my site look/feel super broken and I'm not sure the best way to debug or get around it right now since I need to use `amp-ad`

**Comment by calebcordry** [comment]
@jessanastasio Could you please share the profile you saved? I am not able to repro with the performance tab open 😕

**Comment by calebcordry** [comment]
![image](https://user-images.githubusercontent.com/16087874/42901367-40fe3ec4-8a80-11e8-9038-ac45c3fb1d2f.png)

**Comment by curseagain** [comment]
Hi @calebcordry, here are the steps I've taken to reproduce the issue:
1. Clear your browser's cache of images and files
2. Continuously visit different recipe pages on tasty.co on chrome desktop.  Eventually you'll encounter a page that takes a very long time to load.  Here is a little video to demonstrate: https://monosnap.com/file/CXKKYapljhUXWRqqfybvApaYbpHXHs

The error that I'm seeing each time we experience the lag is this:
```
TypeError: amp-a4a: doubleclick: Cannot read property 'obj' of undefined
    at J (service.js:400)
    at I (service.js:270)
    at Q (service.js:267)
    at oe.push.f.g.getA4aAnalyticsVars (utils.js:552)
    at X (amp-a4a.js:1800)
    at td (amp-a4a.js:1578)
    at oe.push.f.g.renderNonAmpCreative (amp-a4a.js:1413)
    at oe.push.f.g.renderNonAmpCreative (amp-ad-network-doubleclick-impl.js:937)
    at amp-a4a.js:1101
```

Here are each of the ad request URLs from that video:
* [awareness](https://securepubads.g.doubleclick.net/gampad/ads?iu=%2F6556%2Ftasty.awareness.desktop%2Fen%2Frecipe%2Fawareness&adk=1010001596&sz=970x90%7C970x90&output=html&impl=ifr&ifi=1&scp=poe%3Dgoogle.amp%26pos%3Dawareness%26wid%3D42&adf=190812243&nhd=0&eid=21060933&adx=235&ady=58&oid=2&adsid=AOsWmdct09_E0fJ6UqoVEWExCzZF8kyh4VTfKQCESJ0v3zjS_lNqOR8AzXvaQVnH75nX&jar=2018-7-18-19&pucrd=CgYgASgBOAF4Aw&gdfp_req=1&sfv=1-0-23&u_sd=1&is_amp=3&amp_v=1531347091169&d_imp=1&c=21002077&ga_cid=amp-PO21UcEwBmDXYlJLWjIqxw&ga_hid=2077&dt=1531941146995&biw=1440&bih=449&u_aw=1440&u_ah=877&u_cd=24&u_w=1440&u_h=900&u_tz=-420&u_his=24&vis=1&scr_x=0&scr_y=0&bc=7&url=https%3A%2F%2Ftasty.co%2Frecipe%2Fshrimp-salad-with-creamy-avocado-dressing&ref=https%3A%2F%2Ftasty.co%2Frecipe%2Froasted-chickpea-and-avocado-salad&dtd=616&__amp_source_origin=https%3A%2F%2Ftasty.co)
* [promo1-wide](https://securepubads.g.doubleclick.net/gampad/ads?iu=%2F6556%2Ftasty.desktop%2Fen%2Frecipe%2Fpromo1-wide&adk=1778098461&sz=970x250%7C970x250%7C970x90&output=html&impl=ifr&ifi=2&scp=poe%3Dgoogle.amp%26pos%3Dpromo1-wide%26wid%3D68&adf=1676530611&nhd=0&eid=21060933&adx=235&ady=1170&oid=2&adsid=AOsWmdct09_E0fJ6UqoVEWExCzZF8kyh4VTfKQCESJ0v3zjS_lNqOR8AzXvaQVnH75nX&jar=2018-7-18-19&pucrd=CgYgASgBOAF4Aw&gdfp_req=1&sfv=1-0-23&u_sd=1&is_amp=3&amp_v=1531347091169&d_imp=1&c=21002077&ga_cid=amp-PO21UcEwBmDXYlJLWjIqxw&ga_hid=2077&dt=1531941146995&biw=1440&bih=449&u_aw=1440&u_ah=877&u_cd=24&u_w=1440&u_h=900&u_tz=-420&u_his=24&vis=1&scr_x=0&scr_y=0&bc=7&url=https%3A%2F%2Ftasty.co%2Frecipe%2Fshrimp-salad-with-creamy-avocado-dressing&ref=https%3A%2F%2Ftasty.co%2Frecipe%2Froasted-chickpea-and-avocado-salad&dtd=616&__amp_source_origin=https%3A%2F%2Ftasty.co)
* [promo1-bp](https://securepubads.g.doubleclick.net/gampad/ads?iu=%2F6556%2Ftasty.desktop%2Fen%2Frecipe%2Fpromo1-bp&adk=4272256042&sz=300x600%7C300x250%7C300x600&output=html&impl=ifr&ifi=3&scp=poe%3Dgoogle.amp%26pos%3Dpromo1-bp%26wid%3D45&adf=525638586&nhd=0&eid=21060933&adx=980&ady=1524&oid=2&adsid=AOsWmdct09_E0fJ6UqoVEWExCzZF8kyh4VTfKQCESJ0v3zjS_lNqOR8AzXvaQVnH75nX&jar=2018-7-18-19&pucrd=CgYgASgBOAF4Aw&gdfp_req=1&sfv=1-0-23&u_sd=1&is_amp=3&amp_v=1531347091169&d_imp=1&c=21002077&ga_cid=amp-PO21UcEwBmDXYlJLWjIqxw&ga_hid=2077&dt=1531941146995&biw=1440&bih=449&u_aw=1440&u_ah=877&u_cd=24&u_w=1440&u_h=900&u_tz=-420&u_his=24&vis=1&scr_x=0&scr_y=0&bc=7&url=https%3A%2F%2Ftasty.co%2Frecipe%2Fshrimp-salad-with-creamy-avocado-dressing&ref=https%3A%2F%2Ftasty.co%2Frecipe%2Froasted-chickpea-and-avocado-salad&dtd=616&__amp_source_origin=https%3A%2F%2Ftasty.co)

Please let us know if we can provide any additional information!

**Comment by calebcordry** [comment]
We investigated this issue. You can reproduce using the example page located here https://gist.github.com/calebcordry/9ab3e27fcfddd9e34fb5419a86d18558

That gist has a bit of code at the very beginning that logs `window['__AMP_BODY_VISIBLE']` as the very first line of code that runs. AMP uses this property in the runtime to determine if the body is showing. On the good page loads this logs `undefined` but on the bad page loads it evaluates to `true`.

This appears to be caused by some sort of state leakage from one page to another. This property should never be `true` when visiting a new page (until after the runtime has set it).  We think that this leak is probably cause by some bad code in an ad, but regardless chrome should protect against this happening. 

This happens in both chrome 67 and 70 canary versions.

We will be following up with the chrome team to report this issue.

cc/ @lannka @zhouyx
