### ISSUE TITLE
AMP Access expression grammar

### ISSUE THREAD

**Issue by carlosabalde** [ampproject/amphtml#1633]
I would like to clarify a couple of simple questions about the AMP Access expression grammar:

  - Are dots, dashes and/or underscores allowed in the names of properties returned by the AMP Access authorization endpoint? The [expression grammar](https://github.com/ampproject/amphtml/blob/master/extensions/amp-access/amp-access-spec.md#appendix-a-amp-access-expression-grammar) is slightly ambiguous about this.

  - Are string comparisons allowed in AMP Access expressions?

**Comment by dvoytenko** [comment]
@carlosabalde a more complete grammar is here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-access/0.1/access-expr-impl.jison

> Are dots, dashes and/or underscores allowed in the names of properties returned by the AMP Access authorization endpoint? 

No, dots, dashes or underscores allowed. Underscores is rather unfortunate and I will fix it asap. But I think dots and dashes will not be allowed.

**Comment by dvoytenko** [comment]
@carlosabalde

> Are string comparisons allowed in AMP Access expressions?

Yes.

```
field = 'abc'
field != 'abc'
```

**Comment by dvoytenko** [comment]
I updated the grammar. Names now allow underscore.

**Comment by jugglingcats** [comment]
Is there a reason nested objects are not allowed, eg.
```
field: { prop1:'value' }
```
Sometimes an access decision can contain quite complex information needed to message the user, and flattening this into name value pairs is restrictive.

**Comment by dvoytenko** [comment]
No strong reason, no. Mostly it's meant to insist on simpler structures given that the authorization response is free-form and designed specifically for the needs of access. And we'd definitely like to limit the depth, e.g. to only the depth of 1 (object.field). Do you see it really needed? Could you share an example or two?

**Comment by jugglingcats** [comment]
Thanks for reply. A metering response might look like this:
```
{
  "action": "login",
  "exceededMeter": {
   "period": "WEEKLY",
   "max": "10"
  },
  "authenticatedMeter" {
   "period": "WEEKLY",
   "max": "20"
  }
}
```

In some cases complex messaging would be left to the login page, but you can imagine using amp-mustache directly to render a message like:

```
You have exceeded your meter count of 10 articles per week.
But you can get up to 20 articles per week by registering.
Register or sign in now to read this article!
```

Obviously the data can be flattened but this is not very scalable.

**Comment by dvoytenko** [comment]
Sounds good. I moved the request to https://github.com/ampproject/amphtml/issues/1919
