### ISSUE TITLE
`git fetch` is being slowed down by the large number of stale `upstream` branches

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#16346]
A part of the daily AMP development workflow is to run `git fetch` against `https://github.com/ampproject/amphtml` (which is typically mapped to `upstream`). I've noticed that doing a fetch has been getting slower over time, and prints a growing number of branch names each time.

On looking at https://github.com/ampproject/amphtml/branches, I noticed the following: 

- We have more than 200 branches on the main repo, most of them over a year old
- Most of them are `amp-release` branches, and were created during past releases
- A large number (stale and current) belong to a few individuals who appear to be creating branches on the main AMP repo

<img width="1984" alt="" src="https://user-images.githubusercontent.com/26553114/41883917-ed84adbe-78be-11e8-9f3e-852ca68fc692.png">

A couple groups of questions:
1. **`amp-release` branches:**
    - Is there any reason to keep the old `amp-release` branches?
    - Can they be cleaned up after the respective releases are complete?
2. **non-`amp-release` branches:**
    - The dev docs recommend [forking](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code) the main AMP repository. Is there any advantage to developing directly from the `ampproject/amphtml` main repo?
    - Are there circumstances under which that's the only (or preferable) option?
    - Would you be okay if your stale branches were cleaned up?
    - And would you consider working on a fork to speed up `git fetch` for everyone else?

**Comment by rsimha** [comment]
/to @cramforce @mrjoro @erwinmombay for comment on question group 1
/cc @aghassemi @ericlindley-g @bradfrizzell @gmajoulet @jasti @newmuis @kristoferbaxter @pbakaus @rudygalfi for comment on question group 2, since you each have multiple branches on the main repo

**Comment by gmajoulet** [comment]
My use case was editing a documentation file directly from GitHub, to enjoy their editor and markup diff / preview mode.
We should delete the branches once they're merged. My branches can be cleaned up.

**Comment by ericlindley-g** [comment]
Same response on my end as @gmajoulet 's

**Comment by kristoferbaxter** [comment]
Once the branches for changes made via the Github UI have been merged I have ho issue with deleting them.

**Comment by rudygalfi** [comment]
I'm in the same boat as @ericlindley-g and @gmajoulet. No issue with it being cleaned up.

**Comment by newmuis** [comment]
Same

**Comment by mrjoro** [comment]
+1 to what others have said, let's aggressively delete branches with changes that have already been merged.

I'd even be okay deleting old branches off the main repo even if they haven't been merged, ideally with a courtesy notice to the creators.  My understanding is that it is possible restore deleted branches right?

For the release branches I defer to @erwinmombay and you (@rsimha), though if it is possible to undeleted old branches then I'd lean towards deleting them.

**Comment by rsimha** [comment]
Great, thanks all. I'll do a one-time clean up for now, and we can come up with a way of periodically paring down the number of branches on our main repo.

**Comment by rsimha** [comment]
Update: I've done a one-time delete of all stale / unused branches. We can keep an eye on the number of branches over time and see if they continue to accumulate.

**Comment by rsimha** [comment]
Closing for now, will review periodically.
