### ISSUE TITLE
double html elements breaking amp-subscriptions CSS on iPhone with viewer

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#16370]
When an amp doc is rendered in the viewer (eg https://www.google.com/amp/s/amp.ft.com/content/c1bc5920-7936-11e8-bc55-50daf11b720d) a nested `html` elements is created.

![screen shot 2018-06-26 at 7 27 13 am](https://user-images.githubusercontent.com/524856/41919013-5ed6bb62-7912-11e8-9b9c-9eb0c84b92d5.png)

The breaks any CSS of the form

```CSS
html:not(.foo)
```

This breaks `amp-subscriptions` and may be breaking publisher CSS.

**Comment by prateekbh** [comment]
We have 4 of such instances, 
```
html:not(.i-amphtml-subs-loading) [subscriptions-section="loading"] ,
html:not(.i-amphtml-subs-grant-yes) [subscriptions-section="content"],
html:not(.i-amphtml-subs-grant-no) [subscriptions-section="content-not-granted"],
html:not(.i-amphtml-subs-grant-yes) .i-amphtml-subs-dialog-close-button
```

Should we instead scope it by 
`.i-amphtml-singledoc:not` or `html[amp-version]:not(.foo)` ?
CC: @dvoytenko

**Comment by jpettitt** [comment]
or `html:not(#i-amphtml-wrapper):not(.foo)`

**Comment by dvoytenko** [comment]
This is fine. Or alternatively, we can move to `body` element?

**Comment by dvoytenko** [comment]
On reflection, moving the selectors on body would be better. I see other similar ones there. E.g. 

```
body:not(.i-amphtml-subs-loading) [subscriptions-section="loading"] ,
```

etc

**Comment by jpettitt** [comment]
reopening for longer term fix to move classes to `body`

**Comment by prateekbh** [comment]
Re-opening as the cherry-picked changed did not changed the rule for 

https://github.com/ampproject/amphtml/blob/aace0737e981310958244c18834f64426d8d3446/css/amp.css

**Comment by erwinmombay** [comment]
This is a high priority issue but it hasn't been updated in awhile. @jpettitt Do you have any updates?

**Comment by jpettitt** [comment]
This is now fixed.
