### ISSUE TITLE
🌸 Cherry pick request for #16370 into #16025 (Approved)

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#16375]
Replace everything in angle brackets in the title AND body of this issue. If you have any questions see the cherry pick documentation.

GitHub issue your cherry pick is fixing:

Issue #16370 
PR that you are requesting a cherry pick for: 

PR #16373

Release(s) you requesting this cherry pick into:

Release issues can be found at https://github.com/ampproject/amphtml/labels/Type%3A%20Release

If you are requesting a cherry pick into a production release you will most likely need to cherry pick into canary as well, otherwise when the canary is pushed to production your fix will be lost. See the cherry pick documentation.)

Production Release? Yes If yes, Type: Release Issue #16025 

Canary release? Yes If yes, Type: Release Issue #16178, 

Why does this issue meet the cherry pick criteria? Be specific.

This breaks amp-subscriptions in production.

Assign this issue to the current TL (cramforce) if you have permission to, otherwise leave this cc line in.

/cc @cramforce

**Comment by cramforce** [comment]
This is borderline, but approved.

**Comment by jridgewell** [comment]
See https://github.com/ampproject/amphtml/issues/16388 for updates.
