### ISSUE TITLE
Clarify <amp-story> metadata requirements

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amphtml#16376]
Various [attributes of `amp-story`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/amp-story.md#new-metadata-requirements) are used to specify images used for generating previews, etc. The docs specify the expected aspect ratios of each, but they should also include:

- supported/recommended image formats (e.g. is SVG allowed?)
- supported/recommended minimum dimensions
- supported/recommended file sizes

/cc @newmuis @bpaduch

**Comment by newmuis** [comment]
This is now covered in https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/amp-story.md#migrating-from-01-to-10
