### ISSUE TITLE
Enhance `gulp test --local-changes` to pick up CSS changes

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#16387]
As requested by @jpettitt:

Modifying a CSS file and running `gulp test --local-changes` does not run any tests. Try making it so that tests for the JS file that includes the CSS are run.

**Comment by rsimha** [comment]
On looking at the code, I'd imagine we'd need to do something like this to determine which tests to run for a given CSS change:

1. Capture the full list of CSS files spread across `amphtml/css/` and in the various extensions directories
2. Figure out the mapping from `.css` files to `.css.js` files when `gulp css` is run (this is currently hard coded in `gulpfile.js` via a list of `declareExtension()` calls)
3. For each CSS file changed on the local branch, figure out the list of `.js` files that import the corresponding `.css.js` file(s) in the step above
4. For each of those `.js` files, figure out which `test-*.js` files import them
5. Run the tests in those `test-.js` files

Currently, we only do steps 4 and 5 for `.js` files changed by a PR. I wonder if there's a simpler way to accomplish the `.css` -> `.js` mapping than what I've listed in steps 1-3.

@jpettitt Thoughts?

**Comment by jpettitt** [comment]
I don't think set 1 is needed as `gulp css` has all the info you need.  If you could stash that info as it builds the `.css.js` files you'd be a long way towards having this.
