### ISSUE TITLE
The <amp-iframe> 600px / 75% rule - based on what width?

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#1639]
The `<amp-iframe>` spec, and the validation code, reference the 600px/75% rule.  However there is no description of what width that applies to.  For example 600px down on a iPhone 4 is a completely different proposition to the same content on an iPad pro or a desktop.   What width does the CDN use when validating?  Do publishers have to guess based on the user agent what width they are dealing with and adjust content?  Always use worst case?

**Comment by rudygalfi** [comment]
I believe this is measured independently of width. In the context of a device, the restriction has different ramifications, but the enforcement will be the same across screen sizes.

/cc @cramforce

**Comment by dvoytenko** [comment]
This restriction can be removed by adding a placeholder as described here: https://github.com/ampproject/amphtml/blob/a5b3a0f6153f71fbec7e5648bd46b79f6b4013e1/extensions/amp-iframe/amp-iframe.md

**Comment by jpettitt** [comment]
Since you're asking for feedback I think the rule is pretty unusable as defined.  What rule effectively says is "always use a placeholder or your code will fail randomly when some user has a screen wider than you anticipated".  Perhaps just changing it to make placeholders mandatory would be simpler all round?

**Comment by cramforce** [comment]
@jpettitt yeah, we just actually changed the error message to give clear advice how to fix it. Switching to no-rule-but-mandatory-placeholder is generally a good idea. Added to #1356

**Comment by mjangda** [comment]
> Since you're asking for feedback I think the rule is pretty unusable as
defined. What rule effectively says is "always use a placeholder..."

That's what we ended up doing for the WordPress plugin. There isn't a super
easy, consistent, reliable way for us to determine element position when
generating the AMP files so we just include a placeholder for all iframes.

**Comment by cramforce** [comment]
@mjangda What do you put into that placeholder?

**Comment by mjangda** [comment]
> What do you put into that placeholder?

Just a `<div>` with a background image via CSS.

**Comment by rudygalfi** [comment]
Closing since we've captured mandatory placeholder in https://github.com/ampproject/amphtml/issues/1356
