### ISSUE TITLE
Document "noscript" tag and behavior

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#1640]
Probably a good place is in https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md, under the table of elements.

/cc @rudygalfi @Meggin

**Comment by Meggin** [comment]
Is this the new boilerplate? Just want to confirm this is what we want to make sure is documented correctly.

**Comment by dvoytenko** [comment]
No. We know allow `noscript` to be used anywhere in the document. What it gets us is that, the document is still readable, even if the user has decided to turn off javascript.
