### ISSUE TITLE
Initialization of custom elements in friendly iframe causes error to be logged.

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#16416]
This repros on any page with an A4A ad that contains at least one custom element.
<img width="485" alt="screen shot 2018-06-27 at 8 40 54 am" src="https://user-images.githubusercontent.com/89679/41984564-d4bdbdde-79e5-11e8-9bac-16cd28801b66.png">

```txt
v0.js:42 Uncaught TypeError: Cannot read property 'create' of undefined
    at new uj (v0.js:42)
    at new Cf (document-register-element.node.js:294)
    at document-register-element.node.js:284
    at Wb (document-register-element.node.js:291)
    at Sl (amp-img.js:152)
    at Kl.f.installExtensionsInChildWindow (vsync-impl.js:438)
    at friendly-iframe-embed.js:209
```

Example URL https://amp-20minutos-es.cdn.ampproject.org/v/s/amp.20minutos.es/noticia/3357093/0/nueva-portada-revista-time-creada-98-drones/?amp_js_v=0.1&usqp=mq331AQECAEoAQ%3D%3D

This appears to be harmless but spams the console. I don't completely follow why it is logged OR why it is harmless :)

**Comment by oliverfernandez** [comment]
This is happening in AMP Shadows as well, whenever an AMP-AD with Doubleclick Fast Fetch implementation is used

![screen shot 2018-06-29 at 17 10 50](https://user-images.githubusercontent.com/1696239/42100231-ef6d409c-7bbf-11e8-9821-afa9d3850a7f.png)

https://www.thelondoneconomic.com/

We have detected this since 2 weeks ago approximately

**Comment by gabelew** [comment]
We are getting the same error as we also have amp-img in our ad. Is there any update to this issue?

**Comment by christian-felix** [comment]
I got the same error but this simple code: 

```
<button [text]="visible ? 'Show Less' : 'Show More'" on="tap:AMP.setState({visible: !visible})">Show More</button>
<p [class]="visible ? 'show' : 'hide'" class="hide">Some more content.</p>
```
Page validation ok, no errors at all. 

Then  within the developer tool it comes this message up: 

v0.js:formatted:1323 Uncaught TypeError: Cannot read property 'create' of undefined
    at new Oj (v0.js:formatted:1323)
    at new Sf (v0.js:formatted:1797)
    at v0.js:formatted:1791

**Comment by jridgewell** [comment]
This will be fixed by https://github.com/ampproject/amphtml/pull/17205.
