### ISSUE TITLE
amp-selector multiple selection count

### ISSUE THREAD

**Issue by AcidRaZor** [ampproject/amphtml#16414]
Hi,

I'm currently tasked to do a color picker (much like your e-commerce examples) but to have someone select up to 3 color's only (out of 8)

I was hoping there would be a "count" or a "length" that I could leverage off of to control it somehow and force the other 6 selections to "disabled".

I went through as much documentation as possible, as well as the source, but couldn't find a clue on how to achieve a multi-select with a maximum allowed number of items selected while making the other options disabled when that threshold has been reached.

Any insight into this? I know this isn't an issue per-sè but I'm confident that this will either be taken up by the dev-team or a work-around suggested.

Thanks in advance!

**Comment by aghassemi** [comment]
@AcidRaZor I suggest using `amp-bind` to build your color selector. I will allow you todo custom logic based on number of selections, etc.. `amp-selector` precedes `amp-bind` and all of its functionality is doable in `amp-bind` with minimal work.

**Comment by aghassemi** [comment]
Closing per suggestion of using `amp-bind`. We do not plan to extend `amp-selector` with features already doable with bind.

**Comment by AcidRaZor** [comment]
@aghassemi Would you be so kind as to give an example of how amp-bind can be used in place of amp-selector and how I would achieve catching "select" and "deselect" events so I can count how many was selected and stop a person from selecting more? amp-bind seems it won't work for this at all tbh. And since the internet is devoid of anyone going into more detail or tutorials about AMP, it would be highly appreciated if you could post something here instead for people to find in case they struggle with this as well.

**Comment by aghassemi** [comment]
@kul3r4 @sebastianbenz Is there a ABE sample using `bind` similar to what @AcidRaZor likes to do (seems similar to seat picker)? If not, would you be able to help him out? Thanks!

**Comment by kul3r4** [comment]
We don't have a similar sample but I am taking a look now!

**Comment by kul3r4** [comment]
Take a look at [https://codepen.io/anon/pen/QxPPGw?editors=0001](https://codepen.io/anon/pen/QxPPGw)
