### ISSUE TITLE
how can i calculate event params in event?

### ISSUE THREAD

**Issue by zfharoro** [ampproject/amphtml#16411]
i want calculate event.percent in Math.floor(event.percent)

```
<amp-video id="video-player" class="video-player"
            preload
            layout="responsive"
            width="576"
            height="1024"
            on="timeUpdate:replayMaskAni.seekTo(percent=event.percent)">
</amp-video>
```

to
```
<amp-video id="video-player" class="video-player"
            preload
            layout="responsive"
            width="576"
            height="1024"
            on="timeUpdate:replayMaskAni.seekTo(percent=Math.floor(event.percent))">
</amp-video>
```
but faild
how can i get Math.floor for the event.percent

**Comment by zfharoro** [comment]
i want calculate event.percent in Math.floor(event.percent)
<amp-video id="video-player" class="video-player"
            src="{{ data.video.url_list[0] }} " 
            poster="{{ data.video.cover.url_list[0] }}" 
            preload
            layout="responsive"
            width="576"
            height="1024"
            on="replayMaskAni.seekTo(percent=event.percent)">
</amp-video>
to
<amp-video id="video-player" class="video-player"
            src="{{ data.video.url_list[0] }} " 
            poster="{{ data.video.cover.url_list[0] }}" 
            preload
            layout="responsive"
            width="576"
            height="1024"
            on="replayMaskAni.seekTo(percent=Math.floor(event.percent))">
</amp-video>
but faild

**Comment by zfharoro** [comment]
what is more,i can not get amp state value in event as follow:
<amp-state id="download_url">
    <script type="application/json">
        {
            "bottom": "http://m.onelink.me/5f85c8e0"
        }
    </script>
</amp-state>
<div class="bottom-banner" on="tap:AMP.navigateTo(url=AMP_STATE(download_url.bottom)" data-app-download-position="bottom">
            <span class="text">Download to view more!</span>
</div>

**Comment by choumx** [comment]
Why do you need `Math.floor` for `seekTo()`? For the navigation example, you want to use `amp-list` to to render a dynamic anchor tag.

**Comment by zfharoro** [comment]
Because i want to call functions while the video paused, and the only event i can use is the timeUpdate event with event.percent

**Comment by zfharoro** [comment]
For the navigation example，in fact ,i want to realize that 
`<div class="bottom-banner" on="tap:AMP.navigateTo(url=AMP_STATE(download_url.bottom)) setTimeout(_function, 3000)">
      <span class="text">Download to view more!</span>
</div>`
how can i realize this ?

**Comment by choumx** [comment]
I reread this a few times again and I'm still not sure what the intent of this FR is. 

Can you clearly describe your high-level use case? Then we'll reopen the issue.
