### ISSUE TITLE
More Information About Ad Tech Vendors?

### ISSUE THREAD

**Issue by paulredmond** [ampproject/amphtml#1641]
I was researching ad capabilities and came across this post - https://amphtml.wordpress.com/2016/01/25/amp-what-about-ads/. I am trying to compare my current mobile ad offering and compare with AMP capabilities so I can make decisions about how/what to integrate and what I cannot integrate that I currently do for mobile traffic.

> It also includes integration with 20+ ad tech vendors, all of whom are excited to participate in the AMP initiative

Looking at the [ad documentation](https://www.ampproject.org/docs/reference/amp-ad.html) I see a handful of vendors, and I am wondering when / where information will be available for other vendors?

**Comment by rudygalfi** [comment]
cc @kashyapnitin

**Comment by cramforce** [comment]
@kashyapnitin Could you prepare some use case driven docs? Right now we only talk about the capabilities, but users have to transfer that themselves.

@paulredmond While we can improve the docs it is best to get guidance from your existing vendors how to integrate with AMP. Only a small part of the AdTech ecosystem needs "1st class" support in AMP. Most can just give you info how to make their offering work in the AMP context.

**Comment by kashyapnitin** [comment]
Dear Paul, 
we are preparing a more complete ads user guide and tips however in the mean time 

a) you can look at some usecase driven ads related examples here: https://dfp-amp-testing-1185.appspot.com/

b) from a vendors supported perspective the summary is as follows:
* Supported Ad servers - with their own custom type in <amp-ad>	
  / DFP, A9, Dot&Ads, SMART, AdForm
* Supported SSPs & AdExchanges - with their own custom type in <amp-ad>	
  / AdSense, AdReactor, AdTech
* Indirectly supported SSPs & AdExchanges 	
  / All as long as their creatives can be trafficked through any of the supported Ad servers as above
* Supported Sponsored content providers	
  / Outbrain
  / Taboola
  / Plista
* Supported Viewability providers	
 / ActiveView
 / Moat
* Supported Video players	
 / Youtube
 / Brightcove
 / Vine 
 / DailyMotion (not yet in prod)
 / Vimeo
* Supported Video Networks	
 / Any that can have their videos shown in one of the supported players above and ensure all HHTPS content only
* Supported DMPs - with their own custom AMP components	
 / none
* Indirectly supported DMPs	
 / Any as long as the publisher can use the custom 3P integration methodology via remote.html to use them
* Specialised creative / format providers with support / validation for their creatives to work in AMP	
/ All basic HTML creatives from all existing agencies that comply to the ads rules & constraints should work

do you have any additional specific usecases / vendors that you would want to know about but not covered above?

Many thanks

**Comment by paulredmond** [comment]
> do you have any additional specific usecases / vendors that you would want to know about but not covered above?

Thanks for the wealth of information! I'll internalize it and provide follow up feedback :+1:

**Comment by jasti** [comment]
Has been open for a while. Please re-open if necessary.
