### ISSUE TITLE
amp-experiments breaks if an experiment group is set to 0

### ISSUE THREAD

**Issue by cpapazian** [ampproject/amphtml#16418]
## What's the issue?
If an experiment config has a group with `0`, the AMP runtime throws an error (which is not caught), and rejects the entire `<amp-experiments>` configuration.

![image](https://user-images.githubusercontent.com/1939552/41987886-661837ec-79ef-11e8-976f-9abafcac82ee.png)

However, the docs suggest that 0 is a valid configuration:

>A name-to-percentage map where percentage is a float number in range (0, 100) that indicates the amount of traffic will be allocated to the variant. 

Even with an invalid/illegal value in the configuration, a warning, with either: the invalid group(s) or the experiment contains the invalid group(s) would be better, so that one invalid experiment configuration doesn't break the page.

At a minimum, the documentation should be updated to make it clear that 0 is not a valid configuration.

## How do we reproduce the issue?
```
<amp-experiment>
  <script type="application/json">
    {
      "my-broken-experiment": {
        "sticky": true,
        "variants": {
          "treatment_1": 12.5,
          "treatment_2": 12.5,
          "treatment_3": 0.0
        }
      },
      "another-experiment:
        "variants": {
          "enabled": 5.0,
          "control": 5.0
        }
    }
  </script>
</amp-experiment>
```

## What browsers are affected?
Reproduced on Chrome Version 66.0.3359.181 (Official Build) (64-bit) with mobile device emulation

## Which AMP version is affected?
1530043289240

**Comment by jpettitt** [comment]
As intended - see #4824
