### ISSUE TITLE
amp-analytics configurations with VARIANTS fail if amp-experiment is misconfigured

### ISSUE THREAD

**Issue by cpapazian** [ampproject/amphtml#16419]
## What's the issue?

If `VARIANTS` is included in an `<amp-analytics>` request, but `<amp-experiment>` is missing or misconfigured, the request will not fire. Could `VARIANTS` default to an empty string if the `<amp-experiment>` component is not able to supply a value? 

## What browsers are affected?

Reproduced on Chrome Version 66.0.3359.181 (Official Build) (64-bit) with mobile device emulation

## Which AMP version is affected?

1530043289240

**Comment by lannka** [comment]
`VARIANTS` is a `promise` that to be resolved by `amp-experiment`. There is hardly a way for `amp-analytics` to tell if `amp-experiment` failed and `VARIANTS` would never come, so it can stop waiting.
