### ISSUE TITLE
Add data: URI support to amp-img

### ISSUE THREAD

**Issue by kevinmarks** [ampproject/amphtml#1642]
https://withknown.com creates AMP versions of pages and links to them. However, if an image is in a data: URI, amp doesn't render it.

AMP version:

http://known.kevinmarks.com/2016/translating-what-you-write-to-other-sites?_t=amp

normal version:

http://known.kevinmarks.com/2016/translating-what-you-write-to-other-sites

**Comment by dvoytenko** [comment]
@kevinmarks I took a look. I think the problem is not a data URL, but that the image does not have a layout. I added layout attributes and it appears to show:
```
<amp-img layout=responsive width=400 height=300
                                   class="ui-sortable-handle">
...
```
See http://jsbin.com/cihalu/edit?html,output

**Comment by dvoytenko** [comment]
I'll close for now, but please reopen if something is outstanding.
