### ISSUE TITLE
Does amp-youtube support attribute rotate-to-fullscreen ?

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#16431]
To whom it may concern:

I checked the following document and consider &lt;amp-youtube&gt; support attribute **rotate-to-fullscreen**. 

[Video in AMP](https://github.com/ampproject/amphtml/blob/master/spec/amp-video-interface.md#rotate-to-fullscreen)

There will be an error occur when I add "rotate-to-fullscreen" to amp-youtube.

```
<amp-youtube
    id="yt-player"
    data-videoid="xxxx"
    layout="responsive"
    rotate-to-fullscreen
    autoplay
    data-param-rel="0"
    data-param-showinfo="0"
    width="800" height="600"></amp-youtube>
```

I wonder is this an issue or just amp-youtube not support this feature.

Thanks for replying.

Paul

**Comment by sparhami** [comment]
This should work in theory, but I see an error that might prevent this from working correctly.

It looks like an assert is failing here for `<amp-youtube>`:

https://github.com/ampproject/amphtml/blob/942f22672f23ea4c25743e3dd9dcc0f9d9dbc2d9/src/utils/video.js#L116

when called from here:

https://github.com/ampproject/amphtml/blob/942f22672f23ea4c25743e3dd9dcc0f9d9dbc2d9/src/service/video-manager-impl.js#L999

It seems like the video element does not exist yet when this is called.

@alanorozco

**Comment by kevinkassimo** [comment]
Seems moving
https://github.com/ampproject/amphtml/blob/abbccaee3e64e5b54111e2f39d17da6bd2b4b213/extensions/amp-youtube/0.1/amp-youtube.js#L160
to `layoutCallback` after creating iframe should work

**Comment by kevinkassimo** [comment]
Taking this one if no one else is checking out

**Comment by alanorozco** [comment]
@kevinkassimo
Awesome, thanks!
Feel free to assign yourself to any given issue when taking it.

**Comment by aghassemi** [comment]
@meistudioli Short answer is no on iOS (Chrome has native rotate to fullscreen anyway). We need an API from Youtube before we can support iOS. We are tracking the work internally 

b/111646997 for internal reference.

@kevinkassimo is updating the documentation to reflect this.
