### ISSUE TITLE
Multiple Client-side filter is not working at same time.

### ISSUE THREAD

**Issue by techleadzphp** [ampproject/amphtml#16437]
Multiple Client-side filter is not working at same time.

I have used the multiple Client-side filtering in the sidebar but its not working when we select the multiple filters at same time.
Demo Link:
https://dev.optfirst.org/chattanoogaautosquare/inventory.html

How we can fix this issue?

**Comment by aghassemi** [comment]
@techleadzphp Your `setState` is filtering `allProducts`, it needs to filter `filteredProducts` if you want them to compound ( and initially set `filteredProducts` to `allProduct ` to make it easier)

For future, Stackoverflow or Slack channel would be better for these questions, we hope to reserve github for real bugs. Please see https://www.ampproject.org/support/developer/get_support for different developer support channels AMP has.
