### ISSUE TITLE
I2I: amp-skimlinks

### ISSUE THREAD

**Issue by lepunk** [ampproject/amphtml#16435]
Hello AMP Community,

I'm Tamas, Staff Engineer of Publisher Content team at Skimlinks.

Skimlinks is the leading commerce content monetization platform, supporting publishers’ creation of a new revenue stream that allows them to be less dependent on advertising. 

We work with over half of the top 100 US and UK publishers and our technology is deployed on 7.2% of the top 10k websites (source: https://trends.builtwith.com/ads/SkimLinks).  

We monetize 1.3 million clicks on a daily basis and this increases to 4.4 million clicks on key shopping days such as Black Friday.

# Motivation

We are continually working with publishers on ways to increase their revenue streams, without damaging user experience. 

The consistent ask we receive from some of the world's leading publishers, including Vox Media, HuffPost and Hearst, is to provide them with a Skimlinks AMP extension. 

This would enable them to accelerate the monetization of their content through AMP.

# Requirements

Our proposed AMP implementation is the same as our standard javascript implementation that is outlined below. 

We are huge believers of the core AMP principle, performance over everything else (no one likes bloated pages). Our typical desktop javascript bundle is currently just below 10kb, for AMP we are aiming for a fraction of this.

Core functionality to be built as an AMP component initially:

* The core functionality is monetizing retailer links on the publisher website by converting them to the equivalent affiliate link. In order to do this the Javascript collects the unique domains from the page and consults with our API, that responds with a subset that can be monetized
* The javascript does page impression and link impression tracking
* We track both monetized and non monetized clicks 
* We have a bunch of inclusion / exclusion rules to enable our publishers to exclude / include certain sections / domains from monetization

Potential functionality for future AMP development: 

* Our "Skimwords" product is identifying product references in articles and converts them to links to the relevant product page on the retailer's side
* Our "Skimlinks Unlinked" product is identifying written, but not linked urls to retailers and converting them to links

Besides the above functionality requirements, based on the discussions with our Publishers, ease of implementation is critical, so we propose a single tag with optional attributes.

# amp-skimlinks
```
<amp-skimlinks
    data-publisher-id="1X2"  // skimlinks publisher id
    data-skimlinks="true"    // turn link monetization on / off
    data-tracking="true"     // turn tracking on / off
    data-skimwords="true"     // turn skimwords on / off
    ...
    />
```

**Comment by lepunk** [comment]
@jpettitt thank you for your comment

We've seen #9276 and considered it for a long while, unfortunately after discussing it with our publishers we had to realize that the approach outlined would restrict us in many ways. Most notably we wouldn't have control over including / excluding certain areas of the page.

As for design review: I agree we are committed to make this work up to AMP's standards and keeping in mind the core principles

Also Skimlinks is committed to comply 100% with GDPR so we will handle the interaction with amp-consent

**Comment by jpettitt** [comment]
@lepunk, that's good to hear.  The closer we can make this to a generic design with service specific code in a config the better, think `amp-ad` or `amp-analytics`.  This is also the direction we're going with video providing an extensible framework rather than completely custom code for each player.

Regarding areas of the page, could you just add a selector option to #9276 to limit the area?

**Comment by jpettitt** [comment]
@lepunk Are these reporting feature things that can't be done with `amp-analytics`?  There is a strong policy that all analytics providers us `amp-analytics` and if a feature is missing that it's added there.  You are highly unlikely get approval for a backdoor analytics service as part of your link rewrite module.

cc @cramforce

**Comment by cramforce** [comment]
What kind of data is being collected and upon which action is it being reported?

@zhouyx What is the status of extension analytics?

**Comment by lepunk** [comment]
@cramforce @jpettitt 
For the tracking request our `amp-skimlinks` extension would call `amp-analytics` [feasibility of this is being assessed atm by our team]. We are collecting data on the page itself (page url, title, etc.) and the links on the page. The tricky part however is some of the attributes we track on the link are dependent on the response of our "rewrite api" and / or custom attributes on the link itself populated by the publisher. This would require the "generic rewrite plugin" communicating with the `amp-analytics` and firing tracking request conditionally. Which would make the plugin not so generic

A dummy tracking payload would be something like:
```
{
  "page_url":"https://someurl.com",
  "title": "some title",
  "links": [{
    "url": "https://somemonetizablelink",
    "is_monetizable": true,
    "custom_tracking": "[some tracking id the publisher added to the link as a data attrib]"
  }]
}
```

**Comment by lepunk** [comment]
@zhouyx 
Our current js implementation follows this flow:
1. On page load the js collects all the unique, external domains on a page. Respecting include / exclude rules. Some of these rules are css selectors, some of them are list of domains set by the publishers, some of them are data attributes on each link. 
2. Hits our monetization API with the list of domains which replies with the ones that can be monetized
3. The JS attaches two separate click handlers to the monetizable and the non monetizable links
a) monetizable links: upon click we send the user through our redirect server where the click get monetized
b) non monetizable links: we fire an async tracking call to our tracking API while the user is sent to the original url
4. With the data from the monetization API our JS creates an impression object that contains info on the page and each link on the page (more or less as described in the json above). Important to note that this request contains information from the first api call, mixed with info on the page [some of which added by the publisher to each link]

For obvious reasons some of this is not possible in AMP (e.g.: we can't attach click handlers as far as I know)

**Comment by jpettitt** [comment]
Where does it get the rules in step 1 from? Are they in config on the page or do they come from your server (in the JS or in a separate call?)

**Comment by lepunk** [comment]
@jpettitt its a combination: we store settings on our server but publishers can decide to override them on the page itself

**Comment by jpettitt** [comment]
For clarity, if I'm following there are 3 transactions per page after your JS loads.

1. get the config
1. get the monetizable links
1. send async tracking call (if not a monetizable link)

Correct?

Another issue, do you think whatever you build will work with Safari 12?

**Comment by lepunk** [comment]
@jpettitt 
1. get the config (for AMP we are fine having the config hard-coded in the tag itself so this can be omitted)
2. get monetizable links
3. fire page impression / link impression tracking call
4. track clicks / monetizable, non monetizble on click

re: Safari 12
Are you referring to the "intelligent tracking prevention" changes? If so, yes we *think* we are fine as we are dealing in the 1st party context but our team is investigating the implications at the moment

**Comment by jpettitt** [comment]
OK that makes sense.  Are the non-link data fields you need to collect already supported in AMP URL substitution or by analytics?  If so you'll be able to either burn them into your endpoint url or call internal services to get the values. The idea being to avoid trying to parse things out of the page.

**Comment by lepunk** [comment]
@jpettitt I've had a quick skim through of the documentation (correct me if I'm wrong but i think you referred to this: https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md) and it looks like it covers every data point we need on the page level.

So that would leave us with a single scan through the links on the page, an api call to our monetization API, some link replacements and a tracking call

**Comment by jpettitt** [comment]
SGTM, once you have a design nailed please document it here add this issue to one of our [design reviews](https://github.com/ampproject/amphtml/issues?utf8=%E2%9C%93&q=label%3A%22Type%3A+Design+Review%22+) with a time that works best for you.

**Comment by lepunk** [comment]
@jpettitt thank you. our team is working on the design  doc as a priority, will update here shortly

**Comment by lepunk** [comment]
@jpettitt our team has finished the design doc. would you mind having a look and let us know what you think? thanks in advance

https://docs.google.com/document/d/10qEju2E3_c84W3ZPMjz8yGvMfFWwzSefnbMLPcC-vRs/edit

**Comment by cramforce** [comment]
Let me start by saying that I think this is an excellent and thoughtful design.

It does seem to me that this could be generified to something like `amp-affiliate-links` quite easily. Where a vendor configuration defines what URLs are contacted, etc. Besides that the design seems like it should apply similarly to all kinds of similar services.

**Comment by pbecotte** [comment]
I am the CTO at Narrativ, a company that offers similar services. If this could be made to be generic as suggested, we could make use of it as well (we were considering opening a similar issue when we came across this one). If it helps move things along, we would be capable of contributing engineering resources to this effort as well. The existing workflow in the design doc works the same way as ours, with a few minor differences that could easily be abstracted into a vendor specific module.

**Comment by choumx** [comment]
> The existing workflow in the design doc works the same way as ours, with a few minor differences that could easily be abstracted into a vendor specific module.

A generic extension would be great. Can you elaborate on these differences?

**Comment by pbecotte** [comment]
The difference is that our tag works on whole urls instead of just the advertiser domain, so we need to submit both http://merch1.com/producta and http://merch1.com/productb to the api and update the links accordingly (and of course, the API address and the fields for impression tracking are slightly different)

**Comment by choumx** [comment]
@pbecotte Are you still interested in supporting your service in AMP? The skimlinks engs already have a good pull request for `amp-skimlinks` extension that's about ready to be merged.

**Comment by pbecotte** [comment]
Interesting @choumx I would - Didn't realize the work started, didn't see any more action here :) Will look over their solution this week, thanks for the heads up!

**Comment by c-nichols** [comment]
Hi @choumx, I am a coworker of @pbecotte's.  We've spent some time looking over `amp-skimlinks` (nice work all).  We think the best way forward, especially now that the extension is merged, is to implement our own extension, and look for common behavior to consolidate once the two extensions are up.  If that sounds reasonable to you, we will start the process this week (beginning with an i2i issue I believe?) and go from there.

**Comment by choumx** [comment]
Sounds good.

**Comment by choumx** [comment]
Closing since amp-skimlinks is now available.
