### ISSUE TITLE
Give an option to get rid of top shadow

### ISSUE THREAD

**Issue by psdtomanythings** [ampproject/amphtml#16458]
We recently built a story and the top shadow is kind of distractive. Having a class option of no-shadow will be helpful. Just add the class no-shadow to amp-story tag and the whole top inset drop shadow will be gone.

**Comment by newmuis** [comment]
I think this will be tricky, since the top gradient is the only thing that ensures the system icons are visible.

/cc @hongwei1990

**Comment by newmuis** [comment]
This is necessary to ensure that the story UI chrome remains accessible even in the worst case.  I don't think this can be removed.
