### ISSUE TITLE
Multiple submit buttons in amp-form

### ISSUE THREAD

**Issue by fstanis** [ampproject/amphtml#16461]
## What's the issue?

-   Using `<form>` with the `action-xhr` attribute ignores `name` (and `value`) of `<input type="submit">`
-   `formaction` attribute is not allowed

This makes it difficult to build forms with more than one submit button (one example is a dialog with a "Yes"/"No" question where both options should result in a POST).

## How do we reproduce the issue?

```html
<form method="get" action="submit" target="_top">
  <fieldset>
    <input type="hidden" name="id" value="abc">
    <input type="submit" name="decision" value="Yes">
    <input type="submit" name="decision" value="No">
  </fieldset>
</form>
```
Pressing "Yes" correctly makes a request to `submit?id=abc&decision=Yes`

```html
<form method="get" action-xhr="submit">
  <fieldset>
    <input type="hidden" name="id" value="abc">
    <input type="submit" name="decision" value="Yes">
    <input type="submit" name="decision" value="No">
  </fieldset>
</form>
```

Pressing "Yes" makes a request to `submit?id=abc` (the `decision` parameter is not present). Same applies for POST forms.

## Which AMP version is affected?

AMP version 1530043289240

## Proposal

I think the discrepancy between `action` and `action-xhr` can be considered a bug, so perhaps short-term just disallowing the `name` attribute on `<input type="submit">` makes sense.

That said, would be good to allow for multiple submit buttons, since that would make some use-cases easier to do with forms, e.g. rating and prompts to approve / reject things.

**Comment by aghassemi** [comment]
/to @cvializ 

Dup of https://github.com/ampproject/amphtml/issues/15919 (closing the other one since this is more detailed.).

Given few reports of this recently setting as P2.
