### ISSUE TITLE
Viewer does not provide cap=cid

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#16473]
```
ta@https://cdn.ampproject.org/rtv/031530043289240/v0.js:8:169
f.Ga@https://cdn.ampproject.org/rtv/031530043289240/v0.js:3:192
f.expectedError@https://cdn.ampproject.org/rtv/031530043289240/v0.js:3:406
Li/<@https://cdn.ampproject.org/rtv/031530043289240/v0.js:285:85
```

This is now the largest error, with some 260k reports in the last 12 hours.

**Comment by lannka** [comment]
This is an expected error. 

```
dev().expectedError('CID', 'Viewer does not provide cap=cid');
```

Not sure why it shows up in the bug report. It is there to track if all Viewers have migrated over.

**Comment by jridgewell** [comment]
Expected errors aren't throttled any more than regular errors, they're just sent to a different bucket. So the question is how many millions of AMP pages are loaded with a non-capable viewer?

If this is necessary for metrics, maybe CSI would be better.

As it is, it's noisy and isn't actually an error.

**Comment by lannka** [comment]
So what does expectedError exist for? CSI is mainly for latency report, and will be not ideal for this kind of purpose.

Preventing the noise was exactly the reason why we put them in a separate bucket.
