### ISSUE TITLE
iframe origin policy link is 404

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#1647]
https://github.com/ampproject/amphtml/blob/spec/amp-iframe-origin-policy.md is 404 - linked from https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md

link should be https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md

**Comment by rudygalfi** [comment]
cc @Meggin @cramforce @adewale
