### ISSUE TITLE
AMP Story jumping 2 slides while using AMP Ad Auto Start

### ISSUE THREAD

**Issue by psdtomanythings** [ampproject/amphtml#16489]
The story marker at the top is jumping by 2 positions while the story slide changes by just one. Check attached video for the same. 

![ezgif-2-554b13f344](https://user-images.githubusercontent.com/22929187/42121606-f842adfc-7c4f-11e8-862a-9e1f85636864.gif)

**Comment by newmuis** [comment]
This is a duplicate of #14635.

It's not limited to amp-story-auto-ads, and no pages are actually skipped, it's just a confusing UI paradigm.  We have a fix in mind that will hopefully resolve that confusion.
