### ISSUE TITLE
built in elements can run before extension service is instantiated

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#16485]
`amp.js` calls `installBuiltins()` before it calls `adopt()`.  If a built in element tries to use a service provided by an extension, for example `amp-consent` it will fail in `waitForExtensionIfPresent()` due to extension service is not being instantiated until `adopt()` is called.

Fixed in #16484

**Comment by jridgewell** [comment]
Dupe of https://github.com/ampproject/amphtml/issues/15759.

Sorry, meant if you could file an issue for an "AMP is ready" promise.
