### ISSUE TITLE
Better way to use amp-sidebar and multiple menu layers

### ISSUE THREAD

**Issue by tewdin** [ampproject/amphtml#16496]
I really like AMP HTML and want to do full AMP HTML web stores and websites, but there is no good way to make normal menus without doing menu items twice. I don't like doing things twice if I can do it simple. Normally, companies do not want menu button to desktop version, but visible menu with multiple layers.

So, there is two problems:
- Amp-sidebar should be visible if needed without pressing button
---- Need to also open/close with button
- Better way to show multiple layers: I can do it now with amp-sidebar + amp-selector
---- Should be automatic system for menu layers like slimMenu does.

**Comment by jpettitt** [comment]
`amp-bind` gives you a way of adding / removing aritary CSS classes based on user interaction, you can then use media queries to hide the button and show the menu.  It will also let you create more complex structures like nested menus.
