### ISSUE TITLE
Ads and video support for amp-lightbox-gallery

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#16505]
Follow up on the initial launch for amp-lightbox-gallery with basic support for video and the highly-requested feature of ads support inside the lightbox view

**Comment by rickbairstow** [comment]
This would be a great feature to have! Especially for ecommerce where a product carousel might be used to display image and video content, such as this example: https://codepen.io/RickRX/pen/PoqmdKm
