### ISSUE TITLE
Should the 'role' attribute be allowed on AMP?

### ISSUE THREAD

**Issue by AndrewKGuan** [ampproject/amphtml#16510]
Right now if someone tries to add the 'role' attribute on AMP for  ARIA 1.0, it'd fail validation:
<input name="quantity" type="number" **role="textbox"** class="quantity"  maxlength="2" />
Should it be allowed?

**Comment by cathyxz** [comment]
I believe this is whitelisted under global attributes, as well as individually for the `<a>` tag and `<button>` tag, but for some reason not whitelisted for `<input>`. 
https://github.com/ampproject/amphtml/blob/bbf2aca64c2ca1fe4eca03b00adcb566d5389ff8/validator/validator-main.protoascii#L3524

@honeybadgerdontcare do you know why?

**Comment by honeybadgerdontcare** [comment]
`role=` is whitelisted and validates. @AndrewKGuan could you give a code sample where this is failing validation?

closing till an example shows it failing.
