### ISSUE TITLE
Add video analytics for amp-video to amp-analytics

### ISSUE THREAD

**Issue by TomMSNBC** [ampproject/amphtml#1654]
Please add the following events:
- Video Start
- 25%/50%/75% Video Complete
- Video Complete 
- Video Scrub
- Video Pause

**Comment by rudygalfi** [comment]
cc @avimehta

**Comment by ThomasPaq** [comment]
Hello,
As Médiamétrie company, we also need this events to send hits with amp-analytics on amp-video events.
In addition we need to get the following video information :
 - duration
 - state
 - position
The goal is to set this information in the hits sent by amp-analytics.

**Comment by ericlindley-g** [comment]
Rolling into the next milestone

**Comment by adelinamart** [comment]
Is this still relevant?

**Comment by aghassemi** [comment]
Design: #9902

**Comment by rudygalfi** [comment]
@aghassemi I'd suggest closing this because we have #9902, but defer to you in case you're using this issue in any tracking.

**Comment by aghassemi** [comment]
yeah let's close in favor of  #9902
