### ISSUE TITLE
Add PAUSED VisibilityState

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#1655]
Viewer will be sending down a `PAUSED` VisibliityState whenever a swipe begins. After the swipe ends, if the same document is still shown, it'll be made `VISIBLE` again.

**Comment by rudygalfi** [comment]
This is overdue on the Feb 19 milestone. Any update?

**Comment by jridgewell** [comment]
Currently working on it. Looks like we're going to ship the first portion late this week, with the actual resource management (pausing, resuming) next week.

**Comment by dvoytenko** [comment]
So, we discussed today. This is definitely post launch thing. Right away, but after launch.
