### ISSUE TITLE
Fixed position banner is sometimes rendered out of the viewport

### ISSUE THREAD

**Issue by juliacochran** [ampproject/amphtml#16554]
## What's the issue?

Our banner that is fixed to the bottom of the screen (`position:fixed, bottom: 0px`) is sometimes rendered fully or halfway out of the viewport. Both issues can be "fixed" by scrolling to the bottom of the page and swiping down, as if you were doing a pull-to-refresh motion on the bottom of the screen. 

![img_4233](https://user-images.githubusercontent.com/3277587/42243712-1fb5b220-7ec7-11e8-931f-fa99042941e4.PNG)

Here are a few videos that demonstrate the issue to help in case you are unable to reproduce:

- [Banner rendering partially out of the viewport](https://drive.google.com/file/d/1eJoqn_v_yM1H_oMETp7mjZOYFqdO0jOI/view?usp=sharing)
- [Banner rendering fully out of the viewport](https://drive.google.com/file/d/1wxHpRE0TFhD-4uFDDkX5QA5sXpTDqlKf/view?usp=sharing)
- [Swiping through AMP pages that all have partially obstructed banner](https://drive.google.com/file/d/1X8jTC18lPMKJ_Y6PDjd8XKB_X4K7JCa1/view?usp=sharing)

## How do we reproduce the issue?
_This issue is most easily reproducible on an actual phone, rather than by emulating a device in Chrome dev tools._ 

1. Make sure you are logged out of Pinterest by going to www.pinterest.com/logout
2. Visit https://www.google.com/amp/s/www.pinterest.com/amp/pin/27866091429714425/ to see halfway out example
3. Visit https://www.google.com/amp/s/www.pinterest.com/amp/pin/5840674496841567/ to see fully out example

Expected result: Black banner at the bottom is fully visible
Actual result: Black banner is halfway or fully hidden and obstructed by the view port

## What browsers are affected?

Chrome v67.0.3396.87 and Firefox v12.1 (10941) are affected. Safari does not appear to be. Have not tried other versions of Chrome/Firefox.

Reproducible on iPhone X and iPhone 6s. Have not tried other devices.

## Which AMP version is affected?

Unable to tell at this time, since I can only repro on a phone.

**Comment by ericlindley-g** [comment]
@jridgewell Just wanted to check in on this — has anyone been able to take a look at why this is happening?

**Comment by ericlindley-g** [comment]
Checking in: @choumx @jridgewell , is this slated for a specific sprint?

**Comment by ericlindley-g** [comment]
Checking on this one, too— is it related to https://github.com/ampproject/amphtml/issues/16933#issuecomment-413715614 as well?

**Comment by choumx** [comment]
I think so.
