### ISSUE TITLE
Using on-action syntax in amp-date-countdown results in "insufficient trust"

### ISSUE THREAD

**Issue by micyeung** [ampproject/amphtml#16567]
## What's the issue?
Running the following code:
```    
<amp-date-countdown 
  on="timeout: AMP.setState({foo: 'bar'});" 
  end-date="2017-07-04T16:46:00+08:00" 
  when-ended="stop"> 

</amp-date-countdown>
```

or on simpler on-syntax action like
```    
<amp-date-countdown 
  on="timeout: mydiv.show;" 
  end-date="2017-07-04T16:46:00+08:00" 
  when-ended="stop"> 

</amp-date-countdown>
```

results in the following error, contrary to the [documentation](https://github.com/ampproject/amphtml/blob/master/extensions/amp-date-countdown/amp-date-countdown.md):
```
Insufficient trust for "setState" (1 < 100).
```

However, there is no error when the on-syntax action is done with an `amp-animation`, like `on="timeout: anim.start;"`

## What browsers are affected?

All browsers

## Which AMP version is affected?
Found in 1530567757224

**Comment by leonalicious** [comment]
Please refer to https://github.com/ampproject/amphtml/pull/13657#pullrequestreview-101786630 for more informations

**Comment by choumx** [comment]
`AMP.setState` requires a user action to be triggered. We probably should have a more useful error message.

**Comment by choumx** [comment]
@micyeung @leonalicious Can you describe your intended use case?

**Comment by aghassemi** [comment]
@micyeung You can use `amp-animation` to hide and show sections of the page based on the timeout. https://github.com/ampproject/amphtml/blob/master/examples/amp-date-countdown.amp.html has an example for that.
