### ISSUE TITLE
Add poster frame support to amp-youtube

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1656]
Youtube has an API for retrieving a poster frame. The URL is like this: `http://img.youtube.com/vi/{{ videoId }}/maxresdefault.jpg`

If AMP is in prerender mode, we currently don't render YT embeds. We should render the poster frame instead.

You can do that by implementing

```js
/** @override */
    prerenderAllowed() {
      return true;
    }
```

in amp-youtube and then returning true from `layoutCallback` if only the poster frame was added. When the user goes to the page, `layoutCallback` should then be called again (I think :).

**Comment by jridgewell** [comment]
Related to https://github.com/ampproject/amphtml/issues/1175?

**Comment by cramforce** [comment]
@jridgewell Yeah, I knew I had it already, but didn't find it :)

**Comment by cramforce** [comment]
Lets do #1657 first, though. They are very similar.

**Comment by mkhatib** [comment]
@cramforce what do you mean by "if only the poster frame was added"? Do we expect the users to manually add `amp-img` for the `amp-youtube` or do we automatically add that for them?

I've just sent #1718 PR for addressing #1657 - If I am to follow the same logic there I'd probably check if we're in `prerender` mode and insert an image (or an amp-img) and return from layoutCallback before inserting the iframe. Does that make sense or am I missing something?

**Comment by dvoytenko** [comment]
I'd assume we can just add one ourselves - no need for "poster" attribute or "amp-img" tag set manually.

**Comment by cramforce** [comment]
@mkhatib Yes, the logic is the same. The main difference is that we can compute the URL ourselves, so there is no need for an additional attribute.
