### ISSUE TITLE
Date picker launched, but requires enable experiment

### ISSUE THREAD

**Issue by minhruhr** [ampproject/amphtml#16568]
## What's the issue?

amp-date-picker was announced launched on 29th june, but still requires dev-experiment to be enabled

## How do we reproduce the issue?
- add <amp-date-picker> tag to an amp page.
- console will show "Experiment amp-date-picker is disabled."

## What browsers are affected?
All browsers

## Which AMP version is affected?
Version 1530567757224

**Comment by aghassemi** [comment]
This should be fine now.
