### ISSUE TITLE
Add support for G+ and Google my Business embeds.

### ISSUE THREAD

**Issue by 88kbbq** [ampproject/amphtml#16578]
The title pretty much sums it up. Our business does not do business with Facebook anymore, so we need a social alternative. Google my Business, Google+? Aren't you guys working for Google? Where's the love?

**Comment by alanorozco** [comment]
Hi @88kbbq 

Could you specify the plugin you're mentioning?

**Comment by 88kbbq** [comment]
A plugin for Google+ or Google my Business that shows posts, plus ones, reviews, etc. You have three plugins for Facebook... just sayin’

Kevin Woolf | 陳楷汶
執行長｜暨主廚
犇火燻寶有限公司
統一編號：53523822
公司地址：104台北市中山區吉林路161巷14號1樓
公司電話：+886-800-887-427
行動電話：+886-988-575-319
www.88k.com.tw

支票抬頭：犇火燻寶有限公司 | Baba Kevin’s American Barbecue Co., Ltd.
收款戶名：犇火燻寶有限公司 | Baba Kevin’s American Barbecue Co., Ltd.
銀行地址：第一銀行松江分行#146  104台北市松江路309號
銀行代號： 007
帳號：          146-10-059835
服務電話： +886-2-2501-7171
傳真電話： +886-2-2507-7263


1.	收付訂金後，訂單立即生效，貴公司同意下述的條件。Deposit remittance implies acceptance of Baba Kevin’s American Barbecue Co., Ltd. terms and conditions.
2.	開立貴公司統編的三聯發票依政府規定，金額需加5%稅後為總金額。A 5% corporate tax will be added when issuing a Taiwan company receipt.
3.	請於活動預約確認後一週內預付總金額50%為保證金，尾款需於活動當天結算，雙方書面協議尾款結算方式另議則不在此限。All reservations require a 50% deposit within 7 days after event confirmation. The remaining invoiced amount must be paid in full on the day of the event unless previous arrangements have been approved in writing.
4.	外燴活動請貴公司主動提供：穩定110伏12安培電源，車輛行進路線及停放位置，大型烤爐放置位置（從卡車到活動場地如地面不平或沒有電梯，請務必先行告知，或安排貴公司人力支援），乾淨自來水源。Event holder must supply a stable 110V 12AMP electrical power source; accurate location, setting, and parking instructions; adequate access and assistance for commercial equipment loading, positioning, and unloading; and potable water supply.
5.	如因為不可抗的天氣因素取消活動，可接受活動三天前通知延期，超過三天期限才取消活動，訂金將不予退還。Cancelations three calendar days or more from scheduled event may be rescheduled. Cancelations less than three days (72 hours) from scheduled event will result in forfeiture of deposit. All deposits are non-refundable.
6.	本公司有選擇接受履行訂單與否的權力。Baba Kevin’s American Barbecue Co., Ltd. reserves the right to refuse any service request for any reason.

Sent from my iPhone

On Jul 7, 2018, at 6:37 AM, Alan Orozco <notifications@github.com> wrote:

Hi @88kbbq

Could you specify the plugin you're mentioning?

**Comment by sparhami** [comment]
Since the consumer version of [Google+ is being sunset](https://www.blog.google/technology/safety-security/project-strobe/), I'm not sure it makes sense to implement this anymore.

**Comment by alanorozco** [comment]
Maybe for GMB it would make sense but I don't know off the top of my head what's available to embed.

**Comment by 88kbbq** [comment]
Posts, reviews, business info, customer photos
