### ISSUE TITLE
No images without Javascript

### ISSUE THREAD

**Issue by tewdin** [ampproject/amphtml#16585]
Images are loaded only if Javascript is enabled and there are no image tags without it. There should be way to show images without Javascript. Even for mobile only this is bad, because images can be very important content.

**Comment by antejan** [comment]
Hey! Just found that you can use `<img>` within `<noscript>` tag to provide fallback in such case and it doesn't fail AMP validation.

```
<amp-img src="/img/amp.jpg" alt="AMP" width="475" height="268" layout="responsive">
  <noscript>
    <img src="/img/amp.jpg" width="475" height="268" alt="AMP"> 
  </noscript>
</amp-img>
```

https://ampbyexample.com/components/amp-img/

**Comment by jridgewell** [comment]
Correct, the supported way is to use a `<noscript>` tags which allow normal elements like `<img>`.
