### ISSUE TITLE
Add ability to turn off validation when in Developer Mode

### ISSUE THREAD

**Issue by raywainman** [ampproject/amphtml#16595]
## What's the issue?

It would be great to have a way to turn off the validation that happens in `src/validator-integration.js` when developer mode is turned ON. Currently this code attempts to fetch content from a URL to perform validation. When the AMP content is not actually available at the endpoint, multiple errors can be seen in the browser console.

Perhaps there could be a new viewer capability or flag that would allow bypassing of validation in developer mode.

/cc @zhangsu

**Comment by choumx** [comment]
Checking for something like `#validate=0` in mode.js and validator-integration.js should work.
