### ISSUE TITLE
amp-carousel: Support RTL

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#16605]

**Comment by nainar** [comment]
Could you elaborate? Right to left ...?

**Comment by aghassemi** [comment]
Yep, if we set dir= rtl on body, bunch of things should flip but carousel needs extra fixes. Next prev icons need to flip, last slide becomes first slide, loop autoplay should play backwards.

**Comment by mofidsky** [comment]
also the carousel images will not load if the direction is set to "rtl" 
here is a screenshot from my project, surprisingly i have set the direction in the chrome developer tools and the images that were loaded before in not shown any more.
![untitled](https://user-images.githubusercontent.com/41105577/42556035-89fde04c-84ff-11e8-933c-f3096bb117eb.png)

**Comment by aghassemi** [comment]
to be verified in carousel v2

**Comment by stoneshower** [comment]
Hello, let me ask you about the situation since I need to the feature for my page. 
Does amp-carousel already support RTL, if so if there a documentation how to implement?
Or is the feature under development?
Thank you in advance :)

**Comment by sparhami** [comment]
> Hello, let me ask you about the situation since I also need this feature for my project.
Does amp-carousel already support RTL, if so if there a documentation how to implement?
Or is the feature under development?
Thank you in advance :)

amp-carousel currently has a few issues in RTL mode (see https://github.com/ampproject/amphtml/issues/16605#issuecomment-403974974 above) . We are working on releasing a version 0.2 that will fix those issues.

**Comment by nainar** [comment]
Confirmed that this works with v0.2 but not 0.1

Check in amp.dev playground by adding `dir="rtl"` to a carousel
