### ISSUE TITLE
amp-lightbox-gallery does not work in viewer

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#16608]
To repro: search for AMP Lightbox Gallery, and hit the ABE page in the Search Viewer.

/to @cathyxz I am not sure if a regression or not, if regression, please treat a P0.

**Comment by cathyxz** [comment]
Repros on cached amp pages regardless of viewer. 
https://ampbyexample-com.cdn.ampproject.org/v/s/ampbyexample.com/components/amp-lightbox-gallery
