### ISSUE TITLE
amp-video: fullscreen has a blank bottom margin in Chrome Andorid

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#16607]
Using the native "fullscreen" button on `amp-video`, there is a blank bottom margin:

![yd0oh17hnun](https://user-images.githubusercontent.com/2099009/42422674-3b5fac48-829f-11e8-87f2-0e49d5fac656.png)

reproducible on ABE. 

/to @alanorozco

**Comment by alanorozco** [comment]
Chrome bug, fixed in latest Canary.
