### ISSUE TITLE
amp-youtube (possibly other 3P players) do not show the equalizer animation anymore in autoplay

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#16606]
/to @alanorozco

**Comment by alanorozco** [comment]
Caused when `controls` attribute is not set.

This could change semantics somewhat, but we can add a rule so that it's shown for all 3p players  without `controls` set.

Something like

```css
amp-video[controls] .amp-video-eq,
.i-amphtml-video-component:not(amp-video) .amp-video-eq,
amp-story .amp-video-eq
```

WDYT @aghassemi?
