### ISSUE TITLE
AMP Validation errors showing in Google Debug console

### ISSUE THREAD

**Issue by jattsaini** [ampproject/amphtml#1660]
My site is: timesnews.co.uk
I got following two errors in this page: http://www.timesnews.co.uk/7733-blackberry-priv-launched-in-india-for-crazy-926-price-tag/amp/#development=1

The errors are:

> http://www.timesnews.co.uk/7733-blackberry-priv-launched-in-india-for-crazy-926-price-tag/amp/:242:60 The attribute 'rel' in tag 'a' is set to the invalid value 'attachment wp-att-6306'
> validator.js:248 http://www.timesnews.co.uk/7733-blackberry-priv-launched-in-india-for-crazy-926-price-tag/amp/:244:60 The attribute 'rel' in tag 'a' is set to the invalid value 'attachment wp-att-6307

**Comment by mjangda** [comment]
Just pushed a fix for this in the WordPress plugin: https://github.com/Automattic/amp-wp/pull/151

**Comment by jattsaini** [comment]
Thanks will apply it and update the results here...asap

**Comment by jattsaini** [comment]
How to apply the fix in the plugin?

**Comment by rudygalfi** [comment]
Closing this in deference to Automattic/amp-wp#151 resolving this.
