### ISSUE TITLE
amp-facebook loading issues

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#16611]
Per https://github.com/ampproject/amp-by-example/issues/1066#issuecomment-365276447, amp-facebook has comment overflow issues on Android on Firefox.

On iOS Firefox, amp-facebook isn't loading at all for me.

**Comment by nainar** [comment]
Can't repro the issue on Firefox on Android. 
**Taken on a Pixel 2 - Firefox version 61 on Oreo.** 
![screenshot_20180717-111058](https://user-images.githubusercontent.com/7919520/42837236-54f1c104-89b2-11e8-8273-520279d14294.png)

On iOS though, below are screenshots taken on 
**Safari**
![safari](https://user-images.githubusercontent.com/7919520/42839211-d717bd0a-89b7-11e8-9f3b-14e2eddd6148.jpg)
**Firefox**
![firefox](https://user-images.githubusercontent.com/7919520/42839216-da5e15f4-89b7-11e8-907e-8f2863085429.jpg)

**Comment by ericlindley-g** [comment]
@nainar Thanks for trying to repro (possibly got fixed by some other change in the meantime) — maybe we can table the Android issue for now until we can repro, and focus on the iOS issue instead?

**Comment by nainar** [comment]
Yup - I currently don't have an iOS device handy, so I will take a look at this tomorrow as part of the fixit.

**Comment by SchnWalter** [comment]
In Chrome beta `Version 69.0.3497.23 (Official Build) beta (64-bit)`, you not only have cropping issues on the right side, you also have issues with cropping on scroll:

![screenshot_20180806_104824](https://user-images.githubusercontent.com/2186426/43703692-45c0de54-9966-11e8-98a1-a1625d3c1227.png)

Example HTML file: [facebook-embed-issue.zip](https://github.com/ampproject/amphtml/files/2261600/facebook-embed-issue.zip)

**Comment by nainar** [comment]
Hi @SchnWalter could you describe what OS you are using here?

**Comment by orballo** [comment]
Hi there!

I've also got problems with `amp-facebook`. I'm currently using Chrome `Version 68.0.3440.84 (Official Build) (64-bit)`.

However, I think the overflow problem is a Facebook thing. In these docs (https://developers.facebook.com/docs/plugins/embedded-posts/?locale=en_US) they say that the minimum width an embedded post can have is `350px`.
![screenshot 2018-08-08 07 45 14](https://user-images.githubusercontent.com/13615057/43818470-2720ef00-9adf-11e8-9b8f-342055c7989e.png)

The problem I found is that when I'm in devtools emulating mobile the embedded videos won't load.

![screenshot 2018-08-08 07 42 13](https://user-images.githubusercontent.com/13615057/43818628-c99a2d8c-9adf-11e8-9130-703504e2f251.png)
![screenshot 2018-08-08 07 41 58](https://user-images.githubusercontent.com/13615057/43818710-23eba2ac-9ae0-11e8-945f-d67b771a8885.png)

Hope this helps!

**Comment by SchnWalter** [comment]
I'm using Debian 9, Stretch, and this issue shows up only in Google Chrome Beta (`Version 69.0.3497.23 (Official Build) beta (64-bit)`).

And... it also affects the `amp-ad` tags, but not on other tags that I've checked (`amp-iframe`, `amp-image`, `amp-instagram`, `amp-twitter`, `amp-vimeo` or  `amp-youtube`).

**Comment by nainar** [comment]
Definitely a Facebook bug, https://developers.facebook.com/docs/plugins/embedded-posts/?locale=en_US has this problem too:
<img width="357" alt="screen shot 2018-08-10 at 2 09 35 pm" src="https://user-images.githubusercontent.com/7919520/43981844-6efaa684-9ca8-11e8-8e00-7124bbafeb81.png">
