### ISSUE TITLE
amp-date-picker methods today, startToday, endToday not found

### ISSUE THREAD

**Issue by ro2ni3** [ampproject/amphtml#16614]
## What's the issue?

With the following buttons:
```
<button on="tap: date-picker.today">Today</button>
<button on="tap: date-picker.today(offset=14)">Two Weeks time</button>
<button on="tap:date-picker.startToday(offset=7), date-picker.endToday(offset=14)">Next week</button>

```
when pressed, an error is thrown saying that the method today, startDate or endDate are not found.

## How do we reproduce the issue?

```
<button on="tap: date-picker.today">Today</button>
<button on="tap: date-picker.today(offset=14)">Two Weeks time</button>
<button on="tap:date-picker.startToday(offset=7), date-picker.endToday(offset=14)">Next week</button>

<amp-date-picker id="date-picker" locale="en" type="single" mode="overlay" layout="container" on="select:AMP.setState({date1: event.date, dateType1: event.id})"
                    format="DD MMM YY" open-after-select input-selector="[name=date1]" class="example-picker space-between" number-of-months="1">
                    <div class="ampstart-input">
                        <input class="border-none p0" name="date1" placeholder="Pick a date" on="tap:date-picker.today(offset=14)" readonly>
                    </div>
                    <template type="amp-mustache" info-template>
                        <span [text]="date1 != null ? 'You picked ' + date1 + '.' : 'You will see your chosen date here.'">You will see your chosen date here.</span>
                    </template>
</amp-date-picker>
```
[JSBin](https://jsbin.com/xomodezuma/edit?html,css,console,output)

Steps:
1. With the console open, click either Today, Two Weeks Time or Next Week.
2. The console will show these errors: "Method not found: today in ", "Method not found: startToday in ", "Method not found: endToday in " respectively

In firefox you will see:

`Uncaught Error: Action execution failed: AMP-DATE-PICKER today: Method not found: today in [object Object]​​​
`
`Uncaught Error: Action execution failed: AMP-DATE-PICKER endToday: Method not found: endToday in [object Object]​​​
`
`Uncaught Error: Action execution failed: AMP-DATE-PICKER startToday: Method not found: startToday in [object Object]​​​`

## What browsers are affected?

Firefox Quantum 61.0.1 (64-bit) on a Mac
Google Chrome Version 67.0.3396.99 (Official Build) (64-bit) on a Mac

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1530567757224

**Comment by aghassemi** [comment]
@ro2ni3 Seems to work for me: https://codepen.io/aghassemi/pen/bjGMYL?editors=1111 
Unrelated, you page was not valid AMP, missing `<html ⚡>`

Anyway, could you please take a look at my CodePen and see if it is working for you?

**Comment by ro2ni3** [comment]
Yes it has magically started working now. Both your codepen and my JSBin example that I linked above are now working. The site I am working on suddenly started working too, so good news. Nevermind, thanks very much for your reply.

**Comment by ro2ni3** [comment]
Sorry to reopen this issue but just this morning without having changed anything on my project, the amp-date-picker stopped working again. I checked both my [JSBin](https://jsbin.com/xomodezuma/edit?html,css,console,output) and your [CodePen](https://codepen.io/aghassemi/pen/bjGMYL?editors=1111) examples and I noticed they have also stopped working.
Here is proof of it in case it starts working again:

![screen shot 2018-07-12 at 10 15 28](https://user-images.githubusercontent.com/32260852/42624189-b35eec8e-85bc-11e8-8f2f-1d6b3c2d1b16.png)

![screen shot 2018-07-12 at 10 09 06](https://user-images.githubusercontent.com/32260852/42623879-edc4a450-85bb-11e8-90ee-14a89d6a791d.png)

**Comment by jasonconway-williams** [comment]
Any update on this issue. I am having the same problem. @aghassemi, your codepen is also broken.

**Comment by aghassemi** [comment]
@jasonconway-williams Last week we had an issue and need to roll back the production release. 

This is fixed in current Canary Dev Channel ( https://cdn.ampproject.org/experiments.html ) which will become production release by Wednesday this week. 

Sorry about the inconvenience.

**Comment by aghassemi** [comment]
Closing since it is release related and fixed in latest Dev Channel.

**Comment by aghassemi** [comment]
@jasonconway-williams @ro2ni3 Just an FYI that AMP's prod release likely won't happen this week as well so please plan for after July 25th production hit.

**Comment by jasonconway-williams** [comment]
Thanks @aghassemi
