### ISSUE TITLE
[Firefox / Android] amp-form[type=select] does not work

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#16613]
original issue: https://github.com/ampproject/amp-by-example/issues/1082

**Comment by sparhami** [comment]
I'll take a look at this.

**Comment by sparhami** [comment]
I can't reproduce the original issue on Firefox 61 (Android or Linux), or Firefox 52 (Linux). This could have been fixed at some point since the original issue was created by another change or could be related to the browser version (I think this is less likely).
