### ISSUE TITLE
Verify and clarify docs around removal of amp-img srcset polyfill

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#16625]
Follow up to https://github.com/ampproject/amphtml/pull/16404.

**Comment by bpaduch** [comment]
I've reviewed the docs (particularly the [Create responsive AMP pages guide](https://www.ampproject.org/docs/design/responsive/responsive_design#displaying-responsive-images), and there's no other impacts.  As you said in [this comment](https://github.com/ampproject/amphtml/pull/16404#issuecomment-401430462), the docs were accurate but the implementation wasn't.
