### ISSUE TITLE
validation error for cloudflare ssl and e-mail obfuscation

### ISSUE THREAD

**Issue by bcko** [ampproject/amphtml#1662]
Hello, the website is www.drjongchoi.com
I am currently using Cloudflare SSL and e-mail obfuscation feature. 
However, www.drjongchoi.com#development=1 gives me a validation error since Cloudflare inserts script to the page. 
What would be the best way to resolve this? 
I appreciate your help!

**Comment by cramforce** [comment]
@jmadler Do you know someone at cloudflare we could talk to?

**Comment by rudygalfi** [comment]
@bcko If you haven't already done so, please get in touch with the support team at Cloudflare to let them know your issue.

**Comment by bcko** [comment]
Hello @rudygalfi, 
What would be the best way to address my issue to the support team? If they don't insert their script to the page, they would not be able to offer their service. 
Is there anyway for the AMPhtml to put Cloudflare script to validation rule.

**Comment by rudygalfi** [comment]
Please explain the issue to them and you can make reference to this discussion.

Running the Cloudflare script on the AMP page directly is not an option. There may be alternatives if they are willing to engage here to explore them.
