### ISSUE TITLE
Unwanted border around amp-story-page in desktop view

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#16626]
Sometimes when viewing an amp-story in desktop view, there is a border around the content.

![screen shot 2018-07-09 at 2 18 16 pm](https://user-images.githubusercontent.com/5449100/42468533-2d1fe3a2-8383-11e8-86de-63e01ec108d0.png)

**Comment by newmuis** [comment]
Seems like a good candidate for the fixit list!

**Comment by gmajoulet** [comment]
Borders are still visible on some stories.

**Comment by gmajoulet** [comment]
I found various chromium tickets but it looks like it won't be fixed, eg: https://bugs.chromium.org/p/chromium/issues/detail?id=600120

What we could try is making sure the width is always rounded in CSS pixels, using some JavaScript.
