### ISSUE TITLE
Support multilingual webpage <link rel="alternate" hreflang="ko" href=... >

### ISSUE THREAD

**Issue by bcko** [ampproject/amphtml#1664]
hello, 
the website is www.drjongchoi.com 
this website is in both English and Korean so I set 

```
<link rel="alternate" hreflang="en" href="https://www.drjongchoi.com" />
<link rel="alternate" hreflang="ko" href="https://www.drjongchoi.com/ko_index.html" />
```

However I get a validation error saying 

> The attribute 'rel' in tag 'link rel=canonical' is set to the invalid value 'alternate'

what would be a good way to create a multilingual website with AMP integrated?
thank you!

**Comment by cramforce** [comment]
Yeah, it should validate.

**Comment by Gregable** [comment]
rel="alternate" is supported, the validator is getting confused about the hreflang, which is not currently but should be. Should be a quick fix to the validator. Thanks for the report!

**Comment by jridgewell** [comment]
@Gregable: Should this be kept open until the validator is fixed?

**Comment by dvoytenko** [comment]
Agreed. Let's keep open until it's fixed. I updated the title.

**Comment by Gregable** [comment]
Yes, sorry, I clicked the wrong comment button.

**Comment by Gregable** [comment]
This is now fixed in javascript. It may take a day or so to work in the amp cache though.

**Comment by Txooz** [comment]
Hello,

I'm confused about AMP and Hreflang. The hreflangs in the AMP version have to point to the other AMP versions or have to point to the regular version as the canonical?
