### ISSUE TITLE
Experiment amp-next-page disabled when the page is served both from Google's cache & Own Domain

### ISSUE THREAD

**Issue by prash-mi** [ampproject/amphtml#16644]
amp-next-page is throwing 'Experiment amp-next-page disabled' error for the page https://www.google.com.sg/amp/s/m.timesofindia.com/world/south-asia/seychelles-parliament-blocks-planned-indian-naval-base-on-remote-island/amp_articleshow/64698483.cms and https://m.timesofindia.com/world/south-asia/seychelles-parliament-blocks-planned-indian-naval-base-on-remote-island/amp_articleshow/64698483.cms 
That is this error comes both when the page is served from Google's cache and from  m.timesofindia.com domain (Screenshots attached)
Experimental opt-in is done in both of the cases, is it a bug?

![experiment disabled - publisher s domain](https://user-images.githubusercontent.com/11733935/42490030-dc549824-842b-11e8-80fb-3b75ce016b9a.png)
<img width="971" alt="experiment disabled - google cached" src="https://user-images.githubusercontent.com/11733935/42490031-dc8c915c-842b-11e8-98ae-0420d1a49182.png">

**Comment by aghassemi** [comment]
@prash-mi `amp-next-page` is currently at origin trial and not fully launched. You would need to include `<meta name="amp-experiments-opt-in" content="amp-next-page">` in your page.

/cc @ericlindley-g @emarchiori

**Comment by aghassemi** [comment]
Closing per above comment

**Comment by prash-mi** [comment]
@aghassemi `<meta content="experiment-amp-next-page" name="amp-experiments-opt-in">` is already included in the page @ https://m.timesofindia.com/world/south-asia/seychelles-parliament-blocks-planned-indian-naval-base-on-remote-island/amp_articleshow/64698483.cms . Still I am getting the error "`error.js:190 Experiment amp-next-page disabled`" . Tried enabling Dev-channel as well but no luck!

![meta amp next page](https://user-images.githubusercontent.com/11733935/42553139-3863737a-84fd-11e8-9fcc-cf2f0b132547.png)
