### ISSUE TITLE
https://www.ampproject.org/contact/ not getting validation error for using <iframe> instead of <amp-iframe>

### ISSUE THREAD

**Issue by bcko** [ampproject/amphtml#1665]
so I read the ampproject.org  guide about iframe. 
it says we should use amp-iframe.
I was wondering why https://www.ampproject.org/contact/ doesn't get validation error?
when I look at the source code of  https://www.ampproject.org/contact/ , I see that it did not use <amp-iframe> to embed google forms.

 I tried using just <iframe> to embed google map for the website I am making and I get a validation error.
However, I also do not get a validation error for embed <iframe> google forms. 

is it because it is a google form? 
thank you for your help!

**Comment by cramforce** [comment]
Just checked. Works for me. That says nothing about us should fixing that iframe.

**Comment by bcko** [comment]
https://www.ampproject.org/contact/ uses <iframe> instead of <amp-iframe> and doesn't get a validation error. I was wondering when are cases we can use <iframe>?

below is the source code from the site
```
<iframe src="https://docs.google.com/forms/d/19a_8yKgbrhZSoqHRUpTOQazN229-TIVHZqI4UvSpj_c/viewform?embedded=true" width="100%" height="100%" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
</div>
```

**Comment by cramforce** [comment]
I'm getting a validation error. Could you post a screenshot?
