### ISSUE TITLE
Analytics tracking for amp-lightbox-gallery

### ISSUE THREAD

**Issue by juanchaur1** [ampproject/amphtml#16651]
Feature request:

It'd be great to have tracking system in amp-lightbox-gallery
https://www.ampproject.org/docs/reference/components/amp-lightbox-gallery

This way we could track all different navigation levels that the amp-lightbox-gallery presents giving us an overview of the use of them in our amp pages.

**Comment by aghassemi** [comment]
/cc @ericlindley-g @cathyxz we need a few Analytics events for lightbox gallery.

A rough list I can think of (@juanchaur1 please also let us know your thoughts)
- opened (this might already be trackable using existing `click` analytics events)
- slideChange (similar to `amp-carousel`)
- thumbnailsViewToggled
- descriptionToggled
- descriptionExpanded

**Comment by juanchaur1** [comment]
@aghassemi I think you listed all events 👍

**Comment by nainar** [comment]
Taking this on.
