### ISSUE TITLE
Uncaught (in promise) Error: failed to build: amp-auto-ads#12: Experiment is off

### ISSUE THREAD

**Issue by sbefort** [ampproject/amphtml#16674]
## What's the issue?
The amp-auto-ads library is now reporting errors in the console:

`Uncaught (in promise) Error: failed to build: amp-auto-ads#12: Experiment is off.`

This error has started without any changes to the code or any changes within the Adsense settings.

## How do we reproduce the issue?
Go to https://www.sizemytires.com/vehicle/2003/acura/cl and check the console.

## What browsers are affected?
All browsers

## Which AMP version is affected?
Is this a new issue? Or was it always broken? Paste your AMP version. You can find it in the browser dev tools.

This is a new issue that has started without any code changes.
Powered by AMP ⚡ HTML – Version 1530320824316

**Comment by erwinmombay** [comment]
@sbefort , appreciate for the report! we've deployed a fix.
