### ISSUE TITLE
Amp-consent not working correctly

### ISSUE THREAD

**Issue by seomaz** [ampproject/amphtml#16671]
You can see here: https://ampbyexample.com/user_consent/basic_user_consent_flow/

No popup show, and amp components like amp-ad it does not work properly

**Comment by hrkhal** [comment]
Can confirm this is also happening on our properties. AMP validates, but no prompt and all blocked components remain blocked even though we have a timeout set.

https://metro.co.uk/2018/07/11/england-fans-ready-football-come-home-ahead-world-cup-semi-final-7701752/amp/

This is currently only happening when accessing AMP articles directly. All appears to working correctly when hitting the CDN version of an article:

https://www.google.co.uk/amp/s/metro.co.uk/2018/07/11/england-fans-ready-football-come-home-ahead-world-cup-semi-final-7701752/amp/

**Comment by hrkhal** [comment]
To add to the urgency of this, amp-consent is now not firing on the Google CDN.

Seeing the same behaviour for our competitiors.

**Comment by adamleslie** [comment]
@jasti for visibility

**Comment by shimonenator** [comment]
It seems that neither configuration for amp consent is functional right now. This can be evidenced on the AMP by Example site as well as on any publisher page that has consent in place.
The same behavior is on the origin as well as in the viewer. I did see it working earlier today, but all seems to point that I've had a cached version of amp-consent.js, once it was refreshed, it did not work anymore. 

CC @cramforce @dvoytenko for urgency.

**Comment by jpettitt** [comment]
Confirmed and can reproduce.

**Comment by jpettitt** [comment]
Rollback in progress.

**Comment by cramforce** [comment]
Rollback submitted. ETA for full availability 10-25 minutes.

This will need a post mortem.

**Comment by adamleslie** [comment]
I can confirm we're now seeing the CMP + ad calls again across dailymail.co.uk and metro.co.uk

Thanks for the quick turnaround

**Comment by shimonenator** [comment]
Seeing CMP on most recent amp cached article for cbsnews.com (https://cdn.ampproject.org/rtv/031530567757224/v0/amp-consent-0.1.js), but not seeing the update on https://cdn.ampproject.org/v0/amp-consent-0.1.js just yet

**Comment by shimonenator** [comment]
@cramforce how long will it take for https://cdn.ampproject.org/v0/amp-consent-0.1.js cache to clear?

**Comment by jridgewell** [comment]
We're in the submission process for https://cdn.ampproject.org/v0/amp-consent-0.1.js. Maybe another 30 min.

**Comment by seomaz** [comment]
Working now! thanks!

**Comment by shimonenator** [comment]
Thank you @jridgewell. Seeing it functional now.
