### ISSUE TITLE
Design Review 2018-08-22 15:30 UTC (amp-recaptcha-input)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#16693]
Time: [2018-08-22 15:30 UTC](https://www.timeanddate.com/worldclock/meeting.html?year=2018&month=08&day=22&iv=0) ([add to Google Calendar](http://www.google.com/calendar/event?action=TEMPLATE&text=AMP%20Project%20Design%20Review&dates=20180822T153000Z/20180822T163000Z&details=https%3A%2F%2Fhangouts.google.com%2Fhangouts%2F_%2Fgoogle.com%2Famp-eng-desrev))
Location: [Video conference via Google Hangouts](https://hangouts.google.com/hangouts/_/google.com/amp-eng-desrev)

The AMP Project holds weekly engineering [design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md).  **We encourage everyone in the community to participate in these design reviews.**

If you are interested in bringing your design to design review, read the [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md) and add a link to your design doc by the Monday before your design review.

When attending a design review please read through the designs *before* the design review starts.  This allows us to spend more time on discussion of the design.

We rotate our design review between times that work better for different parts of the world as described in our [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md), but you are welcome to attend any design review.  If you cannot make any of the design reviews but have a design to discuss please let mrjoro@ know on [Slack](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#discussion-channels) and we will find a time that works for you.

**Comment by torch2424** [comment]
I would like to present `<amp-recaptcha>`, inspired by #2273

**Comment by aghassemi** [comment]
## amp-recaptcha-input

- Async input, we don't have a standard way of doing this at the momemnt
- Create AmpAsyncElement class that inherits BaseElement which adds a `Promise getValue()`
- reCAPTCHA v3 is UI less ML full
- with recaptcha token is needed to be sent to server in sync way which is how this ties to amp AsynInput
- How about "homepage" action of reCAPTCHA? currently `amp-recaptcha-input` does not support this, we can add a new component for this later if needed.
- @aghassemi: Q: how about domain verification for CDN urls?
- @zhouyx: They know about AMP caches. @lannka We should still verify that they have actually implemented this.
- @jridgewell: What about the FIE? we can't put reCAPTCHA in main JS
- @lannka: we also discussed creating a bootstrap iframe we host on CDN. 
- @aghassemi: So reCAPTHA does not have a hosted iframe helper?
- @torch2424: no, we would need to create and host one.
- @aghassemi: can `layout=nodisplay` have its layout callback get called?
- @jridgewell: with some exceptions like 
- @lannka: when do we unlayout? what if we remove the iframe and something else creates another recaptcha?
- @aghassemi: For race conditions, I suggest making it safe and having `getValue()` always make sure it creates the iframe and in worse case 
- @jpettitt How about `amp-next-page`? If reCAPTCHA needs the page Url, how would that work?
- @aghassemi: as it would stand, it would see the original Url
- @calebcordry: with low-scrores it says 2-factor auth, how that work?
- @torch2424: page author has to handle it. 
- @jpettitt: How would amp-page now? can we use amp-bind.
- @torch2424: on submit they get a score on their side which they can fail the form with the reason and react to it.

**Comment by lannka** [comment]
Thanks Ali for the notes. To expand a little bit about what we discussed regarding to "when to kill the iframe".

I think the current design is:
1. amp-recapcha.js starts the recapcha service when loaded. 
1. amp-recapcha-input element sends `register` signal to the recapcha service on buildCallback
1. amp-recapcha-input element sends `initialize` signal to the recapcha service on layoutCallback. then recapcha service creates the recapcha iframe, if no one exists
1. amp-recapcha-input element sends `unregister` signal to the recapcha service on unlayoutCallback.
1. on every received `unregister` signal, recapcha checks if there's any listeners remaining, if not, kill the iframe

The concern was in case of multiple `amp-recapcha-input` on the page, there could be race condition between `register` and `unregister` signals from those elements. It's possible the iframe will need to be recreated.

The decision here is that we favor configuration simplicity over this kind of optimization for corner cases.
