### ISSUE TITLE
Setting the initial slide of an amp-carousel

### ISSUE THREAD

**Issue by radoslav-boydev** [ampproject/amphtml#16699]
I'm setting the initial slide of an amp-carousel using the [slide] attribute as it is described in the examples page. If I use some integer value less then the total number of slides it takes me to the first slide, but when I click on the arrow buttons it starts transitioning slides from the value of the [slide] attribute.

When I use the amp-state and I set a variable there, it also takes me to the first slide and it appears that it doesn't see the value of that variable.

I'm attaching also a sample code so you can reproduce this issue easier.

[example.zip](https://github.com/ampproject/amphtml/files/2188222/example.zip)

**Comment by aghassemi** [comment]
Hi, @radoslav-boydev `amp-bind` does not work on the initial load by design. Please follow https://github.com/ampproject/amphtml/issues/12591 for the same feature request regarding setting initial carousel slide.

**Comment by aghassemi** [comment]
merging with https://github.com/ampproject/amphtml/issues/12591
