### ISSUE TITLE
Promise errors observed in IE11

### ISSUE THREAD

**Issue by pinker42** [ampproject/amphtml#1670]
Error when using <amp pixel> with IE11: "Promise" is undefined v0.js (273,395)
Is it possible add "Promise" support with polyfill ?

**Comment by cramforce** [comment]
We'll check. AMP already ships with a promise polyfill.

**Comment by cramforce** [comment]
This problem is related to dependency ordering. The Promise polyfill does not appear early enough in the compilation unit.
