### ISSUE TITLE
Navigation/clickhandling service

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#16719]
We currently have a couple of features that intercept link clicks and change destination URL on the fly. It includes:

- A2A navigation
- gclid forwarding (a temporary solution to forward IDs for ads conversion tracking)
- URL macro resolution (QUERY_PARAM, CLIENT_ID)
- CLICK_X/CLICK_Y macro resolution (ads only at the moment)

Those code were scattered around. @alabiaga had some effort to move some of them into a centralized place (navigation.js, #15045).

Some more coming features will complicate this a bit more:
- The [Skimlinks extension](https://docs.google.com/document/d/10qEju2E3_c84W3ZPMjz8yGvMfFWwzSefnbMLPcC-vRs/edit#heading=h.o02l9y762p2t) 
- URL linker based cross domain analytics tracking

We need to clean it up a bit more before things getting messed up. A centralized control of all click handlers can make sure to
- avoid URL rewriting conflicts
- protect privacy
- do some optimization such as caching etc.

The service interface will look like something below:
```
const clickHandlerService = Services.clickHandlersFor(doc);
clickHandlerService.register(domSelector, urlRegex, urlConverter, macroWhitelist);
```
- `domSelector` is to specify a sub DOM for URL replacement (needed by Skimlinks).
- `urlRegex` is to further filter the URLs
- `urlConverter` is a sync function that converts the link
- `macroWhitelist` is to specify the macros that can be resolved in the URL.

**Comment by lannka** [comment]
One goal of the proposed refactoring here is to be able to quickly list all existing use cases in code easily. Right now it's a bit hard to tell how many features are intercepting global clicks, which can be problematic once the landscape becomes more complicated. A common helper method or a service would address that.

Having a specific API helps to generalize the use cases and share code. 

"URL rewriting conflicts": the URL is going to be manipulated by different extensions in a series of operations. 2 things will affect the end results:
- the order of those operations
- does one op read from the result of the previous op,  or should it read from the original URL?

"protect privacy" was mainly about the URL macros. We will make sure pub has control over what data to share with 3p extensions.

I don't think the proposed API  address all the concerns, let's discuss.

**Comment by alabiaga** [comment]
will schedule a meeting early tomorrow to discuss these changes. Thanks
