### ISSUE TITLE
verify-error for forms

### ISSUE THREAD

**Issue by cy137** [ampproject/amphtml#16728]
## What's the issue?

We would like to render a div when xhr form validation fails, similar to ```<div submit-error>```

## How do we reproduce the issue?
```
<div verify-error>
  <template type="amp-mustache">
    {{"{{#verifyErrors}}"}}
      <p>{{message}}</p>
    {{"{{/verifyErrors}}"}}
    {{"{{^verifyErrors}}"}}
      <p>Something went wrong. Try again later?</p>
    {{"{{/verifyErrors}}"}}
  </template>
</div>
```

## What browsers are affected?

All.

## Which AMP version is affected?

1531357871900

**Comment by choumx** [comment]
Looks like form verification triggers XHR on change but <div submit-error> only renders on submit. Without this feature, every XHR before the last one prior to submit is wasted.

**Comment by cvializ** [comment]
Suggested implementation: `<div verify-error>`
