### ISSUE TITLE
[Master feature] Support signed exchanges

### ISSUE THREAD

**Issue by twifkak** [ampproject/amphtml#16738]
Vision: https://www.ampproject.org/latest/blog/a-first-look-at-using-web-packaging-to-improve-amp-urls/

Spec: https://github.com/WICG/webpackage

**Comment by twifkak** [comment]
@Gregable @honeybadgerdontcare @alin04 Feel free to edit.

**Comment by Gregable** [comment]
Closing bug as this is an AMP Cache specific and should be tracked internally.
