### ISSUE TITLE
Google Analytics No Data - amp-analytics

### ISSUE THREAD

**Issue by Polylike** [ampproject/amphtml#1673]
Hey,

testing this example AMP Page https://developers.google.com/analytics/devguides/collection/amp-analytics/ with some new google analytics property IDs (no filter e.g) and i received no data via relatime reports in analytics. "AMP validation successful."

Thanks!

**Comment by dvoytenko** [comment]
@avimehta could you please take a look?

**Comment by rudygalfi** [comment]
I think this is related to: https://github.com/ampproject/docs/issues/25, which says a fix should be available soon.

**Comment by rudygalfi** [comment]
@avimehta Are changes to AMP required to address this? If so, I recommend attaching this issue to those changes. Otherwise, let's close this out.

**Comment by dawnieando** [comment]
Any idea when this is expected to be fixed?

**Comment by avimehta** [comment]
https://github.com/ampproject/amphtml/pull/1627 fixed this and the new script is live.

**Comment by rudygalfi** [comment]
Fixed via #1627.
