### ISSUE TITLE
amp-twitter gives error when using moment

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#16743]
I tried to write a sample for amp-twitter with moment id.
This is the code:
```
    <amp-twitter width="390" height="330"
    layout="responsive"
     data-momentid="1018806709412876288">
  </amp-twitter>
```
and attaching the error I get:
![error-twitter](https://user-images.githubusercontent.com/820891/42764219-fc2d10e6-890c-11e8-993c-470468faa7f9.png)

**Comment by sparhami** [comment]
Looks like support for moments will be in the next AMP release. I'll update this bug once it is live.

**Comment by kul3r4** [comment]
Thanks for the update, I saw that ampproject.org already contains a doc on
that and thought it was ready to use.

**Comment by sparhami** [comment]
This should be live now, sorry for the confusion!
