### ISSUE TITLE
cant display amp-auto-ads 

### ISSUE THREAD

**Issue by ahmadmarafa** [ampproject/amphtml#16741]
hello , 
amp-auto-ads did not display any ads , 
and i got these caution 
both are in log.js line 164 
no placements in config 
unable to fulfill ad strategy

**Comment by aghassemi** [comment]
seems important setting to p1 for now, please adjust as triaged.

**Comment by lannka** [comment]
According to @tlong2 's [comment](https://github.com/ampproject/amphtml/issues/16599#issuecomment-404801727), the messages could be as expected.

Are you not seeing any ads only on desktop? [issue](#16599) was reported for desktop not showing ads. 

If it's also mobile, can you share a link that can reproduce your issue?

@tlong2 pls help triage.

**Comment by ahmadmarafa** [comment]
ya the problem happen in desktop browser , i cant see any ads ,  i did not test it on my mobile , would you like to test it ?

**Comment by irvin** [comment]
@lannka 
I had faced on same issue, all amp-auto-ads disappear after Aug 6 with same error message, 

```
log.js:187 No placements in config
log.js:187 unable to fulfill ad strategy
```

Verified with Chrome with mobile dev mode, so it shouldn't be Firefox's issue.

Available test case:
https://womany.net/articles/3838/amp
https://womany-net.cdn.ampproject.org/c/s/womany.net/articles/3838/amp
https://womany.net/articles/39/amp
https://womany-net.cdn.ampproject.org/c/s/womany.net/articles/39/amp

You can change ID in url to between 1-15000, we have some thousand articles online.

**Comment by ivanionut** [comment]
Hi everyone,
I also have the same problem. Maybe it's because google adsense has retired AMP auto ads? 😕 

![AMP auto ads](https://hostr.co/file/OX1leAOEKDAm/autoads.png)

**Comment by irvin** [comment]
It should mark as graduated and it’s available in normal Adsense now.

**Comment by ivanionut** [comment]
Hi @irvin 
No... I always see "AMP Auto ads - Text & display" in the "Retired Labs" section. 

In your opinion, why does this happen?

**Comment by irvin** [comment]
our ads had been recovered after Aug 18, totally dead from Aug 6-Aug 17, 12 days

**Comment by lannka** [comment]
Hi Irvin thanks for letting us know. AdSense might had fixed their server endpoint.
I've confirmed the recovery with another developer who had the same issue. 

Closing now.

**Comment by cirofeitosa** [comment]
Same problem here, with AMP Auto Ads:

Console log:

- No placements in config
- unable to fulfill ad strategy

**Comment by kiang** [comment]
Same problem found in my site, too.

https://drugs.olc.tw/amp/drugs/index#development=1 or https://drugs-olc-tw.cdn.ampproject.org/c/s/drugs.olc.tw/amp/drugs/index#development=1

**Comment by irvin** [comment]
also happened to me again since two weeks ago.

**Comment by irvin** [comment]
@cirofeitosa @kiang I open a new bug, please also report here, 
https://github.com/ampproject/amphtml/issues/26934
