### ISSUE TITLE
`gulp` fails with "Found 2 AMP_CONFIG(s) before write. Aborting"

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#16768]
Occurs when `--extensions` is set.

**Comment by rsimha** [comment]
Found the problem.

We're building `amp.js` twice in `gulpfile.js`.

https://github.com/ampproject/amphtml/blob/9f72aabe2392c84a7a58bd35327e73745b9e7ef6/gulpfile.js#L277
https://github.com/ampproject/amphtml/blob/9f72aabe2392c84a7a58bd35327e73745b9e7ef6/gulpfile.js#L294

This appears to have been added by @prateekbh in https://github.com/ampproject/amphtml/commit/703aad74ebe0c045389c69e2d43041ffb2bbe9f8#diff-b9e12334e9eafd8341a6107dd98510c9
