### ISSUE TITLE
Provide a "restore" string to the viewer

### ISSUE THREAD

**Issue by ericfs** [ampproject/amphtml#1677]
Add support for a getState request from the viewer which will serialize any state that needs to be restored after a document unload and then reload such as scroll position.

**Comment by ericfs** [comment]
cc @dvoytenko

**Comment by ericfs** [comment]
Also need to accept the value as an initialization parameter to restore the state

**Comment by rudygalfi** [comment]
@ericfs How urgent is this?

**Comment by ericfs** [comment]
It's nice to have but not critical. Whenever it's ready we can make use of it, but it's not blocking.

**Comment by adelinamart** [comment]
Is this still relevant?

**Comment by rudygalfi** [comment]
I'm going to close this, assuming it's no longer needed. Anyone shout, especially @ericfs or @chenshay who's been working in this space recently, if that's wrong.
