### ISSUE TITLE
The only AMP Stories publisher in Turkey 

### ISSUE THREAD

**Issue by evrenselgzt** [ampproject/amphtml#16786]
Hi,

We're the only AMP Stories publisher in Turkey, since 8th March. [https://www.evrensel.net/hikayeler](https://www.evrensel.net/hikayeler)

We want to use DFP auto ads in our stories. We created data-slot "/9920937/AMPStory" and published  300*600 AdSense ad unit. What should we do now?

Also if you could add our stories to the AMP samples, we'll be happy.

**Comment by ecofriendlyAlternative** [comment]
@jasti on [this article from Search Engine Land](https://searchengineland.com/google-releases-amp-stories-v1-0-with-new-features-including-an-ads-beta-for-dfp-users-302203), says that we need to sign-up our DFP account to present the story ads. how do we do that?

**Comment by jasti** [comment]
@ecofriendlyAlternative https://support.google.com/dfp_premium/answer/7084151?hl=en

**Comment by ecofriendlyAlternative** [comment]
@jasti Thanks! And any account will be able to serve story ads? Or do we need to opt-in/sign up for some beta product?

**Comment by jasti** [comment]
It's an open beta at the moment, so shouldn't have any restrictions but please do contact DFP support if you are having any issues regarding this.

**Comment by evrenselgzt** [comment]
@newmuis I'm talking about these real stories: https://www.ampproject.org/stories/

**Comment by newmuis** [comment]
Closing this, since there is nothing actionable here.
