### ISSUE TITLE
Custom page font loading not working properly for AMP CDN URL

### ISSUE THREAD

**Issue by durr04** [ampproject/amphtml#16784]
Custom page font loading not working properly for CDN URL

I have created AMP page with valid AMP HTML & AMP validator test has been passed. The custom fonts used for this page are getting loaded correctly also. But for the AMP Cache url of the same page, the custom font are not loading.

**Comment by jpettitt** [comment]
This is almost certainly a CORS error, if the fonts are on your origin server they won't need an `Allow-origin` and will work,  however when the page is loaded from the cdn it will need an `Allow-origin: *` or `Allow-origin: <domain of the cache>` to be set by your server.

**Comment by Gregable** [comment]
Without more information, there is little we can do to confirm. Closing.
