### ISSUE TITLE
Problems with AMP images and carousels on a ASP .NET CMS

### ISSUE THREAD

**Issue by brunofcb** [ampproject/amphtml#1679]
I've implemented the CMS (ASP .NET) in my amp-html page recently and everything worked fine in the past two weeks, but during this week, I've noticed that some images and carousels uploaded via CMS are not loading and sometimes none of them load. I'm receiving this error all the time:_ Uncaught TypeError: Cannot read property 'fine' of undefined. Does anyone have an idea of what this might be?_

**Comment by dvoytenko** [comment]
@brunofcb Do you have a full stack for this error?

**Comment by brunofcb** [comment]
![image](https://cloud.githubusercontent.com/assets/8183465/12684423/a0d666a4-c69d-11e5-9c59-5eb6ca5f13c0.png)

**Comment by dvoytenko** [comment]
@brunofcb This is rather strange. Do you think you could try this document in a incognito window w/o extensions? My only guess for now is that some extension messes something up.

**Comment by brunofcb** [comment]
@dvoytenko It's really weird. I think you're right. I removed the extensions and it seems that the problem was solved. Thank you.

**Comment by dvoytenko** [comment]
It would be very awesome to find out which extension actually did cause the problem. That way we can perhaps find a solution.

**Comment by hanimohammad** [comment]
please any idea about ajax server side data in amp html
