### ISSUE TITLE
amp-carousel doesn't display description of the images

### ISSUE THREAD

**Issue by jito1989** [ampproject/amphtml#1680]
if within carousel  place  amp-img and div with the description of the image, the carousel only show images and doesn't show description of the images.

add example:

<amp-carousel width=400 height=300  type=slides layout=responsive controls >
                                <?php foreach ($nota["gallery"]["files"] as $x): ?>
                                    <amp-img class=" img_nota_completa loader" 
                                    src="<?php print $x["url_img"] ?>"                            
                                    layout="responsive"
                                    width="360"
                                    alt="<?php print $x["title"]; ?>"
                                    height="216">
                                    </amp-img>
                                <div><?php print $x["title"]; ?></div>
                                <?php endforeach; ?>
</amp-carousel>

**Comment by erwinmombay** [comment]
@jito1989 do you have a page i can look at? or a reproduction of it in a gist/jsfiddle(etc)? would appreciate it

**Comment by ericlindley-g** [comment]
Closing this, but please re-open if this is still and issue for you and you can provide more detail. The [<amp-image-ligthbox> documentation](https://github.com/ampproject/amphtml/blob/master/extensions/amp-image-lightbox/amp-image-lightbox.md), which you can use in <amp-carousel>, has some guidance on working with descriptions and images.
