### ISSUE TITLE
Container layout on responsive amp-ad

### ISSUE THREAD

**Issue by rendude** [ampproject/amphtml#16810]
## What's the issue?

amp-ad component fixes the width and height ratio for responsive ads. For layout="responsive," this becomes a big problem when the size of the screen increases but the height is not increasing at the same ratio. What's left is an awkward white space on the bottom of the ad. If layout="fixed-height" is used, the coder needs to somehow pre-determine the height for all of the content of the responsive ad in the height regardless of the width. This often is impossible as when the ad has text that takes up different amounts of space depending on the screen width. So for responsive ads, particularly those that look native, we need some mechanism to update the height of the iframe. This problem is worsened when working with an ad-server where the client cannot predict which ad is selected for the given zone. The zone could serve ads of a number of different heights.

## How do we reproduce the issue?

1. Create a custom ad using AMPHTML that's just three lines <h1>My text ad</h1><p>A body text that's around 300 characters</p>
2. Define an amp-ad using either "responsive" layout or "fixed-height". Let's say 300 x 150 or just 150 height.
3. Drag the inspector screen and see that either there is big white space underneath the ad (when "responsive" layout is used) or the ad is cut off (when "fixed-height" is used)

If this is a feature request you can use this section to point to a prototype/mockup that will help us understand the request.

## What browsers are affected?
all

## Which AMP version is affected?
Always broken

**Comment by lannka** [comment]
> For layout="responsive," this becomes a big problem when the size of the screen increases but the height is not increasing at the same ratio.

this is not true. layout="responsive" will always keep the original width/height ratio. Or maybe I mis-understood?

> This problem is worsened when working with an ad-server where the client cannot predict which ad is selected for the given zone. The zone could serve ads of a number of different heights.

we allow ad to request a resize after loading. would that address the problem here?

**Comment by lannka** [comment]
Ad resize: https://github.com/ampproject/amphtml/blob/master/ads/README.md#ad-resizing
