### ISSUE TITLE
amp-bind integration tests are routinely timing out on `master`

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#16832]
For example
https://travis-ci.org/ampproject/amphtml/jobs/405132168#L616
https://travis-ci.org/ampproject/amphtml/jobs/405123204#L643
https://travis-ci.org/ampproject/amphtml/jobs/405120361#L643

**Comment by rsimha** [comment]
It's possible that the test prior to these tests is crashing, and resulting in the appearance of timeouts.

**Comment by choumx** [comment]
> It's possible that the test prior to these tests is crashing, and resulting in the appearance of timeouts.

This could've caused second and third failures. First failure had several integration tests time out. I'll keep an eye on master and gather more evidence.

**Comment by choumx** [comment]
@rsimha Is this still an issue? Looks like this probably wasn't the cause of master redness in hindsight.

**Comment by rsimha** [comment]
Yeah, it might have been due to the breaking changes that @erwinmombay and @cramforce reverted.

Let's close this until it repros again.
