### ISSUE TITLE
`amp-fx` does not work in `amp-list`

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#16838]
reported by @mofid on slack channel.

Issue is sanitizer removing the attribute. There may also be other issues (e.g. amp-fx-collection needing to rescan)

**Comment by nainar** [comment]
Some more context from the Slack thread:

```
hi
i have an amp-list with bunch of div inside and i like to use amp-fx on those divs. the problem is that the amp-list deletes amp-fx tag from the divs automatically and inserts amp-fx-roll instead 
how can i fix that?
```

**Comment by mofidsky** [comment]
first of all thanks for working on amp-fx to sync with amp-list but i have a big problem.
when i have amp-fx inside amp-list in a normal html it works just fine.
[html link](https://www.api.telexiran.com/application/videolist.html)
but as i include this html page in a .net project everything breaks apart. although i can see the tag inside the page source, they are being deleted in the developer tools and therefore the amp-fx functionality is not working anymore
[cshtml link](http://178.216.248.58/%D8%A7%D8%AE%D8%A8%D8%A7%D8%B1-%D9%88%DB%8C%D8%AF%DB%8C%D9%88%DB%8C%DB%8C)
