### ISSUE TITLE
Question: AMP Stories and Google Analytics pageviews

### ISSUE THREAD

**Issue by ecofriendlyAlternative** [ampproject/amphtml#16845]
What is the best practice for Google Analytics on Stories?

Should we fire a new pageview on "tap"? should we fire an event?

How could we better understand on which story page the user left on? Should we fire and event at the end of the story?

Thanks in advance for the feedback

**Comment by newmuis** [comment]
@ecofriendlyAlternative See [amp-story-analytics.md](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/amp-story-analytics.md) for how to use analytics within amp-story.

Events are already fired every time a new story page becomes visible (`story-page-visible` trigger) and at the end of the story (`story-bookend-enter` trigger) trigger, so you can combine these with the other signals you normally collect to tell where the user left off in the story.

As a side note, it looks as if the `story-bookend-enter` and `story-bookend-exit` triggers are missing from the documentation, so I will add those to the documentation now.

**Comment by rudygalfi** [comment]
@ecofriendlyAlternative: In discussions I've had with product managers for analytics frameworks, they've said they'd advise considering transition to a new story page to be a new page view. So, for that, you'd need to make a customization on top of the `type=googleanalytics` and use `story-page-visible` trigger to create the additional pageview events.

Of course, a story is a really different experience, so you'll need to keep that in mind with analysis. e.g. Stories will probably generate many pageviews with relatively shorter view time.

**Comment by rudygalfi** [comment]
@newmuis Thanks for the doc update.
