### ISSUE TITLE
Lifter.com.ua want show ads in AMP Stories

### ISSUE THREAD

**Issue by p0hyurt** [ampproject/amphtml#16848]
## What's the issue?

We have site lifter.com.ua and use AMP Stories a few months. We want add adsense/ADX to our stories. We found this link here: 
https://amphtml.wordpress.com/2018/07/16/new-in-amp-stories-monetization-revamped-bookends-and-metadata/

We are biggest publisher in russian-language section on facebook and first publisher, who can try AMP Stories on russian language.

**Comment by jasti** [comment]
Please see instructions here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad-network-doubleclick-impl/single-page-ad.md
