### ISSUE TITLE
switch to native `element.scrollIntoView` for our implementation.

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#16860]
https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView seems widely supported, but we should access how good it is first (special regarding scrolling to elements in sub-scrollable areas like scrollable lightbox and sidebar)

It does not have all the feature we have such as curve and duration for the `smooth` version, but I will be fine with breaking our API and start ignoring duration with a warning.

/cc @alanorozco @sparhami

**Comment by alanorozco** [comment]
+1

- Would be a bundle size win.
- Totally fine to break duration and easing in all cases and ASAP.

**Comment by sparhami** [comment]
Did some testing on jsbin (e.g. https://output.jsbin.com/vahilutaxu/). Some findings:

- `scrollIntoView` works for fixed position elements on Firefox, Safari and Chrome
- `scrollIntoView` works for nested scroll containers on Firefox, Safari and Chrome
  * The smooth behavior works well on Chrome: it scrolls the container smoothly in to view, then the item in the container
  * The smooth behavior is a bit weird on Firefox
- The options (and thus smooth scroll) is not supported in Safari 😢

**Comment by aghassemi** [comment]
:( https://bugs.webkit.org/show_bug.cgi?id=161611

**Comment by westonruter** [comment]
There is also `scroll-behavior:smooth` in CSS which could be used alternatively in some cases: https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior

**Comment by sparhami** [comment]
Looks like we would have avoided #17792 if we had native `scrollIntoView`.

**Comment by sparhami** [comment]
Doing some research on what value of duration developers use, the vast vast majority use a value between 200 and 400ms. As a result, ignoring duration (with the exception of zero, which should disable the smooth scroll) is not a major problem.
