### ISSUE TITLE
Just how does the viewer work?

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#1686]
I've been looking at the viewer example code all day and come to the conclusion that it will never actually work.  Specifically the viewer example has a lot of message passing code in `viewer-integr-messaging.js` but if I grep the source and look at every `addEventListener()` call in the ./src tree I can only find one instance where it's listening for 'message' and that is in `listen()` in `iframe-helper.js` which isn't being called if there are no `<amp-iframe>` elements.  

I confirmed this in chrome debugger by dumping all the listeners on the iframe window containing the AMP document and there is nothing there listening for messages. 

What am I missing?

**Comment by dvoytenko** [comment]
Viewer is not enabled quite yet and the protocol has not been standardized. We are working on it.

**Comment by jpettitt** [comment]
That explains a lot.
