### ISSUE TITLE
Point the spec URLs in the validator at ampproject.org.

### ISSUE THREAD

**Issue by powdercloud** [ampproject/amphtml#1687]
We currently link to markdown files in Github from our error messages. We should start to use ampproject.org where possible, as it's going to be more stable, prettier, general, etc.

So, we need to go through our code and spec file and fix all those links and our feature tests.

/cc: @Gregable

**Comment by ewebxml** [comment]
As a developer/publisher refactors his existing html/html5 and transforms his webpage using AMP markup, 
is there an existing 
1) AMP parser or 
2) AMP validator 
that can provide feedback with respect to 
the correctness of the changes made?

A parser that is similar to https://validator.w3.org/ 
but instead provides feedback for AMP markup.

**Comment by powdercloud** [comment]
@ewebxml thus far we have the #development=1 facility - see here:
https://www.ampproject.org/docs/get_started/create/preview_and_validate.html
Also, the validator that's in there is open source, so if you prefer a command line tool you can build it.
https://github.com/ampproject/amphtml/tree/master/validator
We don't have an interface like validator.w3.org yet. It wouldn't be too hard to do this, e.g. with CodeMirror or as a CodeMirror plugin - the OSS validator is written in Javascript so this could be done without server-side logic (unlike validator.w3.org, which runs server-side).
