### ISSUE TITLE
is amp html another version (separate file.html)?

### ISSUE THREAD

**Issue by alexiirj1** [ampproject/amphtml#1688]
I am complete starter in AMP, just trying to make my landing page discoverable. should i create a new html with the newly-announced tags such as <amp-img> and so forth? or should i implement those tags in the existing ones? 

p.s when i include <amp-img></amp-img> image is not loading? please share some easy to do instruction, thank you so much.

**Comment by rudygalfi** [comment]
@alexiirj1 Thanks for your interest in AMP!

You can go with either path you mentioned; AMP supports both. Please check out this page for detailed instructions: https://www.ampproject.org/docs/guides/discovery.html.

`<img>` is not allowed in AMP but has a replacement: `<amp-img>`. See this for more: https://www.ampproject.org/docs/reference/amp-img.html.
