### ISSUE TITLE
Incorporate pinch to zoom into lightbox

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#1689]
Builds on #304

**Comment by adelinamart** [comment]
Hi Rudy, is this one still relevant?

**Comment by rudygalfi** [comment]
Yes, this is a candidate for a lightbox features project.

**Comment by ericlindley-g** [comment]
Definitely — @aghassemi , is this bug useful to track your work, or would you rather incorporate into your lightbox checklist?

**Comment by aghassemi** [comment]
@ericlindley-g @adelinamart We can close this. It is a core feature of lightbox 2.0, no need to track it separately.
