### ISSUE TITLE
amp-date-picker specify an initial date offset from current date

### ISSUE THREAD

**Issue by ro2ni3** [ampproject/amphtml#16904]
## What's the feature?

I have tried to set up the amp date picker to automatically have a date set on the input as the page loads. I have looked at the documentation but in there the only way to set the date is when the user taps on the input.

## How could the feature be implemented?

Since this is more of an event feature, I was thinking it could be something like this?:
```
<input name="date1" on="load:date-picker.today(offset=14)" role="textbox" tabindex="5" />
```

**Comment by cvializ** [comment]
Agreed, let's add this.

**Comment by ro2ni3** [comment]
@aghassemi yes that's correct, the date value needs to be worked out on page load to be today + 14 days (dynamic) and set into the [value] of the input. Sorry, ignore the event idea.

**Comment by cvializ** [comment]
I plan to implement this by overloading the existing `date`, `start-date` and `end-date` attributes to accept [ISO 8601 duration offset values ](https://en.wikipedia.org/wiki/ISO_8601#Durations) e.g.

```html
<!-- Initially set to 3 days in the future -->
<amp-date-picker date="P3D" mode="static" layout="fixed-height" height="360">
</amp-date-picker>
```

**Comment by aghassemi** [comment]
Implemented by https://github.com/ampproject/amphtml/pull/17388 and is live in production.

**Comment by ro2ni3** [comment]
Thank you very much for adding this feature. It is working as expected but there are a few AMP validator issues that have now come up. When I add the new date attribute it complains saying that 'date' is not an allowed attribute in amp-date-picker given the mode and layout.
Here's the [CodePen](https://codepen.io/ro2nie/pen/XPaROp) 

Sorry I couldn't link to the AMP playground as it doesn't offer to save the html onto a permalink. So just copy that code from the CodePen into the playground and you will see 3 AMP validator errors.

I have tried solving these validation errors but every time I do what it suggests, new validation errors appear. I'm not sure if this is supposed to be working like this.

On our build pipeline, the AMP validation is run before deployment to our staging environment which means it is failing at the moment because of these validation errors.

**Comment by honeybadgerdontcare** [comment]
Here's a link to the Validator WebUI with that html: https://validator.ampproject.org/#url=https%3A%2F%2Fcodepen.io%2Fro2nie%2Fpen%2FXPaROp.html

There are three errors:
-   The specified layout 'CONTAINER' is not supported by tag 'amp-date-picker[type=single][mode=static]'. Learn more.
-   The attribute 'date' may not appear in tag 'amp-date-picker[type=single][mode=static]'. Learn more.
-   The attribute 'mode' in tag 'amp-date-picker[type=single][mode=static]' is set to the invalid value 'overlay'. Learn more.

The central issue for validation is the `date` attribute which can only be used with `mode=static` and not `mode=overlay`.
