### ISSUE TITLE
Document use of emojis in the commit messages

### ISSUE THREAD

**Issue by tobie** [ampproject/amphtml#16902]
I ❤️ seeing emojis used in commit message, but for a newcomer to the project, it's a bit intimidating. What does each one mean in the context of the AMP project?

It would be great to have the most common ones listed (with their definition) in [CONTRIBUTING.md](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md).

**Comment by tobie** [comment]
Turns out there's a [bunch](https://gitmoji.carloscuesta.me/) [of](https://github.com/dannyfritz/commit-message-emoji) [guides](https://gist.github.com/parmentf/035de27d6ed1dce0b36a). Maybe just link to one of them?

**Comment by jpettitt** [comment]
The [pull request template](https://github.com/ampproject/amphtml/blob/master/.github/PULL_REQUEST_TEMPLATE.md) has a list:

✨ New feature (:sparkles:)
🐛 Bug fix (:bug:)
🔥 P0 fix (:fire:)
✅ Tests (:white_check_mark:)
🚀 Performance improvements (:rocket:)
🖍 CSS / Styling (:crayon:)
♿ Accessibility (:wheelchair:)
🌐 Internationalization (:globe_with_meridians:)
📖 Documentation (:book:)
🏗 Infrastructure / Tooling / Builds / CI (:building_construction:)
⏪ Reverting a previous change (:rewind:)
♻️ Refactoring (like moving around code w/o any changes) (:recycle:)
🚮 Deleting code (:put_litter_in_its_place:)

**Comment by tobie** [comment]
Oh, great! +1 to having it documented elsewhere, though.

**Comment by bpaduch** [comment]
Oddly, a description of the icons in [CONTRIBUTING.md](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md) wouldn't be adequate because it's when you create the Pull Request that you stipulate (if you want) an emoji.  Perhaps in the Getting Started Guide, but then again, when you click the button to "Create a Pull Request", the template is already populated with what icons to use and what they mean.

@mrjoro  - thoughts?

**Comment by tobie** [comment]
Yeah, you’re right. CONTRIBUTING.md isn’t necessarily the best place. Note my use case is different than the one you mention. I wanted to understand the meanings of the emojis used in the commit messages, not to create a commit message of my own. My reflex was checking the README, then CONTRIBUTING.md. Either one would have worked.
