### ISSUE TITLE
"IF" deleted from amp-analytics URLs

### ISSUE THREAD

**Issue by fueledbymarvin** [ampproject/amphtml#16917]
## What's the issue?

The string "IF" is deleted from `amp-analytics` request URLs. This is causing base64 encoded strings that contain "IF" to be corrupted which is causing our analytics to not track many of our events.

## How do we reproduce the issue?

1. Visit this page: [https://www.google.com/amp/s/genius.com/amp/Nayt-gola-lyrics](https://www.google.com/amp/s/genius.com/amp/Nayt-gola-lyrics)
2. Inspect the page and run `JSON.parse(document.querySelector('#genius_mixpanel_analytics script').innerText).requests.pageview` in the console to get the request URL that is in the `amp-analytics` configuration. It should be something like:

`https://mpfwd.genius.com?data=eyJldmVudCI6IlNvbmcgUGFnZSBMb2FkIiwicHJvcGVydGllcyI6eyJTb25n
IElEIjpudWxsLCJUaXRsZSI6IkdvbGEiLCJQcmltYXJ5IEFydGlzdCI6Ik5h
eXQiLCJQcmltYXJ5IEFydGlzdCBJRCI6bnVsbCwiUHJpbWFyeSBBbGJ1bSI6
IlJhcHR1cywgVm9sLiAyIiwiUHJpbWFyeSBBbGJ1bSBJRCI6bnVsbCwiVGFn
IjoicmFwIiwiUHJpbWFyeSBUYWciOiJyYXAiLCJQcmltYXJ5IFRhZyBJRCI6
bnVsbCwiTXVzaWM/IjpudWxsLCJBbm5vdGF0YWJsZSBUeXBlIjoiU29uZyIs
IkFubm90YXRhYmxlIElEIjpudWxsLCJmZWF0dXJlZF92aWRlbyI6bnVsbCwi
Y29ob3J0X2lkcyI6bnVsbCwiaGFzX3ZlcmlmaWVkX2NhbGxvdXQiOm51bGws
Imhhc19mZWF0dXJlZF9hbm5vdGF0aW9uIjpudWxsLCJjcmVhdGVkX2F0Ijoi
MjAxNy0wNi0yOFQwNToyNzozOFoiLCJjcmVhdGVkX21vbnRoIjoiMjAxNy0w
Ni0wMSIsImNyZWF0ZWRfeWVhciI6bnVsbCwic29uZ190aWVyIjoiRSIsIkhh
cyBSZWNpcmN1bGF0ZWQgQXJ0aWNsZXMiOm51bGwsIkx5cmljcyBMYW5ndWFn
ZSI6Iml0IiwiSGFzIFNvbmcgU3RvcnkiOm51bGwsIlNvbmcgU3RvcnkgSUQi
Om51bGwsInRva2VuIjoiNzc5NjdjNTJkYzM4MTg2Y2MxYWFkZWJkZDE5ZTJh
ODIiLCJnZW5pdXNfcGxhdGZvcm0iOiJ3ZWIiLCJNb2JpbGUgU2l0ZSI6bnVs
bCwiQU1QIjpudWxsLCJMb2dnZWQgSW4iOm51bGwsIklzIEVkaXRvciI6bnVs
bCwiSXMgTW9kZXJhdG9yIjpudWxsLCJWaWRlb3MgTG9hZGVkIChwbGFjZW1l
bnQ6IGNhcm91c2VsLCByZWxldmFuY2U6IGxvdykgLSBJRHMiOm51bGx9fQ==
&distinct_id=${clientId(_ga)}`

3. Go the "Network" tab and search for the host of this URL (`https://mpfwd.genius.com`). The URL that AMP requested should be something like:

`https://mpfwd.genius.com/?data=eyJldmVudCI6IlNvbmcgUGFnZSBMb2FkIiwicHJvcGVydGllcyI6eyJTb25nIElEIjpudWxsLCJUaXRsZSI6IkdvbGEiLCJQcmltYXJ5IEFydGlzdCI6Ik5heXQiLCJQcmltYXJ5IEFydGlzdCBJRCI6bnVsbCwiUHJpbWFyeSBBbGJ1bSI6IlJhcHR1cywgVm9sLiAyIiwiUHJpbWFyeSBBbGJ1bSBJRCI6bnVsbCwiVGFnIjoicmFwIiwiUHJpbWFyeSBUYWciOiJyYXAiLCJQcmltYXJ5RhZyBJRCI6bnVsbCwiTXVzaWM/IjpudWxsLCJBbm5vdGF0YWJsZSBUeXBlIjoiU29uZyIsIkFubm90YXRhYmxlIElEIjpudWxsLCJmZWF0dXJlZF92aWRlbyI6bnVsbCwiY29ob3J0X2lkcyI6bnVsbCwiaGFzX3ZlcmlmaWVkX2NhbGxvdXQiOm51bGwsImhhc19mZWF0dXJlZF9hbm5vdGF0aW9uIjpudWxsLCJjcmVhdGVkX2F0IjoiMjAxNy0wNi0yOFQwNToyNzozOFoiLCJjcmVhdGVkX21vbnRoIjoiMjAxNy0wNi0wMSIsImNyZWF0ZWRfeWVhciI6bnVsbCwic29uZ190aWVyIjoiRSIsIkhhcyBSZWNpcmN1bGF0ZWQgQXJ0aWNsZXMiOm51bGwsIkx5cmljcyBMYW5ndWFnZSI6Iml0IiwiSGFzNvbmcgU3RvcnkiOm51bGwsIlNvbmcgU3RvcnkgSUQiOm51bGwsInRva2VuIjoiNzc5NjdjNTJkYzM4MTg2Y2MxYWFkZWJkZDE5ZTJhODIiLCJnZW5pdXNfcGxhdGZvcm0iOiJ3ZWIiLCJNb2JpbGUgU2l0ZSI6bnVsbCwiQU1QIjpudWxsLCJMb2dnZWQgSW4iOm51bGwsIklzIEVkaXRvciI6bnVsbCwiSXMgTW9kZXJhdG9yIjpudWxsLCJWaWRlb3MgTG9hZGVkIChwbGFjZW1lbnQ6IGNhcm91c2VsLCByZWxldmFuY2U6IGxvdykgLSBJRHMiOm51bGx9fQ==&distinct_id=Rz3ph5ClomI2ndQEUnNEUMICpjjdzAuXonrWncEdiD7q6IQeD-FCGTtDtiDXobIq`

4. Notice that the URL in the configuration is different from the URL that is actually requested. Specifically, any occurrence of "IF" is removed.

## What browsers are affected?

All browsers.

## Which AMP version is affected?

We think this started around Friday July 13 or Saturday July 14. The AMP version for that page is currently 1531347091169. This does not happen outside of the AMP viewer. Going directly to [https://genius.com/amp/Nayt-gola-lyrics](https://genius.com/amp/Nayt-gola-lyrics) executes the proper behavior.

**Comment by fueledbymarvin** [comment]
Seems like [this line of code](https://github.com/ampproject/amphtml/blame/master/extensions/amp-analytics/0.1/variables.js#L143) is relevant. It's odd that there doesn't need to be parentheses or anything else that indicates a function/macro.

**Comment by zhouyx** [comment]
As we talked, the replace-url v2 macro brings this regression.

**Comment by fueledbymarvin** [comment]
@aghassemi @zhouyx @calebcordry Thanks for investigating this. We've introduced a temporary fix on our end (so the reproduction won't work anymore), but we are eagerly waiting for the permanent fix and the replace url macros feature.

**Comment by calebcordry** [comment]
Yep, we knew that this was coming. You are right we wish we had a better syntax to indicate a macro, but anything we introduce now would be breaking. @fueledbymarvin would it be possible to use a lowercase `if`? Then the parser should ignore it.

**Comment by fueledbymarvin** [comment]
@calebcordry The output of base64 is determined by the input data. We cannot use lowercase `if` without corrupting the data.

**Comment by calebcordry** [comment]
Oh I see. Sorry, I read it as the `IF` was getting replaced before encoding. 😯. We will work on a fix.

**Comment by calebcordry** [comment]
@zhouyx @lannka What do you think about prefixing the `IF` macro? `AMP-IF`? It seems like all the shortest macros have a risk of collision like this. `IF` is the only two letter macro, there is one three letter. `NOT`, everything else is 4+.

**Comment by lannka** [comment]
Prefixing sounds good. Let's prefix all of them with an non-base64 char, for instance`$`.
