### ISSUE TITLE
AMP viewer blocking top sticky banner on iOS

### ISSUE THREAD

**Issue by juliacochran** [ampproject/amphtml#16933]
## What's the issue?
The AMP Viewer sometimes blocks sticky banner at the top of the page, leaving the area of the page that was meant to have the banner on it with just whitespace. 

<img width="274" alt="screen shot 2018-07-19 at 1 34 47 pm" src="https://user-images.githubusercontent.com/3277587/42968572-895fa706-8b58-11e8-9425-08917c792b39.png">

[Screen recording of behavior](https://drive.google.com/file/d/1KAKBMs_70fkPcVmhDAG436eU3my4yyXA/view?usp=sharing)

## How do we reproduce the issue?
1. Search for something that will produce a Pinterest AMP result, like "Pinterest home decor"
2. Click to open Pin page and notice app install banner on top

Note, if you see the app install banner on the bottom of the screen, please clear your cache and try again (this feature is still in experiment).

## What browsers are affected?

iOS Safari, iOS Chrome

## Which AMP version is affected?

Unsure.

**Comment by choumx** [comment]
Looks like the app banner is gated by `amp-access`. Perhaps being added dynamically prevents it from having the viewer header offset applied. Scrolling down then up fixes this issue.

**Comment by ericlindley-g** [comment]
@jridgewell Checking in on this issue — have we been able to investigate more closely?

**Comment by juliacochran** [comment]
@choumx @jridgewell Any updates on a timeline for this? We are still seeing the issue pretty frequently.

**Comment by ericlindley-g** [comment]
Checking in: @choumx @jridgewell , is this slated for a specific sprint?

**Comment by juliacochran** [comment]
@ericlindley-g Any updates on a specific sprint? Or suggestions for how we can mitigate this in the meantime? We have launched this new banner to all users so it should be much easier to repro.

First load is the bug (image on the left). You can see the banner is hidden behind the viewer. After you start to scroll it adjusts correctly (image on the right)

 <img width="274" alt="Bug" src="https://user-images.githubusercontent.com/3277587/44733647-dd58bb00-aa9c-11e8-81a3-d0f92f76a7b5.PNG"><img width="274" alt="Correct" src="https://user-images.githubusercontent.com/3277587/44733714-024d2e00-aa9d-11e8-8716-9993e84a4198.PNG">

**Comment by ericlindley-g** [comment]
Thanks for re-pinging @juliacochran  — this is high priority from my perspective. @jridgewell , @choumx do you have any thoughts or updates here?

**Comment by choumx** [comment]
Justin has begun work on this. I think this is same root cause as #17475 (among others).

Plan of attack: https://github.com/ampproject/amphtml/issues/17475#issuecomment-416390437

**Comment by juliacochran** [comment]
Great thank you @ericlindley-g @choumx! Is there an estimate for when this work will be completed?

**Comment by jridgewell** [comment]
Within the next few weeks. There are [several PRs](https://github.com/ampproject/amphtml/pulls?q=is%3Apr+project%3Aampproject%2Famphtml%2F56+is%3Aclosed) already landing to progress it.

**Comment by juliacochran** [comment]
@jridgewell Appreciate all the progress that has been made on this so far! We have put a hack in place to make the banner show up on the initial render right now, but would like to remove this as soon as possible. Please let me know if there is anything we can update on our side to take advantage of the changes that have been made!
