### ISSUE TITLE
AMP HTML file can't render because https://cdn.ampproject.org/robots.txt set to disallow

### ISSUE THREAD

**Issue by Jimmaki** [ampproject/amphtml#1695]
Fetch and render my AMP HTML files and all, one by one, having the same issue.

The report from Search Console states "Googlebot couldn't get all resources for this page. Here's a list:"

URL: https://cdn.ampproject.org/v0.js<br>
Type: Script<br>
Reason: Blocked<br>
Severity: High<br>
https://cdn.ampproject.org/v0.js/robots.txt

Is there any way to render those?

**Comment by cramforce** [comment]
Good catch. Will fix.

**Comment by cramforce** [comment]
Tracked at Google as b/26889091

**Comment by cramforce** [comment]
This is fixed.

**Comment by Jimmaki** [comment]
Thanx!

**Comment by esginmurat** [comment]
hello. I have a similar problem. How did you fix the problem?
