### ISSUE TITLE
My site use amp-form, however always submit-error?

### ISSUE THREAD

**Issue by shangdev** [ampproject/amphtml#16964]
This is site :https://www.trueniu.com/%E7%BD%91%E7%AB%99seo%E5%B8%B8%E7%94%A8%E5%B7%A5%E5%85%B7/amp/

you can test it.

Response format:
`{"name":"bear shang","email":"test@test.com"}`

But page always show 'Send failed'!

**Comment by aghassemi** [comment]
@shangdev The page is returning
`Response must contain the AMP-Access-Control-Allow-Source-Origin header` error which means your endpoint for submission has not implemented required AMP CORS headers.

Please see https://www.ampproject.org/docs/fundamentals/amp-cors-requests for details of what additional HTTP headers you need to return in the response.
