### ISSUE TITLE
amp-fit-text does weird things

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#170]
It currently fails locally but passes on travis.

@dvoytenko Could you take another look?

**Comment by 88kbbq** [comment]
This was a perfect title to what's happening with amp-fit-text. When applying different layout values, behavior was unpredictable and unintuitive. Fill should fill the height and width defined in amp-fit-text, but this does not happen; multiple amp-fix-text in a grid will overlap each other, ignoring other CSS rules. Fixed does what exactly? Flex? I'd love to contribute examples but I can't figure this out. Seems I get different behavior every time I try playing with amp-fit-text, sometimes the text just disappears!
