### ISSUE TITLE
Cherry pick request for #16370 into #16527

### ISSUE THREAD

**Issue by prateekbh** [ampproject/amphtml#17011]
GitHub issue your cherry pick is fixing:

Issue #16370

PR that you are requesting a cherry pick for:
PR #16542

Release(s) you requesting this cherry pick into:

Release issues can be found at https://github.com/ampproject/amphtml/labels/Type%3A%20Release

If you are requesting a cherry pick into a production release you will most likely need to cherry pick into canary as well, otherwise when the canary is pushed to production your fix will be lost. See the cherry pick documentation.)

Production Release? Yes If yes, Type: Release Issue #16527

Canary release? Yes If yes, Type: Release Issue #16527,

Why does this issue meet the cherry pick criteria? Be specific.

This breaks amp-subscriptions in production. 
The fix done for the specified issue was a workaround which still does not work for iPhoneX due to a style in amp.css.
The requested cherry-pick is a rather long-term solution to the same problem occurring due to multiple `html` tags in case of iPhone.

cc: @cramforce

**Comment by cramforce** [comment]
Approved.

**Comment by aghassemi** [comment]
@prateekbh This will be cherry-picked into Canary that will become Prod tomorrow.

**Comment by aghassemi** [comment]
Since this is already in Canary and since Prod is 2 weeks old, plan is to promote Canary to Prod today instead of cherry-picking. /cc @choumx @erwinmombay
