### ISSUE TITLE
<amp-mathml> seems to only work with TeX

### ISSUE THREAD

**Issue by fstanis** [ampproject/amphtml#17038]
## What's the issue?

It seems that using MathML or AsciiMath in the `data-formula` field for `<amp-mathml>` doesn't display anything, despite the fact they are supported by MathJax.

## How do we reproduce the issue?

```html
<!-- Working -->
<amp-mathml data-formula="\[x\]"></amp-mathml>

<!-- Not working -->
<amp-mathml data-formula="`x`"></amp-mathml>

<!-- Not working -->
<amp-mathml data-formula="&lt;math xmlns=&quot;http://www.w3.org/1998/Math/MathML&quot; display=&quot;block&quot;&gt;&lt;mi&gt;x&lt;/mi&gt;&lt;/math&gt;"></amp-mathml>

```

## What browsers are affected?

Tested on Chrome and Firefox.

## Which AMP version is affected?

Tested with 1531800879103.

**Comment by fstanis** [comment]
@adamsilverstein mind taking a look? I tried looking at the generated iframe and it seems that the div with `id="mathmlformula"` is being correctly generated, but nothing is displayed.

**Comment by adamsilverstein** [comment]
@fstanis Thanks for the bug report. Sure, I'll give it a test soon to see if I can tell whats happening.

**Comment by jaygray0919** [comment]
In our experience, the only technique that works is `data-formula='\[x\] `. Earlier, this failed, but the AMP team fixed the issue. It renders below in the sentence: "where T is the number of words in the ingredient phrase x"
  https://afdsi.org/test/amp_mathml_1/

**Comment by fstanis** [comment]
Thinking about it, it seems that the current approach (`data-formula` attribute) is a bit inconvenient for MathML specifically, since the whole thing requires HTML Entities encoding.

Perhaps it would be better if the formula could be inside `<amp-mathml>` as well:

```html
<amp-mathml>
  <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
    <mi>x</mi>
  </math>
</amp-mathml>
```
should behave the same as
```html
<amp-mathml data-formula="&lt;math xmlns=&quot;http://www.w3.org/1998/Math/MathML&quot; display=&quot;block&quot;&gt;&lt;mi&gt;x&lt;/mi&gt;&lt;/math&gt;"></amp-mathml>
```

This has the added value of potentially bypassing MathJax completely for browsers with native MathML support in the future.

**Comment by fstanis** [comment]
Good point, understood. The current approach definitely works, though it makes me wonder if `amp-mathml` was the correct name to use, as opposed to something like `amp-formula`, `amp-math` or even `amp-mathjax`.

**Comment by KENNYSOFT** [comment]
Maybe this is related to that `<amp-mathml>` doesn't support the non-block mode. \` delimiters are used in ASCIImath, with the non-block mode. See #19420 for more information.
