### ISSUE TITLE
Validator reports as error the  '_self' value of 'target' attribute

### ISSUE THREAD

**Issue by hugronaphor** [ampproject/amphtml#1703]
The error:
`The attribute 'target' in tag 'a' is set to the invalid value '_self'.`

The markup:
`<a href="http://www.theweek.co.uk/election-2015" target="_self">UK general election</a>`

This attribute value should be allowed even if this is a defualt value for 'target' attribute.

**Comment by cramforce** [comment]
The issue is that `_self` may be wrong in some embedding scenarios. This is why AMP pages should never rely on the default actually meaning `_self`. Allowing it would mean that embedders would have to explicitly do something else than the page is stating, which seems problematic.

**Comment by hugronaphor** [comment]
Ok, in this case we really need to push on Issue #994 as it's hard to validate the markup.
