### ISSUE TITLE
Loading indicator not showing for non-built elments

### ISSUE THREAD

**Issue by sparhami** [ampproject/amphtml#17035]
Loading indicators not shown until elements are already built. They should be present for extensions that are opted-in, even before the extension has loaded. The current behavior contradicts this comment in the code: https://github.com/ampproject/amphtml/blob/955a72276ac78ed1257e5516ab3adef06ae68e68/src/layout.js#L93-L94

The above logic living in v0.js is not actually useful since the loader is never actually rendered until the element has been upgraded/built. This is because the loading state being toggled relies on being `isInViewport_`:
https://github.com/ampproject/amphtml/blob/955a72276ac78ed1257e5516ab3adef06ae68e68/src/custom-element.js#L596-L598

Note: the else branch here calls `prepareLoading_`, but it does not actually show the loader. It creates the elements for the loader, but in a hidden state.

Which is only potentially set to `true` in `viewportCallback`:
https://github.com/ampproject/amphtml/blob/955a72276ac78ed1257e5516ab3adef06ae68e68/src/custom-element.js#L1127

Which relies on the element already being built:
https://github.com/ampproject/amphtml/blob/955a72276ac78ed1257e5516ab3adef06ae68e68/src/custom-element.js#L1107-L1116

Specifically, the following check avoids setting the element in the viewport if it is not built: https://github.com/ampproject/amphtml/blob/83f38950b9d1b544add22f93dc30554363541dab/src/service/resources-impl.js#L1584-L1597

**Comment by erwinmombay** [comment]
This issue doesn't have a category which makes it harder for us to keep track of it. @sparhami Please add an appropriate category.
