### ISSUE TITLE
Only install `puppeteer` and `@percy/puppeteer` as dev dependencies when running `gulp visual-diff`

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#17040]
As @rsimha [found out](https://github.com/ampproject/amphtml/pull/16390#issuecomment-405761791), these two dependencies combined are ~220 mb, when all other dependencies are much smaller (totalling at ~5 mb)

We should have these only installed when running `gulp visual-diff`

**Comment by rsimha** [comment]
These could be installed (and cached) on Travis via `.travis.yml`. For local runs, we can add a prerequisite step to `gulp visual-diff` that does the install if it's missing.

**Comment by rsimha** [comment]
A more urgent problem to fix: https://github.com/ampproject/amphtml/pull/16390/files#r204915317

**Comment by rsimha** [comment]
Assigning to @esthkim

**Comment by rsimha** [comment]
Here is the list of dependencies above 50 MB. Clearly, moving `puppeteer` to an on-demand install will greatly speed up development for most contributors.

```
npx cost-of-modules --no-install --include-dev
npx: installed 16 in 1.037s

Calculating...


┌────────────────────────────────────────────────┬───────────────┬─────────┐
│ name                                           │ children      │ size    │
├────────────────────────────────────────────────┼───────────────┼─────────┤
│ puppeteer                                      │ 16            │ 301.48M │
├────────────────────────────────────────────────┼───────────────┼─────────┤
│ jest                                           │ 449           │ 77.50M  │
├────────────────────────────────────────────────┼───────────────┼─────────┤
│ cssnano                                        │ 222           │ 64.97M  │
├────────────────────────────────────────────────┼───────────────┼─────────┤
│ @babel/helper-plugin-test-runner               │ 280           │ 55.08M  │
└────────────────────────────────────────────────┴───────────────┴─────────┘

```
