### ISSUE TITLE
AMP Story - Can't navigate from first page

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#17042]
Issue is reproducible in amp-version `1531800879103` when clicking on an article from Google Search results from an iOS device.

Steps to reproduce:
1. Enter private browsing mode
2. Type `cnn` in Google Search.
3. Click on "I am not my hair.." story.
4. Bug should be present.

**Comment by newmuis** [comment]
My first thought is that this is somehow related to prerendering; so far I've only seen this through Google's search integration, and not when directly accessing the document by URL.  It also seems that not every document is affected, which may suggest that the content of the document may have some relation to the bug (which, has happened in the past with prerendering).

**Comment by newmuis** [comment]
Lowering this to P1 since it only happens from Google's search viewer, for some (malformed?) documents, some of the time.

It looks like the story is built but not laid out (e.g. the `i-amphtml-layout-container` classes are not applied), so it must be short-circuiting somewhere in the layout callback.

One of the lines in the stack trace is from `bookend-component.js`, so I suspect that it may be the call to `initializeBookend_` causing problems, but need to continue investigating further.

**Comment by Enriqe** [comment]
The source mapping seems to be misleading and pointing to different lines than it should (at least in Safari). The line pointing to `bookend-component.js` is actually pointing to 

```
	Mg (amp-story-1.0.js:208:126)
```

Looking at the minified version, this seems to point to the `amp-story.js` constructor, in the request service for amp-story:

https://github.com/ampproject/amphtml/blob/bdb4cfe9f9b534fc04fd0276e9bdbc4c645d44ab/extensions/amp-story/1.0/amp-story.js#L197-L198

Following this stack trace which is repeated 21 times in the repro of the bug,
```
[Error] TypeError: undefined is not an object (evaluating 'a.obj')
	va (amp-story-1.0.js:6:192)
	q (amp-story-1.0.js:5:964)
	u (amp-story-1.0.js:16:557)
	nd (amp-story-1.0.js:88:154)
	md (amp-story-1.0.js:86:294)
	$e (amp-story-1.0.js:140:585)
	createdCallback (v0.js:224:93)
	b (v0.js:223)
	c (v0.js:222:759)
	define
	(anonymous function) (v0.js:60:465)
	Ph (v0.js:257:223)
	Oh (v0.js:256:533)
	Sl (v0.js:461:361)
	Rl (v0.js:461:328)
	(anonymous function) (v0.js:461:251)
	addDocFactory (v0.js:462:219)
	addElement (v0.js:461:236)
	(anonymous function)
	(anonymous function) (amp-story-1.0.js:307:196)
	f (amp-story-1.0.js:307:219)
	registerExtension (v0.js:458:565)
	(anonymous function) (v0.js:488:122)
	promiseReactionJob
```

and looking at `u (amp-story-1.0.js:16:557)` in the minified version points to:


https://github.com/ampproject/amphtml/blob/bdb4cfe9f9b534fc04fd0276e9bdbc4c645d44ab/extensions/amp-story/1.0/page-advancement.js#L269-L273

This would mean `element` would have to be null.

**Comment by newmuis** [comment]
Probably not a coincidence that this error appears 21 times in a 21-page story.  Since the `PageAdvancement` is instantiated per-page, @Enriqe's analysis above could make sense.
