### ISSUE TITLE
Make source code postprocessing invariant to sourcemaps

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#17061]
Current violations

- [x] `AMP_CONFIG` should get its own line
- [ ] `$internalRuntimeVersion$` gets replaced without updating sourcemaps. Could probably be changed to only use `AMP_CONFIG`
- [ ] `shortenLicense()` is run without updating sourcemaps.

**Comment by choumx** [comment]
Related: https://github.com/ampproject/error-tracker/issues/42#issuecomment-398132694
