### ISSUE TITLE
Parse json values as html

### ISSUE THREAD

**Issue by felerticia** [ampproject/amphtml#17076]
I have a json file like this:

{
  items: [
    {
       FullImage: "87acaed5c90d.jpg",
       Title: "sometext",
       description: "`<p id="imagenews"><img src='something'></p>`" ,
    }
  ]
}
how can I insert description into a div as an html? 

I tried
<div>{{description}}</div> 
but it was treated as plain string!!!

**Comment by jpettitt** [comment]
You can't. For security reason AMP doesn't allow insertion of raw html via templates.  The example you give demonstrates why, the `img` tag would make the page invalid AMP.

The way to do this is to put the html into the template and have the `img` url in the json file to populate the `src` attribute.
