### ISSUE TITLE
amp-story: Title logo FR

### ISSUE THREAD

**Issue by psdtomanythings** [ampproject/amphtml#17075]
Attached is the video of previews by Netflix. I really love the way Netflix has a logo at the top referring to the slide whose content is being loaded . A data attribute for this ( something like data-story-header-logo ) will correspond to the logo image. This brings in a much better visual reference to the story. 

![ezgif-3-b7f4e1e98f](https://user-images.githubusercontent.com/22929187/43190998-e008a9ae-9017-11e8-8273-066dcb60e8fb.gif)

**Comment by newmuis** [comment]
Hi @psdtomanythings, much of this can be achieved by placing elements at the top of the `amp-story-page` and using `fly-in` animations.  Tying this to the progress bar segments is probably out of scope at the time.

Does placing this inline work for your use case?

**Comment by newmuis** [comment]
Closing this, since a format-level primitive for this doesn't feel right here; publishers can achieve this by embedding the content directly into the page.
