### ISSUE TITLE
amp-date-picker not properly minified due to copyright notice

### ISSUE THREAD

**Issue by ro2ni3** [ampproject/amphtml#17077]
## What's the issue?
When we run lighthouse tests against our AMP pages amp-date-picker-0.1.js is being flagged as not being minified. I have checked https://cdn.ampproject.org/v0/amp-date-picker-0.1.js and it actually does look like it is minified except for the copyright notice which includes whitespace and new lines. I have checked the .js files for other components such as amp-list and amp-form and I see that they do not have a copyright notice and are therefore properly minified.

So would it be possible to remove/minify the copyright notice from the amp-date-picker-0.1.js file so that it can actually be considered as minified javascript?

![screen shot 2018-07-25 at 11 26 51](https://user-images.githubusercontent.com/32260852/43195688-b12c5afa-8ffd-11e8-9b09-31285bfc15a5.png)

![screen shot 2018-07-25 at 11 26 17](https://user-images.githubusercontent.com/32260852/43195693-b5e03ba2-8ffd-11e8-823d-2b2a0785d524.png)

**Comment by jpettitt** [comment]
The copyright notice is required by the license of the underlying code and cannot be removed. This is a misdetection by lighthouse.

**Comment by ro2ni3** [comment]
Is it possible to remove carriage returns and whitespace from the copyright?

**Comment by patrickhulce** [comment]
For the record, this was indeed a bug with Lighthouse's JS parser, esprima. LH is 1000% onboard with keeping copyright notices in code :)
