### ISSUE TITLE
Allow amp-date-picker to select a date period starting and ending on the same day

### ISSUE THREAD

**Issue by mcmd** [ampproject/amphtml#17082]
## What's the issue?
amp-date-picker doesn't allow to select a date period starting and ending on the same day

![image](https://user-images.githubusercontent.com/868584/43206586-029468cc-901e-11e8-8bf7-03a94a6e409a.png)

This feature would be needed, for example, for:
- Selling return airplane tickets on the same day (not unfrequent with business travelers)
- Booking a car just for one day
- Establishing the validity of a voucher, coupon or membership

Briefly describe the bug/feature request.

## How do we reproduce the issue?
Airbnb's calendar allows you to select periods starting and ending on the same date by clicking on the same twice on the same date, within the same picker:

![image](https://user-images.githubusercontent.com/868584/43211471-77c2d664-9029-11e8-802e-65e49578eb9d.png)

## What browsers are affected?
N/A

## Which AMP version is affected?
N/A

**Comment by ericlindley-g** [comment]
Thanks for filing this — definitely a feature gap we should address.

/cc @aghassemi

**Comment by mdiblasio** [comment]
This issue was [previously discussed](https://github.com/airbnb/react-dates/issues/24) in context of react-dates component library and can be fixed with support for `minimum-nights` attribute on date component ([originally noted](minimum-nights) as supported property).

[I was able to verify this works](https://github.com/ampproject/amphtml/compare/master...mdiblasio:minnights2). Should I submit PR?

**Comment by cvializ** [comment]
Yes if that resolves the issue, please do submit a PR! We really appreciate contributions like this, thank you for taking that initiative @mdiblasio

**Comment by santiago-noduscompany** [comment]
The event triggered with minimum-nights = 0 doesn't contain the date in the array and the values start and end are undefined.

**Comment by cvializ** [comment]
Hi @santiago-noduscompany thanks for reporting your issue. It doesn't seem related to this issue's subject, so I created issue #20727 for you.
