### ISSUE TITLE
Outbrain amp-ad resizing to 1px

### ISSUE THREAD

**Issue by eduardcotmrf** [ampproject/amphtml#17081]
We are facing a strange situation where an amp-ad of type outbrain is resizing to 1px sometimes. This is the amp-ad:

```
<amp-ad type="outbrain" width="300" height="1000" layout="responsive" data-widgetids="AR_1" data-stylefile="https://bc.marfeelcache.com/statics/www.thesocialpost.it/index/resources/outbrain.css">
</amp-ad>
```

It seems like the creativity it's loaded but sometimes it loads also another widget called BTD_1 that inserts itself outside the body of the amp-ad.

![screen shot 2018-07-25 at 17 12 08](https://user-images.githubusercontent.com/23262331/43210999-d5ea9d10-9030-11e8-99d6-d94a3f0e675a.png)

When this happens it gets resized to 1px and you can see the ad.

Any idea what's happening here @lironzluf @tomerlevy1 @bpaduch ?

For us it happens in this canonical AMP website: https://www.thesocialpost.it

**Comment by lannka** [comment]
This seems to be an "outbrain" issue. Did you get a chance to report the bug in their channel?

+ @lironzluf who implemented the "outbrain" plugin.

**Comment by lironzluf** [comment]
@eduardcotmrf Please submit this issue through your Outbrain account manager as this is not an AMP issue.

Thanks @lannka, feel free to close this.

cc: @urielster @tomerlevy1

**Comment by lannka** [comment]
Thanks for the quick response.
