### ISSUE TITLE
FR: amp-analytics: when batching requests, allow forced flush queued requests

### ISSUE THREAD

**Issue by cpapazian** [ampproject/amphtml#17099]
## What's the issue?

Batched requests are great! However, they would be even greater if there a way to force a queued batch of requests to flush. We were hoping that setting `important: true` would flush all requests in the queue when the "important" trigger was sent, but it looks like that just sends a single request.

## How do we reproduce the issue?

1. Set up AMP analytics with batching. Something like: 
```
{
  "requests": {
    "event": {
      "baseUrl": "https://www.example.com/amp/analytics?foo=bar",
      "batchInterval": [ 10 ]
    }
  "triggers": {
    "vis": {
      "on": "visible",
      "request": "event"
      "selector": "#some-id",
      "extraUrlParams": { 
        "time_ms": "${timestamp}"
      }
    },
    "click": {
      "on": "click",
      "important": true,
      "request": "event"
      "selector": "#some-id",
      "extraUrlParams": { 
        "time_ms": "${timestamp}"
      }
    }
  }
}
```
2. scroll to the element with `id="some-id"` and click it

The click event fires immediately. The visibility trigger doesn't fire until the batch interval (10 seconds) is reached. It would be great if `important: true` (or some other attribute) if when the click event fired, the visibility event (which would have been queued) was included.

## What browsers are affected?

all

## Which AMP version is affected?

all

**Comment by zhouyx** [comment]
@cpapazian Thank you for filing the feature request. This is exactly how we design and implement the `important: true` feature. 
> Setting important to true can help to flush batched request queue with some certain triggers.

I just tested with the config you provided, and I was able to see the visibility event trigger sent out together with the click trigger before 10 sec. 
![image](https://user-images.githubusercontent.com/5419904/43231347-e3b719b0-9020-11e8-9eeb-200bf970eab8.png)
See that two `time_ms` params are being appended to the request. I suggest you call them in different names to differentiate them on your end. 

This would be a bug if it doesn't work for your page. If so please let me know how to reproduce it, could you provide us with a link to reproduce? Thank you!

**Comment by cpapazian** [comment]
thanks @zhouyx. we're doing another round of testing now. i've been able to get the `important: true` to force a flush in testing, and our metrics show that this is working better in production. i think we're good for now!
