### ISSUE TITLE
🌸 Cherry pick request for #17094 into #17097 (Pending)

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#17100]
**GitHub issue your cherry pick is fixing:**

Issue #17093

**PR that you are requesting a cherry pick for:**

PR #17094

**Release(s) you requesting this cherry pick into:**

Release Issue #17097

Production Release? NO
Canary release? YES  Release Issue #17097

This breaks `amp-story` on desktop, making the experience look incorrect and/or broken (potentially with very bad crops) for all users using the desktop UI.

**Comment by cramforce** [comment]
Approved

**Comment by choumx** [comment]
Cherry-picked in RTV 1532641868525.
