### ISSUE TITLE
Disable margin-top for initial bookend heading

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#17103]
The first heading in the list comes below the sharing section, which has its own spacing.  The double spacing ends up looking very large:

![screen shot 2018-07-25 at 5 20 52 pm](https://user-images.githubusercontent.com/1651960/43228310-37e3226e-902f-11e8-9d49-672ff1f61e39.png)

**Comment by Enriqe** [comment]
Closed via #17248
