### ISSUE TITLE
amp-accordion with animate flickers

### ISSUE THREAD

**Issue by roelvanhoof** [ampproject/amphtml#17117]
## What's the issue?

If you create an amp-accordion with multiple sections and give the accordion the animate property every section except the last one flickers when clicked. This problem is visible on the ampbyexample website too (https://ampbyexample.com/components/amp-accordion/) in the section Animated Accordions

## How do we reproduce the issue?

Just look at the ampbyexample website

## What browsers are affected?

I have tested this on mac os chrome and safari ios

## Which AMP version is affected?

version 1531800879103

**Comment by aghassemi** [comment]
Thanks for the report @roelvanhoof 
/to @cathyxz @sparhami to take a look.
setting to P2 - Soon since it is related to quality of a newly released feature

**Comment by MkVII** [comment]
Hi,
The flickering is present again.
It seems to only affect text, and strangely sometimes it flickers and other times it doesn't.
The flickering is present on the AMP page here:
(https://amp.dev/documentation/examples/components/amp-accordion/#animated-accordion))

When you press section 1 or section 3.
