### ISSUE TITLE
Validation for video src must be HTTPS

### ISSUE THREAD

**Issue by Meggin** [ampproject/amphtml#1711]
Hey,

As far as I can tell, the validator doesn't enforce that the video src must be HTTPS.

In the amp-video spec, however, it states that it must be.

Also, there might already be an issue for this. I searched for one, but couldn't find it, so creating a new one. Remove if it's a duplicate.

**Comment by Gregable** [comment]
This is being worked on, but I don't think there was a github issue so far.

**Comment by Gregable** [comment]
\cc @honeybadgerdontcare

**Comment by dvoytenko** [comment]
Yeah, I don't see an issue. Let's use this one, @Gregable

**Comment by Gregable** [comment]
This is fixed in github and will be live on cdn.ampproject.org within an hour or so.
