### ISSUE TITLE
amp-date-picker uses deprecated window.webkitStorageInfo

### ISSUE THREAD

**Issue by RonnieWinter** [ampproject/amphtml#17119]
## What's the issue?

When running Lighthouse tests against our AMP pages, there is a warning on amp-date-picker-01.js saying that it is using window.webkitStorageInfo (line 140) which is deprecated.
It says that navigator.webkitTemporaryStorage or navigator.webkitPersistentStorage should be used instead.

![screen shot 2018-07-26 at 17 06 10](https://user-images.githubusercontent.com/32260852/43274144-3d3a3b72-90f6-11e8-9bbb-01a73b1bb300.png)

**Comment by cvializ** [comment]
I agree we shouldn't trigger browser deprecation warnings. Will investigate.

**Comment by aghassemi** [comment]
note sure if we can do much since this is from 3P code. closing for now
