### ISSUE TITLE
AMP stories design spoiled on Chrome on Desktop

### ISSUE THREAD

**Issue by AutadeJS** [ampproject/amphtml#17121]
## What's the issue?
AMP stories looking spoiled on Chrome on Desktop, while they are looking good on other browsers.

## How do we reproduce the issue?
Check any AMP story on Desktop on Chrome

## What browsers are affected?
Chrome 68

All browsers? Some specific browser? What device type?
Chrome only. On Desktop, Windows 10 OS

## Which AMP version is affected?
AMP stories

## Is this a new issue? Or was it always broken?
New issue

**Comment by choumx** [comment]
I think this is a dupe of #17093.

**Comment by newmuis** [comment]
@AutadeJS, do you have a screenshot of specifically what is broken?  Do you agree that the brokenness that you are seeing is what is outlined in #17093?
