### ISSUE TITLE
New lint rules in build-system/eslint-rules aren't always copied to node-modules/eslint-plugin-amphtml-internal

### ISSUE THREAD

**Issue by addieachan** [ampproject/amphtml#17133]
- Newly added lint rules weren't showing up in the node-modules/eslint-plugin-amphtml-internal folder which would cause gulp lint to fail
- Rules were seen in build-system/eslint-rules so there is a problem with linking
- Fixed locally by:
1) 'yarn unlink' in the build system/eslint-rules
2)  'yarn link' in the build system/eslint-rules
3) 'yarn link eslint-plugin-amphtml-internal' in the main directory

**Comment by rsimha** [comment]
Running `yarn unlink` before `yarn link` fixed the issue, so we're now doing that.
