### ISSUE TITLE
The 'min-font-size/max-font-size' attribute in 'amp-fit-text' doesn't works inside an 'amp-list' block

### ISSUE THREAD

**Issue by diegosomar** [ampproject/amphtml#17130]
If I use the `<amp-fit-text>` WITHIN and `<amp-list>` with the attribute `min-font-size` or `max-font-size`, the rendered text not follow the font-size rule.

But, in the same page, if I put the same code OUTSIDE the `<amp-list>`, it works correctly.

In other words, I have an `amp-list` which has some items. The text within these items, sometimes exceed the item height. To solve this, I'm using the component `amp-fit-text`.

This component increase or decrease the font-size, then, the text fits in the container. But this component can do an ellipsis, if I define a min font size. Works fine outside the `amp-list`, but the `min-font-size` attribute is not being followed. In this case, the text is being fitted in the content, rather than use the min font size and creates an ellipsis.

To reproduce, simply creates an `<amp-list>` and in the loop, puts the text inside an `<amp-fit-text>` with the attribute `min-font-size=40`. If the container is small, with this font-size, the text have to creates an ellipsis.

This [fiddle](https://jsfiddle.net/po5mwLka/2/) shows the problem.

I tested in Google Chrome 67.0.3396.99 64 bits. In the test, the viewport had 320px width.

AMP Version 1531800879103.

**Comment by sebastianbenz** [comment]
//cc @aghassemi @choumx
