### ISSUE TITLE
Variables in URL host of amp-list src cannot be substituted after AMP Cache URL rewriting

### ISSUE THREAD

**Issue by cheneytsai** [ampproject/amphtml#17142]
## What's the issue?

AMP Cache appears to be rewriting URLs in amp-list src such that uppercase AMP Variables (ex: AMPDOC_HOST) in path are being converted to lowercase which breaks URL substitution.

## How do we reproduce the issue?

There's a test page [https://www.airbnb.com/amp/s/Navarre--FL](https://www.airbnb.com/amp/s/Navarre--FL), and you can verify that the AMPDOC_HOST variable in the amp-list src resolves to airbnb.com and the banner at the top of the page renders correctly.

Checking the source of the document: AMPDOC_HOST is properly uppercase
`<amp-list width="auto" height="75" layout="fixed-height" src="https://AMPDOC_HOST/amp/kochava?referrer=DOCUMENT_REFERRER&amp;canonical_path=CANONICAL_PATH&amp;canonical_url=CANONICAL_URL&amp;amp_id=CLIENT_ID(amp-cookie-fallback)&amp;channel=seo_amp&amp;source_url=AMPDOC_URL" id="kochava-banner" data-amp-replace="AMPDOC_HOST">`

If you look at the AMP Cache version: https://www-airbnb-com.cdn.ampproject.org/v/s/www.airbnb.com/amp/s/Navarre--FL?usqp=mq331AQECAEoAQ%3D%3D&amp_js_v=0.1, the banner doesn't show. Console throws an error about the lowercase ampdoc_host. 

If you look at the source, you'll find that the AMPDOC_HOST variable in amp-list src is now lowercase: `<amp-list class="i-amphtml-layout-fixed-height i-amphtml-layout-size-defined" height=75 i-amphtml-layout=fixed-height id=kochava-banner layout=fixed-height src="https://ampdoc_host/amp/kochava?referrer=DOCUMENT_REFERRER&amp;canonical_path=CANONICAL_PATH&amp;canonical_url=CANONICAL_URL&amp;amp_id=CLIENT_ID(amp-cookie-fallback)&amp;channel=seo_amp&amp;source_url=AMPDOC_URL"`

It seems to suggest that a rewrite changing the case seemed to have happened and thus variable substitution didn't happen properly causing the XHR to fail.

(Note: AMPDOC_HOST being the improper variable to use here is noted, but the issue might still stand for other variables like CANONICAL_HOST)

## What browsers are affected?

Test on Chrome 68 and 67. Desktop and Android Mobile.

## Which AMP version is affected?

011531800879103

**Comment by rudygalfi** [comment]
@calebcordry Could you take a look? cc @ericlindley-g for the amp-list bit.

**Comment by calebcordry** [comment]
I am not sure I am the right person. The variable service appears to be doing what it should, but the cache seems to be rewriting this url.

cc/ @Gregable for his input.

**Comment by gtyj25dd** [comment]
🤔🤔

**Comment by Gregable** [comment]
This is an interesting case. The AMP cache has no knowledge of these replacements, so this is just an URL. URLs get normalized in the AMP cache for security reasons. DNS is not case-sensitive, so the hostname component of URLs is not case-sensitive and the AMP Cache's parser is not going to notice the difference between these two URLs when normalizing.

**Comment by Gregable** [comment]
If I make a wider comment, I feel like this URL replacement scheme is error-prone as designed. Imagine if the domain name of a site was AMPDOC_HOST.com. Not super likely, admittedly, but there are definitely some more likely to collide names in that [namespace](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md), such as `counter`, `title`, etc. Especially considering that the matches are simple substring, so "MYCOUNTER.COM" would match unintentionally.

While it doesn't directly solve this particular referenced issue, I would recommend that variable substitution only occur in the path, query, and fragment components of URLs.

**Comment by cheneytsai** [comment]
Note also that the original test case URLs in the issue won't work anymore. The pages have been updated to static representations of the domain to circumvent the issue. The underlying problem still exists though potentially.

**Comment by calebcordry** [comment]
I agree the current design is flawed. We have often talked about how nice it would be to have a clear indication that something is a macro, but unfortunately so many people rely on the existing format.

cc/ @zhouyx @lannka For their input. I am actually surprised we haven't seen something like the `MYCOUNTER.COM` collision before.

**Comment by lannka** [comment]
So we need to make a decision if URL substitution in host name should be supported in AMP. i.e., is there valid use cases.

@cheneytsai seems for your use cases, can actually put a static value there to work around, as you already did so.

Depending the decision, here are the solutions
1) if we're not supporting it, then we need to document it clearly. we can also do sanity check in runtime and print out user errors
2) if we're going to support it, 2 options
-- a) Change cache logic to not alternate letter cases in URLs   
-- b) introduce new macro names that are all small cases

If we have to go with 2), I'd love to explore option a) more, since b) will be very tricky to do.

**Comment by lannka** [comment]
After discussing with @Gregable , we think we will not support substitution in URL host, unless there is more specific use cases.
