### ISSUE TITLE
How to hide empty space that results from undelivered ad?

### ISSUE THREAD

**Issue by drobertsacbj** [ampproject/amphtml#1714]
If an ad does not deliver via GPT (aka Doubleclick) it creates a hole the size of the expected ad. Normally I'd use the "collapse empty divs" functionality to deal with it. How would this work in amp?

**Comment by dvoytenko** [comment]
@sriramkrish85 what are the options here?

**Comment by rudygalfi** [comment]
cc @kashyapnitin who may know this

**Comment by sriramkrish85** [comment]
you can use
`window.context.noContentAvailable`

documented here.
https://github.com/ampproject/amphtml/blob/master/ads/README.md#methods-available-to-the-ad
