### ISSUE TITLE
PAGE_LOAD_TIME URL replacement not working

### ISSUE THREAD

**Issue by uncompiled** [ampproject/amphtml#1716]
URL replacements are not working for all documented variables.

In the [AMP Variable Substitutions](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#page_load_time) documentation, it lists PAGE_LOAD_TIME as being available.  The URL replacement [appears to be implemented](https://github.com/ampproject/amphtml/blob/master/src/url-replacements.js#L185), however, the variable is not being replaced when the request is fired.

Some variables are correctly being replaced, such as CANONICAL_URL, RANDOM, SCREEN_HEIGHT, etc.

Example of variables received by the event receiver:
```
pageLoadTime: PAGE_LOAD_TIME
random: 0.2894816743209958
screenHeight: 480
screenWidth: 320
```

**Comment by rudygalfi** [comment]
@avimehta Can you take a look?

Also, updated the title to be more narrowly scoped to the value known not to work. If there are others, please let us know!

**Comment by dvoytenko** [comment]
It's in canary, but hasn't been released yet. I believe the release is later today. But if you'd like to try it out sooner - you can opt-in into dev-channel here: https://cdn.ampproject.org/experiments.html

**Comment by rudygalfi** [comment]
Good catch. @uncompiled Let us know if that fixes it and we can close this. Thanks!

**Comment by uncompiled** [comment]
This works in the dev-channel, so this issue can be closed.
