### ISSUE TITLE
[amp-carousel] - Transition between images is broken for RTL in type=slides

### ISSUE THREAD

**Issue by cadoogi** [ampproject/amphtml#17178]
## What's the issue?

When moving forward and backwards in the gallery lightbox, the transition of the images is very buggy, not smooth and looks like it goes trough 3 images every time. 

## How do we reproduce the issue?

I have created a test page for that:  

https://www.trvbox.co.il/amp-test.html

1. Scroll down in the article to the first gallery image
2. click in image
3. in lightbox click forward button  (or swipe in mobile)

## What browsers are affected?

Tested in chrome (Dekstop) and Safari (Iphone)

## Which AMP version is affected?

Latest version

**Comment by cathyxz** [comment]
Minimal repro: https://codepen.io/cathyxz/pen/qyoQVQ

**Comment by aghassemi** [comment]
dup of https://github.com/ampproject/amphtml/issues/16605
