### ISSUE TITLE
Implement default placeholder / loading state for amp-twitter

### ISSUE THREAD

**Issue by sparhami** [ampproject/amphtml#17171]
Implement a default placeholder for `<amp-twitter>` to show the user that content is loading. Ideally, the user should be able to tell what kind of content is loading (i.e. something from Twitter). Other extensions might use a similar approach if it makes sense.

**Comment by sparhami** [comment]
A prototype of what this might look like: https://somber-wallaby.glitch.me/

**Comment by aghassemi** [comment]
closing for #20237
