### ISSUE TITLE
[amp-lightbox-gallery]  - Only opens once

### ISSUE THREAD

**Issue by cadoogi** [ampproject/amphtml#17177]
## What's the issue?

If you close the lightbox and click on an image again it just removes the page scrollbar and no lightbox is opening. the page just gets stuck.  

Tested both on chrome and Firefox (Desktop) and On mobile (iphone 8, Google Pixel)

## How do we reproduce the issue?

This is even happens in the AMP example page:

https://ampbyexample.com/components/amp-lightbox-gallery/

1. click on first example image
2. close
3. click on the next example image

page stuck with no lightbox

## What browsers are affected? - 

Tested both on chrome and Firefox (Desktop) and On mobile (iphone 8, Google Pixel)

## Which AMP version is affected?

Latest version

**Comment by cathyxz** [comment]
Thanks a lot for filing! This issue should be solved by https://github.com/ampproject/amphtml/pull/17145 and will arrive in production in 2 weeks.

**Comment by cathyxz** [comment]
This is now working in canary.

**Comment by cathyxz** [comment]
Verified fix in https://github.com/ampproject/amphtml/releases/tag/1533692711873
