### ISSUE TITLE
[FEATURE REQUEST] amp-image-slider P1 features

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#17174]
- Being able to seekTo a specific state in the image slider
- You can specify the % of each image that shows up to default. The total for both images should add up to 100%.
- Attributes that allow customization
  - step-size
  - disable-hint
  - hint-reappear
  - hint-reappear-interval

**Comment by aghassemi** [comment]
these are all implemented as far as I see on https://amp.dev/documentation/components/amp-image-slider
