### ISSUE TITLE
Add countdown to amp-live-list refresh time

### ISSUE THREAD

**Issue by bjalford** [ampproject/amphtml#17182]
Add option to show a countdown to to the refresh of the amp-live-list.

An example can be seen here: https://www.eurosport.co.uk/football/international-champions-cup/2018/live-paris-saint-germain-atletico-madrid_mtc1037416/live.shtml

![image](https://user-images.githubusercontent.com/738672/43394126-86098058-93f1-11e8-93ea-880ebf09d68f.png)

**Comment by choumx** [comment]
Nice FR, this would be cool.

/to @ericlindley-g @aghassemi for prioritization.

**Comment by ericlindley-g** [comment]
+1 This would be great —  setting at P3 on the assumption that this is a nice-to-have feature (as opposed to an absolute blocker) and  /cc @erwinmombay for visibility

**Comment by aghassemi** [comment]
related https://github.com/ampproject/amphtml/issues/17254
