### ISSUE TITLE
amp-bind: Support amp-selector[multiple] events

### ISSUE THREAD

**Issue by mazhor90** [ampproject/amphtml#17183]
On a multiple select when I want to update AMP state by "change:AMP.setState({foo: event.value})" event.value doesn't returns all selected values its returns always first selected value

**Comment by kul3r4** [comment]
Maybe related to this, I cannot get the multiple selections when using `amp-selector` and `svg` with `amp-bind`. Is the syntax I am using correct?

You can reproduce https://amp-demos.glitch.me/amp-selector-with-svg.html

@choumx FYI

**Comment by mazhor90** [comment]
I had tested `event.selectedOptions` on an `amp-selector` it's works fine. But in my issue I asked about get all selected values on a simple `select multiple`.
For example I have select
```
<select multiple name="foo" on="change:AMP.setState({filters: {foo: event.value }})>
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
</select>
```
In this case `event.value` returns only first selected value.

**Comment by choumx** [comment]
Ah, sorry I misunderstood your request. Created#18863 to track that.
