### ISSUE TITLE
shadow dom: AMPDOC_URL variable not set

### ISSUE THREAD

**Issue by justforfun** [ampproject/amphtml#17193]
## What's the issue?
We noticed that often the value of the AMPDOC_URL is incorrect when an AMP document is injected via <amp-viewer> in a Progressive Web App.
When the problem occurs the AMPDOC_URL doesn't assume any value.

## How do we reproduce the issue?
You can reproduce the issue here:
https://rep.repubblica.it/pwa/generale/2018/07/29/news/la_ricerca_di_un_leader_forte-202948431/

The canonical URL of the document is:
<link rel="canonical" href="https://rep.repubblica.it/pwa/generale/2018/07/29/news/la_ricerca_di_un_leader_forte-202948431/" >

while the URL of the AMP injected via <amp-viewer> is:
https://rep.repubblica.it/ws/detail/generale/2018/07/29/news/la_ricerca_di_un_leader_forte-202948431/

In the AMP document there are several references to the AMPDOC_URL variable
for instance the JSON object in the HEAD of the document, required by amp-access:

```html
<script id="amp-access" type="application/json">
    {
         "login": {
              "login": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/login?rid=READER_ID&fbia=AMPDOC_URL",
              "loginpw": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/login?rid=READER_ID&fbia=AMPDOC_URL",
              "registration": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/login?page=registration&rid=READER_ID&fbia=AMPDOC_URL",
              "logout": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/logout?rid=READER_ID",
              "purchasedesk": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/purchase?rid=READER_ID&source=REP_PWS_DESK&wt_g=rep_pwl_desk.paywall.campagna_pwl.rep_repubblica_it/pwa/generale/2018/07/29/news/la_ricerca_di_un_leader_forte-202948431/.att.&fbia=AMPDOC_URL",
              "purchasemob": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/purchase?rid=READER_ID&source=REP_PWS_MOB&wt_g=rep_pwl_mob.paywall.campagna_pwl.rep_repubblica_it/pwa/generale/2018/07/29/news/la_ricerca_di_un_leader_forte-202948431/.att.&fbia=AMPDOC_URL",
              "purchaseheaderslim": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/purchase?rid=READER_ID&wt_g=rep_atp_sherp.slim..rep_repubblica_it/pwa/generale/2018/07/29/news/la_ricerca_di_un_leader_forte-202948431/.abb.&fbia=AMPDOC_URL",
              "commenta": "https://rep.repubblica.it/data/widgets/check-sso.html?rid=READER_ID&url=CANONICAL_URL&hash_id=AUTHDATA(profile.hash_id)",
              "purchasedeskphldr": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/purchase?rid=READER_ID&source=REP_PWP_DESK&wt_g=rep_pwl_desk.paywall.campagna_pwl.rep_repubblica_it/pwa/generale/2018/07/29/news/la_ricerca_di_un_leader_forte-202948431/.att.&fbia=AMPDOC_URL",
              "purchasemobphldr": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/purchase?rid=READER_ID&source=REP_PWP_MOB&wt_g=rep_pwl_mob.paywall.campagna_pwl.rep_repubblica_it/pwa/generale/2018/07/29/news/la_ricerca_di_un_leader_forte-202948431/.att.&fbia=AMPDOC_URL",
              "purchasedeskflbk": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/purchase?rid=READER_ID&source=REP_PWF_DESK&wt_g=rep_pwl_desk.paywall.campagna_pwl.rep_repubblica_it/pwa/generale/2018/07/29/news/la_ricerca_di_un_leader_forte-202948431/.att.&fbia=AMPDOC_URL",
              "purchasemobflbk": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/purchase?rid=READER_ID&source=REP_PWF_MOB&wt_g=rep_pwl_mob.paywall.campagna_pwl.rep_repubblica_it/pwa/generale/2018/07/29/news/la_ricerca_di_un_leader_forte-202948431/.att.&fbia=AMPDOC_URL"

         },
         "pingback": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/pingback?rid=READER_ID&ts=TIMESTAMP&url=CANONICAL_URL",
         "authorization": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/authorization?rid=READER_ID&ts=TIMESTAMP&url=CANONICAL_URL",
         "authorizationFallbackResponse": {"showContent": false}
    }
</script>
```

On the AMP side, if you click on the link "Accedi" (on the top right hand corner of the page)
on the browser's development tool, track the related network request you get this:

https://rep.repubblica.it/api/checkpw-v1/premium/amp/login?rid=amp-YzFHQjQ9js4YzTZFHOmF3g&fbia=https%3A%2F%2Frep.repubblica.it%2Fws%2Fdetail%2Fgenerale%2F2018%2F07%2F29%2Fnews%2Fla_ricerca_di_un_leader_forte-202948431%2F%3Faccount_linking_token%3DAS7xo0zsI9-ZGAcn_3YlGmCSE_azAg0QPWWYApQs3ttsUotCCp1-Un3L0JvNDPaoKSUqpZg7YI-wsW2ZRk14OudkkLDGzOo4-7kgS8_YXIDHMhU9i1X7-td8icJE1TaKi2mFKMEmNleSxUnpckWsaPgjb4I85W1r22qAMYiW-F6tfgGAerudJWdFPwX-xnIgC7E0zR8hUH0DShWg6RxwdFqyXHz68w3bsyREhFS2QaGzlx5i2QHt__YY0MzZh1w7-wPTX_dOiS2GXAnNmMJ8BkC8UfvEMLhhdImkAGulka5yrToNZHJWEqY_u2olKmkCFuk5QUw2xF9KumoVqfblxs1qtoooAHQbD3_7F_hEC76McwRTB3MSOnm_UXm5rcjhafdk22Jv0L53BON6FBCVXEqQz7QyOWCkVl5RwZTWU1QjUdNn6OYGitTLgilokB9Z_25YMuixK69frBiKlmAIT9B-RoFsBBQV8zaNnHwOqKOHXVIItdE8yXIh_srYFTWBArYKA3wQ5rfHWArrcClsfHhT%26redirect_uri%3Dhttps%253A%252F%252Fwww.facebook.com%252Fsubscriptions%252Faccount-linking%252Fconfirm%252F%26surface%3Dlocked_article%26article_url%3Dhttps%253A%252F%252Frep.repubblica.it%252Fpwa%252Fgenerale%252F2018%252F07%252F29%252Fnews%252Fla_ricerca_di_un_leader_forte-202948431%252F&return=https%3A%2F%2Fcdn.ampproject.org%2Fv0%2Famp-login-done-0.1.html%3Furl%3Dhttps%253A%252F%252Frep.repubblica.it%252Fws%252Fdetail%252Fgenerale%252F2018%252F07%252F29%252Fnews%252Fla_ricerca_di_un_leader_forte-202948431%252F%253Faccount_linking_token%253DAS7xo0zsI9-ZGAcn_3YlGmCSE_azAg0QPWWYApQs3ttsUotCCp1-Un3L0JvNDPaoKSUqpZg7YI-wsW2ZRk14OudkkLDGzOo4-7kgS8_YXIDHMhU9i1X7-td8icJE1TaKi2mFKMEmNleSxUnpckWsaPgjb4I85W1r22qAMYiW-F6tfgGAerudJWdFPwX-xnIgC7E0zR8hUH0DShWg6RxwdFqyXHz68w3bsyREhFS2QaGzlx5i2QHt__YY0MzZh1w7-wPTX_dOiS2GXAnNmMJ8BkC8UfvEMLhhdImkAGulka5yrToNZHJWEqY_u2olKmkCFuk5QUw2xF9KumoVqfblxs1qtoooAHQbD3_7F_hEC76McwRTB3MSOnm_UXm5rcjhafdk22Jv0L53BON6FBCVXEqQz7QyOWCkVl5RwZTWU1QjUdNn6OYGitTLgilokB9Z_25YMuixK69frBiKlmAIT9B-RoFsBBQV8zaNnHwOqKOHXVIItdE8yXIh_srYFTWBArYKA3wQ5rfHWArrcClsfHhT%2526redirect_uri%253Dhttps%25253A%25252F%25252Fwww.facebook.com%25252Fsubscriptions%25252Faccount-linking%25252Fconfirm%25252F%2526surface%253Dlocked_article%2526article_url%253Dhttps%25253A%25252F%25252Frep.repubblica.it%25252Fpwa%25252Fgenerale%25252F2018%25252F07%25252F29%25252Fnews%25252Fla_ricerca_di_un_leader_forte-202948431%25252F

where you can see the parameter:

fbia=AMPDOC_URL

that's the correct behaviour.

On the PWA side, if you click on the link Accedi (at the top right hand corner of the page)
on the browser's development tool, track the related network request you get this:

https://rep.repubblica.it/api/checkpw-v1/premium/amp/login?rid=amp-YzFHQjQ9js4YzTZFHOmF3g&return=https%3A%2F%2Fcdn.ampproject.org%2Fv0%2Famp-login-done-0.1.html%3Furl%3Dhttps%253A%252F%252Frep.repubblica.it%252Fpwa%252Fgenerale%252F2018%252F07%252F29%252Fnews%252Fla_ricerca_di_un_leader_forte-202948431%252F%253Faccount_linking_token%253DAS7xo0zsI9-ZGAcn_3YlGmCSE_azAg0QPWWYApQs3ttsUotCCp1-Un3L0JvNDPaoKSUqpZg7YI-wsW2ZRk14OudkkLDGzOo4-7kgS8_YXIDHMhU9i1X7-td8icJE1TaKi2mFKMEmNleSxUnpckWsaPgjb4I85W1r22qAMYiW-F6tfgGAerudJWdFPwX-xnIgC7E0zR8hUH0DShWg6RxwdFqyXHz68w3bsyREhFS2QaGzlx5i2QHt__YY0MzZh1w7-wPTX_dOiS2GXAnNmMJ8BkC8UfvEMLhhdImkAGulka5yrToNZHJWEqY_u2olKmkCFuk5QUw2xF9KumoVqfblxs1qtoooAHQbD3_7F_hEC76McwRTB3MSOnm_UXm5rcjhafdk22Jv0L53BON6FBCVXEqQz7QyOWCkVl5RwZTWU1QjUdNn6OYGitTLgilokB9Z_25YMuixK69frBiKlmAIT9B-RoFsBBQV8zaNnHwOqKOHXVIItdE8yXIh_srYFTWBArYKA3wQ5rfHWArrcClsfHhT%2526redirect_uri%253Dhttps%25253A%25252F%25252Fwww.facebook.com%25252Fsubscriptions%25252Faccount-linking%25252Fconfirm%25252F%2526surface%253Dlocked_article%2526article_url%253Dhttps%25253A%25252F%25252Frep.repubblica.it%25252Fpwa%25252Fgenerale%25252F2018%25252F07%25252F29%25252Fnews%25252Fla_ricerca_di_un_leader_forte-202948431%25252F

where the parameter:

fbia=AMPDOC_URL

is missing (the problem we noticed).

## What browsers are affected?

The issue has been detected on all browsers.

## Which AMP version is affected?
AMP Version 1531800879103

**Comment by kul3r4** [comment]
@cvializ would you be able to help with this?

**Comment by cvializ** [comment]
Hey, @kul3r4! @danielrozenberg is the PWA-eng owner

@danielrozenberg would you be able to triage and investigate?

**Comment by sparhami** [comment]
Hmm, looking at the page in question, it seems like the button is in a different AMP doc from the rest of the page. In addition, it has a slightly different `<amp-access>` config:

```html
<script id="amp-access" type="application/json">{
		   "login": {
		        "login": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/login?rid=READER_ID",
		        "loginpw": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/login?origin=MV_ACC_PAY&rid=READER_ID",
		        "registration": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/login?page=registration&origin=MV_PAY&rid=READER_ID",
		        "logout": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/logout?rid=READER_ID",
		        "purchase": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/purchase?rid=READER_ID",
		        "commenta": "https://rep.repubblica.it/data/widgets/check-sso.html?rid=READER_ID&url=CANONICAL_URL&hash_id=AUTHDATA(profile.hash_id)"


		   },
		   "pingback": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/pingback?rid=READER_ID&ts=TIMESTAMP&url=CANONICAL_URL",
		   "authorization": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/authorization?rid=READER_ID&ts=TIMESTAMP&url=CANONICAL_URL",
		   "authorizationFallbackResponse": {"showContent": false}
		}</script>
```

The content of the page seems to be a different AMP document with the following config:

```html

             {
             "login": {
                  "login": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/login?rid=READER_ID&fbia=AMPDOC_URL",
                  "loginpw": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/login?rid=READER_ID&fbia=AMPDOC_URL",
                  "registration": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/login?page=registration&rid=READER_ID&fbia=AMPDOC_URL",
                  "logout": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/logout?rid=READER_ID",
                  "purchasedesk": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/purchase?rid=READER_ID&source=REP_PWS_DESK&wt_g=rep_pwl_desk.paywall.campagna_pwl.rep_repubblica_it/pwa/generale/2018/07/29/news/la_ricerca_di_un_leader_forte-202948431/.att.&fbia=AMPDOC_URL",
                  "purchasemob": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/purchase?rid=READER_ID&source=REP_PWS_MOB&wt_g=rep_pwl_mob.paywall.campagna_pwl.rep_repubblica_it/pwa/generale/2018/07/29/news/la_ricerca_di_un_leader_forte-202948431/.att.&fbia=AMPDOC_URL",
                  "purchaseheaderslim": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/purchase?rid=READER_ID&wt_g=rep_atp_sherp.slim..rep_repubblica_it/pwa/generale/2018/07/29/news/la_ricerca_di_un_leader_forte-202948431/.abb.&fbia=AMPDOC_URL",
                  "commenta": "https://rep.repubblica.it/data/widgets/check-sso.html?rid=READER_ID&url=CANONICAL_URL&hash_id=AUTHDATA(profile.hash_id)",
                  "purchasedeskphldr": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/purchase?rid=READER_ID&source=REP_PWP_DESK&wt_g=rep_pwl_desk.paywall.campagna_pwl.rep_repubblica_it/pwa/generale/2018/07/29/news/la_ricerca_di_un_leader_forte-202948431/.att.&fbia=AMPDOC_URL",
                  "purchasemobphldr": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/purchase?rid=READER_ID&source=REP_PWP_MOB&wt_g=rep_pwl_mob.paywall.campagna_pwl.rep_repubblica_it/pwa/generale/2018/07/29/news/la_ricerca_di_un_leader_forte-202948431/.att.&fbia=AMPDOC_URL",
                  "purchasedeskflbk": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/purchase?rid=READER_ID&source=REP_PWF_DESK&wt_g=rep_pwl_desk.paywall.campagna_pwl.rep_repubblica_it/pwa/generale/2018/07/29/news/la_ricerca_di_un_leader_forte-202948431/.att.&fbia=AMPDOC_URL",
                  "purchasemobflbk": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/purchase?rid=READER_ID&source=REP_PWF_MOB&wt_g=rep_pwl_mob.paywall.campagna_pwl.rep_repubblica_it/pwa/generale/2018/07/29/news/la_ricerca_di_un_leader_forte-202948431/.att.&fbia=AMPDOC_URL"

             },
             "pingback": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/pingback?rid=READER_ID&ts=TIMESTAMP&url=CANONICAL_URL",
             "authorization": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/authorization?rid=READER_ID&ts=TIMESTAMP&url=CANONICAL_URL",
             "authorizationFallbackResponse": {"showContent": false}
             }
```

Notably:

```
"login": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/login?rid=READER_ID",
```

vs.

```
"login": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/login?rid=READER_ID&fbia=AMPDOC_URL",
```

When the standalone page is loaded, the header appears to be a part of the page, which is why it is using the config that you are expecting.

From my understanding, the URL replacements are just a find and replace (and are not related to the URL parameter syntax), so I do not think that a missing URL param would be due to the replacement logic.

One thing to note is that the AMPDOC_URL is the current URL of the page, rather than the URL the document was loaded as. So, in this case, it would be "https://rep.repubblica.it/pwa/generale/2018/07/29/news/la_ricerca_di_un_leader_forte-202948431/", regardless of which AMP doc you do it from.

**Comment by justforfun** [comment]
Hmm, I don't understand the last comment.
If I go here (the PWA page with the AMP injected through shadow dom):
https://rep.repubblica.it/pwa/generale/2018/08/24/news/mausoleo_franco_spagna_spostato-204839700/?qs=querystr

and inspect the code I see this in the amp-access config  (see screenshot)
```"login": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/login?rid=READER_ID&fbia=AMPDOC_URL```
<img width="948" alt="schermata 2018-08-24 alle 21 53 00" src="https://user-images.githubusercontent.com/477983/44605489-d5bdbb80-a7e9-11e8-8e10-5d399da93cda.png">


If I click on the "Accedi" button on the placed on the top right corner of the page I'm redirected here:

```https://rep.repubblica.it/api/checkpw-v1/premium/amp/login?rid=amp-oBE4XABQYzQ0tlRSazbQrQ&return=https%3A%2F%2Fcdn.ampproject.org%2Fv0%2Famp-login-done-0.1.html%3Furl%3Dhttps%253A%252F%252Frep.repubblica.it%252Fpwa%252Fgenerale%252F2018%252F08%252F24%252Fnews%252Fmausoleo_franco_spagna_spostato-204839700%252F%253Fqs%253Dquerystr```

That is the fbia parameter with the associated value are completely missing.

If I go here (the plain and simple AMP page)
https://rep.repubblica.it/ws/detail/generale/2018/08/24/news/mausoleo_franco_spagna_spostato-204839700/?qs=querystr

and inspect the code I see this in the amp-access config  (see screenshot) that is the same code I have in the PWA page:
```"login": "https://rep.repubblica.it/api/checkpw-v1/premium/amp/login?rid=READER_ID&fbia=AMPDOC_URL```

<img width="1026" alt="schermata 2018-08-24 alle 21 56 32" src="https://user-images.githubusercontent.com/477983/44605677-96439f00-a7ea-11e8-8be0-c0de9e833e45.png">

But if I click on the "Accedi" button I'm redirected here:
```https://rep.repubblica.it/api/checkpw-v1/premium/amp/login?rid=amp-oBE4XABQYzQ0tlRSazbQrQ&fbia=https%3A%2F%2Frep.repubblica.it%2Fws%2Fdetail%2Fgenerale%2F2018%2F08%2F24%2Fnews%2Fmausoleo_franco_spagna_spostato-204839700%2F%3Fqs%3Dquerystr&return=https%3A%2F%2Fcdn.ampproject.org%2Fv0%2Famp-login-done-0.1.html%3Furl%3Dhttps%253A%252F%252Frep.repubblica.it%252Fws%252Fdetail%252Fgenerale%252F2018%252F08%252F24%252Fnews%252Fmausoleo_franco_spagna_spostato-204839700%252F%253Fqs%253Dquerystr```

that is the expected and correct behaviour

**Comment by sparhami** [comment]
This is what I see for the PWA case:

![1wvsng32ctu](https://user-images.githubusercontent.com/1410321/44606815-3ece1080-a7a3-11e8-9444-a276d8822d9c.png)

I see what appears two be two different AMP documents, one for the button and one for the content of the page. The article itself seems to have the same amp-access config that you mentioned. The other AMP doc appears to not have `&fbia=AMPDOC_URL`.

**Comment by justforfun** [comment]
Hi,
you are right, we missed to add the parameter to the <amp-access> json config of the AMP document: ```https://rep.repubblica.it/data/widgets/amp-access-login.html```
Thank you for your precious support!

**Comment by sparhami** [comment]
> Thank you for your precious support!

Not a problem! Closing this issue.
