### ISSUE TITLE
reset-on-refresh breaks list with local data binding

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#17202]
Only reproducible in 7/26 Canary (1532641868525).

- Enabled Dev channel
- Visit a category page on AliExpress ( e.g. https://m.aliexpress.com/category/200002455/Deodorants-Antiperspirants.html?categoryName=Deodorants%20&%20Antiperspirants&spm=a2g0n.category-amp.leafcat.Deodorants%20&%20Antiperspirants )
- Click on `filter` and pick something like `Price (Low to High)`
- Note that loading indicator does not disappear after reload.

May be due to https://github.com/ampproject/amphtml/pull/16843

**Comment by aghassemi** [comment]
(filter action on aliexpress is also broken, pretty sure same root cause related)

**Comment by choumx** [comment]
I'll take a look later tonight.
