### ISSUE TITLE
amp-story - Hint UI is broken

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#17207]
When using current 7/26 Canary (1532641868525), the Next/Previous hint UI that shows up on swipe does not show up anymore.

Setting to P0 since it is a regression in Canary, adjust priority as needed.

**Comment by newmuis** [comment]
@enriqe @gmajoulet please investigate

**Comment by aghassemi** [comment]
I will be patching Canary with another fix tomorrow before releasing, let me know and I can wait for this one too. Thanks.
