### ISSUE TITLE
🌸 Cherry pick request for 17209 into 17097

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#17215]
**Replace *everything* in angle brackets in the title AND body of this issue.  If you have any questions see the [cherry pick documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-picks).**

**GitHub issue your cherry pick is fixing:**

Issue #17202

**PR that you are requesting a cherry pick for:**

PR #17209

**Release(s) you requesting this cherry pick into:**

Production Release? No

Canary release? Yes
Release Issue #17097

**Why does this issue meet the [cherry pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?  Be specific.**

amp-list reloading with local data does not remove the loading indicator div which fully covers the list items making it look like refresh is hanging at loading state. Breaks filter/sort for m.aliexpress.com.

/cc @cramforce

**Comment by cramforce** [comment]
Approved. Commented on cherry-pick process to make it more clear when the cherry-pick is into canary.
