### ISSUE TITLE
🌸 Cherry pick request for 17214 into 17097

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#17216]
**Replace *everything* in angle brackets in the title AND body of this issue.  If you have any questions see the [cherry pick documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-picks).**

**GitHub issue your cherry pick is fixing:**

Issue #17207

**PR that you are requesting a cherry pick for:**

PR #17214

**Release(s) you requesting this cherry pick into:**

Production Release? No

Canary release? Yes
Release Issue #17097

**Why does this issue meet the [cherry pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?  Be specific.**

It is a regression that causes the amp-story hint UI (when user swipes instead of tap) not appear.

/cc @cramforce

**Comment by cramforce** [comment]
Approved. Commented on cherry-pick process to make it more clear when the cherry-pick is into canary.
