### ISSUE TITLE
amp-fx-flying carpet initial alignment is broken 

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#17223]
Only reproducible with current 7/26 Canary (1532641868525)
Tested on OSX/Chrome with https://ampbyexample.com/components/amp-fx-flying-carpet/

Prod:
![prod-fx-flying](https://user-images.githubusercontent.com/2099009/43489076-9cac3bd6-94d0-11e8-87bd-a61ac869f967.png)

Canary:
![canary-fx-flying](https://user-images.githubusercontent.com/2099009/43489071-98ef003c-94d0-11e8-8a05-fc656a2138b8.png)

Setting to P0 since it is a regression in Canary and breaks fx-flying-carpet.

Introduced by either #16809 or #16821

Needs to be fixed or reverted for cherry pick on  #17097

/cc @jridgewell any thoughts for a quick fix?

**Comment by rsimha** [comment]
Once the P0 issue is fixed, we should add a better visual test for this component, since the [ABE test page](https://percy.io/ampproject/amphtml/builds/901449/view/53034368/375?browser=firefox&mode=base) doesn't adequately test it.

See #11418

/cc @danielrozenberg

**Comment by jridgewell** [comment]
Dropping to P1, since it's only affecting opt-in canary.

**Comment by aghassemi** [comment]
@jridgewell I am using P0 for anything that's blocking release this week.

**Comment by jridgewell** [comment]
`onMeasureChanged` isn't fired when the custom element is upgraded.

**Comment by aghassemi** [comment]
(issue is in 1% canary that was supposed to go to prod today. I am delaying prod until this and few other ones are patched before promoting)
