### ISSUE TITLE
Amp-carousel type="carousel" - clicking navigation arrows fast enough, can shift slides.

### ISSUE THREAD

**Issue by SimonHogstromRonbol** [ampproject/amphtml#17234]
## What's the issue?

If you have an amp-carousel with the carousel type, and you are using it on a wide display to get more than a single image on the screen at a time, clicking the navigational arrows can shift the perspective so that on the sides you will see only half of an image rather than shifting from image to image as normal.

## How do we reproduce the issue?

1. head to https://www.online-results.dk/ and scroll all the way to the bottom and you will see the amp-carousel.
2. double click the navigational arrow to the right, this might take a few tries.

ive captured this screenshot of the issue.
https://i.imgur.com/s3ILP6r.jpg

## What browsers are affected?

i was able to reproduce this on desktop for the following browsers:
- Chrome
- Firefox
- Internet Explorer

## Which AMP version is affected?

this was tested in AMP version 1531800879103

**Comment by aghassemi** [comment]
@SimonHogstromRonbol Thanks for the report. I can repro on desktop when clicking super fast.

**Comment by jridgewell** [comment]
@nainar: Reopening due to revert.
