### ISSUE TITLE
amp-bind: Bind limit exceed problem

### ISSUE THREAD

**Issue by ziyed** [ampproject/amphtml#17233]
## What's the issue?

I have developed an AMP project where I have created an amp-list pulling data from endpoint. Inside the amp-list it has 24 tiles and on each tile some numbers of operands to manage single item properties and features. I have also developed pagination to change page to page by changing amp-list through [src] change technique. It has more than 10k+ pages. 

After browsing 5 or 6 more pages, 2000 bind limit exceed happen and site totally frozen. No bind related execution can not be done then.

Though I have a pagination more than 10k+ pages and each page have 24 items with identical operands so there always be a chance of exceed limit of 2000, which is now happening after browsing 5/6 pages consecutively.

How this situation can be resolved on AMP project now and limit exceed should not halt the process? 

Idea: Can it be possible to add some params on AMP html which will detect to free the limit exceed binding thus for some special cases where bind limit has some problem with project goal then limit binding issue can be resolved.

Please suggest.
 
## What browsers are affected?

All browsers

## Which AMP version is affected?

AMP Version: 1531800879103

**Comment by choumx** [comment]
Thanks for filing this. Copy this use case to #17233 and closing as dupe.
