### ISSUE TITLE
Google Search Console Validator disagrees with Development Validator - amp-youtube

### ISSUE THREAD

**Issue by jerimiahwelch** [ampproject/amphtml#17238]
## What's the issue?

Google Search Console is identifying pages with valid amp-youtube components as "missing" the youtube video. 

While the development version of the validator does not throw warnings about this, the Google Search Console version does. 

I submitted feedback on google search console yesterday. I am submitting a bug here in case it might be related to the structure of the amp page or an amp validator coordination issue.

## How do we reproduce the issue?

This page (and 600 like it) are flagged as missing a you-tube video in google search console but validate locally. The specific google search console error is "Content mismatch: Missing embedded video":

https://amp.luckyvitamin.com/p-579053-mutant-mass-muscle-mass-gainer-vanilla-ice-cream-15-lbs

Here you can see that the amp pages have the video that is reported as missing:
![amppageshavevideo](https://user-images.githubusercontent.com/1224514/43530342-313cf25e-9562-11e8-9b9e-0da05dd02035.png)

Here you can see how the GSC Validator and Development Validator disagree:
![gscandlocalvalidationdisagree](https://user-images.githubusercontent.com/1224514/43530362-3b82c0e0-9562-11e8-80ce-579be3b03347.png)

Thank you.

**Comment by aghassemi** [comment]
@jerimiahwelch Would you please bring this up in Google Search forum instead? https://productforums.google.com/forum/#!topicsearchin/webmasters/category$3Aaccelerated-mobile-pages-amp%7Csort:relevance%7Cspell:false Folks monitoring AMPProject GitHub mostly deal with the open-source library and are not knowledgable on integration with search engines.

**Comment by jerimiahwelch** [comment]
@aghassemi - Thank you for the link. I'll post there.
