### ISSUE TITLE
apm-access not working on cached version

### ISSUE THREAD

**Issue by elpulga** [ampproject/amphtml#17239]
## What's the issue?

AMP-access response in cached version return access: false even though user is logged in.
Works fine in non-cached version. 

## What browsers are affected?

Seems to happen in chrome and mobile safari. Desktop firefox works fine

## Which AMP version is affected?
1531800879103

**Comment by jpettitt** [comment]
This is almost certainly a CORS issue.  If it works on the orign but does not work cross origin make sure you are setting all the headers required by the[ CORS spec](https://github.com/ampproject/amphtml/blob/master/spec/amp-cors-requests.md) 

If that is not the issue please provide a url we can use to reproduce the error.

**Comment by jpettitt** [comment]
@epulga is this still a problem?
