### ISSUE TITLE
AMP Cache optimizations make already-well-optimized images bigger (and worse-looking)

### ISSUE THREAD

**Issue by eeeps** [ampproject/amphtml#17247]
## What's the issue?

Feeding an already well-optimized image into the AMP cache can result in an image which is larger (and lesser-quality, due to [generation loss](https://cloudinary.com/blog/why_jpeg_is_like_a_photocopier)) than the original.

## How do we reproduce the issue?

Compare (desktop Chrome, DPR: 2):

https://ericportis.com/etc/amp-imgs/

Image 1: 8.3 KB
Image 2: 53.5 KB

to

https://ericportis-com.cdn.ampproject.org/c/s/ericportis.com/etc/amp-imgs/

Image 1: 11.7 KB
Image 2: 69.9 KB

**Comment by aghassemi** [comment]
@Gregable would you be able to coordinate this with the AMP Cache team?

**Comment by jgluk** [comment]
Tracked internally as 111636720.

**Comment by Gregable** [comment]
Closing bug as this is an AMP Cache specific. That project is tracking internally.
