### ISSUE TITLE
Add layout validation for amp-install-serviceworker

### ISSUE THREAD

**Issue by Meggin** [ampproject/amphtml#1727]
Only NODISPLAY layout is supported for amp-install-serviceworker.

Update https://github.com/ampproject/amphtml/blob/master/validator/validator.protoascii to properly include this validation.

**Comment by jmadler** [comment]
Is this still needed?

**Comment by powdercloud** [comment]
It looks like nodisplay is indeed the only layout specified for amp-install-serviceworker. See here:
https://github.com/ampproject/amphtml/blob/master/extensions/amp-install-serviceworker/0.1/validator-amp-install-serviceworker.protoascii
So, perhaps it's done?

**Comment by jmadler** [comment]
Agreed
