### ISSUE TITLE
Replace non-provided macros by empty strings in RTC endpoints

### ISSUE THREAD

**Issue by Spark-NF** [ampproject/amphtml#17273]
Following PR #16905

## What's the issue?

For RTC endpoints, if some parameters/macros are optional and not provided by a publisher, they will be passed to the endpoint as-is. For example, given the following endpoint (where the publisher is to provide a ZONE_ID but the SUB_ID is optional):

```js
test: {
    url: 'https://www.test.com/amp/rtc?zid=ZONE_ID&sid=SUB_ID&...',
    macros: ['ZONE_ID', 'SUB_ID'],
    disableKeyAppend: true,
},
```

If the publisher uses this `amp-ad` configuration:

```html
<amp-ad
    width="300"
    height="250"
    type="doubleclick"
    data-slot="/654321/AdUnit"
    rtc-config='{
        "vendors": {
            "test": {
                "ZONE_ID": 123456
            }
        },
        "timeoutMillis": 700
    }'>
</amp-ad>
```

Then the URL called will be `https://www.test.com/amp/rtc?zid=123456&sid=SUB_ID&...`. My suggestion is to default all macros to an empty string, and therefore call  `https://www.test.com/amp/rtc?zid=123456&sid=&...` instead.

Given this might break current endpoints relying on this behavior, maybe this feature can be hidden behind a flag the same way `disableKeyAppend` is.

## How do we reproduce the issue?

1. Setup AMP RTC with any vendor
2. Forget or purposedly ignore one of their macros
3. The called URL will contain the raw macro name

[Demo](https://output.jsbin.com/rurarafoya/)

As you can see in the JSBin example, the URL called is `https://cdn.krxd.net/userdata/v2/amp/123456?segments_key=SEGMENTS_KEY&kuid_key=USER_KEY&__amp_source_origin=http%3A%2F%2Fnull.jsbin.com` with the `SEGMENTS_KEY` and `USER_KEY` left unchanged.

## What browsers are affected?

All browsers AFAIK.

## Which AMP version is affected?

All versions AFAIK, including the current 1533168552513.

**Comment by Spark-NF** [comment]
Ping @bradfrizzell

**Comment by bradfrizzell** [comment]
hey @Spark-NF 
apologies for the slow response, I was out on vacation the last 10 days 
I think this is a reasonable request, and I'll try to carve out some time in the next week or two to make the change.

**Comment by bradfrizzell** [comment]
Hey again @Spark-NF 
Unfortunately I don't think I am going to have time to look into this for a bit. In the meantime, it seems like this should be an easy case to handle on the server. Sorry about this, if this is a major blocker for you please let me know.
