### ISSUE TITLE
Macro $BASE64 needs to handle unicode

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#17282]
as [pointed out](https://github.com/ampproject/amphtml/issues/13371#issuecomment-390601122) by @adamkasprowicz

> Please note that base64 - atob - has an unicode problem, that needs to be fixed as well
https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding

**Comment by calebcordry** [comment]
Closed by #17290
