### ISSUE TITLE
 Error: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#17280]
Lots of recent errors with `Error: Cannot read property 'style' of null`. Coming from `animateScrollIntoViewInternal_`

See error [CJ3N8aeY447ncw](http://go/ampe/CJ3N8aeY447ncw)

**Comment by aghassemi** [comment]
@jridgewell this error comes from pages with `amp-fx-flying-carpet` in `prerender` mode. https://ampbyexample.com/components/amp-fx-flying-carpet/#visibilityState=prerender 

It does not seem to have any user-facing impact (renders fine after viewer changes it from `prerender` to `visible`) however it is creating a lot of errors, so keeping it at P1.

(the stack trace in the error is totally wrong).

**Comment by jridgewell** [comment]
This is due to https://github.com/ampproject/amphtml/pull/17225. `firstAttachedCallback` is called during upgrade, which happens before `buildCallback` (which creates the element that we're trying to get the `.style` prop from).

**Comment by jridgewell** [comment]
Fixed in https://github.com/ampproject/amphtml/pull/17294.

Given the number of errors, we should cherry-pick Canary, maybe Prod.
