### ISSUE TITLE
amp-video tests are routinely timing out on Travis

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#17309]
It's a different video component each time, but the timeouts look the same.

https://travis-ci.org/ampproject/amphtml/jobs/411942051#L1412
https://travis-ci.org/ampproject/amphtml/jobs/411851659#L1420
https://travis-ci.org/ampproject/amphtml/jobs/411814260#L1420

**Comment by rsimha** [comment]
@aghassemi @cvializ @alanorozco This is still happening. Seems like the same root cause. Perhaps more tests need to be fixed?

https://travis-ci.org/ampproject/amphtml/jobs/414717416#L1423

```
DESCRIBE => amp-ooyala-player
  DESCRIBE =>  
    IT => renders a V3 player
      ✗ Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by aghassemi** [comment]
@rsimha Thanks @rsimha, I had missed a few of them. #17461 for the fix, hopefully it will be all of them now.
