### ISSUE TITLE
amp-image-lightbox broken animation if amp-img has layout="intrinsic".

### ISSUE THREAD

**Issue by zkeram** [ampproject/amphtml#17303]
## What's the issue?

While using `<amp-img>` with `layout="intrinsic"` and `<amp-image-lightbox>` the showing animation (zooming the image) is broken.

### Why it happens

Inside `<amp-img>` with `layout="intrinsic"` there are generated 2 images

1. An image to keep the shape of the image
2. The main image (from `src` attribute)

The first image is selected to be animated, but the second one should have been selected. (There is used dom.elementByTag)

### How to fix it

https://github.com/ampproject/amphtml/blob/master/extensions/amp-image-lightbox/0.1/amp-image-lightbox.js#L905 - Don't get `sourceImage_` by tag, but by class `class="i-amphtml-fill-content i-amphtml-replaced-content"` or get the last `<img>` tag.

## How do we reproduce the issue?

Use `<amp-img>` with `layout="intrinsic"` with `<amp-image-lightbox>`. https://jsfiddle.net/6g0jbt75/

## What browsers are affected?

All browsers.

## Which AMP version is affected?

Always broken.

**Comment by cathyxz** [comment]
We'll need to apply the same fix to `<amp-lightbox-gallery>`.

**Comment by nainar** [comment]
### First Timers Only
We know figuring out the process for contributing to an open source project can be intimidating, so we created this issue as a way for you to learn the ropes.  (If you feel comfortable contributing to open source projects, please leave this issue for someone else.)

### What you will need to know

The fix lies here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-image-lightbox/0.1/amp-image-lightbox.js#L905 - Don't get sourceImage_ by tag, but by class class="i-amphtml-fill-content i-amphtml-replaced-content" or get the last <img> tag.

Please also make the relevant change in `<amp-lightbox-gallery>`. The change lies here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js#L916

### Background

To ensure that the transition on opening an image in lightbox mode or in the lightbox gallery works.

### The bug

Please also test that the fix works in both `<amp--image-lightbox>` and `<amp-lightbox-gallery>`. Demo link here: https://jsfiddle.net/6g0jbt75/

-->
### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.  (If you [join the AMP Project](https://goo.gl/forms/T65peVtfQfEoDWeD3) we'll be able to assign this issue to you after you've claimed it.)
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] [Sign the Contributor License Agreement](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#contributor-license-agreement) before creating a Pull Request.  (If you are contributing code on behalf of a corporation start this process as early as possible.)

- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).

- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review).  Mention `closes Issue <this issue number>` in the description.
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).


Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

### Questions?


If you have questions ask in this issue or on your Pull Request (if you've created one) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

**Comment by techhtml** [comment]
Close this please :)

**Comment by cathyxz** [comment]
Yup! Thank you for your contribution.
