### ISSUE TITLE
Amp-list to generate different elements based on JSON values

### ISSUE THREAD

**Issue by felerticia** [ampproject/amphtml#17302]
Hi I have an amp-list that outputs bunch of divs nice and easy, my only problem is that I want the first output item to have some different attributes from others.

Here's an example:

```
<amp-list layout="responsive" width="40" height="67" src="someurl"  items="." single-item=".">
 <template type="amp-mustache">  
     {{#NewsPaperPages}}
        <div role="tab" class="tabButton" option="{{PageNum}}" aria-selected="false" tabindex="0"></div>
      {{/NewsPaperPages}}
  </template>
</amp-list>
```
which renders to this:

```
<div role="tab" class="tabButton" option="1" aria-selected="false" tabindex="0"></div>
<div role="tab" class="tabButton" option="2" aria-selected="false" tabindex="0"></div>
<div role="tab" class="tabButton" option="3" aria-selected="false" tabindex="0"></div>
```
But I'd like the first item to be :

`<div role="tab" class="tabButton" option="1" aria-selected="true" tabindex="0" selected ></div>`
where aria-selected is set to true and selected attribute has added

**Comment by jaygray0919** [comment]
answered here: https://stackoverflow.com/questions/51684927/amp-list-to-render-different-elements-based-on-json-value/51689630#51689630

**Comment by vamshi5889** [comment]
@felerticia Try below
```
<div role="tab" class="tabButton" option="{{PageNum}}" [aria-selected]="'{{PageNum}}' == '1' ? 
      true : false" tabindex="0"> 
</div>
```

**Comment by choumx** [comment]
I don't think there's a way to do this with mustache.js on the client/template side. You can do this by adding a key to the first array object in the server response JSON and adding the appropriate mustache section. E.g.

```
{{#NewsPaperPages}}
  {{#FirstPage}}
    <div selected role="tab" class="tabButton" option="{{PageNum}}" aria-selected="false" tabindex="0"></div>
  {{/FirstPage}}
  {{^FirstPage}}
    <div role="tab" class="tabButton" option="{{PageNum}}" aria-selected="false" tabindex="0"></div>
  {{/FirstPage}}
{{/NewsPaperPages}}
```

If you can't change the server response, then you'll need #13891.
