### ISSUE TITLE
[Feature Request] amp-carousel should have badge with what slide we are on

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#17317]
It should have the badge counter on the top-{left/right} depending on ltr or rtl. 

cc @spacedino @aghassemi @ericlindley-g

**Comment by nainar** [comment]
This also adds information from an accessibility stand point. It can be an attribute on the carousel to allow for it to be backward compatible.

**Comment by vamshi5889** [comment]
@nainar , I would suggest to have `carousel-indicators` (dots with current one highlighted) instead. And with placement (top-left, bottom-left, top-right, bottom-right etc.)

**Comment by ericlindley-g** [comment]
+1   Would be great to parameterize amp-carousel so that there's some kind of pagination indicator that developers can toggle if they want this.  

FWIW, https://github.com/ampproject/amphtml/issues/2852 links to some similar requests

**Comment by aghassemi** [comment]
closing per carousel v2
