### ISSUE TITLE
Support amp-vimeo, amp-dailymotion amp-soundcloud in validator

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#1732]
- amp-vimeo
- amp-dailymotion
- amp-soundcloud

Blocks #1471

**Comment by cramforce** [comment]
CC @honeybadgerdontcare

**Comment by cramforce** [comment]
Also added amp-dailymotion to this list.

**Comment by Gregable** [comment]
These are fixed. Should be rolled out to javascript in an hour or so.
