### ISSUE TITLE
amp-mustache-0.2: amp-lightbox[scrollable] attribute removed

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#17335]
Here are two examples

1
https://afdsi.org/test/amp_lightbox_tooltip_3/

image fails in Safari
image works in mobile Chrome with 'request desktop site'
image works in mobile Mozilla with 'request desktop site'
image (sometimes) fails in Mozilla desktop
image works in Chrome desktop
image works in Edge desktop

2
https://afdsi.org/test/about_us/
Lightbox is scrollable with mustache 0.1
Lighbox is not scrollable with mustache 0.2

also, there is a bug in the google translate script (@cvializ Carlos is aware)

**Comment by aghassemi** [comment]
@jaygray0919 For #1, the Wikipedia endpoint does not return AMP's expected CORS headers. If you look at error log on mobile, error mentions that fetch failed. There is simply no way to use Wikipedia endpoints currently unless you proxy it from your servers and add the CORS headers AMP needs. See https://www.ampproject.org/docs/fundamentals/amp-cors-requests 

#2 is a bug and `scrollable` is dropped. /to @choumx

**Comment by jaygray0919** [comment]
@aghassemi Ali, the endpoint is Wikidata. Here is the JSON page:
https://www.wikidata.org/wiki/Special:EntityData/Q161426.json

When I check that page with the CORS tester, it responds with a 200 status. Here is the test:

https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fwww.wikidata.org%2Fwiki%2FSpecial%3AEntityData%2FQ161426.json&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote

Here is the report:

```
Fired XHR event: loadstart
Fired XHR event: readystatechange
Fired XHR event: readystatechange
Fired XHR event: progress
Fired XHR event: progress
Fired XHR event: readystatechange
Fired XHR event: load

XHR status: 200
XHR status text: OK
XHR exposed response headers:

cache-control: private, s-maxage=0, max-age=0, must-revalidate
content-type: application/json; charset=UTF-8
last-modified: Thu, 19 Jul 2018 21:50:58 GMT

Fired XHR event: loadend`
```

The AMP page works on all desktop browsers, and also works on mobile Chrome and Mozilla when using 'request desktop site'

Am I missing something?

**Comment by jaygray0919** [comment]
Addendum: here is the header form the Wikidata page:

Response header
```
X-Firefox-Spdy | h2
-- | --
accept-ranges | bytes
access-control-allow-origin | *
age | 80
backend-timing | D=64345 t=1533760467365274
cache-control | private, s-maxage=0, max-age=0, must-revalidate
content-encoding | gzip
content-type | application/json; charset=UTF-8
date | Wed, 08 Aug 2018 20:35:47 GMT
last-modified | Thu, 19 Jul 2018 21:50:58 GMT
p3p | CP="This is not a P3P policy! See https://www.wikidata.org/wiki/Special:CentralAutoLogin/P3P for more info."
server | mw1268.eqiad.wmnet
strict-transport-security | max-age=106384710; includeSubDomains; preload
vary | Accept-Encoding
via | 1.1 varnish (Varnish/5.1), 1.1 varnish (Varnish/5.1), 1.1 varnish (Varnish/5.1)
x-analytics | WMF-Last-Access=08-Aug-2018;WMF-Last-Access-Global=08-Aug-2018;https=1
x-cache | cp1085 miss, cp2004 hit/2, cp2004 miss
x-cache-status | hit-local
x-client-ip | 24.217.226.105
x-content-type-options | nosniff
x-frame-options | DENY
x-powered-by | HHVM/3.18.6-dev
x-varnish | 423468435, 608410429 618080304, 366243909
```

Request header
```

Accept | text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
-- | --
Accept-Encoding | gzip, deflate, br
Accept-Language | en-US,en;q=0.5
Connection | keep-alive
Cookie | WMF-Last-Access=08-Aug-2018;  WMF-Last-Access-Global=08-Aug-2018; wikidatawikiUserName=Jaygray0919;  GeoIP=US:MO:Ballwin:38.56:-90.54:v4
Host | www.wikidata.org
If-Modified-Since | Thu, 19 Jul 2018 21:50:58 GMT
Upgrade-Insecure-Requests | 1
User-Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0

```

**Comment by cvializ** [comment]
Hi @jaygray0919, thanks for reporting this! I used the Safari debugger with an iPhone and found this error in the console
<img width="598" alt="screen shot 2018-08-08 at 16 57 50" src="https://user-images.githubusercontent.com/2363700/43863986-604ea450-9b2c-11e8-8747-73d5845e4fc2.png">

Safari expected to receive a header `Access-Control-Allow-Origin:  afdsi.org` which isn't present. You'll have to use a proxy as @aghassemi suggested to add that header to the response to satisfy the browsers' CORS requirements.

Since this looks like an issue with your specific document I'll close this issue for now, but if you determine it's a bug in AMP we can reopen.

**Comment by cvializ** [comment]
Oops just noticed the `scrollable` issue. Reopening for that.

**Comment by aghassemi** [comment]
@jaygray0919 It should have validated, that's our bug see #17373 (pages won't work on AMP cache if CORS is not satisfied)

**Comment by jaygray0919** [comment]
OK, we're gonna have to figure how to proxy that header. I'll speak with our sys-admin. Thanks for clarifying where the problem originates; will share this thread with our SA to implement a solution.

As you see above, the current solution works on all desktops and on mobile Chrome/Mozilla when using the 'request desktop site'. I'm assuming that if we proxy the correct header, the solution will work in native mode (not desktop mode) for mobile browsers.

**Comment by jaygray0919** [comment]
Bottom line here: well proxy the header and report back the result.

**Comment by aghassemi** [comment]
@jaygray0919 actually looks like we allow non-CORS if `credential` attribute is not specified, so you should be good without proxiying it. The actual problem is that wikipedia endpoint returns bad results when that Url is hit from mobile UA. You can try that outside of AMP, just call `await fetch('https://www.wikidata.org/wiki/Special:EntityData/Q161426.json')` from Chome console when emulating a mobile phone, it fails. Without emulation it works.

**Comment by aghassemi** [comment]
@jaygray0919 As long as the endpoint allows normal CORS, you should be good. dbpedia.org returns `Access-Control-Allow-Origin: *` which should be enough to make it work with `amp-list`

**Comment by jaygray0919** [comment]
@aghassemi Ali, we updated our methods and have a Wikidata and Wikimedia solution.
Here is the previous example, modified:
  https://afdsi.com/tooltip/
It works on mobile (including Safari) and desktop

We'll update to mustache 0.2 later this week per @choumx William advice (experiment mode)

We are still wrangling the DBpedia + SPARQL problem. No good solution yet for that issue.
We're looking at a `node.js` intercept solution rather than a web server solution (nginx or apache).
We gotta make the DBpedia+SPARQL solution work, since we can't get to DBpedia data from Wikidata.
Wikidata does give us a federated query endpoint, so that will meet many of our requirements.
We may be able to federate DBpedia from Wikidata, but have never done this (never made sense until now with the CORS+HTTPS requirements)
