### ISSUE TITLE
The attribute 'rel' in tag 'link rel=' is set to the invalid value 'manifest'

### ISSUE THREAD

**Issue by nuxodin** [ampproject/amphtml#1735]
Is it not useful to make web apps containing amp-documents?

**Comment by cramforce** [comment]
@nuxodin We generally do not allow link tags with significant side effects as AMP files are designed to be embedded into various contexts. There is, however, `amp-install-serviceworker` as a modern equivalent to manifests. ServiceWorkers make more sense as they can upgrade the AMP to your full app, which you can't do with manifests.
