### ISSUE TITLE
amp-mustache-0.2: <noscript> rendered as text on Samsung Internet

### ISSUE THREAD

**Issue by ikselll** [ampproject/amphtml#17353]
## What's the issue?

BUG - After upgrade amp-mustache to v0.2 code from noscript tag inside amp-img shows in browser as plaintext.

## How do we reproduce the issue?

Steps to reproduce:
1. Open https://gist.github.com/ikselll/8238d28aa1ec1d23229eee9b59aee464
2. copy/paste in the amp-playground https://ampbyexample.com/playground/
3. Open on Samsung Internet browser.
4. Code from noscript tag of amp-img is visible as plaintext.

## What browsers are affected?

Samsung Internet 7.2.10.33 (on Samsung Galaxy S8)
Samsung Internet 7.2.10.33 (on Samsung Galaxy S5)

## Which AMP version is affected?

1533253141109

**Comment by choumx** [comment]
Thanks for the report, we'll fix this ASAP.

**Comment by choumx** [comment]
Hmm, `<noscript>` tags should not be rendered at all in either amp-mustache 0.1 or 0.2. Why do you need to use `<noscript>` in a `<template>`? I don't think it will be rendered by the browser if JS is enabled or disabled.

Android Emulator of Galaxy phones don't appear to have Samsung Internet installed. Will try to locate a real test device.

**Comment by choumx** [comment]
I was able to repro on a Galaxy S6 with Samsung Internet 6.2 and 7.2. Samsung Internet is not an official [AMP-supported browser](https://www.ampproject.org/support/faqs/supported-browsers), but I'll see if there's a simple fix we can apply here.

**Comment by ikselll** [comment]
@choumx Good point. I just follow amp-img usage docs.

**Comment by choumx** [comment]
Couldn't find a reasonable fix for this unfortunately. We'll need to wait for an upstream fix in Samsung Internet.
