### ISSUE TITLE
Design Review 2018-08-29 20:00 UTC (amp-subscriptions arbitrary score factors, amp-consent CMP)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#17357]
Time: [2018-08-29 20:00 UTC](https://www.timeanddate.com/worldclock/meeting.html?year=2018&month=08&day=29&iv=0) ([add to Google Calendar](http://www.google.com/calendar/event?action=TEMPLATE&text=AMP%20Project%20Design%20Review&dates=20180829T200000Z/20180829T210000Z&details=https%3A%2F%2Fhangouts.google.com%2Fhangouts%2F_%2Fgoogle.com%2Famp-eng-desrev))
Location: [Video conference via Google Hangouts](https://hangouts.google.com/hangouts/_/google.com/amp-eng-desrev)

The AMP Project holds weekly engineering [design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md).  **We encourage everyone in the community to participate in these design reviews.**

If you are interested in bringing your design to design review, read the [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md) and add a link to your design doc by the Monday before your design review.

When attending a design review please read through the designs *before* the design review starts.  This allows us to spend more time on discussion of the design.

We rotate our design review between times that work better for different parts of the world as described in our [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md), but you are welcome to attend any design review.  If you cannot make any of the design reviews but have a design to discuss please let mrjoro@ know on [Slack](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#discussion-channels) and we will find a time that works for you.

**Comment by jpettitt** [comment]
Refactor amp-subscription to support arbitrary score factors, design doc to follow.

**Comment by zhouyx** [comment]
CMP Integration with AMP consent. I2I #17742

**Comment by mrjoro** [comment]
@jpettitt and @zhouyx were there any notes from this design review you can add here?

**Comment by zhouyx** [comment]
Few thing I recall
1. The concern about blocking analytics vendors
    - There's no good way to support that with the current design
    - Would require analytics offline mode to store events before user giving consent
    - To follow up with some analytics vendors and see if they wish to be blocked. 
2. The concern about vendor list changes
     - To introduce dirty bit to force ask user consent the next time they visit the page
3. Decided to support the integration with `<amp-geo>` with CMP integration as it provides faster experience for users that doesn't require consent. 
4. storage limit concern
     - CMP use the client side storage as their primary source of storage. 
     - We'll start with 300 bytes limit and work on the LRU/LRR to expand the storage limit.
