### ISSUE TITLE
amp-carousel type="slides" buttons not doing anything on dev channel

### ISSUE THREAD

**Issue by kevinkassimo** [ampproject/amphtml#17363]
Reproducing steps:

1. Enable 'dev-channel' in https://cdn.ampproject.org/experiments.html
2. Go to https://ampbyexample.com/components/amp-carousel/
3. Pick one of the examples with `type="slides"`
4. Click on the prev and next buttons before they disappear

__Problem occurs on__: Edge, Safari, Firefox (Chrome yet to be confirmed)

**Comment by nainar** [comment]
Can repro on Mac + Chrome. 
Not on Android + Chrome. 

Suspect: https://github.com/ampproject/amphtml/pull/17281
