### ISSUE TITLE
amp-google-vrview-image not working

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#17361]
Failed to load https://storage.googleapis.com/vrview/build/vrview-analytics.js. resulted in 403. 

```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous caller does not have storage.objects.get access to vrview/build/vrview-analytics.js.
</Details>
</Error>
```

To reproduce: https://ampbyexample.com/components/amp-google-vrview-image/

**Comment by aghassemi** [comment]
`amp-google-vrview-image` is experimental and there no plan to launch it at the moment.

**Comment by lannka** [comment]
Sounds good. shall we have this bug in a "known issues" section in its readme? We got this issue reported during hackathon.

**Comment by aghassemi** [comment]
I think we can just fix it. Added it to our bug list.
