### ISSUE TITLE
amp-story share pill not hidden with embedMode=2

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#17376]
Per [embed-mode.js](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/1.0/embed-mode.js), the share pill should be hidden with `#embedMode=2`:

https://github.com/ampproject/amphtml/blob/f00ce3f6052a947337c41133e843613aa9c171f0/extensions/amp-story/1.0/embed-mode.js#L42-L53

However, it is not:

![a51fef03e68da330e777d8aa8caa6470b3cf43bac38b50eb803f68cfac06b643](https://user-images.githubusercontent.com/1651960/43861760-cc82941c-9b25-11e8-8934-99719a6b64c3.png)

**Comment by juanchaur1** [comment]
I'm taking it
