### ISSUE TITLE
Cherry pick request for 17363 into 17351 (Approved)

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#17375]
**GitHub issue your cherry pick is fixing:**

Issue #17363 

**PR that you are requesting a cherry pick for:**

PR #17366

**Release(s) you requesting this cherry pick into:**

*Release issues can be found at https://github.com/ampproject/amphtml/labels/Type%3A%20Release*

Production Release? NO 

Canary release? YES  If yes, Type: Release Issue #17351

*Why does this issue meet the [cherry pick criteria]
Without this PR we are breaking navigation on all carousels for 1 % of canary users.

*Assign this issue to the current TL (cramforce) if you have permission to, otherwise leave this cc line in.*

/cc @cramforce
Assigning to @mrjoro since @cramforce is OOO.

**Comment by nainar** [comment]
cc @aghassemi

**Comment by aghassemi** [comment]
Since this is Canary bug and will cause P0 in prod when Canary is released next week, I recommend approval. It is also safe since it is just a flag change. /to @mrjoro for approval.

**Comment by mrjoro** [comment]
Approved since this only disables an experiment that was enabled in this build for canary.

**Comment by nainar** [comment]
cc @newmuis for next steps here.

**Comment by rsimha** [comment]
@newmuis has been out sick for the past 2 days. I'm working on this now.

**Comment by rsimha** [comment]
Closing, since this is now in 1% and opt-in canary.
