### ISSUE TITLE
Fetch no longer validates AMP CORS headers on amp-list

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#17373]
See https://s.codepen.io/aghassemi/debug/LBXbgK

The endpoint `https://www.wikidata.org/wiki/Special:EntityData/Q161426.json` does not return any AMP CORS headers and should fail.

There is no error thrown and `amp-list` fetches and displays the data but it should have failed.

/to @prateekbh @jridgewell might be a regression of recent `fetch` changes.

**Comment by prateekbh** [comment]
looking into it

**Comment by prateekbh** [comment]
fwiw its happening even before the the change... but i can look into it

**Comment by prateekbh** [comment]
There's something wrong with this URL. i can't even fetch in an emulated phone mode from a new tab.

**Comment by aghassemi** [comment]
The mobile/desktop thing was a red-herring, the endpoint was doing crazy stuff when seeing mobile UA. We simply are not validating response now.Will investigate more to see where it broke.

**Comment by aghassemi** [comment]
I am super confused, as far as I can see, `amp-list` has always been setting `requireAmpResponseSourceOrigin` to `false` if no `credentials` attribute is set.

**Comment by jpettitt** [comment]
I think if no credential are set we don't need AMP CORS headers, just the browser ones - I think that is WAI unless I'm missing something.

**Comment by choumx** [comment]
After poking around in the history, here's what I think: 

`requireAmpResponseSourceOrigin` is a subset of AMP CORS, which handles the behavior of a single response header: [AMP-Access-Control-Allow-Source-Origin](https://www.ampproject.org/docs/fundamentals/amp-cors-requests#amp-access-control-allow-source-origin:-source-origin).

> AMP-Access-Control-Allow-Source-Origin: <source-origin>
This header allows the specified source-origin to read the authorization response.

This behavior is important for credentialed requests and was added to amp-list in #1805.

Later, we decided to deprecate `requireAmpResponseSourceOrigin` which means no more piecemeal AMP CORS -- either everything is enabled or everything is disabled (for simplicity I guess). This happened in #6744.

So amp-list still has the legacy behavior to avoid breaking sites using it. Something we can probably remove in the new hotness.

**Comment by aghassemi** [comment]
Thanks for the details @choumx and @choumx .

**Comment by prateekbh** [comment]
@choumx are you suggesting we totally remove `requireAmpResponseSourceOrigin` in the new fetch refactoring?

**Comment by choumx** [comment]
No, only its usage in the new version of amp-list. We can't remove it as long as there are legacy users.
