### ISSUE TITLE
Stringent validation protocol for boilerplate causes a major nuisance for editor with auto-format

### ISSUE THREAD

**Issue by zipswich** [ampproject/amphtml#17382]
## What's the issue?
I use Visual Studio (VS) for ASP.Net MVC web applications (each website is an MVC project).  I started to AMPlify a website after attending the team's fantastic roadshow on Tuesday. Actually, AMP goes really well with MVC.

VS auto-formats the file after pasting code.  The boilerplate will not pass validation after auto-formatted to the following:
```
  <style amp-boilerplate>
        body {
            -webkit-animation: -amp-start 8s steps(1,end) 0s 1 normal both;
            -moz-animation: -amp-start 8s steps(1,end) 0s 1 normal both;
            -ms-animation: -amp-start 8s steps(1,end) 0s 1 normal both;
            animation: -amp-start 8s steps(1,end) 0s 1 normal both
        }

        @-webkit-keyframes -amp-start {
            from {
                visibility: hidden
            }

            to {
                visibility: visible
            }
        }

        @-moz-keyframes -amp-start {
            from {
                visibility: hidden
            }

            to {
                visibility: visible
            }
        }

        @-ms-keyframes -amp-start {
            from {
                visibility: hidden
            }

            to {
                visibility: visible
            }
        }

        @-o-keyframes -amp-start {
            from {
                visibility: hidden
            }

            to {
                visibility: visible
            }
        }

        @keyframes -amp-start {
            from {
                visibility: hidden
            }

            to {
                visibility: visible
            }
        }
    </style>
    <noscript>
        <style amp-boilerplate>
            body {
                -webkit-animation: none;
                -moz-animation: none;
                -ms-animation: none;
                animation: none
            }
        </style>
    </noscript>
```
VS auto-formats the entire file after each pasting. VS has an issue in disabling auto-format, but many may not want to disable it because it is a useful feature.  Now, I have to copy and paste the boilerplate, then undo the formatting periodically. 

## How do we reproduce the issue?
Use VS to AMPlify a cshtml file and paste some code.

## What browsers are affected?
N/A

## Which AMP version is affected?
The latest.

Is this a new issue? Or was it always broken? Paste your AMP version. You can find it in the browser dev tools.
Not sure.

**I'd like to suggest allowing formatted boilerplate.**

**Comment by zipswich** [comment]
Thank you for the explanation.  Is it possible to get some sense (just some sense, not accurate data) about which tools cover how much share of web developers.  If three tools cover 80+% developers, maybe accommodating them will be sufficient. 
Another option is making a Visual Studio plug-in like [this one](https://marketplace.visualstudio.com/items?itemName=vs-publisher-599079.CodeFormatter) specifically for AMP. I know this is supposed to be beyond the scope of the AMP team, but it would be so nice to have an official AMP plug-in from the team.  This would be another, albeit small, enticement for the large number of .Net enterprise web developers.

**Comment by dparikh** [comment]
This fix should be included in the release next weekd (by October, 19th).

**Comment by zipswich** [comment]
Fantastic!

**Comment by zipswich** [comment]
Now, I am getting green validation stamp by AMP Validator 1.1.4 with Visual Studio auto-formatted amp-boilerplate.  
Thanks a lot.
