### ISSUE TITLE
amp-fx-collection are not correctly working on iPad mini 3

### ISSUE THREAD

**Issue by prasadkudtarkar07** [ampproject/amphtml#17385]
## What's the issue?

Amp-animations are not correctly working on iPad mini 3
(I guess it has something to do with GPU as well)

## How do we reproduce the issue?

1. Step 1 to reproduce: add this to the amp page
<script async custom-element="amp-fx-collection" src="https://cdn.ampproject.org/v0/amp-fx-collection-0.1.js"></script>

2. Step 2 to reproduce: add this to amp-image tag
amp-fx="fly-in-top" data-fly-in-distance=3%" data-duration="1500ms"

3. Step 3 to reproduce: Check the position of image in iPad mini 3 and compare it with newer devices

If this is a feature request you can use this section to point to a prototype/mockup that will help us understand the request.

## What browsers are affected?

All browsers

## Which AMP version is affected?

I am using latest Amp version.

**Comment by aghassemi** [comment]
@prasadkudtarkar07 What iOS version is your iPad running?
/to @nainar

**Comment by nainar** [comment]
Tried all the iPad versions available in the Xcode simulator on the ABE page: https://ampbyexample.com/components/amp-fx-collection/. None of them show this as reproable.

**Comment by nainar** [comment]
Closing this issue, if needed please reopen with the information requested for here.
