### ISSUE TITLE
[Layers] show(), etc. does not schedule layout of owned elements

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#17389]
Essentially `show()` if anything inside `amp-carousel` or `scrollable amp-list` fails to schedule layout.

See  https://github.com/ampproject/amphtml/issues/17380 for carousel example
See https://github.com/ampproject/amphtml/issues/13102 for scrollable lightbox example

(both carousel and lightbox take ownership)

/cc @jridgewell Something to ensure layers handle. I may try to find a temp solution for now. If you have any ideas for a short-term fix, please let me know.

**Comment by aghassemi** [comment]
b/118630841 
/to @choumx I don't think this is easily fixable without layers

**Comment by aghassemi** [comment]
@jridgewell @choumx  should we just get rid of lazy loading part of scrollable lightbox and schedule all children similar to `amp-sidebar` to get around `setAsOwner` issues until we can use `layers`? It is not ideal but probably the fastest approach to fix some of these issues.

**Comment by choumx** [comment]
That's one way to do it. You could also try to specifically handle visibility toggling with a `MutationObserver`, since they all work by toggling the `hidden` attribute.

**Comment by aghassemi** [comment]
@choumx like `scrollable lightbox` observing `hidden` attribute change of its children and scheduling layout for them when it changes?

**Comment by choumx** [comment]
Yea. Hacky, but it might be more performant than scheduling everything. Not sure how large scrollable lightboxes are in the wild.

**Comment by aghassemi** [comment]
third option would be `scrollable=nolazyloading` to make the behavior opt in. I like the mutation observer approach though, so trying that first.

**Comment by samouri** [comment]
@jridgewell: can we close?
