### ISSUE TITLE
amp-story: youtube autoplay is not working in chrome, also if user interacts with video to play it does not pause after changing page

### ISSUE THREAD

**Issue by durgaprasad1106** [ampproject/amphtml#17384]
Hi,

we are making a amp story in which first story page has you-tube video, behavior I want is it should auto-play with sound and if the user changes the story card it should stop playing. This is the same behavior mentioned in documentation but it is not working. This is the url https://amptest2.uberfortruck.com/. Do I need to use any other player to get above behavior ? or I am doing anything wrong ?. Please assist me

**Comment by aghassemi** [comment]
/to @newmuis for now, I suspect there are things we may need to fix in UI, but leaving the initial investigation with you. /cc @alanorozco

**Comment by newmuis** [comment]
`amp-youtube` is not supported within `amp-story`; this page is not valid: https://validator.ampproject.org/#url=https%3A%2F%2Famptest2.uberfortruck.com%2F

See #15847 for support of video interface videos in stories, including `amp-youtube`.
