### ISSUE TITLE
AMP subscriptions pingback is text/plain should be application/json

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#17393]
https://github.com/ampproject/amphtml/blob/master/extensions/amp-subscriptions/0.1/local-subscription-platform.js#L206

Fixing this is potential breaking change and require a version bump.  If we can identify everybody who is live and notify them we may be able to do it without a bump (not sure if this is practical but it's early enough in the lifecycle of this extension that it may be possible).  The other option is not to fix it.  I don't like this option as it's incorrect usage.

**Comment by jpettitt** [comment]
cc @dvoytenko @cramforce

**Comment by jridgewell** [comment]
https://github.com/ampproject/amphtml/pull/13940#discussion_r173993480

**Comment by prateekbh** [comment]
ohhh thanks for digging this up @jridgewell .

**Comment by jpettitt** [comment]
Ah, makes sense - closing as works as intended.  I'll add a note to the doc explaining why we're doing it this way.
