### ISSUE TITLE
Intent to Implement: Deprecate original AMP boilerplate CSS

### ISSUE THREAD

**Issue by Gregable** [ampproject/amphtml#17397]
**Timeline**
When AMP originally launched, the spec referenced a CSS boilerplate string of:

```
<style>body {opacity: 0}</style><noscript><style>body {opacity: 1}</style></noscript>
```

The [recommended string](https://github.com/ampproject/amphtml/blob/master/spec/amp-boilerplate.md) is currently:

```
<style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
```

This change to the boilerplate in the AMP Validator was made on January 7, 2016. 
I'm not sure what date it was released, but within two weeks of that date. 

On Mar 1, 2016, a deprecation warning was added to the AMP Validator for documents with the original boilerplate, which has been shown in all validator surfaces for 2+ years. The text of this deprecation warning is:

```
The tag 'noscript > style[amp-boilerplate] - old variant' is deprecated - use 'noscript > style[amp-boilerplate]' instead. (see https://github.com/ampproject/amphtml/blob/master/spec/amp-boilerplate.md) 
```

**Intended change**
This proposed change is to invalidate documents containing the original AMP boilerplate.

**Purpose of Change**
Both of these boilerplate strings exist for the purpose of hiding the document until the AMP runtime has loaded and performed layout, to avoid a flash of unstyled content. 

The recommended string has a css-based timeout in the form of an animation in the case that the AMP runtime fails to load. As a result, it represents a strictly better user experience in the worst case and the same experience in the average case.

Note that the negative user experience of the old boilerplate only impacts documents served outside the AMP Cache. The AMP Cache rewrites the AMP boilerplate to the more modern boilerplate. In the future, signed exchange processing will also do the same.

**Impact of change**
A sample of 10,000 crawler-accessible pages shows 14 documents (0.14%) that would become invalid if the original boilerplate string were made unsupported.

For process reference, see [spec/amp-versioning-policy.md](https://github.com/ampproject/amphtml/blob/master/spec/amp-versioning-policy.md).

**Comment by cramforce** [comment]
Looks good. Could you IM me the URLs that are breaking?

**Comment by Gregable** [comment]
A larger sample of 11,857,721 total docs show 11,564 become invalid from this change: 0.0975%

**Comment by cramforce** [comment]
LGTM per policy

**Comment by choumx** [comment]
LGTM

**Comment by aghassemi** [comment]
LGTM

**Comment by Gregable** [comment]
This change is now live.
