### ISSUE TITLE
SCRIPT5007 error from the font-display-swap experiment on IE 11

### ISSUE THREAD

**Issue by Spark-NF** [ampproject/amphtml#17407]
## What's the issue?

The current check verifies that neither `doc.fonts` nor `doc.fonts.values` is defined:

https://github.com/ampproject/amphtml/blob/e6d52ecd4fe95e367652e0caf1a6897153076cec/src/font-stylesheet-timeout.js#L126-L128

However, if `doc.fonts` is not defined, trying to check for `doc.fonts.values` will result in an error.
I noticed this on IE 11 (where `document.fonts` is undefined), getting the following error:

> SCRIPT5007: Unable to get property 'values' of undefined or null reference
> File: v0.js, line: 505, column: 218

## How do we reproduce the issue?

1. Make sure the "font-display-swap" experiment is not disabled (it should be enabled by default)
2. Load an AMP page with IE 11

Can be reproduced on https://www.ampproject.org/, by opening it with IE 11:

![image](https://user-images.githubusercontent.com/11507357/43952464-4fcd0372-9c96-11e8-9c96-f1535a6c6cae.png)

## What browsers are affected?

AFAIK, any browser which does not implement the FontFaceSet API.
Reproduced on IE 11.

![image](https://user-images.githubusercontent.com/11507357/43952406-2832a11e-9c96-11e8-993b-8766540dd75b.png)

## Which AMP version is affected?

Noticed the error on v1533253141109.

**Comment by choumx** [comment]
Thanks for the report and fix!
