### ISSUE TITLE
Date object support into JS-like expressions

### ISSUE THREAD

**Issue by danieltxok** [ampproject/amphtml#17409]
## What's the issue?
This is a FR for [Date object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) support into the [JS-like expressions](https://www.ampproject.org/docs/reference/components/amp-bind#expressions) that currently AMP supports.

## Why this?
I found the need of such a feature while trying to update a value according to the selected range in the date picker (travel pages often show the total number of nights once you select the dates). If the date is modified, this value should update accordingly. This feature does not exist in the amp-date-picker but the Date object will solve this and avoid the complexity of string based arithmetics.

## What browsers are affected?
Should work in all browsers

**Comment by cvializ** [comment]
Thanks for opening this feature request! Using bind expressions is planned. For now, you can count the number of nights using the `select` event. It looks like our documentation is lacking on this event, so I'll create an issue to update it.

```html
<amp-date-picker on="
    select:
      AMP.setState({
        nights: event.dates.length,
      })"
>
```

**Comment by dbarcosb** [comment]
Thanks @cvializ! That will solve our current problem!
