### ISSUE TITLE
[amp-pan-zoom] add attribute to disable doubletap and tweak threshold

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#17416]
Use [`performance.now()`](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now) for timer instead of setInterval, adjust threshold to 200-250 ms, and add attribute to opt-out of double tap.

**Comment by spacedino** [comment]
Double check to make sure this plays well with double tap to zoom and other default browser features.

**Comment by cathyxz** [comment]
This has been done a while ago with `disable-double-tap`.
