### ISSUE TITLE
amp-carousel sliding issues with amp-sticky-ad on Android

### ISSUE THREAD

**Issue by claudiorodriguez** [ampproject/amphtml#17411]
## What's the issue?

Please see reproduction example page. When you have an `amp-carousel type="slides"` inside an `amp-lightbox` and there's an `amp-sticky-ad` on the page (even with `layout="nodisplay"`), and you try to slide the images, they snap back, so the user is unable to slide them 

## How do we reproduce the issue?

http://output.jsbin.com/xoyicabuta
Open in a Samsung Galaxy S9
Click on the button to open the lightbox
Attempt to swipe right on the image - the image snaps back, unable to change slides 

## What browsers are affected?

Samsung Galaxy S9 Chrome

## Which AMP version is affected?

`Version 1533253141109`

**Comment by nainar** [comment]
Hi @claudiorodriguez taking a look at this. Wondering if you know if this is a recent regression?

**Comment by nainar** [comment]
Can repro this on a Pixel 2 Chrome 70 as well.

**Comment by claudiorodriguez** [comment]
@nainar We've become aware of the issue only recently but I couldn't say for certain, sorry.

**Comment by nainar** [comment]
@claudiorodriguez I can't repro this issue anymore. Potentially fixed by: #17453. Please try to repro again?

**Comment by claudiorodriguez** [comment]
@nainar I can still reproduce on Samsung Galaxy S9 Chrome

**Comment by MikeRaynor** [comment]
Hi @nainar i just wondered if this is still being looked into?

**Comment by nainar** [comment]
Hi, we're doing a more involved audit of `<amp-carousel>` to fix a bunch of issues like this. Will be looking at it in coordination with that.
