### ISSUE TITLE
Update List of Extensions Documentation (Missing Entries)

### ISSUE THREAD

**Issue by johnnyshankman** [ampproject/amphtml#1741]
The list in the documentation found here

https://github.com/ampproject/amphtml/tree/master/extensions

is for example missing `<amp-facebook>`.

**Comment by rudygalfi** [comment]
@Meggin Can you post the new PR where you're tracking this?

**Comment by Meggin** [comment]
Here's the README. It's ready for next review and hopefully push.

**Comment by rudygalfi** [comment]
Resolved via #2052
