### ISSUE TITLE
CSS truncated at 10000 characters

### ISSUE THREAD

**Issue by JoyceBabu** [ampproject/amphtml#17414]
**Please only file bugs/feature requests for AMP here.**

## What's the issue?

I am not sure whether this a Google issue or AMP issue. Some times I find that our webpage layout is completely broken. I checked the css inside the rendered amp page and found that the [CSS is truncated at 10000 characters](https://pastebin.com/raw/zTgWiGL7).

https://www.google.co.in/amp/s/www.prokerala.com/astrology/thirumana-porutham.php%3famp=1

---
### Expected Output

![www prokerala com_astrology_thirumana-porutham php_amp 1 1](https://user-images.githubusercontent.com/502942/43970985-032b89d8-9ced-11e8-8426-b89b0ec37eba.png)

---

### Actual Output

![www google co in_search_q thirumana porutham oq thirumana poru aqs chrome 0 35i39j69i60j69i57j69i60j0l2 7546j0j4 sourceid chrome ie utf-8](https://user-images.githubusercontent.com/502942/43970907-be7f0184-9cec-11e8-99a0-19ccd2263480.png)

---

## How do we reproduce the issue?

[Source Page](https://www.prokerala.com/astrology/thirumana-porutham.php?amp=1)
[Google Version](https://www.google.co.in/amp/s/www.prokerala.com/astrology/thirumana-porutham.php%3famp=1)

## What browsers are affected?

I have noticed this mostly when browsing with desktop version of Google Chrome in responsive mode. If I open it in Chrome Mobile, it will be working correctly.

**Comment by JoyceBabu** [comment]
The CSS is not truncated on the source page.

**Comment by aghassemi** [comment]
to @jgluk

**Comment by jgluk** [comment]
Tracked internally: 112595237

**Comment by JoyceBabu** [comment]
I had opened the frame source url directly and took the CSS from there. The CSS was truncated at 10000 characters and had an ellipse character following it.

**Comment by JoyceBabu** [comment]
If the issue happens again, I will update here. Closing for now. Thank you.

**Comment by JoyceBabu** [comment]
I think this is somehow related to AMP Cache.

![screen shot 2018-08-22 at 5 40 15 pm](https://user-images.githubusercontent.com/502942/44462646-e11ab680-a632-11e8-9f9d-698d86f16955.png)

As you can see in the screenshot above, the page rendered within the iframe is broken. But the preview of the html returned from cdn.ampproject.org is rendering correctly.

To ensure that it is not caused by a Chrome extension, I had opened a new chrome instance with an clean profile directory for taking the screenshot.

**Comment by jridgewell** [comment]
This is due to `@media (min-color: 8)` which, strangely, doesn't match when inside the iframe after render.

So, not an issue with the AMP Cache, but likely something in AMP Core.

**Comment by jridgewell** [comment]
This is a Chrome bug with cross-origin iframes and `min-color` media queries. Moving to https://bugs.chromium.org/p/chromium/issues/detail?id=876760.
