### ISSUE TITLE
Validator rejecting fill in styles attribute of svg tag

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#17421]
Pages with `<svg style="fill:rgb(0,0,0)">` incorrectly fail validation - sample page attached.
[broken-svg-style.html.zip](https://github.com/ampproject/amphtml/files/2279114/broken-svg-style.html.zip)

**Comment by Gregable** [comment]
We have two versions of whitelists for style attribute declarations. One for SVG element styles, one for HTML element styles. 

@honeybadgerdontcare I think all that's going on here is that the SVG element style is not applied to the SVG tag itself, only SVG child tags, such as GLYPH. This looks like a one-line change + test.

**Comment by jpettitt** [comment]
That seems correct, the `style="fill: ...` on the `<svg>` tag does have the correct effect on it's children when I change it.

**Comment by honeybadgerdontcare** [comment]
That's correct, only some elements within an SVG allow `style` attribute with restrictions. See [attr_list: "svg-style-attr"](https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii#L2507). As @Gregable mentioned it could be made more available within SVG.
