### ISSUE TITLE
amp-doubleclick: add option to add key-value parameters randomly

### ISSUE THREAD

**Issue by jeffkaufman** [ampproject/amphtml#17427]
If a publisher wants to run an experiment where they compare two different ads, ideally they could flip a coin client-side and attach this to the ad request.  They they could use key-value targeting server-side to choose one ad or the other depending on the coin value.  Right now the only way to do this with cacheable pages would be to use RTC, which is very inefficient just to get a coin flip.

**Comment by jasti** [comment]
@jeffkaufman, is there a way to use `amp-experiment` instead of RTC?

**Comment by jeffkaufman** [comment]
Reading the `amp-experiment` docs it looks like you'd need to be able to macro expand `VARIANT(...)` in a doubleclick ad request.  I don't see how to do that from reading the doubleclick docs, but I'm also not that familiar with this part of the code.

**Comment by jasti** [comment]
Right, I think we can make this work with amp-experiment. Adding it to new FRs since there isn't an active ask but feel free to change/ add support if you think this is priority.
