### ISSUE TITLE
amp-lightbox-galery freezes page

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#17423]
Steps to reproduce:

1. Visit 
https://www.bookitdirect.com/big-bus-tours/las-vegas
2. Click on one of three images
3. Close the lightbox

=> page freezes (reproduced on desktop Chrome and Safari)

Reported here: https://stackoverflow.com/questions/51791982/page-locks-up-on-re-opening-amp-lightbox

@cathyxz @aghassemi

**Comment by aghassemi** [comment]
I can repro on ABE with prod and DevChannel as well. Setting to P1.

**Comment by aghassemi** [comment]
looks like it does not exit "lightbox mode"

**Comment by cathyxz** [comment]
Discussed offline, it's actually solved in dev channel. Fixed by https://github.com/ampproject/amphtml/pull/17268.
