### ISSUE TITLE
amp-carousel stops loading images when used with lightbox after few slides and entire page is not clickable

### ISSUE THREAD

**Issue by happyesthete** [ampproject/amphtml#17458]
There are two related issues that can be reproduced every single time right inside the example page under the section "Image Galleries with lightbox" here:
https://ampbyexample.com/advanced/image_galleries_with_amp-carousel/

1) amp-carousel stops loading images when used with lightbox after few slides and then images are not displayed in the lightbox, only black overlay appears. But, if caption is present, that is displayed properly.

See here:
https://gyazo.com/fd52aa5b5e554b99a07b8dfe896a9f94
See in this gif, last image is not loading in lightbox, and then other images in lightbox all randomly goes blank.

I am not sure from where display: none property is applying to amp-img inside amp-image-viewer. After removing display: none image appears.
https://gyazo.com/2bf0757ed1bb683a26dfad3d7782c4bd

2) Another related issue: Close the lightbox (after issue 1), then again click on image, image shifts and entire page is not clickable. When trying to inspect anywhere in the page below header, it looks like an invisible layer of amp-image-viewer is capturing all the clicks. Entire body including sidebar, except header is not clickable. There is no way to scroll or do anything except reloading the page.
https://gyazo.com/245b431c5878dddd129765f366d6e401

Verified in latest chrome in both Windows and Mac, issue persists.

**Comment by kevinkassimo** [comment]
Reproducible myself, but seems fixed in dev channel. Probably fixed through #17268

**Comment by cathyxz** [comment]
Yup, @kevinkassimo 's reply is correct. Closing per #17268.
