### ISSUE TITLE
FixedLayer: Transfer elements on [hidden] toggle

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#17475]
Problem: Fixed elements that are initially hidden may have incorrect DOM ordering WRT fixed elements that are not initially hidden. 

Proposed solution: Use MutationObserver to listen for tracked, fixed elements that are un-hidden dynamically by removing `hidden` attribute (e.g. via amp-bind or toggle/show actions). Transfer those elements to the fixed layer when they're un-hidden.

Context: `b/111906735`

**Comment by jridgewell** [comment]
This'll be a 4 phase project:

1. Lint style mutations.
   - Everything currently goes through `setStyle`/`setStyles`/`setImportantStyles`/`resetStyles`
2. Disallow `display` style mutations
   - Everything must use `toggle` helper.
3. Convert `toggle` helper to use HTLM5 `hidden` Element attribute.
   - It does the same thing as `display` style mutation.
4. Add Mutation Observer that listens for `hidden` Element attribute changes.
   - Update fixed-layer on mutations.

**Comment by choumx** [comment]
@jridgewell We'll probably need to special-case attributes for amp-access and amp-subscriptions, e.g. `amp-access-hide`, `subscriptions-section`, and `subscriptions-action`.

**Comment by thedavidzhao** [comment]
@jridgewell For `2. Disallow display style mutations`, would this prevent `display` from being set to things other than empty string or `none`, such as `inline-block` or `flex`?

I'm new to `amp` so I don't know if it's in scope. `display: none` and removing it does seem to be the most common use case.

**Comment by choumx** [comment]
No, this only refers to internal usage e.g. by AMP extensions.
