### ISSUE TITLE
Android Poster Bug Still occurring on Chrome for Android

### ISSUE THREAD

**Issue by torch2424** [ampproject/amphtml#17482]
cc @aghassemi 

## What's the issue?

Please see this example site, on Chrome for android (Chrome inspector device emulation works as well): https://torch2424.com/

Seems that the `i-amphtml-android-poster-bug` class does not work as intended, and the initial poster is still visible once an autoplaying video starts.

## How do we reproduce the issue?

[Source code for website](https://github.com/torch2424/dotFiles/blob/master/.files_caddy/karen/index.html)

Or in a snippet:

```
<style amp-custom>

.backgroundVideo {
          position: fixed;
          top: 0px;
          left: 0px;
          width: 100vw;
          height: 100vh;
          z-index: -1;
          background-color: #020202;
        }

</style>

...Some more code here...

      <div class="backgroundVideo">
        <amp-video id="gif-mp4"
                   class="giphyAmpVideo"
                   poster="https://i.giphy.com/media/RDJfOSOdlnhu/200_s.gif"
                   layout="fill"
                   autoplay
                   noaudio
                   noloading
                   loop>

          <div fallback>
            <p>Your browser doesn't support HTML5 video.</p>
          </div>

          <source src="https://i.giphy.com/media/RDJfOSOdlnhu/giphy.mp4" type="video/mp4">
          </source>
        </amp-video>
      </div>
```

## What browsers are affected?

I've tested this on Chrome on Android.

## Which AMP version is affected?

 Version 1533253141109

**Comment by aghassemi** [comment]
this happens when video's intrinsic size is smaller than its layout size. we should be able to just remove the `poster` hack image after load is complete?
