### ISSUE TITLE
validator.js 404s if dev-channel cookie is turned on

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amphtml#17506]
## How do we reproduce the issue?

Either via https://cdn.ampproject.org/experiments.html or the command-line:

```sh
$ curl -s -i -H 'cookie: AMP_CANARY=1;' 'https://cdn.ampproject.org/v0/validator.js' | head -1
HTTP/2 404 # not expected
$ curl -s -i 'https://cdn.ampproject.org/v0/validator.js' | head -1
HTTP/2 200 # expected
```

(`experiments.js` also seems to be affected in the same way.)

/cc @Gregable

**Comment by aghassemi** [comment]
/to @erwinmombay same thing happens with validator.js as well. let's treat as P0 since after enabling DevChannel one can not undo it.

**Comment by ithinkihaveacat** [comment]
In terms of impact, if dev channel is turned on, this bug means you can't use:

- https://validator.ampproject.org/ (it attempts to load validator.js, which 404s)
- https://cdn.ampproject.org/experiments.html (can't disable experiments, or inspect state, since experiments.js can't be loaded)
- https://chrome.google.com/webstore/detail/amp-validator/nmoffdblmcmgeicmolmhobpoocbbmknc?hl=en (validator.js can't be loaded)

**Comment by jridgewell** [comment]
It's the new diversion updates. /cc @jgluk

**Comment by jgluk** [comment]
Rollback submitted, should be fixed within an hour. Sorry folks!

**Comment by jridgewell** [comment]
Fix is live.
