### ISSUE TITLE
amp-mustache 0.2 adds formatting

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#17509]
when using `<p><span></span><span></span></p>`

amp-mustache appears to reform the above as follows:
```
  <p role='listitem'><span></span></p>
  <p role='listitem'><span></span></p>
```
Is there a flag to suppress the generation of a `<p>` for each `<span>`?

We've had to resort to this CSS:
```
p, .keep-together {
	display: inline;
}
```
for this structure:

```
<template type='amp-mustache'>
<p>
{{#wd-Q89}}
<span class='keep-together'>
The European languages are members of the same family. Their separate existence is a myth.
<button
	class=''
	on='tap:my-lightbox-{{lightbox-id}}'
	role='button'
	tabindex='{{button-tabindex}}'
>
{{button-label}}
</button>
</span>
{{/wd-Q89}}

{{#wd-Q177}}
<span class='keep-together'>
For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.
<button
	class=''
	on='tap:my-lightbox-{{lightbox-id}}'
	role='button'
	tabindex='{{button-tabindex}}'
>
{{button-label}}
</button>
</span>
{{/wd-Q177}}
</p>
</template>
```

**Comment by choumx** [comment]
This is actually default behavior of `amp-list`:

> By default, amp-list adds a list ARIA role to the list element and a listitem role to item elements rendered via the template.

https://www.ampproject.org/docs/reference/components/amp-list#behavior

This is because `amp-list` semantically renders a "list" of items. Overriding default behavior with CSS (as you have) is the right solution.
