### ISSUE TITLE
<amp-lightbox-gallery> Larger navigation arrows in gallery view on desktop

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#17508]
@spacedino proposed that we have large arrows for gallery view in `<amp-lightbox-gallery>` when on desktop. Filing this as an FR to allow for discussion.

**Comment by cathyxz** [comment]
So basically we want them to be consistent with carousel, right? Two ways to do this. 
1. Just take out the custom lightbox arrows and directly use carousel arrows instead. Downside here is you'll have to tweak carousel CSS classes in lightbox to respond to single tap in lightbox turning arrows on / off (unless we want to implement that at the carousel level). 
2. Apply media queries / styling on lightbox consistent with those on carousel.

**Comment by nainar** [comment]
They won't match carousel's size. Carousel will retain smaller arrows on both mobile and desktop. 

Didn't add @ericlindley-g and @aghassemi to the conversation earlier sorry.

**Comment by cathyxz** [comment]
Oh. What's the reasoning for differing arrow sizes between lightbox and carousel?

**Comment by nainar** [comment]
Paging @spacedino for further information.

**Comment by aghassemi** [comment]
let's consider as part of amp-carousel v2.
