### ISSUE TITLE
<amp-consent> still adding cookie after blocked

### ISSUE THREAD

**Issue by ghanley** [ampproject/amphtml#17525]
Publisher implemented geo-blocking of AMI sites using <amp-geo>/<amp-consent> tags combo. They tried it on Muscle and Fitness, but unfortunately they came across an instance when AMP page continues to send a request that sometimes results in the cookie to be added to the user’s machine. Below are more details on what was uncovered. -----

Even if the "data-block-on-consent" attribute is present and the user has declined to give a consent, <amp-ad> tag was making remote requests to https://adservice.google.com/adsid/integrator.json?domain=www.muscleandfitness.com

 That means if the same user has visited any site in the past that would set a cookie for the adservice.google.com or *.google.comdomain, the cookie will be sent along with thehttps://adservice.google.com/adsid/integrator.json?domain=www.muscleandfitness.com request from <amp-ad> tag which could mean a non-compliance with GDPR. 

Publisher is concerned that <amp-ad data-block-on-consent> tag keeps sending that remote request when the user has declined to give consent. Do you have any recommendations for them on how to prevent any requests being sent from the AMP page if no user consent was given?

**Comment by zhouyx** [comment]
@ghanley Thank you for the filing the issue
One question I have is could you let me know what AMP component the `data-block-on-consent` is applied to. I suppose it's the `<amp-ad>` if so, could you please also let me know the type of the ad? Thanks

**Comment by jasti** [comment]
@ghanley could you please link to a test page? I believe this is amp-ad type = adsense. @keithwrightbos could you take a look please?

**Comment by zhouyx** [comment]
FYI: according to adsense the ad request will still be sent out on reject, but a npa will be served. adsense treat `dismiss` to not send an ad request.

**Comment by ghanley** [comment]
This is a Google Ad Manager publisher. I will look into @zhouyx question

**Comment by ghanley** [comment]
These are the steps to reproduce the issue:

1. Visit the URL from a EU IP
2. Open Network panel in Chrome. Filter by "integrator".
3. Visit https://dev.radaronline.com/gdpr-blank.html (user/pass: ami_dev/ami_dev)
4. Check request headers for https://adservice.google.com/adsid/integrator.json?domain=dev.radaronline.com request.

**Comment by ghanley** [comment]
Any updates on this?

**Comment by keithwrightbos** [comment]
See #17967 which delays the request in question depending on consent state.  Note that the request in call only reads cookies.
