### ISSUE TITLE
Page not rendering in IE 11 anymore

### ISSUE THREAD

**Issue by sryze** [ampproject/amphtml#17528]
## What's the issue?

Until recently our site was working fine in IE 11, but now it doesn't render correctly. I think it might be related to this error:

```
SCRIPT438: Object doesn't support property or method 'assign'
v0.js (519,398)
```

## How do we reproduce the issue?

See https://www.upnest.com/

## What browsers are affected?

Internet Explorer 11

## Which AMP version is affected?

1534366245210

**Comment by cathyxz** [comment]
This seems similar to https://github.com/ampproject/amphtml/issues/17505.

**Comment by sryze** [comment]
I will try building AMP from git today and check that fixed my issue. Thanks.

**Comment by jridgewell** [comment]
Closing as a duplicate of #17505.
