### ISSUE TITLE
amp-image-slider: Use cursor: col-resize on desktop when hovering on separator

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#17557]
When hovering on or around the separator line, I think `cursor: col-resize` would be nicer than pointer.
(https://www.w3schools.com/cssref/playit.asp?filename=playcss_cursor&preval=col-resize)

@nainar @spacedino

**Comment by kevinkassimo** [comment]
My original proposal was `ew-resize`, but this one also looks okay

**Comment by nainar** [comment]
Agreed. Good pick there!

**Comment by aghassemi** [comment]
closing for #18056
