### ISSUE TITLE
Feature user-error-reporting does not work

### ISSUE THREAD

**Issue by andreyMakahov** [ampproject/amphtml#17569]
Hi guys!
I tested new rolled out feature - "Enable user-error-reporting". But it does not work for me.

## What's the issue?

I created a [page](https://andreymakahov.github.io/amp-test/). I took a source code just from [example](https://github.com/ampproject/amphtml/blob/bde01e900a6fdc31c5a477d4ddedaee1cd0baa3b/examples/analytics-error-reporting.amp.html) and changed a reporting URL address.
It does not send a error request.

Then I executed `AMP.toggleExperiment('user-error-reporting');` in browser console. After I have a cookies for enabling user-error-reporting feature it started to send the request.

## How do we reproduce the issue?

1. Go to the [page](https://andreymakahov.github.io/amp-test/).
2. Open developer console and look to network panel.
3. The expected result is user-error request in network panel but there was not any request.

## What browsers are affected?

All browsers

## Which AMP version is affected?

Is this a new issue.

**Comment by jpettitt** [comment]
`user-error-reporting` only defaults to on if you have [dev channel](https://cdn.ampproject.org/experiments.html) enabled.  Otherwise., as you note, you have to enable it in console.

**Comment by andreyMakahov** [comment]
@jpettitt Thank you for answer.
I thought the feature was rolled out [here](https://github.com/ampproject/amphtml/pull/17301/commits/14f5fe3cf6a01d52027a3d8e8b4770b322292ffb). And now it is not experimental. Am I wrong?
