### ISSUE TITLE
AMP Analytics - Unhandled promise rejection Enable experiment amp-storage

### ISSUE THREAD

**Issue by Polylike** [ampproject/amphtml#1756]
Hey, when i open the console on https://www.ampproject.org/ i getting the error Unhandled promise rejection Enable experiment amp-storage. es6.promise.js:112

(anonymous function)	@	es6.promise.js:112

Same problem for my site but when i remove AMP Analytics the message getting away.

Best regards,
Daniel

**Comment by dvoytenko** [comment]
Thanks for the report, @Polylike . This has been fixed just today or yesterday. Should be all good in next canary. The error itself is benign - it just reports an error incorrect - it doesn't prevent anything from working.
