### ISSUE TITLE
Appnexus Adv - single position ad call

### ISSUE THREAD

**Issue by Nicola1976** [ampproject/amphtml#1757]
Hi guys!

I am trying unsuccessfully to make a AMP-AD with call to a single position to show an AppNexus adverstising AppNexus . Specifically a frame1 300x250 . 

Appnexus is currently NOT supported ad server.

I have to use "Running ads from a custom domain" implementing remote.html?
Which is the correct syntax to make adserver custom?

This is the ad call. I need to pass to it 2 parameter: sitepage and random number.

https://oas.rcsadv.it/RealMedia/ads/adstream_sx.ads/mobile.corriere.it/hp/1234567890@Frame1

It is possible?

Thanks a lot

**Comment by cramforce** [comment]
@Nicola1976 Please get us in touch with App Nexus and we can build first class support for them. This should be quick and easy.

How do you add the "sitepage" and "random number"?

**Comment by Nicola1976** [comment]
Hi,
I found this temporary (orrible) solution (waiting for custom OAS adaptor):

*amp-iframe* > *iframe (another) *> *custom script *(to set random number)

I dont know how get the sitepage from parent page (it is a javascript
variable in page) because, as you know, in AMP page it is not allowed to
use custom javascript.

I am in contact with the OAS that he announced that they are developing an
adapter.

You find temporary solution on this page:

*http://www.corriere.it/test/no-inap/corriere_amp.html*
<http://www.corriere.it/test/no-inap/corriere_amp.html>

Thanks a lot
Nicola

2016-02-03 16:25 GMT+01:00 Malte Ubl <notifications@github.com>:

> @Nicola1976 <https://github.com/Nicola1976> Please get us in touch with
> App Nexus and we can build first class support for them. This should be
> quick and easy.
>
> How do you add the "sitepage" and "random number"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampproject/amphtml/issues/1757#issuecomment-179291477>
> .
>



-- 

*Nicola Colombo*
Front End Developer

FINCONS SPA
Via Torri Bianche 10 - Pal. Betulla

20871 Vimercate (MB)

Mob. +393480919039

www.finconsgroup.com

**Comment by jasti** [comment]
AppNexus support is now available - https://github.com/ampproject/amphtml/blob/master/ads/appnexus.md
Closing this out.
