### ISSUE TITLE
<amp-bodymovin> to support full version and different renderers beyond SVG.

### ISSUE THREAD

**Issue by normmcgarry** [ampproject/amphtml#17578]
## What's the issue?

Currently, the amp-bodymovin component only uses the Light version. This version is restrictive, and uses only the SVG renderer. I understand the goal here was to lighten the fileweight, but the SVG render is extremely slow and intensive on the CPU, which is also a negative for a page.

## How do we reproduce the issue?

N/A. No example to post, however I am currently working on a site that has a handful of illustrations that are animated. As you scroll the page, the animations play and tell a story of how something works. There are about 8 sections total. They are all vector and can be accomplished by the "Light" version, but performance severely degrades on desktops that go to a decent resolution. 

Our other alternative is to use video. This would solve the performance issue, but it degrades the file weight of the site. It seems like a contradiction to require the light version of bodymovin to save on file load, but then that causes people to use video instead. Plus, the SVG renderer is intensive comapred to the HTML and Canvas renderers.

## What browsers are affected?

All. Performance degrades with large SVG rendering on desktop browsers more than mobile actually.

## Which AMP version is affected?

All.

**Comment by aghassemi** [comment]
@normmcgarry between HTML and Canvas which one performs better for you case on desktop?
