### ISSUE TITLE
Unskip amp-image-slider scroll behavior test

### ISSUE THREAD

**Issue by kevinkassimo** [ampproject/amphtml#17581]
Currently, the integration test for scroll out and back into viewport hint reappearance behavior of is flaky and skipped. This is due to runtime scheduling issues and requires further investigation.

Cleanup this issue once the test is un-skipped in master.

**Comment by aghassemi** [comment]
better: let's write new E2E test for it.

**Comment by aghassemi** [comment]
too old, closing (we can easily find skipped tests in code anyway)
