### ISSUE TITLE
Improve documentation for installing validator dependencies

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#17582]
Currently if a contributor runs `gulp validator` after following the instructions in `contributing/getting-started-e2e.md`, they are greeted with the following error:

https://github.com/ampproject/amphtml/blob/af504f3f42d414b5c78b55ab969d3147b2d0d9f9/validator/build.py#L77

That's a good instruction if the contributor develops on a Debian-based Linux distro, but on other platforms it is confusing. This error message should direct users to the correct documentation to resolve the error. And we should provide step-by-step instructions for installing the validator's dependencies.

/cc @aghassemi since we discussed docs updates for before the Contributor Summit

**Comment by honeybadgerdontcare** [comment]
@cvializ I don't develop on non Debian-based Linux distros. Would someone who does be able to provide instructions or loan me their computer so I can figure it out?
