### ISSUE TITLE
amp-ad doubleclick shared correlator for ads on single AMP page

### ISSUE THREAD

**Issue by drummerboof** [ampproject/amphtml#1759]
Hi all!

We have been looking into implementing ads on our AMP pages and are planning to use the custom domain solution so that we can add some additional parameters to the DFP request. Currently, each ad request uses a different correlator parameter meaning that they ad server considers each request a new page view.

Would it be possible to share the same correlator parameter across ad requests from different amp-ad tags so the ads are considered to be from a single page view?

Thanks.

**Comment by bobcassels** [comment]
There is now context['pageViewId']. It is low entropy, currently Math.floor(win.Math.random() * 10000). Is that good enough? Or should we just make that bigger, rather than make a new correlator?

**Comment by cramforce** [comment]
`context.pageViewId` is, indeed the way to go. as of today it is being transmitted to DFP, although I have no idea whether it is used for this purpose. Note, that `url` + `context.clientId` + `context.pageViewId` is meant to be "very likely unique" together.

**Comment by drummerboof** [comment]
Hi - thanks for the response!

It's great that we have the unique identifiers available but it is my understanding that there is no way to assign those values as the correlator in the request that DFP makes. I don't actually do the ad scheduling but am informed that to arrange exclusions and companions/buy outs, the correlator parameter is used and it has to be that parameter, not a custom parameter. Using the custom iframe method it was my understanding that anything we added to the config object ended up being sent as a custom parameter. Does that make sense? Am I mistaken about the scheduling rules?

Thanks

**Comment by cramforce** [comment]
This is definitely one of the things you could do with a custom iframe. I wonder if this should go directly into the GPT integration.

**Comment by cramforce** [comment]
I just learned that doubleclick will fix this on their side for the DFP integration. Closing, but feel free to reopen.
