### ISSUE TITLE
[Master Feature] Establish an API to let ad trigger specific functionality on the AMP page

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#17618]
There are some use cases when the publisher configuration in the ad must allow the external AMP components to behave differently. Some specific examples are:
1. Ability to only selectively refresh an ad by looking for the presence of the ad being a sponsorship vs not. (Most publishers don't want to refresh if the ad is a sponsorship based ad but want to refresh otherwise)
2. Ability to pass additional data from the ad so that the `<amp-next-page>` component can use it request a certain page dynamically
3. Ability to append URL params to the destination URL on ad click by simply updating the JS inside of the creative with a new parameter (e.g. ?dfp-keyword=mwb-test)

**Comment by jasti** [comment]
For 2) Updated the original description. (Sorry). It's the amp-next-page component. 

3) Publishers often use this as a technique for sending additional params to destination URLs that are surveys. On non-AMP, their page would probably just use custom JS to reach the param and append to the destination URL.

**Comment by jasti** [comment]
New Requirement from Post Media: Ability to set '‘data-loading-strategy’' value on a campaign basis based on what's returned within the creative from the ad server.

**Comment by zhouyx** [comment]
I see the request in two parts:
1. API: I know we have such API for 3p ad case. I believe there are also existing API for safeframe and FIE case as well. 
2. Communication between AMP components, for example here `<amp-ad>` and `<amp-next-page>`.

Has there been a privacy and security discussion?

**Comment by calebcordry** [comment]
@ampproject/wg-ads Would the new meta tags accomplish the functionality needed here?

**Comment by lannka** [comment]
De-prioritized.
