### ISSUE TITLE
Make elements in shadow documents refer to their own AmpDoc

### ISSUE THREAD

**Issue by sparhami** [ampproject/amphtml#17614]
Currently, in single doc mode, elements within a shadow document refer to the `AmpDoc` for the outer page. This is the cause of of some issues, e.g. #17465.

We want to have the elements within the shadow document instead refer to their own `AmpDoc`, so that they get the correct service instances.

This essentially means removing the `singleDoc_` check here: https://github.com/ampproject/amphtml/blob/f7217473fa925cbd07d0951529b57754052c9cc8/src/service/ampdoc-impl.js#L102

Instead we want to always look for the `AmpDoc` associated with the containing document. This change was initially made as a performance improvement, but `getRootNode()` should be reasonably fast these days.

**Comment by choumx** [comment]
@sparhami Any progress on this experiment? I'm planning on doing something similar for service-scoping in amp-script and it'd be nice to use this code path.

**Comment by sparhami** [comment]
There may be a few errors it is causing. Here is at least one:

go/ampe//CNmFiNHr6a7EgAE

```
Error: a.getRootNode().getElementsByTagName is not a function. (In 'a.getRootNode().getElementsByTagName("AMP-AD")', 'a.getRootNode().getElementsByTagName' is undefined)
    at https://raw.githubusercontent.com/ampproject/amphtml/1904301721170/extensions/amp-auto-ads/0.1/ad-tracker.js:171:65
    at ampdoc (https://raw.githubusercontent.com/ampproject/amphtml/1904301721170/extensions/amp-auto-ads/0.1/amp-auto-ads.js:81:53)
```

The shadow doc is now being returned, and the shadow root does not have `getElementsByTagName`. Before, this code was searching outside of the shadow dom, so it was still wrong, but the failure path is different. I haven't had a chance to look for what are all the errors that may be caused by the change and I don't have a good grasp of what may change as a result of launching this.

I'll fix this one, but I don't have a lot of cycles right now to look too deeply into what the effects may be on other components.

**Comment by choumx** [comment]
Thanks for the update!
