### ISSUE TITLE
Search form page to save results list when returning to form page

### ISSUE THREAD

**Issue by IamAlta** [ampproject/amphtml#17615]
## What's the issue?
Visitors complained that when they search for something, leave the page then return to the search form, the results are gone and they have to search again.

AMP has no "on page load" available to use.
Amp-bind requires a user action such as a tap or change form element.

I have it partially solved with saving the search terms in a session variable and writing it to the form input element if they returned to it. Autocomplete might work but this is faster. 
All they have to do is click the "submit" button which is not intuitive when they see the search term(s) in the form and no results when they return. 

Having the results show up when the search form page is loaded would be better for the users.

To display the results from submitting the form, the form uses 
→ action-xhr
→ amp-list w/ amp-mustache

## How do we reproduce the issue?
Create a form and submit the form to see the results.
Go to another page, the back to the form page. The results are no longer there.

## What browsers are affected?
All browsers.

## Which AMP version is affected?
1534444305877

**Comment by IamAlta** [comment]
Thank you, Carlos @cvializ. 

I hesitate opening windows because (1) some people have a hard time figuring out a new one opened and (2) It's not really professional.

I think I'll store the search terms in a session variable then if they go back, at least that can cue them in on the last searched.

Make it a wonderful day!

**Comment by cvializ** [comment]
You're welcome. Alternatively, if you haven't yet considered this, you could have the form submit navigate to a search results page rendered by the server, then when the user navigates the back button will return them to the rendered results instead of to the dynamic form. Thanks again!

**Comment by IamAlta** [comment]
Hi Carlos @cvializ,
That'll work. Thanks for the good idea.
