### ISSUE TITLE
Event bus implementation for clickable actions in amp story

### ISSUE THREAD

**Issue by alabiaga** [ampproject/amphtml#17629]
click listeners in stories needs to be centrally managed.  The navigation service needs an API similar to the anchor mutators but not restricted to just the anchor element.

**Comment by alabiaga** [comment]
cc\ @Enriqe

**Comment by newmuis** [comment]
For what it's worth, the stories feature (#16521) is not restricted to only anchors either; we would like to be able to extend it to any arbitrary selector(s).

**Comment by newmuis** [comment]
@alabiaga can you elaborate on the benefits of doing this in the runtime?
@Enriqe do you think we need this for stories?  For our uses, how is this different from using a single click handler that is added within `amp-story`?

**Comment by alabiaga** [comment]
@newmuis Jon, exposing an API in navigation.js will probably have no benefit other than readability (which is arguable) and having a pattern to follow for others to follow, if someone else with an extension would like to do something similar . Like you addressed to @Enriqe, this is no different than handling this in amp-story with one single click handler. The one thing that be potentially be leveraged is the ability to execute the clicks based on priority..which is something we recently added for anchor clicks and can extend to other elements.

**Comment by Enriqe** [comment]
@newmuis I agree that we could just do our own global handler within `amp-story`. We don't really need to overwrite the `href` or set priorities for now. We just need a global handler that e.g. checks that an element is tooltip-triggerable and descendant of `amp-story-grid-layer` and fire the corresponding actions.

But digging into @alabiaga priority implementation I'm thinking it might be useful in the future... (e.g. define priorities between hold to pause and navigation...).

I don't feel strongly about either side though, I think I could go forward with my implementation, and in the case that we need more functionality in the future (like priorities or overwriting the href), then I could change the handler to use the API.

@alabiaga @newmuis let me know your thoughts or if you feel I missed something.

**Comment by choumx** [comment]
> exposing an API in navigation.js will probably have no benefit other than readability (which is arguable) and having a pattern to follow for others to follow, if someone else with an extension would like to do something similar

The problem with each extension using its own click handlers is that installation order (and thus invocation order) will vary. The main purpose of centralized place is to have a strict ordering on invocation order. Improved readability is a nice to have.

**Comment by choumx** [comment]
@alabiaga Can this be closed now?

**Comment by alabiaga** [comment]
Yes, closing as this isn't required on their end as discussed with @Enriqe. Thanks
