### ISSUE TITLE
Google Cookie Choices - EU Cookie Law - AMP

### ISSUE THREAD

**Issue by Polylike** [ampproject/amphtml#1763]
Hey,

is there any AMP Solution for the European Cookie laws? 

"European laws require that digital publishers give visitors to their sites and apps information about their use of cookies and other forms of local storage." 

https://www.cookiechoices.org/

All Solutions work with JS/jQuerry

Thanks,
Daniel

**Comment by erwinmombay** [comment]
here is an example https://github.com/ampproject/amphtml/blob/master/examples/analytics-notification.amp.html
which unfortunately currently requires a server endpoint.

We have some code in our canary branch that get rids of that requirement
and would be a straight forward "copy-pastable" example.

**Comment by rudygalfi** [comment]
Yes, what @erwinmombay said.

They key is to use the [amp-user-notification](https://github.com/ampproject/amphtml/blob/master/extensions/amp-user-notification/amp-user-notification.md) feature to present the notice. You can track an acceptance of the notice and persist it server-side if you want to do things like avoid showing it on subsequent visits.
