### ISSUE TITLE
Navigaton.registerAnchorMutator() should allow same priority

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#17630]
Each `amp-analytics` tag can have its own `Linker` configuration. For each of these configurations we would like to register a callback. 

The call currently looks like this `navigation.registerAnchorMutator(linkerCallback, Priority.LINKER)`

I think that the linker priority should be static for all of these registrations, but this current throws an error, due to `registerAnchorMutator` not allowing two items to have the same priority.

**Comment by calebcordry** [comment]
cc/ @lannka @choumx

**Comment by choumx** [comment]
Are we sure that handler invocation across `Linker` configs are always order-independent? E.g. Is it possible for two `Linker` configs set or modify the same query param?

**Comment by calebcordry** [comment]
It is possible that a pub & analytics vendor specify same param name. In this case we will just create two separate query params with the same name. Talked to @lannka and we think this is fine. If the ingestion breaks it would be the pub breaking their own config.

**Comment by lannka** [comment]
forcing unique priority value for each handler might be infeasible in reality once we have more extensions using this API. I think we should leave it to individual extension to handle. the API should just following the time order of registration.

**Comment by alabiaga** [comment]
spoke to @choumx offline and we will allow same priority to be used. Thanks

**Comment by choumx** [comment]
@calebcordry That should be fine as long as registration order of multiple configs with `Priority.LINKER` is consistent.

@lannka We definitely need each extension to have its own priority value since extension download/execution order is unreliable. Multiple usages of the same priority value within an extension can be delegated to the extension.
