### ISSUE TITLE
FR : already have a semi working infinite-scroll, please patch stuff up to make this work

### ISSUE THREAD

**Issue by albalak88** [ampproject/amphtml#17651]
Hello!

I kinda succeeded in making an infinite scroll for AMP using only amp-list.  It uses recursive templates, with a new amp-list at the end of the template.

This works on Chrome desktop but not on Chrome Android.

On Android the loader animation is stuck forever.

Could you patch this up somehow?   Also, layout="container" would be really great for amp-list.

Thanks!
Jonathan

`
<div style="position:relative;height:10000px;">

    <amp-list
              src="/amp/listData/bizReviews.php?id=<?=$bizId?>&skip=20"
              layout="fill">

        <div placeholder style="position:absolute;top:0;text-align:center;">
            <i class="fa fa-spinner fa-spin" style="margin-top:20px;font-size:20px;"></i>
        </div>
        <template type="amp-mustache" id="reviewListTemplate" style="position:absolute;top:0;">
            
            <br>
            <br>
            {{userName}}
            <br>
            <br>
            
            {{#moreReviews}}
            <div style="position:relative;height:10000px;">
                <amp-list
                        src="{{moreReviews}}"
                        layout="fill"
                        template="reviewListTemplate"
                        >
                    <div placeholder style="position:absolute;top:0;text-align:center;">
                        <i class="fa fa-spinner fa-spin" style="margin-top:20px;font-size:20px;"></i>
                    </div>
                </amp-list>
            </div>
            {{/moreReviews}}
        </template>

    </amp-list>
</div>`

**Comment by aghassemi** [comment]
@albalak88 we have started working on first-class infinite list support. Please subscribe to https://github.com/ampproject/amphtml/issues/14060 to updates.
