### ISSUE TITLE
AMP Story bookend mouseover title

### ISSUE THREAD

**Issue by AutadeJS** [ampproject/amphtml#17654]
In bookend, when you mouseover a link or thumbnail image, a title pups up. It's same for all the links.

**Comment by newmuis** [comment]
Looks like this is because amp-story 1.0 has the mandatory `title` attribute, and the browser is using any ancestor's title on the element in the bookend.  We can strip the metadata at build time and store it in memory.

**Comment by gmajoulet** [comment]
Are we doing anything specific in `amp-story` that brings this behavior?

This doesn't repro:

````
<html>
  <head>
    <title>Should see this as a title when hovering the link</title>
  </head>
  <body>
    <a href="https://example.com">Hover me</a>
  </body>
</html>
````

**Comment by newmuis** [comment]
It's the `title` attribute in the `amp-story` metadata, rather than the `<title>` tag on the page that causes this.
