### ISSUE TITLE
Whitelist Array.push in amp-bind

### ISSUE THREAD

**Issue by AndrewKGuan** [ampproject/amphtml#17666]
This is a useful function which is more fundamental then some of the functions [that are already whitelisted](https://www.ampproject.org/docs/reference/components/amp-bind#white-listed-functions).
Right now the workaround is [1.2.3].join([4]) to append.

**Comment by nainar** [comment]
@choumx would this qualify as a GFI? Is the change needed here? https://github.com/ampproject/amphtml/blob/master/extensions/amp-bind/0.1/bind-expression.js#L136
