### ISSUE TITLE
Need initial visibility info in context

### ISSUE THREAD

**Issue by bobcassels** [ampproject/amphtml#1766]
When sending out an ad request, an important piece of information for the auction is whether the slot is visible.

The only current way to get visibility information is via the "intersection observer". But that is not immediately available. Intersection observer will schedule an evaluation at the time the observe method is called. So you don't get visibility info synchronously, but it will show up very soon after. It does make it near impossible to provide a 'viewability at the time of the request' semantic though.

We need to get that immediately. Ideally passed in with context, but any other synchronous way would be fine.

**Comment by bobcassels** [comment]
BTW, I'm happy to do the work here. But I see that the visibility code uses getBoundingClientRect, which is otherwise proscribed. So we should have some agreement that this is okay. Or a decision that it's not, in which case we'll need to figure out what other information we can provide to help in the auction.

**Comment by cramforce** [comment]
@bobcassels For my clarification: Do you want to use this for the implementation of a new or existing ad type that hardcodes sending this info? Or would you like to include the info with ad requests of, say DFP, that would not always include the info?

I think in the former case it would be reasonable to just immediately ask for a change record. You will always receive one immediately just after you asked for it, so while not synchronous it should be available in the order of a few millis.

**Comment by bobcassels** [comment]
@cramforce I am re-implementing the existing adsense ad handler, and I always wants to include this info. I was wanting to do it more immediately, but if you think using the existing mechanism is the right thing, I will try it and complain if it seems too slow.

**Comment by cramforce** [comment]
@bobcassels yeah, let us know if it seems slow.
