### ISSUE TITLE
SOURCE_URL appending extraneous equals sign

### ISSUE THREAD

**Issue by ObviouslyGreen** [ampproject/amphtml#17671]
## What's the issue?

While using SOURCE_URL within AMP string substitutions, it adds an extra equals sign to params that have no value. For example, if the url is "https://example.com/?amp", the SOURCE_URL variable would evaluate to "https://example.com/?amp="

There is a discrepancy with the value in window.context.sourceUrl (described in https://github.com/ampproject/amphtml/blob/master/ads/README.md) as well. The sourceUrl variable does not have the extra equals sign.

## How do we reproduce the issue?

Can reproduce by visiting https://amp-playground.firebaseapp.com/?amp and using the SOURCE_URL variable

i.e. `  <amp-pixel src="https://foo.com/pixel?href=SOURCE_URL"></amp-pixel>`

![screen shot 2018-08-22 at 2 25 41 pm](https://user-images.githubusercontent.com/4269549/44491844-55dff780-a617-11e8-80a7-36454a57eec5.png)

## What browsers are affected?

Demonstrated through amp playground, chrome dev tools, but observed over many browsers

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1534872626733 https://amp-playground.firebaseapp.com/?amp

**Comment by choumx** [comment]
@ObviouslyGreen Out of curiosity, how is this impacting your usage of AMP?

**Comment by ObviouslyGreen** [comment]
@choumx Not necessarily affecting usage, but found while digging through an issue with our analytics / optimizations for amp, specifically the discrepancy between the value in window.context and SOURCE_URL.

**Comment by zhouyx** [comment]
Thank you @ObviouslyGreen for filing the issue.

Looks like a regression caused by #15368.
