### ISSUE TITLE
AMP detection code with IE

### ISSUE THREAD

**Issue by Samreaksa** [ampproject/amphtml#17678]
Is there any way to add Browser detection code on website that will prompt the user to update their browser if IE10, 11 is detected with amp like jQuery . . . like jQuery?

For example: jQuery Code

if ( !$.browser.msie || $.browser.version < 12 ) {
// Add prompt to user here
}

**Comment by jpettitt** [comment]
You might be able to do that with a CSS hack, I'm not sure if the validator would object to the odd CSS.  You could definitely do it server side checking the user agent and returning a notice with `amp-list`.

**Comment by Samreaksa** [comment]
Hi @jpettitt ,

I really appreciate if you could give me a sample of user agent detection.

Thanks,
Sam

**Comment by jpettitt** [comment]
The PHP solution won't really work for AMP because pages get cached on the AMP cache so you can't serve browser specific content.   I suggest the CSS option as the best solution as it will allow the use of cacheable pages (i just checked and the validator is ok with it)

**Comment by craigscott29** [comment]
Given that it's only hitting Internet Explorer and the AMP cache is only served on mobile (where Internet Explorer isn't available), that's kind of a moot point whether it works in the cache or not. ¯\\_(ツ)_/¯

**Comment by jpettitt** [comment]
Google only serves AMP pages via the cache to mobile.  Other sites, using the Google or Cloudflare cache, may do something else.  In general it's a bad idea to serve different content on AMP pages based on `user-agent` as there is no way to know what user agent is hitting a cache and the cache does not support `vary: user-agent`

(`Vary: user-agent` is a bad idea in general, it leads to massive cache fragmentation.  In one sample of 100K requests Fastly found 8K different user agents)

**Comment by jpettitt** [comment]
Closing this issue
