### ISSUE TITLE
The mandatory text (CDATA) inside tag 'boilerplate (js enabled) - old variant' is missing or incorrect

### ISSUE THREAD

**Issue by AltanAdacay** [ampproject/amphtml#1768]
Hi, I have big problem! I cant fixed this error can you help me please.
This is console log error:  
**The mandatory text (CDATA) inside tag 'boilerplate (js enabled) - old variant' is missing or incorrect se..**

And olso you can test and control here is news site: 
http://www.habersert.com/amp/magazin/ivana-sert-e-nur-yerlitas-in-aldigi-maas-sorulunca--155

Thank you

**Comment by sriramkrish85** [comment]
@AltanAdacay  - thanks for reaching out - I think it is the validator that failed- you can fix this by using our new boilerplate code in the head. 

Follow the example - here 
https://github.com/ampproject/amphtml/blob/master/docs/create_page.md

You will need to delete this code in your head 
`<style>body {opacity: 0}</style><noscript><style>body {opacity: 1}</style></noscript>`

and replace it with the one here: 

https://github.com/ampproject/amphtml/blob/master/spec/amp-boilerplate.md

I shall work with the validation team to provide a better validation error

**Comment by cramforce** [comment]
But, the old code should still validate, no?

**Comment by sriramkrish85** [comment]
Yes on existing pages - (Not on new pages i guess)

@powdercloud can confirm.

**Comment by Gregable** [comment]
This looks like a validator parsing bug. @powdercloud and I are looking into it. It has to do somehow with the multibyte characters in the body, but what's going on is still a puzzle.

**Comment by cramforce** [comment]
@AltanAdacay For you: Don't worry about it. Our server side validator validates your page and the JS validator you are using will soon as well. Thanks for posting the bug!

**Comment by AltanAdacay** [comment]
Thanks all, I can not fixed  from since morning 09.30   

I'm was delete this code : <style>body {opacity: 0}</style><noscript><style>body {opacity: 1}</style></noscript>

and I'm append to under amp-custom styles: https://github.com/ampproject/amphtml/blob/master/spec/amp-boilerplate.md

not fixed this error... thank you again.

**Comment by powdercloud** [comment]
AltanAdacay Merhaba, bu problem bizim kodumuzdaki bir bug'dan dolayi kaynaklaniyor. Sizin sayfaniz da herhangi bir problem yok. Su an sorunu cozmek icin gerekli kodu hazirliyoruz. (translated by a friendly colleague)

**Comment by powdercloud** [comment]
http://www.habersert.com/amp/magazin/ivana-sert-e-nur-yerlitas-in-aldigi-maas-sorulunca--155#development=1 works now.

**Comment by AltanAdacay** [comment]
Thanks for everything... Yes work now perfectly

**Comment by biojazzard** [comment]
I feel nobody posted the solution.
For me it was: avoid whitespace.

**Comment by yegor256** [comment]
I was getting this message because there was `<style>...</style>` block inside HTML. I replaced it with `<style amp-custom>...</style>` and the problem disappeared.

**Comment by JeromeParis** [comment]
Hi,
On my webpage http://m.avocatferval.com/index.htm I still have the error message 
"The mandatory text (CDATA) inside tag 'head > style : boilerplate' is missing or incorrect"
while I respects https://github.com/ampproject/amphtml/blob/master/spec/amp-boilerplate.md
Could you help me finding what is wrong?
Thanks in advance
Jerome

**Comment by Gregable** [comment]
@JeromeParis you need to split your CSS into separate style tags. You have placed custom style inside the boilerplate style tag. Instead it needs to be in a `<style amp-custom>` tag.

**Comment by JeromeParis** [comment]
Hi,

Tanks a lot for your answer!

Best regards
J?r?me

-----------------

Le 1 juin 2016 ? 18:59, Greg Grothaus <notifications@github.com<mailto:notifications@github.com>> a ?crit :


@JeromeParis<https://github.com/JeromeParis> you need to split your CSS into separate style tags. You have placed custom style inside the boilerplate style tag. Instead it needs to be in a <style amp-custom> tag.

-

**Comment by gagadada11** [comment]
I have near the same problem with you today. But i can fix it now. 
Could you try to unintall some plugins on your website, then check install step by step again,

Then try to find out which plugin make this error, After that check the setting on that plugin. 

Some plugins will conflict and cause the problem. Prevous time, I install WP Fastest cache plugin on my wordpress, it make error when i run http://quanglepro.com/2016/04/13/tao-hieu-ung-chuyen-dong-cho-website-voi-revolution-slider/amp/#development=1 

http://quanglepro.com

**Comment by manishupadhyay** [comment]
Hi All,

I am facing the similar problem.
I have tried all the guide lines mentioned above.
Message is also not intuitive like what is the exact issue.
"Error Msg" : "The mandatory text (CDATA) inside tag 'head > style[amp-boilerplate] - old variant' is missing or incorrect"

**Comment by Gregable** [comment]
Please use the exact string found here:
https://github.com/ampproject/amphtml/blob/master/spec/amp-boilerplate.md

If you have that exact string you should be fine.

**Comment by gagadada11** [comment]
Dear  manishupadhyay 

For AMP page with error issue, I have some experience want to share with you
To fix it:

Step 1: Install this plugin on your wordpress **https://wordpress.org/plugins/amp/**
Step 2: Install this plugin on your wordpress **https://wordpress.org/plugins/glue-for-yoast-seo-amp/**
--> Follow the step here " https://yoast.com/setting-up-wordpress-for-amp-accelerated-mobile-pages/ "
If after these steps above, you still can not fix it on your wordpress site, Please deactive all of OTHERS plugin on your wordpress website to find out the plugin issue with AMP

I am sure you can fix it, if you  use wordpress like me.

To check the issue is fixed or not, you just use Chrome browser > Then add " /amp/#development=1 " behind url. 
If you see these infor " Powered by AMP ⚡ HTML – Version 1469143772973
validator.js:381 AMP validation successful. "  --> mean It is fixed correctly.

Thank you
quangle
[https://quanglepro.com/noi-dung-bai-viet-chuan-seo-rat-quan-trong/]

**Comment by manishupadhyay** [comment]
Thank you all.

I got problem resolved.
Actually i was using more than 1 style tag and some of the inline styling.
once i removed all of them, i got above problem resolved.

Thanks
-Manish

**Comment by AltanAdacay** [comment]
Hi, I have recently seen a similar addition to the AMP pages in Google Analytics Right Now system. Is that a problem? "...?usqp=Mq331aqcca="

**Comment by babakhoo** [comment]
I got the problem solved !
Actually you should put your custom style in HEAD but not anywhere that you choose.
In my case, I put the amp-custom style BEFORE the amp-boilerplate.
