### ISSUE TITLE
🌸 Cherry pick request for #17644 into #17495, #17636 (Approved)

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#17682]
**GitHub issue your cherry pick is fixing:** #17644 

**PR that you are requesting a cherry pick for:** #17675

**Release(s) you requesting this cherry pick into:** #17495, #17636 

Production Release? Release Issue #17495

Canary release? Release Issue #17636

Causes pages using amp-list and amp-mustache-0.2 to render incorrectly (dropping attributes in rendered markup). This can cause bad display bugs when the `class` attribute is dropped, for example.

**Comment by danielrozenberg** [comment]
While awaiting approval, I created two branches to kick off Travis builds:
* `amp-release-2018-08-23-on-pr-17495`
  * Target: prod
  * Base RTV: 1534872626733
  * Travis: https://travis-ci.org/ampproject/amphtml/builds/419708960
* `amp-release-2018-08-23-on-pr-17636`
  * Target: opt-in canary and 1% canary
  * Base RTV: 1534879991178
  * Travis: https://travis-ci.org/ampproject/amphtml/builds/419706219

**Comment by mrjoro** [comment]
Approving since this fixes a P0 that was in prod.

**Comment by danielrozenberg** [comment]
Cherry-picking complete. Track progress in the related release-tracking issues
