### ISSUE TITLE
Support stripping of JSON-hijack prefixes

### ISSUE THREAD

**Issue by acsant** [ampproject/amphtml#17691]
## What's the issue?

Components such as `amp-list` get data from JSON endpoints. For purposes of preventing JSON-hijacking (https://haacked.com/archive/2009/06/25/json-hijacking.aspx/), JSON get responses are sometimes prepended with prefixes such as `while(1)`. `amp-list` throws a parsing error on encountering such prefixes.

## How do we reproduce the issue?
Use `amp-list` and use a `src` url that returns a JSON response that has a anti-JSON-hijack prefixes such as `while(1)`.

## What browsers are affected?
I tested this on Google chrome and it is affected.

## Which AMP version is affected?

I used amp version 0.1 to test this.

## My comments:
* Maybe we could have `amp-list` take in a `stripPrefix` attribute that strips that value from the JSON response before parsing it.
```javascript
<amp-list src=_jsonendpoint_ stripPrefix="while(1)" ... />

**Comment by jpettitt** [comment]
Wouldn't it be better to do strict origin header checking on the JSON endpoint to prevent serving to invalid contexts and serve pure JSON?

**Comment by acsant** [comment]
@jpettitt I looked more into this and yes it seems like we should be covered by AMP CORS guidelines. However, this might still be a helpful or a "nice to have" feature because many new applications moving towards adopting AMP would have to ensure that their services return pure JSON. And if they did not, it might be a tedious thing to change their services to account for this. Furthermore, many apps might want to keep their custom JSON response for non-amp context. It's nice to have an option to accommodate custom prepended JSON. This is just in my opinion. I would like to know if you have an alternative viewpoint to this.

Thanks!

**Comment by aghassemi** [comment]
if we do this, should be part of our `fetch` helper.
