### ISSUE TITLE
Make amp-install-service-worker data-iframe-src attribute mandatory for AMP Cache Serving

### ISSUE THREAD

**Issue by gilbertococchi** [ampproject/amphtml#17698]
Hi all, currently data-iframe-src attribute is marked as optional in the [reference](https://www.ampproject.org/ko/docs/reference/components/amp-install-serviceworker) while it's actually necessary to make the Install Service Worker Installation possible and functional from AMP Cache URLs.

Can we consider making it mandatory also from the Component usage point of view?

**Comment by nainar** [comment]
The change needed is as follows: 

Change data-iframe-src to mention optional but needed for the AMP Cache.
