### ISSUE TITLE
Support for Piano Analytics

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#1769]
Initial support for Piano (http://piano.io) AI analytics.

PR #1652

**Comment by rudygalfi** [comment]
@avimehta Assigning to you since you're handling the review.

**Comment by rudygalfi** [comment]
FYI: Now being tracked in PR #2075

**Comment by nathangoulding** [comment]
Now being tracked in rebased PR #2279.

**Comment by rudygalfi** [comment]
Fixed by #2624.
