### ISSUE TITLE
Gmail Content Security Policy blocks external images (dynamically loaded image urls not getting rewritten)

### ISSUE THREAD

**Issue by happyboredom** [ampproject/amphtml#17708]
## What's the issue?

AMP for Gmail's Content Security Policy for `img-src` causes browsers to block external images that are not served by Google image proxy. I'm trying to use an `amp-list` to dynamically produce an image carousel. It works OK on ampbyexample playground but not within Gmail. It appears the URLs in my `amp-list` XHR response are not getting rewritten to conform to the CSP. Is there a workaround?

The browsers js console reports this error
```
#FIREFOX
Content Security Policy: The page’s settings blocked the loading of a resource at https://cdn.myimage.com/path/aaa.jpg (“img-src”).
```
```
#CHROME
Refused to load the image 'https://cdn.myimage.com/path/aaa.jpg' because it violates the following Content Security Policy directive: "img-src data: https://*.googleusercontent.com".
```

## How do we reproduce the issue?

1. Configure endpoint that returns a JSON response. (Figure 1)
2. Create an `amp-list` that renders `amp-img` tags within a mustache template. (Figure 2)
3. Send test email that contains the HTML appropriate AMP MIME-type

Figure 1. Sample JSON response from `myendpoint.com/foo/bar`, called by the `amp-list`
```javascript
{
  "items":{
    "title":"My photo gallery",
    "clickURL":"https://mysite.com",
    "images":[
        {"width":300, "height":250, "url":"https://cdn.myimage.com/path/aaa.jpg"},
        {"width":300, "height":250, "url":"https://cdn.myimage.com/path/bbb.jpg"},
        {"width":300, "height":250, "url":"https://cdn.myimage.com/path/ccc.jpg"}
    ]
  }
}
```

Figure 2. HTML for `amp-list` and `amp-mustache` output.
```html
<!doctype html>
<html amp4email="">
<head>
  <meta charset="utf-8">
  <title></title>
  <style amp4email-boilerplate="">body{visibility:hidden}</style>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>
  <script async custom-element="amp-list" src="https://cdn.ampproject.org/v0/amp-list-0.1.js"></script>
  <script async custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.2.js"></script>
  <script async custom-element="amp-carousel" src="https://cdn.ampproject.org/v0/amp-carousel-0.1.js"></script>
</head>
<body class="flemail">
<amp-list
    id="articlegroup"
    layout="fixed"
    width="500"
    height="500"
    src="https://myendpoint.com/foo/bar"
    class="bodygrid"
    template="amp-small-carousel">
</amp-list>

<template type="amp-mustache" id="amp-small-carousel">
  <section class="article">
<h2><a href="{{clickURL}}">{{title}}</a></h2>
{{#images}}  
<amp-carousel  width="300" height="250" layout="fixed" type="slides">
      <amp-img 
           layout="responsive"
           width="{{image.width}}"
           height="{{image.height}}"
           src="{{image.url}}"></amp-img>
    </amp-carousel>
{{/images}}
  </section>
</template>
</body>
</html>
```

## What browsers are affected?

Chrome and Firefox for Mac

## Which AMP version is affected?

AMP Version 1535038987988. The dynamically loaded images previously  worked within gmail  as of Jun 29, 2018. I don't have an exact date when it stopped working.

**Comment by choumx** [comment]
The CSP is likely working as intended, but the proxying of dynamic templates/images may not be implemented yet. /cc @raywainman

**Comment by zhangsu** [comment]
This was enabled prematurely and should be fixed now. Try refreshing Gmail. Sorry for the inconvenience!

**Comment by choumx** [comment]
Thanks for confirming Su; closing.
