### ISSUE TITLE
AMP validator extension showing a lot of no sense error

### ISSUE THREAD

**Issue by mauricionr** [ampproject/amphtml#17707]
**Please only file bugs/feature requests for AMP here.**

## What's the issue?

I don't know if this is the right place to report this issue

AMP validator is showing a lot of no sense error, check it in the screenshot

![screen shot 2018-08-24 at 14 43 12](https://user-images.githubusercontent.com/2263551/44599657-6d50e900-a7ad-11e8-9727-4527278f6da9.png)

## How do we reproduce the issue?

I don't know how to reproduce this error, maybe a unclosed tag.

## What browsers are affected?

I guess is not releated with the browser

## Which AMP version is affected?

I gues is not releated with the AMP version

cc: @nainar

**Comment by honeybadgerdontcare** [comment]
@mauricionr could you provide some of the html content that is producing this (if not all of it). And could you clarify what you're considering to be "no sense"?

**Comment by mauricionr** [comment]
@honeybadgerdontcare one example of no sense, i have the `The mandatory attribute '⚡' is missing in tag 'html ⚡ for top-level html'` why the amp validator is complaining about it?

i'm sending to you the html in slack.

Thanks for the response.

**Comment by mauricionr** [comment]
`i saw an script tag inside my html, i removed and still getting the same behaviour`

**Comment by honeybadgerdontcare** [comment]
@mauricionr just the `html` tag has several attributes that are not valid AMP:

`amp-version="1535038987988" class="i-amphtml-singledoc i-amphtml-standalone" style="padding-top: 0px !important; cursor: pointer;"`

None of those are allowed in AMP. I'm guessing that this may be the result of AMP already processed by the AMP Runtime instead of source AMP HTML. For instance it has style sheets that are for specific extensions. Those are not included in the source AMP HTML that a developer would produce and are injected by the AMP Runtime.

**Comment by mauricionr** [comment]
I'm not adding these attributes.

my AMP HTML is compiled in the server side without these attrs, i sent to you the HTML AMP already processed in the client.

i'm sending to you one example with a valid page, using the same "layout", and the invalid page with the same "layout" of the valid page, both already compiled by AMP Runtime.

i could not understand the last part,

```
For instance it has style sheets that are for specific extensions. 

Those are not included in the source AMP HTML that a 

developer would produce and are injected by 

the AMP Runtime.
```

**Comment by honeybadgerdontcare** [comment]
The HTML already processed in the browser/client by the AMP Runtime will not be Valid AMP and that appears to be what you're checking to see if it's valid. It won't ever be valid.

**Comment by mauricionr** [comment]
no, i'm not trying to check if my processed html is a valida AMP page, i just sent to you as you request 🤔 

but my point is, the amp validator throws to much errors and it's hard to identify which one is true

**Comment by honeybadgerdontcare** [comment]
If you can send me your initial page, before it's processed in the browser/client then I may be able to help you. But the screenshot you sent is of an AMP document after being processed by the AMP Runtime and that will always be invalid and hence why there are so many errors.

**Comment by mauricionr** [comment]
ok, sent
