### ISSUE TITLE
Improve docs for "building an AMP extension"

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#17714]
- [ ] Add instructions for creating "OWNERS" file for component.
- [ ] Add a checklist at the top for a quick list of what to make sure is done sure to do.
- [ ] Ensure that putting new components behind "experiment" flag is required.
- [ ] Add references to existing implementation and special requirements for types of contributions. For instance, if implementing a video-player, we should include special documentation and point to a few existing components to use as model.

**Comment by choumx** [comment]
/to @jridgewell @alabiaga Can you guys split the tasks here? I'm taking on #17715.

**Comment by alabiaga** [comment]
i'll take the first two

**Comment by alabiaga** [comment]
actually let me just do these tasks. Thanks
