### ISSUE TITLE
Enrich amp-ima-video with features from amp-video

### ISSUE THREAD

**Issue by felerticia** [ampproject/amphtml#17725]
The native `amp-video` has tons of features like (rotate-to-full, double tap on right or left....) but in order to use ads, I'm pretty much forced to use `amp-ima-video` which lacks these features sadly :(

Is there any way to use `amp-video` features in `amp-ima-video`

Thanks.

**Comment by felerticia** [comment]
Thanks @cathyxz and  @alanorozco
I appreciate all the hardwork!

Is that possible to add support for **360 videos** and also  **subtitles**  for amp-video too?

Happy Coding!

**Comment by torch2424** [comment]
Assigning to myself as I've been owning amp-ima-video. If anyone needs updates/desires this feature, feel free to mention me while this is in our backlog.

@felerticia If possible, could we close this, and open more issues that are more specific for the features you are looking for? We do agree amp-ima-video should follow amp-video more closely, and is what we are currently working on when we have time.

**Comment by alanorozco** [comment]
Closing. Specific issues should be created for each feature request to be discussed there.
