### ISSUE TITLE
Integrating with Ads - Dynamic Remarketing

### ISSUE THREAD

**Issue by stephengardner** [ampproject/amphtml#17723]
It's my understanding that Dynamic Remarketing requires a custom script to be put on the page.  Is there anticipated support for Dynamic Remarketing?  Adding a component to enable this?

**Comment by jasti** [comment]
Depends what the tag is trying to do. If it's simply setting cookies, you could use https://www.ampproject.org/docs/reference/components/amp-pixel?

**Comment by jasti** [comment]
@stephengardner, this sounds very specific to the app's behavior and unable to help. Probably best to reach out to the app's support? 

Sorry about not being able to help.

**Comment by stephengardner** [comment]
No I mean I literally run the app.  I own it.
Dynamic remarketing is a feature of Google Ads.  Here's info on Dynamic Remarketing, again, from Google.
https://support.google.com/google-ads/answer/6077091?hl=en&ref_topic=6077046

You have to add a script from Google onto your webpage.  It's a Google service that requires javascript be added to your page.

I am asking how to do this on AMP pages, since Google runs both of them.

**Comment by jasti** [comment]
Thanks for clarifying. Please note that although Google supports the AMP project, given the size of the company, not all Google products are supported in AMP. 
I don't believe this support is available today but to summarize your requirement: You'd want the Google Ads team (previously Google AdWords) to provide an AMP version of the dynamic remarketing tag that you can implement on your AMP site. This way, visitors who browse products on your AMP site may be shown those products on Google.com ads at a future date. Right? 
I'm CCing @rudygalfi who works with the Google Ads team who might be able to convey this feature request but I'd also recommend you do the same via your Google ads support channel. 

Thanks.

**Comment by rudygalfi** [comment]
Is this documentation helpful for what you're looking to implement? https://developers.google.com/google-ads/amp/landing-pages#google_ads_remarketing_example

**Comment by rudygalfi** [comment]
Closing this out because I think https://github.com/ampproject/amphtml/issues/17723#issuecomment-423237441 addresses this.

**Comment by stephengardner** [comment]
Hey @rudygalfi and @jasti - the aforementioned link is now broken.  Please let me know how to proceed with this example.  Again, we're looking for  examples of how to implement Remarketing or Dynamic Remarketing on AMP pages for Ads.

**Comment by stephengardner** [comment]
@rudygalfi just bumping this because as mentioned in my previous comment this link you posted is no longer working:
https://developers.google.com/google-ads/amp/landing-pages#google_ads_remarketing_example
Looking for an answer to this question and would rather not open a new issue
Thanks

**Comment by stephengardner** [comment]
@rudygalfi I investigated the link you sent and it doesn't mention any example for Dynamic Remarketing.  

**Step 1: Create and validate AMP pages** 
- worth noting, of course, but not necessarily related here to analytics.
**Step 2: Set up AMP for conversion tracking and analytics**
- Interesting, but I checked each of the links and none mention anything about Dynamic Remarketing
**Step 3: Enable AMP serving in the Google Ads UI**
- This is important but also doesn't mention Dynamic Remarketing

Is there an example I can see?  Several customers have asked for this integration.  Really hoping there's a direction we can be pointed in, in order to move forward with some testing.

Thanks

**Comment by rudygalfi** [comment]
Hi @stephengardner - sorry for the delay.

It looks like the content in the link I originally sent was changed. I'm not sure if this is due to the remarketing tagging itself having changed or not. However, what might be most helpful is to look at the version of the content that originally existed:

https://web.archive.org/web/20181220222720/https://developers.google.com/google-ads/amp/landing-pages

Check out the section under the heading "Google Ads remarketing example".
