### ISSUE TITLE
FR: can amp-script runtime environment support some windows/document API relied by our statistical script?

### ISSUE THREAD

**Issue by Jade05** [ampproject/amphtml#17727]
## What's the issue?

Our statistical script （UBT.js）relies on a lot of windows/document API which haven't been supported in the amp-script runtime environment

## Related API
 
API  | Detail
---- | ---
window.navigator | (language,userAgent,appName,appVersion,platform,hardwareConcurrency)
window.screen | (width,height,colorDepth)
winodw.location | (hostname, href, protocol,pathname,search,hash)
window.performance | -            
window.devicePixelRatio | -      
window.onerror | -
document.referrer | -
document.readyState | -
document.getElementById | -
document.createElement | -
document.addEventListener | -
Canvas | -
cookie | -
localStorage | -
Image | -
 
It strongly relies on cookie, localstorage and Image.

**Comment by jpettitt** [comment]
At the moment no.  AMP does not currently allow any javascript outside AMP components and runtime.  There is a project to allow javascript in AMP running in a [worker dom](https://github.com/ampproject/worker-dom).  See #14095 

Until then the only way to run javascript on AMP pages is in an `amp-iframe`.
