### ISSUE TITLE
[amp-lightbox] [IE11] lightbox does not appear when activated

### ISSUE THREAD

**Issue by thedavidzhao** [ampproject/amphtml#17766]
## What's the issue?
On IE11, amp-lightbox does not show up when it is activated, say with a tap on a button. Inline `display: none` remains on triggered amp-lightbox because `style[property] = null` does not work. Setting a style property to `null` works in other browsers.

It looks like the inline style `display: none` is not removed when the lightbox is activated, which is a consequence of
https://github.com/ampproject/amphtml/blob/29e1097b9b3800a3938669fb26a93bf6c2007330/extensions/amp-lightbox/0.1/amp-lightbox.js#L313 calling
https://github.com/ampproject/amphtml/blob/29e1097b9b3800a3938669fb26a93bf6c2007330/src/style.js#L267-L278

IE11 silently fails on https://github.com/ampproject/amphtml/blob/29e1097b9b3800a3938669fb26a93bf6c2007330/src/style.js#L275
when it tries to set `display` to `null`.

Instead, this line could be
```
styleObj[prop] = '';
```
which *should* work on all browsers :pray:

## How do we reproduce the issue?
1. Visit https://ampbyexample.com/components/amp-lightbox/
2. Click on `Open Lightbox` button
![button](https://user-images.githubusercontent.com/23362199/44765181-821cdc00-ab21-11e8-93a8-4994d67235c3.JPG)
3. See that scroll is disabled, but no lightbox appears.
4. In the console, run `document.getElementById('my-lightbox').style['display'] = null`. This won't do anything.
5. In the console, run `document.getElementById('my-lightbox').style['display'] = ''` The lightbox should appear.

## What browsers are affected?
IE11

## Which AMP version is affected?
1535038987988

**Comment by kevinkassimo** [comment]
Hi @thedavidzhao , thanks for contributing! Could you send a PR for this fix? Thanks!

**Comment by thedavidzhao** [comment]
Yeah, I can go ahead and do that!

**Comment by thedavidzhao** [comment]
I just ran my reproduction steps again and this looks fixed with AMP version `1810270220450`.
