### ISSUE TITLE
let form submit redirect to a new url 

### ISSUE THREAD

**Issue by felerticia** [ampproject/amphtml#17768]
I have a simple problem yet it seems impossible to solve in AMP!!

I have a simple form with an input and a submit button like this:

<form id="myform">
     <input type="text" id="srchInput"/>
     <button type="submit">Submit</button>
</form>
All I want is to be able to concat a static url to the input value and redirect the page to the result, when the form is submitted.

For instance if the user inputs: "Hello" and submits the form, I would like to redirect him to a page like "MY/STATIC/URL/Hello".

Is there any way to achieve this in amp?

**Comment by cvializ** [comment]
Hi @felerticia thanks for asking about this feature! This is possible using amp-form and the `AMP-Redirect-To` header. The server response can set the value of the header based on the form values after the user submits. Then AMP will redirect the user to the URL in the header. 

Here's a link to the documentation: https://www.ampproject.org/docs/reference/components/amp-form#redirecting-after-a-submission

I'll close this for now. Thanks again!
