### ISSUE TITLE
Feature request: Add new event for hover

### ISSUE THREAD

**Issue by buihoanghai** [ampproject/amphtml#17765]
We migrated our products listing page to AMP. It is fantastic now. We want to our users have a best experiment so we try to keep previous features of last version. Unfortunately when we work around try to keep hover effect on product cards we increased the HTML size a a lot. Some our pages are coming up to 1MB which will impact to our CTR even we down the number of products from 100 -> 60 [example](https://iprice.my/bags/) I tried to remove hover stuffs then these pages reduce down more than 50% size. 
So I think if we create event for hover or amp-hover component it will help us a lot.

**Comment by aghassemi** [comment]
deduping with https://github.com/ampproject/amphtml/issues/12245
