### ISSUE TITLE
Google Ad Manager: Support Fluid along with multi-size

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#17764]
At the moment, 
- Fluid has to be primary size on a multi-size ad request 
- When fluid is defined as one of the sizes, the ad won't render as long as the ad is in the current viewport. 

One workaround for this is to allow defining fluid as a secondary size along with a primary size, which would allow AMP to reserve the primary size available and let the fluid ad (if selected) render inside of the primary size. This way, the fluid ad can render even if it's in the current viewport. In such a case:
- if the fluid ad knows to take up the entire available height based on the width, the UX would be just fine
- if the fluid ad doesn't know to take up the entire available height and can only expand to the fixed aspect ratio height based on the available width, then there may be whitespace below and above the ad but that's no different than how we support multi-size ATF slots. 

Also, we should add a sample in ABE (or Ad Manager helpcenter) and improve our documentation of unsupported cases, if any.

**Comment by jasti** [comment]
@glevitzky has this launched in canary?

**Comment by cathyxz** [comment]
PR #17963 was a part of release [1809181624140](https://github.com/ampproject/amphtml/releases/tag/1809181624140), originally tracked by https://github.com/ampproject/amphtml/issues/18159 and released to production in https://github.com/ampproject/amphtml/issues/18374 per release [1810021759000](https://github.com/ampproject/amphtml/releases/tag/1810021759000). I *think* this is safe to close, but I don't have enough context to know if PR #17963 is sufficient so defer to @jasti and @glevitzky.

**Comment by glevitzky** [comment]
Yes, this is safe to close. Apologies for not doing so sooner.
