### ISSUE TITLE
🌸 Cherry pick request for PR #17762 (approved)

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#17771]
**GitHub issue your cherry pick is fixing:**

Issue #17761

**PR that you are requesting a cherry pick for:**

PR #17762 

**Release(s) you requesting this cherry pick into:**

Production Release? Release Issue #17636
Canary release? Missing release issue for canary

**Why does this issue meet the cherry pick criteria**

The bug causes the last image in `amp-carousel type="scroll"` not to load whenever the width of the carousel is less than the width of the image. `amp-carousel` impacts a lot of users. 

**Notes**
This has been mitigated by a production rollback, and is therefore not an active P0 (per https://github.com/ampproject/amphtml/issues/17761#issuecomment-416887856).

**Comment by cramforce** [comment]
Would be good to note here that the production issue has been mitigated, so this is not an active P0.

Independent of that, the cherry-pick is approved, of course.

**Comment by cathyxz** [comment]
Got it. Added a note on that in the issue above. Thank you!

**Comment by cathyxz** [comment]
Re-assigning to @erwinmombay and myself to see this through now.

**Comment by erwinmombay** [comment]
this should be fixed in production and latest canary
