### ISSUE TITLE
Proactively inform contributors about the delay between PR review and merge

### ISSUE THREAD

**Issue by tobie** [ampproject/amphtml#17829]
## What's the issue?

See [this slack conversation](https://amphtml.slack.com/archives/C9HRJ1GPN/p1535041609000100?thread_ts=1535041326.000100&cid=C9HRJ1GPN) between @jpettitt and @slocka.

There's a period of time when a PR is reviewed and when it is merged that is tied to AMP's release process, as detailed in the [release schedule](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md).

This is not necessarily obvious to the contributor, who might feel stuck in limbo. 

It would be good do be proactive about this. For example by posting a comment that explains this once the PR has been approved (is there a process doc where this could be added?), or having a bot automatically do so.

**Comment by choumx** [comment]
@erwinmombay Do we still have the bot that adds "In production" labels?

**Comment by jpettitt** [comment]
In a perfect would I'd love to see it work like this.

1. When a commit is merged we don't close the issue it fixes, instead we label it merged/pending release.
2. When it's released to dev channel a bot adds a comment "in dev channel release #123456" and a "dev channel" label,
3. When it's pushed to prod a bot adds a comment with the releases #, removed the pending label, adds a "production" label and closes the issue

**Comment by tobie** [comment]
I'm wondering if the [Deployments API](https://developer.github.com/v3/repos/deployments/) couldn't be used for this. I'm not super sure what it does, but there seems to be UI elements you can hook into to provide a deployment status:

![Screencapture of deployment API UI](https://www.dropbox.com/s/e9enwnwibfuqarg/Screenshot%202018-10-19%2018.12.44.png?dl=0)

**Comment by erwinmombay** [comment]
@tobie do you know of any other open source project that uses the deployment API? just curious and would like to see it in action

**Comment by erwinmombay** [comment]
@tobie thanks so much!

**Comment by rsimha** [comment]
@erwinmombay Will it be easy to turn on our bot that applies "In Canary" and "In Production" labels for the time being, while we investigate other fixes?

**Comment by erwinmombay** [comment]
@rsimha yes

**Comment by cathyxz** [comment]
Here's another example of an issue that could benefit from this: https://github.com/ampproject/amphtml/issues/20829.

**Comment by rsimha** [comment]
This is now being tracked by https://github.com/ampproject/amp-github-apps/issues/348.
