### ISSUE TITLE
Built-in Google Analytics configuration not recording page title correctly

### ISSUE THREAD

**Issue by bdchin** [ampproject/amphtml#1782]
The built-in Google Analytics configuration in https://cdn.ampproject.org/v0/amp-analytics-0.1.js is missing an ampersand before the "dt" parameter:

`basePrefix: "v=1&_v=a0&aip=true&_s=${requestCount}dt=${title} ...`

This causes the title to be sent as part of the _s value instead.

**Comment by rudygalfi** [comment]
This is a duplicate of #1778

cc @avimehta
