### ISSUE TITLE
Give option to modify background filter in AMP Stories

### ISSUE THREAD

**Issue by psdtomanythings** [ampproject/amphtml#17843]
At the moment, we have applied filters to the background image in an AMP Story page. But, as AMP Story CSS by default applies the blur(50px) filter to the BG image, it doesn't copy the filters applied to the background image in AMP Layer. Due to this, the BG blur & Image in the front do not go with each other and look out of sync. A great thing to do will be to give an option to extend the filters or customize them. 

<img width="1619" alt="screen shot 2018-09-04 at 3 58 14 pm" src="https://user-images.githubusercontent.com/22929187/45026303-87b37e00-b05b-11e8-8687-ef46353987b7.png">

**Comment by newmuis** [comment]
Good point, and we should fix this.

You'll almost certainly get better performance if you can bake these filters into the assets, though.  Is that something that would be possible on your end?

**Comment by psdtomanythings** [comment]
The better option will be the one you initially suggested. We are generating these filters on runtime and  applying them to images and saving / resaving them will be resource & performance intensive. Best thing will be to capture the filters and apply to BG.

**Comment by newmuis** [comment]
We've found that CSS filters are too slow, so I don't think we'll be providing this.  The automated background image is also no longer applied.
