### ISSUE TITLE
Fix flaky visual diff test for `amp-bind - Amp By Example`

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#17849]
The ["amp-bind - Amp By Example"](https://github.com/ampproject/amphtml/blob/master/examples/visual-tests/amp-by-example/components/amp-bind/index.html) visual diff test is currently marked as flaky: https://github.com/ampproject/amphtml/blob/b19a67c7215fb601237a20a04ec41c090a5eb559/test/visual-diff/visual-tests#L608-L614

See example of a flaky run: https://percy.io/ampproject/amphtml/builds/797668/view/44814688/1400?mode=diff&browser=firefox&snapshot=44814688

Please reassign this if you're not the right person to fix this

**Comment by choumx** [comment]
This is caused by Vimeo abuse detection. Skipping such tests is probably the right thing to do.

**Comment by danielrozenberg** [comment]
I will be removing Amp By Example pages from visual diff tests soon, so this issue is no longer relevant

**Comment by choumx** [comment]
@danielrozenberg 😱 What's the new hotness?

**Comment by danielrozenberg** [comment]
email soon ;)
