### ISSUE TITLE
Fix flaky visual diff test for `amp-analytics - Amp By Example`

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#17848]
The ["amp-analytics - Amp By Example"](https://github.com/ampproject/amphtml/blob/master/examples/visual-tests/amp-by-example/components/amp-analytics/index.html) visual diff test is currently marked as flaky: https://github.com/ampproject/amphtml/blob/b19a67c7215fb601237a20a04ec41c090a5eb559/test/visual-diff/visual-tests#L583-L589

See example of a flaky run: https://percy.io/ampproject/amphtml/builds/858103/view/49620836/375?mode=diff&browser=firefox&snapshot=49620836

Please reassign this if you're not the right person to fix this

**Comment by lannka** [comment]
<img width="367" alt="screen shot 2018-09-04 at 11 32 44 am" src="https://user-images.githubusercontent.com/8496897/45050485-48266b00-b036-11e8-9f47-62db7e48bf4a.png">

The page has a floating box with dynamic content on it. Given nature of amp-analytics being a non-UI component, I suggest we just remove the percy test for amp-analytics.

@danielrozenberg

**Comment by danielrozenberg** [comment]
I will be removing Amp By Example pages from visual diff tests soon, so this issue is no longer relevant
