### ISSUE TITLE
Fix flaky visual diff test for `amp-brightcove - Amp By Example`

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#17850]
The ["amp-brightcove - Amp By Example"](https://github.com/ampproject/amphtml/blob/master/examples/visual-tests/amp-by-example/components/amp-brightcove/index.html) visual diff test is currently marked as flaky: https://github.com/ampproject/amphtml/blob/b19a67c7215fb601237a20a04ec41c090a5eb559/test/visual-diff/visual-tests#L623-L630

See example of a flaky run: https://percy.io/ampproject/amphtml/builds/889329/view/52120454/375?mode=diff&browser=firefox&snapshot=52120454

Please reassign this if you're not the right person to fix this

**Comment by aghassemi** [comment]
@danielrozenberg As discussed offline, these are all dynamic iframes. Visual tests don't really make sense here. All of these have functional tests to ensure iframe loads but what ends up inside the iframe is not something we care about as they are all 3P content.

Could you please remove the visual tests and close the issues?

**Comment by danielrozenberg** [comment]
I will be removing Amp By Example pages from visual diff tests soon, so this issue is no longer relevant
