### ISSUE TITLE
FR: Callback for immediately entering/leaving viewport

### ISSUE THREAD

**Issue by kevinkassimo** [ampproject/amphtml#17870]
## What's the issue?

Currently, we use `viewportCallback` to perform actions related to elements entering/leaving viewport. Due to implementation nature, the callback is not necessarily immediately triggered when the element just goes out of viewport. Instead it usually happens after the component is at least 25% viewport height/width away.
https://github.com/ampproject/amphtml/blob/7885e5603e754298ab73758977da9322950a924b/src/service/resources-impl.js#L1576-L1581

The delay is justified for unloading resource purposes. However, using it as a perfect indication for element leaving viewport will cause some issues (see below section).

It might be necessary to introduce a new callback to the runtime (something like `immediateViewportCallback`) once the top/bottom of the corresponding element left the viewport. It is a desired feature for both `amp-image-slider` and `amp-carousel`.

## How do we reproduce the issue?

1. Go to https://ampbyexample.com/components/amp-image-slider/
2. Interact with any of the slider (except for the one with `disable-hint-reappear` attribute set) and ensure its hint is hidden
3. You'll notice the hint only comes back after you scroll the element far away enough from the viewport. Ideally it should have reappeared once the bottom of the slider leaves the viewport.

### Add `immediateViewportCallback(inImmediateViewport)`
Implements a new runtime callback that would be invoked exactly when the element enters/leaves viewport.

This is easy to implement and has almost no disruption to the current runtime design. However, the action of adding a new callback might be an overkill.

https://github.com/kevinkassimo/amphtml/blob/cc20188e53f4fabae9529ffc8b4cd7bb2f25f995/src/service/resources-impl.js#L1598-L1601

### Add configuration param `this.shouldImmediateViewport`
Expose a boolean on `BaseElement` `this.shouldImmediateViewport = false`. Default to `false` (with 25% expansion, no difference from current behavior). If set to `true`, the runtime would use the non-expanded version of viewport rect for the specific element.

This is also easy to implement, but setting the variable to `true` would also affect the original resource load/unload side effects.

### Change to `viewportCallback(inViewport, inImmediateViewport)`
Make the `viewportCallback` take 2 arguments, the latter corresponding to our exact entering/leaving case. This means that the `viewportCallback` would be triggered for twice on leaving viewport: first on just leaving, with arguments `true, false`, and the second time on leaving the 25% expansion, with arguments `false, false`.

Personally believe this is a pretty bad choice since it would impact a lot of current components.

**Comment by aghassemi** [comment]
@kevinkassimo Like option 1 and agree option 2 is not the best as it requires changes to all components. 

Can we expand the flexibility of option 1? For example we have an existing override that decides how many viewports away a component renders called `renderOutsideViewport` which returns a number like `0.5`. 

Maybe we can borrow the same concept and have a `viewportCallbackMargin()` override and have the default return `0.25` and allow components to set it to whatever. `0` acting as immediate viewport. Negative margin support to shrink the viewport would be nice too and I think we get that by default anyway.

**Comment by kevinkassimo** [comment]
@aghassemi Sounds good to me. The only possible (not quite likely) problem is that making it configuration also means we need to keep recalculating different expanded rect for components with such customization. It would not be that heavy considering that most components won't modify the value, and we can also cache the calculated value inside each `discoverWork_` call when looping through the resources.

(Mentioning about caching, sounds reasonable that we could also move these values and the current 25% expanded rect to be lazily calculated and cached inside `getRect()` of `viewport-impl.js`)

**Comment by choumx** [comment]
Do you have any other example use cases for this API? I'm not convinced that showing the slider hint immediately after exiting viewport is desirable UX.

**Comment by aghassemi** [comment]
This came from UX review. @kevinkassimo @spacedino was the idea that the user actually sees the hint reappearing? (whereas currently because it reappears early, by the time user gets to it, it is already there)

**Comment by kevinkassimo** [comment]
@aghassemi No, the original idea is that if the user scrolls the element out of view, they are always guaranteed to see the hint of the slider reappear.
I would say it is not a very big issue from my own point of view. We can see if this could be a P3

**Comment by samouri** [comment]
Closing due to staleness and lost context
