### ISSUE TITLE
AMP.navigateTo issue when opening link in new tab and navigating original window 

### ISSUE THREAD

**Issue by heyvin** [ampproject/amphtml#17883]
I need to achieve the same behavior as prompted in this issue: https://github.com/ampproject/amphtml/issues/6221
I've tried the solution:
`
<a href="https://example.com" on="tap:AMP.navigateTo(url='https://example.com')" target="_blank">Click me</a>
`
which had been recommended before @aghassemi closed the ticket.
It's working on desktop browser but doesn't seem to be fine on iOS browsers (Safari, Chrome).

**Testing URL:** https://heyvin.github.io/amptest/navigate.html
**Actual:** clicking on "Click me" button will navigate original window to another URL. However it won't open a new tab.
**Expected:** clicking on "Click me" button will navigate original window and open a new tab.
**Affected browser:** mobile browsers on iOS (Safari, Chrome,...).

**Comment by kevinkassimo** [comment]
Just tested, It is actually not working on all Webkit based browsers (desktop Safari also)

**Comment by kevinkassimo** [comment]
@heyvin So currently there is a hack to solve the problem you are having right now. Try this:
`<a id="el" on="tap:el.scrollTo(duration=500),AMP.navigateTo(url='https://yahoo.com')" href="https://google.com" target="_blank">Click me</a>`. Basically, artificially create a delay before the `AMP.navigateTo` is triggered.

__Example URL__: https://gamy-grill.glitch.me/

**Comment by heyvin** [comment]
Hi @kevinkassimo,
It works perfectly. Thank you for your quick response.
When do you have plan to actually fix this in navigation source code? I'll apply this fix in the meantime.

**Comment by aghassemi** [comment]
@heyvin Ideal solution IMO is for us to support `target` option for `navigateTo()`. Created https://github.com/ampproject/amphtml/issues/17899 to track that. Thanks @kevinkassimo for finding a workaround.
