### ISSUE TITLE
Reset timeout for audio message when audio icon is clicked

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#17882]
Right now, we toggle `i-amphtml-story-messagedisplay` to `show` when the icon is clicked, and after a timeout, we reset the value back to `noshow`.  However, if the user clicks the icon again while the value is set to `show`, we should reset the timeout.  Otherwise, we allow the odd experience of clicking the audio icon right before the message disappears, seeing the message change, but it immediately disappears.

**Comment by gmajoulet** [comment]
Closed by #17898
