### ISSUE TITLE
amp-ima-video with preroll triggeres to video-play events

### ISSUE THREAD

**Issue by ingoingoingo** [ampproject/amphtml#17905]
## What's the issue?

The amp-ima-video component triggers the videoplay twice to amp-analytics when a preroll is loaded.
Currently there is no way to differ between a tracking of how many prerolls are started and how many video plays are made. Event worse I would count two video views when the video plays which messes up the analytics and makes tracking it worthless.

## How do we reproduce the issue?

I created a copy of the amp-ima-video example page on Codepen. https://codepen.io/ingoingoingo/full/vzeerW/ 
In amp-analytics I added tracking to trigger an event when the video starts playing.

`<amp-analytics type="googleanalytics" id="analytics">
<script type="application/json">{
          "vars": {
            "account": "UA-73836974-xxx"
          },
            "triggers": {
              "myVideo": {
                "on": "video-play",
                  "request": "event",
                    "selector": "#myVideo"
              }
            }
        }
</script>
</amp-analytics>`

1. Open https://codepen.io/ingoingoingo/full/vzeerW/ 
2. Scroll to the video and start it
3. Check the requests that are made to Google Analytics

As you can see the event is triggered once when the preroll starts and once when the actual video starts.
AFAIK there is no way to to differ those events.

## What browsers are affected?

All browsers

## Which AMP version is affected?

Same version as on the example page.

**Comment by jasti** [comment]
CC @torch2424 @alanorozco as well.
@aghassemi is this related to the video analytics integration or the IMA implementation?

**Comment by torch2424** [comment]
@jasti 

I'll look into to this 😄

**Comment by torch2424** [comment]
@jasti Going to work on a fix now, but unforturnately, one thing we should consider is:

How many people already have systems in place to get around this bug?

It's definitely something we should consider, and try to communicate to our partners before merging a fix.

**Comment by jasti** [comment]
@torch2424 there are about 200 domains using this ATM but not sure how many get around it. Remember that the ad playback is available from the adserver (which is independent of amp-analytics) and this is only applicable to developer who want to measure analytics themselves. 

Is there a way to programmatically find out if anyone is working around the bug?

**Comment by torch2424** [comment]
@jasti Ahh that makes sense.After talking to Yuxuan, we don't think there is since it would probably be done on a backend server of some sort.

Can we contact any big publishers that may be using this and give them a notice, If not, we can slowly introduce the feature through our canary process, and then go from there?

**Comment by torch2424** [comment]
Opened a PR to fix this at #18618 

@jasti I'll work with Yuxuan to do this "graceful" push to production

@ingoingoingo Would you be so kind to look at the screenshots, and let me know if this solves your problem?

Thank you everyone!

**Comment by ingoingoingo** [comment]
@torch2424 Thanks. Looks like this will fix it.
I am not aware of those other events that are shown your screenshot. Are those documented anywhere?
