### ISSUE TITLE
Allow a delay to add/enable a specific trigger

### ISSUE THREAD

**Issue by dougscher** [ampproject/amphtml#17915]
## What's the issue?
Need to hold off on certain events from triggering to limit unneeded events to occur

## How do we reproduce the issue?
If you setup a scroll trigger and most of the page fits on one screen,
and set:
scrollSpec: {
  "verticalBoundaries": [20, 40, 60, 80, 100]
},

5 events will fire at once.

If a trigger could be ignored, except for maybe the last one for a period of time, this would avoid this issue.

If a timer trigger could be setup to contain it's own triggers section that could contain the triggers to be armed, that would be ideal:
```
triggers: {
	trackPageView: {
		on: 'visible',
		request: 'trackPageView'
	},
	triggerTimer: {
		on: 'timer',
		timerSpec: { interval: 10, maxTimerLength: 9.9999999, immediate: false },
		triggers: {
			scrollPings: {
				on: 'scroll',
				scrollSpec: {
					"verticalBoundaries": [20, 40, 60, 80, 100]
				},
				extraUrlParams: {
					pp_ev: 'scroll'
				},
				request: 'trackPagePing'
			},
			focusPings: {
				on: 'visible',
				extraUrlParams: { pp_ev: 'focus' },
				visibilitySpec: { totalTimeMin: 10000, repeat: true },
				request: 'trackPagePing',
			}
		}
	}
}
```
## What browsers are affected?
All

## Which AMP version is affected?
I assume all

**Comment by zhouyx** [comment]
@dougscher Trying to understand your requirement here. 
> If a trigger could be ignored, except for maybe the last one for a period of time, this would avoid this issue.

This can be achieved with the batching feature. Basically you can batch the trigger request within a period of time. 

> If a timer trigger could be setup to contain it's own triggers section that could contain the triggers to be armed, that would be ideal:

Are you suggesting to only fire the contained triggers within an interval? And then stop triggering them afterwards? That sounds like a reasonable feature to me. But more like a feature to every trigger other than the timer trigger.

BTW: If want you want is to start timer trigger after a certain event, we already have support for `startSpec`. https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md#timer-trigger

Please let me know if batching [feature](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md#batching-configs) can help with the situation here. Thanks

**Comment by dougscher** [comment]
I think batching and startSpec may do what I want, let me play with it.
When was startSpec added? I do not recall seeing this before.

One other question, do you handle Intent-to-Implement requests?
Thanks!

**Comment by lannka** [comment]
> One other question, do you handle Intent-to-Implement requests?

Hi @dougscher , please take a look at the [contributing guideline](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#contributing-a-new-feature-concept--design-phase) . For features with good complexity, it might be helpful to briefly discuss the feature before you write a full design.

**Comment by zhouyx** [comment]
`startSpec` was introduced a few months ago. There was a design review for that. 
https://github.com/ampproject/amphtml/issues/11290

**Comment by dougscher** [comment]
Any update on this?

**Comment by zhouyx** [comment]
I believe the batching feature could fulfill this requirement.
https://amp.dev/documentation/components/amp-analytics/#schedule-batch-requests
