### ISSUE TITLE
amp-viz-vega doesn't pass validation

### ISSUE THREAD

**Issue by kina4smile** [ampproject/amphtml#17937]
Hello! We are trying to implement the 'amp-viz-vega' component but, we are getting a validation error every time. And even if we try to validate 'amp-viz-vega' example code from this link https://github.com/ampproject/amphtml/blob/master/examples/viz-vega.amp.html it still doesn't pass the validation.
This is the error we are getting in dev-console. Is it disabled at all now?

![screen shot 2018-09-07 at 2 46 22 pm](https://user-images.githubusercontent.com/7254847/45217527-1703a000-b2ad-11e8-876d-a1da500fa000.png)

**Comment by kevinkassimo** [comment]
Hi @kina4smile , this is due to the component currently being an [experiment](https://www.ampproject.org/docs/reference/experimental)

**Comment by aghassemi** [comment]
@kina4smile We are planning to launch it by the end of the year. Please follow https://github.com/ampproject/amphtml/issues/4171
