### ISSUE TITLE
AMP-date-picker:  Can't display the correct calendar when you have picked a date 

### ISSUE THREAD

**Issue by xiekun09** [ampproject/amphtml#17936]
## Can't display the correct calendar when you have picked a date 

I try to use amp-date-picker, but it seems when I have picked a date then I pick it again, it still displays the current month calendar, not I picked.

for example, I picked a date for 2019-1-3 but when I picked again, it shows calendar Sept. 2019 not Jan 2019

## How do we reproduce the issue?

I just used the example code, it seems just happened on type 'single' 

```
<amp-date-picker id="simple-date-picker"
  type="single"
  mode="overlay"
  layout="container"
  on="select:AMP.setState({date1: event.date, dateType1: event.id})"
  format="YYYY-MM-DD"
  open-after-select
  input-selector="[name=date1]"
  class="example-picker space-between">
  <div class="icon-input"></div>
  <div class="ampstart-input">
    <input class="border-none p0"
      name="date1"
      placeholder="Pick a date">
  </div>
  <button class="ampstart-btn caps"
    on="tap: simple-date-picker.clear">Clear</button>
  <button class="ampstart-btn caps"
    on="tap: simple-date-picker.today">Today</button>
  <button class="ampstart-btn caps"
    on="tap: simple-date-picker.today(offset=1)">Tomorrow</button>
  <template type="amp-mustache"
    info-template>
    <span [text]="date1 != null ? 'You picked ' + date1 + '.' : 'You will see your chosen date here.'">You will see your chosen date here.</span>
  </template>
</amp-date-picker>

```

## Suggestion:
if date picker can select month and year it will be wonderful

Thanks
Ken

**Comment by cvializ** [comment]
Hey thanks for opening this @xiekun09! I am able to reproduce, and this shouldn't be happening. We'll take a look at fixing it soon.

**Comment by cvializ** [comment]
Looks like a known issue with `react-dates` (1). I have a workaround in in-progress. 

(1): https://github.com/airbnb/react-dates/issues/951#issuecomment-359035057
