### ISSUE TITLE
Decouple runtime sanitization from cache modifications e.g. target="_self"

### ISSUE THREAD

**Issue by michael-martin-al** [ampproject/amphtml#17943]
## What's the issue?

Currently, only `_top` or `_blank` are allowed as anchor targets in amp-mustache templates. Please consider allowing `_self` as an anchor target when sanitizing `amp-mustache` output.

## How do we reproduce the issue?

Here's an example using `amp-list`, `amp-selector` and `amp-mustache`:

```
<amp-list
  layout="fill"
  src="/some/json/endpoint"
  single-item
  items=".">
  <template type="amp-mustache">
    <amp-selector layout="container">
      <ul>
      {{#items}}
        <li>
          <a
            target="_self"
            href="{{urlWith}}{{somePlaceholders}}"
          >
            {{local_title}}
          </a>
        </li>
      {{/items}}
      </ul>
    </amp-selector>
  </template>
</amp-list>
```

In this example, the `target="_self"` gets replaced with `target="_top"` because of the code on line 326 in `purifier.js`. 

This causes navigational issues when people put my site inside an iframe ( a common use-case for bible.com ). Instead of navigating around inside the iframe, my site takes over the top frame. 

However, if I include an anchor tag outside of the mustache template, it does not get sanitized and it's target doesn't get replaced. As a result, if a user uses these non-sanitized links to navigate my site everything works as expected, staying within the bounds of the iframe.

Would it be possible to allow `_self` as a whitelisted target attribute for anchors inside `amp-mustache` templates?

You can see an example of this behavior on my live site: https://www.bible.com/bible/116/MAT.1.NLT

## What browsers are affected?

All Browsers. All versions.

## Which AMP version is affected?

Not sure how to determine AMP version... maybe `011535566825959`.

**Comment by choumx** [comment]
Thanks for the detailed FR. 

This is actually a constraint due to the way AMP pages are served from the AMP Cache. In those cases, the AMP pages are also embedded in an iframe and we explicitly want to avoid `_self` navigation for many reasons. 

https://github.com/ampproject/amphtml/blob/master/spec/amp-cache-modifications.md#anchor-tags-must-have-a-target-of-_blank-or-_top

It's not obvious to me what the solution is here. Will require some thought.

**Comment by michael-martin-al** [comment]
Thanks @choumx. 

It's interesting. Links outside of a mustache template do not automatically get the `target='_top'` attribute. Instead, it seems like these links only get the attribute if it's being viewed inside a frame. I'm not sure where that detection is happening.

I'll be glad to help if there's anything I can do.

**Comment by choumx** [comment]
One option is to disable this behavior for obviously invalid AMP pages (which will never be served from cache) e.g. missing "amp" attribute in `<html>` tag.

**Comment by wille** [comment]
Also requesting this feature so we can have proper iframe support.

**Comment by wille** [comment]
Looking through the code and cannot find any runtime functions related to detecting if the document is at least tagged as a valid AMP document. Could you point me in the right direction?

**Comment by robtex** [comment]
https://github.com/ampproject/amphtml/pull/25008 seems to solve this issue in a simple enough way. Can't wait to have it reviewed!
