### ISSUE TITLE
Customizable default config in linkers

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#17954]
We'd like to introduce settings that apply to all linkers, so that
1) configuration is simpler for users
2) analytics vendors can add/change linkers without asking users to retag the pages.

```js
linkers: {
  enabled: true,
  proxyOnly: false,
  destinationDomains: ['amp.example.com', 'example.com'],

  linkerA: {
     ...,
     proxyOnly: true,
     destinationDomains: ['amp.example.com'],
  },
  linkerB: {
     ...
  },
}
```
The default settings are specified under `linkers`. As shown in the above example, `linkerA` has specified override of `proxyOnly` and `destinationDomains`. `linkerB` will inherit all the default config.

For #16737

/cc @jeffjose @btownsend @zikas

**Comment by jeffjose** [comment]
+1 for this change. Looks much cleaner.
