### ISSUE TITLE
uploading file

### ISSUE THREAD

**Issue by phalconjohy** [ampproject/amphtml#17960]
Hi support,

want to upload a file on https://cdn.ampproject.org/v0/

**Comment by kevinkassimo** [comment]
Hi @phalconjohy 
Could you clarify what you mean? /v0/ is supposed to be where AMP extension scripts are served.

**Comment by phalconjohy** [comment]
Hi Kevin,

Actually I have to upload a file for amp purposes as this  domain is only
allowed.

Thanks for the response

On Sep 10, 2018 9:42 PM, "kevinkassimo" <notifications@github.com> wrote:

Hi @phalconjohy <https://github.com/phalconjohy>
Could you clarify what you mean? /v0/ is supposed to be where AMP extension
scripts are served.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ampproject/amphtml/issues/17960#issuecomment-419979788>,
or mute the thread

**Comment by aghassemi** [comment]
@phalconjohy Only components developed and approved for AMP can be served from that Url. I saw your PR, please see https://github.com/ampproject/amphtml/pull/17938#issuecomment-420339632 for instructions.
