### ISSUE TITLE
Error handling for amp-list

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1796]
Right now on error we just show the loading indicator. That isn't very awesome.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)

**Comment by dvoytenko** [comment]
For posterity, this issue has been fixed: loading indicator stops and fallback is displayed.

**Comment by adelinamart** [comment]
Awesome! 👍
