### ISSUE TITLE
Amp-analytics type="krux" issue

### ISSUE THREAD

**Issue by egianco73** [ampproject/amphtml#17976]
Hi,

we have a strange behaviour with amp-analytics type="krux".

Looking at the following URL:

https://roma.repubblica.it/cronaca/2018/09/11/news/mondo_di_mezzo_la_sentenza-206143440/amp/

as you can see, we are using the tag:

```
<amp-analytics type="krux" config="https://cdn.krxd.net/controltag/amp/JW5KTbNq.json">
<script type="application/json">
{
   "extraUrlParams":{  
      "page.pagetype":"dettaglio_content",
      "page.wt_logged_service":"repubblica.it",
      "user.wt_logged_user":"AUTHDATA(profile.hash_id)",
      "page.keywords":"mafia capitale;mondo di mezzo;procura generale di roma;articolo 416bis;salvatore buzzi;massimo carminati;luca tescaroli",
      "page.pubday":"11",
      "page.pubmonth":"09",
      "page.pubyear":"2018",
      "page.wt_map_tree":"\/repubblica\/cronache locali\/roma\/cronaca",
      "page.wt_mobile_type":"amp",
      "page.wt_sitetype":"mobile",
      "page.wt_map_tree1":"repubblica",
      "page.wt_map_tree2":"cronache locali",
      "page.wt_map_tree3":"roma",
      "page.wt_map_tree4":"cronaca"
   }
}
</script>
</amp-analytics>
```

Loading the page, looking at the console, we can see the following URL:

https://beacon.krxd.net/pixel.gif?&&page.pagetype=dettaglio_content&page.wt_logged_service=repubblica.it&user.wt_logged_user=&page.keywords=mafia%20capitale%3Bmondo%20di%20mezzo%3Bprocura%20generale%20di%20roma%3Barticolo%20416bis%3Bsalvatore%20buzzi%3Bmassimo%20carminati%3Bluca%20tescaroli&page.pubday=11&page.pubmonth=09&page.pubyear=2018&page.wt_map_tree=%2Frepubblica%2Fcronache%20locali%2Froma%2Fcronaca&page.wt_mobile_type=amp&page.wt_sitetype=mobile&page.wt_map_tree1=repubblica&page.wt_map_tree2=cronache%20locali&page.wt_map_tree3=roma&page.wt_map_tree4=cronaca

where we can see:

pixel.gif?&&page.pagetype=dettaglio_content

The parameter page.pagetype is passed with:

?&&

The problem we noticed.

Could you please check?

Best Regards,
Enzo Giancola

**Comment by kevinkassimo** [comment]
Hi @egianco73 .

From config loaded from https://cdn.krxd.net/controltag/amp/JW5KTbNq.json, it gives a `"pageview":"${pixelService}?${common}&${timing}"`, which then becomes `https://beacon.krxd.net/pixel.gif?${common}&${timing}` as pageview base url. It seems that there are no expansion option values provided for `common` and `timing`, resulting in them become `''` when expanding.

Further investigation /to @lannka

**Comment by kyle-wright** [comment]
@kevinkassimo @egianco73 @lannka @calebcordry krux vendor configuration appears to have been removed accidentally while doing cleanup googleanalytics-alpha: https://github.com/ampproject/amphtml/pull/16763/files#diff-43075fef96144a4f898edb8d18aae69aL1066

**Comment by kevinkassimo** [comment]
@kyle-wright Thanks for reporting! As an update, #18024 has been merged back to master

**Comment by lannka** [comment]
the fix is cherry-picked to prod: https://github.com/ampproject/amphtml/issues/18025
