### ISSUE TITLE
disabled not working anymore?

### ISSUE THREAD

**Issue by AcidRaZor** [ampproject/amphtml#17998]
hey guys, so here I am again, this time on my day off, get a phone call that the linked-dropdowns I did several months ago stopped working.

The last time this happened to navigateTo (which was fixed 48 hours later by you guys)

Here is the 2nd dropdown code:
```

<select [disabled]="!modelfilter.models"
			disabled        				
			id="mod"
			on="change:
			AMP.setState({		  
			modelselected: event.value,
			redirectTo: makeselected + '/' + rangeselected + '/' + event.value
			})">        
			<option value="">choose a model</option>
			
			{{#models.models}}<option value="{{url_segment}}">{{modelname}}</option>{{/models.models}}
			
		</select>
```

If modelfilter.models is not a null, i.e, set by the previous dropdown, it should enable this dropdown. The object definitely gets populated, as when I remove the initial "disabled", my dropdowns work. As a UX thing, we would have wanted the person to start with the first dropdown, to filter on the 2nd, and not confuse them by showing nothing in the filtered dropdown and have them try to select something.

**_Note, again, Im not struggling to make this work. This worked, went through UAT and QA and was pushed to live months ago by us._**

What changed in AMP where [disabled] doesn't work anymore?

**Comment by aghassemi** [comment]
@AcidRaZor https://ampbyexample.com/advanced/linked_dropdowns/ does the same and it is working for me. Do you mind sharing the AMP version number it is broken at and a repro sample to help us debug?

**Comment by AcidRaZor** [comment]
When I have time I'll do that. I'm running whatever AMP version you guys push to production as I have 0 control over which version I work with. Will try and attach reproducible code as well as it's actually 3 linked drop-downs.

**Comment by choumx** [comment]
Closing as stale. If this is still an issue, please share a reproducible example and we'll reopen. Thanks!
