### ISSUE TITLE
Demo Issue for Contributor Submit

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#18016]
Could we add a comment here to explain what is the `toolbarElements`?

https://github.com/ampproject/amphtml/blob/d3df64d07ae9e9e21a94d8339f3c2d0a9b7d4261/extensions/amp-sidebar/0.1/amp-sidebar.js#L126

**Comment by ampcontributorsummit2424** [comment]
I would like to claim this!

**Comment by techhtml** [comment]
Hello demo!

**Comment by torch2424** [comment]
Haha! I forgot to close this. Thank you! 😄
