### ISSUE TITLE
Submitting amp-form via action-xhr with empty input[type=file] fails in safari 11

### ISSUE THREAD

**Issue by gingerhead** [ampproject/amphtml#18022]
## What's the issue?

Submitting amp-form via action-xhr with empty input[type=file] fails in safari 11

Link to corresponding bug in Webkit:
https://bugs.webkit.org/show_bug.cgi?id=184490

## How do we reproduce the issue?

http://jsbin.com/tutevodeha/1/

1. Open http://jsbin.com/tutevodeha/1/ in Safari 11.1
2. Submit form without uploading file
3. Request fails after timeout

## What browsers are affected?

Safari 11, mobile Safari iOS 11

----------------------------------------------

As suggested in https://stackoverflow.com/questions/49614091/safari-11-1-ajax-xhr-form-submission-fails-when-inputtype-file-is-empty, possible workaround could be detecting and removing empty file input values from FormData before sending it to server

**Comment by cvializ** [comment]
Hi @gingerhead thanks for opening this issue! Since this is a Safari bug and not an AMP bug, I'll log this issue as a feature request to workaround the browser bug. We've prioritized it and we'll address it soon.
