### ISSUE TITLE
Validation issue

### ISSUE THREAD

**Issue by maxakagaret** [ampproject/amphtml#18020]
AMP Version 1536699515199
While using #development=1 argument in url, got error message "Custom JavaScript is not allowed." in browser console. Only js script, used in code, is `<script async src="https://cdn.ampproject.org/v0.js"></script>` (Code is from AMP tutorial). Checked in Firefox, Chrome, Opera.

**Comment by aghassemi** [comment]
@maxakagaret  Could you please let me know what tutorial and a link or content of the AMP page?
(you can also check validity of your page on (https://validator.ampproject.org/)

**Comment by maxakagaret** [comment]
Hello @aghassemi. I found the reason of issue. Validation error appears because my antivirus inject javascript in browser. When I turned off this option in antivirus, validation error disappeared.

**Comment by aghassemi** [comment]
Thanks for the update.
