### ISSUE TITLE
Create test to prevent accidental analytics config removal

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#18027]
To prevent incident #16763 #18025 from happening, we can add a test to make sure the vendor-request.json needs to be changed for any removal of a vendor.

**Comment by zhouyx** [comment]
Had #18028. But agreed #18034 is the eventual solution.

**Comment by lannka** [comment]
#18028 is still useful so that we force a clean up of the test file.

**Comment by zhouyx** [comment]
I really don't think the check is necessary to have after #18034.... #18028 makes our the test look mess even it's not clean already....

**Comment by lannka** [comment]
OK, as long as we do this in code review to make sure tests are cleaned up.
