### ISSUE TITLE
🌸Cherry pick request for 18035 into Canary (17970) 

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#18037]
GitHub issue your cherry pick is fixing:

Issue #18001

PR that you are requesting a cherry pick for:

PR #18035 

Release(s) you requesting this cherry pick into:

1809111831160

If you are requesting a cherry pick into a production release you will most likely need to cherry pick into canary as well, otherwise when the canary is pushed to production your fix will be lost. See the cherry pick documentation.)

Production Release? NO, too dangerous?

Canary release? YES, Release Issue #17970 

Why does this issue meet the cherry pick criteria? Be specific.

> break existing AMP web pages in a significant way

This bug makes it so that publishers cannot use the version of the extension that they want, and must use deprecated extension versions.  For `amp-story` specifically, it also means that unwhitelisted publishers have no way of preventing users from getting broken experiences when visiting their page, even though the publisher has done everything right.

/cc @vinaymahag @gmajoulet @Enriqe

**Comment by cramforce** [comment]
Approved :)

**Comment by cathyxz** [comment]
This is now in progress with build https://travis-ci.org/ampproject/amphtml/builds/428827335 and tracked via #17970.

**Comment by cathyxz** [comment]
This was completed in release [1809142227020](https://github.com/ampproject/amphtml/releases).
