### ISSUE TITLE
[amp-image-slider] Use the semantic cursor for the dragging bar.

### ISSUE THREAD

**Issue by sparhami** [ampproject/amphtml#18056]
`<amp-image-slider>` should use `cursor: col-resize` as an extra affordance that the bar is draggable. Even though you can actually start dragging anywhere, we should still show the cursor when the user is on top of the bar (perhaps with some padding on the left/right).

**Comment by nainar** [comment]
cc @spacedino

**Comment by aghassemi** [comment]
@sparhami Great GFI. Do you mind formatting the description to match the [template](https://github.com/ampproject/amphtml/issues/7720)?

**Comment by techhtml** [comment]
Close this please :)

**Comment by sparhami** [comment]
> Close this please :)

Sure. For future reference, if you do "Fixes #18056" or "Closes #18056" in your Github comment for a pull request, it will automatically close the issue once your PR lands.

**Comment by techhtml** [comment]
@spacedino Oh! Thanks :)
