### ISSUE TITLE
Validator overly sensitive to whitespace in `rel` attributes

### ISSUE THREAD

**Issue by Gregable** [ampproject/amphtml#18059]
Follow up from #18030, the AMP validator considers:

`<a rel="attachment noopener noreferrer">`

Valid, but considers:

`<a rel="attachment  noopener noreferrer">`

Invalid. The difference, which isn't visible in markdown AFAICT, is multiple spaces between `attachment` and `noopener`.

This isn't a _big_ deal, but does seem surprising and hard to debug for a publisher.

**Comment by twifkak** [comment]
(fixed by d97c0d93 of #23802)
