### ISSUE TITLE
body CSS constraints caused pixel imperfection for some inabox ads

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#18065]
**Issue description**
Open [this page](http://native-ads-preview.weebly.com/scaledplacement.html) to reproduce the issue.
Toggle the following CSS to see the difference:

1)
```
body, html {
  height: auto!important;
}
```

2)
```
html.i-amphtml-inabox>body {
  position: initial!important;
}
```

**Proposed solution**
CSS 1) was introduced to fix #2187.
This protection might not be needed for embeds. we can loosen the body "height" constraint to only 
```
html.i-amphtml-standalone>body, html.i-amphtml-standalone {
  height: auto!important;
}
``` 

For 2), @dvoytenko I saw the line was added as part of the visibility refactoring work. Do you recall why inabox is overriding this to `position: initial`, versus regular AMP having it `position: relative`.

b/115342240

**Comment by dvoytenko** [comment]
I believe the regular ampdoc would have `position:relative` in order to be able to offset header from the viewer, which is done by padding. To ensure that `position:absolute` elements are correctly position, `body` must have `position:relative`. Since inabox does not have the same needs, I believe, this property was simply reset back to initial value.

**Comment by lannka** [comment]
> this property was simply reset back to initial value.

If that is the case, we should reduce the scope of the regular AMP's `body {position:relative}`

**Comment by dvoytenko** [comment]
@lannka 

> If that is the case, we should reduce the scope of the regular AMP's body {position:relative}

Sorry, not sure what you mean by this? How do we reduce the scope of a `body` tag?

**Comment by lannka** [comment]
I meant to make the the CSS selector more specific, so it does not apply to inabox body tag.

**Comment by dvoytenko** [comment]
@lannka that would make sense, just need to be done carefully. I don't think this fully addresses the initial question: can the `height` be updated as well. And whether it should be...

**Comment by torch2424** [comment]
After reading through the context of issues and PRs leading up to this, it seems that, in my opinion, creating selectors for inabox vs. regualr amp documents should be fine.

Restricting the height makes sense for our standard amp documents, but inabox is restrained by the iframe. The parent document has control over the iframe is displayed, and the content inside the iframe tends to take up that space.

I also feel that it is important to fix these pixel imperfections, as I am sure it can bother some users.

**Comment by torch2424** [comment]
Discussed offline with @lannka :

Solution is to not override the existing CSS with more CSS, but to reduce the scope of the existing CSS. The `position: relative` causes the bug on inabox pages, thus making a better selector to not include inabox would solve the issue.
