### ISSUE TITLE
Responsive amp-img with animations rendering incorrectly in an amp-story

### ISSUE THREAD

**Issue by Orevarc** [ampproject/amphtml#18089]
## What's the issue?

Intermittently, when trying to render an animated `<amp-img>` with `layout="responsive"` inside an `<amp-story>`, the image will not fill page and instead render half cut off at the top of the page and then animate from there. 

## How do we reproduce the issue?

1. Go to: https://s3.us-east-2.amazonaws.com/bbytes/animation_bug.html. I have just copied the pan-left animation example and changed the layout from `fixed` to `responsive`
2. Force refresh the page, ignoring the cache (`cmd + shift + r` on OS X). I sometimes need to try this multiple times for the issue to appear.
3. The page should render like the image below:

![image](https://user-images.githubusercontent.com/5480289/45642570-8e43eb80-ba86-11e8-9d8f-79df9891e2aa.png)

## What browsers are affected?
 I've had the issue appear on Chrome quite frequently. I have only been able to reproduce it one time on Firefox:
Desktop Chrome:  69.0.3497.92, 68.0.3440.106
Desktop Firefox: 61.0.2

## Which AMP version is affected?
Version 1536865149181
I do not think this is a new issue as I have noticed it for a little while now. 

From looking at the transform styles applied to the image when it's in a broken state vs when it is not, it looks like AMP is incorrectly calculating these values though not sure if that is where the issue lies.

**Comment by Enriqe** [comment]
I can take this one.

**Comment by Enriqe** [comment]
This was fixed in #18244
