### ISSUE TITLE
amp-instagram layout issues

### ISSUE THREAD

**Issue by alvin-milton** [ampproject/amphtml#1809]
CSS related:

This style declaration:
```
amp-instagram {
    padding: 48px 8px!important;
}
```
causes the amp-instagram tag to have unnecessary padding.

![image](https://cloud.githubusercontent.com/assets/13681857/12853138/72d69f0e-cc00-11e5-86b0-666cc9bd7f69.png)

Also the rendered child iframe has a class `.-amp-fill-content` that cuts off the content for me where if I remove it via dev tools, it renders properly.

![image](https://cloud.githubusercontent.com/assets/13681857/12853194/b8d6378a-cc00-11e5-9017-0aea46fd279b.png)

**Comment by cramforce** [comment]
Could you paste your markup? Ideally on jsbin.com or similar.

**Comment by alvin-milton** [comment]
Not sure what happened but this is resolved.
Will open this back if I see the issue resurface.
