### ISSUE TITLE
amp-video-iframe : Allow custom analytics events

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#18138]
`amp-video-iframe` should support all of AMP's predefined video analytics events but additionally should allow publishers to do custom events that is very specific to their use-case/player. (For example  'related video clicked')

/to @alanorozco 
/cc @sebastianbenz @jeffjose

**Comment by aghassemi** [comment]
@alanorozco was chatting with a developer who was very interested in this feature. Let's aim for having it in the launch.

**Comment by alanorozco** [comment]
Partial in #18869. Waiting for Github to recover to send for review.

**Comment by jeffjose** [comment]
@alanorozco I see #18869 has been merged. Can we close this one? or are there pending tasks?

**Comment by alanorozco** [comment]
Whoops, forgot to close, thanks!
