### ISSUE TITLE
amp-instagram does not support captions

### ISSUE THREAD

**Issue by asap** [ampproject/amphtml#1814]
Is there a plan to ever implement captions?

https://github.com/ampproject/amphtml/blob/master/extensions/amp-instagram/0.1/amp-instagram.js#L19

**Comment by cramforce** [comment]
I'd rather not, because it makes the embed size unpredictable.

But if people want it enough we could.

**Comment by adelinamart** [comment]
@ericlindley-g it seems this is something to consider dropping.

**Comment by cramforce** [comment]
This was implemented recently!
