### ISSUE TITLE
Preemptively stop a running/pending Travis builds when a new commit is pushed to a PR

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#18155]
Every commit for a PR creates a new Travis build. If the contributor pushes a new commit to a PR while there are still running/pending Travis builds/shards, those will continue to be queues and "hold hostage" a VM that is no longer going to provide any valuable feedback to the build. We should consider stopping the previous commits' builds in this case

(Related to #18156)

**Comment by rsimha** [comment]
There is a way to cancel a build using the command line: https://blog.travis-ci.com/2013-08-21-abort-mission-cancel-running-builds

The missing ingredient is to figure out which of the running builds are associated with the same PR.

**Comment by rsimha** [comment]
There's an open FR on Travis for exactly this: https://github.com/travis-ci/travis-ci/issues/8712

**Comment by rsimha** [comment]
Update: Still waiting on Travis FR.

**Comment by rsimha** [comment]
Closing this as infeasible until Travis fixes https://github.com/travis-ci/travis-ci/issues/8712 (looking unlikely)

https://docs.travis-ci.com/user/customizing-the-build/#building-only-the-latest-commit
