### ISSUE TITLE
Preemptively stop a running/pending Travis builds when the other shards fails

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#18156]
Every PR creates a Travis build with two shards, one for unit tests and one for integration tests. To release Travis VMs faster, we can consider stopping one shard if the other in the same build already failed

(Related to #18155)

**Comment by danielrozenberg** [comment]
Personally I'm not in favour of doing this: the feedback I get from the two shards is different. My PR can fail on a unit test, but succeed on all integration tests. Or it could fail on a unit test, and also fail on an integration test.

If we stop the integration shard before it gives me feedback, I might waste time fixing the failing unit test and starting 2 new VMs, and then later fail the integration test without having realized earlier that there was an issue there too.

Thoughts?

**Comment by rsimha** [comment]
There is a way to cancel a build using the command line: https://blog.travis-ci.com/2013-08-21-abort-mission-cancel-running-builds.

@choumx @erwinmombay @jridgewell for your thoughts on https://github.com/ampproject/amphtml/issues/18156#issuecomment-422546154

**Comment by choumx** [comment]
SGTM

**Comment by erwinmombay** [comment]
👍

**Comment by rsimha** [comment]
In that case, there's nothing to do here.

**Comment by rsimha** [comment]
This was already discussed in #16918. Travis lacks native support for this.
