### ISSUE TITLE
amp-pinterest sizing has a hard coded size instead of being responsive

### ISSUE THREAD

**Issue by asap** [ampproject/amphtml#1816]
When trying to embed this Pinterest embed:

https://www.pinterest.com/pin/246572148327527311/

Image is scaled down 

```
<amp-pinterest
  data-do="embedPin"
  data-url="https://www.pinterest.com/pin/246572148327527311/"
  height="992"
  layout="responsive"
  width="396"></amp-pinterest>
```

Image is scaled down to 237px wide, but the embed's area is 396px wide, creating a lot of white space.

**Comment by derekpeterson** [comment]
I don't know if this belongs on this issue, but I'm also having problems with the Pinterest embed widget's responsive layout. The image doesn't scale to the full width, and the `overflow: hidden !important` hides the embed box-shadow on the right side. I created [this pen](http://codepen.io/derekpeterson/pen/jqXNNr) to demonstrate the issue. Let me know if you'd like more details or if this belongs in its own issue.

**Comment by dvoytenko** [comment]
/to @rudygalfi to reach out to Pinterest to consult.

**Comment by rudygalfi** [comment]
cc @jparise

**Comment by jparise** [comment]
Thanks for the report! I'll triage on our end and update this issue accordingly.

**Comment by zackargyle** [comment]
@asap If you want to use the larger image you'll need to specific the `data-width="medium"` attribute. The images themselves are not responsive (currently), but we'll look into making the Pin widget more inline with the responsive nature of our non-amp widget.

**Comment by adrianhaurat** [comment]
Having same issue as @derekpeterson. Was there a solution or workaround?

**Comment by christianvuerings** [comment]
@asap @adrianhaurat we made a fix for this at #7320

**Comment by cyrusssschen** [comment]
Has this one being fixed? 
It seems the issue still remains in the example posted by @derekpeterson

**Comment by hirethisdeveloper** [comment]
We're also seeing the issue still happening as well. 
<img width="269" alt="2020-05-21_1009" src="https://user-images.githubusercontent.com/684661/82567388-4b83c200-9b4b-11ea-887f-9c19eb7cc71a.png">
