### ISSUE TITLE
amp form action-xhr does not work in IE 11

### ISSUE THREAD

**Issue by jasonconway-williams** [ampproject/amphtml#18183]
## What's the issue?

Amp form action-xhr does not work in Internet Explorer

## How do we reproduce the issue?

1. Navigate to the https://ampbyexample.com/components/amp-form/ page in Internet Explorer 11 (11.0.9600.19002).
2. Scroll down to the "Form Submission with Page Update" section.
3.  Insert valid values into the inputs and click "Subscribe".

The form does not submit.

## What browsers are affected?

 Internet Explorer 11 (11.0.9600.19002).

## Which AMP version is affected?

 Version 1809142227020

**Comment by mcmd** [comment]
I can't reproduce, the form is sent for me:

<img width="727" alt="form-submission-with-page-update-ie11-success" src="https://user-images.githubusercontent.com/868584/46102032-4418e380-c1c5-11e8-9009-b1df3f7bac21.PNG">

@jasonconway-williams: I think that what you might be experiencing is #18398, could you please doublecheck?

cc @camelburrito , because of PR #9053 , which fixed this issue

**Comment by cvializ** [comment]
Thanks for reporting @jasonconway-williams! And thanks for your suggestion @mcmd. I'll try to reproduce this myself soon and give an update if I discover anything

**Comment by cvializ** [comment]
I am not able to reproduce. @jasonconway-williams are you still able to repro, or can you please provide any more details that will help me reproduce?

**Comment by cvializ** [comment]
@jasonconway-williams I am unable to reproduce. As @mcmd mentioned there is a bug fix in progress for the validation bubbles to provide error messages, but I am able to successfully submit the form in IE11. Are you still able to reproduce, or are you able to provide any additional steps to help us reproduce?

**Comment by jasonconway-williams** [comment]
@cvializ I can confirm that the amp by example form does work in IE11 and it does seem to be a problem with the validation message not being displayed when an invalid value has been inserted into the email field. The fields don't seem to display placeholders in IE11 specifying that the fields are for name and email. 

The issue that I am having is that I am experiencing a problem with the form submit button where IE11 submits to the current page url. You can see an example of this at https://www.travelsupermarket.com/holiday-landing-staging/en-gb/holidays/amp/spain/balearic-islands/ibiza.html. When you hover over the Search button, IE11 displays the current url at the bottom of the window. Clicking the search button doesn't seem to do anything.

**Comment by cvializ** [comment]
I was able to reproduce in that document. It looks like the autosuggest `amp-list` has a `<template>` with an `<amp-selector>`, and somehow the elements inside the `<template>` are being treated like real elements and not just template content.

<img width="442" alt="screen shot 2018-10-02 at 12 00 13" src="https://user-images.githubusercontent.com/2363700/46361290-3509b980-c63b-11e8-96ad-fc04131bfe52.png">
<img width="536" alt="screen shot 2018-10-02 at 11 59 06" src="https://user-images.githubusercontent.com/2363700/46361286-333ff600-c63b-11e8-9e2d-707a64d52c49.png">
