### ISSUE TITLE
Intent to Implement: amp-apester-media selectively show display ad

### ISSUE THREAD

**Issue by OmriKeret** [ampproject/amphtml#18180]
## What's the issue?
Allowing amp-apester-media to bring the publisher's unit monetisation setting (set using Apester CMS) and selectively show a display ad below the amp-apester-media unit.

## Proposed design

1. Use the current XHR request Apester servers to receive the monetisation settings as we don't want to create another request that might effect the Apester Media load time.

2. Use amp-ad component in order to show the display ad below our unit

3. Use a place holder for the display ad with the same dimensions (so the content won't reflow when we receive the display ad response)

**Comment by OmriKeret** [comment]
@lannka

**Comment by lannka** [comment]
@OmriKeret regarding to 3, keep in mind it will be a bit tricky to support full width experience (layout=responsive). 

Other than that, I think it's straight forward, and a reasonable addition to the existing extension.
