### ISSUE TITLE
Error: The operation was aborted.

### ISSUE THREAD

**Issue by adelinamart** [ampproject/amphtml#18208]
@choumx there's this production error if you cna have a look:

Error: The operation was aborted.
at (the-operation-was-aborted.js:1)

https://pantheon.corp.google.com/errors/CNyH5IiB-Ij_xAE?service=default-cdn-1p&time=P1D&project=amp-error-reporting

**Comment by erwinmombay** [comment]
the-operation-was-aborted.js isn't an amp script, so this isn't our issue anymore.

**Comment by choumx** [comment]
UA looks like Mobile Safari UIWebview with a high number of reports from spammy sites. Going to silence this on our reporter.
