### ISSUE TITLE
Cannot read property 'getComputedStyle' of null at install$$module$src$polyfills$math_sign 

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#18203]
```Error: Cannot read property 'getComputedStyle' of null at install$$module$src$polyfills$math_sign (https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/polyfills/math-sign.js:41:7) at https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/service/fixed-layer.js:734:16 at matches (https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/service/fixed-layer.js:830:22) at documentElement (https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/service/viewport/viewport-binding-natural.js:146:4) at ?.prototype (https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/service/viewport/viewport-binding-natural.js:172:2) at ?.prototype (https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/service/viewport/viewport-binding-natural.js:172:2) at onScroll (https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/service/viewport/viewport-binding-natural.js:106:2) at https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/service/fixed-layer.js:460:24 at isAlwaysFixed (https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/base-element.js:304:2) at right (https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/service/resources-impl.js:1289:30)```

```Error: null is not an object (evaluating 'a.getComputedStyle') at install$$module$src$polyfills$math_sign (https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/polyfills/math-sign.js:41:7) at https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/service/fixed-layer.js:727:27 at matcher (https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/service/fixed-layer.js:830:12) at classList (https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/service/viewport/viewport-binding-natural.js:146:4) at ?.prototype (https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/service/viewport/viewport-binding-natural.js:172:2) at ?.prototype (https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/service/viewport/viewport-binding-natural.js:172:2) at ?.prototype (https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/service/viewport/viewport-binding-natural.js:172:2) at onScroll (https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/service/viewport/viewport-binding-natural.js:106:2) at https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/service/fixed-layer.js:460:24 at https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/base-element.js:305:4 at https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/service/resources-impl.js:1294:10 at https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/service/history-impl.js:503:41 at onVisibilityChanged (https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/service/resources-impl.js:250:4) at ?.prototype (https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/service/history-impl.js:717:2) at ?.prototype (https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/service/url-replacements-impl.js:1149:2) at ?.prototype (https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/service/url-replacements-impl.js:1149:2) at https://raw.githubusercontent.com/ampproject/amphtml/1809181624140/src/service/resources-impl.js:2166:50```

cc @adelinamart

**Comment by erwinmombay** [comment]
cc @jridgewell for visibility

**Comment by jridgewell** [comment]
The unminified stack traces are never correct....

**Comment by adelinamart** [comment]
Was just looking at the spike. @erwinmombay assigning it to you, but feel free to reassign. we need to check it out before pushing this version to production next week.

**Comment by jridgewell** [comment]
And confirmed:

```
d.ownerDocument
// => #document

d.ownerDocument.defaultView
// => null

d.ownerDocument.documentElement
// => <html amp4ads class=​"i-amphtml-fie">​…​​</html>​

**Comment by adelinamart** [comment]
I still see the error the new canary after the cherry pick. @jridgewell

**Comment by jridgewell** [comment]
Should be fixed now by https://github.com/ampproject/amphtml/pull/18344
