### ISSUE TITLE
Error: Unexpected token ;

### ISSUE THREAD

**Issue by adelinamart** [ampproject/amphtml#18210]
@jridgewell can you have a look at this production error: 

Error: Unexpected token ;
at (unexpected-token.js:1)

https://pantheon.corp.google.com/errors/CM7U_K-nvc-BFg?service=default-cdn-1p&time=P1D&project=amp-error-reporting

**Comment by rcebulko** [comment]
Bumping this as a top-ten most frequent error. Do you have any guess about what the cause of this might be?

**Comment by rcebulko** [comment]
Similar to https://github.com/ampproject/amphtml/issues/28077 . All the referrers for this error seem to be NSFW websites. We're not able to get any additional debug info, and it's extremely unlikely this is an AMP problem, so I'm muting this in Error Reporting.
