### ISSUE TITLE
Viewability not firing if ad is visible on page load

### ISSUE THREAD

**Issue by Oblium** [ampproject/amphtml#1821]
I'm trying to implement viewability for ads and I've noticed two different behaviours depending on ad position on page load.

If the ad is outside the viewport and then I scroll to bring it inside of it, observeIntersection fires correctly on each scroll. 
If the ad is partially or totally in the viewport and then I scroll, observeIntersection fires only on page load, I have to bring the ad outside the viewport (or switching between tabs) to make observeIntersection firing on each scroll.

Have you encountered the same problem?

**Comment by cramforce** [comment]
Was able to reproduce. Will fix.
