### ISSUE TITLE
Redo viewability tests

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1822]
- Stops relying on manual firing of observer
- No longer manually create intersection observer (should instead entirely simulate postMessage including putting the iframe/ad into the right state which is currently not tested.
- The intersection height tests in amp-iframe seem broken

CC @sriramkrish85

**Comment by cramforce** [comment]
@muxin You kind of did this, right?

**Comment by muxin** [comment]
@cramforce I don't understand the issue. Mind elaborating it?

**Comment by sriramkrish85** [comment]
@muxin i can explain tomorrow. (in case malte does not respond)

**Comment by jasti** [comment]
@muxin, @camelburrito - is this being worked on or can be closed? Cleaning up for new sprint process.
