### ISSUE TITLE
Failed to process trigger "ad-request-start"

### ISSUE THREAD

**Issue by adelinamart** [ampproject/amphtml#18231]
@lannka please look at this error asap. It started with the current production

Error: AmpAnalytics <unknown id> Failed to process trigger "ad-request-start": null is not an object (evaluating 'a.na.addTrigger')
at addTrigger (https://raw.githubusercontent.com/ampproject/amphtml/1809142227020/extensions/amp-analytics/0.1/amp-analytics.js:388)
at addTriggerNoInline_ (https://raw.githubusercontent.com/ampproject/amphtml/1809142227020/extensions/amp-analytics/0.1/amp-analytics.js:314)

Version	
011809142227020 
https://pantheon.corp.google.com/errors/CPiQyKiMp7qR1gE?service=default-cdn-1p&time=P1D&project=amp-error-reporting

Error: AmpAnalytics <unknown id> Failed to process trigger "ad-render-start": a.na is null
at analyticsGroup_ (https://raw.githubusercontent.com/ampproject/amphtml/1809142227020/extensions/amp-analytics/0.1/amp-analytics.js:388)
at addTriggerNoInline_ (https://raw.githubusercontent.com/ampproject/amphtml/1809142227020/extensions/amp-analytics/0.1/amp-analytics.js:314)

https://pantheon.corp.google.com/errors/CLehgcix6Y60GA?service&time=P1D&filter=text:Failed%20to%20process%20trigger%20%22ad-request-start%22&project=amp-error-reporting

**Comment by lannka** [comment]
@calebcordry can you please take a look? It is from the AMP story analytics triggers.

**Comment by calebcordry** [comment]
Looking now.

**Comment by calebcordry** [comment]
Upon further investigation it seems like this error is coming from https://github.com/ampproject/amphtml/blob/ec06c78ce6c61bd9e33fafd08964f6fb12284d7d/ads/google/a4a/utils.js#L542-L546

Tagging a few people that were involved in the original PR @warrengm @keithwrightbos @glevitzky 

Seems like the frequency has increased a bit recently. Bumping to p1 for now. The a4a team will be able to prioritize correctly.

**Comment by lannka** [comment]
It failed at [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/amp-analytics.js#L340) that `this.analyticsGroup_` is null.

@zhouyx could you take a look if this is something to do with extension analytics.

**Comment by zhouyx** [comment]
I've definitely seen the errors before. The reason is mostly because a race condition between the analytics initialization and parent element got remove from the page. We can verify it by introducing a new param, this.hasDetached_ and check on that before proceeding. Once we can verify that's the root cause, we can then remove the new param and simply check the existence of analytics group. 

One thing I don't understand is why is related to story ad? @lannka Could you explain?
