### ISSUE TITLE
Tealium - Intent to implement for AMP Analytics

### ISSUE THREAD

**Issue by tygavin** [ampproject/amphtml#18259]
This issue created following the instructions as documented here:
https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#contributing-features

## A high-level description of the feature.

Add support for Tealium Collect as a built-in AMP Analytics component.

## A description of the API you plan to create.

Tealium provides server-side data integrations for events received on the "collect.tealiumiq.com/event" endpoint.

## Details on any data collection or tracking that the feature might perform.

Data Collection will be similar to analytics solutions such as Google Analytics.

## A prototype or mockup (for example, an image, a GIF, or a link to a demo).

Documentation:
https://community.tealiumiq.com/t5/Universal-Data-Hub/Tealium-Collect-HTTP-API/ta-p/16893

Sample GET request:
https://collect.tealiumiq.com/event?tealium_account={ACCOUNT}&tealium_profile={PROFILE}&tealium_datasource={DATASOURCE}&tealium_visitor_id={VISITOR_ID}&tealium_event=page_view&page_name=my_article_1

**Comment by lannka** [comment]
@tygavin thanks for filing this. Make sure you look at the [integration guidelines](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/integrating-analytics.md) before you start.

**Comment by tygavin** [comment]
https://github.com/ampproject/amphtml/pull/18366

**Comment by tygavin** [comment]
Tealium Collect is added.  I'm guessing this should be closed.
