### ISSUE TITLE
Invalid key presence check in amp-consent

### ISSUE THREAD

**Issue by shimonenator** [ampproject/amphtml#18261]
`amp-consent` configured with `checkConsentHref` throws the following error when `promptIfUnknown` is set to `false`:

> log.js:187 Expecting promptIfUnknown from checkConsentHref when promptIfUnknownForGeoGroup is not specified

I believe the check in the code should be `!remoteConfigResponse.hasOwnProperty('promptIfUnknown')` instead of `!remoteConfigResponse['promptIfUnknown']`:

https://github.com/ampproject/amphtml/blob/eb5e7417c8b1492bee752fd30eac0c9980b8b96d/extensions/amp-consent/0.1/amp-consent.js#L387

**Comment by shimonenator** [comment]
cc @zhouyx seems like this issue was introduced in #17991

**Comment by zhouyx** [comment]
Ahhh! @shimonenator Thank you for looking into the code. I've created #18264 to fix it. 

Fortunately, in this case, the fallback value is `false`, which lead the correct behavior.

**Comment by shimonenator** [comment]
Thank you @zhouyx for a quick fix!
