### ISSUE TITLE
In Spanish, the word "Twitter" should not be translated.

### ISSUE THREAD

**Issue by opusdei** [ampproject/amphtml#18277]
In Spanish, the word "Twitter" should not be translated. In these two files is translated "Twitter" by "Gorjeo", which sounds very strange.

https://github.com/ampproject/amphtml/blob/4eb87bbbe956a6ee9f393c6df8b3318fd0a470ad/extensions/amp-story/1.0/_locales/es.js

https://github.com/ampproject/amphtml/blob/4eb87bbbe956a6ee9f393c6df8b3318fd0a470ad/extensions/amp-story/1.0/_locales/es-419.js

INCORRECT
```
  [LocalizedStringId.AMP_STORY_SHARING_PROVIDER_NAME_TWITTER]: {
    string: 'Gorjeo',
},
```

CORRECT
```
  [LocalizedStringId.AMP_STORY_SHARING_PROVIDER_NAME_TWITTER]: {
    string: 'Twitter',
},
```

**Comment by newmuis** [comment]
Looks like @mcmd will be taking this on 😄

**Comment by opusdei** [comment]
Thanks. Fixed in amp-release 10-10-2018.
