### ISSUE TITLE
amp-form: "clear" action resets button "disabled" state

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#18285]
If the button has a `[disabled]` binding, it can become out of sync.

Looks like this was added a long time ago to prevent duplicate form submissions: https://github.com/ampproject/amphtml/pull/3582. Perhaps we can change that to a programmatic check to avoid mucking with the disabled attribute. 

`b/115780963`

**Comment by aghassemi** [comment]
setting to P2 /cc @cvializ
