### ISSUE TITLE
CustomEventReporter API not auto-loading amp-analytics extension.

### ISSUE THREAD

**Issue by slocka** [ampproject/amphtml#18282]
## What's the issue?

When trying to implement analytics for `amp-skimlinks` using the [customeventreporter-api](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-components-analytics.md#customeventreporter-api)  (see https://github.com/ampproject/amphtml/pull/17907) the `amp-analytics` extension is not automatically loaded on the page.

@lannka  mentioned in the comments of [amp-skimlinks design doc](https://docs.google.com/document/d/10qEju2E3_c84W3ZPMjz8yGvMfFWwzSefnbMLPcC-vRs): `And it's a mis-conception that pub needs to put amp-analytics extension on the page. In fact, it will be automatically inserted if there isn't one one the page.` 

I would therefore expect `amp-analytics` extension to be automatically loaded in the page if not already present.

## How do we reproduce the issue?
In a simple amp page without the `amp-analytics` javascript, send a tracking request from an amp extension using the CustomEventReporter API as described [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-components-analytics.md#customeventreporter-api)

When the `CustomEventReporterBuilder.build` function is called an `Assertion failed` error is showing in the console and the request is never sent.

Note: After trying to debug I noticed that the `CustomEventReporter` [constructor function](https://github.com/ampproject/amphtml/blob/master/src/extension-analytics.js#L102) calls 
`insertAnalyticsElement(...)` with a third argument ("loadAnalytics") set to `false`.  Setting this 3rd argument to `true` fixes the issue. Any reason why "loadAnalytics" is forced to `false` in the context of the CustomEventReporter API?

## What browsers are affected?
All

## Which AMP version is affected?
Not sure, probably all.

**Comment by zhouyx** [comment]
Of course. I can make the change. @slocka However I am on a trip and may not be able to do so in the upcoming week. To unblock you, you can go ahead and set the value to `true` for now, and I'll remove that variable later. Thank you
