### ISSUE TITLE
amp-carousel: Control hints broken on mobile

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#18284]
Previous/next controls are not "hinted" for carousels on mobile.

Looks like `hintControls()` is being called correctly and the CSS class is added as expected, but the controls themselves are positioned incorrectly, maybe because they're hidden on load.

Reproducible on desktop Chrome/Safari with device emulation: https://ampbyexample.com/components/amp-carousel/

`b/116233759`

**Comment by choumx** [comment]
I'm not sure this is related to a canary experiment. I can reproduce this on prod (1809142227020).

**Comment by choumx** [comment]
@nainar Can you provide more context on the fix? I also don't see any code guarding the "amp-carousel-new-arrows" experiment.

**Comment by nainar** [comment]
#18303 and #18287 remove all code regarding new arrows for AMP Carousel. 

I can't seem to repro the issue on prod on master (can on prod). 

Attached are screenshots taken on Chrome on Android:
![screenshot_20180927-174029](https://user-images.githubusercontent.com/7919520/46181813-c57f7d00-c27c-11e8-8160-604d5843d48f.png)
![screenshot_20180927-174035](https://user-images.githubusercontent.com/7919520/46181815-c6181380-c27c-11e8-94ce-40892c77944f.png)

**Comment by aghassemi** [comment]
This seems to be resolved now on prod and canary. I can't repro anymore @choumx and @nainar could you please verify and close if all good?

**Comment by nainar** [comment]
I have tested on the following: 
iOS - Chrome/Safari
Android - Chrome/ Firefox.
I can't repro the issue. 

@choumx feel free to open if needed?

**Comment by choumx** [comment]
Weird, thanks for verifying!
