### ISSUE TITLE
Introduce a visual indicator that there's content to be lazy loaded

### ISSUE THREAD

**Issue by MadaraUchiha** [ampproject/amphtml#1829]
In the case of `<amp-ad>` and `<amp-embed>`, (and probably most other lazy-loaded elements) it's not possible to provide some sort of visual indication that there's something that's supposed to go into the space. 

In the case of bad data connectivity or signal, ads, embeds, images, etc can take a longer time to load, and since they're loaded lazily (and rightly so), it could make the perceived performance of the page worse (because there's a blank, potentially large, square where content is supposed to be, and there's no indication that something should be there).

I've read the argument that at least in the case of `amp-img` one may elect to use a `background-color` but that doesn't hold when transparent `.png` (or :fearful: `.gif`) images are in play. As it would affect how those images look after they're loaded and rendered.

I'm proposing to think about some sort of visual indicator (I'm thinking about a simple spinner in a data URI, but you guys are probably smarter than I am) that would tell the user that something is, in fact, queued to be rendered in the blank square he's looking at. 

Maybe something like
```html
<amp-embed
  <!-- snip -->
  hide-spinner <!-- enabled by default? TBD -->
/>
```

Or even
```html
<amp-embed <!-- attributes --> >
  <amp-spinner />
</amp-embed>
```

What do you think? Is this worth thinking about? Are there plans for this or was it ever discusseed before (I didn't find anything from a search).

----

Is this option available already under a different name? Looking at the docs/examples I couldn't find anything.

**Comment by MadaraUchiha** [comment]
cc @nitzanvolman @effie You May Like.

**Comment by Effie** [comment]
Dor,

You know amp-embed can contain

 <div placeholder>Have a great day!</div>

 <div fallback>Have a great day!</div>


On Sun, Feb 7, 2016 at 10:53 PM, Madara Uchiha <notifications@github.com>
wrote:

> cc @nitzanvolman <https://github.com/nitzanvolman> @effie
> <https://github.com/effie> You May Like.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampproject/amphtml/issues/1829#issuecomment-181114502>
> .
>



-- 


“Weeks of coding can save you hours of planning.”
______________
*Effie Nadiv*
UI Ingenjör
Taboola
Kontor: +972-3-6966966
Mobil: +972 52 253167
effie.n@taboola.com

**Comment by dvoytenko** [comment]
There's a spinner, but it's disabled for `amp-embed`. I'll enable it. However, `amp-ad` is disabled and I don't think we had any plans to enable it.

**Comment by nitzanvolman** [comment]
thanks @dvoytenko !
