### ISSUE TITLE
Story-navigation-help-overlay (Bug in Spanish, French and Italian; and Feature request for all languages)

### ISSUE THREAD

**Issue by opusdei** [ampproject/amphtml#18349]
(From https://github.com/ampproject/amphtml/pull/18278/files/f1925eaec3376f4df58f8066496de958092b08b4#diff-b85c8cabea68995ec44cdcf9d1e2f88c)

(Suggestion from @mcmd, cc @gmajoulet and @newmuis) 

I think it would be preferable to simply translate "Toque" (Tap) in both cases, because "Toque Volver" (Tap Back) does not fit on some devices (see capture of an iPhone 6/7/8 in zoom mode, which shares viewport size with iPhone 5SE, 320 x 460 px).

<img width="320" alt="image-1" src="https://user-images.githubusercontent.com/5907868/45995586-ef784a00-c098-11e8-8db5-147628d61479.png">

Also in Italian (iPhone 5):

![imagen](https://user-images.githubusercontent.com/5907868/46024385-faf26200-c0e6-11e8-9933-dc8ba73d800d.png)

French (iPhone 6/7/8):

![imagen](https://user-images.githubusercontent.com/5907868/46024488-312fe180-c0e7-11e8-96cd-81bfa5a6db01.png)

The arrows above show the direction and you can save the word "Volver" (Back) or "Siguiente" (Next). I think these messages are displayed when the user makes the "swipe" gesture, and we just want to say: "do not swipe, touch" and the "back" and "forward" are shown by arrows icons.

The word "Toque" (Tap) has the advantage that it is a verb, but also a noun: and it can also be understood as "dar un toque aquí" (give a touch here).

![imagen](https://user-images.githubusercontent.com/5907868/46012176-a3dd9480-c0c8-11e8-805d-925335df079d.png)

Alternatively, if you want to keep the two words, you would give `width: 25%;` or `width: 25vw;`  to the element ".i-amphtml-story-hint-placeholder" in the file "/extensions/amp-story/1.0/amp-story-hint.css" (since being positioned in an absolute way, it escapes specifically the flex container of the left sidebar that measures a quarter of the width and that is where that text should "fit"). 

.i-amphtml-story-hint-placeholder {
(...)
width: 25%;
}
![imagen](https://user-images.githubusercontent.com/5907868/46026951-def1bf00-c0ec-11e8-8611-1b7c2824dcc1.png)

**Comment by gmajoulet** [comment]
Thanks for filing this one!

We'll have to ask our designers, there are many possible solutions that would work, like the one you're suggesting, but I think they wanted to try something more visual like a "finger tapping the screen" animation, so we don't have to use any text.

**Comment by opusdei** [comment]
Thank you. Something visual and without text, as you say, would be great, because the left column is narrow and there will always be some language in which the text does not fit.
