### ISSUE TITLE
Move standard actions and action-service out of core

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#18357]
We should be able to move standard-actions and action service out of core and create a separate extension for it.

To keep backward compatibility we should consider:
1- throwing a warning in validation if script for actions is not included
2- dynamically load the extension if not included for at least 1 year before we can consider making the warning into an error.
3- have SSR inject the script for the duration of 2

This should shave off a good chunk from v0.js

/to @kristoferbaxter @prateekbh 
/cc @dvoytenko @choumx

**Comment by choumx** [comment]
According to source-map-explorer, action-impl.js + standard-actions-impl.js comprise about 5% of v0.js: https://choumx.github.io/amphtml/sme_0403.html

That analysis is from April but I just reran and it's still about there.

**Comment by kristoferbaxter** [comment]
Another item to ensure, what the performance impact of this change in the following scenarios:
1. Document doesn't require `standard-action` and `action` services.
2. Document requires `standard-action` and `action` services, but the document ensures they are loaded as extensions.
3. Document requires `standard-action` and `action` services, they are not present in the document, and must be lazily requested.

It would be nice to know what % these cases cover as well across documents.
