### ISSUE TITLE
amp-date-countdown: Support 'template' attribute

### ISSUE THREAD

**Issue by lucasjrd** [ampproject/amphtml#18360]
amp-date-countdown inside an amp-list generates this alert: The tag 'template' may not appear as a descendant of tag 'template'. 

The fact is: in this case it works fine. I can fill end-date attribute inside a amp-counterdown tag with a custom end date of a READER_ID and amp-date-countdown tag generates the correct counterdown. 

Two ways to solve this question:
1. Allow tag template as descendat of tag template when amp-counterdown is descendat of amp-list; or
2. Implement a src attribute inside a counterdown to output custom counterdown to different READER_ID users.

To reproduce this issue: 
1. Create an amp-counterdown tag inside template tag of amp-list.
2. Set amp-list src attribute to return an end-date like {"items":[{"end-date":"2018-09-25T18:34:08.000Z"}]};
3. Put {{end-date}} inside end-date attribute in a descendant amp-counterdown tag
4. Set time display inside template tag of amp-counterdown tag like {{hh}}:{{mm}}:{{ss}} 
5. It will works fine but the validator will display validation error message;

AMP Version 1809142227020
macOS High Sierra - Chrome Version 69.0.3497.100

**Comment by choumx** [comment]
There's a known validation issue with nested `<template>` elements. Instead, you can reference the templates by ID via the `template="<id>"` attribute. E.g.
```js
<template id="myTemplateId">...</template>

<amp-list template="myTemplateId">...</amp-list>
```

**Comment by lucasjrd** [comment]
Choumx,

Referencing the templates by ID via the `template="<id>" `is not the solution to the problem. 
Here the code I wrote:

`'<amp-list width="50" layout="fixed-height" src="https://foo.com/get-end-date.php?ird=READER_ID">`
`'     <template type="mustache">`
`'     '     <amp-date-countdown end-date="{{end-date}}" layout="fixed-height" height="50">`
`'     '     '     <template  type="amp-mustache">{{hh}}h {{mm}}m {{ss}}s</template>`
`'     '     </amp-date-countdown>`
`'     </template>`
`'</amp-list>`

The code worked fine, I got the custom end-date from src attribute and injected it into end-date attribute of amp-date-countdown tag. 
But this has generated the validation message: 'template' may not appear as a descendant of tag 'template'.
Referencing templates by ID via the `template="<id>"` do not change the state of things.
So the issue keeps with no workaround.

**Comment by lucasjrd** [comment]
Just reference templates by ID via the ` template="<id>" ` do not change
the state of things.
Besides this the tag amp-count-down do not accept attribute
`template="templateid"` -> `The attribute 'template' may not appear in tag
'amp-date-countdown'`
So this issue keep with no workaround.


Em qua, 26 de set de 2018 às 16:27, William Chou <notifications@github.com>
escreveu:

**Comment by lucasjrd** [comment]
Just reference templates by ID via the ` template="<id>" ` do not change
the state of things.
Besides this the tag amp-count-down do not accept attribute
`template="templateid"` -> `The attribute 'template' may not appear in tag
'amp-date-countdown'`
So this issue keep with no workaround.

**Comment by choumx** [comment]
Ah, we need to allow the `template` attribute in the validation rules for amp-date-countdown. Thanks, reopening.

**Comment by choumx** [comment]
@cvializ We should also support this in amp-date-picker.

**Comment by cvializ** [comment]
How would this best apply to `amp-date-picker`? I see some incompatibility with a single template attribute, since `amp-date-picker` allows multiple template elements as children which can apply to different calendar days, as well as the info area.

**Comment by choumx** [comment]
Just generally. E.g. supporting `info-template` and `date-template` attributes.

**Comment by leonalicious** [comment]
hey guys, appreciate your guys help on this as we will be having an promotion event at 11.11 (Double 11) globally, and it meant quite a lot to us, could your guys please help to support this `nested <template>` feature for `<amp-date-countdown>` in this 2 weeks time please ?

**Comment by choumx** [comment]
Runtime fix will be in dev-channel next Tuesday and production the following week. 

Validation changes are rolled out independently, but likely 1-2 weeks turnaround as well.

**Comment by RaFr** [comment]
is this validation issue expected to be fixed soon? the validation message is still present when the amp-date-countdown is used inside an amp-list
