### ISSUE TITLE
amp-datepicker: support specifying date ranges up to the present

### ISSUE THREAD

**Issue by dandv** [ampproject/amphtml#18379]
# Use case

Specify a time range for historical charts (e.g. rainfall, # of AMP pages, stock quotes).

This can be done by setting the `max` attribute to today's date.

## Issues

* with `number-of-months="2"`, an extra calendar month is displayed, filled with disabled dates
* the user can still navigate past the `max` date, even though `allow-blocked-ranges` is not present.

![image](https://user-images.githubusercontent.com/33569/46058434-f3937e80-c10f-11e8-9050-7970fff915b9.png)

## Repro

Demo: http://jsbin.com/bapihuc/edit?html,output

The key attributes are:

```
type="range"
number-of-months="2"
min="2018-08-01"
max="2018-09-25"
```

**Comment by cvializ** [comment]
Hello @dandv, thanks for the feature request! If I understand correctly, you would like the date picker to display an unlimited number of dates in the past up to today or another point. Is that correct? Right now that is not possible, but can be practically accomplished by specifying an arbitrarily distant point in the past. And right now we don't have plans to prevent users from viewing months that are completely blocked, but this issue can remain open to track the discussion.

**Comment by dandv** [comment]
Correct, and displaying a (practically) unlimited number of dates in the past is possible by setting `min` to way in the past, as you said. That solution is perfectly acceptable, especially if setting `min` to "0" were documented to work (it seems it does).

**Comment by aghassemi** [comment]
@cvializ anything needed here?

**Comment by cvializ** [comment]
It looks like the OP wanted to prevent navigation beyond the month of the max date. Given our current priorities though, I'm not sure it makes sense to implement it.

**Comment by aghassemi** [comment]
got it. Thanks. set it as P3
