### ISSUE TITLE
Document the datepicker RRULE property

### ISSUE THREAD

**Issue by dandv** [ampproject/amphtml#18371]
Blocked dates are a common use case, yet [the documentation is scant](https://www.ampproject.org/docs/reference/components/amp-date-picker#blocked), simply mentioning "RRULE". After reasonable effort (5 minutes), I wasn't able to figure out the correct syntax for the easiest pattern, blocking out X days starting on YYYY-MM-DD. The best I could come up with was

    blocked="DTSTART;2018-10-10 RRULE:FREQ=DAILY;COUNT=10"

This only disabled October 10 in the calendar.

I understand the RRULES are [complex](https://www.nylas.com/blog/calendar-events-rrules/), but the simple example of a contiguous block of days would go a long way. I suspect the problem with the code above is rather minor, probably an incorrect separator or argument order.

**Comment by cvializ** [comment]
Thanks @dandv for calling out this missing depth in our documentation! Let's prioritize adding more examples of RRULEs to our date picker documentation. 

For now, you might find this tool useful for creating RRULE dates. https://jakubroztocil.github.io/rrule/
