### ISSUE TITLE
amp-ad viewability should be 0 with window not in focus

### ISSUE THREAD

**Issue by giovanni-lovece-dm** [ampproject/amphtml#1838]
We are implementing viewability but we actually need that the ad has been in view for a certain amount of seconds (2 or 3 seconds). 

If I get a change in the intersection stating that the height is, for example, the 80% of the ad I start a timeout and after _n_ seconds i register the viewability. At the moment if the user closes browser or changes tab, I'm not aware that my ad is not visible anymore.

I think this can be solved in three ways: 
 - trigger a changeIntersection with 0 when the window has loss focus and the correct height when the window gets the focus again;
 - expose a method into the iframe to check the actual height of intersection so, before we register viewability, we can check that the value is compliant with our needs (it should be 0 if window is not in focus)
 - expose a method to get a boolean whether the main window is in focus or not;

What do you think about it?

**Comment by cramforce** [comment]
There is no way to know whether a window is focused on desktop (e.g. a different app could be in the foreground), but there is a way to find out whether a different tab has focus. You should definitely use this https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API

We will likely still reduce the height to 0 in this case, but I'd use the above as well.

**Comment by giovanni-lovece-dm** [comment]
If there's an intent to implement the 0 height for this case, I think we will use that.

After all is not that big loss of viewability but it would be fine if there will be a mechanism to check that.

Thank you

**Comment by cramforce** [comment]
Thought some more and 0 height is bad because some people use that for animations.

We will expose the visibility state similar to the page visibility API. I was actually working on that over the weekend.
