### ISSUE TITLE
How to use Shamsi or Hijri or others types of calendars on date picker component ?

### ISSUE THREAD

**Issue by aladaghlou** [ampproject/amphtml#18381]
Hi.
How to use Shamsi date or Hijri date or others types of calendars on date picker component ?
Are there solution for this problem?
This is not small problem !

Best regards.

**Comment by cvializ** [comment]
Hi @aladaghlou, thanks for opening this issue! amp-date-picker doesn't have a feature to display non-Gregorian calendars, but we do allow for parsing those dates using the `locale` attribute. We'll use this issue as a feature request to track non-Gregorian calendar systems.

**Comment by aghassemi** [comment]
If we do this, ideally it would be a separate add-on extension.
