### ISSUE TITLE
[amp-date-countdown inside amp-list] - 'template' may not appear as a descendant of tag 'template`

### ISSUE THREAD

**Issue by leonalicious** [ampproject/amphtml#18385]
Hey guys, we are currently facing an issue, we are getting `The tag 'template' may not appear as a descendant of tag 'template` validation error when we are trying to wrap a `<template>` of `<amp-date-countdown>` inside the `<template>` of `<amp-list>`

![image](https://user-images.githubusercontent.com/4065175/46078464-cc4bb880-c1c6-11e8-83fd-5bc54b1b7a35.png)

Everything works fine besides the validation, any workaround or suggestions please ?

**Comment by choumx** [comment]
Try using the `template` attribute instead. https://github.com/ampproject/amphtml/blob/master/extensions/amp-mustache/amp-mustache.md#nested-templates

Related: #18360

**Comment by lucasjrd** [comment]
Just reference templates by ID via the ` template="<id>" ` do not change the state of things.
Besides this the tag amp-count-down do not accept attribute `template="templateid"` -> `The attribute 'template' may not appear in tag 'amp-date-countdown'`
So this issue keep with no workaround.

**Comment by choumx** [comment]
Reopened #18360 to track the support of `template` attribute in amp-date-countdown. Closing this issue as a duplicate.
