### ISSUE TITLE
Allow customizing bookend content based on desktop vs. mobile

### ISSUE THREAD

**Issue by opusdei** [ampproject/amphtml#18384]
In the Desktop view, when the Bookend is displayed, the  top "share" bar disappears.

The title and other data that do appear on the top of the Bookend on mobile are not shown.

(version amp-story-0.1.js shows the "share" bar; no tittle)
(version amp-story-1.0.js no "share" bar; no tittle)

**Comment by newmuis** [comment]
This was an intentional UI change between 0.1 and 1.0, since sharing on desktop generally happens via URL more than anything else.

**Comment by opusdei** [comment]
Sorry. Maybe I did not explain it well.

The "share" button is present in Desktop, in all pages of the story. For example, there is an [active issue ](https://github.com/ampproject/amphtml/issues/17631) to fix the layout.

The problem is that this button disappears when the "Bookend" is shown, which is perhaps the best moment to share the story.

Another issue, related to what you say, is that the providers could be different in "mobile" and in "desktop". In fact, in many websites the "desktop" version does not show the "WhatsApp" option to share, but the mobile version does. It would be great if publishers can choose which providers want on mobile and which ones they want on desktop.

**Comment by newmuis** [comment]
Makes sense @opusdei!

The "share" pill is intentionally hidden when the bookend is open, but your higher level point of thinking through the sharing options when the story ends on desktop may make sense.

/cc @vinaymahag and @hongwei1990
