### ISSUE TITLE
amp-form: validation tooltip not showing properly in IE11

### ISSUE THREAD

**Issue by mcmd** [ampproject/amphtml#18398]
### What's the issue?
validation tooltip in a form not showing properly in IE11 when trying to submit with invalid input

### How do we reproduce the issue?

- Navigate to the https://ampbyexample.com/components/amp-form/ page in Internet Explorer 11-
- Scroll down to the "Form Submission with Page Update" section.
- Insert invalid values into the inputs and click "Subscribe".
- The form does not submit, and the tooltip either doesn't appear or it appears for a fraction of a second. In most cases: it will look like the form is not working:

<img width="422" alt="form-submission-with-page-update-ie11" src="https://user-images.githubusercontent.com/868584/46102354-fea8e600-c1c5-11e8-8b1d-176bfc960d67.PNG">

- Actually, if one leaves the enter key pressed, one might see the tooltip briefly, blinking.

### Expected result

The expected result for inputing these values and clicking on submit is actually seeing the tooltip. Screenshot from Chrome:

![screen shot 2018-09-26 at 7 56 21 pm](https://user-images.githubusercontent.com/868584/46102475-43cd1800-c1c6-11e8-876a-bb99ff25db7c.png)

Back to IE11, if one inputs correct values, the form actually submits

Example 1, OK response from server:
<img width="727" alt="form-submission-with-page-update-ie11-success" src="https://user-images.githubusercontent.com/868584/46102299-e0db8100-c1c5-11e8-89a1-20b625f72d66.PNG">

Example 2: Error response from server:
<img width="507" alt="form-submission-with-page-update-ie11-error" src="https://user-images.githubusercontent.com/868584/46102313-e5a03500-c1c5-11e8-8e36-28fc4513d47f.PNG">

### What browsers are affected?
Internet Explorer 11

### Which AMP version is affected?
Version 1809142227020

cc @cvializ @jasonconway-williams

**Comment by cvializ** [comment]
I did a quick investigation. First, it looks like there are 2 bugs here.

1. Polyfill standard validation bubbles. For some reason these are not appearing in IE11. They are currently working in Safari. Here's an example.
<img width="480" alt="screen shot 2018-09-26 at 15 44 28" src="https://user-images.githubusercontent.com/2363700/46105088-1753d480-c1a3-11e8-8c84-257dea62aa65.png">

2. Custom validation messages. It looks like AMP hides these with `display: none` and shows them by setting `display: initial`, [but `initial` is unsupported in IE11.](https://developer.mozilla.org/en-US/docs/Web/CSS/initial#Browser_compatibility)
