### ISSUE TITLE
amp-list and parsing json

### ISSUE THREAD

**Issue by spagu** [ampproject/amphtml#1839]
I am getting json short text formated with &amp;pound; charaters inside. 
Once placed to amp-list they do not get parsed and browser show &amp;pound; not £ . 
how to solve?

**Comment by dvoytenko** [comment]
@spagu could you please direct me to a sample page? And in the meantime, are you saying you actually pass `&pound;` directly or do you do `\u00A3`? The later is the correct way to encode pound character in JSON...

**Comment by dvoytenko** [comment]
@spagu will close this for now. Please re-open if you have more questions about this.
