### ISSUE TITLE
Valid analytics types implementation

### ISSUE THREAD

**Issue by aikt** [ampproject/amphtml#1840]
I would like to know if different types of analytics (Chartbeat for example) already has some way of  valid implementation in AMP projects (such as using the "amp-analytics" tag), like in this example:

"amp-analytics type="chartbeat"
script type="application/json"
{
  "vars": {
    "uid": "12345",
    "domain": "my-site.com",
    "sections": "section 1, section 2"
  }
}
/script
/amp-analytics"

Is this already the appropiate way of implementing it or will be another method for doing so?
Thanks.

**Comment by rudygalfi** [comment]
You can see how to use `type` with a Google Analytics integration here: https://devsite.googleplex.com/analytics/devguides/collection/amp-analytics/

If you're curious specifically about Chartbeat, I believe they said last week that they'd be making documentation available soon.
