### ISSUE TITLE
Cherry pick canary release to fix a race condition in amp-analytics unlayout (Approved)

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#18405]
**Replace *everything* in angle brackets in the title AND body of this issue.  If you have any questions see the [cherry pick documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-picks).**

**GitHub issue your cherry pick is fixing:**

Issue #18395 

**PR that you are requesting a cherry pick for:**

*(Put N/A if you do not yet have a PR with a fix; edit this issue to add it when the PR is ready.)*

PR #18400 

**Release(s) you requesting this cherry pick into:**

*Release issues can be found at https://github.com/ampproject/amphtml/labels/Type%3A%20Release*

*If you are requesting a cherry pick into a production release you will most likely need to cherry pick into canary as well, otherwise when the canary is pushed to production your fix will be lost.  See the [cherry pick documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-picks).)*

Production Release? <NO> 

Canary release? <YES>  If yes, Type: Release Issue #18374

*Why does this issue meet the [cherry pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?  Be specific.*

The bug was a regression caused by a recent refactoring.

*Assign this issue to the current TL (cramforce) if you have permission to, otherwise leave this cc line in.*

/cc @cramforce
/cc on duty @calebcordry

**Comment by cramforce** [comment]
Approved
