### ISSUE TITLE
Support for Snap Pixel

### ISSUE THREAD

**Issue by stephengardner** [ampproject/amphtml#18428]
In my understanding of amp-pixel, and amp-analytics, the Snap Pixel is not adequately supported.  Here's documentation for the Snap Pixel and a Page View event: https://businesshelp.snapchat.com/en-US/article/pixel-page-view

**Comment by jeffjose** [comment]
I'm not familiar with what a Snap Pixel is but from reading their documentation you can [setup Snap Pixel through GTM?](https://businesshelp.snapchat.com/en-US/a/formatting-pixel) 

Does that not work?

**Comment by stephengardner** [comment]
@jeffjose I'm similarly not familiar - this is for a client asking for integration.  I believe GTM is possible, and that's what is likely going to happen here, but I'm not sure if the answer should be just to use GTM.  Perhaps that's fine.  The issue seems to be resolved for me at least.

**Comment by jeffjose** [comment]
If you're running into issues, please dont hesitate to reach out again! Closing this issue for now.
