### ISSUE TITLE
Intent To Implement: Yieldmo ad network for amp-ads

### ISSUE THREAD

**Issue by yieldmo-rao** [ampproject/amphtml#1842]
# Overview

Support for the [Yieldmo](https://yieldmo.com) ad-network will be added to `<amp-ad>` elements.

### Comments

Yieldmo will be submitting a PR via the `yieldmo/amphtml` fork from the `feature/yieldmo` branch.

**Comment by cramforce** [comment]
LGTM

**Comment by rudygalfi** [comment]
Closing because #1850 was merged. Let me know if this needs to stay open.
