### ISSUE TITLE
Facebook embeds not working

### ISSUE THREAD

**Issue by maxhartshorn** [ampproject/amphtml#1843]
When I try and run the `facebook.amp.html` example I only see blank boxes where the `<amp-facebook>` embeds should be.

Some documentation for `<amp-facebook>` would be very helpful as well.

**Comment by cramforce** [comment]
@mkhatib Could you take a look?

**Comment by mkhatib** [comment]
@maxhartshorn, are you running the examples with `gulp` command? Are you seeing any errors in the browser console? I've just tried running the example and it seems to be working.

**Comment by mkhatib** [comment]
As for documentation, we've [this document to explain the attributes](https://github.com/ampproject/amphtml/blob/master/extensions/amp-facebook/amp-facebook.md) for `amp-facebook` if anything is missing on the usage happy to add some more docs.

**Comment by maxhartshorn** [comment]
Thanks @mkhatib it was an issue on my local. I am able to see the embeds now. Thanks for the documentation. I had been looking here (https://github.com/ampproject/amphtml/blob/master/extensions/README.md) for documentation updates but I'll look in amphtml/extensions from now on.

**Comment by rudygalfi** [comment]
@maxhartshorn If you think this is resolved, please close. Thanks!
