### ISSUE TITLE
Document opt-out in Analytics

### ISSUE THREAD

**Issue by jmadler** [ampproject/amphtml#1844]

**Comment by cramforce** [comment]
The only thing we can document is: "Please analytics vendor, email us."

**Comment by rudygalfi** [comment]
Can we incorporate this as an item in #1791? For instance, "Consider if your integration requires opt-out support and be sure to clearly raise this requirement in your intent to implement so that we can discuss a solution."

**Comment by cramforce** [comment]
That SGTM.
