### ISSUE TITLE
FR: Facebook "page reviews" and "events" components

### ISSUE THREAD

**Issue by tmdoit** [ampproject/amphtml#18459]
Should work like ie. "amp-facebook" component.

**Comment by ericlindley-g** [comment]
Thanks for filing this, @tmdoit  — do you currently have pages where you'd like to use this feature?

**Comment by tmdoit** [comment]
Currently not, working on projects where I want to use those features.

**Comment by ericlindley-g** [comment]
Got it — thanks @tmdoit 

/cc @aghassemi Would this make a good GFI?

**Comment by aghassemi** [comment]
It bit more involved than a GFI but certainly doable. 

Would be very similar to this Pull Request: https://github.com/ampproject/amphtml/pull/13261 which can be used as reference.

**Comment by aghassemi** [comment]
@tmdoit If you are interested in contributing this component, we have great resources to get you started:

https://bit.ly/helpamp

and series of talks in our recent AMP Contributor Summit, particularly https://www.youtube.com/watch?v=kjn322ELFvs and https://www.youtube.com/watch?v=hnJeUzbCt6I

and as mentioned above: #13261 can be used a reference.

I'll be happy to provide real-time help on Slack as needed as well.

**Comment by tmdoit** [comment]
@aghassemi thanks. Alright, I plan to start next week.

**Comment by aghassemi** [comment]
Thanks @tmdoit! . My Slack handle is the same, ping me anytime here or on Slack i you have questions or run into any issues.
