### ISSUE TITLE
Background color of slide not picking up

### ISSUE THREAD

**Issue by psdtomanythings** [ampproject/amphtml#18458]
When you have an image as a background for a slide, the story picks up the image, blurs it and then adds it behind the slide. But the same behavior does not happen while using gradients or color as a background. Following is an example 

Story slide  taking up the image and blurring it 👌

![my story](https://user-images.githubusercontent.com/22929187/46254404-9a7b7000-c4ac-11e8-8dfc-86825305731f.jpg)

Story slide of how it is right now while having a background color

![my story 1](https://user-images.githubusercontent.com/22929187/46254413-d44c7680-c4ac-11e8-9332-3840b0e0d088.jpg)

My suggestion on how it shall look like by pulling the background color from slide

![my story 2](https://user-images.githubusercontent.com/22929187/46254415-e5958300-c4ac-11e8-8971-0c2c86aacf5d.jpg)

**Comment by newmuis** [comment]
Great suggestion!  Should be an easy fix 🙂

**Comment by newmuis** [comment]
This is obsolete, as we have deprecated this UI.
