### ISSUE TITLE
Support for details / summary tags

### ISSUE THREAD

**Issue by DamonHD** [ampproject/amphtml#18461]
## What's the issue?

The HTML5 details and summary tags are apparently disallowed by AMP and amphtml-validator.

Please add support for them.  They do seem to work in every browser I interact with.

## Which AMP version is affected?

(NPM) amphtml-validator 1.0.23

eg:

    % amphtml-validator amp/sitemap.html 
    amp/sitemap.html:4:391 The tag 'details' is disallowed.
    amp/sitemap.html:4:400 The tag 'summary' is disallowed.

**Comment by choumx** [comment]
Will be fixed by #18440.

**Comment by DamonHD** [comment]
Great!

Rgds

Damon

**Comment by DamonHD** [comment]
Any ETA for when this might appear in a production release?

Just so I can do some planning...

Rgds

Damon

**Comment by westonruter** [comment]
#18440 has been merged

**Comment by DamonHD** [comment]
Thanks again!

How long might that take to wind through the system and be available in a new released validator?

(It's not like anyone's doing anything for the next couple of weeks, right?  %^P)

Rgds

Damon

**Comment by honeybadgerdontcare** [comment]
There's currently a production freeze due to the holidays. Expect to see it once that ends in the new year.

**Comment by DamonHD** [comment]
Hurrah!  \o/

**Comment by DamonHD** [comment]
Data point FYI, the live validators are now fine with details/summary, but Google Search Console continues to complain about "Disallowed tag present." on a sample page.

Hope you have had a good break when/if you see this!  B^>

Rgds

Damon

**Comment by DamonHD** [comment]
Ta!

It will be interesting to see what GSC does with a page that doesn't change and a spec that does, ie will the latter trigger a re-parse and an AMP validation pass automatically?  B^>

Rgds

Damon

**Comment by DamonHD** [comment]
Ahem ... I'm itching to release a small feature that probably no one will ever notice (!), and GSC still says "no" as of a few minutes ago!  Do you have any particular visibility of when these will be really OK in G's index?  B^>

Rgds

Damon

**Comment by DamonHD** [comment]
\o/

GSC is apparently now happy with details/summary.  I have unleashed the hounds.  Well, a auto-ToC...  %-P

Thanks again,

Damon
