### ISSUE TITLE
Stop slide's autoplay when user starts swiping 

### ISSUE THREAD

**Issue by LendsMan** [ampproject/amphtml#1846]
It seems messy when you start swiping slide and suddenly autoplay timeout comes to an end.

* If you try to swipe to the right (backward) and hold (or just swipe at the right time)  you get half of the image you were trying to swipe on top of the next image.
Left half of image is frozen and it disappears from the screen only when the same image comes to the screen.
![Example](http://s22.postimg.org/s7bjtr8m9/Untitled.png)

* If you try to swipe to the left (forward) the image just runs away from under your finger even if you decide not to swipe.

Shouldn't we reset and stop timer when user starts swiping?

**Comment by cramforce** [comment]
+1

**Comment by erwinmombay** [comment]
fixed in https://github.com/ampproject/amphtml/commit/7a49b0bfaee866a2b71430316623e1d7aa7f3f46
