### ISSUE TITLE
 AMP pages with invalid attribute values

### ISSUE THREAD

**Issue by wordpressnewbie** [ampproject/amphtml#1847]
Google crawled my site finally and found the new AMP plugin, Yayyyyy!!! :)

It did send me an error, here is a link to the page, is it because the image is to large?

http://www.canadianprocessserving.com/the-advocates-society-tricks-of-the-trade-2016-seminar/amp/

**Comment by Gregable** [comment]
Nice work! If you want to see the actual error, you can visit
http://www.canadianprocessserving.com/the-advocates-society-tricks-of-the-trade-2016-seminar/amp/#development=1 and open the javascript developer console (Cntrl+Shift+J in chrome).

The errors I see are:
```
http://www.canadianprocessserving.com/the-advocates-society-tricks-of-the-trade-2016-seminar/amp/:237:58 The attribute 'rel' in tag 'a' is set to the invalid value 'attachment wp-att-2558'.
http://www.canadianprocessserving.com/the-advocates-society-tricks-of-the-trade-2016-seminar/amp/:238:58 The attribute 'rel' in tag 'a' is set to the invalid value 'attachment wp-att-2559'.
```

237:58 and 238:58 are line:column numbers referring to:

```
<a href="http://www.canadianprocessserving.com/wp-content/uploads/2016/02/IMG_20160129_104406-1.jpg" rel="attachment wp-att-2558">...</a>
...
<a href="http://www.canadianprocessserving.com/wp-content/uploads/2016/02/IMG_20160129_151302-1.jpg" rel="attachment wp-att-2559">...</a>
```

And at issue are the attributes like `rel="attachment wp-att-2558"`. Those are wordpress specific and not recognized by AMP HTML. If you remove those attributes, you should resolve these errors.

I hope that helps.

**Comment by wordpressnewbie** [comment]
Greg thanks for this!

AS my handle says I am a newbie big time, so another question if I may.

Do I have to physically change the pictures then that I will be using for amp pages?

If so how?

Also my developer tools does not show Javascript!?

Help!

**Comment by cramforce** [comment]
@Gregable Should we just allow `attachment` and `wp-*` for `rel`? This has come up before and seems benign enough.

**Comment by Gregable** [comment]
@cramforce I don't see any problem with that one. It's apparently a base wordpress thingy, so common across wordpress installations.

@wordpressnewbie It sounds like you've enabled the AMP wordpress plugin. Unfortunately, that plugin is still a work in progress and does create some errors. The good news is that these errors don't get you any worse off than you are before. These pages won't appear as AMP pages, but they are still perfectly fine / show up on the web. I suspect as the developer of the plugin continues to iterate on it, things will improve and you'll see fewer errors over time, by doing nothing other than keeping your plugin up to date with new updates.

**Comment by cramforce** [comment]
@Gregable Assigning to you for those extra rel values.

**Comment by mjangda** [comment]
FYI, the next version of the WordPress plugin will actually strip out the `wp-` rel attributes (`attachment` was a valid value when I checked) but might make sense to just have the validator ignore them.

**Comment by cramforce** [comment]
Great! We should still allow them, for people who might roll their own with
WordPress. We use a whitelist for security reasons, not because we want to
police HTML :)

**Comment by Gregable** [comment]
This is fixed in github and will be live on cdn.ampproject.org within an hour or so.

**Comment by wordpressnewbie** [comment]
Wow, I dont know what this all means, but thanks :)

**Comment by Gregable** [comment]
@wordpressnewbie In short, these errors that you've spotted will go away. We've made them non-errors on the AMP side going forward, so that you and other folks using WordPress won't have to bother with them.

**Comment by wordpressnewbie** [comment]
Cue the fireworks, thanks everyone!!!
