### ISSUE TITLE
[Viewer, iOS] Scroll jitter of fixed element gated by amp-experiment

### ISSUE THREAD

**Issue by aboekhoff** [ampproject/amphtml#18479]
If I scroll down on the google hosted version the white CTA appears underneath the button.
I want to confirm if this is a viewer bug or an issue with our AMP code:

[correct layout](https://amp.reddit.com/r/scriptedasiangifs/comments/7ze2v4/best_soccer_goal_of_all_time/)

[incorrect layout](https://www.google.com/amp/s/amp.reddit.com/r/scriptedasiangifs/comments/7ze2v4/best_soccer_goal_of_all_time/)

If it can be fixed by a change to our AMP code please advise.

**Comment by choumx** [comment]
Can you elaborate on what the expected visual state is? It's not obvious to me at a glance.

Publisher origin:
![image](https://user-images.githubusercontent.com/20525523/46835403-1793c880-cd7c-11e8-8d8b-975c58eed1c6.png)

Google viewer:
![image](https://user-images.githubusercontent.com/20525523/46835416-1e224000-cd7c-11e8-8bcd-7aa5f9f8e6a5.png)

**Comment by aboekhoff** [comment]
If you view the page in the view in an actual iOS device the CTA at the bottom bounces around the bottom of the screen when scrolling. 

I also see a blue pill that we removed from the AMP page but appears in the cached in-viewer version.

**Comment by aboekhoff** [comment]
@choumx bump
This bug only happens in the viewer in Safari on an actual iOS device.

**Comment by aboekhoff** [comment]
I was notified of another bug today. On the same page in the viewer on iOS, if you scroll all the way to the bottom then it becomes impossible to scroll back up. Thinking this might be related to the above fix.

@choumx @jridgewell
