### ISSUE TITLE
AMP-YOUTUBE not working when AMP page is loaded in Google carousel

### ISSUE THREAD

**Issue by oliverfernandez** [ampproject/amphtml#18500]
I have an AMP page that has a Youtube video that does not work when seen in Google Search carousel.

The video works fine when:

1. Visting the AMP page itself: https://amp.economiadigital.es/politica-y-sociedad/el-idilio-de-los-cdr-y-quim-torra-da-alas-a-la-aplicacion-de-un-nuevo-155_580583_102.html

2. Visiting the AMP page in the AMP cache: https://amp-economiadigital-es.cdn.ampproject.org/c/s/amp.economiadigital.es/politica-y-sociedad/el-idilio-de-los-cdr-y-quim-torra-da-alas-a-la-aplicacion-de-un-nuevo-155_580583_102.html

But the video does not load when the AMP page is seen in Google Search carousel: https://www.google.es/amp/s/amp.economiadigital.es/politica-y-sociedad/el-idilio-de-los-cdr-y-quim-torra-da-alas-a-la-aplicacion-de-un-nuevo-155_580583_102.html

I've seen that the AMP page loaded by Google Search does not contain the AMP-YOUTUBE Javascript extension `<script async custom-element=amp-youtube src="https://cdn.ampproject.org/v0/amp-youtube-0.1.js"></script>`,  although it is present in the original AMP page, so I suspect it may be a problem related to the an AMP cache transformation

**Comment by Gregable** [comment]
The `google.es/amp/` page is actually just the AMP viewer, so it iframes the doc. If you right click and view frame source, you'll see the custom-element script present, so it's not being removed from the cache.

In fact the cache document in the frame is the same content as your `#2` link. This must be a bad interaction between the viewer and the document. I'm not sure how to debug further myself. @cathyxz for further triage?

**Comment by Gregable** [comment]
Agreed, I got a different usqp parameter. Tracked internally as `117243263`

**Comment by jridgewell** [comment]
We have ramped down the experiment. Testing the [SERP viewer version](https://www.google.es/amp/s/amp.economiadigital.es/politica-y-sociedad/el-idilio-de-los-cdr-y-quim-torra-da-alas-a-la-aplicacion-de-un-nuevo-155_580583_102.html), I now get a different `usqp` parameter. I think that means this is now resolved.

**Comment by jridgewell** [comment]
Sorry, too soon. The configuration change is still propagating.

**Comment by jridgewell** [comment]
Ok, now propagation is done.

**Comment by oliverfernandez** [comment]
Thanks everyone for fixing this! :)

**Comment by twifkak** [comment]
I forgot to mention - the experiment is fixed (hopefully) and ramped back up, as of 15 Oct. Let us know if you see the problem recur!
