### ISSUE TITLE
amp-image-lightbox inside a amp shadow (pwa)

### ISSUE THREAD

**Issue by roelvanhoof** [ampproject/amphtml#18523]
## What's the issue?

When you load an amp page inside a pwa as described here (https://www.ampproject.org/docs/integration/pwa-amp/amp-in-pwa), the amp-image-lightbox will behave different than when the not in a shadow dom.

What happens (see gif below) is that the image is invisible and you see the black background until the image is at the correct position, then all of a sudden it displays the image with a flicker.

When you close the lightbox the image moves up too fair to the top then jumps back down when it reaches the top.

All in all it doesn't look good and feels flaky.

## How do we reproduce the issue?

Load an amp page with an amp image lightbox inside an amp shadow according to the article above, click on the image and see it behave weird.

### behavior inside shadow dom

<img src="https://user-images.githubusercontent.com/2346281/46412535-1bda3900-c71f-11e8-923d-87dca18c73ea.gif" width="375" height="650">

### behavior outside shadow dom

<img src="https://user-images.githubusercontent.com/2346281/46412546-21378380-c71f-11e8-8163-75e09495df08.gif" width="375" height="650">

**Comment by aghassemi** [comment]
Yay! Thanks for the quick fix!
