### ISSUE TITLE
Validator do not recognize timeleft-ms attribute on amp-date-countdown tag.

### ISSUE THREAD

**Issue by lucasjrd** [ampproject/amphtml#18524]
I set up an amp-date-countdown to hide a section div in 15 seconds.
Here the code:
`<amp-date-countdown layout="fixed-height" timeleft-ms="15000"	height="25" on="timeout:section1.hide"  when-ended="stop" locale='en'>`
`     <template type="amp-mustache">`
`     {{s}} seconds to close.`
`    </template>`
`</amp-date-countdown>`

But I got this message on validator:` "One of end-date, timestamp-ms, timestamp-seconds is required"` Validator do not recognize  timeleft-ms attribute on amp-date-countdown tag.

AMP VERSION 1810021759000
Mac OS High Sierra - Chrome  69.0.3497.100 - 64bits

**Comment by honeybadgerdontcare** [comment]
@lucasjrd 	the timeleft-ms was recently merged to the codebase (#18415) and validation changes can take up to 2 weeks to go live in production. I'd check again in a week to see if it is live. Please reopen in a week if there is still an issue with using this feature.
