### ISSUE TITLE
The tag 'amp-recaptcha-input' is disallowed

### ISSUE THREAD

**Issue by usman601** [ampproject/amphtml#18522]
**getting error ,The tag 'amp-recaptcha-input' is disallowed**
## What's the issue?

The tag 'amp-recaptcha-input' is disallowed,when using amp-captcha

## How do we reproduce the issue?
1.include amp-captcha script  as given in example

## What browsers are affected?

All browsers

**Comment by torch2424** [comment]
Hello! 

Yes this is currently disallowed, as the component hasn't been completed yet, and is still in experiment. 

We are getting close to having it ready, and are almost code complete in the client, but now we are working with Caches to make sure we get domains right before we release this to be used.

I'm going to close this issue, but feel free to comment back. Once this gets released I'll be sure to reach out. Thanks! 😄
