### ISSUE TITLE
amp-date-picker: allow amp-bind binding to property src in amp-date-picker

### ISSUE THREAD

**Issue by mcmd** [ampproject/amphtml#18548]
For a travel website, the availability of dates may vary depending on the selection of other options in the page (route, number of people, discounts, etc). 

In order to only show the suer valid dates combinations, the date picker need to dynamically refresh the availability based on the previous selection. This could be achieved by refreshing the remote configuration available in amp-date-picker.src

**Comment by cvializ** [comment]
@mcmd Thanks for the feature request! This one makes sense to me especially for e-commerce use cases.

**Comment by belobrad** [comment]
Could we also add the ability for the amp-date-picker.src to pass back date-specific data that would become available in day templates? 

For example, there might be a nightly surcharge that is different for each night based on mentioned criteria and we would like to show these in calendar for user to make travel date selection based on it.

Adding a 3d parameter to `id` and `dates` fields that would hold the data object for example.

**Comment by AndrewKGuan** [comment]
This is super useful to dynamically (server-side) verify a user's input to provide timely feedbacks such as blocked dates by zip codes, etc.
Any timeline on this feature?

**Comment by AndrewKGuan** [comment]
By the way, the 'blocked' attribute is not bindable either, so there's no way to dynamically block out dates.
I would expand this feature request to making all attributes on date picker bindable.

**Comment by rudygalfi** [comment]
cc @nainar
