### ISSUE TITLE
Recent change causing regression/changes in some features

### ISSUE THREAD

**Issue by shishirm** [ampproject/amphtml#18549]
## What's the issue?

Around the 18th of September, we noticed a few features behavior has changed causing our AMP sites to be broken. Both of these are around usage of amp-mustache,. The two specific instances are,

* Previously the disabled attribute on a select input tag was ignored, but after September 18th, this is now working.
* We are trying to open a new tab using an <a> tag that binds its [href] to a zipcode entered in another field to dynamically construct the URL. We expect the change in zipcode to automatically update the href but this is not happening and the appropriate URL with the zipcode is not being constructed. This was working earlier but stopped working around September 18th or so.

## How do we reproduce the issue?

In the first case here is some sample code,

```
<amp-list width="auto" height="50" layout="fixed-height" [src]="values || '@makesValuesJsonUrl'" src="@makesValuesJsonUrl">
  <template type="amp-mustache">
    @*<label for="value">Value:</label>*@
    <select id="value" name="values" [disabled]="!values">
                        {{#values.0}}
                        <option value="">All Values</option>{{/values.0}}
                        {{#values}}
                        <option value="{{id}}~{{make_id}}">{{name}}</option>{{/values}}
    </select>
  </template>
</amp-list>
```

In the second case,

```
<input data-class="ZipCode" data-errorevent="error" data-form-element="zipCode" id="zipcode" maxlength="5" name="selectedZipCode" on="input-throttled: AMP.setState({ selectedZipCode: event.value, isValidForm: fiveDigitsValidation(event.value) })" pattern="[0-9]{5}" placeholder="Enter Zip" required="" type="tel" value_amp_attribute="selectedZipCode" />

<a class="col-xs-4 custom-padding-values" {href}="quoteHrefRewrite('{{value_seo_name_legacy}}',selectedZipCode)" on="tap:AMP.setState({selectedValue:'{{value_seo_name_legacy}}', hideModal: isValidForm, hideErrorMessage: isValidForm }), home.submit" target="_blank"> <span class="cc-value-box" id="{{value_seo_name_legacy}}" role="button" tabindex="0"> <amp-img class="cc-image" height="39" src="{{image.thumb_url}}" width="85"></amp-img> <span class="{{value_seo_name}}">{{value_name}}</span> </span> </a>
```

## What browsers are affected?

All browsers and devices

## Which AMP version is affected?

This began happening around September 18th (+/- one week)

**Comment by choumx** [comment]
Thanks for the report. Will take a look today. Possibly related to #18463.

**Comment by choumx** [comment]
Sorry forgot to respond. I took a look at these issues.

> Previously the disabled attribute on a select input tag was ignored, but after September 18th, this is now working.

This hasn't changed recently -- `<select [disabled]="foo.bar">` was added over a year ago. Might be a new browser?

In the second case, it looks like the `href` attribute has an unexpected curly brace:

```html
{href}="quoteHrefRewrite...
```

Should be using `href={{...}}` since attribute calculation is not allowed by the AMP validator: https://github.com/ampproject/amphtml/blob/master/extensions/amp-mustache/amp-mustache.md#restrictions
