### ISSUE TITLE
Codelabs: Creating your first AMP Component | Add new requirement

### ISSUE THREAD

**Issue by eduardogoncalves** [ampproject/amphtml#18575]
When creating PRs **travis-ci** runs `gulp check-types`, and this is time consuming if something wents wrong, but without **Java SDK 8** on my local machine I was unable to run `gulp check-all` or `gulp check-types` before sending PRs. I tried to install **Java SE Development Kit 11**, but didn't work, so on Slack @erwinmombay  asked me to try **Java SDK 8** and it worked.

What about to add [Java SE Development Kit 8u172](https://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html) as a requirement in [Creating your first AMP Component add new requirement](https://codelabs.developers.google.com/codelabs/creating-your-first-amp-component/index.html#0).

**Comment by aghassemi** [comment]
agreed. to @alanorozco to update.

**Comment by alanorozco** [comment]
I feel like this might be more relevant [here](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md#build-amp--run-a-local-server)?
