### ISSUE TITLE
Codelabs: Creating your first AMP Component | Add new Slide for sending PRs

### ISSUE THREAD

**Issue by eduardogoncalves** [ampproject/amphtml#18577]
What do you think about add a slide on [Codelabs: Creating your first AMP Component](https://codelabs.developers.google.com/codelabs/creating-your-first-amp-component/index.html#4) after **Slide 4**, about [Running all the Travis CI checks locally](https://github.com/ampproject/amphtml/blob/81262411085754eb3e978fb68e87b5e8fa307d80/contributing/getting-started-e2e.md#running-all-the-travis-ci-checks-locally) or running `lint`, `check-types` and `presubmit`, as this can be time saving when sending PRs?

```
gulp check-all --files extensions/amp-hello-world/0.1/amp-hello-world.js
```
or
```
gulp lint --files extensions/amp-hello-world/0.1/amp-hello-world.js
gulp check-types --files extensions/amp-hello-world/0.1/amp-hello-world.js
gulp presubmit --files extensions/amp-hello-world/0.1/amp-hello-world.js
```

**Comment by aghassemi** [comment]
SGTM, to @alanorozco

**Comment by alanorozco** [comment]
https://codelabs.developers.google.com/codelabs/creating-your-first-amp-component/index.html#4 :)
