### ISSUE TITLE
I2I: A better `localhost:8000` homepage

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#18581]
## Background

The top-level page under the development server (`localhost:8000`) shows the directory contents of the top-level path of the repo. This is useful when browsing the directory itself (e.g. going to an `/examples/` page), but doesn't allow for discoverability or easy use of hidden server features.

## Goal

To provide a more usable interface for the top-level path on the AMP server.

## Details

Several features can be included. **The idea is to keep this tool simple enough to not be a pain to maintain, but robust enough to provide entry points into development features that are somewhat hidden.** This list is open-ended so others can chime in.

- Listing the `/examples/` directory by default (with an option to list the root dir?)
- Outlink instead to a documentation entry point, like [ampproject.org](https://ampproject.org)
- Links to hosted tooling (e.g. Travis, Percy, etc.)
- A simple form to load AMP documents under /proxy/s/.
- Linking to/rendering experiment toggles.
- Fuzzy (possibly, might be too complex) filtering of the current directory using a module like Fuse.js
- Link / instructions to create a PR from this branch if the branch has been pushed
- etc. (this is open-ended)

These features can be laid out to be easily discoverable and usable. Rough mockup of how this would look like:

![image](https://user-images.githubusercontent.com/254946/46564178-a3a87a80-c8ba-11e8-9f01-9e67a2fd476f.png)

**Please chime in with ideas!**

**Comment by ithinkihaveacat** [comment]
Perhaps it could also display the contents of DEVELOPING.md? There's some relevant info there, and it would also give it more visibility.

Very much support adding the load URL by proxy! That thing is amazing, and also somewhat difficult to discover. I guess that should also link to https://github.com/ampproject/amphtml/blob/ab14b783907f811d6fc6a076ec7e1697939ab588/contributing/TESTING.md#document-proxy, or perhaps that info can be moved to DEVELOPING.md, if that ends up being displayed.

**Comment by mrjoro** [comment]
This was implemented!  I'm closing out this issue now; if there are new features you're planning on implementing feel free to reopen or file new issues to track them.
