### ISSUE TITLE
CORS - CDN - Google - Another change with no communication and breaking changes

### ISSUE THREAD

**Issue by AcidRaZor** [ampproject/amphtml#18595]
Hi,

In reference to CORS: https://www.ampproject.org/docs/fundamentals/amp-cors-requests

Nowhere does it mention having to white-list **all** google sites (depending on country of origin)

Have our website listed on Google, ready with the AMP, the link is:

https://www.google.co.za/amp/s/*REDACTED*

So, Google is indexing and showing our site, AMP ready and in the cache, however, none of my API calls will work because above-mentioned documentation shows *.ampproject.org and/or cloudflare headers.

I'm now tasked to find out:

WHY did the AMP Project team and the Search Index team deviate from the documentation?
WHY was there no updates regarding this changing (upcoming, when it would be released etc.)?

Currently I see no benefit with working on this anymore as it would appear Google is deliberately trying to kill the user-experience and journey that so many of us have been promised are the actual goal of this project.... please change my mind about this.

Thank you for your feedback.

**Comment by aghassemi** [comment]
@AcidRaZor there isn't a (new or existing) requirement to list `google.*` sites in CORS headers.

Could you please provide a working link to a page that's broken for you so I can debug?

Here is a working example of `amp-list` served from `https://www.google.co.za` which makes an API call:

https://www.google.co.za/amp/s/ampbyexample.com/components/amp-list/ 

The headers are only:
```
access-control-allow-origin: https://ampbyexample-com.cdn.ampproject.org
access-control-expose-headers: AMP-Access-Control-Allow-Source-Origin
amp-access-control-allow-source-origin: https://ampbyexample.com
```

as it works as expected.

(As mentioned couple of times before, please keep the discussion on GitHub technical. There is no need for blameful language)

**Comment by aghassemi** [comment]
@AcidRaZor Please also let us know what OS/browser you are seeing this issue with. Thanks.

**Comment by AcidRaZor** [comment]
Hi @aghassemi 

The API is written to the specifications on that page, in particular:

> "If the Origin header is set:
> 
> If the origin does not match one of the following values, stop and return an error response:
> 
> *.ampproject.org
> *.amp.cloudflare.com
> the publisher's origin (aka yours)
> where * represents a wildcard match, and not an actual asterisk ( * ).
> 
> If the value of the __amp_source_origin query parameter is not the publisher's origin, stop and return an error response.
> 
> If the two checks above pass, process the request."

Because google.co.za doesn't form part of that, and it's not the publisher's origin, my API responds with a 401 Unauthorized. This means any API call that is made from the google.co.za link won't get honored as per above documentation.

Are you saying I should just allow any origin? Regardless? And ignore the documentation and security? 

If you can confirm this, I will let my team know and we can move forward.

**Comment by AcidRaZor** [comment]
OS/Browser ranges from IOS Safari, Chrome, Android Chrome and Samsung browser. On a PC it redirects to our site immediately

**Comment by aghassemi** [comment]
You should never see requests coming from google.co.za origin. AMP pages that look like they are served from google.co.za are actually iframed pointing to *.cdn.ampproject.org.

**Comment by AcidRaZor** [comment]
Interesting. Thanks for the insight.

**Comment by aghassemi** [comment]
You are welcome.
