### ISSUE TITLE
Amp-ad not appending scp for doubleclick on slow networks

### ISSUE THREAD

**Issue by Guilemon** [ampproject/amphtml#18593]
## What's the issue?

`amp-ad` tag for type `doubleclick` does not append `scp` on slow networks even when targeting data is getting returned from server

## How do we reproduce the issue?

go to url:  https://output.jsbin.com/yubucoj

To test in Chrome:

1. Go to chrome developer tools.
2. In network tab, select Disable Cache and select throttling to Slow 3G. set filter type to xhr
3. Confirm targeting url returning targeting data in response.
4. Check doubleclick url. No `scp` present in header.

To test in firefox, follow same above steps, set throttling to regular 3G

## What browsers are affected?

Tested on chrome version 69.0.3497.100  and firefox version 62.0.2

## Which AMP version is affected?

Tested on Version 1810052220151 . New to amp so can't say whether it existed before.

**Comment by aghassemi** [comment]
to @lannka

**Comment by jeffkaufman** [comment]
@Guilemon thanks for the clear report!

It looks like you're using RTC, and RTC includes a [one second timeout](https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/rtc-documentation.md).  With networking throttled this timeout is hit, and the amp-ad goes ahead and sends the ad request without the `&scp=` parameter.

Closing this, as it looks to me like it's working as it should.  Feel free to reopen if you think I'm missing something!
