### ISSUE TITLE
amp-carousel jitters at the end of transition on iOS

### ISSUE THREAD

**Issue by xiaotong-z** [ampproject/amphtml#18592]
## What's the issue?

amp-carousel jitters at the end of each transition.

## How do we reproduce the issue?

1. Visit m.aliexpress.com
2. Manually swipe the slides.
3. At the end of every transition, there will be jitters.

This cannot be reproduced on Android.

## What browsers are affected?

Safari and Chrome on iOS 11.3

## Which AMP version is affected?

1810052220151

**Comment by xiaotong-z** [comment]
[ScreenRecording_.MP4.zip](https://github.com/ampproject/amphtml/files/2454853/ScreenRecording_.MP4.zip)

**Comment by nainar** [comment]
This should have been fixed by the former PRs. Can't repro on Safari on iOS

**Comment by nainar** [comment]
This should have been fixed by the former PRs. Can't repro on Safari on iOS

**Comment by xiaotong-tj** [comment]
Thanks!
