### ISSUE TITLE
Firefox desktop non-AMP site redirects to AMP version of page (other browsers don't)

### ISSUE THREAD

**Issue by ro2ni3** [ampproject/amphtml#18594]
## How do we reproduce the issue?

Open Firefox Quantum and navigate to https://www.comparethemarket.com/car-insurance/ (a non AMP page)
You will notice that you will get redirected to the AMP equivalent page.
If you do this from other browsers, the redirect never takes place and the proper desktop page is loaded.

## What browsers are affected?

Firefox Quantum 62.0.3

## What browsers are NOT affected?

Google Chrome 69.0.3497.100, 
Safari 12.0, 
Internet Explorer 11 (11.0.9006.19129)

## Which AMP version is affected?

Version 1810052220151

**Comment by aghassemi** [comment]
@ro2ni3 Very interesting! Unfortunately I am not able to reproduce. Going to https://www.comparethemarket.com/car-insurance/ in FF Quantum 62 on Mac desktop, does not take me to the AMP page.

Few things to check on your side:
1- Do you have an AMP extension install in FF that might be doing that?
2- If you own the server, could be redirecting based on some cookie or IP that may have been setup for testing?
3- Could it be caching? was https://www.comparethemarket.com/car-insurance/  even pointing to AMP version that may have gotten cached?

**Comment by ro2ni3** [comment]
Ahha!, it was the extension yes. I feel stupid now.
The setting to load AMP pages automatically is selected by default.
![screen_shot_2018-10-09_at_09_10_22](https://user-images.githubusercontent.com/32260852/46655391-6d614880-cba3-11e8-8665-1a24398ade17.png)

**Comment by aghassemi** [comment]
Good to know. Thanks for sharing your finding.
