### ISSUE TITLE
Non-iframe social sharing components

### ISSUE THREAD

**Issue by tmdoit** [ampproject/amphtml#18607]
**Why?**
Because many business websites are just created once and not updated once (year in footer doesn't count).
Business lives in social services like Facebook, Twitter, Instagram etc. There are daily updates. With social AMP components we could treat social services as CMS for our content ie. facebook-event, facebook-post, twitter-message, instagram-post, youtube-video etc. 
What if those websites could take advantage of AMP with components which could make them visible for google search or for other search engines?

**Why?**
Because for now this make sense, business don't have to change its tools or behaviour to deploy the AMP version of website to take its all advantages.

Edited:
Now I'm thinking that making those websites alive (visible by search engines) could promote PWA Apps - I think every company wants to have contact with its clients, why not use AMP with PWA.
**AMP with PWA could be a next new website for every business.**

**Comment by choumx** [comment]
I'm not quite following. Can you explain the social network integration with AMP a bit more? 

/cc @ericlindley-g

**Comment by tmdoit** [comment]
@choumx content of social amp components is not visible for crawlers because it's in iframe. 
I do some research and see that Facebook plugins cat only be attached to website in iframe. To make them visible for crawlers, the only way is to do custom components talking directly to FB API.

**Comment by choumx** [comment]
Got it, thanks. This seems like a very large task since it would involve writing and maintaining custom client libs for each of these social networks. I'm not sure we have the bandwidth to take this on. 

Is this something you're interested in working on?

**Comment by tmdoit** [comment]
Probably yes, I'll be back here when I make https://github.com/ampproject/amphtml/issues/18459.

**Comment by aghassemi** [comment]
iframe or not is not an issue for crawlers (the good ones run JS anyway). Majority of 3P embeds have some JS SDK that we have to run in an isolated iframe for security anyway. Few simpler ones like `pinterest` we render ourselves. . 👍 having more 3P components such as https://github.com/ampproject/amphtml/issues/18459
