### ISSUE TITLE
Fallback for UCWeb mini or any browser without web component support?

### ISSUE THREAD

**Issue by mohitmayank** [ampproject/amphtml#1861]
http://caniuse.com/#feat=custom-elements

**Comment by rudygalfi** [comment]
@dvoytenko Can you speak to our fallback support and whether this needs to be addressed?

**Comment by dvoytenko** [comment]
We employ polyfills for platforms where custom elements are not supported. This set currently includes iOS Safari.

**Comment by jridgewell** [comment]
Can this be closed?
