### ISSUE TITLE
Documentation on how to style amp-list

### ISSUE THREAD

**Issue by nasearle** [ampproject/amphtml#18619]
## What's the issue?

There's no documentation on how to style the content fetched by amp-list.

## How do we reproduce the issue?

I wanted to put items fetched by amp-list into a grid, but found that styling the amp-mustache `<template>` itself does nothing. I couldn't find any information in the documentation, but I eventually found [this example on github](https://github.com/ampproject/samples/tree/master/amp-tube) that solves the problem using the following code:

```
amp-list div[role="list"] {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    grid-gap: 0.5em;
} 
```

If this is the recommended method for styling amp-lists (into a grid or flexbox) it would make things easier for developers if it was in the documentation somewhere.

**Comment by cathyxz** [comment]
Thank you for filing the issue! =) I'm currently on vacation, but happy to fix this in about a week if nobody beats me to it.

**Comment by CrystalFaith** [comment]
Thanks for filing - I've sent up a fix!
