### ISSUE TITLE
Intent-To-Implement adding UpScore to the analytics vendors list 

### ISSUE THREAD

**Issue by suransandi** [ampproject/amphtml#18626]
Hi all,

We'd like to add UpScore to the analytics vendors list,
[www.upscore.com](url)

Objective
Add configuration tag for UpScore.

Overview
PR to follow shortly including implementation.

Proposed Vendor Configuration

```
<amp-analytics type="upscore">
<script type="application/json">
{
  "vars": {
    "object_id": "foo",
    "object_type":"bar",
    "section":"sport",
    "author":"john suran",
    "creator":"john suran",
    "domain":"clientDomain",
    "pubDate":"01/01/0001"
  }
}
</script>
</amp-analytics>
```

Unfortunately, the first Intent-To-Implement issue was opened accidentally by my private git account, so I am referencing it here #18529.

**Comment by torch2424** [comment]
Sounds good! Thanks for making the Intent-To-Implement 😄 

I assume you saw it, but please feel free to refer here to our vendor integration doc if you need any help: https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/integrating-analytics.md

Thanks!

**Comment by torch2424** [comment]
This has been merged and resolved. Closing... 😄
