### ISSUE TITLE
Provide a way to notify the viewer of an AMP Story about new content

### ISSUE THREAD

**Issue by ow** [ampproject/amphtml#18624]
Hey! I'm using AMP's latest build and one big issue I have is my stories tend to develop over time. For example, I've covered events with them or breaking news. Users have really enjoyed the format and I'm planning to implement paywalled versions -- but the largest complaint by far is that the user needs to do an F5 to see if there's new content.

It seems lime `amp-live-list` could be a candidate to make that happen if it were allowed to be a sibling of the amp-story body, but it isn't. Really want I need is a way to check the server and _tell_ them to refresh, which would be adequate. Under today's rules that doesn't seem possible? 

Examples:

https://char.gd/story/live-from-microsofts-surface-event
https://char.gd/story/live-from-googles-pixel-3-event-in-new-york-city

**Comment by newmuis** [comment]
Yep, `amp-live-list` seems like the right way to tackle this.  Sounds perfectly reasonable; we'll need to see when we can have the bandwidth to implement it.

**Comment by ow** [comment]
Amazing! The other one I'd love to see implemented is the extension of `<amp-install-serviceworker>` to be able to embed the notification subscription button from AMP Stories. I discovered during my first two stories that people wanted to check in when it started, or something notable happened, but there was no way to reach them to tell them the content was there.

**Comment by newmuis** [comment]
Also perfectly reasonable; this should just be whitelisted as a direct child of `amp-story`.

**Comment by ow** [comment]
Right on. I'm not sure I'm best placed to help directly, but if I can help somehow just let me know how.

**Comment by ithinkihaveacat** [comment]
@ow Re notifications, how were you hoping this would work? I don't quite see how all the pieces will fit together… (I could be missing something, but as far as I can tell there's a few more steps to this beyond `<amp-install-serviceworker>` (e.g. `<amp-web-push>` also needs to be available)--don't want you to get your hopes up prematurely!)

**Comment by ow** [comment]
Yeah, I would also need amp-web-push support here, but didn't realize it
wasn't a package deal. Basically:

- Offer the user to notify them of new content
- Install service worker if consent given
- Send limited web push when relevant to user (or beyond, one day, would be
useful: i.e SMS via twilio). I could implement this on the CMS side with a
checkbox, in theory.

I've now run three of these during events and the resounding feedback is
great, but it needs a nudge when you're adding new stuff or the event
begins or it's useless. As a format, Stories seems to shine when used to
document something as it's happening as well as retrospectively.

Let me know what you think, or if I should provide more information.
- O

**Comment by ithinkihaveacat** [comment]
Perhaps the obstacles are not as daunting as I first thought, but it's not a sure thing:

1. `<amp-web-push>` needs to be allowed in AMP Stories. (Mandatory, though trivial.)
2. It needs to be possible to trigger the `<amp-web-push>` [subscription flow](https://documentation.onesignal.com/docs/amp-web-push-setup#section-4-set-up-your-widget) from a story. The story runtime swallows pretty much all taps, swipes, etc.--the only exception is the [`<amp-story-cta-layer>`](https://www.ampproject.org/docs/reference/components/amp-story#amp-story-cta-layer), so you'll need to use that. Combining these two components should just work, but I haven't tried it.
3. For the live update use case, `<amp-live-list>` or similar needs to be available.

Note that service workers are also not installed when pages are viewed from the cache; this will only work on origin.

**Comment by psdtomanythings** [comment]
+1 for this feature.

**Comment by ow** [comment]
Hey! I'm really investing in this right now as a part of a new product. Is there any interest in implementation? Can I help guide this in any way or provide feedback?

**Comment by newmuis** [comment]
@ow It's definitely on the list, and tentatively seems like something we can get to early on in the new year.  If you're willing to help contribute code, that would be a wonderful addition, but I also certainly understand that's not for everyone.

**Comment by newmuis** [comment]
This is being implemented right now as #21714!
