### ISSUE TITLE
amp-pinterest change reference to "Pin it" to "Save" in code

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#18648]
Since Pinterest has now changed their "Pin it" button to read "Save" we should change references to the former in the code.

Note that we don't want to change `data-do` to `"buttonPin"` as that would be a breaking change.

Announcement: https://newsroom.pinterest.com/en/post/the-pinterest-save-button-goes-global

**Comment by caroqliu** [comment]
> Note that we don't want to change data-do to "buttonPin" as that would be a breaking change.
data-do references "buttonPin" in a couple places already; do you mean we don't want to change data-do from "buttonPin" to anything new?
