### ISSUE TITLE
Cherry pick #18666 to canary #18649

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#18667]
**Replace *everything* in angle brackets in the title AND body of this issue.  If you have any questions see the [cherry pick documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-picks).**

**PR that you are requesting a cherry pick for:**

*(Put N/A if you do not yet have a PR with a fix; edit this issue to add it when the PR is ready.)*

PR #18666

**Release(s) you requesting this cherry pick into:**

*Release issues can be found at https://github.com/ampproject/amphtml/labels/Type%3A%20Release*

*If you are requesting a cherry pick into a production release you will most likely need to cherry pick into canary as well, otherwise when the canary is pushed to production your fix will be lost.  See the [cherry pick documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-picks).)*

Production Release? <NO> 

Canary release? <YES>  If yes, Type: Release Issue #18649

*Why does this issue meet the [cherry pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?  Be specific.*

This is an urgent feature requirement from AliExpress (one of the largest canonical AMP adopters). The feature they need to rush out relies on this trivial change. Having it in canary this week and prod next week gives time for them to fully test out their feature. 

*Assign this issue to the current TL (cramforce) if you have permission to, otherwise leave this cc line in.*

/cc @cramforce

**Comment by cramforce** [comment]
I'm not a fan of this. But if release on-duty volunteers to make the extra release it is fine with me.

We have a process for a reason that consistently delivers new features in a 2 week timeframe.
