### ISSUE TITLE
Dev-channel - AMP Dev Channel (more info) - Canary is down

### ISSUE THREAD

**Issue by leonalicious** [ampproject/amphtml#18677]
The current `dev-channel | AMP Dev Channel (more info)`option from `https://cdn.ampproject.org/experiments.html` is down, appreciate your guys help on this.

**Comment by jridgewell** [comment]
This is the second report we’ve gotten on this. @jgluk

**Comment by jgluk** [comment]
The dev channel should be fixed now.

**Comment by jridgewell** [comment]
Confirmed. Thank you for alerting us.
