### ISSUE TITLE
Use 'amp-carousel' Tag in AMP stories.

### ISSUE THREAD

**Issue by enzo77** [ampproject/amphtml#18681]
Hi!!
Thanks in advance,
Can I use the 'amp-carousel' in my Amp stories project?
My project works fine when I use this tag 'amp-carousel'  but in the console Chrome show some errors , like: 
'The tag 'amp-carousel', a child tag of 'amp-story-grid-layer''

Are there ways of implementing that?
Thanks, 
Enzo

**Comment by newmuis** [comment]
Hi @enzo77, currently `amp-carousel` cannot be used within `amp-story`.  I will leave this open and assign it to myself to at document a plan to provide support for it.

**Comment by enzo77** [comment]
Thanks!
Enzo

**Comment by newmuis** [comment]
Closing this in favor of #16522, which aims to serve as a roadmap for all components being integrated with `amp-story`.
