### ISSUE TITLE
amp-state: Support "refresh" action (like amp-list)

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#18684]
If you have an `amp-list` which is initially hidden and then is unhidden by `amp-bind`, then the `refresh` action does not trigger a network call.
Sample here: https://amp-demos.glitch.me/amp-list-empty.html

- click on the first button
- then click on "HERE" where it says "Click here to refresh the page" and notice the network calls by opening Chrome Console. None is made.
@choumx FYI

**Comment by choumx** [comment]
Ah, this is because the `amp-list#ticket-info-amp-list` doesn't have a `src` attribute, so from its point of view there's nothing to fetch or refresh.

What we want in this case is to refresh the `amp-state#ticketInfo`. `amp-state` currently doesn't support a similar "refresh" action -- we can add it.

**Comment by choumx** [comment]
A long-term "data source" abstraction (#16602) will help make this type of usage easier.

**Comment by kul3r4** [comment]
do you mean 
```
<amp-state id="ticketInfo" src="https://amp-demos.glitch.me/amp-list-empty.json">
</amp-state>
``` 
would become 
```
<amp-state id="ticketInfo" [src]="https://amp-demos.glitch.me/amp-list-empty.json?RANDOM" src="https://amp-demos.glitch.me/amp-list-empty.json">
</amp-state>
``` 
?

**Comment by choumx** [comment]
Actually we need the expression value to change each time too. So something like this:
```html
<amp-state id="ticketInfo" 
    [src]="'https://amp-demos.glitch.me/amp-list-empty.json?ignore=' + foo" 
    src="https://amp-demos.glitch.me/amp-list-empty.json">
</amp-state>

<button on="tap:AMP.setState({foo: foo + 1})>Refresh #ticketInfo</button>
```

Makes sense?

**Comment by kul3r4** [comment]
thanks! Can you take a look at the updated version of https://amp-demos.glitch.me/amp-list-empty.html?

**Comment by choumx** [comment]
I think you want to move the `AMP.setState` to the `<a>` tag:

```html
<!-- Replace this. -->
<a on="tap:ticket-info-amp-list.refresh">here</a>

<!-- ...with this. -->
<a on="tap:AMP.setState({foo: foo+1}">here</a>
```

**Comment by kul3r4** [comment]
thanks!

**Comment by kul3r4** [comment]
I noticed that when resolving [src] for `amp-state` I get an error when I am in localhost and the URL looks like: http:localhost:8080..., this may be a limitation for local development
