### ISSUE TITLE
Intent-to-Implement Poool amp-access extension

### ISSUE THREAD

**Issue by dackmin** [ampproject/amphtml#18699]
Hey,

We would like to add Poool (https://poool.fr/en) as a new amp-access extension.

The corresponding PR will follow :)

Cheers,
Ugo.

**Comment by jpettitt** [comment]
I'd strongly recommend you implement it as a service under `amp-subscriptions` (the same way as `amp-subscriptions-google`).  The reasoning is that amp subscriptions uses a well defined set of attributes to manage paywalled content. Those attributes are recognised by apps like Google news.

In addition should the publisher choose to integrate `amp-subscriptions-google` it will make that task much easier.
