### ISSUE TITLE
amp-position-observer: Ability to capture vertical scroll for a certain time

### ISSUE THREAD

**Issue by pbakaus** [ampproject/amphtml#18696]
Hi all,

we're currently designing and developing a use-case driven long form article demo page to highlight on our site, and the goal of the article is to really showcase that AMP can do full featured, art-directed articles.

A lot of the parallax animations require "capturing" the vertical scroll, where you continue to scroll, but what changes is just the fixed animation on screen, similar to how things are done in this article: https://highline.huffingtonpost.com/articles/en/poor-millennials/

A couple questions then:

a) I know this isn't universally loved, and I think we at some point said it's part of our philosophy not to hijack natural scroll. Is that still accurate? Would we make compromises for UX features that are clearly trending?
b) Is this even technically feasible, thinking about the situation where AMP is running in a viewer? I was thinking that in the worst case, we could technically continue to scroll the page, but keep the element anchored on screen for a while...but that would likely cause issues if you want to jump ahead via anchors etc..

Thoughts?

/cc @aghassemi @sebastianbenz

**Comment by ericlindley-g** [comment]
Ali and I chatted about this feature this morning, and I actually just filed a master feature: https://github.com/ampproject/amphtml/issues/18706  In fact, I used that exact article as a reference :)

**Comment by aghassemi** [comment]
Closing in favor of master feature.

I've been thinking about a good technical solution for this in the past and have some ideas to share later. Excited to work on this.
