### ISSUE TITLE
Scroll-freeze effect

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#18706]
Highly interactive documents on the web often employ a "scroll-freeze" effect, where scrolling the page temporarily stops in order to display a scroll- or time-bound animation. This activity implements this feature in AMP in such a way that it avoids common UX issues with this pattern (for instance, when the user feels "trapped" due to performance issues or unclear feedback when scrolling the page)

## Name suggestions
- `amp-scroll-freeze`
- `amp-pin-scroll`
- `amp-sticky-scroll`
- `amp-sticky-view`
- `amp-pin-view`
- `amp-sticky-page`
- `amp-pin-page`

**Comment by aghassemi** [comment]
/cc @pbakaus @sebastianbenz 

For naming, for now we went with scroll-freeze. Anyone knows what these are called in the wild? Another option: sticky-scroll?

**Comment by aghassemi** [comment]
Added a name suggestion section to the description.

**Comment by pbakaus** [comment]
This page is also a good fit: https://www.apple.com/apple-music/

After talking to @spacedino, I think one thing that became clear is that ideally, the technical implementation wouldn't entirely override native scroll, but would utilize it, and simply anchor an element in place. Both the page above and the Genoa bridge page do this.

**Comment by aghassemi** [comment]
(tangent: I think most of these might be already possible with a combination of amp-position-observer, amp-animation, CSS - specially position:sticky - and amp-fx-flying-carpet. My plan is to prototype these instead of trying to create a new API initially)

**Comment by aghassemi** [comment]
this is now verified doable with position sticky, position observer and animation: https://amp-article.herokuapp.com/ 

We can of course make this easier. Leaving the FR open.
