### ISSUE TITLE
amp-facebook-comments with wrong width

### ISSUE THREAD

**Issue by MtDalPizzol** [ampproject/amphtml#18709]
## What's the issue?

The amp-facebook-comments width doesn't work as expected. It should fill the container's width when using `layout="responsive"` but it gets stuck around 220px.

## How do we reproduce the issue?

This is happening even in the [AMP by example](https://ampbyexample.com/components/amp-facebook-comments/) page.

## What browsers are affected?

Not sure, but I can see this on Chrome for Linux (Mint 17), Chrome for Windows and Chrome for Android.

## Which AMP version is affected?

v0

**Comment by aghassemi** [comment]
yikes :(  https://developers.facebook.com/support/bugs/173395380238318/  

Pinged the FB bug thread about this. Hopefully gets fixed soon.

**Comment by thanhsr** [comment]
After 1 hour of research I modified it by replacing width='100'. 
It seems like 100=100%
`<div class='comments'>
<amp-facebook-comments data-numposts='10' expr:data-href='data:post.canonicalUrl' height='200' layout='responsive' width='100'>
</amp-facebook-comments></div>`

**Comment by NickInSpace** [comment]
I'm seeing this bug inconsistently - on around 30% of page loads. Also able to replicate in the AMP by example page, but so far only when logged into Facebook and in Chrome on Mac. It looks like the FB bug thread mentioned above has been closed.

**Comment by devignerforhire** [comment]
Any update on this one? I've noticed this behavior on our site lately. It generally works again after refreshing the page, but that's obviously not ideal. Here is a screenie -> https://drive.google.com/file/d/1N-HpGD5UolQDiH8J6sM7Ke9Oj65_8eIa/view?usp=sharing

**Comment by aghassemi** [comment]
I am not sure there is much we can do here. We are setting the correct FB params, rest is an FB iframe we don't control.

**Comment by kenyeung826** [comment]
Don't know whether is a correct way to do
This problem seems can be evaded by adding 
`<style>
        .fb_iframe_widget_fluid_desktop iframe{
            width: 100% !important;
        }
    </style>`
to remote.html
[https://amp.dev/documentation/components/amp-ad#running-ads-from-a-custom-domain](url)

**Comment by tazihad** [comment]
> Any update on this one? I've noticed this behavior on our site lately. It generally works again after refreshing the page, but that's obviously not ideal. Here is a screenie -> https://drive.google.com/file/d/1N-HpGD5UolQDiH8J6sM7Ke9Oj65_8eIa/view?usp=sharing

Hi. How did you fix this issue?

**Comment by kenyeung826** [comment]
> > Any update on this one? I've noticed this behavior on our site lately. It generally works again after refreshing the page, but that's obviously not ideal. Here is a screenie -> https://drive.google.com/file/d/1N-HpGD5UolQDiH8J6sM7Ke9Oj65_8eIa/view?usp=sharing
> 
> Hi. How did you fix this issue?

1. create your own frame.html (not a amp page) with <style> .fb_iframe_widget_fluid_desktop iframe{ width: 100% !important; } </style>
https://github.com/kenyeung826/amp_poc/blob/master/resources/views/amp/facebook/remote.blade.php

2. add <meta name="amp-3p-iframe-src" content="{{frame.html path}}">
https://github.com/kenyeung826/amp_poc/blob/master/resources/views/layouts/amp.blade.php
