### ISSUE TITLE
AdResizing gives strange values

### ISSUE THREAD

**Issue by renebaudisch** [ampproject/amphtml#1871]
I tried to change the dimensions of an iframe by using this methods:
https://github.com/ampproject/amphtml/tree/master/ads#ad-resizing

I'm sending a request for 320x50 to resize to 300x250.
After this i see the amp-ad container having a height attribute of 50200, while cssText still has "width: 320px; height: 50px;"

I then tried to sniff the code by break on nodes attribute changes and have been stoppen within layoutCallback() method.

There is a line where const newHeight is defined and some comments inline saying /*OK*/, and here my Chrome on Mac returns 50200. Since one has to define width and height by calling requestResize you never shouldn't have to calc the height here, isn't it? Sure, if responsive is set, but normally...

To reproduce, select the iframe "frame_doubleclick_1" already there in demointegration.
Then send window.context.requestResize('300','250') and the conatiner will get a height of 50200px...

**Comment by cramforce** [comment]
@sriramkrish85 please take a look.

**Comment by sriramkrish85** [comment]
looking now!

**Comment by sriramkrish85** [comment]
@renebaudisch do you have a link that i can see?

**Comment by rudygalfi** [comment]
@renebaudisch Can you provide a link that reproduces this issue?

**Comment by sriramkrish85** [comment]
![Here is what i see](https://cloud.githubusercontent.com/assets/1037311/13023781/01e0eb14-d1a1-11e5-9b4c-3d0be7b0da88.png)

**Comment by cramforce** [comment]
I figured out what is going on. Should have read the full bug report.

You need to send the sizes as numbers instead of strings. Yeah, type coercion.

`window.context.requestResize(300, 250)` works just fine.

I'm inclined to not make us robust against this mistake. That would just bloat the binary size.

**Comment by renebaudisch** [comment]
Both didn't work for me at the beginning, but since [this comment](https://github.com/ampproject/amphtml/issues/1871#issuecomment-182127349)
I also couldn't reproduce so everything's fine for me now.

**Comment by adtechnology** [comment]
Height is tested again and work's fine now, but width doesn't proceed till the end.
I'm calling `window.context.requestResize(320,50);` and the iframe itself is resized to 320/50 and height and width attributes of the amp-ad container also but the style looks like this:

`width: 300px; height: 50px;`

Width has not been actualized.
Please fix.

You can check out on:
[http://adtechs.de/demopages/bild/Kirchen%20unterstützen%20Merkels%20Flüchtlingspolitik.html](url)
