### ISSUE TITLE
amp-analytics calculates wrong scroll triggers for embedded shadow documents

### ISSUE THREAD

**Issue by peterjosling** [ampproject/amphtml#18735]
## What's the issue?
amp-analytics ScrollManager calculates scroll positions for scroll triggers based on the viewport scrollHeight/scrollTop. For shadow documents (e.g. in amp-next-page) this means it calculates the current scroll percentage from the entire parent document, even if the shadow document is off screen.

Scroll position should be calculated from the shadow document's body height instead, otherwise you will get completely different analytics behaviour when a document is embedded, vs when used standalone.

**Comment by torch2424** [comment]
The analytics team, ( @lannka @zhouyx @calebcordry ) and I decided that it would be good to re-think how we are doing scroll events, and decide what would be the expected behavior on this before we start implementing a solution.
