### ISSUE TITLE
getFormAsObject doesn't include <button> with name and value

### ISSUE THREAD

**Issue by zhangsu** [ampproject/amphtml#18745]
When submitting a form normally, if the form includes a `<button>` with `name` and `value` attributes, the name-value pair will actually be included in the form submission query string (or `multipart/form- data`). However, `getFormAsObject` doesn't seem to include <button> with name and value, which is not consistent with browser's default form submission behavior.

**Comment by aghassemi** [comment]
related: https://github.com/ampproject/amphtml/issues/16461 https://github.com/ampproject/amphtml/issues/15919

**Comment by cvializ** [comment]
I did some initial investigation. This is complicated by the fact that amp-form disables the submit buttons when it is submitting, making it difficult to tell which button to send with the request. Looking into solutions

**Comment by choumx** [comment]
Disabling submit buttons is also problematic re: #18285. Two birds?

**Comment by cvializ** [comment]
🐦🐧🗿
