### ISSUE TITLE
Scroll dependant header

### ISSUE THREAD

**Issue by aurbanczik** [ampproject/amphtml#18743]
Is there a plan to create a simple possibility for a scroll dependant header in AMP ?

Thanks 

Ales

**Comment by aghassemi** [comment]
Hi @aurbanczik 

Certain types of scroll depender headers are possible in AMP using `amp-position-observer`. Please take a look the the following two samples:

https://codepen.io/aghassemi/pen/WargXW (hides/shows the header after certain scroll point)
https://codepen.io/aghassemi/pen/GOEWEz (shrinks/expands the header after certain scroll point)

More information about the components used here can be found on: 

https://ampbyexample.com/visual_effects/basics_of_scrollbound_effects/

If these do not satisfy your use-case, please create a new issue with the UX you have in mind.
