### ISSUE TITLE
getFormAsObject includes an empty value even if no options are selected in both single and multi <select>

### ISSUE THREAD

**Issue by zhangsu** [ampproject/amphtml#18744]
`getFormAsObject` includes an empty value even if no options are selected in both `<select>` and `<select multiple>`, which is not consistent with actual form submission behavior. When submitting a form with a `<select>` or `<select multiple>` field, when no items are selected, the generate query string (or `multipart/formdata`) doesn't include a parameter with an empty value.

**Comment by aghassemi** [comment]
I believe this is fixed by https://github.com/ampproject/amphtml/pull/18710 

to @cvializ to confirm
