### ISSUE TITLE
the height of amp-list will be resized with some random height when user wants to navigate to another page 

### ISSUE THREAD

**Issue by leonalicious** [ampproject/amphtml#18759]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4065175/47023396-320ddd80-d192-11e8-823d-90ecb0901dee.gif)

Hi guys, we notice since the version released of v1810052256480, the height of amp-list will be resized with some random height when user wants to navigate to another page, can you please check on this ? appreciate your guys assistance on this 

to: @choumx @aghassemi

**Comment by leonalicious** [comment]
https://github.com/ampproject/amphtml/pull/18148
i think this is the PR who is causing the issue, hope it helps

**Comment by erwinmombay** [comment]
this should be in canary now
