### ISSUE TITLE
Hide equalizer icon if video has no audio tracks

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#18760]
Right now, `amp-video`'s equalizer icon is shown unless the `<amp-video>` tag is marked up with the `noaudio` attribute (or the equalizer is hidden by publisher CSS).

We should also hide the equalizer icon if the video has no audioTracks.  The [feature support](https://caniuse.com/#feat=audiotracks) for `audioTracks` is spotty, but it's a better experience for the browsers that do support it.

**Comment by aghassemi** [comment]
sgtm. so hide if `noaudio || forAll(video.audioTracks => !track.enabled)`

**Comment by newmuis** [comment]
yes, but I would also add `|| video.audioTracks.length == 0`

**Comment by alanorozco** [comment]
...and `&& video.audioTracks != (null|undefined)` for feature detection

**Comment by alanorozco** [comment]
(I initially thought this would be quick but I realize I have to back-fill all video extensions with `hasAudioTracks`. This might take a little longer.)
