### ISSUE TITLE
Validator error if extremely long boilerplate line is not byte perfect

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#1877]
I just updated to the latest boilerplate and it's breaking validation.

`http://localhost:8000/templates/amptemplate.html:8:4 The mandatory text (CDATA) inside tag 'boilerplate (js enabled)' is missing or incorrect. (see https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#boilerplate)`

I tracked it to the fact that I broke the lines in the `<style>` on ; to make the page easier to read, it seems even an extra space causes a validation fail.  I get that checking for a string match is far easier but now the boilerplate is 765 characters I suspect a lot of people are going to try and pretty print it in some way.  Is there a better way to enforce this?

**Comment by Gregable** [comment]
Thanks for the report. 

We've been working on a full CSS parser in javascript to allow for pretty much any formulation of this boilerplate, but it's not quite there yet.  For now we only have a fairly fragile regular expression that _tries_ to account for whitespace.

I couldn't find a separate github issue for this, so leaving this open to track progress.

**Comment by dandv** [comment]
Is this issue causing this block to fail (not the space after the opening `{`)?

```
<style amp-boilerplate>body{ -webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style>
```

After deleting the space, validation passes.

The validation error message could be a lot more helpful... confused one partner today at I/O.

**Comment by jridgewell** [comment]
Re: https://github.com/ampproject/amphtml/issues/2369#issuecomment-190954736t

**Comment by poscar** [comment]
This issue is also affecting us. The following fails to validate:
```
    <style amp-boilerplate="">
      body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}
    </style>
    <noscript>
      <style amp-boilerplate="">
        body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}
      </style>
    </noscript>
```

is there an ETA for a fix?

Thanks!

**Comment by cramforce** [comment]
@Gregable any chance boilerplate validation could be switched to use the CSS parser instead?

**Comment by Gregable** [comment]
Yes, we'd like to do that eventually, but for now I think some tweaks to the regexp are a more appropriate solution. @powdercloud has just added a few updates which should help when they roll out.

**Comment by powdercloud** [comment]
@poscar's version works now.
@dandv the space after { is still not allowed.
The criterium I used for what's allowed and what isn't is to take the original boilerplate and make a regex that allows arbitrary whitespace where whitespace is *required*, plus whitespace for putting the CSS on a seperate line, the way html5 tidy wants to do it (as documented by someone in #2369). This keeps the regexes relatively simple. Simpler regexes are more difficult to get wrong and they're also more efficient.
I have a hunch that we can address some of the problem with the pickiness by improving the documentation, e.g. with https://github.com/ampproject/amphtml/pull/3273 and I'll make one more that will add a comment to the boilerplate file in Github.

**Comment by Gregable** [comment]
The recent improvements to whitespace allowances for these variants seem to resolve most issues people are running into. Supporting arbitrary css variants reduces performance, which we are trying to control, so I'm going to close this for now. If folks run into specific variants that are difficult to work around, let me know and we can revisit.

**Comment by tania0339** [comment]
I've been trying to have my pages validated for 2 weeks, making attempts every day! 
I really don't know what's wrong with my "amp-boilerplate" portion of code.. As far as I can see there are no invalid spaces in between...
One example of page is http://www.fantagazzetta.com/amp/approfondimenti/racconti/29_09_2016/fantaracconti---vincere-grazie-a-bruno-fernandes-all-86-232667#development=1 
The Console validation in browser is successful but in the webmaster tools > Accelerated Mobile Pages I have something like one thousand pages with the  MANDATORY_CDATA_MISSING_OR_INCORRECT for the tag tag "noscript > style[amp-boilerplate]" error!

The only thing that I can see in my html, now, is that there are no white lines before and after the "amp-boilerplate" portion of code.. can this affect somehow your regexp validation result? That's a huge waste of time and it's also frustrating.. I hope you can help me out.

**Comment by Gregable** [comment]
Your page is valid. Search Console lags behind due to crawl delays, but will eventually be correct.

You can see your document in the AMP Cache, which wouldn't be possible if it wasn't valid:
https://cdn.ampproject.org/c/www.fantagazzetta.com/amp/approfondimenti/racconti/29_09_2016/fantaracconti---vincere-grazie-a-bruno-fernandes-all-86-232667

**Comment by tania0339** [comment]
OK! I can see more valid pages also in the search console now. Thanks!
