### ISSUE TITLE
Form POST fails due to 'referer' header wrongly set in the AMP cache

### ISSUE THREAD

**Issue by ro2ni3** [ampproject/amphtml#18778]
## What's the issue?

When submitting a form to the endpoint specified in the action-xhr attribute, it will fail with a 403 at the client, and will not even hit the endpoint.
I have noticed that if I override the request header named ‘Referer’ to blank or https://www.travelsupermarket.com (Using the chrome extension ModHeader), then the form successfully submits and I get redirected to the results page.

It might be easier to understand what is happening by watching this video of my screen I recorded: https://drive.google.com/open?id=19r5zUu4fNZ_rTBKe561L9A_Fv-T2UNej
You can try this from this page:
https://www-travelsupermarket-com.cdn.ampproject.org/c/s/www.travelsupermarket.com/en-gb/holidays/amp/portugal/algarve/
 
This is not a CORS issue, and we believe it is an issue with something AMP is doing with the Referer request header.
We have tried different possible workarounds by changing the referer policy with the meta tag but this has not worked properly.
Incidentally we have other components on the same page that are hitting external APIs (GET requests) and they all work.

On the same page linked above, the autocomplete in the 'Holiday destination' works and the deals in the carousel shown lower down the page work as well (These two are hitting external API endpoints). So the Search button not submitting the form is **NOT** a CORS issue.

## What browsers are affected?

All browsers

## Which AMP version is affected?

1810152207300

**Comment by aghassemi** [comment]
@ro2ni3 Are your Search and other endpoints running on different server configurations? My guess is there is a top layer on your server stack rejecting requests if referrer does not match origin.

post xhr-action seems to work fine in AMP Cache for AmpByExample pageshttps://www.google.com/amp/s/ampbyexample.com/components/amp-form/   (view in mobile UA)

**Comment by ro2ni3** [comment]
Thanks for your reply @aghassemi. This was indeed a problem within our stack. We have solved the issue now.
