### ISSUE TITLE
Run tests in Chrome Dev as well.

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#18784]
We should run our unit and functional tests on Chrome Canary in addition to latest Chrome. 

This will help catch issues such as #18777 a few weeks earlier.

/to @rsimha

**Comment by estherkim** [comment]
@rsimha @aghassemi Is it okay to change this from Chrome Canary to Chrome Dev? Reason being that Sauce Labs understandably doesn't support Chrome Canary (daily releases) but supports Chrome Dev (weekly releases).

**Comment by rsimha** [comment]
I see. Yes, running on Chrome dev will still work as an early-warning system for features that might break on Chrome.

**Comment by rsimha** [comment]
In addition, it would be nice for our existing Sauce labs configs to always target the latest stable version of Chrome. (We currently target specific version numbers, which can get old, and need manual updates.)

**Comment by estherkim** [comment]
Makes sense. Sauce Labs supports `version: latest` so I'll include that.

**Comment by aghassemi** [comment]
Yay 🎉 Thank you!

**Comment by rsimha** [comment]
Sorry, the code merged today adds Chrome Dev to our list of platforms, but we'll need a follow up PR from @estherkim to enable it and weed out any new failures. Coming up soon!
