### ISSUE TITLE
Add Support for an Auth Token to be attached to Remote Requests via POST body

### ISSUE THREAD

**Issue by hellokoji** [ampproject/amphtml#18787]
## Motivation

Currently, there is no way to obscure sensitive data given to a remote server. For amp-state, amp-list, and amp-form, the current available solution is to pass credentials via URL substitution, but these credentials within the URLs could be logged or difficult to remove after the fact.

## Requirements

- The capability to pass an auth token with remote requests
- Able to obscure the auth token by not allowing the token to exist within the URL via URL substitution

## General Design

To be merged with https://github.com/ampproject/amphtml/issues/15195. The I2I mentions an `IDENTITY_TOKEN`. This token would instead be added to the request body, and will force a POST request.

To trigger this feature, a new attribute `cross-origin=”amp-viewer-auth-token-via-post”` can be added to any of the \<amp-state\>, \<amp-list\>, or \<form\> (with amp-form) elements. Within each of these elements, the request will be transformed to include the auth token in a POST body.

### Amp-State and Amp-List Implementation

- Each extension will check for `cross-origin=”amp-viewer-auth-token-via-post”`
- If present, check for the viewer assistance service and grab auth token.
- Pass auth token to new function `batchFetchJsonAuth` which includes an additional auth parameter
- The request will be constructed as a POST request with a request body with content type `application/x-www-form-urlencoded`

Example implementation:
```
<amp-state id="myRemoteState" src="https://data.com/articles.json" 
     cross-origin=”amp-viewer-auth-token-via-post”>
</amp-state>
```
Will yield a request body of:
```
ampViewerAuthToken=AUTH_TOKEN_FROM_VIEWER_ASSISTANCE
```

### Amp-Form Implementation

- Extension will check for `cross-origin=”amp-viewer-auth-token-via-post”`
- If present, check for the viewer assistance service and grab auth token.
- An additional `ampViewerAuthToken` field will be added to the `multipart/form-data` payload

Example implementation:
```
<form id="name-form"
    method="post"
    target="_top"
    action-xhr="https://data.com/formsubmit"
    cross-origin="amp-viewer-auth-token-via-post">
  <div class="form-header">Full Name</div>
  <input type="text"
      name="name"
      value="Default name value"/>
  <button type="submit">
    <span class="order-button-text">Submit Name</span>
  </button>
</form>
```
Will yield a request payload of:
```
--------formDataBoundary--------
Content Disposition: form-data; name="name"
Default name value
--------formDataBoundary--------
Content Disposition: form-data; name="ampViewerAuthToken"
AUTH_TOKEN_FROM_VIEWER_ASSISTANCE
```

**Comment by hellokoji** [comment]
Yes, this will be pushed with #15195 .

**Comment by cathyxz** [comment]
Is there any chance we can extend this functionality to allow generally fetching data with `POST` requests, e.g. to support endpoints like GraphQL?
