### ISSUE TITLE
Intent-to-Implement: EPICA

### ISSUE THREAD

**Issue by abiaskosty** [ampproject/amphtml#18808]
We would love to add [EPICA](https://www.epica.ai/) as an amp-analytics plugin.

A simple example that sends a pageview:
```html
<amp-analytics type="epica">
<script type="application/json">
{
  "vars": {
    "writeKey": "abcde1234",
    "name": "Page title"
  }
}
</script>
</amp-analytics>
```

**Comment by zhouyx** [comment]
@abiaskosty Please! Feel free to open a Pull Request and ping us for review. https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/integrating-analytics.md

**Comment by jeffjose** [comment]
Thanks for the Intent to Implement, @abiaskosty! Looking forward to our PR. And meanwhile if you have questions, please dont hesitate to ping here.

Cheers!
