### ISSUE TITLE
✨ Add type recomad for the amp-ad tag

### ISSUE THREAD

**Issue by kimhogeling** [ampproject/amphtml#18804]
## What's the feature request?

Websites that integrate the _recomAD_ widget also have an AMP Version of the site. To offer them our _recomAD_ widget _we_ would like to implement the type `recomad` for the `<amp-ad>` tag.

It would look like this:
```html
<amp-ad
  type="recomad"
  width="XXX"
  height="YYY"
  data-app-id="YOUR_APP_ID"
  data-widget-id="YOUR_WIDGET_ID"
  data-origin="YOUR_CANONICAL_LINK_OF_YOUR_ORIGINAL_PAGE"
  data-search-term="YOUR_SEARCH_TERM"
  data-puid="YOUR_TRACKING_ID_FOR_YOUR_USER"
></amp-ad>
```

The widget uses our product search with help of the given `data-search-term` to recommend buyable products that match the content of the website.

For more information, please visit [https://recomad.de](https://recomad.de)

### User Id
With help of the user id the product search result is made more fitting for the user.

### Impression tracking
To understand how many times the _recomAD_ widget has been seen, we collect anonymous data by firing an AJAX request to `/trackAdImpression`. It contains the search term and origin of the page.

### Click tracking
Also the clicks are tracked via a tracking pixel. This contains information about the clicked product.

## Example of the widget

The widget is build with web performance in mind and it is responsive for smaller mobile displays. Here is an example [https://widget.s24.com/preview/recomad-portrait](https://widget.s24.com/preview/recomad-portrait)

**Comment by torch2424** [comment]
Awesome, I'll bring this up to the rest of the team, thanks for opening the PR at #18736 as well 😄

**Comment by torch2424** [comment]
Left a review on the PR we can discuss there 😄

**Comment by torch2424** [comment]
Closing, PR #18736 was merged 😄
