### ISSUE TITLE
Add Google Charts support

### ISSUE THREAD

**Issue by ghelapratik** [ampproject/amphtml#18830]
Graphs are a great visual tool to display data. Enabling Google Charts support for AMP Stories can give a great boost towards displaying data in the slides, for use cases like annual reports, data driven application, statistics based news and much more.

**Comment by newmuis** [comment]
I don't think we would want this to be stories-specific in any way; if we were to implement this, I would imagine it would just be an AMP component that is usable either in standard AMP documents or in stories.

/to @aghassemi

**Comment by newmuis** [comment]
Actually, I was confused what Google Charts is 😄 

Turns out, you can just get an image URL and use it with `<amp-img>`.  Here's an example of doing that in an `<amp-story>`: http://jsfiddle.net/adnc8p7h/

@psdtomanythings feel free to reopen if you feel this does not adequately address your issue.

**Comment by newmuis** [comment]
Okay, I now see that the image chart API is deprecated 😑 

Back to my original answer!  If you want something in the meantime, it does look like there are various image-based chart APIs available.

**Comment by typpo** [comment]
For what it's worth: I run the [QuickChart](https://github.com/typpo/quickchart) project, a static chart renderer that generates images from Chart.js configs.  This allows you to embed static Chart.js charts in AMP.  

It also includes a [partial reimplementation](https://quickchart.io/documentation/migrating-from-google-image-charts/) of the deprecated Google Image Charts API as well as a server-side [Google Charts rendering endpoint](https://quickchart.io/documentation/google-charts-image-server/).  You can use these tools to create non-interactive chart images using your preferred charting library in AMP.

**Comment by ghelapratik** [comment]
@typpo - Great. But we need it in AMP Stories. So, even if QuickChart is supported in AMP, the stories working group needs to enable support for web stories. 

@newmuis - Is this possible ?

**Comment by newmuis** [comment]
If I'm understanding correctly, the output here is just an image, so yes, it could be embedded in a story the same way as any other image.

**Comment by jaygray0919** [comment]
Can we run an `amp-iframe` in `amp-story`?

**Comment by newmuis** [comment]
No, `amp-iframe` is not allowed in `amp-story`, and, with all likelihood, will never be allowed within the page itself, given that it's impossible to control or understand the user experience within the iframe.

What would you want to use it for?

**Comment by jaygray0919** [comment]
Run D3.JS instances. We run those in an iFrame now on an amp-page. It's the only realistic way of running non-amp services, of which chart.js and similar are examples, on an amp-page. We have tried and failed several times to adapt our d3.js instances in amp-script. So if we have interesting data animated using libs such as d3.js, we can't run those in amp-story. Our work around: show a PNG and then link to the page that runs the d3.js.
