### ISSUE TITLE
amp-story: Animations starting before the slide / page comes into the front

### ISSUE THREAD

**Issue by psdtomanythings** [ampproject/amphtml#18855]
** Only on Desktop **

At the moment, while viewing the story in desktop, elements starts animating even before they come into the front . Below is the image of same. 

![my-story](https://user-images.githubusercontent.com/22929187/47256041-1ad33680-d497-11e8-8d2a-f1751a48f31a.gif)

Can we please make sure that animation starts only after the page has already slid to  centre.

**Comment by newmuis** [comment]
@gmajoulet do you mind taking a look?

**Comment by newmuis** [comment]
Actually, unless the story you're viewing is served from the cache, you'll need to enable the `dev-channel` experiment locally, by executing `AMP.toggleExperiment('dev-channel', true);` in your JavaScript console and refreshing the page.

**Comment by newmuis** [comment]
I agree that this user experience actually ends up being better, since it allows for seamless media playback.  Closing this, since the behavior is intended; feel free to reopen if there are further considerations that should be taken into account.
