### ISSUE TITLE
Q$$module$third_party$closure_library$sha384_generated is not defined at Q 

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#18851]
Error: Q$$module$third_party$closure_library$sha384_generated is not defined at Q (https://raw.githubusercontent.com/ampproject/amphtml/1810191936340/third_party/closure-library/sha384-generated.js:11:555) at https://raw.githubusercontent.com/ampproject/amphtml/1810191936340/src/custom-element.js:1387:8 at https://raw.githubusercontent.com/ampproject/amphtml/1810191936340/src/service/viewport/viewport-impl.js:1108:30

**Comment by erwinmombay** [comment]
actually after talking to @jridgewell this happened on a patch and the code differed just from the cherry-pick. will keep digging

**Comment by jridgewell** [comment]
Confirmed it's only present in `amp-crypto-polyfill-0.1.js` binary, in versions `1810171544580` and `1810191936340`.

**Comment by choumx** [comment]
Saw a similar bug for `node_modules/` dependencies when that folder was added to `js_module_root`. 

Looks like third_party also affected -- CJS `module.exports` possibly silently borked with `module_resolution: 'NODE'`. Quick survey shows that vega and d3 might also be impacted.

**Comment by choumx** [comment]
Vega and D3 are not affected since they're injected manually instead of imported through JS. Some follow-ups:

1. Add integration test for amp-crypto-polyfill.
2. New lint rule banning `module.exports` in JS-bundled sources (e.g. src/, extensions/, third_party/).

Other ideas welcome!
