### ISSUE TITLE
Sticky ads hidden in Google AMP viewer on iOS Chrome

### ISSUE THREAD

**Issue by gramorris** [ampproject/amphtml#18866]
## What's the Issue?

Within the Google viewer on iOS Chrome the bottom toolbar of the new UI doesn’t slide out of the way as it does outside of the viewer. It’s also not pushing fixed position elements up either so the amp-sticky-ad elements are behind the toolbar UI.

## How do we reproduce the issue?

I’m currently seeing this on every page that implements the sticky ad element when viewed through the Google AMP viewer when accessed from the top stories carousel.

## What browsers are affected?

iOS Chrome, latest version

## Which AMP version is affected?

It seems to be an interaction issue between Chrome and the AMP viewer rather than AMP specifically.

**Comment by gramorris** [comment]
Attached a grab where you can see the very top of the close button in the bottom left corner

![img_9262](https://user-images.githubusercontent.com/6436641/47303287-6adb0600-d61b-11e8-9f39-2804e3f5bef1.PNG)

**Comment by torch2424** [comment]
@lannka Categorized this, feel free to assign to whoever can pick this up 😄

**Comment by zhouyx** [comment]
@lannka Just saw this, sorry for the delay.

Yes I agree this is a high priority issue. But there's not much can be done from the AMP side. It will also break other components that stick to the bottom of the page, including user-notification. Let's track this internally.

**Comment by lannka** [comment]
It's confirmed to be a Search Viewer bug. Tracked internally: b/118598702
Will update here once we have a clear ETA for a fix.

**Comment by lannka** [comment]
This should have been fixed in Search Viewer. Please verify.

**Comment by gramorris** [comment]
Confirming I'm seeing this fixed. Thanks all.
