### ISSUE TITLE
Add Array support for amp-analytic vars 

### ISSUE THREAD

**Issue by SmithKevin** [ampproject/amphtml#1886]
As it is now each "vars" are encoded as a single string element.   We would like to be able to pass multiple values into a single var as an array, but at the same time all elements are uri encoded separately and the comma is preserved unencoded. 

Example for two separate labels:
  "vars": {
    "labels": ["Config 1", "Config, The Barbarian"]
  }
is encoded as "Config%201%2CConfig%2C%20The Barbarian" which would then be confused for three separate labels "Config 1", "Config", " The Barbarian"  Instead it would be encoded "Config%201,Config%2C%20The Barbarian"

I have a small fix on my end if you'd be open for a pull request.

**Comment by rudygalfi** [comment]
cc @avimehta Do you think this would work?
@SmithKevin If you have the PR ready, please post it.

**Comment by SmithKevin** [comment]
Ok.  Let me clean it up really quick and I will post it.

**Comment by jridgewell** [comment]
Closed by #1891.
