### ISSUE TITLE
[Validator] Relax minimum-scale from required meta viewport values

### ISSUE THREAD

**Issue by westonruter** [ampproject/amphtml#18896]
AMP currently [requires](https://www.ampproject.org/docs/fundamentals/spec#vprt) a meta viewport including the following values (at least):

```html
<meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
```

The requirement of `minimum-scale=1` can be an impediment for adopting AMP, such as in the new default theme for WordPress core: https://github.com/WordPress/twentynineteen/pull/199#issuecomment-431531700

> In the event an embed or other replaced element introduces horizontal scaling it's helpful to zoom below 1.0 to view the entire thing.

Apparently the initial reason for including `minimum-scale=1` was due to a bug in Chrome that has since been fixed and it is no longer required. If that is the case, then the requirement should be lifted from AMP as well.

/cc @cramforce @amedina

**Comment by cramforce** [comment]
I'd welcome relaxing this.

@dvoytenko @aghassemi Any objections?

**Comment by aghassemi** [comment]
SGTM. Use-case makes sense to me (probably needed for embeddable `amp-story` anyway)

**Comment by Gregable** [comment]
The change is easy. Do we need to wait for @dvoytenko to respond?

@aghassemi 	confused about your comment - do you mean that we need to maintain this requirement for stories?

**Comment by aghassemi** [comment]
@Gregable sorry I meant it makes sense for something like `amp-story` to start at `<1 scale` when it is embedded in another page which relaxing this requirement helps with.

**Comment by Gregable** [comment]
Sounds good. @westonruter 	do you want to take a stab at the change. 

I think you need to modify:
 - `validator/validator-main.protoascii` to change the rules for meta viewport.
 - Modify `validator/testdata/feature_tests/minimum_valid_amp.html` to show that this now works. Then run gulp validator --update-tests to update `minimum_valid_amp.out`
 - update `spec/amp-html-format.md` to simplify the requirements

**Comment by westonruter** [comment]
@Gregable Thanks for the direction. I've opened #19129 for your review.
