### ISSUE TITLE
Hide navigation hint when bookend is opened

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#18903]
Repro steps:
1) Navigate to the last page of any story
2) Swipe horizontally to show navigation hint
3) Tap to next page while the hint is displayed

Observed Result: 
Navigation hint is shown behind the bookend:
![screenshot](https://user-images.githubusercontent.com/1651960/47387377-33349280-d6dd-11e8-8440-083b28363d89.png)

Expected Result: 
Navigation hint should be hidden when the bookend is displayed.

**Comment by newmuis** [comment]
Actually, @hongwei1990, should we just always hide the navigation hint when the user navigates?

**Comment by gmajoulet** [comment]
We already do it when we hide the UI during a "hold to pause" interaction.
Copying this code and adapting it for the `BOOKEND_STATE` should be enough:
https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/1.0/amp-story-hint.js#L175-L178
