### ISSUE TITLE
AMP component for webcam/camera streaming and image capture

### ISSUE THREAD

**Issue by theimgclist** [ampproject/amphtml#18919]
## What's the issue?
I was one of the attendees of AMP Roadshow where I got to know about many AMP components that make existing HTML components better and faster. I'm working on building a web app for Face Recognition. It is currently developed in HTML, Python and a lightweight server. The web app has a webcam video that gets streamed, from which the image is captured and processed to perform face match. Is there any feature already in AMP that supports webcam streaming and image capturing from it? I didn't find anything related to webcam/camera support.

## What browsers are affected?

All browsers and both mobile and desktop (webcam and camera related feature)

## Which AMP version is affected?
This would be a new feature since I didn't find anything related

@mattludwig This is related to the issue I discussed with you during AMP Roadshow, Bangalore

**Comment by aghassemi** [comment]
@theimgclist Please use `amp-iframe`. Use-cases like this would require direct access to JS which AMP does not allow at top level. `amp-iframe` should solve your use-case.

Also if if you web app is just for face recognition, AMP may not be the right framework for your case.
