### ISSUE TITLE
Mysterious reflow and scroll-animation of AMP with <amp-ad>

### ISSUE THREAD

**Issue by yunabe** [ampproject/amphtml#18917]
## What's the issue?
There is an AMP page that reflows and scrolls with animations while users are reading contents.
I think the reflow is caused by `<amp-ad>` on the page.

## How do we reproduce the issue?

1. Google search [site:biography.com+madonna](https://www.google.com/search?hl=en&q=site:biography.com+madonna) on mobile phones
2. Click the first result (https://www.biography.com/.amp/people/madonna-9394994)
3. When the page is opened, scroll down to the bottom quickly.
4. **Issue 1**: The page reflows and changes the scroll position with animation. Bad user experience. ([0:06-0:12 in the video](https://www.youtube.com/watch?v=lVawn9dcNac&t=6s))
5. Back to google.com and reload the page.
6. Click the result again.
7. Now, AMP restores the scroll position and scroll to the bottom automatically.
8. **Issue 2**: In the previous step, the scroll position is set with animation and it takes time ([0:22 in the video](https://www.youtube.com/watch?v=lVawn9dcNac&t=22s)).
9. **Issue 3**: Reflow and scroll animation again. ([from 0:24](https://www.youtube.com/watch?v=lVawn9dcNac&t=24s))
10. **Issue 4**: Also, the scroll position is not restored precisely. Please compare [0:17](https://www.youtube.com/watch?v=lVawn9dcNac&t=17s) and [0:30](https://www.youtube.com/watch?v=lVawn9dcNac&t=30s)

Google search result:
https://www.google.com/search?hl=en&q=site:biography.com+madonna
AMP page:
https://www.biography.com/.amp/people/madonna-9394994
Video:
https://www.youtube.com/watch?v=lVawn9dcNac

## What browsers are affected?
Android Chrome. Not reproducible in iPhone Safari.

## Which AMP version is affected?
The live AMP used in Google search
`Powered by AMP ⚡ HTML – Version 1810152207300`

## Notes
This AMP behavior interacts with animateScrollIntoView in [HighlightHandler](https://github.com/ampproject/amphtml/blob/master/extensions/amp-viewer-integration/0.1/highlight-handler.js) badly and we sometimes fail to show highlighted texts on user screens.

**Comment by aghassemi** [comment]
I think this is WAI, Taboola, etc al ads at the bottom of the page do resize (based on the logic that the last element in the page is allowed to resize) so if user scrolls too quickly to the end, they may notice the reflow.

**Comment by aghassemi** [comment]
There are other cases like this such as amp-twitter resizing always. Technically speaking, AMP page's layout is not 100% static, but it is to a large extend so bad UX is very much minimized.
