### ISSUE TITLE
navigateTo issue with 'target' parameter on Google AMP CDN

### ISSUE THREAD

**Issue by heyvin** [ampproject/amphtml#18916]
We're using 'target' parameter for navigateTo which was described in this PR:
https://github.com/ampproject/amphtml/pull/18043
However when this piece of code runs in Google AMP CDN, it throws the error:
`Blocked a frame with origin "https://fruit-heyv-in.cdn.ampproject.org" from accessing a cross-origin frame.`

**Steps to reproduce:**
- Go to https://search.google.com/test/amp?view=search-preview&id=F6IkYb2NRGAq1hyTUNkJrA
- Click first result. Open Chrome inspect.
- Click "Orders"

**Affected browsers:** Chrome, Safari on mobile devices.

**Comment by aghassemi** [comment]
Looks like `target=_blank` does not work in the viewer. @sparhami, could you please take a look?
