### ISSUE TITLE
ampproject.org/docs/: Menu not working under BlackBerry 10 browser

### ISSUE THREAD

**Issue by devnullzero** [ampproject/amphtml#1892]
Docs section of ampproject.org: 
1) Menu is displayed by default and can't be hidden (see screenshot). 
2) Hamburger icon does nothing.

Tested using:
BlackBerry 10 (10.3.2.2474)
Hardware: Z10
WebKit: 10.3.2.43
Browser Version: 10.3.2.36

Screenshot of https://www.ampproject.org/docs/get_started/about-amp.html
![blackberry-z10-navigator](https://cloud.githubusercontent.com/assets/17152796/12936158/92e636f8-cf69-11e5-9423-190d9269ec7f.png)

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
