### ISSUE TITLE
Document that amp-bind updates value attribute on input

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#18921]
During a discussion about clearing a form that uses amp-bind in https://github.com/ampproject/amphtml/issues/7368#issuecomment-432385515 I noticed that amp-bind updates an input element's value attribute. I want to make sure this is the desired behavior and not a bug. 

Should the attribute be updated, given that the attribute is the initial value? I believe the current behavior is not what we want: pressing an `<input type="reset">` will assign all input elements their `value` attribute, which if bind mutated, will not be the original empty value that a document author expects.

If this is the desired behavior, I think we should document it specifically.

**Comment by choumx** [comment]
Not sure I follow. amp-bind actually updates both properties and attributes for input elements: https://github.com/ampproject/amphtml/blob/b5cae4faec86f5af68b3d9381ce9b0e98c2bc6a1/extensions/amp-bind/0.1/bind-impl.js#L1091-L1112

**Comment by cvializ** [comment]
I believe that the attribute strings themselves should not be updated when they specify an initial state, like `value`. Consider the following form:

```html
<form action-xhr="/post" method="POST"  target="_blank">
<input type="text" name="computed-value" value="initial" [value]="computedString">
<input type="reset">

<input type="submit">
</form>

<input type="button" on="tap:AMP.setState({computedString: computedString ? computedString + 'a' : a})"
```

I would expect that pressing the reset button would change the value of the input to be `initial`. But the actual behavior is that reset does nothing, because `amp-bind` mutates the `value` attribute. In other words, `amp-bind` breaks the standard form reset behavior.
