### ISSUE TITLE
This page has 10 external Javascript scripts. Try combining them into one.

### ISSUE THREAD

**Issue by aladaghlou** [ampproject/amphtml#18922]
Hello.
When we use Google AMP js components for example amp-form,amp-selector and etc realy we increased requests on client-side ! And benchmark tools like GTmetrix said to we this is bad score and we must decreasing requests.
Is there a solution to this problem?
Thanks all

**Comment by torch2424** [comment]
Hello!

So there is a lot of different pros and cons to this, and we chose to go down the route of having separate scripts for a reason.

For instance, a con to this approach, like you stated, is that you end up making a lot of round trip requests to load all of your extensions. While this is not necessarily bad, but I agree it's not entirely good.

But a pro from our point of view, is that this allows extensions to load independently of one another. For example, in your case, you don't have to wait for all 10 extensions to load to then start using them. That way, larger extensions don't stop smaller extensions from running.

Does this answer your question? Feel free to reply/continue the discussion 😄

**Comment by matthiasrohmer** [comment]
I thought about this recently as well and wondered if it has been considered someday to handle this in the CDN? So for example if a document relies on `amp-list`, `amp-bind` and `amp-carousel` you would have

```html
<script async custom-element="amp-carousel" src="https://cdn.ampproject.org/v0/amp-carousel-0.1.js"></script>
<script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>
<script async custom-element="amp-list" src="https://cdn.ampproject.org/v0/amp-list-0.1.js"></script>
```

But maybe the CDN could be enabled to also handle combined component URLs like for example

```html
<script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js+amp-carousel-0.1.js+amp-list-0.1.js"></script>
```

for the same set of dependencies. Though this might still be slower than independent requests especially if you add a fairly big component to the list.

**Comment by torch2424** [comment]
@matthiasrohmer 

Yes definitely, I agree it is possible 😄 But yeah there will be some performance tradeoff happening here if so, gonna to pull someone else from the team into the discussion 👍 

Pinging @aghassemi , Is there a way we handle feature requests? Or is this something we would want to implement?

**Comment by aghassemi** [comment]
@matthiasrohmer @aladaghlou yep, all about trade offs, classic bundling dilemma. We ( @erwinmombay ) are actually working on solution that is a good middle ground. It is part of the "single pass" project. Idea is that we will have v0 + a few new intermediary bundles (like ads.js, media.js, base.js) which hold common code for extensions but bring extension sizes down significantly. This actually increases number of requests but overall considering long cache expiry on AMP and the fact that same Url is used across AMP pages, it will help with loading times.

We constantly measure metrics such FMP, TTI, etc.. and run experiments to lower them.

**Comment by aghassemi** [comment]
Closing per above comment. This is something that we constantly try to improve in AMP Cache.
