### ISSUE TITLE
A9 Integration with AMP

### ISSUE THREAD

**Issue by deepak0004** [ampproject/amphtml#18939]
My changes to accomodate A9 with AMP got merged (3 hours ago).
When I test it using amp-ad code, it errors out for all fields giving unknown attribute for A9.

However, when I test locally through the repo (after setting up repo and doing gulp), it works perfectly.
What could be the reason for it?

For reference, pull request: #18506

**Comment by torch2424** [comment]
Hello!

So we do our releases through a canary process. One week in a canary to test a release, and then it is released to production. 

So in live AMP pages, your changes will be available in production in 7-14 days, depending how the releases get cut.

cc @lannka if you have more context on this.

@deepak0004 if this answers your question, feel free to close the issue. Thank you! 😄

**Comment by deepak0004** [comment]
Okay, thank you!
