### ISSUE TITLE
amp-video should fall back to showing its poster image if the video cannot be decoded

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#18936]
If the video cannot be decoded (e.g. on iOS, where there is a hardware limit to how many videos can be decoded at once), `amp-video` should fall back to showing the poster image.

By default, iOS shows a play button with a line through it:

![screenshot](https://user-images.githubusercontent.com/1651960/47454889-570bdd00-d79e-11e8-8bc2-0b29f61dab75.jpg)

**Comment by aghassemi** [comment]
Currently any failure mode shows `fallback`. We could change this for amp-video so that it falls back this way: `fallback` > `placeholder` > `poster`, seems reasonable.
