### ISSUE TITLE
SESSION_ID from AMP runtime or [Cookie Custom Expiry & Cookie Read/Write with Counter]

### ISSUE THREAD

**Issue by dmvjs** [ampproject/amphtml#18931]
Our tools and dashboard have a use case that requires:
1) cookie expired in 30min. 
2) cookie read/write with a counter

When a user first interacts with a publisher domain, they set a visit ID cookie with a value like 12345abc000. The next view on the same domain within 30 minutes has the param 12345abc001, then ...002, etc., until there is a 30 minute period of inactivity, at which point they will start sending a new visit ID ending in 000 again.

We use this value to deliver publisher visit analytics in our dashboard and also to detect when a publisher has installed their tools correctly.

Right now we can use the CLIENT_ID for part of the task but we still need the other two parts listed above to provide the analytics.

This should be available on all AMP pages and devices. This is a new feature request.

**Comment by lannka** [comment]
Thanks @dmvjs to move this discussion here, we had chat in Slack. 

Can this feature requirement be generalized as providing a SESSION_ID from AMP runtime? it will be transparent to pub how it is implemented (could be as what you described). Pub can have basic config like the 30min interval.

Note that this client storage based solution will not work on Cache. A server side session computation would provide a more complete view.

Meantime, I'm wondering if this kind of "client side session management" is common.  /cc @rudygalfi @jeffjose do you see any similar requirements like this?

**Comment by dmvjs** [comment]
Sounds good to me ^^^

**Comment by jeffjose** [comment]
This actually came up yesterday in a conversation I was having. I think there's a need to have better SESSION support inside AMP. In addition to the use case mentioned by @dmvjs, having robust SESSION IDs can aide in debugging when you're trying to tie a certain frontend state to a backend.
