### ISSUE TITLE
Support tracking in a multi-step work flow

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#18949]
For a typical amp-bind based multi-step work flow in AMP, such as a shopping experience, amp-analytics is currently lacking a good way to track each step. 

New triggers to be considered:
- action trigger
- AMP state change trigger
- DOM event trigger. (use action to fire a custom DOM event)

Open for discussions

/cc @zhouyx @aghassemi @choumx @calebcordry @torch2424 @jeffjose

**Comment by zhouyx** [comment]
An early thought that may or may not worth looking into. This sounds like a usecase for custom analytics event. Is it possible to allow user to trigger their own custom analytics event using amp-bind.

**Comment by choumx** [comment]
From short hangouts discussion with Hongfei, we should compare with what is possible today. 

"Single-page app" like flows require user gestures, and pubs today can already add analytics hooks onto button presses etc.

**Comment by jeffjose** [comment]
It sounds like there's 2 things being requested here. 1. Support for new triggers 2. Grouping them as part of a multi-step workflow.

In general supporting new triggers is a good idea as AMP pages are used for complex pages. The second one is interesting in itself -- an ability to categorize certain triggers into a group (say *checkout-steps*)

Let me know if I'm understanding the requirement incorrectly.

**Comment by lannka** [comment]
@kristoferbaxter would amp-script complicate the landscape here even further? What potential would amp-script enable user to build a single page app?

**Comment by jpettitt** [comment]
Where are we with this? We'd like to implement transaction triggers in `amp-subscriptions-google` to capture a sale, amount, transaction id etc.  I don't want to invent a something new if we already have transaction flow triggers in the works.

**Comment by lannka** [comment]
@jpettitt your use case might be already supported today. We have `amp-carousel` for example sending custom events can captured by `amp-analytics`.

please take a look at this service API, see if it meets your needs: https://github.com/ampproject/amphtml/blob/master/src/analytics.js#L26

**Comment by lannka** [comment]
as @zhouyx pointed out this could be implemented as a DOM event tracker. do we have a tracker for that? We can close this one.
