### ISSUE TITLE
amp-mustache-0.2 sanitizes <use> SVG tag

### ISSUE THREAD

**Issue by poluhovich** [ampproject/amphtml#18958]
If template contains `svg` tag with `use` tag inside, `use` tag will be deleted.
```
<template type="amp-mustache">
    <svg viewBox="0 0 24 24" class="svg-icon">
        <use xlink:href="#icontest"></use>
    </svg>
</template>
```
The result will be:
```
<svg viewBox="0 0 24 24" class="svg-icon">

</svg>
```
## What's the issue?

SVG `use` tag used for assigning images (icons) from sprite resource. It works normally in AMP but AMP-mustache template wipes it out.

## How do we reproduce the issue?

Example of reproducing: https://codepen.io/poluhovich/pen/bmOovy?editors=1000#0

**Comment by aghassemi** [comment]
/to @choumx Repro uses mustache 0.2 which supports SVG, not sure what's happening.

**Comment by choumx** [comment]
`<use>` isn't supported by default in DOMPurify: https://github.com/cure53/DOMPurify/blob/303db0fc57bef5dee115135a1e9d022a41c1041c/src/tags.js#L126-L173

We'd need to allow it in our custom hook, e.g. https://github.com/cure53/DOMPurify/issues/233

**Comment by jerimiahwelch** [comment]
We would love to be able to reuse <use> tags in our amp-lists as well.
