### ISSUE TITLE
Error: Request cid failed: document is not visible

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#18967]
**Over 1.5 million reports** in the last day.

```
Error: Request cid failed: document is not visible
    at X.push.f.X.X (https://cdn.ampproject.org/rtv/011810152207300/v0/amp-viewer-integration-0.1.js:25:224)
    at https://cdn.ampproject.org/rtv/011810152207300/v0/amp-viewer-integration-0.1.js:23:484
r
```

go/ampe/CN3E2-uxucaiqgE

**Comment by lannka** [comment]
@jridgewell the StackDriver link seems to be wrong

**Comment by lannka** [comment]
I'm struggling with the stackdriver reports. I don't see the "Request cid failed: document is not visible" msg anymore, but I could see it in history either...

Also, the link now points to different error messages.
