### ISSUE TITLE
amp-analytics visible trigger does not function properly on Safari

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#18972]
the visible trigger on Safari is based on an IntersectionObserverPolyfill, which has limitation on detecting non-scroll triggered visibility change. For example, when an element's visibility is toggled via amp-bind.

We could leverage MutationObserver (which is [well supported](https://caniuse.com/#feat=mutationobserver)) to increase the coverage. 

This is a blocker for Fandango to launch their AMP integration, before we can offer a better analytics solution for single page app #18949.

/cc @zhouyx

**Comment by torch2424** [comment]
First step, we want to make a minimal amp bind example with analytics visibility trigger.

Then inside `intersection-obersverer-polyfill.js`. Look for where `tick()` is called. In the constructor, and only for safari, add a mutation observer. Whenever it mutates, call tick, and pass only the viewport. We can get the viewport from the viewport service.

**Comment by zhouyx** [comment]
Given this is a high priority task, I am ok with us creating mutationObserver within InOb polyfill at this time. 
But long term, I believe we should only have single instance of mutationObserver. I know @jridgewell is working on using mutationObserver for the layer manager to track AMP component's visibility change via the `toggle()` function. 

@torch2424 It will be great to understand how often mutationObserver is getting called!

**Comment by jridgewell** [comment]
Yup, `FixedLayer` [already has](https://github.com/ampproject/amphtml/pull/18797) a `MutationObserver` specifically to track `hidden` attribute changes (which is now the only official way to show/hide an element). We could extract this out into a `HiddenAttrMutationObserver` service, and have both `FixedLayer` and the InOb Polyfill register with it.

As a short term, I'm fine with InOb adding another `MutationObserver`.

**Comment by torch2424** [comment]
@jridgewell Definitely in favor in having a single service in order to create and manage Mutation Observers. Depending on the comment we receive on how to move forward, perhaps we can have this server pass in their own [MutationObserverInit](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserverInit)? 😄
