### ISSUE TITLE
Akamai BotManager breaks AMP due to script injection

### ISSUE THREAD

**Issue by cnabar** [ampproject/amphtml#18976]
Akamai BotManager breaks AMP due to script injection

https://www.akamai.com/us/en/products/cloud-security/bot-manager.jsp

Script injected:
<script type="text/javascript">var _cf = _cf || []; _cf.push(['_setFsp', true]); _cf.push(['_setBm', true]);</script><script type="text/javascript" src="/_bm/abd-1-30"></script>

This seems similar to earlier issue in Akamai RUM 
https://github.com/ampproject/amphtml/issues/12598

@aghassemi @cvazac
Is this something that can resolved at the product level as well by avoiding script injection when pages are identified as AMP

**Comment by cnabar** [comment]
Yes I meant at the Akamai product level - This was tracked as a 3P implementation issue in the previous bug  https://github.com/ampproject/amphtml/issues/12598

**Comment by cvazac** [comment]
I will raise this with the BM team and report back ASAP.

**Comment by cnabar** [comment]
Thanks @cvazac!

**Comment by choumx** [comment]
Closing as off-topic.

**Comment by choumx** [comment]
Reopening since there's no other place to track this.

**Comment by cnabar** [comment]
@cvazac Wanted to check if the BM product team has any update on resolving this - I recently ran into this issues again with script being injected on AMP page - see below

<script type="text/javascript" >var _cf = _cf || []; _cf.push(['_setFsp', true]); _cf.push(['_setBm', true]); _cf.push(['_setAu', '/static/f66a92d547523719e39c1ea36f6fb99']);</script><script type="text/javascript" src="/static/f66a92d547523719e39c1ea36f6fb99"></script>

Thanks!

**Comment by cvazac** [comment]
I am no longer with Akamai - tapping in @nicjansma in case he's able to speak for the BM team.

**Comment by nicjansma** [comment]
Response from the Akamai Bot Manager team: Current Akamai customers can exclude the injection of BMP JavaScript on AMP pages by adding an exclusion path in the injection rules.

Akamai is exploring other options of excluding BMP JavaScript from AMP pages automatically

**Comment by cnabar** [comment]
Sounds good - thanks for the update @nicjansma

**Comment by Joelsz** [comment]
How about other 3P scripts for security and/or bot detection (incl. Akamai, BIG-IP etc.), is there a common practice on implementing something like this with amp-script? or submitting a custom component?

We originally compromised on security while switching to AMP, we definitely want to get back to the same standards we were at the time. What would be the suggested approach from the AMP team?

Some documentation or guidance would for sure be helpful.
