### ISSUE TITLE
🌸 Cherry pick request for #18772 into #18649 (Approved)

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#18984]
**NOTE:** This is a cherry-pick request for __current__ production #18649
This has already been cherry picked into Canary in https://github.com/ampproject/amphtml/issues/18837

**GitHub issue your cherry pick is fixing:**

Issue: #18759

**PR that you are requesting a cherry pick for:**

PR: #18772

**Release(s) you requesting this cherry pick into:**

Production Release? **YES**. release #18649

Canary release? **NO**

- Fixes [regression](https://github.com/ampproject/amphtml/issues/18759#issuecomment-430309758) that causes resizing on focus for amp-list that have a large-height placeholder.
- Disables Layers in canary pending metrics investigation.

/cc @jridgewell @erwinmombay @cramforce  @leonalicious

**Comment by cramforce** [comment]
Approved

**Comment by aghassemi** [comment]
This has been released.
