### ISSUE TITLE
Cherrypick #18878 into #18971 (Approved)

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#18985]
**Replace *everything* in angle brackets in the title AND body of this issue.  If you have any questions see the [cherry pick documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-picks).**

**PR that you are requesting a cherry pick for:**

*(Put N/A if you do not yet have a PR with a fix; edit this issue to add it when the PR is ready.)*

PR #18878

**Release(s) you requesting this cherry pick into:**

*Release issues can be found at https://github.com/ampproject/amphtml/labels/Type%3A%20Release*

*If you are requesting a cherry pick into a production release you will most likely need to cherry pick into canary as well, otherwise when the canary is pushed to production your fix will be lost.  See the [cherry pick documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-picks).)*

Production Release? NO 

Canary release? YES  If yes, Type: Release Issue #18971

*Why does this issue meet the [cherry pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?  Be specific.*

We plan to do a release freeze during election week, we'd not follow normal release process. All important PRs will be piled as cherrypicks. This PR unblock Segment's linker integration.

*Assign this issue to the current TL (cramforce) if you have permission to, otherwise leave this cc line in.*

/cc @cramforce

**Comment by cramforce** [comment]
Approved

**Comment by misteryeo** [comment]
Hi @cramforce - can I check to see if this was released to Canary or when it will be since it got approved on Friday?

cc: @lannka

**Comment by cramforce** [comment]
Looks like it shipped to canary https://github.com/ampproject/amphtml/releases

**Comment by misteryeo** [comment]
Thanks @cramforce!

**Comment by jridgewell** [comment]
As of [30min ago](https://github.com/ampproject/amphtml/releases/tag/1810281911260), it's also going live to prod.
