### ISSUE TITLE
Content width in /amp 1px wide

### ISSUE THREAD

**Issue by richardaucock** [ampproject/amphtml#1898]
My content is appearing 1px wide and, despite investigation, I can't work out how to alter. Any tips appreciated!

See: http://www.motoringresearch.com/car-reviews/2016-toyota-prius-review-first-drive/amp

On Webmaster search console, it advises this: Prohibited attributes: content_max_width, type...

... which seems to be a clue. Any experts out there who can help?

**Comment by richardaucock** [comment]
Here's a screengrab... 
![screen shot 2016-02-10 at 18 34 53](https://cloud.githubusercontent.com/assets/12961614/12957545/0f638c56-d025-11e5-833f-fdc39c38bd21.png)

**Comment by rudygalfi** [comment]
It looks like you're using the AMP WordPress plugin. You may want to follow-up in that community: https://github.com/Automattic/amp-wp

**Comment by richardaucock** [comment]
Many thanks Rudy, I shall do that. Appreciate your input!
