### ISSUE TITLE
Prototype AMP Story fullscreen experience

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#18986]
Using the browser `requestFullscreen` API, prototype an AMP Story fullscreen experience.

Runtime provides a [fullscreenEnter](https://github.com/ampproject/amphtml/blob/master/src/dom.js#L827) and [fullscreenExit](https://github.com/ampproject/amphtml/blob/master/src/dom.js#L848) cross browser methods.

- Enter fullscreen upon first user interaction (navigation)
- Provide a way to exit fullscreen

More context from @newmuis:

> The old behavior was: automatically enter fullscreen on first nav, automatically exit when you hit the bookend.  whenever you're in fullscreen, you're shown an exit fullscreen icon.  whenever you click that icon we stop automatically pushing you into/out of fullscreen, but give you an enter fullscreen icon to manually do it yourself

**Comment by gmajoulet** [comment]
Android only: https://stamp-fullscreen.firebaseapp.com/examples/s20/body-painting/index.html

**Comment by aghassemi** [comment]
@newmuis @gmajoulet Chrome 71 has shipped the `options` param for `requestFullScreen` (https://developers.google.com/web/updates/2018/12/nic71). 

> The Element.requestFullscreen() method can now be customized on Android and allows you to choose between making the navigation bar visible versus a completely immersive mode where no user agent controls are shown until a user gesture is performed.

**Comment by newmuis** [comment]
I don't think this should be closed.  We should still prototype this, if not even just implement it behind an experiment

**Comment by newmuis** [comment]
Stop closing this, stale bot!

**Comment by gmajoulet** [comment]
@newmuis I was about to close this as it might be a Player feature but saw your comment, do you still think there's value in doing it from an invididual Story?

**Comment by newmuis** [comment]
It might be a player feature, but:

(1) I wonder if that should actually be implemented as a feature in our open source player (e.g. swapping enter fullscreen icon to exit fullscreen icon)

(2) maybe we still need to prototype even in a codepen just to double-check the current state of the fullscreen transition in the current day
