### ISSUE TITLE
Add Bing to AMP caches.json

### ISSUE THREAD

**Issue by mattwomple** [ampproject/amphtml#18992]
## What's the issue?

Bing has an AMP viewer and AMP cache:  
Intro: https://blogs.bing.com/Webmaster-Blog/September-2018/Introducing-Bing-AMP-viewer-and-Bing-AMP-cache  
Sample: https://www.bing.com/amp/s/www.washingtonpost.com/amphtml/science/2018/10/24/no-nasa-didnt-fix-hubble-telescope-by-just-turning-it-off-again/

Bing is not included in the list of AMP caches:  
Master: https://github.com/ampproject/amphtml/commits/master/caches.json  
Live: https://cdn.ampproject.org/caches.json

The [Bing AMP Cache documentation](https://www.bing.com/webmaster/help/bing-amp-cache-bc1c884c) is weak, so I'm not sure about properties `cacheDomain`, `updateCacheApiDomainSuffix`, and `thirdPartyFrameDomainSuffix`.

### Follow-up question

Is `https://cdn.ampproject.org/caches.json` intended to be consumed by API endpoints to determine [safe CORS origins](https://www.ampproject.org/docs/fundamentals/amp-cors-requests#verify-cors-header)? If not, where is a more complete list?

**Comment by honeybadgerdontcare** [comment]
This is now live at https://cdn.ampproject.org/caches.json
