### ISSUE TITLE
Add new analytics var – new visitor

### ISSUE THREAD

**Issue by StephanGuenther** [ampproject/amphtml#1900]
## newVisitor
Provides the status, whether the cookie ID was just generated and set new or already existed.

Example value: 1 or 0

```html
<amp-analytics config="http://example.com/config.json">
<script type="application/json">
{
  "requests": {
    "pageview": "https://example.com/analytics?url=${canonicalUrl}&title=${title}&clientId=${clientId(cid-scope)}&nv=${newVisitor}",
  },
  "vars": {
    "account": "ABC123",
    "title": "Homepage"
  },
  "triggers": {
    "some-event": {
      "on": "visible",
      "request": "pageview",
      "vars": {
        "title": "My homepage",
        "clientId": "my user"
      }
  }
}
</script>
</amp-analytics>
```

**Comment by avimehta** [comment]
I think we can do this if we know whether the client id that was generated is new or not. This leads us to a situation where AMP keeps more state about the user. Not sure how @cramforce and @dvoytenko  feel about this.

It is doable though. Once we do this, I think keeping the session start time also comes back on table since it is related.

**Comment by dvoytenko** [comment]
It's somewhat difficult to do in all cases since we can't use storage in all platforms/environments. E.g. private mode on iOS sort of thing where local storage quota is 0.

**Comment by avimehta** [comment]
In that case, we should close this issue as won't fix.

**Comment by rudygalfi** [comment]
@dvoytenko @avimehta Just want to confirm: It sounds like there's actually an error condition here and we need to account for that. To support this, we'd need to determine a value for that error condition.

I think this raises the issue that this proposal is also asking AMP to have an opinion about the interpretation of some data (whether there is a new visitor) and there's the possibility that it's just unknown.

Getting to the heart of the ask, would it be possible to somehow represent the error state (`-1`?) and rename the variable to something more expressive of what it's indicating?

**Comment by dvoytenko** [comment]
@rudygalfi could you please clarify what you mean by error state? On the surface I don't quite see error state here. We will have a problem consistently being able to tell new vs old user given that (a) AMP doesn't by itself track the system user age; (b) We can't reliably save a flag "new" or "old". In reality, we normally do not create a cookie for CLIENT_ID - we just derive it from a previously existing base.

On the other hand, this would seem like a very easy job for analytics backend to determine whether or not any particular CLIENT_ID has been seen for the first time.

**Comment by avimehta** [comment]
+1 to what @dvoytenko said.

**Comment by rudygalfi** [comment]
After some further review of this topic, I'm not convinced that AMP can build a good newVisitor variable for the reasons that @dvoytenko and @avimehta stated. Unlike my previous understanding that there's an error case to cover, it sounds like there are certain times of failure that we cannot be aware of.

I agree that the analytics providers which consume the CLIENT_ID are in the best position to make an assessment of a new visitor. I suggest that's the path by which this kind of thing is supported, so closing this.
