### ISSUE TITLE
Cherrypick iOS rendering fix to PROD

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#19009]
GitHub issue your cherry pick is fixing:

Issue #8798

PR that you are requesting a cherry pick for:

PR #19007, #19008

Release(s) you requesting this cherry pick into:

- 1810261559300 (prod)
- 1810241929000 (canary)

Production Release? YES
Release Issue #8798

Canary release? YES

Why does this issue meet the cherry pick criteria? Be specific.

Fixes iOS rendering regression.

Assign this issue to the current TL (cramforce) if you have permission to, otherwise leave this cc line in.

/cc @cramforce

**Comment by cramforce** [comment]
Wow, scary. Approved. I'd prefer if we went to canary first and let it bake there.

**Comment by dvoytenko** [comment]
#19055 to unlaunch. The fix was found to create another issue.
