### ISSUE TITLE
How fetch public RSA key .pem file ?

### ISSUE THREAD

**Issue by shangdev** [ampproject/amphtml#19016]
## What's the issue?

I am Update AMP Content, Need to generate public key. 

This is my code:

```
public function generateRsaKey($ampCachePath)
{
        $privateKeyId = openssl_pkey_get_private('file://' . self::KEY_FILE_PATH);
        openssl_sign($ampCachePath, $signature, $privateKeyId, OPENSSL_ALGO_SHA256);
        openssl_free_key($privateKeyId);

        $signature = self::base64Encode($signature);

        return $signature;
}
```

What I don't understand is that the KEY_FILE_PATH variable in the code is actually a .pem file,

But how do I get him?

**Comment by cathyxz** [comment]
Per https://developers.google.com/amp/cache/update-cache: 
> For signature verification, you must serve the public RSA key at a fixed location on the AMP document's domain (to generate the key, see Generate the RSA key). For example:
```
https://example.com/.well-known/amphtml/apikey.pub
```
Per https://developers.google.com/amp/cache/update-cache#rsa-keys: 
> Generate a pair of RSA keys in the textual PEM format like this:
```
openssl genrsa 2048 > private-key.pem
openssl rsa -in private-key.pem -pubout >public-key.pem
```
