### ISSUE TITLE
<amp-subscriptions> analytics: subscribe action events not fired

### ISSUE THREAD

**Issue by justforfun** [ampproject/amphtml#19019]
## What's the issue?
As described here:
https://www.ampproject.org/docs/reference/components/amp-subscriptions#analytics
using a Facebook pixel we are trying to track the outcome of the subscribe action following what the doc suggests:

> subscriptions-action-ActionName-success:
> If the event result reports a success, subscriptions-action-ActionName-success is triggered.
> This event does not contain any data.

This is the Facebook analytics code

```
<amp-analytics>
        <script type="application/json"> {
            "requests":{

                "host": "https://www.facebook.com",
                "base": "${host}/tr?noscript=1",
                "ViewPaywall" : "${base}&ev=ViewPaywall&id=${pixelId}&cd[meter_count]=0",
                "SubscribeActionStarted" : "${base}&ev=SubscribeActionStarted&id=${pixelId}&cd[serviceId]=${serviceId}&cd[action]=${action}",
                "SubscribeActionCompleted" : "${base}&ev=SubscribeActionCompleted&id=${pixelId}",
                "SubscribeActionFailed" : "${base}&ev=SubscribeActionFailed&id=${pixelId}",
                "SubscribeActionRejected" : "${base}&ev=SubscribeActionRejected&id=${pixelId}"
            },
            "vars":{

                "pixelId":"247428115450514",
                "serviceId": "${serviceId}",
                "action": "${action}"
            },
            "triggers": {
                "accessAuthorizationFailed": {
                    "on": "subscriptions-access-denied",
                    "request": "ViewPaywall"
                },
                "subscriptionsActionDelegated": {
                    "on": "subscriptions-action-delegated",
                    "request": "SubscribeActionStarted"
                },
                "subscriptionsActionCompleted": {
                    "on": "subscriptions-action-subscribe-success",
                    "request": "SubscribeActionCompleted"
                },
                "subscriptionsActionFailed": {
                    "on": "subscriptions-action-subscribe-failed",
                    "request": "SubscribeActionFailed"
                },
                "subscriptionsActionRejected": {
                    "on": "subscriptions-action-subscribe-rejected",
                    "request": "SubscribeActionRejected"
                }
            }
        }
        </script>
    </amp-analytics>   
```

While the subscriptions-action-delegated event is fired and we properly track the start of the subscribe flow, none of these events:

subscriptions-action-subscribe-success
subscriptions-action-subscribe-rejected
subscriptions-action-subscribe-failed

is fired.

It seems that in the code of analytics.js related to amp-subscriptions here:
https://github.com/ampproject/amphtml/blob/ad401890b9a0cf4618259e9fb2c46776aa879737/extensions/amp-subscriptions/0.1/analytics.js
success, reject and failed events are not triggered

## Which AMP version is affected?

All

**Comment by dvoytenko** [comment]
/to @prateekbh could you please take a look?

**Comment by prateekbh** [comment]
@justforfun do you have a sample page/dom where you are trying to configure this?
I wonder if it has all the required ` subscriptions-action="login"` attributes on it.

**Comment by justforfun** [comment]
@prateekbh : Here it is the html file
[index.html.zip](https://github.com/ampproject/amphtml/files/2564988/index.html.zip)

**Comment by dvoytenko** [comment]
@prateekbh Did you have a chance to look into this?

**Comment by prateekbh** [comment]
Hi! I just saw the login button and clicking on it seems to be logging the expected events

<img width="1660" alt="screen shot 2018-11-14 at 7 10 50 am" src="https://user-images.githubusercontent.com/5960497/48491538-a7de8680-e7dc-11e8-9973-e0e0965a009e.png">

**Comment by justforfun** [comment]
I'm sorry but I keep on failing to intercept the expected events such as subscriptions-action-subscribe-rejected. This is the analytics code snippet I'm using:
`<amp-analytics>
        <script type="application/json"> {
            "requests":{

                "host": "https://www.facebook.com",
                "base": "${host}/tr?noscript=1",
                "ViewPaywall" : "${base}&ev=ViewPaywall&id=${pixelId}&cd[meter_count]=0&cd[serviceId]=${serviceId}&cd[variant]=${variant}",
                "SubscribeActionDelegated" : "${base}&ev=SubscribeActionDelegated&id=${pixelId}&cd[serviceId]=${serviceId}&cd[action]=${action}",
                "SubscribeActionStarted" : "${base}&ev=SubscribeActionStarted&id=${pixelId}",
                "SubscribeActionCompleted" : "${base}&ev=SubscribeActioCompleted&id=${pixelId}",
                "SubscribeActionFailed" : "${base}&ev=SubscribeActionFailed&id=${pixelId}",
                "SubscribeActionRejected": "${base}&ev=SubscribeActionRejected&id=${pixelId}"
            },
            "vars":{

                "pixelId":"247428115450514",
                "variant": "VARIANT(swg-button-experiment)"
            },
            "triggers": {
                "accessAuthorizationFailed": {
                    "on": "subscriptions-access-denied",
                    "request": "ViewPaywall"
                },
                "subscriptionsActionDelegated": {
                    "on": "subscriptions-action-delegated",
                    "request": "SubscribeActionDelegated"
                },
                "subscriptionsActionStarted": {
                    "on": "subscriptions-action-success-started",
                    "request": "SubscribeActionStarted"
                },
                "subscriptionsActionCompleted": {
                    "on": "subscriptions-action-subscribe-success",
                    "request": "SubscribeActionCompleted"
                },
                "subscriptionsActionFailed": {
                    "on": "subscriptions-action-subscribe-failed",
                    "request": "SubscribeActionFailed"
                },
                "subscriptionsActionRejected": {
                    "on": "subscriptions-action-subscribe-rejected",
                    "request": "SubscribeActionRejected"
                }

            }
        }
        </script>
    </amp-analytics>
`

As you can see from the screenshot I manage to catch the start of the subscribe action but I'm not able to receive any other event. 

<img width="978" alt="schermata 2018-11-20 alle 07 37 28" src="https://user-images.githubusercontent.com/477983/48755987-b1159a80-ec97-11e8-9693-8d8e24f7d56f.png">

I don't even manage to see on the browser console the events you reported in your screenshot. May you suggest me how to switch on that tracking in the console? Have you any hint?

**Comment by dvoytenko** [comment]
@justforfun @prateekbh I see. Looking...

**Comment by dvoytenko** [comment]
@justforfun I think I now see what you mean, but could you please confirm: you're clicking on a SwG offer which pops up the Google payments screen, but you are not seeing the associated event for this. Correct?

If so - I can clearly see that SwG payments screen is not logged in analytics. I can add these events quickly. But please confirm to be certain.

**Comment by justforfun** [comment]
Hi I confirm and I don’t even see any event related to the outcome of the payment 

Inviato da iPhone

**Comment by dvoytenko** [comment]
Fix is in #20257.

**Comment by justforfun** [comment]
We keep on having problems with the firing of the additional events for SwG.
If you look at the reference:
https://amp.dev/documentation/components/amp-subscriptions#analytics
for example given what reported in the document:

_subscriptions-action-ActionName-started
Triggered when the execution of action ActionName starts_


 we should expect the corresponding SwG subscribe event  to be fired:
```subscriptions-action-subscribe-started```

When a user start a SwG purchase flow what we observe is that only the subscriptions-action-delegated event is fired with the following data:

serviceId: subscribe.google.com
action: subscribe

You can replicate the problem following these steps:

1. Access this URL: https://rep.repubblica.it/ws/detail/commento/2019/01/15/news/un_isola_alla_deriva-216660524/#amp-x-swg-button-experiment=swg-paywall-with-google-button

2. With Chrome Enable Local Override and change this code snippet:
```javascript
<script type="application/json">
   {
   "requests": {
   "host": "https://www.facebook.com",
   "base": "${host}/tr?noscript=1",
   "ViewPaywall" : "${base}&ev=ViewPaywall&id=${pixelId}&cd[meter_count]=0&cd[serviceId]=${serviceId}&cd[variant]=${variant}"
   },
   "vars": {
   "pixelId":"247428115450514",
   "variant": "VARIANT(swg-button-experiment)"
   },
   "triggers": {
   "accessAuthorizationFailed": {
   "on": "subscriptions-access-denied",
   "request": "ViewPaywall"
   }
  
 }
   }
   </script>```


with this one:

 ```javascript

<script type="application/json">
 {
               "requests": {                    
               "host": "https://www.facebook.com",
                "base": "${host}/tr?noscript=1",
                "ViewPaywall" : "${base}&ev=ViewPaywall&id=${pixelId}&cd[meter_count]=0&cd[serviceId]=${serviceId}&cd[variant]=${variant}",
                  "SWGDelegated" : "${base}&ev=SWGDelegated&id=${pixelId}&cd[meter_count]=0&cd[serviceId]=${serviceId}&cd[action]=${action}&cd[variant]=${variant}",
                  "SWGStarted" : "${base}&ev=SWGStarted&id=${pixelId}&cd[meter_count]=0&cd[serviceId]=${serviceId}&cd[action]=${action}&cd[variant]=${variant}",
                  "SWGRejected" : "${base}&ev=SWGRejected&id=${pixelId}&cd[meter_count]=0&cd[serviceId]=${serviceId}&cd[action]=${action}&cd[variant]=${variant}"
                },
                "vars": {                    
                    "pixelId":"247428115450514",
                    "variant": "VARIANT(swg-button-experiment)"
                },
                "triggers": {
                    "accessAuthorizationFailed": {
                        "on": "subscriptions-access-denied",
                        "request": "ViewPaywall"
                    },
                    "SWGDelegated": {
                        "on": "subscriptions-action-delegated",
                        "request": "SWGDelegated"
                    },

                    "SWGStarted": {
                        "on": "subscriptions-action-subscribe-started",
                        "request": "SWGStarted"
                    },
                    "SWGRejected": {
                        "on": "subscriptions-action-subscribe-rejected",
                        "request": "SWGRejected"
                    }
                    
                }
            }
</script>


```


3. Install the [Facebook Pixel Helper Chrome Extension](https://chrome.google.com/webstore/detail/facebook-pixel-helper/fdgfkebogiimcoedlicjlajpkdmockpc) 

4. Reload the page and click on the SwG button (Abbonati con Google)
5. You'll see 3 events tracked (View Content, ViewPaywall, SWGDelegated) by the Facebook Pixel Helper while you should have seen 4 events ((View Content, ViewPaywall, SWGDelegated, SWGStarted).

<img width="1256" alt="Schermata 2019-07-02 alle 18 26 51" src="https://user-images.githubusercontent.com/477983/60529523-0a967b00-9cf7-11e9-88bd-2309d1147834.png">

6. Neither the Reject Event is fired. It should be fired when the user closes the product carousel

**Comment by prateekbh** [comment]
cc: // @jpettitt

**Comment by justforfun** [comment]
Hi, 
I managed to track the events, I was expecting to have the subscribe action event at the opening of the  show offers carousel.
When the user taps on the SWG button the ShowOffers event is triggered and when the user taps on a single product then the subscribe action related event is finally triggered.
At the end of the day the events triggering is working properly. 
Thank you!
