### ISSUE TITLE
How can the cache from AMP CDN be controlled ?

### ISSUE THREAD

**Issue by neveldo** [ampproject/amphtml#1901]
Hello,

Sorry if it have been already answered, but I have not found relevant information on this topic within the documentation. I'm wondering how can the cache from the AMP CDN be controlled in order to invalidate a page that has been updated for instance ? Is the HTTP header cache-control taken into account by the CDN ? 

Thanks in advance for your explanation !

**Comment by jugglingcats** [comment]
My limited understanding is that standard cache control headers will be respected, but it would be interesting to know if it's possible to programmatically de-cache a page or subset of pages.

**Comment by cramforce** [comment]
We're currently working on a programmatic solution for invalidation. We respect max-age headers for deciding when to refetch a page, but will keep serving the last known version until we have done so.

**Comment by jugglingcats** [comment]
Thanks @cramforce is there an issue we can follow for this feature?

**Comment by cramforce** [comment]
@jugglingcats we are not currently tracking it in our open source repo, because the cache itself is not open source. Lets just keep this issue open :)

**Comment by neveldo** [comment]
Thanks @cramforce for your answer. So it's possible to prevent the AMP CDN from caching the pages by setting `must-revalidate, max-age=0` for the Cache-Control HTTP header ?

**Comment by cramforce** [comment]
No, the cache always caches and revalidates in the background. There is no
way around that.

**Comment by cramforce** [comment]
There is now (and has been for a while) and update ping mechanism https://developers.google.com/amp/cache/update-ping
