### ISSUE TITLE
amp-selector + amp-bind issues

### ISSUE THREAD

**Issue by mofidsky** [ampproject/amphtml#19017]
hi
we have carousel in witch when clicking on one image the other should update.
we used the regular set state to set the other image source. everything works fine on desktop and android devices but not on ios devices.
[here the link for the page](https://www.m.telexiran.com/%D9%BE%DB%8C%D8%B4%D8%AE%D9%88%D8%A7%D9%86-%D8%B1%D9%88%D8%B2%D9%86%D8%A7%D9%85%D9%87-%D9%87%D8%A7/%D8%B1%D9%88%D8%B2%D9%86%D8%A7%D9%85%D9%87-%D8%A7%DB%8C%D8%B1%D8%A7%D9%86/2018-10-27/amp), test with ios please

**Comment by teksteshqip** [comment]
I have the same problem in all browsers. It may work the first time, but if you refresh the page, it looks like amp-bind is disabled. `[Example Link](https://www.teksteshqip.com/kartolina/step14-26676-0.php)`
This was working fine until Version: 1810091721120 released 19 days ago [Update amp-selector doc with support for disabled](https://github.com/ampproject/amphtml/pull/18547)

**Comment by choumx** [comment]
@mofidksy I can't reproduce. That said, the implemented UX is confusing and possibly wrong. The selector tabs (`div.tabButton`) that change the displayed page are invisible:

![screen shot 2018-10-29 at 6 59 29 pm](https://user-images.githubusercontent.com/20525523/47685504-14d30900-dbad-11e8-9841-3e11fdafc8cf.png)

@teksteshqip I also can't reproduce this on desktop (Chrome, Safari) or mobile (Safari). I also tried refreshing the page several times on each browser. 

For both bugs:
- Which browser/platform/AMP version are you reproducing this on?
- Can you attach a video showing how to reproduce the bug?

**Comment by teksteshqip** [comment]
@choumx [Here is a video reproducing the bug](https://www.teksteshqip.com/kartolina/amp-bind.mp4)
Broswers where I tried:
Desktop: Chrome, IE, Firefox
IOS mobile: Safari, Chrome, UC Browser
I couldn't find a browser where this was working after this AMP version: 1810091721120
If you clear browser's cache, amp-bind will work and it usually will be disabled after you submit the form.

**Comment by choumx** [comment]
@teksteshqip Thanks for the repro video. Are you refreshing the browser at 0:32? If so, I still can't reproduce this on Chrome 70 desktop or Safari iOS 12 with AMP version 1810281911260.

**Comment by teksteshqip** [comment]
Hi @choumx Yes I refresh at 0:32.
I keep trying this in all browsers (also in Chrome 70 desktop or Safari iOS 12) and it happens just like in the video.
Please try  2-3 times submiting the form and then refreshing the page.
I don't know why clearing browser's cache is the only way to enable amp-bind

**Comment by mofidsky** [comment]
Hi @choumx  
the problem only exist in IOS devices like iphone (iphone 7  - ios version 11.0.3)
so i have created a video showing the problem on ios even the problem does not exist on android devices.
[video link](https://drive.google.com/file/d/1_zivaRqeIdnLkha-2lP1Fi3SmhDNzIux/view)

**Comment by choumx** [comment]
Sorry guys, it's still not clear to me what the issue is.
