### ISSUE TITLE
<amp-web-push>: Allow custom scope for SW registration

### ISSUE THREAD

**Issue by demianrenzulli** [ampproject/amphtml#19023]
## What's the issue?

This FR can be related to #14418 for the amp-install-serviceworker component, and it's also mentioned on one of the comments there.

Adding more context here:

*amp-web-push* requires the *service-worker-url* parameter, but doesn't allow to define a custom scope.

The [docs](https://www.ampproject.org/docs/reference/components/amp-web-push) suggest developers to use the [amp-web-push-helper-frame.html](https://cdn.ampproject.org/v0/amp-web-push-helper-frame.html), that's actually in charge of registering the SW. The developer could actually modify this file, hardcode a custom scope and upload a self-hosted version (the line of code for that is [here](https://github.com/ampproject/amphtml/blob/7c850c59b792084b0c2fa8e31cbf4eb8ddbfee52/extensions/amp-web-push/0.1/amp-web-push-helper-frame.js#L235)), but this is not developer friendly (also the helper file is obfuscated which makes it hard to modify).

As an alternative to this, one could just place the SW on a subpath, so, when the component registers it, it will control URLs below that path. This is not currently possible, as it will fail with this error:

"The path of the provided scope ('/') is not under the max scope allowed ('scope').

**Comment by gui-poa** [comment]
Hi @prateekbh . If I understood correctly, both amp-install-serviceworker and amp-web-push, now accept the param data-scope. You just need to update the doc, right?

**Comment by demianrenzulli** [comment]
Hi @prateekbh ,

Bumping this, since @gui-poa comment seem to make sense:

From what you said, it seemed like the data-scope param would be available on the amp-web-push component, but taking a look at the [PR for #19915](https://github.com/ampproject/amphtml/pull/19915/files), it seems it was only added to amp-install-serviceworker.

Maybe we're missing something here?
Thanks.

**Comment by jridgewell** [comment]
This is unrelated to amp-install-serviceworker. Reopening, and assigning to @demianrenzulli.
