### ISSUE TITLE
-webkit-line-clamp property not supported on first paint. 

### ISSUE THREAD

**Issue by iplanwebsites** [ampproject/amphtml#19025]
## What's the issue?

Briefly describe the bug/feature request.
The **-webkit-line-clamp** (for overflow test) doesn't paint properly on initial load.

## How do we reproduce the issue?
Create a **div** with those classes: 
```
    overflow: hidden;
    text-overflow: ellipsis;
    display: -webkit-box;
    display: box;
    -webkit-line-clamp: 4;
```

**Comment by alanorozco** [comment]
Could you specify further about "not painting properly"? What's the expected behavior and what do you see instead?

**Comment by iplanwebsites** [comment]
We need a box with a long text to be clipped at the 4th line.
I'm using responsive typography, so using text-overflow isn't a reliable way to show a balanced amount (4 lines) of text.
So the box doesn't clip on page load. But on browser resize, the expected clipping is triggered.
Do you know what could be a workaround in the meantime?

**Comment by aghassemi** [comment]
The new `amp-truncate-text` https://amp.dev/documentation/components/amp-truncate-text should help here. Please give it a try and raise issues/FRs as needed.
