### ISSUE TITLE
amp-add with smartadserver doesn't work

### ISSUE THREAD

**Issue by okeul** [ampproject/amphtml#1902]
Hello,

I'm trying to use smartadserver with `<amp-add>` but nothing appears and there is an error in the console :
![capture d ecran 2016-02-10 a 12 06 20 pm](https://cloud.githubusercontent.com/assets/6248074/12945636/24214038-cfef-11e5-95c5-f90b5c016afb.png)

Example :
http://output.jsbin.com/qaviwahala/1#development=1

Is it still in progress ?

**Comment by cramforce** [comment]
Would you mind contacting the SmartAdServer support team? They are serving HTTP resources to a HTTPS page which doesn't work.
CC @sebastienferry who contributed the code.

**Comment by sebastienferry** [comment]
Could you add your customer domain in the tag ?
Or if you are not a customer, add https://diff.smartadserver.com
I will open a new PR to have it by default.
Thanks.

`
  <amp-ad width=320 height=50
      type="smartadserver"
      data-domain="https://diff.smartadserver.com"
      data-call="std"
      data-site="94612"
      data-page="629154"
      data-format="38952"
      data-target="foo=bar">
  </amp-ad>
`

**Comment by sebastienferry** [comment]
@okeul : your customer domain is www6.smartadserver.com.
I've updated you jsbin : http://jsbin.com/maruboliha/edit?html,output

Hope this helps

**Comment by okeul** [comment]
@sebastienferry : It works well, thank you ! :-)
