### ISSUE TITLE
Add "refresh" action to amp-access

### ISSUE THREAD

**Issue by fstanis** [ampproject/amphtml#19033]
## What's the issue?

The only way for amp-access to call the authorization endpoint currently is to call the login action, which will spawn a popup window.

It would be good if we could have a "refresh" action, similar to how amp-list has it, e.g. `<a on="tap:amp-access.refresh">Reload data</a>`

One notable use-case this would allow is having a login form on the AMP page itself (when on origin and not on cache):

```html
<form action-xhr="/login" method="POST" on="submit-success:amp-access.refresh">
  <input type="text" name="username" />
  <input type="password" name="password" />
  <input type="submit" value="Login" />
</form>
```

**Comment by dvoytenko** [comment]
This sounds like a good idea to me. @jpettitt do you have any feedback on this?

**Comment by jpettitt** [comment]
SGTM, do we want to add something similar to `amp-subscriptions` ?

**Comment by dvoytenko** [comment]
@jpettitt I think not going to be as useful for `amp-subscriptions` b/c the set of events that can trigger refresh is much stricter and we already trigger refresh in all of those cases.

**Comment by jpettitt** [comment]
Done will be in production in ~2 weeks.

**Comment by sebastianbenz** [comment]
@fstanis can you update your sample once this is live. Might be worth doing a standalone sign-in sample demonstrating all the best practices.
