### ISSUE TITLE
AmpAnalytics analytics Error loading 

### ISSUE THREAD

**Issue by Polylike** [ampproject/amphtml#1903]
Hey,

since yesterday i get this error:

cdn.ampproject.org/v0/amp-analytics-0.1.js:144 AmpAnalytics analytics Error loading remote config:  https://www.myurl.de/include/analytics-config.json Error: Response must contain the AMP-Access-Control-Allow-Source-Origin header(…)(anonymous function) @ cdn.ampproject.org/v0/amp-analytics-0.1.js:144

What to do? Working well before yesterday.

I have changed some .htaccess entry to this yesterday: 

`RewriteEngine On
RewriteCond %{HTTP_HOST} !^www\.
RewriteRule ^(.*)$ $1 [E=WWW_HOST:www.]
RewriteRule ^(.*)_(.*)\.php$ https://%{ENV:WWW_HOST}%{HTTP_HOST}/$1-$2/ [L,QSA,R=301]
RewriteRule ^(.*)\.php$ https://%{ENV:WWW_HOST}%{HTTP_HOST}/$1/ [L,QSA,R=301]
RewriteRule ^(.*)_(.*)/$ https://%{ENV:WWW_HOST}%{HTTP_HOST}/$1-$2/ [L,QSA,R=301]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_URI} !(.*)/$
RewriteRule ^(.*)_(.*)$ https://%{ENV:WWW_HOST}%{HTTP_HOST}/$1-$2/ [L,QSA,R=301]
RewriteRule ^(.*)$ https://%{ENV:WWW_HOST}%{HTTP_HOST}/$1/ [L,QSA,R=301]
RewriteCond %{HTTP_HOST} !^www\.
RewriteRule ^(.*)$ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,QSA,R=301]
RewriteCond %{HTTPS} !=on
RewriteRule ^(.*)$ https://%{ENV:WWW_HOST}%{HTTP_HOST}%{REQUEST_URI} [L,QSA,R=301]
RewriteRule ^([^\-]*)-([^\-]*)/$ $1_$2.php [QSA,L,END]
RewriteRule ^([^\-]*)/$ $1.php [QSA,L,END]`

Can this cause the problems? 

Now i have adding this to the .htaccess
`Header add Access-Control-Allow-Origin "*"
Header add Access-Control-Allow-Headers "origin, x-requested-with, content-type"
Header add Access-Control-Allow-Methods "PUT, GET, POST, DELETE, OPTIONS"
Header add AMP-Access-Control-Allow-Source-Origin "https://www.myurl.de"`

Its working but is it all necessary and correct?

Thanks!
Daniel

**Comment by Polylike** [comment]
Okay i have changed some .htaccess entry to this: `RewriteEngine On

RewriteCond %{HTTP_HOST} !^www\.
RewriteRule ^(.*)$ $1 [E=WWW_HOST:www.]

RewriteRule ^(.*)_(.*)\.php$ https://%{ENV:WWW_HOST}%{HTTP_HOST}/$1-$2/ [L,QSA,R=301]
RewriteRule ^(.*)\.php$ https://%{ENV:WWW_HOST}%{HTTP_HOST}/$1/ [L,QSA,R=301]
RewriteRule ^(.*)_(.*)/$ https://%{ENV:WWW_HOST}%{HTTP_HOST}/$1-$2/ [L,QSA,R=301]

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_URI} !(.*)/$
# RewriteRule ^(.*)_(.*)$ https://%{ENV:WWW_HOST}%{HTTP_HOST}/$1-$2/ [L,QSA,R=301]
RewriteRule ^(.*)$ https://%{ENV:WWW_HOST}%{HTTP_HOST}/$1/ [L,QSA,R=301]

RewriteCond %{HTTP_HOST} !^www\.
RewriteRule ^(.*)$ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,QSA,R=301]

RewriteCond %{HTTPS} !=on
RewriteRule ^(.*)$ https://%{ENV:WWW_HOST}%{HTTP_HOST}%{REQUEST_URI} [L,QSA,R=301]

RewriteRule ^([^\-]*)-([^\-]*)/$ $1_$2.php [QSA,L,END]
RewriteRule ^([^\-]*)/$ $1.php [QSA,L,END]`

Can this cause the problems?

**Comment by Polylike** [comment]
Hello,

okay i have adding this to the .htaccess
`Header add Access-Control-Allow-Origin "*"
Header add Access-Control-Allow-Headers "origin, x-requested-with, content-type"
Header add Access-Control-Allow-Methods "PUT, GET, POST, DELETE, OPTIONS"
Header add AMP-Access-Control-Allow-Source-Origin "https://www.myurl.de"`

Its working but is it all necessary and correct?

Thanks!

**Comment by cramforce** [comment]
You are missing `Access-Control-Expose-Headers: AMP-Access-Control-Allow-Source-Origin`
it is not recommended to set `Access-Control-Allow-Origin` to `*`

Details here:
https://github.com/ampproject/amphtml/blob/master/spec/amp-cors-requests.md

**Comment by Polylike** [comment]
`Header add Access-Control-Allow-Origin "https://cdn.ampproject.org"
Header add AMP-Access-Control-Allow-Source-Origin "https://www.myurl.de"
Header add Access-Control-Expose-Headers "AMP-Access-Control-Allow-Source-Origin"
`
Right?

Thanks a lot!

**Comment by cramforce** [comment]
Right, for Access-Control-Allow-Origin you may also sometimes wan to
respond https://www.myurl.de if the request comes from your own site,
though.
