### ISSUE TITLE
Discovery clarification

### ISSUE THREAD

**Issue by julien51** [ampproject/amphtml#1905]
Based on my understanding of the docs, discovery of an AMP ressource is done thru a `<link>` element in the `<head>` section of the HTML document...  This means that a User-Agent which supports AMP will have to fetch the HTML doc to know that there's indeed an AMP document. This surely wastes at least one expensive HTTP request and some processing to parse at least this part of the HTML.

Is there another type of discovery to avoid this roundtrip? Maybe based on [Content Negotiation](https://en.wikipedia.org/wiki/Content_negotiation)?

**Comment by cramforce** [comment]
@julien51 The general idea is that platforms supporting links would crawl the link they have anyway and then discover there is also an AMP version. Content negotiation would be great for an "I prefer AMP" browsing mode, but that would require actual browser support.

**Comment by julien51** [comment]
Thanks for the answer!
Well, that's not just browsers... there are User-Agents (such as search engine crawlers!) which may not need to fetch the HTML first.
Also, from the SERPs on mobile, you'll surely be linking to the AMP version, right? If so, then, do you "cache" the fact that there's an AMP for a given HTML doc so you link to the right doc (AMP on mobile, HTML on desktop)?

**Comment by cramforce** [comment]
In general AMP is not a mobile-only technology, it works great for desktop.
Google initially will only use AMP for mobile users, though.
