### ISSUE TITLE
<amp-video> NO VOLUME CONTROL

### ISSUE THREAD

**Issue by nakigoe** [ampproject/amphtml#19063]
my AMP page:
<h1><a href="https://nakigoe.github.io/articles/as.html">girls</a></h1>

Why there is no volume control for hosted video?

**Comment by jpettitt** [comment]
Conformed video player on Chrome is not showing volume control (just mute / unmute)

**Comment by aghassemi** [comment]
@nakigoe Chrome team has fixed this and next version (I just tested with Chrome Canary 72) will have a volume slider.

(amp-video uses HTML5 video behind the scene as @jpettitt alluded to)

**Comment by aghassemi** [comment]
Closing per comment above (fixed in Chrome 72)
