### ISSUE TITLE
amp-live-list: reference point update problem on google cache

### ISSUE THREAD

**Issue by spinmar** [ampproject/amphtml#19060]
Hi,
I have a problem on reference point update in tag amp-live-list on google amp cache.
On my server in page with amp-live-list, when there are new items the reference point (a button) is shown and on tap they are seen by users and the button is hide.
When the page is served by google amp cache, on tap the button is not hide. The new items are inserted correctly and the button (reference point) is always visible. While using cdn.ampproject.org cache all is ok.
Did anyone have this problem with google amp cache?
Thanks

**Comment by spinmar** [comment]
It seems that the problem is related to the fact Google amp cache serves the page in an iframe and when there is an update Google puts the button outside iframe and amp-live-list js is not able to hide it in tap.
Is it a bug?

**Comment by spinmar** [comment]
Did anyone experimented this problem?

**Comment by spinmar** [comment]
I'm discussing about this problem also in Google amp forum (Peter):

[https://productforums.google.com/forum/#!msg/webmasters/PLxvgtvS-pw/FCpa7I5kAwAJ](url)

What is not clear is that it is a bug of amp-live-list.js or a Google amp cache problem.
Maybe if some developers could reply....

**Comment by choumx** [comment]
I'm having trouble understanding the issue you're having. Can you share a URL to a page that shows the error?

**Comment by spinmar** [comment]
Hi,
you can check the problem during the next live cached by Google cache.
The url, visible from 15:00 (italian time) of 8th december will be:

`__https://www.google.it/amp/s/sport-pp.virgilio.it/dirette/live/serie-a/8-12-2018/napoli-frosinone/4594/amp/`

Please remove __ in front of url.
Bye

**Comment by aghassemi** [comment]
Closing as stale. Please reopen with more details if this is still an issue. Thank you.
