### ISSUE TITLE
Breaking change with amp-list and CORS variable substitution in AMP 1810301740350

### ISSUE THREAD

**Issue by mikeswright49** [ampproject/amphtml#19061]
## What's the issue?

A change was introduce which updated how the amp-list handles CORS variable replacements. This causes an issue where an error is thrown and the amp-list can no longer hydrate.

`Error fetching amp-list: URL variable substitutions in CORS fetches from dynamic URLs (e.g. via amp-bind) require opt-in. Please add data-amp-replace="CLIENT_ID(ghs-amp-pages)" to the <AMP-LIST> element.`

Previously this was handled with 

`data-amp-replace="CLIENT_ID" >`

## How do we reproduce the issue?

jsbin

https://jsbin.com/nilijuh/4/edit?html,output

Gist
https://gist.github.com/mikeswright49/9c490ec8f77d10e4d7defa05da5a47d8

1. Update amp-list binding to ="CLIENT_ID"
2. Type into the input box
3. Validate issue in console
4. Update amp=list binding to ="CLIENT_ID(a-key)"
5. Type into input box
6. Reset to validate issue gone

## What browsers are affected?

All browsers

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1810301740350

**Comment by choumx** [comment]
This was changed from a warning to an error about six months ago in #15009. Context: #12498

**Comment by choumx** [comment]
@mikeswright49 Can you provide some context on why this appears to be a new change for your use case and its impact?

**Comment by mikeswright49** [comment]
So this has been working in our PP/RC candidate environments for a month or so with data-amp-replace="CLIENT_ID". Within the last 24 hours we're now getting this updated error requiring us to use data-amp-replace="CLIENT_ID(a-key)" as a result we believed that it was tied to the previous release.

**Comment by mikeswright49** [comment]
The concern here is that the list is not populating for a key component on our platform, which would be  removing the main user functionality on our pages.

**Comment by choumx** [comment]
I can reproduce this. Behavior changed between 1810281911260 and 1810301740350 and culprit PR must be [one of these](https://github.com/ampproject/amphtml/releases/tag/1810301740350). Investigating further.

**Comment by choumx** [comment]
This is a bug. `data-amp-replace="CLIENT_ID"` is the correct usage and we're working on a fix.

**Comment by choumx** [comment]
This is fixed in version 1810312337520.
