### ISSUE TITLE
Why is Google tracking inside of: https://cdn.ampproject.org/v0.js ?

### ISSUE THREAD

**Issue by rmaddox** [ampproject/amphtml#1907]
I was just thinking to update my CMS, to produce AMP pages for each page, to speed up the user experience, then I discovered that Google tracking, adsense stuff and doubleclick is in the default Javascript https://cdn.ampproject.org/v0.js

Of course we all want Google to index pages, but this kind of tracking is not chosen by webmasters. We refuse Google Adsense and any kind of tracking by Google. It does not contribute to privacy.

Project is open source, but Google adsense, doublclick and tracking is in the Javascript of each of the pages. 
```
adform:"https://track.adform.net",adreactor:"https://adserver.adreactor.com",adsense:"https://googleads.g.doubleclick.net",taboola:"https://cdn.taboola.com",doubleclick:["https://partner.googleadservices.com",
"https://securepubads.g.doubleclick.net","https://tpc.googlesyndication.com"],dotandads:"https://bal.ad.dotandad.com"},
```

**Comment by cramforce** [comment]
The open source code is here https://github.com/ampproject/amphtml/blob/master/ads/_config.js#L25
This will **only** run when you actually actively integrate the respective ad types into your page. You can easily verify this by looking at the requests that are being made through your browser's devtools.

This is specifically a preloading list which is why it has to be included into the JS before it is know whether it will be used.

**Comment by rmaddox** [comment]
One could then ask if the preloading is making mobile pages faster, why not pre-load also other advertising networks? I understand you work for Google and that is why you think the matter shall be closed.

**Comment by cramforce** [comment]
As the link above shows this is not only used by Google networks (2
Google, all others are non-Google), but rather all networks that have sent
pull requests.

**Comment by rmaddox** [comment]
So Javascript gets pre-loaded.  How does that contribute to philosophy of making something fast?

And how many new pre-loaded scripts by other companies are yet to come?

I thought Internet technology shall be free.

**Comment by cramforce** [comment]
It is only preloaded if it will then later be used. If your page has no
ads, nothing will be preloaded. If it only has Amazon A9 ads, only those
will be loaded, etc. This is only to flatten request waterfalls which
greatly improves performance.

**Comment by rmaddox** [comment]
Thank you for your nice answer, if it is really like that, and I did not check it out, it is not a big deal. But simple existence of those links in the .JS for the onlooker is suspicious. That shall be put in documentation and not to be discovered by accident, as in that way, it looks like a conspiracy.

I will certainly try to implement it in my CMS. 

I only need to understand how to use pandoc or other markdown to get the img converted to amp-img
