### ISSUE TITLE
🌸 Cherry pick request for #19061 into #18971 (Approved)

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#19073]
**GitHub issue your cherry pick is fixing:**

Issue #19061 

**PR that you are requesting a cherry pick for:**

PR #19069 

**Release(s) you requesting this cherry pick into:**

Production Release? YES  1810301740350

Canary release? YES 1810241929000

*Why does this issue meet the [cherry pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?  Be specific.*

~~This is breaking all uses of `CLIENT_ID` when used with the `data-amp-replace` attribute.~~
EDIT: This was an overstatement, it is breaking everywhere `CLIENT_ID` is used with `data-amp-replace` in `amp-list` and potentially anywhere else fetching json with this mechanism

*Assign this issue to the current TL (cramforce) if you have permission to, otherwise leave this cc line in.*

/cc @cramforce @alanorozco

**Comment by calebcordry** [comment]
cc/ @lannka @choumx

**Comment by cramforce** [comment]
Approved
