### ISSUE TITLE
🌸 Cherry pick request for #19079

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#19081]
GitHub issue your cherry pick is fixing:

Issue #19080

PR that you are requesting a cherry pick for:

PR  #19079

Release(s) you requesting this cherry pick into:
Production Release? YES 1810312123110
Canary release? New canary will include fix.

Causes breakages to existing publisher stories because grid layers with template="vertical" don't necessarily have to be 100% height

/cc @alanorozco

**Comment by dvoytenko** [comment]
LGTM
