### ISSUE TITLE
I2I Add publisher definable user agent based override to amp-subscriptions

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#19098]
## Context
`amp-subscriptions` when operating as a client side paywall provides a mechanism for publishers to suppress some or all of the page content for users who do not have a subscription.  Subscription verification is obtained by a CORS request to a publisher supplied endpoint (or a service provided endpoint in the case of `amp-subscriptions-google`.)

## Problem
Canonical pages often grant access to web crawlers (robots) by matching the user agent in the client, removing the need for a CORS request.

If a robot accessing the AMP page is not granted access by the publisher end point and the robot renders the AMP page in a headless browser it may ignore content that is not visible on the resulting page. 

This can generate content mismatch errors in Google Search Console when AMP and Canonical version of the page apply different robot access strategies. 

The server load in the form of uncached requests to the authorization endpoint can represent a significant load on larger sites.

## Proposal: Add User Agent Matching to amp-subscriptions.
Adding the ability to grant access based matching a user agent string will allow a common robots access strategy between AMP on Canonical pages.  It will also reduce the load on authorization endpoints from crawler requests.

## Design

This proposal adds an additional section to the #amp-subscription JSON

````
<script type="application/json" id="amp-subscriptions">
{
  "services": [...],
  "score": {...},
  "fallbackEntitlement": {...}
  "allowedUserAgents" :  [    // Example user agent matches
     "googlebot",
     "google webmaster tools",
     "bingbot",
     "yahoo! slurp",
     "baiduspider",
     "yandexbot",
     "duckduckbot"
   ]
}
</script>
````

The supplied user agent strings will be escaped, concatenated to form a regular expressions and matched against  `window.navigator.userAgent` (if it exists)

## Security considerations

We considered publisher supplied regular expressions and decided aginst as it is possible to create a regex that with [O(2^n)](https://www.regular-expressions.info/catastrophic.html) behavior resulting in non reponsive browsers.

## Compatibility

This feature is not compatible with server side paywalls.

**Comment by jpettitt** [comment]
From a discussion with @cramforce a month or so ago.

cc @dvoytenko @chenshay

**Comment by dvoytenko** [comment]
The markup of amp-subscriptions article indicates explicitly which sections are premium. It's fairly easy for indexers to take that into account. I'd rather avoid client-side override. That'd also not be compatible with any "server-side" strategy we decide to adopt.

**Comment by jwold** [comment]
Just want to make sure I understand the intent of this feature, coming from someone with more of a design than development background. 

1. Are we hoping to solve the problem of mismatched errors ONLY from a client-side perspective?
2. If so, is there any proposal for how this could work on a server side paywall, or is that simply not an option? 
3. Could you point me to a working page with amp-subscriptions? This is a feature I haven't played with yet, so would love to is it in the wild!

**Comment by jpettitt** [comment]
@jwold . We're looking at solving a specific client side use case.  Existing client side paywalls tend to have some sort of bot match (the match list in the example config came from looking at the source code of a large US publisher).  It's not the ideal solution and it's not compatible with server side paywalls.  We're looking at a different server side strategy for `amp-subscriptions`, it's still being reviewed internally.

Amp subscriptions is on www.washingtonpost.com or www.ft.com amongst others.

**Comment by jpettitt** [comment]
Closing as obsolete given the incompatibility with server side paywalls.
