### ISSUE TITLE
Clarify empty inputmask behavior 

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#19093]
> Mask does not show up when first focusing, but remains showing if you delete all text. Feels like it should be consistent when focused, has no text.

What should the input box show when the input is empty? Should it show the placeholder? Should it show no input?

#19089 is a special case of this issue, which asks "When the user tries to empty the input, should the mandatory characters of the mask remain in the input?"

/to @spacedino (and Andrew)

**Comment by nainar** [comment]
cc @andrewwatterson

**Comment by andrewwatterson** [comment]
I think it should show the placeholder or be empty (if no placeholder). The argument for showing only the mandatory characters for a mask is that it helps the user understand what to put there, but ideally developers will include a placeholder to cover that.

**Comment by cvializ** [comment]
Agreed. Since this is the current behavior, I'll close this issue. Thanks @andrewwatterson!
