### ISSUE TITLE
amp-date-picker regression when used in amp-lightbox

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#19109]
Reported by @JakobEichler https://github.com/ampproject/amphtml/pull/18691#issuecomment-435115380 as possible cause

> Hello, since Monday we had no bookings on our mobile version of www.parkscanner.de
> 
> The date-picker was broken, and we made no changes on the date-picker and the AMP site at all.
> 
> I do not know if the issues came with this update or with an other one, anyways here are two sites, which worked before any AMP updates.
> 
> https://www.parkscanner.de/amp/bug-report2.html
> https://www.parkscanner.de/amp/bug-report.html
> 
> Now I fixed those date-pickers temporarily by removing the display: flex; attribute on the ".amp-date-picker-calendar-container" class.
> 
> What has not yet been fixed is the way we display conditional messages in the info-template (bellow the date-picker) depending on which date needs to be entered. This worked some days ago and now also stopped to work.
> 
> Earlier bellow our date-picker on (for example www.parkscanner.de/amp/ ) only one of these messages was displayed:
> 
> Bitte wähle Dein Abreisedatum aus.
> Bitte wähle Dein Anreisedatum aus.
> 
> Now I see both of them, as the .hide action does not work anymore before the template is rendered fully. We now see this error in the console, after clicking in the form field to open the date-picker:
> 
> Target "anreise_first" not found for action [tap:anreise_first.show,abreise_first.hide,lb1_0.open].
> 
> Target "abreise_first" not found for action [tap:anreise_first.show,abreise_first.hide,lb1_0.open].
> 
> Thank you for your great work with developing and maintaining the amp project that makes mobile pages much faster 👍 :)

Issues:
- amp-date-picker changed to not appear without any site changes
- hide action does not work before template is rendered, and console error appears

**Comment by cvializ** [comment]
I want to figure out what changed to cause the date picker to not appear as in your bug-report links, and I'm currently investigating that.

For the template element issue, if the elements need to be hidden on the first render, then you should use the `hidden` attribute and then either call the `.show` action or bind to `[hidden]` when the messages need to be shown.

**Comment by JakobEichler** [comment]
cvializ, thanks for pointing out that the hidden attribute is recommended. I agree with you. Anyways when using the hidden attribute, this would not solve our current issue. Because the element is not available after the amp update anymore before the date-picker is rendered. Saying this, the .show action would result in an error.

**Comment by JakobEichler** [comment]
Hello cvializ, are there any updates concerning this issue? Is it possible for you to reproduce to before and after version?

**Comment by cvializ** [comment]
Sorry about the lack of updates! I was able to reproduce on the before version, and the after version is fixed. I have not yet found the root cause, but I am continuing to investigate.

**Comment by JakobEichler** [comment]
Hello @cvializ , are there any updates? I am ready to schedule a skype call with you and provide more information about the issue we had with the date picker, which was shipped with an amp update.

Skype: j.a.eichler ;)

**Comment by cvializ** [comment]
: ) I found some time to bisect the commits to find the first commit with the different behavior. It looks like it's https://github.com/ampproject/amphtml/pull/18691 and I'm continuing to investigate why it changed things.

**Comment by cvializ** [comment]
This issue should be fixed following the [AMP release schedule](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md), and should be live in production in about 2 weeks. Thanks again for reporting this!

**Comment by JakobEichler** [comment]
@cvializ Thank you very much. The things that changed are bascially from my perspective
1.) visibility of the date picker, when using the above named css propperty to center it
2.) the texts bellow the date picker & the possibility to hide/show elements which are in the <template> of the datepicker, before the datepicker is opened.

Thank you so much for taking this seriously and improving the AMP code.

**Comment by JakobEichler** [comment]
Hopefully you observed both incidents and both will be fixed. Not only 1.) ; )

**Comment by cvializ** [comment]
I believe both issues had the same root cause, so they should be fixed now. I am seeing the correct messages at the correct time, and the date picker is positioned correctly. Those reproduction documents really helped, thank you for making them!
