### ISSUE TITLE
Enable focusable attribute on SVGs

### ISSUE THREAD

**Issue by jtart** [ampproject/amphtml#19107]
## What's the issue?

SVGs have a `focusable` attribute that is used to take SVG's out the tab order for keyboard and assistive technology users who use Internet Explorer. JAWS is the main assistive tech library used for this case. See the [w3 spec](https://www.w3.org/TR/SVGTiny12/interact.html#focus-api).

When the the `focusable` attribute is set to `false`, the AMP validator fails with the message ` The attribute 'focusable' may not appear in tag 'svg'. (see https://www.ampproject.org/docs/reference/spec#svg)`. 

## How do we reproduce the issue?
Run `npx amphtml-validator https://www.test.bbc.com/news/articles/c9rpqy7pmypo.amp` and note the failing test on SVGs.

## What browsers are affected?

[Internet Explorer is the only browser](https://allyjs.io/tutorials/focusing-in-svg.html#browser-compatibility) that implements `focusable`.

## Which AMP version is affected?

All versions.

**Comment by aghassemi** [comment]
/to @Gregable unless there was a security reason ( I can't think fo any ), we should allow this.

**Comment by jtart** [comment]
Hi @Gregable, @westonruter, thanks for doing this work. When I run the `amphtml-validator` CLI tool, SVG `focusable` is still failing. Has an update to the CLI been published?
