### ISSUE TITLE
Mic AMP story Content bleed off problem

### ISSUE THREAD

**Issue by hongwei1990** [ampproject/amphtml#19101]
## What's the issue?

In this mic story https://mic.com/stories/484/will-young-voters-turn-out-in-the-midterm-elections. 10% of the bottom page content bleed off. The system equalizer icon getting bleed off too.
![6317090833380770816](https://user-images.githubusercontent.com/33703058/47882162-d1171400-dde5-11e8-95ca-3f233bceed72.png)

## What browsers are affected?
all browsers, also GSAs 

Is this a new issue? Or was it always broken? Paste your AMP version. You can find it in the browser dev tools.

new issue 
@newmuis @gmajoulet @Enriqe

**Comment by newmuis** [comment]
This seems like #19080.  We should have a cherrypick to fix.

**Comment by newmuis** [comment]
Verified that this appears fixed now that #19080 is fixed.
