### ISSUE TITLE
"Cannot read property 'create' of undefined" in Shadow AMP

### ISSUE THREAD

**Issue by morsssss** [ampproject/amphtml#19112]
This error gets emitted at least once, sometimes twice, on [Shadow Reader](https://amp.cards) pages.  See, for example, https://amp.cards/theguardian/us/business/2018/nov/02/shares-soar-as-trump-hints-at-possible-us-china-trade-deal

I assume the third error in the screenshot below comes from `<amp-analytics>`.

I wonder also if this is related to #17997 .

![screen shot 2018-11-02 at 2 50 36 pm](https://user-images.githubusercontent.com/29419498/47934825-e015c900-deae-11e8-886b-6d8de59ec496.png)

**Comment by choumx** [comment]
Looks like the same cause as #17997. Closing as dupe.
