### ISSUE TITLE
Whitelist Validator issue with decoding attribute in images

### ISSUE THREAD

**Issue by ayumihamsaki** [ampproject/amphtml#19121]
I have the following code example:

```
<amp-img layout="responsive"
    class="photo"
    src="/example-image.jpg"
    alt="something"
    width="686"
    height="415">
    <noscript>
        <img role="img"
        class="photo"
        src="/example-image.jpg"
        alt="something"
        decoding="auto"
        width="686"
        height="415">
    </noscript>
</amp-img>
```

AMP Validator Issue: **The attribute 'decoding' may not appear in tag 'img'. Debug. Learn more.**

Please note: I am using `decoding="auto"` in the `noscript` tags section. This is a validate HTML Attribute under the HTML Spec see here: https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-decoding

Therefore I believe this attribute should be added to the whitelist.

**Comment by honeybadgerdontcare** [comment]
@aghassemi 	Do you see any issue allowing the `decoding` attribute on an `img` tag when `img` has a `noscript` ancestor?
 
https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii#L1968

**Comment by aghassemi** [comment]
@honeybadgerdontcare no, SGTM. (amp-img already implicitly sets decoding on the internal img too)

**Comment by honeybadgerdontcare** [comment]
This will be live in production in 1-2 weeks.

**Comment by ayumihamsaki** [comment]
@honeybadgerdontcare Thank you!
