### ISSUE TITLE
Public feedback for AMP Story ads

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#19124]
Placeholder for the community to provide feedback about AMP Story ads.

**Comment by vbarshai** [comment]
Hi @jasti ! Super excited about AMP Story ads integrations, for someone with a DFP account, where is the best place to find documentation to add inventory to serve AMP Story ads from the inventory?

**Comment by jasti** [comment]
@vbarshai glad to hear that! https://support.google.com/admanager/answer/9038178

**Comment by jasti** [comment]
@ipauler AdSense auto ads support isn't available but you should consider reaching out in the AdSense support channels to request it.

**Comment by ipauler** [comment]
@jasti Ok thanks. How can we get publisher support ?

**Comment by calebcordry** [comment]
Closing as this is a bit outdated. You can find many documents at the new amp.dev. Feel free to reopen this issue with any specific questions.
