### ISSUE TITLE
Can't submit forms in Safari, Edge or IE.

### ISSUE THREAD

**Issue by rahulkhosla** [ampproject/amphtml#19130]
## What's the issue?

Can't submit a form in Safari. I get the error "Failed to parse response JSON: SyntaxError: The string did not match the expected pattern." in the search console.

## How do we reproduce the issue?

1. Open Safari, go to this [amp-website](https://pointandquack.com/contact/)
2. submit the contact form(s)
3. Check the developer's console
4. Reproduce this in Chrome or Firefox to see needed results

The same happens in Edge and IE.

You can view the [form-handler code](https://pastebin.com/pPPuD1yW) here.

## What browsers are affected?

Safari version-12 (I'm testing on a MacBook Pro).
Edge (latest, testing on a Windows laptop).
IE (latest, testing on a Windows laptop).

## Which AMP version is affected?

Using AMP-form version-0.1 and AMP-mustache version-0.2.

**Comment by rahulkhosla** [comment]
CC @dvoytenko

**Comment by rahulkhosla** [comment]
I've fixed it!

if ( ! isset( $_POST['conact_form'] ) ) {

<form name="contact_form">

**Comment by cvializ** [comment]
Hi @rahulkhosla thanks for opening this issue, I'm not able to reproduce on other sites so it must have only been a problem in the pasted code.
