### ISSUE TITLE
Publish GitHub releases on promotion

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#19143]
Can we automate the publishing of GitHub releases during promotion? It's often forgotten as part of "on duty" rotation.

Looks like using this API with `draft: false` will publish an existing release: https://developer.github.com/v3/repos/releases/#edit-a-release

**Comment by rsimha** [comment]
@Marcial1234 Can you see if this can be done by the release automation?

**Comment by Marcial1234** [comment]
It should be. It's noted as TODO.

**Comment by rsimha** [comment]
Assigning to @danielrozenberg who is working on release automation. Feel free to close this and track internally.

**Comment by erwinmombay** [comment]
Closing this. I believe in our last conversation it was decided that we still want this to be an explicit action
