### ISSUE TITLE
Rendering of Google Ads on AMP pages

### ISSUE THREAD

**Issue by Programmatic1000** [ampproject/amphtml#19158]
Hi@all

we're using AdSense via separated booked LineItems per ad unit (group) in Google Ad Manager, but do have some problems with the delivering of Adsense Ads. Just blanks, unless this line item is running on sponsorship level for a test.

The creatives are delivered via the Third Party Tag Template in Google Ad Manager, using HTML type "AMP". 

```
<amp-ad width=300 height=250
  type="adsense"
  data-ad-client="ca-pub-XXXXXX.."
  data-ad-slot="3096044892">
</amp-ad>

```
You can see this AdSense Ad via Admanager live on the following page - only on desktop device: https://www.coolibri.de/magazin/inspiration/
it's been delivered in id "promWrapper5". on the left side, below the fold. Blank..

Moreover we tried to replace the Ad Manager Ad Unit tag with AdSense to find out, if Google Ad Manager is responsible for the issue. Unfortunately we do have the same problem here and no ad is shown.

```
<amp-ad
   width=728
   height=90
   type="adsense"
   data-ad-client="ca-pub-8909329461388579"
   data-ad-slot="2908332890">
</amp-ad>
```

URL: https://www.coolibri.de/autoren/larissa-schueler/

Some other AdSense Ads which where implemented the last days on other positions stopped delivering in the night from Oct 28 to Oct 29. Any known issues?

Many thanks

**Comment by aghassemi** [comment]
to @lannka

**Comment by lannka** [comment]
@jasti do you know who from AdSense should be involved to look into this?

**Comment by Programmatic1000** [comment]
Good News. Problem Solved. Reason was a missed checkmark for "dynamic allocation" in settings of the selected adsense account OR/AND a missing information in the ads.txt with the pub-id of the adsense account. I'm not really sure, but seems to be something like that. If anyone had problems the last day like this - please let me know.

One last thing: It's still not so clear how to create AdSense Creatives within Google AdManager by using a Lineitem Priority like "Price Priority" or House and selecting the Creative Template Third Party Template. (AMP, safeframe, no safeframe.....) Many open questionmarks and not really support in the google help section.

**Comment by lannka** [comment]
Sounds like those are non-AMP specific questions and should have been answered on a AdSense or Google AdManager forum.
