### ISSUE TITLE
Cannot play video after refocusing on document

### ISSUE THREAD

**Issue by gordon225** [ampproject/amphtml#1915]
I noticed that if videos in amp-youtube were not playing when you leave the browser tab, you won't be able to play them after returning to the tab. The player controls are greyed out, and only thing you can tap is the playlist. Tested on Nexus 6p and iPhone 6, using both Chrome and Safari.

**Comment by cramforce** [comment]
@mkhatib Could you take a look?

**Comment by mkhatib** [comment]
This seems to be due the `pause` command being executed before the player even play. Working on a to check if the player is already playing and only then send the pause command.
