### ISSUE TITLE
Compile code snippets into blobs for workers/worklets

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#19155]
**Please only file bugs/feature requests for AMP here.**

## What's the issue?
Use case: In `web-animations.js` we create a string that is essentially a function see [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-animation/0.1/web-animations.js#L208). This code is then added to a worker as can be seen [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-animation/0.1/web-animations.js#L236). We should be able to write these as normal functions (hence get syntax highlighting etc) and then use these in workers.  

cc @aghassemi @kristoferbaxter @choumx @rsimha

**Comment by choumx** [comment]
Compilation would be great too. :) 

Seems like you'll need the output a new standalone binary to get a URL to pass to `addModule()`. Doesn't exist yet in our build infra but should be straightforward to add support, similar to `cssBinaries` that we have currently. I had a PR that did this awhile back but reverted the change for simplicity.

**Comment by choumx** [comment]
The relevant code today: https://github.com/ampproject/amphtml/blob/eb6b8ffeb1e1eb9105343ff8447f2c7916928a73/extensions/amp-animation/0.1/runners/scrolltimeline-worklet-runner.js#L141-L159

**Comment by rsimha** [comment]
Infra hasn't had the bandwidth or the context to take this on. Moving to WG-runtime for triage / prioritization in light of https://github.com/ampproject/amphtml/issues/19155#issuecomment-438044207.
