### ISSUE TITLE
🌸Cherry pick request for #19161

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#19165]
**Replace *everything* in angle brackets in the title AND body of this issue.  If you have any questions see the [cherry pick documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-picks).**

**GitHub issue your cherry pick is fixing:**

Issue #19126

**PR that you are requesting a cherry pick for:**

*(Put N/A if you do not yet have a PR with a fix; edit this issue to add it when the PR is ready.)*

PR #19161

**Release(s) you requesting this cherry pick into:**

*Release issues can be found at https://github.com/ampproject/amphtml/labels/Type%3A%20Release*

*If you are requesting a cherry pick into a production release you will most likely need to cherry pick into canary as well, otherwise when the canary is pushed to production your fix will be lost.  See the [cherry pick documentation](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-picks).)*

Production Release? NO  

Canary release? YES  If yes, Type: Release Issue #19166

*Why does this issue meet the [cherry pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?  Be specific.*

This is a regression potentially can break analytics tracking who uses `extraUrlParams` feature. (A couple of vendors use it in their default setting). The symptom is that any URL macro used in `extraUrlParams` can be double encoded.

For example:

```
extraUrlParams: {
  df: ${documentReferrer}
}
```

will have the URL of `documentReferrer` double URL encoded.

*Assign this issue to the current TL (cramforce) if you have permission to, otherwise leave this cc line in.*

/cc @dvoytenko @cramforce @cvializ @calebcordry

**Comment by dvoytenko** [comment]
Approved.
