### ISSUE TITLE
AMP breaks url-based content filters

### ISSUE THREAD

**Issue by duane** [ampproject/amphtml#19170]
This applies to all url-based content filters, but I am writing specifically based on firefox focus.

For instance, if you block reddit.com, it is still easily accessible via searches from engines which integrate AMP, which rather defeats the point of content filters.

Possible solution: allow an opt-out that either links to the search result or redirects to it. Alternatively, make AMP opt-in, or somehow allow loading AMP results from the domain of the content.

Either way, this makes search engines that enable AMP integration problematic in the current state.

**Comment by duane** [comment]
Another option would be to allow blacklisting urls at the AMP or search engine level.

**Comment by jpettitt** [comment]
This is not an AMP bug, it's a content filter bug. All url based content filters are going to be trivially bypassed via proxy or cache servers. 

AMP cache urls are deterministic and contient filters can can easily add code to map canonical -> camp cache urls if they want to filter AMP pages. See [AMP Cache URL format](https://developers.google.com/amp/cache/overview)
