### ISSUE TITLE
A9 Integration with AMP

### ISSUE THREAD

**Issue by dthukral-amazon** [ampproject/amphtml#19187]
As per issue #18939, I was told my changes, that were merged on 25th October, would come in production within 7-14 days.
It is requested to plz let me know when it would come in production, as our customers are waiting.

**Comment by aghassemi** [comment]
@dthukral-amazon Our next release is on 11/13. Please follow us on #release channel on our Slack for up-to-date release schedule. You can sign up to join Slack [here](https://docs.google.com/forms/d/e/1FAIpQLSd83J2IZA6cdR6jPwABGsJE8YL4pkypAbKMGgUZZriU7Qu6Tg/viewform?fbzx=4406980310789882877).

Thanks
