### ISSUE TITLE
Cherrypick reauthorization in subscriptions to canary

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#19180]
GitHub issue your cherry pick is fixing:

b/119114010

PR that you are requesting a cherry pick for:

PR #19178

Release(s) you requesting this cherry pick into:

1810241929000 (canary)

Production Release? NO

Canary release? YES

Why does this issue meet the cherry pick criteria? Be specific.

A significant bug where the page is not reauthorized post account linking.

/cc @jpettitt

**Comment by cramforce** [comment]
Approved

**Comment by jpettitt** [comment]
cc @cvializ
