### ISSUE TITLE
Update positioning of absolute elements in amp-story

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#19195]
We sometimes position elements that take the whole width and height of their space by specifying: 

`top:0;` `left:0;` `bottom:0;` `right:0;`

We should use: `top: 0 left: 0 width: 100% height` instead, since what we use now has some caused some bugs. e.g. #13433

**Comment by newmuis** [comment]
The bugs are only relating to grid areas, so I think we're probably okay.
