### ISSUE TITLE
Unregister service-worker using amp-install-serviceworker component

### ISSUE THREAD

**Issue by andreyMakahov** [ampproject/amphtml#19205]
## What's the issue?

Impossible to unregister ServiceWorker using amp-install-serviceworker component.

The reason why we need the feature is because we have to unregister service-worker, if something goes wrong after deploy. The only thing we can do is redeploy application with new service worker file, but it will take some time. We want to unregister service worker immediately (we can do it using dynamic switch, which can register/unregister service-worker).  Would be great if we add one more property to amp-install-serviceworker component to unregister service-worker.

Your prompt assistance is very appreciated!

## What browsers are affected?

All browsers

**Comment by jridgewell** [comment]
An attribute in the HTML is likely the wrong place for this, because it would require all CDNs to re-ingest the doc, but there's no API to do it in the SW itself.

So, if it's really necessary, you should be doing as much cleanup in the SW itself. We can then add an unregister attribute to finalize the unregister when the doc is re-ingested.

**Comment by andreyMakahov** [comment]
Yes, unfortunately, I can't [unregister](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/unregister) the service worker inside my service-worker file.

In my understanding we have two choices how to archive it:
1. Add new attribute to amp-install-serviceworker component and call [unregister API](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/unregister) there
```html
<amp-install-serviceworker
  unregister="true"
  src="https://www.your-domain.com/serviceworker.js"
  data-iframe-src="https://www.your-domain.com/install-serviceworker.html"
  layout="nodisplay">
</amp-install-serviceworker>
```
2. Create another simple component to unregister service worker
```html
<amp-uninstall-serviceworker
  src="https://www.your-domain.com/uninstall-serviceworker.js"
  data-iframe-src="https://www.your-domain.com/uninstall-serviceworker.html"
  layout="nodisplay">
</amp-uninstall-serviceworker>
```

**Comment by jridgewell** [comment]
What I mean is you shouldn't be waiting for the HTML to be updated in downstream caches. In your service worker, clean up your caches, stop listening to fetches, and perform any other cleanup. You control that JS, and it's checked for updates very frequently. You don't have that guarantee with the cached HTML.

**Comment by prateekbh** [comment]
My 2 cents:
- For immediate fixes, an attribute or a component might not suffice. 
Imagine a worst case scenerio where you cached your page via the service worker, now it doesn't matter if you add the proposed `amp-uninstall-serviceworker` or the attribute in your next deploy. It will never go to network to fetch the new document.

- The `unregister` attribute, IIUC will unregister the sw before the next one is installed? You can achieve the same thing by deploying a new service worker with `claimClient` and `skipWaiting`.

- @jridgewell do we have a way to permanently unregister a SW though? Imagine my page installed the SW and then the stats show that it isn't working for us and we want to drop using a SW, can we do this at present?

**Comment by jridgewell** [comment]
> do we have a way to permanently unregister a SW though? Imagine my page installed the SW and then the stats show that it isn't working for us and we want to drop using a SW, can we do this at present?

AMP doesn't allow this currently. For this, an unregister attribute is an appropriate solution. But as you explained in your other two points, this should be the last step. First should be deploying an updated SW that fixes itself or stops itself from doing anything. After that, you should update the HTML to unregister the SW entirely.

**Comment by andreyMakahov** [comment]
>   Imagine a worst case scenerio where you cached your page via the service worker, now it doesn't matter if you add the proposed `amp-uninstall-serviceworker` or the attribute in your next deploy. It will never go to network to fetch the new document.

Right, but it can be avoided by not to cache the page.

> AMP doesn't allow this currently. For this, an unregister attribute is an appropriate solution. But as you explained in your other two points, this should be the last step. First should be deploying an updated SW that fixes itself or stops itself from doing anything. After that, you should update the HTML to unregister the SW entirely.

That is what we want. Sorry guys, that did not explain it clearly. I will try to show the problem with the image:
<img width="435" src="https://user-images.githubusercontent.com/5758614/48458668-45987c80-e802-11e8-8527-a3edf3ed569e.png">

We want to avoid such situation. We have dynamic configuration, which does not need redeploy. We will use it immediately after we understand, that something works not as expected. With this dynamic configuration we can  render `unregister attribute` or `new simple unregister component`. And issue will be fixed immediately for all users. After that we will fix the problem and deploy new SW file.

**Comment by prateekbh** [comment]
Thanks for explaining the issue @andreyMakahov, I have a question though:
Why is rendering an attribute via a dynamic configuration is any faster than just reverting the SW file to it's old state or deploying a blank SW file for time being.

I do understand the need of a mechanism for unregistering a SW, but I am just trying to wonder what's a better fix for the above said situation.

**Comment by andreyMakahov** [comment]
We can change dynamic configuration without deploy. So, the SW issue can be fixed much faster. The 5 - 10 mins difference matters for us due to big amount of users.

We can use redeploy in such situations  temporary, but would be great if amp supports unregistering of SW.
