### ISSUE TITLE
AMP HTML click-to-call button

### ISSUE THREAD

**Issue by Noacyl** [ampproject/amphtml#1920]
I was given the task to experiment, and later on implement, the AMP HTML project. Going fine, but I have this issue with the _click-to-call_ button. Normally I would put it in a **anchor tag** with the **href="+18006839847"**. However, AMP doesn't want to validate it. Is there another way to make a mobile _"click-to-call"_ ? 

The code is written as such. **a href="tel:+1-800-683-9847" media="handheld" class="tele""**

**Comment by rudygalfi** [comment]
What error do you see?

cc @Gregable Is "tel:" prefix supported in the validator?

**Comment by Noacyl** [comment]
http://www.freereferral.com/devin_index_amp.html:157:4 Invalid URL protocol 'tel:' for attribute 'href' in tag 'a'.

**Comment by Gregable** [comment]
Yes, we added tel: today, but it hasn't rolled out yet. So, @Noacyl, continue as though tel:<number> works and it will work very soon.

**Comment by Gregable** [comment]
We also are adding sms: if that's useful to you.

**Comment by Noacyl** [comment]
That will be when I get to that page. Thanks @Gregable.
