### ISSUE TITLE
Add account link/unlink analytics events to amp-subscriptions

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#19215]
`amp-subscriptions` does not generate link/unlink analytics events.  The `login` events are ambiguous in this context. 

Tracked internally as b/119115941

**Comment by dvoytenko** [comment]
@jpettitt I don't think we'll ever have an unlink event. But `link` events would probably be relatively straightforward to create?

**Comment by jpettitt** [comment]
In the end I added three new events
```
  LINK_REQUESTED: 'subscriptions-link-requested',
  LINK_COMPLETE: 'subscriptions-link-complete',
  LINK_CANCELED: 'subscriptions-link-canceled',
```
