### ISSUE TITLE
Weird behavior of amp-fx-collection 'fly-in-left/right` behavior

### ISSUE THREAD

**Issue by CrystalFaith** [ampproject/amphtml#19237]
## What's the issue?

`fly-in-left` and `fly-in-right` applied to `<p>` tag cause weird behavior
https://codepen.io/SeaBert/pen/MzeBZg

**Comment by nainar** [comment]
Hi @CrystalFaith what is the weird behaviour, this seems working as intended?

**Comment by aghassemi** [comment]
@nainar Paragraph is initially visible and then flies to the right. (instead of hidden and fly to the left)
