### ISSUE TITLE
The attribute 'slide' may not appear in tag 'amp-carousel'

### ISSUE THREAD

**Issue by harshjv** [ampproject/amphtml#19240]
## What's the issue?

`<amp-carousel>` is missing support for the `slide` attribute which makes it hard to set a default slide. The component is already supporting `slide` attribute via `[slide]`.

See https://github.com/ampproject/amphtml/blob/master/extensions/amp-carousel/validator-amp-carousel.protoascii

## How do we reproduce the issue?

https://jsbin.com/rikonaw/edit?html,output

## What browsers are affected?

All browsers

## Which AMP version is affected?
1811091510240

**Comment by honeybadgerdontcare** [comment]
@cathyxz any reason to not allow `slide` as an attribute for `amp-carousel`?

**Comment by aghassemi** [comment]
@honeybadgerdontcare I would need runtime support before it would work. Dup of https://github.com/ampproject/amphtml/issues/12591. @harshjv Please follow/comment on https://github.com/ampproject/amphtml/issues/12591. Closing as dup.
/cc @nainar
