### ISSUE TITLE
amp-apester-media: Error: null is not an object (evaluating 'a.h.classList')

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#19255]
Likely related to https://github.com/ampproject/amphtml/issues/19254

**Comment by aghassemi** [comment]
/to @IdanLanger @OmriKeret Looks like `amp-apester-media` is throwing in certain cases when it tries to access `classList` on some node.

**Comment by OmriKeret** [comment]
Hi @aghassemi we will take care of this during our upcoming sprint, thanks!
