### ISSUE TITLE
Add a way to pause/resume lifecycle callbacks

### ISSUE THREAD

**Issue by sparhami** [ampproject/amphtml#19259]
In some situations we want to temporarily pause lifecycle callbacks for children. This can be useful if you are scaling up/down an element during a user gesture and you want to prevent re-layout due to size change while the user is in the middle of the gesture. Currently, you can use `setAsOwner` to control the lifecycle callbacks of children, but that is not ideal as you may forget to call some lifecycle methods at the correct time.

**Comment by choumx** [comment]
> but that is not ideal as you may forget to call some lifecycle methods at the correct time.

Do you have an example of which lifecycle methods may be forgotten? Not sure which methods would need to be called in your use case (e.g. while element is being scaled).

**Comment by jridgewell** [comment]
Ferrying `inViewport` usually. I actually don't know what the full requirements are for ownership, and I imagine no one else does either.

**Comment by sparhami** [comment]
> Do you have an example of which lifecycle methods may be forgotten? Not sure which methods would need to be called in your use case (e.g. while element is being scaled).

I don't actually want to call any lifecycle methods during the scaling. I want to avoid calling lifecycle methods (mostly `layoutCallback`) during the scaling. I can stop all lifecycle methods with `setAsOwner`, but then I need to manage the lifecycle callbacks for the child. I don't really want to manage the lifecycle for my child though, because I'll need to manage / remember to tell the child when to layout, when it becomes visible/invisible, when to prerender, etc.

**Comment by choumx** [comment]
Sounds like you want `unsetAsOwner`. I thought you meant lifecycle callbacks during scaling.

**Comment by sparhami** [comment]
Turns out `setAsOwner` is not enough for what I am trying to do. If I call `mutateElement` on my element while scaling a child, it can/will cause my child to run its `onMeasureChanged` callback. That will do some resizing logic that isn't correct / should not be done at that point in time.

For now, I can probably just let the child know it is scaled or maybe have it check if it has an ancestor that is animating before trying to do the work.
