### ISSUE TITLE
Error logs in intersection-observer-polyfill 

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#19252]
New error in Canary release, please see go/ampe/CKrhq5ni6tjc6AE 

Seems to just be from iOS 12. 

Please investigate as P0 and downgrade priority as needed. /cc @zhouyx @torch2424

**Comment by aghassemi** [comment]
Another instance go/ampe/CI7A9JHmssSDkwE but these ones are Chrome and not just iOS.

**Comment by zhouyx** [comment]
Found the cause. IntersectionObserverApi fail to unobserve and remove mutationObserver event listener after it has been destroyed. 

This happens with `<amp-iframe>` when  nested iframe listen to intersection change after unlaid out. Fail to free up resources and caused error logs. But doesn't lead to behavior regression. Set as P1. 

to @torch2424

**Comment by aghassemi** [comment]
Thanks @zhouyx, great investigation.

**Comment by torch2424** [comment]
Thank you @aghassemi and @zhouyx For looking into to this and finding the cause! Will get on this ASAP

**Comment by zhouyx** [comment]
🎉 Thank you @torch2424 for the quick fix! Manually verified the error logs were gone after the fix.
