### ISSUE TITLE
Multiple External Links in Amp-Story

### ISSUE THREAD

**Issue by GrizzlyEnglish** [ampproject/amphtml#19265]
## What's the issue?

When creating the default UI amp-story-consent, can we have the ability to integrate multiple external links since the modal is scrollable based on vendors anyway

## How do we reproduce the issue?

Attempt to add multiple external links to the amp-story-consent, just like having the array of vendors.

## What browsers are affected?

All

## Which AMP version is affected?

1811091510240

**Comment by jasti** [comment]
Hey @GrizzlyEnglish we've been meaning to keep the UX of the consent dialogue on stories as consistent as possible across publishers. Could you explain what type of information you are trying to link to?
