### ISSUE TITLE
amp-ima-video not reproduced and freezes on ios

### ISSUE THREAD

**Issue by Miguelslo27** [ampproject/amphtml#19278]
## What's the issue?

When I open my amp page with video and ad rolls on iOS on any browser, and tap the video to start watching it, the video stays freezed on the first photogram, then I need to pause the video and play again to watch it and the Ad never shows up

## How do we reproduce the issue?

Open any amp project that contains a video implemented with amp-ima-video with a valid vast url with rolls and try to play it.

1. In your iOS device, open a browser
2. Open the url https://amp.foxsports.com.mx/?id=384223&co=MX
3. Play the video

## What browsers are affected?

Chrome, Safari on iOS, even in Chrome on Windows using the Devices Emulator

## Which AMP version is affected?

Last one to the date today

**Comment by aghassemi** [comment]
@Miguelslo27 testing your Url on Chrome (desktop/android), Safari (desktop and iOS emulator), I can successfully play the video and see the ad as well. (Both on your Url and https://ampbyexample.com/components/amp-ima-video/ ).

Are you still running into this issue? Looks like configuration and/or a temp glitch from Ad side.

**Comment by Miguelslo27** [comment]
@aghassemi Hi, and thank you for taking the time to try, I'm still having this issue, I have few questions to you

* When you open in Chrome and turn on the native emulation from the Developer console, are you refreshing the page? If you aren't the add works fine, after you refresh, it stop working

* Did you open the link in a real device?

I'm experimenting the issue in both places, in the prod url, dev url and in my local environment.

I hope to find a solution :)

**Comment by aghassemi** [comment]
@Miguelslo27 yeah refreshing as well, I always get Ads and never see freeze.

Looks like issue is not with the player itself but on the Ads side. I wonder if location difference is causing different type of ads to be returned triggering the bug.

/to @torch2424 to investigate from Ads side.

**Comment by Miguelslo27** [comment]
Great so you say the issue could be on Ads it self, and maybe related to the location, I'm in Uruguay, using a VPN maybe I can trigger the way to see Ads and validate that asumption.

Let me try and I will get back to you.

Thank you a lot in advanced.

**Comment by Miguelslo27** [comment]
@torch2424 Thank you a lot to take this in care.

**Comment by Miguelslo27** [comment]
Sorry, muy bad XD

I've just clicked without intention on the `Close issue` button haha

**Comment by torch2424** [comment]
@Miguelslo27 You are welcome!

I sent out an email, will report back here once we get a response.

Also, another thank you to @aghassemi for trying to reproduce this 😄

**Comment by torch2424** [comment]
@Miguelslo27 Still waiting to hear back from the IMA team, I sent out an email but they may be out for the week. I'll ping them again Monday morning if no response by then 😄

**Comment by Miguelslo27** [comment]
Thanks @torch2424 I will be anxious all the weekend haha :) talk to you on monday then

Thanks for the update

**Comment by torch2424** [comment]
Hello!

So we got a response back from the IMA team. They said they will need more information to debug the issue. I also tried to reproduce this, using the steps you described, and everything worked fine. Thus I agree it may be a regional thing unfortunately.

Could you check / provide any errors that are logged to the Chrome Dev Tools Console? Or any failed requests when trying to get the Ad from the Dev Tools Network Tab? Screenshots / Logs would be helpful for the IMA team.

Thanks! 😄

**Comment by Miguelslo27** [comment]
Hello again, nice to get news from you, even bad ones.

Here I will paste a shared video url I just recorded to show how it behaves when accessing from iOS (emulated from chrome), as you would see in the video, when I load the page from iOS, the pubads endpoint return in a empty VAST response.

I will paste here the headers and the request, I think is something from there.

```
*General*
Request URL: https://pubads.g.doubleclick.net/gampad/ads?slotname=%2F62955556%2Ffoxsports-web%2Fnews%2Froll&sz=640x480&unviewed_position_start=1&output=xml_vast4&env=vp&gdfp_req=1&ad_rule=0&vad_type=linear&vpos=preroll&pod=1&ppos=1&lip=true&min_ad_duration=0&max_ad_duration=120000&vrid=2916&cust_params=domain%3Dlocalhost&url=null&is_amp=0&adk=915807340&correlator=669485256152131&scor=4460746150380693&pucrd=CgwIABAAGAMgACgAOAESAhgHeAM&ged=ve4_td22_tt20_pd22_la0_er0.0.234.414_vi0.0.234.414_vp100_ts19_eb24427&top=http%3A%2F%2Flocalhost%3A3001&osd=2&jar=2018-11-19-19&hl=en&frm=2&video_doc_id=short_onecue&media_url=https%3A%2F%2Fflac-pmd.ficfiles.com%2FPMD%2FFLAC_SPORTS_LATAM%2F521%2F307%2F1374935107957_300000.mp4&sdkv=h.3.257.0&sdki=449&mpt=amp-ima&mpv=0.1&sdr=1&eid=4081989&u_so=l&kfa=0&tfcd=0&adsid=AOhZihv9bMOu9EVA6sZBCgChoAwdhw1w6G5_tVD2fCJGjwJtbZROndDg9A&cookie=ID%3D0467ae05e3db7b0b%3AT%3D1540932604%3AS%3DALNI_MbtXbxDOxkiwWTL5U1tawUCe2oZmg
Request Method: GET
Status Code: 200 
Remote Address: 172.217.162.2:443
Referrer Policy: no-referrer-when-downgrade

*Response Headers*
access-control-allow-credentials: true
access-control-allow-origin: https://imasdk.googleapis.com
alt-svc: quic=":443"; ma=2592000; v="44,43,39,35"
cache-control: no-cache, must-revalidate
content-encoding: br
content-length: 3355
content-type: text/xml; charset=UTF-8
date: Mon, 19 Nov 2018 20:31:06 GMT
expires: Fri, 01 Jan 1990 00:00:00 GMT
google-creative-id: 138248255050
google-lineitem-id: 4838568211
google-mediationgroup-id: -2
google-mediationtag-id: -2
p3p: policyref="https://googleads.g.doubleclick.net/pagead/gcn_p3p_.xml", CP="CURa ADMa DEVa TAIo PSAo PSDo OUR IND UNI PUR INT DEM STA PRE COM NAV OTC NOI DSP COR"
pragma: no-cache
server: cafe
status: 200
timing-allow-origin: *
x-content-type-options: nosniff
x-xss-protection: 1; mode=block

*Request Headers*
Provisional headers are shown
Origin: https://imasdk.googleapis.com
Referer: https://imasdk.googleapis.com/js/core/bridge3.257.0_en.html
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1

*Query String Parameters*
slotname: /62955556/foxsports-web/news/roll
sz: 640x480
unviewed_position_start: 1
output: xml_vast4
env: vp
gdfp_req: 1
ad_rule: 0
vad_type: linear
vpos: preroll
pod: 1
ppos: 1
lip: true
min_ad_duration: 0
max_ad_duration: 120000
vrid: 2916
cust_params: domain=localhost
url: null
is_amp: 0
adk: 915807340
correlator: 669485256152131
scor: 4460746150380693
pucrd: CgwIABAAGAMgACgAOAESAhgHeAM
ged: ve4_td22_tt20_pd22_la0_er0.0.234.414_vi0.0.234.414_vp100_ts19_eb24427
top: http://localhost:3001
osd: 2
jar: 2018-11-19-19
hl: en
frm: 2
video_doc_id: short_onecue
media_url: https://flac-pmd.ficfiles.com/PMD/FLAC_SPORTS_LATAM/521/307/1374935107957_300000.mp4
sdkv: h.3.257.0
sdki: 449
mpt: amp-ima
mpv: 0.1
sdr: 1
eid: 4081989
u_so: l
kfa: 0
tfcd: 0
adsid: AOhZihv9bMOu9EVA6sZBCgChoAwdhw1w6G5_tVD2fCJGjwJtbZROndDg9A
cookie: ID=0467ae05e3db7b0b:T=1540932604:S=ALNI_MbtXbxDOxkiwWTL5U1tawUCe2oZmg

```

Video
https://drive.google.com/file/d/1pNZ5GaZ6Ha-rR09J_XA0HBZvgbijX3_l/view?usp=sharing

**Comment by torch2424** [comment]
Oh this is perfect! Thank you! I'll go ahead and forward this over to them 😄

**Comment by torch2424** [comment]
So I tried some more testing to reproduce, as I thought maybe it was caused by a race condition on network speeds, and got the same results of not being able to reproduce on my end.

Also, I noticed in the video, the bug only happens at around 1:00, after that, it never happens again. Is this correct?

That being said, I'll still wait on the IMA team response and report back here.

**Comment by Miguelslo27** [comment]
Hi @torch2424 

After the first time the bug happen, where the Ad doesnt reproduce and the video freezes, a minute after (if you refresh the page) the video does not freezes again, but the Ad still does not work, in fact the Ad never reproduces on iOS, at least on my end it doesnt

I will keep tuned for AMP and your feedback :)
Thanks again

**Comment by Miguelslo27** [comment]
Very glad to hear that, taht's the light at the end of the tunel we need :D haha.

I will check with the DFP guys to get this fixed, and I will get back to you with the good news.

Thank you so mutch for the help, really appreciated.
Mike

**Comment by torch2424** [comment]
@Miguelslo27 

You are welcome! I'll go ahead and close this issue. If they say it is on our end at some point, feel free to mention me, and we can re-open.

Have a nice day, and good luck! 😄
