### ISSUE TITLE
Amp-Story non-configured share providers

### ISSUE THREAD

**Issue by GrizzlyEnglish** [ampproject/amphtml#19284]
## What's the issue?

On my amp-story, I would like to add non-configured share providers to the sharebar; but I can not add endpoint due to it prepending data-param when the endpoint needs data-share. 

## How do we reproduce the issue?

I don't have a public url, but if you add a bookend with this shareprovider

`{
  "provider": "reddit",
  "share-endpoint": "https://www.reddit.com/submit"
}`

It will generate this share-provider:

`<amp-social-share 
     width="48" 
     height="66" 
     class="i-amphtml-story-share-icon i-amphtml-element i-amphtml- 
           notbuilt amp-notbuilt i-amphtml-layout-fixed i-amphtml- 
           layout-size-defined i-amphtml-error i-amphtml-element-error" 
     type="reddit" 
     data-param-share-endpoint="https://www.reddit.com/submit" 
     style="width: 48px; height: 66px;" 
     error-message="The data-share-endpoint attribute is required. amp- 
           social-share​​​">
</amp-social-share>`

The code specifically prepends data-param as seen [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/1.0/amp-story-share.js#L126).

## What browsers are affected?

All browsers

## Which AMP version is affected?

1811091510240

**Comment by newmuis** [comment]
We could expose a JSON key representing the endpoint, but the problem is going to be the icon.  Thus far, all of the icons are inlined; I'm not sure what the most reliable way to have a configurable icon would be.  Maybe we can accept the icon URL in the configuration JSON as well, but then have a default that is shown if the icon fails to load?

/cc @hongwei1990 @Enriqe

**Comment by GrizzlyEnglish** [comment]
@newmuis  I honestly didn't even consider the icon. The styling would also have to be enforced, right? To keep the sharebar consistent.

**Comment by newmuis** [comment]
Yes, we'll need to keep that consistent as well.  This seems possible, as long as we can come up with good ways to ensure the visual consistency of the icon itself.
