### ISSUE TITLE
amp-orientation-observer is a bit jumpy

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#19310]
see demo here: https://s.codepen.io/aghassemi/debug/eQvORz 

I think we need to smooth it out a bit more.
/to @nainar 
/cc @andrewwatterson

**Comment by andrewwatterson** [comment]
is this something that should have ux eyes? i'm not super sure how to get my local sandbox on mobile, and not sure how to verify that the local sandbox proxy is working rather than just serving up your demo's original AMP version.
