### ISSUE TITLE
amp-carousel not rendered

### ISSUE THREAD

**Issue by fjanevski** [ampproject/amphtml#19314]
## What's the issue?

`amp-carousel` content is not displayed. There is issue regarding building the `amp-casourcel` as show in the browser console.

Error: http://prntscr.com/li7fwp

## What browsers are affected?

It is affecting all browsers.

## Which AMP version is affected?
version number: 1811091519050.

**Comment by darko407** [comment]
We have fixed the issue by removing the value from the autoplay attribute. We had: autoplay="true" and it should have been only autoplay. I am guessing some kind of validation was added in the last update in the amp script that caused this error.

**Comment by aghassemi** [comment]
@darko407 correct, 'autoplay' used to be valueless, now it optionally accepts a number which indicates how many loops it does before stopping.
