### ISSUE TITLE
Missing Documentation for VARIANT and VARIANTS Variable Substibutions

### ISSUE THREAD

**Issue by hadidotj** [ampproject/amphtml#19320]
## What's the issue?

The [AMP HTML URL Variable Substitutions](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md) page is missing definitions for "VARIANT(experiment)" and "VARIANTS" as suggested by the link on the [amp-experiment Reporting section](https://www.ampproject.org/docs/reference/components/amp-experiment#reporting).

## Steps to Reproduce

1. Navigate to the [amp-experiment documentation, Reporting section](https://www.ampproject.org/docs/reference/components/amp-experiment#reporting)
2. Read that "VARIANT(experiment)" and "VARIANTS" are substitution variables, but the link provided-[URL substitution variable](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md)-does not contain details on these variables as suggested.

**Comment by aghassemi** [comment]
to @CrystalFaith

**Comment by CrystalOnScript** [comment]
Over to @zhouyx - thanks! :)
