### ISSUE TITLE
Update worker-dom in amp-script

### ISSUE THREAD

**Issue by fstanis** [ampproject/amphtml#19331]
It seems the currently published version of amp-script (1811091519050) is not up-to-date with the latest worker-dom, specifically, functions like [querySelector](https://github.com/ampproject/worker-dom/blob/6fbcc591488780d15b66d117123bf068b3919be4/src/worker-thread/dom/Element.ts#L414) are missing.

**Comment by choumx** [comment]
Thanks for the report. #19248 upgraded to 0.2.2 which should help.
