### ISSUE TITLE
Intent to Implement: Keen Analytics as a vendor to Amp-Analytics

### ISSUE THREAD

**Issue by adamkasprowicz** [ampproject/amphtml#19359]
Hi there!

We'd like to add [Keen](https://keen.io) to the analytics vendors list, so our customers will be able to use Keen on AMP pages.

**Comment by jeffjose** [comment]
:tada: Thanks for the I2I. Looks like @torch2424 is reviewing your PR over at #19360.

Super excited to see Keen onboard!

**Comment by mrjoro** [comment]
Looks like this was added in #19360.
