### ISSUE TITLE
Handling of AMP Access pages by robots

### ISSUE THREAD

**Issue by jugglingcats** [ampproject/amphtml#1936]
It would be good to understand if there is expected to be any special handling of AMP Access enabled pages by robots. For example, are robots expected to call the authorization and pingback urls and evaluate AMP Access expressions, only indexing visible parts of the content? If so, should robots send their regular user-agent strings to these endpoints?

Any special considerations for server mode support and robots?

**Comment by cramforce** [comment]
Note that the AMP cache robots.txt blocks direct robots access (with a
documented rule how to treat cache URLs like origin URLs). That basically
reduces the problem to how you want to handle robots on your own site.

**Comment by jugglingcats** [comment]
I think that makes sense. Are you saying that search engines will always index the canonical URL, but may then send the user to the amp version of the page using the link information, eg. link rel="amphtml" href="/path/to/amp.html".

Apologies if this is obvious and already discussed at length. I read #498 which provided some further insight.

Thanks

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
