### ISSUE TITLE
amp-img not rendering a new image as src attribute changes when served from Google Cache

### ISSUE THREAD

**Issue by grandloser** [ampproject/amphtml#19364]
## What's the issue?
This problem is only reproducible from AMPs that are served from google cache.
when `amp-img` src attribute bound to `amp-state` changes, the new image is not rendered.

srcset attribute might need to change as well.

## How do we reproduce the issue?

https://ampbyexample-com.cdn.ampproject.org/c/s/ampbyexample.com/components/amp-bind

1.  Change the state to Cat by clicking the `see to cat` button
2. The dog image will not change to the cat image.

## What browsers are affected?

Tested only on google chrome.

**Comment by aghassemi** [comment]
/to @choumx issue is if a given bind Url value is relative, it would be wrong. I think bind needs to try to resolve relative Urls. This probably happens with `amp-list` as well.

**Comment by aghassemi** [comment]
@grandloser as a work-around, please use a fully-qualified Url when binding src, e.g. instead of `/img/foo.jpg` as value of expression, make sure it is `yourdomain.com/img/foo.jpg`.

**Comment by aghassemi** [comment]
Also @Gregable @honeybadgerdontcare, have we never set `<base>` to origin during transformation? that's another solution for this, but I suspect there are reasons I don't see a `<base>`.

**Comment by Gregable** [comment]
Do we want the amp cache to use the publisher's URLs for img src rather than the AMP Cache?

**Comment by Gregable** [comment]
Also note that I don't think you can even rewrite this correctly in bind. The AMP Cache will rewrite all URLs to be absolute (and point to the amp cache as necessary in the case of images) while considering base tags. It then removes the base tag.

So, if the publisher origin page has a base tag, by the time the AMP Cache has run, the value of that tag has been removed and is unavailable to amp-bind javascript.

It would be easy to add it back, but amp-bind would need to be capable of processing URLs with respect to the base tag value.

**Comment by aghassemi** [comment]
Runtime knows the origin and we have utils to correctly resolve relative urls with origin as base, I was hoping to avoid that however since if `<base>` is present, relative Urls will be correctly resolved by the browser against the base, so no need for amp-bind to do anything (at least for `<img>` I am not sure if JS APIs like `fetch` honor presence of `<base>`, probably not...)

**Comment by aghassemi** [comment]
@Gregable pointed out offline, we can tell cache what dimensions to generate an image for, so we could modify the new `src` to generate a pixel perfect size based on the current layout dimensions!

**Comment by Gregable** [comment]
And we could do this for all `<amp-img>`s, not just ones that are amp-bind'ed. I think this would be a really cool optimization.

**Comment by grandloser** [comment]
hey I'm wondering if there is any update on this issue

**Comment by aghassemi** [comment]
@grandloser This is currently not prioritized, you can workaround it by also binding `[srcset]` to the same value as `[src]` per the documentation here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-bind/amp-bind.md#element-specific-attributes

**Comment by aghassemi** [comment]
Closing as dup of https://github.com/ampproject/amphtml/issues/20740
