### ISSUE TITLE
Value of Input (text, button etc.) is not sent by event "tap"

### ISSUE THREAD

**Issue by Publimix** [ampproject/amphtml#19375]
Hello, please see the code bellow. Just tapping the button "myButton" should get its value to var "myVar" and then fill in the value of input "myInput".  But it only puts **null** in the "myInput". Am I doing something wrong? If yes, what is the solution to transfer the value from one element to another via AMPState using "TAP" event?

 `<amp-state id="tempo"><script type="application/json">{"testVar": "temp"}</script></amp-state>
   <input id="testInput" value="" [value]="testVar" />
   <input type="buton" role="button" value="show the text" tabindex="1" on="tap:AMP.setState({testVar:event.value})" />`

Thanks much!

**Comment by aghassemi** [comment]
Hi @Publimix `input` exposes a `change` event where `event.value` is available. `tap` does not expose `event.value`, so you would need `on="change:AMP.setState({testVar:event.value})"` 

p.s. other events exposed by `input` are `input-debounced` and `input-throttled`.

Hope this helps.

**Comment by aghassemi** [comment]
Closing per comment above, please feel free to reopen if it does not solve your issue.

**Comment by Publimix** [comment]
Thank you very much, Ali! It make sense, since `<input type="text" ... />` is for typing.
