### ISSUE TITLE
IntersectionObserver not dispatching event until scroll

### ISSUE THREAD

**Issue by ishaan381** [ampproject/amphtml#19370]
## What's the issue?

Viewability events not being dispatched in desktop safari until the page is slightly scrolled. When an element is being tracked in AMP and is loaded/refreshed so that 100% of the element is in view, on some computers no viewability events were dispatched on the window until there was a scroll. The scroll could be extremely faint, but was needed to trigger the viewability event. This did not happen on all computers, but happended in 2/3 computers this was tested on and happened very consistently. 

## How do we reproduce the issue?

If we subscribe to IntersectionObserver viewability events on an HTML element in Safari and the page loads with the element 100% in the window and visible, often times an IntersectionObserver viewability event will not be dispatched to the window until there is at least a minor scroll.

## What browsers are affected?

Desktop Safari v12.0.1

## Which AMP version is affected?

1811091519050

**Comment by aghassemi** [comment]
to @zhouyx 
cc @torch2424

**Comment by torch2424** [comment]
Thanks @aghassemi !

@ishaan381 Yes so we also noticed this issue, and actually just fixed it recently #19168 . Thus, should be in PROD within about 2 weeks 😄 

Also, do you have an example we can test? Tends to happen when amp-bind is on the page and an element visibility is changed. Would be a good way for us to debug this issue if that is not the case.

**Comment by ishaan381** [comment]
@torch2424 Thank you for the update!

Here's a page I was seeing an issue on: https://urldefense.proofpoint.com/v2/url?u=https-3A__www.cbssports.com_mlb_news_mlb-2Dmonday-2Dscores-2Dhighlights-2Dlive-2Dteam-2Dupdates-2Dnews-2Dreds-2Dindians-2Dsee-2Dwinning-2Dstreaks-2Dend_amp_-3FadTargeting-5Fcampaign-3Damphtml-5Ftest&d=DwMFaQ&c=RoP1YumCXCgaWHvlZYR8PZh8Bv7qIrMUB65eapI_JnE&r=-Pxv2eJzfBcKQ5u60M0LvYjAH-1Rn4Qn-hlkybrTiis&m=sYujuIXFANugScVWulWaF8SGdRoU-ygqQ07rsKj9K5A&s=KIXY3I7JhQXYoynka5XUKhw1CDNeo7NikDZl13c9-Sg&e=

A screenshot of the element I was having this issue with:
![image-2018-08-21-11-14-49-091](https://user-images.githubusercontent.com/18489982/48728575-4a46a180-ec03-11e8-848d-ff8e0cfa9b69.png)

**Comment by zhouyx** [comment]
@ishaan381 Thanks for the demo. The issue doesn't look like it is related to the fix, because `<amp-bind>` doesn't seem to be involved here. 
From the page source, the element you're tracking is an ad? I couldn't find the visibility tracking config related to this specific element and I didn't see any remote config? Could you point me to the config you have? 

To help us reproduce the issue, could you provide more details Including what is the request to look at? What browser/device to use and etc. Thank you!
