### ISSUE TITLE
Run v0.js in strict mode

### ISSUE THREAD

**Issue by zhangsu** [ampproject/amphtml#19380]
On this line:

https://github.com/ampproject/amphtml/blob/7731c43f2c7d01da647e31ccf61b85e773d8e4b7/src/error.js#L212

The first argument to `call` sets the `this` for the `onError` function, and in this case it is `undefined`. However, the function actually assumes that this is a `!Window` (for various checks such as whether to report the error to the viewer). Currently it always fail on this line:

https://github.com/ampproject/amphtml/blob/7731c43f2c7d01da647e31ccf61b85e773d8e4b7/src/error.js#L361

Because `win` is `undefined`. This is a bug that affects error reporting in regular AMP documents on the web, because the `maybeReportErrorToViewer` code path is triggered for regular AMP documents too. However, it only affects approximately half of the errors that are reported explicitly using `reportError` (and transitively, errors that are explicitly logged using `dev().error()`, for example). This doesn't affect errors that are thrown to the top level and caught by the `window.onerror` handler, since the `this` reference in that case would *not* be `undefined`:

https://github.com/ampproject/amphtml/blob/7731c43f2c7d01da647e31ccf61b85e773d8e4b7/src/error.js#L278

I believe this bug has been in the AMP runtime since the following commit:

https://github.com/ampproject/amphtml/commit/2cdc9d3f562286e8f55535114eb30afaaf80cebe

Where `maybeReportErrorToViewer` was first introduced.

It's hard to detect this bug because the error in the error reporting logic actually gets swallowed by the very same error reporting logic: what ended up happening is that `Services.ampdocServiceFor(win)` throws a `Script error.`, and when that happens the error gets caught by the `onError` handler again. However, only `0.1%` of `Script error.` are reported:

https://github.com/ampproject/amphtml/blob/7731c43f2c7d01da647e31ccf61b85e773d8e4b7/src/error.js#L468

This is probably why this bug never triggered any alert and was unnoticed for months... The observed behavior is just that no error happened and no error reported, given the low 0.1% probability of reporting such error, which would only happen if some other error happened in the first place.

To fix the error, we need the `win` reference inside `maybeReportErrorToViewer` to be `!Window` and not `!Window|undefined`. Do you think it is safe to just use `Services.ampdocServiceFor(self)` or should we plumb the `win` reference all the way from `reportErrorForWin` to `reportError` to `onError` and then to `maybeReportErrorToViewer`? There are many callers of `reportError` outside of the `error.js` file if we have to update its signature.

**Comment by jridgewell** [comment]
AMP's code runs in sloppy mode, and in sloppy mode `.call(undefined)` is equivalent to `.call(window)`. We can make this more explicit by changing it to `.call(self)`.

I don't think there's actually an error here, which makes me curious why you're flagged it? Is there an error somewhere that you're not receiving?

**Comment by zhangsu** [comment]
Uh, I didn't know AMP's code runs in sloppy mode. Thanks for clarifying.

I ran into this while using a `localhost` AMP server trying to simulate a non-user error (i.e., a bug in the AMP runtime) by putting a `dev().error()` somewhere in the runtime code. Then, a "Script error." gets thrown when executing `Services.ampdocServiceFor(win)` because `win` is `undefined`. This is because locally-built AMP actually runs in strict mode - I see `"use strict;"` in the locally-built `amp.js`, inside the function wrapper that wraps the `error.js` module.

I don't see `"use strict;"` in https://cdn.ampproject.org/v0.js, so I guess yeah you are right that there's actually an error here. However, it would still be nice to be explicit like you mentioned so that we don't run into this problem when strict mode is enabled for AMP in the future (seems like a nice thing to do). It'd also help local debugging since we don't have to locally modify the `undefined` to `self`.

WDYT?

**Comment by jridgewell** [comment]
Yah, let's do it.
