### ISSUE TITLE
I2I: amp-mraid

### ISSUE THREAD

**Issue by jeffkaufman** [ampproject/amphtml#19388]
## Background

With amp-inabox we have AMP ads on non-AMP pages, and mobile APP webviews are a special case of these.  These webviews commonly provide an API to things such as open external links or determine visibility status.  The most commonly available API is [MRAID](https://www.iab.com/wp-content/uploads/2017/07/MRAID_3.0_FINAL.pdf).

The amp-mraid component is intended to bridge AMP and MRAID for Inabox, implementing the `HostServices` API.

## Markup

It will be the ad network's job to notice that an ad is serving into a mobile app context, and inject amp-mraid into the ad.  This could look like:

```
 <amp-mraid
   fallback-on="load incomplete"
   layout=nodisplay>
```

The `fallback-on` parameter is to handle cases where the server is wrong about whether MRAID is available, or where the available MRAID implementation doesn't work.  Ad networks may want a range of behavior in this case, mostly around how to handle visibility:

* In some cases the ad network will never want to fall back to IntersectionObserver-based measurement.  For example, if the ad network is sure that it served to a mobile app, then any measurements from IntersectionObserver could be misleading, because IntersectionObserver can't determine whether the webview is currently on screen.

* In other cases the ad network will want to fall back to IntersectionObserver if `mraid.js` is not found.  Since the server can't always tell if a request is from a mobile app, and nearly all mobile apps provide an `mraid.js` of some form, then the network might want a policy of "use it if it's available, fall back to IntersectionObserver if it's not, and nothing if it's available but non-functional".

For Google AdManager, we want both of these cases.  Other users of amp-mraid may want an even more permissive approach where you fall back to IntersectionObserver if anything goes wrong at all.

I'm planning to handle this by having a list of error codes (currently just `load` for if `mraid.js` can't be loaded, and `incomplete` for if the `mraid` object is unavailable after `mraid.js` loads).  If amp-mraid encounters one of these errors then it will step aside and allow amp-analytics to fall back to IntersectionObserver only if that error is included in the `fallback-on` list.  For example, to fall back on `load` but not `incomplete` you would include `fallback-on=load`.  To never fallback, you'd leave the parameter off entirely.

**Comment by torch2424** [comment]
cc @zhouyx @lannka (When you are back from vacation 😄 )

**Comment by lannka** [comment]
@jeffkaufman I think this work is all done?

**Comment by jeffkaufman** [comment]
Yes, there's still going to be more work to do as we learn other things that ads on mApp do which need MRAID support, but I think we can close this I2I
