### ISSUE TITLE
Validator: Allow additional print-specific style similar to keyframes-specific style

### ISSUE THREAD

**Issue by westonruter** [ampproject/amphtml#19381]
In the continual effort to keep CSS less than 50KB, one segment of the custom CSS has emerged as a candidate for removal: the print styles. When running CSS code coverage to try to identify which rules could be removed, I noticed (expectedly) none of the print styles would ever apply to the page as I tried various breakpoints.

In particular, [the print CSS](https://github.com/WordPress/twentynineteen/blob/master/print.css) from the Twenty Nineteen theme for WordPress was checked. After the AMP plugin's tree shaking, there is still ~3KB of print-specific CSS left in the `style[amp-custom]`. However, this CSS does not make sense to be included in the `head` of the page as it is not in the critical path for rendering.

**Proposal:** In the same way as there is a `style[amp-keyframes]` element (#9625) that appears at the end of the `body`, there could similarly be a `style[amp-print][media=print]` element that appears toward the end of the `body`. This could have a 50KB limit similar to `style[amp-custom]`, though in reality it would normally be less.

By having a print-specific `style` element, more breathing room would be given for critical rendering styles, and in all cases we can reduce the amount of CSS served in the `head`.

_This idea comes from a discussion with @Gregable at CDS last week._

**Comment by Gregable** [comment]
Discussed with @cramforce a bit offline.

One suggestion he had was to make this into `<link rel=stylesheet media=print href=...>` instead. This has the benefit of not even including the print css until it's needed.

Unfortunately this doesn't work out of the box, because the browser will go ahead and download this even if in screen media.

So, the next suggestion would be to inject the stylesheet via javascript on a print event using something like https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeprint

**Comment by westonruter** [comment]
So something like: 

```html
<amp-style media="print" href="https://example.com/print.css"></amp-style>
```

or

```html
<amp-print-style href="https://example.com/print.css"></amp-style>
```

or

```
<link rel="amp-stylesheet" media="print" href="https://example.com/print.css">
```

Would the URL need to be absolute? It would need to be rewritten to use the AMP cache when served there, yes?

Would this require a new component or would it be part of the AMP runtime?

**Comment by Gregable** [comment]
Those all seem like reasonable suggestions for the format.

The URL would not need to be absolute, the AMP Cache can rewrite it.

@aghassemi and @jridgewell for thoughts on how this would actually be implemented.

**Comment by igrigorik** [comment]
> One suggestion he had was to make this into `<link rel=stylesheet media=print href=...>` instead. This has the benefit of not even including the print css until it's needed.
> 
> Unfortunately this doesn't work out of the box, because the browser will go ahead and download this even if in screen media.

Where does this fail? The browser should not download the resource if the media query does not apply.

**Comment by Gregable** [comment]
@igrigorik 	Malte and I tried this in Chrome and it downloaded the resource.

**Comment by westonruter** [comment]
Apparently browsers download all stylesheets regardless of the media query because the media may change later and make them relevant. This seems to be an old issue, e.g.:

* https://zoompf.com/blog/2009/12/browser-performance-problem-with-css-print-media-type/
* https://stackoverflow.com/q/6311235

**Comment by cramforce** [comment]
@igrigorik Would be nice if Chrome could stop doing it, but definitely does right now. See trivial repro https://output.jsbin.com/milomezebi/quiet

**Comment by jridgewell** [comment]
We can do anything here.

Will browsers download styles inside a `<noscript>`?

**Comment by igrigorik** [comment]
@cramforce @westonruter @Gregable pre-coffee brain fart, apologies.. Yes, you're right, I confused "non matching stylesheets are not part of the critical render path" and "not downloaded" — they are downloaded, they just don't (or, shouldn't at least ;-)) block rendering.

**Comment by cramforce** [comment]
AMP actually takes advantage of this to make Font-provider stylesheets not
block rendering :)

**Comment by honeybadgerdontcare** [comment]
@westonruter is this still necessary with the increase from 50kb to 75kb for css?

**Comment by westonruter** [comment]
The pressure is much-reduced. With tree-shaking, I'd expect it to free up ~2KB from the total CSS limit.

Nevertheless, independent of the CSS limit, being able to move all print styles the end of the document alongside keyframes would offer a slight performance improvement since such print styles are not critical.

**Comment by Gregable** [comment]
I'm going to close this as practically, I don't think we'll ever prioritize it.
