### ISSUE TITLE
amp-analytics: iframe transport not loading

### ISSUE THREAD

**Issue by camdunne** [ampproject/amphtml#19411]
## What's the issue?

For MOAT amp-analytics config, Sometimes the iframe transport does not load even though the creative is fully loaded and is 100% in view.

## How do we reproduce the issue?

Steps to recreate issue:

1.  if you scroll past ad with out stopping, the iframe (https://z.moatads.com/ampanalytics093284/iframe.html) most likely will not load. seen on mobile and desktop for chrome and safari
2. If you scroll slowly down the page and then stop on the ad, the iframe may not load. seen on iPhone/safari (iPhone 6 iOS 11) using the phone's service
Test page:
https://www.cbssports.com/mlb/news/mlb-monday-scores-highlights-live-team-updates-news-reds-indians-see-winning-streaks-end/amp/?adTargeting_campaign=amphtml_test

Creative:
![cbs](https://user-images.githubusercontent.com/22266951/48799897-446dc080-ecd6-11e8-84e9-7821ff053911.png)

## What browsers are affected?

Seen on iPhone IOS, Safari web

## Which AMP version is affected?

current

**Comment by zhouyx** [comment]
Closed by #19738
