### ISSUE TITLE
Create amp-vevo player

### ISSUE THREAD

**Issue by alvin-milton** [ampproject/amphtml#1941]
The amp-iframe tag is not rendering Vevo content.

Here is some output of the tag with vevo content:
https://gist.github.com/alvin-milton/d3959eaab4753a993041

**Comment by cramforce** [comment]
We should create `amp-vevo`

**Comment by mkhatib** [comment]
I couldn't find any documentations around embedding vevo videos. Do you have a sample page where you have embedded a vevo video using normal iframes?

**Comment by adelinamart** [comment]
@alvin-milton is this still an issue? Thanks

**Comment by alvin-milton** [comment]
It was when I reported it @adelinamart, but I'm afraid I haven't tested this in some time.

**Comment by adelinamart** [comment]
Thanks @alvin-milton . It will be great to reproduce this when you have the chance.
