### ISSUE TITLE
AMP-STORY : Page ID change freezes the story totally!

### ISSUE THREAD

**Issue by ChintanPalan** [ampproject/amphtml#19431]
## What's the issue?

AMP Story saves the last visited page id while visiting the story, if it cannot find the page on reload due to some reasons, then it should start from first page instead of just freezing the whole functionality.

## How do we reproduce the issue?
It is a fairly easy issue to reproduce, I wonder how has this been out for such long, To be precise we are facing this issue from the 0.1 version itself.
1. Make any story with more than 1 page and assign ids to amp-story-page
2. Visit story in your browser and go to any page other than first one
3. Go to code and change the id of the page you are on
4. Reload the story

## What browsers are affected?

All browsers that support localStorage.

## Which AMP version is affected?

0.1 and 1.0 both

![error](https://user-images.githubusercontent.com/19709183/48883783-6aff3900-ee47-11e8-9e86-cfa42b5e8c1c.png)

**Comment by newmuis** [comment]
Yep, this makes sense.  I'll send a quick fix for 1.0.  0.1 is deprecated and does not get updated with non-critical fixes.

**Comment by ChintanPalan** [comment]
@newmuis Any update on the fix for this?

**Comment by newmuis** [comment]
Sorry, this was complicated by another issue that I believe has since been refactored.  I should be able to take another look at this in the coming week.

**Comment by ChintanPalan** [comment]
Sure no problem

**Comment by newmuis** [comment]
Actually, @bramanudom already fixed this with #20238.  Thanks @bramanudom!

**Comment by gmajoulet** [comment]
It's been fixed by @bramanudom as part of https://github.com/ampproject/amphtml/pull/20238, which should be available in production :)
Feel free to reopen this ticket if that bug happens again.
