### ISSUE TITLE
amp-action-macro: Conditional invocation based on amp-state

### ISSUE THREAD

**Issue by danieltxok** [ampproject/amphtml#19435]
To perform actions after listening to events only under certain conditions is a very common use case. To help improve the amp-bind component I would like to suggest the following:

The ability to listen to events and perform actions with the _on_ attribute but **only if a condition is met** (e.g. only if a variable in the state has a certain value). It would be something like this:
`<select on="myState.condition == 0 ? change:AMP.setState({myState: {variable: event.value, condition: myState.condition+1}}) : [...]">`

**Comment by torch2424** [comment]
Assigning to @aghassemi . Feel free to re-assign 😄

**Comment by aghassemi** [comment]
Thanks @dbarcosb for the feature request.
reassigning to @choumx for evaluation.

**Comment by choumx** [comment]
This is an interesting enhancement for `amp-action-macro`:

```html
<amp-action-macro action="AMP.setState({foo: 'bar'})" if="baz >= 0">
```

**Comment by gmanguk** [comment]
This would be very useful for at least one of our use cases: showing a Multi-factor authentication (MFA) popup on only certain types of error response while showing error text for others. Currently, we only have one option to conditionally set a page state to simply show the MFA page on top of the current checkout page which is not ideal as the user cannot press <back> to get out of it and has to find the <X> to close it out.

Any ETA of when this would be rolled out?

**Comment by alabiaga** [comment]
@gmanguk We just rolled out the first iteration of amp-action-macro without this but I'll look into this tomorrow and will have a more definite timeline for you then. Thanks

**Comment by alabiaga** [comment]
apologies for not updating this. I'm working on this PR and will have it for review soon. We will have to wait till the beginning of April for review as @choumx will be reviewing. Thanks

**Comment by caiotomazelli** [comment]
Adding another use case that I believe could only be solved by conditional actions:

> Given two dependent amp-date-pickers, say D1 and D2, I would like to set "D2's" date to "D1's date + offset" if and only if I change D1's date to a value that is bigger than D2's date. If D1's date is still smaller than D2's date, I want to keep D2's date unchanged.

This would translate to something like this implementation, using choumx@ suggested API for conditional amp-action-macro:

`
    <amp-action-macro action="D2.setDate({d1Date.offset(1))" condition="d1Date > d2Date">

    <amp-date-picker  id="D1 on="select:conditionalSetD2(),AMP.setState({d1Date: event.value})">
    </amp-date-picker>

    <amp-date-picker id="D2" on="select:AMP.setState({d2Date: event.value})" >
    </amp-date-picker>
`

Any ETA for the amp-action-macro implementation and roll out with this conditional feature would be of great value!

**Comment by sebastianbenz** [comment]
@alabiaga are there any updates on this?

**Comment by alabiaga** [comment]
@sebastianbenz feel free to take over https://github.com/ampproject/amphtml/pull/21625. That was the PR that I worked on that allowed conditional invocations to some extent.  I think it was limited in its conditionals but was a start. Thanks

As discussed offline, I am no longer proactive on working on AMP related things. Many thanks

**Comment by jakewantulok** [comment]
A situation with a project came up that made me ask if this were possible. Will this be included in the near future? It would be amazing to have more of this kind of feature. I hate I sometimes have to write a conditional inside an amp-state. :/

**Comment by jakewantulok** [comment]
Here is an example of what I was hoping to achieve:
```html
<amp-action-macro
  id="example-macro"
  execute="bool ? AMP.scrollTo(id='product-options', position='center', duration=500) : AMP.scrollTo(id='product-options', position='center', duration=500), standard-cart-form.submit"
  arguments="bool"
></amp-action-macro>
```
I suppose with @alabiaga's implementation:
```html
<amp-action-macro
  id="example-macro"
  execute="standard-cart-form.submit"
  arguments="bool"
  condition="bool == false"
></amp-action-macro>

...
on="tap:AMP.scrollTo(id='product-options', position='center', duration=500), example-macro.execute(bool=specialCase)"
```

**Comment by jakewantulok** [comment]
Hold up! This works??  😲
