### ISSUE TITLE
Feature Request - AMP pages for stock quotes 

### ISSUE THREAD

**Issue by Sandesh-Sawal** [ampproject/amphtml#19440]
Hi Team, 
My name is Sandesh Sawal and I'm working as a Product analyst at an algorithms based equity research portal. I want to set up AMP for our stock quotes - pages. I know it is possible as currently AMP is supported for News/Blogs publishers & E-commerce portals. Please let me know how to go ahead with it. 
- website: https://www.marketsmojo.com
- stock page: https://www.marketsmojo.com/Stocks?StockId=513374

Looking forward for a positive response. 

Thanks & Regards,
Sandesh Sawal

**Comment by jpettitt** [comment]
You can use `amp-list` to import "live" data into an AMP page.  See the https://www.ampproject.org website for more general amp development documentation.

**Comment by Sandesh-Sawal** [comment]
Thank you sir. Will get back, if in-case of any further doubts/queries.
