### ISSUE TITLE
How to insert amp-youtube , iframe tags in AMP stories and also about implemention of href in stories.

### ISSUE THREAD

**Issue by syedimran22** [ampproject/amphtml#19444]
Desc: How to insert amp-youtube, iframe tags in AMP stories as the tags are not allowed and The other question is how to implement links in the story added to them so users can be redirected from an image to a landing page.

**Comment by torch2424** [comment]
Assigning to @newmuis since this pertains to AMP Stories. Feel free to re-assign 😄

**Comment by newmuis** [comment]
Thanks @torch2424, and good questions @syedimran22.

- Using `<a>` tags within `<amp-story-cta-layer>` is currently supported
- Using `<a>` tags within `<amp-story-grid-layer>` will be launching within the next few weeks
- `<amp-youtube>` support is tracked in #15847
- There are currently no plans to support arbitrary iframes

**Comment by newmuis** [comment]
@syedimran22 please feel free to reopen this issue if you do not feel it has been addressed adequately.

**Comment by syedimran22** [comment]
Thank you for your response @newmuis I will be waiting for <amp-youtube> element and <a> tags support within <amp-story-grid-layer> .

**Comment by syedimran22** [comment]
And also could you let me update once the support feature gets added in amp-stories so that I can implement the elements in our extensions.

**Comment by sandeepie** [comment]
Can we put <amp-youtube> within <amp-story-grid-layer>

**Comment by newmuis** [comment]
Hi @sandeepie, `<amp-youtube>` is not currently supported within `<amp-story>`.  You can track this support by following #15847.

**Comment by sandeepie** [comment]
@newmuis I just want to know how i use youtube in 'amp-story' tag
