### ISSUE TITLE
lazyload for <amp-iframe>

### ISSUE THREAD

**Issue by Jxck** [ampproject/amphtml#19443]
Hi team

## Detail

currently I'm trying lazyload for img/iframe with chrome flagged feature below on my blog.

https://docs.google.com/document/d/1ITh7UqhmfirprVtjEtpfhga5Qyfoh78UkRmW8r3CntM/edit#heading=h.c7mc4hh4xdhq

my blog was...

- build with my own blog engine
- opt in to AMP
- if `<iframe>` appears replace them in `<amp-iframe>`

and now

- adding lazyload to all `<iframe>`
- if `<iframe lazyload>` appears replace them in `<amp-iframe lazyload>`

but now I got error from Google Search Console about

> The attribute 'lazyload' may not appear in tag 'amp-iframe'.

## Question

I know the `amp-iframe` is **lazyload** by default.
so It's not *necessary* to adding layload attribute to amp-iframe.
but is it MUST NOT ? is it should be error ?

I think this will solve by adding feature-policy header to content if one could change server header, 
but it's convenient for replace-style amp engine based on html to allow lazyload for iframe also amp-iframe.
amp validater can ignore lazyload attribute if appears, and if not appears make it lazyload by default.
if `lazyload=off` , that is THE ERROR in validater.

## Wrapup

allow lazyload attribute for amp-iframe in amp spec excepting lazyload=off.

**Comment by jpettitt** [comment]
As you noted AMP manages its own lazy load, there is no need to add a `lazyload` attribute.  Adding `lazyload` to `amp-iframe` is meaningless (there is no such attribute to `amp-iframe`) and the validator is correctly rejecting this.
