### ISSUE TITLE
some type casting fails on `dev().assert` calls

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#19457]
To be able to do pre-process removal of `assert` calls, we need to add a type cast on the call site after removing the method call. There are some instances where we do this where closure thinks its impossible to cast the value since it seems to think that it hits a code path where the value is always `null`.

to try and prove the issue we convert the `dev()` calls into `user()` calls so that they don't get DCE'd and we can better trace the issue if the error crops up in production.

**Comment by rsimha** [comment]
@erwinmombay we added a new `@closurePrimitive {asserts.matchesReturn}` annotation in https://github.com/ampproject/amphtml/commit/5ebcee3cd569d11295cc8f0dda1ee0a17c7b222c#commitcomment-33643222 in #22446.

Can this be closed or is there more to do?
