### ISSUE TITLE
$sf is not defined within the Google safeFrame

### ISSUE THREAD

**Issue by ndahmani** [ampproject/amphtml#19466]
Sorry for reopening https://github.com/ampproject/amphtml/issues/19139
More an more publishers are complaining.

Problem:
$sf is not defined within the Google safeFrame.
![image](https://user-images.githubusercontent.com/29407178/49075687-8dbe9280-f237-11e8-93ad-9146ff466446.png)
URL: https://calcio.fanpage.it/amichevole-italia-ucraina-le-ultime-sulle-formazioni-le-quote-e-dove-vederla-in-tv/amp/?google_preview=VR1kgoPGP1MYh5_33QUwh7us5QWIAYCAgKDb8MT0SQ&iu=1010633&gdfp_req=1&lineItemId=4816432979&creativeId=138246844693

Same issue here:  https://www.freundin.de/beauty-foehn-im-test?amp&google_preview=vQ8hGQ9h31MY1Ifb3wUw1KOQ5wWIAYCAgKDbkYXoCw&iu=40748507&gdfp_req=1&lineItemId=4870567891&creativeId=138251967304

We tried data-force-safeframe=true, no success.
Thanks for your help!

**Comment by aghassemi** [comment]
to @keithwrightbos
cc @lannka

**Comment by jeffkaufman** [comment]
Reading https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad-network-doubleclick-impl/safeframe.md this looks like it should be working.  I made a test page, https://www.jefftk.com/amp-demo/amp-doubleclick-fsf that is configured to serve a test creative that verifies safeframe is configured properly, but it will take some time before my test creative is serving live.

**Comment by jeffkaufman** [comment]
The test page with safeframe test creative, https://www.jefftk.com/amp-demo/amp-doubleclick-fsf , is working now:

<img width="410" alt="screen shot 2018-11-27 at 2 50 30 pm" src="https://user-images.githubusercontent.com/262566/49107480-d97f3500-f253-11e8-8f7b-d3f9d0fd228b.png">

<img width="445" alt="screen shot 2018-11-27 at 2 50 39 pm" src="https://user-images.githubusercontent.com/262566/49107493-e00dac80-f253-11e8-889a-8f4c838e32f1.png">

The test creative is:

```
<div id="container">
    <style type="text/css">
        #container {
          background-color: #EEF;
          width: 500px;
          height: 500px;
        }
    </style>
    <span>
        <strong>$sf.ext.register and $sf.ext.geom</strong>
        <br>
        Geometry info should be updated on scroll/browser resize.
    </span>
    <pre id="geometry"></pre>
    <script>
      function updateGeometry() {
        var el = document.getElementById('geometry');
        var geom = $sf.ext.geom();
        el.innerHTML = JSON.stringify(geom, null, '  ');
      }

      $sf.ext.register(500, 500, function(status, data) {
        if (status === 'geom-update') {
          updateGeometry();
        }
      });

      updateGeometry();
    </script>
</div>
```

It looks like this is all working correctly?

**Comment by jeffkaufman** [comment]
Testing the two referenced urls I'm not seeing this either.  No reference error, and the ads look good.

**Comment by jeffkaufman** [comment]
@ndahmani

**Comment by jeffkaufman** [comment]
@ndahmani Thanks for the follow-up!

When I visit https://kurier---at---doh-342-safeframe-4-k32e7yy-rltdq4mpxfdic.eu.platform.sh/amp/kultur/wanda-live-in-der-arena-himmlisches-ueberraschungskonzert/400351735?google_preview=yWBpxYCfNcEYgNDI4AUwgOz95wWIAYCAgKDb--D_pQE&iu=39025507&gdfp_req=1&lineItemId=4733082881&creativeId=138252023189 on mobile I don't see any `$sf` warning on the console.  Does this consistently fire for you?

**Comment by ndahmani** [comment]
I apologize, I forgot to mention, the warning screened above got after manually access $sf into the console.
For testing purpose, I usually access $sf this way. I only have to be under the safeframe scope.

However, our ad script uses the same property to test the safeframe context.
If I'm correct, this command should not fire any warning.

Thanks a lot for checking!

**Comment by jeffkaufman** [comment]
Looking on your test page, I don't see `ext.js` getting loaded, which does look wrong.

**Comment by ndahmani** [comment]
Thanks for raising this up @jeffkaufman 
I don't understand why sometimes ext.js is loaded and sometimes not
I don't think the publisher is responsible for loading this library since he only set a DoubleClick amp-ad element.

However, even with ext.js loaded $sf still not defined under the safeframe scope.
<img width="864" alt="capture d ecran 2018-12-17 a 18 33 36" src="https://user-images.githubusercontent.com/29407178/50104546-98fb5180-022a-11e9-9dea-cd7e86e19316.png">

**Comment by olivier-gnagora** [comment]
Hi all,
any update on this issue?
Is there none workaround we can use?
thanks.

**Comment by calebcordry** [comment]
Closing this as it seems the original reporter has fixed? Feel free to reopen.

**Comment by jeffkaufman** [comment]
Sorry for dropping this!

The workaround described above of manually modifying the creative to include ext.js should work as a temporary fix, but over time could have problems as the version of ext.js gets out of sync with the version of the host.

I think the root problem is that Google AdManager is not injecting `ext.js` into the creative when serving to safeframes on AMP pages the way it does when it serves to safeframes on non-AMP pages.  It's not an AMP problem, but an AdManager issue.  I'll look at fixing it.

**Comment by jeffkaufman** [comment]
Sorry for the long wait, but this should be fixed now.  AdManager should inject ext.js now.
