### ISSUE TITLE
i2i: amp-smartlinks

### ISSUE THREAD

**Issue by PhilWinchester** [ampproject/amphtml#19470]
Hi AMP community,

I work for a commerce content monetization platform called Narrativ. We have a few out of the box javascript integrations we offer our clients to help monetize their publications. To help our publishers monetize fully through AMP we would like to add an extension that utilizes our smartlink technology.

A few weeks ago the `amp-skimlinks` extension was merged that offers a similar service to us. They created a service called `link-rewriter` which handles event listeners, link swapping, and click tracking on anchor tags. We aim to utilize that service in our extension since that is a shared feature in both of our platforms. 

Our company believes in the core AMP principles and would like to work alongside your team develop an extension that offers a full suite of publisher tools and an optimized reader experience. 

## amp-smartlinks
For our initial implementation, `amp-smartlinks` will require API calls to fetch the publishers config in our system, a page load event (using `extension-analytics`), and finally a POST call with all anchor tags on the page to be filtered and monetized according to our publisher partnership in our system. All monetized links will be returned and placed in the DOM using `link-rewriter`.

Our documentation on our vanilla JS tag can be found [here](http://docs.narrativ.com/en/stable/tagpublisher.html) and our documentation around Linkmate can be found [here](http://docs.narrativ.com/en/stable/linkmate.html).

```HTML
<amp-smartlinks
    layout="nodisplay"
    nrtv-account-name="examplepublisher"
    linkmate='true'
    exclusive-links='false'
></amp-smartlinks>
```

**Comment by zhouyx** [comment]
@PhilWinchester Sounds good. Please let us know if there's anything we can help with. Looking forward to your PR.

**Comment by choumx** [comment]
@zhouyx Has this gone through design review? Did we consider a generic extension now that N > 1?

**Comment by zhouyx** [comment]
Not specifically for the amp-smartlinks. The amp-smartlink mostly used the existing amp-skimlink service, but they need specific logic for reading their remote config response.

I believe that there's another one (the third one) that's we decide to go with the generic extension now. Based on what I heard, the new extension configuration is purely on client side, so it can be very generic. @lannka and @torch2424 is following on that thread.

**Comment by lannka** [comment]
@choumx we have a design review for the generic extension today at 5PM PST time.
