### ISSUE TITLE
Intent-to-implement: Action macros with amp-action-macro

### ISSUE THREAD

**Issue by alabiaga** [ampproject/amphtml#19494]
Create reusable action macros.

    <amp-action-macro id="closeNavigations" 
        action="AMP.setState({nav1: {open: false}, nav2: {open: false}})">
    </amp-action-macro>

    <button on="tap:closeNavigations">&times;</button> 
    <div class="backdrop" on="tap:closeNavigations"></div>

vs

    <amp-bind-macro id="close" expression="{open: false}"></amp-bind-macro>

    <button on="tap:AMP.setState({nav1: close(), nav2: close()})">&times;</button> 
    <div class="backdrop" on="tap:AMP.setState({nav1: close(), nav2: close()})"> 
    </div>

Please see #19189 for more context and examples.

Checklist:

- [x] submit skeleton implementation
- [x] implementation and examples
- [ ] conditional invocation and multiple action support
- [x] validation rule changes and tests

**Comment by choumx** [comment]
Closing since the extension MVP is shipped.
