### ISSUE TITLE
amp-story desktop amp-social-share svgs too large for parent container.

### ISSUE THREAD

**Issue by GrizzlyEnglish** [ampproject/amphtml#19498]
## What's the issue?

The share hover bar svgs are larger than parent. And lacks any spacing between the svgs.

## How do we reproduce the issue?

Open any amp story in desktop view. Here is one of CNN visual stories.

https://www.cnn.com/ampstories/us/10-of-the-nfls-strangest-stadium-foods

## What browsers are affected?

Chrome 70
Firefox
Safari

## Which AMP version is affected?

I think this is relatively new, I didn't notice in the last few weeks at least.

Version 1811202257200

**Comment by newmuis** [comment]
/to @gmajoulet was this caused by switching to the color versions of the icons?

**Comment by gmajoulet** [comment]
It is... Just sent a fix :)
