### ISSUE TITLE
Presubmit check for PWA-unsafe references in extensions

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#19514]
Consider checking for `window.document` and other PWA-unsafe code in `extensions/**/*`.
- [ ] `window.document`

/cc @jridgewell @lannka

**Comment by prateekbh** [comment]
@choumx @jridgewell @lannka if you know any such APIs from the top of your head can you please comment?

**Comment by choumx** [comment]
Deduping with #25418.
