### ISSUE TITLE
Date-Picker Locale doesn't work

### ISSUE THREAD

**Issue by 88kbbq** [ampproject/amphtml#19524]
After implementing the amp-date-picker, I found that the `locale` attribute doesn't do anything. We have a multi-lingual site, need to change the locale per language. That would be easy if the `locale` attribute could access a URL with translation or something. 

Hurry guys! This is a very humiliating problem to have in 2018 with a framework like AMP.

**Comment by aghassemi** [comment]
@88kbbq Please follow [Code of Conduct](https://github.com/ampproject/amphtml/blob/master/CODE_OF_CONDUCT.md) when filling issues. Missing features / bugs are normal part of software development and GitHub issues if not a platform for rant. 

/to @cvializ to triage.

**Comment by 88kbbq** [comment]
I'd consider that some strong encouragement, not a rant. Locale is in the docs but does nothing at all. Just saying. If there is missing functionality, kindly note that in your documentation so the hard working devs who adopt AMP don't have to bother you here. And not everyone in the world speaks English. I just have no idea why language is such an afterthought in the United States. Even your calendar info icon is only in English. 

There's your rant.

**Comment by 88kbbq** [comment]
I read through all the issues and found that you're not using HTML ISO Language Code Reference codes. Using zh-Hant doesn't work but zh-tw does. That threw me off. All good. Thank you and close.
