### ISSUE TITLE
amp-story bookend consent inconsistent margin.

### ISSUE THREAD

**Issue by GrizzlyEnglish** [ampproject/amphtml#19557]
**Not sure if issue or intended, just looks off.**

## What's the issue?

When you reach the bookend with an amp-story-consent and see the bookends consent the margin is 32px (class: `i-amphtml-story-bookend-consent`), whereas the rest of the bookend components have 24px margins (class: `i-amphtml-story-bookened-component-set `and `i-amphtml-story-bookend-replay`)

## How do we reproduce the issue?

Create an amp-story with a amp-story-consent and reach the bookend. Where you see "Change data privacy settings" it is shifted more to the left than the rest of the components.

## What browsers are affected?

All browsers

## Which AMP version is affected?

1811202257200

**Comment by Enriqe** [comment]
Thanks for the report, I'll take a look.
