### ISSUE TITLE
foreignObject not allowed in inline <svg>

### ISSUE THREAD

**Issue by hw-dwalter** [ampproject/amphtml#19554]
I am using foreignObject in inline svg tags. As stated here https://www.ampproject.org/docs/fundamentals/spec#svg foreignObject should be allowed in svg. But validator will complain about it. Is this a bug or feature?

I have to put my svg inline because i am using apt-bind bindings https://www.ampproject.org/docs/reference/components/amp-bind#bindings
These special attributes seem to be only "valid" if svg is inline.

**Comment by honeybadgerdontcare** [comment]
@hw-dwalter 	Could you provide a code sample that fails validation for this? `filter` is allowed as an attribute. You can test your code sample at `validator.ampproject.org`.

**Comment by hw-dwalter** [comment]
Of course, here is the sample that fails validation  
https://gist.github.com/hw-dwalter/5fb27af180ea233690214d4df012ec53  
See validation result  
https://validator.ampproject.org/#url=https%3A%2F%2Fgist.githubusercontent.com%2Fhw-dwalter%2F5fb27af180ea233690214d4df012ec53%2Fraw%2F3fd87ced4e155980b3bfc0a5aed9963baceb845b%2Famp%252520svg%252520foreignObject.html

**Comment by honeybadgerdontcare** [comment]
`foreignObject` is allowed as an attribute to `filter`. It looks like you want to allow the `foreignObject` as a sub tag for `svg`.

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject

@aghassemi 	any objections to allowing `foreignObject` tag as a ancestor to `svg`?

**Comment by choumx** [comment]
Assuming that the `foreignObject` content will be parsed by the validator as normal HTML, I don't see any problems with it.

**Comment by Gregable** [comment]
Parsing foreignObject is not well supported in the HTML parsers for the AMP validator. In particular, you get into some complex state as these can nest with a lot of complexity:

`<svg><foreignobject><svg><foreignobject>...`

There is very little usage of this seen in the wild when it was removed from the validator(https://github.com/ampproject/amphtml/pull/14460/files). When I looked at the time, I couldn't find a single example in millions of AMP documents, even though it was valid.

**Comment by Gregable** [comment]
As an example of this is:

`<html><svg><foreignobject><div></foreignobject><foo/></svg>`

When loading this doc into Chrome and looking at it with the inspect
element. The foo tag ends up inside the div which ends up inside the
foreignobject. The AMP validator does not know how to correctly handle these cases, nor is it trivial to do so.

Considering the non-existing usage, and the high cost to implementing, I'd recommend against.

I wonder if there is a better solution to the amp-bind problem?

**Comment by choumx** [comment]
> I have to put my svg inline because i am using apt-bind bindings https://www.ampproject.org/docs/reference/components/amp-bind#bindings
These special attributes seem to be only "valid" if svg is inline.

@hw-dwalter Can you give an example that shows which bindings aren't working for you?

**Comment by hw-dwalter** [comment]
Here https://codepen.io/hw-dwalter/pen/GzMxZj I prepared an example. If the `<svg>` is inline, the foreinObject and amp-bind work well. Of course, foreinObject does not validate as amp.
The two images https://knuckl.es/amp-bind1.svg and https://knuckl.es/amp-bind2.svg use nearly the same markup:
```xml
<svg width="100%" height="100" xmlns="http://www.w3.org/2000/svg">
<foreignObject width="100" height="100">
<div xmlns="http://www.w3.org/1999/xhtml">
Here is a <strong [text]="myText">paragraph</strong> that requires <em>word wrap</em>
</div>
</foreignObject>
</svg>
```
amp-bind2.svg without the amp-bind attribute and amp-bind.svg with. The last one throws an parser error in my browser:
![image](https://user-images.githubusercontent.com/1303452/52327867-e22b7e80-29ed-11e9-8a12-10623c9b3daf.png)

**Comment by choumx** [comment]
Looks like the SVG parser fails on bracket characters. amp-bind supports an alternate syntax e.g. `data-amp-bind-foo` instead of `[foo]`. However, the larger issue is that amp-bind doesn't inspect or mutate external SVGs. So this won't work unless the AMP validator supports `foreignObject`.

Can you share your high-level use case? Since implementing this FR is a significant amount of work, it will help provide data and context for prioritization.

**Comment by Gregable** [comment]
I'm going to close this. If there is an actual use case still depending on this, please reopen.
