### ISSUE TITLE
Source maps are inaccurate

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#19585]
Seem to work fine when testing with karma, but do not work when running the local dev server.

The command I use is `gulp`

**Comment by calebcordry** [comment]
Ok did some investigation. The problem lies here https://github.com/ampproject/amphtml/blob/ebf4e77186692ed274edb74167f7d9c06dbdec4f/gulpfile.js#L1273

This line wraps all the built files with the `(self.AMP=self.AMP||[]).push...` code based on filename and some logic in `compile-wrappers.js`. The problem is that this is after the source maps have already been generated here 
https://github.com/ampproject/amphtml/blob/ebf4e77186692ed274edb74167f7d9c06dbdec4f/gulpfile.js#L1255-L1256

This plugin [`gulp-wrap`](https://github.com/adamayres/gulp-wrap) is not supported by the [gulp sourcemap ](https://github.com/gulp-sourcemaps/gulp-sourcemaps) plugin that we are using. (You can see the [supported plugins here](https://github.com/gulp-sourcemaps/gulp-sourcemaps/wiki/Plugins-with-gulp-sourcemaps-support))

Some ideas I had:
1. try to change the order of piping. This did not help.
2. use [supported wrap plugin](https://www.npmjs.com/package/gulp-wrap-js) but it's compiled code was throwing errors and does not appear to be well maintained.
3. try to do it with `regexpSourcemaps`, since we are already using this compatible regex plugin to replace runtime version.
4. use gulp-babel instead of babel for browserify (babelify) 

I think #4 has the most promise. The idea is that then we could wrap the code before sending it to babel and _hopefully_ babel would do the right thing without mangling the wrapping.

**Comment by lannka** [comment]
@calebcordry do you think it's a generic problem not just happen in amp-analytics extension?

**Comment by calebcordry** [comment]
Correct, it is a problem with all extensions.

**Comment by lannka** [comment]
+ @erwinmombay @rsimha if they have any ideas

**Comment by calebcordry** [comment]
closed by #19724
