### ISSUE TITLE
Extra files being included in the Travis pr-check.js

### ISSUE THREAD

**Issue by torch2424** [ampproject/amphtml#19604]
As stated in the team chat, some PRs are failing in travis due to incorrect files being added to their `pr-check.js`.

For example, see the following PRs and their Travis failures:

#19556 (Best Example)
#19334

**Comment by rsimha** [comment]
I'm pretty sure this is due to #19558

Assigning to @danielrozenberg

**Comment by rsimha** [comment]
I realized what's going on here. For the "files changed" check, we need to use the original branch point logic as it used to be. For the visual test baseline, we need to do what you recently added. 

I think splitting this into two functions is the way to go.

**Comment by danielrozenberg** [comment]
Thanks for the analysis! I'll fix this asap
