### ISSUE TITLE
 Chrome audit error for passive listeners 

### ISSUE THREAD

**Issue by 88kbbq** [ampproject/amphtml#19612]
Noted this issue in chrome audit for Best Practices:

> Does not use passive listeners to improve scrolling performance
> Consider marking your touch and wheel event listeners as `passive` to improve your page's scroll performance. Learn more.
> URL
> Location
> /v0/amp-carousel-0.1.js(cdn.ampproject.org)
> line: 44
> /v0/amp-carousel-0.1.js(cdn.ampproject.org)
> line: 33
 Lowers my score so not sure how important this is.

**Comment by jpettitt** [comment]
Not important. AMP balances cross browser compatibility so not all Chrome recommendations are applicable.
