### ISSUE TITLE
Broken images/carousel

### ISSUE THREAD

**Issue by 88kbbq** [ampproject/amphtml#19616]
As of about 7pm local time (Taipei), nearly half of all images and carousel images returned 404. 
I have not touched my website since. 

This happened before with issue #15695 when someone updated and AMP component js. Looks like there's been a lot of activity, new commits and whatnot. 

AMP team, please, if you make changes to a component js library, kindly update the js file version and issue a warning to update component JS like you do now. These breaks can cost companies a lot of money, so let's not just think like developers, think of AMP as an extremely valuable, yet fragile, business tool.

Looking forward to a fix soon. https://www.88k.com.tw

**Comment by 88kbbq** [comment]
Ok, after further inspection, I see a "amp-notsupported" in the class of select images:

`class="i-amphtml-element i-amphtml-layout-responsive i-amphtml-layout-size-defined i-amphtml-layout amp-notsupported"`

**Comment by jpettitt** [comment]
I'm not seeing this on your pages can you provide a link to a page the shows the problem?

**Comment by choumx** [comment]
`amp-notsupported` class is added when an AMP component fallback is toggled. For amp-img, this happens when the image fetch fails, e.g. 404. 

Looks like images on your home page are hosted on `https://www.88k.com.tw/img/`. If you only noticed this on your own domain's pages (i.e. `88k.com.tw`, not `cdn.ampproject.org`), it's probably an issue on your hosting service. I'd contact them to see if there was a recent outage.

**Comment by jpettitt** [comment]
Reducing to P2 since we can't reproduce it.

**Comment by jpettitt** [comment]
Note there was no code push/release at the time cited so it's unlikely this was change to the amp runtime.  I've edited the issue title accordingly.

**Comment by 88kbbq** [comment]
It was a very unusual issue. There were absolutely no code changes or image modification to my static site. Images are now appearing normally and I haven't been on this server since I found the problem. I'm suspecting cache somewhere, but not my browser. Hum... Closed.

**Comment by jpettitt** [comment]
For future reference the first place to start with a broken image is always to try and load the image url in a stand alone browser window to confirm the image actually exists and can be served.

**Comment by 88kbbq** [comment]
Yes, of course I examined everything I could think of before bothering you guys. Nav to the image url just opened the homepage. Extremely weird and couldn't fix it by clearing caches anywhere. Since the js broke once before, I thought to post then went straight to git to try to find something that could help. I do apologize for the annoyance. Good news is that it's all live and working. Cheers!
