### ISSUE TITLE
Single Pass: Generate sourcemaps for alternative amp binaries

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#19620]
We currently do a `post` concatenation process to generate our "alternate" main binaries (shadow-v0.js, amp4ads-v0.js) they are a sum of the `v0.js` file plus their respective code `src/amp-shadow.js`, `src/inabox/amp-inabox.js`.

Because this concatenation step is already after the closure compiler has ran we do not have source maps for `shadow-v0.js` or `amp4ads-v0.js`. 

Can we use something like magic string to fix this issue?

**Comment by rsimha** [comment]
@jridgewell is working on this

**Comment by jridgewell** [comment]
https://github.com/ampproject/amphtml/pull/23327
