### ISSUE TITLE
Fix lint errors in the repository

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#19635]
If you run `gulp lint` in the repository, you'll get a bunch of lint warnings that look like this: 

```
[12:30:46] Starting 'lint'...
[12:30:50] /Users/cathyzhu/Code/amphtml/3p/3p.js
  71:21  warning  Must use a literal string for argument[1] on assert call.
	If you want to pass data to the string, use `%s` placeholders and pass additional arguments  amphtml-internal/no-non-string-log-args

✖ 1 problem (0 errors, 1 warning)
  0 errors and 1 warning potentially fixable with the `--fix` option.

[12:30:51] /Users/cathyzhu/Code/amphtml/3p/iframe-transport-client.js
   43:9   warning  Must use a literal string for argument[1] on assertString call                                                                                          amphtml-internal/no-non-string-log-args
   48:39  warning  Must use a literal string for argument[1] on assert call.
	If you want to pass data to the string, use `%s` placeholders and pass additional arguments  amphtml-internal/no-non-string-log-args
   56:9   warning  Must use a literal string for argument[1] on assertString call                                                                                          amphtml-internal/no-non-string-log-args
   68:15  warning  Must use a literal string for argument[1] on assert call.
	If you want to pass data to the string, use `%s` placeholders and pass additional arguments  amphtml-internal/no-non-string-log-args
   70:15  warning  Must use a literal string for argument[1] on assert call.
	If you want to pass data to the string, use `%s` placeholders and pass additional arguments  amphtml-internal/no-non-string-log-args
   74:19  warning  Must use a literal string for argument[1] on assert call.
	If you want to pass data to the string, use `%s` placeholders and pass additional arguments  amphtml-internal/no-non-string-log-args
  132:5   warning  Must use a literal string for argument[1] on assert call.
	If you want to pass data to the string, use `%s` placeholders and pass additional arguments  amphtml-internal/no-non-string-log-args
```

Some of these, e.g. the ones related to assert are relatively easy to fix. Basically instead of concatenating strings, we'd like to do variable substitution. For example, we'd like to change 

```
  user().assert(fn, 'Unknown 3p: %s' + id);
```
to

```
  user().assert(fn, 'Unknown 3p: %s', id);
```

For a sample PR that does some of this, see: https://github.com/ampproject/amphtml/pull/19324. 

As a Good First Issue, pick any file that has some of these warnings, and try to fix all the warnings in that given file to familiarise yourself with the codebase.

**Comment by signalcat** [comment]
Can I claim this issue?

**Comment by cathyxz** [comment]
Sure thing! Feel free to send in a PR and tag me as the reviewer.

**Comment by jpettitt** [comment]
FWIW I don't think the % placeholder actually works, at least it didn't on logging last time I tried it. @erwinmombay added that warning.

**Comment by erwinmombay** [comment]
@cathyxz im trying to get this in https://github.com/ampproject/amphtml/pull/19251 today. some of the assert methods aren't variadic, that needs to be fixed first.

**Comment by rsimha** [comment]
In addition, there are ~50 warnings with the text `VSync is now a privileged service` that we should fix soon. See https://travis-ci.org/ampproject/amphtml/jobs/499527288#L1461

/cc @jridgewell

**Comment by aghassemi** [comment]
These all have been [fixed](https://travis-ci.org/ampproject/amphtml/jobs/547201121#L369)

**Comment by rsimha** [comment]
Lint errors (like the `VSync` error mentioned above) were merely silenced in #22294. The code still needs fixing. I'll let @jridgewell comment on whether this work is still relevant.
