### ISSUE TITLE
Add page indicator to amp-carousel

### ISSUE THREAD

**Issue by tori3** [ampproject/amphtml#1963]
Other carousel js library (such as bootstrap) viewing the page indicator to carousel.
http://getbootstrap.com/javascript/#carousel
 I think it's thought to be preferred as a UX.

e.g

``` html
<amp-carousel height="280" type="slides">
  <amp-img src="..."></amp-img>
  <amp-img src="..."></amp-img>
  <amp-img src="..."></amp-img>
  <ol class="amp-carousel-indicator" style="position:absolute; bottom: 20px; left: 50%; text-align: center;list-style:none; width: 60%; margin-left:-30%;">
    <li class="amp-carousel-indicator-0" style="display: inline-block; width: 10px; height: 10px;
margin: 1px;">◯</li>
    <li class="amp-carousel-indicator-1" style="display: inline-block; width: 10px; height: 10px;
margin: 1px;">◯</li>
    <li class="amp-carousel-indicator-2" style="display: inline-block; width: 10px; height: 10px;
margin: 1px;">◯</li>
</ol>
</amp-carousel>
```

**Comment by tori3** [comment]
When only set as type="slides" and add "indicator" attribute, shown like sample img.

<img width="406" alt="2016-02-14 22 26 12" src="https://cloud.githubusercontent.com/assets/1157530/13033913/4359dcc0-d36a-11e5-8252-8a7a685ae545.png">

**Comment by vilcheztorrado** [comment]
I've been testing the carousel extension and implementation of new possible improvements . I have implemented the following
![image](https://cloud.githubusercontent.com/assets/10107168/13315794/38fdd95c-dbad-11e5-8d68-5ad650f5ae3f.png)

I propose that the slide carousel are improved to prevent two images displayed simultaneously stay.
It should detect the movement direction and if it shows more than 25% of the next image and stop the slide should advance to the next image.

**Comment by dvoytenko** [comment]
@tori3 @vilcheztorrado: these are pretty cool. Let me loop in @ericlindley-g on this.

> I propose that the slide carousel are improved to prevent two images displayed simultaneously stay.

Not sure about this one? Do you mean that carousel sometimes gets stuck? If so - this is a bug, could you please file a separate issue for it?

**Comment by erwinmombay** [comment]
@vilcheztorrado that is really neat!

**Comment by ericlindley-g** [comment]
@tori3 @vilcheztorrado 

Agreed—both are a big improvement in the amount of information we give to the user. I'm going to follow up with some UX folks here to get some feedback on the interaction, and touch base again soon.

**Comment by vilcheztorrado** [comment]
> I propose that the slide carousel are improved to prevent two images displayed simultaneously stay.

@dvoytenko  when you slide the carousel in mobile ( not with arrows ) you can hold visible two images at once.

![image](https://cloud.githubusercontent.com/assets/10107168/13347566/f9d3d890-dc6e-11e5-9a5a-7f966f6c7c25.png)

This is the result when slide end. I think that this is the default functionality.

**Comment by dvoytenko** [comment]
@vilcheztorrado but when you release gesture - it all goes normal to a single slide, right?

**Comment by jridgewell** [comment]
@dvoytenko: Nope. Worse, clicking the arrows afterwards slides both items over so that there are still two slides showing. Seems to only happens with `type="slides"`.

**Comment by dvoytenko** [comment]
That sounds definitely like a bug. @erwinmombay could you please take a look?

**Comment by vilcheztorrado** [comment]
@dvoytenko as @jridgewell answered, when you release the swipe gesture it doesn't slide to an image, it stays where you left it. It happens by default (`type="carousel"`), with `type="slides"` it works fine.

**Comment by dvoytenko** [comment]
@vilcheztorrado Hmm. But that's the point of `type=carousel` - it's just a flimstrip with arbitrary scroll position. If you need one-slide-at-a-time - `type=slides` is the right option.

**Comment by ericlindley-g** [comment]
Adding @ed-lea for UX feedback

**Comment by dvoytenko** [comment]
Ok, so it looks like we have few things conflated here. Let's focus in this issue on indicators (whether dots or thumbnails). I opened #2355 for additional or alternative ways to customize carousel.

**Comment by ed-lea** [comment]
re: carousel / arbitrary film strip that can land the view with two images showing, that is one possible variation.

There are some carousels that are very low friction feeling, but do eventually snap to a whole image. So you can have momentum, but it always lands on a whole image.

The important part of a carousel (vs slides) is that you can scroll through a lot of content quickly. As long as that is true, you can try to snap to whole images (but I think it works if you don't too).


re: arrow Vs thumbnail. The problem on mobile is going to be that the thumbnails bleed off the edge of the phone. One app that has solved this very well is Instagram on the filters page. Clicking on a filter thumb also moves the filter carousel along. It's a neat solution, but in our case, we have to figure out how to transition to the new image above. In this case you will want to avoid movement and move more to a fade for the larger image.

**Comment by camelburrito** [comment]
@erwinmombay - the bugs reported here should have been fixed with slidescroll launch.

**Comment by ericlindley-g** [comment]
Reopening — some of the "bugs" in the thread have been fixed, but the primary feature request for an affordance indicating the number of items in the carousel has not been addressed, and there have been a few nice proposals that would be good to preserve.

**Comment by erwinmombay** [comment]
closing this, as this should be possible with `bind`

**Comment by ericlindley-g** [comment]
Tracking the task to create an example for this in [AMP by Example](https://github.com/ampproject/amp-by-example/issues/579)
