### ISSUE TITLE
🌸 Cherry pick request for #19632 into #19659 (Pending)

### ISSUE THREAD

**Issue by jeffkaufman** [ampproject/amphtml#19656]
**GitHub issue your cherry pick is fixing:**

Issue #19653

**PR that you are requesting a cherry pick for:**

PR #19632 

**Release(s) you requesting this cherry pick into:**

Release #19659

Production Release? NO

Canary release? YES
Release Issue #19659

*Why does this issue meet the [cherry pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?  Be specific.*

This issue is blocking the Inabox release, which because of the Thanksgiving production freeze and then this issue is still on the 2018-11-09 release cut.  Because Inabox is about to freeze for end of year holidays, if we don't fix this now and get a release out we'll need to wait until January to discover any regressions or test new features.

**Comment by cramforce** [comment]
Approved
