### ISSUE TITLE
Validator highlights incorrect CSS properties but doesn't flag them as errors

### ISSUE THREAD

**Issue by dandv** [ampproject/amphtml#19671]
## What's the issue?

Invalid CSS properties are not flagged, but it would be useful to flag them in order to assist with catching typos. The example below is something I've seen in the wild. Paste it at https://validator.ampproject.org/ and notice that the validation status is "PASS" but the `margin-button` CSS property is a typo and won't work as the developer intended.

Additionally, the closing `</html>` tag is incorrectly highlighted as an error.

![image](https://user-images.githubusercontent.com/33569/49546531-54b89a80-f895-11e8-8ffb-f42630cff14b.png)

## How do we reproduce the issue?

```html
<!doctype html>
<html amp lang="en">

<head>
  <meta charset="utf-8">

  <script async src="https://cdn.ampproject.org/v0.js"></script>

  <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">

  <link rel="canonical" href="https://www.google.com/amp/template-4.html">

  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>

  <style amp-custom>
    body {
      margin-button: 2em;  /* should be margin-bottom */
    }
  </style>

  <body>
</body>
</html>
```

**Comment by honeybadgerdontcare** [comment]
Hi @dandv 

The Validator is to detect and provide feedback around AMP spec issues and not intended to provide feedback on all things that may go wrong in developing a html document. It may be useful to incorporate other tooling to catch things like this such as W3C's CSS Validation Service[1].

Also, this document is considered a valid AMP document despite it having an unknown CSS property name and also not closing the `<head>` tag before `</html>`. The UI that validator.ampproject.org uses happens to highlight these two issues in red, but that is not a part of actual AMP validation, just the widget used within the UI.

[1] https://jigsaw.w3.org/css-validator/validator
