### ISSUE TITLE
Error reporting: JS engine is detected as IE when running in Chrome

### ISSUE THREAD

**Issue by zhangsu** [ampproject/amphtml#19682]
## What's the issue?

In the error reporting code, the `jse` parameter of the error report is detected as `IE` even though I'm running AMP in Chrome.

## How do we reproduce the issue?

1. Start up a local AMP server.

2. Modify `examples/amp-list.amp.html` and make one of the amp-list's `src` attribute point to a URL that doesn't exist (to trigger a user error on 404 response code).

3. Disable a bunch of checks in `error.js` that would fail in local environment or increase development cycle. I had to disable this check locally:

https://github.com/ampproject/amphtml/blob/781be6ba70ca08e3ce8095ec9041b6e0dd24e4e7/src/error.js#L304

and this check:

https://github.com/ampproject/amphtml/blob/781be6ba70ca08e3ce8095ec9041b6e0dd24e4e7/src/error.js#L313

and this check:

https://github.com/ampproject/amphtml/blob/781be6ba70ca08e3ce8095ec9041b6e0dd24e4e7/src/error.js#L476

4. Navigate to `http://localhost:8000/examples/amp-list.amp.html`. 

5. Put a breakpoint at the following line:

https://github.com/ampproject/amphtml/blob/781be6ba70ca08e3ce8095ec9041b6e0dd24e4e7/src/error.js#L650

6. Refresh the page, observe that the break point is triggered, meaning that the JavaScript engine is detected as IE even though we are running in Chrome.

/cc @choumx 
/cc @alabiaga 
/cc @jridgewell

**Comment by jridgewell** [comment]
This is a best effort guess. As Chakra (IE's JS engine) aligns more closely with V8, it's getting harder to tell. We're purposefully not using the user agent string here, since it can be changed at will in browsers.

**Comment by choumx** [comment]
In this case it's the converse: Chrome is incorrectly being identified as IE. I think we should be able to do a better job.
