### ISSUE TITLE
<amp-subscriptions> subscriptions-action event fire repeatedly 

### ISSUE THREAD

**Issue by wigth** [ampproject/amphtml#19684]
## What's the issue?
subscriptions-action event fire twice after subscriptions-action="login"

As I understand LocalSubscriptionPlatform recreated after every click on action and run in constructor method initializeListeners_. This method add new listeners but never remove them and EventListener from previous instance is stil alive . 

This is call stack show this behavor. 
Fb (local-subscription-platform.js:122)
Eb (local-subscription-platform.js:94)
rc (amp-subscriptions.js:142)
(anonymous) (amp-subscriptions.js:489)
push.f.g.resetPlatforms (amp-subscriptions.js:488)
push.f.g.resetPlatforms (service-adapter.js:80)
(anonymous) (local-subscription-platform.js:175)
Promise.then (async)
push.f.g.executeAction (local-subscription-platform.js:173)
(anonymous) (local-subscription-platform.js:139)

## How do we reproduce the issue?

1) Go to AMP page with subscriptions-action 
2) Click on button with action subscriptions-action="login"
3) Authorize
4) when you are back to the page click on another button with action subscriptions-action. For example subscriptions-action="logout"

Observed result:
New window is opened and user stays on it, because event fire twice

## What browsers are affected?

All browsers.
Tested on android google chrome.

## Which AMP version is affected?
1811272154520

**Comment by jpettitt** [comment]
This is a side effect of a fix we put in #19455 working on a fix
