### ISSUE TITLE
Add integration test coverage for various amp-analytics triggers

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#19706]
- [x] click trigger
- [x] element visible trigger
- [x] timer trigger
- [x] scroll trigger

**Comment by zhouyx** [comment]
🎉 
Few more testing ideas. Test batching, also use batching to test multiple request in one
test amp-analytics with sandbox equals true
custom events that works with other component.

**Comment by lannka** [comment]
We already had some coverage for batch mode in test-amp-analytics.js

Sandbox & custom events does need extra coverage. tracked separately: #20126 #20127
