### ISSUE TITLE
[amp-geo] #amp-geo=fr does not work in DevChannel

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#19713]
I can't enable the amp-geo testing mode.

Steps to reproduce:

1. Enable DevChannel via https://cdn.ampproject.org/experiments.html
2. Visit https://ampbyexample.com/components/amp-geo/#amp-geo=fr
3. Click on "Where am I?" at the bottom of the page

Actual behavior: Matched Country Groups is empty (unless you're in france)
Expected beavior:  Matched Country Groups is `football` 

//cc @jpettitt 

P.S. it works when testing on localhost.

EDIT: fixed the wrong expected behaviour description.

**Comment by jpettitt** [comment]
Hmm, working for me - which browser are you using (Safari ITP2 breaks dev channel)

![image](https://user-images.githubusercontent.com/524856/49657240-0ff74580-f9f4-11e8-8ee0-a5ee5ea38372.png)

**Comment by sebastianbenz** [comment]
It's not working for you: the Matched Country Groups should contain `unknown`.

**Comment by sebastianbenz** [comment]
Ah - that's it. I was using Safari. That confused me for a moment. The group issue was already reported in the other issue.
