### ISSUE TITLE
amp-selector reference points don't match self-closing descendants

### ISSUE THREAD

**Issue by tbaik** [ampproject/amphtml#19712]
## What's the issue?

Trying to use the option, selected, or disabled attributes for svg elements throws a validation error saying something like "The attribute 'option' may not appear in tag 'g'." We should be able to use all three of these attributes on svg elements so that svgs can be used with amp-selector.

## How do we reproduce the issue?

See the console logs from this page: https://output.jsbin.com/mobameg#development=1. (code: https://jsbin.com/mobameg/edit?html,output)

## What browsers are affected?

Not browser specific. For AMP Validations

## Which AMP version is affected?

Latest.

**Comment by choumx** [comment]
This should be allowed. It looks like the validator has an edge case with self-closing tags i.e. `<rect></rect>` is allowed but `<rect />` isn't. Try using the former as a workaround for now.

/to @Gregable

**Comment by Gregable** [comment]
Correct, this is actually allowed. The javascript version of the validator doesn't fully understand the differences in parsing rules between html and svg xml. Either will work in Google services.
