### ISSUE TITLE
[amp-selector] toggle action does not fire select event

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#19719]
Given an amp-selector with an on select event handler:

```
<amp-selector id="myTabs" class="tabs" on="select:myTabPanels.toggle(index=event.targetOption, value=true)">
...
</amp-selector>
```

When I toggle a specific element:

```
<button on="tap:myTabs.toggle(index=1, value=true)">
    Select Tab 2
  </button>
```

Then the selected option is changed, but the on select event handler is **not** triggered.

Here is a demo: https://jsbin.com/tosudebasi/1/edit?html,output

Another thing I've noticed: by default the option value is undefined. Why not initialise it with the index instead?

//cc @aghassemi

**Comment by sparhami** [comment]
Another way to achieve this is using `setState`: https://jsbin.com/qupaxoteka/edit?html,output

I'm not sure if that is the preferred way to do it, but I suppose it can't hurt to fire the event here.
