### ISSUE TITLE
[amp-geo] 'unknown' country not part of amp-state 

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#19714]
The country grouping does not list groups for `unknown` flag. 

Steps to reproduce:

1. Serve https://ampbyexample.com/components/amp-geo/#amp-geo=fr from localhost (see #19713 for why this is needed).
2. Click on "Where am I?" at the bottom of the page.

Actual behavior: `Matched Country Groups:` is empty
Expected beavior: `Matched Country Groups:` is `football`

//cc @jpettitt

**Comment by sebastianbenz** [comment]
You need to click on "where am I" to test the behaviour. The matched country groups is '' (as in the screenshot you posted on the other issue).

**Comment by jpettitt** [comment]
In your example the country isn't `unknown` - it's `fr` if you set `#amp-geo=unknown` it will match.

**Comment by sebastianbenz** [comment]
Ah ok - thanks for the clarification.
