### ISSUE TITLE
FR: input clear action

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#19749]
There's no simple way to clear an input field (when not using an amp-form). My use case is adding items to a list which is maintained client-side in amp-state. The simplest way I could come up with is:

```
  <input on="input-throttled: AMP.setState({ newItem: event.value });
             change:AMP.setState({ newItem: '', items: items.splice(items.length, 0, event.value) })"
         [value]="newItem">
```

Which is way too complicated for such a simple thing. The other option is using a dummy form:

```
<form action-xhr="https://example.com" method="post">
  <input  change:AMP.setState({ items: items.splice(items.length, 0, event.value) }),
        myForm.clear">
</form>
```

Which is slightly simpler, but still annoying as it requires defining a dummy form endpoint.

It'd be great to have a clear action for form input fields so that it'd become possible to write this like:

```
 <input id="myInput" 
        change:AMP.setState({ items: items.splice(items.length, 0, event.value) }),
        myInput.clear">
```

//cc @choumx

**Comment by cvializ** [comment]
This makes a lot of sense. Let's work on this soon. Thanks @sebastianbenz!

**Comment by aghassemi** [comment]
This has been implemented AFAIK. 

Please reopen if I am wrong

**Comment by cvializ** [comment]
Yes it was, by #14020. Thanks!

**Comment by sebastianbenz** [comment]
This original issue was about clearing an input field **without a form**. This is still not possible.
