### ISSUE TITLE
Amp ads type="adsense" are not showing up

### ISSUE THREAD

**Issue by Narendharr** [ampproject/amphtml#19743]
AMP ads with type="adsense" and type="a9" are not showing the ads.

I have tested some type of ads here https://www.narendesigns.com/projects/html/amp-test/amp-ad.html

This might be a bug in Google AMP implementation.

It used to work before. I created a website and used ads on https://www.bosloker.com/lowongan-kerja/semarang/-terbaru.html but they are not showing up now.

**Comment by torch2424** [comment]
Confirmed this is working, and looking at the JS console there are a fair bit of errors.

cc @lannka @zhouyx you happen to know why this may be happening?

**Comment by lannka** [comment]
Looks like an empty ad is returned. @keithwrightbos any thoughts for further debugging?

<img width="1067" alt="screen shot 2018-12-18 at 11 00 09 am" src="https://user-images.githubusercontent.com/8496897/50178281-eaeab880-02b8-11e9-8cc0-ae71b7ac1447.png">

**Comment by bradfrizzell** [comment]
hi @Narendharr 

Have you made sure that this site is properly setup and approved on the adsense frontend?

**Comment by lannka** [comment]
Pls follow up with AdSense customer support. Feel free to reopen.
