### ISSUE TITLE
<amp-subscriptions-google> don't update subscriptions-dialog after purchase

### ISSUE THREAD

**Issue by wigth** [ampproject/amphtml#19747]
## What's the issue?

After the user has bought a subscription by button 'subscrbe with google' subscriptions-dialog not updated according to response from local service.
And subscriptions-dialogs with `subscriptions-display="data.p.someVariable and granted"` query don't appear.
After reload page work fine. 

As i understand method renderDialog_ in LocalSubscriptionPlatformRenderer should be called after purchase.

## How do we reproduce the issue?

1) add amp-subscriptions and amp-subscriptions-google in page
2) add this template
```
<div subscriptions-dialog subscriptions-display="data.p.someVariable and granted">
    some content
</div>
```
3) buy something by button 'subscribe-with-google'

Observed result:
No templates are displayed.

## What browsers are affected?

All browsers

## Which AMP version is affected?

1811272154520

**Comment by jpettitt** [comment]
I believe this is fixed in the current dev channel release which goes to prod tomorrow.  Do you have a repro case we can test?

**Comment by wigth** [comment]
We have only closed demo stand. Just report about release and we will check it right away.

**Comment by jpettitt** [comment]
You can enable dev channel here https://cdn.ampproject.org/experiments.html it should work with any code that uses standard AMP js files.

**Comment by jpettitt** [comment]
This fix should now be in production.  Please confirm and close the issue if it's fixed in your tests.

**Comment by wigth** [comment]
Bug was fixed. Thank you!
