### ISSUE TITLE
Inconsistent behavior of [min] and [max] attributes in amp-date-picker when used with amp-bind

### ISSUE THREAD

**Issue by belobrad** [ampproject/amphtml#19744]
## What's the issue?

The `[max]` parameter seems to be off by 1 day when set alone, `[min]` and `[max]` both seem to be off by 1 day with an incorrect styling of min day when set together via binding.

## How do we reproduce the issue?

Go to the *Date picker with amp-bind* section in:
https://ampbyexample.com/components/amp-date-picker/

* let's say the max date is set to 2018-12-20: I would expect the calendar to allow to select a valid date up to and including 2018-12-20; it allows only up tp 2018-12-19
* let's say the min date is set to 2018-12-12 and max date is set to 2018-12-20: I would expect any valid dates between 2018-12-12 and 2018-12-20 including to be selectable; it allows for dates between 2018-12-12 and 2018-12-19. Notice that the min date (2018-12-12) can be selected, however it is styled as blocked out of range

I was able to reproduce the same behavior locally.

## What browsers are affected?

All browsers

## Which AMP version is affected?

1811272154520

**Comment by aghassemi** [comment]
Thanks @belobrad 
@cvializ added to December FixIt project

**Comment by cvializ** [comment]
I am able to reproduce the behavior you're describing, and it looks like the behavior needs to be corrected. I'll try and find a root cause and fix in this fixit sprint. Thanks!
