### ISSUE TITLE
Make error reporting listen for unhandled promise rejections.

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1974]
Should be a simple addition to `src/error.js`

**Comment by jridgewell** [comment]
I don't currently have `unhandledrejection` events in our Promise polyfill. Should this be added?

**Comment by cramforce** [comment]
If you just throw it also works. A benefit of the event would be that non-Chrome browsers don't give the actual error object to window.onerror, so the event would have better exception info.
