### ISSUE TITLE
Validator failing with new amp-user-notification specifications

### ISSUE THREAD

**Issue by lordnerf** [ampproject/amphtml#1975]
AMP Validator (**Version 1455227594932** - windows - chrome 48.0.2564.109 m) generates errors with new specifications of amp-user-notifications:

> "amp-user-notification" (amp-user-notification1) should have "data-show-if-href" attribute.

**Comment by dvoytenko** [comment]
@lordnerf It sounds like it's just the rollout/cache latency. Do you have an example page? Could you please also take a look at what your version prints in the DevTools console. There should be a line "Powered by AMP ⚡ HTML – Version: ????"

@erwinmombay Could you please confirm that #1943 is in PROD now?

**Comment by erwinmombay** [comment]
@dvoytenko tested 1455227594932 on our examples and got rid of `data-show-if-href` and not getting validation errors. (have to clear my local storage to see the notification again)

**Comment by erwinmombay** [comment]
the amp-user-notification-0.1.js file might still be cached?

**Comment by erwinmombay** [comment]
oh no wait,https://github.com/ampproject/amphtml/pull/1943 is in canary but not in prod yet.

**Comment by erwinmombay** [comment]
@lordnerf we'll move amp-access from canary to prod today. and those errors should go away. appreciate the report!

**Comment by rudygalfi** [comment]
This is overdue on the Feb 19 milestone. Any update?

Optimistically closing, as per most recent comment this was just waiting on rollout.
