### ISSUE TITLE
Cherrypick paywall race condition fix

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#19753]
PR that you are requesting a cherry pick for:

PR #19733

Release(s) you requesting this cherry pick into:

1812061946500 (canary)

Production Release? NO

Canary release? YES

Why does this issue meet the cherry pick criteria? Be specific.

A significant race condition when deciding on paywall display.

/cc @jpettitt

**Comment by cramforce** [comment]
LGTM

**Comment by rsimha** [comment]
#19733 has now been cherry-picked to the canary branch: https://github.com/ampproject/amphtml/commits/canary.

I'll post an update here once the branch is tested and a new canary is pushed.

**Comment by rsimha** [comment]
This was pushed, tested by @dvoytenko, and released yesterday.

**Comment by rsimha** [comment]
Promoted to prod. Released with https://github.com/ampproject/amphtml/releases/tag/1812102014220

**Comment by rsimha** [comment]
This went into release #19659
