### ISSUE TITLE
JSON-LD: Allow <script type="application/ld+json"> in <body>

### ISSUE THREAD

**Issue by steffenweber** [ampproject/amphtml#1976]
For performance reasons I would like to place `<script type="application/ld+json">` elements with Rich Snippets data at the very bottom of my HTML code. Unfortunately, the AMP validator does not allow this:

```
The parent tag of tag 'script' is 'body', but it can only be 'head'.
```

Would it make sense to relax this rule?

**Comment by cramforce** [comment]
+1

@Gregable

**Comment by powdercloud** [comment]
@steffenweber Have you measured a performance difference?
I think this complicates the rules, making it harder for a humans and machines to find this information, since arguably meta data belongs into the head, that's what it's for. It would also take an exception compared to other things that are required to be in the head. If someone wanted to store only the head of the document e.g. for rendering bookmarks or search engine results, it's also sad to have this info someplace else.
I think none of these points would be strong if it really made a performance difference. I just doubt that.

**Comment by steffenweber** [comment]
Thank you for the answer. I have not done performance measurements. I think you'd have to be on a _very_ slow connection for these few bytes to make a difference (although sometimes there can be multiple `VideoObject` objects on a page in addition to the `NewsArticle` objects, so in some cases we may be talking about a few KB).

In principle I still like the idea of putting the JSON-LD at the bottom because it is not needed for rendering and therefore less important than all of the other HTML. But your second argument that metadata belongs into the head is a good one.

**Comment by cramforce** [comment]
The main difference comes from when you can flush the head to the socket. This is definitely a valid concern.

**Comment by steffenweber** [comment]
We currently don't flush the head early because some components may still have to add CSP directives. But in principle your argument sounds valid.

By the way, `amp-analytics` uses a `<script type="application/ld+json">` tag in the document body which validates. One could argue that this is metadata, too. Furthermore, the JSON-LD alternative "Microdata" lives in the body, too.

**Comment by Gregable** [comment]
json tags are now allowed as direct children of the `<body>` tag in addition to the `<head>` tag.

**Comment by jaygray0919** [comment]
excellent. Will not be able to place JSON-LD islands near their related DIV.

**Comment by Gregable** [comment]
@jaygray0919 , note that the current implementation still requires the `<script type="application/json">` to be a direct child of the `<body>` tag, so you can't place it inside a `<div>`. https://github.com/ampproject/amphtml/issues/3455 was started to discuss if we want to relax this further.

**Comment by jaygray0919** [comment]
Is this change about `<script type="application/json">` or `<script type="application/ld+json">`? Our concern relates to `<script type="application/ld+json">` and the ability to have many such structures (e.g. `<script type="application/ld+json" id="2">` in BODY.

**Comment by Gregable** [comment]
`<script type="application/ld+json">`, I mis-typed.
