### ISSUE TITLE
AMP4Email: Difficulty in layouts due to restrictions on binding state

### ISSUE THREAD

**Issue by anirudhkhanna** [ampproject/amphtml#19779]
I am facing some layouting issues while working with AMP4Email Dev Preview. Although I was able to solve most parts by taking the longer road, would still like to report some problems I faced and scenarios which could have been dealt better.

Suppose there is a list of item tiles shown (let's say via an API call from `amp-list`). On the click of each item, its details are to be shown in a larger view.

Sample API response (`/api/items`):
```
{
  items: [{
    name: "Item 1", imgUrl: "/image1.jpg", rating: "4.5"
  },
  {
    name: "Item 1", imgUrl: "/image1.jpg", rating: "3.8"
  }]
}
```

Here is what I tried initially:

```
<amp-list src="/api/items" ...>
  <template ...>
    <!-- On click: Set in state to use in the enlarged view -->
    <div on="tap: AMP.setState({
      name: '{{name}}',
      imgUrl: '{{imgUrl}}',
      rating: '{{rating}}'
    })"
    class="list-of-item-names"
    >
      {{name}} - Click me to view details
    </div>
  </template>
</amp-list>

<div class="selected-item-details">
  <h1 [text]="name"> Item 1 </h1> <!-- Works -->
  <p [text]="rating"> 4.2 </p> <!-- Works -->

  <amp-img [src]="imgUrl" ... > 4.2 </amp-img> <!-- Not supported in amp4email -->

  <!-- similarly can't have dynamic forms, lists, or even anchors which we could in AMP -->
</div>
```

In this case, I simply can't make such a dynamic layout if my work involves images.

Also, even if I compromise to make the API call again for fetching a specific item details - just to avoid state because it pretty-much is unusable in email - the API url can't be dynamic too.

```
<amp-list src="/api/items" ...>
  <template ...>
    <div on="tap: AMP.setState({
      name: '{{name}}'
    })"
    class="list-of-item-names"
    >
      {{name}} - Click me to view details
    </div>
  </template>
</amp-list>

<amp-list [src]="'/api/itemdetails/' + name" ...> <!-- Nope - Invalidates here -->
  <template ...>
    <div class="selected-item-details">
      <h1> {{name}} </h1>
      <p> {{rating}} </p>
      <amp-img src="{{imgUrl}}" ...></amp-img> <!-- Supported -->
    </div>
  </template>
</amp-list>
```

Is there any way to make such a dynamic layout without already having all possible item-details in DOM and show-hiding them based on state?

**Comment by fstanis** [comment]
How about rendering all items inside the `<amp-list>` and having them `hidden`, then binding to `[hidden]`?

Something like:

```html
<amp-list src="/api/items" ...>
  <template ...>
    <!-- On click: Set in state to use in the enlarged view -->
    <div on="tap: AMP.setState({
      name: '{{name}}',
      imgUrl: '{{imgUrl}}',
      rating: '{{rating}}'
    })"
    class="list-of-item-names"
    >
      {{name}} - Click me to view details
    </div>

    <div class="selected-item-details" hidden [hidden]="name == '{{name}}'">
      <h1> {{name}} </h1>
      <p> {{rating}} </p>
      <amp-img src="{{imgUrl}}" ...></amp-img>
    </div>
  </template>
</amp-list>
```
This should ensure only one of the `selected-item-details` divs is visible at a time.

**Comment by anirudhkhanna-oyo** [comment]
@fstanis yep. I actually have implemented just that. But it worked only because my items are finite and pre-known. 
How to deal if they are not known before-hand and I only rely on the api for them?

Also, I guess having all the possible items hidden in DOM will be an overkill in situations when there are lots of them - it is just an email after all. If I am not wrong, there is a limit of 100KB (although this is enough for my current use case, but still).

**Comment by anirudhkhanna-oyo** [comment]
Form looks to be a good idea in this case. Will try that out next.

**Comment by anirudhkhanna-oyo** [comment]
* This thread can be closed now *
Looks like the ways to make things work in amp4email are in-fact slightly indirect ones (when compared to AMP).
