### ISSUE TITLE
🌸 Cherry pick request for 19805 into 19659 (Pending)

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#19808]
**GitHub issue your cherry pick is fixing:**

Issue N/a

**PR that you are requesting a cherry pick for:**

PR #19805

**Release(s) you requesting this cherry pick into:**

Production Release? Release Issue #19659

Canary release? Release Issue (in process of being cut)

*Why does this issue meet the [cherry pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?  Be specific.*

On AMP Docs served inside an iframe to iOS, if the page contains any fixed-position elements _and_ a amp-bind attribute expression on the `<body>` (eg, `<body [class]="expression">`), `FixedLayer` will not transfer the fixed-position elements.

This is our current top error, with some 1m reports in the past day. (It recurs every time the fixed-layer tries to update).

/cc @cramforce

**Comment by cramforce** [comment]
This looks like a worthy cherry-pick. I'd feel better to go to canary first.

**Comment by rsimha** [comment]
This will go into today's canary cut: https://github.com/ampproject/amphtml/releases/tag/1812121952400

It can be cherry-picked to prod tomorrow if all looks good.

**Comment by rsimha** [comment]
This is now part of https://github.com/ampproject/amphtml/releases/tag/1812131718380
