### ISSUE TITLE
Support for Krux adding additional targeting to Ads

### ISSUE THREAD

**Issue by sethyates** [ampproject/amphtml#1980]

**Comment by rudygalfi** [comment]
@sethyates Can you add more detail to link to a PR?

Is this an intent to implement?

**Comment by rudygalfi** [comment]
cc @kashyapnitin @cramforce

**Comment by sethyates** [comment]
@rudygalfi yes this is an Intent to Implement. We might actually not need an amp-ads extension and rather just code for remote.html but are still reviewing.

**Comment by sethyates** [comment]
Were able to implement this entirely using remote.html and custom javascript.
