### ISSUE TITLE
Video analytics (currentTime, duration, playedRangesJson, and playedTotal) for amp-brightcove

### ISSUE THREAD

**Issue by bjalford** [ampproject/amphtml#19817]
Working with major UK publishers who use Brightcove and Permutive in a PWAMP set up and 

Some key metrics aren't available according to the docs here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-video-analytics.md#common-variables

In terms of 'partial support'  - Partial support means that all video analytics common variables are included, except for currentTime, duration, playedRangesJson, and playedTotal.

Is there a plan to introduce these common variables in amp-brightcove?

**Comment by torch2424** [comment]
Triaging to @aghassemi 😄 

cc @jeffjose

**Comment by aghassemi** [comment]
@bjalford Full support would require changes on Brightcove side which we in AMP can't make. /cc @mister-ben.

@bjalford We are also launching `amp-video-iframe` (https://github.com/ampproject/amphtml/blob/master/extensions/amp-video-iframe/amp-video-iframe.md) in the first half of January which could possibly be a workaround. Essentially, with `amp-video-iframe` publishers could integrated any video player with existing amp video features such as docking, analytics, etc.. (/cc @alanorozco)

**Comment by mister-ben** [comment]
This can be added. I'll look into it.
