### ISSUE TITLE
AMP4Email: Whitelisted email not able to send AMP mails to Test Account

### ISSUE THREAD

**Issue by anirudhkhanna-oyo** [ampproject/amphtml#19814]
Hello,

I am working on AMP4Email Dev Preview for my organization. We intend to go live with it on our prod mailers when AMP4Email support will be open (any dates?).
It is in development phase right now, and emails sent from Playground are working fine.

Now comes the email-triggering part...

We have a whitelisted email id and we are trying using it as a Sender to the Test Account provided. As of now we found that Gmail API does not support sending `x-amp-html` MIME Type. So, we are using Nodemailer to send AMP enabled emails (it has options to give custom MIME Type).

Still, we are only seeing HTML fallbacks in the email (the same layout works when sent via amp4email Playground).
We are successfully sending AMP Part in those emails (checked via "Show original email" which gives the MIME tree)... But the Test Account is not rendering the AMP part coming in the mails from whitelisted ID. It falls back to HTML content.

Any help possible, it would be greatly appreciated!

<img width="658" alt="screen shot 2018-12-10 at 5 29 20 pm" src="https://user-images.githubusercontent.com/30618147/49851188-4a9f1a80-fe06-11e8-9e8f-ea276379dcdf.png">

(tried shuffling order of MIME types for priority - always plain HTML is shown.)

**Comment by torch2424** [comment]
cc @choumx @fstanis

**Comment by choumx** [comment]
Hi Anirudh, if your company is signed up for the developer preview you should have access to a Gmail support channel to ask questions. 

Unfortunately, the AMP team are not experts on Gmail specifics so I'm afraid we can't help much here.

**Comment by anirudhkhanna-oyo** [comment]
Sure. Got it. 👍
