### ISSUE TITLE
AMP CDN scripts not loading. 

### ISSUE THREAD

**Issue by shawkivai** [ampproject/amphtml#19816]
## What's the issue?
AMP cdn scripts are not loading in our amp-site.  We are using several scripts in the header section of our amp site. and found this type of error in console for every single scripts.
![image](https://user-images.githubusercontent.com/32758956/49859977-0e2de780-fe23-11e8-8d10-b4252c2088ca.png)
Can you please let us know when this is happening all on a sudden!!
We need a quick fix of this issue.

## What browsers are affected?
All browsers for both Android and iOS.

**Comment by jpettitt** [comment]
This is almost certainly a local (firewall?) issue, we are not seeing any issues. Can you try it on multiple ISP's and if it fails indicate which service providers.
