### ISSUE TITLE
add a way to turn off instrumentation completely

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#1982]
the viewer should set a query param named "csi" with either a 1 or 0. (true/false). by default it will be off.

**Comment by cramforce** [comment]
Rather a fragment param. Cool. Lets turn off framerate measurement when this is set.

**Comment by erwinmombay** [comment]
@alf7 you ok with fragment param instead?

**Comment by alf7** [comment]
Yup, fragment is perfect.

**Comment by erwinmombay** [comment]
Closed via https://github.com/ampproject/amphtml/pull/2033
