### ISSUE TITLE
Intent to Implement: Flite ad serving for amp-ads

### ISSUE THREAD

**Issue by andyhills** [ampproject/amphtml#1983]
Adding [Flite](http://flite.com/) ads to the <amp-ad> elements.

Flite will submit a pull request via the flite/amphtml fork and the ads-flite branch.

**Comment by andyhills** [comment]
@cramforce Can you explain why one would be receiving the error "Uncaught Error: Unknown 3p: flite" when as far as I can tell, I included flite correctly in [3p/integration.js](https://github.com/ampproject/amphtml/blob/master/3p/integration.js) correctly?

You can see this issue in effect here:
http://services-staging.s3.amazonaws.com/AndyHills/AMP_HTML/all_ads.html

**Comment by cramforce** [comment]
it is not in production yet, see https://github.com/ampproject/amphtml/releases

You can see it working by opting into dev channel https://github.com/ampproject/amphtml#amp-dev-channel

We'll release later today.

**Comment by jasti** [comment]
Flite integration available now. 
https://github.com/ampproject/amphtml/blob/master/ads/flite.md
Closing this one out.
