### ISSUE TITLE
Amp-Youtube

### ISSUE THREAD

**Issue by aurbanczik** [ampproject/amphtml#19840]
At the end of a video I would like to either
not show any youtube recommendations at all
or
at least just those from my channel.
How do I code that ?

**Comment by aghassemi** [comment]
@aurbanczik We support all the parameters that YouTube exposes in `amp-youtube` So you can set any of the items in https://developers.google.com/youtube/player_parameters by adding a `data-param-<nameOfParam>=<value>` on your `amp-youtube` component.

The one you are looking for is `rel`. So adding `data-param-rel=0` will ensure recommendations are from the same channel as the video itself (based on https://developers.google.com/youtube/player_parameters#release_notes_08_23_2018)

**Comment by aghassemi** [comment]
Closing based on the answer above.

**Comment by aurbanczik** [comment]
Thank you !



Liebe Grüsse



Aleš 




https://rolfguild.eu
http://www.rolfyoga.com/


-----Original-Nachricht-----
Von: "Ali Ghassemi" <notifications@github.com>
An: ampproject/amphtml <amphtml@noreply.github.com>
Cc: aurbanczik <ales.urbanczik@rolfyoga.com>, Mention <mention@noreply.github.com>
Datum: 12.12.2018 23:46
Betreff: Re: [ampproject/amphtml] Amp-Youtube (#19840)


@aurbanczik We support all the parameters that YouTube exposes in amp-youtube So you can set any of the items in https://developers.google.com/youtube/player_parameters by adding a data-param-<nameOfParam>=<value> on your amp-youtube component.

The one you are looking for is rel. So adding data-param-rel=0 will ensure recommendations are from the same channel as the video itself (based on https://developers.google.com/youtube/player_parameters#release_notes_08_23_2018)
