### ISSUE TITLE
Add these links types to Validator Whitelist

### ISSUE THREAD

**Issue by ayumihamsaki** [ampproject/amphtml#19856]
This has never been an issue in the past and only this week the Validator is saying they are not Valid now?

I request AMP-HTML to Whitelist the following two links protocols:

## Facebook Messenger Share Links

These are made up using the following link pattern:

`href="fb-me://share?link=https%3A%2F%2Fwww.example.com"`

Validator Error Message:

```
Invalid URL protocol 'fb-me:' for attribute 'href' in tag 'a'. DISALLOWED_HTML
line 1351, column 22054
```

## WhatsApp Share Links

These are made up using the following link pattern:

`href="wh://send?text=https%3A%2F%2Fwww.example.com"`

Validator Error Message:

```
Invalid URL protocol 'wh:' for attribute 'href' in tag 'a'. DISALLOWED_HTML
line 1351, column 20538
```

**Please note:** I have had the following Social Media Links Shares running in AMP for over 2 years and never had a problem, only this week the Validator is now causing an issue.

I would suggest the AMP Team also test for all the other Messenger APPs as I would guess you are now blocking their Share Links as well.

**Comment by honeybadgerdontcare** [comment]
@ayumihamsaki 	Sorry you're running into this issue. We haven't allowed `fb-me` or `wh` previously. We have allowed `fb-messenger` and `whatsapp` and still do. https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii#L1514

We'll add `fb-me` and `wh` but you may want to use the existing allowed protocols till it's released in production.

**Comment by ayumihamsaki** [comment]
@honeybadgerdontcare Thanks for the info and pr, will save that list, very useful.
