### ISSUE TITLE
Allow using amp-sidebar links to scroll navigate within the page

### ISSUE THREAD

**Issue by TWsky** [ampproject/amphtml#19863]
## What's the issue?

Partner implement scrollTo action on tap event inside amp-sidebar. The scrollTo Behavior will automatically scroll back once the sidebar is closed.

## How do we reproduce the issue?

https://eikiy.github.io/NewEdit/AMP/01/index.html

1. Open sidebar
2. Click "店家位置“ (id="go05")
3. The viewport behind sidebar will scroll to the right section (section with id="go05")
4. close sidebar
5. The viewport automatically scroll back to top

## What browsers are affected?

Chrome 71.0.3578 on MacOS 10.13.6

## Which AMP version is affected?

Version 1812102014220

**Comment by torch2424** [comment]
Triaging to @aghassemi 😄

**Comment by aghassemi** [comment]
This is somewhat working as intended. For a11y, we need move the focus back to the element that opened the sidebar but the use-case here is valid as well so we should think of a way to keep both a11y benefits and handle the use-case here.
