### ISSUE TITLE
Amp-story: how to remove a text with animation

### ISSUE THREAD

**Issue by spinmar** [ampproject/amphtml#19868]
Hi,
I'm implementing various amp-stories and it is not clear to me how to remove a text in apage with animation. 
Supposing to have a story with different pages and in each page the text enters with animation fade-in. I'd like to remove this text after X seconds because the user should be able to view the undergroud video. 
Can you explain me how to do it?
Thansk

**Comment by newmuis** [comment]
Hi @spinmar, it is not currently possible in the amp-story spec to have exit animations.  This is something we have considered for a future date.  I don't think there is a GitHub issue tracking this, so I will leave this issue open to track.

**Comment by spinmar** [comment]
Hi @newmuis thanks for your reply. Yes it will be very useful bacause there are many examples where it should be useful for the user remove animations.

**Comment by mszylkowski** [comment]
In case anyone else needs to know how to do this, `amp-story-animation` is the story version of [amp-animation](https://amp.dev/documentation/components/amp-animation/) and is configured similarly.
```html
<amp-story-page>
<amp-story-animation layout="nodisplay" trigger="visibility">
  <script type="application/json">
    {
      "selector": ".animate-in-out",
      "duration": "1s",
      "delay": "2s",
      "fill": "both",
      "keyframes": [
        {"transform": "translateY(5em)", "easing": "cubic-bezier(0.2, 0.6, 0.0, 1)"},
        {"transform": "translateY(0em)", "offset": 0.2},
        {"transform": "translateY(0em)", "offset": 0.8, "easing": "cubic-bezier(0.2, 0.6, 0.0, 1)"},
        {"transform": "translateY(5em)"}
      ]
    }
  </script>
</amp-story-animation>
<amp-story-grid-layer>
  <h1 class="animate-in-out">This will enter and exit</h1>
</amp-story-grid-layer>
</amp-story-page>
```
