### ISSUE TITLE
Reading/modifying body prior to page load can be unsafe

### ISSUE THREAD

**Issue by sparhami** [ampproject/amphtml#19876]
Writing to `document.body` prior page load can cause AMP elements to run `buildCallback` prior to their children being available. See: https://github.com/ampproject/amphtml/issues/19728#issuecomment-446033966

Reading from `document.body` could result in some elements being missed. For example, the following code reads from the body looking for all elements matching a selector, but this can run before more elements matching the selector are added to the body due to a streamed response.

https://github.com/ampproject/amphtml/blob/bc4d012a70d5386081b733ce3a5fe7d63f1a7eac/extensions/amp-ad/0.1/amp-ad-custom.js#L214-L226

There are two things to do:

1. Fix existing usages
2. Prevent problematic usage in the future (note: some of the usage is dynamic, e.g. opening sidebar, which could happen for longer documents on slower networks)

@jridgewell Is tackling number 2 be something you would be interested in?

//cc @dvoytenko @aghassemi 

Some places with likely issues (not necessarily a complete list):

* https://github.com/ampproject/amphtml/blob/bc4d012a70d5386081b733ce3a5fe7d63f1a7eac/extensions/amp-ad/0.1/amp-ad-custom.js#L214
* https://github.com/ampproject/amphtml/blob/3736cf537998f81efbbd9606ba7a228fe269f46a/extensions/amp-geo/0.1/amp-geo.js#L339
* https://github.com/ampproject/amphtml/blob/3736cf537998f81efbbd9606ba7a228fe269f46a/extensions/amp-viewer-integration/0.1/highlight-handler.js#L331
  * More generally, there are problems with the init for amp-viewer-integration (which kicks off this work) running before the document has finished loading (e.g. finding the highlight nodes might fail) https://github.com/ampproject/amphtml/blob/3736cf537998f81efbbd9606ba7a228fe269f46a/extensions/amp-viewer-integration/0.1/amp-viewer-integration.js#L247
* https://github.com/ampproject/amphtml/blob/3736cf537998f81efbbd9606ba7a228fe269f46a/extensions/amp-image-lightbox/0.1/amp-image-lightbox.js#L970
* https://github.com/ampproject/amphtml/blob/3736cf537998f81efbbd9606ba7a228fe269f46a/extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js#L1068
* https://github.com/ampproject/amphtml/blob/3736cf537998f81efbbd9606ba7a228fe269f46a/extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js#L1101
* https://github.com/ampproject/amphtml/blob/137a2520a42bdb3a61143fcf7e3e7a3b26d6198b/extensions/amp-sidebar/0.1/amp-sidebar.js#L370
* https://github.com/ampproject/amphtml/blob/137a2520a42bdb3a61143fcf7e3e7a3b26d6198b/extensions/amp-addthis/0.1/addthis-utils/pixel.js#L82
* https://github.com/ampproject/amphtml/blob/137a2520a42bdb3a61143fcf7e3e7a3b26d6198b/extensions/amp-addthis/0.1/addthis-utils/pixel.js#L108
* https://github.com/ampproject/amphtml/blob/137a2520a42bdb3a61143fcf7e3e7a3b26d6198b/extensions/amp-recaptcha-input/0.1/amp-recaptcha-service.js#L188
* https://github.com/ampproject/amphtml/blob/137a2520a42bdb3a61143fcf7e3e7a3b26d6198b/extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js#L994
* https://github.com/ampproject/amphtml/blob/137a2520a42bdb3a61143fcf7e3e7a3b26d6198b/third_party/subscriptions-project/swg.js#L5141
* https://github.com/ampproject/amphtml/blob/137a2520a42bdb3a61143fcf7e3e7a3b26d6198b/third_party/subscriptions-project/swg.js#L5496
* https://github.com/ampproject/amphtml/blob/137a2520a42bdb3a61143fcf7e3e7a3b26d6198b/third_party/subscriptions-project/swg.js#L6058
* https://github.com/ampproject/amphtml/blob/137a2520a42bdb3a61143fcf7e3e7a3b26d6198b/extensions/amp-subscriptions/0.1/dialog.js#L72
* https://github.com/ampproject/amphtml/blob/137a2520a42bdb3a61143fcf7e3e7a3b26d6198b/extensions/amp-font/0.1/fontloader.js#L201
* https://github.com/ampproject/amphtml/blob/137a2520a42bdb3a61143fcf7e3e7a3b26d6198b/extensions/amp-web-push/0.1/iframehost.js#L69
* https://github.com/ampproject/amphtml/blob/137a2520a42bdb3a61143fcf7e3e7a3b26d6198b/extensions/amp-access/0.1/amp-access-iframe.js#L153
* https://github.com/ampproject/amphtml/blob/137a2520a42bdb3a61143fcf7e3e7a3b26d6198b/extensions/amp-form/0.1/validation-bubble.js#L56
* https://github.com/ampproject/amphtml/blob/137a2520a42bdb3a61143fcf7e3e7a3b26d6198b/extensions/amp-access-scroll/0.1/scroll-impl.js#L270
* https://github.com/ampproject/amphtml/blob/137a2520a42bdb3a61143fcf7e3e7a3b26d6198b/extensions/amp-access-scroll/0.1/scroll-impl.js#L294
* https://github.com/ampproject/amphtml/blob/137a2520a42bdb3a61143fcf7e3e7a3b26d6198b/extensions/amp-access-scroll/0.1/scroll-impl.js#L365

**Comment by jpettitt** [comment]
In the `amp-geo` instance the `doc.body.appendChild()` is gated by `waitForBodyPromise()`  should it be waiting for something else?

**Comment by aghassemi** [comment]
@jpettitt `waitForBodyPromise` fires when `body` is `opened` which makes it suffer from this issue. Would need to wait for `DOMReady` instead or insert at the top body instead of end.

**Comment by dvoytenko** [comment]
I think the safest is either to:

1. `ampdoc.whenBodyAvailable()` and insert a node as a first child of body. Though this could break `amp-story` checks I've seen around. A slightly safe option could be to insert a new node as a previous sibling to the current node.
2. `ampdoc.whenReady()` and append at the bottom of the body.

So, as you can see, operating on a body in the middle of parsing is not very easy to do safely. Perhaps we should always require option 2 with some necessary exceptions.

**Comment by sparhami** [comment]
I'm working on a different approach. I plan on creating a new `AmpDoc` method called `appendToBody`, which will immediately append to the body. It will also mark the Node as having appended to the body. I'm also changing the logic that checks for Nodes following in the document order to skip over such nodes.

Appending to the start of the body can have problems. For example, page authors may have a z-index matching an existing modal, and things currently work correctly because the modal element is appended to the end of the body, causing it to stack on top.

Waiting for the AmpDoc to be ready is also not ideal. We should not wait for the body to be fully downloaded before opening a lightbox or a sidebar.

I have a WIP here: https://github.com/ampproject/amphtml/compare/master...sparhami:append-to-body

So I am going with this approach because 1: I don't want to break existing pages and 2. I don't want to have an extra delay on user interaction.

**Comment by dvoytenko** [comment]
@sparhami indeed, marking a node as "ignore for pending search" is a pretty cool idea.

**Comment by aghassemi** [comment]
@sparhami LGTM! could you also add a regex for catching `body.append` usages in presubmit?

**Comment by choumx** [comment]
Good sleuthing, thanks for fixing this.

**Comment by jridgewell** [comment]
This applies to much more than body tag, although appending to `document.body` (or `document.documentElement`, *ahem* `FixedLayer`) is certainly the worst case scenario. We traverse up the tree (starting from the element in question) to see if there's any `nextSibling`.


The only generic solution I can think of is patching `appendChild`, `insertBefore`, and `replaceChild` to _also_ insert 2 comment nodes (a start comment and an end comment). We can think detect these nodes when inspecting nextSiblings, and ignore them.

**Comment by sparhami** [comment]
> This applies to much more than body tag, although appending to document.body (or document.documentElement, ahem FixedLayer) is certainly the worst case scenario. We traverse up the tree (starting from the element in question) to see if there's any nextSibling.

Technically speaking yes, but practically speaking this shouldn't be too much of a problem. If you have an Element that appends to itself ( or a child container, i.e. not the body), it shouldn't break anything inside, since the only time it would have appended to itself is after it had all the children available.

The only time this would be a problem is if there was some piece of code that appended to existing elements that had not been upgraded yet. While this could exist in the codebase or be added in the future, but it is a bit hard for me to imagine what such a piece of code would be doing.

> The only generic solution I can think of is patching appendChild, insertBefore, and replaceChild to also insert 2 comment nodes (a start comment and an end comment). We can think detect these nodes when inspecting nextSiblings, and ignore them.

Seems like you shouldn't need to have a marker, you could simply annotate the DOM node(s) themselves.
