### ISSUE TITLE
AMP HTML Google Ads Display Error

### ISSUE THREAD

**Issue by 4tek** [ampproject/amphtml#19878]
Have you ever seen that kind of error of AMP HTML Google Ads?
It looks good where I uploaded it, it's correctly validated and mostly corectly display but sometimes I see it that way. How to fix it? Ad is made with Google Web Designer. I have this problem with many others AMP HTML ads
![ampaderror](https://user-images.githubusercontent.com/45861062/49971119-a3b59e00-ff2d-11e8-9560-c9b207356f8a.jpg)

**Comment by torch2424** [comment]
Triaging to @jasti 

@jasti Feel free to assign to one of us if it is on our end 😄

**Comment by jasti** [comment]
@4tek thanks for the bug. Could you confirm how you are delivering this? i.e. where are you uploading the ad from? Also, a test URL if you have one would be very helpful.

In the mean time, I've reached out to the GWD team to see make sure it's not a bug on their end.

**Comment by jasti** [comment]
Confirmed that it's a bug on the Google Ads rendering side. Will update this bug once the issue is resolved.

**Comment by 4tek** [comment]
Hi @jasti , 

do you know what is the status of solving this problem?

It still appears :/

**Comment by calebcordry** [comment]
@jasti Any update here?
