### ISSUE TITLE
Importing videojs player via CDN

### ISSUE THREAD

**Issue by rushikeshk-gdb** [ampproject/amphtml#19884]
## What's the issue?

I am trying to import videojs cdn library in my AMP custom component.
I used preconnectCallback method to pass the videojs uri using this.preconnect.url(" ") property.
but it gives me min.js file code as it is on html file. but I need videojs player working in my AMP html page 

## How do we reproduce the issue?
1) create an AMP component 
2) import videojs cdn library in that component
3) Check in html file player will going to work or not

## What browsers are affected?

I am using google chrome browser of version " Version 70.0.3538.102 (Official Build) (64-bit)"

## Which AMP version is affected?

Version 1812130601131

**Comment by torch2424** [comment]
Triaging to @aghassemi 😄 

Just to clarify, are you creating an AMP Extension? Or are you trying use one of the AMP video extensions?

**Comment by aghassemi** [comment]
@rushikeshk-gdb 

If you are trying to use a custom video player in your AMP pages, please take a look at `amp-video-iframe` (https://github.com/ampproject/amphtml/blob/master/extensions/amp-video-iframe/amp-video-iframe.md). It is experimentally available so you can give it a try now but will be generally available in January.

If you are trying to create a component for a video service that is not specified to only your AMP pages and other users can use (e.g. something like `amp-youtube`, `amp-dailymotion`). Then please note that you can not load `videojs` JS file inside the component. It either needs to be iframe-based (e.g. `amp-youtube` or the script has to go inside out 3P iframe (similar to how `amp-ima-video`) works.

**Comment by aghassemi** [comment]
Closing per comment above, please ping us on Slack if you are building a component and need help. Thank you!
