### ISSUE TITLE
Global event handler to report all user interactions to viewer inside AMP

### ISSUE THREAD

**Issue by GoTcWang** [ampproject/amphtml#19886]
We would like to evaluate how awesome AMP4EMAIL is and we believe the strongest argument we can make is "users tend to take more actions in AMP4EMAIL than static emails".

In order to do that, we would appreciate AMP runtime collect all user actions (swipe, click, tap and etc.) and report to viewer so that we can do further analysis.

Even better, these user interactions would be bundled with an AMP component, so that we can say like "users like to interact with amp-carousal more". This information can help us argue further than AMP4EMAIL is awesome (people like interacting with these and these AMP components which can never be done in static emails) and also we can recommend those components to later partners.

Let me know if this is possible to have in runtime.

**Comment by cramforce** [comment]
AMP would not provide such information by default unless the viewer requires it for purposes such UI interactions.

Having said that, in the email case the host could likely either inject JS, or use webview APIs on native, or inject amp-analytics, to transmit such information to the host app.
