### ISSUE TITLE
[Google Tag Manager] AMP Container preview mode, doesnt work through amp-analytics

### ISSUE THREAD

**Issue by SimonHogstromRonbol** [ampproject/amphtml#19883]
## What's the issue?

Google Tagmanager preview mode doesnt show up on AMP pages, using normal tagmanager containers, pressing "preview" lets you then visit the site amd you can see an iframe keeping track of what and how different tags are triggering.

Using an amp container when you enter preview mode and visit your amp website, the preview mode iframe doesnt show up, no console error or anything eigther.

i am using amp canonically and using tagmanager through the amp-analytics component

## How do we reproduce the issue?
go to Google Tag Manager and click the preview button:
![image](https://user-images.githubusercontent.com/32469390/49998260-18bbbe80-ff94-11e8-9b84-f56509f1a22b.png)

afterwards go to the amp page where you are using google tag manager, and there wont be a giant iframe waiting for you with a bunch of useful infomation.

## What browsers are affected?
all of them

## Which AMP version is affected?
any version, this had been an issue atleast since march when i encountered this the first time.

**Comment by torch2424** [comment]
Triaging to @jeffjose 😄 

@jeffjose Feel free to assign one of us if this is an issue on our end 😄

**Comment by benjamingram** [comment]
AMP containers in Google Tag Manager (GTM) do not support the debug window you are referring to. Preview mode will still let you preview your changes prior to publishing. 

For a bit more context, Google Tag Manager AMP containers are built using the functionality provided by amp-analytics. This currently relies on providing configuration, but does not enable injecting script or an iframe into the page that is currently necessary for the debug window.

Feature request, duly noted. :)

**Comment by jeffjose** [comment]
Thanks for chiming in, @benjamingram. Looks like this is working-as-intended considering some of the restrictions AMP puts in place (no 3p javascript). Closing this out, but feel free to reopen @SimonHogstromRonbol if you think otherwise.

**Comment by stephengardner** [comment]
Reopening for the team to look into as AMP now has the potential for <amp-script> and therefore there could be some progress towards a solution.   I'm not saying it should work currently, but this issue can be revisited, no?
