### ISSUE TITLE
In `Viewer` constructor, call `documentStateFor` with `win` param

### ISSUE THREAD

**Issue by britice** [ampproject/amphtml#1989]
Expected behavior would have the `Viewer` get the `DocumentState` from the window object passed as a parameter to the constructor rather that the global window object. Using the expected behavior would potentially allow for more flexibility in testing by mocking the `DocumentState` on the window object passed to the `Viewer`.

See the `Viewer` constructor in [viewer-impl.js](https://github.com/ampproject/amphtml/blob/master/src/service/viewer-impl.js). The specific code is:
```javascript
this.docState_ = documentStateFor(window);
```

**Comment by jridgewell** [comment]
Closed by #2080.
