### ISSUE TITLE
I2I: `seekTo` for video

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#19891]
## Goal

Implement a high-trust `seekTo` action for video.

### API

Mimic the `amp-animation` API:

```
on="tap: myVideo.seekTo(time=, percent=)"
```

Where `time` is specified in seconds and `percent` between `[0, 1]`. Both params are optional but one of them should be set.

#### VideoInterface

Basic boilerplate and implementation for `amp-video` filed in #19893.

#### amp-video

See above.

#### VideoManager action

[`VideoManager#registerCommonActions_`](https://github.com/ampproject/amphtml/blob/master/src/service/video-manager-impl.js#L222) should add `seekTo`. For reference on how the callback can be implemented, see [`amp-animation.js`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-animation/0.1/amp-animation.js#L289).

#### amp-video-iframe

This introduces the concept of method parameters to `amp-video-iframe`. `AmpVideoIframe#method_()` should understand this concept by taking an optional `JsonObject` to be passed along postMessage in the `params` field. `timeSeconds` must be passed as an int, and since this is a `JsonObject` the `video-iframe-integration.js` library should unmarshall them correctly.

In the `video-iframe-integration.js` library, the `method` method (mea culpa for bad naming choices here) takes a `params` field that can be either a `JsonObject` or `null`.

Once this is bootstrapped, `videoJS` and `jwplayer` integrations should be simple executions of `method`. 

#### amp-youtube

The [YouTube JS SDK supports `seekTo`](https://developers.google.com/youtube/iframe_api_reference#seekTo) so we can build off of that.

#### amp-ima-video

(@torch2424 to add details)

#### Feasability with other players

Different players can either support this new method or not. Feasibility of each needs to evaluated and implemented independently. Readers can feel free to chime in for prioritization, but we'll start with `amp-video`, `amp-youtube` and `amp-video-iframe` to support a large surface initially.

## Burn down

- [ ] Add boilerplate for `VideoInterface` method. (@alanorozco, #19893)
- [ ] Implement action from `VideoManager`. (@sanchezedgar)
- [ ] Implement for amp-video (@alanorozco, #19893)
     - [ ] Unit tests
- [ ] Implement for amp-video-iframe (@sanchezedgar)
     - [ ] Unit tests
     - [ ] `postMessage` passthru
     - [ ]  Basic `method()` integration
     - [ ] `videoJS` support (@alanorozco)
     - [ ] `jwplayer` support (@alanorozco)
- [ ] Implement for amp-ima-video (@torch2424)
- [ ] Implement for amp-youtube
- [ ] Integration tests for `test-video-players-helper.js`
- [ ] Add action to manual testbench
- [ ] Check feasibility of:
    - [ ] amp-mowplayer
    - [ ] amp-delight-player
    - [ ] amp-vimeo
    - [ ] amp-ooyala-player
    - [ ] amp-dailymotion
    - [ ] amp-brid-player
    - [ ] amp-brightcove
    - [ ] amp-nexxtv-player
    - [ ] amp-ima-video
    - [ ] amp-powr-player
    - [ ] amp-viqeo-player
    - [ ] amp-3q-player
    - [ ] amp-wistia-player
    - [ ] amp-gfycat

/cc @aghassemi @sanchezedgar

**Comment by alanorozco** [comment]
Hi @sanchezedgar 

I think this is something we can work on together. I've wrote down a basic burndown list and I'll start going with a few tasks :)

**Comment by alanorozco** [comment]
@mister-ben It looks like the Brightcove API supports seeking. Is this something you'd be interested in adding to `amp-brightcove`? There's a `VideoInterface.seekTo` boilerplate PR (#19893) that would make this fairly simple to achieve.

**Comment by alanorozco** [comment]
@sanchezedgar I assigned you a couple of tasks if you'd like to begin work on `amp-video-iframe` support and overall action triggering.

**Comment by torch2424** [comment]
I can handle this for `amp-ima-video`.

@alanorozco Is there alreadya . Design doc / design review done for this?

**Comment by alanorozco** [comment]
@torch2424 No design doc needed, this issue should serve the same purpose.

There's not a lot to review but the API, and I think that's fairly uncontroversial. If you'd like to present it next week, feel free, but I'm out until Jan :( Let's discuss design here in the meantime.

**Comment by torch2424** [comment]
@alanorozco Sounds good! Since `amp-ima-video` is essentially a custom player, we communicate with it using iframe `postMessage`. Thus I'll just create a new message type, with a value we should scroll to 😄 

Let's try to coordinate implementing around the same time, that way videos on AMP stay consistent. I'm in no rush to implement this, and we can wait until you get back. Unless someone feels otherwise.
