### ISSUE TITLE
AMP Dashboard / app-index: Allow fuzzy-finding the entire file tree

### ISSUE THREAD

**Issue by torch2424** [ampproject/amphtml#19899]
realtes to #19676

After offline discussion, would be awesome to have a button that can pull up a little modal (OSX Spotlight type thing), to allow fuzzy finding the entire amp file tree for example and things, without having to go to the the actual folder page for the file listing.

**Comment by rsimha** [comment]
@alanorozco Bumping another old issue to ask if it's still relevant.

**Comment by rsimha** [comment]
_[Infra triage]_ Closing this issue as stale. Please reopen if required.
