### ISSUE TITLE
Component for quicklink

### ISSUE THREAD

**Issue by JosefJezek** [ampproject/amphtml#19905]
Could you create component for quicklink?

https://github.com/GoogleChromeLabs/quicklink

**Comment by aghassemi** [comment]
Thanks @JosefJezek. We have started designing for a holistic seamless page transition experience in AMP which would also include the logic of prefetching (and prerendering since AMP can do that). 

Please follow https://github.com/ampproject/amphtml/issues/12981 for updates.

If it turns out that separating page transitions and prefetching into different components makes sense, you may do that as well. For now I am putting this feature request under the same category.

**Comment by westonruter** [comment]
@aghassemi I think this closely relates to amp-sw's link-prefetch module. In fact, I think that Quicklink would provide a better developer and user experience than the current prefetching which is done manually by the developer adding attributes to links: https://github.com/ampproject/amp-sw/issues/15.

**Comment by westonruter** [comment]
Consider an `amp-link-prefetch` component, taking Quicklink's [configuration object](https://github.com/GoogleChromeLabs/quicklink#api) which we've adapted into JSON format for the [wp-quicklink](https://github.com/luehrsenheinrich/wp-quicklink/) plugin:

```html
<amp-link-prefetch>
    <script type=application/json>
        {
            "el": "main",
            "urls": [],
            "timeout": 2000,
            "timeoutFn": "requestIdleCallback",
            "priority": false,
            "origins": [
                "wordpress.example.com"
            ],
            "ignores": [
                "feed=",
                "/feed/",
                "^https?://[^/]+/(#.*)?$",
                "^https://wordpress.example.com/wp-admin/",
                "^https://wordpress.example.com/[^?#]+.php",
                "^https://wordpress.example.com/wp-content/"
            ]
        }
    </script>
</amp-link-prefetch>
```

**Comment by aghassemi** [comment]
I think this fits the `One-line PWA` [project](https://github.com/ampproject/amphtml/issues/16589) fairly well. The configuration may fit better as part of whole configuration needed to auto-PWA a page, so the explicit `amp-link-prefetch` may not be needed and rather it may be a section in a 
```
<amp-pwa-config>
      <script type=application/json>
        { prefech: {
            "el": "main",
            "urls": [],
            "timeout": 2000,
            "timeoutFn": "requestIdleCallback",
            "priority": false,
            "origins": [
                "wordpress.example.com"
            ],
            "ignores": [
                "feed=",
                "/feed/",
                "^https?://[^/]+/(#.*)?$",
                "^https://wordpress.example.com/wp-admin/",
                "^https://wordpress.example.com/[^?#]+.php",
                "^https://wordpress.example.com/wp-content/"
            ]
        }}
    </script>
</amp-pwa-confing>
```

/to @kristoferbaxter 
/cc @prateekbh

**Comment by kristoferbaxter** [comment]
We're discussing this issue here: https://github.com/ampproject/amp-sw/issues/15.

Prefetching is important, but how we do so should be decided before attempting to port `quicklink` to an AMP component. Let's use the linked issue to figure out the best course forward.

**Comment by samouri** [comment]
Closing since AFAIK we don't plan on staffing an effort to implement a quicklink component
