### ISSUE TITLE
Add examples of usage of extraUrlParams and extraUrlParamsReplaceMap

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#1991]
This issue is tracking adding an example to show usage of `extraUrlParams` and `extraUrlParamsReplaceMap` in https://github.com/ampproject/amphtml/blob/master/examples/analytics.amp.html

**Comment by Meggin** [comment]
FYI, I added an example code snippet for extraUrlParams in new analytics docs: https://www.ampproject.org/docs/guides/analytics/deep_dive_analytics.html#appending-request-url-extra-url-params

**Comment by rudygalfi** [comment]
Should be covered by #2269.
