### ISSUE TITLE
useBody attribute in AMP-ANALYTICS not working

### ISSUE THREAD

**Issue by oliverfernandez** [ampproject/amphtml#19919]
## What's the issue?

I'm trying to use the new feature `useBody` from `AMP-ANALYTICS` to send data in the body of a `POST` request. However, I'm unable to make it work, as AMP keeps adding the payload as a query string.

## How do we reproduce the issue?

Here's an example of my `AMP-ANALYTICS` configuration

````
<amp-analytics>
    <script type="application/json">
      {
        "requests": {
          "marfeelAMPPageview": "https://cosmos.marfeel.com/varys/event"
        },
        "triggers": {
          "trackMarfeelPageview": {
            "on": "visible",
            "request": "marfeelAMPPageview",
            "transport": {
              "beacon": true,
              "image": false,
              "xhrpost": true,
              "useBody": true
            },

            "extraUrlParams": {
              "ds": "marfeel_amp",
              "cg1": "article",
              "referrer": "${externalReferrer}",
              "dh": "${canonicalHostname}",
              "dl": "${canonicalUrl}",
              "dp": "${canonicalPath}",
              "ts": "${timestamp}",
              "cid": "${clientId(mrf-client-id)}",
              "buildNumber": "1234",
              "customBuildNumber": "5678",
              "mdt": "s",
              "ua": "${userAgent}",
              "type": "pageview"
            }
          }
        }
      }
    </script>
  </amp-analytics>
````

And this is what I see in the Dev tools

<img width="570" alt="screenshot 2018-12-10 at 11 17 48" src="https://user-images.githubusercontent.com/1696239/49726008-4b507900-fc6d-11e8-89e7-88f4483664cf.png">

**Comment by calebcordry** [comment]
Hello @oliverfernandez can you try moving the "transport" configuration so that it is one lever higher? It should be at the same depth as "requests" and "triggers. Let us know if that works. Thanks

**Comment by oliverfernandez** [comment]
@calebcordry It was exactly that, I think I got the documentation wrong. Everything works fine

**Comment by calebcordry** [comment]
Glad it works! Thanks for the update!
