### ISSUE TITLE
Google Font loading issue on Safari / iOS devices.

### ISSUE THREAD

**Issue by Salindor** [ampproject/amphtml#19912]
## What's the issue?
Google Font loading issue.

## How do we reproduce the issue?
https://marcel.instapage.eu/382080AMP
The "Lato" font is not displaying correctly on provided URL.
This is interesting but refreshing the page will fix the issue.
The reason why this is happening is the line in `<head>` section:
```
<link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic" media="not-matching" i-amphtml-timeout="43">
```
I mean `media="not-matching"` - the "not-matching" value prevents from loading the font. I have tried two scenarios:
1) when the media value is `screen, print`
2) when the attribute is removed completely

But in both cases it's like browser puts `media="not-matching"` anyways, when you load the page for the first time.

## What browsers are affected?
You can recreate it on an **iOS device only**.

## Which AMP version is affected?
AMP version 1812131718380. I have just noticed the issue so I can't tell you if it was always broken.

**Comment by jpettitt** [comment]
Maybe a cache / timing issue with the webkit engine.  On desktop Safari it fails on the initial (cold cache) page load but works on a reload.

**Comment by sparhami** [comment]
Did some investigation and here is what I found:

* The `load` event/`onload` fires in Safari when a non-matching media query is used (as expected)
* The stylesheet for eventually ends up in `document.styleSheets`
* The spec states that the a stylesheet object should be created and then a load even should be fired on the link object:
https://html.spec.whatwg.org/multipage/links.html#link-type-stylesheet:fetch-and-process-the-linked-resource
* This appears to be a race condition, it seems like the sheet may not be in `document.styleSheets`, but the load event may have already fired
  - I have had experience with Safari in the past where things are cached and may be stale, it is possible that `document.styleSheets` may be stale when we look at it

**Comment by sparhami** [comment]
I have a feeling that this may be related to https://bugs.webkit.org/show_bug.cgi?id=83719 or a similar sort of bug.

**Comment by choumx** [comment]
@Salindor Looks like this might just be a browser bug. Have you tried using `@font-face` directly as a possible workaround?
