### ISSUE TITLE
AMP Story "expand your window" message is misleading for desktop users

### ISSUE THREAD

**Issue by eagerterrier** [ampproject/amphtml#19950]
## What's the issue?

We (the BBC) had a complaint from a user for AMP Stories, who encountered the "expand your window" message.

![30siljd](https://user-images.githubusercontent.com/91352/50156330-73238a80-02c6-11e9-8258-0f06b12e4aa3.jpg)

They, quite rightly to my mind, tried to expand their window width-ways and the message did not disappear even when they were at the full width of their screen.

The message should really say "expand the height of your browser window", as this is what is required - a more portrait aspect ratio.

## How do we reproduce the issue?

Message from the user read as follows..

> I click at the last link at https://www.bbc.com/news/science-environment-46582265
> and it directs me to https://www.bbc.co.uk/news/ampstories/climatesteps/index.html
> where I find just this web page with no further information or other effects
> http://oi63.tinypic.com/30siljd.jpg

If you resize your browser window to be full width, but only, say, 50% height, you will see the same message. Their browser window was not quite high enough (excluding the browser and OS furniture) to engage with the content. 

A more helpful message would be appreciated by those desktop users who have not experienced AMP stories before

## What browsers are affected?

Desktop browsers

## Which AMP version is affected?

All

**Comment by vinaymahag** [comment]
@newmuis @gmajoulet , can we change the text to "Expand the height of your window to view this experience"? Thanks.

**Comment by gmajoulet** [comment]
This message appears if your screen is big enough to trigger the desktop version, but has either a height under 550px, or a width under 1024px, meaning it could be either because of the width, or the height.
Maybe we could detect if the message is displayed because of the screen's width or height, and update the message accordingly?

**Comment by vinaymahag** [comment]
@gmajoulet , that makes sense. This means we'd have 3 different messages:

1. Expand the height of your window to view this experience.
2. Expand the width of your window to view this experience.
3. Expand both the height and width of your window to view this experience.

**Comment by kul3r4** [comment]
@gmajoulet What the progress on this?

**Comment by gmajoulet** [comment]
We're about to put a lot more effort into our desktop experience in the next few weeks, we'll try to prioritize this one as part of the desktop experience improvements. Is this blocking or urgent for your use cases?

**Comment by kul3r4** [comment]
@eagerterrier could you add more details?

**Comment by eagerterrier** [comment]
> Is this blocking or urgent for your use cases?

Well these come from (angry) messages from our (confused?) users.

We are not stopping production of AMP Stories due to this, but we do have to field the questions when they come in.

Even a text change to say "or try changing your window to portrait aspect ratio" might work.

Our users believe this to be a BBC product and don't understand we have no control over the messages on screen...

**Comment by newmuis** [comment]
Sounds good to update the messaging, although we will need to get this re-translated into other languages

**Comment by kul3r4** [comment]
@newmuis is there a tracking issue to track progress on this on github?

**Comment by newmuis** [comment]
Sorry for the delays here, I've been out for the majority of the past few weeks.  This is the best issue to track the progress.

@vinaymahag can you help come up with a new string here and work with @gmajoulet or @enriqe to get it implemented?  Once we add the new string, we should file an issue to retranslate that string into other languages.

**Comment by vinaymahag** [comment]
Do these strings work?

* Expand the height of your window to view this experience.
* Expand the width of your window to view this experience.
* Expand both the height and width of your window to view this experience.

**Comment by gmajoulet** [comment]
Thanks Vinay :)
I just sent a PR that's using these.

**Comment by newmuis** [comment]
Thanks for following up @kul3r4!  The new strings have been submitted for English, and should be live within the next 1-2 weeks, as this change propagates to production.
