### ISSUE TITLE
Auto-ads are not working "Unable to fulfill ad strategy"

### ISSUE THREAD

**Issue by pavelgubarev** [ampproject/amphtml#19952]
I have the issue with AMP pages on my website. Adsense auto-ads are not showing at all. For instance https://onethree.ru/zdorovye/vetryanka-u-detej/amp

The auto-ads code is placed properly.

In console I have the messages 

```
log.js:187 No anchor element found
log.js:187 unable to fulfill ad strategy

```
Is is possible that the problem is not on my side? How can I debug the issue?

Thanks!

**Comment by lannka** [comment]
Looks like an empty ad is returned. @keithwrightbos any thoughts for further debugging?

<img width="1067" alt="screen shot 2018-12-18 at 11 00 09 am" src="https://user-images.githubusercontent.com/8496897/50176410-220a9b00-02b4-11e9-9f06-c8473cccebb1.png">

**Comment by lannka** [comment]
I saw ads loaded on my end. Was it a config error you've already fixed? (similar to #17623)

![Uploading Screen Shot 2018-12-19 at 2.05.51 PM.png…]()

**Comment by pavelgubarev** [comment]
> I saw ads loaded on my end. Was it a config error you've already fixed? (similar to #17623)
> 
> <img alt="screen shot 2018-12-19 at 2 05 51 pm" width="1079" src="https://user-images.githubusercontent.com/8496897/50251029-6884f600-0397-11e9-8eda-2e1507fd9149.png">
No. I have added 2 regular codes to avoid losing money. Auto-ads code still produces an error.

**Comment by pavelgubarev** [comment]
Could anybody be so kind to explain what config everybody mentions? I don't see any configs for auto-ads. It's just 2 pieces of code on my side and "ON" button in Adsense panel.
Thank you.

**Comment by tryazi** [comment]
I have this problem. I'm wasting my time on this problem

**Comment by tryazi** [comment]
![adss](https://user-images.githubusercontent.com/45657726/50333067-2386ce00-0515-11e9-8629-c9c54645c402.png)

an ad looks. But I'm not sure it's automatic

**Comment by pavelgubarev** [comment]
Thanks, tryazi. You are right. There is an ad. I just never noticed it, because I expected auto-ads to be put after every 2-3 paragraphs of text like it does on my other sites.

So I guess it is an issue of Adsense algorithms and does not belong here...

**Comment by minificadortt** [comment]
> I have the issue with AMP pages on my website. Adsense auto-ads are not showing at all. For instance https://onethree.ru/zdorovye/vetryanka-u-detej/amp
> 
> The auto-ads code is placed properly.
> 
> In console I have the messages
> 
> ```
> log.js:187 No anchor element found
> log.js:187 unable to fulfill ad strategy
> ```
> Is is possible that the problem is not on my side? How can I debug the issue?
> 
> Thanks!

How do yo resolve the problem, I hava the same problem and I do not what to do. Can you help me? Please. My website is [decumpleanos.com](url)

**Comment by pavelgubarev** [comment]
minificadortt, apparently this problem has no technical 'solution'. If auto-ads are not placed often enough for you, you just place them manually.

**Comment by jkdcdlly** [comment]
How do you resolve the problem, I have the same problem . Can you help me ?
Please.

**Comment by tryazi** [comment]
> How do you resolve the problem, I have the same problem . Can you help me ?
> Please.

add regular ads. it is seen in automatic advertisements over time. Interesting automatic ad code is not even attached
