### ISSUE TITLE
Faulty boolean logic in ALP

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#19958]
https://github.com/ampproject/amphtml/blob/master/src/impression.js#L98

This boolean logic makes no sense. I think these are supposed to be `||`s.

**Comment by jridgewell** [comment]
The code you've written performs ALP in all cases, except for when: `isTrustedViewer` is false, `isTrustedReferrer` is false, and we've not enabled ALP experiment:


| isTrustedViewer | isTrustedReferrer | isExperimentOn(ALP) | perform ALP |
|-----------------|-------------------|---------------------|-------------|
| false           | false             | false               | no          |
| false           | false             | true                | yes         |
| false           | true              | false               | yes         |
| false           | true              | true                | yes         |
| true            | false             | false               | yes         |
| true            | false             | true                | yes         |
| true            | true              | false               | yes         |
| true            | true              | true                | yes         |

**Comment by jridgewell** [comment]
```js
for (const isTrustedViewer of [false, true]) {
    for (const isTrustedReferrer of [false, true]) {
        for (const isExperimentOn of [false, true]) {
            console.log({isTrustedViewer, isTrustedReferrer, isExperimentOn, result: !isTrustedViewer && !isTrustedReferrer && !isExperimentOn})
        }
    }
}
```

**Comment by zhouyx** [comment]
> The code you've written performs ALP in all cases, except for when: isTrustedViewer is false, isTrustedReferrer is false, and we've not enabled ALP experiment:

That's exactly what I am expecting.

**Comment by zhouyx** [comment]
Talked offline The code is expected to run in trusted viewer OR trusted referer OR when it is enabled. 

I'll update the comment to make more clear.
