### ISSUE TITLE
CLIENT_ID(scope) returns strings not prefixed with amp-

### ISSUE THREAD

**Issue by nurse** [ampproject/amphtml#19978]
## What's the issue?

The description about `CLIENT_ID` in AMP HTML URL Variable Substitutions says "These cookies will always have the prefix "amp-" followed by a random base64 encoded string."
https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#client-id

But actually as its `example value` insists, it may return non prefixed strings by Google's AMP Viewer and it seems generated from saved cid in local storage.

I think the behavior is expected one. Therefore the document should be fixed.

Thanks,

**Comment by torch2424** [comment]
Triaging to @jridgewell , Feel free to re-assign 😄

**Comment by jridgewell** [comment]
I think this goes to @lannka, I've got nothing to do with `CLIENT_ID`.

**Comment by lannka** [comment]
@nurse thanks for reporting.

literally it's actually still true that the cookies will always have the `amp-` prefix, because Viewer generated CLIENT_ID are never persisted to cookie.

**Comment by nurse** [comment]
Indeed.. Thank you for comment! I understand it!
