### ISSUE TITLE
Ability to Set Calendar Picker's State Through Binding

### ISSUE THREAD

**Issue by belobrad** [ampproject/amphtml#19982]
## Describe the new feature or change to an existing feature you'd like to see

Ability to set the calendar picker's initial state through binding. It would be great to be able to set the `amp-date-picker` state by using `amp-bind` and a parameter, specifically the month displayed after show action. 

We are using this in a use case where two separate calendars are used to set the date range which must meet certain criteria such as min days, max days etc. When user selects a date from the first calendar we set the allowed dates in the second calendar via binding, then close the first calendar and show user the second calendar in order for them to select the second date of the range. If, however, the first date is couple months in the future , when opening the second calendar the user is presented with a calendar in an initial state that requires them to scroll again in order to select a date that is after the first date. If would be great if we can define the initial state of the second calendar to the desired month via binding before it is opened.

Ideally there would be day parameter we can set to a specific date (something like `scroll-to-date`) via binding parameter and the calendar picker would be scrolled to the matching view making the given date visible without scrolling.

## Describe alternatives you've considered

Date range picker is a great alternative, however some users prefer the UX of having two separate calendars (especially when different supporting day-specific information needs to be presented when selecting either one of the dates.)

## Additional context

This is used for a travel website where users are selecting checkin and checkout dates through two separate calendars. The first calendar needs to show the range of available checkin date and potential surcharges; the second calendar needs to display available checkout dates based on the selected checkin date.

**Comment by cvializ** [comment]
Thanks for the feature request! We'll prioritize this for work soon and update this issue when any changes are made.

**Comment by belobrad** [comment]
@cvializ we would like to contribute to the AMP project and perhaps develop a travel-industry specific date picker which would address all of these FR we have sent over the past couple of weeks and shorten the release schedule for our amp application we are building here.

Do you think there is a need/demand for such component?

Also, if you had to estimate, how would you see the timeframe after the development is finished? i.e. if we develop the component how soon can we start using it in production? (We obviously want to get our application up and running as soon as possible here.)

Thank you.

**Comment by cvializ** [comment]
Hi @belobrad sorry for not updating this thread. We allow setting the amp-date-picker state through the `[src]` binding now, as implemented by https://github.com/ampproject/amphtml/pull/20199. Does that meet your needs?

For developing a new component, the time frame would depend on how long development and review take, and then our release process takes about two weeks once the code is merged.

/cc @aghassemi to discuss priority and demand?

**Comment by belobrad** [comment]
No worries--I'm still waiting for the client to make a decision on how to proceed on this.

**Comment by belobrad** [comment]
Using [src] binding would require a round-trip data to the server and back to update the 2nd calendar, right? i.e. we have 2 calendars and need to update the startDate parameter in the 2nd calendar based on the value selected in the first calendar (each calendar is in it's own lightbox and they open independently.) Is there a way to do this within the amp page itself?

**Comment by cvializ** [comment]
amp-list allows binding amp-bind state objects using its `[src]` attribute, but amp-date-picker does not support this yet, so yes a round trip would be needed for now. This issue can remain open to track that feature request
