### ISSUE TITLE
Errors when running integration tests on unstable browsers are failing builds

### ISSUE THREAD

**Issue by estherkim** [ampproject/amphtml#19980]
Failures when testing on Chrome Beta should not fail the build, but only print warnings.

Here are some builds that fail due to errors on Chrome Beta -
https://travis-ci.org/ampproject/amphtml/jobs/469689459
https://travis-ci.org/ampproject/amphtml/jobs/469680513

cc/ @rsimha @danielrozenberg

**Comment by rsimha** [comment]
Agree. The logic that fails tests when Karma detects zero tests is here:

https://github.com/ampproject/amphtml/blob/73e9f99c900c05bc2402e88da6df2c0bbe2a44f0/build-system/tasks/runtime-test.js#L680-L688

This could be made browser aware.

**Comment by estherkim** [comment]
Closed because beta browsers are nonblocking on Travis.
