### ISSUE TITLE
AMP Cache Pages are staying stale for a long time

### ISSUE THREAD

**Issue by nickmoline** [ampproject/amphtml#19988]
## What's the issue?

Google's AMP Cache (cdn.ampproject.org) is not refreshing cache reliably on our pages on https://www.justia.com/lawyers.  Pages are cached well beyond (in some cases for weeks) even with multiple attempts to use the update-cache mechanism and multiple requests to the page.

We noticed this issue yesterday and when doing investigation (including [discussing on slack](https://amphtml.slack.com/archives/C4X1MDCCW/p1545163616006900) with @jpettitt) some urls will eventually get recached, but other urls do not.   So far of dozens of pages that we noticed were stale, we’ve only seen 4 of them eventually get recached.

When viewing the amp cache urls for the pages, the `Last-Modified:` header shows a clear indication of when the page was cached.  Our pages are updated frequently and it is important that our changes can actually be seen by visitors.

## How do we reproduce the issue?

Here is a small sampling of urls at the time of this posting have outdated content on the AMP Cache (we have tons):

- https://www-justia-com.cdn.ampproject.org/c/s/www.justia.com/lawyers/dui-dwi/new-york/madison-county?amp
	- HTTP Header shows: Wed, 05 Dec 2018 14:45:24 GMT

- https://www-justia-com.cdn.ampproject.org/c/s/www.justia.com/lawyers/dui-dwi/michigan/sterling-heights?amp
	- HTTP Header shows: Fri, 14 Dec 2018 22:43:05 GMT

- https://www-justia-com.cdn.ampproject.org/c/s/www.justia.com/lawyers/dui-dwi/michigan/southfield?amp
	- HTTP Header shows: Sat, 15 Dec 2018 16:28:13 GMT

- https://www-justia-com.cdn.ampproject.org/c/s/www.justia.com/lawyers/dui-dwi/michigan/lake-orion?amp
	- HTTP Header shows: Wed, 12 Dec 2018 05:30:03 GMT

- https://www-justia-com.cdn.ampproject.org/c/s/www.justia.com/lawyers/dui-dwi/michigan/farmington?amp
	- HTTP Header shows: Mon, 17 Dec 2018 11:43:23 GMT

- https://www-justia-com.cdn.ampproject.org/c/s/www.justia.com/lawyers/dui-dwi/michigan/waterford?amp
	- HTTP Header shows: Fri, 07 Dec 2018 22:57:32 GMT

## What we've tried to resolve (to no avail)

- Deprecated update-ping method
- Newer update-cache method
- Enforcing a `Cache-Control: max-age=30` header to indicate that our pages need to expire quickly
- Attempting to use Google Search Console's Fetch as Google feature on both the source html page and the amp url in hopes to force the page getting recached

## Other Notes:

- AMP Pages are properly validating
- @jpettitt on slack suggested that we may be hitting a rate limit based on our crawl rate at google.  We checked our crawl rate was 2.7/sec in GSC which Googlebot + Google-AMPHTML was not exceeding that rate.  In hopes that it might help, we've increased the crawl rate in GSC to the maximum available (10/sec)

## What browsers are affected?

All browsers

**Comment by nickmoline** [comment]
Hello,

Just an update here.  At approximately 10:30 PST (06:30 UTC) last night, we discovered that several of the pages (including the ones here) suddenly updated.  Upon further investigation it seems that the behavior has changed and we are now getting the expected behavior of AMP.  We visit a page, and check a couple minutes later and see that the timestamp has updated to sometime between the time we visited and the current time).  At the moment, things appear to be working normally again, but this problem did exist and the dates we gave above were accurate as of the time we posted.

We are not certain at this time what fixed our problem (but we are certainly glad it is fixed).

As I mentioned in our original ticket, we submitted a request in Google Search Console to increase our crawl rate and it said that request would take a couple days to take effect.  If that is what solved our issue, hopefully the issue won't come back when our crawl rate change expires.

**Comment by jgluk** [comment]
I'm glad to see the issue resolved itself. I am also internally tracking this for follow up investigation.
However, maybe we can close this specific issue in the meantime? (Since we have the internal tracking)

**Comment by nickmoline** [comment]
Hi @jgluk 

As the issue is not actively ongoing at this moment, I think that it is fine to close the github issue and rely on your internal tracking, however we would greatly appreciate it if you could let us know if your follow up investigation finds anything, especially if it finds something that we need to be proactively aware of to make sure this doesn't happen again in the future

**Comment by jgluk** [comment]
Yes, we will let you know if there is an action you can take on your side as a result of our investigation.

**Comment by nickmoline** [comment]
Closing in interim per your suggestion, we look forward to finding out what caused this though.
