### ISSUE TITLE
Fix amp-context API for single pass.

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#20002]

**Comment by zhouyx** [comment]
Since we need to treat everything in amp-context API as externs, I don't think it's a good idea to manually add everything to amp.extern.js 
@erwinmombay Do you have any idea on supporting ampcontext API in singlepass.

**Comment by erwinmombay** [comment]
@zhouyx would creating an extern for ampcontext suffice?

**Comment by erwinmombay** [comment]
also @lannka i guess this confirms that ampcontext-v0.js is used?

**Comment by zhouyx** [comment]
@erwinmombay the AmpContext class? Or the ampcontext.js file. 

And there's also `ampcontext-integration.js` Should we need to create another extern for that?

**Comment by lannka** [comment]
@zhouyx is right. it's also used by `f.js` in ads 3p frame

**Comment by erwinmombay** [comment]
@zhouyx it all depends on the compilation unit. an extern for each compilation unit makes sense to me

**Comment by zhouyx** [comment]
Talked to @erwinmombay offline. We are not using singlepass to compile ampcontext.js bundle. Thus the right fix to this would be to pass context object from AMP to ampcontext in JsonObject.
