### ISSUE TITLE
Linter should show global `event` reference as an error

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#20014]
## Describe the new feature or change to an existing feature you'd like to see

Currently the linter / type checker does not complain if a reference to `window.event` is used in a function. This is a common footgun in JavaScript and should be avoided in AMP's code.

## Describe alternatives you've considered

Code review is one way to avoid adding references to `window.event` in code, but it can miss instances.

/cc @erwinmombay

**Comment by erwinmombay** [comment]
would doing https://eslint.org/docs/rules/no-restricted-globals suffice?

**Comment by cvializ** [comment]
Oh cool! That looks like exactly what's needed for this
