### ISSUE TITLE
amp-consent behavior on receiving response in incorrect format

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#20010]
Follow up issue to https://github.com/ampproject/amphtml/pull/19985#discussion_r243130760 Thanks @torch2424 for the summary. 

cc @lannka @jasti 

This issue is to discuss: When an incoming pose message from iframe is received, what should be the expected behavior. 

#### Real Example ####
Stored consent information {state: accept, value: 'test'}, Message from cmp iframe {state: reject}. In this case, it is most likely that the value is not provided and there's an error.

#### Throw Error Options #### 
Option 1: Not throw error, or only print console error. 

Option 2: Throw user error. The drawback is that these errors are not strictly user error.

Option 3: Send error message to iframe. (There will be race condition because we will also need to unload iframe on receiving message)

#### Fallback Consent State Options ####
Option 1: Respect the incoming invalid message. Override previously stored value. In this example, set stored state to reject, and erase the value 'test'. (Personally I believe this is safe for AMP to strictly follow what is provided by the CMP) 

Option 2: Respect only the valid part of the incoming message. In this example, set stored state to reject, but keep the value=test. 

Option 3: Ignore the incoming message. In this example, the value will still be state=accept, value=test. 

Option 4: Delete everything and assume no consent has been gathered.

**Comment by jasti** [comment]
@zhouyx  As the AMP runtime, I don't think we are in a position to determine if a value is indeed an error. 
My recommendation is Option1: Print console error/ warning and Option1: Respect incoming message and override existing state. 

Let me know if I'm not thinking of any edge cases.

**Comment by zhouyx** [comment]
@jasti I completely agree. Option 1 is the one that I think it's the best as well. \

@lannka I remember that you don't like this option because it could break their use case if an invalid message is received. Could you let us know what is your concern?

**Comment by zhouyx** [comment]
What @jasti and I are trying to prevent is for AMP to stand in the position to determine if the value is an error or not.  But assuming an incoming message is invalid is making assumption itself.
