### ISSUE TITLE
Separate Width and Height  day-size Parameters for Calendar Picker

### ISSUE THREAD

**Issue by belobrad** [ampproject/amphtml#20020]
## Describe the new feature or change to an existing feature you'd like to see

It would be great to be able to specify calendar cell's `day-size` width and height parameters for the `amp-date-picker` separately thus allowing for additional information to be displayed properly underneath the day number text. The current setup results always in a square cell--having a rectangular shape would provide additional room. Perhaps keeping the `day-size` parameter and adding `day-size-height`?

## Describe alternatives you've considered

Smaller font

## Additional context

Current view:
![screen shot 2018-12-20 at 12 40 35 pm](https://user-images.githubusercontent.com/9619113/50309807-0ab6e380-0455-11e9-9210-cd7ad779e780.png)

Desired view:
![screen shot 2018-12-20 at 12 43 54 pm](https://user-images.githubusercontent.com/9619113/50309810-0db1d400-0455-11e9-8db3-7f5aeaede261.png)

**Comment by cvializ** [comment]
Hi @belobrad thanks for telling us about your use-case for this feature. Currently the `day-size` attribute is passed through to `react-dates` `daySize` prop. They don't currently support non-square cell sizes, so there's no existing solution in the component for your feature. We can put effort toward it when it's possible after addressing higher-priority issues. For now, consider using padding in CSS to change the cell dimensions.

**Comment by belobrad** [comment]
Yes please--if you could eventually add it that would be much appreciated.

The problem with the CSS approach is that the `react-dates` script seem to be rendering all table-cells inlined with CSS code specifying the cell height which cannot be modified by the CSS as the inline rule take precedence if I understand this correctly.

![screen shot 2019-01-02 at 12 14 09 pm](https://user-images.githubusercontent.com/9619113/50610506-098baa80-0e88-11e9-880e-86bf73f29abd.png)

Adding padding without modifying the height works fine until some text starts wrapping and then it throws the display out of order:

![screen shot 2019-01-02 at 12 37 06 pm](https://user-images.githubusercontent.com/9619113/50611414-237abc80-0e8b-11e9-9d10-c0a3984db684.png)

Works fine as a temporary solution (and I understand most people will never use something like this) but having height param would be much cleaner I think.

**Comment by belobrad** [comment]
> We can put effort toward it when it's possible after addressing higher-priority issues.

It has been couple of months, any update on where this might be on the priority list?
