### ISSUE TITLE
Add ignore-readonly Parameter For The amp-form Component

### ISSUE THREAD

**Issue by belobrad** [ampproject/amphtml#20023]
## Describe the new feature or change to an existing feature you'd like to see

It seems like the only reliable way to prevent touch devices from displaying a soft keyboard when an input field receives focus (i.e. text filed with a datepicker) is to add `readonly` parameter to such field--this, however, prevents the form from including the given field in validation and in tab index. Would it be feasible to introduce an `ignore-readonly` parameter that would negate this behavior and still prevent the touch devices from displaying the keyboard? 

In other words: the field would have both `readonly` and `ignore-readonly` parameters, the first one would get picked by the touch device and would prevent soft keyboard, the second one would make sure the form still considers the filed in validation.

## Describe alternatives you've considered

Marking the field as readonly

Provide a clear and concise description of any alternative solutions or features you've considered.

## Additional context

The use case for this would be when a date picker is added to the text input field. Touch devices would automatically show the input keyboard which is not a desired UX when picking a date from the calendar.

**Comment by aghassemi** [comment]
Hi @belobrad, if the input is not "typeable", there is no need to use an actual `input`, you can open the date picker with a button or link and submit its value using a `hidden input` (and optionally use `amp-bind` to show the selected date in a `div`). 

@cvializ Do we have a sample for such case.

**Comment by cvializ** [comment]
Are you using a `mode="static"` picker or a `mode="overlay"` picker? Overlay pickers should automatically prevent the input from triggering the keyboard. Does that functionality work in your case?

https://github.com/ampproject/amphtml/blob/ea883c254c8f60b0fb2a9c023131082942c5edd1/extensions/amp-date-picker/amp-date-picker.md#L164-L170

@aghassemi I don't believe there is a good example for that use-case. I opened Issue #20112 to track.

**Comment by belobrad** [comment]
We are using `mode="static"` with a full-screen lightbox to achieve full-screen calendar view (we have lot of additional data to display and need full screen view) and also to achieve horizontal scrolling between the months (the desired UX behavior was not to scroll vertically.)

Using `mode="overlay"` did not allow us to add the additional info we needed around the datepicker and to to achieve the desired UX behavior. This is our current setup:

![screen shot 2019-01-02 at 11 42 48 am](https://user-images.githubusercontent.com/9619113/50609157-c4fe1000-0e83-11e9-9c1d-2ee0262e300a.png)

Could we somehow add the `readonly` behavior also to this scenario, as an optional parameter perhaps?

**Comment by cvializ** [comment]
I think adding an additional parameter to apply validation behavior to input elements with the `readonly` violates the HTML5 spec. Because of that, I don't think AMP should implement it because AMP intends to conform to the standard spec.

Until we find a better solution for when to show mobile keyboards, amp-form custom validation can fill the gaps in the standard validation.

https://ampb.in/#oOHgL62UMwZTd5gFYBYy

```html
<amp-state id="dateValue">
    <script type="application/json">""</script>
  </amp-state>
  <amp-state id="result">
    <script type="application/json">null</script>
  </amp-state>
  <form
    method="get"
    action="https://httpbin.org/response-headers?AMP-Access-Control-Allow-Source-Origin=https%3A%2F%2Fampb.in&access-control-expose-headers=AMP-Access-Control-Allow-Source-Origin"
    action-xhr="https://httpbin.org/response-headers?AMP-Access-Control-Allow-Source-Origin=https%3A%2F%2Fampb.in&access-control-expose-headers=AMP-Access-Control-Allow-Source-Origin"
    target="_blank"
    custom-validation-reporting="show-all-on-submit"
    on="submit-success:message.show, AMP.setState({result: event.response.realdate})"
  >
    <input id="readonlydate" readonly on="tap:lightbox.open" role="button" required pattern=".+" tabindex="0">
    <input id="realdate" name="realdate" [value]="dateValue" required class="hidden">
    <input type="submit" value="Submit">
    <span validation-for="realdate" visible-when-invalid="valueMissing">Please select a date</span>
  </form>
  <button on="tap: picker.clear,AMP.setState({result: ''})">Clear date</button>
  <amp-lightbox layout="nodisplay" id="lightbox">
    <button on="tap: lightbox.close">Close</button>
    <amp-date-picker 
      id="picker"
      layout="fixed-height" height="360"
      input-selector="#readonlydate"
      on="
        activate: lightbox.open;
        select:lightbox.close,AMP.setState({dateValue: event.date});"
    ></amp-date-picker>
    <button on="tap: picker.clear,AMP.setState({dateValue: null})">Clear date</button>
  </amp-lightbox>
  <div id="message" hidden>
    Thank you for submitting. The result is <span [text]="result"></span>
  </div>
```

**Comment by belobrad** [comment]
Got it--thank you!

It would be great if you could eventually implement this functionality though, resources permitting, as I think it would provide more intuitive UX.

We will probably opt for the regular input field and an adjacent calendar icon button setup in order to retain the instant form validation for the time being.
