### ISSUE TITLE
amp-orientation-observer: 3D background image parallax issue

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#20034]
See https://amp-demos.glitch.me/

Two issues:
1- there is a 'jump' when phone goes goes passed the 90, 1800 degrees
2- there is a `jump` at load time. This is because transformation is not relative. There is no way for author to know what the first keyframe would be to apply it in CSS (unlike amp-position-observer) is there is always a change. We may need to provide `relative` events to `amp-position-observer` by making the initial title of the phone at load time to be the base (0) instead of the current state where base is defined by the title degree.

(somewhat related, an amp-fx-collection API for tilt-parallax background would be nice!)
/cc @nainar

**Comment by sebastianbenz** [comment]
Two more things:

1. There's no way to debug amp-orientation-observer, would be great to have a way to log the events.
2. We should add an attribute that'll switch the orientations when the phone switches to landscape mode. You can reproduce with the sample above, the directions are off when the phone is rotated.

P.S. This is the stable URL for the demo: https://amp-demos.glitch.me/parallax.html. The other one might change in the future.

**Comment by wassgha** [comment]
Closed by #24823 and #24606
