### ISSUE TITLE
Element get measured before build

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#20049]
Right now element can get measured before its buildCallback, and use it's previously measured rect after its build complete. 

This could lead to issues, where the element position change or display value change at buildCallback or via its css file. We are currently seeing amp-analytics layoutRect being measured too early before its css load. 

Related code
https://github.com/ampproject/amphtml/blob/master/src/service/resources-impl.js#L1524-L1569
https://github.com/ampproject/amphtml/blob/master/src/service/resource.js#L329-L332

cc @lannka @jridgewell

**Comment by jridgewell** [comment]
I think the core issue lies with the two if statements:

- https://github.com/ampproject/amphtml/blob/master/src/service/resources-impl.js#L1531-L1533
- https://github.com/ampproject/amphtml/blob/master/src/service/resources-impl.js#L1553-L1557

If we're not built, we shouldn't be measuring the element.
