### ISSUE TITLE
Flakes in test-amp-bind.js and test-amp-analytics.js on SL

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#20057]
saw this a couple of times in travis SL:

```
DESCRIBE => amp-bind
  DESCRIBE => + amp-list, amp-mustache:0.2
    DESCRIBE =>  
      IT => evaluate bindings in children
        ✗ Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
Chrome 71.0.3578 (Linux 0.0.0) amp-bind + amp-list, amp-mustache:0.2   evaluate bindings in children FAILED
	Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

e.g.: 
- https://travis-ci.org/ampproject/amphtml/jobs/471150119
- https://travis-ci.org/ampproject/amphtml/jobs/471155956

**Comment by cathyxz** [comment]
I've observed a strange issue with the `<amp-bind>` tests where almost all the timeouts fail because the `this.ww_` promise fails to return in time in this line: 
https://github.com/ampproject/amphtml/blob/master/extensions/amp-bind/0.1/bind-impl.js#L838
Whenever it does this, for whatever reason we're trying load a `browserify.js` file which seems to be the compiled AMP runtime twice. Haven't quite gotten to the bottom of this yet though.

**Comment by lannka** [comment]
Thanks @cathyxz Meantime, I'm adding retries on Saucelabs to work around.

**Comment by lannka** [comment]
Retries seems to give some relief :-) 
15+ greens in a row so far: https://travis-ci.org/ampproject/amphtml/builds

@cathyxz & @choumx do you still want to follow up on the root cause?

**Comment by christian-bromann** [comment]
Is this still an issue you folks are dealing with? I checked the last two weeks of Travis builds and it seems that the flake is now in `test-amp-analytics.js`:

* https://travis-ci.org/github/ampproject/amphtml/jobs/701030575
    * ✗ Timeout waiting for "amp-analytics" to layout
* https://travis-ci.org/github/ampproject/amphtml/jobs/701028244
    * ✗ Timeout waiting for "amp-analytics" to layout
* https://travis-ci.org/github/ampproject/amphtml/jobs/700962370
    * ✗ Timeout waiting for "amp-analytics" to layout
* https://travis-ci.org/github/ampproject/amphtml/jobs/699882553
    * TypeError: Cannot read property 'outputFile' of undefined
    * 2415 at writeOutput (/home/travis/build/ampproject/[secure]/node_modules/karma-structured-json-reporter/index.js:8:14)
    * 2416 at JsonResultReporter.self.onRunComplete (/home/travis/build/ampproject/[secure]/node_modules/karma-structured-json-reporter/index.js:92:5)
* https://travis-ci.org/github/ampproject/amphtml/jobs/697729500
    * [reporter.sauce]: ✖ Browser disconnected

I will check if this is Sauce related or not.

**Comment by choumx** [comment]
The recent timeouts/disconnects appear to be a different source. In my investigation, browser disconnects appear affected by Karma concurrency and long test timeouts. Some more info here: #28925

Closing this issue as obsolete.
