### ISSUE TITLE
AMP Cache triggers reCaptcha Challenge Page

### ISSUE THREAD

**Issue by eveyiyuan** [ampproject/amphtml#20064]
## What's the issue?
When the AMP cache tries to fetch our AMP page, it is receiving the reCaptcha challenge page instead of our AMP page.
@torch2424 Suggested that this might be a cache issue

## How do we reproduce the issue?

1. Visit https://www.google.com/amp/s/www.redfin.com/UT/Park-City/6434-Silver-Lake-Dr-84060/home/71407701/amp (Or search "6434 Silver Lake Dr Redfin")

2. An error page will come up
<img width="280" alt="screen shot 2018-12-21 at 4 22 05 pm" src="https://user-images.githubusercontent.com/6499234/50368349-a2dbc800-053c-11e9-8979-5907adf38bee.png">

3. Click "Debug original page."
(Might need to throttle to slow 3g to click it in time)

4. The mark up in the AMP validator is for the recaptcha challenge page (and thus not valid amp)

## What browsers are affected?

All browsers

## Which AMP version is affected?

Version 1812181822170

**Comment by torch2424** [comment]
cc @Gregable @honeybadgerdontcare Just wanted to check in and was wondering if this is a cache issue?

Though after playing with this myself, the way the Cache works is that we go ahead and crawl AMP pages to be served. Thus, if the page gets crawled by a bot, then you are probably serving the recaptcha to the bot crawling the page. [This explains it much better than I do](https://www.ampproject.org/docs/fundamentals/how_cached). 

And @sebastianbenz actually has a good article on how to allow the AMP crawler to access your pages: https://medium.com/google-developers/how-to-avoid-common-mistakes-when-publishing-accelerated-mobile-pages-9ea61abf530f

Check that out and let me know how it goes. Thanks! 😄

**Comment by honeybadgerdontcare** [comment]
It also looks like the amp page is being redirected to the non-amp page.

https://www.redfin.com/UT/Park-City/6434-Silver-Lake-Dr-84060/home/71407701/amp
redirects to
https://www.redfin.com/UT/Park-City/6434-Silver-Lake-Dr-84060/home/71407701

**Comment by acsant** [comment]
@honeybadgerdontcare We do that when we don't want the users to see an amp page temporarily and see the canonical instead but the google search still has the AMP page indexed

**Comment by acsant** [comment]
@torch2424 So if I understand it correctly, are you saying that the googlebot that crawled the side saw a recaptcha challenge page and that's why the AMP cache is serving that?

**Comment by torch2424** [comment]
@acsant The comment you made to @honeybadgerdontcare we discussed briefly online that the cache would consider a redirection to a non-AMP page, a non-AMP Page. Though, they understand this better than I do, so I may be incorrect.

And the comment to me, yes, that is what it seems like it happening here 😄 Your webserver for serving the AMP page, may realize it's a bot/crawler, and is serving a recaptcha challenge to the AMP crawler, instead of the AMP document.

**Comment by acsant** [comment]
@torch2424 I ran the URL inspection tool from our search console on the canonical's last indexed version and the result came out saying that it has valid AMP html. If the crawler is seeing a recaptcha for the AMP html, then the inspection tools would be reporting it as an invalid AMP html if I understand it correctly?

**Comment by torch2424** [comment]
@acsant Huh that is quite strange, I'll let @honeybadgerdontcare answer that one.

But after investigating, your page does appear to be valid AMP, but it seems like it is just an amp page, that opens an iframe, that redirects to a non-AMP page. Is that your intended behavior? Or is it because I am on a desktop device?

**Comment by torch2424** [comment]
Or better yet, could explain to me your user journey for accessing the site through AMP. And how you expect the journey to be for a bot accessing the AMP site?

**Comment by eveyiyuan** [comment]
@torch2424 We came up with this behavior because we were having issues removing AMP pages from the cache after we unlinked the AMP page from the canonical page. We are running AMP as an experiment right now, so we wanted some kind of "kill-switch" behavior to stop serving AMP pages when we turned off the experiment. The AMP crawler seemed to have been ignoring the 302 we were sending originally when we tried unlinking our AMP page. So, we decided to serve a simple AMP page that redirects a user to the canonical as our kill switch. Ideally, in this case, we would just not show an AMP page at all, but we've run into issues where the crawler fetches the canonical page and thinks it's supposed to be an AMP page.

**Comment by acsant** [comment]
@torch2424 Yes, that is the currently intended behavior. We want to be able to control when a user sees the AMP page vs. the canonical. So often times we will have AMP pages enabled for testing and then we'd decide to disable it temporarily at some point. When we disable it, we would want the users to see the canonical right away. But that wouldn't really happen unless Google re-crawls the page and reindexes the canonical right? So instead we temporarily (until Google re-crawls the page) serve an IFrame that will redirect the users to canonical. 
We also have different states for a page and we have AMP implemented for the first state initially so when a page changes state, we would want to disable AMP such that the user's don't see the stale data and are routed to canonical instead.
The other alternative that we were thinking of was that we return a 404 and force the AMP cache to update using the `update-cache` api. But we didn't want the 404s to hurt the SEO and we weren't sure how it'd impact crawling frequency if we wanted to enable the AMP pages for those markets once again.

**Comment by acsant** [comment]
lol @eveyiyuan beat me to it

**Comment by torch2424** [comment]
Awesome! Thanks for the thorough responses!

I'm not sure if this is an intended high level use case for AMP? Cc @cramforce

**Comment by cramforce** [comment]
CC @sebastianbenz for some insights.

While I understand such kill switches make sense for rollouts, the Search index will always have some latency for some pages.

I'd recommend to run experiments on a subset of pages to minimize risk, and at least avoid needing to do quick back and forth by design (outside of emergencies).

**Comment by torch2424** [comment]
Also, in the meantime while we wait for a response from @sebastianbenz 

Here is a good resource for removing AMP pages: https://developers.google.com/search/docs/guides/remove-amp 

cc @eveyiyuan @acsant

**Comment by acsant** [comment]
@torch2424 We tried having a redirect with 301 or 302 to the canonical. The only downside of doing that is that since the canonical is an invalid AMP HTML, Google will show that blue phone error screen if the AMP page is still indexed

**Comment by cramforce** [comment]
For single-URL-intent-clicks (click not going to a carousel), the error
isn't shown to users. Instead they are redirected to the origin server.

**Comment by acsant** [comment]
@cramforce I'm not sure what you mean by "click not going to a carousel" here. Could you please explain this in a bit more detail and how we could ensure that we follow the correct steps as to not see the error screen? :)  Thanks

**Comment by cramforce** [comment]
If you click a normal search result (not part of a carousel), there should
never be such an error message (in Google, not sure about Bing, Twitter,
etc).

**Comment by acsant** [comment]
@cramforce I don't think there is a carousel for real estate is there? Here's a screenshot of what we were seeing on using a redirect. The error says "missing attribute with the amp lightning symbol" when we redirected to the canonical instead of returning a valid AMP page.

![image](https://user-images.githubusercontent.com/5479907/50852926-c1600280-1335-11e9-8ad4-287402606ff3.png)

**Comment by cramforce** [comment]
@ericfs Is it expected that this is shown to users?

Having said that: The redirect is a fallback not design to be regularly used, of course.

**Comment by acsant** [comment]
@ericfs That's because we added our own valid AMP page there which redirects the users manually to the canonical

**Comment by acsant** [comment]
This one for instance: https://www.google.com/amp/s/www.redfin.com/UT/Millcreek/1161-E-4085-S-84124/home/91760398/amp

**Comment by acsant** [comment]
This is what we're doing to get around the error screen (always serving a valid AMP page instead of ever redirecting):
![amp-gif](https://user-images.githubusercontent.com/5479907/50860763-997b9980-134b-11e9-9d27-d42632b20c1d.gif)

**Comment by acsant** [comment]
In short, the bug still exists. We just have measures placed on our side to ensure that our users don't ever see that "sad phone error screen"

**Comment by ericfs** [comment]
Thanks. I think @cramforce's point is that when Google's AMP Viewer tries to open an invalid AMP document, it is supposed to redirect instead of showing the error pages that are in the screenshot.

Both
https://www.google.com/amp/s/www.redfin.com/UT/Park-City/6434-Silver-Lake-Dr-84060/home/71407701/amp
and
https://www.google.com/amp/s/www.redfin.com/UT/Millcreek/1161-E-4085-S-84124/home/91760398/amp
are valid AMP.

The screenshot you have in step 2) of your original report should not be shown for more than an instant.

I'm trying to reproduce with other invalid pages and so far have not been able to reproduce.

I filed an internal issue: b/122539181

**Comment by acsant** [comment]
@ericfs oh yes, I can confirm that it is only shown for an instant. I had to throttle the network speed down to slow 3G in order to capture that error screenshot lol. But still, we just thought that it was confusing from an end user perspective to be seeing that error screen

**Comment by ericfs** [comment]
Got it, thanks. That is working as intended, then.

**Comment by acsant** [comment]
Out of curiosity, why is that error page shown even for an instant? When I first saw it, it wasn't long enough for me to understand why I was seeing it (it was too fast). Wouldn't it be a smoother experience to just not show it and follow the redirect instead of both? That's just my opinion though

**Comment by ericfs** [comment]
It seems like it may just be legacy reasons. We don't want to slow down the display in the case that the document is not an error, but it should still be possible to avoid showing the error. The internal b/122539181 will track this.

**Comment by ericfs** [comment]
The tracker isn't public, but we can update here.

**Comment by Gregable** [comment]
Since this is an internal product issue, closing here on github.

**Comment by acsant** [comment]
Hello! Any updates on this? Just trying to figure out how this is going to play into our timeline.

**Comment by Gregable** [comment]
The new modified triage process is to leave these open, so reopening.
