### ISSUE TITLE
amp-lightbox-gallery swipes 2 images on left swipe  

### ISSUE THREAD

**Issue by RaFr** [ampproject/amphtml#20068]
## What's the issue?

amp-lightbox-gallery moves 2 images on swipe left. it works fine on right swipe or if it is swiped very slowly. 

## How do we reproduce the issue?

1. open this page https://ampbyexample.com/components/amp-lightbox-gallery/ 
2.  tap on an example on the page to open the lightbox 
3. then swipe left to change the opened image. 

## What browsers are affected?

tested on andoird chrome

## Which AMP version is affected?

amp-version="1812181822170"

**Comment by aghassemi** [comment]
Looks like a `amp-carousel` bug. Might be surfacing in lightbox more often

**Comment by aghassemi** [comment]
fixed by https://github.com/ampproject/amphtml/pull/20336
