### ISSUE TITLE
Elements in the document are overlaid on the lightbox for `amp-lightbox-gallery` when it "fades in"

### ISSUE THREAD

**Issue by acsant** [ampproject/amphtml#20066]
If you have a bug for AMP please fill in the following template.  Delete everything except the headers (including this text).

## What's the issue?
Elements in the HTML with a z-index >= 1 tend to overlay on the lightbox when amp-lightbox-gallery during it's "fade-in" transition to fullscreen

## How do we reproduce the issue?

URL to reproduce it on:
https://www.redfin.com/UT/Spring-City/271-N-Mile-Post-Hwy-89-84662/home/148161515/amp
Note: We're running an experiment so if the URL isn't an AMP page anymore, please let me know and I can provide another

1. Click to open the `amp-lightbox-gallery` in fullscreen

## What browsers are affected?
- Safari
- Chrome is affected if z-index on the elements in question > 1

## Which AMP version is affected?
1812181822170

## Screenshot
<img width="812" alt="screen shot 2018-12-21 at 1 14 20 pm" src="https://user-images.githubusercontent.com/5479907/50369337-fe6c7c80-0561-11e9-9b21-fb65b9f6409e.png">

**Comment by aghassemi** [comment]
@sparhami Same issue as the AMPByExample header going over we chatted about.
