### ISSUE TITLE
Next release 

### ISSUE THREAD

**Issue by dthukral-amazon** [ampproject/amphtml#20071]
My changes were merged 4 days ago (https://github.com/ampproject/amphtml/pull/19986), so I wanted to know when is next release scheduled, when my changes would come in production?

**Comment by aghassemi** [comment]
@dthukral-amazon Next scheduled release will be created on Wednesday, January 2, 2019 (targeting full rollout on January 8)

More info here: https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md
