### ISSUE TITLE
-webkit-text-stroke-color disallowed, but no mention in docs

### ISSUE THREAD

**Issue by stephengardner** [ampproject/amphtml#20092]
`The property '-webkit-text-stroke-color' in attribute 'style' in tag 'span' is disallowed. (see https://www.ampproject.org/docs/guides/author-develop/responsive/style_pages)`

The referenced document doesn't seem to mention the restriction, [here](https://www.ampproject.org/docs/guides/author-develop/responsive/style_pages).

Not sure if it's me that is confused, or the docs that are incomplete.

**Comment by CrystalFaith** [comment]
@cathyxz  - I see this labeled as a bug, should we be supporting `-webkit-text-stroke-color` in inline styles? Or will it always be disallowed?

**Comment by Gregable** [comment]
It's marked on [developer.mozilla.org](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-stroke-color) as:

> This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

However the browser compatibility matrix at the same URL shows broad compatibility, so I don't see any strong reason for AMP to have an opinion on it, and so we should probably allow it, along with `text-fill-color`, `text-stroke-width`, and `text-stroke`.

@stephengardner would you be interested in making a pull request to change this? If not, I can do it, but I thought I'd offer. The file that needs changed is [here](https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii). There are two lists of allowed css properties within style attributes - one for html tags and another for svg tags. Search that file for `text-align-last` to see the two locations. Currently lines 2776 and 5195. The change would simply require adding these new properties to this one file alphabetically.

**Comment by CrystalOnScript** [comment]
@Gregable - any suggestions on what to do with this one?

**Comment by Gregable** [comment]
I'll assume @stephengardner doesn't want to take this one on. We can just fix it in the validator. No need for documentation change.

**Comment by CrystalOnScript** [comment]
Thanks so much @Gregable :)
