### ISSUE TITLE
adsense automatic ads issue

### ISSUE THREAD

**Issue by tryazi** [ampproject/amphtml#20090]
Automatic ads for Amp do not work in any way. I'm using add-in and native. There is no solution to this problem. Required libraries are installed. Many issues have been opened here, but no solution has been produced yet.

example
https://www.odevbul.org/somut-ve-soyut-isim-nedir-konu-anlatim.html (amp page)

**Comment by torch2424** [comment]
cc @keithwrightbos would you happen to know what is happening here? Feel free to re-assign.

**Comment by calebcordry** [comment]
Closing as a stale issue, let me know if this is still a problem.
