### ISSUE TITLE
[amp-list] - set [src] to the root state object

### ISSUE THREAD

**Issue by armandAkop** [ampproject/amphtml#20093]
## Describe the new feature or change to an existing feature you'd like to see

Is there a way to set the [src] value equal to the root amp state object? Something like
```
<amp-list [src]="."></amp-list>
```

## Describe alternatives you've considered

Provide a clear and concise description of any alternative solutions or features you've considered.

**Comment by cathyxz** [comment]
Hi @armandAkop ! Why you want to set it to the root state as opposed to just any other state initialized on the ampdoc?

**Comment by aghassemi** [comment]
amp-state root object would be the `name` used for `amp-state` and that should work.

Please feel free to reopen the issue if that does not work.
