### ISSUE TITLE
ExpectationError: Unexpected call: getScrollHeight()

### ISSUE THREAD

**Issue by e2corporation** [ampproject/amphtml#2009]
After clearing up syntax errors raised by Travis CI, build still failing as of No. 3860.
https://travis-ci.org/ampproject/amphtml/builds/109097694

<img width="1080" alt="screen shot 2016-02-13 at 9 09 57 pm" src="https://cloud.githubusercontent.com/assets/1742233/13031287/5777e94c-d296-11e5-964e-a39e3aad8805.png">

**Comment by cramforce** [comment]
This is because your PR changes `test/functional/test-resources.js`

**Comment by e2corporation** [comment]
So our local code on this branch is causing this test-resources to fail?

**Comment by cramforce** [comment]
It is definitely causing the error in that travis build.

**Comment by e2corporation** [comment]
Thanks, this could have been caused by being outdated from master, I merged in latest changes reverted test-resources.js and I’m getting a passing build starting with 5e726a6
