### ISSUE TITLE
[amp-animation] Add count() CSS extension

### ISSUE THREAD

**Issue by fstanis** [ampproject/amphtml#20097]
## Describe the new feature or change to an existing feature you'd like to see

Add a CSS extension to `amp-animation` called `count()` (or `len()`) that would return the number of targets caught by the selector.

Currently, [this example](https://www.ampproject.org/docs/reference/components/amp-animation#css-index()-extension) is given for `index()` to create a staggered effect when animating something:

```js
{
  "selector": ".class-x",
  "delay": "calc(200ms * index())"
}
```

However, the only way to stagger in reverse order is to hardcode the number of elements (4 in this example):

```js
{
  "selector": ".class-x",
  "delay": "calc(200ms * (4 - index()))"
}
```

## Describe alternatives you've considered

Another option is to instead add something like `rindex()` which returns 0 for the last target, which would also work:

```js
{
  "selector": ".class-x",
  "delay": "calc(200ms * rindex())"
}
```

**Comment by aghassemi** [comment]
Totally, we already have `index`, adding `len` should be simple. @fstanis If you are interested in contributing this, I'd be happy to help.

**Comment by fstanis** [comment]
Sounds good, already explored it a bit in a branch and it seems easy enough.

Any preference on function name? `len()` / `length()` / `count()` / something else?

**Comment by aghassemi** [comment]
let's go with `length()` to match JS
