### ISSUE TITLE
Flex for amp-list amp-mustache to make child heights the same.

### ISSUE THREAD

**Issue by IamAlta** [ampproject/amphtml#20103]
## Describe the new feature or change to an existing feature you'd like to see

Imagine a row of boxes of different heights. They will wrap onto a second, third, etc row.

Use <amp-list><template type="amp-mustache"> where the the inner elements are these boxes.

PROBLEM. When a row has a shorter box, the next row is disrupted and begins after that shorter box on the previous row.

It'd be nice visuals to use flex to make the boxes the same height.
See here for the code, [https://codepen.io/imohkay/pen/gpard?editors=1100#0](https://codepen.io/imohkay/pen/gpard?editors=1100#0)
EQUAL HEIGHT COLUMNS WITH MARGINS IN MULTIPLE ROWS
or
EQUAL HEIGHT COLUMNS WITH MARGINS IN MULTIPLE ROWS and VARIABLE NO OF BOXES

Per the above example at the link, the **parent** must hold display:flex, justify-content: space-between.

But that parent container is created by AMP and I cannot apply the flex CSS.
The parent container is 

`<div role="list" class="i-amphtml-fill-content i-amphtml-replaced-content">`

If I do a test and make that 

`<div role="list" class="i-amphtml-fill-content i-amphtml-replaced-content" style="display: flex;justify-content: space-between;flex-wrap: wrap;">`

with the proper flex-basis CSS in the child container div, then it works.

NOTE: Applying the flex CSS to the wrapper of that parent container does not work.

## Describe alternatives you've considered
Javascript can do this but AMP disallows custom javascript code.

I hope this makes sense. 

Make it a wonderful New Year! You all deserve it!!

**Comment by cathyxz** [comment]
I think you can override those styles with something like `amp-list div[role="list"]` to select the div container inside amp-list (similar to the example [here](http://amp-infinite-scroll.glitch.me/) ).

**Comment by IamAlta** [comment]
I think that will work. Is this explained somewhere in the online AMP Docs? It'd be nice to have it explained in the AMP examples.

Thanks for working on this during a holiday season.

**Comment by cathyxz** [comment]
I think we wanted to avoid getting into this level of detail in the docs, but I think there should definitely be place for things like this somewhere in examples. One thing we sometimes do is to curate codepens and glitch examples which can often be found when you search keyword + codepen. 

@CrystalFaith do you have any thoughts on where examples or documentation like this can go?

**Comment by IamAlta** [comment]
@CrystalFaith 
How about an advanced developers' section? It will definitely grow as AMP does.

**Comment by CrystalFaith** [comment]
Happy new year! 

@IamAlta, thanks for bringing this up! I think something like this might fit in an advanced style guide, depending on how many other style issues seem similar enough. Or as @cathyxz suggested, we could fit it in as a code example for `amp-list`. I'll take a look into it!
