### ISSUE TITLE
Can someone from ampproject.org minify the v0.js script on the ampproject CDN server?

### ISSUE THREAD

**Issue by Patryk-Kawecki** [ampproject/amphtml#20106]
I found that the v0.js script on the ampproject.org CDN server could be minified to reduce its size by 929B (2% reduction). I discovered this testing my website. Here is the GTmetrix report: https://gtmetrix.com/reports/fakesony.co.uk.s3-website.eu-central-1.amazonaws.com/mL7HLCAB. There is also a problem with "Leverage browser caching" of that script and recommendation is "Add Expires headers. There is 1 static component without a far-future expiration date."

**Comment by Patryk-Kawecki** [comment]
2% maybe it's not much, but it lowers the page score. You can download minified v0.js script from GTmetrix report and just update on the amp server. For "Leverage browser caching" You can set the expiration time to 50 minutes, it will be enough to pass page score test and will not affect pages.

**Comment by Patryk-Kawecki** [comment]
> 2% isn't a significant benefit in a faster loading website IMO. And Google never really adheres to those "leverage browser caching" rules, because this project is so fast-moving, if they were to add "the proper" expiry headers or have browsers cache this for too long, if a bug were to roll out, millions of pages are affected for days if not weeks.

2% maybe it's not much, but it lowers the page score. You can download minified v0.js script from GTmetrix report and just update on the amp server. For "Leverage browser caching" You can set the expiration time to 50 minutes, it will be enough to pass page score test and will not affect pages.

**Comment by jpettitt** [comment]
The cache settings for `v0.js` and other AMP js files are intentional. For pages served via the amp cache a versioned js file is substituted and that has a much longer cache lifetime. (`cache-control: public, max-age=31536000`).  

The other thing to keep in mind about cache is that browsers that "double key" the cache (Safari, Firefox) will not share a cached js file between pages from differing origins.
