### ISSUE TITLE
<amp-img> (at least via cdn.ampproject.org) inserts bizarre non-optimal srcset

### ISSUE THREAD

**Issue by DamonHD** [ampproject/amphtml#20104]
This may all simply be a misunderstanding on my part: please educate me if so!

## What's the issue?

The AMP cache (at least for cdn.ampproject.org which I can observe) *deoptimises* image access if presizing has already been done.  A srcset is added that specifies several (fictitious) image versions *all* *larger* than the original.

## How do we reproduce the issue?

For example, in http://amp.earth.org.uk/note-on-survey-results.html the line:

    <a href=http://gallery.hd.org/_c/mechanoids/UK-Millennium-Dome-voting-ticket-credit-card-sized-uniquely-coded-tweaked-1-DHD.jpg.html><amp-img src=http://www.earth.org.uk/img/a/b/UK-Millennium-Dome-voting-ticket-credit-card-sized-uniquely-coded-tweaked-1-DHD.l95176.211x330.jpg layout=intrinsic class=respfloatrsml width=211 height=330 alt="vote/survey" title="vote/survey"></amp-img></a>

gets expanded in the AMP cache in https://amp-earth-org-uk.cdn.ampproject.org/c/amp.earth.org.uk/note-on-survey-results.html to: 

    <a href=http://gallery.hd.org/_c/mechanoids/UK-Millennium-Dome-voting-ticket-credit-card-sized-uniquely-coded-tweaked-1-DHD.jpg.html target=_top><amp-img alt=vote/survey class=respfloatrsml height=330 layout=intrinsic src=https://www-earth-org-uk.cdn.ampproject.org/i/www.earth.org.uk/img/a/b/UK-Millennium-Dome-voting-ticket-credit-card-sized-uniquely-coded-tweaked-1-DHD.l95176.211x330.jpg srcset="https://www-earth-org-uk.cdn.ampproject.org/ii/w220/www.earth.org.uk/img/a/b/UK-Millennium-Dome-voting-ticket-credit-card-sized-uniquely-coded-tweaked-1-DHD.l95176.211x330.jpg 220w, https://www-earth-org-uk.cdn.ampproject.org/ii/w470/www.earth.org.uk/img/a/b/UK-Millennium-Dome-voting-ticket-credit-card-sized-uniquely-coded-tweaked-1-DHD.l95176.211x330.jpg 470w, https://www-earth-org-uk.cdn.ampproject.org/ii/w680/www.earth.org.uk/img/a/b/UK-Millennium-Dome-voting-ticket-credit-card-sized-uniquely-coded-tweaked-1-DHD.l95176.211x330.jpg 680w" title=vote/survey width=211></amp-img></a>

with these entirely spurious srcsrc entries all nominally *larger* than the 211x330 original.

Why?

It's a waste of HTML bytes and processing time at best on the client, and at worst makes for images that are sent larger than necessary and require client CPU memory and time to resize.

## What browsers are affected?

Don't see why this would be especially browser-dependent.

## Which AMP version is affected?

Current as of date of opening ticket.

**Comment by Gregable** [comment]
None of these images are actually larger than the original. The `/ii/w680` is indicating a maximum width, not the actual width. The cache doesn't actually return an image that large, it returns an image of min(original width, indicated width).

You are correct in that in this case, the `srcset` is not actually helping any. All of the images in the srcset are essentially the same. So in theory it's adding bytes to the HTML document and some very minimal CPU for parsing the `srcset` string. That said, I think these are probably not worth worrying much about. The extra bytes in the document are going to get gzip compressed away generally.

The reason for this is that the image and document are cached independently. When the srcset is generated, the cache doesn't know the image dimensions. This is done for a few reasons:

- It's possible that the image could be updated and change dimensions for example. Updating all referencing document when the image changes is possible, but increase cpu costs on the server.
- It also means that in a cold cache cache, the document cannot be returned to the user until the image has been fetched, which slows down delivery of the document. This has a far more significant affect on user experience than the CPU cost of unnecessary srcset parsing.

**Comment by Gregable** [comment]
There is also a comment [here](https://github.com/ampproject/amphtml/issues/19364#issuecomment-439569129) suggesting that what we should really do is have `<amp-img>` generate the srcset in javascript with the precise width that the page requires, rather than a few specific possible widths.

**Comment by DamonHD** [comment]
Thanks for the swift reply.

I think that rather than add more JS, you could take the supplied width as a clue and indeed an upper bound and an exact size in the srcset.  That would probably at least trim some useless entries from the HTML.

Bits of bloat like that add up and so (in part, though this is NOT a very fair comparison) my AMP docs end up being quite a bit larger than the equivalent m-dot doc, compressed or not:

     14400 Dec 31 11:54 note-on-survey-results.html
      5335 Dec 31 12:52 note-on-survey-results.htmlgz
     11535 Dec 31 14:49 m/note-on-survey-results.html
      4534 Dec 31 14:49 m/note-on-survey-results.htmlgz
     13299 Dec 31 13:12 amp/note-on-survey-results.html
      4877 Dec 31 13:37 amp/note-on-survey-results.htmlgz

Thanks again for your time and trouble to explain!

Rgds

Damon

**Comment by Gregable** [comment]
Damon, the width is unfortunately just used by amp to determine a width/height ratio not an actual size, depending on the layout. For example, some publishers will shave a few bytes by writing `<amp-img width=2 height=1 ...>` to specify an image that will end up being shown as 200x100 or so forth. Sadly, in the general case, the cache has no way to know what size the image will eventually be displayed at, even taking into account both the document and the image size.

Your suggestion would work with the `fixed` layout, but not for responsive layouts such as `intrinsic`.

**Comment by DamonHD** [comment]
Hi,

Goodness, I had no idea people did such things, which is presumably why browsers for 'normal' non-AMP HTML cannot use width/height to actually leave space to display.  This is why we can't have nice things!

As I understand it, if I supply a srcset it will be used as-is though?

Can you possibly point me to the reasoning behind the 220/470/680 width split, since I may have a cunning plan!  B^>

Again, thanks for your patience!

Rgds

Damon

**Comment by Gregable** [comment]
Yes, if you supply a srcset, it will be used. So, one workaround would probably be to simply add `srcset=" "` to the tag. Note that a completely empty string will not work, I think. I haven't tested this, but looking at the code I think it would work.

You can see the algorithm for the width selection [here](https://github.com/ampproject/amppackager/blob/bdcd591e2327be58e4a6492582a6f64775819056/transformer/internal/amphtml/srcset.go#L35) which is a golang port of the code running in the cache. The widths were selected as 1.2 multiplier steps starting at 100.

**Comment by DamonHD** [comment]
Thank you!

**Comment by Gregable** [comment]
No problem.

**Comment by DamonHD** [comment]
OK, I like a challenge!

When I next regenerate my AMP pages many of my <amg-img>s will have gained a srcset which will have an entry to target displays down to 360 CSS pixels at 1.5x density, thus ~20% reduced width and maybe ~33% image weight savings...  B^>

Rgds

Damon

**Comment by Gregable** [comment]
Nice! I like it.
