### ISSUE TITLE
Error: No messaging channel: initMessagingChannel

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#20120]
About 6500 errors in canary trailing 7 days. I think this is runtime related, feel free to reassign if not.

```
Error: timeout
at Error (https://raw.githubusercontent.com/ampproject/amphtml/1812261943070/src/log.js:526)
at apply (https://raw.githubusercontent.com/ampproject/amphtml/1812261943070/src/log.js:286)
at (https://raw.githubusercontent.com/ampproject/amphtml/1812261943070/src/service/resources-impl.js:2343)
at cleanupTasks_ (https://raw.githubusercontent.com/ampproject/amphtml/1812261943070/src/service/resources-impl.js:2310)
```

**Comment by rcebulko** [comment]
This error is still occurring, appears to have started back up January 21st

**Comment by Enriqe** [comment]
To add more info, we've had 38k occurrences on the last day.

**Comment by rcebulko** [comment]
Across all releases, this pops up just under 700,000 times a day. Do we have any idea what the source of this is?

**Comment by rcebulko** [comment]
In #23874 , Will mentions the following:

>There are two sources of timeout in that bug: cache-cid-api.js and history-impl.js. This PR makes the former an expected dev error.
>
> I think the latter is due to viewer messaging init timeout but I'm not 100% sure, so changed the message for that timeoutPromise to see what happens.

Since that time, the string he added (`initMessagingChannel`) is the one showing up in the error logs.

**Comment by rcebulko** [comment]
@choumx Does this confirm your theory and, if so, is it safe to mark this as an expected error?

**Comment by choumx** [comment]
Yup, we can mark viewer timeouts as "expected". We still monitor those for spikes right?

**Comment by choumx** [comment]
Maybe related: #18622

**Comment by rcebulko** [comment]
> Yup, we can mark viewer timeouts as "expected". We still monitor those for spikes right?

Yep, they're reported together with standard errors, and we can still watch for spikes

**Comment by omar-dulaimi** [comment]
Hello,
this still occurs:

```
No messaging channel: initMessagingChannel timeout
Uncaught (in promise) Error: No messaging channel: initMessagingChannel timeout
 at gb (log.js:710)
    at ab.f.createError (log.js:359)
    at timer-impl.js:142
    at timer-impl.js:83
```

**Comment by rcebulko** [comment]
Hello @omar-dulaimi ,

This is an expected failure case that can't be avoided in all cases, so this error is reported and logged but does not necessarily indicate anything is broken.

**Comment by omar-dulaimi** [comment]
Thanks for clarifying. Although I've never seen it before until I started implementing amp app banner today. I was thinking that these errors were the reason why I'm unable to see the banner on mobile, even though no validation errors are present.

**Comment by rcebulko** [comment]
Consider reaching out on the [#using-amp](https://amphtml.slack.com/archives/C9HPA6HGB) channel of the AMP Slack!

**Comment by omar-dulaimi** [comment]
Hey @rcebulko 
Unfortunately I don't have a @google email account. Is it possible to get an invitation?

**Comment by Enriqe** [comment]
@omar-dulaimi you don't need a Google account to join the slack channel, you can find the info on how to join at https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#discussion-channels
