### ISSUE TITLE
Add user scroll events `on:scrollUp` and `on:scrollDown`

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amphtml#20125]
## Describe the new feature or change to an existing feature you'd like to see

A way to dispatch events based on the user's scroll direction. This would be great for animations, such as a header that's removed when the user scrolls down and reappears when the user scroll up again. Might be nice to be able to put a range of scrolling: `on:scrollUp.100vh.event` for full screen scrolling and `on:scrollUp.1vh.event` for any user scroll interaction. 

## Describe alternatives you've considered

Original thought was to make it an event, but may not work as desired if needs to be attached to an existing element. Maybe work as `<amp-scroll-tracker>`?

**Comment by aghassemi** [comment]
@CrystalFaith We were originally thinking to create a dedicated component for the scroll-direction-based sticky headers, but I like your proposal much better as it is generic and maybe useful for other cases as well. Aligns nicely with amp-position-observer pattern too.

**Comment by aghassemi** [comment]
@nainar Lots of thumbs up on this request. Setting a P1

**Comment by nainar** [comment]
@aghassemi  has added this to our Fixit week task list.

**Comment by alanorozco** [comment]
Closing this in favor of #20881 unless anyone objects. Those interested in this feature can follow that issue instead. It has been prioritized so you folks can all expect it soon!
