### ISSUE TITLE
Deploy nightly builds (was http://amphtml-nightly.herokuapp.com is old)

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#20142]
Do we still do nightly pushes to http://amphtml-nightly.herokuapp.com ?

Files looks old (From Dec 21)

**Comment by cathyxz** [comment]
I think pushing to heroku no longer works now because our repo size exceeded the maximum size heroku could handle.

**Comment by erwinmombay** [comment]
@cathyxz LOL

**Comment by aghassemi** [comment]
@erwinmombay any plans to have a nightly deploy somewhere? http://amphtml-nightly.herokuapp.com has been super useful for verifying fixes and doing demos on latest code

**Comment by erwinmombay** [comment]
@aghassemi i think we can move it over to firebase or app engine even. 

@lannka where do we have this process running from again?

**Comment by rsimha** [comment]
This can be done after release automation is in place.

Assigning to @Marcial1234 @danielrozenberg

**Comment by taymonbeal** [comment]
Out of curiosity, any particular considerations around this being nightly vs. on every commit?

Also, you could probably just use a GCS bucket.

**Comment by rsimha** [comment]
There's a separate effort to support on-demand deployment of specific commits: #21258

**Comment by taymonbeal** [comment]
Is that about commits that are still being reviewed? I was talking about commits that had been merged into master. The purpose would be to allow integrators outside the AMP Project (like my team at Google) to run their own integration tests on every commit.

**Comment by rajsite** [comment]
Is there a public way to access the artifacts from [tagged releases](https://github.com/ampproject/amphtml/releases)? I wasn't able to use gsutil to list the contents of `gs://amp-travis-builds`.

**Comment by danielrozenberg** [comment]
This is now handled in #25616. Closing this as a duplicate.
