### ISSUE TITLE
Clickjacking: X-Frame-Options header missing

### ISSUE THREAD

**Issue by zobaer99** [ampproject/amphtml#20168]
Hello
I got a clickjacking bug in your Website,sign up Page and Login Panel , about , tools ,docs , etc...

1. First i was visiting your website then i saw your main website are vulnerable to clickjack then i was going to try same thing in your Sing up page then i found that bug again . Then i open notepad and use that following code to confiming that bug :

<html>
<head>
<title>Clickjack test page</title>
</head>
<body
<p>This website is vulnerable to clickjacking!</p>
<iframe src="https://www.ampproject.org/" width="1247" height="800"></iframe>
</body>
</html>

Following link are also vulnerable to Clickjacking :

https://www.ampproject.org/singup/

\*and all the other pages are also vulnerable*/

2.save it as <anyname>.html eg s.html
3.and just simply open that..

 i thing user panel are also vulnerable to clickjaknig..and all the button are working good and all the the page are also bulnerable to clickjacking:)

As far as i know this data is enough to prove that your site is vulnerable to Clickjacking..
according to OWASP its more than enough..
https://www.owasp.org/index.php/Testing_for_Clickjacking_(OWASP-CS-004)

Solution:
https://www.owasp.org/index.php/Clickjacking_Defense_Cheat_Sheet
check this out..here is the solution for that.

+-0
![screenshot_1](https://user-images.githubusercontent.com/42531286/50783163-3dc1f980-12d4-11e9-9ee6-919494cb9952.png)
![screenshot_2](https://user-images.githubusercontent.com/42531286/50783165-3dc1f980-12d4-11e9-80f5-5eb98a1964d3.png)
![screenshot_3](https://user-images.githubusercontent.com/42531286/50783166-3ef32680-12d4-11e9-93a1-330e850b5046.png)
![screenshot_4](https://user-images.githubusercontent.com/42531286/50783168-3f8bbd00-12d4-11e9-8157-4252bcc1f45d.png)
![screenshot_5](https://user-images.githubusercontent.com/42531286/50783171-40bcea00-12d4-11e9-9b3c-62c3b9785390.png)
![screenshot_6](https://user-images.githubusercontent.com/42531286/50783173-41558080-12d4-11e9-8be0-ff3668d80454.png)
![screenshot_7](https://user-images.githubusercontent.com/42531286/50783174-41558080-12d4-11e9-9341-0050a4da6047.png)

Thanks :)

**Comment by aghassemi** [comment]
Thanks @zobaer99. 
@pbakaus, any reason to keep ampproject.org embeddable in all iframes? If not, good idea to enforce it.

**Comment by zobaer99** [comment]
It risked to client id. A Clickjacking attack uses seemingly innocuous features of HTML and Javascript to force the victim to perform undesired actions, such as clicking a button that appears to perform another operation. This is a “client side” security issue that affects a variety of browsers and platforms.

**Comment by pbakaus** [comment]
Just rolled out a fix, good catch, thanks!
