### ISSUE TITLE
Signed HTTP Exchanges?

### ISSUE THREAD

**Issue by fritexvz** [ampproject/amphtml#20160]
Is there possibillity to support the Signed HTTP Exchanges?

Example here:
https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html

How can we implement this on our server?

I am running Nginx.

Or, is there possibillity with CloudFlare?
https://www.cloudflare.com/website-optimization/ampersand/
and
https://blog.cloudflare.com/real-urls-for-amp-cached-content-using-cloudflare-workers/

Thanks!

**Comment by torch2424** [comment]
Triaging to @Gregable

**Comment by Gregable** [comment]
Yes, please take a look at https://github.com/ampproject/amppackager
