### ISSUE TITLE
[amp-list-load-more] focus is lost after hitting enter on see-more button while tabbing

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#20181]
focus is lost on see more button (need to keep focus on it for a11y)

**Comment by wassgha** [comment]
Hey @cathyxz ! I'd like to work on this but I have a few questions after I've investigated this a little,
1. Focusing on the `amp-list-load-more` itself doesn't really work, we need to focus on the internal `button` element, so how do we handle this for custom load-more buttons? (do we let users specify which element receives the focus or do we simply focus on the element they give us?)
2. What behavior should we expect for the infinite scrolling? (do we focus and possibly unintentionally scroll down or do we lose focus as is the case now?) Same applies to the manual mode with multiple elements.
TYA!
