### ISSUE TITLE
[actions] lower default timing of input-throttled and make it customizable

### ISSUE THREAD

**Issue by brandonmcconnell** [ampproject/amphtml#20194]
Feature Suggestion / Improvement: Currently, the only events I'm seeing are tap change and a few other very specific ones like lightboxClose. I'd like to see more events added, such as input. Currently, a field must be exited for the field to make any bind-changes on the page. But for some fields, especially range inputs, I need a label of the range-value to change as the slider is dragged. Similarly, I would like to be able to show field-specific validation outside the form element while a user is still typing, all the functionality already included within amp-bind, but with on `input` instead of on `change`.

Thanks!

**Comment by cathyxz** [comment]
Hi @brandonmcconnell ! Thanks for reaching out. =) 

We have both `input-throttled` and `input-debounced` per [amp-actions-and-events.md](https://github.com/ampproject/amphtml/blob/a4bd6008982cfd05747596227020890fa1a39cf9/spec/amp-actions-and-events.md). Do these work for you? If not, why?

**Comment by brandonmcconnell** [comment]
Hi @cathyxz! Thanks so much for the quick response! The `input-throttled` is exactly what I was looking for, but the 100ms delay is still throwing it off a bit. Any way to do away with that delay altogether or lessen it to 25ms-50ms?

**Comment by brandonmcconnell** [comment]
I don't mind at all @cathyxz! Looks good. Thanks for taking care of that 🙌🏼

**Comment by andrewwatterson** [comment]
I would have guessed that 100ms was reasonably responsive for most applications I can see this being used for (form validation, changing the label on a range slider), but I can also imagine the frustration if that delay were the biggest thing making your app feel slow. :)

So: 👍to making it customizable, but I think 100ms is a reasonable default.

**Comment by brandonmcconnell** [comment]
Thanks @andrewwatterson! Yeah, for form field entry, I think it's very reasonable. I've just already implemented on my range slider and there's a really noticeable delay on my end between the AMP version and my live jQuery version when dragging the slider-thumb.

**Comment by brandonmcconnell** [comment]
@choumx Hey William! Just checking in. Any news yet?

**Comment by cathyxz** [comment]
I'll get to this in our next fixit sprint. Sorry for the delay.

**Comment by brandonmcconnell** [comment]
No worries! I was just touching base. Thanks @cathyxz!

**Comment by cathyxz** [comment]
Took a look at this and it's actually quite a significant change because currently our events don't take parameters. It seems like implementing this would require changing how events are parsed. 

https://github.com/ampproject/amphtml/blob/d412590b7761f82a53c3712f4ce9e7d98a9465db/src/service/action-impl.js#L870-L884

I think we'll need to do some more thinking here, and slot this possible as part of a larger project.
