### ISSUE TITLE
amp-fx-flying-carpet: Jittery in viewer

### ISSUE THREAD

**Issue by jenia2015** [ampproject/amphtml#20207]
Flying Carpet jerks on iPhone when it is delivered from the AMP cache at www.google.com/amp/.
See video example: 

![google-amp-flying-carpet](https://user-images.githubusercontent.com/12524738/50892580-29c6e680-13ff-11e9-8e9a-ac1c3e09385e.gif)

Good: https://ampbyexample.com/components/amp-fx-flying-carpet/
Bad: https://www.google.de/amp/s/ampbyexample.com/components/amp-fx-flying-carpet/

Tested on iPhoneX, iPhoneSE (Safari Version 12.1.2) and Xcode iPhone Simulator

**Comment by choumx** [comment]
@jridgewell Known issue?

**Comment by jridgewell** [comment]
Hmm, probably a change in iOS 12 that caused the CSS/GPU hack to stop working.

**Comment by jridgewell** [comment]
Page scrolling itself is not affected, just the presentation of the flying carpet. There's probably nothing we can do to fix at this point, FixedLayer transfer isn't an option here. Just have to wait for Apple to fix their shoddy iframe scrolling.
