### ISSUE TITLE
Teads for AMP

### ISSUE THREAD

**Issue by RonanDrouglazet** [ampproject/amphtml#2021]
Hi,

As discussed earlier with your team, we would like to add Teads into your ad network list. Please find the one pager describing the expected Teads user experience : http://mobile.teads.tv/amp/inReadbyTeads.pdf

Next step would be opening a pull request linked to this issue. Can we proceed in this way ?

Best,
Ronan

**Comment by cramforce** [comment]
Sounds good. See https://github.com/ampproject/amphtml/pull/2022 for a recent sample PR for network inclusion.

If there are any features you are missing, it would be great if you could express them as a delta against AMP's current feature set.

**Comment by jridgewell** [comment]
Closed by #2190.
