### ISSUE TITLE
Consider installing the `WIP` GitHub application

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#20212]
App link: https://github.com/marketplace/wip

This app allows contributors to ensure a PR cannot be merged by accident (which happened once or twice in the recent past.) The free plan only supports blocking PRs if the word `WIP` is included in the title, the paid plan allows configuring other words (we often use `DO NOT MERGE`) and labels (we have the `blocked` label for that purpose)

**Comment by choumx** [comment]
Do you have links to the PRs? I haven't noticed this.

**Comment by danielrozenberg** [comment]
The only one I remember is #19865, except that we never applied the [blocked] label to it :roll_eyes:

**Comment by cramforce** [comment]
Doesn't our presubmit cover this already?

**Comment by rsimha** [comment]
`gulp presubmit` does cover `DO NOT SUBMIT`, but only when it is a part of source code. (It could be made to include `DO NOT MERGE` and `WIP`.)

https://github.com/ampproject/amphtml/blob/d17f36fe794ec43b8ff2fad964c041da839a5b98/build-system/tasks/presubmit-checks.js#L45-L47

I think the desire here is to block PRs based on the description text. I wonder how many people actually use the description to indicate that a PR is not ready to be merged. (The `blocked` label in #19865 was something I did for sorting PRs, and is a red herring so far as this discussion goes.)

If this is a rare occurrence, I'm not sure it's worth the overhead of installing a new GH app and managing its permissions.

**Comment by danielrozenberg** [comment]
Sounds like there's not a lot of interest in installing an app for this. Closing this issue - we can revisit this in the future if that becomes a real problem and we don't want to solve it using pr-check.
