### ISSUE TITLE
AMP Story CSS animations very janky in iGSA

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#20227]
1. Open any AMP Story in iGSA (ie: the Lebron James Google Stories story)
2. Notice how the progress bar is flickering on the pages that have a `auto-advance` mode 
3. Notice how the bookend opening animation is not as smooth as in a regular browser

## What browsers are affected?

iGSA

**Comment by newmuis** [comment]
I think we should try reimplementing the progress bar animation either (a) without `requestAnimationFrame`, or (b) only with `requestAnimationFrame` and no `transition`, and see if this helps.
