### ISSUE TITLE
[MASTER FEATURE] amp-video docking

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#20235]
A UI by which if video is playing, scrolling down the page minimizes and moves the video to the corner.
When scrolling back again, video maximizes and takes it original space.
The minimized video can be moved around by the user as well.
A dismiss affordance will also be supported. 

More details and discussions here: #8088

cc @aghassemi @alanorozco

**Comment by aghassemi** [comment]
Implemeted
