### ISSUE TITLE
`amp-lightbox-gallery` slides are very janky

### ISSUE THREAD

**Issue by acsant** [ampproject/amphtml#20234]
## What's the issue?
Image slides on the `amp-lightbox-gallery` are janky

## How do we reproduce the issue?

1. Go to https://www.google.com/amp/s/www.redfin.com/UT/Salt-Lake-City/1616-Federal-Pointe-Dr-84103/home/91713798/amp
2. Open the lightbox gallery in full screen and swipe through photos

![ampmblbgexp](https://user-images.githubusercontent.com/5479907/50936223-a370cb80-1423-11e9-9f77-7d56bf414964.gif)

## What browsers are affected?
* Chrome

## Which AMP version is affected?
1901081935550

**Comment by aghassemi** [comment]
@nainar @sparhami Carousel v1 bug, looks pretty bad, we should fix this before v2. Putting on next fixit.

**Comment by sparhami** [comment]
I notice some minor jankiness, both on stable and dev channel, (e.g. the white flashing borders) when trying to reproduce, but not the slides skipping issue. I tried Chrome 71/72 as well as they layers experiment with the same results.

@acsant I have a couple of questions: What version of Chrome are you running? Do you notice this on a specific mobile device, desktop with devtools or both?

**Comment by acsant** [comment]
One of the devices that we tested on had the chrome version 71.0.3578.99 (Android 8.1 Galaxy Note 9) and (One Plus 5 Android 9). I've also seen this on dev tools when you swipe the images slowly. But it's very obvious on the actual devices. I would try to swipe really slow and then really fast and the jankiness becomes obvious. Sometimes the photo loads on the top of the screen and moves down to the center of the full-screen carousel (which is very noticeable).
