### ISSUE TITLE
Google Ads denied the correct AMP ad

### ISSUE THREAD

**Issue by 4tek** [ampproject/amphtml#20246]
Hi guys,

has anyone had a problem with the new Google Ads account refusing valid AMP ads?

When you try to upload your ad, the system displays an error message that this is an HTML5 ad.
The ad is done in Google Web Designer and passes the AMP4ADS test correctly on the page with the validator.
**The most important thing is that the ad loads correctly in other Google Ads accounts.**
I am convinced that it is done well.

Support Google does not want to help, ignores the problem and gives bad and nonsensical advices like "you can not refer to external scripts like https://cdn.ampproject.org/v0/amp-gwd-animation-0.1.js"

Do you have any idea how to deal with it?

**Comment by jpettitt** [comment]
This is outside the scope of amphtml - if it passes validation and the ads system won't take it your best bet is to follow their support protocol (sorry I'm not familiar enough with their support options to give specific advice).  There is nothing we can really add to this.
