### ISSUE TITLE
Introduce an easy way to block components by amp-consent

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#20253]
This is part of the amp-consent-v2 work. We need a feature to block all amp-ad components on the page in an easy way. So that CMP can manage all ads on the page. 

Approach 1: Block all `<amp-ad>` components on the page if there's `<amp-consent type='cmp_name'>` on the page. 
- Pro: Requires minimal work for the publisher if they use CMP to manage consent
- Con: Introduces extra delay to every `<amp-ad>` (even if the ad decides not to be blocked by CMP) because the `<amp-ad>` will need to wait for the `#buildCallback` of `<amp-consent>` element. 

Approach 2: Introduce a new meta tag that's defined by the publisher. Block corresponding components on the page if the meta tag is found. 
- Pro: Better performance because all information is in the header. Cleaner code because everything is synchronous.  
- Con: Need the publisher's effort to add meta tag to the header. If the publisher fail to add the meta tag, it will lead to cmp not blocking anything. (It could also be a pro if the CMP does not exist, because the publisher don't need to individually tag every element they want to block) 

After a discussion with @lannka, we decided Approach is more preferable. Please let us know if there's any early feedback. I'll post the detail design of the meta tag to the issue later. 

@jasti @lannka @torch2424

**Comment by lannka** [comment]
Approach 2 is essentially splitting the amp-consent config into 2 parts, one in document head one in amp-consent element. The one in document head can be used by any other extensions on the page without waiting for amp-consent to load. I think this is the right way to go.

**Comment by jpettitt** [comment]
What about other components that can have ads or handle PII? `amp-iframe` and all of the video components that can carry preroll, twitter, FB, instagram et al.  You only mention `amp-ad` in # 1 and # 2 implies more than `amp-ad` but isn't specific, an example or two would help.

**Comment by jasti** [comment]
Based on the AMP principle: the user experience > developer experience > work we have to do. This seems to fall under the user experience bucket because we want to load the ads as quickly as possible without waiting for build callback. Option 2 SGTM.

**Comment by zhouyx** [comment]
Thank you all for the feedback. I'll go with Option 2. To introduce a new meta tag that the publisher can include in the page header to block AMP components. 

@jpettitt made a good point that we need to provide more flexibility to the publisher. So that they can specify which components they want to block. 

I propose we make the meta tag content customizable. The publisher can define which AMP component to block by specifying the component name. 

For example 
```
<meta name="amp-consent-block" content="amp-ad,amp-iframe">
```
AMP will add `data-block-on-consent` attribute to every `<amp-ad>` and `<amp-iframe>` on the page.  
This provides very limited customization, but I believe it's sufficient in most cases.  WDYT

**Comment by zhouyx** [comment]
We could expand the `content` value upon further request, if the publishers want to select ads of certain type.  

@lannka concerns that the publisher can forget the meta tag when using CMP. 

@Gregable @honeybadgerdontcare Is it possible to force the following rule with validator?
When `<amp-consent>` has a `type` attribute,  `<meta name="amp-consent-block" content="">` must be included in the header.

**Comment by honeybadgerdontcare** [comment]
@zhouyx 	Yes and no.

There isn't anything within an AttrSpec that would require another TagSpec (outside of extensions). However, this is possible to do on the TagSpec.

To accomplish this and allow `<amp-consent>`s without `type` attribute, then there will need to be two TagSpecs. One without the `type` attribute and another with the `type` attribute set as `mandatory`. Then that second TagSpec can utilize `requires` to require the `<meta name="amp-consent-block" content="">` TagSpec and it can utilize `satisfies` to satisfy it.

E.g.
```
TagSpec {
  name: "AMP-CONSENT"
  ...
}
TagSpec {
  name: "AMP-CONSENT"
  spec_name: "amp-consent [type]"
  requires: "meta name=amp-consent-block"
  attrs: {
    name: "type"
    mandatory: true
  }
  ...
}
TagSpec {
  name: "META"
  spec_name: "meta name=amp-consent-block"
  satisfies: "amp-consent [type]"
  attrs: {
    name: "name"
    value: "amp-consent-block"
  }
  ...
}
```

**Comment by zhouyx** [comment]
Thank you @honeybadgerdontcare. One question, if we use two tagSpecs, can we still enforce only one `<amp-consent>` element on the page?

**Comment by honeybadgerdontcare** [comment]
@zhouyx 	Yes! Both can have `unique: true` set on them. What the validator does is it looks for the best matching validator rule to apply and applies that rule. So if the document does not have the `type` attribute present, it will apply the TagSpec without the `type` attribute.

**Comment by zhouyx** [comment]
Great! Thank you @honeybadgerdontcare. I'll try that.
