### ISSUE TITLE
Amp cache purge API issue

### ISSUE THREAD

**Issue by santoshkjena** [ampproject/amphtml#20269]
We are using AMP cache purge API from google to purge any URL from google amp cdn but this is not working .
 Below is the code showing the way we are executing the API . 
[Code here](https://github.com/santoshkjena/ampcachepurgeissue/blob/master/amp_cache_update.php )
Please find the curl command screenshot  (showing the response headers and body) link  below 
[screenshot   here](https://github.com/santoshkjena/ampcachepurgeissue/blob/master/amp-cache-update.png)
Need your quick help to get this verified, if we are missing anything.

**Comment by vishalitg** [comment]
I'm also facing the same issue. Please, help me to fix this issue.

**Comment by aghassemi** [comment]
@santoshkjena Thanks for the report, is this something that used to work with the same code or is the code new?

/to @jgluk to triage. 
/cc @Gregable

**Comment by Gregable** [comment]
Tracked internally for Google's Cache as 122836254

**Comment by Gregable** [comment]
@santoshkjena - can you share the amp cache URLs with me? If you don't want to share them on github, you can send me a private message on our [slack channel](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#discussion-channels). My user name there is also `gregable`.

**Comment by santoshkjena** [comment]
@aghassemi This is a new implementation and it is implemented as per the steps defined on this  https://developers.google.com/amp/cache/update-cache URL

**Comment by santoshkjena** [comment]
@Gregable  i have sent you the details on slack . please have a look.

**Comment by rudygalfi** [comment]
@Gregable Did this get resolved over Slack?

**Comment by Gregable** [comment]
The details sent over slack were shared with the Google Cache team. The issue was not resolved to the best of my knowledge.

**Comment by Antoinebr** [comment]
I'm facing the same issue.

The API sends back : ```OK```  but the cache is not flushed. 

My canonical page has a ```cache-control: max-age=0```

To test how fresh is the cached version I echo a timestamp ( server side ) on my canonical page and compare it to the cached page. 

The code I used to flush the cache : https://glitch.com/edit/#!/amp-tracking?path=bustCache.js:40:13 

I recorded a video which shows the issue : 


It's not possible to embed videos directly, but you can put an image which links to a youtube video:

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/MiozEjLLWSk/0.jpg)](https://www.youtube.com/watch?v=MiozEjLLWSk)

 https://www.youtube.com/watch?v=MiozEjLLWSk&feature=youtu.be

**Comment by morsssss** [comment]
@jgluk does this API work at all currently? Or is it failing in certain circumstances?

**Comment by jgluk** [comment]
We are currently internally tracking a project to fix some of the inconsistent behavior of this API.

**Comment by morsssss** [comment]
thanks! glad to hear it 👍
