### ISSUE TITLE
Add tracking of article reading progress

### ISSUE THREAD

**Issue by helin24** [ampproject/amphtml#20279]
We'd like to track the latest paragraph a user has read in an article and send this information to a server. 

Originally we planned to add this to the amp-access-scroll extension:
https://github.com/ampproject/amphtml/pull/20222

@cramforce

**Comment by cramforce** [comment]
Does element visibility trigger doe this:
https://www.ampproject.org/docs/reference/components/amp-analytics#page-and-element-visibility-trigger

**Comment by helin24** [comment]
Partially, but we'd like to trigger based on many elements in the page (i.e. all paragraphs) and it looks like element visibility is intended for single elements. Is there a way to modify the usage of element visibility to fit our use case, though?

**Comment by cramforce** [comment]
@helin24 I'd certainly be open to allow the selector to match multiple elements and having the match element as a variable.

CC @jeffjose @zhouyx

**Comment by helin24** [comment]
Okay, great! Let me know if these two things are also okay:
- Triggering based on `<p>` elements (not just AMP extended elements)
- Sending information about the text of the paragraphs to the request locations

If that's all reasonable then would you like me to start making modifications to amp-analytics?

**Comment by cramforce** [comment]
@zhouyx PTAL

**Comment by zhouyx** [comment]
@helin24 Thank you for filing the issue. 

I see three requests here:
1. Allow amp-analytics visible trigger to select any random element on the page (not AMP elements)
    - This has been a popular request. We decided to restrict visible trigger to AMP element due to performance concern. Maybe it's time to expand the feature @jeffjose 
    - A workaround we usually suggest is to use <amp-layout> to wrap the non AMP element. Would that work for you?
2. Allow visible trigger to select multiple elements
    - This has been a popular request as well. Copying and paste visible trigger config for individual element is very painful. @jeffjose 
3. Send information about the selected element
    - We support a `data-vars-*` that sends the data you defined along with the request. But innerText is not supported

I looked at #1234, and had some questions
1. Do multiple requests get sent when a paragraphs get viewed twice. 
2. I saw you want to send part of innerText along with paragraph, does this only work with paragraph? Could you describe your usage to me, and is it a special use case or a general use case?

**Comment by jeffjose** [comment]
1. @zhouyx Can you provide more details of the performance penalty? Are some tags worse than others? If so, we could start with a small allow-list.
2. +1.
3. I agree with @zhouyx. If you really want plain-text in the request, you could do something like `data-vars-snippet="<one-sentence-snippet>". Will that work for you, @helin24?

**Comment by cramforce** [comment]
The performance penalty is due to `IntersectionObserver` being not yet widely available. I.e. there isn't a performant way in Safari to know whether an element is in view.

**Comment by helin24** [comment]
To be clear, the position-observer API we're using in #20222 doesn't use IntersectionObserver, right? You're just saying that we shouldn't use IntersectionObserver because of this limitation?

I think for now we're not worried about the last paragraph case because we don't need a precise measure of completeness, just a way to correlate AMP reading position with reading in other mediums. That's why we're sending text and not worrying about scroll position.

Thanks again for the updates and consideration. I see you posted additional comments to our PR; I'll address those shortly.

**Comment by zhouyx** [comment]
Close by #20222
