### ISSUE TITLE
amp-accordion: Accordions containing images don't animate open

### ISSUE THREAD

**Issue by andrewwatterson** [ampproject/amphtml#20271]
https://ampbyexample.com/components/amp-accordion/

In the "Animated Accordions" section:
1. Click "Section 2"
Expected: Section 2 smoothly animates open like Sections 1 and 3 do
Actual: Section 2 snaps open after a perceivable pause

Observed on Chrome 71 and AMP 1901021931380.

**Comment by aghassemi** [comment]
merging with related https://github.com/ampproject/amphtml/issues/20272
