### ISSUE TITLE
Documentation issue with amp-video

### ISSUE THREAD

**Issue by brusco77** [ampproject/amphtml#2027]
Hi, here
https://www.ampproject.org/docs/reference/amp-video.html

https is required for src, but on console log I see "https:// or // is required"

using //, everything works fine and it is validated. is https really necessary?

**Comment by cramforce** [comment]
The video must be served from HTTPS.

**Comment by brusco77** [comment]
ok thanks but... why does it work (and validates) this test here:
http://www.nicolabrusco.com/test.html#development=1
? (the video at the bottom)

**Comment by cramforce** [comment]
Probably a bug.

**Comment by brusco77** [comment]
thank you! sorry for the dumb question: can I use a https domain which is different from the http domain of the amp page?

**Comment by cramforce** [comment]
No dumb question! Thanks for spotting the bug!

**Comment by Gregable** [comment]
We also have this as an outstanding bug for the valiator, but too many documents are using relative URLs at the moment, so we need to roll out carefully.
