### ISSUE TITLE
Validator crashes after finding errors

### ISSUE THREAD

**Issue by morsssss** [ampproject/amphtml#20270]
## What's the issue?

On more than one occasion, I've seen the validator crash when it hits validation errors.

## How do we reproduce the issue?

Here's one sample of the output:
```
product-details.html: FAIL
product-details.html:31:2 The attribute 'src' in tag 'amp-carousel extension .js script' is set to the invalid value 'https://cdn.ampproject.org/v0/amp-carousel-0.2.js'. (see https://www.ampproject.org/docs/reference/components/amp-carousel)
product-details.html:167:12 The script tag contains invalid JSON that cannot be parsed.
product-listing-men.html: PASS
product-listing-women.html: PASS
product-not-found.html: PASS
[09:14:50] 'validate' errored after 1.07 s
[09:14:50] Error in plugin 'gulp-amphtml-validator'
Message:

AMPHTML Validation failed for 1 files.
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```
## What browsers are affected?

All

## Which AMP version is affected?

All

**Comment by honeybadgerdontcare** [comment]
There are multiple ways to call the validator. Could you elaborate your setup and also include the html that eventually causes it to fail like this?

**Comment by morsssss** [comment]
Any error I create seems to trigger this failure. I first noticed it when I foolishly left a stray double quote near an HTML tag:

```
<ul>"
```

Saw it again when our build process requested a JS file from the AMP CDN that doesn't exist yet:

```
<script async custom-element="amp-carousel" src="https://cdn.ampproject.org/v0/amp-carousel-0.1.js"></script>
```

**Comment by Gregable** [comment]
I can't reproduce. If this is still an issue, please reopen.
