### ISSUE TITLE
How To add Facebook Pixel in AMP-Story

### ISSUE THREAD

**Issue by siddiqrahman** [ampproject/amphtml#20297]

**Comment by torch2424** [comment]
Triaging to @newmuis , feel free to re-assign. 😄

**Comment by newmuis** [comment]
See https://stackoverflow.com/questions/45455167/how-to-add-facebooks-pixel-into-googles-amp

In AMP stories, `<amp-pixel>` should be a direct child of the `<amp-story>` element.

Please feel free to reopen this issue if you feel it has not been resolved.
