### ISSUE TITLE
Why AMP-Stories take too much time to load?

### ISSUE THREAD

**Issue by siddiqrahman** [ampproject/amphtml#20296]
my amp-stories taking too much time to load. am attaching the link given below. http://siddiqrahman.com/story/amp.html

**Comment by torch2424** [comment]
Triaging to @newmuis , feel free to re-assign. 😄

**Comment by newmuis** [comment]
@siddiqrahman, how long is it taking?  It feels fairly avergae to me, and I want to better understand whether there is some case where we perform worse than normal, or whether this just falls into the general bucket of needing to improve the initial load performance.

**Comment by newmuis** [comment]
Closing this since the user has not responded; @siddiqrahman please let us know if you're still experiencing issues with this.
