### ISSUE TITLE
Replace ancestorElementsByTag with closestByTag in dom.js

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#20291]
Replace all usages of `ancestorElementsByTag` with `closestByTag`. They do the same thing except the latter uses a browser API if available (better). 

Bonus points for looking for and replacing other doppelganger functions!

**Comment by cjdeleon62** [comment]
@choumx Would it be okay for me to try doing this PR?

**Comment by choumx** [comment]
@cjdeleon62 Sorry, @delima02 was going to take it. Thanks for offering and please check out our other "good first issues"!

**Comment by cjdeleon62** [comment]
@choumx that's okay! on another note, is this issue okay to take? https://github.com/ampproject/amphtml/issues/20377

**Comment by choumx** [comment]
Sure, go for it.
