### ISSUE TITLE
Support of amp-analytics in amp-call-tracking module

### ISSUE THREAD

**Issue by anathex** [ampproject/amphtml#20302]
## What's the issue?

On page of [amp-call-tracking module](https://www.ampproject.org/docs/reference/components/amp-call-tracking) there is [design document](https://docs.google.com/document/d/1UDMYv0f2R9CvMUSBQhxjtkSnC4984t9dJeqwm_8WiAM/edit#heading=h.zha4avn54it8) (almost 2 years has passed since last update - is it still valid?) which has section describing that this module will support amp-analytics configuration on response. 

## How do we reproduce the issue?

It's just enough to use amp-call-tracking module as is. Also there's no examples of JSON response for amp-call-tracking module with additional amp-analytics configuration in [Documentation](https://www.ampproject.org/docs/reference/components/amp-call-tracking).

## What browsers are affected?

All browsers

## Which AMP version is affected?

Any version, e.g. 1901021931380.

**Comment by torch2424** [comment]
cc @lannka @zhouyx @calebcordry @jeffjose

**Comment by micajuine-ho** [comment]
I am going to close this issue, since there has been no response for a while. Feel free to reopen with more details.
