### ISSUE TITLE
amp-inputmask: credit card example doesn't work the way it should

### ISSUE THREAD

**Issue by andrewwatterson** [ampproject/amphtml#20304]
At the bottom of the page, go to "15 or 16 digit Credit Card (switches on 37 or 34)"

1. Type "3"
2. Type "7"
(Notice the value is now "347")
3. Type a 13 more digits
Expected: Card number beginning with 37 is displayed sequentially as characters are entered
Actual: Field displays number starting with "347" until I reach the 15th digit, when the errant 4 magically disappears.

@cvializ

**Comment by aghassemi** [comment]
Setting to `P1` and adding to `UI - Recent Launch Support`. Please adjust the priority as needed after triage @cvializ.

**Comment by cvializ** [comment]
I plan to resolve this with a named mask
