### ISSUE TITLE
Add a way to indicate the boundary that caused a scroll trigger to fire

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#2031]
This issue proposes adding a way to determine which boundary caused a scroll trigger to fire.

One way to do this would be to introduce two variables that are specifically scoped to a `scroll` trigger. The variables are called `verticalBoundary` and `horizontalBoundary`. A definition including this vars might look something like this:

```
<amp-analytics>
<script type="application/json">
{
  "requests": {
    "scrolled": "https://example.com/analytics?url=${canonicalUrl}&title=${title}&acct=${account}&vbound=${verticalBoundary}&hbound=${horizontalBoundary}",
  },
  "vars": {
    "account": "ABC123"
  },
  "triggers": {
    "scrollPings": {
      "on": "scroll",
      "scrollSpec": {
        "verticalBoundaries": [25, 50, 90],
        "horizontalBoundaries": [90]
      },
      "request": "scrolled"
    }
  }
}
</script>
</amp-analytics>
```

**Comment by rudygalfi** [comment]
cc @avimehta

**Comment by avimehta** [comment]
wouldn't [scrollTop](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/analytics-vars.md#scrolltop) and [scrollLeft](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/analytics-vars.md#scrollleft) work here? You can calculate the exact % using those variables and the scrollHeight and scrollWidth values.

**Comment by devdazed** [comment]
Not in all cases.  Given the case where the page loads and, when scrolled to the top, is already 75% through the page, the event will fire 3 times on load with all the same variable information, and it is impossible to tell which boundary each event is designated.  Unless some sort of complex method of maintaining state is implemented server-side it is impossible to accurately keep track of what scroll boundaries were passed on a user-by-user basis.
