### ISSUE TITLE
required by 'amp-fit-text'

### ISSUE THREAD

**Issue by vaso123** [ampproject/amphtml#2034]
Hi!

When this AMP project was heralding, I made the AMP pages for all our products. I validated theme, and everything was good.

Now I have several errors, one of this is:

The 'amp-fit-text extension .js script' tag is missing or incorrect, but required by 'amp-fit-text'.

Why is it?

You can check it here: 

http://vaso.hu/other/amp/amp-text.html#development=1

**Comment by jridgewell** [comment]
You'll need to include the AMP Fit Text component's script file inside the `<HEAD>` element:

```html
<script async custom-element="amp-fit-text" src="https://cdn.ampproject.org/v0/amp-fit-text-0.1.js"></script>
```
