### ISSUE TITLE
amp-install-serviceworker scope error

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#20343]
To whom it may concern:

I use amp-install-serviceworker for a while and it works fine. But I found an error occurred. 

>The path of the provided scope ('/') is not under the max scope allowed ('/mei/'). Adjust the scope, move the Service Worker script, or use the Service-Worker-Allowed HTTP header to allow the scope.

Here comes some information.

- demo site: [https://blog.lalacube.com/mei/yahoo_auction_fp_amp.php](https://blog.lalacube.com/mei/yahoo_auction_fp_amp.php)
- service-worker file path: [https://blog.lalacube.com/mei/sw_yauc_amp_workbox.js](https://blog.lalacube.com/mei/sw_yauc_amp_workbox.js)

it should work well in scope **./**

I checked the amp-install-serviceworker code. Looks like something strange here.
[https://github.com/ampproject/amphtml/blob/master/extensions/amp-install-serviceworker/0.1/amp-install-serviceworker.js#L310](https://github.com/ampproject/amphtml/blob/master/extensions/amp-install-serviceworker/0.1/amp-install-serviceworker.js#L310)

I wonder is this an issue or should I need to do anything ?

Paul

**Comment by torch2424** [comment]
Triaging to @prateekbh , Feel free to re assign 😄

**Comment by prateekbh** [comment]
Right, I see the big in defaulting it to `/`.
While we fix this, you can add data-scope="/me" for now.

**Comment by meistudioli** [comment]
Thanks you.
