### ISSUE TITLE
[amp-story] Progress bar is causing flakes in visual diff tests

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#20346]
See example here:  https://percy.io/ampproject/amphtml/builds/1324584

The expected output is the screenshot on the right. The cause is likely that the screenshot is taken before the progress is filled at the corresponding point of the progress bar. 

Frequency of this flake is not high.

**Comment by newmuis** [comment]
Two ideas: either add a hardcoded delay to all of the tests (that is greater than the number of ms for the progress bar animation), or check `getMode().test` in the progress bar code, and skip the animation during test.

**Comment by Enriqe** [comment]
I think I like the second idea better, since @gmajoulet was mentioning some upcoming changes to the progress bar. It might be easier to change/remove the `getMode().test` from the progress bar code instead of changing every single test, and then again when we change the progress bar code.

WDYT @gmajoulet ? I can send a PR to skip the animation during test.

**Comment by gmajoulet** [comment]
I think this is a progress bar bug that's actually getting caught by our tests :))

I can repro consistently with the following:

1. Click [here](https://www.google.com/search?&q=cnn+10+buildings+that+will+shape+the+world+this+year&oq=cnn+10+buildings+that+will+shape+the+world+this+year)
2. Open the first result
3. Navigate by one page
4. You should have two segments of the progress bar filled, but sometimes, like in the visual test, the second segment is still empty
