### ISSUE TITLE
Update amp-story translations

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#20344]
amp-story is [missing several translations](https://bit.ly/amp-story-strings).  We should update the translations to improve the experience in these languages.

**Comment by psdtomanythings** [comment]
Hey @newmuis , Can we help with translations ? We can help with Hindi ( hi ), Marathi &  Gujarati

**Comment by newmuis** [comment]
@psdtomanythings sure!  We don't currently support Marathi or Gujarati, but If you want to update the [Hindi strings](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/1.0/_locales/hi.js) to include all of the strings marked as `undefined` in the [spreadsheet](https://bit.ly/amp-story-strings), that would be much appreciated!

**Comment by newmuis** [comment]
This was updated in #21572.
