### ISSUE TITLE
AMP analitycs

### ISSUE THREAD

**Issue by vaso123** [ampproject/amphtml#2035]
Hi!

I've copied the code from here to an empty html page:

https://developers.google.com/analytics/devguides/collection/amp-analytics/

This is exactly the same code, I've just add a valid UA- for the code.

You can test it here:

http://vaso.hu/other/amp/amp-analitycs.html#development=1

I am getting this:

`AmpAnalytics analytics1 Analytics config could not be parsed. Is it in a valid JSON format? SyntaxError: JSON.parse: expected ',' or '}' after property value in object at line 4 column 34 of the JSON data
Stack trace:
Z.prototype.mergeConfigs_@https://cdn.ampproject.org/v0/amp-analytics-0.1.js:148:200
Z.prototype.onFetchRemoteConfigSuccess_@https://cdn.ampproject.org/v0/amp-analytics-0.1.js:144:65
promise callback*Z.prototype.layoutCallback@https://cdn.ampproject.org/v0/amp-analytics-0.1.js:143:127
promise callback*kd.prototype.delay@https://cdn.ampproject.org/v0.js:55:838
fe.prototype.schedule@https://cdn.ampproject.org/v0.js:127:252
V.prototype.schedulePass@https://cdn.ampproject.org/v0.js:210:38
V/<@https://cdn.ampproject.org/v0.js:201:457
Sc@https://cdn.ampproject.org/v0.js:48:529
cd.prototype.onReady@https://cdn.ampproject.org/v0.js:51:41
V@https://cdn.ampproject.org/v0.js:201:368
Qe.installResourcesService/<@https://cdn.ampproject.org/v0.js:247:393
w.getService@https://cdn.ampproject.org/v0.js:34:714
Qe.installResourcesService@https://cdn.ampproject.org/v0.js:247:348
cf.installCoreServices@https://cdn.ampproject.org/v0.js:268:643
@https://cdn.ampproject.org/v0.js:291:237
dd.installStyles@https://cdn.ampproject.org/v0.js:52:625
@https://cdn.ampproject.org/v0.js:291:185
@https://cdn.ampproject.org/v0.js:1:53
 amp-analytics-0.1.js:148:449

AmpAnalytics analytics1 No triggers were found in the config. No analytics data will be sent.`

**Comment by jridgewell** [comment]
Hi @vaso123: In your linked example, you have:

```json
{
    "vars": {
        "account": "UA-9219486-1"  // Replace with your property ID.
    },
    "triggers": {
        "trackPageview": {
            "on": "visible",
            "request": "pageview"
        },
        "trackEvent": {
            "selector": "#event-test",
            "on": "click",
            "request": "event",
            "vars": {
                "eventCategory": "ui-components",
                "eventAction": "click"
            }
        }
    }
}
```

Notice the `  // Replace with your property ID.` comment. That is invalid in JSON, thus causing the error. Removing the comment fixes the issue.
