### ISSUE TITLE
amp-vimeo & validator

### ISSUE THREAD

**Issue by okeul** [ampproject/amphtml#2036]
Hi !

amp-vimeo works well but there is an error in validation :
![capture d ecran 2016-02-16 a 12 17 47 pm](https://cloud.githubusercontent.com/assets/6248074/13074828/57342d2a-d4a7-11e5-8480-39883b222826.png)

Example :
http://output.jsbin.com/ducudajule#development=1

Do you have any idea ?

**Comment by cramforce** [comment]
The validator does not recognize it yet. Should land shortly. Tracked in #1732
