### ISSUE TITLE
Validator doesn't understand different layouts for different types of amp-carousels

### ISSUE THREAD

**Issue by Gregable** [ampproject/amphtml#20374]
From https://www.ampproject.org/docs/reference/components/amp-carousel#type

`<amp-carousel type=carousel>` for example, doesn't support the `responsive` layout.

The AMP Validator allows the superset of all layouts for either `carousel` or `slides` types. This is OK, but being more specific would produce more actionable information for developers when trying to build a page with an `<amp-carousel>`.

The plan is to constrain `type=slides` or unset type to the layouts:

```
    supported_layouts: FILL                                                     
    supported_layouts: FIXED                                                    
    supported_layouts: FIXED_HEIGHT                                             
    supported_layouts: FLEX_ITEM                                                
    supported_layouts: INTRINSIC                                                
    supported_layouts: NODISPLAY                                                
    supported_layouts: RESPONSIVE 
```

And to constrain `type=carousel` to the layouts:

```
    supported_layouts: FIXED                                                    
    supported_layouts: FIXED_HEIGHT                                             
    supported_layouts: NODISPLAY  
```

I think this is the correct set of supported layouts.

**Comment by sparhami** [comment]
I believe this is the other way around. `type="carousel"` can do FIXED/FIXED_HEIGHT, and slides can do the larger set.

For carousel v2, there will be no more type attribute, and you can do everything `type="slides"` can currently do.

**Comment by Gregable** [comment]
Yep, I typo'ed this. Fixed the list in the original post.

This is more of a question of what rules we should have for v1, I suppose. We can write new ones for v2.

**Comment by sparhami** [comment]
I think validation would be nice for people using templating systems that might not actually ever view the page. There is a runtime error, but it does not tell you what is valid. Restricting by type for carousel v1 would be nice.

**Comment by sparhami** [comment]
This is no longer relevant with amp-carousel 0.2 and #23840, since both types support the same layouts.

**Comment by nainar** [comment]
This issue is fixed for all users who upgrade their `<amp-carousel>` version to 0.2. 

For more details please see documentation here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-carousel/amp-carousel.md
