### ISSUE TITLE
Change waitForBody and waitForHead

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#20377]
We keep getting bugs around `waitForBody`. The promise returned just means the body has been added to the document, not that the body (and all it's children) have been fully parsed.

Instead, we should make `waitForBody` wait for DOM Ready.

But there are a few cases where waiting for DOM Ready is too much. These cases just want access to the `head` element, which we can guarantee by the presence of the `<body>` tag. So, let's also add a `waitForHead` that behaves exactly like the current `waitForBody` (or rather, let's rename it).

**Comment by cjdeleon62** [comment]
Can I take a crack at this issue if no one is doing it yet?

**Comment by jridgewell** [comment]
Sorry @cjdeleon62, I've been out of office the past two weeks. Thanks for trying though!
