### ISSUE TITLE
Unmute a story if it includes 2+ videos with audio.

### ISSUE THREAD

**Issue by Serhio77777** [ampproject/amphtml#20399]
There is a problem with story page unmuting.

If amp-story page has few videos with audio and we unmute story all videos will play with sounds. And the sounds of all videos overlap. And we can't mute/unmute only one video.

Is there a workaround?

**Comment by newmuis** [comment]
@Serhio77777 are you looking to programmatically mute a video, or allow users to selectively mute each of the videos?

**Comment by Enriqe** [comment]
Hey @Serhio77777, thanks for filing this bug! 

We currently don't have an affordance to control each individual video... BUT we are working on supporting clickable components inside an `amp-story-page` (#19213). This will allow the user to tap on individual videos on an `amp-story-page`, expanding them into an "expanded" view and enabling their controls. Including the mute/unmute controls. Hope this will address your use case.

Closing this issue in favor of #19213.
