### ISSUE TITLE
I2I: amp-auto-lightbox

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#20395]
**This feature is being rolled out.** For details on usage, [see the spec.](https://github.com/ampproject/amphtml/blob/master/spec/auto-lightbox.md)

## Background
`amp-lightbox-gallery` provides an enhanced experience for image viewing (pinch-to-zoom, etc.). 

- documents may explicitly "lightbox" an image by including an attribute and an extension
- documents may include images that are good candidates to lightbox, but do not include the attribute nor the extension

This proposal focuses on the latter.

## Goal
To automatically detect images to be lightboxed implicitly.

### Detection criteria
The document itself must meet certain criteria in order for detection to execute, in order to control the experiment before launch and to control the surface of application in general. Items themselves must meet the following criteria in order to get the auto-lightbox treatment:

1. Item must have loaded successfully.
2. Sizing of image by either of:
    a. one dimension of the natural size of the image should be larger than the viewport OR
    b. the render area of the image covers at least an arbitrary percentage of the viewport area OR
    c. one breakpoint provided in the srcset is larger than its corresponding viewport dimension
6. Item nor its ancestors should be explicitly actionable.
7. Item should not be opted-out at the ancestor or tag level.

Criteria two (2) and three (3) cover all the examples shown here.

Sizing constraints have multiple purposes:

- Reject images that have no purpose in lightboxes, e.g. logos, icons, badges.
- Reject images that would render improperly in a full-size setting, i.e. low-res images in general.

### Grouping
Grouping images into galleries out of scope. The criteria for grouping adds extra complexity and could lead to poor UX, so each lightboxable element will have its own group initially.

### Document-level criteria
In order for `amp-auto-lightbox` to detect items to lightbox, the document must meet the following criteria:

- Renders inside the Google SERP viewer/AGSA/iGSA. This may be extended to origin execution in the future, but we have to try out the feature in real-world scenarios and justify it beforehand.
- Does not use amp-lightbox-gallery explicitly by including the amp-lightbox-gallery extension and setting the lightbox attribute on at least one element.
- Runs default AMP runtime (i.e. no A4A, AMPHTML email, AoG, inabox, shadow).
- Semantically annotated document type matches either of:
    - OpenGraph og:type is article.
    - Contains JSON+LD schema with one of the following annotated @types:
        - `Article`
        - `NewsArticle`
        - `BlogPosting`
        - `LiveBlogPosting`
        - `DiscussionForumPosting`

### Dynamic content
Items dynamically rendered via e.g. `amp-list` or `amp-form` that meet the criteria should be applied by virtue of `DOM_UPDATE`.

### Explicitly actionable
Images should be considered explicitly actionable and thus not lightboxable when one of these criteria is met:

- the image or any of its ancestors has an `on="tap: ..."` action
- any of its ancestors is one of the following:
    - `a[href]`
    - `amp-selector [option]`
    - `button`
    - `amp-script` (impossible to determine click handlers)
    - `amp-story` (default gestures and UI, most images are used as subimposed layers)

### Special cases
Some special cases may also be rejected:
- `[placeholder]` items get replaced on load/hydration, so they should be rejected.
- We don't want nested lightboxes, so items inside an `amp-lightbox` should be rejected.
- `amp-carousel` will most likely in the future fulfill a special case where the feature is triggered as a gallery when all items are a mix of images and text.

### Explicit opt-out
Publisher may explicitly opt-out from auto-lightboxing at the Node level in order to disable the feature for either UI or legal/intellectual property reasons. Any item or ancestors thereof containing the attribute `data-amp-auto-lightbox-disable` should be rejected, so different levels of the document can be disabled:

- the document by `<body data-amp-auto-lightbox-disable>`
- a certain section by e.g. `<section data-amp-auto-lightbox-disable>`
- an individual item by e.g. `<amp-img data-amp-auto-lightbox-disable>`.

/cc @ampproject/wg-ui @aghassemi

**Comment by aghassemi** [comment]
Launched! 🎉

**Comment by photocoder** [comment]
data-amp-auto-lightbox-disable doesn't work.
web page has tag 
`<body data-amp-auto-lightbox-disable>`
But amp-auto-lightbox.js still loading to page
Here is you can see it: https://dimasfrolov.com/
