### ISSUE TITLE
amp-bind: Validating non-primitives causes runtime TypeError

### ISSUE THREAD

**Issue by dbarcosb** [ampproject/amphtml#20405]
## What's the issue?

I need to perform an operation (mapping) on a state before putting it as source for the amp-list. When I map every position of the array into an object, for any reason the list is not recognizing it. I understand this is a bug (not a FR).

## How do we reproduce the issue?

You can find an example [here](https://jsfiddle.net/stweyrzx/10/). However, if I map every position of the array into an array and not an object, it works ([here](https://jsfiddle.net/stweyrzx/9/))

Asked this some time ago [here](https://stackoverflow.com/questions/53516148/mapped-state-into-amp-list-src), but no answer.

## What browsers are affected?

All browsers

## Which AMP version is affected?

It never worked, as far as I know

**Comment by aghassemi** [comment]
@dbarcosb Thanks for the report and sorry you couldn't get an answer through other channels.

So tl;dr: is 
```
 [src]="menu.array.map(x => [x.size.toUpperCase(), x.color.toUpperCase()])"`
``` 
works but 
```
[src]="menu.array.map(x => ({size_new: x.size.toUpperCase(), color_new: x.color.toUpperCase()}))">
```
throws a 
```
blob:http://localhost:8000/f2f353d2-7e3e-4938-b0d8-657f40f25358:352 Uncaught TypeError: Cannot convert object to primitive value
    at Array.toString (native)
    at String (<anonymous>)
    at BindEvaluator.stringValueOf_ (blob:http://localhost:8000/f2f353d2-7e3e-4938-b0d8-
```

/to @choumx thoughts?

**Comment by choumx** [comment]
Ah, this actually has nothing to do with the bind expression syntax. The error is caused by trying to convert a prototype-less object to string via `String(obj)`.

**Comment by choumx** [comment]
https://github.com/ampproject/amphtml/blob/12541179f76ee25f8385a3ae2be81148da7c5b4e/extensions/amp-bind/0.1/bind-evaluator.js#L268
