### ISSUE TITLE
Uncaught SyntaxErrors seen when AMP tests include HTML files

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#20408]
We occasionally see errors of this sort:

```
  {
    "message": "Uncaught SyntaxError: Unexpected token <\nat test/integration/test-released.js:1:1\n\nSyntaxError: Unexpected token <",
    "str": "Uncaught SyntaxError: Unexpected token <\nat test/integration/test-released.js:1:1\n\nSyntaxError: Unexpected token <"
  }
```

From googling, the `<` appears to come from an HTML file. See [here](https://stackoverflow.com/questions/17586074/karma-unexpected-token-when-including-an-html-file) for more info.

In this case, `test/integration/test-released.js` uses `test/fixtures/released.html`. We already apply the `html2js` transform to the files in `./test/fixtures/*.html`, so I'm not sure why the error appears. Perhaps a timing issue?

https://github.com/ampproject/amphtml/blob/73e9f99c900c05bc2402e88da6df2c0bbe2a44f0/build-system/tasks/karma.conf.js#L49

Filing this as a placeholder, in case someone has other ideas.

**Comment by rsimha** [comment]
From http://karma-runner.github.io/3.0/config/preprocessors.html:

> - Note any .html files listed in the files section must be referenced at run time as window.__html__['template.html']. [Learn more](https://github.com/karma-runner/karma-html2js-preprocessor#how-does-it-work-).
> - If this preprocessor is disabled, included .html files will need base/ added to beginning of their path reference. See discussion in [issue 788](https://github.com/karma-runner/karma/issues/788).

**Comment by danielrozenberg** [comment]
Do we still see this happening?

**Comment by rsimha** [comment]
@danielrozenberg Yes, I'm sure I've seen this at some point in the past couple weeks. This can happen with local testing too, not just on Travis.

**Comment by rsimha** [comment]
Another instance from today: https://travis-ci.org/ampproject/amphtml/jobs/495712772#L1412-L1415

**Comment by rsimha** [comment]
This hasn't reared its head recently. Closing as obsolete.
