### ISSUE TITLE
For some elements don't render them if they aren't actually visible

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2042]
E.g. for iframes this is wasteful.

Not visible:

- visibility: hidden
- opacity: 0
- left or right of viewport.

**Comment by cramforce** [comment]
@dvoytenko how do you feel about this?

**Comment by dvoytenko** [comment]
Functionality wise - it's good. I'd only be concerned that we are currently not set up very well to easily measure visibility and opacity (we already do positioning against the viewport). Specifically we would want to monitor css/class changes, media queries, etc which we currently do very spotingly.
