### ISSUE TITLE
[amp-iframe]  sandbox=allow-storage-access-by-user-activation

### ISSUE THREAD

**Issue by Malvoz** [ampproject/amphtml#20423]
I understand if you want to wait for implementations, however I ask to consider adding the new `allow-storage-access-by-user-activation` sandbox directive as defined by the proposed Storage Access API, see: https://webkit.org/blog/8124/introducing-storage-access-api/.

**Comment by aghassemi** [comment]
@Malvoz All sandbox values are supported on `amp-iframe` since we just pass them along to the `ifame` so there is no change needed on our side.

**Comment by Malvoz** [comment]
That's weird, I'm pretty sure I saw a warning the console log.

**Comment by aghassemi** [comment]
@Malvoz that warning comes from the browser (since they don't support it yet). here is a non-AMP page reporting the warning (it happens when `iframe.setAttribute('sandbox', 'allow-storage-access-by-user-activation')` is called). https://output.jsbin.com/tonatazuta

**Comment by Malvoz** [comment]
Oh my bad, thanks! :)

**Comment by Malvoz** [comment]
Oh my bad, thanks!
