### ISSUE TITLE
🌸 Cherry pick request for #20392 into #20361 (Pending)

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#20426]
**GitHub issue your cherry pick is fixing:**

Issue #20392

**PR that you are requesting a cherry pick for:**

PR #20411

**Release(s) you requesting this cherry pick into:**

Production Release? No

Canary release? #20361

**Why does this issue meet the [cherry pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?  Be specific.**

`<amp-geo>` component is now included inside `amp-consent.js` and `amp-user-notification.js`, including the `{{AMP_ISO_COUNTRY_HOTPATCH}}` code. Because those files do not match our hot-patching code's expectations, they do not receive the correct country code. This makes it a race between them and the real `amp-geo.js` file to be the first to register the geo service. If one of the imposters is first, then the geo service will register as an unknown country.

/cc @cramforce

**Comment by cramforce** [comment]
Ouch, approved.

**Comment by cramforce** [comment]
I commented on the PR as to why this wasn't covered by forbidden dependency rules. Please investigate separately.

**Comment by jridgewell** [comment]
Already have an update to the foreign dependency rules in https://github.com/ampproject/amphtml/pull/20412.

**Comment by adelinamart** [comment]
This was cherry picked with new release 1901181700510
