### ISSUE TITLE
amp-ima-video returns error when not used in current document

### ISSUE THREAD

**Issue by cycleos** [ampproject/amphtml#20432]
## What's the issue?
If amp-ima-video is loaded on a page, but not actually used, this breaks the AMP validation.
This is different behavior from amp-video, which can be loaded without having actual video on the page.
Implementing amp-ima-video load only on pages with video could be quite complicated on certain CMS-es.

## How do we reproduce the issue?

1.  Create sample AMP page and include amp-ima-video without video
2. Try to pass validation
3. Validation fails.

If you repeat, but with actual video, validation passes.

In contrast:
1.  Create sample AMP page and include amp-video without video
2. Try to pass validation
3. Validation passes without or with video.

## What browsers are affected?

All browsers

## Which AMP version is affected?
Current version

**Comment by kilitary** [comment]
What's the issue?

If amp-ima-video is loaded on a page

How do we reproduce the issue?

Create sample AMP page and include amp-ima-video 

What browsers are affected?
A

Which AMP version is affected?
Current

**Comment by kilitary** [comment]
Дуфму

**Comment by kilitary** [comment]
INCOMING TRANSMISSION---------------------
.
.
.
.
SELF-BAN REQUEST TO RESCUE INFORMATION LEAK ====>

**Comment by aghassemi** [comment]
This is by design, most amp components need both the script tag and at least one usage tag to be valid. amp-video does not enforce this for historical backward compatibility reasons.

**Comment by cycleos** [comment]
Well, except that there is ad before the video, there is no much difference between AMP VIDEO and AMP IMA VIDEO. It is logical that both work in the same way...
