### ISSUE TITLE
Flicker in Scroll Event in Safari

### ISSUE THREAD

**Issue by egianco73** [ampproject/amphtml#2043]
Hi, 

I've a problem with AMP pages delivered over Google's CDN 
with Safari and iPhone (5, 6 and 6 Plus).

When a <div> container has the following class:

.fixed-bar-container {
    position: fixed;
    bottom: 0;
    left: 0;
    z-index: 999;
    width: 100%;
}

and:

div {
    display: block;
}

scrolling the page, the fixed-bar-container flickers.
Without AMP optimization, the fixed-bar-container is rendered fine in Scroll Event:
fixed at the bottom of the page.

Regards

**Comment by dvoytenko** [comment]
@egianco73 Do you have a sample page with this markup for us to test on?

Also, what do you mean by "Without AMP optimization"? We don't really touch any part of the markup/CSS so I'm not sure at which point they could conflict.

**Comment by egianco73** [comment]
Hi,

as follows a sample URL:

http://www.repubblica.it/spettacoli/musica/2016/02/17/news/app_musicali-132950338/amp

You can see on AMP the article as follows: 
1. open the URL with iPhone and Safari;
http://g.c/ampdemo/it

2. type "repubblica";
3. tap the article
4. scroll the page

You'll see a flicker for the shaebar.

Regards

**Comment by dvoytenko** [comment]
It's definitely an iOS issue. I filed the bug: https://bugs.webkit.org/show_bug.cgi?id=154399

Looking for ways to work it around...

**Comment by dvoytenko** [comment]
The fix for this has been submitted and should be in canary within a day or so.
