### ISSUE TITLE
Can amp-script support web component v1 ?

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#20447]
Hi, @choumx :

amp-script looks so cool. I like to implement amp-script in my AMP pages and try to use some web components which I code. I wonder is there any possible to bring web components through amp-script to AMP page.

Here comes my web components.
- [bounce card](https://blog.lalacube.com/mei/webComponent_msc-bounce-card.html)
 
Code in AMP:
```
<amp-script layout="container" src="script/pack-msc-bounce-card.js">
  <msc-bounce-card layout="responsive" width="1" height="1.1">
    <article>
      ...
      ...
      ...
    </article>
  </msc-bounce-card>
</amp-script>
```

Paul

**Comment by torch2424** [comment]
From what I can tell, currently, `<amp-script>` is under an experiment, and still very much under development. So it may be a while you can start to launch amp pages with `<amp-script>`. But you can definitely try it out, and feedback is very much appreciated!

Also, in terms of WebComponents, I am not entirely sure if that was implemented quite yet in WorkerDOM (the library that powers `<amp-script>`) cc @kristoferbaxter

**Comment by choumx** [comment]
This would be a pretty challenging (but super interesting) feature to add.
