### ISSUE TITLE
amp-geo should resolve during prerender

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#20444]
Currently `amp-geo` does not do anything in prerender mode (since `prerenderAllowed()` is not overridden so `buildCallback` never gets called.)

We should make sure `amp-geo` is prerender-safe ( e.g. does not in anyway expose the user to an endpoint ) and allow allow prerender mode on it.

At least in the case of country added via cache and patched JS case, it seems very doable. 

An example of a page where `amp-geo` stays in pending mode and pub fully blocking rendering in `prerender`: https://www-bakersfield-com.cdn.ampproject.org/v/s/www.bakersfield.com/news/are-feral-cats-supposed-to-be-gone-from-hart-park/article_b1d5e84c-19c1-11e9-983a-2344edc59f0f.amp.html?amp_js_v=0.1#prerenderSize=1&visibilityState=prerender

/to @zhouyx 
/cc @jpettitt 

see also: b/123088355

**Comment by jpettitt** [comment]
There is no 3p data access, the country is added to the  amp-geo.js file by the server.  There were a bunch of weird edge case race conditions bugs around the geo service, all fixed, I'd want to be sure we don't introduce new ones (it shouldn't but ...)

**Comment by jridgewell** [comment]
This needs explicit approval from @cramforce. I don't imagine there are any issues with allowing it, though.

**Comment by cramforce** [comment]
Prerendering is definitely fine here. Components that don't make 3P web requests are always save.

@jpettitt amp-geo never makes 3p requests, right?

**Comment by zhouyx** [comment]
@jpettitt let me know if there's anything I can help with here.

**Comment by jpettitt** [comment]
`amp-geo` makes no external requests.  I'll make a PR to enable pre-render

**Comment by zhouyx** [comment]
@jridgewell I didn't know prerender block `buildCallback` as well, I had this [PR](https://github.com/ampproject/amphtml/pull/14656) to fix a privacy issue due to an xhr request in `buildCallback` before. Is this a new change or I am understanding it incorrectly? Thanks.
