### ISSUE TITLE
[MASTER FEATURE] Enable use of AMP Components outside of AMP pages

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#20456]
Explore the idea of using AMP components in non AMP pages. 

Potential benefits:

- Currently developers have to create a new stack to work in AMP, this adds not just development overhead, but in some cases increase engineering teams (if they decide to use the paired AMP approach).  
- By being able to use AMP components outside of AMP we are making incremental adoption possible rather than require a complete change/addition in infrastructure.
- AMP doesn't support a full range of experiences yet, due to lack of component availability e.g. payments, VR experiences.
- Any significant improvements that we have made to components (e.g. amp-img not triggering reflow after network request, social AMP embeds allow for a single interface, amp-list allows for dynamic lists without JS payloads that may be render blocking) are tied to the AMP ecosystem 

cc @choumx @dvoytenko @jridgewell

**Comment by choumx** [comment]
Related: #15583, #17548

**Comment by cramforce** [comment]
@ssantosms yes!

**Comment by nainar** [comment]
Hi @ssantosms and @cramforce ! Does the discussion entail a high level discussion of the idea or a more in depth design review as well?

**Comment by cramforce** [comment]
Since @dvoytenko is the primary designer of this, he can just bring it up casually, and then we can see what process to follow.

**Comment by westonruter** [comment]
This is the master issue for Bento AMP?

**Comment by nainar** [comment]
@westonruter yes it is!

**Comment by asaxkid** [comment]
Just curious if there is any development on this.
