### ISSUE TITLE
amp-analytics: get details of clicked link

### ISSUE THREAD

**Issue by georgecrawford** [ampproject/amphtml#2046]
Using:
```json
      "anchorclick": {
        "on": "click",
        "selector": "a",
        "request": "anchorclick"
      }
```
How can I add the `href` of a clicked link to the analytics call?

**Comment by avimehta** [comment]
You can't get to this yet. https://github.com/ampproject/amphtml/issues/1298 might be able to help here but it is not ready yet.

**Comment by rudygalfi** [comment]
I think #1298 would indeed cover this. Pinged that one and closing this.

**Comment by georgecrawford** [comment]
:+1:
