### ISSUE TITLE
Sidebar for amp-story desktop incorrect width and overlay.

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#20476]
![image 1](https://user-images.githubusercontent.com/1492044/51619050-73362c00-1efd-11e9-83bb-44b9f5aa7921.png)

1. Width of the sidebar seems incorrect
2. Clicking on the left of the screen while the sidebar is open navigates to the previous page instead of closing the sidebar

Can be reproduced here: https://bulletin.google.com/share/amp/KdZJQgBa/CcZwvh

**Comment by gmajoulet** [comment]
@bramanudom do you have time to look into this during this sprint? Thanks!

**Comment by newmuis** [comment]
The linked document is not valid AMP: https://validator.ampproject.org/#url=https%3A%2F%2Fbulletin.google.com%2Fshare%2Famp%2FKdZJQgBa%2FCcZwvh
