### ISSUE TITLE
🌸 Cherry pick request for #20473 into #20470 (Approved)

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#20479]
## GitHub issue your cherry pick is fixing:

Issue #20264

## PR that you are requesting a cherry pick for:

PR #20477

## Release(s) you requesting this cherry pick into:

Production Release? NO

Canary release? YES

 Release Issue #20470 

## Why does this issue meet the [cherry pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

This isn't a very urgent P0, and maybe just a very very strong P1, but it breaks an API that is supposed to work with amp-story and that some publishers actually use.
Publishers who wrote `<amp-story-page background-audio="audio.mp3">` have their audio not playing.

/cc @cramforce @newmuis

**Comment by cramforce** [comment]
The title should say that this is going into canary, not prod.

Approved.

**Comment by gmajoulet** [comment]
Cherry-picked in the canary: https://github.com/ampproject/amphtml/releases/tag/1901232142340
