### ISSUE TITLE
background audio attributes on amp-story not functional

### ISSUE THREAD

**Issue by tomxbarnesx** [ampproject/amphtml#20473]
## What's the issue?

Background-audio, previously attached as an attribute to an amp-story-page, is no longer functional / playable.

## How do we reproduce the issue?

Create a boilerplate amp-story and attach a background audio file as an attribute of a amp-story-page. No sound. Nothing. This is also the case on past stories now published that were once functional. Has something changed about the way amp-story serves background audio?

## What browsers are affected?

Chrome, Safari, both desktop and mobile.

## Which AMP version is affected?

Version 1901181700510

**Comment by gmajoulet** [comment]
Thanks for filing this.
Broken by: #20264

Good news is version 1901181700510 has been rolled back yesterday because of another issue in the release, so it should work again.

**Comment by tomxbarnesx** [comment]
Hey @gmajoulet @newmuis  I noticed the background audio was working briefly yesterday but is out again. Should we plan on this feature being in and out over the next few days and plan our releases accordingly?
