### ISSUE TITLE
[Urgent] Removed unsafe attribute" error for amp-bind

### ISSUE THREAD

**Issue by leonalicious** [ampproject/amphtml#20474]
## What's the issue?
Please refer to : #20397 
![image](https://user-images.githubusercontent.com/4065175/51581690-0eca9b00-1f04-11e9-8bc1-a17879348fda.png)

## How do we reproduce the issue?
Please visit https://m.aliexpress.com  and click on `Sidebar` menu on the top left, and by then we will be fetching `Country` with `amp-list` and it will cause the browser to **COLLAPSE** with Thousand of errors.

## What browsers are affected?
All browsers

## Which AMP version is affected?
1901181700510

/to: @choumx @aghassemi

**Comment by choumx** [comment]
Same as #20397 and fixed by #20407 (in dev channel). Those are spurious errors and can be ignored.

@leonalicious Do you notice any impact on device?

**Comment by choumx** [comment]
The offending release #20361 has been rolled back -- we'll patch and roll forward tomorrow. Thanks for the report.

**Comment by leonalicious** [comment]
yeap @choumx , it will keep on hammering on the performance of the physical device, my CPU% workload suddenly raised to 150% upon the rendering.

**Comment by gmajoulet** [comment]
I can repro from the `/shopcart/list.html` page, but not by opening the sidebar (navigation menu). Rolling back the release #20361
