### ISSUE TITLE
"Removed unsafe attribute" error for amp-bind within amp-list

### ISSUE THREAD

**Issue by joshcp** [ampproject/amphtml#20472]
## What's the issue?

We're seeing the console error `Removed unsafe attribute:` on pages using amp-bind within amp-list. It also appears that this sanitization is hammering performance on physical devices.

![amp_removed-unsafe-attr](https://user-images.githubusercontent.com/1458588/51574417-86e08480-1e62-11e9-909b-ee4988df1851.png)

## How do we reproduce the issue?

Example URL: https://amp.luckyvitamin.com/p-2257376-swisse-ultiboost-liver-detox-180-tablet-s

Load the example URL and view errors in the console.

## What browsers are affected?

All browsers.

## Which AMP version is affected?

We noted this issue in version 1901181700510 and it looks like the issue may be related to #20285 and #20397

**Comment by choumx** [comment]
Thanks for the report. This is the same as #20474 and #20397.

> It also appears that this sanitization is hammering performance on physical devices.

Investigating this.

**Comment by joshcp** [comment]
Thanks @choumx
