### ISSUE TITLE
Use Chrome's new userActivation.isActive for iframes

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#20471]
https://blog.chromium.org/2018/12/chrome-72-beta-public-class-fields-user.html

Chrome 72 comes with flag to see if a message from an iframe is based on user interaction.
```
// Check that WindowPostOptions is supported
if (window.parent.postMessage.length === 1) {
  window.parent.postMessage('resize', {includeUserActivation: true});
} else {
  window.parent.postMessage('resize', '/');
}
```

```
if (event.userActivation && event.userActivation.isActive) {
    return Promise.resolve();
}
```

Two places we can use this:
1- `resize` detection for `amp-iframe`
2- two-way messaging between `amp-bind` and `amp-iframe` 

The paused unmuted video hack to do this detection should still work for other browsers. That would be needed for (2) but for (1) this would just be a better check than the current `focus` hack and the paused unmuted hack is not needed.

/to @choumx

**Comment by choumx** [comment]
Thanks for the heads up. 👍

**Comment by choumx** [comment]
Related: `b/145181877`
