### ISSUE TITLE
🌸 Cherry pick request for #20474 into #20361 (Approved)

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#20489]
## GitHub issue your cherry pick is fixing:

#20474

## PR that you are requesting a cherry pick for:

#20407

## Release(s) you requesting this cherry pick into:

Production Release? YES (#20361)

Canary release? NO (fix already exists in canary)

## Why does this issue meet the [cherry pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

A very large amount of spurious user errors (30K+ for #20474) can cause performance issues on low-end devices. 

/cc @cramforce

**Comment by choumx** [comment]
Approved by @cramforce over chat.

**Comment by gmajoulet** [comment]
Done, new patched release is https://github.com/ampproject/amphtml/releases/tag/1901231933480
