### ISSUE TITLE
CDN not correctly converting rel="icon" links to https via CDN - mixed content warning.

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#2049]
It looks like the CDN is not converting icons to https links via when loading the page. Instead it's just turning them into fully qualified links to the original site. This causes mixed content warnings

`Mixed Content: The page at 'https://cdn.ampproject.org/c/www.relaymedia.com/home.html' was loaded over HTTPS, but requested an insecure favicon 'http://www.relaymedia.com/favicon-32x32.png'. This content should also be served over HTTPS.`

 `<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">`

**Comment by cramforce** [comment]
Tracked at google as b/27198493

**Comment by jpettitt** [comment]
Seems to be fixed some time ago - closing.
