### ISSUE TITLE
Sandbox preferentially rendered AMP ads

### ISSUE THREAD

**Issue by jeffkaufman** [ampproject/amphtml#20500]
In #14240 we tracked adding the `sandbox-ads` feature (now launched) which turns on `<iframe sandbox=...>` for cross-domain iframes.  Validated AMPHTML creatives rendered in a friendly frame, though, don't get any sandboxing.  Is this something we could add as well?

Playing with this, seeing if it breaks anything, I did:

```
  renderAmpCreative_(creativeMetaData) {
    devAssert(creativeMetaData.minifiedCreative,
        'missing minified creative');
    devAssert(!!this.element.ownerDocument, 'missing owner document?!');
    this.maybeTriggerAnalyticsEvent_('renderFriendlyStart');
    // Create and setup friendly iframe.
    this.iframe = /** @type {!HTMLIFrameElement} */(
      createElementWithAttributes(
          /** @type {!Document} */(this.element.ownerDocument), 'iframe',
          dict({
            // NOTE: It is possible for either width or height to be 'auto',
            // a non-numeric value.
            'height': this.creativeSize_.height,
            'width': this.creativeSize_.width,
            'frameborder': '0',
            'allowfullscreen': '',
            'allowtransparency': '',
            'scrolling': 'no',
            'sandbox':
                'allow-same-origin ' +
                'allow-forms ' +
                'allow-popups ' +
                'allow-top-navigation-by-user-activation ' +
                'allow-popups-to-escape-sandbox'
          })));
```

Of course we'd need to feature detect if we actually did this.

The key thing that `3p-frame.js:applySandbox()` allows that I'd like to prohibit here is `allow-scripts`.  I believe scripting currently happens entirely outside the friendly iframe, and so any scripting within it would be an error.

If we did decide to do this I'd want to set it up for an A/B experiment to verify we weren't breaking ads.

**Comment by calebcordry** [comment]
@jeffkaufman Is there any update on this?

**Comment by jeffkaufman** [comment]
This isn't something I've been prioritizing.  It would be nice to have, but validation is already a lot of protection.
