### ISSUE TITLE
🌸 Cherry pick request for #20506 into 1901232142340 (Pending)

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#20509]
## PR that you are requesting a cherry pick for:
PR #20506

## Release(s) you requesting this cherry pick into:
1901232142340

Production Release? NO

Canary release? YES
Release Issue #20470

## Why does this issue meet the [cherry pick criteria]
Previously cherry picked PR #20473 is produces a new error that is causing users to get stuck on on ads pages for several clicks. 

This PR needs to follow #20473 if it is promoted to prod.

/cc @cramforce

**Comment by cramforce** [comment]
Approved

**Comment by gmajoulet** [comment]
Cherry picked in https://github.com/ampproject/amphtml/releases/tag/1901242049580
