### ISSUE TITLE
Warning message wrong: "Default value (200) does not match first result (200) for <AMP-LIST"

### ISSUE THREAD

**Issue by hw-dwalter** [ampproject/amphtml#20526]
## What's the issue?

Warning message in #development=1 is wrong.

> Default value (200) does not match first result (200) for <AMP-LIST [height]="100 * shop.cart.lines">. We recommend writing expressions with matching default values, but this can be safely ignored if intentional.

![image](https://user-images.githubusercontent.com/1303452/51740204-a90d1900-2093-11e9-8c4d-a119bd74e167.png)

## How do we reproduce the issue?

See gist https://gist.github.com/hw-dwalter/51e7227ee446099e6b053849c06afe19

**Comment by aghassemi** [comment]
/to @choumx It's a string vs number mismatch in `verifyBinding_`. (`'200' vs 200`)

**Comment by bharrigan** [comment]
@choumx Would this be a good issue for me to take a crack at?

**Comment by choumx** [comment]
@bharrigan Go for it! 😃

**Comment by choumx** [comment]
@bharrigan Also sign up here so we can assign issues to you: https://docs.google.com/forms/d/e/1FAIpQLSeF1PN4Ee7Ke5Hvn4uN_oznV3isr-tfFg7cFRLX2F2OJGhXpw/viewform?c=0&w=1
