### ISSUE TITLE
amp-mustache silently removes attribute name="action", not removed if name="a_action" from <input>

### ISSUE THREAD

**Issue by hw-dwalter** [ampproject/amphtml#20528]
## What's the issue?

amp-mustache removes attribute `name="action"` but attribute is not removed if `name="a_action"` from <input>.

![image](https://user-images.githubusercontent.com/1303452/51741034-05713800-2096-11e9-8810-f14b7eb943c9.png)

## How do we reproduce the issue?

See https://gist.github.com/hw-dwalter/bf00c5c96640207691b6da63608abd67

**Comment by choumx** [comment]
This is a duplicate of issue #17897. 

@hw-dwalter What's the impact of this on your page?

**Comment by choumx** [comment]
Closing as a dupe of #17897.
