### ISSUE TITLE
amp-mustache: Universal links (unknown protocols) are sanitized

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#20523]
To whom it may concern:

I use amp-list and amp-mustache to display some dynamic module. Looks like amp-mustach will drop some value not in its whitelist. 

Here comes my example.

HTML code:
```
<amp-list
  layout="responsive"
  width="1.784"
  height="1"
  items="."
  single-item
  src="webService.php"
>
  <template type="amp-mustache">
    {{#hits}}
      <a href="{{link}}">
        {{content}}
      </a>
    {{/hits}}
  </template>
</amp-list>
```

Response:
```
{
  "hits": [
    {
      "link": "https://tw.mall.yahoo.com/act/channel/overseas.html",
      "content": "content1"
    },
    {
      "link": "https://tw.mall.yahoo.com/act/channel/overseas.html",
      "content": "content2"
    },
    {
      "link": "yecstore://activity?p=mall-1-0-150825-bank091",
      "content": "content"
    }
  ]
}
```

The final one's link is an **Universal Links** and amp-mustache will not render it.

Paul

**Comment by choumx** [comment]
Thanks for the report. This should be fixable.

**Comment by meistudioli** [comment]
thanks a lot.

**Comment by choumx** [comment]
/to @delima02 First, try reproducing this by modifying a local example (e.g. examples/amp-list.amp.html) -- be sure to compare `amp-mustache-0.1.js` with `amp-mustache-0.2.js`. I'm curious if we ever allowed arbitrary URL protocols.

The relevant code path for 0.2 is purifier.js#purifyHtml(), which calls out to [DOMPurify](https://github.com/cure53/DOMPurify).

**Comment by choumx** [comment]
@meistudioli Which deep link protocols do you use? Just `yecstore://` or others?

Note that the AMP validator uses a small whitelist though it can be extended e.g. #3727.

**Comment by delima02** [comment]
`amp-mustache-0.2.js` rejects arbitrary protocols unless whitelisted. `amp-mustache-0.1.js` will accept arbitrary protocols like `yecstore://` and others in that format.
