### ISSUE TITLE
Enable amp-list-load-more with origin trials

### ISSUE THREAD

**Issue by palances** [ampproject/amphtml#20527]
Can we enable or add "amp-list-load-more" to "allow-doc-opt-in" in prod-config.json ? That would help developers to opt-in amp-list-load-more via meta tag.

**Comment by aghassemi** [comment]
@palances We are working on enabling Origin Trial for it. (works very similar to the proposed doc-level-optin you mentioned)

/to @cathyxz 
/cc @choumx FYI: use of origin trial coming soon.

**Comment by cathyxz** [comment]
Origin trials for `amp-list-load-more` is enabled via https://github.com/ampproject/amphtml/pull/20592. The PR will be in the next canary cut on Feb 5, and land in production on Feb 12. If you'd like to be in the origin trial, please contact @nainar.

**Comment by palances** [comment]
@nainar can you also added this one into the origin trials? /
https://m.lightinthebox.com

**Comment by nainar** [comment]
Hi @palances will reach out to you off thread for turning this on. Sorry to have missed this.
