### ISSUE TITLE
Design Review 2019-02-21 01:00 UTC (amp-digidip)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#20536]
Time: [2019-02-21 01:00 UTC](https://www.timeanddate.com/worldclock/meeting.html?year=2019&month=02&day=21&iv=0) ([add to Google Calendar](http://www.google.com/calendar/event?action=TEMPLATE&text=AMP%20Project%20Design%20Review&dates=20190221T010000Z/20190221T020000Z&details=https%3A%2F%2Fhangouts.google.com%2Fhangouts%2F_%2Fgoogle.com%2Famp-eng-desrev))
Location: [Video conference via Google Meet](https://bit.ly/amp-dr)

The AMP Project holds weekly engineering [design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md).  **We encourage everyone in the community to participate in these design reviews.**

If you are interested in bringing your design to design review, read the [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md) and add a link to your design doc by the Monday before your design review.

When attending a design review please read through the designs *before* the design review starts.  This allows us to spend more time on discussion of the design.

We rotate our design review between times that work better for different parts of the world as described in our [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md), but you are welcome to attend any design review.  If you cannot make any of the design reviews but have a design to discuss please let mrjoro@ know on [Slack](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#discussion-channels) and we will find a time that works for you.

**Comment by parsingeye** [comment]
I'd like to discuss https://github.com/ampproject/amphtml/issues/20653, a new extension `<amp-digidip>`

**Comment by lannka** [comment]
Notes for amp-digidip

- We can limit the extension one per page. So need to switch CSS selector to select the "scope".
- Suggest to use JSON config, which is more extensible. Also it can be easily sent over the wire in case we want to support remote config.
- We can add custom `vars` support, to provide custom data like publisher ID or so.
- We can run all the condition evaluations after user clicking on the link.
- What extra tracking do we need? The current proposal fits digidip's need already.
- Remote config spec: need to be finalized.
- What are the missing features in this generic extension for amp-smartlinks to migrate over? 1) pageview impression, which can be done via amp-analytics. 2) server side URL rewriting. We can rollout the current proposal as a MVP, and then enhance the extension to cover the server side rewriting. Once there, we can merge amp-smartlinks back to this generic extension.
- Next step for @parsingeye : finalize the JSON config spec and post it back to the I2I.

**Comment by parsingeye** [comment]
@lannka thanks for the summary, and everyone else for all the input.

JSON config spec proposal added to the end of the document https://docs.google.com/document/d/1slfb3znYHg4wdLwsvBqTFgB2K4esiltLAY1xq7g1ZpI
