### ISSUE TITLE
amp-form: Validate non-descendant inputs of a form?

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#20545]
Just browsing around and curious why we don't use [`HTMLFormElement.elements`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/elements) in form-validators.js. 

It returns non-descendant inputs of forms and we use it in amp-form.js. It's also a live collection and so may be more performant by avoiding `querySelector`.

Though if we do change this it may be a breaking change and need a version bump.

**Comment by cvializ** [comment]
Great question, that decision was made before I took ownership so I don't know why it was made off the top of my head, but I can investigate.

What behavior do you think this would change to where it would be a breaking change? Form validation is opt-in so this would only add new behavior that was previously not possible, right?

**Comment by choumx** [comment]
A form may now include previously ignored inputs during validation. Those new inputs may be misconfigured and thus harmless when ignored, but harmful when not.

May seem like a stretch but I'm constantly surprised by how brittle AMP pages in the wild can be. :)
