### ISSUE TITLE
Several amp-yotpo bugs

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#20559]
1. Child iframe removed in `unlayoutCallback` but never restored. `b/123308595`
2. Tapping "Write a review" expands the content height but doesn't appear to resize the iframe, resulting in truncated content. `b/123095598`
3. "Write a review" and other UI is not interactive on Safari when AMP page is embedded in a cross-domain iframe. [Possibly related SO bug](https://stackoverflow.com/questions/52826005/workaround-for-ios-10-12-webkit-safari-chrome-iframe-focus-bug). `b/123093583` 

/to @RanAbram /cc @aghassemi

**Comment by aghassemi** [comment]
Thanks @choumx.

Hi @RanAbram, If you are able to take a look at these and provide some updates, we would appreciate it. Thanks!

**Comment by RanAbram** [comment]
Hey guys,

Thanks for your feedback.
@senyat will take it from here.

**Comment by aghassemi** [comment]
Any updates? @senyat @RanAbram

**Comment by senyat** [comment]
@aghassemi we plan to address these soon.

**Comment by niritdabby** [comment]
Hey @choumx, 
Thanks for you feed back. 
1. Can you please provide some more information. Why should the iframe be restored? we do build it in each buildCallback
2. This is an expected behavior, not related to AMP. 
3. The bug is not reproducible, when opening the widget from iphone / android and the buttons are clickable.

**Comment by choumx** [comment]
1. An element may be laid out again after `unlayoutCallback` is called, e.g. switching to a different browser tab and then coming back. Details here: https://github.com/ampproject/amphtml/blob/master/contributing/building-an-amp-extension.md#destroying-heavyweight-resources
2. Users seeing cut-off text/images is WAI? Please elaborate.
3. The original reproduction page no longer exists but try testing it on AMP pages served from an AMP viewer (e.g. from Google search) on iOS.

**Comment by niritdabby** [comment]
@choumx 
Hey, thanks for your comments. I want to push a fix but I have no permissions. 
Can you please give me access ?

**Comment by choumx** [comment]
Please create a pull request: https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md

**Comment by ericselin** [comment]
These are indeed very serious bugs. I'm experiencing all three as well. Hope the PR will fix these.

**Comment by senyat** [comment]
@choumx we tried pushing to branch and got rejected (with user niritdabby), please assist

**Comment by choumx** [comment]
We don't allow pushing branches to amphtml. You have to fork it and create a pull request against your fork.

https://help.github.com/en/articles/creating-a-pull-request-from-a-fork
