### ISSUE TITLE
amp-call-tracking AdWords response format error

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#20551]
Based on this [Developers guide](https://developers.google.com/google-ads/amp/landing-pages#configure_amp_call_tracker), click-to-call links must be decorated with a link to the Google Ads call tracking configuration. However, when the client used this format, they are getting "Response must contain a non-empty phoneNumber field" error wherein the link containing the Google Ads call tracking configuration doesn't return a JSON response that conflicts to what the [amp-call-tracking component](https://www.ampproject.org/docs/reference/components/amp-call-tracking#attributes) from the official AMP reference page is requiring. 

Google Ads call tracking configuration URL: https://www.googleadservices.com/pagead/conversion/964376400/wcm?cl=hhHcCOOB6JABENDu7MsD&tel=020-7112-8953&mode=1

**Comment by dbarcosb** [comment]
We run into this issue as well. Thanks

**Comment by lannka** [comment]
@dbarcosb could you provide steps to reproduce the issue?

**Comment by torch2424** [comment]
@lannka 

Tested this out myself, and the endpoints provided return a 400 

![Screen Shot 2019-05-01 at 6 26 34 PM](https://user-images.githubusercontent.com/1448289/57052841-b875a280-6c3e-11e9-94d1-fbf2074cbcb4.png)

Thus, I'm starting to think I need something else to get JSON back (or a valid 200 response). Let me know! 😄

**Comment by torch2424** [comment]
So we got this down to two possible issues:

1. The URL expansion (to fill in variables) is not working, and giving what the endpoint expects.
2. We need to allow setting the name of the Key in the JSON response as the endpoint gives us.

Here is where we check the key: https://github.com/ampproject/amphtml/blob/master/extensions/amp-call-tracking/0.1/amp-call-tracking.js#L88

**Comment by lannka** [comment]
According to AdWords call tracking team, the widget is working as expected in Chrome. The error message is because the current browser client does not have a conversion cookie set, hence no phone number override is needed. To have a conversion cookie, user has to click a corresponding ad before landing on the page.

The widget is not functioning in Safari since its ITP launch, as it requires a 3rd party cookie. There is currently no immediate interest from AdWords to improve this given the relatively low usage. But please file separate issue if this become a bigger problem.

In anyway, the current error msg is confusing. I suggest:
1) change the phoneNumber field to optional
2) in case of missing phoneNumber field, we should do nothing (the current behavior), and print a warning message instead of an error message.

@torch2424 could you help on that?

**Comment by torch2424** [comment]
Totally can do this 😄 I think we should get a quick response from @alanorozco if they are okay with this since they started the extension. I'll open a PR though! 👍
