### ISSUE TITLE
FR: Propagate font-face definitions in ShadowDOM to work around Chrome bug

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#20577]
Issue opened from #12098. 

This issue aims to work around the following Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=336876

The HTML spec declares that font-face definitions are allows in ShadowRoot CSS, but Chrome does not support this. AMP can fix this support by propagating ShadowRoot font-face definitions to the parent document.

Areas for concern:
1. Will this add an extra Flash of Unstyled Text?
2. What if a font with the same name and a different file is already in the parent document?
3. How will this affect the bundle size of non-Chrome browsers?

/to @prateekbh for prioritization
/cc @gilbertococchi

**Comment by prateekbh** [comment]
Woops, the issue was archived by chrome :'(

I do see that we'll somehow need to parse the style tag declaring `@font-face` and propagate that font face definition to parent doc.

I'll try digging some ways on how to do that
