### ISSUE TITLE
🌸 Cherry pick request for #20548 into 1901242049580 (Approved)

### ISSUE THREAD

**Issue by torch2424** [ampproject/amphtml#20593]
## GitHub issue your cherry pick is fixing:

Issue #20548

## PR that you are requesting a cherry pick for:

PR #20588

## Release(s) you requesting this cherry pick into:

Production Release? YES

 Release Issue #20470

Canary release? YES

 Release Issue #20587

## Why does this issue meet the [cherry pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

All AMP Pages using AMP Consent with an amp-iframe are currently broken. As their amp-iframe is never laid out. Due to an error in which the parent container is shown and the iframe is shown.

/cc @cramforce
/cc @zhouyx 
/cc @Enriqe

**Comment by cramforce** [comment]
Approved

**Comment by Enriqe** [comment]
@torch2424 @zhouyx this cherry pick is ready to test in opt-in dev-channel version 1901302225410.

Can you please verify that the issue is gone there?

**Comment by torch2424** [comment]
cc @Enriqe 

Confirmed this to be working in the dev channel per the examples provided in: #20548

![screen shot 2019-01-31 at 11 03 00 am](https://user-images.githubusercontent.com/1448289/52079051-8e321d00-2549-11e9-8bfd-3c2a2a57c12b.png)
![screen shot 2019-01-31 at 11 03 15 am](https://user-images.githubusercontent.com/1448289/52079053-8e321d00-2549-11e9-869f-d1d670a1f3a9.png)

**Comment by Enriqe** [comment]
This was pushed and included in release https://github.com/ampproject/amphtml/releases/tag/1901302225410 which was pushed to production today.

**Comment by agarmave** [comment]
Thank you all!!

It works perfectly!
