### ISSUE TITLE
amp-form issue in latest release

### ISSUE THREAD

**Issue by leonalicious** [ampproject/amphtml#20594]
## What's the issue?

Based on the PR, it blocks the `GET` request of `action`
https://github.com/ampproject/amphtml/pull/20362

## How do we reproduce the issue?

Please visit any of our ShopCart / Detail page and Click on "Buy Now" Button, the button is not responding as all the `GET` requests are blocked.

## What browsers are affected?

All browsers

## Which AMP version is affected?

we are seeing this version 1901242049580 on Production but when we are checking it from `release` section, this version is categorized as `pre-release`.

![image](https://user-images.githubusercontent.com/4065175/51955354-9a04dd00-247e-11e9-80bb-dc00c81e9a77.png)

**Comment by aghassemi** [comment]
Rolling back the release until this issue is resolved and will roll forward again. Apologies.

**Comment by choumx** [comment]
I can repro on 011901242049580 but not on 011901241837330.

**Comment by aghassemi** [comment]
@gmajoulet  @torch2424 for now release was rolled back, let's fix, test and patch this and then roll forward again.

**Comment by aghassemi** [comment]
sorry @Enriqe instead of @gmajoulet as the on-duty.

**Comment by aghassemi** [comment]
(Canary would need to be patched or recut as well)

**Comment by Enriqe** [comment]
Sounds good, I will patch the fix for this as well as #20593 in the new release. Then I will roll forward.

**Comment by torch2424** [comment]
@leonalicious 

So the fix for this is now in PROD if I am not mistaken. 😄 

However, I still need to implement the original PR (this time not breaking everything 😞). So I wanted to ask, how were you using amp-form? Looking at the site currently, seems like you were using a button and amp-bind to manually call submit on the form. For example: `on:tap="... , form.submit"`. 

Was the implementation that broke? Thanks!

**Comment by leonalicious** [comment]
@torch2424 Sorry for the late reply, I was away for the past few days.

We have been using the `GET` method to do the `navigation`, so, when the user clicks on `form` submission, we will submit all the `amp-state` as `query params` to be directed into another page.

**Comment by torch2424** [comment]
@leonalicious Thank you for the response!

If you have the chance (and are familiar with the AMP dev channel), could you test the latest canary with your checkout flow? We've merged in: https://github.com/ampproject/amphtml/pull/20667 And want to make sure the new fix won't break your pages. I've gone ahead and manually tested this myself, but some testing on your end would be great. 👍 

Thanks! 😄

**Comment by leonalicious** [comment]
@torch2424 , version `1902072121410` seems working fine BUT version `1902081532110` seems ***NOT*** working on Detail Page

**Comment by torch2424** [comment]
@leonalicious 

Thank you very very very much! 😄 Glad to hear it is working on you end as well.

**Comment by leonalicious** [comment]
thank you for the effort to make this possible. Btw, I am thinking, right now we are only able  `GET` METHOD to do the page navigation, if we are planning to use `POST` METHOD, I presume the only way would be using the `AMP-Redirect-To` as Response Header, am I understanding it correctly?

**Comment by torch2424** [comment]
@leonalicious For that, I'll ask for @cvializ help, as they are more familiar with AMP form than I am 😄

**Comment by cvializ** [comment]
You are correct, the `AMP-Redirect-To` header is the only way to navigate the page after a `<form method="POST" ...>` successfully submits.
