### ISSUE TITLE
[Layers] amp-img not loading in non-root scroller

### ISSUE THREAD

**Issue by bjalford** [ampproject/amphtml#20598]
Example: https://pwamp-indy.indy100.com/article/rutger-bregman-billionaires-tax-evasion-speech-davos-world-economic-forum-watch-video-8752771

Note the list of the left. Scroll down and around item 18 the images won't render. If you then scroll down on the right side you'll see the images render so it looks like the trigger for 'in view' doesn't trigger on scroll.

Is there a solution?

**Comment by aghassemi** [comment]
@bjalford The link is not AMP, can you send an amp version? 

Is it actually using `amp-sidebar`? If it is just an `overflowing div` and not an `amp-sidebar`, that's something we don't yet support until layers project ( https://github.com/ampproject/amphtml/issues/14088 ) is fully launched.

**Comment by tommarulak** [comment]
@aghassemi It is inside amp-sidebar. It seems the amp-image lazy load will be triggered on the page body scroll, not the amp sidebar scroll. If you scroll the amp sidebar up to the no image, then scroll the page (right column) little bit you will see the amp-image initialised.

**Comment by aghassemi** [comment]
Thanks @bjalford.

@jridgewell @choumx This may have always been the case but I was the under the impression that `amp-sidebar` does layout for all its children. Looking at the code, it does call `scheduleLayout` for all children (it is not taking ownership) when it opens but `scheduleLayout` still considers visibility criterial and does not layout things below 3vh.

I don't think we want to go the route of taking ownership of children given layers is the right solution ( and ownership has its own set of issues like https://github.com/ampproject/amphtml/issues/17389#issuecomment-459548675).

**Comment by choumx** [comment]
This should be fixed by `layoutbox-invalidate-on-scroll` experiment (launched) and `intersect-resources` experiment (launching).
