### ISSUE TITLE
🌸 Cherry pick request for #20594 into 1901242049580  (Approved)

### ISSUE THREAD

**Issue by torch2424** [ampproject/amphtml#20602]
## GitHub issue your cherry pick is fixing:

Issue #20594

## PR that you are requesting a cherry pick for:

PR #20601

## Release(s) you requesting this cherry pick into:

Production Release? YES

 Release Issue #20470

Canary release? YES

 Release Issue #20587

## Why does this issue meet the [cherry pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

This is required to fix the P0 issue that is linked above

/cc @cramforce
/cc @cvializ 
/cc @aghassemi 
/cc @Enriqe

**Comment by cramforce** [comment]
Approved for pure revert.

**Comment by Enriqe** [comment]
@torch2424 @aghassemi this cherry pick is ready to test in opt-in dev-channel version 1901302225410.

Can you please verify that the issue is gone in this version?

**Comment by torch2424** [comment]
cc @Enriqe

Confirmed this to be working in the dev channel per the examples provided in: #20594

![screenshot_20190131-111057](https://user-images.githubusercontent.com/1448289/52082855-c38f3880-2552-11e9-801d-6497a87a9b5e.png)
![screenshot_20190131-111103](https://user-images.githubusercontent.com/1448289/52082856-c38f3880-2552-11e9-8f73-199d029f8b38.png)

**Comment by Enriqe** [comment]
This was pushed and included in release https://github.com/ampproject/amphtml/releases/tag/1901302225410 which was pushed to production today.
