### ISSUE TITLE
Add info table for amp-accordion

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#2061]
https://github.com/ampproject/amphtml/blob/master/extensions/amp-accordion/amp-accordion.md needs a table listing basic information and validator errors, which would align it with the presentation of the other extension .md files.

cc @Meggin @Gregable (to advise on validation errors to call out)

**Comment by ericlindley-g** [comment]
Working on this PR at #2064 — following up with Sriram to a table of validation errors as well

**Comment by Meggin** [comment]
Intro table added; couldn't add validations though as they haven't been implemented. Closing, as there's a separate PR that's tracking validation. FYI: https://www.ampproject.org/docs/reference/extended/amp-accordion.html

**Comment by ericlindley-g** [comment]
I think amp-accordion is still experimental (or should be?)—is that right? @sriramkrish85

**Comment by sriramkrish85** [comment]
@ericlindley-g it is still experimental - once we are done with the validation we can open it up.

cc @Gregable @powdercloud

**Comment by ericlindley-g** [comment]
@sriramkrish85 Thanks!

I have a PR to update the info table at #2288

**Comment by Meggin** [comment]
I'll update the docs to say it's experimental! Didn't see it in the dev
channel till now.

**Comment by ericlindley-g** [comment]
No worries—thanks!

**Comment by tori3** [comment]
[Question]
> amp-accordion elements are always display: block ?
https://www.ampproject.org/docs/reference/extended/amp-accordion.html

Is this why? I think to should allow more flexible style for expand trigger element.

**Comment by amphtml-team** [comment]
Could you elaborate more on what kind of flexibility?

Making it block would still let you set a width/height and also you could 
do more css styling. I would be able to help if you ping me on our slack 
channel @skrish

**Comment by Gregable** [comment]
`<amp-accordion>` validation is now live everywhere. It'll hit javascript in roughly an hour.

**Comment by sriramkrish85** [comment]
cool ill pull it out of experimental
