### ISSUE TITLE
amp-bind [hidden] not working with multiple inputs + hide conditions

### ISSUE THREAD

**Issue by nikse** [ampproject/amphtml#20627]
## What's the issue?

I am trying to hide div's based on the state of multiple (3) selects and the first two only partially work while the third fully worksBriefly describe the bug. 

If I use the first or the second select it only works one time and doesn't do anything or hides everything on the second use. If I use the third one first or after using one of the first two everything works as it should and the first two regain full functionality

## How do we reproduce the issue?

Check the jsbin below

https://jsbin.com/lirejiheni 

## What browsers are affected?

at least chrome

## Which AMP version is affected?

v0

**Comment by aghassemi** [comment]
@nikse Could you please provide some more details? A Url or some code that shows the problem?

**Comment by nikse** [comment]
@aghassemi sure, i wrote a description and added a link to an example but everything seems blank now?? let me track it down

**Comment by nikse** [comment]
@aghassemi here's a link to the jsbin i put together (seriously confused as to how my whole initial comment/description is blank all of a sudden)

steps to reproduce:
1) use the first or second dropdown and select any option
2) switch the same selector back to the initial/all option and see that nothing updates
3) if you used the third and final dropdown everything works fine again

furthermore if you start using the third dropdown first all functionality acts as normal. please let me know if you need any more details
