### ISSUE TITLE
Fix bugs in intro tables

### ISSUE THREAD

**Issue by Meggin** [ampproject/amphtml#2062]
It was tricky to test the intro and validation tables to get them exactly right across the docs. Now that they are live, I'm seeing bugs, and I should fix these. Really, it requires an end-to-end test, and sweep.

Three main intro table bugs I want to sweep in a PR:

- The intro to the validation tables is missing an end parenthesis across the tags.
- The links to validation errors are relative based on the ampproject.org site, which means they are broken if accessed from the specifications. Make the specific.
- We've got new tags that are missing intro and validation tables. Check the extensions list and update.

**Comment by rudygalfi** [comment]
FYI, filed #2061 for amp-accordion.

**Comment by Meggin** [comment]
Thanks!

**Comment by Meggin** [comment]
Bugs are fixed, and accordion has proper tables. Closing this.
