### ISSUE TITLE
Error: TypeError: this.media.webkitEnterFullscreen is not a function.

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#20639]
Hey @alanorozco can you please take a look

Most likely coming from 
https://github.com/ampproject/amphtml/blob/4e6291a319855d8faeadfe34e5217bb626bc7277/ads/google/imaVideo.js#L1200

Seen in version [1901302225410](https://github.com/ampproject/amphtml/releases/tag/1901302225410)

```
Error: TypeError: this.media.webkitEnterFullscreen is not a function. (In 'this.media.webkitEnterFullscreen()', 'this.media.webkitEnterFullscreen' is undefined)
```

**Comment by wassgha** [comment]
Claiming for Rebecca! This should require looking at the error logs.

/cc @nainar

**Comment by rebeccanthomas** [comment]
Closing this issue as this error cannot be reproduced.
