### ISSUE TITLE
<amp-list> Can't pre-initialize amp-list with content without an API callback

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#20641]
## Describe the new feature or change to an existing feature you'd like to see

Being able to preinitialize amp-list with content without having to make an API callback. This will ensure that the page renders with content and the end user isn't left waiting with a loading indicator. 

Raised by Alan Kent offline.

**Comment by alanorozco** [comment]
#20752 for approaches to this.

**Comment by samouri** [comment]
This feature landed in https://github.com/ampproject/amphtml/pull/27180.
Documentation is available at: https://amp.dev/documentation/components/amp-list/?format=websites#initialization-from-amp-state

🎉
