### ISSUE TITLE
🌸 Cherry pick request for gtag vendor configuration update. (Approved)

### ISSUE THREAD

**Issue by zikas** [ampproject/amphtml#20645]
PR that you are requesting a cherry pick for:

PR #20591 

Release(s) you requesting this cherry pick into:

1901312147090 (canary)

Production Release? NO

Canary release? YES

Why does this issue meet the cherry pick criteria? Be specific.

This change unblocks floodlight iframe adoption as it starts sending required conversion data to the server.

**Comment by dvoytenko** [comment]
Approved.

**Comment by kristoferbaxter** [comment]
This was already part of the canary release last week. Since the canary was cut late, it made it in.
