### ISSUE TITLE
this.timeout() may be used incorrectly

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#20646]
I've been trying to increase timeouts for flaky integration tests and I've noticed some of my tests not respecting the `this.timeout()` call. 

I believe the issue is it only works in `it()` blocks and not in `describe()` blocks: https://mochajs.org/#test-level

Looks like this is happening in a bunch of places in existing test code, and I'm not sure the `spec.timeout` feature in describes.js works either.

Perhaps we should ban `this.timeout` broadly and set reasonable defaults for unit/integration tests. It would require wrapping `it` though.

/cc @lannka

**Comment by cathyxz** [comment]
According to [documentation](https://mochajs.org/#suite-level), I think it's supposed to work at the suite level too though, no? 
https://mochajs.org/#suite-level

**Comment by choumx** [comment]
Hmm, maybe it's just `spec.timeout` overriding suite/test-level timeout then:
https://github.com/ampproject/amphtml/blob/81dbf07ef986ba4338a71420b01437fc9b2d4759/testing/describes.js#L453-L456

I'll try increasing that instead.

**Comment by choumx** [comment]
Yup, `spec.timeout` overrides `this.timeout` in integration tests. Sorry for the false alarm.
