### ISSUE TITLE
Getting form Information without forms?

### ISSUE THREAD

**Issue by Noacyl** [ampproject/amphtml#2065]
The site I am working on  requires the use of Forms; input, textarea, options are all needed. I looked at the source code for [https://www.ampproject.org/contact/](url) and I followed the idea of using the amp-iframe to include forms, but then I get an error about not using XML (which I have no clue how to do). I also noticed that the previously linked page gets an error for using just the iframe instead of amp-iframe. For sites that NEED forms, how would we go about collecting the information we need? Is there some kind of workaround that is not covered in the AMPProject tutorials? Any info would be fantastic.

**Comment by rudygalfi** [comment]
Yeah, https://www.ampproject.org/contact/ should be using amp-iframe. :-/

You should be able to embed a form in a page using amp-iframe. Not sure about the XML error.

We have an issue tracking direct form support here: #1286.
