### ISSUE TITLE
amp-analytic & at internet

### ISSUE THREAD

**Issue by okeul** [ampproject/amphtml#2067]
Hello !

AMP Analytic doesn't work with AT Internet. There is an error in the validator :
![error_analytic](https://cloud.githubusercontent.com/assets/6248074/13104106/73898b14-d55b-11e5-9eff-56b8c3010300.png)

It's weird because the [documentation of AT internet](http://developers.atinternet-solutions.com/javascript-en/advanced-features-javascript-en/accelerated-mobile-pages-amp-javascript-en/#full-tag_5) is pretty clear but it doesn't seem match with [amp-analytic component](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/vendors.js#L65). For example, there is no trigger in this component.

Live example (from AMP example) :
http://output.jsbin.com/cabaqavura/#development=1

**Comment by cramforce** [comment]
Please contact AT internet support.

CC @BenDz

**Comment by BenDz** [comment]
Hi @okeul !
I do not have this issue, on your JSBin, the hit is correctly sent on my side:
![2016-02-17_15h57_14](https://cloud.githubusercontent.com/assets/3985936/13113422/4945c866-d58f-11e5-9ee8-dea9322e285b.png)

Perhaps your amp-analytics js file is not up to date?

**Comment by okeul** [comment]
It seems to works now. I don't see a blank pixel in the generated url, is it normal ?

**Comment by okeul** [comment]
Nevermind, I just saw your PR https://github.com/ampproject/amphtml/pull/2073/files :-)

**Comment by BenDz** [comment]
@okeul I think this issue is now solved? :)

**Comment by okeul** [comment]
@BenDz Yes, thanks you !
