### ISSUE TITLE
amp-carousel: Janky swiping in [type=slides][loop] with 2 slides

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#20685]
Try the following in [AMP playground](https://ampbyexample.com/playground/#url=https://ampbyexample.com/components/amp-carousel/source/):

```html
  <amp-carousel width="400" height="300" layout="responsive" type="slides" loop>
    <amp-img src="/img/image1.jpg" width="400" height="300" layout="responsive" alt="a sample image"></amp-img>
    <amp-img src="/img/image2.jpg" width="400" height="300" layout="responsive" alt="another sample image"></amp-img>
  </amp-carousel>
```

Swiping between slides is janky/broken. One possible fix is to override `shouldLoop` in `slidescroll.js` when number of slides < 3.

Context: `b/123093858`

/cc @aghassemi

**Comment by aghassemi** [comment]
@sparhami @nainar added it to the `Better AMP Carousel project` to verify as fixed in V2.

**Comment by Tzyinc** [comment]
+1 to facing this issue! Just adding the loop=true attribute breaks the swiping behaviour

**Comment by aghassemi** [comment]
related: https://github.com/ampproject/amphtml/issues/22608

**Comment by nainar** [comment]
This issue is fixed for all users who upgrade their `<amp-carousel>` version to 0.2. 

For more details please see documentation here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-carousel/amp-carousel.md
