### ISSUE TITLE
<ins> and <del>: allow "datetime" attribute

### ISSUE THREAD

**Issue by steffenweber** [ampproject/amphtml#2068]
The HTML elements `ins` and `del` have an optional `datetime` attribute (see [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ins)).

```
<ins datetime="2016-02-17T09:17:45+01:00">
```

However, the AMP validator does not like this attribute:

> The attribute 'datetime' may not appear in tag 'ins'.

Could you please allow the `datetime` attribute on `ins` and `del` elements?

**Comment by cramforce** [comment]
Funky :)

Will add.

**Comment by Gregable** [comment]
I'll also add the `cite` attribute from that doc while at it. Thanks for the report.

**Comment by Gregable** [comment]
This is fixed. Should be rolled out to javascript in an hour or so.

**Comment by steffenweber** [comment]
Thanks!
