### ISSUE TITLE
amp-carousel: Autoplay should not trigger high-trust 'slideChange' event

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#20697]
Allows invoking `AMP.setState()` without user action. Note this is currently used on AE's home page.

Noticed this while debugging a runtime error.

/cc @aghassemi @leonalicious

**Comment by choumx** [comment]
Ha, all good it happens. SGTM and thanks for the quick response.

**Comment by leonalicious** [comment]
@choumx @aghassemi sorry for the late reply, was away last few days.

Understand the problem, not too sure how can I achieve the same effect with `amp-animation`, uhmmm....

**Comment by aghassemi** [comment]
@leonalicious toggling visibility is probably the best approach. Having selected and unselected style `dots` and using amp-animation to toggle the right one via `visibility` property of keyframes.

I fully understand this is really not the best way to program. Carousel V2 will have dots built-in and we are also thinking about exposing low-trust setStyle (https://github.com/ampproject/amphtml/issues/13973)  action to help here but both of those likely come after as we need to make this change with high priority.

**Comment by leonalicious** [comment]
okay, I will give it a try and get back to you

**Comment by aghassemi** [comment]
closing in favour of the formal Intent to Deprecate https://github.com/ampproject/amphtml/issues/21171
