### ISSUE TITLE
ad not displaying anymore

### ISSUE THREAD

**Issue by jdelhommeau** [ampproject/amphtml#2071]
I have been working on an ad adaptor for the AppNexus adserver over past weeks.
Everything was working fine, I pull lastest change from upstream and now the ads don't display anymore.

I troobleshooted the issue. Everything works fine, I have no errors, ads are actually loaded on the page, however, I can see that amp adds a "visibility: hidden" to the main iframe, making the ad invisible. Any idea why the css property is being added?

here is a screenshot of the code on the page:

![image](https://cloud.githubusercontent.com/assets/14938467/13108653/c1bde898-d574-11e5-9045-5bcac8891c9a.png)

I assume this is related to some change brought on AMP latest version, but I can't identify what exactly. Any help appreciated.

Best Regards,
julien

**Comment by cramforce** [comment]
Do you want to upload the change somewhere? The ad is hidden until handshake with the ad iframe has been established which must have failed for some reason. The most likely reason is that there was some JS error during load.

**Comment by mkendall07** [comment]
Here are the steps to reproduce:

1) Checkout a clean copy of master and run `gulp`
2) Copy /examples/ads.amp.html into a webserver (not localhost)
3) Install the chrome extension `local-amp-chrome-extension` and enable
4) Navigate to ads.amp.html page

I just did above and uploaded to this page: 
http://client-test.devnxs.net/ads.amp.html

All the ad iframes are set to hidden.

**Comment by cramforce** [comment]
Could you instead test with a local change. I suspect that the postMessage communication is broken when using the chrome extension.

**Comment by jdelhommeau** [comment]
thank you @cramforce .
Not sure how to test with the local change, since the amp.js has other dependencies which point to the cdn.
We followed the instruction on: https://github.com/ampproject/amphtml/blob/master/DEVELOPING.md
Did those changed? It used to work fine with previous version of amp.

**Comment by cramforce** [comment]
Load the file from examples.build/ instead of examples/
There are .max. files of the otherwise same name in there that point to the
local built.
