### ISSUE TITLE
STAMP auto-advance should respect user intent, stop auto-advancing after any user interaction

### ISSUE THREAD

**Issue by townsendmerino** [ampproject/amphtml#20726]
## What's the issue?

If a user wants to stay on a page of the story, currently they can long-tap to pause, but if the user taps to go back or even forward then they intend to control navigation themselves, and auto-advance should stop controlling things.  I would prefer auto-advance to die if the user pauses, but at the least we should kill auto-advance on manual page navigation.

## How do we reproduce the issue?

1) Navigate to https://posts.google.com/bulletin/share/amp/rqgIxd97/bU3OJJ 
2) once the story has advanced click on the left portion of the screen to navigate to a previous page
3) Note that auto-advance is still in control and continues advancing pages.

## What browsers are affected?

Seems to be universal

## Which AMP version is affected?

<script async src="https://cdn.ampproject.org/v0.js" nonce="tiiFUalZJ/UVK+Iv9cVzlg"></script>

**Comment by torch2424** [comment]
Triaging to @newmuis , Feel free to re-assign 😄
