### ISSUE TITLE
Google Business profile that shows on google organic search need to link to AMP Page

### ISSUE THREAD

**Issue by arunke1** [ampproject/amphtml#20720]
Hi,

I was wondering if there was a way we could update our Google Business profile that shows on google searches in both desktop and mobile to link to our AMP home page. I see the option to do so on desktop but not in mobile.

Thanks and Regards
Arun Kumar

## Describe alternatives you've considered

Provide a clear and concise description of any alternative solutions or features you've considered.

**Comment by aghassemi** [comment]
Hi @arunke1 

Folks on the AMP open-source project are separate from Google's use of the project. Please post Google related questions/feature requests on this forum: https://productforums.google.com/forum/#!topicsearchin/webmasters/category$3Aaccelerated-mobile-pages-amp
