### ISSUE TITLE
Issue using amp-analytics with Shadow DOM (2)

### ISSUE THREAD

**Issue by enzo-giancola** [ampproject/amphtml#20736]
Hi,

related to the issue:

https://github.com/ampproject/amphtml/issues/20400

as attached a screen related to the following URL: 

https://rep.repubblica.it/pwa/generale/2019/02/07/news/francia_macron_eliseo_gilet_gialli_m5s_di_maio_conte_mattarella_salvini-218582355/

where `<amp-analytics>` is placed in the same shadow root with `<amp-subcription>`

Is this correct?

Thank you

![ampproject-amphtml_20400](https://user-images.githubusercontent.com/19192170/52472232-12605200-2b93-11e9-948a-2a05fa021333.jpg)

**Comment by aghassemi** [comment]
/to  @zhouyx per her investigation on the related #20400
/cc @dvoytenko

**Comment by zhouyx** [comment]
@enzo-giancola Thank you for the detailed information. I've reopened #20400, Let's track the issue in the old thread. Thank you very much.
