### ISSUE TITLE
amp-list: Validation fails with data-amp-bind-src without src or [src]

### ISSUE THREAD

**Issue by sachin-pt** [ampproject/amphtml#20735]
## What's the issue?

I am using JSX to render amp pages. Therefore I started using XHTML/JSX safe data-amp-bind-* attributes instead of [*]
It works well in most cases except while using it with an amp-list with no 'src' attribute. Consider the following example:

`<amp-list data-amp-bind-src=SOME_URL></amp-list>`

Now it works fine, it's just that the validator fails (in development mode) with the following error:

"The tag 'amp-list' is missing a mandatory attribute - pick at least one of ['src','[src]']"

## How do we reproduce the issue?

1. try using an amp-list without a src and use data-amp-bind-src attribute to bind the url instead of [src] attribute

## Which AMP version is affected?

AMP HTML version: 1901302225410

**Comment by honeybadgerdontcare** [comment]
`src` or `[src]` are required attributes for `amp-list`, could you try using both `src` and `data-amp-bind-src`?

@choumx 	related to #11115

**Comment by sachin-pt** [comment]
yes it works that way, but unfortunately I am using am-list with src (or  [src]) as amp-state. And it seems that the initial src of amp-list can't be amp-state. Example:

`<amp-list src="myState"></amp-state>
 <amp-state id="myState"></amp-state>
`

This would trigger a request to <MY_DOMAIN>/myState instead of picking up the data from "myState"

Therefore, using both `src` and `data-amp-bind-src` are not an option for me. Please do correct me if I am wrong somewhere. Fairly new to AMP!

**Comment by aghassemi** [comment]
@sachin-pt This is currently not supported. We are tackling this for next version of `amp-list`. Please see https://github.com/ampproject/amphtml/issues/20752 for proposal for this.

**Comment by aghassemi** [comment]
closing as dup of https://github.com/ampproject/amphtml/issues/20752
