### ISSUE TITLE
Allow additional @types for use with <amp-subscriptions>

### ISSUE THREAD

**Issue by davidsteeb** [ampproject/amphtml#20747]
## Problem

`<amp-subscriptions>` requires a document to be marked up with a `@type: "NewsArticle"` type declaration. 
To use amp across a site that requires or offers a signup/login and a broader range of content this requires either the documents being marked up as "NewsArticle" while in fact being of a different type, removing the login option across some of the pages while keeping a matching `@type` declaration for the page content or switching between amp and non-amp pages.

## Usecase and Additional Context

We are in the process of adding amp versions of articles to mulitple scientific magazine brand sites. While a standard "Article" can reasonably be marked up as a "NewsArticle", more specific article types or content types in general should go in a different category. For our magazine brands that includes article types like Case Studies, Product Profiles, White Papers, Solutions, Application Notes etc. that would much better fit the more broader "Article" type. In addition we have personal profiles of leading figures in specific scientific fields etc.

## Overall Goal

The goal for changing the current requirements would be to be able to have a complete magazine site built using amp components across all sections of the site while retaining a login and subscriptions based content restrictions/additions including not just articles but everything from startpage, category pages, topics and discussion pages, and maybe even a users profile page.

## Proposed solution

For our specific use case as well as other project we know of and consider for future implementation using amp components a solution would be to add some additional types to be used in combination with `<amp-subscriptions>`. To be able to use a login/amp-subscriptions across a whole site the addition of some generic types would most probably suffice.

For the purpose of our current use cases the appropriate types would include:

* Article
* Person
* Organization
* Webpage
* Product
* SearchResultsPage

Outside of our specific current usecase the article type "Blog" should certainly be on the list.

If there is no specific need to define a list of "allowed types" the requirement to have a specific one could be changed in favour of requiring any valid `@type`, but I do not know enough about the reasons behind the currently implemented requirement to know if that's a good idea.

**Comment by jpettitt** [comment]
cc @dvoytenko

**Comment by jpettitt** [comment]
I'm leaning toward allowing any valid `@type`.  I'll dig into it and report back.

**Comment by dvoytenko** [comment]
@jpettitt a good person to ask about Schema-LD about this is @alaskajim. He was the person who initially designed this markup and he's done a lot of research in Schema-LD nuances.

**Comment by jpettitt** [comment]
After a conversation with @alaskajim we're going to expand the list to allow the following types
```javascript
const ALLOWED_TYPES = [
  'CreativeWork',
  'Article',
  'NewsArticle',
  'Blog',
  'Comment',
  'Course',
  'HowTo',
  'Message',
  'Review',
  'WebPage',
];
````

The fundamental requirement is that we have `CreativeWork` (and we define a many of the common subtypes as also acceptible) and either `isAccessibleForFree` or `publisher` and `productID`.

Note that we allow multiple types so  `["Article", "Person"]` is a valid way to identify an article about a person.

I'll have a PR to update the swg.js library shortly and that will then rull into the `amp-subscriptions` code a couple of weeks after.

**Comment by alaskajim** [comment]
Some additional color on this:

A developer can type their pages as they see fit. However, we need values set for certain properties of CreativeWork and its subtypes (namely, publisher and isAccessibleForFree). So, if the developer has typed a page with something other than CreativeWork or a subtype of CreativeWork, one of these must be added in order for the publisher and isAccessibleForFree properties to be valid. But to be clear, this type can be in addition to another type the developer has chosen for the page.

Similarly, we need a ProductID value to be set, which is a property of the type Product. So we need a type array that includes Product, CreativeWork or one of its subtypes, and (optional) any other type the developer wishes to apply to the page for other purposes.

**Comment by jpettitt** [comment]
@alaskajim Everything in the allowed types list I proposed is a subtype of `Creativework` (apart from `CreativeWork` :-) so that matches your comment.

**Comment by jpettitt** [comment]
The PR was committed to to the swg.js repon a couple of minutes ago. swg.js will release on Monday, and should get rolled into the AMP canary on Tuesday, then hit prod a week later.

**Comment by davidsteeb** [comment]
That was fast, thank you!!

**Comment by hendrul** [comment]
I Can't use NewsArticle [subtypes](https://schema.org/NewsArticle#subtypes) :(

**Comment by jpettitt** [comment]
@hendrul there are hundreds of subtypes of `CreativeWork` and it would be impractical to add them all.   We suggest using `["NewsArticle", "subtypeofNewsAricle"]` as this will work without us having to add a lot of boilerplate to the js file.
