### ISSUE TITLE
amp-bind doesn't work with responsive images of different sizes

### ISSUE THREAD

**Issue by sergionsz** [ampproject/amphtml#20740]
## What's the issue?

amp-bind will incorrectly render responsive images when they have different aspect ratios.

## How do we reproduce the issue?

You can check [this example](https://codepen.io/sergionsz/pen/KJQPEz) with two images. Notice that both are correctly rendered when they're first placed on the page. After changing one image to the other though, they will not take all the available space (as responsive images should do).

1. Take the code on the [example for dynamically changing the src of an image](https://ampbyexample.com/components/amp-img/#dynamically-changing-the-src)
2. Change it so that images have different aspect ratios
3. Press the button to change the image
4. Verify that images are indeed not rendered correctly

## What browsers are affected?

Tested in Chrome 71 and Firefox 65 on MacOS Mojave

## Which AMP version is affected?

Using amp version 1901302225410

**Comment by aghassemi** [comment]
Thanks @sergionsz, agreed but for now, per documentation (https://github.com/ampproject/amphtml/blob/master/extensions/amp-bind/amp-bind.md#element-specific-attributes)

> When binding to [src], make sure you also bind to [srcset] in order to make the binding work on cache.

Also raised under https://github.com/ampproject/amphtml/issues/19364 , tagging as duplicate

**Comment by aghassemi** [comment]
Closing as dup of https://github.com/ampproject/amphtml/issues/19364

**Comment by sergionsz** [comment]
@aghassemi 

Thanks for your reply!

I updated my previous example [into a new pen](https://codepen.io/sergionsz/pen/YBeryr) to bind to the srcset as well, both with and without the attribute for the width of the image. It's still not rendering the images correctly.

Do you mind taking a look?

**Comment by aghassemi** [comment]
Hi @sergionsz, I am missing how to repro the bug. Image changes for me just fine. Could you post repro steps and maybe a screenshot?

**Comment by sergionsz** [comment]
Hi @aghassemi 

Yeah, in fact images change. However, as they change, they don't fill the entire width of the container (as they should, for being responsive images. That's why I included two examples, so that you could see how it should look after the change. I just updated [my latest pen](https://codepen.io/sergionsz/full/YBeryr) to make the background red, so that you can see more easily the issue:

How it should look:
<img width="507" alt="screen shot 2019-02-13 at 2 34 34 pm" src="https://user-images.githubusercontent.com/4761560/52738895-aec49300-2f9d-11e9-9609-0e4ad072a399.png">

How it actually looks after change:
<img width="501" alt="screen shot 2019-02-13 at 2 36 21 pm" src="https://user-images.githubusercontent.com/4761560/52738910-b6843780-2f9d-11e9-85c8-196336f6934a.png">

How it should look:
<img width="500" alt="screen shot 2019-02-13 at 2 37 08 pm" src="https://user-images.githubusercontent.com/4761560/52738928-c1d76300-2f9d-11e9-9224-a59d1dcdfd99.png">

How it actually looks after change:
<img width="502" alt="screen shot 2019-02-13 at 2 36 32 pm" src="https://user-images.githubusercontent.com/4761560/52738938-c7cd4400-2f9d-11e9-97bb-35c9c35cf601.png">

Please let me know if I'm missing something.

Thank you!

**Comment by aghassemi** [comment]
@sergionsz changing `width` and `height` with `amp-bind` forces the layout to become `fixed`. Ideally it should have updated the `sizer` and kept it responsive. /to @choumx
