### ISSUE TITLE
amp-instagram resizing

### ISSUE THREAD

**Issue by jesse** [ampproject/amphtml#2076]
Any plans to update `amp-instagram` embeds so they resize themselves based on the embed content, similar to the [`amp-twitter` behavior](https://github.com/ampproject/amphtml/blob/9bca86ebaaf754f720a086b47f15f41fd5df38d7/extensions/amp-twitter/0.1/amp-twitter.js#L47)?

**Comment by cramforce** [comment]
It isn't really needed, except for caption-support.

**Comment by src-code** [comment]
This is a dupe of #5032.
