### ISSUE TITLE
Visual Diff: Allow running some tests synchronously

### ISSUE THREAD

**Issue by torch2424** [ampproject/amphtml#20781]
**Feedback from the visual diff workshop**

Due to factors such as #20671 , it may be a good idea to allow interactive tests to be run synchronously, in relation to other tests. (only Tests in the same file should be fine imo).

**Comment by danielrozenberg** [comment]
@torch2424 is this still a feature request? Or did #20783 solve the underlying issue?

**Comment by torch2424** [comment]
Oh I think we can close this 😄
