### ISSUE TITLE
Visual Diff: Allow `console.log()` in interactive_tests

### ISSUE THREAD

**Issue by torch2424** [ampproject/amphtml#20780]
**Feedback from the visual diff workshop**

`console.log` / `console.error` doesn't work.

Got a solution working with:

```
const log = (string) => {
  process.stdout.write(' \n\n');
  process.stdout.write(string);
  process.stdout.write(' \n\n');
};
```

**Comment by danielrozenberg** [comment]
I think that `log('verbose', ...)` in `helpers.js` should be good enough :) I want to make sure that console log messages aren't printed on Travis, so the verbose log should work for that task
