### ISSUE TITLE
Integration `test-amp-skimlinks` flaking/failing on Firefox

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#20796]
https://travis-ci.org/ampproject/amphtml/jobs/491955295
https://travis-ci.org/ampproject/amphtml/jobs/491945157

```
DESCRIBE => amp-skimlinks
  DESCRIBE => Basic features
    DESCRIBE =>  
      IT => Should send NA-tracking on non-merchant link click 
        ✗ Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
●●●●●●○○○●●●●●○○○○●○●●●●○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●○●●●●●●●●●●●●●●○○○○○●○●●○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○●○○○○○○○○○○○○○○○○○○○○○○○○○○○○●○●○●●○○○●●●○○○○○○○○○○○○○○○○○○●○○
[04:11:08] Firefox 65.0.0 (Windows 10.0.0): Executed 134 of 517 (Skipped 383) 1 FAILED
```

/to @alabiaga 
/cc @slocka @lepunk @choumx @ampproject/wg-infra

**Comment by alabiaga** [comment]
cc\ @slocka

**Comment by slocka** [comment]
@alabiaga @choumx I can't reproduce the flakiness on my local, is there a way for me to run the tests on saucelabs? (I don't have an account).

@alanorozco is this failure just a one-off or has it been a recurrent thing? Do you think using `.retryOnSaucelabs()` is a valid approach?

**Comment by alabiaga** [comment]
You can sign up for a free account and run it per instructions here:

https://github.com/ampproject/amphtml/blob/82c54c298478f56338d9f147c5a3566232d48e6c/contributing/TESTING.md#testing-on-sauce-labs

**Comment by slocka** [comment]
@alabiaga I still haven't managed to gain access to saucelabs, I am blocked by this issue https://github.com/ampproject/amphtml/issues/20882. Could you have a look at it please?

**Comment by alanorozco** [comment]
@slocka Recurring, it fails constantly. Retrying does nothing.

**Comment by alabiaga** [comment]
@slocka Feel free to work on extracting the link rewriter logic to its own extension and not let this block you. I think the fact that the tests can still run and pass in other browsers and that the tests failing in particular is related to browser timeout and setup doesn't make me concerned about the functionality of the extension itself not working correctly. I'll take a look at testing this in sauce labs myself when i have the bandwidth. Thanks
