### ISSUE TITLE
I2I: Experiment with priority hints to load AMP scripts with high priority

### ISSUE THREAD

**Issue by prateekbh** [ampproject/amphtml#20804]
## Summary
AMP documents use `async` HTMLScriptElements tags to load AMP runtime and AMP extensions, this allows AMP scripts to download and parse without blocking the main thread. 
By default browsers load all `async` HTMLScriptElements with a **low** priority, which means assets like fonts and their stylesheets might interrupt these scripts with a higher priority.

To prevent this, in AMP we add a `<link rel=prefetch href=v0.js />` to boost the priority of our AMP runtime script to high.

We want to move away from this `<link rel=prefetch` workaround and also boost the priority of the rest of the HTMLScriptElements.

We want to do an AB experiment which would use [priority hints](https://github.com/WICG/priority-hints) to indicate the requested **high** priority of critical HTMLScriptElements.

This experiment will remove the prefetch for AMP runtime `v0.js` and use attributes `importance=high` on all the AMP HTMLScriptElements.

## Scope of this experiment
We want to do this experiment on a small amount of traffic served from AMP CDN. This'll allow us to alter the script tags without developers making any modifications.

## Design document
https://docs.google.com/document/d/11QzSODVge_BzjlCqfYWWW5ar2tEcOSa7XfUhF0pMxRk?usp=sharing

**Note:** AMP scripts however are mostly present in the HEAD section of the document and the only thing which can actually intercept in loading them are fonts stylesheets.

/cc @ampproject/wg-approvers

**Comment by cramforce** [comment]
Is `importance` shipping in Chrome? Would this experiment be Chrome only?

s/prefetch/preload

**Comment by prateekbh** [comment]
This feature is right now only present behind a flag in chrome: https://www.chromestatus.com/feature/5273474901737472

Yes this will be a chrome only experiment.

**Comment by addyosmani** [comment]
Priority Hints are now available as an Origin Trial AMP can [register for](https://developers.chrome.com/origintrials/#/trials/active). You might find this useful for experimenting at scale without relying on our flagged implementation.  

![image](https://user-images.githubusercontent.com/110953/52661673-629f2300-2eb7-11e9-86f7-f41000df9bd0.png)

cc @yoavweiss fyi

**Comment by prateekbh** [comment]
We initially saw a performance dip when using priority hints instead of link prefetch. 
@erwinmombay and @jridgewel can provide more solid results once the release performance dashboard has the complete data

**Comment by shubh28tyagi** [comment]
Hi Guys, did we found any solution for the above mentioned problem?
