### ISSUE TITLE
Closing a tweet embedded in a story that had a video playing doesn't stop it.

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#20806]
If I open an embedded tweet and play the video, closing the tweet to resume the story navigation should also stop its media. Is this something we can do, or that's supported by `amp-twitter`?

**Comment by gmajoulet** [comment]
Additionally: if I play the video and click the fullscreen button, exit the fullscreen button, I get stuck into a mode where the tweet is full bleed, which is a dead end.

**Comment by aghassemi** [comment]
(drive by comments as I was triaging other issues)

amp-story would need to call `schedulePause` on  the overlay after closing It. Runtime handles the rest (for elements that can be paused like amp-youtube, it will be paused. For elements like amp-twitter, the iframe will be removed)

**Comment by Enriqe** [comment]
Oh that's really useful! thanks @aghassemi!
