### ISSUE TITLE
[Validator] Bail out validation for docs that look like optimized AMP

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#20813]
When the validator discovers a document that looks like optimized AMP, we should declare it invalid, but instead of a bunch of errors, show one message explaining that the document looks like optimized AMP.

**Comment by honeybadgerdontcare** [comment]
1) Why?

Either it's valid or it's not and the publisher should know why it's invalid so they can fix their transformers or file bugs against whomever's transformer they're using so it'll generate valid Transformed AMP.

2) What constitutes "looks like optimized AMP"?

Transformed AMP is generated by the open sourced transformers and at each version release those are valid. What makes something "optimized AMP"?

**Comment by cramforce** [comment]
amp-toolbox-optimizer and the AMP Cache currently create invalid AMP. I
know the eventual plan is to fix that, but currently this is very confusing
to people. Better to give an explicit error message instead of dozens of
validation errors.

**Comment by Gregable** [comment]
Now that the validator has a mode for understanding optimized AMP, this is obsolete and we should fix specific issues for mismatch between optimized AMP and validation.
