### ISSUE TITLE
Feature request: support no-looping on story pages background audio 

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#20812]
From Ariel G.:

> amp-story tag has a background-audio attribute. Background audio always loops.
> We would like to build a STAMP-based audio experience where each page has a snippet of audio. We do not want it to loop as that would ruin the experience.
> 
> Could we have some way to set up non-loopable background audio?

**Comment by newmuis** [comment]
To be clear: this is non-loopable audio at the `<amp-story>` level?

**Comment by arielg99** [comment]
I need non-loopable background audio at the page level. It does not necessarily have to be an attribute of <amp-story>

**Comment by newmuis** [comment]
For non-loopable audio at the page level, you can use `<amp-audio>` with the `autoplay` attribute and no `loop` attribute.

**Comment by gmajoulet** [comment]
Thanks @newmuis.

Additional details if anyone else wants to use this solution: `<amp-audio>` has to be within the `<amp-story-page>` and contained in an `<amp-story-grid-layer>` tag, like other elements. It also has to have a `<amp-audio layout="nodisplay">` attribute.
