### ISSUE TITLE
Fail: Form clear on submit-success Reference #7368

### ISSUE THREAD

**Issue by 88kbbq** [ampproject/amphtml#20824]
Viewing documentation and issue #7368, the clear action cannot be invoked. Documentation needs improvement for amp-from clear action: https://www.ampproject.org/docs/reference/components/amp-form

**Comment by 88kbbq** [comment]
Also not helpful. Need to clear a form is submit is successful.
https://ampbyexample.com/components/amp-form/#reset-clear-form-input

**Comment by 88kbbq** [comment]
I'm anticipating some dup question backlash, but the documention listed above are conflicting. 

This issue is important because if the form is not cleared after successful submit, the form allows multiple submissions for every click, thus triggering SMTP server or e-mail relay issues with some form submisssions. 

And since AMP doesn't support Recaptcha, we need a solution.

**Comment by aghassemi** [comment]
@88kbbq Recaptcha is almost ready #2273, @torch2424 when do you think Recaptcha will be ready in prod?

**Comment by aghassemi** [comment]
/to @cvializ to answer the form related concerns here.

**Comment by cvializ** [comment]
Hi @88kbbq , the `clear` action is an [AMP Action and Event](https://www.ampproject.org/docs/interaction_dynamic/amp-actions-and-events) exposed by `amp-form`. To use the `clear` action, you must include it in an `on` attribute in response to an event. So to clear a form on the `submit-success` event, you can write some markup like this.

```html
<form id="my-form" on="submit-success: my-form.clear" ...>
  <!-- ... -->
</form>
```

To your second point, the amp-by-example example has a bug, but if you were to implement an form yourself with the CSS, it would work.

```css
.amp-form-submit-success.hide-inputs > input { display: none; }
```

**Comment by torch2424** [comment]
@aghassemi @88kbbq All updates in Recaptcha are at #2273 . 😄 Feel free to read through there (though the SSL issue I mention at the end, will be fixed as it is being rolled out slowly over this week).

Considering being completely read in PROD. I would say very soon. Currently we are starting origin trials, and collecting feedback (which has all be positive so far 👍 )

**Comment by aghassemi** [comment]
Closing per comments above. Feel free to reopen if needed.

**Comment by 88kbbq** [comment]
Hi @cvializ Thank you for replying. Sorry, I'm been away on biz but had a chance to implement your suggestions:
```
<form id="my-form" on="submit-success: my-form.clear" ...>
  <!-- ... -->
</form>
```
This action also clears the `<div submit-success>` and the message that should appear within this div after successful submission, but since `submit-success` must appear inside the `form` element, kinda stuck here. Suggestions? 

CSS didn't work but I get the idea, try to figure something out.
