### ISSUE TITLE
Support `collapse` message for `amp-iframe` and `amp-video-iframe`

### ISSUE THREAD

**Issue by nerdbeere** [ampproject/amphtml#20828]
I'd like to discuss a feature that would allow to automatically hide `amp-iframe` and `amp-video-iframe` under certain circumstances.

## Our use-case
At [glomex](https://www.glomex.com/) we provide a video player to our customers (publishers) and make it very easy for them to get premium content to their pages.

Usually the publishers add our embed code to their article when they found a fitting video. Recently we introduced a new feature that allows the publishers to always have the code in their article which enables us and them to fill that spot automatically when there's video content available.

This means we need to be able to automatically hide/show the iframe when no content is configured for this article because otherwise the user would just see an empty player.

Naturally our publishers would like to have this feature on their amp pages as well. As it turns out though, this is not so easy to implement.

## Our (hacky) solution
We use `amp-iframe` `resizable` to resize the iframe from within when there is no content configured. The minimum allowed value for height is `100px` so we resize the iframe to `100` and then use the following CSS rule on the outside to hide the iframe:

```
amp-iframe[height="100"] {
  display: none;
  visibility: hidden; 
}
```

*Note* that this only works in cases where the player is embedded below the fold meaning that it must not be in the initially visible area of the screen.

## Proposal
Everything boils down to the generic use-case:  
**Only show `amp-iframe` when content is available**

Our suggestion is to introduce a new property that would:
 - initially hide the iframe
 - show the iframe once amp receives a `show-me` message via `postMessage` from the iframe

**Comment by torch2424** [comment]
Triaging to @alanorozco , feel free to re-assign 😄

**Comment by alanorozco** [comment]
> initially hide the iframe

Can't do that, per AMP's no-content-resize invariant, which is critical to our UX guarantees. We can consider doing this IFF the element is not in the viewport, similar to `amp-auto-ads`, but hiding and showing it naïvely is off the table.

For a feature like this `amp-video-iframe` would be more suitable than `amp-iframe`, and would probably be integrated in the overall integration API so this can be a general suitable use-case and not distributor-specific.

**Comment by aghassemi** [comment]
We can do something similar to `amp-ad` where there is the concept of `collapse`. We could support an additional `collapse` message from iframes. Runtime already has a `collapse` method that handles the whole eligibility logic.

**Comment by aghassemi** [comment]
related (almost dup) #21397

**Comment by cathyxz** [comment]
I did some research into this. What `<amp-ad>` has isn't exactly `collapse`, but `embed-resize`. It allows you to try to resize the ad, following AMP's constraints (e.g. no resizing within the viewport etc). So you can get it to "collapse" by resizing it to height zero. 

For `<amp-iframe>`, the way to do this is https://amp.dev/documentation/examples/components/amp-iframe/#resizable-iframe.
