### ISSUE TITLE
Unknown ad type "jubna"​​ - Ad Network - Supported embed types

### ISSUE THREAD

**Issue by anshuman91** [ampproject/amphtml#20829]
### What's the issue?

Yesterday Jubna Ad implementation was approved by your team. And pull request of Jubna AMP support has been merged to amphtml master branch. Jubna AMP code is working in test (local) server but in production when I used `<amp-embed>` it throws error `Unknown ad type "jubna"`. 

Here I am attatching screenshots of all errors. 
![screenshot 2019-02-13 at 6 44 15 pm](https://user-images.githubusercontent.com/3455354/52715391-5eabf780-2fc2-11e9-9ba5-ea9db2e02cd4.png)
![screenshot 2019-02-13 at 6 43 53 pm](https://user-images.githubusercontent.com/3455354/52715393-5f448e00-2fc2-11e9-8b07-9b53c6dd6390.png)
![screenshot 2019-02-13 at 5 54 02 pm](https://user-images.githubusercontent.com/3455354/52715394-5f448e00-2fc2-11e9-9708-702510c9fc4b.png)
![screenshot 2019-02-13 at 5 53 53 pm](https://user-images.githubusercontent.com/3455354/52715395-5f448e00-2fc2-11e9-91b3-96ffc757178f.png)
![screenshot 2019-02-13 at 5 53 44 pm](https://user-images.githubusercontent.com/3455354/52715398-5fdd2480-2fc2-11e9-87fb-671d50b5a7e7.png)

### What browsers are affected?
All browsers

**Comment by anshuman91** [comment]
Also, Jubna is not showing as supported Ad Network in amphtml official website. Why?
https://www.ampproject.org/docs/reference/components/amp-ad

**Comment by cathyxz** [comment]
I think you're referring to https://github.com/ampproject/amphtml/pull/20109. It generally takes two weeks for PRs merged into master to make it to production. Please see [Determining if your change is in production](https://github.com/ampproject/amphtml/blob/e52c0ce99f4b06fae7c8af3433735fc0024c54c1/contributing/release-schedule.md#determining-if-your-change-is-in-production) for more details and follow the [github release issues](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) and our #release channel on [slack](https://amphtml.slack.com).

**Comment by anshuman91** [comment]
> I think you're referring to #20109. It generally takes two weeks for PRs merged into master to make it to production. Please see [determining if your change is in production](https://github.com/ampproject/amphtml/blob/e52c0ce99f4b06fae7c8af3433735fc0024c54c1/contributing/release-schedule.md#determining-if-your-change-is-in-production) for more details and follow the [github release issues](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) and our #release channel on [slack](https://amphtml.slack.com).

Thanks @cathyxz for updating us.
