### ISSUE TITLE
Versioned, cache URL for ww.js is uncompressed?

### ISSUE THREAD

**Issue by alexanderbartels** [ampproject/amphtml#20827]
## What's the issue?

We've build a new Site with Google AMP and run a lighthouse Audit. A file "ww.js" was served without text compression. Result below: 

![image](https://user-images.githubusercontent.com/522396/52700217-d7d22d00-2f77-11e9-8b55-0108d3819197.png)

The file ww.js should be served with compression.

## How do we reproduce the issue?

Our go-live is next week. So i can provide a URL at Monday. 

But it seem like, that your linked showcase "https://www.vox.com/platform/amp/science-and-health/2017/7/25/16019892/solar-eclipse-2017-interactive-map" has a similar problem. 

other examples:
* https://mobil.stern.de/amp/lifestyle/leute/chris-toepperwien--ueberraschendes-liebes-posting-des-dschungelstars-8577480.html
* https://www.huffingtonpost.de/amp/entry/russland-affare-warum-trumps-ex-wahlkampfmanager-erneut-in-den-fokus-ruckt_de_5c63c910e4b07115222b596c/?ec_carp=7887075255891305912

1. open URL in Chrome
2. open dev tools
3. go to Audits Tab
4. Perform an Performance-Audit
5. Results unter "Opportunities" / "Enable text compression"

## What browsers are affected?

All browsers => must be a server configuration issue.

**Comment by torch2424** [comment]
cc @aghassemi

**Comment by jridgewell** [comment]
Strange, I get the proper compressions:

```bash
$ curl 'https://cdn.ampproject.org/ww.js' -H 'accept-encoding: gzip, deflate' -Is | grep content-encoding
content-encoding: gzip

$ curl 'https://cdn.ampproject.org/ww.js' -H 'accept-encoding: gzip, deflate, br' -Is | grep content-encoding
content-encoding: br

$ curl 'https://cdn.ampproject.org/rtv/011902081532110/ww.js' -H 'accept-encoding: gzip, deflate' -Is | grep content-encoding
content-encoding: gzip

$ curl 'https://cdn.ampproject.org/rtv/011902081532110/ww.js' -H 'accept-encoding: gzip, deflate, br' -Is | grep content-encoding
content-encoding: gzip
```

**Comment by choumx** [comment]
I also can't reproduce this on mobil.stern.de or other examples.
