### ISSUE TITLE
Reduce the number of getBoundingClientRect() for amp-story-page

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#20832]
We are calling `getBoundingClientRect()` on a number of places inside the `amp-story` codebase, when we could store the `DOMRect` value in the `amp-story-store-service` and avoid doing the same kind of expensive operations repeatedly.

**Comment by gmajoulet** [comment]
Update:
The runtime already does this for us, we could replace all our `pageEl.getBoundingClientRect()` calls with `pageEl.getLayoutBox()`
