### ISSUE TITLE
Decouple amp-user-notification from external services  

### ISSUE THREAD

**Issue by montmanu** [ampproject/amphtml#2083]
Currently, the `amp-user-notification` component depends on the `data-show-if-href` and `data-dismiss-href`. Ideally, the `amp-user-notification` component could be implemented without supporting external services. For example, when used in combination with the `amp-access` component, the `authorization` endpoint could serve as the `data-show-if-href` and the `amp-access` expressions could control presentation.

**Comment by dvoytenko** [comment]
@montmanu According to https://github.com/ampproject/amphtml/blob/master/extensions/amp-user-notification/amp-user-notification.md both `data-show-if-href` and `data-dismiss-href` are optional. For instance, see this example: http://output.jsbin.com/vexiti
