### ISSUE TITLE
amp-social-share: Facebook/LinkedIn/Twitter/G+ fail with Firefox Focus on iOS

### ISSUE THREAD

**Issue by yawpitch** [ampproject/amphtml#20830]
Interesting issue under Mobile Safari on iOS 12.1.4 (and likely earlier): the Facebook, LinkedIn, Twitter, and G+ links all fail, while Pinterest, Tumblr, Email, and WhatApp all work) when FireFox Focus is installed and **Settings > Safari Integration** is enabled, _even_ if the **Settings > Tracking Protection > Block Social Trackers** configuration setting is _disabled_. Oddly when that setting is disabled Firefox Focus itself _will_ allow all four of those providers.

Steps to Reproduce:
1. Install Firefox Focus on the device
2. Enable Settings > Tracking Protection > Block Social Trackers (and both settings above)
3. Enable Settings/Safari Integration
4. In Mobile Safari browse to https://ampbyexample.com/components/amp-social-share/#basic-usage and try the above links.
5. In Firefox Focus disable Settings > Tracking Protection > Block Social Trackers.
6. In Firefox Focus browse to the same link, all social share providers should now work.
7. Attempt again in Mobile Safari.

Disabling **Settings/Safari Integration** seems to allow these providers to work once more.

Can't say this is an actionable bug, but it would be nice if there were some sort of graceful fallback, rather than just dead links with a visible icon.

**Comment by torch2424** [comment]
Triaging to @aghassemi , feel free to re-assign 😄

**Comment by aghassemi** [comment]
@yawpitch there are pure iframe's to their services and looks like they fail to render when tracking is disabled. We could look into whether we get any signals that they failed to render and fall back to AMP's fallback mechanism ( https://www.ampproject.org/docs/design/responsive/placeholders  )

`amp-twitter` does this already, I haven't tested but twitter does send a signal and we listen too (not sure if they are sending it in this case). Here is snipper to to try:
```
<amp-twitter width="390"
  height="330"
  layout="responsive"
  data-tweetid="855178606556856320">
  <blockquote placeholder>
    <p>What are 5 common misconceptions people often have about AMP? Find out on today&#39;s installment of Amplify:
      <a href="https://t.co/kaSvV8SQtI">https://t.co/kaSvV8SQtI</a>
      <a href="https://t.co/Cu9VYOmiKV">pic.twitter.com/Cu9VYOmiKV</a>
    </p>&mdash; AMP Project (@AMPhtml)
    <a href="https://twitter.com/AMPhtml/status/855178606556856320">April 20, 2017</a>
  </blockquote>
  <div fallback>
    An error occurred while retrieving the Tweet. It might have been deleted.
  </div>
</amp-twitter>
```

if `An error occurred while retrieving the Tweet. It might have been deleted.` is displayed, then it is working.

**Comment by yawpitch** [comment]
That fallback behavior is exactly what I'd hope for; if a provider isn't functional then I'd rather their button not even appear on my site.

On a tangent it would also be great to suppress providers like **sms** on clients (ie desktop) where they'll be non-functional.

Having buttons on a site remain present but be functionally inactive is incredibly annoying, and would be more so to those with accessibility concerns.
