### ISSUE TITLE
Bundle size checks for extensions

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#20843]
Would be nice to have ~~non-blocking~~ status checks for PRs that change extension bundle sizes. 

May have helped catch bugs like #20842 earlier and saved users tens of KB per page view over a span of months!

**Comment by rsimha** [comment]
This is a companion issue to  #21275 / https://github.com/ampproject/amp-github-apps/issues/142 are fixed.

**Comment by rsimha** [comment]
Filed https://github.com/ampproject/amp-github-apps/issues/271 to track this separately

**Comment by danielrozenberg** [comment]
This is now implemented!
