### ISSUE TITLE
Prevent amp-user-notification from initializing when amp-access expressions are false

### ISSUE THREAD

**Issue by montmanu** [ampproject/amphtml#2085]
Currently, the `amp-user-notification` component initializes regardless of whether or not it is displayed. For example, `amp-user-notification` components nested within a component hidden with `amp-access-hide` initialize even if the amp-access expression is false. This creates an issue when attempting to conditionally show one of several possible notifications - the first is initialized, but not visible, so impossible to dismiss and none of the subsequent notifications are presented to the user. See https://gist.github.com/montmanu/a45aafd6b7f9f5c600b7 for example markup that attempts to show a notification based on the response from the `amp-access` component's `authorization` endpoint.. the desired result can be achieved, but only by abusing the `amp-mustache` component to prevent the initialization.

**Comment by dvoytenko** [comment]
@montmanu It seems like my previous advise on this didn't reach you. Apologies. At this point `amp-access` and `amp-user-notification` don't mesh very well for the purposes of "growl". Quite simply, `amp-user-notification` is intended to be an independent notification component driven by separate signals. It's also a show-one-time component. It's main raison d'etre is "analytics uses cookies" type of messages.

However, you don't need it for "growl". Please take a look at the example here: https://github.com/ampproject/amphtml/blob/master/examples/article-access.amp.html#L235

A simple section that's only shown when your "growl" conditions need it will do. You can style it as you need, e.g. using "position:fixed" or other methods. You can give it a "dismiss" button. Use templates. And so on.  Please take a look at this example and let me know if this satisfies your needs.

**Comment by dvoytenko** [comment]
@montmanu I also noticed that you have somewhat repetitive templates, so I wanted to bring this up. You can show "growl" at different `v` counts in two ways: via `OR` expression or by returning a `showGrowl: true` property from the authorization endpoint.

An example for `OR-v`:
```
<section class="growl" amp-access="v = 4 OR v = 7 OR v = 9 or v = 10">
  You are viewing document {{v}}.
</section>
```
An example for `showGrowl: true`, assuming you return this property in your authorization response:
```
<section class="growl" amp-access="showGrowl">
  You have {{documentsLeft}} documents left.
</section>
```

Mustache templates are somewhat restrictive, but they still allow some breadth of expressions with boolean values that can be returned and evaluated using `{{#value}}` syntax. You can also return some very limited content (e.g. a message) in the authorization response, but I'd recommend to be very careful with this option.

**Comment by dvoytenko** [comment]
Also, a combination of `amp-access` expressions and mustache templates can be helpful:

```
<section class="growl" amp-access="showGrowl">
  <div amp-access="v &lt=; 4">
    <template amp-access-template type="amp-mustache">
      You are reading article {{v}}.
    </template>
  </div>
  <div amp-access="v &gt;= 9">
    <template amp-access-template type="amp-mustache">
      Getting close. You are reading article {{v}}.
    </template>
  </div>
  <div amp-access="v = 10">
    That's it. This is the last. No template even needed.
  </div>
</section>
```

**Comment by montmanu** [comment]
yeah, this is essentially where left off using the templates to prevent the user-notification component from initializing. Will look into the `tap:#id.hide` action for building out a growl-like component instead of using the amp-user-notification component. thanks!
