### ISSUE TITLE
Setting amp-analytics parameters with ${ampState(___)} is broken in PWA

### ISSUE THREAD

**Issue by mattwomple** [ampproject/amphtml#20853]
## What's the issue?

When an AMP page utilizing **amp-analytics** is loaded in a PWA, setting an analytics parameter value via `${ampState(___)}` fails. The console reports `No ampdoc found for [object HTMLHtmlElement]`.

## How do we reproduce the issue?

I have created a minimal example that demonstrates the issue. When you click the "Send Analytics" button on the AMP page, `favnum` in `extraUrlParams` is set correctly (see the collect beacon in network requests). When you click the same button in the PWA, `favnum` is blank and the console reports `No ampdoc found for [object HTMLHtmlElement]`.

- AMP: https://android.cmphys.com/temp/analytics-setstate-amp.html
- PWA: https://android.cmphys.com/temp/analytics-setstate-pwa.html

## What browsers are affected?

The following browsers have been tested and both exhibit the same behavior:

- Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36
- Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1

## Which AMP version is affected?

1902081532110

**Comment by torch2424** [comment]
Triaging to @zhouyx , feel free to re-assign 😄

**Comment by jerimiahwelch** [comment]
Any update on this? This is affecting PWA enhanced ecommerce reporting and A/B testing reporting in Google Analytics for us.

**Comment by zhouyx** [comment]
Thank you for filing the issue and providing the examples.

Seem like runtime fails to find the ampdoc for win.document. 

https://github.com/ampproject/amphtml/blob/18460ff4adc9110b6eb66014b03038f9d473fc9f/src/service/url-replacements-impl.js#L559-L563

@choumx could you please take a look. Thank you
FYI: we have a manual test page https://github.com/ampproject/amphtml/blob/master/test/manual/amp-analytics/analytics-shadow.html for easier local testing. I copied @mattwomple's example https://android.cmphys.com/temp/analytics-setstate-amp.html to test/manual/amp-analytics/analytics-shadow-root-1.html and reproduced locally.
