### ISSUE TITLE
AMP project reference page fails AMP validation

### ISSUE THREAD

**Issue by zipswich** [ampproject/amphtml#20855]
Go to page:
https://www.ampproject.org/docs/reference/components/amp-addthis
Expected: all AMP project pages are properly AMplified.
Actual Result: the page fails AMP Validation.

**Comment by cathyxz** [comment]
This is because of the section: 

```
Check out our YouTube video for step-by-step instructions:
<iframe width="560" height="315" src="https://www.youtube.com/embed/BSkuAB4er2o" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

In [add-this.md](https://github.com/ampproject/amphtml/blame/339d8b67c212e0726bc2d5a1cfbfbe209571cb06/extensions/amp-addthis/amp-addthis.md#L135). It can be fixed by using `<amp-iframe>` or `<amp-youtube>` instead.
