### ISSUE TITLE
Consent prompt UI iframe improvement

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#20858]
Based on feedback from CMP, we want to put `allow-same-origin` to the CMP prompt UI iframe. 

The restriction is that the iframe src origin must NOT be same as the doc origin. Please refer to the amp-iframe origin policy [here](https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md)

Logic should look like
```
if origin different : 
  sandbox = "allow-scripts allow-same-origin"
else:
  sandbox = "allow-scripts"
```

**Comment by hrkhal** [comment]
@zhouyx picking this up.

**Comment by torch2424** [comment]
Closing this as it was merged 😄

**Comment by ptrickney** [comment]
@zhouyx @hrkhal it looks like there's an issue with feature now. We're trying to set up a CMP integration and after pulling down the latest commits I'm getting an allow-same-origin error because the allow-same-origin sandbox attribute is not being added to the iframe. We've also tried other existing CMP implementations and see the same error when they were working before.

`**Failed to read the 'cookie' property from 'Document': The document is sandboxed and lacks the 'allow-same-origin' flag.**`

Not sure exactly what change caused the issue. We've done some debugging this is what we've found below:

```
createPromptIframe_() {
    const iframe = this.parent_.ownerDocument.createElement('iframe');
    const sandbox = ['allow-scripts', 'allow-popups'];

// iframe.src always equals an empty string because the iframe is created just above
    const allowSameOrigin = this.allowSameOrigin_(iframe.src); 
```

```
  allowSameOrigin_(src) {
    const urlService = Services.urlForDoc(this.parent_);

// When src is an empty string (which would be everytime given above logic) urlService.parse(src) returns the parentUrl
// My initial thought is that some logic changed here to return the parentUrl when it receives an empty string 
// but couldn't find anything
    const srcUrl = urlService.parse(src);

// This gets the parent URL
    const containerUrl = urlService.parse(this.ampdoc_.getUrl());

// because now both srcUrl and containerUrl use the parent URL the origin is always the same, so this always returns false
    return srcUrl.origin != containerUrl.origin;
  } 
```

And to be sure, I'm testing on my localhost with my PromptUI iframe URL on a hosted domain, so they are definitely different origins.

**Comment by zhouyx** [comment]
@ptrickney Thanks for reporting. Could you share me an example or the setting for me to reproduce. 

Are you using the `promptUI` and an `<amp-iframe>` component instead of `promptUISrc`?

**Comment by ptrickney** [comment]
@zhouyx thanks for the quick response. Sorry for the confusion, I'm trying to add a new CMP to the built-in CMP list, so I'm not setting the iframe directly, it's coming from the promptUISrc in the CMP_CONFIG.

But I was able to repeat this error with existing CMP types, e.g. type=opencmp and type=SourcePoint

Here's the example _ping_ that works unless you change the promptUISrc in the CMP_CONFIG (in cmp.js) to a different iframe source.

```
<amp-consent id='ABC' layout='nodisplay' type='_ping_'>
        <script type="application/json">
          {
            "consents": {},
            "postPromptUI": "postPromptUI",
            "clientConfig": {
              "CMP_id": "test_id",
              "other_info": "test_info"
            }
          }
        </script>
        <div id="postPromptUI">
          Post Prompt UI
          <button on="tap:ABC.prompt(consent=_ping_)" role="button">Manage</button>
        </div>
      </amp-consent>
```

**Comment by zhouyx** [comment]
Indeed, this is a bug that's recently introduced 😢 
I had #29061 to fix this.
