### ISSUE TITLE
Additional constant height for responsive layout

### ISSUE THREAD

**Issue by sparhami** [ampproject/amphtml#20851]
# Background

In some cases, we want to lay out something that is mostly responsive, but has some additional constant height component to the height of the element. Two cases this has come up so far are for carousel and for ads. Both boil down to essentially the same use case: you have a responsive portion (e.g. an image) that should maintain an aspect ratio as well as some fixed height portion.

For ads, the fixed height portion would be something like an "Ad" label above a responsive ad. For carousel, this would be something like one or two lines of caption text below responsive images. This is illustrated by the following diagram.

```
      large                    small
|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|       |‾‾‾‾‾‾‾‾‾‾‾‾‾‾|
|                |       |              |
|                |       |______________|
|________________|       | some captio… |
| some captions  |        ‾‾‾‾‾‾‾‾‾‾‾‾‾‾
 ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
```

# Proposed Implementation

The responsive layout could be extended to have an `additional-height` attribute that would allow adding the additional, non-responsive height. This might look like:

```html
<amp-carousel layout="responsive" width="400" height="300" additional-height="1.5em">
  ...
</amp-carousel>
```

which would then generate a sizer element that looks like:

```html
<i-amphtml-sizer class="i-amphtml-sizer" style="padding-bottom: calc(75% + 1.5em)">
</i-amphtml-sizer>
```

Changes would be needed to the server side render code as well as the client-side layout to understand the additional height and generate the correct sizer. Browser support for unprefixed `calc` is good (IE9+, Firefox 16+, Chrome 26+, Safari 7+), so we could just generate the unprefixed version.

# Reasons to not Implement

AMP has provided layout as an easy, compact way for developers to to common layouts. Responsive layout, however, can still be done with CSS. Consider the following jsbin: https://jsbin.com/xoropetuwa/edit?html,output

You could implement responsive (+ additional height) as simply as:

```css
  .container {
    position: relative;
  }

  .my-sizer {
    padding-bottom: calc(75% + 1.5em);
  }
```

```html
<div class="container">
  <div class="my-sizer"></div>
  <amp-carousel layout="fill">...</amp-carousel>
</div>
```

One benefit of this approach is that you no longer have some styling in CSS and some styling in attributes. Another benefit is that it allows you to responsively change the aspect ratio, which you cannot currently do with responsive layout:

```css
@media (min-width: 600px) {
  .my-sizer {
    padding-bottom: calc(50% + 1.5em);
  }
}
```

Having developers use this pattern to begin with is nice in that they don't need to change to a new model once they want to switch aspect ratio based on a media query. In the current model, you use the attribute based layout and then it is a bit confusing on how to proceed when thinking about media queries. If developers did this in CSS to begin with, the path to media queries would be much more natural. They could also use things like custom properties and CSS pre-processors.

Ultimately, it would be nice for browsers to have an easy way to do aspect ratio based layout without needing to create a wrapping container and using padding bottom.

@ampproject/wg-ui-and-a11y 
@dvoytenko

**Comment by dvoytenko** [comment]
In CSS, `<div class="my-sizer"></div>` and `.my-sizer {}` can also be replaced with `.container::before {}` to simplify this a bit.

But w.r.t. to `additional-height` and `em` sizes - I often see captions being done using a different font than the rest of the page. Would it be "odd" to specify the font/size needed by a caption on the carousel element itself?

**Comment by sparhami** [comment]
After discussing this offline with @aghassemi, we have a slightly different approach that addresses the need to specify sizes for thumbnails on carousel element. I think for font-size, you could just set the font-size on the carousel itself, which would be inherited down to the captions. You could then size your sizer using some multiplier of the line-height to size to the desired number of lines. [This jsbin](https://jsbin.com/nipayihoxu/edit?html,output) shows the approach.

Essentially, you would pass a custom sizer element that would be added to the sizer element generated by `layout="responsive"`:

```css
.custom-thumbs {
  height: 96px;
}        
```

```html
<amp-carousel layout="responsive" width="400" height="300">
  <div class="custom-thumbs" sizer slot="thumbnail-size"></div>
</amp-carousel>
```

We could use this to size our container for the thumbnails internally, so you wouldn't have to communicate it via an attribute.

As far as AMP's layout is concerned, I think all we would need to do is to not hide these custom sizers by adding an exclusion here: https://github.com/ampproject/amphtml/blob/cb5f3d7bbe39b8e85d5cf8897c16d4b502686ed0/css/amp.css#L410-L414

by changing `*` to `:not([sizer])` (or some other, better, attribute name)

There would still need to be some additional mechanism to hide the thumbnails sizer on mobile, where we don't want it. We could put this carousel specific logic in `amp.css`, but there may be a better or more generic way to do this.

I think at least for the static case where you want layout responsive + some additional height, this approach works better because you can actually make the additional height itself responsive using media queries.

**Comment by sparhami** [comment]
So turns out you can already do responsive + a fixed height component using the `heights` attribute.

From the original example, requesting to do:

```html
<amp-carousel layout="responsive" width="400" height="300" additional-height="1.5em">
  ...
</amp-carousel>
```

You can currently do:

```html
<!-- width and height here are actually not important -->
<amp-carousel layout="responsive" width="400" height="300"
    heights="calc(1.5em + 100% * (4/3))">
  ...
</amp-carousel>
```

The heights can also be configured via media query. Being able to  pass custom sizers may still have value however.
