### ISSUE TITLE
Request Bank: Send back POST Form Data in the body

### ISSUE THREAD

**Issue by torch2424** [ampproject/amphtml#20869]
Currently, request bank isn't handling form data from POST requests, and moving it into the body, similar to: https://github.com/ampproject/amphtml/blob/master/build-system/recaptcha-router.js#L49

This should be done for easy POST tests using amp-form 😄

**Comment by lannka** [comment]
request-bank should handle POST already . see https://github.com/ampproject/amphtml/blob/master/test/integration/test-amp-analytics.js#L455

**Comment by torch2424** [comment]
@lannka Ah yes, so it does support POST, but what it does not support, is getting the Form Data from the POST. It is missing the `multer` module, to handle the `upload`. 

But per your comment in #20868 I'll just go ahead and do this as well.
