### ISSUE TITLE
gulp-amphtml-validator validation error for run-time variables substitution

### ISSUE THREAD

**Issue by antoinebisch** [ampproject/amphtml#20861]
## What's the issue?

This is a bug I came across using gulp-amphtml-validator.
I am working on a server-rendered AMP page and writing data with mustache into the HTML page at run time (the page gets populated according to URL parameters).
The issue is that when I validate the AMP page, it does not take into consideration the run-time data injection and therefore triggers an error as the code is not recognised as valid AMP although it becomes valid AMP when served.

## How do we reproduce the issue?

I could try to set a full working example if needed but that would mean recreating the issue somewhere like glitch. Let me know if needed as it would be time consuming.
However, the code not passing validation is the following line:

`<button type="button" option="<%productsGender%>-shirts" <%isShirtSelected%>>Shirts</button>`
The error output is:
_product-listing.html: FAIL
product-listing.html:1648:28 The attribute '<%isshirtselected%' may not appear in tag 'button'._

At run-time, the server renders the mustache variable `<%isShirtSelected%>` into either empty string or 'selected', so the served page is valid AMP. The page does work properly if I disable the amphtml checks in the build process, which I do not want to.

As a workaround, I had to use the following, less gaceful code:

```
<%#shirtSelected%>
<button type="button" option="<%productsGender%>-shirts" selected>Shirts</button>
 <%/shirtSelected%>
<%^shirtSelected%>
<button type="button" option="<%productsGender%>-shirts">Shirts</button>
<%/shirtSelected%>
```

This can become a lot more complex in the scenario of building an e-commerce site where a page with many buttons might have to be selected by default depending on the category of a product being viewed for example.

A possible solution would be to let users specify characters that define areas that will get substituted, and for the validator to bypass such areas.

## What browsers are affected?

N/A - Validation error

## Which AMP version is affected?

N/A - Validation error

**Comment by torch2424** [comment]
Triaging to @Gregable , Feel free to re-assign 😄

**Comment by honeybadgerdontcare** [comment]
The code sample isn't using the [amp-mustache](https://www.ampproject.org/docs/reference/components/amp-mustache) syntax which is why it is invalid.

cc'ing amp-mustache owner @choumx 	are there plans for supporting this syntax?

**Comment by antoinebisch** [comment]
> The code sample isn't using the [amp-mustache](https://www.ampproject.org/docs/reference/components/amp-mustache) syntax which is why it is invalid.
> 
> cc'ing amp-mustache owner @choumx are there plans for supporting this syntax?

This is using a custom markup for mustache to differentiate and avoid conflicts between the server-side rendering logic in mustache and the AMP side dynamic rendering logic in mustache.

**Comment by choumx** [comment]
Sounds like you should be running `gulp-amphtml-validator` after server-side render, not before. It's only meant to validate AMP pages, not templates of AMP pages.
