### ISSUE TITLE
Request Bank: Send back AMP CORS Headers

### ISSUE THREAD

**Issue by torch2424** [ampproject/amphtml#20868]
Was writing request bank test for #20541 , and found that there are not AMP CORS headers sent back by the request bank.

<img width="544" alt="screen shot 2019-02-14 at 11 53 45 am" src="https://user-images.githubusercontent.com/1448289/52813873-9a40d300-304f-11e9-85e7-494a86f271d7.png">

**Comment by lannka** [comment]
is the test passing with this error msg in browser?
Since you're already on it, please help to improve request-bank. you can follow what has been done in `enableCors` in `app.js`
