### ISSUE TITLE
🌸 Cherry pick request for #20876 into 1902132037100 (Canary)

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#20878]
## GitHub issue your cherry pick is fixing:

This is a rollback of #20608

## PR that you are requesting a cherry pick for:

PR #20876

## Release(s) you requesting this cherry pick into:

1902132037100

Production Release? NO

Canary release? YES

Release Issue #20875

## Why does this issue meet the [cherry pick criteria]

Rollback of an existing pull request.

/cc @cramforce

**Comment by cramforce** [comment]
Approved

**Comment by jpettitt** [comment]
cc @jpettitt

**Comment by Marcial1234** [comment]
Pushed to 1% at 5:57 PM UTC-5, waiting on dev channel to close issue

**Comment by Marcial1234** [comment]
Next patched release: https://github.com/ampproject/amphtml/releases/tag/1902151859190
