### ISSUE TITLE
Access AMP opensauce (saucelabs) account

### ISSUE THREAD

**Issue by slocka** [ampproject/amphtml#20882]
## Context
I would like to debug flaky tests on Saucelabs. I read the instruction here https://github.com/ampproject/amphtml/blob/82c54c298478f56338d9f147c5a3566232d48e6c/contributing/TESTING.md#testing-on-sauce-labs

## What's the issue?

Since I already have a Saucelabs account but with an expired trial, I contacted saucelabs support to ask them for access to opensauce as it is recommended in the [TESTING.md#testing-on-sauce-labs](https://github.com/ampproject/amphtml/blob/82c54c298478f56338d9f147c5a3566232d48e6c/contributing/TESTING.md#testing-on-sauce-labs).
However, the support service is telling me that it's impossible without having the username of the AMP opensauce account. 

- Would you mind sharing the username of the AMP opensauce account?
- It's probably a good idea to add it to the TESTING.md file.

**Comment by rsimha** [comment]
@danielrozenberg @estherkim Did either of you recently have to go through this process with an opensauce account?

**Comment by rsimha** [comment]
Closing this as stale.
