### ISSUE TITLE
Disable default placeholder for CMP iframe

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#20880]
The idea is to add support to `noloading` attribute to `<amp-consent>`. With it, no placeholder will be applied before consent prompt iframe is ready.

**Comment by zhouyx** [comment]
to @hrkhal who kindly offered to help, and @torch2424 who owns the amp-consent UI.

**Comment by hrkhal** [comment]
Cheers for assigning @zhouyx. 

@torch2424, did you have any thoughts or preference as to how the the`noloading` attribute and functionality should be implemented before I get started with the task?

**Comment by torch2424** [comment]
@zhouyx Thanks!

@hrkhal Hello! And no preference personally. What you will probably want to do though, is to:

* [Check for the attribute in the build callback. Attach to `this.noLoading_` or some name like that.](https://github.com/ampproject/amphtml/blob/master/extensions/amp-consent/0.1/amp-consent.js#L109)
* [Don't show / create the placeholder if this `this.noLoading_` is true](https://github.com/ampproject/amphtml/blob/master/extensions/amp-consent/0.1/consent-ui.js#L368)

Let me know if I can help in any way 😄 

Thanks!

**Comment by torch2424** [comment]
@hrkhal Any updates on this? 😄 

Don't mind picking this up, but to be honest, I'm a little spread thin at the moment with other work around the project (especially right after our AMP Conf). Let me know what you think! 👍

**Comment by calebcordry** [comment]
@hrkhal Are you still planning on working on this?
