### ISSUE TITLE
Enable video docking when pre-roll playing on Brightcove video player

### ISSUE THREAD

**Issue by bjalford** [ampproject/amphtml#20885]
We are testing the video docking experience on Brightcove players.

Example here: https://feature-amp-dock.independent.co.uk/news/uk/politics/brexit-deal-latest-customs-union-vote-eu-labour-theresa-may-red-lines-a8774346.html?amp

Feature request is to enable docking to occur when the preroll is playing to ensure viewability of ad

**Comment by aghassemi** [comment]
/To @mister-ben: My guess is that Brightcove does not sent the `Playing ` event when pre-roll starts? (since docking only happens if state of the player == playing)

/cc @alanorozco

**Comment by mister-ben** [comment]
Yes, within the Brightcove Player content and ad playing are distinct. If amp only needs to know _anything_ is playing we can change when that's triggered in the amp component.

**Comment by aghassemi** [comment]
@mister-ben yes, we expect `playing` event when anything is playing. `ad-start` and `ad-end` sufficiently contain information to know whether what's playing is an ad or not.

**Comment by bjalford** [comment]
@mister-ben is this something Brightcove is intending to do?

**Comment by mister-ben** [comment]
Yes. An update to support this is in testing.

**Comment by mister-ben** [comment]
This was released, Brightcove Players should be re-published to get the latest amp support plugin.
