### ISSUE TITLE
Validator blacklisted_value_regex for form[name]

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#20890]
We already have blacklists for `[id]` and `input[name]`. Need one for `form[name]` to mitigate clobbering of `Document`.

/cc @honeybadgerdontcare

**Comment by zhangsu** [comment]
All properties and methods on `document` in the MDN documentation can be a good start:

https://developer.mozilla.org/en-US/docs/Web/API/Document

**Comment by molnarg** [comment]
This is what DOMPurify does: https://github.com/cure53/DOMPurify/blob/3f8fccd845b1625862de1365eccae1492b68ef72/src/purify.js#L718

**Comment by choumx** [comment]
Combined list of document properties in latest Chrome, Safari, and Firefox (with trailing `|` for copy/paste): https://gist.github.com/choumx/17ef671676273166653bc19f212372f4

It includes non-enumerable props like `__proto__` but I also added others from here:
https://github.com/ampproject/amphtml/blob/6efcfc1c7e4a945eba53466412132c97cad05d43/validator/validator-main.protoascii#L5156-L5165
