### ISSUE TITLE
amp-lightbox-gallery: element disappears at beginning of transition

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#20904]
See triggered in auto lightbox here:

https://www.google.com/amp/s/www.aljazeera.com/amp/news/2019/02/trump-demands-europe-hundreds-isil-prisoners-190217051030452.html

Result of #20754.

/cc @cathyxz @aghassemi

**Comment by aghassemi** [comment]
This is fixed by https://github.com/ampproject/amphtml/pull/20909
