### ISSUE TITLE
Amp-carousel + amp-video: video controls disapper on second loop in chrome

### ISSUE THREAD

**Issue by SimonHogstromRonbol** [ampproject/amphtml#20907]
## What's the issue?

If you have a looping amp-carousel with an amp-video with controls in one of the slides, the video works just as you expect on the initial slide, but when you loop through the slider and come back to the slide with the video, the controls are suddenly behind the video itself, thus making the video unable to be interacted with 

## How do we reproduce the issue?

ive made this codepen to replicate the issue.
https://codepen.io/sunturion/pen/omJMzm

1. go to the codepen and see that the controls of the video is there.
2. press the right arrow on the slider enough so that you get to the video slide again (4 times)
3. notice that the controls for the video is now gone, do note that the video has no poster image so that isnt what is blocking the controls.
4. additionally you can press the left arrow 4 times and go back to the first slide again, and then you will see that the controls has returned.

I've also made this video, illustrating the issue.
https://gfycat.com/PowerfulCompleteCockerspaniel

## What browsers are affected?

I've tested in Chrome, firefox, and edge and i have only been been able to reproduce the bug in Chrome,

## Which AMP version is affected?

ive only testet this in version 1902081532110

**Comment by aghassemi** [comment]
@alanorozco Sounds similar to the bug you ran into with `dock`. Let's create a Chrome bug and escalate.

**Comment by alanorozco** [comment]
@SimonHogstromRonbol Thanks for the video, that's very helpful.

@aghassemi It does indeed look like the same bug, but I can't repro using [the example](https://codepen.io/sunturion/pen/omJMzm), running Chrome 72.0.3626.109, with either the video playing or paused.

@SimonHogstromRonbol Could you tell us what version of Chrome you're running? I'm trying to triage to see if this is something we can repro/raise or if it's something that was recently fixed.

**Comment by SimonHogstromRonbol** [comment]
@alanorozco I was using chrome 72.0.3626.109 at the time.

If you want a real world example aside from the codepen, the slider in question is located at https://www.syndicate-tattoo.dk/ - screensized up to 768 px.

**Comment by alanorozco** [comment]
@SimonHogstromRonbol Thanks! Definitely repro's there.

I [isolated](https://video-no-controls.glitch.me/) the example but I still can't get it to repro. I'm trying to find the minimum reduced case so I can raise this, will update.

**Comment by alanorozco** [comment]
Okay, I [was able to repro with a slightly different, but smaller case](https://video-no-controls.glitch.me/), looks like the condition is simply controls being dynamically toggled asynchronously while video is out-of-view. [Raised on Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=933428), hopefully it will gain traction.

**Comment by aghassemi** [comment]
Fixed -> https://bugs.chromium.org/p/chromium/issues/detail?id=933428#c16
