### ISSUE TITLE
FR: Dynamic "target" parameter in AMP.navigateTo() 

### ISSUE THREAD

**Issue by omar-toma** [ampproject/amphtml#20919]
## What's the issue?

I am trying to use an amp-state for the target in AMP.navigateTo() but it doesn't bind it.

## How do we reproduce the issue?

you can see an example for the issue here: https://jsfiddle.net/omartoma/qzbfaest/1/
once you click on the button, there is an exception in the console saying

`Uncaught (in promise) Error: Target 'null' not supported.​​​`

## What browsers are affected?

All browsers

## Which AMP version is affected?

Latest

**Comment by j-jover** [comment]
If you check the AMP documentation, the feature only really supports _blank and _top.

I don't see much of a point in having it look up to a bound state when the optional param can either be _blank or _top (which IMO should be expressed directly rather than having it bound to a state then looked up)

**Comment by omar-a-toma** [comment]
The use case that I have requires changing the target dynamically. I am running an A/B test using amp-experiment to measure the impact difference between opening some links in a new tab or the same one. 
I am sending the variant to an endpoint and this eventually will update a state and that is why I am trying to bind that state to this parameter.
The other option that I have is to duplicate those links and control them using CSS which will increase the page size and will affect the performance.

**Comment by torch2424** [comment]
Triaging to @choumx , feel free to re-assign 😄
