### ISSUE TITLE
Error: Object function Number() { [native code] } has no method 'parseFloat'

### ISSUE THREAD

**Issue by sparhami** [ampproject/amphtml#20927]
This error is coming from: https://github.com/ampproject/animations/blob/a83edf3a9e5df55c6451e8d14c3a59bf1437dfe0/src/object-position.ts#L19

It looks like `Number.parseFloat` is not supported in IE, and the global `parseFloat` should be used instead.

**Comment by alanorozco** [comment]
There's a [lint rule for this specifically.](https://github.com/ampproject/amphtml/blob/master/build-system/eslint-rules/no-es2015-number-props.js)

Sorry this bit ya. If all `ts` is bypassing the linter then that could be worrisome.

**Comment by sparhami** [comment]
> There's a [lint rule for this specifically.](https://github.com/ampproject/amphtml/blob/master/build-system/eslint-rules/no-es2015-number-props.js)
> 
> Sorry this bit ya. If all `ts` is bypassing the linter then that could be worrisome for other, more critical cases.

The problem is the code is in a separate repo that does not have all the AMP linting, etc. I added linting to the list of issues here: https://github.com/ampproject/animations/issues/7

We want to standardize the process / infra for creating one of these standalone repos in the future, it just isn't something we have yet :disappointed:.
