### ISSUE TITLE
Error: Uncaught TypeError: self.reportError is not a function

### ISSUE THREAD

**Issue by sparhami** [ampproject/amphtml#20938]
There is no useful stacktrace for this error. It seems like it has been around for a while, but I could not find an existing issue for this.

go/ampe/CNrg-83bsfKDFQ?service=default-cdn-1p-canary&time=P1D&project=amp-error-reporting

**Comment by mattwomple** [comment]
You can use Issue #17532 to reproduce this issue.

Here is a minimal example: [https://android.cmphys.com/temp/bind-navigation-pwa.html](https://android.cmphys.com/temp/bind-navigation-pwa.html)

You can _Save_ (which runs `AMP.setState`) just fine on the first page, but as soon as you click the link to navigate to the next page within the PWA, you can no longer _Save_ and the console reports `TypeError: self.reportError is not a function`.

**Comment by sparhami** [comment]
Putting a breakpoint on the error, it looks like it is going into `dev().error` here:

https://github.com/ampproject/amphtml/blob/3f3e6dd69758d567149df0da8f974ed1c68af561/src/web-worker/web-worker.js#L75

which then fails here:

https://github.com/ampproject/amphtml/blob/3f3e6dd69758d567149df0da8f974ed1c68af561/src/log.js#L261

It seems since the code is in a worker, we don't get a useful stack trace.

It looks like there are two issues from @mattwomple's example:

1. `self.reportError` is not defined
1. The `bind.init` is being called twice.

For the latter issue, it seems like the code may work fine since it seems to bail out. In that case, perhaps the `dev().error` should be turned into a `devAssert` instead. I will create a separate bug for this.

**Comment by sparhami** [comment]
It looks like `ww.js` never sets an error reporter like the standard runtime does. For example, runtime sets it here:

https://github.com/ampproject/amphtml/blob/eb0585d7c9e73b170fb1afc20829eea66ce63a2e/src/runtime.js#L89-L93

But web-worker.js does not:

https://github.com/ampproject/amphtml/blob/55c78991ed203a676febb2396ff6f25606414ba2/src/web-worker/web-worker.js#L30-L33

@choumx I'm not sure if we want to simply do the same thing as `runtime.js`, since it may pull in additional payload or if we want to do something else.

**Comment by choumx** [comment]
Thanks for the investigation!

**Comment by jridgewell** [comment]
This is one error that we should fix. But, the error that's attempting to be logged is "Evaluator already exists for scope". We should fix that, too.
