### ISSUE TITLE
🌸 Cherry pick request for #20909 into 1902151859190 (Pending)

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#20931]
## GitHub issue your cherry pick is fixing:
This is a rollback of #20754 (#20909)

## PR that you are requesting a cherry pick for:
#20875 (?)

## Release(s) you requesting this cherry pick into:
1902151859190

Production Release? No (hasn't made it to prod)

Canary release? Yes

Release Issue #20875

## Why does this issue meet the [cherry pick criteria]
Rollback of an existing pull request.  **Does not meet criteria by itself**. Breaks presentation/animation. This cherry pick should be included along another, required cherry pick.

/cc @cramforce

**Comment by cramforce** [comment]
Approved

**Comment by sparhami** [comment]
Since we did not end up cherry picking into the canary that went to prod, will close this. The change made the cut-off for the newly cut canary (1902191749350), so it does not need to be cherry picked there.
