### ISSUE TITLE
Can amp-web-push's service-worker file path be modified ?

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#20955]
To whom it may concern:

I like to to implement web push to AMP pages. I can't place the service-worker file to root for some reasons. So it will occur error message:

> The path of the provided scope ('/') is not under the max scope allowed ('/mei/'). Adjust the scope, move the Service Worker script, or use the Service-Worker-Allowed HTTP header to allow the scope.

I wonder is it possible to let file path be optional for developers just like amp-install-serviceworker.js do ?

- [amp-install-serviceworker](https://github.com/ampproject/amphtml/blob/master/extensions/amp-install-serviceworker/0.1/amp-install-serviceworker.js#L312)

- [amp-web-push's scope setting](https://github.com/ampproject/amphtml/blob/master/extensions/amp-web-push/0.1/web-push-service.js#L337)

Paul

**Comment by torch2424** [comment]
Triaging to @prateekbh , feel free to re-assign 😄

**Comment by prateekbh** [comment]
Adding @dvoytenko as he wrote amp-web-push
