### ISSUE TITLE
Ship alternate binaries for `#development=1`

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#20958]
## Background

AMP allows developers to set the `#development=1` fragment to make their pages easier to debug. This lets `user`-level assertion errors to go through to the console in a human-readable format.

In the vast majority of cases, AMP pages are served without that fragment. That means that error mesages are not output to console, so they're useless. Since `user`-level assertions generally contain human-readable messages, these unnecessarily bloat the binaries shipped to the end user.

## High-level proposal

Generate two binaries for each release channel. One is the status quo, called "debug binary" which is only meant for development. The other binary (let's call it "skinny binary") has all `user`-level assertion error messages stripped out. Assertions are still present so errors can be traced and do not propagate.

### Dynamic

Ship the skinny binary by default under the current URLs. On load time, runtime checks for `#development=1` and short-circuits all extensions and the runtime itself, to be replaced with the debug binaries for each. This is slow and convoluted, but since it's a development scenario it should be ok.

### Static

Ship the skinny binary by default under the current URLs. Ship the debug binary under a different URL suffix that developers can use. Before publishing, the developer has the responsibility of replacing the URLs. Easier to handle on the client side, but leaves the responsibility of replacing binaries up to the dev.

## Other opportunities

Some components do more advanced things for debugging than just value assertion. One example is elements that paint themselves red when they detect an invalid usage. These codepaths can also be removed through a flag, e.g.

```js
if (getMode(this.win).userDebug && this.isInvalid_()) {
  this.paintRed_();
}
```

This however introduces diverting codepaths for skinny/debug. Simply removing the messages does not.

/cc @ampproject/wg-infra @ampproject/wg-ui-and-a11y @aghassemi

**Comment by danielrozenberg** [comment]
I like the idea. I'm leaning towards the 1st (dynamic) solution, because it puts less responsibility on website developers to ensure they're serving the right version (avoiding the "I forgot to turn debug mode off and now everyone has my passwords" situation - granted there's no security repercussions here but you get what I mean)

Splitting the runtime to skinny/full code does come with the added risk of having bugs that manifest only in the skinny binary, something to take into consideration

**Comment by cvializ** [comment]
Aren't `user().errors` surfaced in our error dashboard logs, i.e. that the release engineers look at before promoting a canary? We wouldn't want to omit user errors from the production build because that would change how existing errors we're tracking look in the dashboard. Is that how you understand it too?

**Comment by alanorozco** [comment]
@danielrozenberg Yep, that would be a risk but only if we DCE per a flag. Removing the error messages only would not be destructive in that sense.

@cvializ If you keep the assert but remove the message, everything else should still be logged equally. The errors are not omitted, the stacktrace is still pushed.

**Comment by erwinmombay** [comment]
Isn't this sort of similar to the message extraction work? (where we replace all strings with a hex id and generate a url)

also this would affect the ads 3p error reporting possibly @zhouyx (where we forward errors and the message to the vendor)

**Comment by zhouyx** [comment]
+1 to @erwinmombay point on message extraction work.

We forward user error message with outgoing analytics request. But as long as we can fetch the message from somewhere, or vendor can fetch the message from somewhere that should still work. 
https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md#error-trigger

**Comment by alanorozco** [comment]
@erwinmombay @zhouyx 

Thanks for letting me know about the current work. @kristoferbaxter mentioned the message extraction idea offline a while back but I didn't know it was materializing. Cool!

Closing this since something similar is already happening and this doesn't cover the vendor-level reporting that ads require.
