### ISSUE TITLE
amp-a4a: adsense: Assertion failed

### ISSUE THREAD

**Issue by sparhami** [ampproject/amphtml#20962]
Noticed this issue when running `examples/ads.amp.html`

[amp-a4a] Error: amp-a4a: adsense: Assertion failed
    at Log.assert (amp.js:16291)
    at devAssert (amp.js:16730)
    at Resource.whenWithinViewport (amp.js:33593)
    at amp-ad-network-adsense-impl-0.1.js:4013

This is coming from here: https://github.com/ampproject/amphtml/blob/2277223833c75db27ca51f7abc47edc817168640/extensions/amp-a4a/0.1/amp-a4a.js#L613-L618

It looks like the value passed to `whenWithinViewport` is `false` in some cases, but the method has an assert that the value should not be false: https://github.com/ampproject/amphtml/blob/b734396b81d51370b69f5b05234e18c9cf539dd2/src/service/resource.js#L673-L674

**Comment by lannka** [comment]
@keithwrightbos do you have any insight?

**Comment by keithwrightbos** [comment]
Is this still relevant?
