### ISSUE TITLE
I2I: suggest completed values for user inputs with amp-autocomplete

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#20988]
## Summary
An amp-autocomplete extension will enable publishers to easily provide a set of suggestions completing a user query in an input field. 

## Design document
[Design doc](https://docs.google.com/document/d/1OOPnKgShbh7BN2D24u7bxa57z2spAiBA8n9o0L5V3qA/edit#)

## Motivation
Currently the autosuggest example is the only way AMP supports an autocomplete feature. It was developed in response to high demand from e-commerce and news publishing clients. Developing a dedicated component—whose performance during load and user interactions is tested and improved upon—provides a simple way for publishers to improve their user interactions with an easy-to-use API that requires little overhead. 

## Goals
- Provide suggestion functionality on top of a developer inserted input tag.
- Fulfill two primary use cases: a page wide search field or a specific field lookup (i.e. in a form). These meet a wide range of needs including publishing and e-commerce. 
- Support varying forms of source data and filtering mechanisms in response to user input.
- Integration with other AMP ecommerce features, e.g. AMP actions and events, amp-bind

## Additional context
[Helpful autocomplete visual](https://drive.google.com/open?id=10Gisre4o5XKxykfX4NY41T2tIs-J-__E) thanks to @andrewwatterson 

## Caveats
Component data retrieval method pending ongoing discussions about how to integrate with amp-state or if it is better to use a src attribute similar to amp-list now.

/cc @cvializ @gmajoulet @aghassemi

**Comment by andrewwatterson** [comment]
Can you update the visual to the one I posted in Slack yesterday? The one you linked to is out of date. :)

**Comment by andrewwatterson** [comment]
![autocomplete](https://user-images.githubusercontent.com/1370189/53194058-63c30500-35c7-11e9-9dca-727afb746748.png)

**Comment by andrewwatterson** [comment]
Updated visual here ^^^

The link above is out of date.

**Comment by caroqliu** [comment]
Closing since the experiment was cleaned up in #22708 and has fully launched. :)
