### ISSUE TITLE
Intent to implement: redirect from amp-access-scroll when Scroll App is detected

### ISSUE THREAD

**Issue by kushal** [ampproject/amphtml#20997]
When we originally submitted #17987 we wanted to redirect to scroll.com when we detected the presence of the Scroll app in order to authenticate users, instead of just showing a button that would open scroll.com after the user notices it and clicks. It sounded like there might be a bit more privacy/security review required, so we're doing this now as a separate step. What would help you decide if this is kosher? Happy to send test accounts to anybody who wants to see the current implementation in action. Thanks!  cc @dvoytenko

**Comment by kushal** [comment]
@dvoytenko Yup!

We'll know the app is installed by looking for blocking of a well-known URL (no change to existing code at https://github.com/ampproject/amphtml/blob/3e03122f33504a038a27840b7ea0f6b2ecacbdde/extensions/amp-access-scroll/0.1/scroll-impl.js#L206 ).

The only change is at https://github.com/ampproject/amphtml/blob/3e03122f33504a038a27840b7ea0f6b2ecacbdde/extensions/amp-access-scroll/0.1/scroll-impl.js#L215 where we would redirect to the URL from https://github.com/ampproject/amphtml/blob/3e03122f33504a038a27840b7ea0f6b2ecacbdde/extensions/amp-access-scroll/0.1/scroll-impl.js#L320 using `window.location` instead of displaying a button that opens that URL.

**Comment by dvoytenko** [comment]
@kushal I think we are good to proceed here for non-CDN case. Feel free to send me a pull request for an early review to make sure we're on the right path.
