### ISSUE TITLE
Linker doesn't handle fragments well

### ISSUE THREAD

**Issue by shimonenator** [ampproject/amphtml#20998]
## What's the issue?

This issue has been previously addressed in #19456, but it seems to have either never been fixed or resurfaced recently. 
Currently, if there's a fragment url on the page, amp-linker replaces it with full url + linker query string when the link is clicked/tapped, which causes page reload instead of expected action. 

## How do we reproduce the issue?

1. visit https://www.cbsnews.com/amp/news/baby-girl-born-24-year-old-embryo/
2. click on the hamburger menu in the header (top left corner)
3. expected behavior is for the fragment to be simply appended to the url in the address bar, however the page goes through a full page reload instead. 

## What browsers are affected?

All browsers.

## Which AMP version is affected?

Current production build.

**Comment by shimonenator** [comment]
CC @[calebcordry](/calebcordry)

**Comment by calebcordry** [comment]
@shimonenator thanks for reporting. We solved the other issue by not automatically decorating same domain, but you are opting into same domain decoration with your destinationDomain config. I agree that this is a valid use case, and maybe we could do something like check if the link is only a fragment and never decorate those. I am trying to think if there is ever a use-case where you would want fragment to be decorated, but it seems not.

cc/ @lannka
