### ISSUE TITLE
DCE misses NOT expressions

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#21010]
If you take a useless expression and `!` it, closure compiler will fail to DCE it:

```js
/**
 * @param {string} name
 */
function hello(name) {
  /^[\w-]*$/.test(name);  // Will DCE
  !/^[\w-]*$/.test(name);  // Will NOT DCE

  name.indexOf(';'); // Will DCE
  !name.indexOf(';'); // Will NOT DCE
}
hello('justin');
```

**Comment by kristoferbaxter** [comment]
We should file a ticket with the Closure Compiler team for this, and if possible create a Babel transform for it temporarily.

**Comment by jridgewell** [comment]
This is because it's being labeled suspicious (because it's unused). When actually used, it's eliminated.
