### ISSUE TITLE
amp-script: `this` does not point to the bound element at event listener 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amphtml#21028]
## What's the issue?

When using event listener inside amp-script, `this` references the entire `amp-script document` and not the bound element. 

## How do we reproduce the issue?

1. Add event listener to element defined inside `<amp-script>`
2. console.log(this)

## What browsers are affected?

Chrome, current

## Which AMP version is affected?

Current

**Comment by choumx** [comment]
Can you share the event listener code snippet?

**Comment by CrystalOnScript** [comment]
Sure thing!

HTML
```  
<amp-script layout=container src="script.js">
    <div class="iamred" tabindex=-1>
    </div>
  </amp-script>
```

script.js

```
const iamred = document.querySelector('.iamred');
iamred.addEventListener('click', (event) => {
  console.log(this)
})
```

**Comment by choumx** [comment]
I think this is because of the use of a closure which doesn't bind to `this`. If you change it to a normal function it'll do the right thing:
```js
iamred.addEventListener('click', function(event) {
  console.log(this)
})

// Output: HTMLButtonElement {...}
```
