### ISSUE TITLE
Customizable text color on Amp Story ad call to action button 

### ISSUE THREAD

**Issue by jp-washpost** [ampproject/amphtml#21022]
## Describe the new feature or change to an existing feature you'd like to see

Currently, the only color available as a CTA on Amp Story ads is blue. This doesn't always pair well with ad assets, like if the predominant color of an ad is green. We'd like the ability to customize the CTA button by either specifying an override hex value (preferred) or select an optional color from a wider set of options.

## Describe alternatives you've considered

Provide a clear and concise description of any alternative solutions or features you've considered.

## Additional context

It could be neat if the system could log an error if the color selected didn't have sufficient contrast (WCAG AA) with the white button and then default to the blue in that instance.

**Comment by torch2424** [comment]
Triaging to @calebcordry , Feel free to re-assign 😄

**Comment by calebcordry** [comment]
Thanks for creating the FR. We are in discussions about prioritization.
