### ISSUE TITLE
Poster image to amp-youtube

### ISSUE THREAD

**Issue by ronaldlauweb** [ampproject/amphtml#21035]
I want to have a poster image for a YouTube video.

So when you click on an image, it will automatically play the YouTube video.

It’s possible?

Thank you !

**Comment by aghassemi** [comment]
Yes, checkout https://ampbyexample.com/advanced/click-to-play_overlay_for_amp-video/ (sample uses amp-video but amp-youtube is the same)

**Comment by aghassemi** [comment]
Closing per above, please reopen if needed
