### ISSUE TITLE
extraUrlParams: template vars not updated in nested objects.

### ISSUE THREAD

**Issue by murraybiscuit** [ampproject/amphtml#21045]
**Category:** Analytics
**Repro:** set an amp-analytics trigger to send extraUrlParams with a nested object containing template ${variables}.
**Result:** All variables are correctly expanded on initial trigger event. On subsequent events, nested variables are not updated with new values.
**Expected:** Nested object properties reflect updated values.

**Sample code:**
```html
<amp-analytics>
    <script type="application/json">
    {
      "requests": {
        "btnClick": "https://my-endpoint.com/foo"
      },      
      "transport": {
        "beacon": true,
        "xhrpost": true,
        "useBody": true
      },
      "triggers": {
        "btnClick": {
          "on": "click",
          "selector": ".btn",
          "request": "btnClick"
        }
      },
      "extraUrlParams": {
        "time1": "${timestamp}",
        "doesntUpdate": {
          "time2": "${timestamp}",
          }
        }
      }
    }
    </script>
  </amp-analytics>
```
In the above code, `time1` is always updated, `time2` will always reflect the timestamp of the initial event.

#19609 PR enabled nested expansion, but for some reason, nested template vars aren't getting updated.
@ryanashcraft @calebcordry - any ideas if this is expected behavior?

**Comment by torch2424** [comment]
Triaging to @calebcordry , feel free to re-assign 😄

**Comment by calebcordry** [comment]
@murraybiscuit Thanks for reporting! I was able to repro. Looks like we are doing a shallow copy of the given params here
https://github.com/ampproject/amphtml/blob/8521bc08f62093b79e50f21724aca77f1ad8da72/extensions/amp-analytics/0.1/requests.js#L142

And then mutating that object with the resolved macros in `expandExtraUrlParams` 
https://github.com/ampproject/amphtml/blob/8521bc08f62093b79e50f21724aca77f1ad8da72/extensions/amp-analytics/0.1/requests.js#L369-L381

I think just changing this to a deep copy should fix it. I will put it on my list of things to fix.

**Comment by murraybiscuit** [comment]
Thanks @calebcordry! Let me know if you've got any kind of ETA. If it's going to take more than a few weeks, may take a stab at it ourselves. But then I'd need to sign contrib doc etc, so whatever's fastest.
FYI @iandoone

**Comment by calebcordry** [comment]
@murraybiscuit we have a ton of work that we are trying to get done before amp conf. If you could get it done that would be awesome! I am not sure about timeline but may be a couple weeks.

**Comment by murraybiscuit** [comment]
Thanks @calebcordry, will sync with team. Appreciate the comms.

**Comment by torch2424** [comment]
@murraybiscuit Did @calebcordry solve the issue for you? Let us know! 😄

**Comment by hongy20** [comment]
This issue is valid, I can still reproduce it

**Comment by micajuine-ho** [comment]
I believe https://github.com/ampproject/amphtml/pull/29620 closes this issue.
