### ISSUE TITLE
Can amp-carousel support passive event listeners to improve scrolling performance ?

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#21047]
To whom it may concern:

I just wonder: Can amp-carousel support passive event listeners to improve scrolling performance ?

[passive event listeners](https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners)

Paul

**Comment by cathyxz** [comment]
Triaging to @sparhami

**Comment by metawise** [comment]
Wondering what happened to this? I would be great if they put passive listener!

**Comment by sparhami** [comment]
Will take another look at getting this in.
