### ISSUE TITLE
amp-sidebar overlay remains after receiving close action when used within amp-story

### ISSUE THREAD

**Issue by hongwei1990** [ampproject/amphtml#21050]
**Please only file bugs/feature requests for AMP here.**
When close the burger menu, tap on x on the menu will just close the menu content but leave the black overlay.

 @newmuis @gmajoulet @bramanudom 

![u2nyzwvuc2hvdf8ymde5mdiymy0wotizmjuucg5n](https://user-images.githubusercontent.com/33703058/53354359-7006d500-38db-11e9-9778-3ad50249e122.png)
![u2nyzwvuc2hvdf8ymde5mdiymy0wotizmziucg5n](https://user-images.githubusercontent.com/33703058/53354360-7006d500-38db-11e9-86e3-e950ff80cdf1.png)

**Comment by OptimumGraph** [comment]
Would it be a better option to automatically include a close button in the story UI when the sidebar is open?

This also would eliminate the need for a close action within the sidebar.

![sidebar](https://user-images.githubusercontent.com/36829233/54394928-0c154680-46fa-11e9-83a7-4dadc791e170.jpg)

**Comment by hongwei1990** [comment]
Hello, thanks for the suggestion! The dark overlay in between the fly-out menu and page content should visually communicate clear enough that tap/click on the non-menu area will dismiss the menu. Adding additional close graphic there seems not necessary.
