### ISSUE TITLE
Clearing a form will reset the element to its binding value with input and not textarea

### ISSUE THREAD

**Issue by nick-leung** [ampproject/amphtml#21053]
## What's the issue?
When a form containing a textarea and input field is cleared, only the input field will reset to its binding value.

Steps to reproduce:
https://output.jsbin.com/rubuhexagi

1. Click Open lightbox
2. Click Add !
3. Click Clear form and close lightbox
4. Click Open lightbox

Actual result:
Only the input field retains the text "hello!" while the textarea field remains blank

Expected result:
Both the input field and textarea field retain the text "hello!"

## What browsers are affected?
Tested with Chrome

## Which AMP version is affected?
Tested with Version 1902151859190

**Comment by cvializ** [comment]
Hi @nick-leung thanks for letting know what you're experiencing.

I think we'll need to talk about whether this is the expected behavior, since form.clear is meant to reset a form to its initial value, but amp-bind overwrites the `value` attribute when it binds to `[value]`.

For now, you can add an `AMP.setState` call to the clear button. e.g.

```html
<button
  type="button"
  on="tap:
      AMP.setState({product: {text: ''}}),
      formResetSample.clear,
      my-lightbox.close;">Clear form and close lightbox</button>
```

**Comment by choumx** [comment]
Related to #18921. 

I think the confusion is the difference in behavior between input and textarea. As Carlos mentions, the default value of input fields is updated when `[value]` binding is applied. 

To replicate this behavior for textarea, we'll need to set its `textContent`. The problem with doing that is setting `textContent` removes focus: https://github.com/ampproject/amphtml/blob/ae9ee68c0a448a9a8f2bbeb394a3d5b4622c40c9/extensions/amp-bind/0.1/bind-impl.js#L1142-L1143

So I think we should have separate bindings for "update current value" vs. "update default value" e.g. `[value]` vs. `[defaultValue]`. This would be similar to `checked` vs. `defaultChecked` properties for HTMLInputElement. The wrinkle is this would technically be a breaking change for input elements -- I'll try to measure the impact of this.

**Comment by choumx** [comment]
In the meantime, the workaround above should suffice.
