### ISSUE TITLE
Carousel ARIA labels do not work for `amp-carousel type=carousel` (fine for `type=slides`)

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#21071]
To Whom it may concern:

amp-carousel doesn't add aria-label for amp-carousel-button-next & amp-carousel-button-prev elements even I had already set the [data-next-button-aria-label] & [data-prev-button-aria-label].

[amp-carousel document](https://www.ampproject.org/docs/reference/components/amp-carousel#data-next-button-aria-label-(optional))

Paul

**Comment by aghassemi** [comment]
Hi @meistudioli. They get added as `title` because next/prev are `button` and title works better for screen readers.

(we also have a default text that we put in if nothing specified, we put "Next item (n of m)")

**Comment by aghassemi** [comment]
Closing per comment above, please feel free to reopen if still an issue.

**Comment by Jessman5** [comment]
Hej @aghassemi,

I'd like to reopen this Bug because it's still an issue.
It gets applied on type="slides" but not on type="carousel".

**Comment by Jessman5** [comment]
thank you :)

**Comment by aghassemi** [comment]
@Jessman5 After investigating the best pragmatic way to handle this for scrollable carousel (`type=carousel`) case, we ended up hiding the next/previous buttons from screen readers via `role=presentation`. The reasoning is that scrollable carousel is simply a horizontal scrollable div which is navigable just fine via screen readers when virtual focus moves between items so next/previous button were not adding any functionality for screen readers ( they do for keyboard users however ). To avoid the confusion of these buttons showing up in controls list without really helping with anything, we are now hiding them. 

This is very different from `slide` case where only one slide at a time is navigable without the next/previous controls which we already handle for screen readers even when controls are hidden (we keep hidden controls visible to screen readers by positioning them as transparent 2x2 pixel boxes so mobile screen readers can still see and activate them)

**Comment by Jessman5** [comment]
Alright, thank you. :) Waiting for this to be released.
