### ISSUE TITLE
Safari preconnect polyfill should use robots.txt instead of generating a 404

### ISSUE THREAD

**Issue by jono-alderson** [ampproject/amphtml#21088]
## Describe the new feature or change to an existing feature you'd like to see

See the following file, which establishes a preconnection to the AMP origin in order to speed up subsequent requests: https://github.com/ampproject/amphtml/blob/09396b2357d56b467485e4c9ef3f5cd910a0521d/src/preconnect.js

The file includes a polyfill for Safari, which enables it to simulate that preconnection behaviour.

This relies on generating a HEAD request to the following "well-known" URL on the host site: `/amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it?' + Math.random()`

These requests intentionally result in a cache-avoiding 404 error, which increases the likelihood of opening a successful (pre)connection.

Whilst the spec is insistent that "this is fine", the approach comes with the side-effect of:
- Filling server logs with 404'ing requests
- Possibly conflating server-side logging and analytics solutions
- Adding server load

It should also be noted that the presence of the `.` in the URL results in many server setups returning a 'raw' or unconfigured server error (as they think that `_Do_not_worry_about_it` is a file extension), which may cause other unexpected consequences (such as, the inability to intercept the request to achieve custom response handling).

I propose that, this approach "fine", and that it's un-neighbourly behaviour. Various forum/github/support threads also suggest that the labelling is unclear and confusing (and that '`Do not worry about it`' causes worry).

I'd like to see this approach adjusted to be a bit more considerate.

## Describe alternatives you've considered

Specifically, I suggest that we alter the request to `/robots.txt?cache_bust={{rand}}`.

Rationale:
- The current spec postulates that returning a non-404 response to the request is fine, and, that the response should be small. The robots.txt file meets both of these requirements.
- Most sites will already have a `robots.txt` file in place; and for those which don't, the current behaviour will persist (as those requests will return a 404).
- Businesses expect, and are comfortable with, bot-generated requests/visits to the `robots.txt` file.

## Additional context

Future considerations: 
- With further spec'ing, requesting the contents of the robots.txt file may also afford sites the opportunity to 'opt out' of this pre-connection behaviour (where `disallow` rules set to a matching user agent should prevent future requests for a period of time).
- In order to facilitate this, the request should also identify itself in the XHR with a distinct user-agent string.

Related, https://github.com/ampproject/amphtml/issues/11408

CC @cramforce @mkhatib @jridgewell (contributors from the referenced file)

**Comment by cramforce** [comment]
I think this is generally fine to change. I don't think any of the "Further considerations" are possible, since we have to make a non-CORS request to the resource to open a non-CORS connection.

I vaguely remember that preconnect is coming to Safari at which point this whole thing would become obsolete. Not sure exactly what the timing is.

**Comment by jridgewell** [comment]
@jono-alderson: Would you like to implement this? It should be a trivial change.

> * In order to facilitate this, the request should also identify itself in the XHR with a distinct user-agent string.

It's impossible to override the User-Agent header. Just looking at the page referrer should be enough to tell that it's an AMP page.

**Comment by jono-alderson** [comment]
Yes, will do tomorrow! :)
RE: user-agent, gotcha.
