### ISSUE TITLE
amp-pixel substitutions: add VIEWPORT_WIDTH and VIEWPORT_HEIGHT

### ISSUE THREAD

**Issue by steffenweber** [ampproject/amphtml#2108]
Currently, "amp-pixel" supports the substitutions `AVAILABLE_SCREEN_WIDTH` and `AVAILABLE_SCREEN_HEIGHT`. Knowing the screen size can be interesting but what's really useful for web development is knowing the viewport size (which takes window size and zooming into account). Only the viewport width tells you which layout your users see in a responsive design.

It would therefore be great if two new substitutions could be added to AMP:

- `VIEWPORT_WIDTH` which maps to `document.documentElement.clientWidth`
- `VIEWPORT_HEIGHT` which maps to `document.documentElement.clientHeight`

**Comment by rudygalfi** [comment]
Sounds good to me. @steffenweber Do you want to submit a PR for this?

/cc @avimehta who could do code review and/or implement

**Comment by steffenweber** [comment]
Thank you for the feedback. I've created pull request #2439.

**Comment by avimehta** [comment]
I think this is done. Thanks @steffenweber! Please re-open if something else is left.
