### ISSUE TITLE
amp-form not submitting in Edge 14

### ISSUE THREAD

**Issue by reipin** [ampproject/amphtml#21098]
## What's the issue?
amp-form via xhr not submitting at least in Edge 14.

## How do we reproduce the issue?
Problem noticed on a private website, nevertheless it also exists on other amp-form powered websites, most prominently in the examples provided by the Project itself:
https://ampbyexample.com/components/amp-form/#form-submission-with-client-side-rendering

## What browsers are affected?
At least Edge 14, IE11.
Latest Chrome, Firefox, Opera  and Safari seems not affected

## Which AMP version is affected?
Version 1902151859190
Not quite sure, never realized it before, I'm guessing it's a new issue.

**Comment by torch2424** [comment]
Triaging to @cvializ , feel free to re-assign 😄
