### ISSUE TITLE
Validation passes when User-Agent dependent elements are present and are invalid (Google Chrome extension)

### ISSUE THREAD

**Issue by horatiua** [ampproject/amphtml#21093]
## What's the issue?

Page invalid when User-Agent dependent elements are present.

## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. Add invalid AMP elements (from server side) only for mobile User-Agents.
2. Load URL in a desktop browser (Chrome)
3. Check validation using AMP Validator extension for Chrome (it should pass)
4. Check validation using https://validator.ampproject.org/ (it should fail)
5. Check validation using https://search.google.com/test/amp (it should fail)

## What browsers are affected?

Google Chrome for desktop.

## Which AMP version is affected?

Current version.

**Comment by torch2424** [comment]
Triaging to @Gregable , feel free to re-assign 😄

**Comment by Gregable** [comment]
I think that you are saying that you expect the AMP Validator extension to request your page like Googlebot rather than as Chrome, and your server returns valid AMP to some useragents and invalid to other useragents.

This is working as intended. I don't know if extensions can affect the network stack in such a way. The extension is fairly simple - it just validates whatever the server returns.

**Comment by horatiua** [comment]
Hi!
The problem is that validation seems to be done using a desktop User-Agent when validating, rather than a mobile user agent.

Indeed, AMP pages can be used on Desktop, but mostly these are used on mobile.

In my opinion, an option to choose from Desktop vs Mobile user agent should be of use.

**Comment by Gregable** [comment]
The extension uses whatever user agent your browser sends. If you want Chrome to send a mobile useragent, [enable device mode in Chrome](https://developers.google.com/web/tools/chrome-devtools/device-mode/) and select which mobile browser you would like to simulate.

**Comment by horatiua** [comment]
It doesn't seem to work.
It's interesting that when clicking "Debug" after receiving the error the https://validator.ampproject.org/ validator's status is "Pass".
