### ISSUE TITLE
Remove eval and setTimeout(string) from environment.js

### ISSUE THREAD

**Issue by molnarg** [ampproject/amphtml#2111]
The AMP CDN has a strict Content Security Policy that doesn't allow eval and setTimeout with string parameter, so it doesn't make sense to support setTimeout with string parameter in the setTimeout instrumentation code.

https://github.com/ampproject/amphtml/blob/master/3p/environment.js#L192

**Comment by cramforce** [comment]
@molnarg This runs inside of ad iframes served on `3p.ampproject.net` or the publisher's chosen host which does not have a CSP and which unfortunately does run code that is actually using setTimeout(String) :(

**Comment by molnarg** [comment]
Oh, I see, I'll close this ticket then and sorry for the noise.
