### ISSUE TITLE
Error: AbortError

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#21112]
Looks from swg.js

go/amp-error/CLmH8OjN2JbNWw

**Comment by dvoytenko** [comment]
@zhouyx why are we logging AbortErrors? We should just skip them - this is just user-level cancelation.

**Comment by zhouyx** [comment]
I saw the error from 
https://github.com/ampproject/amphtml/blob/1d93fda7d35ab3412ba9bbc9e31ac417bf6c088d/third_party/subscriptions-project/swg.js#L389-L391

I don't know how the errors got logged, maybe from promise rejection?  @erwinmombay Do you know how can we skip these errors? Thank you

**Comment by dvoytenko** [comment]
Sure. But it's a standard user [cancelation error](https://developer.mozilla.org/en-US/docs/Web/API/DOMException#exception-AbortError). Regardless of where we'd see most of cases coming from, we should just ignore it.

**Comment by erwinmombay** [comment]
@zhouyx we could  detect this in error.js and not report them (might hide other underlying issues), or we can just filter them on the graphs and divert them to a new graph

**Comment by dvoytenko** [comment]
@erwinmombay @zhouyx This is an explicitly "user cancelation" error, similar to our "canceled()" signal. I'd say we should filter out in the `error.js` and not send anywhere at all.
