### ISSUE TITLE
Support submitting form with shortcut

### ISSUE THREAD

**Issue by Bill-SnowWolf** [ampproject/amphtml#21120]
## Describe the new feature or change to an existing feature you'd like to see

We use <textarea> in a form. It would be nice we can set some shortcut to submit form like using '⌘/Ctrl + Enter'.

**Comment by torch2424** [comment]
Triaging to @cvializ , feel free to re-assign 😄

**Comment by cvializ** [comment]
@Bill-SnowWolf thanks for the feature request! This would be a great enhancement to add to amp-form. We don't have resources available to work on this now, but it's the perfect size for our next fixit sprint.

**Comment by caroqliu** [comment]
Unassigning myself for now in case anyone wants to pick up as a GFI

**Comment by neelgeek** [comment]
@caroqliu  I would like to try this.

**Comment by caroqliu** [comment]
Apologies, this feature was already introduced by #26152. This issue must have been a duplicate of #26004. Thanks for your enthusiasm! If you would like to make a contribution related to this change, you could update the `amp-form.md` with information about this interaction pattern. :)
