### ISSUE TITLE
AMP Traffic coming as Direct Traffic.

### ISSUE THREAD

**Issue by mrugeshsingh** [ampproject/amphtml#21133]
**Please only file reports about bugs in AMP here.**

Hi Recently we have installed WP AMP plugin. AMP data is reflecting in Organic as well as in Direct, Why? Direct AMP traffic number is more. Please help to resolve this.

**Comment by torch2424** [comment]
Triaging to @amedina , feel free to re-assign 😄

**Comment by mrugeshsingh** [comment]
???

**Comment by amedina** [comment]
@mrugeshsingh Please file issues related to the official AMP plugin here: https://github.com/ampproject/amp-wp

@torch2424 Feel free to close this issue as we will track it on the AMP plugin repository.

**Comment by torch2424** [comment]
Sounds good! Thanks @amedina 

@mrugeshsingh 

Thanks for filing the issue, see the comment above. Closing this since we are moving the issue. Thanks! 😄
