### ISSUE TITLE
Warn and deprecate amp-foo-latest.js in validator

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#21135]
If folks are using `-latest.js` version of an extensions, it makes it really hard for us to have breaking changes in `v2` without breaking [someone](https://github.com/ampproject/amphtml/issues/21127).

`-latest.js` is just a foot-gun without much benefits since if we don't have to make a breaking change, we don't up the version number anyway.

@Gregable @cramforce @choumx for opinions

**Comment by cramforce** [comment]
We'd need data to see if we can do this. If not, we could

- remove documentation
- hardcode latest to mean the current version of an extension.

**Comment by choumx** [comment]
At a minimum, we can make sure that `-latest.js` only points to a new version of an extension when it is stable and ready for release. I don't believe that's the case today.

**Comment by honeybadgerdontcare** [comment]
Data: ~1.8% of AMP documents are using `latest` for at least one of their script tags.

**Comment by aghassemi** [comment]
I guess that's a lot more than `0.1%` threshold for deprecations. 

How about:
1- I create a separate issue for locking `latest` during build to current version.
2- we no longer add `latest` to new component validator rules.
3- keep this issue for validator to warn in usages of `-latest`.
4- revisit usages after warning has been in place for a year and see if deprecations is doable at that point.

I have not found documentation on `-latest` but only did a quick search.

Regardless of whether `-latest.js` is pointing to a stable or unstable version, I think it is still a foot-gun since even if stable, the API/behaviour have some breaking changes in them.

Do we all agree on removing the whole concept of `-latest.js`?

**Comment by Gregable** [comment]
I'll at least make the counter argument and claim that I think the foot gun isn't that big of a deal, but I don't feel too strongly.

In a world without `-latest`, presumably at some point, we would start deprecating `0.1` (or whichever) and warning users to upgrade. Users would then go and s/0.1/0.2/ blindly and run into the same exact issues. So `-latest` may be the symptom, not the actual foot gun.

I agree with choumx's suggestion that `-latest` should not be `-beta`.

`-latest` provides value to small publishers who do not have separate test and prod, and don't perform regular releases. It's almost always better to be on `-latest` than on an eventually invalid version.

**Comment by aghassemi** [comment]
> It's almost always better to be on `-latest` than on an eventually invalid version

When `latest` changes, it is almost guaranteed it will break the current usage in some way (even if not `beta`), without any prior warnings or time for developers to upgrade v.s. developers ignore 6 months of deprecating warnings or blindly `s/0.1/0.2/` without testing (despite us saying new version contains breaking changes). 

So by choosing `latest` they are picking between:
 _immediate automatic breakage of "something" without their knowledge_ 
_v.s._
_I have almost a year to plan an upgrade or my page may become invalid_

**Comment by lannka** [comment]
> Data: ~1.8% of AMP documents are using `latest` for at least one of their script tags.

@honeybadgerdontcare curious how did you quickly get this number. if possible, could you narrow down to `amp-experiment.js` to see how many usage is that?

**Comment by rsimha** [comment]
With #21190, there are two changes:

- The race between versions to be the latest has been fixed
- The version that becomes the latest is now locked, and will have to be explicitly specified

See [#21190 (comment)](https://github.com/ampproject/amphtml/pull/21190#issue-257273690) for more info.

**Comment by choumx** [comment]
@rsimha Can this be closed now?

**Comment by rsimha** [comment]
@choumx just noticed your question. With #21190, the race to be `*-latest.js` was eliminated. However, the door is still open for extension authors to manually change which version is latest. If that's a good state, then yes, this can be closed.
