### ISSUE TITLE
Internet Explorer amp-image not showing

### ISSUE THREAD

**Issue by unumbox** [ampproject/amphtml#21144]
## What's the issue?

Images are not displayed on Internet Explorer 11. This also impacts the main App Project website.

Update: Other components are not working either such as amp-selector, amp-carousel & amp-accordion.

## How do we reproduce the issue?

Visit any AMP website using Internet Explorer 11

## What browsers are affected?

Internet Explorer 11 on Windows 10

## Which AMP version is affected?

This is a new issue which has appeared in the past couple of days. I cannot find anything reported online despite this issue being seen on many devices all using IE11.

**Comment by robinac30** [comment]
Also experiencing this issue, since at least mid-morning today GMT.

Not just amp-img either, it's also affecting various other components including amp-consent and amp-accordion.

**Comment by cloudb** [comment]
Possibly related to the issues with the getBoundingClientRect polyfill in the last release?

https://github.com/ampproject/amphtml/pull/21026
https://github.com/ampproject/amphtml/commits/3a16823e29300486616699612ff0fe6cf7199452/src/get-bounding-client-rect.js

**Comment by aghassemi** [comment]
@choumx  @jridgewell please take a look. Not sure what the precedence is for rolling back for IE 11 but let's cherry pick at least.

**Comment by SimonHogstromRonbol** [comment]
we are also noticing this issue across all of our amp sites, this is affecting multiple amp components
amp-img amp--carousel, and amp-fx-flying-carpet

this is how ampproject.org looks right now in internet explorer:
![image](https://user-images.githubusercontent.com/32469390/53498386-8c0aa200-3aa6-11e9-8760-6554184659bf.png)

**Comment by choumx** [comment]
Thanks for the report. We're rolling back version 1902191749350 that contains this bug.
