### ISSUE TITLE
🌸 Cherry pick request for #21144 into #20973 (Pending)

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#21147]
## GitHub issue your cherry pick is fixing:

Issue #21144

## PR that you are requesting a cherry pick for:

PR #21026

## Release(s) you requesting this cherry pick into:

Production Release? No

Canary release? Yes

 Release Issue #20973

## Why does this issue meet the [cherry pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

AMP is throwing errors when reading `getBoundingClientRect` in IE (not Edge) due to a broken patch.

/cc @cramforce

**Comment by cramforce** [comment]
Approved.

So, there was an IE only polyfill that didn't actually work?

**Comment by jridgewell** [comment]
Yes, we messed up the function signature: https://github.com/ampproject/amphtml/pull/21026/files

**Comment by zhouyx** [comment]
The fix is in prod now.
