### ISSUE TITLE
AMP Validator is not working

### ISSUE THREAD

**Issue by rishad-sayone** [ampproject/amphtml#21140]
https://validator.ampproject.org/#url=https%3A%2F%2Fwww.google.com%2Famp%2Fs%2Fwww.ampproject.org%2Flatest%2F

Even google amp page is not validating

**Comment by honeybadgerdontcare** [comment]
@rishad-sayone 	pages served by an AMP cache are not necessarily valid AMP as they are not intended to be ingested by other AMP caches and served.

Notice that the original page is valid AMP, which is necessary for AMP caches to ingest and serve:
https://validator.ampproject.org/#url=https%3A%2F%2Fwww.ampproject.org%2Flatest
