### ISSUE TITLE
ITI: Twitch.tv video amp-component

### ISSUE THREAD

**Issue by seergiioo6** [ampproject/amphtml#21141]
This proposed `<amp-twitch-player>` component would enable clips, videos and live streams in AMP pages using the twitch.tv video player.

This would create an iframe with the following source:
https://dev.twitch.tv/docs/embed/video-and-clips/

**Comment by aghassemi** [comment]
Hi @seergiioo6 

Yay! twitch player! 

Please add the API you have in mind in this issue for a quick review.

One requirement we have for video players is to implement the video-interface common API which essentially is a `postMessage` bridge between the component and the iframe to expose methods such as `play`, `pause`, `seekTo`, etc.. and corresponding events. This allows AMP to treat all video players the same and to use it to provide common UX across players such as autoplay, dockable videos, managing playback across players, etc... The interface is fairly straightforward to implement and the reference players mentioned above all implement it as well.

A few good video-players which implement the interface to use as reference are: `amp-brid-player`, amp-youtube, `amp-viqeo-player` and `amp-dailymotion`.

/cc @alanorozco to help you review.

**Comment by alanorozco** [comment]
Nice! 

@aghassemi No controls toggling in the API, so no `dock`. Not sure if it should affect `autoplay`.

**Comment by aghassemi** [comment]
@seergiioo6 do you work at Twitch? 
I somewhat read this issue as an ITI from Twitch devs.

**Comment by seergiioo6** [comment]
Hi @aghassemi , no I don't work at Twitch. 

Okey I'm going to add here the API that I have in mind.

Thank's!

**Comment by seergiioo6** [comment]
# amp-twitch-player
An <code>amp-twitch-player</code> displays the Twitch Player used in <a href="https://www.twitch.tv/">twitch.tv</a> Video Platform.

## Example usage

Video player

```html
<amp-twitch-player
    data-video="13663"
    layout="responsive"
    width="480"
    height="270">
</amp-twitch-player>
```

Live stream player

```html
<amp-twitch-player
    data-channel="mongraal"
    layout="responsive"
    width="480"
    height="270">
</amp-twitch-player>
```
## Attributes
<table>
  <tr>
    <td width="40%"><strong>autoplay</strong></td>
    <td>If this attribute is present, and the browser supports autoplay the video is automatically played when the source is ready.</p>
</td>
  </tr>
  <tr>
    <td width="40%"><strong>data-video</strong></td>
    <td>The twitch.tv video ID.</td>
  </tr>
  <tr>
    <td width="40%"><strong>data-channel</strong></td>
    <td>The twitch.tv channel name.</td>
  </tr>
  <tr>
    <td width="40%"><strong>common attributes</strong></td>
    <td>This element includes <a href="https://www.ampproject.org/docs/reference/common_attributes">common attributes</a> extended to AMP components.</td>
  </tr>
</table>

**Comment by seergiioo6** [comment]
@alanorozco what do you mean when you say: No controls toggling in the API ?

Thanks!

**Comment by alanorozco** [comment]
@seergiioo6 The `VideoInterface` that all AMP video components implement has two methods to show and hide the controls displayed on the video. Twitch doesn't support hiding the video controls. So `dock` is not possible.

`autoplay` is also supposed to hide controls but I'm leaving to @aghassemi to decide whether it's acceptable to enable autoplay without the ability to show/hide controls.

**Comment by aghassemi** [comment]
@seergiioo6 are you creating this component to just use on your own website or do you know of others who are interested in this?

I do like to have this component but I much rather have it work properly with `video-interface` which means we need Twitch folks to make player API changes rather than just another iframe wrapper component with incomplete support. Specially now that we have `amp-video-iframe` in place which @seergiioo6 can use to embed twitch anyway.

**Comment by seergiioo6** [comment]
Just for use on my own website, but also for contributing to the project.

I agree with you @aghassemi. I'm gonna use the amp-video-iframe.

Thank's!

**Comment by alanorozco** [comment]
@seergiioo6 Great, I'll close this then. Let us know in the Slack channel whether you encounter any issues.
