### ISSUE TITLE
Support multiple URL properties in amp-access 

### ISSUE THREAD

**Issue by montmanu** [ampproject/amphtml#2115]
Currently, only a `login` URL is supported by the component. Ideally, multiple (arbitrary) URLs would be supported. One example use case would be to support distinct `login` and `subscribe` URLs. Otherwise, the "return" URL must be hardcoded into the HTML response and will not support returning the user to the AMP viewer. Here is an example configuration:

```json
{
  "authorization": "https://meter-svc.nytimes.com/meter.js?rid=READER_ID&url=CANONICAL_URL&referer=DOCUMENT_REFERRER&peek=true",
  "pingback": "https://meter-svc.nytimes.com/meter.js?rid=READER_ID&url=CANONICAL_URL&referer=DOCUMENT_REFERRER",
  "login": "https://myaccount.nytimes.com/mobile/login/smart/index.html?campaignId=4YLYF&EXIT_URI=RETURN_URL&rid=READER_ID",
  "subscribe": "https://myaccount.nytimes.com/get-started/auth?OC=20000040560&campaignId=4YLYF&return_url=RETURN_URL&rid=READER_ID"
}
```

And example usage:

```html
<!-- ... -->
<a on="tap:amp-access.subscribe">Subscribe Now</a>
<!-- ... -->
<p>Already a subscriber? <a on="tap:amp-access.login">Log in »</a></p>
<!-- ... -->
```

**Comment by dvoytenko** [comment]
@montmanu I have #2082 opened for discussion. It implements an `login` configuration that allows a flexible map of URLs. PTAL.
