### ISSUE TITLE
breaking  layout, social share. in language pt-br

### ISSUE THREAD

**Issue by danilomasato** [ampproject/amphtml#21167]
## How do we reproduce the issue?

<img src="https://github.com/danilomasato/report-ampstories/blob/master/compartilhar.png?raw=true" width="300" height="134">
<img src="https://github.com/danilomasato/report-ampstories/blob/master/obter-link.png?raw=true" width="214" height="238">

## What browsers are affected?

all browsers and devices

## Which AMP version is affected?

version 0.1 and 1.0

**Comment by aghassemi** [comment]
@danilomasato in `amp-story` or AMP in general? Do you have a url to share please?

**Comment by aghassemi** [comment]
@newmuis

**Comment by newmuis** [comment]
These are both `amp-story` bugs
