### ISSUE TITLE
Clean up dynamic-css-classes experiment?

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2116]
Should it still be here?
https://cdn.ampproject.org/experiments.html

**Comment by rudygalfi** [comment]
@jridgewell Is Dynamic CSS classes still experiment-guarded, or is the experiment just in need of cleaning up?

**Comment by jridgewell** [comment]
It's still guarded.

**Comment by rudygalfi** [comment]
Could we launch dynamic CSS classes or is there more work to do? (I'm including validation in this question.)
