### ISSUE TITLE
I2I: Update Google Analytics Opt Out Logic

### ISSUE THREAD

**Issue by leeandrew1693** [ampproject/amphtml#21163]
## Summary
Update the analytics opt out logic to also look for an element ID. 

## Design document
https://docs.google.com/document/d/17kuqk5CLzyC90-JlFN0by-dNLyBsC3iySAVCz84tlsY/edit?usp=sharing

## Motivation
Google Analytics provides an opt out extension that adds a function window['_gaUserPrefs'].ioo() => true. Firefox and Safari apply CSP to the content script, so websites with CSP enabled would not run that script. We are solving this by adding an ID to the script so we can identify opt out by also looking for the element id.

## Additional context
Google Analytics Opt Out Extension: https://tools.google.com/dlpage/gaoptout
Firefox's bug for apply CSP to content script: https://bugzilla.mozilla.org/show_bug.cgi?id=1267027
W3 Standard for CSP and Content Script: https://www.w3.org/TR/CSP/#extensions

/cc @ampproject/wg-approvers @lannka

**Comment by lannka** [comment]
@leeandrew1693 the GA extension right now injects the following element to the DOM:
```
<script type="text/javascript">window["_gaUserPrefs"] = { ioo : function() { return true; } }</script>
```

Can you clarify what element ID are you looking for. If it's not launched yet, what format would it look like? We need to find a generic configurable solution for all analytics vendors to do this.

**Comment by leeandrew1693** [comment]
@lannka I've updated the issue with a design document with a generic solution that all analytics vendors could use. 

You can find the doc here: https://docs.google.com/document/d/17kuqk5CLzyC90-JlFN0by-dNLyBsC3iySAVCz84tlsY/edit?usp=sharing

**Comment by lannka** [comment]
I checked the existing opt-out approach is only adopted by Google Analytics. And it's also a vendor only configuration. So you don't need to support both, and you can just migrate over to the new approach.

**Comment by leeandrew1693** [comment]
@zikas had pointed out to me that the final configuration consisted of the vendor configuration and a remote configuration. One of the customers that uses the remote configuration for optout is Google Tag Manager, but there could be other customers that send the opt out configuration. I think its worth keeping the backwards compatibility to make sure we don't inadvertently break anyone.

Where we load remote config:
https://github.com/ampproject/amphtml/blob/e01e846da7797e412f1909d42a30f4b81a207754/extensions/amp-analytics/0.1/amp-analytics.js#L224 https://github.com/ampproject/amphtml/blob/e01e846da7797e412f1909d42a30f4b81a207754/extensions/amp-analytics/0.1/config.js#L68

**Comment by lannka** [comment]
I was looking at this code, where we don't allow optout to be configured remotely.

https://github.com/ampproject/amphtml/blob/77afebb73153c899a88f60f5b3ac32fb3f894d75/extensions/amp-analytics/0.1/config.js#L392-L395

Then I realized we made an exception for `_gaUserPrefs.ioo`.

Can we come up with a deprecation plan? We don't need 2 ways to do opt-out and neither of them seemed to be very extendable solution to other vendors.

**Comment by zikas** [comment]
As long as this is vendors-only feature I believe we'll just need to be backward-compatible until GTM updates. It's a trivial change and will take ~1 week to rollout. After this is done, we can remove string optout support.

**Comment by lannka** [comment]
@zikas that sounds good.

BTW, have we thought about having those browser extensions to remove `amp-analytics type=googleanalytics` tags?

**Comment by zikas** [comment]
You mean for opt-out purposes? 

One of the reasons is because the same opt-out mechanism is supported by analytics.js. 
Extension just provides a signal that does not depend on the library (amp vs anaytics.js) that is used.

**Comment by lannka** [comment]
Done by #21163
