### ISSUE TITLE
legacy carousel: high-trust slideChange event when slide is changed without a user gesture.

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#21171]
# Summary
`slideChange` event of `amp-carousel` fires whenever a slide changes. Currently this event fires as a `hight-trust` event in all cases.

Starting **April 2, 2019** (6 weeks from now based on AMP's deprecation policy). This event will start firing as `low-trust` when a slide is changed without user interaction such as result of `autoplay` or when `goToSlide` action is called from a low-trust event such as `scroll`

If users manually change slides, the event would still be `high-trust`.

# How to migrate
If you are not using the `slideChange` event when `autoplay` is set on `amp-carousel` or when `toGoSlide` is called from a low-trust event, this change does not impact you.

If you rely on running an action when slides changes automatically or via low-trust events such as scroll or video play, make sure you only call an action that accepts `low-trust` events such as `amp-animation's` `start` event. (which can be used to change certain CSS properties such as `opacity`, `transform` and `visibility`)

# Reason
This changes was [not](https://github.com/ampproject/amphtml/issues/12206#issuecomment-356756104) intended and was made by mistake. AMP does not allow high-trust events without user-interaction to prevent disruptive UI changes without user's involvement.

Related issues: 

https://github.com/ampproject/amphtml/issues/12206 https://github.com/ampproject/amphtml/issues/20697

@leonalicious @88kbbq
@ampproject/wg-ui-and-a11y @choumx we require 3 core committer approvals to proceed. Please reply with your objections or approvals.

**Comment by sparhami** [comment]
I approve of this change. I just want to make sure that we preserve the trust level if the slide change occurred via an action (since changing slides requres a low trust action). So a low trust action changing slides should result in a low trust event, and a high trust action should result in a high trust event.

**Comment by aghassemi** [comment]
@sparhami agreed. Updated accordingly

**Comment by nainar** [comment]
As per the deprecation policy [here](https://github.com/ampproject/amphtml/blob/master/spec/amp-versioning-policy.md#deprecations) we needed to allow for at least 2 weeks of open discussion. This discussion had been happening [here](https://github.com/ampproject/amphtml/issues/20697) as per OP's post.  We can proceed with the process by getting 3 approvals from core committers.

**Comment by cathyxz** [comment]
Approve. 
Noting that: 
>If users manually change slides, the event would still be `high-trust`.

**Comment by cvializ** [comment]
Approve.

**Comment by alanorozco** [comment]
![giphy](https://user-images.githubusercontent.com/254946/53584315-3088f480-3b38-11e9-8eb7-969f4e32d1f6.gif)

**Comment by nainar** [comment]
Approve with the understanding that this feature has less usage than a deprecation threshold and has been out for <6 months. 

Would ask that we tweet about this so that we can get some attention on this so that potentially affected partners can be alerted (not everyone checks GitHub)

**Comment by choumx** [comment]
LGTM

**Comment by aghassemi** [comment]
Reminder that this will be disabled in 2 weeks.

**Comment by aghassemi** [comment]
We are delaying this by 3 weeks to allow more time for changes. New effective date is April 23
/cc @leonalicious @ampproject/wg-ui-and-a11y

**Comment by aghassemi** [comment]
@ampproject/wg-ui-and-a11y @nainar:

I have looked at some usages of this and all of them seem be to for `dots` UI in Carousel. I have not found any abuse cases yet.

Given: 
- We don't have a solution for updating `dots` with `autoplay` for carousel until `amp-inline-gallery` is launched
- There are no abuse cases yet.

I like to suggest we postpone this deprecation until after `amp-inline-gallery` is launched.

Thoughts?

**Comment by aghassemi** [comment]
@sparhami let's disable this when `inline-gallery` is launched so folks can migrate and still have dots (that's the main use-case for this)
