### ISSUE TITLE
amp linker won't decorate AMP.navigateTo()

### ISSUE THREAD

**Issue by AndrewKGuan** [ampproject/amphtml#21170]
AMP linker doesn't seems to decorate AMP.navigateTo destinations with CIDs.

If I have 
`<form id="myform" on="submit:AMP.navigateTo(url="MY/THANK_YOU/PAGE>")">`

The user won't be able to enter to that destination domain with a CID.

**Comment by calebcordry** [comment]
cc/ @jeffjose

**Comment by jeffjose** [comment]
Thanks for the bug report. Andrew.

Can you provide more details on the impact of this bug please?

**Comment by AndrewKGuan** [comment]
Hi all,
just a quick check to see how far this issue has been addressed?

**Comment by jeffjose** [comment]
Hi Andrew, Can you provide more context on where this is being impacted? It'll help us prioritize the bug in our weekly sprint. Thanks!

**Comment by AndrewKGuan** [comment]
All forms that are redirected to a submit result page such as a 'thank you' page will need to use this because:

- amp-form won't allow a regular post, xhr will have to be used instead.

- after the xhr comes back, NavigateTo is the only way to forward to that submit result page if the destination cannot/should not be determined on the xhr response. Example, if submit-success and submit-error have different destinations, it won't be easily doable without navigateTo

Also this is only one use case of navigateTo.  I don't how many other usages are there.
