### ISSUE TITLE
Learn More Link Not Working on AMP

### ISSUE THREAD

**Issue by lgrrealag** [ampproject/amphtml#21179]
The "Learn More" link on video ads that are loading in an iframe on an AMP page are not tapable/clickable.

For example. If you visit this post on a mobile and play the video (you should get an ad) Trying to tap the Learn More just pauses or plays the video.

https://amp-realagriculture-com.cdn.ampproject.org/c/s/amp.realagriculture.com/2019/02/fit-farmer-ep-8-remote-support-and-quick-workouts-close-the-gap-on-farm-based-fitness/

Yet if you visit the same page on our desktop site on your mobile and play the video, the learn more link it tapable/clickable and opens in a new tab.

This link redirects to the desktop site of the same post
https://amp.realagriculture.com/noamp.php?url=aHR0cHM6Ly93d3cucmVhbGFncmljdWx0dXJlLmNvbS8yMDE5LzAyL2ZpdC1mYXJtZXItZXAtOC1yZW1vdGUtc3VwcG9ydC1hbmQtcXVpY2std29ya291dHMtY2xvc2UtdGhlLWdhcC1vbi1mYXJtLWJhc2VkLWZpdG5lc3Mv

The player is loaded in an iframe and is identical the only difference is one is on AMP and the other is not.

**Comment by aghassemi** [comment]
@lgrrealag `amp-iframe` are sandboxed by default. You would need to add  `allow-popups` and `allow-popups-to-escape-sandbox` to the `sandbox` attribute for any links to `_blank` to work.

**Comment by aghassemi** [comment]
closing per comment above

**Comment by lgrrealag** [comment]
Thank you.
