### ISSUE TITLE
`git clone` on Travis seems to be getting rate limited by GitHub

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#21175]
**On my laptop:**
`git clone --depth=50 git@github.com:ampproject/amphtml.git` takes ~5 sec at ~35 MiB/s

**On Travis:**
`git clone --depth=50 https://github.com/ampproject/amphtml.git` takes ~1 min at ~2 MiB/s

See https://travis-ci.org/ampproject/amphtml/jobs/499582953#L224

This is likely due to a rate-limit for unauthenticated cloning. Let's investigate a way to speed up `git clone` on Travis.

**Related:**
https://docs.travis-ci.com/user/customizing-the-build/#git-clone-depth
https://github.com/travis-ci/travis-ci/issues/9216 ☹️

**Comment by rsimha** [comment]
From looking at [this](https://travis-ci.org/ampproject/amphtml/jobs/514529637#L231) run today, `git clone` on Travis took multiple minutes at ~300 KiB/s.

@estherkim IIRC, you recently investigated authenticated cloning on Windows. Can we deploy this for our linux VMs?

**Comment by rsimha** [comment]
The way to do an authenticated clone is described at https://docs.travis-ci.com/user/customizing-the-build/#authentication

/cc @erwinmombay to create a read-only token using the bot account he manages.

**Comment by rsimha** [comment]
Assigning to @estherkim. Thanks for looking into this!

**Comment by estherkim** [comment]
Following up - After some digging, I determined that Travis is not getting rate limited by Github. `git clone` is not the same as a GitHub API call, which is rate limited. For example, I can `git clone` all day using an oauth token, but it doesn't decrement the account's remaining rate limit. Regardless of the rate limit, I can't prove the assumption that an authenticated call is faster.

I suspect the slowness might be on Travis' end. I followed up with them with several examples and will update this issue when I hear back.

**Comment by estherkim** [comment]
Following up the follow up - Travis suggested to decrease the depth limit. Haven't seen any slowness recently. 

@rsimha ok to close?

**Comment by rsimha** [comment]
This seems to have settled down. Thanks for investigating to make sure there's nothing missing on our side. Good to close!

**Comment by rsimha** [comment]
Found a recent (stray) instance of clone taking ~9 minutes: https://travis-ci.org/ampproject/amphtml/jobs/563339357#L233

![image](https://user-images.githubusercontent.com/26553114/61897111-58f8fd00-aee4-11e9-989e-b711bf42378f.png)

Adding here for documentaion. Nothing actionable for now.
