### ISSUE TITLE
Tapping on auto-playing amp-ima-video, amp-youtube pauses it on Chrome 72 (74 is fine)

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#21188]
on tasty.co and https://ampbyexample.com/components/amp-ima-video/ tapping any auto playing video's pauses it. it is supposed to just unmute it and keep playing.

This does not happen on Safari or with `amp-video` regardless of browser.

/to @torch2424 @alanorozco 
Setting to P1, I think we should patch Canary with a fix.

**Comment by aghassemi** [comment]
happens with `amp-youtube` as well.

Chrome 72

**Comment by aghassemi** [comment]
Doesn't happen in Chrome 74. Looks like a Chrome regression in 72. I will follow up with Chrome

**Comment by aghassemi** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=925331

**Comment by torch2424** [comment]
@aghassemi Thank you for the investigation! 😄 

FYI @curseagain . No action needed on our part currently, but in case someone at tasty asks about it. 👍
