### ISSUE TITLE
Visual tests are flaking due to loader dots

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#21181]
For example, https://percy.io/ampproject/amphtml/builds/1502495/view/100209590/1400?mode=diff&browser=firefox&snapshot=100209590

This might be related the ongoing effort to change the page-loading UX.

/to @danielrozenberg 
/cc @aghassemi @nainar @andrewwatterson

**Comment by aghassemi** [comment]
we haven't pushed any changes for new loaders yet.

**Comment by danielrozenberg** [comment]
I looked through all the Percy builds from the past 3 days and it doesn't look like there's a repeating loader-dot related flakiness going on, except this one build. It's extremely difficult to debug one-time flakes, so closing for now - reopen if this become repeated
