### ISSUE TITLE
Make transient amp-user-notification 

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2118]
My understanding is that right now, without URLs, we always save state to local storage.

I think we should allow opt-in that the notification just always shows and dismissal is just for closing it.

CC @rudygalfi

**Comment by erwinmombay** [comment]
seems straightforward, what should be the default though? should saving to local storage be the default? (that seems to be implied in your opt in statement).

**Comment by rudygalfi** [comment]
We could have alternatives for the `data-show-if-href` and `data-dismiss-href`:

Instead of `data-show-if-href` --> `show-always` to opt-in to always showing
Instead of `data-dismiss-href` --> `forget-dismissal` to opt-in to not storing the dismissal

**Comment by rudygalfi** [comment]
Or maybe there's just `show-always`? If `forget-dismissal` were set then the result of `show-always` is determined unless the configuration for the notification itself has changed (it was previously possible for the dismissal to be stored but now the policy is to always show).

**Comment by dvoytenko** [comment]
I like `show-always` - it's pretty straightforward and understandable and lets the rest of the system to work w/o changes.

**Comment by rudygalfi** [comment]
By the way, `always-show` might be the better way to word it.

**Comment by cramforce** [comment]
Use case are notifications like: You have 8 articles left in this months.
Which you can't really perma-dismiss :)

**Comment by dvoytenko** [comment]
Yeah. That case we currently serve via `position:fixed` element right now and it's ok, I think. There are other things that make them a bit incompatible. So, I'm not yet 100% sold that this should be a `amp-user-notification`. And also, sometimes the metering "notification" is shown inline, not as an alert.

**Comment by mkhatib** [comment]
Is anybody working on this? Happy to take a look.

**Comment by erwinmombay** [comment]
@mkhatib feel free

**Comment by mkhatib** [comment]
Alright, so for `always-show`. Should that be the strongest value in case other attributes were also provided. For example, `always-show` and `data-show-if-href`? The logical thing to do is just ignore `data-show-if-href` results and just you know `always-show`. 

Should we error if both attributes are provided, or just quietly ignore it?

**Comment by dvoytenko** [comment]
No, they mean somewhat different things. I'd think of `data-show-if-href` as a programatic filter: e.g. it looks at the user and decides where the user should see the notification. For instance, "anyone outside of UK should see this message".

`always-show`, on the other hand, turns off the mode that says "only show the message once and after dismissed, don't show again". So, for some use cases, we don't want this "show-only-once" feature.

**Comment by mkhatib** [comment]
So this means only if `show-if-href`returns `true` then `always-show` kicks off? But if it returned false then it wouldn't show it even though `always-show` is set?

**Comment by dvoytenko** [comment]
No. It means that you should get to the `show-if-href` at all when `always-show` is on. Here's the order right now:
1. Check if the user has already dismissed the notification (a flag that's stored locally)
2. If `data-show-if-href` specified, check if the remote endpoint "wants" us to show the message

So, currently it doesn't even get past the first step when there's a local flag already set. In our case - we won't even set a local flag at all. And we can bypass reading it as well.

**Comment by mkhatib** [comment]
bwt - should we expect a value for `always-show="true"` attribute or just check its existence `always-show` regardless of its value?

**Comment by rudygalfi** [comment]
My sense is that `always-show` and the `data-*` attributes are mutually exclusive. Should we allow for one group to be specified when the other group is also present or do a validation error?

Stylistically `always-show` on its own seems more correct that `always-show="true"`, but I imagine there's some established pattern for the semantics of how this works and we should just look into what that is and follow it.

**Comment by erwinmombay** [comment]
im also in favor of just the property with no value (just `always-show`)

**Comment by erwinmombay** [comment]
@dvoytenko just for clarification: 

*No. It means that you should get to the show-if-href at all when always-show is on.* 

**Did you mean:**

No. It means that you **shouldn't** get to the show-if-href at all when always-show is on.

**Comment by dvoytenko** [comment]
No, I meant "should".

**Comment by erwinmombay** [comment]
@dvoytenko thanks, got confused with the "at all" part.

**Comment by mkhatib** [comment]
This has already been implemented in #2215
