### ISSUE TITLE
Allow to force amp-ad to target _top

### ISSUE THREAD

**Issue by francesconatali** [ampproject/amphtml#21197]
## Problem

In a webview **INSIDE** an app on iOS, links with target "_blank" do not open. So when using amp-ad (_again, seeing the html via a browser inside an app, not when just browsing_) the **AdSense** adverts trying to open a new tab (__blank_) do **not** work.

## Solution

On Google Ad Manager it is possible to set-up an ad slot to open only in a specific way (_top or _blank). It would be great if the same was possible with Ad Sense. 

Or, it would be great to allow something like **click-target="_top"** inside an amp-ad.

Example:

```
<amp-ad width="320" height="50"
          type="adsense"
          click-target="_top"
          data-ad-client="ca-pub-123"
          data-ad-slot="123">
</amp-ad>
```

At this point in time, the above code does not validate as AMP page (due to click-target="_top").

**Comment by francesconatali** [comment]
Interestingly, it is possible to specify the Click Target with **amp-ad-exit**. It would great if it was extended to **amp-ad** as well.

**Comment by torch2424** [comment]
Triaging to @zhouyx , feel free to re-assign 😄

**Comment by zhouyx** [comment]
Sounds like this needs the ad vendor support. to @ampproject/wg-ads

**Comment by lannka** [comment]
@keithwrightbos @jeffkaufman  I'm wondering how this is done in Ad Manager, would that need a flag in request?
