### ISSUE TITLE
[amp-list-load-more] Cannot bind state

### ISSUE THREAD

**Issue by palances** [ampproject/amphtml#21195]
## What's the issue?

Cannot bind state when using load-more="auto" and with load-more ="manual" loaded 2nd page then 1st page's state will not workable 

## How do we reproduce the issue?

- Setup load-more="auto" and bind state after render.

![auto](https://user-images.githubusercontent.com/330330/53614396-c98d3d80-3c14-11e9-8e57-64d1f0906ea5.gif)

- Check [here](https://m.lightinthebox.com/de) with manual scenario，please scroll to the bottom, click on load more and back to previous amp-list-load-more page, click on the heart icon
![manual](https://user-images.githubusercontent.com/330330/53614104-97c7a700-3c13-11e9-9aa0-c34f9fbdda98.gif)

## What browsers are affected?

All browsers

## Which AMP version is affected?

AMP Version : 1902271810270

**Comment by cathyxz** [comment]
TIL people use `<amp-state>` templated inside `<amp-list>`. Wow. Note to eng, here's the relevant piece of sample code: 

```
<amp-list src="something" 
  load-more="manual" load-more-bookmark="next"  
  layout="fill"  items="." noloading single-item="." overflow>
    <template type="amp-mustache">
     {{#items}}
     <amp-state id="fav_state{{id}}" hidden aria-hidden="true">
     <script type="application/json">
     {
     "count":"{{favorite_times}}",
     "value":"{{isFavorited}}"
     }
     </script>
     </amp-state>
```

A test verifying usage of `<amp-state>` within `amp-list-load-more` for each payload would suffice here. 

/fyi @nainar this is possibly good use case to ensure parity with for amp-list v2.

**Comment by nainar** [comment]
FYI: Added to amp-list V2 document.

**Comment by cathyxz** [comment]
So it seems to be the case that the internal `<amp-state>` has the correct representation of the state, but the `bindings` are only updating those from the most recent load. 

<img width="859" alt="screen shot 2019-03-04 at 2 50 08 pm" src="https://user-images.githubusercontent.com/1528181/53768163-dc11ac00-3e8c-11e9-8882-e236ce9d2b07.png">
