### ISSUE TITLE
Set default log level via AMP experiment

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#21201]
Add a cookie equivalent of `#log=n` flag. 
Add setting level in cookie to experiments page on cdn.ampproject.org

This is mostly a developer convenience feature.

**Comment by alabiaga** [comment]
Hey Jon, just wanted to note here for the sake of being explicit that I imagine that all the other means at which the log level is set will take precedence over the cookie level log, which will be checked last. The order that the log level is set is currently:

1. If window.console is not supported, logging is disabled
2. Set via hash query #log
3. Is LogLevel.FINE if mode is `test` or log level overridden via AMP.overrideLogLevel(level)
4. If local dev by default LogLevel.INFO unless overridden by `#log`.
5. Set via cookie **(NEW)**

code details [here](https://cs.corp.google.com/github/ampproject/amphtml/src/log.js?q=%23log+file:%5Eampproject/amphtml/+package:%5Egithub$&dr=C&l=136) and step 5 being the cookie level log setting.

To me, this makes most sense. That is unless you had a different order in mind? Do you think this is worth bringing up briefly in a design review?

**Comment by jpettitt** [comment]
SGTM

**Comment by cathyxz** [comment]
You can also do this in the console using `AMP.setLogLevel(LEVEL)`, it's just kind of unintuitive.

**Comment by jpettitt** [comment]
@cathyxz Unless I missed something that's not persistent across page loads so it makes it hard to do things like watch log events for a page in the top stories carousel.

**Comment by cathyxz** [comment]
Ah I see. `AMP.setLogLevel(LEVEL)` suffices for a lot of use cases I come across, which primarily involves trying to get an output for intermediate `amp-states` in usage of `amp-bind`, which is why I thought it could be useful. But yes, it won't persist across page loads.

**Comment by jpettitt** [comment]
Yeah, my use case is testing `amp-subscriptions`. With `#log=3` all possible subscriptions analytics events log to console (even if there is no `amp-analytics` trigger waiting for them) however they mostly happen as the page loads and renders so having something persistent is really useful.
