### ISSUE TITLE
Scroll to top in IOS

### ISSUE THREAD

**Issue by Publimix** [ampproject/amphtml#21221]
## What's the issue?

When a form element (input, textarea etc.) that is declared FIXED in CSS or inside a FIXED parent, becomes focused (is clicked), the page is scrolling automatically to the top of the page. This is not happening in a normal html page, only in AMP version (all the other elements are exactly the same).

## How do we reproduce the issue?

https://publimix.ro/temporarAMP

The above link is the AMP version page
1. Scroll until the header element (H1 text on white background disappears) and the background start to change its color. 
2. Click inside the FIXED input element.
3. At this moment the content scrolls automatically to the top, loosing the position where the user was.

https://publimix.ro/temporar

The above link is the HTML version page. All the steps 1-2 have the same behavior. In step 3, the input gets the focus leaving the scroll to the position it was. Clicking outside, will just close the IOS keyboard and return in the content at the previous point vertically.

## What browsers are affected?

Apple Iphone 6S, IOS 8.1.2, Safari browser

## Which AMP version is affected?

Here are two screenshots with the input element focused. First is the HTML version, second the AMP.

![htmlversion](https://user-images.githubusercontent.com/37850630/53695000-b74f0300-3dbe-11e9-8579-5a74dcf71d25.PNG)

![ampversion](https://user-images.githubusercontent.com/37850630/53695003-c59d1f00-3dbe-11e9-9fb6-77bc3ae9a85f.PNG)

**Comment by aghassemi** [comment]
Looks like a side effect of transferring to Fixed layer. Not sure if much can be done.
/to @jridgewell

**Comment by jridgewell** [comment]
We could avoid transferring `input`s to `FixedLayer`. I'm not sure of any usecases that would have the input being position-fixed.

**Comment by aghassemi** [comment]
Given iOS 12.2 _may_ ship with a fix (a few patches have landed on Webkit) for the whole iframe scroll and position fixed issues - removing the need for fixed layer - probably not worth trying to workaround this.

**Comment by jridgewell** [comment]
I like that.

**Comment by Publimix** [comment]
Thank you! I can confirm that from IOS 11 forward that bug does not appear any longer.

**Comment by choumx** [comment]
Closing since this is fixed in iOS 11+.
