### ISSUE TITLE
URL variable substitution is not happening when clicking with wheel mouse button (Open in new tab) from Chrome

### ISSUE THREAD

**Issue by cappsool** [ampproject/amphtml#21220]
when having an a element that includes href with variable substitution, for example:
`<a href="/open?clientid=CLIENT_ID(_ga)&utm_source=QUERY_PARAM(utm_source)"  data-amp-replace="CLIENT_ID QUERY_PARAM" target="_blank">open</a>`

and clicking on it with the mouse wheel (to open in a new tab), variable substitution is not happening (using desktop Chrome).

When clicking with the left mouse button it works OK.

Chrome changed the event from "click" to "auxclick" and this is not handled in AMP code (src/service/navigation.js)
In other browsers it works OK.

see:
https://www.chromestatus.com/feature/5663174342737920

BTW, right click -> open in new tab was handled in #14768

**Comment by torch2424** [comment]
Triaging to @alabiaga , feel free to re-assign 😄

**Comment by reulison** [comment]
this works for AMP STORIES?
