### ISSUE TITLE
Expose IP Address as a platform variable

### ISSUE THREAD

**Issue by shishirm** [ampproject/amphtml#21228]
## Describe the new feature or change to an existing feature you'd like to see

Very often backend systems and 3rd party providers are rigid and unable to determine IP address on the server. In such instances, non-AMP sites execute JS on the page to determine the IP address that is then submitted as a variable along with forms. 

Doing this in AMP is a little convoluted and so the request is to expose the IP Address as a platform variable.

## Describe alternatives you've considered

The alternative is to remotely set amp-state where the server attempts to determine the IP address from the request, constructs a JSON in real time and returns it back to the device. This state is then queried when needed.

## Additional context

None

**Comment by jpettitt** [comment]
What is the use case for this?

**Comment by shishirm** [comment]
Hi @jpettitt - Copy pasting from above,

"Very often backend systems and 3rd party providers are rigid and unable to determine IP address on the server. In such instances, non-AMP sites execute JS on the page to determine the IP address that is then submitted as a variable along with forms.

Doing this in AMP is a little convoluted and so the request is to expose the IP Address as a platform variable."

**Comment by jpettitt** [comment]
I saw what you wanted to do, I'm wondering why you need the users IP?

**Comment by shishirm** [comment]
I'm working with a partner and I believe it is for analytics and tracking purposes. 

However I was not aware that the browser is unaware of the external IP. Has this been a common concern and something which might be worthy of implementing. Like potentially including that in the call out to the AMP Cache?

If this is not something a lot of partners are asking about and will need significant amount of work to build out, feel free to de-prioritize.

**Comment by jpettitt** [comment]
Given that the browser is working with a local IP (example 192.168.0.10) that is mapped to an external address by NAT in the router or proxied by firewalls there is no easy way for the browser to determine it's external IP.

To determine it's IP a browser must connect to a server endpoint which can then reflect back the IP it sees the connection originate from.  Given the need for a server endpoint developers who desire to know the browser IP will need to create an endpoint that logs it along with the analytics message. Most CDN's provide this info in an http header.

Closing as infeasible.
