### ISSUE TITLE
Integrate the new UAv2 API into AMP

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#21240]
See:
https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/nkTDR8AUlwM%5B1-25%5D
https://mustaqahmed.github.io/user-activation-delegation/

We would need to feature detects this and add `{transferUserActivation: true}` to `postMessages` we send as part of `VideoInterface` messages we send to video players.

**Comment by aghassemi** [comment]
related: https://github.com/ampproject/amphtml/issues/21188

**Comment by nainar** [comment]
@aghassemi is this a bug or a FR?

**Comment by aghassemi** [comment]
@alanorozco is aware of the details here and is working on a workaround that does not require the exact approach mentioned here.

tl;dr: `{transferUserActivation: true}` proposal did not get traction and Chrome may not launch this as is.

**Comment by aghassemi** [comment]
related: https://github.com/ampproject/amphtml/issues/21247
