### ISSUE TITLE
Intent to Implement: JW Player cloud-hosted video embed

### ISSUE THREAD

**Issue by johnluther** [ampproject/amphtml#2125]
JW Player proposes an `<amp-jwplayer>` component to enable video playback in AMP pages using our cloud-hosted video player. To use the component, a JW Player account would be required (free accounts are available at [jwplayer.com/signup](http://jwplayer.com/signup).

A cloud-hosted JW Player loads the player as well as the video content, thumbnails, captions, etc. from a single HTTP location on the JW Platform content server. In the case of AMP pages, an embedded iframe would be used.

Example:

```html
<amp-jwplayer
    data-media-id="aBcD1234"
    data-video-id="1234"
    layout="responsive"
    width="16" height="9">
</amp-jwplayer>
```

This markup would create an AMP iframe with the src https://content.jwplatform.com/players/aBcD1234-1234.html. The JW Player media-id and player-id parameters are required and accessible in the publisher’s JW Dashboard. The width and height attributes determine the aspect ratio of the Player in responsive layouts.

More info can be found in our [forked repo](https://github.com/jwplayer/amphtml/blob/amp-jwplayer/extensions/amp-jwplayer/amp-jwplayer.md).

Pull request to follow once we get an LGTM.

Thanks--
JL

**Comment by cramforce** [comment]
LGTM.

Love the `width="16" height="9"`

**Comment by johnluther** [comment]
Thanks, Malte, @pablos1 will create the PR after we polish up a few things.

JL

**Comment by pablos1** [comment]
> Love the `width="16" height="9"`

`responsive` FTW :+1:

**Comment by rudygalfi** [comment]
:+1: By the way, in your doc you had a "?" for the "Availability". This would immediately go to stable, so you can specify "Stable" there.

**Comment by pablos1** [comment]
Done.

**Comment by dvoytenko** [comment]
The validator request filed in #2734. /cc @Gregable

**Comment by mkhatib** [comment]
This has already been done. Please re-open if anything else needed.
