### ISSUE TITLE
I2I: amp-story version 0.1 deprecation

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#21251]
## Summary
We would like to deprecate version 0.1 of the `amp-story` extension, since it has limited functionality and requires whitelisting for use.

## Motivation
[amp-story 1.0](https://amphtml.wordpress.com/2018/07/16/new-in-amp-stories-monetization-revamped-bookends-and-metadata/) has been launched since July 2018 and does not require whitelisting for use.  

/cc @ampproject/wg-approvers
/cc @ampproject/wg-stories 
/cc @Gregable

**Comment by Gregable** [comment]
I approve of this change.

**Comment by dvoytenko** [comment]
@newmuis Is this deprecation intended to follow the normal deprecation schedule?

**Comment by newmuis** [comment]
We've been advocating for this deprecation since July, so I think we could move a bit quicker here.  Additionally, amp-story 0.1 was an origin trial that informed users of its own deprecation policy, and collected contact information so that developers may be contacted when it is being deprecated.

That message has been sent to all who signed up, as well as cross-posted in the `#amp-story` Slack channel and the `amp-story` spec.

**Comment by dvoytenko** [comment]
Can you qualify "a bit quicker"?

**Comment by newmuis** [comment]
I think it would be great to mark 0.1 with the deprecated warning in the validator (#21252) as soon as possible, essentially.  The validator has already been serving deprecation warnings for the primary use cases for several months, and the only case for which we are not currently serving a warning is the easiest fix: the case where publishers have updated to use the new extension APIs, but have not updated the version in the script.  We would like to make those people in that category aware of this as soon as possible.

Separately, we have already sent deprecation notices over several channels, including direct emails to all whitelisted users of version 0.1.

As for the final deprecation date (i.e. the date that usage of `amp-story-0.1.js` becomes invalid AMP), I would love if we could do that within the next month.

**Comment by newmuis** [comment]
@dvoytenko @Gregable does this sound reasonable?  I would love to get a new concrete date, since we have previously been communicating March 19, 2019 as the deprecation date; if we want to change that we should communicate that ASAP.

**Comment by Gregable** [comment]
OK with me.

**Comment by newmuis** [comment]
How about this as a concrete proposal:

Let's assume a final deprecation date (i.e. the date that usage of amp-story-0.1.js becomes invalid AMP) of 2019-04-09

| # | Date | Action Item |
| - | ----- | ----------- |
| 1 | 2019-03-08 | Submit #21252, which will give anyone using amp-story-0.1.js a deprecation warning, once this PR reaches production |
| 2 | 2019-03-08 | Send a message to amphtml-announce list with the 2019-04-09 deprecation date |
| 3 | 2019-03-08 | Send a message to amp-story-origin-trial list with the revised 2019-04-09 deprecation date |
| 4 | 2019-03-08 | Send a message to #amp-story slack channel with the revised 2019-04-09 deprecation date |
| 5 | 2019-04-02 (targeting 2019-04-09 rollout) | Submit #21246, making amp-story-0.1.js invalid |
| 6 | 2019-04-02 (targeting 2019-04-09 rollout) | Alias amp-story-0.1.js to amp-story-1.0.js |
| 7 | Anytime after 2019-04-09 | Delete `extensions/amp-story/0.1/` directory |

**Comment by Gregable** [comment]
Can we also propose a deprecation->error date for the validation to correspond with removing the alias?

**Comment by newmuis** [comment]
I've edited (5) to call that out more explicitly.

**Comment by cramforce** [comment]
What is the scale of remaining usage?

We should definitely move ahead with the warning ASAP and then monitor how usage progresses.

**Comment by newmuis** [comment]
On the order of 1k documents.

**Comment by cramforce** [comment]
How many domains?

**Comment by newmuis** [comment]
On the order of 100.  As a note, this is also why I would like to get the deprecation warning through to the validator as soon as possible.

**Comment by newmuis** [comment]
ping @ampproject/wg-approvers, can we go ahead with the proposal outlined [above](https://github.com/ampproject/amphtml/issues/21251#issuecomment-471022716)?  The dates will now need to change, but the order of the events should stay the same.

**Comment by newmuis** [comment]
Ping @ampproject/wg-approvers again.  #22575 fixes a high-priority issue that ideally never would have happened if we had deprecated this 🙃

**Comment by jridgewell** [comment]
I approve.

**Comment by dvoytenko** [comment]
Last time we brought it up, @cramforce had concerns. Please follow up.

**Comment by choumx** [comment]
It's already deprecated with a validator warning  in #21570 right? Are we discussing code removal now?

**Comment by newmuis** [comment]
Yes, making it invalid and deleting the code.

**Comment by choumx** [comment]
Note that the current recommended timeline from deprecation to invalidation is one year, though in hindsight this might be too long.

> A version must not be invalidated until it has been deprecated for at least 1 year.

Do we output a runtime warning for users of amp-story-0.1?

**Comment by cramforce** [comment]
Me can make exceptions. It just depends on the actual usage.

**Comment by Enriqe** [comment]
> Do we output a runtime warning for users of amp-story-0.1 (for dirty AMPs)?

Yes, as of #21570

**Comment by newmuis** [comment]
This has been "deprecated" since April 2018, and actually has been issuing deprecation notices since #14192 for all cases except for the case of following the 1.0 spec while still using the 0.1 JS.  That case has been issuing deprecation notices since #21570, as @Enriqe notes above.

**Comment by newmuis** [comment]
> Last time we brought it up, @cramforce had concerns. Please follow up.

Followed up with @cramforce separately, and he didn't have any concerns here.  I'll follow up with #21246.
