### ISSUE TITLE
Unskip failing `amp-recaptcha-input` tests on Firefox / Edge

### ISSUE THREAD

**Issue by torch2424** [ampproject/amphtml#21256]
relates to #21148
relates to #20541

Currently the tests are being skipped only for Firefox. We should investigate and fix this.

Example build: https://travis-ci.org/ampproject/amphtml/jobs/499342921#L2361-L2381

**Comment by torch2424** [comment]
cc @rsimha 

So I have two suspicions for this:

1. I did some investigation, and it seems like amp-form tests are also skipped for Firefox. So since `amp-recaptcha-input` depends on form, this is possibly one reason why?

2. The build shows amp-recaptcha-input is failing to layout. This tests requires layoutCallback to be called. E.g the test will fail if run in like a background tab or something. Is this a common problem with out firefox tests?

Thank you!

**Comment by rsimha** [comment]
1. You could eliminate this possibility by running the tests in isolation, and then together (with `--files`)
2. Pretty sure integration tests are not run in a background tab. If you suspect this, you could start a PR to enable the tests and examine the videos from the ensuing sauce labs run on Travis.

**Comment by zombifier** [comment]
I'm pretty confident that the reason is the same as #20682 (Firefox 65 failing to load localhost subdomain).

**Comment by torch2424** [comment]
@rsimha after seeing @zombifier 's response, I agree that this is the root cause.

I'll go ahead and leave this issue open, until we solve the issue with Firefox in general. 

Thank you everyone!

**Comment by torch2424** [comment]
Found out this is also an issue for Edge: #21812

Thanks for catching this @rsimha 😄
