### ISSUE TITLE
Conformance Config: Enable BanUnknownTypedClassPropsReferences

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#21254]
It's getting harder and harder to enable new conformance config bans, mostly due to our **very** poor type information. Eg, trying to enable https://github.com/ampproject/amphtml/issues/21234 causes 50 warnings:

```
...
src/utils/xhr-utils.js:160: WARNING - Possible violation: NodeList.p.forEach is not available in IE. Please use iterateCursor in src/dom.js
The type information available for this expression is too loose to ensure conformance.
      init.headers.forEach(entry => {
```

Now, I know `headers` isn't a `NodeList` (and, arguably, Closure should figure that out form the `Array.isArray`), but because of our poor type information on `init`, it has no idea what this value is.

There's an internal doc about this: go/unknownprops

**Comment by rsimha** [comment]
Just tried adding this conformance config rule to `build-system/test-configs/conformance-config.textproto` and ended up with [~1500 errors](https://gist.github.com/rsimha/85c3c819858dd54ff6453a547203fd51).

```js
requirement: {
  rule_id: 'closure:unknownTypedClassPropsReferences'
  type: CUSTOM
  java_class: 'com.google.javascript.jscomp.ConformanceRules$BanUnknownTypedClassPropsReferences'
  error_message: 'Should not reference class properties with unknown types.'
}
```

Am I right in understanding that the AMP code needs a substantial number of changes before this rule can be put in place? (Is there anything in recent versions of closure that provides a workaround?)

In any case, it's unlikely that Infra will be able to work on this in the foreseeable future. Reassigning to @ampproject/wg-runtime for further triage.

**Comment by samouri** [comment]
Worth closing due to us removing Closure Compiler.
