### ISSUE TITLE
AMP.goBack doesn't work.

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#21260]
To Whom it may concern:

I tried to add goBack action on &lt;a&gt;, but looks like it didn't work.

```
<a on="tap:AMP.goBack"">
    Go back
</a>
```

[Actions and events in AMP](https://github.com/ampproject/amphtml/blob/master/spec/amp-actions-and-events.md#target-amp)

I wonder is this an issue or something wrong with my usage.

Paul

**Comment by choumx** [comment]
Might be relevant: https://github.com/ampproject/amphtml/issues/5225#issuecomment-278453344

`AMP.goBack` only pops the local AMP history stack (e.g. closes lightbox or `AMP.pushState`), but it won't navigate the window. What's your intended usage?

**Comment by meistudioli** [comment]
Hi, @choumx 

I thought it could do **window.history.go(-1)** stuff. I like to implement "Back to previous page" function for PWA. Is there any suggestion or amp-component could do that ? Such as amp-script ?

Paul

**Comment by choumx** [comment]
Yea, we'll need #5225 for that. Closing as a duplicate. Please comment on/follow that issue for updates.
