### ISSUE TITLE
🌸 Cherry pick request for #21098 into 1902261915030 (Pending)

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#21273]
## GitHub issue your cherry pick is fixing:

Issue #21098

## PR that you are requesting a cherry pick for:

PR #21232

## Release(s) you requesting this cherry pick into:

 

Canary release? YES

 Release Issue #21169

## Why does this issue meet the [cherry pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

It is both Edge and IE11 and form submission is big for ALP.

/cc @cramforce
/cc @choumx @aghassemi

**Comment by aghassemi** [comment]
Some data from a particular customer: They have >100 canonical AMP sites in Europe with about 5% using IE/Edge.

**Comment by erwinmombay** [comment]
SGTM after approval

**Comment by cramforce** [comment]
Approved. I left a comment on the PR https://github.com/ampproject/amphtml/pull/21232#issuecomment-469835739
