### ISSUE TITLE
Change bundlesize reporter to use brotli size

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#21275]
The gzip file size is largely irrelevant now, and certain optimizations we make that reduce the size of the gzip output can actually increase the size of the brotli output.

**Comment by rsimha** [comment]
Switching the calculation should be fairly straightforward.

https://github.com/ampproject/amphtml/blob/8833970aa194c4c557accd149e684565ac4ba469/build-system/tasks/bundle-size.js#L46-L63

However, there will be a period when PRs will have base commits for which we only have the gzipped bundle size. I suppose we can ease into this by initially computing both sizes, and then switching exclusively from gzip to brotli at some point.

Assigning to @danielrozenberg.

**Comment by danielrozenberg** [comment]
My work plan on changing this is as follows:
1. Modify the reporter for **push builds** to double-write the bundle size on each commit to `bundle-size/[SHA]` (gzip) and `bundle-size/[SHA].br` (brotli), do this for 1 month
2. 1. Modify the reporter for **pull requests** to report both gzip and brotli bundle-sizes to the app
    2. Modify the bundle-size app to read the `[SHA].br` instead of the `[SHA]` file
3. 1. Stop reporting the gzip size for pull-requests and push-builds
    2. Delete all gzip sizes in `amphtml-build-artifacts`

**Comment by rsimha** [comment]
Reverted in #24882

**Comment by danielrozenberg** [comment]
Unreverted in #24888
