### ISSUE TITLE
Allow `amp-bind-macro` to be used in the `on` attribute

### ISSUE THREAD

**Issue by YonahKarp** [ampproject/amphtml#21286]
## Describe the new feature or change to an existing feature you'd like to see

The [`<amp-bind-macro>` tag](https://www.ampproject.org/docs/reference/components/amp-bind#defining-macros-with-amp-bind-macro) is a useful element that allows you to define an expression (with optional use of parameters) and invoke it anywhere in the document. 

 I would like use of these expressions to be allowed inside the `on` attribute.

## Additional context

I find that often you want to use the same or similar actions for multiple elements on a page. There's currently no good way built in to AMP to define an action (or action group) for reuse.

I do understand that the nature of what is found in a bound value differs from what you would expect in `on`. Maybe a `type` attribute could be used on `amp-bind-macro` with expected values being `"bind"` and `"on"`. Or perhaps a new element might be a better solution

**Comment by choumx** [comment]
Does [amp-action-macro](https://github.com/ampproject/amphtml/blob/master/extensions/amp-action-macro/amp-action-macro.md) help?

**Comment by YonahKarp** [comment]
Yes, thank you! That's exactly what I'm looking for. Guess now it's a waiting game now until it's available for production use

**Comment by choumx** [comment]
Great! Timely request.
