### ISSUE TITLE
amp-base-carousel cannot bind to visible-count

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#21296]
I encountered this bug when running some of the end to end tests. It was causing the "should respond to attribute changes" to fail. I'm going to open a PR to skip this test

> http://localhost:8000/test/manual/amp-base-carousel/responsive.amp.html
> amp-base-carousel#carousel-1.i-amphtml-element.i-amphtml-layout-responsive.i-amphtml-layout-size-defined.i-amphtml-layout.i-amphtml-error: Binding to [%s] on <%s> is not allowed. amp-bind visible-count AMP-BASE-CAROUSEL​​​

/to @sparhami for triage and eventual fix.

**Comment by sparhami** [comment]
Fixed by #21300
