### ISSUE TITLE
🌸 Cherry pick request for #21287 into 1902261915030 (Pending)

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#21290]
## GitHub issue your cherry pick is fixing:

Issue #21287 

## PR that you are requesting a cherry pick for:

PR #21289

## Release(s) you requesting this cherry pick into:

1902261915030

Production Release? NO

Canary release? YES

Release Issue #21169

## Why does this issue meet the [cherry pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

Video playback in stories breaks in the stable version of Chrome.  This breaks existing published AMP pages.

/cc @cramforce

**Comment by cramforce** [comment]
Borderline, but approved.

**Comment by newmuis** [comment]
@cramforce would you be okay with patching prod for this?  It missed the canary promote.

**Comment by cramforce** [comment]
No

**Comment by cramforce** [comment]
Well, it depends on how bad it is. Patch to canary first, and if there are no issues there, we can reconsider based on priorities.
