### ISSUE TITLE
Intent To Implement: TripleLift ad network for amp-ads

### ISSUE THREAD

**Issue by szach** [ampproject/amphtml#2129]
# Overview

Support for the [TripleLift](http://triplelift.com) ad-network will be added to `<amp-ad>` elements.

### Comments

TripleLift will be submitting a PR via the `triplelift/amphtml` fork from the `feature/triplelift` branch.

**Comment by cramforce** [comment]
LGTM. Ship it!

**Comment by jasti** [comment]
Closing since https://github.com/ampproject/amphtml/pull/2320 has been merged.
