### ISSUE TITLE
fix components layout whose direct child and itself allows for padding and border to be set

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#213]
we'll have evaluate this per component if we should allow it for the parent or the child or neither.

- amp-ad (padding)
- amp-img (padding and border)
- amp-video (padding and border)
- amp-anim (padding and border)
- amp-audio (padding and border)
- amp-carousel (padding and border, container and container child)
- amp-iframe (padding and border)
- amp-instagram (padding and border)
- amp-lightbox (padding and border)
- amp-slides (padding and border)
- amp-twitter (padding)
- amp-youtube (padding and border)

https://docs.google.com/a/google.com/document/d/1MuZWgq6N3rPMSFfhjC6Y3v6Fm9eRgbIBZ07ST-_qRS4/edit?usp=sharing

related issue for margin: https://github.com/ampproject/amphtml/issues/212

**Comment by rudygalfi** [comment]
Sweeping old bugs: Is this still needed?

**Comment by ericlindley-g** [comment]
@erwinmombay Ping?

**Comment by erwinmombay** [comment]
unlikely, but will have to reconfirm with @dvoytenko to make sure.

**Comment by dvoytenko** [comment]
I think we are all good here. We protected against the most obvious mistakes with inherited properties. With all others - the authors have to be careful with modifying paddings and borders and that's allowed.
