### ISSUE TITLE
AMP Inabox BTF tests fails on Safari if ran on Saucelabs with the full test suite

### ISSUE THREAD

**Issue by zombifier** [ampproject/amphtml#21311]
The tests added by #20972, which should have fixed it.

Example run: https://travis-ci.org/ampproject/amphtml/jobs/503126033

Local Safari test passing:
![image](https://user-images.githubusercontent.com/12178173/53967706-b7ebe000-40c3-11e9-8925-d6abdf32accc.png)

**Comment by zombifier** [comment]
Additional context: When run by themselves on Travis they pass:
![image](https://user-images.githubusercontent.com/12178173/56756626-2bbf7600-6760-11e9-8fa3-039893582a2f.png)

**Comment by rsimha** [comment]
@zombifier
- This test occasionally times out on Chrome too: https://travis-ci.org/ampproject/amphtml/jobs/524635005#L1527
- And for single-pass builds: https://travis-ci.org/ampproject/amphtml/jobs/524681807#L1908-L1912

**Comment by lannka** [comment]
@zombifier we recently fixed a couple of issues (#23519 #23512 #23543) that might have caused those flakiness. I also added some extra request-bank error message to ease the debugging.

That said there is a good chance that those tests are easier to deal with now. There are 4 remaining tests need to be unskipped. Would you take another look?

**Comment by zombifier** [comment]
Made #23605 to try reenabling the test and see what happens, but they weirdly enough still fail on Travis. Local testing with Firefox and Chrome works fine.
