### ISSUE TITLE
Avoid flickering in amp-call-tracking

### ISSUE THREAD

**Issue by fer-sd** [ampproject/amphtml#21327]
Hi there,

I'm making some basic tests with the amp-call-tracking component. After enabling a simple CORS endpoint which returns a JSON object as described in the documentation (https://www.ampproject.org/docs/reference/components/amp-call-tracking). This endpoint has some latency (about 450 ms, may be due to CORS filter) which ends up in a flickering issue when the component is replacing the default phone number with the one returned by de endpoint. It does not seem to be the best UX as that default number in the <a> tag is required (not working if empty text). 
Is there any way to improve the experience when having latency in the endpoint? (i.e. avoid default phone number, latency reduction, etc.)
Any suggestion will be appreciated.

Thanks in advance.

**Comment by fer-sd** [comment]
Any help?

**Comment by aghassemi** [comment]
@fer-sd best way is to ensure the overall format and `width` of the digits don't change between the default and final numbers.

1- Make sure the default umber provided is the exact same format as the final value
2- Use CSS properties such as `font-feature-settings: "tnum"; font-variant-numeric: tabular-nums;` to ensure with with of the digits are the same between default and final numbers so overall width does not change.

Hope this helps.

**Comment by aghassemi** [comment]
Closing per suggestion above
