### ISSUE TITLE
amp-fx fly-in-bottom and fly-in-top broken 

### ISSUE THREAD

**Issue by Axos11** [ampproject/amphtml#21332]
## What's the issue?

amp-fx="fly-in-bottom" and amp-fx="fly-in-top" have stopped working correctly. 
even on the ampbyexample page the error is visible. 
https://ampbyexample.com/components/amp-fx-collection/

## How do we reproduce the issue?

https://ampbyexample.com/components/amp-fx-collection/

https://ampbyexample.com/components/amp-fx-collection/#fly-in-bottom

## What browsers are affected?

Chrome Version 72.0.3626.119 (Official Build) (64-Bit)
Firefox 65.0.2 (64-Bit)
Microsoft EdgeHTML 17.17134

## Which AMP version is affected?

Is this a new issue? Or was it always broken? Paste your AMP version. You can find it in the browser dev tools.

amp-version="1903070012530"

## Example Screenshot:

![image](https://user-images.githubusercontent.com/22347776/54035370-85bcaa00-41b9-11e9-9fa3-23d2738b45e5.png)

**Comment by aghassemi** [comment]
@alanorozco could you please take a look?

**Comment by alanorozco** [comment]
Mea culpa. Legit regression from a bad refactor. Easy fix, should be out soon.
