### ISSUE TITLE
Lightbox is not rendered properly if served from Google on Safari

### ISSUE THREAD

**Issue by selfcatering** [ampproject/amphtml#21331]
## What's the issue?

We're experiencing an issue with lightbox display if page is served from Google cache. iOS Safari is the only affected.

## How do we reproduce the issue?

1. On your mobile device Google "site:fivestar.ie Walshes Lough" and pick the first one, you should land on https://www.google.ie/amp/s/fivestar.ie/amp/self-catering/walshes-lough-1/ 
2. Close privacy consent
3. At the bottom of the page you'll find E-mail icon - click it
4. Lightbox is not rendered properly.
5. Do above on AMP page served from our server https://fivestar.ie/amp/self-catering/walshes-lough-1/ to see it renders ok.

## What browsers are affected?

iOS 11, 12 Safari

## Which AMP version is affected?

Version 1903070012530

**Comment by aghassemi** [comment]
@selfcatering `amp-lightbox` inside a `fixed` element has some known issues (https://github.com/ampproject/amphtml/issues/9576). As a work-around, please move the `amp-lightbox` to be outside of `<div class="contact-options"` that you have as position fixed.

**Comment by aghassemi** [comment]
Closing as dup of #9576
