### ISSUE TITLE
Remove amp-youtube from AMPHTML Ads spec

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#21340]
The current `amp-youtube` implementation relies on a cross-origin iframe which brings uncertainty to the performance of the ad. In general, AMPHTML ads tries to avoid any use of cross-origin iframe. Here we propose to deprecate the use of `amp-youtube` in AMPHTML ads. To follow the [deprecation policy](https://github.com/ampproject/amphtml/blob/master/spec/amp-versioning-policy.md), here is the list of checkboxes:

- [x] Allow for at least 2 weeks of open discussion.
- [x] Wait for 3 approvals from core committers.
- [x] Update spec
- [x] Announce change on the mailing list.
- [x] Start warning for ads that might break via the developer console.
- [x] Give developers 6 weeks to apply changes. (8/23/2019)
- [x] Update validator
- [x] Remove the warning

/cc @keithwrightbos @aghassemi @jasti @honeybadgerdontcare

**Comment by honeybadgerdontcare** [comment]
Is this the i2i to satisfy the [deprecation policy](https://github.com/ampproject/amphtml/blob/master/spec/amp-versioning-policy.md)?

**Comment by lannka** [comment]
@honeybadgerdontcare good point. Updated the issue to follow the process.

**Comment by lannka** [comment]
@ampproject/wg-ads @ampproject/a4a @ampproject/ads

**Comment by yazdotdev** [comment]
@lannka @honeybadgerdontcare by the way, the placeholder image for amp youtube is jpg and not webp.  any chance of changing this? it might be more a youtube team rather than amp team issue though.

**Comment by lannka** [comment]
@yazdotdev thanks for bringing it up. I created a separate issue to discuss this #21357

**Comment by honeybadgerdontcare** [comment]
@lannka 	I approve this of this change

**Comment by lannka** [comment]
thanks @honeybadgerdontcare 
collecting more stamps: @keithwrightbos @aghassemi @jasti @zhouyx

**Comment by jasti** [comment]
Approved!

**Comment by jeffkaufman** [comment]
strongly in favor

**Comment by calebcordry** [comment]
@lannka Are we ready to announce this change on the mailing list?

**Comment by lannka** [comment]
Announced here: https://groups.google.com/forum/m/#!topic/amphtml-announce/_CU2TF1bpfM
