### ISSUE TITLE
Fix amp-story render-delaying usage

### ISSUE THREAD

**Issue by torch2424** [ampproject/amphtml#21349]
relates to #21193

This is a follow up to the PR above. amp-story was render blocking on extension (not supported), instead of by service.

Currently in South Africa for a Roadshow, thus can't work on this. @newmuis if this is high(er) priority for you, don't wait for me 😄

**Comment by newmuis** [comment]
Sounds good!  Thanks for identifying this and getting the root fix in; we can probably take it from here.

**Comment by torch2424** [comment]
Just a heads up PR open here: https://github.com/ampproject/amphtml/pull/21382
