### ISSUE TITLE
I2I: <Please minify all javascript files and add expiration time for v0.js>

### ISSUE THREAD

**Issue by Narendharr** [ampproject/amphtml#21345]
![image](https://user-images.githubusercontent.com/9212952/54072503-89c3f700-42a1-11e9-8f1c-64433f536873.png)

I have tested the AMP pages on Google Page Speed insights and GTMetrix websites. If you check the above image all the they suggest to minify all the scripts that are shown in the above image.

![image](https://user-images.githubusercontent.com/9212952/54072522-d0195600-42a1-11e9-9fd7-1c7f0f86ad51.png)
Another issues is Leverage browser caching for https://cdn.ampproject.org/v0.js . Please enable caching for https://cdn.ampproject.org/v0.js

All these issues can be easily fixed. Please consider the above issues as it plays major role to improve the page speed.

Best Regards,
Narendharr

**Comment by jridgewell** [comment]
Hi @Narendharr 

Our JavaScript is already compressed. We use brotli compression if your browser is new enough, or gzip encoding if your browser is older. The only time the JavaScript is not compressed is when your browser doesn't negotiate for a compression during the request (in the `Accept-Encoding` request header.

```bash
$ curl -sI https://cdn.ampproject.org/v0.js -H 'Accept-Encoding: br' | grep content-encoding
content-encoding: br
$ curl -sI https://cdn.ampproject.org/v0.js -H 'Accept-Encoding: gzip' | grep content-encoding
content-encoding: gzip
$ curl -sI https://cdn.ampproject.org/v0.js | grep content-encoding
No match
```

Additionally, we set a 50min expiration time using `cache-control: private, max-age=3000`.

**Comment by yazdotdev** [comment]
@jridgewell thanks for that clarification ... created this [repo](https://github.com/yazdotdev/miniamp) which may be unnecessary.  
@Narendharr try using the script line with the line I put [there](https://github.com/yazdotdev/miniamp/blob/master/README.md) and it should be optimized for gtmetrix 
@jridgewell any chance of extending the browser cache ttl to 7 days like all the other scripts?
