### ISSUE TITLE
amp-fx-collection position bug

### ISSUE THREAD

**Issue by caiotarifa** [ampproject/amphtml#21353]
## What's the issue?

Some effects (provided by the amp-fx-collection) began to have serious positioning problems.

https://ampbyexample.com/components/amp-fx-collection/

## How do we reproduce the issue?

1. Open the [amp-fx-collection page on AMP by Example website](https://ampbyexample.com/components/amp-fx-collection/).
2. Navigate to "Delayed fly-in animation" or "Fly-in with wifferent bezier curves" section.
3. See the bug.

## What browsers are affected?

Tested on Chrome, Safari and Firefox.

## Which AMP version is affected?

I don't know, but I visit my website every days (which makes use of this feature) and I see the problem on Friday (2019-03-08).

**Comment by aghassemi** [comment]
Hi @caiotarifa, thanks for filling the issue. We have a fix ready for it https://github.com/ampproject/amphtml/pull/21336. Sorry for the breakage.

**Comment by aghassemi** [comment]
closing as dup of #21332

**Comment by caiotarifa** [comment]
Thanks, @aghassemi.

Sorry, but how does it work? Is there a date for the solution to take effect?

**Comment by aghassemi** [comment]
@caiotarifa We are working on patching dev channel with the fix https://github.com/ampproject/amphtml/issues/21359 depending on other release-related issues it will either be mid this week and early next week.

**Comment by caiotarifa** [comment]
Thanks!

**Comment by aghassemi** [comment]
This is fixed and live in production now.

**Comment by caiotarifa** [comment]
Thx, @aghassemi.
