### ISSUE TITLE
"&amp" is not rendering as "&" symbol

### ISSUE THREAD

**Issue by michaelwmcnamara** [ampproject/amphtml#2135]
original issue: 
https://github.com/guardian/frontend/issues/12040

&Amp is being displayed literally, instead of being interpreted as "&" 

![image](https://cloud.githubusercontent.com/assets/7239344/13182793/642c4842-d72b-11e5-9f4b-d8ed280d5356.png)

If this is intentional, we can filter these from our end. Please let us know.

**Comment by cramforce** [comment]
@dvoytenko I think this is working as intended. Strings are meant to be just strings. HTML encoding happens at template rendering time.

**Comment by dvoytenko** [comment]
@cramforce @michaelwmcnamara Correct. Strings in JSON are meant to be strings. These strings are escaped when output into HTML. There's a limited option to use `{{{value}}}` (triple-mustache) that can be used to disable escaping as well.

**Comment by jridgewell** [comment]
Yup, what you're seeing is actually it rendering `&amp;amp;` (the ampersand you're seeing is actually the HTML entity).

**Comment by michaelwmcnamara** [comment]
Thanks for your help everyone! :-)
