### ISSUE TITLE
🌸 Cherry pick request for (21336, 21343)  into 21329

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#21359]
## GitHub issue your cherry pick is fixing:

- Issue #21332
- Issue (untracked, viewer header animation flashing)

## PR that you are requesting a cherry pick for:

PR #21336 
PR #21343

## Release(s) you requesting this cherry pick into:

1903080058260

Production Release? NO

Canary release? YES

Release Issue #21329

## Why does this issue meet the [cherry pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

Two critical presentation bugs that are very visible should be patched before getting to production eg:

#### Issue #21332

![image](https://user-images.githubusercontent.com/254946/54153008-c6a40100-43fb-11e9-8898-fd7f59ac141a.png)

#### Issue (untracked, viewer header animation flashing)

![](https://user-images.githubusercontent.com/254946/54064916-52d0e100-41ce-11e9-853f-9cd7253a0b50.gif)

/cc @cramforce @jridgewell

**Comment by cramforce** [comment]
Approved

**Comment by jridgewell** [comment]
This is rendered moot by #21386.
