### ISSUE TITLE
Validator doesn't accept valid svg

### ISSUE THREAD

**Issue by nbeloglazov** [ampproject/amphtml#2136]
Hi

Current validator doesn't accept svg with "version" attribute and <stop> tag:
```svg
<svg width="120" height="120"  viewBox="0 0 120 120"
     xmlns="http://www.w3.org/2000/svg" version="1.1"
     xmlns:xlink="http://www.w3.org/1999/xlink" >

    <defs>
        <linearGradient id="MyGradient">
            <stop offset="5%"  stop-color="green"/>
            <stop offset="95%" stop-color="gold"/>
        </linearGradient>
    </defs>

    <rect fill="url(#MyGradient)"
          x="10" y="10" width="100" height="100"/>
</svg>
```
From here: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/linearGradient

Validation errors: http://output.jsbin.com/bagukobaco#development=1 I believe this svg is valid and safe from security/performance point of view (though I'm not svg expert).

**Comment by cramforce** [comment]
CC @Gregable @powdercloud @honeybadgerdontcare

**Comment by Gregable** [comment]
This is fixed. Should be rolled out to javascript in an hour or so.
