### ISSUE TITLE
Misalignment on amp-fx fly-in-bottom

### ISSUE THREAD

**Issue by unumbox** [ampproject/amphtml#21363]
## What's the issue?

Any elements using amp-fx="fly-in-bottom" are misaligned lower and to the right. 

This is the same on multiple websites.

## How do we reproduce the issue?

Visit > https://hatch.london/clients/

On a desktop, you will see the middle column logos are dropped and off center.

## What browsers are affected?

Chrome, Firefox, IE and Safari

## Which AMP version is affected?

This was first noticed today but was working on a few days ago so likely to have happened between 8th -11th

**Comment by caiotarifa** [comment]
Related #21353.

**Comment by aghassemi** [comment]
Hi @unumbox we have a fix (#21359) depending on other release-related issues fix will ship either mid this week and early next week. Apologies for the breakage.

**Comment by aghassemi** [comment]
Closing s dup of #21353.
