### ISSUE TITLE
amp-lightbox-gallery - the first image of the gallery doesn't appear in image viewer in some cases

### ISSUE THREAD

**Issue by panakk** [ampproject/amphtml#21374]
When the gallery consists of more than 3 images there is an issue of displaying the first image lightboxed both when opening from the site and when carouseling to it in the image viewer. It happens only when other than this 1st or its neigbor image (2nd or the last one) is opened (clicked) as the first in the gallery.

It happens even in the AMP playground example case when adding more images there (in all common browsers).

Example:
https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-lightbox-gallery%2Fsource%2F
→
https://www.janmateju.cz/tmp/amp/amp-lightbox-gallery__issue.html

**Comment by aghassemi** [comment]
Thanks @panakk. 

I can reproduce this in https://www.janmateju.cz/tmp/amp/amp-lightbox-gallery__issue.html, Chrome 72 -> Mobile Mode -> Click on third image, navigate carousel back twice -> Image does not show up.
/to @alanorozco to take a look. I think we should fix this before launching auto-lightbox for carousels.

**Comment by sparhami** [comment]
Looks doing #21568 would fix this.

**Comment by nainar** [comment]
This should work with carousel v0.2 now.
