### ISSUE TITLE
Need a configurable Background

### ISSUE THREAD

**Issue by ghelapratik** [ampproject/amphtml#21380]
With the new UI implemented, I understand that the blur background images which used to be present are now gone. However, this has really created a new contrast issue and cannot use dark colored images or background color. If we can have a way to configure the background color using a meta tag or a data attribute, it should be a quick fix.

**Comment by hongwei1990** [comment]
The background color value on default desktop is #202125 which is more like a dark, dark gray. It is not pure black so black content from the page should be assessable. Open to configure the background color creates a new problem. For instance, the accessibility of the system layer (progress bar, share icon, etc.) will face risk when the background color is too bright or too light.

**Comment by newmuis** [comment]
This issue is pretty old at this point, but for posterity, you should now be able to achieve this on your site by using the [`amp-story-player`](https://amp.dev/documentation/guides-and-tutorials/integrate/embed-stories/).
