### ISSUE TITLE
🌸 Cherry pick request into #21329 (Approved)

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#21386]
## GitHub issue your cherry pick is fixing:

No issue

## PR that you are requesting a cherry pick for:

PR #21385
PR #21383

## Release(s) you requesting this cherry pick into:

Production Release? NO

Canary release? YES

Release Issue #21329

## Why does this issue meet the [cherry pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

We're seeing a large regression in ads metrics. It could be either of the two mentioned PRs that caused this, so I'm attempting to revert both before we promote the canary to production.

/cc @cramforce

**Comment by cramforce** [comment]
Approved

**Comment by aghassemi** [comment]
https://github.com/ampproject/amphtml/pull/21336 is still valid for cherry pick

**Comment by jridgewell** [comment]
Ok, I'll make sure to get that one, too.

**Comment by jridgewell** [comment]
Releasing with 1903122236150
