### ISSUE TITLE
Collapsing amp-iframes from inside

### ISSUE THREAD

**Issue by neoplomero** [ampproject/amphtml#21397]
## Describe the new feature or change to an existing feature you'd like to see

If you use an amp-iframe would be nice to execute some function to collapse the amp-iframe so is not visible anymore. This would allow to remove it once we've done or shown what was expected.

## Describe alternatives you've considered

Something like:

window.parent.postMessage({
  sentinel: 'amp',
  type: 'collapse'
}, '*');

## Additional context

There are many functionalities that create a blank space after been used. Polls, forms, etc. Many time you need the amp-iframe for a few time then you'd love to remove it.

**Comment by aghassemi** [comment]
@neoplomero Thanks for the FR. This is something we have deliberately disabled in the past (please see https://github.com/ampproject/amphtml/issues/3746) but your use-case it legit.

Some investigation is needed to evaluate the (potential abuse/legit cases) ratio and decide to relax based on that evaluation.

/cc @nainar

**Comment by neoplomero** [comment]
@aghassemi about #3746, why though? Sad :(

**Comment by aghassemi** [comment]
@neoplomero To prevent iframe-based tracking/analytics because they are very in-efficient compared to `amp-analytics`.

@cramforce Given the maturity of the project at this point, can we consider the abuse vector small enough to relax this now? (e.g. allow iframes to collapse). I think given amp-analytics is featureful and the best practices around amp-analytics and amp-pixel has been very much stablished, my vote would be to relax this.

**Comment by neoplomero** [comment]
Mine too @cramforce. 😅

**Comment by aghassemi** [comment]
@sparhami mentioned we should `unlayout` the iframe as well

**Comment by cathyxz** [comment]
Based on our `collapse` constraints, I think the `collapse` functionality that we are able to implement will have the same restrictions as the current iframe resizing feature, which I think you can use as a workaround: 

https://amp.dev/documentation/examples/components/amp-iframe/#resizable-iframe

One important feature of amp-iframe is the ability to resize the iframe at runtime. For this to work:

- The amp-iframe must set the allow-same-origin sandbox attribute.
- The amp-iframe must be defined with the resizable attribute.
- The amp-iframe must have an overflow child element.
- The iframe document must send an embed-size request:
```
window.parent.postMessage({
  sentinel: 'amp',
  type: 'embed-size',
  height: document.body.scrollHeight
}, '*');
```
You should be able to "collapse" the iframe by setting `height` to zero.

**Comment by sparhami** [comment]
I believe you cannot collapse an iframe by setting the size to zero, we currently have a check that prevents you from doing so and deny the resize. We do this in part to prevent so called "tracking" iframes from living on.

So we will want to have a separate API, and remove the iframe when collapsed.
