### ISSUE TITLE
`amp-bind` not working in `<a [href] ...>`

### ISSUE THREAD

**Issue by rwehresmann** [ampproject/amphtml#21396]
## What's the issue?

`amp-bind` not working in `<a [href] ...>`

## How do we reproduce the issue?

The bug can be reproduced through this link: https://cambiostore-staging-pr-323.herokuapp.com/

![Screenshot from 2019-03-12 16-13-42](https://user-images.githubusercontent.com/10273918/54276168-69c75880-456b-11e9-90b8-625ca8f72846.png)

The explanation is based in the printscreen above. The initial href of the anchor tag `Comparar casas de câmbio` is `/dolar/sp/sao-paulo`. The expected behavior is:

1) Changing "São Paulo (SP)" to another option, "Rio de Janeiro (RJ)" for instance, must change the href of the anchor tag to  `/dolar/rj/rio-de-janeiro`;

2) Changing "Dólar" to another option, "Euro" for instance, must change the href of the anchor tag to  `/euro/rj/rio-de-janeiro`.

However, doing the changes described in step 1 and 2 doesn't update the href. I already checked the follow: `currency`, `city` and `state` (states) are changed correctly, only the `href` isn't updated.

## What browsers are affected?

Chrome and Safari in IOS.

## Which AMP version is affected?

I think always was broken.

**Comment by aghassemi** [comment]
Hi @rwehresmann , I am not able to hit https://github.com/ampproject/amphtml/issues/21403 , could you please provide a working link or snippet of the relevant code?

**Comment by rwehresmann** [comment]
Hello @aghassemi ! Sorry, not sure if I understand: a working example of infinite scroll bug? I didn't experimented this problem in my situation, my case is just the amp-bind not working in IOS platform.

**Comment by aghassemi** [comment]
@rwehresmann not infinite list, for the amp-bind issue. I can not access https://cambiostore-staging-pr-323.herokuapp.com/ to see the problem.

**Comment by rwehresmann** [comment]
Ok. This link is hosted in a free web dyno of Heroku who sleeps when doesn't receive web traffic (and currently isn't receiving). You will experiment delay (about 1 minute) until Heroku "wake up" the dyno while you trying access it. But it's working, I double checked here. Please, could you try again?

**Comment by aghassemi** [comment]
@rwehresmann I can repro.

/to @choumx My minimal case using `select` and `amp-bind` works fine in iOS ( https://s.codepen.io/aghassemi/debug/QoBybq  ) but https://cambiostore-staging-pr-323.herokuapp.com/ definitely doesn't. The expression is a bit more complex there, so maybe it has something to do with that.

**Comment by choumx** [comment]
I see the following console error on Safari which looks like amp-bind's worker failing to load:

> Refused to load blob:https://cambiostore-staging-pr-323.herokuapp.com/e1537c59-fe99-450d-830f-66a82fa9d4fe because it appears in neither the child-src directive nor the default-src directive of the Content Security Policy.

Need to update CSP per instructions here: https://amp.dev/documentation/components/amp-bind/?referrer=ampproject.org#errors

Curious why Chrome and Safari apply CSP differently though.
