### ISSUE TITLE
Custom parameters are not working in AMP-YouTube component

### ISSUE THREAD

**Issue by MohammedKaludi** [ampproject/amphtml#21394]
## What's the issue?

data-param-rel is not working in amp-youtube component, if we pass rel=0 parameter the related videos should not load after the current video ends.

As you can check in below screencast no matter what I pass in data-param-rel attribute, related vidoes are always showing at the end of the video.

## How do we reproduce the issue?
You can check this screencast, I have tested locally and on a server as well. Same thing happening. 

This is done on AMPbyExample playground.
https://monosnap.com/file/yej1si8HTfVqWFfLQ1vjWEbk8sZjtW

## Which AMP version is affected?

This is happening with the last few versions, I think it used to work properly before.

**Comment by aghassemi** [comment]
@MohammedKaludi Looking at https://developers.google.com/youtube/player_parameters#release_notes_08_23_2018 looks like YT has changed how `rel` behaves.

**Comment by aghassemi** [comment]
Closing per comment above, please reopen if that does not answer your question.
