### ISSUE TITLE
I2I: Deprecate attribute cross-origin in favor of crossorigin for remote XHR identity requests.

### ISSUE THREAD

**Issue by hellokoji** [ampproject/amphtml#21399]
In accordance with [the deprecation policy](https://github.com/ampproject/amphtml/blob/master/spec/amp-versioning-policy.md#deprecations).

With reference to I2I Issue (#18787) and Pull Request (#21107), the attribute `cross-origin` and `crossorigin` will both be supported to enable POST based identity on remote XHR requests. This deprecation will remove `cross-origin` as a valid attribute in favor of `crossorigin` to align with the [standard CORS attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes).

* [x]  Allow for at least 2 weeks of open discussion.
* [x]  Wait for 3 approvals from core committers.
* [x]  Update spec
* [x]  Announce change on the mailing list.
* [x]  Start warning for pages that might break via the developer console.
* [x]  Give developers 6 weeks to apply changes.
* [x]  Update validator

**Comment by torch2424** [comment]
closing this as this was implemented 😄 

Feel free to comment if this needs more work.

**Comment by honeybadgerdontcare** [comment]
@hellokoji Confirming that all the above steps have been completed before approving #21909. It's just been about six weeks for developers to apply, but I don't see any approvals from core committers here and was there an announcement on the mailing list?

**Comment by honeybadgerdontcare** [comment]
@ampproject/wg-approvers for 3 approvals from core committers.

**Comment by honeybadgerdontcare** [comment]
@hellokoji please announce to  amphtml-announce@googlegroups.com

**Comment by dvoytenko** [comment]
LGTM from me, but I agree with @honeybadgerdontcare. Let's assign the I2I to @ampproject/wg-approvers from now on.

**Comment by dvoytenko** [comment]
/to @choumx and @Gregable to provide additional approvals.

**Comment by hellokoji** [comment]
Apologies, I must have missed this. You're right, this never got announced on the mailing list and never had core committer approval.

I'll send out the announcement on the amphtml-announce@googlegroups.com mailing list.

**Comment by hellokoji** [comment]
[Sent](https://groups.google.com/forum/#!topic/amphtml-announce/i4SAcd6T6v8).

**Comment by Gregable** [comment]
I don't think this change has much to do with wg-caching, other than the fact that it is a (small) literal change to validator rules. Perhaps @cramforce instead for the additional approval.

**Comment by choumx** [comment]
LGTM

**Comment by honeybadgerdontcare** [comment]
@Gregable this isn't about wg-caching but instead about getting 3 approvals from wg-approvers which you are a member of. So far Dima and Will approved. You could be the third to move this along.

**Comment by hellokoji** [comment]
Friendly ping to this thread. Still need 1 more approval from a core-committer.

**Comment by cramforce** [comment]
Approved

**Comment by hellokoji** [comment]
Marking closed with #21909 being merged.
