### ISSUE TITLE
amp-carousel only display one line text

### ISSUE THREAD

**Issue by gaoljie** [ampproject/amphtml#21393]
When I am using amp-carousel under 'carousel' type, no matter I use <p> tag or <amp-fit-text> tag,  there is no way to display more than one line of text. The reason I want to use 'carousel' type is that sometimes I want the width of each slide less than window width.

this is the example:
https://codepen.io/gaoljie/pen/WmXPRE?editors=1000

**Comment by sparhami** [comment]
I'm not sure why that is the default behavior, but you can add the following CSS to make the text wrap:

```css
.amp-carousel-slide {
  white-space: normal;
}
```

**Comment by gaoljie** [comment]
> I'm not sure why that is the default behavior, but you can add the following CSS to make the text wrap:
> 
> ```css
> .amp-carousel-slide {
>   white-space: normal;
> }
> ```

Thanks a lot! it solves the problem. You may consider wrapping the text in slide as a css default setting.

**Comment by sparhami** [comment]
> > I'm not sure why that is the default behavior, but you can add the following CSS to make the text wrap:
> > ```css
> > .amp-carousel-slide {
> >   white-space: normal;
> > }
> > ```
> 
> Thanks a lot! it solves the problem. You may consider wrapping the text in slide as a css default setting.

I'm not sure the context for why this is, but there is some CSS that makes it single-line only. If it is intentional, it may not be safe to change the default at this point since some people may be depending on the behavior. Perhaps we should update the documentation to note this behavior and how to wrap text if desired.

**Comment by aghassemi** [comment]
let's keep this in mind for Carousel V2.

Closing for now.
