### ISSUE TITLE
AMP-bind doesnot allow selectbox to open in firefox mobile

### ISSUE THREAD

**Issue by rehansh16** [ampproject/amphtml#21410]
## What's the issue?

AMP-bind  component doesnot allow selectbox to open in firefox mobile

## How do we reproduce the issue?
create an amp markup
1.include amp-bind in head section.
2. Add a select input tag in body/form section 
3. Add a tap event on body tag.
4 .launch Firefox browser on any mobile device(tested on Android) and tap on selectbox.

Expected behavior : 
Default device drop down should open  and user should be able to interact with options.

Actual behavior:
Dropdown opens and hides for the first time and subsequent try doesnot do anything.

## What browsers are affected?
Mozilla firefox (Mobile)

## Which AMP version is affected?
Version 1903070012530

**Comment by aghassemi** [comment]
@rehansh16 could you please provide a repro Url?

**Comment by choumx** [comment]
Closing as stale due to lack of repro information.
