### ISSUE TITLE
AMP linter

### ISSUE THREAD

**Issue by honeybadgerdontcare** [ampproject/amphtml#21418]
An AMP linter that runs on AMP documents and provides feedback on potential issues or alternatives.

This is not a replacement for the [AMP Validator](https://github.com/ampproject/amphtml/tree/master/validator). This is instead to provide different types of feedback than what the AMP Validator provides.

**Comment by honeybadgerdontcare** [comment]
#1971 mentions something a linter could provide:
When a user includes an `amp-img` with a `width=1` and `height=1` they may instead want to use `amp-pixel` as an alternative.

**Comment by sebastianbenz** [comment]
//cc @ithinkihaveacat
