### ISSUE TITLE
GTAG custom dimensions

### ISSUE THREAD

**Issue by arunke1** [ampproject/amphtml#21419]
Hi,

We’re using GTAG on the AMP pages and everything works with the exception of the custom dimension (we use custom dimensions to filter between production and test in our GA 360 setup)

can you let me know how to include custom dimensions properly?

<amp-analytics type="gtag" data-credentials="include">
      <script type="application/json">
         {
          "vars": {
            "gtag_id": "ID", //Make sure this is the right Campaign Manager ID.
            "config": {
              "ID": { //Same ID as above.
                "groups": "default"
              },
              "AW-ID": { //Make sure this is the right Google Ads ID.
              "groups": "default"
              },
              "UA-ID": { //Make sure this is the right Google Analytics ID.
                "groups": "default"
              }
            }
          },
         
            "trackPageviewWithCustom": {
              "on": "visible",
              "request": "pageview",
              "vars": {"dimension1": "test"} //Still confirming this piece.
            }
          }
        }

      </script>

Thanks 
Arun

**Comment by zhouyx** [comment]
Thank you @arunke1 for creating the issue. 

Looping in @avimehta and @zikas for better context on GTAG support. Thank you

**Comment by zikas** [comment]
Gtag OGT schema resembles gtag web schema.
For custom dimensions the guidance is similar to
https://developers.google.com/analytics/devguides/collection/gtagjs/custom-dims-mets
```
{
  "vars": {
    "gtag_id": "UA-1234-1",
    "config": {
      "UA-30481-5": {
        "custom_map": {
          "dimension1": "age", 
          "dimension2": "color"
        }
      }
    }
  },
  "triggers": {
    "ua_conversion_event": {
      "on": "visible",
      "vars": {
        "event_name": "conversion",
        "age": 18,
        "color": "red"
      }
    }
  }
}
```

**Comment by torch2424** [comment]
@arunke1 Did @zikas solve your issue?

If so, we will go ahead and close this issue. Thank you! 😄

**Comment by zhouyx** [comment]
Thank you @zikas for the information. Closing the issue. @arunke1 feel free to reopen if this doesn't work for you.
