### ISSUE TITLE
Cannot read property 'getLoadMoreEndElement' of null

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#21420]
## What's the issue?
Cannot read property 'getLoadMoreEndElement' of null

Briefly describe the bug.
```
amp-list.js:725 Uncaught (in promise) TypeError: Cannot read property
'getLoadMoreEndElement' of null

```
## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. Open https://m.aliexpress.com/category/200003378/men's-costumes.html?categoryName=Men%27s+Costumes&spm=a2g0n.category-amp.leafcat.Men%27s%20Costumes Aliexpress.com
2. Open developer tools and see error in console

1. Open https://m.aliexpress.com/category/200216296/stationery-stickers.html?categoryName=Stationery+Stickers%20&spm=a2g0n.category-amp.leafcat.Stationery%20Stickers
2. Open developer tools and see error in console

## What browsers are affected?

macOSX Safari Version 12.0.3 (13606.4.5.3.1)
macOSX Chrome 72.0.3626.122 (Official Build) (64-bit)
macOSX FireFox 65.0 (64-bit)

## Which AMP version is affected?
Dev Channel - Version 1903122236150
Stable Channel - Version 1903141753530

Is this a new issue? Or was it always broken? Paste the version of AMP where you saw this issue. (You can find the version printed in your browser's console.)
N/A

cc: @aghassemi to triage, @rsimha 

![Screenshot 2019-03-14 at 1 40 08 PM](https://user-images.githubusercontent.com/48487406/54391267-8d6cca80-4661-11e9-82f7-b981723ff61b.png)

**Comment by aghassemi** [comment]
Thanks @diantekyrie. Related issue: https://github.com/ampproject/amphtml/issues/21403
/to @cathyxz

**Comment by cathyxz** [comment]
Thank you! I've been trying to reproduce this all of yesterday. Great find and great bug report by the way.
