### ISSUE TITLE
Error: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#21423]
## What's the issue?
Error: Cannot read property 'classList' of null

Briefly describe the bug.
```
Error: Cannot read property 'classList' of null
at getFragment (https://raw.githubusercontent.com/ampproject/amphtml/1903122236150/src/service/history-impl.js:988)
at delay (https://raw.githubusercontent.com/ampproject/amphtml/1903122236150/src/service/viewport/viewport-impl.js:846)
```

## How do we reproduce the issue?

Unable to reproduce easily on browser emulation.
Most likely occurs on specific user devices.
Error might possibly be occurring in viewer in Google Search.

URL: https://tw-news-yahoo-com.cdn.ampproject.org/v/s/tw.news.yahoo.com/amphtml/%E9%99%B3%E9%A1%AF%E6%94%BF%E7%B5%90%E5%A9%9A-%E5%B0%8F%E8%B1%AC%E7%A6%AE%E5%88%B0%E4%BA%BA%E6%B2%92%E5%88%B0.html?amp_js_v=0.1&usqp=mq331AQECAEoAQ%3D%3D

URL: https://m-tribunnews-com.cdn.ampproject.org/v/m.tribunnews.com/amp/nasional/2018/03/22/mau-tahu-cara-agar-pengaduanmu-direspon-kpk-cukup-penuhi-syarat-ini?amp_js_v=0.1&usqp=mq331AQECAEoAQ%3D%3D

## What browsers are affected?
Unsure, here are a few user agent strings that this error occurs on.
Mozilla/5.0 (Linux; Android 9; CLT-L29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Mobile Safari/537.36

Mozilla/5.0 (Linux; Android 8.1.0; Redmi S2 Build/OPM1.171019.011) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.91 Mobile Safari/537.36 

Mozilla/5.0 (Linux; Android 5.1.1; A37f Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Mobile Safari/537.36 OPR/37.0.2192.110129 

## Which AMP version is affected?
1903070012530
1903122236150

Is this a new issue? Or was it always broken? Paste the version of AMP where you saw this issue. (You can find the version printed in your browser's console.)
N/A

cc: @aghassemi

**Comment by jridgewell** [comment]
```
TypeError: Cannot read property 'classList' of null
    at https://cdn.ampproject.org/rtv/031903141753530/v0.js:312:90
    at Jm (https://cdn.ampproject.org/rtv/031903141753530/v0.js:509:234)
    at Fm.f.Fh (https://cdn.ampproject.org/rtv/031903141753530/v0.js:508:268)
    at jh.Dc (https://cdn.ampproject.org/rtv/031903141753530/v0.js:180:585)
    at zg (https://cdn.ampproject.org/rtv/031903141753530/v0.js:180:270)
    at https://cdn.ampproject.org/rtv/031903141753530/v0.js:359:767
```

**Comment by jridgewell** [comment]
I think this is caused by https://github.com/ampproject/amphtml/pull/20658. There might be a race between `documentReady` and the document actually parsing the body node. It shouldn't, though...
