### ISSUE TITLE
Clearly identify user errors vs. unexpected errors in console

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#21421]
## What's the issue?
amp-bind: Expression compile error is unclear whether issue is User error or internal error

## Briefly describe the bug.
Error message is unclear whether error is user generated. Can we add a prefix to the error message?

## How do we reproduce the issue?

1. Open https://m.aliexpress.com/category/200003378/men's-costumes.html?categoryName=Men%27s+Costumes&spm=a2g0n.category-amp.leafcat.Men%27s%20Costumes
2. Open developer tools and see error in console

## What browsers are affected?
macOSX Safari Version 12.0.3 (13606.4.5.3.1)
macOSX Chrome 72.0.3626.122 (Official Build) (64-bit)
macOSX FireFox 65.0 (64-bit)

## Which AMP version is affected?
Stable Channel - Version 1903141753530

cc: @choumx 
@aghassemi can you tell AliExpress about this issue.
@rsimha 

![Screenshot 2019-03-14 at 1 40 08 PM](https://user-images.githubusercontent.com/48487406/54392863-e3437180-4665-11e9-95e4-84ac78c5560d.png)

**Comment by aghassemi** [comment]
This is a user issue. /cc @leonalicious

**Comment by diantekyrie** [comment]
Also reproduced at https://m.aliexpress.com/category/200214074/women's-bracelet-watches.html?categoryName=Women%27s+Bracelet+Watches%20&spm=a2g0n.category-amp.leafcat.Women%27s%20Bracelet%20Watches

AMP Dev Version - 1903191703470

![Screen Shot 2019-03-20 at 10 11 45 AM](https://user-images.githubusercontent.com/48487406/54704755-9eea2280-4af8-11e9-89ad-a4a27bcf6109.png)

**Comment by caroqliu** [comment]
Closing this issue as it does not have clear action items for resolution. Perhaps related and more comprehensive discussion can occur in one of these threads: #32739, #27408, #8018
