### ISSUE TITLE
Invalidating AMP key returns 404, while on another subdomain it returnes the key

### ISSUE THREAD

**Issue by sirshurf** [ampproject/amphtml#21428]
## What's the issue?

I created a new key and put it at:
https://www.vpnmentor.com/.well-known/amphtml/apikey.pub

While I am requesting to update it here:
https://www-vpnmentor-com.cdn.ampproject.org/r/s/www.vpnmentor.com/.well-known/amphtml/apikey.pub
I am getting 404.
But if I am using another subdomain (that goes to the same location), for example
https://ru-vpnmentor-com.cdn.ampproject.org/r/s/ru.vpnmentor.com/.well-known/amphtml/apikey.pub
I am getting the key.

## How do we reproduce the issue?

Here I am getting 404:
https://www-vpnmentor-com.cdn.ampproject.org/r/s/www.vpnmentor.com/.well-known/amphtml/apikey.pub

Here I am getting the key:
https://ru-vpnmentor-com.cdn.ampproject.org/r/s/ru.vpnmentor.com/.well-known/amphtml/apikey.pub

And here is the key just in case:
https://www.vpnmentor.com/.well-known/amphtml/apikey.pub

## What browsers are affected?
All, and CURL too.

## Which AMP version is affected?
N/A

**Comment by torch2424** [comment]
cc @aghassemi

**Comment by jgluk** [comment]
I get success for both URLs. Can you try again? Maybe it was cached either in your browser or in the AMP Cache for a little while before you updated it?

**Comment by sirshurf** [comment]
Sorry did not closed this.

It was updated 2 days later
