### ISSUE TITLE
amp-fx alignment issues again

### ISSUE THREAD

**Issue by unumbox** [ampproject/amphtml#21430]
**Please only file bugs/feature requests for AMP here.**

amp-fx is causing issues with alignment again. This was raised last week with a fix announced and assume that the fix has caused more issues now impacting all directions.

See...
https://github.com/ampproject/amphtml/issues/21332

## What's the issue?

Elements with amp-fx fly-in-* are all misaligned. It appears to be related to data-fly-in-distance which when changed moves the position of the elements on initial load. If removed, the elements disappear from the page completely.

## How do we reproduce the issue?

I don't have any examples now as I have had to remove the animation to keep clients happy.

## What browsers are affected?

All

## Which AMP version is affected?

This is a new issue similar to one that was supposed to be fixed last week but has changed in nature.

**Comment by alanorozco** [comment]
Releasing fix as part of 1903191703470. Should be out soon. Bug did not make it to production. Thanks for reporting this!
