### ISSUE TITLE
Lightbox gallery: tap does not toggle controls anymore

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#21431]
Recent regression
/To @sparhami

**Comment by sparhami** [comment]
It looks like `i-amphtml-lbg-button-next` gets the click and calls `stopPropagation`, preventing the click handler for the controls hiding from running. This only happens on mobile (works fine with mouse click).

**Comment by sparhami** [comment]
Bisected it to https://github.com/ampproject/amphtml/commit/2c88dc7a6

Will take a look if there is a way to make both the tap to toggle and the other bug fix work.

/cc @cathyxz
