### ISSUE TITLE
🌸 Cherry pick request for #21430 into #21422 (Pending)

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#21438]
## GitHub issue your cherry pick is fixing:

Issue #21430

## PR that you are requesting a cherry pick for:

PR #21437

Production Release? NO

Canary release? YES

Release Issue #21422

## Why does this issue meet the [cherry pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

Items with `amp-fx=fly-in-*` are misaligned due to a dropped CSS property gaffe. Mea culpa.

/cc @cramforce

**Comment by aghassemi** [comment]
Bump @cramforce

**Comment by cramforce** [comment]
Didn't I approve this before? :)

Approved

**Comment by alanorozco** [comment]
Moot: cutting new canary since last week's did not make it to 1%.
