### ISSUE TITLE
setTimeout stub in 3p/environment.js bug in inner iframe

### ISSUE THREAD

**Issue by itaynave** [ampproject/amphtml#21433]
## What's the issue?

If using AMP-AD
And the content has inner ifframe
And instrumentEntryPoints(win) is called for the inner iframe
clearTimeout inside the inner iframe will not work

## How do we reproduce the issue?

The issue is simple
function instrumentEntryPoints(win) {
  // Change setTimeout to respect a minimum timeout.
  const {setTimeout} = win;
  win.setTimeout = function(fn, time) {
    time = minTime(time);
    arguments[1] = time;
    return setTimeout.apply(this, arguments);
  };
...

setTimeout for the inner iframe is replaced by a call to setTimeout in another window
Since each window has its own timers, calling clearTimeout on the returned timer in the inner Iframe will not do anything or worse will clear another timer with the same id in the other window

Not sure how to reproduce
Experienced it in an ad but its not live anymore

## What browsers are affected?
All

## Which AMP version is affected?
Any

## Suggestion
I thing the fix is simple
Just replace 
    return setTimeout.apply(this, arguments);
with
    return setTimeout.apply(win, arguments);

**Comment by torch2424** [comment]
cc @jridgewell @zhouyx
