### ISSUE TITLE
Multi-step form validation

### ISSUE THREAD

**Issue by AndrewKGuan** [ampproject/amphtml#21449]
Can multi-step amp-form validate when user clicks on a 'next' button only the inputs on the screen?  Multi-step form is a very common UI pattern such as questionnaires and lead gens. 
Breaking down a form into multiple screens and providing a button to advance is doable, what is missing is a way to validate inputs on each step and enable/disable advancing based on the validation.
I'm hoping this common UI pattern can be built into form and made as easy to use as other form validation features.

**Comment by nainar** [comment]
This is a good usecase for amp-script. However, I do agree that we should solve this generically in AMP as it is an important use case for both publishing and e-commerce spaces as highlighted above.

**Comment by AndrewKGuan** [comment]
Thanks Nainar!

**Comment by cvializ** [comment]
This is an important flow to support. I'll investigate the best way forward to implement this

**Comment by fstanis** [comment]
There is a hacky way to do this right now:

```
<form id="form1" method="POST" action-xhr="no-op" on="submit:form2.show,form1.hide">
  <input type="text" name="fruit" on="change:AMP.setState({form: { fruit: event.value }})" required pattern="banana|cherry">
  <input type="submit" value="Next">
</form>
  
<form id="form2" method="POST" action-xhr="endpoint" hidden>
  <input type="hidden" name="fruit" [value]="form.fruit">
  <input type="text" name="name">
  <input type="submit" value="OK">
</form>
```

The main hacky thing about this is the `action-xhr="no-op"` bit, where an HTTP request has to be made (but even a 404 works in this case).

Two ideas off the top of my mind on how this can be better:

1.  Allow form to have no action (or something like `action-xhr="#"`) which just always results in immediate success (but still validates).

2. Add a new action `validate` to forms and also add a new event `validated`, allowing for something like this:

```
<form id="form1" method="POST" action-xhr="no-op" on="validated:form2.show,form1.hide">
  <input type="text" name="fruit" on="change:AMP.setState({form: { fruit: event.value }})" required pattern="banana|cherry">
  <button type="button" on="tap:form1.validate">Next</button>
</form>
  
<form id="form2" method="POST" action-xhr="endpoint" hidden>
  <input type="hidden" name="fruit" [value]="form.fruit">
  <input type="text" name="name">
  <input type="submit" value="OK">
</form>
```

**Comment by AndrewKGuan** [comment]
Thanks for the work-around, but would that work with browser back buttons?

**Comment by fstanis** [comment]
If that's the functionality you're after, perhaps it makes more sense to make a separate page for each form step and use regular form submission (non-XHR)?

**Comment by AndrewKGuan** [comment]
That's functionally viable but doesn't have the same instantaneous UX which client-side logic could provide though.  It requires a page navigation.
