### ISSUE TITLE
[amp-list] Items repeated when using load-more="auto"

### ISSUE THREAD

**Issue by Zhangdroid** [ampproject/amphtml#21455]
## What's the issue?

When using `amp-list` with `load-more="auto"`, sometimes some items will repeat twice when you scroll the page very fast.

## How do we reproduce the issue?

1. Visit https://test-amp-dnig5ghrx.now.sh/
2. Fast scrolling page
3. You will see some items are repeated 

![image](https://user-images.githubusercontent.com/6471705/54491596-aba12780-48fa-11e9-9b8e-35c01b346ffb.png)

Source code based on [load-more-auto.amp.html](https://github.com/ampproject/amphtml/blob/master/test/manual/amp-list/load-more-auto.amp.html)

## What browsers are affected?

Tested on Chrome 73 and Firefox, only Chrome has this issue.

## Which AMP version is affected?

 Version 1903141753530

**Comment by aghassemi** [comment]
/to @cathyxz 
Setting as P1 for post recent launch support

**Comment by cathyxz** [comment]
Yup, a fix is out. Thank you @Zhangdroid for the clean repro!
