### ISSUE TITLE
User error messages contain "%s"

### ISSUE THREAD

**Issue by clodisewp** [ampproject/amphtml#21457]
![1](https://user-images.githubusercontent.com/19813339/54520429-a77d1480-49a3-11e9-89d6-c9eb987d910e.jpg)
Can anyone tell my what does the word "%s" mean in the image above. It appeared many times, but I can not find the corresponding word in my code page.  It really makes me not easy to locate the error.
Thanks!

**Comment by jridgewell** [comment]
It seems our `sprintf` formatting is broken. It means the `<amp-bind>` element in this error message.

**Comment by choumx** [comment]
@erwinmombay Noticed this too. Looks like our error output formatting is not working as expected.

/cc @alanorozco

**Comment by rsimha** [comment]
Assigning to @alanorozco who might be able to solve this via #22146

**Comment by rsimha** [comment]
Marking this as closed now that #22146 has been merged. Please reopen if you see any stray `%s`s in the wild.

**Comment by choumx** [comment]
This is still an issue for `assert()` I think.
