### ISSUE TITLE
Issues with Implementing AMP PIP on youtube player 

### ISSUE THREAD

**Issue by tyagiudit** [ampproject/amphtml#21453]
Implemented the amp dock video player. Test URL can be found below:

https://m.navbharattimes.indiatimes.com/off-url-redirect/india/gautam-gambhir-may-contest-election-from-bjp-ticket-in-delhi/amp_articleshow_piptest/68313299.cms

Some of the issues that we are facing on Android Devices aross all browsers :

1. On Android devices, once PIP becomes dock, we are not able to control play/pause, mute/un-mute events. 
- We are able to do only first action i.e. moving from play to pause. And then if we try to play the video again, it is not happening.

2. We are not able to fire any GA events for PIP Dock. Un-Dock and PIP Close.

3. Dock video and inline embedded videos gets played at the same time. Ideally once user plays inline video and scrolls the inline video should get played in docked version. 

4. PIP Dock functionality is not supported on iPhone amp.

**Comment by aghassemi** [comment]
To @alanorozco 
Setting as P1 for post recent launch support

**Comment by alanorozco** [comment]
@tyagiudit Thanks for bringing this up. A few questions.

> On Android devices, once PIP becomes dock, we are not able to control play/pause, mute/un-mute events.

Is this by clicking on the docked controls or do you mean programatically?

> We are not able to fire any GA events for PIP Dock. Un-Dock and PIP Close.

No analytics events are fired for `dock`. It's however a sensible feature request.

> Dock video and inline embedded videos gets played at the same time. Ideally once user plays inline video and scrolls the inline video should get played in docked version.

I'm not sure I follow the question? Do you mean a different video than what's currently docked?

> PIP Dock functionality is not supported on iPhone amp.

It should be supported directly, but not in the viewer. This is for technical reasons, and at this time it's not possible to make docking work on viewer/iOS.

**Comment by tyagiudit** [comment]
> @tyagiudit Thanks for bringing this up. A few questions.
> 
> > On Android devices, once PIP becomes dock, we are not able to control play/pause, mute/un-mute events.
> 
> Is this by clicking on the docked controls or do you mean programatically?
>> On clicking on the docked controls it works only the first time, but does not work subsequently on the click event. Programatically its working.

> 
> > We are not able to fire any GA events for PIP Dock. Un-Dock and PIP Close.
> 
> No analytics events are fired for `dock`. It's however a sensible feature request.
> 
> > Dock video and inline embedded videos gets played at the same time. Ideally once user plays inline video and scrolls the inline video should get played in docked version.
> 
> I'm not sure I follow the question? Do you mean a different video than what's currently docked?
>> There are cases when in an article there would be a lead video and a video embedded inside the article body. If a user clicks on the lead video and scrolls the video starts playing in docked state. However now if the user clicks on the embedded video inside the article body while the docked video is playing, then user ends up watching two videos at the same time, one in docked state and other in inline state. Idle implementation would be that at any point of time based on user's intent only one video should play wheather in docked or inline state.
> 
> > PIP Dock functionality is not supported on iPhone amp.
> 
> It should be supported directly, but not in the viewer. This is for technical reasons, and at this time it's not possible to make docking work on viewer/iOS.
>> Thats fine. We've removed the support on iOS. Major user base is Android

**Comment by tyagiudit** [comment]
> > @tyagiudit Thanks for bringing this up. A few questions.
> > > On Android devices, once PIP becomes dock, we are not able to control play/pause, mute/un-mute events.
> > 
> > 
> > Is this by clicking on the docked controls or do you mean programatically?
> > > On clicking on the docked controls it works only the first time, but does not work subsequently on the click event. Programatically its working.
> 
> > > We are not able to fire any GA events for PIP Dock. Un-Dock and PIP Close.
> > 
> > 
> > No analytics events are fired for `dock`. It's however a sensible feature request.
> > > Dock video and inline embedded videos gets played at the same time. Ideally once user plays inline video and scrolls the inline video should get played in docked version.
> > 
> > 
> > I'm not sure I follow the question? Do you mean a different video than what's currently docked?
> > > There are cases when in an article there would be a lead video and a video embedded inside the article body. If a user clicks on the lead video and scrolls the video starts playing in docked state. However now if the user clicks on the embedded video inside the article body while the docked video is playing, then user ends up watching two videos at the same time, one in docked state and other in inline state. Idle implementation would be that at any point of time based on user's intent only one video should play wheather in docked or inline state.
> > 
> > 
> > > PIP Dock functionality is not supported on iPhone amp.
> > 
> > 
> > It should be supported directly, but not in the viewer. This is for technical reasons, and at this time it's not possible to make docking work on viewer/iOS.
> > > Thats fine. We've removed the support on iOS. Major user base is Android

@alanorozco : Hope the above feedback was helpfull. Let me know if you need anything else

**Comment by alanorozco** [comment]
> On clicking on the docked controls it works only the first time, but does not work subsequently on the click event. Programatically its working.

I haven't been able to repro but will continue to take a look. 

> There are cases when in an article there would be a lead video and a video embedded inside the article body. If a user clicks on the lead video and scrolls the video starts playing in docked state. However now if the user clicks on the embedded video inside the article body while the docked video is playing, then user ends up watching two videos at the same time, one in docked state and other in inline state. Idle implementation would be that at any point of time based on user's intent only one video should play wheather in docked or inline state.

Valid feature request, will prioritize.

@tyagiudit Would you mind filing two separate issues for each of these? Thanks!

Closing this one since it won't be able to be tracked, but will prioritize the follow-up issues.

**Comment by aghassemi** [comment]
@alanorozco could you split this into FRs and Bugs add to Project [UI - Recent Launch Support]( https://github.com/ampproject/amphtml/projects/74) project?
