### ISSUE TITLE
Dynamically change number of months in AMP date-picker

### ISSUE THREAD

**Issue by waldemarschneider** [ampproject/amphtml#21456]
It would be great to change the number-of-months depending on the screen size.
So when the user has a desktop device, two months can be displayed next to each other, while a user with a mobile device gets displayed only one month.
One easy solution would be to use the capabilities of amp-img, where size can be set via screenwidth.

**Comment by aghassemi** [comment]
@waldemarschneider AMP's `media` attribute works on all elements. (https://www.ampproject.org/docs/design/responsive/control_layout). Would that help with your use case? (e.g. you can have two `amp-date-pickers` which different `media` conditions each with different configuration)

@cvializ I think supporting media-based attributes (like amp-base-carousel has started doing) would make this easier.

**Comment by cvializ** [comment]
Thanks for the feature request @waldemarschneider! This would be a good improvement to make

**Comment by waldemarschneider** [comment]
Thanks Carlos - looking forward :) Let me know if I can help in any way.
