### ISSUE TITLE
Uncaught (in promise) Error: Element "amp-youtube, amp-video" not found: null​

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#21492]
## What's the issue?
Uncaught (in promise) Error: Element "amp-youtube, amp-video" not found: null​

Briefly describe the bug.
Error message displays amp-youtube element is not found when no videos appear to be visible on the page

## How do we reproduce the issue?

1. Open Google Search
2. Open developer tools and see error in console 
3. Search for Lakers 
4. Choose SBNation about "Lakers Rumors" https://www.google.com/amp/s/www.silverscreenandroll.com/platform/amp/2019/3/19/18273210/lakers-rumors-lonzo-ball-impressed-nba-gm-defense-ucla-news-eric-pincus-bleacher-report

## What browsers are affected?
macOSX Chrome Version 73.0.3683.75 (Official Build) (64-bit)
macOSX Safari Version 12.0.3 (13606.4.5.3.1)
macOSX FireFox: 65.0 (64-bit)

## Which AMP version is affected?

Stable Version: 1903141753530

![Screen Shot 2019-03-19 at 4 00 35 PM](https://user-images.githubusercontent.com/48487406/54647559-2a63a500-4a60-11e9-96f5-3c1459241872.png)

**Comment by diantekyrie** [comment]
Looks like a recurring issue on SBNation.
Found on https://www.google.com/amp/s/www.silverscreenandroll.com/platform/amp/2019/3/26/18282572/lakers-rumors-tyronn-lue-lebron-james-magic-johnson-luke-walton-culture-coaching-news-espn

AMP Version: 1903191703470

cc: @alanorozco 

![Screen Shot 2019-03-26 at 3 25 29 PM](https://user-images.githubusercontent.com/48487406/55037570-6c01cc00-4fdb-11e9-88f8-8f71b4ed04eb.png)

**Comment by alanorozco** [comment]
This is not an AMP error.

Just because an error is displaying in the console, it doesn't mean it's an issue. We log `user`-level errors that are supposed to aid developers, but that don't necessarily mean there's anything wrong with the runtime.

In this case, this is due to analytics misconfiguration on the publisher's side.
