### ISSUE TITLE
Allow localizing CTA of AMP story Ad

### ISSUE THREAD

**Issue by Jeshuaviv** [ampproject/amphtml#21491]
## What's the issue?

how we can change the lenguage of CTA of an AMP Story ad?

## How do we reproduce the issue?
isn't an issue. This is a predefined set of choices. https://www.ampproject.org/docs/ads/story_ads_best_practices#call-to-action-button-text-enum

If this is a feature request you can use this section to point to a prototype/mockup that will help us understand the request.

## What browsers are affected?

All browsers

## Which AMP version is affected?

/amp-story/1.0
![CTA-ampstory-ad](https://user-images.githubusercontent.com/5267241/54648390-aadbd300-4a6b-11e9-9b4c-e2d108670a9b.png)

**Comment by torch2424** [comment]
Triaging to @calebcordry 😄

**Comment by newmuis** [comment]
I've actually been handling this; it's not currently possible, but I have #21239 and #21253 out to add this functionality.

**Comment by newmuis** [comment]
Whoops; those have both been merged for several weeks, but I forgot to close this 😅 

Let me know if there are any issues!
