### ISSUE TITLE
[amp-form] Submit handler does not include named submit button in form data

### ISSUE THREAD

**Issue by westonruter** [ampproject/amphtml#21498]
## What's the issue?

When submitting a form, the form data does not include the field for a named submit button, neither when explicitly clicked or implicitly clicked.

An [issue](https://wordpress.org/support/topic/amp-jetpack-subscribe-button-stopped-working/) was filed for the AMP plugin due to a email subscription form not working. The form looks like this:

```html
<form method="post" action-xhr="https://example.com/subscribe/" target="_top">
    <p id="subscribe-email">
        <label for="email">Email Address</label>
        <input id="email" type="email" name="email" required>
    </p>

    <p id="subscribe-submit">
        <input type="hidden" name="action" value="subscribe">
        <button type="submit" name="jetpack_subscriptions_widget">Subscribe</button>
    </p>

    <div submit-error="">
        <template type="amp-mustache">{{{error}}}</template>
    </div>
</form>
```

When clicking the submit button, the posted form data consists of two fields:

```
email: jsmith@example.com
action: subscribe
```

_However_, the Jetpack plugin here is actually [looking for another field](https://github.com/Automattic/jetpack/blob/e3986c699471dbb1dab42bdeac2041b8c979514c/modules/subscriptions.php#L84): `jetpack_subscriptions_widget`. So it is expecting form data to look like:

```
email: jsmith@example.com
action: subscribe
jetpack_subscriptions_widget:
```

This is what you get when submitting the same form on a non-AMP page.

There is a simple workaround for this, by just creating a hidden input:

```html
<input type=hidden name=jetpack_subscriptions_widget>
```

However, it would be ideal if the behavior of amp-form more closely aligned with regular forms to prevent needing workarounds. And such workarounds would not always work, so I believe this should be fixed.

Note that the browser includes a field in the form data for the _first_ named submit button even when enter was pressed inside a text input field. Otherwise, if a submit button was clicked, then the name of the clicked submit button is included instead.

## How do we reproduce the issue?

Simply provide a `name` to a submit button, and observe that the button is not included in the form data.

For example: https://jsbin.com/cizujes/edit?html,output

## What browsers are affected?

Chrome (at least)

## Which AMP version is affected?

1903141753530

**Comment by westonruter** [comment]
cc @aghassemi

**Comment by aghassemi** [comment]
I believe https://github.com/ampproject/amphtml/pull/18785 tried to handle this (it tries to figure out which submit button was clicked and adds it's value to body data). Maybe you are hitting an edge case. To @cvializ to investigate

**Comment by cvializ** [comment]
Thanks for reporting and creating the minimal repro case! I'm able to reproduce and I found the root cause
