### ISSUE TITLE
Invalid URL protocol 'itms-services:' for attribute 'href' in tag 'a'.

### ISSUE THREAD

**Issue by iamafu** [ampproject/amphtml#21499]
This is common for iOS user. If developer can't publish or beta app to app store, they share itms-services link for user to install .ipa file (app) to iphone or ipad.

Need to allow support for itms-services protocol for anchor links, so users can serve iOS apps.

Thanks.

**Comment by torch2424** [comment]
Hello! Thanks for reporting this!

So this is a duplicate of #21225 , so I will close this, in favor of the original issue.

That being said, we are aware, and looking into it. Thank you! 😄
