### ISSUE TITLE
Scrolling not responding correctly

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#21511]
## What's the issue?
Scrolling not responding correctly

Briefly describe the bug.
Scrolling sideways then up and down displays the scrolling bar moving, while the page doesn't move

## How do we reproduce the issue?
1. Go to https://m.aliexpress.com/item/32864032203.html?pid=808_0000_0201&spm=a2g0n.search-amp.list.32864032203&aff_trace_key=&aff_platform=msite&m_page_id=6381amp-i-NUhnrXOPm9ijLvWkMEcQ1553124880414 
2. Open developer tools
3. Scroll down to feedback
4. Select “View More”
5. Use mouse to swipe left/right, then attempt to swipe up/down

## What browsers are affected?
macOSX Chrome Version 73.0.3683.75 (Official Build) (64-bit)

## Which AMP version is affected?
RC-Channel: 1903191703470

https://media.giphy.com/media/3s8XMg9wNUQijmmuhL/giphy.gif
![Scrolling_issue_version_1903191703470](https://user-images.githubusercontent.com/48487406/54727578-d1fed700-4b35-11e9-8824-5a3f2c6399cd.gif)

**Comment by aghassemi** [comment]
@diantekyrie Thanks for the video and details. Have you been able to repro with dev tools closed or on real device? I have not been able to repro and looking at the code it looks like it is just a normal scrollable `div`. wondering if it is dev tools messing things up.

**Comment by diantekyrie** [comment]
@aghassemi If dev tools is off it works with no issues. Currently, I am able to reproduce on my iPhone XS on the Chrome and Safari browsers. The link to the Gif is here https://gph.is/g/E0K3Xb4

**Comment by aghassemi** [comment]
Chatted offline. can repo. It is an AMP bug, not publisher.

**Comment by nainar** [comment]
Page is unavailable.
