### ISSUE TITLE
AMP Pages Don't Behave Identically with Force Pinch to Zoom as Original URL

### ISSUE THREAD

**Issue by jdkang** [ampproject/amphtml#21513]
## What's the issue?

AMP Pages have disjointed if not mostly broken swipe and drag scrolling behavior when using forced punch zoom in Google Chrome mobile for Android 

## How do we reproduce the issue?

https://www.google.com/amp/s/www.cbsnews.com/amp/news/google-paid-35million-former-executive-amit-singhal-accused-sexual-harassment/

1. In Chrome, Settings > Accessability: Enable Force Zoom
2. Visit AMP Page 
3. Pinch zoom into page 
4. Attempt to navigate page while zoomed using swipes and drag gestures 
5. Visit original URL from AMP bar 
6. Repeat steps 3 and 4

## What browsers are affected? 

AFAIK Chrome 72 for Android 

## Which AMP version is affected?

Been an issue for awhile. Not sure how long.

**Comment by aghassemi** [comment]
Thanks for the report @jdkang. Viewer is somewhat separate from AMP OSS, I have raised the issue with the team and tracking it internally.

b/38496044

**Comment by joshm33333** [comment]
just want to say, this is an absolute deal breaker for our company and our 50+ clients
pinch to zoom is critical because many people with poor vision use our sites, to think amp has determined accessibility to be less than a priority concern is unfortunate
