### ISSUE TITLE
AMP auto-ads stopped appearing on the website 

### ISSUE THREAD

**Issue by allexeye** [ampproject/amphtml#21514]
AMP auto ads stopped showing yesterday on 20.03.19 and still not showing.

Console logs:
log.js:187 No placements in config
log.js:187 unable to fulfill ad strategy

URL example:
https://www.testingcatalog.com/report/amp/464

No changes on the website or Adsense console has been made.
This is not the first time when this error happens but all previous issue tickets are closed.

**Comment by torch2424** [comment]
cc @ampproject/ads

**Comment by torch2424** [comment]
Triaging to @zhouyx in the meantime, just to get this looked into. 😄

**Comment by jasti** [comment]
@allexeye
![Screen Shot 2019-03-29 at 2 24 34 PM](https://user-images.githubusercontent.com/2366341/55263505-7ec00f00-522e-11e9-8728-59c01183c8c2.png)
 it looks like ads are working on your site - could you confirm?

**Comment by allexeye** [comment]
Yes, ads got back on the next day @jasti 
Thanks for checking!

**Comment by torch2424** [comment]
@allexeye Thanks for reporting back! Can we close this? 😄
