### ISSUE TITLE
AMP Access Login: RETURN_URL parameter is wrapped in braces, which breaks redirect back to AMP page.

### ISSUE THREAD

**Issue by charlesdavis** [ampproject/amphtml#2152]
**AMP Access**

The RETURN_URL parameter passed to the publisher login page is wrapped in curly braces. For example:
```
?return={https%3A%2F%2Fcdn.ampproject.org%2Fv0%2Famp-login-done-0.1.html%3Furl%3Dhttp%253A%252F%252Fwww.publisher.com%252Famp%252Farticles%252F000001}
```
When the login page attempts to redirect the user back to the return URL (i.e. the AMP page), the braces cause the browser to treat the URL as relative. This results in the browser prefixing the href with the login page origin, for example: 
```
https://amp.publisher.com/%7Bhttps://cdn.ampproject.org/v0/amp-login-done-0.1.html?url=http%3A%2F%2Fwww.publisher.com%2Famp%2Farticles%2F000001%7D#success=true
```

**Comment by dvoytenko** [comment]
Apologies. The example in the documentation was wrong, the declaration should be done without `{}` simply as 
```
?return=RETURN_URL
```

I've updated the documentation.

**Comment by dvoytenko** [comment]
Closing the issue, but please reopen if there are any other comments.
