### ISSUE TITLE
amp-instagram rendering just a frame, but no content

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#2153]
http://nypost.com/2016/02/19/ronda-rousey-embarrassed-by-two-photos-for-opposite-reasons/amp/

<img width="400" alt="screen shot 2016-02-19 at 1 35 35 pm" src="https://cloud.githubusercontent.com/assets/3888212/13189688/b3c581f2-d70d-11e5-9479-f985a67f6396.png">

**Comment by rudygalfi** [comment]
@mkhatib Can you take a look?

**Comment by cramforce** [comment]
I'll take this.

**Comment by cramforce** [comment]
This is because the photo doesn't exist and instagram's error page doesn't allow for display inside of iframes: https://www.instagram.com/p/BB5Iy55hEbm%2F/embed/?v=4
