### ISSUE TITLE
Verify, document and support IE11 for AMPHTML ads

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#21544]
IE11 for AMP web pages has ["it might not be perfect but isn't broken"]("https://github.com/ampproject/amphtml/blob/d213748059fd117bc832d9fe20819006b5fa77d3/contributing/DEVELOPING.md#supported-browsers) support but since a non-insignificant traffic for ads is served to IE11, we should look at supporting IE11 for AMPHTML ads. 

As part of this task, verify and support IE11 for AMPHTML ads and split AMPHTML ad support compared to web page support. 

CC @ampproject/a4a

**Comment by taymonbeal** [comment]
Do we run automated tests on IE? If not, that would seem to be step 1.

**Comment by lannka** [comment]
we're deprioritizing IE11 support for AMPHTML ads. closing now
