### ISSUE TITLE
Fix flaky test `should layout amp-img, amp-pixel, amp-analytics`

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#21545]
Disabled in #21538

/cc @zombifier

**Comment by zombifier** [comment]
Just speculating, but this block (added by me :shamecube:) is probably the culprit:

https://github.com/ampproject/amphtml/blob/master/test/integration/test-amp-inabox.js#L158-L161

The rest of the BTF tests doesn't flake because the resizing is ensured to happen before the iframe renders.

**Comment by lannka** [comment]
@zombifier could you help to fix this? thanks
(tried to assign the issue to you but could not. I guess you have to join some group to be able to take AMP issues)...

**Comment by rsimha** [comment]
This test has been causing fairly regular failures on Firefox (among other browsers).

```
DESCRIBE => A4A
  DESCRIBE => AMPHTML ads rendered on AMP page
    DESCRIBE =>  
      IT => should layout amp-img, amp-pixel, amp-analytics
        ✗ Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
...

Firefox 66.0.0 (Windows 10.0.0): Executed 119 of 521 (1 FAILED) (skipped 402) (5 mins 58.32 secs / 1 min 22.843 secs)
```

@zombifier Any chance you can skip it too?

**Comment by zombifier** [comment]
Just want to note that these tests are A4A, and distinct from inabox tests (which I'm responsible for). Nevertheless there's significant overlap between them and I'm happy to submit the PR to skip them (and investigate them later).

**Comment by rsimha** [comment]
Oh, didn't realise that, since the names of the tests were nearly identical. 

Either way, thanks for the help in keeping Travis green!

**Comment by rsimha** [comment]
@zombifier this is still blocking PR checks.
```
DESCRIBE => A4A
  DESCRIBE => AMPHTML ads rendered on AMP page
    DESCRIBE =>  
      IT => should layout amp-img, amp-pixel, amp-analytics
        ✗ Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```
Can you skip this until it's more stable?

**Comment by zombifier** [comment]
#22165 is ready; since it doesn't look like it's improving you can merge it.
