### ISSUE TITLE
amp-ima-video CORS error with track

### ISSUE THREAD

**Issue by mcrump001** [ampproject/amphtml#21551]
## What's the issue?

Attempting to using <amp-ima-video> tag to add video with DFP ad url.  Video has vtt captions track as will.  When the page loads there is the familiar "Unsafe attempt to load URL" shows up in the debug console.  I have tried adding the crossorigin attribute to the <amp-ima-video> tag but it does not help.  I am guessing that the crossorigin attribute is not being passed through the ima iframe but I may be completely wrong.

## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. To see implementation using `<amp-ima-video>` **error**:
    * Browse to https://stage-mdev-wbns.pantheonsite.io/article/23-million-drugs-seized-during-search-olentangy-commons-apartment-ads-2019-mar?amp
2. To see implementation using `<amp-video>` **no error**:
    * https://stage-mdev-wbns.pantheonsite.io/article/23-million-drugs-seized-during-search-olentangy-commons-apartment-2019-mar?amp

## What browsers are affected?

All browsers and all devices

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1903141753530
Probably always broken

**Comment by mcrump001** [comment]
Hello,

Thanks for the very fast turn around on this issue!!

I see this issue has been closed and a PR submitted and merged.  When will the changes actually be applied to an AMP release?

Cheers,

Michael

**Comment by aghassemi** [comment]
It is currently in our release candidate. Will be in production next week.
