### ISSUE TITLE
analytics config url substitutions not properly delayed

### ISSUE THREAD

**Issue by gad2103** [ampproject/amphtml#2157]
our amp analytics tag:
````
<amp-analytics data-credentials="include" config="{tagxBaseUrl}/api/v1/amp_config.json?url={url|uc}&assetUrl={url|uc}&CG={contentGroup|uc}&SCG={subContentGroup|uc}&referrer=DOCUMENT_REFERRER&canonicalPath=CANONICAL_PATH&charSet=DOCUMENT_CHARSET&articleId={articleId|uc}&sections={sections|uc}&authors={authors|uc}&byline={displayByline|uc}&hitPaywall=AUTHDATA(hitPaywall)"></amp-analytics>

````
it seemed that #2093 was meant to solve this use case, but as far as i can tell it is not working. the requests for config and for the auth call seem to go out at about the same time which indicates that the AUTHDATA url replacement is not waiting for that parameter to resolve before sending the xhr request. 

however, all the other parameters are being replaced properly.

**Comment by cramforce** [comment]
@gad2103 Do you have a URL where we can debug this?

**Comment by cramforce** [comment]
Also CC @dvoytenko

**Comment by cramforce** [comment]
Ah, yes. So, this does definitely depend on the `amp-access-analytics` being turned on, but it also doesn't wait.

@dvoytenko Do you think it is fine to make `AUTHDATA` wait for `access.firstAuthorizationPromise_`?

**Comment by dvoytenko** [comment]
Not sure. Generally waiting is doable easily. But I don't know if this is what's always desired. My goal was to ensure that all Access events specifically wait for it. If misused, many analytics events could be reported with a significantly wrong timestamp drift.

**Comment by cramforce** [comment]
We could document it.

**Comment by cramforce** [comment]
Created #2161

I think that in general our public APIs (And `AUTHDATA` is as public as it gets) should be race free as we don't have a mechanism for coordination.

**Comment by gad2103** [comment]
@cramforce this still doesn't seem to be resolved. the calls for the config are going out without the AUTHDATA variable replacement. it is always empty in the request...

<img width="725" alt="screen shot 2016-03-01 at 3 49 13 pm" src="https://cloud.githubusercontent.com/assets/1045265/13441458/4023dada-dfc5-11e5-9e42-bbdf29a674a7.png">

please advise/re-open this is very important for us at nytimes. thanks!

**Comment by cramforce** [comment]
I think Karen and Rudy are up to date on the timing between them. We'll definitely update you when this launched.

**Comment by gad2103** [comment]
Ok. Thanks!

**Comment by rudygalfi** [comment]
#2391 is the change to enable `amp-access-analytics`. Should go in soon and will roll out according to the normal release process.
