### ISSUE TITLE
amp-social-share :: pinterest & facebook background color doesn't match brand guidelines 

### ISSUE THREAD

**Issue by Jessman5** [ampproject/amphtml#21576]
## What's the issue?

Specified brand colors for Pinterest and Facebook are not matching their brand guidelines

## How do we reproduce the issue?

1. Include `<amp-social-share type="pinterest">` and `<amp-social-share type="facebook">`on page.
2. Background color used in classes: .amp-social-share-pinterest is #bd081c, .amp-social-share-facebook is #3b5998

## What browsers are affected?

All browsers.

## Which AMP version is affected?

Using AMP ⚡ HTML – Version 1903141753530

## Solution

I've made a pullrequest already: [https://github.com/ampproject/amphtml/pull/21575](https://github.com/ampproject/amphtml/pull/21575)

Color for Pinterest should be #e60023 ([see here](https://business.pinterest.com/de/pinterest-brand-guidelines))
Color for Facebook should be #32529f ([see here](https://de.facebookbrand.com/#brand-guidelines-assets))

**Comment by aghassemi** [comment]
Thanks for the PR @Jessman5 ! Appreciate it. It is merged.

**Comment by aghassemi** [comment]
Fixed by #21575
