### ISSUE TITLE
`amp-user-notification` is hidden by the viewers chrome

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#2158]
`amp-user-notification` should be a sibling of body to solve `position: fixed` issues as well as to avoid being hidden by the viewers chrome if padding top is set.

reference https://github.com/ampproject/amphtml/pull/2128

**Comment by cramforce** [comment]
@erwinmombay Right, you can ask the viewer for what should be your minimum `top` value and enforce that to be set if the top is 0

**Comment by dvoytenko** [comment]
Here's the API I imagine:
```
viewport.showInFixedLayer(element);
```

The implementation will delegate to `FixedLayer` and basically will look very simple:
```
class FixedLayer {
  showInFixedLayer(element) {
    this.fixedElements_.push(element);  // But also check it's not there yet.
    return this.update();
  }
}
```

I think it'd be good idea to do. I simplified the testing for fixed layer. Now, all you need is to emulate `localhost` as iPhone and voila.

**Comment by cramforce** [comment]
Should we try to get this in on Monday or even earlier? I have yet to see one of these in the wild and they default to the bottom.

**Comment by amphtml-team** [comment]
We should try. If no one gets to it, I should be able to get to it on
Sunday evening.

**Comment by erwinmombay** [comment]
@cramforce i have the code that just does the offsetting through padding top. dont have any of the code that integrated with any of the new work @dvoytenko did.

**Comment by amphtml-team** [comment]
At this point it'd be better just to use fixedlayer, I think. But
offsetting from top is a fine temporary step
