### ISSUE TITLE
🌸 Cherry pick request for #21581 into 1903191703470 (Pending)

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#21585]
## GitHub issue your cherry pick is fixing:

Issue #21581

## PR that you are requesting a cherry pick for:

PR #21579

## Release(s) you requesting this cherry pick into:

1903191703470

Production Release? YES

Release Issue #21482

Canary release? YES

Release Issue: not yet created.

Causes video ads in amp stories to never play, so appears very broken :(

/cc @cramforce

**Comment by cramforce** [comment]
Is this a regression? Is this affecting any actual story in production?

**Comment by calebcordry** [comment]
Yes a regression, cnn is using it https://www.cnn.com/ampstories/health/your-guide-to-surviving-allergy-season

**Comment by cramforce** [comment]
Approved. Please next time note that in the bug.
