### ISSUE TITLE
Matomo/Piwik Support for AMP

### ISSUE THREAD

**Issue by ullahfahad** [ampproject/amphtml#21593]
Matomo (formerly Piwik) is one of the popular Analytics Vendor which is currently not supported by AMP as an Analytics Vendor.

It would solve a lot of issues and make things simpler if the support is added.

**Comment by aghassemi** [comment]
to @jeffjose

**Comment by zhouyx** [comment]
@ullahfahad Yes please. Here's the [doc](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/integrating-analytics.md) that can help with the integration process.
