### ISSUE TITLE
[amp-bind] support `bind-x` as a shorter alternative syntax for JSX

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#21600]
The current workaround for [amp-bind's brackets in JSX](https://www.ampproject.org/docs/reference/components/amp-bind#bindings) is `data-amp-bind-x="foo"` which is very noisy. It'd be great to also support a shorter version: `bind-x="foo"`. 

//cc @cramforce @choumx @timneutkens

@Gregable FYI for possible validator implications.

**Comment by Gregable** [comment]
@honeybadgerdontcare also. I don't see any validator problems with this unless bind-x is commonly used by something else in the wild. I don't know of anything like that. Could just be `amp-bind-x` too if so.

**Comment by choumx** [comment]
Minor implementation issue: `data-*` attributes are allowed by validator, but `bind-*` isn't. Possible to do but adds some noise and additional skew risk. Does saving the "data-amp-" chars help that much?

**Comment by sebastianbenz** [comment]
I think the main advantage of `bind-*` is improved readability and comprehensibility. I would go even as far as suggesting that this should be the new default for amp-bind related documentation: `bind-text="myValue"` is a lot more intuitive than `[text]="myValue".

**Comment by cramforce** [comment]
I wouldn't worry about the validator change costing time since this isn't super urgent.

**Comment by timneutkens** [comment]
This is still relevant.

**Comment by Gregable** [comment]
I'm going to close this as practically, I don't think we'll ever prioritize it. The current `data-amp-bind-*` works fine for the cases where bracket syntax is insufficient and the suggestion appears to be mostly cosmetic. It also comes with a downsides of increased complexity (one more api) and polluting the html attribute namespace further.
