### ISSUE TITLE
Design Review 2019-05-01 15:30 UTC (wg-access-subscriptions update, worker-dom Canvas)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#21603]
Time: [2019-05-01 15:30 UTC](https://www.timeanddate.com/worldclock/meeting.html?year=2019&month=05&day=01&iv=0) ([add to Google Calendar](http://www.google.com/calendar/event?action=TEMPLATE&text=AMP%20Project%20Design%20Review&dates=20190501T153000Z/20190501T163000Z&details=https%3A%2F%2Fbit.ly%2Famp-dr))
Location: [Video conference via Google Meet](https://bit.ly/amp-dr)

The AMP Project holds weekly engineering [design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md).  **We encourage everyone in the community to participate in these design reviews.**

If you are interested in bringing your design to design review, read the [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md) and add a link to your design doc by the Monday before your design review.

When attending a design review please read through the designs *before* the design review starts.  This allows us to spend more time on discussion of the design.

We rotate our design review between times that work better for different parts of the world as described in our [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md), but you are welcome to attend any design review.  If you cannot make any of the design reviews but have a design to discuss please let mrjoro@ know on [Slack](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#discussion-channels) and we will find a time that works for you.

**Comment by cvializ** [comment]
I'd like to present a design for a [precise geolocation component `amp-user-location`](http://go/amp-geolocation-design)

**Comment by mrjoro** [comment]
The Access control and subscriptions Working Group will be providing their periodic update at this design review.

/cc @jpettitt @ampproject/wg-access-subscriptions

**Comment by delima02** [comment]
I'd like to present a design for worker-dom's `Canvas` implementation. More specifically about polyfilling methods that return objects. [Link to Doc.](https://docs.google.com/document/d/1gQKP0i3CBzxaTmvQ9O_9XLseI6jyZhNAinKGO87BxwU/edit?usp=sharing)

**Comment by tobie** [comment]
@cvializ would you have a public link to that design doc, please?

**Comment by tobie** [comment]
Same request for @delima02: could you make the design doc public, please?

**Comment by cvializ** [comment]
@tobie Sure, here's a public link to the design doc https://docs.google.com/document/d/1oqnjA5KcUP7bHpz_HCtUTBH2jiqry65zGrpAUie1tHw/edit?usp=sharing

**Comment by delima02** [comment]
@tobie [Here](https://docs.google.com/document/d/1itdZt8ywHJmQP9iYWfOPDWhUIgMXJ-EFHuCpXk_tmrQ/edit?usp=sharing) is a public link to my document.

**Comment by cvializ** [comment]
An update, I am going to delay my document's review until next week

**Comment by mrjoro** [comment]
**worker-dom Canvas**

- @cramforce: could this be used to read data when we otherwise disallow it, e.g. for bitcoin use case 
  - if we don't let them make network requests and read the response, if you include data in pixels it's a way around it, for the case where we disallow fetch
  - @lannka: is the data opaque?
  - @dvoytenko: it's pretty common to want to manipulate the image data (image filters), we we need to consider this; @jridgewell: could do masks with normal context drawing, @dvoytenko: the use case is a bit different
  - @cramforce: for fetch, turn off the APIs when we don't want them; so far our design philosophy has been to reduce API surface difference, so only make async where it's absolutely needed to keep the diff small
  - @cramforce: let's separately talk about this case later; @jridgewell would like to understand this attack vector more
- API
  - @kristoferbaxter: we already have a lookup table for these, can we reuse?
  - @jridgewell: can we save two bytes in each request at the expense of complicating the logic a little bit??  or instead of passing down string id/arg id, we can pretend we're calling a real method (fillStyle with object or fillStyle with string on the main thread)
  - @kristoferbaxter would prefer to keep the signature the same
- @lannka: what stage are we in now?  Ads has a lot of creatives and we'd like to try it out to see if the use cases are covered
  - a PR is available; most things should work fine
  - @choumx: send over some sample code to try it

**Comment by mrjoro** [comment]
@jpettitt has published the [wg-access-subscriptions update](https://github.com/ampproject/wg-access-subscriptions/wiki/Status-Update---May-2019) he presented.

We'll link to future WG updates on [the meta WG wiki](https://github.com/ampproject/meta/wiki/Working-Group-Updates).
