### ISSUE TITLE
Story audio UX messages font size is broken.

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#21605]
Story audio UX messages font size is broken.

![image](https://user-images.githubusercontent.com/1492044/55096998-5353ed80-5091-11e9-824d-adbfd4e71e48.png)

**Comment by newmuis** [comment]
System UIs should not inherit the base font size, which is based on the size of the amp-story-page.  We can either remember to always use `px` sizes, or we can add code in the shadow DOM helper to set the font size of the shadow root to something reasonable (e.g. `16px`).
