### ISSUE TITLE
FR: Make amp-accordion share state across pages

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amphtml#21619]
## Make `amp-accordion` share state across pages

The `amp-accordion` component natively stores the state (expanded|collapsed) of its sections per page in the session. It would be nice if the state would not just be saved for a certain page but across pages as well.

An example real world use case is the sidebar in amp.dev's [Guides & Tutorials section](https://amp.dev/documentation/guides-and-tutorials.html). It is currently built using `input:checked` and would hugely benefit from a rebuild on `amp-accordion` with the described feature as the user's selection which sections are opened and which are not stays consistent when she advances through the docs.

## Alternatives considered

Only alternative I can come up with are ugly combinations of `amp-analytics`, `amp-state` and binding to the `expandend` attribute of `amp-accordion` what additionally isn't supported currently.

/cc @sebastianbenz

**Comment by sebastianbenz** [comment]
//cc @aghassemi
