### ISSUE TITLE
.well-known URL flexibility for update-cache 

### ISSUE THREAD

**Issue by mirceapiturca** [ampproject/amphtml#21617]
## Describe the new feature or change to an existing feature you'd like to see

cache-update require a RSA key stored at an exact location: https://example.com/.well-known/amphtml/apikey.pub

There are platforms that do not allow a custom file sistem.
Shopify.com for example keeps all its assets on CDN: https://cdn.shopify.com/s/files/1/xxx/xxx/files/...
Due to this technical limitation, developers are unable to run AMP pages on Shopify as cache update is impossibile.

I would like to propose for consideration a more flexible way of updating the AMP cache.

## Describe alternatives you've considered

For sites that can not have the apikey.pub stored at that exact location some alternative solutions may work:
- 301 redirect from .well-known/amphtml/apikey.pub to a custom location.
- HTML tag similar to Search Console verification: `<meta name="google-site-verification" content="your verification string">`.
- Similar method as update-ping with a domain limit.
- An alternative solution to purge the cache directly from the Search Console.

## Additional context

There are over 800.000 Shopify stores, approx 10% market share, that can benefit from AMP.
However there may be other platforms that due to this limitation can not properly use AMP.

Thank you

**Comment by torch2424** [comment]
Triaging to @Gregable , Feel free to re-assign 😄

**Comment by Gregable** [comment]
Thanks for the suggestion. I'll route your request to the Google AMP Cache product internal issue tracker and give you any updates here, though I'm not much more than a simple router.

I will add that the `<meta>` tag approach is probably not feasible as it is somewhat more common for an attacker to be able to inject content onto a page body than other mechanisms. I don't personally see any particular problem with the remaining.

**Comment by mirceapiturca** [comment]
Thank you,
Really looking forward

**Comment by Gregable** [comment]
Tracked as a google-cache specific issue, so no need to continue tracking here.
