### ISSUE TITLE
Uncaught Error: The first argument to CLIENT_ID, the fallback Cookie name, is required: undefined

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#21612]
## What's the issue?
```
Uncaught Error: The first argument to CLIENT_ID, the fallback Cookie name, is required: undefined
```

Briefly describe the bug.

## How do we reproduce the issue?

1. Open https://www.google.com/amp/s/pagesix.com/2019/03/27/why-denise-richards-invited-ex-charlie-sheen-to-her-wedding/amp/
2. Open developer tools and see error in console

## What browsers are affected?
macOSX Chrome Version 73.0.3683.86 (Official Build) (64-bit)
macOSX Safari Version 12.0.3 (14606.4.5)
macOSX FireFox Version 66.0.2 (64-bit)

## Which AMP version is affected?
Stable: 1903262220080
Dev: 1903262017080
RC: 1903262017080

Is this a new issue? Or was it always broken? Paste the version of AMP where you saw this issue. 
New Issue

/to: @ampproject/wg-analytics

Note: There is also the console error `"Uncaught (in promise) Error: Element "amp-carousel" not found: null​​​."` 

I'm noting that they have an analytic object thats detecting amp-carousel events, but there is no amp-carousel on the page.
I'm also noting the amp-auto-lightbox is defaulted to on, yet clicking on the image does not bring up a lightbox.

![Screen Shot 2019-03-27 at 3 08 56 PM](https://user-images.githubusercontent.com/48487406/55115662-4c81a680-50a2-11e9-8360-538a6cf38ce2.png)

 

![Screen Shot 2019-03-27 at 2 47 30 PM](https://user-images.githubusercontent.com/48487406/55114619-a634a180-509f-11e9-929f-e43e9682bdc9.png)

cc: @alanorozco,

**Comment by aghassemi** [comment]
also user error.
