### ISSUE TITLE
Uncaught (in promise) Error: Response must contain the AMP-Access-Control-Allow-Source-Origin header

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#21621]
## What's the issue?
`Uncaught (in promise) Error: Response must contain the AMP-Access-Control-Allow-Source-Origin header`

Briefly describe the bug.
Page does not contain "must contain the AMP-Access-Control-Allow-Source-Origin header"

## How do we reproduce the issue?
1. Open https://www.washingtonpost.com/arts-entertainment/2019/03/27/why-prosecutors-dismissed-charges-against-jussie-smollett/?utm_term=.8e5149138903
2. Open developer tools and see error in console

## What browsers are affected?
macOSX Chrome Version 73.0.3683.86 (Official Build) (64-bit)
macOSX Safari Version 12.0.3 (14606.4.5)
macOSX FireFox Version 66.0.2 (64-bit)

## Which AMP version is affected?
Stable: 1903262220080
Dev: 1903262017080
RC: 1903262017080

![Screen Shot 2019-03-28 at 9 30 21 AM](https://user-images.githubusercontent.com/48487406/55175244-27da0d00-513c-11e9-9367-0e53cfb8d4cf.png)

**Comment by aghassemi** [comment]
@diantekyrie  `response must contain the AMP-Access-Control-Allow-Source-Origin header` are user errors related to AMP CORS ( https://www.ampproject.org/docs/fundamentals/amp-cors-requests )
