### ISSUE TITLE
🌸 Cherry pick request for 21613 into 1903262017080 (Pending)

### ISSUE THREAD

**Issue by sparhami** [ampproject/amphtml#21622]
## PR that you are requesting a cherry pick for:

PR #21613

## Release(s) you requesting this cherry pick into:

Production Release? NO
Canary release? YES

## Why does this issue meet the [cherry pick criteria]

This breaks re-opening lightboxes on Safari. Since this is a rollback of a small change, it does not have downstream affects.

/cc @cramforce

**Comment by cramforce** [comment]
Approved

**Comment by aghassemi** [comment]
It has been cherry-picked. 

Closing.
