### ISSUE TITLE
Support Video Components in Email

### ISSUE THREAD

**Issue by shawnmaten** [ampproject/amphtml#21620]
## Describe the new feature or change to an existing feature you'd like to see

Support for amp-video (and/or other video components) in amp4email. Trying to get comments on its feasibility and likelihood.

## Describe alternatives you've considered

There's not really an alternative to video, but I could see this needing to be limited to approved video providers, rather than any content source.

## Additional context

I found mention of proxy issues in the amp4email announcement issue.
https://github.com/ampproject/amphtml/issues/13457#issuecomment-388475072
I'm not exactly clear what's meant by this, but the caveats section in the first comment mentions that all media has to be proxied in order to hide viewer's IP, location, etc. So is it an issue of proxying files of that size?

I would also imagine there would be concern about the user experience, particularly auto playing videos. I'm not requesting auto play. I think in an email context it should require user interaction to load and play.

**Comment by shawnmaten** [comment]
Tried to mention @ampproject/wg-amp4email team but that doesn't seem to work so mentioning @choumx and @jasti since you're the contributors listed.

**Comment by choumx** [comment]
Correct, this is a reasonable FR but the issue is in the difficulty of proxying video streams. Certainly an area for future development.
