### ISSUE TITLE
amp-bind: Make [data-vars-*] bindable

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#21633]
When using amp-bind expression to set attribute values, we want amp-analytics to be able to collect some amp-bind expression value. 
This may be done through the `data-vars_*` attribute, I wonder if we can make the attribute bindable?

**Comment by choumx** [comment]
Not currently. You can see the list of bindable attributes in `bind-validator.js`.

- Do `data-vars_foo` attributes have any other use? Or do you just want a way to expose amp-bind state?
- Which use case does [AMP_STATE](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#miscellaneous) URL substitution var not satisfy?

**Comment by zhouyx** [comment]
> Do data-vars_foo attributes have any other use? Or do you just want a way to expose amp-bind state?

I want a way to expose amp-bind state: The `data-vars-*` attribute is only used to allow amp-analytics collecting element information. 
For example  `data-vars-foo=bar` leads to `${foo}=bar`.

>Which use case does AMP_STATE URL substitution var not satisfy?

`AMP_STATE` doesn't work well, in order to collect the value of an expression, it requires server side computation. 

Here's an example
I want to set element `[disable]=case1&&case2&&case3`. Then it requires analytics server to collect three states separately to determine if the element is disabled or not. 

Another option is to have amp-analytics being able to collect all attribute value from element, not limited to `data-vars-*`.

**Comment by choumx** [comment]
I see, sounds reasonable. 

You can try prototyping this by adding a condition to this function that allows binding to all attributes starting with "data-vars-": https://github.com/ampproject/amphtml/blob/47bd44948d0c57bd3c8e8b9cbb19b92c1e7c3b7a/extensions/amp-bind/0.1/bind-validator.js#L192

E.g.
```js
// Allow binding to all data-vars-* attributes for amp-analytics.
if (startsWith(property, 'data-vars-')) {
  return null;
}
```

For the binding, `data-amp-bind-x` is equivalent `[x]` and avoids the need for validation changes, so you could do:

```html
<!-- A bit ugly but will set attribute `data-vars-foo`. -->
<div data-amp-bind-data-vars-foo="case1 && case2">
```

Let me know if that works for you.

**Comment by choumx** [comment]
Re: `AMP_STATE()`, you can avoid server-side computation by using `AMP.setState()` on the client. E.g.

```
AMP_STATE(foo)

<button on="tap:AMP.setState({foo: case1 && case2 && case3})">
```
This may be less ergonomic than `data-vars-*` though.

**Comment by zhouyx** [comment]
Great! I think it works. 

Re: AMP_STATE()

I kind of like the idea of assigning the expression to a state, and report that state. But since the `foo` state cannot be updated without user interaction? I assume it requires one to set the `foo` value at all interactions where `case1`, `case2` `case3` value are being set. Which is less ergonomic I agree.
