### ISSUE TITLE
AMP Errors not showing from Shell command in PHP

### ISSUE THREAD

**Issue by joshin2017** [ampproject/amphtml#21634]
Hi
If I ran the command from CMD amphtml-validator https://ampbyexample.com/ it works fine, also give errors if the url is having amp issues.

But if I try same thing from Php Shell command : $output =  exec('amphtml-validator https://ampbyexample.com/'); It get PASS as return if the link is valid but if the link is having some amp issue it return empty.

**Comment by honeybadgerdontcare** [comment]
I haven't looked at PHP in a while but I'm guessing that this has to do with how `exec` is handling the return object. When validation occurs it returns an ValidationResult object that has both the status (PASS/FAIL) and the errors (ValidationErrors). https://github.com/ampproject/amphtml/blob/master/validator/validator.proto#L881

Have you tried using the [WebUI](https://validator.ampproject.org) to fetch the page instead and see the errors there?

If your tooling requires using PHP to call the NPM version of the validator then the `$output` would need to be able to inspect the `ValidationErrors` field on it.

@sebastianbenz 	do you have any suggestions?

**Comment by sebastianbenz** [comment]
Adding @westonruter who might have a better suggestion on how to run validation from PHP.

**Comment by westonruter** [comment]
@joshin2017 It appears that `exec()` only captures STDOUT. So to capture validation errors you'll need to redirect STDERR to STDOUT. Give this function a try:

```php
/**
 * Do amphtml validator.
 *
 * @param string $url URL.
 * @return array Returns array of validation errors found. If empty, then the validation passed.
 */
function do_amphtml_validator( $url ) {
	exec( sprintf( 'amphtml-validator %s 2>&1', escapeshellarg( $url ) ), $output, $return_var );

	// If exit code is 0, then the result is PASS.
	if ( 0 === $return_var ) {
		return [];
	}

	// Otherwise the $output consists of validation errors.
	return $output;
}
```

**Comment by joshin2017** [comment]
> @joshin2017 It appears that `exec()` only captures STDOUT. So to capture validation errors you'll need to redirect STDERR to STDOUT. Give this function a try:
> 
> ```
> /**
>  * Do amphtml validator.
>  *
>  * @param string $url URL.
>  * @return string[] List of validation errors found. If empty, then the validation passed.
>  */
> function do_amphtml_validator( $url ) {
> 	exec( sprintf( 'amphtml-validator %s 2>&1', escapeshellarg( $url ) ), $output, $return_var );
> 
> 	// If exit code is 0, then the result is PASS.
> 	if ( 0 === $return_var ) {
> 		return [];
> 	}
> 
> 	// Otherwise the $output consists of validation errors.
> 	return $output;
> }
> ```

_@westonruter : Thanks. Your code works.   (y)_ 
Thanks you @honeybadgerdontcare , @sebastianbenz
