### ISSUE TITLE
AMP Dashboard / app-index: Allow a link from the examples page to test/manual

### ISSUE THREAD

**Issue by torch2424** [ampproject/amphtml#21646]
Some people on the team prefer to use `test/manual`, would be nice for an easy way to jump there, since `examples/` is the default.

**Comment by alanorozco** [comment]
Already working on it for an upcoming redesign of the devdash.

**Comment by rsimha** [comment]
@alanorozco Is this still relevant? (The `List root directory` link can lead to `test/manual`. Is that sufficient?)

**Comment by rsimha** [comment]
_[Infra triage]_ Closing this issue as stale. Please reopen if required.
