### ISSUE TITLE
Why !important gets stripped out?

### ISSUE THREAD

**Issue by vegtelenseg** [ampproject/amphtml#21641]
Hello

Thanks for the great library.

Quick one, why is the `!important` css rule get stripped out?

Thanks so much

Siya

**Comment by aghassemi** [comment]
Hi @vegtelenseg.

https://www.ampproject.org/docs/design/responsive/style_pages has some details on our CSS restrictions. In short, disallowing `!important` is needed to enable AMP to enforce its element sizing rules. AMP elements set their one style on the element for sizing and we need to ensure they have the highest specificity.

**Comment by aghassemi** [comment]
Hope this answers your question. Please feel free to reopen the issue if needed.
