### ISSUE TITLE
Date Picker (range)

### ISSUE THREAD

**Issue by waldemarschneider** [ampproject/amphtml#21656]
The user needs to be able to select the same date even if the date-picker is set to "range".
For example, the user wants to book a flight with a return flight on the same day.
One day is also a type of "range".
Doesn't work on the examples on ampproject or ampbyexample as well.

**Comment by aghassemi** [comment]
@cvializ to take a look

**Comment by cvializ** [comment]
The `minimum-nights` attribute can be set to `0` to allow users to select the same start and end date. Does that work for your use-case?

**Comment by waldemarschneider** [comment]
It would - but I can't get that to work,... seems like the minimum-nights="0" doesn't work at all - even on the amp-by-example playground I can't get it to work...

**Comment by cvializ** [comment]
Can you help me understand in what way it is not working for you?

I created a demo page to check if it is working, and selecting the same start and end date appears to be working correctly: https://amp-minimum-nights.glitch.me

**Comment by waldemarschneider** [comment]
Sorry for the short reply - and yes your demo does work. The problem we're running into is that we get "null" instead of the date. Which also seems to be a problem on several examples I found. Your version seems to work as expected - so there must be a way to achieve that.
Thank you so much!

**Comment by cvializ** [comment]
Hmm I understand. It could be due to https://github.com/ampproject/amphtml/issues/20727 which was  affecting some use-cases. It was resolved by https://github.com/ampproject/amphtml/pull/21566 but it has not yet landed in production

**Comment by cvializ** [comment]
I'll close this for now. Thanks for letting us know about your experience!
