### ISSUE TITLE
Chrome 45 not supported?

### ISSUE THREAD

**Issue by popov654** [ampproject/amphtml#21651]
Not a bug, but a question. Here (https://www.ampproject.org/support/faqs/supported-browsers) you claim that the library should not be completely broken in mobile Chrome 28 and higher.

But then why is it broken in desktop Chrome 45 (I can't get the demos working)?

**Comment by aghassemi** [comment]
@popov654 Support for older browsers is limited to "DOM will render" but user interaction may be broken. This support is to ensure crawlers that use older browsers to render will see the correct DOM.

**Comment by popov654** [comment]
> Support for older browsers is limited to "DOM will render"
But it's not rendered. Look at this page:
https://ampbyexample.com/stories/introduction/amp_story_hello_world/

If I click "Continue anyway" button, nothing happens - I see just a black background.
