### ISSUE TITLE
Pause video/audio when user starts playing another video/audio

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#2165]
scenario

play audio
then start a video on the same page - you can hear the audio playing and also the video.

**Comment by cramforce** [comment]
Please add a little jsbin or other repro case.

**Comment by sriramkrish85** [comment]
@cramforce - we can repro in examples/everything.amp.html

**Comment by erwinmombay** [comment]
can you update the header to "Pause video/audio **when** user starts playing another video/audio"*

when i read it at first i thought a play in one component triggers another component to play.

**Comment by cramforce** [comment]
Ah, yes, that title makes more sense :)

**Comment by cramforce** [comment]
Now that we have pause almost everywhere we should implement this across video/youtube/vimeo/dailymotion/etc.

**Comment by rudygalfi** [comment]
I noticed over the weekend that when I played a video (I think it was a video in a tweet) it kept playing when I swiped over into another story. Would the change @cramforce mentioned (https://github.com/ampproject/amphtml/issues/2165#issuecomment-186496806) address this case too?

**Comment by cramforce** [comment]
@rudygalfi No, for that we have to roll out the iframe unloading we've done one-by-one also to tweets.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)

**Comment by rudygalfi** [comment]
@aghassemi Can you clarify why this remained open? Are we planning to do this?

**Comment by aghassemi** [comment]
@rudygalfi iOS Safari already enforces this (they do not play more than one video at the time and pause the other one automatically). Keeping this open to do the same for Chrome (unless we find out Safari is planning to relax this restriction)

**Comment by cramforce** [comment]
Chrome will switch to the same behavior as Safari for autoplay, I believe.
