### ISSUE TITLE
Validator reporting error on first character of HTML page

### ISSUE THREAD

**Issue by ziodave** [ampproject/amphtml#21654]
## What's the issue?

Validator is reporting an invalid AMP page. The same URL works on https://search.google.com/test/amp?.

It shows a red dot at the very beginning of the HTML:
![image](https://user-images.githubusercontent.com/11438/55323085-5fb7bc00-547e-11e9-94d0-ac79fa325f9a.png)

This character is nowhere to be found in the response. The response start with `<!DOCTYPE html...`.

## How do we reproduce the issue?

Validate the following URL:

https://windowsreport.com/google-drive/?amp

E.g.

https://validator.ampproject.org/#url=https%3A%2F%2Fwindowsreport.com%2Fgoogle-drive%2F%3Famp

## What browsers are affected?

Validator-related.

## Which AMP version is affected?

Validator-related.

**Comment by torch2424** [comment]
Triaging to @Gregable , feel free to re-assign 😄

**Comment by Gregable** [comment]
Your response starts with an unprintable unicode character before the doctype. It is a byte order mark:

```
$ curl https://windowsreport.com/google-drive/?amp | less

<U+FEFF><!DOCTYPE html>
<html lang="en-US" ...
```

**Comment by ziodave** [comment]
Thanks @Gregable, I should have checked better.

**Comment by Gregable** [comment]
No worries, it's hard to debug and lots of folks have hit this exact case.
