### ISSUE TITLE
Validator says that layout="responsive" is not supported in amp-carousel when width an height are missing which is confusing

### ISSUE THREAD

**Issue by sryze** [ampproject/amphtml#21673]
## What's the issue?

The [documentation for `amp-carousel`](https://www.ampproject.org/docs/reference/components/amp-carousel) states that `layout="responsive"` is supported where carousel type is `slides`, but I'm getting an error when using this type of carousel:

The specified layout 'RESPONSIVE' is not supported by tag 'AMP-CAROUSEL [type=carousel]'. (see https://www.ampproject.org/docs/reference/components/amp-carousel)

## How do we reproduce the issue?

```
<amp-carousel class="slides" type="slides" layout="responsive" controls loop>
</amp-carousel>
```

## What browsers are affected?

Tested in Chrome, Firefox on macOS

## Which AMP version is affected?

1903262220080

**Comment by aghassemi** [comment]
@sryze the message it confusing, the problem is you are missing `width` and `height` 
```<amp-carousel class="slides" type="slides" layout="responsive" width="300" height="150" controls loop >``` would work.

to @honeybadgerdontcare regarding the confusing error.

**Comment by honeybadgerdontcare** [comment]
We may be able to help the validator make a more informative error message with making the attribute `type=slides` a dispatch key for name/value/parent.

P3, will address when we can.
