### ISSUE TITLE
Cursor jumps to the end of the line in iOS browsers

### ISSUE THREAD

**Issue by xiaotong-kk9** [ampproject/amphtml#21674]
## What's the issue?

When user moves the cursor to the middle to insert some letters, the cursor will automatically jump to the end of the line after one letter has been inserted.

## How do we reproduce the issue?

1. Visit [link](https://m.lightinthebox.com/en) with iOS device(Chrome or Safari)
2. Click on the search bar
3. Input some key words like dress women
4. Click on the middle of the letters
5. Try to add more letters

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8028004/55391976-f793d380-556c-11e9-909f-6774c9a18c14.gif)

## What browsers are affected?

iOS 12.1.2
Both Safari and Chrome v73.0.3683.68
Both Native iOS input method and 3p input method in case you need to have a look :)

Ps: Cannot be reproduced with macbook(Safari&Chrome) or android device(Chrome)

## Which AMP version is affected?

1903262220080

**Comment by xiaotong-kk9** [comment]
This issue may be related to input-throttled.
I tried the [official demo](https://www.ampbyexample.com/components/amp-form/preview/) without any input-throttled event. It cannot be reproduced.
Hope this info helps.

**Comment by aghassemi** [comment]
@cvializ

**Comment by cvializ** [comment]
This is a known issue that we are looking at. It is a result the value produced by `input-throttled` getting bound to the value of the input by `amp-bind`. Because of a race condition, the value is updated by bind with a value that is older than what the user typed in and the cursor position is not preserved. Are you able to replace `input-throttled` with `input-debounced`?

**Comment by xiaotong-kk9** [comment]
Thank you @cvializ for your reply.
This can still be reproduced with `input-debounced`.
And because when another button is clicked, the content in the input need to be updated, so `[value]` is necessary.
