### ISSUE TITLE
Is there any Linker decode package for client ?  

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#21672]
To whom it may concern:

I like to adopt Linker as parameter  transition solution for AMP page to normal page. I've already check the doc - [linker-id-receiving](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/linker-id-receiving.md). Looks like [linker.js](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/linker.js) could do decode and encode for LINKER_PARAM.

I wonder is there any server side solution for developer to decode LINKER_PARAM. (with checksum validation) ?

Paul

**Comment by calebcordry** [comment]
Hi @meistudioli we do not currently offer any service to decode the linker checksum. It is something we have discussed in the past. In the meantime we recommend copying the code in `linker.js` as appropriate to suit your needs.

@jeffjose @zhouyx FYI, perhaps we should revisit this discussion.

**Comment by zhouyx** [comment]
Thank you for suggesting the optimization. 
@calebcordry do you recall why we decide to not provide the service in the past.

To verify the LINKER_PARAM, it requires sending the entire thing to the 3p service which includes user data like client id. TBH I'm am a bit concerned and don't think that AMP wants to play this role. 
But I think it's worth exploring the possibility of providing a link decoding library that can be easily imported.

**Comment by calebcordry** [comment]
@zhouyx We just weren't sure it was worth the effort, and if people would use it. It seems a few people have asked now.

**Comment by jeffjose** [comment]
@meistudioli Is this something you're still interested in?

**Comment by jerimiahwelch** [comment]
+1 for this. 

We have also adapted a solution using the code in linker.js, but this seems like a brittle approach if the way linker.js encodes parameters ever changes.

Our need is slightly different. In the example below the linker parameter needs to be decoded client side when the user transitions from the PWA+AMP /doctors section of the site to the rest of the site. This allows integration between AMP and existing Tealium data layer analytics. This is a common need/request from clients with large sites and tag manager integration.

An example:

https://preview-psjh.provhealth.org/doctors?region=onesite 
  =>
https://preview-psjh.provhealth.org/providence?amp_pvid=1*1u0ujtb*pid*YmJmNmVhYzgyZTlkMjIwNA..&_gl=1*1350p3c*_ga*YW1wLWV2WERnOWdpVGdveDhLZk5TeHFIcFE.

**Comment by nmcalabroso** [comment]
+1 on this. For now, I have to read the linker.js to perform our own decoding from the client-side.

**Comment by zhouyx** [comment]
I agree such a service would be very helpful. But I'm still unsure if the AMP team should host and maintain such a service. 
One question I have: is the linker used without analytics vendors? Asking because I know analytics tags will decode linker on the landing site. Thanks.
