### ISSUE TITLE
[Layers] amp-carousel: Autoplay broken when far from top of viewport

### ISSUE THREAD

**Issue by MrDiCi** [ampproject/amphtml#21675]
## What's the issue?

AMP carousel's autoplay function not working the further the carousel is from the top of the window. Trying to use the amp-carousel to create an amphtml ad banner which will slide several text lines. 

## How do we reproduce the issue?

Here's a codepen  https://codepen.io/MrDiCi/pen/KYpajL?editors=1000

To reproduce the issue, I've included 3 amp-carousels, comment out lines 137, 138, the third carousel autoplay will start working. Uncomment line 114 and all three carousels will stop autoplay. 

The more the gap, the better the chance for autoplay to stop working.

## What browsers are affected?

All browsers

## Which AMP version is affected?

AMP ⚡ HTML – Version 1903262220080

**Comment by sparhami** [comment]
Looks like the codepen works with the `layers` experiment enabled, but has issues when it is not enabled. Needs more investigation.

**Comment by sparhami** [comment]
@aghassemi How should we prioritize this?

**Comment by aghassemi** [comment]
This looks like a runtime issue with `viewportCallback`. Triaging to runtime to take a look. 
/cc @jridgewell

**Comment by choumx** [comment]
Layers is nearly ready for launch. Let's close this when it does.
