### ISSUE TITLE
amp-date-countdown inside of amp-list causes error when list is refreshed

### ISSUE THREAD

**Issue by YonahKarp** [ampproject/amphtml#21680]
## What's the issue?

I'm getting the following error in the console:

````
 Uncaught TypeError: qb(...).getElementById is not a function
     at ef.f.maybeFindTemplate (base-element.js:290)
     at ef.f.findTemplate (base-element.js:235)
     at ef.f.findAndRenderTemplate (preconnect.js:336)
     at G (amp-date-countdown.js:206)
     at amp-date-countdown.js:176
````

The error increments every second, presumably from the timer callback. 
It doesn't cause any impediment to the user, but unnecessarily uses resources and clutters the console with errors.

## How do we reproduce the issue?

Place an `amp-date-countdown` inside of an `amp-list` and bind the amp-list's `src`. perform any action that changes `state`, and the error will occur. 

#### Sample Code

````
<button on="tap:AMP.setState({newEndpoint: "https://mySite.com/newEndpoint"})">
    Click to trigger error
</button>

<amp-list [src]="newEndpoint"
           src="https://mySite.com/myEndpoint" 
           layout="fixed-height" height="100">
    <template type="amp-mustache">
          <amp-date-countdown
              timestamp-ms="{{timeStamp}}" biggest-unit="hours"
              layout="fixed-height" height="18" 
              template="countdown">
          </amp-date-countdown>
    </template>
</amp-list>

<template id="countdown" type="amp-mustache">
    <b>{{h}}:{{mm}}:{{ss}}</b>
</template>
````
You can trigger the error [here](https://www.bhphotovideo.com/c/product/1274705-REG/canon_eos_5d_mark_iv.html/amp) by scrolling down past the "Ask Our Experts" and tapping one of the available tabs

**Comment by Joelsz** [comment]
+1 This is really filling up the logs
