### ISSUE TITLE
I2I: Support for Content Security Policy with Inabox

### ISSUE THREAD

**Issue by jeffkaufman** [ampproject/amphtml#21681]
## Summary

The AMP validation process should allow us to trust that AMP creatives are restricted in what they can do, but it would be good to also enlist the browser in this protection.  We should publish a Content Security Policy that we will support for AMP creatives.

## Motivation

While validation should keep an AMP creative from including custom JS or other things the spec disallows, as a defense in depth we should allow including a Content Security Policy.  This policy would help protect against bugs in the AMP runtime or validator, and somewhat limit risks of, for example, rendering AMP creatives same-domain to the publisher page.

## Implementation

We propose the following CSP:

    script-src https://cdn.ampproject.org/;
    object-src 'none';
    child-src blob:;
    frame-src 'none'

This limits scripts to the AMP CDN, disallows plugins, disallows nested iframes, and only allows workers if they're loaded from `blob:` urls.  Aside from the amp-youtube element, which we're proposing disallowing (#21340), we believe this is sufficient to allow everything the AMP4ADS spec allows.

We've tested this CSP in Google Ad Manager, and it does not seem to harm ads.

Ad networks would be free to choose how to integrate this CSP, or whether to use it at all.  One option would be to add it directly to the creative right before rendering protecting against anything earlier in the process that might have subverted validation.  In Google Ad Manager we've been testing having our client-side JS inject this at the beginning of the `<head>` as a `<meta>` tag:

```
<meta http-equiv=Content-Security-Policy
      content="script-src https://cdn.ampproject.org/;
               object-src 'none';
               child-src blob:;
               frame-src 'none'">
```

## Downsides

The main downside of the AMP project supporting ad networks in applying CSPs is it reduces AMP's flexibility.  If adding a new feature to AMP required loosening one of these directives then there would need to be coordination with the ad networks who had deployed CSPs.

Alternatively, someone might add a new AMP feature that violates the CSP without realizing it.  Once that feature was released, or once ads started using that feature, they might break on networks that enforce the CSP.

One way to mitigate both of these would be to put the CSP directly into the AMP repo.  This would allow ad networks to watch the file for changes (in an automated way) and for AMP to have automated testing that verifies CSP compliance.

/cc @ampproject/wg-approvers

**Comment by jeffkaufman** [comment]
Note that injecting a CSP like this for Firefox doesn't currently work (https://github.com/w3c/webappsec-csp/issues/207, https://wpt.fyi/results/content-security-policy/inheritance/inherited-csp-list-modifications-are-local.html?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned) because Firefox aliases the parent CSP instead of copying it when it makes a same-domain iframe.  In our testing we didn't enable this behavior for Firefox.

**Comment by lannka** [comment]
@jeffkaufman I feel this kind of "defense in depth" should be optional and applied outside AMP. If we're worried about regressions in AMP, we can put this CSP tech into an integration test to safe guard it.

**Comment by lannka** [comment]
Changed to P2 as I do see the necessity to catch issues earlier.

**Comment by jeffkaufman** [comment]
I agree this can be optional for ad networks, and it does need to be applied outside of AMP (as GPT does) in order to have any benefit.  Where AMP comes in is that instead of each ad network trying to maintain their own CSP, and potentially break valid AMP creatives, the CSP to use should be maintained as part of the AMP project.

**Comment by lannka** [comment]
I guess we are on the same page. It does not make too much sense to have the "depend in depth" in AMP validation.

AMP can recommend a CSP rule for any ad network to apply, and maintain integration tests to make sure the CSP rule will not break AMP.

**Comment by jeffkaufman** [comment]
That sounds right to me!  Keeping AMP consistent with the CSP is the important thing.
