### ISSUE TITLE
How to report bugs and or questions

### ISSUE THREAD

**Issue by wordpressnewbie** [ampproject/amphtml#2169]
I nsee that google gives us the option of downloading the results by google docs or CSV, how does the group want things posted with questions by one of these methods or just a link to the page in question?

**Comment by ericlindley-g** [comment]
Hi—if this is related to issues you are seeing reported in the Search Console, you can get help via the [Webmaster Central Help Forum](https://productforums.google.com/forum/#!topicsearchin/webmasters/category$3Aaccelerated-mobile-pages-amp%7Csort:relevance%7Cspell:false).
