### ISSUE TITLE
amp-accordion: images distorted when animate attribute added

### ISSUE THREAD

**Issue by ChrisThorn10** [ampproject/amphtml#21699]
## What's the issue?
When the animate attribute is added to amp-accordion, the image contained as the second child within a section is distorted; the width becomes 100% of the accordion container. 

##Briefly describe the bug.
Fixed layout images display properly within an accordion (the second child within a section) until the animate attribute is added to amp-accordion.  Once this happens, the image width automatically becomes 100% of the accordion container, distorting the image.

## How do we reproduce the issue?
https://jsbin.com/caregok/edit?html,output

1. Expand the accordion to see the image display properly
2. Add the animate attribute to the amp-accordion tag
3. Expand the accordion once more to see the image display with distortion

## What browsers are affected?
I only checked the below three browsers/devices
Chrome Version 72.0.3626.121 (Official Build) (64-bit) on Mac
Firefox 65.0.1 (64-bit) on Mac
iPhone 8+ on Safari

## Which AMP version is affected?
<html ⚡4email> 
I noticed this issue when I was playing around in Gmail AMP for Email Playground https://amp.gmail.dev/playground/

## Image for Reference
<img width="486" alt="Screen Shot 2019-04-03 at 11 59 47 AM" src="https://user-images.githubusercontent.com/29307794/55494057-109d9280-5608-11e9-908a-775d794faaba.png">

**Comment by aghassemi** [comment]
Thanks for the report @ChrisThorn10.

Sounds like the same issue as https://github.com/ampproject/amphtml/issues/20272 which as it seems is not fully resolved.

/to @sparhami
