### ISSUE TITLE
AMP Install Service Worker does not seems to trigger data-iframe-src from AMP cache

### ISSUE THREAD

**Issue by jviviajala** [ampproject/amphtml#21708]
Hi,

I am trying to make the amp-install-service-worker component works, it's working well from the amp URL but not from the Google AMP Cache.

I confirm I set up both src and data-iframe-src attributes but it does not work, I have the following error message : Did not install ServiceWorker because it does not match the current origin

The steps to reproduce is very easy, I just created 2 virtual host in local and set up the following amp-install-service-worker piece of code : 

```
<amp-install-serviceworker
          src="https://www.domain1.com/sw.js"
          data-iframe-src="https://www.domain2.com/sw.html"
          layout="nodisplay">
  </amp-install-serviceworker>
```
Then just load the page entering the www.domain2.com

Thanks for your help!

Julien

**Comment by torch2424** [comment]
Triaging to @prateekbh , Feel free to re-assign 😄 

cc @jridgewell while @prateekbh is out. 👍

**Comment by jridgewell** [comment]
The iframe url should be on the same domain as the AMP document. You can't use cross origin service-workers, so their would be little point in AMP loading an iframe that's cross domain for you to do it.
