### ISSUE TITLE
Uncaught TypeError: window.jwplayer is not a function

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#21704]
## What's the issue?
`Uncaught TypeError: window.jwplayer is not a function`

Briefly describe the bug.
Error message saying jwplayer is not a function
## How do we reproduce the issue?

1. Open https://www.google.com/amp/s/warriorswire.usatoday.com/2018/03/16/kevin-durant-fractured-ribs-injury-two-weeks/amp/
2. Open developer tools and see error in console

## What browsers are affected?

macOSX Chrome Version 73.0.3683.86 (Official Build) (64-bit)
macOSX Safari Version 12.0.3 (14606.4.5)
macOSX FireFox Version 66.0.2 (64-bit)

## Which AMP version is affected?
Dev Channel: Version 1904021746450
Stable Channel: Version 1903281741200

![Screen Shot 2019-04-03 at 11 04 42 AM](https://user-images.githubusercontent.com/48487406/55502463-74708d00-5601-11e9-9576-0180bbba3263.png)

**Comment by alanorozco** [comment]
Not an AMP error.
