### ISSUE TITLE
[Master feature] Support live AMP Stories

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#21714]
Enable the creation of live stories. Users will be able view stories that are updated in real-time as the publisher adds new pages to it - without the need of having the user refresh the page. Think live blogging.

This will unblock use cases like: 
* Live sport match reporting (updated scores, commentaries, etc..)
* Live news coverage 
* Live keynote updates (e.g. reporter using AMP Stories in keynote event)

We’ll use the [amp-live-list](https://www.ampproject.org/docs/reference/components/amp-live-list) functionality to make real-time updates to the DOM. Whenever a new page is detected in the source document, we’ll update the client to reflect the changes. These include a UI treatment and internally letting amp-story know that there is a new page.

This master issue will keep track of the subtasks needed to support this feature.

<table>
  <tr>
    <td colspan="4">
      <h2>Subtasks</h2>
    </td>
  </tr>
  <tr>
    <td><h3>Title</h3></td> 
    <td><h3>Description</h3></td> 
    <td><h3>Status</h3></td> 
    <td><h3>Github Issue</h3></td> 
  </tr>
  <tr>
    <td>Modify `amp-live-list` to support dynamically added lists and add configuration options</td> 
    <td>We will need this to specify `amp-story` as the new container for dynamic elements, see issue for more details</td> 
    <td>DONE</td> 
    <td>#21718</td> 
  </tr>
  <tr>
    <td>Listen to updates at the `amp-story` level </td> 
    <td>We will need to listen to the `AmpLiveList#update` method, and take the necessary actions when that happens (i.e. show system button UI, insert page in DOM, update progress bar, etc...)</td> 
    <td>DONE</td> 
    <td>#21719</td> 
  </tr>
  <tr>
    <td>Show system UI</td> 
    <td>Show a UI treatment when there is a new update in the story.</td> 
    <td>DONE</td> 
    <td>#21721 #22700</td> 
  </tr>
  <tr>
    <td>Update `amp-story` progress bar</td> 
    <td>Whenever a new page is added to the story, we will need to update the progress bar to reflect that. Our current implementation only builds the progress bar at `AmpStory#layoutCallback`</td> 
    <td>DONE</td> 
    <td>#21722</td> 
  </tr>
  <tr>
    <td>Pre-launch testing</td> 
    <td>Sanity checking and adding more tests</td> 
    <td>DONE</td> 
  </tr>
  <tr>
    <td>Launch</td> 
    <td>Enable validation & submit documentation</td> 
    <td>IN PROGRESS</td> 
    <td></td> 
  </tr>
</table>

**Comment by siddiqrahman** [comment]
@Enriqe is it working amp-live-list in amp story?

**Comment by Enriqe** [comment]
Hi @siddiqrahman, this feature is still in development but you can follow the progress in this issue 👍

**Comment by ithinkihaveacat** [comment]
FYI there are some issues with amp-live-list getting timely update on some caches, see e.g. the Google internal b/124009333.

**Comment by Enriqe** [comment]
Thanks for the heads up @ithinkihaveacat 👍

**Comment by Enriqe** [comment]
Main tasks are now done. Performing sanity checking & closing open discussions. Launching process will follow soon after this.

**Comment by Enriqe** [comment]
Note there is a problem with amp-live-list getting timely updates in the amp cache. #13659

/cc @newmuis
