### ISSUE TITLE
MAX_FREE_MUTATION_HEIGHT in amp-script is too low

### ISSUE THREAD

**Issue by patrickkettner** [ampproject/amphtml#21715]
## What's the issue?

The [current value of 300px](https://github.com/ampproject/amphtml/blob/9d6477b4b638f96c52453d7c19492b693e561bdb/extensions/amp-script/0.1/amp-script.js#L43) is too low to be actually useful 

## How do we reproduce the issue?

create an amp-script with a fixed height of > 300px

## Which AMP version is affected?

master

**Comment by torch2424** [comment]
Triaging to @kristoferbaxter , Feel free to re-assign 😄

**Comment by choumx** [comment]
Do you have a specific use case in mind? Note that the 300px height only applies to `layout=container` amp-script elements.

**Comment by choumx** [comment]
@patrickkettner Closing for now, please give more detail and I'll reopen.

**Comment by patrickkettner** [comment]
@choumx sorry, didn't realize that question was to me. @kristoferbaxter asked me to open the issue over chat when I mentioned that it existed
