### ISSUE TITLE
amp-video on:tap action does not work as expected

### ISSUE THREAD

**Issue by mcrump001** [ampproject/amphtml#21712]
## What's the issue?
The amp-video on:tap action does not work as expected - target action on target element does not fire

Briefly describe the bug.
An amp-video element having the on="tap..." action attribute set does not perform the target action on the target element when "tapped/clicked" when on an IOS or Android device or when tested in the device emulator on chrome dev tools.

## How do we reproduce the issue?

1. Create a simple amp-video tag and set the on="tap:target-id.hide" attribute.
1. Create target div having id="target-id".
1. Open file in Chrome browser dev tools set to Iphone or galaxy emulator mode
1. Click on video element.
    1. Expected:  Video to play and target div to hide
    1. Actual: Video plays and target div remains visible

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. Browse to - https://stage-mdev-wbns.pantheonsite.io/sites/default/files/amp-video-test.html using Chrome browser , ios, or android device
1. If using Chrome browser enable dev tools device emulation
1. Click on video player
1. Observe video plays but "Caption div" does not hide as expected

## What browsers are affected?
Chrome dev tools using device emulator
IOS devices
Android devices

## Which AMP version is affected?
Version 1903281741200

Probably always broken

**Comment by torch2424** [comment]
Triaging to @alanorozco , Feel free to re-assign 😄

**Comment by alanorozco** [comment]
👋

This is the browser's native behavior. Since video renders controls, it wouldn't really make sense to capture tap events on it directly.

If you'd like to implement click-to-play, please refer to [this example.](https://amp.dev/documentation/examples/multimedia-animations/click-to-play_overlay_for_amp-video/?referrer=ampbyexample.com)
