### ISSUE TITLE
Remove G+ from documentation of amp-social-share

### ISSUE THREAD

**Issue by bjalford** [ampproject/amphtml#21743]
Should the G+ option now be removed from the amp-social-share documentation since G+ close?

https://www.ampproject.org/docs/reference/components/amp-social-share

**Comment by torch2424** [comment]
Triaging to @aghassemi , Feel free to re-assign 😄

**Comment by DrewRoberts** [comment]
Good suggestion, @bjalford. I'll take a stab at it. I also opened an issue for the Docs repo:

https://github.com/ampproject/docs/issues/1894

**Comment by JoseSoteloCohen** [comment]
Hello, would love to take on this task as my first contribution. May I?

**Comment by aghassemi** [comment]
There is a PR open for this by @drewroberts  ( https://github.com/ampproject/amphtml/pull/21858 ) but needs some changes. @drewroberts are you planning to continue that PR? (see review comments)

**Comment by drewroberts** [comment]
Sure, I'm available to work on it and appreciate the opportunity to contribute to AMP. I'm not sure how to do the `user().warn` for Google+ in the config. @JoseSoteloCohen are you comfortable making that additional change?

**Comment by drewroberts** [comment]
@cramforce Thank you for your help.

Don't forget me in the new world order:

<img width="524" src="https://user-images.githubusercontent.com/24581081/62504390-4032f600-b7c6-11e9-9faf-abf6df072098.png">
