### ISSUE TITLE
FR:  Ability to cancel `AMP. scrollTo()`

### ISSUE THREAD

**Issue by popovvb** [ampproject/amphtml#21754]
I make a smooth scrolling page for reading.
`<div class="prokr" role="button" on="tap:fbcom.scrollTo(duration=50000)" ></div>`
How to stop scrollTo ???

**Comment by aghassemi** [comment]
That's currently not possible.

**Comment by popovvb** [comment]
Tell me, maybe through something else you can implement a smooth scrolling with the ability to stop?

**Comment by caroqliu** [comment]
Can you help us better understand why/when you want to stop scrolling?

**Comment by popovvb** [comment]
I needed a smooth scroll, with the ability to stop and up/slow, for the site of songs with chords. In the regular version, it is implemented, for example: https://uchords.net/en/song/tones_and_i_dance_monkey/2877.html I did not implement it in the AMP version, so i abandoned the AMP pages.

**Comment by caroqliu** [comment]
Thank you for clarifying.
