### ISSUE TITLE
__amp_source_origin not correct

### ISSUE THREAD

**Issue by lsarni** [ampproject/amphtml#21759]
## What's the issue?

I have multiple `amp-list` on my page and I'm getting this error when accessing the page from Google at https://www.google.com/amp/s/www.chefsfeed.com/amp/experts/740-evan-rich:

> Access to fetch at 'https://www.chefsfeed.com/amp/experts/740-evan-rich/more_owned_dishes?__amp_source_origin=https%3A%2F%2Fwww.chefsfeed.com' from origin 'https://www-chefsfeed-com.cdn.ampproject.org' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://www.chefsfeed.com' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

This are the request headers:
![Screen Shot 2019-04-08 at 11 05 00](https://user-images.githubusercontent.com/15196342/55730533-cf81f580-59ee-11e9-9ac2-e62682532b1f.png)

And this the response headers:
![Screen Shot 2019-04-08 at 11 05 18](https://user-images.githubusercontent.com/15196342/55730536-d4df4000-59ee-11e9-8320-a26bcea96015.png)

I understand what the error is, but I believe the value of `__amp_source_origin` isn't correct. It should be https://www-chefsfeed-com.cdn.ampproject.org

When I get a request I'm setting up the following headers to the response:
```
response.headers['Access-Control-Allow-Origin'] = params[:__amp_source_origin]
response.headers['AMP-Access-Control-Allow-Source-Origin'] = params[:__amp_source_origin]
response.headers['Access-Control-Expose-Headers'] = 'AMP-Access-Control-Allow-Source-Origin'
```
This was working just fine since October '18, I'm not sure when it started failing but it was just reported to me.

Did something change on how `__amp_source_origin` works? Or is this an error?

## How do we reproduce the issue?

1. Go to https://www.google.com/amp/s/www.chefsfeed.com/amp/experts/740-evan-rich
2. You should see some headers like "Featured content" and nothing under them.
3. On inspect you should be able to see the errors.

## What browsers are affected?
Tested on Chrome on Android and Safari and Chrome on iOS.

## Which AMP version is affected?
I don't know in which version I started seeing this error, but the current version is 1903281741200 and this pages had been working without any change since October '18.

**Comment by jridgewell** [comment]
`response.headers['Access-Control-Allow-Origin'] = params[:__amp_source_origin]` is incorrect. You want to return the origin of the requesting page (`https://www-chefsfeed-com.cdn.ampproject.org`), not the source origin of the AMP document (`www.chefsfeed.com`).
