### ISSUE TITLE
Responsive is not working on AMP4EMAIL (AMP Email)

### ISSUE THREAD

**Issue by rintish** [ampproject/amphtml#21753]
Hi,

I am trying to make the responsive AMP4EMAIL (AMP Email) email template but it's not working properly without the  `<meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">` 

If we add the `<meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">` tag in the AMP Email it show the error like: 

> The attribute 'name' in tag 'meta name= and content=' is set to the invalid value 'viewport'.

Here is the AMP-Email code example:

`<!doctype html>`
`<html ⚡4email>`
    `    <head>`
`<meta charset="utf-8">`
`<script async src="https://cdn.ampproject.org/v0.js"></script>`
`<!-- If we add the viewport tags AMP-EMAIL is FAIL  in the playground/validator -->`
`<!-- <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1"> -->`
`<style amp4email-boilerplate>body{visibility:hidden}</style>`
`<style amp-custom>`
`.colored { color: blue; }`
`.body { font-size: 14px; }`
`@media screen and (max-width: 500px) {`
`.colored { color:red; }`
`}`
`</style>`
`</head>`
`<body>`
`<div class="body">`
`<p>Hello, AMP4EMAIL World.</p>`
`<p class="colored">`
`This text is blue when window width greater than 500px, otherwise is red.`
`</p>`
`<p>Rintish</p>`
`</div>`
`</body>`
`</html>`

Thanks for your help!
Rintish.

**Comment by avcohen** [comment]
@rintish Did you find a workaround for this? I have a project fully built for desktop and without device width scaling my content doesn't behave correctly according to their respective media queries...
