### ISSUE TITLE
AMP Date Display: cannot be used in amp-list

### ISSUE THREAD

**Issue by fbroersen** [ampproject/amphtml#21758]
## What's the issue?

Our backend produces a JSON that needs to be localized in the frontend. Using the `<amp-date-display>` is not possible due to the limitation of putting the `<amp-mustache>` of the `<amp-date-display>` inside the `<amp-mustache>` of the `<amp-list>`.

It works, but does not validate (and thus not cache).

## Suggested fix:
- Allow nested template of `<amp-date-picker>` inside `<amp-list>`
- Allow external template in the amp-date-display component, e.g. `<amp-date-display template='myTemplate'>`
- Add the amp-date-display functionality inside the `<amp-list>` component, e.g. `<amp-list use='amp-date-display'>`

## How do we reproduce the issue?

Sample url:
https://tryamp.msiteproject.com/tiqets/

JSON:
```
{
      "body": "Perfect. I has worked as it was promised.",
      "country": "Brazil",
      "cs_reply": null,
      "date": "2019-04-05",
      "id": 549739,
      "productpage_title": "Vatican Museums & Sistine Chapel: Skip The Line",
      "rating": 5.0,
      "reviewer": "Jose"
    },
```

HTML:
```
<amp-list layout="responsive" width="450" height="1400" src="reviews.json" items="reviews" single-item>
<template type="amp-mustache" >
...
<amp-date-display class="c4" datetime="{{date}}" layout="fixed-height" height="20">
<template type="amp-mustache">
<div class="c4">{{monthNameShort}} {{day}}, {{year}}</div>
</template>
</amp-date-display>
...
```

## What browsers are affected?

All

## Which AMP version is affected?

All

**Comment by aghassemi** [comment]
Hi @fbroersen 

We do support nested templates but the syntax is a bit different:
You can use `<script type=text/html type=amp-mustache>` instead of `<template>` for the nested case.

Please see https://github.com/ampproject/amphtml/blob/84bf6f3203fd7a0a27349a18a560761ae4490320/extensions/amp-mustache/amp-mustache.md#usage for more details.
