### ISSUE TITLE
amp-bind for updating amp-audio attributes

### ISSUE THREAD

**Issue by bomjastik** [ampproject/amphtml#21760]
Given we have an amp-audio player on the page. Then we get some data from the server using amp-state. How can I update amp-audio with the new data? 

I have tried to do it in "amp-bind" way:
```
<amp-audio [src]="station.src"
           [artwork]="station.artwork"
           [title]="station.title"
           [album]="station.album"
           [artist]="artist.artist"
           height="50"
           width="auto"
           controlsList="nodownload">
    <div fallback>Your browser doesn’t support HTML5 audio</div>
</amp-audio>
```
but I've got errors:

![amp-audio](https://user-images.githubusercontent.com/1671780/55742360-2829b080-5a38-11e9-93ec-ba6a4a5933f3.jpg)

@sbenz

**Comment by aghassemi** [comment]
Thanks @bomjastik, `amp-bind` does not support everything by default, we add support for it on-demand in a lot of case.

This is fairly straightforward to add if it is something you are interested in contributing. https://bit.ly/helpamp

**Comment by lxsedov** [comment]
would be super useful to provide access to audio content with a signed url
