### ISSUE TITLE
I2I: ✨ Add Vpon Analytics to AMP analytics vendors

### ISSUE THREAD

**Issue by vpon-sdk** [ampproject/amphtml#21769]
✨ Add [Vpon Analytics](https://www.vpon.com/) to AMP analytics vendors

**Comment by torch2424** [comment]
Thank you for the I2I, when you create your PR, feel free to mention me once it is created. Thank you! 😄

**Comment by vpon-sdk** [comment]
Hello~@torch2424 :
How can I to solve this problem? (about percy/amphtml)
Would you mind giving me a hand?
https://github.com/ampproject/amphtml/pull/21837

**Comment by torch2424** [comment]
This was merged. Closing 😄
