### ISSUE TITLE
[AMP-IMG] If parent is Position:Fixed / TranslateX -100% = IMG not loaded

### ISSUE THREAD

**Issue by Sylgrid** [ampproject/amphtml#21773]
## What's the issue?

When an AMP-IMG is inside a contener in a fixed position and outside the screen (`TranslateX = -100%`), the Image is not loaded. With `TranslateY`, the image is loaded.

If we check the Chrome Console / Network Tab, we can see that the img URL is not called.

## How do we reproduce the issue?

Demonstration :

- [CodePen example](https://codepen.io/anon/pen/oOBzBa)

Check the input Checkbox so the Contener slide in view.

Here is the code :

```
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <title>My AMP Page</title>
  <link rel="canonical" href="self.html" />
  <meta name="viewport" content="width=device-width,minimum-scale=1">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <style amp-custom>
    h1 {
      margin: 1rem;
    }
    .contener{ position: fixed; top: 20px; left: 0; right: 0; bottom: 0; height: 100vh; background: black; transition: transform 0.8s linear; transform: translateX(-100%); }
    input:checked ~ .contener{ transform: translateX(0%); }
  </style>
</head>
<body>
  <input type="checkbox" />
  <div class="contener">
    <amp-img src="http://lorempixel.com/400/200/" width="400" height="200" layout="fixed" alt="Recherche" noloading></amp-img>
  </div>
</body>
</html>
```

## What browsers are affected?

Seems all browsers. Tested on :

- [MAC] Chrome 73.0.3683.86 (Build officiel) (64 bits)
- [MAC] Firefox 66.0.2 (64 bits)

## Which AMP version is affected?

Actual version.
- Today Date : 09 April 2019 - 15h28

**Comment by jridgewell** [comment]
Hi @Sylgrid,

Thanks for the report and the code demo! We're aware of this issue, and the tracking bug is https://github.com/ampproject/amphtml/issues/17452. In general, AMP does not have a good understanding of elements that are offscreen and move without explicit control by the runtime.

**Comment by Sylgrid** [comment]
Hi @jridgewell
Thank you Justin.

I had guessed the problem origin (runtime mechanic) but I was skeptical because everything is ok with `TranslateY` while the element is offscreen too. :)
Good luck.
