### ISSUE TITLE
Improve cache documentation for config.js e.g. isProxyOrigin() 

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amphtml#21776]
[`isProxyOrigin()`](https://github.com/ampproject/amphtml/blob/4721b11f23920917d7b2eb83991e23a94cfcb724/src/url.js#L371) relies the regular expression `/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/` ([source](https://github.com/ampproject/amphtml/blob/84a002d004fdefa3eae85ef8e8647b9f7abfc472/src/config.js#L41)) to determine whether a page is being viewed on a CDN or not. This regexp matches only one of the three caches currently listed in <https://cdn.ampproject.org/caches.json>.

It seems like these definitions should be synchronized to ensure components that rely on this function (such as `<amp-access>` and `<amp-install-serviceworker>`) behave correctly.

**Comment by jridgewell** [comment]
This is correct. Other caches are not intended to use the exact same JS as the Google AMP Cache uses. Part of the cache transformations is to change `https://cdn.ampproject.org/v0.js` to the Cache specific JS file (eg, `https://www.bing-amp.com/v0.js`). These custom JS are allowed to use their own URL configurations.

This was recently discussed in #21703. We need better documentation around this.

**Comment by ithinkihaveacat** [comment]
Aha! Yes [amp-cache-guidelines.md](https://github.com/ampproject/amphtml/blob/master/spec/amp-cache-guidelines.md) is probably a good place to explain how to do this? It would also be helpful to add a comment against that particular regexp in `config.js`.

**Comment by jridgewell** [comment]
I think so.

**Comment by Gregable** [comment]
Closing as I don't know of any active development of new amp caches.
