### ISSUE TITLE
Change <option> "selected" when a second <select> element is changed.

### ISSUE THREAD

**Issue by IamAlta** [ampproject/amphtml#21785]
## Describe the new feature or change to an existing feature you'd like to see
I have two "select" elements. When one is changed, I'd like the other to change.

The user should be able to change the second "select" element, but the Destination State "initializes" to the Billing State _when that is selected (of course, when the page loads, the Destination is set to to "Select the State").

I can't find anything for [selected] to remove the selection. Instead, they are all selected (I understand that you must remove the "selected" for it to be deselected.). Using [text] doesn't work because it places the text as the option visible text.

E.g., When the Billing State changes, I'd like the Destination State to change to be the same selection. See here [https://codepen.io/iamalta/pen/QPdOYL](https://codepen.io/iamalta/pen/QPdOYL)

    <label for "state">Billing State</label><br>
    <select name="state" id="state" required on="input-debounced:AMP.setState({billstate: event.value })">
        <option value="" disabled selected>Select the State</option>
        <option value="APO-AP">APO</option>
        <option value="FPO">FPO</option>
        <option value="AK">Alaska</option>
        <option value="AL">Alabama</option>
    </select>
    <br><br>
    <label for "sstate">Destination State</label><br>
    <select name="sstate" id="sstate" required >
        <option value="" disabled selected>Select the State</option>
        <option value="APO-AP" [selected]="billstate=='APO-AP' ? 'selected' : ''">APO</option>
        <option value="FPO" [selected]="billstate=='FPO' ? 'selected' : ''">FPO</option>
        <option value="AK" [selected]="billstate=='AK' ? 'selected' : ''">Alaska</option>
        <option value="AL" [selected]="billstate=='AL' ? 'selected' : ''">Alabama</option>
    </select>

**Comment by aghassemi** [comment]
Hi @IamAlta 

For "boolean" type attributes like `selected`, the `bind` expression needs to also be `boolean`.
So switching from `billstate=='APO-AP' ? 'selected' : ''` to just `billstate=='APO-AP'` will solve it.

Here is an example that seems to be working (I also changed the event from `input-debounce` to  `change` since that's more semantic)

https://codepen.io/aghassemi/pen/ROKxrE

**Comment by aghassemi** [comment]
Closing per comment above, please reopen if needed.
