### ISSUE TITLE
Broken link (404) in documentation

### ISSUE THREAD

**Issue by mdiblasio** [ampproject/amphtml#21780]
The "Google AMP Client ID API documentation" link in [this article](https://github.com/google/amp-client-id-library) returns a 404.

**Comment by torch2424** [comment]
Triaging to @calebcordry , feel free to re-assign 😄 

cc @lannka @jeffjose

**Comment by zhouyx** [comment]
@jeffjose Could you please link to the corresponding document? Thank you
