### ISSUE TITLE
Refactor the Timer class to use a custom key type instead of `number`

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#21804]
This came out of the discussion at https://github.com/ampproject/amphtml/pull/21618#discussion_r270519325

We currently use `number` as the default type in the `Timer` class. We should use a custom key type instead, that will make typecasts elsewhere in the code either unnecessary, or less ambiguous.

https://github.com/ampproject/amphtml/blob/a352b31ab681c723819bb793853d156074bfd602/src/service/timer-impl.js#L67
https://github.com/ampproject/amphtml/blob/a352b31ab681c723819bb793853d156074bfd602/src/service/timer-impl.js#L96

**Comment by choumx** [comment]
I assume this was @jridgewell's suggestion.
