### ISSUE TITLE
Form Submission issues with 406 error

### ISSUE THREAD

**Issue by Narendharr** [ampproject/amphtml#21817]
## What's the issue?

Form Submission issues with 406 error.

I build AMP pages for my clients. The forms used to work before with same code without any errors. I get the same errors on all the websites I built previously. All forms are not working now and getting the same error.

![image](https://user-images.githubusercontent.com/9212952/55932090-c048b500-5c45-11e9-8029-4705ff5cc20d.png)

All of sudden I am getting following errors. 

**1. 406 error
2. Response must contain the AMP-Access-Control-Allow-Source-Origin header
3. Form submission failed: Error: Response must contain the AMP-Access-Control-Allow-Source-Origin header​​​**

AMP-Access-Control-Allow-Source-Origin header code already present in my code 

I tried with header("Access-Control-Allow-Origin: https://www.narendesigns-com.cdn.ampproject.org"); too.

![image](https://user-images.githubusercontent.com/9212952/55932125-eb330900-5c45-11e9-9f6a-7101df9d24f4.png)

## How do we reproduce the issue?

Below are the links to check the form issues.

https://www.narendesigns.com/projects/html/beauty-cafe/contact-us.php

https://www.filingbankruptcymemphis.com/

https://www.narendesigns.com/projects/html/ashwani/#contact

1. Fill the Form
2. Check the Console Errors

## What browsers are affected?

The errors are there on all browsers. I checked on Mozilla, Chrome and Mircosft Edge browsers

![image](https://user-images.githubusercontent.com/9212952/55932368-02bec180-5c47-11e9-85de-0e4a1383b293.png)

![image](https://user-images.githubusercontent.com/9212952/55932090-c048b500-5c45-11e9-8029-4705ff5cc20d.png)

## Which AMP version is affected?

This is a new issue.

Any help can be appreciated.

Thank you in advance.

Regards,
Narendharr

**Comment by choumx** [comment]
I think HTTP 406 indicates an issue with server configuration with respect to `Accept-*` headers. I don't believe this is AMP related.

/cc @cvializ
