### ISSUE TITLE
valueMissing error triggered on select field set via amp-bind/amp-state

### ISSUE THREAD

**Issue by shishirm** [ampproject/amphtml#21816]
## What's the issue?

I am using amp-state and amp-bind to pre-set values on linked select type dropdowns. While I am able to set the fields as expected, it automatically triggers a valueMissing error and then any manual selection of drop downs does not cause the errors to disappear.

## How do we reproduce the issue?

https://hissing-direction.glitch.me/#development=1

Clicking on the button causes the various select fields to get set but also triggers the valueMissing error validation.

## What browsers are affected?

All browsers, all device types

## Which AMP version is affected?

This is always broken.

The AMP version I am working with is: 1904021746450

**Comment by torch2424** [comment]
Triaging to @choumx , Feel free to re-assign 😄

**Comment by shishirm** [comment]
Updating with the latest. 

https://spicy-need.glitch.me/

In the latest updates to the page, there is a specific usecase where we cannot get the error messages to disappear. To reproduce,

1. Click on "Change Program"
2. Change first dropdown to anything else, say "Criminal Justice"
3. Click "Get Info" button at the bottom of the form. This will cause the invalidation errors to pop up
4. Now select an Academic Level, say "Associate". This will cause the "Please Select an Academic Level" to disappear.
5. Next select a Degree, say "AS Criminal Justice". The error / invalid message remains even though the right class i.e. _class="user-valid valid_

Now if I were to re-select "Select A Degree" from the dropdown and then re-select "AS Criminal Justice", the error goes away.

We suspect this is happening because the event listener inside the template is getting erased when the parent dropdown drives this dropdown being set, but the parent should ensure that the value missing span is also added back in.

Any help here would be greatly appreciated!

**Comment by choumx** [comment]
Sorry for the delay, we've been busy at the annual AMP Conference. 

Looks like this is an issue with custom validation caching when the element being validated is re-rendered via amp-list. The validation element can't be found as a property on the element if the elemnt itself has changed: https://github.com/ampproject/amphtml/blob/23485bf351346743b526c74622004d77e7215860/extensions/amp-form/0.1/form-validators.js#L349-L350

/to @vializ

**Comment by shishirm** [comment]
Hello. Is there an ETA on this fix?

**Comment by nainar** [comment]
Hi @cvializ how often are we expecting this error to trigger? I want to dig into the prioritization for this issue.

**Comment by cvializ** [comment]
This is a bug and is not expected to trigger with normal usage in a valid AMP, so it should be fixed. Is there anything specific information you were looking for to assess priority @nainar? Feel free to ping me

As a workaround while we fix this, consider disabling HTML validation for the bound `<select>` and responding with a server error on form submit if the value is missing.
