### ISSUE TITLE
I am making AMP live blogs but they are not appearing anywhere in search.

### ISSUE THREAD

**Issue by vaibhav-readwhere** [ampproject/amphtml#21820]
I have started making AMP Liveblogs for events my team cover i.e cricket or football matches. Everything is according to amp requirements but they are not showing up in search. Please help.

My liveblog sample page url - https://live.indiatvnews.com/article/news-detail/195_10464869/liveblog/amp

Please help.

**Comment by choumx** [comment]
Unfortunately we can't give guidance on SEO-related issues. I'd double-check your page against public documentation for AMP in Google Search e.g. https://developers.google.com/search/docs/guides/about-amp

Good luck!
