### ISSUE TITLE
Can AdSense Direct tags be implemented for AMP Ads?  How about Custom JS tags?

### ISSUE THREAD

**Issue by Beach808** [ampproject/amphtml#2184]

**Comment by cramforce** [comment]
AdSense: yes: https://github.com/ampproject/amphtml/blob/master/ads/adsense.md

No custom JS is allowed inside AMP docs. For ads you can do more advanced things using https://github.com/ampproject/amphtml/blob/master/builtins/amp-ad.md#running-ads-from-a-custom-domain

**Comment by michaelkleber** [comment]
As @cramforce says, an <amp-ad> tag does not allow any way for a publisher to provide custom javascript to do the ad rendering.  If your AdSense implementation involves google_ad_output=js (as AdSense Direct does), then the standard <amp-ad type="adsense"> tag will not work for you.
