### ISSUE TITLE
amp-audio should support responsive layout

### ISSUE THREAD

**Issue by janrieke** [ampproject/amphtml#2185]
Currently, the amp-audio tag does not allow layout="responsive". This causes the player not to use the full available width, making it look a bit ugly in our layout.

A quick test with the Chrome developer tools shows that manually setting the style of the amp-audio tag to "-amp-layout-responsive" and removing the fixed width attribute works like a charm. So I think this should be easily realizable.

**Comment by cramforce** [comment]
I believe it is the way it is because on iOS you cannot set the dimensions
of the audio tag with any reasonable control.

**Comment by sebastianbenz** [comment]
It's already supported by setting width=auto. See also https://github.com/ampproject/amphtml/issues/2229

**Comment by wojtekmo** [comment]
Hello  Team,
Please remove my input into "amphtml"
Thank you
Wojtek 

    On Tuesday, February 23, 2016 3:04 PM, Sebastian Benz <notifications@github.com> wrote:
 

 It's already supported by setting width=auto. See also #2229—

**Comment by janrieke** [comment]
Great, that all we need!
