### ISSUE TITLE
AMP Cache-Update is failing 

### ISSUE THREAD

**Issue by prash-mi** [ampproject/amphtml#21853]
AMP Cache update is failing with a 403 error, following is the exact error message:

![Screen Shot 2019-04-15 at 16 10 40](https://user-images.githubusercontent.com/11733935/56126739-3b3d0300-5f99-11e9-91b8-378fa9cf29b8.png)

[This](https://mweb--demos-appspot-com.cdn.ampproject.org/update-cache/c/s/mweb-demos.appspot.com/amp-as-pwa/index.html/?amp_action=flush&amp_ts=1555324826&amp_url_signature=Ki6MHJUT1y9FNdk_GvYVBoPc49JihND845L_HqLoWVwMklT16hhWKdtC5gtWJzTJPzC2EwBnttPoekA8D4PqshBAfNQpGq4a6c-KBdfcSHJCtPYxSX7iRKftrm953LKKDlj29boZ2IcOSbd8SNE_545qVDPsSmBH8wPRze03NrO--EsIkfpuXzveOSt14I0NzXrTjnr85_PKKr8BMfwNuYizskvUCdPWiTYIg9S4mStT5G9j_hRW1sdsFBOm5v_iaixxA-__rtdPwDdyFs1uix_lIPPwc_MtYD0UNL7N0xEiY8Cv7VvS9GSxoG6yOMfuO7fTmbNlx_HcqdbsHE568g==) is the sample update-cache URL which I am composing. 

Verification of signature returns `"Verified OK"`

I further checked and found that the public key isn't cached in AMP CDN, this URL gives a 404! https://mweb--demos-appspot-com.cdn.ampproject.org/update-cache/r/s/mweb-demos.appspot.com/.well-known/amphtml/apikey.pub
![Screen Shot 2019-04-15 at 16 16 08](https://user-images.githubusercontent.com/11733935/56127001-d9c96400-5f99-11e9-8d81-e54801bebdab.png)

This could be the reason of 403. The question is that why the [above URL](https://mweb--demos-appspot-com.cdn.ampproject.org/update-cache/r/s/mweb-demos.appspot.com/.well-known/amphtml/apikey.pub) gives a 404, despite the public key being published here: https://mweb-demos.appspot.com/.well-known/amphtml/apikey.pub ?

**Comment by Antoinebr** [comment]
@prash-mi 

on : https://mweb-demos.appspot.com/.well-known/amphtml/apikey.pub 

You key has a ```content-type: text/html``` 

It should be ```content-type: text/plain```

The documentation is not very clear so I took some note during my implementation ( node ) 
https://gist.github.com/Antoinebr/25673fabb11fd18c31cda4e3fbab74c3 

I hope this can help
