### ISSUE TITLE
`installExtensionForDoc` for `amp-mustache` installs v0.1

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#21862]
`amp-auto-stories` uses `installExtensionForDoc` to fetch `amp-mustache` extension.

The problem is, it seems to always fetch `v0.1` of `amp-mustache` which can be an issue if the page already has `amp-mustache v0.2` included as it would result in a `Uncaught (in promise) Error: Duplicate template type: amp-mustache​​​` error.

I think `installExtensionForDoc` should load the same version that is already included in the page and if not included already, it should fetch latest?

this is the root cause of https://github.com/ampproject/amphtml/issues/21861

**Comment by aghassemi** [comment]
(this is not causing any user-visible issue AFAIK and is not a new thing)

**Comment by choumx** [comment]
I wonder why it's trying to install `amp-mustache` when the page already has it (albeit a different version). That's the first thing to fix.

Re: versioning, easiest thing might be to make the version parameter required:

```js
installExtensionForDoc(ampdoc, extensionId, opt_extensionVersion) {
  ...
}
```

Then each extension should call this with the latest version.

**Comment by aghassemi** [comment]
@calebcordry 
My understanding is that story auto ads is a templated ad and does not require parent to include amp-mustache to work, but parent may include amp-mustache for other reasons.

**Comment by calebcordry** [comment]
@aghassemi That is correct. It looks like `installExtensionForDoc` is smart enough not to load the same extension twice if they are the same version, so everything worked as intended before the launch of V0.2. 

Separately, would it make sense to switch story ads to always use v0.2? (We would still need to solve this problem in case parent page has v0.1)

**Comment by choumx** [comment]
Related: #12429

**Comment by rcebulko** [comment]
Bumping this thread, as https://github.com/ampproject/amphtml/issues/21861 is still one of the top reported errors
