### ISSUE TITLE
responsive amp-ad tag

### ISSUE THREAD

**Issue by bobaaaaa** [ampproject/amphtml#2188]
At the moment the `amp-ad` tag is not responsive with fixed `width` and `height` attributes. Are there any solutions for this issue? Something line the Taboola integration would be nice:

```
<amp-embed width=100 height=283
             type=taboola
             layout=responsive
             heights="(min-width:1907px) 39%, (min-width:1200px) 46%, (min-width:780px) 64%, (min-width:480px) 98%, (min-width:460px) 167%, 196%"
             data-publisher="amp-demo"
             data-mode="thumbnails-a"
             data-placement="Ads Example"
             data-article="auto">
  </amp-embed>
```

**Comment by cramforce** [comment]
Everything that works on `amp-embed` also works on `amp-ad`. Of course, the creative needs to support being responsive. If you see it not working, it is most likely the creative's fault.
