### ISSUE TITLE
FR: add a way to hide an element once it looses focus

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#21888]
This is a use case I've encountered multiple times for menus and tooltips. Clicking on a button should show the element, but clicking anywhere outside the element should hide it again. 

For example, take the menu that appears when you click on the Github profile icon in the top right icon (on desktop):

* it opens when the icon is clicked
* it closes when clicking anywhere outside the menu
* clicking inside the menu doesn't close it (unless it's a button)

There's no straightforward way to implement this in AMP. ([Here's](https://jsbin.com/buhohupasu/1/edit?html,output) a working version using the show/hide actions. But it has two shortcomings:

1. an always active `on=tap:menu.hide` action on the body element.
2. an `on=tap:menu.show` action on the menu action avoiding that it closes when the use clicks inside the menu.

Proposal: a new action `showOnFocus` (not sure about the name), which will show an element, but will automatically hide it, when the user clicks outside the element's boundaries. 

//cc @aghassemi @kristoferbaxter

**Comment by sebastianbenz** [comment]
Update: [here is a slightly better solution](https://jsbin.com/jezemuguna/1/edit?html,output) which doesn't require adding a tap handler to `body`. There are still downsides:

* complicated
* requires amp-bind
* accessibility not ideal as there are three elements with `role=button` and redundant functionality.

**Comment by aghassemi** [comment]
@sebastianbenz is your use-case primarily `tooltip`? I do think we need a dedicated `tooltip` component in `AMP`

**Comment by aghassemi** [comment]
related: https://github.com/ampproject/amphtml/issues/8366 : Maybe a more generalized `amp-overlay` in addition to a high-level `amp-tooltip` is needed.

**Comment by sebastianbenz** [comment]
My primary use case was a menu (similar to the GitHub profile menu on desktop). My first idea was also to propose a component for this, but it feels too heavy for what's needed. That's why I proposed an action instead.

Tooltip has additional challenges (e.g. tooltip placement if the trigger is close the border of a page).
