### ISSUE TITLE
cdnjs cloudflare font awesome not supported in AMP

### ISSUE THREAD

**Issue by rohitkashyap8756** [ampproject/amphtml#21899]
I am trying to include cdnjs cloudflare font awesome in AMP using font face but it is not working and showing error
https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css

**Comment by aghassemi** [comment]
@rohitkashyap8756 Only certain font repositories are whitelisted to be used in AMP. FontAwesome is in the list, however only these CDNs: `https://maxcdn.bootstrapcdn.com, https://use.fontawesome.com`

More info here
https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/custom_fonts
