### ISSUE TITLE
Warnings and flakes in gulp visual-diff

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#21896]
Sample warning:
```
[01:10:31] WARNING: Error in test AMP Article 
   The browser test runner failed to complete the navigation to the test page 
   { TimeoutError: Navigation Timeout Exceeded: 3000ms exceeded
```

Sample flake:
```
[02:23:19] ERROR: Error in test amp-story: embed mode 2 
   Unknown failure in test page 
   Error: Execution context was destroyed, most likely because of a navigation.
```

Impact: I had to restart the visual test job for #21782 three times. The flake error text seem to indicate an underlying infra issue rather than a poorly written test.

https://travis-ci.org/ampproject/amphtml/jobs/521507045

**Comment by danielrozenberg** [comment]
Duplicate of #21056, actively working on this
