### ISSUE TITLE
Uncaught (in promise) Error: Invalid query selector amp-video[id=]​

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#21906]
## What's the issue?
`Uncaught (in promise) Error: Invalid query selector amp-video[id=]​`

Briefly describe the bug.
Invalid query selector for AMP-Video

## How do we reproduce the issue?
1. Go to https://www.google.com/amp/s/www.theringer.com/platform/amp/nba/2019/4/18/18412811/brooklyn-nets-playoffs-new-york-city-fan-base
2. Open developer tools

## What browsers are affected?
macOSX Chrome Version 73.0.3683.103 (Official Build) (64-bit)
macOSX Safari Version 12.0.3 (14606.4.5)
macOSX FireFox Verison 66.0.3 (64-bit)

## Which AMP version is affected?
Dev Version 1904170517570
Stable Version: 1904091426070

<img width="1461" alt="Screen Shot 2019-04-18 at 10 21 48 AM" src="https://user-images.githubusercontent.com/48487406/56379133-da454300-61c3-11e9-9076-5f39c9d8bf11.png">

**Comment by alanorozco** [comment]
Not an AMP error. Caused by publisher's misconfig:

```json

{
  // ...
  "videoPlayYouTube_": {
    "on": "video-play",
    "request": "event",
    "selector": "amp-video[id=]",
    "vars": {
      "eventCategory": "video",
      "eventAction": "youtube:watchcontentCOUNTER(${id}):feature:amp",
      "eventLabel": ""
    }
  }
  // ...
}
```
