### ISSUE TITLE
AMPHTML Layout System listed twice in docs

### ISSUE THREAD

**Issue by breyed** [ampproject/amphtml#21904]
In the [website guides and tutorials](https://amp.dev/documentation/guides-and-tutorials/?format=websites), the **Learn** sidebar lists the **AMPHTML Layout System** twice, each with a slightly different URL:
* https://amp.dev/documentation/guides-and-tutorials/learn/amp-html-layout/?format=websites
* https://amp.dev/documentation/guides-and-tutorials/learn/amp-html-layout/introduction?format=websites

**Comment by aghassemi** [comment]
Thanks @breyed, could you please move the issue to the https://github.com/ampproject/docs repository?

**Comment by breyed** [comment]
I can't [move](https://help.github.com/en/articles/transferring-an-issue-to-another-repository) the issue because I'm not an admin, but I made a copy as ampproject/docs#1922.

**Comment by aghassemi** [comment]
Perfect, thank you!
