### ISSUE TITLE
Promote amp-list[binding] & improve performance

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#21901]
Dev-ex:
- [x] Change examples to use `binding=no|refresh` by default (https://github.com/ampproject/docs/pull/2206)
- [ ] Add user warning to add `binding` attribute 
- [ ] Strip bind attributes from children of amp-list[`binding=no`] 

Performance:
- [x] Don't bother calling `scanAndApply` if no children have bindings (#22938)
- [x] Don't block `scanForBindings` on amp-bind's DOM scan if possible (#22938)

Future:
- Make sure next version (amp-render) uses defaults to `binding=refresh ` behavior
- Reconsider `binding` attribute value naming (possibly confusing e.g. #22043)

**Comment by mattwomple** [comment]
@choumx Following-up on #22043, would it make sense to strip bind attributes from all elements created by `<amp-list binding="no">` before adding those elements to the `document`? Re-using the sample I posted in that issue, [android.cmphys.com/temp/amp-list-binding-no-bind.html](https://android.cmphys.com/temp/amp-list-binding-no-bind.html), I currently observe inconsistent behavior where sometimes `[class]` applies after `amp-list#amplist1` loads and sometimes it does not (ever) apply. If the bind attributes were completely removed from elements when `binding="no"` is specified, it could reduce confusion of developers wondering why they can see the `data-amp-bind-attribute` in the document but it doesn't take effect, as well as eliminate the inconsistent behavior we currently see.

**Comment by mattwomple** [comment]
Another idea I've been considering that would resolve the issue I mentioned above is a new `binding="after-visible"` option. The behavior would be to render amp-list content without any regard for bind attributes and then after the content is visible, let amp-bind prepare elements to respond to bind changes. I would be OK with either waiting for the next bind event to trigger a change or to apply the current bind values as soon as possible.

I understand this could result in some content shifts, but for many use cases this would be acceptable. For example, if the buttons to change a bind value are also inside the template being rendered, then they could not have been tapped to change the default value before the amp-list was rendered. This does raise the question of what behavior should be expected if `[src]` changes for the amp-list (should the behavior mimic `binding="refresh"` or `binding="after-visible"`). If the primary goal is to make sure the first amp-list load is as fast as possible, then adopting the behavior of `binding="refresh"` after first load would probably be fine.

**Comment by choumx** [comment]
> would it make sense to strip bind attributes from all elements created by <amp-list binding="no"> before adding those elements to the document?

Sounds reasonable to me.

> I understand this could result in some content shifts

That would be my main concern. Let's see how much we can improve performance without a new API.

Sorry for the delay on this overall -- have been busy with other stuff. Will spend some time soon.

**Comment by jridgewell** [comment]
This seems like something that could be important, given how frequently amp-list is used. What's left to finish?

**Comment by choumx** [comment]
Just some developer hints on how to use the `binding` API. I can wrap that up quickly.
