### ISSUE TITLE
AMP4Email: Support custom fonts

### ISSUE THREAD

**Issue by jackiewung** [ampproject/amphtml#21907]
## Describe the new feature or change to an existing feature you'd like to see
@ampproject/wg-amp4email 

AMP projects currently support custom fonts using `amp-font` `link` or `@import`. The amp4email renders all custom-font methods as invalid, unless I'm missing something.

## Describe alternatives you've considered
N/A

## Additional context
Used HTTPS googlefonts as an import and followed guidelines of AMP's font imports

**Comment by eolivelli** [comment]
cc @fabienbrouillaud

**Comment by amirgamil** [comment]
Bump on this feature?
