### ISSUE TITLE
amp-brightcove doesn't work when third-party-cookies are blocked

### ISSUE THREAD

**Issue by TStrothjohann** [ampproject/amphtml#2191]
Hey,

I am wondering why the amp-brightcove player doesn't work in Chrome when I block third party cookies. I have captured a Screencast: https://drive.google.com/file/d/0B1nHmrLSmY_NRC15V055Zkc3SFE/view?usp=sharing

You can test it here: http://www.zeit.de/amp/wissen/2016-02/albert-einstein-gravitationswellen-physik-relativitaetstheorie-beweis-astronomie

I think there are many users blocking those third party cookies and in my opinion video playback shouldn't be dependent on cookies being set.

Best
Thomas

**Comment by cramforce** [comment]
CC @mister-ben 

This would also be a problem in Safari.

**Comment by mister-ben** [comment]
This will be addressed in the Brightcove Player itself, soon. Nothing will need to change in the amp-brightcove component.

**Comment by ericlindley-g** [comment]
@mister-ben, do you have an update on this?

**Comment by mister-ben** [comment]
This is fixed in the Brightcove Player version 5.1.8, released end of February.
