### ISSUE TITLE
Lots of `Error: GEONOTPATCHED: amp-geo served unpatched, ISO country not set` in latest Canary

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#21915]
There are lots of new `Error: GEONOTPATCHED: amp-geo served unpatched, ISO country not set` errors in the new Canary. 

go/amp-error/CJOu-fOv5uiPzwE

I am reverting 1% because of it.

**Comment by jridgewell** [comment]
The `trim()` was optimized away, likely in the closure upgrades.

**Comment by aghassemi** [comment]
What's happening here is that a `trim()` call that is performed after `amp-geo` replaces the `magic` string is being optimize out by the new version of the closure compiler, so likely caused by https://github.com/ampproject/amphtml/pull/21618 

# Prod (without bug)
Notice the `trim` and the end of `"us        "` string

![Screen Shot 2019-04-19 at 10 16 48 PM](https://user-images.githubusercontent.com/2099009/56453112-a0725a80-62f1-11e9-86e4-dd097e26c8b0.png)

# Canary (with bug)
Notice the `trim()` is missing which means we end up with the wrong value.
<img width="408" alt="Screen Shot 2019-04-19 at 10 12 22 PM" src="https://user-images.githubusercontent.com/2099009/56453116-be3fbf80-62f1-11e9-9d9e-80fed1e0aa12.png">


## Root cause
I think new version of CC added in https://github.com/ampproject/amphtml/pull/21618 is being super smart here an removing `trim()` because the `magic` string and later gets replaced at serving time is `const COUNTRY = '{{AMP_ISO_COUNTRY_HOTPATCH}}';` and `{{AMP_ISO_COUNTRY_HOTPATCH}}` doesn't need trimming.

**Comment by aghassemi** [comment]
@jridgewell beat me to it.

**Comment by aghassemi** [comment]
We can either not pad the country code and break source map or try to outsmart CC (until they outsmart us at somepoint in the future)

Looking at CC's [optimizations around string method ](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/PeepholeReplaceKnownMethods.java#L197), it doesn't look like they try to optimize `replace`, only `trim` and `upper/lowerCase`. So `s/trim()/.replace(' ','')`? there is no whitespace in the middle to worry about. WDYT @jridgewell?

**Comment by jridgewell** [comment]
I'm putting together a regex now, which can never be optimized.
