### ISSUE TITLE
Adsense ads on desktop

### ISSUE THREAD

**Issue by AutadeJS** [ampproject/amphtml#21918]
## What's the issue?
Adsense ads in AMP pages don't work on desktop. Due to this issue, sites using Adsense cannot be AMP First and have to use paired AMP.

Discussion with @jasti on https://twitter.com/vamseeJasti/status/1119729999844495360
 
## How do we reproduce the issue?

1. Open https://vacayholics.com/facts-about-arc-de-triomphe on desktop
2. Open it's AMP version https://vacayholics.com/facts-about-arc-de-triomphe.amp on desktop in separate tab
3. Notice that in the AMP version, ads don't show. Moreover they take up too much height, notice the empty space.

If we were to show AMP version to desktop users it'd be bad UX because of the gaps. Also it won't monetize.

## What browsers are affected?
All browsers on Desktop.

## Which AMP version is affected?
All

**Comment by torch2424** [comment]
Triaging to @jasti  , feel free to re-assign 😄
