### ISSUE TITLE
Age validation component for AMP stories

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#21922]
## Feature description

Some content can only be shown to users if they confirm they are above a certain age.

A component should exist that offers either a "Confirm" option, "Yes" / "No" options, or a way to enter a birth date.

## Alternative to feature

With AMP Stories this is not easy to implement due to the limited interactivity and lack of `amp-binding`.

An ugly hack is to make the cover a consent page.

## Additional context

Many legislations restrict content shown to minors. Currently there is no way to implement these legal requirements. This could slow down the adoption of AMP Stories for specific regulated industries such as movie, gaming, alcoholic beverage, gambling and adult entertainment industries.

**Comment by torch2424** [comment]
Triaging to @newmuis , feel free to re-assign 😄

**Comment by newmuis** [comment]
@cpauwels could you use [`<amp-story-consent>`](https://amp.dev/documentation/components/amp-consent?referrer=ampproject.org#prompt-ui-for-stories) for this?

**Comment by cpauwels** [comment]
@newmuis didn't think of the <amp-story-consent> component in this use case, in my mind it was GDPR/Cookies/privacy specific. Never used the component so I'll see how it can be used for age consent for instance.

I'll close the issue in the meantime. I'll open <amp-story-consent>-specific issues if I run into usecases that block the implementation of age validation.

Thanks!
