### ISSUE TITLE
Inverted Story Progress bar

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#21923]
## Feature description

On pages with a very light background, the gradient overlay behind the story progress bars at the top of the screen is very pronounced. An inverted progress bar (white gradient overlay with black progress steps) would make the page visually more appealing.

## Alternative to feature

None.

## Additional context

An additional option on the `amp-story-page` component to toggle an inverted progress bar would allow for cleaner, more immersive and just as clear story progress indication.

### Before
<img width="400" alt="Screenshot_2019-04-21_at_16_27_35" src="https://user-images.githubusercontent.com/4594196/56471457-1510da80-6453-11e9-91bb-bb26dae59389.png">

### After
<img width="400" alt="Screenshot_2019-04-21_at_16_31_06" src="https://user-images.githubusercontent.com/4594196/56471463-24902380-6453-11e9-9874-a63c2135a5b0.png">

**Comment by newmuis** [comment]
I think this looks good; I wonder a little about publisher control here -- we can't tell in the runtime what color is actually appearing in that region of the screen, so I think we'd have to leave it up to publishers to tell us that they want the dark/light theme for the progress bar.

Which, of course, means that publishers could misuse it, and request the white on white progress bar, or the black on black progress bar.  But, at the same time, white on white is what we (potentially) serve users today, anyway; black on black might not be any worse?

/to @hongwei1990 
/cc @gmajoulet

**Comment by hongwei1990** [comment]
Will this based on page level or story level? If we open this to the page level, it looks strange when users jump between the dark bar and the light bar. The current white bar is a bit hard to read on a white background, but it is passing AA accessibility. If we open this to the story level, I wonder should we offer dark story theme VS story light theme? Users can pick the theme based on which one works better with their assets.

**Comment by gmajoulet** [comment]
+1 to what Hong said, it'd have to be a story - not page - level configuration.

The white progress bar on white background works today and is accessible. What I'm worried about is that the black progress bar would only work against very light backgrounds, making it very easy for publishers to make it not accessible on one or several of their story pages, depending on their images...

**Comment by hongwei1990** [comment]
+1 i don’t see a very strong reason that we MUST add the black theme. At
least by now I don’t see strong needs. I think this is something we should
put down to consider but no urgent actions needed?

**Comment by cpauwels** [comment]
@hongwei1990 @gmajoulet I would argue for the opposite, make it a page-level configuration. This would allow for the best accessibility in all cases as a story could have very light pages (such as text on white background) as well as darker pages (thinking full screen imagery).

A good example is how Google News handles the change in progress bar on a page basis:

![2019-04-26 09 16 50](https://user-images.githubusercontent.com/4594196/56790178-2a478980-6804-11e9-8d8b-edbdc615bb01.gif)

This to me does not feel strange at all and looks quite lovely 😊
