### ISSUE TITLE
amp-img loading indicators missing in amp-page-attachment

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#21924]
## What's the issue

The `amp-img` loading dots don't appear when loading `amp-img` components in `amp-story-attachment`s.

## How to reproduce

1. Create a Story page with an attachment.
2. Add an `amp-img` to the attachment.
3. Make sure you throttle the bandwidth in your browser so the image doesn't load instantly
4. See that the `amp-img` loading dots don't show up

A live example can be found here: [https://tappable.co/s/tokyo](https://tappable.co/s/tokyo)

<img width="400" alt="Screenshot_2019-04-21_at_16_34_48" src="https://user-images.githubusercontent.com/4594196/56471494-a718e300-6453-11e9-9444-1b036db37661.png">

## Which browsers are affected?

Haven't tested on browsers other than Chrome.

## Which AMP version is affected?

As the `page-attachment` component is very new, I'm guessing all the ones since release of the component.

**Comment by torch2424** [comment]
Triaging to @newmuis , feel free to re-assign 😄
