### ISSUE TITLE
Customizable CTA for Stories attachments

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#21920]
## Feature description

Currently the CTA for the Stories attachment is "Swipe Up". A customisable title would make the component more suitable for some use cases.

## Alternative to feature

None, the CTA is not customisable.

## Additional context

This feature could give the viewers more context on what the attachment will offer to them. Sign Up, More Info, Read Article, Watch Video, etc. could all work.

The API for the CTA customization could be similar to what has been built for links and embeds in the page content (`data-tooltip-text` could become `data-cta-text`)

## Example

<img width="400" alt="Screenshot_2019-04-21_at_16_02_47" src="https://user-images.githubusercontent.com/4594196/56471164-95354100-644f-11e9-9a93-a93ff14f92aa.png">

**Comment by torch2424** [comment]
Triaging to @newmuis , feel free to re-assign 😄

**Comment by newmuis** [comment]
This seems completely reasonable.  @gmajoulet can we add an attribute to override the default page attachment CTA text?

**Comment by gmajoulet** [comment]
Thanks for the feature request @cpauwels!
