### ISSUE TITLE
Title in Stories attachments

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#21921]
## Feature description

The draggable area at the top of the attachment is currently empty, and that space could be used to add an optional title to the attachment.

## Alternative to feature

Adding the title of the attachment in the attachment itself, pushing content further down.

## Additional context

This feature could give the viewers a title that matches the attachment. Could be useful for highlighting some content that will always be visible regardless of how far in the attachment  the user scrolled.

An example could be that the attachment is a review of a place featured on the story page. The name of the place could remain visible at all times in the top bar of the story.

## Example

<img width="400" alt="Screenshot_2019-04-21_at_16_12_03" src="https://user-images.githubusercontent.com/4594196/56471239-71262f80-6450-11e9-9e3e-e852cf1a7f15.png">

**Comment by torch2424** [comment]
Triaging to @newmuis , feel free to re-assign 😄

**Comment by newmuis** [comment]
@gmajoulet WDYT?

I think we'll need to truncate/ellipsify to one line, but otherwise seems reasonable to me.  It's publisher-specified, so they'll need to test it out for content fit.

**Comment by gmajoulet** [comment]
Sounds good to me! This was actually in the original mocks, even though the feature evolved a lot since then: https://github.com/ampproject/amphtml/issues/20209
