### ISSUE TITLE
AMP Validator: not reporting illegal animations/transitions

### ISSUE THREAD

**Issue by SimonHogstromRonbol** [ampproject/amphtml#21933]
## What's the issue?

According to [the documentation](https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml?referrer=ampproject.org#stylesheets) animations and transitions should be limited as such:

> AMP only allows transitions and animations of properties that can be GPU accelerated in common browsers. We currently white list: opacity, transform (also -vendorPrefix-transform).

Currently though, the amp validator doesnt invalidate amp pages that break these rules.

## How do we reproduce the issue?

I have written this very janky example:
https://pastebin.com/raw/S4SAF3Zk

You can paste that into eigther the sandbox over at https://playground.amp.dev/ if you want to preview the janky animations.

Or you can paste it into the validator at https://validator.ampproject.org/

Both will validate them, despite the fact that the animations arent supposed to be valid.

## What browsers are affected?

All browsers.

## Which AMP version is affected?

this is not a new issue.

@nainar we talked about this shortly at AMP Conf following your talk, but normally I just cc @aghassemi

**Comment by aghassemi** [comment]
Hi @SimonHogstromRonbol 

In AMP4Ads we enforce this in CSS, just not for main AMP documents. I don't believe there is a good reason for not enforcing these rules in CSS for documents other than we initially didn't and now it is too late without breaking many pages.

We are not planning to add non GPU friendly properties to `amp-animation` however.

**Comment by aghassemi** [comment]
Similar conversation here: https://github.com/ampproject/amphtml/issues/18253

**Comment by SimonHogstromRonbol** [comment]
makes sense to me, thank you.

**Comment by aghassemi** [comment]
Glad it answered your question. Closing this ticket for now.
