### ISSUE TITLE
AMP-Form: add Request Headers to XHR Requests

### ISSUE THREAD

**Issue by eduardogoncalves** [ampproject/amphtml#21949]
## Describe the new feature or change to an existing feature you'd like to see

Need an option to add custom request headers to an AMP-FORM xhr request.

Some APIs needs that some params be set via request headers. 

![image](https://user-images.githubusercontent.com/4308648/56606561-7ca26380-65d4-11e9-82a7-2f9a21320faf.png)

**Comment by cvializ** [comment]
Thanks for opening this feature request issue! I'll prioritize it and we will address it accordingly

**Comment by eduardogoncalves** [comment]
What if we add a script tag to config headers, like:
```html
<form method="POST" action-xhr="/form/echo-json/post">
        <script type="application/json">
            "headers" : {
                "x-access-token" : "nononononoo"
            }
        </script>
</form>
```
but is it possible to change, for example _x-access-token_ value via __amp-bind__?

**Comment by cvializ** [comment]
@eduardogoncalves amp-bind would only be able to change attributes on the form element since it is not an AMP element, so it would not be possible.

Just a thought, but if you make the API from `<input type="hidden">` with a special name value for a header, it would be bindable.

 ```html
<!-- suggestion -->
<input type="hidden" name="__amp-form-header" value="x-access-token=nononononoo">
<input type="hidden" name="__amp-form-header" value="x-other-header=nononononoo" [value]="'x-other-header=' + variable">
```

**Comment by eduardogoncalves** [comment]
@cvializ currently I'm using this approach with input hidden at https://gerenciador.fidoapp.com.br/ and using a proxy to add headers. But I wish to use it without a proxy.

**Comment by kanchunlee** [comment]
Hope this feature can be implemented, we also have some APIs need to add a access token in request header.

**Comment by sebastianbenz** [comment]
One possible workaround for this is using amp-script to submit the request.
