### ISSUE TITLE
Support for DoubleClick Ad Exchange

### ISSUE THREAD

**Issue by nickdima** [ampproject/amphtml#2194]
Does the `amp-ad` component work with ADX? I tried with setting type to "adsense" and put the client id and slot id that I get from the ADX inventory but it seems to load an empty iframe.
Any suggestions?
I know I could probably load my ads trough DFP but was wondering if I could avoid that for now.

**Comment by cramforce** [comment]
CC @kashyapnitin

**Comment by nickdima** [comment]
Trying some more it seems to load some times, but very rarely. Same ad slot loads just fine in my normal non-AMP page.
I also see these errors in the console, not sure if they matter.
```
HEAD https://pagead2.googlesyndication.com/amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it?0.6407519727945328 Wb.preconnectPolyfill_ @ preconnect.js:173Wb.url @ preconnect.js:106Wb.prefetch @ preconnect.js:122b.preconnectCallback @ amp-ad.js:125(anonymous function) @ custom-element.js:476
amp:1 XMLHttpRequest cannot load https://pagead2.googlesyndication.com/amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it?0.6407519727945328. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.my-site.com' is therefore not allowed access. The response had HTTP status code 404.
preconnect.js:173 HEAD https://googleads.g.doubleclick.net/amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it?0.009048564359545708 Wb.preconnectPolyfill_ @ preconnect.js:173Wb.url @ preconnect.js:106b.preconnectCallback @ amp-ad.js:132(anonymous function) @ custom-element.js:476
amp:1 XMLHttpRequest cannot load https://googleads.g.doubleclick.net/amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it?0.009048564359545708. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.my-site.com' is therefore not allowed access. The response had HTTP status code 404.
preconnect.js:173 HEAD https://3p.ampproject.net/amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it?0.8248486316297203 Wb.preconnectPolyfill_ @ preconnect.js:173Wb.url @ preconnect.js:106Wb.prefetch @ preconnect.js:122Kc.prefetchBootstrap @ 3p-frame.js:159b.preconnectCallback @ amp-ad.js:120(anonymous function) @ custom-element.js:476
amp:1 XMLHttpRequest cannot load https://3p.ampproject.net/amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it?0.8248486316297203. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.my-site.com' is therefore not allowed access. The response had HTTP status code 404.
```

**Comment by michaelkleber** [comment]
Do you have a failing example page we could look at?  The amp-ad type="adsense" should indeed work for AdX publishers.  If you're seeing failures I'm happy to investigate.

(I'm not worried about the errors in the console; they contain the string "404_or_other_error_expected._Do_not_worry_about_it", so I'll take their word for it that I should not!)

**Comment by cramforce** [comment]
@nickdima Those errors have "404_or_other_error_expected_Do_not_worry_about_it" in the URL to make them as non-confusing as possible. This is a technique for speeding up load times in iOS which lacks native preconnect support. Let me know how we could improve the error message to make you not think there is an actual error.

**Comment by nickdima** [comment]
@michaelkleber I'll have an example soon online, I'll post it here.
@cramforce yeah, the url name was pretty self explanatory, but it made me wonder a little anyway. Maybe you can console.log a message in dev mode explaining it? Not sure if it's technically possibile.

**Comment by cramforce** [comment]
@nickdima I'm not sure spamming the console even more would be helpful :) but that is a good idea in general.

**Comment by nickdima** [comment]
OK, I started working better. It seems that they now load at the same rate as on the "normal" page. Probably there was some kind of warm-up involved.
