### ISSUE TITLE
Please add to whitelist Google's new priority hints api

### ISSUE THREAD

**Issue by ghost** [ampproject/amphtml#21945]
Hi very quick simple issue, please can you whitelist the attribute: `importance`

So I can test and use Google's new priority hints api - see here: https://developers.google.com/web/updates/2019/02/priority-hints

An example I am adding will be like this:

```html
<script async src="https://cdn.ampproject.org/v0.js" importance="high"></script>
```

According to the Spec found here: https://wicg.github.io/priority-hints/

We can add this attribute to the following items:

- scripts
- styles
- iframes
- images

For AMP-HTML I will be adding it to the following things:

```
<script>
<amp-img>
<link rel-preload>
```

Hopefully that gives you enough information to add it to your whitelist.

If any of the AMP Team wants to give me any advice that would be a bonus, thanks.

**Comment by ayumihamsaki** [comment]
Also at a later date in the near future maybe the AMP Team would consider adding the Performance API to the amp core to allow doing something like this:

```html
<script async src="https://cdn.ampproject.org/v0.js" importance="high"></script>

<amp-img src="/static/samples/img/amp.jpg"
  width="1080"
  height="610"
  layout="responsive"
  alt="AMP"
  importance="high"></amp-img>
```

**Comment by Gregable** [comment]
@jridgewell I can make the change trivially, but it would be good from someone on @ampproject/wg-runtime to give feedback / approve the behavior of the change.

**Comment by choumx** [comment]
Sounds fine, though we should consider what to do if this experimental feature gets canned. Imperfect, but perhaps whitelist it with a deprecation warning to start?

We'd also need to add it here for it to work in amp-img: https://github.com/ampproject/amphtml/blob/35aaf577288af3d66dd95985f675fa76095d6e8d/builtins/amp-img.js#L30-L31

**Comment by kristoferbaxter** [comment]
cc @prakeekbh, we are experimenting with priority hints and discussed this today.

Likely given the way our runtime manages the request flow for amp-img there is little benefit for other cases beyond htmlscriptelement.

**Comment by choumx** [comment]
Might be useful for prioritizing important/hero images in first viewport in the case where first viewport contains a large amount of images, but agree otherwise.

**Comment by ayumihamsaki** [comment]
Probably a dumb comment, I will also be using it for beta-testing on the rel-preload e.g.

`<link rel="preload" href="https://cdn.ampproject.org/v0.js" as="script" importance="high">`

Not sure if you need to whitelist it there as well or not?

**Comment by kristoferbaxter** [comment]
It's a good idea for testing with rel preload. Tough call about using it outside of the experiment right now, but we should consider it.

@prateekbh is running an experiment on an AMP Cache using this attribute right now. I'll let him comment further.

**Comment by prateekbh** [comment]
@ayumihamsaki We are currently experimenting ourselves with priority hints on AMP cache with scripts. Once we start seeing some results from this experiment we will be able to take a better decision of whether to make this attribute valid or not and if yes then in what shape. I should be able to update this thread in 3-4 weeks with some findings.

For amp-image, amp runtime has a bunch of optimizations baked in already for loading images based on distance from current viewport. With this we feel that adding support priority hints would not be much beneficial and making this valid would make it valid for all amp pages. This may or may not adversely affect AMP document's performance.

**Comment by ayumihamsaki** [comment]
@prateekbh interesting! Is it possible to create a gist of the results, something like cathyxz does in this repo, see here for an example: https://gist.github.com/cathyxz/30fa610e62da3385da8f230c81e236d0

Would be interested to see any results.

**Comment by prateekbh** [comment]
Yes definitely

**Comment by prateekbh** [comment]
The result of the data is to be shared by @erwinmombay and @jridgewell.
However in early results we saw a dip in performance when using priority hints vs `link rel=prefetch`

**Comment by ayumihamsaki** [comment]
Interesting, we been getting increased performance using a combination of rel-preload and priority hints api. However, we got a few people reporting about issues with the loading order when we were using:

```html
<link rel="preload" href="https://example/something.js" as="script" importance="low">
<script src="https://example/something.js" importance="low"></script>
```

With their custom scripts, the `importance="low"` and `async` seems to not work the exact way it's expected.

**Comment by ayumihamsaki** [comment]
Interesting, we're been getting increased performance using a combination of rel-preload and priority hints api. However, we got a few people reporting about issues with the loading order when we were using:

```html
<link rel="preload" href="https://example/something.js" as="script" importance="low">
<script async src="https://example/something.js" importance="low"></script>
```

With their custom scripts, the `importance="low"` and `async` seems to not work the exact way it's expected.

**Comment by ayumihamsaki** [comment]
Interesting, we're been getting increased performance using a combination of rel-preload and priority hints api. However, we got a few people reporting about issues with the loading order when we were using:

```html
<link rel="preload" href="https://example/something.js" as="script" importance="low">
<script async src="https://example/something.js" importance="low"></script>
```

The `importance="low"` and `async` seems to not work the exact way it's expected in the rendering order.
