### ISSUE TITLE
Update ampproject.org references in amphtml repo to amp.dev

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#21965]
There are a large number of references to ampproject.org in the amphtml repo that should be updated to amp.dev.

https://github.com/ampproject/amphtml/search?q=%22ampproject.org%22+NOT+%22cdn.ampproject.org%22&unscoped_q=%22ampproject.org%22+NOT+%22cdn.ampproject.org%22&type=Code

/cc @ampproject/wg-outreach

**Comment by pbakaus** [comment]
@matthiasrohmer could you and your team take a look at this?
