### ISSUE TITLE
Unskip flaky amp-ad-xorigin-iframe-handler test

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#21961]
Sample Travis run: https://travis-ci.org/ampproject/amphtml/jobs/523889487

https://github.com/ampproject/amphtml/blob/15e085d9f68f030f8535509390c9ef5a43f62001/extensions/amp-ad/0.1/test/test-amp-ad-xorigin-iframe-handler.js#L156-L167

**Comment by lannka** [comment]
thanks for reporting. @cvializ you can go ahead and mute it for now. we will fix it later
