### ISSUE TITLE
Math Whitelist Functions: add "sqrt" and "log"

### ISSUE THREAD

**Issue by MkVII** [ampproject/amphtml#21971]
Hi,

I'm designing a medical calculator, and many of the calculations require Math.sqrt and Math.log.

Unfortunately they are not whitelisted Math functions:
https://amp.dev/es/documentation/components/amp-bind?referrer=ampproject.org#white-listed-functions

May the above functions be added to the whitelist please?

Thanks
Brad

**Comment by torch2424** [comment]
Triaging to @choumx , feel free to re-assign 😄

**Comment by MkVII** [comment]
Hi. Just following up. Any chance this can be done? Or would you like me to do a pull request myself?
Thanks :-)

**Comment by choumx** [comment]
A pull request would be great! Check out existing whitelisted Math functions in `bind-expression.js` for example, and make sure to add a test to `test-bind-expression.js`.

**Comment by abiral** [comment]
@choumx I have added sqrt and log functions in `bind-expression.js`, added test case in `test-bind-expression.js`
I also have ran the test locally as mentioned in this URL: https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md
It showed me no errors at all. So, what else should I do? How can I make sure that I have done it right?

I have committed the changes to feature branch of the repo I have forked. What else should I do now?

Thanks in advance.

**Comment by choumx** [comment]
You can create a pull request against amphtml: https://help.github.com/en/articles/creating-a-pull-request

**Comment by abiral** [comment]
Hello @choumx,
I have created a pull request - https://github.com/ampproject/amphtml/pull/22107

What else should I do now?

Thanks for help.

**Comment by choumx** [comment]
Congrats on your first contribution!

**Comment by torch2424** [comment]
@abiral Thank you for the contribution! Stoked to hear it is your first one! Congrats! 🎉 😄 👍
