### ISSUE TITLE
Add Native Lazy Loading Support and Whitelist attribute loading

### ISSUE THREAD

**Issue by ayumihamsaki** [ampproject/amphtml#21982]
Google Chrome is officially launching Native Lazy Loading in Chrome 75+ and they have created a new attribute called [loading](https://chromestatus.com/feature/5645767347798016).

Example of the Google Spec will be like this:

```html
<!-- Lazy-load an offscreen image when the user scrolls near it -->
<amp-img src="/static/samples/img/amp.jpg"
  width="1080"
  height="610"
  layout="responsive"
  alt="AMP"
  loading="lazy"></amp-img>

<!-- Load an image right away instead of lazy-loading -->
<amp-img src="/static/samples/img/amp.jpg"
  width="1080"
  height="610"
  layout="responsive"
  alt="AMP"
  loading="eager"></amp-img>

<!-- Browser decides whether or not to lazy-load the image -->
<amp-img src="/static/samples/img/amp.jpg"
  width="1080"
  height="610"
  layout="responsive"
  alt="AMP"
  loading="auto"></amp-img>
```

Please can you add the attribute to the whitelist and add it to the AMP Core.

Thanks.

**Comment by aghassemi** [comment]
Hi @ayumihamsaki 

AMP has its own heuristics for lazy-loading, we are thinking about exposing ability to configure this heuristics in https://github.com/ampproject/amphtml/issues/21497 . `loading` attribute that was added was actually a collaboration between AMP and Web Platform to push for bringing some of AMP's features to the general Web.

Please subscribe to https://github.com/ampproject/amphtml/issues/21497 to ad your thoughts and get updates.

**Comment by aghassemi** [comment]
Closing as dup of https://github.com/ampproject/amphtml/issues/21497

**Comment by ayumihamsaki** [comment]
@aghassemi Thanks for the info and link.
