### ISSUE TITLE
amp-ima-video results in JS error

### ISSUE THREAD

**Issue by cycleos** [ampproject/amphtml#21987]
## What's the issue?
When using amp-ima-video, it never loads ads (edit: From Ad Networks). In the console, there is a JS error
imaVideo.js:1361 Uncaught TypeError: Cannot read property 'event' of null at Cf (imaVideo.js:1361)

## How do we reproduce the issue?
Go here and open the dev console:
https://news.bg/politics/borisov-gleda-bashtinski-na-spora-mezhdu-unss-i-mf.html?amp=true

The error will display itself in the console.

## What browsers are affected?
All browsers I used for tests (Chrome, Chrome Mobile, Firefox Mobile)

## Which AMP version is affected?
Not aware. It was working in February latest. I have seen the same error on a reference URL from another ticket (so it is a implementation from completely different person) and the same error appears:
https://stage-mdev-wbns.pantheonsite.io/article/23-million-drugs-seized-during-search-olentangy-commons-apartment-ads-2019-apr?amp=

The error appears in the demo as well, however it plays the ads:
https://playground.amp.dev/?url=https://preview.amp.dev/documentation/examples/components/amp-ima-video

**Comment by aghassemi** [comment]
Hi @cycleos 

I will look into the errors but I can see Ads loading fine on both https://news.bg/politics/borisov-gleda-bashtinski-na-spora-mezhdu-unss-i-mf.html?amp=true and our example site https://amp.dev/documentation/examples/components/amp-ima-video/ on both desktop and mobile

Do you see any ads loading on our sample page? https://amp.dev/documentation/examples/components/amp-ima-video

I don't think this a player issue, likely Ad Unit, Inventory, targeting config from the Ads side is making you not see your own ads.

**Comment by aghassemi** [comment]
(Verified that the errors are not causing user-visible issues, but will be fixing them)

**Comment by cycleos** [comment]
I see the ads on the demo page. Changing the ad tag with our own ad tag (DFP) on the demo page results in exactly the same behavior as on our own site. Direct video campaigns are displayed. Videos ads from ADX or other ad networks are not. The last could be caused by other reasons (i.e. low demand in the geo), yet I can't either confirm it. If you have seen ad, then it is very probably low demand or other similar issue and not technical one.

**Comment by cycleos** [comment]
OK, after dozens of refreshes I have seen a network ad, so it is market demand issue.
The JS error is not causing unexpected behavior from user perspective.
