### ISSUE TITLE
`amp-sidebar` tests are timing out on Firefox

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#21999]
Results from the past couple hours:

https://travis-ci.org/ampproject/amphtml/jobs/524684465#L1618
https://travis-ci.org/ampproject/amphtml/jobs/524679086#L1616
https://travis-ci.org/ampproject/amphtml/jobs/524678968#L1603

**Comment by aghassemi** [comment]
verified nothing is actually broken in FF 66. looking into the flake.
