### ISSUE TITLE
`amp-image-lightbox` tests are timing out on Firefox

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#21997]
Results from the past couple hours:

https://travis-ci.org/ampproject/amphtml/jobs/524674697#L1608
https://travis-ci.org/ampproject/amphtml/jobs/524691866#L1594
https://travis-ci.org/ampproject/amphtml/jobs/524691866#L1594

**Comment by aghassemi** [comment]
verified nothing is actually broken in FF 66. looking into the flake.
