### ISSUE TITLE
Consider forwarding touch events from ads to doc

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2200]
So that swiping works when ad is visible.

Is a a security problem that the ad would swipe away the doc? Kinda doesn't make any sense.

Should we also provide an API or little script for other iframes?

**Comment by mkhatib** [comment]
Is the touch events are grabbed by our own iframes that wrap ads? 

Is the idea of not disabling `pointers-events` on these iframes is to allow scrolling in the ad iframe itself?

**Comment by dvoytenko** [comment]
By those iframes, yes, and by all others - there many iframes, including YouTube.

I don't know if we can actually disable `pointer-events` inside of the iframes - that sounds like clickjacking :) But normally those iframes do need touch and all other pointer events.

**Comment by jasti** [comment]
This has been open for a while.
To @lannka for prioritization.

**Comment by cramforce** [comment]
We fixed the swiping issues in amp carousels. I don't think we can do the proposed thing.
