### ISSUE TITLE
amp-consent v2: Exit full-screen mode

### ISSUE THREAD

**Issue by torch2424** [ampproject/amphtml#22005]
realtes to: #17742 

https://github.com/ampproject/amphtml/issues/17742#issuecomment-486851211

> Being able to exit full-screen mode from the iframe (ie have a postMessage to tell AMP to exit full-screen mode). In our current setup, once the user enters full-screen mode (clicking on "Learn More" from a notice, for instance), we are unable to exit it.

**Comment by torch2424** [comment]
cc @zhouyx

**Comment by MaximePlancke** [comment]
Hi @torch2424 @zhouyx 

Were you guys able to see if it would be possible to add this feature? We are planning to deploy on production our first version of AMP consent notice next week and this feature is pretty important to us as right now when the user open the full screen preferences popup, it is not possible to close it and come back to the bottom banner.

Thank you :)

**Comment by torch2424** [comment]
@MaximePlancke 

"We are planning to deploy on production our first version of AMP consent notice next week"

Oh awesome! Congrats! 😄 🎉

"this feature is pretty important to us as right now when the user open the full screen preferences popup, it is not possible to close it and come back to the bottom banner."

I will probably be the one to implement this if we decide to do this. But will delegate this to @zhouyx and @jasti For prioritization 😄 

Thanks! 👍

**Comment by zhouyx** [comment]
Thank you @MaximePlancke and @torch2424 for the update. From the demos we saw, users would have to interact with the consent prompt (either accept or reject) after entering full screen. So that's the reason we didn't implement this 'exitFullscreen' feature. 
@MaximePlancke We don't want user to be always blocked by a consent blocking prompt, even it is at the bottom. In such case, when the user close the full screen popup, should it considered that user dismiss or reject the prompt and hide the banner? Curious on what your prompt flow looks like and happy to discuss further. 

RE: prioritization. 
If we decide to implement this feature. I'd prefer that @torch2424 can work on it because they own the consent UI code. But @torch2424 is traveling next week. So I expect we can plan for the feature the next spring (6/10-6/21). @MaximePlancke would that work for you? Thank you

**Comment by MaximePlancke** [comment]
@zhouyx @torch2424 Thank you for your answers. 

In our case, the full screen is the preferences popup. It is a detailed version of the bottom banner where you can see the list of purposes and vendors, accept all/reject all. This popup can be closed without giving a consent by clicking on the top right cross. In that case, we can't consider that action as a `reject` for our clients. Once closed, the user still have the choice to `accept` or `learn more` (open the preferences popup) again from the bottom banner.

The `dismiss` action doesn't exist in our current flow and the user needs to answer by `accepting` or `rejecting` to close the popup. 

The most important point is that to be GDPR compliant we will have to consider `dismiss` as `reject` and adding that behavior would not be a change accepted by our current clients. Let me know if you have any more questions.

Yes 6/10-6/21 works for us and would be really appreciated from our side :).

Thank you!

**Comment by zhouyx** [comment]
@MaximePlancke Thank you for clarifying. 

>In our case, the full screen is the preferences popup. It is a detailed version of the bottom banner where you can see the list of purposes and vendors, accept all/reject all. This popup can be closed without giving a consent by clicking on the top right cross. In that case, we can't consider that action as a reject for our clients. Once closed, the user still have the choice to accept or learn more (open the preferences popup) again from the bottom banner.

I see. My worry is that in this case the user has already interact with the prompt, which I find less user friendly to still block them with the prompt window. Especially allow prompt ui to mask over the content and block the content.  

>The dismiss action doesn't exist in our current flow and the user needs to answer by accepting or rejecting to close the popup.

Ideally I still think the best approach is to report `dismiss` in such scenario.  Unlike `reject`, `dismiss` will not be stored, so the prompt will show up the next time user visit the page. By default `dismiss` is treated the same like `reject` by AMP components on this visit. However different components can choose to override the `dismiss` behavior. (doubleclick ad for example support the `data-npa-on-unknown-consent` attribute to determine `dismiss` behavior). 

Let me know if `dismiss` work for you. Thank you!

**Comment by MaximePlancke** [comment]
@zhouyx I understand your point.

After discussing with the team, we will go with the `dismiss` option. If you decide to implement this option to exit de full-screen mode later on, please let me know.

Thank you!

**Comment by zhouyx** [comment]
Thank you @MaximePlancke We will definitely keep you updated if we decide to pick up the work!
