### ISSUE TITLE
Exclude @font-face from CSS limit

### ISSUE THREAD

**Issue by anuragphadke** [ampproject/amphtml#22002]
Exclude @font-face length calculation for 50KB CSS limit.

While we have white listed certain font providers, a lot of us use custom fonts as part of the @font-face tag. It will be really nice if we can exclude the size limit for CSS calculation  when `@font-face` is used in the CSS.

Example gist: https://gist.github.com/anuragphadke/271c7bd0139424960f0b7e4503569bdb
The gist alone is few kb's and quickly adds to the CSS limit.

Alternatively, would love to read if there is some documentation / reasoning as why we don't want to exclude @font-face from size calculation.

thank you.

**Comment by torch2424** [comment]
cc @aghassemi 👍

**Comment by choumx** [comment]
Do you have a reason why `@font-face` should be treated qualitatively different from other CSS? I don't see anything obvious. 

For rationale on the CSS limit generally: https://twitter.com/cramforce/status/806291737903648768. The ultimate goal is to allow CSS without limits that's known to be used on the page. 

Merging this issue with #4555.
