### ISSUE TITLE
FRs for amp-action-macro

### ISSUE THREAD

**Issue by alabiaga** [ampproject/amphtml#22013]
- [ ] Support conditional invocation
- [ ] Support multiple actions
- [ ] Support references by amp-bind-macro (with constraints to avoid sequential `setState`)

Related: #19494

**Comment by sebastianbenz** [comment]
Have we got an ETA for the conditional invocation? I regularly see questions about this on Slack and SO (e.g. the [latest question](https://stackoverflow.com/questions/57554671/how-to-check-response-is-null-or-not-in-amp)).

**Comment by alabiaga** [comment]
@sebastianbenz I had a PR for this, https://github.com/ampproject/amphtml/pull/21625/files. I will reopen for @choumx to review and comment on, whether the approach I am taking is correct or if it needs more work. Thanks
