### ISSUE TITLE
Validator Web UI appears to incorrectly cause the amp-web-push component to change URLs from https to http

### ISSUE THREAD

**Issue by samparnell** [ampproject/amphtml#22018]
## What's the issue?

Given a valid AMP page I get inconsistent results when using the Validator Web UI vs the NPM CLI/Chrome Extension. This only seems to happen on certain domains and only when querystring params are added to the URL. 

This is currently preventing us linking to/rendering this content in our viewer. I believe I have seen similar behavior in the past but wasn't able to reproduce consistently before. If I can identify other domains this occurs on I will update.

## How do we reproduce the issue?

This page is a valid amp as reported by the amp validator site/chrome plugin/npm cli: https://civileats.com/2019/04/24/fast-food-workers-can-be-fired-for-no-reason-a-new-bill-could-change-that/amp/

With querystring params added the amp validator chrome plugin and npm cli still report as valid but the amp validator site does not.

Example amp url: https://civileats.com/2019/04/24/fast-food-workers-can-be-fired-for-no-reason-a-new-bill-could-change-that/amp/?some=param
Example validator url: 
https://validator.ampproject.org/#url=https%3A%2F%2Fcivileats.com%2F2019%2F04%2F24%2Ffast-food-workers-can-be-fired-for-no-reason-a-new-bill-could-change-that%2Famp%2F%3Fsome%3Dparam

Note: viewing the source of the amp page directly, with and without the param, yields the same result. The reported result about invalid url protocols in the amp-web-push component using http rather than https does occur in the source of the page.

Consequently this cache url is fine: https://civileats-com.cdn.ampproject.org/c/s/civileats.com/2019/04/24/fast-food-workers-can-be-fired-for-no-reason-a-new-bill-could-change-that/amp/

But this one is not and redirects: https://civileats-com.cdn.ampproject.org/c/s/civileats.com/2019/04/24/fast-food-workers-can-be-fired-for-no-reason-a-new-bill-could-change-that/amp/?some=param

Or returns an error for the viewer version: https://civileats-com.cdn.ampproject.org/v/s/civileats.com/2019/04/24/fast-food-workers-can-be-fired-for-no-reason-a-new-bill-could-change-that/amp/?amp_js_v=0.1&some=param#origin=https%3A%2F%2Fdistributedmedialab.com&cap=swipe%2CnavigateTo%2Cfragment%2CerrorReporter&horizontalScrolling=0&prerenderSize=1&visibilityState=visible

**Comment by honeybadgerdontcare** [comment]
@samparnell I noticed running `curl http://civileats.com/2019/04/24/fast-food-workers-can-be-fired-for-no-reason-a-new-bill-could-change-that/amp/` serves up a page where `amp-web-push` has `http` instead of `https` as protocols. Could the issue be server side?

**Comment by samparnell** [comment]
It could be but the validator urls that I posted are all using the https version. Arguably they should be redirecting to https but that may not be feasible for all publishers who may still support http for non-amp pages (they should be doing it everywhere but not all do).

**Comment by samparnell** [comment]
Also I'm not sure how that would explain the issue only came up when we have query string params on the url. They don't redirect to the http version or anything like that.

**Comment by samparnell** [comment]
Update: Civil Eats updated their setup to redirect all http traffic to https. This seems to have resolved the issue for them. 

I guess the underlying question is why would the validator use the http version when https one is specified? Not all publishers will be able to change their http/https set up so easily.

**Comment by Gregable** [comment]
The issue is no longer presenting for the publisher. It also sounds like @honeybadgerdontcare 's analysis is correct in that this was happenning on the server side of the publisher. The AMP Validator does not modify the document it receives from the publisher.
