### ISSUE TITLE
Ads would like a timestamp for the "beginning" of processing an ad

### ISSUE THREAD

**Issue by bobcassels** [ampproject/amphtml#2201]
For analysis purposes, we would like to have timestamps for various points in the life of an ad. Once we get control, we can take our own timestamps. But it would be nice to have a "base" time. We were thinking that would be something like when we started building the structure for the amp-ad. That timestamp could be passed in as a "context" entry.

I'm happy to do the work, if we can agree on where the start time should be recorded, and what the name of the context entry should be. I assume the value will be a timestamp similar to the one in intersection change entries.

**Comment by kashyapnitin** [comment]
Could you clarify who is "We" in the request (the amp runtime, creative, adserver, somebody else) and what's the use case - what are these timestamps needed for?

**Comment by cramforce** [comment]
Would certainly be easy to implement.

**Comment by jasti** [comment]
@bobcassels is this still necessary since A4A code path is not an extension anymore and you have full control? Please close if not necessary.
