### ISSUE TITLE
🌸 Cherry pick request for [22022] into [1904240947200] (Pending)

### ISSUE THREAD

**Issue by chenshay** [ampproject/amphtml#22031]
# Cherry-pick request

| Issue | PR  | Production? | RC? | Release issue|
| :---: | :-: | :---------: | :-: | :-----------: |
| #22022 | #22023 | **NO** | **YES** | #21958 |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

getEntitlements is broken in the subscriptions local service

## Summary

getEntitlements is broken in the subscriptions local service. This is in RC and not in PROD.

---

/cc @cramforce

**Comment by dvoytenko** [comment]
Approved.

**Comment by lannka** [comment]
done
