### ISSUE TITLE
DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.

### ISSUE THREAD

**Issue by sryze** [ampproject/amphtml#22039]
## What's the issue?

Hello,

I'm converting a (working) CSS animation into `<amp-animation>`, I think I've done it correctly but I'm getting an error:

```
Uncaught (in promise) DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
    at https://cdn.ampproject.org/v0/amp-animation-0.1.js:27:766
    at Array.map (<anonymous>)
    at tb.push.f.r.init (https://cdn.ampproject.org/v0/amp-animation-0.1.js:27:703)
    at https://cdn.ampproject.org/v0/amp-animation-0.1.js:209:104
```

Is this because I'm using `offset` in keyframes?

## How do we reproduce the issue?

Here is both CSS and AMP versions:

https://gist.github.com/sryze/9ce17d9c80f6dff79bb847cefec47f80

It has been auto generated by a script I wrote. I'm rewriting it in JSON because of the limit of 50KB for CSS in AMP. Previously I wrote this animation in CSS because of another restriction of AMP - the inability to execute custom JavaScript code (it was pretty painful).

## What browsers are affected?

Chrome

## Which AMP version is affected?

1904200955460

**Comment by aghassemi** [comment]
Hi @sryze,

Yes, you need a final keyframe. Currently the last keyframe you have is `"offset": "0.18",`, you need another one with `"offset": "1"` so your keyframe definitions become complete.

**Comment by aghassemi** [comment]
Closing per comment above, please feel free to reopen in your concerns are not fully addressed.
