### ISSUE TITLE
amp-list State bind, initially list not in view

### ISSUE THREAD

**Issue by stibio** [ampproject/amphtml#22043]
Can be **closed**.

The issue was having the attribute binding="no" on the hidden list, for the _original_ example in the 'Step By Step' it needs binding="always" or binding="refresh" attribute in order to work. 

Although only binding="always" works for an amp-list that is initially hidden via media query styles without extra code. The performance isn't the best in this case so not an ideal solution. 

Updated JSBIN with media queries and binding="always", working but occasionally poor performance even on this basic example:
https://jsbin.com/zonutokewa/1/edit?html,output

Have added a further change to use binding="refresh" and then explicitly call the 'refresh' whenever a button in the lists are clicked, as can be seen in the final JSBIN:
https://jsbin.com/pinuyarela/edit?html,output

## What's the issue?

I have an amp-list component that isn't visible at all screen sizes that pulls in a list of items from a json file on the server. This works fine and populates with the required items, some of the html tags inside contain conditional css classes using the [class] attribute that get updated with state changes. At desktop views this works as expected and the classes (an 'on' state) get updated when a particular item is selected. However at views where the amp-list is hidden on load (eg portrait tablet) and then come into view later (eg rotated to landscape tablet), the [class] values never update based on state changes. Other elements on the page do update so it's not an issue with state setting (and printState() confirms this).

I have got around the issues mentioned here: https://github.com/ampproject/amphtml/issues/11998 - [amp-list not setting based on the current state on load], this seems like a separate problem.

## How do we reproduce the issue?

If you create an amp list with elements with the bound class - [class]="..." - attribute that relies on state values. Have the list not shown by default and then show the list at a later point - this can be a viewport change or using a separate bind variable, then observe that state bound classes won't update as expected.

Step by step example:

1. Visit the JSBIN - https://jsbin.com/jividedone/1/edit?html,output (original - button to open trigger)
2. View the items in the list and see that by default 'Item 3' is 'on' (green background). The state matches this.
3. Click on any item (e.g Item 4) in the visible amp-list to see how the 'on' item changes to whichever is clicked. This is achieved via a simple state change on tap.
4. Click on the "Toggle 'Hidden' List" link to show, via a state variable + [class], a duplicate amp-list that was hidden by default. Observe that 'Item 3' is always the selected item (expected as per: https://github.com/ampproject/amphtml/issues/11998) 
5. Now 2 amp-lists are visible, click on any item in either amp-lists and see how the top amp-list never updates the 'class' attribute unlike the bottom one that works as expected. All buttons in both list will update the state as required but the top amp-list, which was initially hidden, always shows 'Item 3' as 'on' which was the item that was set as selected in the json file.

## What browsers are affected?

All browsers.

## Which AMP version is affected?

As far as I can tell, it has always been an issue.

**Comment by aghassemi** [comment]
related: https://github.com/ampproject/amphtml/issues/21901 
Thanks for the detailed write up @stibio .
/cc @cathyxz FYI ( also https://github.com/ampproject/amphtml/issues/21901 ) something to incorporate into `amp-list v2` design as we would want a better default here.

**Comment by aghassemi** [comment]
I will keep this open and added it to the tracker for `amp-list v2` as use-case to verify.

**Comment by mattwomple** [comment]
Just want to chime in to say that I've been affected by this as well. I expected that bind attributes would not be evaluated at time of `amp-list` load (when `binding=no`), but was surprised to find that those bind attributes could not be used well after load.

Minimal example: https://android.cmphys.com/temp/amp-list-binding-no-bind.html
The buttons on that page will change the text color of everything but the title. The color change _sometimes_ works for the text in `#amplist1` (depending on whether your browser already has the images cached) and will almost certainly fail for the text in `#amplist2`.

**Comment by aghassemi** [comment]
@choumx anything here that's not captured in #21901?

**Comment by choumx** [comment]
Perhaps just that the naming is confusing, but I think can be closed.
