### ISSUE TITLE
Support HTML5 Ping Attribute on Links

### ISSUE THREAD

**Issue by ekingery** [ampproject/amphtml#22052]
## Describe the new feature or change to an existing feature you'd like to see

I would like to see AMP support [the HTML5 Ping Attribute on Links](https://www.w3.org/TR/html53/links.html#element-attrdef-a-ping). This is also referred to as [hyperlink auditing](https://html.spec.whatwg.org/multipage/links.html#hyperlink-auditing).

## Describe alternatives you've considered

The amp-analytics component is more-or-less functionally redundant (and a superset) of what the HTML5 ping attribute offers. However, I think the ping attribute is worthwhile for two reasons.

1. amp-analytics is not available in the [amp4email spec](https://github.com/ampproject/amphtml/blob/master/spec/amp-email-format.md#amp-specific-analytics).

2. In my opinion, the HTML5 ping attribute provides a more uniform, lightweight, and transparent means to tracking clicks in both emails and in traditional HTML markup / serving. 

## Additional context

The ping attribute [is currently implemented on most browsers](https://caniuse.com/#feat=ping). 

I am interested in converting this / opening an intent-to-implement (pending the outcome of this ticket, of course). Regardless of the outcome, it seems that [the documentation should be updated](https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml#html-tags
) to reflect the intent to support or not support the ping attribute. Right now as I read the documentation, it should be supported. That said, I couldn't find anywhere that states specifically which version of the HTML spec that AMP is modeled on. If it is before 5.3, then it would stand to reason that the ping attribute would not be supported. I think making this explicit is worthwhile.

**Comment by Gregable** [comment]
The validator changes are trivial, however this is more of a question of if behavior makes sense for AMP or not.

For amp4email, I imagine that this wouldn't be allowed in that spec either. I'm just guessing, but the privacy requirements are stricter there. The browser is not supposed to make direct http connections to another site in webmail providers. One could argue that the click event is authorization for this, but it's unclear.

**Comment by torch2424** [comment]
cc @lannka This is super interesting, and could be used for something like the new link rewriter? 😄 🤔

**Comment by lannka** [comment]
@ekingery thanks for bringing this up.

Could you share the use cases you're looking at? Here are a couple of things we need to consider depend on the real use cases.

- To make the tracking useful, we will want to support macros in the ping URL. In my local testing, the ping post request does not include cookies, (although the spec said credential=include). So likely we will want to put user identifiers in the request.
- The `ping-from` header will be missing when the AMP page is served from cache. We need an alternative way for pub to know which page the ping is from
- FireFox does not support `ping` yet. We might consider adding a polyfill.

**Comment by ekingery** [comment]
@lannka, absolutely. The primary motivation for me to get HTTP Ping into AMP is so that it can be made available in Amp4Email. I am working on an email newsletter-like product and I would like to measure engagement on behalf of the senders. I'm primarily looking to count clicks, I don't need a cookie trail or anything else. I was planning to pass a newsletter-ID in the query string of the ping URL. 

HTTP Ping is great for this use case, because you don't have to rewrite the URLs using a redirect service, which in my opinion increases trust and transparency for the recipients of the email. Without getting into the details, I can also see the flip side, that it could be seen as decreasing transparency vs using a URL redirect service.

To your second point about passing through user identifiers, that seems like it would be a useful feature for other use cases, and I would potentially use that in the future as well. It would be nice to be able to opt in or out of this.

If the `ping-from` header will not be passed through when cached, I could work around that by encoding the link destination in the query string of the ping URL. Perhaps that is something that could be done automatically by AMP to compensate. Definitely something worth documenting but I don't see that as a blocker.

Lastly, for FireFox I believe HTTP Ping is available now in a browser config switch and [it looks like they will enable it by default soon](https://www.bleepingcomputer.com/news/software/mozilla-firefox-to-enable-hyperlink-ping-tracking-by-default/). That article also does a decent job of covering the privacy / transparency point I touched on above.

**Comment by lannka** [comment]
@ekingery thanks for the details. 

They are all good. The only challenge that drags me behind is where to put those logic. It wouldn't be ideal to include those extra bytes in the core runtime (v0.js), as I don't foresee a broad usage of this the `ping` attribute. 

For your specific email use case, I see 2 possible ways forward
- we ignore the mentioned limitations, no user identifier, no ping-from. to do that, we simply make a validation rule change to allow `ping`. your described use case might still work 
- bring amp-analytics to amp4email spec. need to understand what was the blockers (which could also be blockers for supporting `ping` in email).

@jasti @choumx any input on this?

**Comment by jridgewell** [comment]
Is amp-analytics necessary here? If amp-pixel is already allowed, we could rely on that?

**Comment by lannka** [comment]
we will need the click trigger functionality that amp-analaytics provides. meantime, amp-pixel is also not allowed in amp4email.

**Comment by jridgewell** [comment]
So the line between pixel and analytics always confuses me. I don't think we need analytics bundle, sense it does a lot more than is necessary here (actual analytics collection). I think all that's needed is the URL replacements, we pixel uses. The click listener itself should be minimal enough that we can implement it by default in runtime, and we just early exit if URL replacements isn't loaded by something else.

> It wouldn't be ideal to include those extra bytes in the core runtime (v0.js), as I don't foresee a broad usage of this the ping attribute.

I think the browsers are going to be pushing using the `ping` attribute, that's why everyone is enabling it by default even against the hacker news FUD.

**Comment by lannka** [comment]
Hm, one race condition to think about for url-replacement . If AMP runtime is not yet ready before user clicking on the anchor, browser will send the ping with unresolved macros.

To be fair, the race condition exists today when amp-analytics is not ready yet before the user click. In that case, we don't send ping.

Hard to say which behavior is better. 

@jridgewell I don't see why we can't allow `ping` attribute. Just not sure where to put the extra features to make it useful. For the amp4mail use case, it's more of a question for privacy and security.

**Comment by jridgewell** [comment]
I'm totally fine with whitelisting `ping` with no additional functionality. I think it should be enabled in AMP at least, and A4A and A4E should evaluate whether to allow it (I think they should).

We can add URL replacement functionality later (and A4A and A4E can determine if they want that functionality).

**Comment by choumx** [comment]
As Greg mentioned, support in AMP4EMAIL sounds reasonable but may need work from some providers that have strict privacy invariants.

**Comment by lannka** [comment]
@choumx are different amp4email providers putting custom restrictions on the content? what's the right way to move forward?

I think we all agreed to make validation rule changes to allow `ping` attribute on anchors for both AMP & AMP4ADS spec. It at least can be immediately used for non-user identifiable tracking. So it's a matter of AMP4EMAIL.

**Comment by Gregable** [comment]
> @choumx are different amp4email providers putting custom restrictions on the content? what's the right way to move forward?

My preference would be to see how far we can get with a single unified set of constraints for AMP4EMAIL. Presumably that would mean **not** supporting html5 ping.

**Comment by choumx** [comment]
Correct, no support in AMP4EMAIL for now but possibly in the near future.

**Comment by lannka** [comment]
So what's the option for @ekingery for click tracking? Do they have to do the redirection?

**Comment by Gregable** [comment]
The question gets to what is the privacy model for webmail providers. Clearly they consider clicking a link as implicitly allowing for the origin in the link to gain access to the user's network request. The question is if they consider the same event to allow for any origin that the link sender suggested. More concretely, if foo@example.com sends me an email with a link to http://wikipedia.org/, should me clicking that link cause example.com to get a network request from my browser.

Perhaps getting some feedback from existing implementors of the AMP Email spec would provide more information.

**Comment by jasti** [comment]
I'll take the action item to get feedback from the providers (Gmail & Co) and if there is a reason why `amp-pixel` was disallowed in the first go around. Please stay tuned.

**Comment by lannka** [comment]
@Gregable good thinking about the privacy model. Probably that's [why FF disabled the feature ](https://bugzilla.mozilla.org/show_bug.cgi?id=415168) before they can come up with a good UI to inform user about the extra network request.

**Comment by ekingery** [comment]
@jasti any updates from the email providers? Thanks!

**Comment by fstanis** [comment]
@jasti and I discussed this with the Gmail team as well as a few others, including ESPs.

We won't be adding `ping` attribute support to the AMP for Email spec for now. The main reason is lack of browser support, something which was a major factor in our previous decisions regarding attribute and element support.

Notably, in this case, because not all browsers support it, it would provide inaccurate metrics and thus has little value compared to the current email practice of using redirects to achieve the same goal.

Regarding `amp-pixel`: the decision not to support comes from the fact that AMP for Email doesn't support URL variable substitutions, which are the only reason to use `amp-pixel` over `amp-img`. Therefore, enabling `amp-pixel` is effectively blocked by the lack of supported URL variable substitutions. If you have a good use-case for supporting `amp-pixel` that can't be solved via `amp-img`, I think this would be good to bring up with [the working group](https://github.com/ampproject/wg-amp4email).

Regarding `amp-analytics`: Like with enabling variable substitutions, I believe this is better suited to bring up with [the working group](https://github.com/ampproject/wg-amp4email) since, like @Gregable mentioned, other email providers need to chime in with regards to what, if any, acceptable support can be provided in accordance with their privacy models.

Please keep in mind we decided to err on the side of simplicity with the components we initially whitelisted and that the list is by no means final. We hope that more components will be whitelisted over time by the working group as the user base expands and new use-cases are brought up for discussion there.
