### ISSUE TITLE
Any limits to show the number of comments posts in amp-facebook-comments?

### ISSUE THREAD

**Issue by pegazee** [ampproject/amphtml#22062]
## What's the issue?

I've added the amp-facebook-comments and set the data-numposts to 150 or more than 100 ( data-numposts="150" ). And getting the blank space instead of a comment box.

If I've set the data-numposts to 100 or less than 100, the box was displaying & working perfectly. Is there any limits to show the number of comments posts? I've also read the documentation here: https://amp.dev/documentation/examples/components/amp-facebook-comments/ but didn't find any guidelines for limits.

**Comment by aghassemi** [comment]
@pegazee Although not documented, 100 seems to be the limit enforced by FB's embed SDK (which we use behind the scene). I tested http://www.directlyrics.com/adele-25-complete-album-lyrics-news.html on their playground ( https://developers.facebook.com/docs/plugins/comments ) and setting `Number of Posts` to anything above 100 does not render their widget.

I suggest filing a FR with Facebook. We will update the documentation on our side to reflect this.
