### ISSUE TITLE
amp-analytics facebook additional pageview trigger automatically

### ISSUE THREAD

**Issue by TinyTinyKame** [ampproject/amphtml#22063]
## What's the issue?

When i'm using amp-analytics with facebookpixel vendor, there's always a pageview event that is triggered

## How do we reproduce the issue?

Just use the amp-analytics with facebookpixel vendor, and look at the network, you'll see a call with a pageview event when you are not tracking it and if you are tracking a pageview, then you'll see 2 calls

## What browsers are affected?

I've only tested on chrome and safari but i don't see any requests made for analytics on safari which seems to be a known issue

## Which AMP version is affected?

i'm using this
`<script async src="https://cdn.ampproject.org/v0.js"></script>`
`<script async custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>`

I don't know if i'm using in wrong but it seems like a bug to me.
For now i'm using a custom requests to do the same thing. For what I've seen in this file [facebookpixel.js](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/vendors/facebookpixel.js), there seems to be a pageview trigger that is triggered on initialization.

I hope i'm clear enough on the issue, if not, feel free to ask me any questions.

**Comment by torch2424** [comment]
cc @ampproject/wg-analytics

**Comment by torch2424** [comment]
@TinyTinyKame 

Hello! So I did a quick google search: https://stackoverflow.com/questions/45455167/how-to-add-facebooks-pixel-into-googles-amp

And I think they made a good point, that perhaps using [`<amp-pixel>`](https://amp.dev/documentation/components/amp-pixel) would be a good idea.

There's also some docs on Facebook on how to use their AMP integration: https://www.facebook.com/help/publisher/196055780933623

Let me know if you've already seen this / it doesn't work for you. If not, could you please post the code snippet or AMP page so we can take a look? 👍 

Thank you! 😄

**Comment by TinyTinyKame** [comment]
Hi !

here's the snippet, i'm using pug :
```
amp-analytics(type="facebookpixel" id="facebookpixel")
    script(type="application/json").
      {
        "vars": {
          "pixelId": :PIXEL-ID
        },
        "triggers": {
          "PageView": {
            "on": "visible",
            "request": "pageview"
          }
        }
      }
```

So when you enter any pages, you'll get 2 calls with pageview instead of only one.

As for using `amp-pixel`, didn't see/try it, since i thought `amp-analytics` would have been alright, i'll give it a try. But i think, for my use cases, it won't be me any good, because i'm not only tracking pageviews, i'm also tracking form submission and other stuffs after some user interactions.

For now, i'm using exactly the same configuration found in `facebookpixel.js` without the trigger part, and it works as it should, meaning, only one call is made at the right time.

**Comment by calebcordry** [comment]
@TinyTinyKame The way this works is that the default configuration provided by the vendor (`facebookpixel.js`) is merged with your custom inline configuration. You are correct that the facebook default is already tracking pageviews. 

I am a bit unclear what your end goal is. If you just want the pageview trigger you shouldn't need to add anything inline and the facebook defined trigger will fire once.

**Comment by calebcordry** [comment]
Please let me know if that helps clarify, otherwise happy to answer more questions.

**Comment by lannka** [comment]
@calebcordry is right, the pageview ping is from facebookpixel's default config. you can choose to disable that default ping by adding the following block to your triggers setting,

```
triggers: {
  trackPageview: {
    enabled: false
  }
}
```

closing this bug for now. feel free to reopen if you have any other questions.
