### ISSUE TITLE
Shorten licenses in `v0.js`

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#22076]
We currently have two full-length licenses that are shipped with `v0.js`:

From `third_party/webcomponentsjs/ShadowCSS.js`:

```js
/*

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 Use of this source code is governed by a BSD-style
 license that can be found in the LICENSE file or at
 https://developers.google.com/open-source/licenses/bsd


*/
```

From `node_modules/document-register-element/build/document-register-element.patched.js`:
```js
/*
 Copyright (C) 2014-2016 by Andrea Giammarchi - @WebReflection

Use of this source code is governed by a MIT-style
license that can be found in the LICENSE file or at
https://opensource.org/licenses/MIT.















*/
```

We should probably remove these. **Edit:** We can't because of https://github.com/ampproject/amphtml/issues/22076#issuecomment-488094658

Stretch goal: Remove blank lines while not breaking sourcemaps.

**Comment by jridgewell** [comment]
These are already the shortest licenses that the lawyercats will let us use. See https://github.com/ampproject/amphtml/pull/11589.

**Comment by rsimha** [comment]
Gotcha.

About trimming blank lines, do you think we can eliminate the need for this code...

https://github.com/ampproject/amphtml/blob/f3c72feff5c5e01fdb53e63ce7e3a4d6c47c4540/build-system/compile/shorten-license.js#L22-L31

... by calling `shortenLicense()` on just the two files with the long licenses before compile? (Calling it on all files is a slow O(N^2) operation, so we shouldn't do that).

**Comment by aghassemi** [comment]
@rsimha I think making the static `short` versions be same number of lines as the original would work to eliminate this. this function only runs on license part of the file, so not really sure if perf is an issue here.

**Comment by rsimha** [comment]
I believe I've managed to eliminate blank lines from the licenses without breaking sourcemaps. Sent out #22077 for revie.
