### ISSUE TITLE
Update who is responsible for approving cherry picks

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#22089]
Our [current process for cherry picks](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-picks) says that the "TL/designate" is responsible for approving cherry picks.  After the recent governance change we no longer have a TL, so we should decide who should approve cherry picks.

We required the TL (@cramforce at the time) to approve all cherry picks because (a) they'd be able to consistently apply a high bar for approving cherry picks and (b) people who were trying to get a cherry pick approved would need to justify why the cherry pick is required to someone with a broad view of AMP who it would be difficult pressure into lowering the bar for approving a cherry pick.

A few options:

- The TSC designates someone who can continue to fill this role, e.g. @cramforce.
- We allow cherry picks when at least 3 [Approvers](https://github.com/orgs/ampproject/teams/wg-approvers/members) approve it, similar to our I2I/I2S process.  This is potentially slower, but in true emergencies we'd likely want to roll back rather than cherry pick anyway.
- We allow any one Approver to approve cherry picks.  This is faster than requiring 3 Approvers, but could mean an inconsistent bar is applied.
- The TSC designates some other group with the power to approve cherry picks.

/cc @ampproject/tsc

**Comment by cramforce** [comment]
I've scheduled this as a discussion point for the next regular TSC meeting https://github.com/ampproject/meta-tsc/issues/13

**Comment by cramforce** [comment]
The TSC would like to see the following setup

- Rollback into prod/canary: 1 approver
- Cherry-pick into canary: 1 approver
- Cherry-pick into prod: 1 approver from new group (@cramforce, @dvoytenko, @mrjoro)
