### ISSUE TITLE
Allow passing htmlFormat amp4ads in the gulp package

### ISSUE THREAD

**Issue by renegeuze** [ampproject/amphtml#22088]
## Describe the new feature or change to an existing feature you'd like to see

Allow passing the htmlFormat AMP4ADS to gulp-amphtml-validator.

## Describe alternatives you've considered

I'm currently just using my own "fork"(read copy-paste) that includes this feature.
Also instead of just passing htmlFormat it could be an object of settings just in case it ever becomes relevant.

## Additional context

Required changes:
https://github.com/ampproject/amphtml/blob/master/validator/gulpjs/index.js:38
`module.exports.validate = function(validator) {` => `module.exports.validate = function(validator, htmlFormat) {`

https://github.com/ampproject/amphtml/blob/master/validator/gulpjs/index.js:57
`validatorInstance.validateString(inputString);` => `validatorInstance.validateString(inputString, htmlFormat);`

**Comment by honeybadgerdontcare** [comment]
@renegeuze we'd welcome a PR to add this feature, but we would want it to be backward compatible such that if a htmlformat is not passed in validate would treat is at AMP.

**Comment by honeybadgerdontcare** [comment]
If someone has a PR to make this happen we'd love to review it. Until then we're closing this issue.
