### ISSUE TITLE
Staying up-to-date with AMP Development

### ISSUE THREAD

**Issue by mjangda** [ampproject/amphtml#2208]
Not really an issue, but more of a question / point of discussion.

With the pace at which AMP is being developed, it's pretty hard to keep up with changes. Has there been any discussion on posting regular updates that cover addition of new components, updates to existing to existing components, breaking spec/validator changes, etc.? Maybe a `(weekly|bi-weekly|monthly)` round-up post of the most interesting changes?

**Comment by rudygalfi** [comment]
Yes that's a great suggestion. Let me follow up with validator folks on how easy it is to do reporting on that area and see what's reasonable. For components, I think it's definitely possible to have a changelog.

**Comment by archiebrooks19** [comment]
Hey, 

Couple ideas from the DailyMail / MailOnline tech team:

1.	Give us 1 week notice of any changes going to PROD via email
2.	Confirm the changes with a change log 
3.	Provide us with a “Canary” or “Pre-Prod” environment so we can review changes (like a simulator – with the carousel)
4.     Package all updates/commits into one bundle
5.     Release them on a fixed frequency (weekly/biweekly) after a week on staging.

**Comment by cramforce** [comment]
@archiebrooks19 This is pretty much exactly the plan (and what we did in the months leading up to launch). Frequency just went up in the days leading up to the launch.

You are likely familiar with https://github.com/ampproject/amphtml/releases
You can already subscribe to those changes by setting up a respective email filter as new releases automatically trigger an email.
https://groups.google.com/forum/#!forum/amphtml-announce is the place to hear about breaking changes. We will not post regular release notices to that list. It is meant for super low volume announcements.

**Comment by cramforce** [comment]
And just making sure you saw https://github.com/ampproject/amphtml#amp-dev-channel

**Comment by rudygalfi** [comment]
@mjangda Check out this release notes draft: https://github.com/ampproject/amphtml/releases/tag/1457112743399.

Something new we're doing there is to group updates by component -- and you can also see a bunch of validator-related changes. Is this format useful? Would you suggest anything else?

/cc @erwinmombay

**Comment by Meggin** [comment]
This makes it trickier, but for sure more valuable-- call out new, updated,
and deprecated tags and attributes within tags.

Meggin

**Comment by Gregable** [comment]
My latest validator roll up PR tried to spell this out a bit clearer. You can click through from @erwinmombay's draft, the actual text is here: https://github.com/ampproject/amphtml/pull/2401

It would be good to figure out the best way to include these in our release draft too. Happy to help sort this out.

**Comment by Meggin** [comment]
Greg-- good stuff. That helps a good bit on validation side. And it would
also be cool to see this on tag/attribute side.

**Comment by erwinmombay** [comment]
@Gregable sweet, i can definitely consume that Pull Request body for validators.

**Comment by mjangda** [comment]
The releases look great and will be super helpful.

> You can already subscribe to those changes by setting up a respective email filter as new releases automatically trigger an email.

Could we add some sort of unique string across all the release notes to make them more easily filterable? (Or is there a specific string we can search for already?)

**Comment by rudygalfi** [comment]
some of the common boilerplate in the notes like "breakdown by component" should help separate releases from other issues
