### ISSUE TITLE
AMP Story bookend "get link" & "line" are buggy

### ISSUE THREAD

**Issue by TWsky** [ampproject/amphtml#22099]
## What's the issue?
![Screenshot_20190502-175651](https://user-images.githubusercontent.com/4546841/57068261-c9d4b280-6d03-11e9-931b-d65c015666ad.png)
As above screenshot the "Get link" doesn't work on mobile, and the "Line" share button miss it's caption.

## How do we reproduce the issue?

1. Use mobile to open this [url](https://graphics.tvbs.com.tw/amp_stories/greenland/greenland.html) and click to the end page.

## What browsers are affected?
Chrome 73.0.3683

## Which AMP version is affected?
Version 1904301721170

**Comment by torch2424** [comment]
Triaging to @newmuis , feel free to re-assign 😄

**Comment by newmuis** [comment]
Label for Line was added in #22639.

Let's use #17023 to track issues with the "Get Link" button.
