### ISSUE TITLE
Unable to reference amp-bind-macro ID from JSON

### ISSUE THREAD

**Issue by MkVII** [ampproject/amphtml#22098]
Hi.

I'm trying to reference an amp-bind-macro expression (I need to use different amp-bind-expressions depending on user inputs) using JSON format.

Trouble is, when I try to reference them, it doesn't execute the expression. In the console it says syntax error. No matter what I try I can't get it working.

Here's an example of the code I'm trying to implement:

<amp-bind-macro id="exampleMacro" arguments="input" expression="8*input"></amp-bind-macro>

<amp-state id="exampleJson">
<script type="application/json">
 { "test": "exampleMacro" }
</script>
</amp-state>

<span [text]="exampleJson.test(input)">0.0</span>

I've also asked this question on StackOverFlow.
https://stackoverflow.com/questions/55949362/reference-amp-bind-macro-ids-to-execute-expression

Any help would be much appreciated. Thanks

**Comment by choumx** [comment]
Replied on SO. 

As the example in the documentation link shows, amp-bind-macro can only be referenced by id in amp-bind expressions. E.g.

```html
<span [text]="exampleMacro()">0.0</span>
```

**Comment by torch2424** [comment]
Triaging to @choumx , feel free to re-assign 😄
