### ISSUE TITLE
AMP4EMAIL: Allow binding to amp-list[src]

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#22105]
Copied from https://github.com/ampproject/wg-amp4email/issues/1.

**Comment by fstanis** [comment]
While not exactly a replacement, [Advanced Server Request](https://amp.dev/documentation/examples/interactivity-dynamic-content/advanced_server_request/?format=email) shows how binding to a hidden `amp-form` field can be used to achieve a similar effect.
