### ISSUE TITLE
in.com | amp bench validator issue

### ISSUE THREAD

**Issue by sagart30** [ampproject/amphtml#22103]
We have same type of server side setting for all properties (in.com, Firstpost, News18, etc).
but still we are getting fail status in amp bench tool for logo and article image.

Please share logs or error for Googlebot for reference if you can

Please find attached screenshots

## How do we reproduce the issue?

https://ampbench.appspot.com/validate?url=https%3A%2F%2Fwww.in.com%2Fentertainment%2Fbollywood%2Fthe-hook-up-song-from-soty-2-tiger-shroff-and-alia-bhatt-get-groovy-in-style-392213.htm%2Famp

## What browsers are affected?
All Browsers

## Which AMP version is affected?
0.1
![1](https://user-images.githubusercontent.com/17844989/57072501-8ece8100-6cfb-11e9-9d54-d7b8b2dea245.JPG)

![2](https://user-images.githubusercontent.com/17844989/57072515-9e4dca00-6cfb-11e9-96d0-6edaa63d64dc.JPG)

**Comment by torch2424** [comment]
cc @sebastianbenz Perhaps you can help here? 🤔

**Comment by sebastianbenz** [comment]
adding @ithinkihaveacat who's currently maintaining amp bench.

**Comment by ithinkihaveacat** [comment]
Thanks for the report. This appears to be a bug in ampbench; there doesn't seem to be any issues with the pages themselves. I've created a bug report for ampbench at https://github.com/ampproject/ampbench/issues/115.

**Comment by torch2424** [comment]
Thanks @ithinkihaveacat ! 😄 

@sagart30 

I'll go ahead and close this issue, please feel free to continue this on the issue opened by @ithinkihaveacat , or if you have more concenrs feel this issue should still be open, feel free to re-open 😄 

Thanks everyone! 😄
