### ISSUE TITLE
amp-story JS error "Cannot read property 'checked' of null" when clicking on "get link" button

### ISSUE THREAD

**Issue by toruhjp** [ampproject/amphtml#22106]
# amp-story JS error "Cannot read property 'checked' of null" when clicking on "get link" button

## Evidences

![clicking_on_get_link](https://user-images.githubusercontent.com/11867257/57085037-62842600-6d36-11e9-9e1d-25a245287452.png)
![the_line](https://user-images.githubusercontent.com/11867257/57085046-6617ad00-6d36-11e9-81d5-7ea22bfdccbc.png)

## What's the issue?

Impossible to get and copy URL when clicking on "get link" button

## How do we reproduce the issue?

1. Implement and deploy a bookend json according to https://amp.dev/documentation/guides-and-tutorials/start/visual_story/create_bookend
2. Click or tap on "get link" button with opening Chrome developer console
3. You will see the error in console

## What browsers are affected?

Win 10, Chrome 73.0.3683.103

## Which AMP version is affected?

1904262212040

## Optional information

Referring to https://github.com/ampproject/wg-stories/issues/6#issuecomment-477842336 , I submit this issue here, not in wg-stories.
And if the issue is the duplicated one, I'm sorry!
I tried to find it but I couldn't!

**Comment by torch2424** [comment]
Triaging to @newmuis , Feel free to re-assign 😄
