### ISSUE TITLE
🌸 Cherry-pick request for #21902 into #1904262212040 (Pending)

### ISSUE THREAD

**Issue by prateekbh** [ampproject/amphtml#22113]
# Cherry-pick request

| Issue | PR  | Production? | RC? | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---: | :-: | :---------: | :-: | :-----------: |
| #21902 | #21976  | **YES** | **YES** | #21958 |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?
#21902 is affecting production traffic for https://rep.repubblica.it.
They are observing errors due to hidden observables introduced in PR#21687

# Mini-postmortem

## Summary
One of our partners (rep.republica.com) tried loading two AMP documents using the shadow runtime.
This lead to a race condition of which document is loaded first. The document loading second was not able to render an amp-list element, which was blocked on amp-bind eval. The eval failed since the web worker only supports one document with amp-bind per window.

| Users affected | Impact |
| -------------- | ------ |
| Users of rep.republica.com were affected | Partial loss of functionality as the page was unable to show followers and comments count on the article |
## Root Causes
- #21763 was merged, which causes an amp-list/amp-bind interaction to fail if amp-bind itself fails to initialize.
- The affected page has two shadow AMP docs: (1) the main article and (2) a subscriptions widget in the top right corner. 
- Both of these shadow docs use amp-bind, but amp-bind's worker is only scoped to support 1 doc per window. This is the cause of the worker console error -- the second doc's amp-bind initialization always fails.
- So the race is actually "which page gets initialized first". If the article doc happens to be initialized after the subscriptions, then the initialization promise never resolves. 
- This means amp-list render gets stuck waiting for amp-bind to rescan.

## Action Items
| Action Item | Type | Owner | PR # |
| ----------- | :--: | :---: | :--: |
| Support multiple docs per window in web worker | Prevent | @choumx | TODO(choumx) |
| Add test for "double shadow doc" scenario | Prevent | @choumx | TODO(choumx) |
| Make x-extension APIs (amp-list/amp-bind) more resilient  | Mitigate | @choumx | TODO(choumx) |
| Fix error logging in web worker  | Mitigate | @choumx | TODO(choumx) |

## Lessons Learned
- We need better testing infra around AMP shadow runtime.
- We need better tools for contributors of AMP project to make sure their code doesn't only work in main runtime but also specialized runtimes.

### Things that went well
- Since AMP shadow runtime are not valid AMP documents, the publisher could pin their shadow documents to a particular version and continue their operations.

### Things that went wrong
- This issue was hard to debug and took over a week to find the root cause.

---

/cc @cramforce

**Comment by cramforce** [comment]
Approved

**Comment by rsimha** [comment]
This went out last week with https://github.com/ampproject/amphtml/releases/tag/1905021827420. Closing.

**Comment by choumx** [comment]
Reopening since the PM is unfinished.

**Comment by prateekbh** [comment]
@choumx can we close this now?
