### ISSUE TITLE
Intent to Implement: WebEngage

### ISSUE THREAD

**Issue by ayushgupta29** [ampproject/amphtml#22124]
We at [WebEngage](https://webengage.com/) would love to add our platform as an amp-analytics plugin, we already created a new API which supports query string and have everything ready with us.

A simple example that sends us a pageview:

```
<amp-analytics id="webengage-amp-analytics" >
    <script type="application/json">
    {
      "vars": {
        "licenseCode": "~134105385"
      },
      "requests": {
        "base": "https://c.webengage.com/amp?licenseCode=${licenseCode}&luid=${clientId(we_luid)}&pageUrl=${canonicalUrl}&pageTitle=${title}&referrer=${documentReferrer}&vh=${viewportHeight}&vw=${viewportWidth}",
        "we_amp_pageview_request": {
            "baseUrl": "${base}&eventName=Page Viewed&category=application"
        }
      },
      "triggers": {
        "we_amp_pageview": {
            "on": "visible",
            "request": "we_amp_pageview_request"
        }
      }
    }
    </script>
  </amp-analytics>
```

we would ask our customers to add more triggers/request if they need to send us any other amp-analytics supported events.

Do let us know feedback/issue if any, before I open a PR.

**Comment by lannka** [comment]
@ayushgupta29 you're welcome to add a `<amp-analytics type="webengage">` support. please refer to our integration [guideline](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/integrating-analytics.md).

you can ping @ampproject/wg-analytics once have your PR ready.
