### ISSUE TITLE
Clearer documentation for amp-geo self hosting

### ISSUE THREAD

**Issue by indieisaconcept** [ampproject/amphtml#22123]
Hi amphtml team,

I've reviewed the documentation for amp-geo self-hosting & there is very little detail on the subject other than implementation concerns to be aware of when serving the file to end users. 

> Publishers and caches that re-host AMP JavaScript files must implement server-side patching of the amp-geo-0.1.js file or pre-rendering (see above).

So it's not clear what caveats there are or if there is more configuration required in-order to support this.

For context I'm reviewing this from a publisher perspective for the purpose of self hosting amp-geo to maintain parity with how our origin server determines a users locale once served from an amp cache. I'm not looking to implement an amp cache.

I have this working as expected ( i.e locale is correctly substituted ) & content updated accordingly but validation fails due to `CUSTOM_JAVASCRIPT_NOT_ALLOWED`.

Due to the above I believe there needs to be more detail on self hosting in-order for publishers to understand possible limitations / configuration concerns etc.

Thanks.

**Comment by jpettitt** [comment]
`amp-geo` self hosting refers to the case where a publisher chooses to create a non-valid amp page by hosting all the AMP js files on their own server.  If you do this you have to replicate the 'hot patch' at serving time that inserts the country code into `amp-geo`.

If you just want to set the country on the server, but maintain valid AMP, a better way to go is to add the geo classes to the `body` when it's rendered on the server.  `amp-geo` will respect the geo class you add unless it's running on a cache where it will override the classes you set in favor of the ones it determines for the users IP.

**Comment by indieisaconcept** [comment]
@jpettitt thank-you for your input I see that you added the initial documentation for `amp-geo` & self-hosting in #14780.

I think there would be value for the community if there was more detail in relation to self-hosting beyond `apm-geo` which outlined caveats such as validation as there seems to be very little on the [subject](https://github.com/ampproject/amphtml/search?q=%22self+hosting%22&unscoped_q=%22self+hosting%22&type=Issues) & it's only mentioned in passing in `amp-geo`.

The more I think about it this is less of an `amp-geo` specific issue & more a self-hosted documentation issue.

As for my use-case with self-hosted `amp-geo` I was experimenting to see if it where possible to support extending geo detection to be far more granular than country, eg: supporting regional levels. I was actually able to get this working & have it pass amp validation & cache correctly though that did expose a different issue to solve ( if your interested see https://amp-geo.expt.dev ).

**Comment by jpettitt** [comment]
See https://github.com/ampproject/amp-toolbox/tree/master/packages/optimizer

**Comment by jpettitt** [comment]
See also https://docs.google.com/document/d/1oqnjA5KcUP7bHpz_HCtUTBH2jiqry65zGrpAUie1tHw/
