### ISSUE TITLE
Galaxy s10 problem using google chrome

### ISSUE THREAD

**Issue by JamesRoitberg** [ampproject/amphtml#22120]
## What's the issue?

We have been reported a bug on this url: 
https://esporte.uol.com.br/amp-stories/os-10-mais-bem-pagos-do-futebol-brasileiro/index.htm,
In this case this don't open in the galaxy s9 and s10 using chrome browser (version 73.0.3683.90) android 9. 
We found also that the same bug occurs using some of your demo stories, as we mention in the step below

## How do we reproduce the issue?

1. https://expansion.mx/ampstories/2018/12/12/nueve-hoteles-para-dormir-antes-de-morir
2. https://edition.cnn.com/ampstories/world/monarchies-around-the-world
3. https://esporte.uol.com.br/amp-stories/os-10-mais-bem-pagos-do-futebol-brasileiro/index.htm

## What browsers are affected?

Just on google chrome (73.0.3683.90) android 9

## Which AMP version is affected?

amp-story-1.0.js

**Comment by torch2424** [comment]
Triaging to @newmuis , Feel free to re-assign 😄
