### ISSUE TITLE
amp-video-iframe in chrome throws DOMContent exception when attempting play

### ISSUE THREAD

**Issue by justinph** [ampproject/amphtml#22122]
## What's the issue?

When using `amp-video-iframe` in Chrome with a custom video player and attempting to instruct the video to play from a user action, Chrome will throw a `DOMContent` exception and the video will not play. The exception message is `play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD` [link](https://goo.gl/xX8pDD) In these cases, the video will load behind the scenes, but playback will not be allowed to start.

I've tried numerous things to get this to work, including making sure all the amp-video-iframe communication events were correctly wired. I have sometimes observed it working correctly, but not consistently. It is difficult to determine what is going given the complexities of iframe security, cross domain issues, and video autoplay policies.  

## How do we reproduce the issue?

1. Use Google Chrome
2. Visit one of the following URLs:
   - https://direct.fiddlyio.com/misc/amp/index.html
       - player: https://static01.nyt.com/video-static/amp-player/amp-video-iframe-debug/player.html?id=100000002883899
   - https://direct.fiddlyio.com/misc/amp/player-no-api-no-ads.html
        - player: https://static01.nyt.com/video-static/amp-player/amp-video-iframe-debug/player-no-api-no-ads.html
3. Give the frame a moment to load, then click the play button above the video.
4. Observe the console eventually throw a DOMContent exception.

Note the latter URL uses a simpler iframe video that does not execute XHR requests to get the video info, so it should play much quickier. The video player in question is the NYTimes video player; I've put the hosting amp pages on a different domain to simulate the cross-domain issues we'd see when a page is hosted through the google amp CDN.

## What browsers are affected?

This only affects Chrome. Tested in v74 on MacOS.

## Which AMP version is affected?

Observed in 1905021827420

**Comment by aghassemi** [comment]
@alanorozco This is due to Chrome UserActivation and `allow=autoplay` stuff. Given UAv2 is not making it to Chrome 75, I am thinking to take a whole different approach here:

Although we can't add `allow=autoplay` like we did for a few other video players, what we can do is: "When VideoManager receives a `play` or other actions call, if the event behind it is High-Trust, then it will be safe enough to add `allow=autoplay` to the iframe and then send the message to it" WDYT?

**Comment by alanorozco** [comment]
@aghassemi That could work, I'll give it a shot.

**Comment by justinph** [comment]
Thanks for jumping on this. Let me know if there's anything I can do to assist.

**Comment by aghassemi** [comment]
@mustaqahmed FYI
