### ISSUE TITLE
Adaptive bandwidth handling in STAMP

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#22127]
Just an idea:

If we notice that images haven't fully loaded when the user tabs to a next page N times (N = 1-2?), could we for future images that we load switch to a lower-res srcset value (assuming that is present)?

**Comment by newmuis** [comment]
Good idea!  One thing that's suboptimal is that we can't tell the filesize of the image without initiating the fetch for it.  So, for example, if the image that is loading slowly is a 4K image (which has actually happened), later images that might be smaller will still get downsampled.

**Comment by cramforce** [comment]
At least on the AMP cache, you should never see a 4K image, because of the automatic srcset generation. I think it is fair to assume that if a slow-loading image used a srcset, that it provided a reasonable amount of pixels for the respective screen.
