### ISSUE TITLE
guard against empty carousels

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#2213]
see http://blog.sfgate.com/sfmoms/2016/02/22/obamaandkids-clark-reynolds-president-obama/amp/

**Comment by rudygalfi** [comment]
What's going on there? It looks like the children are `<div>`s? Is there a reason it doesn't render anything?

**Comment by mkhatib** [comment]
@erwinmombay it doesn't seem the carousel empty in source. So might be something else is happening.

**Comment by erwinmombay** [comment]
@rudygalfi @mkhatib we have extra elements there that we append ourselves for the controls etc. they actually don't have any elements if you do a `view-soruce` (not element inspector)

**Comment by cramforce** [comment]
Now I see stuff in the source as well.

**Comment by erwinmombay** [comment]
this is probably caused by unclosed `span` tag

**Comment by erwinmombay** [comment]
sorry, i actually meant. this is the whole `div` nested in a `p` issue again

**Comment by erwinmombay** [comment]
see: <img width="1096" alt="screen shot 2016-02-22 at 5 04 57 pm" src="https://cloud.githubusercontent.com/assets/354746/13238249/71080e2c-d986-11e5-8667-2eb5a83e0c0b.png">

**Comment by cramforce** [comment]
@rudygalfi Can you contact SFGate?

**Comment by erwinmombay** [comment]
adding addt'l context and info:
http://stackoverflow.com/questions/8397852/why-p-tag-cant-contain-div-tag-inside-it

reductions:
http://jsbin.com/sututocevi/edit?html,css,js,output
http://jsbin.com/funasayiqa/edit?html,output
