### ISSUE TITLE
Trouble Whitelisting amp@gmail.dev

### ISSUE THREAD

**Issue by orionhashax** [ampproject/amphtml#22139]
Hi Amp team. I am an email developer and I have been attempting to create amp emails in the amp playground tool here: https://amp.gmail.dev/playground/. While my clients have been successful in enabling dynamic email content, I have been unable to in my personal gmail. Any idea on why I keep getting sent the html version? I went in and whitelisted amp@gmail.dev in Gmail Settings > General > Dynamic email > Dynamic email development. Any help on this would be greatly appreciated!!!

**Comment by choumx** [comment]
This is a better question for Gmail support forums. We'll keep an eye on these similar reports though.

/cc @johnbarr
