### ISSUE TITLE
amp-img: Vague "failed to load" error without src

### ISSUE THREAD

**Issue by Meai** [ampproject/amphtml#22143]
## What's the issue?
Adding some tags suddenly causes an error that doesnt have any message in it. This is caused by empty img src tags loaded from a test.json, however I get no message indicating this.

## How do we reproduce the issue?

1. Host this on localhost with python3 -m http.server
2. on pageload it will show a generic "Failed to load: http://localhost:8000/amp-index.html​​​"

## Unacceptable workaround: 
1. Remove the amp-img tag from the provided .html or add valid urls to the "img" key value pair in the test.json
2. Suddenly no error

## Wish

Provide a descriptive error, if there is a loading error of some kind then tell me why it was loading what and why it failed.

## What browsers are affected?
*Only* Chrome 74
Tested: Firefox 67, Edge

## Which AMP version is affected?
see zip

Powered by AMP ⚡ HTML – Version 1905021827420

[amp.zip](https://github.com/ampproject/amphtml/files/3144099/amp.zip)

**Comment by choumx** [comment]
This is caused by the amp-img initialization failing:
https://github.com/ampproject/amphtml/blob/d0744039025fb5a31fc53b86f660985dbce3f687/src/event-helper.js#L204-L212

Introduced by #4800. `target.src` appears to be the current document URL if `src` attribute is empty string.

**Comment by wassgha** [comment]
Claiming for Rebecca
/cc @nainar
