### ISSUE TITLE
[Search Console] "Linked AMP version is invalid" for a valid page

### ISSUE THREAD

**Issue by thinkdifferent** [ampproject/amphtml#22152]
In Google Search Console we are getting "Linked AMP version is invalid" error.

Page is: 
https://www.ilmeteo.it/notizie/meteo-diretta-video-le-previsioni-per-sabato-4-maggio

which has a (valid) amp page: 
https://www.ilmeteo.it/notizie/meteo-diretta-video-le-previsioni-per-sabato-4-maggio/amp

We used the right canonical and amphtml tags.

What is missing?

**Comment by torch2424** [comment]
cc @sebastianbenz Could you triage this? 😄

**Comment by sebastianbenz** [comment]
Everything looks OK now. Is it possible that you accidentally broke something around 6 days ago, which is now reverted?

It works on the cache: https://www-ilmeteo-it.cdn.ampproject.org/c/s/www.ilmeteo.it/notizie/meteo-diretta-video-le-previsioni-per-sabato-4-maggio/amp.

Google AMP Tester accepts it as well: https://search.google.com/test/amp?id=iclC3L72eu7fVd_krqnSDw

Google search for 'meteo-diretta-video-le-previsioni-per-sabato-4-maggio' only shows the AMP version, which is weird: https://www.google.com/search?q=meteo-diretta-video-le-previsioni-per-sabato-4-maggio&rlz=1C5CHFA_enDE843DE843&oq=meteo-diretta-video-le-previsioni-per-sabato-4-maggio&aqs=chrome..69i57j69i60l2.27j0j7&sourceid=chrome&ie=UTF-8

=> index still contains an outdated version from 6 days ago which appears to be the wrong version

Sidenote: Github is not the best place to ask questions like this. Next time, please use either Stackoverflow using the `amp-html` tag or the Google product forums.
