### ISSUE TITLE
amp-analytics click tracking with dynamic data-var-* attributes only shows info of the first selected element

### ISSUE THREAD

**Issue by xiao-lix** [ampproject/amphtml#22156]
## What's the issue?

I'm using amp-analytics to track data sending to my own end point. I need to track which button or link the user clicked by adding data-vars-* attribute for the elements, but it turns out that the result only shows the first element's info I clicked on. Thus it depends on which element I clicked first, my endpoint will receive all other clicked elements the same value of the first one.

## How do we reproduce the issue?

For example I have multiple elements that can have click action, for any click I want to trigger a pageAction event.

HTML:

      <button class="trackedAction" data-vars-event-category="page button" data-vars-event-action="toggle article" data-vars-event-label="Show/Hide Article">a button</button>

      <amp-carousel ...>
          <amp-img ... class="trackedAction" data-vars-event-category="image" data-vars-event-action="./img-01" data-vars-event-label="img-01"></amp-img>
          <amp-img ... class="trackedAction" data-vars-event-category="image" data-vars-event-action="./img-02" data-vars-event-label="img-02"></amp-img>
          <amp-img ... class="trackedAction" data-vars-event-category="image" data-vars-event-action="./img-03" data-vars-event-label="img-03"></amp-img>
      </amp-carousel>

      <form ...
        data-vars-event-action="https://ampbyexample.com/components/amp-form/submit-form-input-text-xhr">
          <input ...
           class="trackedAction" data-vars-event-category="input" data-vars-event-action="input" data-vars-event-label="form input">
          <input ...
           class="trackedAction" data-vars-event-category="input" data-vars-event-action="input" data-vars-event-label="form input">
          <input ... class="trackedAction" data-vars-event-category="submit" data-vars-event-action="submit" data-vars-event-label="form submit">
      </form>

As indicated from the code, I have multiple elements grouped in class "trackedAction", but when I trigger the event with click, the result only shows the first element's info. Eg. If I click img-01 first, every other elements show the same event category, event action, event label the same as img-01.

amp-analytics:
```
 <amp-analytics config="...">
      <script type="application/json">
        {
          ...
          "triggers": {
            "trackPageAction": {
              "on": "click",
              "selector": ".trackedAction",
              "request": "event"
            }
          }
        }
      </script>
 </amp-analytics>
```
I tried to set the "selector" as "*", it gave me the same result. Any idea why this happens? thanks.

## Which AMP version is affected?

Version 1905021827420

**Comment by xiao-lix** [comment]
Hi, just want to follow up on my question and provide some more details. I'm sending data to my own endpoint, and I wrote a configuration JSON file, all requests are POST. I tried to update to GET requests, and the problem I mentioned above is gone. Is the format to config for GET and POST request different? Thanks.

**Comment by zhouyx** [comment]
@xiao-lix  Thank you for reporting. This sounds like a bug to me. We will take a look. When you say the issue goes away after switching from POST to GET. Could you please provide us with the configuration change. Thank you. cc @ampproject/wg-analytics

**Comment by xiao-lix** [comment]
@zhouyx sure, the config files are basically identical. Here's the config file:

**POST**
```
{
  "requests": {
    "event": "<URL>"
  },
  "triggers": {
    "trackPageAction": {
      "extraUrlParams": {
          "eventCategory": "${eventCategory}",
          "eventAction": "${eventAction}",
          "eventLabel": "${eventLabel}"
        }
      } 
  },
  "transport": {
    "beacon": true,
    "xhrpost": true,
    "image": false,
    "useBody": true
  }
}
```
**User's side**
```
    <amp-analytics config="//localhost:..post.json">
      <script type="application/json">
        {
          "vars": {
            <required account Id>
          },
          "triggers": {
            "trackPageAction": {
              "on": "click",
              "selector": ".trackedAction, .menu-link", // suppose I have multiple elements to track click on
              "request": "event",
              "vars": {
                "eventCategory": "${eventCategory}",
                "eventLabel": "${eventLabel}",
                "eventAction": "${eventAction}"
              }
            }
          }
        }
      </script>
    </amp-analytics>
```
**GET**
```
{
  "requests": {
      "pageAction": "<URL>"
  },
  "triggers": {
    "trackPageAction": {
      "extraUrlParams": {
        "eventCategory": "${eventCategory}",
        "eventAction": "${eventAction}",
        "eventLabel": "${eventLabel}"
      }
    }
  },
  "transport": {
    "beacon": false,
    "xhrpost": false,
    "image": true
  }
}
```
**User's side**
```
<amp-analytics config="//localhost:...get.json">
      <script type="application/json">
        {
          "vars": {
            <required account Id>
          },
          "triggers": {
            "trackPageAction": {
              "on": "click",
              "selector": ".trackedAction, .menu-link",
              "request": "pageAction",
              "vars": {
                "eventCategory": "${eventCategory}",
                "eventLabel": "${eventLabel}",
                "eventAction": "${eventAction}"
              }
            }
          }
        }
      </script>
    </amp-analytics>
```
Please let me know if you need other info. Thanks.

**Comment by zhouyx** [comment]
@xiao-lix So I tested locally with both GET and POST. But couldn't reproduce the error that you described. 

This is the page I am testing with. https://gist.github.com/zhouyx/bfff166992f6a6f59dc05153bab92add

You have a test page that I can reproduce the issue? That will be very helpful.

**Comment by xiao-lix** [comment]
@zhouyx Thanks for your time solving this, I checked your test and found it was my mistake put eventCategory under "vars" instead of "extraUrlParams". I close this issue. Thanks for your help. Do you mind telling me the difference of these two or is there a link for this? Thanks.

**Comment by zhouyx** [comment]
Hello @xiao-lix, I tested with 'vars' again, and it still work. Please see my test page
https://gist.github.com/zhouyx/3751202548634f18f56391cf24830d72

As for the difference between 'vars' and 'extraUrlParams'. AMP automatically append params from 'extraUrlParams' to the outgoing link. So you could have 
```
request: example.com,
extraUrlParam {
  a: 1
}
```
And the outgoing request will be `example.com&a=1`. 

However, with vars, you'll need to manually append the variable to the url. For example 
```
request: example.com&a=${a},
extraUrlParam {
  a: 1
}
```
And the outgoing request will then be `example.com&a=1`

**Comment by xiao-lix** [comment]
@zhouyx Hi thank you very much for your time, it makes sense to me now. I mistakenly confused them two.  I used var on client side and extraUrlParams on json config file that's why it didn't work. You are right, they both work fine. 👍

**Comment by xiao-lix** [comment]
@zhouyx hey, I have a question about "extraUrlParam" field. Can I nest data in it? The scenario is, my end service only accept extra customer data under "data" bag, but when I nest it like this: 
```
extraUrlParam {
   data: {
       eventCategory: ${eventCategory}
   }
}
```
the same error happens.. only the first click display the correct info, the following clicks will all display the same info as the first click. I tried on your test page too, but the response is like this:

```
data: [object Object]
```
 Does extraUrlParam only accept one layer? 
Thanks!

**Comment by zhouyx** [comment]
Hello @xiao-lix 
We don't support serializing nested object in POST request. However if you use the `useBody: true` https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md#use-body-for-extra-url-params, nested object is supported. Please let me know if that answer your question, thank you
