### ISSUE TITLE
Sidebar open animation randomly skipped

### ISSUE THREAD

**Issue by auxsoft** [ampproject/amphtml#22150]
I think a recent change was made that makes the sidebar animation work erratically. Sometimes it opens smoothly but other times the open animation seems to be entirely skipped. 

Apart from mine, I tried other amp sites and I can see they have the same problem. 

This happens to me on desktop, Android and iOS.

AMP Version 1905021827420

![amp-sidebar-animation (2)](https://user-images.githubusercontent.com/2872204/57230742-6bebe780-6fef-11e9-82b2-ffcd95b4e380.gif)

**Comment by nainar** [comment]
Random URL that I see this happening on: 

https://deadline.com/2019/05/james-gunn-guardians-of-the-galaxy-suicide-squad-offensive-tweets-interview-news-1202610248/amp/

(Can repro on Desktop and Android)

**Comment by sparhami** [comment]
Will take a look. For a bit of context, I did a previous change, #16831, to attempt to address some issues with open/close.
