### ISSUE TITLE
outbrain support

### ISSUE THREAD

**Issue by obeyer** [ampproject/amphtml#2216]
the doc here says you have it: https://github.com/ampproject/amphtml/blob/325878c6bde7a4bd40d67e8c81b9e599af1039d7/ads/integration-guide.md
but the doc here is NOT listing it as supported type https://github.com/ampproject/amphtml/blob/master/builtins/amp-embed.md
and, if included on the page, the error is given: 
Uncaught Error: Embed type outbrain not allowed with tag AMP-EMBED​​​

**Comment by cramforce** [comment]
The doc you are referencing is a guide for outbrain how to make it work. We are working with them to get them into this framework.

**Comment by obeyer** [comment]
thank you for your quick response. do you have a time frame for when it will be done?

**Comment by cramforce** [comment]
That is entirely up to outbrain. Probably best to contact them.

**Comment by AmitErental** [comment]
Hi Olena, please see the link below for  details on adding Outbrain widget to your AMP pages. Your Outbrain account manager will be happy to assist with any question as well.

http://www.outbrain.com/blog/2016/01/making-the-mobile-web-a-better-place-outbrain-and-google-amp.html

**Comment by obeyer** [comment]
Hi AmitErental, I was able to implement the widget, using the code sample from the blogpost. Thank you very much.
However, it keeps infinitely growing, adding white space, with just 4 initial posts at the top and the console is full of this:
amp.html:245 xxxxxxxxxxxxxxxxx-> send height
amp.html:258 xxxxxxxxxxxxxxxxx-> make massage:
amp.html:259 Object {sentinel: "amp", type: "embed-size", height: 4409}
amp.html:267 xxxxxxxxxxxxxxxxx->  Send message
amp.html:245 xxxxxxxxxxxxxxxxx-> send height
amp.html:258 xxxxxxxxxxxxxxxxx-> make massage:
amp.html:259 Object {sentinel: "amp", type: "embed-size", height: 4449}
amp.html:267 xxxxxxxxxxxxxxxxx->  Send message
amp.html:245 xxxxxxxxxxxxxxxxx-> send height
amp.html:258 xxxxxxxxxxxxxxxxx-> make massage:
amp.html:259 Object {sentinel: "amp", type: "embed-size", height: 4489}
amp.html:267 xxxxxxxxxxxxxxxxx->  Send message
amp.html:245 xxxxxxxxxxxxxxxxx-> send height
amp.html:258 xxxxxxxxxxxxxxxxx-> make massage:
amp.html:259 Object {sentinel: "amp", type: "embed-size", height: 4529}
amp.html:267 xxxxxxxxxxxxxxxxx->  Send message
amp.html:245 xxxxxxxxxxxxxxxxx-> send height
amp.html:258 xxxxxxxxxxxxxxxxx-> make massage:
amp.html:259 Object {sentinel: "amp", type: "embed-size", height: 4569}
amp.html:267 xxxxxxxxxxxxxxxxx->  Send message
amp.html:245 xxxxxxxxxxxxxxxxx-> send height
amp.html:258 xxxxxxxxxxxxxxxxx-> make massage:
amp.html:259 Object {sentinel: "amp", type: "embed-size", height: 4609}
amp.html:267 xxxxxxxxxxxxxxxxx->  Send message
amp.html:245 xxxxxxxxxxxxxxxxx-> send height
amp.html:258 xxxxxxxxxxxxxxxxx-> make massage:
amp.html:259 Object {sentinel: "amp", type: "embed-size", height: 4649}
amp.html:267 xxxxxxxxxxxxxxxxx->  Send message
amp.html:245 xxxxxxxxxxxxxxxxx-> send height
amp.html:258 xxxxxxxxxxxxxxxxx-> make massage:
amp.html:259 Object {sentinel: "amp", type: "embed-size", height: 4689}
amp.html:267 xxxxxxxxxxxxxxxxx->  Send message
amp.html:245 xxxxxxxxxxxxxxxxx-> send height
amp.html:258 xxxxxxxxxxxxxxxxx-> make massage:
amp.html:259 Object {sentinel: "amp", type: "embed-size", height: 4729}
amp.html:267 xxxxxxxxxxxxxxxxx->  Send message
amp.html:245 xxxxxxxxxxxxxxxxx-> send height
amp.html:258 xxxxxxxxxxxxxxxxx-> make massage:
amp.html:259 Object {sentinel: "amp", type: "embed-size", height: 4769}
amp.html:267 xxxxxxxxxxxxxxxxx->  Send message
amp.html:245 xxxxxxxxxxxxxxxxx-> send height
amp.html:258 xxxxxxxxxxxxxxxxx-> make massage:
amp.html:259 Object {sentinel: "amp", type: "embed-size", height: 4809}
amp.html:267 xxxxxxxxxxxxxxxxx->  Send message
amp.html:245 xxxxxxxxxxxxxxxxx-> send height
amp.html:258 xxxxxxxxxxxxxxxxx-> make massage:
amp.html:259 Object {sentinel: "amp", type: "embed-size", height: 4849}
amp.html:267 xxxxxxxxxxxxxxxxx->  Send message
amp.html:245 xxxxxxxxxxxxxxxxx-> send height
amp.html:258 xxxxxxxxxxxxxxxxx-> make massage:
amp.html:259 Object {sentinel: "amp", type: "embed-size", height: 4889}
amp.html:267 xxxxxxxxxxxxxxxxx->  Send message
amp.html:245 xxxxxxxxxxxxxxxxx-> send height
amp.html:258 xxxxxxxxxxxxxxxxx-> make massage:
amp.html:259 Object {sentinel: "amp", type: "embed-size", height: 4929}
amp.html:267 xxxxxxxxxxxxxxxxx->  Send message
amp.html:245 xxxxxxxxxxxxxxxxx-> send height
amp.html:258 xxxxxxxxxxxxxxxxx-> make massage:
amp.html:259 Object {sentinel: "amp", type: "embed-size", height: 4969}
amp.html:267 xxxxxxxxxxxxxxxxx->  Send message
amp.html:245 xxxxxxxxxxxxxxxxx-> send height
amp.html:258 xxxxxxxxxxxxxxxxx-> make massage:
amp.html:259 Object {sentinel: "amp", type: "embed-size", height: 5009}
amp.html:267 xxxxxxxxxxxxxxxxx->  Send message
amp.html:245 xxxxxxxxxxxxxxxxx-> send height
amp.html:258 xxxxxxxxxxxxxxxxx-> make massage:
amp.html:259 Object {sentinel: "amp", type: "embed-size", height: 5049}
amp.html:267 xxxxxxxxxxxxxxxxx->  Send message
amp.html:245 xxxxxxxxxxxxxxxxx-> send height
amp.html:258 xxxxxxxxxxxxxxxxx-> make massage:
amp.html:259 Object {sentinel: "amp", type: "embed-size", height: 5089}
amp.html:267 xxxxxxxxxxxxxxxxx->  Send message
amp.html:245 xxxxxxxxxxxxxxxxx-> send height
amp.html:258 xxxxxxxxxxxxxxxxx-> make massage:
amp.html:259 Object {sentinel: "amp", type: "embed-size", height: 5129}
amp.html:267 xxxxxxxxxxxxxxxxx->  Send message
amp.html:245 xxxxxxxxxxxxxxxxx-> send height
amp.html:258 xxxxxxxxxxxxxxxxx-> make massage:
amp.html:259 Object {sentinel: "amp", type: "embed-size", height: 5169}
amp.html:267 xxxxxxxxxxxxxxxxx->  Send message
amp.html:245 xxxxxxxxxxxxxxxxx-> send height
amp.html:258 xxxxxxxxxxxxxxxxx-> make massage:
amp.html:259 Object {sentinel: "amp", type: "embed-size", height: 5209}
amp.html:267 xxxxxxxxxxxxxxxxx->  Send message
amp.html:245 xxxxxxxxxxxxxxxxx-> send height

**Comment by urielster** [comment]
Hi Olena

That's a great feedback for us, i can imagine this echoing happens between us and the AMP although we never experienced it here, we will enforce restrictions in the code to avoid such cases. we would be happy if you can share the test page/env/browser/os so we can test it with your configuration which has, probably, something different than our tests.

Thanks again..

Urielster
Outbrain

**Comment by obeyer** [comment]
@urielster
Thank you for your reply. Here's a url to a  gallery on a dev server, with an outbrain widget at the bottom. scroll to the very bottom of the page, you'll see the 4 posts appeared, and after that it just keeps adding white space
http://popsugar.dev35.onsugar.com/celebrity/Pregnant-Celebrities-2016-39789637/amp

**Comment by obeyer** [comment]
hi @urielster.
do you have any updates on infinite polling?
thank you!

**Comment by urielster** [comment]
Sure, We released new code today which limits the height updates to a maximum of 20 times. 1 sec between calls (lifetime in js)
Thanks again for the headsup. 

urielster
