### ISSUE TITLE
Loop videos that are not used for auto-advance

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#22174]
Videos should either be used for auto-advance, or loop.  If they're not the video used in the page's `auto-advance` attribute, we should enforce the fact that they loop.

**Comment by newmuis** [comment]
I still think we should take this on if we haven't already.  /cc @gmajoulet

**Comment by gmajoulet** [comment]
I remember working on this at some point and figuring out it was much harder than we thought, but honestly can't remember the context. My guess would be that we either (1) lacked knowledge on how to add an attribute (here `loop`) to `amp-video` and then propagate it to the `video` element, regardless of who controls it, or (2) were struggling with race conditions between amp-video.layoutCallback and the media pool, that we now resolved.

I think the initial ticket description should be achievable now.
cc @ampproject/wg-stories
