### ISSUE TITLE
amp-script: Remove AMP CORS requirements for author JS?

### ISSUE THREAD

**Issue by leonalicious** [ampproject/amphtml#22170]
Hi guys, we have started to play around with `<amp-script>`, the first issue we have bumped into, is there a way that we can request a js file without `AMP-Access-Control-Allow-Source-Origin header​​​` Response Header on it ? reason simply because most of the static files are stored on the `cdn` and we got limited access to add Header onto the Response of the request.

![image](https://user-images.githubusercontent.com/4065175/57295952-4a2d5600-70fe-11e9-891b-e9f391bd4a9a.png)

We have thought of wrapping our `cdn's js` with another backend API and append the required header with it, but feel like there are many extra steps needed to be done, any better suggestion on this please ?

/cc: @kristoferbaxter @choumx

**Comment by nainar** [comment]
@choumx can correct me here but I think that might be a larger [AMP constraint](https://amp.dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cors-requests?format=websites)

**Comment by choumx** [comment]
I think this is fine since author JS is a static resource. Plus we're hoping to remove/loosen AMP CORS in the general case anyways (#22136). I'll make this change soon.

**Comment by leonalicious** [comment]
thank you guys, looking forward to it

**Comment by kristoferbaxter** [comment]
Resolved, and should be available with the next release. Let us know if you continue to encounter problems.

**Comment by choumx** [comment]
Fixed in #22389.
