### ISSUE TITLE
Title providers in share not visible in language pt-br

### ISSUE THREAD

**Issue by danilomasato** [ampproject/amphtml#22179]
**Please only file reports about bugs in AMP here.**

<img src="https://github.com/danilomasato/report-ampstories/blob/master/bug-share-lang-pt-br.png?raw=true">

## What's the issue?

Title providers in share not visible in language pt-br.

## How do we reproduce the issue?

changing to language to pt-br, and click in share.

## What browsers are affected?

all browsers and devices (web/mobile)

All browsers? Some specific browser? What device type?

## Which AMP version is affected?

version 1.0

**Comment by torch2424** [comment]
I think this is a storied bug? @newmuis 😄

**Comment by newmuis** [comment]
Hi @danilomasato, can you share an example story that has this issue?

**Comment by danilomasato** [comment]
@newmuis follow example: https://esporte.uol.com.br/amp-stories/title-providers/index.htm

**Comment by kazechen** [comment]
@newmuis 
I tested it and found, that the following languages not visible:
pt-BR (Portuguese, Brazil)
pt (Portuguese, Portugal)
zh-TW (Traditional Chinese)
zh (Simplified Chinese)
