### ISSUE TITLE
How to Show responsive Ad with Adsense

### ISSUE THREAD

**Issue by gkteck** [ampproject/amphtml#2218]
Need to show responsive ads to be displayed on mobile.
Does amp-ad supports  data-ad-format="auto" ?

**Comment by luixxiul** [comment]
See: https://github.com/ampproject/amphtml/pull/1851

**Comment by gkteck** [comment]
is this fix available ?

The only adsense example I can see is
 <h2>AdSense</h2>
  <amp-ad width=300 height=200
      type="adsense"
      data-ad-client="ca-pub-8125901705757971"
      data-ad-slot="7783467241">
  </amp-ad>

**Comment by rudygalfi** [comment]
Closing, as this is a duplicate of #1851.
