### ISSUE TITLE
3p Video players: Implement 10s rewind/forward where possible

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#22184]
Implement the ability to double tap to rewind back/go forward by 10s.

Other players on mobile have this in full screen.

**Comment by newmuis** [comment]
When we do this, let's make sure it doesn't break or delay navigation in stories 😃

**Comment by alanorozco** [comment]
@nainar In fullscreen this will not work on Safari.
@newmuis Possibly a non-Stories only feature unless you folks are interested?

**Comment by torch2424** [comment]
cc @curseagain For the `amp-ima-video` side of things 😄

**Comment by aghassemi** [comment]
Both iOS and Android native players have this feature. iOS is 15s buttons. Android has double tap.

**Comment by alanorozco** [comment]
I'm guessing this request is more for the 3p side of things, for which we can only control `ima`.

**Comment by aghassemi** [comment]
Closing this per comment above (ie. Native players support it). Let's reopen with more details if needed.
