### ISSUE TITLE
 Response must contain the AMP-Access-Control-Allow-Source-Origin header

### ISSUE THREAD

**Issue by rohitkashyap8756** [ampproject/amphtml#22193]
I am new in amp I am using amp recaptcha input but getting this error on form submission

**Comment by torch2424** [comment]
Hello! Thanks for trying out AMP reCAPTCHA 😄 

Please see our [Handling CORS in AMP](https://amp.dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cors-requests?format=websites) documentation. This is how AMP handles CORS requests from a server.

For a quick example, [please see our glitch endpoint in `server.js`](https://glitch.com/edit/#!/torch2424-amp-glitch-express) that we are temporarily using for the [amp.dev amp-recaptcha-input example](https://amp.dev/documentation/examples/components/amp-recaptcha-input/).

Let me know if this helps, and we can close out this issue. Thanks! 😄 

cc @sebastianbenz

**Comment by torch2424** [comment]
@rohitkashyap8756 I'm going to go and close out this issue. Please take a look at the documentation I sent you. And if there are any more problems, feel free to open a new issue, or we can re-open this one.

Thank you! 😄
