### ISSUE TITLE
Uncaught Error: unknown animation type: must have "animation", "animations" or "keyframes" field

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#22209]
## What's the issue?
Uncaught Error: unknown animation type: must have "animation", "animations" or "keyframes" field

Briefly describe the bug.
Error message displays unknown animation type: must have "animation", "animations" or "keyframes"
## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. Open https://m.aliexpress.com/item/32946847352.html?pid=808_0000_0101&spm=a2g0n.search-amp.list.32946847352&aff_trace_key=&aff_platform=msite&m_page_id=3121amp-i-NUhnrXOPm9ijLvWkMEcQ1557334647651
2. Open developer tools and see error in console

## What browsers are affected?

macOSX Chrome Version 74.0.3729.131 (Official Build) 

## Which AMP version is affected?

Dev Version 1905071607430
Stable Version 1904301721170

Is this a new issue? Or was it always broken? Paste the version of AMP where you saw this issue. (You can find the version printed in your browser's console.)

New Issue

![Screen Shot 2019-05-08 at 3 30 58 PM](https://user-images.githubusercontent.com/48487406/57412835-04789800-71a7-11e9-84f6-2a8cea1e2d32.png)

**Comment by alanorozco** [comment]
1. Not analytics.
2. Not reproduceable.
3. User-level error.
