### ISSUE TITLE
Dark theme for page attachment

### ISSUE THREAD

**Issue by pithcell** [ampproject/amphtml#22204]
Feature request: amp-story-page-attachment header should have dark mode or the color of the header should be configurable.

**Comment by torch2424** [comment]
Triaging to @newmuis , Feel free to re-assign 😄

**Comment by hongwei1990** [comment]
We already have the design of dark theme attachment! Gabriel should have my spec :)

**Comment by gmajoulet** [comment]
Sounds good :)
So Hong, you want us to go with the "dark theme" mode that you designed, not a publisher configurable color?

**Comment by hongwei1990** [comment]
Ah! So as our system default. We will offer white and dark two themes.
Regarding open it up let s Alain with Jon and Vinay ：）

*From: *Gabriel Majoulet <notifications@github.com>
*Date: *Thu, May 9, 2019 at 6:58 AM
*To: *ampproject/amphtml
*Cc: *hongwei1990, Mention

Sounds good :)
