### ISSUE TITLE
AMP - Google Search Console

### ISSUE THREAD

**Issue by ChristofRemeysen** [ampproject/amphtml#22212]
Hi AMP team,

We have implemented Google Analytics tracking for our AMP pages, following your documentation guidelines: https://developers.google.com/analytics/devguides/collection/amp-analytics/

Next, we have set up Google Search Console, and linked it to our Google Analytics property. 

If we take a look at the Google Search Console report in Google Analytics, we notice that:
(1) No impressions and clicks are recorded for **/amp pages** that appear in the report (source = Google Search Console). However, session data is recorded (source = Google Analytics). 
(2) All data (impressions, clicks, sessions, etc.) is recorded for our **non /amp pages**. 

Can someone provide me guidance regarding the root cause? We would like to assess our AMP page results separately in order to make informed decisions about further future roll-outs.
Could it be due to erroneous linking of AMP and non-AMP versions that we can not distinguish both: https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/discovery?referrer=ampproject.org? 

Looking forward to your reply.

Kind regards,

Christof Remeysen

**Comment by torch2424** [comment]
cc @jeffjose can you help with this? 😄

**Comment by jeffjose** [comment]
Hi Christof,

Kinda hard to debug without seeing first-hand what is going on. If I understand correctly, you've setup the integration between Search Console and Google Analytics but Search Console isnt showing *any* data from GA?

Also, can you clarify #2? Do you mean the data for /amp pages are getting attributed to non /amp pages?

**Comment by ChristofRemeysen** [comment]
Hi @jeffjose,

Yes, we have set up the integration between Google Search Console and Google Analytics. It is showing data from GA, but it comes in mixed for /amp and non-/amp URLs for mobile traffic. My assumption was that this might be due to canonical linking.

Here you can find a dummy set of data that illustrates the behavior in Google Analytics (filter set on mobile): https://docs.google.com/spreadsheets/d/1-WizX5zxeICxnpXVTS_xYP-b3G1LObcSMtWOGaTTR30/edit?usp=sharing

Looking forward to your insights on this.

**Comment by aghassemi** [comment]
Closing as stale. Please reopen as needed.
