### ISSUE TITLE
Enable unique key value for AMP Ad Refresh

### ISSUE THREAD

**Issue by eschow** [ampproject/amphtml#22215]
## Describe the new feature or change to an existing feature you'd like to see

I'd like to see the ability to enable a unique key value for ad refresh v. non-refresh. This would help with track initial load v. refresh.

## Describe alternatives you've considered

N/A

## Additional context

Related: #13471 , but not necessarily thinking about a dynamic solution (yet).

**Comment by torch2424** [comment]
cc @ampproject/wg-ads

**Comment by keithwrightbos** [comment]
The ad request includes a parameter indicating it is a refresh and so this should be unnecessary.  I suggest reaching out to GAM reporting to determine if/how is refresh can be included.

**Comment by cdwalls-washpost** [comment]
@keithwrightbos if you are referring to the 'rc' key parameter, then I'm pretty sure that 'rc' is a "reserved key" in GAM/DFP and thus it is NOT available for targeting in the GAM/DFP targeting widget and it is also not reportable.  Therefore, it cannot be used for our use-case and we still need what we asked for:  the ability to enable a unique key-value for ad refresh v. non-refresh
(like we can on GPT adcalls on the web)

Can this be re-opened? Or can you loop in any GAM engineers who may be able to clarify this further?
