### ISSUE TITLE
Validator : add support of shrink-to-fit

### ISSUE THREAD

**Issue by okeul** [ampproject/amphtml#2221]
Is it possible to add support of `shrink-to-fit` in ` <meta name=viewport />` ?
> The property 'shrink-to-fit' in attribute 'content' in tag 'meta name=viewport' is disallowed.

It's necessary to fix iOS9 bug : https://forums.developer.apple.com/message/60444#60444

**Comment by cramforce** [comment]
CC @dvoytenko for advice on the bug.

**Comment by okeul** [comment]
More information here, about `shrink-to-fit`: https://developer.apple.com/library/prerelease/mac/releasenotes/General/WhatsNewInSafari/Articles/Safari_9_1.html#//apple_ref/doc/uid/TP40014305-CH10-SW6`

**Comment by dvoytenko** [comment]
Enabling `shrink-to-fit` in validator is fine. But one detail - we always force `overflow-x: hidden` which, I believe, cancels `shrink-to-fit=yes` anyway.

**Comment by powdercloud** [comment]
This is live in the validator.
