### ISSUE TITLE
Unable to scroll on page

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#22222]
## What's the issue?
Unable to scroll on page

Briefly describe the bug.
Unable to scroll on page after being able to previously scroll

## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. Go to https://m.aliexpress.com/item/32640703374.html?pid=808_0000_0201&spm=a2g0n.search-amp.list.32640703374&aff_trace_key=&aff_platform=msite&m_page_id=4627amp-i-NUhnrXOPm9ijLvWkMEcQ1557425205007
2. Open developer tools
3. Begin scrolling on page using click and drag

## What browsers are affected?
macOSX Chrome Version 74.0.3729.131 

## Which AMP version is affected?
Dev Version: 1905071607430
Stable: 1904301721170

Is this a new issue? Or was it always broken? Paste the version of AMP where you saw this issue. (You can find the version printed in your browser's console.)

New Issue
![Scrolling_Failure](https://user-images.githubusercontent.com/48487406/57477071-bb7b1f00-724c-11e9-8dbf-3f5e00ceb13e.gif)

cc: @aghassemi, @cathyxz

**Comment by aghassemi** [comment]
Does this happen on real devices (Android and iOS) or just similator in chrome Dev tools?

**Comment by aghassemi** [comment]
I can't repro on real devices, but I think I know what's going on. This only happens if mouse down for scrolling happens inside the long `amp-iframe` AliExpress is including for product description.

@leonalicious I believe this is an issue with the page inside that `iframe` preventing scrolling via mouse (maybe a `mousemove)` ( but not a `touchmove`) is doing `preventDefault`? ). Could you please take a look from your side?

**Comment by aghassemi** [comment]
(this could be a Chrome DevTools bug with iframes as well)

**Comment by aghassemi** [comment]
definitely a Chrome Devtools bug. Can repro in non-AMP easily with any iframes. will try to find a Chromium bug or file here.

**Comment by aghassemi** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=961426

**Comment by aghassemi** [comment]
I am going to close this as a Chrome bug.
