### ISSUE TITLE
amp.validator.validateUrlAndLog is not a function

### ISSUE THREAD

**Issue by huanghuiquan** [ampproject/amphtml#22239]
## What's the issue?

Hello, I built validator manual by run `gulp validator`, and got a validator_minified.js.

Proxy `https://cdn.ampproject.org/v0/validator.js` -> `validator/dist/validator_minified.js`,  and then use #development=1, but got error `amp.validator.validateUrlAndLog is not a function`.

**Comment by huanghuiquan** [comment]
Anyone can help ？I think it should add `amp.validator.validateUrlAndLog` to entry points.

**Comment by honeybadgerdontcare** [comment]
`amp.validator.validateUrlAndLog` is called by https://github.com/ampproject/amphtml/blob/master/src/validator-integration.js

You want to use `validateString` instead via console. There is also the chrome/opera [extension](https://chrome.google.com/webstore/detail/amp-validator/nmoffdblmcmgeicmolmhobpoocbbmknc) and [WebUI](https://validator.amp.dev/)

**Comment by huanghuiquan** [comment]
@honeybadgerdontcare But why amp validator.js  https://cdn.ampproject.org/v0/validator.js has `amp.validator.validateUrlAndLog`, how they built it?

**Comment by honeybadgerdontcare** [comment]
It's provided via [validator-in-browser.js](https://github.com/ampproject/amphtml/blob/master/validator/engine/validator-in-browser.js)

**Comment by huanghuiquan** [comment]
@honeybadgerdontcare Thanks, but is there any script or task to build validator-in-browser.js ? I could not  find it.
