### ISSUE TITLE
The attribute 'content' may not appear in tag 'span'

### ISSUE THREAD

**Issue by ferlo** [ampproject/amphtml#2223]
I've installed and using the plugin an a live site for few days.
GMT notified me about this

The attribute 'content' may not appear in tag 'span'

for every amp page indexed until now.

Plugin updated to 0.3 from WP repository.
suggestions?

**Comment by Gregable** [comment]
The `content` attribute is not a HTML standard allowed attribute for the `<span>` tag. You'll probably need to wait until WordPress updates their plugin to handle this specific issue.

**Comment by ferlo** [comment]
thank you.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
