### ISSUE TITLE
amp-date-picker: add an offset to the [max] date when it's based off the selected date of another date-picker's date

### ISSUE THREAD

**Issue by melskii** [ampproject/amphtml#22238]
I'd like to set the `[max]` date on one `amp-date-picker` based on another's value but with an offset of `n` days like you can with the `date-picker.today` and `date-picker.startToday` functions. 

So when I select the 1st May 2019 on one date-picker, I expect it to set the max value of the other date-picker to 29th May 2019 with an offset of 28 days.

I've attempted setting `maximum-nights` with a `range` type but that restricts the min and max dates selected and is confusing to users to clear the dates every time they tap.

I also tried to add an offset to the date using `amp-bind-macro` but because `event.date` is parsed as a string I receive an `NaN`

**Proposed solution:**
```
<amp-date-picker
    type="single"
    layout="container"
    format="YYYY-MM-DD"
    input-selector="[name=startDate]"
    on="
        select:
            AMP.setState({
                binding: {
                    startDate: event.date,
                    maxEndDate: event.date(offset=28)
                }
            })">
    <input name="startDate" placeholder="Start date">

</amp-date-picker>

<!--/* End date */-->
<amp-date-picker
        type="single"
        mode="overlay"
        layout="container"
        format="YYYY-MM-DD"
        input-selector="[name=endDate]"
        [min]="binding.startDate"
        [max]="binding.maxEndDate" 
        on="
            select:
                AMP.setState({
                    binding: {
                        endDate: event.date
                    }
                })">
    <input name="endDate" placeholder="End date">
</amp-date-picker>
```

**Comment by torch2424** [comment]
Triaging to @cvializ , feel free to re-assign 😄

**Comment by cvializ** [comment]
Thanks for the feature request! This sounds like a good feature to implement and I think it would be low effort.

**Comment by caroqliu** [comment]
Hi @melskii thanks for filing this issue! I investigated further and noticed that the requested `event.date(offset)` pattern is not transferable to the `date-picker.today(offset)` pattern as the first is accessed as an event property whereas the second is an AMP action invocation. Seeing as I'm not finding any precedence for event properties serving as functions or themselves taking arguments, I'm not sure this feature is as straight forward to implement as initially expected. cc @ampproject/wg-runtime for further advice here.

Would it suffice to expose `event.dateAsNumber`, similar to how we have [`event.valueAsNumber` on inputs](https://amp.dev/documentation/guides-and-tutorials/learn/amp-actions-and-events/?referrer=ampproject.org#input-elements) so you can continue on the `amp-bind-macro` route?
