### ISSUE TITLE
Design Review 2019-05-29 20:00 UTC (wg-outreach, AMP CORS deprecation, monthly releases)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#22245]
Time: [2019-05-29 20:00 UTC](https://www.timeanddate.com/worldclock/meeting.html?year=2019&month=05&day=29&iv=0) ([add to Google Calendar](http://www.google.com/calendar/event?action=TEMPLATE&text=AMP%20Project%20Design%20Review&dates=20190529T200000Z/20190529T210000Z&details=https%3A%2F%2Fbit.ly%2Famp-dr))
Location: [Video conference via Google Meet](https://bit.ly/amp-dr)

The AMP Project holds weekly engineering [design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md).  **We encourage everyone in the community to participate in these design reviews.**

If you are interested in bringing your design to design review, read the [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md) and add a link to your design doc by the Monday before your design review.

When attending a design review please read through the designs *before* the design review starts.  This allows us to spend more time on discussion of the design.

We rotate our design review between times that work better for different parts of the world as described in our [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md), but you are welcome to attend any design review.  If you cannot make any of the design reviews but have a design to discuss please let mrjoro@ know on [Slack](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#discussion-channels) and we will find a time that works for you.

**Comment by mrjoro** [comment]
The Outreach Working Group will be presenting their [periodic update](https://github.com/ampproject/meta/wiki/Working-Group-Updates) at this Design Review (10-15 minutes).

/cc @pbakaus @ampproject/wg-outreach

**Comment by dvoytenko** [comment]
I'd like to talk about docroots and scoping.

**Comment by rsimha** [comment]
I'd like to talk about adding a monthly release to the mix of AMP releases.

**Comment by dvoytenko** [comment]
I'd also like to discuss AMP CORS deprecation: #22136.

**Comment by lannka** [comment]
I'd like to discuss issues about vendor integration in AMP. [slides](https://docs.google.com/presentation/d/1JyRqPWOSR5H-wWXYoxaLuW93BVUdgvkEHbImW0B_nuQ/edit#slide=id.g588217d423_0_50)

**Comment by lannka** [comment]
My topic might take 20~30min. If time does not allow, we can do it on the week of 6/16. (I'm OOO next week).

**Comment by pbakaus** [comment]
The wg-outreach update I presented today can be found here: https://github.com/ampproject/wg-outreach/wiki/Status-update:-May-2019

**Comment by mrjoro** [comment]
**remove AMP CORS protocol (#22136), presenter: @dvoytenko**
- @aghassemi: in cases that publishers had a wildcard (*.ampproject.org) in the normal HTTP access and then a tighter rule for the AMP version, would potentially other AMP documents be able to do this?  @dvoytenko: they couldn't do partial wildcards like this
- @aghassemi: this will help a lot with confusion; get a lot of questions about amp-list not working, etc.

**Comment by mrjoro** [comment]
**monthly releases, presenter @rsimha**
- @sparhami: how are the extensions served with the right version, since they're made separately by the parser and could be made in parallel?
  - @rsimha: when the cache gets a request it knows the URL, so we'll match extensions that match the runtime request; @dvoytenko has to be URL separated, not a cookie
  - @dvoytenko: all RTV versions are separated by URL; there is a mode for unversioned where we request a specific RTV for extensions, otherwise everything has to match v0.js in version; validator should ensure each extension matches the v0.js version (basically option 2); @rsimha will follow up with @jridgewell on this
- @erwinmombay/dvoytenko: how do we get non-Google AMP Caches to implement similar functionality?  when they optimize the AMP pages they replace the cdn.ampproject.org urls with the version loaded from themselves; @rsimha: we have to look into it; @dvoytenko: it should be a goal for this to work with every cache
- @aghassemi: instead of being in the path of the URL, could be a query string parameter?  various: this seems like a good idea; @rsima: does Google AMP Cache infra support query string?  not sure, but probably
- @rsimha: to summarize: moving to a renamed version is likely to be a breaking change for caches, but using a query parameter (?monthly) is preferred & extensions should explicitly specify the version and validator should check this
- @rsimha: is it controversial that the cookie supersedes the URL specified?  (if you go to foo.com that requests monthly, but I set cookie to RC, I should get the weekly RC)
  - @aghassemi/@sparhami: we need how to address the testing concern that prompted the monthly build; do we need a monthly RC as well to test against? i.e. what is the lead time on the monthly release so people can have enough time to test against it?  (e.g. should we use the release from 2 weeks ago to allow for 2 weeks to testing)
- @sparhami: any thinking about making the monthly the default and opt-in for weekly?  @rsimha: no plans for that right now, for most people having a faster update should be better
- @rsimha: should we do the monthly cut after N weeks or M releases?  depends on how we decide to do the RC; @sparhami/@dvoytenko: aligning on weeks is a lot simpler
