### ISSUE TITLE
Auto-Select "Featured Snippet" on AMP landing page

### ISSUE THREAD

**Issue by peterquale** [ampproject/amphtml#22241]
## Describe the new feature or change to an existing feature you'd like to see

The AMP feature that automatically highlights the featured snippet in each AMP page and scrolls to the snippet on load is very useful to sighted users. When the page loads using TalkBack, the user is not read the snippet, but they hear "scrolled to section" then the page title. An excellent added feature would be immediately focusing and selecting the content so Talkback reads the page title, then "Scrolled to section." and then the highlighted content. 

## Describe alternatives you've considered

Placing the featured snippet in an element with role="alert" read as the page loads would likely suffice, but if the content was already selected when the page loads, users could immediately copy the text to their clipboard for sharing or saving out. 

I assume the only way this would work is using a screen-reader-only text field that is focused when the page loads and the field would automatically select the contents. At which point, an ARIA alert role or aria-live attribute wouldn't be necessary. 

Doing this might be problematic for sighted users who don't realize they are focused in a text field, but some sighted users with physical disabilities would benefit from seeing the AMP notification change from "scrolled to section." to "Scrolled to selected snippet." or similar. The user could simply copy to clipboard with a minimum effort-- critical for some users, especially switch (assistive technology) users.

Thanks for considering this feature.

**Comment by torch2424** [comment]
cc @sebastianbenz @pbakaus

**Comment by aghassemi** [comment]
Please recreate in https://github.com/ampproject/docs repo. Thanks!
