### ISSUE TITLE
Send document.title in initial viewer handshake

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2225]
We should send the document's title to the viewer in our initial handshake. See internal bug b/27308672

@dvoytenko @erwinmombay Any takers?

CC @ericfs

**Comment by ericfs** [comment]
Including it in the documentLoaded message would be good

**Comment by cramforce** [comment]
Making a PR

**Comment by cramforce** [comment]
Sent out #2228

**Comment by erwinmombay** [comment]
@cramforce thanks
