### ISSUE TITLE
amp-brid dont work

### ISSUE THREAD

**Issue by seomaz** [ampproject/amphtml#22260]
The amp-brid not work [example](https://amp.dev/documentation/examples/components/amp-brid-player/?referrer=ampbyexample.com)

The player does not render, thumbnail 404 error.

**Comment by aghassemi** [comment]
@seomaz . What browser/platform are you using? Could you post more details (screenshot, errors in console). It seems to work to work for me on Chrome and Safari on Mac and Chrome on Android

**Comment by seomaz** [comment]
its working now! thanks
