### ISSUE TITLE
Scrolling does not contribute to engaged time on mobile devices

### ISSUE THREAD

**Issue by britice** [ampproject/amphtml#2226]
PR https://github.com/ampproject/amphtml/pull/1818 was intended to capture overall engagement with articles by users across any viewing platform. One action which should contribute to a measure of user engagement is the `'scroll'` event.

A scroll event listener is being registered by the `Activity` service in an attempt to include that activity in the engaged time measurement. However, in testing in mobile devices since the feature was released, scrolling in the device does not contribute to engaged time.

**Comment by britice** [comment]
I think I figured it out already. The `scroll` event listener is being registered on `document.documentElement` rather than on the `document`. I'll need to modify how this is being set up.

**Comment by cramforce** [comment]
@britice use `viewer.onScroll`. That will give you scroll events independent of our various platform specific scrolling implementations.

**Comment by britice** [comment]
Oh perfect.

**Comment by britice** [comment]
@cramforce, did you mean `viewport.onScroll` instead of `viewer.onScroll`? I don't see that method available on the `Viewer` class.

Or were you suggesting to use `viewer.onViewportEvent`?

**Comment by cramforce** [comment]
Sorry, `viewport` is correct.

**Comment by ericlindley-g** [comment]
Closing, as this looks like it's resolved, but @britice, please feel free to reopen if there are any outstanding issues/questions!
