### ISSUE TITLE
Incorrect typedefs in `ads/google/imaVideo.js`

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#22277]
- The following typedefs in `ads/google/imaVideo.js` are invalid because they are missing curly braces around the `Element` typename.
- When curly braces are added, the presubmit rule that requires the use of `dev().assertElement()` instead of `/** @type {!Element} */` kicks in.
- When `dev().assertElement()` is used, we see test failures due to `videoPlayer` not actually being an `Element`.

**Test:**
```
gulp test --unit --files extensions/amp-ima-video/0.1/test/test-amp-ima-video.js
```
**Error:**
```
      Error: Element expected: [object Object]
          at Log.assert (/tmp/cc54e5f9ee28148cf3695259696da85e.browserify.js:42563:15)
          at Log.assertElement (/tmp/cc54e5f9ee28148cf3695259696da85e.browserify.js:42590:10)
          at Object.onContentPauseRequested (/tmp/cc54e5f9ee28148cf3695259696da85e.browserify.js:1353:47)
          at Context.<anonymous> (/tmp/cc54e5f9ee28148cf3695259696da85e.browserify.js:3886:17)
```

**Erroneous source code:**
https://github.com/ampproject/amphtml/blob/1f0a26da32d2001b54a8dd4a025b137304299a74/ads/google/imaVideo.js#L628
https://github.com/ampproject/amphtml/blob/1f0a26da32d2001b54a8dd4a025b137304299a74/ads/google/imaVideo.js#L835
https://github.com/ampproject/amphtml/blob/1f0a26da32d2001b54a8dd4a025b137304299a74/ads/google/imaVideo.js#L852
https://github.com/ampproject/amphtml/blob/1f0a26da32d2001b54a8dd4a025b137304299a74/ads/google/imaVideo.js#L899
https://github.com/ampproject/amphtml/blob/1f0a26da32d2001b54a8dd4a025b137304299a74/ads/google/imaVideo.js#L913

This bug is currently blocking #21212

**Comment by rsimha** [comment]
/to the UI team for triage @aghassemi @torch2424 @alanorozco

**Comment by rsimha** [comment]
After debugging, I found that `videoPlayer` does indeed look like an `Element`, but its `nodeType` field is `undefined`, which causes it to fail the `dev().assertElement()` check below.

Any idea why this might be?

https://github.com/ampproject/amphtml/blob/d974c819a4238ef39983af7d8aeb26af1fcbb2dc/src/log.js#L366-L371

**Comment by torch2424** [comment]
@rsimha So `amp-ima-video` was originally contributed externally, so I am not sure if it should / shouldn't have the `nodeType` field. That being said, the code does a lot of weird things, and I'd be open to adjusting the types on these things 😄

**Comment by rsimha** [comment]
SG. In that case, I'll leave the original type annotations for `Element` and temporarily exempt the file from the presubmit check that requires the use of `dev().assertElement`.

Thanks!

**Comment by torch2424** [comment]
@rsimha You're welcome / Thank you! 😄
