### ISSUE TITLE
anchor link in an AMP

### ISSUE THREAD

**Issue by marcorroma** [ampproject/amphtml#22312]
Hi, I have a problem with AMP.
I need to create an index for an article, in the desktop and mobile version I have no problems with classic anchor code (`<a href="#example">` and `<a name="example">` code), with the AMP version clicking on the anchor link opens a new window.
What is the right code to insert a list with anchor link in an AMP version (also compatible with desktop and mobile version)?
Thank you.
Marco

**Comment by marcorroma** [comment]
**I have found a solution.** This is my code for Amp and not.
Code:
`<style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
   <script async src="https://cdn.ampproject.org/v0.js"></script>

<ul tabindex="point1" role="button" on="tap:point1.scrollTo()">POINT 1</ul>

<a id="point1">POINT 1</a>`

I hope it's helpful

**Comment by torch2424** [comment]
Awesome! Glad you figured out your issue! 😄 I'll go ahead and close this, feel free to mention me if you feel like this needs something more 👍
