### ISSUE TITLE
Animate-in of the rotated layer visible before the start

### ISSUE THREAD

**Issue by StebneRuslan** [ampproject/amphtml#22329]
Hi, I have a problem with APM story animation. I create a simple story with an image layer.  But if I want to rotate the image the image is visible before animation starts.
It is possible to rotate the story layers? Or it’s not supported now?

http://prntscr.com/noqzg8

https://cutnut-tv.cdn.ampproject.org/c/s/cutnut.tv/amp/464fd4b2-f26e-4fd9-ab64-122bde29038f

**Comment by torch2424** [comment]
Triaging to @newmuis Feel free to re-assign 😄

**Comment by newmuis** [comment]
The element is supposed to be positioned offscreen, but that's not working; either because of the rotation or because of scaling stuff we do internally.  We should address this as an internal implementation detail when applying the first animation frame; the code as listed shouldn't have to change.

**Comment by StebneRuslan** [comment]
Hi, are there any updates here?

**Comment by nainar** [comment]
paging @newmuis for an update here. Cutnut asked about this in our partner meeting

**Comment by newmuis** [comment]
Hi @nainar and @StebneRuslan, this is on our radar; hopefully we'll be able to get around to it soon!  @StebneRuslan if you're willing to contribute a fix, we could walk you through what that might look like as well

**Comment by newmuis** [comment]
I was just looking at some other rotation-related stuff, and I wonder if we fail to take the `transform-origin` into account; if the origin is the center of the element, then how far we have to move it offscreen would be dependent on the size of the element

**Comment by yarina2917** [comment]
Hi, are there any updates about this issue?

**Comment by gmajoulet** [comment]
@processprocess I believe you might have fixed this one?

**Comment by processprocess** [comment]
This needs to be double checked and tested with elements of different heights and widths.
fly-in also has this problem in some aspect ratios #30790

**Comment by danielstockton** [comment]
This issue is still actual, and is also reproducible with non-rotated objects. Demo:

https://stories.nws.ai/1288492465/nam-1770-animate-in/
