### ISSUE TITLE
Not able to scroll after switching articles

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#22337]
## What's the issue?
Not able to scroll after switching articles

Briefly describe the bug.
Scrolling after switching articles fails. Seen 3/5 after refreshing page.

## How do we reproduce the issue?
1. Search for NBA
2. Open developer tools
3. Select an article
4. Use the click and swipe to swipe between articles
5. Attempt to scroll on page

## What browsers are affected?
macOSX Chrome Version 74.0.3729.131

## Which AMP version is affected?
Canary Version: 1905140117570

Is this a new issue? Or was it always broken? Paste the version of AMP where you saw this issue. (You can find the version printed in your browser's console.)
New Issue

cc: @choumx, @aghassemi 

![scrolling_issue](https://user-images.githubusercontent.com/48487406/57871958-752f3e00-77bf-11e9-867f-e9199cdca00e.gif)

**Comment by diantekyrie** [comment]
Could be a problem that's hidden behind an experiment flag.

**Comment by choumx** [comment]
I'm having trouble reproducing this on macOS Chrome (iPhone emulation) and on Safari on iPhone.

**Comment by choumx** [comment]
@diantekyrie Are you able to reproduce this on any mobile devices?

**Comment by diantekyrie** [comment]
@choumx, no I checked on iPhone and its fine.

**Comment by choumx** [comment]
Thanks, might be an emulation quirk then. Please reopen if you notice this bug on device.

**Comment by aghassemi** [comment]
It's same as this: https://bugs.chromium.org/p/chromium/issues/detail?id=961426

It's a DevTools bug and I don't expect Chrome to fix it soon, so let just be aware of it.
