### ISSUE TITLE
aria-hidden="true" for focusable content of (i.e.) amp-carousel slides that already have aria-hidden="true"

### ISSUE THREAD

**Issue by Jessman5** [ampproject/amphtml#22331]
## What's the issue?

In (i.e.) an amp-carousel, focusable content like simple link tags need to be `tabindex="-1"` or at least have the attribute `aria-hidden="true"`, too, if the parent slide is invisible. 
This applies to all modules that have a container that is hidden with aria whose content can have anything inside.

This is an accessibility issue because WCAG 4.1.2 – ARIA hidden element must not contain focusable elements.
See [here](https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html) and [here](https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus?application=msftAI)

## How do we reproduce the issue?

The basic amp-carousel html
````
<amp-carousel>
    <div class="i-amphtml-slides-container i-amphtml-slidescroll-no-snap" aria-live="polite">
        <div class="i-amphtml-slide-item i-amphtml-slide-item-show">
            <div class="amp-carousel-slide" aria-hidden="false">
                <a href="#">your link content</a>
            </div>
            <div class="amp-carousel-slide" aria-hidden="true">
                <a href="#">your link content</a>
            </div>
        </div>
    </div>

    <div tabindex="0" class="amp-carousel-button amp-carousel-button-prev" role="button" aria-disabled="true" title="1/2"></div>
    <div tabindex="0" class="amp-carousel-button amp-carousel-button-next" role="button" aria-disabled="false" title="2/2"></div>
</amp-carousel>
````
The `<a href="#">your link content</a>` in the hidden `div.amp-carousel-slide` is still focusable and WCAG doesn't like it.

I'm trying to get around it by doing this:

````
<amp-state id="setHiddenState">
     <script type="application/json">
          {
              "currentSlide": 0
          }
      </script>
</amp-state>

→ <amp-carousel on="slideChange:AMP.setState({setHiddenState: {currentSlide: event.index}})">
    <div class="i-amphtml-slides-container i-amphtml-slidescroll-no-snap" aria-live="polite">
        <div class="i-amphtml-slide-item i-amphtml-slide-item-show">
            <div class="amp-carousel-slide" aria-hidden="false">
→               <a href="#" [aria-hidden]="setHiddenState.currentSlide != 0 ? 'true' : 'false'">your link content</a>
            </div>
            <div class="amp-carousel-slide" aria-hidden="true">
→               <a href="#" [aria-hidden]="setHiddenState.currentSlide != 0 ? 'true' : 'false'">your link content</a>
            </div>
        </div>
    </div>

    <div tabindex="0" class="amp-carousel-button amp-carousel-button-prev" role="button" aria-disabled="false" title="1/2"></div>
    <div tabindex="0" class="amp-carousel-button amp-carousel-button-next" role="button" aria-disabled="false" title="2/2"></div>
</amp-carousel>
````
The current slide will get `aria-hidden="false"`, while all others are `true` due to the `<amp-state id="setHiddenState">`

It would be great if that's sth that comes with the module(s) right away.

## What browsers are affected?

All major browsers.

## Which AMP version is affected?

AMP Version 1905091827220

**Comment by aghassemi** [comment]
Thanks @Jessman5

**Comment by sparhami** [comment]
Sounds like the `inert` attribute would be useful here, as well as fixing text selection and find-in-page. Unfortunately, there doesn't seem to be much progress on it for Chrome (behind a flag, https://www.chromestatus.com/feature/5703266176335872) and non-existent for other browsers. There is a polyfill for it here: https://github.com/GoogleChrome/inert-polyfill, which seems to at least cover the tabbing case (and selection using `user-select: none`).

There are other cases where the polyfill would be nice (when we open lightbox or sidebar), so we may want to consider dynamically loading it, since many things seem to benefit.
