### ISSUE TITLE
Recaptcha service may not work in shadow.

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#22345]
I haven't actually tested this, but it looks like https://github.com/ampproject/amphtml/blob/724ce3222978ac55aeb6fe393150ee26e8f7e464/extensions/amp-recaptcha-input/0.1/amp-recaptcha-input.js#L148
is using the same structure that I previously used, and did not perform correctly in shadow mode. 

If it helps you can now write a integration test using https://github.com/ampproject/amphtml/blob/724ce3222978ac55aeb6fe393150ee26e8f7e464/test/integration/test-amp-analytics.js#L817

**Comment by torch2424** [comment]
@calebcordry Been super busy, and haven't had time to investigate this, but I think this will be fixed by: #22511 ? 🤔

**Comment by calebcordry** [comment]
Yep looks like it :)

**Comment by torch2424** [comment]
@calebcordry Rad thanks! When the PR is closed, I'll close this issue than 😄

**Comment by choumx** [comment]
I'd leave this issue open to track addition of the integration test.
