### ISSUE TITLE
Update Ad / Analytics Vendor integration process to mention they should include the working group

### ISSUE THREAD

**Issue by torch2424** [ampproject/amphtml#22340]
That way we all get a notification, and PRs don't slip through like: #21650

cc @ampproject/wg-ads 
cc @ampproject/wg-analytics

**Comment by torch2424** [comment]
cc @mrjoro Let me know how your investigation goes if new accounts can mention people without being in the org 😄

**Comment by torch2424** [comment]
It works! 😄 #22342

**Comment by micajuine-ho** [comment]
Closed by #26156
