### ISSUE TITLE
amp-brightcove attribute data-video-id inconsistent

### ISSUE THREAD

**Issue by Gregable** [ampproject/amphtml#2235]
https://github.com/ampproject/amphtml/blob/master/extensions/amp-brightcove/amp-brightcove.md
`data-video-id`

https://github.com/ampproject/amphtml/blob/master/extensions/amp-dailymotion/amp-dailymotion.md
https://github.com/ampproject/amphtml/blob/master/extensions/amp-vimeo/amp-vimeo.md
https://github.com/ampproject/amphtml/blob/master/extensions/amp-youtube/amp-youtube.md
`data-videoid`

https://github.com/ampproject/amphtml/blob/master/extensions/amp-soundcloud/amp-soundcloud.md
`data-trackid`

https://github.com/ampproject/amphtml/blob/master/extensions/amp-twitter/amp-twitter.md
`data-tweetid`

https://github.com/ampproject/amphtml/blob/master/extensions/amp-vine/amp-vine.md
`data-vineid`

Should we change amp-brightcove to use:
`data-videoid`

Or at least accept either?

**Comment by wojtekmo** [comment]
Hello  Team,
Please remove my input into "amphtml"
Thank you
Wojtek 

    On Tuesday, February 23, 2016 2:56 PM, Greg Grothaus <notifications@github.com> wrote:
 

 https://github.com/ampproject/amphtml/blob/master/extensions/amp-brightcove/amp-brightcove.md
data-video-idhttps://github.com/ampproject/amphtml/blob/master/extensions/amp-dailymotion/amp-dailymotion.md
https://github.com/ampproject/amphtml/blob/master/extensions/amp-vimeo/amp-vimeo.md
https://github.com/ampproject/amphtml/blob/master/extensions/amp-youtube/amp-youtube.md
data-videoidhttps://github.com/ampproject/amphtml/blob/master/extensions/amp-soundcloud/amp-soundcloud.md
data-trackidhttps://github.com/ampproject/amphtml/blob/master/extensions/amp-twitter/amp-twitter.md
data-tweetidhttps://github.com/ampproject/amphtml/blob/master/extensions/amp-vine/amp-vine.md
data-vineidShould we change amp-brightcove to use:
data-videoidOr at least accept either?—

**Comment by mister-ben** [comment]
It uses `data-video-id` to match the attribute in the non-AMP Brightcove embed. I think only accepting `data-videoid` would be unintuitive to some, but I've nothing against accepting either.

**Comment by rudygalfi** [comment]
Ping @Gregable

**Comment by Gregable** [comment]
Works for me.
