### ISSUE TITLE
Playbuzz script generates an error if no amp-playbuzz tag is used on a page

### ISSUE THREAD

**Issue by dotun-o** [ampproject/amphtml#22354]
## What's the issue?

If a page has the **amp-playbuzz** script included, a validation error is generated if no **amp-playbuzz** tag is present on that page. Normally, script tags for AMP components can be present (often bundled in header files) whether or not a particular page uses any or all of the included components.

## How do we reproduce the issue?

This can be reproduced on Google AMP's Playground:

1. Visit https://playground.amp.dev/
2. Replace editor code with this:

```<!doctype html>
<html amp lang="en">
<head>
  <meta charset="utf-8">
  <title>My AMP Page</title>
  <link rel="canonical" href="self.html" />
  <meta name="viewport" content="width=device-width,minimum-scale=1">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script async custom-element="amp-twitter" src="https://cdn.ampproject.org/v0/amp-twitter-0.1.js"></script>
  <script async custom-element="amp-playbuzz" src="https://cdn.ampproject.org/v0/amp-playbuzz-0.1.js"></script>
  
  <style amp-custom>
    h1 {
      margin: 1rem;
    }
  </style>
</head>
<body>
  <h1>Hello AMPHTML World!</h1>
</body>
</html>
```

3. You will find validation error for only Playbuzz, in contrast to the Twitter component script which is also present, even though the **amp-twitter** tag was not used either

## What browsers are affected?

Tested on Chrome, Safari, Firefox; almost certainly browser-agnostic.

## Which AMP version is affected?

Confirmed in version 1905091827220

**Comment by torch2424** [comment]
Triaging to @Gregable , feel free to re-assign 😄

**Comment by Gregable** [comment]
This is working as intended. The feature to detect usage of an extension was added during the lifetime of AMP, not at the start. In order to not break existing pages in the wild, extensions that were added before this time do not have this requirement in the validator, but all new extensions do.
