### ISSUE TITLE
amp-form ignores fields created inside submit-success

### ISSUE THREAD

**Issue by fstanis** [ampproject/amphtml#22353]
## What's the issue?

I was trying to have a form generate additional fields for the second submission, based on the server response from the first submission. However, it seems that `amp-form` ignores form fields that are created this way inside `<div submit-success>`.

## How do we reproduce the issue?

```
<form method="post" action-xhr="https://amp.dev/documentation/examples/api/echo">
    <input type="submit" value="Submit">
    <div submit-success>
        <template type="amp-mustache">
            <input type="text" name="test" required>
        </template>
    </div>
</form>
```

Submitting for the first time creates a new input element. Submitting for the second time should include this new input field in the POST request, but it currently doesn't. Form validation works, however, which shows that the input does belong to the correct form.

## What browsers are affected?

Tested on Chrome, presumably not browser-specific.

## Which AMP version is affected?

Tested on 1905091827220.

**Comment by aghassemi** [comment]
Thanks @fstanis . To @cvializ to take a look.

**Comment by caroqliu** [comment]
```html
```
