### ISSUE TITLE
force to use amp-img option attribute in amp-carousel

### ISSUE THREAD

**Issue by imansa** [ampproject/amphtml#22378]
according to following documents, on **Image gallery with preview** part we must use **option** attribute on amp-img tags to make a slider with preview

[amp-carousel sample document](https://amp.dev/documentation/examples/multimedia-animations/image_galleries_with_amp-carousel/?format=websites#asd)

## What's the issue?

according to amp-carousel documents on **Image gallery with preview** part, we must use **option** attribute on amp-img tags to make a slider with preview. but option attribute is not in amp-img allowed attributes in [standard](https://amp.dev/documentation/components/amp-img?referrer=ampproject.org) and will be removed by amp validators like [this one](https://github.com/Lullabot/amp-library)

## How do we reproduce the issue?

it is about amp-carousel standard an is visible in [it's sample page](https://amp.dev/documentation/examples/multimedia-animations/image_galleries_with_amp-carousel/?format=websites#asd) and do not need any test case

## What browsers are affected?

All browsers

## Which AMP version is affected?

1905091827220

**Comment by aghassemi** [comment]
Hi @imansa `option` attribute becomes valid when inside `amp-selector`, which is needed to make that example work. You can also use `amp-bind` to make a a photo gallery.  One of the codelabs we have ([Building Beautiful, interactive, canonical AMP pages](https://codelabs.developers.google.com/codelabs/amp-beautiful-interactive-canonical/#0)) takes you through both approaches.

Hope this helps

-Ali

**Comment by imansa** [comment]
Hi Ali

you said _"option attribute becomes valid when inside amp-selector"_. where is it's document ? i am try to create an issue like [this one](https://github.com/Lullabot/amp-library/issues/263) on [validator](https://github.com/Lullabot/amp-library) to fix it's problems. but i need some document to show my issue is valid according to amp standards. being a attribute valid when tag is child of other tag is some complex and i do not know how to find it's document for it and same problems in future.

thanks a lot

**Comment by aghassemi** [comment]
@imansa `option` is an attribute that is meant for children of `amp-selector` per https://amp.dev/documentation/components/amp-selector but those children can by anything themselves (e.g. `div`, `amp-img`, etc..)
