### ISSUE TITLE
amp-script throws error for `removeAttribute('disabled')`

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amphtml#22371]
## What's the issue?

amp-script throws the following error when calling `element.removeAttribute('disabled')`:

`Cannot read property 'replace' of null`
&
`Uncaught TypeError: Cannot read property 'replace' of null`

Also doesn't work for `document.getElementById("elementId").disabled = false;`

But strangely works for `element.setAttribute('disabled', 'true');`

## How do we reproduce the issue?

Add an element inside `amp-script` component with disabled attribute.

Call `element.removeAttribute('disable')` in the script 

## What browsers are affected?

Chrome 74.0.3729.157 (Official Build) (64-bit)
MacOS

## Which AMP version is affected?

Version 1905091827220

**Comment by torch2424** [comment]
cc @kristoferbaxter 😄

**Comment by choumx** [comment]
Fixed by #23245.
