### ISSUE TITLE
AMP.navigateTo does not handle relative URL correctly on CDN

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#22376]
It should resolve relative URL to source URL 
To repro: 
https://lannka-github-io.cdn.ampproject.org/c/s/lannka.github.io/amp-ad-template/test.html

have console open, and click on the text. it lands on CDN , then redirected to pub origin

/cc @jridgewell @choumx

**Comment by jridgewell** [comment]
Is this a high priority bug?

**Comment by lannka** [comment]
Not sure how many people are doing relative URLs in AMP.navigateTo. Hopefully user will be redirected and landed on the right page. 

It will affect Linker though, as links to CDN domain are not decorated.

I will put a P2

**Comment by choumx** [comment]
Thanks for the report.
