### ISSUE TITLE
<amp-ad> is not allowed to be placed in elements with position:fixed:  

### ISSUE THREAD

**Issue by dejandex** [ampproject/amphtml#2238]
.fixed {
      position: fixed;
      top: 0;
      right: 0;
    }

	<div class="fixed">
		<amp-ad width=468 height=60
		type="adsense"
		data-ad-client="ca-pub-************"
		data-ad-slot="3091498012">
		</amp-ad>
	</div>

**Comment by cramforce** [comment]
Correct. That is a rule in AMP.

**Comment by dejandex** [comment]
but is in file 

https://github.com/ampproject/amphtml/blob/master/examples/ads.amp.html

**Comment by cramforce** [comment]
Yes, to test that it doesn't work :)

**Comment by cramforce** [comment]
We should add a comment to make that clear.

**Comment by dejandex** [comment]
:) yes
