### ISSUE TITLE
I2I: <amp-ym-chatbot>

### ISSUE THREAD

**Issue by Rachana040** [ampproject/amphtml#22382]
## Summary
YM-chatbot component is a tool that takes a query from the user, runs the query and displays the prediction made by the chatbot.

## Motivation
Currently there is no amp component serving this purpose. Also this increases the user interactivity, allowing them to do get their queries answered without the need of visiting the site.

/cc @ampproject/wg-approvers

**Comment by mrjoro** [comment]
Hi @Rachana040, have you been working with anyone on this I2I yet?

/cc @ampproject/wg-ui-and-a11y

**Comment by aghassemi** [comment]
Hi @Rachana040 I will be happy to help with this ITI. Looking forward to see the design doc. Feel free to ping my on Slack as well.

**Comment by Rachana040** [comment]
@mrjoro Hi. No, not yet.
@aghassemi Thanks! that would be great.

**Comment by aghassemi** [comment]
@Rachana040 below are a few examples of ITI's that are somewhat similar to the component you are proposing. You can use them as template and update this ITI with more details:

https://github.com/ampproject/amphtml/issues/13105
https://github.com/ampproject/amphtml/issues/19916
https://github.com/ampproject/amphtml/issues/14299

In terms of implementation, we don't have any messaging components yet, so this would be the first! but 3P components such as `amp-yotpo` and `amp-addthis` are probably the closest in terms of implementation.

**Comment by Rachana040** [comment]
@aghassemi Great! Will look into it. 
Well YM refers to our company Yellow Messenger that provides chatbot services. Some of the companies using our chatbot services include HDFC ERGO, Bajaj Finserv, Apollo Munich, Indigo and many more.
Here's Link to the website: https://yellowmessenger.com/

**Comment by Rachana040** [comment]
@aghassemi I am working for the first time on this project, can you guide me on how to get started with the implementation.

**Comment by Rachana040** [comment]
@aghassemi Hey. If you look into this link, https://www.hdfcbank.com/personal/products/loans/personal-loan there's our chatbot(Ask Eva) at the right corner of the page. So we have all the script to add our chatbot onto a website. Similarly we want to add the same script, so that bot shows on to a mail. Is it possible to do that?
