### ISSUE TITLE
amp-video-iframe not working on iOS 12.3

### ISSUE THREAD

**Issue by lukacmi** [ampproject/amphtml#22406]
## What's the issue?
amp-video-iframe not working on iOS 12.3. Not sure if this has started since iOS 12.3 update or AMP release 1905091827220.

Safari console throws two errors:
Error while parsing the 'sandbox' attribute: 'allow-presentation' is an invalid sandbox flag.
https://cdn.ampproject.org/rtv/011905091827220/v0/amp-iframe-0.1.js:714

[Error] Failed to load resource: the server responded with a status of 404 () (ww.js.map, line 0)
https://amp.dev/documentation/examples/components/amp-video-iframe/preview/blob:https://amp.dev/ww.js.map

## How do we reproduce the issue?
Tested on iPhone and iPad - both iOS 12.3

1. Open the URL on iOS device:
https://amp.dev/documentation/examples/components/amp-video-iframe/preview/
2. Video fails to play

## What browsers are affected?
Both Safari and Chrome (latest) on iOS 12.3

## Which AMP version is affected?
Version 1905091827220 - worked in the past.

**Comment by aghassemi** [comment]
/to @alanorozco setting as P1, please update after you investigate accordingly.
