### ISSUE TITLE
Can I use AMP playground for my educational videos?

### ISSUE THREAD

**Issue by Stefany93** [ampproject/amphtml#22401]
I have been using Codepen to record educational AMP videos, but the AMP playground is way better. Some of the videos I sell, some of them I upload to my YT channel. Can I use the playground for that ?

**Comment by torch2424** [comment]
Hello!

cc @pbakaus @sebastianbenz 

I think they may know, but I hope we can say yes! Would be super awesome! Wish you much luck on your YT channel! 😄 🎉

**Comment by pbakaus** [comment]
Sure thing, go ahead!

**Comment by Stefany93** [comment]
Thanks so much @torch2424  , @pbakaus

**Comment by torch2424** [comment]
@Stefany93 You are welcome! Going to close out this issue.

Feel free to comment more here, or open new ones if something comes up. Thanks! 😄 👍
