### ISSUE TITLE
Date picker automatic focus to previous selection

### ISSUE THREAD

**Issue by danieltxok** [ampproject/amphtml#22412]
## What's the issue?

It looks that the clearing of the dates does not fully work because when selecting new dates again, it automatically scrolls to the position of the previous date range.

## How do we reproduce the issue?

Go [here](https://www.iberostar.com/vacaciones-en-mayo?format=amp) and click on Inicia tu busqueda. Select a date range (e.g. in June) and then clear it. If you start selecting a different date (e.g. in September), the view automatically scrolls to the position of the previous selection (June). Is just the view that changes the focus by automatic scrolling, the selection is correct to September.

Video [here](https://drive.google.com/file/d/1GnO0BYYjm1JH8FHMxqH7gfUvbfvOKzDq/view?usp=sharing)

## What browsers are affected?
All

**Comment by torch2424** [comment]
Triaging to @cvializ , feel free to re-assign 😄

**Comment by cvializ** [comment]
Hi @dbarcosb thanks for letting us know about your issue. I'm able to reproduce it and I've marked it to be worked on. We'll address it when we have effort available for its prioritization

**Comment by caroqliu** [comment]
Hi @danieltxok the original reproduce example is no longer available, though I do want to address the underlying bug in the video. Is it possible to provide a minimal code sample?

**Comment by danieltxok** [comment]
Hi @caroqliu,
Unfortunately am not the owner of that demo, the partner I was working with at that time removed it. I tried to build a minimal sample but couldn't replicate.

**Comment by caroqliu** [comment]
@danieltxok no worries, thank you for the heads up. I'll close the issue for now and we can re-open once we are able to reproduce.
