### ISSUE TITLE
amp-script: Support AMP.setState in JS

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amphtml#22410]
It seems `amp-script` does not support AMP's any of [actions and events](https://amp.dev/documentation/guides-and-tutorials/learn/amp-actions-and-events)—for example, it's not possible to listen for a `select` event from `amp-selector`, to fire the `show` action on arbitrary elements, or to use `AMP.setState(…)` from within a script.

/cc @choumx @kristoferbaxter

**Comment by westonruter** [comment]
See also https://github.com/ampproject/amphtml/issues/18615#issuecomment-427999056

**Comment by choumx** [comment]
Will work on this soon.

**Comment by choumx** [comment]
@ithinkihaveacat Do you have any `amp-script` actions/events in mind other than plumbing `AMP.setState()` to the worker?

**Comment by ithinkihaveacat** [comment]
I was thinking of events too, so that, for example, a `select` event on `<amp-selector>` could be received by `<amp-script>`:

```html
<amp-script src="...">
  <div id="foo">
</amp-script>

<amp-selector id="mySelector" layout="container" on="select:foo.dosomething" multiple>
  <div option>Option One</div>
  <div option>Option Two</div>
</amp-selector>
```

Is there any way for the script to listen for the `dosomething` event?

(Trying to test this again now, but running into the `amp-experiment-token` problem. Is there any way to get around that? Seems to want a token even for `localhost`.)

**Comment by choumx** [comment]
The way AMP actions/events works is that `dosomething` would have to be invoked on the `amp-script` element itself:

```html
<amp-script id=foo src="...">
</amp-script>

<amp-selector id="mySelector" layout="container" on="select:foo.dosomething" multiple>
</amp-selector>
```

And there's the question of what `dosomething` actually does. :) Is there a specific, higher level use case you had in mind? E.g. selecting an product on an e-commerce pages causes X. 

> Is there any way to get around that? 

Have you tried `AMP.toggleExperiment('amp-script')`?
