### ISSUE TITLE
Nested macro throw error if returned value is not a string

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#22423]
Reported by @zikas 
`$SUBSTR(TIMESTAMP, 0, 10)` throws an error and doesn't resolve. The reason is because `TIMESTAMP` in the nested macro resolve to a Number, but `SUBSTR` expects its argument to be as string. 

The potential root cause to this could be that we fail to convert the return type to string here. 
https://github.com/ampproject/amphtml/blob/4296d7ddd6d6530ba50d1b6f6a16c74d58a1e8e4/src/service/url-expander/expander.js#L328

Proposing two approaches to fix the issue

Approach 1. Always convert a macro returned value to string. 
-Pro: Because we agree on the generic behavior (always expect a string), it's going to be less error prone. 
-Con: Some macros makes less sense. For example `$IF` `$NOT`. And usage like EQUALS (#22160)

Approach 2. Have individual macro to convert args. For example here, have $SUBSTR convert input argument to a string first. 
-Pro: It makes more sense in some cases because the macro understand the usage the best. And can support the #22160 use case. 
-Con: A lot of effort to make sure each macro does the correct thing. I don't know if this lead to different code path for nested versus non nested macro. 

I'm leaning towards Approach 1, but want to get ideas on how can we better support use case like `$IF` `$NOT` and potential `$EQUALS`. 
On top of that, we are thinking about introducing `$INT` `$NUMBER()` macro. How does that work along with our implementation.

**Comment by zhouyx** [comment]
Discussed offline. Here's the summary. 
1. Due to the implementation of the expander, and the existing behavior we have. We decide to always convert value to a string. Each macro resolver need to handle type casting on their own if they require input type that's not a string. 

2. To support casting value type in request body.  Three approaches had been discussed. We decide to use the `extraUrlParamsReplaceMap` to support. 
 - `$INT` `$BOOLEAN` are two very special macro, which we don't want to introduce special check to our codebase. 
- `preserveValueType` to `extraUrlParams` could help preserving nested vars type
- [selected] `extraUrlParamsReplaceMap` is an object which provides a way to rename `extraUrlParams. Given only variables within `extraUrlParams` can be sent in request body, it's the right object to assign value type. 

Example usage:
```
'extraUrlParams': {
  'time': 'TIMESTAMP',
  'enabled': true,
  'other': 'RAMDOM'
}
'extraUrlParamsReplaceMap': {
  'time': {
    'name': 't',
    'typecast': 'number' 
  },
  'enabled': {
    'typecast': 'boolean'
  },
  'other': 'o'
}
```

**Comment by lannka** [comment]
Seems this is fixed?
