### ISSUE TITLE
`toggleClass` could remove internal `i-amphtml-` and `amp-` prefixed classes

### ISSUE THREAD

**Issue by xrav3nz** [ampproject/amphtml#22435]
## What's the issue?

`toggleClass` could remove internal `i-amphtml-` and `amp-` prefixed classes

## How do we reproduce the issue?

https://jsbin.com/fobefivecu/edit?html,output

```html
<button on="tap:html.toggleClass(class='i-amphtml-singledoc')">
  toggle <code>html.i-amphtml-singledoc</code>
</button>

<button on="tap:body.toggleClass(class='amp-mode-mouse')">
  toggle <code>body.amp-mode-mouse</code>
</button>
```

Clicking on the buttons will remove `i-amphtml-singledoc` and `amp-mode-mouse` classes.

**Comment by cvializ** [comment]
@choumx

**Comment by cvializ** [comment]
@ampproject/wg-ui-and-a11y

**Comment by choumx** [comment]
Nice find, we should fix this.

**Comment by aghassemi** [comment]
@choumx How does bind handle this with `[class]`? Private classes would be easy to handle in both `toggleClass` and `[class]` cases, for public ones like `amp-mode-mouse` (incl. element specific public ones like `amp-carousel-slide`), we would need to maintain a list.

**Comment by choumx** [comment]
amp-bind uses a regex to detect and preserve internal classes: https://github.com/ampproject/amphtml/blob/83cfcfff825012e7b2dc562f0841bb0c0486527b/extensions/amp-bind/0.1/bind-impl.js#L1212-L1232

**Comment by inidaname** [comment]
@aghassemi I will like to take this up, I will love if you could point to a little guide of how to approach this.

Thank You

**Comment by aghassemi** [comment]
@inidaname go for it and thanks! Change requires `toggleClass` code in `standard-actions-impl.js` to check the class name against the regular expression that another part of code already uses ( see comment @choumx  above ) and reject the toggling. Positive and negative unit tests would be important to add.

**Comment by cvializ** [comment]
An update: I don't see any usages of internal private `toggleClass(class='i-amphtml-foo')`, but there are some internal public classes like `toggleClass(class='amp-form-submit-error')`

**Comment by ahmadalfy** [comment]
@aghassemi I would love to work on this one. There is an optional argument called `force`; should that case check for amp specific classes as well or the check is cancelled if that argument is true?

**Comment by cvializ** [comment]
Feel free to work on it! I think the `force` parameter should also check, since it should only apply to the toggle state and not the internal class check.
