### ISSUE TITLE
[maybe] add platform specific classes amp-dynamic-css-classes

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#22437]
This will allow a user to hide/show platform specific section, or platform specific stylings by targeting the top level class added to the `body` (`isIOS`, `isAndroid`, etc.)

cc @aghassemi for approval since this has a lot of abuse implications

**Comment by aghassemi** [comment]
This was considered in https://github.com/ampproject/amphtml/issues/22060 and was ruled out.

**Comment by aghassemi** [comment]
We can bake variations when it makes sense based on compelling use-cases into components but a generic versions is not something we want to consider without much stronger arguments for it.

**Comment by aghassemi** [comment]
I will leave this open to collect feedback from the community.

**Comment by erwinmombay** [comment]
@aghassemi got it. apologies, didn't look it up if there was already an issue filed.
