### ISSUE TITLE
🌸 Cherry pick request for 22429 into 1905140117570 (Pending)

### ISSUE THREAD

**Issue by shackijj** [ampproject/amphtml#22433]
# Cherry-pick request

| Issue | PR  | Production? | RC? | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---: | :-: | :---------: | :-: | :-----------: |
| #22429 | #22431 | **YES** | **YES** | #22292 |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

Users see empty pubmine ad slots on AMP pages.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

**Comment by prateekbh** [comment]
// @prateekbh

**Comment by cramforce** [comment]
Approved

**Comment by prateekbh** [comment]
Version 1905222334000 is in opt in
