### ISSUE TITLE
🌸 Cherry-pick request for #22443 into 1905211840370 (Pending)

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#22449]
# Cherry-pick request

| Issue | PR  | Production? | RC? | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---: | :-: | :---------: | :-: | :-----------: |
| #22423 | #22443 | **No** | **Yes** | #22426 |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

The bug is blocking gtag from using the nested macro. And writing the cookie value on origin page. 

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

<_YOUR_SUMMARY_>

| Users affected | Impact |
| -------------- | ------ |
| <_Which users were affected? Roughly how many?_> | <_How were users affected? E.g. partial or complete loss of functionality?_> |

## Root Causes

1.

## Action Items

| Action Item | Type | Owner | PR # |
| ----------- | :--: | :---: | :--: |
| <_E.g. Add integration test_> | <_Investigate/Mitigate/Prevent_> | @<_USERNAME_> | #<_PR_NUMBER_> |

### Things that went well

-

### Things that went wrong

-

---

/cc @cramforce

**Comment by zhouyx** [comment]
to @prateekbh

**Comment by cramforce** [comment]
Approved for canary

**Comment by zhouyx** [comment]
cc @zikas as well.

**Comment by prateekbh** [comment]
Version 1905222334000 is in opt in
