### ISSUE TITLE
Dynamically generate custom closure compiler for AMP

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#22452]
Now that AMP's closure compiler is at the latest available version (#22446) modulo one awaited bug fix (https://github.com/google/closure-compiler/issues/3041), it's time to think about how to stay there as new releases appear.

**Here's my proposed solution:**
1. Wait for https://github.com/google/closure-compiler/issues/3041 to be fixed. After this, single pass can simply use `node_modules/google-closure-compiler-java/compiler.jar` with no changes.
2. Delete `third_party/closure-compiler/**` and `build-system/runner/dist/runner.jar`
3. Check in a copy of `ant` to `third_party/ant/`
4. Whenever `gulp dist` or `gulp check-types` are invoked, run a pre-requisite task that generates `runner.jar` by calling `ant clean && ant jar && ant test` and makes sure everything worked
 
**Notes:**
- Whenever a new version of closure compiler is released, a `renovate` PR will automatically test it out by generating a new `runner.jar`, running `gulp check-types`, performing a minified build, and running all our tests.
- If a breaking change appears, we will be alerted by build / test failures, and can make the required changes and move on.
- We'll no longer need to separately maintain `compiler-and-tests.jar` since we are no longer using a custom version of `compiler.jar`. The tests in `build-system/runner` should be sufficient to verify the custom AMP passes.
- The speed up gains for multi pass due to `nailgun` will remain as they are, since we'll continue to re-use a single instance of the dynamically generated `runner.jar`

**Comment by erwinmombay** [comment]
@rsimha number 4 would only be needed for multi pass correct?

**Comment by rsimha** [comment]
> @rsimha number 4 would only be needed for multi pass correct?

No, it's also used during single pass for these targets.

```
[13:41:41] Minified f.js (7.268 s)
[13:41:44] Minified ampcontext-v0.js (9.730 s)
[13:41:46] Minified iframe-transport-client-v0.js (11.975 s)
[13:41:48] Minified recaptcha.js (14.314 s)
[13:41:50] Minified amp-viewer-host.js (15.910 s)
[13:41:52] Minified video-iframe-integration-v0.js (17.774 s)
[13:41:54] Minified amp4ads-host-v0.js (19.796 s)
[13:41:56] Minified alp.js (21.845 s)
[13:41:58] Minified examiner.js (23.441 s)
[13:42:00] Minified ww.js (25.819 s)
[13:42:02] Minified experiments.js (27.367 s)
[13:42:04] Minified amp-web-push-permission-dialog.js (28.832 s)
[13:42:06] Minified amp-web-push-helper-frame.js (30.645 s)
[13:42:08] Minified amp-login-done-0.1.js → amp-login-done-latest.js (32.561 s)
```

**Comment by rsimha** [comment]
This is now truly done, and future updates should be automatic (modulo breaking changes). See https://github.com/ampproject/amphtml/pull/23759#issuecomment-520162085
