### ISSUE TITLE
Clean up `$weak$.js` after single pass compilation

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#22463]
During single pass compilation, closure compiler generates a file called `$weak$.js` (empty as of today). It stems from [this](https://github.com/google/closure-compiler/blob/maven-v20190513/src/com/google/javascript/jscomp/JSModule.java#L48-L52) place in the source code:

```js
  // The name of the artificial module containing all weak sources. Regardless of the module spec,
  // weak sources are moved into this module, which is made to depend on every other module. This is
  // necessary so that removing weak sources (as an optimization) does not accidentally remove
  // namespace declarations whose existence strong sources rely upon.
  public static final String WEAK_MODULE_NAME = "$weak$";
```

If the file isn't a necessary part of the AMP runtime, it should either be cleaned up, or not generated in the first place.

**Comment by rsimha** [comment]
An added data point: There are several instances of `[synthetic:es6/util/inherits]` in the sourcemap (`.map`) files generated during single pass (but not multi pass). I wonder if that is related to why single pass generates `$weak$.js`. See [this](https://github.com/google/closure-compiler/blob/maven-v20190513/src/com/google/javascript/jscomp/JSModule.java#L289-L295) place in the source code: 

```js
  /**
   * Returns whether this module is synthetic (i.e. one of the special strong or weak modules
   * created by the compiler.
   */
  public boolean isSynthetic() {
    return name.equals(STRONG_MODULE_NAME) || name.equals(WEAK_MODULE_NAME);
  }
```

**Comment by jridgewell** [comment]
This seems like a closure bug?

Either way, we actually do have the inherits synthetic in multipass builds. It's how we can do `class Foo extends Bar {}`.

**Comment by rsimha** [comment]
> Either way, we actually do have the inherits synthetic in multipass builds. It's how we can do `class Foo extends Bar {}`.

I was referring to the fact that `.map` files contain `[synthetic:es6/util/inherits]` for single pass, but not multi pass.

**Comment by rsimha** [comment]
@erwinmombay IIRC, this file came in the way of a release earlier this month, didn't it? Can you add detail? Is cleaning up the file the correct action?
