### ISSUE TITLE
Story video: should not display the "play video" button if the loading error was a 404

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#22473]
When a video fails to play, the story runtime shows a "play video" button, that will retry the video playback.
If the video error was a 404, retrying likely won't play the video. We should not display the button in the first place, but replace it with an error message.

**Comment by newmuis** [comment]
Not sure if it's easier to address this as a separate issue, but we should also probably not show the "play video" button more than once per video.  i.e, if we show a "play video" button and the user clicks it, resulting in another error, we should actually just display an error message.

**Comment by gmajoulet** [comment]
cc @hongwei1990 can we re-use that mock?

![image](https://user-images.githubusercontent.com/1492044/60030004-35862c80-9670-11e9-8e26-aad9d57ba2d5.png)

**Comment by hongwei1990** [comment]
sure, is this one good enough?
