### ISSUE TITLE
amp-bind: Support regex syntax

### ISSUE THREAD

**Issue by ashish-r** [ampproject/amphtml#22491]
## Describe the new feature or change to an existing feature you'd like to see
I need to filter all non-alphanumeric characters from string. I am using `amp-bind-macro`  with regex to achieve this.
`<amp-bind-macro id="cleanString" arguments="str"
expression="str.split(/[^0-9a-z]/gi).join('')">
</amp-bind-macro>`

But I am getting the error: 

>  amp-bind-macro#cleanString.i-amphtml-element.i-amphtml-layout-container.i-amphtml-error.i-amphtml-element-error %s amp-bind: Parsing amp-bind-macro failed. Parse error on line 1:
> str.split(/[^0-9a-z]/gi).join(
> ----------^
> Expecting '(', ')', '!', '-', '+', 'NAME', '[', 'STRING', 'NUMBER', 'TRUE', 'FALSE', 'NULL', '{', got '/'​​​

which means regex is not allowed inside split. But It would be nice to have this feature as it is very common to use regex as it is optimized if compared to iterating over and checking for allowed or not allowed characters

## Describe alternatives you've considered

Other alternatives require storing allowed or not allowed characters in state and then splitting string to form an array of characters and filtering those characters
`str.split('').filter(x => allowedCharsState[x]).join('')`

**Comment by jaygray0919** [comment]
bump
