### ISSUE TITLE
Visual diff tests ignore animations

### ISSUE THREAD

**Issue by sparhami** [ampproject/amphtml#22499]
The visual diff tests currently ignore animations. This prevents the screenshot from capturing the end state of animations when using something like `animation-fill-mode: forwards`. As a result, we had to disable the visual diff tests for `<amp-sidebar>` in #22324. This also affects #22495.

If possible, the visual diff tests should do something like run animations with `animation-duration: 0 !important`, before taking the screenshot rather than disabling animations entirely.

**Comment by sparhami** [comment]
A page on Percy's website about freezing animations: https://docs.percy.io/docs/animations. They say that they:

> Freeze most CSS animation and transition styles.

but do not elaborate on what "most" means or if there is a way to get your animations to go to the end state.

**Comment by sparhami** [comment]
For #24504, it would additionally be useful to be able to set animations to a specific point in time before taking a screenshot. This can be done by setting a negative `animation-delay` value, taking into account any existing `animation-delay` that is present.

**Comment by rsimha** [comment]
Assigning to @danielrozenberg for triage / prioritization.

**Comment by danielrozenberg** [comment]
After talking to Percy about how they handle animations, we now know we can't control the exact snapshot point of the animation. Closing this as wontfix
