### ISSUE TITLE
Separate `gulp test` into `gulp unit` and `gulp integration`

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#22507]
Today, all of AMP's unit and integration tests are run by [build-system/tasks/runtime-test/index.js](https://github.com/ampproject/amphtml/blob/b1afbe2d15ca011fe662ff39a8bbfac7fd03bebb/build-system/tasks/runtime-test/index.js), which is 700+ lines long and growing. However, unit tests and integration tests use different sets of configs, flags, test files, and pre-requisite tasks, and serve different purposes. Let's split them into two tasks called `gulp unit` and `gulp integration`.

**Things to do:**

- [x] Move [code coverage report uploading](https://github.com/ampproject/amphtml/blob/b1afbe2d15ca011fe662ff39a8bbfac7fd03bebb/build-system/tasks/runtime-test/index.js#L561-L594) (Travis only) into a new `gulp codecov-upload` task that's run at the end of `Local Tests` (Done in #22515)
- [x] Move task-specific code from `tasks/runtime-test/index.js` into `tasks/unit.js` and `tasks/integration.js`
- [x] Move common code into `tasks/runtime-test/helpers.js`
- [ ] Simplify [`getConfig()`](https://github.com/ampproject/amphtml/blob/b1afbe2d15ca011fe662ff39a8bbfac7fd03bebb/build-system/tasks/runtime-test/index.js#L62-L145), [`printArgvMessages()`](https://github.com/ampproject/amphtml/blob/b1afbe2d15ca011fe662ff39a8bbfac7fd03bebb/build-system/tasks/runtime-test/index.js#L147-L240), and [`runTests()`](https://github.com/ampproject/amphtml/blob/b1afbe2d15ca011fe662ff39a8bbfac7fd03bebb/build-system/tasks/runtime-test/index.js#L242-L453)
- [x] Refactor `tasks/report-test-status.js` to understand the new gulp task structure
- [x] Update `TESTING.md`

/cc @ampproject/wg-infra

**Comment by rsimha** [comment]
@estherkim Since you worked on #20117, and wrote `gulp e2e`, could I assign this to you? :smiley:

**Comment by danielrozenberg** [comment]
Modified the description to also mention changes required to `tasks/report-test-status.js`

**Comment by estherkim** [comment]
Okiedokie
