### ISSUE TITLE
Image carousel animation on partial swipe is stilted

### ISSUE THREAD

**Issue by rannazhou** [ampproject/amphtml#2250]
Browser: Safari on iOS 9.2.1

Steps to repro:
- Swipe fast and very minimally (as in, not enough for the image carousel to actually switch to next image).
- Observe that animation of the second image away off of the screen is choppy.

https://www.google.com/amp/www.chron.com/news/politics/amp/Ben-Carson-says-Obama-was-raised-white-6849347.php?client=safari#fpstate=amp_viewer

**Comment by ericlindley-g** [comment]
@rannazhou , are you able to repro? I tried this again recently and didn't see an issue.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
