### ISSUE TITLE
Synchronize the call to `reportAllExpectedTests()` in `checks.js`

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#22509]
Today, `build-system/pr-check/checks.js` calls `reportAllExpectedTests` right at the start, before running its checks. Yet, the actual reporting appears to be getting done [at the end](https://travis-ci.org/ampproject/amphtml/jobs/536974514#L390) of the task.

https://github.com/ampproject/amphtml/blob/da14fb6118e134799083447800ba4a65cee688fe/build-system/pr-check/checks.js#L68-L102

As a result, when one of the checks fails, expected tests aren't reported. For example, [here](https://travis-ci.org/ampproject/amphtml/jobs/536667569#L398).

I think an `await` is missing before `reportAllExpectedTests(buildTargets);`

**Comment by rsimha** [comment]
While you're fixing the above bug, I think a behavior change might be in order.

Today, all expected tests are reported at the start of the `Checks` job. However, if a different job like `Build`, `Dist`, or `Validator` were to fail, the test statuses remain in the pending state.

I think it's better to report expected tests at the start of the job that executes them, so that they are guaranteed to get to a pass / fail state.

**Comment by danielrozenberg** [comment]
The idea of putting the "pending" check early on is to let PR authors know what to expect. I'd rather not move them to the same shard as the actual test runner. If the Travis checks fail and the status stays as "pending", the PR's total status is still going to be red because of the Travis failure
