### ISSUE TITLE
Seeing "Uncaught (in promise) no handler found"

### ISSUE THREAD

**Issue by aprigogin** [ampproject/amphtml#2251]
I am seeing: "Uncaught (in promise) no handler found" error on the console. 
I am also seeing same message coming from some publisher pages which sometimes marked as "?amp_v_js=3", sometimes "***somearticleurl***.php".

Trying to understand whether it is our viewer issue or not.

**Comment by cramforce** [comment]
Most likely not. To debug we'd need a URL. ?amp_v_js=3 is something you append to the URL to trigger the viewer integration.

**Comment by aprigogin** [comment]
After making some changes from our side, the error messages went away. The changes were related to how we tear down amp iframes.
