### ISSUE TITLE
amp-script: Sharing JS across multiple elements e.g. frameworks

### ISSUE THREAD

**Issue by demil** [ampproject/amphtml#22514]
As i understood right now if we have multiple amp-script depended components and they are all "preact" javascript components for example we would need to load "preact" library in bundle multiple times? 

Is there any possibility to share same dependency for multiple amp-script components?

**Comment by torch2424** [comment]
Triaging to @kristoferbaxter , feel free to re-assign 😄 

cc @choumx

**Comment by kristoferbaxter** [comment]
This makes sense as a requirement, we'll add this capability in.
