### ISSUE TITLE
AMP stories only work on Edge full screen

### ISSUE THREAD

**Issue by Stefany93** [ampproject/amphtml#22520]
## What's the issue?

When I load an [AMP story ](https://edition-cnn-com.cdn.ampproject.org/c/s/edition.cnn.com/ampstories/world/protecting-the-antarctic-a-journey-to-a-continent-in-distress) on Edge on desktop, I get an error telling me to "Expand the height of my window to view this experience" ([screenshot](https://prnt.sc/nu4ebo))
## How do we reproduce the issue?

1. Go to this AMP story https://edition-cnn-com.cdn.ampproject.org/c/s/edition.cnn.com/ampstories/world/protecting-the-antarctic-a-journey-to-a-continent-in-distress (or any other)
2. The error will appear
3. Only after pressing F11 (aka full screen) does the story play.

## What browsers are affected?

Microsoft Edge 42.17134.1.0

Tried it on screen resolution 1920x1080

**Comment by aghassemi** [comment]
to @newmuis

**Comment by newmuis** [comment]
This is actually not about the browser, but about the size of the window; unfortunately, we require oddly specific browser window sizes for this to render.  Leaving this open to track that, although I think this will take some design thinking to resolve.

**Comment by Stefany93** [comment]
@newmuis But it plays great all on other browsers except edge? On the same monitors ?

**Comment by newmuis** [comment]
Yes, this may mean that with the zoom levels, screen resolution, and window size used on your machine, Edge is smaller and falls below the viewport size threshold.

I've verified it works on two other Edge machines, and the fact that it also works on yours on the larger (fullscreen) viewport size suggests the same.

However, that doesn't make this behavior good or correct; just outlines the particular fix we need to make: in this case, relaxing the viewport size restrictions to allow it to show on a wider range of screen sizes.

**Comment by Stefany93** [comment]
^^ Thank you @newmuis
