### ISSUE TITLE
[amp-state] Persist amp-state on cookie or SessionStorage

### ISSUE THREAD

**Issue by eduardogoncalves** [ampproject/amphtml#22527]
Persist **amp-state** on cookie or SessionStorage like is done at amp-accordion, so if user hit **browser refresh button/F5**, the state maintains.

Ex.: In a SPA, an user select Tweets tab, and hit browser refresh button and when page reloads it should maintains Tweets tab selected instead of back to default state.

![image](https://user-images.githubusercontent.com/4308648/58480414-51a5b500-8128-11e9-8e66-b25975e07f17.png)

**Comment by eduardogoncalves** [comment]
amp-bind has **AMP.setState** and **AMP.pushState**, what if we add something like *AMP.storeState*

**Comment by aghassemi** [comment]
@nainar This is essentially stateful page transitions, when we add a master issue for it, we can dedup it

**Comment by eduardogoncalves** [comment]
related to #12360

**Comment by nainar** [comment]
Deduping in favour of #12360
