### ISSUE TITLE
Google AMP Viewer shows desktop images

### ISSUE THREAD

**Issue by joshin2017** [ampproject/amphtml#22526]
Google AMP Viewer shows desktop images. Website is adaptive. Any clue? Images on xyz.com/amp shows correct images but when we look into google ampviewer its showing images with different dimension.

**Comment by torch2424** [comment]
Hello!

Could you please provide an example AMP article where this problem is occuring? And if possible, and exact image on the article? Thanks! 😄 

cc @aghassemi

**Comment by aghassemi** [comment]
Please reopen with more details such as links to repro the issue.
