### ISSUE TITLE
I2I: AMP Form Dirtiness Indicator Class

### ISSUE THREAD

**Issue by xrav3nz** [ampproject/amphtml#22534]
## Summary

This proposes a new `amp-form-dirty` class, that will be applied to AMP form’s `<form>` element, when any of its containing form controls is dirty.

This allows AMP document developers to style forms differently when it has been modified by the user, and there are unsubmitted data.

## Design Document

https://docs.google.com/document/d/16Q3yY-XRtCVjlcsRYkrXYlmZJfcIrFgnMKqXsy3nS4w

## Attack Plan

- [x] Export [`isDisabled` helper](https://github.com/ampproject/amphtml/blob/f7d6f31ceeb1b937a68172f2e0dd9d71e5dc3d7d/src/form.js#L148-L152)
- [x] Extract an `isFieldDefault` helper from current [`isDirty_`](https://github.com/ampproject/amphtml/blob/7501cf57ee2424372d60eeea309b5a53f09ca855/extensions/amp-form/0.1/form-verifiers.js#L119-L140) implementation
- [x] An `isFieldEmpty` helper that checks if a field is empty
- [x] Track text-type `input`s and `textarea`'s dirtiness, based on default value and emptiness
- [x] Track radio button, checkbox, and dropdown menu's dirtiness, based on default value and emptiness
- [x] Track submitted form data
- [x] Track `amp-bind` form values changes

## Potential Future Improvements
- Support custom AMP components (e.g. `<amp-selector>`)
- Track some attribute changes (`disabled` and `hidden`) with a Mutation Observer

/cc @cvializ @GoTcWang @zhangsu

**Comment by aghassemi** [comment]
Although this is doable with `amp-bind` it will be a lot of work with lots of unnecessary event handlers and state comparison to do it for a complex form. 

👍 for this ITI. One question I have that I could not figured out in the design doc is whether programmatically setting `value` of an `input` (maybe via `amp-bind` or later via `amp-script`) will make it dirty. By default I think yes, but there might be use-cases where programmatically setting value is should not be considered dirty. Worth adding thinking about and adding a section to the doc about it.

**Comment by andrewwatterson** [comment]
Hey @xrav3nz - this sounds great. I'm curious what types of experiences this might be used to enable, though. Can you add some examples of ways this might be used to the doc?

**Comment by xrav3nz** [comment]
> whether programmatically setting `value` of an `input` will make it dirty

I didn't think of this before, thanks for bringing it up @aghassemi! Since changing `value` directly does not fire an `InputEvent`, the current approach will **not** mark the input as dirty. 

In order to support detecting `amp-bind` changes, would dispatching a custom event when an `amp-bind` evaluation changes be up for discussion? This would actually also help detecting certain attribute changes, like `disabled` and `hidden`.

I will also explore some other options, and add them to the doc.

**Comment by xrav3nz** [comment]
> what types of experiences this might be used to enable

Good point, I will revise the doc to include some examples @andrewwatterson! Aside from different visual styling, the viewer could also leverage this to alert the user when they're navigating away from unsubmitted data.

**Comment by aghassemi** [comment]
@xrav3nz Dispatching custom events as a way of doing internal communication is totally fine, we do it all over the place. Internal events names are usually prefixed with `amp:`. These events won't be exposed externally be default anyway, so there is no risk of authors running actions by listening to these events.

**Comment by aghassemi** [comment]
`amp-bind` fires a custom `AmpEvents.DOM_UPDATE` event anyway whenever mutations happens (Other components like `amp-list` that can generate new DOM nodes including form elements, also fire it). Listening to that might be enough to for case. @xrav3nz

**Comment by andrewwatterson** [comment]
@xrav3nz I guess my question is "what's an example of when you'd want different visual styling on a dirty value"?

@sparhami points out that this may be useful to curtail overly-aggressive native-HTML form validation that could try to validate empty/potentially already submitted values? In which case I can totally see the use case: forms that try to validate empty inputs if I've focussed/blurred them are extremely annoying.

So if the observation is that
```.my-input:invalid { style: holyShit; }```
regularly yields overly aggressive form validation, instead I'd do
```.my-input.amp-dirty:invalid { style: holyShit; }```
? But I'm also making a lot of assumptions here based on a 30 second conversation with Sepand. :)

**Comment by GoTcWang** [comment]
@andrewwatterson 
Hey Andrew, thanks for the comments! We should put more background in the doc. I guess we didn't put too much thoughts on the visual styling part. We are trying to have the feature of prompting users from navigating away if there are dirty forms. And this is the first step, followed up by querying such class at document level. 

However, on a second thought, styling might also benefit from this class, as you said. In case of multiple amp-forms in one doc, at least we can have some indications on which one has some unsubmitted data so users can easily find out. WDYT?

**Comment by xrav3nz** [comment]
An update on form changes made by `amp-bind`:

After experimenting and digging into the code, `amp-bind` does not seem to fire `AmpEvents.DOM_UPDATE`. It [listens to the event](https://github.com/ampproject/amphtml/blob/7fa4543d579a4c6afbbf00d0090832d25191368e/extensions/amp-bind/0.1/bind-impl.js#L507-L508) to rescan the DOM for bindings.

I am proposing a new custom event `BindEvents.MUTATE`. It is dispatched whenever an `amp-bind` mutation happens. An additional event handler will determine the dirtiness of the form fields mutated by `amp-bind`. This is also helpful for detecting attribute changes like `disabled`. 

There is one unexpected `amp-bind` behavior --  binding the `value` attribute on `<input>` element has a side effect of  updating its `defaultValue` property (#18921). It is planned to create separate bindings for `[value]` and `[defaultValue]` (https://github.com/ampproject/amphtml/issues/21053#issuecomment-490593511), to resolve the ambiguity. This will also help the AMP document author to clarify their intent behind the binding.

(will also update the doc shortly)
