### ISSUE TITLE
Error AdSense reports

### ISSUE THREAD

**Issue by wlorenzo** [ampproject/amphtml#2254]
Yesterday afternoon, I officially launched my site in AMP. 
Immediately AdSense stopped counting impressions and earnings in the reporting for the web site or url channel.
Instead impressions and earnings for advertising or for custom channel units have counted correctly impressions and clicks, and therefore earnings.

I have successfully got the validation by AMP # development = 1 and I see correctly ads.
After a few hours my results in AMP came out for some queries and even on g.com/ampdemo

Is there any recognized problem or Ineed a custom implementation of the tag amp-ad?

I use this code:
`<amp-ad width=320 height=100
              type="adsense"
              data-ad-client="ca-pub-XXXXXXXXXXXXXXXX"
              data-ad-slot="XXXXXXXXXXX">
          </amp-ad>`

And I call just this 4 script:
https://cdn.ampproject.org/v0.js
https://cdn.ampproject.org/v0/amp-iframe-0.1.js
https://cdn.ampproject.org/v0/amp-analytics-0.1.js
https://cdn.ampproject.org/v0/amp-user-notification-0.1.js

Thank you
Lorenzo

**Comment by cramforce** [comment]
Are ads showing?

**Comment by wlorenzo** [comment]
Yes, correctly

**Comment by cramforce** [comment]
Any change you could ping adsense support?

Would need to debug with your actual data.

**Comment by wlorenzo** [comment]
Yes,
but I haven’t received an answer, for the moment.

Right now I changed address of the AMP website, now you can find here:
http://amp.businessonline.it

Lorenzo

**Comment by nachitox** [comment]
The same is happening to us. Any clues ?
