### ISSUE TITLE
amp-sidebar not opening in Firefox

### ISSUE THREAD

**Issue by karsten-eger** [ampproject/amphtml#22553]
## What's the issue?
Today we noticed the toggling to open/close amp-sidebar is not working in Firefox anymore.
When pressing the toggle element the page fades and nothing else happens. The sidebar is not opening.

## How do we reproduce the issue?
I cannot provide our page as an example right now because we fixed it by using an older amp release in the meantime. But even the AMP Example page is also affected:

https://amp.dev/documentation/examples/components/amp-sidebar/preview/?referrer=ampbyexample.com

1.) Open this page in Firefox
2.) Use one of the buttons to toggle the bars - none of those is working

## What browsers are affected?
Noticed in Firefox (67, mobile (android) and desktop (macos))
It's working in Chrome!

## Which AMP version is affected?
Latest - 1905222334000
I tried using one version back . 1905211840370. This did not work either BUT I'm not confident to say this was my error. :( I went further back then to resolve the issue.

So we switched to 1905091827220 for now. It's working here.

**Comment by eduardogoncalves** [comment]
I can confirm this issue.
On left is Firefox and on right Chrome

![image](https://user-images.githubusercontent.com/4308648/58555371-4c5b6f80-81e7-11e9-96cb-1d5da44c3def.png)

**Comment by aghassemi** [comment]
Looks like a regression from #22531 . 

I think issue is with `!important` in the initial `transform: translateX(100%);` rule. Looks like animation properties in FF do not have higher specificity than `!important`, unlike blink/wekit. 

Which is probably a good thing, see: [More important than important](https://paulbakaus.com/2017/07/27/more-important-than-important/) which a post based on some fun and confusing debugging session me and Paul did a while back.

/to @sparhami let's target patching at least Canary.

**Comment by aghassemi** [comment]
There is already a cherry pick request for Prod (https://github.com/ampproject/amphtml/issues/22561) might be worth piggy backing on that (maybe via a clean revert)

**Comment by jaygray0919** [comment]
we see the same: https://playground.amp.dev/?url=https://preview.amp.dev/documentation/examples/components/amp-sidebar
FF amp-sidebar was working 2 days ago (May 27) if that helps identify a change

**Comment by jaygray0919** [comment]
back to normal
