### ISSUE TITLE
Stacking up browsing history when new amp story is opened from bookend! 

### ISSUE THREAD

**Issue by dhruva205** [ampproject/amphtml#22564]
Opening up a new story from the amp-stories bookend adds up a new URL in the browsing history (previous story URL and now new story URL in the browsing history) .
User going through multiple stories will lead to a long history generation in the browser , so at this point if user click back button(browser or other physical back button) he/she will go through all those stories again..

The current bookend works this way..
Code Sample
<amp-story-bookend layout=nodisplay> <script type="application/json"> { "bookendVersion": "v1.0", "shareProviders": ... "components": [ { "type": "heading", "text": "More to read" }, { "type": "small", "title": "This is India an the best places you should go", "url": "http://localhost/app/posts/p10/", "image": "http://placehold.it/256x128" } ] } </script> </amp-story-bookend>

When clicking the bookend component, it will load the URL specified in it.
If i do not mention the "url" tag , the component don't show up in the bookend.
I need something like to execute location.replace(url) or if we can specify the id tag in components to run a script on event click listener of the "id" along with giving tag of "no url" which will specify that the url is not required for this component or a tag which will specify the new tab opening or new url opening or replacing url

**Comment by torch2424** [comment]
Triaging to @newmuis , feel free to re-assign 😄

**Comment by newmuis** [comment]
This is the expected behavior.  As you link to another story, it's a new page and therefore has an entry in the history, just like other webpages.

@dhruva205 are you intending to link to another document?  Or are you trying to create some other type of behavior?

**Comment by dhruva205** [comment]
@newmuis  i just don't want to keep up the history of previous story in the browser.
Say for example we have home_url, url1, url2, url3.
if we execute them as 
from home_url we go to 
location.replace(url1);  // loading url1 (say its a url of story)
location.replace(url2);  // loading url2 (say its a url of story, which we opened from the bookend of url1 story)
location.replace(url3);   // loading url3 (say its a url of story, which we opened from the bookend of url2 story)
the url2 and url1 will not be available in the browser history ( if behavior of location.replace(url) is followed).
So, if at url3, i click the back button , it will take me to the home_url instead of following url2 then url1 then home_url (if sequence gets executed in a way as location.replace script type)
So like, you can add a tag just like url tag inside the bookend which will specify either to save the history or not...

I know what currently  happening is its default behavior , but above mentioned thing is something i need!
Thank you for your reply!

**Comment by newmuis** [comment]
Hi @dhruva205, this behavior is kept consistent across all stories, to ensure a consistent user experience.  The behavior you're describing is the intended behavior.

Have you considered other navigational affordances to help users more easily navigate to your homepage, such as the sidebar menu>

**Comment by dhruva205** [comment]
> other navigational affordances

Ya i tried them , and i even added my custom button/href to go to the home page.
The thing i am asking is actually because i wanted my ui to work that way. 
Because many a times i feel like exiting from stories using phone back button (like on instagram , with back click ) 
If u can add an attribute (as i asked earlier) like 
`url_load_option : stack(current working) / replace (the one um asking) `
which will allow developer to keep it the way they want.



> is the intended behavior.

Ya i know that ( i just need this other option )
Or can you guide me through the file/location where this functionality is defined!

**Comment by newmuis** [comment]
The behavior desired here would now be possible using the `amp-story-player`.
