### ISSUE TITLE
🌸 Cherry-pick request for #22558 into #22426 (Approved)

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#22561]
# Cherry-pick request

| Issue | PR  | Production? | RC? | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---: | :-: | :---------: | :-: | :-----------: |
| #22558 | #22560 | **Yes** | **Yes** | #22426 |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

Bug introduced in swg.js library causes subscribe withe google button to fail to render on amp pages.

# Mini-postmortem

## Summary

A new feature introduction in the swg.js library accidentally changed a nullable parameter to non-nullable causing an exception when `amp-subscriptions-google` passed a null value.

| Users affected | Impact |
| -------------- | ------ |
| Unknown | Users were unable to see the subscribe with google button and as a result unable to invoke the Google buyflow.  |

## Root Causes

1. When the `smartButton` experimental feature was merged the API was changed from a nullable second `options` parameter to non nullable and the smartButton code did not correctly handle the null case. 

## Action Items

| Action Item | Type | Owner | PR # |
| ----------- | :--: | :---: | :--: |
| Investigate better type checking conformance. | Investigate | @jpettitt | N/A |

### Things that went well

The issue was immediately apparent once reported and the fix was simple.

### Things that went wrong

Type checking does not operate across 3rd party API's like swg.js.  Fix deployment was complex due to the need to deploy the swg.js library then integrate the update into amp and cherry pick to productions.

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by dvoytenko** [comment]
Approved.

**Comment by jpettitt** [comment]
PR is merged.
