### ISSUE TITLE
amp-ad friendly iframe embedding fails due to static function being stripped

### ISSUE THREAD

**Issue by zombifier** [ampproject/amphtml#22572]
Related issue: #21545.

## What's the issue?

After #22446, which among other things remove the `@nocollapse` tag from `installInEmbedWindow`, friendly frame rendering for amp-ad breaks with the following error:

![image](https://user-images.githubusercontent.com/12178173/58584650-c1996580-8224-11e9-982a-af5ca3253e45.png)

This is due to the static function `installInEmbedWindow` of various AMP services being stripped from compiled code. Additionally it is responsible for the amp-a4a test failing (it was flaking before, but now it fails).

## Steps to reproduce

1. Build AMP at HEAD with `gulp dist --fortesting`
2. Load `examples/a4a.amp.html` on the `gulp serve` server with serve mode set to "compiled".
3. Observe that the fake ad (topmost ad) and the doubleclick a4a ad (bottommost ad) is no longer being put inside a friendly iframe along with the above console errors.
4. Switch serve mode to either "default" or "cdn" and see the problem does not occur.

The obvious solution is to reinstate the tag (see #22504), but I want input on how we should proceed with this.

## Affected releases

None, as #22446 is not part of any releases yet.

**Comment by zombifier** [comment]
@lannka

**Comment by lannka** [comment]
@zombifier pls confirm but reading the description seems a high priority issue.
@calebcordry pls hold the canary cut, to prevent this bug being released

@rsimha do you think we'd revert your PR, or should we go with @zombifier 's fix #22504

**Comment by rsimha** [comment]
@zombifier Nice sleuthing. Thanks for investigating.

My preference is to apply the fix in #22504, since we'd like to keep moving forward with compiler updates and make sure our code uses the correct set of annotations when necessary.

**Comment by lannka** [comment]
@rsimha are we confident these are the only breakage? I don't know how @zombifier caught this, but I'm a bit worried if there could be other places need this new annotation.

**Comment by rsimha** [comment]
Yes, just checked, there are exactly 8 spots from https://github.com/ampproject/amphtml/commit/206027c763bfb227eea98d9b5ae630f7202777e5 that need `@nocollapse` to be reinstated, and #22504 addresses all 8 spots.

**Comment by zombifier** [comment]
Closing this since the PR is merged.
