### ISSUE TITLE
AMP Stories not showing up in sidebar of Wordpress

### ISSUE THREAD

**Issue by MomentumAdvertising** [ampproject/amphtml#22573]
**AMP Stories plugin not working in WordPress.**

We have version 5.2.1 of WordPress
we have downloaded AMP, Gutenberg, and AMP Stories and the AMP Stories plugin does not show up in the sidebar menu. How can this be fixed?

**Comment by torch2424** [comment]
Triaging to @amedina , feel free to re-assign 😄

**Comment by amedina** [comment]
@MomentumAdvertising Can you file an issue here: https://github.com/ampproject/amp-wp

**Comment by amedina** [comment]
Tracking in https://github.com/ampproject/amp-wp/issues/2475

**Comment by swissspidy** [comment]
@torch2424 Feel free to close this issue here as we're tracking it separately now. Thx!

**Comment by torch2424** [comment]
@amedina @swissspidy Thank you very much! 😄
