### ISSUE TITLE
amp-form erroneous usage of renderTemplateArray

### ISSUE THREAD

**Issue by alabiaga** [ampproject/amphtml#22570]
ssrTemplateHelper was introduced to abstract the work for rendering templates. In amp-form, when the data set returned from a form submission is a JSON array then the template service will try to apply that array data set to the template for rendering. This will cause an error when trying to render the template as the returned type is the unexpected array of elements as opposed to one element.

1. Create a form with an action-xhr that will return return a JSON array. e.g. [null, null]. Also add a submit-success message.
2. Submit form and submit-success msg will not display, along with js console error.

See: https://stackoverflow.com/questions/56342836/amp-mustache-success-error-messages-not-displaying/56345478#56345478

Demo for testing purposes as provided by user: https://www.craigattachments.com/test-form.php

Solution: amp-form should assert that rendered is only 1 element or that the data passed to renderTemplate is always of type json object data {} and not []?

**Comment by cvializ** [comment]
I don't think this fix is needed since they can remove the template tag from their markup to show the success message, since they don't use the response data. If they don't want the data to render as an Array, they should not pass the data as an Array.

```html
<div submit-success>
  <template type="amp-mustache">
    Thanks, your message has been sent successfully.
 </template>
</div>
```

Is there a doc or documentation that specs out how different response payloads should be rendered by the `ssrTemplateHelper`?

**Comment by craigscott29** [comment]
@cvializ yeah I was able to get around my problem my taking it out of the array - was unsure why it was in an array to begin with. @alabiaga mentioned potentially making the error message received a little more clear on Stack (linked in the OP).
