### ISSUE TITLE
submit-success and submit-error elements of amp-form are not enforced to be direct children of <form>

### ISSUE THREAD

**Issue by zhangsu** [ampproject/amphtml#22586]
## What's the issue?

I think AMP used to enforce that elements with `submit-success` or `submit-error` attributes must be a direct child of the `<form>` element according to #6516, but it looks like neither the validator or the runtime enforces this anymore.

AMP documentation says they must be direct children of `<form>`:
https://amp.dev/documentation/components/amp-form#to-render-responses-with-templating:

## How do we reproduce the issue?

The following AMP HTML passes validation and runs fine at runtime:

The following seems to be valid AMP now:

```html
    <form id="amp-form-success" method="post" action-xhr="https://example.com/test">
        <div>
            <input type="text" name="name" placeholder="name" required>
            <input type="email" name="email" placeholder="email" required>
            <input type="date" name="date" required>
            <input id="submit-success" type="submit" value="submit">
            <div submit-success>
                <template type="amp-mustache">{{items.request-form.name}}</template>
            </div>
            <div submit-error>
                <template type="amp-mustache">error</template>
            </div>
        </div>
    </form>
```

## What browsers are affected?

All browsers

## Which AMP version is affected?

Tested with 1905291911450

**Comment by caroqliu** [comment]
It looks like the enforcement was removed in #16771 with relevant discussion in #16500. Am I understanding correctly that this issue is filed regarding the documentation/behavior inconsistency, and not necessarily recommending conformance in one direction or the other? If so, the only fix needed for this is an update to the `amp-form` documentation.

**Comment by zhangsu** [comment]
Fixing the documentation SGTM. Personally I don't care if it's enforced.
