### ISSUE TITLE
Side effects with GET parameters for AMP pages ?

### ISSUE THREAD

**Issue by neveldo** [ampproject/amphtml#2259]
Hello,

We would want to  switch from a regular page to the AMP version by using a GET parameter. The AMP version of `www.example.com/article` would be `www.example.com/article?amp=1`.

I wonder if using such a parameter instead of a regular `.amp` extension or `/amp/` directory would have any negative side effect, maybe regarding the indexation of the AMP pages or the cache policy of the AMP CDN ?

Thanks in advance  !

**Comment by rudygalfi** [comment]
@neveldo What you want to do should work. Let us know if you observe any issues doing that.

**Comment by serdarde** [comment]
Hi, I want to make the same thing. Can you please tell me how was the google's reaction about this? Should I go on?

**Comment by cramforce** [comment]
This isn't a good place to ask questions about Google. Having said that, using query strings is pretty common practice.

**Comment by serdarde** [comment]
Okay, thaks @cramforce
