### ISSUE TITLE
Serving AMP content from an API and if the content doesn't exist

### ISSUE THREAD

**Issue by jeremy-green** [ampproject/amphtml#2260]
We currently have a monolithic CMS and serve our regular web based pages out of it.  We also have a content API which does it's best to ingest our content.  However, due to different front end consumers (Facebook Instant Articles, Apple News), we have to exclude some pieces of content.  When we launch AMP, we'll be adding

`<link rel="amphtml" href="http://amp.example.com/url/to/document.html">`

to all of our pages served out of the monolithic CMS.  The AMP document will be a different front end consumer, served on a sub domain and will hit our content API for the data and render out the respective HTML if the page exists in that endpoint.  If the page does not exist, we will redirect them back to the original, non AMP page with a 302 status code.

Our AMP endpoint has no notion if the content is available in the API and our CMS has no idea if the piece of content has been consumed by our content API so the tag will need to live on every page.

* Is this the correct behavior?
* Is a 302 redirect the correct status code since we may open up previously excluded pieces of content as the platform matures
* If not, what should the expected behavior be?

**Comment by tomremo** [comment]
Of course the best case would be if your CMS were able to selectively include the "rel" link only if the AMP document exists.

Barring that, it would preferable to return a 404 to indicate that the AMP document does not exist, and would be consistent with what others have done. A 302 would cause Google's and other potential caches to follow the redirect only to ultimately discard the result as an invalid AMP document.
