### ISSUE TITLE
Custom Java-script execution with onclick or with href

### ISSUE THREAD

**Issue by dhruva205** [ampproject/amphtml#22607]
**<script>
function mf(a){
location.replace(a);
}
</script>**
`< a href="javascript:mf ( some_url) " > Execute JavaScript< / a>`

In the above section , i want it to run the specified script(js) .
As it is a custom script, it is not allowed in the amp.
Is there a way i can implement it??
( ignore the wrong spacing in the code)

**Comment by aghassemi** [comment]
What do you need to do when link is clicked? AMP has several builtin Actions you can run onclick, `amp-bind` can also be used to dynamically change parts of the page when user taps a link.

**Comment by dhruva205** [comment]
> What do you need to do
in normal html, we have the function  ..  windows.location.replace(url);
this function can be executed with the 'href' as
<a href="javascript:myFunction(url);">Execute JavaScript</a>
<script> myFunction(url){window.location.replace(url)};</script>

But as it is custom js , its not valid amp!
Is there any other way to execute such thing!


Apart from this, I am currently working amp with wp.
In that i need to load some posts (say 5) , when loadMore is clicked, it must further expand the list by 5 more posts without refreshing the page..
Currently that is possible through ajax/custom js
How to do that in amp!

**Comment by aghassemi** [comment]
@dhruva205 https://amp.dev is your best bet to find AMP equivalent for many use-cases that require JS. We have `AMP.navigateTo` for instance. LoadMore can be implemented using `amp-list`'s `LoadMore` feature.

https://codelabs.developers.google.com/codelabs/accelerated-mobile-pages-foundations/#0 and 
https://codelabs.developers.google.com/codelabs/advanced-interactivity-in-amp/index.html#0

are couple of good Codelabs to get started with AMP as well.
