### ISSUE TITLE
Pages using AMP scripts but not for forms

### ISSUE THREAD

**Issue by IamAlta** [ampproject/amphtml#22618]
**Please only file bugs/feature requests for AMP here.**
Is there any way to use the amp scripts for things like formatting elements and disconnect from AMP for forms?

## What's the issue?
I am re-coding pre-packaged software to use AMP. (The license allows user modifications.) All has gone well until I get to checkout forms.
The software is convoluted and re-uses snippets a lot.

I got the home, category, product, and other non-checkout pages re-coded okay. That is because they can use the form method="get" for nonsensitive data.

But, the checkout with action-xhr/CORS is another problem to trace through the existing code and then re-code with AMP.

That is, the main template/layout for the pages is now in AMP (such as bind and mustache for category menu lists), but I'd like the forms to be disconnected and allow action='url' and method='post' without the json/CORS.

## How do we reproduce the issue?
n/a

## What browsers are affected?

All browsers

## Which AMP version is affected?
Current one is in use.

**Comment by choumx** [comment]
@IamAlta This should be possible for invalid AMP pages if you don't include `amp-form` extension on the page. Or is your request to support this for valid AMP pages?

/cc @cvializ

**Comment by IamAlta** [comment]
@cgiynx @cvializ
That's the answer I needed. Thank you.
