### ISSUE TITLE
amp-ad fallback image is not displayed

### ISSUE THREAD

**Issue by justforfun** [ampproject/amphtml#2261]
Hi, on `<amp-ad> `we’ve a problem similar to the one we had on `<amp-iframe>`: 
https://github.com/ampproject/amphtml/issues/2114
It’s happening when the ad server returns “No Ad”. If we put an image in the fallback div this is not displayed. This is the code:
```
<amp-ad width=300 height=100
             type="doubleclick"
             data-slot="/35012960/repubblica.it/amp/interna/Top"
             json='{"targeting":{"pageType":"dettaglio_content"}}'
           >
     <div class="adv-placeholder" placeholder>
       <amp-anim width=16 height=16 src="//www.repstatic.it/cless-mobile/main/amp/2016-v1//img/loader.gif">
           <amp-img placeholder width=16 height=16 src="//www.repstatic.it/cless-mobile/main/amp/2016-v1//img/loader.gif">
         </amp-img>
       </amp-anim>
     </div>
     <div fallback>
       <a href="http://www.repubblica.it/sport/2016/02/09/news/app_rep-133068373/">
         <amp-img placeholder width=300 height=100 src="//www.repstatic.it/cless-mobile/main/amp/2016-v1/img/adv-300-100.jpg">
       </a>
     </div>
   </amp-ad>
```

**Comment by sriramkrish85** [comment]
Could you try something like this ?
```
<amp-ad width=300 height=100
             type="doubleclick"
             data-slot="/35012960/repubblica.it/amp/interna/Top"
             json='{"targeting":{"pageType":"dettaglio_content"}}'
           >
     <div class="adv-placeholder" placeholder>
       <amp-anim width=16 height=16 src="//www.repstatic.it/cless-mobile/main/amp/2016-v1//img/loader.gif">
           <amp-img width=16 height=16 src="//www.repstatic.it/cless-mobile/main/amp/2016-v1//img/loader.gif">
         </amp-img>
       </amp-anim>
     </div>
     <div fallback>
       <a href="http://www.repubblica.it/sport/2016/02/09/news/app_rep-133068373/">
         <amp-img width=300 height=100 src="//www.repstatic.it/cless-mobile/main/amp/2016-v1/img/adv-300-100.jpg">
       </a>
     </div>
   </amp-ad>
```

**Comment by justforfun** [comment]
Hi, unfortunately your tip didn’t solve. Here you can take a look:
https://www.repstatic.it/cless-mobile/main/amp/2016-v1/view/nazionale/detail.html#development=1
I refer to the banner placed on the top of the page

**Comment by cramforce** [comment]
This might be a bug. It appears the fallback is hidden by a competing style sheet.

**Comment by sriramkrish85** [comment]
@cramforce no its not a CSS issue

@justforfun - AMP expects a `no-content` postmessage from the ad iframe to display a fallback if available (else collapse the ad). I tried to see if such a message is being sent - and i cannot see that message (all i see is multiple `render-start` and `embed-size` messages), could you please check if you are sending the `no-content` message from your iframe. 

Here is more information on how to trigger this message.
https://github.com/ampproject/amphtml/blob/master/ads/README.md#methods-available-to-the-ad

**Comment by justforfun** [comment]
@sriramkrish85 : we are using DFP to serve ads and we have no control on its response.
May you point us any sample implementation of using `window.context.noContentAvailable` (is a function that the ad system can call if the ad slot was not filled. The container page will then react by showing fallback content or collapsing the ad if allowed by AMP resizing rules) with DFP?
All we see is that when the ad slot is not filled the DFP response to this call:
https://securepubads.g.doubleclick.net/gampad/ads?nwids=35012960
looks like that:
`callbackProxy([{"/35012960/repubblica.it/amp/interna/Top":{"_type_":"html","_expandable_":false,"_html_":"","_snippet_":false,"_height_":60,"_width_":234,"_empty_":true,"_is_afc_":false,"_creative_ids_":[],"_adgroup2_ids_":[],"_is_psa_":false,"_is_3pas_":false,"_cids_":[""],"_a2ids_":[""],"_pstok_":""}}]);`

**Comment by emasab** [comment]
It seem like an issue in the interaction between the amp-ad and the amp-img lazy load. If we replace the amp-img with a plain img element, the fallback is displayed (but the amp runtime does not validate the page). Maybe it's because the fallback is displayed by adding the **amp-notsupported** class ?

```
.-amp-element:not(.amp-notsupported)>[fallback] {
    display: none;
}
```

**Comment by sriramkrish85** [comment]
@justforfun this fallback will not be triggered for all ad formats (as far as i know doubleclick supports this). The real issue is you have an iframe (your own) containing the doubleclick iframe and hence the issue. 

So if you can listen to doubleclicks no content message and then call `window.context.noContentAvailable` fallback should work.

I believe that this is your own iframe `https://oasjs.kataweb.it/amp/remote.html ` and you have called our `draw3p` method here, which gives you the ability to call `window.context.noContentAvailable`

Now you can do something like this to propagate the message to the AMP page

``` javascript
 window.addEventListener(‘message’, function(e) { 
  if (e.data && e.data.type=’no-content’) {
    window.context.noContentAvailable();
  }
})
```

or through some other logic figure-out that the ad is empty and call `window.context.noContentAvailable();` 

That should solve your problem

@emasab no it is not an issue with `amp-img`

**Comment by emasab** [comment]
@sriramkrish85 the noContentAvailable is already called by

```
g.addEventListener("slotRenderEnded", function(b) {
                    var d = b.creativeId || "_backfill_";
                    b.isEmpty && (a.context.noContentAvailable(),
                    d = "_empty_");
                    a.context.reportRenderedEntityIdentifier("dfp-" + d)
                });
```
that is inside 

https://3p.ampproject.net/1456440290687/f.js

that is in the head of 

https://oasjs.kataweb.it/amp/remote.html

than I see the the event "no-content" trigger the

```
b.prototype.noContentHandler_ = function() {
        var a = this;
        if (!this.fallback_) {
            var b = this;
            this.attemptChangeHeight(0, function() {
                b.element.style.display = "none"
            })
        }
        this.deferMutate(function() {
            a.fallback_ && a.toggleFallback(!0);
            a.element.removeChild(a.iframe_)
        })
    };
J.registerElement(a, "amp-ad", b)
```
and toggleFallback adds the amp-notsupported class

do you agree that the noContentHandler_ is triggered by the no-content message and that the amp-notsupported class is added ? To see there is a condition, the draw3PDone is called at a condition

`if(window.kwdnt !== -1) draw3PDone(config);`

to make this condition true you have to accept the privacy policy on http://www.repubblica.it/ 
we have to fix this by doing 

```
if(window.kwdnt !== -1) draw3PDone(config);
else window.context.noContentAvailable();
```

but that doesn't have to do with this issue (at the moment I can't edit the remote.html).

**Comment by justforfun** [comment]
Hi, we think there's a bug in the visualization of `<amp-img>
![schermata 2016-02-28 alle 11 49 46](https://cloud.githubusercontent.com/assets/477983/13378793/12868744-de12-11e5-9fd4-aa53a43a0575.png)
` elements inside the fallback div.
You can see the bug in action here:
http://justforfun.github.io/examples-amp/rep-article.amp.html#development=1


We manage to intercept that DFP doesn't fill the slot and to call the window.context.noContentAvailable()
```
if (event.isEmpty) {
        	window.context.noContentAvailable();
}

```
In this page we have two <amp-ad> elements requesting a 300x100 slot.

The topmost `<amp-ad>` element is using a valid AMP code 
```
<div fallback>
      <a class="fallback-link" href="http://m.repubblica.it/mobile/r/sezioni/sport/2016/02/09/news/app_rep-133068373/?ref=amp">
              <amp-img layout="responsive" width=300 height=100 src="//www.repstatic.it/cless-mobile/main/amp/2016-v1/img/300x100_AppRepubblicaSport.gif"></amp-img>
            </a>
 </div>
```

In this case the `<amp-img>` inside the fallback div is not shown

The second `<amp-ad>` element is using an invalid AMP code
```
<div fallback>
    <a class="fallback-link" href="http://m.repubblica.it/mobile/r/sezioni/sport/2016/02/09/news/app_rep-133068373/?ref=amp">
              <img width=300 height=100 src="//www.repstatic.it/cless-mobile/main/amp/2016-v1/img/300x100_AppRepubblicaSport.gif"></img>
    </a>
</div>
```
but in this case the image inside the fallback div is shown


Please refer to the attached screenshot


Trying to summarize we found out that there are only two cases where we manage to show a fallback img:

1) If we use a `<img>` element instead of an `<amp-img>` element
`<div fallback>
    <a class="fallback-link" href="http://m.repubblica.it/mobile/r/sezioni/sport/2016/02/09/news/app_rep-133068373/?ref=amp">
              <img width=300 height=100 src="//www.repstatic.it/cless-mobile/main/amp/2016-v1/img/300x100_AppRepubblicaSport.gif"></img>
    </a>
</div>
`
but this lead to a non valid AMP page.

2) If we use a svg image instead of an <amp-img>.
Here:
http://www.repubblica.it/esteri/2016/02/28/news/iran_parlamento_riformisti_in_testa_in_tutto_il_paese-134406893/amp
you can find an example.

**Comment by emasab** [comment]
If've found that if you call from the consoel

```
AMP.resources.relayoutAll_ = true;
AMP.resources.schedulePass()
```

the amp-img inside the fallback is displayed.
That should be triggered by the toggleFallback.

**Comment by dvoytenko** [comment]
@sriramkrish85 Sounds like we simply need to ensure that the fallback element gets its "layout" callback invoked when fallback is enabled. Ping me directly, and I'll provide details.

**Comment by sriramkrish85** [comment]
@dvoytenko thanks! does this involve calling `mutateElement` :)

**Comment by dvoytenko** [comment]
@sriramkrish85 , no, it's just will be part of your `noContentHandler_` in `amp-ad`. You already have `deferMutate` there - you can simply add `togglePlaceholder(false)` in it.

**Comment by sriramkrish85** [comment]
@dvoytenko - so https://github.com/ampproject/amphtml/pull/2371 should have solved this right?

**Comment by dvoytenko** [comment]
Nope. Actually not even related :) Basically, when fallback is turned on - runtime needs to pick up the changes sooner - otherwise it could be long time before it notices that things changed. The path to do it is via `Resources.scheduleLayout` or a derivative of it.

**Comment by justforfun** [comment]
@sriramkrish85: 
Has the fix been pushed in production?
Here:
http://justforfun.github.io/examples-amp/rep-article.amp.html#development=1
I still get the problem.
Thank you

**Comment by amphtml-team** [comment]
Not yet!

**Comment by dvoytenko** [comment]
@justforfun The fix should go into canary this Thursday (March 17th) and to PROD the following Thursday.

**Comment by justforfun** [comment]
@dvoytenko Hi, it seems to me the problem is still open
http://justforfun.github.io/examples-amp/rep-article.amp.html#development=1
What am I missing?

**Comment by dvoytenko** [comment]
@justforfun is this in canary or PROD? The fix went into PROD just about an hour or so ago. But it was in canary for about a week.

**Comment by justforfun** [comment]
@dvoytenko it works fine now, I was using production environment. Thank you

**Comment by dvoytenko** [comment]
@justforfun Thanks a lot!
