### ISSUE TITLE
[amp-script] Support inline JS

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#22612]
Not sure if this came up already (at least I couldn't find anything): it looks like amp-script currently only supports embedding external JS via the `src` attribute. It'd be great to be able to define custom scripts inline:

```html
 <amp-script layout=container src="/examples/amp-script/hello-world.js">
    <button id="greeting">Say hello</button>
    <script>
    const button = document.getElementById('greeting')
    ...
    </script>
  </amp-script>
``` 

I see a few advantages for this:

1. This would greatly simplify documenting amp-script as samples would no longer need two files. 
2. Faster loading time (we probably should restrict script size for these cases even further).

**Comment by dhruva205** [comment]
i requested for the same, hoping for a solution!

**Comment by sparhami** [comment]
Perhaps this could be done by giving the script a `type` that causes it to be inert?

```html
<script type="text/amp-script">...</script>
```

@kristoferbaxter

**Comment by ArunKumar-61Steps** [comment]
amp js & my custom js files takes more time for loading..so my performance gets decreased...how to minimize thread work because it help me to increase performance...
Kindly provide Any solution...?

**Comment by sebastianbenz** [comment]
//cc @choumx @kristoferbaxter

**Comment by choumx** [comment]
Sounds reasonable.

**Comment by ArunKumar-61Steps** [comment]
Do you have any better Solution  sir..!! @choumx

**Comment by ArunKumar-61Steps** [comment]
Do you have any better Solution  sir..!!







---- On Tue, 04 Jun 2019 22:33:55 +0530 William Chou <notifications@github.com> wrote ----


Sounds reasonable.
