### ISSUE TITLE
PayPal Exress uses a Form but action-xhr won't work.

### ISSUE THREAD

**Issue by IamAlta** [ampproject/amphtml#22621]
**Please only file bugs/feature requests for AMP here.**

PayPal Express Checkout uses a form but neither action-xhr/post nor action/get will work.
Is there a fix for this?

## How do we reproduce the issue?

The paypal button is a FORM element. Using action-xhr doesn't work because of CORS.
Error was "Form submission failed: Error: XHR Failed fetching (https://www.paypal.com/...): NetworkError when attempting to fetch resource.​​​"

    <form action-xhr="https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&amp;token=EC-MyToken" id="paypal--expresscheckout" class="center mb2 i-amphtml-form user-valid amp-form-submit-error" method="post" novalidate="">
    <input type="image" name="PayPal Express Checkout" alt="PayPal Express Checkout" src="/PAYPAL.png" class="inline mx1 mt1 pt1 user-valid valid">
    </form>

If you post with "get", the form fails and you're sent to paypal's home page. I'll be the order info isn't sent to them.

## What browsers are affected?
All browsers. All devices.

## Which AMP version is affected?
Latest AMP

**Comment by aghassemi** [comment]
@IamAlta, @dvoytenko is working on removing AMP's CORS requirements. Subscribe to https://github.com/ampproject/amphtml/issues/22136 for updates.

**Comment by aghassemi** [comment]
PayPal endup still needs to set normal HTTP response header for `Access-Control-Allow-Origin` to either the requester origin or `*` for this to work but AMP specific requirements will go away.  

We currently don't have plans to enable non-XHR-based `POST`

**Comment by aghassemi** [comment]
closing per comment above
