### ISSUE TITLE
Unable to show AdSense ads in China

### ISSUE THREAD

**Issue by palances** [ampproject/amphtml#22636]
## What's the issue?

AdSense works in China but not work on amp-ads and amp-auto-ads. Network screenshot and domain route trace as below:

<img width="976" alt="Screen Shot 2019-06-03 at 1 34 35 PM" src="https://user-images.githubusercontent.com/330330/58778584-bddf5780-8605-11e9-981c-9f9e47015322.png">
<img width="581" alt="Screen Shot 2019-06-03 at 1 43 32 PM" src="https://user-images.githubusercontent.com/330330/58778592-c46dcf00-8605-11e9-9b06-e39262eab82e.png">

## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. Connect to China network
2. Visit [sample site](https://jamesqi.com/?amp=&from=singlemessage)
3. Check the amp-auto-ads on the first screen

## What browsers are affected?

All browsers

## Which AMP version is affected?

Always broken

**Comment by torch2424** [comment]
cc @ampproject/wg-ads 

Thank you for the issue @palances 😄

**Comment by calebcordry** [comment]
Closing as dup of #14949
