### ISSUE TITLE
WindowMessenger code not included in amp-web-push-helper-frame.html and amp-web-push-permission-dialog.html

### ISSUE THREAD

**Issue by nawazMoEngage** [ampproject/amphtml#22637]
## What's the issue?

Getting the error:  
```
amp-web-push-helper-frame.html?parentOrigin=https://localhost:8080:7 Uncaught ReferenceError: module$build$all$amp_web_push_0_1$window_messenger is not defined
    at new p (amp-web-push-helper-frame.html?parentOrigin=https://localhost:8080:7)
    at amp-web-push-helper-frame.html?parentOrigin=https://localhost:8080:18
    at amp-web-push-helper-frame.html?parentOrigin=https://localhost:8080:18
```
I have checked the source code and figured out that `module$build$all$amp_web_push_0_1$window_messenger` should be included in the code as WindowMessenger code.
I checked the actual source code in `https://github.com/ampproject/amphtml/blob/master/extensions/amp-web-push/0.1/amp-web-push-helper-frame.js`
And it seems like some build issue

## How do we reproduce the issue?
Just create a simple AMP with amp-web-push. Follow this: `https://amp.dev/documentation/components/amp-web-push`

## What browsers are affected?

Google Chrome v74.0.3729.169

## Which AMP version is affected?
v0

**Comment by albirrkarim** [comment]
i have same problem

**Comment by torch2424** [comment]
@nawazMoEngage @albirrkarim

Thank you very much for bringing up this issue! 😄 

cc @aghassemi @kristoferbaxter 

I don't know which working group this would fall under 🤔

**Comment by nawazMoEngage** [comment]
any update on this?
is anybody solving it or not?

**Comment by torch2424** [comment]
@nawazMoEngage Bumped this to the team 😄

**Comment by choumx** [comment]
Looks like this was broken on May 14 in [1905091827220](https://github.com/ampproject/amphtml/releases/tag/1905091827220).

**Comment by choumx** [comment]
Likely a bundling/compile issue. My current guess is #22125 based on: https://github.com/ampproject/amphtml/blame/1905091827220/build-system/tasks/dist.js

/to @rsimha

**Comment by choumx** [comment]
Possibly wrong file path here: https://github.com/ampproject/amphtml/commit/e9acfc63ccde5afe4d048d275b4320a771443396#diff-7c22ae941e7d608ea3ed2ca2f101e835R245

https://github.com/ampproject/amphtml/blob/9c6f331cfb88cd3412afee7b3246b6cccba8bd94/build-system/tasks/dist.js#L235-L239

**Comment by rsimha** [comment]
Nice catch, @choumx. Fix in #23093

**Comment by gustavopaes** [comment]
Maybe need to update here too?
https://cdn.ampproject.org/v0/amp-web-push-helper-frame.html

Following the documentation, I still get error:
https://amp.dev/documentation/components/amp-web-push

AMP Version 1907022322580

![Screenshot from 2019-07-12 13-11-34](https://user-images.githubusercontent.com/227400/61142654-a74eda80-a4a6-11e9-91da-913140a9be0f.png)

**Comment by rsimha** [comment]
The last PR to touch that code was #22839. 
> There were some complications with buildExperiments, buildLoginDone, and buildWebPushPublisherFiles calls since they move they're files into the build directory to be processed by closure way later into the process (in their individual methods) so i had to separate this file move step into a pre${method} invocation that needed to be executed before the babel preprocessing. In buildWebPushPublisherFiles case it also had a post process step.

@erwinmombay Can you take a look?

**Comment by erwinmombay** [comment]
looking

**Comment by himanshu-myupchar** [comment]
Hi! Is this resolved ?

**Comment by erwinmombay** [comment]
@gustavopaes @nawazMoEngage @himanshu-myupchar can any of you give me a live link to replicate the code. appreciate it

**Comment by gustavopaes** [comment]
@erwinmombay here:
https://www3.uol.com.br/gpaes/amp-web-push/index.htm

Both `helper-iframe.html` and `permission-dialog.html` files I got here:
https://amp.dev/documentation/components/amp-web-push

**Comment by erwinmombay** [comment]
@gustavopaes could you update the amp-web-push-helper-frame html file with the latest from view-source:https://cdn.ampproject.org/v0/amp-web-push-helper-frame.html and see if that fixes the problem?

it looks like there is a bit of disconnect here since the html source is supposed to be copied. I'll talk to @rsimha to see if theres anything we can do about this

**Comment by gustavopaes** [comment]
@erwinmombay updating and working.

**Comment by erwinmombay** [comment]
@nawazMoEngage @himanshu-myupchar could you ya'll also try and update the helper frame html and see if it works?

**Comment by himanshu-myupchar** [comment]
No still not working

**Comment by erwinmombay** [comment]
@himanshu-myupchar do you have a live page i can debug?

**Comment by himanshu-myupchar** [comment]
Can you check this:
https://www.myupchar.com/en/tips/immunity-boosting-foods-in-hindi.amp

And also is there a way by which the user automatically gets asked for notifications, rather than clicking on Subscription button, like in Non-Amp Pages.
