### ISSUE TITLE
Not Getting Crawled

### ISSUE THREAD

**Issue by johnnyshankman** [ampproject/amphtml#2264]
http://www.refinery29.com/sean-avery

Has a reference to 

http://www.refinery29.com/amp/sean-avery

via the `rel="amphtml"` tag.

We're not seeing that there are any AMP articles in our Webmaster console.

We've *most definitely* followed the check list and our articles are all valid. 

Why is google unaware of our link?

**Comment by LightManEye** [comment]
Inside Google Webmaster Console, you have to wait about a week to see AMP Pages.

**Comment by johnnyshankman** [comment]
TY

**Comment by johnnyshankman** [comment]
Do pages not turn up in Google Search results until they also show up in the Google Webmaster Console?

**Comment by ticktockreed** [comment]
I submitted an AMP page via "Fetch As Google" 8 days ago. The page validates in the console with the #development=1 query string. The page is indexed within the site. It appears with a google search for site:www.hugoandcat.com. However it does not appear within the "Search Appearance">"Accelerated Mobile Pages" tab. 

Will it take about a week after the page is indexed to show in webmaster tools?

**Comment by cramforce** [comment]
@jmadler Do you know where we can point these folks? The AMP project isn't a good place to discuss Google Search related questions. There is nobody monitoring this forum that knows anything about it.

**Comment by adewale** [comment]
@cramforce the right place for people to ask questions about Google Search is the [Webmaster Central Help Forum](https://productforums.google.com/forum/#!topicsearchin/webmasters/category$3Aaccelerated-mobile-pages-amp%7Csort:relevance%7Cspell:false). They even have a section dedicated to AMP.

Please close this issue.

**Comment by cramforce** [comment]
@adewale Awesome. Thanks!

**Comment by Raghuch2415** [comment]
Hello,
We have launched AMP website(www.elebnis.com) but not getting AMP result on google. Can you tell me what is problem with my website.

**Comment by cramforce** [comment]
Please see https://goo.gl/utQ1KZ for Google specific questions.
