### ISSUE TITLE
amp-form: Response of form submission with verifyErrors does not invalidate fields

### ISSUE THREAD

**Issue by westonruter** [ampproject/amphtml#22651]
Given this example form:

```html
  <form class="sample-form" method="post"
        action-xhr="https://ampbyexample.com/components/amp-form/verify-form-input-text-xhr"
        verify-xhr="https://ampbyexample.com/components/amp-form/verify-form-input-text-xhr"
        target="_top"
        custom-validation-reporting="as-you-go">
    <input type="text" id="verification-username" name="username" placeholder="Username..." required pattern="\w+">
    <span visible-when-invalid="customError" validation-for="verification-username">That username is already taken</span>
    <span visible-when-invalid="patternMismatch" validation-for="verification-username">Invalid character in username</span>
    <input type="submit" value="Check">
    <div submit-success>
      <template type="amp-mustache">
        Success! Thanks {{name}} for trying the <code>amp-form</code> demo! Try to insert the word "error" as a name input in the form to see how <code>amp-form</code> handles errors.
      </template>
    </div>
    <div submit-error>
      <template type="amp-mustache">
        {{#verifyErrors}}
        <p>{{message}}</p>
        {{/verifyErrors}}
        {{^verifyErrors}}
        <p>Something went wrong. Try again later?</p>
        {{/verifyErrors}}
        <p>Submission failed</p>
      </template>
    </div>
  </form>
```

Upon entering “error” into the input box and tabbing out of the field, an XHR request is made with the response:

```json
{
    "verifyErrors": [
        {
            "message": "The username \"error\" is already taken",
            "name": "username"
        }
    ]
}
```

I see the the expected showing of the `span[visible-when-invalid="customError"]` element (though as I [commented](https://github.com/ampproject/amphtml/issues/18775#issuecomment-498043052) elsewhere, I expected the response's `message` to populate this `span`):

> ![image](https://user-images.githubusercontent.com/134745/58826940-b5cbeb80-85f6-11e9-931e-3a02ae11e8fd.png)

I also see the `input` itself gets the classes for `user-invalid customError` and the `aria-invalid="true"` attribute:

```html
<input type="text" id="verification-username" name="username" placeholder="Username..." required="" pattern="\w+" class="user-invalid customError" aria-invalid="true">
```

Likewise, the `input.validationMessage` is populated with "The username "error" is already taken".

So that's all well and (mostly) good.

# Problem: Removal of `verify-xhr` attribute

So now what happens when I remove the `verify-xhr` attribute. When I enter "error" again and I hit Submit then I see:

> ![image](https://user-images.githubusercontent.com/134745/58827426-db0d2980-85f7-11e9-9ba8-2e9d0b080f46.png)

Notice that `span[visible-when-invalid="customError"]` is not displayed, and the `input` still has the `user-valid valid` classes. This is all in-spite of the response including (the same as above):

```json
{
    "verifyErrors": [
        {
            "message": "The username \"error\" is already taken",
            "name": "username"
        }
    ]
}
```

👉 My expectation is that if the response to an `action-xhr` form submission includes `verifyErrors` that it should update the state of the fields in the same way as a `verify-xhr` response. A form author shouldn't need to reference the `verifyErrors` in the `submit-error` template because they should already be contextually displayed along with their respective inputs.

Additionally, some sites may not want to use `verify-xhr` since it incurs extra server load since every input `change` causes an extra HTTP request. They may want to only check the form validation upon submission, and this is particularly true when not using the `as-you-go`  reporting strategy.

**Comment by cvializ** [comment]
Hi @westonruter  thanks for opening this. If I understand correctly, you expect amp-form to have unified behavior with how it handles error responses from the server whether that's with `action-xhr` or `verify-xhr`? Additionally you're requesting that the frequency of the requests should be lower, since many of the reporting strategies only check after a single explicit user interaction like submit. Please let me know if I'm accurately describing your issue

**Comment by westonruter** [comment]
> If I understand correctly, you expect amp-form to have unified behavior with how it handles error responses from the server whether that's with `action-xhr` or `verify-xhr`?

Correct. If the server sends back `verifyErrors` for both responses, the invalid fields should have their custom validity set in both cases.

> Additionally you're requesting that the frequency of the requests should be lower, since many of the reporting strategies only check after a single explicit user interaction like submit.

Actually, this isn't exactly a request. But some sites may want to skip adding `verify-xhr` to reduce the server load. Also, if the custom errors states could be populated at `action-xhr`, then it would be unnecessary to even use `verify-xhr` in the first place if `as-you-go` is not being used.

**Comment by kfurmaga-marcura** [comment]
I have the same issue - I have backend which returns validation errors on submit - I expected that if I return the same value on submit that is normally returned in verify-xhr then It will work the same... also I have the case where I can not use verify-xhr - because api doesn't have endpoint for verification - and I would need to duplicate verification logic in my app...
