### ISSUE TITLE
amp-image-lightbox 'script' tag is present more than once in the document.

### ISSUE THREAD

**Issue by imokweb** [ampproject/amphtml#22668]
Hello, 

I have a WP site with AMP plugin, but on a few pages there is an error like this:
**on the GConsole:** An AMP component 'script' tag is present more than once in the document.
**on the browser Console:** http://prntscr.com/nxh4s6
**Page URL**: https://www.modern-forager.com/the-grand-fir-abies-grandis-and-mushrooms/amp/

This script loaded by the WP Plugin, right?

How can I resolve this?

**Comment by aghassemi** [comment]
The error is safe to ignore but I can't repro on the provided Url, is this still happening?

**Comment by aghassemi** [comment]
(please reopen the ticket with the answer to above, closing for house keeping purposes)
