### ISSUE TITLE
Invalid amp-state JSON should not pass validation

### ISSUE THREAD

**Issue by radiovisual** [ampproject/amphtml#22667]
**Please only file reports about bugs in AMP here.**
## What's the issue?
Invalid amp-state JSON does not fail validation. It passes, but AMP rendering fails. 

## How do we reproduce the issue?

Paste this code into the AMP playground: https://amp.gmail.dev/playground/ 

```html
<!doctype html>
<html amp4email>

<head>
  <meta charset="utf-8">
  <style amp4email-boilerplate>
    body {
      visibility: hidden
    }
  </style>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>
</head>

<body>

  <amp-state id="myState">
    <script type="application/json">
      {
        "secret": "trailingCommaError",
      }
    </script>
  </amp-state>
  
  <p [text]="myState.secret">******</p>
  <button on="tap: AMP.setState({myState: {secret: 'supersecret'}})">Click to show secret</button>
</body>

</html>
```

And you will see: 

![image](https://user-images.githubusercontent.com/5614571/58878948-ce123800-86d4-11e9-9dc7-f18edbb51ae8.png)

![image](https://user-images.githubusercontent.com/5614571/58879066-087bd500-86d5-11e9-8521-d35eaf40351d.png)

The warning says that JSON is invalid, but validation passes. In this simple example, the interactions still behave normally, but in a more complex app or various mail clients/browsers might introduce unwanted behaviours if it encounters invalid JSON, so should it not fail validation, or is is safe as a warning?

**Comment by torch2424** [comment]
Triaging to @Gregable , feel free to re-assign 😄

**Comment by Gregable** [comment]
This is one of those cases where we decided that the page may be broken, but that does not make it invalid. It will not cause the page to have performance or security issues. It may or may not be the best decision, but it would be difficult to change to an error now as it would likely invalidate currently valid documents.

Marking this as working as intended.

**Comment by radiovisual** [comment]
Thanks @Gregable. I understand. 

> but it would be difficult to change to an error now as it would likely invalidate currently valid documents.

Would it be worth putting in some sort of strict mode? Where we can opt-in for JSON errors to fail validation? Or are there any linting strategies that you know of that can inspect AMP markup *and* it's embedded JSON?

**Comment by Gregable** [comment]
The validator does have the ability to emit both errors and warnings. Warnings are errors that will not cause the overall validation to fail. However, we would like to keep warnings limited to a set of issues that are serious enough that we would imagine making them into errors in the future. The rationale there is that we don't want developers to learn to ignore warnings, they should take them as seriously as errors.

We've considered in the past creating an independent "linter" tool using the validator framework that reports on non-validation issues which the publisher may be interested in knowing about. Your strict mode sounds similar to this in spirit. I'll keep this issue on the list of ideas for a linter if we go that route, but unfortunately the broader usefulness of such a linter is unclear and the maintenance burden is not insignificant.
