### ISSUE TITLE
Include e2e tests in code coverage calculations

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#22675]
Currently e2e tests do not factor into test coverage reports. We have discussed including them somehow, but investigation is needed. Challenges include how the coverage binaries are separate from the test code across the WebDriver boundary.

**Comment by estherkim** [comment]
Hey @cvializ, I thought we decided that code coverage isn't necessary for e2e tests? Because e2e tests aren't meant to cover 100% of the code base, given how costly they are. More so they're meant to capture the most common user scenarios. Reporting code coverage might confuse the two.

**Comment by cvializ** [comment]
Oh that's right, thanks. We can close this issue to track that decision.
