### ISSUE TITLE
Events on scroll down and scroll up

### ISSUE THREAD

**Issue by demil** [ampproject/amphtml#22678]
Is there possibility to have on scroll up and on scroll down event to hide and show headers and footers based on this action like all modern apps do, so if you begin to scroll up on any part of page header will show and if you begin to scroll down header will hide for example?

**Comment by aghassemi** [comment]
Hi @demil, we have this feature under the `amp-fx-collection` extension. Please see https://amp.dev/documentation/components/amp-fx-collection#float-in-top,-float-in-bottom for documentation and https://scroll-toggle.glitch.me/ for a demo.

/cc @alanorozco

**Comment by aghassemi** [comment]
Closing per comment above, please feel free to reopen if that does not handle your use-case or file new issues if you run into bugs.
