### ISSUE TITLE
Form fields inside amp-list fallback/placeholder do not get dismissed on submit

### ISSUE THREAD

**Issue by dritter** [ampproject/amphtml#22672]
Hi there!

## What's the issue?

We put a form field inside an `amp-list`, to work around rendering local state. To have the best possible UX, we had the urge to include the form fields in the `placeholder` and `fallback` elements as well (side problem: despite having the dummy request cached in a ServiceWorker, it takes quite long; seems to be delayed somewhere). Now, when I submit the form, all the fields are included:
```
myfield: afdasdf
myfield: afdasdf
myfield: afdasdf
```
This is somewhat unexpected.. It gets worse, if I submit a value while the dummy request is still going on. Then it sends 
```
myfield: afdasdf
myfield: 
```
The second field is empty here, thus it overwrites the first value.

My expectation would be that only the currently displayed fields would be included in the request.

The Problem might be fixed, once `amp-list` is capable of rendering local state (no need for the dummy request / fallbacks / placeholder). Another workaround was suggested by @sebastianbenz in slack:

>  When the inputs get submitted, first write the input values to amp-state which is bound to hidden fields in the form and then submit the form via action. This might also be a way to sync input values between placeholder and real input.

## How do we reproduce the issue?

Put this in the amp-playground and submit the form:
```html
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <title>My AMP Page</title>
  <link rel="canonical" href="self.html" />
  <meta name="viewport" content="width=device-width,minimum-scale=1">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script async custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.2.js"></script>
  <script async custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js"></script>
  <script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>
  <script async custom-element="amp-list" src="https://cdn.ampproject.org/v0/amp-list-0.1.js"></script>
  <style amp-custom>
    h1 {
      margin: 1rem;
    }
  </style>
</head>
<body>
  <h1>Hello AMPHTML World!</h1>
  <amp-state id="mystate">
    <script type="application/json">
    {
    	"value": "This is the value."
    }
    </script>
  </amp-state>
  <form id="myform" method="post" action-xhr="https://somewhere.net">
    
  
  <amp-list src="https://cors-test.appspot.com/test"
            single-item
            items="."
            layout="fixed-height"
            height="50"
            >
    <div placeholder>
      <input name="myfield" type="text" placeholder="This is the Placeholder" [value]="mystate.value" on="input-debounced:
              AMP.setState({
                mystate: {
                    value: event.value
                }
              });" />
    </div>
    <div fallback>
      <input name="myfield" type="text" placeholder="This is the Fallback" [value]="mystate.value" on="input-debounced:
              AMP.setState({
                mystate: {
                    value: event.value
                }
              });" />
    </div>
    <template type="amp-mustache">
      <input name="myfield" type="text" placeholder="This is the Default Field" [value]="mystate.value" on="input-debounced:
              AMP.setState({
                mystate: {
                    value: event.value
                }
              });" />
    </template>
  </amp-list>
    <button type="submit">
      Submit
    </button>
    </form>
</body>
</html>
```

## What browsers are affected?

I observed this in chrome, but other browsers are probably affected too.

All browsers? Some specific browser? What device type?

## Which AMP version is affected?

I haven't seen a fixed version, so I assume it was broken forever.

// cc @sebastianbenz

**Comment by aghassemi** [comment]
/to @cvializ interesting area to investigate. Should invisible form elements in `hidden`, `fallback`, `amp-selector's not selected panel`, etc... be configurable to be excluded from submission?

**Comment by cvializ** [comment]
IMO this is expected behavior since `input` elements styled as hidden are always submitted.

I think this feature request is effectively expecting the `[fallback]` and `[placeholder]` tags to act like `<template>` tags, where the markup is not active until it is rendered and displayed. I think that would be a good approach, but it might involve adding to the size of `v0.js` since `[placeholder]` and `[fallback]` are core features, so we'd have to weigh the implementation details and the benefits

**Comment by aghassemi** [comment]
I was thinking maybe a new feature on `amp-form`, something like `exclude-invisible-inputs`, for a reasonable definition of invisible.
