### ISSUE TITLE
amp-date-picker keyboard popup, amp-form fails to validate

### ISSUE THREAD

**Issue by mdiblasio** [ampproject/amphtml#22688]
URL: https://www.cheapoair.com/flights/amp

When a user inputs a depart or return date into the `amp-date-picker`, the keyboard pops up and covers the calendar:

![GjC44dBGpmZ](https://user-images.githubusercontent.com/17748781/58924261-d4baa280-8708-11e9-99b8-c93ba6f1cd79.png)

(Note: a keyboard will not popup in Chrome emulation, need to try on physical device)

The issue happens on this page (page #1): https://www.cheapoair.com/flights/amp
But **does not** happen on this page (page #2): https://www.cheapoair.com/flights/cheap-flights-from-new-york-city-to-bangkok-nyc-bkk/amp

The difference is that there is a `readonly` attribute in the input field on the page where the issue is happening (page #1):

```
<input placeholder="Date"
       id="fromDt"
       autocomplete="off"
       class="date"
       name="fromDt"
       [disabled]="formDataVar.oneway"
       required=""
       readonly=""   <----------- READONLY ATTRIBUTE
/>    
```

Removing the `readonly` attribute fixes the keyboard popup issue, but allows the user to submit the `amp-form` without depart and return dates, which are required input fields. The user should instead see a validation message that looks like this: 

![DED86OpfWNk](https://user-images.githubusercontent.com/17748781/58924276-e56b1880-8708-11e9-86f3-1cce5eb35327.png)

**Comment by nainar** [comment]
Hi @cvializ have you had a chance to take a look here?

**Comment by cvializ** [comment]
I have not yet been able to investigate, but I will be able to take a look this week since it's a fixit

**Comment by cvializ** [comment]
I am not able to reproduce on a device and a minimal reproduction document with amp-date-picker https://plaid-flight.glitch.me

I am also seeing something strange. When I look at the source in Chrome I see the `readonly` attribute on the inputs. But I am not seeing the `readonly` attribute when I look at the validator or when I load it on a mobile device, so I think different markup may be getting served to different clients. https://validator.ampproject.org/#url=https%3A%2F%2Fwww.cheapoair.com%2Fflights%2Famp

@mdiblasio are you able to share a minimal reproduction case that will help me reproduce the bug?

**Comment by Sitanderkumar** [comment]
Hi @cvializ,
check url with m. domain.
https://m.cheapoair.com/flights/amp

you will see the same code. if still facing issue.

just add validation on your both input filed, page which you created for date picker. 
https://plaid-flight.glitch.me

**Comment by cvializ** [comment]
I double checked and unfortunately I found that the markup at https://m.cheapoair.com/flights/amp URL on my iPhone does not have the `readonly` attribute, which causes the keyboard to appear:
<img width="100%" alt="Screen Shot 2019-06-14 at 10 03 06" src="https://user-images.githubusercontent.com/2363700/59514851-bf254580-8e8b-11e9-81a0-5d74994086d9.png">

**Comment by cvializ** [comment]
I just noticed that the markup at that URL has the `touch-keyboard-editable` attribute, which makes the mobile keyboard appear when interacting with the date picker. If you remove that attribute, the keyboard will not appear on mobile devices.

I will look at the validation

**Comment by Sitanderkumar** [comment]
This touch-keyboard-editable attribute generated by the date-picker component.

below is the actual code:

<amp-date-picker type="range" id="daterange" on=" select: AMP.setState({dates: event.dates, tacoTuesdays: event.dates.filter(d=> d.id=='tacos2').length,})" mode="overlay" locale="en" format="Y-MM-DD" blocked="2017-10-15 2017-09-17 2017-10-19 2017-10-21" highlighted="2018-01-29" number-of-months="1" start-input-selector="[name=fromDt]" end-input-selector="#toDt">

**Comment by Sitanderkumar** [comment]
"<amp-date-picker type="range" id="daterange" on=" select: AMP.setState({dates: event.dates, tacoTuesdays: event.dates.filter(d=> d.id=='tacos2').length,})" mode="overlay" locale="en" format="Y-MM-DD" blocked="2017-10-15 2017-09-17 2017-10-19 2017-10-21" highlighted="2018-01-29" number-of-months="1" start-input-selector="[name=fromDt]" end-input-selector="#toDt">"

**Comment by Sitanderkumar** [comment]
<amp-date-picker 
type="range" 
id="daterange" on=" 
select: AMP.setState({dates: event.dates, tacoTuesdays: event.dates.filter(d=> d.id=='tacos2').length,})" 
mode="overlay" 
locale="en" 
format="Y-MM-DD" 
blocked="2017-10-15 2017-09-17 2017-10-19 2017-10-21" 
highlighted="2018-01-29" 
number-of-months="1" 
start-input-selector="[name=fromDt]" 
end-input-selector="#toDt">

**Comment by Sitanderkumar** [comment]
amp-date-picker 
type="range" 
id="daterange" on=" 
select: AMP.setState({dates: event.dates, tacoTuesdays: event.dates.filter(d=> d.id=='tacos2').length,})" 
mode="overlay" 
locale="en" 
format="Y-MM-DD" 
blocked="2017-10-15 2017-09-17 2017-10-19 2017-10-21" 
highlighted="2018-01-29" 
number-of-months="1" 
start-input-selector="[name=fromDt]" 
end-input-selector="#toDt"

**Comment by Sitanderkumar** [comment]
thanks issue has been resolved, however performance is bit slow, now calendar take more time then previous.
