### ISSUE TITLE
WhatsApp a href protocol bug

### ISSUE THREAD

**Issue by LightManEye** [ampproject/amphtml#2268]
On iOS - Safari : 
the link with "whatsapp" protocol does not open the application WhatsApp:

example:
```html
<a href="whatsapp://send?text=%anytext%"></a>
```

**Comment by dvoytenko** [comment]
@Gregable , do we allow this protocol in the validator?

**Comment by Gregable** [comment]
@dvoytenko , we do allow it for anchors.

**Comment by dvoytenko** [comment]
@mkhatib could you please try this out?

**Comment by mkhatib** [comment]
On it.

@LightManEye do you get any alert messages or does clicking on the link do nothing at all?

**Comment by mkhatib** [comment]
@LightManEye just tested this out, this is working on iOS Safari. This is the example we tested: http://jsbin.com/jewoxe/edit?html,output

Please reopen with a provided example and more details on the versions you're using if the problem persists

**Comment by dvoytenko** [comment]
@mkhatib did you test when it's iframed, e.g. like it is in search? Or even via CDN - it's possible that our CDN prevents this somehow.

**Comment by LightManEye** [comment]
@mkhatib 

on iOS:
- on OUR SERVER : It is operating normally
- via CDN, after the click nothing happens

**Comment by mkhatib** [comment]
We were able to reproduce this on Safari iOS. Will do some more debugging to figure out what's happening.
