### ISSUE TITLE
Support CORS JSON responses with a security prefix

### ISSUE THREAD

**Issue by NikhilS** [ampproject/amphtml#22689]
This is related to the checkConsentHref handling for amp-consent. Security best practices for many companies (incl Google) recommend prefixing JSON responses with a prefix:

 )]}']\n

Can we support stripping that out in amp-consent?

Thanks!

**Comment by zhouyx** [comment]
Thank you for reporting. That's a good point. Yes we can add the support while being backward compatible.

**Comment by choumx** [comment]
We should support these on all JSON fetching components e.g. amp-list. 

`b/143896641`

**Comment by choumx** [comment]
De-duping with #17691.
