### ISSUE TITLE
The Modification of Show-More-Button text

### ISSUE THREAD

**Issue by clodisewp** [ampproject/amphtml#22692]
According to our requirement, we need to change the text of this button into different languages. 
I don't know wheather you have already offered the method.
If true, please show me.
else, could you offer this.
Thanks.
![image](https://user-images.githubusercontent.com/19813339/58942385-3e41bc00-87b0-11e9-9700-c2380bb852ec.png)

**Comment by aghassemi** [comment]
Hi @clodisewp , you can provide your own button for load more with arbitrary style and text by adding something like the following to `amp-list` as a child:
```
     <amp-list-load-more load-more-button>
      <button>
        Show lots more
      </button>
    </amp-list-load-more>
```

**Comment by aghassemi** [comment]
Closing per comment above, please reopen if that does not solves your issue.

**Comment by clodisewp** [comment]
> Closing per comment above, please reopen if that does not solves your issue.

Thanks @aghassemi for your reply. It works.
