### ISSUE TITLE
amp-video-iframe does not work in amp-carousel

### ISSUE THREAD

**Issue by juniorneo2** [ampproject/amphtml#22693]
The component amp-video-iframe is not rendering inside amp-carousel.  The error that occurs in the console follows the link below.

Link image console
https://drive.google.com/file/d/1Pt-LZTPJjIvnlg6nz6ReBgfub7vA8AkK/view?usp=sharing

The code

`	<div class="mobile-carousel">
		<amp-carousel width="3" height="2" layout="responsive" type="slides" class="galeria">
				<div class="slide">
										<amp-video-iframe width="480" height="237" layout="responsive" poster=""
														  src="https://player.performgroup.com/eplayer/ep4/assets/amp-iframe-loader.html?ep4on#c27886baf56c21787515163bcf.1h5f1r71m3oan1t1lihbvnvfwg$videoid=1064rpqfdfixx13s5tdz6i967i">
											<div overflow tabindex=0 role=button aria-label="show player">mostrar player</div>
										</amp-video-iframe>
				</div>
		</amp-carousel>
	</div>
`

**Comment by aghassemi** [comment]
to @alanorozco I think the issue is that `isTrackingIframe` for `amp-video-iframe` runs in `buildCallback` which might be too early as it may race with layout of parents that are container like carousel. `onLayoutMeasure` might be the right place for that check.
