### ISSUE TITLE
amp-custom validation with attribute with empty string

### ISSUE THREAD

**Issue by taylorhayduk** [ampproject/amphtml#22698]
## What's the issue?

`The mandatory attribute 'amp-custom' is missing in tag 'style amp-custom'.` error throws when the attribute is set with empty string e.g. `<style amp-custom="">` .  This is a problem when setting attributes with Next.js framework.  (Found this issue with @morsssss at AMP Roadshow Atlanta.)

## How do we reproduce the issue?

Boot up Next.js app and place the following in pages/index.js

```
import { withAmp } from 'next/amp';
import Head from 'next/head';

function HomePage() {
  return (
    <div>
      <Head>
        <style amp-custom={true}>{`body {background-color: purple;}`}</style>
      </Head>
      <div>Hello AMP!</div>
    </div>
  );
}

export default withAmp(HomePage);

```

## What browsers are affected?

All browsers as this is a validation issue.

## Which AMP version is affected?

Next.js installs AMP with withAmp().  Looks like they use https://cdn.ampproject.org/v0.js

**Comment by taylorhayduk** [comment]
`SOLVED`

Looks like Next.js will compile this correctly if you instead use a <style jsx global> tag.

```
<Head>
  <style jsx global>{`
    body {
      background-color: purple;
    }
  `}</style>
</Head>
```

**Comment by taylorhayduk** [comment]
Note: You might need to do `global={true}`

**Comment by morsssss** [comment]
Before we close this, though... would it be hard to make this recognized as valid AMP?

`<style amp-custom="">`

Others have been generating AMP via JS frameworks, and I can imagine this will come up for others too!

**Comment by morsssss** [comment]
@taylorhayduk , wdyt?
