### ISSUE TITLE
video-percentage-played doesn't trigger

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#22701]
The `video-percentage-played` only triggers at 100% regardless of the `percentages` settings. 

Can be reproduced with `test/manual/amp-video.amp.html`.

**Comment by cvializ** [comment]
Able to reproduce, investigating the root cause.

**Comment by cvializ** [comment]
It looks like the `loadedmetadata` event is triggered by the element before the video manager begins listening for the event, and the `video-percentage-played` feature needs the event to fire to get the duration and emit its event.

**Comment by zhouyx** [comment]
Thank you @cvializ for the fix! 🎉

**Comment by cvializ** [comment]
np!
