### ISSUE TITLE
[Analytics] Rename "baseUrl" to "url" in config

### ISSUE THREAD

**Issue by jonathantyng-amp** [ampproject/amphtml#22705]
## Description

In `amp-analytics` config, deprecate the `baseUrl` attribute in the `requests` objects. Introduce `url` to replace it.

## Additional context

With the introduction of `requestOrigin`, `baseUrl` will no longer technically be the base of the URL. This naming will be confusing for users and renaming it to `url` will be more apt.

cc @zhouyx

**Comment by zhouyx** [comment]
@jonathantyng-amp I assigned the issue to you : ) We can work on this once we merge the `requestOrigin` change
