### ISSUE TITLE
amp-ad - Uncaught TypeError: Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by fox94610** [ampproject/amphtml#22726]
Directly related to this "closed" issue:
https://github.com/ampproject/amphtml/issues/17997

I know this is a 'silent' error that I guess doesn't have any user facing side effects, but I thought y'all should know it's still out there. Go to this page and you'll see it:
https://www.babycenter.com/amp/0_breastfeeding-exclusively-for-3-months-decreases-risk-of-chr_40005552.bc

If you don't see it the first time, reload browser, it's dependent on what ad is being served.

**Comment by torch2424** [comment]
cc @ampproject/wg-ads

**Comment by zhouyx** [comment]
cc @jridgewell

**Comment by jridgewell** [comment]
Dupe of https://github.com/ampproject/amphtml/issues/17997.
