### ISSUE TITLE
fallback for amp-analytics variables

### ISSUE THREAD

**Issue by VorticonCmdr** [ampproject/amphtml#22721]
AMP Analytics supports substitute variables like `${ampdocHost}`, what is missing and should be considered as a feature request ist to define a fallback if the variable returns nothing.

An example on how this could look like:
`${ampdocHost|"fallback value"}`

**Comment by torch2424** [comment]
cc @ampproject/wg-analytics 

Thank you for the issue @VorticonCmdr 😄

**Comment by zhouyx** [comment]
@VorticonCmdr We have support for `$DEFAULT` macro, that should work for you case. 
Try
`$DEFAULT(${ampdocHost}, fallback value)`
and let us know if that works well for you. Thanks.

**Comment by VorticonCmdr** [comment]
@zhouyx thanks. We will try. Where is this documented?

**Comment by zhouyx** [comment]
@VorticonCmdr We haven't get a chance to document these macros yet : (
Here's the code
https://github.com/ampproject/amphtml/blob/be54ccec593891af1bb7396edba9247aa0513126/extensions/amp-analytics/0.1/variables.js#L162-L173
