### ISSUE TITLE
amp-form doesn't clear validation errors

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#22739]
It seems that in some cases we aren't removing the validation message when the form is valid. 

Repro steps:
Go to: https://ninth-melody.glitch.me/
Click on Change Program
<img width="1440" alt="Screen Shot 2019-06-07 at 2 36 18 AM" src="https://user-images.githubusercontent.com/7919520/59074764-45aab780-88cd-11e9-9436-4a563b585dc8.png">

Click on the first entry and select a different Program - "Criminal Justice"
<img width="1440" alt="Screen Shot 2019-06-07 at 2 36 27 AM" src="https://user-images.githubusercontent.com/7919520/59074765-46434e00-88cd-11e9-9b16-0c4f6bf3d626.png">

Click on Select a Degree, you can't select a degree - no prepopulation
<img width="1440" alt="Screen Shot 2019-06-07 at 2 36 49 AM" src="https://user-images.githubusercontent.com/7919520/59074766-46434e00-88cd-11e9-877d-ace5780c4187.png">

Click on Select an Academic Level - "Masters"
<img width="1440" alt="Screen Shot 2019-06-07 at 2 37 00 AM" src="https://user-images.githubusercontent.com/7919520/59074767-46434e00-88cd-11e9-8cc3-a20fceb0b271.png">

Click on Select a Degree, - "MS Criminal Justice"
<img width="1440" alt="Screen Shot 2019-06-07 at 2 37 08 AM" src="https://user-images.githubusercontent.com/7919520/59074768-46434e00-88cd-11e9-9d7a-e9b2654fb3e8.png">

The validation error doesn't get removed. Note this worked for selecting an Academic Level.

**Comment by wassgha** [comment]
@nainar the link is not working, could you update it please?
