### ISSUE TITLE
Cleanup ampdoc-fie experiment

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#22733]
See launch in #22734

TODO for cleanup:

- [x] Remove `FriendlyIframeEmbedLegacy`
- [x] `FriendlyIframeEmbed` make `ampdoc` non-nullable and update the code accordingly.
- [x] cleanup ampdoc service lookup
- [x] Remove `EmbeddableService.installInEmbedWindow` interface.
- [x] Remove `installServiceInEmbedScope` function.
- [x] Remove `opt_win`, `opt_root`, etc arguments from `Bind`, `AmpGwdRuntimeService`, `HiddenObserver`, `Action`, `StandardActions`, `Navigation`, `Url`, and other embeddable services. (See #22493 for some examples).
- [x] Remove the `getExistingServiceForDocInEmbedScope`.
- [x] Remove the `installStylesLegacy`.

**Comment by zhouyx** [comment]
cc @ampproject/wg-ads Does this mean that FIE will have its own instance of ampdoc in the future?

**Comment by dvoytenko** [comment]
yes
