### ISSUE TITLE
Script tag which has amp link print out Custom JavaScript is not allowed.

### ISSUE THREAD

**Issue by heritiermwalila** [ampproject/amphtml#22744]
## What's the issue?

Script tag which include amp library link still print out the 'Custom JavaScript is not allowed'. 
validator.js:533 http://127.0.0.1:5500/article.html:53:0 Custom JavaScript is not allowed. 
code:

```html
<!doctype html>
<html ⚡ lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">

    <link rel="canonical" href="/article.html">
    <link rel="shortcut icon" href="amp_favicon.png">

    <title>News Article</title>

    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
    <style amp-custom>
      body {
        width: auto;
        margin: 0;
        padding: 0;
      }

      header {
        background: Tomato;
        color: white;
        font-size: 2em;
        text-align: center;
      }

      h1 {
        margin: 0;
        padding: 0.5em;
        background: white;
        box-shadow: 0px 3px 5px grey;
      }

      p {
        padding: 0.5em;
        margin: 0.5em;
      }
    </style>
    <script async src="https://cdn.ampproject.org/v0.js"></script>
  </head>
  <body>
    <header>
      News Site
    </header>
    <article>
      <h1>Article Name</h1>

      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam egestas tortor sapien, non tristique ligula accumsan eu.</p>

      <amp-img src="mountains.jpg" layout="responsive" width="266" height="150"></amp-img>
    </article>
  </body>
</html>
```

Briefly describe the bug.

## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. Step 1 to reproduce
2. Step 2 to reproduce
3. …

## What browsers are affected?

Google Chrome is up to date
Version 75.0.3770.80 (Official Build) (64-bit)

All browsers? Some specific browser? What device type?

## Which AMP version is affected?
https://cdn.ampproject.org/v0.js"

Is this a new issue? Or was it always broken? Paste the version of AMP where you saw this issue. (You can find the version printed in your browser's console.)

![error](https://user-images.githubusercontent.com/42043981/59102744-525ef800-892d-11e9-97ad-9a55a96d909f.PNG)

**Comment by sparhami** [comment]
Putting this into the online validator, https://validator.ampproject.org/, seems to work just fine. The amp-validator Chrome extension does report this issue, not sure why.

@Gregable

**Comment by Gregable** [comment]
I cannot reproduce in any AMP Validator, Chrome extension or website.

**Comment by sparhami** [comment]
Oh, I see. When I ran the Chrome extension, I was running using the local gulp serving for development. That rewrote the v0.js URL to `dist/amp.js`, which is invalid. When I run the Chrome extension against the page normally, it works fine. Not sure if that is the original issue.

**Comment by Gregable** [comment]
Sounds like that's the main issue.
