### ISSUE TITLE
video-pause and video-ended triggers fire at the same time

### ISSUE THREAD

**Issue by MisSassi** [ampproject/amphtml#22740]
why does the video-pause and video-ended triggers both fire the moment the video reaches the end? 
Should be only a video-ended event since pause is something different. Any plans to change this?

[(https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-video-analytics.md)]

**Comment by aghassemi** [comment]
This is how HTML `video` and `audio` work. They trigger `pause` on `end` as well. We don't have a plan to change this so we stay consistent with HTML. You should be able to differentiate on server-side however based on the data
