### ISSUE TITLE
AMP4EMAIL: amp-carousel[arrows][autoplay][dots][delay] are invalid

### ISSUE THREAD

**Issue by Nerone95** [ampproject/amphtml#22745]
## What's the issue?

We have an amp carousel with type="slides" but the gmail's playground give us error. 

## How do we reproduce the issue?

You can try with a carosel example.
If you use this code:
 ```
<amp-carousel
			width="600"	height="460" layout="responsive" loop autoplay delay="3000" type="slides">
			<amp-img role tabindex src="https://be-mn1.mag-news.it/nl/res/3626/campaigns/17/img/mainimage.png"
			  width="600"  height="454"  alt="mainimage"></amp-img>
			<amp-img role tabindex src="https://be-mn1.mag-news.it/nl/res/3626/campaigns/17/img/mainimage2.jpg"
			  width="600"  height="454" alt="mainimage"></amp-img>
	  </amp-carousel>
```

in gmail's playground you can see this error. 

_The specified layout 'RESPONSIVE' is not supported by tag 'AMP-CAROUSEL [type=carousel]'. Learn more.
 The attribute 'type' in tag 'AMP-CAROUSEL [type=carousel]' is set to the invalid value 'slides'. Learn more.
 The tag 'AMP-CAROUSEL [type=carousel]' requires including the 'amp-carousel' extension JavaScript. Learn more._

## Which AMP version is affected?

The last one, with this script:
`<script async custom-element="amp-carousel" src="https://cdn.ampproject.org/v0/amp-carousel-0.1.js"></script>`

**Comment by Nerone95** [comment]
up

**Comment by RosSpa95** [comment]
Same problem!

**Comment by aghassemi** [comment]
/to @choumx seems specific to A4Email rules.

**Comment by choumx** [comment]
This is because `autoplay` and `delay` attributes (and `dots` and `arrows`) were removed from AMP4EMAIL validator spec. /cc @fstanis

**Comment by RosSpa95** [comment]
okay, thank you so mutch. 
We see this attributes on the Email Documentations. 
For example:
_"The delay attribute is only applicable to carousels with type=slides."_
and
_"By default, advances a slide in 5000 millisecond intervals (5 seconds); this can be overridden by the delay attribute. Attaches the loop attribute to amp-carousel if loop is not already present.
Requires at least 2 slides for autoplay to occur. Applies only to carousels with type=slides"._

Thanks again.

**Comment by Nerone95** [comment]
Yes, i use this attributes because i found it on the Documentations. 

@choumx  OK! Thank you :)

**Comment by fstanis** [comment]
`delay` and `autoplay` should be supported now (which I think is the main issue here).

**Comment by Nerone95** [comment]
Thank you.
i tried and it works
