### ISSUE TITLE
Adding 'allow-popups' to the consent prompt UI iframe

### ISSUE THREAD

**Issue by hrkhal** [ampproject/amphtml#22759]
Add `allow-popups` to the CMP prompt ui iframe to allow links to open up in a new tab thus matching our standard CMP and existing amp-consent experience.

Our CMP includes links to the privacy policies of all of our advertising partners and vendors and should the user click on one of these links it should open up in a new tab but does not due to current sandboxing.

/cc @zhouyx @torch2424

**Comment by zhouyx** [comment]
closed by #22760
