### ISSUE TITLE
amp-selector: Add support for required attribute for form validation

### ISSUE THREAD

**Issue by westonruter** [ampproject/amphtml#22750]
The `amp-selector` component is intended to be a replacement for a `select`. As such, it supports attributes `disabled`, `form`, `multiple`, and `name`  just like a normal `select` does. It can also be used instead of `radio` buttons or `checkbox`.

However, it cannot be used entirely as a replacement for `radio` as it does not support the `required` attribute. I suggest adding support for this attribute so that one or more selection must be made in the context of a `form` prior to submission.

**Comment by aghassemi** [comment]
We will keep this as a feature request. One workaround is having a invisible required `input` and setting the value of the input based on `amp-selector` selection and letting the browser validate that. (that's how we would implement this anyway).

**Comment by aghassemi** [comment]
(sample for the workaround mentioned above: https://codepen.io/aghassemi/pen/PegPQp?editors=1001)

**Comment by caroqliu** [comment]
@westonruter thanks for filing this issue! Would you mind providing an update in the context of the workaround mentioned above and the discussion in #6930? Is explicit support for the `required` attribute still desirable for your use case? 

cc/ @IamAlta from similar thread with this discussion

**Comment by westonruter** [comment]
It is still desirable, but the workaround works.

**Comment by caroqliu** [comment]
Update: Looked into this further and there is not a clear way to add this feature in a fully accessible way, which would be critical for a feature that can block form submission user flows. Until we figure out this piece of the puzzle we won't be able to release the feature.

cc/ @ampproject/wg-ui-and-a11y

**Comment by caroqliu** [comment]
Closing this issue given the above. Feel free to re-open if there is continued interest.
