### ISSUE TITLE
Uncaught Error: Render timeout waiting for service amp-story-render to be ready.​​​

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#22774]
## What's the issue?
Uncaught Error: Render timeout waiting for service amp-story-render to be ready.​​​
Briefly describe the bug.

Rendering timeout in articles. Sometimes shows log.js or v0.js.

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. https://www.google.com/amp/s/amp.cnn.com/cnn/2019/06/09/americas/mlb-david-ortiz-shot-dominican-republic/index.html
2. Open developer tools
3. Select a category from the selection

## What browsers are affected?
macOSX Chrome Version: 75.0.3770.80 (Official Build) (64-bit)
macOSX Safari Version: 12.1.1 (14607.2.6.1.1)
macOSX FireFox Version: 66.0.5 (64-bit)

## Which AMP version is affected?
Dev Channel: 1906051812580
Stable: 1905292322390

Note: @choumx, is this a Runtime issue?

<img width="1442" alt="Screen Shot 2019-06-10 at 3 16 07 PM" src="https://user-images.githubusercontent.com/48487406/59230718-378dbd00-8b93-11e9-9d1e-99dea0a147d8.png">

**Comment by Enriqe** [comment]
Closed by #31448
