### ISSUE TITLE
Allow the <base> tag

### ISSUE THREAD

**Issue by tomayac** [ampproject/amphtml#2277]
The <base> tag is currently [disallowed](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#html-tags), albeit @cramforce in a [tweet](https://twitter.com/cramforce/status/663012156808425472) said it "could probably be whitelisted pretty easily". The concrete motivation is to support pages that use URL rewriting like below…

```
RewriteRule ^(\d{4})\/(\d{2})\/(\d{2})\/(.*?)$ /index.php?date=$1-$2-$3
```

…which rewrites http://example.org/2016/02/25/foobar to http://example.org/index.php?date=2016-02-25 and requires the base URL be set to http://example.org/ for local links to work.

**Comment by cramforce** [comment]
Filed b/27356051 internally, because this first has to be support in AMP cache serving because it can be made valid.

**Comment by Gregable** [comment]
Closing this old issue. `<base href=/>` is now valid. We may extend this in the future to other `href` values, but this works for the given use case.

**Comment by tomayac** [comment]
While my first AMP pages have just gone live (e.g., https://cdn.ampproject.org/c/s/blog.tomayac.com/categories/technical), it seems like ```<base href=/>``` is not back-translated to the origin URL, as all links currently ```404```, e.g., https://cdn.ampproject.org/2015/06/24/mediterranea-js-trip-report-151125 that should actually point to https://blog.tomayac.com/2015/06/24/mediterranea-js-trip-report-151125 (a currently invalid AMP page, but irrelevant for the actual issue that ```<base href="/">``` served from the AMP Cache forgets it should actually point to ```<base href="https://blog.tomayac.com/">```, which is not allowed as a value). 

(CC: @Gregable @cramforce)

**Comment by cramforce** [comment]
That seems buggy, indeed. I would have expected the base tag to be removed from the output document and the links to be rewritten.

**Comment by jridgewell** [comment]
Reopened our internal issue.

**Comment by Gregable** [comment]
This has been fixed on the cache. New documents or documents that change and are refreshed on the cache should have the correct tags. Still working on reprocessing existing documents.

**Comment by sham77** [comment]
@tomayac thanks for opening that. It's very common indeed. I have the same issue too, and I use the base tag for the same purpose as you mention.

However attn @Gregable @cramforce it seems this hasn't been fully fixed. Trying to validate my amp pages, I get the error  [attribute 'href' in tag 'base' is set to the invalid value]. You can try a test version of it here.  http://test1.shoppinginformer.com/amp-tst/stores/Lacoste/363

**Comment by jridgewell** [comment]
@sham77: We [only allow `/`](https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii#L111-L117).

**Comment by sryze** [comment]
So to clarify, if you use `<base href="/"> and a page is served from http://example.com/app/mypage and has a relative link to myotherpage, when you click on the link you will go to http://example.com/myotherpage, not http://example/app/myotherpage, correct? That is, the base tag doesn't help in this case?

**Comment by dandv** [comment]
Any progress on allowing actual URLs in the `href` attribute?

**Comment by MrMooky** [comment]
Seeing that there are over 1.5k issues currently open, AMP seems to be a big mess. And not be able to have an actual url inside the base tag is just one of the smaller "WTFs". More than two years later and this is still not possible.

**Comment by ZdejPoham** [comment]
And two more years on, still not working with actual URLs...

**Comment by turkoder** [comment]
year 2023 no answer yet
