### ISSUE TITLE
amp-analytics: documentExit only works within same domain

### ISSUE THREAD

**Issue by sanchezedgar** [ampproject/amphtml#22777]
## What's the issue?

When using `amp-analytics` page visibility trigger with the `visibilitySpec` configured to use `documentExit`, the event will only fire when navigating between documents on the same domain but if you navigate to a different domain, the event won’t fire.
```
  ...
  "on": "visible",
  "request": "event",
  "visibilitySpec": {
    "reportWhen": "documentExit"
  }
  ...
```

## How do we reproduce the issue?

You can follow these steps using this reduced test case on JSBin:
https://jsbin.com/jujuhag/2/edit

(To observe the events, click on "Preserve log" in the network tab and look for `POST` requests to `https://httpbin.org/post`)

1. Reload while on the JSBin test case page. The event should fire as expected. 
2. In the location bar of the browser enter a jsbin.com URL (example, http://jsbin.com/help/getting-started) or click on a link from the JSBin navigation and the event will again fire as expected.
3. Now, this time while on the test case page, enter a different domain in the location bar, example, https://google.com. No event fires when the document exits.

## What browsers are affected?

Chrome and Safari are both affected but works perfectly fine on FireFox.

## Which AMP version is affected?

Version 1906051812580

Not sure if this is a new issue but it's the first time we've attempted to use `documentExit`.

**Comment by sanchezedgar** [comment]
re: @alabiaga @zhouyx

**Comment by zhouyx** [comment]
add @jonkeller who knows the `unload` and `pagehide` event better.

@sanchezedgar `documentExit` listens to browsers `unload` and `pagehide` event. I could reproduce the issue you report. I don't have an immediately solution to it right now, because according to the doc [here](https://developers.google.com/web/updates/2018/07/page-lifecycle-api), `unload` event is extremely unreliable. @jonkeller could you help remind me how the `documentExit` event works for you? Thank you

**Comment by jonkeller** [comment]
Hi, Yuxuan and Edgar,

You're right, unload and pagehide are not perfect. Please see comments at
https://github.com/ampproject/amphtml/blob/c4a663d0ba13d0488c6fe73c55dc8c971ac6ec0d/extensions/amp-analytics/0.1/events.js#L1436
and
line 1444 of the same file for some analysis on when each should work.

It is possible that the information in those comments may be outdated now.
But at the time, this seemed to work for a sufficient number of situations,
and a better alternative was not known :/

Please let me know if changes are desired.

Thanks!
-Jon
