### ISSUE TITLE
🌸 Cherry pick request for #22753 into 1906051812580 (Approved)

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#22795]
# Cherry-pick request

| Issue | PR  | Production? | RC? | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---: | :-: | :---------: | :-: | :-----------: |
| #22794 | #22753 | **YES** | **NO** | #22686 |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

This is a regression introduced in #22361. It preventing some partners from continuing A/B testing on AMP conversion.

## Why is a RC cherry-pick not needed?

This is included in today's cut.

# Mini-postmortem

## Summary
This is a regression introduced in #22361. Links with fragments e.g `href=#` would be rewritten as full links (`href=https://example.com#`) even if no linker value was added. 

| Users affected | Impact |
| -------------- | ------ |
| All publishers using fragments on their AMP pages | clicks on these links would cause a full navigation as opposed to scrolling to the right section|

## Root Causes

1. Linker was setting `anchor.href = anchor.href`. In modern browsers the href getter returns the full url.

## Action Items

| Action Item | Type | Owner | PR # |
| ----------- | :--: | :---: | :--: |
| Introduce test that setter was called | Prevent mutation of this attribute | @calebcordry  | #22753 |

## Lessons Learned
Be careful of operations that you think are NOOPs, sometimes they have side effects.

### Things that went well

- Partner team found and reported this bug through the appropriate channels.

### Things that went wrong

- Took too long to find this regression. This fix is only for cache, work to fix canonical is still in progress. Needed better testing.

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by cramforce** [comment]
Discussed offline. Approved for merge after ~24h backing time in canary.

**Comment by nainar** [comment]
Flagging this with @Enriqe for cherry pick when possible.

**Comment by Enriqe** [comment]
Since the release was delayed we still need to wait more time to comply with Malte's request of ~24hr backing time in 1%.

I'll keep the thread updated when this is done.

**Comment by nainar** [comment]
Ahh gotcha - thank you! :)

**Comment by Enriqe** [comment]
After 24 hrs of monitoring and not seeing related issues I went ahead and cherry picked this PR into a new release [1906131851520](https://github.com/ampproject/amphtml/releases/tag/1906131851520).

It is being submitted and soon to be found in production.
