### ISSUE TITLE
🌸 Cherry-pick request for #22546 into 1906051812580 (Approved)

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#22793]
# Cherry-pick request

| Issue | PR  | Production? | RC? | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---: | :-: | :---------: | :-: | :-----------: |
| #22619 | #22546 | **YES** | **NO** | #22686 |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

-  "break existing AMP web pages in a significant way"

When browsing a Story rendered in a viewer, users who open a page attachment get stuck and cannot close it.
They can't swipe down and the `X` button is unresponsive: they can't read the rest of the content and have to leave the page.

## Why is a RC cherry-pick not needed?

The PR fixing this bug is already in today's cut.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

<_YOUR_SUMMARY_>

| Users affected | Impact |
| -------------- | ------ |
| <_Which users were affected? Roughly how many?_> | <_How were users affected? E.g. partial or complete loss of functionality?_> |

## Root Causes

1.

## Action Items

| Action Item | Type | Owner | PR # |
| ----------- | :--: | :---: | :--: |
| <_E.g. Add integration test_> | <_Investigate/Mitigate/Prevent_> | @<_USERNAME_> | #<_PR_NUMBER_> |

### Things that went well

-

### Things that went wrong

-

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by flaviori** [comment]
I would clarify that this is already affecting any AMP Story with page attachments being rendered in a viewer context in production already.

For example to reproduce:
- you can search for [Washington Post] on Google Search on mobile
- scroll down to the visual stories carousel
- click on any one of the Washington Post travel stories in the visual stories carousel
- tap to a story-page with a swipe-up page attachment and try out closing.

The same applies to any other story result in organic web results in Google Search.
For example, search for [local guide eat and do rome wapo] on mobile Google Search and click on the Washington Post result.
https://www.google.com/search?q=local+guide+eat+and+do+rome+wapo

**Comment by gmajoulet** [comment]
Friendly ping
cc @cramforce

**Comment by cramforce** [comment]
I think this is high risk and very borderline.

What is the state of this patch? Has it had production exposure via canary/RC?

**Comment by gmajoulet** [comment]
It got pushed to canary 30 minutes ago. Do you want a few more hours of error monitoring before taking a decision here?

**Comment by cramforce** [comment]
Definitely. And manual testing/verification in production using the viewer. I think there is significant risk for a regression.

**Comment by cramforce** [comment]
Given new info on severity (affects non-STAMP pages) this is approved for immediate cherry-pick.

**Comment by gmajoulet** [comment]
cc @Enriqe

**Comment by Enriqe** [comment]
Performing cherry pick.

**Comment by Enriqe** [comment]
Cherry pick is in [new production release](https://github.com/ampproject/amphtml/releases/tag/1906141418310)
