### ISSUE TITLE
"Play video" message in stories should be sized responsively

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#22804]
The message looks really small when the size of the `amp-story-page` is large; we could just size it using `rem` and I think we will get responsive sizing for free.

![Screenshot](https://user-images.githubusercontent.com/1651960/59377008-4d2fed80-8d1f-11e9-9b4f-7d40b461994b.png)

**Comment by gmajoulet** [comment]
I think the original idea behind having a fixed font size was that it wouldn't take too much space over the publisher's story. On most phones and three panels desktop UI I'd say it's fine, but it's true that on fullbleed desktop or some tablets, the button is very small.

@hongwei1990 could you please help us here? Should we simply increase the font size on full bleed desktop / large touch screens, or should we come up with a new design?

**Comment by newmuis** [comment]
This idea came from the fact that the responsive font size would take up the same percentage of space across different stories.

A fixed size font gets continually smaller as the device size gets larger (and vice versa, it will get larger as the device gets smaller)

**Comment by gmajoulet** [comment]
Good point, thanks, let's start with that and revise if Hong comes with better ideas. :)
