### ISSUE TITLE
FR: Replace history for amp-story

### ISSUE THREAD

**Issue by Amanrazdan** [ampproject/amphtml#22806]
This thing came up while working with amp stories. In that we can implement dynamic bookend and also added functionality to move within stories like instagram or snapchat without pressing back and going to home screen again and again. 
https://github.com/ampproject/amp-wp/issues/2442 https://github.com/ampproject/amp-wp/issues/2441

![image](https://user-images.githubusercontent.com/28403318/59382520-88f8a080-8d7b-11e9-814a-b583a8218c80.png)

now what we generally do is to use location.replace to not stack history.
`<script type="text/javascript">
		function change_post(url_toload)
		{
			location.replace(url_toload)
		}
    </script>`

but this can not valid amp js. 

please add this component as an alternative to location.replace and other window or location-based functions

**Comment by choumx** [comment]
FYI history API aside, I don't think the intended use case of custom forward/back buttons would be supported in amp-story anyways.

**Comment by gmajoulet** [comment]
Thanks for the suggestion!
We've solved this in an other way: we allow swiping from one story to the other. But to build this, you need to write a "viewer", that is basically an iframe that renders the Story and can communicate with it.
When set up properly, that viewer will receive touch events from the Story, allowing you to build a "swiping" transition to your next story.

The documentation on how to build a viewer lives [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-viewer-integration/integrating-viewer-with-amp-doc-guide.md)
And the part about swiping from a document to ther other is [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-viewer-integration/integrating-viewer-with-amp-doc-guide.md#enabling-swiping-between-amp-pages)

It is more engineering work to build, but we believe it to be a much better user experience. The arrows on your screenshot might be confusing for the user, as it would be hard to know if clicking on them navigates to the next page, or to the next story...

Please let us know if that doesn't work for you!

**Comment by Amanrazdan** [comment]
thanks would get my team to do this

**Comment by Amanrazdan** [comment]
The documentation over there is not in much detail and also there is no example that I could find.
@gmajoulet can you suggest links related to any of those

**Comment by gmajoulet** [comment]
I'm afraid this is all the documentation we have as of today... Are you actively trying to implement this? If so, when were you trying to get this up and running?
We're discussing how to make this easier to implement but we're still not sure what form it will take. It's work we planned and prioritized for this next quarter.

If you're trying to build this right now, please come talk to use on our [Slack channel](https://amphtml.slack.com/messages/C9ARUE6Q6/) so we can help you
