### ISSUE TITLE
Add analytics triggers to amp-story bookend components

### ISSUE THREAD

**Issue by danieltxok** [ampproject/amphtml#22800]
Currently it is possible to [track when the bookend is fired](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/amp-story-analytics.md#bookend-enter-trigger-on-story-bookend-enter). Ideally we should be able to track how the user interacts with the bookend and which way it continues: it clicks on a similar article, it navigates to the App Store, it decides to share the story via social media...

**Comment by torch2424** [comment]
Triaging to @newmuis 😄 Feel free to re-assign 👍
