### ISSUE TITLE
Certain Image URLs Generate Duplicate dpr Errors

### ISSUE THREAD

**Issue by adjectivedevelopment** [ampproject/amphtml#2281]
This markup generates a Duplicate dpr error, is it possible some character is causing the issue?  Looks similar to https://github.com/ampproject/amphtml/issues/538 `<amp-img width="400" height="300" itemprop="image" srcset="https://ppands81stg.blob.core.windows.net/cmsstorage/pittsburghpaintsstains/media/pps/projects/accent walls/accent-walls-4.jpg?sv=2015-04-05&amp;sr=b&amp;sig=IKEUgWFhPO0NnrrU1SzeqE4NC1zExpJOzdGZLObC070%3D&amp;st=2016-02-25T16%3A30%3A19Z&amp;se=2016-02-26T16%3A35%3A19Z&amp;sp=r" alt="A Little Goes A Long Way" />`

**Comment by dvoytenko** [comment]
There's a space in the URL that should be encoded: `accent walls` -> `accent%20walls`
