### ISSUE TITLE
AMP page showing invalid while serving from google cache

### ISSUE THREAD

**Issue by ziyed** [ampproject/amphtml#22819]
## What's the issue?

I have an AMP website which has a valid amp page validated using AMP validator. The problem is that, for some of the pages sometime it is showing "Sorry this page is Not valid AMP HTML" error while searching on google and trying to access the page from google cache. after a few seconds it is auto redirecting to my AMP site. 

amphtml & canonical links are valid on both AMP and Non-AMP page i have checked.

Also my page passed AMP validation successfully without any errors. 

My Question is what could be the possible reason behind the google cache showing invalid AMP html although I have a valid AMP page?

What should be solution for this issue?

## What browsers are affected?

Tested on iPhone Safari browser for now

## Which AMP version is affected?

AMP version: 1906051812580

**Comment by torch2424** [comment]
cc @Gregable @pbakaus @sebastianbenz @morsssss

**Comment by morsssss** [comment]
Have you looked in Search Console? It can tell you about AMP validation errors that occur on your page on the cache.

If that doesn't help, can you provide more details here? Especially a URL of a page that exhibits this problem?

**Comment by ziyed** [comment]
Hi morsssss,

Thanks for your comment, Yes I have checked the console got an error like this 
**Failed to load resource: the server responded with a status of 404 ()**
After showing this console error it is auto redirecting to my AMP site which is available and not a 404 page

**Comment by morsssss** [comment]
Based on this conversation so far, I don't think you're going to be able to provide enough details here to debug! Maybe you should try something more interactive - like our Slack channel? That's https://amphtml.slack.com .

**Comment by ziyed** [comment]
Hi morsssss,
I did not find any more console alert rather than what I have shared. Thanks for the info.

**Comment by choumx** [comment]
Ben means Google Search Console, not dev console. 

https://support.google.com/webmasters/answer/7450883?hl=en
