### ISSUE TITLE
Error: Object has no method 'endsWith'

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#22822]
Seeing a high rate of occurrences of this error -- 18.5k in 1% / 36k in all services. First seen 18 hours ago.

Seems to have been introduced in #22712 or #22510

```
Error: Object https://www.wattpad.com has no method 'endsWith'
at endsWith (https://raw.githubusercontent.com/ampproject/amphtml/1906111828200/src/cookies.js:128)
at getHighestAvailableDomain (https://raw.githubusercontent.com/ampproject/amphtml/1906111828200/extensions/amp-analytics/0.1/linker-manager.js:91)
at init (https://raw.githubusercontent.com/ampproject/amphtml/1906111828200/extensions/amp-analytics/0.1/amp-analytics.js:547)
```
`go/ampe/CIu1wLjmssarlAE`

This week's release issue: #22792

**Comment by zhouyx** [comment]
Thank you @Enriqe. #22510 seems to be the cause. 

From here, 
https://github.com/ampproject/amphtml/blob/11a1e760c5215d45e3e98c6f58d443973b300642/src/cookies.js#L126-L128

However, looking at the `#getSourceOrigin()` method, it always returns a string, not an object. 
https://github.com/ampproject/amphtml/blob/11a1e760c5215d45e3e98c6f58d443973b300642/src/url.js#L512-L515

@jridgewell Do you happen to how why the returned origin is an object? Thank you

**Comment by jridgewell** [comment]
`sourceOrigin` isn't an object (the error message is bad). The error is that `endsWith` is a ES6+ method, and not available on these old browsers. Use the [`endsWith`](https://github.com/ampproject/amphtml/blob/11a1e760c5215d45e3e98c6f58d443973b300642/src/string.js#L61-L70) helper.

**Comment by zhouyx** [comment]
Thank you for the explanation that makes sense. How many browsers will be affected? Do you think it's worth a cherrypick? Thanks

**Comment by jridgewell** [comment]
These are [super old browsers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith#Browser_compatibility) and IE11...

**Comment by zhouyx** [comment]
Cool. Do you think it's worth adding a presubmit check for `.endsWith(`. If so, I can add that.

**Comment by jridgewell** [comment]
There's [already](https://github.com/ampproject/amphtml/blob/master/build-system/conformance-config.textproto#L65-L69) one.

**Comment by zhouyx** [comment]
Hmm I wonder why it didn't catch this usage

**Comment by jridgewell** [comment]
Reopening and assigning to @rsimha

**Comment by rsimha** [comment]
This should've been caught by `gulp check-types`. I can confirm that we are correctly passing `--conformance_configs=build-system/conformance-config.textproto` to closure compiler during that check. Not sure why it's not detecting illegal usage of `.endsWith`. Investigating.
