### ISSUE TITLE
Clean up amphtml repo permissions

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#22825]
We now have the Reviewers and Collaborators roles to define who has write access to the amphtml repo.

Currently we have many people listed individually as having write permissions; let's clean this up.

**Comment by mrjoro** [comment]
I have completed the first step, removing people who are currently in Reviewers but also listed individually as having write permissions.  If you notice any problems as a result, let me know.

**Comment by gmajoulet** [comment]
Some of us (including @jridgewell, @cvializ, @Enriqe) lost the "Restart build" button on the Travis CI interface, do you think this could be related? If that helps debugging, @estherkim can still see that button.

Thanks!

**Comment by gmajoulet** [comment]
Looks like it came back :)
