### ISSUE TITLE
"Play video" message in stories should be re-evaluated whenever video playback is attempted

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#22820]
If a video fails to play automatically, then the video is retried without user interaction, it is possible for the video to succeed the second time.  For example, if the window is put in the background, then brought back to the foreground, the `resumeCallback` will be executed and video playback attempted again.

Without doing this, the "Play video" label can potentially be shown on top of a playing video.

**Comment by gmajoulet** [comment]
Fixed by #23754
