### ISSUE TITLE
amp-youtube loads thumbnail image despite layout="nodisplay"

### ISSUE THREAD

**Issue by sryze** [ampproject/amphtml#22834]
## What's the issue?

When a video is hidden via `layout="nodisplay"` the thumbnail image is loaded during page load. IMO it should not be loaded until the video becomes visible.

Also, if you put a video inside a lightbox that has `layout="nodisplay"` you can observe the same behavior. Ideally I would like amp-youtube to not load thumbnails until its parent lightbox is shown.

## How do we reproduce the issue?

```
<amp-youtube layout="nodisplay" data-videoid="lBTCB7yLs8Y"></amp-youtube>
```

Above code will cause https://i.ytimg.com/vi/lBTCB7yLs8Y/sddefault.jpg to load.

## What browsers are affected?

Tested in Chrome, Firefox

## Which AMP version is affected?

1906131851520

**Comment by aghassemi** [comment]
Currently we create and append the default placeholder during `buildCallback`, at least setting the `src` part should move to `layoutCallback`

**Comment by cramforce** [comment]
I think the behavior is correct. Placeholders should load eagerly.
