### ISSUE TITLE
Google Ads - pause after 30 seconds (amp-animation)

### ISSUE THREAD

**Issue by html5maker** [ampproject/amphtml#22842]
## Describe the new feature or change to an existing feature you'd like to see

Google Ads require animation to stop after 30 seconds. Imagine you have a 7-second animation that loops. There need to be a property in amp-animation to specify the timeout when animation need to be paused.

## Describe alternatives you've considered

Provide a clear and concise description of any alternative solutions or features you've considered.

## Additional context
<img width="873" alt="2019-06-14 22-30-08" src="https://user-images.githubusercontent.com/27346151/59536446-0810e480-8ef4-11e9-9a08-75978224b45c.png">

**Comment by sparhami** [comment]
`amp-animation` allows you to specify the number of iterations to play the animation for. This can also be a fractional amount or the result of a `calc` expression.

For example, if you wanted to play for exactly 30 seconds, you can do:


```javascript
{
  "duration": "7s",
  "fill": "both",
  "iterations": "calc(30/7)",
  …
}
```

It may make more sense to just use 4 iterations however.

Perhaps this can be better documented, both on amp-ads as well as the documentation for `amp-animations`.
