### ISSUE TITLE
AMP story link sharing issue in Safari 

### ISSUE THREAD

**Issue by ernee** [ampproject/amphtml#22851]
## What's the issue?

Instead of the modal window with the option to copy the AMP story link, in Safari 12.1.1 the sharing icon reveals the following menu: 

![MacOS Safari AMP story link sharing](https://user-images.githubusercontent.com/8108643/59560073-c8d5b700-900b-11e9-84dd-d161f3598721.png)

## How do we reproduce the issue?

One can reproduce the steps in this story: https://www.washingtonpost.com/graphics/2019/world/amp-stories/hong-kong-protests/

1. Click on the sharing icon at the top right
2. See the menu revealed (instead of the modal window for link sharing)

## What browsers are affected?

MacOS (possibly iOS), Safari, Version 12.1.1 (14607.2.6.1.1)

## Which AMP version is affected?

AMP version: 1906141418310

This is the first I've tested this functionality, so I'm not sure if it has occurred before. I spotted this [previous issue ](https://github.com/ampproject/amphtml/issues/13136) about iOS Safari. In my current testing (in the Xcode simulator app, iOS 12.2), the same may be occurring: 

![Screen Shot 2019-06-16 at 8 08 38 AM](https://user-images.githubusercontent.com/8108643/59560230-d7719d80-900e-11e9-83a5-1cd15c939b81.png)

(do not have an actual Apple mobile device to reproduce)

**Comment by newmuis** [comment]
Hi @ernee,

We delegate to the link sharing mechanism natively provided by the platform, if one is made available, and provide our own if one is not.  As such, the options that appear in this list are defined by the platform/browser vendor.

May I ask what in particular is broken about the native sharing option?

**Comment by ernee** [comment]
hi @newmuis,

Thanks for your explanation. It makes sense now. My expectation was the modal provided in both Safari and Firefox:

**Comment by newmuis** [comment]
Sounds good, closing this issue for now, then.  Please feel free to reopen if you have any further questions or concerns!
