### ISSUE TITLE
amp-iframe access parent inner height

### ISSUE THREAD

**Issue by demil** [ampproject/amphtml#22854]
To solve a problem from #22644 i tried solution to use amp-iframe resizing capability to set iframe to be exact height of `window.parent.innerHeight` but i can not access it, and the error is:

> Uncaught DOMException: Blocked a frame with origin "null" from accessing a cross-origin frame.
    at <anonymous>:1:15

but iframe is on same domain, scheme and port.

is there any possibility to access parent window height, then use javascript inside iframe to calculate exact window height as described in referenced issue, and then use amp-iframe resizing capability to achieve window 100% height. It seems a little bit hacky, but i am trying everything possible to have 100% height on mobile without using javascript fixes and to stay amp valid page.

**Comment by aghassemi** [comment]
Not currently possible, I remember @zhouyx & @lannka were thinking about a similar use-case for Ad iframes. Not sure where we ended up.

**Comment by zhouyx** [comment]
Ad iframes can register to the IntersectionObserver listener, which includes info about viewport Rect . 
https://github.com/ampproject/amphtml/blob/master/ads/README.md#position-in-viewport

`<amp-iframe>` intersectionObserver API we provide is a bit different from the ads one. But may be possible to retrieve the viewport size with `IntersectionObserverEntry.rootBounds `. https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md#iframe-viewability

**Comment by aghassemi** [comment]
Thanks @zhouyx.

@demil Please give https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md#iframe-viewability a try and see if `rootBounds` is enough to handle your use-case, if not, please reopen the feature request.
