### ISSUE TITLE
iOS : amp viewer amp-bind issue in menu with z-index

### ISSUE THREAD

**Issue by josselinDecathlon** [ampproject/amphtml#22859]
## What's the issue?

When going to an our amp page with an iPhone. I open the menu and click on submenu. The title of the category should appear at the top of the menu. But the text seems to be under my menu layer. It appears that the div containing the category name get extracted from the amp-sidebar element which seems to be the problem. 

## How do we reproduce the issue?

Search "decathlon velo" from an iOS device or using the chrome dev tool emulation of iOS devices. 

Load the page in the amp viewer by clicking the amp result on search, open the menu, click on the item "Tous les sports" for example. Instead of the title a blue color bar appears. When closing the menu, the category title appears on the page (it shouldn't).

## What browsers are affected?

Chrome and Safari browsers on iOS.

## Which AMP version is affected?

The current version.

Video of the bug available at this link.
https://drive.google.com/open?id=1-sDFuQhphVoBbPYPl4N6-qrSFoLT2u0A

**Comment by torch2424** [comment]
Triaging to @aghassemi , cc @kristoferbaxter 😄

**Comment by jridgewell** [comment]
This would be fixed by https://github.com/ampproject/amphtml/pull/22881.

**Comment by choumx** [comment]
The PR above is merged and will be in this week's canary and prod in next. Please let us know if it's not fixed by end of next week.
