### ISSUE TITLE
Intent to Implement - Amp Sharethrough

### ISSUE THREAD

**Issue by peterkinmond** [ampproject/amphtml#2286]
# Overview

Displays a [Sharethrough](http://www.sharethrough.com/) native ad. 

# Usage

```
<amp-sharethrough 
	data-native-key="abcd1234">
</amp-sharethrough>
```

## Required attributes

**data-native-key**

The native or placement key for the ad unit, an hexadeximal string.

# Considerations

* We didn't use `amp-ad` for these reasons:
	* Not able to inherit styles of parent page, due to inline CSS required in AMP
	* The size of an ad unit must be static. It must be knowable without fetching the ad and it cannot change at runtime except through iframe resizing

**Comment by peterkinmond** [comment]
Relates to #2271

**Comment by cramforce** [comment]
This should be implemented as `amp-ad`. Happy to discuss its limitations to make sure it works for you.

Your custom component cannot itself work around the sizing limitations. For it to be accepted into the code base it would also need to comply with the restriction on resizing. In particular, you must not require a HTTP request to determine the size of the box.

**Comment by nuclearghost** [comment]
The size of the box would be determined by the same `layout`, `width`, and `height` components of other amp elements and wouldn't need to be updated based on the HTTP response. This component would be sized the same way a publisher would size any other amp-element.

In order for publishers to support the best looking and feeling native ads, we inherit style from the publisher's parent page. Our approach allows the publisher to update their site CSS and thus native ads without any additional work or communication. My understanding of AMP limitations is that there aren't any external style sheets. If we were to use `amp-ad` which is in an iFrame, how could we inherit these styles?

**Comment by jasti** [comment]
Closing since #3036 has been merged.
