### ISSUE TITLE
String "Undefined" flashes on Story slide

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#22865]
I heard this from someone else and then was able to repro on my phone.

Happens on this STAMP
https://www.washingtonpost.com/graphics/2019/world/amp-stories/hong-kong-protests/

The undefined flashes during load at the bottom-left of the screen and then during slide navigation in the top left.

May require a slow-ish connection to repro, and doesn't repro consistently for me.

**Comment by newmuis** [comment]
Believe it or not, this is actually a publisher issue; the string "undefined" is just actually in the story (a lot, actually).

It only disappears because they've layered other content on top of it.
