### ISSUE TITLE
AMP Form speed issue

### ISSUE THREAD

**Issue by scottxmarshallx** [ampproject/amphtml#22861]
## What's the issue?

I'm having issues with the amp-form. The main issue is speed.  When clicking send the form is taking upto 30 seconds to send. 

The form is working, it does send eventually. If I inspect the page and view network to try and see what is going on it sends instantly as expected. When viewing the page normally it is really slow. 

I have contacted my hosting company to confirm the issue is my end rather than a server issue.

I have no idea what would be causing this? 

I have contacted my hosting company to confirm the issue is my end rather than a server issue.

I have posted on StackOverflow also and have pasted all my code also:

https://stackoverflow.com/questions/56629241/amp-form-problems-very-slow

## What browsers are affected?

Chrome, possibly all.

## Which AMP version is affected?

https://cdn.ampproject.org/v0.js

**Comment by aghassemi** [comment]
Hi @scottxmarshallx this would be a server side problem. Please profile your network and see how long the XHR endpoints takes to respond.
