### ISSUE TITLE
amp-accordion with amp-anim

### ISSUE THREAD

**Issue by Nerone95** [ampproject/amphtml#22864]
## What's the issue?

Hi, we have a problem with amp-accordion in amp email.

If we use amp-anim inside the accordion, the second time you open the accordion the amp-amin does not appear.

## How do we reproduce the issue?

```
<amp-accordion class="accordion" animate>
	<section>
		<h4>SHOW IMAGE</h4>
		<div>
		<amp-anim src="https://bit.ly/2XT7pnp" width="600" height="300" alt=""></amp-anim>
		</div>
	</section>
</amp-accordion>
```
## What browsers are affected?

All and gmail

## Which AMP version is affected?
**On amp for email**
```
<script async custom-element="amp-anim" src="https://cdn.ampproject.org/v0/amp-anim-0.1.js"></script>
<script async custom-element="amp-accordion" src="https://cdn.ampproject.org/v0/amp-accordion-0.1.js"></script>
```

**Comment by aghassemi** [comment]
Thanks @Nerone95.

I can repro this: https://s.codepen.io/aghassemi/debug/xoOZxj

Problem is when we `unlayout` `amp-anim`, both `src` and `srcset` are set to some tiny in memory bytes, when the `amp-img` gets `relayout` again, fake `srcset` sticks around and breaks it.

**Comment by Nerone95** [comment]
Thanks for your reply :)

So this bug will be fixed later?

**Comment by aghassemi** [comment]
Yes, @sparhami already merged a fix. Will be in production in a week.

**Comment by Nerone95** [comment]
good!
Tnk!
