### ISSUE TITLE
Image galleries with amp carousel page 404 

### ISSUE THREAD

**Issue by Stefany93** [ampproject/amphtml#22877]
## What's the issue?

Page 404'od 
![image](https://user-images.githubusercontent.com/2403939/59635721-7da8ca80-9117-11e9-8f14-345c73746114.png)

https://amp.dev/advanced/image_galleries_with_amp-carousel/

## How do we reproduce the issue?

Go here https://amp.dev/documentation/examples/components/amp-carousel/
Click "A good use case for amp-carousel are image galleries, here are some examples."

**Comment by torch2424** [comment]
Hello!

Thank you for the issue! cc @pbakaus @sebastianbenz 

Though, I think this will probably be moved to the amp.dev repo: https://github.com/ampproject/docs

Thanks! 😄

**Comment by aghassemi** [comment]
Fixed by https://github.com/ampproject/docs/pull/2336
