### ISSUE TITLE
amp-social-share not sharing proper url in amp-next-page articles

### ISSUE THREAD

**Issue by k-prashant** [ampproject/amphtml#22893]
## What's the issue?

Next articles are loaded using `amp-next-page` components. Also, used `amp-social-share` component for sharing articles. 
`amp-social-share` works properly on first article, but when scrolled to next article, `amp-social-share` uses title and url of first article. It happens to every subsequent articles.

## How do we reproduce the issue?

For every next article loaded after first article using `amp-next-page` components, the `amp-social-share`  uses incorrect title and url.
`amp-social-share` with type `system` doesn't allow to use custom` data-params-*`

## What browsers are affected?

All browsers

## Which AMP version is affected?

Since `amp-next-page` is experimental, it can be a feature request to support `amp-social-share`.

**Comment by irrelevante** [comment]
This issue persist in the non-experimental 1.0 version.
