### ISSUE TITLE
Add a trigger for when a story is completed

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#22901]
Master issue #12191

Right now, we rely on the bookend trigger to know whether a story was completed or not. This could cause issues in the future if we decide to introduce an option where the bookend is not available in some stories. 

Let's add a specific event for when a story is completed.

**Comment by jeffjose** [comment]
cc/ @zhouyx

**Comment by zhouyx** [comment]
Thanks @Enriqe. 
Instead of creating a brand new event type. What do you think that we add some variable specifically to the `story-page-visible` event? You can refer to the visibility event variables here https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#visibility

**Comment by Enriqe** [comment]
Sure, no issue with me. Thanks @zhouyx!

**Comment by zhouyx** [comment]
Talked to @jeffjose offline. He wanted to support sending the story end to different request url.  Let's still do different event types : ) Because event is one to one match to request.

**Comment by Enriqe** [comment]
Sounds good 👍
