### ISSUE TITLE
[amp-viewer]Fixed/sticky elements have layout issues inside amp-viewer.

### ISSUE THREAD

**Issue by xiaotong-kk9** [ampproject/amphtml#22920]
## What's the issue?

Fixed/sticky elements have layout issues.

## How do we reproduce the issue?

Fixed elements: (Mobile Browser: Chrome 75.0.3770.85 iOS 12.1.2)
1. Visit [amp page link](https://www.fs.com/amp_index.php) and [amp viewer link](https://www.google.com/amp/s/www.fs.com/amp_index.php)
2. Inside amp-viewer, the header of the page is covered by viewer header. It should be displayed below the viewer header.

![1643699](https://user-images.githubusercontent.com/8028004/59736331-bff31880-928b-11e9-89fd-a78379fb49aa.jpg)

Sticky elements: (Desktop browser: Chrome 75.0.3770.90 Mac 10.14.5)
1. Visit [amp page link](https://blog.amp.dev/) and [amp viewer link](https://www.google.com/amp/s/blog.amp.dev/)
2. Please scroll down the page inside amp-viewer. The sticky element (`header.ap--header`) moves out of the viewport.

AMP page screenshot:
![Screen Shot 2019-06-19 at 12 22 32 PM](https://user-images.githubusercontent.com/8028004/59736600-f4b39f80-928c-11e9-925e-96500614d18a.png)

AMP page inside amp-viewer screenshot:
![Screen Shot 2019-06-19 at 12 22 37 PM](https://user-images.githubusercontent.com/8028004/59736627-101eaa80-928d-11e9-9dd0-36f3039c760f.png)

## Which AMP version is affected?

1906141418310

**Comment by xiaotong-kk9** [comment]
@jridgewell
Hey Justin, not sure if you are the right one to ask :)
Since fixed and sticky elements can not display perfectly as intended, what is the best solution/workaround to implement a sticky header?

**Comment by jridgewell** [comment]
You need to set a `top: 0` style on the element that is actually `position: fixed`. In your case, it should be on the `div.header_main` element, not the `header` element.
