### ISSUE TITLE
AMP.setState causes browser to request favicon.ico repeatedly

### ISSUE THREAD

**Issue by mattwomple** [ampproject/amphtml#22935]
## What's the issue?

Whenever `AMP.setState()` is called, the browser makes another request for favicon.ico.

## How do we reproduce the issue?

1. In Chrome, with DevTools open, visit [android.cmphys.com/temp/amp-list-binding-refresh-bind.html](https://android.cmphys.com/temp/amp-list-binding-refresh-bind.html)
2. Click the "Make text green" or "Make text black" button
3. Watch for a new entry in Chrome DevTools Network tab

## What browsers are affected?

This was observed on: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36`

## Which AMP version is affected?

1906141418310

**Comment by torch2424** [comment]
Triaging to @choumx , feel free to re-assign 😄

**Comment by mattwomple** [comment]
This is (mostly) out of AMP's control and is likely limited to Chromium. When the browser's native `history.replaceState()` is called, `favicon.ico` is requested. You can try this on any site you like:
```javascript
let state = history.state || {};
state.url = location.href;
history.replaceState(state, undefined, state.url);
```
So, as long as bind states are stored in history, this behavior will exist. Closing this issue since there's nothing more that needs to be pursued.
