### ISSUE TITLE
Livereload support

### ISSUE THREAD

**Issue by jcdarwin** [ampproject/amphtml#2294]
As part of dev workflows, having the ability to use livereload would be very useful, however this of course injects a script into the page, which is not allowed by AMP.

Could there be any way in future that we could have access to tools like livereload when developing AMP pages?

**Comment by cramforce** [comment]
@jcdarwin We actually use it during development. It makes the document technically invalid, but as long as you know that one error is expected it should be fine.

Ideally there would be some mechanism to ignore certain errors (e.g. triggered by hash fragment). I'd accept that as a PR :)

**Comment by jcdarwin** [comment]
Could we have a mechanism where we use a particular value for the type
attribute on the script tag (i.e. similar to that used for the
JSON-LD script, e.g. type="application/amp-invalid"
or type="application/amp-dev"), coupled with the fact that it's a page
served in a non-production environment (e.g. has localhost or something
like amp-dev somewhere in the URL)?

I'm guessing we wouldn't want this facility to be available / abused in
production.

As well as the livereload case, this mechanism would also be useful for
allowing the use of a script to report back and collect actual browser
performance of the amp page.

**Comment by rudygalfi** [comment]
Closing since there hasn't been any action on this in awhile.
