### ISSUE TITLE
amp-consent CMP: Frame height differs from amp-lightbox

### ISSUE THREAD

**Issue by torch2424** [ampproject/amphtml#22943]
A vendor reported the following:

> One using amp-consent v2 and the other using amp-lightbox for comparison. We’d expect the fullscreen prompt to behave the same as amp-lightbox. Note the checkConsent call is only going to show prompt if you’re in the EU since it’s pointing to our prod endpoint. The fullscreen Prompt and Lightbox Content in both of the examples consist of ten divs at 10% height each.

[Demo Current](https://static-metro-co-uk.s3-eu-west-1.amazonaws.com/amp/consent-ui/index.html)
[Demo Desired](https://static-metro-co-uk.s3-eu-west-1.amazonaws.com/amp/consent-ui/lightbox.html)

cc @zhouyx

**Comment by hrkhal** [comment]
@torch2424 Does #23491 fix this? I see nothing in the PR that affects the height, only that the AMP viewer will now be hidden with `requestFullOverlay`. Am I missing something?

**Comment by torch2424** [comment]
@hrkhal Yes! So from my understanding, the height of light box (in full screen mode), should be the same as they are both based on either viewport or percentage units. 

Perhaps I misunderstood the problem then. Are you more curious about the non fullscreen height? 

Thank you! 😄
