### ISSUE TITLE
How to apply for amp-experiment-token?

### ISSUE THREAD

**Issue by zhuozhang19911122090807** [ampproject/amphtml#22953]
1. When using amp-script, must amp-experiment-token?
2. How to apply for amp-experiment-token?
2. When using amp-script, can the src link content not use node.js, use the original javascript?

**Comment by torch2424** [comment]
Triaging to @kristoferbaxter feel free to re-assign 😄

**Comment by choumx** [comment]
Use the "Origin Trial" link on the amp-script documentation to sign up for an experiment token: https://github.com/ampproject/amphtml/blob/master/extensions/amp-script/amp-script.md

> When using amp-script, can the src link content not use node.js, use the original javascript?

The JS is meant to be run in a browser context, not Node.js.
