### ISSUE TITLE
Chrome Canary menu stuck

### ISSUE THREAD

**Issue by jidanni** [ampproject/amphtml#22959]
First install the latest version of Chrome Canary from the Google Play Store on Android.

 Now browse
https://www.google.com.tw/amp/s/www.howtogeek.com/226184/how-to-identify-a-song-on-any-smartphone-pc-or-tablet/amp/

You will see the Chrome Canary menu at the bottom of the screen does not ever go down like it should. It is permanently stuck occupying a big chunk on the bottom of the screen

**Comment by choumx** [comment]
Which version of Chrome was that? This issue may be obsolete now that it's been awhile.

**Comment by jidanni** [comment]
> ...commented on Jun 21
> First install the latest version of Chrome Canary from the Google Play Store on Android.

So that's the version, the one of Jun 21.

I don't have my phone handy to test the current version.

**Comment by choumx** [comment]
Per [version history](https://omahaproxy.appspot.com/), it was earlier than `android,canary,77.0.3843.2,2019-07-04 21:39:04.266007`. 

Current stable is `77.0.3865.92` and we haven't heard other reports of this, so I think it might've been a red herring or a canary-only feature.
