### ISSUE TITLE
Images scrolling on its own

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#22950]
## What's the issue?
Images scrolling on its own

Briefly describe the bug.
When selecting an item on AliExpress, it takes you to another page and the images begin scrolling on their own.

## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. Opt into Canary
2. Open JavaScript Console
3. Open https://m.aliexpress.com/wholesale/red-wig.html?searchType=mainSearch&keywords=red-wig&shadingAction=&channel=direct
4. Select a item
5. On new tab open JavaScript console

## What browsers are affected?
macOSX Chrome Version 75.0.3770.90
macOSX FireFox Version 67.0.4

## Which AMP version is affected?

Dev Channel (Canary): 1906191709480

![ali_express_fast_moving_images](https://user-images.githubusercontent.com/48487406/59885721-19814300-9371-11e9-97b1-5b5e76afca16.gif)

**Comment by diantekyrie** [comment]
If the first photo is actually a video it may not scroll through all the images.

**Comment by nainar** [comment]
@diantekyrie is this still an issue you have come across?

**Comment by diantekyrie** [comment]
@nainar no I'm not able to reproduce. I'll close this and reopen it if required.
