### ISSUE TITLE
amp-accordion not working at all, adds loading delay for entire site

### ISSUE THREAD

**Issue by 88kbbq** [ampproject/amphtml#2295]
Testing shows a three second delay before page loads and the contents of amp-accordion do not display regardless of the expanded class. Temporarily viewable at pos. 88k. com. tw

**Comment by cramforce** [comment]
@88kbbq Could you paste a valid test URL?

**Comment by cramforce** [comment]
I believe that `amp-accordion` is currently behind an experiment. @sriramkrish85 Do the docs state clearly that it cannot actually be used for prod sites?

**Comment by 88kbbq** [comment]
The URL is pos.88k.com.tw. I'm sure you have examples in the works. Just reporting.

**Comment by jridgewell** [comment]
I'm looking into this one, it appears the AMP-Accordion extension is not fulfilling it's Element Service Promise. The 3 second delay is the timeout for us to wait for the service to load.
