### ISSUE TITLE
amp-ima-video: Does not show Play/Pause buttons when an ad is playing

### ISSUE THREAD

**Issue by torch2424** [ampproject/amphtml#22952]
Currently, `amp-ima-video` does not show the play/pause buttons while an ad is playing.

[Demo](https://amp.dev/documentation/examples/components/amp-ima-video/)

![Screen Shot 2019-06-20 at 5 08 20 PM](https://user-images.githubusercontent.com/1448289/59888831-615a9700-937e-11e9-8223-4f72f2b9d660.png)

cc @curseagain 😄

**Comment by curseagain** [comment]
Oh no!  I'll take a look this weekend 👍 Thanks for the cc, @torch2424.

**Comment by torch2424** [comment]
@curseagain No worries! More of an FYI than an assignment 😄 So no pressure to do this, but if you can / want to that would be rad! 👍

**Comment by curseagain** [comment]
@torch2424 I have a fix in progress now, but it requires some tweaks to the logic surrounding play/pause.  That logic was written with the assumption that no play button would be displayed until the video started.

Just wanted to give you a heads up!  I should have this ready for review soon!

**Comment by torch2424** [comment]
@curseagain Awesome! Thank you very much! Stoked to do a review for this 😄
