### ISSUE TITLE
Cannot read property 'frameElement' of null

### ISSUE THREAD

**Issue by bmarotta** [ampproject/amphtml#22961]
## What's the issue?

An unhandled exception is raised: 

TypeError: Cannot read property 'frameElement' of null

## How do we reproduce the issue?

Check details here: https://sentry.io/share/issue/7cfc752c7b4b41109082328ee016644c/

## What browsers are affected?

Chrome

## Which AMP version is affected?

https://raw.githubusercontent.com/ampproject/amphtml/1906111828200/ads/inabox/position-observer.js

**Comment by torch2424** [comment]
cc @ampproject/wg-ads 😄

**Comment by jeffj6123** [comment]
I also see this issue. We use Google AdSense and this is breaking some of our pages

**Comment by jeffj6123** [comment]
is there any ETA for when this would be fixed?

**Comment by jeffj6123** [comment]
I can try and add as much info as possible.
Its an angular 8 application and we have it fire from multiple places
https://sentry.io/share/issue/4478b945b1144f53ab86dac016c61f61/
https://sentry.io/share/issue/0e6de6350f8d4ca6925d8ba88bd6913d/
https://sentry.io/share/issue/f74f8f8c00da4d0cba9c95e6caee6a53/
https://sentry.io/share/issue/2c631029a48045199889b98ee289c864/
https://sentry.io/share/issue/2c631029a48045199889b98ee289c864/

so besides the original issue posted above we also saw additional issues around the same area. Let me know if there is any other info that would be useful.

**Comment by jridgewell** [comment]
Do you have a page that causes this error?

**Comment by jeffj6123** [comment]
@jridgewell to give as much context as possible. There was an issue raised by our users saying our page would lock and would not be able to scroll up and down. Primarily on mobile but a few times on desktop. One time when a user had the issue reported we were able to get them to open dev console and send a screenshot and that's how we traced to the ads causing the problem. We have since then removed all ads and have no more reported issues. 
![image](https://user-images.githubusercontent.com/15344718/65536473-513fdf80-deb8-11e9-80dd-1f8d4dab1ef4.png)
This is what we were given by our users.

**Comment by jeffj6123** [comment]
are there any updates on the status of this?

**Comment by halaei** [comment]
Not sure but this propably has to do with overriding on IntersectionObserver.observe(). I override the observe() like bellow and see the error:
```js
const observeIntersection = IntersectionObserver.prototype.observe;
IntersectionObserver.prototype.observe = function (target) {
    //...
    return observeIntersection.call(this, target);
}
```
To fix, I replaced call with apply: `observeIntersection.apply(this, arguments)`.

**Comment by jeffj6123** [comment]
Are there any updates on this?

**Comment by janlukasschroeder** [comment]
Not AMP, but I'm using the React AdSense component and have the same issue. Error message below:

<img width="678" alt="Screen Shot 2019-11-18 at 8 13 07 pm" src="https://user-images.githubusercontent.com/26613830/69039348-d91d1280-0a3f-11ea-9b42-e130ff5a0d82.png">

**Comment by jridgewell** [comment]
Ping @lannka

**Comment by danyalasif** [comment]
> Not AMP, but I'm using the React AdSense component and have the same issue. Error message below:
> 
> <img alt="Screen Shot 2019-11-18 at 8 13 07 pm" width="678" src="https://user-images.githubusercontent.com/26613830/69039348-d91d1280-0a3f-11ea-9b42-e130ff5a0d82.png">

Having the exact same issue, my sentry logs are spammed by this and I'm reaching my monthly limit because of that. I hope this gets fixed soon or a solution on how to bypass it

**Comment by thattomperson** [comment]
@danyalasif You can always temporarily ignore the error until the issue is resolved
https://stackoverflow.com/questions/55846690/how-to-globally-ignore-errors-with-sentry-v5-to-reduce-noise

I use rollbar and I have done a similar thing for now

**Comment by jeffj6123** [comment]
The issue for us is this seemed to be linked to breaking our page and particularly causing our page to not be scrollable.

**Comment by lannka** [comment]
Fix is coming.

**Comment by tranle13** [comment]
@lannka has this issue been fixed yet? I'm using VueJS with GrapesJS and it's happening to me too.
