### ISSUE TITLE
🌸 Cherry-pick request for #22966 into #22937 (Pending)

### ISSUE THREAD

**Issue by sparhami** [ampproject/amphtml#22979]
# Cherry-pick request

| Issue | PR  | Production? | RC? | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---: | :-: | :---------: | :-: | :-----------: |
| #22966 | #22978 | **NO** | **YES** | #22937 |

## Why does this issue meet the [cherry-pick criteria]
This breaks image lightboxing in Canary. It may also cause major problems for other components using `setAsOwner`.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

<_YOUR_SUMMARY_>

| Users affected | Impact |
| -------------- | ------ |
| <_Which users were affected? Roughly how many?_> | <_How were users affected? E.g. partial or complete loss of functionality?_> |

## Root Causes

1.

## Action Items

| Action Item | Type | Owner | PR # |
| ----------- | :--: | :---: | :--: |
| <_E.g. Add integration test_> | <_Investigate/Mitigate/Prevent_> | @<_USERNAME_> | #<_PR_NUMBER_> |

### Things that went well

-

### Things that went wrong

-

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by cramforce** [comment]
Approved
