### ISSUE TITLE
How can amp-list be refreshed with the latest data but not the cached.

### ISSUE THREAD

**Issue by clodisewp** [ampproject/amphtml#22972]
//------------------------Situation Description:
Here I have an amp-list of user comments. When a user submit a form in a popup window, I set the amp-list to be refreshed in a button. Sometimes the result is the latest data, but more ofter it seems like the cached data. Yes I have SW in my project.

//------------------------Question, as you have seen in the title.

      Post: Please do not suggest me to ask questions in StackOverflow. Because it is international to me, I can not wait minites for the Chrome to load a new page.

**Comment by choumx** [comment]
Have you tried busting browser cache by adding a [`RANDOM`](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#random) URL variable?

**Comment by clodisewp** [comment]
> Have you tried busting browser cache by adding a [`RANDOM`](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#random) URL variable?

Thanks for your reply.
According to your advise, I tried to use RANDOM. But the result seems the same as that yesterday.
Here are the screenshots:
1、data submit:
![image](https://user-images.githubusercontent.com/19813339/60065348-31bcdd80-9736-11e9-97bc-67d12661d529.png)
2、browser network:
![image](https://user-images.githubusercontent.com/19813339/60065386-52853300-9736-11e9-8842-478b24f4d994.png)
3、amp-list refreshed:
![image](https://user-images.githubusercontent.com/19813339/60065411-6892f380-9736-11e9-9371-04807d3eb8d6.png)

In the third image. If I click the button to refresh the amp-list manually, it works ~

**Comment by choumx** [comment]
Oh I see, you might want [`cache=reload`](https://developer.mozilla.org/en-US/docs/Web/API/Request/cache) for the fetch after form submission. 

Can you share a URL of your page or a simplified version of the HTML (with amp-form & amp-list)?

**Comment by clodisewp** [comment]
> Can you share a URL of your page or a simplified version of the HTML (with amp-form & amp-list)?

Because my project is still in localhost test, so here is the simplified version:
**1、amp-list:**
`<amp-list width="1" height="1" id="myamplist" src="/js/ajax/appProductsReview.aspx?opt=view&amp;guid=17996095&amp;p=1" layout="responsive" load-more="manual" load-more-bookmark="next" reset-on-refresh="always" class="i-amphtml-element i-amphtml-layout-responsive i-amphtml-layout-size-defined i-amphtml-layout" i-amphtml-layout="responsive" aria-live="polite" style="height: 477px;"><template type="amp-mustache"><div class="list-item"><div class="review-info"><dl><dt><p>{{name}}<span class="country">[{{countryname}}]</span></p><span class="time">{{time}}</span></dt><dd><span><i class="{{star0}}" aria-hidden="true"></i></span><span><i class="{{star1}}" aria-hidden="true"></i></span><span><i class="{{star2}}" aria-hidden="true"></i></span><span><i class="{{star3}}" aria-hidden="true"></i></span><span><i class="{{star4}}" aria-hidden="true"></i></span></dd></dl></div><div class="review-desc"><p>{{content}}</p></div></div></template><div role="list" style=""><div class="list-item" role="listitem"><div class="review-info"><dl><dt><p>Clock Kenter<span class="country">[]</span></p><span class="time">2019/6/26 9:59:36</span></dt><dd><span><i aria-hidden="true" class="fa fa-star"></i></span><span><i aria-hidden="true" class="fa fa-star"></i></span><span><i aria-hidden="true" class="fa fa-star"></i></span><span><i aria-hidden="true" class="fa fa-star"></i></span><span><i aria-hidden="true" class="fa fa-star"></i></span></dd></dl></div><div class="review-desc"><p>kljsdkaaksdfasdfasd</p></div></div><div class="list-item" role="listitem"><div class="review-info"><dl><dt><p>USAgod<span class="country">[]</span></p><span class="time">2019/6/26 9:55:45</span></dt><dd><span><i aria-hidden="true" class="fa fa-star"></i></span><span><i aria-hidden="true" class="fa fa-star"></i></span><span><i aria-hidden="true" class="fa fa-star"></i></span><span><i aria-hidden="true" class="fa fa-star"></i></span><span><i aria-hidden="true" class="fa fa-star"></i></span></dd></dl></div><div class="review-desc"><p>aklsjkjjjhhfaskdfasdfasfs</p></div></div><div class="list-item" role="listitem"><div class="review-info"><dl><dt><p>coocie<span class="country">[]</span></p><span class="time">2019/6/26 9:54:14</span></dt><dd><span><i aria-hidden="true" class="fa fa-star"></i></span><span><i aria-hidden="true" class="fa fa-star"></i></span><span><i aria-hidden="true" class="fa fa-star"></i></span><span><i aria-hidden="true" class="fa fa-star"></i></span><span><i aria-hidden="true" class="fa fa-star"></i></span></dd></dl></div><div class="review-desc"><p>lsdkjflaksjflkasjkfdsafasf</p></div></div><div class="list-item" role="listitem"><div class="review-info"><dl><dt><p>Glassman<span class="country">[]</span></p><span class="time">2019/6/26 9:53:48</span></dt><dd><span><i aria-hidden="true" class="fa fa-star"></i></span><span><i aria-hidden="true" class="fa fa-star"></i></span><span><i aria-hidden="true" class="fa fa-star"></i></span><span><i aria-hidden="true" class="fa fa-star"></i></span><span><i aria-hidden="true" class="fa fa-star"></i></span></dd></dl></div><div class="review-desc"><p>kasjdfkasjklfasdfasfdafas</p></div></div><div class="list-item" role="listitem"><div class="review-info"><dl><dt><p>Globalman<span class="country">[]</span></p><span class="time">2019/6/26 9:50:12</span></dt><dd><span><i aria-hidden="true" class="fa fa-star"></i></span><span><i aria-hidden="true" class="fa fa-star"></i></span><span><i aria-hidden="true" class="fa fa-star"></i></span><span><i aria-hidden="true" class="fa fa-star"></i></span><span><i aria-hidden="true" class="fa fa-star"></i></span></dd></dl></div><div class="review-desc"><p>askldfjlksjdflasjdfasdf</p></div></div></div><div class="i-amphtml-loading-container i-amphtml-fill-content amp-hidden"><div class="i-amphtml-loader">
        <div class="i-amphtml-loader-dot"></div>
        <div class="i-amphtml-loader-dot"></div>
        <div class="i-amphtml-loader-dot"></div>
      </div></div><amp-list-load-more load-more-button="" class="view-more amp-visible" style=""><button>View More</button></amp-list-load-more><amp-list-load-more load-more-loading="" class="i-amphtml-default-ui">
          <div class="i-amphtml-list-load-more-spinner"></div>
        </amp-list-load-more><amp-list-load-more load-more-failed="">unknown mistake</amp-list-load-more><amp-list-load-more load-more-end="" class="no-more">没有更多评价</amp-list-load-more></amp-list>`
**2、amp-form**
`<form class="sample-form i-amphtml-form amp-form-initial" method="post" id="myform" action-xhr="/js/ajax/appProductsReview.aspx?opt=set&amp;guid=17996095" target="_top" autocomplete="off" on="submit-success:AMP.setState({reviewState:event.response.state})" novalidate=""><dl><dt><sup>*</sup>Name</dt><dd><input type="text" name="name" required="" maxlength="50" value=""></dd></dl><dl><dt><sup>*</sup>Email</dt><dd><input type="email" name="email" required="" maxlength="50" value=""></dd></dl><dl><dt><sup>*</sup>Content</dt><dd><textarea name="content" required="" maxlength="1000"></textarea></dd></dl><div class="review-send"><input type="hidden" name="score" value="5" [value]="starValue!=null?starValue:5"><input type="submit" value="Submit" role="button" tabindex="0" on="tap:myamplist.refresh"><div submit-success=""><template type="amp-mustache"><p>{{message}}</p></template></div></div></form>`

---------------------------- Thanks! -----------------------------

**Comment by choumx** [comment]
My guess is the problem is this:

```html
<input type="submit" value="Submit" role="button" tabindex="0" on="tap:myamplist.refresh">
```
The "tap" event is triggered at the same time as form submission, which is async. Try using this instead:
```html
<form id="myform" on="submit-success:myamplist.refresh">
```

**Comment by clodisewp** [comment]
> My guess is the problem is this:
> 
> ```
> <input type="submit" value="Submit" role="button" tabindex="0" on="tap:myamplist.refresh">
> ```
> 
> The "tap" event is triggered at the same time as form submission, which is async. Try using this instead:
> 
> ```
> <form id="myform" on="submit-success:myamplist.refresh">
> ```

>>>>>Great..........Thanks!<<<<<<
