### ISSUE TITLE
Preconnect timer and BUILT event delays FCP

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#22975]
Noticed this while futzing around with IntersectionObserver instrumentation. On a test page with ~400 amp-img, the two combined take about 14% of pre-FCP script evaluation time. 

1. The `setTimeout` in preconnect results in O(N) timer installations in browser ([Install Timer](https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/performance-reference)).
2. `AmpEvents.BUILT` is dispatched O(N) times but only has one listener in `amp-fx-flying-carpet.js`.

We should batch the preconnect timer and probably remove `AmpEvents.BUILT` outright.

[1] https://github.com/ampproject/amphtml/blob/cd8ce972f9be9d36ea1574cb8347be9645b327dd/src/custom-element.js#L574-L581

[2] https://github.com/ampproject/amphtml/blob/cd8ce972f9be9d36ea1574cb8347be9645b327dd/src/service/resource.js#L350

Ran on Chrome Mac Pro 2013 with 4x CPU throttling:

![Screen Shot 2019-06-24 at 10 55 33 AM](https://user-images.githubusercontent.com/20525523/60029187-a9bfd080-966e-11e9-9c8a-d6ed33d4b951.png)

/cc @ampproject/wg-performance @ampproject/wg-runtime

**Comment by cramforce** [comment]
Great fixit bug!

**Comment by Enriqe** [comment]
I'd like to take a stab at this :-)

**Comment by jridgewell** [comment]
Stealing our fixit bugs? 😛

**Comment by Enriqe** [comment]
Is it stealing if I asked for permission first? 😛

**Comment by cramforce** [comment]
@Enriqe Are you picking up work on this?

**Comment by Enriqe** [comment]
Yes. I was planning on putting time on it this week for the fixit!
