### ISSUE TITLE
Add ad-support for adspirit adserver

### ISSUE THREAD

**Issue by janwinkler** [ampproject/amphtml#2297]
Hello,

i'm not familliar with how this works here in order to request a feature, so im just adding it as an issue: I'd like to request support for ads from adspirit adservers. According to the AMP documentation, this is what you need:

The “normal” adserver output of a non-AMP page would look like:

<ins class="asm_async_creative" style="display:inline-block; text-align:left;" data-asm-host="myhost.com" data-asm-params="pid=123456"></ins><script src="http://myhost.com/adasync.js" async type="text/javascript" language="JavaScript"></script>

So the js file for AMP should look like this:
import {checkData} from '../src/3p';

/**
  * @param {!Window} global
  * @param {!Object} data
  */
export function adsense(global, data) {
   checkData(data, ['asm-params', 'asm-host']);

   const i = document.createElement('ins');
   i.setAttribute('data-asm-params', data['asm-params']);
   i.setAttribute('data-asm-host', data['asm-host']);
   i.setAttribute('class', 'asm_async_creative');
   i.style.cssText = 'display:inline-block;text-align:left;';
   global.document.getElementById('c').appendChild(i);

   const s = document.createElement('script');
   s.src = 'https://'+data[asm-host]+'/adasync.js';
   global.document.body.appendChild(s);
}

Example AMP tag:
<amp-ad width=300 height=200
    type="adspirit"
    data-asm-params="pid=123456"
    data-asm-host="myhost.com">
</amp-ad>

**Comment by kashyapnitin** [comment]
To enable this adspirit adserver would have to contribute code & an implementation to the project - just as many other ad servers have done. You can read the 3P integration guidelines [here](https://github.com/ampproject/amphtml/blob/master/ads/integration-guide.md) and take a look at many of the other adserver implementations [here](https://github.com/ampproject/amphtml/tree/master/ads)

They would have to sign the contributing CLA & create a PR with their changes which will then be reviewed and merged.

**Comment by jasti** [comment]
The adspirit integration is available now. https://github.com/ampproject/amphtml/blob/master/ads/adspirit.md
Closing this one out.
