### ISSUE TITLE
Some accents appear when converting markdown to amp.dev docs

### ISSUE THREAD

**Issue by eduardogoncalves** [ampproject/amphtml#22970]
## What's the issue?
Some accents appear when converting markdown to amp.dev docs

this:
![image](https://user-images.githubusercontent.com/4308648/59971317-a7168b80-9547-11e9-9861-069ed94eff3a.png)

become this:
![image](https://user-images.githubusercontent.com/4308648/59971194-76355700-9545-11e9-882a-39613d099184.png)

![image](https://user-images.githubusercontent.com/4308648/59971246-36bb3a80-9546-11e9-9f8d-54ac7c8cc372.png)

## How do we reproduce the issue?
Visit some documentation pages, like:
- https://amp.dev/documentation/components/amp-user-location?format=websites
- https://amp.dev/documentation/components/amp-accordion?format=websites

## What browsers are affected?

All browsers

**Comment by neurologyphd** [comment]
Great job.###

**Comment by eduardogoncalves** [comment]
Change markdown ` ` to <code></code> on tables to prevent strange accents.

@mrjoro what about open some **GFI** to next AMP Contributor Summit, so attendees can fix docs with this problem?

**Comment by torch2424** [comment]
cc @cvializ Did you work on `amp-user-location`? The PR Referencing this says you have haha! :joy: No worries if not!

**Comment by cvializ** [comment]
ooops I did. I'll fix it, thanks for the heads up

**Comment by eduardogoncalves** [comment]
@cvializ whats wrong with my PR #22971 ?

**Comment by cvializ** [comment]
Oh thanks, I missed that. I merged yours : )

**Comment by cvializ** [comment]
Leaving open to track other components like `amp-accordion`

**Comment by eduardogoncalves** [comment]
@cvializ what about open some 'Good First Issue' to next AMP Contributor Summit, so attendees can fix docs with this problem?

**Comment by cvializ** [comment]
Thanks for the suggestion, but it might be better to take care of these as we find them so the docs don't look broken for longer than necessary

**Comment by eduardogoncalves** [comment]
ok!

**Comment by choumx** [comment]
Looks like this can be closed with #22999.
