### ISSUE TITLE
Don’t use non-matching @media values

### ISSUE THREAD

**Issue by tomayac** [ampproject/amphtml#22984]
On the Chrome team we’re [considering](https://bugs.chromium.org/p/chromium/issues/detail?id=977573) to not load resources with never-matching @media values anymore. 

AMP [uses this](https://github.com/ampproject/amphtml/blob/master/src/font-stylesheet-timeout.js#L89-L92), but it seems like just switching to "print" would work, too.

**Comment by jridgewell** [comment]
`print` would be fine.
