### ISSUE TITLE
amp-youtube - maxresdefault and sddefault are not guaranteed to exist

### ISSUE THREAD

**Issue by Polylike** [ampproject/amphtml#2298]
Hey,

dont know if it is a AMP Problem or YouTube. Embed a video via amp-youtube - ID j1K_u8u8fdk and getting this error: GET https://i.ytimg.com/vi/j1K_u8u8fdk/sddefault.jpg 404 (OK)

Just start searching and found this: https://github.com/tylerpearson/lazyYT/issues/45 
https://github.com/tmtmtm/lazyYT/commit/59a2b3e7f4b939382dbefa6906baecb4052e09d7

Cheers,
Daniel

**Comment by mkhatib** [comment]
Hey @Polylike thanks for filing this.

This is expected, what we do is actually try to load `sddefault.jpg` if that failed we fallback to `hqdefault.jpg` which should exist for all videos. Maybe we should try to suppress the 404 log and log something like 'falling back to hqdefault'. 

I am not sure about making an XHR request to get the data from YT data APIs to get the metadata for the video and check if thumbnails exist. @cramforce @dvoytenko would that be ok to do during prerendering?

**Comment by cramforce** [comment]
Nope, fast is more important than keeping the log clean :)

**Comment by jridgewell** [comment]
Maybe we can add the same `?404_is_fine` that we do with prefetch?

**Comment by cramforce** [comment]
#404_is_fine may work.

Using a query string is bad, since it actually affects the cache key.

**Comment by jridgewell** [comment]
A hash won't be included in the network panel or 404 error message.

**Comment by mkhatib** [comment]
This how it looks like in the console. Is this good enough? Or should we follow up with our own log message?

![screen shot 2016-02-29 at 5 24 30 pm](https://cloud.githubusercontent.com/assets/2647/13414724/ab05c73a-df09-11e5-9d44-94a3247fdc8f.png)

**Comment by mkhatib** [comment]
Added #404_is_fine to hint that this error message should be ignored.
