### ISSUE TITLE
Allow <style amp-custom> in <body>

### ISSUE THREAD

**Issue by machal** [ampproject/amphtml#22995]
I'm curious why this is not allowed:

```html
<body>
  <style amp-custom>
    /* My styles… */
   </style>
</body
```

Demo case: https://output.jsbin.com/posepoh/1

The AMP Validator says: 

> "The parent tag of tag 'style amp-custom' is 'body', but it can only be 'head'."

Link to the specs: https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml#stylesheets

## Why do we need it?

On my website I'm experimenting with `<link>` in `<body>` solution like Jake Archibald described it. https://jakearchibald.com/2016/link-in-body/

```html
<link rel="stylesheet" href="/site-header.css">
<header>…</header>

<link rel="stylesheet" href="/article.css">
<main>…</main>

<link rel="stylesheet" href="/comment.css">
<section class="comments">…</section>
```

From the performance and maintability point of view this is a great way of inserting styles into websites.

All current browsers support it.

The problem is when I have AMP version of the sites where I'm using it. I need two separate CSS devstacks.

So – is it possible to allow it?

**Comment by choumx** [comment]
The progressive blocking that Jake proposes in the article is not relevant to AMP because there is no blocking to begin with (no external CSS). :)

**Comment by machal** [comment]
Thanks for the answer @choumx!
 
> there is no blocking to begin with (no external CSS). :)

Yes, I know. I'have added this issue mainly from the maintability point of view. Let's say I have website using „link in body“ technique.

Then – the template has AMP version. So I need to have extra distribution for the CSS for AMP version.

My proposal is possibility to have `<style amp-custom>` in the `<body>`.

Regular template:

```html
<link rel="stylesheet" href="/site-header.css">
<header>…</header>
```

AMP template:

```html
<style amp-custom>/* site-header.css contents goes here */</style>
<header>…</header>
```

(FYI: "Link in body" is not proposal only, it works in all browsers now and you can try it here for example: https://www.vzhurudolu.cz/prirucka/amp-javascript)

**Comment by choumx** [comment]
Ah yes, combining the multiple `link[rel=stylesheet]` into a single `style[amp-custom]` would be another conversion step, but I'd say this already has to happen anyways for stylesheets in the document head. Thanks for raising this though.

**Comment by machal** [comment]
I don't think this has an easy solution. Combining multiple CSS files from `<head>` together is much easier than combining multiple CSS files from component in `<html>`.

My answer is: Why in AMP it is not possible to add  `<style amp-custom>` into the `<body>`?

@choumx Please, do not close this issue. I think this is going to be interesting topic for many web developers using "CSS in body" technique.

**Comment by choumx** [comment]
As an update, it looks like [whatwg now documents](https://html.spec.whatwg.org/multipage/semantics.html#allowed-in-the-body) "`<link>` in body" but "`<style>` in body" still appears to be undefined behavior.

> Contexts in which this element can be used:
> - Where metadata content is expected.
> - In a noscript element that is a child of a head element.

https://html.spec.whatwg.org/multipage/semantics.html#the-style-element
