### ISSUE TITLE
Amp-img not rendering inside an amp-selectors tabpanel when shown by an amp action

### ISSUE THREAD

**Issue by SimonHogstromRonbol** [ampproject/amphtml#22997]
## What's the issue?

When I have an amp-selector acting like a tab, much like in the example given on https://amp.dev/documentation/examples/style-layout/tab_panels_with_amp-selector/ images inside those tabs will be blank/not rendered when the tab panel is shown by an amp action.

it will work fine when a div with the role "tab" is pressed, but when a button with on="tap:myTabs.toggle(index=0, value=true)" or similar, the amp-img won't render.

## How do we reproduce the issue?

i've made a codepen that reproduces this issue:
https://codepen.io/sunturion/pen/QRxMoa

the code in the pen is taken directly from https://amp.dev/documentation/examples/style-layout/tab_panels_with_amp-selector/ and the images are placeholder images.

- the first example works fine, since we are using the normal tabs.
- the second example works fine if you use the tabs, but the buttons won't work.
- the last example doesn't work at all.

note that on the second example, if you use the tabs first, and then the buttons afterwards, you will still see the images rendered at the tab press.

## What browsers are affected?

ive tested this in chrome, firefox, and Edge, and it is a problem in all browsers.

## Which AMP version is affected?

i've only tested the lastest version, but i do not believe this is a new issue since we have had people on the team run into this issue before.

@aghassemi

**Comment by SimonHogstromRonbol** [comment]
also, i wanted to add that if the viewport leaves the blank, unrendered amp-img and returns, the images loads like it is supposed to.

**Comment by aghassemi** [comment]
Thanks @SimonHogstromRonbol . It is the same bug as https://github.com/ampproject/amphtml/issues/20640 and https://github.com/ampproject/amphtml/issues/9267.

See https://github.com/ampproject/amphtml/issues/9267#issuecomment-459808719 for some workarounds.

I will bump up the priority of this.

Closing as dup of https://github.com/ampproject/amphtml/issues/20640
