### ISSUE TITLE
We don't define a deprecation threshold in our deprecation guidelines

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#23019]
https://github.com/ampproject/amphtml/blob/master/spec/amp-versioning-policy.md#deprecations

Doesn't mention a deprecation threshold.

**Comment by mrjoro** [comment]
Can you explain what you mean by deprecation threshold?

**Comment by nainar** [comment]
The % of AMP pages that can at max use a feature before we consider deprecating it.

**Comment by choumx** [comment]
> The following exceptions may be implemented without a new version: Changes that affect fewer than 0.1% of crawler-accessible AMP pages.

Anything greater than this? Why is a threshold necessary?
