### ISSUE TITLE
Rhombus: Scans and manipulates DOM at runtime

### ISSUE THREAD

**Issue by abester101** [ampproject/amphtml#23020]
Hi there,

Our team is working on scoping AMP support for our product Rhombus, which helps publishers such as USA Today Sports, Rolling Stone, Variety, among other ComScore 100 publishers monetize social embeds that already live inside their articles. 

Our product relies on being able to dynamically scan the DOM for certain elements (`twitter-widget` blockquotes and divs, iframes, etc). After finding the elements, we call our servers to determine if ads should be displayed and to retrieve them if so. Then we move the elements inside a wrapper element we create, with ads above and below.

Our team's initial understanding is that none of that is possible on AMP pages, even with the new amp-script feature, but I would be interested to know if we are something we are missing or if there's some kind of workaround. We could alternatively parse the pages in advance, but would still need to be able to manipulate the DOM of the page.

Thank you!

**Comment by choumx** [comment]
I think you're right that there's no current mechanism that supports this use case. This would likely have to be implemented as a new extension, although I have some concerns about this:

> Then we move the elements inside a wrapper element we create, with ads above and below.

I'm not sure how to do this while preserving layout stability. It may have to only operate on elements outside of current viewport.

**Comment by abester101** [comment]
@choumx Thank you for your reply

Would scanning and manipulating the DOM of the entire page something that would be allowed in an amp extension, if we only operated on elements at least ~600px away from the top of the page (the amp-iframe component, for example, has to be 600px or 75% of the first viewport down).

Best,

**Comment by choumx** [comment]
My sense is that the feedback you'll receive in design review is it'll need to be out of viewport entirely, though you're free to state your case. :)

**Comment by abester101** [comment]
Got it - thank you :)
