### ISSUE TITLE
[WP] background-image: none breaks AMP

### ISSUE THREAD

**Issue by randomascii** [ampproject/amphtml#23033]
## What's the issue?

I recently discovered that this page fails to display in AMP:

https://randomascii.wordpress.com/2018/08/26/commute-challenge-2018/

More precisely, the image calendar - which is the fun part of the page since it visually summarizes the commute methods and links to the individual videos - shows up as blank. It shows fine on the desktop page.

## How do we reproduce the issue?

Visit this site (https://randomascii.wordpress.com/2018/08/26/commute-challenge-2018/) and scroll down to where it says "here's a calendar that links to all of the videos:" - there should be a grid (or a line) of 20 images (the first one is intentionally blank).

At first I thought it was the "display: inline" tag again (that's what the problem was last time, per this issue - https://github.com/ampproject/amp-wp/issues/1803) but removing those tags from the calendar images didn't help. Then I removed "background-image: none" and that fixed the issue. I have since restored the HTML.

There appears to be some sort of caching going on so it is possible that the "display: inline" tag was actually the problem and it just took a while for the fix to propagate when I removed it - I can't tell.

## What browsers are affected?

I have tested this on Chrome on my Pixel 3A Android phone.

## Which AMP version is affected?

I don't know if this is a new version and I'm not sure how to get the AMP version.

**Comment by randomascii** [comment]
Twitter discussion of the original (possibly related?) bug is here:

https://twitter.com/westonruter/status/1121409140369154048

**Comment by randomascii** [comment]
There were some caching issues which caused me to misdiagnose this, but I have now confirmed that display: inline; is the problem.  This page demonstrates the problem:

https://randomascii.wordpress.com/2018/08/26/commute-challenge-2018/

There is supposed to be a 5x4 grid of images representing a calendar of weekdays. By default the image tags contain this styling:

img style="background-image: none; padding-top: 0; padding-left: 0; display: inline; padding-right: 0; border: 0;" title="...

This causes the images to not show up at all on mobile. There is just a long strip of white (the images end up in a 20x1 vertical strip on my phone).

If I remove the display: inline tag so that I have this:

img style="background-image: none; padding-top: 0; padding-left: 0; padding-right: 0; border-width: 0;" title="

then the images show up. I have done this for 19 of the 20 images, thus preserving the bug on the last image while making the site mostly functional.

It's quite frustrating to have AMP making my blog almost useless on mobile. I never look at it on mobile so I don't know how many pages are affected or how long this has been going on for.

**Comment by westonruter** [comment]
I believe this issue would not have appeared if the version of the AMP plugin was up to date. In particular, this issue was addressed in v1.2 via https://github.com/ampproject/amp-wp/pull/2209. Nevertheless, the version of the AMP plugin on WordPress.com is still on an old v0.6.2. At the moment you can update to the current version only if you switch to the business plan, at which point the plugins are under your control.

**Comment by randomascii** [comment]
Ah - so it's a wordpress problem? Although, the original bug said "This issue did not happen in 0.7 because prior to 1.0" so how come it happens in v0.6.2?

**Comment by westonruter** [comment]
That's a good question. How is the markup being added to the post in the first place? Is it some shortcode or some other template feature?

**Comment by randomascii** [comment]
I use Windows Live Writer to write my posts - always have - so I get whatever HTML quirks that it defaults to.

**Comment by westonruter** [comment]
Please look at the code view of the editor and copy/paste the raw underlining `post_content` as saved in the database and share it here so we can try to reproduce the issue.

**Comment by westonruter** [comment]
@randomascii WordPress.com has been updated to AMP plugin 1.4+. Can you re-check to see if this is still an issue?

**Comment by randomascii** [comment]
I had enough problems with AMP that I turned it off so I can't easily do test anymore. I am glad that the fix is out there but I'll probably just leave AMP off for now.
