### ISSUE TITLE
amp-consent CMP: Iframe prompt ui is not displayed on Safari ios8.x

### ISSUE THREAD

**Issue by hrkhal** [ampproject/amphtml#23036]
In safari ios8.x the amp-consent prompt iframe is not displayed to the user however the overlay is displayed when `{overlay:true}`. 

No prompt displayed means the user cannot make a choice and is left in a state of limbo where they can scroll the article due to the bug in #22945 but cannot click any of the links due to the overlay.

You can view the bug on this [demo](https://static-metro-co-uk.s3-eu-west-1.amazonaws.com/amp/consent-ui/index.html). 

To be clear we haven't confirmed this bug on actual device as we did not have an appropriate one available. It was initially noticed in browserstack which only offers the iPhone 6/6+ on ios8.

The bug was also confirmed on multiple ios8.2 devices using the Xcode Simulator.

/cc @zhouyx @torch2424

**Comment by torch2424** [comment]
@hrkhal Thank you very much for filing this issue! 😄

**Comment by hrkhal** [comment]
@torch2424 No worries. It should be noted we also found this happening in ios7 so it may be safe to assume it's happening in all versions of ios8 and under.
