### ISSUE TITLE
Dailymotion videoid problem

### ISSUE THREAD

**Issue by nahuelange** [ampproject/amphtml#2304]
We have some embeded dailymotion videos that seems to have problems with amp-dailymotion tag.
Like this video:
http://www.dailymotion.com/embed/video/kudB5qO1NWiTwu4xnqV
We set videoid attribute to "kudB5qO1NWiTwu4xnqV" as the documentation says, but we have a validation error:
```
The attribute 'data-videoid' in tag 'amp-dailymotion' is set to the invalid value 'kudB5qO1NWiTwu4xnqV'. (see https://github.com/ampproject/amphtml/blob/master/extensions/amp-dailymotion/amp-dailymotion.md)
```

Is it an issue from the AMP plugin or something we are doing wrong?

**Comment by Meggin** [comment]
Try lowercase. Id is case sensitive.

From docs: Error thrown when the data-videoid attribute is invalid. Check
your ID to make sure letters are lowercase; the ID is case sensitive.

**Comment by Meggin** [comment]
Also, where are you seeing this id in docs-- I want to fix it :)

In these docs:
https://www.ampproject.org/docs/reference/extended/amp-dailymotion.html

Sample ID looks like this:

<amp-dailymotion
    data-videoid="x2m8jpp"
    layout="responsive"
    width="480" height="270"></amp-dailymotion>

**Comment by Gregable** [comment]
It isn't supposed to be case-sensitive. We have a fix we will start rolling out early next week.

**Comment by Lovntola** [comment]
@nahuelange ..and your video id is starting with k that means private. see [Issue 2222](https://github.com/ampproject/amphtml/issues/2222)

**Comment by nahuelange** [comment]
Hi,
Thanks for your answers, but id is case sensitive (at least for "k" prefixed videos). In this case, the lower-cased id return a 404:
http://www.dailymotion.com/embed/video/k4AoZyx8IlCSsx4RsQh
http://www.dailymotion.com/embed/video/k4aozyx8ilcssx4rsqh

When the fix will be deployed? ATM all pages with dailymotion videos can't be indexed by Google.

@Meggin : it's not a videoid from the documentation, but a videoid from a real case.

**Comment by rudygalfi** [comment]
Is this still unresolved? @Gregable can you confirm that the fix rolled out?

**Comment by Gregable** [comment]
This is fixed.
