### ISSUE TITLE
amp-script JS size restriction?

### ISSUE THREAD

**Issue by ChiangChienHui** [ampproject/amphtml#23062]
I use amp-script include third-party javascript, and i have a amp script token; I get the error below in the console of my browser;
My web site url is https://test-web.zi.media/@jfsblog/post/peqzZQ/amp?debug=true#development=1

error image(https://user-images.githubusercontent.com/50347875/60251210-afc9e180-98fa-11e9-9785-f5820d8e3fc1.png)

**Comment by choumx** [comment]
amp-script has a 150KB max total script size limit: https://github.com/ampproject/amphtml/blob/master/extensions/amp-script/amp-script.md#im-getting-a-size-exceeded-error

**Comment by ChiangChienHui** [comment]
But I use amp-script include third-party javascript , the javascript file size is 128KB, so how can i do...?

**Comment by choumx** [comment]
Is the total size of your JS 128KB?

**Comment by ChiangChienHui** [comment]
Yes is the total size of mine JS 128KB , and the web site is private, so I need your working hours, I will open web site permission with your working hours.
