### ISSUE TITLE
`element.getPlaceholder()` may return incorrect data.

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#23076]
It only looks for `placeholder` as the last child of the element but this is not correct, certain components that override `createPlaceholderCallback` may append other DOM later on making the `placeholder` not the last item. 

This means depending on when `getPlaceholder` is called, it may or may not return the placeholder.

/cc @choumx I have a fix that I will send out later as part of a new loader PR.

**Comment by jridgewell** [comment]
It's looking for a child that matches the predicate in reverse order. 😉 

Is there are name that would make this more clear?

https://github.com/ampproject/amphtml/blob/master/src/dom.js#L366-L383

**Comment by aghassemi** [comment]
Oh that explains why changing it to use scoped selector made no difference.

Name is fine, it is me being stupid and not noticing the predicate callback.
