### ISSUE TITLE
Story vertical rendering mode doesn't show animated text.

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#23070]
Story vertical rendering mode doesn't show animated text.

Example: https://www-pcgamesn-com.cdn.ampproject.org/c/s/www.pcgamesn.com/amp-stories/best-battle-royale-games.html

**Comment by gmajoulet** [comment]
Note: some publishers, like Google Stories, don't use built in story runtime animations, but rely on the `[active]` attribute to trigger the animations. Adding this `[active]` attribute to all pages would fix these.

**Comment by cramforce** [comment]
Are they using CSS animations triggered on active or what is the mechanism?

**Comment by gmajoulet** [comment]
Yes: the `<amp-story-page>` that's displayed gets an `[active]` attribute. I thought Google Stories was not using built in animations but using this attribute to trigger their custom CSS animations, but actually it turns out they don't.
I'll still send a follow up PR just in case someone uses this one day, but it didn't need to be in the cherry-pick

**Comment by cramforce** [comment]
For the CSS animations could can also make the duration be 0s with
!important in vertical mode.
