### ISSUE TITLE
amp-mustache strips off structured data tags (e.g. `meta`) and attributes e.g. `itemprop` from templates

### ISSUE THREAD

**Issue by designgrill** [ampproject/amphtml#23089]
## What's the issue?

AMP supports Structured Data [including the use of meta tags](https://github.com/ampproject/amphtml/blob/5f75efe35b734a4fcf0884d373315de60cd42df9/examples/metadata-examples/recipe-microdata.amp.html#L94) in content. However, same meta tags get stripped off when you try to get them through `amp-mustache` templates.

## How do we reproduce the issue?
Please create an `amp-mustache` template with Structured Data `meta` tags and/or `itemprop` attribute.

## What browsers are affected?
All browsers

## Which AMP version is affected?
At least 1906191709480

**Comment by choumx** [comment]
We can allow `itemprop` but `meta` is a bit more sensitive in AMP usage. Is `meta` necessary for your use case?

**Comment by designgrill** [comment]
`meta`, inside the body, is definitely something we use on our regular website for things which are difficult to express using `itemprop`. Awaiting more details from our team regarding the criticality though. Will reopen or raise a new issue in case it is critical. Thanks!
