### ISSUE TITLE
The height of a responsive amp-list does not change after the list refreshed?!!

### ISSUE THREAD

**Issue by clodisewp** [ampproject/amphtml#23087]
The problem is described in the title in the condition of manual load;

Thanks to @choumx, I got the right way to refresh the list. But the height doesn't change anyway.

**Comment by choumx** [comment]
amp-list has [specific resizing rules](https://amp.dev/documentation/components/amp-list#dynamic-resizing). Alternatively, you can add a `[height]` binding. 

Please post usage questions on StackOverflow from now on. This repository is meant for reporting bugs and feature requests.
