### ISSUE TITLE
AMP validation: The attribute '[type]' may not appear in tag 'INPUT [type=password]'.

### ISSUE THREAD

**Issue by Stefany93** [ampproject/amphtml#23082]
## What's the issue?

AMP validation error `The attribute '[type]' may not appear in tag 'INPUT [type=password]'.`

## How do we reproduce the issue?

I am creating a show / hide password button and if I set the input type to `password`, AND add the `[type]` amp-bind attribute, the AMP validator starts screaming with the above-mentioned error. If I set the input type to text, it works fine. 

Code: 
```
<form class="m3" action-xhr="https://example.com" method="post" >
        Password: <input type="password" [type]="toggleType ? 'password' : 'text'" value="password" >
</form>
```

## Which AMP version is affected?

Version 1906191709480

**Comment by choumx** [comment]
If the format of the AMP document is AMP4EMAIL, this is working as intended. We currently disallow `input[type=password]` as well as changing `input[type]` at runtime to prevent potential spam/cloaking. 

@Stefany93 Can you share the full page HTML?

**Comment by Stefany93** [comment]
Sure! https://codepen.io/Stefany93/pen/KjyryP?editors=1000 I made a button to hide / show password field. 
I hope you won't disallow it, heh. The `type` is initially `text` which is actually better user experience than being initially `password` but I was wondering if it is a bug. It is working fine. Just now `password` to `text`

**Comment by choumx** [comment]
Ok, this is just an inconsistency for the AMP format. Thanks for the report.

**Comment by Stefany93** [comment]
@choumx thank you
