### ISSUE TITLE
Allow passing htmlFormat together with url parameter

### ISSUE THREAD

**Issue by vitsuchanek** [ampproject/amphtml#23088]
We would like to use AMP validator for validation of AMP4EMAIL. That is by calling https://validator.ampproject.org/#htmlFormat=AMP4EMAIL&url=xxx. However, if a query string contains a value of 'url' parameter, parameter 'htmlFormat' is ignored.

I checked AMP validator source codes a bit so I suppose this would represent a change in /validator/webui/@polymer/webui-mainpage/webui-mainpage.html. Something like this:

```
--- a/validator/webui/@polymer/webui-mainpage/webui-mainpage.html
+++ b/validator/webui/@polymer/webui-mainpage/webui-mainpage.html
@@ -309,6 +309,9 @@
         // If #url=<url> was provided, load it, otherwise, start with the
         // minimum valid AMP document.
         else if (params.hasOwnProperty('url') && params['url']) {
+          if (params.hasOwnProperty('htmlFormat') && params['htmlFormat']) {
+            urlForm.setHtmlFormat(params['htmlFormat']);
+          }
           this.$.urlForm.setURLAndValidate(params['url']);
           // If filter=<error_category> was provided, filter error-list.
           if (params.hasOwnProperty('filter') && params['filter']) {
```

**Comment by choumx** [comment]
validator.ampproject.org is meant as an ad hoc devtool. If you'd like validation as part of your dev pipeline, use the [amphtml-validator npm package](https://www.npmjs.com/package/amphtml-validator).

**Comment by vitsuchanek** [comment]
Hi William, thanks for you feedback! But if validator.ampproject.org is meant to be just an adhoc tool, why do you support passing Base64-encoded content together with HTML format as URL GET parameters? I would expect a consistent approach when you open the validator using either of both approaches (passing encoded AMP content via GET parameters or using a URL to the AMP content). Vít
