### ISSUE TITLE
Amp audio analytics missing

### ISSUE THREAD

**Issue by deprantik** [ampproject/amphtml#23090]
There is no documentation on amp-audio analytics. Please help me find it or built it!

**Comment by zhouyx** [comment]
Hello @deprantik, thank you for opening the issue. We currently don't have analytics support for amp-audio. 
There's a GFI opened #20070, where we will be adding play/pause trigger support. Please let us know what else support are you thinking. Thank you.

**Comment by micajuine-ho** [comment]
Closed by #23317
