### ISSUE TITLE
Intent to implement: amp-fixed

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2309]
Using direct fixed positioning via CSS does not work well under iOS Safari when AMPs are embedded into other viewers.

We have a solution for simple cases, but it does not scale well (e.g. for deeply nested elements).

`amp-fixed` would do the same as our hack, but be explicit about it and can be documented.

Just like `position: fixed` it would not be allowed to contain ads.

**Comment by adelinamart** [comment]
Is this still in progress?
