### ISSUE TITLE
Duplicated ad request in amp-ad-custom extension

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#23094]
Reported by Dianomi integration: "We are seeing some problems in our own metrics system which I've been investigating. We are counting the number of requests made for our ads and the numbers are an awful lot higher than in the previous system.

I've been trying to work out why. If you load this page and look at the network tab you can see many many requests coming though, especially if you for example drag the line that resizes the main window vs developer window. It seems to generate dozens of requests.

Is there a way of us ensuring that there's just one request each time?"

To reproduce:
https://www.dianomi.com/mjs/amp/one.epl?smartad_id=5001

**Comment by dianomi-mjs** [comment]
Thanks - I presume I have to wait a while to test this for myself. Will this address the multiple requests before the layout changes?

I see 4 requests for the JSON on https://www.dianomi.com/mjs/amp/one.epl?smartad_id=5001 without resizing the window

**Comment by glevitzky** [comment]
Unfortunately, yes, you'll need to wait to test this, unless you're willing to set up a local AMP build and test against that.

>  I see 4 requests for the JSON on https://www.dianomi.com/mjs/amp/one.epl?smartad_id=5001 without resizing the window

With my fix there will only be the one request.

**Comment by lannka** [comment]
@dianomi-mjs you can use our nightly build to test it now. 

```
http://amphtml-nightly.herokuapp.com/proxy/s/www.dianomi.com/mjs/amp/one.epl?smartad_id=5001
```

Note that the link right now redirects because your page is invalid AMP (missing amp-form script). It should work after a fix. Let me know if you see problem.

**Comment by dianomi-mjs** [comment]
Hi @lannka can you tell me when we can expect the fix to be hitting production?

I've removed the form from that page for testing - still getting redirected at the moment, will try later and report back.

**Comment by dianomi-mjs** [comment]
http://amphtml-nightly.herokuapp.com/proxy/s/www.dianomi.com/mjs/amp/one.epl?smartad_id=5001 is still being redirected although the page passes the AMP validator now.

**Comment by lannka** [comment]
@dianomi-mjs I'm also experiencing issues with the nightly server. I will take a look when a got a chance.  Worst case, the change will be in canary for testing tmr.

**Comment by dianomi-mjs** [comment]
cheers @lannka, I'll try the canary release tomorrow. 
When are we looking at the fix hitting production - a week's time?

**Comment by lannka** [comment]
@dianomi-mjs the canary was out yesterday, i just verified that the issue has been fixed on your test page:
https://www.dianomi.com/mjs/amp/one.epl?smartad_id=5001

It will hit prod next Tuesday on 7/16.

**Comment by dianomi-mjs** [comment]
Thanks, looking good
