### ISSUE TITLE
🌸 Cherry-pick request for #23101 into #1906191709480 (PROD) and #1906272257090 (Canary)

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#23104]
# Cherry-pick request

| Issue | PR  | Production? | RC? | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---: | :-: | :---------: | :-: | :-----------: |
| #23101 | #23103 | **YES** | **YES** | #1906191709480 |
| #23101 | #23103 | **NO** | **YES** | #1906272257090 |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

Breaks paywall entitlement fetches in some cases.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

Some viewers allow early entitlement resolution, but they are blocked by the fetch activation restrictions.

| Users affected | Impact |
| -------------- | ------ |
| - | Paywall may be showing up unexpectedly |

## Root Causes

1. #23101

### Things that went wrong

-

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by mrjoro** [comment]
Approved for cherry pick into prod and RC.
