### ISSUE TITLE
Utilizing Google AMP Cache vs. Third-Party CDN?

### ISSUE THREAD

**Issue by kwsutton** [ampproject/amphtml#2310]
Hi All,

First-time poster here. I was hoping to develop a deeper understanding of how specifically AMP utilizes its caching feature, and moreover, how a publisher could go about utilizing their own CDN for caching if they so desired. I read the following on the AMP Project website, but don't entirely understand how this implementation would work: "AMP pages can be served from either a publisher's website or the AMP Cache."

So, a few questions:
1. Are pages cached using the AMP Cache "by default," or is a certain specification required for this to occur?
2. If a publisher wanted to utilize their own CDN for caching (e.g., Akamai), how would they go about specifying this in their AMP implementation?

Thanks in advance,
Kyle

**Comment by cramforce** [comment]
The choice of cache is a decision of the platform that is sending the user (Say Twitter or Google Search). These AMP caches can deliver all AMP documents. Whether the publisher decides to use a CDN for delivery is independent of that.

**Comment by jridgewell** [comment]
> Are pages cached using the AMP Cache "by default,"

If they pass validation, they are cached.

**Comment by cramforce** [comment]
If they pass validation and someone requests them through the cache.

**Comment by khilnani** [comment]
Would the AMP CDN honor  headers around caching? Cache-Control, Surrogate-Control, Expires, Age etc. (example, https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching?hl=en)

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please verify first whether the feature proposal is still relevant.

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
