### ISSUE TITLE
Add WAI-ARIA to amp-social-share extension

### ISSUE THREAD

**Issue by ayumihamsaki** [ampproject/amphtml#23118]
Testing the `amp-social-share` extension, it appears that the WAI-ARIA is incomplete and you are missing some important coding.

Currently it contains: 

- tabindex="0"
- role="button"

But it doesn't contain:

- aria-pressed="false"
- aria-pressed="true"

Say for example a blind person clicks on the button, the Screen Reader will not be able to confirm and tell them that they have clicked the button. They may end up just repetitively clicking on the button waiting for confirmation.

Please add the extra coding in via javascript to update accordingly to the Users request.

Thanks.

**Comment by aghassemi** [comment]
Hi @ayumihamsaki ,

`aria-pressed` is only applicable for toggle buttons. Button and links that perform an action such as social share should not have those attributes.

**Comment by ayumihamsaki** [comment]
ok thanks.
