### ISSUE TITLE
Deflake "Rendering of one ad should create an iframe loaded"

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#2311]
Chromium 45.0.2454 (Ubuntu 0.0.0) Rendering of one ad should create an iframe loaded FAILED
    Error: Timeout waiting for 3p JS to load.
        at poll (/tmp/b3115e4eee484a1402cc5a855a7aacfd.browserify:72832:18 <- /home/travis/build/ampproject/amphtml/testing/iframe.js:274:17)

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
