### ISSUE TITLE
<amp-auto-ads>: unable to fulfill ad strategy (since Friday)

### ISSUE THREAD

**Issue by ivanionut** [ampproject/amphtml#23126]
Hi,
<amp-auto-ads> no longer works on (all pages) my website since Friday.

I activated debugging (#development=1) and in the console I found:
`
No placements in config
log.js:184 unable to fulfill ad strategy
`

Some pages of my site:

https://www.petyoo.it/blog/cani/omega-6.amp
https://www.petyoo.it/blog/cani/rimedi-casalinghi-prurito-allergie.amp
https://www.petyoo.it/blog/cani/5-oli-essenziali-allergie-canine.amp

Etc

is this a problem like this?

https://github.com/ampproject/amphtml/issues/15338

**Comment by ivanionut** [comment]
@choumx any news? Thanks! 👍

**Comment by lannka** [comment]
dup with #23131
