### ISSUE TITLE
amp-selector: Lazy-loading hidden resources

### ISSUE THREAD

**Issue by virgiltu** [ampproject/amphtml#23120]
So i realized that I can make a tab system using the  amp-selector component. But what I am looking to do is to have a tab with 5 tabs that are lazy loaded. I do not want to load all the tabs at once since they will all have a lot of pictures and information. Is that something we have or can we get that.

**Comment by choumx** [comment]
AMP should do this automatically e.g. `amp-img` that are hidden won't be loaded until they are visible.

If you're seeing otherwise, can you share a sample page?

**Comment by virgiltu** [comment]
Yep so I use that, but I wanted to lazy load the entire tab. I guess since it will be products, there won’t be much text.

**Comment by choumx** [comment]
You could do that by using an `amp-list` to wrap the contents of each hidden tab.

**Comment by choumx** [comment]
Closing this since there are ways to accomplish the use case. Thanks for chatting!
