### ISSUE TITLE
rel="preload" does not support fonts in stylesheet

### ISSUE THREAD

**Issue by anuragphadke** [ampproject/amphtml#23123]
I am using Google Fonts to load Open Sans family of fonts. 

## What's the issue?
```
<link href="https://fonts.googleapis.com/css?family=Muli|Open+Sans:400,700&amp;display=swap" rel="preload"/>
```
rel="preload" does not load the font.

```
<link href="https://fonts.googleapis.com/css?family=Muli|Open+Sans:400,700&amp;display=swap" rel="stylesheet"/>
```
the above line loads the font. 
However, this affects PageSpeedInsights score with the message "Eliminate render blocking CSS"

## How do we reproduce the issue?

Gist: https://gist.github.com/anuragphadke/a45d4bbc64371b3604e24cfa7bd28fe0
## What browsers are affected?

All browsers? Some specific browser? What device type?

## Which AMP version is affected?

Affected AMP version: 1906282130140

**Comment by choumx** [comment]
This isn't AMP specific. `link[rel=preload]` is a supplementary browser hint and doesn't replace `link[rel=stylesheet]` for your font. Use [font-display](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display) to reduce render-blocking time.

**Comment by anuragphadke** [comment]
@choumx fair point, however, 
```
<link href="https://fonts.googleapis.com/css?family=Muli|Open+Sans:400,700&amp;display=swap" rel="preload"/>
```
doesn't load the font at all. Shouldn't the above value load + render the font eventually?

**Comment by kristoferbaxter** [comment]
@anuragphadke Unfortunately not. Here's an article describing the functionality of `rel=preload`.

https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

Preload doesn't indicate to the user-agent the resource should be leveraged, just requested.
