### ISSUE TITLE
Possible to validate with task?

### ISSUE THREAD

**Issue by corysimmons** [ampproject/amphtml#2313]
It'd be nice if there was an npm cli for validating amp pages as a pre-commit hook or something. I'd hate to have to check console all the time or risk accidentally committing broken amp. :X

**Comment by jridgewell** [comment]
Have you read [Building a command-line AMP Validator](https://github.com/ampproject/amphtml/blob/master/validator/docs/building_a_command_line_amp_validator_for_mac_os_x.md) yet? :wink:

**Comment by corysimmons** [comment]
Welp, if this does what the title says it does then I think we're done here. :dancer:
