### ISSUE TITLE
AdSense amp-auto-ads stopped working

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#23131]
Reported by an AdSense auto ads user:

> A similar event happened a year ago or so -- Adsense Auto Ads stopped displaying. I attached an image that shows where the code is getting hung up. The Auto Ads stopped showing Friday mid morning EST.  https://www.navycs.com/militarytime-amp.html

**Comment by lannka** [comment]
The first look is the response does not contain `placements` object, meaning no ads are returned from AdSense server. So it might be an AdSense server side regression or a mis-configuration.

```js
{  
   "producerVersion":"20190626_060350",
   "attributes":{  
      "data-tag-origin":"ampa",
      "data-package":"3075533375",
      "data-experiment-id":"719471003"
   },
   "optInStatus":[  
      2,
      1
   ],
   "adConstraints":{  
      "initialMinSpacing":"1vp",
      "subsequentMinSpacing":[  
         {  
            "adCount":3,
            "spacing":"2vp"
         },
         {  
            "adCount":6,
            "spacing":"3vp"
         }
      ],
      "maxAdCount":8
   }
}
```


Then also found that there are recent code changes in amp-auto-ads extension: #22956

**Comment by lannka** [comment]
Then also found that there are recent code changes in amp-auto-ads extension: #22818 . This change entered production on 6/25, which does not align with the timeline here (6/28).

/cc @aishwaryavora

**Comment by lannka** [comment]
Another AdSense customer experienced the same issue and reported on AdSense forum: https://support.google.com/adsense/thread/8944708?msgid=8944708

Quote from the previous reporter: 
> All other modes of AdSense ad delivery on my site, including non-AMP auto ads, are working as advertised.

**Comment by ivanionut** [comment]
Hi @lannka 
yes, I reported the problem on the adsense forum...

but also here: https://github.com/ampproject/amphtml/issues/23126

**Comment by lannka** [comment]
The reporter of the issue said the traffic is back. @ivanionut can you confirm?

**Comment by ivanionut** [comment]
Hi @lannka
