### ISSUE TITLE
amp-bind: Add support for Math.pow

### ISSUE THREAD

**Issue by dbarcosb** [ampproject/amphtml#23133]
This is a request to add [pow() method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/pow) to the [whitelisted Math JS functions](https://amp.dev/documentation/components/amp-bind#white-listed-functions).

Currently '^' or '**' are not working to perform the power of two numbers. If there is a workaround for this, happy to know about it. Thank you!

**Comment by samouri** [comment]
@choumx, are you currently working on this? If not, would you mind if I took a whack at it?

**Comment by choumx** [comment]
@samouri Go for it. :)
