### ISSUE TITLE
amp-list performance

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#23134]
a recent change to `amp-list` has improved the performance of a look-up significantly. Previously, page loads were very slow for a list with 10,000 items. Now the lookup has very little delay.

**Comment by choumx** [comment]
Glad to hear it! Does your sample page use amp-bind? If so, it may be #22938.

**Comment by jaygray0919** [comment]
just plain `amp-list`. In the following case we fire 10,000 individual "gets".

`<amp-list class="m1" width="auto" height="50" layout="fixed-height" src="https://m.wikidata.org/wiki/Special:EntityData/Q35120.json" items="entities.Q35120.sitelinks.eswiki" single-item="url"><template type="amp-mustache"><p><span>_result_</span><span>{{url}}</span></p></template><div fallback><p>Missing URL</p></div></amp-list>`

When using a single `amp-list` with 10,000 items, its even faster (no loading symbols on page-load).

**Comment by choumx** [comment]
What version of AMP are you using? It will be printed in dev console.

**Comment by jaygray0919** [comment]
version `1906282130140`

**Comment by choumx** [comment]
Hm, I'm not sure which change is causing this apparent performance boost in 1906282130140.

Anyways, thanks for the feedback and let us know if it changes in the future.
