### ISSUE TITLE
488 Errors in Search Console

### ISSUE THREAD

**Issue by ThomasKujawa** [ampproject/amphtml#2314]
perhaps http://go.shr.lc/1UpkHCd / http://go.shr.lc/1UplB1H / 

boilerplate (js enabled) is missing

how can i fix it?

I use https://github.com/automattic/amp-wp and https://wordpress.org/plugins/glue-for-yoast-seo-amp/

**Comment by rudygalfi** [comment]
This indicates missing https://github.com/ampproject/amphtml/blob/master/spec/amp-boilerplate.md. The AMP plugin from WordPress should be including this, so it might be the two plug-ins interacting with each other in an unexpected way. You may want to raise this in https://wordpress.org/plugins/glue-for-yoast-seo-amp/.

There's a community at https://productforums.google.com/forum/#!topicsearchin/webmasters/category$3Aaccelerated-mobile-pages-amp%7Csort:relevance%7Cspell:false that can help with Search Console errors.

**Comment by ThomasKujawa** [comment]
Thank you.
