### ISSUE TITLE
Do not strip the "format-detection" meta tag in the AMP Cache transformations

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#23155]
## Describe the new feature or change to an existing feature you'd like to see

Whitelist the "format-detection" meta tag so it is not removed by AMP caches.

## Additional context

Code numbers such as video games cheat codes can be interpreted as phone numbers by iOS. Numbers get different native iOS styles and unintended behaviors (like triggering the phone app on tap).

Using the `<meta name="format-detection" content="telephone=no">` to fix this sounds like the way to go, however this meta tag [is not allow listed](https://github.com/ampproject/amphtml/blob/master/spec/amp-cache-modifications.md#remove-non-whitelisted-meta-tags) and is removed when ingested by AMP caches.

Example: https://www.pcgamesn.com/amp-stories/fortnite-creative.html meta tag works on the origin but not on the Google Cache, where the Fortnite code triggers the phone app

**Comment by Gregable** [comment]
The change is now in the Google AMP Cache, and should be released soon.
