### ISSUE TITLE
`scroll-behavior:smooth` on `html` behaves badly in AMP

### ISSUE THREAD

**Issue by yunabe** [ampproject/amphtml#23164]
## What's the issue?

[`scroll-behavior: smooth`](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior) on `<html>` is allowed in AMP now. But it causes unnecessary scroll animations when scroll positions are adjusted automatically in AMP.

`scroll-behavior: smooth` on `<html>` should be disallowed in AMP.

## How do we reproduce the issue?

1. Open an AMP page with `scroll-behavior: smooth`
   e.g. https://www.google.com/search?hl=en&gl=us&q=michelle+knight+site%3Awww.biography.com
2. Scroll down the page.
3. **Bug 1:** When contents are injected before the current view, scroll positions are automatically adjusted by AMP. But there are unnecessary animations.
    https://www.youtube.com/watch?v=KagvKCpATAo&t=3s
4. Go back to Google search and reload it.
5. Revisit the same page.
6. **Bug 2:** AMP restores the previous scroll position. Due to `scroll-behavior: smooth` in the page, this causes unnecessary scroll animation.
    https://www.youtube.com/watch?v=KagvKCpATAo&t=17s

Also, there are existing libraries to implement [animated scroll in this repository](https://github.com/ampproject/amphtml/blob/45aa1e62c0b6089d0ff2172171ce2da934387cbb/src/service/viewport/viewport-impl.js#L569).

To avoid unexpected interactions with existing features, I think we want to disable `scroll-behavior: smooth` in AMP.

## What browsers are affected?

Android Chrome. iOS Safari does not support `scroll-behavior:smooth` now.

## Which AMP version is affected?

All

**Comment by sparhami** [comment]
`<amp-base-carousel>` handles this when restoring scroll position. It disables smooth scrolling using a function here:

https://github.com/ampproject/amphtml/blob/c3940a0a90663270e8c244d0e82fb3d67958ad34/extensions/amp-base-carousel/0.1/carousel.js#L54-L66

Perhaps the base runtime can do the same thing when restoring scroll position. If we want to work around it, things that "animate" scroll need to avoid animating when using `scroll-behavior`. We did want to move over to native `scroll-behavior` (e.g. for `scrollTo` action), but have not yet as the feature is not present in Safari.
