### ISSUE TITLE
Alexa code don't work on AMP cache url domain

### ISSUE THREAD

**Issue by seomaz** [ampproject/amphtml#23169]
Hi,

The alexa code for this domain: cibercuba.com is:

`<amp-analytics type="alexametrics">
<script type="application/json"> {"vars": { "atrk_acct": "1BFEn1QolK10T3", "domain": "cibercuba.com" }}</script>
</amp-analytics>`

This code work fine (and stats are equal than other analytics) when the user navigate on the canonical domain (cibercuba.com), but when the user enter to de amp document via AMP cache url (https://www-cibercuba-com.cdn.ampproject.org/c/s/www.cibercuba.com) the alexa code don't work.

We using the amp cache url to post on social media, all this traffic its outside the alexa counter

**Comment by choumx** [comment]
This FR is a bit too vague to be actionable. Do you have a link to a reference URL for the Alexa feature you're trying to embed?
