### ISSUE TITLE
AMP4EMAIL: Attribute [src] not appearing in AMP-IMG

### ISSUE THREAD

**Issue by mont23** [ampproject/amphtml#23165]
## What's the issue?

I am following the AMP-BIND tutorial and getting this error: The attribute '[src]' may not appear in tag 'AMP-IMG (AMP4EMAIL)'

## How do we reproduce the issue?
When following the amp-bind tutorial https://amp.dev/documentation/components/amp-bind?format=email in the "A slightly more complex example" it give me the error of [src] not being supported.

```
<!doctype html>
<html ⚡4email>
<head>
  <meta charset="utf-8">
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>
  <style amp4email-boilerplate>body{visibility:hidden}</style>
</head>
<body>
  <!-- Store complex nested JSON data in <amp-state> elements. -->
<amp-state id="myAnimals">
  <script type="application/json">
    {
      "tiger": {
        "imageUrl": "https://raw.githubusercontent.com/ampproject/docs/future/pages/static/img/docs/tutorials/firstemail/photo_by_nick_karvounis.jpg"
      },
      "cat": {
        "imageUrl": "https://raw.githubusercontent.com/ampproject/docs/future/pages/static/img/docs/tutorials/firstemail/photo_by_caleb_woods.jpg"
      }
    }
  </script>
</amp-state>

<p [text]="'This is a ' + currentAnimal + '.'">This is a tiger.</p>


<!-- Change an image's src with the [src] binding. -->
<amp-img width="300" height="200" src="https://raw.githubusercontent.com/ampproject/docs/future/pages/static/img/docs/tutorials/firstemail/photo_by_nick_karvounis.jpg"
    [src]="myAnimals[currentAnimal].imageUrl">
</amp-img>

<button on="tap:AMP.setState({currentAnimal: 'cat'})">Set to Cat</button>
</body>
</html>
```

Output error in playground : _The attribute '[src]' may not appear in tag 'AMP-IMG (AMP4EMAIL)'._

## Which AMP version is affected?
Email playground
<script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>

**Comment by choumx** [comment]
This is an intentional difference between the AMP4EMAIL and AMP formats. We should add some language to the amp-bind documentation about the format differences.

/cc @fstanis

**Comment by fstanis** [comment]
@CrystalOnScript can we put that section behind a "format filter"?

**Comment by fstanis** [comment]
Closing in favor of ampproject/amp.dev#2745 which tracks the issues with component docs.
