### ISSUE TITLE
amp-bind: Initial amp-state with falsy value is not recognized

### ISSUE THREAD

**Issue by westonruter** [ampproject/amphtml#23189]
Given the following state:

```html
<amp-state id="count">
	<script type="application/json">0</script>
</amp-state>
```

Doing `AMP.printState()` yields an empty object:

![image](https://user-images.githubusercontent.com/134745/60764417-0ee7ce80-a03e-11e9-9859-0cfe5e5c08d7.png)

This also causes a warning to be raised with the following code:

```html
<input [value]="count" type="number" value="0" readonly>
```

Since the `count` state is `null`, a warning is issued:

> Default value (0) does not match first result (null) for <INPUT [value]="count">. We recommend writing expressions with matching default values, but this can be safely ignored if intentional.

If the value is changed from `0` to `1` then it is recognized:

![image](https://user-images.githubusercontent.com/134745/60764427-76058300-a03e-11e9-8c88-0087113fb382.png)

And there is no corresponding warning.

So there appears to be a problem with parsing the JSON. Perhaps a parsed value of `0` is incorrectly being interpreted as a parse failure?

Tested in AMP v1906282130140 on Chrome 75.

**Comment by westonruter** [comment]
Actually, other falsy values get ignored as well:

```html
<amp-state id="zero">
	<script type="application/json">0</script>
</amp-state>
<amp-state id="untrue">
	<script type="application/json">false</script>
</amp-state>
<amp-state id="emptyString">
	<script type="application/json">""</script>
</amp-state>
```

![image](https://user-images.githubusercontent.com/134745/60765449-63477a00-a04f-11e9-9d5b-3a1621f38aa4.png)

**Comment by choumx** [comment]
Thanks for the detailed report. I'll tackle this in the fix-it sprint coming up.
