### ISSUE TITLE
amp-subscriptions has no way to print user information like amp-access without a dialog

### ISSUE THREAD

**Issue by aferrandini** [ampproject/amphtml#23181]
## amp-subscriptions has no way to print user information like amp-access without a dialog

When `amp-subscriptions` is implemented and you get logged in and receive some user informacion in the payload, there is no way to print some information received in the payload with a mustache template in the web without a dialog.

**Payload received:**
```json
{
  "granted": true,
  "grantReason": "SUBSCRIBER",
  "data": {
    "message": "Token validated",
    "loggedIn": true,
    "firstName": "Firsname",
    "lastName": "Lastname",
    "nickname": "nickname"
  }
}
```

**AMP html implemented:**
```html
<template type="amp-mustache" subscriptions-display="data.loggedIn">
  <div>Welcome {{firstName}}!</div>
</template>
```

`data.fisrtName` was used also to try print the data but it does not work too.

## How do we reproduce the issue?

1. Implement `amp-subscriptions`
2. Login as a user
3. Receive a payload with extra user information
4. Try to print some information like the user name without a dialog using mustache

## What browsers are affected?

All browsers are affected

## Which AMP version is affected?

This issue or missing feature affects to all the `amp-subscription` versions

## Related questions in StackOverflow

There is a question about that in StackOverflow without any response or solution.

https://stackoverflow.com/questions/55619265/getting-amp-mustache-templates-to-render-without-using-dialogs-after-amp-subsc

**Comment by jpettitt** [comment]
We don't recommend doing this via `amp-subscriptions` `data` values.  With `amp-subscriptions` the data object will not be present when a secondary platform (eg `amp-subscriptions-google`) returns entitlements.

If you use `amp-list` and call the same endpoint the value will be available to `amp-list` templates and only one network call will be made as fetched resources are cached for the life of the page.  

Note that a user logged in via `amp-subscriptions-google` may not have a publisher cookie so you might not be able to return useful data.

**Comment by aferrandini** [comment]
@jpettitt thank you for your answer.
We are trying with `amp-list` component fetching the same endpoint but we see at network profiler that both requests are happening been sent to our servers.
In fact, it has sense because the `amp-list` request must use `credentials` in order to get the user data and seems that in this case it isn't cached.

Here you can see how we are implementing `amp-list` and a network profiler screenshot:

```html
...
<section subscriptions-actions subscriptions-display="data.loggedIn" class="checkout-section">
  <header>
    <amp-list items="data.userInfo" credentials="include" width="360" height="100" binding="no" layout="responsive" src="https://<authentication host>/auth/token/validate">
      <template type="amp-mustache">
        <h3>Welcome {{firstName}}</h3>
      </template>
    </amp-list>
  </header>
</section>
...
```

**Screenshot with two requests**
![Screenshot 2019-07-11 at 11 00 59](https://user-images.githubusercontent.com/196210/61037362-34246600-a3cb-11e9-918c-646fe796d501.png)

**Comment by jpettitt** [comment]
Hmm, that makes sense.  My concern about adding this to `amp-subscriptions` is that it will not work as expected if a secondary authorizer (eg `amp-subscriptions-google`) is used.   Specifically if the user has a linked account it's likely the `amp-subscriptions-google` entitlement will arrive first and the data object may not be available as expected.

The secondary issue is page jump.  `amp-list` has extensive logic to prevent page re-layout in the viewport, this is one of the fundamental design principles of AMP.  If we implement a non-dialog option in `amp-subscriptions` we'll end up having to replicate much of the `amp-list` logic.

Is the double network hit a problem for you?

**Comment by jpettitt** [comment]
cc @dvoytenko

**Comment by aferrandini** [comment]
First of all, thanks for the answer @jpettitt 

For us, making two calls it's not exactly a problem, but we have to think that we're handling a huge AMP traffic in our sites (~25 online medias and some online magazines). In this case, doubling the call will change our auth service systems requirements and this makes us to almost double the scale of the system of our service just to handle this two calls.

About the case of using other provider, probably this won’t be useful at all, but we can explain in the documentation how it should be use with a custom provider and with Google provider.

**Comment by jpettitt** [comment]
If you set `Cache-control: private, max-age=2` on your entitlement response that should solve the double request.  Also you have "disable cache" checked on your developer tools window which won't help :-)

**Comment by aferrandini** [comment]
Thank you @jpettitt we're going to try the header `Cache-Control`.
