### ISSUE TITLE
amp-fit-text can truncate the lower portions of some fonts

### ISSUE THREAD

**Issue by IanDoone** [ampproject/amphtml#23185]
## What's the issue?

The amp-fit-text component is capable of truncating the lower portions of some fonts.

**Note:** this could be patched by adding an option to the component to preserve line height instead of setting it to 1.15em, as that line height is why that part of the text is below the element height.

## How do we reproduce the issue?

[JSBin test page](https://output.jsbin.com/kequvizigu)

1. Set an amp-fit-text component to fixed height, 28px.
2. Set the max-font-size to 35px.
3. Set the font to Segoe UI.
4. Insert text containing a lowercase "g".

## What browsers are affected?

All tested browsers and devices.

## Which AMP version is affected?

1906282130140

**Comment by nakigoe** [comment]
The same is with text shadows. They are truncated.

maybe allow h1 inside `<apm-fit-text>`h1`</amp-fit-text>` to have padding? 

For some reason h1 inside amp-fit-text disappears completely, so the current structure is 
`<h1><amp-fit-text>` Title `</amp-fit-text></h1>`

at least allow some text overflow in options

![nakigoe](https://nakigoe.github.io/_IMG/icon.png)
<h1><a href="https://nakigoe.github.io/articles/ask.html">nakigoe.github.io/articles/ask.html</a></h1>

**Comment by brianpetro** [comment]
Bump: Fix or explanation?

**Comment by brianpetro** [comment]
This really needs to be fixed or documented. 

Adding text shouldn't be a chore.

CSS alone can't fix this. An additional HTML element has to be added.

For example, set the line-height of an element inside amp-fit-text:

`<amp-fit-text layout="responsive" width="900" height="75"><span style="line-height:1.33em;">gggjjjpppqqqyyy</span></amp-fit-text>`
