### ISSUE TITLE
New release for NPM amphtml-validator

### ISSUE THREAD

**Issue by saitho** [ampproject/amphtml#23190]
Hi there,

I'm using the NPM package "amphtml-validator" to ensure the generated CSS is valid.
The package however is over a year old. Thus it is reporting that the CSS is valid even though it is not with the current "live" validator of AMP.
Can you put out a new release for that? :)

Thanks.

**Comment by choumx** [comment]
Can you share an example of CSS that's affected by this bug?

**Comment by saitho** [comment]
media queries

Live validator says:
> The attribute 'media' may not appear in tag 'style amp-custom'. (see https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml#stylesheets)

The validator via NPM package does not report that.

**Comment by Gregable** [comment]
Are you passing in a local validator rules file? Otherwise, the NPM pacakage autoupdates the validator rules by fetching them from https://cdn.ampproject.org/v0/validator.js, making the package evergreen.
