### ISSUE TITLE
System layer missing from ads in desktop mode

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amphtml#23217]
Desktop:

![Screenshot 2019-07-09 at 14 20 57 (1)](https://user-images.githubusercontent.com/51244/60891573-77f55f00-a255-11e9-955a-ad897a3e1868.png)

Mobile:

![plentifun com_how-to-make-bubbles-with-glycerin(Pixel 2)](https://user-images.githubusercontent.com/51244/60891631-965b5a80-a255-11e9-82d3-042e414fc46b.png)

URL is https://plentifun.com/how-to-make-bubbles-with-glycerin

/cc @calebcordry

**Comment by Enriqe** [comment]
Thanks for triaging @cvializ.

@calebcordry can confirm, but the fact the progress bar is missing while an ad is playing is WAI.

The only issue I see here is that the "Ad" badge isn't visible due to the white background of the ad page. @hongwei1990 might have an opinion on what to do here.

**Comment by calebcordry** [comment]
I agree with @Enriqe. This works on mobile because there is the gradient on top so you can still see the ad badge. This gradient doesn't exist on the desktop view. @hongwei1990 Should we give this badge some sort of outline or something for this case?

**Comment by gmajoulet** [comment]
If that helps, here's the `text-shadow` we usually set on white text that could potentially be displayed against a white background: https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/1.0/amp-story.css#L973
We usually try to combine it with a small gradient though.
