### ISSUE TITLE
Improve hover menu experience via diagonal hover surface area

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#23222]
E.g. a submenu where when you hover, the submenu appears, and you have to move your mouse exactly horizontally sideways to get onto the submenu, then vertically to make your selection. If you go on a diagonal the submenu disappears. 

A better solution suggested by both @alanorozco and @alankent is that once the submenu appears draw diagonal lines from the current menu item bounding box up to the bounding box of the submenu and if the mouse stays in that region, keep the submenu open. Then the mouse can move in a straight line from the current point on a menu item to the submenu item without it disappearing, no matter what it goes over.

@alanorozco is this possible to take on as a fixit item? Would help #12619 a lot.

**Comment by alankent** [comment]
Clearly this is a good idea for at least the Alan's in this world, right @alanorozco? 

For UX advice on some of the issues please see https://baymard.com/blog/dropdown-menu-flickering-issue. There is also "diagonal mouse movement" advice here https://www.nngroup.com/articles/mega-menus-work-well/, including hover recommendations.
