### ISSUE TITLE
Uncaught (in promise) Error: CANCELLED

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#23226]
## What's the issue?

Error when swiping between articles produces `Uncaught (in promise) Error: CANCELLED`

## How do we reproduce the issue?

1. Opt into Canary
2. Open JavaScript console
3. Go to Google search for NBA
4. Select an article
5. Begin swiping between articles

## What browsers are affected?

macOSX Chrome Version 75.0.3770.100
Not reproducible in FireFox due to separate issue.

## Which AMP version is affected?
Canary: 1907022322580
![uncaught_promise_cancelled](https://user-images.githubusercontent.com/48487406/60910296-453b6e80-a235-11e9-9fd4-15229a620756.gif)

**Comment by zhouyx** [comment]
I do see this error. Comes from `AmpA4A.checkStillCurrent()`. Looks like an expected issue where the promise chain got cancelled due to user swipe away. 
cc @ampproject/wg-ads

**Comment by zhouyx** [comment]
close as expected error.
