### ISSUE TITLE
amp-auto-ads & Configuration Spec

### ISSUE THREAD

**Issue by ivanionut** [ampproject/amphtml#23225]
Hi,
I had [problems with amp-auto-ads](https://github.com/ampproject/amphtml/issues/23126) and would like to implement the amp-auto-ads configuration: https://amp.dev/documentation/components/amp-auto-ads#example-configuration

I didn't understand where I need to enter the json configuration code. Directly on the page _(head)_ like this?

```HTML
<!doctype html>
<html ⚡>
<head>
 <meta charset="utf-8">
 
<script type="application/ld+json"> 
{
  "placements": [
    {
      "anchor": {
        "selector": "DIV#contentselector",
        "index": 2,
        "sub": {
          "selector": "P.paragraph",
          "all": true,
        },
      },
      "pos": 4,
      "type": 1,
      "style": {
        "top_m": 5,
        "bot_m": 10,
      },
    },
  ]
}
</script>

</head>

<!--- etc. --->
```

Thanks,
Ivan

**Comment by ivanionut** [comment]
Hi @lannka 
do you have any idea how to solve this problem?

**Comment by grantlee75** [comment]
Are there any updates related to this request?
