### ISSUE TITLE
Error parsing json encoded files

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#23238]
This error occurs when we use `--pseudo_names` flag with `gulp dist`. Might possibly be a race condition because `--pseudo_names` has a different code path in CC or because it is a bit slower.

This is currently mitigated by using `MAX_PARALLEL_CLOSURE_INVOCATIONS = 1` in `compile.js`

**Comment by rsimha** [comment]
Ran into this for single pass (which uses `--pseudo_names` and tried solving it in #22040, but hit some issues. Will investigate a fix.

**Comment by rsimha** [comment]
This is because of https://github.com/google/closure-compiler-npm/issues/9. A good workaround for AMP is to use `--pseudo_names` only for local debugging, which will allow us to increase closure concurrency on Travis.

**Comment by rsimha** [comment]
This has popped up again in a different local dev scenario. Let's just disable parallelism for local dev.
