### ISSUE TITLE
AMP validation error: The attribute 'height' may not appear in tag 'symbol'.

### ISSUE THREAD

**Issue by kmturley** [ampproject/amphtml#23259]
## What's the issue?

AMP says it supports SVG in the spec:
https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml#svg

But when using an SVG symbol for example:
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol

It throws an error:
```
AMP validation had errors:
The attribute 'height' may not appear in tag 'symbol'.
The attribute 'width' may not appear in tag 'symbol'.
```

## How do we reproduce the issue?

Example here:
https://jsbin.com/mukisaf/edit?html,console,output

Steps to reproduce:
1. Create a default AMP page
2. Copy in the example SVG from https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol
3. Run the page using the development validator url param: #development=1

## What browsers are affected?

All browsers

## Which AMP version is affected?

v0.1

**Comment by choumx** [comment]
@ampproject/wg-caching

**Comment by Gregable** [comment]
It looks like `width` and `height` were added to that document in October 2018:

- https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol$revision/1371828
- https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol$revision/1422709

They should be added to the AMP spec as well.

**Comment by Gregable** [comment]
Fixed
