### ISSUE TITLE
I2I: <amp-embed type="insticator">

### ISSUE THREAD

**Issue by vladdeev** [ampproject/amphtml#23257]
## What we want to achieve 
We’d like to add a new type to the `<amp-embed>` tag. 
The desired name for the type is insticator: `<amp-embed type="insticator">`

### Expected Behavior
When implemented in AMP articles or sidebars this `<amp-embed type="insticator">` would embed our content enhancement unit. The unit is white labeled and serves quizzes and polls to better engage a publishers audience. In the future more content types will be added.

### Technical Details
We’ll ingest a configuration option named "data-embed-id" which we’ll use to serve the appropriate unique content unit.

### Monetization
Our non-AMP unit utilizes advertisements above and below our content to monetize. We’d like to use an <amp-ad> tag in this implementation in order to accomplish this.

### Desired Tag
`<amp-embed type="insticator" data-embed-id="7atc7d4c-e5e2-4b1e-bfc7-4775790decb7">`
`</amp-embed>`

### Visual Output
![image](https://user-images.githubusercontent.com/20981830/60978912-d70fae00-a2ff-11e9-8412-bc06fc46009c.png)

сс @lannka

**Comment by lannka** [comment]
@vladdeev thanks for coming up with the alternative solution.

This looks good to me. One thing to keep in mind is that you will need to [resize](https://github.com/ampproject/amphtml/blob/master/ads/README.md#ad-resizing) the `amp-embed` after your ad is ready. The `resize` might be rejected though if amp-embed is already on the screen. 

Alternatively, you would let pub reserve space for both ad and quiz. And request a down size when an ad is not filled. This down size request might also be rejected and end up leaving an empty space in your widget.

**Comment by vladdeev** [comment]
@calebcordry @lannka @mrjoro thank you for you time and help!
Our PR was merged, closing this issue.

cc @triso07
