### ISSUE TITLE
AMP linker not working with Stories bookend links.

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#23260]
AMP linker not working with Stories bookend links.

To repro:

1. Navigate to [this story](https://www.laroche-posay.fr/article/anthelios-story/amp-a36900.aspx)
2. Navigate to the last page of the story and click on the CTA.
3. GOOD: notice the `_gl` GET parameter that has been added to the URL by the AMP linker
4. Click on the link from the bookend
5. BAD: notice how this parameter has not been added

**Comment by gmajoulet** [comment]
cc @Enriqe do you have time to look into this?

**Comment by Enriqe** [comment]
After debugging a little bit it looks like the bookend isn't forwarding the clicked target when the click event is fired. It passes the entire shadow DOM instead. 

I'll change it so that the bookend forwards the clicked target correctly.

**Comment by Enriqe** [comment]
It looks like we were already trying to do this here: 

https://github.com/ampproject/amphtml/blob/16f4ec184a7117859bb75e292fa364ad37c8203f/extensions/amp-story/0.1/amp-story-bookend.js#L516-L536

Investigating why it's not working.
