### ISSUE TITLE
Contradictory Schema.org rules

### ISSUE THREAD

**Issue by adactio** [ampproject/amphtml#2326]
Webmaster Tools is flagging up some issues with the JSON-LD in AMP articles that lead to a kind of circular Kafkaesque roundabout.

To satisfy AMP, you must supply a "publisher" field in the JSON-LD. That has two possible types: Person or Organization. If the publisher is of the type Person but no logo is provided, that throws an error because apparently a logo is required for the publisher. But if you include a logo, *that* throws an error because in its infinite wisdom, schema.org has declared that the type Person cannot have a logo (I beg to differ).

So the only way for a person who is a publisher to pass validation is to lie and say that they are an organization.

To summarise...

This triggers an error because there is no logo:

        "publisher": {
          "@type": "Person",
          "name": "Jeremy Keith"
        }

This triggers an error because there is a logo:

        "publisher": {
          "@type": "Person",
          "name": "Jeremy Keith",
          "logo": {
            "@type": "ImageObject",
            "url": "https://adactio.com/skins/default/images/logo.png",
            "width": "240",
            "height": "53"
          }
        }

This does not trigger an error but it is factually incorrect:

        "publisher": {
          "@type": "Organization",
          "name": "Jeremy Keith",
          "logo": {
            "@type": "ImageObject",
            "url": "https://adactio.com/skins/default/images/logo.png",
            "width": "240",
            "height": "53"
          }
        }

**Comment by Lovntola** [comment]
The AMP Article says the required a publisher as organisation with a Logo for the carousel.  
See [Top Stories with AMP](https://developers.google.com/structured-data/carousels/top-stories#markup_specification).  
But you are right schema.org says it can be Person/Organisation. 
I think it is more import to tell that there is a missing field for the carousell, as validate again schema.org. Without this field google will ignore the hole site for this.

**Comment by jmadler** [comment]
@Lovntola, @adactio - thanks for the heads up.  I'll fix that for you.

For future reference, since this is a Google-specific request, not an AMP Project question, please post in Google's forum: https://productforums.google.com/forum/#!categories/webmasters/accelerated-mobile-pages-amp

**Comment by adactio** [comment]
@jmadler Ah, right—sorry about posting in the wrong place. Good to know where to post stuff like this in feature.

**Comment by jmadler** [comment]
No worries dude :)
