### ISSUE TITLE
include <noscript><img /></noscript> fallbacks in docs

### ISSUE THREAD

**Issue by thebigbad** [ampproject/amphtml#2327]
Sample code at https://www.ampproject.org/docs/get_started/create/include_image.html and https://www.ampproject.org/docs/guides/amp_replacements.html fails to include <noscript> fallbacks for images, resulting in missing images when js is disabled.

For example:
`<amp-img src="welcome.jpg" alt="Welcome" height="400" width="800"></amp-img>
`

Should change to:

```
<amp-img src="welcome.jpg" alt="Welcome" height="400" width="800">
  <noscript>
    <img src="welcome.jpg" alt="Welcome" height="400" width="800" />
  </noscript>
</amp-img>
```

Or:

```
<amp-img src="welcome.jpg" alt="Welcome" height="400" width="800"></amp-img>
<noscript>
  <img src="welcome.jpg" alt="Welcome" height="400" width="800" />
</noscript>
```

_edit:_ fixed multiline formatting of code samples

**Comment by cramforce** [comment]
I don't think it is necessary to do this by default. But it would be good to mention this in the doc.
The first example is is the recommended way of doing it.

**Comment by jmadler** [comment]
I'd agree about enabling noscript behavior by default particularly as I'm unsure how the runtime could even accomplish that without JS enabled.

I think these specific examples should be focused on demonstration of amp-img, but I would welcome an addition to [this section](https://www.ampproject.org/docs/guides/amp_replacements.html#media), and also an example snippet in amp-by-example.

**Comment by Marqin** [comment]
bump
