### ISSUE TITLE
AMP-Carousel icon numbers don't change when scrolling/swiping

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#23281]
## What's the issue?

When swiping/scrolling through images the number icon doesn't identify which image you're on

## How do we reproduce the issue?

1. Opt into Canary
2. Go to webpage ([link](https://m.aliexpress.com/item/32898425649.html?pid=808_0000_0101&spm=a2g0n.search-amp.list.32898425649&aff_trace_key=&aff_platform=msite&m_page_id=4930amp-i-NUhnrXOPm9ijLvWkMEcQ1562861606115))
3. Open Web Console
4. Scroll/Swipe through images

## What browsers are affected?
macOSX Chrome Version 75.0.3770.100
macOSX FireFox 68.0
iOS Chrome 75.0.3770.103

## Which AMP version is affected?

Canary: 1907091704050

![scrolling_icon_doesnt_change](https://user-images.githubusercontent.com/48487406/61068782-ac852a00-a3bf-11e9-869f-3e57b76766ee.gif)

@kristoferbaxter, is this one of our issues since it is in AMP-Carousel?

**Comment by sparhami** [comment]
It looks like the problem is actually with amp-bind, this is potentially affecting a large number of sites. I do not think we should release a new version until this has been investigated / fixed.

@kristoferbaxter Lets hold off on releasing.

**Comment by sparhami** [comment]
@choumx Can you take a look to see why the binding is not being applied on canary/RC? The `slideChange` event is being fired correctly.

**Comment by choumx** [comment]
Great find. This is caused by #22938 on this line: https://github.com/ampproject/amphtml/blob/9f13b9aa14f07630dcba6a98a1a13d1e40711054/extensions/amp-bind/0.1/bind-impl.js#L862

If the ternary condition is true but there's no next sibling, the tree walker gets stuck on that node. It should be: `walker.nextSibling() || walker.nextNode()`
