### ISSUE TITLE
amp-list-load-more loads more than 3 viewports away

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#23286]
> My team just implemented amp-list-load-more for an infinite scroll effect.  The documentation online states that the list should preload 3 viewports ahead. https://amp.dev/documentation/components/amp-list#load-more-(mandatory)
However, our pages seem to be preloading much more than that. It seems to try and load enough so that that current view is near the middle of the page.

**Comment by cathyxz** [comment]
Closed by https://github.com/ampproject/amphtml/pull/23288.
