### ISSUE TITLE
Accelerated Mobile Pages > Prohibited attribute

### ISSUE THREAD

**Issue by evivz** [ampproject/amphtml#2328]
How to fix it? I tested in development mode. There are no error in console.

**Comment by evivz** [comment]
Strange it gives error some times and sometimes not!

**Comment by jmadler** [comment]
Is this in Google's Search Console?

**Comment by evivz** [comment]
chrome developer console.

**Comment by alaimrancars** [comment]
Hello google console , I have this message with
Accelerated Mobile Pages
Correct any errors in your pages Accelerated Mobile Page (GPA) so they can be widely disseminated to mobile users. Read more
We have not found any page Accelerated Mobile page on your site.
The Accelerated Mobile Pages ( AMP ) is an open source initiative for providing Web pages that load quickly and have well on mobile devices , even on slow networks.
If your GPA compatible pages include additional information , they may also benefit from special display features in our search results .

**Comment by alaimrancars** [comment]
web site : [http://www.alaimrancars.com](http://www.alaimrancars.com)

**Comment by dvoytenko** [comment]
@evivz Do you have error text? The sample URL?

@alaimrancars This is not an AMP page. Did you send it by mistake?

**Comment by alaimrancars** [comment]
Noo 
My web site is resposive mobile

**Comment by jmadler** [comment]
@all - please post your question on StackOverflow with the tag amp-html.  Thanks!
