### ISSUE TITLE
Have binary size check for amp4ads-v0.js

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#23307]
As to ensure the success of the inabox-lite project #22867, we would like to monitor the binary size for amp4ads-v0.js in the same way as v0.js.

@rsimha is this something your team can help? Thanks

**Comment by rsimha** [comment]
Assigning to @danielrozenberg.

@lannka I assume you're interested in the `brotli` compressed size? (See related issue #21275)

**Comment by lannka** [comment]
@rsimha yep, that sounds better. Thanks!

**Comment by lannka** [comment]
Can we prioritize this item? We just got a bundle size regression: https://github.com/ampproject/amphtml/issues/23487

It's very easy to pull in regular AMP code to AMP4ADS and cause a big size regression. 

@rsimha @danielrozenberg

**Comment by lannka** [comment]
@zhouyx do you want a size check for amp-analytics-0.1.js ? :-)

**Comment by rsimha** [comment]
Adding @erwinmombay who is going to work on some of the bundle-size feature requests.

**Comment by zhouyx** [comment]
I'm trying to think what's the value for such a check for amp-analytics.js. I could definitely see the value if later on we lazy load feature bundles, but not right now. 

It would be great to introduce such check for amp-analytics.js, but I also don't think that's super urgent right now. Really based on the effort and the cost on adding such check.

**Comment by rsimha** [comment]
Un-assigning @erwinmombay who no longer works on this. Tracking the bundle size of other binaries is definitely possible, although it will need non-trivial changes on the `amp-github-apps` side.

/cc @ampproject/wg-infra

**Comment by danielrozenberg** [comment]
Fixed
