### ISSUE TITLE
Material Design Icons?

### ISSUE THREAD

**Issue by virgiltu** [ampproject/amphtml#23304]
Ok so there are no more icons supported for amp as the current moment. 

Typography.com: https://cloud.typography.com   -- NO Icons
Fonts.com: https://fast.fonts.net   -- NO Icons
Google Fonts: https://fonts.googleapis.com  -- NO Icons
Typekit: https://use.typekit.net   -- NO longer a working project 
Font Awesome: https://maxcdn.bootstrapcdn.com, - CDN changed to stackpath.bootstrapcdn.com
 https://use.fontawesome.com  -- NO longer supported in the new Font Awesome update that now requires a JS kit.

**Comment by Stefany93** [comment]
I just go to Material Icons and download the `svg` icons to add them to my pages.

**Comment by virgiltu** [comment]
I mean I found a work around also by adding individual ones, just annoying that none of the options on the project work. 

It also sucks because what if the company has their own font? I can’t use it because it is not hosted on the whitelisted services. :/

**Comment by Stefany93** [comment]
@virgiltu , have you tried using `amp-font` for custom fonts ?

**Comment by choumx** [comment]
+1 to what @Stefany93 said. 

For fonts: https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/custom_fonts/

**Comment by virgiltu** [comment]
OK i thought we were limited to the ones on the page. Thank you
