### ISSUE TITLE
Page fails validation for amp elements 

### ISSUE THREAD

**Issue by virgiltu** [ampproject/amphtml#23302]
I am a bit confused. Maybe I am doing something wrong. Here s my validation report 

Please disregard the CSS failure. 

Validation fails saying that JavaScript is not allowed. But it tags the JS failed from amp and fontawsome.  Lower is fails that these modules are required. The files do load as the website works so what is the issue? 

[https://search.google.com/test/amp?utm_source=gws&utm_medium=onebox&utm_campaign=suit&id=tU4cdNhBtm4b8Es_McxU3g](https://search.google.com/test/amp?utm_source=gws&utm_medium=onebox&utm_campaign=suit&id=tU4cdNhBtm4b8Es_McxU3g)

**Comment by choumx** [comment]
There are typos in the script tags:
```html
<script async custom-element="mda-sidebar" src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js"></script>
```
https://validator.ampproject.org/#url=http%3A%2F%2Fcleardeal.com%2F
