### ISSUE TITLE
AMP Adsence problem

### ISSUE THREAD

**Issue by jimmy-espace-musculation** [ampproject/amphtml#2330]
hello

I have probleme with adsense as you can see in the console :+1: 

https://www.espace-musculation.com/squat.html/amp/#development=1

I have put this code
```
 <div class="ad-bas">
    <amp-ad width=300 height=200 type="adsense" data-ad-client="ca-pub-XXXXXXXXXXXX" data-ad-slot="XXXXXXX">	</amp-ad></div>
```

Is it possible that Cloudflare Rocket load is the problem ?

Have you got a solution ?

**Comment by jimmy-espace-musculation** [comment]
` <div class="ad-bas">
    <amp-ad width=300 height=200 type="adsense" data-ad-client="ca-pub-XXXX" data-ad-slot="XXXX">	</amp-ad></div>`

**Comment by jmadler** [comment]
Is this resolved as per #2331?  The amp-ad call seems fine.

**Comment by jimmy-espace-musculation** [comment]
Not resolved ....
i can see errors but i have a message : AMP validation successful

**Comment by kashyapnitin** [comment]
Can you please clarify what the problem is? I can see a valid AMP ad. Do you have any screenshots of the issue / problem you are seeing? I can separately see AMP validation error in the developer console when i open your webpage in chrome - but none related to ads.

**Comment by jridgewell** [comment]
@kashyapnitin:

> https://www.espace-musculation.com/squat.html/amp/:7:0 The attribute 'type' in tag 'script type=application/ld+json' is set to the invalid value 'text/javascript'.tx.error @ cdn.ampproject.org/v0/validator.js:320

@jimmy-espace-musculation: The error is indeed Cloudflare injecting javascript into your page. It's not injecting the code when you're on a mobile device.

**Comment by jimmy-espace-musculation** [comment]
![amp-bug](https://cloud.githubusercontent.com/assets/17526229/13474914/656da3f6-e0c0-11e5-8486-90a13ef8ecfc.jpg)

**Comment by jridgewell** [comment]
"404_or_other_error_expected._Do_not_worry_about_it" :wink: 

That's a speedup we do to make connecting to external servers faster. Unfortunately, it results in an error message in the console.

**Comment by jimmy-espace-musculation** [comment]
Thanks you Justin :+1: 

Jimmy from France
