### ISSUE TITLE
Rich page transitions e.g. swup.js

### ISSUE THREAD

**Issue by virgiltu** [ampproject/amphtml#23303]
Have you guys seen https://swup.js.org/ 

This thing is amazing and honestly I would love to see this in amp. It really makes a website feel instant and more app like. 

One of the best plugins is the preload one. This made some of our sites super fast. If not the entire thing we at minimum need this plugin. 
https://swup.js.org/plugins/preload-plugin

**Comment by choumx** [comment]
@ampproject/wg-ui-and-a11y

**Comment by choumx** [comment]
Deduping with #12981.

**Comment by virgiltu** [comment]
Thank you

**Comment by cvializ** [comment]
Thanks for triaging @choumx!

**Comment by virgiltu** [comment]
@chroumx what about preloading internal links? Is that something? I think the only thing I seen is if the page has three children that it will load these. But what about if I have a page with products and I want the site to preload the product on hover

**Comment by nainar** [comment]
Hi @virgiltu thanks for sending this through - let's chime in on the linked issue since that is the page where we are gathering product requirements?
