### ISSUE TITLE
[AMP] Problem with JSON-LD 

### ISSUE THREAD

**Issue by jimmy-espace-musculation** [ampproject/amphtml#2331]
Hello, 

As you can see on all my page /amp/ on https://www.espace-musculation.com/

I have a probleme with  JSON-LD

No solution ?

**Comment by jimmy-espace-musculation** [comment]
Ok i disable all plugins... nothing

I disable Rocket load... nothing..


**FINALY I DISABLE "MIRAGE" option from CLOUDFLARE... And it's OK !!**

>> AMP validation successful

**Comment by jmadler** [comment]
I've reached out to CloudFlare to let them know.

**Comment by jimmy-espace-musculation** [comment]
Yeahhh :-) Thank you very much !  

Jimmy from Paris
