### ISSUE TITLE
Not a bug with AMP itself, but the website 

### ISSUE THREAD

**Issue by joezimdelta** [ampproject/amphtml#23324]
The Amp-Analytics page is broken: https://amp.dev/documentation/components/amp-analytics/?format=websites

See https://www.screencast.com/t/VHca1oTYb

**Comment by cathyxz** [comment]
Thanks for letting us know! I filed this as https://github.com/ampproject/docs/issues/2498 with our docs repo instead. That's the repository for amp.dev.
