### ISSUE TITLE
🌸 Cherry-pick request for #23281 into #23271 (Pending)

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#23338]
# Cherry-pick request

| Issue | PR  | Production? | RC? | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---: | :-: | :---------: | :-: | :-----------: |
| #23281 | #23333 | **NO** | **YES** | #23271 |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

Causes amp-bind to prematurely stop scanning the DOM during initialization in some cases, resulting in inert bindings.

# Mini-postmortem

## Summary

A coding error lead to amp-bind's initialization DOM scan to get stuck on amp-list elements that have no `nextSibling`. This results in amp-bind being inert for the remaining, unscanned portion of the page.

| Users affected | Impact |
| -------------- | ------ |
| RC users on affected pages | Broken amp-bind functionality on parts of the page |

## Root Causes

1. Coding error due to misunderstanding of TreeWalker API. Calling `TreeWalker.nextSibling()` is insufficient for skipping the currently traversed node's subtree. If `nextSibling` is null, the current node remains unchanged (!), so we need to manually go to the next node in document order.

## Action Items

| Action Item | Type | Owner | PR # |
| ----------- | :--: | :---: | :--: |
| Add integration test | Prevent | @choumx | #23333 |

### Things that went well

- The bug was reported by QA (#23281) and externally (#23329) and caught in RC before it hit production.

### Things that went wrong

- The bug went unnoticed because it did not affect manual test pages.

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by dvoytenko** [comment]
Approved
