### ISSUE TITLE
🌸 Cherry-pick request for #23254 into prod 1907022322580 and canary 1907091704050

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#23334]
# Cherry-pick request

| Issue | PR  | Production? | RC? | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---: | :-: | :---------: | :-: | :-----------: |
| #23254 | #23328 | Y | Y (not sure, yes? @erwinmombay can you answer?) | https://github.com/ampproject/amphtml/issues/23271 |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

This is a P0 issue affecting amp-accordion usage in production for all IE11 and Edge users.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

`MutationObserver.prototype.observe` throws a `SyntaxError` if it is passed a configuration object that includes the property `attributeFilter` but does not have `attributes: true`.

| Users affected | Impact |
| -------------- | ------ |
| All pages with amp-accordion | The amp-accordion did not work as expected |

## Root Causes

1.

## Action Items

| Action Item | Type | Owner | PR # |
| ----------- | :--: | :---: | :--: |
| Add conformance check | Prevent | @alanorozco 🎉 | //TODO(@alanorozco) |

## Lessons Learned

Our testing story on IE is still not ideal

### Things that went well

- The fix was relatively easy to implement

### Things that went wrong

- This bug has happened before in other components (citation needed?)
- This bug had not had a conformance test added (yet)
- Other browsers silently ignore the `attributeFilter` so this was not monitoring the attributes
- An E2E test would have caught this bug

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by dvoytenko** [comment]
Approved

**Comment by erwinmombay** [comment]
@cvializ if its P0, then yes RC needs to be patched (it is essentially in step with canary)

**Comment by dvoytenko** [comment]
+1 on RC patch

**Comment by jridgewell** [comment]
We're going to patch RC, then promote that to production.

**Comment by alanorozco** [comment]
[1907161745080](https://github.com/ampproject/amphtml/issues/23372) with the patch has now been promoted to production.
