### ISSUE TITLE
500 Error on AMP Email about page

### ISSUE THREAD

**Issue by noodles** [ampproject/amphtml#23342]
I was trying to access the [AMP Email About page](https://amp.dev/about/email/). 

The page says: 

> "Uh oh! That's an error.
> Something went terribly wrong. Why don't you browse around?"

The [cached version](https://webcache.googleusercontent.com/search?q=cache:jxMLzMDnTsAJ:https://amp.dev/about/email+&cd=4&hl=en&ct=clnk&gl=au) is visible so I think someone might have broken something in a recent release of the website

**Comment by noodles** [comment]
The following pages are also facing the same issue:

- https://amp.dev/about/ads/
- https://amp.dev/about/stories/
- https://amp.dev/documentation/tools/?format=websites

All other menu bar & footer links appear to be working

**Comment by cathyxz** [comment]
Thanks for letting us know! Based on the filing of https://github.com/ampproject/amp.dev/issues/2510 and the current state of all the pages referenced, I think @sebastianbenz and folks have already fixed this. But if any further issues arrive with amp.dev, you can let us know here: https://github.com/ampproject/amp.dev/issues. =)
