### ISSUE TITLE
Using amp-carousel reports   -amp-notbuilt   -amp-unresolved

### ISSUE THREAD

**Issue by JSto88** [ampproject/amphtml#2334]
Hello,

I have an AMP page which passes AMP-Validation, however, intermittently when the page loads the amp-carousel is blank. When looking in the inspector, the AMP Carousel hasn't been built and has these classes applied to it:

"-amp-notbuilt" and "-amp-unresolved"

I've been unsuccessful in finding anybody else with this issue, how can this be resolved so the carousel loads correctly every time?

Thanks.

![screen shot 2016-02-29 at 15 23 44](https://cloud.githubusercontent.com/assets/11848417/13385739/742ff4a8-def8-11e5-9085-3207fe93c472.png)

**Comment by dvoytenko** [comment]
@JSto88 it's hard to be sure without seeing the actual page. But my guess is that the carousel's script is not included in the head:
```
<script async custom-element="amp-carousel" src="https://cdn.ampproject.org/v0/amp-carousel-0.1.js"></script>
```
Could you confirm if it's there?

**Comment by JSto88** [comment]
thanks for replying, yes the amp-carousel script is included in the head, and it has been successfully loaded too.

**Comment by dvoytenko** [comment]
@JSto88 Could you send the URL to the sample page? Or copy/paste source code in a gist?

**Comment by JSto88** [comment]
@dvoytenko No problem, here it is: [https://gist.github.com/JSto88/d1c6a9809138021dd744](url)
The amp-carousel is nearer to the bottom of the page, it's sliding through some of our website reviews. The website itself uses the cakePHP framework.

Note: I've hidden some of the generic text to hide our site.

**Comment by dvoytenko** [comment]
@JSto88 Hmm. Just opened up this page - it looks fine - the carousel is resolved and working. I can't quite see on the screenshot - what browser is this and version?

**Comment by JSto88** [comment]
@dvoytenko It is intermittent, 80% of the time it resolves and builds perfectly.

My main browser is Safari 9.0.3, however it happens in Firefox 43.0.2 too, I've not seen it happen in Chrome yet. I've not seen it happen on iOS yet.

**Comment by dvoytenko** [comment]
@JSto88 I've tried this page on the browsers you mention - but no matter how many times I tried - I can't repro. Is it possible that there's some interference from extensions?

Do you think you could send me the

1. Copy/paste or a screenshot of your console logs
2. A screenshot of your network tab. I'm specifically interested in the request/response for `amp-carousel-0.1.js`.

**Comment by bpaduch** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
