### ISSUE TITLE
Store configuration objects as JSON

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#23352]
## Describe the new feature or change to an existing feature you'd like to see

Large JSON-like configuration objects (eg, [vendors.js](https://github.com/ampproject/amphtml/blob/master/ads/_config.js) or [ads config.js](https://github.com/ampproject/amphtml/blob/master/ads/_config.js)) should be stored as JSON and parsed before use.

## Additional context

Parsing a configuration object from JSON is much [faster](https://github.com/GoogleChromeLabs/json-parse-benchmark) (additional context at https://v8.dev/blog/cost-of-javascript-2019#json) than parsing the object as if it were a real JS object literal (due to the dynamic behavior that _could_ be inside an object literal). The Chrome team also hinted last year that this may be better for memory, since the things inside the JSON will have a better backing hidden class to inherit from.

Past issues: https://github.com/ampproject/amphtml/issues/13289, https://github.com/ampproject/amphtml/issues/13288

**Comment by lannka** [comment]
@jridgewell can you confirm this is all ready in all browsers? I remember we hit an issue here: https://github.com/ampproject/amphtml/issues/13288#issuecomment-372777160

**Comment by jridgewell** [comment]
The chome canary fix has been live for almost a year. But that was specific to memory impact (we were expecting better memory usage). What we've not considered before is how much more efficient it is to parse and execute, which is [consistently faster](https://github.com/GoogleChromeLabs/json-parse-benchmark#analysis) in all browsers.
