### ISSUE TITLE
amp-experiment: Document when/how VARIANTS variable in Analytics becomes 'none'

### ISSUE THREAD

**Issue by torch2424** [ampproject/amphtml#23376]
On the current documentation page: https://amp.dev/documentation/components/amp-experiment/

It has no mention of 'none'. This was noticed by a client, and fix this.

**Comment by zhouyx** [comment]
We did document `none` is a reserved keyword. Closing the issue.  
"Variants don’t have to sum up to 100%. In that case, there will be a portion of the traffic allocated to a variant named none, which is a reserved keyword that indicates no variant was allocated."
