### ISSUE TITLE
scrollTo() doesn't work in fixed element

### ISSUE THREAD

**Issue by demil** [ampproject/amphtml#23396]
Here is pen:

[https://codepen.io/anon/pen/GVRxYz](https://codepen.io/anon/pen/GVRxYz)

Scroll to top event dont work inside fixed element.

**Comment by sparhami** [comment]
#16860 would solve this, as `scrollIntoView` supports nested containers. The current scrolling implementation does not. The main problem is that `scrollIntoView` doesn't support smooth scrolling on Safari.

I think the scope of this is larger than a fixit task, we need to investigate async loading and either handling nested scrolling or loading a polyfill.
