### ISSUE TITLE
AMP Access extension - No pingback fired after login

### ISSUE THREAD

**Issue by adaybujeda** [ampproject/amphtml#2340]
Our testing shows that after a user logs in, the AMP Access extensions triggers an amp-access request.
The user is able to see the content, but there is no pingback request fired by the framework.

This will affect metered models were AMP devices will be an extra view.

**Comment by dvoytenko** [comment]
@adaybujeda Pingback is defined as a once-per-view signal. It'd not be hard to extend it to also fire after login, but I'd like to understand this need a little better. You are saying that this will affect metered models, but how? Assuming that the user has logged in?

**Comment by adaybujeda** [comment]
Our understanding was that the pingback request would fire after a user **with access** sees an article.

When a user sees an AMP article and we do not recognize the readerId, but block the content and ask the user to login. Login is used to link the readerId to our access model.
Our testing shows that the amp-access request is fired after login, and that the user is able to see the article, but this view will not be counted as there is no pingback after that resulting in a free article.

**Comment by georgecrawford** [comment]
Essentially, since we have a barrier and are blocking content until after sign-in, the 'once-per-view' pingback needs to reflect the fact that the view has *changed* after a sign-in. Pingback should fire either "after a user with access sees an article", or "after a user sees an article, and after the access level is changed".

**Comment by dvoytenko** [comment]
@georgecrawford @adaybujeda I see. Makes sense. I will implement re-pingback after sign in/up.

**Comment by georgecrawford** [comment]
Thanks for your quick responses, @dvoytenko.

**Comment by georgecrawford** [comment]
@dvoytenko is the repeated pingback logic live yet?

**Comment by dvoytenko** [comment]
@georgecrawford No, not yet. I expect it will be in the canary soon and can be tested there. I'll send an update.

**Comment by dvoytenko** [comment]
@georgecrawford Confirmed. It's scheduled to be in canary this Thursday and in PROD the following Thursday - it follows the Thursday release cycle at this time.
