### ISSUE TITLE
AMP4EMAIL: Invalid URL protocol 'tel:' for a[href]

### ISSUE THREAD

**Issue by ChrisThorn10** [ampproject/amphtml#23411]
## What's the issue?
I am trying to validate code using https://amp.gmail.dev/playground/ and I am getting an error message for an anchor tag that has a telephone as the link.  I haven't read anywhere where tel links are not allowed so I thought it might be a bug.

## Briefly describe the bug.
I am getting an error message when trying to validate links that contain telephone numbers. Error message reads 'Invalid URL protocol 'tel:' for attribute 'href' in tag 'A (AMP4EMAIL)'.'

## How do we reproduce the issue?
Here is a github gist to reproduce the error message:
https://gist.github.com/ChrisThorn10/41cb1a78d202530860db2247e8620b46

Here is the playground I am using to test and develop:
https://amp.gmail.dev/playground/

You can paste the code from the gist into the playground editor to see the issue.

## Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:
Here is a github gist to reproduce the error message:
https://gist.github.com/ChrisThorn10/41cb1a78d202530860db2247e8620b46

Here is the playground I am using to test and develop:
https://amp.gmail.dev/playground/

You can paste the code from the gist into the playground editor to see the issue.

## What browsers are affected?
This issue is not tied to a browser

## Which AMP version is affected?
This is an AMP email issue

**Comment by ChrisThorn10** [comment]
Please note: I did send a test email using the playground and when I have the phone number included as just text (no anchor link) the gmail email client doesn't convert it into a clickable phone number.

**Comment by choumx** [comment]
@ampproject/wg-amp4email

**Comment by choumx** [comment]
These are the protocols currently allowed in a[href]: https://github.com/ampproject/amphtml/blob/680499c2c973ab4c97efb314d1da2c4ac3bff3f3/validator/validator-main.protoascii#L1927-L1929

Can we loosen this?

**Comment by kaewka** [comment]
This is a pretty useful feature on mobile phone.  It could also work on Desktop if you have the right set up.  Otherwise, you won't be able to make the call on Desktop.  The good practice is to put the phone number in the anchor text to make sure that user can also see the phone number in the email.  I don't have any security concern.

**Comment by fstanis** [comment]
I'm a bit unclear on how standardized / supported this is. [RFC 3966](https://www.rfc-editor.org/rfc/rfc3966.txt) is what I found deals with it, but it didn't seem to get much traction.

Is this supported in HTML emails?

**Comment by kaewka** [comment]
@fstanis Currently, Yahoo Mail doesn't support this in any of our mail clients.  I believe It is well supported in all modern browsers (mobile and desktop).  I am not against supporting it, but I totally understand if we don't want to support this at this point if it is unclear whether it is widely adopted as a standard or not.

**Comment by kaewka** [comment]
By the way, I would not tag this as a bug (git label).  This is more like a feature request.

**Comment by RosSpa95** [comment]
Is there any news regarding this feature? Our latest tests show that the tel protocol is not yet supported:

![image](https://user-images.githubusercontent.com/51668307/73180270-48387680-4115-11ea-9640-37c408fbe607.png)


Thanks

**Comment by zhangsu** [comment]
We will discuss this in the next AMP for Email WG meeting in 2 weeks to get a consensus among all the email clients on whether to proceed.

**Comment by zhangsu** [comment]
The working group has consensus on allowing this in the AMP for Email spec. I will be making a spec change soon.

**Comment by zhangsu** [comment]
This is fixed by #27201.
