### ISSUE TITLE
Failed to send image request

### ISSUE THREAD

**Issue by rejeep** [ampproject/amphtml#2342]
Hi,

I'm trying to implement a new vendor. Everything works fine except that I see the error message below in the Chrome-console logs (on the page `http://localhost:8000/examples.build/analytics.amp.max.html`):

```
"[AmpAnalytics.Transport]" "Failed to send image request" ...
```

I've tried to look at the event error, but it gives no clue to what is wrong. The `error` event happens on the element, but there is no information on the event on what the error was?

This is an example response from out log-servers.

```
$ curl -I "http://test.c.richmetrics.com/log?type=page"
HTTP/1.1 204 B
content-type: text/javascript
Connection: keep-alive
```

I have tried changing the response code and content-type, but get the same result.

As I said, everything works, the request is sent to our servers and that's all fine. The only issue here is the "error" log.

I'm not completely done with adding the vendor, but if you want to take a look at the code, you can view it [here](https://github.com/burtcorp/amphtml/pull/1) for now.

Thanks!

**Comment by dvoytenko** [comment]
/cc @avimehta @btownsend 

@rejeep This looks fairly certain to be an HTTP problem. What does network tab in DevTools show you? it should have request/response pair for your request. Unfortunately, image requests are not great in exposing errors to JavaScript, but network tab should have complete info.

**Comment by rejeep** [comment]
@dvoytenko All good as far as I can see:

![image](https://cloud.githubusercontent.com/assets/20277/13421318/e7d587d4-df8d-11e5-804d-edeca8ba267b.png)

**Comment by dvoytenko** [comment]
/to @btownsend 

It looks like the image decoding fails and hence you see an error. It sounds like you are receiving the event over the network just fine. But empty response causes the image itself to fail. I looked at the error event and there's no way to reliably tell the difference between an HTTP error and image decoding error.

@btownsend do you we have any recourse here? Could you please also remind me why aren't we simply sending an XHR GET request?

**Comment by btownsend** [comment]
Yes, a valid image response is required for transport.image to work.

Using images to transport analytics data is historically very common as it does not require any special setup for cross-domain requests. For analytics providers that do support CORS headers, XHR POST is preferable (as it is more semantically correct for this use.)

For this particular vendor setup, would configuring the transport options to disable image transport be sufficient?

**Comment by rejeep** [comment]
> It looks like the image decoding fails and hence you see an error.

Ahh, sneaky. That's why there was no error message.

We have always used a script tag instead of an image tag for sending requests. I don't recommend this as it's much slower than using an image tag, so sometimes the request doesn't have time to finish before the user leaves the page. You also have to modify the DOM for this to work (it's not enough to just set the script `src` as you do with an image, the script tag must also be added to the DOM).

There are a few options here to solve this:

1. Update our log-servers to support cross-domain requests
2. Update our log-servers to respond with an image
3. Add support for script-tags in amp-analytics, similar to the image option

We really don't want to update our log servers as this is the most critical part of our platform (also the reason to why we still use a script tag). If we would do (2), we would also have to set up a new cluster of log-servers to be compatible with our current scripts.

For us, (3) would obviously be the best option, what is your opinion on that?

**Comment by dvoytenko** [comment]
Sounds like responding with an image is very common. I keep seeing different blogposts with titles such as "the smallest gif". It looks like one can find a gif of only 37bytes in length.

**Comment by dvoytenko** [comment]
In the meantime, I'll close this issue. Please reopen if there are any other questions.
