### ISSUE TITLE
amp-user-notification - data-show-if-href not behaving as expected

### ISSUE THREAD

**Issue by pstricker** [ampproject/amphtml#23428]
## What's the issue?

We have implemented an amp-user-notification and are using the data-show-if-href attribute to control its visibility. It appears to be working when accessing the page from a Desktop browser using mobile emulation, however, on actual iOS devices, the notification is never shown.

I have been able to verify that the HTTP response returned from the data-show-if-href request does indeed match the value as described in the documentation `{ "showNotification": true }`. 

## How do we reproduce the issue?

Using a desktop browser with Mobile emulation (Chrome, iPhone X)
1. Start a new Incognito/Private Tab
2. Go to https://www.google.com/amp/s/www.ebags.com/amp/product/ebags/tls-professional-slim-junior-laptop-backpack/318268
3. Note the banner at the bottom of the screen that reads "Want to save 25%?".
4. This is the expected behavior

Using an iOS device (Chrome or Safari)
1. Start a new Incognito/Private Tab
2. Go to https://www.google.com/amp/s/www.ebags.com/amp/product/ebags/tls-professional-slim-junior-laptop-backpack/318268
3. Note that NO banner is displayed at the bottom of the screen.
4. This is NOT the expected behavior

## What browsers are affected?

Google Chrome for iOS
Safari for iOS

## Which AMP version is affected?
 Version 1907152257550

**Comment by wassgha** [comment]
Hello @pstricker, thank you for filing the issue! I am looking into this however I do not see the banner on the desktop browser as well and I can't seem to find any usage of the `amp-user-notification` extension on the page even though the extension script and styles are included. Has the page changed since you filed the issue? Thank you.

**Comment by pstricker** [comment]
Hi @wassgha! Yes, we removed the component a few weeks ago because of the issue. I will take a look and see if we can programmatically include the component for a single product page and will update this ticket if I can get it released.

**Comment by wassgha** [comment]
Sounds good, thank you :)

**Comment by pstricker** [comment]
Sorry for the delay in updates. In the coming weeks, I am looking at developing a mechanism to allow for a more granular release of features so we can get a small subset of pages released with the component re-enabled. I will let you know once we get something back into production to look at.
