### ISSUE TITLE
Placeholder and Fallback overlapping

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#2345]
In the `examples/ads` The Doubleclick no ad with placeholder and fallback (screenshot below) fails to hide placeholder after falling back. I understand that the expected behavior is that the placeholder would be hidden after we fallback.

<img width="161" alt="screen shot 2016-02-29 at 12 50 22 pm" src="https://cloud.githubusercontent.com/assets/2647/13408605/9e8c7574-dee3-11e5-9159-40e73baaa828.png">

**Comment by mkhatib** [comment]
It seems I am unable to reproduce this consistently, but after few trials I got the same issue again. So it does correctly hide placeholder sometimes but fails at other times.

**Comment by amphtml-team** [comment]
It probably does not fail , but the toggle is not scheduled yet ,
@dvoytenko can provide some explanation on why this might happen

**Comment by dvoytenko** [comment]
Looks like this may happen when first layoutCallback fails. We need to hide placeholder when fallback is shown.

**Comment by sriramkrish85** [comment]
@mkhatib this should be easy to fix - if you have time tomorrow can you fix this? (i will not be able to get to it till thursday). If not please reassign to me !

**Comment by mkhatib** [comment]
I'll take a look :+1:
