### ISSUE TITLE
Merging/yarn installing didn't produce working build process

### ISSUE THREAD

**Issue by andrewwatterson** [ampproject/amphtml#23461]
## What's the issue?

Merging the latest master on a fairly outdated branch and running `yarn install` still produced a failing `gulp` run.

Issue was fixed by blowing away `node_modules` and re-`yarn install`ing.
I also had to `gulp clean` to solve a different issue that occurred later in the build.

![screenshot of terminal](https://user-images.githubusercontent.com/1370189/61660012-c9521500-ac7d-11e9-9c1b-a1aa1986028b.png)

cc @rsimha who asked me to file this

## How do we reproduce the issue?

Probably not easily reproduceable - have a really old branch and then merge the latest code? :)

**Comment by rsimha** [comment]
@andrewwatterson Thanks for the report. Do you remember approximately how old your branch was before you synced it today? (I wonder if this is due to dependencies that were once declared in `package.json` but have since been removed.)

**Comment by rsimha** [comment]
Did some digging and found that this was a breaking change introduced by #23179. Unfortunately, the only workaround is to delete `node_modules/`.
