### ISSUE TITLE
Use play event for analytics instead of playing

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#23509]
Related to https://github.com/ampproject/amphtml/pull/23317#issuecomment-514438498

The `playing` event fires when a video begins playing for any reason, including after the buffer runs out and the video must pause then play again. `play` fires when the user initiates a play event. It looks like a mistake that the `playing` event was used initially.

| Event | Description |
|--|--|
|`play`|The element is no longer paused. Fired after the play() method has returned, or when the autoplay attribute has caused playback to begin.|
|`playing`|Playback is ready to start after having been paused or delayed due to lack of media data.|

Based on this, the event should be `play` if we want to track when the user plays the video.

- [ ] Somehow communicate that metrics will change. This could include updating the documentation or messaging the slack channel or the changelog for the release.
- [ ] Change the event listener from `playing` to `play`

/to @zhouyx for priority and triage
/cc @wassgha

**Comment by zhouyx** [comment]
Add @jeffjose and @nainar on ideas to communicate with existing users that we are planning to change the current behavior. THanks

**Comment by jeffjose** [comment]
Do we have stats on how many sites/pages are currently using this?

**Comment by cvializ** [comment]
I ran a query and these appear to have a lot of usage. I can send you a link to some data if you like

**Comment by jeffjose** [comment]
Yes please. Thanks!

**Comment by lannka** [comment]
since @cvializ has switched the focus, anyone from @ampproject/wg-ui-and-a11y can own this PR? /cc @kristoferbaxter
