### ISSUE TITLE
Load mustache templates from remote resource

### ISSUE THREAD

**Issue by omar-toma** [ampproject/amphtml#23504]
I am looking for loading mustache templates remotely, for example
    `<script type="text/plain" template="amp-mustache" src="https://domain.com/endpoint">`

This will help us to reduce the HTML size and will enhance our dynamic content experience.

**Comment by cathyxz** [comment]
I don't think we currently have plans to support this. @omar-a-toma could you tell us a bit more about the use cases that you are using this for? Templates really should not be so large that they need to be loaded from a separate endpoint.

**Comment by aghassemi** [comment]
So far templates had to be static to be validated with the same rules as the rest of AMP markup. With `amp-script` duplicating a lot of our validation rules in the runtime sanitizer, this might now be doable if we decide to.

**Comment by omar-a-toma** [comment]
@cathyxz So we are using AMP in our price-aggregator website [https://iprice.my](url), we are using amp-list in multiple places and most of them are not shown unless the user triggered them with an action. cutting out those templates will help to reduce the HTML size also it can help us to provide a personalized user experience

**Comment by cathyxz** [comment]
I see. So there is a rather valid use case for this. I'll defer to @nainar as to whether and when we'd like to scope this for implementation.

**Comment by nainar** [comment]
I think that is definitely something to consider and scope highly for amp-list. I am sure there are security issues that we will have to consider here. 
Paging @choumx

**Comment by huuvan20** [comment]
In some cases, the templates are very long & somehow heavy. If we could load it remotely, that would speed up the site load a lot.

**Comment by choumx** [comment]
I don't see why this is desirable yet. Can you share a concrete use case e.g. URL to a live AMP page?

**Comment by omar-a-toma** [comment]
@choumx we are using multiple templates in our website here for example [iprice.my](https://iprice.my/phones-tablets/)

**Comment by jaygray0919** [comment]
bump
