### ISSUE TITLE
AMP Story Auto Ad documentation shows different script to load

### ISSUE THREAD

**Issue by shreyaa1** [ampproject/amphtml#23507]
## What's the issue?

AMP Story Auto ad documentation (https://amp.dev/documentation/components/amp-story-auto-ads/) shows to include `<script async custom-element="amp-story" src="https://cdn.ampproject.org/v0/amp-story-1.0.js"></script>` to load where it should have been `<script async custom-element="amp-story-auto-ads" src="https://cdn.ampproject.org/v0/amp-story-auto-ads-0.1.js"></script>`

## How do we reproduce the issue?

Using just amp script to load an ad won't work as we need the `amp-story-auto-ads-0.1.js` ad also should be available in the page.

## What browsers are affected?

All browsers.

## Which AMP version is affected?

Documentation is wrong?

**Comment by calebcordry** [comment]
Looks like this issue has been fixed :)
