### ISSUE TITLE
Create a New Issue template

### ISSUE THREAD

**Issue by jmadler** [ampproject/amphtml#2351]
The [New Issue](https://github.com/blog/2111-issue-and-pull-request-templates) template should:
* Redirect support questions to StackOverflow

Anything else I'm missing?

**Comment by cramforce** [comment]
Ah, cool! Was talking to @adewale but didn't realize they launched this 10 days ago. I know Github promised to do it.

More

- Google Search related questions

Data we need

- Repro instructions
- URL with repro case
- AMP version (printed to console)
- Affected browsers
