### ISSUE TITLE
Create a New PR template

### ISSUE THREAD

**Issue by jmadler** [ampproject/amphtml#2352]
The [New PR](https://github.com/blog/2111-issue-and-pull-request-templates) template should include the steps from CONTRIBUTING.md

**Comment by rudygalfi** [comment]
@dvoytenko If you have ideas for what you'd like to see in a PR template, can you create one?

Otherwise, let's close this.

**Comment by ericlindley-g** [comment]
Closing without a response—feel free to reopen as needed
