### ISSUE TITLE
Improve navTiming to resolve earlier

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#23534]
Right now all `navTiming` metrics waits for the window load event, which is not necessary. 
This delays request pings, one optimization we could have is to resolve `navTiming` earlier

![image](https://user-images.githubusercontent.com/5419904/61906577-82b02500-aee0-11e9-87a1-c1526913b82f.png)

cc @jonkeller @jeffkaufman and @lannka

**Comment by lannka** [comment]
Cool chart, we could convert this chart to a map so every metric only wait the event they need to wait.

I hope all browsers implemented this standard.

**Comment by zhouyx** [comment]
Good point, I don't know about individual browser support. But I'm a bit concern about the value of mapping each metric to their corresponding timestamp. It requires us to understand all navTiming supported metrics in the future which could lead a code increase as well. 

@jridgewell and @choumx Do you know if runtime expose these signals? Thanks

**Comment by zhouyx** [comment]
The current plan is to only have `loadEventStart` wait for the `onload` event. 
This changes the current behavior. I'm a bit concerned that we may resolve the rest metrics too early. 

@ampproject/wg-runtime Right now all triggers happen after `viewer.whenFirstVisible()`. Is that sufficient for metrics like `domContentLoaded`? If not, what do you think is the best signal to wait for each stage? Thanks.

**Comment by jridgewell** [comment]
> Do you know if runtime expose these signals? Thanks

What signals?

> Right now all triggers happen after viewer.whenFirstVisible(). Is that sufficient for metrics like domContentLoaded?

Do you mean does `viewer.whenFirstVisible()` resolve after `domContentLoaded`?

Note that waiting for `viewer.whenFirstVisible()` is done for privacy (you cannot send analytics during prerender, only after user intent).

**Comment by zhouyx** [comment]
Thanks @jridgewell 

Honestly I'm not very familiar with the different stages in the chart above. 

1. Can I assume that all events before and includes `responseEnd` (from the chart) are always before `viewer.whenFirstVisible()`? In that case I can remove the wait for `onload` event for those. 

2. Currently we are resolving all events after `onload` event. But we think it's unnecessary, and want  to change the behavior.  
`domLoading` `domInteractive` `domContentLoaded` `domComplete` Those four events I suppose I'll also need to wait for `onload` event, but please let me know if there's some runtime signal that's after `domComplete` event but before window `onload` event. Thank you!

**Comment by jridgewell** [comment]
> Can I assume that all events before and includes responseEnd (from the chart) are always before viewer.whenFirstVisible()? 

It [appears](https://w3c.github.io/navigation-timing/#processing-model) so.

> domLoading domInteractive domContentLoaded domComplete Those four events I suppose I'll also need to wait for onload event, but please let me know if there's some runtime signal that's after domComplete event but before window onload event.

https://github.com/ampproject/amphtml/blob/cfb9330c5cb7abcaea75c96c87ab723cccb58762/src/service/ampdoc-impl.js can fire before `onload`, but is guaranteed to be after `domComplete`. `onload` _may_ be several seconds after `domComplete` because it has to wait for all network resources to be done. For large pages (lots of HTML elements) or for pages with everything in cache, `domComplete` and `onload` may be the same time.

**Comment by zhouyx** [comment]
Awesome! Thanks @jridgewell. Will switch to  the `ampdoc.whenReady()` instead of `onload`

**Comment by jridgewell** [comment]
Sorry, I meant to link to  https://github.com/ampproject/amphtml/blob/e705649863aca1c5b9bcc00c65dc408ea21de9af/src/document-ready.js#L84

**Comment by zhouyx** [comment]
Thank you @jridgewell. Created #23580 to wait for documentComplete instead of onload event.
