### ISSUE TITLE
Update title and metas

### ISSUE THREAD

**Issue by RajinderKaurIndialends** [ampproject/amphtml#23541]
Hi,
Can we create dynamic pages with updated title and metas with this feature??

**Comment by sparhami** [comment]
You should be able to use [`<amp-bind>`](https://amp.dev/documentation/components/amp-bind/) to change the title (and meta tags) like you can change any other element. This will need to be initiated from a user request (e.g. clicking a button) like any other bindings change.

This could look something like:

```html
<!doctype html>
<html ⚡>
  <head>
    <meta charset="utf-8">
    <script async src="https://cdn.ampproject.org/v0.js"></script>
    <title [text]="title">Welcome to my page</title>
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <script async src="https://cdn.ampproject.org/v0.js"></script>
    <script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>
  </head>
  <body>
    <amp-state id="title">
      <script type="application/json">"Welcome to my page"</script>
    </amp-state>
    <button on='tap:AMP.setState({ title: "A new title" })'>Update title</button>
  </body>
</html>
```

Is something like that what you are looking for or do you have something else in mind?
