### ISSUE TITLE
RESIZE_REJECT in console amp-ad

### ISSUE THREAD

**Issue by DenyHF** [ampproject/amphtml#23542]
Hello!
After implementing requestResize, errors appeared in the console.
https://prnt.sc/okdgrz
https://prnt.sc/olk5rw
In the screenshot you can see that with each resizing request console.error appears.

**Comment by tomerlevy1** [comment]
+1
I also see the same issue with amp-embed

**Comment by choumx** [comment]
Duplicate of #23619.
