### ISSUE TITLE
Consider parametrizing amp-carousel differently

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#2355]
See jQuery carousel for some ideas: http://kenwheeler.github.io/slick/

Some ideas for parameters:
- Number of slides shown at a time: 1 (current type=slides) vs 2/3/4 vs as many as fit
- Number of slides to scroll at a time
- Transition type: scroll vs overlay/fade
- Snapping behavior: with more than one slide visible at a time, whether carousel should snap to the closest slide after gesture is complete.

It's totally possible that what we already have is good and we just need to add 1-2 new features, such as different transition type. Or it's possible that we'd indeed what to split our simple `type=carousel/slides` into a combination of parameters.

**Comment by ericlindley-g** [comment]
@dvoytenko Thanks for starting this—we're building out designs for improvements to the carousel, and it's good to think of these pieces of the parametrization. Adding @ed-lea for visibility.

**Comment by Meggin** [comment]
Added Documentation label, as once this works, it will be good to document it, and provide a sample in amp-by-example.

**Comment by adelinamart** [comment]
Hi. This was not updated in a while. Do we still want to work on this? Thanks.

**Comment by ericlindley-g** [comment]
Yep — keeping this open as part of a larger project we hope to do to re-vamp amp-carousel

**Comment by caroqliu** [comment]
Closing this issue as the aforementioned configurations are available on amp-base-carousel and amp-stream-gallery.
