### ISSUE TITLE
I2I: better local development tooling support for AMPHTML ads

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#23569]
AMPHTML ads can be served and rendered in couple of different ways.

We currently have the following "envelopes" to preview an AMPHTML ad in those different env:
- `/inabox/ad.html`: served to non-AMP page, rendered inside a cross-domain iframe w/ inabox-host.js loaded.
- `/a4a/ad.html`: served to AMP page, rendered inside a friendly iframe sharing runtime w/ the AMP page. 
- `/a4a-3p/ad.html`: served to AMP page, rendered inside a cross-domain iframe due to signature verification failures.

Here we need a couple of more envelopes to accommodate our new use cases:
- `/inabox-friendly/ad.html`: served to non-AMP page, rendered inside a friendly iframe w/o inabox-host.js loaded.
- `/inabox-mraid/ad.html`: served to a MRAID enabled environment.
- `/inabox-safeframe/ad.html`: served to a SafeFrame enabled environment.

/cc @jeffkaufman @zombifier

**Comment by zombifier** [comment]
I wrote the implementation for the first 2 envelopes at #23699. PTAL.
