### ISSUE TITLE
AMP Shadow popstate navigation: Cannot read property 'originalHash' of undefined

### ISSUE THREAD

**Issue by Joelsz** [ampproject/amphtml#23575]
## What's the issue?
We're working on implementing the AMP Shadow functionality into our existing PWA.

The page is loading successfully and being attached to the DOM with the `AMP.attachShadowDocAsStream()` method, however, when navigating away from the AMP Shadow page to another (non-AMP) page and then hit the back button to get back to the shadow page, we get this error from the `attachShadowDocAsStream` method.

```
TypeError: Cannot read property 'originalHash' of undefined
    at t (mode.js:82)
    at Pn (runtime.js:510)
    at On.attachShadowDocAsStream (runtime.js:585)
```

The navigation is handled via our PWA router and the flow is basically as follows:

- Any navigation closes the AMP doc if exists and removes the container element.
- Creates a new AMP doc if needed by calling the streaming method and attaches it to a new element.
So navigating back to the AMP Shadow page should have no existing AMP doc and no container to worry about.

## How do we reproduce the issue?
I was not able to built a test case for this since it perfectly worked there... So I'm turning here to get the pro insight from those who know the code if they can resolve this without an example.

Here's the code.
```
(window.AMP = window.AMP || []).push(function(){
	
	// clean up previous AMP page
	var prevContainer = this.shadowContainer;
			
	this.shadowContainer = document.createElement('div');
	
	if(prevContainer)
		this.el.replaceChild(this.shadowContainer, prevContainer);
	else
		this.el.appendChild(this.shadowContainer);
	
	// if exists, close previous amp page (when navigating between AMP shadow pages)
	if(this.ampShadow)
		this.ampShadow.close();
	
	var ampShadow = this.ampShadow = AMP.attachShadowDocAsStream(this.shadowContainer, url);
	
	streamDocument(url, function(chunk){
		
		// for first chunk checking for validity
		
		ampShadow.writer.write(chunk);
	}.bind(this)).then(function(){
		ampShadow.writer.close();
		
		// update meta tags and link handler

	}.bind(this)).catch(function(error){
		
		// handle error

	}.bind(this))
});

function streamDocument(url, callback){
	return fetch(url).then(function(response){
		
		var reader = response.body.getReader();
		var decoder = new TextDecoder();
		
		function readChunk() {
			return reader.read().then(function(chunk){
				var text = decoder.decode(
					chunk.value || new Uint8Array(),
					{stream: !chunk.done});
				
				if(text) {
					console.log('got bytes: ', text.length);
					callback(text);
				}
				if(chunk.done){
					console.log('end stream...');
					return Promise.resolve();
				} else {
					return readChunk();
				}
			});
		}
		return readChunk();
	});
}
```

On navigation to a non-AMP shadow page we simply close the amp doc and remove the references.
```
if(this.ampShadow)
	this.ampShadow.close();

this.ampShadow = null;
this.shadowContainer = null;
```

## What browsers are affected?

Chrome 75 on windows 10

## Which AMP version is affected?

AMP ⚡ HTML shadows – Version 1907161745080
https://cdn.ampproject.org/shadow-v0.js

**Comment by Joelsz** [comment]
Though it doesn't always happen, but when happening the page doesn't show up at all, so this prevents us from going live with AMP Shadow.

It's more than just Performance, If this could be prioritized it would be appreciated. Thank you.

**Comment by kevinkimball** [comment]
@Joelsz  on this line:

```
var ampShadow = this.ampShadow = AMP.attachShadowDocAsStream(this.shadowContainer, url);
```

Is `url` defined outside of the code sample you provided here? Perhaps by the PWA router? I'm trying to get additional context so I can better investigate this issue.

**Comment by Joelsz** [comment]
> @Joelsz on this line:
> 
> ```
> var ampShadow = this.ampShadow = AMP.attachShadowDocAsStream(this.shadowContainer, url);
> ```
> 
> Is `url` defined outside of the code sample you provided here? Perhaps by the PWA router? I'm trying to get additional context so I can better investigate this issue.

Yes, it's from the PWA router which is being modified to the AMP url for the current page.

**Comment by kevinkimball** [comment]
> So navigating back to the AMP Shadow page should have no existing AMP doc and no container to worry about.

The referenced code in the trace (`mode.js`) sets variables on the `window`, not the document, which starts to explain how this might happen. We set an `originalHash` variable during bootstrap that might not yet be set, causing the error. 

@Joelsz can you provide more information about the PWA router you are using?

**Comment by Joelsz** [comment]
@kevinkimball we are using the [Backbone Router](https://backbonejs.org/#Router)

**Comment by kevinkimball** [comment]
@Joelsz I am not able to reproduce the issue given the code sample you have provided, which is just the boilerplate for shadow AMP, and which it appears you have implemented correctly. I suspect the issue is probably related to state leaking out of the embedded AMP docs (could be related to the `close()` function or incorrect references to `window`, etc.), but it's hard to say without additional information about your router implementation and document structure. If you could share that code it would help me debug further. Thanks!

**Comment by Joelsz** [comment]
Closing, since this is no longer an issue for us. Feel free to reopen if needed.
