### ISSUE TITLE
Investigate conformance check for forEach calls on NodeList

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#23570]
There have been a number of bugs that have been caused by calling `forEach` on `NodeList`. e.g. #23566 

I'm unsure of the exact implementation this would take, but it could be valuable to have in the long term.

/cc @jridgewell if there has been existing work done for this

**Comment by jridgewell** [comment]
Duplicate of https://github.com/ampproject/amphtml/issues/21234?

**Comment by cvializ** [comment]
Ah you're right, I'll close as duplicate.
