### ISSUE TITLE
Canvas support in amp-script

### ISSUE THREAD

**Issue by alabiaga** [ampproject/amphtml#23579]
There are popular charting/visual JS libraries that make use of the [canvas](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API) element. [worker-dom](https://github.com/alabiaga/worker-dom) has recently added support for canvas. Is there any reason why we haven't allowed the usage of it within the context of amp-script? 

e.g.

    <amp-script src="http://example.com/my-script.js" width=300 height=100>
       <canvas id="myCanvas">..</canvas>
    </amp-script>

**Comment by choumx** [comment]
Ah, it fails validation right?

**Comment by choumx** [comment]
Note you can still create and add canvas elements via JS. But we should fix this.

**Comment by alabiaga** [comment]
Sounds good. Yes validation fails. I can make the change Will. Thank you

**Comment by alabiaga** [comment]
cc\ @choumx @kristoferbaxter

**Comment by fstanis** [comment]
Related: ampproject/worker-dom#255

**Comment by jaygray0919** [comment]
d3.js also please. published an experiment here: https://afdsi.org/amp-script/amp-index.html
