### ISSUE TITLE
I2I: <amp-render>

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#23587]
Design doc link: [go/amp-render-design](https://docs.google.com/document/d/1KOfU1199vXCgPAAFT5qcCOiTepzf3uLgF8FUES3V2n8/edit#heading=h.84y1zb6jbi6o) 
It's also copy-pasted inline. 

# Overview
<amp-render> will be a component that renders JSON from a server endpoint or <amp-state> and renders it into a static template using <amp-mustache>, without list-specific features like pagination, load-more, or filter and sort. List-specific features will be implemented on top of `<amp-render>` as an upgraded version of `<amp-list>`. 

# Goals
<amp-render> should provide a simple-to-use templating component that: 
- Supports an easy-to-understand layout API that supports dynamic resizing (layout container) without causing content shifting.  
- Has better handling of loading and error states. 
- Supports sourcing data from amp-state and from REST endpoints (parity). 
- It should provide feature parity with current amp-list, with the exception of the load-more functionality. 
# Non Goals
<amp-render> will not support any capabilities that depend on the assumption that the rendered component is a list, or that the data comes in the shape of an array. Namely: 
- Filtering
- Sorting
- Infinite scroll / Load-more

# Use Cases
- Current usages of amp-list with the single-item attribute. 
- Favorite buttons with count (e.g. Pinned X times, Liked Y times, Retweeted Z times). 
- Seat maps like the seat picker in Fandango’s usage of amp-pan-zoom. 
     - We should already know what the seat picker needs to look like initially. 
     - The loading data should only pertain to seat availability. 
- Product detail page with remote data. 
- With amp-carousel, amp-selector, amp-accordion. 
- Search box with different categories of results. 
     - Sample code here: https://gist.github.com/cathyxz/54faee538a7a9ee9375cfb07f92d7c9b

# API
`<amp-render>` should be an AMP component that takes JSON data and renders it according to a template. The template currently uses `<amp-mustache>` but can be handlebars in the future. 
## `<amp-render>` with url src
The simplest usage of `<amp-render>` would look something like this: 
```
<amp-render src="www.example.com/" layout="fixed" width="300" height="300"> 
  <template type="amp-mustache">
    <h1>{{title}}</h1>
    {{#items}}
      <div class="url-entry">
        <a href="{{url}}">{{title}}</a>
      </div>
    {{/#items}}
    {{#favorites}}
      <div class="favorites-entry">
        <a href="{{url}}">{{title}}</a>
      </div>
    {{/#favorites}}
  </template>
</amp-render>
```
Sample JSON returned from the sample endpoint would look something like this: 
```
{
  "title": "foo", 
  "items": [
    {"url": "www.a.com", "title": "a"}, 
    {"url": "www.b.com", "title": "b"}
  ],
  "favorites": [
    {"url": "www.a.com", "title": "a"}, 
    {"url": "www.b.com", "title": "b"}
  ]
}
```

## src should be bindable
For example, we should be able to bind the src of <amp-render> to an <amp-state>. 
```
<amp-state id="my-list-url"> 
  <script type="application/json"> 
    "www.example.com/"
  </script> 
</amp-state>

<amp-render src="www.example.com/" [src]="my-list-url" 
  layout="fixed" 
  width="300" 
  height="300"> 
  <template type="amp-mustache">
    <h1>{{title}}</h1>
     ...
  </template>
</amp-render>
```
## amp-render with amp-state as src

```
<amp-state id="my-src-id"> 
  <script type="application/json"> 
    {
       "Items": [
         {"url": "www.a.com", "title": "a"}, 
         {"url": "www.b.com", "title": "b"}
       ]
     }
  </script> 
</amp-state>
<amp-render src="amp-state://my-src-id" layout="fixed" width="300" height="300"> 
  <template type="amp-mustache">
    {{#items}}
    <div class="url-entry">
      <a href="{{url}}">{{title}}</a>
    </div>
    {{/#items}}
  </template>
</amp-render>
```

### Behavior
The expected behavior here would be that <amp-render> is populated with the static data within the <amp-state id="my-src-id">. In the case that the referenced <amp-state> has a bound src attribute, the <amp-render> would update accordingly when the <amp-state> refetches new data or changes otherwise due to user manipulation. For example, 

```
<amp-state id="my-src-id" [src]="foo-url"> 
  <script type="application/json"> 
    {
       "Items": ...
     }
  </script> 
</amp-state>
<amp-state id="foo-url"> 
  <script type="application/json"> 
        "www.example.com/endpoint"
  </script>
</amp-state>
<amp-render src="amp-state://my-src-id" layout="fixed" width="300" height="300"> 
  <template type="amp-mustache">
    {{#items}}
    ...
    {{/#items}}
  </template>
</amp-render>
```

### Performance 

In this case it should be discouraged to share the <amp-state> designated for the src of <amp-render> with unrelated data such as selectors. This will result in a performance hit since <amp-render> will rerender entirely every time the referenced <amp-state> changes. A child node of the <amp-state> should be referenced as src instead. 

### Using nested <amp-state> or otherwise sharing <amp-state>

It should be valid to reference attributes of <amp-state> or nested <amp-state> as the src of <amp-render>. For example, referencing my-src-id.data in the following: 

```
<amp-state id="my-src-id"> 
  <script type="application/json"> 
    {
       "data": {
         "items": [...]
       }, 
       "selected": false,
     }
  </script> 
</amp-state>
<amp-render src="amp-state://my-src-id.data" layout="fixed" width="300" height="300"> 
  <template type="amp-mustache">
    {{#items}}
    ...
    {{/#items}}
  </template>
</amp-render>
```

This <amp-render> should re-render when data changes, but not when selected does. 

### Possible alternatives
A separate attribute, e.g. state-src, that is mutually exclusive with src. Since all of these attributes can be bound, it might be confusing to switch from a <amp-state> as src to a REST endpoint as src. We could also use `state` as the attribute name. 

### Supported Layouts
- Fixed
- Fixed Height
- Fill
- Container* 
- Intrinsic 
- Responsive

Except for layout container, <amp-render> will maintain the same dimensions or aspect ratio, and not change on load or refresh. If the height of the items rendered in layoutCallback is larger or smaller than the height of the list at build time, the <amp-render> will not resize and content will be cut off. 

`layout="container"` will be allowed for pre-rendered <amp-render> components or with width and height restrictions. If <amp-render> is expected to change size (due to having accordion as children, or bound src), the developer should use layout="container". 

### Attributes
- credentials - omit by default

### Bindable Attributes
- src - should either begin with https:// and point to a url, or amp-state:// and point to an <amp-state>. 
    - An alternative to this src=”amp-state://” API would be state=nameOfAmpState, in which case the [state] attribute would be bindable. 
- src of referenced <amp-state> 
     - <amp-state>’s src attribute is bindable, and will cause the underlying data for amp-render to change. 

### Actions
- refresh - this action will trigger a refetch of the src if the src is an `https://` endpoint. 

## Differences from current v1 <amp-list> API
- `height` is no longer a bindable attribute. This should not be necessary due to reduced scope, the support for layout container, and the overflow button. 
- `is-layout-container` and `changeToLayoutContainer` is removed in favor of supporting - `layout="container"` for `<amp-render>` with prerendering. 
- `single-item` attribute is removed because the data returned is assumed to be an object and not an array. No assumptions are made about the format of the returned JSON object.

**Comment by matthiasrohmer** [comment]
@cathyxz, the design doc is not publicly available 🙂

**Comment by cathyxz** [comment]
Access will be happily given to whoever that requests it. Otherwise, the best I can do is just copy and paste it into the github issue (which it is).

**Comment by samouri** [comment]
@dmanek, can this be closed
