### ISSUE TITLE
Add passive event listeners support to improve amp-position-observer and amp-animation performance

### ISSUE THREAD

**Issue by ild0tt0re** [ampproject/amphtml#23596]
Can you add support for passive listener to amp-position-observer and amp-animation  as made for amp-carousel here:  https://github.com/ampproject/amphtml/issues/21047

**Comment by sparhami** [comment]
Do you have an example page where non-passive events are being added (that have a `passive` version, like `touchstart`, `wheel`, etc.)? My understanding of amp-position-observer is that it uses a scroll listener internally, which is always `passive` (`preventDefault()` in a scroll event has no effect), so making it `passive` should have no effect.

**Comment by ild0tt0re** [comment]
Thanks @sparhami i understood the problem.
Lighthouse gave me this error "Does not use passive listeners to improve scrolling performance" after added amp-position-observer and amp-animation but at the same time, I have installed a chrome plugin which was the cause of the problem.
