### ISSUE TITLE
amp-analytics request json base64 encoding

### ISSUE THREAD

**Issue by iefserge** [ampproject/amphtml#2360]
I'm trying to add Keen.io analytics to the AMP page, but [Keen.io API](https://keen.io/docs/api/#record-a-single-event) requires all request variables to be json and base64 encoded.

Related https://github.com/ampproject/amphtml/issues/1292

Would it be a good idea to support base64 placeholder like so?

```
${base64(variable_name)}
```

Variable can be an object, which is implicitly converted to JSON:

``` json
{
  "vars": {
    "object": {
      "key": "value
    }
  }
}
```

Then, `${base64(object)}` will be replaced by base64 encoded `{"key":"value"}`

I think this can be useful for other analytics services too that require encoded requests.

**Comment by ccnixon** [comment]
Hey team - any updates here or thoughts on when it might be available? Thanks!

**Comment by cramforce** [comment]
@ccnixon Do you have a contact at Keen.io who could contribute a pull request to implement this?

**Comment by ccnixon** [comment]
@cramforce I do not. I'm with Segment and our API looks for base64 encoding as well (as do a few other analytics providers I believe). Happy to see where I could contribute unless you think this is something that is close to a release?

**Comment by rudygalfi** [comment]
Nobody is currently working on this, so we would appreciate a pull request. I'm assuming @avimehta and @cramforce are fine with introducing the described behavior. From my point of view, this looks like a useful addition to integrate with services that require this encoding format.

**Comment by jesuskelisto** [comment]
Hi
Is there any updates here? 
I'm trying to use something like this:
``
      "requests": {
        "pageview": "https://api.mixpanel.com/track/?data=${$data|base64)}"
      },
      "vars": {
        "data": {
          "event": "SomeEvent,
          "properties": {
            "token": "SomeToken"
          }
        }
``
But it doesn't look to work, Am I missing anything?

Thank you

**Comment by rudygalfi** [comment]
@jesuskelisto: Regarding your question, this feature is not yet released is production and is available only experimentally. To enable the experiment, in the console, do:

``` text
> AMP.toggleExperiment('variable-filters')
```

It looks like this is being covered by #2198. So I will close this. Let's continue discussion about `base64` filter there if needed.
