### ISSUE TITLE
Improve AMP's TTI/FID and generally reduce continuous main thread time

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#23618]
@kristoferbaxter submitted a first step in this direction in #22532

I noticed that we still have a quite large continuous block along the lines of

<img width="582" alt="Screen Shot 2019-07-31 at 8 28 52" src="https://user-images.githubusercontent.com/89679/62225576-925ebc00-b36d-11e9-912a-42c510966020.png">

These are CE upgrades. Those are scheduled as a `StartupChunk` and things should just work, but instead they appear to all go synchronous. Needs investigation.

**Comment by cramforce** [comment]
Good news. From my testing: The initial change is

- working as intended (modulo the issue above)
- I haven't seen over-painting (extra CPU wasted by painting when yielding to the event loop)

**Comment by kristoferbaxter** [comment]
I'll add this to the fixit list for the performance working group.
