### ISSUE TITLE
Allow audio in inactive windows/background

### ISSUE THREAD

**Issue by tobaco** [ampproject/amphtml#2361]
I know, the behaviour is on purpose (https://github.com/ampproject/amphtml/issues/440), but will you ever allow audio to play in background?

We have a very audio centric site with longer audio content (e.g. http://detektor.fm/digital/datenschutz-privacy-shield-statt-safe-harbor/amp) and our users often listen to these audios, when they are doing other stuff. Right now, if you are using the AMP version and switch tabs or let your mobile phone go in to standby, the audio stops. This can be very annoying, if you want to listen to that content and have to unlock the phone and start the audio again.

Thanks!

**Comment by jridgewell** [comment]
I'm working on the new visibility states [right now](https://github.com/ampproject/amphtml/pull/2212) that will support this:

- When the AMP doc is inactive (user swipes to next doc in search, closes viewer, etc), we will pause all content.
- When the AMP doc is hidden (the browser tab is not selected, but the AMP doc is active), we will continue to play audio.

This will land in https://github.com/ampproject/amphtml/pull/1637.

**Comment by tobaco** [comment]
Great, Thanks!
