### ISSUE TITLE
RESIZE_REQUEST error log

### ISSUE THREAD

**Issue by oste** [ampproject/amphtml#23619]
## What's the issue?

I am seeing `RESIZE_REQUEST` errors in the console. It seems to be coming from [log.js](https://raw.githubusercontent.com/ampproject/amphtml/1907231757120/src/log.js) file

![AMP_Widget_Template](https://user-images.githubusercontent.com/350275/62226455-41a88c80-b388-11e9-8267-bacdba2a5948.jpg)

## How do we reproduce the issue?

Visit this test url and view console http://code.revcontent.com/performante/amp.php/?env=feature/REVC-662

## What browsers are affected?

Tested on Chrome, iOS

## Which AMP version is affected?

Latest prod versions

**Comment by oste** [comment]
Update: the log is coming from here https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad/0.1/amp-ad-ui.js#L203 but still not too sure why.

**Comment by oste** [comment]
here is a recent change that seems to be related https://github.com/ampproject/amphtml/pull/23239

**Comment by oste** [comment]
@dvoytenko I thought you might be able to provide some insight. Is this something I am doing that is causing that log to show? I would think it should only show in dev mode.

Thanks for any information you can provide.

**Comment by dvoytenko** [comment]
This error is tagged as "expected" error - it's there temporarily for measurement needs as we are trying to assess new user activation APIs. Sorry for inconvenience.

/cc @lannka

**Comment by DenyHF** [comment]
Ticket #23542 with the same problem has already been created 10 days ago.

**Comment by vishal-taboola** [comment]
@dvoytenko  any insight/info on when can we expect it to be closed/fixed ?

**Comment by dvoytenko** [comment]
@vishal-taboola Should be gone with the next release or the following one.
