### ISSUE TITLE
amp-form: Runtime error when rendering non-element node (SSR)

### ISSUE THREAD

**Issue by ShahJay147** [ampproject/amphtml#23617]
**Please only file reports about bugs in AMP here.**

## What's the issue?
I am using AMP-email playground to develop search box which shows list of dynamic options when search. The question has been asked how to achieve this which can found [here](https://stackoverflow.com/questions/57182931/how-to-make-search-box-which-shows-list-of-dynamic-option-according-to-data-ret). I have written this in a similar format.
```
      <input id="name-input" placeholder="Search name..." on="input-throttled:AMP.setState({ name: event.value }), suggestions.submit">
      <form id="suggestions" method="get" action-xhr="https://example.com/a/b">
        <input type="hidden" name="q" value="" [value]="name">
        <div submit-success>
          success
          <template type="amp-mustache">
            {{#.}}
            <div>{{name}}</div>
            {{/.}}
          </template>
        </div>
        <div submit-error>
          error
        </div>
      </form>
``` 

API request has been called correctly and shows response data in the network. Console is producing these errors.
```
b.setAttribute is not a function. (In 'b.setAttribute("i-amphtml-rendered","")', 'b.setAttribute' is undefined)
```
and
```
Unhandled Promise Rejection: TypeError: b.setAttribute is not a function. (In 'b.setAttribute("i-amphtml-rendered","")', 'b.setAttribute' is undefined)
```

This error has been shown in amp-email's form when it is making get request and on submit and amp-mustache is called. 

## What browsers are affected?

All browsers.
## Which AMP version is affected?

I am using amp email playground for this.

**Comment by fstanis** [comment]
I'm unable to reproduce this - could you provide the full code of the email?

**Comment by choumx** [comment]
Looks like it could happen if the SSR template render succeeds but returns a non-element (e.g. text or comment node). We can handle this edge case.

**Comment by choumx** [comment]
Relevant line: https://github.com/ampproject/amphtml/blob/54f53de58ce04c35349b7202463e824241e791b1/extensions/amp-form/0.1/amp-form.js#L1159
