### ISSUE TITLE
amp-subscriptions: support conditional rendering based on scoring factors

### ISSUE THREAD

**Issue by ratana** [ampproject/amphtml#23621]
## Describe the new feature or change to an existing feature you'd like to see

Add the ability to conditionally display dialogs and buttons based on items currently used in scoring factors, such as with amp-subscriptions-google "ready to pay"; example, if user is ready to pay, show button, if not, don't show button.

## Describe alternatives you've considered

N/A
## Additional context

N/A

**Comment by jpettitt** [comment]
The design I'm working on creates a new SwG object that can be used to control dialog behavior.  It provides for any score factor to be used in rendering.  The format is `scores.[factor].[service]`

Example `scores.isReadyToPay.subscribe_google_com` would be the ready to pay score factor from the `subscribe.google.com` service (also known as `amp-subscriptions-google`).  Similarly `scores.isReadyToPay.local` would be for the `local` service and `scores.suppotsViewer.subscribe_google_com` would be the score factor for the Google service supporting the current viewer. viewer. 

Usage example:

```html
    <!-- Shows a Subscribe with Google button if the user is ready to pay -->
    <button subscriptions-display="scores.isReadyToPay.subscribe_google_com"
      subscriptions-action="subscribe"
      subscriptions-service="subscribe.google.com"
      subscriptions-decorate>Subscribe with Google</button>
    <!-- Shows a Publisher button if the user is not ready to pay -->
    <button subscriptions-display="NOT scores.isReadyToPay.subscribe_google_com"
      subscriptions-action="subscribe"
      subscriptions-service="local"
      subscriptions-decorate>Publisher offer</button>
    <div subscriptions-display="NOT subscribed">btw u are not subscribed</div>
```

I have this working in test.
