### ISSUE TITLE
Create new reference document for `amp-story-cta-layer`

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amphtml#23641]
## 📖 Missing or out-of-date documentation

**Describe the content that is missing or should be up dated**
`amp-story-cta-layer` is a separate amp component from `amp-story`. It should be migrated to its own page and include a code samples and a top table with description, required script, ect. 

https://amp.dev/documentation/components/amp-story/?format=websites#amp-story-cta-layer

**Comment by CrystalOnScript** [comment]
I think the component should still have it's own reference document, since `<amp-story-cta-layer>` can only be used once per page. However, I think we could add a section that states "Additional linking options" that routes users to these other options - where are those documented? Are they documented? This also might be appropriate for an update to the `<amp-story>` doc - maybe a section for "provide additional context" that highlights `<amp-story-cta-layer>`, `<amp-story-page-attachment>`, ect?

**Comment by newmuis** [comment]
SGTM!

**Comment by newmuis** [comment]
Fixed by #23701
