### ISSUE TITLE
AMP Access: pingback behavior

### ISSUE THREAD

**Issue by carlosabalde** [ampproject/amphtml#2364]
This is a follow up of issue #2340. I would like to clarify when pingback requests are fired. According with the spec, I was assuming:

- Pingbacks are fired when a user sees a content. It doesn't matter if the user is anonymous or authenticated. It doesn't matter if (based on the authorization response) the full version of the content is show to the user or if a login page or teaser of the content is shown. In all cases a pingback request is fired and can be used in the server side to update meters, feed server side metrics, etc.

- Further accesses of the same user to the same content will trigger additional pingback requests.

Is this correct? Thanks!

**Comment by dvoytenko** [comment]
@carlosabalde 

> Pingbacks are fired when a user sees a content. It doesn't matter if the user is anonymous or authenticated.

Correct. In fact, AMP doesn't know whether or not the user is authenticated with you - since the authorization response is a blackbox for us. You, however, can add a some data point from your authorization response into pingback to clarify it. I.e.:

```
"pingback": "https://my.com/pingback?rid=READER_ID&state=AUTHDATA(state)"
```

**Comment by carlosabalde** [comment]
Thanks. I got confused by #2340, but we've done some internal tests and everything works as expected (except the missing post-loging pingback described in the issue).
