### ISSUE TITLE
AMP4EMAIL: mobile support

### ISSUE THREAD

**Issue by alexandr-kazakov** [ampproject/amphtml#23651]
Type: Discussion/Question

Hey, guys. Now AmpEmail does not support mobile devices. I would like to know if you plan to add support in the future, if so, when?

Thanks.

**Comment by choumx** [comment]
The AMP4EMAIL spec has no restriction on mobile support. I assume you're asking about a specific email provider launch?

**Comment by alexandr-kazakov** [comment]
@choumx thanks for your reply

> The AMP4EMAIL spec has no restriction on mobile support

I just logged in from my Android 9 phone to my gmail and from my phone with the latest iOS. The html version is displayed everywhere instead of the amp version.
I have tried and through the app to go to gmail and just through the browser from mobile.

Also, I do not see in the settings how I can activate the display of the amp-version of email.

If the amp version of the email works in gmail on mobile then please tell me how to enable it?

**Comment by choumx** [comment]
Gmail hasn't launched AMP4EMAIL on mobile yet. 

https://gsuiteupdates.googleblog.com/2019/06/dynamic-email-in-gmail-becoming-GA.html

> This feature is currently only available in Gmail on the web, with mobile coming soon.
