### ISSUE TITLE
I2I: ✨ Add ContentSquare Analytics  to AMP analytics vendors

### ISSUE THREAD

**Issue by matthieuberger** [ampproject/amphtml#23653]
Hi everyone !

Add [ContentSquare](https://contentsquare.com) Analytics to AMP analytics vendors list.

**Comment by nainar** [comment]
Hi, Please follow the following instructions here :https://github.com/ampproject/amphtml/blob/47d8f204b1546b0ab7eff07be6757a198c68538d/extensions/amp-analytics/integrating-analytics.md

**Comment by matthieuberger** [comment]
I followed the instructions, according to the document first step is 

> Create an Intent-To-Implement issue stating that you'll be adding your analytics service's configuration to AMP HTML's runtime.

Can you reopen the issue please ?
