### ISSUE TITLE
amp-accordion images not loading within page attachments

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#23659]
From Slack:

"amp-accordion is not loading images when a section is hidden... You can see it in this story (second page):  https://storiestests.netlify.com/traveltips2"

**Comment by gmajoulet** [comment]
cc @newmuis this should be a good candidate for the fixit week :))

**Comment by newmuis** [comment]
Agreed!  Added.  @gmajoulet are you willing to take this on?

**Comment by gmajoulet** [comment]
Of course :)

**Comment by sparhami** [comment]
This may be related to #23449, which @cathyxz is taking a look at. Fixing one may fix the other as well.

**Comment by gmajoulet** [comment]
Thanks Sepand, will wait for this fix to land before we take on this one.

**Comment by cathyxz** [comment]
I think they might actually not be related, since the `amp-selector` issue repros with `<amp-selector>` only, and seems to be an issue isolated to children of `<amp-selector>` not laying out correctly when the `selected` attribute is toggled.

**Comment by gmajoulet** [comment]
This was fixed a while ago, when Stories starting taking ownership of AMP elements within page attachments.
