### ISSUE TITLE
amp-story boilerplate is invalid

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#23661]
The [boilerplate](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/amp-story.md#boilerplate) code for `amp-story` doesn't validate.  We should update this and fix the errors pointed out by the validator.

**Comment by petekip** [comment]
@newmuis Can you assign me this problem?

**Comment by newmuis** [comment]
@petekip done!

**Comment by newmuis** [comment]
@petekip are you still interested in working on this?

**Comment by petekip** [comment]
Yes @newmuis I am on it, thanks

**Comment by petekip** [comment]
@newmuis I have pushed the updates on my fork! Boilerplate now validates properly

**Comment by petekip** [comment]
> 
> 
> The [boilerplate](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/amp-story.md#boilerplate) code for `amp-story` doesn't validate. We should update this and fix the errors pointed out by the validator.

Hi @newmuis , did you get a chance to confirm the fix?

**Comment by newmuis** [comment]
Hey @peterkip, can you create a pull request to pull the changes from your fork into the main amphtml repository?

**Comment by petekip** [comment]
@newmuis  I have created the pull request.

**Comment by newmuis** [comment]
@petekip can you provide a link to the pull request here? I am unable to find it.

**Comment by petekip** [comment]
@newmuis here you go:  https://github.com/newmuis/amphtml/pull/1/commits/347afef1dbd920ecbdb25205211261b337313689

https://github.com/newmuis/amphtml/pull/1

**Comment by newmuis** [comment]
Hi @petekip, can you instead make a pull request to the ampproject/amphtml repository?  Please also make sure that the only commits from the pull request are your own, and that other changes aren't being pulled in mistakenly

**Comment by petekip** [comment]
Hi @newmuis ,
I see, I have done as you advised. Kindly check https://github.com/ampproject/amphtml/pull/23940

**Comment by petekip** [comment]
Hi @newmuis I hope you are well, we should close this issue, can you help revert so I can make necessary ammends

**Comment by nainar** [comment]
Fixed by #23940
