### ISSUE TITLE
Stories sidebar is too thin on desktop

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#23664]
The sidebar currently has a maximum width of `320px`.  We should increase the width.

**Comment by karansapolia** [comment]
Hey @newmuis, may I work on this issue?

**Comment by newmuis** [comment]
Sure!  @hongwei1990 is still coming up with the right numbers of what the width *should* be

**Comment by petekip** [comment]
Looking forward to the new dimension! Hopefully it will be flexible and accomodative enough

**Comment by karansapolia** [comment]
@newmuis Thank you. Sure, I'll wait for when we have the right width number.

**Comment by newmuis** [comment]
For viewports that are from 320px to 1023px, we should use a width of 75%, with a max width of 360px.

For viewports that are 1024px and above, we should use a width of 25%, with a max width of 600px.

@karansapolia let me know if you have any questions or need any help!

**Comment by newmuis** [comment]
Sorry for the confusion; this was actually already fixed by #23773

**Comment by karansapolia** [comment]
Oh! okay. Thanks for the heads up @newmuis . Do you have any other potential GFIs in mind for me to work on :slightly_smiling_face:?
