### ISSUE TITLE
amp-list causes SVG to re-render for each item

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#23674]
Our goal is to label nodes in an SVG document using `amp-list` and `amp-mustache`
Inspiration is a @sebastianbenz Sebastian Benz example:
  https://amp.dev/documentation/examples/interactivity-dynamic-content/seatmap/preview/
SVG's label selectors are sourced from an`amp-list`

Here, labels are "baked-into" the SVG.
  https://afdsi.org/amp-list-04/flavonoids.svg

Now see result when rendered using `amp-list` and `amp-mustache`
  https://afdsi.org/amp-list-05/

An SVG diagram is rendered for each item in `amp-list`. In other words, the number of SVG diagrams equals the number of items in `amp-list`.

@cathyxz Cathy Zhu looked at this issue and suggested we copy @kul3r4 Chiara on this thread.

For us, this is a `severity-1` issue because we have no work-around. We cannot generate National Language versions of an SVG, where `amp-list` is source of National Language labels.

Are we doing something wrong?
Is there an alternative way to inject values into an SVG using `amp-list` and `amp-mustache`?

**Comment by sebastianbenz** [comment]
You should be using amp-list's `single-item` mode instead. By default, amp-list will add additional markup which is breaking your svg. 

Instead, manually iterate over the items inside the amp-list template: 

```
<amp-list single-item items="." ...>
  <template ...>
   <svg>
      {{#items}}
         <rect {{item}} ...
      {{/items}}
   </svg>
  </template ...>
</amp-list>
```

Closing this for now, feel free to re-open in case it's an issue with the AMP runtime.
