### ISSUE TITLE
Valid amp code fails biolerplate check after passing through html tidy

### ISSUE THREAD

**Issue by PaulElschot** [ampproject/amphtml#2369]
After html tidy (for html 5) I get this amp validation error message:
"The mandatory text (CDATA) inside tag 'boilerplate (js enabled)' is missing or incorrect."

I'm using this tidy: https://github.com/htacg/tidy-html5/releases/tag/5.1.25

The problem is that tidy adds a few new lines inside the required `<style amp-biolerplate>`.
I tried using the --new-pre-tag option to tidy, but it still adds newlines.

There are a few solutions:
- make the amp biolerplate validation a little less strict,
- make tidy a little smarter (or did I miss a tidy option for this?),
- patch the tidy output to remove the added newlines in the amp biolerplate code.

For now my workaround is to not use tidy to produce the actual html, but I'd prefer to keep using it.

Any suggestions on how to go about this minor problem?

**Comment by Gregable** [comment]
Thanks for the report. We would prefer to eventually make the validation less strict and we're working on fully parsing the CSS to do so. There is a similar request at https://github.com/ampproject/amphtml/issues/1877 for tracking this.

In the meantime, we are _trying_ to be whitespace agnostic, but it's not perfect. If it helps, here's the regexp we're using: https://github.com/ampproject/amphtml/blob/master/validator/validator.protoascii#L564
Note that the line number may change as commits roll in, you can search on the page for `webkit-animation` if that link isn't working.

**Comment by jridgewell** [comment]
@Gregable: In the meantime, the following regex should be a little more forgiving to normal css style:

```
\\s*body\\s*{\\s*-webkit-animation:\\s*-amp-start\\s+8s\\s+steps\\(1,\\s+end\\)\\s+0s\\s+1\\s+normal\\s+both;\\s*-moz-animation:\\s*-amp-start\\s+8s\\s+steps\\(1,\\s+end\\)\\s+0s\\s+1\\s+normal\\s+both;\\s*-ms-animation:\\s*-amp-start\\s+8s\\s+steps\\(1,\\s+end\\)\\s+0s\\s+1\\s+normal\\s+both;\\s*animation:\\s*-amp-start\\s+8s\\s+steps\\(1,\\s+end\\)\\s+0s\\s+1\\s+normal\\s+both\\s*}\\s*@-webkit-keyframes\\s+-amp-start\\s*{\\s*from\\s*{\\s*visibility:\\s*hidden\\s*}\\s*to\\s*{\\s*visibility:\\s*visible\\s*}\\s*}\\s*@-moz-keyframes\\s+-amp-start\\s*{\\s*from\\s*{\\s*visibility:\\s*hidden\\s*}\\s*to\\s*{\\s*visibility:\\s*visible\\s*}\\s*}\\s*@-ms-keyframes\\s+-amp-start\\s*{\\s*from\\s*{\\s*visibility:\\s*hidden\\s*}\\s*to\\s*{\\s*visibility:\\s*visible\\s*}\\s*}\\s*@-o-keyframes\\s+-amp-start\\s*{\\s*from\\s*{\\s*visibility:\\s*hidden\\s*}\\s*to\\s*{\\s*visibility:\\s*visible\\s*}\\s*}\\s*@keyframes\\s+-amp-start\\s*{\\s*from\\s*{\\s*visibility:\\s*hidden\\s*}\\s*to\\s*{\\s*visibility:\\s*visible\\s*}\\s*}\\s*
```

**Comment by SanderTuit** [comment]
According to the documentation:  **Next, make sure that your AMP page is actually valid AMP, or it won’t get discovered and distributed by third-party platforms like Google Search**. 

Does this whitespace problem also block my AMP from being indexed?

**Comment by Gregable** [comment]
It blocks the document from appearing in the AMP carousel. The canonical will still be indexed and ranked as a regular HTML document.

**Comment by PaulElschot** [comment]
I don't know how to test the html out of tidy against the regexp used by the amp validation.

So, for the record, this is how I'm using tidy in a unix pipe:

tidy -q -utf8 --tidy-mark no --wrap 120 --new-inline-tags amp-img

and this is what tidy makes of the biolerplate:

```html
<style amp-boilerplate="">
body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}
</style>
<noscript>
<style amp-boilerplate="">
body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}
</style></noscript>
```

**Comment by powdercloud** [comment]
I've submitted an update to allow leading and trailing spaces, so the particular version in @PaulElschot's post should start working once this is live (I'll try to update this issue). The regex I put is not as elaborate as @jridgewell's however - I'd like to keep this a bit simpler for now.

**Comment by powdercloud** [comment]
The slightly more lenient regex is live, so @PaulElschot's example in particular should work from hereon. I'll take the liberty and close this particular issue - thanks much for raising it.
