### ISSUE TITLE
Unit tests in extensions subfolders don't run

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#23704]
- `extensions/amp-foo/0.1/test/test-foo.js` will be run.
- `extensions/amp-foo/0.1/test/unit/test-foo.js` will not be run.

https://github.com/ampproject/amphtml/blob/4727ad1f28764f53e21ea0e47f0518372e1cf41a/build-system/config.js#L78-L82

Looks like amp-script and amp-addthis are affected, maybe others. Let's either run all tests in subfolders or error at runtime.

/to @ampproject/wg-infra

**Comment by rsimha** [comment]
I'll send out a PR to fix the globs in `unitTestPaths`.

For a long-term fix, there's an outstanding task to standardize the location of test files across the repo. See #20197 (/cc @estherkim)
