### ISSUE TITLE
AMP Linker decorating anchor that points to elem in same page

### ISSUE THREAD

**Issue by danieltxok** [ampproject/amphtml#23725]
Hi,

we have a page with a form element at the bottom which has the attribute _id="contact-form"_. Above the fold there is a _"More info"_ CTA that takes the user to the form. This CTA has an anchor element and an attribute _href="#contact-form"_. This has traditionally worked.

However, with the linker, the URL is decorated when clicking on that anchor and the browser identifies that as a completely new page, reloading the page again and duplicating page views.

Even though this can be avoided by removing the anchor and adding  _on="tap:contact-form.scrollTo(duration=200,position=top)"_, ideally and to avoid this issue on new AMP pages implementing the linker, the linker should not decorate links pointing to an element of the same page.

Thanks,

Daniel

**Comment by micajuine-ho** [comment]
Hi @danieltxok. Thank you for your issue report. 

Would it be possible to include an example page to illustrate the problem you are having?
