### ISSUE TITLE
Switch from prefetch to preload where available

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2372]
Link to @yoavweiss's feature detect script
https://github.com/w3c/preload/pull/39/files

Would require enhancing our preload calls to include the type.

**Comment by igrigorik** [comment]
This should be a big win. Prefetch is low-priority fetch.. Preload should offer much better fit for what you're trying to do.

**Comment by mkhatib** [comment]
@igrigorik we ran into one problem #2492  with preload `as` attribute and thought you might know why. According to the spec we should be able to use `as=document` for document loaded through iframe/frame. 

Any idea if this is a browser support issue? For now we dropped #2500 the `as=document` usage.

**Comment by yoavweiss** [comment]
That's an implementation issue, as `document` support didn't yet make it.

Can you please open a crbug and send it my way? I'll do my best to then merge it back to 50.

**Comment by mkhatib** [comment]
Thanks @yoavweiss done https://bugs.chromium.org/p/chromium/issues/detail?id=593267#

**Comment by cramforce** [comment]
Does the warning mean the value is ignored? In that case we might just want to revert our change to not use `document`.

**Comment by yoavweiss** [comment]
Yeah, the value is ignored (since the alternative would have been a double download). I'll comment on this issue once the Chrome bug is resolved.

**Comment by cramforce** [comment]
@mkhatib Lets revert #2500

**Comment by cramforce** [comment]
@yoavweiss While I have you here: If I preload URL X and X responds with a preload directive in the HTTP response header, is that execute immediately?

**Comment by yoavweiss** [comment]
Normally Link based preloads should be acted upon after that initial response data is committed. (so after the first chunk of payload data arrives)
