### ISSUE TITLE
module build should be run under strict mode

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#23734]
seeing a few errors:
Error: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
Error: Use of const in strict mode.

double check that module builds is ran under strict mode

**Comment by choumx** [comment]
Related: https://github.com/ampproject/amphtml/pull/26779#issuecomment-604001815, #19380

**Comment by kristoferbaxter** [comment]
Module script tags are strict by default.
