### ISSUE TITLE
Google Webmaster Console - blocked resources - > https://instagram.fsnc1-1.fna.fbcdn.net > /amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it

### ISSUE THREAD

**Issue by Polylike** [ampproject/amphtml#2376]
Hey,

i found the following message in Google Webmaster Console - blocked resources - > https://instagram.fsnc1-1.fna.fbcdn.net > /amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it

A issue for Google, AMP or Instagram or "Do_not_worry_about_it"?

Thanks

**Comment by jmadler** [comment]
I think Do_not_worry_about_it :)

But we do need to skip these in Search Console.  I'll let the team know.  Thanks!

**Comment by cramforce** [comment]
Awesome "Bug"

**Comment by Polylike** [comment]
Hey, the problem is still there and there are a other blocked resource: https://video-iad3-1.xx.fbcdn.net Thanks a lot.

**Comment by jmadler** [comment]
In Google's Search Console, you can send them feedback by clicking on Help -> Send Feedback.  It'll take a screenshot of the page (with blackout/hilight options), so they can have a complete bug report.

**Comment by Integralist** [comment]
Hi, I'm seeing this `amp_preconnect_polyfill_404_or_other_error_expected` in our logs and I've no idea what triggers it (I know very little about the amp project btw). Any one with any info? Much appreciated :-)

**Comment by cramforce** [comment]
@Integralist Does this help https://github.com/ampproject/amphtml/blob/78b17216c8066818a528a76df27c2254eb69aea5/src/preconnect.js#L244
