### ISSUE TITLE
amp-carousel should support no swipe in AMP for Email

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#23760]
Using this to understand the requirements for `<amp-carousel>` in AMP for Email.

Do we disable swipe actions on the carousel on mobile and always show arrows?

The reason to do this could be to allow the swipe actions in the email client to run without hijacking the swipe action.
cc @choumx

**Comment by choumx** [comment]
Swipe gesture is allowed in AMP4EMAIL.
