### ISSUE TITLE
Intent to implement: Brid.tv player embed

### ISSUE THREAD

**Issue by DarXector** [ampproject/amphtml#2378]
This proposed ```<amp-brid-player>``` component would enable video playback in AMP pages using the Brid.tv video player. This component will be used by publishers using [Brid.tv Video Platform](https://www.brid.tv/) services.

Attributes specifying the publisher (partner), player and video id's determine the embed url that will be used. All assets are loded from an HTTPS location on Brid.tv content servers. An embedded iframe would be used.

Example:
 ```
<amp-brid-player
    data-partner="264"
    data-player="4144"
    data-video="13663"
    layout="responsive"
    width="480" height="270">
</amp-brid-player>
```
This would create an iframe with the following source:
https://services.brid.tv/services/iframe/video/13663/264/4144/0/1 

More info can be found in the forked [repo](https://github.com/DarXector/amphtml/blob/master/extensions/amp-brid-player/amp-brid-player.md).

The component supports a pause postMessage event to pause the video.

Thank you,
Marko

**Comment by cramforce** [comment]
LGTM

Lets make it `<amp-brid-player`

**Comment by DarXector** [comment]
Done

**Comment by DarXector** [comment]
Merge complete, I am closing this issue.
