### ISSUE TITLE
AMP-lightbox with custom transition

### ISSUE THREAD

**Issue by p2er** [ampproject/amphtml#23785]
## Describe the new feature or change to an existing feature you'd like to see

amp-lightbox only supports a fixed set on transitions which do not allow animation customization. A new animate-in attribute value like "custom" could allow for custom transition animations to be created (animate-in="custom"). This property should set a class after removing the [hidden] attribute instead of triggering the inline transition. That would allow developers to write custom transitions, because the only available hook at the moment would be to trigger the animation on [hidden] attribute added/removed. But since the display state has changed from "none" to visible css transitions are not executed in browsers. The class "custom-in" could be used to animate transitions for lightbox becomming visible while "custom-out" could be used to animate the state change to hidden. To make sure the [hidden] attribute is only set once the transition has ended the component could listen to "ontransitionend" and set [hidden] one "custom-out" is completed.

## Describe alternatives you've considered

if the animation would not be set as inline style, but instead with a transition class for the existing animations the at least the transitions could be overwritten. Would not help with the current timing of the [hidden] attribute. Main Problem is that animation timings and easing functions are very fast and can not be tuned to a more pleasing scenario. Furthermore having only the [hidden] attribute to work with does not help with chained animations.

Alternative could also be extend amp-sidebar to support side="top".  

## Additional context

amp-lightbox prevents scrolling on ios and is therefore a liable option to create menues opening from the top of the page in a consistent way.

**Comment by cathyxz** [comment]
> extend amp-sidebar to support side="top".

This is actually something we are considering working on. 

For better context, do you have demos / examples of the kind of experience you are trying to support?

**Comment by p2er** [comment]
We've just recently swapped the amp-iframe implementation with an amp-bind based approach that you can check out here: https://www.cu-camper.com/de/magazin/

**Demo:**
- open: https://www.cu-camper.com/de/magazin/
- click menu to open menu
- click search button to transition to search
- click close button to close the last opened navigation layer

Biggest issue  right now is that in menu scrolling on iOS devices can hit the page in the background wich would cause that page to scroll. The amp-lightbox uses JS to avoid that behaviour. We also tried to open an invisible lightbox right behind our menu layer, but it seems that the tap/scroll events must hit the lightbox to trigger the workaround. So as long as we want a scrollable menu on mobile we will encounter this.

Same Problem is present on the BMW AMP page: 
- open in mobile viewport: https://www.bmw.com/en/index.html
- click menu to open the overlay (with checkbox hack instead of amp bind)
- scroll menu

Its a pretty common menu type but I can't find a reliable solution with plain CSS.
