### ISSUE TITLE
Add @powerivq to reviewers

### ISSUE THREAD

**Issue by powerivq** [ampproject/amphtml#23787]
The requirement for being a reviewer has been met for @powerivq :

https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#reviewers 

It is requested that @powerivq be added to https://github.com/orgs/ampproject/teams/reviewers-amphtml

**Comment by lannka** [comment]
@powerivq has merged 13 PRs https://github.com/ampproject/amphtml/pulls?q=is%3Apr+author%3Apowerivq+is%3Aclosed

LGTMed

**Comment by lannka** [comment]
@mrjoro could you help with this?

**Comment by mrjoro** [comment]
Done!  I've invited you to the Reviewers team.  You'll have to join the ampproject org first, but then you should be automatically added to the team after you accept the invitation.
