### ISSUE TITLE
AMP Stories video "controls" attribute should not be allowed.

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#23798]
Within an `amp-story`, `<amp-video controls` attribute should not be allowed.

The AMP Stories runtime code already handles video playback, and it creates confusing UI to the user.

We will go through the deprecation process before making this attribute invalid AMP.

**Comment by mufaddal7** [comment]
Users should be encouraged to use the attachment feature. For keeping base UI simple

**Comment by gmajoulet** [comment]
Good point, thanks for bringing it up!

Videos with `controls` enabled can be displayed in `amp-story-page-attachments`.
