### ISSUE TITLE
AMP pages on desktop

### ISSUE THREAD

**Issue by eRen4ik** [ampproject/amphtml#23812]
On https://informburo.kz/novosti.html (news website) AMP pages shows on desktop browsers ignoring canonical url. Both the URLs (AMP and non-AMP) are redirecting to the AMP. Problem usually affects all fresh "news" or articles on website.

For example, if you open any freshly posted article on informburo.kz you will see AMP page on desktop browser (all browsers Mozilla, Chrome, Edge, etc) and in mobile version of website also. 

We had <canonical> and <amphtml> listed in <head> section of website but it's always show amp page no matter what. Maybe it's cached somewhere but if you once encounter this amp page bug on site it will show you everything in amp style on desktop.

**Comment by VMBindraban** [comment]
Correct me if i am wrong but isn't the canonical url only used by search engines?

```
The link element rel="canonical", often called canonical URL, is a powerful tool to combat duplicate content problems when multiple variants of (more or less) the same page exist.
```

**Comment by nainar** [comment]
In your case the link rel="canonical" is also pointing to the AMP page. It should be pointing to the non AMP page.

I took a look at this page: https://informburo.kz/novosti/v-kyzylordinskom-sadike-detyam-davali-prosrochennye-i-protivopokazannye-lekarstva-.html

**Comment by eRen4ik** [comment]
> In your case the link rel="canonical" is also pointing to the AMP page. It should be pointing to the non AMP page.
> 
> I took a look at this page: https://informburo.kz/novosti/v-kyzylordinskom-sadike-detyam-davali-prosrochennye-i-protivopokazannye-lekarstva-.html

That's the problem. Canonical points at normal non-amp page, it's the amp-page showing on the desktop browser. If you refresh this page again or look at incognito mode then you'll see normal page. Please look again.

AMP url must be this: 
<link rel="amphtml" href="https://informburo.kz**/amp/**novosti/v-kyzylordinskom-sadike-detyam-davali-prosrochennye-i-protivopokazannye-lekarstva-.html"/>
