### ISSUE TITLE
[amp-imgur] refused to display because "X-Frame-Options: deny" 

### ISSUE THREAD

**Issue by Homskiy** [ampproject/amphtml#23816]
When i try insert imgur gallery
`<amp-imgur data-imgur-id="a/XXtVaie" height="350" layout="fixed-height"></amp-imgur>
`
i get this error:

`"Refused to display 'https://imgur.com/a%2FXXtVaie/embed?pub=true' in a frame because it set 'X-Frame-Options' to 'deny'."`

But earlier it worked ...
Looks like the problem is that Imgur recently added the `x-frame-options: DENY` header

AMP Version: 1907231757120

**Comment by wassgha** [comment]
Related to #10490 , the problem comes from the fact that we use `encodeURIComponent` on the ID, however, with IDs that are in the `a/xxxx` format this breaks because the slash is encoded. Essentially #10517 didn't fix it and I'm not sure how nobody complained about it for two years.
