### ISSUE TITLE
amp-video validation fails on valid option

### ISSUE THREAD

**Issue by sevatt** [ampproject/amphtml#2381]
The amp-video docs state: 

Autoplay
The presence of the attribute alone implies that the animated image will always autoplay. The author may specify values to limit when the animations will autoplay. Allowable values are desktop, tablet, or mobile, with multiple values separated by a space. The runtime makes a best-guess approximation to the device type to apply this value.

However, when autoplay is set to "desktop tablet mobile", we get the following validation error:

The attribute 'autoplay' in tag 'amp-video' is set to the invalid value 'desktop tablet mobile'. (see https://www.ampproject.org/docs/reference/amp-video.html)

Any suggestions as to how to fix this?  Thanks.

**Comment by Meggin** [comment]
I think this might be a typo in the docs. Based on video tag in HTML5, this
is a boolean.

Checking now if maybe it's just a doc issue, and will fix once I find out.

Meggin

**Comment by sevatt** [comment]
Thanks.

**Comment by cramforce** [comment]
Its not a typo, but rather a bug. I think @dvoytenko thought about this at some point :)

**Comment by dvoytenko** [comment]
Since we can't support `autoplay=mobile`, to be honest, I don't really see a point in these values.
