### ISSUE TITLE
Error on page: amp-ad-network-doubl…ick-impl-0.1.js:519

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#23828]
##What's the issue?
Error looks it suggests an issue on Amp-Ad

Briefly describe the bug.
Error looks it suggests an issue on Amp-Ad

## How do we reproduce the issue?

1. Opt into Canary/RC
2. Open JavaScript Console
3. Open https://www.google.com/amp/s/www.mlb.com/amp/news/ian-happ-grand-slam-lifts-cubs-past-a-s.html

## What browsers are affected?
macOSX Chrome Version 76.0.3809.87

## Which AMP version is affected?

Canary/RC Version: 1908061758110

<img width="1502" alt="Screen Shot 2019-08-08 at 11 23 36 AM" src="https://user-images.githubusercontent.com/48487406/62728206-046b7c80-b9d0-11e9-9e21-66e9d70f5bc9.png">

Note: @zhouyx, @lannka is this a blocker to promote to 1%?

**Comment by erwinmombay** [comment]
i can replicate this in stable/production (1907301630320) so ill proceed with 1%

**Comment by lannka** [comment]
I feel the stack trace is a red herring . but still @keithwrightbos in case he sees something.

BTW, I couldn't reproduce on my machine.
