### ISSUE TITLE
Don't use global sinon sandbox

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#23842]
use env.sandbox instead. `env.sandbox` has custom `setUp` & `tearDown` logic baked in for `describes` tests.  Which sometimes can be critical to cause state leaks. see https://github.com/ampproject/amphtml/pull/23512#issuecomment-515806161 for example

**Comment by rsimha** [comment]
@lannka Can you point out where this must happen? Currently, we create a new sandbox and assign it to `window.sandbox` in the global `beforeEach()`.

https://github.com/ampproject/amphtml/blob/12e4ada55c87979b1486e5f5d734adb193f6b4cd/test/_init_tests.js#L407

**Comment by rsimha** [comment]
To answer my own question, [several tests](https://github.com/ampproject/amphtml/search?utf8=%E2%9C%93&q=%22sandbox+%3D+sinon.sandbox%3B%22) are using the global `sinon.sandbox` today. They all need to use `window.sandbox` or `env.sandbox`, which are created  for each test.
