### ISSUE TITLE
Error: Cannot read property '__AMP__RESOURCE' of undefined at Z

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#23858]
elevated levels of this error occurring on RC/canary

(https://cdn.ampproject.org/rtv/031908061758110/v0.js:226:24) at zj.f.scheduleLayout (https://cdn.ampproject.org/rtv/031908061758110/v0.js:309:40) at HTMLElement.b.toggleFallback (https://cdn.ampproject.org/rtv/031908061758110/v0.js:280:345) at Km.f.toggleFallback (https://cdn.ampproject.org/rtv/031908061758110/v0.js:104:103) at https://cdn.ampproject.org/rtv/031908061758110/v0/amp-ad-latest.js:23:464 at mutate (https://cdn.ampproject.org/rtv/031908061758110/v0.js:312:185) at bn (https://cdn.ampproject.org/rtv/031908061758110/v0.js:512:234) at Ym.f.Qh (https://cdn.ampproject.org/rtv/031908061758110/v0.js:511:268)

ex. page  https://gaadiwaadi-com.cdn.ampproject.org/v/s/gaadiwaadi.com/heres-is-why-we-didnt-review-the-kia-seltos/amp/?amp_js_v=0.1

@zhouyx @lannka can ya'll triage this for severity/priority?

**Comment by zhouyx** [comment]
Looking

**Comment by zhouyx** [comment]
I'm able to reproduce this locally. This is a regression affecting all `scheduleLayout()` I think. 

https://github.com/ampproject/amphtml/blob/4d577afeb5c8a60262c0c04700fb3321d00136af/src/custom-element.js#L1636-L1639
I'm going to test with other `scheduleLayout` usage other than the schedule fallback element. My guess is that `this.element` is not persisted in the owner.scheduleLayout() context. 

Could be a pretty high priority bug. @lannka

I'm going to test again

**Comment by lannka** [comment]
@powerivq let's revert the PR(s) and patch to RC/canary . hope it will still be a clean revert.

**Comment by zhouyx** [comment]
took a quick look, this could affect `<amp-consent>` and `<amp-carousel>`. I propose let's rollback 1% canary/RC before the patch.

**Comment by zhouyx** [comment]
@powerivq and I figured the fix. it's not a bout the context 😄 

`this.element` for `CustomElement` doesn't exist, the fix should be changing it to pass `this` instead.

**Comment by powerivq** [comment]
Looked more into this. I think that was caused by me mistreating a `Resources.scheduleLayout` as `BaseElement.scheduleLayout` so it changed the behavior. I believe we have high confidence of the fix and could roll forward instead.

**Comment by lannka** [comment]
Please also check all the other places. Could this be caught by `gulp check-types`?

**Comment by powerivq** [comment]
Checked thru my PRs and had no other findings.

**Comment by lannka** [comment]
SGTM to patch the fix given the rollback PRs are big and also risky

we might investigate more why `gulp check-types` didn't catch the issue. @erwinmombay @jridgewell you have any insights?

**Comment by choumx** [comment]
It's due to the `@suppress` annotation on the class. Seeing if there's a way to remove it.

**Comment by powerivq** [comment]
Keeping this open till after cherry picking.

**Comment by choumx** [comment]
#23877 fixes the underlying type checking issue.

**Comment by choumx** [comment]
Closing since cherry-pick is complete: https://github.com/ampproject/amphtml/issues/23869#issuecomment-520978645
