### ISSUE TITLE
AMP-List is supported in AMP stories , however while adding <template> it throws an error

### ISSUE THREAD

**Issue by mufaddal7** [ampproject/amphtml#23855]
## What's the issue?

The demonstration in the amp.dev shows it's possible to use `<AMP-LIST>` with `<Template>` in **AMP stories** however, it displays an error.

**The tag 'template' may not appear as a descendant of tag 'amp-story-grid-layer'.**

## How do we reproduce the issue?

https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fcomponents%2Famp-list.example.1.html%3Fformat%3Dstories&format=stories&_gl=1*px4bns*_ga*YW1wLXpLcHY1WnJpV3NPd1ZXSmFITDNHUHc.

1. Clik on this link
2. Click the error button to check errors

## What browsers are affected?

All browsers

![image](https://user-images.githubusercontent.com/42934221/62778779-f0f30b00-bace-11e9-8f14-b70d2a6959d0.png)

**Comment by gmajoulet** [comment]
Fixed by https://github.com/ampproject/amphtml/pull/28051
