### ISSUE TITLE
🌸 Cherry pick request for 23858 into 23822 (Approved)

### ISSUE THREAD

**Issue by powerivq** [ampproject/amphtml#23869]
# Cherry-pick request

| Issue | PR  | Production? | RC? | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---: | :-: | :---------: | :-: | :-----------: |
| #23858 | #23868 | **NO** | **YES** | #23822 |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

Error is caught when displaying amp-ads fallback in existing amp pages on canary.

# Mini-postmortem

## Summary

During a refactoring, we overlooked a variable and messed amp-element with a dom element. The change was in RC channel before catching the errors.

| Users affected | Impact |
| -------------- | ------ |
| RC users | Elements fallback might not render correctly. |

## Root Causes

1. `gulp check-types` did not catch the incompatible type for improper use of the variable.
2. During the refactoring, the unit tests are changed accordingly to test the incorrect behavior.
3. e2e/visual test coverages for the fallback are not good enough to cover the failure.

## Action Items

| Action Item | Type | Owner | PR # |
| ----------- | :--: | :---: | :--: |
| Fix type checking | Prevent | @choumx | #23877 |
| Add tests for element fallback | Prevent | @powerivq  | #<_PR_NUMBER_> |

### Things that went well

- We caught the error during RC, so the mistake did not propagate to all users.

- Fallback is not the primary use case for most users, so its breakage did not have as big of an impact to the users.

### Things that went wrong

- Unit tests are not reliable ways of preventing mistakes when the underlying behavior changes, and yet that were the only thing gating at the time.

- Lack of mechanisms to ensure that suppression annotations are reviewed and, when possible, removed when the underlying reasons have disappeared.

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers
/cc @lannka

**Comment by cramforce** [comment]
LGTM

**Comment by choumx** [comment]
Cherry-pick is complete.

/to @powerivq for the post-mortem.
