### ISSUE TITLE
Is it possible to do WAI-ARIA to a list of social buttons in AMP-HTML

### ISSUE THREAD

**Issue by ghost** [ampproject/amphtml#23879]
I have a list of social share image link butttons on my amp-html page, on my desktop version (non-amp-html) I have created a jQuery script to allow the keyboard navigation to work.

I have already spoken to the w3c team and they told me to create the following `role="toolbar"`.

An example of what I'm talking about can be found here: https://www.w3.org/TR/wai-aria-practices-1.2/examples/toolbar/toolbar.html

In the example you can scroll through the menu options using the arrow keys.

In my desktop version of my website, I can scroll through the social share buttons using the arrow keys - all nice and tidy.

Now my question is with the AMP-HTML team. Is it possible to do the same kind of thing and is there a script module I can use to get the same functionality. I would like it to sort out the `tabindex` `0` and `-1` and allow arrow keys to scroll through the items.

Right now my mobile version (amp-html) just allows a user to `tab` through each social share item. This is really annoying as there are around 30 social share items a user would have to keep pressing the `tab` key instead of just pressing the `tab` key once to enter and a second time to leave.

I hope I explained it well for you to understand,

Thanks and look forwqard to any suggestions.

**Comment by sparhami** [comment]
You can do something like the following jsbin: https://jsbin.com/ledopojawe/edit?html,output

This uses `<amp-selector>` with keyboard-select-mode="focus" to move focus over as you navigate with arrow keys. It does not have support for the home/end keys, which is something we can look into adding.

```html
  <amp-selector layout="container"
                keyboard-select-mode="focus"
                role="toolbar">
    <amp-social-share layout="fixed" width="48" height="48"
                      type="twitter"
                      aria-label="Share via Twitter"
                      option>
    </amp-social-share>
    <amp-social-share layout="fixed" width="48" height="48"
                      type="facebook"
                      aria-label="Share via Facebook"
                      option>
    </amp-social-share>
    ...
  </amp-selector>
```

You probably want to cancel out the selected styling since it doesn't make sense to keep visual track of the selected item when focus leaves the selector.

**Comment by ayumihamsaki** [comment]
@sparhami 

Thank you that is prefect. Good to see it's gonna be mentioned in the doc's. 👍

**Comment by cathyxz** [comment]
/cc @CrystalOnScript is there a reasonable place in our documentation / amp.dev to add this? For example, is there a generic way to add searchable examples with component and area tags (e.g. this example could be tagged with amp-selector, amp-social-share, accessibility, keyboard navigation, etc.). 

Would we want to be more proactive and consider documenting this as a best practice under `amp-social-share` to say that if you have 5+ social share buttons, you should do this to improve the a11y experience?

**Comment by ayumihamsaki** [comment]
@cathyxz @sparhami 

p.s. There is an error with the `<amp-selector>` it doesn't work for `Home` and `End` buttons.

- `Home` button should go to the first item.

- `End` button should go to the last item.

Should I open another github issue for that?

**Comment by cathyxz** [comment]
@sparhami already filed https://github.com/ampproject/amphtml/issues/23905, which will be resolved by https://github.com/ampproject/amphtml/pull/23929/.

**Comment by CrystalOnScript** [comment]
Hi @ayumihamsaki - thanks for pointing this out! I think this would be great to mention in the `amp-social-share` documentation and include it under [examples](https://amp.dev/documentation/examples/). I know we've been pushing to include more accessibility documentation, so we may make it a part of that push :)
