### ISSUE TITLE
amp-story-auto-ads not working

### ISSUE THREAD

**Issue by umuur** [ampproject/amphtml#23919]
## What's the issue?

amp-story-auto-ads component not rendering the ads. It fires:
"utils.js:60 Uncaught TypeError: Cannot read property 'contentDocument' of undefined"

This was working fine with the ads before. Yesterday, I realized that the ads not working anymore. Also, the public test page which shows the ad not working anymore.

## How do we reproduce the issue?

examples/amp-story-auto-ads.amp.html

## What browsers are affected?

All browsers.

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1907301630320

**Comment by newmuis** [comment]
@calebcordry can you take a look?

**Comment by calebcordry** [comment]
@umuur I don't see an amp-story-auto-ads tag on that page. I assume you have changed it. Could you share a broken page?

**Comment by umuur** [comment]
@calebcordry Hi there, could you please check this url: https://feed.storyim.com/donanim-haber/?url=https://api.donanimhaber.com/dev/web/api/storyfeed

I need to change the page because the one above is on production.

**Comment by umuur** [comment]
Hi @calebcordry, I've update the test url for reproducing this issue. Could you please check it?

**Comment by mzrahmani** [comment]
Any update on this issue??
I am getting validation error when using auto ads : 
The tag 'amp-story-auto-ads' requires including the 'amp-story-auto-ads' extension JavaScript.
According to documentation I should not add any specific extension and when I do add the extension I get also an error :
The extension 'amp-auto-ads' was found on this page, but is unused. Please remove this extension.

Check this link to produce this error:
https://xn--mgbaj6b6cjhb0b.com/recipe/%D8%A3%D8%A8%D9%88-%D8%B4%D9%88%D8%B4%D8%A9-%D9%82%D9%84%D9%82%D8%A7%D8%B3-%D9%86%D8%A8%D8%A7%D8%AA%D9%8A%D8%A9/recipe_story/#development=1

**Comment by calebcordry** [comment]
@mzrahmani We worked through the original issue offline. Sorry should have updated here. Anyway your issue is slightly different. Looks like you are including the script for `amp-auto-ads` not `amp-story-auto-ads`  if you include this `<script async custom-element="amp-story-auto-ads" src="https://cdn.ampproject.org/v0/amp-story-auto-ads-0.1.js"></script>` I think your problem should sort itself out.
