### ISSUE TITLE
Request for @leafsy to become a collaborator on amphtml

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#23912]
> A person may become a Collaborator after 2 merged PRs that are non-trivial (not only fixing typos, not only config changes) and a +1 from 1 current Reviewer. To request becoming a Collaborator file an issue in the repository in which you are requesting to be a Collaborator and cc a Reviewer in that repository.

https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#roles

Relevant PRs: #23880, #23906. 

/cc @leafsy

**Comment by mrjoro** [comment]
@leafsy congrats on becoming a Collaborator!  I've sent you an invite to join the ampproject org and the Collaborator GitHub team.

Note that this doesn't quite yet give you write access to the amphtml repo while we work on getting a bot in place to ensure Reviewer approval of PRs.  @rsimha / @erwinmombay is there an issue tracking that work?

**Comment by erwinmombay** [comment]
the system will still be relying on the "reviewers" team that we've established on github (this is for reliability purposes)

**Comment by cathyxz** [comment]
Does that mean Collaborators will have permissions to merge their authored PRs after said PRs have been approved by Reviewers?

**Comment by rsimha** [comment]
> @rsimha / @erwinmombay is there an issue tracking that work?

We have a [few issues](https://github.com/ampproject/amp-github-apps/issues?q=is%3Aissue+is%3Aopen+label%3A%22Category%3A+Owners%22) in the `amp-github-apps` repo to track this work. @rcebulko is taking over this work from @erwinmombay, and will begin working on it very soon.

**Comment by cathyxz** [comment]
Hmm, so it looks like it'll be a race between getting merge permissions as a reviewer vs. waiting for these issues to land in production.  @leafsy +oil! xD
