### ISSUE TITLE
amp-carousel not showing loading indicator in firefox

### ISSUE THREAD

**Issue by VMBindraban** [ampproject/amphtml#23916]
## What's the issue?

`amp-carousel` is not showing the loading indicator when loading the images.
It shows the `alt` of the image until the images is loaded.

In chrome the `alt` text is not shown but the loading indicator is (which is correct).

## How do we reproduce the issue?

```html
<amp-carousel
  layout="fill"
  type="slides">
    <amp-img alt="alt text"
    layout="fill"
    src="[IMG]"></amp-img>
</amp-carousel>
```

## What browsers are affected?
Firefox 68.01 Desktop

## Which AMP version is affected?

amp-carousel-0.1
amp V0

**Comment by sparhami** [comment]
I could not reproduce the issue locally. Do you have a demo page (e.g. on jsbin) where you see the issue?
