### ISSUE TITLE
ampUrls.batchGet returns inconsistent results

### ISSUE THREAD

**Issue by samparnell** [ampproject/amphtml#23925]
## What's the issue?

My customer (Hearst publishing) has live, valid, amp pages that are present in the amp cache. The Google ampUrls.batchGet api fails to report that they are present in the cache. 

This issue has been hard to pin down but I have consistently seen the ampUrls.batchGet api misreport content, that is valid and present in the cache, for the majority of this year. 

## How do we reproduce the issue?

See below for sample links to the google dev tool. 

This is an example of the issue. I see this problem occurring on approx 40% off the links for this publisher. If you go to the SFGate.com front page and select a few links the issue is easy to reproduce. 

### Sample
This link has a live, valid, AMP page that is present in the google cache:
Publisher html page: https://www.sfgate.com/news/article/Lake-Tahoe-report-Removing-invasive-shrimp-14296655.php
Publisher AMP Page: https://www.sfgate.com/news/amp/Lake-Tahoe-report-Removing-invasive-shrimp-14296655.php
AMP Cache Page: https://www-sfgate-com.cdn.ampproject.org/c/s/www.sfgate.com/news/amp/Lake-Tahoe-report-Removing-invasive-shrimp-14296655.php

[API Request using the html page url](https://developers.google.com/amp/cache/reference/acceleratedmobilepageurl/rest/v1/ampUrls/batchGet?apix_params=%7B%22resource%22%3A%7B%22lookupStrategy%22%3A%22FETCH_LIVE_DOC%22%2C%22urls%22%3A%5B%22https%3A%2F%2Fwww.sfgate.com%2Fnews%2Farticle%2FLake-Tahoe-report-Removing-invasive-shrimp-14296655.php%22%5D%7D%7D):
```
{
  "lookupStrategy": "FETCH_LIVE_DOC",
  "urls": [
    "https://www.sfgate.com/news/article/Lake-Tahoe-report-Removing-invasive-shrimp-14296655.php"
  ]
}
```
Response :
```
{
  "urlErrors": [
    {
      "errorCode": "NO_AMP_URL",
      "errorMessage": "No AMP URL for the request URL.",
      "originalUrl": "https://www.sfgate.com/news/article/Lake-Tahoe-report-Removing-invasive-shrimp-14296655.php"
    }
  ]
}
```

Using the AMP url to check the api does work however.

[API Request using the amp page url](https://developers.google.com/amp/cache/reference/acceleratedmobilepageurl/rest/v1/ampUrls/batchGet?apix_params=%7B%22resource%22%3A%7B%22lookupStrategy%22%3A%22FETCH_LIVE_DOC%22%2C%22urls%22%3A%5B%22https%3A%2F%2Fwww.sfgate.com%2Fnews%2Famp%2FLake-Tahoe-report-Removing-invasive-shrimp-14296655.php%22%5D%7D%7D):
```
{
  "lookupStrategy": "FETCH_LIVE_DOC",
  "urls": [
    "https://www.sfgate.com/news/amp/Lake-Tahoe-report-Removing-invasive-shrimp-14296655.php"
  ]
}
```
Response:
```
{
  "ampUrls": [
    {
      "originalUrl": "https://www.sfgate.com/news/amp/Lake-Tahoe-report-Removing-invasive-shrimp-14296655.php",
      "ampUrl": "https://www.sfgate.com/news/amp/Lake-Tahoe-report-Removing-invasive-shrimp-14296655.php",
      "cdnAmpUrl": "https://www-sfgate-com.cdn.ampproject.org/c/s/www.sfgate.com/news/amp/Lake-Tahoe-report-Removing-invasive-shrimp-14296655.php"
    }
  ]
}
```
## Additional Examples
Here is a list of other pages that have the same issue from SeattlePI (other Hearst site):

- https://www.seattlepi.com/realestate/article/At-489K-small-but-clever-houseboat-lives-twice-14382151.php
 - https://www.seattlepi.com/sports/uw_huskies_wsu_cougars/article/How-will-the-Huskies-handle-Arizona-in-week-7-14389860.php
 - https://www.seattlepi.com/science/article/Puget-Sound-earthquake-ETS-slow-slip-magnitude-14381974.php

**Comment by samparnell** [comment]
Additional note: I just retested this using the single link in the request. I have two browser windows open on the google api test. One window consistently returns a valid response, the other one consistently returns the NO_AMP_URL response. So the exact same request is giving inconsistent responses. 

Request:
```
{
  "lookupStrategy": "FETCH_LIVE_DOC",
  "urls": [
    "https://www.sfgate.com/news/amp/Lake-Tahoe-report-Removing-invasive-shrimp-14296655.php"
  ]
}
```
Response in window 1:
```
{
  "ampUrls": [
    {
      "originalUrl": "https://www.sfgate.com/news/amp/Lake-Tahoe-report-Removing-invasive-shrimp-14296655.php",
      "ampUrl": "https://www.sfgate.com/news/amp/Lake-Tahoe-report-Removing-invasive-shrimp-14296655.php",
      "cdnAmpUrl": "https://www-sfgate-com.cdn.ampproject.org/c/s/www.sfgate.com/news/amp/Lake-Tahoe-report-Removing-invasive-shrimp-14296655.php"
    }
  ]
}
```
Response in window 2:
```
{
  "urlErrors": [
    {
      "errorCode": "NO_AMP_URL",
      "errorMessage": "No AMP URL for the request URL.",
      "originalUrl": "https://www.sfgate.com/news/article/Lake-Tahoe-report-Removing-invasive-shrimp-14296655.php"
    }
  ]
}
```

**Comment by samparnell** [comment]
Additional note: 
I just retested this and noticed that my single link example was using the publisher amp url not the html url.

Please see the two examples below, using the amp url is successful, using the html url is not. 
The html page does have the correct amphtml tag present. 
The canonical tags match.

AMP Request:
```
{
  "lookupStrategy": "FETCH_LIVE_DOC",
  "urls": [
    "https://www.sfgate.com/news/amp/Lake-Tahoe-report-Removing-invasive-shrimp-14296655.php"
  ]
}
```
Response:
```
{
  "ampUrls": [
    {
      "originalUrl": "https://www.sfgate.com/news/amp/Lake-Tahoe-report-Removing-invasive-shrimp-14296655.php",
      "ampUrl": "https://www.sfgate.com/news/amp/Lake-Tahoe-report-Removing-invasive-shrimp-14296655.php",
      "cdnAmpUrl": "https://www-sfgate-com.cdn.ampproject.org/c/s/www.sfgate.com/news/amp/Lake-Tahoe-report-Removing-invasive-shrimp-14296655.php"
    }
  ]
}
```
HTML Request:
```
{
  "lookupStrategy": "FETCH_LIVE_DOC",
  "urls": [
    "https://www.sfgate.com/news/article/Lake-Tahoe-report-Removing-invasive-shrimp-14296655.php"
  ]
}
```
Response :
```
{
  "urlErrors": [
    {
      "errorCode": "NO_AMP_URL",
      "errorMessage": "No AMP URL for the request URL.",
      "originalUrl": "https://www.sfgate.com/news/article/Lake-Tahoe-report-Removing-invasive-shrimp-14296655.php"
    }
  ]
}
```

**Comment by cramforce** [comment]
I've copied this issue to a Google internal bug (b/140409802) since this repository isn't dealing directly with AMP Cache related issues.
