### ISSUE TITLE
 Optimize the domain white list regex

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2393]
Can https://github.com/ampproject/amphtml/blob/fc5346fdd49b839fbf9e88139e34f4da250f2a6f/src/service/viewer-impl.js#L112
be made faster?

**Comment by sriramkrish85** [comment]
i think the regex pattern here might help 

https://jsperf.com/url-parsing/27

**Comment by dvoytenko** [comment]
Hmm, this is an expression that's evaluated only once, isn't it?

**Comment by jridgewell** [comment]
I'm throwing my hat behind (not to mention it fixes a bug with `www.google` domains):

```js
/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2})$/
```

http://jsperf.com/amp-th-regex
