### ISSUE TITLE
🌸 Cherry-pick request for #23947 into #23939 (Approved)

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#23948]
# Cherry-pick request

| Issue | PR  | Production? | RC? | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---: | :-: | :---------: | :-: | :-----------: |
| #23946 | #23947 | **NO** | **NO** | #23939 |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

It broke light box ads in inabox. 

# Mini-postmortem
- The experiment has run with GAM traffic, where lightbox ads are not used.
- The problem is surfaced locally after removal of the experiment flag.

## Summary

Impact so far is small, the experiment is not yet GA launched. 

## Root Causes

1. the CSS split caused missing critical CSS

## Action Items

| Action Item | Type | Owner | PR # |
| ----------- | :--: | :---: | :--: |
| Add e2e/visual tests | Prevent | @powerivq  |  |
| By default enable all inabox experiments in local development | Precent | @lannka  |  |

### Things that went well
- Issue got caught last minute before it went GA launch.

### Things that went wrong

- Should had e2e visual tests
- Should by default have flag on during local development so it could be caught earlier.

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by dvoytenko** [comment]
Approved

**Comment by cramforce** [comment]
Approved
