### ISSUE TITLE
AMP4EMAIL: Polling component for chat feature

### ISSUE THREAD

**Issue by mbelchin** [ampproject/amphtml#23941]
## Describe the new feature or change to an existing feature you'd like to see

I would like to know if there's any plan on add support for **amp-live-list** for **Amp4Emails**.

## Additional context

We're experimenting with this technology and we are right now thinking about to use it in production.

Basically we are using amp-form to send data to our servers, but we need to get data coming back, every X seconds. amp-live-list would be a good choice.

**Comment by choumx** [comment]
One caveat: today, `amp-live-list` works by polling the origin document URL, but there's no such thing in the email context. You might want `amp-list` (which allows specifying a `src`) with a polling feature.

**Comment by choumx** [comment]
> Basically we are using amp-form to send data to our servers, but we need to get data coming back, every X seconds. 

Can you elaborate on this use case? E.g. what sort of use case causes data change after form submission response?

**Comment by mbelchin** [comment]
Hi @choumx,

Thanks for your answers.

You are right, probably the best approach will be to use `amp-list` with some poll mechanism in place. If I'm not wrong I think you're already considering something like that, right? https://github.com/ampproject/amphtml/issues/15780

About the use case. Basically what we're trying to achieve is to build a chat system within Gmail. We provide chat solution and would like to integrate with Gmail, so our users can chat with us directly from the emails we send to them using AMP4Email.

Right now we're using `amp-form` + textarea + submit button to send messages to our chat agents, so the only pending thing is to have a mechanism to poll every X seconds and get messages back from agents to our users.

With that poll mechanism in place we'll be able to have "close to real time" communication, that is enough for us at this stage.

We have been considering as well to use `amp-script` and we could test it on websites, we could use setInterval however `HTMLFormElement.submit()` is not yet supported on WorkerDOM (https://github.com/ampproject/worker-dom/blob/master/web_compat_table.md)

Maybe, you can suggest to us any other ideas to consider in order to achieve this chat communication.

Thanks in advance.

**Comment by mbelchin** [comment]
Hi again @choumx ,

Is there any possibility to build our custom component (https://codelabs.developers.google.com/codelabs/creating-your-first-amp-component/index.html) and use it in AMP4Emails ?

I've seen for now it's only supported for Websites, do you know if that can be used for Email as well ?

Thanks again.
