### ISSUE TITLE
Be able to measure how much CSS is on the page

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#23977]
Currently we don't give developers any indication of the amount of CSS on the page. They only know that they are below or above the limit. 

We should be giving developers more feedback here. 

I know @Gregable has a change out for this but creating an issue to track the change and related documentation.

**Comment by Gregable** [comment]
You can now temporarily modify your `<style amp-custom>` tag to be `<style amp-custom-length-check>`. The rules for the latter have a maximum CSS length of -1, so with this temporary modification the error message will display the current length of your CSS.
