### ISSUE TITLE
amp-ad not rendering on amp-next-page when served from google cdn/cache

### ISSUE THREAD

**Issue by andyblackwell** [ampproject/amphtml#23983]
## What's the issue?

When using `<amp-next-page>`, the ads inside the appended articles render fine when self-hosted, but don't render when in the google cache.

I've also seen intermittent issues with `<amp-img>` as well, so may be a lazy loading issue causing both?

similar behavior was mentioned in #15807 
I've seen this happen on the popsugar article linked in #15807 as well, to a lesser extent. I needed to scroll down further to start seeing blank images / ads.

For the ads, in the network log I see the requests fire off and return an ad. The placeholders seem to change to the correct size of the incoming ad, except the ad never actually renders.

## How do we reproduce the issue?

Go to these urls and scroll down to the next article.

**self hosted**: amp-ad's load normally in articles loaded in via amp-next-page
https://www.gossipcop.com/brad-pitt-snoop-dogg-music/amp/

**vs.**

**Google CDN**: amp-ad's don't load in articles loaded in via amp-next-page
https://www.google.com/amp/s/www.gossipcop.com/brad-pitt-snoop-dogg-music/amp/

-- **Update**
Noticed with the current DEV channel version (1908150025400)
that this also happens on the self-hosted setup, for both images and ads

![IMG_4982](https://user-images.githubusercontent.com/372590/63122963-9134ae00-bf6d-11e9-9e55-172d9f2782aa.jpg)

## What browsers are affected?

All browsers that I can tell, both on device and spoofing in chrome. Haven't tried an android device yet.

## Which AMP version is affected?

Noticed in AMP version: 1907301630320
Current DEV channel version: 1908150025400

**Comment by andyblackwell** [comment]
Seeing these errors associated with the issue:
<img width="1175" alt="console-errors" src="https://user-images.githubusercontent.com/372590/63130778-3d33c480-bf81-11e9-9a9d-50ef5054c18b.png">

error refers to this line of code:
<img width="893" alt="error-line" src="https://user-images.githubusercontent.com/372590/63130777-3d33c480-bf81-11e9-97c8-5228deaefa65.png">

**Comment by jridgewell** [comment]
Duplicate of https://github.com/ampproject/amphtml/issues/22357.

**Comment by choumx** [comment]
@andyblackwell Does this bug still repro when you turn off dev-channel?

**Comment by andyblackwell** [comment]
I first saw it on the prod channel.

I'll have to setup a test to check if anything has changed. We had to disable `amp-next-page` due to this bug, and another where the click urls for `amp-next-page` links in the cdn are borked and cause error pages when clicked or when the page is refreshed after `amp-next-page` has changed the url.

On first glance looking at popsugar.com, the dev-channel bug seems to still just exist in the dev-channel where it also affects self-hosted amp pages.
I was able to get a couple blank images on the google cdn using prod channel for them, but the bug is always hit and miss for me on their domain for whatever reason.

Will try to get a test setup in the next couple days.

**Comment by andyblackwell** [comment]
I setup one old article with `amp-next-page` again.
https://www.google.com/amp/s/www.gossipcop.com/robert-pattinson-royal-wedding-rumor/amp/

----

for the error: `Cannot read property 'ownerDocument' of undefined`
on `prod channel`: **not** getting the error 
on `dev channel`: still getting the error 

----

on `prod channel`:

Ads are still not rendering on the appended articles for me.
Could this be related to loading strategy? popsugar is set to 3, while ours is at 1.25

Also, the `amp-next-page` links got a *partial* fix for the bugs when hosted on the google cdn.
You can click them now and don't get an error page, though now when the page loads from clicking an `amp-next-page` link you can't scroll at all. Can repro in the linked amp document above.

Other google cdn bug also still exists where `amp-next-page` updates the page url to broken links.
Can repro in the linked amp document above.
examples:
**correct**: https://www.google.com/amp/s/www.gossipcop.com/robert-pattinson-royal-wedding-rumor/amp/
**broken**: https://www.google.com/amp/s/www.gossipcop.com/v/s/www.gossipcop.com/robert-pattinson-royal-wedding-rumor/amp/
**broken**: https://www.google.com/amp/s/www.gossipcop.com/c/s/www.gossipcop.com/prince-harry-meghan-markle-baby-raising-truth/amp/

**Comment by choumx** [comment]
@ampproject/wg-ui-and-a11y Who maintains `amp-next-page` now? This and #22357 seem like important and non-trivial bugs to fix.

**Comment by andyblackwell** [comment]
**Update:** 
looks like something has changed, I'm now seeing ads and images loading as they should for the amp-next-page loaded documents, looking at the test article I shared previously. So we're going to test amp-next-page again next week.

The url is still being updated incorrectly when it is changed, so that's still broken, but progress! 

Not sure what changed though, or when this was fixed? I've looked at release notes and haven't seen anything but some renaming related to amp-next-page <shrug>

**Comment by andyblackwell** [comment]
Looks like this issue has returned again, there's some other chatter about it in AMP slack

**Comment by andyblackwell** [comment]
All ad placeholders are the entire height of the new amp-next-page document
![image](https://user-images.githubusercontent.com/372590/101810542-8b59c900-3ade-11eb-8c98-6f950ba8a6c0.png)

And here's a screenshot of the un-closeable modal auto-pop issue that was mentioned the first time around as well:
![image](https://user-images.githubusercontent.com/372590/101810779-cd830a80-3ade-11eb-9fee-25fa220c93eb.png)

**Comment by andyblackwell** [comment]
ah whoops -  I added these new comments in a hurry to the wrong ticket, meant to add them to:
#30641 **amp-next-page bugs - fallback/placeholder rendering**
