### ISSUE TITLE
Add Safari support to e2e tests

### ISSUE THREAD

**Issue by estherkim** [ampproject/amphtml#24009]
There's a lot of Safari-specific logic in AMP core services. Having Safari coverage for E2E tests will be very beneficial.

**Comment by lannka** [comment]
@dvoytenko and I are doing a bunch a refactoring of core services at this moment. Having test coverage on Safari will be very helpful.

@rsimha is this something we can prioritize?

**Comment by rsimha** [comment]
> @rsimha is this something we can prioritize?

It'd be useful to understand how much work this requires on the infra side. @estherkim could you comment on what this might involve?

**Comment by estherkim** [comment]
Sure, I see 2 options.
A. Run tests locally - spinning up a macOS VM on Travis to run tests with Apple's WebDriver.
B. Run tests remotely - moving tests to SauceLabs, which handles all browser driver logic, but involves more changes to our current e2e framework.

I'm leaning towards A for the ease of local debugging - I can start with that and see how it goes.

**Comment by lannka** [comment]
I think A is a good start. Overall Saucelabs is much harder to debug. So even later we switch to Saucelabs for better browser coverage, it is still good to have Safari support locally for debugging purpose.

Thanks @estherkim for looking into this!

**Comment by rsimha** [comment]
I wonder if Safari E2E tests can now be run during our GitHub Actions workflow on macOS.

https://github.com/ampproject/amphtml/blob/884f4962f7ed66ca609b9758e6a97ccc028c4c6e/build-system/pr-check/cross-browser-tests.js#L31-L78

Assigning to @rileyajones for experimentation when time permits.
