### ISSUE TITLE
The attribute '[href]' may not appear in tag 'A (AMP4EMAIL)'.

### ISSUE THREAD

**Issue by ChrisThorn10** [ampproject/amphtml#24003]
## What's the issue?
I am using `amp-bind` to update the href attribute of an anchor, however, I am getting an error message when input my code into amp.gmail.dev/playground. According to the documentation at https://amp.dev/documentation/components/amp-bind/?format=email#element-specific-attributes [href] is a valid attribute to use with binding.

## Briefly describe the bug.
When I input code with binding on the href attribute of an anchor tag I get an error message that reads "The attribute '[href]' may not appear in tag 'A (AMP4EMAIL)'. "

## How do we reproduce the issue?
Take this gist: https://gist.github.com/ChrisThorn10/7e0e0b5c5b717a8c3159879480b2f1b8
and paste it into the playground at amp.gmail.dev/playground

You will see the error message.  Once you remove `[href]="'https://www.lendingtree.com?' + recommendedProduct[currentProduct].buttonUrl"` from line 295 the code will render correctly.

## What browsers are affected? 
Not a browser specific issue

## Which AMP version is affected? 
AMP4EMAIL

**Comment by choumx** [comment]
Ah, so binding to `a[href]` is actually not allowed in AMP4EMAIL but the amp-bind documentation does not update when a different format is selected.

**Comment by choumx** [comment]
@fstanis Do we have docs that specify which bindings are allowed in AMP4EMAIL? Also, is it possible to have "if (isFormat(email))` conditionals in component docs?

**Comment by fstanis** [comment]
Yes, the [AMP for Email Supported Components](https://amp.dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-components/?format=email) lists bindings are (not) allowed in emails.

ampproject/amp.dev#2745 is the tracking issue to integrate that with the component documentation, so I'll close this in favor of that.
