### ISSUE TITLE
Send same event as "prerender complete" as semantic event to viewer.

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2400]
CC @alf7 for coordination on the event name.

**Comment by erwinmombay** [comment]
@alf7 you ok with "prerenderComplete" ?

**Comment by alf7** [comment]
SGTM! Thanks Erwin.

**Comment by rudygalfi** [comment]
@erwinmombay Have you started on this yet? Trying to figure out when to slot it...

**Comment by erwinmombay** [comment]
@rudygalfi i have, will submit pr shortly.
