### ISSUE TITLE
I2I: "Snowplow V2" amp-analytics vendor

### ISSUE THREAD

**Issue by max-tgam** [ampproject/amphtml#24006]
# Summary
Current snowplow tracker provides a very limited functionality that does not meet modern analytics requirements. The changes needed for that would not be backward-compatible for  anyone running current snowplow tracker. As a result new tracker version is required.

## Design document
This implementation will closely follow Snowplow's [Canonical Event Model](https://github.com/snowplow/snowplow/wiki/canonical-event-model) and [Tracker Protocol](https://github.com/snowplow/snowplow/wiki/snowplow-tracker-protocol)

## Motivation
Current snowplow tracker provides a very limited functionality that does not meet modern analytics requirements. The changes needed for that would not be backward-compatible for  anyone running current snowplow tracker.

## Additional context
Specific focus of this work is as follows:
- Improve visitor and visit tracking 
- Make Page View tracking automatic
- Add automatic Page Ping tracking
- Add Link Click tracking
- Add tracking for Self Describing Events
- Add Custom Contexts

/cc. @ampproject/wg-approvers

**Comment by micajuine-ho** [comment]
closed by #26059
