### ISSUE TITLE
Create hover event for all elements

### ISSUE THREAD

**Issue by morsssss** [ampproject/amphtml#24008]
Creating a tooltip feature for amp.dev, I realized, to my surprise, that AMP has no `hover` event. `tap`, yes... but not `hover`.

Of course, we can create this tooltip with pure CSS, but, if it would be simple, would you consider adding `hover` to AMP?

**Comment by nainar** [comment]
cc @ampproject/wg-ui-and-a11y @cathyxz @sparhami (since I have been talking with them about this as well.)

What do you all think? 

I agree that this is important. Specially since we can do a lot more  for a11y if this component is baked in like making sure the tap and hover action don't do different things.

**Comment by sparhami** [comment]
I know that custom tooltips are generally not accessible and I'm not sure there is a way to make them accessible in general. I think having a way of customizing how the `title` attributes render as a tooltip would be fine, but anything other than that seems questionable.

I think we should first discuss this with some accessibility experts before we even consider a feature here (either hover or a more restricted tootlip). It isn't clear to me that we should implement anything here.

**Comment by alanorozco** [comment]
A `hover` event wouldn't be very useful for displaying a tooltip, anyway. We can't guarantee that a change via `bind` or otherwise wouldn't cause content to shift so we can't qualify `hover` as a trusted user interaction for mutations.

**Comment by morsssss** [comment]
I see the point about accessibility!

If accessibility is an issue, I could see why we wouldn't want to allow use of `hover`. On the other hand, if `hover` might sometimes produce an undesired effect if content had moved, I'd still think we should allow `hover`. I'd think we should trust developers to try it out and see if it worked for their use cases! Otherwise, we're simply restricting everyone from using a basic browser event. And I think that makes developers resent AMP.

**Comment by cathyxz** [comment]
Related: https://github.com/ampproject/amphtml/issues/23222.

**Comment by erwinmombay** [comment]
could this be tied to a hover analytics event as well?

**Comment by AndrewKGuan** [comment]
+1 on this FR

**Comment by alanorozco** [comment]
Important point: cannot do DOM mutations without explicit user interaction (a hover action is not considered this type of interaction under our definition, this is to avoid reflows/content shifting.)

We could make a `hover` event low-trust, but that would limit its functionality. I don't think the use case described here can be handled by a low-trust event (hence without mutations).

**Comment by pierlon** [comment]
In the context of a navigation menu sub-menu that appears on hover, it would be great if there was a `hover` event to allow for the `aria-expanded` attribute to be toggled based on user interaction, for example.
