### ISSUE TITLE
🌸 Cherry pick request for #24017 into #23939 (Approved)

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#24020]
# Cherry-pick request

| Issue | PR  | Production? | RC? | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---: | :-: | :---------: | :-: | :-----------: |
| #24017 | #24013 | **YES** | **YES** | #23939 #23822 |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

Some AMP Story-specific analytics events aren't being logged, in particular in the first page. This is messing with critical metrics for publishers. For example: bounce rates, completion rates, story progress...

# Mini-postmortem

Early analytic events (e.g. story-page-visible when visiting the first page) weren't being logged correctly since the amp-analytics service wasn't being initialized on time to handle these events properly.

This has been happening since #23030 was pushed; as it stopped buffering early events and delaying their handling.

## Summary

Due to a [change](https://github.com/ampproject/amphtml/pull/23030) where we stopped waiting for the `<amp-analytics>` service to be up before handling the events.

| Users affected | Impact |
| -------------- | ------ |
| <_Which users were affected? Roughly how many?_> | <_How were users affected? E.g. partial or complete loss of functionality?_> |

## Root Causes

1. #23030

## Action Items

| Action Item | Type | Owner | PR # |
| ----------- | :--: | :---: | :--: |
| Add integration tests | Prevent | @Enriqe | #24310 |

## Lessons Learned

* We need integration / e2e tests for analytics.
* We need to monitor our dashboards more often.

### Things that went well

* Not all analytics events were affected.

### Things that went wrong

* The issue went unnoticed for a month. We only noticed from a report. 

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by dvoytenko** [comment]
Approved.

**Comment by dvoytenko** [comment]
Back to @Enriqe for postmortem.

**Comment by Enriqe** [comment]
Filled out PM and next steps to prevent this type of issue in the future. Closing, but feel free to re-open if I missed something.
