### ISSUE TITLE
Make test-amp-ad-doubleclick.js support glade based injection

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2402]
We should probably run this test 2x forcing the 2 modes.

CC @bobcassels
CC @kashyapnitin

**Comment by cramforce** [comment]
#2404 forces the test to always use GPT

**Comment by rudygalfi** [comment]
Any updates here?

**Comment by bobcassels** [comment]
I have a change that runs the test twice, one with glade and once once without.

But I for me, the original test fails (in an unmodified copy of the current master), so of course my new version does, too.

**Comment by jridgewell** [comment]
It's a very flaky test. Please open a PR, and we'll see what we can do to make it more consistent.

**Comment by bobcassels** [comment]
PR for my change, untested? I'm happy to do that. I can check that it fails the same way as the original. ;-)

**Comment by bobcassels** [comment]
Or are you asking me to open an issue that the existing test doesn't work?

**Comment by jridgewell** [comment]
@bobcassels: Open an issue with the test that doesn't work.

**Comment by rudygalfi** [comment]
Rolling this into next milestone.

**Comment by ericlindley-g** [comment]
Any updates on this?

**Comment by rudygalfi** [comment]
Rolling forward into next milestone. @bobcassels let me know if you don't think you can get to this in the next two weeks.

**Comment by ericlindley-g** [comment]
Rolling into the next milestone

**Comment by jasti** [comment]
ping @bobcassels  and @ampproject/a4a team.

**Comment by tdrl** [comment]
I'm late to the game on this.  What's the issue here?

**Comment by jasti** [comment]
@jridgewell Can you comment please?

**Comment by jridgewell** [comment]
We want to test DoubleClick in glade mode.

Re: https://github.com/ampproject/amphtml/pull/2404/files, which forces our tests to use GPT mode.

**Comment by jasti** [comment]
Since there is no active development happening on glade or GPT, closing this. Please consider if we need this for the A4A code path or reopen.
