### ISSUE TITLE
Is the dynamic amp page indexed on google?

### ISSUE THREAD

**Issue by shotaws** [ampproject/amphtml#24032]
## What's the issue?

We know the static pages are indexed on Google. 
I want to know how the dynamic page is indexed on Google when the page url is "http://testAMP.html?index=12345, " for example.

**Comment by choumx** [comment]
I believe URLs with query params are not treated differently. Let us know if you have a test case showing otherwise.

**Comment by shotaws** [comment]
@choumx 
Thank you for answering my question.

Now I know the static and dynamic pages are indexed on Google through the above answer.
I have a question about more deep things, how the behaviors of the URL are.
For example, if the URL is http://test.web-site.com/?query=hoge, which is indexed on Google, http://test.web-site.com/ or http://test.web-site.com/?query=hoge ?
