### ISSUE TITLE
Pre-connecting origin domain(s) and potentially prefetching outbound clicks

### ISSUE THREAD

**Issue by AndrewKGuan** [ampproject/amphtml#24043]
Wouldn't it make sense to preconnect the origin domain and other subdomains while a user is on a cached amp served from ampproject.org?

For example, add a <link rel=preconnect href="example.com"> inside the source code of an AMP during the transformation process.

Perhaps the AMP runtime could do something like that after the page is done loading? Better yet, if some automatic preloading of the next page can be done heuristically, that would help smoothen the gap between AMP->canonical site?

**Comment by cramforce** [comment]
Should be implemented as a startup behavior for the preconnect service connecting to the underlying origin and the canonical origin.
Additionally `amp-form` should probably connect to its destination.
