### ISSUE TITLE
[id] clobbers AMP globals

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#24051]
We currently blacklist `[id]` values that clobber DOM APIs: https://github.com/ampproject/amphtml/blob/0c5e03f962ebee782476a0da9f68600ba92c3cc1/validator/validator-main.protoascii#L6377-L6500

But we don't blacklist custom AMP globals that are set on the window by AMP JS, e.g. https://github.com/ampproject/amphtml/blob/0c5e03f962ebee782476a0da9f68600ba92c3cc1/src/mode.js#L55

The following AMP globals are added on a minimal AMP page after startup: 
```
AMPErrors
AMP_CONFIG
AMP_MODE
AMP_TAG
BaseCustomElementClass
UrlCache
__AMP_TOP
__AMP__EXPERIMENT_TOGGLES
ampExtendedElements
reportError
services
```

Some extensions also set globals -- the same survey done on `examples/article.amp.html` yields:
```
3pla
AMPErrors
AMP_CONFIG
AMP_FAST_FETCH_SIGNATURE_VERIFIER_
AMP_MODE
AMP_TAG
BaseCustomElementClass
UrlCache
__AMP_TOP
__AMP__EXPERIMENT_TOGGLES
ampAdGoogleIfiCounter
ampAdPageCorrelator
ampAdSlotIdCounter
ampExtendedElements
defaultBootstrapSubDomain
experimentBranches
gaGlobal
goog_identity_prom
listeningFors
log
reportError
services
```

Short-term, we can blacklist the minimal set of AMP globals. This may break some pages due to generic names like "services".

Long-term, it would be nice to migrate all custom AMP globals to the same prefix (e.g. `__AMP_`) and blacklist that prefix. Then introduce a presubmit that checks that assignment operations of the form `win.foo = bar` obey the prefix rule.

See `b/139534623` for more context.

**Comment by choumx** [comment]
This issue should be mostly resolved now. The following globals were renamed:
```
AMPErrors
AMP_MODE
AMP_TAG
BaseCustomElementClass
UrlCache
ampExtendedElements
defaultBootstrapSubDomain
experimentBranches
log
reportError
services
```

`AMP_CONFIG` is a non-issue since the first line of `v0.js` sets it unconditionally.

The new lint rule only checks files in `src/` for now. In a local test, it reports the following errors in `extensions/`:

```
[15:18:39] extensions/amp-a4a/0.1/amp-a4a.js
  2018:6  error  Window property "AMP_FAST_FETCH_SIGNATURE_VERIFIER_" should be prefixed with "__AMP_"  local/window-property-name

[15:18:40] extensions/amp-a4a/0.1/cryptographic-validator.js
  38:8  error  Window property "AMP_FAST_FETCH_SIGNATURE_VERIFIER_" should be prefixed with "__AMP_"  local/window-property-name

[15:18:43] extensions/amp-ad/0.1/concurrent-load.js
  79:5  error  Window property "3pla" should be prefixed with "__AMP_"  local/window-property-name

[15:18:54] extensions/amp-date-picker/0.1/react-utils.js
  38:5  error  Window property "state" should be prefixed with "__AMP_"  local/window-property-name

[15:18:56] extensions/amp-form/0.1/form-proxy.js
  65:5  error  Window property "FormProxy" should be prefixed with "__AMP_"  local/window-property-name

[15:19:16] extensions/amp-web-push/0.1/amp-web-push-helper-frame.js
  414:3  error  Window property "_ampWebPushHelperFrame" should be prefixed with "__AMP_"  local/window-property-name

[15:19:17] extensions/amp-web-push/0.1/amp-web-push-permission-dialog.js
  277:3  error  Window property "_ampWebPushPermissionDialog" should be prefixed with "__AMP_"  local/window-property-name

[15:20:17] extensions/amp-viewer-integration/0.1/examples/amp-viewer-host.js
  190:1  error  Window property "AmpViewerHost" should be prefixed with "__AMP_"  local/window-property-name
```

Note the linter is imperfect and may be missing some globals and have false positives.

**Comment by Gregable** [comment]
My understanding is that this is fixed. Please reopen if I misunderstand.
