### ISSUE TITLE
amp-consent: Support ConsentManager CMP

### ISSUE THREAD

**Issue by janwinkler** [ampproject/amphtml#24068]
Hello,

on https://github.com/ampproject/amphtml/blob/master/extensions/amp-consent/amp-consent.md and https://amp.dev/documentation/components/amp-consent/ is a list of "Supported Consent Management Platforms" that currently only lists Didomi. Please add consentmanager.net CMP to the list (see https://help.consentmanager.net/books/cmp/page/using-the-cmp-with-amp-websites).

Thank you!

Best regards,
Jan

**Comment by micajuine-ho** [comment]
Hi @janwinkler, thank you for your request.

We are happy to get started on integrating ConsentManager.net to our list of CMPs. 

Please refer to the [integration documentation](https://github.com/ampproject/amphtml/blob/master/extensions/amp-consent/integrating-consent.md) and #26040 as an example PR, and when you're ready, create a new PR with the required changes and we will look through them.
