### ISSUE TITLE
Updates tests to use async/await for readability

### ISSUE THREAD

**Issue by wassgha** [ampproject/amphtml#24076]

**Comment by rsimha** [comment]
This is definitely a worthwhile effort, but I don't see a way in which wg-infra can update 10,000+ unit tests and hundreds of integration tests.

I'm tagging the other working groups so they can triage / prioritize.

**Comment by samouri** [comment]
I support this issue, but I'm not sure it belongs as an issue.  It isn't high enough priority for anyone to take on single handedly as well as it is difficult to know when it is "done". 

In an effort to clean up the repo, i'm closing but feel free to reopen if you disagree! 

Thanks,
Jake
