### ISSUE TITLE
amp-viewer-integration-0.1.js:30 [Intervention] Ignored attempt to cancel a touchmove event with cancelable=false

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#24087]
## What's the issue?
`[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.` issue appears when swiping through articles

Briefly describe the bug.
amp-viewer-integration-0.1.js:30 issue when swiping between articles.

## How do we reproduce the issue?

1. Opt into Canary/RC
2. Open JavaScript Console
3. Search for something in Google Search (I chose Trump)
4. Select an Amp article (I chose [link](https://www.google.com/amp/s/www.nytimes.com/2019/08/20/us/politics/trump-economy-recession-data.amp.html))
5. Swipe between different articles 

## What browsers are affected?
macOSX Chrome Version: 76.0.3809.100
Doesn't seem to be reproducible on FireFox 68.0.2

## Which AMP version is affected?
Stable: 1908162134430

Video of Repro: https://drive.google.com/open?id=17vzmqTjWPDy6IngqU6P9Xy9_qsrHngNp

**Comment by lannka** [comment]
Same issue appeared on current prod: 1908162035200
