### ISSUE TITLE
doc: Missing I2I instructions in CONTRIBUTING.md

### ISSUE THREAD

**Issue by tobie** [ampproject/amphtml#24083]
## What's the issue?

This is a documentation issue.

The [I2I issue template](https://github.com/ampproject/amphtml/edit/master/.github/ISSUE_TEMPLATE/intent-to-implement--i2i-.md) references [CONTRIBUTING.md](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md) for how to fill-up the I2I template, yet there's no reference to I2I in CONTRIBUTING.md.

/cc @nainar

**Comment by jaherche** [comment]
I believe I understand and I'd like to attempt to fix this. (This will only be my second PR ever, if I am successful.)
