### ISSUE TITLE
rel="stylesheet" s set to the invalid value

### ISSUE THREAD

**Issue by moderactif** [ampproject/amphtml#2409]
Hello,

I have a css page linked as following:
`<link  rel="stylesheet" href="https://www.mydomain.com/bootstrap/bootstrap.min.css">`

but the validator.js reports me this error:

> The attribute 'href' in tag 'link rel=stylesheet for fonts' is set to the invalid value 'https://www.mydomain.com/bootstrap/bootstrap.min.css'. (see https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#custom-fonts)

How can I solve?

**Comment by luixxiul** [comment]
https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#author-stylesheets
> Authors may add custom styles to a document using a single `<style amp-custom>` tag in the head of the document.

**Comment by jridgewell** [comment]
Correct. You can't include an external stylesheet (unless it's to pre-approved Font vendors). You can include a [single inline stylesheet](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#author-stylesheets):

```html
<head>
  <!-- ... -->
  <style amp-custom>
    body {
      color: black;
    }
  </style>
<!-- ... -->
