### ISSUE TITLE
Make contributing guidelines more detailed

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#241]
This is mostly for new features such as new custom elements. We only want to support these if the feature impacts a significant subset of our (future :) user base.

Before starting a new element or making significant changes an "Intent-to-implement" Github issue should be created for discussion.

2 LGTMs from core team members are required to proceed.

We need to define criteria for inclusion. Having an oembed is an important signal. Having a wikipedia page about the thing being integrated is another one.

Then before shipping the feature and "Intent-to-ship" issue should be opened. Again 2 LGTMs from core team members are required to proceed.

@jmadler interested in taking this?

**Comment by erwinmombay** [comment]
has this been satisfied?
