### ISSUE TITLE
Introduce a proper task abstraction in AMP

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#24109]
We currently have `Chunk` and `Pass` (at least). Chunk has many but not all features we need.

- Pass should be replace with Chunk
- Chunk should gain features that make it work better at "runtime". It was primarily designed for startup. This might be just a rename of `startupTask` to `task` :)
- Chunk has a priority queue, but doesn't expose it. This needs to change.
- Chunk should align with the platform scheduler proposals
- One big question is if vsync should align with chunks.

CC @jridgewell

**Comment by jridgewell** [comment]
> isInputPending cannot be polyfilled. But, yeah, we basically want to debounce our work queues if isInputPending is true.

It's doesn't have to be a true polyfill, just an approximation.

```js
let lastCheck = 0;
let frameStart = 0;

/**
 * Gives up the thread every 16ms.
 * This must be called at least twice in a single frame before we'll return true.
 */
function isInputPending(unusedEvents) {
  const now = Date.now();
  const framesDelta = now - frameStart;
  const delta = lastCheck - frameStart;

  lastCheck = now;

  // If we're not in the same frame, we can't be in a for-loop.
  // Note, this can be tricked if the for-loop takes longer than 16ms to
  // complete. We could schedule a macro-task to clear state, which would
  // remove the need for frame checking (it'd be event-loop check instead).
  if (framesDelta >= 16) {
    frameStart = now;
    return false;
  }

  // If we've checked consecutively for 15ms, we've run out of time in the
  // frame.
  if (delta >= 15) {
    return true;
  }

  return false;
}
```

This is approximately what `Resources` uses to test if we've done too much work.

**Comment by cramforce** [comment]
This is basically implemented here https://github.com/ampproject/amphtml/blob/master/src/chunk.js#L464

That implementation can, of course, be improved. Especially being unaware of vsync disallows good judgement of how much time there is left.

**Comment by cramforce** [comment]
I'd like to only have one taskqueue for AMP. Would probably be good to have
a "white board" session in person.

**Comment by samouri** [comment]
Commenting here to note a third task abstraction at `src/service/task-queue.js`.

**Comment by choumx** [comment]
Adding a note that a single task scheduler is needed for trying out [`scheduler.postTask`](https://github.com/WICG/main-thread-scheduling/blob/master/PrioritizedPostTask.md) API in AMP. Origin trial slated for [Chrome 82-84](https://github.com/WICG/main-thread-scheduling/blob/master/OriginTrialStatus.md).
