### ISSUE TITLE
Intent to implement - Springboard player embed code

### ISSUE THREAD

**Issue by Em-PredragMilosevic** [ampproject/amphtml#2410]
This proposed <code>&lt;amp-springboard&gt;</code> component would enable video playback in AMP pages using a Springboard video player. This component will be used by publishers using <a href="http://home.springboardplatform.com/">Springboard Video Platform</a> services.

Attributes specifying the publisher (partner), player and content id's determine the embed iframe url that will be used. All assets are loaded from an HTTPS location on Springboard content servers. An embedded iframe would be used.

Embed code example:

<pre>
<code>
&lt;amp-springboard
      data-site-id="261"
      data-mode="video"
      data-content-id="1578473"
      data-player-id="test401"
      data-domain="test.com"
      data-items="10"
      layout="responsive" width="480" height="270"&gt;
&lt;/amp-springboard&gt;
</code>
</pre>

This embed code would create an iframe with the following URL:
<a href="https://cms.springboardplatform.com/embed_iframe/261/video/1578473/test401/test.com/10">https://cms.springboardplatform.com/embed_iframe/261/video/1578473/test401/test.com/10</a>

The component supports a pause postMessage event to pause the video.

You can find all details in <a href="https://github.com/Em-PredragMilosevic/amphtml">repo</a>.

Thanks,
Predrag Milosevic

**Comment by cramforce** [comment]
LGTM.

Lets make it `amp-springboard-player`

**Comment by Em-PredragMilosevic** [comment]
Changed to <code>amp-springboard-player</code>.

Can I create pull request now?

**Comment by jridgewell** [comment]
> Can I create pull request now?

Yup. :smile:

**Comment by Em-PredragMilosevic** [comment]
Hi,

Can anybody take a look at my <a href="https://github.com/ampproject/amphtml/pull/2467">pull request</a>?

Thanks

**Comment by mkhatib** [comment]
Thanks @Em-PredragMilosevic - merged!
