### ISSUE TITLE
How to add ecwid store (custom tag give by ecwid ) in Amp pages?

### ISSUE THREAD

**Issue by gagan1910** [ampproject/amphtml#24101]
## Describe alternatives you've considered

Provide a clear and concise description of any alternative solutions or features you've considered.

**Comment by gagan1910** [comment]
Any suggestions?

**Comment by choumx** [comment]
This FR is a bit too vague to be actionable. Do you mean the Ecwid embed as suggested here? https://support.ecwid.com/hc/en-us/articles/115004678945-Your-Ecwid-store-on-any-website

Embeds that include 3P JS must be iframed in AMP pages, so give [amp-iframe](https://amp.dev/documentation/components/amp-iframe/) a try.
