### ISSUE TITLE
New amp-accordion headings error?

### ISSUE THREAD

**Issue by pstricker** [ampproject/amphtml#24118]
## What's the issue?

We have begun seeing a new error show up in the console that reads "amp-accordion headings should not have tap actions registered." for every use of the amp-accordion component on a page.

We have not modified this markup for quite some time so we are having difficulty troubleshooting the new error.

In looking at each use of amp-accordion, we also can not identify any tap actions being registered.

## How do we reproduce the issue?

1. Open https://www.google.com/amp/s/www.ebags.com/amp/product/tumi/cfx-bayview-travel-duffel/365912
2. View errors listed in the console.

## What browsers are affected?

This appears to be across browsers and device type.

## Which AMP version is affected?

This appears to be a new issue.
Version 1908162134430

**Comment by creativefold** [comment]
I am also facing the same issue on an AMP based website. How do we fix this issue?

**Comment by buihoanghai** [comment]
![image](https://user-images.githubusercontent.com/6602376/63481677-cb033880-c4c8-11e9-8f1a-d768bdcc04b3.png)
I think the temporary solution is set the color for these sections first. asleast users still see texts

**Comment by stephensaw** [comment]
The issue seems like it's because amp-accordion doesn't allow to have tap event on the header. However after removed the tap event from header still failing for me.

Seems like the `findAction` is doing a loop for each of the parentElement, after removing the tap on my parent element it seems to be working. Why is the function not scoped at the accordion component only?

**Comment by BurakDev** [comment]
According to #23264 , bad use of hasAction method, third parameter should be the header element to prevent checking tap presence on all parents divs. @sparhami @cathyxz Is planned to do an emergency release or anything ? If not, we will have to remove all tap on parents elements.
