### ISSUE TITLE
🌸 Cherry-pick request for #24112 into #1908201719490  (Approved)

### ISSUE THREAD

**Issue by kristoferbaxter** [ampproject/amphtml#24114]
# Cherry-pick request

| Issue | PR  | Production? | RC? | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---: | :-: | :---------: | :-: | :-----------: |
| #24112 | #24108 | **NO** | **YES** | #24086 |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

This change is prohibiting the data capture for changes to address first input delay slowness on complex AMP documents.

# Mini-postmortem

The author of the change (me) was mistakenly under the impression that url level opt-ins were automatically promoted to production releases with the subsequent release of AMP following a successful canary.

## Summary

AMP documents queue up `startupTasks` purely using micro tasks, which can delay the first response to user input since a device continues to process the micro task queue before having a chance to respond to user input.

This change enables a URL level opt-in to gather metrics for a change that moves from continuing micro task processing to bailing out the remaining micro tasks until the next macro task. The bailout conditions are described in [chunk.js](https://github.com/ampproject/amphtml/blob/master/src/chunk.js#L458). 

| Users affected | Impact |
| -------------- | ------ |
| Performance Capture Tools | No loss of functionality |

## Root Causes

1. URL level opt-in added to canary configuration, but not production configuration.

## Action Items

| Action Item | Type | Owner | PR # |
| ----------- | :--: | :---: | :--: |
| Update Developer Documentation | Mitigate | @kristoferbaxter | #24108 |

## Lessons Learned

Experiment URL opt-ins should be added to production configurations manually following successful canary results.

### Things that went well

- No impact to end user behaviour or document performance.

### Things that went wrong

- Loss of crucial data for a significant change to the startup routine for AMP documents.

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by jridgewell** [comment]
I don't think this qualifies as a prod cherry-pick, since nothing is actually breaking? It's just an experiment that'll have to wait another week to start.

**Comment by cramforce** [comment]
Yeah, since this is a zero-risk change we can do it, of course. But maybe should wait for another cherry-pick instead of doing one right now.

**Comment by kristoferbaxter** [comment]
Makes sense to wait for another change, thank you.

**Comment by lannka** [comment]
Updated title with the RC release RTV

**Comment by lannka** [comment]
So I assume this is approved for a canary/RC cherrypick.

**Comment by lannka** [comment]
cherrypick done, it's in canary opt-in now.
