### ISSUE TITLE
`macro-after-long-task` experiment only available in canary

### ISSUE THREAD

**Issue by kristoferbaxter** [ampproject/amphtml#24112]
## What's the issue?

The `macro-after-long-task` experiment is only available in canary, and is missing from production.

## How do we reproduce the issue?

Load any AMP document with an additional parameter (`e-macro-after-long-task`) and observe the number of macro tasks during startup, on a canary build versus production build the number will vary. This increase in macro tasks is designed to reduce first input delay.

## What browsers are affected?

All browsers.

## Which AMP version is affected?

1908150025400

**Comment by choumx** [comment]
Looks like this was fixed in #24108.
