### ISSUE TITLE
AMP issue with filter/menu on chrome and iOs

### ISSUE THREAD

**Issue by KarlBigL** [ampproject/amphtml#24139]
## What's the issue?

The problem appeared on iOS and chrome. 
Open google, search and open an AMP page, press/open a menu/filter, do nothing and close. It doesn't close the menu/filter but returns you to google search.

## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. iOS (12.4) and Chrome (Version 76.0.3809.100 (Official Build) (64-bit)
), open google.com.
2. Google for an AMP page, click and do nothing.
3. open menu/filter, do nothing.
4. close menu/filter.

## What browsers are affected?

Chrome, iOS devices.

**Comment by choumx** [comment]
@KarlBigL Can you share a URL with this issue?
