### ISSUE TITLE
Whitelist Font Awesome

### ISSUE THREAD

**Issue by tagliala** [ampproject/amphtml#2413]
Hi,

What is your position about icon fonts? Is there any chance of whitelisting a CDN serving icon fonts?

Refers to: https://github.com/FortAwesome/Font-Awesome/issues/8662

Regards

**Comment by rudygalfi** [comment]
@cramforce Can we do this? What kind of additional information do we need?

**Comment by cramforce** [comment]
We can. The requirements are:

- CSS only integration
- serving over HTTPS

**Comment by fabianpimminger** [comment]
So the requirements for fontawesome (https://fortawesome.github.io/Font-Awesome/get-started/) should be satisfied, or am I missing something?

**Comment by tagliala** [comment]
The above cdn also contents which are not fonts, e.g.:
```
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js
```

Is this an issue?

**Comment by cramforce** [comment]
Looks good. So we'd whitelist

`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/$VERSION/css/font-awesome.min.css">`

Or just https://maxcdn.bootstrapcdn.com/font-awesome/ as a prefix.

**Comment by nicholasgriffintn** [comment]
It would be awesome if you could do this, font awesome is great for icons. Fort Awesome (formally font icons) integration would also be awesome.

**Comment by tagliala** [comment]
@nicholasgriffintn unfortunately Fort Awesome uses javascript integration. At the moment it could not be whitelisted. I will ask Dave if there are plans to support .css only integration too

**Comment by nicholasgriffintn** [comment]
Yeah I did think that, however, they might be willing to work with AMP to make a CSS integration.

**Comment by Gregable** [comment]
This change is live everywhere. Please reopen if you spot any issues.

**Comment by codersaiful** [comment]
issue found....

**Comment by AndersDK12** [comment]
It seems https://pro.fontawesome.com is not whitelisted. Could you confirm, and whitelist asap? Thanks.

**Comment by AndersDK12** [comment]
On a second note, this is attached to a specific domain, so I assume it won't work when loaded through Google AMP?

**Comment by cramforce** [comment]
You mean that the response is limited to a certain referrer? You'd need to whitelist the AMP Cache domains.

**Comment by AndersDK12** [comment]
> You mean that the response is limited to a certain referrer? You'd need to whitelist the AMP Cache domains.

Yes. I came to the same conclusion yesterday, and did just that. By AMP cache domains, you mean www.google.com, www.google.se etc, right?

Apparrently this seems to be a problem for Font awesome (FA), as I did add the different Google domains, but the FA resource still responds with a 403 error (forbidden). I have asked the FA team to look into it, and they will. I also suggested that they always whitelist Google domains.

Will update this, when i have more from FA team.

**Comment by AndersDK12** [comment]
Seems you need to whitelist <domain>.cdn.ampproject.org

**Comment by cramforce** [comment]
Correct on the latter. The Google domains don't need to be whitelisted.
This list has the full list of AMP Caches, although currently Microsoft is still missing
https://github.com/ampproject/amphtml/blob/master/caches.json

CC @ssantosms
