### ISSUE TITLE
Create templates for documents needed in I2I

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#24132]
- [ ] PRD
- [ ] User Research
- [ ] Design Doc
- [ ] UX Interaction Spec
- [ ] Accessibility Review
- [ ] Security Review
- [ ] Privacy Review
- [ ] Internationalization Review

**Comment by tobie** [comment]
See my comments in https://github.com/ampproject/amphtml/pull/24072#issuecomment-523377725.
