### ISSUE TITLE
[DX] Lazily build JS binaries for default gulp task

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#24141]
- block web server startup by nothing
- maybe eagerly build core runtime
- register a URL handler in the web server that does the following:
  - If the path points to a a file we could build
  - build the file now,
  - and when that is done respond with the result
- If the watcher rebuilds a file, behave like above, so that the next reload on the client always gets a fresh file.
- That way we'd have quick startup and would just lazily build extensions as they are actually requested.

Known issues of current implementation:

- Not all command line flags may be passed down to building and serving process

**Comment by rsimha** [comment]
> Not all command line flags may be passed down to building and serving process

Solved by #24325.
