### ISSUE TITLE
Shall we change --with_shadow to --noshadow

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#24145]
also applies to --with_inabox 

reasons:
- comparing the 100+ extensions we have, compiling extra inabox & shadow runtime does not significantly increase compilation time
- easy to get ignored by first time contributor and then spending tons of time debugging on a local-only test failure (/cc @powerivq :-) )
- to be consistent with `gulp dist`, which compiles everything by default.

**Comment by powerivq** [comment]
Seconding that. With the number of methods to execute builds and tests, it is hard to keep track all of them.

**Comment by rsimha** [comment]
Why not remove the flags altogether and always build inabox and shadow runtime? If it doesn't affect the rest of the build, I'd be happy to approve a PR that removes both flags.

**Comment by lannka** [comment]
I can do the PR if you don't see a reason to not do it.
