### ISSUE TITLE
AMP-Story Auto Ads Support for Videonow Ad server

### ISSUE THREAD

**Issue by nixtka** [ampproject/amphtml#24156]
## What's the issue?

We (Videonow) want to be a supported ad-server for amp-story-auto-ads tag

## Context

Videonow Ad Server is supported by <amp-ad> (https://github.com/ampproject/amphtml/blob/master/ads/videonow.md) and now we almost developed a Viqeo Stories Studio to export AMP visual stories. And to support active production of AMP stories by Digital media Publishers, we would like to develop an option to monetise AMP Stories.

### More details

1. Monetisation — is an important part of Digital Media Business and AMP Stories mass usage by media publishers
2. Not all publishers have a Doubleclick to monetise stories (i.e. in Russia <20%)
3. Success of AMP pages depends, among other things, on the fact that Publishers can monetise pages with many different ways (with many ad-servers & formats) and unlike Facebook Instant Articles AMP pages are growing very fast
4. We are ready to render ads the way they should be rendered according to AMP Stories logic.
5. We are registered in #wg-stories Slack Channel, know how AMP Stories work and ready to develop features that support AMP Stories requirements.

**Comment by nixtka** [comment]
We are ready to implement similar behaviour to ads requests/responces:
https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad-network-doubleclick-impl/single-page-ad.md

**Comment by nixtka** [comment]
Hi guys!
Any chances to support external ad server? @newmuis , what is the best way we can do to move this further? We can do our best to move forward.

**Comment by newmuis** [comment]
I'm not sure of the details, but perhaps @jasti or@calebcordry would know

**Comment by nixtka** [comment]
@newmuis thanks for the info! @jasti , @calebcordry we would like to move forward with that. We've released our Viqeo.tv stories studio and wish to develop AMP Stories creation with Publishers, but not all of them have Ad Manager, and also we have video demand for stories from advertisers, so would be happy to support <amp-auto-ads> natively

**Comment by calebcordry** [comment]
@nixtka Great! We are excited by the possibility of more ad networks. Ads served into AMP stories must be [AMPHTML Ads](https://amp.dev/documentation/guides-and-tutorials/learn/intro-to-amphtml-ads/).  Perhaps the most straightforward option for your ad network to serve AMPHTML ads is to implement [template ads](https://docs.google.com/document/d/1nF1L_1rAn7I5culLX0_6HqQaCWTfmu0nHaYqwMbfnGI/edit#heading=h.ha73jvcfte12). 

Story ads also have a few additional requirements. You can read about some of the best practices [here](https://amp.dev/documentation/guides-and-tutorials/develop/story_ads_best_practices/).

Once you have the chance to review, let me know and we can schedule a meeting. Feel free to ping me with any questions. I am also on our slack channel as `@caleb`.

**Comment by nixtka** [comment]
@calebcordry thanks for the detailed info. As we support AMP Stories in our platform (example: https://amphtml.viqeo.tv/story?id=14) I think it won't be too hard to support required formats.
Just wanted to ask a permission for template ads — no access to file. And will add you in Slack, thank you!

**Comment by newmuis** [comment]
Just as a heads up: ads for stories do not use the same markup as the stories themselves.

**Comment by calebcordry** [comment]
@nixtka Sorry I sent you the old docs for template ads, please see updated link [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad-custom/amp-ad-custom.md)
