### ISSUE TITLE
How is the dynamic amp page indexed on google?

### ISSUE THREAD

**Issue by shotaws** [ampproject/amphtml#24159]
Now I know the static and dynamic pages are indexed on Google through https://github.com/ampproject/amphtml/issues/24032.
I have a question about more deep things, how the behaviors of the URL are.
For example, if the URL is http://test.web-site.com/?query=hoge, which is indexed on Google, http://test.web-site.com/ or http://test.web-site.com/?query=hoge ?

**Comment by choumx** [comment]
Closing as single party indexing behaviors are unrelated to AMP.
