### ISSUE TITLE
🌸 Cherry-pick request for #24142 into #23939 (Approved)

### ISSUE THREAD

**Issue by wassgha** [ampproject/amphtml#24151]
# Cherry-pick request

| Issue | PR  | Production? | RC? | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---: | :-: | :---------: | :-: | :-----------: |
| #24118 | #24142 | **YES** | **YES** | #23939  #24086 |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

Fixes an assertion that caused `amp-accordion` to break on multiple websites due to a scoping issue.

# Mini-postmortem

## Summary

Users reported that the `amp-accordion` component was breaking due to a misbehaving new rule that was supposed to prevent registering `tap` actions on the header element of each section of the accordion but was instead issuing errors for `tap` actions on *any* element above the section in the DOM tree.

| Users affected | Impact |
| -------------- | ------ |
| Users of `amp-accordion` who had any `on:tap` action on any element above the accordion in the DOM tree | Loss of interactivity on the `amp-accordion` element (unable to open/close sections), errors in the console and Google dev console |

## Root Causes

#23720 aimed to enforce a "working as intended" behavior by preventing binding `tap` actions to the header element of each `amp-accordion` section. Three main factors contributed to this breakage:
1. The scope of the check was not limited so the assertion was looking for `tap` events on any parent (up to the root of the DOM tree) instead of limiting the scope to the `amp-accordion`'s section. 
2. The enforcement of this behavior was implement as an `Error` as opposed to a `Warning` (which would have prevented the element from completely breaking but still caused multiple unwanted `warning` entries)
3. No integration tests were in place to verify the integration of the extension's action lookup with other elements on the page that might have `tap` actions.

## Action Items

| Action Item | Type | Owner | PR # |
| ----------- | :--: | :---: | :--: |
| Add an integration test that would've caught this issue  | Prevent | @cathyxz  | TBD |
| Check for other unscoped usages of `hasAction`  | Investigate | @sparhami   | TBD |
| Consider warning instead of erroring to enforce desired behavior | Investigate | @cathyxz  | TBD |

## Lessons Learned

- Warning instead of erroring on non-critical problems
- (I learned how to write a cherry-pick request!)

### Things that went well

- Cherry picking a PR from a community contributor (@BurakDev )!

<img src="https://user-images.githubusercontent.com/591655/63609354-e125fd00-c58b-11e9-8c1b-7bafecffe7a3.png" alt="I am so proud of this community" width="400" />

### Things that went wrong

- Took more than a day to detect and deploy the fix

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by cramforce** [comment]
Approved.

I'm a bit worried that the fix that have a test. Definitely prep a postmortem for this one.

**Comment by wassgha** [comment]
^ manually tested, but I agree @cathyxz maybe add a test to catch this case
Waiting on Travis to merge the PR

**Comment by lannka** [comment]
FYI, check picking prod

**Comment by lannka** [comment]
FYI, prod checkpick is out

**Comment by lannka** [comment]
FYI, cherry picking canary

**Comment by wassgha** [comment]
Added postmortem!

**Comment by lannka** [comment]
FYI, canary/RC cherrypick it out, closing this
