### ISSUE TITLE
Validator allows viewport units for intrinsic layout

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#24161]
It's currently valid to specify viewport units for intrinsic width and height:

```
<amp-img layout=intrinsic width=30vh height=20vh src="https://unsplash.it/400/300"></amp-img>
```

It doesn't work though (the image won't show) and doesn't really make sense in the case of the intrinsic layout.

Suggestion: don't allow vh / vw for intrinsic layout.

//cc @Gregable @choumx

**Comment by Gregable** [comment]
Is there more context for this being a common issue or such? There are numerous ways to create an `amp-img` that won't display, only some of which the validator could reasonably catch.

**Comment by Gregable** [comment]
Closing will not implement. To reopen, I'd like to see a stronger rationale for tightening the rules here.
