### ISSUE TITLE
CLIENT_ID not populating

### ISSUE THREAD

**Issue by dnicol** [ampproject/amphtml#2416]
I think there is an issue with CLIENT_ID getting populated. 

Example tag 

<amp-pixel src="https://bcp.crwdcntrl.net/5/c=931/tp=ADVI/tpid=CLIENT_ID(_cc_id,amp-user-notification1)/rand=RANDON/b=28348571"></amp-pixel>

The way I understood the docs is if I dont pass a fall back cookie id CLIENT_ID would generate and that should get replaced.

I suspect this only works when this is rendered in the GCDN?

**Comment by rudygalfi** [comment]
@dnicol Can you copy in the example tag?

**Comment by dnicol** [comment]
so sorry I thought I did

<amp-pixel src="https://bcp.crwdcntrl.net/5/c=931/tp=ADVI/tpid=CLIENT_ID(_cc_id,amp-user-notification1)/rand=RANDON/b=28348571"></amp-pixel>

https://cdn.ampproject.org/c/s/www-dev.nj.com/fed/dnicol/amp-lotame.html#development=1

**Comment by dnicol** [comment]
`<amp-pixel src="https://bcp.crwdcntrl.net/5/c=931/tp=ADVI/tpid=CLIENT_ID(_cc_id,amp-user-notification1)/rand=RANDON/b=28348571"></amp-pixel>
`

**Comment by cramforce** [comment]
There are 2 bugs

1. In your page, you need to include the extensions for `amp-user-notification` and `amp-analytics`
2. We don't yell at you for it.

**Comment by cramforce** [comment]
Filed #2418 for the bug on our end.

**Comment by dnicol** [comment]
cramforce Thanks, I included the two .js files for both of those extensions. Still a bunch of noise in the validation.js

**Comment by cramforce** [comment]
@dnicol Its not noise :)

**Comment by cramforce** [comment]
It seems to work now. Please note that the HTML returned by the AMP cache is not expected to validate.

**Comment by dnicol** [comment]
@cramforce  I actually dont see the pixel being dropped now. I see the amp-pixel tag in the source but the call out isnt happening now.

**Comment by cramforce** [comment]
@dnicol That is because your `<amp-user-notification` calls fail. Definitely publicly.

**Comment by dnicol** [comment]
Thanks its making sense now and working, at least I am getting the BASE 64 ID populating now.  Need to see why the cookie value Im declaring is not being picked up.

**Comment by dnicol** [comment]
I noticed that the base 64 value is being written into the cookie name I am specifying. The way I interpreted the docs was that the preexisting value of a cookie would be utilized as the CLIENT_ID  if specified.

**Comment by cramforce** [comment]
It will use the cookie only if present on your own site: http://www-dev.nj.com/fed/dnicol/amp-lotame.html#development=1
Not when accessed through cdn.ampproject.org

**Comment by rudygalfi** [comment]
Marking as closed since I think the most recent comment addressed the last issue. Please re-open if not.
