### ISSUE TITLE
 %id must have "sha384-%s" in meta[name="amp-script-src"] - amp-script error 

### ISSUE THREAD

**Issue by Stefany93** [ampproject/amphtml#24171]
## What's the issue?

 `%id must have "sha384-%s" in meta[name="amp-script-src"]` Error in the console after `amp-script` was launched. Before that, it worked great. 

![image](https://user-images.githubusercontent.com/2403939/63605281-3c0f2280-c593-11e9-8e26-8333932468f6.png)

## How do we reproduce the issue?
Code: 

```
<!-- Reference a local script by id via the "script" attribute. -->
<amp-script layout="container" script="hello-world">
  <button>Hello amp-script!</button>
</amp-script>

<script id="hello-world" type="text/plain" target="amp-script">
  const btn = document.querySelector('button');
  btn.addEventListener('click', () => {
    document.body.textContent += 'Hello World!';
  });
</script>

```

## Which AMP version is affected?

1908162134430

**Comment by Stefany93** [comment]
Also, the validator went nuts and it showing me a `Custom JavaScript is not allowed` error.

**Comment by honeybadgerdontcare** [comment]
@Stefany93 	unfortunately the custom script is not allowed yet. The [file](https://github.com/ampproject/amphtml/blob/master/extensions/amp-script/validator-amp-script.protoascii) states it is pending a security review. @kristoferbaxter as fyi.

**Comment by choumx** [comment]
I'll work on updating the documentation to include the required `meta` tag and improve the error message (fix string templating and include a link).

**Comment by Stefany93** [comment]
Thank you for the fast response.

**Comment by fstanis** [comment]
FYI: Tracking issue for documenting this is ampproject/amp.dev#2807

**Comment by adjieguntoro-tokped** [comment]
I'm facing the same issue, for now, I just copy-paste the sha384 from console to `<meta name="amp-script-src" />` whenever I change my script.

will follow this conversation and waiting for the update. 😄

**Comment by choumx** [comment]
#24242 should make the documentation and error messages clearer. Splitting the local script validation issue out into #24309.

**Comment by alamKhan1807** [comment]
What's the issue? and how to solve

<img width="1438" alt="Screen Shot 2019-09-13 at 12 39 32 PM" src="https://user-images.githubusercontent.com/53565186/64843854-d0fdbc80-d623-11e9-9c26-f9fc028740ef.png">

**Comment by choumx** [comment]
@alamKhan1807 That's just debug messaging. Can be ignored.

**Comment by alamKhan1807** [comment]
thank you @choumx  👍
