### ISSUE TITLE
Update Validator Chrome extension to show debug icon instead of error when in dev mode

### ISSUE THREAD

**Issue by westonruter** [ampproject/amphtml#24176]
In #20974 a new `data-ampdevmode` attribute was added which tells the validator to suppress reporting validation errors for elements it appears on, except for the root `html` element:

![image](https://user-images.githubusercontent.com/134745/63612066-2fd69580-c592-11e9-8b20-fff5621214c2.png)

In such case, however, when there is only one validation error and it is due to being in debug mode, it would be very useful if the Validator extension would not show an error icon but rather a debug icon, similar to how it shows a warning icon when there are deprecation issues.

If there are other validation errors other than the one `data-ampdevmode` on the root `html` element, then the Validator extension should continue to show the error icon.

By showing a debug icon, users won't get alarmed when the system is generating markup that is explicitly invalid for dev mode purposes.

Originally suggested in https://github.com/ampproject/amphtml/issues/20974#issuecomment-524403120.

**Comment by westonruter** [comment]
@honeybadgerdontcare When do you think this will be implemented? We're planning to release the next version of the WordPress AMP plugin in a couple weeks and it will have support for dev mode. We'll want to include an explanation of this mode and what users can expect when using the AMP validator extension. So having a sense of timing will help.

**Comment by honeybadgerdontcare** [comment]
I have no timeline for implementing this, there are other high priority items I'm working on.

**Comment by westonruter** [comment]
We are starting to get more AMP plugin user reports about this. For example: https://wordpress.org/support/topic/amp-dev-mode-error-with-amp-validator/
