### ISSUE TITLE
URL replacements should not log, but rather report to the user if replacement promise failed

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2418]
Currently those errors get eaten.

See https://github.com/ampproject/amphtml/blob/2dd024ddfabfe9d95803a409b1fe0d71d19fec6e/src/url-replacements.js#L389

**Comment by jridgewell** [comment]
What are you asking me to do? Just rethrow the error?

**Comment by cramforce** [comment]
Yeah, I think we want to maintain the property that we resolve the promise, but throw in a timeout.

**Comment by cramforce** [comment]
Taking this since Justin is out.
