### ISSUE TITLE
I2I: Lazy load non-render blocking services

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#24188]
- [ ]   18K installUrlReplacementsServiceForDoc(ampdoc);
- [ ]   10K installActionServiceForDoc(ampdoc);
- [ ]   8K installHistoryServiceForDoc(ampdoc);
- [ ]   6K built-ins (amp-img, amp-pixel, amp-layout)
- [ ]   5K installGlobalNavigationHandlerForDoc(ampdoc);
- [ ]   4K installStandardActionsForDoc(ampdoc);
- [ ]   4K install[Batched]XhrService(global);
- [ ]   2K installGlobalSubmitListenerForDoc(ampdoc);
- [ ]   2K installCryptoService(global);
- [ ]   2K installTemplatesService(global);
- [ ]   2K installInputService(global);
- [ ]   2K iframeMessagingClient
- [ ]   1K installAnchorClickInterceptor
- [ ]   1K installDocumentInfoServiceForDoc(ampdoc);
- [ ]   1K installHiddenObserverForDoc(ampdoc);

/cc @dvoytenko

**Comment by jpettitt** [comment]
I think `installUrlReplacementsServiceForDoc` is in the critical path for `amp-subscriptions` and `amp-access` entitlements checks.  Lazy load will delay the check which may lead to screen jank depending on where the publishers has put the cut between free and paid sections (IE is it in viewport).   I'm not sure is this is going to be an issue in the real world.
