### ISSUE TITLE
Validation Errors on http://pittsburghpaintsandstains81stg.ppgac.com/projects/accent-wall-paint-colors?amp=true

### ISSUE THREAD

**Issue by adjectivedevelopment** [ampproject/amphtml#2421]
I am using Microsoft MVC Razor Views to generate my html and it is replacing `<script async src="https://cdn.ampproject.org/v0.js"></script>
    <script async custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>` with `<script async="async" src="https://cdn.ampproject.org/v0.js" type="text/javascript"></script>
    <script async="async" custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js" type="text/javascript"></script>`, which is causing the validator to fail.  Is it possible to change the validator to look for a script tag with the right script reference rather than the exact string `<script async custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>`?  I cannot find a way to stop this markup normalization form happening.

**Comment by Gregable** [comment]
The issue is the additional unnecessary `type="text/javascript"` attribute. That seems fine to me to allow. I'll make the change.

**Comment by Gregable** [comment]
This change is live everywhere. Please reopen if you spot any issues.

**Comment by adjectivedevelopment** [comment]
Looks good to me, thanks!
