### ISSUE TITLE
Make extraUrlParams a substitution variable

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#2423]
This would support cases where you need the extra URL params to appear within the request rather than at its end.

Proposal would be: If the substitution is used in a request, then the normal behavior of appending the extra URL params is not done.

The `pageview` request in the example below might return (assume URLs or text are escaped properly):

`https://example.com/analytics?url=https://my-domain.com/my-page.html&title=PageTitle&acct=ABC123&a=1&b=2&ref=https://google.com`

``` html
<amp-analytics>
<script type="application/json">
{
  "requests": {
    "pageview":"https://example.com/analytics?url=${canonicalUrl}&title=${title}&acct=${account}${extraUrlParams}&ref=${documentReferrer}",
  },
  "vars": {
    "account": "ABC123",
  },
  "extraUrlParams": {
    "a": "1",
    "b": "2",
  },
  "triggers": {
    "someEvent": {
      "on": "visible",
      "request": "pageview",
      "vars": {
        "title": "My homepage",
      }
    }
  }  
}
</script>
</amp-analytics>
```

**Comment by avimehta** [comment]
Can you give a complete example config with results?

**Comment by rudygalfi** [comment]
@avimehta Updated the original post with a full example.

**Comment by rudygalfi** [comment]
@avimehta I'm slotting this into the upcoming milestone since I think you have work in progress on this in #3168. Can you confirm?
