### ISSUE TITLE
Make no-JS case valid

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#24232]
Let's consider making the following case valid AMP

- Document contains no runtime or extensions script elements or other script elements of type javascript.
- Document does not contain CSS boilerplate.

**Comment by honeybadgerdontcare** [comment]
This is a valid case that we should consider, avoiding stale bot.

**Comment by samouri** [comment]
@honeybadgerdontcare: is this difficult to implement? it seems like a good idea

**Comment by honeybadgerdontcare** [comment]
@samouri It's slightly complicated since it requires enforcing some rules but not others. It would require changes to both validator engines to work. Also need to verify that caches will insert the necessary script tags for it to work in the viewer.

Since we're anticipating retiring the native JavaScript implementation, I'd prefer to wait till that is complete before implementing this. Unless there's an urgent need for this?

**Comment by kristoferbaxter** [comment]
There isn't an urgent need, but it'd be great if we could slot it in after the native JavaScript version is retired.

**Comment by Gregable** [comment]
@kristoferbaxter Could you help, or suggest someone who could help, identify what parts of AMP should still require `v0.js` or the `<style amp-boilerplate>`?

I have the following dependencies:

 - Any `<script ... src="...amp-...js">` requires `v0.js`
 - `v0.js` requires the boilerplate
 - `<amp-img>` and `<amp-pixel>` require `v0.js` even though there is no matching `<script>` tag.

The last of these three was not previously identified in this issue, so I'm worried I might be missing more. It's straightforward to make the case @cramforce mentioned valid, but we need to make sure we don't make anything else valid that shouldn't be.

**Comment by kristoferbaxter** [comment]
Any Custom Element with an `amp-` prefix could safely be considered dependent on `v0.(m)js` or a future `v1.(m)js`.

**Comment by kristoferbaxter** [comment]
A good person to help get to a more authoritative list would be @jridgewell.

**Comment by samouri** [comment]
`amp-layout`, `amp-pixel`, and `amp-img` are the only three components considered "builtin". this means that their presence implies v0.m?js is necessary

**Comment by honeybadgerdontcare** [comment]
In progress, cl/392498113

**Comment by Gregable** [comment]
The no-js case is now valid, live everywhere.
