### ISSUE TITLE
Use different conformance config for amp-inabox-host.js binary

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#24234]
This is a good pattern to try out. If works - we could also try it on other auxiliary binaries. The current [conformance-config.textproto](https://github.com/ampproject/amphtml/blob/master/build-system/conformance-config.textproto) is constructed for AMP binary (v0 and extensions). But it doesn't cover all situations for non-AMP binaries such as `amp-inabox-host.js`, `login-done.js`, etc. One of the main distinction in `amp-inabox-host.js` is that it cannot install polyfills. That shows up regularly in bugs such as #24219, where an unpolyfilled `Array.includes` was used in a dependent file. It would be great if we could catch such problems on the compilation level using a separate conformance-config. It'd be even better if this conformance-config could inherit from the main one. I think this mainly affects [this](https://github.com/ampproject/amphtml/blob/c68ef8fdcd222ade24b458a3b91c132e13474eda/build-system/compile/compile.js#L326) compilation setting.

/cc @jridgewell @erwinmombay @lannka

**Comment by rsimha** [comment]
Assigning to @erwinmombay, who is working on updating the way conformance configs are used by `gulp check-types`. Perhaps the configs can be split up while you're at it?

**Comment by rsimha** [comment]
Clearing assignees since I don't think Erwin is actively working on this.

Do I understand correctly that we do not include `amp-inabox-host.js` in `gulp check-types`?

I'll let the folks tagged in the issue description comment on what needs to happen here.

**Comment by rsimha** [comment]
_[Infra triage]_ Closing this as stale. Please reopen if required.
