### ISSUE TITLE
Discussion: Allow lazy-loading img element

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#24233]
Chromium recently shipped the `loading=lazy`attribute for `img` and other browsers seem to be on track to gain support as well.

With that, I'm wondering if we are ready to make image elements of the form

```html
<img 
    loading=lazy 
    decoding=async 
    width=$width 
    height=$height 
    src=… 
    srcset=…
    sizes=…>
```

valid?

CC @Gregable @dvoytenko

**Comment by dvoytenko** [comment]
That's true. As long as they are both specified and both are valid numbers.

**Comment by cramforce** [comment]
Yeah, we still have the validator. That is why we don't need the browser policy.

**Comment by cramforce** [comment]
Although I could also see to require application of the policy in meta tag and then *not* requiring width and height.

**Comment by dvoytenko** [comment]
@cramforce I think we can definitely start with `width` and `height` as you suggested above. Supporting unsized media policy would go much deeper with more validator changes.

**Comment by cramforce** [comment]
It seems that consensus is now moving towards inferring aspect ratio from width and height attributes (the same thing that AMP does) https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/hbhKRuBzZ4o/pmehGGHKAAAJ

One difference compared to AMP is that if those values are wrong, things will still jump. That is definitely a reason to concern. E.g. `width=1 height=1` on every `img` would be valid, but jumpy.

**Comment by dvoytenko** [comment]
@cramforce Yeah. That would take a metric to report and resolve.

**Comment by cramforce** [comment]
I'm actually not 100% certain my interpretation is correct. I'll ask on the blink-dev thread.

**Comment by cramforce** [comment]
OK, this was clarified. Current intent is to give the image priority, so this would be a jank vector.

**Comment by alanorozco** [comment]
RE: auto-lightbox, we would only need to change how the extension scans. We also might need to change how lightbox-gallery scans and picks images.

**Comment by dvoytenko** [comment]
@cramforce Do we have any concern that `loading=lazy` might break preloading guarantees if we ever allowed non-cache src for images on cache?

**Comment by cramforce** [comment]
We couldn't allow those,

**Comment by westonruter** [comment]
Aside: Allowing `img[loading=lazy]` would also open the door to allowing the `picture` element. This would be helpful for serving existing web content in AMP since it can be difficult/impossible to translate `picture` into `amp-img`. We've tried in the context of the AMP plugin: https://github.com/ampproject/amp-wp/issues/1316.

**Comment by cramforce** [comment]
Closing in favor of #29786
