### ISSUE TITLE
Error: No config could be discovered in the page

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#24247]
```
Error: No config could be discovered in the page
at (https://raw.githubusercontent.com/ampproject/amphtml/1908162134430/third_party/subscriptions-project/config.js:603)
```

go/ampe/CIev74KVpcHgqwE

**Comment by marcosalberto** [comment]
@newmuis can you send the url?

**Comment by jamespearn** [comment]
When I had this same error message it was because my page was missing the SwG specific Structured Data Markup as described here:

https://developers.google.com/news/subscribe/guides/structured-data-markup#subscribe-with-google-structured-data-markup-requirements

**Comment by newmuis** [comment]
I don't actually have a specific url that I encountered this on; I see this error occurring in aggregate through AMP's onduty dashboard.

**Comment by aferrandini** [comment]
In our case, this problem was that metadata didn't contain `productID ` nor `isAccessibleForFree` information as shown in [amp-subscription documentation](https://amp.dev/documentation/components/amp-subscriptions/#microdata-markup)

> The configuration is resolved as soon as productID and isAccessibleForFree are found. It is, therefore, advised to place the configuration as high up in the DOM tree as possible.

You have to set both like:

```html
<script type="application/ld+json">
{
  ...
  "isAccessibleForFree": false,
  ...
  "isPartOf": {
    "@type": ["CreativeWork", "Product"],
    "name" : "Product name",
    "productID": "product-id"
  }
  ...
}
</script>
```

**Comment by newmuis** [comment]
Then, it sounds like maybe this should be an expected error, if it's a publisher configuration thing?

@ampproject/wg-access-subscriptions to verify

**Comment by rcebulko** [comment]
Bumping this, since we're still seeing large error volume. @ampproject/wg-access-subscriptions is this an expected/user error?

**Comment by rcebulko** [comment]
I think more generally, I see that the `user().error`, `dev().error`, `dev().assert` etc. methods are not used by the SwG project, and so every error that gets raised--even user errors and expected errors--is treated the same way and reported as an unexpected runtime error, which clutters the main error logs and appears as something that's broken when it's really an error the publisher should be seeing

**Comment by rcebulko** [comment]
We added amphtml-style error logging helpers in https://github.com/subscriptions-project/swg-js/pull/1017, which should allow SwG to propagate that info when used within AMP code.
