### ISSUE TITLE
Fix youtube/amp-video to only render poster on layoutCallback

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2426]
I'm wondering: Should we just render the poster in layoutCallback and render the iframe/video in viewportCallback (if not done yet)

CC @dvoytenko

**Comment by cramforce** [comment]
The problem with that solution is that it is hard to get the right `loadPromise`. So, we should have a way to layoutCallback again when something first enters the viewport.

**Comment by dvoytenko** [comment]
These elements normally only have `layoutCallback` called when they enter viewport or very close to. I think instead we need to revisit the idea of `prerenderCallback` and leave `layoutCallback` be as today.

**Comment by cramforce** [comment]
+1 How do you feel about my implementation in #2434?

That seems kinda hacky. Would really prefer prerenderCallback.

**Comment by dvoytenko** [comment]
Yes, I'd much much more prefer to have a `prerenderCallback`. I can take this on for FixIt if you'd like.

**Comment by mkhatib** [comment]
yeah I think `prerenderCallback` would streamline a lot of the 'workarounds' that we're currently doing to handle placeholders during prerendering.

**Comment by dvoytenko** [comment]
Ok. Let me make a pass on it then early next week and we can redo that PR then.

**Comment by cramforce** [comment]
See #2434 for one way to do it now.

**Comment by mkhatib** [comment]
I've started working on porting your solution to `amp-youtube`. One of the drawback is that we're not gonna be able to lazily render the images placeholders - I think the `amp-instagram` change also fails to do that, all instagrams images (not iframes) are loaded regardless where they are in the viewport in prerender mode, no?

With #2385 we set `renderOutsideViewport() => false`  but this won't work alongside `prerenderAllowed() => true`, right?

**Comment by dvoytenko** [comment]
Let's catchup tomorrow on `prerenderCallback` - I believe it's the infrastructure that's missing here.

**Comment by cramforce** [comment]
Prerender callback isn't all here: For these widgets we also want to eagerly render the posters and then render iframes super late.

**Comment by dvoytenko** [comment]
Yes, agree. But I think it's a common enough pattern that we should get it settled early.

**Comment by cramforce** [comment]
Wanted to ping this. I think this is pretty important for certain pages.

**Comment by mkhatib** [comment]
Not sure where do we stand with this now. What is the wanted behavior here?

**Comment by cramforce** [comment]
- Render posters only in `layoutCallback`
- Render embeds when element enters viewport and layoutCallback has been called already (or is in viewport during layoutCallback)

**Comment by dvoytenko** [comment]
Hmm. I'd rather much avoid using `layoutCallback` for managing posters. Isn't this already accomplished overall? Maybe we just need to fine-tune thee priority a bit with numeric `rendersOutsideViewport` that @jridgewell implemented?

**Comment by cramforce** [comment]
Right now we render all posters for YT/Instagram for the entire page in pre-render mode. That should be fixed.

**Comment by jridgewell** [comment]
`#renderOutsideViewport` is just for managing when `#layoutCallback` is called. We could move calling `#createPlaceholder` into the resource lifecycles, so that it's only called when within (some larger) distance declared by `#renderOutsideViewport`:

```js
const distance = this.element.renderOutsideViewport();
if (distance < distanceFromViewport) {
  // call #layoutCallback
} else if (distance * 2 < distanceFromViewport) {
  // call #createPlaceholder
}

**Comment by mkhatib** [comment]
> Right now we render all posters for YT/Instagram for the entire page in pre-render mode. That should be fixed.

@cramforce I don't think this is true anymore - at least for instagram. Now that we use `createPlaceholderCallback` to create an `amp-img` (instead of img) placeholder, its left to the `resources` to schedule layout for the placeholder - this includes not scheduling if outside viewport in prerender mode. Does this not match what you expect?

For YouTube we have #3216

**Comment by cramforce** [comment]
Perfect!

**Comment by mkhatib** [comment]
Should we close this one? We're tracking the YouTube issue in #3216

**Comment by jridgewell** [comment]
Closing 'cause @cramforce emoted instead of closing. 😛
