### ISSUE TITLE
Support api for amp website

### ISSUE THREAD

**Issue by bcrazydreamer** [ampproject/amphtml#24260]
## Describe the new feature or change to an existing feature you'd like to see
The one feature which is used by lots of websites should be added, i. e. support api integration like chat popup on for need help kind of features or so on. example **intercom** api provided by https://www.intercom.com or many similar api

**Comment by choumx** [comment]
This FR is a bit too vague to be actionable. Can you describe the characteristics of the desired APIs and use cases for them?
