### ISSUE TITLE
Closure complier not failing when expected

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#24283]
I introduced some code in #24044 which included a new dependency where `amp-story-auto-ads` is dependent on the [`assertConfig`](https://github.com/ampproject/amphtml/blob/098b2be2852515f4a3ecf5100f0e72d8cff515df/extensions/amp-ad-exit/0.1/config.js#L117) function from `amp-ad-exit`.

I added the explicit path `extensions/amp-ad-exit/0.1/config.js` to the [`CLOSURE_SRC_GLOBS`](https://github.com/ampproject/amphtml/blob/098b2be2852515f4a3ecf5100f0e72d8cff515df/build-system/sources.js#L68) array.

This function has a transitive dependency of the `extensions/amp-ad-exit/0.1/filters/filter.js` file. When this change hit canary it started throwing the error `FilterType$$module$extensions$amp_ad_exit$0_1$filters$filter is not defined`

It is unclear why this error was not caught at compile time. I also manually tested with `gulp clean && gulp dist --fortesting && gulp serve --compiled` and everything appeared to be working fine.

**Comment by calebcordry** [comment]
cc/ @lannka

**Comment by jridgewell** [comment]
It's because these are reported as warnings:

```
extensions/amp-ad-exit/0.1/config.js:17: WARNING - [JSC_JS_MODULE_LOAD_WARNING] Failed to load module "./filters/filter"
import { FilterType } from './filters/filter';
^

src/services.js:231: WARNING - [JSC_JS_MODULE_LOAD_WARNING] Failed to load module "../extensions/amp-loader/0.1/amp-loader"
     * @return {!Promise<!../extensions/amp-loader/0.1/amp-loader.LoaderService>}
                          ^

src/services.js:234: WARNING - [JSC_JS_MODULE_LOAD_WARNING] Failed to load module "../extensions/amp-loader/0.1/amp-loader"
    return (/** @type {!Promise<!../extensions/amp-loader/0.1/amp-loader.LoaderService>} */(getElementServiceForDoc(
                                 ^

src/services.js:243: WARNING - [JSC_JS_MODULE_LOAD_WARNING] Failed to load module "../extensions/amp-standalone/0.1/amp-standalone"
     * @return {!Promise<!../extensions/amp-standalone/0.1/amp-standalone.StandaloneService>}
                          ^

src/services.js:246: WARNING - [JSC_JS_MODULE_LOAD_WARNING] Failed to load module "../extensions/amp-standalone/0.1/amp-standalone"
    return (/** @type {!Promise<!../extensions/amp-standalone/0.1/amp-standalone.StandaloneService>} */(getElementServiceForDoc(
                                 ^

src/services.js:740: WARNING - [JSC_JS_MODULE_LOAD_WARNING] Failed to load module "../extensions/amp-user-location/0.1/user-location-service"
     * @return {!Promise<?../extensions/amp-user-location/0.1/user-location-service.UserLocationService>}
                          ^

src/services.js:743: WARNING - [JSC_JS_MODULE_LOAD_WARNING] Failed to load module "../extensions/amp-user-location/0.1/user-location-service"
    return (/** @type {!Promise<?../extensions/amp-user-location/0.1/user-location-service.UserLocationService>} */(getElementServiceIfAvailableForDoc(
```

**Comment by rsimha** [comment]
Sheesh. We're forced to silence the warnings for imports in typedefs because of https://github.com/google/closure-compiler/issues/3041. I'd have imagined bad imports would result in an error and not a warning.
