### ISSUE TITLE
AMP version has no release tag

### ISSUE THREAD

**Issue by andyblackwell** [ampproject/amphtml#24293]
## What's the issue?

When trying to track down a reason for a [different bug](https://github.com/ampproject/amphtml/pull/23554#issuecomment-526213624), I wanted to see the release notes for the version of AMP I was on, only to find no release tag exists for it.

version: 1908231648370
404s: https://github.com/ampproject/amphtml/releases/tag/1908231648370

Guessing it was probably deleted? But if so, I'm not sure why I'm still getting this version in production. Even in incognito and hard refreshing.

From the version number it looks to have been made between the last two versions, so between 7 days ago and 2 days ago:
2 days ago: https://github.com/ampproject/amphtml/releases/tag/1908271552560
? days ago: https://github.com/ampproject/amphtml/releases/tag/1908231648370
7 days ago: https://github.com/ampproject/amphtml/releases/tag/1908222134250

Seems like I **should** be getting version 1908222134250, as it's currently marked as "Latest release", and was released 6 days ago.

![Screen Shot 2019-08-29 at 11 01 32 AM](https://user-images.githubusercontent.com/372590/63956854-e502c500-ca4c-11e9-83f0-a514fd71d38e.png)

## How do we reproduce the issue?

https://cdn.ampproject.org/experiments.html
You should see: "This is version 1908231648370 of the AMP runtime."
You should also get a 404 when trying to load the release tag: https://github.com/ampproject/amphtml/releases/tag/1908231648370

## What browsers are affected?

All browsers

## Which AMP version is affected?

version: 1908231648370

**Comment by calebcordry** [comment]
Sorry I'm not on duty. Maybe @newmuis (on duty this week) or @lannka (last week)

**Comment by andyblackwell** [comment]
just asked in slack and @jridgewell responded there. Sounds like tagging the release is manual and it was just accidentally skipped

**Comment by andyblackwell** [comment]
they just tagged the release, so closing ticket
