### ISSUE TITLE
[amp-anim] add support for [amp-lightbox-gallery]

### ISSUE THREAD

**Issue by maciejmackowiak** [ampproject/amphtml#24306]
## Describe the new feature or change to an existing feature you'd like to see
I would love to use amp-lightbox-gallery when embedding gifs on page but as per AMP documentation:
![obraz](https://user-images.githubusercontent.com/24996403/64009914-121ca980-cb19-11e9-82ae-022fcb00d25a.png)
gif should be embeded with amp-anim but amp-lightbox-gallery doesn't support amp-anim.
https://amp.dev/documentation/examples/components/amp-anim/

## Describe alternatives you've considered
Probably I could use amp-img for gif's but:
1. like above as per AMP documentation gif should be embedded with amp-anim.
2. when using amp-wp this is not possible
https://github.com/ampproject/amp-wp/blob/develop/includes/sanitizers/class-amp-img-sanitizer.php#L311

**Comment by archon810** [comment]
Curious what the solution here will end up being and whether we should implement annoying workarounds or wait for AMP to fix it. Appreciate any discussion to "feel the room" and gauge the complexity of the fix.

**Comment by archon810** [comment]
Here's an example of the issue: https://www.androidpolice.com/2019/08/28/gmail-finally-adds-that-smooth-account-switching-gesture-apk-download/?amp.

The GIFs are currently being excluded from the gallery and can't even be tapped on to zoom in.

**Comment by nainar** [comment]
Due to amp-anim's poor performance I think our intention has been to deprecate it. There is appetite for using videos to manage gifs as you can see here: https://github.com/ampproject/amphtml/issues/24001

Curious to hear: Is it possible to use `<amp-img>` for the gifs in this case? So that they are lightboxable?

**Comment by archon810** [comment]
That would certainly make things simpler for us.

**Comment by nainar** [comment]
You can currently add your gifs to `<amp-img>` as well. The drawback here is that `<amp-img>`s aren't unloaded when they leave the viewport whereas `<amp-anim>`s are. This means that large GIFs will stay loaded forever. If you are ok with that or are using small GIFs you can add them in `<amp-img>`

**Comment by archon810** [comment]
> You can currently add your gifs to `<amp-img>` as well. The drawback here is that `<amp-img>`s aren't unloaded when they leave the viewport whereas `<amp-anim>`s are. This means that large GIFs will stay loaded forever. If you are ok with that or are using small GIFs you can add them in `<amp-img>`

@nainar This is the problem in AMP-WP though: https://github.com/ampproject/amp-wp/blob/develop/includes/sanitizers/class-amp-img-sanitizer.php#L311. How do we proceed?

**Comment by westonruter** [comment]
@archon810 Would you [create a new issue](https://github.com/ampproject/amp-wp/issues/new) on the AMP plugin repo for this? Let's collaborate there on a way to force `amp-img` to be used for GIFs instead of `amp-anim`.

**Comment by archon810** [comment]
@maciejmackowiak will create it soon.

**Comment by westonruter** [comment]
Also, here's a quick workaround plugin that forcibly converts all `amp-anim` to `amp-img` after the image sanitizer has done its conversions: https://gist.github.com/westonruter/1eeb2224004c0e904fa2a35fc92899c0

**Comment by archon810** [comment]
Fantastic - the workaround works https://www.androidpolice.com/2019/08/28/gmail-finally-adds-that-smooth-account-switching-gesture-apk-download/?amp.

We'll revert it when this ticket is eventually properly resolved.

Thanks @westonruter!

**Comment by archon810** [comment]
Any updates here please?

**Comment by westonruter** [comment]
I believe this will soon be obsolete with the intent to deprecate `amp-img` which will include, I presume, deprecation of `amp-anim`. See https://github.com/ampproject/amphtml/issues/30442.
