### ISSUE TITLE
Improve Chartbeat analytics documentation link

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#2430]
In https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md the link currently goes here:

http://support.chartbeat.com/docs/

but it should go to something more specific.

**Comment by rudygalfi** [comment]
@breauxc and @britice -- Can either of you take this?

**Comment by breauxc** [comment]
Yes, we just talked about this today.
