### ISSUE TITLE
Improve Adobe Analytics documentation link

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#2431]
In https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md the link currently goes here:

https://helpx.adobe.com/marketing-cloud/analytics.html

but it should go to something more specific.

**Comment by rudygalfi** [comment]
@cory-work -- Can you take this?

**Comment by bpaduch** [comment]
Fixed in https://github.com/ampproject/amphtml/commit/994dbc735d7c0afe2e0fc43cb3b4d1a7758b331b.

**Comment by bpaduch** [comment]
Fixed in https://github.com/ampproject/amphtml/commit/994dbc735d7c0afe2e0fc43cb3b4d1a7758b331b.
