### ISSUE TITLE
Fallback element for amp-iframe

### ISSUE THREAD

**Issue by mjangda** [ampproject/amphtml#2433]
Looks like `amp-iframe` does not display the `fallback` element when iframe errors or fails to load. If you have a `placeholder`, that continues to display but it would nice to toggle to the `fallback` if included.

**Comment by jridgewell** [comment]
Related to https://github.com/ampproject/amphtml/issues/2261?

**Comment by dvoytenko** [comment]
Yes. #2261 is the right bug to track this. I will close this one as a duplicate.
