### ISSUE TITLE
Get Link not working in Desktop

### ISSUE THREAD

**Issue by ghelapratik** [ampproject/amphtml#24334]
There is a get link button in the AMP Story. However, when you click the get link button, it says link copied. But when you try to paste it, it doesn't work. Below video illustrates the behavior. 

![Sep 3 2019 10_06 AM - Edited](https://user-images.githubusercontent.com/22929187/64144575-b6ad2d00-ce32-11e9-9bf7-7221a0cf43fb.gif)

**Comment by newmuis** [comment]
@estherkim were you able to repro this when working on #23860?  I'm now seeing this behavior now in Chrome; looks like maybe we traded Chrome support for Firefox support 😦

**Comment by estherkim** [comment]
I can repro this too - taking a look now!
