### ISSUE TITLE
Chrome Extension to auto-fetch/use AMP pages if available

### ISSUE THREAD

**Issue by corysimmons** [ampproject/amphtml#2435]
It'd be interesting to see how the web looks on desktop without all the bloat.

I'm on 56k so this would be extra helpful for me.

**Comment by adewale** [comment]
Try: https://chrome.google.com/webstore/detail/amp-accelerated-mobile-pa/baodpdnidmedcpanneabeldenamaaeoe?hl=en-GB

I haven't used it myself so I can't vouch for it.

**Comment by corysimmons** [comment]
Cool, works pretty well. For some reason The New York Times version doesn't work but The Guardian's works as expected. It adds some gunk to the end of the url.

I just realized an extension would literally just be hitting a page, looking for `<link canonical="amphtml">`, and redirecting accordingly.
