### ISSUE TITLE
🌸 Cherry-pick request for #24364 into #24352 (Approved)

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#24366]
# Cherry-pick request

| Issue | PR  | Production? | RC? | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---: | :-: | :---------: | :-: | :----------- |
| #24364 | #24365 | **YES** | **YES** |  #24086 (prod) <br> #24254 (RC) <br> #24352 (opt-in) |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?
Impacts a large number of users with layout intrinsic that rely on auto-sizes to auto-generate a sizes attribute. 

# Mini-postmortem

## Summary
We reverted the auto-generated sizes feature for layout intrinsic in `<amp-img>`. This turned out to affect a large number of users who were depending on it. 

| Users affected | Impact |
| -------------- | ------ |
| Wordpress Converter | The wordpress converter converts to layout intrinsic by default if no layout is specified, so this impact most of their users whose webpages contained images. The impact is that no sizes attribute was provided and larger images than necessary were downloaded. |

## Root Causes
1. A misunderstanding of how layout intrinsic behaves in `<amp-img>` with `srcset` and `sizes`. I interpreted the documentation to mean that the size of the `<amp-img>` with layout intrinsic would be determined by the natural size of the element, which has particular meaning for images. This interpretation is incorrect (the natural size of the element in our case is defined by width and height attributes passed to the layout intrinsic element). 
2. Based on this incorrect understanding, I concluded that the auto-sizes feature would lead to problematic behavior for images with layout intrinsic, and therefore removed this feature for layout intrinsic. The actual case is that it was only problematic for a niche CSS use case enforcing the img's natural size via height/width: auto and min-height/min-width: 0.

## Action Items

| Action Item | Type | Owner | PR # |
| :---: | :-: | :---------: | :-: |
| Revert offending PR to bring back auto-sizes for layout intrinsic | Mitigate | @cathyxz | #24364 |
| Investigate original #23453 | Investigate | @cathyxz | N/A |
| Update documentation for layout intrinsic | Prevent | @cathyxz | #24450 | 

## Lessons Learned
Layout Intrinsic's natural size is determined by the attributes passed to it, not by the intrinsic size of the element being laid out. 

### Things that went wrong
- Misunderstanding how layout intrinsic behaved, not having sufficient documentation in the auto-sizes design doc regarding the prior investigation done to ensure this feature was working (this had actually been investigated before launch). 

### Things that went well
- @estherkim was extremely fast with the revert and cherry pick to production. Thank you!
- @jridgewell made himself available to double check and review the behavior of layout intrinsic. Thank you!
- @westonruter was quick to jump on the initial bug report and available to help verify the fix after deployment. Thank you! 

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by cramforce** [comment]
Approved

**Comment by cathyxz** [comment]
Ping @ampproject/cherry-pick-approvers for one more approval.

**Comment by estherkim** [comment]
Deployed.
prod: `1909051800160`
1%: `1909051756330`
opt-in: `1909051736590`

**Comment by cathyxz** [comment]
Reassigned back to myself for post-mortem.

**Comment by cathyxz** [comment]
Closing since post-mortem is complete.
