### ISSUE TITLE
Deprecate amp-anim in favour of amp-img with a better unloading strategy

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#24367]
There have been prior discussions about deprecating amp-anim in favour of amp-img/amp-video. See #24001. Having them as 2 separate codebases means that images and GIFs though similar entities get slightly different treatments (e.g. amp-anim doesn't get lightboxed #24306 ).

We should swap amp-anim to be governed by amp-img under the hood instead. amp-img should et logic added to it to unload images after they are a few viewports away. (This can be 2/3 viewports or customizable).

What do folks think?

cc @cathyxz @sparhami @alanorozco @ampproject/wg-ui-and-a11y @kristoferbaxter

**Comment by wassgha** [comment]
There's always the concern about amp-img's size but the differences are minimal between the two. We can also gate amp-anim's behavior behind an attribute too if necessary.
/cc @dvoytenko

**Comment by dvoytenko** [comment]
I think initially it was important to stop (pause) animation of a GIF image. I'm not sure if it's still important of if browsers figured it out.

**Comment by alanorozco** [comment]
@dvoytenko I think this proposes that `amp-img` should have the same unloading/pausing strategy as `amp-anim`.

**Comment by dvoytenko** [comment]
@alanorozco Yes. Exactly. But that may conflict with our desired to deprecate `amp-img` in favor of the `img` with the loading strategy per #24233.

**Comment by archon810** [comment]
Any updates here please?

**Comment by dvoytenko** [comment]
I think semantically there are still some benefits from knowing img vs animation. E.g. some caches could rewrite a GIF to a mp4.
