### ISSUE TITLE
disabling auto-sizes in amp-img with layout intrinsic is causing a lot of amp-imgs to not have a sizes attribute

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#24364]
We recently disabled `auto-sizes` for layout intrinsic in `<amp-img>` to fix https://github.com/ampproject/amphtml/issues/23453. This leaves a lot of `<amp-img>`s that rely on this feature without a sizes attribute. We need a more nuanced fix or to apply that only to images whose `srcset` attributes are generated by the AMP cache. 

/cc @jridgewell @westonruter @ampproject/wg-ui-and-a11y

**Comment by nainar** [comment]
@estherkim who is on release duty. FYI there is an upcoming revert coming your way that will need to be cherrypicked.

**Comment by cathyxz** [comment]
Revert PR: https://github.com/ampproject/amphtml/pull/24365

**Comment by cathyxz** [comment]
This issue is now resolved since #24365 hit production. An incoming post-mortem will be written in the cherry-pick issue #24366.
