### ISSUE TITLE
🌸 Cherry-pick request for #24364 into #24086 (Pending)

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#24376]
# Cherry-pick request

| Issue | PR  | Production? | RC? | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---: | :-: | :---------: | :-: | :-----------: |
| #24364 | #24365 | **YES** | **YES** | #24086 |

Duplicate request of https://github.com/ampproject/amphtml/issues/24366 for current production. 

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by cramforce** [comment]
Approved
