### ISSUE TITLE
Documentation: Update amp-script reference 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amphtml#24378]
## What's the issue?

[amp-script reference](https://amp.dev/documentation/components/amp-script/?format=websites) documentation needs to be updated. Reference documentation is the source of truth for components, amp-script documentation is missing vital information. 

## Update requests

- A simple example: copy should be more clear. "An `amp-script` element can load JavaScript in two ways." With subheadings "Load file from a URL" and "Reference local script" with further explanation on referencing `id`. 

- Use of inline script for amp-script: we either need to add a warning that it currently isn't valid AMP, or we need to allow it. 

- Include section on CSP. We need to explain when a CSP is appropriate and how to hash it (an example of how to do this would be appreciated). Should probably be a top level header or update "Security features" to include this information. 

- Remove "Interested in using amp-script?" - amp-script is live, this information doesn't seem relevant. 

- Remove the FAQ: if it is asked frequently enough it should have a permeant place in the documentation. 
    - "Which JavaScript APIs can I use?" This should be moved under "Restrictions" with a subheading of "Allowed APIs" . Combine with "Can you support ____ API?" to include instructions on how to request APIs. 
    - Remove all other FAQ - these should be answered/addressed under "Size of JavaScript code" and CSP information. 

Please let me know when these changes are ready to be reviewed!

**Comment by nainar** [comment]
Issue for the fact that local scripts aren't allowed is here: https://github.com/ampproject/amphtml/issues/24309
