### ISSUE TITLE
🌸 Cherry-pick request for #24365 into #24254 (Pending)

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#24377]
# Cherry-pick request

| Issue | PR  | Production? | RC? | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---: | :-: | :---------: | :-: | :-----------: |
| #24364 | #24365 | **YES** | **YES** | #24086 |

Duplicate request of https://github.com/ampproject/amphtml/issues/24366 for current 1%. 

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by cramforce** [comment]
Can we use a single issue to track all cherry-picks?

**Comment by estherkim** [comment]
Sure let me consolidate.
