### ISSUE TITLE
Bing cache no longer maintained?

### ISSUE THREAD

**Issue by indeed-a-genius** [ampproject/amphtml#24391]
I apologize if it's not the correct way to report this.

Is the Bing AMP cache still maintained? All bing-amp.com cache URLs just 302 redirect me to the non-cached URL.
Example: 
https://www-theverge-com.bing-amp.com/c/s/www.theverge.com/platform/amp/2018/9/20/17881766/bing-google-amp-support-mobile-news

Both Google and Cloudflare caches work fine:
https://www-theverge-com.cdn.ampproject.org/c/s/www.theverge.com/platform/amp/2018/9/20/17881766/bing-google-amp-support-mobile-news
https://www-theverge-com.amp.cloudflare.com/c/s/www.theverge.com/platform/amp/2018/9/20/17881766/bing-google-amp-support-mobile-news

I cannot find a single Bing AMP cache URL that works.

**Comment by choumx** [comment]
I just found a couple pages served from Bing's CDN from searching on bing.com e.g. [this one](https://www.bing.com/amp/s/amp.cnn.com/cnn/2019/09/10/football/iran-football-women-sahar-khodayari-spt-intl/index.html).

Is there a specific problem you're having?
