### ISSUE TITLE
Error on documentation about amp-image-slider

### ISSUE THREAD

**Issue by reinhardmohr** [ampproject/amphtml#24397]
**Please only file reports about bugs in AMP here.**

## What's the issue?

There is an error in the documentation on the amp.dev website. It's about amp-image-slider on page:
https://amp.dev/documentation/components/amp-image-slider/?format=websites

Briefly describe the bug.

The provided code there is missing an important piece:
 layout="fill"
This is missing in all the examples. So when I copied the code from there nothing worked.
It should be e.g.:
<amp-img src="/uploads/images/Restaurierung-Vergleichsbilder-Grams-Demmel/Napoleon-Bild-vorher.jpg" alt="A blurry image about canoeing" layout="fill"></amp-img>

What makes it even more confusing is that the examples page is kind of buggy, too.
None of the examples there work:
https://amp.dev/documentation/examples/components/amp-image-slider/?format=websites

## How do we reproduce the issue?
Try to copy the code from this page – and try to get it to work.

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. Step 1 to reproduce
2. Step 2 to reproduce
3. …

## What browsers are affected?
That's not a browser bug. So all are affected.

## Which AMP version is affected?
Latest, probably all; everything that is copied from this page.

Is this a new issue? Or was it always broken? Paste the version of AMP where you saw this issue. (You can find the version printed in your browser's console.)

**Comment by nainar** [comment]
Hi!

@cathyxz is layout="fill" supported on amp-image-slider?

Also @reinhardmohr the examples seem to be working fine on Chrome on Mac. Could you say more about what browser/device you are using?

**Comment by cathyxz** [comment]
Per the validation file, layout fill is not supported by `amp-image-slider`. The examples are also working for me.

**Comment by reinhardmohr** [comment]
Hi,cathyxz and nainar,
thanks for helping.
Okay, the examples are working – I don't know what was wrong there …

But:
Your code on the page
https://amp.dev/documentation/components/amp-image-slider/?format=websites
still does NOT work.
Only your playground provides the correct code WITH LAYOUT=FILL !

So I provide 5 screenshots here:
1) highlighted code from your playground with layout="fill"
I copied the code, it works!
![Bildschirmfoto 2019-09-11 um 14 55 29](https://user-images.githubusercontent.com/13329800/64699913-1ac09880-d4a6-11e9-9c9b-0cfb9a217be0.png)

2) A screenshot with the code sample from the above mentioned page. This does not work …
![Bildschirmfoto 2019-09-11 um 14 50 32](https://user-images.githubusercontent.com/13329800/64700021-5e1b0700-d4a6-11e9-802b-8ee7a5117c82.png)

3) This is how your code looks on my page (sure, my images are in the code, but they don't show:
![Bildschirmfoto 2019-09-11 um 14 50 14](https://user-images.githubusercontent.com/13329800/64700065-7e4ac600-d4a6-11e9-95f0-3fe6006157f8.png)

4) The code now on my website. It origins from your playground:
![Bildschirmfoto 2019-09-11 um 14 51 02](https://user-images.githubusercontent.com/13329800/64700112-902c6900-d4a6-11e9-9cb7-67f4c7394d70.png)

5) And this is what it looks like:
![Bildschirmfoto 2019-09-11 um 14 49 37](https://user-images.githubusercontent.com/13329800/64700132-9c182b00-d4a6-11e9-8592-b4c6ee3a4a55.png)

Thanks for helping
Reinhard
