### ISSUE TITLE
Document that Cloudflare AMP CDN is deprecated

### ISSUE THREAD

**Issue by archon810** [ampproject/amphtml#24407]
Hi,

https://cdn.ampproject.org/caches.json currently advertises 3 AMP CDNs: Google's, Bing's, and Cloudflare's.

In attempting to figure out why Cloudflare's AMP CDN isn't working with our recently-launched AMP site, I contacted them, and they just got back to me with this:

> Hi Artem,
> 
> Our team has tested on our side and confirmed the our AMP cache is fully deprecated. We have introduced the new AMP real URL and the AMP cache is not further supported in this case.
> 
> Please let us know if there is anything else we can assist.
> 
> Kind regards,
> 
> Qia | Technical Support Engineer

**Comment by sebastianbenz** [comment]
Thanks for letting us know!

//cc @CrystalOnScript for the doc updates

**Comment by archon810** [comment]
Hang on, what about updating the JSON file https://cdn.ampproject.org/caches.json? We shouldn't close before doing so.

**Comment by fstanis** [comment]
IIRC, https://cdn.ampproject.org/caches.json is pulled from https://github.com/ampproject/amphtml/blob/master/caches.json
