### ISSUE TITLE
FTP links are not validating

### ISSUE THREAD

**Issue by portalzine** [ampproject/amphtml#2441]
Just by using ftp links in a document the validation fails, why?
Even on mobile, ftp links are not without relevance. 
Sometimes documents  are stored on a FTP server.

**Comment by cramforce** [comment]
Seems reasonable for our custom protocol whitelist.

**Comment by jridgewell** [comment]
@mkhatib: We'll also need to add it to https://github.com/ampproject/amphtml/pull/2292.

**Comment by cramforce** [comment]
Does iOS handle FTP?

**Comment by jridgewell** [comment]
> Does iOS handle FTP?

Yup.

**Comment by Gregable** [comment]
This is only for links, aka `<a href=...>`, right? I'm wondering if there are any other resources we want to allow delivery from ftp: for such as images/videos/audio/etc. I don't actually know how browsers handle these.

**Comment by mkhatib** [comment]
@Gregable not sure either but seems [browsers might be able to handle ftp sources](http://stackoverflow.com/questions/17169251/retrieve-image-from-ftp-to-webpage) for images. I am not sure if this has any security implications. I guess we can start with anchor links support for now. 

Does the validator blacklist ftp specifically? Anything is done to custom protocols like `whatsapp://`?

@jridgewell currently the logic for iOS handles anything that's not `http` or `https` by opening the link in `blank` to allow the browser to forward that to whatever app it wants. Are you saying we shouldn't do that for `ftp` and let browsers handle it normally instead?

**Comment by Gregable** [comment]
The validator whitelists for all url protocols. `whatsapp://` is one of our whitelists for anchor hrefs. It's too dangerous to use a blacklist as there may be application types which run code that we aren't aware of. For example, I was aware of `javascript://` but not `vbscript://`initially.

We'll add `ftp://` to the whitelist.

**Comment by jridgewell** [comment]
@mkhatib: FTP is handled natively in Safari, so it is "normal". We shouldn't open `_blank` for it.

**Comment by mkhatib** [comment]
@jridgewell just tested this out. It's true the browser can handle it natively and the logic I've added shouldn't interfere with that *unless* the document is embedded - just tested this out and it seems the Safari iOS issue also affects `ftp:` protocol - so we still need the `open(_blank)` fix for them to work.

Also, it seems desktop Safari is also affected for embedded documents with `ftp:` links - clicking them throws a warning in console:

```
[blocked] The page at https://output.jsbin.com/jewoxe/quiet was not allowed to display insecure content from ftp://ftp.funet.fi/pub/standards/RFC/rfc959.txt.
```

So we might want to consider to either generalize the `open(_blank)` fix to handle custom protocols (incl. ftp) on both Desktop and Mobile. Or just put another check that handles ftp on both desktop and mobile.

I've [setup a test jsbin with 3 embedded pages](https://output.jsbin.com/sacegi/quiet) - test it out on both Safari desktop and iOS.

**Comment by Gregable** [comment]
This change is live everywhere. Please reopen if you spot any issues.
