### ISSUE TITLE
amp-video not autoplaying in amp-story

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#24414]
## What's the issue?

`amp-video` components don't autoplay when present on the first page of a story. Only when advancing and then coming back to the first page will they start playing. The error message indicated in the story is "Video failed to load".

Interestingly the video `<source>` elements are is not shown in the DOM, and the error shown in the console is `Failed to load: [object HTMLVideoElement]​​​`

## How do we reproduce the issue?

I created a [minimal, reproducible example here](https://charles.tappable.link/video-autoplay.html). A version with two pages is [available here](https://charles.tappable.link/video-autoplay-2.html).

## What browsers are affected?

All browsers.

## Which AMP version is affected?

I believe this is a newly introduced bug as it was working a few weeks ago. I was on holidays so I have no idea when in the past two weeks this started failing.

**Comment by cpauwels** [comment]
Update: if you CMD+click the links above so they open in a background tab, and then navigate to the tab, the videos autoplay correctly. This makes me think it could be a race condition issue.

**Comment by gmajoulet** [comment]
Thanks for the report and for hosting the demos, I'll have a look today.

**Comment by gmajoulet** [comment]
I just sent a fix, but the good news is that you don't have to wait for it to be available.

Your code is very specific and unveiled a code path we didn't consider. The fix will ensure it works for future use cases, but in the meantime, adding `width: 100%;` to your `.grid {}` CSS properties will give an initial size to all your components, and should play the video.

**Comment by gmajoulet** [comment]
Thanks, I tested the fix with your example and it works :)

**Comment by cpauwels** [comment]
Do you have any timetable on when the fix will be published?

**Comment by gmajoulet** [comment]
I just merged the fix, it should be available in production in ~2 weeks. Do you think you could adjust your CSS so elements have a defined height in the meantime?
Please let me know if that works for you.

**Comment by cpauwels** [comment]
Works for me! Thanks 👍
