### ISSUE TITLE
Support for Session Storage in amp-script

### ISSUE THREAD

**Issue by eawooten** [ampproject/amphtml#24416]
## What's the issue?

I have a client that is interested in using AMP for their hospitality sites. They currently track reservation information (check in date, number of guests, and duration) using session storage so implementing AMP has been difficult since there is no communication from AMP page to full site where the conversion has to take place.

## How do we reproduce the issue?

Having the ability to set session storage in amp-script javascript would be a perfectly fine solution. Being able to use AMP state would also be great since that is where all the data is stored. It would also be necessary to get the domain of the session data accurate to the full site's domain vs. the cache's domain.

## What browsers are affected?

All browsers

## Which AMP version is affected?

amp-version="1909051800160"

**Comment by eawooten** [comment]
@choumx @kristoferbaxter

**Comment by choumx** [comment]
`localStorage` and `sessionStorage` are implemented and should work. Are you seeing otherwise?

`amp-state` interop is currently WIP.

**Comment by eawooten** [comment]
@choumx I did not try implementing them as the compatibility table says they are not supported. https://github.com/ampproject/worker-dom/blob/master/web_compat_table.md

Would love to hear that the table is outdated though, that would be great.

**Comment by eawooten** [comment]
It is indeed outdated. We can close this issue.

https://github.com/ampproject/worker-dom/commit/d809c7ad4d7b9513637589c76bc2dbc02226dd44
