### ISSUE TITLE
AMP-BASE-CAROUSEL Not Working NEED HELP

### ISSUE THREAD

**Issue by mark-dev14** [ampproject/amphtml#24412]
Hello, I am trying to use amp-base-carousel from the examples provided on your page (https://amp.dev/documentation/components/amp-base-carousel/?format=websites). Nothing is working and I know this component is exactly what I am looking for on my website. Would it be possible to provide a working example of the responsive design of this component.

Thank you,
Mark

**Comment by nainar** [comment]
Hi! amp-base-carousel is in experimental - can you try using amp-carousel version 2 instead? https://amp.dev/documentation/components/amp-carousel/?format=websites
