### ISSUE TITLE
AMP Story Analytics

### ISSUE THREAD

**Issue by AutadeJS** [ampproject/amphtml#24417]
As per the latest update on analytics regarding AMP Stories, 
we had updated the code according to https://blog.amp.dev/2019/08/28/analytics-for-your-amp-stories/

Concern 1:  There is an error in the console ["on" and "request" attributes are required for data to be collected].
>> If we add "request":"event" after "on":"story-page-visible/story-last-page-visible",
Example : {"on": "story-page-visible",
           "request": "event", 
then there is no such console error, So it right to add "request": "event"?

Concern 2: What about the pageview request?
>> Do we need to add
"trackPageview":{"on":"visible","request":"pageview"},
in "triggers"  for pageview request.

**Comment by AutadeJS** [comment]
Thank you so much

**Comment by AutadeJS** [comment]
Hi Enriqe

As per the latest update on analytics regarding AMP Stories, we had updated the google analytics code which you check on https://vacayholics.com/big-ben-facts,
but we are not receiving any data, not even the page view. What I found that in DevTool> Network > Header > Query String Parameters > tid :
it is blank there is no Google Analytics Tracking Id. This is the code what we implemented which you will find in view-source:https://vacayholics.com/big-ben-facts

Can you once check the code where the implementation is according to the latest update ?

<amp-analytics type="googleanalytics" data-credentials="include">
<script type="application/json">
{ 
   "vars":{ 
      "gtag_id":"UA-100756269-3",
      "config":{ 
         "UA-100756269-3":{ 
            "groups":"default"
         }
      }
   },
   "triggers":{ 
      "storyPageVisible":{ 
         "on":"story-page-visible",
         "request":"pageview"
      },
      "storyProgress":{ 
         "on":"story-page-visible",
         "request":"event",
         "vars":{ 
            "event_name":"custom",
            "event_action":"story_progress",
            "event_category":"${title}",
            "event_label":"${storyPageId}",
            "send_to":[ 
               "UA-100756269-3"
            ]
         }
      },
      "storyEnd":{ 
         "on":"story-last-page-visible",
         "request":"event",
         "vars":{ 
            "event_name":"custom",
            "event_action":"story_complete",
            "event_category":"${title}",
            "send_to":[ 
               "UA-100756269-3"
            ]
         }
      }
   }
}
</script></amp-analytics>

**Comment by abhiz10** [comment]
Hey, @Enriqe 
@AutadeJS had added the above concern, Can you once check the code where the implementation is according to the latest update?

**Comment by AutadeJS** [comment]
Hi @Enriqe
As per the latest update on analytics regarding AMP Stories, 
we had updated the google analytics code which you check on https://vacayholics.com/big-ben-facts,
we have also created the Dashboard as per the guidelines are given on https://blog.amp.dev/2019/08/28/analytics-for-your-amp-stories/
but we are not getting any data except PageView Data as we have added this code {"storyPageVisible":{"on":"story-page-visible","request":"pageview"}.

Can you once check the code where the implementation is according to the latest update?
and also please suggest to us that do we need to change anything else while creating the Dashboard other than the guidelines.

<amp-analytics type="googleanalytics" data-credentials="include"><script type="application/json">
{"vars":{"account":"UA-100756269-3","config":{"UA-100756269-3":{"groups":"default"}}},"triggers":{"storyPageVisible":{"on":"story-page-visible","request":"pageview"},
"storyProgress":{"on":"story-page-visible","request":"event","vars":{"event_name":"custom","event_action":"story_progress","event_category":"${title}","event_label":"${storyPageId}",
"send_to":["UA-100756269-3"]}},"storyEnd":{"on":"story-last-page-visible","request":"event","vars":{"event_name":"custom","event_action":"story_complete","event_category":"${title}",
"send_to":["UA-100756269-3"]}}}}
</script></amp-analytics>

**Comment by Enriqe** [comment]
@jeffjose can you take a look at their configuration and see if they're missing something? They are using the default configuration specified in the blog post using Global Site Tag, which I'm not familiar with. Their config:

```
<amp-analytics type="googleanalytics" data-credentials="include">
        <script type="application/json">
          {
            "vars": {
                "account": "UA-100756269-3",
                "config": {
                  "UA-100756269-3": {
                    "groups": "default"
                  }
                }
              },
              "triggers": {
                "storyPageVisible": {
                  "on": "story-page-visible",
                  "request":"pageview"
                },
                "storyProgress": {
                  "on": "story-page-visible", 
                  "request": "event",
                  "vars": {
                    "event_name": "custom",
                    "event_action": "story_progress", 
                    "event_category": "${title}",
                    "event_label": "${storyPageId}",
                    "send_to":["UA-100756269-3"]
                  }
                },
                "storyEnd": {
                  "on":"story-last-page-visible",
                  "request": "event",
                  "vars": {
                    "event_name": "custom",
                    "event_action": "story_complete",
                    "event_category": "${title}", 
                    "send_to":["UA-100756269-3"]
                  }
                }
              }
            }
        </script>
      </amp-analytics>
```

**Comment by abhiz10** [comment]
Hi @Enriqe @jeffjose 
Is there any update on the above concern.

**Comment by zhouyx** [comment]
Hi @abhiz10, have you tried adding `enabled: true` to your config. The `storyProgress` and `storyEnd` are disabled by default.

**Comment by abhiz10** [comment]
Hi, @zhouyx Thanks for the solution ... it's working fine now.

**Comment by abhiz10** [comment]
Hi, @zhouyx I need help with this
Add your amp-analytics configuration to the story. We will be using the ${storyInteractiveId} and ${storyInteractiveResponse} to gather additional information on the responses.
https://amp.dev/documentation/examples/components/amp-story-interactive-quiz/?format=stories
How to add in my existing GA code.
{
   "vars":{
      "account":"@Html.DisplayFor(modelitem => Model.VerticalInfo.GATrackingId)",
      "config":{
         "UA-XXXXXXXXX-3":{
            "groups":"default"
         }
      }
   },
   "triggers":{
      "storyPageVisible":{
         "on":"story-page-visible",
         "request":"pageview",
         "extraUrlParams":{
            "cd1":"AMP",
            "cd2":"${ampdocHost}"
         }
      },
"storyProgress":{
         "on":"story-page-visible",
         "request":"event",
         "enabled":"true",
         "vars":{
            "event_name":"custom",
            "event_action":"story_progress",
            "event_category":"${title}",
            "event_label":"${storyPageId}",
            "send_to":["UA-XXXXXXXXX-3"]
         }
      },
      "storyEnd":{
         "on":"story-last-page-visible",
         "request":"event",
         "enabled":"true",
         "vars":{
            "event_name":"custom",
            "event_action":"story_complete",
            "event_category":"${title}",
             "send_to":["UA-XXXXXXXXX-3"]
         }
      }
   }
}

**Comment by Enriqe** [comment]
@mszylkowski have we added analytics to the `amp-story-interactive-*` components?

**Comment by mszylkowski** [comment]
@Enriqe Yes that has been integrated since the beginning, check https://github.com/ampproject/amphtml/blob/1ff2dfb860b8d9752cae6292d51b799c4586caa9/extensions/amp-story-interactive/0.1/amp-story-interactive-abstract.js#L517-L536

**Comment by Enriqe** [comment]
Have we also documented those? Would you mind linking them for @abhiz10 please?

**Comment by mszylkowski** [comment]
https://amp.dev/documentation/components/amp-story-interactive/#analytics

**Comment by abhiz10** [comment]
Thank you so much @mszylkowski @Enriqe
