### ISSUE TITLE
amp-animation not working in user-defined templates in GAM

### ISSUE THREAD

**Issue by coreyb-cbs** [ampproject/amphtml#24433]
@lannka  @jasti  @aghassemi I am working on an amp ad product and have a good working test creative built in the system-defined Custom template in GAM. Once the R&D was complete and the ad behaved as desired I moved on to creating a user-defined template so traffickers can generate these ads at scale, but I'm finding that amp-animation / amp-position-observer isn't functioning as the background image isn't parallaxing as you scroll up/down.

demo page:
https://rev.cbsi.com/corey/test/amp/amp_powerbar_321x21.html

that demo page above has two ads in rotation (refresh the page until you see both):
1. built in the system-defined Custom template (Jaguar car bkg image) and has an amp-animation based upon amp-position-observer - working correctly as the background image has a parallex effect
2. built in my user-defined template (blue bkg image with "736x736" text) and has the exact same amp-animation and amp-position-observer codesame code as the functioning creative above - not working correctly as the background image does not move as you scroll up/down

**Comment by coreyb-cbs** [comment]
@lannka @jasti @aghassemi Any thoughts on this bug? If there is someone on the AMP team with GAM expertise can we get their eyes on it? Thanks!

**Comment by jasti** [comment]
Hey @coreyb-cbs, the ad looks great! 
I'm not sure user-defined templates are supported for AMPHTML ads but I'll let @tedherbstman from the Google Ad Manager team comment.

**Comment by jasti** [comment]
Hi Corey, I heard back internally from the Ad manager team and that user-defined templates aren't supported at the moment.
They also requested that you reach out to the account manager in expressing interest and future Ad manager related requests to get the right support and right prioritization. 
Thanks.

**Comment by coreyb-cbs** [comment]
@jasti  Thanks for the response. That's the reply I feared given we couldn't get AMP Story ads working in user-defined templates either. Not being able to churn out amp creatives from user-defined templates in GAM really kills a lot of opportunities.
