### ISSUE TITLE
Feature request: wp amp validate-site should support the ability to only check posts with AMP issues

### ISSUE THREAD

**Issue by archon810** [ampproject/amphtml#24432]
After rolling out AMP on our site with 40k+ posts, we started getting some AMP validation warnings from the AMP WP plugin, and as we were fixing them, it was relatively easy to tap the batch Recheck button in the WP UI to recheck the affected posts.

Then I found out about `wp amp validate-site` and ran it on all 40k+ posts, which generated 500+ urls with AMP warnings and 2000+ errors in the error index.

We started fixing them, but I found that batch rechecking this list from the WP UI is a pain. First, you need to paginate, then Cloudflare kicks in because it takes a long time to run the recheck and the page times out, and in general it's not a very friendly way to run this recheck.

So I suggest an additional parameter to `wp amp validate-site` https://amp-wp.org/documentation/developing-wordpress-amp-sites/wp-cli-commands/, which would only run on posts with AMP issues.

**Comment by westonruter** [comment]
@archon810 Would you please close this issue and re-file on the amp-wp repo? https://github.com/ampproject/amp-wp/issues/new

**Comment by archon810** [comment]
Whoops, my bad. Brainfarted that this is a WP feature because it's cli (but it's WP cli).

**Comment by archon810** [comment]
Opened https://github.com/ampproject/amphtml/issues/24432.

**Comment by archon810** [comment]
Opened https://github.com/ampproject/amp-wp/issues/3227.
