### ISSUE TITLE
The standards/schema seem to require an image for blog posts?

### ISSUE THREAD

**Issue by pembo13** [ampproject/amphtml#2443]
It seems like the Schema for the AMP pages require an image for a blog post, which I don't really understand the motivation of. Why would all blog posts need to have an image? Google's Webmaster tool flags all my AMP pages without images as not valid.

Use case: I have a simple blog post about a problem I ran into and solved building a web application in Django. There by default no image for this kind of post.

**Comment by jridgewell** [comment]
Re: https://productforums.google.com/forum/#!topic/webmasters/2T3-tt2pYtg;context-place=topicsearchin/webmasters/category$3Aaccelerated-mobile-pages-amp%7Csort:relevance%7Cspell:false

**Comment by cramforce** [comment]
AMP certainly doesn't care. Google currently requires this for AMP carousel inclusion. Seems questionable :)
