### ISSUE TITLE
Amp-Ad resize request

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#24446]
## What's the issue?
Multiple Amp-Ad resize request on single page

Briefly describe the bug.
When on an Amp page there will be a few Amp-Ad resize requests

## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. Opt into Canary/RC
2. Open Java Console
3. Go to [link](https://www.google.com/amp/s/amp.cnn.com/cnn/2019/09/10/politics/cnn-poll-trump-reelection-2020/index.html)

## What browsers are affected?
Chrome: 76.0.3809.132
FireFox: 68.0.2

## Which AMP version is affected?
AMP Version: 1909051736590

Note: @lannka is this a client issue or is this specifically Ads?

**Comment by diantekyrie** [comment]
Adding photo of issue.

![Screen Shot 2019-09-16 at 9 22 00 AM](https://user-images.githubusercontent.com/48487406/64975318-94200880-d863-11e9-9217-83b4f206c1ee.png)

**Comment by lannka** [comment]
this is expected logging introduced in #23239 
@dvoytenko shall we remove that now?

**Comment by dvoytenko** [comment]
Yeah. I will remove.

**Comment by dvoytenko** [comment]
Closed via #24860.
