### ISSUE TITLE
amp-access doesn't refresh view after authorisation in iOS 8

### ISSUE THREAD

**Issue by georgecrawford** [ampproject/amphtml#2444]
Our testers are reporting that amp-access is not refreshing the view (i.e. showing/hiding content correctly) after a successful authorisation. The login browser window closes as expected, but the view does not change. Refreshing the page results in the updated, authorised view as expected.

I haven't run this through an inspector to see which amp-access calls are made, but let me know if you need more information.

**Comment by dvoytenko** [comment]
@georgecrawford Could you please confirm that your login dialog returns `#success=yes` hash fragment to our RETURN_URL?

**Comment by rudygalfi** [comment]
Closing because I think this was fixed. Please re-open if that's not the case.

cc @ashwinlimaye
