### ISSUE TITLE
should amp-analytics error when it cant find an element?

### ISSUE THREAD

**Issue by chopki** [ampproject/amphtml#24456]
## Describe the new feature or change to an existing feature you'd like to see

At the moment if you set up more generalised tracking e.g. whenever someone clicks on a link fire an event or whenever a form is submitted send an event and the page requested does not have the element you are tracking on it then an error is recorded:

![image](https://user-images.githubusercontent.com/2270132/64688142-a543d080-d483-11e9-8d40-95e7ebf44de4.png)

Tracking like this needs to be at a global level to catch every possible instance but its quite possible a page may not have one of these tracking items on it so it makes sense to have a mechanism in place to not throw an error as if you were coding this on a non amp page you would just check for the existence of the element before binding the analytics event.

## Describe alternatives you've considered

Should this merely be a warning instead? or an option on the trigger to not care if an element exists e.g. 'throwErrorOnNotFound: false'.

**Comment by micajuine-ho** [comment]
Hi @chopki would it be possible for you to include a code snippet of the analytics config and the relevant html that would me to reproduce this error?
