### ISSUE TITLE
Animation doesn't resume in Edge and Safari

### ISSUE THREAD

**Issue by andrejoblakceltra** [ampproject/amphtml#24455]
## What's the issue?

If you have an amp-animation with infinite loops, animation doesn't resume when you switch to different browser tab and then return to the tab with animation. But it does resume if you do that one more time. We observed this issue on Edge, Internet Explorer 11 and Safari browsers. It works ok on Firefox and Chrome.

## How do we reproduce the issue?

Example which reproduces this issue can be accessed here:
https://www.dropbox.com/s/0h5e8yvcbhw3ypi/edge-animation-bug.zip?dl=0

## What browsers are affected?

Edge, Internet Explorer 11, Safari

## Which AMP version is affected?

Latest version

**Comment by nainar** [comment]
@wassgha could you take a look? This might be a regression
