### ISSUE TITLE
Element toggleClass action stopped to work with classes which start with `amp-`

### ISSUE THREAD

**Issue by OEvgeny** [ampproject/amphtml#24457]
## What's the issue?
We encountered the problem after AMP runtime got updated. I noticed that classes which start with `amp-` (e.g. `amp-opened`) don't work properly with `toggleClass` action anymore.

I checked AMP docs and haven't found any notes about `amp-*` class names are reserved.

## How do we reproduce the issue?
https://jsbin.com/biyuniwawo/edit?html,output

1. Click to "amp-opened" element
2. Click to "am-opened" element
3. Verify text color changed for both elements

## What browsers are affected?

All browsers

## Which AMP version is affected?

I noticed it doesn't work on `1909051736590`.
But it worked previously on `1907161745080`

**Comment by cathyxz** [comment]
This issue should stay open until the fix lands in production.

**Comment by cathyxz** [comment]
Verified that the bug (https://jsbin.com/biyuniwawo/edit?html,output) no longer repros in production.

**Comment by cathyxz** [comment]
Verified that the bug no longer repros in RC.
