### ISSUE TITLE
AMP Stories don't load in iframe if set as data url src

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#24454]
## What's the issue?

When setting the source of an `iframe` as a data URL string containing an AMP Story source code, the AMP Stories don't render. This is the error given:

```
Uncaught Error: failed to call initLogConstructor
    at A (log.js:819)
    at Zd (experiments.js:207)
    at Ld (experiments.js:162)
    at P (experiments.js:73)
    at polyfills.js:49
    at amp.js:66
```

## How do we reproduce the issue?

I created an [example here](https://charles.tappable.link/iframe.html). The first `iframe` has its `src` set to a data url, the second one has its `src` set to the story link itself. Both frames should show the same Story.

## What browsers are affected?

All browsers tested are affected.

## Which AMP version is affected?

The last working release in which the `iframe` data url `src` works is `1908201719490`. From what I could dig up, the issue is related to `custom-elements-v1 ` (#24215) launched in `1908271552560`.

**Comment by choumx** [comment]
Should be fixed by #24468. @jridgewell to confirm.

**Comment by cpauwels** [comment]
@choumx I can confirm it's working again with release `1909141409590`.

**Comment by jridgewell** [comment]
This is actually fixed by https://github.com/ampproject/amphtml/pull/24529, with the tracking bug at https://github.com/ampproject/amphtml/issues/24499.
