### ISSUE TITLE
Always use sendBeacon instead of Image where available

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2446]
Why would one ever want to use Image instead of sendBeacon?

I think we should always use sendBeacon if we can.

@avimehta @rudygalfi Any opinions?

**Comment by avimehta** [comment]
yes. Agreen. GA has an open bug where for sendBeacon requests, our servers respond before we get the full request and that has made us not go full sendBeacon. but overall, we would want to go full sendBeacon where possible.

**Comment by cramforce** [comment]
I don't fully understand: What does "our servers respond before we get the full request" mean?

**Comment by rudygalfi** [comment]
Is the proposal to change the `transport` config options?

**Comment by cramforce** [comment]
Basically to kill the image transport and only use it if sendBeacon is not available.

My main question is: Is there any reason not to do this? Does the image transport do anything that sendBeacon does not?

**Comment by avimehta** [comment]
> Is there any reason not to do this? Does the image transport do anything that sendBeacon does not?

1. sendBeacon is not supported on all browsers.
2. Not many analytics vendors support post yet.

**Comment by rudygalfi** [comment]
Is @avimehta's latest response sufficient or does this need more discussion?

**Comment by igrigorik** [comment]
If sendBeacon supported GET, would this allow us to make it the default for all browsers that support it?

**Comment by dvoytenko** [comment]
@igrigorik I'd think so. I can't think of any reason then not to use it as a default.

**Comment by cramforce** [comment]
Not going there until https://github.com/w3c/beacon/issues/22 is resolved

**Comment by lannka** [comment]
A proposal to implement this is here: #7096
