### ISSUE TITLE
Does AMP contain Google Analytics by default?

### ISSUE THREAD

**Issue by corysimmons** [ampproject/amphtml#2447]
Someone in your https://www.youtube.com/watch?v=hVRkG1CQScA presentation mentions AMP is full of Google tracking/ad stuff. Is this true?

![image](https://cloud.githubusercontent.com/assets/224636/13536318/34f0dbbe-e20d-11e5-87b5-d468ba99c10a.png)

If so, can you explain why it's necessary?

**Comment by corysimmons** [comment]
Also where can I find an un-minified/uglified version of https://cdn.ampproject.org/v0.js ?

**Comment by jridgewell** [comment]
> AMP is full of Google tracking/ad stuff. Is this true?

No, that's not true (answered already [here](https://github.com/ampproject/amphtml/issues/1907#issuecomment-182423845)). The short answer is, that is _just_ a string in the file. The DoubleClick/"Google" tracking **does not** run unless you add a `<amp-ad type="doubleclick" />` tag to your page. That is, it runs after you tell it to.

> Also where can I find an un-minified/uglified version of https://cdn.ampproject.org/v0.js ?

I don't believe we publish an un-minified version. But, the source code is all in this repo.

**Comment by cramforce** [comment]
No, it doesn't. This is the entry point to v0.js https://github.com/ampproject/amphtml/blob/master/src/amp.js

AMP ships with this file https://github.com/ampproject/amphtml/blob/master/ads/_config.js#L25 which **if** a page contains one of those features, make preconnect/preload requests to thoses hosts/URLs.

Feel free to include this github URL on that YT thread.

**Comment by corysimmons** [comment]
Cool, I suspected that's how you guys would handle it. :100: 

Very sorry I forgot to grep issues before asking.

**Comment by rmaddox** [comment]
Is it possible to host the .JS files myself? In that case I can remove references to Google

**Comment by cramforce** [comment]
@rmaddox Yes, but not if you want it to be a valid AMP file (as in passing the validator, because it requires including the JS from a central CDN). It would work fine from a rendering perspective.

**Comment by rmaddox** [comment]
Thank you, very helpful.

**Comment by cramforce** [comment]
As of last week, the ads code was removed from AMP core and must be explicitly loaded as an extension, so none of the above is included anymore unless pages ask for it.
