### ISSUE TITLE
🌸 Cherry-pick request for #24513 into #24438 (Approved)

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#24470]
# Cherry-pick request

| Issue | PR  | Production? | RC? | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---: | :-: | :---------: | :-: | :-----------: |
| #24462 | #24513 | No | No | #24438 |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

Any page that uses `amp-mustache` and gets selected for the canary diversion will fail to render any templates.

## Why is a RC cherry-pick not needed?

The experiment is only enabled in Canary.

## Summary

We're experimenting with a new Custom Elements V1 Polyfill, currently only enabled in Canary. Any page that uses `amp-mustache` and gets selected for the canary diversion will fail to render any templates. This is caused by an over-eager upgrade of custom elements inside the template's distinct `document`.

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by choumx** [comment]
Curious why integration/visual tests didn't catch this. We should consider cherry-picking a PR that turns off the experiment until we have confidence of good component coverage through the new code paths.

**Comment by jridgewell** [comment]
@estherkim Are integration tests run with `getMode().test` enabled?

**Comment by estherkim** [comment]
Yep just checked on Travis, they are. https://github.com/ampproject/amphtml/pull/24484

**Comment by jridgewell** [comment]
Then our tests should be running with CEv1 polyfill: https://github.com/ampproject/amphtml/blob/d10f092483c487e15acd8555b00b3a464f0b0064/src/polyfills.js#L48-L52

Are there integration tests for amp-mustache?

**Comment by cathyxz** [comment]
Per discussion offline with @choumx @danielrozenberg, let's cherry pick https://github.com/ampproject/amphtml/pull/24513 to turn off the `custom-elements-v1` experiment until we have better test coverage. I am editing this cherry pick issue to refect that.

**Comment by cathyxz** [comment]
Approving this cherry pick to canary as a member of @ampproject/wg-approvers, but since I made this change, can a second member of @ampproject/wg-approvers also LGTM this? 

> For cherry picks into canary, at least one member of the Approvers WG must approve the cherry pick.

Reference: https://github.com/ampproject/amphtml/blob/7ac6a2a627e76f03440aeb197bc268b11149d48f/contributing/release-schedule.md#cherry-pick-criteria

**Comment by choumx** [comment]
Approved :)
