### ISSUE TITLE
🌸 Cherry-pick request for #24466 into #24352 (Approved)

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#24483]
# Cherry-pick request

| Issue | PR  | Production? | RC? | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---: | :-: | :---------: | :-: | :-----------: |
| #24457 | #24466 | **YES** | **NO** | #24254 |
| #24457 | #24466 | **NO** | **YES** | #24438 |
## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

We disabled toggle on `amp-*` and `*-amp-*` CSS classes, which are not internally reserved CSS classes as part of disabling internal CSS classes. This caused a regression for users relying on toggling `amp-*` classes.  

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

<_YOUR_SUMMARY_>

| Users affected | Impact |
| -------------- | ------ |
| <_Which users were affected? Roughly how many?_> | <_How were users affected? E.g. partial or complete loss of functionality?_> |

## Root Causes

1.

## Action Items

| Action Item | Type | Owner | PR # |
| ----------- | :--: | :---: | :--: |
| <_E.g. Add integration test_> | <_Investigate/Mitigate/Prevent_> | @<_USERNAME_> | #<_PR_NUMBER_> |

### Things that went well

-

### Things that went wrong

-

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers @nainar @leafsy

**Comment by cramforce** [comment]
Approved

**Comment by cathyxz** [comment]
The fix has now landed in all applicable releases. Assigning back to myself for post-mortem.
