### ISSUE TITLE
`gulp dist` is frequently timing out on Travis

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#24487]
For example:
https://travis-ci.org/ampproject/amphtml/jobs/583921852
https://travis-ci.org/ampproject/amphtml/jobs/581750275
https://travis-ci.org/ampproject/amphtml/jobs/581434498
https://travis-ci.org/ampproject/amphtml/jobs/583763000

```
dist-bundle-size.js: Running gulp dist --fortesting...
[00:34:44] Using gulpfile ~/build/ampproject/amphtml/gulpfile.js
[00:34:44] Starting 'dist'...
[00:34:54] Performing multi-pass babel transforms in /tmp/c087c16580ed7d5f2d7cf1f10ed49845
.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[00:35:39] Minifying multi-pass JS with closure-compiler
...............................................................................................................................................................
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by rsimha** [comment]
Some ideas:
- Enable verbose logging to see which step is stalling
- Reduce `MAX_PARALLEL_CLOSURE_INVOCATIONS` and see if it makes a difference

**Comment by rsimha** [comment]
Here's an instance of a stalled `gulp dist` from today, reported by @estherkim: https://travis-ci.org/ampproject/amphtml/jobs/586175076#L516

Current plan: Split this `Promise.all()` into pieces to shed light on which step stalled.

https://github.com/ampproject/amphtml/blob/8b7ecde386bc702b4c429a0e8a11a77747d53ab8/build-system/tasks/dist.js#L135-L146

**Comment by rsimha** [comment]
First run on `master` looks good: https://travis-ci.org/ampproject/amphtml/jobs/586563191#L509

Will continue to look out for stalled builds.

**Comment by rsimha** [comment]
@estherkim just found a stalled build. This was the state after 5 minutes of waiting.

![image](https://user-images.githubusercontent.com/26553114/65283382-fd727680-db04-11e9-9122-020b7639546a.png)

Here's the code:

https://github.com/ampproject/amphtml/blob/6695c980b71570a634f252235d87f73cd8c00b80/build-system/tasks/dist.js#L143-L150

Seems like line 149 executed, but line 150 got stuck. I'm going to try and make it non-blocking.

**Comment by rsimha** [comment]
Turns out it wasn't nailgun after all, which means the call to `buildExtensions` did not return. Since it is highly parallel across cores, the next step is to temporarily reduce / eliminate closure concurrency on Travis and see if it makes a difference. Additional logging would be useful too.

**Comment by estherkim** [comment]
Sanity check here - are we sure it's not nailgun? Per https://github.com/ampproject/amphtml/commit/f480db0d43b826b58e1e23515d6201cb64bff797, there should be something logging at the end of `stopNailgunServer()`, right? But this stalled build is missing that - https://travis-ci.org/ampproject/amphtml/jobs/588052454

**Comment by rsimha** [comment]
Here's why I believe it's not nailgun:
1. If `buildExtensions()` had exited cleanly, `stopNailgunServer()` would've run for at most 5 seconds before printing a success or a timeout message. (Neither message was printed.)
2. If OTOH, `buildExtensions()` was waiting on an unfinished promise, it would print all the `Minified so-and-so extension` messages and stall.

My suspicion is that 2 is true today. Unless you think I'm missing something, and that it could still be 1?

**Comment by estherkim** [comment]
Ohhh `buildExtensions()` needs to return before `stopNailgunServer()` starts. Got it!

**Comment by rsimha** [comment]
Yeah :)

Unfortunately, my attempted changes in #24662 seem to be breaking single-pass. I meant to try and reduce the scope of the changes and check it in, but I won't get to it until next week. Feel free to take over or replace the PR if this becomes a blocker and you end up finding a better way to solve.

**Comment by rsimha** [comment]
Haven't seen any stalled builds since #24662 was merged. Closing until we see this again.

**Comment by rsimha** [comment]
Reopening this due to a higher than normal incidence of stalled builds on Travis:

![image](https://user-images.githubusercontent.com/26553114/80648013-6e83f000-8a3d-11ea-9473-3e6af8a70350.png)

There are documented instances of concurrency problems with our custom closure compiler `runner.jar`. Actually solving this problem needs us to eliminate `AmpPass.java` (#24047), which is currently blocked by #23960.

Meanwhile, I'm going to reduce closure concurrency on Travis from 4 to 2, to match the [number of cores](https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system) in the default Xenial VMs.

**Comment by rsimha** [comment]
5 out of 5 invocations of `gulp dist` on `master` were green after closure concurrency was reduced by #28114.

https://travis-ci.org/github/ampproject/amphtml/jobs/681230265
https://travis-ci.org/github/ampproject/amphtml/jobs/681236023
https://travis-ci.org/github/ampproject/amphtml/jobs/681236195
https://travis-ci.org/github/ampproject/amphtml/jobs/681237191
https://travis-ci.org/github/ampproject/amphtml/jobs/681237628

This is no longer a problem for the time being.

For a proper long-term fix, see https://github.com/ampproject/amphtml/pull/27821#issuecomment-621488829.

**Comment by rsimha** [comment]
Reopening yet again because this is still rearing its head:

![image](https://user-images.githubusercontent.com/26553114/81106984-6ff16480-8ee4-11ea-82af-19fcf8c68e0c.png)

A long-term fix for this is to move to the native closure compiler. Currently blocked by #28173 and #28172.

**Comment by rsimha** [comment]
We've been using native closure for a few months now. Closing.
