### ISSUE TITLE
Valid schema.org markup failing amp validation

### ISSUE THREAD

**Issue by nikse** [ampproject/amphtml#2449]
I have some meta tags containing schema.org data in my markup like so 

```
<div class="article-route" itemscope="true" itemtype="https://schema.org/NewsArticle">
<meta itemscope="true" itemprop="mainEntityOfPage" itemtype="https://schema.org/WebPage" itemid="#{url}">
...
</div>
```

My html validates through the schema.org validator, so I would expect it to validate through the amp validator yet I am getting these errors

```
The mandatory attribute 'charset' is missing in tag 'meta charset=utf-8'. (see https://www.ampproject.org/docs/reference/spec.html#required-markup)

The parent tag of tag 'meta' is 'div', but it can only be 'head'. (see https://www.ampproject.org/docs/reference/spec.html#required-markup)
```

**Comment by Gregable** [comment]
My understanding is that schema.org `<meta>` tags all have a content attribute. These validation errors are confusing your `<meta>` tag with one for setting the charset, which must be in the head. If you add a `content` attribute, it should validate. The error should be improved.

If this still isn't the right validation logic, please reopen.
