### ISSUE TITLE
Can not make amp-ad be less than screen width.

### ISSUE THREAD

**Issue by tranvansang** [ampproject/amphtml#24491]
##  What's the issue?

Currently, `amp-ad` tag requires width be `100vw`, and height be `300px`.
In my website, I want to put the ad in the sidebar whose width is one third of screen size.

For example, the followig snippet does not work

```html
<div style="width: 30%; height: 300px;">
  <amp-ad layout="fill"/>
</div>
```

Here is the line of code which logs out error

https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js#L232

## How do we reproduce the issue?

This is the production page of out website. Currently, the ad take full width of the screen and overlaps other text.

https://carstay.jp/ja/media/vanlife/5d751ab4a9d7d30b2a294380/amp

Note: the site may change in future (e.g. when the bug is fixed)

## What browsers are affected?

All browsers

## Which AMP version is affected?

Version 1909051756330

**Comment by 2shrestha22** [comment]
This in not any bug. AMP is targeted for mobile phones and Google AdSense gives ad code that uses 100vw. You are using AMP in desktop too so you are getting this problem. I had similar problem, however I solved it and wrote about this solution here - https://sangams.com.np/how-to-make-adsense-work-with-amp-desktop-version/

**Comment by HUKE1987** [comment]
I have the same problem
