### ISSUE TITLE
Visual diff tests should run in beta browser versions as well

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#24516]
Currently our Visual Diff tests only test the current browser versions. 

We should be one step ahead and running tests on beta/preview versions. 

Canary is a step too far (too much noise.)

cc @ampproject/wg-infra @rsimha @estherkim

**Comment by danielrozenberg** [comment]
Unfortunately Percy doesn't support beta browsers, so this is blocked until they do

**Comment by danielrozenberg** [comment]
This is related to #20713. We asked Percy to support beta and legacy browsers and they said they'll consider it

**Comment by cortisiko** [comment]
Hey guys any update here?

**Comment by danielrozenberg** [comment]
This is blocked on support from Percy, the service we're using for visual diffs. The good news is that they recently got acquired by BrowserStack and are planning on adding support for more browsers soon!

**Comment by cortisiko** [comment]
Sweeet, Thanks @danielrozenberg
