### ISSUE TITLE
FR - Support for client-hints in AMP

### ISSUE THREAD

**Issue by demianrenzulli** [ampproject/amphtml#24520]
## Describe the new feature or change to an existing feature you'd like to see

[Client hints](https://developers.google.com/web/updates/2015/09/automating-resource-selection-with-client-hints) are a  way to implement adaptive loading in websites.

Before receiving them, a site needs to go through an initial negotiation step, by specifying which hints to receive in the `Accept-CH` and `Accept-CH-Lifetime` headers in a resource response, or by using the corresponding meta `http-equiv tags`.

Currently AMP presents some limitations to use client hints (see next section). 
Enabling them would allow for the following use cases:

- **Paired AMP sites**: Performing the negotiation step, while users are visiting AMP Pages, so that, when they navigate to the non-AMP site, they can start receiving hints in the first request.
- **AMP-First sites**: Using client hints, to serve different assets or different versions of the page to users according to network, memory, and other conditions.

## Tests

[This Glitch project](https://glitch.com/edit/#!/join/6b031b8d-489c-4e13-a2f4-3611baaa8c9f) contains 3 tests. Each of them tries a different way of implementing client hints: in the response of the HTML document, in the response of amp-list and by using a `http-equiv` HTML Tag.

- [Test 1](https://amp-client-hints.glitch.me/page1): Sends `Accept-CH` header in the page's response. Reloading the page shows the client hints (`rtt`, `ect`, etc) sent in the header of the HTTP request. This works well when users visit AMP from origin, but won't persist the hints in AMP Cache to origin scenarios.

- [Test 2](https://amp-client-hints.glitch.me/page2): Sends `Accept-CH` header in the response from amp-list. When reloading the page shows the client hints (`rtt`, `ect`, etc) are not sent in the header of the HTTP request (this could be a bug).

- [Test 3](https://amp-client-hints.glitch.me/page3): Uses the HTML`http-equiv` meta tag, which breaks validation.
**Note:** Enabling this can be useful for AMP-First sites, but won't fix AMP Cache to Origin scenarios.

## Conclusion

The conclusion of these tests is that there are things that could be done to give better support for client hints to AMP-First sites (allowing the `http-equiv` HTML meta Tag, and letting hints be used in the amp-list response).

Enabling the AMP Cache to origin scenario can be more complicated, since the the client hints registration is double-keyed. Meaning, if publisher-cached-url.com fetches publisher-origin.com/resources which registers for hints, that registration is scoped to publisher-cached-url.com.

An alternative we've discussed (but haven't tested deeply) would be using an iframe that opens a URL in the publisher's origin, where the client hints negotiation could takes place (similar to what amp-install-serviceworker does to register the SW from the AMP Cache). 
This would mean creating an `<amp-client-hints>` component to encapsulate this logic.

cc // @igrigorik

**Comment by igrigorik** [comment]
* (2) is [WAI](https://github.com/yoavweiss/client-hints-infrastructure#opt-in-mechanism).
* AMP should definitely allow and support (3) to enable site owners to use `http-equiv` meta tag to opt-in to receive hints.

**Comment by jridgewell** [comment]
> 1. Sends Accept-CH header in the page's response.

WAI.

> 2. Sends Accept-CH header in the response from amp-list

This will only ever register the amp-list's endpoint for CH. Refreshing the page won't cause CH to be sent, only the amp-list's next fetch will trigger them.

> 3. Uses the HTML http-equiv meta tag, which breaks validation

We can add validation support for this, but it would need to be stripped from cache. /cc @Gregable. 

> Enabling the AMP Cache to origin scenario can be more complicated, since the the client hints registration is double-keyed.

If the registration is double keyed, there is no way to support the cache to origin transition. An iframe will created from `publisher-cached-url.com` to `publisher.com`, that iframe will be keyed by `publisher-cached-url.com`. Navigating to `publisher.com` will look up the wrong key.
