### ISSUE TITLE
Will Google rank AMP pages higher? If so, how much?

### ISSUE THREAD

**Issue by corysimmons** [ampproject/amphtml#2453]
I've been trying to track down the answer to this for a while and no one really seems to know.

The general guess is that AMP pages will be ranked higher, but no one can say for sure.

The closest I've gotten to a real answer is "If 2 pages are identical, and one is faster than the other. We'll rank that page higher." but that's not very helpful (what makes 2 pages identical?) or explicit about how the ranking actually works.

I'm sure it's an ever-evolving thing and I'm not asking anyone to open source Google's PageRank algorithm but it would be nice to know just how important AMP pages are to PageRank.

Will it rank AMP pages higher just on mobile? Or on desktop as well?

I'm sure a lot of people have a lot of questions about exactly what Google is going to do.

It'd just be nice if there was less obfuscation around this in general.

**Comment by cramforce** [comment]
Please ask over at Google. This is the AMP open source project and it doesn't know anything about Google Search.

https://productforums.google.com/forum/#!topicsearchin/webmasters/category$3Aaccelerated-mobile-pages-amp%7Csort:relevance%7Cspell:false

The short answer to your question is that AMP is not currently a ranking factor in Google Search and "If 2 pages are identical, and one is faster than the other. We'll rank that page higher." is correct.
