### ISSUE TITLE
QUERY_PARAM should support + (plus) encoding

### ISSUE THREAD

**Issue by mattwomple** [ampproject/amphtml#24534]
## Describe the new feature or change to an existing feature you'd like to see

`+` and `%20` are both recognized as the space character in URL encoding \([MDN reference](https://developer.mozilla.org/en-US/docs/Glossary/percent-encoding)\). `QUERY_PARAM` variable substitution recognizes `%20` and does not re-encode the `%` symbol on substitution, but it unfortunately encodes `+` as `%2B`. Below is a minimal example where `QUERY_PARAM` is used in `amp-list`:

- `%20` space: [android.cmphys.com/temp/amp-form-ex.html?q=my%20search](https://android.cmphys.com/temp/amp-form-ex.html?q=my%20search)  
Resulting `amp-list` URL: `https://ampsupport.wompmobile.com/echoquery/dictionaryformat?q=my%20search&__amp_source_origin=https%3A%2F%2Fandroid.cmphys.com`
- `+` space: [android.cmphys.com/temp/amp-form-ex.html?q=my+search](https://android.cmphys.com/temp/amp-form-ex.html?q=my+search)  
Resulting `amp-list` URL: `https://ampsupport.wompmobile.com/echoquery/dictionaryformat?q=my%2Bsearch&__amp_source_origin=https%3A%2F%2Fandroid.cmphys.com`

## Additional context

The sample form in the AMP page linked above is a good example because form submission uses `+` for spaces in many browsers. As an example, try typing `my search` in the text input and notice that the form submission takes you to `https://android.cmphys.com/temp/amp-form-ex.html?q=my+search`.

**Comment by zhouyx** [comment]
Looks like a common use case in form to encode space to `+`. However I'm concerned to just change the generic behavior because it can break the existing use case. Would it be possible for decode %2B on server side? 

to @ampproject/wg-ui-and-a11y, and @caroqliu for a form specific solution. (maybe a new attribute).

**Comment by mattwomple** [comment]
My original post could have been written better. Here's a more accurate depiction of the problem with AMP's implementation of `QUERY_PARAM` variable substitution.

`QUERY_PARAM` does not decode `+` as the space character. Instead, it treats it like a literal plus character. Consider a GET request to an AMP page: `https://amp.dev?q=a+b`. When `QUERY_PARAM` is used to forward parameters to another server, for example in the `src` attribute of an `<amp-list>`, the value of the parameter is mangled: `https://example.com?q=QUERY_PARAM(q)` becomes `https://example.com?q=a%2Bb`. This is simply incorrect handling of GET parameter values. It should not be the responsibility of the server at `example.com` to recognize `%2B` as a space character; `%2B` is a plus character.

Pull request #24626 resolves this issue by treating incoming GET parameter values with `+` encoding for spaces the same as [`URLSearchParams.get()`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/get). Give this a try in your browser of choice:

    const url = new URL('https://example.com?q=a+b%20c%2Bd');
    url.searchParams.get('q');

You'll invariably see output: `a b c+d`. I would hope that this would be enough justification for fixing the behavior of `QUERY_PARAM`.

Consider further that GET `form` submissions are a common means of directing users to URLs with query parameters. All of the browsers that I've tested today (Edge 15, Firefox 69, Chrome 78, Safari on iOS 11) encode spaces in inputs of GET `form` submissions as `+` \(also see [MDN's article on Percent-encoding](https://developer.mozilla.org/en-US/docs/Glossary/percent-encoding)\).

I have seen two comments now: "This isn't a safe change for all callers" and "it can break the existing use case", but neither presents an actual use in AMPHTML that would be broken.

To be clear, I'm not advocating for the AMP project to change all URL _encoding_ to use `+` instead of `%20`, but _decoding_ should be handled properly.

**Comment by jridgewell** [comment]
> Give this a try: `url.searchParams.get('q')`

Ok, it seems ok to follow the URL parsing spec here. Note though, that it has another quirk: You have to run `unescape(decodeURIComponent(str.replace(/\+/, ' ')))` to decode UTF-8 encoded sequences that are precent encoded. Craziness.

**Comment by mattwomple** [comment]
> Note though, that it has another quirk

Do you have an example? This appears to work as expected in Chrome 77:

    let enc = encodeURIComponent('✨');

Value of `enc`: `%E2%9C%A8`

    let dec = decodeURIComponent('%E2%9C%A8');

Value of `dec`: ✨

    decodeURIComponent(encodeURIComponent('✨')) === '✨'

`true`

Maybe browser-specific handling of sequences of percent encoded characters?

**Comment by jridgewell** [comment]
Never mind, I misinterpreted the spec. Just a `decodeURIComponent` should be all that's necessary.

**Comment by zhouyx** [comment]
Thanks for the detailed explanation. I think this is fine as long as we are only changing the decoding behavior.

**Comment by mattwomple** [comment]
Bump. I haven't seen further push-back on either PR #24626 or this issue report. Please let me know if anything more is needed from me.
