### ISSUE TITLE
Get link not working of bookend of story on chrome.

### ISSUE THREAD

**Issue by Avdhoot05** [ampproject/amphtml#24537]
1. Open the story in chrome
2. Go at the end of story
3. In chrome,Get link not working 

## What browsers are affected?
Chrome

![BookendJson](https://user-images.githubusercontent.com/46551690/64937261-3ac1d480-d877-11e9-95b8-cc4bea89d1be.PNG)

**Comment by newmuis** [comment]
@estherkim is this a duplicate?

**Comment by estherkim** [comment]
Yes it's a duplicate. The fix is in the RC and Dev channels, but not in production yet. The release that contains the fix is here - https://github.com/ampproject/amphtml/releases/tag/1909141409590

**Comment by newmuis** [comment]
Thanks!  Closing for now; feel free to reopen if this can still be  reproduced when `1909141409590` is in production, which should be in a week or less.
