### ISSUE TITLE
🌸 Cherry-pick request for #24529 into #24254 (Approved)

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#24530]
# Cherry-pick request

| Issue | PR  | Production? | RC? | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---: | :-: | :---------: | :-: | :-----------: |
| #24499 | #24529 | **YES** | **NO** | #24254 |
| #24499 | #24529 | **NO** | **YES** | #24438 |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

Users that have 3p cookies turned off (eg, for privacy reasons) were broken due the order in which code initializes.

# Mini-postmortem

## Summary

AMP launched a Custom Elements v1 experiment in 1908271552560. Part of determining whether this experiment should be used is to read from the global `AMP_CONFIG` flags, and to allow local overriding, to read from `localStorage`.

In order to install the polyfill, this experiment read must happen during page initialization. Unfortunately, an error occurs when reading from `localStorage` in some browsers, causing an error that should have been recoverable. But the logging code that itself then threw an error, causing an unrecoverable error.

| Users affected | Impact |
| -------------- | ------ |
| Anyone with 3p cookies disabled in Chrome | Empty pages |
| Anyone for which accessing `localStorage` throws an error | Empty pages |

## Root Causes

- an experiment was added to switch to a new custom element polyfill
- it being a polyfill the check whether to use the new or old has to happen
very early in program init
- the experiment code reads from localStorage to see if the experiment is on
- this read fails in 3p context if 3p cookies are disabled
- the failure is caught and an error is logged. The program is supposed to
continue as normal
- unfortunately, the logging system hadn't been initialized yet because
this read happens to early that init depends on code order that the
compiler determined
- fail

## Action Items

| Action Item | Type | Owner | PR # |
| ----------- | :--: | :---: | :--: |
| <_E.g. Add integration test_> | <_Investigate/Mitigate/Prevent_> | @<_USERNAME_> | #<_PR_NUMBER_> |

### Things that went well

-

### Things that went wrong

-

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

Fixes #24499

**Comment by cramforce** [comment]
Approved

**Comment by cramforce** [comment]
CC @rsimha @jridgewell 

Some notes for the postmortem

- We have no test coverage for chrome set to reject 3p cookies.
- That our log code requires a function to be called before logging works is super brittle and needs to change.
- I'm somewhat surprised that `dev().warn()` stays in prod code.

**Comment by rsimha** [comment]
> * We have no test coverage for chrome set to reject 3p cookies.

Here's the  `puppeteer` tracking issue for disabling 3p cookies: https://github.com/GoogleChrome/puppeteer/issues/3998. Doesn't seem straightforward, but it might be possible to do so from an E2E test.

@estherkim Was this something you looked into while working on `puppeteer` + E2E?

**Comment by cramforce** [comment]
Another option may be to monkey patch `localStorage.get/setItem` to throw. A real environment would be preferred, of course.
