### ISSUE TITLE
<amp-selector>: GSC giving error while amp validator is passing

### ISSUE THREAD

**Issue by pranjalk** [ampproject/amphtml#24540]
## What's the issue?

**amp-selector** **_option_** / _**selected**_ attributes are giving error in google search console while ampproject validator is passing

## How do we reproduce the issue?

1. Open https://www.practo.com/tests/amp/hiv-western-blot-blood/p in AMP validator it passes
2. Open the same in search console it gives the following error

<img width="1280" alt="Screen Shot 2019-09-16 at 12 03 51 PM" src="https://user-images.githubusercontent.com/6200009/64941272-c93c5300-d883-11e9-8955-d6c680fadb2f.png">

## What browsers are affected? **None**

All browsers? Some specific browser? What device type? **Not Applicable**

## Which AMP version is affected?

New Issue first noticed on 2019-09-15 **Version 1909141411050**

**Comment by honeybadgerdontcare** [comment]
@pranjalk if you are still seeing this issue please reopen.
