### ISSUE TITLE
markdown version required for AMP

### ISSUE THREAD

**Issue by ghost** [ampproject/amphtml#2455]
Thank you Malte, you are very helpful. The idea is basically in the core of HTML idea, but due to all varieties, HTML is too bloated for mobile devices.

The problem is that content is mostly in markdown on my side, so I am now in need to find a way, to get new version of markdown producing these kind of tags.

I am thinking now of making custom writer with pandoc:

```
pandoc --print-default-data-file sample.lua > sample.lua
```

and changing it to support amp tags, I don't think I need long time. We will see. Many things to solve in the CMS that I use. But I am moving forward.

If you know working markdown for AMP, let me know.

**Comment by cramforce** [comment]
I don't, but that would be really nice!

**Comment by rmaddox** [comment]
The above solution with pandoc is possible, but I will rather make it in Guile http://www.gnu.org/software/guile/ and let you know.

**Comment by puppetmaster3** [comment]
+1. Markdown to AMP flavor, for example of <IMG/>

**Comment by kristoferbaxter** [comment]
Closing out this issue, if someone would like to create a Markdown format supporting Custom Elements and AMP please let us know and we'll reopen it.
