### ISSUE TITLE
No messaging channel: initMessagingChannel​​​

### ISSUE THREAD

**Issue by VMBindraban** [ampproject/amphtml#24577]
# What's the issue?

Suddenly this error showed up in my console multiple times.
I have no idea where this is coming from but they started when i began experimenting with `amp-app-banner`. I removed this component and the error still show up sometimes.

```
log.js:688 Uncaught (in promise) Error: No messaging channel: initMessagingChannel​​​
    at Ra (log.js:688)
    at Ma.f.createError (log.js:333)
    at timer-impl.js:142
    at timer-impl.js:83
```

https://raw.githubusercontent.com/ampproject/amphtml/1909141411050/src/log.js
https://raw.githubusercontent.com/ampproject/amphtml/1909141411050/src/service/timer-impl.js

## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. 🤷‍♂ 

## What browsers are affected?

Chrome 76.0.3809.132

## Which AMP version is affected?
1909141411050

**Comment by choumx** [comment]
Please provide a URL to a reproduction case.
