### ISSUE TITLE
amp-iframe Safari browser back problem with amp-bind

### ISSUE THREAD

**Issue by LNHarders** [ampproject/amphtml#24580]
## What's the issue?

If there are two amp-iframes on one page and you click a link while one is hidden, the amp-iframes switch content when you go back to that page. The problem only occurs when amp-bind is used.

## How do we reproduce the issue?

[test.html.zip](https://github.com/ampproject/amphtml/files/3620740/test.html.zip)

1. open the attached file
2. follow the instruction on the page
3. repeat if nothing happened (maybe try to clear the cache)

## What browsers are affected?

Safari (seen on two different machines with version 12.1.2 on Mac OS X 10.14)

## Which AMP version is affected?

Latest version (Version 1909141411050)

**Comment by choumx** [comment]
I can't reproduce this on Safari 13.1. Sounds like a very surprising if it did.
