### ISSUE TITLE
How to integrate LeadPages embed script to AMP HTML

### ISSUE THREAD

**Issue by Debuggingyourcode** [ampproject/amphtml#24581]
II want to add leadpages embed script to amp HTML page, here my script

`<script src="https://static.leadpages.net/leadboxes/current/embed.js" async></script>`

Let me know how we add this script.

**Comment by choumx** [comment]
https://support.leadpages.net/hc/en-us/articles/115000463348-Publish-your-pop-ups

Looks like you can use [amp-iframe](https://amp.dev/documentation/components/amp-iframe/) to embed this UI widget. Please ask future questions on [StackOverflow](https://stackoverflow.com/questions/tagged/amp-html).
