### ISSUE TITLE
Handling mailto: and standard other non-http in embedded documents

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#2458]
On Desktop (Chrome), `mailto:` protocol can be handled by webapps like Gmail or Inbox. 

In embedded AMP docs, this breaks if the links didn't have `target="_blank/_top"`, because the embedded iframe will try to embed Inbox or Gmail and fail.

This is not an issue in the Google Search Carousel since it adds _blank to all links. 

We need to either handle this better, document or validate that `mailto:` links have `target="_blank"`.

Other ideas?

**Comment by jridgewell** [comment]
Can't webapps be responsible for any arbitrary protocol? I think we might just need a whitelist (similar to our iOS whitelist) that we allow embedded links, and treat everything else as `_blank`.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please verify first whether the feature proposal is still relevant.

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
