### ISSUE TITLE
PWA: Navigating shadow docs causes Safari tab crash & reload

### ISSUE THREAD

**Issue by Joelsz** [ampproject/amphtml#24594]
## What's the issue?

We have set up our PWA to use AMP as a data source via AMP Shadow. While testing the implementation we discovered that AMP Shadow doesn't behave well when navigating through multiple AMP Shadow instances, that is when navigating from an AMP Shadow page to another one via the SPA shell the browser crashes and restarts itself with the following native message "A Problem has occurred with this webpage so it was reloaded".

This could happen going from the second AMP Shadow instance to the third one and sometimes even from the first instance to the second one.

## Technical details

When the user taps on a link within the AMP Shadow page that is linking to another AMP Shadow page, we kill the AMP Shadow instance using the `ampShadow.close()` method, and additionally we also add an asynchronous wait time of 50ms as suggested by one of the great AMP engineers, then we start the process of loading and injecting the new AMP Shadow instance.

We are using the streaming API, not involving the non-streaming API because of [this](https://github.com/ampproject/amphtml/blob/master/spec/amp-shadow-doc.md#api)

> Once streaming API graduates from experimental, the non-streaming API will be deprecated.

This issue seems to be happening specifically on iOS but might be on other OS or browsers as well while we didn't notice anything yet (we stopped testing for now because of this issue).

This issue might be related to #23575 and please see our code setup over there as it's the same codebase.

## How do we reproduce the issue?

See above how going from Shadow to Shadow breaks the page quite often.

## What browsers are affected?

Safari on iOS

## Which AMP version is affected?

Powered by AMP ⚡ HTML shadows – Version 1909051756330

**Comment by choumx** [comment]
@Joelsz Do you have a sharable URL that reproduces this bug?

**Comment by Joelsz** [comment]
> @Joelsz Do you have a sharable URL that reproduces this bug?

Unfortunately no. We have not published it yet.

**Comment by Joelsz** [comment]
This is the message we're getting on iOS.

![IMG_0458](https://user-images.githubusercontent.com/6243173/66588365-4cd32200-eb5a-11e9-8d39-31ef0d511d47.jpg)

**Comment by Joelsz** [comment]
This is no longer an issue for us. Feel free to reopen if needed.
