### ISSUE TITLE
Mention related tag in error message

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#246]
E.g. in DISALLOWED_ATTR and INVALID_ATTR_VALUE

**Comment by cramforce** [comment]
Friendly ping :)

**Comment by powdercloud** [comment]
Sorry to sit on it. Any preferences for a format?
testfile:1:25 DEPRECATED_ATTR foo in tag bar - use x instead
testfile:1:25 DEPRECATED_ATTR bar.foo - use x instead
testfile:1:25 DEPRECATED_ATTR bar::foo - use x instead
testfile:1:25 DEPRECATED_ATTR bar[foo] - use x instead

**Comment by cramforce** [comment]
Sorry, for not responding. This is in the works, right?

**Comment by powdercloud** [comment]
Yes I think this is done - especially in the Javascript / Chrome Developer console.

E.g. see this example:
https://github.com/ampproject/amphtml/blob/master/validator/testdata/feature_tests/several_errors.out

**Comment by powdercloud** [comment]
I'll go ahead and close it, feel free to reopen / make a new one as you see fit.

**Comment by cramforce** [comment]
This looks so much better. Awesome and thank you!!!!
