### ISSUE TITLE
Easylist blocks Twitter embeds when used in AMP

### ISSUE THREAD

**Issue by archon810** [ampproject/amphtml#24611]
Follow-up to https://github.com/ampproject/amphtml/issues/24429 and https://github.com/ampproject/amphtml/issues/8311.

I found that Easylist blocks Twitter embeds when used in AMP.

Script being blocked: https://3p.ampproject.net/1909141409590/f.js.

Filter: ||ampproject.net^*/f.js

Filter list: EasyList 

Example: https://www.androidpolice.com/2019/09/09/puma-michael-kors-armani-dieel-snapdragon-wear-3100-ifa/?amp.

![image](https://i.imgur.com/1pHkVhD.png)

Here, the Twitter embed, a necessary element, is being blocked because of Easylist.

Without AMP: https://www.androidpolice.com/2019/09/09/puma-michael-kors-armani-dieel-snapdragon-wear-3100-ifa/, the embed is there just fine.

![image](https://i.imgur.com/FBAtViz.png)

Thanks in advance for fixing.

In the meantime, I filed a bug with them here: https://forums.lanik.us/viewtopic.php?f=64&t=43520, but I suspect we can fix it in AMP instead.

**Comment by archon810** [comment]
For you, @sebastianbenz?

**Comment by sebastianbenz** [comment]
Thanks for reporting @archon810! You've already done all the work :-). I'll leave this issue open until the report in the easy list forum has been resolved.

**Comment by archon810** [comment]
Well, I wasn't sure if it's possible to resolve it another way on AMP's side like you've done in the other tickets - I'm not sure what other things f.js contains and if EasyList will choose to stop blocking it, for example. If they don't, we may need to split up whatever they consider tracking/advertising-related and things like Twitter embed support.

**Comment by archon810** [comment]
Easylist dev removed the offending filter.

Woo! 

https://github.com/easylist/easylist/commit/bf4747b7f7c14eed3b1a2612b4ff04cca26db13a

**Comment by archon810** [comment]
I'll close this once the filter update is pushed out to users. Right now it hasn't updated yet.

**Comment by archon810** [comment]
Updated the list again and now I see the Twitter embed. Hooray!

![Screenshot 2019-09-20 at 9 13 52 AM](https://user-images.githubusercontent.com/469543/65342177-099f1800-db87-11e9-92c6-2ad8934056b8.png)

**Comment by sebastianbenz** [comment]
Yay! Thanks @archon810!
