### ISSUE TITLE
Description field for SHA exclusions

### ISSUE THREAD

**Issue by jvplopper** [ampproject/amphtml#24617]
## Describe the new feature or change to an existing feature you'd like to see

When adding a SHA exclusion in AMP, it would be awesome to have a description field where we can add comments regarding the SHA value mentioned.  I would use to mention the file name, how often the file might change, users in charge of said file, etc.

## Describe alternatives you've considered

A spreadsheet that maintains a list of SHA exclusions and meta-data.  Gross.

**Comment by choumx** [comment]
Wrong project?

**Comment by jvplopper** [comment]
Oh yes, sorry.  I see this is HTML improvements.  Apologies.
