### ISSUE TITLE
Issues related to AMP Pages

### ISSUE THREAD

**Issue by usmansiddiqui93** [ampproject/amphtml#2462]
Recently I implemented AMP to my site. My website is on Wordpress Platform and I have used official AMP plugin. However all process was smooth but now facing few error in my webmaster. I am not able to understand and resolve these errors.

[AMP Webmaster & Console Image
](http://i.stack.imgur.com/M8zda.png)

Error 1: Prohibited attributes: style
Error 2: Prohibited attributes: align
Error 3: Incorrectly nested tags: body > script, body > link
Error 4: Stylesheet syntax errors: Invalid Declaration
Error 5: Required attributes missing: async, src
Error 6: Invalid attribute values: type=text/javascript, href=http://www()example()com/wp-content/plugins/jetpack/css/jetpack.css?ver=3.9.2
Error 7: When I run test in Google Structured Data Testing Tool, I found "logo:	missing and required" error in schema.

When I ran #development=1 in my AMP URL, none of the error show up in my console.

Can anyone help me to solve these issues?

**Comment by grvsunny** [comment]
I am also getting same error in my search console while  #development=1 is showing this site is amp validated

**Comment by usmansiddiqui93** [comment]
I am resolved all my issues!! Follow this tutorial [Accelerated Mobile Pages (AMP) ](http://www.mustips.com/implement-accelerated-mobile-pages-amp/)

**Comment by grvsunny** [comment]
I am also getting error message in structure data that image is missing although i had already been able to resolve that logo issue and it worked but image is still missing you can check for http://perfectsexstories.com can you please help

**Comment by usmansiddiqui93** [comment]
Try with the tutorial i have referred!

**Comment by OfferGyan** [comment]
Guys. I Have Also this Problem.
Recently I Installed AMP on My Blog [https://offergyan.com](url)
But now there are lots of amp errors in webmaster. Please solve it.
