### ISSUE TITLE
amp-carousel 0.2 Safari missing transition

### ISSUE THREAD

**Issue by LNHarders** [ampproject/amphtml#24628]
## What's the issue?

The transition animation for the sliding in an amp-carousel 0.2 is not working on Safari

## How do we reproduce the issue?

[Example in playground](https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fcomponents%2Famp-carousel.example.2.html%3Fformat%3Dwebsites&format=websites&_gl=1*1ppqdk3*_ga*YW1wLXZaeVN1LTRtVlp0QXI5WjQ1bU83Mnc.)

1. open the link in Safari
2. change "https://cdn.ampproject.org/v0/amp-carousel-0.1.js" to "https://cdn.ampproject.org/v0/amp-carousel-0.2.js"
3. click the transition button of the example

## What browsers are affected?

Seen in Safari (version 12.1.2) on Mac OS

## Which AMP version is affected?

Latest version (1909141409590)

**Comment by LNHarders** [comment]
Maybe a related problem:
If you use the following carousel in Safari the slide buttons don't change their opacity and you can't go back in the carousel. The problem only appears when you use the buttons not when you scroll/slide.
When the carousel width is changed to something below 340 the problem with the back button still occurs after the first slide.

```html
<amp-carousel width="450"
  height="150">
  <amp-img src="/static/inline-examples/images/image1.jpg"
    width="225"
    height="150"></amp-img>
  <amp-img src="/static/inline-examples/images/image2.jpg"
    width="225"
    height="150"></amp-img>
  <amp-img src="/static/inline-examples/images/image3.jpg"
    width="225"
    height="150"></amp-img>
</amp-carousel>
```

**Comment by nazariodili** [comment]
> ## What's the issue?
> The transition animation for the sliding in an amp-carousel 0.2 is not working on Safari
> 
> ## How do we reproduce the issue?
> [Example in playground](https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fcomponents%2Famp-carousel.example.2.html%3Fformat%3Dwebsites&format=websites&_gl=1*1ppqdk3*_ga*YW1wLXZaeVN1LTRtVlp0QXI5WjQ1bU83Mnc.)
> 
> 1. open the link in Safari
> 2. change "https://cdn.ampproject.org/v0/amp-carousel-0.1.js" to "https://cdn.ampproject.org/v0/amp-carousel-0.2.js"
> 3. click the transition button of the example
> 
> ## What browsers are affected?
> Seen in Safari (version 12.1.2) on Mac OS
> 
> ## Which AMP version is affected?
> Latest version (1909141409590)

Any updates about this bug?
