### ISSUE TITLE
lightboxed carousel gets corrupted state in amp-list

### ISSUE THREAD

**Issue by dijs** [ampproject/amphtml#24631]
## What's the issue?

The lightbox component is keeping past images in the carousel, and corrupts AMP state after using the component a few times.

## How do we reproduce the issue?

Please visit this URL to see the bug in action

http://g.recordit.co/i1TV10QqIc.gif

As I am changing the product color, I am fetching and updating the carousel images. And the carousel is configured to show a lightbox as documented.

## What browsers are affected?

Tested both Chrome and iOS Safari. Problem exists in both browsers.

## Code

Here is the computed AMP code from Chrome's devtools

![image](https://user-images.githubusercontent.com/1774430/65228136-9a67ec00-dad2-11e9-98b0-6268e6ae5a9c.png)

As you can see, I am using an amp-list to dynamically update state, which renders an amp-carousel using a template

## Second issue

Also, after updating the image state multiple times, switching carousel images a few times, and opening the lightbox, the AMP state becomes corrupted. Here is the error it shows in console just after the above video is completed.

<img width="753" alt="AMP error" src="https://user-images.githubusercontent.com/1774430/65228499-44e00f00-dad3-11e9-9344-a3443170bab9.png">

**Comment by cathyxz** [comment]
Do you have a live repro we could take a look at?

**Comment by dijs** [comment]
Yes,

https://react-storefront-boilerplate.moovweb.cloud/p/2.amp?c=2&s=1
