### ISSUE TITLE
amp-carousel 0.2 autoplay transition bug

### ISSUE THREAD

**Issue by LNHarders** [ampproject/amphtml#24632]
## What's the issue?

amp-carousels 0.2 that use autoplay have jumpy transition animations and jump to the wrong slides when you click the slide buttons.

## How do we reproduce the issue?

[Example in playground](https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-carousel&format=websites&_gl=1*lti3ek*_ga*YW1wLU8tZGRBdk00aGdzZ1BwR3BuMXRDeEE.)

1. open the link
2. change "https://cdn.ampproject.org/v0/amp-carousel-0.1.js" to "https://cdn.ampproject.org/v0/amp-carousel-0.2.js"
3. click the slide button repeatedly on carousels that use autoplay

## What browsers are affected?

Seen in Chrome (version 77.0.3865.75) and Firefox (version 69.0.1) on Mac OS

## Which AMP version is affected?

Latest version (1909141409590)

**Comment by jaygray0919** [comment]
Also see https://github.com/ampproject/amphtml/issues/24335

**Comment by sparhami** [comment]
I don't think this issue should occur anymore. I believe there was an issue with autoplay not being cancelled when you click an arrow has since been fixed. Please re-open if this is still an issue,
