### ISSUE TITLE
Question: supported browser, mobile and tablet

### ISSUE THREAD

**Issue by alexonbalangue** [ampproject/amphtml#2463]
hello,
what was supported on browser, mobile and tablet? (not only google chome).

i want to know:
firefox: (yes or no) i'm not sure
chrome: yes
opera: (yes or no)
iOS: : (yes or no) i yes but what version begening
android: yes

PS: i dont yet found this info.

thak's advance,
best regards.

**Comment by cramforce** [comment]
The policy is here
https://github.com/ampproject/amphtml/blob/master/DEVELOPING.md#supported-browsers
