### ISSUE TITLE
Chrome Flags Samesite Cookies Enabled messes up AMP experiments

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#24643]
## What's the issue?
When Samesite cookies flags are enabled, the cookie enabling to opt-in to canary or rc doesnt work.

Briefly describe the bug.
When these settings are enabled and you opt-in to canary or rc the version still displays production.

## How do we reproduce the issue?

1. Go to chrome://flags
2. Search for Samesite
3. Enable both flags
4. Relaunch Chrome
5. Opt-in Canary/RC
6. Navigate to an AMP page
7. Open Java console

## What browsers are affected?

macOSX Chrome: Version 77.0.3865.90

## Which AMP version is affected?

Canary/RC Version: 1909181902540

Note: This issue was noticed once I updated my chrome browser from 77.0.3865.75 to 77.0.3865.90.

@sparhami may be able to add more details.
Set to P1, downgrade if necessary.

<img width="1085" alt="Screen Shot 2019-09-19 at 1 54 02 PM" src="https://user-images.githubusercontent.com/48487406/65280985-5e3e8680-dae6-11e9-9386-5062c51eec4b.png">

**Comment by sparhami** [comment]
I think in order to fix this, we need to add `SameSite=None` when setting the cookie for the canary version. However, per https://www.chromestatus.com/feature/5088147346030592, we should not set `SameSite=None` for Safari, as the behavior has a bug where it is treated as `Strict`.

**Comment by sparhami** [comment]
So it looks like if you are running Chrome Beta, you will need to flip the samesite cookie flags (as of Chrome beta 78?). This is expected to land in Chrome 80, so we still have some time to make the change.
