### ISSUE TITLE
handlebars.js support

### ISSUE THREAD

**Issue by danielkman** [ampproject/amphtml#2465]
How about a [handlebars.js](http://handlebarsjs.com/) extension?

**Comment by dvoytenko** [comment]
@danielkman we certainly can do this, but there are few nuances to discuss:
 1. Handlebars binary is about 7 times bigger than mustache which affects performance and bandwidth.
 2. Handlebars allows a lot reacher logic, which is nice but also affects performance.
 3. We'd have to push Handlebars integration through Google security review - it's usually not a big deal but does take a bit of time.

/cc @rudygalfi

**Comment by rudygalfi** [comment]
Definitely open to keeping the discussion on this going if there's demand. Since we haven't heard much feedback recently, I'm going to close this out.
