### ISSUE TITLE
amp-subscriptions-google: option to skip carousel and go directly to pay screen when only 1 sku, when `subscribe` action fired

### ISSUE THREAD

**Issue by ratana** [ampproject/amphtml#24650]
## Describe the new feature or change to an existing feature you'd like to see

For amp-subscriptions-google, when only 1 sku is configured, create an option to skip the carousel [including the 'arrow' which may go to an O+O buy landing page] and go directly to the SwG pay screen, when `subscribe` action fired.

## Describe alternatives you've considered
N/A

## Additional context
N/A

**Comment by jpettitt** [comment]
This is a complex question.  In some use cases it's preferable to show the extra step even if there is only one offer as it conveys more info than a naked buy button.  We'd need to make this optional / configurable.  We might make this moot if we offer real time config as suggested in #24651

**Comment by jpettitt** [comment]
Addressed in #24651
