### ISSUE TITLE
Validation error for mandatory_anyof constraint when using data-amp-bind-src on amp-list

### ISSUE THREAD

**Issue by westonruter** [ampproject/amphtml#24661]
On blog.amp.dev we noticed a validation error starting to happen after https://github.com/ampproject/amp.dev/pull/2934:

> `The tag 'amp-list' is missing a mandatory attribute - pick at least one of ['src','[src]'].`

The markup being introduced included:

```html
<amp-list data-amp-bind-src="query == undefined ? null : '/search/do?q=' + encodeURIComponent(query) + '&amp;locale=en'" binding="no" items="." height="10" layout="fixed-height" data-amp-bind-is-layout-container="query.length" load-more="auto" load-more-bookmark="nextUrl" reset-on-refresh="" single-item="">
	<template type="amp-mustache">...</template>
</amp-list>
```

As of https://github.com/ampproject/amp-wp/pull/2974, the AMP WordPress plugin normalizes the bracketed amp-bind attribute syntax to `data-amp-bind-*`, so the original `[src]` is being converted here to `data-amp-bind-src`. The AMP validator then is flagging this as an error because of this `mandatory_anyof` constraint:

https://github.com/ampproject/amphtml/blob/8c7a61288f841dfaa3781afc1a7bb813e0270212/extensions/amp-list/validator-amp-list.protoascii#L93

A quick fix here would be to just add `data-amp-bind-src` to the list:

```diff
- mandatory_anyof: "['src','[src]']"
+ mandatory_anyof: "['src','[src]','data-amp-bind-src']"
```

However, this seems like a fix for a more fundamental issue where the validator needs to be more aware of the alternate syntax (https://github.com/ampproject/amphtml/issues/11115).

**Comment by Gregable** [comment]
I actually think the proposed fix is fine. The validator isn't really aware of the current `[foo]` syntax in any special case way, these are just allowed. All `data-` attrs are also allowed. 

Is there any other example of an issue caused by the validator being not aware of the bind syntax?

**Comment by westonruter** [comment]
I believe that the `mandatory_anyof` constraint in `amp-list` is the only instance. I've opened #24793 to implement that change.
