### ISSUE TITLE
Using Microsoft Azure tracking tags inside AMP pages

### ISSUE THREAD

**Issue by yuvalight** [ampproject/amphtml#24675]
Hi,

We are an online gambling company named Codere Apuestas.
We started working with AMP in the last year and we have some AMP pages.
In our general sites(not the AMP sites) we have a big JS file which has all the trackers that we use for tracking our users.
We would like to implement the JS file inside the AMP pages, but because of the limitation AMP has we need you to help us find a way to do that implemetation.

**Comment by eduardogoncalves** [comment]
Hi @yuvalight , have you tried [Google Tag Manager](https://support.google.com/tagmanager/answer/9205783?hl=en)?

**Comment by yuvalight** [comment]
@eduardogoncalves hi,
All of our trackers are on Azure that is why it is hard for us to move everything to Google Tag Manager...

**Comment by eduardogoncalves** [comment]
@yuvalight which [Azure Service](https://azure.microsoft.com/en-us/services/) are you using?
