### ISSUE TITLE
<amp-beopinion>does not work in <amp-story-page-attachment> 

### ISSUE THREAD

**Issue by mufaddal7** [ampproject/amphtml#24672]
## What's the issue?
`<amp-beopinion>` does not work in `<amp-story-page-attachment> ` 

## How do we reproduce the issue?
```
<amp-story-page id="page1">
<amp-story-page-attachment layout="nodisplay">
                <h1>Vote Now</h1>
                <amp-beopinion width=375 height=472
                               layout="responsive"
                               data-account="5d85e66f46e0fb00019f4e68"
                               data-content="5d85e77f46e0fb00019f5837"
                               data-name="content-slot">
                </amp-beopinion>
            </amp-story-page-attachment>
        </amp-story-page>

```
Upload this code in a story

## Solution
@BeOpinion Needs to change the style of the iframe to `display:block` from `display:flex`

**Working in this image 1**
![image](https://user-images.githubusercontent.com/42934221/65371542-23715580-dc82-11e9-8029-60e9d8981402.png)

**Not working in the existing setting**
![image](https://user-images.githubusercontent.com/42934221/65371550-397f1600-dc82-11e9-8c3d-6d0c78372c23.png)

**Comment by bloodyowl** [comment]
@mufaddal7 thanks for the bug report! I opened a PR with a fix to your issue.

**Comment by mufaddal7** [comment]
There has been a temporary solution provided by the Beop team (Message by Beop team)
I have validated the issue and it seems to be solved currently, however it works very slow and is spoiling the user experience and the UI also seems to be poor for AMP Stories

**Comment by gmajoulet** [comment]
Could you post more information about how to reproduce this issue? Was it on any specific browser, or with any specific CSS?

On a story with no CSS and on Chrome, your snippet seems to work:

![image](https://user-images.githubusercontent.com/1492044/65540840-30888180-deda-11e9-8faa-5c29514f3319.png)

**Comment by bloodyowl** [comment]
@gmajoulet we (BeOp) added a temporary workaround on our side while #24673 is pending
