### ISSUE TITLE
amp-autocomplete: Support prefetching remote data via an attribute to improve responsiveness for users

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#24687]
Issue to track followup effort for [#23772 (comment)](https://github.com/ampproject/amphtml/issues/23772#issuecomment-519284625) and [#24645 (comment)](https://github.com/ampproject/amphtml/pull/24645#pullrequestreview-291321195)

Add an amp-autocomplete attribute to support prefetching remote data since the default is to fetch on `touchstart` or input `focus`, whichever occurs first.

**Comment by caroqliu** [comment]
Un-assigning myself as this is a GFI :) Happy to work with anyone who wants to take this on!

**Comment by Asadius** [comment]
Hi Caroline! Could I work on this feature? :)

**Comment by caroqliu** [comment]
Absolutely! Thank you for contributing! Feature work includes: 

- Reading the proposed attribute in the `layoutCallback` to fetch data and flip `this.interacted_` to avoid repeat fetches from `checkFirstInteractionAndMaybeFetchData_`
- Consider renaming `this.interacted_` with `this.hasInitialFetch_` or similar for clarity of usage
- Adding unit tests for the new attribute
- Updating `amp-autocomplete.md` with description of the new attribute

Feel free to send PRs my way and let me know how else I can help!

**Comment by dmanek** [comment]
Reassigning to me since this issue has been inactive for a while.
