### ISSUE TITLE
amp-date-picker highlighted/blocked attributes do not work

### ISSUE THREAD

**Issue by lvberkum** [ampproject/amphtml#24682]
## What's the issue?

amp-date-picker highlighted and blocked attributes have no effect

## How do we reproduce the issue?

See https://amp.dev/documentation/examples/components/amp-date-picker/?format=websites#highlighted-and-blocked-attributes . 

## What browsers are affected?

All browsers? 

## Which AMP version is affected?

AMP version 1909141409590. Not sure if this is a new issue, haven't tried to use the date picker before.

**Comment by nainar** [comment]
Verified that this is broken at least on amp.dev

**Comment by rsimha** [comment]
@jridgewell removed RRule support from `amp-date-picker` because it never did work. (See [this list](https://github.com/ampproject/amphtml/pulls?utf8=%E2%9C%93&q=is%3Apr+rrule++sort%3Aupdated-desc) of attempts to make it work.)

**Comment by lvberkum** [comment]
This is unsatisfactory? Without the possibility to parameterize  amp-date-picker in this way it is not very efficient? 
Also, there are bound to be numerous RRule implementations currently? 
And also, the current documentation still references RRule support?

**Comment by jridgewell** [comment]
See https://github.com/ampproject/amphtml/issues/25244. We plan on adding RRule back, but the current implementation was broken.

**Comment by lvberkum** [comment]
I somehow missed that, thanks for clearing that up.

**Comment by wassgha** [comment]
Assigning @caroqliu since this will be resolved by #25244
