### ISSUE TITLE
Remove temporary ownership of OWNERS.yaml file

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#24685]
In #24599 , @rcebulko is added as an owner of all `OWNERS.yaml` files in the repo.  The rule will be there only temporarily during the transition period while many owners files are being updated as contributors and teams notice which files are out of date. The `#` modifier means the owners bot will tag me on any PR that touches an owners file. This will allow me to verify syntax and semantics of all updates until the syntax check API for Travis to use is complete.

Though this gives me the ability to approve changes to owners files, I do not currently have merge access; the owners check is currently non-blocking; and I run and maintain the owners bot application. Within a week or so, once the peak of owners updates has passed, this rule must be removed.

**Comment by rsimha** [comment]
Can this be removed now? It has been about a month since this was put in place, most files have been updated, and we have a basic parsing check in place for `OWNERS` files.

**Comment by rcebulko** [comment]
I could; most of my review comments these days are about people introducing new files without the top comment, or adding themselves as an owner but not a working group, or adding non GitHub usernames as owners (idk), (or now, rejecting non-working group teams) and I don't really need to be the owner here at this point. It might be nice to wait until the Travis check is done, but I could swing either way.

**Comment by rcebulko** [comment]
Closed by #25304
