### ISSUE TITLE
Cite attribute for blockquote is rejected by validator

### ISSUE THREAD

**Issue by weeblr** [ampproject/amphtml#2469]
cite is a [valid HTML5 attr for blockquote](https://www.w3.org/TR/html5/grouping-content.html#the-blockquote-element), but is rejected by validator.

Expected?

Rgds

**Comment by cramforce** [comment]
Must have overlooked it.

**Comment by Gregable** [comment]
This change is live everywhere. Please reopen if you spot any issues.
