### ISSUE TITLE
How to setup AMP LIVE List On AMP Version

### ISSUE THREAD

**Issue by themeenanaresh** [ampproject/amphtml#24699]
Please provide complete information for amp live list on amp Version. I am completely designed live Blog on non Amp version. Complete implement liveblogposting schema. But not show live icon on Google. Please provide details AMP LIVE List for AMP version

**Comment by nainar** [comment]
Hi!

Thank you for reaching out - please read this: https://amp.dev/documentation/examples/components/amp-live-list/ to understand how to use `<amp-live-list>`.

**Comment by themeenanaresh** [comment]
This link is good but guide is not available on AMP.
