### ISSUE TITLE
Is Event slideChange no longer exist at amp-carousel[type="slides"] ver. 0.2 ?

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#24705]
To whom it may concern:

I wonder is Event slideChange no longer exist at amp-carousel[type="slides"] ver. 0.2 ? Looks like I can't use it if I upgrade to  Version 0.2

- git doc: https://github.com/ampproject/amphtml/blob/master/spec/amp-actions-and-events.md#amp-carouseltypeslides

- amp.dev: https://amp.dev/documentation/guides-and-tutorials/learn/amp-actions-and-events/#amp-carousel[type=%22slides%22]

Paul

**Comment by sparhami** [comment]
The event should still exist and work. It will not fire a high trust action for autoplay, so if you are trying to use it for autoplay and something like `setState`, that will not work in carousel 0.2.

Do you have an example page that you can share where you see issues with carousel 0.2?

**Comment by meistudioli** [comment]
Hi, @sparhami:

Thanks for reply. Yes, I trid to do some pagination through `setState`. Looks like I need to remove these if I upgrade to  .2 ?

**Comment by conwaydev** [comment]
We also have this issue as we toggle an active state on indicator buttons based off a carousel's state

**Comment by sparhami** [comment]
> Hi, @sparhami:
> 
> Thanks for reply. Yes, I like to do some indicators through `setState`. Looks like I need to remove these if I upgrade to .2 ?
> 
> ![image](https://user-images.githubusercontent.com/10822546/65560167-244f0380-df70-11e9-9e9f-5da0a1d8ded4.png)
> 
> demo site (VER. 0.1): https://blog.lalacube.com/mei/yahoo_mall_fp_amp.php

If you are using `autoplay` (which it looks like that page is), then yes, the `setState` will no longer work when the slide changes due to `autoplay`.

**Comment by meistudioli** [comment]
I see. Thank you so much. I'll remove that indicator once I migrate to amp-carousel 0.2.
