### ISSUE TITLE
Support Cooladata tracker

### ISSUE THREAD

**Issue by efiroz** [ampproject/amphtml#24729]
We are behavioural analytics platform for online web and mobile applications, we would like our tracker to be supported.
link to our documentation -[ ](https://docs.cooladata.com/getting-started/)
link to our javascript tracker Initialization - [](https://docs.cooladata.com/javascript/)

**Comment by efiroz** [comment]
This are the links:
https://docs.cooladata.com/getting-started/
https://docs.cooladata.com/javascript/

**Comment by choumx** [comment]
@efiroz Is this something your team can contribute to amphtml? :)

https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md

**Comment by micajuine-ho** [comment]
Hi @efiroz.

Please refer to [this documentation](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/integrating-analytics.md) on how to integrate your analytics with AMP. 

When you are ready, create a new I2I issue (outlined in the doc). I am going to close this issue, feel free to reopen it if you have any questions.
