### ISSUE TITLE
Clone documentation for amp-sidebar v2

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#24728]
The current setup will break the amp.dev component doc importer as the readme.md will be associated with the latest version 1.0 resulting in the translations not being shown.

Please, copy the readme and mark the new version as experimental:

```
<td width="40%"><strong>Availability</strong></td>
    <td><a href="https://amp.dev/documentation/guides-and-tutorials/learn/experimental">Experimental</a></td>
```

//cc @leafsy @sparhami

**Comment by sparhami** [comment]
I don't think we want to have this become the primary documentation yet. This component still in development and I'm not sure that we should call it experimental yet since the API is still in flux.

**Comment by leafsy** [comment]
Should I proceed with cloning the readme given the status described above? I was under the impression that keeping `latestVersion: '0.1'` in `bundles.config.js` would keep the latest version unaffected, but this is evidently not the case for documentation purposes.

**Comment by sebastianbenz** [comment]
> This component still in development and I'm not sure that we should call it experimental yet since the API is still in flux

But isn't this the definition of experimental?

**Comment by sparhami** [comment]
> > This component still in development and I'm not sure that we should call it experimental yet since the API is still in flux
> 
> But isn't this the definition of experimental?

I think for experimental, we want to at least have an API we think is ready, though there may be changes, rather than changing it wholesale.

**Comment by sebastianbenz** [comment]
I'd disagree about the definition of experimental, but that's not really relevant for this issue. 

We need a way to be able to match a documentation file to its version. The current algorithm is:

* if amp-component.ms is in the component root dir, assume it matches the latest version.
* if amp-component is in a versioned directory (e.g. `amp-sidebar/v0.1/amp-sidebar.md`), then use  use the directory name as version.

This breaks now for amp-sidebar. One fix would be to support defining the version in the document frontmatter via `version: 0.1`.
