### ISSUE TITLE
Documentation error - reference to "AMP By Example" on most component pages

### ISSUE THREAD

**Issue by noodles** [ampproject/amphtml#24720]
## What's the issue?

In the "Examples" row of the table that sits at the top of most Component pages, there is a reference to the now defunct "AMP By Example" site.

![Screen Shot 2019-09-25 at 10 01 56 AM](https://user-images.githubusercontent.com/183972/65558841-8b25ea00-df7b-11e9-8c7f-337b77b08bff.png)

## How do we reproduce the issue?

Look at various component documentation pages:

E.g.

1. https://amp.dev/documentation/components/amp-facebook-page/?format=websites
2. https://amp.dev/documentation/components/amp-facebook-like/?format=websites
3. https://amp.dev/documentation/components/amp-facebook/?format=websites 

## Proposal

Replace "See AMP By Example's" with "this" on all affected Documentation > Component Pages

### Example

Replace this:

See AMP By Example's [annotated amp-facebook](https://amp.dev/documentation/examples/components/amp-facebook/?format=websites) example.

with this:

See this [annotated amp-facebook](https://amp.dev/documentation/examples/components/amp-facebook/?format=websites) example.

**Comment by noodles** [comment]
@CrystalOnScript does this sound OK to you? Let me know if you'd prefer it worded differently.

**Comment by CrystalOnScript** [comment]
Thanks for bringing this up @noodles! The "See AMP By Example" wording should definitely be dropped, but the proposed update won't work with components with multiple examples, such as [amp-carousel](https://amp.dev/documentation/components/amp-carousel/?format=websites). I think it might just be better just have it as a link for a single example, or a bulleted list for multiple. 

Replace: 

AMP By Example's: 
- [amp-carousel example](https://amp.dev/documentation/examples/components/amp-carousel/?format=websites)
- [Image galleries with amp-carousel](https://amp.dev/documentation/examples/multimedia-animations/image_galleries_with_amp-carousel/?format=websites)

With:
- [amp-carousel example](https://amp.dev/documentation/examples/components/amp-carousel/?format=websites)
- [Image galleries with amp-carousel](https://amp.dev/documentation/examples/multimedia-animations/image_galleries_with_amp-carousel/?format=websites)

@sebastianbenz WDYT?

**Comment by noodles** [comment]
That makes sense.

For pages with a single example: 

This:

See AMP By Example's [annotated amp-facebook](https://amp.dev/documentation/examples/components/amp-facebook/?format=websites) example.

becomes:

[annotated amp-facebook example](https://amp.dev/documentation/examples/components/amp-facebook/?format=websites)

- No bullet
- The word example included in the hyperlink

**Comment by sebastianbenz** [comment]
Thanks for reporting. We're currently working on removing this column and replacing it with an automatically generated list of samples using the component. See https://github.com/ampproject/amp.dev/issues/2971
