### ISSUE TITLE
I have a Issues

### ISSUE THREAD

**Issue by ahmetcem96** [ampproject/amphtml#2473]
Hello guys;

1) Restricted Label, Input

url: http://www.dizimerkezi.net/tanitim-sex-drugs-rock-roll/amp/

2) The mandatory text (CDATA) inside tag 'boilerplate (js enabled) - old variant' is missing or incorrect se...

This issue talk about but i can't fixed (https://github.com/ampproject/amphtml/issues/1768)

function gives an error.

url: http://www.dizimerkezi.net/tanitim-sex-drugs-rock-roll/amp/ (again)

3) multiple instances of a unique label: link rel=canonical, amphtml engine v0.js script

url: http://www.dizimerkezi.net/tanitim-sex-drugs-rock-roll/amp/ (again)

4) syntax error Unknown: amp-analytics extension .js script required by amp-analytics

url: http://www.dizimerkezi.net/madoff-abc-mini-dizisi/amp/

How do I fix this issues. Thank you in advance .

Best regards

Ahmet Cem

**Comment by ahmetcem96** [comment]
@cramforce

**Comment by jmadler** [comment]
Hi Ahmet,

Please post your questions on [StackOverflow](https://stackoverflow.com/questions/tagged/amp-html) and I'll happily respond over there :)

Thanks!
