### ISSUE TITLE
Investigate amp-loader CSS in shadow docs

### ISSUE THREAD

**Issue by sparhami** [ampproject/amphtml#24740]
It seems like the CSS from the new loaders (from `amp-loader`) may not being applied to shadow docs correctly (i.e. when using shadow-v0.js). We should investigate that the styling is working correctly, and if possible, create an e2e test.

**Comment by sparhami** [comment]
So after some initial investigation, it seems like the styles are installed correctly. There may still be a race condition somewhere. Need some more investigation to see if we can reproduce the issue.

**Comment by mattwomple** [comment]
@sparhami I figured out how to reproduce this issue. It only appears after page navigation in a PWA, not on first page load. I created a minimal example that only uses `<amp-img>` and no other AMP components.

 - [img-loader-test-pwa.html](https://android.cmphys.com/temp/img-loader-test-pwa.html) - PWA, loads `-amp1.html` below on page load, intercepts anchor clicks
 - [img-loader-test-amp1.html](https://android.cmphys.com/temp/img-loader-test-amp1.html) - Image is set to return after 5 seconds from server, giving you time to see the loader working correctly
 - [img-loader-test-amp2.html](https://android.cmphys.com/temp/img-loader-test-amp2.html) - Image is set to return after 5 minutes from server, allowing plenty of time for debugging

To reproduce the issue, go to [img-loader-test-pwa.html](https://android.cmphys.com/temp/img-loader-test-pwa.html) and click the link that says _Go to image 2_. Screenshot below.

![dot](https://user-images.githubusercontent.com/29927572/66265083-12b5f900-e7c5-11e9-9335-c5d73c609c4f.png)

**Comment by mattwomple** [comment]
Just playing around here a bit. I notice that when `getLoaderServicePromise()` is called in `loader.js` when the second page loads, global variable `loaderServicePromise` is still defined. If I set it to null before the `if (!loaderServicePromise)` check, then the image loader works fine on the second page. Does this indicate that loader is not being properly disposed in `shadowDoc.close()`?
