### ISSUE TITLE
Using pipe character for multiple webfont names causes validation error

### ISSUE THREAD

**Issue by oliverw** [ampproject/amphtml#2474]
According to [this document](https://developers.google.com/fonts/docs/getting_started#Syntax) it is perfectly valid to optimize multiple webfont requestst using the <code>|</code> character.

Unfortunately this triggers validation errors both in development mode and in the google webmaster console:

`Invalid attribute values:	href=//fonts.googleapis.com/css?family=Lato%7CRaleway
`

**Comment by cramforce** [comment]
I think your problem is that the URL should start with `https:`
