### ISSUE TITLE
In amp-story, amp-experiment is alerted by amp validator, but it work correctly.

### ISSUE THREAD

**Issue by Shagamii** [ampproject/amphtml#24748]
## What's the issue?
In amp stories, amp-experiment component should be allowed to use,  but it is alerted by amp validator.

Related Link
- https://amp.dev/documentation/components/amp-experiment/?format=stories
- https://amp.dev/documentation/components/amp-story/#children

| contained in amp-story | contained in amp-story-grid-layer | 
| :--- | :--- |
| <img width="784" alt="Tag 'amp-experiment' is disallowed as child of tag 'amp-story'. Child tag must be one of ['amp-analytics', 'amp-consent', 'amp-geo', 'amp-pixel', 'amp-sidebar', 'amp-story-access', 'amp-story-auto-ads', 'amp-story-bookend', 'amp-story-page']." src="https://user-images.githubusercontent.com/18458057/65655624-d281a880-e057-11e9-8fa0-ec39081ecfba.png"> | <img width="786" alt="The tag 'script' may not appear as a descendant of tag 'amp-story-grid-layer'." src="https://user-images.githubusercontent.com/18458057/65655667-ef1de080-e057-11e9-83a5-1298276d29e6.png"> | 

However, amp-experiment work correctly.
<img width="373" alt="amp-x-ui-experiment attributes are given to body" src="https://user-images.githubusercontent.com/18458057/65656141-bc74e780-e059-11e9-8ae0-2e9477934526.png">

## How do we reproduce the issue?

1. add amp-experiment component url
2. Following [this example](https://amp.dev/documentation/components/amp-experiment/?format=stories), write amp-experiment  contained in amp-story or amp-story-grid-layer.

## What browsers are affected?

[chrome extension](https://chrome.google.com/webstore/detail/amp-validator/nmoffdblmcmgeicmolmhobpoocbbmknc?hl=ja) version 1.1.4
[amphtml-validator](https://www.npmjs.com/package/amphtml-validator)

## Which AMP version is affected?
1909181902540

**Comment by gmajoulet** [comment]
Thanks for the bug report.

We already allow `amp-experiment` without `amp-story-grid-layer`, but we should allow a `<script type="application/json">` as a direct descendant of `amp-experiment`.

cc @ampproject/wg-stories

**Comment by gmajoulet** [comment]
The implementation can look like what we have for the `script` tag within `amp-story-consent`: https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/validator-amp-story.protoascii#L396-L418

**Comment by jackbsteinberg** [comment]
It's not exactly clear on the documentation, but <amp-experiment> is only allowed in stories as a child of the <amp-story-grid-layer> element. #24909 fixes <amp-experiment> under <amp-story-grid-layer> elements, but <amp-experiment> as a direct child of <amp-story> is disallowed.
