### ISSUE TITLE
Documentation on script tag allowances is inconsistent

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#24757]
While [Github](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md) states that script types can only be `application/ld+json` or `text/plain`, the [amp-access documentation](https://amp.dev/documentation/components/amp-access/) shows that application/json is permitted for the amp-access case.

My assumption is that the more pervasive view i.e. application/ld+json or text/plain for all cases and "application/json" for amp-access is the right model. 

cc @CrystalOnScript @jpettitt 

[edited by @jpettitt for markdown readability]

**Comment by jpettitt** [comment]
There area [lot of places ](https://github.com/ampproject/amphtml/search?q=application%2Fjson&unscoped_q=application%2Fjson)where application json is used for inline scripts.  Which makes me thing the master spec is out of date here.

**Comment by choumx** [comment]
Should be a quick PR. :)

**Comment by Guzzler** [comment]
Hey I would like to claim this issue and create a PR. A newcomer to contributing to open source but from what i understand is the change just to update the amp-access documentation to include both the types of scripts?

**Comment by choumx** [comment]
Yea I think just include the other types of allowed `script` elements.
