### ISSUE TITLE
The geolocation example is not showing anything

### ISSUE THREAD

**Issue by theRealBitcoinClub** [ampproject/amphtml#24755]
## What's the issue?

The geolocation example is not showing anything

## How do we reproduce the issue?

Follow this link:

https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fuser-consent%2Fgeolocation-based_consent_flow&format=websites&mode=Galaxy+S5

## What browsers are affected?

Firefox & Chrome on Linux Mint

## Which AMP version is affected?

As of today

**Comment by nainar** [comment]
cc @zhouyx

**Comment by zhouyx** [comment]
Track the issue in the amp.dev repo instead
https://github.com/ampproject/amp.dev/issues/3063
