### ISSUE TITLE
amp-carousel 0.2 auto snap to start position when page scroll occured

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#24750]
To whom it may concern:

I've already migrate amp-carousel to Version 0.2 and feel something strange about the action.

※ Reproduce step:
1. horizontal scroll one amp-carousel.
2. page scroll occured.
3. amp-carousel auto snap to the start position.

video: https://youtu.be/T39di7eVJQE

 ※ Expect:
Keep it alone. I don't want to bother user to scroll back again.

demo address: https://tw.bid.yahoo.com/amp/homepage

Above example is test from iOS 13.1 Safari.

I wonder is this an issue or not. 

Paul

**Comment by conwaydev** [comment]
Also with autoplay it invokes a slide change as you scroll, planning on filing a separate bug once I make a isolated example but I can recreate by scrolling https://amp.dev/documentation/examples/components/amp-carousel/ on a mobile device and the autoplay example skips around.

**Comment by sparhami** [comment]
Looking at the linked page, it seems like it no longer uses `amp-carousel` for the section outlined in the video.

I tried creating a jsbin (http://output.jsbin.com/mazajac) to reproduce the issue, but I don't seem to be able to reproduce on iOS 13.1.

Do you still have a page available where this issue occurs?

**Comment by conwaydev** [comment]
@sparhami I’m still seeing the behavior at https://amp.dev/documentation/examples/components/amp-carousel/

**Comment by sparhami** [comment]
> @sparhami I’m still seeing the behavior at https://amp.dev/documentation/examples/components/amp-carousel/

That page is using `amp-carousel` 0.1, (we should update it to 0.2), but the issue above is about 0.2 specifically. The issue for 0.1 will be fixed when #24771 goes live.
