### ISSUE TITLE
Support for modifying analytics variables before substitution

### ISSUE THREAD

**Issue by georgecrawford** [ampproject/amphtml#2476]
I'd love a way to do something like this for access analytics variables:
```
{
    barrier: 'NOT AUTHDATA(access)'
}
```

i.e. I want to send a value `barrier` which is `true` when the auth call returned `false` for `access`, and visa versa. We can do this on the server, but it'd be neater if we could do it within the AMP client. 

Alternatively, a way to conditionally define analytics variables within `amp-access` HTML blocks, to override the defaults. That might be more useful, on second thoughts.

**Comment by georgecrawford** [comment]
See also #1298

**Comment by dvoytenko** [comment]
Hmm. We are considering extending analytics expression syntax a bit to possibly support some functions/transformations. But `NOT` would not fit into it super well. Perhaps it'd be better to just return `barrier` field in the authorization response itself?

**Comment by georgecrawford** [comment]
`barrier` is a decision made in the UI, not in the authorisation. But either some functions/transformations, or the ability to define variables within `amp-access`-protected blocks, would work for this use-case.

**Comment by georgecrawford** [comment]
Any further thoughts on this?

**Comment by dvoytenko** [comment]
I don't think we can define variables within `amp-access`-protected blocks, but I might be misunderstanding what it means. That being said, I think defining transforms for analytics is on the roadmap. @avimehta could you provide your feedback on this?

**Comment by avimehta** [comment]
https://github.com/ampproject/amphtml/issues/2198 and https://github.com/ampproject/amphtml/issues/2360 have similar requests to add transformations to variable values. #2198 describes a format for how we could transform values. Basically what you said can be written as:

```
{
    barrier: 'AUTHDATA(access)|boolean|not'
}
```

or more simply:
```
{
    barrier: 'AUTHDATA(access)|not'
}
```

wdyt?

**Comment by georgecrawford** [comment]
perfect for our use-case. Thanks.

**Comment by rudygalfi** [comment]
Looping in @dvoytenko for feedback on syntax.

I think in AMP Access we have an affordance for expressions like "NOT hitPaywall". The bar (|) syntax seems a little foreign to me and wondering if we can go in the direction of something more traditional.

I don't have a strongly formed opinion on this; just wanted to ensure some discussion on the merits happens.

**Comment by avimehta** [comment]
@rudygalfi I think i might have misunderstood the initial post. I thought this was about amp-analytics syntax and not amp-access.

**Comment by dvoytenko** [comment]
@rudygalfi @avimehta  - yes, this is specifically analytics thing, not access - access is simply a source of values that may need to be transformed before passing them to the analytics package.

I think simply `|not` or `|negate` would do - we can run a simple logic that would treat numbers and booleans via this transformation. 

But as far as substitution itself - I kind of imagine this would be within the `${}` syntax? Otherwise it'd seem it'd be hard to correctly identify boundaries?

**Comment by avimehta** [comment]
Things we would like to add:

- [ ] Not (negation)
- [ ] Trim
- [ ] JSON.stringify
- [ ] Base 64
- [ ] Default Value


Feel free to edit this comment to add more or comment below and I'll collect them all here.

**Comment by avimehta** [comment]
Being tracked by #2198. Closing this.
