### ISSUE TITLE
AMP version of page doesn't appear on Google Image Search

### ISSUE THREAD

**Issue by yajiv185** [ampproject/amphtml#24789]
## What's the issue?

AMP product page not being displayed on 'swipe to visit' for some websites. The amp page is displayed in a google search result but it is not getting displayed in "swipe to visit".
We have already asked on google support and StackExchange but did not get the answer.
- StackExchange:- https://webmasters.stackexchange.com/questions/125023/amp-product-page-not-being-displayed-on-swipe-to-visit-for-some-websites-while
- Google forum:- https://support.google.com/webmasters/thread/15183089?hl=en

## How do we reproduce the issue?

Following are the steps to reproduce it.
1) Select images search on google.
2) Type "Classic 350"
3) In the result, find the image from "bikewale.com" and click on it.
4) Click on "Visit".

So while clicking on "Visit", instead of AMP page actual website is opening but we were expecting to open AMP page.

## What browsers are affected?

All browsers.

**Comment by choumx** [comment]
Have you followed the steps here? https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/discovery/

I don't see a `link[rel=amphtml]` on your non-AMP page, for example.

**Comment by yajiv185** [comment]
It is present:- 
Desktop:- view-source:https://www.bikewale.com/royalenfield-bikes/classic-350/
Mobile:- view-source:https://www.bikewale.com/m/royalenfield-bikes/classic-350/

That's why AMP page is shown in google search result(and also opening correctly), but when go through image search AMP page is not opening.

**Comment by yajiv185** [comment]
Any updates?
