### ISSUE TITLE
Discourage on="tap:AMP.navigateTo" vs. <a>

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#24798]
Add some documentation and maybe a runtime warning to discourage `on="tap:AMP.navigateTo(...)"` in favor of `<a>` tags. The former has no crawler support.

**Comment by dritter** [comment]
This would break our workaround for #23896 and #23891 ...

**Comment by choumx** [comment]
We won't remove this functionality so it won't break anything in the wild. Having a complete sitemap also helps the crawler issue.
