### ISSUE TITLE
Expose file metadata in <input type=file>

### ISSUE THREAD

**Issue by cheluskin** [ampproject/amphtml#24794]
## What's the issue?

When selecting a file in input, information about the selected file is not available. Name, size. The variable files is undefined. Also, you cannot get information from the change event.

**Comment by nainar** [comment]
Could you elaborate on the issue here? 
What file are you attempting to select?

**Comment by cheluskin** [comment]
Absolutely any file on tag input. <input type="file">
There is no way to get its size in bytes. Even using <amp-script>

**Comment by choumx** [comment]
We need more information on your use case. What are you trying to do with the file metadata?

**Comment by cheluskin** [comment]
I need to know the exact file size and upload it via xhr to a remote server. It is not possible to do this by submitting a form, because I need to have authorization headers in the request
