### ISSUE TITLE
Images skip when swiping in amp-carousel

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#24806]
## What's the issue?
When swiping from left to right, or right to left, the images will skip if user didn't complete a full swipe.

Briefly describe the bug.
Images are skipping when swiping in amp-carousel.

## How do we reproduce the issue?

1. Opt-in to Canary/RC
2. Go to [link1](https://m.aliexpress.com/item/4000020845688.html?pid=808_0000_0101&spm=a2g0n.search-amp.list.4000020845688&aff_trace_key=&aff_platform=msite&m_page_id=5695amp-s8mh9s4A0FMyTVITQo8ciA1569535055662) or [link2](https://www.google.com/amp/s/www.sfchronicle.com/warriors/amp/360-degree-tour-Warriors-locker-room-and-player-14467573.php)
3. Open Java Console
4. In the amp-carousel begin swiping left-to-right or right-to-left

## What browsers are affected?

Chrome Version: 77.0.3865.90

## Which AMP version is affected?

Canary/RC: 1909241711100

Video Link: https://drive.google.com/open?id=1fPZPCZuOSR7gKYuvpp3n3zJlsmKOy8sC

**Comment by sparhami** [comment]
This is fixed by #24771 (on both iOS and Chrome), which should either be in the next canary or cherry-picked soon.
