### ISSUE TITLE
Respect prefers-reduced-motion for story animations.

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#24821]
We should consider respecting the user `prefers-reduced-motion` setting for amp-story documents, and disable all enter animations like fly-in, rotate-in, ... to show the page directly in its final state.

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

**Comment by Malvoz** [comment]
While this is feature specific, there's also #20433. FYI.
