### ISSUE TITLE
Make <amp-sidebar> mask element compatible with Story

### ISSUE THREAD

**Issue by leafsy** [ampproject/amphtml#24827]
Currently, `amp-sidebar` appends its mask directly under body; this does not work for AMP Story since sidebar is a child of `<amp-story>` and the default mask would appear above sidebar.

Investigate a way to make the mask element work in this context. We should also ensure that sidebar swipe-to-dismiss works when swiping from the mask inside an AMP story.

/cc @newmuis @gmajoulet

**Comment by gmajoulet** [comment]
Awesome! Please let us know if you need help testing anything, or removing the custom AMP Story mask.

**Comment by newmuis** [comment]
Just to verify: this will be done to sidebar 0.2 only?  Or both 0.1 and 0.2?

**Comment by leafsy** [comment]
@newmuis 0.2 only (updated issue title), since it involves DOM changes that could break user-defined CSS selectors.

**Comment by leafsy** [comment]
@gmajoulet @newmuis 

As a followup to our discussion last week (open for feedback):
Stories need a way to know where the mask will be appended (depending on version) in order to decide if their own mask should be shown instead. The potential solutions discussed are:
1. Add a public method to both versions of sidebar, e.g. "isMaskAppendedToBody" and return a boolean.
2. Auto-upgrade all sidebars to v0.2 when ready and validator restrict 0.2 if not ready (backward compatibility concerns?).

I'll tentatively make the change to move the mask element inside sidebar v0.2 as well as add the public methods.

**Comment by newmuis** [comment]
This SGTM.

/cc @kristoferbaxter re: UI components + stories conversations we've been having

**Comment by gmajoulet** [comment]
SGTM
On top of (1), the Story runtime will have to hide its custom sidebar when `isMaskAppendedToBody` returns `true`
