### ISSUE TITLE
Apply query parameter value to class or data attribute on page load

### ISSUE THREAD

**Issue by mattwomple** [ampproject/amphtml#24832]
## Describe the new feature you'd like to see

It would be great if `QUERY_PARAM()` could be used to apply a value to `class` and/or `data-` attributes on page load.

Some of WompMobile's clients have AMP pages that differ based on the `?region=` parameter (or similar). It is possible to apply these differences immediately in a PWA, but bare AMP pages require less than optimal workarounds like passing QUERY_PARAM in `<amp-list src="...">`. If we could pass-down that region parameter into a `data-` attribute, we could write CSS styles like:

```
.washington,
.oregon,
header[data-region="washington"] .default,
header[data-region="oregon"] .default {
    display: none;
}
header[data-region="washington"] .washington,
header[data-region="oregon"] .oregon {
    display: block;
}
```

_I'm sure this has been asked in a slightly different way in the past. My searches came up empty, though. Please link me to similar feature requests if you know of any so I can read-up on past discussions!_

## Describe alternatives you've considered

The workarounds that we currently use are:

- Server-side rendering of AMP - this is rarely an option for us since 99.9% of our AMP pages are served from a CDN
- Use `<amp-list>` with a `src` that echoes back query parameter values (e.g. https://ampsupport.wompmobile.com/echoquery/dictionaryformat?query_param1=value%201&query_param2=value%202 ) - this is not a great solution because network requests can be slow and it is possible to end-up with `id` attribute collisions between the `placeholder` and `role="list"` elements in the `<amp-list>`

Ideas like the following do not work because `QUERY_PARAM()` substitution doesn't actually manipulate the DOM or an event is required to trigger the DOM update:

Failed attempts to use adjacent element for styles like `[data-region="washington"]+header {}`:
```
<form>
    <input type="hidden" name="region" value="QUERY_PARAM(region,default)" data-amp-replace="QUERY_PARAM">
    <header>
```
or
```
<a hidden href="QUERY_PARAM(region,default)" data-amp-replace="QUERY_PARAM">
<header>
```

**Comment by choumx** [comment]
Other alternatives (some discussed on Slack):
1. Add state-level geolocation to `amp-geo`. 
2. Publish a separate AMP page for each variant.
3. Add rendering with local data to `amp-list`, and somehow merge `QUERY_PARAM(...)` into that local data.

/cc @ampproject/wg-ui-and-a11y
