### ISSUE TITLE
AMP sticky ads are covered by the new Google News "Coverage bar".

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#24841]
https://twitter.com/andreapernici/status/1177933152242806784?s=19

**Comment by calebcordry** [comment]
Working on repo, seems like an android specific issue as I only see the "coverage bar" on android not iOS.

**Comment by lannka** [comment]
@calebcordry it will be helpful if you can show a screenshot.

/cc @zhouyx who has the most knowledge about amp-sticky-ad

**Comment by calebcordry** [comment]
![image](https://user-images.githubusercontent.com/16087874/66000627-af3e6b00-e454-11e9-8101-e66ee79061f7.png)
![image](https://user-images.githubusercontent.com/16087874/66000720-e7de4480-e454-11e9-9d4b-d74697af293a.png)

**Comment by calebcordry** [comment]
Found a couple examples 👆from different pubs where everything seems to be working as expected, and you can see the "Full Coverage" bar. Still working finding a broken case.

**Comment by calebcordry** [comment]
Still having trouble reproducing. I sent an email to the original reporter to get more details.

**Comment by calebcordry** [comment]
Received more details. This is a problem that happens from `-1` screen Discover on android, when user clicks an article from their feed. 
![image](https://user-images.githubusercontent.com/16087874/66163707-cc567380-e5e5-11e9-993d-2920b965ceb7.png)
