### ISSUE TITLE
amp-addthis: transitive URL references are 404'ing due to overly long cache age of external document

### ISSUE THREAD

**Issue by archon810** [ampproject/amphtml#24848]
Example url: https://www.androidpolice.com/2019/10/01/youtube-new-share-ui/?amp, but none of our AMP urls, whether served directly or through Google Cache, load the AMP Addthis widgets.

However, the widgets work on my PC. And my Pixel 3. But on my OnePlus 7 Pro, in Chrome and Chrome beta, nothing, but in Chrome Dev and Canary, addthis shows up.

The reason seems to be 404s to some Addthis scripts, namely:
https://s7.addthis.com/dc/7.92e7c8ab8e1c0cce01ea.js
https://s7.addthis.com/dc/tools.85aa2bad75a8e6657a1c.js

These are loaded from https://s7.addthis.com/dc/amp-addthis.html.

![image](https://user-images.githubusercontent.com/469543/66027476-d70eec80-e4af-11e9-9344-0d974232972a.png)

However, in Chrome Dev, scripts do load, though with different urls.

![image](https://user-images.githubusercontent.com/469543/66027615-26edb380-e4b0-11e9-87d5-3d94965f1667.png)

The content of https://s7.addthis.com/dc/amp-addthis.html that's broken is here: https://gist.github.com/4a107e8c61328cc3c3f171e96bcc2578. Working one is here: https://gist.github.com/bd612f974305786dac4842ff80e089a1.

What's happening here?

**Comment by archon810** [comment]
Also submitted a report here https://www.addthis.com/support/.

**Comment by nainar** [comment]
cc @ampproject/wg-ui-and-a11y

**Comment by archon810** [comment]
The problem is still there for me.

**Comment by caroqliu** [comment]
Thank you for filing this issue! I will take a look at this.

**Comment by wassgha** [comment]
I can't reproduce this anymore. Looks like it was fixed on AddThis' side. Closing for now, if this is still reproducible please reopen the issue.

**Comment by archon810** [comment]
@caroqliu I'm still able to reproduce it as per the original ticket.

**Comment by archon810** [comment]
I absolutely don't understand why though, as it happens to even the newest articles, like https://www.androidpolice.com/2019/10/07/samsung-pay-beta-adds-international-money-transfers-and-prepaid-samsung-pay-cash-card-apk-download/?amp, but only on my main phone (OnePlus 7 Pro). 

How can there be such a long persistent addthis cache that would reference old 404 scripts even in new posts, and only on specific devices, presumably with this cache already there? It has to be some sort of framework-level cache...

**Comment by archon810** [comment]
Please reopen.

**Comment by wassgha** [comment]
Have you tried incognito mode, clearing cache, etc?

**Comment by archon810** [comment]
In Incognito, it does work, but there should be no technical reason why this issue should persist for so long without having to clear cache. As I mentioned, I loaded newly posted posts, and the issue was present there, so it's not something that can be cleared by refreshing the page or loading a new one. Things like this should not happen. What could this be?

**Comment by archon810** [comment]
I can no longer reproduce this on my OnePlus 7 Pro. I'll close.

**Comment by archon810** [comment]
The issue has returned for me on all of my devices - desktop and mobile, and has persisted for the last several weeks.

This is crazy - it's like some addthis AMP cdn cached which JS scripts it's loading and hasn't updated for weeks since they went 404.

The current links it's trying to load that are 404:
- https://s7.addthis.com/dc/7.92e7c8ab8e1c0cce01ea.js
- https://s7.addthis.com/dc/tools.85aa2bad75a8e6657a1c.js

![image](https://user-images.githubusercontent.com/469543/74288781-2973db80-4ce2-11ea-84b5-84a2dd5062b9.png)
![image](https://user-images.githubusercontent.com/469543/74288793-30025300-4ce2-11ea-9408-63ebd83a38fc.png)

This is driving me nuts.

**Comment by archon810** [comment]
Some more experimenting:
- load the page in incognito on Wi-Fi, doesn't work. Switch to LTE, reload, doesn't work. Close incognito and load in a fresh incognito on LTE - works.
- load the page in Firefox on Wi-Fi (a browser I don't typically use) - works.
- clear cache and various saved data for Chrome - works.

So, once again https://s7.addthis.com/dc/amp-addthis.html is cached by the browser and contains references to old JS files that have since gone 404, and even a ctrl-F5 on androidpolice.com doesn't refresh this file. The headers insist on very long cache-control of 86313600 seconds which is 999 days:

```
cache-control: public, no-check, max-age=86313600
cache-tag: at_client
content-encoding: gzip
content-length: 3965
content-type: text/html; charset=UTF-8
date: Tue, 11 Feb 2020 23:31:06 GMT
last-modified: Tue, 09 Apr 2019 18:49:23 GMT
p3p: CP="NON ADM OUR DEV IND COM STA"
status: 200
surrogate-key: at_client
vary: Accept-Encoding
X-DNS-Prefetch-Control: off
x-host: s7.addthis.com
```

There's no cache-busting - the url is always https://s7.addthis.com/dc/amp-addthis.html, so it's no wonder it gets aggressively cached and is hard to bust this cache for the user - in fact, this file itself needs to be force-refreshed.

So, with all the info here, can AddThis please address this issue?

Thank you.

**Comment by alanorozco** [comment]
@taojing10
@dmvjs
@pjcunnin
@matthinegardner

I believe max-age should be configured properly.

@archon810 

We might be able to work around it by adding an AMP version query param: #26761

**Comment by archon810** [comment]
Good start! And can be reverted once properly resolved.

**Comment by archon810** [comment]
Any idea when this will hit production? I am once again experiencing the issue. I don't understand why more people don't report it. 

Missing widget:
![Screenshot_20200304-195334](https://user-images.githubusercontent.com/469543/75946475-19b76500-5e52-11ea-8c96-ff0c24a53e98.png)
