### ISSUE TITLE
Bug in amp-carousel 

### ISSUE THREAD

**Issue by rafaelgodinho-wunderman** [ampproject/amphtml#24844]
**## What’s the issue?**
We found a bug in the amp-carousel. After a short investigation, I think it could be the same bug founded in the site itself https://amp.dev/.

**## How do we reproduce the issue?**
Using the same steps evidenced on amp site itself in the pages bellow:
http://hml.vivo4g.clientes.ananke.com.br/videos/erro-carousel-iphone.webm
http://hml.vivo4g.clientes.ananke.com.br/videos/erro-carousel-iphone2.webm

**## What browsers are affected?**
It occurs in IPhone X+ using Google Chrome and Safari.

**## Which AMP version is affected?**
1909181902540

**Comment by sparhami** [comment]
Duplicate of #24541
