### ISSUE TITLE
AMP Validator Console/Search Console passes a failing page

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#24849]
Here is an invalid AMP page: https://tribune.com.pk/story/2068372/1-imrans-mediation-offer-slim-chance-success/?amp=1#development=1

The Chrome extension fails it correctly.

Console validator passes it. They use an old version of Wordpress and the AMP plugin.

Anyone know why this is happening?

**Comment by honeybadgerdontcare** [comment]
It appears the server sometimes requires a captcha to see the content. So it could be that an AMP cache, or whatever validation method being used, gets the actual valid document or gets the captcha page which is invalid AMP.
![Screenshot 2019-10-02 at 7 38 57 AM](https://user-images.githubusercontent.com/1340565/66053821-d72ade80-e4e7-11e9-9a9b-311e26fa07cb.png)

**Comment by honeybadgerdontcare** [comment]
Further, if a page was valid and then becomes invalid, we will still serve the previous valid page from the cache.
