### ISSUE TITLE
Single Input for date ranges in amp-date-picker 

### ISSUE THREAD

**Issue by charlessyms** [ampproject/amphtml#24843]
## Describe the new feature or change to an existing feature you'd like to see

It would be nice if we could use a single input for a date range so that we can output dates in booking forms, rather than having to use 2 boxes to show 2 different dates.

## Describe alternatives you've considered

I've tried using Bind and Mustache to replicate the above with no success.

**Comment by nainar** [comment]
https://amp.dev/documentation/examples/components/amp-date-picker/?format=websites#date-range-picker has an example on how to do this. 

Please also use Slack (sign up here: https://bit.ly/amp-slack-signup) for questions regarding using AMP.

**Comment by charlessyms** [comment]
I've read that list 50 times over. There is not a way to display both dates from a date range in the same box. Maybe I didn't word my feature request clearly enough.
