### ISSUE TITLE
this is more of a question: <amp-ad> data-loading-strategy

### ISSUE THREAD

**Issue by obeyer** [ampproject/amphtml#2485]
since we can't run js, to determine if the ad slot is coming in a view, how to make sure that the ad isn't loaded until it is approaching the viewport? Does amp js take care of it? WHat about this experimental attribute: 'data-loading-strategy'. The docs says: Supported value: prefer-viewability-over-views. Instructs AMP to load ads in a way that prefers a high degree of viewability, while sometimes loading too late to generate a view.
We don't want to generate very hight impressions (will happen if we put all ad slots on a page right away), with very low viewability (will happen if user won't scroll through the entire article for example, with the ads already there).
Thank you in advance for your answer.

**Comment by jasti** [comment]
prefer-viewability-over-views is not available to use in production at the moment, but soon will be. prefer-viewability-over-views will solve your exact problem. i.e. only when an ad is within 1.25 * the viewport is when the ad will be requested. This is all taken care of by the amp js. Please check back in 2 weeks for GA.

**Comment by obeyer** [comment]
@jasti thank you! what is the behavior now (without the aforementioned parameter)? I noticed the ads also don't load until they are scrolled into view (if you are scrolling fast enough). is that true?

**Comment by jasti** [comment]
The current behavior doesn't necessarily optimize for viewability. i.e. some ads in the bottom of the page could be requested even if the user doesn't reach the bottom of the page.

**Comment by cramforce** [comment]
@obeyer the current behavior is a compromise that tries to balance impact on page load time by ads with trying to get them rendered by the time users see them. We don't really care about fast scrolling. The goal is to have them loaded with realistic scrolling.

The new strategy loads ads a bit later, so it is more likely they aren't done by the time the users sees them but also less likely they are loaded at all when they aren't going to be seen.
