### ISSUE TITLE
Upgrade `@percy/puppeteer` to v1.x

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#24869]
The version currently in use ([0.4.0](https://github.com/percy/percy-puppeteer/releases/tag/v0.4.0)) is more than a year old, and has a few dependencies with security vulnerabilities. 

https://github.com/ampproject/amphtml/blob/6f0465b998d62c302d0126b547e987539f2e75d9/build-system/tasks/visual-diff/package.json#L6-L9

![image](https://user-images.githubusercontent.com/26553114/66085048-23a10900-e53e-11e9-8dc8-67619beb4510.png)

The renovate upgrade PR (#23462) could not be checked in because the new version introduces [breaking changes](https://github.com/ampproject/amphtml/pull/23462#issuecomment-513959254).

We've manually upgraded transitive dependencies in the past (#23789), but it's hard to maintain a good state this way due to the large number of (outdated) dependencies involved.

**Comment by rsimha** [comment]
Can confirm that all security warnings due to this package have gone away.

**Comment by danielrozenberg** [comment]
🎉🎉🎉
