### ISSUE TITLE
Error AMP

### ISSUE THREAD

**Issue by Gradk** [ampproject/amphtml#24878]
Hello, there was a plugin on my site earlier. Website virilismed.ru

Now we have traffic from a page which does not exist:

http://virilismed-ru.cdn.ampproject.org/c/s/virilismed.ru/services-ozdorovitelnoprofilakticheskiy_kompleks-grudnichkovoe_plavanie/amp/

This traffic is not live, it's some kind of bots, how to remove it? It spoils company statistics

**Comment by choumx** [comment]
We don't have control over crawlers. Have you considered blocking traffic by referrer?

**Comment by mikaramotosan** [comment]
> 
> 
> We don't have control over crawlers. Have you considered blocking traffic by referrer?

referrer has different ip (more than 100 ip)
