### ISSUE TITLE
Can i use WP custom post for AMP Live List (Live blog )

### ISSUE THREAD

**Issue by themeenanaresh** [ampproject/amphtml#24874]
i am created live blog on my wp site. i am insert live entry by wp custom post . but this not show on google live red icon lable. liveblogposting schema is good working. only not implement amp live list rules.

please can you help me ..... amp-live-list makeing

<?php

/**
 * liveblog_article_meta_view
 * @param type $post
 */
function liveblog_article_meta_view($post) {
    $post_id = $post->ID;
    $published = $post->post_date;
    $modified = $post->post_modified;
    $date_atom = DATE_ATOM; //"Y-m-d\TH:m:s+G:i";

    $event_start = get_post_meta($post->ID, 'event_start', true);
    $event_end = get_post_meta($post->ID, 'event_end', true);

    $excerpt = wp_strip_all_tags(get_the_excerpt($post_id));
    $excerpt = substr($excerpt, 0, 150);
    ?>
    <meta itemprop="headline" content="<?php echo get_the_title($post_id); ?>" >
    <meta itemprop="datePublished" content="<?php echo date($date_atom, strtotime($published)); ?>">
       <meta itemprop="dateModified" content="<?php echo date($date_atom, strtotime($modified)); ?>">
       <meta itemprop="coverageStartTime" content="<?php echo date($date_atom, strtotime($event_start)); ?>">
    <meta itemprop="coverageEndTime" content="<?php echo date($date_atom, strtotime($event_end)); ?>">
    <span itemtype="https://schema.org/ImageObject" itemscope="itemscope" itemprop="image">
        <meta itemprop="url" content="<?php echo get_the_post_thumbnail_url($post_id, 'full'); ?>">
        <meta content="480" itemprop="width">
        <meta content="267" itemprop="height">
    </span>     
    <?php
    $keywords = array();
    $post_tags = get_the_tags($post_id);
    if (!empty($post_tags)) {
        foreach ($post_tags as $tag) {
            $keywords[] = $tag->name;
        }
    }
    ?>

    <meta itemprop="keywords" content="<?php echo implode(", ", $keywords); ?>">
    <meta itemprop="about" content="event">
    <meta itemprop="url" content="<?php echo get_permalink($post_id); ?>">
    <meta itemprop="description" content="<?php echo $excerpt; ?>">
    <?php
}

add_action("liveblog_article_meta", "liveblog_article_meta_view");

/**
 * todaylive_blog_shotcode
 * 
 * @param type $atts
 * @param type $content
 * @return type
 */
function todaylive_blog_shotcode($atts, $content) {

    global $post;
    $post_id = $post->ID;
    ob_start();
    ?><div id="tlive-wrapper">
        <div id="liveblogstart"></div>
        <div class="bloghead"><h2 class="liveblogbg">Live Blog</h2>
            <?php if (is_user_logged_in()): ?>
                <a target="_blank" href="<?php echo admin_url('post-new.php?post_type=liveblog&livepid=' . $post_id); ?>">Add New</a>
            <?php endif; ?>
        </div>
        <div class="LiveAjaxWrapper">
            <div id="tlive-conatiner" class="LiveAjaxContainer" >
                <div itemtype="http://schema.org/LiveBlogPosting" itemscope="itemscope">
                    <?php
                    do_action("liveblog_article_meta", $post);

                    $lvp = (!empty($_POST['lvp'])) ? $_POST['lvp'] : 1;

                    $per_page = 40;
                    $count_posts_args = array(
                        'post_type' => 'liveblog',
                        'post_status' => 'publish',
                        'meta_key' => 'liveblog_parent',
                        'meta_value' => $post_id,
                        'posts_per_page' => -1,
                    );
                    $count_pages = count(get_posts($count_posts_args));

                    //  date_default_timezone_set('IST'); 
                    $post_args = array(
                        'post_type' => 'liveblog',
                        'post_status' => 'publish',
                        'meta_key' => 'liveblog_parent',
                        'meta_value' => $post_id,
                        'posts_per_page' => $per_page,
                        'paged' => $lvp
                    );
                    $lives = get_posts($post_args);

                    $date_atom = DATE_ATOM; //"Y-m-d\TH:m:s+G:i";
                    if (count($lives) > 0):
                        foreach ($lives as $live):
                            // print_r($live);
                            $share_url = urlencode(get_permalink($post_id) . "#liveblog" . $live->ID);
                            $share_title = urlencode($live->post_title);
                            ?>
                            

                            <div id="liveblog<?php echo $live->ID; ?>" class="live-item-wrapper">
                                <div class="liveitem-share">
                                    <div class="liveitemdate">
                                        <span class="item-time"><?php echo date("G:i", strtotime($live->post_modified)) . ' (IST)'; ?></span>
                                        <span class="item-date"> <?php echo date("j M Y", strtotime($live->post_modified)); ?></span>
                                    </div>
                                    <div class="liveshare">
                                        <a class="mh-facebook" href="#" onclick="window.open('https://www.facebook.com/sharer.php?u=<?php echo $share_url; ?>&amp;t=<?php echo $share_title; ?>', 'facebookShare', 'width=626,height=436'); return false;" title="Share on Facebook">
                                            <span class="mh-share-button"><i class="fa fa-facebook"></i></span>
                                        </a>
                                        <a class="mh-twitter" href="#" onclick="window.open('https://twitter.com/share?text=<?php echo $share_title; ?>&amp;url=<?php echo $share_url; ?>', 'twitterShare', 'width=626,height=436'); return false;" title="Tweet This Post">
                                            <span class="mh-share-button"><i class="fa fa-twitter"></i></span>
                                        </a>
                                        <a class="mh-whatsapp" href="whatsapp://send?text=<?php echo $share_title; ?>&amp;url=<?php echo $share_url; ?>" data-action="share/whatsapp/share" title="Share via Whatsapp">
                                            <span class="mh-share-button"><i class="fa fa-whatsapp"></i></span>
                                        </a>
                                    </div>
                                </div>                        
                                <div itemtype="http://schema.org/BlogPosting" itemprop="liveBlogUpdate" itemscope="itemscope" class="live-post-<?php echo $live->ID; ?> tlive-post">

                                    <time itemprop="datePublished" datetime="<?php echo date($date_atom, strtotime($live->post_date)); ?>"></time>
                                    <url itemprop="url" content="<?php echo get_permalink($post_id) . "#liveblog" . $live->ID; ?>"></url>
                                    <span itemscope="itemscope" itemprop="author" itemtype="http://schema.org/Person">
                                        <meta content="<?php echo site_url(); ?>" itemprop="sameAs">
                                        <meta content="<?php echo get_the_author_meta('display_name', $live->post_author); ?>" itemprop="name">
                                    </span>
                                    <?php //get_avatar_url  <?php bloginfo('template_directory'); ? >/images/image-meta-logo.png  ?>
                                    <span itemtype="https://schema.org/ImageObject" itemscope="itemscope" itemprop="image">
                                        <meta itemprop="url" content="<?php echo get_avatar_url($live->post_author); ?>">
                                        <meta content="480" itemprop="width">
                                        <meta content="267" itemprop="height">
                                    </span> 
                                    <span itemtype="https://schema.org/Organization" itemscope="itemscope" itemprop="publisher">
                                        <span itemtype="https://schema.org/ImageObject" itemscope="itemscope" itemprop="logo">
                                            <meta content="<?php bloginfo('template_directory'); ?>/images/publisher-logo.png" itemprop="url">
                                            <meta content="125" itemprop="width">
                                            <meta content="26" itemprop="height">
                                        </span>
                                        <meta content="<?php bloginfo('name'); ?>" itemprop="name">
                                    </span>

                                    <meta itemprop="mainEntityOfPage" content="<?php echo get_permalink($post_id); ?>">
                                    <meta itemprop="dateModified" content="<?php echo date($date_atom, strtotime($live->post_modified)); /* echo date('Y-m-d', strtotime($live->post_modified)).'T'.date('H:m:s', strtotime($live->post_modified)).'+05:30'; */ ?>">
                                    <meta itemprop="headline" content="<?php echo $live->post_title; ?>">
                                    <h3><?php echo $live->post_title; ?></h3>
                                    <div itemprop="articleBody">
                                        <?php echo apply_filters("the_content", $live->post_content); ?>  
                                    </div>
                                    <?php
                                    $keywords = array();
                                    $post_tags = get_the_tags($live->ID);
                                    if (!empty($post_tags)) {
                                        foreach ($post_tags as $tag) {
                                            $keywords[] = $tag->name;
                                        }
                                    }
                                    ?>

                                    <meta itemprop="keywords" content="<?php echo implode(", ", $keywords); ?>">                            
                                </div>
                            </div>
                            
                            <?php
                        endforeach;
                    endif;
                    ?>
                </div>
            </div>
        </div>    
        <?php if ($count_pages - $per_page > 0): ?>
            <div class="loadmore-wrapper"><a href="javascript:;" id="liveloadmore">Load more</a></div>
        <?php endif; ?>
    </div>

    <?php
    return ob_get_clean();
}

add_shortcode('todayliveblog', 'todaylive_blog_shotcode');

add_action("wp_head", function() {

    if (is_single()) {
        ?><meta http-equiv="refresh" content="300;url=<?php the_permalink(); ?>?#liveblogstart"><?php
    }
});

add_action("wp_footer", function() {
    ?><script>
            jQuery(document).ready(function ($) {
                var lvp = 2
                $("#liveloadmore").click(function () {
                    $.post(window.location, {lvp: lvp}, function (data) {

                        var livehtml = $(data).find(".LiveAjaxContainer").html();
                        console.log(livehtml.trim().length);
                        if (livehtml.trim().length == 0) {
                            $("#liveloadmore").parent().hide();
                            return false;
                        }
                        $(".LiveAjaxContainer").append(livehtml);

                        console.log('Ajax Run');
                        lvp++;
                    });

                    /*$(".LiveAjaxWrapper").load(window.location+" .LiveAjaxContainer", {lvp:lvp}, function(data){
                     console.log('Ajax Run');
                     lvp++;
                     });*/
                });
            });
    </script><?php
});

**Comment by nainar** [comment]
Please use slack for questions regarding use AMP components: https://bit.ly/amp-slack-signup

Documentation on how to use amp-live-list: https://amp.dev/documentation/components/amp-live-list/
