### ISSUE TITLE
AMP4Email: Support autocomplete

### ISSUE THREAD

**Issue by Sitanderkumar** [ampproject/amphtml#24881]
I am trying to create a search widget in AMP email, below is the code.
but i am getting in promise error in the console when clicking on the submit button. 

@and is there any way to use autosuggest for from and to the field.

```html
<form method="post" action-xhr="https://m.cheapoair.com/remotesearchhandler.aspx"   id="widget-form"  id="widget-form" >
<!-- <span [text]="'formDataVar.originCityCode = ' + formDataVar.originCityCode + 'formDataVar.originCity = ' + formDataVar.originCity  + 'formDataVar.originquery = ' + formDataVar.originquery "></span> -->
	<input type="search" name="from" id="from" class="search-box" required="" pattern="[A-Za-z\s]+">
	<input type="search" name="to" id="to" class="search-box" required="" pattern="[A-Za-z\s]+">
	<input type="submit" value="Search" id="search"> </div>
</form>
```
@nainar @cvializ

**Comment by nainar** [comment]
Hi, for autocomplete we suggest using amp-autocomplete: https://amp.dev/documentation/examples/components/amp-autocomplete/

**Comment by Sitanderkumar** [comment]
Thanks Nainar,

but this auto-suggest not acceptable by amp4emai.

**Comment by Sitanderkumar** [comment]
a part for  it, as i already mentioned above that form that i am trying  to create in email is giving me error when click on submit button. (find code above)

![image](https://user-images.githubusercontent.com/36926473/66202344-1d886500-e6c3-11e9-9f75-46cc559782eb.png)

**Comment by sparhami** [comment]
The `amp-autocomplete` is not yet valid in the email format. I know @caroqliu is working on some autocomplete functionality for emails. t I think for the basic component, it is only a matter of the email format working group being comfortable with allowing the component in the current state.

**Comment by ggaabe** [comment]
Is there a spec for which native autocomplete attributes will be supported in email? It seems certain ones fail while others work fine.

**Comment by caroqliu** [comment]
> Is there a spec for which native autocomplete attributes will be supported in email? It seems certain ones fail while others work fine.

All attributes listed in the email-view of amp.dev should work: https://amp.dev/documentation/components/amp-autocomplete/?format=email
