### ISSUE TITLE
Request to add @leafsy as reviewer

### ISSUE THREAD

**Issue by leafsy** [ampproject/amphtml#24897]
Request to be added to the reviewers group (and get those sweet merge permissions).

[Reviewer requirements ](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#reviewers) & [Relevant PR's](https://github.com/ampproject/amphtml/pulls?q=is%3Apr+author%3Aleafsy)

/cc @cathyxz

**Comment by cathyxz** [comment]
Hi @mrjoro! Since @leafsy does meet the reviewer requirements referenced above, do you think you could add him to the reviewers github group? https://github.com/orgs/ampproject/teams/reviewers-amphtml/members.

**Comment by mrjoro** [comment]
Done!  Congrats on becoming a Reviewer @leafsy!
