### ISSUE TITLE
Amp-mowplayer using wrong version of mowplayer

### ISSUE THREAD

**Issue by micajuine-ho** [ampproject/amphtml#24903]
The `amp-mowplayer` does not load the media due to using the wrong version of the mowplayer. 
The problem can be viewed in test/manual/amp-video.amp.html under the `amp-mowplayer` dropdown  in the console.

**Comment by wassgha** [comment]
Being investigated by the team @MowPlayer

**Comment by gopanisandip** [comment]
Hi  Yes! Let me fix this issue.

**Comment by gopanisandip** [comment]
@wassgha   Please check PR for this bug fix https://github.com/ampproject/amphtml/pull/25484
