### ISSUE TITLE
Display a description in analytics-notification example

### ISSUE THREAD

**Issue by micajuine-ho** [ampproject/amphtml#24905]
In examples/analytics-notifications.amp.html, let's add a description to let the reader know what is happening behind the scenes and what to expect in the developer console.

**Comment by ajitsinghkaler** [comment]
@micajuine-ho Hi, I would like to work on this but I need more details on this. This is also my first contribution I would really appreciate if you can guide me through it.

**Comment by micajuine-ho** [comment]
@ajitsinghkaler Hi Ajit. Happy to you guide you through this. Have you taken a look at the resources in the contributing folder? [This](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md) is a good link that describes how to contribute code.

As for the issue, I imagine that adding some text in analytics-notifications.amp.html to describe what is happening would be sufficient. You can learn about what is happening with that page, specifically the amp-user-notification tag, [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-user-notification/amp-user-notification.md).

Let me know if you have any other questions.

**Comment by ajitsinghkaler** [comment]
After setup whenever I open analytics-notifications.amp.html I get the following error. Do, I need any additional setup for CORS on that page.

![Desktop screenshot (3)](https://user-images.githubusercontent.com/39260684/67698547-8ddb8b00-f9d0-11e9-90c9-c228299cec7d.png)

**Comment by micajuine-ho** [comment]
What commands are you running?

**Comment by ajitsinghkaler** [comment]
I'm running gulp command in the amphtml folder. After installing Gulp-CLI, nvm, yarn

**Comment by micajuine-ho** [comment]
I'm not sure about the CORS error, but the other errors make sense (because they're fake endpoints). 

Take a look at this [documentation](https://amp.dev/documentation/components/amp-user-notification/). 

It seems like the webpage is using the amp-user-notification tag in the same way that is shown in Example 1. Try substituting it out for Example 2 :)

**Comment by noodles** [comment]
Is this the kind of thing you're looking for?

![localhost_8000_examples_analytics-notification amp html(Pixel 2) (1)](https://user-images.githubusercontent.com/183972/68646101-3d3a6500-056e-11ea-936f-c8799512ef32.png)

**Comment by micajuine-ho** [comment]
@noodles Perfect!

**Comment by noodles** [comment]
@ajitsinghkaler are you still in interested in this issue?

**Comment by ajitsinghkaler** [comment]
Yes, I am but I can't figure out the CORS error is it okay if I still create a PR using your content.

**Comment by noodles** [comment]
@ajitsinghkaler to get rid of the CORS error, I replaced the amp-user-notification in the demo with 'Example 2' from the [documentation](https://amp.dev/documentation/components/amp-user-notification/) @micajuine-ho mentioned.

```
<amp-user-notification
      layout=nodisplay
      id="amp-user-notification6"
      data-persist-dismissal="false">
This notification should ALWAYS show on every page visit.
<a href="#learn-more">Learn more.</a>
<button on="tap:amp-user-notification6.dismiss">Dismiss</button>
</amp-user-notification>
```
After that, I just edited the text in the notification and added an explanation to the body of the page. Does that help?

**Comment by ajitsinghkaler** [comment]
So, should I generate the pull request or you are generating it because you solved it first?

**Comment by noodles** [comment]
@ajitsinghkaler you found the issue first so please go ahead and create your own PR.

**Comment by ajitsinghkaler** [comment]
Thanks @noodles

**Comment by ajitsinghkaler** [comment]
@micajuine-ho is there a problem in the first example if there is a problem then should I create a new issue for that.

**Comment by micajuine-ho** [comment]
@ajitsinghkaler I don't think there is a problem with example 1. Example 2 is just more straightforward and easier to understand :)

**Comment by ajitsinghkaler** [comment]
@micajuine-ho So, should we add example 2 as the default example.

**Comment by ajitsinghkaler** [comment]
@micajuine-ho So should example 2 be the default example. What are your thoughts on it?

**Comment by micajuine-ho** [comment]
@ajitsinghkaler Example 1 will only display if the data-show-if-href gets a positive response from its endpoint. However since the endpoint in the example is fake, it will not show, which could be confusing.

Example 2 will always show, and so is less confusing.  We should use example 2 instead of 1 to reduce confusion.

**Comment by ajitsinghkaler** [comment]
So should I create an issue for that

**Comment by ajitsinghkaler** [comment]
I was asking if we should create a new issue for that

**Comment by micajuine-ho** [comment]
You should not, you can just create a PR and then reference this issue in the PR.

**Comment by ajitsinghkaler** [comment]
Okay, thanks for your help
