### ISSUE TITLE
🌸 Cherry-pick request for #24846 into #24694 (Pending)

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#24906]
# Cherry-pick request

| Issue | PR  | Production? | RC? | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---: | :-: | :---------: | :-: | :-----------: |
| #24778 | #24846 | **YES** | **YES** | #24694 |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

`(HTMLInputElement|HTMLTextAreaElement).value` prop setters and getters are broken on the `worker-dom` version bundled with `amp-script`. This breaks the vast majority of `<form>` use cases.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

A regression in the `worker-dom` version bundled with `amp-script` breaks getters and setters for `value` properties on `<input>` and `<textarea>` elements. This makes most `<form>` elements (or other scripted components that use either `HTMLInputElement|HTMLTextAreaElement`) unusable inside `amp-script`.

| Users affected | Impact |
| -------------- | ------ |
| *Unable to determine subset of `amp-script > form` users* | Breaks the vast majority of `<form>` use cases on `amp-script`. |

## Root Causes

1. `worker-dom` regression ampproject/worker-dom#667

## Action Items

N/A, handled in ampproject/worker-dom#669

### Things that went well

`TODO`

### Things that went wrong

`TODO`

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers @gmajoulet @kristoferbaxter

**Comment by cramforce** [comment]
Is this a cherry-pick into the current prod or into the currently blocked new prod release?

**Comment by alanorozco** [comment]
@cramforce Both. Duplicate issue or include here?

**Comment by cramforce** [comment]
1 issue, clearly documented.

I think this is a fine cherry-pick. I'd like a second opinion.

**Comment by gmajoulet** [comment]
What's the update on this cherry-pick? I'm starting the process for https://github.com/ampproject/amphtml/issues/24915

**Comment by dvoytenko** [comment]
Should be all ready

**Comment by dvoytenko** [comment]
Sorry, was responding to the wrong bug. No idea the status of this one.
