### ISSUE TITLE
🌸 Cherry-pick request for #24914 into 1909241711100 (Pending)

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#24915]
# Cherry-pick request

| Issue | PR  | Production? | RC? | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---: | :-: | :---------: | :-: | :-----------: |
| #24914  | #24913 | **No** | **Yes** | #1909241711100 |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

This breakage is affecting all AGSA traffic.

## Why is a RC cherry-pick not needed?

<_YOUR_REASONS_>

# Mini-postmortem

## Summary

A recent refactor on the AMP viewer implementation removed some methods that were used by the AGSA viewer script. The error broke the handshake between AMP documents and the AGSA viewer, hence broke many use cases.

| Users affected | Impact |
| -------------- | ------ |
| All AGSA users | pageView ping not sent, 3p components with non-cache URLs not working properly |

## Root Causes

A recent refactor on the AMP viewer implementation removed a function that were used by the AGSA viewer script

## Action Items

| Action Item | Type | Owner | PR # |
| ----------- | :--: | :---: | :--: |
| Document external viewer interface | Prevent | @<_USERNAME_> | #<_PR_NUMBER_> |
| Monitor expected error volume more closely | Prevent | @<_USERNAME_> | #<_PR_NUMBER_> |

## Lessons Learned
- There are many different AMP viewer, a change to the viewer interface can be a breaking change. 
- Monitoring the error graph is important
- Viewer integration please add CORS header if you allow AMP to collect error info

### Things that went well

- Prod was rolled back quickly
- The release 1909241711100 baseline was relatively clean to investigate and debug.

### Things that went wrong

- The error was not caught through error reporting. Errors were reported as ‘Script Errors’, that is reported at 0.1% as expected error. 

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by gmajoulet** [comment]
More context: this week's prod release has been rollbacked, and we will rollforward with this fix + cherry-pick canary

**Comment by cramforce** [comment]
Approved

**Comment by cramforce** [comment]
I'd like to understand in the postmortem why these errors didn't get reported to our error reporting service.

**Comment by dvoytenko** [comment]
> I'd like to understand in the postmortem why these errors didn't get reported to our error reporting service.

Ditto. @zhouyx could you pls check the error reporting in this environment?

**Comment by zhouyx** [comment]
Good point! Will do

**Comment by zhouyx** [comment]
to @gmajoulet for cherrypick

**Comment by zhouyx** [comment]
Still investigating why the error reporting doesn't work. 

A few findings:
1. I couldn't find any error related to `getFirstVisibleTime()` in the report.
2. I did find some (not a lot) `initMessagingChannel` error in the report.

I still can't explain why the error from agsa viewer script is not reported. @erwinmombay @jridgewell could you help with this.

For the "initMessagingChannel timeout" error. I found the timeout error got reported as a user error. And we missed that when monitoring the error report.

**Comment by cramforce** [comment]
Could it be that something in that script is catching and not reporting the errors? Our global error handler should otherwise report them.

**Comment by dvoytenko** [comment]
Yeah, at the very minimum we need to make sure that any integration script would rethrow any error so that we have a chance to catch them in canary. I'm wondering if those errors get caught in the `detectNonAmpJs` branch. But even in that case we should see 1% of errors.

**Comment by gmajoulet** [comment]
This cherry-pick has been deployed yesterday. Re-assigning to @zhouyx

**Comment by zhouyx** [comment]
Thank you @gmajoulet I'll fill in the post mortem later this week : )

> I'm wondering if those errors get caught in the detectNonAmpJs branch.

I tested this. Doesn't seem to be the issue. 

>Could it be that something in that script is catching and not reporting the errors?

Good point. I'll confirm with them.

**Comment by zhouyx** [comment]
Found the reason why the errors are not reported. 

Related to #7353

Errors from the va2.js script are reported as `Script error` because it is from a different domain, and we failed to put `access-control-allow-origin: *` to the header.

**Comment by zhouyx** [comment]
Looked at the dashboard. There was a spike. The "Script error" was reported as expected error, which unfortunately we didn't notice the spike immediately : (

**Comment by dvoytenko** [comment]
I think we should start monitoring expected errors more closely. The goal with such errors is not to get them to 0, but instead monitor their delta from the previous release's baseline.

**Comment by zhouyx** [comment]
+1. Is it possible to send out alert whenever the delta is too big?

**Comment by cramforce** [comment]
Also: Are you adding the CORS header?

**Comment by zhouyx** [comment]
@jridgewell is fixing the CORS header. Thank you @jridgewell

**Comment by zhouyx** [comment]
CORS header added. 
Mini-postmortem updated. Closing the issue.

**Comment by cpapazian** [comment]
@zhouyx is the mini-postmortem for this publicly available? thanks!

**Comment by zhouyx** [comment]
Yes, the mini-postmortem is updated in the Issue description above.
