### ISSUE TITLE
amp-toolbox/optimizer should set AMP_CONFIG URLs when self-hosting AMP JS

### ISSUE THREAD

**Issue by mattwomple** [ampproject/amphtml#24927]
## What's the issue?

When AMP pages that have been optimized using the [amp-toolbox transformer](https://github.com/ampproject/amp-toolbox/tree/master/packages/optimizer/lib/transformers) are loaded into a PWA using `shadow-v0.js`, any self-hosted AMP runtime URLs for AMP extensions are ignored and `cdn.ampproject.org` is used instead.

## How do we reproduce the issue?

_Edited 2019-10-07 with much simpler sample._

A minimal example PWA that illustrates this issue is available at:

- [self-hosted-amprt-amp.html](https://android.cmphys.com/temp/self-hosted-amprt-amp.html) - Original AMP page
- [self-hosted-amprt-opt.html](https://android.cmphys.com/temp/self-hosted-amprt-opt.html) - Transformed AMP page with self-hosted AMP runtime
- [self-hosted-amprt-pwa.html](https://android.cmphys.com/temp/self-hosted-amprt-pwa.html) - PWA. Accepts query param ?page=amp to load the original AMP page and ?page=opt to load the transformed page. `shadow-v0.js` is set to pull from a self-hosted runtime, regardless of AMP page loaded.

These HTML files, along with the simple node.js script that transformed `-amp.html` to `-opt.html` is available in [github.com/mattwomple/self-hosted-amp-pwa](https://github.com/mattwomple/self-hosted-amp-pwa).

Watch the network traffic when loading `self-hosted-amprt-amp.html`. You should see `v0.js` and `amp-form-0.1.js` are requested from `https://amp-android.cmphys.com/7769/amp-dist/`. Note: `amp-auto-lightbox-0.1.js` loads from `cdn.ampproject.org` because it is added dynamically; this is another issue for another day.

Next, watch the network traffic when loading `self-hosted-amprt-pwa.html`. Notice `shadow-v0.js` is requested from `https://amp-android.cmphys.com/7769/amp-dist/` but `amp-form-0.1.js` is requested from `https://cdn.ampproject.org/rtv/011909141409590/v0/`. This is what I hope can be fixed.

## What browsers are affected?

All browsers. Tested on Chrome 77.

## Which AMP version is affected?

1909141409590

**Comment by sebastianbenz** [comment]
Thanks for filing this Matt! This will also become relevant once we will officially support self-hosting the runtime. It'd be nice to have a way to do this that doesn't require rewriting the runtime bundles. Maybe `<meta name="runtime-host" content="example.com">`? We could ensure via the validator that this is only allowed if `<html transformed="XXXXX">` is set.

//cc @honeybadgerdontcare 

P.S. Sorry, for the issue transferral noise (should've read to the end first).

**Comment by choumx** [comment]
@mattwomple Right, you'd need to overwrite the `self.AMP_CONFIG={...}` line not simply prepend. Sorry for the confusion.

**Comment by mattwomple** [comment]
The bulk of this issue is remedied by setting an environment variable before loading `shadow-v0.js`:
```
<script>
  window.AMP_CONFIG = {
    cdnUrl: 'https://amp-android.cmphys.com/7769/amp-dist'
  };
</script>
```
There are still some changes necessary to bring amphtml in-line with amp-toolbox/optimizer, hence the PR.

**Comment by choumx** [comment]
That's a good workaround.

**Comment by mattwomple** [comment]
Closing in favor of #25873.
