### ISSUE TITLE
Validation: The attribute 'start' may not appear in tag 'ol'

### ISSUE THREAD

**Issue by mjangda** [ampproject/amphtml#2493]
AMP Version 1456954860788

Using the `start` attribute in an `ol` triggers a validation error even though it's an allowed attribute: https://www.w3.org/TR/html-markup/ol.html#ol.attrs.start

Example:

```
<ol start="3">
  <li>This is item #3</li>
</ol>
```

**Comment by Gregable** [comment]
Good catch. I was actually adding this attribute to our rules today. Should be out soon.

**Comment by rudygalfi** [comment]
Any update on this? Please close if resolved.

**Comment by Gregable** [comment]
It's resolved. Looks like I missed this issue to update, thanks.
