### ISSUE TITLE
Can't use <section> within amp-accordion

### ISSUE THREAD

**Issue by iamschulz** [ampproject/amphtml#24930]
## What's the issue?
Using `<section>` nested within the content of `<amp-accordion>` causes the validator to throw an error:
```The parent tag of tag 'amp-accordion > section' is 'div', but it can only be 'amp-accordion'.```
The page renders and functions just fine in all browsers, I just get the error from the validator.
I expect to be able to use semantic html5 tags, such as section, within an accordion.

## How do we reproduce the issue?
1. go to: https://output.jsbin.com/tijawuzuna
2. validate the page
3. confirm aforementioned error message

## What browsers are affected?
The page renders and functions just fine in all browsers, I just get the error from the validator.
I tested the chrome extension as well as the web based validator at https://validator.ampproject.org

## Which AMP version is affected?
1909181902540

**Comment by honeybadgerdontcare** [comment]
This is working as intended. The element `section` must be a child of `amp-accordion`.  In this case the parent of `section` is `div`. One could put the `div` as a child of `section` instead.

Note the [documentation](https://amp.dev/documentation/components/amp-accordion/) explicitly states:
```
An amp-accordion can contain one or more <section> elements as its direct children.
```
