### ISSUE TITLE
Configurable timing for "add to home screen" e.g. beforeinstallprompt

### ISSUE THREAD

**Issue by gilbertococchi** [ampproject/amphtml#24933]
Hi all, I've tried to prevent the Chrome PWA Mini-Info bar showing by intercepting the beforeInstallPrompt event via Amp-Script in this [demo](https://developers.google.com/web/fundamentals/app-install-banners) but it doesn't seem to work.

https://amp-beforeinstallpropmpt.glitch.me

Can we support this event into the AMP-Script Worker DOM if possible to be able to control the showing of the [PWA Web App Install Banner](https://developers.google.com/web/fundamentals/app-install-banners)? 

AMP First websites would benefit of this by choosing when to show the prompt to avoid also showing multiple prompt at once (thinking about Amp-Consent prompt covered by the PWA one).

**Comment by choumx** [comment]
Ah, amp-script/worker-dom runs JS on a web worker, which doesn't have access to main thread objects like `window`. So support `beforeinstallprompt` event would need to be a special integration.

**Comment by choumx** [comment]
@gilbertococchi Can you share specifically under what conditions you'd want to for the app install prompt to be displayed? This may be more easily accomplished with components other than `amp-script`.

**Comment by gilbertococchi** [comment]
Hi William, thanks for your answer.

I would be really interested to hear more voices but so far I've see the following potential issues that may cause a UX issues on AMP First Websites.

Example: Browser http://standard.co.uk/ directly out from AMP Cache.

Result: AMP-Consent loading, Amp-sticky-ad loading, lastly Chrome MiniInfobar loading.
All of the three one over the other.

I believe it would be interesting to give developers the power to decide to display these consents in order.

Although I agree with you that the amp-script may not be the correct contest where to do that, but a part from this I don't know if we can have other windows of JS handlers to do the same.

@b1tr0t and @nainar for additional feedback about UX Chrome Permissions on AMP

**Comment by gilbertococchi** [comment]
Hi @nainar and @choumx, the condition that would require an AMP page to intercept and handle beforeInstallPrompt is when a website wants to implement Native App Install Banners https://developers.google.com/web/fundamentals/app-install-banners/native.

Unfortunately the only way to make it work would be to handle beforeInstallPrompt somehow, that's why I thought about using amp-script to support that but if you have alternatives in mind I am happy to discuss.

**Comment by gui-poa** [comment]
Same here, @gilbertococchi . Did you have any advance on making custom prompt to install PWA on AMP pages?
Maybe should have a new tag similar to [allow push notifications](https://amp.dev/documentation/components/amp-web-push/)

**Comment by gilbertococchi** [comment]
@nainar do you know if there is already a draft FR about a component to allow PWA UX Install personalization?

**Comment by nainar** [comment]
There isn't an FR - to pick up on @choumx's question earlier: 

what level of customization are you looking for in a PWA install prompt?

**Comment by gui-poa** [comment]
The main two things INMHO are: frequency (display control) and text/buttons.

I was thinking something related to [user-notification](https://amp.dev/documentation/examples/components/amp-user-notification/) with the option to display text and two buttons, like: Install / Not Now and track them. 

The "not now" could work exactly the same way as the "dismiss" in the user-notification

**Comment by romaincurutchet** [comment]
I am working with AMP publishers who would benefit from being able to configure the "Add to Home" PWA prompt, in terms of:
- Triggers: after X sec, after Y page visits...
- UI: being able to put the 'Add to Home' button in their navigation, on a newsletter sign-up page, inline an article...
It would be nice if this could be a feature request.

**Comment by HelaGone** [comment]
Hello everyone! 
Is there any advance in this matter?

I'm trying to accomplish the same behavior as described by @gilbertococchi along with send this user interaction to google analytics. 

Please advice
