### ISSUE TITLE
Top stories carousel in Google search results page

### ISSUE THREAD

**Issue by robertveramrf** [ampproject/amphtml#24931]
## What's the issue?

Top stories carousel in google serp is not showing the logo, only a fallback text.

Structured data validation tool is validating the structured data as correct and showing the logo in the preview.

## How do we reproduce the issue?

Make a search for **01net** in France location and french language. No logo in the carousel.

## What browsers are affected?

All browsers.

## Which AMP version is affected?

1909241711100

CURRENT STRUCTURED DATA

```
{
  "@context":"https://schema.org/",
  "@graph":[
    {
      "@context":"http://schema.org",
      "@type":"NewsArticle",
      "datePublished":"2019-10-07T12:07:06+02:00",
      "primaryImageOfPage":" ",
      "articleBody":"Article body hidden as is too long",
      "dateModified":"2019-10-07T10:15:35Z",
      "image":{
        "@type":"ImageObject",
        "height":"800",
        "url":"https://bc.marfeelcache.com/statics/i/ps/img.bfmtv.com/c/630/420/ba5/01154dad9c0c1b425a5c75a834962.png?width=1200&enable=upscale",
        "width":"1200"
      },
      "mainEntityOfPage":"https://www.01net.com/actualites/pourquoi-l-ipod-a-t-il-ete-un-si-gros-succes-l-un-de-ses-createurs-devoile-les-secrets-d-apple-1782216.html",
      "publisher":{
        "@type":"Organization",
        "logo":{
          "@type":"ImageObject",
          "height":"60",
          "url":"https://bc.marfeelcache.com/statics1340/www.01net.com/index/logo_carousel.png",
          "width":"142"
        },
        "name":"01net"
      }
    }
  ]
}
```

**Comment by choumx** [comment]
The amphtml repository is meant for issues concerning the AMP JS library. Consider Google Search or Structured Data support channels for these types of questions.

At a glance, it's possible that your article image is not [indexable/crawl-able](https://support.google.com/webmasters/answer/178636):

> Only a marked-up image that directly belongs to the article should be specified.
Images should be at least 1200 pixels wide.
Every page must contain at least one image (whether or not you include markup). Google will pick the best image to display in Search results based on the aspect ratio and resolution.
Image URLs must be crawlable and indexable.
Images must represent the marked up content.
Images must be in .jpg, .png, or .gif format.
For best results, provide multiple high-resolution images (minimum of 800,000 pixels when multiplying width and height) with the following aspect ratios: 16x9, 4x3, and 1x1.

https://developers.google.com/search/docs/data-types/article#logo-guidelines
