### ISSUE TITLE
Do not report an error status when Karma detects zero tests

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#24957]
Karma sometimes returns a transient state with zero tests. This is a recoverable state, so we shouldn’t be reporting an error to the github test status app. 

To fix this:

- Find the `karmaBrowserComplete_` function in `build-system/tasks/runtime-test/helpers.js`
- Remove the call to `reportTestErrored`
- Update the comment to reflect the fact that a warning is printed, but an error state is not reported

/cc @erwinmombay (who reported this a few days ago)

**Comment by amzick** [comment]
@rsimha I have taken a stab at this

**Comment by amzick** [comment]
Here's the PR:
https://github.com/ampproject/amphtml/pull/24959
