### ISSUE TITLE
[amp-script] AMP.setState() should trigger amp-bind script evaluation

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#24950]
Currently, calling AMP.setState({}) from within amp-script won't execute bindings. We should at least allow this if the AMP.setState call was initiated by an user interaction. 

My use case is: open a search dialog via a keyboard shortcut. 

Demo: https://amp-script-demos.glitch.me/#development=1

**Comment by choumx** [comment]
Thanks for the FR. Deduping with #24862.
