### ISSUE TITLE
Strip logging from production binary

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2497]
This is currently unavailable via the open source closure compiler's command line interface.

The solution would be to build our own runner. Should just be a small Java file with a main that parses a flag and then runs the compiler from the existing jar.

CC @dvoytenko

**Comment by erwinmombay** [comment]
fixed via https://github.com/ampproject/amphtml/pull/2593

**Comment by erwinmombay** [comment]
@cramforce what was the difference between this and https://github.com/ampproject/amphtml/issues/2386 ?

**Comment by cramforce** [comment]
6 days and a very lossy brain :)
