### ISSUE TITLE
Error: Server terminated early with status 1

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#24975]
Different e2e tests are failing with same error message on travis.

https://travis-ci.org/ampproject/amphtml/jobs/595223778
https://travis-ci.org/ampproject/amphtml/jobs/595298115
https://travis-ci.org/ampproject/amphtml/jobs/595298116
https://travis-ci.org/ampproject/amphtml/jobs/595254117

**Comment by rsimha** [comment]
Just a hunch: This could be a selenium error. Maybe try reverting https://github.com/ampproject/amphtml/commit/d844f994cf3060a173a9962047cab74330b92563

**Comment by estherkim** [comment]
My hunch as well. Haven't seen this error before.
