### ISSUE TITLE
Refactor and split purifier into an npm module

### ISSUE THREAD

**Issue by fstanis** [ampproject/amphtml#24970]
## Describe the new feature or change to an existing feature you'd like to see

Turn the functionality provided by [purifier.js](https://github.com/ampproject/amphtml/blob/0d1bebea5e4a9e4f388d59ce18ae0195e5a3aed9/src/purifier.js) into an npm module so that other projects can use it to implement `amp-mustache` in the same way AMP does it.

## Additional context

When the AMP Viewer API `viewerRenderTemplate` capability is used, the viewer is expected to perform mustache template rendering on behalf of the AMP document. To make this possible, the viewer needs to perform most of the functionality `amp-mustache` provides.

In this case, it's useful to share code with the AMP runtime - specifically, the purifier code sanitizes the rendered output, which is important to do in the same way as the AMP runtime for security reasons.

## Describe alternatives you've considered

One alternative is for the AMP Viewer API to perform the purify steps when `viewerRenderTemplate` is used, though this may limit the usefulness of that capability.

**Comment by fstanis** [comment]
Friendly ping on this, would make implementing ampproject/amp-email-viewer#7 much easier.

**Comment by choumx** [comment]
I'll try to carve out some time to do this but it might be awhile.
