### ISSUE TITLE
publish validator on npm

### ISSUE THREAD

**Issue by jaredmcdonald** [ampproject/amphtml#2498]
hi all--is it possible to publish the AMP validator (i.e. what ends up at https://cdn.ampproject.org/v0/validator.js) as an npm module? we're looking at ways of validating amp documents as part of our release pipeline and this would be super helpful. thanks!

**Comment by Gregable** [comment]
There is an unofficial project here: https://www.npmjs.com/package/amp-validator . We've talked about doing something a little differently, such that it doesn't require a headless browser, but haven't done so yet. It's definitely a todo.

**Comment by Gregable** [comment]
@jaredmcdonald , as an update, there is a node package that can be used in your release pipeline. Some documentation here:
https://github.com/ampproject/amphtml/tree/master/validator

We're working on releasing this as an npmjs module.

**Comment by powdercloud** [comment]
The Node.js API and command line tool for the validator is published here:
https://www.npmjs.com/package/amphtml-validator
