### ISSUE TITLE
[amp-list] support container layout if no src is provided

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#24983]
Currently, amp-list requires a layout, even if it is initially empty. It'd be nice to be able use a `container` layout if the list does not define a `src`:

```
<amp-list [src]=items layout=container>
  <template>
      <div>{{item}}</div>
  </template>
</amp-list>
```

which would be equivalent to:

```
<amp-list layout="fixed-height" height="0" [src]=items is-layout-container=items>
  <template>
      <div>{{item}}</div>
  </template>
</amp-list>
```

Combined with the `diffable` attribute, this would make amp-list a great way to implement isomorphic rendering:

```
<amp-list [src]=items layout=container diffable>
  <div role=list>
      <div role=listitem>Item 1</div>
      <div role=listitem>Item 2</div>
    </div>
  <template>
      <div>{{item}}</div>
  </template>
</amp-list>
```

//cc @nainar @choumx

**Comment by choumx** [comment]
Heh, `[diffable]` isn't even documented yet. 👀

This sounds reasonable though I'm curious about the "isomorphic rendering" use case.

**Comment by sebastianbenz** [comment]
With "isomorphic rendering" I mean using the same templates server and client-side.

**Comment by choumx** [comment]
Right, I mean you can have isomorphic rendering without `layout=container` no?

**Comment by sebastianbenz** [comment]
Yes, but if you don't know the height of your content, you have to do something like:

```
<div hidden=items>Initial content</div>
<amp-list layout="fixed-height" height="0" [src]=items is-layout-container=items>
  <template>
      <div>{{item}}</div>
  </template>
</amp-list>
```
