### ISSUE TITLE
Story attachment + React Router history conflict

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#24989]
From the Slack channel:

> Hi,
Is there anyone having a bug (on Safari Desktop) with the close button (top left cross) of a page attachment for an AMP-story contained in an Iframe ?
In my case, the first time I click : nothing happens; the second times : it goes to my previous page in my main window.
No problem for Chrome or Firefox.
https://codesandbox.io/s/a-simple-react-router-v4tutorial-d51lt
You will find the iframe in the "Buggy iframe" `<li>`.
When opening the codesandbox on Safari, opening the page attachment and then trying to close it, it will try to GoBack in the history of the router of the application.

**Comment by newmuis** [comment]
I wonder if this happens in sandboxed iframes?  My sense is that we should generally require stories to be embedded in sandboxed iframes.  Definitely something we should get right for our own embed library.

**Comment by dcombe** [comment]
@newmuis 
I did try it in a sandboxed iframe but it didn't change the behaviour.

**Comment by gmajoulet** [comment]
@dcombe are you sure that this is not a `codesandbox.io` issue? It doesn't repro when I go to the URL that codesandbox loads directly.

**Comment by dcombe** [comment]
@gmajoulet Yes this is not only happening on codesandbox.io, we can see this behaviour in a preview (of the AMP-Story) we provide to our users in our tool.

**Comment by gmajoulet** [comment]
Thanks for following up. I couldn't find an easy fix for now but will keep investigating next week!
