### ISSUE TITLE
Spanish version of CTA button text enum for AMP Stories Ads

### ISSUE THREAD

**Issue by elsilten** [ampproject/amphtml#25001]
## What's the issue?

Need spanish version of CTA button text enum for AMP Stories Ad (please!).

## How do we reproduce the issue?

I think this is just translate the button text. All the documentation about this is [in here](https://amp.dev/es/documentation/guides-and-tutorials/develop/story_ads_best_practices/?format=stories).

Thanks!

**Comment by newmuis** [comment]
The button text is currently shown in the language of the story, rather than the language of the advertisement.  Are you seeing an issue with the existing Spanish translations?
