### ISSUE TITLE
Doubleclick served a4a ads do not work when loaded in a PWA with shadowdom

### ISSUE THREAD

**Issue by indieisaconcept** [ampproject/amphtml#25007]
## What's the issue?

When loading an AMP document into a **shadowdoc** as part of **PWA**, should the document contain an `amp-ad` of type "doubleclick" which loads an **amp4ads** based ad, the ad fails to load due to numerous errors related to `No ampdoc found for [object HTMLHtmlElement]`.

![image](https://user-images.githubusercontent.com/640613/66576954-4c6f7100-ebc4-11e9-9abf-3a9ec129be71.png)

## How do we reproduce the issue?

A demo is available here: https://d1kvlucx6m02nr.cloudfront.net/

Upon first ( uncached ) load the ad loads correctly as the document is yet to be loaded within the shell container. 

![image](https://user-images.githubusercontent.com/640613/66577244-be47ba80-ebc4-11e9-82dd-1fb912318f2c.png)

However as soon as navigation occurs & the shell container is used the ad fail to load.

1. Navigate to https://d1kvlucx6m02nr.cloudfront.net/
2. Click on "Article 1"

## What browsers are affected?

All browsers

## Which AMP version is affected?

HTML shadows – Version 1910071803120

Based on previous issues related to PWA, shadowdoc & Doubleclick it looks like there may have a been a regression.

- https://github.com/ampproject/amphtml/issues/9679
- https://github.com/ampproject/amphtml/pull/9999

Additionally the a4a ad example loaded via projects example of a PWA is also broken. http://localhost:8000/pwa/

**Comment by indieisaconcept** [comment]
Just wondering whether this issue is on anyones radar in @ampproject/wg-ads

**Comment by jeffjose** [comment]
@calebcordry Would you mind taking a quick look?

**Comment by indieisaconcept** [comment]
Thanks @jeffjose & @calebcordry. FYI I had to replace the ad as it is no-longer being trafficked. I've replaced it with the a4a example.

**Comment by mehigh** [comment]
I've looked at the deme page myself in the latest Chrome Canary - it behaves in the same way as the screenshot posted here. It's behaving in the same fashion in Safari on OSX, so I can rule it out as being a browser-specific quirk.

**Comment by derekherman** [comment]
@calebcordry could you estimate when you would be able to put some headspace around this issue or find someone else on the AMP team that could?

**Comment by calebcordry** [comment]
@indieisaconcept @mehigh @derekherman Sorry for the delay. 

@indieisaconcept Thanks a lot for the example page.

Did some searching and I think this might be related to the work in #22734 @dvoytenko would you mind taking a look?

**Comment by indieisaconcept** [comment]
@calebcordry thanks. Happy to provide further support/examples as required to assist with getting this resolved.

**Comment by dvoytenko** [comment]
@calebcordry The #22734 is not launched yet. And based on error stacks I can confirm that this is not in the same codepath.

**Comment by calebcordry** [comment]
@dvoytenko thanks for checking. I will dig more into this today.

**Comment by calebcordry** [comment]
cc/ @ampproject/wg-ads

**Comment by indieisaconcept** [comment]
@calebcordry I had chance to pull down your branch. It looks like the change your proposing in #25321 resolves the issue which is great news.

**Comment by indieisaconcept** [comment]
@calebcordry great to see this merged. When do you think this could be feasibly released?

**Comment by calebcordry** [comment]
@indianburger While debugging this issue we also found a related issue fixed in #25357. We are currently discussing the risk/reward in trying a cherry pick. I will update here with the resolution. Worst case it would follow the normal [AMP release schedule](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md).

**Comment by dvoytenko** [comment]
Cherrypick is in #25367, so hopefully it can be in PROD sooner.

**Comment by calebcordry** [comment]
@indieisaconcept Change should now be live in canary. You can opt in at https://cdn.ampproject.org/experiments.html . I tested the new version on you example page, but feel free to test on your own, and let us know if you run into anything unexpected.

**Comment by indieisaconcept** [comment]
@calebcordry thanks! I can confirm based on testing that I am seeing the same behaviour as yourself with the example page & when testing against our pre-prod environment I am seeing ads load correctly.

**Comment by indieisaconcept** [comment]
@calebcordry, @dvoytenko just wanted to say thanks for getting this resolved so quickly. I verified again today following the prod release.

**Comment by dvoytenko** [comment]
@indieisaconcept Thanks for reporting and helping us repro this!

**Comment by jeffjose** [comment]
Thanks for the quick turnaround on this, @calebcordry and @dvoytenko!
