### ISSUE TITLE
amp-app-banner inside Google AMP Viewer in Safari iOS opens store always

### ISSUE THREAD

**Issue by abdelbolanos-cbc** [ampproject/amphtml#25019]
## What's the issue?

The amp-app-banner does not work correctly inside the Google AMP Viewer in Safari iOS.

Example URL: https://www.cbc.ca/amp/1.5317946

Viewer URL: https://www.google.com/amp/s/www.cbc.ca/amp/1.5317946

 Amp app banner (amp-app-banner) in Safari iOS in Google AMP Viewer always opens the store , independent of whether the app is installed or not.

## How do we reproduce the issue?

1. Open in Safari iOS the Viewer URL (or search for any CBC news from google search and open an amp card)
2. Click on "OPEN APP" in bottom amp-app-banner.
3. See the openInAppUrl fails (Safari here cannot open it) and opens the store, install app.
4. Go back to the viewer (Safari) and click "OPEN APP" again.
5. See how opens the openInAppUrl and in 1.5 second opens the store (that should not open it).

I took a look in the source code 
https://github.com/ampproject/amphtml/blob/master/extensions/amp-app-banner/0.1/amp-app-banner.js AmpIosAppBanner.openButtonClicked()

and it seems to be the expected behaviour, open the installAppUrl after 1.5 seconds of trying to open openInAppUrl.

Note: the Google AMP Viewer in Chrome iOS it works as expected (no issues here).

## What browsers are affected?

Safari on iOS (tested on iPhone 7 with version iOS 12.4.1)

## Which AMP version is affected?
AMP https://cdn.ampproject.org/v0.js

**Comment by alabiaga** [comment]
cc\ @ampproject/wg-ui-and-a11y

**Comment by manuhook** [comment]
This issue is still present on Safari iOS, the same behavior is also happening on Chrome iOS.
Can we reopen this ?
