### ISSUE TITLE
Story stuck in low connection situation

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#25020]
![Screenshot_20191011-121552](https://user-images.githubusercontent.com/89679/66689646-972ece80-ec40-11e9-9f1c-8e7111e8fe8f.png)

When I reached this slide (note the message that the video failed to load) I couldn't click anything.

**Comment by newmuis** [comment]
@cramforce do you have the URL of this story?

**Comment by cramforce** [comment]
https://www.usatoday.com/amp-stories/how-to-make-pumpkin-spice-latte-recipe/

**Comment by gmajoulet** [comment]
#26505
