### ISSUE TITLE
<figure> element wrapping an <amp-img> element is mis-sized

### ISSUE THREAD

**Issue by schlessera** [ampproject/amphtml#25032]
## What's the issue?

When wrapping an <amp-img> element with `layout="intrinsic"` in a <figure> element, the wrapping <figure> has a height that is a few pixels larger then the image it wraps.

This problem seems to be unrelated to any CSS being parsed, so I assumed this is JavaScript behavior inside the <amp-img> element that is broken.

![Image 2019-10-14 at 11 53 04 AM](https://user-images.githubusercontent.com/83631/66743458-3e4a7a80-ee7a-11e9-9e97-9edf420510d8.png)

## How do we reproduce the issue?

Markup to reproduce:

```html
<figure>
    <amp-img src="https://via.placeholder.com/580x300"
             width="580"
             height="300"
             layout="intrinsic"></amp-img>
</figure>
```

See https://codepen.io/schlessera/pen/BaaKaxo

## What browsers are affected?

Tested in Google Chrome Version 77.0.3865.120 (Official Build) (64-bit)

## Which AMP version is affected?

Seen in version 1910071803120.

**Comment by westonruter** [comment]
I think this might just be a CSS issue and may not be a problem with AMP. See https://github.com/ampproject/amp-wp/issues/3493#issuecomment-541772055

**Comment by schlessera** [comment]
The problem seems to stem from the fact that AMP sets the `<amp-img>` with an `intrinsic` layout to `display: inline-block;`, whereas the original image was styled to be `display: block;`.

I'm closing this issue as being a CSS problem, not a bug.
