### ISSUE TITLE
I2I: <amp-sidebar> v0.2

### ISSUE THREAD

**Issue by leafsy** [ampproject/amphtml#25049]
## Summary
Upgrade `<amp-sidebar>` to version 0.2 and introduce a new `<amp-nested-menu>` component for rendering nested drill down menus.

## Design document
https://docs.google.com/document/d/1FNduZqgOU8yl3j6_b-VpTvp9cmtbCfNQ25Vm8w-BXQc/edit?usp=sharing

## Motivation
Improve user experience and feature parity with existing sidebar component implementations, namely:
- Provide first class support for nested drill down menus (e.g. amazon.com);
- Support animations of the sidebar and document body for open and close;
- Move sidebar mask inside the component itself (#24827);
- Ensure that sidebar is compliant with accessibility standards and supports accessibility best practices.

**Comment by nainar** [comment]
Accessibility considerations: https://docs.google.com/document/d/12_F6DpT_KGHcONEhW04P_uPYu8V_q05JYQ5PmVF-LEE/edit

**Comment by mrjoro** [comment]
@wassgha the design linked to in this I2I is an internal-to-Google document.

- Is this I2I still active?
- If it is, can we make the design available in a public doc (on an amp.dev account)?
