### ISSUE TITLE
doubleclick ads with 3rd party tags: celtra inter scroller

### ISSUE THREAD

**Issue by obeyer** [ampproject/amphtml#2504]
We have some ads served through doubleclick as 3rd party tags, like celtra inter scroller. The resulting ad doesn't look ok, since the js fails to execute inside, and doesn't create the required element. Is there a different way in amp-ad for doubleclick ads to serve 3rd party ads?
For the reference, the inter scroller ads are in this gallery after the 4th and the 8th slide
http://popsugar.dev9.onsugar.com/fashion/What-Clothes-Should-I-Wear-My-30s-34356107/amp
and they look broken.
Same ads are ok on non-amp page (same ad slots and placement)
http://popsugar.dev9.onsugar.com/fashion/What-Clothes-Should-I-Wear-My-30s-34356107

If it is out of your scope, could you, please, refer me to the doubleclick ads engineering, so we could figure out if inter scroller ads are even possible in amp.
Thank you!

**Comment by jasti** [comment]
hi @obeyer I can't exactly reproduce and see ads on the 4th and 8th slide. Screenshot of some sort should help. The main thing with 3rd party tags is to ensure that all assets being served are SSL compliant.

**Comment by rudygalfi** [comment]
@obeyer Please reopen if you can provide screenshots or better help us understand the issue.

**Comment by obeyer** [comment]
@rudygalfi 
Hi! Sorry, but when you were checking the issue, the dev9 server weren't running tose ads anymore. Here's a link to production: http://www.popsugar.com/fashion/What-Clothes-Should-I-Wear-My-30s-34356107/amp
Look in the mobile simulator, or mobile phone (we have different ads served to mobile). You will see an interscroller ad after the 5th image, right before the image called 'The perfect pencil skirt'. The ad has balck bars at the top and bottom. Top says Advertisement, Bottom says 'Scroll to continue with content'. You can visit a non-amp page (just remove the amp from the end of the url), to see how the interscroller should behave: it should take the whole screen, and scroll inside

**Comment by rudygalfi** [comment]
Thanks. I can see it now. Attaching a screenshot.

@jasti @kashyapnitin  -- I think you're looking into this kind of format?

<img width="389" alt="screen shot 2016-03-31 at 11 23 15 am" src="https://cloud.githubusercontent.com/assets/3888212/14186418/264f358e-f733-11e5-9437-475f3fe36d43.png">

**Comment by jasti** [comment]
@obeyer Can you send me a link to your DFP lineitem that calls out the 3rd party? It's possible that the Celtra Inter Scroller tag is not SSL compliant and therefore the DFP lineitem competition would exclude it from being considered for an AMP ad request.

**Comment by mattc1176** [comment]
Hi there...I stumbled across this thread as I'm having issues trafficking an interscroller unit on mobile and was hoping for some help. It is a celtra tag, and I'm trying to get it up on several publishers that all use DFP. One has made it work using the out-of-page inventory size. However, not all sites use that placement. Does anyone have any insight on how to get this to serve using a different inventory size like 320x480 or 320x50? Also, what creative template works best?I'm trying to avoid any additional dev work on the publisher end such as adding an ad call or creating a new template. Any help is appreciated!!

**Comment by jasti** [comment]
@mattc1176 Do you have a link to the publisher that made it work?

**Comment by mattc1176** [comment]
Thanks for the reply, the one pub it's running on has a ton of sites so to try and find it live will not really work. The basic instructions from them are below: 
1-	set it up as an out-of-page with the custom OutOfPage creative. 
2-	Make sure to add the impression macro as follow : <img src="%%VIEW_URL_UNESC%%data:image/png,celtra"
3-	remove the checkmark in Serve into a SafeFrame otherwise the creative will not show.

That seemed to get it to work, but not sure how to take those instructions and make them work elsewhere if there's no out-of-page placement or custom creative template. Seems like these ads are becoming more popular so I would think serving it shouldn't require a ton of extra steps. Thanks!

**Comment by jasti** [comment]
Please consider using the flying carpet format which is live now or have Celtra directly support this AMP.

**Comment by ovived** [comment]
any one here want to help me with a similar problem for $ ?
