### ISSUE TITLE
[amp-consent-ui] postPromptUI element with id=post-consent-ui not found

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#25041]
## What's the issue?
`amp-consent-ui] postPromptUI element with id=post-consent-ui not found`

Briefly describe the bug.
There is an error while looking at any article on the HotNewHipHop page.

## How do we reproduce the issue?
1. Opt-in to Canary/RC
2. Open Java Console
3. Go to [link](https://www.google.com/amp/s/www.hotnewhiphop.com/lebron-james-brings-back-infamous-chalk-toss-routine-fans-react-news.93110.html%3f_amp)

## What browsers are affected?
Chrome Version: 77.0.3865.90
FireFox Version: 69.0.3

## Which AMP version is affected?

Canary/RC: 1910071804120

Code:
```
[amp-consent-ui] postPromptUI element with id=post-consent-ui not found

Na @ v0.js:8
f.ua @ v0.js:9
f.error @ v0.js:10
push.f.U.R @ amp-consent-0.1.js:38
U @ amp-consent-0.1.js:37
push.f.W.buildCallback @ amp-consent-0.1.js:52
(anonymous) @ v0.js:258
b.build @ v0.js:257
f.build @ v0.js:229
yk @ v0.js:319
xk @ v0.js:317
Ik @ v0.js:334
h @ v0.js:344
Wj.setState @ v0.js:309
f.doPass @ v0.js:327
(anonymous) @ v0.js:312
bj.xc @ v0.js:245
ig @ v0.js:245
(anonymous) @ v0.js:362
Promise.then (async)
f.delay @ v0.js:362
bj.schedule @ v0.js:245
f.schedulePass @ v0.js:324
(anonymous) @ v0.js:313
f.fire @ v0.js:209
f.ge @ v0.js:518
f.overrideVisibilityState @ v0.js:516
f.receiveMessage @ v0.js:418
(anonymous) @ amp-viewer-integration-0.1.js:34
Ea @ amp-viewer-integration-0.1.js:28
push.f.W.Z @ amp-viewer-integration-0.1.js:26
(anonymous) @ amp-viewer-integration-0.1.js:24

```

**Comment by sparhami** [comment]
This seems to be an issue on the publisher's side. They are missing an element with an id of `post-consent-ui`. It seems like they copied an example from the [documentation](https://amp.dev/documentation/components/amp-consent/), but left out the UI for when consent is given.

I get the same error when not in canary. I don't believe there is anything for us to do here.
