### ISSUE TITLE
Next Page pageview GA event fired in <amp-pixel> while using with <amp-next-page>

### ISSUE THREAD

**Issue by akkyverma** [ampproject/amphtml#25069]
**Next Page pageview GA event fired in `<amp-pixel>` while using with `<amp-next-page>`**
 
## What's the issue?
 
We are trying to implement `<amp-next-page>` functionality in our AMP pages and to fire GA pageviews as per the AMP documentation, `<amp-analytics>` is currently unsupported for pages added under `<amp-next-page>`. Here's a screenshot from the official documentation: https://images.hindi.news18.com/ibnkhabar/uploads/2019/10/doc.png

 

 
Hence in order to measure page views per suggestion, we are using `<amp-pixel>`, but amp-pixel seems to firing in background with XHR calls for next page even before user scrolls till the next page. This is leading to false analytics data for page views, which is undesirable. 

Please look into the screen capture. https://images.hindi.news18.com/ibnkhabar/uploads/2019/10/Issue.png

 
## How do we reproduce the issue?
 
1. Open browser with network tab in debug window.
2. Open the [URL](https://stgassam.news18.com/amp-infinite/news/nation/amit-shah-calls-meet-on-thursday-of-bjp-office-bearers-to-elect-new-party-chief-15587.html)
3. Write _collect_ in search field and just enter the URL in browser.
4. Now you can see 2 URLs (GA events under amp-pixel) fired - first for 'amit-shah-calls-meet-on-thursday-of-bjp-office-bearers-to-elect-new-party-chief...' and 2nd for next coming page when user is going to scroll to,  at the time of loading itself without any actual scroll or resize event. 
We sense that for optimizing the amp-next-page user experience, the next page is fetched before hand itself (as can be seen in the network tab with "fetch" event for the next page straight away) and since amp-pixel in part of the code which is getting fired even before it's in view and while the page is rendered, the event gets triggered before hand.

![Issue](https://user-images.githubusercontent.com/5645132/67068300-41ee4200-f197-11e9-952f-60e7035ae23f.png)

 
## What browsers are affected?
Tested only in Google Chrome Version 77.0.3865.90 (Official Build) (64-bit) [Mobile Device] Galaxy S5.
 
## Which AMP version is affected?
Powered by AMP ⚡ HTML – Version 1910071803120
`amp-next-page-0.1.js`

**Comment by zhouyx** [comment]
`<amp-pixel>` fires as soon as it has been built. @wassgha This should be fixed in the same way as `<amp-analytics>` which we need to start/pause the trigger based on signal from the `<amp-next-page>` component.

**Comment by DishaTatvic** [comment]
Hi All,

We are facing the same issue with few of our clients.
Additionally, we are also observing an issue of over-reporting of users when user lands on Google-hosted amp pages performing a search, with each subsequent scroll to the next article a different client id is generated with each pageview.

Thanks in advance for the help!

**Comment by wassgha** [comment]
Hey @DishaTatvic ,
Which version of the runtime are you using (see `console.log`) this fix only made it to the production build a few days ago. For the client id, how are you generating exactly?

Best
