### ISSUE TITLE
Add some people to Collaborators

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#25060]
I am cleaning up the list of people with merge access to the amphtml repo to conform with our [updated policy on Collaborators and Reviewers](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#code-review-and-approval), which we are now able to enforce with the Owners bot.

The following people currently have merge access to the amphtml repo and should continue to have this permission based on their knowledge of the AMP code / product.  By default I will add them to the Collaborators repo to maintain the status quo.  This means they will continue to have write access to the repo (assigning reviewers, adding labels, etc.) and can merge their own code once it has been reviewed by a Reviewer and OWNER.

For those on this list, if you want to be added to the Reviewers group and meet the [requirements](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#reviewers) (basically 10 non-trivial PRs and/or code reviews), add a comment here.  (The main benefit of being a Reviewer instead of a Collaborator is that your review on a PR can allow that PR to be merged; as a Collaborator this is only true if the PR author is also a Reviewer.)

@CrystalOnScript 
@diantekyrie 
@dparikh 
@fstanis 
@jasti 
@jeffjose 
@pbakaus 
@rudygalfi 
@thatbez 

/cc @ampproject/reviewers-amphtml to get a +1 on adding these people to Collaborators

**Comment by mrjoro** [comment]
With @rsimha's thumbs up, we have Reviewers approval so I'm adding everyone to Collaborators. :)

**Comment by mrjoro** [comment]
I missed @sebastianbenz as well; can I get a thumbs up from a Reviewer? :)

**Comment by cramforce** [comment]
I don't think @thatbez qualifies :)
