### ISSUE TITLE
amp-carousel v0.2 switches between cards after swiped out of the fullscreen

### ISSUE THREAD

**Issue by acsant** [ampproject/amphtml#25077]
**Please only file reports about bugs in AMP here.**

## What's the issue?
Originally [this issue](https://github.com/ampproject/amphtml/issues/24541) was filed to address the problem of cards in an `amp-carousel` being changed when scrolling on an AMP page. This issue still persists, however only when I swipe out of the carousel from the fullscreen mode.

## How do we reproduce the issue?
1) Click on the `amp-carousel` to open the full screen mode (requires `amp-lightbox-gallery`)
2) Swipe up to get out of the fullscreen lightbox mode
3) Scroll on the page (notice that the cards changed on scrolling on the page)

## What browsers are affected?
Safari iOS 13

![SwipeCarouselBug](https://user-images.githubusercontent.com/5479907/66949376-4128a500-f00b-11e9-9b43-e51d1b717007.gif)

**Comment by sparhami** [comment]
It looks like somehow the scroll position of the carousel is being changed when vertically scrolling (after you leave the lightbox mode). I'm not sure what is causing this, but I cannot seem to find anything in the carousel code itself causing this.

From local testing, it looks like this issue occurs on both carousel 0.1 and 0.2.

**Comment by acsant** [comment]
@sparhami There does seem some jankiness going on with vertically scrolling on the page:

![ScrollBug](https://user-images.githubusercontent.com/5479907/67135569-fc01a000-f1cf-11e9-8273-c7ae917bc035.gif)
