### ISSUE TITLE
Bad loading behavior with large images

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#25076]
Actually the large images might be a red herring, but otherwise this seems like a very simple doc:
https://www.theverge.com/platform/amp/2019/10/15/20915462/google-pixel-4-xl-iphone-11-pro-camera-comparison-test-photos-specs?__twitter_impression=true

This article wants to do image comparisons and thus is actually using the raw images off the phone without compression.

The problem repros in Chrome both on desktop and mobile, but it might require a slow connection.

Some of the images seems to be loading forever, but then somehow they flicker under the loader as one scrolls.

**Comment by sparhami** [comment]
Looking at the image loading and network request, it seems like the network requests are sometimes hanging on in a downloading state for quite a while. I was able to reproduce the issue using the "Fast 3G" network throttling from the Chrome devtools.

As far as the images showing, it seems like these progressive JPEGs (checked using ImageMagick): 

```sh
$ identify -verbose IMG_20191015_133227.jpg | grep Interlace
  Interlace: JPEG
```

There seems to be a brief period prior to us showing the loader where the partially loaded progressively image shows until we render the loading container on top of it. I suppose the same issue could happen for non-progressive images as well.

There are a few questions / concerns / things to follow up on here:

* Is there anyway to detect progressive vs baseline images? AFAIK there is nothing in the web standards to do this.
* Do we want to render the (a?) loader on top of progressively loading JPEGs, if we could detect them? If so, what kind of UI treatment do we want to give them?
* Should we discourage developers (and perhaps even warn from search console) if they use progressive images (and maybe suggest they use blurry placeholders instead)?
* Can we change the code to avoid the flash of the progressively loaded image in this case? Perhaps `visibility: hidden;` on the `<img>` it until the load event has fired?

/cc @ampproject/wg-ui-and-a11y

**Comment by nainar** [comment]
That's an interesting edge case catch. 
Seems like we can't tell if they are loading a progressive JPEG or a regular one to switch on that.

In this case the publisher should have the `noloading` attribute. If this page is served from the cache and the Blurry Placeholder project is launched we wouldn't have this issue since the loader would not be present anyway.

**Comment by cramforce** [comment]
We definitely can't rely on the cache for correctness.

I think that if we could load the image "behind" the loader that would be
best.
