### ISSUE TITLE
Request to add `mattwomple` as AMP collaborator

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#25074]
please add @mattwomple as AMP collaborator.

@mattwomple let us know if you are OK with this :)

**Comment by mattwomple** [comment]
Thank you for considering me! I reviewed the expectations at [Contributing code and features](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#roles) and it sounds fine to me.

My only hang-up is that most of the time I spend on the AMP Project is my free time. I can log hours at work if the issue I work on is directly related to bugs or feature requests we have at WompMobile. So, if collaborator status would require frequent meetings with working-groups, it may not be appropriate for me. There will be times that I'm simply not available. Could you let me know if there are additional expectations beyond what's written in the collaborator roles doc?

**Comment by mrjoro** [comment]
There aren't any additional expectations for Collaborators in terms of meetings/discussions/etc.  It basically gives you merge access and other permissions like adding reviewers/labels to PRs & issues.  A Reviewer who has a PR would also be able to merge their PR after you approve it.

You can use it purely for merging your own PRs if you prefer. :)

**Comment by mattwomple** [comment]
Thanks for the clarification @mrjoro . I'm happy to be considered for a Collaborator role! Also, fret not about trigger-happy merges. I try to be cautious and considerate of how my code affects other parts of a project and still have quite a ways to go before I see the forest for the trees in amphtml.

**Comment by erwinmombay** [comment]
yep absolutely no additional expectations. this is purely to make your life as a contributor easier (whether you choose to contribute or not is purely your discretion). We just appreciate your efforts and want to make it easier on you 😄

**Comment by mrjoro** [comment]
Done!  You should have merge rights now (though it says it may take up to 24 hours).

Once we get the ownersbot issue resolved you can try out your new powers on #24818. :)

**Comment by mattwomple** [comment]
@mrjoro Account @mattwomple will become inactive after Jan 30 when I finish up my work at WompMobile. I still work on AMP under my personal GitHub account @mdmower. If possible, it would be great to replace mattwomple with mdmower in the Collaborators group, otherwise, just removing mattwomple will be fine. Thanks!

**Comment by mrjoro** [comment]
Done!  I've added @mdmower to Collaborators and removed @mattwomple.  Let me know if you run into any issues.
