### ISSUE TITLE
Request to add `ChrisAntaki` as AMP collaborator

### ISSUE THREAD

**Issue by ChrisAntaki** [ampproject/amphtml#25089]
> A person may become a Collaborator after 2 merged PRs that are non-trivial (not only fixing typos, not only config changes) and a +1 from 1 current Reviewer. To request becoming a Collaborator file an issue in the repository in which you are requesting to be a Collaborator and cc a Reviewer in that repository.

https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#roles

Relevant PRs: #23163, #23256, #23269

/cc @dvoytenko

**Comment by dvoytenko** [comment]
Approved.

**Comment by ChrisAntaki** [comment]
Thanks!

**Comment by mrjoro** [comment]
Done!
