### ISSUE TITLE
PR Deploy Bot doesn't work with ads

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#25104]
Ads don't display on demos created by the PR deploy bot. For example: https://storage.googleapis.com/amp-test-website-1/amp_dist_65323/examples/ads.amp.html. 

Context: https://github.com/ampproject/amphtml/pull/25092#issuecomment-543302678. 

<img width="251" alt="Screenshot 2019-10-17 at 12 52 55 PM" src="https://user-images.githubusercontent.com/1528181/67042628-1870e000-f0dd-11e9-98aa-de5dcc1f90db.png">

The specific issues we're seeing is that crucial files (e.g. integration.js, frame, etc.) are 403-ing, and trying to load from a specific rtv, which I guess doesn't exist. 

/to @ampproject/wg-infra /cc @ampproject/wg-ads

**Comment by alanorozco** [comment]
This would be fixed by #32326

**Comment by cathyxz** [comment]
Nice! xD
