### ISSUE TITLE
amp-carousel: hide caption on tap

### ISSUE THREAD

**Issue by georgecrawford** [ampproject/amphtml#2510]
I'd like to request the ability to hide caption on tap (i.e. adding a CSS class to the carousel when tapped, so that captions superimposed over images can be hidden).

Let me know if you'd like any further details.

**Comment by georgecrawford** [comment]
We have some images with very long captions. For example:
![screenshot 2016-03-09 17 02 06](https://cloud.githubusercontent.com/assets/84737/13643428/b47a31b4-e618-11e5-8477-4b32ce60f737.png)
Our 'house style' is to float the caption over the image with a translucent background, but this really requires the caption to hide when tapped so the user can see the whole image.

Any other suggestions?

**Comment by dvoytenko** [comment]
@georgecrawford Not yet, but we should definitely support this. We have one option now to use `amp-fit-text`which would play with font size to try to fit more text, but that's obviously not enough for a caption this long. We'll find a way to accommodate this, just need to evaluate couple of options.

**Comment by georgecrawford** [comment]
I moved the pagination request to a new ticket: https://github.com/ampproject/amphtml/issues/2512

**Comment by georgecrawford** [comment]
I'm closely watching https://github.com/ampproject/amphtml/issues/1866, which would help greatly here. A simple carousel (with no captions, or truncated text using amp-fit-text) in combination with a lightbox to show larger images and full captions would be ideal.

**Comment by enatork** [comment]
@georgecrawford 
I created a pen that will hide/show a caption on an amp carousel using css selectors.  Hope this helps.
http://codepen.io/vanle/pen/XdErpM

**Comment by ericlindley-g** [comment]
Rolling into the next milestone

**Comment by poscar** [comment]
@enatork Thanks for that example. I simplified it to make it a "tap-image-to-view-caption" flow using figure and figcaption. Works pretty well!

**Comment by erwinmombay** [comment]
@enatork thats pretty awesome!

**Comment by aghassemi** [comment]
Closing as Lightbox 2.0 will have this feature.
