### ISSUE TITLE
Fix flaky visual diff test for `amp-consent`

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#25105]
The interactive test at `examples/visual-tests/amp-consent/amp-consent.js` has failed regularly over the past several weeks for PRs that don't touch any extension / runtime code.

Here are a bunch of failures from today. All snapshots are slightly different, which makes me think the page hasn't settled down before the snapshots were taken.

https://percy.io/ampproject/amphtml/builds/2843449
https://percy.io/ampproject/amphtml/builds/2836999
https://percy.io/ampproject/amphtml/builds/2836927
https://percy.io/ampproject/amphtml/builds/2836923
https://percy.io/ampproject/amphtml/builds/2836662

@zhouyx, can we skip this test if the fix is not straighforward?

/cc @danielrozenberg

**Comment by rsimha** [comment]
Bumping this to P1 since it's causing numerous PR checks to fail, and requires manual approval of all failing Percy builds.

**Comment by zhouyx** [comment]
I wonder if it is a race condition between the screenshot time and the image load time. One thing we can try is to wait for the layout complete of the `<amp-img>` component. Let me find if there's a good css class for that. @jridgewell do you know. Thanks

**Comment by zhouyx** [comment]
Also feel free to skip the test for now if it is blocking many PRs.

**Comment by rsimha** [comment]
I've noticed that this flake has reared its head a couple of times this week. Can we skip this until a better CSS class is available?

/cc @calebcordry, who is this week's build cop.

**Comment by danielrozenberg** [comment]
@zhouyx @micajuine-ho any progress on this?

**Comment by zhouyx** [comment]
I believe we can remove all the visual tests here now that we have added e2e tests? @micajuine-ho what do you think? Thanks.

**Comment by micajuine-ho** [comment]
Yes, I will make sure that visual tests have been fully migrated to e2e tests.
