### ISSUE TITLE
STAMP: Previous page animation seems off

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#25118]
## What's the issue?

Animation seems to be flying too far to the left for previous page

## How do we reproduce the issue?

Opt into canary. Visit any desktop site using the 3 panel view eg https://www.vice.com/ampstories/best-places-to-drink-in-new-york-city/index.html

## What browsers are affected?

Latest Chrome at least

## Which AMP version is affected?
Latest canary

**Comment by newmuis** [comment]
Is this only visible in the canary?

**Comment by calebcordry** [comment]
As far as I can tell, yes.

**Comment by Enriqe** [comment]
I'm able to repro with version `1910161528000`, taking a look.
