### ISSUE TITLE
Validator: 'allowfullscreen' is an invalid sandbox flag 

### ISSUE THREAD

**Issue by ott-fogliata** [ampproject/amphtml#2511]
## amp-iframe | 'allowfullscreen' is an invalid sandbox flag 

When I put allowfullscreen in the sandbox attribute, the console shows this 
"Error while parsing the 'sandbox' attribute: 'allowfullscreen' is an invalid sandbox flag".

Moreover, it seems that a videoplayer (like jwplayer) in a amp-iframe, in fullscreen mode, fills iframe area (not the entire page)

Thanks 
- Ott.

**Comment by dvoytenko** [comment]
/to @Gregable 

Is `allowfullscreen` a valid sandbox flag? I don't remember ever seeing it. I believe it's only the iframe element attribute.

**Comment by ott-fogliata** [comment]
I have seen "allowfullscreen" flag in https://ampbyexample.com/components/amp-iframe/

**Comment by dvoytenko** [comment]
I believe this is an error in the example. /cc @sebastianbenz

**Comment by sebastianbenz** [comment]
Yup - forgot to remove it. Fixed it: https://github.com/ampproject/amp-by-example/pull/71

**Comment by Gregable** [comment]
@dvoytenko , we currently allow any value for the `sandbox` attribute in the `amp-iframe` tag. We should probably sort out the full list of allowable values and improve our errors here at some point down the line.

**Comment by dvoytenko** [comment]
@Gregable This was identified as a documentation/examples issue. No changes needed from validator side, but it's always good to confirm that we support all `sandbox` values :)
