### ISSUE TITLE
amp-bind doesn't work in <amp-script /> 

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#25126]
To whom it may concerned:

I try to bind some data through AMP.setState inside <amp-sctipt />. But looks like it can't works well. Does amp-bind not support in `<amp-script />` ?

Here comes my code:

```html
<amp-script width="300" height="100" script="local-script">
  <p [text]="status.cat">cat name</p>
</amp-script>
<script type="text/plain" target="amp-script" id="local-script">
  const node = document.createElement('p');
  node.classList.add('amp-script-node');
  node.appendChild(document.createTextNode('Show me the money.'));
  document.body.appendChild(node);

  localStorage.setItem('myCat', 'shadow');
  const cat = localStorage.getItem('myCat');

  console.log('cat',cat);

  AMP.setState({
    status:{
      cat
    }
  });
</script>
``` 

Looks like it can not mutate immediately. I try to do some AMP.setState with user tap action and the [text] will mutate. 

Is this an issue or amp-bind with mutation is set high-trust level ?

Paul

**Comment by mattwomple** [comment]
This appears to be reported here: https://github.com/ampproject/amphtml/issues/24862
Does that bug report match what you're describing here?

**Comment by meistudioli** [comment]
hi, @mattwomple 

Ya, looks the same issue. So it will be fixed in future ?

**Comment by mattwomple** [comment]
I don't have any more information than what's written in that report, but since it is already reported and acknowledged by AMP project members, would you mind closing this report and following that one? Thanks!

**Comment by meistudioli** [comment]
@mattwomple 

Sure. thanks.
