### ISSUE TITLE
Programatically set the active story page in an AMP Story.

### ISSUE THREAD

**Issue by agaktr** [ampproject/amphtml#25127]
AMP Stories should have a feature that you can set the active page in an AMP Story document.

The reason:

Lets say a user visits our Story that has 10 pages and goes until the 5th page and then leaves.

We track that the user left on the 5th page and the other(6-10) are unseen.

When the user returns to the Story, the Story should start from the 6th page and not the 1st one.

Pretty much like Facebook and Instagram does.

**Comment by gmajoulet** [comment]
You can either:

Add a `#page=<amp-story-page.ID>` parameter to the Story URL, or use the `selectPage` viewer message:
https://github.com/ampproject/amphtml/blob/8f0446b4d13880bc8f0ee38fb2d729ee96c94dc8/extensions/amp-story/1.0/amp-story.js#L808
