### ISSUE TITLE
Fix carousel amp-by-example image dimensions stretch

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#2513]
In the [carousel amp-by-example](https://ampbyexample.com/components/amp-carousel/), the images in the carousel should have a 4x3 aspect ratio, but are getting stretched vertically to fit the 4x3.5 carousel

May be as simple as setting the carousel dimensions to 400x300 for this one case, but the carousel extension itself may need tweaking so images don't stretch to the carousel dimensions

cc/ @dvoytenko

**Comment by sebastianbenz** [comment]
Thanks Eric! I fixed the sample.
