### ISSUE TITLE
Link at bottom of carousel amp-by-example page is 404'ing

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#2514]
Hey Sebastian, the [link](https://ampbyexample.com/Advanced/Image_Galleries_with_amp-carousel/) at the bottom of the [carousel amp-by-example page ](https://ampbyexample.com/components/amp-carousel/) is 404'ing this morning. Are you the right person to look into this?

**Comment by sebastianbenz** [comment]
Thanks. It's fixed. Feel free to create these issues directly in the amp-by-example project.

**Comment by ericlindley-g** [comment]
Thanks! And sorry about that—will put it in amp-by-example directly next time
