### ISSUE TITLE
Proposal: Alias `amp-list` to `amp-fetch` or something similar

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#25159]
Being at a roadshow, and watching people learn about/use `amp-list`, a recurring question is "Why is this called amp-list?" I'm guessing the name originated from the "intended" use case of displaying a list of results from a JSON payload, but now in our roadshow presentations, tutorials, and guides, we are showing examples where `amp-list` is used to fetch a single property. It seems like it would make sense to alias this (and possibly raise warnings for using `amp-list`). Thoughts?

/cc @wassgha @erwinmombay

**Comment by mattwomple** [comment]
My 2 cents, `amp-list` is still appropriate. It ultimately is listings results, even if just one, and you get some control over formatting. A more generic name like `amp-fetch` could cause backlash from users who expect more freedom to create a `request` handle a `response`. Aliases, in general, seem like a good way to introduce confusion to the user base, so I'd be hesitant to add them.

**Comment by cathyxz** [comment]
Related: https://github.com/ampproject/amphtml/issues/23587
