### ISSUE TITLE
Safari 13: Viewer query params cause document.referrer downgrade

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#25179]
Avoids `Document.referrer` downgrade due to harmless viewer query params like `amp_js_v` and `usqp`.

/cc @ampproject/wg-analytics

**Comment by choumx** [comment]
Removing query params from the viewer iframe works, but they remain missing on back navigation in some cases. Missing query params affects some AMP functionality e.g. `QUERY_PARAM()` URL variable replacement. 

I also did a quick code search for `parseQueryString()` and `location.search` and found the following usages:

```
extensions/amp-access-scroll/0.1/scroll-impl.js
extensions/amp-access/0.1/amp-login-done-dialog.js
extensions/amp-ad-network-adsense-impl/0.1/amp-ad-network-adsense-impl.js
extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js
extensions/amp-analytics/0.1/linker-reader.js
src/impression.js
src/mode.js
src/service/document-info-impl.js
src/service/url-replacements-impl.js
src/service/viewer-impl.js
src/url.js
```

One solution that was suggested is to store the query params in memory before removal e.g. fix the above usages. 

A simpler solution is to just restore the query params to the viewer iframe after the navigation event -- either on `pageshow` event when back navigation triggers the page cache (bfcache) or on next event loop for `_blank` navigation.

**Comment by zhouyx** [comment]
🎉 Woohoo! Thank you @choumx 

cc @zikas
