### ISSUE TITLE
amphtml-validator returns this.sandbox.amp.validator.categorizeError is not a function

### ISSUE THREAD

**Issue by anuragphadke** [ampproject/amphtml#25188]
##What's the issue?
Running amphtml-validator via command line returns 
```
this.sandbox.amp.validator.categorizeError is not a function
```
## How do we reproduce the issue?

1. install the latest amphtml-validator package from 
2. run 
amphtml-validator file.html  #this file is attached as file.zip in this ticket.
[file.html.zip](https://github.com/ampproject/amphtml/files/3753810/file.html.zip)
returns:
this.sandbox.amp.validator.categorizeError is not a function

## What browsers are affected?
amphtml-validator via command line is affected

**Comment by Sevenaka** [comment]
same problem, is there a solution?

**Comment by joselcc** [comment]
it seems we need to upgrade to the latest version https://github.com/ampproject/amphtml/commit/7d7b8d6d0ef7767a2b319c7fbd1959dffbc8931e#diff-5185ebf96af6c84dd9d0f25168752664L279

**Comment by anuragphadke** [comment]
Tried on 1.0.26 which is the latest and was released 3 days ago, same error.

**Comment by joselcc** [comment]
yeah, I still see the old code in `v1.0.26`, I think they meant to publish `v1.0.25`

**Comment by jackbillstrom** [comment]
Man this is really putting me in a bad position, how the f*ck did they manage to do this....

**Comment by Jeiwan** [comment]
I'm using version `1.0.21` and it's also broken, but it worked a few hours ago.

**Comment by kevva** [comment]
It's broken because `amphtml-validator` tries to run https://cdn.ampproject.org/v0/validator.js which doesn't contain the said function anymore.

**Comment by joselcc** [comment]
all `amphtml-validator` versions use what is published in `https://cdn.ampproject.org/v0/validator.js`, `categorizeError` was [removed here from the validator engine](https://github.com/ampproject/amphtml/commit/7d7b8d6d0ef7767a2b319c7fbd1959dffbc8931e#diff-52a1cb778626c52da13d91b4849462d6L6283)

**Comment by jackbillstrom** [comment]
Oh I am going mental over this... And I'll sure love some answers from whos responsible.
Removed him/her as a contributor, I'd be in love.

How did this occur?

1. Worthless employee ?
2. Script Kiddie on his first "The internship" days ?
3. Just someone who thought it shouldn't be there ?
4. Removed of the function was planned ?


I'd love it Nuxt.js wasn't so dependant on it.

**Comment by kevva** [comment]
@jackbillstrom, that's not productive at all. You can still remove the line locally for `amphtml-validator` in your `node_modules` folder, that's what I did until they fix it.

**Comment by liorbashan** [comment]
@kevva , Can you give more details as for what changes can be done locally in node_modules until (or if) they fix this?

**Comment by jackbillstrom** [comment]
@kevva Productive or not, **I couldn't understand on to get passed this bug**. Of course I then come with some hard-on questions.

Thus, as you say, bugs **always occur** but this was just so annoying.

Thanks. :smiling_imp:

**Comment by kevva** [comment]
@liorbashan, in `node_modules/amphtml-validator/index.js` on line `279` or something like that.

**Comment by liorbashan** [comment]
@kevva , Thank you :)
This is obviously a temporary solution.
Still wondering why would they remove the error documentations from this service, since it was really useful. (more useful than amp.dev documentations :))

**Comment by sakinee** [comment]
videolar için amp cache dügün çıkması yönünde ne yapılabilir bazı videoların ölçekleri amp de düzgün çalışmıyor.
Örneğin ; https://pornoyakala.com/amp/   bu raya gidrdinmi boyut büyük 16/9 olmuyor neden ?

**Comment by cpapazian** [comment]
> all `amphtml-validator` versions use what is published in `https://cdn.ampproject.org/v0/validator.js`, `categorizeError` method was [removed here from the validator engine](https://github.com/ampproject/amphtml/commit/7d7b8d6d0ef7767a2b319c7fbd1959dffbc8931e#diff-52a1cb778626c52da13d91b4849462d6L6283)

that is unfortunate. there really should be a way to run validation while only depending on local code. filed https://github.com/ampproject/amphtml/issues/25200 to track this.

**Comment by nainar** [comment]
@jackbillstrom your comments above are violating AMP's [Code of Conduct](https://github.com/ampproject/meta/blob/master/CODE_OF_CONDUCT.md) which aim to promote civil discourse on all AMP channels.

Please ensure that all future comments follow the Code of Conduct. We understand that the current situation is upsetting, however, personally attacking any of our other members is not.

**Comment by amaltas** [comment]
Validator error categories and all the references to amp.validator.categorizeError were removed https://github.com/ampproject/amphtml/pull/25134  validator rollup.

Publishing a updated amphtml-validator npm package now.

**Comment by amaltas** [comment]
amphtml-validator version 1.0.27 published. Please update the amphtml-validator dependencies to use latest version.

In future, we will make sure any changes in validator.js do not break nodejs package and/or get caught during the release.

Please reopen the issue if you still see the error, or I missed something. PS: This is my first npm publish.

**Comment by twifkak** [comment]
Fix for that is pending in #25208.

**Comment by twifkak** [comment]
Fix published as https://www.npmjs.com/package/amphtml-validator version 1.0.28.

**Comment by dmouse** [comment]
any plans to support node 8.x? Next.js use it zeit/next.js#9172

**Comment by rodolphonetto** [comment]
Maybe I'm not so much smart.. but even after updating the package to 1.0.28 I'm still facing the same error... I use it as dependency of next.js amp pages.

**Comment by Timer** [comment]
@rodolphonetto Don't worry! This is still broken despite this issue being closed. We're trying to work with the AMP team on a resolution that doesn't leave all users with broken!

**Comment by rodolphonetto** [comment]
Ahh ok! I thought version 1.0.28 solved all problems, Where can I watch to be updated about that problem?

**Comment by honeybadgerdontcare** [comment]
@rodolphonetto @Timer Sorry you're still experiencing issues around this change. We're working on addressing them. Could you verify that this is happening with `1.0.28`?

**Comment by cpapazian** [comment]
> @rodolphonetto @Timer Sorry you're still experiencing issues around this change. We're working on addressing them. Could you verify that this is happening with `1.0.28`?

@honeybadgerdontcare `1.0.28` moves the minimum node version to 10, so it is still broken on 8, or any other previous versions.

**Comment by rodolphonetto** [comment]
> @rodolphonetto @Timer Sorry you're still experiencing issues around this change. We're working on addressing them. Could you verify that this is happening with `1.0.28`?

There is no problem, I can wait :) 

Yes, I'm still facing the same issue with version 1.0.28, my node version is 12.10.0

**Comment by Gregable** [comment]
All interfaces should be returning errors/warnings now. This includes previous versions of NPM (sync back to 1.0.23 if you have node compatibility issues).

Note that all errors are categorized as UNKNOWN. The error category system has retired. For some history, this system categorized all errors into an set of 10 broad enums like "GENERIC" and "AUTHOR_STYLESHEET_PROBLEM". Note that category is distinct from severity, which is of the set ERROR/WARNING. Severity is still present and unchanged. There was little if any remaining usage of these categories. Google Search console was one of the remaining users, but no longer consumes categories. Any older version of the validator that still consumes categories will now categorize all errors as UNKNOWN. We'll follow up with fixes to those interfaces to ensure they remove references to categories as well.

**Comment by Gregable** [comment]
For browser interfaces you may need to force reload https://cdn.ampproject.org/v0/validator.js

**Comment by Timer** [comment]
Thank you for the detailed explanation, distinction between severity and category, and the fix @Gregable et al.

**Comment by rodolphonetto** [comment]
All working fine right now, thank you so much :)

**Comment by Gregable** [comment]
FYI as a follow up, the release process for `cdn.ampproject.org/v0/validator.js` now includes an automated step that runs light verification tests against the latest amphtml-validator NPM version. This would have caught the specific release failure mentioned in this github issue.

This step would not have caught the separate issue with removing support for older Node versions, but that was an explicit decision rather than an unintended bug, which isn't really what tests are there to catch. The consequences of that decision were not fully understood, but I think we understand them better now.
