### ISSUE TITLE
amphtml-validator: avoid breaking API changes in patch releases

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#25189]
The latest amphtml-validator npm release `1.0.26` upgraded the required node version from 10 to 12 which is a breaking API change. We should only do these by also increasing the major version to avoid breaking downstream clients.

**Comment by estherkim** [comment]
@sebastianbenz, agreed with the intent. However the node upgrade hasn't been published yet; it's misleading but `1.0.26` was released on [18 Oct](https://www.npmjs.com/package/amphtml-validator/v/1.0.26) while node was upgraded on [21 Oct](https://github.com/ampproject/amphtml/pull/25161/commits/505f23df75b2f9853138020e85f9c9e1bd4ad7fb).

**Comment by honeybadgerdontcare** [comment]
Resolved via #25208
