### ISSUE TITLE
[amp-auto-ads] No ad placements found for publisher ID

### ISSUE THREAD

**Issue by indiandragon** [ampproject/amphtml#25194]
## What's the issue?

With correct publisher ID, [amp-auto-ads] for Adsense doesn't show Ads and throws the following warning in the console,

[amp-auto-ads] No ad placements found for publisher ID 'ca-pub-XXXXXXXXXXXXXXXX'. Check that the provided publisher ID is correct.

Note: Publisher ID is masked in the above warning.

The site has been validated for AMP standards, there are no other warnings or errors. Normal Adsense Auto Ads with the same publisher ID was working before in a non AMP site, AMP-AUTO-ADS on an AMP site throw this error. The website is AMP only with canonical url pointing to the same permalink.

## How do we reproduce the issue?
Implementing amp-auto-ads for Adsense in a AMP website.

## What browsers are affected?

All browsers.

## Which AMP version is affected?

This seems to be occurring for quite a while as there are similar issues reported at Google Adsense community forums [[1](https://support.google.com/adsense/thread/10337359?hl=en)][[2](https://support.google.com/adsense/thread/11951902?hl=en)]. Some say it gets resolved in a week or two[[3](https://support.google.com/adsense/forum/AAAAKDuOfxQbI09ZBkGINo/?hl=en&gpf=%23!topic%2Fadsense%2FbI09ZBkGINo%3Bcontext-place%3Dtopicsearchin%2Fadsense%2Fcategory%243Atechnical-errorsbugs%257Csort%3Arelevance%257Cspell%3Afalse)].

**Comment by markbiernat** [comment]
I am experiencing similar issues. AMP Auto Ads are not working.
I am using Wordpress Twenty-Twenty theme with only Jetpack and Akismet and AMP as plugins. 
With AMP-activated -  no Ads show.
With AMP-deactivated - Ads show.

**Comment by eduardogoncalves** [comment]
same as #25845

**Comment by chojnicki** [comment]
Same here

**Comment by levyblue** [comment]
Also experiencing it with my side.

**Comment by takien** [comment]
Any fix for this problem?

**Comment by lannka** [comment]
dup of  #25845

**Comment by AlexMnrs** [comment]
Same here

**Comment by nvFede** [comment]
Same Issue here, do you guys find a way to solve this ?

**Comment by eduardogoncalves** [comment]
@nvFede, please follow this issue here #25845

**Comment by sevakram** [comment]
I had similar issue on my AMP only website [Marketsetup.in](https://marketsetup.in)

I observed some of the other AMP websites where Auto ads are working. Adding `amp-ad` custom element seems to have resolved the issue for me.

So now the final code looks like - 

```html
<script async custom-element="amp-ad" src="https://cdn.ampproject.org/v0/amp-ad-0.1.js"></script>
<!-- Amp Ads -->
<script async custom-element="amp-auto-ads" src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js"></script>
<!-- Auto Ads -->
<script async custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>
```

Hope this helps everyone.

**Comment by DrLightman** [comment]
@sevakram 
> ```
> 
> <script async custom-element="amp-ad" src="https://cdn.ampproject.org/v0/amp-ad-0.1.js"></script>
> 
> <script async custom-element="amp-auto-ads" src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js"></script>
> ```
> 
> Hope this helps everyone.

It doesn't work.

**Comment by netnaps** [comment]
@sevakram Doesn't Work for me as well, I have seen adding `<p>` blank tags it picks up but takes at least one week.
Usually, in the posts, we don't have any Anchor elements, the ads require.
