### ISSUE TITLE
amphtml-validator command line tool and npm module should not call production

### ISSUE THREAD

**Issue by cpapazian** [ampproject/amphtml#25200]
amphtml-validator command line tool and npm module (https://www.npmjs.com/package/amphtml-validator) have a dependency on https://cdn.ampproject.org/v0/validator.js, which means this breaks unexpectedly. at the very least, there should be an option to disable the dependency on the production validator and only depend on local code.

**Comment by Gregable** [comment]
There is:

```
$ amphtml-validator --validator_js https://cdn.ampproject.org/v0/validator.js foo.html
```

See:

```
$ amphtml-validator --help
```
