### ISSUE TITLE
Use `renovate` to auto-update Node versions in `package.json` files

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#25209]
We've had to periodically update the `engines` section of our `package.json` files each time a new version of Node is released. Sometimes, this breaks Travis builds. And at other times, it breaks tools like `amphtml-validator`.

See https://github.com/ampproject/amphtml/pull/25161#discussion_r337182956 for a discussion on this.

I propose that we configure Renovate to keep the `engines` section in all our `package.json` files up to date. Here are the docs: https://docs.renovatebot.com/node. I think a support policy of `active` should give us what we're looking for.

**Comment by rsimha** [comment]
@estherkim since you just fixed this for amphtml and validator, can I assign this to you?

**Comment by twifkak** [comment]
I suggest `lts` instead of `active`. (Or perhaps `['lts', 'active']` if there's some nuance I'm missing?)

Note that [in the future](https://nodejs.org/en/about/releases/) there will be only a two day overlap between the "active" status of v12 and v14, which would give people insufficient time to upgrade.

**Comment by rcebulko** [comment]
This seems reasonable, especially for minor and patch upgrades

**Comment by rsimha** [comment]
I had a déjà vu moment and realized that we've already attempted this before: See #19218. Not sure if it doesn't work, or if it hasn't had to do anything thus far. Will need to dig into this some more.

**Comment by rsimha** [comment]
And here's the long discussion we had when node version 8 gave way to 10: #19050
