### ISSUE TITLE
Fetching specific RTV numbers during installExtensionForDoc 404s in demo builds

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#25214]
I'm observing that in deployed demos like the PR Deploy Bot and Firebase, extensions that are loaded from other extensions (e.g. `amp-carousel` and `amp-image-viewer` in `amp-lightbox-gallery`, and `amp-loader` and `auto-lightbox` on all articles in extension-helpers.js) are all trying to load from a specific RTV. But on demo builds this tends to 404 because these files aren't present in a specific RTV, they're just present in the dist file, or on the regular path. 

Is there an existing build flag, or something that we can add to make these features work for demo builds? 

Sample repros: 
PR Deploy Bot: https://storage.googleapis.com/amp-test-website-1/amp_dist_65323/examples/article.amp.html
Firebase: https://amp-testing-715cb.firebaseapp.com/examples/article.amp.html

Note that amp-loader and auto-lightbox fail to load. 

This is due to the `installExtensionForDoc` codepath eventually calling the following: 
https://github.com/ampproject/amphtml/blob/b6c4242ace9a3d32f82550a378593527c849a460/src/service/extension-location.js#L56-L71

This hardcodes an RTV number, and is not compatible for demo builds like firebase and PR deploy bot, occasionally problematic for localhost. To fix this, we could either copy over the RTV folder in these scripts, or try to introduce a local build mode that pulls from `dist` instead of a specific rtv folder path. 

Somewhat related: the `version-locking` experiment which forces scripts to be of the same release. It's sometimes useful to turn this off in local development when you're creating partial builds, but otherwise not relevant. 

The question is, aside from demo builds and self-hosted deployments of AMP binaries, is there a legit use case for not having `installExtensionForDoc` load from a specific RTV. Is there benefit to making it load from `dist` instead if `getMode().localDev` returns true?

**Comment by mattwomple** [comment]
@cathyxz - I have two PRs that are relevant to this under review: #25026 and #25028 . The first would resolve the issue of it being necessary to include `{rtv}/rtv/` in the URL for components and the second would allow revising the CDN URL via `<meta>` tags in the document itself. I believe they both require design reviews before moving forward, so this doesn't help in the immediate future; i.e. you may still need to introduce a compatibility solution for now.

**Comment by cathyxz** [comment]
That's awesome. Commented on your PR. This isn't incredibly urgent, and I think your PR will solve this problem, though a minor edit to it might make the solution to this particular problem a lot easier for deploying demos.

**Comment by rsimha** [comment]
_[Infra triage]_ Is this something we'd like to do? If not, can this be closed?
