### ISSUE TITLE
amp-script: 406 (Not Acceptable) error when trying to load javascript from local javascript file.

### ISSUE THREAD

**Issue by avrohit2000** [ampproject/amphtml#25216]
Hello Guys, I have recently started working on AMP. As of now i am not sure if <amp-script> src supports a local javascript file rendering from client. For example i am trying to invoke a local JS as ..\scripts\[javascriptfile].js an it returns 406 error. Could you please see if this scenario handled at amp. We keep updating local JS file once in every two weeks. I have already added content-type attribute as in the screenshot below.

![image](https://user-images.githubusercontent.com/11708742/67385628-56fa1500-f58b-11e9-90b0-36856db4d40f.png)

If any of you feel that this can be solved by adding Accept attribute in header request. Please mention an example with <amp-script> for reference. I verified a sandbox attribute but not exactly that did help me to place in a right attribute.

**Comment by choumx** [comment]
Looks like a local server configuration issue e.g. it doesn't serve the JS file given the `Accept[-*]` headers. Sorry we can't help since this isn't an AMP issue.
