### ISSUE TITLE
Dynamically add RTV Experiment globals to eslint

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#25227]
## Describe the new feature or change to an existing feature you'd like to see

Stemming from https://github.com/ampproject/amphtml/pull/25173#issuecomment-545658237. We can add the RTV Experiment globals individually to the `.eslintrc` file, but then we have to keep them in sync. It'd be better to switch to a `.eslintrc.js` config file, that way we can dynamically generate the allowed globals based on `experiments-config.json`.

## Describe alternatives you've considered

- Maintain the globals in both `.eslintrc` and `experiments-config.json`.
- Continue to comment `// eslint-disable-next-line no-undef`

## Additional context

https://eslint.org/docs/user-guide/configuring

**Comment by danielrozenberg** [comment]
This sounds like a perfect fixit week/GFI task, agree @rsimha?
