### ISSUE TITLE
I2I: Move CSI collection to GCP Monitoring Metrics

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#25228]
## Summary

Move AMP's Client Side Instrumentation collection service to Google Cloud's Monitoring service. This service will collect simple metrics like First Contentful Paint (not PII) so we can determine if a release contains a performance regression.

This I2I is intended allow us to discuss both the GCP implementation, and whether or not we should even be using GCP to collect these metrics.

## Design document

https://docs.google.com/document/d/1FV_kj3jvmB6IOjRMNqgMR63wNMNYsc9ws5wxhKjuzN4/edit

## Motivation

AMP's current CSI collection is through Google's SERP viewer, has a 3 day latency (currently), and the data is restricted to Google employees.

Moving to GCP will allow us to reduce the latency to minutes, and free us from the tight integration with SERP viewer.

### Infrastructure

- [ ] Create `/metrics` App Engine Endpoint
- [ ] Create new data aggregation/pusher cron service

### Runtime

- [ ] Intercept metrics pings, forward to both Viewer and `/metrics`
- [ ] After we have confidence in the new CSI, disable viewer metrics integration

/cc @ampproject/wg-approvers
/cc @cramforce 
/cc @kristoferbaxter

**Comment by choumx** [comment]
Closing since we've decided to go with a smaller fix (with no AMP code changes) to address the latency issue. 

GCP is still an option in the larger effort to externalize AMP's latency metrics however.
