### ISSUE TITLE
Graceful fallback when 3rd party JS is blocked

### ISSUE THREAD

**Issue by k0nserv** [ampproject/amphtml#2524]
Hi,

I've been trying out AMP on my own site and have found it to be great. I like that the `amp-boilerplate` is available to gracefully handle user agents that do not support JS. However when the user agent supports JS but blocks third party JS the fallback does not work because it relies on `<noscript>`. 

I'm wondering if there's a recommended way to gracefully fallback when https://cdn.ampproject.org/v0.js is blocked or fails to load. If no such recommendations exist could it be interesting to consider expanding the current `<noscript>` solution?

Hugo

**Comment by cramforce** [comment]
I don't think there is much we can do. I think https://cdn.ampproject.org/v0/* is a good path to whitelist when one is blocking 3p JS.

**Comment by jridgewell** [comment]
@cramforce: Could we shorten the visible animation to 1s, then alter that back to 8s in JS?

**Comment by cramforce** [comment]
@jridgewell I think we should make it configurable. 3s was definitely under discussion (same as font timeout in most browsers).

**Comment by k0nserv** [comment]
> I don't think there is much we can do. I think https://cdn.ampproject.org/v0/* is a good path to whitelist when one is blocking 3p JS.

While I agree that it would be wise to add it to the whitelist. The fact that AMP already works okay without javascript seems to indicate that this is something you've taken into account and worked to support. It seems reasonable to extend it to handle the case when the script is not loaded at all as well.

Another option is making the script available as a dependency in in some package manager so it can be bundled directly with the site and loaded from the origin instead of a 3rd party cdn.

**Comment by rudygalfi** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues. This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
