### ISSUE TITLE
Intent-to-Deprecate-and-Remove: "duplicate" and "requires usage" in AMP Email format validation

### ISSUE THREAD

**Issue by honeybadgerdontcare** [ampproject/amphtml#25249]
## Summary

In #24854 the validation for the AMP Email format `script` tags was separated from other AMP formats. This allowed for the removing support of `version: latest` and explicitly required a numerical version.

As a result of this separation from other HTML formats, it is not necessary to include `requires_usage: GRANDFATHERED` or `deprecated_allow_duplicates: true` as part of the AMP Email format. Those were included to support the AMP format.

The plan is to let AMP Email providers review this change and upon approval remove `requires_usage: GRANDFATHERED` and `deprecated_allow_duplicates: true` from the validator for the AMP Email format for `amp-accordion`, `amp-fit-text`, and `amp-form`.

## Motivation

These validator features were created for the AMP format and should not be needed for the AMP Email format.

## Impact on existing users

It is unlikely that this will break any AMP Emails.

## Additional context

#24854: removal of `version: latest` and separating of `script` tags
#25246: removal of `version: latest` from `amp-fit-text`

/cc @ampproject/wg-approvers
/cc @ampproject/wg-caching 
/cc @ampproject/wg-amp4email

**Comment by honeybadgerdontcare** [comment]
@ampproject/wg-approvers This has generated zero discussion. Requesting approval from three of you to move forward.

**Comment by choumx** [comment]
Approved.

**Comment by Gregable** [comment]
Approved

**Comment by choumx** [comment]
@ampproject/wg-approvers One more approval?

**Comment by cramforce** [comment]
Approved

**Comment by zhangsu** [comment]
Let's reopened this as I reverted this change internally so it should be merged to GitHub upstream soon too: rationale [here](https://github.com/ampproject/amphtml/pull/29642#issuecomment-672198302).
