### ISSUE TITLE
amp-story: configurable target for amp-story-cta-layer links

### ISSUE THREAD

**Issue by bezoerb** [ampproject/amphtml#25255]
## What's the issue?

All links inside an `amp-story-cta-layer` are currently forced to `target=_blank`.
We use the `amp-story` component on https://www.bmw.com and want to add a link to the next story on the last slide. With this issue in place the user ends up with tons of tabs showing read stories while exploring the page. 
It is necessary that there's a choice between `_top`, `_self` or `_blank`.

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. Open https://output.jsbin.com/mutalos/
2. Navigate to second slide and click the link

## What browsers are affected?

This is not a browser issue. It's an issue with the design decision made ;)
See implementation: https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/1.0/amp-story-cta-layer.js#L66

## Which AMP version is affected?

All

**Comment by bezoerb** [comment]
@newmuis: You requested a use-case in #13775.

**Comment by newmuis** [comment]
You can currently use the bookend (which will navigate within the same frame) for recirculation links at the end of a story.

We are also building a dedicated experience for navigating to the next story after completing one: #24539

**Comment by bezoerb** [comment]
Thanks for the quick answer. We know about the bookend but only putting the links there doesn’t suit the needs of our client. We need a way to place links without the target=_blank in the slides.

**Comment by newmuis** [comment]
Hmm, can you elaborate on what the needs are from a user perspective?  And why, specifically, the bookend and/or the dedicated next story experiences would be insufficient?

**Comment by bezoerb** [comment]
Sorry for the delay, 
we need a way to prominently link to the next story. The bookend feels too cluttered and in addition, there are very limited ways to customize/style. The dedicated next story experiences might work, but they need to be implemented in the first place. After that we could check if it's sufficient. Is there already a planned release date?

**Comment by bezoerb** [comment]
@newmuis: friendly ping :)

**Comment by newmuis** [comment]
There currently no planned release date, but it's likely going to take a few months until it is available.

I'm not certain what specific customization or styling concerns you have around the bookend links, but if you want to have this experience today, that's currently the way forward.

Perhaps this is something that can be raised at the monthly stories working group meeting (we will next meet in early December)?  If you're interested in joining, you can denote your availability [here](https://doodle.com/poll/xdaimkg5yqixxskd). Part of the stories initiative is to provide a consistent interaction model and user experience, while also allowing the flexibility to express your brand visually.

I think the correct way to do this is the next story experience we're developing, but as mentioned, it's not yet ready.  Unfortunately, if we allow changing the target here, we'd have to maintain backwards compatibility even after the next story feature is launched, or deprecate the target customization just months after launching it, neither of which seems ideal.

**Comment by bezoerb** [comment]
Thanks for the quick response :)
We will then go for the bookend alternative for now.
