### ISSUE TITLE
🌸 Cherry-pick request into #25222 (Approved)

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#25258]
# Cherry-pick request

|       Issue       |       PR       | Production?  |     RC?      | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :----------: | :----------: | :-----------------------------------------------------------------------------: |
| #25245  | #25245 | No | Yes |                               #25222                                |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

All AMP pages are broken in IE 11 due to a bug in the Custom Elements polyfill.

# Mini-postmortem

## Summary

The new [Custom Elements v1 polyfill](https://github.com/ampproject/amphtml/blob/ea38284da499ce2bb6b7b67a9b9b4f8ab802bc76/src/polyfills/custom-elements.js) contained a bug that prevented creating custom element instances in IE 11.

| Users affected                                   | Impact                                                                       |
| ------------------------------------------------ | ---------------------------------------------------------------------------- |
| All users of IE11 | Complete break of page, no images, videos, ads, etc. Text would work |

## Root Causes

Custom Elements must extend from the `HTMLElement` class (required by the CE spec). The new polyfill injected a brand new function `HTMLElementPolyfill` as a subclass of `HTMLElement`, and overwrite `window.HTMLElement = HTMLElementPolyfill`. With proper subclasses, the prototype of both the Class' constructor function and the associated prototype must point to the superclass. Meaning, `HTMLElementPolyfill.__proto__ === HTMLElement` and `HTMLElementPolyfill.prototype.__proto__ === HTMLElement.prototype`. This is how subclassing works in ES6 browsers.

When you transpile a subclass, generally, you must have the equivalent of a `super()` call in the subclass constructor. This is usually compiled to `superClass.call(this)` as the ES5 way of doing subclass construction.

In IE11, `HTMLElement` is an exotic host object, and does not extend from the `Function` class. Because it doesn't extend from `Function`, `HTMLElement.call` does not exist (it's defined on `Function` class). So, when we transpiled `super()` to `HTMLElement.call(this)`, we got an error.

## Action Items

| Action Item                   |               Type               |     Owner     |      PR #      |
| ----------------------------- | :------------------------------: | :-----------: | :------------: |
| Add `crossorigin=anonymous` | Mitigate | @jridgewell | #24731 |

## Lessons Learned

- IE11 has a lot of nonstandard behaviors.
- Cross origin errors are not reported without `crossorigin=anonymous` on the scripts

### Things that went well

- Ads metrics drop alerted us to the issue within 24hours

### Things that went wrong

- The error reports were silently dropped by the browser because they originated from a crossorigin script.

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by zhouyx** [comment]
I am the release engineer this week. Let me know when this is ready.

**Comment by jridgewell** [comment]
PR is already merged, we just need cherry-pick approval.

**Comment by dvoytenko** [comment]
Approved

**Comment by cramforce** [comment]
Approved

**Comment by zhouyx** [comment]
Cherry-pick to canary and RC completed. Assign back to @jridgewell for postmortem

**Comment by jridgewell** [comment]
Postmortem published, closing.

**Comment by choumx** [comment]
@jridgewell Is a regression test we can add or opt-in for IE for CE registration?

**Comment by jridgewell** [comment]
Integration tests would be all that's necessary, if we enabled them.

**Comment by choumx** [comment]
Yea, enabling something trivial on IE (e.g. single `amp-img` integration test) will do.
