### ISSUE TITLE
AMP Cache update stopped working

### ISSUE THREAD

**Issue by seomaz** [ampproject/amphtml#25264]
The Update AMP content ([link](https://developers.google.com/amp/cache/update-cache#use-update-cache)) it seems to stop working.

Calls to update the cache return OK, but the content is not updated.

The example: 

**AMP URL**: [link](https://www.cibercuba.com/videos/deportes/2019-10-27-u1-e196568-s27066-historico-onel-hernandez-convierte-primer-futbolista)

**AMP Cache URL**: [link](https://www-cibercuba-com.cdn.ampproject.org/c/s/www.cibercuba.com/videos/deportes/2019-10-27-u1-e196568-s27066-historico-onel-hernandez-convierte-primer-futbolista)

The AMP URL was updated several times and the AMP Cache URL was update via update-cache method with OK result (see screenshot) the request: 

<img width="1812" alt="Captura de pantalla 2019-10-26 a las 11 59 02" src="https://user-images.githubusercontent.com/5072690/67617950-d6385480-f7e8-11e9-9f0a-579676b2b255.png">

`https://www-cibercuba-com.cdn.ampproject.org/update-cache/c/s/www.cibercuba.com/videos/deportes/2019-10-27-u1-e196568-s27066-historico-onel-hernandez-convierte-primer-futbolista?amp_action=flush&amp_ts=1572254987&amp_url_signature=ZylmpVj-0FbFpFBtEwQGvV0pUUq279UcX5veihTEHY6lw3jVIzw8onMpEThrYatSFReHCeBxpgkTp3--phPfKFs6crp0jho-NSmzkwSE9qUNXAlVeq3hSUrNhb6hQIDbawiFLOdQ2l3KfcUoOF7xZ9xnwGVOvgLOQRWb8VycXSIWx1P48kHQNZgxsvjlxGHQyRsKUhknoDoiFcSC9newI0JsDvkq_IKDPK8SQSvsXcblGqNyqSjB3-XmmFw97pkmePmHmCg_SdjLEj0udWMb5q72GJJ7wCaEzsEOI3gr63NLxnagDGU9k1jfkpIKtGjah5DkIc-3zuzTFuC_o4Lnnw`

But the cache was not updated correctly, you can compare the contents of both urls by searching for ".."

Since yesterday I tried with different URL obtaining the same result: **the AMP URL cache is not updated**

**Comment by kristoferbaxter** [comment]
Closing in favor of #31794.
