### ISSUE TITLE
Fallback url for <amp-state> without user-activated reloading

### ISSUE THREAD

**Issue by mumpo** [ampproject/amphtml#25273]
When retrieving data from an API in `<amp-state>`, there are some cases in which you have a fallback JSON in case the request fails to retrieve data. In these cases currently the only option to fetch again the data is showing a button (e.g. inside an `<amp-list>` fallback) that changes the `src` binding of the `<amp-state>` to the fallback url.

It would be nice to have an alternative way to provide a fallback url in `<amp-state>`.

A possible solution would be this:
```html
<amp-state
    id="data"
    src="my-domain.com/api"
    fallback-src="my-domain.com/fallback.json"
></amp-state> 
```

**Comment by choumx** [comment]
Interesting FR, but what will be the fallback for `fallback-src`? :) I think this fallback behavior should be done on the `my-domain.com/api` endpoint.

Note that `amp-state` already supports a local, in-page fallback (JSON in child script element).
