### ISSUE TITLE
The attribute 'type' may not appear in tag 'ol'.

### ISSUE THREAD

**Issue by eduardozulian** [ampproject/amphtml#2528]
AMP Version: 1456954860788

The `The attribute 'type' may not appear in tag 'ol'` validation error occurs, however `type` attribute is no longer deprecated: https://www.w3.org/TR/html-markup/ol.html#ol.attrs.type

**Comment by dvoytenko** [comment]
@Gregable `ol[type]` is no longer deprecated, so let's support it.

**Comment by Gregable** [comment]
I picked this one up on my last sweep of HTML5 attributes along with `start` and `reversed`, so we'll have it available in a later release. Thanks for the report though, HTML is definitely a large language so these reports are very helpful in catching all issues.

**Comment by eduardozulian** [comment]
Thanks! :facepunch:
