### ISSUE TITLE
amp-img fails to load images with space in their path

### ISSUE THREAD

**Issue by weeblr** [ampproject/amphtml#2529]
## Short description of your issue:

Some users have images with spaces in their path, ie `<img src="/images/admins/FirstName LastName.jpg" ...`

In the AMP version, this gets converted to:
`<amp-img src="/images/admins/FirstName LastName.jpg..."`

Though the space is absolutely invalid per RFC and should be either URL encoded or escaped, this happens often with user generated content, and browsers accept those images and display them fine (in img tags).
Not so with amp-img, and the images are missing on the AMP pages.

## How do we reproduce the issue?

Any document with an amp-img tag and src has a space in file name should trigger that.

## What browsers are affected?

Tested on latest IE11, FF and Chrome (desktop and mobile for Chrome): they all behave the same, showing the image with img tag but not with amp-img

## Which AMP version is affected?

currently happening.

## Question

What do you think? should the AMP run-time URL encode? 

Rgds

**Comment by cramforce** [comment]
@dvoytenko this is likely because the `srcset` code runs on the `src`, right? I think it would be very reasonable to not do that. Would also save some CPU. I think otherwise this is, of course, an invalid URL. URLs cannot contain spaces.

**Comment by weeblr** [comment]
Hi
Great to see things moving forward like this ;)
Will this be available soon?

**Comment by dvoytenko** [comment]
I believe we missed today's canary, so it will go out next Thursday to canary.

**Comment by dvoytenko** [comment]
It will be in canary today. We'd really appreciate if you check it in canary in a couple of hours.
