### ISSUE TITLE
Add support for CONSENT_STRING in fast fetch configuration for amp-ad-network-doubleclick-

### ISSUE THREAD

**Issue by jdelhommeau** [ampproject/amphtml#25302]
This is more of a question than an actual feature request (although it may result in a feature request depending on the answer).

AMP recently added support for amp-consent to support passing consent string as per the IAB TCF framework (https://github.com/ampproject/amphtml/blob/master/ads/README.md#amp-consent-integration).

Didomi already built support for it with their CMP. However, I am still unsure how it will work.
For example, appnexus prebid server added the "CONSENT_STRING" macro in their RTC call in callout-vendors.js file (https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/0.1/callout-vendors.js).

However, the macro is not replaced at call time, even though the didomi CMP is on page.

Reading a bit more through the fast fetch doc, and specifically, the macro substitution, it seems for the CONSENT_STRING macro to be replaced at load time in the RTC config, the AmpAdNetworkAmpAdComImpl from the publisher using the RTC config must implement it as part of getCustomRealTimeConfigMacros.

So in case publisher is using the doubleclick amp-ad, it means for the CONSENT_STRING macro to be replaced in real time by the actual consent string from the didomi CMP, it requires doubleclick amp-ad to implement this additional macro. So something like this:

{code}
/** @override */
  getCustomRealTimeConfigMacros_() {
    /**
     * This whitelist allow attributes on the amp-ad element to be used as
     * macros for constructing the RTC URL. Add attributes here, in lowercase,
     * to make them available.
     */
    const whitelist = {
      'height': true,
      'width': true,
      'data-slot': true,
      'data-multi-size': true,
      'data-multi-size-validation': true,
      'data-override-width': true,
      'data-override-height': true,
    };
    return {
      CONSENT_STRING : () =>[CODE TO RETRIEVE CONSENT STRING USING AMP-CONSENT API],
      PAGEVIEWID: () => Services.documentInfoForDoc(this.element).pageViewId,
      HREF: () => this.win.location.href,
      REFERRER: opt_timeout => this.getReferrer_(opt_timeout),
      TGT: () =>
        JSON.stringify(
          (tryParseJson(this.element.getAttribute('json')) || {})['targeting']
        ),
      ADCID: opt_timeout =>
        getOrCreateAdCid(
          this.getAmpDoc(),
          'AMP_ECID_GOOGLE',
          '_ga',
          parseInt(opt_timeout, 10)
        ),
      ATTR: name => {
        if (!whitelist[name.toLowerCase()]) {
          dev().warn('TAG', `Invalid attribute ${name}`);
        } else {
          return this.element.getAttribute(name);
        }
      },
      CANONICAL_URL: () =>
        Services.documentInfoForDoc(this.element).canonicalUrl,
    };
  }
{code}

Is that correct? Or am I misunderstanding how the far fetch system works?

Thank you very much for your help.

cc @mkendall07

**Comment by jawadst** [comment]
@zhouyx @torch2424 @jasti 
We are discussing with a few supply sources/vendors using RTC and CONSENT_STRING/CONSENT_STATE macros seem to be the last missing pieces for them to be able to collect/leverage the consent string passed by the CMP.

Would be great to see this added to your roadmap!

**Comment by zhouyx** [comment]
Hello @jawadst and @jdelhommeau. The CONSENT_STRING/CONSENT_STATE macros are already supported in the RTC request. https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/rtc-documentation.md#url-macro-substitution

https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/0.1/real-time-config-manager.js#L275

Let me know if that works. Thanks.

**Comment by jdelhommeau** [comment]
thank you @zhouyx for your answer. I am not sure this code is enough for RTC to support the consent string macro. At least on my tests pages, this is not working (CONSENT_STRING remains empty despite CMP and CONSENT_STRING being generated on page).

Looking at the code you sent, it seems the consent string that RTC tries to initialize must be passed as part of the `maybeExecuteRealTimeConfig` method, as per code here:

> maybeExecuteRealTimeConfig(customMacros, consentState, consentString) {
>    if (!this.validateRtcConfig_(this.a4aElement_.element)) {
>      return;
>    }
>    this.consentState_ = consentState;
>    this.consentString_ = consentString;
>    this.modifyRtcConfigForConsentStateSettings();
>    customMacros = this.assignMacros(customMacros);
>    this.rtcStartTime_ = Date.now();
>    this.handleRtcForCustomUrls(customMacros);
>    this.handleRtcForVendorUrls(customMacros);
>   return Promise.all(this.promiseArray_);
>  }

But then I am not sure who is going to pass the CONSENT_STRING value in this call.

Seems to me that:
 * didomi did the code to generate consent string on page
 * some RTC vendors (such as PBS) did the work to use CONSENT_STRING
 * but nobody did the work in between to enable communication between the two.

Do you have a working test page, with a didomi CMP on, and a RTC call being made with the generated consent string?

**Comment by zhouyx** [comment]
Hello @jdelhommeau 

The communication between the two is done by the AMP runtime. and through the `#getConsentPolicyInfo()` API. 

I don't have a working test page. I haven't worked with a RTC example before. Do you maybe have an example that I can take a look. Thanks

**Comment by jdelhommeau** [comment]
@zhouyx thank you for additional details. I only have a test page running on local server, so nothing I can share with you directly. But you can find the code below to use as test page localy on your side.

It loads the didomi CMP, which should be exposing the consent string in the `getConsentPolicyInfo()` API as well as a RTC call to prebid server, but the CONSENT_STRING isn't set (it remains empty):

`<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>AST AMP Tag - Multiple</title>
		<link rel="canonical" href="http://nonblocking.io/" >
		<meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
		<style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
		<script async src="https://cdn.ampproject.org/v0.js"></script>

		<script async custom-element="amp-consent" src="https://cdn.ampproject.org/v0/amp-consent-0.1.js"></script>
	</head>
	<body>
		<div>
			<amp-consent id="didomi"  type="didomi">
			<script type="application/json">{"clientConfig": {"gdprAppliesGlobally": true, "config": {"app": {"apiKey": "7dd8ec4e-746c-455e-a610-99121b4148df"}}}}</script>
			</amp-consent>
		</div>

		<div id="apn_ad_1">
		<amp-ad
                                layout="responsive"
                                width="320"
                                height="50"
                                type='doubleclick'
                                data-slot="/3048/d.thesun.amp/uknews"
                                json='{"targeting":{"platform":"amp","AMP":"true","tagForChildDirectedTreatment":1,"section":"3048%2Fd.thesun.amp%2Fuknews","admantx_ents":null,"admantx_emotion":null,"admantx_cat":null,"admantx_bs":null,"path":"https:\/\/www.thesun.co.uk\/news\/uknews\/9980859\/uk-weather-forecast-met-office-rain-drench-flood-thunder\/","sec_id":327,"cont_type":"art","kw":"uk%2Cweather%2Cforecast%2Cmet%2Coffice%2Cissues%2Cmore%2Csevere%2Cwarnings%2Cas%2Ctorrential%2Cshowers%2Cdrench%2Cbritain%2Cwith%2Cflash%2Cfloods%2Call%2Cweek%2Cclaudia%2Caoraha%2Cgoodbye%2Csummer%2Cuknews","slug":"","topics":"","om_v_id":"null","om_ses_id":"null","om_s_id":"null","mpu":1,"eid":"null","ppid":"null","aid":9980859,"vid":"null","search":"null","article_type":"post","viewport":"null","refresh":false,"C":"null","A":"null","G":"null","P":"null","pos":"header"}}'
                                rtc-config='{"vendors":{"prebidappnexus":{"PLACEMENT_ID":"13245218"}}}'>
                        </amp-ad>
	
		</div>
	</body>
</html>`

**Comment by jawadst** [comment]
@zhouyx 
Thanks for your explanations. We are indeed able to see the CONSENT_STRING macro correctly replaced in RTC calls now. We might have some inconsistent state in the CONSENT_STATE status sent back by Didomi to AMP that could explain why @jdelhommeau wasn't able to see the consent string there so we are working on that on our side.

**Comment by jawadst** [comment]
@zhouyx @jdelhommeau 
After doing some more testing, I think the missing piece is that one must add `<meta name="amp-consent-blocking" content="amp-ad">` to the page for the consent string to be effectively replaced in RTC calls. Simply adding `<meta name="amp-consent-blocking" content="">` is not enough: the consent string is never replaced in that case.

Do you have a sense of why that is the case? Is that the expected behavior?

My understanding is that that is an issue as it prevents publishers from loading ads before consent is collected as `amp-ad` tags would not be loaded until consent is given (whether positive or negative). That is the most standard setup for regular web and definitely something publishers want as a configuration option.  
The `sendRegardlessOfConsentState` does not seem to change that: RTC calls are only sent after consent is collected.

I am attaching two example pages with the `prebidappnexus` RTC vendor and the Didomi CMP configured:

- test_pbs_CMP_with_amp_ad_blocking: with `amp-ad` tags blocked, the CONSENT_STRING macro is correctly replaced (look for requests to prebid.adnxs.com -> https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/0.1/callout-vendors.js#L61)
- test_pbs_CMP_without_amp_ad_blocking: without `amp-ad` tags blocked, the CONSENT_STRING macro is not replaced

**Comment by zhouyx** [comment]
Thank you for the detailed explanation. 
That is the expected behavior. One must specify the `<amp-ad>` component to be blocked by consent either through `<meta name="amp-consent-blocking" content="amp-ad">` or through `<amp-ad data-block-on-consent>`. Other wise the ad RTC call won't wait for the consent iframe to return the consent string, and thus it will resolve to null. Does this make sense? Thanks

I see the RTC call part of the ad request. Which it should be blocked until the the consent has been collected (positive/negative). Would it ever be the case where one wants to send out RTC request without waiting for user consent, but still wants to block the ad request itself? 

Thanks
