### ISSUE TITLE
Missing baseScore in markup example

### ISSUE THREAD

**Issue by brichacek** [ampproject/amphtml#25309]
# What's the issue?

The baseScore option is missing from the example markup.  The baseScore should have a reasonable default assigned to the example markup.

## How do we reproduce the issue?

https://amp.dev/documentation/components/amp-subscriptions-google/ 
https://github.com/ampproject/amphtml/blob/master/extensions/amp-subscriptions-google/amp-subscriptions-google.md

The "Example with Markup" on these pages is missing the baseScore.

## What browsers are affected?

N/A

## Which AMP version is affected?

Documentation

**Comment by jpettitt** [comment]
It might make more sense to make the base score optional and default it internally if it's missing.

**Comment by jpettitt** [comment]
Just checked baseScore is [optional](https://github.com/ampproject/amphtml/blob/868e96181a23f9116bf9684322879ef9530e7395/extensions/amp-subscriptions/0.1/local-subscription-platform-base.js#L209) already so why put it in the example ?

**Comment by brichacek** [comment]
I would chalk this one up to a misunderstanding of baseScore by both myself and the partner I was helping integrate AMP then.  From what I understand now, the preferred method for most publishers is to enable the SwG service via a button somewhere in their local flow, rather than set a baseScore to force the SwG service.

**Comment by jpettitt** [comment]
OK closing  Works As Intended
