### ISSUE TITLE
Validator incorrectly accepts layout=fixed_height

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amphtml#25320]
The JS validator at https://validator.amp.dev (incorrectly) considers components with layout `fixed_height` valid. (This should be written `fixed-height`.) The validator used in the Google AMP cache does not.

Example doc with `layout=fixed_height` that is rejected by the Google validator (as expected), but accepted by the JS validator (unexpected): https://brash-grease.glitch.me/

Identical page except with `layout=fixed-height` for comparison: https://picayune-yttrium.glitch.me/

/cc @Gregable

**Comment by honeybadgerdontcare** [comment]
This is also true of `flex_item`, which should be `flex-item`. It appears the JavaScript engine is changing `-` in layout to `_`.
