### ISSUE TITLE
🌸 Cherry-pick request for #25332 into #25222 (Approved)

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#25338]
# Cherry-pick request

|       Issue       |       PR       | Production?  |     RC?      | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :----------: | :----------: | :-----------------------------------------------------------------------------: |
| #25332 | #25337 | Yes | No |                               #25222                                |
| #25332 | #25337 | No | Yes |                               #25319                                |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

Custom Elements inside Shadow Roots are not upgraded.

# Mini-postmortem

## Summary

Custom Elements inside a Shadow Root's tree (not in the document's light DOM) failed to upgrade in a very specific series:

1. Any custom is registered (eg, `<amp-img>`).
2. A shadow root is created
3. An unregistered custom element is appended to the shadow root (eg, `<amp-state>`)
4. That new custom element is registered

| Users affected                                   | Impact                                                                       |
| ------------------------------------------------ | ---------------------------------------------------------------------------- |
| PWA pages using amp-shadow | Previously unregistered elements failed to upgrade |

## Root Causes

1. When creating a new shadow root, the Custom Element polyfill adds the shadow root to a list of tracked "root" trees
2. When the first custom element (any custom element) is registered, we cleared the list of root trees
3. When registering any more custom elements, we used a `querySelectorAll` on the document to search for any already-existing elements to upgrade

Because `querySelectorAll` does not return results inside a shadow tree, we failed to find already-existing CEs inside them.

## Action Items

| Action Item                   |               Type               |     Owner     |      PR #      |
| ----------------------------- | :------------------------------: | :-----------: | :------------: |
| A test suite for custom elements | Prevent | @jridgewell | #25370 |

### Things that went well

- The issue was reported within 1 day of release

### Things that went wrong

- Releasing the patched version took an additional day due to infrastructure issues

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by cramforce** [comment]
Approved

**Comment by jridgewell** [comment]
Postmortem posted.
