### ISSUE TITLE
amp-bind fails to initialize in PWA

### ISSUE THREAD

**Issue by mattwomple** [ampproject/amphtml#25332]
## What's the issue?

`amp-bind` does not work on the first AMP page loaded into a PWA since release 1910251950120 . It fails to initialize due to a hung promise:
https://github.com/ampproject/amphtml/blob/b63d17b740cc0c2f1279846ce5fea9ff934eb457/extensions/amp-bind/0.1/bind-impl.js#L596-L600

## How do we reproduce the issue?

Minimal example AMP and PWA available:

- Bind works: https://android.cmphys.com/temp/bind-init-fail-amp.html
- Bind does not work: https://android.cmphys.com/temp/bind-init-fail-pwa.html

## What browsers are affected?

Chrome 78 Windows and Linux tested

## Which AMP version is affected?

1910251950120

**Comment by mattwomple** [comment]
/CC @jridgewell I'm just starting to investigate this now, but wanted to ping you in case this has anything to do with custom elements polyfill v1 that was included in 1910251950120. If you could tag relevant people to this issue report it would be much appreciated as it is affected a large number of WompMobile PWAs.

**Comment by jridgewell** [comment]
Looking now

**Comment by jridgewell** [comment]
Found the problem, working on a fix now.

**Comment by mattwomple** [comment]
I'm a little slower than you, but I think I see. `const upgradeCandidates = this.queryAll_(root, query);` identifies 0 nodes that can be updated in the `upgrade()` method in `custom-elements.js`. Maybe?

**Comment by jridgewell** [comment]
Yup, I was querying only the `document` and not the individual shadows.
