### ISSUE TITLE
Difficult to Debug Doubleclick Targeting

### ISSUE THREAD

**Issue by ctbarna** [ampproject/amphtml#2533]
It doesn't seem possible to open the google console (a la `?googfc`) in an AMP page with doubleclick ads. Our AdOps team is finding it difficult to troubleshoot targeting issues and has no tools to help them figure out anything about what is wrong.

Are there any parameters–hidden or otherwise–that we can use to debug doubleclick ad delivery?

**Comment by jasti** [comment]
@ctbarna Thanks for raising this. I suggest you please reach out publisher-support@google.com, so they are able to prioritize Google Console or Google Publisher Toolbar to work for AMP ad requests. I will also reach out to the team internally.

In the mean time, please use the Chrome dev tools to emulate mobile requests and troubleshoot using the network tab by filtering for "pubads" and inspecting the payload.

**Comment by whatisjasongoldstein** [comment]
This is still a problem for us. I can use Chrome and confirm the targeting matches the markup, but non-developers cannot, and it's not helpful for determining what served (line item, creative, empty response, etc.)

Can you please press the issue again?
