### ISSUE TITLE
Our font file passes validation on our AMP page but NOT on cdn

### ISSUE THREAD

**Issue by dodozhang21** [ampproject/amphtml#2534]
Could someone help us understand why our ttf font file returns 404 on the cdn server but works fine on our regular AMP page? Our regular AMP page also validates without issue.

http://amp.parents.com/pregnancy/complications/miscarriage/is-it-a-miscarriage/#development=1
![amppagevalidates](https://cloud.githubusercontent.com/assets/646064/13675771/c233bf7e-e6a8-11e5-854b-24bd34921494.jpg)

https://cdn.ampproject.org/c/amp.parents.com/pregnancy/complications/miscarriage/is-it-a-miscarriage/
![cdnttf404](https://cloud.githubusercontent.com/assets/646064/13675763/bb1efb86-e6a8-11e5-9081-42b2b9231f0a.jpg)

**Comment by r0b0ticus** [comment]
Got some guidance from Google and sounds fonts at the moment need to return the correct content-type of font/ttf to be valid.

**Comment by dodozhang21** [comment]
Thanks for the reply. We will take care of that on our web servers.

**Comment by cramforce** [comment]
Docs are coming soon. Sorry about that. 

@r0b0ticus is right. Adding a content type in the response will fix it.
