### ISSUE TITLE
Story fails to build

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#25351]
Seems like stories sometimes completely fail to build, leaving the page rendered vertically.

JavaScript console claims that the page timed out waiting for `amp-story-render` service to be ready.

/cc @ampproject/wg-stories

**Comment by newmuis** [comment]
Trying to figure out a consistent repro case.

**Comment by newmuis** [comment]
I can't tell if it's the new release ([1910302211460](https://github.com/ampproject/amphtml/releases/tag/1910302211460)) or just a heisenbug, but I can't repro this at all anymore.  Lowering to P1 to keep an eye on it.

I was able to repro this at least sometimes in [1910251950120](https://github.com/ampproject/amphtml/releases/tag/1910251950120), so perhaps this was another effect of #25332 (since [the PR which resolves that](https://github.com/ampproject/amphtml/pull/25337) is the only difference between [1910251950120](https://github.com/ampproject/amphtml/releases/tag/1910251950120) and [1910302211460](https://github.com/ampproject/amphtml/releases/tag/1910302211460)).

**Comment by gmajoulet** [comment]
I forgot what the fix was but it's been verified with 3p publishers who could repro very often.
