### ISSUE TITLE
Ellipsis misplaced or missing in `amp-fit-text` on Android

### ISSUE THREAD

**Issue by georgecrawford** [ampproject/amphtml#2535]
We've seen a few problems with misplaced ellipses in `amp-fit-text` elements inside `amp-carousel`. Sometimes, the ellipsis appears with the wrong vertical alignment (Nexus 7 - 5.1.1):

![screenshot 2016-03-10 16 34 21](https://cloud.githubusercontent.com/assets/84737/13676504/008e10b4-e6de-11e5-955e-fce312d03614.png)

We've also seen ellipses disappear when moving between slides (e.g. ellipsis shows on slide 1, but after tapping the arrow they don't show on slide 2, nor when returning to slide 1).

Able to reproduce on android devices: 
Samsung s6 - 5.1.1
Samsung s4 - 4.4.2
Nexus 9 - 5.0.1
Nexus 7 - 5.1.1

Unable to reproduce on iOS devices: 
iPhone6 - 8.3
iPhone 6+ - 9.1

Example URL: https://ft-google-amp-staging-pr-80.herokuapp.com/content/18f1fd90-e3ba-11e5-a09b-1f8b0d268c39 (this is a PR app which will disappear when the branch is merged). Implementation here: https://github.com/Financial-Times/google-amp/pull/80.

**Comment by dvoytenko** [comment]
Interesting. I'll check which CSS might be misinterpreting the positioning.

**Comment by dvoytenko** [comment]
@georgecrawford Just got here. Could you please export this doc again? Having hard to reproducing this on other examples.

**Comment by georgecrawford** [comment]
It's now available at https://amp.ft.com/content/18f1fd90-e3ba-11e5-a09b-1f8b0d268c39. I don't have an Android device to test with, so can't be sure if it's still buggy.

**Comment by dvoytenko** [comment]
Yeah, I see. This is a fairly old bug. I'm gonna look for a link and post it here. Basically, `line-clamp` is buggy when switching visibility/display. I think it was fixed in WebKit a bit ago, but is still an issue in Blink. I'm gonna try to find a workaround.

**Comment by dvoytenko** [comment]
In the meantime, we are also exploring options to split carousel's description and place them under the carousel - that would allow us to more-or-less display descriptions without many limitations.

**Comment by georgecrawford** [comment]
Aah, we'd definitely be interested in that. 

________________



George

**Comment by dvoytenko** [comment]
One thing I'm exploring right now is to put two carousels under each other - master and dependent. Master contains images and interactive. Dependent is non-interactive and would contain descriptions. Swiping the master carousel would automatically switch the dependent one as well.

I think this would give a greater freedom to layout captions more flexibly with more space. I've seen this pattern in a number of use cases. WDYT?

**Comment by dvoytenko** [comment]
@georgecrawford and here's the blink bug on ellipsis and line-clamp: https://bugs.chromium.org/p/chromium/issues/detail?id=453483

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
