### ISSUE TITLE
amp-list without template yields inconsistent client-side versus server-side errors

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#25360]
An `amp-list` that is missing a `template` tag will result in a client-side `"Template not found"` error and a server-side `Expected response with format ...` error. To be self-consistent and more developer friendly, the server-side reported error should also be `"Template not found"`.

Repro: 
1. Go to https://amp.gmail.dev/playground/
2. Select "amp-list #1" from the examples
3. Remove the template element from the sample (and the mustache script so it validates)
4. Check the console -- it produces this error 
<img width="479" alt="Screen Shot 2019-10-31 at 5 49 49 PM" src="https://user-images.githubusercontent.com/10456171/67988600-dd0b0100-fc06-11e9-8b1c-707e11989ec0.png">
5. Press "Send" and open the email in Gmail
6. Check the console -- it produces this error
<img width="479" alt="Screen Shot 2019-10-31 at 5 50 50 PM" src="https://user-images.githubusercontent.com/10456171/67988649-fe6bed00-fc06-11e9-8f7f-cce849876196.png">

Currently the template assertion is unreachable in the SSR path `findAndSetHtmlForTemplate` because if there is no template, the code will never return a response with `html` property. The template assertion could be placed further upstream from the response assertion, with the tradeoff that the template service rendering methods would either be redundant (second assertion later) or self-inconsistent (the only method in the template service that does not check for this there).

cc/ @ampproject/wg-amp4email @ampproject/wg-ui-and-a11y

**Comment by choumx** [comment]
We can just change `SsrTemplateHelper.ssr()` to use `findTemplate()` instead and early-out if it returns null.

**Comment by caroqliu** [comment]
The CSR code path fires the XHR unconditionally and then asserts on the presence of the template. Shouldn't SSR also fire the XHR (by postMessage to the viewer) and then assert on the response from the viewer later?

**Comment by choumx** [comment]
I think it's reasonable to change CSR behavior here too. Seems like a waste of network resources. Hopefully there isn't some active niche use case that relies on fetching only (and ignoring render).

**Comment by caroqliu** [comment]
Closing as this has been fixed
