### ISSUE TITLE
<amp-subscriptions> include the productID in the available variable substitutions

### ISSUE THREAD

**Issue by ed-bird** [ampproject/amphtml#25365]
## Describe the new feature or change to an existing feature you'd like to see

Publishers need to understand what level of access is required for a particular article so that they can give the appropriate response to the request against their `authorizationUrl`.

If not, they may have to simply look to see if a user has *a* subscription or not instead of which level of access the user has.

Therefore, could we add the productID into the request to the `authorizationUrl` ?

## Describe alternatives you've considered

An alternative/workaround is for publishers to include the CANONICAL_URL in the `authorizationUrl` and then make a lookup on the publisher's side to see what level of access is needed for that article but this seems like an unnecessary step.

## Additional context

This is particularly important for some publishers who might want to offer subscriptions and contributions under the same publication and therefore need to differentiate between the two easily.

**Comment by ed-bird** [comment]
Actually, the better alternative is for publishers to do this when they actually specify the authorizationUrl as that is within their control.

No need for this in the end, sorry.

**Comment by jpettitt** [comment]
We should make product id a variable substitution, which would allow it in auth but more interestingly would allow in in amp-analytics and any other non-swg fetch requests.  P3 when possible.,
