### ISSUE TITLE
🌸 Cherry-pick request for #25007 into #25319 (Approved)

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#25367]
# Cherry-pick request

|       Issue       |       PR       | Production?  |     RC?      | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :----------: | :----------: | :-----------------------------------------------------------------------------: |
| #25007 | #25321 | **NO** | **YES** |                               #25319                                |
| #25007 | #25357 | **NO** | **YES** |                               #25319                                |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

The fixes unbreak a4a ads in shadow mode, which has significant impact.

# Mini-postmortem

The reason for this bug is an incorrect use of the top level `window.document` API which has different meaning in shadow docs, FIE, scoped services, etc.

## Summary

We received the report in #25007 that A4A ads would not render at all into PWA shell. This is a regression, but is unclear when exactly it started. The issue got attention from representatives from multiple companies, indicating it was a problem breaking all users of PWA model.

| Users affected                                   | Impact                                                                       |
| ------------------------------------------------ | ---------------------------------------------------------------------------- |
| All users of A4A ads served into PWA | Ads would not render at all. |

## Root Causes

1. Incorrect use of `window.document` API instead of ampdoc.

## Action Items

| Action Item                   |               Type               |     Owner     |      PR #      |
| ----------------------------- | :------------------------------: | :-----------: | :------------: |
| Prohibit `window.document` API | Investigate | @dvoytenko | #25418 |
| Investigate executing realWin unit tests in shadow mode  | Investigate | @dvoytenko | #25419 |

### Things that went well

- The issue was debugged and resolved

### Things that went wrong

- A fairly deep-in-the-core bug. We need better tools to prevent such bugs from happening.

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers
/cc @calebcordry @jeffjose

**Comment by cramforce** [comment]
Approved

**Comment by dvoytenko** [comment]
postmortem posted. /ht @calebcordry
