### ISSUE TITLE
Tests are failing because they can't find `sinon`

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#25371]
@jridgewell filed #14779 a long time ago to prevent the duplicate importing of `sinon` in test and runtime code.

As of today, we don't import `sinon` in `_init_tests.js`, which could be the cause of this error.

```
IT => "before each" hook for "<non-AMP element>.toggleVisibility"
  ✗ sinon is not defined
  require<["/home/travis/build/ampproject/amphtml/test/_init_tests.js"]</</<@/home/travis/build/ampproject/amphtml/test/_init_tests.js:403:3 <- /tmp/0ca27527e0cb92392409c507d4e9695d.browserify.js:99333:3
  
●
IT => "after each" hook for "<non-AMP element>.toggleVisibility"
  ✗ sinon is not defined
  require<["/home/travis/build/ampproject/amphtml/test/_init_tests.js"]</</<@/home/travis/build/ampproject/amphtml/test/_init_tests.js:433:3 <- /tmp/0ca27527e0cb92392409c507d4e9695d.browserify.js:99369:3
```

There's also #23726 which is trying to upgrade `sinon` to the latest version, and is running into failures due to `btoa` not being found.

Finally, there's #23842, which points out that tests should not be using the global sandbox.

I think all these issues can be fixed by importing `sinon` at the start of `_init_tests.js`, creating a fresh sandbox in the global `beforeEach()`, and ensuring that all tests use `window.sandbox` instead of the global `sinon` sandbox.

**Comment by rcebulko** [comment]
Nice find!
