### ISSUE TITLE
At attribute "srcset" tag "amp-img" is not specified url

### ISSUE THREAD

**Issue by ut4utc** [ampproject/amphtml#25391]
```
<figure class="amp-wp-article-featured-image wp-caption">
	<amp-img width="700" height="438" src="https://parketdoska.ua/wp-content/themes/woodheart/images/lazy.png" class="attachment-large size-large woodmart-lazy-load woodmart-lazy-none wp-post-image amp-wp-enforced-sizes" alt="013-5" srcset="" data-wood-src="https://parketdoska.ua/wp-content/uploads/2018/12/013-5.jpg" data-srcset="https://parketdoska.ua/wp-content/uploads/2018/12/013-5.jpg 700w, https://parketdoska.ua/wp-content/uploads/2018/12/013-5-600x375.jpg 600w, https://parketdoska.ua/wp-content/uploads/2018/12/013-5-300x188.jpg 300w" layout="intrinsic"><noscript><img width="700" height="438" src="https://parketdoska.ua/wp-content/themes/woodheart/images/lazy.png" class="attachment-large size-large woodmart-lazy-load woodmart-lazy-none wp-post-image" alt="013-5" sizes="(max-width: 700px) 100vw, 700px"></noscript></amp-img>	</figure>
```

## What's the issue?

Hi there, today afer update - 273 errors: At attribute "srcset" tag "amp-img" is not specified url.
This is my page with empty srcset:

## How do we reproduce the issue?

A public URLs 
https://parketdoska.ua/uk/gallery-woodfloor-woodheart/?amp
https://parketdoska.ua/каталог/террасная-доска/декоративная-планка-175х13х2200/amp/

1. Step 1 to reproduce - I don't know how to reproduce it. 

## What browsers are affected?

This errors at Google search console https://prnt.sc/prvctr

## Which AMP version is affected?

AMP version is 1.4.0.

**Comment by choumx** [comment]
Can you remove the empty `srcset` attribute?
