### ISSUE TITLE
Enable Percy visual diff tests for RTV experiment branches

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#25403]
This could help to catch bug like #25402 earlier in development phase.

@estherkim let me know what you think.

**Comment by estherkim** [comment]
We run integration and e2e tests on master builds in the `Experiment` Travis stage. Would it suffice to add visual diff tests there?

**Comment by lannka** [comment]
Yes. That is what I was thinking.

**Comment by danielrozenberg** [comment]
Percy only supports one execution of visual diff tests against a PR, so running multiple tests in different shards will not work. I can't think of a reasonable workaround at the moment but I'll keep thinking about it

**Comment by rsimha** [comment]
_[Infra triage]_ Is this something we'd like to do? If not, can this be closed?

**Comment by danielrozenberg** [comment]
Closing as outdated
