### ISSUE TITLE
@cramforce will be OOO from 7/23 to 8/31

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2540]
Please ping @dvoytenko for all questions you would have directed at me.

**Comment by cramforce** [comment]
Looks like this is starting today.

**Comment by cramforce** [comment]
Merged 2016-03-14
![Emma](https://i.imgur.com/Az5PJz5.jpg)

**Comment by dvoytenko** [comment]
LGTM!

**Comment by Meggin** [comment]
Congrats to the family!

**Comment by aprigogin** [comment]
Congratulations!

On Tue, Mar 15, 2016 at 11:19 AM, Meggin Kearney <notifications@github.com>
wrote:

> Congrats to the family!
>
> On Tue, Mar 15, 2016 at 10:42 AM, Dima Voytenko <notifications@github.com>
> wrote:
>
> > LGTM!
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ampproject/amphtml/issues/2540#issuecomment-196943176>
>
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ampproject/amphtml/issues/2540#issuecomment-196958389>
>



-- 
=G

**Comment by christianhaller** [comment]
Herzlichen Glückwunsch!

**Comment by ehd** [comment]
@cramforce Damn, congrats! :smile:

**Comment by bogosj** [comment]
+1

**Comment by individual8** [comment]
Good job!

**Comment by michaelkleber** [comment]
Woot!  Mazel tov!

**Comment by adewale** [comment]
LGTM++

**Comment by ymotongpoo** [comment]
LGTM :smile:

**Comment by Quodexx** [comment]
Congratulations!

**Comment by avimehta** [comment]
congratulations!

**Comment by cramforce** [comment]
Reopening this. Will be out to second half of paternity the next 5 weeks. Yipppeee :)

**Comment by mkhatib** [comment]
@cramforce is actually back! Believe it or not for awhile now 💃
