### ISSUE TITLE
🌸 Cherry-pick request for #25295 into #25319

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#25417]
# Cherry-pick request

|       Issue       |       PR       | Production?  |     RC?      | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :----------: | :----------: | :-----------------------------------------------------------------------------: |
| https://github.com/ampproject/amphtml/issues/13659 |https://github.com/ampproject/amphtml/pull/25295 | Yes| Yes |                               #25319 |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

While this is a long standing issue with amp-live-list, this is an issue that more and more publishers are facing with amp-live-list always returning stale values. This is an opt in fix needed for Nov 5 elections. A long term cache side fix is being explored.

## Why is a RC cherry-pick not needed?

Needs to be in RC and prod. 

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

<_YOUR_SUMMARY_>

| Users affected                                   | Impact                                                                       |
| ------------------------------------------------ | ---------------------------------------------------------------------------- |
| Anyone who access amp-live-list from cache will be affected. | Loss of amp-live-list functionality on cache if updates are coming in very quickly. Origin is fine.  |

## Root Causes

1.

## Action Items

| Action Item                   |               Type               |     Owner     |      PR #      |
| ----------------------------- | :------------------------------: | :-----------: | :------------: |
| <_E.g. Add integration test_> | <_Investigate/Mitigate/Prevent_> | @<_USERNAME_> | #<_PR_NUMBER_> |

### Things that went well

-

### Things that went wrong

-

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by nainar** [comment]
@cramforce does this still have your approval?

**Comment by jridgewell** [comment]
We're promoting the current RC (#25319) to production tomorrow (or whatever will be the current rc + this cherry pick). I'd be against cutting a new production _and_ rc just to never serve the new production after tomorrow.

**Comment by nainar** [comment]
@jridgewell The problem is this change is blocking deploying AMP coverage of tomorrow's elections. This change is needed for tomorrow

**Comment by cramforce** [comment]
Oh, wow, well, given that time constraint:

This is approved given it is opt-in. Please do an ASAP cherry-pick into RC, test it, and then you may proceed with production patch.

**Comment by jridgewell** [comment]
Can we promote RC + cherry pick (after verification) to prod tonight? Doing two separate cherry picks would mean a lot of delay.

**Comment by cramforce** [comment]
We can.

**Comment by nainar** [comment]
That should work for the publishers.
