### ISSUE TITLE
Consider removing timeout for extension loading

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#25415]
Research if removing timeout is better. The argument is that if a client asks to resolve a service and that takes "longer than usual", it's still better to resolve it eventually. The client can always timeout itself if it's operation is time-sensitive.

/cc @jpettitt

**Comment by newmuis** [comment]
Yeah, I mean also for extensions like `amp-story` (or maybe we're the only one?), where the extension basically is the functionality of the page, this seems extra important.

**Comment by jpettitt** [comment]
This timeout exposed a bug in extension loading.  I think keeping it, or removing the hard fail but logging slow loads to the console and our error reporting would be valuable.

**Comment by dvoytenko** [comment]
I agree with both sentiments. I've bumped up the timeout to 16 seconds and as the next step I'll redo it to just log.

**Comment by samouri** [comment]
@dvoytenko: is there more to do here?

**Comment by dvoytenko** [comment]
> @dvoytenko: is there more to do here / can this be closed?

IMHO, the timeout should just go. The error logging could still be kept for monitoring though.
