### ISSUE TITLE
Resource scheduling with IntersectionObserver

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#25428]
Investigate replacing AMP's scroll-event-based resource scheduling system with IntersectionObserver.

Related: https://github.com/w3c/IntersectionObserver/issues/372

New flagged feature in Chromium that enables `rootMargin` on implicit root in x-origin iframes: https://github.com/w3c/IntersectionObserver/issues/372#issuecomment-543938684

**Comment by choumx** [comment]
Dima's suggestions on the "position" vs. "size" coupling issue:

> InOb would legitimately skip most of resize events if they do not change intersection. I think this issue comes up here because we've been using `measure()`, `requestMeasure()`, `mutateElement()` and the rest of our infra to do all three: resize, position, and in-viewport monitoring. Separating them at this point would be difficult.
> 
> Alternative approach could be do something like this:
> 
> 1. Separate layoutBox into position and size.
> 2. Remove calls to `getLayoutBox()` API and instead use an asynchronous API of some kind to either provide measurements or intersection.
> 3. Remove `measureCallback()` APIs and replace them with async versions, that are cleaner map to resize observer concept.
> 4. Remove `inViewport()` callback and replace with async API better mapped to InOb.

**Comment by samouri** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉
