### ISSUE TITLE
<amp-subscriptions> requires markup that in turn requires inapplicable markup

### ISSUE THREAD

**Issue by slowernet** [ampproject/amphtml#25435]
The `amp-subscriptions` component [requires](https://amp.dev/documentation/components/amp-subscriptions/) `"isPartOf": { "@type": ["CreativeWork", "Product"], ...}`. 

Per [errors in Search Console](http://scr.slower.net.s3.amazonaws.com/YTujxLaz.png), designating the page to be part of `Product` in turn requires specification of `offers`, `review`, or `aggregateRating`, which seem intended to apply to products for sale in an e-commerce context, rather than articles or content subscriptions. (In our case, we don't have this type of metadata for our subscription product.)

It would be simpler if `amp-subscriptions` required `CreativeWork` only.

**Comment by jpettitt** [comment]
This was a search console false positive, it's been fixed.
