### ISSUE TITLE
Extension reload breaks waitForExtension

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#25436]
When an extension depends on another extension for a service it ends up in `waitForExtension` if the provider hasn't yet loaded.   We've been seeing timeouts from `waitForExtension` that shouldn't be happening.

This problem is that if v0.js detects a version mismatch (v0.js version differs from an extension version) it automatically loaded the correct version of the extension to match v0 9`getExtensionScript_`).  When it does this it creates a new extension holder which leaves `waitForExtension` waiting on a load that will never happen.

This only happens on publisher sites due to the AMP cache automatically syncing versions and it only happens if the extension in cache mismatches v0.js.

See deletion of the extension holder https://github.com/ampproject/amphtml/blame/40fa29d8daacd92fbbcfda825f4b7f89dab25a34/src/service/extensions-impl.js#L255

**Comment by jpettitt** [comment]
cc @choumx @jridgewell @i-like-robots also tracked in Google b/143942489

force fail example https://github.com/i-like-robots/broken-amp-versions-test-case

**Comment by dvoytenko** [comment]
I'm moving this to P0.

**Comment by dvoytenko** [comment]
The bug is in [this line](https://github.com/ampproject/amphtml/blob/819a2761c6e2354c2bd86c1359a5baa1fec2c11f/src/service/extensions-impl.js#L277). The regex is too allowing and matches both `amp-subscriptions-0.1` and `amp-subscriptions-google-0.1`. It was introduced by proxy in the #24730.

/cc @choumx

**Comment by dvoytenko** [comment]
The race condition indicated by @jpettitt is also an issue, but less likely to occur. Will be fixed in the same pull request.
