### ISSUE TITLE
Add console API for origin trials e.g. AMP.isOriginTrialOn(name)

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#25438]
Similar to `AMP.isExperimentOn('name')` but to check if an Origin Trial has been turned on. 

This could be done by returning the value of `window.__AMP_SERVICES['origin-experiments']`

**Comment by choumx** [comment]
This would require installing "originExperiments" service by default, which would have some v0.js bundle size impact.

Another solution is to print the enabled experiments to console when `OriginExperiments.getExperiments()` is invoked. Would that suffice?
