### ISSUE TITLE
Make AMP page invalid when there are 2 <amp-iframe> considered as tracking analytics

### ISSUE THREAD

**Issue by oliverfernandez** [ampproject/amphtml#25430]
As [per documentation](https://amp.dev/documentation/components/amp-iframe/?format=websites#tracking/analytics-iframes) only 1 `<AMP-IFRAME>`, considered to be used for analytics purposes, is allowed in an AMP page.

However, right now, when more than 1 of such `<AMP-IFRAME>` exist, the AMP page is still valid, and only a runtime console error is thrown

![Screenshot 2019-11-05 at 13 26 38](https://user-images.githubusercontent.com/1696239/68207772-f4b00400-ffcf-11e9-859a-df43b1b93de0.png)

This makes very hard to spot AMP errors, like this one, for services that automatically translate any HTML to an AMP valid page.

Would it be possible that this is detected at AMP validation time, so the problem can be detected and fixed before publishing the AMP page?

**Comment by choumx** [comment]
Thanks for filing this issue. 

The detection of iframes as "analytics" or "tracking" is a runtime heuristic that's subject to change. Also, this error just disables the affected `amp-iframe` element, which is a more targeted failure mode than making the entire page invalid.

So I don't think this is possible or desired, unfortunately.
