### ISSUE TITLE
AMP-Redirect-To doesnt work anymore?

### ISSUE THREAD

**Issue by baert93** [ampproject/amphtml#25432]
Hi, since yesterday no amp redirect via php is working anymore. 
header("AMP-Redirect-To: https://littlehelps.de/index.php");
exit();
I didnt change anything at my code and it worked fine all the time so i assume that you updated something? 

## What browsers are affected?

all browsers on all devices

## Which AMP version is affected?

amp-version="1911042323000"

**Comment by aaron-renovationbrands** [comment]
We can confirm the same behavior.

**Comment by aaron-renovationbrands** [comment]
Anyone care to comment why this quit working?
Is it related to another issue?

**Comment by nainar** [comment]
@aaron-renovationbrands @baert93 can we get a link to a live page that is down?

**Comment by aaron-renovationbrands** [comment]
https://www.americantinceilings.com/pattern6/

Not "Add to Cart" here,  the post action is on the slider(interstitial) titled "Skip & Continue To Cart" .
Products add to cart (navigate manually).

**Comment by caroqliu** [comment]
Thanks for reporting the issue! This is the PR to revert: #25242

**Comment by nainar** [comment]
The fix has landed in master. We are verifying the fix and will be rolling out to production ASAP.

**Comment by caroqliu** [comment]
@aaron-renovationbrands @baert93 Can you confirm that the behavior is restored on your respective pages?

**Comment by aaron-renovationbrands** [comment]
Working.
Thanks!!

**Comment by caroqliu** [comment]
The issue is resolved since #25470 hit production, post mortem on cherry-pick #25473 to follow.

**Comment by baert93** [comment]
yeah its working fine, ty for the fast solution!

**Comment by caroqliu** [comment]
@baert93 Could you still provide the steps to reproduce on your website? It would be great to have as much information as possible for the post mortem.
