### ISSUE TITLE
Allow ads in amp-subscriptions dialog fixed layers.

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#25469]
Currently ads in fixed layers are extremely limited (only `amp-sticky-ad`).
 
`amp-subscriptions` presents a content blocking fixed layer modal dialog to the user when the paywall meter expires.  There is a valid use case to present paywall call to action messages via an ad platform to facilitate a/b testing and message targeting.

## Feature Request

Allow `amp-ad` within the `amp-subscriptions` dialog.

### Issues to Consider

This may present an abuse vector to circumvent the `amp-sticky-ad` size and scroll limits.  It's probably not possible to guarantee that the creative is paywall specific.  We may want to constrain it to cases where the content access is not granted and disallow it in "you have x pages left" (access granted by metering) use cases.

Size, we should not constrain this to small size used by `amp-sticky-ad` since the point here *is* to block the content.

cc @jasti @jeffjose @rudygalfi

**Comment by jeffjose** [comment]
cc/ @lannka 

@jpettitt - Can you clarify the "disallow it in the _you have x pages left_" bit?

**Comment by jpettitt** [comment]
@jeffjose `amp-subscriptions` allows 2 types of fixed layer popup.  A non blocking "_you've used X of Y pages this month notice_" as the meter ticks down and a blocking "_you've used all your pages please give us money paywall_" when the user runs out of free reads.

I'm proposing that we only allow the ad in the fixed layer in cases where the meter count had expired and access was not granted.  Two reason for this:

1. It reduces the opportunity for abuse since the dialog is shown only under specific conditions we understand.
1. In the case where access to the content is not granted by the paywall page quality is not adversely affected by the ad in the dialog because we're already blocking access to the page content anyway.

**Comment by jpettitt** [comment]
@jeffjose @lannka let me know if you are ok with this and I'll have the SwG team make the changes and tag @lannka for a review.

**Comment by jpettitt** [comment]
cc @dvoytenko

**Comment by lannka** [comment]
Interesting, so the popup is a content blocking in-house ad for subscription. Is there a latency concern? as AMP put artificial delays to `amp-ad`.

**Comment by dvoytenko** [comment]
this could be allowed, but definitely some concerns:

1. Showing and ad really close to "Please subscribe" might make "Subscribe" feel less like a call to action. There are a lot of ads out there for subscribe/install/stuff-like-that. So might get things pretty muddy.
2. When we show an ad on a non-blocked page the message is: you can read this content because we also show you ads. When we shown an ad on a blocked page that a user cannot read we can't say that. If it was "subscribe or watch an add" that would be a different story, but that's not the case here.

**Comment by jpettitt** [comment]
They specifically want to use the ad system to serve the "please subscribe" messaging.  This lets them do a/b, geo specific calls to action.

**Comment by lannka** [comment]
> are ads held back for all render transitions or just initial render? If it's just the initial render it's not an issue as we have paywall query latency to deal with. If there is a delay after the dom mutate to show the paywall that could be an issue.

@dvoytenko correct me. `amp-ad` is a P2 element, we delay 2s. I'm not sure if it timed from the very beginning or from the time it is displayed. @dvoytenko ?

https://github.com/ampproject/amphtml/blob/afde5080073c71b1957824398d432afa4d5621e0/src/service/resources-impl.js#L1539-L1554

**Comment by dvoytenko** [comment]
@lannka i believe it's timed from the first visible time.

**Comment by lannka** [comment]
@jpettitt overall, this can lead to a latency issue. and also, this can be considered as a "Prestitial ad" that is listed as one of ["the least user preferred ad formats"](https://www.betterads.org/research/) on mobile devices by betterads.org. 

So I'm quite nervous about opening this Pandora's box.

/cc @jeffjose

**Comment by jpettitt** [comment]
I think all paywalls are Prestitial Ad's in that context - so that ship has sailed, the question is are we going to allow a publisher to use ad tech to render it.
