### ISSUE TITLE
amp-script: Interop with amp-list

### ISSUE THREAD

**Issue by AndrewKGuan** [ampproject/amphtml#25460]
currently the two components cannot be used together to produce UI.  
For example, if an amp-list is nested inside an amp-script tag, the new elements generated by the amp-list won't be able to get querySelected and mutated from the script.
Please see [this example](https://sulfuric-conga.glitch.me/testtest.html#development=1)

**Comment by AndrewKGuan** [comment]
Hi,
any thoughts on this request?  Would it be valuable?

**Comment by nainar** [comment]
I definitely think is worth having being able to mutate amp-components from `<amp-script>` is necessary for adoption.

**Comment by AndrewKGuan** [comment]
Lightbox seems to have its issue with script as well if the <amp-script> is inside the lightbox.

**Comment by AndrewKGuan** [comment]
It appears to me that if <amp-script> wraps around <amp-list>, it won't get access to the elements generated by the <template>.  But if  <amp-list> wraps around <amp-script>, the generated content is accessible.  That's still an issue because the first case is more common, for example, registering an event handler that can modify the contents inside the amp-list.

**Comment by AndrewKGuan** [comment]
So for both amp-lightbox and amp-list, the contents inside those components are inside a document fragment as appears to me.  If the script is inside the components, meaning that the script is living in the same fragment as the content, it'll work.  But the problem is that, most interactive cases such as clicking a button and triggering mutations on contents of those components, the trigger is most likely outside of those components, which means that you can't register an event handler that mutates the generated contents because the trigger is on the document and the content is on a fragment.

**Comment by AndrewKGuan** [comment]
Added an example for amp-lightbox:
https://sulfuric-conga.glitch.me/testLightbox.html

**Comment by AndrewKGuan** [comment]
I also changed the layout to 'fixed'.  The error still exists.

**Comment by choumx** [comment]
#25185 too.
