### ISSUE TITLE
Ability to open an image in amp-image-lightbox by clicking a different element 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amphtml#25474]
## Describe the new feature or change to an existing feature you'd like to see

Currently, the only way to open an image in `amp-image-lightbox` is by clicking that image. Not all users will understand they are able to do this. Publishers should be able to call out "click here to enlarge image" or "tap here to view images in gallery mode" and open an image. 

## Describe alternatives you've considered

An alternative would be creating a `tap` action, much like the `tap` event. This could then trigger the `tap` on the desired image to open it in a gallery. 

CC: @sebastianbenz

**Comment by cathyxz** [comment]
I think we had plans to migrate `amp-image-lightbox` to use `amp-lightbox-gallery` per https://github.com/ampproject/amphtml/issues/22955. This functionality is already supported by `amp-lightbox-gallery` per discussion in https://github.com/ampproject/amphtml/issues/25475, so we could refer folks to that instead. 

This is a relatively simple feature to implement. It would simply involve passing a parameter for the elementID and then using a getElementById call to find the element to open in `amp-image-lightbox.js`'s open function here: 
https://github.com/ampproject/amphtml/blob/5e7617e6729fe7c3e6060bfb08f42dc9fc587b0a/extensions/amp-image-lightbox/0.1/amp-image-lightbox.js#L865-L870

I think this is simple enough to be a good first issue, which would involve making the above change and writing a unit test for it.
