### ISSUE TITLE
Validator now returns 'UNKNOWN' instead of 'MANDATORY_AMP_TAG_MISSING_OR_INCORRECT'

### ISSUE THREAD

**Issue by morsssss** [ampproject/amphtml#25472]
This is happening for me in our build process for our AMP Camp demo site.

We use our [amphtml-autoscript](https://www.npmjs.com/package/amphtml-autoscript) gulp module to automatically insert script tags for AMP components that require them. The gulp module runs `amphtml-validator`, looks for errors indicating a missing script, and then inserts the necessary script tags.

Our module looks for error categories that are `MANDATORY_AMP_TAG_MISSING_OR_INCORRECT`. Now, though, we always see category 'UNKNOWN' instead. For example:

```
ValidationError {
       severity: 'ERROR',
       line: 1615,
       col: 0,
       message:
        'The tag \'amp-analytics extension .json script\' requires including the \'amp-analytics\' extension JavaScript.',
       specUrl: 'https://amp.dev/documentation/components/amp-analytics',
       category: 'UNKNOWN',
       code: 'MISSING_REQUIRED_EXTENSION',
       params: [Array] },
```

Unless I'm experiencing some sort of anomaly, this will break the build for anyone who uses our autoscripter.

Is this change intentional? If so, we can modify the autoscripter.

**Comment by honeybadgerdontcare** [comment]
This is related to the removal of error categories and it can be ignored now. We no longer display them in UI error messages but it's still part of the ValidationError due to issues with updating the API. Instead of using the error category you can use the `code` for your purposes.

**Comment by honeybadgerdontcare** [comment]
See #25188  [#issuecomment-545612607](https://github.com/ampproject/amphtml/issues/25188#issuecomment-545612607) for background.

**Comment by morsssss** [comment]
Ok, thanks!

I wish there was a safe way to warn other users out there... if there are any...
