### ISSUE TITLE
Add action to open amp-lightbox-gallery in overview mode

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amphtml#25475]
## Describe the new feature or change to an existing feature you'd like to see

I would like the option to open `amp-lightbox-gallery` to a specific image or in overview mode by clicking a non-image element. 

Currently, images are only viewable in `amp-lightbox-gallery` by clicking on an image with the `lightbox` attribute. 

CC: @sebastianbenz

**Comment by cathyxz** [comment]
Teehee! We already have this. =) 

https://github.com/ampproject/amphtml/blob/ad26bd3fe01bd7209b638525abead3fe7db87915/extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js#L722-L745

You should be able to reference an element by id and have it open in `amp-lightbox-gallery` so long as the element with said ID exists and is lightboxable (i.e. is an `amp-img` or `amp-video`).

**Comment by CrystalOnScript** [comment]
Awesome! I'm confused about one detail:

Where is `myLightboxGallery` declared? I'm unsure where we would place an id on `amp-lightbox-gallery`?

**Comment by CrystalOnScript** [comment]
After some more playing around, it seems to work with this syntax:

`on="tap:amp-lightbox-gallery.open(id='element-id')"`

I'll work on updating the documentation. Unless there should be a way to declare an id for `amp-lightbox-gallery`?

**Comment by sebastianbenz** [comment]
@cathyxz is it also possible to open the overview page of the gallery?

**Comment by cathyxz** [comment]
@sebastianbenz it is not. To clarify: 
1. Unless otherwise specified, including the `amp-lightbox-gallery` extension will automatically create a `<amp-lightbox-gallery>` element with the id `amp-lightbox-gallery`. This is the default id for the default `<amp-lightbox-gallery>`. You can override this by defining your own with a different id. 
2. `<amp-img id="foo" on="tap:amp-lightbox-gallery.open">`Clicking on the `amp-img` with id=foo will open the `amp-img` with `id=foo` in the default amp-lightbox-gallery. 
3. 
```
<amp-img id=foo lightbox.../> 
<button id=bar on="tap:amp-lightbox-gallery.open('id=foo')>Open Lightbox</button>
```
Clicking the button with `id=bar` will open the `amp-img` with `id=foo` in the default amp-lightbox-gallery.

**Comment by cathyxz** [comment]
I think defining your own `<amp-lightbox-gallery>` isn't currently supported via validator. We originally considered adding certain general / default options to `<amp-lightbox-gallery>`, but these haven't been super high priority so there's currently no reason to define one.

**Comment by sebastianbenz** [comment]
Sorry for not being clear, what I meant was: it'd be great to have an action that opens the gallery overview page, e.g.:

```
<button on="tap:amp-lightbox-gallery.open>Open Image Gallery</button>
```

would show the overview page:

<img width="437" alt="Screen Shot 2019-11-08 at 21 45 03" src="https://user-images.githubusercontent.com/380472/68509419-272c5c00-0271-11ea-9a88-f56bb3ee9efa.png">

**Comment by cathyxz** [comment]
Yup. That functionality does not currently exist, could be relatively straightforward to add. Sorry, I meant to clarify @CrystalOnScript 's questions prior with that list of cases.

**Comment by cathyxz** [comment]
I think this could also be a good first issue. Implementing an "open amp-lightbox-gallery in overview mode" PR would look something like modifying the `openAction_` function here to add a parameter for opening the lightbox in overview mode, e.g. ('overview=true'), and then calling the `openGallery_` function in `amp-lightbox-gallery.js`. 

In this function: 
https://github.com/ampproject/amphtml/blob/ad26bd3fe01bd7209b638525abead3fe7db87915/extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js#L734-L745

Conditionally call this function: 
https://github.com/ampproject/amphtml/blob/ad26bd3fe01bd7209b638525abead3fe7db87915/extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js#L1276

**Comment by anbei711** [comment]
can't get this working. Does amp-lightbox-gallery.js need an edit? Or use a different script?
<script async custom-element="amp-lightbox-gallery" src="https://cdn.ampproject.org/v0/amp-lightbox-gallery-0.1.js"></script>
