### ISSUE TITLE
Cannot load amp-ad iframe 

### ISSUE THREAD

**Issue by jandolezal71** [ampproject/amphtml#25481]
## What's the issue?

I treid to check amp-ad examples in local running repository at `http://localhost:8000/examples/ads.amp.html`, but none of them is displaying. 

In Chrome console is full of errors with:

```
[Resources] task failed: amp-ad#9#L amp-ad#9 Error: only iframes with src supported
    at Log.assert (log.js:422)
    at devAssert (log.js:920)
    at listenFor (iframe-helper.js:264)
    at new SubscriptionApi (iframe-helper.js:473)
    at new IntersectionObserver (intersection-observer.js:156)
    at AmpAdXOriginIframeHandler.init (amp-ad-xorigin-iframe-handler.js:104)
    at amp-ad-3p-impl.js:396
```

![Screenshot_20191107_093814](https://user-images.githubusercontent.com/46811197/68373065-5abc9880-0142-11ea-8121-62d077de929b.png)

In Firefox, all ads have page not found.

![Screenshot_20200123_152608](https://user-images.githubusercontent.com/46811197/72992841-b66af980-3df4-11ea-84e2-6cbc94bf3966.png)

## How do we reproduce the issue?

1. git clone https://github.com/ampproject/amphtml.git 
2. cd amphtml
3. npm i yarn -g
4. yarn install
5. ./node_modules/.bin/gulp
5. Navigate to `http://localhost:8000/examples/ads.amp.html`
6. None of ads are displayed

I do not have an ad-blocker.

## What browsers are affected?

Chrome (version is 78). 
Firefox (version is 72)

**Comment by jandolezal71** [comment]
I am unable to develop on this repo anymore, because i cannot see ads in Firefox or Chrome now :( Any suggestions?

**Comment by vishaldodiya** [comment]
@jandolezal71 Would you please share what is in ads.amp.html?

**Comment by calebcordry** [comment]
Taking a look, checked out clean master, Chrome 79.0.3945.130 on Mac worked fine for me, but was able to repro on FF 72.0.2 Mac

**Comment by calebcordry** [comment]
Ok I think I know whats going on here. Our 3p ads wrapper is served from `ads.localhost.com`, chrome seems to resolve this to `127.0.0.1` while firefox does not. If you edit your `etc/hosts` file (on unix based systems) it will fix the issue.

@powerivq is looking into adding some documentation to avoid this in the future. @powerivq could you also add how to do this on windows? Thanks!

**Comment by calebcordry** [comment]
Windows host file appears to be at `C:\Windows\System32\drivers\etc\hosts`

**Comment by damjan25** [comment]
@calebcordry 

not sure if it is connected, I tried your fix but it did not work.
Currently getting on main branch this: "/examples/ads.amp.html could not be transformed by the postHTML pipeline"

when trying to access http://localhost:8000/examples/amp-fx-float-in.html
