### ISSUE TITLE
amp-video not loading in amp-ad

### ISSUE THREAD

**Issue by coreyb-cbs** [ampproject/amphtml#25494]
I have an amp-video inside an amp-ad inside a flying-carpet and the video won't load, only the poster image displays. Can someone help debug?
https://issue6823.qa.gamespot.com/amp-articles/hand-of-fate-developer-defiant-development-is-clos/1100-6468654/?adNetwork=7336&adTargeting_campaign=amp-flyingcarpet_321x31

I have it working fine on a demo page:
https://rev.cbsi.com/corey/test/amp/amp_demo_flying-carpet_736x739.html

Here's the amp-html running inside the amp-ad:
https://jsfiddle.net/k9zpch63/

**Comment by lannka** [comment]
@powerivq could you take a look?

**Comment by powerivq** [comment]
@lannka ack yes

**Comment by powerivq** [comment]
@coreyb-cbs Your first link is not working. Can you take a look?

I ran your example on jsfiddle and the video does play on my browser.

**Comment by coreyb-cbs** [comment]
@powerivq that first url is behind our firewall, so I built a demo page with the non-functioning video creative. The only difference between this creative and the other is the templates they were built in in GAM/DFP. Is this because of the video component js inclusion? 

The js fiddle doesn't work for me either, it was just a simplest way to share code so as to not clog up this ticket.

**Comment by powerivq** [comment]
I can't think GAM/DFP would cause the video to behave differently in this case. Can you pull out the creative and generate an example from it?
