### ISSUE TITLE
Incorrect error message selected for parent element restriction

### ISSUE THREAD

**Issue by cathyxz** [ampproject/amphtml#25499]
As a follow up to https://github.com/ampproject/amphtml/pull/25339#discussion_r343952781, 
In this example: 
```
 <!-- Invalid: submenus cannot be inside an amp-accordion -->
|        <amp-accordion>
|          <section>
|            <h4>accordion header</h4>
|            <div>
|              <h4 amp-nested-submenu-open></h4>
|              <div amp-nested-submenu></div>
>>             ^~~~~~~~~
amp-nested-menu/0.1/test/validator-amp-nested-menu-error.html:59:12 The attribute 'amp-nested-submenu' may not appear in tag 'div'.
```

The real error is that divs containing the `amp-nested-submenu` attribute should not be a child of accordion, not that "The attribute 'amp-nested-submenu' may not appear in tag 'div'." The error message is misleading, since the `amp-nested-submenu` attribute is actually supposed to be used with a div.

**Comment by Gregable** [comment]
This is fixed in an upcoming PR that'll be synced out shortly. Closing.
