### ISSUE TITLE
Local Proxy throws an error for a valid AMP

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#2549]
## Short description of your issue:
Local proxy (http://localhost:8000/max/s/URL) says page is invalid because of lack of `link canonical` but the page is valid in production and does have `canonical` link.

## How do we reproduce the issue?

Please post a public URL and ideally post a reduced test case. E.g. on jsbin.com that exhibits only your issue and nothing else.

1. Run the local proxy `gulp`
2. Try http://localhost:8000/max/s/searchengineland.com/google-dance-2016-recap-244051/amp OR http://localhost:8000/min/s/searchengineland.com/google-dance-2016-recap-244051/amp
3. Notice errors in the console and that the proxy fails to render the page (see screenshot)

![screen shot 2016-03-10 at 7 48 53 pm](https://cloud.githubusercontent.com/assets/2647/13692761/3393be12-e6f9-11e5-8185-adefa850e5cb.png)

## What browsers are affected?
Version 50.0.2656.0 canary (64-bit)
Mac OS X 10.11.3 (15D21)

## Which AMP version is affected?
Running `8550ddb6f093dc58636b9cf84b8457fd339d00f2` from `master` with version AMP `1456780777111`.

**Comment by erwinmombay** [comment]
@mkhatib i dont see that page being valid, i see a bunch of errors at http://searchengineland.com/google-dance-2016-recap-244051/amp#development=1

**Comment by erwinmombay** [comment]
@mkhatib nvm, i didnt realize you meant the actual sadphone page being invalid lol

**Comment by erwinmombay** [comment]
@mkhatib sorry i think i was confused, did you mean the actual searchengineland or the sadphone page ? funnily enough the error page isnt valid amp :)

**Comment by mkhatib** [comment]
No you were right, I thought the searchengineland article is valid, but it isn't although the errors thrown by the local proxy are different in this case it says there's no canonical tag.

**Comment by erwinmombay** [comment]
cool, thanks for clarifying. feel free to close
