### ISSUE TITLE
The AMP component script tag required for a tag on this page does not exist.

### ISSUE THREAD

**Issue by nailaliyev** [ampproject/amphtml#25534]
Hi
I have got 3 error pages abour AMP.
''The AMP component script tag required for a tag on this page does not exist.''
Pleace help me?

**Comment by mattwomple** [comment]
Hi @nailaliyev , it sounds like you're missing the scripts for the AMP components used by your page. The error messages tell you which script tags are missing. For example, [`<amp-lightbox>`](https://amp.dev/documentation/components/amp-lightbox/?format=websites) requires script `<script async custom-element="amp-lightbox" src="https://cdn.ampproject.org/v0/amp-lightbox-0.1.js"></script>` in the `<head>` of your document.
