### ISSUE TITLE
I2I: Propensity to Subscribe

### ISSUE THREAD

**Issue by mborof** [ampproject/amphtml#25546]
## Summary

Allow publishers to get the user's likelihood of subscribing to their products within AMP.

## Design document

https://docs.google.com/document/d/1__C9SJx9sjxOo1TiAb7c7MSPtOzbJkCnAXCeG_6UgbE/edit#heading=h.4zli8r3l75p6 (DRAFT)

## Motivation

The SwG team already provides this service for non-AMP purposes and would like to enable it for usage within AMP.

This will allow publishers to tailor their advertising and subscription options to the user based on how likely that user is to subscribe to their product.

## Additional context

Propensity to Subscribe is a module used to report subscription buy-flow events for a user and subsequently get a "propensity to subscribe" score for that user (likelihood that user will purchase a subscription to the news).  This is a Google provided service.

The Subscribe with Google (SwG) project makes it easier for news publishers to use Google's log in and payment infrastructure to manage their subscriptions.  The SwG team provides the front-end API for publishers to use Propensity to Subscribe.

## Launch tracker

TODO

/cc @ampproject/wg-approvers

**Comment by samouri** [comment]
@mborof / @jpettitt: what is the status of this? Can it be closed?

**Comment by jpettitt** [comment]
Yes close for now, the underlying design is obsoleted by the death of 3p cookies, will re-open if needed later.
