### ISSUE TITLE
OWNERS bot automatically add label

### ISSUE THREAD

**Issue by honeybadgerdontcare** [ampproject/amphtml#25550]
Is it possible for the OWNERS bot to automatically add a label in addition to cc'ing a group?

For instance, validator related changes cc ampproject/wg-caching. Could it also add the label "WG: caching"?

**Comment by rcebulko** [comment]
It is possible, but I'm not sure if it really falls under the scope of the owners bot's purposes. What would be the use-case for this feature?

**Comment by honeybadgerdontcare** [comment]
If there's a validator file change we'd like it labeled with "WG: caching". This provides for easy searching and discovery of existing issues and pull requests. If this is outside of the OWNERS bot, we can do a search for mentions of wg-caching instead and apply the label manually or create our own bot.

**Comment by rsimha** [comment]
I don't think it's always reasonable to automatically label PRs based on files changed. 
- Large PRs that rename a variable across several files or refactor commonly used code will end up tagging all working groups.
- PRs primarily focused on one area that just happen to touch common code (like runtime or infrastructure) will tag more WGs than necessary.

In addition, I'm not sure if all WGs use labels for PRs like they do for issues. I'd be interested in hearing of other ideas that will scale across all use cases.

**Comment by rcebulko** [comment]
I would be inclined to suggest starting with `notify: true` in the `OWNERS` file, and then one of the notified members can selectively add a label if appropriate

**Comment by danielrozenberg** [comment]
Looks like @ampproject/wg-infra has qualms about this feature request. @honeybadgerdontcare does the solution Ryan suggested work for you instead?

**Comment by honeybadgerdontcare** [comment]
@danielrozenberg yes, that would work.

**Comment by danielrozenberg** [comment]
Alright, closing this issue :)
