### ISSUE TITLE
[amp-next-page-v2] History manipulation

### ISSUE THREAD

**Issue by wassgha** [ampproject/amphtml#25553]
Currently `amp-next-page` only keeps the state of the currently viewable document in history which means that it's impossible to go back to the original article (the host page) using the browser's back button.
`amp-next-page` `v2` currently does not manipulate history at all so we have to implement the existing behavior and improve it by keeping a history stack of all pages seen (and replacing history state if the user scrolls back to a previously seen page).

**Comment by nainar** [comment]
@wassgha could you give a more detailed description here?
