### ISSUE TITLE
<amp-img /> occurs error about "TypeError: Cannot read property 'complete' of null"

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#25568]
To whom it may concerned:

Check the following screenshot. Looks like `<amp-img />` occured error.

![image](https://user-images.githubusercontent.com/10822546/68728192-93a4b380-0601-11ea-8b07-3ff7482a1838.png)

Is this error relate with `amp-carousel` 0.2 ? I check some `amp-carousel` 0.1 pages and them work fine.

demo page: https://tw.bid.yahoo.com/amp/homepage

Looks like the following code has already fixed. Just wondering when will this one release ?

https://github.com/ampproject/amphtml/blob/7131290c6030b4e1cd91d4c7a723781bcc644a4f/builtins/amp-img.js#L288

Paul

**Comment by cathyxz** [comment]
This fix was merged in https://github.com/ampproject/amphtml/pull/25498, which made the canary release tracked by https://github.com/ampproject/amphtml/issues/25569. You can follow #25569 to see when the release will be pushed to production. Releases will also be announced in the #release slack channel.

**Comment by meistudioli** [comment]
@cathyxz , thanks a lot.

**Comment by cathyxz** [comment]
No problem, thank you for your continued contributions and excellently communicated issues. =)
