### ISSUE TITLE
I2I: Rename AMP's release flavors

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#25560]
## Summary

This I2I proposes a new set of names for all of AMP's current and upcoming release flavors.

## Design document

[AMP Release Names](https://docs.google.com/document/d/1qd9s7MUZV5g_X9Px9AlEz3wQIakmjgeg8KYCMYO0w9M)

## Motivation

When the AMP project started, there were two release flavors: `prod` (the current stable release) and `canary` (the latest code with experimental features). Since then, multiple release flavors have been added with more on the way. This has caused terms like "prod" and "canary" to be overloaded to refer to both release flavors and config types.

The purpose of this I2I is to specify a set of names that are self-explanatory and easily recognized for all of AMP’s release flavors, including ones that are in the process of being created.

## Proposed name changes

Names that are changing are italicized. Updated documentation for what each release contains will follow.

Current name | New name
-- | --
prod | _stable_
rc | _beta_
canary | _experimental_
control | control
nightly (#25578) | nightly
monthly (#25616) | _lts_
experimentA | experimentA
experimentB | experimentB
experimentC | experimentC

## Launch tracker

Will be updated by @ampproject/wg-infra.

/cc @ampproject/wg-approvers

**Comment by rsimha** [comment]
Updated description with proposed names.

**Comment by rcebulko** [comment]
Long-term: Once we've shifted most usage of `prod` to `stable`, I think `prod` or `production` in documentation should be used to refer to the combination of `stable` and `lts`. For example, in release guidelines and cherry-pick/rollback procedures, it would be useful to say "If there is a P0 in production" versus "If there is a P0 in stable and/or LTS"

**Comment by rcebulko** [comment]
This rename requires an update to [AMP Release Schedule](github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)

**Comment by danielrozenberg** [comment]
What's still missing to mark this as fixed?

**Comment by rcebulko** [comment]
AFAIK this has been updated in `ampproject/amphtml` everywhere except https://github.com/ampproject/amphtml/blob/master/tools/experiments/experiments.js#L63

**Comment by danielrozenberg** [comment]
Cool. I sent PR #26489 to fix this along with other related changes. Let's close this issue!

**Comment by rcebulko** [comment]
Let's add "Closes #xxxx" to the above PR and let GitHub close it when that PR goes in

**Comment by rcebulko** [comment]
Correction, there is still more work to be done on this, please do not close.

**Comment by rsimha** [comment]
+1 to adding a "Closes #XXXX" or "Fixes #XXXX" to the pull request and letting GH do its thing. Makes it easier to trace related PRs / issues in future.

**Comment by danielrozenberg** [comment]
Pretty sure this is done. @rcebulko wanna do the honours?
