### ISSUE TITLE
slowButAccuratePrng name is misleading

### ISSUE THREAD

**Issue by riklund** [ampproject/amphtml#25572]
src/experiments.js contains a method called slowButAccuratePrng which has a comment describing in detail why it's preferable over Math.random(). However it is then implemented as just calling Math.random():
https://github.com/ampproject/amphtml/blob/14e352a628261124a702c2700e069a8f36a8c8ee/src/experiments.js#L347-L349

I think it would be good if we could either rename it or actually implement a better PRNG method.

**Comment by sparhami** [comment]
Is this comment still accurate? The code was originally added in #3534, over three years ago. I know there was a change to the `Math.random` implementation in several browsers a while ago, so I'm not sure if they are still a problem.

**Comment by riklund** [comment]
No idea. If we believe it isn't I think it would be good to rename the function and remove the comment.

**Comment by molnarg** [comment]
We still can't trust Math.random(), but no idea how we can implement a better one in JS if the crypto APIs are not available.
