### ISSUE TITLE
Intent-to-Deprecate-and-Remove: <amp-user-location>

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#25573]
## Summary

`<amp-user-location>` uses geolocation API for precise user-location data, which supports the use case where dynamic data is tied to user location. See [Reference documentation](https://amp.dev/documentation/components/amp-user-location/).

Removal plan: Unregister the component, remove associated documentation and examples on amp.dev

## Motivation

No one is currently using it as it is only available under experimental. Additionally, the API is inconsistent with `<amp-geo>` which would be a more ideal component to eventually support the original use case anyway.

## Impact on existing users

None

## Alternative implementation suggestion for developers using AMP

We could eventually subsume the functionality of `amp-user-location` under `amp-geo` for relaunch with continued interest for the feature.

/cc @ampproject/wg-approvers @ampproject/wg-ui-and-a11y

**Comment by cramforce** [comment]
LGTM1

**Comment by cramforce** [comment]
Process comment: If this never launched beyond experiments a formal intent issue is probably not needed. But still helpful for awareness.

**Comment by nainar** [comment]
In that case @caroqliu let's work on removing the code? 

@kristoferbaxter and @jeffjose as an FYI.
