### ISSUE TITLE
how to use IFrame API with AMP?

### ISSUE THREAD

**Issue by lovasoailay** [ampproject/amphtml#25570]
#25570  What's the issue?

I have an error log when integrating the IFrame API in AMP. 
This is my code. The file named base.js contains the onYouTubeIframeAPIReady function.
    <amp-script layout=container src="/amp/base.js">
    <amp-script src="https://www.youtube.com/iframe_api">
    <button id="hello">SEPARATION</button>
    <div id="player"></div>
    </amp-script>	
    </amp-script>	

## What browsers are affected?

Opera and Chrome

**Comment by nainar** [comment]
Hi, please use the Slack channel to ask such questions: https://docs.google.com/forms/d/e/1FAIpQLSd83J2IZA6cdR6jPwABGsJE8YL4pkypAbKMGgUZZriU7Qu6Tg/viewform?fbzx=4406980310789882877

Also hopefully this can help you get started: https://amp.dev/documentation/components/amp-iframe/
