### ISSUE TITLE
Add documentation for strip-prefix.

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#25593]
**summary**
After landing prefix stripping for amp-list (https://github.com/ampproject/amphtml/pull/25489), we should also add it's documentation. On top of that we should also figure out which other components to add it to.

**conditions of satisfaction**
- [x] `amp-list.md` documentation updated to explain usage of the new strip-prefix attribute.
- [x] determined list of json fetching components to add `strip-prefix` to.

**Comment by caroqliu** [comment]
For "explain usage of the new `strip-prefix` attribute" I'd recommend both describing how to use it and including code snippets

**Comment by samouri** [comment]
>  determined list of json fetching components to add strip-prefix to.

List of already asked for components:
- [x] `amp-list` (https://github.com/ampproject/amphtml/issues/17691)
- [ ] `amp-consent` (https://github.com/ampproject/amphtml/issues/22689)
- [ ] `amp-form` (b/143896641)

**Comment by lannka** [comment]
should we encourage using POST for JSON XHR going forward?
