### ISSUE TITLE
`amp-carousel` overlaps images after rotating device

### ISSUE THREAD

**Issue by georgecrawford** [ampproject/amphtml#2559]
Steps to reproduce:

1. Go to https://amp.ft.com/content/e96b93ea-2933-11e2-9591-00144feabdc0 on a mobile device, portrait.
2. Swipe a couple of images on the slideshow.
3. Rotate to landscape.
4. Broken layout:
![img_0035](https://cloud.githubusercontent.com/assets/84737/13698941/30627500-e76f-11e5-844f-889ca57c4149.PNG)

NB. this only seems to affect slideshows that are advanced with a swipe gesture. Using the arrow buttons doesn't present a problem with rotation.

Affects at least iOS and Android phones.

Video here: https://dl.dropboxusercontent.com/u/568883/slideshow-overlap.mov

**Comment by erwinmombay** [comment]
thanks @georgecrawford ! i've seen this before, definitely a bug.

**Comment by erwinmombay** [comment]
@dvoytenko assigning to you for now. feel free to reassign. (I'll grab it once i finish out my queue and nobody has gotten to it yet as well)

**Comment by sriramkrish85** [comment]
The url above does not work.
Here is an easy to reproduce URL - https://ampbyexample.com/components/amp-carousel/

**Comment by georgecrawford** [comment]
We're live with this now, so I updated the URL to https://amp.ft.com/content/e96b93ea-2933-11e2-9591-00144feabdc0.
