### ISSUE TITLE
Pause resource loading during swiping

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2560]
When we detect that a page is swiped we should immediately stop issuing new `layoutCallback` invocations for the page that is being swiped.

CC @ericfs @dvoytenko @jridgewell

**Comment by cramforce** [comment]
See also google issue number 27574989

**Comment by dvoytenko** [comment]
We discussed something like this - basically we simply need to completely turn off runtime passes until swipe is done. I guess this is our PAUSE state.

**Comment by jridgewell** [comment]
This should be very simple with the vis-state state machine. When in transitioning from `PASED` to `PAUSED`, we just noop instead of the pass function we do currently.

**Comment by dvoytenko** [comment]
Agree. And the `pause` callbacks themselves will happen in `VISIBLE` -> `PAUSED` and such transitions, right?

**Comment by jridgewell** [comment]
> And the pause callbacks themselves will happen in VISIBLE -> PAUSED and such transitions, right?

Yup.

**Comment by cramforce** [comment]
Nice, this will help a lot!
