### ISSUE TITLE
amp-date-picker: unselect date

### ISSUE THREAD

**Issue by ruipvs** [ampproject/amphtml#25609]
## Describe the new feature or change to an existing feature you'd like to see

When we select a date we should be able to unselect this date and with this remove the class selected to the previous selected date

## Describe alternatives you've considered

I tried to use amp state to toggle the value but amp-state-picket is not binded with the state variable. we should be able to bind a amp state variable

**Comment by joaopsrleal** [comment]
I've been taking a look at this FR.

A quick and somewhat hacky fix for this, would be to clear the date property we provide to the Picker component when responding to the [onDateChange event](https://github.com/ampproject/amphtml/blob/55ac520ca649f068aea56edf0fb15447df95c389/extensions/amp-date-picker/0.1/amp-date-picker.js#L1479-L1488).

Instead, I was thinking that we could maybe add this functionality to the [react-dates repo directly](https://github.com/airbnb/react-dates/tree/b87beb448680a6f131a23b3414c8a63bd7f56e6d). This way we minimize duplicating some of the logic already there and it would probably benefit others as well. This would mostly require modifying the [DayPickerSingleDateController component](https://github.com/airbnb/react-dates/blob/927fb93091f84393301b857bdb8b9d7c4aa00081/src/components/DayPickerSingleDateController.jsx) to check whether the day is already selected when running the [onDayClick callback](https://github.com/airbnb/react-dates/blob/927fb93091f84393301b857bdb8b9d7c4aa00081/src/components/DayPickerSingleDateController.jsx#L351-L366) using the [isSelected method](https://github.com/airbnb/react-dates/blob/927fb93091f84393301b857bdb8b9d7c4aa00081/src/components/DayPickerSingleDateController.jsx#L620-L622) and to pass undefined when the same date is selected. Probably we should add a new property to gate this behavior in order not to break existing users.

I'm happy to make this contributions to the react-dates repo.

@caroqliu wdyt?

**Comment by caroqliu** [comment]
Contributing the change at the level of react-dates SGTM. Will we have to bump our version of `react-dates` as well?

**Comment by joaopsrleal** [comment]
Given that this is effectively introducing a feature in a backward-compatible way, we could consider bumping the minor version of the repo. If that happens, then yes. I'll file a FR in the react-dates repo and we can have this discussion there.
