### ISSUE TITLE
Implement minimum penalty for ads

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2561]
We currently get hit by a special case (I believe) where if the first viewport contains no resources and the first resource on the page is an ad, then we load that ad immediately. This can strongly impact experience during swiping between articles.

I think we may want to put in an additional penalty that only applies at the very beginning of a page lifecycle.

CC @ericfs @dvoytenko @jridgewell

**Comment by dvoytenko** [comment]
This is in the visible state?

**Comment by aprigogin** [comment]
I think so, yes. We ended up delaying placing amp into the visible state
for 1 second. That greatly improved fast swiping through viewer.

On Fri, Mar 11, 2016 at 4:23 PM, Dima Voytenko <notifications@github.com>
wrote:

> This is in the visible state?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampproject/amphtml/issues/2561#issuecomment-195613880>
> .
>



-- 
=G

**Comment by cramforce** [comment]
Dima: Could you take this on? @jridgewell might also be great for you!
