### ISSUE TITLE
I2I: Nightly Releases for AMP

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#25616]
# Background

The AMP runtime library is released and updated on a weekly schedule, with a 5 to 6 day canarying period (approximately 1% of AMP documents) to give the team an opportunity to analyze logs for errors, warnings, and performance regressions and for the community to report issues found in the wild. This process has worked well in the past but with the amount of new code getting checked into the GitHub repository, the amount of new bugs also introduced has grown accordingly. The project has had 17 [P0 issues](https://github.com/ampproject/amphtml/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22P0%3A+Drop+Everything%22) in 2019 (last checked: November 15), mandating either a canary and/or a production cherry pick. The cherry pick process takes a considerable amount of time for release engineers and erodes community trust.

This I2I proposes the introduction of automated nightly builds coupled with a new release process, both with the aim of reducing the amount of cherry picks, the number of users affected by new issues, time spent by release engineers, and to increase community trust in releases.

## Non-goals

* Directly reduce the number of P0 issues: there are multiple other ongoing projects with this aim. This I2I is concerned with reducing the number of _potentially affected users_ of any future P0’s, and with streamlining the recovery process once a P0 is discovered
* Changes to any other type of release channel

## Prerequisites and related features

* [**prerequisite**] #25228 Move CSI collection to GCP Monitoring Metrics
    * The current performance metrics take days to get calculated, preventing us from being able to promote releases from nightly to canary until we have them
* [**optional prerequisite**] #25205 Opt-in to Specific AMP RTV
    * Having this feature can help release engineers quickly determine whether they should revert a release with a discovered issue and which versions have introduced the regression
* [**related feature**] #25560 Rename AMP's release flavors
    * The proposal discussed here is currently using release channel names before any changes proposed in #25560. Once that issue is finalized, this proposal will be updated to reflect those changes.
* [**related feature**] #25578 Create stable release channel with slower release cadence
    * Both this current I2I and #25578 propose process changes to releases, with different end goals and intents
* [**related feature**] Automate creation of AMP GitHub releases and reporting changes on Slack
    * This is proposed work by @estherkim, no GitHub issue yet

## See also

* https://github.com/ampproject/wg-infra/issues/18: Document the long-term strategy for disentangling the AMP runtime from the Google AMP Cache

# Overview

The current release schedule and process is described in [release-schedule.md](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md). We propose the following changes:

* Monday – Friday
    * [**new**] [**automated**] Create a new `nightly` release every day by choosing the last commit merged into the `master` branch that has passed all automated tests (“green” commit) before midnight PST, Monday through Thursday (that is, Monday 00:00, immediately after Sunday ends)
        * If no green commit exists, skip that day. This is an unlikely scenario over a 24 hour period but has happened occasionally in the past, usually due to infrastructure issues, such as a failed 3rd party integration.
    * [**new**] [**automated**] The release will be automatically promoted to the `nightly` channel (both percentage-traffic and opt-in) at 9 AM PT (most release engineers begin their work day at ~9 AM PT, but some are in different timezones), subject to the same code-freeze policy (i.e., no promotions to `nightly` channel during major US holidays)
        * The release on-duty should be attentive to this process
* Tuesday
    * [**changed**] On Tuesday 11 AM PT the on duty release engineer will choose a `nightly` build from the previous week (see description below of how the release engineer should choose which nightly to promote) to promote to the `canary` and `rc` opt-in channels (_not_ to the percentage-traffic channels)
        * Note that this is a change from the existing schedule, in which the last “green” commit before 11 AM PT is the one that gets promoted to these opt-in channels. This means that on Tuesday, the code being pushed to these channels is at the _latest_ from Thursday 11:59:59 PM PT
    * [**unchanged**] The previous `rc` is promoted to `prod`/`control` as before
    * [**changed**] The previous `rc` is also promoted to the new `nightly-control` channel, which will be served to an equal population volume as `nightly`. This is to allow fair comparisons between `nightly` and `prod` when it comes to finding new error reports
* Wednesday
    * [**unchanged**] This week’s opt-in `canary`/`rc` are promoted to the percentage-traffic channels

## Promotion strategies from `nightly` to `canary`/`rc`

The release on-duty should choose to promote to `canary`/`rc` the most recent `nightly` build from the previous week that:

1. Does not introduce a performance regression (see #25228) and
2. Does not have any discovered P0 issues

That is, if Friday’s release has no performance regression and no P0 issues, promote that.

<table>
  <tr>
   <td><strong>Week #</strong>
   </td>
   <td>
   </td>
   <td><strong>Monday</strong>
   </td>
   <td><strong>Tuesday</strong>
   </td>
   <td><strong>Wednesday</strong>
   </td>
   <td><strong>Thursday</strong>
   </td>
   <td><strong>Friday</strong>
   </td>
  </tr>
  <tr>
   <td rowspan="2" ><strong>n</strong>
   </td>
   <td><strong>After midnight</strong>
   </td>
   <td>release 1 is created
   </td>
   <td>release 2 is created
   </td>
   <td>release 3 is created
   </td>
   <td>release 4 is created
   </td>
   <td>release 5 is created
   </td>
  </tr>
  <tr>
   <td><strong>Working hours</strong>
   </td>
   <td>release 1 is promoted to <code>nightly</code>
   </td>
   <td>release 2 is promoted to <code>nightly</code>
   </td>
   <td>release 3 is promoted to <code>nightly</code>
   </td>
   <td>release 4 is promoted to <code>nightly</code>
   </td>
   <td>release 5 is promoted to <code>nightly</code>
   </td>
  </tr>
  <tr>
   <td rowspan="2" ><strong>n+1</strong>
   </td>
   <td><strong>After midnight</strong>
   </td>
   <td>release 6 is created
   </td>
   <td>…
   </td>
   <td>…
   </td>
   <td>…
   </td>
   <td>…
   </td>
  </tr>
  <tr>
   <td><strong>Working hours</strong>
   </td>
   <td>
   </td>
   <td>release <strong>5</strong> is promoted to <code>canary</code>
   </td>
   <td>
   </td>
   <td>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td colspan="7" ><em>Ideal scenario: no performance regressions or P0 issues were found on Friday’s <code>nightly</code> release, so we promote that one to <code>canary</code>.</em>
   </td>
  </tr>
</table>

Otherwise, looking into Thursday, Wednesday, and so on until a `nightly` is found without those problems.

<table>
  <tr>
   <td><strong>Week #</strong>
   </td>
   <td>
   </td>
   <td><strong>Monday</strong>
   </td>
   <td><strong>Tuesday</strong>
   </td>
   <td><strong>Wednesday</strong>
   </td>
   <td><strong>Thursday</strong>
   </td>
   <td><strong>Friday</strong>
   </td>
  </tr>
  <tr>
   <td rowspan="2" ><strong>n</strong>
   </td>
   <td><strong>After midnight</strong>
   </td>
   <td>release 1 is created
   </td>
   <td>release 2 is created
   </td>
   <td>release 3 is created
   </td>
   <td>release 4 is created
   </td>
   <td>release 5 is created
   </td>
  </tr>
  <tr>
   <td><strong>Working hours</strong>
   </td>
   <td>release 1 is promoted to <code>nightly</code>
   </td>
   <td>release 2 is promoted to <code>nightly</code>
   </td>
   <td>release 3 is promoted to <code>nightly</code>
   </td>
   <td>release 4 is promoted to <code>nightly</code>
   </td>
   <td>release 5 is promoted to <code>nightly</code>
   </td>
  </tr>
  <tr>
   <td rowspan="2" ><strong>n+1</strong>
   </td>
   <td><strong>After midnight</strong>
   </td>
   <td>release 6 is created
   </td>
   <td>…
   </td>
   <td>…
   </td>
   <td>…
   </td>
   <td>…
   </td>
  </tr>
  <tr>
   <td><strong>Working hours</strong>
   </td>
   <td>
   </td>
   <td>release <strong>3</strong> is promoted to <code>canary</code>
   </td>
   <td>
   </td>
   <td>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td colspan="7" ><em>Scenario: a performance regression or P0 issue is found on both Friday’s and Thursday’s <code>nightly</code> releases, but not on Wednesday’s. We promote Wednesday’s release to <code>canary</code>.</em>
   </td>
  </tr>
</table>

If Monday’s `nightly` release also has those problems, skip promoting a `canary` release this week.

<table>
  <tr>
   <td><strong>Week #</strong>
   </td>
   <td>
   </td>
   <td><strong>Monday</strong>
   </td>
   <td><strong>Tuesday</strong>
   </td>
   <td><strong>Wednesday</strong>
   </td>
   <td><strong>Thursday</strong>
   </td>
   <td><strong>Friday</strong>
   </td>
  </tr>
  <tr>
   <td rowspan="2" ><strong>n</strong>
   </td>
   <td><strong>After midnight</strong>
   </td>
   <td>release 1 is created
   </td>
   <td>release 2 is created
   </td>
   <td>release 3 is created
   </td>
   <td>release 4 is created
   </td>
   <td>release 5 is created
   </td>
  </tr>
  <tr>
   <td><strong>Working hours</strong>
   </td>
   <td>release 1 is promoted to <code>nightly</code>
   </td>
   <td>release 2 is promoted to <code>nightly</code>
   </td>
   <td>release 3 is promoted to <code>nightly</code>
   </td>
   <td>release 4 is promoted to <code>nightly</code>
   </td>
   <td>release 5 is promoted to <code>nightly</code>
   </td>
  </tr>
  <tr>
   <td rowspan="2" ><strong>n+1</strong>
   </td>
   <td><strong>After midnight</strong>
   </td>
   <td>release 6 is created
   </td>
   <td>…
   </td>
   <td>…
   </td>
   <td>…
   </td>
   <td>…
   </td>
  </tr>
  <tr>
   <td><strong>Working hours</strong>
   </td>
   <td>
   </td>
   <td>nothing is promoted to <code>canary</code>
   </td>
   <td>
   </td>
   <td>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td colspan="7" ><em>Scenario: a performance regression or P0 issue is found on all of week n’s <code>nightly</code> releases. We do not promote any release to <code>canary</code>.</em>
   </td>
  </tr>
</table>

### In `nightly`

Performance regression or P0 issues in `nightly` builds should be fixed as soon as possible or the offending code should be rolled back until a fix can be produced. We should not bother with rolling back the entire version or cherry picking that version, due to the small traffic it receives and because the issue will be fixed automatically with the next nightly release (either through a fix or through a rollback). Exceptions to this rule should be made when the issue is a P0 that has potential for privacy, security, or data loss issues.

Any `nightly` release that contains the offending code but not the fix is discarded from future consideration for promotion to `canary`/`rc` and `prod`.

### In `canary`/`rc`

The release on-duty will backstep from the promoted `nightly` (e.g., Thursday) until a release without the problem is found in the previous week (e.g., Tuesday), then roll back `canary`/`rc` to that version.

<table>
  <tr>
   <td><strong>Week #</strong>
   </td>
   <td>
   </td>
   <td><strong>Monday</strong>
   </td>
   <td><strong>Tuesday</strong>
   </td>
   <td><strong>Wednesday</strong>
   </td>
   <td><strong>Thursday</strong>
   </td>
   <td><strong>Friday</strong>
   </td>
  </tr>
  <tr>
   <td rowspan="2" ><strong>n</strong>
   </td>
   <td><strong>After midnight</strong>
   </td>
   <td>release 1 is created
   </td>
   <td>release 2 is created
   </td>
   <td>release 3 is created
   </td>
   <td>release 4 is created
   </td>
   <td>release 5 is created
   </td>
  </tr>
  <tr>
   <td><strong>Working hours</strong>
   </td>
   <td>release 1 is promoted to <code>nightly</code>
   </td>
   <td>release 2 is promoted to <code>nightly</code>
   </td>
   <td>release 3 is promoted to <code>nightly</code>
   </td>
   <td>release 4 is promoted to <code>nightly</code>
   </td>
   <td>release 5 is promoted to <code>nightly</code>
   </td>
  </tr>
  <tr>
   <td rowspan="2" ><strong>n+1</strong>
   </td>
   <td><strong>After midnight</strong>
   </td>
   <td>release 6 is created
   </td>
   <td>…
   </td>
   <td>…
   </td>
   <td>…
   </td>
   <td>…
   </td>
  </tr>
  <tr>
   <td><strong>Working hours</strong>
   </td>
   <td>
   </td>
   <td>release <strong>5</strong> is promoted to <code>canary</code>
   </td>
   <td>Release <strong>2</strong> is promoted to <code>canary</code>
   </td>
   <td>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td colspan="7" ><em>Scenario: no performance regressions or P0 issues were found </em>at first<em> on Friday’s <code>nightly</code> release, so we promote that one to <code>canary</code>. The next day we find a P0 in <code>canary</code> and discover it is also present in Thursday’s and Wednesday’s release, but not in Tuesday’s. We rollback <code>canary</code> to Tuesday’s nightly release.</em>
   </td>
  </tr>
</table>

If all of the `nightly` release from last week have that issue, a cherry pick will be performed per the [existing cherry pick](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-picks) instructions.

<table>
  <tr>
   <td><strong>Week #</strong>
   </td>
   <td>
   </td>
   <td><strong>Monday</strong>
   </td>
   <td><strong>Tuesday</strong>
   </td>
   <td><strong>Wednesday</strong>
   </td>
   <td><strong>Thursday</strong>
   </td>
   <td><strong>Friday</strong>
   </td>
  </tr>
  <tr>
   <td rowspan="2" ><strong>n</strong>
   </td>
   <td><strong>After midnight</strong>
   </td>
   <td>release 1 is created
   </td>
   <td>release 2 is created
   </td>
   <td>release 3 is created
   </td>
   <td>release 4 is created
   </td>
   <td>release 5 is created
   </td>
  </tr>
  <tr>
   <td><strong>Working hours</strong>
   </td>
   <td>release 1 is promoted to <code>nightly</code>
   </td>
   <td>release 2 is promoted to <code>nightly</code>
   </td>
   <td>release 3 is promoted to <code>nightly</code>
   </td>
   <td>release 4 is promoted to <code>nightly</code>
   </td>
   <td>release 5 is promoted to <code>nightly</code>
   </td>
  </tr>
  <tr>
   <td rowspan="2" ><strong>n+1</strong>
   </td>
   <td><strong>After midnight</strong>
   </td>
   <td>release 6 is created
   </td>
   <td>…
   </td>
   <td>…
   </td>
   <td>…
   </td>
   <td>…
   </td>
  </tr>
  <tr>
   <td><strong>Working hours</strong>
   </td>
   <td>
   </td>
   <td>release <strong>5</strong> is promoted to <code>canary</code>
   </td>
   <td>Issue is fixed in commit <code>a</code> on <code>master</code>.
<p>
Release <strong>5+<code>CP(a)</code></strong> is created and promoted to <code>canary</code>
   </td>
   <td>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td colspan="7" ><em>Scenario: no performance regressions or P0 issues were found </em>at first<em> on Friday’s <code>nightly</code> release, so we promote that one to <code>canary</code>. The next day we find a P0 in <code>canary</code> and discover it is also present in all of week n’s <code>nightly</code> releases. We fix the issue on <code>master</code> and perform a cherry pick.</em>
   </td>
  </tr>
</table>

### In `prod`

A cherry pick will be performed per the [existing cherry pick](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-picks) instructions.

# Implementation details

## Channel changes

<table>
  <tr>
   <td colspan="4" ><strong>AMP runtime channels*</strong>
   </td>
  </tr>
  <tr>
   <td colspan="2" ><strong>Traffic diverted by experiments platform</strong>
   </td>
   <td rowspan="2" colspan="2" ><strong>Notes</strong>
   </td>
  </tr>
  <tr>
   <td><strong>Name</strong>
   </td>
   <td><strong>Percentage</strong>
   </td>
  </tr>
  <tr>
   <td><code>prod</code>
   </td>
   <td>[remainder]
   </td>
   <td colspan="2" >
   </td>
  </tr>
  <tr>
   <td><code>control</code>
   </td>
   <td><code>0.5%</code>
   </td>
   <td colspan="2" >Same binaries as <code>prod</code>**
   </td>
  </tr>
  <tr>
   <td><code>rc</code>
   </td>
   <td><code>0.5%</code>
   </td>
   <td colspan="2" >
   </td>
  </tr>
  <tr>
   <td><code>canary</code>
   </td>
   <td><code>0.5%</code>
   </td>
   <td colspan="2" >
   </td>
  </tr>
  <tr>
   <td><code>experiment{A,B,C}</code>***
   </td>
   <td><code>0.5%</code> each
   </td>
   <td colspan="2" >
   </td>
  </tr>
  <tr>
   <td><strong><code>nightly</code></strong>
   </td>
   <td><strong><code>0.05%</code></strong>
   </td>
   <td colspan="2" >Add this
   </td>
  </tr>
  <tr>
   <td><strong><code>nightly-control</code></strong>
   </td>
   <td><strong><code>0.05%</code></strong>
   </td>
   <td colspan="2" >Add this
   </td>
  </tr>
  <tr>
   <td colspan="2" ><strong>Traffic diverted by opt-in cookie</strong>
   </td>
   <td colspan="2" >
   </td>
  </tr>
  <tr>
   <td colspan="2" ><strong>Name</strong>
   </td>
   <td colspan="2" >
   </td>
  </tr>
  <tr>
   <td colspan="2" ><code>rc</code>
   </td>
   <td colspan="2" >
   </td>
  </tr>
  <tr>
   <td colspan="2" ><code>canary</code>
   </td>
   <td colspan="2" >
   </td>
  </tr>
  <tr>
   <td colspan="2" ><strong><code>nightly</code></strong>
   </td>
   <td colspan="2" >Add this
   </td>
  </tr>
  <tr>
   <td colspan="2" ><code><em>rtv-specific</em></code>
   </td>
   <td colspan="2" ><em>Proposed in <a href="https://github.com/ampproject/amphtml/issues/25205">#25205</a></em>
   </td>
  </tr>
  <tr>
   <td colspan="4" >* only including web channels, i.e., excludes <code>amp4ads</code>, <code>amp4email</code>, etc.
<p>
** except for minor changes in the <code>AMP_CONFIG</code>, such as the <code>type</code> and <code>v</code> fields
<p>
*** <code>amp4ads</code> experiments have variable percentages, and therefore require their own equivalent control group to compare metric data; this is handled by the experiments platform used
   </td>
  </tr>
</table>

# Security and privacy considerations

This change is not expected to introduce any new security or privacy issues.

# Alternatives considered/to consider

## Do nothing

One option we can consider is to not introduce nightly releases at all.

## Auto-scaling traffic

In a previous design review we discussed the option of having traffic for `nightly` builds scale up automatically until they reach `prod` status automatically. This idea was rejected for two main reasons:

1. The traffic diversion platform used at Google does not support this feature out of the box, and implementing this would involve considerable work that might not be worth the effort
2. The release on-duty’s role as a human observer for sanity checks was preferred over automation

**Comment by mattwomple** [comment]
I attended the design review (#25447). I'm not entirely sold on this idea.

1. This increases branch complexity at a time when additional branch complexity is being considered in #25578 .
2. The goal of identifying regressions before the next release could be achieved by better advertisement of rc/dev releases (https://cdn.ampproject.org/experiments.html) to publishers.
3. Especially if this process is not blindly automated, this requires additional engineer resources. The every-increasing [Issues](https://github.com/ampproject/amphtml/issues) list suggests engineering resources are already stretched thin.
4. Especially if cherry-picks are permitted into nightlies, the cherry-pick process becomes more cumbersome due to testing and code review requirements in additional branches.

**Comment by danielrozenberg** [comment]
These are valid concerns, my responses to them are:

1. The branching complexity is a one-time change, and the backing platform supports the addition of channels relatively easily. We certainly have to create a flowchart as @twifkak requested to clarify the branching behaviour. It's really not as complex as you think :)
2. No strong opinion on this
3. I suggested that promoting the nightly release to receive traffic should be the only manual step, and this process update actually reduces the amount of manual steps the release on-duty has to perform (e.g., there will no longer be a need to manually cut the release and trigger a build). @dvoytenko wants to make the promotion automated as well, which means the release on-duty's job would only be to monitor error logs and performance metrics, both things that are already on their plate
4. There should be no cherry-picks into nightly builds except for the most extreme circumstances (I'm also working on easing the cherry-pick process, but that's mostly an implementation detail)

Do these answers help alleviate your concerns? If not, tell me why

**Comment by mattwomple** [comment]
Thanks for your responses @danielrozenberg .

> I suggested that promoting the nightly release to receive traffic should be the only manual step, and this process update actually reduces the amount of manual steps the release on-duty has to perform (e.g., there will no longer be a need to manually cut the release and trigger a build).

I appreciate the clarification. Perhaps this doesn't add as much overhead as I was concerned about.

I have no strong objections; you've largely alleviated my concerns. I'll be interested in hearing how the release managers on-duty receive this change. Hopefully, it does lead to earlier discovery of critical issues before releases are cut.

**Comment by danielrozenberg** [comment]
Great! We'll start the process in January though, it doesn't make sense to make this change now given the upcoming release freeze

**Comment by danielrozenberg** [comment]
Nightly builds are a thing!
