### ISSUE TITLE
I2I: amp-story-quiz

### ISSUE THREAD

**Issue by jackbsteinberg** [ampproject/amphtml#25615]
## Summary

The `<amp-story-quiz>` element will be an extension for adding multiple choice quizzes into AMP Stories. The quizzes will provide immediate feedback on the correctness of a response, along with percentage data for each response. These responses will be received from a backend storage system and updated on user interaction. Engagement data can also be captured from the element using AMP Analytics.

## Design document
[Link](https://docs.google.com/document/d/1kMLT2m6XOYmMQWoag6IUyQN7T2051vh6OnfKa9-Az-k/edit?usp=sharing)

## Motivation

Creating an `<amp-story-quiz>` element will allow viewers of stories to interact directly with creator content, and will allow creators to build a stronger relationship and understanding with their viewers.

## Launch tracker

- [x] Add interaction and default styling
- [x] Add automatic sizing and handle positioning constraints
- [x] Add animations
- [x] Add AMP Analytics support
- [x] Add support for custom backends
- [x] Add percentage display using a default backend
- [x] Add i18n support
- [x] Add custom styling surfaces
- [ ] Add validation

## Example

![image52 copy](https://user-images.githubusercontent.com/49928364/68972850-bb8b4700-07ba-11ea-9ff7-cb8b70f2985c.gif)

/cc @ampproject/wg-approvers @gmajoulet @newmuis

**Comment by gmajoulet** [comment]
Tracked in https://github.com/ampproject/amphtml/issues/28280
