### ISSUE TITLE
`gulp visual-diff` fails to start server on macOs

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#25613]
Running `gulp visual-diff` on `master` yields the following error message on MacOS Mojave 10.14.6: 

```
Error: Failed to start a web server: Error: connect ECONNREFUSED 127.0.0.1:8000
    at log (/Users/carolineliu/amp/amphtml/build-system/tasks/visual-diff/helpers.js:73:13)
    at performVisualTests (/Users/carolineliu/amp/amphtml/build-system/tasks/visual-diff/index.js:747:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

This appears to be failing at [`launchWebServer`](https://github.com/ampproject/amphtml/blob/3c9075504a45bf263dedb3b387170a9d937ea20f/build-system/tasks/visual-diff/index.js#L148). Directly executing `gulp serve --compiled --host localhost --port 8000` works, so the issue is not suspected to be with the `gulp serve` command itself.

**Comment by rsimha** [comment]
The server was recently rewritten so it can be started in-process. Will take a stab at this.

**Comment by rsimha** [comment]
Should be good now.

<img width="678" alt="" src="https://user-images.githubusercontent.com/26553114/69163863-fb08aa80-0abc-11ea-95cc-823b6e3cfc40.png">
