### ISSUE TITLE
amp-script: Treat "keydown" as user gesture

### ISSUE THREAD

**Issue by chasefinch** [ampproject/amphtml#25625]
## Describe the new feature or change to an existing feature you'd like to see

`amp-script` allows mutations for 5s after a user gesture. Currently it seems that within a text input, a keypress that causes an "input" event is considered a user gesture, but other keypresses (such as arrow keys) don't. I'd like for any input that would normally cause a "keydown" to be considered a user gesture and reset the allowed mutation window.

I'm trying to implement a common UI pattern, where a text input shows completion suggestions as the user types, with the first item highlighted by default. Then, the user can use the up/down arrow keys and then choose a selection with the enter key. This works for 5 seconds, but if the user touches "up" or "down" after 5s, the script terminates due to illegal mutation.

## Describe alternatives you've considered

This also seems to create a problem with `amp-autocomplete`. In order to use keyboard navigation of results, a user has to tab to the results pane. The more common UI pattern is to allow navigation without losing focus for the input. This is the behavior of the search box on Google.com.

Currently I'm working around the issue by automatically selecting the highlighted item if the user doesn't make a choice within 4.5s.

## Additional context

<img width="542" alt="Screen Shot 2019-11-16 at 12 45 45 PM" src="https://user-images.githubusercontent.com/1236825/68996972-10889500-086f-11ea-90cc-a5e06219be61.png">

**Comment by choumx** [comment]
```html
<link rel="manifest" href="http://writetogeather.com/wp-json/pwa-for-wp/v2/pwa-manifest-json/amp">
```

The protocol of this URL must be HTTPS.

**Comment by chasefinch** [comment]
The escape key is another use case that would probably be common to many custom amp-script components.

**Comment by samouri** [comment]
@chasefinch: https://github.com/ampproject/amphtml/pull/31825 adds `keydown` as an eligible activation event. It'll take ~2 weeks to reach stable.

I'll close this for now, but feel free to comment if there is something I've missed
