### ISSUE TITLE
Error: Request saveStore failed: Error: Xg

### ISSUE THREAD

**Issue by wassgha** [ampproject/amphtml#25643]
[http://go/ampe/CKC376fCmcT9Eg](http://go/ampe/CKC376fCmcT9Eg)

```
Error: Request saveStore failed: Error: Xg
at (https://raw.githubusercontent.com/ampproject/amphtml/1911121900560/extensions/amp-viewer-integration/0.1/messaging/messaging.js:460)
at event (https://raw.githubusercontent.com/ampproject/amphtml/1911121900560/extensions/amp-viewer-integration/0.1/messaging/messaging.js:83)
```

/cc @ampproject/wg-viewers

**Comment by ericfs** [comment]
This is a `storage unavailable` error from the Google AMP Viewer. I think this is expected that this will happen sometimes since a user could disable storage. I think the code that sends the `saveStore` message should be prepared for it to fail and it doesn't need to be logged as an error.

**Comment by wassgha** [comment]
@ericfs do you mind triaging this then?

**Comment by ericfs** [comment]
Meaning what? I'm not familiar with the AMP code that uses `saveStore`. Though looking quickly it's presumably related to https://github.com/ampproject/amphtml/blob/master/src/service/storage-impl.js#L402-L408

**Comment by choumx** [comment]
There's a short list of storage service users: https://github.com/ampproject/amphtml/search?q=storageForDoc&unscoped_q=storageForDoc

We can silence this error as part of a fix it e.g. catching the Promise rejection in `ViewerStorageBinding`.
