### ISSUE TITLE
Links not working Correctly in amphtml/contributing/contributing-code.md

### ISSUE THREAD

**Issue by ajitsinghkaler** [ampproject/amphtml#25640]
## What's the issue?

In amphtml/contributing/contributing-code.md Reviewer, Collaborator, Owner,Collaborators (amphtml), Reviewers (amphtml) , OWNERS Links are not working correctly

## How do we reproduce the issue?
1. Go to  amphtml/contributing/contributing-code.md
2. Search for above provided words
3. Move to those links
4. It shows a 404 page

**Comment by ajitsinghkaler** [comment]
I can take on this issue if you can tell me the correct links.

**Comment by choumx** [comment]
Those links aren't broken but perhaps access to GitHub teams pages are restricted. 

The "OWNERS" link to https://github.com/ampproject/amphtml/search?o=asc&q=filename:%22OWNERS%22&s=indexed should definitely work.

/cc @mrjoro
