### ISSUE TITLE
Ads: Declarative Viewability Loading Distance

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#2565]
We've had two requests for a declarative way to set the "viewability distance" that should load an ad.

- https://github.com/ampproject/amphtml/pull/2425#issuecomment-192407210
- https://github.com/ampproject/amphtml/issues/2407#issuecomment-195074242

**Comment by src-code** [comment]
Beyond merely determining when to load the ad, what about viewability as defined by the IAB, whereas (at least for desktop) 50% of the ad's pixels must be in the viewport for >= 1 second to be considered "viewable"?  

http://www.iab.com/guidelines/state-of-viewability-transaction-2015/

**Comment by cramforce** [comment]
Have people seen
https://github.com/ampproject/amphtml/blob/master/builtins/amp-ad.md#experimental-data-loading-strategy
? This is available in dev channel since today.

Regarding the IAB stuff: @src-code Are you asking for IAB style viewability events exposed to `amp-analytics`?

CC @jasti

**Comment by jasti** [comment]
@src-code The IAB definition is only applicable to the _viewability vendors_ for measuring what's considered viewable vs not. For e.g. ActiveView from DoubleClick and MOAT are the ones that use that IAB definition to determine if an ad is viewable. 
AMP supports both ActiveView and MOAT.

**Comment by cramforce** [comment]
@jasti we are planning to expose viewability to analytics. This wouldn't necessarily be ad specific, but it would do something like "trigger a hit when this amp element was viewable according to IAB".

**Comment by jasti** [comment]
Ah, this is great. Would love to read the spec/ requirement if there is one.

**Comment by avimehta** [comment]
@jasti The spec for this is outlined in https://github.com/ampproject/amphtml/issues/1297#issuecomment-197441289. Feedback welcome :).

**Comment by jasti** [comment]
@avimehta LGTM. Thanks!

**Comment by rudygalfi** [comment]
@jridgewell this is in progress, right? Can you give an ETA on it landing? Is it by March 31 release or after that?

**Comment by jridgewell** [comment]
It's not one of my priorities yet. Seems [Analytics integration](https://github.com/ampproject/amphtml/issues/2565#issuecomment-195604705) is more important now?

**Comment by rudygalfi** [comment]
Will this be dependent on https://github.com/ampproject/amphtml/issues/1297#issuecomment-197441289?

**Comment by jridgewell** [comment]
The code sharing between ads and analytics in our code is a little blurry to me, but these are very similar. I imagine we'd add a `visibilitySpec` attribute that's exactly like https://github.com/ampproject/amphtml/issues/1297#issuecomment-197441289.

**Comment by ericlindley-g** [comment]
@jridgewell , is this targeting the 4/14 milestone?

**Comment by jridgewell** [comment]
I don't even know what we want for this. After reading everything, this may be entirely handled by the analytics `visibilitySpec` without any need to change the ad loading behavior.

**Comment by ericlindley-g** [comment]
Got it—putting in the backlog for now, while we determine next steps

/cc @rudygalfi

**Comment by rudygalfi** [comment]
These do seem pretty related. It sounds like the `visibilitySpec` being developed in #1297 would be applicable here and we want to wait on it to land/stabilize before we move forward here.

cc @kashyapnitin

**Comment by jasti** [comment]
I thought the issue here is to allow a publisher to configure the ad loading distance instead of the default- 1.25 viewport before.
I think we can close this because we've been seeing that 1.25 works pretty well. Always can experiment later.
@jridgewell @avimehta do you agree?
If so, we can close this.
