### ISSUE TITLE
Make <amp-list> resizable.

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#25662]
From @morsssss 

"As far as I know, you still can't really allow it to grow and shrink as loaded content grows and shrinks.
For example, one company I talked to recently uses <amp-list> to display results from search - but as they can't predict how many hits each search will get, they end up leaving lots of white space. It doesn't feel good.
Also, if the browser windows changes size, <amp-list> doesn't respond well."

This is something multiple AMP adopters have asked for.

**Comment by morsssss** [comment]
@nainar , just noticed this is now a P3. Do you think we can bump up the priority here? I still hear about this issue frequently.

For example, at Chrome Dev Summit, I talked to UnoTV, who are using `<amp-list>` to display results from search - but they have trouble showing them without a lot of white space.

**Comment by choumx** [comment]
I think #26873 might fix this.

**Comment by morsssss** [comment]
I think that looks really promising!

**Comment by caroqliu** [comment]
Dedup with #26873
