### ISSUE TITLE
Prevent owners bot from assigning reviewers on draft PRs

### ISSUE THREAD

**Issue by wassgha** [ampproject/amphtml#25708]
Would be great if the OWNERS bot didn't assign a reviewer every time a commit is pushed to a draft PR (or maybe have a way to disable the automatic suggestion while keeping the blocking aspect of it)

**Comment by rcebulko** [comment]
Closing as a duplicate of https://github.com/ampproject/amp-github-apps/issues/587.

You can always opt-out of reviewer assignment by including #no-add-owners in the PR description.
