### ISSUE TITLE
[amp-script] Support calling AMP actions 

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#25711]
It'd be useful to be able to trigger AMP Actions from within an amp-script. Use cases would be:

* open an amp-lightbox from a script
* submit a form from a script
* trigger closeOrNavigateTo or navigateTo actions from a script

A positive side-effect would be that scripts can target elements outside the amp-script element's scope.

**Comment by choumx** [comment]
Combining with #24763.
