### ISSUE TITLE
Google Maps key is expired in AMP Docs at amp.dev

### ISSUE THREAD

**Issue by shakaran** [ampproject/amphtml#25710]
See
https://amp.dev/es/documentation/components/amp-iframe/

it says "Google Maps Platform rejected your request. The provided API key is expired."

**Comment by nainar** [comment]
@sebastianbenz this issue doesn't happen in the English translation but does in the Spanish one?

**Comment by sebastianbenz** [comment]
Most likely, the API key hasn't been updated for the other translations.

>
