### ISSUE TITLE
<amp-img> tags are not translated to <img> tags when unlocked with <amp-access-poool>

### ISSUE THREAD

**Issue by AdrienK-pro** [ampproject/amphtml#25712]
## What's the issue?

I'm working on News websites and some of our articles are locked up for none suscribed users.
When the content of an article is unlocked by Poool, the content that was hided is displayed succesfully unless for images. Indeed, the `<img>` tag that is supposed to appear after <amp-img> tag, when AMP is translated to HTML, is not appearing.  And if I reload the page, I can see that `<img>`.
If there is a `<amp-image-lightbox>` for the image, the lightbox displays it properly.

## How do we reproduce the issue?

Here is a URL where you can see the issue : [https://tinyurl.com/rs96646](https://tinyurl.com/rs96646)

To reproduce it:
1. Make a page that have the same setup of documentation's example : https://amp.dev/documentation/components/amp-access-poool/#html-sections

```
<section poool-access-preview amp-access="NOT access">
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur
    ullamcorper turpis vel commodo scelerisque.
  </p>
</section>

<section poool-access-content amp-access="access" amp-access-hide>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur
    ullamcorper turpis vel commodo scelerisque.
  </p>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur
    ullamcorper turpis vel commodo scelerisque.
  </p>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur
    ullamcorper turpis vel commodo scelerisque.
  </p>
</section>

<section amp-access="NOT error AND NOT access" id="poool"></section>
```

2. Place `<amp-img>` tags in the initially hided section `<section poool-access-content>`

3. Unlock this content with the "gift" widget of Poool.

## What browsers are affected?

All browsers, All device types.

## Which AMP version is affected?

I don't know if that issue was in previous versions. At this day, the version used is: 1911121900560.

Thank you in advance for digging in my issue.

**Comment by jpettitt** [comment]
The poool extension is not correctly using [mutateElement](https://github.com/ampproject/amphtml/blob/b692bf32880910cd52273cb41935098b86fb6725/extensions/amp-access/0.1/amp-access.js#L479) then it [changes the attributes ](https://github.com/ampproject/amphtml/blob/b692bf32880910cd52273cb41935098b86fb6725/extensions/amp-access-poool/0.1/poool-impl.js#L210) assigning to @dackmin

**Comment by jpettitt** [comment]
Please contact poool as they own the code in this extension.

**Comment by dackmin** [comment]
looking into this issue right now

**Comment by AdrienK-pro** [comment]
> Please contact poool as they own the code in this extension. - Edit: I've emailed them about it.

Thanks a lot for having a look @jpettitt !
