### ISSUE TITLE
Make amp-carousel[controls] the default behavior in AMP for Email

### ISSUE THREAD

**Issue by fstanis** [ampproject/amphtml#25713]
## Describe the new feature or change to an existing feature you'd like to see

Make `<amp-carousel>` work the same as `<amp-carousel controls>` for AMP for Email.

## Describe alternatives you've considered

Alternative: make `controls` mandatory for `amp-carousel` in the validator. This is not really ideal developer experience.

## Additional context

Gmail on mobile has the swiping motion reserved for moving between emails and thus [documents](https://developers.google.com/gmail/ampemail/tips) that users should always use `controls` on mobile. It seems many other mobile clients have the same problem.

**Comment by choumx** [comment]
I wonder if this should be a hint/warning in `#development=1` mode instead of forcing this option and adding another amp/amp4email divergence (and potential point of confusion).

**Comment by fstanis** [comment]
I think one problem is that the platform where this manifests (mobile apps) is the one where it's hardest to use development mode.

I guess another option is to make it a validator warning, but that'd be equally divergent from the web.

**Comment by fstanis** [comment]
Friendly ping

**Comment by choumx** [comment]
Did the discussion in #25714 have a resolution?

The current behavior for 0.1 seems reasonable to me -- the controls are temporarily flashed on touch devices, and always present on mouse devices. 

0.2 is fine since controls are always visible until interaction.

> Gmail on mobile has the swiping motion reserved for moving between emails and thus documents that users should always use controls on mobile.

Swiping between slides works well for me as long as I stay away from the edge. This "overloaded swiping" issue also exists for the Top Stories carousel on Google Search.

**Comment by fstanis** [comment]
This is one of the most reported issues with AMP emails on mobile since Gmail added support for Android, so I'd really want to address it somehow. For example, see [this tweet](https://twitter.com/cossssmin/status/1230201627082133506) for a good demo of how hard it can be swipe a carousel.

> Swiping between slides works well for me as long as I stay away from the edge.

I just tried this and was unable to move the carousel without moving to the next email no matter which part I tried to swipe:

![carousel](https://user-images.githubusercontent.com/250887/74941858-a9d5c300-53eb-11ea-9c02-da360fdb0960.gif)

The only thing that works is diagonal swipes:

![carousel2](https://user-images.githubusercontent.com/250887/74941878-b35f2b00-53eb-11ea-8070-5c36fc39dbfc.gif)

> 0.2 is fine since controls are always visible until interaction.

0.2 is not supported in emails (and likely won't be any time soon), so I'm hoping to also add this behavior to 0.1.

cc @zhangsu

**Comment by choumx** [comment]
Huh, works fine for me on iOS. :) Is this is a known issue on Gmail Android? 

It's a harmless enough change and I'm OK if there's no way around it. But if possible, would like to avoid diverging the spec due to a fixable bug on a single platform of a single email provider.

**Comment by zhangsu** [comment]
My 2c: Fixing the swiping issue in Gmail can take a while. If we feel like this behavior in the runtime is something that we can easily revert in the future and doesn't hurt the email ecosystem after email clients fix the swiping issue, then it's a good temporary stop gap solution that will immediately benefit users and developers while Gmail prioritize the long term fix in the client code.

> Is this is a known issue on Gmail Android?

Yes. Swiping carousels is also janky on Gmail iOS, but it's not completely broken like Gmail Android.
