### ISSUE TITLE
Override all experiment percentage to 100% for integration tests

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#25720]
While `--fortesting` flag is specified, we should override all fraction numbers in `prod-config.json` to 1 before prepending to `amp.js`. This is to remove randomness in tests. 

/cc @rsimha to triage.

**Comment by rsimha** [comment]
Good catch. Thanks for filing this. Can be done along with #24817.

**Comment by lannka** [comment]
Thinking twice, then it also comes with a risk that we're not testing the code with the experiment off anymore.

hmm...

**Comment by rsimha** [comment]
We do run the visual tests separately for canary and prod configs. So in that case, we could consider overriding all fractional numbers to 1.0 for canary and 0.0 for prod. For integration and e2e tests though, we currently test only with the prod config. Not sure what the best approach is here.

Would it make sense to add a new config json that's only applied when tests are run?

Tagging @ampproject/wg-infra, @ampproject/wg-runtime, and @ampproject/wg-performance for opinions on this.

**Comment by danielrozenberg** [comment]
We can also do three runs - `prod` config, `canary` config, and a specialized `all-experiments` config. This would of course add 50% to the execution time of integration tests and visual diff tests. wdyt?

**Comment by rsimha** [comment]
> This would of course add 50% to the execution time of integration tests and visual diff tests

This isn't acceptable because we already spend huge amounts of Travis CPU time running integration tests.

At a minimum, I think it makes sense to replace fractional numbers in the prod config with 1.0 while running integration tests. This can be accomplished by changing the behavior of `gulp dist --fortesting`. Can solve this along with #24817.

**Comment by rsimha** [comment]
Update: I did change the behavior of `gulp dist` to add `AMP_CONFIG` by default (#26554), but have not yet normalized the experiment values during `--fortesting`. Keeping this open.

**Comment by samouri** [comment]
If the only goal is to remove randomness, we could also normalize via `Math.round()`

**Comment by rsimha** [comment]
> If the only goal is to remove randomness, we could also normalize via `Math.round()`

I'm good with this plan (all non-zero experiment fractions effectively become 1 while running tests).
