### ISSUE TITLE
*_HOST URL substitutions use hostname, omit port number

### ISSUE THREAD

**Issue by src-code** [ampproject/amphtml#2572]
Currently (at least as of v1457112743399) the `SOURCE_HOST`, `CANONICAL_HOST` and `AMPDOC_HOST` URL substitutions rely on the `hostname` property of the anchor element, not `host`.  Because of this, the port number is omitted.  This can cause problems when referencing hosts serving on non-standard ports, for example in pre-production environments. 

I'd like to propose that these `*_HOST` vars should be changed to rely on `host`, and that new variables be introduced for `*_HOSTNAME` that would preserve the existing behavior.  This would of course be a breaking change, but would be more consistent going forward.  (And really, the impact may be minimal, so perhaps calling it a breaking change is being overly cautious?)

**Comment by dvoytenko** [comment]
I have no problem with this. @cramforce what do you think?

**Comment by rudygalfi** [comment]
Maybe combined with vendors.js updates we can do this?

**Comment by dvoytenko** [comment]
I think we should just go ahead and do it. /to @mkhatib

**Comment by rudygalfi** [comment]
@mkhatib when you start on this, please update the milestone. Thanks!

**Comment by mkhatib** [comment]
This sounds good. This hopefully won't break anyone's current usage as I'd imagine people don't use ports in their prod-setup.
