### ISSUE TITLE
🐢Tests using wrapped `rethrowAsync` take a very long time.

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#25725]
I don't think this is a problem on travis because we increase the timeout limit, but when running tests locally this causes consistent failure on macbook pro.

We have a function that stubs usage of `rethrowAsync` in tests https://github.com/ampproject/amphtml/blob/d1a7ee5a00f9e4cf08a06aeff321c97aa34c0517/test/_init_tests.js#L375

This stub eventually calls https://github.com/ampproject/amphtml/blob/d1a7ee5a00f9e4cf08a06aeff321c97aa34c0517/test/_init_tests.js#L380 

In these stubed tests `self.__AMP_REPORT_ERROR()` is a ref to https://github.com/ampproject/amphtml/blob/d1a7ee5a00f9e4cf08a06aeff321c97aa34c0517/src/error.js#L150

In that function we call https://github.com/ampproject/amphtml/blob/d1a7ee5a00f9e4cf08a06aeff321c97aa34c0517/src/error.js#L200

**That line of code takes between 2.7 - 3.1  seconds to execute on my laptop!!?!!?**

console error here is also stubbed to be a no op https://github.com/ampproject/amphtml/blob/d1a7ee5a00f9e4cf08a06aeff321c97aa34c0517/test/_init_tests.js#L321

I put some `console.time`s in here to see what was going on, and from the call to the time the NOOP function is executed accounts for the slowness. Unfortunately all the code that is executed in between is part of our external testing packages so I am not sure there is a good fix. Maybe reevalute how we are stubbing things?

If you want to see my "profiling" I have a draft pr here https://github.com/ampproject/amphtml/pull/25724 if you pull those changes and run `gulp unit --files=test/unit/test-3p.js --verbose` you should be able to repro and see some times being logged.

**Comment by calebcordry** [comment]
to/ @ampproject/wg-infra cc/ @ampproject/wg-ads

**Comment by calebcordry** [comment]
Had another thought, maybe this is slow because we are passing around the whole error stack? Just a guess though.

**Comment by rsimha** [comment]
Nice sleuthing, @calebcordry.

For context, `rethrowAsync()` was stubbed in order to prevent errors from one test from leaking into a subsequent test (#16916), and `console.error` was stubbed (via the `allowConsoleError` mechanism) in order to keep tests honest about runtime errors that may occur during execution (#14336).

I agree we should work on improving how tests can legitimately surface errors. Happy to discuss ideas. 

/cc @estherkim who is going to work on overall test reliability.

**Comment by calebcordry** [comment]
Thanks! I actually like the idea of the stubbed errors etc, but I think this stubception&trade; might be confusing sinon. Maybe we can convince them to work on their perf for things like this :)

**Comment by rsimha** [comment]
Resetting assignees since our projects have changed since this was filed. However, I think this is a good area to investigate, since the potential gains can be very high. Bumping to P2.

**Comment by rileyajones** [comment]
I can't seem to reproduce this issue anymore. If anyone thinks this is still happening, please reopen this ticket.
@dvoytenko @lannka
