### ISSUE TITLE
amp-date-picker: set an initialVisibleMonth

### ISSUE THREAD

**Issue by ruipvs** [ampproject/amphtml#25737]
## Describe the new feature or change to an existing feature you'd like to see

As in react-dates library we can set an `initialVisibleMonth`, amp-date-picker should be able to do that too

I can implement this feature.

**Comment by caroqliu** [comment]
Sounds good, could you also provide a link to the property documentation from react-dates for context? 👍

**Comment by nainar** [comment]
A good candidate for GFI if needed.

**Comment by rpvsilva** [comment]
> Could you also provide a link to the property documentation from react-dates for context? 
> 
> cc/ @nainar

In the link below you have an example of the feature that I want to implement.

https://github.com/airbnb/react-dates#daypickerrangecontroller

**Comment by caroqliu** [comment]
Thanks for providing the resource! #25741 is a change similar to this one in case it is helpful to reference what supporting it would look like.

**Comment by wassgha** [comment]
Claiming for Rebecca
