### ISSUE TITLE
Owners bot not expanding ampproject/working-groups?

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#25732]
<img width="1092" alt="Screen Shot 2019-11-21 at 3 51 18 PM" src="https://user-images.githubusercontent.com/8496897/69386225-d2c4ab80-0c76-11ea-99fb-c3c593f27805.png">

/cc @mrjoro

**Comment by rcebulko** [comment]
This was a result of deploying from a branch (to patch a blocking issue) that was not fully sync'd to master. The current master is now deployed, and this should no longer be an issue.
