### ISSUE TITLE
Amp Validator Result vs Search Console Result

### ISSUE THREAD

**Issue by rotexhawk** [ampproject/amphtml#25745]
Amp validator passes all my amp pages but google complains about them. Please see the following two urls. I have this issue for all my amp urls. 

**Amp Validator Result:** 
https://validator.ampproject.org/#url=https%3A%2F%2Fwww.michaelharwinlaw.com%2Fwhat-is-a-career-criminal%2Famp%2F

**Search Console Result**
https://search.google.com/test/amp?id=aClwacaTtbw5q7-Dm3glPg&skip_amp_follow=true

**Comment by honeybadgerdontcare** [comment]
Hello @rotexhawk,

For Search Console, if one clicks on the `VIEW AMP HTML` link it'll report the html begins with:

```
<!DOCTYPE html><html amp="" lang="en-US" amp-version="1911121900560" class="i-amphtml-singledoc i-amphtml-standalone" style="padding-top: 0px !important;"><head><style amp-runtime="">
...
```

For AMP Validator, the html begins with:

```
<!DOCTYPE html><html amp="" lang="en-US"><head><meta charSet="utf-8"/>
...
```

Which likely means the server is returning different html for each of these requests. The one being returned to Search Console appears to be some form of transformed AMP but does not include all the necessary requirements to be Valid Transformed AMP. If you're using a converter then you'll want to contact the owners of the converter to let them know something is going wrong.

**Comment by rotexhawk** [comment]
Thanks @honeybadgerdontcare. I am using gatsby js to statically build these pages and you can see the final html output [search console](https://search.google.com/test/amp?id=khLFg07BIgoKn_XaRuHfIQ). You can see that the generated html is valid, these tags are added after the page is loaded. 

It is added by the `v0.js` and I don't know why. If I remove the script, the html stays the same. 

```<script async src="https://cdn.ampproject.org/v0.js"></script>```
