### ISSUE TITLE
on Item click listner not working in amp-list

### ISSUE THREAD

**Issue by vishalvanpariya** [ampproject/amphtml#25756]
i created one list with carousel which has 6 image for different category.
but on tap function not working. can we use custom function like simple html.

please give me some solution.

Thanks,

Vishal

**Comment by caroqliu** [comment]
Hi Vishal, thanks for letting us know about this! In order to better help with the issue, could you provide a sample of your markup along with what you are expecting?

**Comment by caroqliu** [comment]
Dedup with #25316
