### ISSUE TITLE
AMP page is breaking when browser cached files are loading

### ISSUE THREAD

**Issue by pgdeep** [ampproject/amphtml#25751]
AMP page is breaking when browser cached files are loading. Its hard to replicate, but when the issue occurs there are many javascript errors in console. Ads are not loading. If I do cache refresh or ctrl + F5, it works fine. But, I can tell that to website visitors. If I try from different browser, it works without cache refresh. So, I suspect it should be something with browser cached files. It works if I browse the google amp cache url.

Please check below pages.
https://firstranker.com/mbbs/mbbs-2008-2019-question-papers-rajiv-gandhi-university-health-sciences/?amp
https://firstranker.com/fr.php/frdA041119A132440/download-ptu-b.tech-1st-semester-[2019]-70970-engineering-math-iii-question-papers
<img width="939" alt="fr" src="https://user-images.githubusercontent.com/16613943/69481534-256da700-0de0-11ea-88a3-df785a78b08f.png">

please find below the errors from console. Attached screenshot
```
amp.js:157 Powered by AMP ⚡ HTML - Version 1911062056110 https://firstranker.com/?amp extensions-impl.js:258 Uncaught (in promise) TypeError: Cannot read property 'setAttribute' of null

at Yl.f.reloadExtension (extensions-impl.js:258)
at jm (runtime.js:919)
at gm (runtime.js:208)
at lm (runtime.js:325)
at wi.qd (amp.js:118)
at vi (chunk.js:192)
at ri.Ze (chunk.js:410)
at chunk.js:461
amp-ad-0.1.js:1 Uncaught TypeError: (intermediate value)(intermediate value).push is not a function

at amp-ad-0.1.js:1
amp-loader-0.1.js:1 Uncaught TypeError: (intermediate value)(intermediate value).push is not a function

at amp-loader-0.1.js:1
amp-auto-lightbox-0.1.js:1 Uncaught TypeError: (intermediate value)(intermediate value).push is not a function

at amp-auto-lightbox-0.1.js:1
```

**Comment by jpettitt** [comment]
cc @lannka

**Comment by lannka** [comment]
<img width="1337" alt="Screen Shot 2019-11-25 at 9 58 21 AM" src="https://user-images.githubusercontent.com/8496897/69565586-25011780-0f6a-11ea-8fb7-ef45d2a7ab3e.png">

Not sure if it is related to the issue you're reporting, but the first example page has the `amp-ad` script included 2 times, which is consistently causing a different error message in the console:

> amp-ad is already registered. The script tag for amp-ad is likely included twice in the page.
vf @ error.js:195

**Comment by lannka** [comment]
I also suspect that the cache problem can be caused by mixing `amp-xyx-latest.js` with `amp-zyx-0.1.js` on the same doc. Any reason to do so?

**Comment by lannka** [comment]
@choumx @jridgewell do you see similar issue in the past? What's our current recommendation on using `-latest`

**Comment by choumx** [comment]
Ah, the new `getExtensionScript_()` doesn't handle `-latest` alias. Lots of bugs in this code path.

**Comment by jridgewell** [comment]
Seems like we should make `getExtensionScript_` use `parseExtensionUrl`, and fix `parseExtensionUrl` to parse `-latest`.

**Comment by choumx** [comment]
Looks like a top 25 error overall. `go/ampe/CI2FwOC7-YT7-wE` shows O(thousands) of errors per day.

**Comment by pgdeep** [comment]
> <img alt="Screen Shot 2019-11-25 at 9 58 21 AM" width="1337" src="https://user-images.githubusercontent.com/8496897/69565586-25011780-0f6a-11ea-8fb7-ef45d2a7ab3e.png">
> 
> Not sure if it is related to the issue you're reporting, but the first example page has the `amp-ad` script included 2 times, which is consistently causing a different error message in the console:
> 
> > amp-ad is already registered. The script tag for amp-ad is likely included twice in the page.
> > vf @ error.js:195

this is different issue, I can fix it from my code

**Comment by pgdeep** [comment]
> Looks like a top 25 error overall. `go/ampe/CI2FwOC7-YT7-wE` shows O(thousands) of errors per day.

Thank you..

**Comment by iniciopublic** [comment]
> > Looks like a top 25 error overall. `go/ampe/CI2FwOC7-YT7-wE` shows O(thousands) of errors per day.
> 
> Thank you for fixing the issue..

hello, how could you solve it? , I have the same problem, some functions do not work, sometimes yes and sometimes not

**Comment by choumx** [comment]
The fix will be released to production tomorrow.
