### ISSUE TITLE
Date of Birth selection with amp-date-picker

### ISSUE THREAD

**Issue by mfitconsultants** [ampproject/amphtml#25760]
Currently we want the user to be able to select their date of birth on a form using `amp-date-picker`

With other date selectors it is possible to click back to select the current year quickly and easily by clicking the month, year etc. 

https://demos.devexpress.com/aspxeditorsdemos/DateTime/DateRangePicker.aspx 

Navigating back over a long period of time is arduous and not a great user experience.

**Comment by caroqliu** [comment]
`amp-date-picker` was not built with the expectation of being able to select dates far in the past, though I'm unclear on if this has recently become a use case we are actively supporting. @nainar for more insights on this FR.

**Comment by nainar** [comment]
I agree that the date picker experience for picking a far behind date isn't good. 
The react date picker does allow it by enabling the `showYearDropdown` which can be implemented here. 

However currently the way to go about using it would be input date:https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

Current priority set makes sense. a GFI possibly?
