### ISSUE TITLE
Error: null is not an object (evaluating 'c.naturalWidth')

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#25764]
Looks like amp-auto-lightbox needs to handle amp-img's unlayout case.

For prod 1911121900560, this is our current top error report. 

`go/ampe/CKeCkqOTj53cWg`.

**Comment by Enriqe** [comment]
Any updates here? Still seeing a high number of occurrences on the last day in the current canary `2001251659540`.

**Comment by rcebulko** [comment]
This is one of the highest reported errors, with over half a million reports per day (across all releases). Have we identified the source of this issue? I'd be happy to take a stab at it if I could reproduce it

**Comment by alanorozco** [comment]
I believe #26573 will handle this. Not sure about reproducing manually.
