### ISSUE TITLE
Cannot override carousel controls SVG when used in email

### ISSUE THREAD

**Issue by adamgruber** [ampproject/amphtml#25777]
## What's the issue?

The [`<amp-carousel>` docs](https://amp.dev/documentation/components/amp-carousel/?format=email#attributes) state that you can override the default SVGs used for the controls by setting `background-image` for the `.amp-carousel-button` class. If I try to use a `data:` protocol as shown in the docs with `amp4email` it does not validate.

## How do we reproduce the issue?

1. Open the [AMP playground](https://playground.amp.dev/?runtime=amp4email&mode=Responsive)
2. Paste in the following code:
```
<!doctype html>
<html ⚡4email>
<head>
<meta charset="utf-8">
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script async custom-element="amp-carousel" src="https://cdn.ampproject.org/v0/amp-carousel-0.1.js"></script>
  <style amp4email-boilerplate>body{visibility:hidden}</style>
  <style amp-custom>
	.amp-carousel-button-prev {
      left: 5%;
      background-image: url("data:image/svg+xml,%3Csvg version='1.1' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'%3E%3Cpath d='M10.6,11.9l6.5-6.5c0.3-0.3,0.3-0.8,0-1.1L16,3.3C15.7,3,15.3,3,15,3.3l-8.1,8.1c-0.3,0.3-0.3,0.8,0,1.1 l8.1,8.1c0.3,0.3,0.8,0.3,1.1,0l1.1-1.1c0.3-0.3,0.3-0.8,0-1.1L10.6,11.9z'/%3E%3C/svg%3E%0A")
    }
    .amp-carousel-button-next {
      right: 5%;
      background-image: url("data:image/svg+xml,%3Csvg version='1.1' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'%3E%3Cpath d='M14.4,12l-6.5,6.5c-0.3,0.3-0.3,0.8,0,1.1L9,20.7c0.3,0.3,0.8,0.3,1.1,0l8.1-8.1c0.3-0.3,0.3-0.8,0-1.1 L10,3.3C9.7,3,9.3,3,9,3.3L7.9,4.4c-0.3,0.3-0.3,0.8,0,1.1L14.4,12z'/%3E%3C/svg%3E%0A");
    }
  </style>
</head>
<body>
  <amp-carousel height="300" layout="fixed-height" type="slides">
    <amp-img src="https://amp.dev/static/samples/img/image1.jpg" width="400" height="300" alt="a sample image"></amp-img>
    <amp-img src="https://amp.dev/static/samples/img/image2.jpg" width="400" height="300" alt="another sample image"></amp-img>
    <amp-img src="https://amp.dev/static/samples/img/image3.jpg" width="400" height="300" alt="and another sample image"></amp-img>
  </amp-carousel>
</body></html>
```
3. Observe the reported validation errors

## What browsers are affected?

All browsers

## Which AMP version is affected?

1911121900560

**Comment by caroqliu** [comment]
Hi @adamgruber 👋 Thanks for filing this issue!

SVGs are currently not allowed via styling in AMP for Email, and this specification should be clearly articulated in the documentation. [This issue](https://github.com/ampproject/amp.dev/issues/2745) reflects the effort to make this possible, so I will be closing this issue to dedup. 

cc/ @ampproject/wg-amp4email @fstanis
