### ISSUE TITLE
Allow amp-selector in AMP4ADS

### ISSUE THREAD

**Issue by jyn15** [ampproject/amphtml#25773]
**amp-form** is allowed in amp4ads, and the doc says amp-selector is allowed in amp-form:
https://amp.dev/documentation/components/amp-form/?format=ads#inputs-and-fields

Is there any reason why **amp-selector** itself is not allowed in amp4ads?

**Comment by lannka** [comment]
seems reasonable.
@ampproject/wg-ads @ampproject/wg-runtime @ampproject/wg-ui-and-a11y any objections?

**Comment by jyn15** [comment]
btw, this allows us achieving more customized carousel buttons in amp-carousel-0.2
https://amp-playground.appspot.com/amp/5639955095224320

**Comment by lannka** [comment]
@jyn15 you can go ahead and make the validator change. you will be updating: 
https://github.com/ampproject/amphtml/blob/master/extensions/amp-selector/validator-amp-selector.protoascii

/cc @honeybadgerdontcare correct me

**Comment by honeybadgerdontcare** [comment]
> @jyn15 you can go ahead and make the validator change. you will be updating:
> https://github.com/ampproject/amphtml/blob/master/extensions/amp-selector/validator-amp-selector.protoascii
> 
> /cc @honeybadgerdontcare correct me

That is correct. Any tag spec that has `html_format: AMP`, add underneath it `html_format: AMP4ADS`. Probably should also add a specific test file in [amp4ads_feature_tests](https://github.com/ampproject/amphtml/tree/master/validator/testdata/amp4ads_feature_tests) as well.

**Comment by jyn15** [comment]
Thanks! I will make the change.

**Comment by lannka** [comment]
@jyn15 could you please also update amp-a4a-format.md file

**Comment by jyn15** [comment]
Btw, do you know how to remove the banner on the top of page
https://amp.dev/documentation/components/amp-selector/?format=ads
saying "this component does not support your currently selected format ads!"

**Comment by honeybadgerdontcare** [comment]
@CrystalOnScript  @pbakaus regarding the banner message
