### ISSUE TITLE
I2S: layoutbox-invalidate-on-scroll experiment

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#25785]
## Summary

This accomplishes the main goal of Layers (supporting nested scrolling elements) by invalidating the layout boxes of elements inside a nested scrolling element after a scroll.

Eg, if an `<amp-carousel>` (once it migrates off of Ownership system) were to scroll, all `<amp-img>`s inside it would invalidate their layout boxes. Once the next Resources pass happens, the images would be remeasured, and we'll now detect that the image has moved closer/further from viewport.

The layout boxes themselves are still page-absolute and not viewport-relative. This means we keep the speed benefits that stopped us from shipping Layers.

## Intent-to-implement (I2I) issue

https://github.com/ampproject/amphtml/pull/25172

## Experiment(s) to enable

- `layoutbox-invalidate-on-scroll` 

## Required release version

1911042323000, https://github.com/ampproject/amphtml/issues/25319

## Demo instructions

Load https://gaitz.github.io/AMP-issues/amp-img-load.html, scroll the carousels

## Additional context

/cc @ampproject/wg-approvers

**Comment by cramforce** [comment]
Approved

**Comment by choumx** [comment]
Launched in #26430.
