### ISSUE TITLE
Switch experiments to read the global config

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#2579]
Switch experiments to read the global config

read ex. `window.AMP_CONFIG.experiment1`

**Comment by dvoytenko** [comment]
I think ideally it'd be:
```
window.AMP_CONFIG.experiments = {}  // Map<string, number>
```

**Comment by erwinmombay** [comment]
@dvoytenko so i intentionally made it at the top level to try and keep it flat, but if you feel strongly about it i don't mind adding the `experiments` namespace on top of the actual experiments

**Comment by dvoytenko** [comment]
Hmm - no, not very strong. Let's start with top level and see how it feels. I think it could be fine.

**Comment by erwinmombay** [comment]
closed by https://github.com/ampproject/amphtml/pull/2632
