### ISSUE TITLE
Allow font CDN stylesheets to be placed in body to avoid render blocking

### ISSUE THREAD

**Issue by westonruter** [ampproject/amphtml#25803]
When adding a font stylesheet (such as Google Fonts), AMP requires that it be placed in the `head`. This has the effect of making the stylesheet render-blocking, and Lighthouse will often complain about this:

> ![image](https://user-images.githubusercontent.com/134745/69776323-9b5f6e80-1150-11ea-8fdf-be36c4393125.png)

This is in spite of [font-stylesheet-timeout.js](https://github.com/ampproject/amphtml/blob/master/src/font-stylesheet-timeout.js) forcing render-blocking stylesheets to be made asynchronous. See also https://github.com/GoogleChrome/lighthouse/issues/10046.

Nevertheless, stylesheet `link` tags placed in the `body` now [no longer block rendering](https://jakearchibald.com/2016/link-in-body/). Therefore, could not the need for `font-stylesheet-timeout.js` be avoided?

Essentially, the change could be just this:

* Only run `font-stylesheet-timeout.js` on stylesheets in the `head`.
* Update the validator to allow font stylesheets anywhere (either the `head` or the `body`).

In diff form:

```diff
diff --git a/src/font-stylesheet-timeout.js b/src/font-stylesheet-timeout.js
index d5e1cfe82..2986e96a1 100644
--- a/src/font-stylesheet-timeout.js
+++ b/src/font-stylesheet-timeout.js
@@ -62,7 +62,7 @@ function maybeTimeoutFonts(win) {
     // Find all stylesheets that aren't loaded from the AMP CDN (those are
     // critical if they are present).
     const styleLinkElements = win.document.querySelectorAll(
-      `link[rel~="stylesheet"]:not([href^="${escapeCssSelectorIdent(
+      `head > link[rel~="stylesheet"]:not([href^="${escapeCssSelectorIdent(
         urls.cdn
       )}"])`
     );
diff --git a/validator/validator-main.protoascii b/validator/validator-main.protoascii
index 9622c57ac..a05ffe71c 100644
--- a/validator/validator-main.protoascii
+++ b/validator/validator-main.protoascii
@@ -309,7 +309,6 @@ tags: {
   tag_name: "LINK"
   spec_name: "link rel=stylesheet for fonts"
   named_id: LINK_FONT_STYLESHEET
-  mandatory_parent: "HEAD"
   attr_lists: "nonce-attr"
   attrs: { name: "async" }
   attrs: { name: "crossorigin" }  # SRI attribute (https://www.w3.org/TR/SRI/)
```

**Comment by choumx** [comment]
Looks like this is now [documented by whatwg](https://html.spec.whatwg.org/multipage/semantics.html#allowed-in-the-body) but still curious about:

1. Is the Firefox workaround in Jake's article is still necessary?
2. How do smaller-share AMP-supported browsers like UC handle `<link>` in body?

Related: #22995

**Comment by choumx** [comment]
Looked closer at font-stylesheet-timeout.js. If we make this change, it may remove the small font block period (250ms or whatever the UA decides for `font-display: swap`) which can increase risk of FOUC. 

It seems that having a "very small" font block period is desirable in most cases though, so we should first discuss whether this is a desirable change to begin with. It's not clear to me that it is.

**Comment by choumx** [comment]
Closing in favor of a bug fix in Lighthouse: https://github.com/GoogleChrome/lighthouse/issues/2832#issuecomment-560940332.

**Comment by paulirish** [comment]
Based on https://github.com/ampproject/amphtml/issues/25803#issuecomment-560566740 it sounds like these stylesheets are indeed render blocking. 

Given that, I believe Lighthouse is correctly flagging these requests.
