### ISSUE TITLE
The attribute 'access-hide' may not appear in tag 'amp-accordion > section'.

### ISSUE THREAD

**Issue by jdalk** [ampproject/amphtml#25807]
I'm not sure, whether it is actually a bug or wanted behavior.
Therefore I form a question:

I have an amp-accordion with sections that need to react on return-values from amp-access.
This is working. Shows and hides are done.

But I get the validation error:
"The attribute 'access-hide' may not appear in tag 'amp-accordion > section'."

Is it intended, that amp-access visibility-controll is not allowed in amp-accordion. If yes. Why?

If not. Can someone please reproduce the behavior and change vaidation rule.

Thanks in advance
Jan

**Comment by wassgha** [comment]
I couldn't find a rule that specificially prohibits this other than the fact that `[data-expand]` is the only allowed attribute on `amp-accordion > section` other than the standard attributes. It might help if you could provide an example for this use case and if it's a valid request we can allowlist it.

/cc @nainar

**Comment by jdalk** [comment]
Hi wassgha,

this code
```
<amp-accordion expand-single-section disable-session-states>
    <section amp-access="NOT nwPlus" access-hide>
        <h2 class="accordion-header">Web-Abo <span class="show-more">&#9207;</span><span class="show-less">&#9206;</span></h2>
        <div>***</div>
    </section>
    <section amp-access="NOT nwPlus" access-hide>
        <h2 class="accordion-header">Tagespass<span class="show-more">&#9207;</span><span class="show-less">&#9206;</span></h2>
        <div>***</div>
    </section>
    <!-- LOGIN-Form -->
    <section amp-access="NOT loggedIn" amp-access-hide>
        <h2 class="accordion-header">Login<span class="show-more">&#9207;</span><span class="show-less">&#9206;</span></h2>
        <form id="loginform-overlay" class="text-center" method="post" action-xhr="" target="_top" on="submit:loading-spinner.show;submit-success:loginform.hide,loading-spinner.hide,logoutform.show">
            <input id="my_user" type="text" name="my_user" maxlength="50" size="20" placeholder="Benutzername o. E-Mail" required>
            <input id="my_pass" type="password" name="my_pass" maxlength="50" size="20" placeholder="Passwort" required>
            <a href="/profil/?pid=7" class="password-forgotten">Passwort vergessen?</a>
            <input id="loginbutton" class="btn-primary text-center" type="submit" value="Anmelden">
        </form>
    </section>
</amp-accordion>
```
yields this error-message:
"The attribute 'access-hide' may not appear in tag 'amp-accordion > section'."

Seems, that amp-access in section is not white-listed ... :-/

**Comment by jdalk** [comment]
Hello wassgha,

sorry to push here. Is it ment to be like there must not be amp-access in amp-accordion section?
If so, I will try to go another way.

Thanks a lot
Jan

**Comment by nainar** [comment]
Seems reasonable to me.
