### ISSUE TITLE
Validation : add amp-brid-player component

### ISSUE THREAD

**Issue by DarXector** [ampproject/amphtml#2580]
Please add `amp-brid-player` component to validation. Pull request: [2438](https://github.com/ampproject/amphtml/pull/2438)

Thank you,
Marko.

**Comment by dvoytenko** [comment]
@Gregable ping on eta...

**Comment by Gregable** [comment]
Sounds good. 

@DarXector , do you want any validation rules for any of the `data`- attribute values? It looks like they are all numerical in the example, I can validate that, something else, or allow any values. The benefit of validation is nice error messages for developers running validation inside toolchains. Any thoughts?

**Comment by DarXector** [comment]
Yes, they will be strictly numerical for a foreseeable future. So you can add that validation.

**Comment by Gregable** [comment]
Validation added, but it'll take a week or so before this will go live.

**Comment by dvoytenko** [comment]
That's good. The code itself is scheduled to go to PROD end of next week.

**Comment by Gregable** [comment]
<amp-brid-player> validation is now live everywhere. It'll hit javascript in roughly an hour.
