### ISSUE TITLE
Intent to implement: `amp-ad` type for AdServSolutions

### ISSUE THREAD

**Issue by adservsolution** [ampproject/amphtml#25806]
Hi,
I intend to implement an amp-ad type for @AdServSolutions (advertising company)

Actually, I have already completed the implementation and signed a CLA so I will send a pull request along shortly.

Thanks,
John

**Comment by adservsolution** [comment]
@amp-pr-deploy , where is "Create a test site" button located? I don't get http://prntscr.com/q4xovz

**Comment by tarasmatokhniuk** [comment]
All checks have passed! May you merge this pull request, please?
