### ISSUE TITLE
[A11Y] Replace `.i-amphtml-screen-reader` for relevant AMP components

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#25820]
The [`i-amphtml-screen-reader`](https://github.com/ampproject/amphtml/blob/master/css/ampshared.css#L164-L194) class makes it possible to provide a11y-specific elements to assistive technologies that are critical for completing user journeys. It does so by creating effectively "invisible" buttons that are tiny and in the top left corner, such as this declared "Previous" button in the following `amp-carousel`:
![A9JVOK50B8V](https://user-images.githubusercontent.com/10456171/69992580-f6f67700-1517-11ea-9ff6-de041cad4df7.png)

While this is typically used in AMP components where buttons are useful for engaging with content via screen reader and otherwise have no visual placement on the page, it is also being used generally for components who may have more logical placements for them. In the example above, for instance, the buttons might be more appropriately located where and sized how arrows on an `amp-carousel` might typically be:
![02E8tNTF4sm](https://user-images.githubusercontent.com/10456171/69992821-8865e900-1518-11ea-9c1a-dcbec117aca8.png)

[`amp-base-carousel`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-base-carousel/0.1/amp-base-carousel.css#L62-L72) is able to provide accessible action buttons by circumventing this helper class and instead hiding elements visually while still exposing them to assistive technologies via `opacity: 0` and `pointer-events: none`. 

For the following components, we need to assess if there is more suitable placement for SR-specific navigational elements using the `i-amphtml-screen-reader`, investigate if they might be better served by removing the helper class in favor of the alternative described, and make changes accordingly:

- [x] `amp-carousel 0.1`
- [ ] `amp-carousel 0.2`
- [ ] `amp-lightbox-gallery`
- [ ] `amp-sidebar`
- [ ] `amp-mega-menu`
- [ ] `amp-image-lightbox`

related: b/145232689

**Comment by aghassemi** [comment]
`pointer-events: none` likely won't work for TalkBack and VoiceOver as those ATs actually dispatch `tap` events at x,y coordinates of buttons (instead of running the attached event handlers like desktop ATs do)

**Comment by sparhami** [comment]
> `pointer-events: none` likely won't work for TalkBack and VoiceOver as those ATs actually dispatch `tap` events at x,y coordinates of buttons (instead of running the attached event handlers like desktop ATs do)

From my testing, they both ignore `pointer-events: none`. Looking at a performance trace, Chrome dispatches a click, it doesn't go through the hit test when using Talkback to activate an element, which is what I assume `pointer-events` modifies. I assume that VoiceOver is doing the same (or similar).

**Comment by caroqliu** [comment]
`amp-carousel` status update:

#26069 intends to replace utilization of the `i-amphtml-screen-reader` class on `amp-carousel` with a new `i-amphtml-carousel-hide-buttons` attribute for `amp-carousel 0.1`. However `pointer-events: none` is not effective on slide advance "buttons" because they are attached as `div[role=button]` elements rather than first class `button` elements. We explored the following options to be able to go forward with the change:

Option 1: 
- Replace `i-amphtml-screen-reader` class on the buttons in `amp-carousel 0.1` with an `i-amphtml-carousel-hide-buttons` attribute on the `amp-carousel`.
- Only when hiding an `amp-carousel > div[role=button]`, generate a new `amp-carousel > button` that is invisible to mouse users and usable via screen reader.

Option 2: 
- Replace `i-amphtml-screen-reader` class on the buttons in `amp-carousel 0.2` with an `i-amphtml-carousel-hide-buttons` attribute on the `amp-carousel`.
- Replace instances of `amp-carousel > div[role=button].amp-carousel-button-prev` with `amp-carousel > button.amp-carousel-button-prev`.

Option 3: 
- Bump `amp-carousel` to version `0.3` that is based on `0.1` with the modification that swaps out `amp-carousel > div[role=button].amp-carousel-button-prev` with `amp-carousel > button.amp-carousel-button-prev`. This is not an option for `0.1` without a small version bump because it is suspected that that change would break too many instances of usage.

Resolution: We intend to go with Option 1 as this is the least invasive towards existing usage.

/cc @ampproject/wg-ui-and-a11y @sparhami @kristoferbaxter
