### ISSUE TITLE
I2I: amp-next-page v2

### ISSUE THREAD

**Issue by wassgha** [ampproject/amphtml#25826]
## Summary

This is the second phase of #25500 , proposes a second version of the `amp-next-page` component that breaks the initial API in order to allow for true infinitely scrolling AMP documents as well as substantial fixes to the initial extension.

## Design document

[Design document](https://docs.google.com/document/d/1tsCEo6UW5G6HmQn8eOvLNwuHKpfbxcWyxNgSIBuXThU/edit?usp=sharing)

## Motivation

The status quo is that `amp-next-page` v1 is launched as doc-level opt-in only (but is significantly in usage) and only provides next document loading up to three "next documents". Demand dictates a truly infinite document loading experience as well as multiple fixes to the extension and a simpler API (see #24889 ). Since the API changes would be breaking (and given that `amp-next-page` v1 never launched in a production ready state), it might be appropriate to launch as v2 (either `0.2` or `1.0`) once all issues are fixed and the API is final.

## Additional context

More context in the [design doc](https://docs.google.com/document/d/1tsCEo6UW5G6HmQn8eOvLNwuHKpfbxcWyxNgSIBuXThU/edit?usp=sharing), the [master issue](https://github.com/ampproject/amphtml/issues/25500) and an external contribution at #24889 . Partially started implementation under #25636 .

## Launch tracker
[Launch tracker](https://docs.google.com/spreadsheets/d/1EacJaTs6o7KXTzXVnq9iPwzVco6DBD8cjNPcHFQSeyM/edit?usp=sharing)

**Comment by davidstrauss** [comment]
Can you please make this design document accessible to the public?

**Comment by davidstrauss** [comment]
The launch tracker document appears to need a publicly accessible version as well.

**Comment by kristoferbaxter** [comment]
I was able to access the design document from a non-logged in account, was this changed after design review?

**Comment by wassgha** [comment]
I had an issue with my amp.dev account but I was able to resolve it right before the meeting. No worries though, I'll continue working on this and implement changes if needed after the next meeting.
