### ISSUE TITLE
Make amp-analytics sendBeacon non-blocking

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#25827]
as found by @kristoferbaxter , the native browser API `sendBeacon` can block UI thread for ~10ms (on a desktop machine) when the return value is used. Example here:

https://lavender-jumpsuit.glitch.me/

![Screen Shot 2019-12-02 at 12 23 55 PM](https://user-images.githubusercontent.com/8496897/70004230-708f6480-151a-11ea-81a8-e3116395eab7.png)

![Screen Shot 2019-12-02 at 12 24 12 PM](https://user-images.githubusercontent.com/8496897/70004263-7e44ea00-151a-11ea-971e-b7fb08336ee3.png)

Currently, `amp-analytics` takes the return value to make sure the beacon request was queued successfully. If not, it will fallback to other `transport` options such as XHR post or img tag. According to the `sendBeacon` [spec](https://www.w3.org/TR/beacon/), the return value can be `false` when:
> If the amount of data that can be queued to be sent by keepalive enabled requests is exceeded by the size of transmittedData, set the return value to false and terminate these steps.

https://github.com/ampproject/amphtml/blob/1705bff3d52b198f23e91342412c44b4ca0ae2b6/extensions/amp-analytics/0.1/transport.js#L115-L126

That said, if we want to get rid of the 10ms delay, we will have a small risk of not sending out the request due to an over crowded queue. (Not sure if it can happen in practice).

Thoughts? @kristoferbaxter @dvoytenko @zhouyx

**Comment by dvoytenko** [comment]
Can we file this with Chrome to get their opinion on what's up with that. I'd think queuing is needed to avoid exactly this kind of issues...

**Comment by zhouyx** [comment]
Agree that we should reach out to the Chrome team to get their opinion. 

Notes from offline discussion with @kristoferbaxter. In the meanwhile, a good improvement on the AMP side is to not use sendBeacon but fallback to use xhr before DOMContentLoaded (except the `documentExit` case). So the delay on the UI thread doesn't affect First Input Delay.

**Comment by dvoytenko** [comment]
Yes, we might have to do that. But I'd still like someone to file a Chrome issue. This might be completely unexpected on their side and could lead to a faster prioritization.

**Comment by zhouyx** [comment]
Here is the newly filed Chrome issue https://bugs.chromium.org/p/chromium/issues/detail?id=1032316

**Comment by zhouyx** [comment]
We've verified this is a Chrome issue with devtools only. No action item on the AMP side. Closing the issue.
