### ISSUE TITLE
amp-auto-ads not working on canonical AMP

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#25845]
A couple of users reported that their AdSense auto ads stopped working on their AMP pages since 11/12/2019. 

The issue was reproduced [here](https://www.learnengineering.org/working-of-a-limited-slip-differential.html). The response from AdSense auto ads server print this error:
> [amp-auto-ads] No ad placements found for publisher ID 'ca-pub-***'. Check that the provided publisher ID is correct.

The issue has been reported to Google AdSense team and got confirmed by them. They're working on a fix. 

Will post here for any updates we got from them.

**Comment by eduardogoncalves** [comment]
I'm having this issue here too at https://www.saibatudomt.com.br/

```
log.js:244 [amp-auto-ads] No ad placements found for publisher ID 'ca-pub-8168441694441175'. Check that the provided publisher ID is correct.
```

**Comment by KrashTime** [comment]
I'm having this issue here too at https://tobruxo.com.br/

**Comment by chojnicki** [comment]
Same here, any info?

**Comment by lannka** [comment]
Although the root cause is at AdSense server side, we cherrypicked a client side work around to mitigate the issue last Friday. I was told that with this change, sites with higher traffic will likely get recovered sooner. A full fix at server side will come in January.

**Comment by levyblue** [comment]
I am having the same problem. Any idea when a fix will be provided?

**Comment by lannka** [comment]
@levyblue could you also provide a link to reproduce the issue?

**Comment by levyblue** [comment]
Sure, the issue is happening on my [personal finance blog](https://personalfinance.leblonblue.com/)

**Comment by xiekun09** [comment]
I'm having the same issue, my website is https://www.yourzodiacsign.com.
amp-auto-ads worked on this website before, but now it can't work.

**Comment by megane9988** [comment]
I'm having the same issue too.
https://megane-blog.com/

**Comment by levyblue** [comment]
Hello team, does anyone have an update on this issue?

**Comment by bishrulhaq** [comment]
I'm still having the issue, :(

**Comment by eduardogoncalves** [comment]
Hello team, does anyone have an update on this issue?

**Comment by flixwatchsupport** [comment]
Having similar issues on my website - https://www.flixwatch.co/
Some of the sample pages are- 
https://www.flixwatch.co/movies/hush/
https://www.flixwatch.co/country/usa/
https://www.flixwatch.co/lists/100-best-movies-on-netflix/

**Comment by gacontre** [comment]
Following this. having the same issue.
[amp-auto-ads] No ad placements found for publisher ID 'ca-pub-

**Comment by gacontre** [comment]
> Although the root cause is at AdSense server side, we cherrypicked a client side work around to mitigate the issue last Friday. I was told that with this change, sites with higher traffic will likely get recovered sooner. A full fix at server side will come in January.

January is almost over. any progress on this? please advise

**Comment by gacontre** [comment]
Try this?

https://isabelcastillo.com/auto-ads-amp-wordpress

**Comment by flixwatchsupport** [comment]
> Try this?
> 
> https://isabelcastillo.com/auto-ads-amp-wordpress

Have you tried it? It's from 2018 and no recent comments on the post.

**Comment by eduardogoncalves** [comment]
Hi @lannka, any updates to share with us?

**Comment by lannka** [comment]
@eduardogoncalves just pinged AdSense team again. I will update here once heard back from them.

**Comment by vazgen** [comment]
I still see this issue even with configuration. https://www.w3docs.com/ad-network-config.js
I want to show ads as a sibling of `main div.code-snippet` for example on page https://www.w3docs.com/learn-git/git-clone.html.
Also, it is not clear should we use 
```
{
  "placements": [
    {
      "anchor": {
        "selector": "MAIN",
        "sub": {
          "selector": "DIV.code-snippet",
        }
      },
      "pos": 4,
      "type": 1,
      "style": {
        "top_m": 5,
        "bot_m": 10
      }
    }
  ]
}
```
or 
```
export default {
  "placements": [
    {
      "anchor": {
        "selector": "MAIN",
        "sub": {
          "selector": "DIV.code-snippet",
        }
      },
      "pos": 4,
      "type": 1,
      "style": {
        "top_m": 5,
        "bot_m": 10
      }
    }
  ]
}
```

**Comment by eduardogoncalves** [comment]
We need attention with this issue, maybe this isn't important do AdSense team, but for AMP we can lose publishers using AMP Canonical/AMP First, because who uses AMP Canonical/AMP First are losing tons of AdSense money and soon will stop using and investing in AMP.

/ping @lannka

**Comment by changoz** [comment]
same issue [here](https://www.zip-codes.me/). 
Opened a ticket with Google Adsense yesterday, waiting their reply.

**Comment by rsimha** [comment]
> /ping @lannka @rsimha

Unfortunately, I don't work on ads, and don't have any context for the cause of this issue. Will leave it to someone from @ampproject/wg-ads to post an update.

**Comment by eduardogoncalves** [comment]
@rsimha 😳 Sorry, my mistake. I Saw a picture of you in some commit related to amp-auto-ads, but now I saw that was unrelated.

**Comment by tlong2** [comment]
@eduardogoncalves sorry for the delay on this; it's taking longer to fix than we hoped. It is important to us and we're working on it.

There's some complexity in ensuring that our backend system pickups the correct URLs to analyze for the case of canonical AMP. For various reasons that has not been as simple to solve as we had hoped.

Thanks for your patience, and sorry again for the time this is taking.

**Comment by powerivq** [comment]
@eduardogoncalves 

Google ads team (@tlong2 ) would provide updates on the server-side fix.

**Comment by nvFede** [comment]
Hello, I have the same problem on this site: https://buenavibra.es/

Anyone has a solution for this ? 

[amp-auto-ads] No ad placements found for publisher ID 'ca-pub-2XXXXXXXX. Check that the provided publisher ID is correct.

**Comment by megane9988** [comment]
Thanks my blog was fixed. 
Auto Ad is displayed. 

I didn't change my code.  
Probably I think someone fixed this issue from google.
https://megane-blog.com/

**Comment by lannka** [comment]
The issue should have been fixed at AdSense side. Close now.

**Comment by tobiastromm** [comment]
Hi. I am having this exactly problem.

[amp-auto-ads] No ad placements found for publisher ID 'ca-pub-xxx'. Check that the provided publisher ID is correct.

Can someone tell me how to fix?

**Comment by ashishguptastar** [comment]
same issue on my website [http://nielitexams.com/](url)

**Comment by infoAnew** [comment]
Experiencing this issue in July 2020 on this new site: [infoAnew.com](https://infoanew.com). 

`[amp-auto-ads] No ad placements found for publisher ID 'ca-pub-9705598290828550'. Check that the provided publisher ID is correct.` I noticed that the `ca-` prefix is not displayed when I look at the publisher ID in Google Analytics. So I'll try dropping the prefix and see if that helps.

**Comment by infoAnew** [comment]
> Experiencing this issue in July 2020 on this new site: [infoAnew.com](https://infoanew.com).
> 
> `[amp-auto-ads] No ad placements found for publisher ID 'ca-pub-9705598290828550'. Check that the provided publisher ID is correct.` I noticed that the `ca-` prefix is not displayed when I look at the publisher ID in Google Analytics. So I'll try dropping the prefix and see if that helps.

Dropping the  `ca-` prefix did not help. AdSense instructs you to use it. Under the error above I see additional info:
`[amp-auto-ads] No placements in config` and, `[amp-auto-ads] unable to fulfill ad strategy`. I'm guessing the config has to be present and will try create it.

**Comment by rolero** [comment]
We have exactly the same issue here: https://www.bizzlibrary.com/Template/NH281/acceptable-encryption-policy/
