### ISSUE TITLE
GitHub release tags sometimes missing pull requests

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#25858]
This might be a known issue but I noticed one of my PRs was missing from the release tag despite it showing in the commit list.

```
[amp-ad] Add a4a (fast fetch) support to myTarget amp-ads (#25130) 
Enable 'remove-viewer-query-params-on-navigate' in prod. (#25586)
Disable sidebar close animation on iOS back (#25250)
```

https://github.com/ampproject/amphtml/commits/1911191835190

```
[amp-ad] Add a4a (fast fetch) support to myTarget amp-ads (#25130)
Disable sidebar close animation on iOS back (#25250)
```

https://github.com/ampproject/amphtml/releases/tag/1911191835190

/cc @estherkim FYI since I think you were planning to work on this.

**Comment by estherkim** [comment]
Thanks! I'll take a look.

**Comment by choumx** [comment]
🎉
