### ISSUE TITLE
Change tagName of story info dialog and story social share menu

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#25855]
This will help with analytics as their tagnames will be easier to identify and track.

**Comment by newmuis** [comment]
@Enriqe can you elaborate on what needs to be done here?  What should they be changed to?

**Comment by Enriqe** [comment]
Sure, with the recent change (#25787), we now support tracking "openable" and "closeable" elements such as the info dialog and the social share. 

We will allow publishers to track these specific elements by specifying a `tagName` in the config. So for example, publishers can track the opening of an `amp-story-page-attachment` by doing this:

```
"trackPageAttachmentOpen": {
    "on": "story-open",
    "tagName": "amp-story-page-attachment",
    "request": "url"
},
```

Problem is, since the story info dialog and the story share menu are a `<div>` and an `<a>` tag respectively and the `tagName` property of an element is read-only, I introduced an [ANALYTICS_TAG_NAME](https://github.com/ampproject/amphtml/pull/25787/files#diff-892ff6b93efdc55aac93e5d622e65f01R167) that maps to the `tagName` that the publisher will specify (e.g. `amp-story-info-dialog`) in the config. This way, we are able to map the config's tagName with the analytics tag name, if that makes sense.

By changing the info dialog and share menu's HTML tag to something like `<amp-story-info-dialog>` and `<amp-story-share-menu>`, we wouldn't have to go through the `ANALYTICS_TAG_NAME` approach mentioned above. Does this make sense?

**Comment by newmuis** [comment]
Got it, thanks!

But, does this mean that going forward, every internal thing that we want to make trackable needs to have a custom element?

**Comment by Enriqe** [comment]
If by internal you mean amp-story-specific, then I think it makes sense to do so, yes.

More general web-development things like clicks in <a> tags can continue to work as they do today with amp-analytics.

/cc @gmajoulet for any thoughts

**Comment by newmuis** [comment]
Sorry, by internal, I mean not just publisher-specified components like amp-story-bookend or amp-story-page-attachment, but also things we define ourselves, like the info dialog or share menu.

**Comment by Enriqe** [comment]
Oh, I think it also makes sense too, since I don't see any drawbacks?
