### ISSUE TITLE
Need to Add support to 3rd party JS, added to "approved" list

### ISSUE THREAD

**Issue by Liron-Gigya** [ampproject/amphtml#2586]
Please walk through the following steps for reporting an issue about AMP:

- Please ask general questions about AMP over on stackoverflow under the AMP HTML tag: http://stackoverflow.com/questions/tagged/amp-html
- Please ask/post questions/problems related to Google Search in Google's AMP forum: https://goo.gl/utQ1KZ

## Short description of your issue:

Start by deleting everything above this including this sentence :)

## How do we reproduce the issue?

Please post a public URL and ideally post a reduced test case. E.g. on jsbin.com that exhibits only your issue and nothing else.

1. Step 1 to reproduce
2. Step 2 to reproduce
3. …

## What browsers are affected?

All browsers? Some specific browser? What device type?

## Which AMP version is affected?

Is this a new issue? Or was it always broken? Paste your AMP version. You can find it in the browser dev tools.

**Comment by Liron-Gigya** [comment]
My understanding is that AMP does not support 3rd party JS.
Can you add an option to get our JS approved by Google for inclusion on AMP pages?

**Comment by rudygalfi** [comment]
@Liron-Gigya -- Can you describe your 3rd party use case in more detail?

**Comment by Liron-Gigya** [comment]
Hi Rudy,

Our customers need to include Gigya JS as described here
<http://developers.gigya.com/display/GD/Global+Conf+JS>. Unless you will
add Gigya to the "approved" 3rd party list, Gigya will not be able to
provide a library to support Google AMP

Thanks!
Liron

On Tue, Mar 15, 2016 at 8:24 PM, Rudy Galfi <notifications@github.com>
wrote:

> @Liron-Gigya <https://github.com/Liron-Gigya> -- Can you describe your
> 3rd party use case in more detail?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ampproject/amphtml/issues/2586#issuecomment-196960407>
>

-- 
Gigya <http://www.gigya.com/> | The Leader in Customer Identity Management
2016 CRM Watchlist Winner 
<http://www.zdnet.com/article/and-the-winners-of-the-2016-crm-watchlist-are/>

**Comment by rudygalfi** [comment]
Given we have an offline conversation on this, let's close this for now and re-open once that thread has progressed.

**Comment by gpirie** [comment]
Was this progressed at all?

We use Gigya for our single sign-on implementation and looking to integrate with AMP.

**Comment by Liron-Gigya** [comment]
Hi Graeme,

Which company do you work for? Who is your AM? We can continue this through
SF.

Thanks!
Liron

**Comment by grantkemp** [comment]
HI @Liron-Gigya we have a customer who is looking at this- did you manage to progress.
