### ISSUE TITLE
WebP Detection for CSS background images

### ISSUE THREAD

**Issue by kevincolten** [ampproject/amphtml#25874]
## Describe the new feature or change to an existing feature you'd like to see

Be able to detect WebP broswser support, similar in functionality to Modernizr feature detection. Simply adds a `.no-webp` or `.webp` on the `body`. This will help with using `.webp` images as CSS `background-image`s

## Describe alternatives you've considered

You could possibly have a webp image stacked on top of a non-webp image using html elements so that the image would load as fast as the browser can support, but this would still load both images on supported browsers.

**Comment by wassgha** [comment]
Hello @kevincolten , have you considered using [fallback images](https://amp.dev/documentation/components/amp-img/#example:-specifying-a-fallback-image)? I understand that this is not as clean as css switched `background-images` but does it at least work as a temporary fix?

**Comment by kevincolten** [comment]
We use those quite extensively, but that won't work as elegantly for image backgrounds with text overlays. Maybe using absolute positioning but that becomes a pain to maintain.

**Comment by wassgha** [comment]
Hey @kevincolten , another quick fix to get the behavior you want is to put an `amp-img` with a webp source and a fallback at the same level in the DOM tree as one of the ancestor of the element you want to style with a `background-image`, once the `amp-img` falls back to the non-webp image, it will get a `amp-notsupported` class added to it. You can then use that as a sort of alternative to a media query for browsers that don't support `webp`.
Here's a working example I made for this workaround https://jsbin.com/hayaqociko/edit?html,output
/cc @kristoferbaxter

**Comment by kristoferbaxter** [comment]
Hi there,

Would you be interested in a server solution as well? Responding to an image request with WebP versus JPG/etc based on request headers?

**Comment by kevincolten** [comment]
@wassgha Whoa, this worked beautifully! I created 1px by 1px transparent images called `amp.png` and `amp.webp`

```html
<style>
.webp-test {
  position: absolute;
}

.bg-img {
  background-image: url('image.webp');
}

.webp-test.amp-notsupported + .bg-img {
  background-image: url('image.png');
}
</style>

<amp-img
  class="webp-test"
  alt="webp test"
  width="1"
  height="1"
  src="amp.webp"
>
  <amp-img
  	class="webp-test"
  	alt="webp test"
  	width="1"
  	height="1"
  	fallback
  	src="amp.png"
  ></amp-img>
</amp-img>

<div class="bg-img">
	Some overlay text
</div>
```

@kristoferbaxter My AMP projects are mostly static sites without a way to put logic on a server, but that would be great as a middleware package for something like node/express.

**Comment by wassgha** [comment]
@kevincolten glad that worked out, I'll keep this issue open to see if there's more interest in native support for this feature without a workaround, although I'm not very supportive of using a class on the `body` element to do this.
