### ISSUE TITLE
🌸 Cherry pick request for #25875 into 1911191835190 (Pending)

### ISSUE THREAD

**Issue by zombifier** [ampproject/amphtml#25878]
# Cherry-pick request

|       Issue       |       PR       | Production?  |     RC?      | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :----------: | :----------: | :-----------------------------------------------------------------------------: |
| #25875  | #25875 | **NO** | **YES** |                               #25680                                |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

Saw regression in ad queries for inabox after the launch of inabox-viewport-friendly.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

| Users affected                                   | Impact                                                                       |
| ------------------------------------------------ | ---------------------------------------------------------------------------- |
| <_Which users were affected? Roughly how many?_> | <_How were users affected? E.g. partial or complete loss of functionality?_> |

## Root Causes

1.

## Action Items

| Action Item                   |               Type               |     Owner     |      PR #      |
| ----------------------------- | :------------------------------: | :-----------: | :------------: |
| <_E.g. Add integration test_> | <_Investigate/Mitigate/Prevent_> | @<_USERNAME_> | #<_PR_NUMBER_> |

### Things that went well

-

### Things that went wrong

-

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by lannka** [comment]
/cc @cramforce for approval
note this is a regression on canary.

**Comment by rsimha** [comment]
@lannka A clarifying note about labels (since I added them just today): The canary and RC cherry-pick labels always go hand in hand because we now release to RC whenever we release to Canary. (The reason they are separate labels is because we didn't have an RC release until early this year, and I wanted to go back in time to study how many canary-only cherry-picks we had in 2018.)

**Comment by lannka** [comment]
thanks @rsimha for clarifying. this cherrypick is a bit unusual as it only cherrypick inabox RC (inabox does not have canary). what should we do here?

**Comment by rsimha** [comment]
I see. In that case, I retract my statement, and agree that there's still a valid use case for cherry picking to RC but not canary.

**Comment by cramforce** [comment]
Approved

**Comment by lannka** [comment]
Cherrypicked to inabox RC
