### ISSUE TITLE
🌸 Cherry pick request for #25856 into 1912032225230 (Approved)

### ISSUE THREAD

**Issue by micajuine-ho** [ampproject/amphtml#25885]
|       Issue       |       PR       | Production?  |     RC?      | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :----------: | :----------: | :-----------------------------------------------------------------------------: |
| #25856  | #25857 | **No** | **Yes** |                               #25861                       |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

Publishers will not be able to rely on server-side user consent decision for amp-consent as intended. 

## Summary

Publishers need to send us user consent decision from their server (to stay in sync) using `expireCache` and `consentStateValue` (so that we would never have local storage and always ping them). We were treating the update and clearing as mutually exclusive, so it would not allow publishers to stay compliant with opt-in regulations. 

| Users affected                                   | Impact                                                                       |
| ------------------------------------------------ | ---------------------------------------------------------------------------- |
| Publishers implementing server-side opt out consent flow | New amp-consent would not work as documented for server-side opt out flow  |

## Root Causes

1. Treating `expireCache` and `updateCacheIfNotNull` as mutually exclusive

## Action Items

| Action Item                   |               Type               |     Owner     |      PR #      |
| ----------------------------- | :------------------------------: | :-----------: | :------------: |
| Change expire and sync flow  | Prevent | @micajuine-ho | #25857 |

## Lessons Learned

- Make sure spec lines up with code

### Things that went well

- Knew about the issue, knew about the fix.

### Things that went wrong

- 

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by lannka** [comment]
Note that this is a canary cherrypick.

**Comment by cramforce** [comment]
Approved

**Comment by zhouyx** [comment]
#25857 is merged.
