### ISSUE TITLE
Clarify developer / amp errors

### ISSUE THREAD

**Issue by diantekyrie** [ampproject/amphtml#25883]
## Describe the new feature or change to an existing feature you'd like to see

Have the java console make it more noticeable if it's an AMP or Client Error.

## Describe alternatives you've considered

At the moment the only way to really check and see if the issue is related to AMP is to ask the developers if its our issue.

## Additional context

1. This [page](https://www.google.com/amp/s/amp.cnn.com/cnn/politics/live-news/impeachment-hearing-12-04-19/index.html) displays am `HTTP Error 404` for the amp-app-banner. This is not an AMP issue.
![Screen Shot 2019-12-04 at 2 33 00 PM](https://user-images.githubusercontent.com/48487406/70187428-02c27480-16a3-11ea-8b29-30b8280ebf44.png)

2. This [issue](https://www.google.com/amp/s/pagesix.com/2019/12/03/gabrielle-unions-stylist-addresses-reports-her-hair-was-too-black-for-agt/amp/) displays that its looking for the `amp-carousel` element, however there is no `amp-carousel` on the page.
![Screen Shot 2019-12-04 at 2 35 36 PM](https://user-images.githubusercontent.com/48487406/70187715-bd527700-16a3-11ea-8abd-a75f2bba3e7c.png)

**Comment by sparhami** [comment]
There are a few places where we display errors due to developer misuse or issues with an endpoint for a network request in the console, which can be confusing when testing AMP, since you need to look about it and reason about whether or not AMP has a problem itself.

**Comment by caroqliu** [comment]
Closing this issue as it does not have clear action items for resolution. Perhaps related and more comprehensive discussion can occur in one of these threads: #32739, #27408, #8018
