### ISSUE TITLE
Validation: The attribute 'cite' may not appear in tag 'q'.

### ISSUE THREAD

**Issue by briangbell** [ampproject/amphtml#2590]
When validating a page with #development=1 I get the following error:
The attribute 'cite' may not appear in tag 'q'.

The tag in question is used like this, which is valid markup:
`<q cite=URL>`

**Comment by Gregable** [comment]
Thanks for the report. 

This tag/attr pair is actually allowed in the latest version, but it may be a week or two before we can roll it out everywhere. In the meantime, I'm letting the developer console errors continue to show it to avoid confusion. If you want to ignore these messages your pages will soon validate, just not quite yet.
