### ISSUE TITLE
amp-ad size 0x0 is rendered, which is not expected behavior

### ISSUE THREAD

**Issue by renebaudisch** [ampproject/amphtml#25906]
## What's the issue?

amp element with size 0 should not be laid out, so no iframe is expected behavior,
but iframes get's inserted instead.

## How do we reproduce the issue?

https://adtechnology.axelspringer.com/demopages/2019/amp.html 
(modified/stripped copy of ads.amp.html example page)

## What browsers are affected?

Doesn't seem to matter.

## Which AMP version is affected?

1911191835190

**Comment by powerivq** [comment]
Make sense, but wanna understand what the use case is for having width or height be 0? Should it be deemed invalid instead?

**Comment by powerivq** [comment]
Make sense, but wanna understand what the use case is for having width or height be 0? Should it be deemed invalid instead?

**Comment by renebaudisch** [comment]
Yes, but also when using layout="nodisplay" instead amphtml didn't generate an iframe. Maybe since this is not intended for amp-ad tags?

**Comment by powerivq** [comment]
layout=nodisplay means you can have something toggle it so it shows. Do you have an example where width/height=0 would be useful?

**Comment by renebaudisch** [comment]
This tag is meant to work as a setup/config node so there will be no content to display. 

If there would be a way to use a json script tag like for amp-consent for an amp-ad tag, I would prefer that way, but the config information has to be valid for the same domain as the amd-ad iframes and I think a json config for amp-ad also is not accessible at the moment.

**Comment by powerivq** [comment]
I tested again on `http://localhost:8000/examples/ads.amp.html?type=springAds` and it is no longer laying the iframe out, therefore I am closing this issue. Feel free to reopen if you find this not being the case.
