### ISSUE TITLE
🌸 Cherry pick request for 25917 into 1912050134470 (Pending)

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#25919]
# Cherry-pick request

|       Issue       |       PR       | Production?  |     RC?      | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :----------: | :----------: | :-----------------------------------------------------------------------------: |
| #25917 | #25917 | **NO** | **YES** |                               #25861                                |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

This is a regression in canary that broke A4A Spam detection. The spam detection iframes got injected inside the ad iframe window instead of parent window.

# Mini-postmortem

## Summary

| Users affected                                   | Impact                                                                       |
| ------------------------------------------------ | ---------------------------------------------------------------------------- |
| 1% canary users | AMPHTML Ads spam detection not functioning on AMP pages |

## Root Causes

The regression was introduced here:
https://github.com/ampproject/amphtml/pull/25769/files#r354981761

## Action Items

| Action Item                   |               Type               |     Owner     |      PR #      |
| ----------------------------- | :------------------------------: | :-----------: | :------------: |
| Add e2e test | Prevent | @lannka  | #25921 |

### Things that went well

- Caught by Google ads integration tests

### Things that went wrong

- Could have been caught eariler

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by dvoytenko** [comment]
Approved

**Comment by lannka** [comment]
Done
