### ISSUE TITLE
Incident report: Google Search viewer is unable to connect to an AMP document

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#25924]
Incident date: 2019-12-03
Incident resolved: 2019-12-03 17:00 PST

Manifestation:
Visually: Ads were blocked, amp-access was very slow.
JavaScript error: "No messaging channel: initMessagingChannel"

What happened:
A bug in the Google Search viewer was preventing the viewer from establishing the messaging link. Thus the viewer was unable to switch a document from the "prerender" state to "visible".

Why wasn't this problem not found earlier:
The "No messsaging channel" was mistagged as a user (expected) error, which are not monitored the same way as other errors.

Resolution:
Retag "No messaging channel" as a dev error. See https://github.com/ampproject/amphtml/issues/25923.

**Comment by dvoytenko** [comment]
The issue has been resolved.

**Comment by jeffjose** [comment]
Thank you for debugging and fixing the issue.
