### ISSUE TITLE
<frame> or <iframe> elements do not have a title (Lighthouse says)

### ISSUE THREAD

**Issue by machal** [ampproject/amphtml#25934]
When testing my clients' AMP page, Google Lighthouse says: "<frame> or <iframe> elements do not have a title".

![image](https://user-images.githubusercontent.com/16641/70431817-20feea80-1a7e-11ea-9667-fae9dc6c5bf7.png)

The problem is with `<iframe>` generated inside `<amp-ad> element:

![image](https://user-images.githubusercontent.com/16641/70431887-4e4b9880-1a7e-11ea-9abe-38e73a291af3.png)

This `<iframe>` is automatically generated by AMP Cache? Is there a way to solve it on our side?

**Comment by sparhami** [comment]
The iframe looks to be created by amp-ad, but there are various other places in amp that also create iframes that we should look at.

**Comment by sparhami** [comment]
Not sure if we should add a default title to all ad iframes, but it seems like we should allow developers to specify titles on the `<amp-ad>` element itself (via some attribute, perhaps `title`), to be set on the iframe created for the ad to allow for localizing and customizing the accessibility message.

**Comment by lannka** [comment]
Is this mainly for accessibility? Agree. We can have a default title for our ad bootstrap frame `frame.html`. Publishers already has the option to use their own bootstrap frame if they want to customize the title.

**Comment by lannka** [comment]
I guess I mixed up `title` attribute versus `<title>` element in the iframe.

Seems accessibility is counting on the iframe `title` attribute.
We already pass down `title` attribute from amp-ad element to its iframe element. 
@machal  could you just try to add a title attribute to your amp-ad element?

**Comment by machal** [comment]
@machal Will try it, thanks!
