### ISSUE TITLE
Release names should be an enum, not free strings

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#25937]
A recent change to release names in a build script caused a breakage in ad reporting in canary. Fortunately the impact was minimal, impacting only canary, and is resolved by #25914 . Tests were updated to reflect the name change, but they do nothing to protect against similar issues in the future.

One contributor to this bug was the fact that valid release names are treated as free strings in `amphtml`, and as such there is no validation on what is used and it's harder to track down uses and make changes.

It would be ideal if release names existed as an enum type, which could be used in the few places  that reference them. This would pave the way for #25560 to be addressed with reduced risk, since the actual string values of the enum type could be altered (or temporarily duplicated with a second identifier of the same-value) without needing to update where it's used.

**Comment by rcebulko** [comment]
Before I touch this @ampproject/wg-infra do you see any issues with this/have any particulars to call attention to?

**Comment by rsimha** [comment]
This is a good idea.

One thing we'd need to make sure of is that the release flavors continue to be represented as strings when they are written to `AMP_CONFIG` in `v0.js` and other files. In other words, we should make sure that `v0.js` still contains `"type":"production"` and not `"type":RELEASE_FLAVOR_PRODUCTION`, etc.

**Comment by rcebulko** [comment]
```javascript
const RELEASE_FLAVORS = Object.freeze({
  PRODUCTION: 'production',
  ...etc
});
```
and then throughout the code

```javascript
...
"type": RELEASE_FLAVORS.PRODUCTION
```

Would that not work?

**Comment by rcebulko** [comment]
Where should something like this live? I'm not too familiar with the structure of `amphtml`. Something standalone like `src/releases.js`? Is that accessible from `ads`?

**Comment by rsimha** [comment]
I'd imagine this should live somewhere in `src/`. I think it can be added to `src/mode.js`, which contains other AMP config related stuff, but we should check with @ampproject/wg-runtime in case they have a better idea.

**Comment by jridgewell** [comment]
Only freeze it in dev mode, please.
