### ISSUE TITLE
Document Ad resizing rules

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#2594]
Document which iframe resizing rules apply to Ad resizing. If they are the same - we can consider merging this part of the doc or simply referencing one from the other.

/cc @Meggin @coreybyrnes

**Comment by jasti** [comment]
@dvoytenko I have an example here for ads that you may find helpful : http://dfp-amp-testing-1185.appspot.com/amp_tests/dfp-image-resize.html

**Comment by dvoytenko** [comment]
Thanks, @jasti !

**Comment by sriramkrish85** [comment]
@dvoytenko - resizing is already documented here - 
https://github.com/ampproject/amphtml/tree/master/ads#ad-resizing

do we need to add something?

**Comment by dvoytenko** [comment]
@sriramkrish85 cool, thanks!

@coreybyrnes how does this look? https://github.com/ampproject/amphtml/tree/master/ads#ad-resizing

**Comment by rudygalfi** [comment]
@coreybyrnes Please give feedback when you get a chance. Closing this since it seems like it's addressed.

**Comment by coreybyrnes** [comment]
In my opinion the documentation isn't clear on what will allow a resize to occur or not. From my testing it seems a resize will always occur if triggered by user interaction or if triggered automatically and the ad is above or below the viewport. It seems if the resize is triggered automatically (from within the ad code) and the ad is within the viewport that the resize will always fail. I feel like simply replacing the word "whether" with "if" in the documentation would make it much more clear.
