### ISSUE TITLE
🌸 Cherry-pick request for #25754 into #1912061958420 (Approved)

### ISSUE THREAD

**Issue by ChrisAntaki** [ampproject/amphtml#25945]
# Cherry-pick request

|       Issue       |       PR       | Production?  |     RC?      | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :----------: | :----------: | :-----------------------------------------------------------------------------: |
| #25754 | #25901 | **NO** | **YES** |                               #25861                                |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

I think this issue meets the criteria because it does "break existing AMP web pages in a significant way". It affects users with the latest version of iOS who visit PWAs using AMP's shadow DOM library along with the `amp-subscriptions` plugin. Essentially, `amp-subscriptions` click delegation is broken in that scenario, due to a change in how the latest version of mobile Safari is bubbling up events when a `shadowRoot` has a `body` property. 

## Summary

This issue affects users with the latest version of iOS who visit PWAs using AMP's shadow DOM library along with the `amp-subscriptions` extension. Essentially, `amp-subscriptions` click delegation is broken in that scenario, due to a change in how the latest version of mobile Safari is bubbling up events when a `shadowRoot` has a `body` property. 

| Users affected                                   | Impact                                                                       |
| ------------------------------------------------ | ---------------------------------------------------------------------------- |
| Users of latest iOS (13.2.3+) on PWA pages using AMP shadow DOM with `amp-subscriptions` extension  | Buttons handled by `amp-subscriptions` like "Login" aren't working

## Root Causes

1. Change in event bubbling in latest version of mobile Safari

## Lessons Learned

We need automated tests for the AMP shadow DOM + `amp-subscriptions` that cover the latest mobile Safari versions as soon as they're available, in my opinion. Otherwise users or third party developers will be the ones to report issues like this, right?

### Things that went well

- Quick response and resolution time

### Things that went wrong

- We had to rely on users catching the issue.

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers @jpettitt @wassgha @gilbertococchi @iwoak

**Comment by wassgha** [comment]
Thanks for filing the cherry-pick! assigning @rsimha who is on duty

**Comment by rsimha** [comment]
The on-duty calendar was incorrect (I've fixed it). Assigning to @newmuis who is actually on duty this week.

**Comment by newmuis** [comment]
Ping @ampproject/cherry-pick-approvers 

Should we hold 1912061958420 (#25861) from going out until this is in?  If we want to get data with the cherrypick in, it would delay the release pretty late at this point.  Or should we release 1912061958420 and also cherrypick this into production?

**Comment by choumx** [comment]
I don't see how the cherry-pick PR changes would affect performance so I think it's safe.

Note that we now have @samouri's beta dashboard which can get perf data after a couple hours.

**Comment by dvoytenko** [comment]
Approved.

**Comment by rsimha** [comment]
This is part of https://github.com/ampproject/amphtml/releases/tag/1912120230490.
