### ISSUE TITLE
🐛amp-story videos + analytics can make tab unresponsive

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#25954]
## What's the issue?

Using videos in amp-story along with video percentage reporting in amp-analytics will sometimes cause infinite recursion. This happens when the `video.duration === NaN` causing this bit of code to call itself over and over freezing the tab
https://github.com/ampproject/amphtml/blob/17f0ce3798a4ca3de1b2b9ff6f54352fa80810e2/src/service/video-manager-impl.js#L1489-L1501

I am unsure of the exact root cause but @alanorozco hypothesizes that it has something to do with the interaction between media pool and the video-manager-impl not having the right ref (correct me if I am wrong).

## How do we reproduce the issue?

If you use this example page and click around a lot eventually you will see the behavior
https://gist.github.com/calebcordry/27935d46744b79ce36d33bfeaea189f9

Note: the infinite recursion is protected by a `devAssert` when built locally, but not in prod

## What browsers are affected?

I think all?

## Which AMP version is affected?

Prod going back at least a few weeks. Likely much longer.

**Comment by calebcordry** [comment]
cc/ @ampproject/wg-stories 

I am working on adding a protection here to fix the symptom but not necessarily the root cause. Coming soon.

**Comment by alanorozco** [comment]
Freeze has been worked around by #25956 and I'll do some sleuthing to find the root cause. This might be affecting more players.
