### ISSUE TITLE
Support aliases for AMP element 

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#25967]
3rd party service providers can integrate AMP by introducing its own AMP extension, like `amp-youtube`, or reusing an existing extension, like `amp-ad type=taboola`.

For maintainability, AMP encourages the latter option. However, most service providers would prefer the former approach for branding purposes. 

Here we propose a syntax to declare element aliases:

```html
<head>
  ...
  <script async custom-element="amp-ad" 
          element-aliases="amp-taboola amp-triplelift" 
          src="...amp-ad-1.0.js">
</head>
<body>
  <amp-taboola>
  </amp-taboola>
  <amp-triplelift>
  </amp-triplelift>
</body>
```

In the above example, the `amp-ad` extension will read `element-aliases` and register all those aliases.

Validator will keep valid alias mappings

@ampproject/wg-approvers

**Comment by Gregable** [comment]
There would need to be a registry of allowed aliases, otherwise someone would try, for example, to register `<script>` tag:

```
  <script async custom-element="amp-ad" 
          element-aliases="script" 
          src="...amp-ad-1.0.js">
```

And just in general to avoid conflicts. How would you avoid naming conflicts with AMP components? For example, it appears there is a registered ad network called "pixels". Would this be `<amp-pixels>`?

**Comment by lannka** [comment]
Yep, validator should hold the accounting book. 

for naming conflicts, first come first serve ...

**Comment by lannka** [comment]
@ampproject/wg-runtime @ampproject/wg-ui-and-a11y for comments

**Comment by sparhami** [comment]
Some UI components recognize others by their tag names, so aliasing might be a problem, for example, for `amp-ad`:

https://github.com/ampproject/amphtml/blob/67d14150f01f6e9f457077d53e04b4dd4e425003/extensions/amp-a4a/0.1/amp-a4a.js#L482-L486

https://github.com/ampproject/amphtml/blob/67d14150f01f6e9f457077d53e04b4dd4e425003/extensions/amp-loader/0.1/amp-loader.js#L314-L316

https://github.com/ampproject/amphtml/blob/67d14150f01f6e9f457077d53e04b4dd4e425003/extensions/amp-lightbox-gallery/0.1/amp-lightbox-gallery.js#L1377-L1381

There are quite a few other usages as well for `amp-ad` and for other extensions. Would need to have a strategy for handling these cases. Some extensions also refer to their own tag in the CSS in selectors, which wouldn't work for these (they could be migrated to use a class instead, but it would change selector specificity, and would be a breaking change).

**Comment by lannka** [comment]
Thanks @sparhami . I wasn't thinking of an auto-migration for existing extensions, as you pointed out, it can be breaking changes.

The proposal is mostly for new integrations.

**Comment by dvoytenko** [comment]
I'm curious if it'd be a big deal for us to simply declare an extension, even if it's mostly a fork of an existing one with 1-2 attributes different?

**Comment by lannka** [comment]
@dvoytenko for example I still want all the affiliate link vendors to share the same extension amp-link-rewriter, but with the flexibility to tag the page using: amp-skimlinks, amp-smartlinks, amp-amazon-onetag etc.

**Comment by choumx** [comment]
Related: #9143

**Comment by dvoytenko** [comment]
@lannka Ok, I think this could work. This should be brought up in design review in case anyone might see some unintended problems.

**Comment by cramforce** [comment]
Just wanted to note that I'm quite unconvinced of the need.

**Comment by lannka** [comment]
> Just wanted to note that I'm quite unconvinced of the need.

@cramforce I remember in my "new vendor integration guideline" design review, you mentioned that `amp-foo type=bar` was generally a bad start. we should have started with `amp-foo-bar`. Or did I mis-understand?

**Comment by cramforce** [comment]
I don't think there is a difference with that respect if the
implementations are generic and the alias nature needs to be hard coded in
every document.

**Comment by alanorozco** [comment]
One more data point.

@ampproject/wg-ui-and-a11y often gets PRs for video player components when authors could be using `amp-video-iframe` instead. The vendors' interest often lies in having a) a branded component and b) defining their own set of attribute parameters for URL config.

We've been considering using `amp-video-iframe` to synthesize aliased components with simple mapped configuration, which would reduce our cost of maintenance and keep vendors happy (we could apply this aliasing to existing players too, hence reducing the cost of maintaining those as well).

**Comment by cramforce** [comment]
amp-video-iframe is a bit of a different situation. There is genuine
benefit for a vendor of video players to have a first class extension.
amp-video-iframe is for the case where a publisher has a custom video
player.

**Comment by alanorozco** [comment]
> There is genuine benefit for a vendor of video players to have a first class extension.

@cramforce In theory, yes. And for some of our players this is true. But most implementations in practice follow a subset of the same playback actions via the same mechanism, just with different "glue". For these cases, we could just build configuration for that glue, and via aliasing, specific features for that player can be added later as its own component if needed.

**Comment by alanorozco** [comment]
(Also, sorry if I was unclear before. For this idea we wouldn't employ `amp-video-iframe` as-is, they would actually be used via the same component-attribute API as current 3p players. It might even be a separate implementation but it's the same concept under the hood with nicer APIs.)
