### ISSUE TITLE
amp-list: race condition for a sequence of quick `src`attr mutations.

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#25961]
**summary**

When hooking up `amp-bind` with `amp-list` where we mutate the bound `[src]` attribute, it is possible to enter a race condition where the rendered items are for the previous state.

Imagine a shopping cart with categories for women's/mens clothing:
1. Default page to land on is women's clothing, and this endpoint takes 1s to resolve.
2. User quickly clicks a the tab for men's clothing, and this only takes 200ms.

It is possible that the promise for loading data from (1) will end up resolving after (2). This leads to the jarring UX of having "Men" selected and yet seeing Women's clothing.

One can reproduce this in [AMP Camp](https://github.com/ampproject/samples/tree/master/amp-camp): https://camp.samples.amp.dev/product-listing?gender=women&category=shirts.

cc @choumx @morsssss

**Comment by morsssss** [comment]
Once you mentioned this to me, I was able to reproduce it pretty easily too!

I couldn't figure out a way to fix it in AMP Camp. Which doesn't mean that @choumx might not already have a special way...

**Comment by samouri** [comment]
This is now fixed! And with no changes to AMP Camp necessary 🎉 .

**Comment by morsssss** [comment]
Wow!

One more thing that AMP takes care of for me automatically :)
