### ISSUE TITLE
[amp-youtube] Add Click-to-play overlay for amp-youtube docs

### ISSUE THREAD

**Issue by eduardogoncalves** [ampproject/amphtml#25976]
Add an example of how to set up a [custom poster image/Click-to-play overlay](https://amp.dev/documentation/examples/multimedia-animations/click-to-play_overlay_for_amp-video/)  at amp-youtube's docs (https://amp.dev/documentation/components/amp-youtube/),

**Comment by esng25** [comment]
Seconded. I've been trying to use on="tap:videoElementID.play" It preloads and buffers the video but doesn't start playing. The user has to click the play button again which seems extremely counter-intuitive.
