### ISSUE TITLE
New analytics tool configuration for "Memo"

### ISSUE THREAD

**Issue by bradkagawa** [ampproject/amphtml#25979]
## Summary

Adding implementation configuration for analytics tool Memo (memo.co)

## Motivation

New integration for existing analytics product that does not have native AMP support yet.

## Additional context

Typical web integration is done via on-page JavaScript.

/cc @ampproject/wg-approvers

**Comment by jeffjose** [comment]
Thanks for the I2I. If you havent seen already, heres the integration guide for analytics - https://amp.dev/documentation/guides-and-tutorials/contribute/integrate-your-analytics-tools/

Please feel free to create a PR when you're ready to submit.
