### ISSUE TITLE
amp-analytics does not accept query string parameters with 2 _'s in them

### ISSUE THREAD

**Issue by mborof** [ampproject/amphtml#25981]
## What's the issue?

When using amp-analytics if I build a request that has a query string parameter with 2 _'s in it then amp-analytics does not generate any requests.  

For example, this generates an HTTP post:

const VENDOR_CONFIG = jsonLiteral({
  'requests': {
    // Variables
    'req' : 'https://pubads.g.doubleclick.net/subopt?',
  },
  triggers: {
    on: {
      'on': 'visible',
      'request': 'req',
    },
  'transport': {
    'beacon': true,
    'xhrpost': false,
    'image': false,
  },
});

And this does not generate an HTTP post:

const VENDOR_CONFIG = jsonLiteral({
  'requests': {
    // Variables
    'req': 'https://pubads.g.doubleclick.net/subopt?__amp_source_origin=${sourceHost}',
  },
  triggers: {
    on: {
      'on': 'visible',
      'request': 'req',
    },
  'transport': {
    'beacon': true,
    'xhrpost': false,
    'image': false,
  },
});

## How do we reproduce the issue?

1. Create a JavaScript file with the above in it inside the amp-analytics vendors folder.
2. Register the component in vendors.js  (remember the TYPE)
3. Add this tag to an amp page (filling in the TYPE):
<amp-analytics type="{TYPE}"
    data-credentials="include"
    credentials="include">
</amp-analytics>
4. Execute the page you added it to.  You should see a request generated without the __ query string param and not see one generated with it.

## What browsers are affected?

I was specifically testing in Chrome; I did not test other browsers.

## Which AMP version is affected?

This is the current version of AMP (as of 12/11/2019).  I have no seen this work previously (or tried).

**Comment by micajuine-ho** [comment]
Hi @mborof, thank you for your issue report. 

Are you still experiencing this issue? 

I tried to reproduce this issue, through both inline config as well as altering a vendor config, without any success.

**Comment by mborof** [comment]
Yes.  In this PR:

https://github.com/ampproject/amphtml/pull/26003

If I modify "subscriptions-propensity.json" so that _amp_source_origin= is instead __amp_source_origin I no longer get any amp-analytics HTTP requests from my propensity module.

**Comment by micajuine-ho** [comment]
@mborof Thanks for your follow up. 

The reason for this is that `__amp_source_origin` is not allowed as a parameter name and not that it has 2 leading underscores. See #4670 for more details.

**Comment by mborof** [comment]
Makes sense.  Closing.
