### ISSUE TITLE
AMP should respect ⚡️ apart from ⚡

### ISSUE THREAD

**Issue by tomayac** [ampproject/amphtml#25990]
Both ⚡️ and ⚡ look the same, but they're different:

```js
'⚡️'.length;
// 2
'⚡'.length;
// 1
'⚡'.charCodeAt(0) + ' ' + '⚡'.charCodeAt(1);
// "9889 NaN"
'⚡️'.charCodeAt(0) + ' ' + '⚡️'.charCodeAt(1);
// "9889 65039"
```
AMP respects the ⚡but rejects ⚡️, which is confusing since the macOS emoji picker creates ⚡️, that is, the representation with the [Unicode Variation Selector-16](https://unicode.org/cldr/utility/character.jsp?a=FE0F).

![amp-validator](https://user-images.githubusercontent.com/145676/70709427-2c9c1c80-1cdd-11ea-8e67-e045cbd167ed.png)

The AMP validator [checks](https://github.com/ampproject/amphtml/blob/a561d0e8be10c8996d9f3db6920f69ffffafd5d8/validator/engine/validator.js#L5366-L5395) for the presence of the representation without Variation Selector-16, but then [replaces](https://github.com/ampproject/amphtml/blob/a561d0e8be10c8996d9f3db6920f69ffffafd5d8/validator/engine/validator.js#L5303) it with `amp`, the same happens on the AMP cache. 

To avoid this confusion, AMP could potentially allow for both, ⚡️ and ⚡, and then just replace them with the textual attribute `amp`. 

More background on this bug: https://blog.tomayac.com/2019/12/12/same-same-but-different-unicode-variation-selector-16/.

**Comment by samouri** [comment]
I'm a fan.

> To avoid this confusion, AMP could potentially allow for both, ⚡️ and ⚡, and then just replace them with the textual attribute amp.

It would probably be best to accept _all_ variants of the lightning bolt instead of just two of them. That could involved either checking against all 16 possibilities or normalizing the attributes by removing all variant selectors (at least for the purpose of the bolt check).

**Comment by honeybadgerdontcare** [comment]
This should hit production by beginning of next week, but due to the holidays it may get delayed till beginning of next year.
