### ISSUE TITLE
amp-video and https

### ISSUE THREAD

**Issue by gcovato** [ampproject/amphtml#260]
Hi to all,

It is becoming a big issue for us the restriction that was applied on the urls of the video files supported by amp-video.

We have the majority of our video files on a video server that doesn't support the https urls.

Our plan was to create a amp-html version of all our articles on the server. Your restriction, applied from our point of view suddenly and without a pre clarification on the documentation, is making useless much part of our work.

We would like to ask to remove this restriction. Video files played by this component are files owned by the publishers. Why the component should check the real source using a certificate?

Thank you

Giuseppe

**Comment by dmlap** [comment]
Just stumbled on this-- I work at Brightcove. I'm getting a 404 on @gcovato's example page right now but would be happy to find the right person to review anything if it comes back up.

**Comment by gcovato** [comment]
@dmlap the repository was private. You should be able to access it now. I opened a support ticket  for getting the needed help.
