### ISSUE TITLE
Validator: include src in the script error messages

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#2600]
When available the script error message should include `src` value in
"The tag \'script\' is disallowed except in specific forms."

**Comment by dvoytenko** [comment]
As discussed, this can be just an extra field with the element's ID.

**Comment by rudygalfi** [comment]
Any updates on this?

**Comment by Gregable** [comment]
none so far

**Comment by Gregable** [comment]
@dvoytenko , the solution implemented is a little different than initially proposed, but it solves the same problem. If you add the attribute `data-amp-report-test` to a tag, any errors emitted regarding that tag will have a new field dataAmpReportTestValue which will contain the attribute value set in the document. 

Example:

`<!doctype lemur data-amp-report-test="foo">`
results in a validationResult object whose errors array looks like:
`errors[0].dataAmpReportTestValue === 'foo'`

**Comment by Gregable** [comment]
FYI, this will be visible on the cdn.ampproject.org validator in about an hour.

**Comment by lordzden** [comment]
You may also check this resource: [The tag ‘script’ is disallowed except in specific forms](https://asknoypi.com/accelerated-mobile-pages-validator/#script).
