### ISSUE TITLE
AMP analytics playground demo isn't working.

### ISSUE THREAD

**Issue by joshm33333** [ampproject/amphtml#26016]
AMP analytics playground demo isn't working.

Visited the following url in an incognito browser, iframe gives 500 error.

Visited on my iphone, same error.

Installed the code on my own site, same error.

Tried dealing with console errors by adding allow-same-origin, still no good.

Can anyone else replicate the issue?

https://playground.amp.dev/?url=https://preview.amp.dev/documentation/examples/components/amp-analytics

**Comment by caroqliu** [comment]
cc/ @ampproject/wg-analytics

**Comment by micajuine-ho** [comment]
Issue is tracked [here](https://github.com/ampproject/amp.dev/issues/3306)
