### ISSUE TITLE
Reporting more errors to the viewer

### ISSUE THREAD

**Issue by fstanis** [ampproject/amphtml#26012]
Currently, an AMP viewer may receive error data from the AMP page if the following conditions are met:
https://github.com/ampproject/amphtml/blob/2dd8c32b732714b7abf08d82d677803602167734/src/error.js#L372-L376

This is already a high bar as it requires access to modify the AMP code, a viewer capability and being trusted (or building your own runtime). However, even when all of these are met, due to throttling, the following may still prevent the error from being passed (based on [`onError`](https://github.com/ampproject/amphtml/blob/2dd8c32b732714b7abf08d82d677803602167734/src/error.js#L307) and [`getErrorReportData`](https://github.com/ampproject/amphtml/blob/2dd8c32b732714b7abf08d82d677803602167734/src/error.js#L459)):

*   If the page has any non-AMP JS, only 1% of the errors are reported.
*   If the error is a load error, a script error or the window is detached, only 0.1% of errors are reported.
*   If the error is a user error, only 10% of the errors are reported. 

## Describe the new feature or change to an existing feature you'd like to see

I propose we either move the throttling logic to server reporting (and thus let the viewer receive all errors) or add a viewer parameter that disables it. Also, I think we should consider removing the trusted viewer requirement, as this would help tools related to AMP development (see additional context).

## Describe alternatives you've considered

If building your own runtime, you could just change the throttling constants. However, they are currently a bit scattered, so this is not an easy thing to do.

## Additional context

The main aim here is to make it easier for email clients using AMP for Email to track errors in emails. If the runtime reports them to the viewer, no information is lost and the viewer is in a better position to setup logging and alerting.

In addition, it'd be useful for things like playground.amp.dev if we lift the trusted viewer and throttling restriction: this would allow these tools to surface errors to the users directly and help them debug AMP.

**Comment by caroqliu** [comment]
cc/ @ampproject/wg-runtime @samouri
