### ISSUE TITLE
Investigate preloading first story page assets

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#26022]
> Preloading Critical Resources In The First Page
> AMP Stories starts displaying content after AMP scripts have been fetched and evaluated, and then starts fetching content in a page. This means that sometimes media content could not display due to network latency.
> 
> Preloading critical resources can be a good idea to help displaying them soon. In our stories, images on the first page are critical resources. The images are preloaded by link element in HTML, and can be fetched before the AMP script has been executed.

From https://developers.cyberagent.co.jp/blog/archives/24105/

We should do some testing for different assets / cache context / network speed and consider doing these optimizations at the AMP Cache level while ingesting documents.

cc @ampproject/wg-stories

**Comment by gmajoulet** [comment]
Reassigning to @mszylkowski who has this on his roadmap.

**Comment by mszylkowski** [comment]
This is the experiment `story-load-first-page-only`
