### ISSUE TITLE
Intent-to-Deprecate-And-Remove: `AMP-Redirect-To` header in AMP4Email

### ISSUE THREAD

**Issue by zhangsu** [ampproject/amphtml#26030]
## Summary

The ["redirecting after a submission" feature of `amp-form`](https://amp.dev/documentation/components/amp-form/#redirecting-after-a-submission) should be banned in the AMP for Email spec.

### Proposal

Ban this feature in the AMP runtime for the email spec and update the spec documentation.

- [ ] Ban redirection in runtime
- [ ] Update AMP for Email spec documentation

## Motivation

Emails should never be able to redirect themselves to another URL for security reasons.

## Impact on existing users

This feature is currently already banned by various email clients implementing the AMP for Email spec (e.g., by filtering out the header in the form HTTP response). Banning this in the runtime ensures that the security guarantee holds for all future email clients as well.

## Alternative implementation suggestion for developers using AMP

Developers should not be able to redirect their emails.

/to @choumx 
/cc @ampproject/wg-amp4email
/cc @fstanis

**Comment by cramforce** [comment]
From my point of view this can just proceed if the thing that is being removed currently doesn't work.

**Comment by choumx** [comment]
LGTM
