### ISSUE TITLE
Validator: spec_url field is not supplied for every tag spec

### ISSUE THREAD

**Issue by westonruter** [ampproject/amphtml#26033]
In the [AMP WordPress plugin](https://github.com/ampproject/amp-wp) we want to [add more linkages](https://github.com/ampproject/amp-wp/issues/1420) between the internal validation tool and amp.dev. If someone is using a component in a way that violates its validator spec, then we'd want to link the user to the docs page for that component. However, the required `spec_url` is not supplied for all tag specs.

For example, let's say I put an `<amp-accordion>` on my page and inside of it I put a `<section>` which contains one single `<h2>`. This would violate the spec. But which spec? Specifically it would be the spec with the name `amp-accordion > section`, and and we'd want to link the user to https://amp.dev/documentation/components/amp-accordion/

However, there is no `spec_url` defined for this tag spec:

https://github.com/ampproject/amphtml/blob/2dd8c32b732714b7abf08d82d677803602167734/extensions/amp-accordion/validator-amp-accordion.protoascii#L67-L74

And so the Validator is not able to provide a “Learn More” link:

> ![image](https://user-images.githubusercontent.com/134745/70882811-bf5ee480-1f85-11ea-963f-2b89598193af.png)

The spec name for `amp-accordion` does have a `spec_url` defined, however:

https://github.com/ampproject/amphtml/blob/2dd8c32b732714b7abf08d82d677803602167734/extensions/amp-accordion/validator-amp-accordion.protoascii#L43-L62

When that tag spec is violated, a “Learn More” link is provided:

> ![image](https://user-images.githubusercontent.com/134745/70882765-9dfdf880-1f85-11ea-8027-ec0629dc91f4.png)

So why is https://amp.dev/documentation/components/amp-accordion not supplied as the `spec_url` for the `amp-accordion > section` tag spec as it is done for the `amp-accordion` tag spec? If the `spec_url` were supplied for every tag spec this would facilitate providing developers with important context for why it is invalid and where they can find proper usage information.

Can all of the tag specs be updated to supply the relevant `spec_url` for each?

**Comment by honeybadgerdontcare** [comment]
@westonruter we in the wg:caching team welcome PRs that improve the developer experience. It looks like you're working on one and we would appreciate anything that improves the developer experience.

**Comment by westonruter** [comment]
Ok great. I mainly wanted to know if there was a reason for the `spec_url` not being supplied for each tag spec. I'll work on a PR.

**Comment by Gregable** [comment]
This bug is stated as more of a question than a specific feature request. I'm not sure when we would consider it closed as a feature request. Since the question is answered, closing this.

**Comment by amedina** [comment]
This is more a bug report than a FR. Could we reopen and seek a solution? /cc @sebastianbenz
