### ISSUE TITLE
Showing behavioural UI to user on first few visits

### ISSUE THREAD

**Issue by ghelapratik** [ampproject/amphtml#26036]
**Problem ** 

The AMP Story users are often resorting to moving away from the intended TAP behavior like swipe. We need to find a way where the AMP Story users get a UI that hints them on tapping for 2-3 visits irrespective of which domain is serving the story 

**Solution ** 

AMP Project has an amp-story.js being loaded from amp project CDN. We can set a cookie from ampproject.org domain recording the number of visits to a story. If the user comes to the site for 1st time, the amp-story.js file can check the cookie containing visit number and then accordingly show the Tap UI

**Comment by newmuis** [comment]
We can't reliably use cookies for this across domains, but I agree with the high-level problem.  Leaving this open to track.

**Comment by gmajoulet** [comment]
This has been done in https://github.com/ampproject/amphtml/issues/27097
Tracked in https://github.com/ampproject/amphtml/issues/27828, to document the new `education` feature.
