### ISSUE TITLE
I2I: Remove amp-script's height constraint for DOM mutation

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#26047]
## Summary

amp-script currently has [several constraints with regard to DOM mutations](https://amp.dev/documentation/components/amp-script/#user-gestures):

> 1. Mutations are always accepted for five seconds after a user gesture.
> 2. The five second interval is extended if the author script performs a `fetch()` as a result of the user gesture.
> 3. Mutations are always accepted for amp-script elements with `[layout!="container"]` and height ≤ 300px.

This issue proposes removing the height restriction in the third point:

> 3. Mutations are always accepted for amp-script elements with `[layout!="container"]`.

## Motivation

amp-script's mutation constraints were conservatively designed to minimize content jumping on AMP pages. However, recent use cases (e.g. data journalism) found these constraints to be a blocking impediment. Loosening the constraints should increase usefulness.

The primary insight is that a similar constraint is not present in [amp-iframe](https://amp.dev/documentation/components/amp-iframe/), which has the same mutability properties.

This increases the risk of poorly implemented, large-sized amp-script elements causing content jumping on AMP pages. However, given the developmental overhead of `amp-script`, abuse cases should be limited (there are similar costs for bootstrapping an iframe for `amp-iframe`).

Note that behavior will remain unchanged for amp-script elements with `[layout="container"]`.

/cc @kristoferbaxter @dvoytenko @patrickkettner @sebastianbenz 
/cc @ampproject/wg-approvers

**Comment by dvoytenko** [comment]
The rationale sounds good to me. I'm ok with this change.

**Comment by sebastianbenz** [comment]
This is great news!

**Comment by cramforce** [comment]
I first missed the !=. Makes total sense to me.

**Comment by dvoytenko** [comment]
Per design review, I'd only like to discuss if anyone has concerns that this relaxation could pave way for interstitials abuse.

**Comment by morsssss** [comment]
🎉🎉🎉

When this goes through, we should make sure to update [the documentation](https://amp.dev/documentation/components/amp-script/)
