### ISSUE TITLE
Intent to implement: amp-timeline

### ISSUE THREAD

**Issue by anandvtk** [ampproject/amphtml#2604]
# Overview

In order for publishers to tell a story around a topic or person that has persisted for a long time it is useful for them to enhance their content with a timeline, which gives some background to it in a more visual and ordered way. A timeline allows publishers to list a series of events that have lead up to the article without having to include all of them in the article body. 

We envisage the AMP timeline being a series of boxes containing AMP components connected to a line that can also have text or images associated with them. A piece of lead text and image can also be supplied e.g.

![screenshot 2016-03-16 11 13 43](https://cloud.githubusercontent.com/assets/1099077/13810521/30d7cb64-eb68-11e5-9e6a-2d3e30547c3d.png)
# Usage

Make up of the component would look like this eg. :  

```
<amp-timeline>
    <header>
        <h2>Motorheads Lemmy: 1945-2015</h2>
        <amp-img class="main-image" src="" alt=""></amp-img>
    </header>
    <ul>
        <li class="item">
            <div class="card">
                <div class="content">
                    <h3 class="date">24 December 1945</h3>
                </div>
                <div class="content">
                    <div class="description">
                        <p>Ian Fraser &quot;Lemmy&quot; Kilmister is born in Stoke-On-Trent, UK. His nickname reportedly came from his younger wheeling and dealing days, when he would ask people “lemme borrow a fiver”. </p>

                        <p>Lemmy played in bands around the north of England as a teenager before moving to London in 1967, where he landed a job as a roadie for The Jimi Hendrix Experience. Hendrix, he later said, was a gentleman because he &quot;always stood up when a woman walked into the room&quot;.</p>
                    </div>
                </div>
            </div>
        </li>

        <li class="item">
            <div class="card">
                <div class="content">
                    <h3 class="date">1975</h3>
                </div>
            <div class="media">
                <amp-img class="image" src="" alt=""></amp-img>
                <i class="source"><strong>Motörhead - Lemmy Kilmister, Phil “Philthy Animal” Taylor and Eddie Clarke</strong> <a href="" target="_blank">Photo: Rex</a></i>
            </div>
            <div class="content">
                <div class="description">
                    <p>Lemmy is fired from Hawkwind after being arrested on drug charges, and forms a new band in London with drummer Lucas Fox (who is soon replaced by Phil “Philthy Animal” Taylor) and guitarist Larry Wallis (later replaced by Eddie Clarke).</p>
                </div>
            </div>
            </div>
        </li>
    </ul>
</amp-timeline>
```
# Behaviour

The Timeline will made up of a series of components , amp-img , amp-video and simple text (possibly to extend with social media extensions). The javascript for this component will ensure the grid will responsively collapse, see this for an example : 

http://cf-particle-html.eip.telegraph.co.uk/4ce2c8f9-65f4-4854-9769-38186e0b90d3.html

The component makes assumptions around class naming to drive customisation for each publisher.

**Comment by dvoytenko** [comment]
@anandvtk This looks pretty awesome. Couple quick questions:

1. Do you usually serve timelines as a separate article as here? Or as a "menu" to navigate to different articles?
2. What does JavaScript do here? Could this timeline be fully designed via CSS and media queries?
3. Is there some interactivity inherent in the timeline? E.g. transition to lightbox or similar?

**Comment by anandvtk** [comment]
@dvoytenko 

1. We normally embed them into an article to give it context , maybe we could also provide links to allow an onward journey to other pieces content/articles.
2. The javascript allows the grid view to cascade based on viewport size. We use Masonary to deal with the grid layout and to give a nice transition when collapsing the grid  
3. Not at present or though we envisage that pressing a timeline element could go to lightbox or setup a carousel of each element

**Comment by dvoytenko** [comment]
Thanks @anandvtk 

/cc @ericlindley-g @rudygalfi

**Comment by rudygalfi** [comment]
I think this is a really interesting custom element idea.

Can you speak more to the pieces that you think could be customizable? For instance, there's red (or maybe it's more plum) diamonds used to indicate the points on the timeline and there's a really specific format of having:

```
Header
-------------------<>
Description text
```

I'm wondering if any aspects of positioning would be flexible and more elaboration on these points would be helpful.

**Comment by anandvtk** [comment]
This component is not heavily customisable , but would maybe benefit from being able to left/right align the timeline and customise the points eg : 

<amp-timeline  alignment="<left/right>"  marker="<diamond, square circle>" >

The timeline revolves around “card” elements that provide the decorative CSS used as timeline markers.

Our existing setup creates the line and the marker using :before and :after styles:

The marker uses:
background-color, border, box-shadow and rotation to form the diamond. We could provide some alternative styles that could be used in the markup, or provide examples of how to customize yourself

**Comment by ericlindley-g** [comment]
@anandvtk

That sounds good—assuming that all the default text styles can be easily over-ridden with custom styles, we'll also want to support customization for

• the color of the line and marker that connect each entry to the central timeline
• the ability to use a custom shape as the marker (examples of how to customize is a great idea)


Related to the responsive behavior:
• If there were no animation on window resize, could this be done without JS? For performance, payload, and effort, I wonder if a simple refresh would be a good approach.
• Something to fix in the final implementation: I can resize my browser to a point where the layout breaks for a bit, before it jumps back into place again.

/cc @cramforce

**Comment by dandv** [comment]
Can http://timeline.knightlab.com/ be reused?

**Comment by dvoytenko** [comment]
@dandv It looks like http://timeline.knightlab.com/ works via iframes and thus they should work in AMP.

**Comment by ericlindley-g** [comment]
Closing ITI due to inactivity — please reopen if you're interested in picking it up again. Thanks!
