### ISSUE TITLE
An AMP component 'script' tag is present, but unused.

### ISSUE THREAD

**Issue by fricikoma** [ampproject/amphtml#26058]
Google Search Console keeps reporting this error for some of my AMP pages:
An AMP component 'script' tag is present, but unused.

These pages pass the ampproject validator but they keep failing the search console validator.

An example: [https://rgbcolorcode.com/amp/imperial-purple](https://rgbcolorcode.com/amp/imperial-purple)

**Comment by honeybadgerdontcare** [comment]
You may need to contact Google Search Console [support](https://support.google.com/webmasters/?hl=en#topic=9128571). The URL provided when processed on Search Console's [AMP Test](https://search.google.com/test/amp?id=ufouebHlaXg4L7UHeQU4Zw) shows it being Valid AMP.

**Comment by sushiltechvision** [comment]
An AMP component 'script' tag is present, but unused.
Sir, there is no ad on my site, yet I am having this problem, please help me
url https://blogseohelp.com/blogger-blog-me-seo-kaise-kare/
![amp error](https://user-images.githubusercontent.com/73654269/98245746-63cf8800-1f97-11eb-87f1-e23f062bee7e.JPG)

**Comment by fricikoma** [comment]
HiThis is the amp version of your site, not the one you validated: https://blogseohelp.com/blogger-blog-me-seo-kaise-kare/amp/Kind regards,Ferenc

    On Thursday, November 5, 2020, 03:18:23 PM GMT+2, sushil kumar <notifications@github.com> wrote:  
 
 


An AMP component 'script' tag is present, but unused.
Sir, there is no ad on my site, yet I am having this problem, please help me
url https://blogseohelp.com/blogger-blog-me-seo-kaise-kare/
