### ISSUE TITLE
How to make a menu in AMP?

### ISSUE THREAD

**Issue by juniorneo2** [ampproject/amphtml#2606]
Hi people,

I need make a menu in AMP like this http://mobile.nytimes.com/international/, but I don't know how to do in AMP. Someone can help me? I developed a custom tag of web components(polymer) but does not work.

**Comment by dvoytenko** [comment]
@juniorneo2 There are two approaches that frequently in use today:

1. `:focus` singling selector. In this case when button is focused, the CSS selectors trigger display of the menu.
2. `:target` selector. In this case you'd have a `<a href="#menu">` tag. Clicking on it, the `:target` selector can activate the menu.

These two approaches are rather complicated by `position:fixed` and scrolling bugs to support this easily across the browsers. So, to address this, we are working on #827 to support menus as a direct extension to AMP. Please follow that issue and I will close this one for now. Feel free to reopen if you have additional questions.

**Comment by juniorneo2** [comment]
@dvoytenko Thank you!

I have a last question. Can I use Web Components in my project AMP? Like Polymer

https://www.polymer-project.org/1.0/docs/start/quick-tour.html

Thank you.

**Comment by dvoytenko** [comment]
Nope. Not at this time. Even though they use a similar technology, they are currently separate. But if there are some things that you really like in that library and would like to have here - please do let us know.
