### ISSUE TITLE
Handle chrome:// links

### ISSUE THREAD

**Issue by archon810** [ampproject/amphtml#26061]
Similar to https://github.com/ampproject/amphtml/issues/11824, can AMP handle chrome:// links without flagging them?

Here's where the validation is done: https://github.com/ampproject/amphtml/blob/680499c2c973ab4c97efb314d1da2c4ac3bff3f3/validator/validator-main.protoascii#L1926.

These links aren't clickable in Chrome, but they're sometimes linkified by the sites to make right click url copying easier:
![image](https://user-images.githubusercontent.com/469543/71021505-5ffef280-20b3-11ea-813d-b557f0a562cf.png)

And they cause warnings:

![image](https://user-images.githubusercontent.com/469543/71021442-3ba31600-20b3-11ea-9c4e-06b096d29312.png)

Sample url with the issue: https://www.androidpolice.com/2019/07/17/15-tips-tricks-chrome-android-2019/.

**Comment by honeybadgerdontcare** [comment]
@ampproject/wg-security-privacy I don't see any issue with allowing the `chrome://` protocol, does anyone else?

**Comment by molnarg** [comment]
No objection.
