### ISSUE TITLE
Intercepting anchor links breaks CSS's :target

### ISSUE THREAD

**Issue by ehmorris** [ampproject/amphtml#2607]
[This function](https://github.com/ampproject/amphtml/blob/e33d632b50ac1075e0d3698dc2d369a072c36f0d/src/document-click.js#L91) intercepts anchor clicks and prevents anchor tags from pushing to the history stack. This seems to prevent CSS's `:target` pseudo class from working properly.

I couldn't find if there's a way around this interception.

## How do we reproduce the issue?

In [this repo](https://github.com/ehmorris/amp-anchor-tag-examples) I have two examples of pages that use CSS's `:target` class. One has AMP and the other doesn't.

#### The AMP example, with broken `:target` behavior

[The amp page](http://ehmorris.github.io/amp-anchor-tag-examples/amp-anchor-tags.html) behavior looks like this:
![licecap](https://cloud.githubusercontent.com/assets/654275/13822291/72574e1c-eb7b-11e5-9618-683b85e20478.gif)

Or like this, if the page is loaded with an anchor tag:
![licecap2](https://cloud.githubusercontent.com/assets/654275/13822293/740fce0a-eb7b-11e5-98d3-02a1c989498e.gif)

#### The non-AMP example, with working `:target` behavior

[The non-amp page](http://ehmorris.github.io/amp-anchor-tag-examples/non-amp-anchor-tags.html) behavior looks like this:
![licecap3](https://cloud.githubusercontent.com/assets/654275/13822560/83d92ae2-eb7c-11e5-9248-1e99e82395d4.gif)

Note that clicking the anchor links highlights the tag with that ID, and that it creates an entry in the page history.

## What browsers are affected?

This is at least present in:
- OSX Chrome 49.0.2623.87
- OSX Firefox 47.0a2
- OSX Safari 9.0.1 (11601.2.7.2)
- iOS Safari (iOS version 9.2)

## Which AMP version is affected?

1457112743399

**Comment by ehmorris** [comment]
cc @dvoytenko it looks like you worked on this

**Comment by erwinmombay** [comment]
i believe this is fix in #2520 which is currently in canary. we'll be cutting a production release tomorrow afternoon PST. @ehmorris can you see if opting into canary fixes it for you? 

to opt in go to cdn.ampproject.org/experiments.html and turn "dev channel" on. and test the page.

**Comment by mkhatib** [comment]
I confirm that opting into canary fixes this behavior.

**Comment by ehmorris** [comment]
Sick! Yes it seems like this is fixed in AMP version 1457721872758.
