### ISSUE TITLE
Disable Mouse/Keyboard focus to <amp-mathml/>

### ISSUE THREAD

**Issue by jwinkworth** [ampproject/amphtml#26082]
## What's the issue?
Issue #17039 removed the context menu from mathjax, which is the only reason keyboard/mouse focus is enabled by default.

With the menu now disabled, each mathjax instance is now inside dom flow with nothing to interact with. Screen readers will read the appropriate math content regardless of whether or not the focus is enabled.

Just as a user wouldn't expect to tab to random words within a paragraph, a user should not expect to tab to a math expression with no way to interact with it.

## Steps to reproduce
Open any AMP page with `<amp-mathml>` on a PC and click anywhere in the formula, or navigate the page via tab key.

## Proposed solution
As per the mathjax documentation, this fix can be implemented by setting
```
MathJax.Hub.Config({
	menuSettings: {
		inTabOrder: false
	}
});
```

## Additional context
There are many configuration features of Mathjax that authors may want to be able to set based on page context. Right now, none of these options are available, so any mechanism to control these config options would be appreciated.

**Comment by krdwan** [comment]
@jwinkworth Thanks for filing the issue.  We've just merged in the change to remove <amp-mathml> from tab-index so you should see that reflected in the components in ~week.

Regarding additional configurations for the mathjax library.  Would you mind filing an additional issue and letting us know which configurations you'd like to see?  Thanks!
