### ISSUE TITLE
amp-bind does not support a href with FaceTime protocol link

### ISSUE THREAD

**Issue by chickenham** [ampproject/amphtml#26098]
## What's the issue?

Using amp-bind, trying to populate the href attribute of an <a> tag with a FaceTime link produces an error:

```
%s: Expression evaluation error in \"%s\". %s amp-bind 'facetime:+' + userData.phone \"facetime:+1-463-123-4447\" is not a valid result for [href]. 
```

Note that constructing a URL in the same fashion with a sms: protocol works fine.

FaceTime links are documented here: https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/FacetimeLinks/FacetimeLinks.html#//apple_ref/doc/uid/TP40007899-CH2-SW1

## How do we reproduce the issue?

See this jsbin to repro: [https://jsbin.com/bokesot/edit?html,console,output](https://jsbin.com/bokesot/edit?html,console,output)

## What browsers are affected?

All browsers and devices

## Which AMP version is affected?

It was always broken AFAIK

**Comment by samouri** [comment]
Fixed in https://github.com/ampproject/amphtml/pull/27134
