### ISSUE TITLE
Can we deprecate `AMP-Same-Origin` header?

### ISSUE THREAD

**Issue by dreamofabear** [ampproject/amphtml#26093]
Would simplify implementation of data backends e.g. for amp-list. Completes #22136.

Context:
- https://github.com/ampproject/amphtml/issues/22136#issuecomment-567257937
- `b/29881817`

/cc @ampproject/wg-runtime

**Comment by choumx** [comment]
Looked into this a bit more and the recent Firefox change is actually unrelated (though might allow non-XHR POST in AMP). There's still a `Origin` header gap for same-origin XHR, which Chrome now follows as well:

> The Origin header is not set on Fetch requests with a method of HEAD or GET.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin

We'd need security approval that giving publishers guidance that "XHR GET must be idempotent" is sufficient before removing `AMP-Same-Origin`. Though I'm not sure why that wasn't always the case...

**Comment by choumx** [comment]
Tested on Chrome 79, Firefox 71, Safari 13, Edge 18, IE 11:
```
XHR+GET+SAMEORIGIN: No browser
XHR+GET+CROSSORIGIN: All browsers

XHR+POST+SAMEORIGIN: Chrome, Firefox, Safari, Edge
XHR+POST+CROSSORIGIN: All browsers

NOXHR+GET+SAMEORIGIN: No browser
NOXHR+GET+CROSSORIGIN: No browser

NOXHR+POST+SAMEORIGIN: Chrome, Firefox, Safari
NOXHR+POST+CROSSORIGIN: Chrome, Firefox, Safari
```

**Comment by choumx** [comment]
Conclusion is we can remove `AMP-Same-Origin` and enable NOXHR+POST if we offer an opt-in CSRF protection (e.g. CSRF tokens) for IE. The risk is that publishers will ignore IE and leave it vulnerable.
