### ISSUE TITLE
amp-carousel 0.1 swipe action overridden by Gmail swipe gesture

### ISSUE THREAD

**Issue by Nerone95** [ampproject/amphtml#26103]
# What's the issue?
When carousel's arrow icons fade out, if the app can swipe email, you change email in the inbox and you can't swipe the photo in the carousel

## How do we reproduce the issue?

The Email must contains a carousel

1) Open email in gmail App mobile
2) Wait until the carousel's arrows fade out
3) Try to swipe photo in the carousel left or right

Expected result:
I can change the photos in the carousel, swiping left and right

Actual result:
You swipe the email in the inbox, not the photos

https://drive.google.com/file/d/1--sXN5ovrx2NY2_V5wLavuWLD2Tdk8gW/view?usp=sharing

## What browsers are affected?

We reproduce it on Samsung Galaxy A8 (2018) 
App Gmail Mobile 4/12/2019 version

## Which AMP version is affected?

AMP for Email- App Gmail Mobile

**Comment by fstanis** [comment]
This is a known issue. [Gmail currently recommends](https://developers.google.com/gmail/ampemail/tips) always adding the `controls` attribute to ensure the controls don't fade away.

#25713 and #25714 is some discussion on a runtime fix for this, so I'll close this to continue there.
