### ISSUE TITLE
AMP4Email content jumping on user tap actions

### ISSUE THREAD

**Issue by RosSpa95** [ampproject/amphtml#26105]
## What's the issue?

Visualization bug on Gmail iOS app

## How do we reproduce the issue?

You can see the video in **Gmail App**.
When you click, all the email moves randomly

https://drive.google.com/file/d/1kZQNw9OsiVcmhODNOD1bSTM5fnPkKagP/view?usp=sharing

## What browsers are affected?

Gmail App, in iOS. Version: 13.3

## Which AMP version is affected?

the last one.

**Comment by caroqliu** [comment]
Thanks for filing this issue. Can you provide a minimal sample so we can investigate?

**Comment by Nerone95** [comment]
@caroqliu  you can open this? 
https://drive.google.com/file/d/1kZQNw9OsiVcmhODNOD1bSTM5fnPkKagP/view?usp=sharing


It is the same problem that i also found on ios.

**Comment by fstanis** [comment]
Can you provide us with the code used for this so we can reproduce?

**Comment by Nerone95** [comment]
Here, try carousel and sidebar:
[issue_amp_example.zip](https://github.com/ampproject/amphtml/files/4009479/issue_amp_example.zip)

Gmail App, in iOS. Version: 13.3

@fstanis

**Comment by Nerone95** [comment]
Here, try carousel and sidebar:
[issue_amp_example.zip](https://github.com/ampproject/amphtml/files/4009509/issue_amp_example.zip)

Gmail App, in iOS. Version: 13.3

@fstanis

**Comment by RosSpa95** [comment]
up

**Comment by UldisPF** [comment]
Have noticed the same issue thats outlined here, tested on around 12 iOS devices (iPhones and iPads with gmail app) - all have the same issue with "jumpy" content when AMPhtml element that dynamically is pressed (carousel or accordion blocks - radio buttons seem to be unaffected).

Whats more if I test other people made AMP4email examples they all have the same bug so it seems that its something global and not issue with the template code itself. 

Video recordings of behaviour - 3 different email examples tested, coded from completely different people. 
[RPReplay_Final1664193236.mov.zip](https://github.com/ampproject/amphtml/files/9652608/RPReplay_Final1664193236.mov.zip)
[RPReplay_Final1664193185.mov.zip]
(https://github.com/ampproject/amphtml/files/9652609/RPReplay_Final1664193185.mov.zip)
[RPReplay_Final1664193020.mov.zip](https://github.com/ampproject/amphtml/files/9652611/RPReplay_Final1664193020.mov.zip)


Code example where issue is noticed: 
[testAMP.html.zip](https://github.com/ampproject/amphtml/files/9652545/testAMP.html.zip)

**Comment by akshayadinesh** [comment]
@fstanis any update here? this issue is affecting ALL AMP emails on gmail, including the ones that google has created for Google Store, Pixel Buds/Google Store, etc. It's hurting our ability to send AMP emails because they're virtually unusable on mobile.

**Comment by alexandr-kazakov** [comment]
+1 This still is not solved

**Comment by Pe4all** [comment]
+1 This still is not solved
