### ISSUE TITLE
Style for input button on iOs Gmail App

### ISSUE THREAD

**Issue by Nerone95** [ampproject/amphtml#26104]
## Describe the new feature or change to an existing feature you'd like to see

We'd love to style the submit button on iOS Gmail App.

In our example:

CSS
```
button,input,select,textarea{font-size:100%;border-radius:0;white-space:initial;appearence:none;line-height:normal;cursor:default;}
button,.submit{width:auto;color:#ffffff;font-weight:bold;padding:10px 30px;background-color:#333333;border:none;text-align:center;max-width:100%;border-radius:0px;cursor:pointer;}
button:hover,.submit:hover{background-color:#3d3d3d;}
```

HTML
`<input class="submit" type="submit" value="CONFERMA">`

## Describe alternatives you've considered

We usually use this style to overwrite the standard iOS style: 

input {
    -webkit-appearance: none;
}

It doesn't work in this case.

## Additional context

See screenshots below:

Gmail App on Android Phone (Samsung A8)

![samsung](https://user-images.githubusercontent.com/51479683/71185636-1c0b1980-227c-11ea-9927-3e346cf7d1e4.jpg)

Gmail App on iPhone7  iOS 13.2.3

![iphone](https://user-images.githubusercontent.com/51479683/71185628-17defc00-227c-11ea-902e-94bfa0333573.png)

**Comment by fstanis** [comment]
This is a known issue and Gmail will add support for `-webkit-appearance` (and `appearance`) soon.

Please use [Gmail's support channels](https://developers.google.com/gmail/ampemail/support) for issues specific to Gmail in the future.

**Comment by fstanis** [comment]
Here's two workarounds for the interim, until this lands in Gmail:

1. Use `<button type="submit">My button</button>` instead of `<input type="submit" value="My button">`. `<button>` has less default styles then `<input>` on iOS so the only thing you'd need to override is `border`.

2. Override all of `background` (`background-color` seems to not be enough), `border` and `border-radius` if you use an `<input type=submit>`.

**Comment by Nerone95** [comment]
Does the form work correctly with both? <button type="submit"> or <input type="submit">? @fstanis

**Comment by fstanis** [comment]
Yes, `<button type="submit">My button</button>` is the same as `<input type="submit" value="My button">` when it comes to functionality. From [the WHATWG HTML standard](https://html.spec.whatwg.org/#attr-button-type-submit-state):

> ***Submit Button***
If the element has a form owner and the element's node document is fully active, the element must submit the form owner from the button element.

Also, I checked this in Gmail just now to be sure. :)

**Comment by Nerone95** [comment]
It would be useful to be able to also use `appearance: none;`, for the future!


But great support! Thanks so much

**Comment by fstanis** [comment]
Just a quick update, Gmail now supports `-webkit-appearance` and `appearance`.

**Comment by Nerone95** [comment]
perfect
thank you ;)
