### ISSUE TITLE
🌸 Cherry pick request for 25845 into 1912101856490 (Approved)

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#26118]
# Cherry-pick request

|       Issue       |       PR       | Production?  |     RC?      | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :----------: | :----------: | :-----------------------------------------------------------------------------: |
| #25845 | #26116 | **YES** | **NO** |                               #25987                                |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

amp-auto-ads is not returning ads for canonical AMP

## Why is a RC cherry-pick not needed?

RC cherrypick is not needed because this RC will never enter prod due to holiday release freeze.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

<_YOUR_SUMMARY_>

| Users affected                                   | Impact                                                                       |
| ------------------------------------------------ | ---------------------------------------------------------------------------- |
| <_Which users were affected? Roughly how many?_> | <_How were users affected? E.g. partial or complete loss of functionality?_> |

## Root Causes

1.

## Action Items

| Action Item                   |               Type               |     Owner     |      PR #      |
| ----------------------------- | :------------------------------: | :-----------: | :------------: |
| <_E.g. Add integration test_> | <_Investigate/Mitigate/Prevent_> | @<_USERNAME_> | #<_PR_NUMBER_> |

### Things that went well

-

### Things that went wrong

-

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by rsimha** [comment]
Approved via IM by @cramforce. Will let him confirm at leisure.

**Comment by rsimha** [comment]
Cherry-pick complete. https://github.com/ampproject/amphtml/releases/tag/1912201827130
