### ISSUE TITLE
amp-instagram video is not playing the video

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#2613]
## Short description of your issue:

amp-instagram does not play the video when the post contains a video

## How do we reproduce the issue?

https://jsbin.com/ruhiropeyo/1/edit?html,output

## What browsers are affected?

All browsers?

## Which AMP version is affected?

My AMP version is: 1457721872758

**Comment by kul3r4** [comment]
@sebastianbenz

**Comment by jridgewell** [comment]
The wrapper/cover image seem to be covering up the iframe...

**Comment by mkhatib** [comment]
Yes, this is due to not actually hiding the prerendered elements. The usecase was we don't need to hide it because it is the same one apparently this isn't true in case of a video :smile:  will work on a fix.
