### ISSUE TITLE
amp-script throws an illegal mutation error when setting state inside a callback

### ISSUE THREAD

**Issue by AndrewKGuan** [ampproject/amphtml#26131]
Seems to be related to setting state inside a promise/event call-back that's executed on the page loads.  Event call-backs are fine if they are inside another post-hydration event.
[Example here](
https://funky-thorium.glitch.me/)
The same code causes an illegal mutation error when executed on-load, but is fine inside the click handler of the button.

**Comment by AndrewKGuan** [comment]
Hi,
any thoughts on this issue?

Thanks

**Comment by kristoferbaxter** [comment]
@choumx This appears to be an issue with `AMP.setState` from within a `WorkerDOM` context.

**Comment by samouri** [comment]
@AndrewKGuan, did you modify the example and comment out the suppressed AMP.setState() call? I'm seeing this: 

![Screen Shot 2020-01-10 at 7 31 24 PM](https://user-images.githubusercontent.com/4656974/72195370-f2a75e80-33df-11ea-899d-70eae4cdc989.png)

> Seems to be related to setting state inside a promise/event call-back that's executed on the page loads.

Have you seen the docs related to [User Gestures](https://amp.dev/documentation/components/amp-script/?format=websites#user-gestures)? I think the issue could be that your `amp-script` components have `layout="container"`, which means that any mutation requires a user gesture.

**Comment by AndrewKGuan** [comment]
hi, sorry for the accidental change.  It's reverted now.

**Comment by AndrewKGuan** [comment]
I also changed the layout to 'fixed'. The error still exists.

**Comment by samouri** [comment]
Hi @AndrewKGuan, I believe you set the wrong `amp-script` to "fixed". Try setting the amp-script pointing to `test_with_error`.

![Screen Shot 2020-02-21 at 5 10 11 PM](https://user-images.githubusercontent.com/4656974/75076096-4328d600-54cd-11ea-8bf8-2f97645caeaf.png)


I tested it out locally and it worked for me.
