### ISSUE TITLE
Distinguishing snippet views (subscription prompt) from full article views 

### ISSUE THREAD

**Issue by CallumDJ** [ampproject/amphtml#2614]
## Short description of your issue:
WSJ.com has a FCF implementation, where a user gets a "snippet view"/prompt to subscribe on their 4th visit. 

We don't currently have a way of distinguishing the snippet view from a full article view in Adobe. 

## How do we reproduce the issue?

N/A

Please post a public URL and ideally post a reduced test case. E.g. on jsbin.com that exhibits only your issue and nothing else.

1. Step 1 to reproduce
2. Step 2 to reproduce
3. …

## What browsers are affected?
ALL 

All browsers? Some specific browser? What device type?
ALL 

## Which AMP version is affected?
ALL 

Is this a new issue? Or was it always broken? Paste your AMP version. You can find it in the browser dev tools.

New issue.

**Comment by dvoytenko** [comment]
@CallumDJ You should be able to pass data points from your own response via `AUTHDATA(field)` vars. See https://github.com/ampproject/amphtml/blob/master/extensions/amp-access/amp-access-analytics.md for more details.

Let me know if this works for you.

**Comment by rudygalfi** [comment]
Ping @CallumDJ

**Comment by rudygalfi** [comment]
Slotting into our current milestone. If there's no feedback on @dvoytenko's proposal by the 31st, we'll close this out.

**Comment by CallumDJ** [comment]
Thanks @dvoytenko - Will this also work for amp-iframe solution? We're not yet using amp-analytics, but are looking to transition in the future

**Comment by dvoytenko** [comment]
@CallumDJ , sorry, but what's the iframe solution? Could you please clarify?

**Comment by rudygalfi** [comment]
@dvoytenko I think it refers to using an amp-iframe for analytics purposes (instead of amp-analytics). I don't believe this will work in such an arrangement since what we're talking about is functionality that's specific to amp-analytics.

**Comment by dvoytenko** [comment]
@rudygalfi I will reassign to you then since it's in the analytics purview, but please assign to @avimehta as you see fit.

**Comment by rudygalfi** [comment]
As Dima said in https://github.com/ampproject/amphtml/issues/2614#issuecomment-198035696, amp-analytics is the way to go here.
