### ISSUE TITLE
tests occasionally fail with "amp-youtube renders FAILED"

### ISSUE THREAD

**Issue by frazjp65** [ampproject/amphtml#2615]
The build failed for Pull Request #2519, but the failure looked unrelated to my changes. The output around the failure is: 

> 17 03 2016 14:48:18.200:WARN [web-server]: 404: /base/build/polyfills.js
> ium 45.0.2454 (Ubuntu 0.0.0): Executed 1718 of 1744 (skipped 17) SUCCESS (0 secs / 27.878 secs)
> 17 03 2016 14:48:19.337:WARN [web-server]: 404: /base/build/polyfills.js
> Chromium 45.0.2454 (Ubuntu 0.0.0) amp-youtube renders FAILED
> 	Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
> Chromium 45.0.2454 (Ubuntu 0.0.0): Executed 1719 of 1744 (1 FAILED) (skipped 17) (0 secs / 29.956 secs)
> 17 03 2016 14:48:20.986:WARN [web-server]: 404: /base/build/polyfills.js
> ium 45.0.2454 (Ubuntu 0.0.0): Executed 1720 of 1744 (1 FAILED) (skipped 17) (0 secs / 30.719 secs)
> 17 03 2016 14:48:21.588:WARN [web-server]: 404: /base/build/polyfills.js
> ium 45.0.2454 (Ubuntu 0.0.0): Executed 1721 of 1744 (1 FAILED) (skipped 17) (0 secs / 30.819 secs)
> 17 03 2016 14:48:21.703:WARN [web-server]: 404: /base/build/polyfills.js
> ium 45.0.2454 (Ubuntu 0.0.0): Executed 1722 of 1744 (1 FAILED) (skipped 17) (0 secs / 31.426 secs)
> 17 03 2016 14:48:22.314:WARN [web-server]: 404: /base/build/polyfills.js
> ium 45.0.2454 (Ubuntu 0.0.0): Executed 1723 of 1744 (1 FAILED) (skipped 17) (0 secs / 32.004 secs)
> 17 03 2016 14:48:22.903:WARN [web-server]: 404: /base/build/polyfills.js
> ium 45.0.2454 (Ubuntu 0.0.0): Executed 1724 of 1744 (1 FAILED) (skipped 17) (0 secs / 32.585 secs)
> 17 03 2016 14:48:23.481:WARN [web-server]: 404: /base/build/polyfills.js
> ium 45.0.2454 (Ubuntu 0.0.0): Executed 1725 of 1744 (1 FAILED) (skipped 17) (0 secs / 33.12 secs)
> 17 03 2016 14:48:24.008:WARN [web-server]: 404: /base/build/polyfills.js
> ium 45.0.2454 (Ubuntu 0.0.0): Executed 1726 of 1744 (1 FAILED) (skipped 17) (0 secs / 33.669 secs)
> 17 03 2016 14:48:24.576:WARN [web-server]: 404: /base/build/polyfills.js
> ium 45.0.2454 (Ubuntu 0.0.0): Executed 1727 of 1744 (1 FAILED) (skipped 17) (0 secs / 34.241 secs)
> ium 45.0.2454 (Ubuntu 0.0.0): Executed 1727 of 1744 (1 FAILED) (skipped 17) (47.839 secs / 34.241 secs)
> [14:48:26] 'test' errored after 1.25 min
> [14:48:26] Error: 1
>     at formatError (/home/travis/.nvm/versions/node/v5.9.0/lib/node_modules/gulp/bin/gulp.js:169:10)
>     at Gulp.<anonymous> (/home/travis/.nvm/versions/node/v5.9.0/lib/node_modules/gulp/bin/gulp.js:195:15)
>     at emitOne (events.js:90:13)
>     at Gulp.emit (events.js:182:7)
>     at Gulp.Orchestrator._emitTaskDone (/home/travis/build/ampproject/amphtml/node_modules/orchestrator/index.js:264:8)
>     at /home/travis/build/ampproject/amphtml/node_modules/orchestrator/index.js:275:23
>     at finish (/home/travis/build/ampproject/amphtml/node_modules/orchestrator/lib/runTask.js:21:8)
>     at cb (/home/travis/build/ampproject/amphtml/node_modules/orchestrator/lib/runTask.js:29:3)
>     at removeAllListeners (/home/travis/build/ampproject/amphtml/node_modules/karma/lib/server.js:336:7)
>     at Server.<anonymous> (/home/travis/build/ampproject/amphtml/node_modules/karma/lib/server.js:347:9)
>     at Server.g (events.js:273:16)
>     at emitNone (events.js:85:20)
>     at Server.emit (events.js:179:7)
>     at emitCloseNT (net.js:1535:8)
>     at _combinedTickCallback (node.js:380:13)
>     at process._tickCallback (node.js:407:11)

I looked at other recent build failures and there were some with the same issue: 

* https://travis-ci.org/ampproject/amphtml/builds/116653920
* https://travis-ci.org/ampproject/amphtml/builds/116613500
* https://travis-ci.org/ampproject/amphtml/builds/116573741
* https://travis-ci.org/ampproject/amphtml/builds/116556231
* https://travis-ci.org/ampproject/amphtml/builds/116553094
* https://travis-ci.org/ampproject/amphtml/builds/116538721

## How do we reproduce the issue?

I am unsure how to reproduce the issue since it seems to pass on other builds. 

## What browsers are affected?

None. This is a build issue. 

## Which AMP version is affected?

I believe this is in the current master branch.

**Comment by dvoytenko** [comment]
/cc @erwinmombay @mkhatib 

@frazjp65 This looks like an intermittent failure. You can add `.only` to `describe.only` to test specific tests only if that helps.

**Comment by mkhatib** [comment]
[This](https://travis-ci.org/ampproject/amphtml/builds/116713783) also just failed with `amp-youtube` tests. Testing if increasing the timeout would make this less flaky.

**Comment by rudygalfi** [comment]
Any updates here?

**Comment by mkhatib** [comment]
We've increased the timeout for amp-youtube tests, no one complained of amp-youtube tests failing after that, are you seeing some test failures with this? Otherwise we can go ahead and close this.
