### ISSUE TITLE
Allow to add data from url to amp-state via AMP.setState() method in AMP EMAILS

### ISSUE THREAD

**Issue by modernwarfareuplink** [ampproject/amphtml#26166]
## Summary

There must be way to bind the value from amp-list to amp-state by using AMP.setState() method as there are cases where you cannot have mustache template to be used but can access the amp-state values.

## Motivation

I want to use amp-list and template within amp-lightbox which needs data from another amp-list remote data value, I will be able to use it only if I am able to set the latter's data using amp-state to use the data in lightbox. Please advise. 

P.S - Have gone through SO and issues in AMP but could not find anything and I think can be filed as issue.

/cc @ampproject/wg-approvers

**Comment by fstanis** [comment]
Could you maybe provide a code sample of what you're trying to do? I'm a bit unclear on how you want amp-state to interact with amp-list here and whether this is something that AMP for websites can do but email can't or a completely new feature.
