### ISSUE TITLE
[amp-story] keyboard next-page with active page-attachment causes blank next page

### ISSUE THREAD

**Issue by gabe97330** [ampproject/amphtml#26180]
## What's the issue?

The desktop amp-story player supports keyboard navigation. When a page attachment is active and next-page is executed, the display state of the next page is blank. 

## How do we reproduce the issue?

On desktop: 
- navigate to https://foodaciously.com/amp/recipe/vegan-peanut-butter-chocolate-chip-cookies/story
- Advance to the page 2 of the story and activate the page-attachment.
- press left-arrow to execute next-page action.
- observe that page 3 is blank.

## What browsers are affected?

chrome Version 79.0.3945.88, others??

## Which AMP version is affected?

Version 1912201827130

Is this a new issue? Or was it always broken? Paste the version of AMP where you saw this issue. 

See above

**Comment by gmajoulet** [comment]
This has been fixed as part of our accessibility work: https://github.com/ampproject/amphtml/projects/102
