### ISSUE TITLE
AMP timer to auto load javascript for PWA after page loaded

### ISSUE THREAD

**Issue by demil** [ampproject/amphtml#26199]
I know how to use service workers and to make AMP page entry page and every other link as entry to PWA, but why we should not have possibility to have all of AMP  which will load our PWA script to rehydrate all html after everything has loaded, so we will have best of both worlds in single request, fast loading AMP page and then rehydrate to PWA after everything has loaded.

It can be simple as single tag which just point to some script to be async loaded after page finished loading everything.

**Comment by kevinkimball** [comment]
@demil Can you elaborate a bit more on this feature suggestion? If I understand correctly, you would like to have your PWA script loaded into an AMP document directly (for example, an AMP document served from the Google cache?). Currently the assumption is that your PWA is not itself an AMP document, but a wrapper around AMP document. Just want to understand the feature request correctly. Thanks!

**Comment by demil** [comment]
Currently we use amp as a framework but for some more progressive enchanhment we load pwa on next click which is basicly same amp document with additional svript that rehydrate some of html and doesnt touch any of amp components, so my feature suggestion is to have this pwa progressive enchanhment script loaded on first entry async after all scripts are loaded and then we have best of both worlds, it is like we have redirect to pwa after x seconds on loaded amp bit without actual redirection but rehydratation instead. Was that more clear?
