### ISSUE TITLE
amphtml-validator does not work behind a proxy

### ISSUE THREAD

**Issue by Joelsz** [ampproject/amphtml#26200]
## What's the issue?

The amphtml-validator does not work behind a corporate proxy, it fails with general proxy error which could easily be resolved when using curl, however, amphtml-validator does not support those options.

Please fix by accepting more arguments or provide a usable workaround.

## How do we reproduce the issue?
```
$ amphtml-validator https://amp.dev/
Unable to fetch https://cdn.ampproject.org/v0/validator.js - unable to get local issuer certificate
```
Using local validator JS
```
$ amphtml-validator --validator_js validator.js https://amp.dev/
Unable to fetch https://amp.dev/ - unable to get local issuer certificate
```

## Which AMP version is affected?
```
$ npm -v amphtml-validator
6.5.0
```

**Comment by honeybadgerdontcare** [comment]
@Joelsz would you be willing to provide the workaround? It would be great to have you contribute to the AMPHTML Validator.

**Comment by Joelsz** [comment]
I guess the easiest workaround would be to accept proxyHost and proxyPort (and credentials?) and pass it along to the [clientModule.request()](https://github.com/ampproject/amphtml/blob/master/validator/nodejs/index.js#L118).

I have not contributed to an open source project yet, if you can guide me on how to get started I can look into this.

**Comment by honeybadgerdontcare** [comment]
This may the place to start [contributing code](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md). If it's overwhelming that's okay, we can work with you through the Pull Request process.
