### ISSUE TITLE
Resize callbacks and documentation

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#2622]
How/Where to document Resize Status PostMessages i.e, the exact message names - 'embed-size-changed', 'embed-size-denied' etc -

Do we need to have iframe resize status callbacks( 'embed-size-changed', 'embed-size-denied') for amp-iframe?

**Comment by sriramkrish85** [comment]
cc @dvoytenko

**Comment by dvoytenko** [comment]
My take is that we should extend this API to all iframes. And ideally we'd have a single helper class that would manage iframe lifecycle and implement this API to avoid code duplication between ads and iframe.

**Comment by sriramkrish85** [comment]
I wanted to have a resizeManager for managing iframe resize requests - per @cramforce it was too small at that point and not worthy of its own class. May be a helper file would be more appropriate now.

**Comment by rudygalfi** [comment]
Any updates here?

**Comment by dvoytenko** [comment]
@sriramkrish85 @rudygalfi Let's split refactoring issue from documentation. It'd be great to refactor code a bit during the next FixIt. But this sounds like specifically the documentation issue? Does it still exist?

**Comment by rudygalfi** [comment]
@sriramkrish85 What the documentation requirement here?

**Comment by ericlindley-g** [comment]
@sriramkrish85 Ping! Is there any remaining documentation task here?

**Comment by ericlindley-g** [comment]
@sriramkrish85 Haven't seen updates for this, so bumping this back to backlog, but please feel free to update/correct as needed

**Comment by rudygalfi** [comment]
We should do this or close it.

**Comment by camelburrito** [comment]
I think the APIs have changed now ? and @zhouyx @lannka modified a lot more after me :) We can close it or give it to them

**Comment by ericlindley-g** [comment]
Closing this for now due to inactivity — @camelburrito @dvoytenko @zhouyx  feel free to re-open if this is still needed
