### ISSUE TITLE
Error: failed to build: amp-analytics#3: a.getPlaceholder is not a function

### ISSUE THREAD

**Issue by kristoferbaxter** [ampproject/amphtml#26224]
https://go/ampe/CLfd-KWxtZ2nOg

```
Error: failed to build: amp-analytics#3: a.getPlaceholder is not a function
at getPlaceholder (https://raw.githubusercontent.com/ampproject/amphtml/1912180046560/src/custom-element.js:544)
```

**Comment by zhouyx** [comment]
The occurrences seems pretty low. Also I noticed it occurs with the build of different components. Wonder if it's related to custom-element. 
to @ampproject/wg-runtime

**Comment by choumx** [comment]
Weird bug. Only seems to happen on a single page on Android Chrome 74. Possibly a one-off client issue.
