### ISSUE TITLE
Requesting orientation permission for interactive `amp-story` experiences

### ISSUE THREAD

**Issue by wassgha** [ampproject/amphtml#26235]
Starting iOS 13, it is now required to request user permission to use the device orientation sensor (gyroscope/accelerometer), see https://medium.com/flawless-app-stories/how-to-request-device-motion-and-orientation-permission-in-ios-13-74fc9d6cd140 .

Many experiences that live inside `amp-story` need this permission, including 360 photos, 3D parallax #24299 , VR, etc. so there needs to be support for a button that gets dynamically added to pages that use this feature (UX needed + figuring out how extensions would communicate with the permission management).

/cc @ampproject/wg-stories

**Comment by newmuis** [comment]
Yep.  In my opinion, we should do this on the first page of a story that needs the feature.

**Comment by gmajoulet** [comment]
Wassim, do you know if the permission is per subdomain? If a user gives permission for `foo.cdn.ampproject.org`, do we have to request it again for `bar.cdn.ampproject.org`, or is it already granted?
