### ISSUE TITLE
Document placeholder more prominently on elements like amp-embed

### ISSUE THREAD

**Issue by ryanlombardo** [ampproject/amphtml#2623]
As fast as AMP pages are, some content may take a long time to appear. Specifically, images and embeds. (Especially embeds!) It would improve user experience if there was a well-defined and customizable way to define a placeholder for embeds and images that would be shown until the actual asset loads.

Related: https://medium.com/ux-for-india/facilitating-better-interactions-using-skeleton-screens-a034a51120a5#.anadmfc82

**Comment by mkhatib** [comment]
Hey @ryanlombardo thanks for filing the issue. Have you checked out [placeholder attribute](https://github.com/ampproject/amphtml/blob/f2bbf3c40c08eeac77e87f7d26d3545710d1e6a1/spec/amp-html-layout.md#placeholder).

This should be supported by most amp embeds and extensions. Some even build their own placeholder - see `amp-youtube` and `amp-instagram`

**Comment by ryanlombardo** [comment]
@mkhatib Thanks for the info! That looks like it should work. It would help others if a note was added to the `amp-embed` documentation at https://www.ampproject.org/docs/reference/amp-embed.html

**Comment by rudygalfi** [comment]
@Meggin: Can you see if there's a better way to promote the `placeholder` attribute across our docs?

https://github.com/ampproject/amphtml/blob/master/spec/amp-html-layout.md#placeholder

**Comment by bpaduch** [comment]
I'm going to close this one.  If you disagree, please reopen.  The [amp-ad](https://www.ampproject.org/docs/reference/components/amp-ad) reference docs include a section on "[Placeholder](https://www.ampproject.org/docs/reference/components/amp-ad#placeholder)".  As well, any components that utilize common attributes references the "Common Attributes" doc, which has [placeholder](https://www.ampproject.org/docs/reference/common_attributes#placeholder) documented.
