### ISSUE TITLE
<amp-stories-widget> - tag for AMP-pages to include stories

### ISSUE THREAD

**Issue by nixtka** [ampproject/amphtml#26237]
The idea is to implement a new tag for AMP-pages to show special Stories widget among AMP-pages.

Current solution for AMP-Stories are based on canonical links to pages (page to story) but if publisher wants to promote stories instead of waiting while Google crawler download and cache AMP-Story there is no solution for showing Stories among AMP pages. For typical pages there are a lot of custom solutions but if websites get a lot of traffic on AMP pages it should be a solution to show stories widget the same way as Facebook, Instagram and many others do - a line of stories on the top of the main (or any other) page.

This Idea was promoted by me at the latest AMP-Stories workgroup meeting and got a positive feedback. @newmuis recommended to create an issue and I've decided to do it in a new 2020 :)

Also I've created a short deck to show how it can be done:
http://bit.ly/ampStoriesWidget

So if the idea has a chance to be realised it would be great additional promotion to use stories for publishers.

I can talk to AMP UX designers to discuss all possible features and options this potential tag could have.

**Comment by nixtka** [comment]
What can I do to move this forward?

**Comment by newmuis** [comment]
Hey @nixtka!  We're resource-constrained but haven't forgotten about this!  We're about to launch `<amp-story-player>` which allows viewing a single story on your own site in a rich experience.  We're then also adding #26751 and #26865 which will allow you to view multiple stories (and one future PR that's not yet done, to allow swiping).

At that point, it would make sense to consider implementing something like this, where the initial version can be as simple as a static set of stories that each have a UI element (card, or maybe circle, as you've suggested), each of which opens the `<amp-story-player>`.

So, I think this is just waiting for its dependency (`<amp-story-player>`) to be complete enough to be used.
