### ISSUE TITLE
AMP.navigateTo issue on AMP Cache page

### ISSUE THREAD

**Issue by caothang53** [ampproject/amphtml#26248]
## What's the issue?

I need to make a link opened in a new tab and navigate the original tab to another page (exactly the same as https://github.com/ampproject/amphtml/issues/6221) using AMP.navigateTo with on:tap event. It's worked in the site while testing, but it's not working on AMP Cache.

## How do we reproduce the issue?

Sample URL: https://uc-browser-test-iprice-id.iprice.mx/coupons/kfc/

Please follow these step to reproduce the issue:
1. Go to the sample URL https://uc-browser-test-iprice-id.iprice.mx/coupons/kfc/ directly
2. Click on any item in the list under "Dapatkan kode diskon dari KFC"
3. Observe the action: A new tab will open with a popup, and the original tab will be navigated to another page. This is expected behavior of the link.
4. Get the sample page cached in AMP using AMP Test: https://search.google.com/test/amp
5. Go to "Preview Results"
6. Click on the SERP result to go to the sample page
7. Click on any item in the list under "Dapatkan kode diskon dari KFC"
8. Observe the action: No action took place. No new tab opened, no navigation in original tab.

## What browsers are affected?

All browsers

## Which AMP version is affected?

Version 1912201827130
This is new issue.

**Comment by twifkak** [comment]
cc @ampproject/wg-caching

**Comment by Gregable** [comment]
@caroqliu for further triage, I'm not sure where to route from here. Here's what my debugging turned up:

This appears to be unrelated to the cache directly. The "link" here is an `on` attribute unmodified by the cache:
```
<a ... on="tap:AMP.navigateTo(url='/coupons/kfc/...', target='_blank'), AMP.navigateTo(url='https://uc-browser-test-iprice-id.iprice.mx/r/c/...')"</a>.
```

When I click that element, Chrome console lights up with errors:
```
Unknown path prefix in url  https://zq3kammqwtx2krbphc2r522b6fduucm2dz6wyjepttjlbadblhcq.cdn.ampproject.org/...
Uncaught (in promise) Error: Unknown path prefix in url https://zq3kammqwtx2krbphc2r522b6fduucm2dz6wyjepttjlbadblhcq.cdn.ampproject...

```

This may have something to do with the fact that the AMP Cache origin is not the standard rewrite, but follows the fallback algorithm described in `https://amp.dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cache-urls/`. However, even if so, this is a javascript bug not an AMP Cache bug.

**Comment by choumx** [comment]
This is a runtime error from #23698.

"Unknown path prefix in url" is from here: https://github.com/ampproject/amphtml/blob/28f75c860df6281b0337748d17c5c9920aaea58b/src/url.js#L532-L536

This triggers because the relative URL `/coupons/kfc/...` in `tap:AMP.navigateTo(url='/coupons/kfc/...', target='_blank')` resolves to `*.cdn.ampproject.org/coupons/kfc/...`, which is not a valid AMP cache path.
