### ISSUE TITLE
[amp-script] Should `text/javascript` be allowed?

### ISSUE THREAD

**Issue by Malvoz** [ampproject/amphtml#26259]
`<amp-script>` requires a content-type of `application/javascript` when `src` is same-origin, which is documented in https://amp.dev/documentation/components/amp-script/#security-features. Should this be extended to allow `text/javascript` as well?

https://amp.dev serve scripts with `text/javascript`, and [this HTTP Archive post](https://discuss.httparchive.org/t/can-you-get-a-list-of-non-standard-mime-types-used-for-js-scripts/1141) suggests `text/javascript` is used widely.

Edit: Also, the HTML spec [recommends](https://html.spec.whatwg.org/#scriptingLanguages) use of `text/javascript` for script resources.

**Comment by choumx** [comment]
Reasonable and a quick change. Interested in contributing a PR? :) 

Note that `text/javascript` is technically marked obsolete.

**Comment by adamsilverstein** [comment]
Hi @choumx & @Malvoz - Thanks for the bug report, we were seeing this issue as well. I took a first pass at fixing this in https://github.com/ampproject/amphtml/pull/26465.

**Comment by choumx** [comment]
Fixed by #26465
