### ISSUE TITLE
Validator web UI build.py using Python 2.7

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#26279]
@danielrozenberg noticed that there are occasionally warnings about Python2.7 in use. It seems like the only offender is https://github.com/ampproject/amphtml/blob/master/validator/webui/build.py , which has a `python2.7` hash-bang. The only Python 2 code in the file appears to be a single `print >> sys.stderr, msg` line, which could likely be replaced by `print(msg, file=sys.stderr)`. Since Python2.7 is no longer supported, it may be worth finishing this migration to Python3

**Comment by honeybadgerdontcare** [comment]
This was supposedly fixed according to issue #22555 but it looks like it wasn't. @amaltas please look at implementing @rcebulko feedback.

**Comment by honeybadgerdontcare** [comment]
@rcebulko there were other files but we addressed them. They are mostly internal to Google; see cl/279395963.
