### ISSUE TITLE
Add linker to ADOBEANALYTICS_CONFIG

### ISSUE THREAD

**Issue by cory-work** [ampproject/amphtml#26289]
## What's the issue?

I'd like to update the Adobe analytics config to take advantage of the linker. I'll also refresh the configuration to use xhrpost and clean up some other issues.

## How do we reproduce the issue?

I'll add something like this to both extensions/amp-analytics/0.1/vendors/adobeanalytics.js and extensions/amp-analytics/0.1/vendors/adobeanalytics.json

'linkers': {
  'enabled': true,
  'proxyOnly': false,
  'linker': {
    'ids': {
      'adobe_amp_id': '${vid}'
    }
  }
}

## What browsers are affected?

All browsers.

## Which AMP version is affected?

This is a new feature.

**Comment by micajuine-ho** [comment]
Hi @cory-work, these sound like good improvements. 

Please reference this issue when you create a PR with the changes.
