### ISSUE TITLE
amp-sidebar does not display in Chrome and Firefox

### ISSUE THREAD

**Issue by Xuffasch** [ampproject/amphtml#26295]
## What's the issue?

Following the websites advanced features tutorial-guide, I tried to add the sidebar menu in the demo News site. The hamburger button does not open the sidebar.

## How do we reproduce the issue?

I just followed the tutorial for advanced features about "Navigating your site". I wrote the code that I ran in browsers.

## What browsers are affected?

The same code operates correctly on Desktop Safari, but not in Chrome or Firefox.

## Which AMP version is affected?

Is this a new issue? Or was it always broken? Paste the version of AMP where you saw this issue. (You can find the version printed in your browser's console.)

I guess I'm using the current version of AMP.

**Comment by caroqliu** [comment]
Can you provide more information on how you are running and sampling the code? I tested out the following code copied from the ["Navigate with a sidebar" section in the tutorial](https://amp.dev/documentation/guides-and-tutorials/start/add_advanced/navigating/?format=websites) in playground.amp.dev on Chrome and Firefox and was able to open and close the sidebar as expected:

```
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <title>My AMP Page</title>
  <link rel="canonical" href="self.html" />
  <meta name="viewport" content="width=device-width,minimum-scale=1">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script async custom-element="amp-sidebar" src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js"></script>
  <style amp-custom>
    .hamburger {
      padding-left: 10px;
    }
    .sidebar {
      padding: 10px;
      margin: 0;
    }
    .sidebar > li {
      list-style: none;
      margin-bottom:10px;
    }
    .sidebar a {
      text-decoration: none;
    }
    .close-sidebar {
      font-size: 1.5em;
      padding-left: 5px;
    }
  </style>
</head>
<body>
  <header class="headerbar">
    <div role="button" on="tap:sidebar1.toggle" tabindex="0" class="hamburger">☰</div>
    <div class="site-name">News Site</div>
  </header>
  <amp-sidebar id="sidebar1" layout="nodisplay" side="left">
  <div role="button" aria-label="close sidebar" on="tap:sidebar1.toggle" tabindex="0" class="close-sidebar">✕</div>
  <ul class="sidebar">
    <li><a href="#">Example 1</a></li>
    <li><a href="#">Example 2</a></li>
    <li><a href="#">Example 3</a></li>
  </ul>
</amp-sidebar>
</body>
</html>
```

**Comment by Xuffasch** [comment]
First thank you for your answer and your code as I tried it and it worked on Chrome.

I've push a commit in my repo ("amp-advanced") where I compare : 
- the working code you gave me ("amp.article.html")
- the bugged code I wrote ("article.amp.html")

My code is quite long as it has all the code I tested with the advanced features of the guide.

A rapid comparison does not show differences in the way I wrote the amp-sidebar parts. Maybe it is the order by which I appended the scripts in the header. I would be very interested if you can try my code to see if you also have the buggy behavior or better if you can tell me what is wrong ! 

If there an official repository for all the tutorial guide code ?

Thanks again for answering again.

**Comment by caroqliu** [comment]
Thanks for directing me to your sample code! It looks like the sidebar is not opening because there is an element (`div.site-name`) covering the button (`div[role=button]`) that toggles the sidebar open. When you go to click on the button, you are actually clicking on an element above it.

One way to fix this is by replacing the CSS property:
```
.site-name {
      flex: 1;
      margin-left: -36px;
 }
``` 
with one that does not cover the button element:
```
.site-name {
      margin: auto;
}
```

**Comment by caroqliu** [comment]
@CrystalOnScript -- Is there a file with all of the steps in [this tutorial](https://amp.dev/documentation/guides-and-tutorials/start/add_advanced/navigating/?format=websites) pieced together that we can look at? It might need the same CSS modification described above.

**Comment by CrystalOnScript** [comment]
Thanks for reporting this @Xuffasch! 

Good call @caroqliu - the culprit is [here](https://amp.dev/documentation/guides-and-tutorials/start/add_advanced/navigating/?format=websites#link-back-home). 

I've opened a [PR to resolve it](https://github.com/ampproject/amp.dev/pull/3364).

**Comment by Xuffasch** [comment]
Thanks @caroqliu for your analysis and solution. 
I'm kind of new in CSS so let me summarise how I understand my bug:
- the ".site-name" setting for my News Site text is covering my hamburger button because margin is -36px
- changing that css setting to "margin: auto" will set the start of the text at least after the end of the hamburger button.

Using the dev tools, I've been able to see the sizes and positioning of the 2 elements, without the change in Safari and with the correction in Chrome.

I find it interesting the difference of behavior between Safari and Chrome:
- Chrome is just strictly following CSS.
- Safari is a little smarter as even if the "News Text" was covering the button. Since the text is not set to respond to any click or interaction, Safari looks for the next element beneath it and found the button, which explains why I can still see the expected behavior. This is exactly the kind of behavior in iOS on mobile devices.

OK thanks for the explanation again, I'll keep an eye from now on about this hiding stack effect.
