### ISSUE TITLE
[Issue tracker] 👓 amp-story-player

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#26308]
### Overview

Open Source Story Player: a container for embedding and playing AMP Stories on the web. A player can have multiple stories within it, and supports capabilities like “swipe-to-next” and social sharing options. Existent players can be found in native apps and on the web in the Google Search results. 

### Goals

* Support in both AMP and non-AMP websites.
* Open source
* Support the following features:
  * Swipe/tap-to-next and previous story.
  * Pre-rendering.
* Identical API & behavior across AMP/non-AMP.
* Support for mobile and desktop web.

<table>
  <tr>
    <td colspan="4">
      <h2>Subtasks</h2>
    </td>
  </tr>
  <tr>
    <td><h3>Title</h3></td> 
    <td><h3>Description</h3></td> 
    <td><h3>Status</h3></td> 
    <td><h3>Github Issue/PR</h3></td> 
  </tr>
  <tr>
    <td>1. Add JS library </td> 
    <td>To make the viewer work in non-AMP pages. Refine the experience when the JS and/or iframe are not yet loaded.</td> 
    <td>Done</td> 
    <td>#26276 #26557 #26305</td> 
  </tr>
  <tr>
    <td>2. Add & support fragment param to communicate with stories</td> 
    <td>This will enable us to (1) make runtime changes (e.g. UI tweaks) when in player (2) load viewer integration script conditionally (3) open the door for analytics.</td> 
    <td>Done</td> 
    <td>#26694 </td> 
  </tr>
  <tr>
    <td>3. Add viewer integration messaging API </td> 
    <td>This API will enable communication between the viewer and the document.</td> 
    <td>Done</td> 
    <td>#26305 #26694 #26719</td> 
  </tr>
  <tr>
 <tr>
    <td>4. Pre-rendering & navigation logic</td> 
    <td>Whenever a user is navigating, we should pause the story, play the next one, and pre-render the next-next story.</td> 
    <td>Done</td> 
    <td>#26696</td> 
  </tr>
<tr>
    <td>5. Add tap to next/prev story</td> 
    <td>Whenever a user is finished reading a story, the next tap should take the user to the next story.</td> 
    <td>Done</td> 
    <td> #26697 </td> 
</tr>
<tr>
    <td>6. Add swipe-to-previous/next story</td> 
    <td>Add support for swiping to previous/next story.</td> 
    <td>Done</td> 
    <td> #26698 </td> 
  </tr>
<tr>
    <td>7. Sandbox iframes</td> 
    <td>The iframes we create in the player should be iframed, see amp [iframe].</td>
    <td>Done</td> 
    <td>#27178 </td> 
  </tr>
<tr>
  <td>8. Control the player programmatically</td>
  <td> We should expose an API so that the player can be controlled programmatically. </td>
  <td> In progress </td>
  <td> #28416</td>
</tr>
<tr>
    <td>9. Load documents from the cache.</td> 
    <td>We should load the stories from the cache unless the publisher opts-out.</td> 
    <td>Done </td> 
    <td>#27588 </td> 
  </tr>
<tr>
    <td>10. Add embed modes </td> 
    <td>Add a parameter that publishers can specify in the DOM/JSON configuration that can be passed through to the embedMode fragment parameter, to allow specifying embed modes.</td> 
    <td>Not started</td> 
    <td></td> 
  <tr>
    <td>11. Support  embedding within an AMP document </td> 
    <td>Once the above tasks are ready we should add the same support for AMP pages.</td> 
    <td>Done</td> 
    <td>#29312</td> 
  </tr>
</table>

**Comment by newmuis** [comment]
For "Add JS Library" milestone, I think there may still be more work to do.  We need to refine the experience when the JS and/or iframe are not yet loaded.

**Comment by newmuis** [comment]
Can we add a few things to this list?

- Load documents from cache
- Sandbox iframes
- Support for embedding within an AMP document (supporting all other features mentioned here)

**Comment by Enriqe** [comment]
@newmuis done!

**Comment by gmajoulet** [comment]
@Enriqe is it ready to be closed now that new features are tracked separately?

**Comment by Enriqe** [comment]
I think it's fine to keep open, as there are other general features that could be tracked here (non programmatic API-related)

**Comment by llccrr** [comment]
@Enriqe Would it be possible to have the in-between Stories animation customizable with some css, presets or keyframes... ?

**Comment by newmuis** [comment]
@llccrr do you mind filing this as a separate feature request?

**Comment by llccrr** [comment]
I just found out that it was already mentionned in the following feature request #27333

**Comment by irene84111** [comment]
Is there any progress/plan on Task #11?
Partners are eager to embedded Web Stories in their AMP pages and it would be great to have an expected release date.
