### ISSUE TITLE
Access request not being sent, causing blank pages

### ISSUE THREAD

**Issue by quarterto** [ampproject/amphtml#2630]
Sometimes, when loading the AMP carousel and swiping a few times, the access requests stop being sent. When this happens, neither the article content nor the barrier are shown. I am signed in to the FT, and when the access request *does* happen, the service is returning `access: true`, and the content is correctly shown.

<img width="401" alt="screenshot 2016-03-18 09 34 34" src="https://cloud.githubusercontent.com/assets/631757/13874076/6b27f9de-eced-11e5-8b6e-f9cf5d310b73.png">

This is the article rendered at https://amp.ft.com/content/dbf0ae98-ec63-11e5-bb79-2303682345c8.

I'm also seeing some errors in the console; I'm unclear if these are related:

```
Uncaught Error: Service activity was requested to be provided through amp-analytics, but amp-analytics is not loaded in the current page. To fix this problem load the JavaScript file for amp-analytics in this page.​​​
Uncaught Error: Service cid was requested to be provided through amp-analytics, but amp-analytics is not loaded in the current page. To fix this problem load the JavaScript file for amp-analytics in this page.​​​
```

We're seeing this with an emulated Nexus 5 as well as a real iPhone 5s and Galaxy S4, in AMP version 1457721872758.

**Comment by dvoytenko** [comment]
@quarterto Could you please describe how you are reproducing this? Do you use the same one article that you cite above but include it multiple times in the carousel? Could you provide some instructions for me to repro?

Generally, "Service X was requested to be provided" simply means that a referred script is missing in the head, but I'd try to repro first before jumping to a conclusion.

**Comment by dvoytenko** [comment]
@quarterto I believe I found an issue. I should be able to fix it shortly. Thanks for reporting!

**Comment by dvoytenko** [comment]
This is fixed in canary.
