### ISSUE TITLE
[amp-video-docking] Readme: broken link for elligible targets

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#26315]
See section on amp.dev: https://amp.dev/documentation/components/amp-video-docking/#attributes

> N/A. amp-video-docking does not define any custom elements. To use this extension, set the dock attribute on an elligible video player component.

This link is broken: https://github.com/ampproject/amphtml/blob/master/extensions/amp-video-docking/amp-video-docking.md#support

**Comment by alanorozco** [comment]
You mean the anchor link to the section? It seems to be working for me.

**Comment by sebastianbenz** [comment]
Sorry for the false alarm. No idea why it didn't work before...
