### ISSUE TITLE
Bookend relative links should be resolved when served from an AMP Cache

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#26316]
Bookend relative links should be resolved when served from an AMP Cache.

1. Open https://beautifuldestinations-com.cdn.ampproject.org/c/s/beautifuldestinations.com/products/iceland and trigger the bookend
2. Click on the first bookend item

```
{
  "type": "portrait",
  "title": "Black Sand Beach, Iceland",
  "url": "/products/black-sand-beach-iceland",
  "category": "Framed Photographs",
  "image":"//cdn.shopify.com/s/files/1/0246/8331/5280/products/CLARE-PERSONAL-ICELAND-2.JPG_1f624b3b-64ee-498f-ac76-8fab80bf7f34_x750.jpg?v=1574388303"
}
```

The `url` relative URL should be resolved to an absolute URL pointing to the canonical domain.

**Comment by gmajoulet** [comment]
cc @Enriqe do you have bandwidth to take this one on since you've also been working on https://github.com/ampproject/amphtml/pull/25614?

**Comment by Enriqe** [comment]
Yep sure, I can take on this one.
