### ISSUE TITLE
Request for merge access

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#26327]
I've submitted [21 PRs](https://github.com/ampproject/amphtml/pulls?q=is%3Apr+is%3Aclosed+author%3Asamouri).

Thank you!

cc @jridgewell, @choumx

**Comment by jridgewell** [comment]
👍 @mrjoro

**Comment by mrjoro** [comment]
Done!  Congrats on becoming a Reviewer @samouri. :)
