### ISSUE TITLE
MP_AD Appnexus Adaptor / Cookie Policy Support

### ISSUE THREAD

**Issue by Nicola1976** [ampproject/amphtml#2633]
Hi

We use oas amp ad adaptor with appnexus implementation. Oas tech support told us to ask directly to you to solve some problemz about our needs :

At a time when the user loads the page AMP-AD component with amp-user-notification  showing a message of acceptance of cookies policy.

 We need that the ADV should not displayed and AD call not fired until this message is actually accepted. 

As is on the following example on repubblica.it, that is using doubleclick adserver type.

Could you think it is possible to have the same behaviour on amp-ad for appnexus?

This is my actual implementation on a test page:
https://stadvtools.akamaized.net/xaxsis/common/googleAMP/nclamp/indexOLD.html

Problem:
1) why the page show the message everitime I reload the page? How to show just the first time?
2) It is possibile to block ad call and rendering of adv until user click on "ok button"?

thanks a lot!
nicola

------------------------------------------------------------------------------------------
BELOW WHAT WE NEED TO ACHIEVE
------------------------------------------------------------------------------------------

**example page on repubblica.it:**
https://www.google.it/amp/www.repubblica.it/tecnologia/2016/03/14/news/stanford_confidential-135229426/amp#

notification code element:

![image](https://cloud.githubusercontent.com/assets/14162566/13883537/28a419d4-ed2a-11e5-9256-e0ff4e76b726.png)

**AMP-AD component before cookye policy has been accepted:**

![image](https://cloud.githubusercontent.com/assets/14162566/13883562/48a37496-ed2a-11e5-84fb-8b966d4edd25.png)

![image](https://cloud.githubusercontent.com/assets/14162566/13883590/6c28c68c-ed2a-11e5-93f6-5df7ec6a6ec7.png)

**AMP-AD component after cookye policy has benn accepted **

![image](https://cloud.githubusercontent.com/assets/14162566/13883627/8bb96e34-ed2a-11e5-9092-b8ef01353796.png)

**Comment by erwinmombay** [comment]
@Nicola1976 you can add `data-consent-notification-id="amp-user-notification-privacy"` to an `amp-ad` to block it until the amp-user-notification has clicked "ok". let me know if that works for you

**Comment by Nicola1976** [comment]
Sorry, i try to add as you suggested but it seems dont work.

<amp-ad width=300 height=100
                type="openadstream" 
				data-adhost="oas.rcsadv.it" 
				data-sitepage="mobile.corriere.it/hp" 
				data-pos="Frame1" 
				data-query="keyword=test-google-amp"
				data-consent-notification-id="amp-user-notification-privacy"
                >

https://stadvtools.akamaized.net/xaxsis/common/googleAMP/nclamp/indexOLD.html 

I have this error in console:
f.js:10 Uncaught Error: Unknown attribute for openadstream: consentNotificationId.​​​

Thanks a lot
Nicola

**Comment by erwinmombay** [comment]
@Nicola1976 looking into it

**Comment by erwinmombay** [comment]
so theres 2 things to do to fix the issue,

1) is for you to add `amp-analytics` on your page, as `amp-analytics` is required for `cid` (client id) generation on `amp-user-notification`.

2) is for us to add add "openadstream" to https://github.com/ampproject/amphtml/blob/master/ads/_config.js#L116 since `amp-ad` won't block on `amp-user-notification` unless a `scope` is given. 

I'm still researching the 2nd item as I don't know why we don't add all ad providers to that list so I need to ask the right people first if we can add openadstream or not.

**Comment by Nicola1976** [comment]
Thanks a lot! 

I added amp-analytics on my page just before amp-user-.notification link:

https://stadvtools.akamaized.net/xaxsis/common/googleAMP/nclamp/indexOLD.html 

let me know as soon as possible because we are blocked by this bug. 
It's a very urgent question because at the time in Italy , as elsewhere in the world, it is prohibited by law writing any third part cookies if the user has not accepted the cookie policy.

Thanks
Nicola

**Comment by Nicola1976** [comment]
Hi Erwin! 
So the issue is solved right? Now the amp-ad is blocked by amp-user-notification even when no amp-ad scope exist?

So why I see in console the error "**Uncaught Error: Unknown attribute for openadstream: consentNotificationId.​​​**". What's wrong on my test page? 

https://stadvtools.akamaized.net/xaxsis/common/googleAMP/nclamp/indexOLD.html

How can I solve defenitly my problem and delete the error?

Thanks a lot

**Comment by erwinmombay** [comment]
@Nicola1976 the fix has been merged but it'll take another week for it to make full production. It will go into canary this Thursday and then full Production by next Thursday.

/cc @rudygalfi

**Comment by dvoytenko** [comment]
@Nicola1976 we'd appreciate it if you would try it out in the canary this thursday.

**Comment by Nicola1976** [comment]
Yeah, sure no problem.  
Do you mean that you'll send me a link to test the new functionality on canary web browser? right?

Let me know.

Thanks a lot.
nicola

**Comment by Nicola1976** [comment]
Sorry, another question : it would be possible to accelerate  full Production, I mean before next Thursday, if all the tests are successful?

We have a urgent issue in production that depend on this fix.

nicola

**Comment by erwinmombay** [comment]
@Nicola1976 to test it when canary is updated, you'll need to go to https://cdn.ampproject.org/experiments.html and turn on `dev-channel` and go to the test/repro pages you provided. (you might need to do `localStorage.clear()` first to trigger the notification again)

as for expediting the code to prod i'll defer the decision to @cramforce @rudygalfi
we can roll custom branches if necessary.

**Comment by Nicola1976** [comment]
Hi Erwin, So can I try the fix today on canary as you described?

**Comment by erwinmombay** [comment]
hey @Nicola1976 sorry not yet, its 2am here in the US :sleeping: will get to this in around 12 hrs time. I will ping you here asap when it is launched

**Comment by Nicola1976** [comment]
Sorry! Good night! See you tomorrow! :-)

**Comment by erwinmombay** [comment]
@Nicola1976 please go ahead and test this.

first head over to https://cdn.ampproject.org/experiments.html and turn on "dev-channel" and then go to your test page and make sure to clear local storage by executing "localStorage.clear()" on the javascript console and then refresh the page and test. let me know!

**Comment by Nicola1976** [comment]
I Erwin, Great! It seems to work fine! Now if I dont accept cookie policy the adv call is not fired. Thanks a lot.

How can we have the fix in full production to more easly make massive test on our real page?

Let me know.

Thanks again
Nicola

**Comment by erwinmombay** [comment]
@Nicola1976 we should deploy it on thursday.

**Comment by Nicola1976** [comment]
Hi Erwin, the test is active also right now? 
Because I can't run the test as in past days. Let me know.

thanks
nicola

**Comment by erwinmombay** [comment]
@Nicola1976 not sure what you mean by test is active? if you go to https://cdn.ampproject.org/experiments.html and turn on dev-channel it should still be working. 
let me know if theres anything i can clarify or help with. Thanks. We should turn this on to full production by end of day tomorrow PST.

**Comment by Nicola1976** [comment]
OK I go on this page and turn on the dev 
![image](https://cloud.githubusercontent.com/assets/14162566/14168889/0aeb7aea-f725-11e5-9ed9-679195351482.png)

than I go to my test page passing in console loacalStoratge.clear() but, differently from before, I have the original error in console like this:

![image](https://cloud.githubusercontent.com/assets/14162566/14168972/76270c5c-f725-11e5-994c-48ec760adbe7.png)

Somtehing wrong on my test page?

**Comment by Nicola1976** [comment]
Sorry It was my fault! everything is ok!
Let me know when it is on full production.

Thanks a lot.

Nicola

**Comment by Nicola1976** [comment]
I see that all works fine already also in full pruduction (without turning on dev mod on AMP experiment page)

It is possibile?

Thanks!

**Comment by erwinmombay** [comment]
@Nicola1976 it would probably be only be working in production if the ad type is doubleclick right now.

**Comment by erwinmombay** [comment]
@Nicola1976 https://github.com/ampproject/amphtml/releases/tag/1458844805881 should be now in production. please test it out, and let us know if you still see any issues. thank you for you patience!

**Comment by Nicola1976** [comment]
Hi we have noticed that ther is a old issue in production amp article. As you remember we required that in appnexus adaptor the cookie policy banner should blodk the adv call until it is accepted. But now in production (we dont have change nothig) we see the banner and the cookie policy banner too.

So, as appened in your first implementation, when the user loads the page, the AMP adaptor doesn't stop the adv  cal.

Do you have made some modification?

you can check this behaviour searching for "corriere notizie" on google mobile version to have OUT AMP article.

Below a screenshot

![8cea4eca83ae6ebfa81aa9fc7211e8424cdac98dea4913ac18 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/14162566/18788708/37f6bcd0-81a8-11e6-867a-215a1cf06a06.jpg)

![ba6d7212237363819024ea24bcfbe6de9a1305c2ca8792e47a pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/14162566/18788712/3ac044e0-81a8-11e6-9252-fad16104b057.jpg)

Let me know.
Thank a lot
