### ISSUE TITLE
In AMP stories, the CTA button in Publisher Served Ad doesn't display in Firefox.

### ISSUE THREAD

**Issue by Avdhoot05** [ampproject/amphtml#26334]
Check this in latest version of Firefox:
https://ampbyexample.com/stories/monetization/publisher_served/preview/embed/
In this AMP story example, look for ad. You won't see CTA button in the ad, while you'll see one when you check on Chrome and Edge.

**Comment by calebcordry** [comment]
@Avdhoot05 Thanks for reporting, will look into this later today.

**Comment by Avdhoot05** [comment]
@calebcordry Ok.Thanks !Hoping this issue will be solve asap in production .

**Comment by gmajoulet** [comment]
@Avdhoot05 you can look at the labels on the actual PR to see if it is available in production. Right now it says "In beta / experimental", so it should go to production today.
https://github.com/ampproject/amphtml/pull/26438
