### ISSUE TITLE
amp-script: Decouple disabling script hash from data-ampdevmode

### ISSUE THREAD

**Issue by morsssss** [ampproject/amphtml#26341]
When you use the `data-ampdevmode` attribute with `<amp-script>`, the validator outputs the following warning:

`Tag 'html' marked with attribute 'data-ampdevmode'. Validator will suppress errors regarding any other tag with this attribute. Debug.`

It sounds to me like the validator might be choosing to ignore other AMP validation errors in the HTML, though I don't think that's what it means. Also, when I see "Debug", I assume it means I'm doing something wrong and I should fix it.

Could this error instead say something like:

`You're using 'data-ampdevmode' to suppress errors regarding your <amp-script> hash or the size of your <amp-script> JavaScript. Remove this attribute before putting code in production.`

**Comment by morsssss** [comment]
Alternately, the warning that's output to the console is quite clear to me:

`[amp-script] JavaScript size and script hash requirements are disabled in development mode.`

Although, as it's more compact, it conveys less information than what I proposed.

**Comment by choumx** [comment]
`data-ampdevmode` was originally implemented to disable all validation on elements that have the attribute. amp-script reuses the attribute for the use case you mentioned.

**Comment by morsssss** [comment]
Got it! AFAIK we've never documented this attribute, and I didn't know about it. We only mention it in the [<amp-script> documentation](https://amp.dev/documentation/components/amp-script/). I feel like we should document it and keep its behavior as is. As far as I'm concerned we can close this.
 
@CrystalOnScript WDYT?

**Comment by Gregable** [comment]
reassigning to @CrystalOnScript . Let me know if you want help writing.

**Comment by morsssss** [comment]
Also, back in #26398, @choumx said:

"Yea, so we used to have a separate development attribute that only disabled the script hash behavior and then combined it when data-ampdevmode when we found out about it.

Sounds like you'd like it to be separate again?"

This conversation dropped... but... yes, definitely!

I can make this a separate FR if that's easier.

**Comment by choumx** [comment]
Heh, that's fine. Let's just refactor this issue.

We can also consider renaming to distinguish between validator and runtime "dev" modes: 
- Rename `data-ampdevmode` to `dev-suppress-validation`.
- Use `dev-disable-hash` for amp-script's dev mode.

**Comment by morsssss** [comment]
`dev-disable-hash` sgtm!

**Comment by samouri** [comment]
i've always heard technology advances in cycles...

I'd be happy to implement this change.
Where do we think devs would want to place the `dev-disable-hash` attribute?
My gut says placing it on the html root and having it apply to all `amp-scripts`s in the page would be most ergonomic.

**Comment by morsssss** [comment]
I share your gut here (if that's a thing).

I don't think anyone would want to disable the hash for a single `<amp-script>` but not others...

**Comment by samouri** [comment]
ccing @westonruter since he had opinions on the last version of this.

**Comment by samouri** [comment]
Question: would we expect that `dev-suppress-validation` would _also_ disable the hash check?

**Comment by samouri** [comment]
> Heh, that's fine. Let's just refactor this issue.
> 
> We can also consider renaming to distinguish between validator and runtime "dev" modes:
> 
> * Rename `data-ampdevmode` to `dev-suppress-validation`.
> * Use `dev-disable-hash` for amp-script's dev mode.

I think we could solve the same problem more elegantly by instead relaxing the requirement that `data-ampdevmode` is present on both the node and the html root. That way devs could use the same flag and also separately toggle these features.  In other words:
- `data-ampdevmode` on the root html node means to suppress validation.
- `data-ampdevmode` on an individual amp-script means to enable dev mode for that script (disable hash/size checks).

**Comment by westonruter** [comment]
> * Rename `data-ampdevmode` to `dev-suppress-validation`.

Note this will cause headaches for frameworks that have implemented support for this, e.g. Next.js (https://github.com/zeit/next.js/issues/8298) and the WordPress AMP plugin (which we can hotfix if needed), at least.

**Comment by morsssss** [comment]
@samouri there may be implications I haven't thought about, but I really like your idea. It provides for backward compatibility, avoids creating an additional attribute, and increases consistency.

**Comment by samouri** [comment]
Closing this now that I've merged #27076. The end result was that the attribute is still named `data-ampdevmode`, but it can now be placed on `amp-script` tags without having to also place it on the root html node.
