### ISSUE TITLE
changeSize and attemptChangeSize call - stops responsive layout

### ISSUE THREAD

**Issue by rares-mihai-preda** [ampproject/amphtml#26381]
I created a custom amp html component that inherit from BaseElement. Our component support just responsive layout. 

By design, our component that is embedded in an iframe supports two layout types: portrait and landscape. When orientation change, we call this.element.changeSize(height, width) which will resize the component. The bad part is that after resizing, if the viewport change, the component in not responsive anymore.

**Comment by jridgewell** [comment]
Are you just trying to change the aspect ratio of the responsive element? We could consider adding a specific method for that. Right now, `changeSize` implies that you are changing your size from _anything_ to a known fixed size.

**Comment by rares-mihai-preda** [comment]
@jridgewell Yes. We need to change the aspect ratio of the responsive element. 

Thanks for considering adding a specific method for this because currently, we have a technical limitation because of changeSize which changes the size from anything to a known fixed size.

We are happy to hear this from you and hope to hear from you soon. Thanks a lot!
