### ISSUE TITLE
All amp-story visual diff tests including amp-video tags fail.

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#26390]
All amp-story visual diff tests including amp-video tags fail. Hard to figure out when it started breaking as the Percy's UI doesn't let you go too far back in time without melting your computer, but it's been over 3 months.

Affected tests include amp-story bookend.

**Comment by cramforce** [comment]
Comment in visual test added in #26849 when this is fixed.

**Comment by cramforce** [comment]
This is still happening.

Downloading the doc that was diffed, it renders totally fine. Super weird.

**Comment by gmajoulet** [comment]
To keep this thread up to date:
- @cramforce opened #28727
- @danielrozenberg is contacting Travis support about the issue
