### ISSUE TITLE
<amp-script> outputs error to console for layout != 'container'

### ISSUE THREAD

**Issue by morsssss** [ampproject/amphtml#26398]
Whenever I use <amp-script> with a layout that's not `container` - e.g., `fixed` or `responsive`, the following error is output to the console:

`Expected height to be available:  null` - `error.js:195`

While this may seem trivial, I've already seen examples where AMP developers reached out to Googlers for help because they couldn't figure out how to debug their code, and they assumed this bug was their fault.

See screenshot for full stacktrace:

<img width="352" alt="Screen Shot 2020-01-17 at 7 02 46 PM" src="https://user-images.githubusercontent.com/29419498/72654114-03b21b80-395c-11ea-85b0-d14e3ce0a4b6.png">

**Comment by choumx** [comment]
Can you share an example page?

**Comment by morsssss** [comment]
Sure! This simple HTML does it. (I've removed the AMP boilerplate for simplicity)


```
<!doctype html>
<html ⚡ lang="en" data-ampdevmode>

<head>
  <meta charset="utf-8">
  <title>amp-script tests</title>
  <link rel="canonical" href="localhost">
  <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">

  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script async custom-element="amp-script" src="https://cdn.ampproject.org/v0/amp-script-0.1.js"></script>

  <script id="myscript" type="text/plain" target="amp-script">
    let foo = 3;
  </script>
</head>

<body>
  <amp-script layout="responsive" script="myscript" data-ampdevmode>
    <div>
      <p>Some text</p>
    </div>
  </amp-script>
</body>
</html>
```

**Comment by choumx** [comment]
Some layouts (including `responsive`) requires a `width` and `height` to be set on the AMP element.

https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/control_layout/#supported-values-for-the-layout-attribute

**Comment by morsssss** [comment]
Good point!

However, with other AMP elements, when dimensions are missing, the validator throws an error, like this:

`The mandatory attribute 'height' is missing in tag 'amp-img'.`

So, ideally, I think the validator would do the same for `<amp-script>`. Otherwise, I fear that developers who don't realize they need to specify dimensions, or who forget to, will simply be confused.

Further, if this isn't enlarging the runtime unnecessarily, we should replace these two console errors:

`Expected height to be available: null`
`Expected width to be available and not equal to "auto":  null`

with something as friendly as this:

`The element did not specify a layout attribute. Check https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/control_layout and the respective element documentation for details.`

**Comment by choumx** [comment]
Ah, it does throw the same validator error but such errors are silenced by `data-ampdevmode` on the amp-script element.

Agree on the friendlier runtime error.

**Comment by morsssss** [comment]
Oh, interesting!

Then should I amend #26341 to ask that the validator only silence warnings about the hash or the size of the JS? Or, really, my impression is that it would always be useful to get warnings about JS size. Just that it would be useful to not have to calculate the hash until we get nearer to production.

**Comment by choumx** [comment]
Yea, so we used to have a separate `development` attribute that only disabled the script hash behavior and then combined it when `data-ampdevmode` when we found out about it.

Sounds like you'd like it to be separate again?

**Comment by morsssss** [comment]
I feel like what we need here is something that disables the script hash behavior, exactly as you used to do with `development`. That's the thing a developer would want to disable while working on a script. I don't think it's worth suppressing any other errors, since the developer would want to catch those during development.

So I like what you used to do 😃 But /cc @fstanis , @patrickkettner , @sebastianbenz all of whom have more experience developing with `<amp-script>`.
