### ISSUE TITLE
Reduce need for FixedLayer

### ISSUE THREAD

**Issue by kristoferbaxter** [ampproject/amphtml#26397]
Fixed Layer setup is executed in the next available microtask when an AMP document is 'ready'. `ampdoc.whenReady().then(() => this.fixedLayer_.setup());`

There are a few things we could do to reduce its impact on initial document performance:
1. Do no work in `setup` if the document is not inside an AMP Viewer.
2. Remove the need for its complexity by performing transforms on source document as part of generating a signed exchange or entry into an AMP Cache. This transform would use css variables (https://caniuse.com/#feat=css-variables) to execute the same shift in position for fixed elements that is currently done with JavaScript.

### Alternatives you've considered
Do nothing, live with the impact.

**Comment by kristoferbaxter** [comment]
Per offline conversation with Dima:

We could split this work into different buckets and raise the priority of the first:
1. Participate with scheduler to execute `setup`, and disable when the document is not in the viewer.
2. Move to CSS Variables for the entire system, including changes to ingestion of documents and the generation of signed exchanges.

**Comment by jridgewell** [comment]
> Move to CSS Variables for the entire system, including changes to ingestion of documents and the generation of signed exchanges.

Prior work at 
https://github.com/jridgewell/amphtml/commit/8fd33d1b5677dbe352ae2083d0792309667d9d97
