### ISSUE TITLE
Allow AMP to be HTML-valid

### ISSUE THREAD

**Issue by twifkak** [ampproject/amphtml#26402]
It would be nice if there were a way to express every AMP capability in an HTML valid way (doesn't make something like https://validator.w3.org/ upset). Provide `data-` alternatives for attributes like `<script custom-element>`, `on`, etc. I note that [amp-bind already does this](https://amp.dev/documentation/components/amp-bind/#bindings) and that's great, but I'm not sure that's true across the board? I haven't vetted anything.

Things that would need doing:
 - [ ] Ensure runtime interprets both forms (and has reasonable behavior if conflicting values)
 - [ ] Ensure validator allows both forms
 - [ ] Ensure cache transforms understand both forms
 - [ ] ...?

What do people think? Is this harder than I expect? Would anybody find it useful?

**Comment by Gregable** [comment]
@jridgewell would this be something runtime would be interested in collaborating on as a Fixit item?

**Comment by Gregable** [comment]
Closing due to lack of interest.
