### ISSUE TITLE
`amphtml-validator` Support Node 13 

### ISSUE THREAD

**Issue by farnabaz** [ampproject/amphtml#26408]
Is there any specific reason to not support node 13 on `amphtml-validator`?

https://github.com/ampproject/amphtml/blob/master/validator/nodejs/package.json#L12-L14

**Comment by honeybadgerdontcare** [comment]
@rsimha  @sebastianbenz thoughts?

**Comment by rsimha** [comment]
We originally supported only even numbered versions of `node` in order to restrict the versions to those that would eventually become an LTS version.

Given that the `amphtml-validator` package is used externally, I'm supportive of expanding the list of versions.

If the folks on @ampproject/wg-caching are fine with it, I'm open to simply removing the `engines` section from the `package.json` file and allowing developers to use whatever version they like, and allowing other error messages to dictate whether they have a compatible version of `node` or not.

WDYT?

**Comment by kristoferbaxter** [comment]
How about specifying a minimum version corresponding with the lowest supported LTS version? This could assist with removing some boilerplate code in the module too (like wrapping fs.readFile in a promise).

**Comment by Gregable** [comment]
I have no problem with this.

**Comment by sebastianbenz** [comment]
SGTM as well. For lower version we should stick with Node 8 at least until end of this year (it's official EOL).

**Comment by kristoferbaxter** [comment]
Good news, Node 8 EOL was Dec 2019. 
You need only support 10+.

See https://nodejs.org/en/about/releases/

**Comment by sebastianbenz** [comment]
🤦 it's already 2020

**Comment by rsimha** [comment]
> 🤦 it's already 2020

The Internet told me that we're now closer to 1/1/2050 than we are to 1/1/1990.

**Comment by rsimha** [comment]
> You need only support 10+.

When I spoke to @MylesBorins at Open JS last month, he mentioned to me that the `engines` section is likely to be deprecated soon, and that a better way of enforcing `node` versions in a repo is to have tests / CI return an error for incompatible versions. We already do this for `amphtml` via [build-system/common/check-package-manager.js](https://github.com/ampproject/amphtml/blob/master/build-system/common/check-package-manager.js).

My instinct at this point is to delete the `engines` section from all `package.json` files inside `amphtml`, including the ones in `validator/` and its sub-directories.

Does this work for everyone?

**Comment by rsimha** [comment]
Reopening this issue because I realized we still need to push a new version of `amphtml-validator` for the fix to take effect.

**Comment by honeybadgerdontcare** [comment]
@rsimha we'll publish a new version of `amphtml-validator` and `gulp-amphtml-validator`

**Comment by honeybadgerdontcare** [comment]
Theses are now published with `engines` removed. `amphtml-validator` at `1.0.30` and `gulp-amphtml-validator` at `1.0.3`. #26774
