### ISSUE TITLE
Urgent help required - How to do automatic copy to clipboard

### ISSUE THREAD

**Issue by kalyie** [ampproject/amphtml#26405]
Hi Team,

we are developing a coupon website which will have multiple coupons for stores 
like below 
![image](https://user-images.githubusercontent.com/60026306/72658973-7237bd80-39de-11ea-96ea-2b1bca83d771.png)

now problem is when user click on get code we want the coupon to be copied automatically to clipboard and this copying to clipboard should happen in new window which opens when user click on get code 
![image](https://user-images.githubusercontent.com/60026306/72658993-c17dee00-39de-11ea-93d8-f940957ebc50.png)

we wanted to know how to do this in amp ?

we tried using below way 
https://amp.dev/documentation/examples/interactivity-dynamic-content/copy_button/

but this way leads to n - number of requests on page load and reduces performance 
as for n number of coupons  there will be n numbers of button.html file 

what is optimal way to copy to clipboard in amp ?

steps :

1) open link https://www.grabon.in/dominos-coupons/
2) click on get code then a new window opens which says "Code Successfully Copied!"
3) so in that new window we want amp code which copies the coupon code to clipboard 

Please guide me on this urgently 

Thanks

**Comment by wassgha** [comment]
Related to #4853

**Comment by choumx** [comment]
Closing as dupe.
