### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by magadetejas5** [ampproject/amphtml#26411]
Plese add Bootstrap

**Comment by samouri** [comment]
@magadetejas5, can you please provide more details about what you are asking for?
I'm assuming you are referring to [this bootstrap](https://getbootstrap.com/).

We don't allow for 3p js on the page (except for in a sandboxed iframe),and we also have limits on the size of included CSS.

See the answers to a similar question here: https://github.com/ampproject/amphtml/is.
