### ISSUE TITLE
[iGA, iOS 13] AMP components fail to bootstrap on page

### ISSUE THREAD

**Issue by RuChuanLin** [ampproject/amphtml#26410]
## What's the issue?

We have observed that when opening AMP pages from Google APP for the first load, every AMP related tag is not working well.

We have tested for the following devices:
- iPhone XR (iOS 13.3)
- iPad Air (iOS 12.1.1)
- XiaoMi 9T (Android 9)

Only iPhone XR has this issue.

## How do we reproduce the issue?

1. Open Google App
![image](https://user-images.githubusercontent.com/22973504/72705888-9094e900-3b97-11ea-8fea-a2cdbaa1a173.png)

2. Type the keyword "lynx yahoo", and click the result as following:

![image](https://user-images.githubusercontent.com/22973504/72708347-7b22bd80-3b9d-11ea-9b9a-879b321435d8.png)

You can see the URL to check if you enter the right webpage:
https://tw.buy.yahoo.com/?sub=838

3. You can see that every AMP related HTML tags is blank.

![image](https://user-images.githubusercontent.com/22973504/72708461-ba510e80-3b9d-11ea-8dbd-ba10ab59f111.png)
![image](https://user-images.githubusercontent.com/22973504/72708466-bfae5900-3b9d-11ea-9b62-efb611e92523.png)
![image](https://user-images.githubusercontent.com/22973504/72708469-c341e000-3b9d-11ea-8d5a-0786d57ee54b.png)
![image](https://user-images.githubusercontent.com/22973504/72708473-c5a43a00-3b9d-11ea-9bc4-1c71471d94a9.png)

There are some visible elements, which are not amp elements but basic HTML elements.

4. When I click the home link of this page, then I will get every element to work fine.
![image](https://user-images.githubusercontent.com/22973504/72708601-10be4d00-3b9e-11ea-8950-eb00d9661c6d.png)

I assert that this problem is caused by wrongly loading AMP JavaScript, or I could not figure out the reason why only AMP related elements were missing.
Aside from that, other browsers like Safari, Google Chrome are problem-free with it even in the same device.

## What browsers are affected?

iPhone XR (iOS 13.3), Google App

**Comment by choumx** [comment]
I can reproduce this. The page is more easily found with the query "Lynx官方旗艦店". 

Filed internally: `b/148783122`

**Comment by RuChuanLin** [comment]
@choumx @jridgewell This issue has been open for a while, we need to fix this problem as soon as possible because we think we lose our clients when they find there are nothing to be browsed.

If you are not nice to handle this issue, could you provide me ways to debug on Google App Browser? It seems to be hard to find out development tools on the Internet.

**Comment by choumx** [comment]
Sorry for the delay, I think this is a bug in the Google iOS app. I've followed up with the team internally, but can you also file feedback in the app itself?

**Comment by RuChuanLin** [comment]
Hi, I have reviewed most of our pages and I found something interesting.
The following two pages are made from 2 template, but very similar from each

- https://tw.buy.yahoo.com/?sub=656
- https://tw.buy.yahoo.com/act/flagship/story/656.html

I searched on Google App for both, the former does not show AMP tag, while the latter works nice.

I cloned both html and compared them. There are no big different except the meta content url. As you can see below, on the left side shows the former, the content url contains '?' and '=' characters, while it does not on the other side.

![image](https://user-images.githubusercontent.com/22973504/82071881-4963d280-9709-11ea-8bd2-7c183f61cbcd.png)

**Comment by RuChuanLin** [comment]
If you need to reproduce it, here are the steps
### For the former
keyword : `點睛品官方旗艦館`
![image](https://user-images.githubusercontent.com/22973504/82073200-803ae800-970b-11ea-899f-d1a4655900c3.png)

### For the latter
keyword : `YAHOO旗艦故事館`
![image](https://user-images.githubusercontent.com/22973504/82073283-9e084d00-970b-11ea-8093-887adc803db8.png)

**Comment by RuChuanLin** [comment]
How do I file feedback to that app? On App Store?

**Comment by RuChuanLin** [comment]
@choumx  How do I file feedback to that app? On App Store?

**Comment by RuChuanLin** [comment]
@choumx I have commented Google App on iOS App Store. Is there anything new?
