### ISSUE TITLE
Validator: Add support for rel="noopener"

### ISSUE THREAD

**Issue by steffenweber** [ampproject/amphtml#2641]
The new attribute value `rel="noopener"` can help to prevent phishing in Chrome 49+ and Opera 36+ (see https://mathiasbynens.github.io/rel-noopener/).

However, the `noopener` value currently does not validate. The AMP validator 1457721872758 says:
```
The attribute 'rel' in tag 'a' is set to the invalid value 'noopener'.
```

**Comment by Gregable** [comment]
Agreed, we should allow that value.

**Comment by rudygalfi** [comment]
Closed by #2711.

**Comment by Gregable** [comment]
FYI, this will be visible on the cdn.ampproject.org validator in about an hour.

**Comment by steffenweber** [comment]
Thanks!
