### ISSUE TITLE
amp-form: AMP Validation doesn't allow value 'tooShort' for 'visible-when-invalid' attribute

### ISSUE THREAD

**Issue by RafalOddslife** [ampproject/amphtml#26412]
## What's the issue?

When using amp-forms AMP Validation doesn't allow value 'tooShort' for 'visible-when-invalid' attribute. It returns an error:
> The attribute 'visible-when-invalid' in tag 'span' is set to the invalid value 'tooShort'.

'tooShort' is correct value and should be supported (https://developer.mozilla.org/en-US/docs/Web/API/ValidityState/tooShort). For other attribute values like 'tooLong' it works fine.

Issue was already spotted here: https://github.com/ampproject/amphtml/issues/5268#issuecomment-405173609

In _validator-main.protoascii_ I can't find _tooShort_ as allowed value:
https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii#L6722

## How do we reproduce the issue?

Code:
https://glitch.com/~misty-helicona

1. Run page: https://misty-helicona.glitch.me/#development=1
2. You will find error in console

> AMP validation had errors:
> https://misty-helicona.glitch.me/:38:6 The attribute 'visible-when-invalid' in tag 'span' is set to the invalid value 'tooShort'.

## What browsers are affected?

It doesn't work for me in Chrome 79.0.3945.117 but I guess it affects all browsers

## Which AMP version is affected?

2001071857360

**Comment by Gregable** [comment]
This isn't typically an attribute _set_ by users, it's instead read. However, I agree that there is no reason to disallow it, so let's implement. Thanks for the report.

**Comment by Gregable** [comment]
This will roll out within about a week.
