### ISSUE TITLE
`gulp dist` does not work on Python 3

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#26425]
Tangentially related: #26279

**Comment by rsimha** [comment]
`gulp dist` uses [Nailgun v1.0](https://github.com/ampproject/amphtml/blob/master/third_party/nailgun/nailgun-runner), which is a python script used to launch a reusable instance of closure compiler.

Nailgun is technically supposed to be python 3.0 compatible (https://github.com/facebook/nailgun/pull/128), but there's likely something else wrong.

Happy to investigate at some point.
