### ISSUE TITLE
instanceOf HTMLElement returns false due to polyfill 

### ISSUE THREAD

**Issue by vidhu** [ampproject/amphtml#26424]
## What's the issue?

`HTMLElement` is overridden by a polyfill. This causes the `instanceOf` operator to return `false` in cases where it should return `true`

## How do we reproduce the issue?
Here is a minimal reproducible example

```
<!DOCTYPE html>
<html>
  <head>
    <script type="text/javascript" src="//cdn.ampproject.org/v0.js"></script>

    <script>
      (function() {
        let el = document.getElementById("test");
        console.log(el instanceof HTMLElement);
      })();
    </script>

  </head>
  <body>
    <div id="test"></div>
  </body>
</html>
```
The console should log out `true` since `<div id="test"></div>` is an instance of `HTMLElement` however it logs out false.

[Running example](https://codesandbox.io/s/dreamy-tree-w60v9)

## What browsers are affected?

All browsers?

## Which AMP version is affected?
Version 2001071857360

**Comment by choumx** [comment]
Can you share a sample use case on a valid AMP page? AMP doesn't allow `<script>` as written above.

**Comment by jridgewell** [comment]
It's not possible to polyfill `HTMLElement` and preserve the `instanceof` check here. Custom elements are required to use `Foo extends HTMLElement`, which means we must change the value of `HTMLElement` global. Natively constructed elements will still inherit directly from the intrinsic class, regardless of the global's current value. So `div instanceof HTMLElement` can't be properly done.

**Comment by Zielak** [comment]
Will it be safe to assume `div instanceof Element` would work as a workaround for a future?

**Comment by jridgewell** [comment]
When we no longer need the polyfill. This requires that both the browser natively support Custom Elements v1, and the project must not compile native classes to ES5. We're actively working on the second, and the first just takes time.

**Comment by acaroselli1** [comment]
core.js:6006 ERROR Error: Uncaught (in promise): Error: [Parchment] Unable to create [object HTMLDivElement] blot
Error: [Parchment] Unable to create [object HTMLDivElement] blot
    at new ParchmentError (quill.js:148)
    at Object.create (quill.js:178)
    at new Quill (quill.js:1153)
    at ngx-quill.js:324
    at ZoneDelegate.invoke (zone-evergreen.js:368)
    at Zone.run (zone-evergreen.js:130)
    at NgZone.runOutsideAngular (core.js:28195)
    at QuillEditorComponent.<anonymous> (ngx-quill.js:323)
    at Generator.next (<anonymous>)
    at fulfilled (tslib.es6.js:71)
    at resolvePromise (zone-evergreen.js:1209)
    at zone-evergreen.js:1116
    at fulfilled (tslib.es6.js:71)
    at ZoneDelegate.invoke (zone-evergreen.js:368)
    at Object.onInvoke (core.js:28267)
    at ZoneDelegate.invoke (zone-evergreen.js:367)
    at Zone.run (zone-evergreen.js:130)
    at zone-evergreen.js:1272
    at ZoneDelegate.invokeTask (zone-evergreen.js:402)
    at Object.onInvokeTask (core.js:28255)

**Comment by consigliere23** [comment]
Any solution for this?
