### ISSUE TITLE
JavaScript error in Google AMP Viewer

### ISSUE THREAD

**Issue by staceyfenton** [ampproject/amphtml#26453]
## What's the issue?

We have been experiencing an intermittent issue in the Google AMP Viewer. Navigating away from the AMP page to a non-AMP page and then clicking the browser's back button to return to the AMP page sometimes results in a JavaScript error which prevents the AMP page from being displayed.

## How do we reproduce the issue?

1. Perform a Google search with AMP results
2. Click on an AMP page
3. Click on a link within the AMP page which takes you to a non-AMP page
4. Click the browsers back button to return to the AMP page - sometimes the AMP page fails to load because of a JavaScript error. 

Here are some screenshots from Chrome Dev Tools which show the error: 

<img width="650" alt="Screenshot 2020-01-21 at 19 27 16" src="https://user-images.githubusercontent.com/2691031/72989935-2a9ea080-3de7-11ea-950c-1c2819e4a4a2.png">

<img width="650" alt="Screenshot 2020-01-21 at 19 27 53" src="https://user-images.githubusercontent.com/2691031/72989942-2ecabe00-3de7-11ea-9436-b6b957f606e6.png">

## What browsers are affected?

Have replicated this in Chrome for Android and Safari for iOS but issue only happens intermittently.

## Which AMP version is affected?

Current version is 2001071857360 but we have noticed this behaviour in previous versions as well.

**Comment by ericfs** [comment]
Filed internal issue: b/151612730

Does this happen for particular documents only? Can you share the URL from the screenshot?

**Comment by staceyfenton** [comment]
@ericfs the AMP page from the screenshot is https://www.comparethemarket.com/ps/van-insurance/?amp 

We have several AMP pages on our website and have noticed the behaviour across multiple pages. However, the issue is intermittent and doesn't happen all the time.

**Comment by ericfs** [comment]
Thanks. I can see this result showing up for the query [compare van insurance], though I am not able to reproduce so far.
