### ISSUE TITLE
Link for fonts doesn't accepts Material Icons

### ISSUE THREAD

**Issue by carusogabriel** [ampproject/amphtml#2645]
Hello there,

Recently I started use the [Material Icons](https://design.google.com/icons/) with an AMP page, and the follow tag `<link rel='stylesheet' href="https://fonts.googleapis.com/icon?family=Material+Icons">` causes an error: `The attribute 'href' in tag 'link rel=stylesheet for fonts' is set to the invalid value 'https://fonts.googleapis.com/icon?family=Material+Icons'.`. Is something I'm doing wrong, or AMP does not support Material Icons?

Thanks

**Comment by amphtml-team** [comment]
Github appears down.

We allow the prefixes of:
https://fonts.googleapis.com/css?
https://fonts.googleapis.com/earlyaccess/css?

Any issues with:
https://fonts.googleapis.com/icon?

-Greg


---------- Forwarded message ----------

**Comment by dvoytenko** [comment]
@Gregable I don't have any issues with it. Please proceed to whitelist.

**Comment by Gregable** [comment]
Thanks.

**Comment by rudygalfi** [comment]
Closed via #2711.

**Comment by Gregable** [comment]
FYI, this will be visible on the cdn.ampproject.org validator in about an hour.
