### ISSUE TITLE
Amp-call-tracking - ability to return html rather than strictly returning text.

### ISSUE THREAD

**Issue by SimonHogstromRonbol** [ampproject/amphtml#26469]
## Describe the new feature or change to an existing feature you'd like to see

The formattedPhoneNumber returned by amp-call-tracking is only allowed to return as text, but i would like it to be able to return html to make more complex things like buttons with icons and other neat gadgets, easier to make with amp-call-tracking.

## Describe alternatives you've considered

Our solution right now is to have the before and after elements of the a tag inside amp-call-tracking act as icon and icon background, but it gets really hacky very fast, it becomes difficult to keep the design consistant between call-tracking buttons and normal a tags, when the markup is different.

## Additional context

In the amp-call-tracking component, a phoneNumber and a formattedPhoneNumber is returned from the call-tracking script, the phoneNumber variable gets applied to the href of the a tag inside the amp-call-tracking component, and the formattedPhoneNumber overwrites the textContent inside the a tag, and that is great, but in the real world the a tag might also contain an icon, or have part of the phone number in a different color than another part, so my suggestion would be to have the formattedPhoneNumber variable return HMTL instead.

I found the exactly spot in the amp-call-tracking script:
https://github.com/ampproject/amphtml/blob/master/extensions/amp-call-tracking/0.1/amp-call-tracking.js it's on line 89.

![amp-call-tracking](https://user-images.githubusercontent.com/32469390/73053861-317def80-3e89-11ea-9a03-86016f0e2f07.png)

I would like for this to change to .innerHTML rather than .textContent

According to https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#Differences_from_innerHTML .textContent is more performant than .innerHTML so maybe a solution to keep the great performance of .textContent would be to have an attribute on the amp-call-tracking element called return, where you could have return="html" or return="text" with the default being text.

A different solution to that same problem would be instead of only accepting phoneNumber and formattedPhoneNumber, we could have a 3rd formattedPhoneNumberHTML to be accepted if defined.

**Comment by SimonHogstromRonbol** [comment]
@morsssss this is the one i emailed about. :)

**Comment by morsssss** [comment]
Great! I'm glad you're contributing :)

**Comment by alanorozco** [comment]
@SimonHogstromRonbol 

We can't allow plain `innerHTML` from JSON for security reasons.

`amp-call-tracking` was also designed with plain text labels intentionally.

Maybe a single-item [`<amp-list>`](https://go.amp.dev/amp-list) suits your needs better since it takes templates?

**Comment by morsssss** [comment]
Simon, I'm sorry - when I encouraged you to file an issue, I didn't quite grasp that you wanted to change this component to insert arbitrary HTML. That's something AMP doesn't do, as far as I know, since it doesn't want people to inject HTML that makes elements move on the page, inject `<script>`'s, etc.

Could this styling be done with `<amp-list>` and a cleverly designed mustache template? If not, maybe a case for `<amp-script>`?

**Comment by SimonHogstromRonbol** [comment]
This makes sense, i get why this can't be implemented at this time, i'll see if i can use amp-list instead. thank you for looking into it though.
