### ISSUE TITLE
🌸 Cherry-pick request for #26478 into #2001141706210 (Pending)

### ISSUE THREAD

**Issue by micajuine-ho** [ampproject/amphtml#26477]
# Cherry-pick request

|       Issue       |       PR       | Production?  |     RC?      | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :----------: | :----------: | :-----------------------------------------------------------------------------: |
| #26478| #26324 | **YES** | **NO** |                               #26356  |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

It is breaking previous analytics usage

## Why is a RC cherry-pick not needed?

The fix (#26324) is already in RC/Experimental/Beta.

The breaking change (#26157) was part of a different cut and was promoted to prod

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

Vars in analytics requests can be arrays. Numbers in the arrays breaks it:
{
  vars: [1331]
}

| Users affected                                   | Impact                                                                       |
| ------------------------------------------------ | ---------------------------------------------------------------------------- |
| <_Which users were affected? Roughly how many?_> | <_How were users affected? E.g. partial or complete loss of functionality?_> |

## Root Causes

1. Cut didn't include the fix, like we had intended

## Action Items

| Action Item                   |               Type               |     Owner     |      PR #      |
| ----------------------------- | :------------------------------: | :-----------: | :------------: |
| <_E.g. Add integration test_> | <_Investigate/Mitigate/Prevent_> | @<_USERNAME_> | #<_PR_NUMBER_> |

## Lessons Learned

Double check that fixes are in the same cut as bug

### Things that went well

-

### Things that went wrong

-

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by lannka** [comment]
Should create a separate issue to describe the bug in production. My understanding is that the fix to a long standing issue (#21224) introduced a new regression?

**Comment by micajuine-ho** [comment]
I will create a new issue

**Comment by lannka** [comment]
LGTM

**Comment by cramforce** [comment]
LGTM

**Comment by gmajoulet** [comment]
We decided to not cherry-pick production and skip this week's production release. Canary is unaffected by this issue and will be pushed to production next Tuesday.
