### ISSUE TITLE
I2I: amp-playon NEW MEDIA component

### ISSUE THREAD

**Issue by PlayOncontent** [ampproject/amphtml#26471]
**## Describe the new feature or change to an existing feature you'd like to see**

We are a Spanish video company who provide video technology to the biggers newspapers, networks and sites in Spain and LATAM.

We have our own HTML5 and JS videoplayer, IAB & IMA full compliant, and we need a way to help our customers to implement it in their AMP sites, like they can do with the amp-youtube or amp-brightcove components.

Now the player can be added to a site using an <iframe> and <script> tags who calls a function, .js file and a few parameters (video_id, affiliate_id, player_width and player_height):

```html
<iframe id="[id_video]_[random]" width="[width]" height="[height]" ></iframe><script type="text/javascript" src="//domain/file.min.js"></script><script type="application/javascript">(function(){IFRIENDLY_DATA.init({"idFrm":"[id_video]_[random]","url":"video/[id_user]/[id_video]/[width]/[height]","domain":"//domain"});})()</script>
```

**## Describe alternatives you've considered**

There´s no alternative as our customers want to use our tech and monetize videos using it.

**## Additional context**

Attached 2 screenshoots about the player working. 

<img width="746" alt="player2" src="https://user-images.githubusercontent.com/60256308/73062773-70b63b80-3e9d-11ea-8958-84f46b78b951.png">
<img width="687" alt="player1" src="https://user-images.githubusercontent.com/60256308/73062777-714ed200-3e9d-11ea-9ebb-81a58b2f9cf2.png">

**Comment by alanorozco** [comment]
@PlayOncontent 

Thank you for your I2I.

Have you looked into using [`amp-video-iframe`](https://amp.dev/documentation/components/amp-video-iframe/#for-third-party-video-vendors)? 

It will give you the harnesses you need. I believe you only need need to create a hosted document that can dynamically insert videos from URL using the code snippet you included.

**Comment by PlayOncontent** [comment]
Hello @alanorozco 

Yes, we tried but it´s not possible: we have problems with demand platforms (ads).

We need a component like brightcove, jw-player or dailymotion use (as we do quite the same, but free for our publishers).

Thank you.

**Comment by alanorozco** [comment]
@PlayOncontent 

> we have problems with demand platforms (ads).

Could you specify these problems in more detail and file issues if appropriate?

> We need a component like brightcove, jw-player or dailymotion use (as we do quite the same, but free for our publishers).

This requires more details:

- What's the HTML API for the proposed component?
- What does this `//domain/file.min.js` script do? AMP does not allow embedding third-party Javascript, this would require an intermediate 3p frame to embed it.
- Is this is an intent for you/your team to implement this, or a request for others to do so?

If you wish to implement this, please read through the [vendor-specific player spec.](https://github.com/ampproject/amphtml/blob/master/spec/amp-3p-video.md) for more information.
