### ISSUE TITLE
I2I: Allow amp-list to render from amp-state initially

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#26473]
**summary**

Initially proposed in https://github.com/ampproject/amphtml/issues/15647, this I2I is about allowing `amp-list` to render from `amp-state` for its first render, instead of only subsequent ones.  In order to support this, we can create a new [uri scheme](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Definition), `amp-state:`. The path that follows would then refer to an amp-state path.
  
For example,
```html
<amp-list src="amp-state:data.path">...</amp-list>
```

In the above example, we would expect the value at `data.path` to contain the exact same json that a properly configured server would have returned. This means json with an array at `items`, as well as an optional `load-more-src`. Note that both of those required keys would still be configurable via `amp-list` attributes (`items`, and `load-more-bookmark` respectively).

**motivation**

- Reduces the amount of effort required for publishers to show stale data, since they don't need to duplicate the template rendering logic on the server.

**prototyping status**
See https://github.com/ampproject/amphtml/pull/26284, for a prototype of this feature behind a flag.

**Comment by samouri** [comment]
**primary question for design review**
- Should the `amp-state:` uri require that the entire json is SSRed (and therefore available on init) or should a `<amp-state src="..."></amp-state>` also be allowed.
- Assuming we also create a scheme like `fn:` or `amp-script:` for specifying js functions, are we then adding too many new protocols (https://github.com/ampproject/amphtml/issues/26474).

**Comment by samouri** [comment]
@alanorozco and I just had an interesting discussion where he proposed a potential second step to optimize performance:
- we should allow for a full statically rendered `amp-list`, so that no rerender is needed on load (best ux possible)
- we could have the AMP Cache convert any `amp-list` elements that are initialized from amp-state into statically rendered versions which lets it skip the CSR.

My gut says that both of these could/should be pursued after first deciding on the first parts of the I2I (syntax, expected value in amp-state, etc.).

**Comment by samouri** [comment]
Answers:
- `amp-state: ` as a URI is fine. Lets make sure it couldn't conflict with other URIs.
- Should be a warning if someone tries to depend on url-based `amp-state`, since its just a weird pattern
- The above bullets are irrelevant since we should pursue the simpler option without a custom uri and instead have json as the first element of the amp-list.

**Comment by morsssss** [comment]
This is indeed similar! And I agree that it's cleaner.

My only concern is that this will eliminate this use case: a site server-side renders JSON in order to render a template and also so that that JSON can populate a state variable. I'm thinking of a case where the site will allow the user to make changes to the JSON.

We did this in the AMP Camp demo on [product pages](https://camp.samples.amp.dev/product-details?categoryId=women-shirts&productId=L1035). For example, let's say shirts come in different colors, and those color options depend on the shirt. In this case, you might have JSON object that stores both the options and the current selection. You want to display those options with a template, and you also want to let the user choose their preferred option.

I wonder if this use case ever occurs in the real world, though? For that, I'd defer to people like @pancham348, @dritte, and @danieltxok, who commented on #15647. I believe @mattwomple has wanted before to be able to load JSON in the document `<head>`... and so he might also have an opinion. They'd also know more about how they'd like to serve an `<amp-list>` with no data to caches and an <amp-list> with SSR'd data from their origin.

/cc also @demianrenzulli and @antoinebisch

**Comment by morsssss** [comment]
As no one has commented yet... maybe @alankent ? You're an awesome Github issue commenter :)

**Comment by alankent** [comment]
There have been other threads of discussion, so apologies if this is duplicate content.

There is amp-list with `src=...` and `[src]=...`. The former the server precomputes for the first page load, the latter supports recomputing the list when AMP state updates change a bind variable in the expression.

One of the observations for amp-list populated from AMP state is that it makes less sense having the two modes. You just want the amp-list to display the current AMP state value – on first page load and afterwards as state is updated. Did we really want to repeat AMP state bindings for initial page load and subsequent updates?

This then links up with how to initialize AMP state on page load. Can you initialize AMP State (which automatically updates the amp-list on page load) and render the pages using the Mustache template. After that, updates to AMP State trigger a refresh to the amp-list contents. Can I avoid specifying two attributes (`src="amp-state:foo" [src]="foo"`).

This also links up with the suggestion to be able to pre-render amp-list contents. If the server does prerender the initial results of the amp-list, how to ensure it does not get recomputed in the client.

Some of these points may be out of scope for what is considered. E.g. rendering amp-list from initialized AMP State on initial page load goes against some of the AMP principles like "the server must pre-render the page, then AMP bind expressions can be used to update parts of the page". In practice this can be problematic – you have to maintain an AMP Mustache plus a server side template to generate identical markup to the AMP Mustache template.

Sorry if this got off track, but want to make sure the full experience fits together well.

**Comment by samouri** [comment]
Thank you Ben and Alan for your insights! Ben, thank you for pointing to the use-case of wanting the json both in `amp-state` and as the data for initial render. Thats a compelling reason to make the `amp-state` based option.

So that tradeoff I see is:
- Initializing from json makes development more straightforward (and more performant!) for any devs without an investment in `amp-state`/`amp-bind`.
- Initializing from `amp-state` is slightly slower and requires this new URI, but is unquestionably better for advanced `amp-bind` use cases (e.g. AMP Camp). Also, as Alan says, it is a bit awkward needing to specify the same piece of state for both `src` and `[src]`.

Since the two options don't conflict per se, I'd prefer to start with the less intrusive option (initialize from json), and then reevalute how prevalent the "initialize from amp-state" case is.

> pre-render amp-list contents

We can definitely get there! I'll do some preliminary investigations into how much effort this would be to build into `amp-list`. It doesn't _feel_ like it should be too much considering it mostly amounts to avoiding work. That said, when it comes to sizing tasks, feelings can't be trusted :)

**Comment by samouri** [comment]
I keep vacillating on this decision, but a couple of thoughts made me switch back, for hopefully the last time, to preferring `amp-state:` (keeping in mind that both can still coexist if we have a need).

1. Starting off with the solution that satisfies all stakeholders is better than starting off with the limited option (why not make developers happy).
2. The performance benefit of child json vs. `amp-state` disappears the second we enable the [static rendering of amp-list](https://github.com/ampproject/amphtml/pull/26765) as well as turn on an automatic transformation in the AMP Cache.
3. Even though it is slick for the basic case, there are awkward components with the json approach as well. For example, if using multiple `amp-list` components that depend on the same json, you'd have to render that json in each component (the amp-state solution doesn't have this issue).

**Comment by morsssss** [comment]
#3 is a really good point - even though I haven't seen that use case, I admire that you're thinking ahead to use cases others may experience.

That's why I like `amp-state:` - it covers a case that would otherwise not be covered. I still wish others would comment here as well... @mattwomple ? last chance?

**Comment by samouri** [comment]
Leftover tasks:
- [ ] merge race condition bugfix https://github.com/ampproject/amphtml/pull/26530
- [ ] manually test in various forms and see if there are any other helpful warnings we could emit.
- [ ] remove feature flag
- [ ] add documentation to amp.dev

**Comment by mdmower** [comment]
Thanks for the ping @morsssss (and sorry for the github account change).

 I really like this succinct summary of `src` and `[src]` by @alankent :
> There is amp-list with `src=...` and `[src]=...`. The former the server precomputes for the first page load, the latter supports recomputing the list when AMP state updates change a bind variable in the expression.

I like it so much that I think it should guide two decisions:
1. `amp-list` has two distinct means of sourcing data. Let's not introduce a third if it's not strictly necessary. As you've demonstrated, `src` will continue to work with a new URI scheme.
1. Still require bind `[src]` to re-render templates automatically based on bind changes. Give publishers the option of using state `foo` to render a template once. For better or worse, `<amp-list [src]="foo">` re-renders an entire mustache template for _any_ property under `foo` that is updated, even if that property is unused by the template. By giving publishers a render-once option, they can safely let elements rendered by amp-list depend on `foo.bar` without worry that amp-list will re-render a template and potentially wipe out user input. 

On a side note, it might be nice to add hidden support for syntax `[src]="amp-state:foo"` as well. It doesn't need to be documented, but it would be nice if it "just happens to work" for developers who cringe at the inconsistency of `src="amp-state:foo"` and `[src]="foo"` .

**Comment by morsssss** [comment]
Thanks @mdmower ! Glad I found your github persona again 😉

**Comment by sebastianbenz** [comment]
Sorry for being late to the party:

1. I'm not a fan of the inline JSON. The main reason (IMO) for initializing amp-list is re-using amp-state (use case initial render and filtering on the same data set). Inline JSON means that you'd need to duplicate the JSON inline and for amp-state. I see few scenarios were inline JSON would be useful.
2. I'm not a fan of the data URI either. I agree with Matt and Alan, we already have two ways to set amp-list data, which are already hard enough to understand. Adding a third one is confusing. I would not add this at all.

My suggestion is: allow `[src]` bindings on page load - iff `binding="always"` and no `src` is set. Reason: in this case we're already evaluating amp-state on page load and @samouri's contra against this approach is not quite valid:

> pros: don't need to wait for amp-bind to finish init, and can stay consistent with bindings never being evaled on first load.

**Comment by samouri** [comment]
> My suggestion is: allow [src] bindings on page load - iff binding="always" and no src is set. Reason: in this case we're already evaluating amp-state on page load and @samouri's contra against this approach is not quite valid.

In terms of performance, allowing `[src]` on load is the worst of all three options. Inline JSON doesn't require amp-bind at all, the amp-state URI requires amp-bind, but doesn't need the web worker to complete initialization, and then `[src]` support requires the full initialization of bind to complete (so that it can support bind expressions).

That said, you've made a good case for it:
- It is the most simple option to understand
- We already have support for `binding=always` which waits for the full amp-bind init anyway. This wouldn't make it the delay any worse, but it would expand the use cases where that mode would be used.

**Comment by samouri** [comment]
@sebastianbenz, due to the performance cost associated with `binding="always"`, I'm going to push ahead with the `amp-state:` uri solution. Hopefully we can create a cleaner API for a v2 of `amp-list`.

**Comment by morsssss** [comment]
I do think that
```HTML
<amp-list src="amp-state:foo" [src]="foo.items">
```
is confusing. I'm sure you've already thought of this - but is there any other way to make this consistent? Treating the JSON at the URI in the exact same way as JSON from a server?

Honestly, I've long found the `items` thing confusing too, but I know we can't just change that spontaneously :)

If we can't make this more consistent, we'll just have to provide lots of examples with your `items="."` attribute.

**Comment by samouri** [comment]
> is confusing. I'm sure you've already thought of this - but is there any other way to make this consistent? Treating the JSON at the URI in the exact same way as JSON from a server?

One of the confusing parts is that I'm doing exactly that 🤕. Its the bound `[src]` that has different requirements from the server response. 
- `src` expects to be pointed at a json obj with items
- `[src]` expects to resolve to an array

**Comment by morsssss** [comment]
alas, we are probably stuck then!

**Comment by samouri** [comment]
This feature was first implemented as an experiment in https://github.com/ampproject/amphtml/pull/26284 and then launched in https://github.com/ampproject/amphtml/pull/27180.

Closing the thread 🎉
