### ISSUE TITLE
Numbers in arrays vars breaks amp-analytics 

### ISSUE THREAD

**Issue by micajuine-ho** [ampproject/amphtml#26478]
Issue for cherry-pick #26477

In prod, analytics request that uses numbers in arrays breaks it:
```
{
  ...
  vars: ['foo', 1331]
}
```

Bug is caused by: #26157 

The fix is in RC/Beta/Experimental: #26324

**Comment by lannka** [comment]
I assume we are not seeing same error messages in our current RC? (which has the fix already).

**Comment by micajuine-ho** [comment]
That is correct

**Comment by micajuine-ho** [comment]
Closed via #26477
