### ISSUE TITLE
🌸 Cherry pick request for 26484 into 26356 (cherry-picked)

### ISSUE THREAD

**Issue by powerivq** [ampproject/amphtml#26483]
# Cherry-pick request

|       Issue       |       PR       | Production?  |     RC?      | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :----------: | :----------: | :-----------------------------------------------------------------------------: |
| #26484 | #26479 | **YES** | **YES** |                               #26356                                |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md#cherry-pick-criteria)?

This is a production-affecting bug.

## Why is a RC cherry-pick not needed?

Not applicable.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

We are refactoring several interfaces out from `resources` service to a `mutator` service. amp-auto-lightbox uses the API from `resources` service and was not switched to the new one. It was not caught until on production, and console error log triggered the alarm.

| Users affected                                   | Impact                                                                       |
| ------------------------------------------------ | ---------------------------------------------------------------------------- |
| all users using amp-auto-lightbox on prod | partial loss of functionality of amp-auto-lightbox |

## Root Causes

1. amp-auto-lightbox uses `element.getResources` to obtain the service object, and the type checker is not able to find the type reference of that method. The type checker therefore failed to check whether the method call exists.

2. There is insufficient traffic for this single extension on canary that would have triggered an alarm.

## Action Items

| Action Item                   |               Type               |     Owner     |      PR #      |
| ----------------------------- | :------------------------------: | :-----------: | :------------: |
| https://github.com/ampproject/amphtml/issues/26750 | Prevent | @choumx | #<_PR_NUMBER_> |

### Things that went well

- The refactoring itself was splitted into phases, so that the final switch-over PR was not large and easy to be reverted.

### Things that went wrong

- Traffic on canary is not large enough for relatively infrequent code paths.

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by cramforce** [comment]
Prod rolled back already right?

Is there a second cherry-pick coming? I thought that was the case.

**Comment by gmajoulet** [comment]
The other cherry-pick is here: #26477

Both should be cherry-picked into prod before it is rollforwarded

**Comment by cramforce** [comment]
Approved

**Comment by gmajoulet** [comment]
We decided to not cherry-pick production and skip this week's production release.
Canary has been patched, is available as of a few minutes ago, and will be pushed to production next Tuesday.

Reassigning to @powerivq for the mini post mortem.

**Comment by erwinmombay** [comment]
closing this issue
