### ISSUE TITLE
Bookend images receive HTTP 200 but appear broken

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#26494]
Bookend images appear broken for this publisher, even though the request return a HTTP 200 code and the src seems valid:

https://www.washingtonpost.com/graphics/2020/world/amp-stories/mapping-coronavirus/

cc @ampproject/wg-stories

**Comment by Beethoven** [comment]
It's working for me here:

<img width="665" alt="Screen Shot 2020-01-27 at 06 38 51" src="https://user-images.githubusercontent.com/81638/73164053-e6a1e900-40cf-11ea-860b-9e90bb9942d6.png">

**Comment by Enriqe** [comment]
I don't seem to be able to repro either. Can you share the steps / device / browser where you see this?

**Comment by gmajoulet** [comment]
1. Open Chrome Devtools and emulate an iPhone
2. Open https://www.washingtonpost.com/graphics/2020/world/amp-stories/mapping-coronavirus/ and navigate to the bookend
3.
![image](https://user-images.githubusercontent.com/1492044/73192023-75296100-40f6-11ea-96bb-0474572263d7.png)

**Comment by Beethoven** [comment]
Emulating an iPhone same problem here.

**Comment by mszylkowski** [comment]
Just tested with chrome devtools > toggle device toolbar > iphone x and the images showed up correctly. Emptied cache and did hard reload, and they still loaded properly.

@gmajoulet @Enriqe Was this fixed? Can anyone repro it?

**Comment by gmajoulet** [comment]
It was probably an emulation bug (it was working on actual phones), I can't repro today.
