### ISSUE TITLE
Meta viewport properties cause validation error when extra whitespace is present

### ISSUE THREAD

**Issue by westonruter** [ampproject/amphtml#26496]
During work on the [AMP plugin](https://github.com/ampproject/amp-wp) for WordPress, @pierlon [discovered](https://github.com/ampproject/amp-wp/pull/4137#issuecomment-578467681) that a meta viewport tag formatted with whitespace surrounding the equals signs resulted in a validation error (as [seen in the Postmag theme](https://themes.trac.wordpress.org/browser/postmag/1.1.7/header.php#L15) for WordPress): 

```html
<meta name = "viewport" content = "width = device-width, initial-scale = 1.0" >
```

![image](https://user-images.githubusercontent.com/134745/73143769-e1eb1f80-4052-11ea-8a0e-9d1ddcf94389.png)

Nevertheless, both Chrome and Firefox seem to read the `viewport` properties just fine with the extra whitespace. So this appears to perhaps be a bug with how the AMP Validator parses the properties. 

The quick fix for the AMP plugin is for the sanitizer to trim the extra whitespace. However, if the whitespace is valid in browsers then it seems the AMP Validator should also be fine with it.

**Comment by westonruter** [comment]
cc @ampproject/wg-caching

**Comment by Gregable** [comment]
This has been fixed (thanks @honeybadgerdontcare ), awaiting push and release.
