### ISSUE TITLE
Actions and Events - Ability to add on="stuck:.." and on="unstuck:.." to elements

### ISSUE THREAD

**Issue by SimonHogstromRonbol** [ampproject/amphtml#26499]
## Describe the new feature or change to an existing feature you'd like to see

I would like to see the ability to react to when an element with position: sticky gets stuck to the page, or unsticks from the page on scroll.

The usecase for us is whenever we create a website with elaborate header elements, some of the content from said header elements, menu, logo (dependent on screensize) and so on, should follow the user on scroll,, but leave some as it is, it should also maybe resize a logo, og move a menu as the header sticks.

With an on="stuck:.." or on="unstuck:.." action, we would have full control of adding a classname "stuck" or "unstuck" to the menu, which then could provide us all the tools we need to modify the look of the header using CSS.
 
## Describe alternatives you've considered

Right now, our solution is using 2 amp-position observers, in 2 absolutely positioned divs, where 1 is positioned at the top, and one if positioned just outside the initial viewport at 100vh + 10px, and then we do our modifications using amp-animation.

This solution works for most usecases, but does not work if the page is reloaded while the user is already scrolled down.

Using amp-animation itself is also limiting since you can only use properties that are able to be animated, and since it is using css animations it isn't possible to debug using chrome dev tools.

An example of something that would be very difficult to do with animations, but relatively easy to do with classes would be an effect like this desktop menu header on the official world of warcraft website: https://worldofwarcraft.com/en-us/

## Additional context

Eric Bidelman wrote a great article on how we can return an event like this using an IntersectionObserver so we don't have to use scroll events and compromise performance.
https://developers.google.com/web/updates/2017/09/sticky-headers

**Comment by kristoferbaxter** [comment]
Thanks @caroqliu, assigning @kevinkimball who is working on a proposal for refactoring the `FixedLayer` system. This work ties in nicely.

**Comment by morsssss** [comment]
This was a nice idea! Does anyone have time to work on it in the near future?

@SimonHogstromRonbol , have you ever considered contributing to AMP yourself? If you'd like to work on this feature, we can help you get started.
