### ISSUE TITLE
Navigation is stuck after tapping quickly in an amp-story

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#26505]
1. Go to any story (e.g. https://www.telegraph.co.uk/visual-stories/anna-mellor-singapore-story/)
2. Tap quickly to navigate forward.
3. Tap quickly to navigate backwards.

After some combination of steps 2 and 3 I've found that navigation is stuck. The progress bar is not updated and I can't leave the current page.

Tested on iOS 13.3 with Chrome and Safari.

Maybe related to #25020

/cc @ampproject/wg-stories

**Comment by Enriqe** [comment]
Testing on a real device and monitoring the console I've found the following error:

```
[Error] SecurityError: Attempt to use history.replaceState() more than 100 times per 30 seconds
	replaceState (v0.js:193:487)
	replaceState
	e (v0.js:193:487)
	(anonymous function) (v0.js:200:108)
	(anonymous function)
	pd (amp-story-1.0.js:69:494)
	bl (amp-story-1.0.js:468:156)
	(anonymous function) (amp-story-1.0.js:465:369)
	(anonymous function) (amp-story-1.0.js:447:101)
	dispatchEvent
	ud (amp-story-1.0.js:70:657)
	(anonymous function) (amp-story-1.0.js:190:190)
	(anonymous function) (amp-story-1.0.js:190)
	Fk (amp-story-1.0.js:463:417)
	(anonymous function) (amp-story-1.0.js:448:298)
	(anonymous function) (amp-story-1.0.js:96:304)
	forEach
	(anonymous function) (amp-story-1.0.js:96:290)
	(anonymous function) (amp-story-1.0.js:104:346)
	(anonymous function)
```
After which, navigation is frozen until (I suspect) 30 secs have passed. After which, navigation is unblocked again.

**Comment by gmajoulet** [comment]
Cool! Great catch!

Let's throttle this to make sure it doesn't trigger more than 100 times every 30s?

https://github.com/ampproject/amphtml/blob/244d6476cae989c9e3219e9a9c5a637ab6914bac/extensions/amp-story/1.0/utils.js#L269-L278

**Comment by gmajoulet** [comment]
Can you also double check why we call `setHistoryState` that often? You'd need to change page every 330ms for 30s straight to hit this limit, we shouldn't be able to repro that easily.

**Comment by Enriqe** [comment]
Yep, I think debouncing/throttling the call should fix this. I think we just have to make sure to call `replaceState` before a `pushState` is performed.

Re. why it's firing that often, I've been playing around with it a bit and it seems that it has to do with the fact that we're calling it both from [onCurrentPageIdUpdate_](https://github.com/ampproject/amphtml/blob/1c5d54b5e3e4a2c108a558fa66b9cc22ca61058e/extensions/amp-story/1.0/amp-story.js#L1689) and [updateNavigationPath_](https://github.com/ampproject/amphtml/blob/1c5d54b5e3e4a2c108a558fa66b9cc22ca61058e/extensions/amp-story/1.0/amp-story.js#L1531) on each navigation. 

This makes the rate of quota 3.3 `replaceState`/second easily achievable, considering that 2 `replaceState` are performed per second.  E.g. Consider 3 taps per second cause 6 `replaceState`; you would be able to reach the quota in 16.67s

**Comment by gmajoulet** [comment]
Cool thanks for investigating!

1. I think throttle would be preferable over debounce so the history says as accurate as possible. The operation isn't expensive so that should be fine.
2. Could we stop storing `HistoryState.PAGE_ID` and rely on the last item of `HistoryState.NAVIGATION_PATH` instead? (1) would fix the issue but it's always cool to kill some. (Might be a diff PR)

**Comment by Enriqe** [comment]
Sounds good, I'll send out a PR soon 👍

**Comment by Enriqe** [comment]
Commenting what we ended up doing in the PR for future reference:

The issue will be mitigated by the removal of the duplicate `replaceState` that we were performing before this (It will make it harder to repro since users will have to tap through 100 pages faster than 3.33/s for 30s to reach the quota). Even if they reach the quota, they will be in a frozen state for a short time before the quota is reset.
