### ISSUE TITLE
Consider switching to the new private-var style for all private class-instance vars

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#26516]
E.g. `this.privateVar_` -> `this.#privateVar`.

Updating it sooner in Closure compiler could be helpful to migrate our old style. We just need to ensure that our obfuscation logic supports this.

/cc @jridgewell 
/cc @ampproject/wg-infra 
/cc @kristoferbaxter

**Comment by jridgewell** [comment]
Closure doesn't currently class fields (and likely, private methods): https://github.com/google/closure-compiler/issues/2731

Also, private fields are not equivalent to public properties. For one, access is scoped only to the class lexical scope, and nothing outside (eg, the rest of the file or a test file) can access it.

**Comment by rsimha** [comment]
The closure bug is still open. Reassigning this to @jridgewell for triage / prioritization.
