### ISSUE TITLE
Story bot render mode: Force text to be visible

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#26528]
The text inferred from slide titles and video alt attributes should be forced to be readable.

This could e.g. be achieved by setting the background color of the text and the color of the text to different, high contrast colors. Today it can happen that a story e.g. sets a white background color and a white text color which works, because the text is usually not shown directly over the page background.

**Comment by gmajoulet** [comment]
Did you notice that on a specific story?

We already have some CSS that should prevent this from happening, I'd be curious to see what kind of publisher provided CSS overrode it:

https://github.com/ampproject/amphtml/blob/0b9623cbc43521e28e395a58b9ab3613044cda14/extensions/amp-story/1.0/amp-story-vertical.css#L66-L68

**Comment by cramforce** [comment]
Interesting. I thought I saw it, but I must have been mistaken. Will keep an eye out for it!

**Comment by cramforce** [comment]
One tiny change: Should we made `width: auto` instead of `width:100%`. Right now, because of the padding, the text runs over the right screen.
