### ISSUE TITLE
amp-lightbox-gallery adds also amp-img with non matching media attribute

### ISSUE THREAD

**Issue by j3ll3yfi5h** [ampproject/amphtml#26536]
## What's the issue?

I'm using at least two different amp-img with different `media` attributes and the `lightbox` attribute (from `<amp-lighbox-gallery>`). The lightbox also "takes" the `<amp-img>` with the non-matching media attribute.

## How do we reproduce the issue?

See [example](http://amp-lighbox-gallery-bug.jelley.fish/)

1. Add at least two different `<amp-img>`
2. Open lightbox
3. Get two slides, one black
4. (Also in overview both are present)

## What browsers are affected?

All browsers

## Which AMP version is affected?

Always "broken".
AMP ⚡ HTML – Version 2001071857360

**Comment by merakmarey** [comment]
j3ll3yfi5h What is your expected behavior here?

**Comment by j3ll3yfi5h** [comment]
@merakmarey The `<amp-img>`'s with the none matching `media` attributes should be fully ignored in the lightbox view. (including image overview)

![amp-lighbox-gallery-bug jelley fish_lightbox](https://user-images.githubusercontent.com/6337411/73606060-718a5400-45a6-11ea-9e76-31c298068c77.png)
![amp-lighbox-gallery-bug jelley fish_overview](https://user-images.githubusercontent.com/6337411/73606061-7222ea80-45a6-11ea-8fde-bb3ad3a74139.png)

**Comment by merakmarey** [comment]
On the first screenshot, image is not displayed, which is correct according to media query, but maybe you are expecting to be only one slide (since narrow.jpg is not supposed to appear due media query condition)...is this what you expect?
Om image overview, those images do not inherit media attributes, hence the image shows anyway..

**Comment by j3ll3yfi5h** [comment]
@merakmarey 

- Yes, that's it. I expect that there is only one slide.
- I also expect, that this one is ignored in the overview. E.g.: Think about the same image and with art direction for smaller screens.

**Comment by merakmarey** [comment]
But then you also expect that if the viewport is resized the images excluded by the media query become available without a reload..correct?

**Comment by j3ll3yfi5h** [comment]
@merakmarey exactly!

**Comment by merakmarey** [comment]
In regard of the media query, the solution would be to create a regular media query on the css, and adding the class affected by the media query to the amp-img added to the amp-lightbox-gallery, but alas, classes are not inherited either by the thumbnails..that would be something useful, been able to style thumbnails...
In regard of hidding/showing slides dynamically, I believe that would require to know if the media query would affect the visibility of the slide BEFORE creating the slide, which sound really complicated, and honestly I don't see that feature been commonly used..but hey, what do I know?...
@alanorozco any thoughts?
