### ISSUE TITLE
In amp-story ,the Get Link in share option for http (Without SSL Certificate) website, it copies wrong url

### ISSUE THREAD

**Issue by Avdhoot05** [ampproject/amphtml#26537]
In amp-story ,the Get Link in share option for http website, it copy wrong url for all browser. Here are some examples:-
http://learn.travclan.com/how-to-sell-maldives
http://learn.travclan.com/learn-to-sell-singapore-easiest-way

but it works fine for website with SSL certificate(https)
https://travel.visualstories.com/10beautiful-buddhist-temples-in-thailand-worth-a-trip

Please see attached screenshot
![WrongGetLinkCopy](https://user-images.githubusercontent.com/46551690/73356698-ef0d4600-42c0-11ea-80c9-800852c9446e.png)

**Comment by newmuis** [comment]
I believe this is a bug in the page.  The canonical URL for the page is:

```html
<link rel="canonical" href="http//learn.travclan.com/learn-to-sell-singapore-easiest-way">
```

The colon after the `http` protocol is missing.  It should be:

```html
<link rel="canonical" href="http://learn.travclan.com/learn-to-sell-singapore-easiest-way">
```

@Avdhoot05 can you try fixing this and seeing if it corrects the issue?

**Comment by Avdhoot05** [comment]
@newmuis Thanks! It's working.
