### ISSUE TITLE
Remove Purification for Valid Templates

### ISSUE THREAD

**Issue by kristoferbaxter** [ampproject/amphtml#26544]
## Change you'd like to see

Remove JavaScript driven purification for valid `amp-mustache` templates. This reduces execution time to render templates significantly.

**AMP Mustache with 44 single depth DOM items**

| Before | After |
| --- | --- |
| 670ms ![image](https://user-images.githubusercontent.com/61764/73393540-adfd3d80-4290-11ea-8ef1-603571317ac4.png) | **270ms** ![image](https://user-images.githubusercontent.com/61764/73393699-f4529c80-4290-11ea-8171-6e2d58808051.png) |

**Summary**
Can we safely remove purification, if the document templates can be purified during validation?

**Assumptions**
1. Templates can either be inside a `<template>` or `<script type='template'>`.
2. Template does not use a triple tick (output to `innerHTML`).

**Requirements**
1. Enhance Validation and Document ingestors to validate templates.
2. Remove `DOMPurify` from `<amp-mustache>` and `<amp-script>` converting it to a service that can be lazily loaded or bundled directly as needed.
3. When a document comes from a cache, and has been marked with exclusively safe templates - use Mustache directly.
4. In the case when a document is unsafe, request the `Purify` service and use for all templates.

**Enhancements**
1. Work with teams to deliver a signal an ingested valid document is sub-optimal due to unsafe templates. This information can be delivered async (Search Console) or sync (Validation Warning).

## Describe alternatives you've considered

Default to using [trusted types](https://github.com/w3c/webappsec-trusted-types/blob/master/README.md), and fallback to current `Purify` logic in a service when trusted types are not available.

**Edit**: Resolves #26472

**Comment by Gregable** [comment]
I'm changing this from a P1 to a P3 after our discussions offline. I'd also be open to closing this issue, as I don't think we currently plan to implement.

**Comment by Gregable** [comment]
Closing this issue. Feel free to reopen if there is new discussion.

**Comment by samouri** [comment]
@kristoferbaxter  / @Gregable: can you speak more to what made this infeasible?

**Comment by Gregable** [comment]
The condition "if the document templates can be purified during validation" is infeasible.
