### ISSUE TITLE
🌸 Cherry pick request for 26551 into 26510 (Pending)

### ISSUE THREAD

**Issue by elijahsoria** [ampproject/amphtml#26552]
# Cherry-pick request

|       Issue       |       PR       | Production? | Release Issue | 
| :---------------: | :------------: | :------------------: | :------------------: | 
| #26551  | #26288 |     **YES**     | #26356 |

## Why does this issue meet the [cherry-pick criteria]

This error is causing breakages for multiple publishers, including the Washington Post. This cherry-pick fixes their production site for SwG integration.

## Why is a Beta / Experimental cherry-pick not needed?

Affecting production.

## Why is an LTS cherry-pick needed?

Affecting production.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

We are checking for "entitlements.granted" before checking to see if entitlements is not null in amp-subscriptions.js. This causes errors to be thrown, like the following.

Uncaught (in promise) TypeError: fetch entitlements failed for subscribe.google.com: Cannot read property 'granted' of null
at amp-subscriptions.js:284

| Users affected                                   | Impact                                                                       |
| ------------------------------------------------ | ---------------------------------------------------------------------------- |
| WashingtonPost SwG users on iOS Chrome | complete loss of SwG functionality |

## Root Causes

1. Not checking for null entitlements before checking for member.

## Lessons Learned

Although we have a test case for this scenario, it wasn't throwing a blocking error on our test browsers.

### Things that went well

- Fix was very easy.

### Things that went wrong

- Issue was found by partner.

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by dvoytenko** [comment]
Approved

**Comment by Enriqe** [comment]
This fix is included in the soon-to-be released version `2001251659540`. It will be live momentarily.

**Comment by elijahsoria** [comment]
Confirmed that the error is not showing in publisher's AMP page.
