### ISSUE TITLE
Use go.amp.dev links in `amphtml` documentation wherever possible

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#26561]
There are [200+](https://github.com/ampproject/amphtml/search?l=Markdown&q=%22github.com%2Fampproject%2Famphtml%22) direct links and [4](https://github.com/ampproject/amphtml/search?l=Markdown&q=%22go.amp.dev%22) short links in our repo's documentation.

Now that we have the ability to add [go.amp.dev](https://github.com/ampproject/amp.dev/blob/future/platform/config/go-links.yaml) links, we can do the following:
- Add short links for `github.com/ampproject/amphtml` URLs that are frequently referenced in our external-facing documentation
- Replace existing links in our docs with short links when possible, so they translate across all uses

**Comment by rsimha** [comment]
/to @sebastianbenz for triage
/cc @rcebulko who brought this up in https://github.com/ampproject/amphtml/pull/26549#discussion_r372637456

Related issue: #21965

**Comment by rcebulko** [comment]
How would you feel about adding a check into `gulp check-links` that fetches `go-links.yaml` from AMP.dev and reports when links are used that should be go links?

**Comment by rsimha** [comment]
> How would you feel about adding a check into `gulp check-links` that fetches `go-links.yaml` from AMP.dev and reports when links are used that should be go links?

That sounds great, since we won't have to update the check each time a new go.amp.dev link is added. I certainly agree that `gulp check-links` is the place to do this. Not high priority though (will let Sebastian confirm).

**Comment by rsimha** [comment]
_[Infra triage]_ It has been a year since this was proposed in https://github.com/ampproject/amphtml/pull/26549#discussion_r373019460, during which time there have been changes to AMP's documentation backend, membership of working-groups, and team priorities. @rcebulko @sebastianbenz Do either of you see reason to keep this around? If there's no strong reason, I'm okay with closing.
