### ISSUE TITLE
Replace `.then()` chains in `build-system/` code with `async` and `await` wherever possible

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#26562]
A lot of the code in `build-system/` was written when we were using node v4, and consists of [chains of `.then()` calls](https://github.com/search?utf8=%E2%9C%93&q=%22.then%28%22+repo%3Aampproject%2Famphtml+path%3Abuild-system%2F+language%3AJavaScript+language%3AJavaScript&type=Code&ref=advsearch&l=JavaScript&l=JavaScript).

Now that we have `async` and `await`, it's probably worth migrating legacy code to use it.

**Comment by rcebulko** [comment]
Leaving aside the `then`/`async-await` specifics, these chains of `then()` calls don't execute anything asynchronous; they should just be normal code.
