### ISSUE TITLE
OWNERS check should display the file paths it resolved from

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#26603]

**Comment by rcebulko** [comment]
Do you think this should be a) all the OWNERS files that are relevant b) the ones where the suggested reviewers appeared c) only the ones for missing owners d) something else?

**Comment by alanorozco** [comment]
@rcebulko

Possibly `b)`.

My use case is connecting the resolved `wg` to a chosen owner. 

From this then I'd like to find out if a more appropriate rule for my own `wg` could be set in the resolved file.

I had [this](https://github.com/ampproject/amphtml/pull/26504/checks?check_run_id=411404240) occur recently:

<img width="600" alt="Screen Shot 2020-02-04 at 7 37 18 AM" src="https://user-images.githubusercontent.com/254946/73759904-76274780-4721-11ea-8517-ef925f67a49a.png">

`spec/` has no `OWNERS` file. The resolved rule is from root-level `OWNERS`:

```js
  {
    pattern: '**/*.md',
    owners: [{name: 'mrjoro'}, {name: 'ampproject/wg-outreach'}],
  }
```

So by navigating back manually I could find the rule. It would have been helpful to connect `alankent` to `/OWNERS` beforehand.

(Maybe this is a second FR: it's still opaque that this is the chosen rule since you don't necessarily know that `alankent` is part of `ampproject/wg-outreach`.)

**Comment by rcebulko** [comment]
@alanorozco Addressing your last question first, you may find [this dynamic owners tree](http://ampproject-owners-bot.appspot.com/tree) helpful.

With regards to actually presenting the groups the individual users came from, I'll look into what's possible/practical. The selection algorithm converts groups into big lists of users. For example, `wg-ads` owns `extensions/amp-ads` and `wg-analytics` owns `extensions/amp-analytics`; `calebcordry` is in both, so a PR touching both directories will always add him (or `lannka` or `zhouyx`, who are also in both). The point being, breaking the users out of groups is useful for this selection.

I may be able to pass around groups/files of origin in the reviewer selection stage, or it may make more sense to look at the reviewer set after the fact and retroactively determine which files/groups they satisfy. Currently on release duty this week, but will look into it further when I have some down time. In the interim, hopefully you find that link useful.

**Comment by alanorozco** [comment]
I remembered the `resolve` link being access-restricted, didn't know it linked to the owners tree! 

That's enough for my use case, up to you to keep this FR open or not.

**Comment by rcebulko** [comment]
In that case, I'll add a link to the tree from the GitHub check output and call it a day.
