### ISSUE TITLE
links (a href) under amp-sidebar not getting click

### ISSUE THREAD

**Issue by anuragphadke** [ampproject/amphtml#26608]
`<a href> ` links under amp-sidebar are not getting clicked even though the CSS looks correct.

## How do we reproduce the issue?

1. Go to https://beta.webfast.co/toylibrary-co/a.html
2. Click on the hamburger menu at top left
3. menu pops up with few options: shop, best sellers etc. and social icons
4. Clicking on any of the links does not result in navigating to those pages, the sidebar stays open.
Expected behavior:
Clicking on the links will load the respective page.

## What browsers are affected?

All mobile browsers, Chrome and iOS

## Which AMP version is affected?
2001251659540

**Comment by anuragphadke** [comment]
looks to be CSS issue on my end, closing.

**Comment by mehmoodumer05** [comment]
I've same issue..
