### ISSUE TITLE
amp-story-quiz: fallback animation for option selection not running in Safari

### ISSUE THREAD

**Issue by jackbsteinberg** [ampproject/amphtml#26617]
## What's the issue?

The animation for selecting an option on the `<amp-story-quiz>` element does not run when an option is selected using Safari on desktop or iOS devices.

Relates to tracking issue #25615.

## How do we reproduce the issue?

Open the [demo for story quizzes](https://stamp-quiz-demo.firebaseapp.com/examples/amp-story/quiz.html) and select an option without data (none will have data at this time).

## What browsers are affected?

Safari on desktop and iOS

## Which AMP version is affected?

Version 2001242153080

cc/ @gmajoulet

**Comment by gmajoulet** [comment]
I think @mszylkowski fixed this one. Matias, can you double check and close this issue if so? Thanks!

**Comment by mszylkowski** [comment]
Yes! Will be closed through #28643
