### ISSUE TITLE
amp-instagram inside amp-carousel does not show entirely

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#2662]
## Short description of your issue:

When embedding amp-instagram inside amp-carousel, the instagram post does not show entirely, the header and footer do not show. 
## How do we reproduce the issue?

I made an example here in which I use the same amp-instagram tag first inside amp-carousel, then alone
https://jsbin.com/xatuxetore/1/edit?html,output
## What browsers are affected?

Tried on Chrome
## Which AMP version is affected?

1457721872758

**Comment by kul3r4** [comment]
@sebastianbenz

**Comment by dvoytenko** [comment]
@kul3r4 Do you mean facebook embeds? I only see facebook embeds here and they seem to be displayed fully...

**Comment by kul3r4** [comment]
Hi, I messed up with the examples, sorry!
this one contains an amp-instagram: https://jsbin.com/hesadahuxa/edit?html,output

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
