### ISSUE TITLE
Cannot read property 'scrollingElement' of undefined

### ISSUE THREAD

**Issue by xprtedgar** [ampproject/amphtml#26623]
## What's the issue?

position-observer.js:165 Uncaught TypeError: Cannot read property 'scrollingElement' of undefined.

## What browsers are affected?

All browsers

## Which AMP version is affected?

Version 2001251659540

**Comment by choumx** [comment]
Guessing this is due to occasional missing `this.win_` in `ads/inabox/position-observer.js`.
