### ISSUE TITLE
Make amp-viz-vega production-ready

### ISSUE THREAD

**Issue by adekbadek** [ampproject/amphtml#26642]
The [`amp-viz-vega`](https://amp.dev/documentation/components/amp-viz-vega/) component would be a great feature in the AMP. Currently, it seems abandoned - the code has been added as an experiment about three years ago, and it [seems to be using](https://github.com/ampproject/amphtml/blob/5f75efe35b/third_party/vega/README.amp) an older version of Vega library (`2.6.1`, while current is `5.9.1`).

It'd be nice to make it production ready, that is:
- use the current version of Vega
- make it regular component, not an experimental one

Related: #18705, #18830

**Comment by spasibych** [comment]
I also look forward to it, and so far I have to be content with server rendering in SVG or heavy insertions in iframe.

**Comment by wassgha** [comment]
@nainar to prioritize

**Comment by nainar** [comment]
@adekbadek  or @spasibych would you be interested in contributing code to make this change?

**Comment by adekbadek** [comment]
@nainar absolutely, I just would need some pointers about local development - I could not find anything on amp.dev or in readme/contributing docs

**Comment by spasibych** [comment]
@nainar, @adekbadek my experience on GitHub is too small. Perhaps I will be useful in testing.

In any case, my interest in Vega integration is high. In case of not implementing `<amp-viz-vega>`, i would try to use it through `<amp-script>`.

**Comment by wassgha** [comment]
Hey @adekbadek and @spasibych , thank you for your interest in contributing! To get you up to speed, the [quick start guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) should have most of the information you need to get a local instance of AMP running on your computer. Let me know if you have any questions or if you get stuck on any of the steps! You can also ask your questions on our [Slack channel](amphtml.slack.com) for immediate help.

**Comment by spasibych** [comment]
@wassgha second link is 404. Perhaps meant [amphtml.slack.com](https://amphtml.slack.com)?

**Comment by wassgha** [comment]
That's correct! Sorry about that
