### ISSUE TITLE
<amp-script> Responsive Layout is loading Fill layout css

### ISSUE THREAD

**Issue by jsanchez-avvo** [ampproject/amphtml#26646]
## What's the issue?

The styles that are supposed to load on a Layout Responsive setting isn't loading in a <amp-scrip> block. instead `class="i-amphtml-fill-content i-amphtml-replaced-content"` is the class that surrounds the elements.

## How do we reproduce the issue?

Just set a basic amp-script block with this settings:
```
<amp-script  src="https:://some_valid.js" layout="responsive" height=1 width=100 sandbox="allow-forms">
  </amp-script>
```
Inspecting the element we see the difference between the layout given and the class been set
![Screenshot from 2020-02-06 17-19-49](https://user-images.githubusercontent.com/56874944/73975397-fce84a00-4904-11ea-8ee1-ba6080849197.png)

If you manually change the fill part to `class="i-amphtml-responsive-content i-amphtml-replaced-content"` you are able to see the correct css

Just yesterday(02-05-2020) everything was working fine, something change to today (02-06-2020)

## What browsers are affected?

All browsers

## Which AMP version is affected?
2001281851410

**Comment by jsanchez-avvo** [comment]
I think the issue began on this commit https://github.com/ampproject/amphtml/commit/49823f308c0b02b48a268044d2807bf8c5cb727c

Does this means that the layout="responsive" is not going to allow us to have a dynamic height? Is going to behave always as a fix layout?! @choumx

**Comment by samouri** [comment]
@jsanchez-avvo, my understanding is that the previous behavior was a mistake. Elements with `layout=responsive` have their size fixed once laid out (except it will re-layout on browser resize or orientation change).

We accomplish this via the sizer element with a `padding-top: N%`. The `N` is determined by calculating `height/width`, and then essentially wrapping the whole `amp-script`'s content in a container div with `height:0; width:0` (the `i-amphtml-fill-content` you are seeing).

Can you provide an example of a page/experience that was previously working and that no longer renders properly?

**Comment by jsanchez-avvo** [comment]
> Elements with layout=responsive have their size fixed once laid out (except it will re-layout on browser resize or orientation change).

Mmm all right. No unfortunately on Prod don't have a page to show you guys, this was a feature on development and that's why I saw the impact from one day to another. The behavior was Similar to what you are telling me, but in my case I had a drop down content and the height of my `amp-script` content adapted it's height accordingly and didn't truncate my elements.

Don't have an page for you to test but can add some more screen shots. With the `i-amphtml-fill-content` The behavior is this:

My content is loaded with a fixed height as you said and the internal content never re-layout this height. The height is only triggers the re-layout on resize as you said:

![Screenshot from 2020-02-07 15-10-14](https://user-images.githubusercontent.com/56874944/74054471-e271a780-49bc-11ea-947f-3d8bb1592724.png)
![Screenshot from 2020-02-07 15-10-31](https://user-images.githubusercontent.com/56874944/74054489-ebfb0f80-49bc-11ea-9098-a59c012e374d.png)

with the previous responsive behavior I was having an initial height given the `padding-top: N%` calculation and the content height didn't re-layout on resize but did when there was and internal change.

![Screenshot from 2020-02-07 15-12-12](https://user-images.githubusercontent.com/56874944/74054766-63c93a00-49bd-11ea-982c-4c0b01c59ea0.png)

Is possible that my initial take on how it was suppose to behave the responsive layout was wrong. I was able to achieve the previous behavior using a different configuration of another layout but wanted to continue this report in case any other person encounter this problem.

**Comment by samouri** [comment]
Thank you for highlighting this @jsanchez-avvo. The fix to `amp-script` you highlighted is indeed indeed a breaking change. `amp-script` is now compliant though with the spec, so the new behavior is the desired one.

/to @choumx to see if there is any action for us to take re. ensuring the fix didn't break Publishers.  If not, lets close this out :)
