### ISSUE TITLE
amp-ad-3p: custom path test fails when network response unreadable

### ISSUE THREAD

**Issue by mdmower** [ampproject/amphtml#26651]
Local tests fail when network response to URL in test _amp-ad-3p-impl: should use custom path_ is unreadable. Test and its URL are defined [here](https://github.com/ampproject/amphtml/blob/4d05b4403bca9c48f4f093a32ad1fd8d480464e5/extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js#L230). Requests to `https://example.com/boot/remote.html` currently result in malformed responses; content encoding reports gzip but content is not compressed. The result of this is that `.loadPromise()` on the iframe does not resolve in time for `ad3p.layoutCallback()` to resolve before the test times out.

Perhaps [`iframe.loadPromise`](https://github.com/ampproject/amphtml/blob/4d05b4403bca9c48f4f093a32ad1fd8d480464e5/extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js#L202) could be stubbed so the actual network request never matters when trying to complete this test? Otherwise, temporary solution is to simply replace `https://example.com/boot/remote.html` with `https://example.com`.

Sample failed builds on travis:

- https://travis-ci.org/ampproject/amphtml/jobs/647046714#L1917
- https://travis-ci.org/ampproject/amphtml/jobs/647049827#L1921
- https://travis-ci.org/ampproject/amphtml/jobs/647118652#L1921

**Comment by mdmower** [comment]
@ampproject/wg-infra

**Comment by estherkim** [comment]
Looks like @newmuis skipped the test here https://github.com/ampproject/amphtml/pull/26659.

Assigning to @calebcordry to follow up.

**Comment by calebcordry** [comment]
@powerivq let me know if you know what happened here. Otherwise I can investigate.

**Comment by calebcordry** [comment]
also thanks @mdmower !
