### ISSUE TITLE
🌸 Cherry-pick request for #26658 into #26560 (Pending)

### ISSUE THREAD

**Issue by ChrisAntaki** [ampproject/amphtml#26662]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #26665 | #26658 |     **YES**     | **YES** | **YES** | #26560                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

There is a P0 bug that breaks existing AMP web pages in a significant way. Basically the `amp-subscriptions` "click" event listener is not working inside of FixedLayer elements.

## Why is an LTS cherry-pick needed?

This issue is affecting a lot of iOS users.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

The `amp-subscriptions` "click" event listener is not working inside of FixedLayer elements.

| Users affected                                   | Impact                                                                       |
| ------------------------------------------------ | ---------------------------------------------------------------------------- |
| Users on iOS 12 or lower | Users couldn't click SwG buttons like "sign in", or "subscribe" in the AMP viewer, if these buttons were inside of a FixedLayer element |

## Root Causes

1. Events were listened to on the document root's `body` property if available, however FixedLayer creates a second `body` element and moves elements there to try and improve scrolling on iOS.

## Action Items

| Action Item                   |               Type               |     Owner     |      PR #      |
| ----------------------------- | :------------------------------: | :-----------: | :------------: |
| Add tests for SwG in AMP viewer across browsers/devices | Prevent | @ChrisAntaki  | ... |

### Things that went well

- 

### Things that went wrong

- Issue was not caught by automated tests

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by dvoytenko** [comment]
Approved

**Comment by rcebulko** [comment]
Can we verify via RTV opt-in to RTV `011912201827130` from `experiments.html` that this does actually impact LTS and require an LTS cherry-pick?

**Comment by rcebulko** [comment]
Update: Because we are a) unable to reproduce the issue on LTS with RTV opt-in and b) LTS is very recently announced and not yet adopted and c) the current Stable build will be promoted to LTS next Monday, we are not going to cherry-pick this into LTS

**Comment by rcebulko** [comment]
Also cherry-picking https://github.com/ampproject/amphtml/pull/26639 , which is a test-skip PR. Currently the cherry-pick branches are failing builds because of a known test-only breakage. @dvoytenko :+1: ?

**Comment by rcebulko** [comment]
Same as above re: https://github.com/ampproject/amphtml/pull/26670

**Comment by ChrisAntaki** [comment]
Sorry, I didn't see the note about mini-postmortems and action items

**Comment by ChrisAntaki** [comment]
This was superseded by #26746
