### ISSUE TITLE
Share and sidebar UI controls should not be displayed while ads are onscreen on mobile

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#26669]
When a story is viewed on mobile, the share and sidebar icons should be hidden while the user is on an ad.

/cc @calebcordry @ampproject/wg-stories

**Comment by gmajoulet** [comment]
Here's the CSS that hides the progress bar when an ad is visible:

https://github.com/ampproject/amphtml/blob/75495f42b2ea105a97efbda34f22ff8fa1600e33/extensions/amp-story/1.0/amp-story-system-layer.css#L99-L101

Instead, we could either (1) change this selector to hide the whole system layer, or (2) use the store service action that hides all system UI:
`this.storeService_.dispatch(Action.TOGGLE_SYSTEM_UI_IS_VISIBLE, boolean);`

(1) gives more control over the animation, the page transition is a cut while the `SYSTEM_UI` action is a fadeIn/Out, but (2) is more future proof.

**Comment by newmuis** [comment]
Is the `ad` badge part of the system layer element?

**Comment by calebcordry** [comment]
Not really, its created by the story ads extension and placed in the system layer area on mobile, but it moves independently in other view modes.
