### ISSUE TITLE
Missing Documentation on amp-access-scroll

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amphtml#26664]
[`amp-access-scroll`](https://github.com/ampproject/amphtml/tree/master/extensions/amp-access-scroll) had no documentation, and therefore unusable. Please create a `.md` file that outlines the use of this component following the [extension-doc.template.md](https://github.com/ampproject/amphtml/blob/master/build-system/tasks/extension-generator/extension-doc.template.md) format.

**Comment by jpettitt** [comment]
@kushal please create a .md

**Comment by kushal** [comment]
Hi! Sorry about that! You'll find instructions at https://developer.scroll.com/amp but we'll also work on adding something to the extension itself.
