### ISSUE TITLE
AMP Validator considers a reference to template script[type=text/plain] an error

### ISSUE THREAD

**Issue by spasibych** [ampproject/amphtml#26676]
## What's the issue?

When referenced from `<amp-list ... template="my-template"></amp-list>` to `<script id="my-template" type="text/plain" template="amp-mustache"> ... </template>` AMP Validator showing error "Attribute 'template' in tag 'amp-list' contains a value that does not match any other tags on the page".

However, everything will work, but the page will be deleted from Google AMP Cache due to this error.

## How do we reproduce the issue?

1. Add code to AMP page:
```html
<amp-state id="items"><script type="application/json">[]</script></amp-state>
<button on="tap:AMP.setState({ items: items.splice(items.length, 0, items.length) })">Add item</button>
<template id="items-template" type="amp-mustache"><code>{{#.}}, {{/.}}{{.}}</code></template>
<script id="items-scripted" type="text/plain" template="amp-mustache"><code>{{#.}}, {{/.}}{{.}}</code></script>
<amp-list [src]="items" items="." layout="fixed-height" height="32" template="items-template"></amp-list>
<amp-list [src]="items" items="." layout="fixed-height" height="32" template="items-scripted"></amp-list>
```
2. View the AMP page.
3. See AMP Validator errors.

AMP Validator will point to a line with `amp-list` referring to the template `script[type=text/plain]` by id `items-scripted`. However, everything will work.

## Source and Screenshots

Source test script: [amp-mustache.html.zip](https://github.com/ampproject/amphtml/files/4173530/amp-mustache.html.zip)

![amp-mustache](https://user-images.githubusercontent.com/11217397/74075406-f946e700-4a1a-11ea-9787-9adaecfa60b4.png)

**Comment by banaag** [comment]
cc @ampproject/wg-caching

**Comment by twifkak** [comment]
Sorry for the delay. Here's a [minimal test case](https://validator.amp.dev/#doc=PCFkb2N0eXBlIGh0bWw%2BCjxodG1sIOKaoT4KPGhlYWQ%2BCiAgPG1ldGEgY2hhcnNldD0idXRmLTgiPgogIDxsaW5rIHJlbD0iY2Fub25pY2FsIiBocmVmPSJzZWxmLmh0bWwiIC8%2BCiAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCxtaW5pbXVtLXNjYWxlPTEiPgogIDxzdHlsZSBhbXAtYm9pbGVycGxhdGU%2BYm9keXstd2Via2l0LWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoOy1tb3otYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1zLWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoO2FuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RofUAtd2Via2l0LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1vei1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1tcy1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1vLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1Aa2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fTwvc3R5bGU%2BPG5vc2NyaXB0PjxzdHlsZSBhbXAtYm9pbGVycGxhdGU%2BYm9keXstd2Via2l0LWFuaW1hdGlvbjpub25lOy1tb3otYW5pbWF0aW9uOm5vbmU7LW1zLWFuaW1hdGlvbjpub25lO2FuaW1hdGlvbjpub25lfTwvc3R5bGU%2BPC9ub3NjcmlwdD4KICA8c2NyaXB0IGFzeW5jIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAuanMiPjwvc2NyaXB0PgogIDxzY3JpcHQgYXN5bmMgY3VzdG9tLXRlbXBsYXRlPSJhbXAtbXVzdGFjaGUiIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAvYW1wLW11c3RhY2hlLTAuMi5qcyI%2BPC9zY3JpcHQ%2BCiAgPHNjcmlwdCBhc3luYyBjdXN0b20tZWxlbWVudD0iYW1wLWxpc3QiIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAvYW1wLWxpc3QtMC4xLmpzIj48L3NjcmlwdD4KPC9oZWFkPgo8Ym9keT4KPHNjcmlwdCBpZD0iaXRlbXMtc2NyaXB0ZWQiIHR5cGU9InRleHQvcGxhaW4iIHRlbXBsYXRlPSJhbXAtbXVzdGFjaGUiPjwvc2NyaXB0Pgo8YW1wLWxpc3QgW3NyY109Iml0ZW1zIiBpdGVtcz0iLiIgbGF5b3V0PSJmaXhlZC1oZWlnaHQiIGhlaWdodD0iMzIiIHRlbXBsYXRlPSJpdGVtcy1zY3JpcHRlZCI%2BPC9hbXAtbGlzdD4KICA8L2JvZHk%2BCjwvaHRtbD4K).

This requirement was added in #24267 (from cl/264646527); it seems it was too strict.

The solution is to add `attrs { name: "id" add_value_to_set: TEMPLATE_IDS }` inside the script tagspec at https://github.com/ampproject/amphtml/blob/26295bc28d43750dc7fb1550c2b1841426a7ac2b/extensions/amp-mustache/validator-amp-mustache.protoascii#L66

But first we need to make sure that all [the dependents](https://github.com/ampproject/amphtml/search?q=template_ids) know how to find templates in script elements.

**Comment by twifkak** [comment]
Yes all of [amp-date-display 0.1](https://github.com/ampproject/amphtml/blob/7c483ddd878455d014ef84d52b4b95d601d2282b/extensions/amp-date-display/0.1/amp-date-display.js#L132), [amp-date-display 0.2](https://github.com/ampproject/amphtml/blob/7c483ddd878455d014ef84d52b4b95d601d2282b/extensions/amp-date-display/0.2/amp-date-display.js#L53), [amp-list 0.1](https://github.com/ampproject/amphtml/blob/7c483ddd878455d014ef84d52b4b95d601d2282b/extensions/amp-list/0.1/amp-list.js#L859), and [amp-date-countdown 0.1](https://github.com/ampproject/amphtml/blob/7c483ddd878455d014ef84d52b4b95d601d2282b/extensions/amp-date-countdown/0.1/amp-date-countdown.js#L210) seem to [support script element templates](https://github.com/ampproject/amphtml/blob/7c483ddd878455d014ef84d52b4b95d601d2282b/src/service/template-impl.js#L270).

**Comment by twifkak** [comment]
OK, fix is in `master`. It may take ~1 week to propagate.

**Comment by spasibych** [comment]
@twifkak thank you very much!
