### ISSUE TITLE
Constrain stories to a minimum and maximum aspect ratio

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#26671]
We should have minimum and maximum aspect ratios for stories, beyond which we'll stop stretching the size of the `<amp-story-page>` and show a non-full-bleed experience (for example a 1-up view similar to our current 3-up view without the previous and next pages).

This will allow us to give better guarantees to designers about the aspect ratios at which their stories will be seen, and will also allow us to get rid of the "resize your browser window" warning message that gets shown at some screen sizes, as all screen sizes would have some UI implementation for a story.

**Comment by newmuis** [comment]
I'll work with @hongwei1990 to make sure we get the right minimum and maximum ratios.

**Comment by newmuis** [comment]
For portrait, the recommendation is to go from as tall as 1:2 to as wide as 3:4. 

For stories that support landscape, I'll need to double check, but perhaps we can just use the inverse of those ratios (as wide as 2:1 or as tall as 4:3).

**Comment by gmajoulet** [comment]
Reassigning to @MaxBittker
