### ISSUE TITLE
Namespace classes in amp-social-share elements

### ISSUE THREAD

**Issue by jsit** [ampproject/amphtml#2668]
Right now elements created with `amp-social-share` have class names like this:

```html
<span class="twitter">
```

They should probably be something like:

```html
<span class="amp-social-share-twitter">
```

so as not to conflict with class names used elsewhere on a site's stylesheets.

**Comment by dvoytenko** [comment]
That does make sense. @paul-matthews wdyt?

**Comment by rudygalfi** [comment]
Agree -- we should do this.

**Comment by jsit** [comment]
Is BEM naming too cumbersome? For instance:

amp-social-share__button--twitter

Or:

amp-social-share__twitter

Or maybe just:

amp-social-share-twitter

**Comment by erwinmombay** [comment]
BEM would be nice, unfortunately AMP did not adopt BEM so `amp-social-share-twitter` would be more in line with AMP's internal css practice.

**Comment by mkhatib** [comment]
Is social share still in experimental? Do we need to worry about backward compatibility? Namely, if we start using `.amp-social-share-twitter` instead of `.twitter` would that affect people who already using the extension?

**Comment by dvoytenko** [comment]
No need to worry about backward compatibility. Yes, in experimental still.
