### ISSUE TITLE
amp-lightbox-gallery: Load unseen slides more eagerly

### ISSUE THREAD

**Issue by photocoder** [ampproject/amphtml#26686]
## Describe the new feature or change to an existing feature you'd like to see
After initial loading when you open first picture and look and a lot of pictures in gallery, some of next photos will be unloaded with initial page (because of "deferred loading"). And next available photo will load right after you click to "next".

## Describe alternatives you've considered
I think will be nice if when you look current photo, gallery can upload on the background the next one.

**Comment by wassgha** [comment]
Hello, could you please specify what component exactly you're using?

**Comment by alanorozco** [comment]
(If this `amp-lightbox-gallery` this might be related to children ownership.)

**Comment by photocoder** [comment]
> Hello, could you please specify what component exactly you're using?
Yes, I use `amp-lightbox-gallery`.

> (If this amp-lightbox-gallery this might be related to children ownership.)
What does it mean?

**Comment by alanorozco** [comment]
@photocoder 

`amp-lightbox-gallery` schedules the loading of children elements inside of it, rather than letting the runtime scheduler do it. I jotted it down as a hint for whoever debugs this, no action to take from your side :) 

Thanks for clarifying the component.
