### ISSUE TITLE
I2I: "Browsi" amp-analytics & RTC vendors

### ISSUE THREAD

**Issue by ofirpaBrowsi** [ampproject/amphtml#26688]
## Summary

The analytics and RTC vendors additions provide the option to send real time data to ad objects  on AMP pages using Browsi Prediction Service.

## Design document

[Design Doc](https://docs.google.com/document/d/1KuCOjUcp6-xm79DbXgjWohgVveXr4NOm0bsexukZ7OI/edit?usp=sharing)

## Motivation

Publishers, who maintain an AMP page, implement ads to monetize their sites.
Browsi has many publishers benefiting from our products on mobile web, desktop web and app - many of them wish to use the same Browsi products on AMP env too.
Our products help publishers to gain the most out of their inventory by providing real time data to be able to optimize yield.

## Additional context

Browsi’s analytics vendor uses built-in events to collect data for the  ‘Browsi Prediction Service’ which allows Browsi’s RTC vendor to provide accurate predictions and real-time data enrichments, as additional  key-value 'targeting' per ad in real-time.

This extension was developed by [Browsi](https://www.gobrowsi.com)

cc @ampproject/wg-approvers
cc @ampproject/wg-analytics
cc @ampproject/wg-ads

**Comment by lannka** [comment]
Thanks @ofirpaBrowsi . We have have discussions in your design doc.

**Comment by micajuine-ho** [comment]
Hi @ofirpaBrowsi, there was some discussion around being able to track multiple elements with the same selector in your design doc. 

This feature has been added and is available under an experiment flag if you would like to test it. 

Please see #26823 for more details, or feel free to follow up here.

Closing this issue via #26835.
