### ISSUE TITLE
Inconsistency between AMP Validator and AMP test on Google Search Console

### ISSUE THREAD

**Issue by anuragphadke** [ampproject/amphtml#26685]
## What's the issue?
AMP HTML validator tags a page is valid, however, GSC gives validation errors.
Briefly describe the bug/feature request.

## How do we reproduce the issue?

1. Visit https://beta.webfast.co/lgkwealth-ca/services-our-process.html
2. Ensure you have the AMP HTML Validator Chrome extension from https://chrome.google.com/webstore/detail/amp-validator/nmoffdblmcmgeicmolmhobpoocbbmknc?hl=en
3. Chrome extension will say the page is valid.
4. Enter the same URL at https://search.google.com/test/amp

The above report will throw errors on SVG side.
## What browsers are affected?
All browsers are affected

## Which AMP version is affected?
version: 2001281851410

**Comment by banaag** [comment]
cc @ampproject/wg-caching

**Comment by Gregable** [comment]
Hi @anuragphadke,

Your HTML has the following (simplified) structure:

```
<svg style="..." version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>

    <div class="symbol" id="icon-facebook">
      <path d="...">
      ...
    </div>

    ...
  </defs>
</svg>
```

`<div>` is not a legal child of `<svg>`. An HTML parser, including the AMP Validator will thus close the `<svg>` tag when it encounters the `<div>`, such as:

```
<svg style="..." version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>
  </defs>
<svg>

<div class="symbol" id="icon-facebook">
  <path d="...">
   ...
</div>

</defs>
</svg>
```

The AMP Validator then encounters the `<path>` tag, which is not valid outside of `<svg>` and you get the error you see.


This isn't AMP-related. Open Chrome and inspect the DOM of the document you linked to. The DOM will be the same as the 2nd version I posted.

The validator on validator.amp.dev is limited in it's parser capability and doesn't know about what's a legal child tag of `<svg>` which is where we run into this.

Should be an easy fix on the web page side.

**Comment by anuragphadke** [comment]
@Gregable : thx for the reply. 
Will the limitation in parser be fixed in future?

**Comment by Gregable** [comment]
Possibly, though this is very rare and considered a low priority issue to fix.

Note that if the parser were to be fixed, the result would be that all AMP Validators consider this page invalid, not that the page would become valid.
