### ISSUE TITLE
Document minimal <amp-analytics> configuration for Google Analytics

### ISSUE THREAD

**Issue by rrjanbiah** [ampproject/amphtml#26691]
## Describe the new feature or change to an existing feature you'd like to see

For using Google Analytics through `amp-analytics` there are multiple documents and sort of confusing. For example, some documents refer to `type="gtag"` and few others refer to `type="google-analytics"`. Similarly few documents refer to `account` property and few others `gtag_id` and so on. 

Most confusing aspect is with tracking data https://amp.dev/documentation/guides-and-tutorials/start/add_advanced/tracking_data/ Some example suggests that we need to pass URL and few others suggest that we can use inbuilt variables like `${ampdocUrl}`

So, it is not very clear, if we really have to configure all page tracking params to get Google Analytics working?

For Google Analytics, it would be ideal to provide simple configuration and explain what are available with it and what not.

**Comment by micajuine-ho** [comment]
Hi @rrjanbiah. 

> For example, some documents refer to type="gtag" and few others refer to type="google-analytics".

Gtag and google analytics are two different vendors. [Here](https://www.analyticsmania.com/post/google-tag-manager-vs-google-analytics/) is an article that can help you understand how they differ.

These examples are showing you how you can use different [vendor configs](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md#sending-data-to-an-analytics-vendor-)

> Some example suggests that we need to pass URL and few others suggest that we can use inbuilt variables like ${ampdocUrl}

[Here is the documentation](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md#vars) on `vars` that might help clear things up.

> So, it is not very clear, if we really have to configure all page tracking params to get Google Analytics working?

In the spec linked above, you can see that variables that are not configured will just resolve to null.

> For Google Analytics, it would be ideal to provide simple configuration and explain what are available with it and what not.

The example that you linked to above shows an example of a perfectly valid configuration  for `<amp-analytics>`using `type=googleanalytics`. Do you have a specific question about the config?

**Comment by rrjanbiah** [comment]
@micajuine-ho Thank you so much for your attention and quick reply.

> > For example, some documents refer to type="gtag" and few others refer to type="google-analytics".
> 
> Gtag and google analytics are two different vendors. [Here](https://www.analyticsmania.com/post/google-tag-manager-vs-google-analytics/) is an article that can help you understand how they differ.

But, kindly refer to these links (ranked top in Google):
1. https://developers.google.com/gtagjs/devguide/amp
2. https://developers.google.com/analytics/devguides/collection/amp-analytics

Both the links are referring to `gtag`. Similarly, Google mostly bring top results of the form:
```html
<amp-analytics type="gtag" data-credentials="include">
  <script type="application/json">
    {
      "vars" : {
        "gtag_id": "UA-XXXX",
        "config" : {
          "UA-XXX": {
             "groups": "default",
             "linker": { "domains": ["foo.com"] } 
          }
        }
      }
    }
    </script>
</amp-analytics>
```
We're also using like above in couple of sites. (So, the concern here is "minimal" setup for Google Analytics when using AMP)


> These examples are showing you how you can use different [vendor configs](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md#sending-data-to-an-analytics-vendor-)

I hope, you'll take this feedback in a positive sense. Basically, there are so many information. But, what we need is "minimal" setup for Google Analytics.

> > Some example suggests that we need to pass URL and few others suggest that we can use inbuilt variables like ${ampdocUrl}
> 
> [Here is the documentation](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md#vars) on `vars` that might help clear things up.
> > So, it is not very clear, if we really have to configure all page tracking params to get Google Analytics working?
> 
> In the spec linked above, you can see that variables that are not configured will just resolve to null.
> 

Sorry, I was not clear. 

Kindly refer to these 2 links:
1. https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#title (suggests that we can use `${title}`
2. https://amp.dev/documentation/guides-and-tutorials/start/add_advanced/tracking_data/ :

<details>
  <summary>Code from above link</summary>

```html
<amp-analytics type="googleanalytics">
<script type="application/json">
{
  "vars": {
    "account": "UA-YYYY-Y"
  },
  "triggers": {
    "default pageview": {
      "on": "visible",
      "request": "pageview",
      "vars": {
        "title": "Name of the Article"
      }
    }
  }
}
</script>
</amp-analytics>
```  
</details>

Note that it looks like we can use `${title}` instead ` "title": "Name of the Article"`. But, it is not very clear from document perspective. 

> > For Google Analytics, it would be ideal to provide simple configuration and explain what are available with it and what not.
> 
> The example that you linked to above shows an example of a perfectly valid configuration for `<amp-analytics>`using `type=googleanalytics`. Do you have a specific question about the config?

Again, for example https://amp.dev/documentation/guides-and-tutorials/start/add_advanced/tracking_data/ :

<details>
  <summary>Code from above link</summary>

```html
<amp-analytics type="googleanalytics">
<script type="application/json">
{
  "vars": {
    "account": "UA-YYYY-Y"
  },
  "triggers": {
    "default pageview": {
      "on": "visible",
      "request": "pageview",
      "vars": {
        "title": "Name of the Article"
      }
    }
  }
}
</script>
</amp-analytics>
```

</details>

1. It is not clear, if really need to add `triggers` to get `pageview` tracked.
2. If `triggers` is completely removed, will it still track? (Seems to track based on my experience. But, I used `gtag` variant as mentioned above)

**Comment by micajuine-ho** [comment]
I understand. I agree that the documentation can be a lot to ingest. I would suggest you play around with test examples. You can test locally by creating amp pages in the `test/manual` folder. A good place to start would be to play around with the files in `test/manual/amp-analytics` and explore their output in the dev console.

As for a minimal example, the following will start to track for you: 
```
<amp-analytics type='googleanalytics'></amp-analytics>
```

Vy doing `type=....` amp-analytics imports that specific vendor's JSON and uses it as the tracking API. If you were to include your own inline JSON inside a <script> within amp-analytics, your JSON would be merged with the vendor's JSON. You might want to do this if you wanted to track different events/requests than the preset `googleanalytics` events. You can explore the googleanalytics JSON [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/vendors/googleanalytics.json).

**Comment by rrjanbiah** [comment]
@micajuine-ho Wow!, your comment is an eye opener. `type="googleanalytics"` does all the basic configuration automatically. That's awesome. So, I believe, this is the "minimal" code required:

```html
<amp-analytics type="googleanalytics" data-credentials="include">
<script type="application/json">
{
	"vars": {
		"account": "UA-XXXXX"
	}
}
</script>
</amp-analytics>
```

Like you've suggested, may have to play around to get correct understanding and minimal code to use. But, at this point of time (without playing around), https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/vendors/googleanalytics.json is clear on `timing`, but NOT clear on `pageview` (Do we still need to add trigger?) and `social`

**Comment by micajuine-ho** [comment]
>  So, I believe, this is the "minimal" code required:

Yes that sounds right.

> pageview (Do we still need to add trigger?) 

Since there are no `triggers` in the config that say: `request: pageview`, then you will need to add that trigger to **your** inline config. Same for `social`.

**Comment by rrjanbiah** [comment]
@micajuine-ho Thank you so much for your comments. I have also opened a related ticket #26808 if that helps
