### ISSUE TITLE
Write documentation for the stories tooltip analytics.

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#26693]
I think we forgot to write the documentation for the stories expandable elements (tooltip) analytics: https://github.com/ampproject/amphtml/pull/25547(and maybe also https://github.com/ampproject/amphtml/pull/25649?)

**Comment by deeksha-agarwal** [comment]
Hi @gmajoulet is the documentation avaliable now for the new tooltip analytics. I can't seem to find anything in docs. Thanks in advance!

**Comment by Enriqe** [comment]
Hi @deeksha-agarwal ! Sorry, we haven't gotten to it yet, but I will send a PR soon. I'll add you to make sure you get notified.

**Comment by Enriqe** [comment]
Just sent out #28534 to address this

**Comment by deeksha-agarwal** [comment]
Thanks @Enriqe for your prompt reply!
