### ISSUE TITLE
Validator Chrome Extension no longer shows a list of errors in Chrome 80

### ISSUE THREAD

**Issue by merapi** [ampproject/amphtml#26712]
## What's the issue?

Validator Chrome Extension no longer shows a list of errors in Chrome 80.

![empty list](https://i.ibb.co/rGH7YLX/S-gJmjbY.png)

Error message: `Uncaught TypeError: document.registerElement is not a function`

**Cause**: `registerElement` was removed in Chrome 80 
https://www.chromestatus.com/features/4642138092470272

**Possible solution**: Add `registerElement` polyfill? so rewrite will not be required.

## How do we reproduce the issue?

1. Check any website with AMP errors (like this one https://jade-universe-v22uo4o1i.glitch.me/)

## What browsers are affected?

Chrome 80+.

## Which AMP version is affected?

Not related.

**Comment by kristoferbaxter** [comment]
Looks like this is due to a 503 error from https://validator.ampproject.org/

**Comment by merapi** [comment]
Found it way earlier (when site was fine).
Was working in Chrome 79 and also after hot fixing it with polyfill in Chrome 80.

**Comment by honeybadgerdontcare** [comment]
The release version (1.1.6) with this fix is currently being deployed in Chrome Web Store.
