### ISSUE TITLE
Doc update: amp-iframe origin policy + CORS

### ISSUE THREAD

**Issue by jmadler** [ampproject/amphtml#2673]
How does CORS impact the [amp-iframe origin policy](../tree/master/spec/amp-iframe-origin-policy.md)?

**Comment by bpaduch** [comment]
@adelinamart  - Can we assign this to a developer who's familiar with these topics?

**Comment by adelinamart** [comment]
@rudygalfi who will be the best person to answer here

**Comment by rudygalfi** [comment]
I nominate @cramforce  :)
