### ISSUE TITLE
🌸 Cherry-pick request for PR/26340 into 2002072310350, 2001281851410, 2002072311510, 2002041606330 (Pending)

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#26742]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| N/A | #26340 #26776 #26780 #26795 #26851 |     **YES**     | **YES** | **YES** | 2002072310350, 2001281851410, 2002072311510, 2002041606330                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?
This is needed to ramp up new functionality in the AMP cache, and we will need these new `mjs` files in case a rollback is needed. It would cause an outage if the files don't exist on the rollback versions.

## Why is an LTS cherry-pick needed?
To not cause an outage in case rollback's are needed.

## Summary

There is currently no "problem" this is in case a rollback is needed where the new functionality on the AMP cache will look for "mjs" files to serve instead of "js" files

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by cramforce** [comment]
Approving this special-case (forward-backward-compat 🥇 ) cherry-pick!

**Comment by erwinmombay** [comment]
This has been cherry picked into LTS (2002191527100), stable (2002200031230), and latest experimental (2002192257490) last week.
