### ISSUE TITLE
🌸 Cherry-pick request for #26665 into 2001281851410, 2002041606330 (Pending)

### ISSUE THREAD

**Issue by ChrisAntaki** [ampproject/amphtml#26746]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #26665 | #26702 |     **YES**     | **YES** | **NO** | 2001281851410, 2002041606330                       |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

There is a P0 bug that breaks existing AMP web pages in a significant way. Basically the `amp-subscriptions` "click" event listener is not working inside of FixedLayer elements.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

The `amp-subscriptions` "click" event listener is not working inside of FixedLayer elements.

| Users affected                                   | Impact                                                                       |
| ------------------------------------------------ | ---------------------------------------------------------------------------- |
| Users on iOS 12 or lower | Users couldn't click SwG buttons like "sign in", or "subscribe" in the AMP viewer, if these buttons were inside of a FixedLayer element |

## Root Causes

1. I updated a click listener within `amp-subscriptions` to listen on the root's `body` property if it was present. This didn't work with FixedLayer though, which activates on iOS 12 and lower, since FixedLayer creates a second body element and moves elements into it. So those moved elements had click events bubble up to the root, and the listener on the original body wasn't seeing them.

## Action Items

| Action Item                   |               Type               |     Owner     |      PR #      |
| ----------------------------- | :------------------------------: | :-----------: | :------------: |
| Improve SwG tests to catch regressions relating to FixedLayer | Prevent | ... | ... |
| Improve SwG tests to catch regressions relating to `amp-bind` | Prevent | ... | ... |
| Create an effective testing plan for future PRs | Prevent | ... | ... |

### Things that went well

- AMP team was very helpful and generous with their time.

### Things that went wrong

- Issue was not caught by automated tests.

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by ChrisAntaki** [comment]
Hey @erwinmombay , I was able to verify iOS 13 Safari, iOS 11 Safari, and Android 9 Chrome work with the experimental version 2002112037430. I tested these with BrowserStack, which supports using DevTools on iOS Safari. I used the DevTools console to confirm version 2002112037430 was being tested. I couldn't verify iOS 12 because I couldn't get it to load the experimental version 2002112037430 for whatever reason, maybe cookies.

**Comment by rcebulko** [comment]
@erwinmombay @zhouyx @ChrisAntaki What is the status of this cherry-pick? Which releases is it in? It definitely doesn't appear to be in LTS yet; not sure about Stable or Experimental/Beta.

**Comment by erwinmombay** [comment]
@rcebulko it is now in stable and experimental/beta, not yet in LTS (i'm preparing the release)

**Comment by erwinmombay** [comment]
This was cherry picked into LTS (2001281851410, 12002191527100), last week's stable (2002112037430), this weeks stable (2002200031230), and latest experimental (2002192257490)
