### ISSUE TITLE
Teads.tv Structure Update

### ISSUE THREAD

**Issue by dmitrymotorin** [ampproject/amphtml#2675]
Hey guys,
We've set amphtml teads.tv ad container but it didn't become available. Teads.tv support told us that we use an old tag structure of ad container and they have updated the structure.
Could you check please?

**Comment by jridgewell** [comment]
Ping @RonanDrouglazet.

**Comment by RonanDrouglazet** [comment]
Hi @dmitrymotorin ! You can find the right tag structure on https://github.com/ampproject/amphtml/blob/master/ads/teads.md

Can you give me your contact at Teads's support please ?

**Comment by RonanDrouglazet** [comment]
And thanks @jridgewell for the ping ;)

**Comment by jridgewell** [comment]
> And thanks @jridgewell for the ping ;)

Welcome. I'm going to close this, but please continue commenting if something needs to change with the Teads component.

**Comment by dvoytenko** [comment]
https://github.com/ampproject/amphtml/pull/2190 created by @RonanDrouglazet is already in PROD so it should be fully available. @dmitrymotorin are you seeing some errors? Or is the ad simply not filled?

**Comment by dmitrymotorin** [comment]
@dvoytenko the ad simply not filled

**Comment by dmitrymotorin** [comment]
@RonanDrouglazet Jim Ausanio jim.ausanio@teads.tv
