### ISSUE TITLE
📦All of url-replacement-impl is bundled into amp-a4a.js

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#26789]
Affects all of the following extensions
```
amp-ad-network-adsense-impl-0.1.js
amp-ad-network-adzerk-impl-0.1.js
amp-ad-network-cloudflare-impl-0.1.js
amp-ad-network-doubleclick-impl-0.1.js
amp-ad-network-fake-impl-0.1.js
amp-ad-network-gmossp-impl-0.1.js
amp-ad-network-mytarget-impl-0.1.js
amp-ad-network-triplelift-impl-0.1.js
```

Possibly could use the service getter instead? Should lead to significant bundle size reduction. Might be difficult to use dynamic amp doc and win.

to/ @ampproject/wg-ads

**Comment by erwinmombay** [comment]
@ampproject/wg-performance do tradeoff analysis how much code this will move into v0.js
