### ISSUE TITLE
I2I: Expose AMP JS resource timing metrics via the Resource Timing API to the viewer

### ISSUE THREAD

**Issue by zhangsu** [ampproject/amphtml#26796]
## Summary

Similar to how AMP currently exposes to the viewer performance metrics such as `first-contentful-paint`, it'd be nice if AMP also leverages the [Resource Timing API](https://developer.mozilla.org/en-US/docs/Web/API/Resource_Timing_API/Using_the_Resource_Timing_API) to get things like the cache hit rate of the AMP JS. `transferSize` of 0 should give you a signal if the entry is loaded from cache [also zero for cross-origin](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming/transferSize).

## Design document

TODO: will delegate this to Erwin's team.

## Motivation

This allows embedders to gather metrics about the performance of loading the AMP JS, which is valuable when the embedders do something like prefetching AMP JS.

## Additional context

N/A

## Launch tracker

N/A

/to @erwinmombay 
/cc @ampproject/wg-approvers
/cc @ericfs 
/cc @kevinkimball 
/cc @kristoferbaxter

**Comment by kevinkimball** [comment]
Implemented by #27311
