### ISSUE TITLE
amp-script: Improve messaging for non-mutating AMP.setState

### ISSUE THREAD

**Issue by morsssss** [ampproject/amphtml#26816]
As per discussion in #26401 and #26524 :

Currently, in an <amp-script> container that's variable-sized (as defined in #26524), `AMP.setState()` is simply not allowed on load, even when that state change doesn't cause a DOM mutation. In other words, it's not allowed even when the state change wouldn't change anything the user could see.

Is it worth allowing this, perhaps by simply not following through on binds in such cases? Or is that even *more* confusing?

**Comment by samouri** [comment]
> Is it worth allowing this, perhaps by simply not following through on binds in such cases? Or is that even more confusing?

I'm pretty sure thats exactly what we are currently doing. We change state, but don't trigger bind reevaluation.

**Comment by morsssss** [comment]
I see! I think this was changed after we discovered this issue, but before I reported it 😈 

I'd like to clarify this error message, though. Maybe something like this:

`AMP.setState updated the state variable. But criteria for recent user interaction were not met, so bindings weren't updated.`

Or perhaps:

`Since user interaction and fixed-size container criteria weren't met, page bindings weren't updated after setState().`

We need a better - and standardized - phrase for "criteria for recent user interaction", which could also be used in [places like this](https://github.com/ampproject/amphtml/blob/80a3bb91ccb482e66a8e4a2b40e4d1444d6994c7/extensions/amp-script/0.1/amp-script.js#L436).

**Comment by kristoferbaxter** [comment]
The longer these error messages get, the more we need to move them to documents and urls in the console.

Jake, do you want to have a chat about taking over the work that was started here?

**Comment by morsssss** [comment]
I had that concern too. I don't want to waste bytes!

A link or standard phrase could replace "Since user interaction and fixed-size container criteria weren't met". I've also written up an explanation of when mutations are and are not allowed, which I've got in a Doc right now. That could be published, and these could refer to that.
