### ISSUE TITLE
`amp-mega-menu` won't let GTM the `button`s be used as trigger

### ISSUE THREAD

**Issue by erakor** [ampproject/amphtml#26818]
## What's the issue?

When trying to select the `button`s inside a `amp-mega-menu` using GTM (e.g. "click on amp-mega-menu button"), no event is ever fired.
The exact same `button`s, but not wrapped within the mega menu work fine.

I know this is an experimental component. I'd love to see if we can get that fixed before it hits the prod mode.

## How do we reproduce the issue?

1. Add a `amp-mega-menu` menu to your page;
2. Add the necessary GTM config object on your page;
3. Add a trigger to GTM targeting the `button` inside the `amp-mega-menu`;
4. Confirm using a event racker (we use Event Tracking Tracker Chrome extension) that no event is fired when `button`s are clicked.

**Comment by wassgha** [comment]
Hello, @erakor! Thank you for bringing this to our attention. Is there a demo/jsfiddle that you could share with us? Otherwise, could you please paste the GTM config here?

**Comment by mdvb1001** [comment]
@wassgha We are having the same issue. Would be great to see a fix for this. Let me know if there's anything I can do to help.

**Comment by nainar** [comment]
@mdvb1001 is there a demo URL you can share with us?

**Comment by nainar** [comment]
Please file a new issue if a demo link is available. Thank you!
