### ISSUE TITLE
AMP-LIST supports `[src]='https://example.com'+location.search`

### ISSUE THREAD

**Issue by myhirra** [ampproject/amphtml#26827]
Sometimes we need send `location.search` to remote server , however , apm-list doesn't support right now.

**Comment by mdmower** [comment]
Could you use `QUERY_PARAM` [variable substitution](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md)? Be sure to read about per-use opt-in in that document as well.

**Comment by myhirra** [comment]
Thanks, I had a try before , but I couldn't get all params by one key, like `location.search` . if using QUERY_PARAM, I have to get all keys one by one
