### ISSUE TITLE
<amp-script>: setState() updates all state variables

### ISSUE THREAD

**Issue by morsssss** [ampproject/amphtml#26825]
I may be missing something. But, as far as I can tell, if I use `AMP.setState()` within `<amp-script>`, I end up updating every state variable in the document.

Actually, given the API that's described, I don't know how AMP would know which state variable I wished to change - unless that was determined by the previous `AMP.getState()`. I'd suggest an API where `setState()` let me choose the state variable I was updating, as in:

`setState(variableName, jsonToMerge)`

Here's a simplified version of the code where I saw this behavior. In this case, both `<span>`s update.

```HTML
<head>
  <script id="myscript" type="text/plain" target="amp-script">

    changeState();

    async function changeState() {
      let text = await AMP.getState("text");
      AMP.setState({foo: "we changed it"});
    }
  </script>
</head>
<body>
  <amp-state id="text">
    <script type="application/json">
      {
        "foo": "bar"
      }
    </script>
  </amp-state>

  <amp-state id="otherText">
      <script type="application/json">
        {
          "foo": "bar"
        }
      </script>
  </amp-state>
  
  <amp-script layout="responsive" script="myscript" height="300" width="1000" data-ampdevmode>
    <div>
      <p><b><span [text]="text.foo">This text</span></b> will change.</p>
      <p><b><span [text]="otherText.foo">This text</b> should not change. But it does!</p>
    </div>
  </amp-script>
</body>
```

**Comment by morsssss** [comment]
Actually, it's simpler than that. The JavaScript can simply look like this:

```html
  <script id="myscript" type="text/plain" target="amp-script">
    AMP.setState({foo: "we changed it"});
  </script>
```

/cc @andrewkguan

**Comment by mdmower** [comment]
@morsssss It looks like you're setting the global `foo` state in your example. Have you tried setting `foo` under a specific `amp-state`?
```
AMP.setState({otherText: {foo: 'we changed it'}})
```

**Comment by morsssss** [comment]
Yeah - looks like I got confused here, both by the `setState` syntax and the fact that all state bindings update when you update a single state. (Now I know this happens because of the way state variables are implemented.) This behavior's a little surprising but is as expected. Closing.

**Comment by samouri** [comment]
> all state bindings update when you update a single state.

I don't believe you even need to set a single state. Another way to think about it is that bind values are not used on init, but the second that `amp-state` is modified with high trust (user action), all the bound attributes on the page become active.

Even an empty setState could update all the bindings on the page:
```
AMP.setState({});
```
