### ISSUE TITLE
I2I: Trinity Audio Player extension

### ISSUE THREAD

**Issue by industral** [ampproject/amphtml#26836]
## Summary

Trinity Audio proposes an <amp-trinity-player> component to enable publishers to audiofy their content using our cloud-hosted audio player.
To use the component, it is required to have an account with Trinity Audio (there is a free option). Registration is through our site (trinityaudio.ai).

## Motivation

Trinity Audio allow textual content creators the option to distribute and interact with their readers using audio.
By doing so, it allows users to enjoy the high quality content they are already consuming in times when they couldn't before.
As of so, most consumption is done from mobile, and a significant amount of publishers integrated AMP.
By adding the Trinity component, it will allow all of those AMP-publishers the ability to (freely) explore how users interact with their content in audio.
More so, it improve the accessibility of the content as people who are visually impaired or don't read well can enjoy content they couldn't before.

Since Trinity Player reads content from a page by provided selector (configures it on backoffice dashboard, later will be added ability to rewrite it by parameter, as we already have it in our Javascript version of player), we need somehow pass it to our player.
We've tried to achieve that by using `amp-iframe`, but it's impossible to pass a text as it doesn't support `postMessages` yet. Also it required complicated setup. Neither approach with `amp-state` works, due to it will not reflect state update if there were no user interaction upon component.

PR did similar to https://amp.dev/documentation/components/amp-jwplayer/ and https://amp.dev/documentation/components/amp-minute-media-player/ extensions.

/cc @ampproject/wg-approvers

**Comment by alanorozco** [comment]
> but it's impossible to pass a text as it doesn't support postMessages yet

What this means is that the proposed component [passes `document.body.innerHTML` to an external URL on initialization](https://github.com/ampproject/amphtml/pull/26837/files/824e742be51ddf54638d6bb2c976d1afd8cd314a#diff-ba86024657b7943fd9c154b2768841a5R70):

https://github.com/ampproject/amphtml/blob/824e742be51ddf54638d6bb2c976d1afd8cd314a/extensions/amp-trinity-tts-player/0.1/amp-trinity-tts-player.js#L65-L70

I'm not sure this should be allowed for privacy reasons. This would send all user content on the page to a third-party without consent.

@ampproject/wg-security-privacy for review of this feature.

**Comment by honeybadgerdontcare** [comment]
@molnarg

**Comment by shlomisut** [comment]
Hey @alanorozco, let me try to add some context to the requirement here.
As stated, Our widget is used to transform article text into audio, and for that we require access to the text.

I'm not sure what you mean by "User content" - this is the same content that is accessible to us in our HTML integration,Which is only done with consent by the publisher, who owns the content. Our plugin does not work with publishers without such an agreement.

If there's another way to access the page content (other than wrapping the whole page with our component, which is unlikely to be done by any publisher) we'd be happy to use it. As @industral  stated, we've looked around & tried different ways before coming to this solution.

Happy to add more details if required,
Thanks, Shlomi

**Comment by alanorozco** [comment]
@shlomisut 

`innerHTML` can always contain user content outside the scope of this component even if it’s not modified explicitly. It is not static and will change before this component is laid out by the runtime. 

This is the user content that can leak:

- consent state as defined after interacting with `amp-consent`

- authorization tokens and user ids as defined by content laid out by `amp-ad`

- personalization state fetched dynamically with something like `amp-list`. This can be anything and publishers may use it for potential PII. 

- any bound and changed state via `amp-bind`, `amp-state` and or `amp-script`. I may be missing a lot of other components that may change `innerHTML`, potentially containing user data. 

The publisher defines the content, but will still inadvertently leak some if not all of this by using this component alone. 

So it definitely needs privacy review. Pinging @molnarg 

Personally, the only way I can see this working is with publishers rewriting their documents in a way that this component would always take one `.textContent` TextNode that only contains the statically defined “article content” or similarly. 

(Wrapping the entire page in another tag is the same as the `body.innerHTML` problem so I don’t believe that’s an option.)

**Comment by honeybadgerdontcare** [comment]
I agree with @alanorozco. This is something that will need a more detailed privacy review. It will have to wait till that is completed or taking the other approach that @alanorozco mentions.

**Comment by molnarg** [comment]
Instead of sending the content of the page, wouldn't the URL of the page (without URL fragment) be enough? After that, the service can fetch the content, render it, and generate audio from it. This way, no user data is leaked, but would still work well for the use cases that this service seems to be focusing on (news, other static content).

**Comment by industral** [comment]
we have publisher with news via subscriptions, and our JS version of player works well there. In case of fetching URL we need to do that request on server with cookies, that even worse in that case. Even if we'll able to do that, some tokens could be bind to specific IP, and it will not work.

Suggestions:
1. extension could accept CSS selector what should be read, and publisher has to specified it. We'll read **only** content using that selector.
2. publisher gives his consent about reading text on a page by passing parameter to component explicitly e.g.`data-allow-to-read-page-content="1"`

**Comment by alanorozco** [comment]
@industral 

> 1. extension could accept CSS selector what should be read, and publisher has to specified it. We'll read only content using that selector.

They could simply select `body`, creating the same issue as the original proposal.

> 2. publisher gives his consent about reading text on a page by passing parameter to component explicitly e.g.`data-allow-to-read-page-content="1"`

It's not about publisher consent, it's about user consent. Tagging publisher consent is effectively the same as including the extension.

So I don't believe this approach works. Please consider **a.** a static `TextNode` or **b.** fetching a URL independently.

---

> In case of fetching URL we need to do that request on server with cookies, that even worse in that case.

What do you mean by this? Do you require user cookies to read the content?

> we have publisher with news via subscriptions, and our JS version of player works well there. 

Do you mean this approach works fine on documents that aren't AMP? 

AMP makes some [decisions that are additional to the web platform overall](https://amp.dev/about/mission-and-vision/), in order to prioritize user experience. Privacy problems like these are what we're trying to avoid :)

**Comment by shlomisut** [comment]
Hey @alanorozco  @honeybadgerdontcare 
Thanks for clarifying and the suggestions.  We'll see if We can utilize your suggestion, the issue is that this adds another layer of integration friction which We try to reduce. 

As for using the URL to fetch the content (as @molnarg suggested) - we have looked into that before, that has  issue with dynamically loaded content, subscriptions etc

We'll wait for the privacy review, While validating the addtional text tag option with our publishers.

Thanks
Shlomi

**Comment by alanorozco** [comment]
> We'll wait for the privacy review

So far as @molnarg, @honeybadgerdontcare and I have mentioned, the result of privacy review this cannot go through in this form.

> As for using the URL to fetch the content (as @molnarg suggested) - we have looked into that before, that has issue with dynamically loaded content, subscriptions etc

So this is a user credentials problem. With the `TextNode` approach, publishers can authenticate the content, while also scoping it and not leak anything else.

> While validating the addtional text tag option with our publishers.

Please make sure to update this issue with this approach. Once you've validated this, please book [a design review meeting](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md). Any new component needs to be approved this way.
