### ISSUE TITLE
🌸 Cherry-pick request for #26844 into X (no release ticket for the current week) (Accepted)

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#26846]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #26844 | #26793 |     **YES**     | **YES** | **NO** | #<_RELEASE_ISSUE_>                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

This issue leads to broken story templates for prerendered SRP stories. Publishers are impacted in different ways, but the celebrity stories are unreadable.

![image](https://user-images.githubusercontent.com/1492044/74767372-c25fa500-5254-11ea-9123-86b23c3b79b4.png)
![image](https://user-images.githubusercontent.com/1492044/74767389-c7245900-5254-11ea-80e5-eb115c5c0457.png)

# Mini-postmortem

## Summary

In very specific circumstances, the `onMeasuredChange()` callback does not trigger, cf https://github.com/ampproject/amphtml/issues/26866.
The code living in this callback is responsible for setting a few CSS variables, used by publishers to size elements and create responsive templates. These CSS variables not being set, the templates appeared heavily broken.

For the bug to happen, the story would need to be in the `prerender` `visibilityState` AND have a lot of AMP elements (38 was the threshold on my testing story but that might not be relevant).

| Users affected                                   | Impact                                                                       |
| ------------------------------------------------ | ---------------------------------------------------------------------------- |
| Celebrity Google Stories users (eg: Tony Hawk) | Very broken templates (cf screenshots) |

## Root Causes

1.https://github.com/ampproject/amphtml/issues/26866

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by cramforce** [comment]
Approved

**Comment by erwinmombay** [comment]
@gmajoulet why don't we need this in LTS ?

**Comment by gmajoulet** [comment]
Thanks Erwin we're right, the PR introducing the issue (https://github.com/ampproject/amphtml/pull/26449) is also in LTS, so we need the fix in the LTS version.

**Comment by rcebulko** [comment]
@erwinmombay @gmajoulet LTS is supported only in AMP Webpages; it is invalid AMP in Stories. This doesn't need to be cherry-picked into LTS

**Comment by rcebulko** [comment]
@gmajoulet To confirm, this is an issue with the story itself, not the viewer, correct?

I'm not too familiar with how stories are embedded. By my understanding, the actual AMP Story is sort of a standalone HTML page, which is then rendered in an iframe by the viewer. The AMP Story HTML cannot currently use LTS and be considered valid AMP. An outer page could be using LTS, and could display a story-viewer. Am I understanding correctly, and given this is my assessment correct that the patch is not required in LTS?

**Comment by rcebulko** [comment]
Update: I can't confirm that it would be a validator error to use LTS in a Story. They are not officially supported, and documentation indicates as much (and adoption is very minimal at present), but if the regression risk of the fix to other components is minimal it should be fine to patch into LTS

**Comment by gmajoulet** [comment]
Here's the code that, when running, sometimes create our bug:
https://github.com/ampproject/amphtml/blob/c0454f7095a2a07d99e626b9c320f7b302d8541a/src/service/viewport/viewport-binding-ios-embed-wrapper.js#L178-L184

Looks like it's only for when iframed (viewer) and iOS.

**Comment by gmajoulet** [comment]
https://github.com/ampproject/amphtml/pull/26793 has been merged cc @zhouyx

**Comment by zhouyx** [comment]
@erwinmombay is currently working on the cherrypick.

**Comment by gmajoulet** [comment]
The cherry-picked fix was not working.
We uncovered a bug in the AMP runtime (#26866) and are sending a PR to work around it until it's fixed https://github.com/ampproject/amphtml/pull/26871. This PR should be cherry-picked.

**Comment by gmajoulet** [comment]
cc @cramforce can we cherry-pick the followup pr #26871? (Cf previous message)

**Comment by rcebulko** [comment]
I'm guessing this is in LTS as well?

**Comment by gmajoulet** [comment]
This new PR is already in this week's canary build and should only be cherry-picked on master. The previous PR hasn't been added in LTS.

**Comment by zhouyx** [comment]
To clarify, 2002191442400 contains the previous fix (#26793) is already in prod. 
#26871 need to be patched to prod, and we also need to include it in the new canary cut.

**Comment by cramforce** [comment]
Approved

**Comment by rcebulko** [comment]
#26793 was cherry-picked into LTS already. Is there another PR that needs to be cherry-picked into LTS to fix something #26793 broke?

**Comment by zhouyx** [comment]
From @gmajoulet patch to LTS is not required, and the previous patch (#26793 to LTS) has no side effect.

**Comment by gmajoulet** [comment]
Fixed at 9:59 AM, Feb 20, 2020 UTC-5
