### ISSUE TITLE
onMeasureChanged() not called sometimes when prerendered

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#26866]
### Summary

If an AMP component is built *after* measure (and the build doesn't affect the component's layout box), `onMeasureChanged` won't be invoked. 

I.e. `opt_measurementsChanged == true` but `isBuilt() == false`:
https://github.com/ampproject/amphtml/blob/8f0aa2d54ee3bfea22ed15292b4b1a24ce88e3f2/src/custom-element.js#L602-L610

### Details

This is somewhat unexpected because usually build precedes measure in our `discoverWork_()` flow.

In some cases, however, a component can skip build (phase 1) due to prerender quota, get measured (phase 2), and then get built here (phase 4):
https://github.com/ampproject/amphtml/blob/8f0aa2d54ee3bfea22ed15292b4b1a24ce88e3f2/src/service/resources-impl.js#L1129-L1142

In the next pass, the component will get measured again now that it's built. However, if this measure doesn't change its layout box, `onMeasureChanged` won't get invoked!

/cc @ampproject/wg-runtime

**Comment by gmajoulet** [comment]
Once this bug is fixed, https://github.com/ampproject/amphtml/pull/26871 should be reverted.

**Comment by jridgewell** [comment]
I thought we fixed this with https://github.com/ampproject/amphtml/pull/23718.

**Comment by choumx** [comment]
We do the measure, so the issue isn't a stale layout box. The issue is that `onMeasureChanged` callback is never invoked.
