### ISSUE TITLE
Add LTS opt-in channel to experiments.html

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#26861]
Particularly in the case of LTS cherry-picks, team members are asking how to test LTS. They could look up the LTS version and do an RTV opt-in, but this could be provided as an easy option in experiments.html

**Comment by rcebulko** [comment]
This would also be really useful for publishers to test their sites before actually making the code changes to use LTS

/cc @nainar

**Comment by danielrozenberg** [comment]
Dissenting opinion: I don't know if this is a good solution here. LTS, unlike beta and experimental, is opted-in to by the publishers, and requires they make code changes to their website. I would expect publishers that want to make code changes to their own website to have a dev or staging server where they can make those changes and test them

**Comment by rcebulko** [comment]
That's a pretty heavyweight change, and takes a lot more effort than opting into a channel. As mentioned above, it would also be really useful for testing the LTS release in general, and in the case of cherry-picks

**Comment by danielrozenberg** [comment]
(I don't feel strongly about my dissenting opinion, but I want to hear what others think about this. Not sure who should be CC'd here)

**Comment by rcebulko** [comment]
I would also guess that there may be publishers using site-building tools or CMS platforms without support for creating a staging environment

**Comment by nainar** [comment]
I think this is good for internal debugging (quickly verifying that an issue doesn't exist on an LTS release as opposed to current weekly release). I agree that engineers having to  RTV opt-in isn't a good user flow. For that reason would support one on experiments.html if possible. Don't see publishers using this for the reason @danielrozenberg mentioned.

**Comment by danielrozenberg** [comment]
@rcebulko where are we on this? :)

**Comment by rcebulko** [comment]
I may have mistakenly assumed that you were the deciding vote on this/would be the one to implement, since you are so familiar with `experiments.html`. It seems you may have had a similar impression toward me :sweat_smile: 

![image](https://user-images.githubusercontent.com/6694512/80753637-96d22400-8afb-11ea-9381-8c9d2d247947.png)

I can put this in my queue :+1:

**Comment by danielrozenberg** [comment]
I meant to ask where are we with respect of whether we are intending to make this happen at all

**Comment by rcebulko** [comment]
I think we're at a "would be nice to have, but not high priority". Bumped down to P3

**Comment by rcebulko** [comment]
Given that this will require a network request to find out the LTS RTV, the added complexity here may not be worth the dev time. Punting this until we add dropdown of RTVs, if we ever get there. At that point, marking LTS and other RTVs will be trivial.
