### ISSUE TITLE
Content mismatch: Missing content in AMP page vs. canonical

### ISSUE THREAD

**Issue by php4fan** [ampproject/amphtml#26860]
Half of the times I visit an AMP page (not because I choose to but because Google offers it to me in search results) it's so broken that it's unusable.
Often the whole content of the page is missing.
Sometimes it's not completely obvious that it's an issue in amp (and as a user, you barely notice you're seeing an AMPed page of you look carefully, and I bet most users don't even know what amp is) and the first impression as a user is that the page is crap, when in reality it turns out the original page works perfectly fine and is mobile friendly and fast and wouldn't need amp on the first place.
so you are hurting publishers' reputation by offering a broken version of a page to unknowing users.

Because of this, as a user, when I'm presented with an amp page, I always go to the original because I know I can't trust the amp crap to resemble what the publisher meant to publish.

Here's just one example:
https://www.google.com/amp/www.rainews.it/dl/rainews/media/amp/ContentItem-ff31c59c-cc4d-45b0-ae24-dc538d80af5d.html

http://www.rainews.it/dl/rainews/media/accadde-oggi-80-anni-fa-nasceva-fabrizio-de-andre-in-sala-il-concerto-ritrovato-di-Faber-e-PFM-ff31c59c-cc4d-45b0-ae24-dc538d80af5d.html

**Comment by mdmower** [comment]
> so you are hurting publishers' reputation by offering a broken version of a page to unknowing users.

Just a little clarification: Publishers write AMP pages. The quality of the AMP pages you encounter are a product of the effort invested in writing those AMP pages, and the results can be fantastic for the end user: fast, dynamic, and easy to use. I suggest you contact the publisher to let them know their AMP pages are not displaying correctly, just like to might if their non-AMP pages were misbehaving.

**Comment by choumx** [comment]
On the Google side, these "content mismatch" issues used to be automated but was disabled some time ago. I believe there's still manual review on a case-by-case basis: https://support.google.com/webmasters/answer/9044175

> The content of the AMP version and its canonical web page should be essentially the same. The text need not be identical, but the topic should be the same, and users should be able to accomplish the same tasks on both the AMP and the canonical page.

Here are AMP publishing guidelines: https://support.google.com/webmasters/answer/6340290

> Users must be able to experience the same content and complete the same actions on AMP pages as on the corresponding canonical pages, where possible.

**Comment by php4fan** [comment]
> Just a little clarification: Publishers write AMP pages

Whops, my bad, sorry. I thought they just "signed up" or "enabled" their pages for AMP and that Google would do everything. I didn't imagine so many publishers (e.g. digital news outlets) could be so careless to publish pages that don't even work at the most basic level, I mean if they are writing the AMP version themselves I thought they would at least check them. I'm pretty sure they use some automated tools (probably third-party shitty ones).

> I believe there's still manual review on a case-by-case basis:

So shouldn't there be a way to report an amb page to Google when it violates those guidelines? I would expect to find this option in the top amp bar, or at least for it to be easy to find (googling "report amp pages" doesn't help as all the results are about Google Analytics "reports")

Incompetent publishers who publish crappy AMP versions of their content should have their AMP page disabled by Google or, at least, it shouldn't come up as the first search result when the content isn't even accessible.

**Comment by choumx** [comment]
> So shouldn't there be a way to report an AMP page to Google when it violates those guidelines?

I personally think this would be cool though it's outside my wheelhouse.

**Comment by php4fan** [comment]
> I personally think this would be cool

If there's no way to report, what _do_ they review? Every single page??
