### ISSUE TITLE
Sauce proxy is not closed on disconnect error

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#26883]
When `gulp integration` fails with the infamous `Disconnectedreconnect failed before timeout of 12000ms (ping timeout)`, the task never properly winds down. Most notably, it never stops the Sauce Connect Proxy or closes the open Sauce tunnel. The effect of this is visible by monitoring the "Active Tunnels" from the Sauce Labs control panel, where you can see currently active tunnels for Travis builds that failed due to disconnect long ago. 

This is a result of using `timeExecOrDie`, which exits the node process before the `stop_sauce_connect.sh` script is executed (see `amphtml/build-system/pr-check/remote-tests.js`).

The impact of the dangling tunnels on tests is unclear.

/cc @ampproject/wg-infra

**Comment by rsimha** [comment]
Dangling tunnels as a result of test failures should be cleaned up by the `after_script` section in `.travis.yml`. 

https://github.com/ampproject/amphtml/blob/1b2413852b83d7b4ce7fd403df9fcf54321fea94/.travis.yml#L83-L84

**Comment by rcebulko** [comment]
I would gamble that leaving the sessions open/hanging around might also leave dangling sessions, impacting the concurrency issue

**Comment by rcebulko** [comment]
Nevermind; looks like it's already in the `after_script` block. I read the comment above mine as "Dangling tunnels...should be cleaned up (but aren't)". Closing this.
