### ISSUE TITLE
Error: "Failed to parse \"amp-subscriptions\" JSON: SyntaxError

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#26892]
Error: "Failed to parse \"amp-subscriptions\" JSON: SyntaxError: Unexpected token , in JSON at position 938"

Noticed the error with the release 2002200031230. 

go/ampe/CKC7u-T2oNLHXQ

**Comment by jpettitt** [comment]
This is a publisher content error. We're reaching out to the publisher to request they fix it.

**Comment by jridgewell** [comment]
Relevant lines: https://github.com/ampproject/amphtml/blob/6ff62464aa1076958028c35ee5c1557e7a37af24/extensions/amp-subscriptions/0.1/amp-subscriptions.js#L178-L181

This should be throwing a `user().createError()` instead, so we don't get it in our dev logs.

**Comment by jridgewell** [comment]
BTW, calling `reject` with a non-error is super nasty. That's probably the reason the error messages are a mess.
