### ISSUE TITLE
Error: null is not an object (evaluating 'b.appendChild')

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#26893]
Error: null is not an object (evaluating 'b.appendChild')
at appendChild (https://raw.githubusercontent.com/ampproject/amphtml/2002200031230/extensions/amp-access-poool/0.1/poool-impl.js:206)

go/ampe/CPmml5_X4N_duQE

**Comment by jpettitt** [comment]
cc/ @dackmin

**Comment by jpettitt** [comment]
Error is here https://github.com/ampproject/amphtml/blob/master/extensions/amp-access-poool/0.1/poool-impl.js#L206 We are seeing this accross multiple domains

**Comment by dackmin** [comment]
I will make sure the main container is available before trying call `appendChild` on it, but do you have any repro code so I can investigate the reasons?
@jpettitt are those domains using `amp-shadow-doc` by any chance?
