### ISSUE TITLE
WARNING  in G console  : "The script tag contains invalid JSON that cannot be parsed"

### ISSUE THREAD

**Issue by abhiz10** [ampproject/amphtml#26905]
Hi AMP Team,

We are getting a WARNING  in  G console: "The script tag contains invalid JSON that cannot be parsed"

Ref: https://nature.visualstories.com/paper-recycling-process

<amp-analytics type="googleanalytics" data-credentials="include"><script type="application/json">
{"vars":{"account":"UA-158509309-22","config":{"UA-158509309-22":{"groups":"default"}}},"triggers":{"storyPageVisible":{"on":"story-page-visible","request":"pageview"},"storyProgress":{"on":"story-page-visible","request":"event","enabled":"true","vars":{"event_name":"custom","event_action":"story_progress","event_category":"${title}","event_label":"${storyPageId}","send_to":["UA-158509309-22"]}},"storyEnd":{"on":"story-last-page-visible","request":"event","enabled":"true","vars":{"event_name":"custom","event_action":"story_complete","event_category":"${title}","send_to":["UA-158509309-22"]}}}}
</script></amp-analytics>

But when we validate the above JSON there is no such warning or error reflecting.

**Comment by mrcferri** [comment]
We're experiencing the same exact problem. Google Search console returns this warning:

        "The script tag contains invalid JSON that cannot be parsed"

but validation is successful and no warnings or errors are returned.  Google console highlights all amp tags containing JSON like

```
    <amp-geo layout="nodisplay">
           <script type="application/json">
           {
               "ISOCountryGroups": {
                     "eea": [ "at", "be", "bg", "cy", "cz", "de", "dk", "ee", "es", "fi", "fr",
                          "gb", "gr", "hr", "hu", "ie", "is", "it", "li", "lt", "lu", "lv", "mt", "nl",
                            "no", "pl", "pt", "ro", "se", "si", "sk"]
                  }
            }
           </script>
</amp-geo>
```
The warnings  showed up just a couple of days ago, even though the pages were the same as before, no changes, Maybe a bug in some new version of the validator used by Google console?

**Comment by itsmsc** [comment]
Exact the same problem here. 13.000 pages with warnings since yesterday.

**Comment by webdevmike** [comment]
This same issue is happening at https://amp.magnetjewelrystore.com/allssgend.html and dozens of other AMP pages on the same domain.

**Comment by jridgewell** [comment]
Note, this is just a warning.

/cc @ampproject/wg-caching

**Comment by itsmsc** [comment]
Removing all newlines in the the  application/json - Tags solves the problem for me. 
see https://support.google.com/webmasters/thread/29367056?hl=en -> https://twitter.com/westonruter/status/1230920547132792832?s=19

**Comment by abhiz10** [comment]
Now, it's not showing any WARNING ....Thanks

**Comment by Gregable** [comment]
This is being reported as a warning in search console and has no impact on your appearance in search. The issue has already been resolved, but your pages will need to be re-indexed before the warning will disappear.
