### ISSUE TITLE
AMP Lightbox Gallery slider swipe get stuck

### ISSUE THREAD

**Issue by photocoder** [ampproject/amphtml#26941]
## What's the issue?

If I open the gallery and swipe left to next image, after a few swipes, it gets stuck ... I click to next button and it loading, but not by swipe. Swipe works only after waiting few seconds.

Here is the video of situation.:
https://yadi.sk/i/zw29x3k-5-KBKw

Tested page:  https://dimasfrolov.com/portfolio/wedding/

So, by the click to "next" button it is going very good, but not by swiping.

## What browsers are affected?
iOS Chrome 

## Which AMP version is affected?
Powered by AMP ⚡ HTML – Version 2002200031230 https://dimasfrolov.com/

**Comment by wassgha** [comment]
@alanorozco I think we noticed this during the bug bash but never got to fix it

**Comment by photocoder** [comment]
Hope it will be fixed... Because if you swipe fast it get stuck. 
But with small delay, it works.
Anyway, for clicking "next button" is working very well and without delay or stucking.
