### ISSUE TITLE
Support header tag for amp-accordion section headers.

### ISSUE THREAD

**Issue by powdercloud** [ampproject/amphtml#2695]
I had forgotten to add this in the spec file, so this issue tracks when the fix is live.
We will then want to update the amp-accordion documentation to reflect it.

**Comment by rudygalfi** [comment]
Do you have an ETA?

**Comment by powdercloud** [comment]
Unless we do extra work to make it happen faster, it'll get there soon after indexing etc. gets updated, which should be ~2 weeks. Hope that's fine.

**Comment by powdercloud** [comment]
This is done and live everywhere.
