### ISSUE TITLE
Resources in <details> element do not load upon opening

### ISSUE THREAD

**Issue by westonruter** [ampproject/amphtml#26952]
## What's the issue?

Initially [reported](https://wordpress.org/support/topic/media-doesnt-show-as-long-as-under-ab-accordion-when-amp-standart-mode/#post-12475441) on the [Atomic Blocks](https://atomicblocks.com/) support forum (for this WordPress plugin). An issue with AMP was uncovered with the Accordion block, which [uses the HTML5 `details` element](https://github.com/studiopress/atomic-blocks/blob/b11d0b6176367861ce1be36a132fd19b19d9b87f/src/blocks/block-accordion/components/save.js#L23-L32) as opposed to `amp-accordion`.

When an image, iframe, or other external resource is located inside of `details` element that is not initially `open`, the elements will fail to load when the `details` element is `open`-ed.

## How do we reproduce the issue?

Given this markup:

```html
  <details>
    <summary>Show</summary>
    <p>
      Image:
      <amp-img src="https://ps.w.org/amp/assets/banner-1544x500.png?rev=1987390" width="1544" height="500" layout="responsive"></amp-img>
    </p>
    <p>
      Iframe:
      <amp-iframe src="https://example.com/" layout="fixed-height" height="300">
        <span placeholder>Loading example.com...</span>
      </amp-iframe>
    </p>
  </details>
```

Clicking “show” reveals the elements without them being loaded:

> ![image](https://user-images.githubusercontent.com/134745/75196816-d7868780-57b0-11ea-8610-9f61767e6a60.png)

Contrast with the same code above where the `open` attribute is initially present on the `details` element:

> ![image](https://user-images.githubusercontent.com/134745/75196866-f258fc00-57b0-11ea-9282-94e411e5ab6c.png)

## What browsers are affected?

Tested in Chrome, presumably all browsers affected.

## Which AMP version is affected?

Always broken, AFAIK. Support for `details` was added a couple years ago (#18440) but this was not paired with an update to the resource manager to handle content revealed in the `details`.

**Comment by westonruter** [comment]
cc @jridgewell

**Comment by jridgewell** [comment]
Yup, this is a runtime issue. We're not able to detect that the element is now visible because it doesn't trigger a `hidden` attribute mutation.

We're exploring using an IntersectionObserver as a replacement for quite a few things in Resources, and this would be naturally fixed by it. /cc @choumx

**Comment by westonruter** [comment]
Just to note that it seems this is being addressed with Bento. The Bento `amp-iframe` loads successfully when the `details` is expanded. See [AMP Playground](https://playground.amp.dev/#share=PCFET0NUWVBFIGh0bWw+CjxodG1sIOKaoT4KICA8aGVhZD4KICAgIDxtZXRhIGNoYXJzZXQ9InV0Zi04IiAvPgogICAgPHRpdGxlPk15IEFNUCBQYWdlPC90aXRsZT4KICAgIDxsaW5rIHJlbD0iY2Fub25pY2FsIiBocmVmPSJzZWxmLmh0bWwiIC8+CiAgICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoIiAvPgogICAgPHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1vei1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDstbXMtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7YW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGh9QC13ZWJraXQta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtbW96LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1zLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW8ta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUBrZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19PC9zdHlsZT48bm9zY3JpcHQ+PHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOm5vbmU7LW1vei1hbmltYXRpb246bm9uZTstbXMtYW5pbWF0aW9uOm5vbmU7YW5pbWF0aW9uOm5vbmV9PC9zdHlsZT48L25vc2NyaXB0PgogICAgPHNjcmlwdCBhc3luYyBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwLmpzIj48L3NjcmlwdD4KICAgIDxzY3JpcHQgYXN5bmMgY3VzdG9tLWVsZW1lbnQ9ImFtcC1pZnJhbWUiIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAvYW1wLWlmcmFtZS0xLjAuanMiPjwvc2NyaXB0PgogICAgPHNjcmlwdD4KICAgICAgKHNlbGYuQU1QID0gc2VsZi5BTVAgfHwgW10pLnB1c2goZnVuY3Rpb24gKEFNUCkgewogICAgICAgIEFNUC50b2dnbGVFeHBlcmltZW50KCdiZW50bycsIHRydWUpOwogICAgICB9KTsKICAgIDwvc2NyaXB0PgogICAgPHN0eWxlIGFtcC1jdXN0b20+CiAgICAgIGgxIHsKICAgICAgICBtYXJnaW46IDFyZW07CiAgICAgIH0KICAgIDwvc3R5bGU+CiAgPC9oZWFkPgogIDxib2R5PgogIDxkZXRhaWxzPgogICAgPHN1bW1hcnk+U2hvdzwvc3VtbWFyeT4KICAgIDxwPgogICAgICBJZnJhbWU6CiAgICAgIDxhbXAtaWZyYW1lIHNyYz0iaHR0cHM6Ly9leGFtcGxlLmNvbS8iIGxheW91dD0iZml4ZWQtaGVpZ2h0IiBoZWlnaHQ9IjMwMCI+CiAgICAgICAgPHNwYW4gcGxhY2Vob2xkZXI+TG9hZGluZyBleGFtcGxlLmNvbS4uLjwvc3Bhbj4KICAgICAgPC9hbXAtaWZyYW1lPgogICAgPC9wPgogIDwvZGV0YWlscz4KICA8L2JvZHk+CjwvaHRtbD4K) with `amp-iframe` v1.0.

Compare with non-Bento `amp-iframe` v0.1 on [AMP Playground](https://playground.amp.dev/#share=PCFET0NUWVBFIGh0bWw+CjxodG1sIOKaoT4KICA8aGVhZD4KICAgIDxtZXRhIGNoYXJzZXQ9InV0Zi04IiAvPgogICAgPHRpdGxlPk15IEFNUCBQYWdlPC90aXRsZT4KICAgIDxsaW5rIHJlbD0iY2Fub25pY2FsIiBocmVmPSJzZWxmLmh0bWwiIC8+CiAgICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoIiAvPgogICAgPHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1vei1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDstbXMtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7YW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGh9QC13ZWJraXQta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtbW96LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1zLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW8ta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUBrZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19PC9zdHlsZT48bm9zY3JpcHQ+PHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOm5vbmU7LW1vei1hbmltYXRpb246bm9uZTstbXMtYW5pbWF0aW9uOm5vbmU7YW5pbWF0aW9uOm5vbmV9PC9zdHlsZT48L25vc2NyaXB0PgogICAgPHNjcmlwdCBhc3luYyBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwLmpzIj48L3NjcmlwdD4KICAgIDxzY3JpcHQgYXN5bmMgY3VzdG9tLWVsZW1lbnQ9ImFtcC1pZnJhbWUiIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAvYW1wLWlmcmFtZS0wLjEuanMiPjwvc2NyaXB0PgogICAgPHN0eWxlIGFtcC1jdXN0b20+CiAgICAgIGgxIHsKICAgICAgICBtYXJnaW46IDFyZW07CiAgICAgIH0KICAgIDwvc3R5bGU+CiAgPC9oZWFkPgogIDxib2R5PgogIDxkZXRhaWxzPgogICAgPHN1bW1hcnk+U2hvdzwvc3VtbWFyeT4KICAgIDxwPgogICAgICBJZnJhbWU6CiAgICAgIDxhbXAtaWZyYW1lIHNyYz0iaHR0cHM6Ly9leGFtcGxlLmNvbS8iIGxheW91dD0iZml4ZWQtaGVpZ2h0IiBoZWlnaHQ9IjMwMCI+CiAgICAgICAgPHNwYW4gcGxhY2Vob2xkZXI+TG9hZGluZyBleGFtcGxlLmNvbS4uLjwvc3Bhbj4KICAgICAgPC9hbXAtaWZyYW1lPgogICAgPC9wPgogIDwvZGV0YWlscz4KICA8L2JvZHk+CjwvaHRtbD4K).

**Comment by westonruter** [comment]
This issue appears to be fixed.
