### ISSUE TITLE
Intent-to-Deprecate: amp-sidebar in amp-story

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#26958]
## Summary and Motivation

The `<amp-sidebar>` feature in stories has not achieved scale, but is creating an inconsistent user experience.  It has also been brought up that the feature is an anomaly, as it's not one that's generally supported in story platforms.  This has been demonstrated by the low adoption since launch, as compared to other features.

## Alternative implementation suggestions for publishers

Rather than using links within a sidebar, publishers can look to these following suggestions:

1.  Publishers can use `<a>` tags directly within their [`<amp-story-grid-layer>`](https://amp.dev/documentation/components/amp-story/?format=stories#links-in-amp-story-grid-layer) or [`<amp-story-cta-layer>`](https://amp.dev/documentation/components/amp-story-cta-layer/) tags
1.  Publishers may load additional context in [`<amp-story-page-attachment>`](https://amp.dev/documentation/components/amp-story-page-attachment/)
1.  Publishers can use [`<amp-story-player>`](https://github.com/ampproject/amphtml/blob/master/spec/amp-story-player.md) to embed their story in another page, containing custom UI to present this data. See demo of this at https://codepen.io/mszylkowski/pen/dyOLKgE

## Additional Context

We would like to start triggering warnings to inform publishers of the deprecation on a wider scale.  After the warning period, we will deprecate the feature by removing its documentation and making its markup a no-op (to prevent invalidating documents).

In the future, we can file a separate I2R to invalidate the `<amp-sidebar>` markup within `<amp-story>` at a time where its impact is minimal.  Before doing so, it may be a good idea to update the deprecation notice with a concrete removal date.

**Comment by Gregable** [comment]
Do you have data you can share on the low adoption rate?

**Comment by newmuis** [comment]
99% of stories using `<amp-sidebar>` are published by only 15 publishers.  Those stories amount to less than 0.3% of all stories.

**Comment by cathyxz** [comment]
That means https://github.com/ampproject/amphtml/issues/24827 will no longer be relevant, and this can unblock moving amp-sidebar's mask from body to inside the component. /cc @ampproject/wg-ui-and-a11y

**Comment by Beethoven** [comment]
I think it should be optional.
Sidebar is essential to navigate on a Story using branching and to put Social links, terms etc.
Amp Story is a web page in essencial and needs a MENU.

Example:
https://stapp.app/ferrari

**Comment by newmuis** [comment]
AMP stories are webpages, but they're also stories, and the question becomes: which one takes precedence?

To build out the feature set that users expect when they engage with story content, generally the story definition takes precedence.

> I think it should be optional.

This is the core of the problem.  Optional from whose perspective?

- If we want to make this optional for publishers (i.e. a publisher can choose to include or not include a sidebar), this is the current state of affairs.  It creates the problems described above.
- If we want to make this optional for consumption platforms (i.e. a platform can choose whether or not it wishes to display a story's sidebar), then this creates inconsistent expectations.  Publishers might publish their stories to their own sites and be completely unaware that other sites are effectively changing the contents of their stories.  If the angle here is to make this more like traditional web content, that's not how websites are generally treated, either.

**Comment by Kevin-Ellen** [comment]
My 2 pence for what it is worth.

In my opinion a 'menu' is slightly redundant in this context, as it is hard to directly link to a specific page from outside sources (you are forcing users to navigate through the story) and the URLs do not change; given that a Story is not a website, but a single page application. 

A Story is a single page, which feels like a website; and only till we start supporting individual URLs per page, would it make sense.

As for social media links and engagement, we should use attachment in my opinion.

What about being allowed to use page attachment from different positions? So not just bottom of the screen, but also either top, right or left?

**Comment by Beethoven** [comment]
Page attachment is a per page component and cant't serve as MENU.
Page attachment is a "SWIPE UP TO SEE MORE" component not a MENU.
Amp Story is a website that uses a stories UX.
We need to thing in users as the creators of the amp stories sites, not only as the consumers who see.
We need to ask the consumer if they want a menu on his stories site or not.
For me Publisher can be anyone.
We have more than 4m stories sites with sidebar and we can help with statistics.

**Comment by Kevin-Ellen** [comment]
> Page attachment is a per page component and cant't serve as MENU.

Fair enough, and affectively it should not be used as a menu indeed. I was more hinting at having worthwhile sharing opportunities and credits in attachments.

> Page attachment is a "SWIPE UP TO SEE MORE" component not a MENU.

Correct.

> Amp Story is a website that uses a stories UX.

I continue to disagree on this point.

> We need to ask the consumer if they want a menu on his stories site or not.

Big fan of this, as we should give people options to use them or not. Especially given that `amp-sidebar` is already a worthwhile component.

> We have more than 4m stories sites with sidebar and we can help with statistics.

I am sure @newmuis would be interested, given he posted some numbers earlier and the more data the team has, the better decision they can make. This kind of data can help the group to make a better decision.

@newmuis - while `amp-sidebar` is not fully taken on by many people when it comes to AMP Stories, what are the benefits of removing the support for it? The component will remain in AMP; so what is the point?

**Comment by Beethoven** [comment]
My point:
Amp Story is a website that uses a stories UX.

Think as Sales department:
Everyone needs a website on top of Serps. 
Amp Stories is a website that engage and in our analytics almost zero bounce (3% bounce).

The user don't need another platform to share stories, they need a site on top of serps that convert. And a site need a menu.

Our customer can't understand what AMP Stories is and why to build it.
But a Site on top of SERPs all of them want.

**Comment by newmuis** [comment]
> Amp Story is a website that uses a stories UX.

I also disagree on this point.

AMP stories are stories that live on the open web.  They're not intended to be a replacement for a website or any specific piece of website functionality.  The intent is to make stories a first class citizen of the web.  Put another way, we're bringing stories to the web, not bringing the web to stories.

> They need a site on top of serps that convert. And a site needs a menu.
Our customer can't understand what AMP Stories is and why to build it.
But a Site on top of SERPs all of them want.

Stories are a medium, not a ranking factor.  We wouldn't add a sidebar menu to video formats to help users convert, because videos are an understood medium that have an expected set of functionalities (play/pause, seek, mute/unmute, etc... but not sidebar).

My vote here is actually to handle this the same way as video: if you would like to have a video with a sidebar menu, you create a new page that contains both the video player and the sidebar menu.  This is analogous to my third "alternative implementation" above: create a new page that contains both the story player and the sidebar menu.

> @newmuis - while amp-sidebar is not fully taken on by many people when it comes to AMP Stories, what are the benefits of removing the support for it? The component will remain in AMP; so what is the point?

It will remain in AMP, but not valid for stories.  I don't think of it as a "removal"; it's still possible to have a sidebar, it would just need to exist at the platform layer.  One concrete advantage is a benefit to the user experience when embedded in consumption platforms (i.e. avoiding having the platform's menu and also the story's menu).

**Comment by Beethoven** [comment]
We want to make amp stories universally accessible to empower voices - and having a sidebar to navigate helps in its accessibility because It can be a substitution of a site.
Amp Stories is a perfect UX for a site or landpage. Like a  "don't make me think site".
 
Since AMP Stories is  html, css, js are just web pages. 
Like Flavio Palandri Antonelli write on his post:
"Importantly, AMP Stories are just web pages. They have a URL on your web server, they are linkable, and they can link out to other web pages."
From amp.dev Blog
 
We need to ask the users if they want a sidebar to navigate on his stories or not.
For example Sidebar is perfect for a Summary.
 
I know amp stories are not a ranking factor. But engagement, time on site and in terms bounce is. And we are seeing Amp Stories with all of that.
 
When saying "when embedded in consumption platforms" is that Google can show a sequence of Amp stories of various publishers, like we saw in Visual Stories results?

**Comment by newmuis** [comment]
> having a sidebar to navigate helps in its accessibility because It can be a substitution of a site.
Amp Stories is a perfect UX for a site or landpage.

This is not the intended use case of the format.  I think it's okay for people to try to be creative and push the boundaries, but we should avoid making format-level decisions with ecosystem-wide implications for something that is not the primary use case of the format.

> When saying "when embedded in consumption platforms" is that Google can show a sequence of Amp stories of various publishers, like we saw in Visual Stories results?

That is one experience, but you can imagine such an experience on any consumption platform.  For example, imagine that a consumption platform like Twitter, Instagram, Google, etc wished to show AMP stories in their app, alongside their existing content.  Wouldn't it be weird to allow sidebars in that context?  The UX would conflict with platform-level controls (e.g. they might have a sidebar of their own).  As such, it would be a blocker for adoption from such platforms.

Hence the recommendation: let publishers have full control to create sidebars on their own platforms, that makes sense.  Publishers of course can still include links as part of the story content itself, but sidebars, as a platform-level feature, should live with the platform.

**Comment by Beethoven** [comment]
I understand now. And now I can vote to deprecate it too.
We will love to see amp stories on platforms, and the efforts to make it accessible.
We just need an example to use sidebar with amp-story-player accessing pages. It is possible?
And tks for the replies.

**Comment by newmuis** [comment]
Agreed, it would be great to have an example of this; I can own writing this up.

**Comment by Beethoven** [comment]
We can help with examples too. (if we know how to do it)

**Comment by AutadeJS** [comment]
Agree with @newmuis that bookend and sidebar must be deprecated. The endless stories experience that the amp-story-player promises is much more important from UX pov than a website wanting to have a menu or related links in stories.

In our own proprietary implementation of an endless stories UX we had to get rid of the bookend: https://visualstories.com/?app=pwa

We should make it easier for consumption platforms if we wish for AMP Stories to be adopted quickly by the big social media platforms, the likes of Fb, Twitter, etc. AMP Stories can become a great tool for websites to reach the masses through these big platforms.

We from VisualStories.com vote to deprecate both bookend and sidebar. We'll remove them from our 50k+ stories soon.

**Comment by Enriqe** [comment]
Hi @ampproject/wg-approvers,

We'd like to move forward with the deprecation / removal of the bookend. I think we have all we need to move forward with it (original comment has been updated. Could you PTAL and let us know what is missing to get the three approvals? 

/cc @mszylkowski

**Comment by dkolba** [comment]
I created a website for a podcast that is amp-story only (perfect story use case BTW), now the menu that leads to stuff like imprint and data privacy etc. is deprecated. What gives 🤷‍♂️  ?
German law requires, that the imprint is always max two clicks/taps away - amp-sidebar solved this problem elegantly.

**Comment by mszylkowski** [comment]
@dkolba as some of the previous comments on this thread, sidebars can still be implemented on your website using the [amp-story-player](https://github.com/ampproject/amphtml/blob/master/spec/amp-story-player.md) as seen [in this Codepen](https://codepen.io/mszylkowski/pen/dyOLKgE). There are plenty of alternatives to sidebars that we've created over the years for these purposes, like [amp-consent](https://amp.dev/documentation/components/amp-consent/?format=stories), [page-attachment](https://amp.dev/documentation/components/amp-story-page-attachment/?format=stories), [links](https://amp.dev/documentation/components/amp-story/?format=stories#customizing-tooltip-for-links-or-interactive-components); and they can link to your imprint or other important information.

Our thinking behind this deprecation is not to get rid of sidebars on story experiences, but to change the responsibility from the story format to the website support (eg: through the amp-story-player), which allows websites to implement their own sidebars, dialogs, snack bars, or whatever UI best fits the purpose, using a style that reflects the design of your website better.
