### ISSUE TITLE
Error in amp-img tag.

### ISSUE THREAD

**Issue by VsheeKhan** [ampproject/amphtml#26979]
Dear Sir / Mam,
I have encountered an issue with the amp-img tag. As you know when we use amp-img tag in our HTML code it ads some other code as from amp side. Today I found that a tag ` i-amphtml-sizer ` is also there and it doesn't have any content but it is taking 91.125% padding from the top.
![cssCode](https://user-images.githubusercontent.com/8350583/75351343-08101380-58ce-11ea-9c16-fef41275fead.JPG)
![htmlcode](https://user-images.githubusercontent.com/8350583/75351350-0a726d80-58ce-11ea-9fb3-c70cc3fad5c3.JPG)
![imgcode](https://user-images.githubusercontent.com/8350583/75351352-0b0b0400-58ce-11ea-9e33-379fed7a6d50.JPG)

**Comment by jridgewell** [comment]
The `i-amphtml-sizer` element is how responsive sizing is implemented. It preserves the aspect ratio of the image.
