### ISSUE TITLE
auto-advance-after does not work with audio files

### ISSUE THREAD

**Issue by krschacht** [ampproject/amphtml#26997]
##  What's the issue?

amp-stories support auto-advance-after. This attribute is supposed to allow "An ID of an HTMLMediaElement." It works if the ID points to a video but it does not work if the ID points to an amp-audio element.

## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. Create a simple story with two pages
2. Try putting a video element on one page, give it an ID, and specify this ID in the auto-advance-after. Confirm that it works.
3. Switch out this video element for an amp-audio element, give it the same ID, now auto-advance-after fails. AMP Story does auto-play the audio but the progress bar does not proceed as the audio plays and the slide does not auto-advance after the audio is complete.

## What browsers are affected?

I've only tested in Chrome 79.0.3945.130

## Which AMP version is affected?

Version 2002192257490, I did not test in previous versions.

**Comment by gmajoulet** [comment]
Fixed by https://github.com/ampproject/amphtml/issues/28511
