### ISSUE TITLE
Allow viewers/players to subscribe to Story state updates.

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#26994]
https://github.com/ampproject/amphtml/pull/26285 introduced a viewer <> runtime messaging API to get/set Story internal states, such as `CURRENT_PAGE_ID` or `MUTED_STATE`.

Additionally, we should provide a way to subscribe to these state updates, for viewers/players building features that need to be kept in sync with the story's states.

cc @ampproject/wg-stories

**Comment by gmajoulet** [comment]
#### Existing `getDocumentState` API

Viewers send a `getDocumentState` message with a specific state as a parameter. The runtime responds instantly with the corresponding value.

```
const viewer = Services.viewerForDoc(this.element);

viewer.onMessageRespond('getDocumentState', data => {
  const {state} = data;

  // Pseudo code.
  return Promise.resolve({state, value: storeService.get(state)});
});
```

#### `onDocumentState` option A

Viewers send a `onDocumentState` message with a specific state as a parameter. The runtime returns a pending promise, waits for a state update, and finally returns the new state.
Viewers would have to send a new `onDocumentState` message after the first one resolved.

```
const viewer = Services.viewerForDoc(this.element);

viewer.onMessage('onDocumentState', data => {
  const {state} = data;

  // Pseudo code. The runtime will respond only once, when the state changes.
  return new Promise(resolve => {
    storeService.subscribe(state, value => {
      resolve({state, value});
    });
  });
});
```
##### Pros
- API is consistent with `get/setDocumentState`
- Easier to implement: only one message to send, vs one to send + one to receive

##### Cons
- Really oldschool long polling pattern that has its drawbacks (risk of missing a state change if subscribing for the next one takes too much time)

#### `onDocumentState` option B
Viewers send a `onDocumentState` message with a specific state as a parameter. The runtime does not respond.
On state update, the runtime sends a new `documentStateUpdate` message, with both the state and the new value as parameters.
```
const viewer = Services.viewerForDoc(this.element);

viewer.onMessage('onDocumentState', data => {
  const {state} = data;

  // Pseudo code. The runtime does not respond, but send a message for each
  // state update.
  storeService.subscribe(state, value => {
    viewer.sendMessage('documentStateUpdate', {state, value});
  });
});
```

##### Pros
- No risk of race conditions

##### Cons
- API is NOT consistent with `get/setDocumentState`
- Needs to declare two viewer messaging events
- Usual JavaScript patterns allow registering a callback. Here, there is no callback, but another event is fired instead. This is how other viewer events work, though




cc @Enriqe @newmuis wdyt?

**Comment by newmuis** [comment]
I vote B; doesn't seem like it's more work, per se (correct me if I'm wrong here).  The inconsistency of the API doesn't seem actually that odd to me.

**Comment by Enriqe** [comment]
I also vote B. I'm scared of race conditions with option A. B makes the code more predictable and easier to debug.

**Comment by gmajoulet** [comment]
Thanks, I marked the option B as accepted. :)
