### ISSUE TITLE
TBD: A validator rule that would require not one but several JS files

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#2701]
We need to be careful with this because some of these errors are already likely and it's not always a critical thing. However, there are some not-very-visible dependencies between components that we could address by showing errors (or warnings) in validator when dependent scripts are missing.

The two examples I know of right now are `amp-user-notification` and `amp-access` both depend on `amp-analytics`. These dependencies are documented, but, of course, forgetting to include them is a very easy error to make. In these cases we could require documents with `amp-user-notification` to have both `amp-user-notification.js` and `amp-analytics.js`.

**Comment by Gregable** [comment]
> These dependencies are documented, but, of course, forgetting to include them is a very easy error to make.

I'm looking at [amp-user-notification](https://github.com/ampproject/amphtml/blob/master/extensions/amp-user-notification/amp-user-notification.md) and [amp-access](https://github.com/ampproject/amphtml/blob/master/extensions/amp-access/amp-access.md) and don't see any text noting that these depend on `amp-analytics.js`. Am I understanding the request correctly that you feel they both depend on `amp-analytics.js`?

**Comment by dvoytenko** [comment]
Oops. We recently stripped `<script>` declarations from the docs and these dependencies went by the way of that. Not sure why we did that. Will correct.

**Comment by dvoytenko** [comment]
@Gregable Adding docs on extra dependencies in https://github.com/ampproject/amphtml/pull/2726

**Comment by Gregable** [comment]
It also looks like these should be updated:
https://ampbyexample.com/components/amp-access/
https://ampbyexample.com/components/amp-user-notification/

**Comment by dvoytenko** [comment]
Yep. VEry good point. Will file separately. /cc @sebastianbenz @andreban

**Comment by Gregable** [comment]
This validator change will be live in the chrome dev console messages within an hour or so.
