### ISSUE TITLE
I2I: Consolidate VideoManager/VideoEntry hierarchy

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#27010]
## Motivation

The current shared `VideoManager` interfaces are problematic since they keep `AmpVideoComponent`s flat:

- When using playback methods exposed from the `VideoInterface`, users need to juggle `BaseElement` and `VideoInterface` types.

- When reading video-specific state that's interpreted by the service, users need to ask the `manager` to search for the entry internally and return a specific property.

## Goal

Use a clear hierarchy instead that exposes the currently internal `VideoEntry`, that can be played back as a `VideoInterface` component. This exposes its internally interpreted state directly.

## Simplify `VideoManager`

Rather than having `VideoManager` expose:

- **`.isMuted`**`(video) => .getEntry(video)`**`.isMuted()`**
- **`.isRollingAd`**`(video) => .getEntry(video)`**`.isRollingAd()`**
- **`.userInteracted`**`(video) => .getEntry(video)`**`.userInteracted()`**
- **`.getPlayingState`**`(video) => .getEntry(video)`**`.getPlayingState()`**
- ...etc

`VideoManager` only exposes:

- **`.getEntry(componentOrElement):`**`VideoEntry`

After obtaining the `VideoEntry`, users can treat that as an independent component and in most cases forget about the `VideoManager` service.

## Expose `VideoEntry`

Users outside the `VideoManager` can consume `VideoEntry` objects.

Then, expose its wrapped element to use their interface directly, but cast it separately as a public `.playback` property to use as a `VideoInterface` object:

```js
class VideoEntry {
  constructor(component) {
    this.playback = /** @type {!VideoInterface} */ component;
    this.component = /** @type {!AMP.BaseElement} */ component;
    this.element = component.element; // maybe, for ergonomics
  }
  // ...
}
```

Then users can access the wanted APIs directly like `entry.playback.play()` or `entry.component.element`, without casting.

Playing state as interpreted on the common layer is exposed via the `VideoEntry` wrapper: 

- `get isMuted(): boolean `
- `get isRollingAd(): boolean`
- `get didUserInteract(): boolean`
- ~~`get playingState(): !PlayingStates`~~
  Remove `PlayingStates` altogether. This is a rarely used abstraction for which the consumers only care about two separate states that we now expose:
- `get isPlaying(): boolean`
- `get isPlayingManual(): boolean` (same as `isPlaying && didUserInteract`, could remove)

## Allow bookkeeping

When top-level handlers, like `VideoDocking` or `RotateToFullscreenManager` register a video component, they can keep the entry instead:

```diff
  /**
-  * @param {!VideoInterface|!AMP.BaseElement} video
+  * @param {!VideoEntry} video
   */
  register(video) {
    this.video_ = video;
  }
  useState() {
    // These would do a linear search (!) each. But if we receive an already
    // registered VideoEntry, we don't have to search for it each time, or
    // use the manager at all.
-   const isMuted = this.videoManager_.isMuted(this.video_);
-   const isPlaying =
-     this.videoManager_.getPlayingState(this.video_) !== PlayingStates.PAUSED;
+   const {isMuted, isPlaying} = this.video_;
  }
  useBothInterfaces() {
-   const playback = /** @type {!VideoInterface} **/ (this.video_);
-   const component = /** @type {!AMP.BaseElement} **/ (this.video_);
-   const {element} = component;
+   const {playback, component, element} = this.video_;
    playback.play();
    component.applyFillContent(foo);
    element.classList.add('foo');
  }
```

## Internal state

Some public `VideoEntry` methods actually handle internal state from the `VideoManager`. 

These should _not_ be public. They can be removed and localized privately in different ways:

- `updateVisibility()`: trigger a DOM event instead to be consumed by the entry (...or just use a local `IntersectionObserver`)

- `videoLoaded()`: this is already a result of a listener, listen from entry instead.

## Future work

`VideoEntry` might be a similar surface to what's expected from any React video component outside AMP docs, but we'll explore that later. This is the first step in normalizing towards that result.

Later goals include removing AMP-specific concepts, or make them not required:

- `VideoManager.getEntry()` assumes `Service`s.

- `playback` and `component` may have their public methods wrapped from `entry`, thus exposing its interface as a flat outer "`Component`":

```diff
- entry.playback.play()
+ entry.play() // => entry.playback_.play()
```

**Comment by wassgha** [comment]
LGTM!
