### ISSUE TITLE
SWG: Error: not allowed

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#27021]
go/ampe/CNn9pqqluez4aA

```
Error: not allowed
    at String (https://raw.githubusercontent.com/ampproject/amphtml/2002251816300/third_party/subscriptions-project/swg.js:2116:18)
    at code (https://raw.githubusercontent.com/ampproject/amphtml/2002251816300/third_party/subscriptions-project/swg.js:3095:12)
    at cmd (https://raw.githubusercontent.com/ampproject/amphtml/2002251816300/third_party/subscriptions-project/swg.js:2899:22)
    at cmd (https://raw.githubusercontent.com/ampproject/amphtml/2002251816300/third_party/subscriptions-project/swg.js:2862:24)
```

Seems to be all iPhones

/cc @jpettitt

**Comment by ChrisAntaki** [comment]
Looks like most of these errors are from publications that haven't done the SwG onboarding. There are some errors for onboarded publications like NYT though

**Comment by jpettitt** [comment]
These are coming from publications that are not configured properly for amp-subscriptions-google.  @ChrisAntaki the error message is coming from the pay iframe when we try and establish messaging to it.   Please open an internal bug to track better ways of handling this, hold off on doing anything as it's just noise in the error channel at this point.  We can discuss priorities with the rest of the team later.

**Comment by ChrisAntaki** [comment]
Sounds good!

**Comment by rcebulko** [comment]
In that case, would it make sense for this to be reported as an expected user error?

**Comment by ChrisAntaki** [comment]
Yes, most of the time at least

**Comment by rcebulko** [comment]
Once https://github.com/subscriptions-project/swg-js/issues/1016 is reviewed/submitted, we can start using AMP logging conventions to report expected errors.

**Comment by jpettitt** [comment]
[swg-js#1016](https://github.com/subscriptions-project/swg-js/issues/1016) was merged and included in SwG 0.1.22.96 #27248 which was merged into AMP yesterday.  We should start seeing the fixed error message withe the next canary release.

**Comment by rcebulko** [comment]
@jpettitt I don't think that closes this particular issue yet, since https://github.com/subscriptions-project/swg-js/pull/1017 only added the library (it didn't actually modify most of the errors reported by SwG). At some point today I'll put together a PR migrating a few of the SwG errors, including making this one expected.

**Comment by ChrisAntaki** [comment]
> including making this one expected

Some of these errors aren't expected though, go/ampe/CNn9pqqluez4aA?filter=text:nyt

**Comment by rcebulko** [comment]
After looking into how this error is actually happening, it's pretty odd. Not sure why String-ifying `data` (which is always an Error in this case) shoudn't throw like this...
