### ISSUE TITLE
amp-iframe sends constant errors when not resizable and child has pym loaded

### ISSUE THREAD

**Issue by maxlever** [ampproject/amphtml#27025]
## What's the issue?

Seeing many constant errors flooding the console when using amp-iframe: 
```
[amp-iframe] Ignoring embed-size request because this iframe is not resizable 
```

![image (3)](https://user-images.githubusercontent.com/6324699/75563164-defb9a00-5a17-11ea-8a0c-c2de2523be8e.png)

## How do we reproduce the issue?

public example here:

https://www.axios.com/carbon-emissions-rate-slower-2019-f235af5a-fbd8-46fc-a196-228233f20f16.html

jsfiddle:
https://jsfiddle.net/frch0xL7/

To reproduce
1. Create an amp-iframe _without_ a resizable attribute.
2. As iframe src, input any webpage which loads pym.js AND sends messages to the parent. you can use https://graphics.axios.com/hermes/2019-12-03-2037-annual-fossil-fuel/index.html as an example
3. Observe that the number of errors is steadily increasing (2x second).

## What browsers are affected?

All browsers.

## Which AMP version is affected?

Version 2002200031230 and above.

Follows this PR: https://github.com/ampproject/amphtml/pull/24917.

## Go deeper

this error is sent from updateSize, https://github.com/ampproject/amphtml/blob/39b1f619b7206bcfc91d4a0cc3b8b1386d416f1a/extensions/amp-iframe/0.1/amp-iframe.js#L670, which is called here:  https://github.com/ampproject/amphtml/blob/39b1f619b7206bcfc91d4a0cc3b8b1386d416f1a/extensions/amp-iframe/0.1/amp-iframe.js#L524 after this PR https://github.com/ampproject/amphtml/pull/24917 was merged (and not before, so this a different issue from #15665). logging error is sent when using amp-iframe without resizable attribute where the frame source has pym.js sending messages to parent.

See associated [thread on the amp slack](https://amphtml.slack.com/archives/C9HPA6HGB/p1582760440024100)

## Suggested fix

Ideal behavior should be that these messages should be ignored _if_ the iframe is not resizable, rather than logging all of the errors. a check should be made before calling `updateSize`, or within `updateSize`, to see if the iframe has the `resizable` attribute.

**Comment by jridgewell** [comment]
@maxlever: Are you interested in fixing this? We could add a "has already been warned" boolean to ignore after the first message.

**Comment by maxlever** [comment]
@jridgewell @westonruter I'm new to the repo but am happy to take a stab at it this weekend.

**Comment by maxlever** [comment]
@jridgewell made an initial attempt here: https://github.com/ampproject/amphtml/pull/27034
