### ISSUE TITLE
WP: Support ol[start] for list numbering

### ISSUE THREAD

**Issue by rajkumar1025** [ampproject/amphtml#27024]
Enabled the amp pages for post detail pages for wordpress site.  In post detail page, we are having the order item listing. If we used the start attribute to create the order type it shows the same number for all listing items. 

Not Working:
```
<ol>Item1</ ol >
<ol start=”2” > Item2</ ol >
<ol start=”3” > Item3</ ol >
```

Result:
```
1. Item1
1. Item2
1. Item3
```

**Comment by choumx** [comment]
Not an AMP bug. Do you have a sample page that shows the bug in WordPress?
