### ISSUE TITLE
Add source for C++ validator

### ISSUE THREAD

**Issue by dknecht** [ampproject/amphtml#2702]
What are the plans for open sourcing the C++ validator?

**Comment by Gregable** [comment]
We haven't announced any plans to open source any official ports of the validator other than the JavaScript one here. What would you like to accomplish specifically, maybe we can help with making the JavaScript validator meet your needs?

**Comment by dknecht** [comment]
CloudFlare is experimenting some tools to help our publishers with AMP.   We only run Go, C, C++, and Lua on the boxes where this needs to run.  If interested can do a hangout to give more details.

**Comment by dknecht** [comment]
@rudygalfi @ericlindley-g @dvoytenko Would it be possible to do a hangout to discuss your plans in this area?

**Comment by rudygalfi** [comment]
We have no plans at this time to open-source the C++ validator.
