### ISSUE TITLE
Actions/events: Support referencing parent element in target

### ISSUE THREAD

**Issue by azaslonov** [ampproject/amphtml#27038]
It would be great to have the ability to invoke methods of related elements, i.e. parent. It could be something like this:
```
<button on="tap:$parent.toggleClass(class=myclass)">
   Toggle
</button>
```
The only option now is to set `id` attribute and reference it in the event, but in many cases it is not convenient at all.

**Comment by sebastianbenz** [comment]
@azaslonov I've moved your issue over to the amphtml repository. 

//cc @choumx

**Comment by azaslonov** [comment]
Sure, thanks.

**Comment by choumx** [comment]
This doesn't seem related to amp-bind.

Why doesn't referencing by `id` attribute work for your use case?

**Comment by azaslonov** [comment]
Hi William,

Oh, I thought `<script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>` is needed enable `tap` event, at least [this article](https://amp.dev/documentation/components/amp-bind/) led me to belive that.

Anyways, I'm doing on a [content builder](https://demo.paperbits.io) that works with dynamic structures, e.g. multi-level menus (and menu components in AMP library do not work for us by several reasons), where there can be a lot of elements bound by child-parent relationships, and assigning IDs for each of them looks like overkill.
