### ISSUE TITLE
AMP4Email: Automatically forward Gmail messages to another account

### ISSUE THREAD

**Issue by alexandr-kazakov** [ampproject/amphtml#27033]
## What's the issue?

If we set up automatic movement of a Gmail message to another account, the AMP version does not open, but the normal HTML version opens.

## How do we reproduce the issue?

1. We have two different gmail accounts. Mail is automatically forwarded from one gmail account to another. Standard settings are used, as written here: https://support.google.com/mail/answer/10957?hl=en
2. In each account, the address of the sender of amp-emails is added to the settings manually(Settings > General > Dynamic email), for example: 
![chrome_PKgMXm30cp](https://user-images.githubusercontent.com/20513262/75609216-ad69f800-5b17-11ea-939f-094b41b4d085.png)
3. If we send an amp-email to each of these gmail accounts, it will be displayed correctly(The amp-version will be shown.).
4. But if we send an amp-email to the first gmail account that sends the email to the second gmail account, then this last one will show the HTML version, not the AMP.

Total: after redirecting from one gmail email to another, the amp version is not shown, but the HTML version of the email is always shown.

## What browsers are affected?

It was checked in gmail from different computers and mobile devices.

## Which AMP version is affected?

Version 2002112037430

**Comment by choumx** [comment]
This forwarding behavior is by spec:

> The email client strips out the text/x-amp-html part of the MIME tree when a user replies to or forwards an AMP email message.

https://github.com/ampproject/amphtml/blob/master/spec/email/amp-email-structure.md#replyingforwarding-semantics

Can you explain your intended use case here?

/cc @ampproject/wg-amp4email

**Comment by alexandr-kazakov** [comment]
> This forwarding behavior is by spec:

Thanks choumx,  I really missed this moment.

> Can you explain your intended use case here?

I'm developing amp-emails for a company. This company has corporate emails (such as: donald@company.com) in gmail, they got them using GSuite. From these corporate emails, they are redirected to their personal gmail account.
Until recently, I sent them different examples of amp-emails to corporate mail and they displayed them after the redirect(as they told me), but recently they stopped displaying, they wrote to me about it. I thought it was a bug and came here.

I think we can close this topic.  :wave:
