### ISSUE TITLE
Follow a defined syntax pattern for actions/events 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amphtml#27041]
## Describe the new feature or change to an existing feature you'd like to see

AMP actions and events are specific to AMP. We define how they work and the syntax pattern they follow - except we do not follow one pattern. For example [Element-specific actions for all elements](https://amp.dev/documentation/guides-and-tutorials/learn/amp-actions-and-events/?format=websites#*-(all-elements)):

1. `hide`, `show`, and `toggleVisibility`. Use `hide` when a visible element should no longer be visible and only allow it to be visible when the `show` action is explicitly executed. Use `show` to reveal a hidden element and only allow it to be hidden when the `hide` action is explicitly executed. Use `toggleVisibility` when an element's hidden and visible state should actively alternate. 

1. `toggleClass(class=STRING, force=BOOLEAN)`: Define `toggleClass(class="className", force=true)`when applying a class that should only be added, and only allow it be removed when `toggleClass(class="className", force=false)` is explicitly executed. Define `toggleClass(class="className", force=false)`when applying a class that should only be removed, and only allow it be added when `toggleClass(class="className", force=true)` is explicitly executed. Define `toggleClass(class="className")` when applying a class should actively alternate on an element. 

This level or syntax provides no overarching method to AMP development. This means micro-level things are implemented on a case-by-case basis. Developers must memorize these differences (or constantly refer to the documentation) instead of learning AMP's implementation. 

## Describe alternatives you've considered

1. Change `hide`, `show`, and `toggleVisibility` syntax to: `toggleVisibility(force=BOOLEAN)`

1. Change `toggleClass(class=STRING, force=BOOLEAN)` syntax to: `addClass(class=STRING)`, `removeClass(class=STRING)`, and toggleClass(class=STRING)`

//cc: @sebastianbenz

**Comment by choumx** [comment]
Thanks for the feedback. We probably can't safely remove the old APIs but we could deprecate them and encourage usage of the new stuff.

/cc @ampproject/wg-runtime
