### ISSUE TITLE
Run more AMP tests on IE 11

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#27048]
Today, it is already possible to run AMP's unit and integration tests on IE 11 in opt-in mode. However, there is just one test that has opted in.

![image](https://user-images.githubusercontent.com/26553114/75699026-bb398d80-5c7d-11ea-95ab-bff85c2ea939.png)

I'm filing this as a tracking bug for the AMP team's push to improve runtime performance. This can be closed when all working groups opt in at least a handful of their tests to run on IE 11.

This can be done using `enableIe()`, like so:

https://github.com/ampproject/amphtml/blob/79e2715683d905c5809c6dea1de64befd68beb6e/test/integration/test-amp-ad-doubleclick.js#L19-L23

**Comment by rcebulko** [comment]
Would it make sense to split this into tracking bugs for each WG, so they can have separate discussion threads about what should be done?

**Comment by rsimha** [comment]
> Would it make sense to split this into tracking bugs for each WG, so they can have separate discussion threads about what should be done?

I'll leave that to the WGs.

**Comment by newmuis** [comment]
Stories explicitly do not support IE11.

**Comment by lannka** [comment]
we also de-prioritized the IE11 support for AMPHTML ads.

**Comment by powerivq** [comment]
@lannka How about amp-ad on amp doc?

**Comment by choumx** [comment]
What's our high-level goal? E.g. AFAIK our IE11 support til now has been "best effort/mostly working".

**Comment by rsimha** [comment]
> What's our high-level goal? E.g. AFAIK our IE11 support til now has been "best effort/mostly working".

@nainar or @kristoferbaxter can comment on this.

**Comment by rcebulko** [comment]
Proposal: Create a PR temporarily enabling all tests in IE11 and look at the results. For all tests that pass, enable them explicitly.

**Comment by kristoferbaxter** [comment]
> My 2c: If our goal is "mostly working" on IE 11, I'd imagine we want more than one solitary ads test to run on the browser smiley

Precisely. If we intend to list IE11 in any regard as supported we should be running tests against it.

Otherwise, we should change our documentation and make significant changes to the codebase that eliminate the complexity added by supporting it (but not testing for it).

**Comment by choumx** [comment]
My point is different kinds of tests provide different kinds of coverage. E.g. if we only care about "mostly working", it's probably more effective to run end-to-end/visual tests on a handful of simple pages vs. trying to run `src/*.js` unit tests on IE.

**Comment by kristoferbaxter** [comment]
Higher coverage would be great for additional confidence, but starting with easier tests like `end-to-end` should give us more confidence than we have now with lower effort.

I like this suggestion.

**Comment by rsimha** [comment]
Some work has been done to fix our integration test infrastructure on IE11 (#27796) and add more tests (#27785). However, this is just a start, and needs more work from WGs for whom IE 11 support is important. The good news is that it's is very easy to enable existing integration tests on IE 11.

Meanwhile, getting E2E tests to run on IE11 requires significantly more work, like:
- Adding E2E support for IE 11 (needs Windows development machines)
- Getting Travis's Windows VMs to work efficiently (last attempted in #20945, VMs were too slow, and infeasible to use for CI)
- Using something like Github Actions (needs significant work)

Since these items are unlikely to happen in the near future, I'm leaving this issue as a tracker for WGs who would like to add / enable more IE 11 tests. Another thing worth trying on the side is the proposal in https://github.com/ampproject/amphtml/issues/27048#issuecomment-594184946, but it will need to be done piecemeal (per area), since most of our 10,000+ unit tests do not work on IE today.

**Comment by choumx** [comment]
I think we still need some definition of "minimal support" for IE11 and other technically unsupported browsers (e.g. a high-volume runtime error on Yandex browser came up recently). I'll file a discussion issue with a proposal.

**Comment by choumx** [comment]
#28152

**Comment by choumx** [comment]
Closing in favor of #28152.
