### ISSUE TITLE
Story-auto-advance needs to wait for resource load

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#27050]
I was looking at a Story with slow internet and the story advanced from the first to the second slide while the image (which made up all the content) on the first slide had only really been shown for a few milli seconds.

I think we need to hold advancing until the load event for all sub-resources has fired or something like that.

**Comment by newmuis** [comment]
Makes sense for time-based auto-advancement

AKA
- manual advancement should ~never be blocked
- media-based auto-advancement won't have this issue since it's dependent on the load (and completion) of the media by definition

**Comment by gmajoulet** [comment]
cc @ampproject/wg-stories
