### ISSUE TITLE
Validator: Add support for rel=standout

### ISSUE THREAD

**Issue by orzage** [ampproject/amphtml#2705]
The value "standout" for the rel attribute on link elements is a Google-introduced, established standard used by news organizations:

https://support.google.com/news/publisher/answer/191283?hl=en
http://googlenewsblog.blogspot.com/2011/09/recognizing-publishers-standout-content.html

However, it currently does not validate (version 1457721872758):

> The attribute 'rel' in tag 'link rel=' is set to the invalid value 'standout'.

**Comment by Gregable** [comment]
FYI, this will be visible on the cdn.ampproject.org validator in about an hour.

**Comment by orzage** [comment]
Confirmed, looks good.
