### ISSUE TITLE
Sourcemaps are not generated during babel pre-transform

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#27066]
https://github.com/ampproject/amphtml/blob/6584d230e6168f9e444cd46649fe597d3085d21c/build-system/tasks/helpers.js#L713-L724

This needs to be running the transforms and generating a sourcemap, so that Closure knows how to track the changes back to the true source files.

**Comment by rsimha** [comment]
With #27447 and related PRs, we are now generating sourcemaps during pre-babel transforms. (See lines 374-375.)

https://github.com/ampproject/amphtml/blob/929dfd9e53254a601331ec96869aa4fe0e35f711/build-system/compile/compile.js#L372-L401

With #27795, we now have a test to make sure sourcemaps are structurally correct.
