### ISSUE TITLE
Way to condition amp-auto-ads on amp-access

### ISSUE THREAD

**Issue by kushal** [ampproject/amphtml#27068]
The `amp-access-scroll` extension is used by our partners to hide ads depending on the result of an amp-access cal by surrounding advertising blocks in amp-access conditionals.

```
<div class="amp-ad-container" amp-access="NOT scroll.scroll">
  <amp-ad... >
</div>

```
However, we have now have a partner using `amp-auto-ads`, which doesn't provide any points of control where we can similarly hide ads for Scroll users.

We're happy to help with implementation if needed, but we could use some guidance on what is the most idiomatic path forward.

**Comment by dvoytenko** [comment]
An interesting case. @lannka would you say that initializing auto-ads from `buildCallback` is not correct? Or should auto-ads understand access restrictions inside the `buildCallback`?

**Comment by kushal** [comment]
Hi! We'd love some ideas here!

**Comment by jpettitt** [comment]
Had a quick chat with Dima and Caleb.  What we came up with is:

Add something like `<amp-auto-ads [access expression?]>` (and an equivalent for `amp-subscriptions`.   We expose a service from access and subscriptions and have have `amp-access-auto-ads` call it with the expression.  The service promise will resolve with the result of the expression once the access/subscriptions entitlement calls resolve.  From there the ads extension will know if it can render.

We'd have to limit the expression to one that resolves to a bool and we'd have to figure out how to handle amp-access-scroll and amp-subscriptions on the page at the same time but those are both solvable.

It might make sense to add this to the base `amp-ad` extension too as it would be cleaner than just wrapping the ad in a conditional.

@calebcordry @dvoytenko @kushal WDYT?

**Comment by dvoytenko** [comment]
I'll see what @calebcordry has to say. But I think this makes a lot of sense. I believe `amp-access` and `subscription-display` already resolve to boolean, so that fits as well.

**Comment by calebcordry** [comment]
SGTM. We can either block the config request or the ad creation on the result of the service promise. If we block on creation, ads-enabled users would see the creatives more quickly (more revenue etc) but the ad networks might not want to calculate the placements for the population of users that will never see ads.  I can run it by our partner ad networks and see what they think. They may already be doing something similar for the non-amp world.

**Comment by dvoytenko** [comment]
Thanks @calebcordry. Good point about placement-vs-creation latency. Let's confirm with the providers and see what they think. But I think generally everyone expects that the placements might not actually always take place. But, certainly, let's confirm.

**Comment by kushal** [comment]
This plan sounds awesome, thanks! Let us know if we can help.

**Comment by dvoytenko** [comment]
@calebcordry @lannka How would you recommend we proceed here? I'd like to see if we can keep it moving.

**Comment by dvoytenko** [comment]
/to @lannka to try the display/layoutCallback approach.

**Comment by lannka** [comment]
@kushal the PR is merged, and will likely hit our nightly channel next Monday. You can start testing by opt-in to the experiment: `AMP.toggleExperiment('auto-ads-layout-callback', true)`.
