### ISSUE TITLE
Intent to Implement Sovrn implementation for amp-ad

### ISSUE THREAD

**Issue by pdramos1** [ampproject/amphtml#2706]
Sovrn would like to submit an implementation for amp-ad. We will submit PR via a sovrn fork. Much thanks in advance.

**Comment by dvoytenko** [comment]
@pdramos1 Thanks! Looking forward to seeing your PR!

**Comment by jasti** [comment]
Implemented - https://github.com/ampproject/amphtml/blob/master/ads/sovrn.md.
Closing.
