### ISSUE TITLE
Email Binding Documentation is Broken/Incomplete

### ISSUE THREAD

**Issue by DouglasDev** [ampproject/amphtml#27086]
## What's the issue?

Documentation doesn't contain information listed in the table of contents. Without this information, it's difficult or impossible for developers to figure out what subset of JavaScript is valid in AMP for email.

## How do we reproduce the issue?

1. navigate to: https://amp.dev/documentation/components/amp-bind/?format=email
2. Click on various links in the table of contents such as 'state', 'expressions', 'bindings', and any of the subsections.
3. Documentation is missing.

## What browsers are affected?

All

## Which AMP version is affected?

All

**Comment by fstanis** [comment]
I believe this is tracked as ampproject/amp.dev#3545

**Comment by DouglasDev** [comment]
@fstanis Okay that looks like the same issue, but I don't think it is described correctly. Shouldn't this information be available for AMP for email? I need to know which JS expressions and methods can be used in an amp-bind tag, and without any documentation, I'm stuck doing it by trial and error, with no way of knowing why my AMP email is breaking.

**Comment by fstanis** [comment]
Ah, I see what you mean! Thanks for reporting, seems the bulk of that article is missing due to a mismatched filter, #27143 fixes it.

**Comment by DouglasDev** [comment]
@fstanis Are you sure that it was fixed? Most of the documentation still seems to be missing.

**Comment by fstanis** [comment]
Both of those are an issue with ToS (ampproject/amp.dev#3545), `target` is not allowed in `amp-form` and `credentials` is not allowed in `amp-list`. You can find "Invalid AMP email attributes" in each reference that explicitly mentions this.

The `amp-bind` issue is fixed in code, but we'll need to wait a week or so for it to go live on amp.dev.

**Comment by DouglasDev** [comment]
@fstanis Got it. Thanks for your help.
