### ISSUE TITLE
Expose `ampTrust` property with amp-carousel v2 `slideChange` event

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#27082]
## Describe the new feature or change to an existing feature you'd like to see

amp-carousel v1 recently exposed this property in #26991 and amp-carousel v2 should as well to keep this behavior consistent across versions.

## Describe alternatives you've considered

Keep this behavior inconsistent across versions: this is bad for devx. 

## Additional context

This is a "good first issue"! The change would involve replicating the change in the PR linked above, except in amp-carousel v2. This change should only apply to carousel with `type="slides"`.

**Comment by AtharvaSune** [comment]
Hi i am new here, if this issue is still open and available to work on i would like to work on it

**Comment by caroqliu** [comment]
Sure thing! Thanks for volunteering!

**Comment by AtharvaSune** [comment]
I ll start working on this then :slightly_smiling_face:

**Comment by AtharvaSune** [comment]
hi, i had some doubts regarding writing tests , could you please help :sweat_smile: ?

**Comment by dmanek** [comment]
This issue has been dormant for a while. Assigning to myself. Will build on @AtharvaSune's PR.
