### ISSUE TITLE
Add a component to display Tiktok posts

### ISSUE THREAD

**Issue by pierlon** [ampproject/amphtml#27080]
## Describe the new feature or change to an existing feature you'd like to see

Tiktok is becoming a very popular platform and as such a component should be added to support their posts. Also, WordPress has recently [added support](https://core.trac.wordpress.org/ticket/49083) through their OEmbed API.
 
## Describe alternatives you've considered

There has been effort to display Tiktok posts via the `amp-iframe` component (see https://github.com/ampproject/amp-wp/pull/4357), but the URL being used for the `src` attribute is not the same as what the Tiktok iframe uses. Tiktok creates the URL for the `iframe` on page load via their included JS embed script, and so there is no guarantee that the URL being used as the `src` for `amp-iframe` will be the same as what would be generated by the script. In this case, for example, the `lang` query parameter cannot be determined on the server side.

One possible way to overcome this would be to use the `BROWSER_LANGUAGE` variable to substitute the value of the `lang` query parameter, but it seems it is [not supported when used in the `src` attribute of an `amp-iframe`](https://github.com/ampproject/amphtml/pull/10884).

**Comment by westonruter** [comment]
Something else that this component may be required to do is sizing, if TikTok isn't sending the required AMP resize messages for `amp-iframe`.

**Comment by westonruter** [comment]
I've tried sending an email to TikTok to see if we can get connected with a developer who works on embeds.

**Comment by westonruter** [comment]
Closing in favor of #32219.
