### ISSUE TITLE
<amp-script> allows mutations with no restrictions if layout="fill"

### ISSUE THREAD

**Issue by morsssss** [ampproject/amphtml#27118]
For an `<amp-script>` component like this:

`<amp-script layout="fill" script="myscript">`

Mutations are allowed immediately on page load, and they can go on forever. This is true even if dimension attributes are not included, as in the sample above.

Since it's not hard to make that component fill a large part of the browser window, I fear this situation is ripe for abuse.

(See also #26524 for discussion)

**Comment by samouri** [comment]
I tried reproing this locally and was unable to have the mutations change the size of the amp-script's dimensions.

I don't see a difference between allowing `fill` to mutate forever and allowing a `fixed` one mutate forever

**Comment by morsssss** [comment]
Yeah, I can't get mutations to change the amp-script's dimensions either!

My concern is that we allow mutation forever even if dimensions aren't set in HTML, where as we require dimensions to be set in HTML to enable this behavior for any other type. I've been using this in my test to cheerfully modify anything I want to, on the entire page, for as long as I want to.

But I agree the effect isn't that different from what you can achieve with other layout types and very large dimensions set. So I'm happy to close this.
