### ISSUE TITLE
Remove build.conf.js

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#27117]
The entire file is dedicated to setting up Babel in special ways. This should all live in `babel.conf.js`, so that there's only one place where babel configuration takes place.

**Comment by rsimha** [comment]
Happy to have someone on infra work on this, given that it's refactoring work in our compilation toolchain.

@erwinmombay let me know if you'd prefer working on this
@rcebulko if not, is this something you can look into?

**Comment by erwinmombay** [comment]
happy to help, but id prefer to defer to infra team. if not i can take it on next sprint

**Comment by rsimha** [comment]
I'll take this on, since I've messed with the code quite a bit recently.
