### ISSUE TITLE
ads - rtc-config - gpt safeframe does not expand on refresh when using data-enable-refresh

### ISSUE THREAD

**Issue by J-Pitt** [ampproject/amphtml#27125]
## What's the issue?

Using a 300x250 `amp-ad` element with `data-enable-refresh=30` attribute, the gpt safeframe collapses to 1x1 on refresh calls and does not expand on subsequent requests. I am using a 1x1 GAM creative with safeframe enabled, and it has a 300x250 size override. 

JavaScript used to resize:
```
        var iframeWidth = window.innerWidth,
            iframeHeight = window.innerHeight,
            adWidth = 300,
            adHeight = 250,
            newWidth = adWidth - iframeWidth,
            newHeight = adHeight - iframeHeight,
            sfAPI = window.sfAPI || window.$sf.ext;
        if (sfAPI) {
            if (iframeWidth !== adWidth || iframeHeight !== adHeight) {
                sfAPI.register(adWidth, adHeight);
                sfAPI.expand({
                    r: newWidth,
                    b: newHeight,
                    push: false
                });
            }
        }
```

Note: The initial call to expand the safeframe works as expected, but on the first refresh, the safeframe delivered is 1x1 and does not expand. This occurs in instances where the `amp-ad` unit stays 300x250 (so no reflow). 

I am expecting the call to expand the safeframe to succeed on refresh calls, just like it did initially. According to [safeframe.md](https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad-network-doubleclick-impl/safeframe.md)<link>:

**To prevent reflow for SafeFrame expansion, expand will only succeed in the following scenarios:**
>"The expansion request is made for an expanded-size that is less than or equal to the size of the parent amp-ad element. All SafeFrames within AMP are nested within an amp-ad element. amp-ad elements are already laid-out within the page to a specific size. If a creative calls expand() such that the expanded size of the SafeFrame will still be entirely contained within the amp-ad, then expand will succeed regardless of whether the SafeFrame is within the viewport or not."

***In this case, the `amp-ad` element has the size 300x250, but the safeframe inside does not expand.***

## How do we reproduce the issue?

1. go to: https://jsbin.com/firolawume/edit?html,output
2. view the ad delivered initially (text that says "I'm an ad"), size of creative (safeframe) was expanded from 1x1 to 300x250
3. wait 30 seconds until the first refresh, view the safeframe, note the 1x1 size. 

The same code was delivered on both the initial ad request and the refresh. 

## What browsers are affected?
All browsers

## Which AMP version is affected?

Is this a new issue? Or was it always broken? Paste the version of AMP where you saw this issue. Version 2002192257490

**Comment by J-Pitt** [comment]
@lannka Could you help confirm if this is a bug or point me in the direction of someone that can?

**Comment by lannka** [comment]
@glevitzky do you have insights on this?
