### ISSUE TITLE
Support history on back button for amp-sidebar

### ISSUE THREAD

**Issue by sriramkrish85** [ampproject/amphtml#2712]
Support history on back button for amp-sidebar like done in amp-lightbox

**Comment by ericlindley-g** [comment]
@sriramkrish85 , is this something you're already working on, or for the future?

**Comment by dvoytenko** [comment]
Yes, it's for the next sprint.

**Comment by rudygalfi** [comment]
Is there a PR for this? I'm putting this into the next sprint, but we can pull in if there's active work on this that will land by tomorrow.

**Comment by sriramkrish85** [comment]
nope - this is future work

**Comment by ericlindley-g** [comment]
Rolling into the next milestone

**Comment by ericlindley-g** [comment]
Looks like there hasn't been activity on this, so putting into backlog for now

**Comment by dvoytenko** [comment]
I'll move it to the next milestone since it's about 5 lines of code.
