### ISSUE TITLE
Support styling amp-lightbox-gallery caption

### ISSUE THREAD

**Issue by photocoder** [ampproject/amphtml#27121]
#27000  What's the issue?

 [The manual ](url=https://amp.dev/documentation/components/amp-image-lightbox/)  has description about styling.

> The `amp-image-lightbox-caption` class is also available to style the caption section.

But it doesn't work. 

## How do we reproduce the issue?

Here is testing page: https://dimasfrolov.com/test/1/
style included:
```
.amp-image-lightbox-caption {
    color: red;
}
```
And as you see, it still white when look at the photo via lightbox.
![Screenshot](https://dimasfrolov.com/test/styling_capture.png)

## Which AMP version is affected?
Powered by AMP ⚡ HTML – Version 2002192257490

**Comment by caroqliu** [comment]
Hi @photocoder thanks for filing this issue! It looks like you are using `amp-lightbox-gallery` on your page, whereas the `amp-image-lightbox-caption` class is specifically used by the `amp-image-lightbox` component. 😅  It would be great to have something similar here so the API surface is more consistent between these two.

**Comment by caroqliu** [comment]
Marking this as a feature request and GFI to expose a public class on the caption for publishers to be able to target and style.

**Comment by THE-VR7** [comment]
Hello. I am new  and would love to contribute.
I would like to fix this issue, if no one is already on it.

**Comment by caroqliu** [comment]
Please do, thanks for volunteering. :)

**Comment by THE-VR7** [comment]
I am new to this , Please can you guide me ,
Am i supposed to make the changes in amp-lightbox-gallery-caption css file or somewhere else

**Comment by caroqliu** [comment]
1. Modify [lightbox-caption.js](https://github.com/ampproject/amphtml/blob/master/extensions/amp-lightbox-gallery/0.1/lightbox-caption.js#L42). Where it currently generates `<div class="i-amphtml-lbg-caption-text"></div>`, make sure it also has: `amp-lightbox-gallery-caption` class.
2. Add an example usage in with the class being used to style the caption. 
3. Modify `extensions/amp-lightbox-gallery/amp-lightbox-gallery.md` to include the new `amp-lightbox-gallery-caption` as well as how to use it, similar to the [Styling section for amp-image-gallery](https://amp.dev/documentation/components/amp-image-lightbox/#styling).
4. Send your PR for review :)
