### ISSUE TITLE
I2I: Stale bot

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#27138]
## Summary

Install [stale bot](https://github.com/apps/stale) to automatically close issues that reach one year of inactivity.

```
daysUntilStale: 358
daysUntilClose: 7
```

The motivation is to reduce triage/issue management toil for maintainers by automatically and regularly cleaning up obsolete issues.

Not all inactive issues are obsolete however, so please feel free comment on the issue to avoid auto-closing or to request that a closed issue be reopened. 

The stale bot will give a one week warning.

**Comment by choumx** [comment]
162 issues that would be auto-closed as of 2020-03-01: https://github.com/ampproject/amphtml/issues?q=is%3Aissue+is%3Aopen+updated%3A%3C2019-03-01+

We can also decide on a label for opting out e.g. `Indef`.

/cc @ampproject/wg-infra

**Comment by rcebulko** [comment]
I've seen similar bots that, instead of/in addition to closing the issue, add a tag like "archived for inactivity". Do you know if this implementation has a feature like that?

**Comment by rcebulko** [comment]
(I'm thinking of the case where PM X wants to do something and says "I know we had a tracking issue for this but...")

**Comment by choumx** [comment]
It supports adding a label to stale issues.

```
# Label to use when marking an issue as stale
staleLabel: wontfix
```

**Comment by rsimha** [comment]
My two suggestions from design review:
- Change `stateLabel` to `stale` instead of `wontfix` (so we merely label the issue without making a judgement about whether it's actually worth fixing)
- Increase grace period from 7 days to 14 days (I don't feel strongly about this)

Happy to help with actual installation of the app!

**Comment by choumx** [comment]
From https://github.com/ampproject/amphtml/issues/26576#issuecomment-598414390:

> DV: what about stale but never triaged issues?
WC: Good point, could use another bot for this. TODO: Find the # of issues

There are [10 issues](https://github.com/ampproject/amphtml/issues?q=is%3Aissue+is%3Aopen+updated%3A%3C2019-03-01+-label%3A%22P0%3A+Drop+Everything%22+-label%3A%22P1%3A+High+Priority%22+-label%3A%22P2%3A+Soon%22+-label%3A%22P3%3A+When+Possible%22+-label%3A%22WG%3A+access-subscriptions%22+-label%3A%22WG%3A+ads%22+-label%3A%22WG%3A+amp4email%22+-label%3A%22WG%3A+viewers%22+-label%3A%22WG%3A+analytics%22+-label%3A%22WG%3A+caching%22+-label%3A%22WG%3A+infra%22+-label%3A%22WG%3A+performance%22+-label%3A%22WG%3A+runtime%22+-label%3A%22WG%3A+stories%22+-label%3A%22WG%3A+ui-and-a11y%22+-label%3A%22Type%3A+Release%22+-label%3A%22Type%3A+Design+Review%22) that are 1Y+ stale with no WG or priority label, and none of them look untriaged.

**Comment by choumx** [comment]
> Happy to help with actual installation of the app!

I already requested installing into amphtml, I think it just needs approval. :)

**Comment by rsimha** [comment]
I think @cramforce or @mrjoro need to approve.
