### ISSUE TITLE
Frequent Percy failures

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#27181]
**summary**
In the past ~week or so I've noticed what feels like a significant uptick in spurious Percy failures. In some cases, I've been unable to get them to pass even with multiple rounds of rebasing/rerunning.

It also seemed to me like there were just a couple of test cases failing most of the time (e.g. "Grid layer (fill)" failed for most of my PRs). 

We should harden our tests to be less flaky, or at least skip the worst offenders

/to @rsimha

**Comment by rsimha** [comment]
@samouri Thanks for the report. Can you post some example links to failures?

- @calebcordry is this week's build cop and can help alleviate this by skipping any test that regularly flakes.
- @gmajoulet should know what those STAMP visual tests are trying to do, and how to make them more reliable.
- @danielrozenberg is the overall area expert for visual tests, and can advise on whether the tests are using any known anti-patterns (like not waiting long enough for a UI element to appear)

**Comment by calebcordry** [comment]
the mega-menu visual diff tests also seem to pop up often, eg https://percy.io/ampproject/amphtml/builds/4467899

**Comment by caroqliu** [comment]
I've also had trouble with amp-story: https://percy.io/ampproject/amphtml/builds/4471771
Occasionally I will see amp-sidebar, amp-lightbox-gallery

**Comment by gmajoulet** [comment]
@caroqliu the first one looks like a bug, thanks for posting about it. The second one is an image loading issue though, which caused many of the failures I've seen.

**Comment by danielrozenberg** [comment]
Thanks everyone for adding more "evidence" here, I'll look into it tomorrow. In the meantime please everyone keep adding more broken/flaky builds that you see!

// special callout to @ampproject/wg-ui-and-a11y @ampproject/wg-runtime @ampproject/wg-ads @ampproject/wg-stories

**Comment by samouri** [comment]
Two more [examples](https://percy.io/ampproject/amphtml/builds/4484301?utm_campaign=ampproject&utm_content=amphtml&utm_source=github_status_public):
1. "amp-mega-menu: template render (click menu item one)"
2. "amp-story: info dialog"

**Comment by samouri** [comment]
Three more [examples](https://percy.io/ampproject/amphtml/builds/4486412?utm_campaign=ampproject&utm_content=amphtml&utm_source=github_status_public):
1. "amp-story: unsupported browser (desktop)" -- I've definitely seen this one many times
2. "AMP Sticky Ad"
3. "amp-story: info dialog" (repeat from above)

**Comment by caroqliu** [comment]
fade-in & fade-in-scroll: https://percy.io/ampproject/amphtml/builds/4506500

This also appears to be an image loading issue

**Comment by danielrozenberg** [comment]
Contacted Percy support, I'll keep y'all posted here. Thanks for the various examples!

**Comment by ChrisAntaki** [comment]
I'm also seeing issues with images loading
https://percy.io/ampproject/amphtml/builds/4560241

**Comment by danielrozenberg** [comment]
I'm working on applying some of the suggestions that Percy support gave me, will keep this thread updated!

**Comment by danielrozenberg** [comment]
I merged #27292 two days ago, which should, hopefully, have fix the missing *images* flakes. Let me know if you see any more flaky visual diff tests and I will debug them

**Comment by rcebulko** [comment]
I'm seeing some flakes on bits of text appearing/disappearing. @Enriqe have you seen [these failures](https://percy.io/ampproject/real-world-pages/builds/4689359) this week? Should some of these tests get skipped?

**Comment by danielrozenberg** [comment]
After making the change in #27292 and disabling the flaky tests last week it looks like this issue is mostly resolved. Please reopen this if you see more flaky visual diff tests!
