### ISSUE TITLE
AMP-IMG not render inside HTML details tag  

### ISSUE THREAD

**Issue by nebuso** [ampproject/amphtml#27193]
AMP-IMG inside HTML `details` tag  does not load photos when `details` opened.
`<amp-img` not responding on change state to `details[open]` .
I need do click on picture to load them.
I'm styling `figure` element. 
`amp-img`  with `lightbox`
JavaScript doing "the job" and i see replaced `<amp-img` with `<img` 
**but** its render **empty space**, and in console i don't see **any network request** to loading the image.

https://www.w3schools.com/tags/tag_details.asp

`#development=amp` console clear, amp valid

```
<details>

<summary> title</summary>

<div>
<!-- DIV with 4 images -->
<h4>title </h4>

<figure ig="">

<amp-img 
   layout="responsive"
   lightbox="galleryname"
   src="webp image" 
   srcset="1.webp 100w, 2.webp 200w">

<amp-img fallback with jpg></amp-img>

</amp-img>
</figure>

3 more * <figure><amp-image> ...

</div>

</details>
```

Thanks for your time!
Dawid

**Comment by caroqliu** [comment]
Hello Dawid, thank you for taking the time to file this issue! I was able to produce the following code sample with an `amp-img` inside of a `<details>` tag: https://jsbin.com/neyisuyehe/edit?html,output

It looks like the image is rendering, and I added some examples with a placeholder and fallback as well. Can you describe more the issue you are having?

**Comment by nebuso** [comment]
https://jsbin.com/neyisuyehe/edit?html,output

Hello.
I remove "open" attribiute in your example.

Press open/close mamy times, 
and i see placeholder "Waiting for the image!". 

*
Chrome on Android 9, 
Chrome beta at Windows 10 (1909),
Firefox - Latest

**Comment by caroqliu** [comment]
Thanks for reporting this issue. Here is the updated sample: https://jsbin.com/joyahibuku/1/edit?html,output

I was able to reproduce in Firefox and Chrome 80, 82. 

I'm also noticing that if you open the `detail` "quickly" i.e. within a few hundred ms of load, the image does load and eventually replace the placeholder. However if you toggle it back and forth or wait before initially opening, the image never gets fetched as you say.

**Comment by jridgewell** [comment]
Thanks for the report! I'm going to de-duplicate this with https://github.com/ampproject/amphtml/issues/26952.
