### ISSUE TITLE
AMP Consent to support "gdprApplies" param

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#27190]
TCF requires replacing the "[gdprApplies](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#what-does-the-gdprapplies-value-mean
)" param. 

AMP doesn't support that variable. The closest is the [`consentRequired`](https://amp.dev/documentation/components/amp-consent/#consentrequired) field. 
`consentRequired` doesn't work well because its value can be true when another regulations applies. Since AMP decided to support IAB TCF, I propose we introduce a new field to the CMP endpoint response "gdprApplies". The value will be stored along with the consent string and passed to ad vendors. 

```
{
  "consentRequired": {boolean}
  "consentStateValue": {?enum} [default: null]
  "consentString": {?string} [default: null]
  "expireCache": {boolean} [default: false]
  "gdprApplies": {boolean} [default to consentRequired value]
}
```

Note: AMP will use the "consentRequired" value if the "gdprApplies" is not defined. 

Important Notice:
AMP reduces the delay by always respecting the localStored value, and only updates it for the next user visit. That will apply to the "gdprApplies" value as well.

**Comment by zhouyx** [comment]
cc @yoannOgury @PierigOgury @andresilveirah @jawadst @tla-sirdata

**Comment by tla-sirdata** [comment]
Works for me. I think we should also consider a ccpaApplies field. Thanks

**Comment by micajuine-ho** [comment]
@tla-sirdata Does the [US Privacy String](https://github.com/InteractiveAdvertisingBureau/USPrivacy/blob/master/CCPA/Version%201.0/US%20Privacy%20String.md#us-privacy-string-format) not satisfy the `ccpaApplies` field?

**Comment by tla-sirdata** [comment]
@micajuine-ho 

This field only reflects the user choice to opt-out when the CCPA banner is surfaced to him.
The US Privacy String may have been updated when user has accessed the website while being in California but if he travels in Europe, CCPA no longer applies to him (uncommon case I admit).

Also if `consentString` is empty and `gdprApplies`is `false`, there's no way to know that CCPA applies. The main idea is to transmit to AMP an information whether another regulation applies so the appropriate banner can be displayed.

**Comment by zhouyx** [comment]
One thing I want to state is that AMP wants to add support to `gdprApplies` because it is required param by the TCF v2 and will be used by many ad vendors. That's the difference between `gdprApplies` and `ccpaApplies`. If we `ccpaApplies` will be adopted by all vendors then we are more than happy to add support in the future. 

Right now, you should be still be able to pass `ccpaApplies` and other custom param value to an ad vendor using the `sharedData` object.

**Comment by tla-sirdata** [comment]
Hi, I'm not sure if this feature is live but I just want to let you know that we updated our [checkConsentHref endpoint](https://sddan.mgr.consensu.org/api/v1/public/amp/check) to include `gdprApplies`.

**Comment by micajuine-ho** [comment]
Hi @tla-sirdata, thanks for the update. 

The AMP team plans to change the `checkConsentHref` API in the near future which will directly change the `gdprApplies` field. 

Would you be willing to hold off your change until this or be willing to change your API when the `checkConsentHref` API changes?

**Comment by tla-sirdata** [comment]
If that's OK for you, I prefer to let the new field on. The `consentRequired` field is still unchanged.
I'll be able to update quickly when the API changes.

Thanks

**Comment by micajuine-ho** [comment]
Yes, that sounds good to me. Will update you when the changes occur.

**Comment by micajuine-ho** [comment]
@tla-sirdata Update: Change to `gdprApplies` PR is out now https://github.com/ampproject/amphtml/pull/28852

**Comment by tla-sirdata** [comment]
@micajuine-ho Thank you, I'll update and send you an integration example.

**Comment by tla-sirdata** [comment]
@micajuine-ho I've updated the `checkConsentHref` response and the `promptUiSrc` workflow to include `consentMetadata` (`gdprApplies` + `consentStringType`).

Please find an example [here](https://www.futura-sciences.com/alternative/amp/actualite/80151/).

**Comment by micajuine-ho** [comment]
Hi @tla-sirdata, the metadata looks good from `checkConsentHref`!

What changes did you make to your `promptUiSrc` workflow?

**Comment by tla-sirdata** [comment]
@micajuine-ho I included `consentMetadata` in the `consent-response` message when the user saves his choices.
