### ISSUE TITLE
Layout=responsive default with attributes - mismatch between docs and actual behaviour

### ISSUE THREAD

**Issue by ZauberNerd** [ampproject/amphtml#2720]
The documentation says that a layout of type `responsive` is assumend:
* if width or height attributes are present along with sizes and/or heights attribute, responsive layout is assumed;

But this only happens, when: `width` **and** `height` **and** (`heights` **or** `sizes`) is present.
Otherwise it will become `fixed-height`.

See here the condition which applies `fixed-height` when `height` is set and `width` is unset or 'auto'.
This condition comes before the `responsive` condition:
https://github.com/ampproject/amphtml/blob/fd2fce8d8086f7953f65d816e509905e17fd0d54/src/custom-element.js#L175

and here is the condition for `responsive` layout which unlike the documentation specifies, does not allow only `width` **or** `height` but needs both **and** (`heights` **or** `sizes`): https://github.com/ampproject/amphtml/blob/fd2fce8d8086f7953f65d816e509905e17fd0d54/src/custom-element.js#L177

What is the correct behaviour? As specified in the docs or the implemented behaviour?

See the documentation is question here:
https://github.com/ampproject/amphtml/blob/master/spec/amp-html-layout.md#layout

**Comment by ZauberNerd** [comment]
Oh, same goes for `layout` = `fixed-height` | `fixed`.
The documentations says that if `width` is set and `height` is unset or `auto` the layout will be `fixed-height` but also says that if only `with` or `height` are specified the `layout` will be `fixed`.
But a `fixed` layout is only assumed when only `height` is set.
Should I open another issue for that or change this issue to be about the "layout inferring" in general?

**Comment by jridgewell** [comment]
@dvoytenko: Can you confirm that this is the expected behavior?

**Comment by dvoytenko** [comment]
Yes, the documentation is incorrect in those places. I started the fix in the https://github.com/ampproject/amphtml/pull/2727
