### ISSUE TITLE
SwG: Integration with AMP error reporting

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#27223]
The AMP Runtime and extensions use a [handful of helpers](https://github.com/ampproject/amphtml/blob/master/src/log.js) to report errors to a central [error tracking](https://github.com/ampproject/error-tracker/) service. These errors are tagged with information about the release, browser, stacktrace, and whether the error was expected (ie. a known failure case), a user error (incorrect configuration or usage), or unexpected (something is borked and we don't know why).

Since SwG is integrated as a third-party plugin, errors thrown by it (examples include https://github.com/ampproject/amphtml/issues/27021 and https://github.com/ampproject/amphtml/issues/24247) bubble up to the calling code in the AMP runtime or extension and are treated as unexpected breakages. This can make it difficult to identify new "real" errors, or to know when an error that pops up requires a fix or is a known failure case.

User errors are identified by using a triple zero-width space `\u200B\u200B\u200B` sentinel at the start of any error message, while expected errors are identified by adding `error.expected = true` to the error object.

Where else is the SwG library used as a third-party library? Would it be reasonable or disruptive to either import, duplicate, or implement the AMP logging standard? Alternately, would it be feasible to catch any possible errors in a central place where SwG is invoked, or does it run outside of the AMP  HTML runtime in some way? Making some progress on standardizing SwG logs could make it easier to detect regressions in SwG itself as well.

/cc @ampproject/wg-access-subscriptions

**Comment by rcebulko** [comment]
Come to think of it, I expect it wouldn't be too difficult for the error reporting service to identify SwG errors based on the stack trace and report errors in SwG to a separate service bucket. @jridgewell What do you think about this idea?

**Comment by jpettitt** [comment]
We should write a better internal error handler in swg.js - right now it just throws `new Error(...)` all over the place.  swg.js issue [1016](https://github.com/subscriptions-project/swg-js/issues/1016)

**Comment by jridgewell** [comment]
I'd rather not add have to analyze the stack trace code, since each browser has its own format. Having a SwG register a global `onerror` would be cool, provided it could still report errors generated by runtime.

**Comment by rcebulko** [comment]
@jridgewell So far I've transferred a stripped-down version of AMP's error loggers (`user().expectedError()` etc.) into SwG, it should be a no-op for SwG but will allow the errors to carry the `expected` property or user error sentinel string, so when AMP catches and reports them we should get them reported as desired
