### ISSUE TITLE
Allow `clip-path` in AMP (web-only)

### ISSUE THREAD

**Issue by wassgha** [ampproject/amphtml#27239]
See #27160

**Comment by wassgha** [comment]
Hey @Gregable , any update on this?

**Comment by Gregable** [comment]
In progress? It requires significant rework.

**Comment by pbakaus** [comment]
@Gregable could you provide an update here? Would love to hear what the rework refers to. It sounded like it was mostly a scoping issue (not allowing it for AMP4Email)?

This is a fairly timely request for us - we are releasing an alpha of our stories editor this week to select folks, and all stories generated by it will be invalid.

Thanks much!

**Comment by Gregable** [comment]
Not much has changed since Friday. Still in progress.

**Comment by pbakaus** [comment]
@Gregable apologies I missed the date from your response earlier, didn't mean to imply you should have worked weekends :) I'll stay tuned then.

**Comment by dvoytenko** [comment]
@Gregable let's touch base on this. Anything we can do to help? Maybe I misjudged the issue, but I expected it to be a fairly small configuration change.

**Comment by Gregable** [comment]
@dvoytenko responded via email.

**Comment by Gregable** [comment]
This fix is now live.

**Comment by pbakaus** [comment]
Amazing, thank you Greg!!

**Comment by dvoytenko** [comment]
Thanks so much, @Gregable!
