### ISSUE TITLE
Add html{overflow-y:scroll} to enforce a scrollbar at first paint

### ISSUE THREAD

**Issue by kevinkimball** [ampproject/amphtml#27245]
## Describe the new feature or change to an existing feature you'd like to see
Reduce measured layout shift on desktop by adding `html{overflow-y:scroll}` CSS to enforce a scrollbar at first paint. This would need to be added to the boilerplate. 

## Describe alternatives you've considered
The CSS could be injected by the cache

## Additional context
n/a

**Comment by jridgewell** [comment]
We already have [`overflow-x: hidden`](https://github.com/ampproject/amphtml/blob/8be63bf7b769f7c903a7d57bf44f8cca19760743/css/ampdoc.css#L27), which makes `overflow-y` implicitly `auto` (default is `visible`). Does this the implicit `auto` already give us the benefit? Or do we specifically need to use `overflow-y: scroll`?

**Comment by kevinkimball** [comment]
Good question @jridgewell 

Here's the inspiration for this shared by @cramforce 
https://twitter.com/TimVereecke/status/1239454788116533248?s=19

According to [MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-y), auto does not show scrollbar unless necessary. This property should force it to show all the time, preventing horizontal layout shift.
