### ISSUE TITLE
Add Viewer Capability to Handle All External Navigation

### ISSUE THREAD

**Issue by ammaxwell** [ampproject/amphtml#27252]
## Describe the new feature or change to an existing feature you'd like to see

We're building an AMP Viewer and would like to be able to handle any navigation on the AMP page in the viewer instead of letting navigation happen normally (for external links leaving the doc. Internal links should still navigate through the doc as normal).

Two possible options for moving forward:
1. Expand the 'navigateTo' viewer capability to be used for all external navigation, instead of just app redirects.
2. Create a new viewer capability, maybe "intercept-navigation" that is checked before navigating, and hands off the url to the viewer. 

## Describe alternatives you've considered

I haven't found a foolproof alternative after looking through the various viewer capabilities that are available. The 'navigateTo' capability seems to be closely related to what we want to do, but is currently only used for native app redirects, and the 'a2a' capability is only for navigating to other AMP pages.

## Additional context

Both a2a and navigateTo capabilities are similar to what we want, but don't cover the full extent of all external navigation.

**Comment by ammaxwell** [comment]
@choumx

**Comment by choumx** [comment]
Let's add a new `interceptNavigation` capability.

Aside: Small part of me is bugged that we didn't go with `reportError` and `interceptXhr` vs. `errorReporter` and `xhrInterceptor`.

**Comment by choumx** [comment]
Implemented in #27649.
