### ISSUE TITLE
Do not force AMP Stories to be self-canonical

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#27307]
Currently AMP Stories have to be self-canonical. Given the deprecation notice of the amp-sidebar and the bookend, publishers may want to make a separate page that contains an `amp-story-player` the canonical URL. That way they can have features like auto-advancing to the next story and showing a sidebar.

**Comment by newmuis** [comment]
Thanks for raising this @cpauwels!  This guidance has been revised, and we've added a section to the [SEO for AMP Stories blog post](https://blog.amp.dev/2020/02/12/seo-for-amp-stories/) about it.

**Comment by rrjanbiah** [comment]
@newmuis Came here while searching for a solution for `amp-story canonical error` issue.

But, unfortunately, it is still not clear:

> https://blog.amp.dev/2020/02/12/seo-for-amp-stories/
> However, if you have a separate story webpage with the same content as an AMP Story, you should consider making the AMP Story canonical. Make sure to AMP-validate your Web Stories.

Say for example, https://example.com/ampstory is the AMP story of https://example.com/ ...  looks like you're suggesting to use 'canonical' for https://example.com/ampstory. But, 

1. how to do the pairing? 
2. If pairing is not supported, how to handle duplication (and possible penalty)? 
3. And, how to refer https://example.com/ ('canonical' or)?

**Comment by rrjanbiah** [comment]
@newmuis Apologies for my poor English and continuation of above comment... to be very clear about this issue....

### Option 1 ###

In https://example.com/ampstory (AMP story version of https://example.com/ )
```html
<link rel="canonical" href="https://example.com/ampstory">
```
And in https://example.com/ 
```html
<link rel="canonical" href="https://example.com/">
<link rel="amphtml" href="https://example.com/ampstory">
```

### Option 2 ###

When both https://example.com/ and https://example.com/ampstory are AMP HTML validated:

In https://example.com/ampstory (AMP story version of https://example.com/ )
```html
<link rel="canonical" href="https://example.com/ampstory">
<link rel="amphtml" href="https://example.com/">
```
And in https://example.com/ 
```html
<link rel="canonical" href="https://example.com/ampstory">
<link rel="amphtml" href="https://example.com/">
```

Which is correct?

**Comment by rrjanbiah** [comment]
Bump! Apologies..

**Comment by newmuis** [comment]
The `rel="amphtml"` pairing model is not supported for stories.

If https://example.com/ is also a story, but not using the AMP story format, you should be able to just use the canonical link on both pages to whichever version should be canonical (but as the snippet you've quoted says, consider making the AMP story canonical).

If https://example.com/ is not a story (e.g. an article, a landing page, a video, etc), then the two documents likely just shouldn't be linked, as their contents are different.

**Comment by rrjanbiah** [comment]
@newmuis Thanks a lot. Apologies for missing your reply.

But, IM*H*O:

> is not a story (e.g. an article, a landing page, a video, etc)

Unfortunately, the 'story' needs to clearly defined. For example, https://makestories.io/ SEO part allows you to add 'article' JSON-LD

Thanks again for your reply. Much appreciated.

**Comment by newmuis** [comment]
"Story" based on the actual content, not any metadata present within the document.  There's no concrete definition, but I think I would say if you have to ask, it's not a story.

Of course, story or not, you're always free to just not look the documents.

**Comment by rrjanbiah** [comment]
@newmuis Thank you!
