### ISSUE TITLE
amp-analytics cannot handle multibyte characters in vars

### ISSUE THREAD

**Issue by aayusharyan** [ampproject/amphtml#27308]
## What's the issue?
When I add any Japanese Character to the Vars part of amp-analytics. It converts it into `?`
 in the Request. But if I use that in another variable. (Let's take `title` for example), it sends it just as it should.

## How do we reproduce the issue?

I am using this config, it can be reproduced with this.
 ```
<script type="application/json">
    {	
		"requests": {
            "base": "https://${host}/b/ss/${reportSuites}/1/amp/s${random}",
            "pageView": "${base}?AQB=1&pageName=${pageName}&g=${pageURL}&ch=${channel}"
        },
		 "vars": {
            "host": "xxxxxxx.com",
            "reportSuites": "xxxxxxxx",
        },
        "triggers": {
            "pageLoad": {
                "on": "visible",
                "request": "pageView",
                "vars": {
                    "pageName": "Name",
                    "pageURL": "abcd.com",
                    "channel": "的コ",
                }
            }
        }
    }
</script>

```
Here, instead of hardcoded Japanese, if I add that to Title of the Page and use `${title}`, it works as expected.

## What browsers are affected?

All Browsers

## Which AMP version is affected?

I am not sure if it is new or not, but I am experiencing it at Version 2003101714470.

**Comment by micajuine-ho** [comment]
Hi @aayusharyan, thank you for this bug report. I am not able to reproduce this error.

When I set the title of my test page to `"的コ的コ"` and use the `${title}` variable in my request, I see that it still gets encoded. 

Can you provide a test webpage that demonstrates this bug?

**Comment by aayusharyan** [comment]
@micajuine-ho 
Exactly... If you use like `${title}`, it works, however, if you send it directly, like `"channel": "的コ",` in the vars, then it breaks.

**Comment by micajuine-ho** [comment]
Hi @aayusharyan, maybe I was being unclear. 

I created a test page, and set the `<title>Ad Visible 的コ</title>`, then in the request I use `title=${title}` as well as `japanese=${japanese}` and the resulting request I get is:

`/test/manual/amp-analytics/title=Ad%20visible%20%E7%9A%84%E3%82%B3&japanese=%E7%9A%84%E3%82%B3`

which when decoded using utf8 turns into:
`/test/manual/amp-analytics/title=Ad visible 的コ&japanese=的コ`

This seems to be working as intended. Can you please provide a webpage to demonstrate your problem?
