### ISSUE TITLE
amp-position-observer: update docs to cover all attributes

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#27317]
The attributes section is currently empty. It's probably worth to revisit the structure of the whole doc as well. Might be worth explaining how the viewport-margin attribute works, and how it's different from IntersectionObserver's rootMargin. 

//cc @CrystalOnScript @ampproject/wg-ui-and-a11y

**Comment by CrystalOnScript** [comment]
Any chance the lack of attributes might be an amp.dev issue? I'm seeing them on the GH page: https://docs.google.com/document/d/1Vr7WSAu4-nGP3x7mC16xYOhuZeXZ3Kz4JtLmoFL9dnw/edit?ts=5e6b4238#bookmark=id.ppm9x0pshr8a

Although, it would be resolved if migrated to the template.

**Comment by sebastianbenz** [comment]
Hah! We should do both, fix the docs and the amp.dev importer.  I've filed https://github.com/ampproject/amp.dev/issues/3732 for amp.dev.
