### ISSUE TITLE
Clarify <track> support in <amp-video>

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#2731]
Is [`<track>`](http://www.w3schools.com/tags/tag_track.asp) supported in `amp-video`?

If so, we should update the [documentation](https://www.ampproject.org/docs/reference/amp-video.html) to make this more explicit.

If not, could we add support?

**Comment by erwinmombay** [comment]
https://github.com/ampproject/amphtml/releases think it got added pretty recently

**Comment by rudygalfi** [comment]
Ah, yes, in https://github.com/ampproject/amphtml/releases/tag/1458255876469.

**Comment by dvoytenko** [comment]
Correct.

**Comment by Gregable** [comment]
That's not correct. Track was added as allowed inside a `<video>` tag, not an `<amp-video>` tag. The `<video>` tag is a corner case really, as it in turn is only allowed inside a `<noscript>` tag.

If `<amp-video>` is supposed to support `<track>`, we should update the docs and validator.

**Comment by dvoytenko** [comment]
Sounds good. Let's update the validator. Over to you, @Gregable

**Comment by Gregable** [comment]
Sounds good. Please update the spec with any constraints on attributes as well. For `<video>` we allow:

- `src`, must be https absolute.
- `default`, supports no value
- `kind`, `label`, `srcset` with any values
- globally allowed attrs like `class`

Also, should we allow track for `<amp-audio>`?

**Comment by dvoytenko** [comment]
Yes, `<track>` should be allowed for both video and audio. The allowed attributes and additional constraints are:

- `default`
- `kind`: a enum of `{subtitles, captions, descriptions, chapters, metadata}`
- `label`
- `src` - only HTTPS allowed
- `srclang` - Must be present when `kind=subtitles`

**Comment by rudygalfi** [comment]
Pushing into next milestone

**Comment by Gregable** [comment]
This is live everywhere.
