### ISSUE TITLE
Layout promises never resolve when elements are destroyed before load fired

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#2732]
If the user load an article with say Instagram embeds and then swipe to move the the next one quickly and then swipe back to that article the Instagram embed will never load if the instagram layout promise never resolved the first time.

The reason this happen is that runtime will never schedule the element for a layout again because the first layout is still in our `exec` queue and will never exit because the first `loadPromise` will never resolve or error.

This is specially critical on slower connections where resolving the load promise for iframes might take along time and users navigate away from the document before that happens.

## How do we reproduce the issue?
I haven't tried to reproduce this on search carousel, but in theory it should be reproducible there. I was able to reproduce this issue on the examples/viewer.html setup with `amp-instagram.html` example set as the 2nd viewer.
1. In the viewer.html navigate to 2nd (instagram example) viewer and quickly navigate back to another one
2. This will force unlayout for all instagram elements 
3. Now go back to 2nd viewer and notice instagram posts will never load
4. If you look in the console, the `exec` queue will always have the same number of never "ending" tasks

I'll try to reproduce this on carousel as well. But in general we need to account for removing DOM before the layout promise resolve.

**Comment by mkhatib** [comment]
I've done some more testing on this yesterday and wasn't able to reproduce the blocking behavior, although it did seem that I was able to keep stacking tasks inside exec that doesn't end - but even with that the element managed to render correctly. Will do some more testing on this and see if it is no longer a problem.

**Comment by mkhatib** [comment]
Was able to reproduce. I was having troubles reproducing because I was using `amp-instagram` as an example, and in its current setup its "load promise" is really the load promise for the image that it's prerendering. Was able to reproduce with `amp-brightcove` instead. Will send a PR.

**Comment by rudygalfi** [comment]
Rolling this into next milestone.
