### ISSUE TITLE
Allow selection of past dates on amp-date-picker 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amphtml#27322]
## Describe the new feature or change to an existing feature you'd like to see

I would like to be able to select past dates on [amp-date-picker](https://amp.dev/documentation/components/amp-date-picker/?format=websites). Current implementation only allows me to select future dates. Selecting past dates would be useful for:

- Logging previously taken vacation / sick days
- Tracking / selecting past events, such as disasters or festivals
- Requesting a statement from your bank account

Maybe add an attribute such as `allow-past-selection` 

## Describe alternatives you've considered

Time travel into the past a day before what you would like to select from amp-date-picker.

**Comment by caroqliu** [comment]
@CrystalOnScript Thanks for filing this issue! I had begun implementing `allow-past-selection`, but I actually now think [`min`](https://amp.dev/documentation/components/amp-date-picker/?format=websites#min) suffices for your stated use cases. What do you think?

**Comment by CrystalOnScript** [comment]
Thanks for answering @caroqliu! Has that always been there? I think it will fit the need, I'll looking into adding guidance around it :)

**Comment by caroqliu** [comment]
Yes it has! Sounds good. Closing the issue.
