### ISSUE TITLE
amp-consent triggering layout shift causing CLS to drop

### ISSUE THREAD

**Issue by martinschierle** [ampproject/amphtml#27329]
## What's the issue?
amp-consent seems to trigger layout shifts

## How do we reproduce the issue?

Look e.g. at this URL:
https://rom--ausfluege-de.cdn.ampproject.org/c/s/rom-ausfluege.de/eintritt-vatikan/amp/

* Set Chrome DevTools to 3g and slow CPU
* In DevTools->Rendering activate checkbox for 'layout shift regions'
* Set network to disable cache
* Reload page, look out for the blue flashes - you will see them within the consent popup

Screenshot with the blue overlay indicating the layout flash is here:

![image](https://user-images.githubusercontent.com/23057458/77174130-dea76980-6ac0-11ea-860c-7e2e1e903d12.png)

**Comment by micajuine-ho** [comment]
Closed via #26819
