### ISSUE TITLE
[AMP-STORY-PLAYER] Feature Request : Event from the player

### ISSUE THREAD

**Issue by edoudou** [ampproject/amphtml#27332]
## Description

We need to get information from the player. 

## Solution

Via Event, or via callbacks, we need to be able to get the following informations : 
- The user finished the last story
- The user changed stories
- Processed Gesture (Propagate gesture events when they have no impact on the story. Examples : propagate Swipe Up if there is no Page Attachment, Swipe Down if there is no Page attachment open in the story, etc)

**Comment by edoudou** [comment]
I also opened 2 more feature request for amp-story-player : 
- https://github.com/ampproject/amphtml/issues/27333
- https://github.com/ampproject/amphtml/issues/27331

**Comment by gmajoulet** [comment]
Tracked in https://github.com/ampproject/amphtml/issues/28416
