### ISSUE TITLE
amp-ad triggering layout shifts, causing CLS to increase

### ISSUE THREAD

**Issue by martinschierle** [ampproject/amphtml#27330]
## What's the issue?
amp-ad if used in top-slots seem to push content down, causing layout shifts. It isn't visible, but can be seen by devtools debug overlays

## How do we reproduce the issue?

* Set DevTools to disable cache, 3g, cpu throttle
* Set DevTools to highlight layout shifts (devtools--> Rendering)
* Load [this url](https://www-alaraby-co-uk.cdn.ampproject.org/c/s/www.alaraby.co.uk/amp//politics/2019/5/13/%D8%A7%D9%84%D9%82%D8%B6%D8%A7%D8%A1-%D8%A7%D9%84%D8%A5%D8%B3%D8%B1%D8%A7%D8%A6%D9%8A%D9%84%D9%8A-%D9%85%D8%A7%D8%B6-%D9%81%D9%8A-%D8%AA%D8%A8%D8%B1%D8%A6%D8%A9-%D9%85%D8%B1%D8%AA%D9%83%D8%A8%D9%8A-%D9%85%D8%AD%D8%B1%D9%82%D8%A9-%D8%B9%D8%A7%D8%A6%D9%84%D8%A9-%D8%AF%D9%88%D8%A7%D8%A8%D8%B4%D8%A9)

Look out for the blue flash across all content below the ad:

![image](https://user-images.githubusercontent.com/23057458/77174877-09de8880-6ac2-11ea-9720-b7ed0ec7a5c3.png)

Disclaimer - I can't proof the ad is at fault here, but seems like the likely root cause. Alternatively it might also be something with the sidebar overlay.

**Comment by kevinkimball** [comment]
@martinschierle I don't believe this is amp-ad related. I do see a warning related to the amp-sidebar usage (relating to where it is in the DOM). Does the issue persist if that is fixed?

**Comment by lannka** [comment]
Sorry I failed to repro this anymore. Feel free to reopen.
