### ISSUE TITLE
amp-mustache: Loosen restrictions on allowed unescaped tags

### ISSUE THREAD

**Issue by Noah-Lc** [ampproject/amphtml#27344]
## What's the feature

Allow displaying data as an HTML

## More details

I fetch data to show an article by amp-list and I'm using 3 mustaches but as you know three mustaches support only some tags, for example, my article has pictures with amp-img and titles with h2 and h3. I can't display them using three mustaches.

## Example

here is an example of JSON that I'm using
`
{
  "items": [
    {
      "title": "How many calories an adult needs per day",
      "thumbnail": "/img/blog_23-495x320.jpg",
      "content": "<h3>Title</h3>\n<p>This is text.</p>\n<amp-img layout=\"responsive\" src=\"/blog_12-1024x683.jpg\" width=\"1600\" height=\"1067\"></amp-img>"
    }
  ]
}
`

**Comment by caroqliu** [comment]
You should be able to use unescaped HTML with `{{{` [under the documented restrictions](https://amp.dev/documentation/components/amp-mustache/#restrictions).

It sounds like it is stripping `<h3>` and `<amp-img>` tags -- are there others you want to request to be allowed?

**Comment by caroqliu** [comment]
Anyway IIUC the changes required are to add the desired tags to this list:
https://github.com/ampproject/amphtml/blob/master/src/purifier/sanitation.js#L120

**Comment by THE-VR7** [comment]
Hello. I am new  and would love to contribute.
I would like to fix this issue, if no one is already on it.

**Comment by caroqliu** [comment]
You're welcome to make this contribution once there is more clarity on what desired tags are being requested. :)

**Comment by Noah-Lc** [comment]
You know most of who using amp now they are focused to get a full SEO website, like in my case I'm trying to build a website using AMP so when I want to show articles I need some tags to respect SEO rules like H1, H2, BLOCKQUOTE, and also amp-img to display pictures inside an article.

**Comment by nainar** [comment]
@THE-VR7 are you able to create a PR for h1, h2, h3 and `<amp-img>` tags?

**Comment by mnjit20** [comment]
@caroqliu @nainar : i can create a PR i will suggest it should allow h1, h2, h3, h4, h5; 

> Anyway IIUC the changes required are to [add the desired tags to this list](https://github.com/ampproject/amphtml/blob/master/src/purifier/sanitation.js#L120). #26345 is an exemplary PR which allowed `col`.

@caroqliu : I am not able to locate this purifier directory in the current repo.
I was trying to add these tags to fix this. Could you help in locating this file.

exmaple: https://github.com/ampproject/amphtml/blob/master/ error 500

**Comment by caroqliu** [comment]
This is the section: https://github.com/ampproject/amphtml/blob/3ad4eebad8e2e2a89c4244c28e916902b2a721c2/src/purifier/sanitation.js#L114-L121

**Comment by nickFalcone** [comment]
Hi @caroqliu, I attempted to allow `<h1>` `<h2>` `<h3>` and `<amp-img>` tags to be used in `<amp-mustache>` templates by following your work in #26345. I created a template in examples/amp-list.amp.html based on @Noah-Lc 's original example.

I see the heading tags and `<amp-img>` render in the example as expected, but am a bit stuck on my test for amp-mustache 0.1 (the same test passes for amp-mustache 0.2)

My questions are:

- Would such a test need to be added for 0.1 if this version is deprecated?
- Is there still interest in allowing `<h1>` `<h2>` `<h3>` and `<amp-img>` in triple mustache?
- If both above are affirmative, I'd be happy to share the test I've come up with and receive feedback.

Thanks!

**Comment by caroqliu** [comment]
@dvoytenko may be more familiar with the context, but I would assume that if 0.1 version is deprecated, it is reasonable not to maintain it in lock step with 0.2. Unless others disagree, free to support `<h1>`, `<h2>`, `<h3>`, and  `<amp-img>` in 0.2 exclusively.

It does look like both versions rely on `TRIPLE_MUSTACHE_ALLOWLISTED_TAGS`, so wouldn't adding to this list for 0.2 also impact 0.1?

**Comment by nickFalcone** [comment]
> wouldn't adding to this list for 0.2 also impact 0.1?
Yes, both versions rely on `TRIPLE_MUSTACHE_ALLOWLISTED_TAGS` but it appears that the sanitization process is different. Running `gulp --extensions_from=examples/amp-list.amp.html` with amp-mustache 0.2 rendered the amp-img, however running with amp-mustache 0.1 did not. 

It looks like 0.1 is using [Caja](https://developers.google.com/caja) (to be archived January 31st, 2021) while 0.2 uses dompurify.

**Comment by nickFalcone** [comment]
Hi @caroqliu & @dvoytenko, I opened a draft PR to allow the additional HTML tags.  If it looks ok at first glance, I will mark it ready for review.  Thanks!
