### ISSUE TITLE
amp-script: Clearer error for form element mutations

### ISSUE THREAD

**Issue by morsssss** [ampproject/amphtml#27342]
If you try to mutate a form element in an `<amp-script>` element that doesn't include the attribute `sandbox="allow-forms"`, you get the error:

`[amp-script] Form elements ({element}) are not allowed without sandbox="allow-forms".`

(where _(element}_ may be, for example, "button")

I'd suggest instead something like:

`[amp-script] Form elements ({element}) cannot be mutated unless you include the attribute sandbox="allow-forms".`

Looks like that message is [here](https://github.com/ampproject/amphtml/blob/28638cb03bad2f5cf89565c7b0d11e469875060f/extensions/amp-script/0.1/amp-script.js#L667) in the code. If folks think my message looks good, I could... just... submit a PR?

**Comment by choumx** [comment]
Fixed in #27490.
