### ISSUE TITLE
Support validator for amp-jwplayer

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#2734]
Please add validator support for jwplayer described in https://github.com/ampproject/amphtml/blob/master/extensions/amp-jwplayer/amp-jwplayer.md.

The parent issue is #2125

**Comment by honeybadgerdontcare** [comment]
Could someone provide clarification about what layouts are supported?

The documentation at https://github.com/ampproject/amphtml/blob/master/extensions/amp-jwplayer/amp-jwplayer.md states several errors for layouts:
IMPLIED_LAYOUT_INVALID	Error thrown when implied layout is set to CONTAINER; this layout type isn't supported.
IMPLIED_LAYOUT_INVALID	Error thrown when implied layout is set to CONTAINER; this layout type isn't supported. (obviously a dupe)
SPECIFIED_LAYOUT_INVALID	Error thrown when specified layout is set to CONTAINER; this layout type isn't supported.

**Comment by honeybadgerdontcare** [comment]
@pablos1 
Could you provide the requirements to a `data-account` value since this is required according to the errors? And could you update the Examples to include a "valid" data-account.

Thank you.

**Comment by pablos1** [comment]
@honeybadgerdontcare looks like we had a typo in the documentation.  It should be `data-player-id` that's required, not `data-account`.  Should I create a PR for that?

As for the layout errors, the extension uses the `isLayoutSizeDefined` from `/src/layout`; the error messages were copy-pasted from another module that uses that validator.

**Comment by honeybadgerdontcare** [comment]
@pablos1 Yeah, go ahead and do another PR to make the documentation in line with what should be accepted.

**Comment by pablos1** [comment]
@honeybadgerdontcare PR is in.  Let me know if there's anything else needed.

**Comment by rudygalfi** [comment]
Closed via #2740.

**Comment by dvoytenko** [comment]
`isLayoutSizeDefined` supports `fixed`, `fixed-height`, `responsive` and `fill` layouts.

**Comment by Gregable** [comment]
This validator change will be live in the chrome dev console messages within an hour or so.
