### ISSUE TITLE
amp-story-player not working on old Edge browser

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#27358]
## What's the issue?

The `amp-story-player` throws an error in Edge (old non-chromium based Edge)
The error thrown is `Object doesn't support property or method 'attachShadow'`

## How do we reproduce the issue?

Add a story to an amp-story-player and open in Edge

## What browsers are affected?

Edge < Chromium based version

## Which AMP version is affected?

Probably all amp-story-player versions

**Comment by Enriqe** [comment]
Thanks for the report!

It looks like older Edge browsers don't support shadow root, I'll add a polyfill.

**Comment by cpauwels** [comment]
Any updates on this? Older Edge browsers are still quite prevalent, especially on company devices that aren't updated very often 😅

**Comment by Enriqe** [comment]
Hey @cpauwels do you have numbers on how many of your users are using this specific version of Edge, so I can prioritize accordingly?

[statcounter](https://gs.statcounter.com/browser-market-share) shows 2.19% of market share for Edge legacy, for a point of reference.

**Comment by cpauwels** [comment]
@Enriqe Unfortunately for our users it's still quite common, as it's often the only browser available on work laptops for users who don't have the rights to update to the latest Chromium-based Edge or install Chrome or Firefox.

Here are some statcounter numbers closer to home.

US: 3.7%
BE: 4.76%
UK: 4.33%

These are not insignificant IMO. Especially when considering desktop traffic, where the `amp-story-player` is more likely to be used. For desktop-only the figures are

US: 7.9%
BE: 8.01%
UK: 9.2%

This becomes quite the issue if 1 out of 11 desktop users in the UK doesn't see the story rendered.
