### ISSUE TITLE
Allow ES6 Structures?

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#27362]
In https://github.com/ampproject/amphtml/issues/6551, we decided to forbid all of ES6 data structures. According to [caniuse](https://caniuse.com/), some of them have widespread browser support.

#### Can we loosen the restriction on these:
- [WeakMap](https://caniuse.com/#feat=mdn-javascript_builtins_weakmap): allow everything.
- [Set](https://caniuse.com/#search=built-in%3A%20set): allow everything.
- [Map](https://caniuse.com/#search=built-in%3A%20map): allow everything except `.keys()` because ie11 does not support it.

One potential pitfall is IE11's `Map.prototype.set`, `WeakMap.prototype.set`, and `Set.prototype.add`. They return undefined instead of the collection. We may want to create a rule that guards against using the return value of these functions.

#### And continue to forbid:
- [WeakSet](https://caniuse.com/#feat=mdn-javascript_builtins_weakset): no ie11 support
- [Symbol](https://caniuse.com/#search=built-in%3A%20Symbol): no ie11 support

cc @ampproject/wg-runtime

**Comment by choumx** [comment]
We should also check UC browser support: https://amp.dev/support/faq/supported-browsers/

**Comment by kristoferbaxter** [comment]
@jridgewell added a set of changes for Map allowing it in the codebase recently.

See here: https://github.com/ampproject/amphtml/pull/26996

**Comment by samouri** [comment]
> A lot of these rules can be reconsidered once we are shipping module based output to the vast majority of users (read: very very soon).

Would it also be a reasonable time to start allowing for `async/await` syntax as well?
