### ISSUE TITLE
Investigate amp-subscription's usage of amp-access expressions

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#27364]
**summary**

While working on https://github.com/ampproject/amphtml/pull/27359, I noticed that `local-subscription-platform-renderer` directly calls the amp-access expression evaluator. Within that PR, we created a cache for amp-access expression evaluations, but I left out `amp-subscriptions` because I'm unfamiliar with the use case.

Should we also cache expression evals for `amp-subscription`?

cc @ampproject/wg-runtime

**Comment by jpettitt** [comment]
Short answer: yes that would be good.

Longer answer: there may be some edge cases where the underlying data changes, I need to go look at the code and confirm there are no edge cases where one service resolves, we render, then another service resolves which may change things.
