### ISSUE TITLE
Availability of variable substitution in other components.

### ISSUE THREAD

**Issue by VasudevHarshal-123** [ampproject/amphtml#27398]
## Describe the new feature or change to an existing feature you'd like to see
[AMP HTML URL Variable Substitutions](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md) can be made available for other components. These features are available in `<amp-analytics>` `<amp-pixel>` etc but in these components, it is compulsory to send these values to a URL, that's what the name says, but making them available to other components such as <amp-script> without a compulsion to send it to a URL will help to make front-end projects.

**Comment by njy** [comment]
Absolutely agree: I recently needed to use just a simple RANDOM variable substitution in the data-tag attribute (vast url) but it didn't work.
I think, given the almost total scripting limits of AMP, this should be available almost everywhere.
