### ISSUE TITLE
I2I: Bisect utility to identify performance regression

### ISSUE THREAD

**Issue by powerivq** [ampproject/amphtml#27402]
## Summary
Inabox runtime is intended for ad on a non-amp page that might be non-cooperative, as compared to amp pages. We do not want to yield unnecessarily to non-amp page because that compromises the ad performance for publishers and do not necessarily result in better user experience for users. There is a performance regression test added to gate the regressions in this means.

## Design document
A new command line tool is proposed to be added to this repo as below:
`gulp dig --cmd="gulp performance {args}" --begin={commitSha1} --end={commitSha2}`

What it will do is to bisect all commits between the two given commit SHAs and find out the first commit where `gulp performance` exceeds the permissible threshold.

The drawback of doing a bisect is that the performance is monotonous over time, so it does not guarantee the result is the most impactful one. Therefore, we plan to add an argument `--all`, that will force all commits to be tested.

Initially, only `gulp performance` is supported. We might want to expand it to unit tests, etc.

## Motivation
Because the regression test is expected to run daily, not per commit, whenever a regression is found, we still need human to find out which one of the commits is responsible for it.

## Launch tracker

/cc @ampproject/wg-infra

**Comment by rcebulko** [comment]
If we're already running `gulp performance` on every commit as it's merged, shouldn't we already have this data available in some way that we could query more easily?

**Comment by powerivq** [comment]
@rcebulko 

We prefer that but initially we were told there is resource constraints preventing it from realizing. Today, Yuxuan, Mica and I synced with esther and it seems possible to run it on each commit after merging to master. We'll try this approach first and I am putting this on hold for now.

**Comment by kristoferbaxter** [comment]
There are resource constraints holding us from running per commit right now. Have we ensured that we're comfortable with per-commit checks?

**Comment by estherkim** [comment]
Not yet, but we can give it a try with a small set of pages on master builds. It will help me estimate how long the job might take, and we'll reassess when nightly builds become available.
