### ISSUE TITLE
amp-base-carousel prev-arrow not working from last slide

### ISSUE THREAD

**Issue by robinvanopstal** [ampproject/amphtml#27403]
When at the last slide of an `amp-base-carousel`, with more than one visible slide, its `next-arrow` can still be clicked. If done so the `prev-arrow` stops working.

https://jsfiddle.net/ro6invanopstal/1s3ctxz9/

@sebastianbenz

**Comment by chrjs75** [comment]
I have the same issue. The next arrow button is not disabled (i.e. the `disabled` attribute is not added in the HTML) when the carousel reach the end, so it causes malfunctions if clicked.
The  `disabled` attribute seems to be properly set in the prev button, at least until the broken next button is clicked after reaching the end.
