### ISSUE TITLE
An amp-ad with amp-access-hide that is made visible doesn't actually appear until window is resized

### ISSUE THREAD

**Issue by kushal** [ampproject/amphtml#2741]
## How do we reproduce the issue?

See http://kushaldave.com/ampadbug.html
After the fallback access response is loaded, the box for the ad appears but not the ad.
Try resizing the window and the ad appears.

## What browsers are affected?

Seen in Chrome and Safari.

## Which AMP version is affected?

Seen in version 1458430572640. Unsure if it's new.

**Comment by dvoytenko** [comment]
Thanks @kushal , I will take a look right away. One confirmation - is the `amp-access-hide` on the actual `amp-ad` or on one of its parents? Is there any chance you can post the relevant source fragment?

**Comment by dvoytenko** [comment]
@kushal I think I reproduced the issue. It looks to only happen when `amp-access-hide` is on the `amp-ad` tag itself. I will fix it shortly. In the meantime, the workaround is to put `amp-ad` inside the DIV and move the `amp-access`/`amp-access-hide` to that DIV. Let me know if you see something different.

**Comment by dvoytenko** [comment]
Fixed via #2748. It will be in canary this Thursday and in PROD the following Thursday. Please use the recommended workaround in the meantime.

**Comment by kushal** [comment]
Awesome, thank you!
