### ISSUE TITLE
Carousel Slider doesn't actually preload next slide

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#2742]
The problem seems to be the fact that the next slide is always `display:none` and hence `isDisplayed() => false`. Because of this the `schedulePreload` call doesn't actually schedule anything because of the condition `isDisplayed` not satisfied.

### Reproduce by
1. Open carousel.html example page.
2. Inspect the slider carousel.
3. Notice that the next slide didn't render the image

To reproduce visually, remove the 2nd carousel from the page, disable cache and throttle the network to Good 2G and try to navigate the carousel, notice the loading dots when clicking next arrow.

**Comment by mkhatib** [comment]
I'll try to address this in the prerender work

**Comment by rudygalfi** [comment]
@mkhatib slotting this into next milestone. Please move if needed.

**Comment by mkhatib** [comment]
Thanks @rudygalfi.

To kick off the discussion, a possibility to fix this might be on how carousel is structured and how we display items in it. Maybe instead of display: none we explore a visibility solution. I'll look some more into this and possibly send a small document to get some more comments on this.

**Comment by rudygalfi** [comment]
cc @ericlindley-g

**Comment by dvoytenko** [comment]
The solution is definitely to set `display:block` and `visibility:hidden` on preloaded slides. This was the intention, but I think it must have regressed.

**Comment by ericlindley-g** [comment]
@dvoytenko @mkhatib Is this actively being worked on for the 4/14 milestone?

**Comment by dvoytenko** [comment]
I'd say, yes, let's aim to fix in this milestone.

**Comment by rudygalfi** [comment]
Rolling into next sprint? We've punted on this one before. Should we move to Backlog?
