### ISSUE TITLE
I2I: wg-caching should uniquely own validator changes

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#27440]
## Summary

We currently enforce: @ampproject/wg-caching owns _every_ `.protoascii`
We should also enforce: No one else can own _any_ `.protoascii`

For example, members of @ampproject/wg-ui-and-a11y can approve any validation changes in `extensions/`. Instead, they should not be able to.

## Motivation

- All validation changes should be approved by a member of @wg-caching. When a wider set of reviewers can approve, changes that have not been reviewed by the caching team can slip through the cracks. OWNERS bot should tightly enforce what is already expected for these types of changes.
- @ampproject/wg-caching members currently use the "Validator: Approved" label to convey approvals on PRs where OWNERS bot allows a wider set of reviewers to approve. This is confusing because it means they may use the label in lieu of a review in situations where their approval is actually required (i.e. changes in `validator/` instead of in `extensions/`) and blocking.

Both these points speak to establishing consistency, making it smoother to contribute and review validator changes, and increasing the baseline of confidence in validation changes.

### Approach 1: Restructure `extensions/`

We currently have
```
extensions
└───amp-foo
    └───0.1
    **/*: ampproject/wg-ui-and-a11y 
```

Instead we can have
```
extensions
└───amp-foo
    └───0.1
        └───validations
            **/*: ampproject/wg-caching
    **/*: ampproject/wg-ui-and-a11y 
```

Pros:

- Extensions with multiple versions inconsistently locate their validator rules. Having a common place for them introduces a better file tree structure for `extensions` long term.

Cons:

- Manual change to every ext folder
- Does not catch validation rules for extensions that have not been created yet

### Approach 2: Require approvals for all validation files top-down

We currently have this in root OWNERS:
```
# OWNERS.md
{
  pattern: '**/validator-*.{protoascii,html,out}',
  owners: [{name: 'ampproject/wg-caching', notify: true}],
},
```

Instead we could have something like this in root to signify precedence over other rules:
```
# OWNERS.md
{
  pattern: '**/validator-*.{protoascii,html,out}',
  owners: [{name: 'ampproject/wg-caching', notify: true, required: true}],
},
```

Pros:

- No intervention on our codebase structure
- Future-proofed for validation rules that may appear outside of `extensions/` or `validator/` later on

Cons:

~- OWNERs bot doesn't currently support this~

EDIT: This can be accomplished with `required: true` [per this comment](https://github.com/ampproject/amphtml/issues/27440#issuecomment-604691142), likely making this approach the more preferable one.

### Approach 3: Amend all `extensions/` OWNERS files

We currently have
```
# OWNERS.md
{
  rules: [
    {
      owners: [{name: 'ampproject/wg-ui-and-a11y'}],
    },
  ],
}
```

Instead we can have

```
# OWNERS.md
{
  rules: [
    {
      owners: [{name: 'ampproject/wg-ui-and-a11y'}],
    },
    {
      pattern: "*.protoascii",
      owners: [{ name: "ampproject/wg-caching" }],
    },
  ],
}
```

Pros:

- No intervention on our codebase structure

Cons: 

- Manual change to every OWNERs file that may share a directory with a `protoascii`
- Does not catch validation rules for extensions that have not been created yet

## Additional Notes
- Changes in `extensions/` can also be incorporated into the extension generator `gulp` task

/cc @rcebulko

**Comment by honeybadgerdontcare** [comment]
@rcebulko and I had discussed something similar previously for OWNERS bot. It looks like other WGs may want us to purely own these files as well. If possible I'd prefer to avoid Approach 1 since it's a massive move of files and others may be expecting these files to be where they currently are.

**Comment by rcebulko** [comment]
I think what you're looking for is the ability to make some reviewers required: https://github.com/ampproject/amp-github-apps/issues/516

Add `required: true` to the owners, ie.

```javascript
# OWNERS.md
{
  pattern: '**/validator-*.{protoascii,html,out}',
  owners: [{name: 'ampproject/wg-caching', required: true}],
},
```

**Comment by rcebulko** [comment]
With `required: true`, even when reviewers are owners because of other directory OWNERS rules, Owners Bot won't approve until someone in the required group has approved as well.

**Comment by caroqliu** [comment]
@rcebulko Is there a meaningful difference in presence of `required: true` in your example vs. Approach 3?

**Comment by caroqliu** [comment]
Ahh, nvm. Sounds like `required: true` is immediately suitable in Approach 2's as a replacement to the hypothetical `unique_owners` flag. Does this designation get overridden by more granular OWNERS files?

**Comment by rcebulko** [comment]
Yes, it's closer to Approach 2. The `required: true` option is top-down, and it's possible for there to be multiple different required owners; if any is missing, the PR will not pass the owners check, regardless of what other owners have approved. ie. `jridgewell` (top-level owner) could approve, but if there's a required owner, Owners Bot won't approve without their :heavy_check_mark:

**Comment by Gregable** [comment]
Discussed with wg-caching, everyone agreed that approach #2 sounds good. Let us know when the changes are in place, and we'll adjust our process.

**Comment by Gregable** [comment]
@rcebulko @caroqliu : this seems done, anything left before we close this issue?

**Comment by rcebulko** [comment]
Nope!
