### ISSUE TITLE
Dev mode on html element does not suppress validation errors for invalid attributes on the document element

### ISSUE THREAD

**Issue by westonruter** [ampproject/amphtml#27467]
## What's the issue?

When adding the `data-ampdevmode` attribute to the `html` element, I expect to be able to add an invalid attribute to that element and for its validation error to be suppressed by the validator. Nevertheless, in addition to the (expected) validation error being raised for `data-ampdevmode` for the document being in AMP dev mode, an unexpected validation error is also raised for the invalid attribute:

> ![image](https://user-images.githubusercontent.com/134745/77808737-e3809600-7049-11ea-8ce5-f23575fc33da.png)

This is not expected.

## How do we reproduce the issue?

Take the Hello World AMP page and add the `data-ampdevmode` and `onclick="console.info('You clicked me')"` attributes to the `html` document element:

```html
<!doctype html>
<html amp data-ampdevmode onclick="console.info('You clicked me')">
<head>
  <meta charset="utf-8">
  <title>My AMP Page</title>
  <link rel="canonical" href="self.html" />
  <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <style amp-custom>
    h1 {
      margin: 1rem;
    }
  </style>
</head>
<body>
  <h1>Hello AMPHTML World!</h1>
</body>
</html>
```

## Which AMP version is affected?

2003261442330

**Comment by westonruter** [comment]
cc @ampproject/wg-caching

**Comment by Gregable** [comment]
It seems open to interpretation as to what the correct behavior is. My mental model is that `data-ampdevmode` on the `html` tag by itself does not suppress any errors at all, it simply creates an error which allows us the validator to safely suppress errors elsewhere.

I do agree that this does not allow one to suppress errors on the `html` element, but similarly suppressing other errors on that element means that we have a different problem: there is no way to enable devmode on a subtree _without_ suppressing errors on the `html` element. It's unclear which issue would be more severe in the general case.

The original issue from which the design of this debugging feature came from did not have a need for the behavior you are requesting, so more context on the use of this behavior would help with designing a solution.

**Comment by westonruter** [comment]
I don't have a clear use case for needing to add invalid attributes to the `html` element. It's just something that didn't align with my interpretation of what the expected behavior would be. I also keep forgetting that `data-ampdevmode` applies to the entire subtree; in the WordPress plugin we currently require it to be added to every element for which invalid elements/attributes should not be sanitized out of the document.

I suppose the root issue here is that the `data-ampdevmode` attribute is serving two purposes. If it were split in two, one attribute used exclusively on the root element to indicate a dev mode document and another which is used on any elements intended to have the errors suppressed. In that case, in order to suppress validation errors for the `html` element itself, then there could be both of these attributes and not just the one.

This relates to [an idea](https://github.com/ampproject/amp-wp/issues/1921#issuecomment-527539680) from @schlessera:

> there should be a way for `data-ampdevmode` to mark an entire DOM subtree as having its validation errors ignored. This would avoid having to add the `data-ampdevmode` to each descendant element. This would require an update to AMP validator. Perhaps instead of `data-ampdevmode` being a boolean attribute, it could take an attribute value that defines the scope for ignoring the validation errors. Scope could be:
> 
> * Exclude the element and its attributes only.
> * Exclude the element only.
> * Exclude certain attributes.
> * Exclude the entire tree from that element and below.

This could also be indicated via values to the `data-ampdevmode` attribute as well.

**Comment by Gregable** [comment]
My vague recollection is that there are some other ideas for usage of this attribute in client-side runtime as well.

I'm definitely open to making changes to the semantics of this. A v2 `data-ampdevmode` if you will, though I'd probably just do a hard swap since it can't break any pages from validation.

It would be nice if someone could collect the suggestions and drive consensus on an ideal semantic design for this. I'll commit to implementation.

**Comment by Gregable** [comment]
@westonruter did you want to do more with this proposal? If there isn't a concrete plan, I might recommend that we close the issue in the meantime.

**Comment by westonruter** [comment]
I don't have an immediate plan, no.
