### ISSUE TITLE
Feature request: a `reader-comments` extended component

### ISSUE THREAD

**Issue by sketchytech** [ampproject/amphtml#2746]
## Feature request: A `reader-comments` extended component

Reader comments are a huge part of interaction with the news. There's not a news site on the Internet that doesn't have them. Could there be a way similar to `user-notifications` to GET and POST to a comments section? Making it something inbuilt into amp would provide the power to control how these are handled. I suspect otherwise news sites will work to display comments and also have people drawn away from the amp version to make comments. Therefore, it makes sense to include the functionality from the outset rather than wait for hacky implementations to be made. (Apologies if I've missed something in the documentation that allows for comments, I'm rather new to the spec.)

**Comment by ericlindley-g** [comment]
Thanks for the request—we're working on finding a good solution for comments, and don't yet support them natively in AMP, so you didn't miss anything :)

Though, we do have active issues around enabling comments, such as https://github.com/ampproject/amphtml/issues/2442

**Comment by dandv** [comment]
Disqus is one of the most popular commenting widgets. Would including it via an iframe do the job?

**Comment by ericlindley-g** [comment]
@dvoytenko — do you know if putting Disqus in an iframe would work? My understanding is that complexities around login for Disqus make it currently unsupported.

**Comment by seomaz** [comment]
what about facebook comment, i try to put on iframe, but facebook api dont work on sandobx iframe

**Comment by dvoytenko** [comment]
@ericlindley-g Correct. Iframe would work (I believe there are cases in the wild that do that already). But we don't have the full story with login integration. Alternative here would be to add AMP extension.

@seomaz That seems like a very reasonable request for Facebook to allow their embeds to work with sandbox - this is a critically important tech and been out for a while now.

**Comment by aghassemi** [comment]
There are multiple 3P commenting extensions in AMP. 

1P commenting system can be created with existing primitives but it a higher-level component for comments still a reasonable request. /cc @nainar
