### ISSUE TITLE
Support most recent amp-consent configuration in Stories

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#27469]
The amp.dev playground consent for Stories example was broken because it was using the most recent `amp-consent` examples.
Our Stories documentation is still providing a working code snippet, but we should support the newest `amp-consent` snippets so publishers can use the same configuration for regular AMP pages or Stories.

cf https://github.com/ampproject/amp.dev/pull/3776, the previous code should work too

cc @ampproject/wg-stories

**Comment by zhouyx** [comment]
In addition, `promptUISrc` is something you want to block in stories.
