### ISSUE TITLE
AMP4Email: Support scrollTo action

### ISSUE THREAD

**Issue by lichinshao** [ampproject/amphtml#27460]
## What's the issue?
AMP email: scrollTo functionality doesn't work on AMP email playground or in gmail client when you send a test email from playground. 

## How do we reproduce the issue?

1. copy code here, which is essentially amp list #2 example in playground with added srollTo top button. https://glitch.com/edit/#!/alert-mica-ticket
2. paste into AMP3Email playground: https://amp.gmail.dev/playground/
3. Observe bug when you scroll to the bottom and click on the "to top" button. Can also send a test email from playground and view bug in gmail client. 

## What browsers are affected?
amp4 email playground, gmail client.

**Comment by fstanis** [comment]
Unfortunately, scrolling in emails is a hard problem (this is a big issue for lightbox: #23170). The email is always fully in viewport, since it's rendered inside an iframe, so you'd need to scroll the parent page which is on a different origin.
