### ISSUE TITLE
Use of state value in amp-analytics.

### ISSUE THREAD

**Issue by VasudevHarshal-123** [ampproject/amphtml#27479]
## Describe the new feature or change to an existing feature you'd like to see
`<amp-analytics>` has [AMP HTML URL Variable Substitutions](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md) has lots of variables provided which one can use to send data to their server. But is there a way to send some values which the user has calculated on `<amp-script>` along with other data? 

## Describe alternatives you've considered
Allowing `<amp-analytics>` to access the value set in the state.

**Comment by samouri** [comment]
Apologies for the incredibly late reply!
This is a reasonable request.
We don't have implementing this on the radar, but are open to contributions.

The ability to retrieve values from `<amp-script>` is a recent addition, so this task should not be very large.
For anyone interested in this feature, feel free to reach out and I'd be happy to give implementation pointers.
