### ISSUE TITLE
<amp-next-page> v1.0: deep-parsing="false" attribute not working.

### ISSUE THREAD

**Issue by demianrenzulli** [ampproject/amphtml#27493]
## What's the issue?

According to the https://amp.dev/documentation/components/amp-next-page/#deep-parsing-(optional), setting `deep-parsing` attribute to `false` prevents the component from reading the JSON on the following page, a test was made where this behavior is not working as expected. As a result 3 articles are being rendered when 2 should be rendered instead.

## How do we reproduce the issue?

The following has implemented <amp-next-page> 1.0:

https://www.forbes.com/cdeleon/amp-infinite.html

Inspecting the inline JSON script, the deep-parsing is set to "false".
When scrolling, only the second article should be fetched, but 3 articles are being rendered instead.

## What browsers are affected?

Tested in Chrome 80.

## Which AMP version is affected?

The amp-next-page component 1.0 is being used.

cc // @cjdeleon62 @nainar

**Comment by wassgha** [comment]
Hey @demianrenzulli , thank you for reporting the bug. I've sent out a fix :)

**Comment by demianrenzulli** [comment]
That was fast! Thanks for confirming @wassgha!
