### ISSUE TITLE
Do not report CANCELED as errors in console.

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#2749]
See `error.cancelation()` API.

**Comment by Gregable** [comment]
@ericlindley-g , it looks like you added the "Related to: Validator" tag on this. Is this a validator issue? I would need some more context if it is.

**Comment by rudygalfi** [comment]
@Gregable I think it's mislabeled. Removing Validator label.

**Comment by ericlindley-g** [comment]
Mislabeled—sorry about that!

**Comment by erwinmombay** [comment]
i can't remember, ill have to double check.
