### ISSUE TITLE
Carousel 0.1: some slides occasionally jump one slide ahead on swiping

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#27503]
To repro:

* Search for "sfgate cayote"
* Select the article about cayotes on the streets
* Try to swipe carousel

Occasionally the carousel will jump one slide ahead.

**Comment by caroqliu** [comment]
Is this the same as #26249 ?

**Comment by dvoytenko** [comment]
Yes. Thanks for the dedupping. Closing this, but would be great to see the fix.
