### ISSUE TITLE
Feature request: sms protocol separator

### ISSUE THREAD

**Issue by iefserge** [ampproject/amphtml#2751]
Depending on the user device sms protocol links should use different separators ( `?`, `;` or `&` ). See http://stackoverflow.com/questions/6480462/how-to-pre-populate-the-sms-body-text-via-an-html-link/19126326#19126326

Would it be a good idea to add a dynamic placeholder for those links?

```
<a href="sms:SMS_SEPARATORbody=text"></a>
```

**Comment by dvoytenko** [comment]
@mkhatib please take a look. This is an interesting issue. Perhaps we can simply do replacement ourselves directly. Although currently we do not intercept the links when not iframe'd, but it's worth considering to reduce pain.

**Comment by mkhatib** [comment]
Interesting, yeah this possible. In general this would basically prevent default on sms links and then `open(replacedLink, a.target)`.

**Comment by adelinamart** [comment]
@ericlindley-g @aghassemi we should consider prioritizing this soon. Thanks

**Comment by aghassemi** [comment]
`amp-social-share` will be supporting SMS with https://github.com/ampproject/amphtml/pull/9365 . That provides a good alternative for this issue. 

Closing, feel free to reopen if SMS support in `amp-social-share` is not enough for your use-case.
