### ISSUE TITLE
🌸 Cherry-pick request for #27523 into #27511(Pending)

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#27524]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #27523 | #27501 |     **YES**     | **~YES~ NO** | **NO** | #27511                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?
We need to test the new error reporting end point and this also fixes it for us to be able to see module build errors.

# Mini-postmortem

No postmortem needed as there is no regression, this is just to fix a critical bug in the error reporting server as well as testing migration

## Summary
N/A

## Impact
N/A

## Action Items

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by erwinmombay** [comment]
cc @rsimha

**Comment by rsimha** [comment]
@erwinmombay Does this need to be CP'd to LTS? (The label doesn't match the description)

**Comment by rcebulko** [comment]
No, this should not be CP'd into LTS

**Comment by rcebulko** [comment]
#27501 is the first step in migrating to the new error-reporting endpoint, which is intentionally going to be a very slow, steady process (see https://github.com/ampproject/error-tracker/issues/112 for the migration plan/schedule). CP into Beta/Experimental will be enough to get useful error data for mjs, which is the reasoning for CP. We don't want to migrate Stable to the new error reporting until we've verified functionality in production on Beta/Experimental.

**Comment by rcebulko** [comment]
To add some context for historical purposes: The legacy error-reporting app drops non-JS stacktraces, making it impossible to monitor errors in the new MJS scripts. #27523 diverts 20% of standard error reporting and 100% of MJS error reporting to the new endpoint (part of the migration in https://github.com/ampproject/error-tracker/issues/112). If we CP'd into Stable, it would report 20% of errors to the new endpoint, which we are not yet confident enough in.

**Comment by erwinmombay** [comment]
im closing the request since there will be no need to cherry pick anymore as @rsimha is cutting a new canary and we only need this in canary.
