### ISSUE TITLE
🌸 Cherry-pick request for #27422 into #27390 (Complete)

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#27525]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #27422 | #27422 |     YES     | ~NO~ YES | NO | #27390                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

The rollback was missed from the release by accident.

## Why is an LTS cherry-pick needed?

The pre-revert never made PROD or LTS.

# Mini-postmortem

## Action Items

The original breaking #27319 was reverted. We should consider such reverts as "backlisted" and fail the branch if we try to include a blacklisted commit w/o its counterpart revert.

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by rcebulko** [comment]
If this is only CP into Beta and Experimental, can we remove the **Cherry-pick: Stable** and **Cherry-pick: LTS** labels?

**Comment by dvoytenko** [comment]
I believe it has been already done on Stable and never was deployed on LTS.

**Comment by rsimha** [comment]
Re-adding the Stable label, since this will go into beta/experimental and be included in stable later today when we roll forward.

**Comment by rsimha** [comment]
CP release [2004012158290](https://github.com/ampproject/amphtml/releases/tag/2004012158290) has been promoted to 1% and Stable.

**Comment by dvoytenko** [comment]
Added a proposal for this kind of problem: https://github.com/ampproject/wg-infra/issues/36
