### ISSUE TITLE
🌸 Cherry-pick request for #27521 into #27390 (Complete)

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#27534]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #27521 | #27521 |     **YES**     | **YES** | **NO** | #27390                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

New codepath for amp-list with layout=container breaks some existing AMP pages that use amp-list with infinite scroll. The fix keeps these paths mutually exclusive.

# Mini-postmortem

## Summary

The [new feature to support `layout=container` on `<amp-list>`](https://github.com/ampproject/amphtml/pull/27159) interfered with the pre-existing infinite scroll feature. The `amp-list` component follows the same codepath to render any items, regardless if it is static content, typical dynamic content, or size-managed infinite content. 

In AMP, the `container` layout type in particular stretches to the size of its contents. For amp-list with typical dynamic content, this can cause content jumping, and for infinite content this would break the existing size management. The new change managed this by locking the amp-list height to its current contents, rendering dynamic content, and unlocking its height only upon a successful call to `attemptChangeHeight`. This was put in place to prevent content jumping with dynamic content. Because this is an asynchronous call, the return types of nested calls for some codepaths had to be modified. 

Another piece to note: While `amp-list` did not explicitly support `layout=container` before the new feature, there were features in place to force `amp-list` to change its layer to container, namely the `is-layout-container` attribute and the `changeToLayoutContainer` action. In both cases, an amp-list that began with one layout type and switched to the container layout type could not be combined with the infinite scroll feature.

Because the pre-existing logic was in place to guard the two features, it was expected that the layout=container feature would roll out independently of existing usage.

amp-list in particular handles many special use cases, its codepaths often disentangling and re-entangling throughout its lifecycle, as with the single point of render that may delegate across the use cases at distinct branching off points. 

## Impact

- Some infinite scroll amp-lists displayed no content at all due to `Uncaught TypeError: Cannot read property 'then' of undefined`

## Action Items

- #27540: Add QA manual tests for amp-list 
- #27541: Add documentation that `layout=container` and infinite scroll are treated as mutually exclusive features

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by dvoytenko** [comment]
Approved

**Comment by cramforce** [comment]
Approved

**Comment by rsimha** [comment]
CP release [2004012158290](https://github.com/ampproject/amphtml/releases/tag/2004012158290) has been promoted to 1% and Stable.

**Comment by rsimha** [comment]
Reopening for post-mortem by @caroqliu

**Comment by caroqliu** [comment]
Post-mortem complete
