### ISSUE TITLE
[amp-story-player] Stories don't load in Firefox

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#27538]
## What's the issue?

The amp-story-player spinner spins forever and the story doesn't load. The error reported in the console is:

```
Error: failed to call initLogConstructor log.js:845:14
    buildCallback log.js:845
    loadPlayers amp-story-player-manager.js:104
    onload amp-story-player.js:21
```

## How do we reproduce the issue?

Embed a story in a page using the `amp-story-player` and open the page in Firefox. Example: https://story.tappable.dev/embed/stay-cultured-while-at-home

## What browsers are affected?

Firefox v73 and v74

## Which AMP version is affected?

amp-story-player is pretty new, so I'm guessing all of them.

**Comment by cpauwels** [comment]
Ping @Enriqe in case you didn't see this :)

**Comment by Enriqe** [comment]
Sorry, I didn't see this. Taking a look.
