### ISSUE TITLE
Buggy UI with amp-next-page and amp-fx-collection's float-in-top 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amphtml#27552]
## What's the issue?

I'm working on a mobile infinite scrolling experience with `amp-next-page` and `float-in-top` header using `amp-fx-collection`. The header scrolls away fine, but when I get to the an article rendered by `amp-next-page`, the header appears behind that articles content. See gif below. 

![next-page-gif](https://user-images.githubusercontent.com/23297417/78310847-f12f9300-7503-11ea-9926-b137cfbd0863.gif)

## How do we reproduce the issue?

Use `<amp-next-page>` version 1.0 and `amp-fx-collection` `float-in-top` together. Or click the link the glitch project I have made :)

[Glitch Project](https://glitch.com/edit/#!/cautious-puddle-polyanthus?path=index.html:1:0)

**Comment by CrystalOnScript** [comment]
Adding `z-index: 1` to the header CSS resolves this issue. Probably close?

**Comment by wassgha** [comment]
Closing, please let us know if the `z-index` doesn't fix this :)
