### ISSUE TITLE
🌸 Cherry-pick request for revert of #27159 and #27521 into #27555 release (Pending)

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#27554]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| https://github.com/ampproject/amphtml/commit/4923f7fb7320cde47acec98b0fbe2e5a0b10446f | https://github.com/ampproject/amphtml/commit/4923f7fb7320cde47acec98b0fbe2e5a0b10446f |     **YES**     | **YES**  | **NO**  | #27555                                                              |
| https://github.com/ampproject/amphtml/commit/e9b99069b755993824f0049470e590efa04c0e4e| https://github.com/ampproject/amphtml/commit/e9b99069b755993824f0049470e590efa04c0e4e|     **YES**     | **YES**  | **NO**  | #27555                                                              |
## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?
P0 - Breaks E-comm site B&H

# Mini-postmortem

## Summary

(1) Prior to explicitly supporting `layout=container`, amp-list included `is-layout-container` and `changeToLayoutContainer` features that changed an initial non-container layout to container without restriction. 

(2) Adding support for `layout=container` came with explicit guarantees around managed content jumping i.e. locking the visible styled height, attempting to re-height its dimensions, and only unlocking the styled height upon successful resize.

The increased restrictions introduced by (2) broke existing behavior of (1).

## Impact

- Any amp-list with content below it that relied on `is-layout-container` or `changeToLayoutContainer` to display overflow content

## Action Items

- #27540: Add QA manual test cases for amp-list

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by nainar** [comment]
@cramforce or @ampproject/wg-approvers to approve

**Comment by dvoytenko** [comment]
Ok. At this point i'm a bit confused about amp-list and layout=container. Didn't it come through for yesterday's cp?

**Comment by nainar** [comment]
#27521 was a fix for an edge case not covered in #27159 (a FR). 

For this cherry pick we are just reverting both so that we can start afresh.

**Comment by nainar** [comment]
FYI @erwinmombay has cut the stable release.

**Comment by dvoytenko** [comment]
Ok. Approved.

**Comment by caroqliu** [comment]
Post mortem complete
