### ISSUE TITLE
🐛Able to collapse ad in first viewport

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#27567]
## What's the issue?

If a requested ad does not fill we will try to toggle its fallback
https://github.com/ampproject/amphtml/blob/00a728570949e07236b5387d85f8cf1a75c1c157/extensions/amp-ad/0.1/amp-ad-ui.js#L111

The `BaseCustomElement.toggleFallback()` method will then add the class `amp-notsupported` https://github.com/ampproject/amphtml/blob/00a728570949e07236b5387d85f8cf1a75c1c157/src/custom-element.js#L1595

Some clever publishers will write a CSS selector that looks for this class and use it to collapse the ad element even when it is in the first viewport eg
```css
.amp-notsupported {
  max-height:1px;
  padding:0;
  opacity:0
}
```

## What browsers are affected?

All.

## Which AMP version is affected?

Goes back at least 3 years.

I propose that we change this class to use the `i-amphtml` prefix so that any CSS rules targeting this class will cause the ampdoc to become invalid.

@zhouyx Does this seem like a reasonable solution to you?

**Comment by zhouyx** [comment]
The class is applied to more components, not only ads. 
It looks like a class we introduced for publishers to customize on purpose. Any idea why we introduce it in the first place? 
Add @alanorozco and @jridgewell for opinion. 

FYI https://github.com/ampproject/amphtml/issues/7388#issuecomment-278396138

**Comment by jridgewell** [comment]
We definitely need to schedule a measure if this is happening. We could just set `min-height` with  `!important` to disable the collapsing.
