### ISSUE TITLE
Add Vkontake and Baidu to amp-social-share

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#2756]
### What you will need to know
- [`amp-social-share-config.js`](https://github.com/ampproject/amphtml/blob/c2be5ab1ecfde40a7337f6eeb57aad4328017b60/extensions/amp-social-share/0.1/amp-social-share-config.js)
- [`amp-social-share.js`](https://github.com/ampproject/amphtml/blob/c2be5ab1ecfde40a7337f6eeb57aad4328017b60/extensions/amp-social-share/0.1/amp-social-share.js)
- Documentation for Vkontake:  https://vk.com/dev/widget_share
- Documentation for Baidu: http://d.baidu.com/search/cang_help.html

### Background
We have a component called `<amp-social-share>`. We have default configurations (share link, icon, etc) for common components like facebook, twitter, pinterest, etc. 

### Motivation
From @jayston in #1201:

> Hi, sorry to jump into this discussion. We'd love to have social sharing buttons for our amp pages but our Audience is coming from Russia and Asia where Facebook and Twitter are not the leading social platforms. Would it be possible for you to add the Vkontakte sharing button? Baidu would also be a good addition but Weibo should already cover a big part of this user segment.
> 
> https://vk.com/dev/widget_share
> http://d.baidu.com/search/cang_help.html
> 
> vkontakte: http://vkontakte.ru/share.php?url=[URL]&title=[TITLE]&description=[DESCRIPTION]&image=[IMAGEURL]&noparse=true
> baidu: http://cang.baidu.com/do/add?iu=[URL]&it=[TITLE]

### The feature
The request is to add a default share configuration for Vkontakte and Baidu. You can do this by adding a Baidu / Vkontakte icon to [`amp-social-share.css`](https://github.com/ampproject/amphtml/blob/c2be5ab1ecfde40a7337f6eeb57aad4328017b60/extensions/amp-social-share/0.1/amp-social-share.css), and adding configurations to [`amp-social-share-config.js`](https://github.com/ampproject/amphtml/blob/c2be5ab1ecfde40a7337f6eeb57aad4328017b60/extensions/amp-social-share/0.1/amp-social-share-config.js). Don't forget to update the documentation with the default parameters too. =) 

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.  (If you [join the AMP Project](https://goo.gl/forms/T65peVtfQfEoDWeD3) we'll be able to assign this issue to you after you've claimed it.)
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] [Sign the Contributor License Agreement](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#contributor-license-agreement) before creating a Pull Request.  (If you are contributing code on behalf of a corporation start this process as early as possible.)
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review).  Mention `closes Issue #2756` in the description and tag @cathyxz for review.
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

**Comment by hkmaly** [comment]
Would it be possible to actually USE the width and height specified as opposed to hardcoding width 60px and height 44px as is now? I suppose I can override them, but then the images on buttons are too big.

**Comment by ericlindley-g** [comment]
@hkmaly, I've pulled your question into a separate issue here: #2843

**Comment by Lillian-wang** [comment]
Given issue #2946 has been merged, is there anything to do in this bug?

**Comment by ericlindley-g** [comment]
@Lillian-wang, as I understand it, there's still a small task to do, but it wouldn't add new functionality. We could make it simpler to share through Vkontake or Baidu by offering default icons, and make the documentation clear about what data-* attributes are accepted.
