### ISSUE TITLE
Add Github Action Windows Development Sanity Check

### ISSUE THREAD

**Issue by kristoferbaxter** [ampproject/amphtml#27570]
## Describe the new feature or change to an existing feature you'd like to see

Per https://github.com/ampproject/amphtml/pull/27520#issuecomment-608846344, I'd like to see a sanity check that commits to AMPHTML do not break the ability to develop the project on Windows machines.

## Describe alternatives you've considered

Do the same but on Travis.

**Comment by rsimha** [comment]
@kristoferbaxter I started working on this issue now that we are using GitHub actions for AMP testing. We can successfully run `gulp dist` on macOS and Linux using native closure compiler, but the Windows build is [broken](https://github.com/ampproject/amphtml/pull/29115/checks?check_run_id=846716418).

![image](https://user-images.githubusercontent.com/26553114/87073820-fa5b8a80-c1eb-11ea-97cf-e20cf8adadce.png)

I spun up a Windows VM and added some debugging, and it appears that [kristoferbaxter/amp-closure-compiler](https://github.com/kristoferbaxter/amp-closure-compiler/tree/master/packages) supports `darwin` and `linux` but not `win32`. Meanwhile, the Java closure compiler returns `JSC_PARSE_ERROR` for all JS files.

a) Are you familiar with those errors and do you have any idea where they originate?
b) Can we add windows support for native closure compiler?

/cc @jridgewell and @erwinmombay in case they know what's going on here.

**Comment by kristoferbaxter** [comment]
Apologies, am out on paternity leave.

We can add back in Windows support for the Graal native compiled version of Closure Compiler.

Sounds like a good task as we move the repository over to the ampproject scope.

**Comment by rsimha** [comment]
I see from [here](https://github.com/kristoferbaxter/amp-closure-compiler/blob/master/packages/google-closure-compiler/lib/utils.js#L19) that we don't currently have a windows codepath for the `gulp` plugin of our custom closure. Doing this after moving the repo to `@ampproject` SGTM.

Enjoy paternity leave 😃

**Comment by rsimha** [comment]
For posterity, the failures in https://github.com/ampproject/amphtml/issues/27570#issuecomment-656270218 were due to Windows using `\` and not `/` as a path separator. Since then, we've moved our compiler code to the `@ampproject` org, fixed the build on Windows, and added a Windows workflow to GH actions that runs tests on Edge and IE 11.

**Comment by rcebulko** [comment]
Also for posterity: the phrase "sanity-check" may fall under the umbrella of ableist language (see Google developer style guide on [writing inclusive documentation](https://developers.google.com/style/inclusive-documentation)). Possible substitutes include "check for completeness" or "validity check"
