### ISSUE TITLE
Invalid Value link 

### ISSUE THREAD

**Issue by samir2006h** [ampproject/amphtml#27580]
`<link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css' rel='stylesheet'/>`

The attribute 'href' in tag 'link rel=stylesheet for fonts' is set to the invalid value 

> 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css'.

**Comment by wassgha** [comment]
Please check https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/custom_fonts/ only select origins are allowed for link tags (known to be fast and reliable). For your use case, it's possible to use `use.fontawesome.com` instead:
```
<link href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" rel="stylesheet" type="text/css"/>
```

**Comment by wassgha** [comment]
Closing for now, feel free to reopen if there's still an issue
