### ISSUE TITLE
[amp-story-player] Load documents from the cache

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#27588]
Support loading the stories from the cache unless the publisher opts-out. 

API will look as following:

```
<amp-story-player> // does not load from the cache (the default)
<amp-story-player amp-cache="cdn.ampproject.org"> // loads from cdn.ampproject.org (explicitly)
<amp-story-player amp-cache="cdn.example.com"> // loads from cdn.example.com (explicitly)
```

/cc @ampproject/wg-stories

**Comment by gmajoulet** [comment]
SGTM!

Bikeshedding: should we explicitly call it `amp-cache`, as it's not any cache?

**Comment by newmuis** [comment]
What is the value for the `amp-cache` attr?  Is it the host?  Or protocol+host?  Either one?

**Comment by Enriqe** [comment]
I think just the host is fine, WDYT?

**Comment by kristoferbaxter** [comment]
What's "the cache" in the default case? Whatever is specified by v0?

**Comment by Enriqe** [comment]
@kristoferbaxter if no cache is specified explicitly by the publisher, we will load the documents from the origin (no cache). Since this is a standalone JS library, v0.js / AMP is not expected to be loaded in this context.

**Comment by kristoferbaxter** [comment]
If this is a standalone JS library, is there any reason to build it from `amphtml`? Sounds like a perfect candidate for a standalone repo.

**Comment by Enriqe** [comment]
Given that we have plans to support AMP in the near future, we think it's appropriate for it to live here
