### ISSUE TITLE
clean up local storage errors

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#2759]
some new errors cropping up that are mostly from webview 
- is iframed boolean (need to know if inside viewer)
- viewer url (possibly)

minor changes to possibly reduce errors:
- localstorage == null?
  - storage api/notification
  - cid usage

**Comment by rudygalfi** [comment]
@erwinmombay Can we downgrade this from High priority? Would this be fixed in the next milestone (next two weeks)?

**Comment by erwinmombay** [comment]
we have a partial fix in through https://github.com/ampproject/amphtml/pull/2775 but more work needs to be done.

**Comment by rudygalfi** [comment]
Do you think the additional work is urgent (next milestone) or we can take it up someday later (backlog)?

**Comment by erwinmombay** [comment]
this has been recategorized to expected errors.
