### ISSUE TITLE
amp-iframe : Feedback about the 600px restriction

### ISSUE THREAD

**Issue by teleservizi** [ampproject/amphtml#276]
from amp-iframe.md : "NOTE: We are currently looking for feedback as to how well this restriction works in practice."

My opinion is that until we have not customized the amp-ad and amp-video to properly work in our production environment, we should remove the 600px-from-top restriction

**Comment by riking** [comment]
I've got an iframe-at-the-top case.
I'm exploring AMP for [discourse](/discourse/discourse), and people have put embedded Google Forms links in the first post (if someone puts a link on its own line, we automatically embed it).

When this happens in the first post, of course, the iframe is shown in the first 600px of the page.

Here's an example page (heavy-js version) which would give the 600px error if shown as an AMP:
https://forum.riking.org/t/example-topic-with-a-google-forms-signup/280

**Comment by cramforce** [comment]
@riking I think the <amp-click-to-play> component would help here. Start with a generic "here is a form" marker and then open it on click. I realize this isn't ideal, but with AMP prefetching you won't be able to prefetch the form, so having a good placeholder is crucial.

**Comment by erwinmombay** [comment]
relevant -> https://github.com/ampproject/amphtml/issues/571

**Comment by riking** [comment]
Click-to-play looks good. Would classify each iframe embed as "lightweight" or "heavyweight" and put heavy ones behind a CTP, and light ones in the first post as well.

**Comment by cramforce** [comment]
#571 Is the related intent to implement. Will close this in favor of that bug.
