### ISSUE TITLE
text-decoration-skip-ink CSS property to be allowed in inline styles

### ISSUE THREAD

**Issue by danielstockton** [ampproject/amphtml#27606]
## Describe the new feature or change to an existing feature you'd like to see

AMP stories with code like `<p style="text-docration-skip-ink: auto;">test</p>` do not validate.

## Describe alternatives you've considered

We assign these elements an id and move the style into a `<style amp-custom>` which works and validates.
Therefore, there doesn't seem to be any reason to disallow this style inline.

## Additional context

Allowing this property inline would just make things a bit simpler for us, since we wouldn't need logic to hoist styles into a <style> tag at the top of the page.

**Comment by Gregable** [comment]
We don't currently validate any CSS properties in `<style amp-custom`>. That's a legacy thing. We'd like to apply the same list in inline style as `<style amp-custom>`.

Currently, this property doesn't appear supported in Safari. @dvoytenko , do you know how the policy on browser support would apply here?

At the moment, we also don't have support for selectively allowing properties per AMP format, so we'd need approval from @ampproject/wg-amp4email and @ampproject/wg-ads before proceeding.

**Comment by dvoytenko** [comment]
The `text-docration-skip-ink` is definitely fine to allow. We'll still keep this on a case-by-case basis, but purely stylistic properties like this that do not change the layout are definitely fine to add as soon as the spec is clear and at least one browser supports.

**Comment by choumx** [comment]
Looks fine for email.

**Comment by fstanis** [comment]
This might be an issue for some email clients (e.g. Gmail) since it's experimental / not widely supported.

**Comment by Gregable** [comment]
This has been complete for a while.
