### ISSUE TITLE
Design Review 2020-04-22 15:30 UTC (error issue creation, CSS in Bento, wg-stories)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#27601]
Time: [2020-04-22 15:30 UTC](https://www.timeanddate.com/worldclock/meeting.html?year=2020&month=04&day=22&iv=0) ([add to Google Calendar](http://www.google.com/calendar/event?action=TEMPLATE&text=AMP%20Project%20Design%20Review&dates=20200422T153000Z/20200422T163000Z&details=https%3A%2F%2Fbit.ly%2Famp-dr))
Location: [Video conference via Google Meet](https://bit.ly/amp-dr)

The AMP community holds weekly engineering [design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md).  **We encourage everyone in the community to participate in these design reviews.**

If you are interested in bringing your design to design review, read the [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md) and add a link to your design doc or issue by the Monday before your design review.

When attending a design review please read through the designs *before* the design review starts.  This allows us to spend more time on discussion of the design.

We rotate our design review between times that work better for different parts of the world as described in our [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md), but you are welcome to attend any design review.  If you cannot make any of the design reviews but have a design to discuss please let mrjoro@ know on [Slack](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#discussion-channels) and we will find a time that works for you.

**Comment by mrjoro** [comment]
The Stories Working Group will be presenting their [periodic updates](https://github.com/ampproject/meta/wiki/Working-Group-Updates) at this Design Review (10-15 minutes).

/cc @ampproject/wg-stories @newmuis

**Comment by rcebulko** [comment]
I'd like to share the plans for a work-in-progress bot to file issues for production errors automatically (https://github.com/ampproject/amphtml/issues/27675)

/cc @ampproject/wg-infra

**Comment by jorydotcom** [comment]
@mrjoro - @sumodas plans to join from the @ampproject/ac

**Comment by caroqliu** [comment]
I'd like to discuss [CSS in Bento AMP](https://docs.google.com/document/d/1NfB2mZX9exwTvNGe_nBlpKXxUJGyF_ytd9gBWwHRX6c/edit) if time allows.

**Comment by newmuis** [comment]
I can only attend the second half of this meeting; would be great to push the stories WG update towards the end, if possible.

**Comment by caroqliu** [comment]
Notes about CSS in Bento AMP: 

- High level summary of styling in AMP today:
  - surface area for styling increase by adding Bento and Preact modes
  -  two types of default styles AMP uses today (functionally critical versus decorative)
- Open questions:
  - inline styling shortcomings i.e. pseudoselectors, additional cost of shipping in JS not always worth it
  - styles lost when component children elements cross light/shadow DOM threshold
  - how to distribute optional decorative styles
- Suggestions from discussion:
  - Be careful to have an option to get styles embedded in JS and not
  - Focus on how publishers can consume styles and output them themselves

**Comment by rcebulko** [comment]
Primary takeaway for error issue creation: Security/privacy concerns about errors that could contain PII or other sensitive info being auto-published
- Risk is somewhat reduced by thresholding
- Some sort of moderation/approval buffer would be good
- Possible workaround: Create issue in separate private ampproject repo with link to duplicate into amphtml
- Alternate workaround: Release dashboard integration + separate alerting
