### ISSUE TITLE
Design Review 2020-04-16 00:00 UTC (deferred account creation flow, wg-runtime)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#27600]
Time: [2020-04-16 00:00 UTC](https://www.timeanddate.com/worldclock/meeting.html?year=2020&month=04&day=16&iv=0) ([add to Google Calendar](http://www.google.com/calendar/event?action=TEMPLATE&text=AMP%20Project%20Design%20Review&dates=20200416T000000Z/20200416T010000Z&details=https%3A%2F%2Fbit.ly%2Famp-dr))
Location: [Video conference via Google Meet](https://bit.ly/amp-dr)

The AMP community holds weekly engineering [design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md).  **We encourage everyone in the community to participate in these design reviews.**

If you are interested in bringing your design to design review, read the [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md) and add a link to your design doc or issue by the Monday before your design review.

When attending a design review please read through the designs *before* the design review starts.  This allows us to spend more time on discussion of the design.

We rotate our design review between times that work better for different parts of the world as described in our [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md), but you are welcome to attend any design review.  If you cannot make any of the design reviews but have a design to discuss please let mrjoro@ know on [Slack](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#discussion-channels) and we will find a time that works for you.

**Comment by mrjoro** [comment]
The Runtime Working Group will be presenting their [periodic updates](https://github.com/ampproject/meta/wiki/Working-Group-Updates) at this Design Review (10-15 minutes).

/cc @ampproject/wg-runtime @jridgewell

**Comment by vderosa** [comment]
I'd like to discuss the deferred account creation flow described at https://github.com/ampproject/wg-access-subscriptions/issues/8 (5-10 minutes).

**Comment by jridgewell** [comment]
WG-Runtime [status update](https://github.com/ampproject/wg-runtime/issues/33)

**Comment by mrjoro** [comment]
@vderosa can you add notes from the design review here when you get a chance?

**Comment by vderosa** [comment]
Notes:
  - Deferred flow design seemed OK, there were some open questions on the changes to `pingback` described in the design.
  - After offline discussion, the design has been changed to directly call the flow without relying on pingback.
