### ISSUE TITLE
Error reporting exponential backoff on intentional error status codes

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#27617]
When `error.js` tries to report an error to the server/viewer, it uses exponential backoff to retry in the event of a server error. AMP Error Reporting uses some error status codes such as `422 Unprocessable Entity` (when there is an error unminifying or standardizing a stacktrace) or `400 Bad Request` (when the stacktrace is ignored, such as non-JS stack frames or blacklisted errors).

In these cases, the client will repeatedly try to report errors that will be ignored every time, forcing an infinite (though exponentially-slowing) loop of reporting ([example](https://www.tierragamer.com/my-hero-academia-temporada-5-avance/amp/)). The error reporting logic should catch these expected failure conditions and give up, rather than trying to repeatedly report the same error.

/cc @jridgewell

**Comment by jridgewell** [comment]
We use exponential backoff for the total number of errors, but we never retry sending the same error. Eg, if you get 3 errors `A`, `B`, and `C`, then:

1. `A` is sent immediately
2. `B ` is sent after 1.5ms
3. `C` is sent after 2.25ms

But if any of them fail to send, they're dropped.

**Comment by rcebulko** [comment]
Ahh gotcha, I didn't pick that up. Closing.
