### ISSUE TITLE
Apply dynamic css classes on <body>

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#2761]
https://www.ampproject.org/docs/reference/extended/amp-dynamic-css-classes.html says they are added to the "HTML element", implying `<html>`. There was some discussion that it's actually `<body>`, so this needs to be confirmed one way or the other.

cc @ericlindley-g

**Comment by jridgewell** [comment]
It's `<html>`.

**Comment by rudygalfi** [comment]
Thanks. No doc change needed.

**Comment by dvoytenko** [comment]
We need to discuss: all other classes are applied on `body`. Ideally we'd put them all in one place, but at this point it'd be hard to move other classes to `html`.

**Comment by rudygalfi** [comment]
What are the options?

We could:
- add dynamic CSS classes also to `<body>` while also keeping them on `<html>`
- add, but also remove from `<html>` (how would this work?)

**Comment by dvoytenko** [comment]
The only option we can consider at this time (as opposed to keep it as is) is to move classes to `body` for all cases.

**Comment by jridgewell** [comment]
@dvoytenko: Dynamic CSS Classes hasn't been officially released yet (it's still behind an experiment in the latest release). Should we change this before pushing out the next prod?

**Comment by rudygalfi** [comment]
For some reason I was thinking it was stable. Yes, we should definitely make that change.

**Comment by jridgewell** [comment]
It's stable now, but we haven't pushed a new release. :wink:
