### ISSUE TITLE
Intent to Implement: amp-live-list

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#2762]
### progress
- **js validation**
  - [x] id validation
  - [x] child id validation
  - [x] data-sort-time (data-sort-key) on children 
  - [x] response is HtmlDocument
- **polling**
  - [x] off when viewer is not visible
  - [x] minimum poll interval value (currently set at 5000, might be too low)
  - [x] handle 415 and 500 with backoff
  - [x] restart timers when OK after backoff
- [ ] UX/visual work
  - [ ] adjusting top position
  - [x] visual indicator of new items
- [x] discover new children and append (w/o sorting)
- [x] scroll into view feature
  - [x] smooth scroll
  - [ ] optin/optout flag if necessary
- [x] data-max-items-per-page + paging
- [x] data-tombstone + deletion
  - [ ] compensate scroll position when live-list is above current viewport
- [x] data-update-time + url-append
  - [x] in place update of already present child
- [x] documentation
- [ ] validation
- [x] samples and demos
- [x] add way to disable updates (disabled property?), this helps with not updating when on page 2 for example or when a live list is old and will no longer get updates.
- [ ] paging reference point

---

trimmed down copy of @cramforce 's original design document (will be provided here if its public, or will copy verbatim if thats easier)
### overview

special form of web article which get constantly updated as a story evolves, with new elements typically being added to the front of the article.
### implementation

component polls against the document itself wherein the response can either be the full document or a fragment (with a smart server). This means within the cdn the response will always have been validated.

amp-live-list **must** and its direct children **must** have a unique id as this is the basis of filtering new updates, some additional attribute will allow is to be smarter or have more functionality.
### attributes
- id (required): To uniquely identify an amp-live-list (since multiple are allowed on a single page)
- data-poll-interval (optional): Time behind checks for new content. (will have minimum allowed value)
- data-max-items-per-page (required): Maximum number of child entries. Additional elements are assumed to be on the next "page".
### direct children attributes
- id (required): Id of the entry must never change.
- data-update-time (optional): Timestamp when the entry was last updated.
- data-sort-time (required): Timestamp used for sorting entries. Higher timestamps will be inserted before older entries.
- data-tombstone (optional): If present the entry is assumed to be deleted.

**Comment by ericlindley-g** [comment]
Since you're currently working on this, I'm thinking we can tentatively slot for the next milestone, but make clear somewhere what piece of the overall feature is being targeted for then.

Another option is to make a separate issue for the piece of functionality targeted, and slot that in the milestone; we can think about what's easiest

**Comment by erwinmombay** [comment]
@ericlindley-g i was planning to just keep this open and just tick stuff off the checklist (feel free to add items there too since i know you've been more in touch with partners etc) and not close it until all items are done.

**Comment by erwinmombay** [comment]
@ericlindley-g of course if you feel strongly about opening new issues i don't mind doing that at all. let me know :+1:

**Comment by ericlindley-g** [comment]
@erwinmombay That's what I was thinking, too—don't want to create extra work where we don't need any :)  Current plan: just have this one bug for the feature; slot it for sprints to indicate that it is actively being worked on; and communicate somewhere (maybe in the bug, but not in separate bugs) what's expected for the end of each sprint.  Of course, we can tweak this as we go

**Comment by erwinmombay** [comment]
@ericlindley-g SGTM, there will also be multiple PR's etc so i will probably convey work expectations either there or bring that info back here. (most likely the latter since the PR's can be closed etc and can get lost).

**Comment by cramforce** [comment]
@erwinmombay Feel free to publish the doc. Let Karen do a quick review.

**Comment by erwinmombay** [comment]
documentation here https://github.com/ampproject/amphtml/pull/3335

**Comment by erwinmombay** [comment]
disabled property here https://github.com/ampproject/amphtml/pull/3369

**Comment by jaygray0919** [comment]
Please put me on your beta-test list when appropriate. We're holding off converting our blogs to a conventional AMP structure in favor of using the new AMP elements.

**Comment by ericlindley-g** [comment]
Good timing—though the feature isn't 100% finished, we're hoping publishers can start testing the component. You shouldn't use amp-live-list in production until the component itself is officially pushed to prod (it won't work for any user not opted into the experiment), but it's available now as an experiment to gather feedback.

You can find documentation about how to implement `amp-live-list` [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-live-list/amp-live-list.md), and information about how to opt-in to the experiment for testing [here](https://www.ampproject.org/docs/reference/experimental.html) (to test locally, you can toggle the experiment on by entering `AMP.toggleExperiment('amp-live-list')` into your browser's javascript console).

**Comment by devongovett** [comment]
Is it possible to have an `amp-live-list` poll a different url than the page url? We provide liveblogging software to many third parties (e.g. CNN, Fox News, etc.), and they want to support amp. Since we are providing the content, our customers will not have the content directly on their amp pages, so we need a way to have amp update using content from our servers rather than the customers. We can run a server containing amp markup for the items within a liveblog, but the customer needs to host the surrounding content on the rest of the page.

**Comment by ericlindley-g** [comment]
That's a promising idea. In thinking through the advantage of this approach I see it as a way to have the simple markup of `amp-iframe`  with the UI flexibility of `amp-live-list`. 

I imagine we would have to make sure that the target url for polling is also valid AMP, to make sure the page doesn't break or introduce any security risks on updates. 

Another factor to consider is that, in this model, the primary content for the page would be pulled in from another URL. This means that we may want to require a placeholder, or make sure the component isn't within the first viewport, to ensure good UX (that the content has arrived by the time the user is looking for it).

One last thing to consider would be pagination, so users could see additional content after the max-items-per-page number is exceeded. Maybe this could be done if the publisher hosts one main live blog page, and has a dynamically generated "archive" page (e.g. "publisher.com/live-blog-page?page=7"), containing an amp-live-list that is itself configured to poll the URL of a dynamically generated page (e.g. "polling-url.com/live-blog-content?page=7")

@erwinmombay, what do you think? Maybe it could be an <amp-live-list> tag with an additional 'polling-url="pollingurl.com/live-blog-content"' attribute, and no children except the update button?

**Comment by ericlindley-g** [comment]
FYI to all the folks on this thread—we posted recently about [the beta release of `amp-live-list`](https://amphtml.wordpress.com/2016/07/26/live-updating-amps/) on the AMP Project blog. Please give it a try in development and let us know what you think! (this is the best time for feedback, before we push it to production)


And to walk through the options available today, for developers thinking about the potential paths:

Option 1: Publishers can use `amp-iframe` to show live blogs (including iframed or javascript embeds) hosted on another page inside of an iframe. Drawbacks here are that the iframe will load later than the rest of the page, and the UI (like a floating "updates available" button) couldn't appear outside of the iframe itself.

Option 2: When `amp-live-list` is available in production publishers could conceivably use it in conjunction with a live blogging platform's API by wrapping the content returned by the API in `amp-live-list` before publishing. A live blogging platform could optimize this by giving an option for publishers to request content wrapped in `amp-live-list` already, via their API. I'd be curious to hear feedback from live blogging platform providers like you, @devongovett , on this general approach.

Option 3: Publishers can publish their live blogs as static pages. Though the work to just wrap those static updates in `amp-live-list` is trivial at that point, so I would recommend doing that extra work and having a real "live" blog when `amp-live-list` is available : )

**Comment by devongovett** [comment]
Option 1a: The publisher could do a server side include in their amp page, wrapping content returned from our API in an `amp-live-list`. The problem with this approach is that the cache ttl on the amp page might be too long, and the publisher may use server side caching layers as well. With realtime updates, a ttl of even 5 minutes is too long.

Option 2. You mentioned several drawbacks to the `amp-iframe` approach already, but another one is that the liveblog is often the main content of the page, and `amp-iframe`s must appear outside the initial viewport currently if my understanding is correct.

Option 3: Same drawbacks as option 1, plus no real-time updates.

Ideally we'd like to combine option 1a with polling updates directly to our servers, so the publisher would do a server side include with the initial content to get it on the screen quickly, but live updates would come directly from our backend rather than the publisher's.

**Comment by ericlindley-g** [comment]
@devongovett Sending polling updates directly to your servers is an interesting idea—though there would need to be some way to ensure that the response contains only valid AMP (currently this assurance happens automatically via caching).  One option would be to run the content through validation on the fly, but that may not scale @erwinmombay @dvoytenko — do you have any thoughts on this?

**Comment by dvoytenko** [comment]
This is definitely something to think about in a bit more detail. But few quick comments:

> amp-iframes must appear outside the initial viewport currently if my understanding is correct

No. Iframes can be in the initial viewport as long as they provide the placeholder. The goal there is simply avoid the page looking blank and provide visual indication that something important will appear.

So, I've been trying to find some live-blog examples and so far found a few, such as this one: http://www.cbssports.com/olympics/news/rio-olympics-2016-michael-phelps-says-goodbye-on-emotional-night-with-gold/

All the ones I've seen were based on iframes. They look pretty cool. I'm a bit concerned about nested scrolling, but I think it's generally justifiable in this case.

Can you send some of your current example articles for us to get a better idea how you approach your integrations?

**Comment by cramforce** [comment]
It seems reasonable to poll a different URL, but I think the better approach if the publishers just integrate on the server side.

In any case, we do not directly talk to that URL when loading from the AMP cache, so those URLs must produce valid AMP docs and be retrievable (and cacheable) on the AMP caches.

**Comment by randallbpotter15** [comment]
@dvoytenko Double scrolling on a page is never justifiable.  It is a bad user experience.  This article from the Baynard Institute says it well.  http://baymard.com/blog/inline-scroll-areas

I think the issue I'm having here is that neither Live List or Live Blog are actually live or updating incrementally.  It seems that they are just general content that is compared against a cache at a regular interval and the whole page is updated.

So it's hard to pitch this as a live blogging experience to the content provider as it disregards an entire ecosystem of martech products aimed at live blogging.

Semantics (call it live content instead) aside the ask I have is the same -- I need a way to pull in JSON data from an endpoint and populate an AMP component.  It could use normal attributes as a sort of templating engine.

Pseudo:
[amp-live-blog-real id="myliveblog" polInterval="600" autorefresh="true" endpoint="myjsonservice"]

{{for each entry in myliveblog.entries}}

[blog entry meta1="{{entry.meta1}}" meta2="{{entry.meta2}}"][end blog entry]

{{ end for }}

[/amp-live-blog-real]

That was really ghetto but don't have much time while writing this.

This would give AMP control over the display even into the new content.

Thoughts?  I just want to make sure we avoid a "developer" mindset here and welcome the experience of the user who would double scroll (scroll treadmill) and the publisher who has an established time tested (years) method for distributing content.

**Comment by cramforce** [comment]
Agree, double scrolling sucks, but `amp-live-list` never triggers that.

It does not update the whole page. It diffs the page and includes new entries into the page. Seems like ideal UX. If anything is missing it can be added, of course.

**Comment by randallbpotter15** [comment]
Sorry my comment was about calling an html page on a different domain that contained the third party embed code in order to support other vendors instead of the amp component.  Will add this clarification to my comment.  Thank you for replying! :)

**Comment by cramforce** [comment]
It seems it is best for users when the content is directly embedded into
the served doc.

What is the primary value provided by 3p live blogging platforms? If it is
primarily the authoring tool, maybe this is a good time to invest into
backend integrations that do not suffer the latency issues of client side
integrations.

**Comment by cramforce** [comment]
I'd like to point to
https://github.com/ampproject/amphtml/blob/master/DESIGN_PRINCIPLES.md#user-experience--developer-experience--ease-of-implementation
In AMP we care about user experience more than about ease of integration
and developer experience. If there is a user experience benefit of a
frontend integration I'd love to hear it.

**Comment by devongovett** [comment]
For Storify, we are moving forward with a server side integration for customers. They'll hit our API and do a server side include of an `<amp-live-list>` that we serve, with the content of the liveblog. As long as the Google AMP cache updates frequently enough, and the customers aren't caching on their end, that should be sufficient for us.

**Comment by randallbpotter15** [comment]
@devongovett Does that handle LiveFyre blog feeds and will it work on Node servers?

@cramforce Integrating web workers into a periodic polling mechanism for a page already rendered, especially when the _user is expecting_ the content to periodically update would be just fine.  The user's page loaded incredibly fast, they are expecting content to refresh, and worldwide brands can continue using their publishing platforms without spending millions on development and retraining.  

Using UX terms, both the user persona and mental model heavily correlate in a live blogging scenario. 

How is the user experience paradigm handled on the AMP interactive content scenarios?  A third party widget is delivered to the user through an iframe.  Google has little to no control over what is displayed and we can all hope that the developer of the interactive item coded it with UX direction.

**Comment by randallbpotter15** [comment]
@devongovett I was thinking in terms of CNN that it may be fruitful if there was a way to push content updates to AMP as in Live Search.  Breaking news would be at the mercy of that cache expiry.  

Also even if the server side include was faster than DOM ready would it always be?  How would AMP know to wait to fire until after the server side include fired off seeing as the page would have a full DOM tree to satisfy AMP validation.  I'm mainly thinking of network latency to call that data from a third party.  I can see some ways around it all but would be interested in hearing your thoughts.

**Comment by randallbpotter15** [comment]
@cramforce from that page:  "Some things can be made fast and are still a terrible user experience. AMPs should deliver a fantastic user experience and speed is just one part of that. Only compromise when lack of support for something would stop AMP from being widely used and deployed."

The scope I'm talking about is a very real worldwide millions and millions of users audience.  The company already has a live blogging infrastructure in place that users are used to and content writers have been trained on.   It's also a lot harder at this scale to steer that change.  Using an AMP component that talks to a JSON feed the principles of AMP can still be achieved and maintain a great user experience.  The page paint would be incredibly fast and the user is expecting content updates at intervals -- hence it being a live blog and also hence Google already doing the polling themselves against the CDN.  I believe the part about Endpoints was described as something a developer wouldn't have to do.  But some of us need to do it in order to adopt this on the very real scale mentioned above.  

Google could also have the opportunity to broker the JSON consumption should a business value be found in doing so.

**Comment by cramforce** [comment]
Please look into `amp-list` and it's limitations. It might be feasible to allow `amp-live-list` update using the same mechanism, but for security reasons we must severely limit the type of content that can be written from the mustache templates which may be insufficient for most live blog use cases.

I understand that re-architecting things can be daunting, but AMP (as linked to above) does not aim for the path of least resistance in terms of adoption.

@randallbpotter15 `amp-list-list` always works with full server side rendered page DOMs. The Nth request is the same as the N-1th request. All the server always has to do is render its most current understanding of the live content. As long as a publisher is capable of publishing a web page (which is their business) they can make them live-enabled.

**Comment by randallbpotter15** [comment]
Was out sick @cramforce.  Thank you for the response.  Will look into amp-list and compare with amp-live-list to the end you described.

Good to know about the server side renders too :)

**Comment by adelinamart** [comment]
What's the status of this? Thanks.

**Comment by erwinmombay** [comment]
this is still in progress

**Comment by rudygalfi** [comment]
@ericlindley-g Might be nice to move remaining items into a project for tracking

**Comment by ericlindley-g** [comment]
Agreed— @erwinmombay, what do you want to preserve from this issue? We could either bump those out to a single issue w/ checklist, or separate issues as needed, and close this when they're tracked elsewhere. (I'll also do a sweep to make sure we're capturing the needs expressed in the thread, as well)

**Comment by dvoytenko** [comment]
Let's fan out the remaining issues and close this one since officially launch has been done.

**Comment by erwinmombay** [comment]
@ericfs dont see anything i want to preserve that's already not in another issue
