### ISSUE TITLE
Custom JavaScript is not allowed.

### ISSUE THREAD

**Issue by alexsonnay** [ampproject/amphtml#27620]
How are we supposed to use AMP in a Vue CLI project if we can't use custom JS ?! Am I missing something ?

**Comment by wassgha** [comment]
When using a Javascript framework (e.g. React or Vue.js), it's possible to create AMP pages if they are server-side rendered (which strips out all custom framework javascript and outputs AMP HTML). For React, the usual path is to use Next.js. For Vue, it's Nuxt.js. Both of which are a layer on top of the framework to allow for server-side rendering and reduce code discrepancies between the server-side-rendered and client-side-rendered components. I'd take a look at https://medium.com/the-web-tub/making-a-website-with-nuxt-vue-and-amp-3ef904819de6 for more information on AMP with Nuxt.js
