### ISSUE TITLE
PWA: Add <html> element to shadow AMPs

### ISSUE THREAD

**Issue by wassgha** [ampproject/amphtml#27637]
## What's the issue?

When using the `MultidocManager`, attaching an AMP Shadow doc creates `<style>` and `<script>` elements at the same level as the `<body>` element of the shadow doc and adds neither `<head>` nor `<html>`. This manifested as an additional `8px` padding added to `<amp-next-page>` embeds since the CSS rule that overrides the browser default (by adding `margin: 0;`) is expecting an `<html>` element:

https://github.com/ampproject/amphtml/blob/ae4fc6e974aef5a0199173ac6e0e2de0bffce7ae/css/ampdoc.css#L40-L47

We need to either update these CSS rules to use a different selector than `html` for shadow docs, or we should make it so that shadow docs mirror the regular amp document structure, with an `html` wrapper, `head`, etc.

## What browsers are affected?

All browsers

## Which AMP version is affected?

All versions

/cc @dvoytenko

**Comment by dvoytenko** [comment]
Yes. I'd like to see `<html>` to be reintroduced into shadow docs safely.

**Comment by wassgha** [comment]
@dvoytenko do you mind sharing more context on why it's not there right now?

**Comment by dvoytenko** [comment]
The thinking went that it's really one root hosting many documents (bodies). But in reality the number of `if`s that this is causing is too much and definitely now seems like a wrong decision. E.g. it'd have probably been easier to just emulate `scrollingElement` on the shadow root then to rely on the fact that we need to reach for the document's root for that. A lot of code we have set classes and listeners on `documentElement`, so not having it there causes bugs.
