### ISSUE TITLE
AMP.navigateTo with standard URL substitutions

### ISSUE THREAD

**Issue by cadoogi** [ampproject/amphtml#27643]
## What's the issue?

In the documentation its clearly stated that AMP.navigateTo supports but I can't get it to work with select event on amp-autocomplete

https://amp.dev/documentation/guides-and-tutorials/learn/amp-actions-and-events/

## How do we reproduce the issue?

1. go to https://site.ampify.io/test/navigate.html
2. type "n" in the input field
3. select the first result from the autocomplete
4. navigates to https://example.com/?cityId=518&r=RANDOM  (RANDOM should to be substituted)

## What browsers are affected?

ALL

## Which AMP version is affected?

Latest

**Comment by jridgewell** [comment]
It appears this is a documentation bug, the `navigateTo` action does not support URL replacements. /cc @CrystalOnScript

**Comment by CrystalOnScript** [comment]
Thanks for flagging, I've send up a fix!

**Comment by choumx** [comment]
Fixed in ampproject/amp.dev#3865.

**Comment by trivedi** [comment]
Did this bug reappear somehow? I'm still seeing this copy in https://amp.dev/documentation/guides-and-t


In fact, now it's bold and in a larger text! Very misleading

<img width="748" alt="Screen Shot 2021-08-04 at 4 42 09 PM" src="https://user-images.githubusercontent.com/2756580/128251995-80c70632-894c-4e5d-b90d-124c86305f2c.png">
utorials/learn/amp-actions-and-events/
