### ISSUE TITLE
I2I: New supported type premiumads for amp-auto-ads

### ISSUE THREAD

**Issue by rochapablo** [ampproject/amphtml#27666]
**Provide a brief description of the feature/change you are planning on implementing.**

We would like to add support for premiumads network on amp-auto-ads, so our publishers can easily activate and monetize their AMP version.

**Explain why AMP needs this change.**

Currently, publishers using Wordpress have to rely on third-party plugins to insert ad tags on their AMP version, since the official AMP plugin does not support this natively. Publishers with a custom built website must do this manually, leading to error prone ad insertion and more ads than content. Both of these scenarios require basic HTML and JS knowledge, and that’s something many of our publishers don’t have.

Our solution eliminates the need to insert individual ad tags in favor of a single script that identifies strategic placements for ad insertion on the AMP version.

**Design**

```
<amp-auto-ads
   type="premiumads"
   data-publisher="f326cb3e-4302-4f7b-ac75-0b31153d0c59">
</amp-auto-ads>
```

**Add any other information that may help people understand your I2I.**

The changes are really simple. It was just added an extension for amp-auto-ads tag that will allow a new type "premiumads", where the ads json will be provided by our API.

**Comment by lannka** [comment]
closed via #27667
