### ISSUE TITLE
I2I: Error Issue Bot

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#27675]
Overview
---

Right now, the release on-duty monitors errors reported to AMP Error Reporting by inspecting the stackdriver logs, identifying new errors, and then filing a GitHub issue for them. Until recently there was no standard format for this issue, but they generally included a stacktrace and tag a relevant user or working group, 

We could eliminate most of this work for the release on-duty, as well as make it easier for AMP developers to debug and resolve errors, with a lightweight automation of this process.

Proposal: Error Issue Creator
---

The [error report issue template](https://github.com/ampproject/amphtml/blob/master/.github/ISSUE_TEMPLATE/error-report.md) has a handful of fields for the on-duty to include:
- error message
- stacktrace
- daily frequency
- first seen date

A standalone Cloud Function/app could accept queries containing these fields; I've prototyped a simple version of this already to validate its feasibility. Using the stacktrace and the GitHub GraphQL Blame API, we can identify the most recent user to edit each line in the stacktrace. After filtering out PRs that are very old or contained many files (like refactor PRs), the app can identify a few users who are most likely to be related to the error. Finally, it will file an issue with the **Type: Error Report** label and all the necessary error data.

An example of an issue generated in this way can be seen here: 
[![image](https://user-images.githubusercontent.com/6694512/78929185-ec249380-7a6f-11ea-8aff-24a79c47ad72.png)](https://github.com/rcebulko/amphtml/issues/30)

> Note: For testing, I wrote a bookmarklet which extracts the data from the error page and queries the endpoint.

Proposal: Error Monitoring
---

Stackdriver error logging has a very simple notification system with no settings for frequency thresholds or other notification controls, rendering it effectively unusable for AMP. Instead, a separate app/cron task can periodically fetch the top N (say, 25) most frequent errors using the Cloud Logging API.

For each error that is marked **Open**, it would
- pass the error stacktrace and stats along to the Error Issue Creator endpoint
- wait for the issue URL returned in the response
- mark the error instance as **Acknowledged**
- link the GitHub issue

On-duty Experience
---

As a release on-duty, you wouldn't have to look at the Stackdriver error logs at all. You would open the list of issues with the `Type: Error Report` label and ensure all the ones created in the past week were assigned to a user or working group; if they aren't, you'd have a few users suggested in the comment and could choose to /cc a working group if none of the edits in the stacktrace blame look relevant.

Additional Considerations
---

1. Automatically notifying people would make the process more useful, but would introduce potential for notification-spam
- This could be mitigated by filtering out changes to `log.js`, `error.js`, etc.
2. What if there's a P0 security/privacy vulnerability? Do we want that automatically reported to a public GitHub issue?
- What would happen currently? Would the release on-duty identify the issue, or would they paste the stacktrace as normal, leaving it to be caught on the GitHub issue anyway?

/cc @ampproject/wg-infra @ampproject/wg-runtime

**Comment by choumx** [comment]
Neat idea! Would it be possible to only file these issues if they're in the top N of all errors? Relative error volume is an important signal. E.g. is 10k/day a lot? 🤷‍♂️

**Comment by rcebulko** [comment]
> Neat idea! Would it be possible to only file these issues if they're in the top N of all errors? Relative error volume is an important signal. E.g. is 10k/day a lot?

Yes, I agree! I mentioned something like that:
> "a separate app/cron task can periodically fetch the top N (say, 25) most frequent errors using the Cloud Logging API"

**Comment by choumx** [comment]
Let's display the error rank in the issue itself, front and center.

**Comment by rcebulko** [comment]
I worry that the rank would have potential to become pretty obsolete pretty quickly. It would depend on the frequency of the task to monitor the errors, but if it's less than 24 hours then the error will always appear and first get picked up/recorded when it first reaches the page, ie. 23/24/25 out of 25. Then if it gets more frequent, the issue rank is pretty useless. Likewise, issues that are surpassed by new ones will appear higher-ranked than they are. The specifics of how to determine and update rank would need some careful thought if we were to display the error rank this way

**Comment by choumx** [comment]
Yea, I think it'll be important to identify P0s vs. P2s. Otherwise, engs might start to ignore these autogenerated issues over time. The distinction is pretty obvious in manual review. Another option is to only report top 10 errors, so every issue is likely important.

Alternatively, thinking through the workflow -- once an eng sees an autogenerated error issue, the next step is probably to open the error reporting site to get fresh data. So the main value-add might just be alerting, which we could accomplish with an email or other alerting mechanism in GCP.

**Comment by rcebulko** [comment]
You're definitely right re: eng ignoring auto-generated issues over time. Maybe in addition to/instead of a "top N" approach we manually define some threshold, 10k/day for example, and don't file issues under that threshold. Over time we can lower that threshold slowly as the overall frequency goes down, but that would let us semi-manually "skim off the top" without so much issue spam.

Alerting would definitely be one of the major value-adds; unfortunately, built-in alerting mechanisms in GCP are not very well suited to our use case, so a simple external solution may be needed.

**Comment by rcebulko** [comment]
Main takeaway from design review: Security/privacy concerns about errors that could contain PII or other sensitive info being auto-published
- Risk reduced by thresholding
- Some sort of moderation/approval buffer would be good
- Possible workaround: Create issue in separate private ampproject repo with link to duplicate into amphtml
- Alternate workaround: Release dashboard integration + separate alerting

**Comment by rcebulko** [comment]
Closing this as done
