### ISSUE TITLE
Set up protected branches

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2767]
https://github.com/blog/2137-protected-branches-improvements

We basically want the lowest requirements, but limit merges to the current group minus PMs :)

**Comment by erwinmombay** [comment]
:+1:

**Comment by erwinmombay** [comment]
@cramforce dont think i have access to ampproject/amphtml settings page

**Comment by cramforce** [comment]
Done.

I also turned on status checks.

**Comment by cramforce** [comment]
@erwinmombay What is the current state of release branches? We now use one-off-branches created from master, right?
