### ISSUE TITLE
Amp plugin issue

### ISSUE THREAD

**Issue by priyankajam** [ampproject/amphtml#27694]
I am using accelerated mobile pages plugin for wordpress site but after installing plugin i am facing 'This site is experiencing technical difficulties'

Please give me solution ASAP
Thanks

**Comment by selfcatering** [comment]
Hi priyankajam,

This repo is dedicated to AMP itself. You should check that plugin support for solution. 

Good luck

**Comment by amanintech** [comment]
@priyankajam the issue you are pointing to relates to faulty plugin installation. You can go to the Wordpress directory and delete this .maintenance file. If that doesn't work you can remove the plugin from directory and try again

**Comment by priyankajam** [comment]
> @priyankajam the issue you are pointing to relates to faulty plugin installation. You can go to the Wordpress directory and delete this .maintenance file. If that doesn't work you can remove the plugin from directory and try again

ok

**Comment by amanintech** [comment]
We may close this issue
