### ISSUE TITLE
Investigate strategy for dependency pinning

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2771]
We used to use NPM shrinkwrap, but we stopped due to problems with @greenkeeperio-bot. We should reconsider. I'd also consider just checking node_modules into the repo (or ideally a separate repo connected with git submodule (Rule number 1: Never ever use git submodule, they are the worst).

**Comment by erwinmombay** [comment]
cool, will go ahead and run shrinkwrap again. these days we dont really upgrade as much we would like to anyways, so i think we should be good. we can always remove shrinkwrap again if it becomes a issue. 

ive never done checking the whole node_modules into a repo, not sure whats its implications are building etc (besides cloning slowdown + bandwidth)

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)

**Comment by cramforce** [comment]
@erwinmombay where are we with yarn on this?

**Comment by erwinmombay** [comment]
@cramforce confirmed it works internally in the release process. i need to update the docs and send out an email to the team

**Comment by adelinamart** [comment]
@erwinmombay anything else to be done here? Thanks

**Comment by choumx** [comment]
This should be fixed for good now.
