### ISSUE TITLE
I2I: Classify traffic for AdSense Ad Size Optimization

### ISSUE THREAD

**Issue by Jiaming-X** [ampproject/amphtml#27712]
## Summary
In the earlier [issue](https://github.com/ampproject/amphtml/issues/23568), we have implemented the logic for Adsense Ad Size Optimization. However, the width expansion would not work for some of the users with wide viewport since the expanded Ad could cover the contents in the nearby columns. To prevent broken user experience, we need to classify the traffic to decide whether to turn on the Ad Size Optimization or not.  

## Design document
Check out this Google doc for [details](https://docs.google.com/document/d/16umi6J2d6hajbdt27skhbzH-7w2tIZ4u922kxVWl1Oo/edit#heading=h.l8jetkktdduy) and internal references. 

## Motivation
To prevent broken user experience, we need to classify the traffic to decide whether to turn on the Ad Size Optimization or not.  

/cc @ampproject/wg-approvers, @charliereams

**Comment by calebcordry** [comment]
to/ @ampproject/wg-ads

**Comment by jamesozzie** [comment]
@Jiaming-X @calebcordry I'm happy to share some examples of sites using Auto ads for AMP which would be impacted by this. Easy to replicate, and I not sure it's specific to users with wide viewports.

**Comment by Jiaming-X** [comment]
@jamesozzie Thanks James. Feel free to share it. I think there are a few flows would create the similar issues in the bug. The Formatopia(this one) is one of them. I might need to create another issue for the auto ad one.

**Comment by jamesozzie** [comment]
@Jiaming-X Sure, below are examples of some sites I've came across which I've noticed Auto ads for AMP placing adverts directly above the content.
- [Site 1](https://www.zodiacenthusiasts.com/cancer-boss/?amp) ([Screenshot](https://i.imgur.com/fg0RZRT.png))
- [Site 2](https://beijing.ie/?amp) ([screenshot](https://i.imgur.com/pPVDj4f.png))
- [Site 3 ](https://meetrussia.online/magical-attributes-in-the-russian-fairy-tales/?amp)
- [Site 4 ](https://www.eqrae.com/%d9%82%d8%b5-%d8%a7%d9%84%d8%b4%d8%b9%d8%b1-%d9%81%d9%89-%d8%a7%d9%84%d8%a7%d9%8a%d8%a7%d9%85-%d8%a7%d9%84%d9%82%d9%85%d8%b1%d9%8a%d8%a9-2020/)
- [Site 5](https://indomtl.com/)

Happy to provide further details if necessary, or recreate with test sites. All the above are WordPress sites.

**Comment by Jiaming-X** [comment]
The issue was resolved. Closing the ticket now.
