### ISSUE TITLE
Add a .zip/.tar.gz file with the release's files to AMP releases on GitHub

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#27726]

**Comment by rsimha** [comment]
_[Infra triage]_ Do recent changes to CI / release automation make this easier to do?

**Comment by danielrozenberg** [comment]
While not added to the release page on GitHub, there are .tar.gz archives of each release on CircleCI, e.g., last night's nightly build: https://app.circleci.com/pipelines/github/ampproject/amphtml/22503/workflows/3df9f4bc-5e03-42df-95ba-93309e397681/jobs/447033/artifacts

Unless we decide to prioritize this, I think we can safely say that the last mile (copying this file to a relevant release page) isn't going to happen, so I think it's safe to make this as "fixed for the most part". wdyt?
