### ISSUE TITLE
🌸 Cherry-pick request for #27665 into #27625 (Pending)

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#27746]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| N/A | #27665 |     **YES**     | **NO** | **NO** | #27625                                                               |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

This issue breaks sourcemaps, and by extension breaks part of our error reporting pipeline. The error reporting service converts production stacktraces to sourcemapped stacktraces, and errors are grouped and tracked based on that stacktrace. With the broken sourcemap, every error is reported as a new error, making it difficult to identify trends/spikes or new errors versus a deluge of existing errors re-surfacing.

If this cherry-pick does not go in, then the same thing will happen a second time when the fix eventually reaches stable.

@jridgewell Would it be feasible to cherry-pick this fix, or does the recent churn in some of the build files make merge conflicts to risky? The differing stacktrace file paths will make it much harder to identify new vs. existing errors, and without a cherry-pick this won't make it into Stable until the week after next. In theory the generated binaries should be the same, with only the sourcemaps changing.

Alternately, I could try to temporarily patch AMP Error Reporting (which has a separate release cadence) to dedupe directory paths in stacktraces. This would be more of a band-aid, but with lower risk of regressions in the actual AMP Runtime.

# Mini-postmortem

**TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

<_1-2 sentences summarizing the problem and root causes._>

## Impact

- <_Which users were affected? Roughly how many?_>
- <_How were users affected? E.g. partial or complete loss of functionality?_>

## Action Items

- #<_ISSUE_NUMBER_>: <_Add unit/integration/end-to-end test_>
- #<_ISSUE_NUMBER_>: <_Add monitoring for edge case via error logging_>
- #<_ISSUE_NUMBER_>: <_Refactor an easily misused API_>

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by dvoytenko** [comment]
Approved

**Comment by danielrozenberg** [comment]
Please create an issue for this

**Comment by jridgewell** [comment]
> The differing stacktrace file paths will make it much harder to identify new vs. existing errors, and without a cherry-pick this won't make it into Stable until the week after next.

We can actually manually fix this by editing the files on server. As this isn't touching actual JS code, I don't believe a cherry pick is necessary.

**Comment by rcebulko** [comment]
Closing based on Justin's comment above

**Comment by cramforce** [comment]
Could we write very basic unit tests to ensure that the generated sourcemaps are OK?

E.g.

- Take known string in source code (Like `amp-video`)
- Find it in the compiled source
- Resolve its original source position
- Compare to actual source position

**Comment by jridgewell** [comment]
@cramforce: I opened https://github.com/ampproject/amphtml/issues/27681 to track just that.
