### ISSUE TITLE
🌸 Cherry-pick request for #27768 into #27625/#27765 (Approved)

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#27769]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #27554 | #27768 |     **YES**     | **YES** | **NO** | Stable: #27625 \| Beta/Experimental: #27765                                                        |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

Known breakage #27554 is included in the target release. The reverts cherry-picked in #27554 directly went to 2004030010070, leaving the change to be rolled out in subsequent versions as discussed but not resolved in #27555.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

<_1-2 sentences summarizing the problem and root causes._>

## Impact

- <_Which users were affected? Roughly how many?_>
- <_How were users affected? E.g. partial or complete loss of functionality?_>

## Action Items

- #<_ISSUE_NUMBER_>: <_Add unit/integration/end-to-end test_>
- #<_ISSUE_NUMBER_>: <_Add monitoring for edge case via error logging_>
- #<_ISSUE_NUMBER_>: <_Refactor an easily misused API_>

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by nainar** [comment]
@ampproject/wg-approvers 

cc @cramforce @dvoytenko 

Cherry pick was approved for stable already in #27554

**Comment by nainar** [comment]
We have @cramforce's approval

**Comment by caroqliu** [comment]
Root cause discussed in [ampproject/wg-infra#36](https://github.com/ampproject/wg-infra/issues/36)

**Comment by danielrozenberg** [comment]
Verified as fixed by @nainar
