### ISSUE TITLE
Consider moving size change requests to TaskQueue_

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#2776]
Currently `resources.requestsChangeSize_` uses a JS array unlike the `queue_` and `exec_` queues.

This might not be needed as @dvoytenko mentioned we're trying to consolidate these queues to just use one or two.

**Comment by dvoytenko** [comment]
I'll close this for now. There are other issues tracking a more end-to-end refactoring of Resources that would cover this.
