### ISSUE TITLE
I2I: Force `font-display: optional` on AMP pages

### ISSUE THREAD

**Issue by wassgha** [ampproject/amphtml#27776]
## Summary

An intent to experiment with forcing all AMP pages to use `font-display: optional` in order to reduce [Cumulative Layout Shift (CLS)](https://web.dev/cls/) and improve the general user experience.

## Motivation

An abundant number of pages were observed to use fallback fonts that don't match the requested font causing the page to shift contents down significantly when the correct font is loaded.

<img src="https://user-images.githubusercontent.com/591655/79308056-c7d01900-7eac-11ea-9af3-9ac1ca076fa1.gif" width="300" />

This issue particularly happens in a few circumstances:
- The font is not part of the system fonts (e.g. Roboto is usually fine on Android devices)
- The font is not cached (usually happens when the font is hosted by a proprietary server as opposed to CDNs like Google Fonts)
- The fallback font is very different from the requested font 

Some possible solutions to this include
- Forcing the browser to keep the fallback font if the requested font is not cached, see next paragraph
- Using a better fallback font, see https://meowni.ca/font-style-matcher/ , this requires a new complex validation step for AMP pages in order to be enforced

Using the `font-display` option we can [control the font loading behavior of the browser](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display). Particularly, `font-display: optional` and `font-display: fallback` are of interest to us.

In particular, websites using Google Fonts should be able to quickly be switched to `font-display: optional` by adding a parameter to the URL, see https://twitter.com/szynszyliszys/status/1126261253280649216

## Launch tracker

Still experimenting.

/cc @ampproject/wg-approvers @kristoferbaxter @ampproject/wg-caching

**Comment by cramforce** [comment]
The problem with `font-display: optional` is that it isn't backwards compatible. If we forced it, it would break cases where no proper fallback font exists such as for icon fonts.

AMP currently forces all fonts to `swap`. See here https://github.com/ampproject/amphtml/blob/master/src/font-stylesheet-timeout.js#L141 (Also for the related comment).

This is a trade-off between CLS and LCP (not-painting-fonts blocks LCP, dual-painting leads to CLS).

I recently proposed to the Chrome team to change the default blocking time for fonts to align with LCP goals (2500ms but leaving time to actually paint) instead of the current value of 3000ms.

It might make sense for us to implement that behavior using our existing mechanism. It could be that our [current timeout](https://github.com/ampproject/amphtml/blob/master/src/font-stylesheet-timeout.js#L52) is too aggressive, and we should instead use something like `2000 - (now -  perf.timing.responseStart)`. That would provide balance towards keeping LCP under 2500ms and keep CLS lower.

**Comment by cramforce** [comment]
Example PR #27781

**Comment by wassgha** [comment]
#27781 does seem to improve the swapping a little, however to address your previous comment, even though it might not be feasible to use `font-display: optional` for `amp-custom` styles given that there might be no fallback font configured, how do we feel about forcing it for Google Fonts and the other `<link>` [font providers we support](https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/custom_fonts/#1.-using-%3Clink%3E) where we know that the fonts are not icon fonts and have proper fallbacks available?

**Comment by cramforce** [comment]
I think a fine-grained solution scoped to only font providers who do not offer icon fonts is definitely worth exploring! As with the existing intervention it should not override explicitly set font-display.

**Comment by Gregable** [comment]
@wassgha Can you outline a specific proposal for the parts that we should have the Cache implement?

**Comment by wassgha** [comment]
> @wassgha Can you outline a specific proposal for the parts that we should have the Cache implement?

@alanorozco and I are going to be reviewing the impact of #27781 since it reached production, however, the initial proposed change (Google Fonts) would be as easy as `&display=optional` to pages that link to a Google Fonts stylesheet. For example:
```
http://fonts.googleapis.com/css?family=Open+Sans&font-display=optional
```

**Comment by Gregable** [comment]
@wassgha Thanks! Is that change something we should go ahead and prioritize, or do we need to wait for additional confirmation.

**Comment by wassgha** [comment]
This I2I should be enough of a notice for us to go ahead with the change for at least 1% of eligible pages (those with Google fonts but without display=optional) and measure improvement on CLS if any. Once we see improvement we can extend to all pages and consider doing it for providers and custom fonts other than Google Fonts.

**Comment by cramforce** [comment]
Would definitely be nice to see the data. As discussed, we should not include the display arg when it is already present. We could also consider making non-presence a warning in the validator at some point.

**Comment by Gregable** [comment]
Track the Cache part of this in Google as #158335651. Removing `wg-caching` label.
