### ISSUE TITLE
Release infra: fail on reverted commits

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#27771]
Originally filed by @dvoytenko. Migrating this from https://github.com/ampproject/wg-infra/issues/36, since we do not use the `wg-infra` repo to track issues or PRs, we only use it for status updates.

## Describe the new feature or change to an existing feature you'd like to see

If commit was found to be problematic, it's reverted. However, it still could end up in a release branch without its revert counterpart. This would create a bad release. However, this situation is fairly easily avoidable.

## Description

Naming:
 * COMMIT - the bad commit that was reverted.
 * PR(COMMIT) - the pull request that created the bad commit.
 * REVERT - the reverting commit.
 * PR(REVERT) - the pull request that created the reverting commit.
 * BRANCH - the branch created for the release.

Once the BRANCH is created, we scan the new commits in this branch. If a COMMIT is found in this branch, there must also be REVERT. If there's no REVERT, the release should fail (or warn).

## Technicals

Let's look at the recent failure with https://github.com/ampproject/amphtml/pull/27319 and the reverting https://github.com/ampproject/amphtml/pull/27422.

It's not clear that GitHub API itself provides the data that we want. For instance, here's the reverted [commit](https://api.github.com/repos/ampproject/amphtml/git/commits/17636f5a70147c20cc8b4d75d824bd508449aef5) and [pull request](https://api.github.com/repos/ampproject/amphtml/pulls/27319). I didn't find any good information to indicate that it was reverted. Thus we may have to create a label "Reverted" and set it on the reverted pull request.

The reverting [commit](https://api.github.com/repos/ampproject/amphtml/git/commits/d328abc7e23a8253812c9354cc7382d2a11555d1) and [pull request](https://api.github.com/repos/ampproject/amphtml/pulls/27422) on the other hand provide plenty of information. Such as:
 * Commit message includes "This reverts commit 17636f5a..."
 * Pull request body includes "Reverts ampproject/amphtml#27319"
 * Default branch name is "revert-27319-..."

Thus, we could look for "Reverted" label and see if there's a matching reverting commit available.

/cc @ampproject/wg-infra

**Comment by rsimha** [comment]
In addition to @dvoytenko's request above, based on this week's learnings, we should fail any release that contains a commit without an accompanying PR.

**Comment by danielrozenberg** [comment]
Not sure how to approach the first problem here in a robust way, but this one:

> In addition to @dvoytenko's request above, based on this week's learnings, we should fail any release that contains a commit without an accompanying PR.

should be much easier - basically something like this pseudo-code can do the trick:
```javascript
const commits_not_in_master = exec(`git log --pretty=format:%H master..${branch}`)
const cherry_picked_commits_in_branch = exec('git cherry master')

if (commits_not_in_master != cherry_picked_commits_in_branch) {
  throw new Error('...');
}
```

**Comment by rcebulko** [comment]
My thoughts about the first bit are to tag the reverted commit with a `reverted` label, which can be easily identified by release/testing code even in the absence of the revert. Then the revert commit can be tagged `reverts-abc123` on the `master` branch. When it's cherry-picked the tag will have to be re-applied to the cherry-picked commit, which will be manual (at least initially) and possibly annoying, but would guard against a reverted commit making it into a release

**Comment by danielrozenberg** [comment]
Using `reverted` and `reverts-<sha>` tags as the control mechanism works for me, question is how can we ensure these are added?

One quick idea that comes to mind is to write another bot (yay bots!) that:
* listens to new PR changes - if a PR with any of the relevant keywords ("revert", "reverts", "rollback") are in the title/description/branch name it'll add a comment to the PR saying that this PR will tag this commit with `reverts-<sha>` and tag `<sha>` with `<reverted>` + "if this is not correct edit the description and add `/norollback` to it"
* when that PR is submitted tag the relevant commits (unless `/norollback` is in the description)

**Comment by danielrozenberg** [comment]
@estherkim you started working on this, correct?

**Comment by estherkim** [comment]
Nope! This is different from the cherry picking automation that I'm building.

**Comment by rsimha** [comment]
_[Infra triage]_ Is this already addressed by recent release changes? If not, is this something we'd like to do?

**Comment by estherkim** [comment]
This is still pending and worth doing 👍

**Comment by danielrozenberg** [comment]
Closing as outdated
