### ISSUE TITLE
Cannot read property 'applyToElement' of undefined

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#27779]
0. Opt-in to AMP version 2004142327160
1. Load https://www.nationalgeographic.com/amp-stories/stonewall-riots-50th-anniversary-lgbt-gay-pride-stories-resistance-resilience/
2. Navigate to page with video (pg 4)
3. Error should show

```
error.js:208 Cannot read property 'applyToElement' of undefined
rf	@	error.js:208
Promise.catch (async)		
f.delay	@	timer-impl.js:70
Tf	@	media-pool.js:972
(anonymous)	@	media-pool.js:965
```

/cc @ampproject/wg-stories

**Comment by Enriqe** [comment]
Closed via #27782

**Comment by caroqliu** [comment]
Error appears to still occur: go/ampe/CM_kydGTz6i3FA

**Comment by gmajoulet** [comment]
Thanks Caroline!
I can't repro manually, I'll keep monitoring this over the next 24h.

**Comment by gmajoulet** [comment]
I'm not 100% sure how to read this but it looks like the errors come from old 1p releases. It doesn't look like it happens in stable today, and I double checked that the faulty PR was correctly reverted.
