### ISSUE TITLE
Intent to implement: new layout type `flex-item`

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#2778]
A new layout type will be called `flex-item`. It will be similar to the `fill` layout, but instead of trying to take all of the space of the container, it will take the available space based on the flexbox model.

### Declaration
```
<amp-element layout=flex-item></amp-element>
```

### Implementation
```
.-amp-layout-flex-item {
  flex: 1 1 0;
  align-self: stretch;
  height: 100%;
  width: 100%;
}
```

Notice that `height=100%` and `width=100%` are overridable defaults and are only there to ensure that the container indeed specifies `display: flex`. Alternatively, the element can force `display: flex` on the parent.

### Motivation
The size-defining layouts currently include `fixed`, `responsive` and `fill`. The main goal of these layouts is to ensure that the element's size does NOT change when resources are loaded, which would otherwise lead to constant reflows and a broken user experience.

The `flex-item` layout is similar - it ensures that the element is not sporadically resized while also giving it a more flexible positioning options. It'd also allow the element to participate in the flexbox layouts.

### Workaround
Currently the same can be arranged using the following workaround:
```
<style>
.container {
  display: flex;
}
.childN {
  position: relative;
  flex: 1 1 0;
}
</style>

<div class="container">
  <div class="child1">...</div>
  <div class="child2">...</div>
  <div class="childN">
    <amp-element layout="fill"></amp-element>
  </div>
</div>
```

The proposed `layout=flex-item` will allow the same but without the need of, otherwise meaningless, `div.childN`.

**Comment by cramforce** [comment]
:100:

**Comment by powdercloud** [comment]
Should I look at PR #2856 and get this done for the validator also?

**Comment by cramforce** [comment]
@powdercloud Yes, please!

**Comment by dvoytenko** [comment]
@powdercloud As before, let's wait for us to land this PR and you can follow. Thanks!

**Comment by dvoytenko** [comment]
as discussed earlier, we removed the implicit flex styling via `height=auto`

**Comment by dvoytenko** [comment]
`layout=flex` renamed to `layout=flex-item`

**Comment by erwinmombay** [comment]
@Meggin just fyi. is there anything we need to do on the docs end?

**Comment by Meggin** [comment]
We'd for sure need to update validation tables for any components that
support this layout type.

Are validations ready yet?

**Comment by erwinmombay** [comment]
@Meggin nope, validation isnt ready yet
