### ISSUE TITLE
Celebrity stories's slide doesn't show image of celebrity.

### ISSUE THREAD

**Issue by Ichigo3d** [ampproject/amphtml#27794]
Description: 
Celebrity stories's slide doesn't show image of celebrity on amp version 2004142327160 with Chrome, FFox, Safari browsers.

Steps:
1) change version of amp on cdn.ampproject.org/experiments.html or requestly extension or any kind of app to 2004142327160
2) open new google.com page
3) input "Emma Stone" in search text field
4) click on "Emma Stones her life in images" 
5) Switch to the second page manually or wait when it's switched automatically  
6) Observe result

Actual result: 
Celebrity stories's slide doesn't show image of celebrity

Expected result:
Celebrity stories's slide shows image of celebrity

Environment:
amp version 2004142327160
Chrome 81.0.4044.92
FFox 75.0 
Safari 13 
<img width="1223" alt="Screen Shot 2020-04-15 at 4 05 59 PM" src="https://user-images.githubusercontent.com/37351864/79397943-3c9a6600-7f34-11ea-9e22-e44668778cde.png">

**Comment by Ichigo3d** [comment]
This issue is appearing under amp version 2004152339120 too

**Comment by ericfs** [comment]
It looks like there just is no image so the story is rendered correctly:

```
<amp-story-grid-layer template="vertical" class="tp-content no-image wallpaper "><div class="main-text-block">
      <div class="timeline first-km">
      <div class="date active" animate-in="fly-in-right"
      animate-in-duration="0.2s">
        <span animate-in="fade-in" animate-in-duration="0.2s">
          1988
        </span>
      </div>
        <div class="line" animate-in="fade-in" animate-in-duration="0.3s"
        animate-in-delay="0.1s"></div>
        <div class="date" animate-in="fly-in-right" animate-in-duration="0.2s">
          <span animate-in="fade-in" animate-in-duration="0.3s">
            2000
          </span>
        </div></div><div class="sentence" animate-in="fly-in-right"
        animate-in-duration="0.3s"><span animate-in="fade-in"
        animate-in-duration="0.4s" class="web-scraped-sentence">
      Emily Jean "Emma" Stone was born on November 6, 1988, in Scottsdale, Arizona.
         </div>
       </div>
</amp-story-grid-layer>
```

**Comment by ericfs** [comment]
That's from: https://www.google.com/search/static/gs/m09yhzs.html

**Comment by Ichigo3d** [comment]
Ok, got it. Closing issue
