### ISSUE TITLE
[amp-script] Lightbox doesn't work in created images

### ISSUE THREAD

**Issue by alexandr-kazakov** [ampproject/amphtml#27808]
I use **amp-script** to add new images to the page, but **amp-lightbox-gallery** doesn't work in them.

I asked my question on stackoverflow: https://stackoverflow.com/q/61162755/7460038 there is a working example and code.

How do I make amp-lightbox-gallery work with these images and do you plan to add this feature in the future?

**Comment by samouri** [comment]
Sorry to report this, but `amp-script` [does not support](https://amp.dev/documentation/components/amp-script/#creating-amp-elements) creating lightboxed images dynamically. This is something we are working to address with part of [Bento](https://blog.amp.dev/2021/01/28/bento/), but I don't have an estimate of when this will fully launch. 

Deduping with: https://github.com/ampproject/amphtml/issues/25344
