### ISSUE TITLE
AMP Base Carousel pagination-next arrow not functioning properly

### ISSUE THREAD

**Issue by stephengardner** [ampproject/amphtml#27817]
When advancing slides, the final amp-base-carousel pagination arrow remains, even when on the last slide.  Arrow remains visible, not blurred out, and un-functional, causing confusion. 

Test:
8 simple slides 
advance-count="4"
visible-count="4".
Advance one time.
Arrow remains.

Codepen:
https://codepen.io/jquery-examples/project/editor/Xmwyno

**Comment by chrjs75** [comment]
I have the same issue. The next arrow button is not disabled (i.e. the disabled attribute is not added in the HTML) when the carousel reach the end, so it causes malfunctions if clicked.
The disabled attribute seems to be properly set in the prev arrow button, at least until the broken next button is clicked after reaching the end.

**Comment by chrjs75** [comment]
Any feedback on this? This seems to me a major issue of amp-base-carousel.
