### ISSUE TITLE
Remove the concept of services and its intricacies

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#27810]
We would like to reduce the complexity of retrieving modules. Conceptually it seems that this service retrieval code (like service locators) can be conceptually replaced by async imports.

Would like to start a conversation on if this feasible.

**Comment by erwinmombay** [comment]
@dvoytenko @jridgewell would like to start a conversation on this

**Comment by dvoytenko** [comment]
We will definitely be changing services architecture, but I'm not sure it will go where you hope it will. It's still not a super simple `export Service1` sort of thing. We are most likely to be moving toward something similar to React's [contexts](https://reactjs.org/docs/context.html). These are inherently side-effecty. I think we can possibly remove side-effects and bring them closer to what you want. However, we have an added need to set them on the DOM nodes. I'm actually currently prototyping this nuance. Once I have it, we should discuss and see if we can satisfy both requirements.

Another nuance: some services are auto-install. So we need to decide how to do that. Auto-install is a side-effect as well. I think at least 20% of our services are auto-install at this time. For instance, amp-access services.
