### ISSUE TITLE
amp-consent allow full screen after promptTrigger: action

### ISSUE THREAD

**Issue by micajuine-ho** [ampproject/amphtml#27819]
[Link to original issue](https://github.com/ampproject/amphtml/issues/26197#issuecomment-598639396)

We had originally disallowed amp-consent to enlarge the 3p consent iframe, until user-interaction with the `promptUi` had been detected. 

It seems reasonable to also allow the 3p iframe to enlarge if the `promptTrigger: action`  signal is sent from a button to amp-consent as well.

/cc @zhouyx

**Comment by micajuine-ho** [comment]
@hrkhal & @ptrickney Change has been merged. It will be available in next Tuesday's Canary cut/today's [nightly build](https://amp.dev/documentation/guides-and-tutorials/learn/spec/release-schedule/#nightly).

**Comment by hrkhal** [comment]
@micajuine-ho This issue seems to have crept back in again, using v2007102309001.
