### ISSUE TITLE
I2I: Add Usercentrics CMP to amp-consent

### ISSUE THREAD

**Issue by Usercentrics-AMP** [ampproject/amphtml#27823]
## Summary

Usercentrics is a market leader in the area of enterprise consent management platforms (CMP) and empowers companies to obtain, manage and document the consent of their users across platforms.

## Design document

The design will follow the official design and implementation guidelines.

## Motivation

We want to provide an AMP integration for our customers

/cc @ampproject/wg-approvers

**Comment by zhouyx** [comment]
👍 Yes please. 
https://github.com/ampproject/amphtml/blob/master/extensions/amp-consent/integrating-consent.md
Please refer to the instruction above. Let me know if there's any question. Thank you

**Comment by Usercentrics-AMP** [comment]
Closing because MR was merged.
