### ISSUE TITLE
Remove haptic feedback on story page long press.

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#27830]
You can pause a story page and its content with a long press. However, this long press triggers a haptic feedback (vibration) on Android, that we should remove.

cc @ampproject/wg-stories

**Comment by MaxBittker** [comment]
@gmajoulet do you know if this is the same haptic feedback as on iOS?

**Comment by gmajoulet** [comment]
Back when I filed this ticket (just 2 months ago) this was not happening on iOS. But it is the long press haptic feedback, so I assume they're the same.

**Comment by gmajoulet** [comment]
Closing: infeasible.
