### ISSUE TITLE
The extension 'amp-wistia-player' was found on this page, but is unused. Please remove this extension

### ISSUE THREAD

**Issue by gerardorm** [ampproject/amphtml#27831]
Recently I added this extension in order to use the wistia player. After adding all my pages that don't have a wistia element are getting that error message, and the page is not validated successfully.

Is this the desired behavior? or is it an AMP known issue?.

![image](https://user-images.githubusercontent.com/14027305/79594180-6e750f00-8091-11ea-83e5-cd2502ecccb3.png)

**Comment by caroqliu** [comment]
Thanks for filing this issue! Can you share more information such as a minimal sample markup of your page that causes the error?
