### ISSUE TITLE
🚀Launch Programmatic Story Ads Task List

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#27851]
Publishers are currently only able to use custom or reservation based story ads in their AMP Stories. This is tracking the launch of programmatic demand to this inventory.

- [x] Enable `adsense` in `amp-story-auto-ads` for e2e testing
- [x] Run experiment
- [x] Write docs

/cc @raovs

**Comment by lucemia** [comment]
@calebcordry 

I would like to know currently `amp-story-auto-ads` not support `adsense` yet is due to there is no demo and docs, 
or there is other reasons?

**Comment by calebcordry** [comment]
@lucemia we are currently working on its implementation. We should have an update for you soon.

**Comment by saurabhsdev** [comment]
Hey @calebcordry is there any update regarding amp-story-auto-ads for AdSense?

**Comment by calebcordry** [comment]
Hi all story ads for adsense have been launched! Please see the docs at https://support.google.com/adsense/answer/10175505?hl=en
