### ISSUE TITLE
amp-script tag sample in amp.dev does not work by default

### ISSUE THREAD

**Issue by zarar3333** [ampproject/amphtml#27878]
## amp-script tag does not work properly
the javascript code not working in amp-script tag.

**Comment by patrickkettner** [comment]
hi @zarar3333!

Could you share the code you are attempting to use?

**Comment by zarar3333** [comment]
the amp-script not working in amp playground tutorial.
You see this code and preview [https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-script](url)

**Comment by caroqliu** [comment]
It appears the console prints the `Script hash not found` error in the AMP playground example included above. There is a helpful section on [common errors and how to debug them](https://amp.dev/documentation/components/amp-script/#errors).

I'm not sure there is a way to work around this in the playground example -- do people trying `amp-script` out in the playground always have to manually replace the hash? @choumx @kristoferbaxter

**Comment by choumx** [comment]
Developers can add `data-ampdevmode` to disable script hash check during development. Details here: https://amp.dev/documentation/components/amp-script/#security-features

**Comment by zarar3333** [comment]
Great, thank you
