### ISSUE TITLE
🌸 Cherry-pick request for #27802 into #27765 (Pending)

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#27889]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #27802 | #27806 |     **YES**     | **NO** | **NO** | #27765 |

**NOTE:** Breaking change (#27773) made it to nightly release 2004191437490, and it's cut as part of a not-yet released Beta.

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

Prevents a large set of `<amp-animation>` configurations from executing.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

Web Animations were forced to be polyfilled on Safari due to an issue with native support rolled out on WebKit 13.1. The [method to accomplish this](https://github.com/ampproject/amphtml/pull/27773) caused `<amp-animation>` to throw an error in some cases, since the polyfill would try to run a method on an empty object (`{}.cancel()`).

## Impact

- Documents with more than one `<amp-animation>` element on Safari. (Unsure of %)
- `<amp-animation>` does not execute for these cases.

## Action Items

- #27888: End-to-end test for constructing an animation and ensure it doesn't `throw`

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers @dvoytenko

**Comment by dvoytenko** [comment]
Approved.

**Comment by estherkim** [comment]
On-duty here, thanks for letting me know! Instead of taking 2004191437490, we'll take the nightly generated tonight and promote it to opt-in. That will include your fix and no cherry-pick is needed.

That said, can you update the issue description to remove references to Beta, 2004172112280? It's a bit confusing!

**Comment by alanorozco** [comment]
Discussed offline with @danielrozenberg and @estherkim: Instead of cherry-picking, we'll use tonight's cut as tomorrow's Beta.
