### ISSUE TITLE
Extend amp-audio's analytics to include listen duration

### ISSUE THREAD

**Issue by Spengreb** [ampproject/amphtml#27882]
The amp-audio analytics component does not support how long a user was listening in the case that a user leaves the page without hitting the pause button. 

I propose a feature to include an 'audio-seconds-played' similar to the amp-video's 'video-seconds-played' where the trigger is fired every interval seconds when the audio is playing. This interval would be configurable in a similar way. This seconds played metric would be useful for static audio and audio streams.

**Comment by caroqliu** [comment]
cc @ampproject/wg-analytics
