### ISSUE TITLE
amp-list: Loading indicator sometimes never hidden

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#27902]
Race: If the `toggleLoading(true)` call in `viewportCallback` happens after the `toggleLoading(false)` call in amp-list.js, the loading indicator is unexpectedly displayed and never hidden. 

I think affects components that override `isLoadingReused()` (amp-list and amp-twitter) because this clause doesn't do the right thing for the first render: https://github.com/ampproject/amphtml/blob/62248e7ade786d78afa6fd8a0f24a6b3697d2afb/src/custom-element.js#L1630

Noticed this on examples/amp-list.amp.html. The JSON fetch needs to be very fast in order to win the race, so might not happen often in the wild.

**Comment by samouri** [comment]
Wow. Great catch. So I think the race here is actually between `viewportCallback` and `layoutCallback`. If layoutCallback completes before the timer in vC fires, then we get the zombie loading indicator.

The `toggleLoading(false)` that we have in amp-list should only be necessary for layouts after the initial one.
