### ISSUE TITLE
I2I: PubMatic Amp-ad GDPR/CCPA support

### ISSUE THREAD

**Issue by pm-harshad-mane** [ampproject/amphtml#27927]
## Summary
How to add support for passing GDPR and CCPA consent in ad-request from amp-ad?
Can somebody help here?

/cc @ampproject/wg-approvers

**Comment by zhouyx** [comment]
Hello @pm-harshad-mane Have you tried https://github.com/ampproject/amphtml/blob/master/ads/README.md#amp-consent-integration

Let me know if there's any question.

**Comment by pm-harshad-mane** [comment]
Thanks @zhouyx for a quick reply.
I am wondering how our code will know if the provided consent is GDPR consent or CCPA consent string?

**Comment by zhouyx** [comment]
There's a feature request for AMP to pass the consent type information as well. #27907 
Before that's added, we learnt that people determine the consent string type based on the length.

**Comment by pm-harshad-mane** [comment]
sounds good @zhouyx .
Thank you for your help :-)

**Comment by micajuine-ho** [comment]
Closing this now, feel free to reopen with any questions or concerns :)
