### ISSUE TITLE
Fix Java validator tests and merge maven upgrade PRs

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#27939]
I'm filing this as a tracking issue based on the conversation starting at https://github.com/ampproject/amphtml/pull/27842#issuecomment-617553437.

There are two things to do:

- [ ] Fix the Java validator [test failures](https://travis-ci.org/github/ampproject/amphtml/jobs/677960140#L375-L550).
- [x] Merge the [backlog](https://github.com/ampproject/amphtml/pulls?q=is%3Apr+is%3Aopen+%22validator%2Fjava%2Fpom.xml%22+sort%3Aupdated-desc) of package upgrade PRs for the Java validator that are all blocked by the test failures. (Done in #27951 and #28032)

**Comment by rsimha** [comment]
Assigning to @honeybadgerdontcare for triage

/cc @ampproject/wg-caching

**Comment by honeybadgerdontcare** [comment]
//cc @GeorgeLuo the first task is being handled in #27842.

I think we should do a manual update since there are so many outstanding but would like confirmation from @GeorgeLuo first.

**Comment by GeorgeLuo** [comment]
That's a reasonable course, from a usability perspective the tests will fail already, changing the dependencies has a neutral-positive effect in the current state.

**Comment by GeorgeLuo** [comment]
The changes to catch up the engine to yesterday's changes are somewhat expansive. I'm working on porting them over, but the whole of the changes this won't be resolved today. Can the upgrade PRs be forced through? Or are you guys waiting for a PR from my end to compile all of them?

**Comment by rsimha** [comment]
I’m leery about force-merging all those dozen plus PRs because it involves using admin privileges. Would you able to put them together into a single PR? I can help by force-merging it for you.

**Comment by Gregable** [comment]
@GeorgeLuo As an aside, one of the commits in yesterday's changes is separated out as a formatting-only change. That may help with porting, as that specific commit can be ignored.

**Comment by GeorgeLuo** [comment]
got it thanks 👍I was somewhat aware, but separating out by commit will be handy.

**Comment by rsimha** [comment]
@GeorgeLuo Looks like we have a [new batch](https://github.com/ampproject/amphtml/pulls?q=is%3Aopen+is%3Apr+author%3Arenovate-bot+%22validator%2Fjava%2Fpom.xml%22) of updates that came in today. I've currently labeled / assigned them to @ampproject/wg-caching folks.

(I recognize that this is a glut of PRs to deal with, but once we're all caught up, the updates should be much less frequent.)

**Comment by GeorgeLuo** [comment]
Ack. I started and scoped the changes yesterday. It'll be hard to estimate when they can go in, if significant unit test changes need to be implemented. So I may aggregate the dependency changes for a PR if those take an exorbitant amount of time.

**Comment by GeorgeLuo** [comment]
@rsimha can you clarify the state of this job? As I understand it the completion of `gulp validator-java ` is no longer a predicate to completing the job. So why did java come into play in the [latest travis job](https://travis-ci.org/github/ampproject/amphtml/jobs/686329451)? Was the logic added to watch for changes to under _validator/java_ path? thank you

**Comment by rsimha** [comment]
> As I understand it the completion of `gulp validator-java ` is no longer a predicate to completing the job.

Successful completion of `gulp validator-java` is not a requirement for PRs that do not touch `validator/java`.

> So why did java come into play in the [latest travis job](https://travis-ci.org/github/ampproject/amphtml/jobs/686329451)? Was the logic added to watch for changes to under _validator/java_ path?

Correct, it is a requirement for code that does touch that directory, to prevent _new_ breaking changes from being merged. Here's the logic (notice the presence / absence of `OrDie`):

https://github.com/ampproject/amphtml/blob/aca8b111c3a3e3d3133edfb2ffaa8acf38bed60c/build-system/pr-check/validator-tests.js#L77-L81

**Comment by GeorgeLuo** [comment]
Ah awesome, thanks. The system works!

**Comment by Gregable** [comment]
I think this has already been resolved last year. If I'm missing something, please reopen.
