### ISSUE TITLE
BlueConic amp-analytics vendor

### ISSUE THREAD

**Issue by paulrutter** [ampproject/amphtml#27930]
We at [BlueConic ](http://www.blueconic.com) are kicking off a project to build official support for AMP. This will require a new set of APIs on our side and a contribution to this project in order to make BlueConic an analytics vendor option.

The intention is to track the page visits and events on the AMP pages. Now we track the web- and mobile traffic. But miss all the data of the AMP visits to give more insights to the AMP traffic we want to give our customers the option to track there traffic on AMP pages as well.
We plan to have our implementation store a prefixed cookie using the cookies config option. In addition, we plan to leverage the linkers field to support cross-domain session tracking.

cc @ampproject/wg-approvers

**Comment by micajuine-ho** [comment]
SGTM, feel free to assign me as a reviewer once your PR is out.

**Comment by paulrutter** [comment]
@micajuine-ho The PR has been pushed.

**Comment by bc-stef** [comment]
When will the merged pull request be deployed and live? Try to connect with the amp-analytics type="blueconic" but no response yet. And when are we added to this list: https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/configure-analytics/analytics-vendors/?format=websites

**Comment by micajuine-ho** [comment]
You can opt into the nightly builds, where it should be out already or the weekly build (canary) where it will be out next week. 

Checkout out our release documentation for more info.
https://amp.dev/documentation/guides-and-tutorials/learn/spec/release-schedule/

If you do not want to opt into any of these releases, this change will be out in production on Jun 1.
