### ISSUE TITLE
Feature Request: support whatsapp in amp-social-share

### ISSUE THREAD

**Issue by gam-phon** [ampproject/amphtml#2794]
Using Custom URL Scheme.
When pressed, whatsapp will be opened with predefined text and link to share it.
For example:

    <a href="whatsapp://send?text=....."/>

https://www.whatsapp.com/faq/en/iphone/23559013

**Comment by ericlindley-g** [comment]
This would be great—slotting into the backlog

**Comment by mkhatib** [comment]
Closing in favor #2831
