### ISSUE TITLE
🌸 Cherry-pick request for #27940 into #27908 (Approved)

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#27947]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #27931 | #27940 |     **YES**     | **NO** | **NO** | #27908                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

Prevents all `<amp-video>` elements from executing on IE.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

`NodeList` is typed to allow `forEach()`, while IE11 doesn't support it. A recent change uses this method on a `NodeList`.

## Impact

- All `<amp-video>` users on IE.
- Complete loss of functionality in this case.

## Action Items

---

/cc @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by dvoytenko** [comment]
Approved.
