### ISSUE TITLE
Hover/Long press on the remote attachment UI should show full URL

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#27941]
Web browsers allow users to preview links href by hovering them on desktop or long pressing (context menu) on mobile.

Story remote page attachments should offer this feature on the "swipe up" call to action UI visible at the bottom of a story page.

cc @ampproject/wg-stories

**Comment by MaxBittker** [comment]
I changing this element to an <a> tag with an href, but long press on mobile is not triggering the desired pop-up yet. 

Now investigating what other handler may be co-opting that event.

**Comment by processprocess** [comment]
Just to clarify, is this the goal?
<img width="788" alt="Screen Shot 2020-12-16 at 2 32 51 PM" src="https://user-images.githubusercontent.com/3860311/102397231-9cf21380-3fab-11eb-8dc5-8849739cb4e1.png">

**Comment by gmajoulet** [comment]
Yes, basically the default behavior of a `<a href=""`
