### ISSUE TITLE
Add runtime test pages to gulp performance config

### ISSUE THREAD

**Issue by estherkim** [ampproject/amphtml#27955]
We want to use Travis to measure performance of AMP components compared to stable v0.js.

To start, can @ampproject/wg-runtime  add test pages to https://github.com/ampproject/amphtml/blob/master/build-system/tasks/performance/config.json#L7 ?

Once we have at least one URL, we'll run `gulp performance` on master builds, with the option to move it to nightly builds.

Test pages are served on `localhost:8000` so if you want to add  `examples/bind/basic.amp.html`, it would look like

```
{
  "handlerName": "defaultHandler",
  "urls": [
    "localhost:8000/examples/bind/basic.amp.html"
  ]
}
```

 No external websites please! Thanks

**Comment by choumx** [comment]
@samouri @estherkim Looks like some of the newly added runtime fixtures are causing volatility flakes.

> http://localhost:8000/examples/runtime/article.html
x maxFirstInputDelay

> http://localhost:8000/examples/runtime/images.html
x firstPaint
x firstContentfulPaint
x largestContentfulPaint

https://travis-ci.org/github/ampproject/amphtml/jobs/707779408
https://travis-ci.org/github/ampproject/amphtml/jobs/707708140
https://travis-ci.org/github/ampproject/amphtml/jobs/707401263
https://travis-ci.org/github/ampproject/amphtml/jobs/707011873
