### ISSUE TITLE
[amp-stories] Story invisible after returning from remote attachment

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#27981]
## What's the issue?

When swiping up on a remote attachment to a link that opens an external app (e.g. a YouTube link), going back on android return the user to the story but the story is invisible. I think the opening animation remains open and hides the story.

![ezgif-6-16ea010cb30e](https://user-images.githubusercontent.com/4594196/80089207-da59ea80-855d-11ea-944d-af378de33a1a.gif)

## How do we reproduce the issue?

Open a remote page attachment with a youtube link on an android device with YouTube installed. Going back to the story should show a blank page.

## What browsers are affected?

All browsers I think.

## Which AMP version is affected?

Latest since it's the first with remote attachments

**Comment by cpauwels** [comment]
Pinging @gmajoulet since I think you're working on the remote attachment :)

**Comment by gmajoulet** [comment]
That's very interesting, I completely forgot to test deep links to native apps. I'll work on a fix, thanks for the report!

cc @ampproject/wg-stories
