### ISSUE TITLE
Structured data error Google - w/ full amp validation on console

### ISSUE THREAD

**Issue by dothebangthingsalon** [ampproject/amphtml#2799]
## Short description of your issue:

Google is not indexing page despite amp validation in dev console.  States structured data missing.  Unsure what is missing.  Please advise.

## How do we reproduce the issue?

Please post a public URL and ideally post a reduced test case. E.g. on jsbin.com that exhibits only your issue and nothing else.

1. Step 1 to reproduce
https://dothebangthingsalon.com/amp/#development=1
2. Step 2 to reproduce
Open Dev console
3. Step 3 to reproduce
https://developers.google.com/structured-data/testing-tool/?url=https%3A%2F%2Fdothebangthingsalon.com%2Famp%2F
<img width="759" alt="screen shot 2016-04-02 at 12 18 13 pm" src="https://cloud.githubusercontent.com/assets/16827125/14228298/d1fc54c0-f8cd-11e5-957a-f5868e22a774.png">

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1458844805881

**Comment by adewale** [comment]
This isn't an issue with AMP. Please raise this in the Webmaster Support forums: https://productforums.google.com/forum/#!forum/webmasters
