### ISSUE TITLE
Remove idleRenderOutsideViewport()

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#28012]
Only used by `amp-ad-network-doubleclick-impl` and confirmed OK to remove by ads team.

**Comment by choumx** [comment]
Self-assigning for weekend #mariekondo.

**Comment by calebcordry** [comment]
Took me a bit to realize what happened here. IIUC with the even with exp turned off any ad unit not using `data-loading-strategy` will have this value set to `12`, explaining why elimination of this feature would have such measurable impact.

https://github.com/ampproject/amphtml/blob/5365f610383b3b91d487ffb8f82723e25889f6be/extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js#L356

**Comment by choumx** [comment]
Yea, also confusing since `idleRenderOutsideViewport` is supposed to return a boolean.

**Comment by choumx** [comment]
Closing as obsolete.
