### ISSUE TITLE
`TIMEZONE_CODE` not working in `<amp-state>` src URL

### ISSUE THREAD

**Issue by walling** [ampproject/amphtml#28034]
## What's the issue?

Including the [`TIMEZONE_CODE` variable](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#timezone-code) in the URL of `<amp-state>` doesn't produce the desired result. It seems that only the `TIMEZONE` part is replaced with the UTC offset and the `_CODE` remains in the URL, sent to the server.

## How do we reproduce the issue?

Example code:

```html
<amp-state id="tz" src="https://enilxqlk7kab.x.pipedream.net/?tz_code=TIMEZONE_CODE"></amp-state>
```

Example on JS Bin: https://jsbin.com/xogulewizi/edit?html,output

Request bin (to see the requested URL): https://requestbin.com/r/enilxqlk7kab/1b2Fs8Fquro580l7hUwny2F1HPO

Step-by-step instructions:

1. Go to JS Bin example; the url will be requested
2. Go to Request bin and see the latest requested url

Expected url path: <tt>/?tz_code=**Europe/Berlin**&__amp_source_origin=https%3A%2F%2Fnull.jsbin.com</tt>

Actual url path: <tt>/?tz_code=**-120_CODE**&__amp_source_origin=https%3A%2F%2Fnull.jsbin.com</tt>

My local UTC offset is -120, so it seems `TIMEZONE_CODE` became `-120_CODE`, i.e. only part of the variable name was replaced.

## What browsers are affected?

I tested on Chrome, Firefox, and Safari on Mac OS X as well as Safari on iPhone (13.3.1). The bug is the same in all these browsers.

## Which AMP version is affected?

Tested on AMP ⚡ HTML – Version 2004172112280.

**Comment by micajuine-ho** [comment]
Hi @walling, `TIMEZONE_CODE` was removed from the platform variables and now is only available through amp-analytics (#26896). It looks like the documentation was not updated to reflect this change; sorry about that.
