### ISSUE TITLE
amp-soundcloud and soundcloud playlists...

### ISSUE THREAD

**Issue by alvin-milton** [ampproject/amphtml#2808]
## Short description of your issue:

**amp-soundcloud** tag doesn't render soundcloud playlists.
## How do we reproduce the issue?

Use the amp-soundcloud tag to render this markup

`<iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/34709617&color=ff5500"></iframe>`
## What browsers are affected?

All browsers are affected
## Which AMP version is affected?

Current version is affected.

**Comment by malev** [comment]
I wonder if there is still interest on having this one done. I definitely need it to be working 😄
