### ISSUE TITLE
add `amp` namespace for `hidden` and `active` classes when applicable

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#281]

**Comment by dvoytenko** [comment]
Changed `-amp-hidden` request to `amp-hidden`. As discussed, there's no need to "hide" this class.

**Comment by erwinmombay** [comment]
@dvoytenko same for `-amp-active` -> `amp-active` correct?

**Comment by dvoytenko** [comment]
Yep. Let's defer this a little though. A lot of changes are brewing here. Probably can do next week.,

**Comment by erwinmombay** [comment]
SGTM

**Comment by erwinmombay** [comment]
obsolete. current classes should all be prefixed with `amp-${state}`
