### ISSUE TITLE
amp-form: Presence of verify-xhr breaks forms on pages served by AMP Cache

### ISSUE THREAD

**Issue by westonruter** [ampproject/amphtml#28103]
## What's the issue?

Given the `amp-form` example: https://preview.amp.dev/documentation/examples/components/amp-form#verification-username

There is this “Form Verification: as-you-go” example:

> ![image](https://user-images.githubusercontent.com/134745/80618015-a6684480-89f7-11ea-86b5-0b378fa67bac.png)

Normally if I type “error” then the result is:

> ![image](https://user-images.githubusercontent.com/134745/80618374-255d7d00-89f8-11ea-8126-eb953224b84a.png)

But putting something something else in the field and pressing “Check” results in: 

![image](https://user-images.githubusercontent.com/134745/80618434-3b6b3d80-89f8-11ea-9c01-2fbd7e4cab2d.png)

_Hoever_, **now try the same for the page served by the AMP Cache**: https://preview-amp-dev.cdn.ampproject.org/c/s/preview.amp.dev/documentation/examples/components/amp-form#verification-username

Nothing happens after entering “error” and hitting tab:

> ![image](https://user-images.githubusercontent.com/134745/80618573-68b7eb80-89f8-11ea-98ec-0818a2eb642f.png)

There is actually an error in the console that was added when the page loaded:

> Error: form verify-xhr should not be on AMP CDN: form​​​
> ![image](https://user-images.githubusercontent.com/134745/80618749-a452b580-89f8-11ea-9e72-2e90b76b35c8.png)

Trying to put in another value and clicking “Check” does nothing: 

> ![image](https://user-images.githubusercontent.com/134745/80618831-c2b8b100-89f8-11ea-80f0-cd3b55738c7a.png)

## How do we reproduce the issue?

Create a form with a `verify-xhr` attribute and access the containing page on the AMP Cache.

Try the “Form Verification: as-you-go” form example: https://preview-amp-dev.cdn.ampproject.org/c/s/preview.amp.dev/documentation/examples/components/amp-form#verification-username

## What browsers are affected?

All browsers.

## Which AMP version is affected?

v2004240001480

**Comment by westonruter** [comment]
cc @ampproject/wg-caching

**Comment by westonruter** [comment]
cc @ampproject/wg-ui-and-a11y

**Comment by alanorozco** [comment]
It seems like the cache should transform `verify-xhr` into an absolute origin URL like it does for `action-xhr`.

**Comment by Gregable** [comment]
Fixed on AMP Cache in change id `310025020`. Will likely be released this week.
