### ISSUE TITLE
amp-slider interactions tests flaking on Travis

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#28116]
Sample builds: https://travis-ci.org/github/ampproject/amphtml/jobs/681051172 , https://travis-ci.org/github/ampproject/amphtml/jobs/681006253

The exact test varies, but this family of tests seems to be semi-regularly encountering timeout issues. The flakes appear across Single Pass Tests, Remote Tests, and End To End Tests.

/cc @ampproject/wg-ui-and-a11y since I don't see any recent meaningful edits to the tests or source

**Comment by rcebulko** [comment]
Test skipped in https://github.com/ampproject/amphtml/pull/28113#event-3286591004

**Comment by rcebulko** [comment]
@wassgha edited recently, do you know who the owner of this component is?

**Comment by wassgha** [comment]
This was an intern project, the two interns who worked on it are no longer actively contributing unfortunately

**Comment by rsimha** [comment]
Reopening because the skip PR did not actually fix this issue.

Logs for posterity, since the original Travis builds may have been restarted:

```
DESCRIBE => amp-image-slider
  DESCRIBE => amp-image-slider
    DESCRIBE =>  
      IT => "before each" hook for "pressing Home should move slider bar to center when slider is focused"
        ✗ Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```
