### ISSUE TITLE
Reintroduce <amp-story-cover>

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#28117]
Practically speaking, we want different behavior for the first page of stories, for a number of reasons:

1. The first actual page of the story should be a "cover page" containing information about the story, such as it's title, publisher, publication date, etc.
2. The first page of a story that the user views (which is not necessarily the first page of the story, since people can deep link to other pages, but there's definitely a correlation) should be lighter weight to improve performance on cold loads.
3. Single-page "stories" with CTAs should be avoided, as they can come off as spammy.

With all of this combined, I believe the first page of a story acts sufficiently different to warrant its own component, to help enable and clarify validation rules.  For example, we should have:

- No `amp-story-cta-layer` on the first page of a story
- No `amp-story-page-attachment` on the first page of a story
- No `amp-story-quiz` or similar on the first page of the story
- Perhaps this should also apply to embeds like tweets, etc

I think we could get to this state by:

1. Implement JS runtime enforcement of the rules above.  Publisher stories will fail with console errors, but no validation errors.
2. Implement `amp-story-cover` with validation rules for the above
3. Trigger a warning when the first page of a story is not `amp-story-cover`, encouraging its usage due to the clearer validation rules.

/cc @ampproject/wg-stories WDYT?

**Comment by cpauwels** [comment]
I think this is a good idea for editorial stories, but it's also limiting and opinionating stories to be editorial only. We're seeing demand for marketing stories, and customers want to have a CTA on the first page. 

I think the other way around the issue of spammyness could be to require at least two amp-story-pages for stories to be AMP valid.
