### ISSUE TITLE
Consent: Allow vendors to listen to user consent update

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#28112]
Users can resurface the consent dialog and change their choices. AMP supports this via the `postPromptUI` or the `prompt` action. 

AMP Consent also needs to provide callback to vendors to access any update.

**Comment by zhouyx** [comment]
I lowered the priority of this task because we haven't heard similar request from ad/analytics vendors. 
Happy to prioritize if there's such a feature request.

**Comment by HeinzBaumann** [comment]
TCFv2 supports a notification mechanism for when change to the consent string happened and when the CMP is initiated/closed. For TCFv2 vendors and CMP providers it is important to have a this support in AMP. Not sure why this is closed. When a interest group like IAB is requesting they do speak for their ad vendor and cmp vendors.

**Comment by zhouyx** [comment]
Hello @HeinzBaumann, I understand this is some feature that's missing. To clarify the request was de-proritized not closed. 

We have indeed discussed this with the IAB team and a few TCFv2 ad vendors. As far as we were told, updating the consent string on page load is sufficient. I am not aware of any AMP integrated ad vendors who listen to consent update after the ad request has been sent out. Please let us know if you know ad vendors who relies on such listener, and we're happy to prioritize the feature. Thanks 

(I don't believe this is related to CMP providers. Instead it's the CMP which informs AMP of any consent update not vice versa.)

**Comment by levin-roski** [comment]
As there are more components then just ads, tracking and pixels, I would like you to reconsider the de-prioritization as there are some UI components like amp-youtube and amp-recaptcha, which are sometimes really important for user experience.
See this use case: https://github.com/ampproject/amphtml/issues/15406#issuecomment-662520421

If the components directly render or de-render on consent-change it would bring less hustle than a full page reload.
I'm not sure if I understood the FR correctly and whit relevance to #15406
