### ISSUE TITLE
Cached video sources should always take precedence.

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#28136]
Cached video sources should always take precedence.

From [this cached document](https://www-refinery29-com.cdn.ampproject.org/v/s/www.refinery29.com/stories/amp/how-to-be-an-influencer-eugenie-grey/?amp_js_v=0.1&usqp=mq331AQFKAGwASA%3D#origin=https%3A%2F%2Fwww.google.com&prerenderSize=1&visibilityState=prerender&paddingTop=0&p2r=0&horizontalScrolling=0&csi=1&aoh=15882617234705&viewerUrl=https%3A%2F%2Fwww.google.com%2Famp%2Fstory%2Fs%2Fwww.refinery29.com%2Fstories%2Famp%2Fhow-to-be-an-influencer-eugenie-grey%2F&history=1&storage=1&cid=1&cap=navigateTo%2Ccid%2CfullReplaceHistory%2Cfragment%2CreplaceUrl%2CiframeScroll), if a publisher adds different transcodes for a video, our cache infrastructure will replace the source with the cached source and keep the same `<source>` element index.
If a transcode with a smaller index is not cached, it would take precedence over the cached one.

Eg:
- Publisher provides one HLS source, one MP4 source
- Cache infrastructure adds a cached URL for the MP4 source
- AMP runtime generates: (0) HLS source, (1) MP4 cached source, (2) MP4 origin source

I believe we should change this order and make it (1), (0), (2).

cc @ampproject/wg-stories 
cc @cramforce FYI

**Comment by cramforce** [comment]
+1. I think this should be implemented as a sort function on the client side when moving sources from the custom element to the video element. This would also be the right hook to later implement bandwidth-selection.

**Comment by gmajoulet** [comment]
From @cramforce about the optimal sources order:

> If the cache works, but you get a decode error, then you want cached, cached, non-cached, non-cached
> If the cache 404s the current order is better

**Comment by gmajoulet** [comment]
This might actually already be working.

**Comment by cramforce** [comment]
This might have been fixed by your change to always wait for the component to init from the media pool.

**Comment by cramforce** [comment]
Maybe we should add a test :)
