### ISSUE TITLE
Incorrect height of amp-consent when navigation bar is displayed

### ISSUE THREAD

**Issue by MaximePlancke** [ampproject/amphtml#28133]
## What's the issue?

`amp-consent` is loading an Iframe which takes 100vh when the full screen mode is activated. This 100vh includes the navigation bars on iOS devices and some Android which doesn't let the user scroll down to the bottom of the Iframe. It is a problem for us as we have our action buttons inaccessible. Instead of using 100vh, could you make sure the Iframe takes 100% of the visible height? 

A working solution would be to remove the `height: 100vh` and add 

```
min-height: -webkit-fill-available;
min-height: 100%;
```

It is a blocking issue on our side. Thank you.

## How do we reproduce the issue?

https://sandbox.didomi.io/amp.html

Don't scroll the page, click on Learn More and try to scroll down. You won't be able to reach the bottom buttons. 

## What browsers are affected?

This example is on an iPhone 8 with iOS 13.4 on Safari but you can find this issue on a lot of iOS devices. 

## Which AMP version is affected?

2004240001480

**Comment by micajuine-ho** [comment]
Hi @MaximePlancke  I am unable to reproduce the error with the website you linked. Would you be able to make a gif of the error and post it here?

**Comment by MaximePlancke** [comment]
Hi @micajuine-ho ,

Sure, here it is
![ezgif-5-1a853778fc0b](https://user-images.githubusercontent.com/5814860/80970640-7b139a00-8de9-11ea-8ede-c1d57d287abb.gif)


Don't hesitate if you need more information.
Thank you!

**Comment by micajuine-ho** [comment]
Hi @MaximePlancke,

I have tried to reproduce with safari and an iphone 8 to no avail. Do you notice anything wrong with this?
![image](https://user-images.githubusercontent.com/30711678/81113808-a5db1c80-8ed5-11ea-9b09-06f234490069.png)

**Comment by MaximePlancke** [comment]
Hi @micajuine-ho ,

The Safari responsive mode doesn't properly simulate a real device and the behavior is not 100% accurate. (Example: no navigation bar here). You need to test with Xcode using a simulator or with a real device to be able to see the issue.

**Comment by zhouyx** [comment]
Related to #20100.

**Comment by micajuine-ho** [comment]
@MaximePlancke Thanks for your help! I'm able to repro the issue now. Would you be able to spin up a quick jsbin/example that I can test locally?
