### ISSUE TITLE
AMP Sidebar is hidden due to Safari bottom navigation

### ISSUE THREAD

**Issue by stephengardner** [ampproject/amphtml#28145]
This issue appears to have been fixed by older issues, but has resurfaced.

Stackblitz example: https://stackblitz.com/edit/amp-sidebar-bug?file=index.html

View this page on an iphone: https://amp-sidebar-bug.stackblitz.io

See this result: 
![amp sidebar bug example](https://user-images.githubusercontent.com/7368566/80747400-67b6b500-8af1-11ea-82f5-1d8a98e42675.png)

Related issue: https://github.com/ampproject/amphtml/issues/12998 (closed)

Checked on: iPhone 11 Pro & iPhone XS

**Comment by amanintech** [comment]
This similar issue also occurs in android chrome when you have a full-height content

https://mobile-web.dev

![image](https://user-images.githubusercontent.com/28403318/80914996-e2d7cf80-8d6c-11ea-80e9-686868113458.png)

**Comment by rsimha** [comment]
@ampproject/wg-ui-and-a11y for triage
