### ISSUE TITLE
Support customizing the behaviour of amp-youtube component based on user control 

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#28149]
YouTube PfP (Player for Publishers) partners use the ⁠amp-youtube component to embed their YouTube videos in their AMP pages and traffic their own ads against the video inventory that is generated.
 
When embedding their YouTube videos, partners are able instruct the player to request personalized or non-personalized ads using existing player configuration options. On AMP pages partners are unable to configure this based on user consent. As such, partners leave the nonPersonalizedAd option unset so the player defaults to non-personalized ad requests based on the viewer's location.
 
Could we please look into supporting the ability to customize the amp-youtube component based on whether the user has provided consent to be shown personalized ads?

b/155078790

**Comment by wassgha** [comment]
@rebeccanthomas wanna take a stab at this? I'd set up a quick meeting with @zhouyx from the analytics team to understand `amp-consent`'s API and try to integrate it with `amp-youtube`
