### ISSUE TITLE
Minimum support for browsers like IE11 

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#28152]
From [AMP supported browsers](https://amp.dev/support/faq/supported-browsers/):

> In general we support the latest two versions of major browsers like Chrome, Firefox, Edge, Safari, Opera and UC Browser. We support desktop, phone, tablet and the web view version of these respective browsers.
> 
> Beyond that, the core AMP library and built-in elements should aim for very wide browser support and we accept fixes for all browsers with market share greater than 1 percent.
> 
> In particular, we try to maintain "it might not be perfect but isn't broken"-support for IE 11, iOS 8, the Android 4.0 system browser and Chrome 41.

Let's get consensus on what "it might not be perfect but isn't broken" actually means. 

Also, we can update our special-case version support e.g. `iOS 8` only has 0.23% market share today.

Some data:
- [Browser market share](https://gs.statcounter.com/browser-market-share)
  - Also see [version share](https://gs.statcounter.com/browser-version-market-share). Samsung Internet and Edge 79+ are Chromium-based, so Chrome testing should provide good coverage.
- [Android market share](https://gs.statcounter.com/android-version-market-share/mobile-tablet/worldwide)
  - Also see [Android browser versions](https://decadecity.net/blog/2013/11/21/android-browser-versions) e.g. Android 4.0-4.3 primarily use a WebKit-based "Android browser".
- [iOS (Mobile Safari) market share](https://gs.statcounter.com/ios-version-market-share/mobile-tablet/worldwide)
  - Also see [supported iOS releases by device](https://en.wikipedia.org/wiki/List_of_iOS_devices#Supported_iOS_releases) e.g. `iOS 9.3` is the last supported version for iPhone 4S.

Note that regional market share may differ dramatically e.g. [South Korea has IE11 at 7.6%](https://gs.statcounter.com/browser-version-market-share/all/south-korea) vs. 1.21% globally.

### Proposal

Define "isn't broken" as "user can read an AMP news article, with working primary use cases for the most popular components". 

Most popular components:
```
amp-img
amp-pixel
amp-ad
amp-youtube
amp-carousel
amp-analytics
amp-social-share
amp-sidebar
amp-accordion
```

Maintaining minimum support for browsers then requires drafting an "news article" test fixture containing the above components and writing integration tests for (1) basic runtime functionality like loading resources on scroll and (2) each component use case.

Until we have coverage stats for integration tests, skipped/flaky tests must be fixed with high priority (P1) to avoid loss of coverage over time.

Re: version support, let's bump minimum iOS support to `9.3` (1.53%) and remove Chrome 41 (Googlebot now uses evergreen Chrome). We can consider dropping Android system browser too (0.62%).

/cc @ampproject/wg-ui-and-a11y @ampproject/wg-analytics @ampproject/wg-ads @ampproject/wg-infra @ampproject/wg-runtime

**Comment by alanorozco** [comment]
This makes sense to me. I would like to see an addendum for completeness related to support inside embedded third party services, e.g. we can't guarantee that `amp-youtube` will work if its embedded document doesn't support the same minimum surface.

**Comment by twifkak** [comment]
Ideally, I would like to see a second tier for the next most popular components, with a lower bar. Goes towards "user can read an AMP news article". Something like:
 - doesn't break the rest of the page
 - if its children elements commonly contain "main content" [1], then they're still displayed
 - interactive/dynamic stuff may break

Then after that would be tier 3 components for which no guarantees are made.

Just a straw proposal that I'm making without any personal cost. Those who are actually building stuff should override based on feasibility.

[1] by "main content" I mean like the main column of an article, not header/footer/sidebar

**Comment by jridgewell** [comment]
> e.g. iOS 9.3 is the last supported version for iPhone 5 to iPhone SE.

Nit:
- iOS 9 is the last supported version for 4S, iPad 2, iPad 3, and iPad Mini 1.
- iOS 10 is the last for iPhone 5/C and iPad 4.
- iOS 12 is the last for iPhone 5S, iPhone 6, iPad Mini 2, iPad Mini 3, and iPad Air 1.

**Comment by choumx** [comment]
This is currently blocked on IE support in GH Actions.

**Comment by rcebulko** [comment]
> This is currently blocked on IE support in GH Actions.

IE11 tests are now blocking

**Comment by rsimha** [comment]
Closing because tests have been running on IE for a few months now.
