### ISSUE TITLE
Implement a `gulp release` task to build a complete AMP release

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#28168]
Currently Google is the only body that has the complete picture on how AMP releases are created. As a result, it is not easy for open-source contributors to execute the exact same set of commands and processes without foreknowledge (@mdmower is working on improving the documentation around this, see #27100)

Google has a shell script that performs various other gulp tasks, file moves, and other manipulations to take a code snapshot of the amphtml repository and make a complete, deliverable AMP release.

This effort is three-fold:
* Make the process available for others, e.g., to make self-hosting easier
* Make this a "one command" process - running `gulp release` anywhere should generate the same exact files that the CDN serves
* Reduce the technical debt caused by five years of patch-work on the Google-internal release shell script

// cc @ampproject/wg-foundation-onboarding

**Comment by rsimha** [comment]
Looks like this can be closed?

**Comment by tobie** [comment]
Oh, wow, awesome! Congrats, folks!

**Comment by danielrozenberg** [comment]
> Looks like this can be closed?

Haha a while ago! Yes :)
