### ISSUE TITLE
Trim answer-choice-bounce scale values to save bytes

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#28162]
The `answer-choice-bounce` animations for `amp-story-quiz` use percentage scales that are too granular.  On a 1080x1920 screen, the smallest percentage that could make at least a 1px difference would be 1/1920, which is ~0.0005.  Any granularity beyond that seems like a waste of bytes to me.

Can we trim all of these percentages to 4 decimal places? 

/cc @ampproject/wg-stories

**Comment by mszylkowski** [comment]
Agree, will work on it! Probably even 3/4 points could be enough for the animation to feel the same.
