### ISSUE TITLE
Documentation: amp-bind-recaptcha is not an AMP component

### ISSUE THREAD

**Issue by jmooring** [ampproject/amphtml#28161]
## What's the issue?

Documentation and examples refer to "amp-bind-recaptcha" as if it were an AMP component. It is not.

## How do we reproduce the issue?

See <https://amp.dev/documentation/examples/components/amp-bind-recaptcha/>

![image](https://user-images.githubusercontent.com/335669/80825532-9a72b300-8bae-11ea-8ff6-ea401cbb6497.png)

Also see: <https://amp.dev/documentation/components/amp-bind>

![image](https://user-images.githubusercontent.com/335669/80825693-e58cc600-8bae-11ea-996a-d352022db23e.png)

## What browsers are affected?

NA

## Which AMP version is affected?

NA

**Comment by choumx** [comment]
That's definitely confusing. Thanks for flagging.
