### ISSUE TITLE
AMP Story desktop mode error playing video if reload icon is clicked

### ISSUE THREAD

**Issue by alankent** [ampproject/amphtml#28189]
## What's the issue?

The video on page one and two of the story https://www.usatoday.com/web-stories/10-tips-perfect-burger/ frequently fails to play in desktop view after clicking reload button at end of story.

## How do we reproduce the issue?

I was experimenting with https://www.usatoday.com/web-stories/10-tips-perfect-burger/ on my desktop and was clicking very fast through (fast as I could). I do not think the speed of clicking changes anything. In mobile, the last page comes up with a special end of story experience. On the desktop view the next page button is replaced by a refresh button. 

![image](https://user-images.githubusercontent.com/5702163/81032721-b80d7a00-8e45-11ea-9611-88005a9e1825.png)

If you click this, it seems to go back to page one but the video does not play.

1. Open https://www.usatoday.com/web-stories/10-tips-perfect-burger/ on desktop (the version with multiple pages side by side - I cannot repeat on mobile view showing a single page)
2. Click 12 times on the next page icon to the right
3. The "next" icon changes to a reload icon. Click it again. (So click 13 times in the same spot)
4. The first page of the story is displayed again, but the video does not play. Either it shows a busy icon or an error message saying it cannot display the video (see screenshot).

![image](https://user-images.githubusercontent.com/5702163/81032618-59e09700-8e45-11ea-97b4-907ca5a19715.png)

Note: Once the video did start playing again successfully, even though it displayed an error message saying it could not display the video.

## What browsers are affected?

I tested on Chrome and Safari on MacBook.

## Which AMP version is affected?

I was just looking at the story on desktop. Not sure which versions are affected.

**Comment by gmajoulet** [comment]
cc @ampproject/wg-stories

**Comment by newmuis** [comment]
There are details in #14222
