### ISSUE TITLE
Catch errors in publisher amp-script code

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#28198]
It seems that in cases (example: https://github.com/ampproject/amphtml/issues/27904) where custom amp-script code from publishers causes errors, those errors bubble up into an unhandled promise rejection, and are reported to AMP Error Reporting. This adds noise to error reporting, as the underlying issue is one with publisher code, not with AMP code. These errors should be caught and reported as user errors.

/cc @jridgewell

**Comment by jridgewell** [comment]
Assigning to @samouri
