### ISSUE TITLE
Please pass pageopen time to Ibeat vendor in amp-analytics

### ISSUE THREAD

**Issue by denmark-admin** [ampproject/amphtml#28194]
## Describe the new feature or change to an existing feature you'd like to see

Request you to please provide a mechanism to pass pageopen time to Ibeat vendor in <amp-analytics>. We receive multiple calls for a page through time based trigger. We need all of these request to also have the pageopen time. This is the time when page first became visible. Didn't find such a variable to be passed to our API through time triggers.

## Describe alternatives you've considered

N/A

## Additional context

Requirement: pageopen time in all of our /ping API in ibeat fired every 15 seconds since the page is opened in the browser.

**Comment by micajuine-ho** [comment]
Hi @denmark-admin, we do not explicitly provide a `pageopen` metric, through our substitution vars, however we offer a wide variety of metrics/timers [substitutions available](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#variables). Please take a look at this document and let me know if any of these can satisfy your requirement or let me know if you have any questions.

**Comment by denmark-admin** [comment]
Thanks @micajuine-ho for the reply, `${firstVisibleTime}` looks close. Have some doubts though as of now we are using a timer with frequency 15 seconds to invoke our API

```
  'triggers': {
    'trackInterval': {
      'on': 'timer',
      'timerSpec': {
        'interval': 15,
        'maxTimerLength': 7200,
      },
      'request': 'track',
    },
  },

```
to use `${firstVisibleTime}` it seems we'll have to use `visibilitySpec`. Can you please tell us both `visibilitySpec` and `timerSpec` can be used simultaneously i.e. is the following a valid trigger

```
  'triggers': {
    'trackInterval': {
      'on': 'timer',
      'timerSpec': {
        'interval': 15,
        'maxTimerLength': 7200,
      },
      'visibilitySpec': {
        'selector': ':root'
      },
      'request': 'track'
    },
  },

```
Basically our use-case is to fire our API as soon as the page loads and there after keep on invoking the API every 15 seconds and send the value of pageopen time in every request. The value of pageopen time be same for every call i.e. the first time this page become visible.

**Comment by micajuine-ho** [comment]
Hi @denmark-admin, `${firstVisibleTime}` does not need to be used in conjunction with a `visibilitySpec`, so you can continue to use your `timerSpec`, and just add `${firstVisibleTime}` to your request.

```
'requests': {
   'track': '......fvt=${firstVisibleTime}....'
},
'triggers': {
    'trackInterval': {
      'on': 'timer',
      'timerSpec': {
        'interval': 15,
        'maxTimerLength': 7200,
      },
      'request': 'track',
    },
  },
```
