### ISSUE TITLE
amp-experiment console error

### ISSUE THREAD

**Issue by nllorca** [ampproject/amphtml#28195]
Hi, i am trying to use amp-experiment and i get tu following console error in chrome

[OriginExperiments] Crypto is unavailable
[amp-experiment] Experiment amp-experiment-1.0 is not enabled

any idea?

thanks

**Comment by micajuine-ho** [comment]
Hi, amp-experiment-1.0 has not been fully released and is only available through experiments/origin trials.

To enable amp-experiment-1.0 as an experiment add this to your HTML:
```
      <script>
        (self.AMP=self.AMP||[]).push(function(AMP){
            AMP.toggleExperiment('amp-experiment-1.0', true);
        });
      </script> 
```

**Comment by nllorca** [comment]
micajuine-ho, thanks...but...if i put in html, amp validator fails..."Custom JavaScript is not allowed."

**Comment by micajuine-ho** [comment]
Hi @nllorca, as I said above, amp-experiment-1.0 is still under development, so it's not expected to be valid amp at this point. I recommend using amp-experiment-0.1 if that fits your use cases.
