### ISSUE TITLE
Make Stories more resilient to viewer communication initialization errors.

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#28227]
If a Viewer <> Story communication initialization fails, the Viewer can't switch the Story `visibilitystate` from `prerender` to `visible` after it is made visible, leaving users stuck on a completely unresponsive story.

We should improve this worst case scenario by making a trusted user gesture (tap/click) on a prerendered user story switch its `visibilitystate` to `visible` and proceed with the Story playback.

This change has been discussed with Google internal Privacy Working Group.

cc @ampproject/wg-stories

**Comment by cramforce** [comment]
Activating on interaction is a good idea.
