### ISSUE TITLE
amp-story-player keyboard navigation

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#28235]
## Describe the new feature or change to an existing feature you'd like to see

Right now pressing the left or right keys on a keyboard only advances the story if the story has been clicked and has focus. Also, when there are multiple stories added to the player, after finishing the first story, right and left keys advance not page by page but story by story.

## Describe alternatives you've considered

Ideally pressing the left or right key does the same as tapping on the left or right side of the story. i.e. advance or go back one page at a time, regardless of wether it's the first story in the player or if the user already went through a full story.

Additionally, if there was a method on the amp story player to give it focus, pages in which the story player is the main element could have keyboard navigation work straight ahead without having to click it first.

**Comment by gmajoulet** [comment]
cc @ampproject/wg-stories @Enriqe

**Comment by newmuis** [comment]
Can we implement our own `autofocus` attribute? (And also provide the programmatic hook?)

**Comment by gmajoulet** [comment]
+1 for a programmatic hook
cc @Enriqe who's finalizing the Player API

**Comment by Enriqe** [comment]
Sounds good, I'll add it to #28416

**Comment by gmajoulet** [comment]
Tracked in https://github.com/ampproject/amphtml/issues/28416

**Comment by Enriqe** [comment]
Reopening since this describes an issue with keyboard navigation, which is not tracked in #28416
