### ISSUE TITLE
triggerAnalyticsEvent doesn't wait for viewer.isVisible

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#28244]
Context: https://github.com/ampproject/amphtml/pull/28203#discussion_r421043233

We're trying to add `prerenderAllowed` to a new extension that calls `triggerAnalyticsEvent`. However, this helper doesn't seem to wait for `viewer.isVisible` at all, so this could accidentally send an analytics event before the user has opened the viewer.

/cc @ampproject/wg-analytics

**Comment by cramforce** [comment]
amp-analytics itself doesn't do anything until the doc is visible.

@zhouyx I'll leave it up to you, but I think it might be fine to just close this issue and possibly document those expectations.

**Comment by jridgewell** [comment]
Cool, I manually tested by patching on https://output.jsbin.com/zuvexej/quiet#visibilityState=prerender. It seems the event is still triggered, but Analytics won't actually fire anything else.

**Comment by zhouyx** [comment]
Analytics won't fire analytics requests before the doc is visible. 

However calling `triggerAnalyticsEvent()` does buffer events from pre render mode. Is that expected?  `triggerAnalyticsEvent()` is designed for components to trigger custom events like `video-play`. I can't think of a good example of calling `triggerAnalyticsEvent` during pre-rendering.

**Comment by cramforce** [comment]
I don't think we have cases where this would be expected to happen. Just a defense-in-depth that if it happens, then that should not be catastrophic.

**Comment by zhouyx** [comment]
I see. I'm seeing two layers of protections here
1. `triggerAnalyticsEvent()` is designed for custom user events (e.g. enter-lightbox ,video-play). Code review should help us detect any misuse. 
2. Analytics service will buffer the event and only send requests after the document is visible. 

These should be sufficient. Closing the issue.

**Comment by jridgewell** [comment]
> `triggerAnalyticsEvent()` is designed for custom user events (e.g. enter-lightbox ,video-play). Code review should help us detect any misuse.

This won't always be true, though. We're now using it an extension that prerenders, and the event is automatically triggered (the auto slide-change). We're just relying on Analytics to always guarantee that events won't trigger before visible.

**Comment by zhouyx** [comment]
>This won't always be true, though. We're now using it an extension that prerenders, and the event is automatically triggered (the auto slide-change)

Hmmm should we only enable the auto slide-change after the doc is visible, otherwise it sounds like a waste of resources to me. And the user may landed on the doc with the hero slide already scrolled away. 

We can always add another layer of protection to not buffer the event. But my feeling is that if we allow such event during prereder, it makes sense to also allow those events to be collected but sent after page is visible.

**Comment by jridgewell** [comment]
> Hmmm should we only enable the auto slide-change after the doc is visible, otherwise it sounds like a waste of resources to me. 

Yes, that's probably good. We never thought about this before, because the carousel never prerendered before.

> it makes sense to also allow those events to be collected but sent after page is visible.

I think that's good. Can you point to where the buffer is consumed after the viewer is visible? Like, what's the thing that waits for `whenFirstVisible`?

**Comment by cramforce** [comment]
FWIW carousel 0.1 was prerendering. It was just forgotten to port to later versions.

**Comment by zhouyx** [comment]
The `buffer` is consumed when `CustomEventTracker.add()` is called. 
https://github.com/ampproject/amphtml/blob/cb57fe236c0e904b2030efcf611332d4c83fcea3/extensions/amp-analytics/0.1/events.js#L337-L342
Call stack:
`CustomEventTracker.add()` <= `AnalyticsGroup.addTrigger()` <= `AmpAnalytics.registerTrigger()` <= `AmpAnalytics.ensureInitialized_()`.
https://github.com/ampproject/amphtml/blob/cb57fe236c0e904b2030efcf611332d4c83fcea3/extensions/amp-analytics/0.1/amp-analytics.js#L207-L214

**Comment by jridgewell** [comment]
Thanks! I think this is fine.
