### ISSUE TITLE
Page showing valid but error in webmaster console

### ISSUE THREAD

**Issue by techzotezo** [ampproject/amphtml#28255]
Some of my url is showing error in AMP console in google webmaster,but Pages are showing valid in when we AMP validation checking-
1) A mandatory AMP HTML tag is missing from this document.
https://www.zotezo.com/in/reviews/relief-bunion-shield-with-ring/?amp
https://www.zotezo.com/in/reviews/burberry-brit-for-her-eau-de-toilete-spray-100ml-3-3oz/?amp
2) Custom JavaScript is not allowed and A mandatory attribute is missing from an HTML tag.
https://www.zotezo.com/in/reviews/relief-bunion-shield-with-ring/?amp
https://www.zotezo.com/in/reviews/liponorm-5mg-tablet/?amp
https://www.zotezo.com/in/reviews/alfugress-10mg-tablet-er/?amp
https://www.zotezo.com/in/reviews/burberry-brit-for-her-eau-de-toilete-spray-100ml-3-3oz/?amp
3) The tag ‘img’ should be replaced with an equivalent ‘amp-img’ tag.
Same above url
4) The tag ‘i-amphtml-sizer’ is disallowed except in specific forms.
Same above url
5) The parent tag of tag ‘html’ must be ‘!doctype’.
Same above url
What is the issue? Both url is AMP validated in https://validator.amp.dev/ and https://search.google.com/test/amp Why suddenly issue happened?

Also amount of validated AMP url is gradually decreasing two days before it was 10k now it is reduced to 9571 pages.What is the reason?
Thanks

**Comment by honeybadgerdontcare** [comment]
@techzotezo hopefully you've been able to resolve your issues. The URLs above currently 404 even after redirect. If you're still having difficulties please reopen with more recent URLs or try contacting [Search Console Help](https://support.google.com/webmasters/?hl=en#topic=9128571).
