### ISSUE TITLE
Define rules for AMP embedding in Web Views

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#2826]
Require a connecting iframe or webview to specify either `viewer` or `viewerUrl`. Also make it logged in error.js. Currently both are done for `viewerUrl`. `viewer` should work the same and fallback to `viewerUrl` origin if not specified.

**Comment by rudygalfi** [comment]
Rolling this forward into next milestone.

**Comment by ericlindley-g** [comment]
Rolling into the next milestone

**Comment by chenshay** [comment]
duplicate of https://github.com/ampproject/amphtml/issues/6066
