### ISSUE TITLE
I2I: Limit the Full-Width Responsive Upgrade in Auto Ads to mobile users.

### ISSUE THREAD

**Issue by Jiaming-X** [ampproject/amphtml#28279]
## Summary
Currently, according to the Auto Ads[ logic in placement.js](https://github.com/ampproject/amphtml/blob/master/extensions/amp-auto-ads/0.1/placement.js#L202), the ads will be upgraded to full-width responsive if the responsive flag is enabled. 

This full-width expansion will likely to cover the nearby contents in desktop layout and will create broken user experience like this [one](https://screenshot.googleplex.com/N7n5CTvKDUa.png).

## Design
To avoid the broken user experience, the solution is to limit the full-width responsive upgrade to mobile users. As for the desktop users, they should fall back to the default Auto Ads flow.

See these internal references for the visual differences:
Before the changes:  https://screenshot.googleplex.com/N7n5CTvKDUa.png
After the changes(in local mode): https://screenshot.googleplex.com/2cCCj8WHPgW

/cc @ampproject/wg-approvers, @charliereams, @tlong2, @aishwaryavora

**Comment by Jiaming-X** [comment]
https://github.com/ampproject/amphtml/pull/28288

**Comment by aishwaryavora** [comment]
LGTM. Thanks!!

**Comment by Jiaming-X** [comment]
The issue was resolved. Closing the ticket now.
