### ISSUE TITLE
Nested AMP elements are never scheduled for layout in Carousel

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#2828]
@dvoytenko pointed out this issue regarding amp-elements used as `placeholder` inside other amp-elements. For example `amp-anim > amp-img.placeholder`. You can test it out by just launching the [carousel example](http://output.jsbin.com/qokanow/quiet) and notice that `amp-anim > amp-img.placeholder`  element is never actually gets laid out. 

![image](https://cloud.githubusercontent.com/assets/2647/14336311/5a8e84a6-fc17-11e5-926d-d51b9cda16a0.png)

Or for a better effect try to load the [carousel example in a `#visibilityState=hidden` state](http://output.jsbin.com/qokanow/quiet#visibilityState=hidden).

This is true to nested amp elements and not just placeholders that are not scheduled by the `discoverWork_` flow. (i.e. A parent element has scheduled its children for layout/preload).

`scheduleLayoutOrPreloadForSubresources_` needs to account for nested amp-elements resources and schedule these as well.

This is not limited to carousel, any amp element that will schedule layout or preload for its elements is prune to having this issue if it contains nested amp elements.

**Comment by jridgewell** [comment]
This is a bug with `Resources#discoverResourcesForElement_`, then.

**Comment by dvoytenko** [comment]
@mkhatib @jridgewell : yes, I agree. This looks to be a `discoverResourcesForElement_` issue. The fix would be simple.

Right now it's:
```
if (element.isAmp) {
  callback(element);
  return; // stop search
}
```

But it will be:
```
if (element.isAmp) {
  callback(element);
  if (!element.isLaidOut && element.hasPlaceholder()) {
    callback(element.getPlaceholder());
  }
  return; // stop search
}
```

Or some such.

**Comment by mkhatib** [comment]
Is the expectation that the nesting happens only for placeholder elements?

Are there any amp-elements that we expect people to nest (other than Carousel/Slider)? The snippet Dima wrote seems to only address the placeholder case not the nesting of non-placeholder elements.

This might not happen today but in future if we have some more elements that can be nested it might not be able to be scheduled inside a carousel. For example (amp-figure is a fictional amp element):

```
<amp-carousel>
    <amp-figure>  <-- this will be scheduled
        <amp-img placeholder></amp-img> <-- this will be scheduled
        <amp-img></amp-img>  <-- this will NOT be scheduled
        <amp-fit-text></amp-fit-text>  <-- this will NOT be scheduled
    </amp-figure>
</amp-carousel>
```

**Comment by dvoytenko** [comment]
Correct. This may happen. The answer to this is `Resource.hasOwner()` method. The `discoverResourcesForElement_` should never look inside resources with `hasOwner()` flag, with a sole exception of placeholders. These are two important properties of relationships between AMP elements:

1. Ownership: If an element, such as Carousel declares ownership over an element, it basically says "I'm competent to manage the state of this element myself and runtime should ignore it"
2. Placeholder is more like an automatic unshadowing of elements. You can almost imagine the `placeholder` elements to actually be outside of an AMP element, but with their visibility controlled by the state of this AMP element.

**Comment by rudygalfi** [comment]
Is there a PR for this? Moving into the next sprint...

**Comment by mkhatib** [comment]
> The discoverResourcesForElement_ should never look inside resources with hasOwner() flag, with a sole exception of placeholders.

@dvoytenko does this mean we leave the nested non-placeholder elements to be scheduled by the carousel (or the owner) of the element? So we expect the carousel to look into the element and see if there are more elements inside of it that it needs to schedule?

**Comment by ericlindley-g** [comment]
Rolling into the next milestone
