### ISSUE TITLE
TalkBack reads too much text on each Story page

### ISSUE THREAD

**Issue by ericfs** [ampproject/amphtml#28294]
## What's the issue?

Too much text is read for each story page. In addition to the reading the displayed text it reads "Updated, alert, Sound off..." on every page of the story.

![Screenshot_20200508-154153](https://user-images.githubusercontent.com/851850/81452929-3aec4880-9156-11ea-9f15-97572be921f6.png)

## How do we reproduce the issue?

1. Enable TalkBack
2. Open a story such as https://www.10best.com/web-stories/amp/what-are-jonnycakes-and-why-do-rhode-islanders-love-them/
3. Tap to read a text box
4. Double tap to advance to the next page

## What browsers are affected?

Android Chrome

## Which AMP version is affected?

2004252135000

**Comment by processprocess** [comment]
This was fixed by [28860](https://github.com/ampproject/amphtml/pull/28860).
