### ISSUE TITLE
amp-ad reference docs: data-foo-bar

### ISSUE THREAD

**Issue by jmadler** [ampproject/amphtml#2829]
A colleague of mine noticed that it's unclear how to add ''google_ad_host'' inside `<amp-ad type="adsense">`.  

It might make sense to look at ways to improve the amp-ad ref docs for specific ad networks to be more concise.

**Comment by cramforce** [comment]
Not clear to me what this means. Are you asking an adsense questions? AdSense docs can likely be improved, but I think it is a loosing game to do this on the AMP side. We typically ask ad networks to link to documentation on their own site.

**Comment by kbnaik** [comment]
Would like to echo here that at this point there are only two data attributes supported for AdSense Ad network: adClient and adSlot. (https://github.com/ampproject/amphtml/blob/master/ads/google/adsense.js)

google_ad_host is one of the (optional) key/value pairs for AdSense script:

<script type="text/javascript">
</script>

If this is added to the supported data-xxx dictionary, devs would be able to use it in the <amp-ad> tag for tracking purposes.

**Comment by jasti** [comment]
@bobcassels, you seem to know most about this. Could you PTAL? If not, please reassign?

**Comment by jasti** [comment]
Adding 'google_ad_host' is not supported in the adsense implementation of AMP :)
Closing for now but as @cramforce says - prob best to have this detail listed on the Adsense site. 
@konakk FYI
