### ISSUE TITLE
amp-bind: Validator doesn't error on AMP.setState without extension JS

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amphtml#28302]
## What's the issue?

Using amp-bind on a page without adding `<script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>` to the `<head>` element is still considered valid by the validator while it throws an error of `MISSING_REQUIRED_EXTENSION` for other extensions.

Currently, this only throws the error "AMP-BIND is not installed." and also only when the user interacts with the element.

This is problematic for people who rely on the validator results to confirm their pages are working in general.

## How do we reproduce the issue?

```html
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <title>My AMP Page</title>
  <link rel="canonical" href="self.html" />
  <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <!-- <script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script> -->
  <style amp-custom>
    .red {
      background-color: red;
    }
  </style>
</head>
<body [class]="red ? 'red' : ''">
  <button on="tap:AMP.setState({red: true})">
    Turn red
  </button>
</body>
</html>
```

## What browsers are affected?

All.

## Which AMP version is affected?

2004252135000

**Comment by choumx** [comment]
Thanks for the report. The validator doesn't parse `on` attributes (actions) so it doesn't know that an amp-bind action (`setState`) is being used without the extension. 

The same issue is also present for actions that rely on extensions other than `amp-bind`, though in those cases you'd see an error like `Target (...) doesn't support "foo" action.`.

**Comment by choumx** [comment]
More generally, there is a large class of correctness problems at runtime that the validator doesn't or can't enforce. Can give more context on the severity of this issue?

**Comment by matthiasrohmer** [comment]
Thanks for picking this up! I don't think that's an urgent error. I stumbled over this when working on amp.dev's playground. See https://github.com/ampproject/amp.dev/issues/3911#issuecomment-626625530 for context. 

For amp.dev we definitely find a way around for this use-case. Just wanted to bring this up as the behaviour might confuse new users 🙂

**Comment by Gregable** [comment]
@choumx What would be the condition that the validator should trigger on? Is it sufficient to throw an error if the document contains an `on` attribute, but not `amp-bind` js?

**Comment by Gregable** [comment]
I think what we want here is potentially warnings if either of the following are true:

1. an `on` attribute on the pages contains `"AMP.setState"` but `amp-bind.js` is missing.
2. `amp-bind.js` is present but no `on` attribute on the pages contains `"AMP.setState"`.

If anyone sees any mistake in that logic, let me know. Confirmation that this sounds right is also helpful!

**Comment by Gregable** [comment]
I think this is probably low enough priority FR that it will unlikely be tackled at this point. Closing due to low priority.
