### ISSUE TITLE
I2S: Turn on module/nomodule build in production

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#28310]
As described in https://github.com/ampproject/amphtml/blob/master/AMP_MODULE_BUILD.md
The module/nomodule pattern allows for us to ship a modern build of the AMP runtime. We intend to ship this gradually as this is a big change to how we ship code.

## Experiment(s) to enable
Module/nomodule

## Required release version
We have been deploying the module/nomodule build since late march 2020 to all versions

Status: OFF

**Comment by samouri** [comment]
@erwinmombay, closing this because I believe this was shipped already
