### ISSUE TITLE
Text is not rendering in amp story slides having amp fit text mainly for ios devices.

### ISSUE THREAD

**Issue by akashshah3991** [ampproject/amphtml#28327]
## What's the issue?
Text is not rendering in amp story slides having amp fit text mainly for ios devices. Text on first slides is visible as they do not have amp fit text. There may be another issue but seems to be amp fit text issues. It happens randomly. Sometimes it shows text and sometimes it's not.

## How do we reproduce the issue?

Live Urls:https://stories.whatahotel.com/top-5-resorts-in-san-diego
	  https://stories.whatahotel.com/top-10-hotels-chicago  and some more.
	  Homepage Url:https://stories.whatahotel.com/
	  The attached video will guide you through. Video is captured in the google search app on the iOS device. The attachment also contains Snapshot with the actual text. You will see the original story on the Andriod device or desktop. 

Html Code:
![code](https://user-images.githubusercontent.com/53644713/81645510-55207200-9447-11ea-96cd-2ab25ed5cf78.PNG)

## What browsers are affected?
Do not know exactly but mainly we getting this for ios devices (iPhone Xr) from safari and from google search app.

[Snapshots-and-video.zip](https://github.com/ampproject/amphtml/files/4613752/Snapshots-and-video.zip)
``

## Which AMP version is affected?
Live Version: 2004252135000

**Comment by gmajoulet** [comment]
cc @ampproject/wg-stories 

Might be the same as https://github.com/ampproject/amphtml/issues/28330

**Comment by akashshah3991** [comment]
@gmajoulet We also faced this  #28330 issue when we used flex-item layout for amp-fit-text. Sharing this that might help you generate test cases.

**Comment by cramforce** [comment]
I haven't been able to reproduce this.

**Comment by akashshah3991** [comment]
@cramforce We solved it using different layout for now  . So you won't get If you testing it on live urls stated in description.

**Comment by cramforce** [comment]
@akashshah3991 Ah, ok. Any chance you could provide a sample of the old markup? E.g. as a private glitch.com project?

**Comment by akashshah3991** [comment]
@cramforce 
Yes, I have hosted sample html having old markup on below URL.
https://my-first-project-95548.web.app/layout-fill.html

**Comment by cramforce** [comment]
Does this still reproduce for you? I've been trying your URL in Chrome and Safari at various screen resolutions.

**Comment by akashshah3991** [comment]
@cramforce Not for now. Maybe #28330 solved this issue too. Thanks.

**Comment by cramforce** [comment]
That fix wouldn't be available yet (unless you checked AMP at head from the repository).

I'll close this for now, but feel free to reopen if it reoccurs. Thanks!

**Comment by akashshah3991** [comment]
ok will see.
