### ISSUE TITLE
🚨 406 (Not Acceptable): [Failed to load resource]

### ISSUE THREAD

**Issue by jashraf82** [ampproject/amphtml#28334]
GET https://mydomain.com/amp/assets/js/custom.js 406 (Not Acceptable)
```

Details
---
I'm trying to add external javascript in Asp.NET amp project but always facing error "log.js:713 Uncaught (in promise) Error: HTTP error 406​​​"
```
Amp script Code:

"<"amp-script  layout="container" src="https://mydomain.com/amp/assets/js/custom.js" class="amp-script-sample">
        <button id="hello">Click!</button>
</amp-script">"
```

**CORS is enabled on IIS server as follow:**
```
<"add name="AMP-Same-Origin" value="true" />
      <add name="Access-Control-Allow-Origin" value="https://mydomain-com.cdn.ampproject.org" /">	        	  
	   <"add name="Access-Control-Allow-Headers" value="text/javascript" /">     
```
-->
**Error report:** `Falied to load resource: the server respond with error 406 (Not Acceptable)`
**First seen:** 
![image](https://user-images.githubusercontent.com/5330456/81795865-11e90080-9526-11ea-8fdb-7b8167c825d2.png)

-->

**Comment by choumx** [comment]
This looks like a configuration error on your server, not an AMP error.
