### ISSUE TITLE
amp-fit-text doesn't fit text properly in amp-stories

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#28330]
## What's the issue?

amp-fit-text has very inconsistent behavior when used in amp-stories. Here's a GIF:

![amp-fit-text](https://user-images.githubusercontent.com/4594196/81665591-2b644c80-9441-11ea-85bb-c58a0caa4467.gif)

As you can see, on some screen sizes amp-fit-text renders text at the smallest possible size.

## How do we reproduce the issue?

Open https://tappable.co/gifs/2020-05-10/, and resize the viewport. Text size will start to jump all over the place when resizing. Also try reloading the page, you'll see it's not due to the resizing itself.

## What browsers are affected?

All browsers as far as I know

## Which AMP version is affected?

This issue has been in place for over a year, just haven't used amp-fit-text anymore. @akashshah3991 recently filed #28327 which made me think of this. Both issues could be related.

**Comment by gmajoulet** [comment]
cc @ampproject/wg-stories
