### ISSUE TITLE
[amp-mustache] Why the link target is only blank?

### ISSUE THREAD

**Issue by juniorneo2** [ampproject/amphtml#2834]
I have a list and need that the link target be "_self". The script change the link target to "_blank". Why does it do this?

Code

<div style="background: #ffffff; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><table><tr><td><pre style="margin: 0; line-height: 125%"> 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15
16
17
18
19
20
21
22
23</pre></td><td><pre style="margin: 0; line-height: 125%"><span style="color: #007700">&lt;amp</span><span style="color: #0000CC">-list</span><span style="color: #007700">&gt;</span>
   <span style="color: #007700">&lt;template</span> <span style="color: #0000CC">type=</span><span style="background-color: #fff0f0">&quot;amp-mustache&quot;</span><span style="color: #007700">&gt;</span>
      {{#isFirst}}
      <span style="color: #007700">&lt;div</span> <span style="color: #0000CC">class=</span><span style="background-color: #fff0f0">&quot;teaser {{fieldCanaisCustom}}&quot;</span><span style="color: #007700">&gt;</span>
         <span style="color: #007700">&lt;div</span> <span style="color: #0000CC">class=</span><span style="background-color: #fff0f0">&quot;mod-teaser&quot;</span><span style="color: #007700">&gt;</span>
            {{#srcImage}}
            <span style="color: #007700">&lt;div</span> <span style="color: #0000CC">class=</span><span style="background-color: #fff0f0">&quot;teaser-image&quot;</span><span style="color: #007700">&gt;</span>
               <span style="color: #007700">&lt;a</span> <span style="color: #0000CC">href=</span><span style="background-color: #fff0f0">&quot;{{link}}&quot;</span> <span style="color: #0000CC">target=</span><span style="background-color: #fff0f0">&quot;_self&quot;</span><span style="color: #007700">&gt;</span>
                  <span style="color: #007700">&lt;amp</span><span style="color: #0000CC">-img</span> <span style="color: #0000CC">src=</span><span style="background-color: #fff0f0">&quot;{{srcImage}}&quot;</span> <span style="color: #0000CC">width=</span><span style="background-color: #fff0f0">&quot;120&quot;</span> <span style="color: #0000CC">height=</span><span style="background-color: #fff0f0">&quot;120&quot;</span><span style="color: #007700">/&gt;</span>
               <span style="color: #007700">&lt;/a&gt;</span>
            <span style="color: #007700">&lt;/div&gt;</span>
            {{/srcImage}}
            <span style="color: #007700">&lt;h3</span> <span style="color: #0000CC">class=</span><span style="background-color: #fff0f0">&quot;versal&quot;</span><span style="color: #007700">&gt;</span>{{versal}}<span style="color: #007700">&lt;/h3&gt;</span>
            <span style="color: #007700">&lt;h4</span> <span style="color: #0000CC">class=</span><span style="background-color: #fff0f0">&quot;title&quot;</span><span style="color: #007700">&gt;&lt;a</span> <span style="color: #0000CC">href=</span><span style="background-color: #fff0f0">&quot;{{link}}&quot;</span> <span style="color: #0000CC">target=</span><span style="background-color: #fff0f0">&quot;_self&quot;</span><span style="color: #007700">&gt;</span>{{title}}<span style="color: #007700">&lt;/a&gt;&lt;/h4&gt;</span>
            <span style="color: #007700">&lt;div</span> <span style="color: #0000CC">class=</span><span style="background-color: #fff0f0">&quot;clear-both&quot;</span><span style="color: #007700">&gt;&lt;/div&gt;</span>
         <span style="color: #007700">&lt;/div&gt;</span>
      <span style="color: #007700">&lt;/div&gt;</span>
      {{/isFirst}}
   <span style="color: #007700">&lt;/template&gt;</span>
   <span style="color: #007700">&lt;div</span> <span style="color: #0000CC">overflow</span> <span style="color: #0000CC">role=</span><span style="background-color: #fff0f0">button</span> <span style="color: #0000CC">aria-label=</span><span style="background-color: #fff0f0">&quot;Show more&quot;</span> <span style="color: #0000CC">class=</span><span style="background-color: #fff0f0">&quot;list-overflow&quot;</span><span style="color: #007700">&gt;</span>
      Show More
   <span style="color: #007700">&lt;/div&gt;</span>
<span style="color: #FF0000; background-color: #FFAAAA">&lt;</span>/amp-list&gt;
</pre></td></tr></table></div>

**Comment by jridgewell** [comment]
@dvoytenko, mind answering this?

**Comment by dvoytenko** [comment]
This is due to the #1572. Unfortunately the sanitizer drops the target completely for some bizarre reason. So, the `_blank` was the only option we had here. This is, however, reasonable when the page is shown in a viewer, e.g. iframe'd inside of Google.com - since CDN updates all `_self` links to `_blank` anyway because of sandbox policy would not allow self navigation. 

I pinged on the sanitizer's GitHub bug and hopefully they can address it quickly.

**Comment by juniorneo2** [comment]
Ok! Thank you! @dvoytenko @jridgewell

**Comment by dvoytenko** [comment]
If you don't mind, I'll dedup this bug into #1572.

**Comment by Wadekone** [comment]
Hey guys, any news on resolution for this issue? Hope you understand this is an awful UX as every new page user opens is a new browser tab (way too much consumption of mobile device's resource at least). We are currently in a process of implementing the solution that will allow the customers to navigate through AMPs using the AMP CDN and this bug is causing a trouble. 
Hope someone can update this thread soon. 

Best Regards,
Vadim

**Comment by dvoytenko** [comment]
@Wadekone, this bug is deduped to #1572. Could you please chime in there?
