### ISSUE TITLE
Sauce Labs runs frequently fail with disconnection errors / zero-test warnings

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#28343]
I've noticed a few Sauce Labs failures recently that are due to disconnection errors / zero-test warnings.

For example: https://travis-ci.org/github/ampproject/amphtml/jobs/686172826#L2358 (pasting screenshot below in case build gets restarted)

![image](https://user-images.githubusercontent.com/26553114/81726656-b94a3280-9455-11ea-9f45-7bca9898583c.png)

There is a plan add a heartbeat, but it hasn't worked as expected thus far. See #27484 and #27721.

Filing this tracking issue in case this becomes more frequent. If you see this happen, please add a comment with a link to the Travis build.

**Comment by rsimha** [comment]
Seeing more reports of this: https://travis-ci.org/github/ampproject/amphtml/jobs/686250218#L2535

```
[21:26:18] Safari 12.1.1 (Mac OS 10.13.6): STARTED
Safari 11.1.2 (Mac OS 10.13.6) ERROR
  Disconnected, because no message in 120000 ms.
[21:28:17] WARNING: Received a status with zero tests: {"startTime":1589318777091,"total":0,"success":0,"failed":0,"skipped":0,"totalTime":120001,"netTime":0,"error":false,"disconnected":true}
12 05 2020 21:28:17.092:ERROR [reporter.sauce]: ✖ Browser disconnected
Safari 12.1.1 (Mac OS 10.13.6) ERROR
  Disconnected, because no message in 120000 ms.
[21:28:18] WARNING: Received a status with zero tests: {"startTime":1589318778291,"total":0,"success":0,"failed":0,"skipped":0,"totalTime":120001,"netTime":0,"error":false,"disconnected":true}
12 05 2020 21:28:18.293:ERROR [reporter.sauce]: ✖ Browser disconnected
```

**Comment by rcebulko** [comment]
It's interesting this is resurfacing so suddenly. I haven't seen this error in a while, and our VM concurrency today has been very low, so it's not the concurrency limit issue. Will have to dig in

**Comment by rsimha** [comment]
> it's not the concurrency limit issue. Will have to dig in

Yeah, I doubt this is due to concurrency. I wonder if some tests are causing a browser crash / restart on the VM. Since you're our in-house expert on this, I've assigned this to you for investigation when time permits 😃

**Comment by rsimha** [comment]
I took a look at the Sauce Labs logs. The Karma server is getting disconnected while running tests even though the browser is still up and running. This is happening early in test runs (~2-5 mins in), so it isn't due to the idle timeout, which is 10 mins.

Will escalate this to Sauce Labs support.

**Example below:**

**Travis logs:** https://travis-ci.org/github/ampproject/amphtml/jobs/686410570

![image](https://user-images.githubusercontent.com/26553114/81831358-3f748080-950b-11ea-8930-84d3fd790da4.png)

**Sauce logs:** https://app.saucelabs.com/tests/b9a77e165c5543ee90ffbccea517a5dc#1

<img width="965" alt="Screen Shot 2020-05-13 at 11 19 30 AM" src="https://user-images.githubusercontent.com/26553114/81831970-f5d86580-950b-11ea-88c6-7ad2c8047ffa.png">

**Comment by wswebcreation** [comment]
@rsimha 

Can you try to run on Sauce Labs again and use Chrome and try to provide the capability `extendedDebugging: true`. That might show some network traffic on the browser

Secondly try to log the Sauce Connect logs to a file so we can see what it happening there?

**Comment by rsimha** [comment]
@wswebcreation Thanks for the tips. Both steps are done in the debugging PR #28384. Results should be available in a few minutes in [this](https://travis-ci.org/github/ampproject/amphtml/builds/686646104) Travis build. (See [job 9](https://travis-ci.org/github/ampproject/amphtml/jobs/686646114) for Sauce labs logging.)

**Comment by rsimha** [comment]
From #28384, here is a full set of logs:

**Travis logs:** https://travis-ci.org/github/ampproject/amphtml/jobs/687581857#L2448

**Tunnel info:**

Tunnel ID: `689d7336f79d4deca411382a075bd88a`, Identifier: `75029.10`

![image](https://user-images.githubusercontent.com/26553114/82097652-506eee80-96d1-11ea-8968-f0b40f1cb920.png)

**Disconnections:**

![image](https://user-images.githubusercontent.com/26553114/82096791-9e82f280-96cf-11ea-98bd-460483713b51.png)

**Sauce connect log:**

[sauce_connect_log_75029.10.zip](https://github.com/ampproject/amphtml/files/4637195/sauce_connect_log_75029.10.zip)

**Comment by wswebcreation** [comment]
@rsimha 

I'm trying to debug this one, but it's pretty hard with the logs from Sauce Connect and not having the instances in Sauce Labs that failed, can you provide them also?

**Comment by christian-bromann** [comment]
I am investigating the issue together with the Sauce Connect team here at Sauce. It seems that there is too much traffic going through the tunnel causing package loss.
