### ISSUE TITLE
White flash when switching Story from non visible visibilitystate to visible

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#28341]
When switching a Story from a non visible visibilitystate (ie: `prerender` or `paused` or `hidden`) to `visible`, the Story can have a white flash.

Not sure if this happens only when there's a video on the first page or not.

More info: b/156128288

cc @ampproject/wg-stories

**Comment by gmajoulet** [comment]
Repro URL: https://www.vice.com/stories/amp/worst-summer-jobs/

**Comment by cramforce** [comment]
@gmajoulet Were you able to repro this with something like http://localhost:8000/proxy/s/www.vice.com/stories/amp/worst-summer-jobs/#visibilityState=prerender

Definitely doesn't happen now. Tested on both desktop and mobile. I think this might be a dupe of #28649

**Comment by gmajoulet** [comment]
I can still see a jump when the video goes from poster to first frame, but I'm not sure that's what the bug was originally about.

**Comment by cramforce** [comment]
@gmajoulet What kind of jump are you seeing? The poster frame isn't identical to the first frame of the video. I think there is little we can do about that.

**Comment by gmajoulet** [comment]
I could see the background color flashing when the video was transitioning from poster to first frame, but I can't repro today. I'll re-open if I ever see this issue again.
We do have #28586 to improve how close the poster / first frame look like on Android though.
