### ISSUE TITLE
Don't trigger amp-next-page for large viewports on initial load

### ISSUE THREAD

**Issue by mhart** [ampproject/amphtml#28353]
## Describe the new feature or change to an existing feature you'd like to see

Hard to know whether this is a bug/feature-request that belongs in this project, or whether it's something that Googlebot should fix, but basically the way amp-next-page fetches multiple pages on initial load is apparently considered a no-no according to John Mueller:

https://twitter.com/JohnMu/status/1260120253469806593

> I'd recommend not using infinite scrolling in this way when it comes to search. If these are separate, independent items, then expanding the viewport of a page shouldn't trigger them loading together. Mixing things on a single URL makes it possible that they're indexed together.

## Describe alternatives you've considered

* Only trigger page fetching if the user interacts with the page. Not sure if this is a hack, or the "correct" solution
* Don't use amp-next-page

**Comment by cramforce** [comment]
I think the best implementation here is likely to not trigger loading more pages if not scroll event has ever been observed.

**Comment by mhart** [comment]
Agreed, I think the only question is whether there are use cases that ppl *want* this behavior – eg, a related list of items that you're just paginating through. Because they're related, it might make sense to load as many as can fit in the viewport as once.

So basically, should there be an option for it

**Comment by nainar** [comment]
@wassgha agree with @cramforce's comment. 

Also better from a performance standpoint. 

@mhart in the counter example you point to `a related list of items that you're just paginating through` - that would be dealt with the case that a scroll has occurred correct?

**Comment by mhart** [comment]
@nainar no it wouldn't. I actually mean a list of related things that would likely appear together (eg, here are 100 things that xyz). In that case you'd want as many to load as would fill the viewport without a scroll event occurring.
