### ISSUE TITLE
Uncaught ReferenceError: module$build_system$global_configs$caches_json is not defined

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#28355]
`amp-story-player` is throwing the following error:

```
Uncaught ReferenceError: module$build_system$global_configs$caches_json is not defined

```

Causing the player to stop loading.

This is because in #27658 we import the `caches.json` found in `build-system/`, but it looks like it's not bundled in production.

/cc @ampproject/wg-stories

**Comment by Enriqe** [comment]
Importing @jridgewell's comment here for visibility https://github.com/ampproject/amphtml/pull/27658/files#r424018799

"Importing from build-system isn't supported, because isn't not included as one of our files when we pass them to closure."

@ampproject/wg-infra can we add a pre-submit check to prevent importing from `build-system/`? Is that something that could've prevented this?

**Comment by rcebulko** [comment]
My inclination is that this should be a compilation/build-time failure rather than a presubmit check. Ideally it would fail as soon as a developer tried to build locally

**Comment by Enriqe** [comment]
Discussed with @jridgewell offline, he came up with a [fix](https://github.com/ampproject/amphtml/pull/28356/commits/6b2688ee6f983a22ac6d9d9915b72d3e7ef4940f) to the existing regex that checks for unknown dependencies. He thinks Closure possibly changed the import identifier format.
