### ISSUE TITLE
Parse only once per received message, not once per listener

### ISSUE THREAD

**Issue by NataliaLKB** [ampproject/amphtml#2836]
## Parse only once per received message, not once per listener

If PR #2835 is merged, resize postmessages received by amp-iframe will parse for each listener. However, they should be parsed per message received.

**Comment by ericlindley-g** [comment]
@jridgewell , is this work that you'll be doing off of PR #2835? I've slotted it in the backlog, but is it urgent?

**Comment by jridgewell** [comment]
I [started](https://github.com/ampproject/amphtml/pull/2925) this because it was the top of the backlog and I had free time. 😃
