### ISSUE TITLE
I2I: Allow sticky ads in amp-ad component

### ISSUE THREAD

**Issue by powerivq** [ampproject/amphtml#28386]
## Summary

This PR proposes to merge the feature available on amp-sticky-ad into amp-ad.

## Design document

```html
<amp-ad type=networkname format=sticky data-site=xxxx data-slot=xxxx data-options=xxxx></amp-ad>
--

Arguments:
format: A string. The only possible value is sticky, if it is set.
render-on-load: A boolean. Default to false. If true, the ad will be loaded when the page is loaded. This will lead to higher view but lower performance.
```

### Dynamic size
In the traditional amp-ad tag, the size of the ad slot must be statically defined at the page creation time. This constraint ensures layout stability within the page. However, since this type of ads is fixed on the viewport, allowing dynamic size should not cause layout shifts on the page, so we should have it allowed.

### Size limit
Although we could allow the size (width and height) of the creative to be decided dynamically (set within the specific creative), we still plan on having a reasonable limitation on how large an ad could be. If the requested creative size (measured by area) divided by the viewport size is over a given threshold, it will be rejected.

### X button
We propose the component will own the X button that would collapse the ad.

## Motivation
`amp-sticky-ad` has a fixed size and limitations of the ad format (a fixed size sticky to bottom). We want to allow the advertising network to have more freedom on the type of creative they may serve, and this will lead to a higher revenue potential for a specific ad slot.

The additional benefit is that the publisher does not have to create two tags (one amp-sticky-ad and one amp-ad) just to make a sticky ad slot. The duplicative tag does not create a very meaningful benefit to us.

## Launch tracker

/cc @ampproject/wg-approvers @ampproject/wg-ads-reviewers

**Comment by cramforce** [comment]
Is allowing `amp-ad` to upgrade itself from non-sticky to sticky in scope here as well? Or is that not desired?

**Comment by powerivq** [comment]
@cramforce Not in scope for this. However, since upgrading ads to match an environment is done in some cases (DoubleClick), we can defer this question to the specific ad network.

**Comment by zhouyx** [comment]
So if I understand it correctly, the proposal is only to change the tagging.
By changing `<amp-sticky-ad>` to `<amp-ad format=sticky>`. 
Publishers are still required to decide and tag which ad will be displayed as sticky ad.
