### ISSUE TITLE
Add an attribute to amp-story for publishers to know if the story audio is muted.

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#28395]
Add an attribute to amp-story for publishers to know if the story audio is muted.

Audio playing:
`<amp-story ...>`

Audio muted (default):
`<amp-story muted>`

Publishers can then write CSS targeting muted or unmuted states:
`amp-story:not([muted]) {}`
`amp-story[muted] {}`

cc @ampproject/wg-stories

**Comment by newmuis** [comment]
😂 this was the initial implementation way back in the day. Glad to see it come full circle
