### ISSUE TITLE
Create new Story viewer capability to support "Swipe down to close" gestures.

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#28397]
Create new Story viewer capability to support "Swipe down to close" gestures, for singleton documents that don't have the `cap=swipe`.

cc @ampproject/wg-stories

**Comment by Enriqe** [comment]
This was done in #27055. Does this not resolve the requirements?

**Comment by gmajoulet** [comment]
No, the story runtime would still block the events. What is #27055 used for? I believe it's a no-op on a Story.

**Comment by Enriqe** [comment]
It's used for the "swipe down to close" feature in Google's SERP, for singleton documents. It allows the viewer to receive touch events, without enabling all the `cap="swipe"` functionality in the story runtime.

**Comment by gmajoulet** [comment]
How did you test it? I'm 99% sure that it does not work, we even have unit tests to ensure that events don't bubble up beyond the amp-story:

https://github.com/ampproject/amphtml/blob/7a69be3f4cfdcb3fd1d1895de609d3afb8f0d404/extensions/amp-story/1.0/test/test-amp-story.js#L1572-L1578

**Comment by Enriqe** [comment]
It sends the event as a message, it doesn't actually block the event from bubbling up the DOM. 

See
https://github.com/ampproject/amphtml/blob/7a69be3f4cfdcb3fd1d1895de609d3afb8f0d404/extensions/amp-viewer-integration/0.1/touch-handler.js#L140-L143

**Comment by gmajoulet** [comment]
What I meant in my previous message is that the story swallows the touch events and won't let them get to the `touch-handler.js` listeners, cf the unit test.
How did you test it? Maybe our implementation and unit tests are broken, but it'd be good to know if so.

**Comment by gmajoulet** [comment]
We should verify Enrique's PR, and either rename it, or roll it back to create a new `swipeToClose` capability for singleton documents, that doesn't disable the bookend or the navigation UI hint, but forwards "swipe down" touch events to the viewer.

**Comment by Enriqe** [comment]
I can tackle this if you want, I was just taking to Greg about it
