### ISSUE TITLE
[amp-story] amp-audio isn't playing audio

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#28404]
Getting this error
```
log.js:425 Uncaught (in promise) Error: Cannot play unregistered element.
    at Log.assert (log.js:425)
    at devAssert (log.js:910)
    at MediaPool.loadInternal_ (media-pool.js:682)
    at MediaPool.play (media-pool.js:799)
    at amp-story-page.js:937
    at async Promise.all (index 0)

```
and audio is not playing

/cc @ampproject/wg-stories

**Comment by Enriqe** [comment]
I'm thinking this might be the cause:

https://github.com/ampproject/amphtml/blob/7dc79a0a5cf144ee9c165d3cc2298b32602b43be/extensions/amp-story/1.0/amp-story-page.js#L1109-L1116

We recently made a change to wait for the `amp-audio` element to be laid out before registering it to the media pool, but since `amp-audio` elements use `layout="nodisplay"` in stories, they aren't laid out, and thus the element is never registered in the media pool.

**Comment by Enriqe** [comment]
For `amp-audio` we really only have to wait for it to be built, not laid out. We can do something like 
```
if (parentEl.tagName === 'AMP-AUDIO') {
  promise = parentEl.signals().whenSignal(CommonSignals.BUILT);
```

**Comment by gmajoulet** [comment]
From the `amp-audio.js` file, it looks like the `layoutCallback` not running with `layout=nodisplay` is expected.

Let's fix our Story code to work with it:
if 'AMP-AUDIO' && layout is not Layout.NO_DISPLAY -> wait for LOAD_END
if 'AMP-AUDIO && layout is Layout.NO_DISPLAY -> wait for BUILT

**Comment by Enriqe** [comment]
We only validate ` Layout.NO_DISPLAY` in stories though, so I think we should only wait for it to be built.
