### ISSUE TITLE
Talkback: story education reads special characters

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#28410]
When the story education is visible, talkback reads the special characters (or SVG?).

To display the education layer, append `#cap=education` to your Story URL, and add `this.setState_(State.NAVIGATION_TAP)` as the very last line of `amp-story-education.buildCallback()`.

cc @ampproject/wg-stories 
b/156132895

**Comment by gmajoulet** [comment]
Additionally, talkback should not read what's behind the education layer.

**Comment by newmuis** [comment]
Is there some way we can not special case the education layer, but rather any time there's a modal or drawer overlaid?

**Comment by processprocess** [comment]
It doesn't look like there are any special characters when the `NAVIGATION_TAP` or `NAVIGATION_SWIPE` states are active.
That might have been a part TalkBack reading content behind the modal in b/156132895.

I'm not sure if we can prevent TalkBack from reading special characters but we can prevent the screen reader from reading specific elements.

I wonder if we want to make a separate bug for hiding content when a modal or drawer is active.

**Comment by processprocess** [comment]
in b/156132895 TalkBack is working as intended.
TalkBack is reading the image `src` since an `alt` tag isn't provided.

I feel like this is up to the publisher to follow best practices.

Do we encourage publishers to provide an alt tag on images and videos?
Should that be part of the validator?

**Comment by newmuis** [comment]
Unfortunately, the validator is pretty weak here. It can only entire the presence of the attributes, not their values (not effectively anyway).  So we'd end up with a lot of `alt="image"` (or even just `alt="."`) which is not better in any way

**Comment by processprocess** [comment]
In that case it's on the publishers to name the image file descriptively or write an alt tag.

Since TalkBack is working as intended, what can we do as developers if the publishers are not following best practices?

**Comment by gmajoulet** [comment]
Did the change to remove the `aria-live=polite` prevented Talkback from reading the `src` attribute?
Follow up question if the answer is "no", do we consider not reading the `src` better than reading it? If yes, what happens if we specify an empty alt `alt=""`?

**Comment by processprocess** [comment]
Removing the `aria-live=polite` did not prevented Talkback from reading the `src` attribute. So, no.

I think adding `alt=""` if no `alt` value is specified is a good option as long as we are okay with assuming that all images without an `alt` tag are [decorative images](https://www.w3.org/WAI/tutorials/images/decorative/) (images that don't add meaningful content).

What do you think?
