### ISSUE TITLE
Add mszylkowski to @ampproject/reviewers-amphtml

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#28424]
@mszylkowski from @ampproject/wg-stories has 11 merged PRs and 4 open ones, including some complex/high quality ones (https://github.com/ampproject/amphtml/pull/28412, https://github.com/ampproject/amphtml/pull/28209, https://github.com/ampproject/amphtml/pull/28054) and should be added to @ampproject/reviewers-amphtml 

cf: https://github.com/ampproject/amphtml/pulls/mszylkowski

**Comment by mrjoro** [comment]
Done!
