### ISSUE TITLE
I2I: Make SafeFrame API available for all amp-ad network

### ISSUE THREAD

**Issue by powerivq** [ampproject/amphtml#28428]
## Summary
Currently, only Adsense and DoubleClick fast fetch extension supports SafeFrame API. This issue proposes to implement SafeFrame APIs for all 3p ads.

## Design document
We propose to implement the following SafeFrame APIs, as delineated in the [API doc](https://www.iab.com/wp-content/uploads/2014/08/SafeFrames_v1.1_final.pdf).

Whether we run the safeframe container or not will be controlled by the ad vendor configuration. The vendor can choose whether SafeFrame APIs should be allowed on a per-request basis.

The APIs intended to be implemented include:
- $sf.ext.register()
- $sf.ext.supports()
- $sf.ext.status()
- $sf.ext.meta()
- $sf.ext.inViewPercentage()
- $sf.ext.resize()
- $sf.ext.expand()
- $sf.ext.geom()
- $sf.ext.collapse()

## Motivation
Since most 3p ads are rendered within a cross-domain iframe, they have limited access to the AMP page. This constrains the ad in a given fixed size container, and prevents the ad from making certain interactions.

To allow more interactive-type ads (mostly reservation ads) be successfully displayed on AMP pages, we need to have a common interface between the creative (in a 3p iframe) and the content page. [SafeFrame API interface](https://www.iab.com/wp-content/uploads/2014/08/SafeFrames_v1.1_final.pdf) is in a good position to solve this problem. It has defined a set of sensible interfaces that most ads uses to expand, collapse, resize, etc. It is also flexible enough that we can further extend. SafeFrame is being used by advertisers.

Currently, both the DoubleClick and Adsense fast fetch extension support rendering a creative in a SafeFrame. If AMP implements SafeFrame API for all the ads extensions, it could benefit immediately those who already wrote the ads in SafeFrame.  

## Additional context
This proposal is relevant: https://github.com/ampproject/amphtml/issues/28386 in that they both seek to expand ad format support on AMP.

## Launch tracker

/cc @ampproject/wg-approvers @ampproject/wg-ads

**Comment by zhouyx** [comment]
Combined with #28386, will there be a `requestFixed` API that and ad can request to upgrade to a sticky-ad? (And potentially flying carpet ad in the future)
Is that in scope of this I2I?

**Comment by powerivq** [comment]
@zhouyx Not in this safeframe proposal today, but it is feasible. Are there a big demand for that?

**Comment by zhouyx** [comment]
I've definitely received that request a few times. 

Publishers works with ad networks and rely on ad networks to tell which ad should be rendered as sticky ad. It would make a nice addition to #28386.
