### ISSUE TITLE
🌸 Cherry-pick request for #28423 into #28223 #28389 (Pending)

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#28433]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #28431 | #28423 |     **YES**     | **YES** | **NO** | #28223 #28389                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

This makes animated links in stories unclickable.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

#28080 was a workaround for an error reported from animations pausing in certain cases. This workaround caused animations to restart on pause if they were already finished, which means that animated clickable elements that are hidden initially could not be clicked.

## Impact

- All stories with links in animated layers under some presets.

## Action Items

- #<_ISSUE_NUMBER_>: <_Add unit/integration/end-to-end test_>
- #<_ISSUE_NUMBER_>: <_Add monitoring for edge case via error logging_>
- #<_ISSUE_NUMBER_>: <_Refactor an easily misused API_>

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by gmajoulet** [comment]
+1

**Comment by cramforce** [comment]
Approved

**Comment by gmajoulet** [comment]
Could not cherry-pick today, cf https://github.com/ampproject/amphtml/pull/28423#issuecomment-628984547

**Comment by gmajoulet** [comment]
Done, cf #28223 and #28389 for release times.
