### ISSUE TITLE
gulp dist --fortesting --single_pass failing for ?? operator within preact component (bento)

### ISSUE THREAD

**Issue by krdwan** [ampproject/amphtml#28432]
I am running into an issue with: `gulp dist --fortesting --single_pass`
It appears to be erroring out based on the null coalescing operator in my code (`??`).
The null coalescing operator is within a preact component, which may be contributing to this error.

Link to PR: (I have sinced removed the null coalescing operator and replaced with `||`).
https://github.com/ampproject/amphtml/pull/28137

Travis Job Link:
https://travis-ci.org/github/ampproject/amphtml/jobs/687140839

Screen shot:
![image](https://user-images.githubusercontent.com/25626770/81980317-5fd03800-95fc-11ea-8cfc-0d829b9e6aa6.png)

**Comment by erwinmombay** [comment]
single pass project is obsolete closing.
