### ISSUE TITLE
I2I: Inline analytics vendor config on Google AMP Cache

### ISSUE THREAD

**Issue by kevinkimball** [ampproject/amphtml#28437]
## Summary
AMP loads predefined analytics vendor config and merges it with the inline config one client side. The proposal is to handle the above operations on the server. That will help reduce analytics requests delay by saving one round trip to get the static json object. Merging configs on the server will also save end users some CPU resources. 

## Design document
WIP

## Motivation
This is a performance optimization that was identified as part of a larger effort to improve AMP performance. Specifically the deep merge was identified as a cause of FID on the client. 

## Additional context
n/a 

## Launch tracker
WIP

/cc @zhouyx

**Comment by zhouyx** [comment]
Thank you @kevinkimball. Super excited about this feature. 

Current order of precedence for configs is
Remote config > Inline config > Vendor config > Default config. 

With this optimization we can merge default and vendor config to inline config. And only need to handle remote config on the client side!

**Comment by kevinkimball** [comment]
I wrote up a TDD on this and determined that there would be a significant amount of complexity relative to the performance improvement. For that reason I decided with Kris to focus on other higher-impact work and I don't plan to implement in the near future.
