### ISSUE TITLE
FR: ability to use "container" layout for amp-social-share

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#2843]
from @hkmaly in #2756:

> Would it be possible to actually USE the width and height specified as opposed to hardcoding width 60px and height 44px as is now? I suppose I can override them, but then the images on buttons are too big.

@hkmaly, I believe what you're asking for would be something like using ["container" layout](https://github.com/ampproject/amphtml/blob/bbbb7e6dccd8159fe9f139b7c65715a4a3526754/spec/amp-html-layout.md#container). @mkhatib is doing some work on amp-social-share that should solve this issue, but I'm opening up this feature request so we don't lose track of it.

@mkhatib, I've slotted this in for the 4/28 milestone, but let me know if that's not the right place for it, or if it's premature to schedule at this point

**Comment by hkmaly** [comment]
I don't think it will help. I'm speaking about the ability to use
<amp-social-share type=>"twitter" width=30 height=22>
instead of my current workaround of using
<span><amp-social-share type=>"twitter" width=60 height=44></span>
with styles like
  span {
    position: relative;
    height: 22px;
    width: 30px;
    margin-left: 5px;
    display: inline-block;
  }
  amp-social-share {
    transform: scale(0.5,0.5);
    transform-origin: 0 0;
    position: absolute;
  }

**Comment by ericlindley-g** [comment]
@hkmaly — ah, now I see: you want to use the size specified with the height and width attributes for amp-social-share, not the dimensions of the images themselves

@mkhatib — shouldn't this already work? I'm assuming this will already be addressed with the other changes you'll be making before this component is pushed out of experimental again, but we should make sure that if there's a bug here it doesn't persist in the revised implementation

**Comment by mkhatib** [comment]
@ericlindley-g this should already work if I understand what @hkmaly is trying to do.

My understanding is that he is trying to make the amp-social-share button smaller, right?

The snippet you sent should work correctly, I've created a [demo page with both of your snippets](https://jsbin.com/jusare/edit?html,output) and both of them render in the correct size. Am I missing anything?

**Comment by mkhatib** [comment]
If that didn't render you might need to manually toggle experiments by typing `AMP.toggleExperiment('amp-social-share')` inside the jsbin console and reloading.

**Comment by hkmaly** [comment]
Note that I didn't reacted after "shouldn't this already work" because I'm not familiar with your design flow and speed ; it was 8 days ago (Apr 4th) when I made the original comment and I'm not sure what version of amp-social-share it was - it was before I realized it is in experimental status. When CDN rejected the page because of it, I disabled it and didn't retried.

**Comment by ericlindley-g** [comment]
@hkmaly Thanks for following up—it sounds like the particular problem you were having is fixed. No further action is needed, and you can keep an eye on our releases to see when amp-social-share is available in production.

For tracking, we can keep the request identified in the title of this issue (for amp-social-share to support "container" layout) open until it is addressed by the work that @mkhatib is doing.

**Comment by mkhatib** [comment]
Using all layouts will be possible in the next release of amp-social-share next week.
