### ISSUE TITLE
can we restart the same instance of amp-date-countdown multiple times?

### ISSUE THREAD

**Issue by cw-RayeesKausar** [ampproject/amphtml#28442]
I went through the amp page documents. and i wanted to restart the amp-date-countdown on click of a button, but i was not able to restart it. I added the hidden attribute on amp-date-countdown depending on a variable but after first rendering timer was not working again, I mean i was not able to restart it.

**Comment by krdwan** [comment]
Thanks @cw-RayeesKausar.  We will prioritize this feature request against other priorities and provide and update at a later time.  Thanks!

**Comment by krdwan** [comment]
@cw-RayeesKausar For reference, amp-date-countdown does not currently support restart multiple times.  It is a countdown to a set time in the future.  Are you able to share any additional background on what your use case is?  Maybe there is another component that may fit your use case.

**Comment by krdwan** [comment]
Hi @cw-RayeesKausar !  I am closing out this bug as this is not the intended behavior of amp-date-countdown!  If you would like to request this functionality as a new feature or potentially new amp component, please file a feature using the link below (select 'Feature request' for the type of issue).  Thanks!

https://github.com/ampproject/amphtml/issues/new/choose
