### ISSUE TITLE
Amp disable link and buttons

### ISSUE THREAD

**Issue by Aivaras100** [ampproject/amphtml#28459]
I have problem with Iphone phone, IOS 13.4.1. Safari browser.

I get problem when:
1. Open amp product category;
2. Click on product (no amp url);
3. Go back to amp category.
4. Then I not can click on product. Disable all url and buttons.

Why does this happen?

**Comment by Ichigo3d** [comment]
Hello. Thank you for your participation. Could you provide url of website, where appeared this issue?

**Comment by Aivaras100** [comment]
I my site amp disabled, to solve this problem. But ex: https://www.google.com/search?client=firefox-b-d&q=alybaba+pencil is the same problem with Iphone phone, IOS 13.4.1. Safari browser.

**Comment by choumx** [comment]
We need more information. Please provide a reproduction URL and screenshots.
