### ISSUE TITLE
RFC: Factor amp-ad into extension

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2845]
`amp-ad` is the only core component that is not simple and in core. Removing it should bring down the default JS size by quite a bit.

We could replace it with an extension and a stub in core that loads it dynamically, so that all existing content keeps working.

Then we could tell people to explicitly load the extension to get the previous speed back, but overall it should not be such a bad perf regression.

**Comment by ericlindley-g** [comment]
@cramforce — I'm slotting this in the backlog, but let me know if you have a concrete target in mind

**Comment by cramforce** [comment]
@ericlindley-g Lets be aggressive about it.

**Comment by ericlindley-g** [comment]
@cramforce Done :)

(feel free to re-slot if 4/28 isn't the right level of aggressive—it's hard for me to gauge without a good sense of the scope of the task)

**Comment by erwinmombay** [comment]
will need to remember to move amp-embed too

**Comment by ericlindley-g** [comment]
Rolling into the next milestone
