### ISSUE TITLE
amp-mustache sanitation

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#28464]
The output of `amp-mustache` "triple-braces" is sanitized to allow, for example,  the following tags: `a`, `div`, `li`, `ol`, `p`, `span`, `table`, `tbody`, `td`, `th`, `thead`, `tfoot`, `tr`, `ul`

In short, paragraphs, tables and lists can be embedded and reused in `{{{triple-braces}}}`

Please add support for `dl`, `dt` and `dd` as these elements often are used to provide more detail than is possible with native lists (i.e. without using nested lists)

**Comment by krdwan** [comment]
Thanks @jaygray0919 for the request.  We will prioritize against other priorities and provide an update at a later time.

**Comment by jaygray0919** [comment]
Beautiful - thank you. Gives us extra flexibility with triple braced content.
