### ISSUE TITLE
Scrollbar not allowed on amp-access login link

### ISSUE THREAD

**Issue by hkmaly** [ampproject/amphtml#2848]
I understand that it's supposed to work on smartphones and generally be small, but would it be possible to allow scrollbars on the login window? Currently, it's opened with window.open without scrollbars being mentioned, which unfortunately means they are turned off on some browsers. When the page content is bigger than the window, it's not possible to see it then.

## How do we reproduce the issue?

https://www.einpresswire.com/amp/article/319717314/foam-for-wound-dressing-industry-by-companies-country-and-type-2016-to-2021-global-and-chinese-market-research-report

https://cdn.ampproject.org/c/s/www.einpresswire.com/amp/article/319962384/london-app-company-launches-a-new-scheme-making-social-apps-accessible-for-start-ups

1. Open login url
2. ... with browser who actually honors turning off the scrollbar
3. ... and notice that it can't be scrolled even if more content is there.

## What browsers are affected?

Palemoon and Firefox at least.
It seems working on chrominum and android chrome.

## Which AMP version is affected?

Is this a new issue? Or was it always broken? Paste your AMP version. You can find it in the browser dev tools.

You mean the "Powered by AMP ⚡ HTML – Version 1459447315826" line? I never saw it work, but I'm only working on AMP for few weeks.

**Comment by dvoytenko** [comment]
@hkmaly Absolutely. Will implement ASAP.

**Comment by dvoytenko** [comment]
@hkmaly while I'm fixing this... Could you actually clarify which browsers actually default `scrollbars` to `no`? I did a quick run and all browsers I tried force it to `yes` by default.

**Comment by hkmaly** [comment]
"Default" is hard to pinpoint here. Firefox (and Palemoon) have a setting - dom.disable_window_open_feature.scrollbars - which have two values: false - honor the standard and true - force scrollbars to yes. See https://developer.mozilla.org/en-US/docs/Web/API/Window/open

Firefox won't change the settings by itself on upgrade, but I suspect new installs set it to true. Or you may have it set that way manually. That's not something I would want to rely on.

**Comment by hkmaly** [comment]
(Although I suppose people like me who didn't reset their profile since Firefox version 3 are rare, I have no idea when this might've changed.)

**Comment by dvoytenko** [comment]
@hkmaly I see. In either case a good idea to fix. I sent https://github.com/ampproject/amphtml/pull/2855
