### ISSUE TITLE
Java Validator tests cause Ubuntu keyserver error, breaking builds

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#28497]
The Ubuntu keyserver is down, which is killing all the builds when they try to fetch a key to run the Java Validator checks.

![image](https://user-images.githubusercontent.com/6694512/82360603-9f6d9a00-99d7-11ea-93da-29f2a6acf6b6.png)

![image](https://user-images.githubusercontent.com/6694512/82360587-9b417c80-99d7-11ea-87ea-75846ee85378.png)

/cc @ampproject/wg-infra

**Comment by rsimha** [comment]
FYI @ampproject/wg-caching @GeorgeLuo

Given our discussion around moving the java validator tests to a new repo, we are going to disable them on `amphtml`'s Travis builds for the time being.

**Comment by rcebulko** [comment]
Update: Ubuntu keyserver appears to be back up for the time being, but still moving ahead with skipping `gulp validator-java` so we can remove the dependency altogether.
