### ISSUE TITLE
Remove documentation on overflow

### ISSUE THREAD

**Issue by Nemo64** [ampproject/amphtml#28515]
## What's the issue?

I want to use overflow-x in code snippets on a site. The amp documentation does this: [example, scroll the code snipped](https://amp.dev/documentation/guides-and-tutorials/learn/spec/amp-boilerplate/?format=websites).
But the documentation also states that I'm not allowed to use [overflow](https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml/?format=websites#properties) to add scrollbars anywhere.

## How do we reproduce the issue?

Well, you can use the example from above and add the development=1 argument which should tell you that this is invalid. But it doesn't.

## Which AMP version is affected?

Version 2005151844001

## What now?

The amp documentation makes a good case for allowing `overflow-x: auto` and I don't see a layout problem there. For other cases... I don't know, having amp components within a scolling div might cause issues. Other than that I don't really see a problem in having scrolling elements.

**Comment by Nemo64** [comment]
I also noticed that other parts of the documentation don't mention it: https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages/?format=websites

So the missing validation and the inconsistent documentation leads me to belive it's just a documentation error?

**Comment by choumx** [comment]
I think might just be a developer warning since AMP historically did not support horizontal scrollers well. AMP does support horizontal scrollers now so the documentation can probably be removed.

**Comment by Gregable** [comment]
@choumx the validator doesn't have any treatment for this, warning or otherwise. Should it? If not, I think we can just move this to be a documentation issue.

**Comment by choumx** [comment]
No, I think this is just a documentation update.
