### ISSUE TITLE
Remove AMP Analytics error when remote config returns empty response

### ISSUE THREAD

**Issue by sushan04** [ampproject/amphtml#28516]
When amp-analytics component uses remote config to retrieve the json configuration, a console log error is thrown when there's no response found (Screenshot attached).
![amp-analytics](https://user-images.githubusercontent.com/45952279/82388160-d7d89c80-9a06-11ea-985d-2f4cc3d236c7.png)

Since this can be an expected behavior for remote config, it'd be better to handle the no response case with either a warning or a graceful exit instead of a console log error as it may mislead the user of a broken response.

**Comment by zhouyx** [comment]
It's reasonable for the remote config to return an empty object. 
We decided to switch the user error to a user warning.
