### ISSUE TITLE
[amp-story] Using background-audio + autoadvance is not working.

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#28511]
Having a `background-audio` attribute on an `<amp-story-page id="my-page">`,  plus an `auto-advance-after="my-page"` should auto-advance the page when the audio is over. But this is not currently working.

example: https://www.gstatic.com/amphtml/stamp/qa/audio-story.html

Expected: page should auto-advance after audio is over
Actual: Progress bar is completely filled in current page and is not auto-advancing

/cc @ampproject/wg-stories

**Comment by Enriqe** [comment]
From a quick investigation it looks like the `duration` in the dynamically created `<audio>` is returning NaN. This [stackoverflow](https://stackoverflow.com/questions/44610417/audio-duration-returns-nan) question recommends adding `preload="metadata"`, but I think we already add `preload="auto"` which should preload the metadata too...

**Comment by gmajoulet** [comment]
Thanks for looking into this!!
To know when the duration is available you can look at the `readyState` `HAVE_METADATA` or the `loadedmetadata` event, cf https://html.spec.whatwg.org/multipage/media.html#mediaevents

**Comment by Enriqe** [comment]
So after some sleuthing I found a few things...

When `page-advancement.js` checks for the audio's duration:

https://github.com/ampproject/amphtml/blob/9e08d3be66a7fcb0c3552cd3e59f86823fe9ae38/extensions/amp-story/1.0/page-advancement.js#L1056

`this.mediaElement_` is actually an `<audio>` placeholder element created by the `media-pool` which contains no `src`.

This happens because in `amp-story-page`'s `layoutCallback` we create a new `<audio>` element and register it to the MediaPool. But since the media pool doesn't know about this element, it thinks it's a placeholder:

https://github.com/ampproject/amphtml/blob/9e08d3be66a7fcb0c3552cd3e59f86823fe9ae38/extensions/amp-story/1.0/amp-story-page.js#L532-L537

https://github.com/ampproject/amphtml/blob/90549c63b278cbf54e5e687d0a743edceb543570/extensions/amp-story/1.0/media-pool.js#L741-L745

https://github.com/ampproject/amphtml/blob/90549c63b278cbf54e5e687d0a743edceb543570/extensions/amp-story/1.0/media-pool.js#L753-L757

This placeholder element never gets any `loadedmetadata` / `timeupdate` events because it doesn't even have a source.

We have to call the `play()` method on the media pool in order to load the source back on the audio element again.

https://github.com/ampproject/amphtml/blob/90549c63b278cbf54e5e687d0a743edceb543570/extensions/amp-story/1.0/media-pool.js#L798-L805

**Comment by Enriqe** [comment]
Maybe related we are handling different audio elements of the media pool

in AmpStoryPage.layoutCallback() we register / play audio element we created (placeholder)
https://github.com/ampproject/amphtml/blob/9e08d3be66a7fcb0c3552cd3e59f86823fe9ae38/extensions/amp-story/1.0/amp-story-page.js#L535

and then in `AmpStoryPage.resume_()` we are dealing with the element that was initialized in the mediaPool from the beginning (not placeholder)
https://github.com/ampproject/amphtml/blob/9e08d3be66a7fcb0c3552cd3e59f86823fe9ae38/extensions/amp-story/1.0/amp-story-page.js#L504

we are registering the audio element that was registered in the media pool (not the

**Comment by Enriqe** [comment]
I sent #28550 which adds a patch addressing https://github.com/ampproject/amphtml/issues/28511#issuecomment-632156407, but I think we could clean this up further to address https://github.com/ampproject/amphtml/issues/28511#issuecomment-632189114
