### ISSUE TITLE
Experiment with more readable branch names for renovate major updates

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#28525]
Currently, renovate branches created for major version updates take the following form:
`renovate-bot:renovate/{{groupName}}-{{kebab-case-dependency}}.{{version}}.x`
for example: `renovate-bot:renovate/validator-google-closure-compiler-20200517.x`

**Comment by rcebulko** [comment]
Closed by https://github.com/ampproject/amphtml/pull/28627

**Comment by rsimha** [comment]
_[Infra triage]_ Closing because #28627 didn't work out.
