### ISSUE TITLE
amp-carousel v2

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#2852]
Improve on interaction and visual design of existing carousel, addressing as many of the following issues as possible in a fluid, useful re-design that includes lightbox capabilities
#2019, #2355, #2512, #1963, #2510, #2250, #2374, #1866, #2366

4/8 status: pending UX

/cc @dvoytenko @sriramkrish85 @erwinmombay

**Comment by aghassemi** [comment]
😄  I had no idea we were thinking about carousel v2 3 years ago. it's coming soon!
