### ISSUE TITLE
Add a mode to `gulp clean` to delete all `node_modules` dirs under `amphtml`

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#28537]
This can help in cases where we have breaking dependency changes. E.g. issues due to babel upgrades, or the recent `chromedriver` issue.

Nice to have: logging that prints out the directories that were actually deleted.

**Comment by rsimha** [comment]
/to @estherkim to decide if this is worth it.

**Comment by estherkim** [comment]
Could be a good fixit issue.
