### ISSUE TITLE
Move Java Validator to separate repo and remove `validator-java` gulp task

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#28533]
Tracking issue for this migration and removal of the testing infra surrounding it.

Related: https://github.com/ampproject/amphtml/issues/28497, https://github.com/ampproject/amphtml/issues/27939, https://github.com/ampproject/amphtml/issues/27786, https://github.com/ampproject/amphtml/issues/27093

/cc @rsimha

**Comment by rsimha** [comment]
Adding @Gregable, who is in the process of creating a new repo.

**Comment by Gregable** [comment]
Repo created here: https://github.com/ampproject/validator-java

cc @nhant01 @GeorgeLuo

**Comment by honeybadgerdontcare** [comment]
@nhant01 @GeorgeLuo do not have access to the new repo. who can grant them access?

**Comment by rcebulko** [comment]
It looks like @Gregable is the only contributor, or @mrjoro since he is an org admin

**Comment by Gregable** [comment]
There is a separate email thread discussing next steps to configure the repo. This is pending resolution from Raghu, but he's OOO this week.

**Comment by Gregable** [comment]
Added @GeorgeLuo, @nhant01 as repo Maintainers.
