### ISSUE TITLE
I2I: Add analytics vendor RudderStack

### ISSUE THREAD

**Issue by dhawal-rudder** [ampproject/amphtml#28543]
Hi there!

We'd like to add [RudderStack](https://rudderstack.com/) to the amp-analytics vendors list, to make it easier for our customers to integrate [RudderStack](https://rudderstack.com/) with their AMP pages.

cc @ampproject/wg-approvers
cc @ampproject/wg-analytics

**Comment by micajuine-ho** [comment]
@dhawal-rudder Thank you for your i2i! Once you have your PR out, please make sure to link this issue :) 

Feel free to assign me to the PR as well.

**Comment by micajuine-ho** [comment]
Closed via #28597
