### ISSUE TITLE
combination fails: amp-state + amp-list + amp-mustache + amp-date-display

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#28559]
this combination fails: amp-state + amp-list + amp-mustache + amp-date-display

```
<amp-state id="localState-date">
  <script type="application/json">
    {"items": [{"date":"2020-02-04T15:27:33+01:00"}]}
  </script>
</amp-state>
<amp-list
  src="amp-state:localState-date"
  single-item
  items="."
  layout="fixed-height"
  height="50"
>
<template type="amp-mustache">

<amp-date-display
  class="amp-date"
  datetime="{{date}}"
  layout="fixed-height"
  height="20"
>
<script type="text/plain" template="amp-mustache">
<div class="amp-date">
  {{monthNameShort}} {{day}}, {{year}}
</div>
</script>
</amp-date-display>

</template>
</amp-list>

```

`amp-validator` error message:

> The tag 'SCRIPT type=text/plain' may not appear as a descendant of tag 'template'.

But from "AMP Date Display: cannot be used in amp-list": https://github.com/ampproject/amphtml/issues/21758

>We do support nested templates but the syntax is a bit different:
You can use `<script type="text/html" template="amp-mustache">` instead of `<template>` for the nested case.

(corrected small type in issue-21758)

Have we made an error?

**Comment by choumx** [comment]
Yea, `<template>` and similar elements can't be nested. You'll have to extract the `<script template=amp-mustache>` out and reference it by ID in the `<amp-date-display>` instead.
