### ISSUE TITLE
AMP Ads NOT showing on Desktops

### ISSUE THREAD

**Issue by user631** [ampproject/amphtml#28554]
## What's the issue?
**Title:** AMP-ADS are not working on desktop for AMP-only site.

**Details:** I have built a AMP only site - that is, there is only one (AMP-only) version where all pages are AMP compatible.

However, after almost a year of hard work in abiding to AMP rules and making lots of compromises for limited features, I found it the hard way that the Google Adsense AMP ads (non-auto) DO NOT show when this AMP-only site is accessed through a desktop. The Adsense ads are shown only when the site is accessed through mobile devices. In worst case, many times they don't show even when the site is accessed through mobile.

A related issue exists on a GitHub thread (https://github.com/ampproject/amphtml/issues/28254) for AUTO-AMP-ADS, but Google confirmed that they have a "product error" and have asked to switch to non-auto (manual) amp-ads instead of auto-amp-ads.

Now the problem is that even the non-auto AMP-ads are not showing at all through desktop access, and are occasionally not showing through mobile access. This is also confirmed through a big mismatch between visits reported in Google Analytics, and the impressions in Google Adsense reports. All the impacted webpages are well indexes in Google and other SE, and are getting lots of organic traffic from various SE (primarily Google). Its strange that AMP-ads are not showing.

## How do we reproduce the issue?
1) Visit the page: https://fknol.com/etf/ivv.php through a DESKTOP.
You will find that when accessed thru a desktop, the amp-ads (non-auto ones) show a big blank white block just under the Page Title and Update Date timestamp ("Updated May 14, 2020")
Same on other pages like https://fknol.com/etf/qqq.php, https://fknol.com//list/market-cap-sp-500-index-companies.php, https://fknol.com/list/best-performing/basic-industries-stocks.php, and the likes

Please see **attached image** for precise details.

2) Try to access the above mentioned webpages through a mobile, and see if the AMP-ADS show up most of the times, but often they are a no-show with a whitespace blank block being displayed.

**The PRIMARY problem is non-appearance of AMP-ADS (non-auto) on desktop, and that's what needs an immediate fix.**

3) Additionally (but not urgent), while Google has confirmed that AUTO-AMP-ADS are a problem, I have left the AUTO-AMP-ADS in these webpages (https://fknol.com/candle/aapl.php) to see if they start working. Please let me know if anything can be done for AUTO-AMP-ADS.

## What browsers are affected?
ALL

## Which AMP version is affected?
AMP ⚡ HTML – Version 2005151844001
![amp-ads-error](https://user-images.githubusercontent.com/65609173/82672846-888ca900-9c5e-11ea-98bf-1ce8d1437a26.png)

**Comment by rsimha** [comment]
@ampproject/wg-ads

**Comment by calebcordry** [comment]
Thanks for reporting. I was able to repro. This seems to be an adsense specific issue where the ad server is returning this as the creative: `<html><body style="background-color:transparent"></body></html>` @Jiaming-X could you take a look?

**Comment by user631** [comment]
@ampproject/wg-ads
@Jiaming-X

Hello, just checking if there is any update on this? 
More and more webpages are missing the ads, and simply showing a whitespace large size block as shown in the image attached to original bug description. Here are two more URLs that show the white block instead of ads : https://fknol.com/dividend/list/consumer-defensive.php and https://fknol.com/dividend/list/aerospace-capital-goods.php

**Comment by jeffkaufman** [comment]
I do see the ad request going out, and the `<html><body style="background-color:transparent"></body></html>` response looks like the ad server deciding it doesn't want to serve an ad ("nofill").

When I run "Copy as cURL" on the request, and retrigger it from the command line, though, it does receive a full ad in response ("fill").

This looks like a server-side AdSense issue, so I think @Jiaming-X is better able to look at this than I would be.

**Comment by user631** [comment]
@Jiaming-X 
@ampproject/wg-ads

The responses received so far on this thread are really appreciated. However, the issue continues to persist even after almost a month of reporting, and even after several other contributors confirming that the "ad server is not serving the ad".

A bit disappointed that no response has come from the Adsense team, not even an acknowledgement :-( 

Generated reports for the last 30 days for page views and for ad views - each from Google Analytics and Google Adsense. A compare tell that only 52% of the pages are showing ads, which means that nearly 50% of page views are NOT being monetized at all! :-(

Not sure if this is because of AMP, or because of Adsense, or because of a combination of both. Anyways, It's a loss for us. :-(

**With no response, confirmation or resolution in sight, is it advisable to ditch AMP completely?**

Due to AMP, we have already made several compromises in terms of end-user site functionality, and also closed doors to other advertisers as their code is non-AMP. 

Ditching AMP will at least open doors to other monetization opportunities beyond Adsense.

At present, despite a long wait on this error, AMP and Adsense continue to be a such a loss-making proposition. 

Any thoughts, please?

**Comment by Jiaming-X** [comment]
Missed the previous chats as the notifications were sent to my personal email. What the “bug” actually is? For the blank retangle, it should be intended if we don’t have an ad.

Just for more context, for the “rspv” ad tag, it was historically created for Full-Width Ad for mobile experience. If publishers used it for desktop and the user browser happened to have a very wide viewport, it might have lower match rate. You could add a parent container and adjust the width accordingly to see if it matched better. Just some manual tests I tried for https://fknol.com/dividend/list/consumer-defensive.php: I could see the ad more often when I decrease the width of my browser compared to full-screen mode(I have a 27’' monitor).

I created an internal ticket for the team to double check.

**Comment by user631** [comment]
@Jiaming-X 
Thanks a lot! Your advice and inputs regarding rspv ad tag is helpful.
Looks like this is what was missing - "add a parent container and adjust the width accordingly to see if it matched better".
I set the div for max-width of 728 px for the ad code, and it is apparently now visible on devices of varying width.
However, I'll test it across more pages thoroughly over the next few days before concluding.

Thanks again.

**Comment by user631** [comment]
Thanks a lot @Jiaming-X , your suggestion of adding a container for adjusting the width worked. The problem is fixed, and was in the structure of the page. 

Appreciate your help and inputs!

**Comment by Jiaming-X** [comment]
Thanks for confirming! Glad that it's helpful.
