### ISSUE TITLE
Fixed layer (amp-sidebar) - reset state when elements are moved out of fixed layer

### ISSUE THREAD

**Issue by sriramkrish85** [ampproject/amphtml#2859]
## Short description of your issue:

When you move elements back and forth between the fixed layer then the computations are stacked up and it causes weirdness like this

https://www.youtube.com/watch?v=IsDShWCA7Ho&feature=youtu.be

## What browsers are affected?
IOS (safari?) - where ever fixed layer is being used.

**Comment by sriramkrish85** [comment]
**cc** @dvoytenko

**Comment by ericlindley-g** [comment]
@sriramkrish85  Tentatively slotting for 4/14, but is that too aggressive for this fix?

**Comment by sriramkrish85** [comment]
@ericlindley-g hopefully! - working on it now.
