### ISSUE TITLE
Are nested templates supported?

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#28598]
AMP documentation says that the following example of nested templates is valid and operational
For example see: https://github.com/ampproject/amphtml/issues/21758

Here is a sample structure where the source for the nested `<script>` could be a JSON endpoint or `<amp-state>` and a child processor could be `amp-date-display`
```
<amp-list id="myList" src="https://foo.com/list.json">
  <template type="amp-mustache">
    <div>{{title}}</div>
       <script type="text/plain" template="amp-mustache">
         {{foo}}
       </script>
  </template>
</amp-list>
```
The structure does pass the validator but does not work.
In contrast, nested `<templates>` do work but are not valid.

This is causing some heartburn. Can we escalate a review here?

**Comment by choumx** [comment]
Looks like the nested template does generate a validator error. Documentation shows that nested templates are a problem here: https://github.com/ampproject/amphtml/blob/84bf6f3203fd7a0a27349a18a560761ae4490320/extensions/amp-mustache/amp-mustache.md#nested-templates

**Comment by jaygray0919** [comment]
BTW, nested templates, using alternating <template> and <script>, **do not work**.
Alternatively, nested templates using <template> and <template> **do work** but are not valid.

**Comment by jaygray0919** [comment]
@choumx Since nested templates using `<template>` and `<template>` work, would you update the validator to accept the working condition?
