### ISSUE TITLE
review all components which we set `hidden` if it needs any a11y work

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#286]

**Comment by stevefaulkner** [comment]
may be helfpul http://www.html5accessibility.com/tests/hidden2013.html

**Comment by erwinmombay** [comment]
@stevefaulkner :+1: will review, thanks!

**Comment by stevefaulkner** [comment]
also this http://w3c.github.io/aria-in-html/#hiding-content-has-no-effect-on-accessible-name-or-description-calculation

**Comment by aghassemi** [comment]
Closing this, I did a run-through of components for general a11y and results are here: https://github.com/ampproject/amphtml/projects/9
