### ISSUE TITLE
Video doesn't play on tweet post in FFox Android

### ISSUE THREAD

**Issue by Ichigo3d** [ampproject/amphtml#28617]
## What's the issue?
Video doesn't play on tweet post in FFox Android

## How do we reproduce the issue?
1. Got through this link: https://www.gstatic.com/amphtml/stamp/qa/tooltip.html
2. Tap on post image
3. tap on appeared tooltip "Expand"
4. tap on video button in twit
5. Observe result
Actual result: video doesn't play
Expected result: video should start to play in tweet post

## What browsers are affected?
FFox Android

## Which AMP version is affected?
2005150002001
Is this a new issue? Or was it always broken? Paste the version of AMP where you saw this issue. (You can find the version printed in your browser's console.)

**Comment by alanorozco** [comment]
This appears to be an issue with the embedding script provided by Twitter:

```
SecurityError: The operation is insecure. TwitterVideoPlayerIframe.cefd459559024bfb.js:76
```

This occurs with a basic embed that doesn't use AMP: https://jsbin.com/venebumedo/edit?html,output

**Comment by Ichigo3d** [comment]
I found that FFox in mobile version changed settings by default in privacy. They changed: allowance cookies excluding social tracking cookies, enable tracking protection, and enable "do not track feature. If I disabled all this settings and enabled all cookies - everything works well.

**Comment by alanorozco** [comment]
@paularmstrong Escalating to Twitter since this appears to be an issue with the embed itself. Let us know if we can help out further.

**Comment by paularmstrong** [comment]
Thanks @alanorozco . I've handed this off to our internal team to figure out.

**Comment by wassgha** [comment]
@alanorozco is there a link to track this?

**Comment by alanorozco** [comment]
@paularmstrong Thank you!
@wassgha Nothing publicly from Twitter's side. I'll close this issue, I don't think we need to track the fix from our side.
