### ISSUE TITLE
Video is played with sound on the mute mode in STAMP FFox MacOS

### ISSUE THREAD

**Issue by Ichigo3d** [ampproject/amphtml#28625]
## What's the issue?
Video is played with sound on the mute mode in STAMP FFox MacOS 

## How do we reproduce the issue?
1. Go to https://www.gstatic.com/amphtml/stamp/qa/video.html
2. tap for switching to the next page
3. Observe result

Actual result: video is playing with sound in the mute mode
Expected result: video should play without sound in the mute mode.

Notice: When I tap twice on the mute button, video plays without sound.

## What browsers are affected?
FFox MacOS

## Which AMP version is affected?
012005150002001
Is this a new issue? Or was it always broken? Paste the version of AMP where you saw this issue. (You can find the version printed in your browser's console.)

**Comment by gmajoulet** [comment]
cc @ampproject/wg-stories 

@Enriqe do you have time to look into this and assess if it's release blocking?

**Comment by Enriqe** [comment]
I'm able to repro, taking a look

**Comment by gmajoulet** [comment]
Awesome thanks :)) It looks like this issue is not new so not release blocking. We should work on a fix asap though.

**Comment by Ichigo3d** [comment]
Fix is verified on 2005220120000

**Comment by Ichigo3d** [comment]
Still repro on 2005220120000 in FFox

**Comment by Enriqe** [comment]
Thanks for confirming this was an existing issue. Sorry for taking a bit to answer, picking this up again. Hope to have a fix soon.
