### ISSUE TITLE
Celebrity stories is unavailable on the 1st page of Google search page. 

### ISSUE THREAD

**Issue by Ichigo3d** [ampproject/amphtml#28628]
## What's the issue?
Celebrity stories is unavailable on the 1st page of Google search page. 
Briefly describe the bug.

## How do we reproduce the issue?
1. Go to google.com 
2. Type search request:  Denzel Washington or Emma Stone
2. Observe result 

## What browsers are affected?
All browsers

## Which AMP version is affected?
All versions
<img width="413" alt="Screen Shot 2020-05-29 at 11 56 00 AM" src="https://user-images.githubusercontent.com/37351864/83295190-6a193700-a1a3-11ea-8b63-e50706ce3768.png">

**Comment by gmajoulet** [comment]
Closing as this is an internal Google thing.
