### ISSUE TITLE
can i hide the tooltip when i click the link in the amp-story?

### ISSUE THREAD

**Issue by normanfan** [ampproject/amphtml#28620]
## Describe the new feature or change to an existing feature you'd like to see

in my case, I want to show some links in the page center. I don't want to show the tooltip when the user clicks it. so, how can I do it? 

## Describe alternatives you've considered
Can I use the  'show-tootip=false' to hide the tooltip?

**Comment by newmuis** [comment]
@normanfan it is not possible to hide the tooltip for links in the center of an `amp-story-page`.  Doing so conflicts with navigating through a story.
