### ISSUE TITLE
webmaster tools reports errors, but AMP pages validate...

### ISSUE THREAD

**Issue by alvin-milton** [ampproject/amphtml#2862]
Currently, GWT is reporting errors under the Required Tag Missing Category however, the page validates with #development=1 flag turned on.

This is the error:
- **Required tags missing:**	body, head > style : boilerplate, amphtml engine v0.js script, noscript > style : boilerplate, noscript enclosure for boilerplate

This is the url in question:
http://amp.www.complex.com/pop-culture/2013/07/donald-trump-fires-obama-in-celebrity-apprentice-spoof#development=1

There are quite a few urls under this bucket reported as error in GWT, yet validate.

All browsers are affected. Current version of amp is affected.

**Comment by cramforce** [comment]
@honeybadgerdontcare could you take a quick look? Thanks!

**Comment by Gregable** [comment]
I'm guessing by GWT, you mean Webmaster Tools / Search Console.

It looks like this document had some errors in the past when it was last crawled, but it appears fine now. It seems like the site template may have changed in the last few days? 

Search Console lags due to crawl time. If you validate with `#development=1` you should be good to go for AMP validation the next time Google indexes the page.

**Comment by adactio** [comment]
I'm running into this same issue where Webmaster Tools tells me there are errors with my AMP pages but when I then run those AMP pages through Webmaster Tools' own validation, there are no errors or warnings to be found.

Here's an example URL:

https://thesession.org/recordings/3732/amp

Google Webmaster Tools says there's an error: "Info: Missing structured data element"

And here's the result of running that same URL through the structured data testing tool:

https://search.google.com/structured-data/testing-tool/u/0/?url=https://thesession.org/recordings/3732/amp#url=https%3A%2F%2Fthesession.org%2Frecordings%2F3732%2Famp

No error.

Webmaster Tools is saying that 4,058 AMP pages have errors, and while I haven't tested each one individually, all the pages I did test came back with no errors or warnings.

This isn't about stale content either: these errors have been reported for quite a while now.

**Comment by cramforce** [comment]
I filed this as b/32193984 with the Search Console team. I know that they used to conflate AMP with the requirements of the "Top Stories Carousel" meta data, but that was supposed to be fixed.
