### ISSUE TITLE
Support data-vars for all analytics event

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#28636]
Variables as data attribute is supported by click and visible events. 
https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/analytics-vars.md#variables-as-data-attribute

To follow the thread in #28348, we propose to expand the `data-vars` attribute support to more analytics events. Including all custom events like `form-submit-success` and story events. 
With this
```
  <form data-vars-add-to-cart-form=true method="post"
    action-xhr="https://example.com/subscribe"  target="_top">
    <button type="submit">Submit me</button>
  </form>
```
`form-submit-success` event from this form will include the variable `addToCartForm=true`. 

Question: custom and story events have their own defined variables (For example `formId`). Should publishers defined `data-vars` variables be overwritten by events defined variables? 
cc @Enriqe @caroqliu

**Comment by caroqliu** [comment]
> Should publishers defined data-vars variables be overwritten by events defined variables?
For `amp-form`, `formId` is the only defined variable that could feasibly collide with the `data-vars` variables. We could explicitly disallow `data-vars-form-id` in validations to account for this one. The other fields are passed in as `formField[foo]` with the below example so this should not be an issue:

This form submission:
```html
<form id="myForm" ...>
  <input name="term" value="asd">
  <input name="term2" value="123">
</form>
```

will send analytics data with this shape: 

```json
{
  "formFields[term]": "asd",
  "formFields[term2]": "123",
  "formId": "myForm"
}
```

Haven't looked at impact for other components, though.

Another question: Is it possible to modify the variables as data attribute API to be presence-based for boolean values? Such that `<amp-foo data-my-boolean>` has a `myBoolean` value of `true` and `<amp-foo>` has a `myBoolean` value of `false`? The evaluation order could be `element.getAttribute(...) ?? element.hasAttribute(...)`, though I'm not sure with how compatible this is with the status quo.

**Comment by zhouyx** [comment]
Thank you @caroqliu, this is very helpful. 

Disallowing `data-vars-form-id` is a special case for form. I prefer a more generic solution. Sounds like we always want individual extension to override the `data-vars-*` value because the extension will have the best context. 

Here's the proposal
```
triggerAnalyticsEvent(target, eventType, opt_vars, opt_disableDataVars)
```
- `opt_vars` value will override the default `data-vars` attribute value of the `target` element. 
- `target` element's `data-vars` value will be included unless specifically disabled.


>Another question: Is it possible to modify the variables as data attribute API to be presence-based for boolean values?

The analytics service doesn't really understand the attributes. It only tries to look for attributes with the `data-vars-` prefix. In the case of `<amp-foo data-vars-my-boolean=true myBoolean = false>` I don't think it makes sense for the analytics service to try to interpret every attribute of the `<amp-foo>` component. 
It should be up to the `<amp-foo>` implementation to decide if `myBoolean` value should override `data-vars-my-boolean` value or vise versa.

**Comment by Enriqe** [comment]
Agreed that they should not be overridden since individual extensions will have more context.

**Comment by caroqliu** [comment]
Thanks for clarifying, this makes sense to me -- let's also make documenting the component-specific properties that will override data-vars a prereq for closing this issue.
