### ISSUE TITLE
Story players flash of content before first page renders

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#28649]
In some Story players (not the open source one as far as I know), the Story frequently flashes some content before rendering the first page, when it was not pre-rendered.
This does not repro on a regular cold load.

Ideas of things that could cause these flashes to look into:
- Switching player `visibilitystate` to visible/hidden (any combination)
- AMP Cache server side rendering (with `usqp` parameter)

Video available b/156913855

cc @ampproject/wg-stories

**Comment by cramforce** [comment]
Wow, this is a nasty bug.

I think this is caused by `makeBodyVisible` being called too early. But I don't yet know why.

- Could be expected error
- Could be that the story-render-delaying service should wait for children to build

**Comment by cramforce** [comment]
I sent cl/315367721 to fix the underlying issue

**Comment by gmajoulet** [comment]
Wow great find, thank you!
