### ISSUE TITLE
Correctly track LCPx metrics for Stories

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#28651]
We received feedback that Stories LCPx metrics appear to be incorrect for Stories:

https://github.com/ampproject/amphtml/blob/65a678662ebf7a7043083f938d8ed8c73feefc81/src/enums.js#L50-L52

cc @ampproject/wg-stories

**Comment by cramforce** [comment]
Did we verify that this wasn't the same general brokenness that @zhouyx fixed recently?

**Comment by cramforce** [comment]
…and did this impact the metrics reported by AMP rather than Chrome UX Report?

**Comment by zhouyx** [comment]
If only `lcpv` is broken, then it's very likely related to #29015

**Comment by gmajoulet** [comment]
This has been fixed since.
