### ISSUE TITLE
amp-script: Failed to execute 'insertBefore' on 'Node': This node type does not support this method

### ISSUE THREAD

**Issue by GhufranShahid** [ampproject/amphtml#28676]
I am using amp-script to create an animation on my AMP page.
Following is my code for the animation.
`<script id="hello-world" type="text/plain" target="amp-script">

        var sentences = [
        "I‘m not getting any impressions",
        "I‘m getting impressions but no clicks",
        "I‘m getting clicks but no conversions",
        "My wasted spend is increasing",
        "My keywords are not performing",
        "My cost per click is increasing",
        "My ad is not showing in the top position",
        "My ROI is declining"
        ];
        var index = 0;
        var reverse = false;

        setInterval(myTimer1, 1);

        function myTimer1()
        {
        if(!reverse)
        {
        sleep(120);
        }
        else{
        sleep(60);
        }
        
        sentenseAnimation(sentences[index]);

        }
        function sentenseAnimation(sentense)
        {
        if(document.querySelector(".txtex").innerHTML == "")
        {
        sleep(1000);
        }
        var s = document.querySelector(".txtex").innerHTML;
        if(s.length != sentense.length && !reverse){
        s=s + sentense.charAt(s.length)
        }
        else{
        if(!reverse)
        {

        sleep(1000);
        }
        reverse = true
        s = s.slice(0, -1);
        if(s.length == 0)
        {

        reverse = false;
        if(index < sentences.length-1){
        index++;
        }
        else{index=0;}
        }
        }
        document.querySelector(".txtex").innerHTML = s;
        }
        function sleep(delay) {
        var start = new Date().getTime();
        while (new Date().getTime() < start + delay);
        }
    </script>`
 

Animation runs smoothly but after 5 to 6 hours the animation stops and gives an error(Failed to execute 'insertBefore' on 'Node': This node type does not support this method) in amp-script.js.
The error is shown in screenshot attached.
![image_2020_06_03T11_33_33_292Z](https://user-images.githubusercontent.com/37533270/83649576-caa7da00-a5d0-11ea-8bb1-3edf9d22abba.png)

**Comment by alanorozco** [comment]
@GhufranShahid How does this animation look like? Could you achieve the same effect with CSS animations?

**Comment by choumx** [comment]
Unexpected since `Node.insertBefore` is supported by worker-dom.

**Comment by GhufranShahid** [comment]
> @GhufranShahid How does this animation look like? Could you achieve the same effect with CSS animations?

@alanorozco you can check the animation on http://ipdfapps.polyvista.com/ppcexponew.
