### ISSUE TITLE
AMP Validator: support server-side rendering img tags

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#28672]
To enable [more efficient hero image loading](https://www.webpagetest.org/video/compare.php?tests=200602_G1_2afbe599fb189aa6afee7448f98c03a6,200602_0E_484e9b7174c8cc31da7745cff0b78b1d,200602_2M_5a54e77893d95bf77c44c113f801a5aa,200602_1Z_ee1db86528db0ed0aaa528e615cc01b1) (the image gets rendered twice as fast as with amp-img) we should make it possible for publishers to server-side render the `img` tag inside an amp-img.

The following changes need to be done to the validator:

* in transformed mode, the `img` element is allowed inside an amp-img element.
* the `amp-img` needs to specify the `i-amphtml-ssr` attribute
* the same attribute validation rules apply for `img` and `amp-img`

Sidenote: inabox SSR already implements this so it's [already supported by the runtime](https://github.com/ampproject/amphtml/blob/master/builtins/amp-img.js#L164). 

//cc @kristoferbaxter @Gregable @honeybadgerdontcare @jridgewell

**Comment by jridgewell** [comment]
> The img.i-amphtml-ssr also also needs to also have loading=lazy and decoding=async, correct? 

Yes.

> Perhaps the concern here is for the minority of browsers that don't yet support lazy-loading. 

Exactly.

> In that case, perhaps the validator could just allow the first N amp-img elements in the document to have SSR'd images with loading=lazy? 

Can we share Google's implementation plan for hero images? @amaltas

**Comment by jridgewell** [comment]
This was merged with https://github.com/ampproject/amphtml/pull/29408 (cl/321463348)
