### ISSUE TITLE
URL doesn't change while scrolling to amp-next-page on cached page version

### ISSUE THREAD

**Issue by vadzim-trusau** [ampproject/amphtml#28673]
Here we use amp-next-page v1.0
https://www.google.com/amp/s/afisha.tut.by/amp/news/reviews/683752.html

When the next page appears on the screen, URL doesn't change, all analytics vendors receive the initial url 
https://drive.google.com/file/d/1DCJwyruLZz7vxXgpB7GVWl7NkpsTfj6e/view 

Version from our server https://afisha.tut.by/amp/news/reviews/683752.html works as it's expected

Seems it's a bug.

Console errors:
error.js:208 failed to execute a task:: Request replaceHistory failed: fb
error.js:208 history trace for replace: History: failed to execute a task:: Request replaceHistory failed: fb _reported_

**Comment by cramforce** [comment]
Actually fixing this needs major viewer work. Fixing analytics events should be easier.

**Comment by aldeimos** [comment]
> Here we use amp-next-page v1.0
> https://www.google.com/amp/s/afisha.tut.by/amp/news/reviews/683752.html
> 
> When the next page appears on the screen, URL doesn't change, all analytics vendors receive the initial url
> https://drive.google.com/file/d/1DCJwyruLZz7vxXgpB7GVWl7NkpsTfj6e/view
> 
> Version from our server https://afisha.tut.by/amp/news/reviews/683752.html works as it's expected
> 
> Seems it's a bug.
> 
> Console errors:
> error.js:208 failed to execute a task:: Request replaceHistory failed: fb
> error.js:208 history trace for replace: History: failed to execute a task:: Request replaceHistory failed: fb _reported_

Hello there. Did you manage to fix it?

**Comment by vadzim-trusau** [comment]
> > Here we use amp-next-page v1.0
> > https://www.google.com/amp/s/afisha.tut.by/amp/news/reviews/683752.html
> > When the next page appears on the screen, URL doesn't change, all analytics vendors receive the initial url
> > https://drive.google.com/file/d/1DCJwyruLZz7vxXgpB7GVWl7NkpsTfj6e/view
> > Version from our server https://afisha.tut.by/amp/news/reviews/683752.html works as it's expected
> > Seems it's a bug.
> > Console errors:
> > error.js:208 failed to execute a task:: Request replaceHistory failed: fb
> > error.js:208 history trace for replace: History: failed to execute a task:: Request replaceHistory failed: fb _reported_
> 
> Hello there. Did you manage to fix it?

uh no, we wait for it from amp-dev team
