### ISSUE TITLE
amp-ad - [AmpAnalytics <unknown id>] Inline or remote config should not overwrite vendor transport settings

### ISSUE THREAD

**Issue by smatoox** [ampproject/amphtml#28675]
## What's the issue?

<amp-ad> return error in console about AmpAnalytics :

`[AmpAnalytics <unknown id>] Inline or remote config should not overwrite vendor transport settings log.js:258`

I'm using `<amp-analytics>` too but same errors without analytics module.

## How do we reproduce the issue?

Each error depends of amp-ad :
> <amp-ad width="320" height="50" type="doubleclick"data-slot="/{id}/amp_/45503615/mweb_fussballtransfers/hp_infeed_1" rtc-config='{"vendors": {"aps": {"PUB_ID": "{id}","PARAMS":{"amp":"1"}},"criteo": {"NETWORK_ID": {id}}}}'></amp-ad>

_{id} are replaced with values_

An other error is displayed sometimes and I don't know if its related:

> Refused to frame '<URL>' because it violates the following Content Security Policy directive: "frame-src cm.g.doubleclick.net googleads.g.doubleclick.net <URL> accounts.google.com pagead2.googlesyndication.com/pagead/s/cookie_push.html gmsg: <URL>".

You can see this errors on :

- https://www.fussballtransfers.com/home-amp
- https://www.fussballtransfers.com/amp3118520006219860946-hannover-96-neuer-stuermer-aus-istanbul

## What browsers are affected?

Test on Chrome and Firefox, Linux Ubuntu and Mac OS.
And probably on smartphones...

## Which AMP version is affected?

- https://cdn.ampproject.org/v0/amp-ad-0.1.js
- https://cdn.ampproject.org/v0/amp-analytics-0.1.js

**Comment by zhouyx** [comment]
@smatoox Thanks for reporting. This is a recent regression on amp-analytics. It should only affect error reporting, and has been fixed by #28448
