### ISSUE TITLE
Consent: Support the reprompt API to clear stored consent

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#28684]
The `prompt` action will take arg `expireCache=true` (default to false).
When set to `true`, AMP will set dirtyBit to the stored consent information and clear value on next user visit.

**Comment by tla-sirdata** [comment]
Hi @zhouyx, me again :)
Can you tell me in which case this feature would be used ? A publisher providing a button for users to delete their choices ?
Thanks
