### ISSUE TITLE
amp-subscriptions Error: fetch entitlements failed for local: timeout​​​

### ISSUE THREAD

**Issue by fdosruiz** [ampproject/amphtml#28693]
## What's the issue?

We are using the amp-subscriptions component for our subscription model, but we are having problems from quite a few users who report that the paywall appears when it shouldn't.

Researching on this topic, we have seen that when the paywall jumps in the console the following error appears:

```
log.js:710 Uncaught (in promise) Error: fetch entitlements failed for local: timeout​​​
    at bb (log.js:710)
    at Ya.f.createError (log.js:359)
    at timer-impl.js:142
    at timer-impl.js:83bb@log.js:694f.createError@log.js:344(anonymous)@timer-impl.js:117(anonymous)@storage-impl.js:417setTimeout (async)f.delay@storage-impl.js:417(anonymous)@timer-impl.js:117f.timeoutPromise@timer-impl.js:117(anonymous)@amp-subscriptions.js:519Promise.then (async)nd@amp-subscriptions.js:519(anonymous)@amp-subscriptions.js:139(anonymous)@amp-subscriptions.js:139Promise.then (async)push.f.h.start@amp-subscriptions.js:139(anonymous)@amp-subscriptions.js:755Tc@service.js:392S@experiments.js:370(anonymous)@extensions-impl.js:364f.addDocFactory@extensions-impl.js:404f.addService@extensions-impl.js:364(anonymous)@amp-subscriptions.js:755f@amp-subscriptions.js:755f.registerExtension@core-services.js:122(anonymous)@runtime.js:82
```
The operation mode we use for amp-subscriptions is through iframe, and we have been able to verify that the authorization service is not responsible for this error.

## How do we reproduce the issue?

We have been able to reproduce the error by limiting the network bandwidth, and verifying that the problem is due to the initial loading time of the page, which explains that when the network or the user's device is slow, the payment wall jumps.

By default, this article is always open for paywall, but when the error appears, the modal paywall is activated, because it omits the loading the autentication service, and the fallbackEntitlement.granted is false by default. For example, you can reproduce it by limiting the bandwith to 1024 kbits of download.

Example: https://elpais.com/elpais/2020/05/12/planeta_futuro/1589279924_166617.amp.html

1. Limit bandwith to 1024kbits. For this, you can use wondershaper for linux. (sudo wondershaper eth1 1024 1024)
2. Open a new navigation tab, with the developer tool open and with the option "Disable cache" activated.
3. Load the article url (https://elpais.com/elpais/2020/05/12/planeta_futuro/1589279924_166617.amp.html).
4. You should see the timeout error in the console tab.

The part of the code where the exception comes from:

```javascript
import {ENTITLEMENTS_REQUEST_TIMEOUT} from './constants';

  /**
   * @param {!SubscriptionPlatform} subscriptionPlatform
   * @return {!Promise}
   */
  fetchEntitlements_(subscriptionPlatform) {
    // Don't fetch entitlements on free pages.
    if (this.isPageFree_()) {
      return Promise.resolve();
    }    let timeout = ENTITLEMENTS_REQUEST_TIMEOUT;
    if (getMode().development || getMode().localDev) {
      timeout = ENTITLEMENTS_REQUEST_TIMEOUT * 2;
    }
    // Prerender safe platforms don't have to wait for the
    // page to become visible, all others wait for whenFirstVisible()
    const visiblePromise = subscriptionPlatform.isPrerenderSafe()
      ? Promise.resolve()
      : this.ampdoc_.whenFirstVisible();
    return visiblePromise.then(() =>
      this.timer_
        .timeoutPromise(timeout, this.getEntitlements_(subscriptionPlatform))
        .then((entitlement) => {
          entitlement =
            entitlement ||
            Entitlement.empty(subscriptionPlatform.getServiceId());
          this.resolveEntitlementsToStore_(
            subscriptionPlatform.getServiceId(),
            entitlement
          );
          return entitlement;
        })
        .catch((reason) => {
          const serviceId = subscriptionPlatform.getServiceId();
          this.platformStore_.reportPlatformFailureAndFallback(serviceId);
          throw user().createError(
            `fetch entitlements failed for ${serviceId}`,
            reason
          );
        })
    );
  }
```
https://raw.githubusercontent.com/ampproject/amphtml/2005150002001/extensions/amp-subscriptions/0.1/amp-subscriptions.js

## What browsers are affected?

All browsers and devices.

## Which AMP version is affected?

Version 2005150002001

**Comment by gmajoulet** [comment]
@ampproject/wg-access-subscriptions
