### ISSUE TITLE
AMP analytics scroll-related vars return Doubles for Android, where int is expected

### ISSUE THREAD

**Issue by colmsnowplow** [ampproject/amphtml#28691]
## What's the issue?

AMP analytics variables `${scrollTop}` and `${scrollLeft}` return double values on Android devices, where they should be integer (or at least, they are integer elsewhere and intuitively seem as if they should be, given that it's 'number of pixels').

## How do we reproduce the issue?

Fire some Snowplow extension [page ping events](https://github.com/ampproject/amphtml/blob/d26998701caec331942277745a5a977ee2663c25/extensions/amp-analytics/0.1/vendors/snowplow_v2.json#L32) from Android. 

## What browsers are affected?

Seems to be all browsers on android.

## Which AMP version is affected?

Seems to have always been this way.

cc @max-tgam who [reported the issue for the Snowplow extension](https://github.com/snowplow-incubator/amphtml/issues/10)

**Comment by gmajoulet** [comment]
@ampproject/wg-analytics @zhouyx

**Comment by zhouyx** [comment]
Thanks for reporting! Indeed the `pageYOffset` we're using is subpixel precise, so it may not be an integer.
https://developer.mozilla.org/en-US/docs/Web/API/Window/pageYOffset

What we can do is to always roundup the value before sending it out.

**Comment by max-tgam** [comment]
@zhouyx Is this (rounding) something we can do inside analytics code (i.e. inside https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/vendors/snowplow_v2.json) or it has to be done before that?

**Comment by zhouyx** [comment]
I think it is reasonable to have [amp-analytics](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/variables.js#L231) round up all `SCROLL_TOP` and `SCROLL_LEFT` values. Or even the [AMP viewport service](https://github.com/ampproject/amphtml/blob/master/src/service/viewport/viewport-impl.js#L247) to round up the value so the fix applies to all usage.

**Comment by zhouyx** [comment]
@jridgewell 
Do you think we should convert all `scroll_top` to integer in the runtime? 
I can change all `viewportBinding.getScrollTop`, or change the `viewport.getScrollTop()`.

**Comment by cramforce** [comment]
I think we shouldn't change anything internally. Rounding the external value makes sense.

**Comment by zhouyx** [comment]
Cool. I'll make the change to amp-analytics.

Curious how useful the subpixel precision is. I found it to be a bit confusing without know whether I'll get an integer or a double value. Which might be the case why we have the conversion here. 
https://github.com/ampproject/amphtml/blob/3966448e41f2c714dc09311f568aa2040b079465/src/service/viewport/viewport-impl.js#L356-L361
