### ISSUE TITLE
Adsense unknown attribute adRegion

### ISSUE THREAD

**Issue by dmitrymotorin** [ampproject/amphtml#2870]
Hey guys,
We've implemented ad regions (data-ad-region) for adsense blocks and got an error:
**_Uncaught Error: Unknown attribute for adsense: adRegion.​​​_**
If this attribute is unknown, will adsense receive it?

**Page example**
[http://womanitely.com/exercises-transform-your-body/amp-list/](http://womanitely.com/exercises-transform-your-body/amp-list/)

**Block example**
`<amp-ad width="300" height="250" type="adsense" data-ad-region="REGION_1" data-ad-client="ca-pub-8125901705757971" data-ad-slot="7783467241"></amp-ad>`

**Comment by cramforce** [comment]
Also cc @bobcassels

**Comment by michaelkleber** [comment]
No, the set of publisher controls supported by AdSense in the AMP runtime is very limited, and the data-ad-region / google_ad_region setting will have no effect.  All configuration of your ad slots should happen in the AdSense Frontend, not in the HTML.

**Comment by ericlindley-g** [comment]
@dmitrymotorin  Closing as answered, but please feel free to reopen if there are unanswered questions here
