### ISSUE TITLE
Pass consent string to amp-iframe / amp-video-iframe

### ISSUE THREAD

**Issue by nerdbeere** [ampproject/amphtml#28719]
Hi,
I wasn't able to find anything on this topic. If there's already something planned it would be great if you could point me in the right direction so we can track this issue on our end.

## Describe the new feature or change to an existing feature you'd like to see

Pass the tcf 2.0 consent string to `amp-iframe` and `amp-video-iframe`

## Additional context

We provide a video player to our customers. Those customers (publishers) heavily rely on monetization on amp pages which we provide through video ads. To ensure proper monetization in the future we need a way to retrieve the consent string and pass it to our advertising partners.

**Comment by zhouyx** [comment]
cc @ampproject/wg-ui-and-a11y

**Comment by zhouyx** [comment]
Sounds reasonable to be. Today `amp-iframe` and `amp-video-iframe` components both has the capability to retrieve the TC string. I think what's missing is a postMessage API for the iframe to listen to the string. To @alanorozco on the message API design. 

One question I have is: would the video be blocked until TC string has been collected or what's a fallback case?

**Comment by nerdbeere** [comment]
> One question I have is: would the video be blocked until TC string has been collected or what's a fallback case?

Maybe some more context: We pass the consent string to the saleshouses we work with. Those saleshouses consume the consent string and decide whether they want to monetize or not.

To answer your question: If we don't retrieve a consent string it will (at the moment) most likely lead to no monetization but our player will play content anyway.

**Comment by zhouyx** [comment]
Thank you @nerdbeere for the clarification. 
In this case I think it makes sense to have the `<amp-video-iframe>` pass the consent information to the iframe via postMessage. So it won't block the content.

**Comment by nerdbeere** [comment]
@zhouyx For us it's important that also `<amp-iframe>` gets access to consent information as that's how our customers currently embed us.

**Comment by nerdbeere** [comment]
Hi @alanorozco @zhouyx is there an update on this? For us this is very important so if you could point us in the right direction we could prepare a PR on the matter.

**Comment by nerdbeere** [comment]
Hi @alanorozco @zhouyx I implemented this now the same way `send-interactions` is implemented within `amp-iframe` which would be a good solution for us. I opened a PR and would be happy to receive some feedback from you.
