### ISSUE TITLE
“Failed to load resource: the server responded with a status of 406 (Not Acceptable)” using amp-script

### ISSUE THREAD

**Issue by GhufranShahid** [ampproject/amphtml#28712]
I downloaded the sample code of AMP from "https://github.com/CrystalOnScript/vanilla-js-amp-script". I am getting "Failed to load resource: the server responded with a status of 406 (Not Acceptable)" in my browser's console. I have referred my script as <amp-script  src="http://localhost:9999/scripts/script.js">
![screenshot](https://user-images.githubusercontent.com/37533270/83891701-05dc1180-a767-11ea-9365-b83021bc4556.png)

**Comment by kristoferbaxter** [comment]
Did a fresh clone of the project and it seemed to work here. 

Adding @CrystalOnScript who might want to move this issue to `vanilla-js-amp-script` repo, but can answer better than I.

[Screen Recording 2020-06-05 at 8.34.04 AM.mov.zip](https://github.com/ampproject/amphtml/files/4737021/Screen.Recording.2020-06-05.at.8.34.04.AM.mov.zip)

**Comment by CrystalOnScript** [comment]
Thanks for highlighting this! This repo is no longer maintained, instead try:
https://github.com/ampproject/samples/tree/master/amp-script-tutorial
