### ISSUE TITLE
Please add Media Impact to the Ad Documentation

### ISSUE THREAD

**Issue by adtechnology** [ampproject/amphtml#2871]
Please add Media Impact to the list of supported Ad Networks:

https://www.ampproject.org/docs/reference/amp-ad.html

**Comment by ericlindley-g** [comment]
Thanks for flagging this, @adtechnology —

@cramforce, this [merged PR](https://github.com/ampproject/amphtml/pull/2069) seems to have added support: is there anything we're waiting on to update the documentation?

**Comment by cramforce** [comment]
Nope, this is typically done as part of the initial PR. @adtechnology feel free to send a follow up PR.
