### ISSUE TITLE
La validación de la URL falló debido a un JSON no esperado en la respuesta de validación AMP.

### ISSUE THREAD

**Issue by agustinparera** [ampproject/amphtml#28718]
Como puedo resolver esto?
 How can I solve this?

**Comment by Ichigo3d** [comment]
Hello. Thank you for participate in improving our product. Could you provide more information about this issue: steps to reproduce, screenshots or video. It will help us for solve with problem faster.

**Comment by Ichigo3d** [comment]
"URL validation failed due to an unexpected JSON in AMP validation response." -  title in English
