### ISSUE TITLE
AMP-SCRIPT adding info logs in browser console

### ISSUE THREAD

**Issue by rohit-ambre** [ampproject/amphtml#28714]
## What's the issue?
AMP-SCRIPT adding info logs in browser console it's annoying for site in production.

![image](https://user-images.githubusercontent.com/20537740/83950210-989fad80-a846-11ea-802a-4633fe6aee39.png)

## How do we reproduce the issue?
I am not using '#development=1' but still amp-script logs present. I am not sure if amp has any other developer mode running which need to be de-activated but as per document could not see any such mode details shared.

## What browsers are affected?
It's present in Chrome and Firefox.

## Which AMP version is affected?
Powered by AMP ⚡ HTML – Version 2005220120000

**Comment by Ichigo3d** [comment]
I checked it on https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-script&format=websites&_gl=1*1qlth51*_ga*MTA2MzUzODA2Mi4xNTkxMjIwNDc2
