### ISSUE TITLE
amp-brightcove does not correctly render when nested inside other components

### ISSUE THREAD

**Issue by jwinkworth** [ampproject/amphtml#28745]
## What's the issue?
amp-brightcove does not correctly render when "shown/hidden" while nested in components such as amp-selector or amp-accordion.

### Brightcove inside Selector
* Visit https://dcc-upload.s3.ca-central-1.amazonaws.com/jw-rnd-days/cs-amp-templates/bug85277/amp-issue-selector.html#development=1
* When the page is loaded, the Brightcove component is correctly rendered inside an amp-selector.
* Switch to the second tab. Switch back to the first tab.
* The Brightcove video now displays a "loading" icon.

### Brightcove inside Accordion
* Visit https://dcc-upload.s3.ca-central-1.amazonaws.com/jw-rnd-days/cs-amp-templates/bug85277/amp-issue-accordion.html#development=1
* Note that in the console, the following warning appears: <code>[amp-brightcove] Did not receive ready callback from player null. Ensure it has the videojs-amp-support plugin.</code> This appears to be due to the brightcove component has not been fully rendered because it is hidden in a closed accordion pane.
* When the page is loaded and the second accordion pane is expanded, the Brightcove component is correctly rendered inside.
* Collapse the second tab. Re-expand the second tab.
* The Brightcove video now displays a "loading" icon.

## What browsers are affected?
Was able to reproduce in the latest version of the following browsers:
* Chrome Desktop (OSX)
* Chrome Desktop (Win 10)
* Chrome Moble (Android)
* Firefox Desktop (OSX)
* Firefox Desktop (Win 10)
* Firefox Mobile (Android)
* Edge (Win 10)

## Which AMP version is affected?
0.1

## Other information
[The example of a video carousel](https://amp.dev/documentation/examples/multimedia-animations/video_carousels_with_amp-carousel/?format=websites) is currently exhibiting the same behavior (the third slide in the example is amp-brightcove).

[This stackoverflow post](https://stackoverflow.com/a/53063375/1306) references an amp-brightcove attribute "noloading" which is [not documented](https://amp.dev/documentation/components/amp-brightcove/?format=websites#attributes). Adding this in fixes the issue above.

**Comment by Ichigo3d** [comment]
cc @dvoytenko  Could you review it please? I checked it and issue is reproducible.

**Comment by gmajoulet** [comment]
cc @ampproject/wg-ui-and-a11y

**Comment by jwinkworth** [comment]
@alanorozco I reviewed this change this morning, and when you collapse the accordion, then re-open it, the *player* is re-rendered but the video no longer plays
https://dcc-upload.s3.ca-central-1.amazonaws.com/jw-rnd-days/cs-amp-templates/bug85277/amp-issue-accordion.html#development=1
