### ISSUE TITLE
Embed AMP story player doesn't work on FFox browser MacOS

### ISSUE THREAD

**Issue by Ichigo3d** [ampproject/amphtml#28777]
## What's the issue?
Embed AMP story player doesn't work on FFox browser MacOS.
It shows blank screen in embed page.

## How do we reproduce the issue?

1. Go to https://amp.dev/documentation/guides-and-tutorials/integrate/embed-stories/
2. Observe result

## What browsers are affected?
FFox MacOS

## Which AMP version is affected?
2005272217000
<img width="979" alt="Screen Shot 2020-06-09 at 12 20 38 PM" src="https://user-images.githubusercontent.com/37351864/84190703-357f6800-aa4c-11ea-8246-a5b85beb7d3d.png">

**Comment by cpauwels** [comment]
@Enriqe any updates on this? This is quite a big issue for us at Tappable, as we use the amp-story-player quite heavily.

**Comment by Enriqe** [comment]
Looking into this now @cpauwels

**Comment by Ichigo3d** [comment]
It still repro on 2006050512000 
https://github.com/ampproject/amphtml/issues/28909

**Comment by Enriqe** [comment]
That's because `2006050512000` was cut on June 10th, and the fix was merged on June 12th. That means it didn't make the cut for this release, and should be available on the next one.

**Comment by Ichigo3d** [comment]
Still repro on 2006112352000 FFox MacOS
