### ISSUE TITLE
remove canary flag found in amp-login-done-0.1.js

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#2882]
This is because amp-login-done has its own compile steps, It shouldn't have the global canary flag on it. doesn't hurt anything right now since amp-login-done is currently not loaded with the main binary but this should still be fixed.

**Comment by ericlindley-g** [comment]
Rolling into the next milestone

**Comment by erwinmombay** [comment]
closed by https://github.com/ampproject/amphtml/pull/3230
