### ISSUE TITLE
Amp story auto ad does not load properly when shown twice

### ISSUE THREAD

**Issue by mszylkowski** [ampproject/amphtml#28840]
## What's the issue?

When loading http://localhost:8000/examples/amp-story/ampconf.html, the first ad (after page 1) works as expected, but the second ad (after page 7) takes me to the second page. This results in an endless loop where it's impossible to advance to page 8, since it always takes me to page 2 after page 7.

eg: 
1 -> ad -> 2 -> 3 -> 4 -> 5 -> 6 -> 7 -> ad
..................^______________________________˩

A closer inspection on the elements show that the second time the ad is loaded, the attributes return-to and advance-to still point to the pages 1 and 2, even though they should point to pages 6 and 7.

## How do we reproduce the issue?

Open ampconf.html in the examples folder and go through the story. The location of the ads is dynamic so it doesn't always load 2 ads.

## What browsers are affected?

Tested on Mac > Chrome, probably happens in other browsers

**Comment by calebcordry** [comment]
also the ad is broken due to trying to load from ampbyexample.com, not sure if this is causal

**Comment by mszylkowski** [comment]
If you have a working ad url I could try it and let you know
