### ISSUE TITLE
amp-bind updates multiple images on setState update

### ISSUE THREAD

**Issue by anuragphadke** [ampproject/amphtml#28857]
## What's the issue?
I am using amp-bind with setState to update the amp-img URLs for different swatches at https://beta.webfast.co/magma/collections-galaxy.html 
However, even though I am updating specific variables such as s0, there are other divs that are getting updated which isn't the intent.

## How do we reproduce the issue?
1. Visit https://beta.webfast.co/magma/collections-galaxy.html
2. Scroll to product that has title "Last Resort Men's Tee" (the div on the left)
3. Click on the first swatch that has the color white.
4. The product image div to the right of the swatch disappears.
5. The neighboring div image should not be affected.

## What browsers are affected?
Chrome, Safari

## Which AMP version is affected?
2005272217000

Is this a new issue? Or was it always broken? Paste the version of AMP where you saw this issue. 
New issue. Noticing it for first time.

**Comment by choumx** [comment]
I think the problem is that the other variables are evaluated to `null`, so you need to initialize them with the default values. You can see this printed in dev console if you add `#log=4` to the end of your URL.

Also see: https://amp.dev/documentation/components/amp-bind/?referrer=ampproject.org#warnings

**Comment by anuragphadke** [comment]
@choumx : I tried the above suggestion, see: 
https://beta.webfast.co/magma/swatch.html

Do I need to add value to setState for s0 and s1 for every independent invocation of on:tap? 

Or am I initializing in the wrong way?

**Comment by choumx** [comment]
No, either you can use amp-state to initialize each variable or you can add the default value directly into the expression.

```html
<amp-state id=products>
  <script type=application/json>
    {
      "s0": ...,
      "s1": ...
  </script>
</amp-state>

<amp-img [src]="products.s0" on="tap:AMP.setState({products: {s0: <new_value>}})"></amp-img>

<!-- OR -->

<amp-img [src]="s0 || 'my_default_url'"></amp-img>
```

**Comment by anuragphadke** [comment]
thx @choumx . The above pointer definitely helped.
