### ISSUE TITLE
For amp-story consent, Accept text on button not display sometime in mobile.

### ISSUE THREAD

**Issue by akashshah3991** [ampproject/amphtml#28861]
##  What's the issue?
In amp-story,Accept text on button not display sometime as shown in test case snapshot image.

![testcaseimg](https://user-images.githubusercontent.com/53644713/84515038-8eb7f780-ace9-11ea-9912-1c0c549abf8f.jpg)

## How do we reproduce the issue?

Actually issue is random and you may get this issue in following url within mobile;
https://stories.whatahotel.com/
for example ,  https://stories.whatahotel.com/us-virgin-islands-best-hotels

Html code

![consent](https://user-images.githubusercontent.com/53644713/84514715-18b39080-ace9-11ea-84f2-778c75726f79.PNG)

## What browsers are affected?
Mobile browsers , mostly safari

## Which AMP version is affected?
Current AMP Version

## Test case snapshots
[Images.zip](https://github.com/ampproject/amphtml/files/4771449/Images.zip)

**Comment by Ichigo3d** [comment]
Hello. Thank you for participate in improve our product. I can't repro it. Could you send more information: version mobile OS, version browsers, did you use wifi or LTE or GSM connection, model of phone? Thank you

**Comment by akashshah3991** [comment]
@Ichigo3d 
Hi, Details are:
 iPhone X , Network is WiFi , Latest Safari Browser Version, and exactly OS version we don't know as we haven't tested it on multiple versions. But you can take the latest and its earliest.

**Comment by gmajoulet** [comment]
Thanks for the bug report! Could you please try to get the exact iOS version? I've been trying various versions / phones, and asked other team members to check as well, so far we haven't been able to repro. :(

**Comment by akashshah3991** [comment]
@gmajoulet 
Hi, the issue was also produced on the Mobile model: iPhone Xʀ, iOS Version: 13.5.1 (17F80).
