### ISSUE TITLE
🐛 Story Ad: move CTA to shadow DOM

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#28865]
Pub styles are leaking to the button affecting letter spacing, eg https://www.10best.com/web-stories/how-to-extend-the-life-of-your-spices-and-herbs/

![image](https://user-images.githubusercontent.com/16087874/84529768-e4af7f80-ac96-11ea-98d9-ffb58ed1e0b1.png)

**Comment by gmajoulet** [comment]
Even in a Shadow DOM, inherited properties will pierce the Shadow DOM boundaries. If that helps, we're using this reset on top of Shadow DOM to fully scope Story components: https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/1.0/amp-story-shadow-reset.css
