### ISSUE TITLE
<amp-img> is not displaying image

### ISSUE THREAD

**Issue by GhufranShahid** [ampproject/amphtml#28880]
I am using amp-img tag for all my images.
if I use 
![image](https://user-images.githubusercontent.com/37533270/84670523-abe60380-af3f-11ea-9aac-dd251ef4df15.png)
it seems like 
![image](https://user-images.githubusercontent.com/37533270/84669549-696ff700-af3e-11ea-9628-48b183f4ba6c.png) in console. You can see that img tag inside amp-img tag.In some cases amp is not producing img tag inside amp-img tag and in those cases images are not displaying.
For example I am using 
 <amp-img width="17.05" height="21.9" src="~/Content/images/AMPReports/play.svg" alt="" border="0"style="overflow: inherit;"></amp-img> 
and it seems like ![image](https://user-images.githubusercontent.com/37533270/84670007-f6b34b80-af3e-11ea-9b63-10f9e6f5d68c.png) in console.

Please help me with this issue.

**Comment by Ichigo3d** [comment]
Good morning. Thank you for participate in improve of our product. Could you send me url of your site, I want to check it. And how often do you see this issue? Thank you.
