### ISSUE TITLE
add new amp-analytics triggers for Core Web Vitals

### ISSUE THREAD

**Issue by patrickkettner** [ampproject/amphtml#28881]
## Describe the new feature or change to an existing feature you'd like to see

We have access to the metadata around Core Web Vitals with #28122, but there isn't an obvious [trigger](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/configure-analytics/deep_dive_analytics/#when-data-gets-sent:-triggers-attribute). It would be great to add a new trigger for this data.

Anything would be fine, but perhaps that can send data before close ([`onbeforeunload`](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload) for example).

## Describe alternatives you've considered

as LCP, CLS, and FID could happen at any time during the users time on the page, the only [trigger](https://amp.dev/documentation/components/amp-analytics#triggers) choice that makes sense as a global recommendation is `timer`, but that would of course be a kludge that could miss short sessions, etc.

**Comment by micajuine-ho** [comment]
Hi @patrickkettner, an option here is to use a trigger like the visibility trigger, as it resolves its macros async, meaning that it will wait for the core web vital macros (`LARGEST_CONTENTFUL_PAINT`, `FIRST_INPUT_DELAY`, and `CUMULATIVE_LAYOUT_SHIFT`) to resolve before sending out the request.

**Comment by patrickkettner** [comment]
thanks a lot @micajuine-ho! That is a much better workaround than the `timer` I mentioned.
The reason this came up was I was writing some docs around how to use it for amp.dev. Using `visibility` feels unintuitive advice to be giving (at least on face value). Do you think there is a way to have a trigger that does the same action but be named in a way that is less confusing?

**Comment by micajuine-ho** [comment]
@patrickcarey what do you suggest the name of the new trigger to be?

**Comment by patrickkettner** [comment]
if the original idea is used, `beforeUnload` would be my first guess as it has existing connotations. 
If it is the same as `visibility`, but renamed, maybe something like `afterResolved`? It feels a bit more complex as it depends on the specifics of how the reporting is done though. For example

- if I request `LARGEST_CONTENTFUL_PAINT` and `FIRST_INPUT_DELAY` on my site's amp-analytics config, but my page does not have any inputs (and therefore FID never occurs), is it submitted after `LARGEST_CONTENTFUL_PAINT` fulfilled?
- What happens if an even larger `LARGEST_CONTENTFUL_PAINT` occurs after an initial one? Are two analytics requests triggered?

**Comment by patrickkettner** [comment]
(sorry, I just realized you may have meant that question for patrick carey, rather than me)

**Comment by micajuine-ho** [comment]
> It feels a bit more complex as it depends on the specifics of how the reporting is done though. 

I agree that it does feel more complex. My initial reaction would be to add documentation to the Visibility Trigger where we state how it will wait for all macros to resolve before sending the request (and if the macro resolves to null, then it never occurred), as well as adding documentation to the LCP, FID, and FCP macros saying how we recommend using the visibility trigger.

What are your thoughts on that?

**Comment by patrickkettner** [comment]
> and if the macro resolves to null, then it never occurred

to be clear - does that mean if someone requests FID, but FID never occurs, they would get none of the information?

**Comment by micajuine-ho** [comment]
>to be clear - does that mean if someone requests all of their Core Web Vitals, but FID never occurs, they would get none of the information?

@patrickkettner The other CWV would still be there (assuming they happened)

**Comment by patrickkettner** [comment]
Apologies for the novice question, but if the trigger occurs after the values resolve and one of the values doesn’t resolve, how is it still triggered ?

**Comment by micajuine-ho** [comment]
When the visibility trigger occurs, amp-analytics will wait for all the macros in the request to resolve to a value (potentially null) before sending out the request. In the end, all the macros will resolve, and at that point the request will be sent out.

Does that answer your question?

**Comment by patrickkettner** [comment]
I think! 

Thanks so much for explaining it all. One thing that I am not clear on - first input delay measures how long it takes for the first input (button, text input, etc) you interact to become responsive. You may not have an input for a long period of time (i.e, long form article, recipe, or other page that they takes a long time to read, but there is a button at the end to rate it).

So if Alice has an amp webpage that 20 minutes to read, with a button at the bottom. She configures amp-analytics to measure FID, LCP, and CLS. Bob reads the article, and then at minute 20 taps on that input (thereby allowing the browser to measure the delay for the first input). Carol read the article in the same amount of time, but closes rather than interact with the button. In a vanilla web app, Alice could measure Bob's FID, but not Carols. What would happen here? 

Unless I am misreading #28122, there isn't a special case being handled that would `null` out a value. It just assigns the value once that performance tick occurs if the browser supports it, (if the browser doesn't support it and there is no polyfill, the value is dropped). How do we know to submit the values that have occurred? Sorry for the pestering, I just want to make sure the docs being written aren't misleading folks.

thanks again!

**Comment by micajuine-ho** [comment]
> In a vanilla web app, Alice could measure Bob's FID, but not Carols. What would happen here?

I believe the same thing would happen, Carols FID would not be calculated and thus no request would be sent.

> How do we know to submit the values that have occurred? Sorry for the pestering, I just want to make sure the docs being written aren't misleading folks.

What do you mean by 'submit the values'? Submit these resolved values to where?

**Comment by patrickkettner** [comment]
> What do you mean by 'submit the values'? Submit these resolved values to where?

Sorry, didn't have a better phrasing. I meant "the event the developer is tracking is sent to the analytics server".


I think I may have had a fundamental misunderstanding though. If I want to track the three Core Web Vital metrics, does amp-analytics send three separate analytics events? I have been laboring under the assumption it would send one. If it is multiple, would you be able to share an example config for tracking the three core web vitals?


thanks again!

**Comment by micajuine-ho** [comment]
We could make it send out multiple or requests or a single request.

Single:
```
{
        "requests": {
          "endpoint": "https://fake.com/analytics?fid=${firstInputDelay}&fcp=${firstContentfulPaint}&cls=${cumulativeLayoutShift}"
        },
        "triggers": {
            "pageview": {
                "on": "visible",
                "request": "endpoint"
            }
        },
        "transport": {
          "beacon": false,
          "xhrpost": false,
          "image": true
        }
      }
```

One request per Core Web Vital:
```
{
        "requests": {
          "endpoint": "https://fake.com/analytics?"
        },
        "triggers": {
            "pageviewCls": {
                "on": "visible",
                "request": "endpoint",
                "extraUrlParams": {
                  "cls": "${cumulativeLayoutShift}"
                }
            },
            "pageviewFid": {
                "on": "visible",
                "request": "endpoint",
                "extraUrlParams": {
                  "fid": "${firstInputDelay}"
                }
            },
            "pageviewFcp": {
                "on": "visible",
                "request": "endpoint",
                "extraUrlParams": {
                  "fcp": "${firstContentfulPaint}"
                }
            }
        },
        "transport": {
          "beacon": false,
          "xhrpost": false,
          "image": true
        }
      }
```
