### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by pasha-bolokhov** [ampproject/amphtml#28890]
At the top of page
https://amp.dev/documentation/guides-and-tutorials/start/visual_story/animating_elements/?format=stories
"use in a webs tory:"

**Comment by Ichigo3d** [comment]
Thank you for participate in improve of our product. 
<img width="801" alt="Screen Shot 2020-06-15 at 3 06 12 PM" src="https://user-images.githubusercontent.com/37351864/84710873-eb99f480-af19-11ea-98de-b4e248860089.png">

**Comment by patrickkettner** [comment]
@Ichigo3d I believe you meant  to assign me :)

**Comment by patrickkettner** [comment]
Thanks a lot @pasha-bolokhov. The website is actually at [ampproject/amp.dev](https://github.com/ampproject/amp.dev). It was fixed in ampproject/amp.dev#4082 and it is now live on the site

**Comment by Ichigo3d** [comment]
Verified that it's fixed. Closing task

**Comment by erwinmombay** [comment]
closed by https://github.com/ampproject/amp.dev/pull/4082
