### ISSUE TITLE
Experiment with running AMP tests on Circle CI

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#28897]
We'd like to get a sense for whether and how easily AMP code can be built / tested on Circle CI.

Some questions to answer:
- Does a full `gulp dist` work on Circle CI?
- Do `gulp unit` and `gulp integration` run and pass?
- Which OSs does Circle CI natively support? (Linux should work, most likely MacOS too, and less likely Windows)
- How fast are the VMs? (Start up time, set up time, build time, testing time, etc.)
- Any other observations (good or bad)?

Github integration can be [enabled](https://circleci.com/integrations/github/) for a personal fork of `amphtml`, following which a minimal build / test job can be [configured](https://circleci.com/docs/2.0/configuration-reference/) using these [samples](https://circleci.com/docs/2.0/sample-config/) for inspiration.

/cc @ampproject/wg-infra

**Comment by danielrozenberg** [comment]
> * Does a full `gulp dist` work on Circle CI?

* Yes

> * Do `gulp unit` and `gulp integration` run and pass?

* I managed to get `gulp unit` to pass when I placed it in the same "job" as `gulp dist`, but not when separated. Probably a matter of caching the exact right set of files/directories though.
* `gulp integration` fails hundreds of tests on timeouts, not sure what's going on

> * Which OSs does Circle CI natively support? (Linux should work, most likely MacOS too, and less likely Windows)

* Seems to support all three, although I only tried Linux

> * How fast are the VMs? (Start up time, set up time, build time, testing time, etc.)

* Startup is immediate (~1-2 seconds after a commit is pushed). `gulp dist` runs in around 6-9 minutes in the few builds I tried

> * Any other observations (good or bad)?

* *good* extremely flexible, configuration-wise
* *good* has a built-in mechanism to share data between jobs
* *good* interface is clean, jobs can be split into individual steps in a way similar to folding on Travis, but more "baked in" to the UI
* *bad* couldn't figure out how to expose build logs to the public
* *bad* if a job goes on for long its log loses colouration
* *bad* doesn't do word wrapping, so e.g., browserify's dots cause a long horizontal iframe

**Comment by rsimha** [comment]
Thanks for doing the research! Closing this issue now that we have the data we were looking for.
