### ISSUE TITLE
Flaky test in amp-font

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2890]
See https://travis-ci.org/ampproject/amphtml/builds/122667706

**Comment by ericlindley-g** [comment]
@cramforce : putting in backlog, but please feel free to bump to another milestone or let me know if there's a more specific timeline for this

**Comment by cramforce** [comment]
Flaky tests should be fixed in the next available 30 minutes :)

**Comment by ericlindley-g** [comment]
Yikes—will update. Thanks!

**Comment by cramforce** [comment]
We should at least look at them every week. Most are simple to fix, but
increase dev productivity enough to make them net-positive in a week.

**Comment by ericlindley-g** [comment]
Rolling into the next milestone

**Comment by sriramkrish85** [comment]
Not happening anymore after @mkhatib s fixes.
