### ISSUE TITLE
Allow amp-lightbox to be closed by swiping down

### ISSUE THREAD

**Issue by otsuky** [ampproject/amphtml#28900]
## Describe the new feature or change to an existing feature you'd like to see

I would like to close the amp-lightbox with a down swipe gesture to improve UX, like amp-lightbox-gallarey.

## Describe alternatives you've considered

I considered using amp-lightbox-gallarey. 
But I couldn't do it because I needed to display videos in the lightbox.

**Comment by krdwan** [comment]
Hi @nainar , would you mind commenting on the priority of the feature request?

**Comment by ydnikolaev** [comment]
same here
will be usable  for creating  native app like menus
