### ISSUE TITLE
Amp-side bar dragging issue 

### ISSUE THREAD

**Issue by yk8329** [ampproject/amphtml#28902]
when using amp-sidebar and dragging the sidebar the following errors are printed in the console.
![err](https://user-images.githubusercontent.com/63966974/84736863-5dc71380-afc4-11ea-86ac-9b5333dae365.png)
and this is the console error
gesture.js:462 Unable to preventDefault inside passive event listener invocation.
please resolve this issue as soon as possible.

**Comment by Ichigo3d** [comment]
Good morning. Thank you for participate in improve of our product. Could you provide more information about the bug: URL of your site and steps to reproduce. Thank you

**Comment by yk8329** [comment]
Thanks for fast reply.
The website is 
1)My Website :- [https://blog.ykdeveloper.com](url)
 Steps to reproduce issue :- 

1. Open Developers tools
2.Open Mobile View of website you will see a menu open the sidebar and drag it left and right.
3. You will see the errors in console "gesture.js:462 Unable to preventDefault inside passive event listener invocation."

![Screenshot from 2020-06-16 22-08-28](https://user-images.githubusercontent.com/63966974/84802272-f938a280-b01d-11ea-99ae-ab5aa82c2e94.png)


This issue is also on official website of AMP.dev  [https://amp.dev/documentation/examples/components/amp-sidebar/preview/?format=websites](url)
just open demo in mobile view open sidebar and try dragging you wiil see errors in console.
