### ISSUE TITLE
Auto advance after media should take precedence over the loop attribute

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#28913]
If a media has a `loop` attribute but is used for page level `auto-advance-after`, the page will restart instead of advancing to the next one.
We should remove the `loop` attribute when a media is used in a `auto-advance-after` attribute.

Example: https://www.usatoday.com/web-stories/here-is-why-mail-in-voting-is-so-controversial/

cc @ampproject/wg-stories

**Comment by newmuis** [comment]
This is potentially a breaking change; ideally the two options would be mutually exclusive, but since we haven't enforced that, it's kind of an undefined behavior.  But we wouldn't know how many stories whose behavior would be altered by this, right?

**Comment by newmuis** [comment]
Put another way: can we just tell publishers who run into this not to specify both?  Either by picking documentation, through active outreach, or with console warnings/errors?

**Comment by Enriqe** [comment]
@newmuis what do you think publishers expect when they define an auto advance after=video with a loop attribute? (Genuine question, I can’t think of a reasonable behavior other than ignoring the loop)

**Comment by gmajoulet** [comment]
The story I linked to has been fixed so it's not a good example.
If you use a video to auto advance but keep the 'loop' attribute, it'll restart the page when the video ends rather than auto advancing.

**Comment by Enriqe** [comment]
> it'll restart the page when the video ends rather than auto advancing.

But that's also the behavior of having a video with the `loop` attribute without the `auto-advance-after` attribute, right? I feel like if the publisher explicitly specified the `auto-advance-after` attribute it's because they want the story to continue advancing, not get stuck in this video.

**Comment by gmajoulet** [comment]
Yes I totally agree with you :))
We should remove the `loop` if and only if this very video is used to auto-advance. Otherwise the progress bar segment loops too because the video never triggers an `end` event.
