### ISSUE TITLE
Flaky test in amp-fit-test

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2891]
See https://travis-ci.org/ampproject/amphtml/builds/122602067

**Comment by ericlindley-g** [comment]
@cramforce : putting in backlog, but please feel free to bump to another milestone or let me know if there's a more specific timeline for this

**Comment by dvoytenko** [comment]
This is not related to the `amp-fit-text` - this looks like a general iframe testing thing. Closing in favor of other improvements we do here.
