### ISSUE TITLE
Flaky test in Viewer test

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2892]
See https://travis-ci.org/ampproject/amphtml/builds/122662551

**Comment by dvoytenko** [comment]
@jridgewell Looks like visibility transition tests fail here. PTAL.

**Comment by ericlindley-g** [comment]
@cramforce : putting in backlog, but please feel free to bump to another milestone or let me know if there's a more specific timeline for this

**Comment by jridgewell** [comment]
These already have an extended 5s timeout. Short of some clever solution to drop our iframe usage, I don't know how to make these types of tests better.

**Comment by cramforce** [comment]
The flakes caused by us loading iframes from our own test server are really sad.

I was hoping to at some point have the time to replace those that can with the fixture mechanism that doesn't hit the network. Still really curious why they are so slow.

**Comment by rudygalfi** [comment]
This hasn't been touched in awhile. Can we move to "Next" or "Backlog" milestone?

**Comment by jridgewell** [comment]
Closed due to https://github.com/ampproject/amphtml/issues/3461.
