### ISSUE TITLE
amp-next-page v1.0 freezes browser tab 

### ISSUE THREAD

**Issue by ags1773** [ampproject/amphtml#28924]
## What's the issue?
`amp-next-page` freezes the browser tab when a remote url is given as `src`. This happens when the JSON configuration contains the `next` key
 
## How do we reproduce the issue?
- repo containing an express app serving static html demonstrating the issue > https://github.com/ags1773/express-app
- URL of deployed app > https://amp-bug.herokuapp.com
- Screen Recording for reference https://youtu.be/CTApdnz1v0U

## What browsers are affected?
All browsers that I tested on
Chrome 83.0.4103.106 (MacBook Pro)
Firefox 76.0.1 (MacBook Pro)
Chrome 83.0.xx (Android 9)

## Which AMP version is affected?
amp-next-page version 1.0

Is this a new issue? Or was it always broken? Paste the version of AMP where you saw this issue. 
Not sure if it's new or existing issue
Version 2006050512000

**Comment by wassgha** [comment]
@ags1773 Thank you for the highly detailed bug report and demo pages! Looking into this.
