### ISSUE TITLE
'ended' event for amp-video component

### ISSUE THREAD

**Issue by noodles** [ampproject/amphtml#28938]
## Describe the new feature or change to an existing feature you'd like to see

The amp-video & amp-youtube components currently only support 2 events, firstPlay & timeUpdate.

I would like an additional 'ended' event added to these components that fires when the video or playlist has finished playing.

## Additional context

A use case for this feature would be when a video is playing in a lightbox. The 'ended' event could be used to close the lightbox when the video has completed playing.

It would also be useful if this feature was made available to all video components e.g. amp-vimeo

**Comment by AnthonyMondelloAU** [comment]
Please see an example of our websites-https://www.thephotographyinstitute.edu.au/ 

On the home page of some of our sites we have included video. It is a little clumsy, as our developer is unable to make the video auto play, for the background music to auto play and importantly for the video to auto close at the end of the viewing session, to direct the user back to the website.
 
After paying for most of the traffic, we really need the user to be re-directed back to the site for obvious commercial reasons.

Can this be solved asap
