### ISSUE TITLE
Intent-to-Deprecate-and-Remove: amp-social-share[data-mode=replace]

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#28947]
## Summary

The `amp-social-share` component has a an attribute `data-mode=replace` that is used in tandem with `type=system` to produce the following behavior: If the WebShare API is supported on the device, all `type!=system` instances of `amp-social-share` elements will collapse in the document. 

This issue intends to deprecate and remove support of the `data-mode=replace` attribute.

For example, if a document has the following three instances of `amp-social-share`, and a user loads the page with WebShare API support, the `type=facebook` and `type=twitter` instances will always collapse:
```html
<amp-social-share type="system"
                  data-mode="replace"
                  data-param-text="Shared via the Web Share API"
                  aria-label="Share">
</amp-social-share>
<amp-social-share type="facebook"
                  data-param-text="Hello world"
                  data-param-href="https://example.com/?ref=URL"
                  data-param-app_id="123"
                  aria-label="Share to Facebook">
</amp-social-share>
<amp-social-share type="twitter"
                  aria-label="Share to Twitter">
</amp-social-share>
```

## Motivation

This feature causes significant layout shift which is fundamentally in opposition to providing a good page experience.

## Impact on existing users

Where the button would have collapsed before, it will stay visible, statically sized, and interactable. This means in contexts where the WebShare API is supported, users will still be able to click on `type != system` buttons to share.

## Alternative implementation suggestion for developers using AMP

I suppose you could still hide the non-`type=system` instances on user interaction rather than on load with something like this:
```html
<amp-social-share type="system"
                  data-mode="replace"
                  data-param-text="Shared via the Web Share API"
                  aria-label="Share"
                  on="tap:facebookShare.hide,twitterShare.hide">
</amp-social-share>
<amp-social-share type="facebook" id="facebookShare"
                  data-param-text="Hello world"
                  data-param-href="https://example.com/?ref=URL"
                  data-param-app_id="123"
                  aria-label="Share to Facebook">
</amp-social-share>
<amp-social-share type="twitter" id="twitterShare"
                  aria-label="Share to Twitter">
</amp-social-share>
```

## Additional context

#27228 

/cc @ampproject/wg-approvers

**Comment by cramforce** [comment]
I don't think we should do this. I think `replace` should even be the default.

Given that roughly 100% of mobile browsers support web-share, we should make it such that if `replace` is present, we hide the non-system `amp-social-share` instances using CSS to avoid CLS impact.

**Comment by dvoytenko** [comment]
Maybe it should be one component with `type=auto` and we'd use type=system if available and otherwise will dropdown a list of other known (or configured) share types? Or something like this?

```
<amp-social-share type=system>
  <div fallback>
    <amp-social-share type=facebook></amp-social-share>
    <amp-social-share type=twitter></amp-social-share>
    ...
  </div>
</amp-social-share>
```

**Comment by cramforce** [comment]
Yep, that would be better!

**Comment by caroqliu** [comment]
From #27228:

> The WebShare API supported with `data-mode=replace` behavior requires further work:
> - In the short term we can file an intent to deprecate `data-mode=replace` (low usage as of today) because it is fundamentally not in the spirit of core web vitals
> - In the long term design a grouping component that can behave roughly as follows: Display a single button for sharing. If WebShare API is supported, trigger that. Otherwise turn into a click-to-expand/dropdown/slide-out experience that displays other `amp-social-share` instances.

This I2D is being filed as a short term stop-gap to discontinue allowing the unstable layout experience that is the status quo for the feature in question. This includes an action to introduce a deprecation warning for a period of at least 6-weeks. 

The less immediate resolution, similar to what is described above, can still provide an experience in the spirit of the original feature. This might be timed to coincide with the conclusion of the warning period or introduced in parallel with the removal of the existing feature, but I may be misunderstanding if the intention is for the availability of the new feature to preclude removing of the old.

**Comment by caroqliu** [comment]
I also disagree with using CSS to hide as a reason not to remove the `data-mode=replace` feature. 

Let's say we hide with `visibility: hidden` In a row of `amp-social-share` components, it could cause a set of buttons that is structured like the first to effectively render as the second, causing it to appear randomly placed:

```
[ x ][ x ][ x ][ x ][ s ][ x ][ x ]

[   ][   ][   ][   ][ s ][   ][   ]
```

We had previously discussed using CSS to [eliminate horizontal shift to some degree](https://github.com/ampproject/amphtml/pull/27312). While this reduces layout shift significantly in some cases, it also increases it significantly in others.

**Comment by cramforce** [comment]
Do we have hard data for how often making the change would move documents from having bad CLS to having good CLS?

The technical merits we should probably discuss in a design review.

**Comment by caroqliu** [comment]
Sounds good. To follow up here: I'm going to perform further analysis with `gulp performance` and bring this discussion to an upcoming design review.
