### ISSUE TITLE
[amp-base-carousel] progress indicator when auto-advance is enabled

### ISSUE THREAD

**Issue by eduardogoncalves** [ampproject/amphtml#28959]
Display a progress bar for each slide, something like whats is done on [Web Stories](https://amp.dev/about/stories/)

![image](https://user-images.githubusercontent.com/4308648/85164276-21005400-b232-11ea-9dbb-e64453e4640e.png)

Maybe when `auto-advance` is set true, `amp-base-carousel` could expose a **% value** representing the current time based on `auto-advance-interval` so the designer can use this % value to customize a progress indicator via `amp-bind`.

https://codepen.io/pseudop/pen/Xedbam
![image](https://user-images.githubusercontent.com/4308648/85163445-d500df80-b230-11ea-97eb-2349ce7b6c66.png)

https://codepen.io/nevnein/pen/NBWdwb
![image](https://user-images.githubusercontent.com/4308648/85165293-9a4c7680-b233-11ea-9d05-ad5a18e3f3c6.png)

https://codepen.io/hus_hmd/pen/PNepRJ
![image](https://user-images.githubusercontent.com/4308648/85163966-a20b1b80-b231-11ea-9dfb-4220aa9a7a87.png)

**Comment by caroqliu** [comment]
@eduardogoncalves thanks for filing this issue! If you are interested in having a progress indicator paired with your carousel, I would recommend using [`amp-inline-gallery`](https://amp.dev/documentation/components/amp-inline-gallery/), which is powered by `amp-base-carousel` and provides progress in the form of dot or thumbnail pagination options.

**Comment by eduardogoncalves** [comment]
Hi @caroqliu :)
Is it possible to enable/extends `amp-inline-gallery-pagination` to display a progress bar in each indicator like `amp-stories`?

![image](https://user-images.githubusercontent.com/4308648/86184784-dc629b80-bb02-11ea-836c-968aaceafe9c.png)
