### ISSUE TITLE
Enable hero image optimization by AMP Caches and Optimizers via `data-hero` attribute

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#28954]
Image loading in AMP is currently blocked by the runtime JS which has a negative impact on LCP. AMP Caches and Optimizers can improve this by rewriting `amp-img` to `img` tags. However, automatically detecting hero images is often not feasible (e.g. the [amp.dev](https://amp.dev) homepage has multiple hero images). The only way to support these cases (without rendering the page) is to make it possible for developers to explicitly markup hero images. 

Proposal: introduce a new attribute `data-hero` that can be used to explicitly declare hero elements. The attribute would be supported by AMP Caches and Optimizers for the following elements:

* amp-img
* amp-iframe
* amp-video
* amp-video-iframe
* amp-anim

This change does not require any changes on runtime side, but needs to be documented.

//cc @ampproject/wg-caching @ampproject/wg-performance @patrickkettner @westonruter

**Comment by twifkak** [comment]
http://b/79420251 has some useful context, too.

**Comment by sebastianbenz** [comment]
Documented in the new AMP Optimizer landing page.

**Comment by jridgewell** [comment]
Can you share a link to the landing page?

**Comment by sebastianbenz** [comment]
Landing page:
https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/amp-optimizer-guide/?format=websites
Section about hero images:
https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/amp-optimizer-guide/explainer/?format=websites#hero-image-optimization

>

**Comment by twifkak** [comment]
@jridgewell Is this bug fixed? (Have the validator changes been made?)

**Comment by jridgewell** [comment]
Validator changes landed in https://github.com/ampproject/amphtml/pull/29408

**Comment by twifkak** [comment]
Oops, sorry, I somehow missed that it was already closed. yada yada mondays
