### ISSUE TITLE
Arrows disappear on amp-carousel if you click on it too fast

### ISSUE THREAD

**Issue by razvan-rotaru** [ampproject/amphtml#28953]
## What's the issue?

amp-carousel:
On mobile if you click on an item while the carousel scroll still has inertia the arrows disappear and never appear back

## How do we reproduce the issue?

1. Use a phone or Google Chrome mobile view
2. Swipe to the right or left fast so the slider has inertia
3. Click on an item before the slider stops
4. Both arrows disappear and never appear again

## What browsers are affected?

Tested on MacOs 10.15.4  Chrome 83.0.4103.97 and my client reported the issue first on IPhone X Safari.

## Which AMP version is affected?

amp-carousel 0.2

## Video recording of the issue on Chrome mobile view

[Documentation_ _amp-carousel_ - amp.dev.mp4.zip](https://github.com/ampproject/amphtml/files/4802537/Documentation_._amp-carousel_.-.amp.dev.mp4.zip)

This was recorded on the official amp-carousel demo page: https://amp.dev/documentation/components/amp-carousel/?format=websites

**Comment by Ichigo3d** [comment]
Hello. Thank you for participate in improve of our product. I checked it's reproducible on real device (Safari IOS) and Chrome mobile view Iphone X MacOS. @nainar, could you see it?

**Comment by Ichigo3d** [comment]
cc @alanorozco and @wassgha
