### ISSUE TITLE
Flaky visual test: amphtml-ads: friendly iframe static (page view)

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#28975]
https://percy.io/ampproject/amphtml/builds/5652990

Looks like a race: the screenshot can be taken either before or after component load.

![image](https://user-images.githubusercontent.com/254946/85315165-652c6800-b46f-11ea-89b0-2f251bc06c32.png)

/cc @ampproject/wg-ads

**Comment by powerivq** [comment]
@alanorozco Thanks. I was able to confirm that the js we ran does not properly wait till loaded.

**Comment by rsimha** [comment]
This test is still flaky.
