### ISSUE TITLE
🌸 Cherry-pick request for #28777 into #28910 and #28789 (Approved)

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#28981]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #28777 | #28873 |     **YES**     | **YES** | **NO** | #28910 #28789                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

amp-story-player fails to load in Firefox.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

There is some unexpected behavior when adding certain sandbox flag to the iframe in Firefox, if other flags weren't applied beforehand.

## Impact

- All Firefox users.

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by cramforce** [comment]
Approved

**Comment by lannka** [comment]
Is this still valid?

**Comment by Enriqe** [comment]
Nope, I think I forgot to close it.
