### ISSUE TITLE
StoryPage getAllVideos_() sometimes returns the empty set if there is a video

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#28997]
Repro case:

Slide 1 of http://localhost:8000/proxy/s/nowthisnews.com/stories/you-can-be-served-by-a-robot-at-this-korean-coffee-shop/

during init phase (e.g. when we start measuring performance)

**Comment by gmajoulet** [comment]
Good catch, thanks! We did get some reports that video performance were not logged on the first page of a story.

**Comment by cramforce** [comment]
Would probably be good to get a fix in. Ideally the getAllVideos_ functions and similar would return a promise or we find some other way to not externalize the state machine to the caller.

**Comment by gmajoulet** [comment]
What's the bug you noticed? The fact that getAllVideos_() returns an empty set is kinda WAI, we then subscribe to visibility events and perform all the required operations as they get visible. This is so publishers can show/hide videos using CSS media queries for different templates / aspect ratios.

I'm sending a fix for the performance measurements but was curious to know if there's any other one.

**Comment by cramforce** [comment]
If this is WAI, some docs might help. I might have also ignored them :)
