### ISSUE TITLE
Support for CCPA Implementation

### ISSUE THREAD

**Issue by abhiz10** [ampproject/amphtml#28996]
Hi Team,
I need to implement CCPA on my website, I mean in AMP pages and AMP Story Pages, I am attaching two demo file of my implementation, Please can you confirm the implementation are right or not.
PFA
[CCPA_Implementation.zip](https://github.com/ampproject/amphtml/files/4818205/CCPA_Implementation.zip)

**Comment by micajuine-ho** [comment]
@abhiz10  They look good to me.

**Comment by abhiz10** [comment]
Thanks, @micajuine-ho so I can use custom list list "mylist" in Story HTML, and one <div> using the same id in as I mentioned in AMPHtml ?

**Comment by micajuine-ho** [comment]
@abhiz10 The amp-consent integration with amp-geo works across stories and amphtml.

**Comment by abhiz10** [comment]
Actually What I meant to say that 
In AMP HTML:
<amp-geo layout="nodisplay">
        <script type="application/json">
            {
            "ISOCountryGroups": {
            "eea": ["preset-eea"],
            "usca":["preset-us-ca"]
            }
            }
        </script>
    </amp-geo>
    <amp-consent id="myUserConsent" layout="nodisplay">
        <script type="application/json">
            {
            "consentInstanceId":"world-wide-consent",
            "consentRequired":false,
            "geoOverride":{
            "eea":{
            "promptUI":"consentDialog",
            "consentRequired":true
            },
            "usca":{
            "consentRequired":true,
            "promptUI":"consentDialog"
            }
            }
            }
        </script>
        <div id="consentDialog">
            <div class="consentPopup">
                <div class="bg-lgo-banner"></div>
                <div class="bg-lgo">
                    <amp-img src="https://media.visualstories.com/visual/favicon-260x260.png" layout="intrinsic" width="40" height="40"></amp-img>
                </div>
                <div class="consent-wrap">
                    <div class="consent-wrap__inr">
                        <p class="p-x4">
                            We use cookies to ensure you get the best experience. By using our website you agree to our policy of using cookies. For more information, please visit our <a class="a-clr-uline" href="https://visualstories.com/about/privacy" target="_top" title="Privacy Policy">Privacy Policy</a>.
                        </p>
                    </div>
                    <div class="cnst-btn-link p-y5">
                        <button on="tap:myUserConsent.accept" class="cnsnt-cta-link">Accept</button>
                    </div>
                </div>
            </div>
        </div>
    </amp-consent>

I am using the same ["promptUI":"consentDialog"] for both "eea" and "usca" is that ok to use the same "promptUI" Id for both?
As I'm using one  "<div id="consentDialog">" block to show the same message for both "eea" and "usca"

**Comment by abhiz10** [comment]
And, while in AMP Stories also I'm using only one div in consent, but create my custom array: "mylist" in amp-geo and in consent is mentioned "promptIfUnknownForGeoGroup": "mylist".
<script type="application/json">
            {
            "ISOCountryGroups": {
            "eea": ["preset-eea"],
			"usca":["preset-us-ca"],
			"mylist":["preset-eea","preset-us-ca","in"]
            }
            }
        </script>
         </amp-geo>
         <amp-consent id='storyConsent' layout='nodisplay'>
            <script type="application/json">
               {
               "consents": {
               "storyConsent": {
               "promptIfUnknownForGeoGroup": "mylist",
               "promptUI": "storyConsentUi"
               }
               }
               }
            </script>

**Comment by abhiz10** [comment]
Actually the issue what I'm facing with AMP-Stories that I can't use this script in AMP-Stories format its show me error in console: error.js:204 Cannot convert undefined or null to object 
<script type="application/json">
{
"consentInstanceId":"world-wide-consent",
"consentRequired":false,
"geoOverride":{
"eea":{
"promptUI":"consentDialog",
"consentRequired":true
},
"usca":{
"consentRequired":true,
"promptUI":"consentDialog"
}
}
}
</script>

**Comment by abhiz10** [comment]
[Story_AMPConsent_CCPA_2.txt](https://github.com/ampproject/amphtml/files/4827852/Story_AMPConsent_CCPA_2.txt)
In this, I had used this script <script type="application/json"> { "consentInstanceId":"world-wide-consent", "consentRequired":false, "geoOverride":{ "eea":{ "promptUI":"consentDialog", "consentRequired":true }, "usca":{ "consentRequired":true, "promptUI":"consentDialog" } } } </script>
Showing me error in console: error.js:204 Cannot convert undefined or null to object

**Comment by abhiz10** [comment]
@micajuine-ho Can you check all the implementation once regarding my concerns, please, it would be a great help

**Comment by micajuine-ho** [comment]
> I am using the same ["promptUI":"consentDialog"] for both "eea" and "usca" is that ok to use the same "promptUI" Id for both?

Yes that is fine.

> Can you check all the implementation once regarding my concerns, please, it would be a great help

Looking now

**Comment by abhiz10** [comment]
@micajuine-ho thank you so much

**Comment by micajuine-ho** [comment]
@abhiz10 FYI this is actually a bug, and it is on my radar to fix. There should be no changes necessary on your end.

**Comment by abhiz10** [comment]
@micajuine-ho Ok
