### ISSUE TITLE
Visibility tracking error from inabox ad rendered in friendly iframe

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#28994]
The issue is related to the recent `INTERSECTION_OBSERVER_POLYFILL_INABOX` launch. 

The inob polyfill doesn't work in friendly iframe, and we failed to set up the `win.IntersectionObserver['_setupCrossOriginUpdater']` in the friendly iframe case. This leads to the inob entry fired even when the iframe itself is out of viewport. 

Three steps to fix the issue
1. To unlaunch `INTERSECTION_OBSERVER_POLYFILL_INABOX` #28988 
2. To register `win.IntersectionObserver['_setupCrossOriginUpdater']` when the inabox ad is rendered in friendly iframe
3. To potentially change the polyfill behavior.

**Comment by dvoytenko** [comment]
Blocked by https://github.com/w3c/IntersectionObserver/pull/436
