### ISSUE TITLE
New optional attributes for Stories to better represent the creator entity 

### ISSUE THREAD

**Issue by raovs** [ampproject/amphtml#28992]
## Describe the new feature or change to an existing feature you'd like to see

Add three optional attributes to the <amp-story> component to better reflect the creator or entity who made the Story.

- Entity name (text)
- Entity URL (link to entity's web presence) 
- Entity avatar (link to logo for entity)

In many different use cases, the publisher name alone does not provide sufficient attribution for a Story:
- Publishers might want to attribute the Story to a section (e.g. "AB News Lifestyle" or "AB News Cooking") or to a reporter / creator (e.g. "Jane Doe")
- Platforms may need to better represent and attribute the person or channel who created the Story (e.g. "Jane Doe" or "Storymaker12")

## Describe alternatives you've considered

Some of this information can be provided in Schema.org metadata, but having it within the Story component will help tools and Story creators more consistently represent and attribute to creators.

@jasti @newmuis @gmajoulet

**Comment by gmajoulet** [comment]
Existing metadata: `publisher`, `publisher-logo-src`, ...

Proposed metadata API:

```
<amp-story creator="String" creator-logo-src="URL" creator-url="URL"
```

**Comment by gmajoulet** [comment]
@jasti is suggesting that we use `entity` over `creator` so it works for more use cases, eg: "<Publisher> cooking"

**Comment by raovs** [comment]
+1 to entity over creator
