### ISSUE TITLE
I2I: Implementing amp-sona custom component to amp pages

### ISSUE THREAD

**Issue by daniel-samson** [ampproject/amphtml#29013]
## Summary

Adds amp-sona custom component to amp pages, which displays images and videos from the [Digitonic Sona](https://digitonic.co.uk/platforms/sona) network.

## Design document

Process Overview / Flow:
- adds an iframe to the amp page
- iframe loads an image or video from the Digitonic Sona Network
- the image or video is displayed
- fraud protection is recorded

## Motivation

The amp-sona components provide the ability for advertisers and publishers to add a Digitonic Sona Widget to their AMP sites.

### Alternatives Considered

Adding a new type to amp-ad was considered but there is a limitation, we can not run our Widget. The related tags such as amp-analytics and amp-pixel would not be able to support a fully compliant, unique user tracking method regulated in accordance with GDPR and CCPA.

The amp-iframe was also considered, but the documentation strictly forbids the use of iframes for advertising purposes. 

## Additional context

Information about the [Digitonic Sona](https://digitonic.co.uk/platforms/sona) product.

PR is coming soon...

## Launch tracker

/cc @ampproject/wg-approvers

**Comment by lannka** [comment]
> ... which displays images and videos from the Digitonic Sona network.

Are the images and videos ad creatives?

> Adding a new type to amp-ad was considered but there is a limitation, we can not run our Widget.

What kind of widget are you referring to?

**Comment by daniel-samson** [comment]
Hi lannka

`Are the images and videos ad creatives?`
Yes they are like ad creatives, but they are provided by the Digitonic sona network.


`What kind of widget are you referring to?`

The widget is javascript code which gets the assets, performs fraud protection.

**Comment by lannka** [comment]
Correct me if wrong, looking at your PR, all the proposed extension does is to inject an iframe. I'm wondering why it cannot be done via `amp-ad` which is exactly designed for this..

**Comment by daniel-samson** [comment]
After looking at amp-ad in more detail i think you are correct. Also i just found "Integrating ad networks into AMP". So i think i will try an create a new type instead of an extension. What is the process for doing so? eg do you need an I2I?
