### ISSUE TITLE
LCP and FID variable values differ greatly from chrome extension values

### ISSUE THREAD

**Issue by hannahmahon** [ampproject/amphtml#29015]
## What's the issue?
The substitute variables for LCP and FID in my `amp-analytics` script don't appear to be accurate. They are both long ints that look like `1593003422844`, and don't match any of the numbers output by my web vitals chrome extension (not simply a matter of moving a decimal point)

## How do we reproduce the issue?
My code looks like this: 
```
...
<amp-analytics type="googleanalytics" id="googleanalytics1">
<script type="application/json">
{
   "vars":{
      "account":"UA-XXXXXXX-1"
   },
   "extraUrlParams":{
      "cd53":"Outlook;History"
   },
   "triggers":{
      "webVitals": {
      	"on":"visible",
         "request":"event",
         "extraUrlParams":{
            "lcp":"${largestContentfulPaint}",
            "fid":"${firstInputDelay}",
            "cls":"${cumulativeLayoutShift}"
         }
      }
   }
}
</script>
</amp-analytics>
```

CLS is working beautifully, but when I look at the network call for lcp & fid, they look more like ids than the true vital values. I can't get a jsbin to fire any of the events so I don't have a sandbox for you, but hoping you can still help

![image](https://user-images.githubusercontent.com/15826427/85568828-06e2bf00-b600-11ea-9c47-b2cb87427ba2.png)
![image](https://user-images.githubusercontent.com/15826427/85568883-13671780-b600-11ea-82e0-99aa14605137.png)
![image](https://user-images.githubusercontent.com/15826427/85568919-1cf07f80-b600-11ea-8341-9fac817fabd5.png)

## What browsers are affected?
At least chrome

## Which AMP version is affected?
Version 2006112352001

**Comment by Ichigo3d** [comment]
cc @zhouyx

**Comment by zhouyx** [comment]
Thanks for reporting. Taking a look

**Comment by zhouyx** [comment]
Found two issues. 
1. There's a bug on how we offset the pre-rendering time 
2. largest-contentful-paint is resolved only after the document turned invisible. 
Will follow up with PRs to fix them.

**Comment by hannahmahon** [comment]
Awesome, thanks for the fast turnaround!!

**Comment by zhouyx** [comment]
@hannahmahon The issue has been fixed by #29039, it should be shipped in production within two weeks. 

(We decided not to request cherry-pick to patch the fix because this is a recently shipped feature without wide adoption yet. And there's no regression, the issue existed when we shipped the feature. ) Please let us know if you feel otherwise. 

Thank you.

**Comment by hannahmahon** [comment]
Thanks for letting me know, sounds good!

**Comment by hannahmahon** [comment]
Hi @zhouyx ,  has this been deployed?

**Comment by zhouyx** [comment]
Hi @hannahmahon, not yet. 
You can track the deployment in #29171
