### ISSUE TITLE
I2I: Allow referrerpolicy on amp-img

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#29016]
## Summary

`<amp-img>` has internally supported the `referrerpolicy` attribute for quite a while, forwarding it to the `<img>` tag when it's created. However, we've never allowed the publisher to specify this. `referrerpolicy` allows you to specify how much referrer information to share with external resources. Every value (except `unsafe-url`) actually reduces the amount of info shared.

We could disallow `unsafe-url`. When navigating from `https` to `http`, usually no referrer info is sent. But `unsafe-url` overrides this, letting the full referrer info be sent. I don't think this is really required, though.

## Design document

This is a simple validator change. Runtime already handles this.

## Motivation

- Allowing publishers to leak _less_ user information is a good thing.

/cc @ampproject/wg-approvers

**Comment by cramforce** [comment]
I think this is probably just an oversight.

**Comment by jridgewell** [comment]
I think so, too. Can I get an explicit approval, though?

**Comment by dvoytenko** [comment]
Not sure how much this is related, but for context, `referrerpolicy` also seems to have landed in Safari 14 Beta (https://bugs.webkit.org/show_bug.cgi?id=213285). Is this already enabled on validator?

**Comment by cramforce** [comment]
Approved

**Comment by jridgewell** [comment]
> referrerpolicy also seems to have landed in Safari 14 Beta

This appears to be for `<script>`s, it's been enabled in safari on every other element. We could enable it for `<script>`, but we rely on the referrer to do random build diversion on Origin pages.

**Comment by Gregable** [comment]
Approved 2

I don't think we need to restrict the value. @ampproject/wg-amp4email may prefer a slightly different rule however.

**Comment by choumx** [comment]
Would this impact images that have their `src` rewritten? E.g. in AMP cache or in an email provider.

**Comment by jridgewell** [comment]
> Would this impact images that have their src rewritten?

Yes, the would receive less referrer information. I think that's fine.

**Comment by choumx** [comment]
Yea, I think so too. LGTM.

**Comment by jridgewell** [comment]
👍, given the 3 approvals, I'll merge the PR.

**Comment by kristoferbaxter** [comment]
Apologies for delay, approved here as well.
