### ISSUE TITLE
Amp-Analytics onscroll vertical boundaries not respected

### ISSUE THREAD

**Issue by hannahmahon** [ampproject/amphtml#29026]
## What's the issue?
The `verticalBoundaries` of a scroll trigger are not being respected -- events are firing before they are supposed to.

## How do we reproduce the issue?
My code:
```
{
   "vars":{
      "account":"UA-XXXXXXX-1"
   },
   "triggers":{
      "scrollStart":{
         "on":"scroll",
         "request":"event",
         "scrollSpec":{
            "verticalBoundaries":[
               20
            ]
         },
         "vars":{
            "eventCategory":"onpage-scroll ${verticalScrollBoundary}%",
            "eventAction":"total page height: ${scrollHeight}",
            "eventLabel":"current scrolltop: ${scrollTop}"
         }
      }
   }
}
```
What I see in my network:
![image](https://user-images.githubusercontent.com/15826427/85618354-aae35f00-b62e-11ea-983c-48e476c1c872.png)
It should fire when the scrollTop position is at 20% of the total scrollHeight, but instead fires at a scrollTop position of 0 (and thinks that it's at 20%). 

## What browsers are affected?
At least chrome

## Which AMP version is affected?
2006112352001

**Comment by micajuine-ho** [comment]
Hi @hannahmahon could you please provide a webpage that exemplifies this behavior?

**Comment by hannahmahon** [comment]
@micajuine-ho unfortunately the issue was discovered in testing on a dev environment and never made it to a public/prod site. I did check again this morning and saw the same behavior, is there a sandbox your team has that I can paste my config code into?

**Comment by micajuine-ho** [comment]
Could you create test html file and share it here or a jsbin that shows this behavior?

**Comment by hannahmahon** [comment]
Working on it, but unless I'm missing something it seems like the amp-analytics playground linked from the official documentation doesn't fire any events in the network: (linked from button on [this page](https://amp.dev/documentation/examples/components/amp-analytics/index.html?format=websites))
https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-analytics

Here's my attempt which also doesn't fire anything for `page visible` or otherwise
https://jsbin.com/sofejuxoco/edit?html,console,output

Let me know if this is enough to go on, or whatever else I can do to help

**Comment by micajuine-ho** [comment]
> Working on it, but unless I'm missing something it seems like the amp-analytics playground linked from the official documentation doesn't fire any events in the network

This playground page has been broken for a while (but not due to amp-analytics).

> Here's my attempt which also doesn't fire anything for `page visible` or otherwise
> https://jsbin.com/sofejuxoco/edit?html,console,output

If you check the network tab, you can see that the correct requests get sent out. 

I reccomend for testing that you omit the `type="googleanalytics"` and use manual config to easily see the requests sent out:
```
<amp-analytics>
      <script type="application/json">
        {
            "requests": {
              "endpoint": "https://fake.com/pageview",
              "scroll": "https://fake.com/scroll?vsb=${vsb}&sh=${sh}&sc=${sc}"
            },
            "triggers": {
                "pageview": {
                    "on": "visible",
                    "request": "endpoint"
                },
                "scroll": {
                    "on": "scroll",
                    "request": "event",
                    "scrollSpec":{
                      "verticalBoundaries":[
                         25, 50, 75, 100
                      ]
                   },
                   "vars":{
                      "vsb":"onpage-scroll ${verticalScrollBoundary}%",
                      "sh":"total page height: ${scrollHeight}",
                      "sc":"current scrolltop: ${scrollTop}"
                   }
                }
            },
            "transport": {
              "beacon": false,
              "xhrpost": false,
              "image": true
            }
          }
      </script>
    </amp-analytics>
```

With this setup on your test page, I see that the scroll requests get sent out correctly. Can you double check this?

**Comment by hannahmahon** [comment]
Thanks for the help re: omitting google analytics; now I'm seeing the original issue. When my verticalBoundaries is just an array of 1 interval, it fires on page load

https://jsbin.com/jucucuseso/edit?html,console,output

**Comment by micajuine-ho** [comment]
In this example, your vertical boundary is 20. 
![image](https://user-images.githubusercontent.com/30711678/87081078-9336d980-c1dd-11ea-9b79-39c2c612c440.png)

In this image, the device height is 812, and the calculated scrollHeight of the page is 3338. On page load, the page is shown from the top, so amp-analytics calculates the amount of the page seen to be 812/3338 = ~24% which is greater than the 20% boundary, and thus sends out the request.

This is in contrast to when I test with a smaller device, with a height of 667. The same calculation applies, except that the percent visible on the screen is ~19% and thus the vertical boundary isn't triggered.

![image](https://user-images.githubusercontent.com/30711678/87081371-1f490100-c1de-11ea-9266-a04fd43e795a.png)

Is there something that I'm missing here?

**Comment by hannahmahon** [comment]
Ah, I didn't realize that it would start the scroll height at the device viewport height instead of 0. Thanks so much for explaining, we should be all set here!
