### ISSUE TITLE
Post message from amp-ad to parent window

### ISSUE THREAD

**Issue by stefee** [ampproject/amphtml#29022]
## Describe the new feature or change to an existing feature you'd like to see

We would like to be able to call `window.parent.postMessage` from within an `amp-ad` frame to fire a `message` event in the main window.

The [AMP docs show](https://amp.dev/documentation/components/amp-iframe/) an example of doing this with `amp-iframe` (but not `amp-ad`):

> Note: In the following examples, we assume the script is in the created iframe, where window.parent is the top window. If the script lives in a nested iframe, change window.parent to the top AMP window.
> 
> Example: iframe send-intersections request
> ```js
> window.parent.postMessage(
>   {
>     sentinel: 'amp',
>     type: 'send-intersections',
>   },
>   '*'
> );
> ```

## Additional context

Here's a snippet from the docs for our own ad library called Fuel, which describes our approach to displaying native ads using React:

>Some advertising formats, such as native advertising, require the ad to fit into the look and feel of the page.
> 
> Google Ad Manager has a concept called creative templates, where you can define an HTML template with variables (a bit like handlebars) and provide the JS and CSS that goes with it. While this does work, it becomes difficult to maintain with the frequent changes to styling made to a website. The templates are also stored per site, which in our case means the changes would need to be done tens of times.
> 
> To work around this, we use a technique first [described by Bunte](https://medium.com/@funkymusic/how-to-run-fully-responsive-doubleclick-native-ads-without-iframes-994affce9007). We create a template with the variables for the native advertisement, but we render no html at all. Instead, we take the variable and put them into a postMessage back to fuel. Fuel will then in turn expose these variables as render props in the NativeAd React component, which lets the consuming application do whatever it wants with them, such as rendering a component.
> 
> This has the nice effect of allowing any React component to be turned into an ad.

We would like to do native ads on AMP in a similar way, but rather than running React on the client, we would do a partial render of the ad component on the server to get the HTML and CSS into the AMP-HTML doc (the native ad component sans content) and then execute a simple `amp-script` on the client which listens for the `message` event from the `amp-ad` and inserts the ad contents into the native ad DOM.

Related to https://github.com/ampproject/worker-dom/issues/747 and https://github.com/ampproject/worker-dom/issues/865.

## Describe alternatives you've considered

We have considered changing our native ads architecture. Note however that this would mean changing how we serve native ads on the web in general as well as on AMP pages. This alternative approach would involve essentially copy/pasting our HTML and CSS into AdManager for each brand and market that is served by our multi-tenant web application, or finding a way to automate this in CI so that the creatives in AdManager all stay in sync with our various brand identities. This would be tricky since we use React styled-components for our presentation components, pulling out the relevant styles into a stylesheet to upload to AdManager would be tricky and probably quite error-prone, and it adds a new build step to our pipeline which needs to be maintained.

We have also considered trying to use `amp-iframe` for the purpose of serving native ads, but this doesn't seem technically feasible or in line with AMP best practices.

**Comment by lannka** [comment]
@stefee sorry for the delayed response. 

The I2I isn't very clear to me what such a postMessage is for, who will be listening to such a postMessage, and what is the desired action to take upon that?

Technically, you can already postMessage in your ad iframe to parent, I guess what you really want is a listener of such a postMessage in AMP?

**Comment by stefee** [comment]
Thanks @lannka. I’ll do my best to clarify this. 

> who will be listening to such a postMessage

A script (`<amp-script>` ?) in `window.top.document` would register a “message” event listener (`window.addEventListener(“message”, handler)`) and act on the contents of the message posted from ad frame. This script would be included in the server-side rendered amphtml document. 

My understanding currently is posting messages like this from within an `<amp-ad>` is not supported but correct me if I’m wrong?

> what is the desired action 

To update/hydrate the DOM with the ad creative data (image src, title, advertiser name) posted from the ad frame. The DOM structure and styles would be pre-rendered on the server, but the ad “content” would come from Google Ad Manager. 

> Technically, you can already postMessage in your ad iframe to parent

We were led to believe this was not possible. If this is the case then that is good news for us, we might have to give it a try and find out.

**Comment by lannka** [comment]
For your use case, have you looked at our template ad solution: https://github.com/ampproject/amphtml/blob/master/ads/custom.md

1) it does not render ad in an iframe (to provide a native feel).
2) It requires a mustache template on your page
3) it fetches data from your server to hydrate your template

**Comment by stefee** [comment]
This might be what we’re looking for. I’ll get back to you on this! Thanks.

**Comment by stefee** [comment]
Looking at this doc, I’m not sure this will work with Google Ad Manager, since the response from GAM server will not be in this format.

> ```
> {
>   "1": {
>     "src": "https://my-ad-server.com/my-advertisement.gif",
>     "href": "https://bachtrack.com",
>     "info": "Info1"
>   },
>   "2": {
>     "src": "data:image/gif;base64,R0lGODlhyAAiALM...DfD0QAADs=",
>     "href": "http://onestoparts.com",
>     "info": "Info2"
>   }
> }
> ```

Am I correct @lannka?

**Comment by lannka** [comment]
it does require a specific format from the ad server. I'm not familiar with what GAM returns.

are you able to proxy the GAM request and convert the response to the desired format?

**Comment by stefee** [comment]
Sorry it took me a couple of days to get back to you @lannka. We wanted to spend some time checking some of our original assumptions around how amp-script works. On reflection, my original feature request is not technically feasible. This is because amp-script does not have access to the window object since it is executed within a worker thread. As you said in [your previous message](https://github.com/ampproject/amphtml/issues/29022#issuecomment-662613646), it is already possible to execute a `postMessage` from within an ad iframe, but there is no way of receiving the message event in the main window.

Your suggestion of using the templating language provided by `type="custom"` ads is a lot closer to something that would work for our use case.

There are a couple of reasons why this ad type isn't ideal for use with Google Ad Manager:
1. Currently, the officially supported way to form Google Ad Manager requests is using [Google Publisher Tag](https://developers.google.com/doubleclick-gpt/guides/get-started). It's not possible to run Google Publisher Tag in an amp-script because it's an end-to-end solution which needs unrestricted access to the window object, and amp-script runs on a separate worker thread which cannot access the window.
2. The ad server response from Google Ad Manager is conventionally an HTML response as opposed to a JSON response. See [API reference here for `htmlSnippet` on `CustomCreative`](https://developers.google.com/ad-manager/api/reference/v202005/CreativeService.CustomCreative#htmlsnippet). While I don't see a technical reason why we couldn't put a JSON string in the payload, this wouldn't be in line with Google Ad Manager conventions.

It is worth noting that AMP does have it's own solution for forming Google Ad Manager requests which does not use Google Publisher Tag. The source code for this can be found [here](https://github.com/ampproject/amphtml/blob/fb1ff2f7f100585a89de6f894b6113bbeafbc256/ads/google/a4a/utils.js#L351-L382) and there is more information about AMP's Google Ad Manager implementation [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad-network-doubleclick-impl/amp-ad-network-doubleclick-impl-internal.md). Since the code here is not published as a package, we can't use it in our own amp-script. However, it might be possible for the AMP team to implement a templating language, similar to the [custom ad type](https://github.com/ampproject/amphtml/blob/master/ads/custom.md), into the Google Ad Manager component. Let me know your thoughts on this idea.

Note that implementing templating into the GAM/doubleclick ad component doesn't resolve my second point about JSON payload being an unconventional response from Google Ad Manager point of view, but this might not be a problem if we are willing to break convention.

**Comment by lannka** [comment]
Unfortunately this is one of the features that amp-doubleclick does not support. And I don't see a way or a reason for AMP to work around that without a official support.

**Comment by stefee** [comment]
Thanks for the update @lannka.

CC @danhaller

**Comment by pkolenic** [comment]
@lannka to follow up on this.
Should **amp-ad** be able to handle
```
window.parent.postMessage(
  {
    sentinel: 'amp',
    type: 'send-intersections',
  },
  '*'
);
```
The same way as **amp-iframe**?

My team currently has it working within an **amp-iframe**, but we are wanting to move towards using **amp-ad** to give our ads a more native feel and reduce the html snippet size that a publisher needs to include on their templates.

Our listener is setup as
```
// Listen for Intersection data from Parent Window
window.addEventListener('message', (event) => {
  if (
    event.source !== window.parent
    || event.origin === window.location.origin
    || !event.data
    || event.data.sentinel !== 'amp'
    || event.data.type !== 'intersection'
  ) {
    return;
  }
  event.data.changes.forEach((change) => {
    const inViewport = change.intersectionRatio > 0.15;
    /* CUSTOM LOGIC */
  });
});
```
However when testing on a local gulp server I'm not receiving any **intersection** messages for the **amp-ad**
