### ISSUE TITLE
amp-script: classList.add/remove broken (class="[object Set]")

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#29037]
Reported on Slack:

> I believe the worker-dom implementation of classList (classList.add, classList.remove) was recently broken. I have several amp-scripts on bringfido.com which are showing class=“[object Set]" for any classes that were manipulated using classList.

@kristoferbaxter was able to repro on AMP playground.

**Comment by kristoferbaxter** [comment]
I was able to create a reproduction directly with WorkerDOM using the ES5 implementation. This appears to be a bug related to babel.
