### ISSUE TITLE
Broken link on amp.dev/support/faq/overview/

### ISSUE THREAD

**Issue by randzman** [ampproject/amphtml#29034]
**FAQ ... Who page link is 404.... 
"The project is open to all players in the ecosystem - publishers, consumer platforms, advertisers and creators. To get an idea who some of the companies and sites are who use AMP, head to the Who page."**

**Comment by Ichigo3d** [comment]
Hello @randzman. Thank you for participate in improve of our project. I checked it and it's reproducible. 
https://amp.dev/support/faq/overview/
<img width="772" alt="Screen Shot 2020-06-25 at 8 55 43 AM" src="https://user-images.githubusercontent.com/37351864/85754526-fa269f80-b6c1-11ea-8321-03522db544fd.png">
<img width="878" alt="Screen Shot 2020-06-25 at 8 55 51 AM" src="https://user-images.githubusercontent.com/37351864/85754536-fc88f980-b6c1-11ea-8d05-b7b3e4e7bd2a.png">

**Comment by Ichigo3d** [comment]
cc @patrickkettner
