### ISSUE TITLE
AMP multiple video auto-playing issue

### ISSUE THREAD

**Issue by ngurav** [ampproject/amphtml#29035]
I have multiple videos in an HTML, I have added attributes 'controls' 'autoplay'  'loop' in my code, but after refreshing the page first video in the list is not auto-playing and other videos are auto-playing properly.

I need a solution for this can anyone help me asap

![image](https://user-images.githubusercontent.com/33622063/85728337-71d1ea00-b715-11ea-9981-93a52173000f.png)

**Comment by Ichigo3d** [comment]
Hello @ngurav . Thank you for participate in improve of our product. I can't reproduce this bug. Could you share more information about the bug: AMP version, version of browser or browsers, and screenshots?

**Comment by wassgha** [comment]
Would be great if you could please provide a demo url for this.

**Comment by ngurav** [comment]
@wassgha Here you can find the bug

https://d11.s3.amazonaws.com/d11-static-pages/what-is-dream11-test.html

**Comment by wassgha** [comment]
@alanorozco to verify but this sounds to me like a bug in visibility of the first video, autoplaying seems to initialize correctly but does not trigger
