### ISSUE TITLE
Update amp-story-consent to not use legacy amp-consent config

### ISSUE THREAD

**Issue by micajuine-ho** [ampproject/amphtml#29046]
amp-story-consent is current using the legacy amp-consent config:
```
{
   "consents": {
      ...
   },
}
```

The current amp-consent [config](https://github.com/ampproject/amphtml/blob/master/extensions/amp-consent/amp-consent.md#consent-configuration) does not use a `consents` object, because it only supports 1 consent policy at a time. 

Upgrading this would make it less confusing for publishers.

https://github.com/ampproject/amphtml/blob/725595ac41082b0f9db3103143b04070b0fa7a9e/extensions/amp-story/1.0/amp-story-consent.js#L374-L396

/cc @zhouyx

**Comment by gmajoulet** [comment]
We're tracking this here: https://github.com/ampproject/amphtml/issues/27469
I'm raising the priority, thanks for filing this ticket!

**Comment by micajuine-ho** [comment]
@gmajoulet Thanks! Please let me know if you need any help with the consent stuff!

**Comment by gmajoulet** [comment]
Happy to help you with code pointers and code reviews if you have some bandwidth to take this on!

Here's how the Story specific component gets the `amp-consent` configuration:

https://github.com/ampproject/amphtml/blob/725595ac41082b0f9db3103143b04070b0fa7a9e/extensions/amp-story/1.0/amp-story-consent.js#L303-L368

**Comment by gmajoulet** [comment]
cc @ampproject/wg-stories

**Comment by micajuine-ho** [comment]
@gmajoulet Ya I can take this on :)
