### ISSUE TITLE
🌸 Cherry-pick request for #29037 into #2006112352001 (Approved)

### ISSUE THREAD

**Issue by kristoferbaxter** [ampproject/amphtml#29044]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #29037 | #29041 |     **YES**     | **YES** | **NO** | #28910 #29007                                                             |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

This issue causes documents using `amp-script` to incorrectly set the className of user-derived script driven components, falling into the category of **breaking existing AMP web pages in a significant way**.

# Mini-postmortem

1. WorkerDOM was upgraded from `0.24.0` to `0.25.0`
2. This regressed the ES5 transpiled output functionality used within AMP documents. 
3. To remedy this, we enabled 'strict' transpilation and released WorkerDOM `0.25.1`. This change increases the size of the binary, but gives higher confidence that transpiled code is executing as intended by the source.

**Following this issue**, we'll be adding additional testing into WorkerDOM to ensure releases do not regress in this manner.

## Summary

1. WorkerDOM was upgraded from `0.24.0` to `0.25.0`
2. This regressed the ES5 transpiled output functionality used within AMP documents. 
3. To remedy this, we enabled 'strict' transpilation and released WorkerDOM `0.25.1`. This change increases the size of the binary, but gives higher confidence that transpiled code is executing as intended by the source.

**Following this issue**, we'll be adding additional testing into WorkerDOM to ensure releases do not regress in this manner.

## Impact

- All AMP documents using `amp-script` were impacted.
- Partial loss of functionality, since other segments of AMP documents are unimpacted.

## Action Items

**Following this issue**, we'll be adding additional testing into WorkerDOM to ensure releases do not regress in this manner.

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by cramforce** [comment]
Approved for Beta/Stable. I'd like us to confirm whether LTS partners are impacted before cherry-picking into it.

**Comment by kristoferbaxter** [comment]
Confirming LTS code contains the issue: https://cdn.ampproject.org/rtv/012006112352001/v0/amp-script-worker-0.1.js

## LTS Output
```javascript
(n.add = function () {
  for (
    var t, e = this.value, n = arguments.length, r = Array(n), i = 0;
    i < n;
    i++
  )
    r[i] = arguments[i];
  (t = this[43]).splice.apply(
    t,
    [0, this[43].length].concat(new Set(this[43].concat(r)))
  ),
    this[67](e, this.value);
}),
```

## Known Broken Output
```javascript
(n.add = function () {
  for (
    var t, e = this.value, n = arguments.length, r = Array(n), i = 0;
    i < n;
    i++
  )
    r[i] = arguments[i];
  (t = this[43]).splice.apply(
    t,
    [0, this[43].length].concat(new Set(this[43].concat(r)))
  ),
    this[67](e, this.value);
}),
```

## Known Working Output
```javascript
{
  key: "add",
  value: function () {
    for (
      var e,
        t = this.value,
        n = arguments.length,
        r = Array(n),
        i = 0;
        i < n;
        i++
    )
      r[i] = arguments[i];
      (e = this[43]).splice.apply(
         e,
         [0, this[43].length].concat(d(new Set(this[43].concat(r))))
      ),
      this[67](t, this.value);
   },
},
```

**Comment by cramforce** [comment]
Are there known LTS customers who are impacted by this?

**Comment by kristoferbaxter** [comment]
Just asked @nainar offline, will report back.

**Comment by cramforce** [comment]
How old is the current LTS?

**Comment by kristoferbaxter** [comment]
Looks like May 15th. https://cdn.ampproject.org/lts/experiments.html

@rsimha can you confirm?

**Comment by rsimha** [comment]
Can confirm @kristoferbaxter is correct. In https://cdn.ampproject.org/lts/v0.js, I see `"v":"012005152259000"`, which means today's LTS channel is the same as the stable channel release (`01`) that was cut on May 15, 2020 (`200515`) at 10:59 PM UTC (`2259`), and contains zero cherry-picks (`000`).

**Comment by cramforce** [comment]
Since we don't appear to have reports from LTS customers I'd prefer not to change it.

When it the next LTS going into prod? We should make sure it has the fix.

**Comment by kristoferbaxter** [comment]
Sounds good to me, I'll modify the Cherry pick request.
