### ISSUE TITLE
Please add validateString parameters to the docs.

### ISSUE THREAD

**Issue by jrtderonde** [ampproject/amphtml#29076]
**This only complies to the validator documentation.**

## Describe the new feature or change to an existing feature you'd like to see
It would be nice if you could add the different parameters for the `validateString()` function. Trial and error thought me that setting the second parameter to `AMP4EMAIL` would now validate my input as AMP4EMAIL (as I was looking for).

**Comment by Gregable** [comment]
@jrtderonde , just so we know where you are looking for documentation. I assume you mean add something here: https://www.npmjs.com/package/amphtml-validator describing the extra fields. Do you have suggestions for other places that you found documentation that should be updated?

**Comment by Gregable** [comment]
@honeybadgerdontcare 
Let's go ahead and update the npm doc to describe this usage, then close out this issue.
