### ISSUE TITLE
Custom elements not loaded due to Firefox CORS bug

### ISSUE THREAD

**Issue by marcusclip** [ampproject/amphtml#29073]
## What's the issue?

Not strictly an AMP bug, but a result of a bug in Firefox blocking scripts due to a CORS bug.

See: https://bugzilla.mozilla.org/show_bug.cgi?id=1559795

Due to this bug loading custom elements with crossorigin="anonymous" fails and therefore those custom elements are not available in Firefox. Since using crossorigin there is only for the purpose of getting more detailed error reports maybe this should be disabled for Firefox or maybe only enabled when in debug mode.

Fixing this in AMP would be a much quicker solution than waiting for a fixed Firefox to propagate to all end users.

The crossorigin is set here:

https://github.com/ampproject/amphtml/blob/46def58d2d78f0f5058369832af9636cd7e85b22/src/service/extensions-impl.js#L594

## How do we reproduce the issue?

I encountered this with an AMP ad loaded with the the "doubleclick" network. The ad ended up not functioning in Firefox due to this issue (also IOS Chrome).

Due to not being able to request a specific AMP ad with the <amp-ad> tag I cannot provide a test case.

## What browsers are affected?

Firefox 68, i.e. current Android version. See here: https://bugzilla.mozilla.org/show_bug.cgi?id=1559795

## Which AMP version is affected?

I'm guessing all.

**Comment by Ichigo3d** [comment]
cc @lannka
