### ISSUE TITLE
Story native sharing does not work

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#29080]
From https://www.gstatic.com/amphtml/stamp/qa/sharing.html:

> Sharing on an actual iOS/Android mobile phone should open the system sharing, showing the phone installed applications or most recent contacts

This does not happen.

Tested in AMP release `2006112352003` with a Pixel 2 running Android 10 and Chrome 83.0.4103.106

**Comment by gmajoulet** [comment]
Can you double check whether you loaded the HTTPS version? This doesn't work over HTTP.

**Comment by Ichigo3d** [comment]
Under 2006112352003 on Android real device. 
![IMG_7526](https://user-images.githubusercontent.com/37351864/86041855-2c563b00-b9fb-11ea-97ca-f20b2b4beee2.jpg)
Under 2006112352003 on mobile view Chrome MacOS
<img width="1249" alt="Screen Shot 2020-06-29 at 11 26 53 AM" src="https://user-images.githubusercontent.com/37351864/86042178-a090de80-b9fb-11ea-9430-cdf075144bff.png">

**Comment by newmuis** [comment]
Wow, ok yep, that was it!

Leaving this open to track documenting that HTTP vs. HTTPS difference in the instructions (which I will do).
