### ISSUE TITLE
The Share function doesn't work in the top stories viewer in Google.com in Chrome and FFox MacOS 

### ISSUE THREAD

**Issue by Ichigo3d** [ampproject/amphtml#29082]
## What's the issue?

The Share function doesn't work in the top stories viewer in Google.com in Chrome and FFox MacOS  and in console error appears: TypeError: window.navigator.share is not a function

## How do we reproduce the issue?
1. go to google.com
2. send search request "new york"
3. open top stories article
4. click on the Share icon
5. Observe result

Actual result:
The Share function doesn't work in the top stories viewer in Google.com in Chrome and FFox MacOS 

Expected result: After click on the Share icon, menu with icon of social nets and messengers should appear on the bottom of the screen. 

## What browsers are affected?

Chrome and FFox MacOS

## Which AMP version is affected?

2006112352003
<img width="1267" alt="Screen Shot 2020-06-29 at 12 23 55 PM" src="https://user-images.githubusercontent.com/37351864/86048526-85c36780-ba05-11ea-8ae9-491b94f623ef.png">

**Comment by Ichigo3d** [comment]
cc @alanorozco

**Comment by ericfs** [comment]
@ampproject/wg-viewers

**Comment by ericfs** [comment]
Filed internal issue: b/160255073

**Comment by ericfs** [comment]
To clarify this is *Mac* OS not *iOS*?

**Comment by Ichigo3d** [comment]
It’s MacOS
