### ISSUE TITLE
amp-base-carousel go to slide 0 do not move carousel to slide 0

### ISSUE THREAD

**Issue by mauriciopiber** [ampproject/amphtml#29098]
## What's the issue?

Using amp-base-carousel, when try to use "on tap go to slide", index=0 not working at all. Tried using amp-selector and literal buttons. index=1 until 3 works great.
Tried a test using amp-carousel and go to slide 0 works fine.

## How do we reproduce the issue?

1. Enter https://output.jsbin.com/qupejadeza
2. Click slide 2 
3. Click slide 1 //wont work
4. Click slide 3 
5. Click slide 4
6. Click slide 1 //wont work

## What browsers are affected?

Found issue on chrome Version 83.0.4103.116 (Official Build) (64-bit)
Firefox 77.0.1 (64-bit)

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 2006112352003 http://localhost:3000/

Any help if it's really a bug or I’m doing something wrong will be appreciated.

**Comment by artneo7** [comment]
I'm using version **2007302351001** and **index=0** is still not working. It starts working from 1.
