### ISSUE TITLE
[amp-story] Joint latency in media performance metrics investigation

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#29105]
Joint latency is supposed to measure the initial buffering of a video (should measure as soon as the video bytes are being fetched from the server), but I'm seeing otherwise.

Doing a manual sanity check shows that `MediaPerformanceMetricsService.startMeasuring()` is called after the video bytes started loading in the network tab (best seen in slower connections).

Currently, we start measuring it after the `registerAllPromise` in amp-story-page, which I think is too late if we want to measure that initial buffering. 

https://github.com/ampproject/amphtml/blob/86d65c1d208117d24b5cd6c08f35deb001b697c3/extensions/amp-story/1.0/amp-story-page.js#L507-L515

/cc @ampproject/wg-stories

**Comment by gmajoulet** [comment]
Fixed by https://github.com/ampproject/amphtml/pull/29233

**Comment by gmajoulet** [comment]
Actually somehow it's not fixed, sorry about the spam
