### ISSUE TITLE
Story Player animation flash when repositioning prerendered stories

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#29117]
When the story player repositions an iframe from distance -2 to distance 1, this iframe flies across the player and is visible to users for a brief amount of time.

cc @ampproject/wg-stories

**Comment by processprocess** [comment]
I wonder how this could be reproduced. I think I see the issue but I'm not positive.

**Comment by Enriqe** [comment]
Actually I don't think I can repro anymore, either. I think we might have fixed it at some point recently?

**Comment by Enriqe** [comment]
Will close for now, will reopen if we see it again.

**Comment by gmajoulet** [comment]
To repro:

1. Add 5 stories to a player
2. Slow down animations to 25 or 10%
3. Navigate to the 4th or 5th Story (I don't really understand how they're repositioned), you'll see the Story that gets repositioned to the right fly over the visible content

**Comment by gmajoulet** [comment]
This might have been fixed with the latest refactoring.
