### ISSUE TITLE
Intent-to-Deprecate-and-Remove: SimpleReach

### ISSUE THREAD

**Issue by devdazed** [ampproject/amphtml#29111]
## Summary

In March of 2019 Nativo Inc acquired SimpleReach.  As of today Nativo has fully sunset the SimpleReach product.  Any requests to the SimpleReach servers will fail.

## Motivation

SimpleReach no longer exists as a product.

## Impact on existing users

AMP installations using the SimpleReach integration will begin to error when making requests to the SimpleReach servers.  The removal will prevent this.

## Alternative implementation suggestion for developers using AMP

None

## Additional context

SimpleReach vendor configuration location: https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/vendors/simplereach.json

/cc @ampproject/wg-approvers

**Comment by micajuine-ho** [comment]
Hi @devdazed, is there an alternative analytics solution for the previous `simplereach` customers?

**Comment by alanorozco** [comment]
@micajuine-ho It's my understanding that this product is not offered anymore. We can go ahead with removal.
