### ISSUE TITLE
AMP4Email: CSS to mimic a password field

### ISSUE THREAD

**Issue by suchitagarwal** [ampproject/amphtml#29110]
## What's the issue?

Gmail for AMP playground supports adding a 

```css
-webkit-text-security: disc;
```

style to an input field and mimic a password field.

When that same email is sent to a gmail address, the password field is unmasked.

## How do we reproduce the issue?

1. Go to https://amp.gmail.dev/playground/
2. Create an email with the following html:

```html
<!--
     Below is the mininum valid AMP4EMAIL document. Just type away
     here and the AMP Validator will re-check your document on the fly.
-->
<!doctype html>
<html ⚡4email>
<head>
  <meta charset="utf-8">
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <style amp4email-boilerplate>body{visibility:hidden}</style>
  <style amp-custom>
    .password-input {
      -webkit-text-security: disc;
    }
  </style>
  </head>
<body>
  Hello, AMP4EMAIL world.
  <input type="text" class="password-input">
</body>
</html>
```

3. Type a password in the password field and notice that it is masked:

![Screen Shot 2020-07-01 at 2 32 41 PM](https://user-images.githubusercontent.com/773077/86279288-c529b980-bba7-11ea-929b-ac17ccf47b98.png)

4. Send the email to the current logged in account, type a password in the password field and notice that it is not masked:

![Screen Shot 2020-07-01 at 2 35 45 PM](https://user-images.githubusercontent.com/773077/86279569-36696c80-bba8-11ea-8ed9-2b1dd8ad937c.png)

## What browsers are affected?

All browsers, all devices

**Comment by caroqliu** [comment]
Hi @suchitagarwal thanks for filing this issue! Unfortunately `-webkit-text-security` is not one of our [supported CSS properties](https://amp.dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-css/#supported-css-properties).

**Comment by suchitagarwal** [comment]
Hi @caroqliu thanks for your response, appreciate it. Is there any other way to mask input fields in amp4email right now?

**Comment by suchitagarwal** [comment]
bump

**Comment by caroqliu** [comment]
Inputs with `type=password` have historically been disallowed in email due to phishing concerns, along with any workarounds that may convey a similar user flow. There is some discussion of this in #26364, so I am going to dedup this thread with that one for now. Please feel free to chime in in that discussion to describe your use case if this is a desired feature.

**Comment by suchitagarwal** [comment]
Thanks a lot Caroline. I will go through the discussion in the other thread and comment as appropriate
