### ISSUE TITLE
I2I: New supported type alright for amp-auto-ads

### ISSUE THREAD

**Issue by liquidlx** [ampproject/amphtml#29129]
## Summary

We would like to add support for alright network on amp-auto-ads, so our publishers can easily activate and monetize their AMP version.

## Design

```
<amp-auto-ads
   type="alright"
   data-publisher-id="123456"
   data-page-type="home"
   data-content-category="sports">
</amp-auto-ads>
```

data-page-type and data-content-category are optional.
## Motivation

A lot of our publishers have a version of their sites in amp, but they don't know how to implement ads on it. We want to make it as simple as possible. We have a platform that has all of our publishers' configurations for their ads (positioning, targeting, etc), so we want to provide a simple line of code (amp-auto-ads with type 'alright') that consume our API with this configuration.

## Additional context

We want to add an extension for amp-auto-ads tag that will allow a new type "alright", where the ads json will be provided by our API.

**Comment by AbhiramReddyD** [comment]
So, are we gonna just add the ad publisher id as we did for analytics? That'll be very useful indeed
