### ISSUE TITLE
Web Stories: Error in automated structured data

### ISSUE THREAD

**Issue by Jleesley** [ampproject/amphtml#29144]
I created two "Google Web Stories, one was pre-designed (template) and one was from complete scratch. Ironicly enough, both have the "Error in required structured data element," just like it's said the last several years whenever you try and build an AMP page. This renders the software useless. It's an AMP-building plugin. Question: Google didn't write the code for even their own templates in the plugin? 

Do you know that when you download a regular WordPress plugin, you won't have to write code to it? That's the **reason** plugins exist — so you don't have to write code. 

JL
PS: I tried to add structured data to one of the web stories I made on the Google's structured data testing [website](https://search.google.com/structured-data/testing-tool/u/0/), but the page freezes; you can't scroll down.

**Comment by choumx** [comment]
What tool were you using to create the web story? If it's the (beta) of "Web Stories by Google", you should file an issue here: https://github.com/google/web-stories-wp/

**Comment by choumx** [comment]
Can you also share the story HTML with the structured data?
