### ISSUE TITLE
How to make undock for video when I scrolled to amp-next-page?

### ISSUE THREAD

**Issue by NikitaCG** [ampproject/amphtml#29146]
I use amp-video-iframe for the video. I made a custom dock-slot and want to remove it when I scroll to the next material on the page, which is made using amp-next-page. I tried adding an amp-position-observer to the end of the main material, but the dock doesn't respond to the observer because it doesn't do anything by itself.

**Comment by caroqliu** [comment]
Thanks for filing this issue! Can you provide a minimal code sample for us to try and reproduce? cc @alanorozco @wassgha

**Comment by NikitaCG** [comment]
hi, here are the pieces of code I'm working with for this case.
`<amp-video-iframe
          id="video-iframe"
          width="400"
          height="240"
          layout="responsive"
          src="url"
          poster="url"
          dock="#dock-slot"
        >
 </amp-video-iframe>
<amp-layout
        layout="responsive"
        width="16"
        height="9"
        on="undock: " // what command should I write to remove the dock when I scroll to #video-stop-ref ?)
        id="dock-slot">
</amp-layout>

//
// content
//

// it is to stop video, when i scroll to end of main content
<amp-layout>
      <amp-position-observer
        id="video-stop-ref"
        intersection-ratios="1"
        layout="nodisplay"
        on="enter: video-iframe.pause"
      >
      </amp-position-observer>
</amp-layout>

<amp-next-page deep-parsing="false">
      <script type="application/json">
         {
          ......
         }
      </script>
</amp-next-page>
`
I can't throw off the code of the entire page because there is a lot of it, and it has little to do with this case
