### ISSUE TITLE
Add instructions to renovate PRs requiring manual adjustments

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#29169]
Sample: https://github.com/ampproject/amphtml/pull/29147

Sometimes renovate PRs require associated updates, such as when a change to a linting dependency demands new lint fixes. We should include instructions for how to check out and update a renovate PR within the PR description, to make it easier for  reviewer to make the necessary updates.

/cc @rsimha

**Comment by rcebulko** [comment]
Closed 
![image](https://user-images.githubusercontent.com/6694512/87805668-b851ca80-c823-11ea-9cce-e306d87541fc.png)

**Comment by rcebulko** [comment]
Correction: it's enabled for linting PRs right now. Were you thinking we include this on all PRs @rsimha ?

**Comment by rsimha** [comment]
> Were you thinking we include this on all PRs?

Thanks for enabling this for lint PRs. Yes, I did mean for the message to be a part of all renovate PRs, since any of them can potentially introduce a breaking change.
