### ISSUE TITLE
Expose JS API for amp-story-player

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#29164]
Let's expose a JS API for the AMP Story Player. Some desirable features:

- Callback or custom event emitted when displayed story changes with information about the new story.
- Forwarding of story-related `amp-analytics` events as custom events on the player side.
- Programmatic API to add Stories to the set
- Programmatic API to change the displayed Story

Related FR: provide a way to set the initially displayed story out of the set of `<a>` child elements (So, one can have a constant set but have the player initially load the 3rd story instead of the first).

**Comment by Enriqe** [comment]
Duplicate of #28416. I'll port the outstanding items to that issue :)
