### ISSUE TITLE
add full version onto window.AMP_CONFIG (with prefix)

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#2917]
this makes it so we dont have to look at the main binary script file src to get the full version.

Related to https://github.com/ampproject/amphtml/issues/2874

**Comment by ericlindley-g** [comment]
Slotting in backlog for now, but let me know (or feel free to update) if you have a more specific target

**Comment by erwinmombay** [comment]
this is completed. (internal change to release process)
