### ISSUE TITLE
[amp-story] Tweet creates vertical gap

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#29194]
1. Add `<amp-twitter>` on an `<amp-story-grid-layer>` with `template="vertical"`
2. Add an element on top/bottom of the tweet
3. A gap is visible between the tweet and the surrounding content.

We should introduce negative vertical margin to make up for the height increase in the scale.

/cc @ampproject/wg-stories

**Comment by cramforce** [comment]
Thanks for filing!
