### ISSUE TITLE
[Paid] How to add AMP support in Discourse forum topics?

### ISSUE THREAD

**Issue by FaizanZahid** [ampproject/amphtml#29200]
I love open source and i appreciate the work done by all contributors out there. i am using https://meta.discourse.org/ as an open source forum software for my community site. And some of the biggest banks, companies use Discourse as open source forum for their forums and communities. https://github.com/discourse/discourse

The only thing i am currently struggling with is, discourse doesn't have any plugin or support for automatic conversation of all its topics pages in to Google AMP.

I have requested a paid request for this by discourse team already, https://meta.discourse.org/t/paid-convert-discourse-topics-forum-to-google-amp-automatically/155244/4 but i didn't get any one so far.

I am checking here, if anyone here from the AMP community willing to take this project for me and convert my discourse forum on 100% compatible AMP pages, my sole purpose of doing this is to provide my users a great, faster UX and improve my search engines rankings.

I am happy to pay for this, if this is not the right place to post this, please suggest me where else can i post, or reach me on faizan.zad@gmail.com

Thanks in advance.

**Comment by choumx** [comment]
Thanks for filing this issue. Looks like this is an issue with Discourse not AMP so I'm afraid you'll have to keep following up with them.
