### ISSUE TITLE
amp-analytics chokes on CDATA

### ISSUE THREAD

**Issue by weeblr** [ampproject/amphtml#2920]
## Short description of your issue:

application/json script allowed inside amp-analytics (and am-social-share) breaks if the script json is wrapped with CDATA
## How do we reproduce the issue?

Add the following to an AMP page:

```
<amp-analytics type="googleanalytics" id="analytics269"><script type="application/json"><![CDATA[<![CDATA[
{
  "vars": {
    "account": "UA-12346-1"
  },
  "triggers": {
    "trackEvent" : {
      "on": "click",
      "selector": "#link269",
      "request": "event",
      "vars": {
        "eventCategory": "xxxx",
        "eventAction": "xxxxxxx",
        "eventLabel": "xxxxx"
      }
    }
  }
}
]]]]><![CDATA[>]]>
</script>
</amp-analytics>
```

The validator accepts the page content, as it should, but the AmpAnalytics code breaks with this error:
`Analytics config could not be parsed. Is it in a valid JSON format?" SyntaxError: Unexpected token < in JSON at position 0`

We have managed to removed the CDATA from the output, but it's a bit of a problem and a waste. PHP built-in DOM functions will output the CDATA automatically, as they are (mostly) required.

PS: the double CDATA in this sample doesn't influence the problem, amp-analytics reject that content with a single or a double CDATA

Rgds

**Comment by cramforce** [comment]
@Gregable 
I think we should make CDATA invalid. Just adds complexity, isn't needed and not in HTML5.

**Comment by Gregable** [comment]
Chatted with @cramforce in person. While not valid HTML5, we should still be able to support this in our runtime with a little bit of regex to strip the CDATA tags.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
