### ISSUE TITLE
`gulp presubmit` throws many errors locally

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#29206]
Running `gulp presubmit` locally I see many errors.
![image](https://user-images.githubusercontent.com/16087874/86973033-bfdce980-c128-11ea-89a5-f087ed9cf018.png)

Since many of these errors are from `build-system/tasks/performance/node_modules` so I tried excluding that here https://github.com/ampproject/amphtml/blob/aa6ed337476fce22d0f0437da4333fad60c433c9/build-system/test-configs/config.js#L103 but there were still many others. 

Everything passes on Travis, not sure if Travis is WAI or false negative.

**Comment by rsimha** [comment]
Ignoring that `node_modules` directory during presubmit checks is the way to go. Can you share the edits you made? Perhaps there's an error in the globs you used?

**Comment by calebcordry** [comment]
Sorry I don't think I was clear, adding `'!build-system/tasks/performance/node_modules/**/*.*'` does get rid of most of the errors, but there are still quite a few left and I gave up at that point :) Here are some more, but there are too many to capture.

![image](https://user-images.githubusercontent.com/16087874/86976562-94113200-c12f-11ea-987f-8c3fb0171530.png)

**Comment by rsimha** [comment]
Those look like they're coming from `build-system/tasks/performance/cache`. Did you ignore that directory too?

**Comment by calebcordry** [comment]
Good eye :) PR incoming.
