### ISSUE TITLE
Advancement animation is broken on player when coming back to a story with auto-advance

### ISSUE THREAD

**Issue by mszylkowski** [ampproject/amphtml#29245]
## What's the issue?

When you swipe to a different story and come back to it, the page advancement doesn't update the system layer "fill" animation at all, but after the specified time in the auto-advance, the story goes to the next page properly. This animation error happened with both auto advance after a video and a timer.

## How do we reproduce the issue?

Open a player with 2 stories, the first one needs auto-advance features.
While on an auto-advance page on the first story, scroll to the second page and come back
The system layer animation for the current page will stop filling up the current page progress
After the specified time, auto-advance will still work, and the system layer will start to work again properly.

## What browsers are affected?

Tested on Android Chrome, should affect all browsers.

**Comment by MaxBittker** [comment]
reproduced this!
