### ISSUE TITLE
I2I: new extension amp-viralize-player

### ISSUE THREAD

**Issue by biagimarco** [ampproject/amphtml#29243]
## Summary

We are [Viralize](https://viralize.com/), an Italian video company that has developed a custom video player. We'd like to include it as an extension of AMP so as to allow our customers to use it in their AMP websites.

Additional details about the player can be found [here](https://viralize.com/player/).

## Motivation

According to [AMP documentation](https://github.com/ampproject/amphtml/blob/master/contributing/building-an-amp-extension.md), a custom video player can be included in an AMP page implementing it as an extension.

## Additional context

In the following a screenshoot of how the player will look like:

<img width="307" alt="Screenshot 2020-07-13 at 16 11 34" src="https://user-images.githubusercontent.com/9765167/87314644-d5d11c80-c523-11ea-81ab-8dc7e9643dbe.png">

/cc @alanorozco @wassgha

**Comment by alanorozco** [comment]
@biagimarco Thank you for the I2I. Make sure you [read through the vendor video policy](https://github.com/ampproject/amphtml/blob/master/spec/amp-3p-video.md) and please include additional details:

1. How large is the user base for this component? An approximate count of domains?

2. Can this be an `<amp-video-iframe>` instead? You can provide a [document through your server](https://go.amp.dev/c/amp-video-iframe#vendors) that's easily configurable by authors without adding a new component.

**Comment by duilio** [comment]
Hi @alanorozco, please find here some 3rd party stats https://trends.builtwith.com/media/Viralize that I hope can provide you an unbiased answer. We do already have an adv tag in AMP, some publishers (ab)uses it also for the video player too and that is the main reason we are contributing with this extension.

We can probably fall back to `amp-video-iframe` with some more work but it doesn't look like this would be fair with our competitors (that already have the custom tag).

**Comment by duilio** [comment]
Hi @alanorozco are there any progress on this?

We have been trying to use `amp-video-iframe` as you have suggested in the meantime, unluckily we have spotted an issue that the other players are working around this way:

https://github.com/ampproject/amphtml/blob/438fd47f265f7aff4b116a9498d8b0d661a980bb/src/iframe-video.js#L143
