### ISSUE TITLE
I2I: Multi-bitrate support in amp-video

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#29254]
## Summary

Support videos sources of varying bitrates in amp-video and automatically pick the most appropriate one for the user.

## Design

Goals

- Works for videos too short to ever change the bitrate mid-flight.
- Works for modern codecs (HLS is limited to h264)
- Works on iOS (no support for modern adaptive-bitrate codecs).
- Works with a super simple web server (no fancy streaming infra)

### Design overview

- We're introducing a `multi-bitrate` attribute on `amp-video`
- If present `data-bitrate` on the child `<source>` elements is supported to pick an appropriate bitrate for the user.
- Pick the best bitrate based on `navigator.connection.effectiveType`
- Learn from playback what the best bitrate is for the user. Especially, if the above isn't available (iOS)

## Motivation

We feel this proposal is a simple compromise to get most of the benefit of a full-on MPEG-DASH/MediaSource API implementation while providing full iOS support and avoiding the complexity of MPEG-DASH encoding and serving. We hope the letter will lead to much bigger adoption in practice.

/cc @ampproject/wg-approvers

**Comment by kristoferbaxter** [comment]
What are the criteria for success?

**Comment by cramforce** [comment]
Higher percentage of videos play through with 0 or fewer-than-currently buffer interruptions.

**Comment by cramforce** [comment]
I guess also relevant: Manual testing shows that this works pretty well :)

**Comment by kristoferbaxter** [comment]
Are we tracking these metrics today in a way we can revisit once this has been completed?

My hunch is there are far more extensive things that could be done. I'd like to quantify the effort versus the result compared to this minimal viable approach.

**Comment by cramforce** [comment]
Please be concrete in what actually could be done; especially on iOS where adaptive bitrate streaming isn't supported.

We do have metrics on video performance for Stories displayed on Google, so we'll be able to validate this once it is out there.

**Comment by kristoferbaxter** [comment]
My understanding is HLS is natively supported by iOS Safari, though my work in this space is several years out of date at this point.

If true, you could use a combination of Dash (w/ MSE) and HLS to support most devices. This means you could combine all video for a story into a single adaptive stream and control playback per slide.

Once we see how well this approach works, it's worth looking at the effort and potential gain from a full adaptive streaming player. It might be worth the investment, and it also might not be.

**Comment by cramforce** [comment]
Yep, HLS is natively supported but works really badly. It was designed for desktop and hasn't been updated (e.g. fetching a video byte causes a 3-deep-HTTP cascade for manifests). E.g. YT isn't using it in their web client for this reason.

This change isn't meant to say we'd never ship real adaptive streaming for AMP, but I think that is a separate project; especially given that there are no off-the-shelf players that fit into our size ideas.

Whether to support backing multiple slides with a single video is a somewhat separate concern from this I2I. I think that is an interesting idea. I know @dvoytenko was looking at using seeking to implement trimming in videos. @gmajoulet Have you ever considered doing this? Technically this is supported today with [Media Fragments](https://caniuse.com/#feat=media-fragments)

**Comment by gmajoulet** [comment]
Yes that's a really good idea, @kristoferbaxter suggested that we do that from the client using MSE, constructing a longer single video from all the other ones. That'd allow us to completely remove the media pool, but doesn't solve the ABR issues that made us write our own implementation.
But if we could stitch all the videos of a Story together server side, then we could completely remove the media pool AND use DASH/HLS.

Like you said, it's a separate project and getting our own ABR implementation in in the meantime is a good first step before we tackle these harder solutions.

**Comment by gmajoulet** [comment]
cc @ampproject/wg-stories

**Comment by kristoferbaxter** [comment]
My comments are not intended to derail this current effort. Just ensuring we have good metrics to determine success and can iterate with other approaches if needed.

**Comment by gmajoulet** [comment]
Here's the metrics we're tracking as of today, only when served from Google platforms:

- watch time
- Error rate, grouped by error code
- percentage of videos served from the AMP cache
- joint latency at 50th, 75th, 95th, 99th percentiles
- rebuffer rate at 50th, 75th, 95th, 99th percentiles
- average number of rebuffers for first page video at 50th, 75th, 95th, 99th percentiles
- average number of rebuffers for non first page video at 50th, 75th, 95th, 99th percentiles
- average video bitrate played at 50th, 75th, 95th, 99th percentiles

**Comment by cramforce** [comment]
An initial change landed (but this obviously hasn't launched). Primary thing missing for MVP is to handle videos that never get into playing state.

**Comment by gmajoulet** [comment]
This has shipped some time ago. Experiments show strictly negative performance impact though, so we're tweaking it before announcing it, but publishers who opted-in the video cache `<amp-video cache="google"` automatically get this.
