### ISSUE TITLE
Shadow AMP don't call amp-analytics type krux

### ISSUE THREAD

**Issue by iwoak** [ampproject/amphtml#29257]
## Brief
Using amp-analytics we send an event to DMP Krux for each page view, that works fine on pure amp page, but it don't works on our PWA with AMP-VIEWER using shadow amp. 

## Reproduce

1. Visit this public page, a pure AMP: https://rep.repubblica.it/ws/detail/rubrica/la-prima-cosa-bella/2020/05/04/news/coronavirus_4_maggio-255554727/
2. You can see on network console a call to krux pixel with this url: https://beacon.krxd.net/pixel.gif
3. Now you can visit the same page, but through amp-viewer component using shadow amp at this url: https://rep.repubblica.it/pwa/rubrica/la-prima-cosa-bella/2020/05/04/news/coronavirus_4_maggio-255554727/
4. You can see as on network console there aren't any call about krux 

## Code

`<amp-analytics type="krux" data-consent-notification-id="amp-user-notification-privacy" config="https://cdn.krxd.net/controltag/amp/JW5KTbNq.json"><script type="application/json">{"extraUrlParams":{"page.pagetype":"dettaglio_content","page.wt_logged_service":"prm.repubblica.it","user.wt_logged_user":"AUTHDATA(data.profile.hash_id)","page.keywords":"Gabriele Romagnoli","page.pubday":"04","page.pubmonth":"05","page.pubyear":"2020","page.wt_map_tree":"\/repubblica\/rep","page.wt_mobile_type":"amp","page.wt_sitetype":"mobile","page.wt_map_tree1":"repubblica","page.wt_map_tree2":"rep","page.ADX_CAT_1":"NC","page.ADX_CAT_2":"NC","page.ADX_CAT_3":"NC","page.ADX_CAT_4":"NC"}}</script></amp-analytics>`

## What browsers are affected?
I think every browser are affected, but I verified just Chrome and Firefox

## Which AMP version is affected?
The last stable online versione

**Comment by gilbertococchi** [comment]
@nainar can we check this as part of the Shadow AMP related issues?

**Comment by gilbertococchi** [comment]
Hi @iwoak, I believe the issue is caused because of the amp-user-notification element missing on the Shadow DOM version.

I've tried with Charles Proxy to remove the amp-user-notification attribute and the krux ping triggers correctly.

**Comment by gilbertococchi** [comment]
Actually that's not so trivial as amp-viewer removes the amp-user-notification element but not the attributes.

@nainar @jeffjose  Can we check with someone why Amp-Analytics tags are not triggering if they have amp-user-notification attributes but the amp-user-notification tag has been removed by the AMP-Viewer rule?

<amp-viewer id="ampviewer" title="true" filtered-ids="bottom-header,detail-audio_trigger" filtered-tags="amp-user-notification">
