### ISSUE TITLE
🌸 Cherry-pick request for #29233 into #29171 (Approved)

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#29252]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #29233 | #29233 |     **YES**     | **NO** | **NO** | #29171                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

Four different 1p Story Players reported playback issues with stories having a video on their first page. There are various bugs, all fixed in the same Pull Request, ranging from the video failing to play entirely to the video being paused with no way to play it (except if navigating next then prev).

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by gmajoulet** [comment]
cc @choumx FYI

**Comment by cramforce** [comment]
It is late for a beta cherry-pick of such a complicated change. Approved only if we can do it now as I want to maximize bake time. Also, we would need to do additional manual testing of the release for video/stories related content.

**Comment by gmajoulet** [comment]
Sounds good.

@choumx does that work for you?

I've been testing with various stories and our QA documents, but can do more testing tomorrow morning with @Ichigo3d before we promote to production.

**Comment by choumx** [comment]
I'll get it started now.

**Comment by choumx** [comment]
Cherry-pick RTV: https://github.com/ampproject/amphtml/releases/tag/2007040248002
