### ISSUE TITLE
[stories] amp-video not playing in single page stories

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#29256]
## What's the issue?

We are seeing videos not playing in stories outside of the `amp-story-player`, where things seem to work correctly.

First investigations point to the issue being with single-page stories. Videos will not play when the story is shown by itself or is embedded in a regular iframe. 

Is this related to recent changes? (#29233)

## How do we reproduce the issue?

Single page story with video (BREAKS): https://amphtml.tappable.link/amp-video-bug?story
Single page story with video in amp-story-player (WORKS): https://amphtml.tappable.link/amp-video-bug

## What browsers are affected?

All tested browsers

## Which AMP version is affected?

The most recent

**Comment by gmajoulet** [comment]
https://github.com/ampproject/amphtml/pull/29233 should fix this issue, it's available on beta/experimental right now if you want to test it. It'll very likely be pushed to production later today (unless we find major issues, we're testing it very thoroughly right now).

(to opt-in: https://cdn.ampproject.org/experiments.html)

Feel free to re-open if you don't see it fixed. It appears to work with the examples you hosted! :))
