### ISSUE TITLE
[amp-story-player] storyend event

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#29279]
## User reached end of story
* Custom event: `storyEnd`

e.g.

```
player.addEventListener('storyEnd', () => {
  console.log('User is in the last page of the story');
})
```

/cc @ampproject/wg-stories

Tracker #28416

**Comment by gmajoulet** [comment]
As per our conversations on other tickets, publishers should use the `progress` on CURRENT_PAGE_ID events.
