### ISSUE TITLE
Make sure the story store service is not included in sub extensions bundles.

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#29282]
For story sub extensions, like auto-ads, education, 360, or interactive, we import `StateProperty` or `Action` from the store service. We need to make sure that the actual store class is not repeated in these bundles. This would not cause any bugs but would load unnecessary extra bytes.

We should also check: analytics-service, variables-service

cc @ampproject/wg-stories

**Comment by mszylkowski** [comment]
@gmajoulet So far have been able to refactor the LocalizedIds from the Interactive extension, removing 4kb from it (6%), will check what other improvements can be made and to other bundles as well

**Comment by gmajoulet** [comment]
Awesome! Can you link the PR here so we can track all these improvements?

**Comment by mszylkowski** [comment]
Have not seen much room for improvement in education or auto-ads. Can come back in the future to optimize further
