### ISSUE TITLE
URGENT : AMP Auto Complete Search not working while moving away Cursor Focus

### ISSUE THREAD

**Issue by sratnesh** [ampproject/amphtml#29284]
Hi , 

We are using amp auto complete to implement search functionality but as soon as we move away cursor the results are disappeared .

Use case : In search bar i have search string as "apple" and i get the results for apple 
Now  have not removed or cleared my search string but when i move cursor away from search bar the results will be cleared . 
But in search edit box we still have search string present 

We need urgent help and fix for this issue on priority 

Please find herein video for the same 
https://drive.google.com/file/d/1kW3TckuK0uOvTTOXXHaSoiXz6245rEUB/view?usp=sharing

Thanks
Ratnesh

**Comment by caroqliu** [comment]
Hello @sratnesh thank you for reaching out! One of the features for autocomplete is to only display results while focus is on the input field. It appears in this video that when the results "disappear" this is the intended consequence of clicking away from the input. It appears that focus is lost on the input, which can be assumed because the cursor (indicating focus) also disappears on the input.

**Comment by sratnesh** [comment]
Hi @caroqliu I understand your point but from user point of view user might move focus little bit here and there and as long as search string is present we should not clear out the results until searchpopup is closed.

In my case ( search popup) how i can have this ?

If user has not closed the search popup and user has not removed his search string then i want to retain search result how to achieve this ?

Thanks
Ratnesh

**Comment by caroqliu** [comment]
Yes absolutely. It looks like the user flow you are intending to achieve is: 
(1) Type into a search box
(2) Be able to select from suggested possible search queries
(3) See a list of search results
(4) Select from search results

amp-autocomplete is intended to do (2) but not necessarily (3) or (4) on its own -- it is a tool for making completing this user flow much quicker than if a user had to type a full query themselves. 

amp.dev serves as a helpful example for how to do this using amp-autocomplete in combination with a few other components, and they even [wrote a blog post about how they did it](https://blog.amp.dev/2020/02/14/in-search-of-the-amp-dev-search/). One piece to note here is that amp-autocomplete is only one part of the whole search experience, and they also use amp-list, amp-form, and amp-lightbox.

**Comment by caroqliu** [comment]
I'm going to close the issue. Feel free to re-open if you encounter any obstacles building this page.
