### ISSUE TITLE
[amp-story-player] Circular wrapping

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#29289]
We should open up the option for circular wrapping, meaning a user should be taken to the first story when they finish the last story in the player, and viceversa. 

/cc @ampproject/wg-stories

**Comment by newmuis** [comment]
@Enriqe can we change this API?  I think it would make sense that the API is "when I get to the end of my list of stories, the player should..."

- Loop back to the first story (circular wrapping)
- Fetch another story from some endpoint
- ....just end?
- etc

**Comment by Enriqe** [comment]
@newmuis yep that's a great idea. Maybe we should expose this as a method, so that if publishers want to end it at some point, they could call `setEndBehavior` or whatever with the desired option?

Options for parameters:

* `null` (default) - just ends
* `circularWrapping`
* `fetch`, and an accompanying parameter `url` to provide an endpoint where the stories would be fetched from.

**Comment by Enriqe** [comment]
Discussed offline with @gmajoulet  and we think using separate parameters for the circular wrapping and fetching from an endpoint is the best option. This will enable support for both features: fetching from endpoint when available, and circular wrapping when there are no more stories. This will also make the API simple and compatible with the AMP spec / validation. We can also expose a programmatic method so that publishers can use that if they wish to do so. 

Separately, I've also filed #29864 (fetch from endpoint) and #29865 (dispatch end of stories event) which are relevant here.


### Option A (current)
 ```
<amp-story-player
  style="..."
  amp-cache="..."
  enable-circular-wrapping
  />
  <a href="">My story</a>
</amp-story-player>
 ```

### Option B

This option has a shared `on-end` attribute for both circular wrapping and fetching from endpoint. Biggest issue here is how to use both functionalities. Also an additional `endpoint` attribute would still be required for the fetching of stories, so it doesn't really minimize the amount of attributes.

 ```
<amp-story-player
  style="..."
  on-end="enable-circular-wrapping"
  amp-cache="..."
  />
  <a href="">My story</a>
</amp-story-player>
 
<amp-story-player
  style="..."
  on-end="fetch"
  endpoint="..."
  amp-cache="..."
  />
  <a href="">My story</a>
</amp-story-player>
 ```

### Option C (Preferred)

 ```
<amp-story-player
  style="..."
  enable-circular-wrapping <!-- Disables end of stories event -->
  amp-cache="..."
  />
  <a href="">My story</a>
</amp-story-player>
 
<amp-story-player
  style="..."
  endpoint="..." <!-- fetch additional stories, when no more stories are returned, dispatches an end of stories event -->
  amp-cache="..."
  />
  <a href="">My story</a>
</amp-story-player>
 
<amp-story-player
  style="..."
  enable-circular-wrapping <!-- Disables end of stories event -->
  endpoint="..." <!-- takes precedence, when no more stories are returned circular wrapping kicks in -->
  amp-cache="..."
  />
  <a href="">My story</a>
</amp-story-player>

```

WDYT @newmuis ?

**Comment by Enriqe** [comment]
Yeah, I think we all agree that developers don't usually read documentation, which would make it hard for them to know if more than one behavior is allowed or which of them takes precedence. 

But I think that by condensing all of the behaviors into one attribute, it makes it clearer that they all belong to the same "category" - it would harder to understand this if they are all different attributes. I think it also scales better if we decide to add more behaviors in the future.

Let's move forward with Option B then, and add multiple behavior support by comma-separated values in the future if there's a demand? @newmuis @gmajoulet

**Comment by gmajoulet** [comment]
Sounds good!
