### ISSUE TITLE
Font from origin 'https://public.slidesharecdn.com' has been blocked from loading by Cross-Origin Resource Sharing policy

### ISSUE THREAD

**Issue by jitendravyas** [ampproject/amphtml#2931]
I'm embedding a SlideShare slide using `amp-iframe` getting this error in console

`Font from origin 'https://public.slidesharecdn.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.slideshare.net' is therefore not allowed access.`

HTML Code
```
<amp-iframe width="340" height="290" 
layout="responsive" 
sandbox="allow-scripts allow-same-origin allow-popups" 
allowfullscreen 
frameborder="0" 
src="https://www.slideshare.net/slideshow/embed_code/key/Aa0H9JnIZUJWWP">
</amp-iframe>
```

**Comment by jridgewell** [comment]
Not sure who to assign to, so @cramforce gets it.

**Comment by cramforce** [comment]
@jitendravyas I think this is something you will need to bring up with slideshare since that request is being emitted from their embed.

**Comment by ssaunier** [comment]
@jitendravyas Did you contact Slideshare? I get the same error on one of my embed.

**Comment by d3netxer** [comment]
I am getting this same error with my github page

**Comment by nlamming** [comment]
Just as a footer to this for anyone else that comes across this thread. This is what Slideshare Support shared with me today:
13/04/17 15:50pm
"Thanks for contacting us about this error you are getting when embedding. What you've encountered is a known issue and I'm very sorry for the inconvenience. Our engineering team is working on it but there's no estimate as to how long that might take. We'll do our best to keep you posted."
 
"In the meantime, I'll gladly help if you have any other questions."

Reading between the lines... Don't hold your breath for a fix any time soon.

**Comment by KasunWijesekara** [comment]
Did anyone find a fix for this issue ?

**Comment by nlamming** [comment]
15th December and I'm still seeing the errors. Anyone else found a solution/workaround (other than not embedding slideshare)?

**Comment by mpoisot** [comment]
4 years later and it's still broken.

**Comment by darioizzo** [comment]
I could also use a workaround, anyone?

**Comment by jridgewell** [comment]
This has to be fixed by SlideShare. There's nothing we can do on our end to help here.
