### ISSUE TITLE
[amp-story-player] PE: improve loading strategy

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#29320]
In the player, we load the 3 iframes pretty much at the same time, we should load the first iframe, then next ones.

/cc @ampproject/wg-stories

**Comment by rnkimani** [comment]
When loading all the iframes sequentially, does it guarantee that the subsequent iframes will have been rendered fully?

**Comment by rnkimani** [comment]
How about rendering one extra iframe after the first iframe has fully rendered? That way the only 2 iframes that can rendered at a particular point in time; just after the first one has fully rendered.

**Comment by gmajoulet** [comment]
Only loading N-1, N, N+1 vs loading 3 stories sounds like a good improvement too, thanks for the suggestion! On page load that'd mean loading one less story and should help a ton.

**Comment by Enriqe** [comment]
> When loading all the iframes sequentially, does it guarantee that the subsequent iframes will have been rendered fully?

It's not guaranteed but it will greatly decrease the likelihood of them timing out. It depends on several factors (what scripts/poster images/etc... are loaded for the stories, where are they hosted (cached or not), etc...).

**Comment by Enriqe** [comment]
I will prioritize this work :)
