### ISSUE TITLE
[amp-story-player] self.onload usage conflicts with other scripts

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amphtml#29335]
## What's the issue?

This is something that was reported by a user of the Web Stories for WordPress plugin at https://github.com/google/web-stories-wp/issues/3245.

There can be conflicts between custom JavaScript on the page and the amp-story-player JS if both scripts use `self.onload`/`window.onload` to initialize.

If the custom script comes after the player JS, the player will never initialize, causing the progress bar to appear infinitely:

<img width="1252" alt="Screenshot 2020-07-17 at 12 17 15" src="https://user-images.githubusercontent.com/841956/87776130-8e020c00-c827-11ea-8e9c-a7a96143198b.png">

The solution would be to use `document.addEventListener('DOMContentLoaded', ... )`, perhaps through the existing `onDocumentReady` helper function in the code base.

## How do we reproduce the issue?

Test case to reproduce: https://jsbin.com/wuqizocavi/edit?html,output

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. Load amp-story-player script as documented/intended
2. Add some custom JS _after that_ which does `window.onload = ....`
3. See 

## What browsers are affected?

All browsers

## Which AMP version is affected?

All versions of amp-story-player as far as I can tell.

**Comment by Enriqe** [comment]
Thanks for reporting! `onDocumentReady` sounds good. I will send a PR soon.

/cc @ampproject/wg-stories
