### ISSUE TITLE
Incorrect unpausing on back navigation to AMP doc

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2933]
It appears that when you

1. E.g. have an ad on a page
2. Click on a link to navigate away
3. Click back

the ad is not shown.

Could it be that we pause on unload? Or is anything else going on.

**Comment by ericlindley-g** [comment]
Slotting into this current sprint, given the high priority, but please update if that's not right

**Comment by jridgewell** [comment]
I'm unable to produce on a standalone AMP page (local build, with ad unloading). Might be a viewer interaction causing it? @ericfs.

**Comment by ericfs** [comment]
I'm also not able to reproduce when using a viewer.

**Comment by jridgewell** [comment]
Got a reproduction thanks to Malte. This only affects elements inside the viewport. For some reason, `inViewport` is false for them, even though the `#renderOutsideViewport` code has detected they are in viewport.
