### ISSUE TITLE
Intent to implement: Support click measurement in AMP

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2934]
Today URL shorteners and other redirectors are used to implement cross-platform click tracking between web pages and apps and web pages. This is bad because it adds extra round trips to the page request that are 100% in the critical path. 1-5 seconds per redirect are not uncommon. Standard mechanisms like `sendBeacon` and the `ping` attribute are insufficient because they do not work when crossing app boundaries.

We'd like to add a feature to AMP where the referrer can request a ping back when a page loaded, so that it does not need to rely on the intermediate redirects.

#### AMP

When an AMP page is loaded with a fragment `#click=URL` then AMP will request that URL. It will also immediately clear the fragment from the URL to avoid further shares of the same URL being tagged with the same URL.

#### Utility

We'll provide a utility script that provides a click handler for generating the `#click=` URLs on pages that would otherwise use a redirect.

**Comment by ericlindley-g** [comment]
Slotting in the backlog, but please update if there's a more specific timeline for this
