### ISSUE TITLE
amp-brightcove cannot be played inside other elements on second click

### ISSUE THREAD

**Issue by dritter** [ampproject/amphtml#29364]
Hi there!

The amp-brightcove player does not work well when it is embedded in other elements (lightbox/accordion/etc) on second click.

Reproducible with the snippet down below. Just open the lightbox twice. On the second time, the video won't play.
Affected versions: at least 2007040248002. Related issues: #28745 . Maybe @jwinkworth has some more infos (sorry for @ mention). [His demo](https://dcc-upload.s3.ca-central-1.amazonaws.com/jw-rnd-days/cs-amp-templates/bug85277/amp-issue-accordion.html#development=1) has the same issue.
Sorry for opening another issue, but the other one is closed..

```html
<!doctype html>
<html ⚡>
<head>
<meta charset="utf-8">
  <title>amp-brightcove</title>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script async custom-element="amp-lightbox" src="https://cdn.ampproject.org/v0/amp-lightbox-0.1.js"></script>
  <!-- ## Setup -->
  <!-- Import the Brightcove component in the header. -->
  <script async custom-element="amp-brightcove" src="https://cdn.ampproject.org/v0/amp-brightcove-0.1.js"></script>
  <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
  <link rel="canonical" href="https://amp.dev/documentation/examples/components/amp-brightcove/index.html">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
</head>
<body>

  <p>
    Open the Lightbox and play the video. On second open, you won't be able to playback the video! :(
    Repeatedly hit the play button, and the video progresses frame by frame.
  </p>
  <button on="tap:lightbox">
    Open Lightbox
  </button>
  <amp-lightbox id="lightbox" layout="nodisplay">
    <amp-brightcove data-account="906043040001" data-video-id="1401169490001" data-player-id="180a5658-8be8-4f33-8eba-d562ab41b40c" layout="responsive" width="480" height="270">
  	</amp-brightcove>
    <button on="tap:lightbox.close">close lightbox</button>
  </amp-lightbox>
  
</body></html>
```

**Comment by dritter** [comment]
Here is a screen recording:
![Brightcove-Issue](https://user-images.githubusercontent.com/1544760/87930673-c81e1880-ca88-11ea-9d72-500f5ec1654c.gif)

**Comment by jwinkworth** [comment]
You can also see a issue in a tabs example:
https://dcc-upload.s3.ca-central-1.amazonaws.com//jw-rnd-days/cs-amp-templates/bug85277/tabs1.html#development=1

If you play the video in either tab, switch to another tab, switch back, and press play again, you get a black screen

**Comment by misteroneill** [comment]
Taking a cursory look at this, it appears that AMP is sending a `pause` message into the player iframe.

**Comment by mister-ben** [comment]
It's being paused in `pauseOtherVideos()` in the video manager. Each time the lightbox is opened there is another object in `this.entries_` for the same player, and one of them gets paused.  

https://github.com/ampproject/amphtml/blob/462f3fda97da22e6056b95de91c6c74f09910bfe/src/service/video-manager-impl.js#L401-L412

**Comment by dritter** [comment]
I wasn't even able to start the video again. Every time I pressed play the video paused immediately. Hard to see in the gif, but I mashed the play button..

**Comment by mister-ben** [comment]
Same behaviour with amp-youtube, but not amp-video.
