### ISSUE TITLE
I2I: Added extension code for amp-speechkit

### ISSUE THREAD

**Issue by zetta83** [ampproject/amphtml#29360]
We want to implement component for audio player supported by https://speechkit.io

Prodecure :
- User will get project-id and the podcast details from here: https://speechkit.io/. 
- Add that project-id as attribute of amp-speechkit.
- User can now listen to podcasts from speechkit-player and manage settings in speechkit-player.

Example :
```
<amp-speechkit
    height="40"
    layout="fixed-height"
    data-projectid="6673"
    data-podcastid="534513"
>
```

**Comment by alanorozco** [comment]
This can be done with an `amp-iframe` and a URL scheme set by authors.

If you'd like `data-` params, like this code does, you can instead use an [amp-video-iframe](https://amp.dev/documentation/components/amp-video-iframe/#third-party-video-vendors).

Is there an additional, specific need for this component?
