### ISSUE TITLE
request for @xiexr151e to become an AMP collaborator

### ISSUE THREAD

**Issue by xiexr151e** [ampproject/amphtml#29388]
Opening this issue to request to become a collaborator.

https://github.com/ampproject/amphtml/pull/29297
https://github.com/ampproject/amphtml/pull/29109

**Comment by erwinmombay** [comment]
+1 from me

**Comment by mrjoro** [comment]
Great!  @xiexr151e I've added you to the Collaborators list. :)

**Comment by xiexr151e** [comment]
Thank you!!!

**Comment by erwinmombay** [comment]
@mrjoro would you mind resending @xiexr151e a collaborator request again, i dont believe he was able to accept it and the invite expired (i think, correct me if im wrong @xiexr151e )

**Comment by xiexr151e** [comment]
Hey Erwin, I have accepted the collaborator invitation. However, for whatever reason, I was able to merge any of my PRs.

**Comment by mrjoro** [comment]
It looks like you weren't yet in the Collaborators team; I just added you.  Let me know if you're able to merge now!  (Note that a [Reviewer will still have to approve your PR](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#code-review-and-approval), but you can do the merging yourself.)

**Comment by xiexr151e** [comment]
Hey Joey, sorry for bothering you with this, but I am able to merge now! Thanks again for your help!

**Comment by mrjoro** [comment]
Great!
