### ISSUE TITLE
amp-iframe does not load sometimes

### ISSUE THREAD

**Issue by sryze** [ampproject/amphtml#29398]
## What's the issue?

amp-iframe does not load sometimes

## How do we reproduce the issue?

1. Go to https://www.upnest.com/re/buysell3
2. Hit refresh until you see a blank white box instead of the calculator iframe

I made a video demonstrating the issue:

https://drive.google.com/file/d/1g223D8PtwUqJ5RyxTKGSzDYVCBDTueUD/view?usp=sharing

## What browsers are affected?

Windows 10: Chrome 83.0.4103.116, Microsoft Edge 44.18362.449.0

## Which AMP version is affected?

2007040248002

**Comment by nainar** [comment]
@Ichigo3d can you reproduce this?

**Comment by sryze** [comment]
Any news on this issue?

If you check this page: 

https://www.upnest.com/re/buysell-discount

the iframe is *not loading at all* right now. It used to work before...

**Comment by sryze** [comment]
It seems to have something to do with `layout="fill"` because if I replace that with `layout="fixed"` and add explicit width and height, the iframe is always loaded

**Comment by westonruter** [comment]
@nainar I'm seeing this as well. An `amp-iframe` with a `layout=fill` is not loading. Another `layout` like `fixed-height` does load. 

Test case ([open on playground](https://playground.amp.dev/#share=PCFkb2N0eXBlIGh0bWw+CjxodG1sIOKaoT4KPGhlYWQ+CiAgPG1ldGEgY2hhcnNldD0idXRmLTgiPgogIDx0aXRsZT5NeSBBTVAgUGFnZTwvdGl0bGU+CiAgPGxpbmsgcmVsPSJjYW5vbmljYWwiIGhyZWY9InNlbGYuaHRtbCIgLz4KICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLG1pbmltdW0tc2NhbGU9MSxpbml0aWFsLXNjYWxlPTEiPgogIDxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoOy1tb3otYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1zLWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoO2FuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RofUAtd2Via2l0LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1vei1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1tcy1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1vLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1Aa2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fTwvc3R5bGU+PG5vc2NyaXB0PjxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjpub25lOy1tb3otYW5pbWF0aW9uOm5vbmU7LW1zLWFuaW1hdGlvbjpub25lO2FuaW1hdGlvbjpub25lfTwvc3R5bGU+PC9ub3NjcmlwdD4KICA8c2NyaXB0IGFzeW5jIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAuanMiPjwvc2NyaXB0PgogIDxzY3JpcHQgYXN5bmMgY3VzdG9tLWVsZW1lbnQ9ImFtcC1pZnJhbWUiIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAvYW1wLWlmcmFtZS0wLjEuanMiPjwvc2NyaXB0PgogIDxzdHlsZSBhbXAtY3VzdG9tPgogICAgYm9keSB7CiAgICAgIHBhZGRpbmc6IDEwcHg7CiAgICB9CiAgPC9zdHlsZT4KPC9oZWFkPgo8Ym9keT4KICA8cD4KICAgIGFtcC1pZnJhbWUgd2l0aCBmaWxsIGxheW91dDoKICA8L3A+CiAgPGRpdiBzdHlsZT0iaGVpZ2h0OjI1MHB4OyBwb3NpdGlvbjpyZWxhdGl2ZTsiPgogICAgPGFtcC1pZnJhbWUgc3JjPSJodHRwczovL2V4YW1wbGUuY29tLyIgbGF5b3V0PSJmaWxsIj4KICAgICAgPHNwYW4gcGxhY2Vob2xkZXI+TG9hZGluZyBleGFtcGxlLi4uPC9zcGFuPgogICAgPC9hbXAtaWZyYW1lPgogIDwvZGl2PgoKICA8cD4KICAgIGFtcC1pZnJhbWUgd2l0aCBmaXhlZC1oZWlnaHQgbGF5b3V0OgogIDwvcD4KICA8ZGl2IHN0eWxlPSJoZWlnaHQ6NDAwcHg7IHBvc2l0aW9uOnJlbGF0aXZlOyI+CiAgICA8YW1wLWlmcmFtZSBzcmM9Imh0dHBzOi8vZXhhbXBsZS5jb20vIiBsYXlvdXQ9ImZpeGVkLWhlaWdodCIgaGVpZ2h0PSIyNTAiPgogICAgICA8c3BhbiBwbGFjZWhvbGRlcj5Mb2FkaW5nIGV4YW1wbGUuLi48L3NwYW4+CiAgICA8L2FtcC1pZnJhbWU+CiAgPC9kaXY+CjwvYm9keT4KPC9odG1sPgo=)):

```html
<p>amp-iframe with fill layout:</p>
<div style="height:250px; position:relative;">
	<amp-iframe src="https://example.com/" layout="fill">
		<span placeholder>Loading example...</span>
	</amp-iframe>
</div>

<p>amp-iframe with fixed-height layout:</p>
<div style="height:400px; position:relative;">
	<amp-iframe src="https://example.com/" layout="fixed-height" height="250">
		<span placeholder>Loading example...</span>
	</amp-iframe>
</div>
```

AMP page renders as:

> ![image](https://user-images.githubusercontent.com/134745/92321094-068d7980-efdc-11ea-9a49-6fa11e2329ee.png)

The `iframe` for the first `amp-iframe` is not getting constructed:

> ![image](https://user-images.githubusercontent.com/134745/92321115-3dfc2600-efdc-11ea-9896-8968cc652bd6.png)

**Comment by westonruter** [comment]
This is somewhat blocking a Jetpack plugin PR to add AMP compat for the OpenTable block: https://github.com/Automattic/jetpack/pull/17085

**Comment by kristoferbaxter** [comment]
Thank you @jridgewell for agreeing to take a look.
