### ISSUE TITLE
amp-script component is broken on IE 11

### ISSUE THREAD

**Issue by claudiucelfilip** [ampproject/amphtml#29395]
## What's the issue?

`<amp-script>` doesn't work on IE 11 and throws the error: `Object doesn't support property or method 'startsWith'`

## How do we reproduce the issue?

1. Go to https://jsbin.com/nubahub/
2. Click `Hello amp-script!` button

### Expected 
Button should be replaced with `Hello World!` text.

### Actual
Button does nothing and a console error is triggered:

<img width="780" src="https://user-images.githubusercontent.com/2749938/88059124-16a4e300-cb6d-11ea-9b87-4e9d8ed3deb7.png" />
<img width="780" src="https://user-images.githubusercontent.com/2749938/88059128-186ea680-cb6d-11ea-9f8d-4d9b87657bf3.png" />

## What browsers are affected?
IE 11

## Which AMP version is affected?
Powered by AMP ⚡ HTML – Version 2007040248002

**Comment by mrjoro** [comment]
@choumx can you take a look with @kristoferbaxter out?

/cc @ampproject/wg-runtime @ampproject/wg-performance

@ampproject/release-on-duty as FYI

**Comment by samouri** [comment]
@choumx: I can take this. Installing an ie11 vm now to repro

**Comment by samouri** [comment]
This is currently blocked on https://github.com/ampproject/worker-dom/issues/217

**Comment by samouri** [comment]
Closing as we've officially deprecated IE11. https://github.com/ampproject/amphtml/issues/34453
