### ISSUE TITLE
Actions: protocol for arguments

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#294]
@cramforce , @erwinmombay for advice:

Currently our actions have no arguments. But we need some, e.g.

on="tap:target.toggleClass(visible)"

Some ideas:

- We can allow positional arguments:
  on="tap:target.toggleClass(visible, false)"

- We can allow named arguments:
  on="tap:target.toggleClass(name=visible, on=false)"

- We can allow both types of arguments (Dart style):
  on="tap:target.toggleClass(visible, false, x=1, y=2)"

- We can implement argument syntax ourselves, e.g. functional (Dart style) above

- We can use JSON (unfortunately it's hard to do positional in this case and quotes!):
  on="tap:target.toggleClass{'name': 'visible', 'on': false, 'x': 1, 'y': 2}"

WDYT?

**Comment by cramforce** [comment]
What do we actually need right now?

How about actual JSON in a second attribute?:

```html
<button on="tap:target.toggleClass" arguments='{"foo", 123}'>
```

Having said that: I don't want us to implement toggleClass without a deep discussion. It s fine example, though :)

**Comment by erwinmombay** [comment]
i believe it was mentioned this is sort of modeled on `jsaction` ? will we allow any arbitrary action? (im guessing no). yeah a discussion on this would be good for sure

**Comment by cramforce** [comment]
jsaction certainly doesn't allow arbitrary and doesn't support arguments :)

**Comment by dvoytenko** [comment]
`on` currently allows multiple actions delimited by semicolons.

There's not much need so far for arguments - actually they only case we wanted to do so far is with `toggleClass`, but it's likely that something would come up.

**Comment by cramforce** [comment]
Yeah, starting with positional only makes sense. I think we should quote
strings, though.

The problem with toggleClass is that it can be used to build invasive ads
(e.g. full page overlays). What do you want to use it for?

**Comment by rudygalfi** [comment]
Do we want to call this discussion closed, or keep this around for post-M1 discussion?

**Comment by dvoytenko** [comment]
Let's close until it comes up with the specific request.
