### ISSUE TITLE
<amp-youtube> embed has a large amount of unused JS

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#29401]
The youtube embed currently has a large amount of unused JS - [400kb](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Felpais.com%2Fespana%2Fmadrid%2F2020-07-14%2Flos-residentes-de-madrid-estan-entre-los-peores-pagados-de-espana.html%3FoutputType%3Damp) in some cases. 

While I know this is coming from the 3p script. Is there anything we can do on the AMP end to help minimize this?

It falls outside the 20kb limit posed by LightHouse

Related: https://github.com/ampproject/amphtml/issues/28638

**Comment by shraddha-kesari** [comment]
Facing the same issue. Please provide suggestions to fix this. Thank you.
