### ISSUE TITLE
AMP Iframe Resizing not working as intended

### ISSUE THREAD

**Issue by alaurelut** [ampproject/amphtml#2940]
According to the AMP project documentation : https://www.ampproject.org/docs/reference/extended/amp-iframe.html,

It is possible to resize the height of an amp-iframe in run time, to do so : 

I followed the doc and my amp-iframe used to be resizing just fine in february, the height of the amp-iframe was the same of what was inside of the iframe.

But I noticed recently that it wasn't working properly anymore, the iframe is still resizing, but not to the right height which should be the iframe body height, it it resizing to a height that seems to be linked to the height attribute of the amp-iframe element (but not the same height as this attribute).

Here is an url where you can see the issue : http://ligatus-toolbox.com/amp/test.html#development=1

I tested on Chrome and Firefox on a desktop, and for mobile i tested on android 5.1 and 6.0, and it's not working properly anywhere.

I'm testing with the v0 AMP version (https://cdn.ampproject.org/v0.js)

Let me know if you need more information.

**Comment by sriramkrish85** [comment]
@alaurelut , i debugged your page, and i dont see any postmessage for embed-size arriving from your iframe. This is because the `event.origin` is set as null when the message arrives to the parent. 

https://www.w3.org/TR/cors/#generic-cross-origin-request-algorithms

try using `allow-same-origin` on your iframe.

**Comment by alaurelut** [comment]
Hi @sriramkrish85, thanks for your time.

I added `allow-same-origin` to the sandbox attribute on my iframe, and checked the event.origin which return `"https://d2.ligatus.com"` and not null on my side, but it is still not working.

I logged the message event on my test page, and i can see `embed-size` in the object datas.

Any ideas what else it could be ?

**Comment by alaurelut** [comment]
Hi,
Just to let you know, i figured out what was breaking the interception of the postMessage from the iframe by the parent page.

My amp-iframe src had a hostname different from the one returned from the server ( for some reason ..).

So I had : 
```
<amp-iframe id="iframe" width="300" height="300"
sandbox="allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox"
layout="responsive"
resizable
src="https://d.ligatus.com/?ids=78659&s=1">
    <div overflow tabindex=0 role=button aria-label="Read more">Read more!</div>
</amp-iframe>
```

But the server did a redirection to a different subdomain named `d2.ligatus.com`.

This broke the condition of the amp-iframe.js `if (event.source != iframe.contentWindow)` (line 48 in https://github.com/ampproject/amphtml/blob/master/src/iframe-helper.js)

I just had to change the hostname in the src of my amp-iframe to `d2.ligatus.com`, and it is now working perfectly.
