### ISSUE TITLE
Validator: More helpful error message for value_oneof_set

### ISSUE THREAD

**Issue by morsssss** [ampproject/amphtml#29413]
When using `<amp-script>`, if you omit the `target` attribute from a `<script>` tag, you get these validation errors:

`Custom JavaScript is not allowed.`
`Attribute 'script' in tag 'amp-script' contains a value that does not match any other tags on the page.`

This is true even if we get a strong hint that the `<script>` was intended for use by `<amp-script>`, as in:

```html
<script id="myscript" type="text/plain">
...
<amp-script layout="fixed" script="myscript">
```

It would be nice if we could recognize such cases by the `id` in the `<script>` tag, and instead tell people something like:

`Any script intended for <amp-script> must include the attribute 'target="amp-script"'.`

![image](https://user-images.githubusercontent.com/29419498/88112043-0f85d100-cb7d-11ea-97fe-8e6a88b4bc57.png)

**Comment by choumx** [comment]
Sounds like a validator feature request for `value_oneof_set` and `add_value_to_set`. I.e. is it possible to print the possible set values in the error message?
