### ISSUE TITLE
Link to a Specific Part of a Page - IM NEW

### ISSUE THREAD

**Issue by munaterai336** [ampproject/amphtml#29425]
Good afternoon, I am new to programming. I am learning...

reviewing a page that I made, I see that on the page there is a link to go to a specific part of that same page. 

[https://pmotion.co/amp/promociones/?t=dispensadores-de-agua-alcalina-y-mineralizada&id=16947](https://pmotion.co/amp/promociones/?t=dispensadores-de-agua-alcalina-y-mineralizada&id=16947)

The page is fine as AMP, but when clicking on the link...   `<a href="#arriba">`  it does nothing. 
It is supposed to go to the ID, to the part of the page with that ID.

What am I doing wrong .. What am I missing?

the AMPs can do that?

Thnks for the help..

Sorry for my english..

I speak spanish

**Comment by nainar** [comment]
Hi @munaterai336 there is no section with an id of `arriba` in the page for the a href to point to. 

See here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a (Linking to an element on the same page)

**Comment by munaterai336** [comment]
Thank you very much for responding...

now i can see the problem, 

when converting <img to <amp-img the id = "arriba" is getting lost...

the conversion is automatic .. php code


now the problem will be, how to convert <img to <img amp without losing the id
