### ISSUE TITLE
Default code for AMP for stories in AMP playground produces validation errors

### ISSUE THREAD

**Issue by mcmd** [ampproject/amphtml#29423]
## What's the issue?

The code loaded by default in AMP playground for AMP for Stories produces 4 validation errors.

![Screen Shot 2020-07-22 at 3 38 39 PM](https://user-images.githubusercontent.com/868584/88192155-1cb1c700-cc34-11ea-93a2-4abd84840d6c.png)

## How do we reproduce the issue?

1. Open [AMP validator](https://playground.amp.dev/)
2. Select AMP for Stories in the top left dropdown
3. Get validation errors

## What browsers are affected?

N/A

## Which AMP version is affected?

N/A

**Comment by brianpetro** [comment]
Currently, the amp4stories playground is completely unusable. The code doesn't even appear to be rendered in the preview window.

![My-Story-AMP-Playground](https://user-images.githubusercontent.com/1886014/103215532-9c2d7b80-48e1-11eb-9dfa-453aa904891c.png)
