### ISSUE TITLE
The "Advanced" feature in cdn.ampproject.org/experiments.html is unavailable through UI on Internet Explorer 11 (Windows)

### ISSUE THREAD

**Issue by Ichigo3d** [ampproject/amphtml#29439]
## What's the issue?
UI button of the "Advanced" feature is broken in cdn.ampproject.org/experiments.html is unavailable through UI on Internet Explorer 11 (Windows)

## How do we reproduce the issue?

1) go to cdn.amproject.org/experiments.html in Internet Explorer 11
2) Observe the "Advanced" button

## What browsers are affected?

Internet Explorer 11

## Which AMP version is affected?

![IMG_8917](https://user-images.githubusercontent.com/37351864/88228831-98a41300-cc24-11ea-8ccd-ad6e2584e571.jpg)

**Comment by Ichigo3d** [comment]
@ampproject/wg-infra

**Comment by rsimha** [comment]
I noticed that the opening and closing tags for this section are mismatched (`details` / `detail`).

https://github.com/ampproject/amphtml/blob/6de0ebfff6360fe21b45b7c9af001254bb13a4a9/tools/experiments/experiments.html#L251-L265

Either that, or the `<details>` tag just [doesn't work on IE 11](https://stackoverflow.com/questions/51304178/html-details-tag-does-not-work-in-ie-edge).

**Comment by rcebulko** [comment]
> Either that, or the `<details>` tag just [doesn't work on IE 11](https://stackoverflow.com/questions/51304178/html-details-tag-does-not-work-in-ie-edge).

https://caniuse.com/#feat=details

**Comment by danielrozenberg** [comment]
> Either that, or the `<details>` tag just [doesn't work on IE 11](https://stackoverflow.com/questions/51304178/html-details-tag-does-not-work-in-ie-edge).

I'm gonna admit that I actually knew that but didn't think it would become a problem >_<
Open to ideas what to do here instead!

**Comment by rsimha** [comment]
_[Infra triage]_ Given that IE 11 was sunsetted by Microsoft [in November 2020](https://en.wikipedia.org/wiki/Internet_Explorer_11#cite_note-9), I think this issue can be closed. Please reopen if there's good reason to solve this.
