### ISSUE TITLE
amp-consent: Need to increase the consent string max length again

### ISSUE THREAD

**Issue by vyoungnyc** [ampproject/amphtml#29454]
## What's the issue?

we have some publishers exceeding the max consent string length supported by amp.

## How do we reproduce the issue?

for one of our publishers, the consent string we see is above 1700 characters, while max consent string length is set at 1200 character limit.

CO29EzZO29EzZAGABCENAvCgAAAAAH_AACiQAAAMIIpMBQUCoaFtqAbbdKIUwgQjyFuQUBnDCMBBtYbEw4N2BQEeoAhYCowAEgEMhBBZAQCAAyACJCogAABAQCqAiEQAAoBGgIQAUSBBLIiQIAgAFQNHQAmmCEgxg4sAo_2IiKoBI0AwACwAMQAmQBWgDVAG0AOMAeABKwCWwFeAV8AuwBnAD9gISAR2Aj0BIICUQEvAKZAWIAusBdwkBqAAYABYADgALgAoABYAD4AIQARAAjABQACwAFsAMQAbwA5gClAFaANUAcAA4wBzgDrAHkAPkAkwBKwCWgE6AKgAVmArwCvgF2AM4AagA2wBuAD1AH7AQkAjsBIICSwEogJeAU3AsQCxQFogLiAXRAusC7AF3ALxCgSQABAAGgAcAB4AFwAPgAoABYADIAHYAQgAjABQgCkAKYAWwAxAB_AEJAIoAiwBKgCtAFwAL4AYQA0QBqgDaAHAAOOAdQB1gDyAHyAP8Ag4BFwCNAEmAJWAToAn4BUACswFeAV8AuwBmADOAG2APUAfsBCQCHwEdgI9ASCAksBKICVgEtAJeAUSApcBTICpgFXgK-AWIAsmBaAFogLigXUBdgC7oF4gXkAv4BhAcBmAAYABYADgALgAoABYADwAIQARAAjABYAC2AGIAN4AcwA8AClAFaANUAcAA4wBzgDrAHkAPkAkwBK4CWgJcATgAnQBWYCvAK-AXYAzgBtgD1AH7AQkAkEBJYCUQEvAKbgWIBYoC0QFxALogXWBdgC7gF4gL6FgHAAWABiADwAJkAVoA1QBtADjAHgAPkAkwBK4CWgJdAV4BXwC7AGcAP2AhIBHYCPQEogJeAUzAsQCxQFogLrAXcAvoeBVAAMAA8AD4AKAAWAAyAByAD8AIIARgAoABSAC2AF0AL4AZAA0AB_AEJAIoAiwBJgCdAFbALIAswBcAC-AGEANUAbQA44B1AHXAPEA8gB8wD_AQAAg4BEYCLAIuARoAkwBK4CWgJcATYAnABOoCfAJ-AVmArwCvgFtgLqAuwBgYDMAMyAZwA14BtgDyAHmAPUAfsBCACEoEPgRAAjsBHoCSwEogJUgSsBK4CWgEvAKFAUgApOBS4FMgKqAV2Ar4BYkCyQLKgWgBaUC6QLsAXcAvEBewC-gGCEQGQALAAfgBBAC-AGgAP4AiwBJgCtAFkAL4AYQA1QBtADgAHgAPkAf4BKwCXAE4AKzAV4BX4C6gLsAZkAzgB2wDzAH7AQ-AiIBHYCPQEogJUASuAloBLwChQFIAKTAUyAr4BYgCyYF1gXYAu4BewC-gGCEwHYABgAHAAhABQACwAHIAQgAoABSAC-AGQAN4AeABCACTAFaALIAXIAvgBqgDaAHGAOsAfIBBwCEgErAJaAToApoBWYCvAK-AWeAuoC7AGcANeAbYA-QB9gD9gISAR2AkEBKICVgEvAKTAUyAqkBYgCygFpALYAXFAusC7AF3ALxAXsAvoqBHAA-ACEAFAALAAZAA5gB8AH4AQgAjABQACyAF8AMgAbwA5AB4AEIAIsASYAmQBOgCtAFkALkAXwAwgBqgDXAG0AOMAdQA8AB8gEAAIOAQmAioCLAErAJaATYAnUBPgE_AKzAV4BX4C6gLsAZwA14BtgDtgHkAPMAfIA_YB_wEJAI7AR6AksBKICWgEvAKQgUwBTICuwFiALQAXWAu4BeIC-gGCAA.YAAAAAAAAAAA

## What browsers are affected?

all browsers

## Which AMP version is affected?

all versions of amp, as it exceeds the limit

**Comment by zhouyx** [comment]
sign. Let's also monitor the error rate.

**Comment by zhouyx** [comment]
There are two related errors.
1. amp-consent checks for the string size, report a [**user error**](https://github.com/ampproject/amphtml/blob/master/extensions/amp-consent/0.1/consent-state-manager.js#L384) when the size exceed 1.2k
2. AMP viewer reports a [**dev error**](https://github.com/ampproject/amphtml/blob/master/src/service/storage-impl.js#L409) error, when the total size exceed 2k.

I couldn't find any error logs related to these two errors. @vyoungnyc Do you have an estimate on the percentage of traffic that are been affected today?

**Comment by vyoungnyc** [comment]
We have only seen reports of 1 publisher at the moment. They are transitioning from tcfv1 to tcfv2 at the moment so the traffic isnt high. The publisher probably has 400+ vendors, so i can imagine we will experience this problem sooner or later.
