### ISSUE TITLE
when sending autoplay tap-to-unmute is not considered in amp-dailymotion

### ISSUE THREAD

**Issue by kutayvardar** [ampproject/amphtml#29451]
## What's the issue?

`autoplay` attribute is not being handled as explained in the public docs.
=> https://amp.dev/documentation/components/amp-dailymotion/

## How do we reproduce the issue?
https://jsfiddle.net/nr5zq3Lk/

## What browsers are affected?

All browsers.

## Which AMP version is affected?

https://cdn.ampproject.org/v0/amp-dailymotion-0.1.js

**Comment by Ichigo3d** [comment]
Hello. Thank you for your participation in improve of our product. Could you explain more about issue? Which parameters don't work as described? Here parameters of autoplay:
"If this attribute is present, and the browser supports autoplay:
the video is automatically muted before autoplay starts
when the video is scrolled out of view, the video is paused
when the video is scrolled into view, the video resumes playback
when the user taps the video, the video is unmuted
if the user has interacted with the video (e.g., mutes/unmutes, pauses/resumes, etc.), and the video is scrolled in or out of view, the state of the video remains as how the user left it. For example, if the user pauses the video, then scrolls the video out of view and returns to the video, the video is still paused."

**Comment by kutayvardar** [comment]
Hello @Ichigo3d ! Many thanks for your response.
I'm using autoplay parameter as provided in the fiddle, but "the video is not automatically muted before autoplay stats" therefore `autoplay` doesn't work.
`<amp-dailymotion data-videoid="x3rdtfy" width="480" height="270" autoplay>`

**Comment by Ichigo3d** [comment]
I can't reproduce this issue. In my case: all videos are muted and autoplayed. I tried it under beat and production versions, got the same result. Try to clean cache in the browser

**Comment by kutayvardar** [comment]
@Ichigo3d you can reproduce over here: https://jsfiddle.net/nr5zq3Lk/
Thanks.

**Comment by Ichigo3d** [comment]
I see it. Thank you. cc @alanorozco

**Comment by kutayvardar** [comment]
Hello @alanorozco et all, 
Sorry for that, but Is there any movements in regards to the fix as I think we have no workarounds to remedy in the short term?
