### ISSUE TITLE
Display Web Stories play/pause button in mobile view

### ISSUE THREAD

**Issue by ernee** [ampproject/amphtml#29469]
## Describe the new feature or change to an existing feature you'd like to see

Currently, the play/pause button in the Web Stories UI is only available [in the desktop view](https://github.com/ampproject/amphtml/issues/25595).

Providing the play/pause button in the mobile view could be helpful for some users.

## Describe alternatives you've considered

N/A

## Additional context

Initial request was from a user in the Web Stories WordPress plugin repository after they tested with an audience new to the format: 

https://github.com/google/web-stories-wp/issues/3315
https://github.com/google/web-stories-wp/issues/3281#issue-661452856

No play/pause button in mobile view: 

<img width="374" alt="no play/pause button in mobile view" src="https://user-images.githubusercontent.com/8108643/88442905-0c802000-cdcb-11ea-8d3f-f5447cf8b22c.png">

**Comment by swissspidy** [comment]
Original reason in #27815 was:

> Not shown on Mobile UI since the long press works as a pause button
