### ISSUE TITLE
SSR'd img tags should be visible by default

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#29479]
Server-side rendered hero images (amp-img -> img) still don't render without the AMP runtime being loaded. The problem is that they're hidden by the following rule:

<img width="495" alt="Screen Shot 2020-07-23 at 20 23 48" src="https://user-images.githubusercontent.com/380472/88337029-49e69e00-cd36-11ea-9070-2128f0440540.png">

Adding the following rule to v0.css would fix this issue by explicitly setting server-side rendered `img` to visible:

```
amp-img[i-amphtml-ssr]:not(.i-amphtml-element):not([layout=container])>* {
  display: block;
}
```

**Comment by dvoytenko** [comment]
The `amp-img` we can just get away with:

```
amp-img[i-amphtml-ssr]>img {
  display: block;
}
```

If we want a more generic implementation, it would be something like this:
```
- .i-amphtml-notbuilt:not(.i-amphtml-layout-container) > *, .... {
+.i-amphtml-notbuilt:not([i-amphtml-ssr]):not(.i-amphtml-layout-container) > *, .... { 
  display: none;
}
```

But, tbh, I think it's a good idea to start with just the image and we can go from there.

**Comment by sebastianbenz** [comment]
```
amp-img[i-amphtml-ssr]>img {
  display: block;
}
```

does not work due to CSS rule precedence. Also, `>img` would hide the sizer dive inside the `amp-img`.

**Comment by dvoytenko** [comment]
I see. It'd be probably than safer to add `:not([i-amphtml-ssr])`. But to clarify, why would a rule on `>img` hide the sizer? It's supposed to be always shown, I believe. Also, does the SSR'd `<img>` have the `i-amphtml-fill-content`? If it does, we can also use that. E.g.

```
... > * {display: none}
```

would be
```
... > :not(.i-amphtml-fill-content) {display: none}
```

**Comment by sebastianbenz** [comment]
Has this already been fixed in the runtime (as the img transformation is now also implemented in the AMP cache)?
