### ISSUE TITLE
Safari desktop. Video captions are clipped in "desktop panel" mode.

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#29470]
To reproduce 
1. Open a video with captions in Safari desktop. 
For example, last page of [this story](https://www.gstatic.com/amphtml/stamp/qa/video.html)
2. Be sure the screen is in `desktop panel` mode.

Screenshot:
![Screen Shot 2020-07-23 at 2 02 10 PM](https://user-images.githubusercontent.com/3860311/88321443-2cd9ad00-cced-11ea-9588-d2bac071871f.png)

**Comment by processprocess** [comment]
Changing translateX of any parent causes this bug.
This may be a bug in WebKit.
![Dec-16-2020 14-19-37](https://user-images.githubusercontent.com/3860311/102396093-f48f7f80-3fa9-11eb-9a94-7d3f3c867273.gif)

**Comment by gmajoulet** [comment]
Closing in favor of https://github.com/ampproject/amphtml/issues/34016
