### ISSUE TITLE
Single finger scroll not working in amp-lightbox and amp-image-lightbox

### ISSUE THREAD

**Issue by atiqul** [ampproject/amphtml#2948]
I am trying to use amp-image-lightbox to show image with its caption when user click on the image from a carousel which is also implemented by amp-carousel. When caption overflowed its container, can't scroll (mousewheel scroll working fine) though it set to 'overflow-y: auto' and '-webkit-overflow-scroll: touch'. Anything if I found from the net is using '-webkit-overflow-scroll: touch'. Is there any solution and please don't mind if it is duplicate. Thanks in advance.
![screenshots](https://cloud.githubusercontent.com/assets/334633/14670646/cf60c386-070f-11e6-99f6-d10098bfadc9.PNG)

**Comment by ericlindley-g** [comment]
@sriramkrish85 — since you're looking into other lightbox fixes/enhancements, do you have thoughts about where we can target this bug? (temporarily putting in "pending sprint slotting")

**Comment by sriramkrish85** [comment]
If i understand this right , @atiqul wants an overflow mechanism for the lightbox text (and this probably has nothing to do with the carousel)

@ericlindley-g this is probably a design decision - we can discuss if this needs changes or not.

@atiqul please provide a link with your mock implementation (even a js bin would do), this would help me follow the issue better.

**Comment by atiqul** [comment]
[mock implementation with jsbin](http://jsbin.com/mitobo/edit?html,output)
@sriramkrish85 here you can find the details scenario which I have mentioned in the issue. Open [output](http://output.jsbin.com/mitobo) in mobile view and try to scroll the caption it will not scrolling but mousewheel scroll is working. If you test it with the real device (rather than chrome emulator) you will find scroll is working with two finger that's why I mentioned single finger scroll not working to the title of the issue.

Thanks

**Comment by camelburrito** [comment]
@atiqul - we added a scrollable attribute to the lightbox and you should be able to use that to make the scrolling happen let me know if that works for you (i see the reported issue is also working now as well) let me know if these work for you. Else feel free to re-open

**Comment by atiqul** [comment]
Thanks for your reply but no luck in my case. I have given you [mockup link](http://jsbin.com/mitobo/edit?html,output). Could you please test on the mockup given?
I think it is created long ago and better if you create a new ticket and link it with that new one would be better than to reopen this one. 
Thanks.
