### ISSUE TITLE
[Story video] Do not downgrade a managed video that is already fully loaded

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#29498]
Do not downgrade a managed video that is already fully loaded. It would just use more bandwidth to re-load a video at a lower quality.

cc @ampproject/wg-stories

**Comment by mszylkowski** [comment]
Would this refer to "fully loaded" or "somewhat loaded"? And I assume this is only valid after implementing https://github.com/ampproject/amphtml/issues/29501 right (so it's only on slow initial load that this could happen)?

**Comment by gmajoulet** [comment]
Let's only do fully loaded, or over 80% loaded for now. There is a lot of context to "somewhat loaded", happy to share it but I don't want to overload this ticket with extra context.

This piece of code needs to be optimized, right now it will try to preload ALL the videos that are managed:
https://github.com/ampproject/amphtml/blob/e7798f4fbd1128a5d3785ab1f098bf2ea2d4c782/extensions/amp-video/0.1/flexible-bitrate.js#L223-L244

It needs to be optimized to:
- Using [`HTMLMediaElement.buffered`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/buffered), detect that the video is loaded and doesn't need to downgraded + loaded again. (`readyState` is unreliable to do that)
- Sort sources but NOT call `load` on videos that weren't preloaded yet. I assume using the `readyState` we can guess that a video is in a future page and shouldn't be preloaded using `load()`
