### ISSUE TITLE
🌸 Cherry pick request for 29431 into 29429 (Approved)

### ISSUE THREAD

**Issue by Jiaming-X** [ampproject/amphtml#29493]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #29431 | #29431 |     **YES**     | **NO** | **NO** | #29429                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

It would otherwise cause a significant harm to AMP's reputation if left unresolved. It affects 55K queries per day. In 6 days, there are 9 pubs affected for more than 10K queries. The worst one is 100K queries.

# Mini-postmortem

> Not a cherry pick to stable.

## Summary

The issue creates invalid format like 0x250 ad request, and will leave the ad slot blank.

## Impact

- It affects 55K queries per day. In 6 days, there are 9 pubs affected for more than 10K queries. The worst one is 100K queries

## Action Items

- Alerts for this issue: https://buganizer.corp.google.com/issues/161723080

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by rsimha** [comment]
@lannka Since this is only going to beta / experimental, do you approve?

**Comment by Jiaming-X** [comment]
Might need some feedback here.

For the current impact, do we need Stable cherry-pick?

**Comment by Jiaming-X** [comment]
In terms of time, what's the difference for stable cherry-pick vs beta / experimental one?

**Comment by choumx** [comment]
Stable is immediate (today), beta goes to production next Tuesday.

**Comment by Jiaming-X** [comment]
Confirmed it with Stephen @yuanlx / stephenyuan. 

Beta / Experimental one should be enough. Thanks.

**Comment by lannka** [comment]
Approved

**Comment by rcebulko** [comment]
It appears this was not cherry-picked last week, will likely have to cherry-pick this with #29528 and possible delay Stable by a day to allow time in Beta

**Comment by rsimha** [comment]
This is now in Stable channel as part of https://github.com/ampproject/amphtml/releases/2007242032001.

**Comment by rsimha** [comment]
Assigning to @Jiaming-X for verification and closure.

**Comment by Jiaming-X** [comment]
Just noticed you guys were not in this bug ticket: https://buganizer.corp.google.com/issues/161723080

I have verified the results, and included verification screenshot in the ticket.

**Comment by Jiaming-X** [comment]
Thank you everyone!
