### ISSUE TITLE
[Story 360] Deallocate resources on page navigation

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#29512]
Deallocate resources when navigating away from a 360 image or video. This will require using the Owners service and manually layout/unlayout the `amp-story-360` components based on the story page `distance` value.

cc @ampproject/wg-stories

**Comment by gmajoulet** [comment]
We can use the lose context feature: https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_lose_context/loseContext

To layout/unlayout the elements through the Owners service:

```
const owners = Services.ownersForDoc(this.element);
owners.setOwner(ampImgEl, this.element);
owners.scheduleLayout(this.element, ampImgEl); // or scheduleUnlayout(...)
```

We can do this from the `amp-story-page.setDistance()` method where we know how far away from the active page the component is, and the page has references on its `amp-story-360` components to handle their layout/unlayout lifecycle.

**Comment by processprocess** [comment]
For reference:

Information / example of loosing and restoring webgl context:
https://www.khronos.org/webgl/wiki/HandlingContextLost

Docs on `WEBGL_lose_context`
https://www.khronos.org/registry/webgl/extensions/WEBGL_lose_context/
