### ISSUE TITLE
Block one AMP components until other component is resolved

### ISSUE THREAD

**Issue by kodemonks** [ampproject/amphtml#29534]
I want to block some amp-components (amp-image, amp-ad, or amp-iframe) until one of the amp components is resolved. ie. - amp-captcha is solved or amp-script ran successfully.
I checked that we can achieve something similar in amp-consent component using **data-block-on-consent** attribute, I am wondering if we have some param to achieve this.

**Comment by choumx** [comment]
There's no generic non-consent API for this. Can you describe your use case in more detail?

**Comment by kodemonks** [comment]
@choumx - I want to hide/show one or more AMP components (can be any of these  - amp-image, amp-ad, or amp-iframe) based on API response from an API endpoint. We will get either 1 or 0 as a response.
So In case of 0 as a response, I will not load the above amp-component and/or show captcha, If the user solves captcha I will unblock/load those components.
Does this give a brief idea of what I am trying to achieve? let me know if you have any other questions regarding the same.

**Comment by choumx** [comment]
Have you tried using amp-list + amp-recaptcha-input?

**Comment by kodemonks** [comment]
Thanks! @choumx  - I am checking this, will share my output/observation over here.

**Comment by kodemonks** [comment]
Hi @choumx ,
I tried using amp-list and amp-recaptcha input component and it worked on problem scenario to some extent.
I was wondering if there is a way to remove re-captcha input once it is solved.? Looking for a while now with no success.
Thanks.

**Comment by kodemonks** [comment]
Hello @chomux,
Any suggestion on how to remove the amp-recaptcha component once solved.? I don't want any user to hit it multiple times.?
Apart from that, I was trying to pass some value to other components down below. i.e. - Once captcha is solved I need to unlock x ad-units and these can be way below on-page. Now I cannot directly update these values unless user interaction on those areas. I was hoping to replace those ads with blank space of the same size so we don't change the layout.
Any suggestions/recommendations will be appreciated.
Thanks in advance.
