### ISSUE TITLE
Video doesn't autoplay from cached source in stories (Safari IOS)

### ISSUE THREAD

**Issue by Ichigo3d** [ampproject/amphtml#29538]
## What's the issue?
Video doesn't autoplay from cached source in stories. Test case cell 44 in amp test passes.

## How do we reproduce the issue?
1. Go to this link https://www.gstatic.com/amphtml/stamp/qa/video.html
2. Go to the second slide
3. Observe result

Actual result: Video doesn't autoplay, Error message is appearing: "Video failed to play". 
Expected: Video should autoplay.

## What browsers are affected?
Safari IOS

## Which AMP version is affected?
2007172306003
![IMG_9062](https://user-images.githubusercontent.com/37351864/88700386-78a99f00-d0bd-11ea-834d-f7913c45ad54.jpg)

**Comment by Ichigo3d** [comment]
The same error message is appearing in test case of audio https://www.gstatic.com/amphtml/stamp/qa/amp-audio.html
<img width="1458" alt="Screen Shot 2020-07-28 at 12 32 22 PM" src="https://user-images.githubusercontent.com/37351864/88712935-5882db80-d0cf-11ea-8116-01a56b7b1e52.png">

**Comment by gmajoulet** [comment]
Closing as we monitor these errors through an error reporting mechanism. They happen ~0.2% of the time and we did not notice any spike with the latest release.
