### ISSUE TITLE
🌸 Cherry-pick request for #29482 into #29539 (approved)

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#29548]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| N/A | #29482 |     **YES**     | **NO** | **NO** | https://github.com/ampproject/amphtml/issues/29539                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

We need to launch module/nomodule as soon as possible. to be able to prove that there is no ads regression we need these experiment ids to be reported asap

## Why is an LTS cherry-pick needed?

Currently only need this to expedite to stable for next weeks promote

## Summary

There is no issue, this is to prove that there will be no regression when we move forward with launch.

## Impact

- <_Which users were affected? Roughly how many?_> N/A
- <_How were users affected? E.g. partial or complete loss of functionality?_> N/A

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by erwinmombay** [comment]
would like to piggy back on the current new cut/cherry pick work with this cherry pick request

**Comment by lannka** [comment]
approved

**Comment by rcebulko** [comment]
This PR is already in the Nightly being promoted to Beta/Experimental, I don't think this requires a cherry-pick
