### ISSUE TITLE
Load only required portion of AMP library 

### ISSUE THREAD

**Issue by askmeoffers** [ampproject/amphtml#29553]
Hi , 

This is regarding our amp based site https://askmeoffers.com/coupon-deal-offer-promo-store/oyorooms-com/

We notice that page speed tool ( light house ) throws warning for unused amp js libraries 
https://developers.google.com/speed/pagespeed/insights/

for our oyo coupons store and other pages as well
https://askmeoffers.com/coupon-deal-offer-promo-store/oyorooms-com/

As per below snapshot 

We have already raised this issue with amp wordpress team but they informed that amphtml should look into it .

As AMP is meant for performance so I think this should be high priority .

![image](https://user-images.githubusercontent.com/55142548/88758363-e6b99900-d185-11ea-9eba-91734438fadb.png)

**Comment by choumx** [comment]
Deduping with #29553.
