### ISSUE TITLE
[amp-ad] Supports json variables and variable substitutions in data-url for amp-story-auto-ads and amp-ad

### ISSUE THREAD

**Issue by jerryluk** [ampproject/amphtml#29573]
## Describe the new feature or change to an existing feature you'd like to see

Similar to amp-list, supports a way to use variables in making the requests for custom ads. This will allow the ad server to provide contextual ads for the AMP.

## Describe alternatives you've considered

Tried to look into amp-iframe but it is not supported in AMP story.

## Additional context

There is already a TODO in https://github.com/ampproject/amphtml/blob/master/ads/custom.md#to-do

**Comment by calebcordry** [comment]
to @ampproject/wg-ads for prioritization.

**Comment by lannka** [comment]
This will be relatively a small change. @jerryluk do you have engs can contribute to this? I can be the code reviewer.

Basically you want to follow what amp-pixel did to expand the URL using `urlReplacements` utility: https://github.com/ampproject/amphtml/blob/eeca1bc84acbc0d5fbfe88663236982109ac01c5/builtins/amp-pixel.js#L84-L101

**Comment by jerryluk** [comment]
Hi @lannka let me talk to the team. It is exciting since none of us has experience with AMP before.
