### ISSUE TITLE
Add `@morsssss` to `@ampproject/reviewers-amphtml`

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#29571]
I'd like to nominate AMP's Developer advocate, @morsssss from `@ampproject/wg-outreach`, as a member of `@ampproject/reviewers-amphtml`.

He has merged [more than 60 PRs](https://github.com/pulls?q=is%3Apr+author%3Amorsssss+user%3Aampproject) to various repos under the `@ampproject` organization. Most recently, he rewrote large parts of the documentation for `amp-script` (#29487).

**Comment by mrjoro** [comment]
Done!
