### ISSUE TITLE
Add new members to `@ampproject/reviewers-amphtml`

### ISSUE THREAD

**Issue by morsssss** [ampproject/amphtml#29576]
I'd like to nominate three members of `@ampproject/wg-outreach` to also be members of `@ampproject/reviewers-amphtml`.

* @CrystalOnScript has merged [an incredible 191 issues](https://github.com/pulls?q=is%3Apr+author%3Acrystalonscript+user%3Aampproject+) to `ampproject` repos. She does an incredible amount of work on the AMP documentation.

* I thought 191 was a lot. But @sebastianbenz has merged a whopping [818 PRs](is:pr author:sebastianbenz user:ampproject) to `ampproject` repos. He's also the primary author of [@ampproject/toolbox-optimizer](https://github.com/ampproject/amp-toolbox/tree/main/packages/optimizer).

* Finally, @patrickkettner has created [41 PRs](https://github.com/search?q=is%3Apr+author%3Apatrickkettner+user%3Aampproject) in the `ampproject`. He's helped out with `<amp-script>` and is currently undertaking an effort to translate all our documentation into many new languages.

Submitted for your approval!

**Comment by mrjoro** [comment]
Done!

**Comment by sebastianbenz** [comment]
Thanks Ben! This is going to make our lives so much easier :-).
