### ISSUE TITLE
Ebay Affiliate Smart Placements

### ISSUE THREAD

**Issue by equilibriumxco** [ampproject/amphtml#29579]
Hello. @kristoferbaxter @choumx

This is the first time I am trying to use Amp-Script and I am confused on this particular need I have.
To place Ebay Affiliate Smart Placements I use the following
In the Head section of the template
<script async src="https://epnt.ebay.com/static/epn-smart-tools.js"></script>
In the article the specific campaign (Beauty products)
<ins class="epn-placement" data-config-id="5f1ea2786bfa2e622e082544"></ins>

I already placed the AMP project script in the Wbamp plugin header.
Now, my issue is how to write the amp-script for this particular case
I tried this 
<amp-script layout="container" async src="https://epnt.ebay.com/static/epn-smart-tools.js"><ins class="epn-placement" data-config-id="5f1ea2786bfa2e622e082544"></ins>
</amp-script>

But doesn't work. What will it be the correct way...??
You can use this URL as an example: https://www.equilibriumx.com/tips-en/dormir-con-mascotas-si-o-no/amp

Eduardo
www.equilibriumx.com

## Describe alternatives you've considered

Provide a clear and concise description of any alternative solutions or features you've considered.

**Comment by choumx** [comment]
`amp-script` was designed for interactive user content, not ads e.g. it won't update the DOM on load.

Looks like [Smart Placements](https://partnerhelp.ebay.com/helpcenter/knowledgebase/Smart-Placements-Quick-Start-Guide/) is a banner ad system -- you'll need an integration with `amp-ad` for this if it doesn't already exist. @ampproject/wg-ads-reviewers

**Comment by powerivq** [comment]
@equilibriumxco Unfortunately, amp-script would not work in your use case. https://amp.dev/documentation/components/amp-link-rewriter/ Maybe you would want to consider using amp-link-rewriter to rewrite your links to ebay affiliate links on AMP.

**Comment by equilibriumxco** [comment]
> `amp-script` was designed for interactive user content, not ads e.g. it won't update the DOM on load.
> 
> Looks like [Smart Placements](https://partnerhelp.ebay.com/helpcenter/knowledgebase/Smart-Placements-Quick-Start-Guide/) is a banner ad system -- you'll need an integration with `amp-ad` for this if it doesn't already exist. @ampproject/wg-ads-reviewers

Hello, I have amazon ads as well. I don't see Ebay as a type anywhere. Thats why I am asking for an alternative solution. I tried to experiment on different ways usingthe a9 type with ebay.. doesn't work
<amp-ad
  width="900"
  height="220"
  type="a9"
  ins class="epn-placement"
  data-recomtype="async"
  data-config-id="5f226caf3a3c375d61c3b943"
  data-regionurl="https://epnt.ebay.com/static/epn-smart-tools.js"
>
</amp-ad>

**Comment by powerivq** [comment]
> > `amp-script` was designed for interactive user content, not ads e.g. it won't update the DOM on load.
> > Looks like [Smart Placements](https://partnerhelp.ebay.com/helpcenter/knowledgebase/Smart-Placements-Quick-Start-Guide/) is a banner ad system -- you'll need an integration with `amp-ad` for this if it doesn't already exist. @ampproject/wg-ads-reviewers
> 
> Hello, I have amazon ads as well. I don't see Ebay as a type anywhere. Thats why I am asking for an alternative solution. I tried to experiment on different ways usingthe a9 type with ebay.. doesn't work
> <amp-ad
> width="900"
> height="220"
> type="a9"
> ins class="epn-placement"
> data-recomtype="async"
> data-config-id="5f226caf3a3c375d61c3b943"
> data-regionurl="https://epnt.ebay.com/static/epn-smart-tools.js"
> 
> >

With respect to smart placement, it does not look like eBay currently supports amp-ad, and therefore smart placement will not work with amp. Maybe you can bring it up with eBay? If they want to build an amp integration, people will be able to use these features on an amp page

**Comment by equilibriumxco** [comment]
> > > `amp-script` was designed for interactive user content, not ads e.g. it won't update the DOM on load.
> > > Looks like [Smart Placements](https://partnerhelp.ebay.com/helpcenter/knowledgebase/Smart-Placements-Quick-Start-Guide/) is a banner ad system -- you'll need an integration with `amp-ad` for this if it doesn't already exist. @ampproject/wg-ads-reviewers
> > 
> > 
> > Hello, I have amazon ads as well. I don't see Ebay as a type anywhere. Thats why I am asking for an alternative solution. I tried to experiment on different ways usingthe a9 type with ebay.. doesn't work
> > <amp-ad
> > width="900"
> > height="220"
> > type="a9"
> > ins class="epn-placement"
> > data-recomtype="async"
> > data-config-id="5f226caf3a3c375d61c3b943"
> > data-regionurl="https://epnt.ebay.com/static/epn-smart-tools.js"
> > >
> 
> With respect to smart placement, it does not look like eBay currently supports amp-ad, and therefore smart placement will not work with amp. Maybe you can bring it up with eBay? If they want to build an amp integration, people will be able to use these features on an amp page

I just created a case in Ebay Affiliate and they escalated it to a technical support team since the customer support has no idea what AMP means... I will post here their solution for everyone to see
cheers, mate
