### ISSUE TITLE
amp-story: Sometimes there is a slight gray line on every page

### ISSUE THREAD

**Issue by merapi** [ampproject/amphtml#29583]
## What's the issue?

Sometimes there is a slight gray line on every page when you resize the browser on a desktop.

![Screenshot 2020-07-30 at 09 40 58](https://user-images.githubusercontent.com/21036224/88896308-f69ab100-d249-11ea-905f-bff390e1d382.png)
![Screenshot 2020-07-30 at 09 38 08](https://user-images.githubusercontent.com/21036224/88896318-fa2e3800-d249-11ea-835c-8cd37fc2dc85.png)

## How do we reproduce the issue?

Probably can be any story (used [this](https://joshmuskin.com/stories/1-year-ironman-training-plan/))

1. Resize the window a few times (on desktop)

## What browsers are affected?

Easily reproducible on Chrome, harder on Firefox/Safari.

## Which AMP version is affected?

Not sure, all versions?

**Comment by merapi** [comment]
This was initially found/reported by @pbakaus on #google-web-stories Slack.

I have done an initial investigation:

Because we use `aspect-ratio` attr, we have 2 extra vars from AMP and those are set using `clientWidth` which does this:
>Note: This property will round the value to an integer. If you need a fractional value, use element.getBoundingClientRect().

in my test case it’s `382`
at the same time `amp-story-page` has `max-width: 45vh!important` which in my case translates to `382.95`.

On emulated mobile device there is no `.i-amphtml-story-desktop-panels` which has this `max-width: calc(3/5 * 75vh) !important` so no gray line there.

**Comment by swissspidy** [comment]
AFAIK this is still an issue

**Comment by swissspidy** [comment]
AFAIK this is still an issue
