### ISSUE TITLE
Support for AdSense host parameter (host API) in <amp-ad>

### ISSUE THREAD

**Issue by AltervistaTechStaff** [ampproject/amphtml#2958]
Hi, we have direct support from Google AdSense, due to our partnership program.

Currently, we have about 40,000 AdSense accounts in our hosting platform associated to our host publisher id.

To start supporting AMP pages, we need to have something like this working:

    <amp-ad width="320" height="200"
        type="adsense"
        data-ad-client="ca-pub-XXXXXXX"
        data-ad-slot="XXXXXXX">
        data-ad-host="pub-9280273811890686"
    </amp-ad>

(notice the host publisher id is real, just as a reference)

Unfortunately, that won't even validate at the moment.

The code in https://github.com/ampproject/amphtml/blob/master/ads/google/adsense.js should have something like this:

    /**
    * @param {!Window} global
    * @param {!Object} data
    */
    export function adsense(global, data) {
    checkData(data, ['adClient', 'adSlot', 'adHost']);

[...]

    const i = global.document.createElement('ins');
    i.setAttribute('data-ad-client', data['adClient']);
    if (data['adSlot']) {
      i.setAttribute('data-ad-slot', data['adSlot']);
    }
    if (data['adHost']) {
      i.setAttribute('data-ad-host', data['adHost']);
    }

So it seems quite trivial to do.

We have already contacted the AdSense team on our own, and they suggested to report an issue on  Github.

Kind regards,
Altervista TechStaff

**Comment by jridgewell** [comment]
Kinda related to https://github.com/ampproject/amphtml/issues/2870.

**Comment by bobcassels** [comment]
That's a good idea. I will implement it.

**Comment by ericlindley-g** [comment]
@bobcassels , Can this be closed with PR #3027 merged?

**Comment by bobcassels** [comment]
Yes, data-ad-host is implemented, as they suggested. Please close.
