### ISSUE TITLE
[amp player]: Render timeout on multiple stories

### ISSUE THREAD

**Issue by rnkimani** [ampproject/amphtml#29584]
## What's the issue?
- While loading multiple stories in the amp player, I sometimes get render timeout errors.
- In the console the error displayed is ` Uncaught Error: Render timeout waiting for service amp-story-render to be ready.`

## How do we reproduce the issue?
- Add multiple stories to the `<amp-player></amp-player>` and try going to the next story using a swipe event or clicking through. 
- It sometimes doesn't render the next story until another click event. At this point the error being displayed is `Received user action in non-visible doc.`

## What browsers are affected?
- Chrome Version 84.0.4147.105 (Official Build) (64-bit)

## Which AMP version is affected?
- v0

cc @Enriqe

**Comment by Enriqe** [comment]
These error messages shouldn't conflict with the stories' functionality, but we should probably handle the `Received user action in non-visible doc` one.
 
I'll prioritize https://github.com/ampproject/amphtml/issues/29320, which should significantly reduce these errors.

**Comment by rnkimani** [comment]
I agree.
Before showing the timeout message does it do a retry to re-render the doc? Because it's interesting how it doesn't rerender but when clicking on the 'invisible doc' it shows the story.

**Comment by Enriqe** [comment]
The messages shouldn't prevent the doc from rendering, it just warns that they have passed the timeout amount. They should still render after the message displays. If you wait a little bit more, do the stories render after the message is shown?

**Comment by Enriqe** [comment]
@rnkimani are you still seeing these errors often? Hopefully #29703 helped alleviate a good number of them. I'll close this issue but will re-open if appropriate.

**Comment by rnkimani** [comment]
Yes this is fixed.
