### ISSUE TITLE
[amp-story] RTL: share icon should be on the left in desktop

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#29588]
https://www.gstatic.com/amphtml/stamp/qa/rtl.html

On desktop:
expected: share icon should be on the left
actual: share icon is on the right

![image](https://user-images.githubusercontent.com/5449100/88944642-ff47b300-d25a-11ea-9cca-753dbae76e1b.png)

**Comment by Ichigo3d** [comment]
in mobile view of Chrome desktop it is placed on left side.

**Comment by Enriqe** [comment]
@Ichigo3d yep, this is regarding the desktop version
