### ISSUE TITLE
[Story 360] Pause animation on long press

### ISSUE THREAD

**Issue by t0mg** [ampproject/amphtml#29593]
Implement long press behavior: pause the any currently playing animation 

cc @ampproject/wg-stories

**Comment by t0mg** [comment]
I noticed in #30290 ([demo](https://stories-360.web.app/examples/amp-story-360.amp.html)) that the video pauses naturally so we got that going for us already. I was wondering if we should also pause the gyroscope when that feature is enabled. Rationale:  I've asked about toggling off the gyroscope with a UI button similar to the audio one, but that idea was dismissed. The ability to freeze the gyro when viewing the story in the subway or somewhere where one would not be comfortable pointing their device at the horizon would totally be a fringe case but a nice detail nevertheless.

**Comment by processprocess** [comment]
> The ability to freeze the gyro when viewing the story in the subway or somewhere where one would not be comfortable pointing their device at the horizon would totally be a fringe case but a nice detail nevertheless.

We're thinking of creating a gyroscope control UI which might help solve this.
This would likely be part of the next version of the 360 component.
