### ISSUE TITLE
Use own cache instead of google cache

### ISSUE THREAD

**Issue by brusco77** [ampproject/amphtml#2959]
Hi, in some introductory AMP pages, it's said that one can use his own cache instead of google cache.

Howeverm I cant find that throughout documentation: how can I disable google cache on my pages?

thank you

**Comment by rudygalfi** [comment]
There's some information on this at https://www.ampproject.org/docs/support/faqs.html:

> By using the AMP format, content producers are making the content in AMP files available to be cached by third parties. Under this type of framework, publishers continue to control their content, but platforms can easily cache or mirror the content for optimal delivery speed to users.

So, by using AMP the content is able to be cached by anyone, including Google, so there's no ability to "disable" caching from Google.

**Comment by rudygalfi** [comment]
Also, note that the original publisher continues to serve the content, so if you use a caching solution in the path of serving the original file, you can continue to do that, independent of caching by Google or anyone else.
