### ISSUE TITLE
AMP shadows broken due AMP doc being activated on interaction

### ISSUE THREAD

**Issue by oliverfernandez** [ampproject/amphtml#29608]
This bug has been introduced when the issue #28227 has been fixed in the PR #28807

SInce now an AMP document is set to `visible` when the users interacts with `window`, those websites that use AMP shadows does not have control over the `visibilityState` of the `ampdoc` since it automatically switches to `visible`

I understand that this "visible on user interaction" behaviour is not necessary in AMP shadow mode.

The fix should be as easy as checking here `this.ampdoc.isSingleDoc() === true` before calling `visibleOnUserAction_()` method, and I was going to open a PR for it.

However I just saw that it seems that the method `isSingleDoc` is being deprecated, and there's a new `ampdoc FIE` that I'm not familiar with, so I'm not sure which should be the right fix.

**Comment by oliverfernandez** [comment]
cc/ @dvoytenko

**Comment by dvoytenko** [comment]
@oliverfernandez `isSingleDoc` can indeed be used here. I'd appreciate the pull request. The `isSingleDoc` is not being deprecated, it's just being renamed. The meaning will change slightly, but not for this use case. Ampdoc FIE is not relevant here - those are just ads. They've always existed, but now they are just more standardized.

**Comment by oliverfernandez** [comment]
Got it!

I'll send the PR ASAP. Thanks!!

**Comment by oliverfernandez** [comment]
@dvoytenko PR ready!

**Comment by dvoytenko** [comment]
Thanks a lot! Merged!

**Comment by lannka** [comment]
A side note: this issue was also seen on amp-next-page causing more unnecessary ad requests . fixed by the same PR. thank you @oliverfernandez
