### ISSUE TITLE
Switch to polling free font loading polyfill

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#2960]
For `amp-font`.

See http://smnh.me/web-font-loading-detection-without-timers/ for the technique. It relies on the content change from the font having loaded causing a scroll event.

**Comment by ericlindley-g** [comment]
Putting in backlog, but feel free to update the issue or let me know if you have a more concrete milestone in mind

**Comment by sriramkrish85** [comment]
we would not need this on IOS 10 (we already dont need this on android). Will test and close this is that is the case.

**Comment by cramforce** [comment]
+1 with native support in iOS10 (lets hope it works), we should not invest
in making the fallback better.

**Comment by sriramkrish85** [comment]
just checked this on IOS 10 - Safari (10). The new fonts api is supported as expected. (FF and chrome already support this). So we wont be improving the polyfill.

CC @cramforce
