### ISSUE TITLE
amp-list / amp-carousel: Inappropriate ARIA live regions

### ISSUE THREAD

**Issue by TetraLogicalHelpdesk** [ampproject/amphtml#29611]
## WCAG Level
Level A

## Priority
Critical

## Type
Notifications

## Pages/Components affected
* [amp-list](https://amp.dev/documentation/components/amp-list/)
* [amp-carousel](https://amp.dev/documentation/components/amp-carousel/)

## Description
Currently, both `<amp-list>` and `<amp-carousel>` are rendered as ARIA live regions, with the inclusion of an `aria-live="polite"` attribute. Once an element is designated as a live region, any changes to the content of the element is explicitly announced by assistive technologies (such as screen readers). However, this leads to the following problems with `<amp-list>` and `<amp-carousel>`:

* due to the way lists and carousels are dynamically rendered, on any page that contains one of these elements the list or carousel content will be announced immediately when the page is loaded (presumably because the container element, designated as a live region, is generated first, and then its content is dynamically injected/rendered inside it). This leads to a confusing/nonsensical experience for assistive technology users, who will hear the contents of those elements be read out, in full, completely out of context once the page is loaded - before any of the other content on the page.
* when a list item is dynamically added/removed from an `<amp-list>`, the entire content of the list (including all elements that are unchanged) will be announced again, in full, to the user.
* in `<amp-carousel type="slides">` carousels, whenever the currently visible slide changes, the entire contents of the newly visible slide is announced. In the case of carousels with `autoplay`, this results in a constant live announcement of the newly displayed slide.

## User impact
For an assistive technology user, having the content of any list or carousel announced out of sequence, right on page load, will be extremely confusing. Hearing the entire content of the list announced again when an item is added/removed will be extremely verbose (particularly when list individual list items are complex). In the case of autoplaying slide carousels, the constant announcement of the newly displayed slide content will be distracting at best, but can (depending on the amount of content in the slide and the `delay` used for the `autoplay`) make the page completely unusable.

## Required solution
We recommend completely removing the `aria-live="polite"` that is generated by default for `<amp-list>` and `<amp-carousel>`. If you want to convey a particular change explicitly to assistive technologies (for instance, when a list has been updated), use a separate (visually hidden, but accessible) container element, set to `aria-live="polite"`, and use this to dynamically generate announcements for assistive technologies. Keep those announcements short and to the point.

To convey that a list has changed, use announcements such as "list updated", "item added", or similar. Don't fire these announcements on page load when the list if first rendered, but reserve these for subsequent changes after the initial render.

For slide carousels, consider short announcements to indicate when a new slide is shown (rather than announcing the entire content of the slide). However, to avoid having the `autoplay` carousel constantly announcing its changes, only trigger these announcements if the user is currently interacting with the carousel itself (i.e. if their focus is currently inside the carousel).

## Test procedure(s)
Use these steps to confirm that the solution has been correctly applied:
1. Turn on your screen reader
2. Load a page with an `<amp-list>` or `<amp-carousel>`
3. Verify that, on load, the content of the list or carousel is not automatically announced
4. Load a page with an `<amp-carousel type="slides">`
5. Verify that changing slides does not lead to the entire slide content being announced

Once short/specific announcements have been implemented for lists and carousels:
1. Turn on your screen reader
2. Load a page with an `<amp-list>` where the list items can change
3. Verify that when a list item is added or removed, the change is announced by the screen reader (e.g. "list updated")
4. Load a page with an `<amp-carousel type="slides">`
5. Verify that changing slides only leads to a short announcement (e.g. "Showing slide 1 of 3")
6. Verify that if the carousel has `autoplay`, these short announcements only happen when keyboard focus is inside the carousel

## Related standards
* [WCAG 2.1 Success Criterion 4.1.2 Name, Role, Value (Level A)](https://www.w3.org/TR/WCAG21/#name-role-value)

## More information
* [MDN - ARIA live regions](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions)
* [W3C WAI tutorials - Carousels / Functionality](https://www.w3.org/WAI/tutorials/carousels/functionality/)

## Test data
Test date: July 2020

**Comment by zhouyx** [comment]
I'll break the issue to two `<amp-list>` and `<amp-carousel>`. and I'll start with `<amp-list>` first.
