### ISSUE TITLE
<amp-script>: Fix and improve error messages for script hash

### ISSUE THREAD

**Issue by morsssss** [ampproject/amphtml#29614]
There are a few things here!

### Changed amp.dev link ###

The error message currently says, `See https://amp.dev/documentation/components/amp-script/#security-features.​​​`. In fact, in https://github.com/ampproject/amphtml/pull/29487, we changed this link to `See https://amp.dev/documentation/components/amp-script/#script-hash.​​​`

Can we update the link in error messages?

### Incorrect message for incorrect script hash ###
If you happen to get the script hash for `<amp-script>` wrong, you might expect to get an error message that says something like, `Script hash for <amp-script> is incorrect. You must include <meta name="amp-script-src" "sha384-...">`

Instead, what you see is this:

`amp-script Script hash not found. amp-script[script="user-agent-script"].js must have "sha384-2pF8pO53GSTphKniorRl5ubWFfal7Bwf7_jBq8_r-SaaoT14q0gAOBzro5gndckK" in meta[name="amp-script-src"].`

This situation can easily happen - if you update your inline JavaScript, you'll get this error unless you're also using tooling to update the hash.

### Using that wording for missing script hash, too ###
I wouldn't have requested this change independently, but if you like the wording above, you might want to use something similar for a missing script hash. Like:

`Script hash for <amp-script> is missing. You must include <meta name="amp-script-src" "sha384-...">`

Or:

`<amp-script>: Missing script hash. You must include <meta name="amp-script-src" "sha384-...">`

### Uncaught error ###

It would also be DX-positive if this error was caught, so the developer didn't see an additional error in the console, like this:

![image](https://user-images.githubusercontent.com/29419498/89062200-08588300-d334-11ea-87e8-ce3cf0a00db1.png)

/cc @samouri , @sebastianbenz

**Comment by sebastianbenz** [comment]
+100 to making the correct script hash html tag copy pasteable

**Comment by morsssss** [comment]
If we can just quickly update the amp.dev link mentioned in the error message, that would be a great start, independent of the other requests mentioned here. Right now the link does go to the right page, but because the hash has changed, it no longer goes to the part that describes the script hash.

**Comment by samouri** [comment]
@morsssss: its unclear to me when we'd show the "incorrect hash" vs. the "not found" for cases where there are > 1 <amp-script>s on the page. I've made the other few changes though and hope they improve the situation!

Namely:
1. Copy/pasteable html tag in the error
2. Removed the uncaught exception error
3. Fixed the link to more info
