### ISSUE TITLE
SERP Locking on iOS 13.5.1 Safari

### ISSUE THREAD

**Issue by candice-womp** [ampproject/amphtml#29625]
## What's the issue?

If a user tries to hard scroll up an SERP after it loads it will lock the page making the user unable to scroll up or down the page. Here is a video where you can see the issue: https://www.dropbox.com/s/gtbndobbowra8ej/serp_issue.mp4?dl=0

## How do we reproduce the issue?

Example URLs where you can look at this issue:

- https://www.google.com/amp/s/amp.direct.asda.com/munchkin-wonder-waterway/002696472,default,pd.html
- https://www.google.com/amp/s/amp.direct.asda.com/george/clothing/10,default,sc.html
- https://www.google.com/amp/s/amp.capitalfund1.com/

## What browsers are affected?

This happens on iPhone X with iOS 13.5.1 on the Safari browser.

## Which AMP version is affected?

Version 2007172306003

**Comment by choumx** [comment]
I've seen this occasionally too so it's possibly a very old bug. Seems like over-scrolling on the viewer page instead of the iframed AMP page.

@ampproject/wg-viewers Have we had any other reports about this?

**Comment by ericfs** [comment]
Thanks for the video. Filed internal b/164429446.
