### ISSUE TITLE
Unavailable resource linked in Ad Network Integration guide

### ISSUE THREAD

**Issue by kbnaik** [ampproject/amphtml#2962]
a9.js link here: https://github.com/ampproject/amphtml/blob/master/ads/integration-guide.md is pointing to an unavailable resource. Throwing 404. 

## How do we reproduce the issue?

Go to the link and click on the hyperlink a9.js (see screenshot attached)
![a9_missin_resource](https://cloud.githubusercontent.com/assets/11433063/14722572/f733beb6-07c0-11e6-84c7-32437ddc10a1.png)

Repro steps:

1. https://github.com/ampproject/amphtml/blob/master/ads/integration-guide.md
2. Click on a9.js
3. See 404 at redirect URL

## What browsers are affected?

Browser independent

## Which AMP version is affected?

N/A

Not sure how long it has been 404, it recently came to our attention. 
Appropriate resource here: https://github.com/ampproject/amphtml/blob/master/ads/a9.js

**Comment by ericlindley-g** [comment]
@jridgewell , looks like you're working on this now, so slotted in the current sprint and assigned to you, but feel free to update or let me know if any of that is off.
