### ISSUE TITLE
Ads with fixed-height attribute not rendering as they were previously

### ISSUE THREAD

**Issue by jamesozzie** [ampproject/amphtml#29637]
As reported by @webzunft ad units using the `fixed-height` layout attribute are not appearing until a `width:auto` rule is applied. 

Ads using the same format were appearing fine previously. See image below of current ad snippets:
![image](https://user-images.githubusercontent.com/41326532/89203964-490f0100-d5ad-11ea-8da9-10f1d870c88e.png)

Live example can be found [here](https://oi.ie/ad-sample/).

Console error below:
`Failed to load resource: the server responded with a status of 400 ()`

Worth nothing that in my case adding `width:auto` doesn't result in any ads appearing.

![ads](https://user-images.githubusercontent.com/41326532/89205724-10245b80-d5b0-11ea-873f-c406417ff7b7.gif)

## What's the issue?

As above, ads not rendering when using the fixed-height layout attribute. 

## How do we reproduce the issue?

Ad the following ad code into a site (replacing the AdSense account ID)

```
<amp-ad type="adsense" 
  data-ad-client="ca-pub-******" 
  data-ad-slot="321321" 
  layout="fixed-height" 
  height="320">
</amp-ad>
```

## What browsers are affected?

All browsers

## Which AMP version is affected?

This started occurring recently, no conclusive date.

**Comment by webzunft** [comment]
Thanks, @jamesozzie.
I just wanted to add that [this doc page](https://amp.dev/documentation/guides-and-tutorials/learn/amp-html-layout/?format=websites#layout) states that the `fixed-height` value for the `layout` attribute does not require a `width` attribute. Just in case that behavior changed, at least the manual needs an update.
