### ISSUE TITLE
amp-story: [aspect-ratio] with fewer surprises

### ISSUE THREAD

**Issue by dreamofabear** [ampproject/amphtml#29640]
### Motivation

As a story creator, I want to be able to author content in a fixed aspect ratio that:
1. Never has horizontal letterboxing (crops top/bottom with vertical centering around the "safe zone" instead)
2. Doesn't have letterboxing on desktop
3. Doesn't use hacky workarounds (see "Workaround" below)

### Status quo

`amp-story-grid-layer[aspect-ratio] == "9:16"` in a 2:3 mobile viewport has horizontal letterboxing (point 1).

<img width="456" alt="Screen Shot 2020-06-30 at 4 56 14 PM" src="https://user-images.githubusercontent.com/20525523/89209704-d2faa200-d58c-11ea-992c-a5917a0227d3.png">

`amp-story-grid-layer[aspect-ratio] = "9:16"` on desktop viewport has letterboxing (point 2).

<img width="631" alt="Screen Shot 2020-06-30 at 3 43 11 PM" src="https://user-images.githubusercontent.com/20525523/89209821-076e5e00-d58d-11ea-9c15-5943e72f643f.png">

## Workaround

1. Author my content in 9:16 but set `aspect-ratio="2:3"`
2. Override default CSS to set `amp-story-grid-layer { overflow: visible; }`
3. Create a child container div with 9:16 height 
  a. CSS: `height: { calc(2 / 3 * 16 / 9) * 100% }` and `top: { calc(1 - calc(2 / 3 * 16 / 9) / 2 * 100%)  }`
4. Replace any usages of `--story-page-vh` with `calc(--story-page-vw * 16 / 9)`
  a. Note that `--i-amphtml-story-layer-height` is also imprecise (2:3 height instead of 9:16 height)

## Proposal

`amp-story-grid-layer[aspect-ratio]` doesn't satisfy the above points because grid-layer never allows its content to be cropped. This might be a reasonable semantic invariant for grid-layer.

Instead of changing behavior, we can add a new `[aspect-ratio]` attribute to `amp-story-page`. This also has the added benefit that `--story-page-vh` will be precise/useful.

Playing around with it, adding the following CSS on `amp-story-page` appears to work for desktop and mobile: 
<img width="507" alt="Screen Shot 2020-07-31 at 11 17 11 PM" src="https://user-images.githubusercontent.com/20525523/89212553-a39a6400-d591-11ea-95af-91e24f6bb4dc.png">

Caveat: there appears to be some hardcoded ads code that assumes story size on desktop is (45vh, 75vh).

**Comment by dvoytenko** [comment]
For WP stories we worked out a safe/fullbleed zone approach. See https://github.com/google/web-stories-wp/issues/1245 (see the prototype attached to there). It's constructed as basically putting a 9:16 container inside a 2:3 container. I.e. it looks like this:

```
<div 2:3>
  <div 9:16>
    ...
  </div>
</div>
```

It's aimed to solve for:
1. The safe zone is always fully visible on any screen.
2. The fullbleed zone is always aligned the same way with the safe zone.
3. With 2:3 ratio, the margins "almost never" show.

These are just a set of compromises we took. This is a rather opinionated layout, so the Stories decided not to adopt it, or at least not yet. Instead we just took the top part - the ability to set the top-level aspect ratio and implemented in the format as a bare necessary minimum. This implementation follows the upcoming Aspect Ratio CSS so once that becomes widely available, can be simply replaced with it.

**Comment by choumx** [comment]
Thanks, yea that's the workaround I mentioned. There are a couple downsides e.g. desktop view is always 9:15 which results in minor vertical cropping.

**Comment by newmuis** [comment]
I'd like to advocate for introducing it at the story level rather than the page level; it's definitely ok to have layers with different aspect ratios, and probably ok to have stories with different aspect ratios, but a single story whose pages have different aspect ratios seems undesirable to me.

**Comment by dvoytenko** [comment]
> Thanks, yea that's the workaround I mentioned. There are a couple downsides e.g. desktop view is always 9:15 which results in minor vertical cropping.

Correct. And the vertical cropping was deemed by us acceptable since we usually require a fullbleed background. One thing I forgot to mention: that model allows to parametrize alignment of the safe zone within the viewport. It can be aligned to the top, bottom, or centered. I believe we are currently only centering it, but it's pretty trivial to customize it.

**Comment by mszylkowski** [comment]
I've somehow missed this FR (stalebot surfaced it after 1.5 years) but we've introduced https://amp.dev/documentation/components/amp-story-grid-layer/#modern-aspect-ratio presets that behave really well with all the current surfaces for stories, and it looks like it could do what the FR asks for, and more. It essentially gives you a background layer (that will never have letterboxing on mobile) and a foreground layer (that could have letterboxing, but the background layer will cover it). It should help with the responsiveness issues and there are a few examples on the `examples/amp-story` folder and in the documentation
