### ISSUE TITLE
[amp-story] Support opt-out from localStorage

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#29645]
We should support adding a URL parameter that, when provided, opts-out of using local storage. Use case is that some users want to restart the story from the first page when opened in a different tab / context.

**Comment by gmajoulet** [comment]
Is this a Player feature or just a story feature?

**Comment by Enriqe** [comment]
I guess there's work in both sides (we could provide an attribute in the player that applies the fragment param to all stories inside of it) but yep, mainly on the story side.
