### ISSUE TITLE
`amp-consent` does not work when not using `checkConsentHref`

### ISSUE THREAD

**Issue by claudiulodro** [ampproject/amphtml#29662]
## What's the issue?

There seems to be an issue with `amp-consent` and the `geoOverride` setting incorrectly excluding the `consentRequired` setting when no `geoOverride` is defined and `consentRequired` is used without `checkConsentHref` (This is better explained by looking at the code sample below). With this configuration, the geo settings get parsed into a setting that contains no `consentRequired` setting, so it gets caught in [this check](https://github.com/ampproject/amphtml/blob/master/extensions/amp-consent/0.1/consent-config.js#L235-L236) and incorrectly throws a "`consentRequired` is required" error, breaking the `amp-consent` element.

The underlying use-case here is an AMP-compatible cookie notice that purely uses local storage. This is an important use-case, as sites with many visitors cannot use `consentRequired: 'remote'` for this sort of cookie notice. Using a remote endpoint sends an un-cacheable HTTP request on every pageload to determine whether a user has consented and causes heavy server load.

## How do we reproduce the issue?

[You can view the super basic example below at this AMP Playground URL.
](https://playground.amp.dev/#share=PCFkb2N0eXBlIGh0bWw+CjxodG1sIOKaoT4KPGhlYWQ+CiAgPG1ldGEgY2hhcnNldD0idXRmLTgiPgogIDx0aXRsZT5NeSBBTVAgUGFnZTwvdGl0bGU+CiAgPGxpbmsgcmVsPSJjYW5vbmljYWwiIGhyZWY9InNlbGYuaHRtbCIgLz4KICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLG1pbmltdW0tc2NhbGU9MSxpbml0aWFsLXNjYWxlPTEiPgogIDxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoOy1tb3otYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1zLWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoO2FuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RofUAtd2Via2l0LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1vei1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1tcy1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1vLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1Aa2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fTwvc3R5bGU+PG5vc2NyaXB0PjxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjpub25lOy1tb3otYW5pbWF0aW9uOm5vbmU7LW1zLWFuaW1hdGlvbjpub25lO2FuaW1hdGlvbjpub25lfTwvc3R5bGU+PC9ub3NjcmlwdD4KICA8c2NyaXB0IGFzeW5jIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAuanMiPjwvc2NyaXB0PgogIDxzY3JpcHQgYXN5bmMgY3VzdG9tLWVsZW1lbnQ9ImFtcC1jb25zZW50IiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1jb25zZW50LTAuMS5qcyI+PC9zY3JpcHQ+CiAgPHNjcmlwdCBhc3luYyBjdXN0b20tZWxlbWVudD0iYW1wLWZvcm0iIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAvYW1wLWZvcm0tMC4xLmpzIj48L3NjcmlwdD4KICA8c3R5bGUgYW1wLWN1c3RvbT4KICAgIGgxIHsKICAgICAgbWFyZ2luOiAxcmVtOwogICAgfQogIDwvc3R5bGU+CjwvaGVhZD4KPGJvZHk+CiAgCTwhLS0gVGhpcyB3aWxsIHRyaWdnZXIgYSAiYGNvbnNlbnRSZXF1aXJlZGAgaXMgcmVxdWlyZWQiIGVycm9yIGRlc3BpdGUgY29uc2VudFJlcXVpcmVkIGJlaW5nIGRlZmluZWQgYW5kIHBhc3NpbmcgQU1QIHZhbGlkYXRpb24uIC0tPgoJPCEtLSBAc2VlIGh0dHBzOi8vZ2l0aHViLmNvbS9hbXBwcm9qZWN0L2FtcGh0bWwvYmxvYi9tYXN0ZXIvZXh0ZW5zaW9ucy9hbXAtY29uc2VudC8wLjEvY29uc2VudC1jb25maWcuanMjTDIzNS1MMjM2IC0tPgoJPGFtcC1jb25zZW50IGlkPSJ3cC1nZHByLWNvb2tpZS1ub3RpY2Utd3JhcCIgY2xhc3M9IndwLWdkcHItY29va2llLW5vdGljZS13cmFwIiBsYXlvdXQ9Im5vZGlzcGxheSI+CgkJPHNjcmlwdCB0eXBlPSJhcHBsaWNhdGlvbi9qc29uIj4KCQkJewogICAgICAgICAgICAJImNvbnNlbnRzIjp7CiAgICAgICAgICAgICAgICAJIndwLWdkcHItY29va2llLW5vdGljZSI6ewogICAgICAgICAgICAgICAgICAgIAkiY29uc2VudFJlcXVpcmVkIjp0cnVlLAogICAgICAgICAgICAgICAgICAgICAgICAicHJvbXB0VUkiOiJ3cC1nZHByLWNvb2tpZS1ub3RpY2UiCiAgICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgfQogICAgICAgICAgICB9CgkJPC9zY3JpcHQ+CgkJPGRpdiBpZD0id3AtZ2Rwci1jb29raWUtbm90aWNlIiBjbGFzcz0id3AtZ2Rwci1jb29raWUtbm90aWNlIiByb2xlPSJhbGVydCIgYXJpYS1sYWJlbD0iQ29va2llIENvbnNlbnQgTm90aWNlIj4KCQkJPGgxPgogICAgICAgICAgICAgIENvb2tpZSBub3RpY2UhCiAgICAgICAgICA8L2gxPgogICAgCTwvZGl2PgogIDwvYW1wLWNvbnNlbnQ+CjwvYm9keT4KPC9odG1sPgo=)
At the AMP Playground, open the browser JS console and observe the error thrown.

#### Here are step-by-step instructions to reproduce the issue:

1. Create the following `amp-consent` element:
```
<amp-consent id="wp-gdpr-cookie-notice-wrap" class="wp-gdpr-cookie-notice-wrap" layout="nodisplay">
    <script type="application/json">
        {
            "consents":{
                "wp-gdpr-cookie-notice":{
                    "consentRequired":true, 
                    "promptUI":"wp-gdpr-cookie-notice"
                 }
           }
        }
    </script>
    <div id="wp-gdpr-cookie-notice" class="wp-gdpr-cookie-notice">
        <h1>Cookie notice!</h1>
    </div>
</amp-consent>
```
2. In the browser JS console observe error is thrown and the consent prompt is not displayed:

<img width="647" alt="Screen Shot 2020-08-04 at 11 33 09 AM" src="https://user-images.githubusercontent.com/7317227/89331299-5e843980-d646-11ea-8ecd-28a3cfdca6eb.png">

**Note**: The same error also happens if you use `"consentRequired": false`, or if you use `"consentRequired: 'remote'` without a corresponding `checkConsentHref` setting defined. In the latter situation, I'd expect an error about `checkConsentHref` not being defined would be thrown instead of this error.

## What browsers are affected?

All browsers

## Which AMP version is affected?

I tested with `2007172306003`, however the issue still seems present in the code of the master branch as far as I can tell.

**Comment by claudiulodro** [comment]
Adding onto the above issue, I attempted a workaround by adding a global geo group: 
```
    <script type="application/json">
        {
            "consents":{
                "wp-gdpr-cookie-notice":{
                    "consentRequired":true, 
                    "promptUI":"wp-gdpr-cookie-notice",
                    "geoOverride":{ 
                        "default":{
                             "consentRequired":true
                        }
                     }
                 }
              }
           }
        }
    </script>

```

This continues to throw the same error.

**Comment by claudiulodro** [comment]
Further follow up: I believe the issue happens only when using a certain format of consent configuration. The following `amp-consent` element works nicely:

```
<amp-consent id="myUserConsent"
  layout="nodisplay">
  <script type="application/json">
    {
      "consentInstanceId": "consent-id",
      "consentRequired": true,
      "promptUI": "consentDialog"
    }
  </script>
  <div class="popupOverlay"
    id="consentDialog">
      <h2>Headline</h2>
    </div>
</amp-consent>
```

However when using this form of configuration, the element (erroneously) fails to build:
```
<amp-consent id="myUserConsent"
  layout="nodisplay">
  <script type="application/json">
    {
        "consents":{
            "consent-id":{
                "consentRequired":true, 
                "promptUI":"consentDialog"
            }
        }
    }
  </script>
  <div class="popupOverlay"
    id="consentDialog">
      <h2>Headline</h2>
    </div>
</amp-consent>
```

I can use the configuration format that works in the meantime, so not a huge hurry, but I believe it is a valid bug that the second form of configuration fails to build.

**Comment by micajuine-ho** [comment]
> bug that the second form of configuration fails to build.

Hi @claudiulodro, thanks for your report! The `consents` object is deprecated, as we now only support a single consent instance. Please let me know if you need help setting up your [consent config](https://github.com/ampproject/amphtml/blob/master/extensions/amp-consent/amp-consent.md#consent-instance).

**Comment by claudiulodro** [comment]
Good to know. Thanks for quickly following up. This issue can be closed. Just a heads-up, there is [at least one place in the official docs](https://amp.dev/documentation/components/amp-consent/#post-prompt-ui-(optional)) using the deprecated `consents` object and no mention of this deprecation on there that I can find.
