### ISSUE TITLE
Access: consider eliding option for restricted sections

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#2967]
Instead of completely hiding sections marked up with `amp-access-hide`, add an eliding mode that would blur them out and make them unreadable via `amp-access-hide="elide"` markup. See the attached image as an example:

<img width="217" height="345" style="border: 1px solid gray;" alt="screen shot 2016-04-22 at 8 59 52 am" src="https://cloud.githubusercontent.com/assets/726049/14747384/b8b24c0e-0868-11e6-8d20-6ff92faabb01.png">

Also, see the following jsbin as a prototype: https://jsbin.com/maxabi/2/edit?html,css,output

One "problem" with this approach is that "login" links and other access-related markup need to be displayed over the blurred out content - ideally using `position:sticky`, which is not yet supported in some browsers.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
