### ISSUE TITLE
Intent to implement: Server-side access protocol

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#2968]
The details TBD

**Comment by dknecht** [comment]
It looks like some code has been committed.  Can you explain more of what the CDN will do in this case?

**Comment by dvoytenko** [comment]
@dknecht Still working on the details. But we are currently exploring with the CDN initially sending pre-filtered document with only sections that are initially visible and then sending the rest on the second authorization request.

**Comment by adelinamart** [comment]
Is this still work in progress?

**Comment by dvoytenko** [comment]
Yes.

**Comment by petitpress** [comment]
Hi, according to https://www.ampproject.org/roadmap/ this should be in limited-beta right now. Is it so? If yes can we contribute in testing? If no, when it will be ready?

**Comment by amithgeorge** [comment]
Any updates on this? I came here from the roadmap page. Really looking forward to this feature.

**Comment by trodrigues** [comment]
@dvoytenko we'd probably be interested in having this functionality in amp-access-laterpay if it became available in amp-access.

We've discussed adding it to our similar, non AMP website integration using a token provided by our API that a publisher's backend could verify, possibly with a shared secret as some of our other APIs already do, or with some other API for the purpose of verification, although we definitely haven't figured this out very specifically.

We're still not sure as to when we'd eventually work on this but it's definitely something on our roadmap.

**Comment by dvoytenko** [comment]
@trodrigues Could you pls remind me: you don't currently do metering, do you? Metering is the real sticking point here. I see a lot of consensus that a signed/verifiable entitlement for subscribers is a good thing, but metering has been a harder issue.

**Comment by choumx** [comment]
Can this be closed now that amp-subscriptions is a thing?
