### ISSUE TITLE
AMP story Player: Unnecessary assert in constructor

### ISSUE THREAD

**Issue by rnkimani** [ampproject/amphtml#29682]
## What's the issue?
- I've been testing out the new proposed API features and one error I get is "Missing configuration" and it's a bit ambiguous.

## How do we reproduce the issue?
- Try creating a new AmpStoryPlayer instance on a slower connection
- I back-traced the code back to this
https://github.com/ampproject/amphtml/blob/3119b32146f2f0720b78345fd5910e1634764c67/src/amp-story-player/amp-story-player-impl.js#L119-L122

## Which AMP version is affected?
- Ref [28416](https://github.com/ampproject/amphtml/issues/28416)

## Additional context
- I'm not sure if it's unnecessary but if it's really needed we can add more information to that log.

cc @Enriqe

**Comment by rnkimani** [comment]
@Enriqe ^

**Comment by Enriqe** [comment]
Thanks for the heads up. I'll fix this soon.
