### ISSUE TITLE
🌸 Cherry-pick request for #29663 into #29539 (Approved)

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#29697]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #29663 | #29663 |     **NO**     | **YES** | **NO** | #29539                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

Hi approvers, this cherrypick request is a bit different from the past. It's not to fix a production issue but rather, it's to ramp up an experiment to a bigger traffic volume to help the debugging an issue in the experiment w/o waiting for a full release cycle. The experiment has been run in canary for a week. No big issues found, but there are ads metric slightly shifted that can only be debugged with larger traffic volume.

## Why is a Beta / Experimental cherry-pick not needed?

The experiment is already 100% on Experimental channel.

## Why is an LTS cherry-pick needed?

Not needed

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by dvoytenko** [comment]
Approved

**Comment by rsimha** [comment]
@lannka I assume this doesn't need to go to experimental or LTS, but it does need to go to stable and beta (so that next week's stable has the change). I just updated the labels.

**Comment by rsimha** [comment]
This has been released to stable and beta/experimental.

**Stable:** https://github.com/ampproject/amphtml/releases/tag/2007242032002
**Beta / Experimental:** https://github.com/ampproject/amphtml/releases/tag/2007302351001
