### ISSUE TITLE
move polyfill removal code in closure to babel

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#29723]
before we had the babel pipeline and transformers we did polyfill removal through a "file shadowing" feature in closure where we write out a fake file that was an empty install function (that will eventually DCE'd). We should move this module removal or code removal to a babel plugin as there are already similar functionalities established in the pipeline

file shadowing and stubbing code: https://github.com/ampproject/amphtml/blob/4826ddcdca9b10b70b6355b5ca2e0d332e42bda1/build-system/compile/compile.js#L183-L212

**Comment by rsimha** [comment]
_[Infra triage]_ Closing because it looks like this has been fixed.
