### ISSUE TITLE
change.intersectionRect is never updated

### ISSUE THREAD

**Issue by ruizb** [ampproject/amphtml#29759]
## What's the issue?

The `change.intersectionRect` object is never updated.

## How do we reproduce the issue?

1. Resize your viewport to be e.g. 850px wide (not too wide since there isn't much content on the page).
2. Go to https://amp.teads.tv/.
3. Wait a little bit (1-2 seconds), then scroll down the page.
   <details>
     <summary>See demo</summary>
         
     ![amp-nightly-no-startad](https://user-images.githubusercontent.com/5022023/89767314-fb891b80-daf9-11ea-8f35-3b6a2f0879b3.gif)
   </details>
4. Below the 2nd "lorem ipsum" paragraph, you should see a light-grey rectangle. This is where the ad is supposed to play. On stable (v. 2007242032002) and beta (v. 2007302351001), the ad is indeed displayed.
5. If you take the focus of the `amp-ad > iframe > body` element, then observe the changes on `_teads_amp.change.intersectionRect`, you'll notice that the values are never updated. We are using this object to detect when the ad is visible, then start/play it. Since the object contains only zeros, we don't consider the ad visible, and we don't start it.
   <details>
     <summary>See changes observed on v. 2007242032002 (stable)</summary>
         
     ![amp-stable-intersectionrect-observed](https://user-images.githubusercontent.com/5022023/89767685-b9140e80-dafa-11ea-9284-92a49a188761.gif)

   </details>

   <details>
     <summary>See changes observed on v. 2008072132000 (nightly)</summary>
     
     ![amp-nightly-intersectionrect-observed](https://user-images.githubusercontent.com/5022023/89767840-042e2180-dafb-11ea-9b14-8be251fe0ca9.gif)
   </details>

## What browsers are affected?

So far, I could test only on these browsers:

- Chrome v84, both desktop and mobile
- Firefox v79

I couldn't set the nightly version on Safari v13.1.

## Which AMP version is affected?

2008072132000

**Comment by ruizb** [comment]
Additionally, when using `context.observeIntersection(callback)`, the `callback` doesn't seem to be triggered anymore when scrolling in the page. It works on 2007242032002 but not on 2008072132000 anymore.

**Comment by ruizb** [comment]
It doesn't work with the current Experimental version, v. 2008072132002.

**Comment by ruizb** [comment]
I didn't want to ping anyone, but I couldn't get any answer since last week, and this issue prevents all our ads from being started. Since it's been promoted to the Experimental channel, I'm a bit worried.

I'm pretty sure it's due to the following commit: https://github.com/ampproject/amphtml/commit/c720e08c02d59ddc603136d235a51b36237308da. Please @choumx, can you have a look?

**Comment by choumx** [comment]
Thanks for the detailed report. I can repro the issue, but I don't think it's c720e08 because `AMP.toggleExperiment('intersect-resources')` doesn't fix it. If I refresh the page with the ad in viewport, then the ad loads as expected.

@ampproject/wg-ads-reviewers

**Comment by ruizb** [comment]
Hello, thanks for the reply!

Yes, the initial `intersectionRect` has the correct values, so when the ad is in the viewport when loading the page, it plays. However, as the rect is never updated, the ad continues to play despite leaving the viewport (it's supposed to be paused when "not visible").

Our automated tests stopped working since a commit merged on 2020-08-06 or 2020-08-07. I thought it was this one since it's about "intersect", but I guess I was wrong!

**Comment by choumx** [comment]
Yea it's somewhere in here: https://github.com/ampproject/amphtml/compare/2007302351000...2008070238000

**Comment by choumx** [comment]
Tried `git bisect` locally on unminified builds and I think it's #28929.

**Comment by lannka** [comment]
Thanks Will, I can take it from there

**Comment by kristoferbaxter** [comment]
For clarity @ruizb, @lannka addressed this regression in #29853. We're following up with some additional tests for confidence going forward.

**Comment by ruizb** [comment]
Hey, thanks for the fix! I tested on the latest nightly channel (v. 2008180007000) and it works fine! 👍

**Comment by ruizb** [comment]
Hello again! It works, but it takes much more time to "start working". I noticed the `context.observeIntersection` callback was called a few times, then paused for some time, then got called again every time I scroll. I'm not sure what could introduce some delay? (we're talking about several seconds)

![CleanShot 2020-08-19 at 09 59 23](https://user-images.githubusercontent.com/5022023/90608308-b30ce480-e202-11ea-8b2d-82a1e7892485.gif)
