### ISSUE TITLE
Support <link rel=manifest>

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amphtml#2975]
`<link rel=manifest>` is [not valid AMP](https://cdn.ampproject.org/c/s/cdn.rawgit.com/anonymous/8f444d34156456bb91a5cad4663833ab/raw/dd91fc915dcc1e5b5123dfb40b7a17b24a515c3c/index.html). (See [validator-main.protoascii#L143](https://github.com/ampproject/amphtml/blob/d47bf25e011249083962798e8900ec080929b014/validator/validator-main.protoascii#L143).)

This is a problem because the manifest is used by Chrome and other browsers to store metadata such as the appropriate icons to use in different circumstances as well as the [GCM sender id](https://developer.mozilla.org/en/docs/Web/API/Push_API/Using_the_Push_API#manifest.json) for push notifications. Being able to link a manifest is essentially a requirement if a page is to be both a valid AMP page and a Progressive Web App.

(It might be possible to specify this in a HTTP header (`link: </manifest.json>; rel=manifest`) however modifying headers is difficult or impossible in many situations.)

**Comment by Gregable** [comment]
@cramforce who may know more. This was an explicit decision. I'm not that we are ready for AMP pages to be web apps so far, and manifests trigger network traffic and client processing which could have an affect on performance.

**Comment by cramforce** [comment]
@Gregable We basically tabled it. Because this is an important modern element with usages beyond apps, I think it would be better to allow it, but teach the AMP Cache to eliminate it from the document.

**Comment by ithinkihaveacat** [comment]
Removing `<link rel=manifest>` when served from the AMP Cache would work for my use case, and probably most (?) use cases.

If there's going to be a difference in on-CDN versus off-CDN behavior, I wonder if it's worth having a standard system to express/indicate this. (`<amp-install-serviceworker>` also has different behaviour--are there any other examples?)

**Comment by cramforce** [comment]
In general we try to absolutely minimize these differences. This seems to be a case where it makes sense, or could you come up with a manifest usage that would be nice on the Cache?

`amp-install-serviceworker` at least tries to support both cases and do the same side effect for both scenarios.

**Comment by ithinkihaveacat** [comment]
@mounirlamouri @PaulKinlan Are there any circumstances (or do you foresee any circumstances) in which it would be very useful to have a manifest associated with individual documents in the AMP Cache?

Are there any security/privacy/performance issues with doing this? Note that in the cache, pages from different publishers share the same origin:

* https://cdn.ampproject.org/c/www.bbc.co.uk/news/amp/35966412
* https://cdn.ampproject.org/c/s/amp.theguardian.com/australia-news/2016/apr/25/crocodile-attacks-man-dragging-him-from-tent-in-northern-territory

**Comment by mounirlamouri** [comment]
I don't have enough background about AMP to answer this. Hopefully @PaulKinlan can help :)

**Comment by slightlyoff** [comment]
What's the concern with supporting `<link rel=manifest>` from the AMP Cache? As these documents won't have a serviceworker (or will they?), they won't trigger an add-to-homescreen prompt. If you ran the same document from the source origin, you might get the prompt as the SW would install correctly.

Is the concern that the manifest link + an AMP Cache Service Worker might cause the prompt?

**Comment by cramforce** [comment]
The question now is: Would `<link rel=manifest>` ever do anything useful on the AMP cache or can we just filter it out?

**Comment by cramforce** [comment]
As in: It is clearly useful on the origin and so it should be allowed. I don't think it is enough of a noop to be allowable on the Cache, though. But for that I can be convinced otherwise.

**Comment by ericlindley-g** [comment]
Still tbd if this is the right approach, but I believe `<link rel=manifest>` would also be necessary to trigger the native Android app-install button in Chrome, as well

**Comment by sebastianbenz** [comment]
Any news on this? Was surprised to see the validator complaining when I added a manifest to ampbyexample.

**Comment by cramforce** [comment]
@mkhatib can summarize latest discussion.

But TL';dr is: Manifests should be valid, of course! And that is pretty urgent. The AMP Cache rewriter should neuter the link-tag by renaming the rel to a different value like `origin-manifest`.

**Comment by Gregable** [comment]
Sounds like a plan. Will allow them on amp docs and strip them in the cache.

**Comment by Gregable** [comment]
I'll add one additional tiny constraint just to be explicit. Since we'll be stripping out the tag, we won't allow space separated rel attributes for manifest, ie `<link rel=manifest href=...>` is fine. `<link rel="manifest lemur" href=...>` will not validate. You can always use two link tags with the same href.

**Comment by cramforce** [comment]
@Gregable Can you do the rewrite instead of strip I suggested above? We actually need to be able to find the manifest, because there is an AMP component that reads it at runtime.

**Comment by Gregable** [comment]
Sure, I missed that part of your comment.

**Comment by Gregable** [comment]
This was fixed here (https://github.com/ampproject/amphtml/pull/3676/commits/c3b0b6eb03189b7c2948dc16d60d638674987671), but the issue didn't get updated. This should be live on cdn.ampproject.org next week.

**Comment by Gregable** [comment]
This change is now live on cdn.ampproject.org

**Comment by cramforce** [comment]
Enables #3742
