### ISSUE TITLE
WP: prism.js syntax highlighting stopped working

### ISSUE THREAD

**Issue by SM-Fahim** [ampproject/amphtml#29756]
## What's the issue?

Briefly describe the bug.
I use prism.js and prism.css code in my site for syntax highlighting programming blogs. But when I installed AMP, the amp site stopped loading prism at all. The non-amp site working properly.

The developers of prismjs told that the issue is with AMP, as it’s not loading the js files. Didn't get any reply from the plugin support page. Tried using Standard and Transitional options but it breaks the website. 

How can I fix it?
Need a detailed guide as I’m not a web developer.

## How do we reproduce the issue?

Normal link working properly: [Comments in Python - All possible ways](https://www.machinelearningwiki.com/python/comments-in-python-all-possible-ways/)
But not the amp version: [Comments in Python - All possible ways (amp version)](https://www.machinelearningwiki.com/python/comments-in-python-all-possible-ways/amp)

Please notice the coding part.

[Response from the Prismjs developers
](https://github.com/PrismJS/prism/issues/2511#issuecomment-670988370)

## What browsers are affected?

All browsers, PC and Phone

## Which AMP version is affected?

The latest version on WordPress plugins, as just installed it.

**Comment by sirajalam049** [comment]
Same :(

**Comment by kristoferbaxter** [comment]
@westonruter This likely needs to be moved over to the `amp-wp` repo right?

**Comment by westonruter** [comment]
Yes, however I already provided a resolution on the plugin support forum: https://wordpress.org/support/topic/syntax-highlighting-stopped-working-after-installing-amp/#post-13229400

**Comment by kristoferbaxter** [comment]
Closing due to previous comment.
