### ISSUE TITLE
🌸 Cherry-pick request for #29716, #29722 into #29725, #29539 (Approved)

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#29761]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #29716  | #29716 |     **YES**     | **YES** | **YES** | #29725, #29539                                                           |
| #29722 | #29722  |     **YES**     | **YES** | **YES** | #29725, #29539                                                          |
| #29499 | #29646  |     **YES**     | **YES** | **YES** | #29725, #29539                                                          |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

To be able to continue with the module/nomodule rollout these three fixes need to be on the channels. Without it adsense will be broken completely, and intersection observer will be broken in iOS < 12.2

## Why is an LTS cherry-pick needed?

Unfortunately we are currently not able to segregate the rollout from affecting LTS and with the LTS stability in mind I'd like these fixes to be in LTS before doing any rollout

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

There is currently the usage of `this` in a static method of a class. This is currently not supported in closure compiler. I am not able to do a rollout unless this fix is cherry picked in

## Impact

- percentage of AMP documents < 1%
- adsense would break

## Action Items
- #29692: Add eslint rule to prevent use of `this` in static methods

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by rcebulko** [comment]
@erwinmombay @calebcordry Since this is two relatively meaty PRs and LTS would otherwise be promoted today, can we cherry-pick this onto the current Stable this afternoon and let it bake for a day in Stable or so before pushing it directly to LTS?

**Comment by erwinmombay** [comment]
im ok with that if @calebcordry is

**Comment by kristoferbaxter** [comment]
Approved.

**Comment by calebcordry** [comment]
SGTM. Ill start with prod now.

**Comment by erwinmombay** [comment]
@ampproject/wg-approvers I need to add https://github.com/ampproject/amphtml/pull/29646 to the list of cherry pick requests as to not break amp input mask when rolling out module/nomodule
