### ISSUE TITLE
Don't render Story share menu when native sharing is supported

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#29773]
It appears that the sharing menu is rendered even when native sharing is supported on the browser/platform. We should optimize this and not render this extra DOM / component.

cc @ampproject/wg-stories

**Comment by processprocess** [comment]
Agree that it's redundant.
Just to clarify, remove the system share button if `navigator.share` exists?

IOS screenshot:
<img width="280" alt="Screen Shot 2020-12-16 at 4 52 11 PM" src="https://user-images.githubusercontent.com/3860311/102410817-15ae9b00-3fbf-11eb-87e9-ac3588a70d35.png">

Webview screenshot:
<img width="418" alt="Screen Shot 2020-12-16 at 4 59 42 PM" src="https://user-images.githubusercontent.com/3860311/102411593-29a6cc80-3fc0-11eb-98ab-589b30e15e6b.png">

**Comment by gmajoulet** [comment]
I meant this as a code optimization, we render the HTML web sharing options (menu, icons etc) in the background even though the native sharing will trigger instead of our HTML.
But you're making a good point as well! We should run this by PM/UX though.

**Comment by mszylkowski** [comment]
Would this be a change in the `isSystemShareSupported`?

https://github.com/ampproject/amphtml/blob/76894ef4d326643945d5f1514f3f139fdd058a50/extensions/amp-story/1.0/amp-story-share.js#L324-L334

https://github.com/ampproject/amphtml/blob/76894ef4d326643945d5f1514f3f139fdd058a50/extensions/amp-story/1.0/amp-story-share-menu.js#L112-L126
