### ISSUE TITLE
AMP experiments page: Not working when using the BlackBerry 10 browser

### ISSUE THREAD

**Issue by devnullzero** [ampproject/amphtml#2979]
## Short description of your issue:

The "AMP experiments page" (https://cdn.ampproject.org/experiments.html) doesn't display the  "extensions table" when using the BlackBerry 10 browser. 

Javascript error:
ReferenceError: Can't find variable: Promise     experiments.js:4
## How do we reproduce the issue?

Go to https://cdn.ampproject.org/experiments.html using the default web Browser
## What browsers are affected?

BlackBerry 10 (10.3.2.2474)
Hardware: Z10
WebKit: 10.3.2.43
Browser Version: 10.3.2.36

"Mozilla/5.0 (BB10; Touch) AppleWebKit/537.35+ (KHTML, like Gecko) Version/10.3.2.2639 Mobile Safari/537.35+"
## Which AMP version is affected?

N/A

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
