### ISSUE TITLE
Auto-advancing embedded story (amp-story-player) plays only when in viewport

### ISSUE THREAD

**Issue by ernee** [ampproject/amphtml#29798]
## Describe the new feature or change to an existing feature you'd like to see

Currently, when embedding an auto-advancing story in a webpage (via [amp-story-player](https://github.com/ampproject/amphtml/blob/master/spec/amp-story-player.md)), the story plays even when not in the viewport. Given certain factors (for example: the length of the page, loading time, the scrolling speed of the visitor, and the speed of the advancing the story, etc. ), the visitor may miss pages of the story or potentially arrive at the story on the last page. 

## Describe alternatives you've considered

N/A

## Additional context

Example: https://recordit.co/Qm71hPvefX

Initially reported [in this issue](https://github.com/google/web-stories-wp/issues/3561) for the Web Stories WordPress plugin (beta). The user also suggested the story should be at the first page at DOM ready, particularly in the case that the story renders later due to the rest of the page loading.

**Comment by Enriqe** [comment]
Thanks for the report. This is definitely a bug on our side. Will take a look.
