### ISSUE TITLE
amd-ad: remove element when no ad is avaliable

### ISSUE THREAD

**Issue by gustavopaes** [ampproject/amphtml#298]
Looking at the pull-requests, I saw this one #284.

I got a doubt: If I not define a placeholder, will the amd-ad be removed if no ad is avaliable?

Tks

**Comment by erwinmombay** [comment]
can we close this? I think currently we display the `ad` for ampproject.org? (correct me if i'm wrong)

**Comment by gustavopaes** [comment]
it's ok to me

**Comment by cramforce** [comment]
yeah, we can close this.

We have the preview mechanism in place and a more generic fallback mechanism for later as well.
