### ISSUE TITLE
The attribute of "amp-facebook-comments":data-colorscheme=dark, which has been invalid since August 13, 2020

### ISSUE THREAD

**Issue by jarsonwong** [ampproject/amphtml#29812]
The attribute of "amp-facebook-comments":data-colorscheme=dark, which has been invalid since August 13, 2020

**Comment by realPrimoh** [comment]
Hi Jarson, thanks for bringing this to our attention. This seems to be a reoccurring bug within the Facebook SDK (https://developers.facebook.com/support/bugs/1759174414250782/). For now, I'd recommend using the "light" color scheme and subscribing to the linked bug report on Facebook for further updates from the Facebook SDK team.
