### ISSUE TITLE
Removing a story page leads to console errors during development

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#29816]
To repro

- make a story with some pages
- load it in the browser
- remove the current page
- hit reload

Now all page loads of the URL start having an error in the console.

Before attempting to restore a page from history we should check whether that page still exists.

**Comment by newmuis** [comment]
Odd, we check this already:

https://github.com/ampproject/amphtml/blob/a8d944b2fe83a3cfe59dfeb7b0aac5d48affa9d1/extensions/amp-story/1.0/amp-story.js#L1122-L1138

I'll debug and see why that's not working.

**Comment by newmuis** [comment]
@mszylkowski made me realize that it could be during the page graph traversal, if we reuse the navigation stack from history

**Comment by mszylkowski** [comment]
Added to Fixit project, will try to take a look at it this week

**Comment by cramforce** [comment]
It is definitely history related. I tried to debug it for 10 minutes before filing this issue but couldn't quite make it out.

Took me a while to understand how it could search for this ID that wasn't even managed in the doc :)
