### ISSUE TITLE
Enable cross-origin Service Worker installation for hosts other than AMP Cache

### ISSUE THREAD

**Issue by jmadler** [ampproject/amphtml#2983]
amp-install-serviceworker can install cross-origin serviceworkers only in the context of the AMP Cache.  

That means that, for example, ampbyexample.com can't install a SW for fortunate.io as an illustrative example.  I'm unsure if any other valid (or invalid) use cases exist. 

Does it make sense to remove the restriction and enable enable cross-origin SW installation for hosts other than the AMP Cache?

/related to #586 #981 
/cc @cramforce @jeffposnick @slightlyoff @sebastianbenz

**Comment by adewale** [comment]
Does this mean that: https://cdn.ampproject.org/c/s/ampbyexample.com/introduction/hello_world/ can install a remote service worker but: https://ampbyexample.com/introduction/hello_world/ can't?

**Comment by jmadler** [comment]
Yes

**Comment by cramforce** [comment]
I'm not aware of a use case. The feature exists, so documents can install service workers for themselves.
