### ISSUE TITLE
🌸 Cherry-pick request for #29853 into #29805 (Pending)

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#29855]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #29759 | #29853 |     **YES**     | **NO** | **NO** | #29805                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

It breaks many 3p ads that wait for inViewport signal to render (e.g. play video)

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Action Items
- #29856: Need an integration test for this.

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by kristoferbaxter** [comment]
Approved.

**Comment by estherkim** [comment]
Noted - cherry picking 2008072132002

**Comment by kristoferbaxter** [comment]
Sent a few follow up messages to this as well, but we'd like to add some additional testing to ensure this issue is fixed as expected for more scenarios.

**Comment by rsimha** [comment]
_[Cleaning up old CP issues]_ Can this be closed?
