### ISSUE TITLE
amp-script: incorrect validator error message if inline script is too large

### ISSUE THREAD

**Issue by morsssss** [ampproject/amphtml#29859]
`amp-script` allows inline scripts to be 10,000 bytes or less. If you include a larger script,
* The script is allowed to run.
* The validator throws an error: `The author stylesheet specified in tag 'script' is too long - document contains {xxx} bytes whereas the limit is 10000 bytes.`  (where, of course, `{xxx}` is the size of the script)

Let's fix the first part of that error message!

And, then - should the script be allowed to run? I don't personally have a problem with that, although `amp-script` does block remote scripts that exceed the 150,000-byte limit.

**Comment by morsssss** [comment]
I imagine we're not blocking inline scripts because this check occurs in the validator, not at runtime.

**Comment by honeybadgerdontcare** [comment]
Since it has the tag name, maybe this should just be generalized to:
`The content specified in tag 'script' is too long - document contains {xxx} bytes whereas the limit is 10000 bytes.`

`s/author stylesheet/content`

Thoughts?

**Comment by morsssss** [comment]
Thanks @honeybadgerdontcare !

Thinking about this further - how about something like `Inline script is {xxx} bytes, which exceeds the limit of 10,000`? This would be more succinct and likely closer to what a developer might expect.

**Comment by honeybadgerdontcare** [comment]
That is much more succinct. It would require an engine change in addition to the error message change. It's not difficult though as we know the context of the error and can see if it's a script or a style tag.

@CrystalOnScript any thoughts on wording for this new message? Should we also update the `style` error message wording?

Current (for style but unfortunately also showing for script):
`The author stylesheet specified in tag 'script' is too long - document contains {xxx} bytes whereas the limit is 10000 bytes.`

Proposals:
`The content specified in tag 'script' is too long - document contains {xxx} bytes whereas the limit is 10000 bytes.`
`Inline script is {xxx} bytes, which exceeds the limit of 10,000.`

**Comment by honeybadgerdontcare** [comment]
This has been fixed in cl/327740937. It applies to `amp-experiment` and any other extensions that have inline `script` tags.

The message is: `The inline script is 12345 bytes, which exceeds the limit of 10000 bytes. (see https://amp.dev/documentation/components/amp-script/#faq)`
