### ISSUE TITLE
[amp-story-player] Dispatch end of stories event

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#29865]
An event should be dispatched when the user taps next on the last story page of the last story in the player.

@ampproject/wg-stories

**Comment by gmajoulet** [comment]
I don't fully understand the need for a "user navigated to the last page" event as described in #29394 or in this PR.
If you want to perform an action - eg: close the player - when there are no more stories, then you want to dispatch the event when a user is trying to navigate beyond the last page of the last story? ie: tap to next when there's no next

**Comment by ChintanPalan** [comment]
I would like to disagree, when outside the viewer, we keep track of stories being viewed by user, and hence when a story is fully traversed, we need to mark it as complete. 
And this is the use case with all major social media platforms like Facebook, Instagram, and Snapchat, so I think this is a very valid approach. And as it is, if we are allowing the whole story to be played in the player, then there should not be an issue to share a basic event like Story End.
In case publishers don't want to share the data, we can later think of features where they can opt-out from allowing a story to be viewed in the player by using some kind of meta-data.

**Comment by gmajoulet** [comment]
> I would like to disagree, when outside the viewer, we keep track of stories being viewed by user, and hence when a story is fully traversed, we need to mark it as complete.

Could you describe some Player features you need this (an event when reaching the last page of a story) for?

**Comment by ChintanPalan** [comment]
Basically our player is a high-level wrapper around AMP Story Player where developers can add a list of stories and it would be shown as a carousel similar to Instagram stories on their website.
Now the thing is trying to emulate the full behavior of Instagram including ordering of stories as per view status.
Once the user has completed the story, we need to mark it as complete and send it to the end of the carousel.
Makes sense?

**Comment by gmajoulet** [comment]
So if a user swipes away from the Story before the last page to go the next one, you would not want to send it to the end of the carousel?

**Comment by ChintanPalan** [comment]
Yes, we do, and for that, the navigation event is already available in the AMP Story player.

**Comment by ghelapratik** [comment]
@Enriqe - Since you have moved this to wg-stories Player, shall we expect this story end available to be captured only when you launch it with the AMP Player?

**Comment by gmajoulet** [comment]
For now you could rely on the `CURRENT_PAGE_ID` event, that is dispatched on each page navigation. It has an extra parameter that's the `progress` within the story.

cf https://github.com/ampproject/amphtml/pull/29878

It behaves exactly like the analytics `storyProgress`: https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/amp-story-analytics.md#storyprogress
