### ISSUE TITLE
Optimizer for Drupal :droplet:

### ISSUE THREAD

**Issue by neerajklite** [ampproject/amphtml#29872]
## Feature

Hey there , huge fan of AMP and its ecosystem. We have been using it on our Drupal sites for a couple of months and its brought us a lot of joy. So, thank you all !!! . 
Recently I watched a youtube video where @nainar talked about the possibility of bringing the amp optimiser to other cms projects such as drupal [youtube](https://youtu.be/h8bQA1X6RRc?t=1775). Can anyone share the roadmap or anything related to that. Thanks :pray:

**Comment by sebastianbenz** [comment]
There are no official plans to add support for Drupal, but @chasefinch recently published a Python based AMP Optimizer implementation that can be used as a Drupal middleware: https://github.com/chasefinch/amp-renderer

**Comment by neerajklite** [comment]
Drupal is php based. Wordpress already has a library [wp amp optimiser](https://github.com/ampproject/amp-wp/tree/develop/lib/optimizer) I thought drupal would get it too

**Comment by sebastianbenz** [comment]
Sorry, my fault. @westonruter or @amedina might know more about Drupal support.

**Comment by westonruter** [comment]
@neerajklite We have ported the AMP Optimizer to PHP for use in the WordPress AMP plugin. At the moment the package is nested inside of the plugin repo: https://github.com/ampproject/amp-wp/tree/develop/lib/optimizer

However, the PHP code is platform-agnostic and can be used in a Drupal project. We will soon be extracting the library into a standalone Composer package on Packagist. For more, see https://github.com/ampproject/amp-wp/issues/4567

**Comment by neerajklite** [comment]
Thats wonderful 👍 . Thanks for the clarification.
