### ISSUE TITLE
amp-next-page no effect

### ISSUE THREAD

**Issue by cloewen8** [ampproject/amphtml#29888]
# What's the issue?

`amp-next-page` appears to have no effect.

## How do we reproduce the issue?

I observed this from the provided example: https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-next-page&format=websites

1. The initial 6 sections of Lorem ipsum display normally.
2. I scroll to the bottom. Nothing more is displayed.
3. I scroll back to the top. Nothing appears to have changed.

I'm unsure if this is an isolated occurrence. I was able to reproduce this in multiple browsers, but have also seen a video showing it working and several issues relating to specific features of it. I also tried implementing it in my own website and got the same result. At the time I shrugged it off as the component being unfinished.

## What browsers are affected?

I repeated these steps in Firefox (79), Chrome (84) and Edge (84).

## Which AMP version is affected?

I am fairly new to AMP and have only observed this behavior within the last 3~ days. Says version `2007302351001`.

**Comment by dmanek** [comment]
The example is broken since amp-next-page requires the JSON config URL to be on same origin. I've submitted https://github.com/ampproject/amp.dev/pull/5173.

**Comment by dmanek** [comment]
ampproject/amp.dev#5173 is merged & will be available after the next push to amp.dev. Closing this issue.
