### ISSUE TITLE
amp-script: error thrown if AMP component script is missing

### ISSUE THREAD

**Issue by morsssss** [ampproject/amphtml#29884]
As far as I can tell, I can't open a `<amp-lightbox>` inside an `<amp-script>`. I get this error:

![image](https://user-images.githubusercontent.com/29419498/90570387-8c589a80-e17d-11ea-88c9-5f5f1f0f22b2.png)

Sample code:

```html
  <script id="myscript" type="text/plain" target="amp-script">
    console.log("I am a script");
  </script>
  <amp-script layout="fixed-height" height="300px" script="myscript">
    <div>
      <amp-lightbox id="my-lightbox" layout="nodisplay">
        <div class="lightbox" on="tap:my-lightbox.close" role="button" tabindex="0">
          <h1>Hello World!</h1>
        </div>
      </amp-lightbox>
      <button on="tap:my-lightbox">
        Open lightbox
      </button>
    </div>
  </amp-script>
```

**Comment by morsssss** [comment]
Um... actually, this is my fault. I failed to include the JS that `amp-lightbox` requires:

`<script async custom-element="amp-lightbox" src="https://cdn.ampproject.org/v0/amp-lightbox-0.1.js"></script>`

Of course, if I omitted this, someone else will have the same problem, and it would be best if this error was caught so a friendlier message could be shown!

**Comment by samouri** [comment]
> Of course, if I omitted this, someone else will have the same problem, and it would be best if this error was caught so a friendlier message could be shown!

Closing as this has nothing to do with `amp-script`.
Feel free to open up an issue about generically making nice error messages for missing extensions from `<head>`
