### ISSUE TITLE
Delay when calling listener registered with context.observeIntersection

### ISSUE THREAD

**Issue by ruizb** [ampproject/amphtml#29893]
## What's the issue?

A listener registered with the `context.observeIntersection` function is called a few times at the beginning, then it's not called anymore for some time (this is the issue), then we get the expected behavior, i.e. listener called when scrolling in the page.

## How do we reproduce the issue?

1. Resize your viewport to be e.g. 850px wide (not too wide since there isn't much content on the page).
2. Go to https://amp.teads.tv/.
3. Wait a little bit (1-2 seconds), then scroll down the page.
   <details>
     <summary>See demo on beta and nightly (resp. v. 2008150009001 and v. 2008180007000)</summary>
         
     ![CleanShot 2020-08-19 at 09 59 23](https://user-images.githubusercontent.com/5022023/90608308-b30ce480-e202-11ea-8b2d-82a1e7892485.gif)
   </details>
4. Below the 2nd "lorem ipsum" paragraph, you should see a light-grey rectangle. After some time (~1-3 seconds), the ad should start playing. On stable channel (v. 2007302351001), the ad starts playing right away. On beta (v. 2008150009001) and nightly (v. 2008150009001), there is some delay.
   <details>
     <summary>See demo on stable (v. 2007302351001)</summary>
         
     ![CleanShot 2020-08-19 at 10 02 25](https://user-images.githubusercontent.com/5022023/90608605-27e01e80-e203-11ea-81dd-0f86017b7d03.gif)
   </details>

## What browsers are affected?

So far I could witness the issue on these browsers:
- Mac OS Chrome v84
- Android Chrome v84
- It's hard to tell on iOS Safari 12.0, but since our automated tests are flaky, I'm assuming there is some delay too.

## Which AMP version is affected?

Beta: 2008150009001
Nightly: 2008180007000

**Comment by choumx** [comment]
@ampproject/wg-ads-reviewers @lannka

**Comment by powerivq** [comment]
Hi,

I have tried reproducing on both nightly and prod. Once I scrolled past a certain position (in the video ad slot), it starts playing. I do not see delay.

**Comment by ruizb** [comment]
Hello,

I tested with the Chrome Dev Tools closed and still got the issue: https://youtu.be/bWvl5Wuzpsc.

**Comment by ruizb** [comment]
Hello again,

I've tested about 15 old versions (from 002007210634000 to 2007302351001) and I got the same instability.

Could it be related to the way I manually test it? I'm setting the version with the https://cdn.ampproject.org/experiments.html page, which sets a cookie in order to get the AMP version I provided (I'm assuming). Maybe it's actually related to some cache policy being different between test versions and stable/production version? 🤔

**Comment by choumx** [comment]
Dev console prints the AMP version on page load. Is it printing the expected version?

> I've tested about 15 old versions (from 002007210634000 to 2007302351001) and I got the same instability.

So this bug is actually older than originally thought? You mentioned in https://github.com/ampproject/amphtml/issues/29759#issuecomment-675917789 that 2007302351001 has no delay.

**Comment by ruizb** [comment]
> Dev console prints the AMP version on page load. Is it printing the expected version?

Yes, every time I checked it printed the version I asked for on the experiments page.

> So this bug is actually older than originally thought? You mentioned in #29759 (comment) that 2007302351001 has no delay.

The thing is, I'm not sure it's a bug related to AMP itself, but rather on the way it's served to clients.

When I test the current stable version (2007302351001) but using the "advanced" panel, I get the delay 🤔 

![CleanShot 2020-08-26 at 09 34 56@2x](https://user-images.githubusercontent.com/5022023/91274806-8b2bfc80-e77f-11ea-8d0e-cfdc793dcd20.png)

But when I test it without doing anything in the experiments page, it works as expected, without delay.

**Comment by choumx** [comment]
Could be related to browser caching causing dynamic reloading of JS to match the new version. Can you reproduce after disabling caching in devtools?

**Comment by ruizb** [comment]
The "Disable cache" flag was checked during all the tests I did.
