### ISSUE TITLE
🚄 onResizeSuccess/onResizeDenied deprecated in 2007302351000

### ISSUE THREAD

**Issue by DenyHF** [ampproject/amphtml#29895]
There was request https://github.com/ampproject/amphtml/pull/29533 added to 2007302351000.
Our company is actively using this function for best viewability of our informers.

Is there any alternative functions to use instead of onResizeSuccess/onResizeDenied?

thank you so much!

**Comment by powerivq** [comment]
@DenyHF Sorry. Did not see your issues here. Yes, we change the requestResize to return a `Promise` and you can use the promise to determine when/if the request succeeds or fails.

You can use this https://github.com/ampproject/amphtml/blob/master/ads/README.md#ad-resizing as a reference.
