### ISSUE TITLE
amp-script: AMP.getState without a state path returns null

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amphtml#29908]
## What's the issue?

Follow-up to https://github.com/ampproject/amp.dev/pull/4320#issuecomment-676893292. My expectation was that `AMP.getState()` without a state path returns an object with all amp-states but it returns `null`.

## How do we reproduce the issue?

See the following [AMP Playground demo](https://playground.amp.dev/#share=PCFkb2N0eXBlIGh0bWw+CjxodG1sIOKaoT4KPGhlYWQ+CiAgPG1ldGEgY2hhcnNldD0idXRmLTgiPgogIDx0aXRsZT5NeSBBTVAgUGFnZTwvdGl0bGU+CiAgPGxpbmsgcmVsPSJjYW5vbmljYWwiIGhyZWY9InNlbGYuaHRtbCIgLz4KICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLG1pbmltdW0tc2NhbGU9MSxpbml0aWFsLXNjYWxlPTEiPgogIDxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoOy1tb3otYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1zLWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoO2FuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RofUAtd2Via2l0LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1vei1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1tcy1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1vLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1Aa2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fTwvc3R5bGU+PG5vc2NyaXB0PjxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjpub25lOy1tb3otYW5pbWF0aW9uOm5vbmU7LW1zLWFuaW1hdGlvbjpub25lO2FuaW1hdGlvbjpub25lfTwvc3R5bGU+PC9ub3NjcmlwdD4KICA8c2NyaXB0IGFzeW5jIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAuanMiPjwvc2NyaXB0PgogIDxzY3JpcHQgYXN5bmMgY3VzdG9tLWVsZW1lbnQ9ImFtcC1iaW5kIiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1iaW5kLTAuMS5qcyI+PC9zY3JpcHQ+CiAgPHNjcmlwdCBhc3luYyBjdXN0b20tZWxlbWVudD0iYW1wLXNjcmlwdCIgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC9hbXAtc2NyaXB0LTAuMS5qcyI+PC9zY3JpcHQ+CiAgPHN0eWxlIGFtcC1jdXN0b20+CiAgICBoMSB7CiAgICAgIG1hcmdpbjogMXJlbTsKICAgIH0KICA8L3N0eWxlPgogIDxtZXRhIG5hbWU9ImFtcC1zY3JpcHQtc3JjIiBjb250ZW50PSJzaGEzODQtUkF4ejhXRDNiOEpkQlhabGJEYm9tam1DVkpscVpNYmticTg2c2Q2SXdxQTdNTi1aZzdOVE01QVlxQmlJMmt3bSBzaGEzODQtUVpjaHBQYXFtZGVSbTd4N1NGVXkyM2hoTjRvc1dxUXJfSDRrR1lQTmt4RV9ROTVZREEyTFAxY2wzVlVyVEJFNSBzaGEzODQtTTduUG0xSnNITWpmcGJfWEFOREZDN29NSi1TSGRNZWYyWS1HUlROa1FaR1dBZHJCeDBVOHVnZ3VNNWNpR0tRRCAiPgo8L2hlYWQ+Cjxib2R5PgoKICA8YW1wLXNjcmlwdCBsYXlvdXQ9ImNvbnRhaW5lciIgc2NyaXB0PSJkZW1vIj4KICAgIDxidXR0b24gaWQ9ImdldC1zdGF0ZSI+CiAgICAgIEFNUC5nZXRTdGF0ZSgpCiAgICA8L2J1dHRvbj4KICAgIDxpbnB1dCBwbGFjZWhvbGRlcj0ic3RhdGUtanNvbiIgaWQ9InN0YXRlLWpzb24iIGRpc2FibGVkPgogIDwvYW1wLXNjcmlwdD4KICA8YW1wLXN0YXRlIGlkPSJwaXhpIj4KICAgIDxzY3JpcHQgdHlwZT0iYXBwbGljYXRpb24vanNvbiI+CiAgICAgIHsKICAgICAgICAia2V5IjogInZhbCIKICAgICAgfQogICAgPC9zY3JpcHQ+CiAgPC9hbXAtc3RhdGU+CiAgPHNjcmlwdCBpZD0iZGVtbyIgdHlwZT0idGV4dC9wbGFpbiIgdGFyZ2V0PSJhbXAtc2NyaXB0Ij4KICAgIEFNUC5nZXRTdGF0ZSgpLnRoZW4oKHN0YXRlKSA9PiB7CiAgICAJY29uc29sZS5sb2coJ1JlY2VpdmVkIHN0YXRlJywgc3RhdGUpOwogICAgfSk7CiAgICAKICAgIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdnZXQtc3RhdGUnKS5hZGRFdmVudExpc3RlbmVyKCdjbGljaycsIChlKSA9PiB7CiAgICAgICAgQU1QLmdldFN0YXRlKCkudGhlbigoc3RhdGUpID0+IHsKICAgICAgICAJZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3N0YXRlLWpzb24nKS52YWx1ZSA9IEpTT04uc3RyaW5naWZ5KHN0YXRlKQogICAgICAgIH0pCiAgICB9KQogIDwvc2NyaXB0Pgo8L2JvZHk+CjwvaHRtbD4K)

## What browsers are affected?

All.

## Which AMP version is affected?

2007302351001

/cc @morsssss, @samouri

**Comment by samouri** [comment]
Hi @matthiasrohmer, I believed this was fixed in https://github.com/ampproject/worker-dom/pull/1035 but I didn't remember to close this issue. Just tested to confirm and it seems like full state object is returned these days when no arg is provided.

Please reopen if you are seeing differently.
