### ISSUE TITLE
amp-consent: Increase consent rates

### ISSUE THREAD

**Issue by opencmp** [ampproject/amphtml#29910]
## Describe the new feature or change to an existing feature you'd like to see

We realized that the consent rates are very bad with the current integration of our CMP with amp-consent compared to the desktop version. Users seem to ignore the CMP and keep surfing the page without giving any consent.

To solve this problem we can think of following approaches:
- Increase initial height to whole screen
- Position the CMP in the middle of the screen
- Put a semi opaque layer on top of the page's content to make it unreadable for the user

We would appreciate a discussion about how to improve consent rates. Thank you!

**Comment by micajuine-ho** [comment]
Hi @opencmp, thanks for your issue.

> Increase initial height to whole screen

We allow the consent dialog to take up the full screen in the browser after user interaction: 
https://github.com/ampproject/amphtml/blob/master/extensions/amp-consent/integrating-consent.md#enter-fullscreen

Additionally, we only allow the full screen request if the consent dialog is a bottom pane and not a modal (see below).

> Position the CMP in the middle of the screen

We have recently introduced the new modal UI for the consent dialog, which can be triggered by sending a vh value greater than 60 and less than 80:
https://github.com/ampproject/amphtml/blob/master/extensions/amp-consent/integrating-consent.md#ready

The modal will be automatically centered and have an overlay (semi-opaque layer) on top of the page's content.

> Put a semi opaque layer on top of the page's content to make it unreadable for the user

As mentioned above, this overlay is default when using the modal UI. For the bottom pane UI, you can enable the overlay through the `uiConfig` either inline or as a part of the CMP config.
https://github.com/ampproject/amphtml/blob/master/extensions/amp-consent/amp-consent.md#uiconfig


Please let me know if you need any help implementing any of these solutions.

**Comment by micajuine-ho** [comment]
Closing for now. Feel free to reopen.
