### ISSUE TITLE
Unable to setState on chained submit-success

### ISSUE THREAD

**Issue by cw-ashish-sharma** [ampproject/amphtml#29911]
unable to set states on submit-success event of form
getting Trust level error as low
can we have it as High?

this happens when we are trying to submit another form on the submit-success event of a form

example:
```
<form action="apicall1" on="submit-success: AMP.setState({dummyName:"Asda"})" id="f1">
<!-- fields -->
</form>

<form action="apicall2" on="submit-success: f1.submit" id="f2">
<!-- fields -->
</form>
```

on the `submit-success` of form f1 it is not able to set the state because it shows it has low trust level to set the state

**Comment by cw-ashish-sharma** [comment]
@choumx  any updates on this?

**Comment by choumx** [comment]
> We can create a single endpoint but then it will become amp specific

I'd recommend doing this for the best user experience. However we can also consider support slightly longer submit chains. 

Are any other sites affected? 

@arvindnitharwal How can I repro the issue on www.carwale.com?

**Comment by arvindnitharwal** [comment]
we have removed from our prod servers but if you req we can share a video.
