### ISSUE TITLE
[amp-next-page] v1.0 not working if in first viewport

### ISSUE THREAD

**Issue by noodles** [ampproject/amphtml#29918]
#29855  What's the issue?

amp-next-page does not work at all if the component appears in the first viewport

![next-page-demo glitch me_1_0issue html(Moto G4)](https://user-images.githubusercontent.com/183972/90835555-49badc00-e390-11ea-989a-7c33c7e5082b.png)

## How do we reproduce the issue?

Create an AMP page with with the amp-next-page component but only add enough text/content so that the amp-next-component is visible in the first viewport.

[v1.0 issue example](https://next-page-demo.glitch.me/1_0issue.html)

Adding more content to push the amp-next-page component out of the first viewport will fix the isse;

[v1.0 fix example](https://next-page-demo.glitch.me/1_0issue.html)

## What browsers are affected?

All browsers

**Comment by dmanek** [comment]
@nainar @wassgha this unit test https://github.com/ampproject/amphtml/blob/master/extensions/amp-next-page/1.0/test/test-amp-next-page.js#L332 leads me to believe that amp-next-page was designed to be displayed only when the user scrolls below the first viewport. Do we want to support this use case?

**Comment by wassgha** [comment]
That's correct behavior. This is to avoid [layout shift](https://web.dev/cls/)

**Comment by dmanek** [comment]
Closing this issue as WAI.
