### ISSUE TITLE
Give amp:access a little time to return before rendering

### ISSUE THREAD

**Issue by kushal** [ampproject/amphtml#2992]
If a page has content that uses amp:access to show or hide elements, would it be worth considering a couple hundred milliseconds of waiting for the amp:access RPC tor return in order to avoid flicker?

Per the discussion on this SO topic http://stackoverflow.com/questions/36636357/are-there-strategies-for-reducing-flicker-when-using-ampaccess/36798626#36798626

**Comment by jridgewell** [comment]
@cramforce Should this be high priority? Flashing is anti-AMP.

**Comment by adelinamart** [comment]
What's the status here?

**Comment by dvoytenko** [comment]
This request is different. It asks to make authorization part to block render-start for the document, just as we do for fonts, experiments, etc.

**Comment by dvoytenko** [comment]
@adelinamart This needs to be scheduled and done. Not a controversial thing by any extent.
