### ISSUE TITLE
Embedded story blocks vertical scrolling

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#29935]
To repro

- Embed a story further down into a longer article
- Scroll down
- Try scrolling path the Story while touching the Story

Example page: https://thatwebsiteis.me/archives/web-stories/

Observed: User see the education that they should tap, not scroll

Expected: Page should scroll

How to fix:

- Don't block scrolling when embedded into a page that is much taller than the Story
- Potentially provide for a different user education instead.

**Comment by newmuis** [comment]
@Enriqe @raovs I think it would be good for us to figure out which milestone a fix for this should land in

**Comment by Enriqe** [comment]
Duplicate of #28009

**Comment by gmajoulet** [comment]
Enrique could you either triage or close this one if everything is tracked on #28009?
