### ISSUE TITLE
Smoother placeholder transitions please :)

### ISSUE THREAD

**Issue by neerajklite** [ampproject/amphtml#29940]
## Amp already has animations built in, probably we can use that ?

attaching examples of how medium does it and comparing it with the amp implementations I did on a demo site of mine.

[medium-example](https://user-images.githubusercontent.com/53794487/91051600-f4a3f200-e63d-11ea-8164-4ae22dbe287d.gif)
[my-site](https://user-images.githubusercontent.com/53794487/91051643-038aa480-e63e-11ea-8c31-8adf56953034.gif)

**Comment by nainar** [comment]
@patrickkettner FYI 

The AMP cache already does this for you, and if you want this experience on origin you can use AMP optimizer which does this for free: https://github.com/ampproject/amp-toolbox

**Comment by neerajklite** [comment]
So, AMP loads the placeholders first on the page load. Then when the actual image is available after download it switched it with the placeholder. The hidden css execution is just without any animation. So you mean to say amp cache and toolbox do this and the amp library doesnt ?

**Comment by neerajklite** [comment]
To be honest I use google search all the time and many results are from the amp cache. I have never seen the smooth animation ever.

**Comment by neerajklite** [comment]
@Anybody ?

**Comment by kristoferbaxter** [comment]
Hi there, we'd be happy to accept code contributions for the transition you are speaking of, but do not have the item on our current roadmap.

Our roadmap for images:
1. Support Native HTMLImageElement with lazy loading.
2. Extend Image Optimization on Caches.
3. Support Native HTMLPictureElement.
4. Support Native HTMLImageElement within AMP Custom Elements.

Marking this item P3, when possible.
