### ISSUE TITLE
amphtml-validator url is wrong on npmjs.com

### ISSUE THREAD

**Issue by ka2jun8** [ampproject/amphtml#29941]
## What's the issue?

The URL of GitHub repository in npmjs.com is wrong.
https://www.npmjs.com/package/amphtml-validator

```
- https://github.com/ampproject/amphtml/tree/master/validator/nodejs
+ https://github.com/ampproject/amphtml/tree/master/validator/js/nodejs
```

<img width="952" alt="amphtml-validator_-_npm" src="https://user-images.githubusercontent.com/12580072/91056902-7fe2af00-e661-11ea-96f4-14eb51d689da.png">

**Comment by honeybadgerdontcare** [comment]
This is fixed in 1.0.33. https://www.npmjs.com/package/amphtml-validator
