### ISSUE TITLE
Close/ Exit feature for Web Stories

### ISSUE THREAD

**Issue by ernee** [ampproject/amphtml#29949]
## Describe the new feature or change to an existing feature you'd like to see

A [common requested feature](https://github.com/google/web-stories-wp/issues/3452) from users of the [Web Stories WordPress plugin](https://google.github.io/web-stories-wp/beta/) is a way to close or exit the story from the UI. 

## Describe alternatives you've considered

Navigation back in the browser (but has limitation with loading time and general discoverability) 

## Additional context

Request from users of the Web Stories WordPress plugin currently in Beta:
https://github.com/google/web-stories-wp/issues/3452

**Comment by newmuis** [comment]
Hey @ernee, the WordPress plugin could use the amp-story-player and utilize its [exit control](https://github.com/ampproject/amphtml/blob/master/spec/amp-story-player.md#exit-control); does that work?

**Comment by swissspidy** [comment]
@newmuis Yeah sort of, although I haven't tested it yet. But it seems like many users want an exit feature when opening a standalone web story, so nothing related to the player. i.e. you share a URL with them, they open it, and then they want a "back" button.

**Comment by swissspidy** [comment]
Citing [this comment](https://github.com/google/web-stories-wp/issues/3452#issuecomment-674551493):

> Anyone that i showed this amazing plugin to either tries to swipe down or expects a little closing or dismissal cross at the top. We always expect a way back to a previous page for anything on the internet... and nobody i showed this to (with all my excitement) has thought of the back button.

**Comment by MANIKTANEJA3** [comment]
@ernee if the swipe feature as has been cited in the above comment does not seem feasible a tap in the background i.e. around the story, could be used as the exit feature.
Picking up the concept of touch pad tracing and user tap area.

**Comment by swissspidy** [comment]
I like how @cramforce worked around this with his stories: https://www.industrialempathy.com/new-on-the-web/

**Comment by cramforce** [comment]
I used the story player that @newmuis suggested.

**Comment by aqvaspirt** [comment]
like thise feature!
We need to place closed button on the top of stories. Now we solve thise problem with ourself widget. https://testovskiy.vercel.app/test.html
<img width="1031" alt="Screenshot 2020-10-26 at 11 32 03" src="https://user-images.githubusercontent.com/49196731/97150294-f5ace900-177e-11eb-9da7-120c4ad501c0.png">

**Comment by laristyn** [comment]
Hi, is there any update regarding exit feature of google web stories? I am searching for an opportunity for webbrowser and ioS by using wordpress. Thanks.

**Comment by newmuis** [comment]
@laristyn are you able to use the `amp-story-player` as mentioned above?  It's the canonical way to solve this problem.  As a perk, it will also give you additional features such as navigation between stories (instead of having to close a story and re-open the next one).

There's no way to have a custom control within the story itself, as when the story is redistributed or embedded on other sites/platforms, the button would not be functional.
