### ISSUE TITLE
<amp-pinterest> doesn't show context on all browsers

### ISSUE THREAD

**Issue by Ichigo3d** [ampproject/amphtml#29957]
## What's the issue?

Amp-pinterest doesn't show part of labels on all desktop browsers, in console I see following error: SyntaxError: Unexpected token r in JSON at position 0 
## How do we reproduce the issue?

1. create local version of amp on your computer
2. go through this link http://localhost:8000/examples/pinterest.amp.html

## What browsers are affected?

All browsers on MacOS
## Which AMP version is affected?
2008150009001
<img width="1245" alt="Screen Shot 2020-08-25 at 7 07 00 AM" src="https://user-images.githubusercontent.com/37351864/91185259-70d02100-e6a2-11ea-83d6-815dea1dc9b7.png">

**Comment by Ichigo3d** [comment]
@alanorozco

**Comment by caroqliu** [comment]
Dedup with #32333
