### ISSUE TITLE
Add layout `flex-item` to validator

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#2996]
https://github.com/ampproject/amphtml/pull/2856
cc: @Gregable @powdercloud 
need help adding to validator

**Comment by ericlindley-g** [comment]
Setting at least for the next milestone, given the high priority

**Comment by powdercloud** [comment]
Code is done, will give an update as to when it's going live.

**Comment by powdercloud** [comment]
@zhouyx This was has been out for a while - sorry I'm a bit slow with following up. Closing the bug since it's all done.
