### ISSUE TITLE
Fix local flakey amp-accordion tests

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#2998]
## Short description of your issue:

amp-accordion tests fail locally.

## How do we reproduce the issue?

1. execute `gulp test` on the command line

<img width="1436" alt="screen shot 2016-04-25 at 1 42 53 pm" src="https://cloud.githubusercontent.com/assets/354746/14798274/a429217e-0aeb-11e6-89e9-c790094221cd.png">

**Comment by ericlindley-g** [comment]
Setting at least for the next milestone, given the critical priority
