### ISSUE TITLE
Fix local FontLoader test

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#2999]
1. run `gulp test`
2. profit

<img width="1177" alt="screen shot 2016-04-25 at 1 43 54 pm" src="https://cloud.githubusercontent.com/assets/354746/14798296/c8dc8c90-0aeb-11e6-8b32-f67f2728f2aa.png">

**Comment by ericlindley-g** [comment]
Setting at least for the next milestone, given the critical priority

**Comment by mkhatib** [comment]
This should be fixed.
