### ISSUE TITLE
Seeing "?" when using  :before content: '\u2022' in AMP css

### ISSUE THREAD

**Issue by matt-shade-nbcuni** [ampproject/amphtml#29996]
## What's the issue?
When using 
li::before {
    content: '\u2022';
} 
we are seeing bullets rendering as question marks.

Briefly describe the bug.
See screengrabs below.

## How do we reproduce the issue?
Step 1
The bullets are rendering as question marks from the amp cdn:
https://www.google.com/amp/s/www.cnbc.com/amp/2020/08/26/hurricane-laura-forecast-category-4-poses-catastrophic-threat-to-louisiana-and-texas.html
![?bullets](https://user-images.githubusercontent.com/14319706/91374245-c8c37080-e7e5-11ea-98da-b0174caad23f.png)

Step 2
Hitting the url directly from the origin the bullets render as expected:
http://www.cnbc.com/amp/2020/08/26/hurricane-laura-forecast-category-4-poses-catastrophic-threat-to-louisiana-and-texas.html
![correctBullets](https://user-images.githubusercontent.com/14319706/91374526-64ed7780-e7e6-11ea-9c65-e6ebb92facf2.png)

## What browsers are affected?
all mobile browsers and devices seem to be affected.

## Which AMP version is affected?
Powered by AMP ⚡ HTML – Version 2007302351001

Is this a new issue? Or was it always broken? Paste the version of AMP where you saw this issue. (You can find the version printed in your browser's console.)
This seems like a new issue as we have not noticed before.

**Comment by matt-shade-nbcuni** [comment]
saw this is no longer an issue, so may have been caching. closing this bug.

**Comment by jridgewell** [comment]
This was fixed with https://github.com/ampproject/amphtml/issues/29959.
