### ISSUE TITLE
Fix amp-facebook local test

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#3000]
<img width="1360" alt="screen shot 2016-04-25 at 1 44 56 pm" src="https://cloud.githubusercontent.com/assets/354746/14798319/eba5b5b2-0aeb-11e6-9224-9c7e5c709ea0.png">

**Comment by ericlindley-g** [comment]
Setting at least for the next milestone, given the critical priority

**Comment by mkhatib** [comment]
Closing this now with fixes in #3372 and #3313. 

If this is still happening please reopen.
