### ISSUE TITLE
fix local ad test that is failing

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#3001]
<img width="876" alt="screen shot 2016-04-25 at 1 45 37 pm" src="https://cloud.githubusercontent.com/assets/354746/14798343/0a8a3ab6-0aec-11e6-9144-a931ff3b4dfc.png">

**Comment by ericlindley-g** [comment]
Setting at least for the next milestone, given the critical priority

**Comment by mkhatib** [comment]
I've been debugging the failing tests, this seems to be related to changes made related to doubleclick glade in #2989 and the change #2404 that @cramforce put in place seems to be causing this now for some reason. It seems updating the iframe src to add `google_glade=0` to disable glade based doubleclick seems to be broken and AMP never renders the document when the src is updated after the fixture is loaded.

I'll continue to do some more debugging in here if I can find anything else.

**Comment by cramforce** [comment]
I can take a look. If something fails consistently, file an issue and disable the test.

Does it not fail on travis?

**Comment by erwinmombay** [comment]
@mkhatib do you think all the flakey local tests related to the same issue?

**Comment by mkhatib** [comment]
No unfortunately doesn't seem like all is related to the same thing. This one though is consistent locally it will always fail. @cramforce please take a look I couldn't figure out a way to get this fixed.

Most of the others keep timing out and still trying to figure out why.
