### ISSUE TITLE
nodom amp-script attribute does not pass AMP validation

### ISSUE THREAD

**Issue by RedNinjaX** [ampproject/amphtml#30017]
## What's the issue?

The "nodom" attribute for amp-script does not pass AMP validation via any validation tool (e.g. AMP extension, AMP validation page, Google AMP Validator). The placement of the attribute within the tag is irrelevant. The attribute itself works properly, however.

## How do we reproduce the issue?

1. Create a amp-script element and include the "nodom" attribute in it.
2. Pass the HTML code or a link to the page via any AMP validation tool.
3. An error should appear stating "The attribute 'nodom' may not appear in tag 'amp-script'."

[Example here](https://testo.wonderfulsubs.com/p/blog.html) 

## What browsers are affected?

All browsers

## Which AMP version is affected?

Version 2008150009001

**Comment by samouri** [comment]
Thank you for reporting this! I'll put out a fix today.

**Comment by RedNinjaX** [comment]
@samouri thank you!
