### ISSUE TITLE
[Animation presets] Example story

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#30028]
Example story to document updates & show off new presets

[WIP demo story](https://scale-fade.web.app/examples/amp-story/presets-update.html)

cc @ampproject/wg-stories

**Comment by mszylkowski** [comment]
Can we show this on the official amp.dev documentation? Looks much better than the current one in https://amp.dev/documentation/examples/visual-effects/amp_story_animations/?format=stories (also sth that should be updated)
