### ISSUE TITLE
amp-sticky-ad: Ad is loaded before user scroll

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#30033]
Found the issue from error log related to #29820. 

Some sticky-ad is loaded, and its iframe is created before user scroll. This also leads to activeview request of such ads got sent out before it's visible to users. 

Here's a [link](https://www-forbes-com.cdn.ampproject.org/v/s/www.forbes.com/sites/jonathanponciano/2020/08/26/worlds-richest-billionaire-jeff-bezos-first-200-billion/amp/?amp_js_v=a3&amp_gsa=1&usqp=mq331AQFKAGwASA%3D#ampshare=https%3A%2F%2Fwww.forbes.com%2Fsites%2Fjonathanponciano%2F2020%2F08%2F26%2Fworlds-richest-billionaire-jeff-bezos-first-200-billion%2F) to reproduce the issue. Notice the sticky-ad iframe is created, and an activeview ping is sent out before scroll. 

Note: there seems to be a race condition of the resolved element size when activeview ping is sent. I saw the size resolve to either 50 or 0.

**Comment by powerivq** [comment]
Verified that this bug is fixed by https://github.com/ampproject/amphtml/pull/30167
