### ISSUE TITLE
I2I: DOM data and presets for amp-autocomplete

### ISSUE THREAD

**Issue by dreamofabear** [ampproject/amphtml#30045]
## Summary

Prototype: https://github.com/ampproject/amphtml/pull/30044

### DOM data

**Status quo**: amp-autocomplete renders autocomplete data from a JSON data source, either from an inline script or remote URL. This data is rendered into DOM as children of amp-autocomplete.

**Proposal**: Allow providing autocomplete data in DOM, in the same structure that amp-autocomplete already uses. IOW, support manual prerendering of amp-autocomplete.

For example, a usage with inline script:
```html
<amp-autocomplete id=foo>
  <script type="application/json">
    { "items" : ["apple", "banana", "orange"] }
  </script>	
</amp-autocomplete>
```
...can be represented as:
```html
<!-- May need to rename i-amphtml-autocomplete-* to avoid validation errors. -->
<amp-autocomplete id=foo>
  <div class="i-amphtml-autocomplete-results" role="listbox" id=foo hidden>
    <div class="i-amphtml-autocomplete-item" role="option" data-value="apple" dir="auto">apple</div>
    <div class="i-amphtml-autocomplete-item" role="option" data-value="banana" dir="auto">banana</div>
    <div class="i-amphtml-autocomplete-item" role="option" data-value="orange" dir="auto">orange</div>
  </div>
</amp-autocomplete>
```

### Presets

**Status quo**: amp-autocomplete supports rendering data into DOM via a template (amp-mustache). 

If a template is not provided, amp-autocomplete renders simple data (string array) into a list of `<div>`s. For example, `['foo', 'bar']` is rendered as `<div>foo</div><div>bar</div>`.

For certain email clients, it's preferable to avoid template rendering (see "Motivation" section below). Instead, we can offer a more robust, hard-coded rendering scheme that avoids templates.

**Proposal**: Support rendering of [more complex data (object array)](https://amp.dev/documentation/examples/components/amp-autocomplete/#suggesting-rich-content) with a `preset` attribute. Define the existing simple data rendering as `preset=text` (or missing `preset`). 

Add a new `preset=rich` type that supports rendering text and images. For example:
```
[
  {
    "name": "William Chou",
    "email": "will@email.com",
    "photo": "http://url_like_string"
  },
]
```
...will be rendered as:
```html
<!-- Actual DOM structure subject to change. -->
<p data-item-key="name">William Chou</p>
<p data-item-key="email">will@email.com</p>
<div data-item-key="photo">
  <amp-img layout="fill" src="http://url_like_string"></amp-img>
</div>
```

## Motivation

This enables performant usage of amp-autocomplete in email clients that use `allow-viewer-render-template` and have spam checking -- by having all autocomplete data in DOM, there is no need for SSR template rendering or additional spam checks after page load.

Concrete use cases include @ mentions in Docs comment notification emails.

/cc @ampproject/wg-ui-and-a11y @ampproject/wg-amp4email @caroqliu

**Comment by bill97819** [comment]
Just wanted to confirm that for the "DOM data" proposal, the new markup:
```
<!-- May need to rename i-amphtml-autocomplete-* to avoid validation errors. -->
<amp-autocomplete id=foo>
  <div class="i-amphtml-autocomplete-results" role="listbox" id=foo hidden>
    <div class="i-amphtml-autocomplete-item" role="option" data-value="apple" dir="auto">apple</div>
    <div class="i-amphtml-autocomplete-item" role="option" data-value="banana" dir="auto">banana</div>
    <div class="i-amphtml-autocomplete-item" role="option" data-value="orange" dir="auto">orange</div>
  </div>
</amp-autocomplete>
```
Would be specified by senders themselves, correct?


And also wanted to confirm that the two proposals are mutually exclusive, and the support for a structured data object in "Presets" proposal would not affect the "DOM data" one, as no data object would be specified in "DOM data" to begin with.

**Comment by choumx** [comment]
Yes and yes. 

There is a small interaction between the two -- since amp-autocomplete will parse the DOM to get the source data, it needs to know what DOM structure to expect. It does this by looking at the `preset` attribute before parsing the DOM.
