### ISSUE TITLE
AMP List in Blogger Json feed

### ISSUE THREAD

**Issue by diwakaran1dan** [ampproject/amphtml#30071]
i have seen the amp-list using src="example.com/json". but is there is a way to use blogger json feed inside amp-list?

```
<amp-list width="auto" height="140" layout="fixed-height" 
src="https://example.blogspot.com/feeds/posts/default?alt=json">
<template type="amp-mustache">
-----
</template>
</amp-list>
```

**Comment by caroqliu** [comment]
Thanks for filing this issue @diwakaran1dan ! Am I correct in understanding there is an error when using the above sample because the fetch is blocked by the CORS policy?

**Comment by diwakaran1dan** [comment]
Yes you are right @caroqliu .. i have tried the following code to fetch , but no result.. i am trying to fetch Blogger Json feed in Amp-List

```
<amp-list width="auto" height="140" layout="fixed-height" items="feed.entry" src="...?alt=json">
<template type="amp-mustache">
<div class="title">{{#title}}{{$t}}{{/title}}</div>
<div class="content">{{#content}}{{{$t}}}{{/content}}</div>
</template>
```
</amp-list>

**Comment by caroqliu** [comment]
You could proxy the request using your own server. Here's more info on the [CORS policy in AMP](https://amp.dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cors-requests/).

**Comment by RedNinjaX** [comment]
Just for the record even if you find a workaround, you're still going to need to use amp-script in the end as the Blogger JSON returns thumbnail images in icon size (72px72px) which can only be resolved by using JavaScript to replace the 's72-c'  part in the url with an appropriate size. If it wasn't for this then everything could be done without amp-script. Though if you don't care about thumbnail images then its not necessary.

**Comment by diwakaran1dan** [comment]
Thank your @caroqliu  and @RedNinjaX its help me a lot... its work perfectly now... without help from you guys it won't happen...

**Comment by diwakaran1dan** [comment]
i have one more doubt in this issue... can you please help
i need to fetch Url from blogger Json feed when i tried the following Tag it will bring 3 to 4 the urls (i.e., Blogger ID link, comment link, and Article link)...
`{{#link}}{{href}}{{/link}}`
Output: 

```
https://www.blogger.com/feeds/ID-XXXX/posts/default/ID-XXXX
https://www.blogger.com/feeds/ID-XXXX/posts/default/ID-XXXX
https://example.blogspot.com/2020/08/........html
```
i think it came because there is a nested object in Blogger Json feed...
can you please tell me **how to fetch only the url of that particular article**
