### ISSUE TITLE
Some elements don't appear after the first loading of page

### ISSUE THREAD

**Issue by Ichigo3d** [ampproject/amphtml#30082]
## What's the issue?

When I try to open web page, some elements don't appear on the screen when page is loaded in the first time. After refreshing of page these elements appear. 

## How do we reproduce the issue?
prestep: create local server
1. go to http://localhost:8000/examples/animations.amp.html or http://localhost:8000/test/manual/loaders.amp.html 
2. Observe result

Some elements don't appear. 

## What browsers are affected?

All desktop browsers: Safari, Chrome, FFox on MacOS  

<img width="1680" alt="Screen Shot 2020-09-01 at 10 57 25 AM" src="https://user-images.githubusercontent.com/37351864/91890276-160b6c00-ec44-11ea-827c-2b74b0c6278a.png">
<img width="1680" alt="Screen Shot 2020-09-01 at 11 13 59 AM" src="https://user-images.githubusercontent.com/37351864/91890421-4e12af00-ec44-11ea-966b-c31582cbc30c.png">

**Comment by kristoferbaxter** [comment]
This was due to the sample image no longer being available at the requested URL.
