### ISSUE TITLE
I2I: Support for RushFlow Components and Media Publishers

### ISSUE THREAD

**Issue by SerzhSergeev** [ampproject/amphtml#30091]
## Summary

I am planning to implement extension that will help Media Publishers to add personal interactive elements on AMP pages more faster with customisable functional. 

Often, Media Publishers want to make their content interesting and interactive for the user, and by publishing the next article, for example, accompanying it with interactive charts, statistics, notifications about updates of events in real time.

RushFlow is a service that helps Media Publishers skip development step and provide ready to use solutions right from the box. That mean that you as Editor/Author from big Media Publisher or small new Medias, you can use features of RushFlow without any needs in development, just choose your type of component and where it should be on user screen - and publish it.

## Examples
- **Inline usage** (for example code will be inserting between two paragraphs in the article): `<amp-rush-flow data-cid="104" width="250px" height="150px" layout="flex-item"></amp-rush-flow>`. As you can see for this type of embed content we will provide to Media Publishers attributes of width and height that will help to avoid CLS on AMP pages. 
Demo page: https://rushflow.ru/static/examples/rush-flow_basic-inline-usage.html
And demo with interactive charts inside: https://rushflow.ru/static/examples/rush-flow_basic-inline-usage_data.html
- **Over page content usage** (Media Publisher notifications): `<amp-rush-flow data-cid="107" width="1px" height="1px" layout="flex-item"></amp-rush-flow>`. In this type of usage all content that extension should show, placed over the page content that helps to avoid CLS too. This type of format helps Media Publishers setting up few positions for this extension: `top-left`, `top-center`,`top-right`, `bottom-left`, `bottom-center`, `bottom-right`.
Demo page: https://rushflow.ru/static/examples/rush-flow_position-fixed.html

## Motivation

RushFlow this is a ready if set of Media Publishers tools (no coding) just choose and publish. Features can be inside articles or over page content (fixed position), and this available without any code manipulations for Media Publishers.

Few Media Publishers all over the world has the ability to and dev teams that can make in a few hours to write code for personal component that will be available on AMP pages with interactive features inside and etc. And here is the another thing: without releasing and PR component will not be available on AMP, and for PR and merging they need a few days minimum. This solution will help Publishers to add effective instruments to AMP pages right out of the box, just after adding `amp-rush-flow` code to the Media Publisher AMP with personal `id`. 

Basically `amp-rush-flow` is a safe container that content personal Media Publisher content with their dimensions and position on AMP page. Communication realised through postMessages between extension and content inside. All basic CSS classes (positions, polite animations, margins) already inside `amp-rush-flow` extension.

Here is examples how it looks like:
- Simple block - with custom dimensions from Media Publisher, can support any interactive element inside.
- Simple block - with custom dimensions and charts.
- Cross Notifications - for Media Publishers that rise on AMP when you need to deliver emergency news (like COVID), that positioned over page content (politely, on different sides if needed, or only one element).
- Magic button - that can be using for same emergency, or important feature for users of Media Publisher.
- And many other variations of Media Publishers creative that will help to highlight important news/articles and etc..

_Here is few images that will help to understand it more visually:_
![RushFlow preview](https://rushflow.ru/static/rush-flow-preview_800.jpg?123)

## Q&A

**Question 1:** Why that should be an extension? Explain why the component you are proposing cannot be accomplished for example via  `amp-script` or similar?
**Answer:**
- First of all `amp-script` solution that can be using only by development teams, and if your feature is too individual, then your development team needs to spend a lot of time on its implementation and testing it.
- At second, this extension is not only about insert some custom code to AMP page, because RushFlow can measure how effective it works, and recommending to Media Publisher something new.

**Question 2:** Why don't we use `amp-iframe` instead this extension?
**Answer:**
- Basically `amp-iframe` can't be positioned over page content, without additional css code that must be written by developer, that linked to `amp-iframe`. RushFlow can do that right out of the box, without any additional codes and developer resources. Just insert RushFlow extension amp string - and you got it.

**Question 3:** How that extension affect on Cumulative Layout Shift (CLS) in AMP?
**Answer:**
We do care about CLS and here is two bullets that will help to understand it more deeply.
- For inline page usage we providing Media Publishers amp extension code with fixed width and height - depends on it's content inside.
- For over page content usage (css `position: fixed`) with default width and height equal to 1px.
This simple way helps to avoid any CLS issues on AMP pages.

## Wishes
This is just an example how we can help Media Publishers with Fast Time to Market and customisation. Hope AMP community like it, and i can move to Code and PR discussing.

## Additional context
Here is PR for this extension, please follow it there: [https://github.com/ampproject/amphtml/pull/30084](url)

/cc @ampproject/wg-approvers, @caroqliu

**Comment by Serzhenka** [comment]
@kristoferbaxter @zhouyx @caroqliu Hi guys! 
I've added examples here to I2I (in Examples section), please have a look on it, and our answers to questions (in Q&A section) that we have discussed on previous Design Review. **Question 2** and **Question 3** is important to know. 
Please tell me if everything ok now and we can move forward.

**Comment by zhouyx** [comment]
Hi @Serzhenka, Thank you for the examples!
For the **Inline usage** example, it looks like an `<amp-embed type=rushflow width=100 height=100>` solution will work. In the case AMP loads a bootstrap iframe to run your script. The component is identical to `<amp-ad>`, you can refer to the amp ad doc [here](https://github.com/ampproject/amphtml/blob/master/ads/README.md).

The **Over page content usage** needs more discussion. AMP disallow non visible iframe running in the background.(Iframe with width/height 1px is considered invisible) or iframe placed within the first viewport when a placeholder is not provided. In addition, a restriction on the position fixed iframe size needs to be applied to prevent interstitials. 
@erwinmombay @caroqliu Do you think `<amp-live-list>` is a good fit here?

**Comment by Serzhenka** [comment]
> Hi @Serzhenka, Thank you for the examples!
> For the **Inline usage** example, it looks like an `<amp-embed type=rushflow width=100 height=100>` solution will work. In the case AMP loads a bootstrap iframe to run your script. The component is identical to `<amp-ad>`, you can refer to the amp ad doc [here](https://github.com/ampproject/amphtml/blob/master/ads/README.md).
> 
> The **Over page content usage** needs more discussion. AMP disallow non visible iframe running in the background.(Iframe with width/height 1px is considered invisible) or iframe placed within the first viewport when a placeholder is not provided. In addition, a restriction on the position fixed iframe size needs to be applied to prevent interstitials.
> @erwinmombay @caroqliu Do you think `<amp-live-list>` is a good fit here?

**Comment by Serzhenka** [comment]
> Hi @Serzhenka, Thank you for the examples!
> For the **Inline usage** example, it looks like an `<amp-embed type=rushflow width=100 height=100>` solution will work. In the case AMP loads a bootstrap iframe to run your script. The component is identical to `<amp-ad>`, you can refer to the amp ad doc [here](https://github.com/ampproject/amphtml/blob/master/ads/README.md).
> 
> The **Over page content usage** needs more discussion. AMP disallow non visible iframe running in the background.(Iframe with width/height 1px is considered invisible) or iframe placed within the first viewport when a placeholder is not provided. In addition, a restriction on the position fixed iframe size needs to be applied to prevent interstitials.
> @erwinmombay @caroqliu Do you think `<amp-live-list>` is a good fit here?

@zhouyx Thanks for feedback!
You are right about `<amp-embed>` and it can be using for inline usage type, but it's separately only.
Just a few words about `<amp-live-list>`. I'm not sure that this is good fit for **Over page content usage**.
- extension combine 2 solutions in 1 and helps to this all without coding and additional developer resources
- for this type of format we believe that there can be various kinds of content inside - only notifications, but also buttons and other interactive elements

**Comment by zhouyx** [comment]
Hi @Serzhenka, I understand the intention here. I agree that having one extension to help manage content and also page layout save publishers a lot of configuration work. 

However after talking to the team, we think this violates AMP's [principle](https://amp.dev/about/mission-and-vision/) of prioritizing user's experience over developer's experience.  By fetching the layout configuration remotely using the id, it delays the actual layout and trade the page load time with the ease of page configuration. 
Because of this, we don't think we should build this component. 

If you still want to build the solution for the inline usage type, please consider using `<amp-embed>`

Meanwhile we're open to support more built-in page layout effect (Over page content usage). It wouldn't be `<amp-rushflow>`, more like `<amp-embed layout-type='sticky-to-top'>`. The layout type would be defined inline, not through an id. If you think this could fulfill your use case, we're more than happy to discuss more on this. 

Thank you!
