### ISSUE TITLE
amp-list fails to load more items when using amp-script as a data source

### ISSUE THREAD

**Issue by RedNinjaX** [ampproject/amphtml#30095]
## What's the issue?

When creating an amp-list element that loads items via amp-script, and with the load-more attribute set to any value to retrieve more items, the list fails to load more items. This is likely due to the fact that when calling load more items, amp-list defaults to using the standard behavior of loading items via the 'src' attribute, which is reasonable. The problem is that there is no way to let amp-list know to use amp-script as a data source again for the next load as well as a way to pass the load-more-src value to the associated amp-script script. The two methods are completely separated at this point.

## How do we reproduce the issue?

1. Create an amp-list (load-more attribute set to 'auto' or 'manual') with an associated amp-script element for fetching JSON (which includes a next page url for the load-more-src attribute):

```
<amp-script nodom id="dataFunctions" script="local-script"></amp-script>
<script id="local-script" type="text/plain" target="amp-script">
    function transformData(data) {
    var items = data.entries.map(function(entry) {
        return {
        name: entry.first_name
        };
    });
    var nextPageUrl = entry.next.replace('abc-123','xyz-789'); //  e.g. https://myendpoint.com/list.json?index=25&max-results=25
    return { items: items, "load-more-src": nextPageUrl };
    }
    function getRemoteData() {
    return fetch('https://myendpoint.com/list.json?index=0&max-results=25')
        .then(function(resp) { return resp.json(); })
        .then(transformData);
    }
    exportFunction('getRemoteData', getRemoteData);
</script>
<amp-list load-more="auto" width="100" height="200" layout="responsive" src="amp-script:dataFunctions.getRemoteData">
<template type="amp-mustache">
    <div>Hello, {{name}}</div>
</template>
</amp-list>
```

2. Visit the page. If load-more is set to manual then click the See More button, otherwise just scroll down. An error message occurs saying "UNABLE TO LOAD MORE". When looking in the JavaScript console, an error reads, 'Response must contain an array or object at " items ". ', showing that the behavior defaulted back to using the 'src' attribute on amp-list.

[Example here](https://testo.wonderfulsubs.com/p/blog.html)

## What browsers are affected?

All browsers

## Which AMP version is affected?

Version 2008220050001

**Comment by samouri** [comment]
Thank you @RedNinjaX for reporting this! We are definitely still ironing out this new feature 😬.

A couple of observations: 
- The interaction between "load-more" and "amp-script as a data source" features isn't documented. We should add that. The way you are using it right now actually won't work, the correct `load-more-src` to return in `getRemoteData` would be: `"amp-script:dataFunctions.getRemoteData"`. You may need to maintain state in between calls to getRemoteData, but you should be able to do that in the JS (or if needed via AMP.setState).
- There is a bug ([repro](https://eight-lucky-diamond.glitch.me/load-more-script.html)) in amp-list.js where it doesn't interpret "amp-script:" or "amp-state:" protocols correctly. Should be a small fix, I'm addressing that  in https://github.com/ampproject/amphtml/pull/30101

**Comment by RedNinjaX** [comment]
@samouri ah thanks a lot. I tried several workarounds to no avail trying to get this to work. At least I'm happy to know there is a fix on the way. And yeah, some documentation would be nice when it becomes stable enough 😅 Funny thing is I could have done all of this without amp-script if the mustache template had a way to transform values on the spot (e.g. {{imgUrl.replace('medium', 'large')}}), but I understand that's not the point of it.

I try to limit the amount of components I need to add, so if I could maintain state without having to import amp-state a step in the right direction would be greatly appreciated.

May I make a suggestion? Instead of passing ``amp-script:dataFunctions.getRemoteData`` to ``src`` and ``load-more-src`` alone, would it be possible to have it pass an optional parameter instead? That would remove the need to maintain state I would imagine.

For instance, instead of this:
```
...
/* some code to maintain state via amp-state instead of JS */
<script id="local-script" type="text/plain" target="amp-script">
    /* some code to maintain state via JS instead of amp-state */
    function transformData(data) {
        ...
        return { items: transformedItems, "load-more-src": "amp-script:dataFunctions.getRemoteData"};
    }
    function getRemoteData() {
        return fetch('https://myendpoint.com/list.json?index=0&max-results=25')
            .then(function(resp) { return resp.json(); })
            .then(transformData);
    }
    exportFunction('getRemoteData', getRemoteData);
</script>
<amp-list load-more="auto" width="100" height="200" layout="responsive" src="amp-script:dataFunctions.getRemoteData">
...
```

Why not this?
```
...
<script id="local-script" type="text/plain" target="amp-script">
    function transformData(data) {
        ...
        var transformedNextPageUrl = entry.nextLink.replace('abc','xyz'); //  e.g. https://myendpoint.com/list.json?index=25&max-results=25;
        return { items: transformedItems, "load-more-src": "amp-script:dataFunctions.getRemoteData('" + transformedNextPageUrl  + "')"};
    }
    function getRemoteData(linkToFetch) {
        return fetch(linkToFetch)
            .then(function(resp) { return resp.json(); })
            .then(transformData);
    }
    exportFunction('getRemoteData', getRemoteData);
</script>
<amp-list load-more="auto" width="100" height="200" layout="responsive" src="amp-script:dataFunctions.getRemoteData('https://myendpoint.com/list.json?index=0&max-results=25')">
...
```

**Comment by griffinsharp** [comment]
Hey there @samouri! Is `The interaction between "load-more" and "amp-script as a data source"` still considered an undocumented feature at this point?
