### ISSUE TITLE
I2I: Rename amp-playbuzz to amp-exco

### ISSUE THREAD

**Issue by iddanh** [ampproject/amphtml#30109]
## Summary

Following our company's rebranding we would like to change the name of the current `amp-playbuzz` extension to `amp-exco`. 
We would also like to modify the url the extension uses to our new domain.

## Motivation

Last year our company rebranded itself from Playbuzz to Ex.Co, see [this](https://techcrunch.com/2019/11/18/playbuzz-becomes-ex-co-and-expands-its-content-marketing-platform/) article for a summary.
We want to keep the embed process as friction free as possible for our partners, so we would like to rename the existing extension to match our new brand.

Additionally, the extension currenly uses url's we are planning on deprecating in the near future. We have a new url on the new domain that should be used instead.

/cc @ampproject/wg-approvers

**Comment by caroqliu** [comment]
It might also be worth filing an I2D/I2R for `amp-playbuzz` since I assume the intention is any live usage will break by this change?

**Comment by iddanh** [comment]
@caroqliu thanks for the reply. 
Ideally any live usage will continue to work by keeping the current dist script of `amp-playbuzz` (https://cdn.ampproject.org/v0/amp-playbuzz-0.1.js). 
Will this stop working after the rename?

**Comment by honeybadgerdontcare** [comment]
@iddanh Looking at the PR you submitted then yes, all the pages with amp-playbuzz would become invalid AMP. You will need to file an I2D/I2R for that PR to be approved.

**Comment by iddanh** [comment]
@honeybadgerdontcare thanks for taking a look.
We would very much like to avoid breaking existing pages (many of our clients have "evergreen" items created years ago that still bring in pageviews...).
What is the best way to retain backwards compatibility with the old tag name?

**Comment by honeybadgerdontcare** [comment]
The validator rules for the previous name would need to continue to exist. That could be done by keeping the old rules file or moving those rules in addition to adding the new ones to the new file. The related javascript would still need to continue being served from the previous name's resource location (either directly or via a client http code or internal server redirect).

@ampproject/wg-infra have we renamed an extension before and provided support for the old name?

**Comment by iddanh** [comment]
Seeing that the rename is not a trivial issue and could take a while, so in the meantime I created a new [PR](https://github.com/ampproject/amphtml/pull/30144) that includes only the first 2 commits from the first PR. 
These only include the bugfix to update the internal iframe url from the depracted `www.playbuzz.com` to `app.ex.co/stories`. That way at least this fix could be released sooner. 

Let me know if I should create a new I2I issue for this.

**Comment by rcebulko** [comment]
To my knowledge, there is no back-end/serving-side support for an alias or redirect response. This would be a non-trivial task given that all AMP CDNs would probably have to provide similar support, possibly on a case-by-case basis. Since I suspect this would be infeasible, our only option may be to build and serve the existing amp-playbuzz, with only the necessary changes to make it work with the new URLs, and then fork off the renamed one into a new extension folder that gets compiled to its own binary. More details can be worked out in the I2D. @iddanh if/when you create the I2D, please tag `@ampproject/wg-infra`

**Comment by iddanh** [comment]
Hey, I'm trying to move #30144 along but am getting no responses.

**Comment by iddanh** [comment]
@caroqliu @honeybadgerdontcare @rcebulko Please help, I created this PR 23 days ago and nothing has happened since. 
If something is missing please let me know. I dont want to spam but I'm getting pretty frustrated.

https://github.com/ampproject/amphtml/pull/30144
