### ISSUE TITLE
Want to read and set Google Analytics cookies

### ISSUE THREAD

**Issue by bobcassels** [ampproject/amphtml#3011]
For Google AdSense and Doubleclick ads, we would like to read and set Google Analytics cookies. There is no personal information stored in this cookie. For further information, see the [discussion of cookie details](https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage).

(I can do the work -- just need privacy review.)

**Comment by cramforce** [comment]
@bobcassels Could you be a bit more specific?

AMP already passes the CID that Google Analytics uses in AMP into the ad for doubleclick and adsense and it is being read here: https://github.com/ampproject/amphtml/blob/master/ads/google/doubleclick.js#L61 (and somewhere equivalent in adsense). This is not what you mean, right?

**Comment by bobcassels** [comment]
Never mind. We don't need this after all.
