### ISSUE TITLE
Make getMode().localDev compile away for production builds

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#3012]
We can likely just replace it with a thing that is easier to manipulate like exporting 'isLocalDev' as a variable from the `mode` module.

CC @erwinmombay

**Comment by erwinmombay** [comment]
if we strip away localDev with `false` would closure compiled eliminate the dead branches/blocks

like:

```js
if (false) {
  // if local dev
} else {
 // do else stuff
}
```

into:

```js

// do else stuff
```

**Comment by erwinmombay** [comment]
checked, it does kill unreachable code.

**Comment by cramforce** [comment]
Yes. It also does this for constant (only assigned once) variables where it can be seen at compile time that their value is false.

**Comment by erwinmombay** [comment]
so we could do the exporting of `isLocalDev` on the mode module or i could also just turn the `const isLocalDev = expression` into `const isLocalDev = false` inside the `getMode_` function.

the minor issue right now with exporting it at the mode object is the aliasing of the mode object like in error.js (see below) and `localDev` isnt unique enough to of a label i think (it probably is in practice, but yeah)

```js

const somerandomname = getMode();

if (somerandomname.localDev) {

}
```

**Comment by erwinmombay** [comment]
better:

```js
import {isLocalDev} from '.../../src/mode';

if (isLocalDev) {

}
```

```js
// safe to execute at module level?
export const isLocalDev = (location.hostname == 'localhost' ||
      (location.ancestorOrigins && location.ancestorOrigins[0] &&
          location.ancestorOrigins[0].indexOf('http://localhost:') == 0)) &&
      // Filter out localhost running against a prod script.
      // Because all allowed scripts are ours, we know that these can only
      // occur during local dev.
      !!document.querySelector('script[src*="/dist/"],script[src*="/base/"]');
```

***

also doable:

```js
getMode_() {
    const isLocalDev = false;
    //.. other code
}
```

**Comment by cramforce** [comment]
It would need to be

`export const isLocalDev = COMPILER_CONSTANT && previous logic`.

We already have a `--fortesting`. I think `gulp dist` should just compile AMP in a way that `COMPILER_CONSTANT` is always `false`.

Hostly, it might be cool if we throw out the current guessing and just let this evaluate to be constant true, unless `gulp dist` ran.

**Comment by erwinmombay** [comment]
yeah that would be cool, thought it would be possible through the process.env.NODE_ENV value but we inject that through the wrapper.  would it be possible to inject that at the compiler level? this would also get rid of some `getMode().minified` code

**Comment by cramforce** [comment]
Same deal, but no real reason to use `process.env.NODE_ENV`. We can use a better named variable.

**Comment by erwinmombay** [comment]
yeah but that would be more in line with non closure compiler code (babel/node etc)

**Comment by cramforce** [comment]
Hmm, I don't feel strongly, but it does seem pretty awkward to use an environment variable.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
