### ISSUE TITLE
Amp-iframe video blocked from playing on Firefox - need crossorigin attr allowed

### ISSUE THREAD

**Issue by abigailoswald** [ampproject/amphtml#30131]
## What's the issue?

On the firefox browser, we are getting this error: `CookieBlockedForeign=Request to access cookies or storage on “X” was blocked because we are blocking all third-party storage access requests and content blocking is enabled.` According to the [Firefox docs](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Storage_access_policy/Errors/CookieBlockedForeign?utm_source=devtools&utm_medium=firefox-cookie-errors&utm_campaign=default), we can fix this by adding a `crossorigin=anonymous` attribute to the relevant element. However, `amp-iframe` does not allow this attribute. It was added for `amp-video` [here](https://github.com/ampproject/amphtml/issues/10209), could we get it added for `amp-iframe` as well? Or is there another way around this that I am not aware of? Thanks
## What browsers are affected?

Only Firefox has this issue. The video plays on Chrome and Safari just fine. Note: you can manually click the `i` in the toolbar on FF, select `Turn off blocking for this site`, and the video will play.

## Which AMP version is affected?

AMP Version: 2008220050001

**Comment by krdwan** [comment]
Related to: https://github.com/ampproject/amphtml/issues/30150
