### ISSUE TITLE
remove amp-script deployment if else block

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#30142]
remove amp-script deployment if else block once https://github.com/ampproject/worker-dom/pull/929 is in place

**Comment by samouri** [comment]
Whats the status of this issue?

**Comment by erwinmombay** [comment]
this can be closed as the `if else` logic was removed since the PR for https://github.com/ampproject/amphtml/commit/44d2d777c74b88bbde0f3197aa5b5403d88868cf#diff-586cddcb20b3d24635a884ba630a84119d063df527b9397d9aded7d16e2fb481 was merged AFTER https://github.com/ampproject/worker-dom/pull/929
