### ISSUE TITLE
[Validator] Allow all layouts in amp-social-share

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#3014]
With #2946 getting close to being ready. We'd like to update the validator for `amp-social-share` element to allow all layouts and not just `fixed`.

**Comment by mkhatib** [comment]
One more change would be to allow `amp-social-share` inside `amp-sidebar`.

**Comment by mkhatib** [comment]
@dvoytenko can we go ahead and move `amp-social-share` out of experiment?

**Comment by powdercloud** [comment]
You may want to wait til we have the validator rolled out for less confusion.
