### ISSUE TITLE
AMP Story Player. Exit control not visible

### ISSUE THREAD

**Issue by rnkimani** [ampproject/amphtml#30179]
## What's the issue?
- I have implemented the exit control but it's not visible.
- It looks like this element could need a z-index

## Which AMP version is affected?
- latest
- Ref [#28416](https://github.com/ampproject/amphtml/issues/28416)

cc @Enriqe

**Comment by newmuis** [comment]
As far as I know, this should be addressed by the UI control refactor, right @Enriqe?

**Comment by Enriqe** [comment]
Yes, this will be addressed in https://github.com/ampproject/amphtml/issues/30031
