### ISSUE TITLE
Filtering Multiple Options

### ISSUE THREAD

**Issue by virgiltu** [ampproject/amphtml#30177]
Anybody has any ideas how to filter multiple options.  I am working on a eCommerce website and looking at the examples I can filter items by one filter option, but almost all our products we have a minimum of 5 filter options. I really appreciate any help.  

https://amp.dev/documentation/examples/e-commerce/product_browse_page/

**Comment by nainar** [comment]
You could follow the example here: https://amp.dev/documentation/examples/e-commerce/product_browse_page/#filter-and-sorting - add more options.
