### ISSUE TITLE
🌸 Cherry-pick request for #30170 into #30086 & #30147 (Approved)

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#30175]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
|  #30170 |  #30170 |     **YES**     | **YES** | **NO** | #30086 #30147                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

A recent browser change requires iframes to explicitly set `allow="autoplay"`, otherwise the media won't be autoplayed. Use cases where the `amp-story-player` is expected to autoplay the stories are are not working because of this.

# Mini-postmortem

## Impact

- Player users expecting media to autoplay.

## Action Items

- #30180 Adds integration test

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by alanorozco** [comment]
LGTM on video effects.

**Comment by mrjoro** [comment]
Confirmed with @kristoferbaxter this is safe, so LGTM.

**Comment by danielrozenberg** [comment]
Cherry-picks are complete, @Enriqe please verify
