### ISSUE TITLE
Pass Consent String from outside

### ISSUE THREAD

**Issue by opencmp** [ampproject/amphtml#30195]
Many publishers maintain websites which are a hybrid of normal HTML and AMP HTML, so the CMP will show up twice for every user as they navigate between HTML and AMP pages. Is there a way to pass an existing Consent String to amp-consent so that amp-consent doesn't show up?

**Comment by micajuine-ho** [comment]
Yes, via check `checkConsentHref`, documentation [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-consent/amp-consent.md#checkconsenthref).

Within the response from that endpoint, you can return a consent string that would be shared between the sites, and a boolean `consentRequired` value to signal to AMP to show or hide the prompt.

Please let me know if you need help setting up this config.
