### ISSUE TITLE
Intent to implement: Support for Lotame Analytics

### ISSUE THREAD

**Issue by Tonsil** [ampproject/amphtml#3020]
Implement ability to collect and send analytics data to Lotame Solutions, Inc.

**Comment by Tonsil** [comment]
This should have the Labels "INTENT TO IMPLEMENT",  "Related to: Analytics",  "Type: Feature",  "3P"

**Comment by dvoytenko** [comment]
heads up to @avimehta

**Comment by avimehta** [comment]
thanks. Added a few comments to the PR.

**Comment by Tonsil** [comment]
So, out of curiosity (and because people are asking me) what happens next with this? Is there anything else I need to do on my end? Is there a way I can monitor progress and know when to expect my changes to be made available? Thank you.

**Comment by rudygalfi** [comment]
Based on the merge date for #3021, I believe this should be available in the production release.

There should be nothing further for you to do and the configuration should be useable via the `type` attribute on amp-analytics now.
