### ISSUE TITLE
AMP-Story with Sibling tag 🚨 Error

### ISSUE THREAD

**Issue by diwakaran1dan** [ampproject/amphtml#30212]
Is there a way to implement AMP - story with Sibling tags like `<h1> or <div>`

**Comment by newmuis** [comment]
No, an AMP story must be the only child of `<body>`.

If you need to include other content on the page besides the story itself, you should create a separate page that [embeds the story using `<amp-story-player>`](https://amp.dev/documentation/guides-and-tutorials/integrate/embed-stories/) and includes any other additional elements.
