### ISSUE TITLE
Flakey test: 'should perform polling handshake'

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#30217]
**summary**
A test is causing flakes.

File: extensions/amp-viewer-integration/0.1/test/integration/test-messaging-handshake.js
Test: 'should perform polling handshake'

![image](https://user-images.githubusercontent.com/4656974/93107817-17935600-f680-11ea-9f80-14be06af6969.png)

Related: https://github.com/ampproject/amphtml/pull/30124

**Comment by Enriqe** [comment]
I'm still seeing this very often @ampproject/build-cop

**Comment by zhouyx** [comment]
Yes I'm still seeing this after expanding the timeout to 10000ms.  Will take a look.

**Comment by zhouyx** [comment]
Seems related to `--headless`
