### ISSUE TITLE
amp-story: Play/pause button is unlabeled (A11Y)

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#30221]
<img width="319" alt="Screen Shot 2020-09-14 at 12 27 44 PM" src="https://user-images.githubusercontent.com/20525523/93112236-bec6bc00-f685-11ea-870c-9d037b9fdc03.png">

**Comment by Enriqe** [comment]
@mszylkowski would you like to take a look at this one?

**Comment by mszylkowski** [comment]
Sure, didn't see the comment

**Comment by mszylkowski** [comment]
Check #30276 for fix
