### ISSUE TITLE
LCP tripled for certain pages like bmw.com since 2007242032001

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amphtml#30231]
## What's the issue?

According to the Google Search Console there has been a heavy increase for the LCP metric for 700 pages of the bmw.com since mid of August. [This page](https://www-bmw-com.cdn.ampproject.org/c/s/www.bmw.com/en/automotive-life/bring-back-these-classic-games.amp.html) has an LCP of 1.0s for 2007172306003 but 3.4s with 2009040024001 (latest).

## How do we reproduce the issue?

The following steps assume you are using Google Chrome.

1. Open an incognito or guest browser window
2. Go to https://www-bmw-com.cdn.ampproject.org/experiments.html
3. In the "Release channels" section expand "Advanced" and enter `012007172306003`
4. Click "opt-in" and leave the tab open, open a new tab
5. Go to https://www-bmw-com.cdn.ampproject.org/c/s/www.bmw.com/en/automotive-life/bring-back-these-classic-games.amp.html and run a Lighthouse test (running only the Performance tests is sufficient) - observe a LCP of ~1.0s
6. Go back to the Experiments page and opt-in to any release after that like `2007242032001` (following) or `2009040024001` (latest at the time of writing)
7. Go back to the bmw.com tab and run another Lighthouse test - observe a LCP of ~3.4s

## What browsers are affected?

Tested in Chrome, most likely all browsers.

## Which AMP version is affected?

Affects 2007242032001 and higher.

**Comment by nainar** [comment]
@ampproject/wg-performance @kristoferbaxter

**Comment by kevinkimball** [comment]
Hi @matthiasrohmer , I am not able to replicate your results. Following the instructions you provided, I saw similar LCP for `2007172306003` and `2007242032001`. Using webpagetest.org I got similar results: 

`2007172306003`:
https://www.webpagetest.org/result/200915_JZ_558435894f1e3335136995678324e669/

`2007242032001`:
https://www.webpagetest.org/result/200915_RP_908cd09da43ac2750c188c937a07aa67/

By clicking into the details tab you can confirm the correct RTV is being loaded. 

Therefore I believe this is something related to your test environment. However, if you can provide additional details I will take another look.
