### ISSUE TITLE
I2I: Intercept click navigation on 3P iframes with a glass pane

### ISSUE THREAD

**Issue by ammaxwell** [ampproject/amphtml#30245]
## Describe the new feature or change to an existing feature you'd like to see
Under extremely specific conditions [see below], we would like our AMP Viewer to capture clicks on iframed content rather than allowing clicks to end up triggering navigations. 

Combined with #27252, this allows internal navigations to continue navigating within the page, while links off the page and clicks on iframed content that could include navigations (for example, an `<amp-ad>`), are intercepted by the viewer. 

We will accomplish this by adding an invisible overlay on top of tags that include iframes that can intercept clicks. In some cases, it may be possible to send the actual link a user would have clicked on to the viewer, but in general, we will not be able to tell what content is within the iframe.

Specific conditions:
1. AMP Viewer origin is either a trusted origin or localhost.
2. AMP Viewer has the "interceptNavigation" capability.
3. AMP doc is opted in via including "allow-navigation-interception" attribute on the <html> tag.

## Describe alternatives you've considered
We can use sandbox attributes to block navigations, but then the viewer also wouldn't know an interaction happened. As far as I can tell, there isn't a clean way to block navigations from iframed content while still allowing the viewer to know the user clicked on the element. 

## Additional context
#27252 added the new viewer capability and allowed viewers to intercept navigation from links within the AMP document itself. 

cc @choumx

**Comment by cramforce** [comment]
@lannka Are you familiar with the background of this?

**Comment by choumx** [comment]
There's an internal thread, I'll add @ampproject/wg-ads.

**Comment by jpettitt** [comment]
This may break `amp-subscriptions-google` and some `amp-access` implementations please add me to the thread.
