### ISSUE TITLE
amp-springboard-player autoplay is default

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#3024]
## How do we reproduce the issue?
I tried the amp-springboard-player in this example https://github.com/ampproject/amp-by-example/pull/98 and I noticed that it automatically autoplay. I can't find a way to keep it stopped at default.

## What browsers are affected?
I tried on Chrome

## Which AMP version is affected?
I am using version 1460655576651

**Comment by dvoytenko** [comment]
I believe you might be running into some Chrome experiments with turning on autoplay. Could you try on Safari as well?

**Comment by kul3r4** [comment]
Thank you very much, it works ok on Safari and also in Chrome incognito window, so that must be some Chrome experiments as you mentioned. Closing this.
