### ISSUE TITLE
🌸 Cherry-pick request for #30243 into #30147, #30086 (Complete)

### ISSUE THREAD

**Issue by powerivq** [ampproject/amphtml#30244]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #30243  | #30174 #30235  |     **YES**     | **YES** | **YES** | #30147 #30086                                                               |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

The regression broke two ad networks and all users using these two ad vendors do not get any ad at all.

## Why is an LTS cherry-pick needed?

The change has flowed into LTS, and it is serious enough that should not stand there for longer.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

Since 9/8 release, Kargo and Yield Pro ads have stopped working. It was caused by us enabling strict mode for JS (#29929), and the ads using the implicit `this` in the vendor configuration suddenly finding `this` to become undefined. Kargo reached out to us once they noticed their ad is no longer serving on AMP.

## Impact

- All publishers using Kargo and Yield Pro are affected
- All the ads using these two ad vendors fail to load

## Action Items

- Fixed the issue (https://github.com/ampproject/amphtml/pull/30235)
- Determined that the vendors are in the best position to add test coverage, either on amp repo or on their own infra. wg-ads does not have subject-matter expertise on the specific network.

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by cramforce** [comment]
Approved

**Comment by gmajoulet** [comment]
All done, assigning to @powerivq for a post mortem.

**Comment by rsimha** [comment]
_[Cleaning up old CP issues]_ Can this be closed?

**Comment by Enriqe** [comment]
[Cleaning up old CP issues] Can this be closed?
