### ISSUE TITLE
amp-kaltura-player validator

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#3025]
I am working on an example which includes amp-kaltura-player https://github.com/ampproject/amp-by-example/pull/98, but I have validator failures when using it: https://travis-ci.org/ampproject/amp-by-example/builds/126139305

## What browsers are affected?

I tried on Chrome

## Which AMP version is affected?

1460655576651

**Comment by Gregable** [comment]
[`<amp-kaltura-player>`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-kaltura-player/amp-kaltura-player.md) hasn't been implemented in the validator yet. Is this ready for validation?

**Comment by dvoytenko** [comment]
Yes.

**Comment by powdercloud** [comment]
Working on this.

**Comment by powdercloud** [comment]
https://github.com/ampproject/amphtml/pull/3181

**Comment by jridgewell** [comment]
Closed by #3181.
