### ISSUE TITLE
[Story Player] Ability to customize the player background color

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#30258]
We should be able to customize the player background color from the current default grey.

@ampproject/wg-stories

**Comment by Enriqe** [comment]
It's technically possible to do it today with the `--story-player-poster` CSS variable we expose. It's for the poster image, but if none is specified we use the light grey default. 

For example, if you'd want a blue background while the player loads, you could do this:

```
    <amp-story-player>
        <a href="./story.html"
            style="--story-player-poster: blue;">
        </a>
```

Does this work for your use case?

**Comment by gmajoulet** [comment]
Oh cool, thank you! I'm a bit confused as to why we called it `poster` and implemented it as `background`.
Publishers should be able to specify both a poster and a background color (visible before the poster loads).

Current:

```
background: var(--story-player-poster);
```

Suggested fix:

```
background-image: var(--story-player-poster);
background: var(--story-player-background);
```

This should not break any existing implementations.

**Comment by newmuis** [comment]
Sorry, I think this isn't semantic.  Wouldn't it be better for publishers to not specify a `poster` variable, but instead use CSS to set a background of their choice?

I originally proposed it as `poster` as each story in the player could have its story metadata present on its corresponding `<a>` tag, which could mean that once we push the ecosystem to a place where these tags can be retrieved automatically from the story metadata (e.g. through a story's share target, or through tooling), then we can maximize the amount of data we have at our disposal.  Not sure if this plan still makes sense, but I personally am still in favor

**Comment by gmajoulet** [comment]
That sounds great, especially if we want to display a preview card of the next stories, but how do we move forward with this?

We need to:

1. Allow specifying a background, whether it's a color or an image (`--story-player-poster` is not an appropriate variable name to specify a color, and we might want to specify both a color/gradient/whatever feels right, and an image). Side question: can publishers write a simple property `amp-story-player {background-color: red;}` today?
2. Specify a poster for each story that's easy to parse, having either a URL `--story-player-poster: url(https://example.com/poster.jpg)` would be hard to extract, and publishers might specify base64 or svgs. Additionally, we'd need a different name, as `player-poster` refers to the player and not the story.

**Comment by newmuis** [comment]
Yeah, I think this should be per-story and not per-player.  I don't know if we need to parse it; we could always get the image from computed style if we need it.

What I would have loved to do is have an html attribute like `<a href="..." poster="cat.jpg">`, and use `background: attr(poster)`, but this is unsupported.

**Comment by Enriqe** [comment]
> Side question: can publishers write a simple property `amp-story-player {background-color: red;}` today?

The anchor tag background would take over (either poster image if specified or the default grey) since it's sitting on top of the `amp-story-player` element.

> What I would have loved to do is have an html attribute like `<a href="..." poster="cat.jpg">`, and use `background: attr(poster)`, but this is unsupported. We could, of course, do it with javascript, but a big part of the poster's purpose is before the javascript has loaded.

Yeah, we actually already make use of `background-image` in the iframe when the `data-poster-portrait-src` is specified in the `<a>` tag, but like you said that's after the JS is loaded. (Side note: found a bug while trying this out, sending a fix here: #30374)

Would it make sense to create a new CSS variable `--story-player-background ` like suggested by @gmajoulet, and continue using `data-poster-portrait-src` for per-story image for preview of stories, etc..?

**Comment by gmajoulet** [comment]
> Would it make sense to create a new CSS variable --story-player-background like suggested in #30258 (comment), and continue using data-poster-portrait-src for per-story image for preview of stories, etc..?

If we're keeping `--story-player-poster` and use it for the `background-image` property that sounds good to me.

**Comment by westonruter** [comment]
Aside: Using `--story-player-poster` is currently flagged as a validation error in an inline `style` attribute. I've filed this under https://github.com/ampproject/amphtml/issues/30414.

**Comment by Enriqe** [comment]
Closing this in favor of https://github.com/ampproject/amphtml/pull/30753, since publishers will be able to specify an `img` and apply a `background-color` to it if they like.
