### ISSUE TITLE
Intent to implement: `amp-ad` type: 'epl-display'

### ISSUE THREAD

**Issue by sebaperez** [ampproject/amphtml#3026]
Hi all,

I'd like to request the addition of the epl-display type for the amp-ad component.
I think that I've read all documentation there is to read on this topic, but please tell me if I'm missing something.

I already submit an Individual CLA and I am waiting for a response.

Thanks!

Sebastian

**Comment by dvoytenko** [comment]
@sebaperez Could you please provide a link to the "epl-display"? Are you willing to contribute the code for it?

**Comment by sebaperez** [comment]
Hi @dvoytenko 
I've forked to project and worked on a separate branch that can be found here
https://github.com/sebaperez/amphtml/commit/89c9eb41dbf799d9f04f985f597c0cf660d451d8

Thanks for your support!

**Comment by braraujo** [comment]
@dvoytenko here is the link to the ad-server http://www.e-planning.net/

**Comment by sebaperez** [comment]
I made a pull request. This is the link:
https://github.com/ampproject/amphtml/pull/3033

**Comment by sebaperez** [comment]
Please take another look

**Comment by dvoytenko** [comment]
@sebaperez Did you close #3033 PR on purpose?
