### ISSUE TITLE
amp-list renders arrays even with single-item attribute

### ISSUE THREAD

**Issue by riuri** [ampproject/amphtml#30261]
## What's the issue?

The amp-list with the single-item attribute renders arrays, even if there are multiple items. Note that even if this is the intended behavior we are having an accessibility bug by not setting the role in https://github.com/ampproject/amphtml/blob/941616d/extensions/amp-list/0.1/amp-list.js#L631

## How do we reproduce the issue?

1. Open https://playground.amp.dev/
2. Choose amp-list from the examples.
3. Add the `single-item` attribute to any `amp-list` element.
4. Verify multiple items are still being rendered.
5. Verify the accessibility roles `list` and `listitem` are not present.

## What browsers are affected?

Browser-independent.

## Which AMP version is affected?

The issue is present since the `single-result` introduction on 3777b6a. The accessibility mismatch is present since d75636d.

**Comment by samouri** [comment]
This is a bit of a confusing situation. I'd argue that our behavior for allowing a multiple-item `single-item` `<amp-list>` was a mistake on our part. It should have been an error. I don't think this is something we can change going forward.

I can see two potential AIs here:
(1)  Emit a warning when multiple items are supplied to a `single-item` amp-list.
(2) Check if item count `>1` and apply the correct roles within the render pass (currently the role=list is applied at build time, even before the network request has completed). Note that this goes _against_ the author provided intent, which makes me hesitant to implement this AI.

I'll start with (1), and if anyone has strong opinions we can also experiment with (2).

**Comment by samouri** [comment]
I've implemented (1) which emits a warning when `single-item` is used incorrectly. Going to close this issue but anyone should feel free to reopen/comment if they believe we should be pursuing (2).
