### ISSUE TITLE
[amp-story] Update system header UI

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#30274]
![image](https://user-images.githubusercontent.com/5449100/93485703-5835de00-f8d1-11ea-81cf-bee97042178d.png)

![image](https://user-images.githubusercontent.com/5449100/93485720-5cfa9200-f8d1-11ea-81de-dd069e468357.png)

**Comment by gmajoulet** [comment]
cc @ampproject/wg-stories @processprocess
