### ISSUE TITLE
Component amp-subscriptions attribute subscriptions-decorate doesnt work in template

### ISSUE THREAD

**Issue by kalan2001** [ampproject/amphtml#30271]
## What's the issue?

Render a button to subscribe with Google (SwG) doesn't work in a template inside amp-list component.

The expected behaviour were to show a button decorated with Swg Layout, but this button doesn't render.

I connect with "skuMapUrl" property and a JSON to start a specific purchase flow. 

## How do we reproduce the issue?

` <amp-list id="offers" src="products.json" credentials="include" width="300" height="600" layout="responsive">
                     <template type="amp-mustache">
                        <div class="pn-offer-grid__item">
                        <div class="pn-offer-grid__wrapper">
                           <amp-img src="https://s6.eestatic.com/assets_css/img/icon-exclusive.svg" alt="Icono" width="45" height="45" class="img"></amp-img>
                              <h2 class="p.permission pn-offer-grid__name boxTitle permission"> {{title}} </h2>
                              <p class="pn-offer-grid__text pn-offer-grid__text--description">{{description}}</p>
       <button id="{{buttonSwgId}}"  subscriptions-display="true"
                           subscriptions-decorate
                           subscriptions-action="subscribe"
                           subscriptions-service="subscribe.google.com">
                     Subscríbete con Google
                  </button>`

## What browsers are affected?

All browsers

## Which AMP version is affected?

      <script async custom-element="amp-subscriptions" src="https://cdn.ampproject.org/v0/amp-subscriptions-0.1.js"></script>
      <script async custom-element="amp-subscriptions-google" src="https://cdn.ampproject.org/v0/amp-subscriptions-google-0.1.js"></script>
      <script async custom-element="amp-list" src="https://cdn.ampproject.org/v0/amp-list-0.1.js"></script>
      <script async custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.2.js"></script>

Is this a new issue? Or was it always broken? Paste the version of AMP where you saw this issue. (You can find the version printed in your browser's console.)

New issue.
Powered by AMP ⚡ HTML – Version 2009040024003

**Comment by nainar** [comment]
@jpettitt

**Comment by jpettitt** [comment]
I suspect what's happening is the button is not seen because the template renders after SwG tries to decorate the buttons.    We will take a look.
