### ISSUE TITLE
amp-autocomplete responding with a status of 406 ?__amp_source_origin

### ISSUE THREAD

**Issue by artneo7** [ampproject/amphtml#30281]
## What's the issue?
`amp-autocomplete` responding with a status of 406.

<amp-autocomplete … src="https://medsales.com.br/wp-json/neoblog/v1/search/" >

![src](https://user-images.githubusercontent.com/17693529/93528258-71aa4a80-f910-11ea-9f71-6290ac011ff8.png)

Locally it's working just fine, but on production it's adding additional info on the URL: **?__amp_source_origin**

`GET | https://medsales.com.br/wp-json/neoblog/v1/search/?__amp_source_origin=https://medsales.com.br`

![error](https://user-images.githubusercontent.com/17693529/93528267-74a53b00-f910-11ea-9a20-bc8de0171294.png)

## How do we reproduce the issue?
Access https://medsales.com.br/, click the search bar and open the console.

## What browsers are affected?
Tested on Chrome and Firefox.

## Which AMP version is affected?
2009040024003

**Comment by nainar** [comment]
@caroqliu
