### ISSUE TITLE
Story education and viewport warning layer don't overlap well

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#30294]
Story education and viewport warning layer don't overlap well. This can be seen on mobile when using the "split screen" feature:

![image](https://user-images.githubusercontent.com/1492044/93629734-c0122480-f9b6-11ea-9644-d866a5b2aeec.png)

Suggested fix: playing with the z-index so the viewport warning layer covers all the content. Once the user has resized their viewport, they will see the education and/or the story content.

cc @ampproject/wg-stories

**Comment by newmuis** [comment]
My preferred fix is to deprecate the viewport warning layer 😀

**Comment by gmajoulet** [comment]
Haha yep. This one is the "best viewed in portrait mode" though, but I 100% agree for the "screen too narrow/short" one

**Comment by processprocess** [comment]
This could be fixed by deprecating desktop panels mode :)

I agree with the suggestion to adjust the `z-index`.
Maybe a fix for now would be to have the viewport warning on top of the education layer.

**Comment by processprocess** [comment]
The description of #28410 has instructions on how to force the education overlay to display. 
From there we might be able to debug the `z-index` value.
