### ISSUE TITLE
🌸 Cherry pick request for #30264 into #30253 (Pending)

### ISSUE THREAD

**Issue by xiexr151e** [ampproject/amphtml#30293]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #30253 | #30264 |     **YES**     | **NO** | **NO** | #<_RELEASE_ISSUE_>                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

This breaks the rendering of some ads.

# Mini-postmortem

## Summary

This was caused by a missing import, which the missing import was not detected because an `Animation` global also exists in native browser implementation.

## Impact

- This bug was caught in Beta, so this affected Beta users.
- Some ads cannot be displayed in Beta.

## Action Items

- #30264: Added a rule in `.eslintrc.js` to forbid the Animation global and added the unit test to make sure that the correct `Animation.animate` is called.

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by cramforce** [comment]
Approved.

Thanks for including both a test case and a linter defense-in-depth for this issue.

**Comment by gmajoulet** [comment]
To clarify: this is the same fix as https://github.com/ampproject/amphtml/issues/30286 but it has to be cherry-picked in the main AMP beta release, on top of the ads release?

cc @zhouyx

**Comment by xiexr151e** [comment]
@gmajoulet 
This would be a different fix, though I think both fixes are related to ads. It also appears that we are basing our fix from two different releases.

**Comment by gmajoulet** [comment]
Got it, thank you. Just #30264 is needed for this cherry-pick, we don't need the other PR from #30286? 

cc @zhouyx

**Comment by xiexr151e** [comment]
For the issue I listed, we only need the PR I listed.

**Comment by powerivq** [comment]
@gmajoulet Yes. These are two distinct issue. The other cherry pick is only needed for amp4ads-v0.js, not v0.js.

**Comment by zhouyx** [comment]
@gmajoulet. We don't need the other PR from #30286 as long as we are not promoting the cherrypicked version to inabox.

**Comment by gmajoulet** [comment]
Deployed, assigning to @xiexr151e for a post mortem
