### ISSUE TITLE
Intent to implement: amp-analytics type: linkpulse

### ISSUE THREAD

**Issue by tomsky** [ampproject/amphtml#3030]
[Linkpulse](http://www.linkpulse.com/) is used by many European news publishers. I would be great to see Linkpulse implemented as a vendor for the amp-analytics component.

I'll try to get in touch with the people at Linkpulse to see if they can contribute some code.

**Comment by dvoytenko** [comment]
/cc @avimehta for heads up

@tomsky Are you planning to contribute code for this support?

**Comment by nilshofgaard** [comment]
We (Linkpulse) are in contact with @tomsky regarding this and will contribute/maintain the code to support amp-analytics as an analytics vendor.

**Comment by avimehta** [comment]
Awesome, Please cc me once you have a PR ready or need help with any part.

**Comment by dvoytenko** [comment]
Thanks @nilshofgaard @tomsky! Looking forward to pull request!

**Comment by nilshofgaard** [comment]
@avimehta @dvoytenko A PR is submitted with initial support. However I could not figure out how to add the label "NEEDS REVIEW" on the PR itself.

**Comment by avimehta** [comment]
Will review it today.
