### ISSUE TITLE
The Share button doesn't work in the STAMP on Chrome IOS 14

### ISSUE THREAD

**Issue by Ichigo3d** [ampproject/amphtml#30302]
## What's the issue?

The Share button doesn't work in the STAMP on Chrome IOS 14. Under IOS 13.7 it works well. 

## How do we reproduce the issue?

You have to use IOS 14
1. Open Chrome and go to google.com
2. Send search request "cnn news"
3. open any visual story in the search results
4. Tap on the share button  in the story
5. Observe result
Actual result: the share button doesn't response on our action.

## What browsers are affected?

Only Chrome IOS
IOS 14

## Which AMP version is affected?
All versions under IOS14

**Comment by Ichigo3d** [comment]
cc @gmajoulet , @Enriqe

**Comment by gmajoulet** [comment]
cc @ampproject/wg-stories
