### ISSUE TITLE
Google doesn't search amp page

### ISSUE THREAD

**Issue by aiyappann** [ampproject/amphtml#3031]
Hi everyone,

This is the original url of this page - http://www.vikatan.com/news/india/63251-during-the-day-dont-cook-bihar-govt-order.art

This is my amp page related to it - http://www.vikatan.com/other/summer_article.amp.html

The above amp page is static page which is include the original site content.

Is this possible google search my amp page. I just add the above amp page only. there is no amp related file existing in this folder.

anyone please help me.

**Comment by dvoytenko** [comment]
@aiyappann Could you clarify what you mean by "Google doesn't search"?

/cc @ericlindley-g

**Comment by fsencinas** [comment]
Umm... could it be related to the fact that Google no longer yields amp related results or carousel style highlights, regardless no errors in search console?

**Comment by aiyappann** [comment]
Yes, There is no error in amp pages. When i search through my keyword or headline or article head, google only search for my website only, not an amp page.

**Comment by rudygalfi** [comment]
There are cases in which Google Search may choose not to link to the AMP version of a page. If the page doesn't have errors and everything looks OK in Google's Search Console, then you've done everything you can do.

In the future, questions related to appearance in Google are best directed at Google's Webmaster Forum for AMP: https://productforums.google.com/forum/#!topicsearchin/webmasters/category$3Aaccelerated-mobile-pages-amp
