### ISSUE TITLE
🌸 Cherry-pick request for #30188,#30167 into #30086 (Pending)

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#30320]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
|https://github.com/ampproject/amphtml/issues/27036,  | https://github.com/ampproject/amphtml/pull/30188, #30167  |     **NO**     | **NO** | **YES** | #30086                                                               |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

- in certain situations, amp components that use the owners system (carousel, amp-list) fail to render. 
- in certain situations, amp components using `layout=fill` fail to render.

## Why is a Beta / Experimental cherry-pick not needed?

- The fix is already in Beta/Experimental

## Why is an LTS cherry-pick needed?

The bug was merged on aug 7th, LTS was cut from code on aug 29th.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

Issue with intersect-resources experiment where it can use an out-of-date rect. Specifically we were seeing a regression in amp-ad where a carousel 1.0 slides were not being laid out at all. This is due to a mismatch in isDisplayed between the premeasure rect and the more-recent measure within owners.

## Impact

- Users of amp-carousel 1.0
- Users of amp-iframe

## Action Items

- #<_ISSUE_NUMBER_>: (TODO) 

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers @jridgewell

**Comment by samouri** [comment]
The fix is scheduled to be promoted tomorrow anyway. Closing since I was too late with the CP attempt

**Comment by cramforce** [comment]
But let's make sure we don't promote the known-broken week to LTS without the patch

**Comment by samouri** [comment]
> But let's make sure we don't promote the known-broken week to LTS without the patch

From what I can tell, it looks like LTS already has the IO bug. We should probably CP both fixes (https://github.com/ampproject/amphtml/pull/30188, https://github.com/ampproject/amphtml/pull/30167) into LTS.

**Comment by powerivq** [comment]
@cramforce Just to confirm that there's an approval for LTS cherry picking?

**Comment by cramforce** [comment]
That depends on a number of factors such as when it was cut and how the cherry-picked code has baked.

**Comment by samouri** [comment]
> That depends on a number of factors such as when it was cut and how the cherry-picked code has baked.

The active LTS rtv is cut from 8-29. The commit that ramps IO experiment to 100% was merged on [8-07](https://github.com/ampproject/amphtml/pull/29733). Meaning LTS definitely has the bug (I also confirmed [this manually](https://lts-amp-fill-io-bug.glitch.me/)).

> how the cherry-picked code has baked.

What does that mean?

**Comment by cramforce** [comment]
Baked? How confident we are that the cherry-pick is good.

To me a cherry-pick seems in order, but I'd ask @nainar @kristoferbaxter and @rsimha

**Comment by rsimha** [comment]
The last LTS release was on 9/14, the next one is expected on 10/12. Code usually reaches LTS channel after having been on stable channel for at least a week (a.k.a. "baked"). Based on the release tagging labels, #30188 and #30167 don't appear to have hit stable yet. To repeat Malte's question, how confident are we that the CPs are good? If they are low risk, I'm okay with CPing to LTS.

**Comment by kristoferbaxter** [comment]
@samouri Another option to consider, revert the 100% ramp of IO for the LTS branch.

Until the fix has shipped in stable and for more than a few days of feedback, I agree we should hold off picking into LTS.

**Comment by samouri** [comment]
@kristoferbaxter: I'm fine with that option. I'll spin up a revert / revert-revert now

**Comment by samouri** [comment]
Forgot to close the loop here. After my last comment I had an offline discussion with @kristoferbaxter where we made the call to let the fix sit in stable for a bit and then cherry pick to LTS afterwards. Since it has now been ~1 week, without any known regressions, should be ok to CP to LTS

**Comment by Enriqe** [comment]
> Forgot to close the loop here. After my last comment I had an offline discussion with @kristoferbaxter where we made the call to let the fix sit in stable for a bit and then cherry pick to LTS afterwards. Since it has now been ~1 week, without any known regressions, should be ok to CP to LTS

Can we get approval from @ampproject/cherry-pick-approvers to confirm this please?

**Comment by dvoytenko** [comment]
Approved.

**Comment by Enriqe** [comment]
New LTS with CPs is live. @samouri please verify the fix is in and close this issue when PM is complete.

**Comment by samouri** [comment]
Was able to fully confirm the `layout=fill` bug is fixed and partially that the owners system bug is fixed [test pages](https://live-amp-bugs.glitch.me/). The reason I couldn't fully confirm the owners bug was because one of the test ads looks like its no longer valid (the repro case called out in https://github.com/ampproject/amphtml/pull/30188)
