### ISSUE TITLE
[Story] CTAs in Web Stories should be limited to reasonable sizes

### ISSUE THREAD

**Issue by raovs** [ampproject/amphtml#30322]
Some Stories end up with a single tap target that cover a large part of the page, making the Story harder to consume e.g. [page five in this Story](https://newcityadventures.com/stories/urban-hikes-in-san-francisco/).

We should ensure that a CTA tap target does not trigger if it covers more than X% of the screen (to be defined by UX) or if it falls outside the permissible interaction area. 

Further improvements (for discussion) might include making this situation a validation failure, and ensuring that only visually distinct elements can have a tap target.

@hongcatlover @newmuis

**Comment by newmuis** [comment]
Agree the problem needs solving; we'll need to brainstorm on the solution space.

I take it that these cases are intentionally seeking this user experience, so we'd need something robust enough to prevent someone who's seeking it out.  e.g. even if each CTA can only take max 50% width or height, you could still fill the screen with 4 such CTAs.

Open to ideas here, but I think at the very least we could:

1. Increase the gutter size on the pre-tap state (i.e. tapping within X pixels of the left/right edge of the screen should advance you to the next page even when the whole page is a tap target)

**Comment by newmuis** [comment]
Didn't mean to close this 🤦‍♂️
