### ISSUE TITLE
amp-carousel / amp-img fallback failure on Safari (if webp not supported sometimes image get not from fallback)

### ISSUE THREAD

**Issue by bohdan-berezhniy** [ampproject/amphtml#30334]
amp-carousel / amp-img fallback failure on Safari (if webp not supported sometimes the image src gets not from fallback)
{safari version is 13}

Steps to reproduce^
- use safari (desktop version)
- go to https://opt.demo.magefan.top/amp-img/amp-img.html and try to reload 5-9 times  (reload the page at that moment when the page will be ready)

You will see broken image and  image tag that build by amp with src that contain .webp (should be jpg or png because webp is not supported in Safari)

![image](https://user-images.githubusercontent.com/26215478/93869135-17283a00-fcd4-11ea-8714-057849b6be12.png)

![image](https://user-images.githubusercontent.com/26215478/93869113-11325900-fcd4-11ea-96eb-ba469ff2390a.png)

**Comment by Ichigo3d** [comment]
Hello bohdan-berezniy. I can't reproduce this bug. Could you send me under which version it's happen?
