### ISSUE TITLE
Story outlink tooltip "undefined is not an object"

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#30341]
We're getting this error when closing the outlink tooltip:
`"undefined is not an object (evaluating 'b.__AMP_EMBED_DATA__')"`

Reproducible at https://www.gstatic.com/amphtml/stamp/qa/tooltip.html. It doesn't seem to cause any bug though.

![image](https://user-images.githubusercontent.com/1492044/93919107-43938480-fcdb-11ea-961f-8ece77dd4af9.png)

cc @ampproject/wg-stories

**Comment by Enriqe** [comment]
Confirmed repro by 
1. opening tweet and  closing it, then
2. opening link tooltip and clicking outside.

Sent a PR #30369 to fix this
