### ISSUE TITLE
<amp-img>: Invalid length value:  auto

### ISSUE THREAD

**Issue by neerajklite** [ampproject/amphtml#30342]
### Page in question
[https://dev-amp-mors.pantheonsite.io/node/3](https://dev-amp-mors.pantheonsite.io/node/3)
### Error
Console is reporting an error while using srcset and sizes. Since all the three images in the set have different sizes and different crop ratio I am using  layout `fill` attribute with width set to `auto` for all the three viewports `sizes="(min-width: 540px) auto, (min-width: 1280px) auto, auto"` . Everything seems to work fine on the frontend.

What to do with the console error , shall I just ignore it ?

**Comment by samouri** [comment]
@neerajklite: are you sure that `auto` is a valid setting for width? Reading the spec / looking at mdn, I can't find the value "auto" documented anywhere.

**Comment by neerajklite** [comment]
With "auto" none of the browsers seem to complain. Its only when I use this in AMP it shows errors. It works as expected as far as the actual rendering on the frontend is concerned, on amp and without. So I am not sure what is right here.

**Comment by neerajklite** [comment]
No, I am not sure

**Comment by samouri** [comment]
Given that "auto" is an invalid length value, then I believe the error message is justified. Assuming the `sizes` attribute is acting as a no-op (it isn't having an effect on the page) and that behavior is currently as you'd like, the proper action is probably to remove the attribute from the `amp-img` element.

**Comment by neerajklite** [comment]
Can we close the issue ? i think this is not the correct way to do art direction in amp. I used the media attribute on the <amp-img> tag.  `<amp-img alt="grey cat"
    media="(min-width: 470px) and (max-width: 669px)"
    width="450"
    height="340"
    src="/static/inline-examples/images/cat-medium.jpg"></amp-img>` [link](https://playground.amp.dev/?format=websites#share=PCFkb2N0eXBlIGh0bWw+CjxodG1sIOKaoT4KPGhlYWQ+CiAgPG1ldGEgY2hhcnNldD0idXRmLTgiPgogIDx0aXRsZT5DcmVhdGUgcmVzcG9uc2l2ZSBBTVAgcGFnZXMgLSBFeGFtcGxlIDQ8L3RpdGxlPgogIDxzY3JpcHQgYXN5bmMgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC5qcyI+PC9zY3JpcHQ+CiAgPGxpbmsgcmVsPSJjYW5vbmljYWwiIGhyZWY9Imh0dHBzOi8vcHJldmlldy5hbXAuZGV2L2RvY3VtZW50YXRpb24vZ3VpZGVzLWFuZC10dXRvcmlhbHMvZGV2ZWxvcC9zdHlsZV9hbmRfbGF5b3V0L3Jlc3BvbnNpdmVfZGVzaWduLmV4YW1wbGUuNC5odG1sIj4KICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLG1pbmltdW0tc2NhbGU9MSxpbml0aWFsLXNjYWxlPTEiPgogIDxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoOy1tb3otYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1zLWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoO2FuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RofUAtd2Via2l0LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1vei1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1tcy1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1vLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1Aa2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fTwvc3R5bGU+PG5vc2NyaXB0PjxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjpub25lOy1tb3otYW5pbWF0aW9uOm5vbmU7LW1zLWFuaW1hdGlvbjpub25lO2FuaW1hdGlvbjpub25lfTwvc3R5bGU+PC9ub3NjcmlwdD4KPC9oZWFkPgo8Ym9keT4KPGFtcC1pbWcgYWx0PSJncmV5IGNhdCIKICAgIG1lZGlhPSIobWluLXdpZHRoOiA2NzBweCkiCiAgICB3aWR0aD0iNjUwIgogICAgaGVpZ2h0PSIzNDAiCiAgICBzcmM9Ii9zdGF0aWMvaW5saW5lLWV4YW1wbGVzL2ltYWdlcy9jYXQtbGFyZ2UuanBnIj48L2FtcC1pbWc+CiAgPGFtcC1pbWcgYWx0PSJncmV5IGNhdCIKICAgIG1lZGlhPSIobWluLXdpZHRoOiA0NzBweCkgYW5kIChtYXgtd2lkdGg6IDY2OXB4KSIKICAgIHdpZHRoPSI0NTAiCiAgICBoZWlnaHQ9IjM0MCIKICAgIHNyYz0iL3N0YXRpYy9pbmxpbmUtZXhhbXBsZXMvaW1hZ2VzL2NhdC1tZWRpdW0uanBnIj48L2FtcC1pbWc+CiAgPGFtcC1pbWcgYWx0PSJncmV5IGNhdCIKICAgIG1lZGlhPSIobWF4LXdpZHRoOiA0NjlweCkiCiAgICB3aWR0aD0iMjI2IgogICAgaGVpZ2h0PSIzNDAiCiAgICBzcmM9Ii9zdGF0aWMvaW5saW5lLWV4YW1wbGVzL2ltYWdlcy9jYXQtc21hbGwuanBnIj48L2FtcC1pbWc+CjwvYm9keT4KPC9odG1sPg==)
