### ISSUE TITLE
Integration tests on simulated iOS mobile devices

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#30353]
Goal: allow integration tests to run on push/pull builds with GitHub Actions on Mac OS

I've made a couple attempts so far:

1. Attempt a build/test workflow directly

Sample of how this might look for an iOS project by itself: https://sarunw.com/posts/github-actions-for-ios-projects/
PR: https://github.com/ampproject/amphtml/pull/30317

Actually setting this up and figuring out how to run our tests within this framework requires setting up an XCode project on a Mac. I do not have a Mac, so my progress on this is halted.

2. Run tests via Karma plugin

I've found two karma plugins, (`karma-ios-launcher`)[https://github.com/xdissent/karma-ios-launcher] (last updated 7 years ago) and (`karma-ios-simulator-launcher`)[https://developer.aliyun.com/mirror/npm/package/karma-ios-simulator-launcher] (last updated 4 years ago). The first of these would not build on my machine (it's possible it might build on a Mac?)

An attempt was made with the latter of these (https://github.com/ampproject/amphtml/pull/30319), and it appears the GitHub Actions VM could start up the simulator, but immediately failed with an OpenGL issue. Digging in on the issue didn't yield much fruit. Without a Mac, I can't make much more progress on this route either.

**Comment by rsimha** [comment]
_[Infra triage]_ Closing this issue in light of the comment above. This can be reopened if / when we move cross-browser testing to CircleCI and / or support is added for more launchers.
