### ISSUE TITLE
<amp-install-serviceworker src="http://localhost/sw.js"> is not valid AMP

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amphtml#3038]
The validator complains about AMP pages that include install a service worker served over `http`, even if the host is `localhost` (which is special-cased to support service workers, for development purposes). ([Validator source](https://github.com/ampproject/amphtml/blob/master/extensions/amp-install-serviceworker/0.1/validator-amp-install-serviceworker.protoascii#L58).)

````html
<amp-install-serviceworker src="http://localhost/sw.js" layout="nodisplay"></amp-install-serviceworker>
````

Results in:

````
Invalid URL protocol 'http:' for attribute 'src' in tag 'amp-install-serviceworker'. (see https://www.ampproject.org/docs/reference/extended/amp-install-serviceworker.html)
````

(Note that the service worker is actually installed; this is a validator error only.)

[Live demo](https://cdn.ampproject.org/c/s/cdn.rawgit.com/anonymous/847060fb392625e509c12c847de38e7c/raw/7a8835adbc40215a1717b7b5d978c62d5ecf07bd/index.html)--though in this case the service worker doesn't actually install, because the hosts don't match.

**Comment by ericlindley-g** [comment]
Hi @ithinkihaveacat — I think the issue here is that you're going through http rather than https. Feel free to re-open if you still get the same validation error after trying "https://localhost/sw.js"

**Comment by ithinkihaveacat** [comment]
@ericlindley-g The issue is that `https` is difficult to use for local development. (Service workers, which otherwise  require `https`, are whitelisted to work on `http://localhost` for this reason.)

In addition, the extension does actually install the service worker--the issue is that there's a mismatch between the validator's algorithm, and the validation that happens within the code.

I don't seem to have permission to re-open this, but I do think it would be good to resolve this.

**Comment by dvoytenko** [comment]
@ithinkihaveacat It would be fairly misleading to allow `http://locahost` in the validator since the production validator will not allow it later. As it stands, it's sort of a reminder to replace `http://localhost` with the final address and it should be just an error message and not affect the functionality. I.e. you should be able to test your code regardless of what validator says. Are you seeing a different behavior? Or is it just the message that's distracting to you?

**Comment by jridgewell** [comment]
> Are you seeing a different behavior? Or is it just the message that's distracting to you?

From the OP:

> (Note that the service worker is actually installed; this is a validator error only.)

I think that means this can be closed.
