### ISSUE TITLE
Validator spec for amp-video appears to mistakenly allow alt attribute (which serves no purpose)

### ISSUE THREAD

**Issue by westonruter** [ampproject/amphtml#30415]
First noticed at https://github.com/google/web-stories-wp/issues/4708.

In the Web Story editor, I added a video to an story page and it resulted in this markup:

```html
<amp-video
    autoplay="autoplay" poster="https://wordpressdev.lndo.site/content/uploads/2020/09/image.jpeg" 
    artwork="https://wordpressdev.lndo.site/content/uploads/2020/09/image.jpeg" 
    title="Title text" 
    alt="Alt text" 
    layout="fill" 
    loop="loop" 
    id="el-b8f30411-37f5-4e4e-ace6-8b2666470bd2-media"
>
    <source type="video/mp4" src="https://wordpressdev.lndo.site/content/uploads/2020/09/PXL_20200907_180100-trimmed.mp4"></source>
</amp-video>
```

Note the `amp-video` here has both a `title` and an `alt` attribute. 

In the documentation for [`amp-video`](https://amp.dev/documentation/components/amp-video/?format=stories), there is no reference to an `alt` attribute. 

The `alt` attribute is likewise _not_ copied onto the `video` child element by the `amp-video` extension:

```html
<video 
    class="i-amphtml-pool-media i-amphtml-pool-video i-amphtml-fill-content i-amphtml-replaced-content" 
    id="i-amphtml-pool-media-5" 
    playsinline="" 
    webkit-playsinline="" 
    preload="auto" 
    poster="https://wordpressdev.lndo.site/content/uploads/2020/09/image-1.jpeg" 
    muted=""
>
    <source type="video/mp4" src="https://wordpressdev.lndo.site/content/uploads/2020/09/PXL_20200908_112624.mp4">
</video>
```

There is no mention of `alt` on the MDN [documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video) for `video`, nor is there any reference in the [HTML spec](https://html.spec.whatwg.org/multipage/media.html#the-video-element).

Nevertheless, the `alt` attribute is allowed on `amp-video` according to the validator spec:

https://github.com/ampproject/amphtml/blob/6aad5c748b3034916e3523fa5ce2fe5585ba5616/extensions/amp-video/validator-amp-video.protoascii#L37

There is no mention of `alt` elsewhere under `extensions/amp-video/`.

It appears that this `alt` attribute serves no purpose and it may have been a bug to allow it in the first place.

**Comment by westonruter** [comment]
cc @ampproject/wg-caching

**Comment by newmuis** [comment]
`alt` can and should be used for videos within stories

@gmajoulet do you know if there are docs on this?

**Comment by westonruter** [comment]
OK, I can see `alt` referenced in the code under `extensions/amp-story/`:

https://github.com/ampproject/amphtml/blob/6aad5c748b3034916e3523fa5ce2fe5585ba5616/extensions/amp-story/1.0/amp-story-page.js#L1802-L1813

https://github.com/ampproject/amphtml/blob/6aad5c748b3034916e3523fa5ce2fe5585ba5616/extensions/amp-story/1.0/semantic-render.js#L66-L73

But it appears to not be documented. I'm curious why `alt` is supported here while the standard `aria-label` isn't just used instead?

**Comment by Gregable** [comment]
Sounds like the validator is correct here?

**Comment by westonruter** [comment]
The validator seems to have allowed `alt` for `amp-video` for 4+ years ever since 4a8c02908b5d4eb04abbf49bc8a680eb23a5dda2. Nevertheless, the `alt` attribute has not been used since it started to be used by stories for accessibility purposes (as far as I can tell, as it is not used in the `amp-video` extension proper). However, stories is already handling `title` and `aria-label` both of which are standard for `video`, and it's including `alt` as well since it is allowed on `amp-video`. However, to me it seems perhaps it was accidentally included on `amp-video` in the first place.

**Comment by Gregable** [comment]
Yes, but removing it would break stories from the sounds of @newmuis comment. I don't see any harm in leaving it in for validation, even if it has no effect, and there is a risk of breaking existing pages by removing, even if their usage is ineffective.

**Comment by gmajoulet** [comment]
The currently supported attributes are `title`, `alt`, and `aria-label`. We know `alt` is invalid HTML but given how common it is for images we still support it.

To quote Malte: "Folks can use `title` for burned-in text without making a11y trade-offs because they can use `aria-label` for an a11y specific text."
