### ISSUE TITLE
[amp-story-player AMP version] Width & Height attributes not working with layout responsive 

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#30423]
When using the AMP version of the `amp-story-player` with `layout="responsive"`, the `width` and `height` attributes are not respected. 

The amp-story-player CSS seems to force a width of 360px and height of 600px for the component.

For example, if we use `<amp-story-player width="410" height="684" layout="responsive">...`, the width and height stay at 360/600.

It seems to be caused by this CSS that gets applied:

https://github.com/ampproject/amphtml/blob/8fb1a06a49088fb87de9b24646dee2058d910a87/css/amp-story-player.css#L17-L22

But when I delete these default styles, the result is a player with a computed height of `0px`. Here is a [demo](https://amp-story-player-responsive.web.app/examples/amp-story/player-amp.html).

@ampproject/wg-ui-and-a11y, is there anything I have to do on the [amp-story-player](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story-player/0.1/amp-story-player.js) extension to fix this? Is it because I need to propagate the attributes correctly? Or is it caused by the fact we are embedding a shadow DOM with iframes?

@ampproject/wg-stories

**Comment by westonruter** [comment]
See also https://github.com/ampproject/amphtml/issues/30414

**Comment by alanorozco** [comment]
The shadow root breaks the `padding-top: %` sizer element for `layout=responsive`. See [example](https://jsbin.com/rexitakuko/edit?html,output).

This may work if you attach the shadow root to an intermediate element. Instead of:

```js
this.shadow_ = this.element.attachShadow({ ... });
```
do:
```js
const shadowContainer = document.createElement('div');
this.applyFillContent(shadowContainer);
this.element.appendChild(shadowContainer);
this.shadow_ = shadowContainer.attachShadow({ ... });
```
