### ISSUE TITLE
"activate 360" button is hidden by cta layer

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#30420]
#30381 did not resolve this.

`i-amphtml-story-360-activate-button` is currently a descendant of `amp-story-grid-layer` which has `z-index: 2`.
`amp-story-cta-layer` has a `z-index: 3` so it will always be covered.

This element might need to be attached at the `amp-story` or `amp-story-page` level for it to be above content.

<img width="162" alt="Screen Shot 2020-09-28 at 1 03 50 PM" src="https://user-images.githubusercontent.com/3860311/94463517-13d8f680-018b-11eb-9a06-29e3a01bc89e.png">

cc @ampproject/wg-stories @t0mg

**Comment by newmuis** [comment]
My first impression is that we could make this a child of amp-story, and only have 1 instance per story.  It's always hidden, until you reach a page that needs you to activate 360, in which case it is shown.

**Comment by gmajoulet** [comment]
What Jon said sounds good but is a bit tricky to implement. I'd like to suggest an easier option: disabling click on the cta-layer except on its children. Right now all the cta-layer is a click shield and maybe that's the issue.

Eg:
```
cta-layer {pointer-events: none;}
cta-layer > * {pointer-events: all;}
```

Wdyt?

**Comment by processprocess** [comment]
> What Jon said sounds good but is a bit tricky to implement. I'd like to suggest an easier option: disabling click on the cta-layer except on its children. Right now all the cta-layer is a click shield and maybe that's the issue.

We could do that but it could still be covered by content.
Since we need this to display above all content we might need to attach it `to amp-story`

<img width="489" alt="Screen Shot 2020-10-01 at 12 29 27 PM" src="https://user-images.githubusercontent.com/3860311/94837261-09fd0080-03e2-11eb-8557-84568b46b554.png">

**Comment by gmajoulet** [comment]
That makes sense. Can you get inspiration from the "swipe up open attachment" UI that's in the `amp-story-page` code and get to something that is consistent? We're going to keep adding some of these so we could benefit from defining a clear pattern.

**Comment by processprocess** [comment]
I'm hesitant to add code in `amp-story-page` if it's not used on every page.
wdyt about encapsulating this logic in the component, such as in #30479
