### ISSUE TITLE
Add description for how to use <meta name="amp-consent-blocking">

### ISSUE THREAD

**Issue by SebastianZ** [ampproject/amphtml#30430]
## Describe the new feature or change to an existing feature you'd like to see

Not directly a feature request but, as far as I can see, there is no proper documentation for how to use the `<meta name="amp-consent-blocking">` element and how to define to block multiple components.

Currently, the only mention of it is in https://github.com/ampproject/amphtml/blob/master/extensions/amp-consent/integrating-consent.md#before-you-begin, there's no mention at [amp.dev](https://amp.dev/documentation/components/amp-consent/).

So it would be great if some documentation around how to use the `<meta name="amp-consent-blocking">` element would be added.

## Describe alternatives you've considered

From testing and [searching in the AMP project code](https://github.com/ampproject/amphtml/search?q=amp-consent-blocking) I got that there are two supported variants.

1. A comma-separated list of element names within the `content` attribute.
2. Multiple `<meta>` elements, each one holding one element name in its `content` attribute.

Sebastian

**Comment by micajuine-ho** [comment]
closed via #30464

**Comment by SebastianZ** [comment]
Thank you for adding this to the documentation, @micajuine-ho!

Sebastian
