### ISSUE TITLE
Flakey amp-reach-player tests

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#3044]
Chromium 45.0.2454 (Ubuntu 0.0.0) amp-reach-player renders FAILED
	Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

**Comment by ericlindley-g** [comment]
Putting in current sprint to get eyes on the flaky tests (if not fix them)

**Comment by mkhatib** [comment]
This should be fixed with #3197 and #3313 in place. If still happening please re-open.
