### ISSUE TITLE
Can AMP Email CSS media features support dark mode ?

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#30448]
To whom it may concern:

It's very common to support light / dark mode for web page. I've already check AMP Email [Media features](https://amp.dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-css/?format=email#media-features) support list and looks like `prefers-color-scheme` is not exist.

```
<style amp-custom>
:root {
   --logo: url(css/logo-light.svg);
}

.logo {
  background: var(--logo) no-repeat 50% 50% / cover;
}

@media (prefers-color-scheme: dark) {
  :root {
      --logo: url(css/logo-dark.svg);
  }
}
</style>
```

I wonder is it possible to support this media feature ?

Paul

**Comment by Manouchehri** [comment]
This still seems like an issue. I noticed today how horrible AMP emails can look in dark mode. 

![image](https://user-images.githubusercontent.com/7232674/218295530-3265b7d7-5d03-404b-8f67-b05f428c7ed4.jpeg)
