### ISSUE TITLE
Limelight Player Support

### ISSUE THREAD

**Issue by hjanuschka** [ampproject/amphtml#3045]
can we have a `amp-limelight`. as this is one of our biggest show-stoppers to go full-AMP.

a sample embed looks like:

```
<span class="LimelightEmbeddedPlayer" style="display:none;">
    <script src="//video.limelight.com/player/embed.js">
    </script><object class="LimelightEmbeddedPlayerFlash" data=
    "//video.limelight.com/player/loader.swf" height="182" id=
    "limelight_player_fe8a" name="limelight_player_fe8a" type=
    "application/x-shockwave-flash" width="320">
        <param name="movie" value="//video.limelight.com/player/loader.swf">
        <param name="wmode" value="window">
        <param name="allowScriptAccess" value="always">
        <param name="allowFullScreen" value="true">
        <param name="flashVars" value=
        "mediaId=e7b0763fcb874c7a8f7c0060101df3df&amp;playerForm=4e6d373502214c939cc83b20a3b4d67f">
    </object>
    <script>
    LimelightPlayerUtil.initEmbed('limelight_player_fe8a', {embedMode:"html"});
    </script></span>

```

where as the "embedMode":html -> forces the html5 player so maybe the flash object can be stripped.
i would love to have a tag like:

```
<amp-limelight
playerForm="4e6d373502214c939cc83b20a3b4d67f"
mediaId="e7b0763fcb874c7a8f7c0060101df3df"
width=486 height=657
layout="responsive"
></amp-limelight>
```

i am not a limelight official - would you accept a PR from non-officials - if so i ll try to provide one?

**Comment by erwinmombay** [comment]
/cc @rudygalfi @jmadler if we know anybody from limelight

we're always happy to take in any contribution!

**Comment by hjanuschka** [comment]
right now i managed to put the embed/js code in a standalone page, and using `amp-iframe` on the main page

**Comment by cramforce** [comment]
We'd take a contribution from you, but ideally with limelight involved. E.g. they should documented that this works on their side as well.

**Comment by ericlindley-g** [comment]
Closing this for now, due to inactivity, but please feel free to re-open if you'd like to submit an implementation.
