### ISSUE TITLE
🌸 Cherry-pick request for #30449 into #30435 #30436 (Approved)

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#30453]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| [#30449](https://github.com/ampproject/amphtml/issues/30449) | [#30450](https://github.com/ampproject/amphtml/pull/30450) |     **YES**     | **YES** | **NO** | #30435 [#30436](https://github.com/ampproject/amphtml/issues/30436)                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?
On desktop users are not able to click on links on the left side of the bookend.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

While refactoring the pagination button code this use case was not tested and the code was checked in. 

## Impact

- Desktop users were not able to open links on the left side of the bookend.

## Action Items

- Add manual QA instructions to click the buttons on the bookend.
- Test all use cases and contexts when working on a UI element.

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by Enriqe** [comment]
@dvoytenko @cramforce PTAL

**Comment by dvoytenko** [comment]
Approved

**Comment by Enriqe** [comment]
Fix has been CP'd into prod and beta/experimental @processprocess please close this issue when PM is completed.

**Comment by rsimha** [comment]
_[Cleaning up old CP issues]_ Can this be closed?
