### ISSUE TITLE
🌸 Cherry-pick request for #30257 into #30436 (Approved)

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#30452]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #30257 | #30257 |     **NO**     | **YES** | **NO** | #30436                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

I'd like to run the module/nomodule experiment again as soon as possible so that It can be ready for AMP Fest now that https://github.com/ampproject/amphtml/pull/30257 has been merged. 

## Why is a Beta / Experimental cherry-pick not needed?

https://github.com/ampproject/amphtml/pull/30257 is already in beta/experimental

# Mini-postmortem

## Summary

While running the module/nomodule experiment we were still getting bad ad queries numbers. during investigation with the ads team we noticed that there was no amp-runtime CSS in the friendly iframe which in turn would sometimes cause blank ads. this was because of the `filter-import` babel plugin that we used that would magically remove whole programming statements if there was any reference to the css import symbol/identifier that was supposedly to be installed in the friendly iframe. We do not install these css in the ESM/module build since it is assumed to be injected by the cache BUT not in the case of ads.

## Impact

- experiment group was the only people affected
- experiment group would sometimes see blank ads

## Action Items

- https://github.com/ampproject/amphtml/issues/30451: add integration/end-to-end test for module build transferring of CSS case

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by Enriqe** [comment]
@dvoytenko @cramforce PTAL

**Comment by dvoytenko** [comment]
Approved

**Comment by Enriqe** [comment]
Fix has been CP'd into prod @erwinmombay please close this issue when PM is completed.

**Comment by erwinmombay** [comment]
tested in stable looks good . thanks everyone
