### ISSUE TITLE
I2S: Web Player - simplify integrating Stories into your site

### ISSUE THREAD

**Issue by raovs** [ampproject/amphtml#30461]
## Summary

We are planning to significantly improve the Web Player ([amp-story-player](https://amp.dev/documentation/components/amp-story-player/)) in early Q4 to make it the easiest way to incorporate [Web Stories](https://amp.dev/about/stories/) into your websites.

- Allow users to view multiple Stories and swipe between them
- Customize and brand the Story consumption experience
- Integrate your recommendation system and arbitrary custom actions

[**Key capabilities and features coming in Q4**](https://docs.google.com/document/d/1RVuVIeYAEMRuqcp75N3Tq4JsVf8gTAzmIznBZkhWsO8/edit#)

## Timeline

- Early Oct: Developer preview (sign up for developer preview emails [here](https://groups.google.com/a/amp.dev/g/web-stories-devpreview))
- Early Q4: Full launch
- Q4 onwards: Improvements and additional features

## Github Project

- Track progress in the project and the different effort areas in the [wg-stories Player project](https://github.com/ampproject/amphtml/projects/109).

/cc @ampproject/wg-approvers @ampproject/wg-stories

**Comment by cramforce** [comment]
I'm [using this on my own website](https://www.industrialempathy.com/new-on-the-web/) and I have no concerns. LGTM.

**Comment by dvoytenko** [comment]
+1

**Comment by Enriqe** [comment]
Quick update: We plan on launching the dev preview in October 2020. This will include support for custom UI configurations (#30031), fetching more stories from an endpoint (#29864), plus many programmatic APIs (#28416) that will allow developers to perform and listen to actions in the player. 

For whoever is interested, remember to sign up to the Web Stories Dev Preview email list to receive the latest updates:

https://groups.google.com/a/amp.dev/g/web-stories-devpreview

**Comment by Enriqe** [comment]
We just posted an update regarding the player (formerly "dev preview") here: https://github.com/ampproject/amphtml/blob/master/src/amp-story-player/README.md

**Comment by gmajoulet** [comment]
Can we close this ticket @Enriqe?

**Comment by Enriqe** [comment]
What do you think @raovs? Do you want to keep this open until the Q4 update? or should we close this now that we have sent the November update?

**Comment by raovs** [comment]
I'd suggest keeping this open till the end of Q4 (since there are still big
elements of the I2S in flight), then close and have a new one for Q1
deliverables.
