### ISSUE TITLE
I2I: Allow header tags such as h1 and h2 to be rendered on amp-mustache 

### ISSUE THREAD

**Issue by teles** [ampproject/amphtml#30470]
## Summary

As described in amp-mustache documentation the output of "triple-mustache" is sanitized to only allow the following tags: a, b, br, caption, col, colgroup, code, del, div, em, hr, i, ins, li, mark, ol, p, q, s, small, span, strong, sub, sup, table, tbody, time, td, th, thead, tfoot, tr, u, ul.

I'm trying yo use amp-list plus amp-template to insert some text from a backend endpoint into a AMP page. This text is meant to attend some SEO criteria and because of that te use of header tags such as h1, h2 and h3 are really necessary.

The fact that <amp-template> does not support h1, h2, h3 make is useless for SEO purposes.

## Motivation

I guess allow amp-template to be rendered may not provide any issue to AMP, but not allowing important SEO tags makes amp-list almost useless to SEO purposes.

Having no h1 and h2 tags allowed in AMP force development to avoid using <amp-list> and render all texts in backend using a different approach just like django templates or a similar. For a teams focused on front-end it may be a issue.

## Additional context

Here I just created an example of how <amp-template> removes header tags on sanitization proccess:
https://codepen.io/teles/pen/qBZGJXV

All the following code is a copy from the codepen above.

```html
<amp-script id="dataFunctions" script="local-script" nodom></amp-script>
<script id="local-script" type="text/plain" target="amp-script">
function parseMarkdown(markdownText) {
    const response = ("\n" + markdownText)
        .replace(/(\n|\r)/gim, "\n")        
        .replace(/^\n([^\n#]+)\n/gim, "<p>$1</p>")
        .replace(/^#\s(.*)?/gim, "<h1>$1</h1>")
        .replace(/^##\s(.*)?/gim, "<h2>$1</h2>")
        .replace(/^###\s(.*)?/gim, "<h3>$1</h3>")        
        .replace(/\[(.*?)\]\((.*?)[\s"']["'](.*?)["']\)/gim, "<a href='$2' alt='$3'>$1</a>")
	    .trim();
    console.log(response);
    return response;
}

function getRemoteData() {
    return fetch('https://www.vivadecora.com.br/api/3/product-category-descriptions/produtos')
      .then(resp => resp.json())
      .then(resp => {
        return [{
            subtitle: parseMarkdown(resp.content_subtitle),
            body: parseMarkdown(resp.content_body)
        }];    
    });
  }
  exportFunction('getRemoteData', getRemoteData);    
</script>

<amp-list
    id="amp-list"
    width="800"
    height="600"
    layout="responsive"
    src="amp-script:dataFunctions.getRemoteData"
    items="."
>
  <template type="amp-mustache">
    <div class="content">{{{body}}} </div>
  </template>
</amp-list>
```

## Launch tracker

https://docs.google.com/spreadsheets/d/18ypGgYjsyMatZgGejPCL7JKrXr9H16HB2TaRkshAH9o/edit#gid=0

/cc @ampproject/wg-approvers

**Comment by jaygray0919** [comment]
bump
