### ISSUE TITLE
[Story] Support native img tag with loading=lazy attribute

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#30474]
With[ the intent to deprecate `amp-img`](https://github.com/ampproject/amphtml/issues/30442) and replace them with `<img loading=lazy>` tags, the story runtime needs to:

- Check that the way `img` tags are positioned away from the visible viewports still lazy load images as we expect it (ie: pages with `distance > 2` does not load `img`, `distance <=2` does load them)
- Check that all the code tracking resources load (Story renderer service, page load events...) through the `amp-img` tag also work with the `img` tag
- Update the validation rules to allow for the `img` tags, and potentially enforce the `loading=lazy` attribute

cc @ampproject/wg-stories

**Comment by newmuis** [comment]
I would also be willing to bet that there are selectors (either in `querySelector` calls or in CSS) that explicitly expect `amp-img`
