### ISSUE TITLE
amp-lightbox: Invalid trust when going "forward" in history

### ISSUE THREAD

**Issue by chasefinch** [ampproject/amphtml#30493]
## What's the issue?

When opening an amp-lightbox, the browser's "back" button correctly closes the lightbox. However, clicking "forward" again does not reopen the lightbox as expected, but shows an error message in the console:

`Invalid trust for setState`

## How do we reproduce the issue?

The amp.dev example page for amp-lightbox is currently experiencing this issue:

https://amp.dev/documentation/examples/components/amp-lightbox/?format=websites

## What browsers are affected?

Latest Safari & Chrome on macOS, at least.

## Which AMP version is affected?

I saw this issue in 012009190410002 - Assuming it's been around for awhile, as I hadn't used amp-lightbox before.

**Comment by caroqliu** [comment]
Thanks for filing @chasefinch I'm able to see the behavior you describe (back closes lightbox; forward does not reopen lightbox) however I'm not see any error messages in the console.

**Comment by Beethoven** [comment]
And The back button closes the lightbox but not dispatch the lightboxClose event #30136

**Comment by Beethoven** [comment]
And Allow amp-lightbox to be closed by swiping down #28900 like Bookend on Stories

**Comment by chasefinch** [comment]
I don't know if this is related, but I noticed that when updating the state with an AMP.pushState action, this bug (or a similar one) shows up too. You can undo the state change with the back button, but a subsequent forward button doesn't _redo_ the state change.
