### ISSUE TITLE
Allow page filtering for triggers.

### ISSUE THREAD

**Issue by Gueorgi** [ampproject/amphtml#3050]
Since JSON configs can be shared on multiple pages/sites there should be a way to limit what request and/or what triggers run on which page/site without the need of the need to program that dynamically on the server (i.e. allow reuse of a static JSON but control what gets fired on each page).

At bare minimum this should be supported in the triggers and while blacklisting is an option I have slight preference for white-listing like this (missing white-list means all are white-listed):

{
  "requests": {
    "base": "https://example.com/?title=${title}&time=${timestamp}",
  },
  "triggers": {
     "ping": {
        "on": "visible",
        "request": "base",
        "filter": "*.github.com", // Allow this trigger only on github sites.
        "vars": {
          title="GitHub Runs Triggers, others don't: Static JSON."
        }
    }
}

**Comment by Gueorgi** [comment]
P.S. While the most common case is page URL filtering I can see the filter eventually containing AMP vars like ${title} etc. to use for filtering and thus being more flexible. So the name 'filter' vs. 'pageFilter'. Page filtering however seems to me the most important and useful first step.

**Comment by rudygalfi** [comment]
I understand the proposal. Are there particular development environments / arrangements where varying the config server side is challenging?

Server-side definitely feels like a great way to go in generally because the relevant thing to do is always marked up on the pages where it needs to happen.

**Comment by Gueorgi** [comment]
Server side requires:

a) Codding server side (time and resource consuming),
b) Implies dynamic config response (no cache, or no simple caching),
c) Prevents re-using the same static configuration file on a lot of
different pages (i.e, some hits may be allowed on some pages/countries etc.
- now each has to be coded server side),
d) Can't easily access client-side AMP variables like timezone, browser
language, scroll location etc. that could be used for the filtering.

For example if one would like to have a special click hit sent only when
the browser language is french and the document title contains 'In English'
while doing so for millions of pages served from different sites that may
reuse the same config becomes quite tricky quickly if it needs server side
processing. Compare this to a single static JSON with AMP filters.

**Comment by rudygalfi** [comment]
This hasn't been updated in awhile, so I'm going to close.

Please re-open if there's any interest in designing this out further and implementing, or if it needs further discussion.
