### ISSUE TITLE
stories inside infinite scroll (amp-next-page) aren't firing google analytics correctly

### ISSUE THREAD

**Issue by ags1773** [ampproject/amphtml#30514]
## What's the issue?

Stories that are inside `amp-next-page` aren't making the correct API call to google analytics. The query param `dl` wrongly contains the URL of the original story and not the current story.
This is causing incorrect analytics data being shown inside GA console

## How do we reproduce the issue?

1. Go to any of these stories: [Example 1](https://www.eastmojo.com/amp/story/nagaland/2020/10/05/manipur-covid-19-death-count-climbs-to-74-with-3-more-cases) | [Example 2](https://www.vikatan.com/amp/story/business/news/challenges-for-elon-musk-to-start-tesla-operations-in-india)
2. Open network tab, add `google-analytics` as filter
3. Note the value of the query param `dl` for this request.
4. Scroll to the next story. This should make another network call to GA
5. Check the query param `dl` of this request. It should change, but it's the same as the 1st request

## What browsers are affected?
All browsers

## Which AMP version is affected?
amp version: 2009190410002
not sure if it's an old or a new issue

![Screenshot 2020-10-05 at 1 21 01 PM](https://user-images.githubusercontent.com/27222520/95055601-29ad6500-0711-11eb-952c-b38b10ce353a.png)
![Screenshot 2020-10-05 at 1 21 29 PM](https://user-images.githubusercontent.com/27222520/95055984-af311500-0711-11eb-92d3-c346ce4133a8.png)

**Comment by zhouyx** [comment]
Hi @ags1773 Thanks for reporting. You're right, some variables may resolve incorrectly within amp-next-page, and get the parent page's value, and we're aware of this.
