### ISSUE TITLE
I2I: amp-playbuzz internal URL change

### ISSUE THREAD

**Issue by iddanh** [ampproject/amphtml#30525]
## Summary

Following our company's rebranding we would like to modify the url the extension uses to our new domain.

## Motivation

Last year our company rebranded itself from Playbuzz to Ex.Co, see [this](https://techcrunch.com/2019/11/18/playbuzz-becomes-ex-co-and-expands-its-content-marketing-platform/) article for a summary.
The extension currenly uses url's we are planning on deprecating in the near future. We have a new url on the new domain that should be used instead.

## Additional context

I already created a PR with the neccessary changes: https://github.com/ampproject/amphtml/pull/30144

/cc @ampproject/wg-approvers

**Comment by kristoferbaxter** [comment]
Thanks for filing the i2i, looks like broad approval on the PR.

**Comment by samouri** [comment]
Since the PR was merged, are there any outstanding items to be addressed? Can this I2I be closed?

**Comment by zhouyx** [comment]
Close as the change has already been merged.
