### ISSUE TITLE
goToSlide(index=0) does not work on amp-base-carousel

### ISSUE THREAD

**Issue by esng25** [ampproject/amphtml#30523]
## What's the issue?

goToSlide(index=0) does not work on amp-base-carousel. It works on amp-carousel just fine.

## How do we reproduce the issue?

1. Create a amp-base-carousel with three slides. 
2. Create an object with on="tap:base-carousel.goToSlide(index=0)"
3. Index=1..2...etc works fine. 0 does not work.

See jsfidde: [https://jsfiddle.net/d1ces5jm/3/](https://jsfiddle.net/d1ces5jm/3/)

## What browsers are affected?

All browsers are affected as this is a javascript issue.

## Which AMP version is affected?

Using current version.

**Comment by caroqliu** [comment]
Thanks for filing this issue. This should be fixed by changing `||` to `??` here:
https://github.com/ampproject/amphtml/blob/226dc2297048a5bdfad06caaeb92af3d03b216cd/extensions/amp-base-carousel/0.1/amp-base-carousel.js#L452

**Comment by stabee** [comment]
Would I be able to work on this issue?

**Comment by caroqliu** [comment]
Absolutely! I'd be happy to review. Please also be sure to add unit tests and a manual sample to test :)
