### ISSUE TITLE
amp-analytics Comscore is raising "Failed to send image request" 

### ISSUE THREAD

**Issue by kkopachev** [ampproject/amphtml#3054]
## How do we reproduce the issue?

Image analytics transport is raising  "Failed to send image request" for comscore tracking for pageview event. Comscore responding with HTTP 204 with no content.

![upload](https://cloud.githubusercontent.com/assets/2279051/14932208/cd2e75da-0e27-11e6-8f70-e96c6f26a4cd.png)

Page to try https://www.popsugar.de/stars/Fotos-der-Stars-beim-Jupiter-Award-2016-Berlin-40842909/amp#development=1

Chrome, google crawler, others?

Seems to be new issue. 
Powered by AMP ⚡ HTML – Version 1460655576651

related issue https://github.com/ampproject/amphtml/issues/2342

**Comment by cramforce** [comment]
I don't think there is anything we can do here. Maybe file a Chrome bug that the warning is spammy?

**Comment by dvoytenko** [comment]
I think the typical recommendation is to return an actual image to the image requests. For instance, see http://probablyprogramming.com/2009/03/15/the-tiniest-gif-ever

**Comment by kkopachev** [comment]
@cramforce what about google crawler complains?

@dvoytenko Are you suggesting to open ticket with comscore? I am not using anything, but standard `amp-analytics` tag with `type=comscore`.

**Comment by cramforce** [comment]
@kkopachev Sorry, know nothing about Google crawler. 

Opening a ticket with comscore would, indeed, be best. I'd still think user agents should not complain about `204` responses.
