### ISSUE TITLE
Web Stories auto-advance pushes out LCP

### ISSUE THREAD

**Issue by shishirm** [ampproject/amphtml#30557]
**Please only file reports about bugs in AMP here.**

## What's the issue?

For stories that have auto-advance turned on and for which see significant UI changes across pages, the LCP keeps getting pushed out artificially. Is there a way to cap the LCP to not account for auto-advance in Stories?

## How do we reproduce the issue?

[Sample Story](https://www.jumprope.com/g/amp/things-to-do-in-san-diego/EeENntmN) that displays this behavior

## What browsers are affected?

All browsers

## Which AMP version is affected?

All versions

**Comment by gmajoulet** [comment]
Thanks for the bug report Shishir. How do you measure the LCP to see it being pushed out as auto-advance navigates between pages?

I can't repro here: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.jumprope.com%2Fg%2Fthings-to-do-in-san-diego%2FEeENntmN
Can't repro either with the Chrome extension: https://chrome.google.com/webstore/detail/web-vitals/ahfhijdlegdabablpippeagghigmibma?hl=en

cc @ampproject/wg-stories
