### ISSUE TITLE
amp-consent-blocking meta tag is required

### ISSUE THREAD

**Issue by fjanevski** [ampproject/amphtml#30553]
## What's the issue?

As mentioned in the documentation for [blocking behaviour with amp-consent](https://amp.dev/documentation/components/amp-consent/#blocking-behaviors) we can block components either by:
* adding the `data-block-on-consent` attribute to the AMP extension
* adding the `amp-consent-blocking` meta tag with the list of extensions to be blocked

On our pages we are using the `data-block-on-consent` attribute, but from recently we started to receive invalid amp pages with the following message: `The tag 'meta name=amp-consent-blocking' is missing or incorrect, but required by 'amp-consent'.`

## How do we reproduce the issue?

In the AMP [playground](https://playground.amp.dev/) by adding amp-consent and one other component, i.e. amp-analytics. 

## What browsers are affected?

Checked on Chrome 85.0.4183.121

## Which AMP version is affected?

Checked on version: 2009252320001

**Comment by micajuine-ho** [comment]
Hi @fjanevski could you provide a link to one of your pages where you're experiencing this issue?

**Comment by fjanevski** [comment]
hi @micajuine-ho this is one example: https://gutscheine.focus.de/angebote/winterschlussverkauf/amp.

After some investigation we discovered that the issue is not happening on the general amp-consent implementation, but is vendor specific. We are using `ConsentManager` and only when that implementation is in place we face the issue.

Structure with issue:
```
<amp-consent layout="nodisplay" id="consent-element" type="ConsentManager">
    <script type="application/json">
        {
            "clientConfig": {
                "id": <ID>,
                "params": ""
            }
        }
    </script>
</amp-consent>
```

Works with:
```
<amp-consent layout="nodisplay" id="consent-element">
    <script type="application/json">
        {
            "consents": {
                "consentmanager-consent": {
                    "checkConsentHref": "https://consentmanager.mgr.consensu.org/delivery/amp.php?id=<ID>&type=check",
                    "onUpdateHref": "https://consentmanager.mgr.consensu.org/delivery/amp.php?id=<ID>&type=update",
                    "promptUI": "consent-ui"
                }
            }
        }
    </script>
    <amp-iframe id="consent-ui" height="100" width="600" resizable
                sandbox="allow-scripts allow-forms allow-same-origin allow-top-navigation allow-top-navigation-by-user-activation"
                layout="responsive" frameborder="0"
                src="https://consentmanager.mgr.consensu.org/delivery/amp.php?id=<ID>&type=consent">
    </amp-iframe>
</amp-consent>
```

**Comment by micajuine-ho** [comment]
Hi @fjanevski 

> hi @micajuine-ho this is one example: https://gutscheine.focus.de/angebote/winterschlussverkauf/amp.

When I open this page, I do not see the `The tag 'meta name=amp-consent-blocking' is missing or incorrect, but required by 'amp-consent'.` error message. Am I missing something?

**Comment by fjanevski** [comment]
Hi @micajuine-ho, we switched back to the general amp-consent implementation because it was a critical for us. The issue can be reproduced only when using the `ConsentManager` as a `type` of CMP.

**Comment by micajuine-ho** [comment]
I still cannot reproduce this when I test locally using `ConsentManager` type. Can you share the  amp-consent config that triggered this error?

**Comment by fjanevski** [comment]
this is the configuration we used:
```
<amp-consent layout="nodisplay" id="consent-element" type="ConsentManager">
    <script type="application/json">
        {
            "clientConfig": {
                "id": "18009",
                "params": ""
            }
        }
    </script>
</amp-consent>
```
I can see the issue in AMP playground as well for this configuration.

![image](https://user-images.githubusercontent.com/7254205/96008563-fae56c00-0e3f-11eb-8709-bb2f53f71e0e.png)

**Comment by micajuine-ho** [comment]
I see now. This behavior is intentional for `amp-consent` when using a CMP integration. 

See this comment for more information on this: https://github.com/ampproject/amphtml/issues/17742#issuecomment-512564655.

In any case, I will update the documentation to make this more clear.
