### ISSUE TITLE
Facebook Instant Articles

### ISSUE THREAD

**Issue by aiyappann** [ampproject/amphtml#3055]
Hi,

I created sample articles and submit for review process. They given a approval for post our articles in facebook.

![fb_instant](https://cloud.githubusercontent.com/assets/18085749/14935646/8152f990-0ef6-11e6-90ea-88f4bc4c048f.png)

Here there are two tabs are there, one is production and another one is development. So why we use (i.e purpose) production and development in instant article library.

Using instant article library, we have to create a new articles and publish it.

Instead of new articles create from instant article library, i need to import articles through my cms and display to instant article library.

So, i need the api code for config my instant article library. I read the document, but, i don't have any idea to integrate this api ti my cms code. i am a new for integrating api.

please help me.

**Comment by jmadler** [comment]
Hi!  We're not related to Instant Articles, and I'm not sure how to answer your question.  It might make sense to try asking on the Facebook Developers Group: https://www.facebook.com/groups/fbdevelopers

Hope this helps.
