### ISSUE TITLE
amp-video with autoplay is not keyboard accessible

### ISSUE THREAD

**Issue by ilknureren** [ampproject/amphtml#30565]
## What's the issue?

When we add `autoplay` attribute to amp-video, the component is not fully keyboard operable unless user clicks on the video first. This is an accessibility issue for users that navigate the website by keyboard.

## How do we reproduce the issue?

Go to the amp-video autoplay example: https://amp.dev/documentation/examples/components/amp-video/#autoplay
Tab through the page and see if the video plays on tab.
Unless the user clicks on the video, the component is not keyboard operable.

## What browsers are affected?
All browsers

## Which AMP version is affected?
2009252320001

**Comment by kristoferbaxter** [comment]
We have a fixit week planned right after AMP Fest, we'll try to address it then!

Also, if you'd like to submit a fix... we are happy to review.

**Comment by alanorozco** [comment]
Gave it a go on #30565.

@ilknureren This PR ensures that the video is keyboard operable, but I have a couple of questions that I'd love for @caroqliu to weigh in.
