### ISSUE TITLE
[amp-video] First frame not showing on iOS (tested on iPhone)

### ISSUE THREAD

**Issue by avitorio** [ampproject/amphtml#30592]
## What's the issue?

Amp-video doesn't show the first frame of the video on Safari, iOS.

## How do we reproduce the issue?

Visit [this playground link](https://playground.amp.dev/?format=websites&_gl=1*1ba1m0k*_ga*YW1wLWota0pFT2FuMjg0V1F3cVRXalN0bkE.#share=PCFkb2N0eXBlIGh0bWw+CjxodG1sIOKaoT4KPGhlYWQ+CiAgPG1ldGEgY2hhcnNldD0idXRmLTgiPgogIDx0aXRsZT5hbXAtdmlkZW8gLSBFeGFtcGxlIDE8L3RpdGxlPgogIDxzY3JpcHQgYXN5bmMgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC5qcyI+PC9zY3JpcHQ+CiAgPHNjcmlwdCBjdXN0b20tZWxlbWVudD0iYW1wLXZpZGVvIiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC12aWRlby0wLjEuanMiIGFzeW5jPjwvc2NyaXB0PgogIDxsaW5rIHJlbD0iY2Fub25pY2FsIiBocmVmPSJodHRwczovL3ByZXZpZXcuYW1wLmRldi9kb2N1bWVudGF0aW9uL2NvbXBvbmVudHMvYW1wLXZpZGVvLmV4YW1wbGUuMS5odG1sIj4KICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLG1pbmltdW0tc2NhbGU9MSxpbml0aWFsLXNjYWxlPTEiPgogIDxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoOy1tb3otYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1zLWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoO2FuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RofUAtd2Via2l0LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1vei1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1tcy1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1vLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1Aa2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fTwvc3R5bGU+PG5vc2NyaXB0PjxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjpub25lOy1tb3otYW5pbWF0aW9uOm5vbmU7LW1zLWFuaW1hdGlvbjpub25lO2FuaW1hdGlvbjpub25lfTwvc3R5bGU+PC9ub3NjcmlwdD4KPC9oZWFkPgo8Ym9keT4KCjxhbXAtdmlkZW8gY29udHJvbHMKICB3aWR0aD0iNjQwIgogIGhlaWdodD0iMzYwIgogIGxheW91dD0icmVzcG9uc2l2ZSI+CiAgPHNvdXJjZSBzcmM9Ii9zdGF0aWMvaW5saW5lLWV4YW1wbGVzL3ZpZGVvcy9raXR0ZW4tcGxheWluZy53ZWJtIgogICAgdHlwZT0idmlkZW8vd2VibSIgLz4KICA8c291cmNlIHNyYz0iL3N0YXRpYy9pbmxpbmUtZXhhbXBsZXMvdmlkZW9zL2tpdHRlbi1wbGF5aW5nLm1wNCIKICAgIHR5cGU9InZpZGVvL21wNCIgLz4KICA8ZGl2IGZhbGxiYWNrPgogICAgPHA+VGhpcyBicm93c2VyIGRvZXMgbm90IHN1cHBvcnQgdGhlIHZpZGVvIGVsZW1lbnQuPC9wPgogIDwvZGl2Pgo8L2FtcC12aWRlbz4KPC9ib2R5Pgo8L2h0bWw+) in Safari on an iOS device. There's no poster tag in the amp-video component, so it should show the first frame. Unfortunately it only shows a blank image.

## What browsers are affected?

Safari for iOS (iPhone)

## Which AMP version is affected?

I can't inform the version, I believe the latest since it's showing when also using playground.amp.dev.

**Comment by G-Sheridan** [comment]
Should this issue be labeled as Good First Issue?

We are doing research about how to help newcomers onboarding in an open source project and how to accelerate the issue resolving process.
We have developed a tool to automatically label the Good First Issue (GFI), i.e., the issue which is good for newcomers. 
We first extract 72 features from different dimensions of issue reports, such as readability, semantic meaning, associated code snippets, etc, and experimentally investigate to what extent these features correlate with GFI. Results turn out that a large portion of these features do have a medium to large correlation with GFI. 
We then build a machine learning model based on these features to predict GFI. The experiments on a dataset of 12k issues from Github show that 0.90 AUC can be achieved. 

Our tool shows that this issue has a very large possibility to be a GFI. 
Could you please tell us whether it should be labeled as a GFI?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by avitorio** [comment]
Yes, this could be a GFI. Cheers.
