### ISSUE TITLE
[amp-story-auto-ad] Allow developer to specify which page for ad to show up in AMP Story Ad

### ISSUE THREAD

**Issue by jerryluk** [ampproject/amphtml#30590]
## Describe the new feature or change to an existing feature you'd like to see

Currently AMP ad requires the story contains at least 7 pages and the first ad will show up in the 7th page (and after). However, we are doing AMP video story, each page is a 15 -30 seconds videos. It is almost impossible for the ad to show up in this case.

It would be good if there is a way to allow the ad to show up after the first page.

## Describe alternatives you've considered

There is no alternatives right now.

## Additional context

To make publishers successful, ad revenue is very important. Please consider this. If this is a concern for showing ads too often, may be consider this is only for video stories.

**Comment by calebcordry** [comment]
Hi @jerryluk we have plans to tweak this algorithm soon. We are thinking about some sort of time based solution that should help here, but we don't want to gives publishers complete control because of the potential for abuse. 

cc/ @ampproject/wg-monetization
