### ISSUE TITLE
Add general support for referrer header removal on amp-analytics

### ISSUE THREAD

**Issue by j-e-shaw** [ampproject/amphtml#3061]
We would like support for removing the referrer header on amp-analytics tags. This can be done by using a temporary iframe.

Meta tags may also work: http://stackoverflow.com/questions/6817595/remove-http-referer/32014225#32014225

**Comment by cramforce** [comment]
As discussed offline, this could be offered by passing the `no-referrer` option to `fetch` in supported browsers. We will not use iframes for this for well documented performance reasons.

We can use meta-referrer to polyfill the referrer removal where fetch is not supported.

**Comment by rudygalfi** [comment]
Is this still needed? Also, any more detail on motivation for removing the referrer to provide context?

Per @lannka amp-pixel supports this currently.

**Comment by lannka** [comment]
done by #16734
