### ISSUE TITLE
I2I: Support Assist.js on amp pages

### ISSUE THREAD

**Issue by LichaoYin** [ampproject/amphtml#30631]
## Summary

Assist.js is a javascript library third party developers can include on their website to "Assistant enable" it. It provides features such as:

- Assistive "breadcrumbs" (e.g. add items to my Assistant list)
- Voicification

Assist.js currently support regular html pages and this project is to add support for amp pages.

## Design document

https://bit.ly/38evFqN

## Motivation

Amp has limitations to use iframe and javascript, while Assist.js will import multiple iframes, inter-frame communications, backend calls and dom manipulating. 

## Additional context

TODO: add more resources

## Launch tracker

TODO: add project tracker. Tracker template: bit.ly/amp-launch-tracker

/cc @samouri 
/cc @ychsieh
/cc @ianba
/cc @ampproject/wg-approvers

**Comment by zhouyx** [comment]
@LichaoYin 

Could you expand a little bit on the assist.js library and what it does on the page? 

>Amp has limitations to use iframe and javascript, while Assist.js will import multiple iframes, inter-frame communications, backend calls and dom manipulating.

We need to review the usage to make sure that there's no iframes running in the background (invisible iframes), and also the DOM manipulating won't lead to content shift, or negatively impact LCP.

**Comment by LichaoYin** [comment]
> @LichaoYin
> 
> Could you expand a little bit on the assist.js library and what it does on the page?
> 
> > Amp has limitations to use iframe and javascript, while Assist.js will import multiple iframes, inter-frame communications, backend calls and dom manipulating.
> 
> We need to review the usage to make sure that there's no iframes running in the background (invisible iframes), and also the DOM manipulating won't lead to content shift, or negatively impact LCP.

Here is the brief introduction:  in the regular html world, the third-party site imports assist.js script, and embedded several assist.js widgets tags like <google-assistant-add-to-list>. The imported assist.js runtime will initialize and render those tags with google-owned iframe, and also an invisible bottom sheet which shows as the assistant dialog plate.

So, yes, we currently have an invisible bottom sheet.

Here is the [demo](https://developers.google.com/assistant/engagement/assistant-links#rich_assistant_links) of one assist.js breadcrumbs.

**Comment by zhouyx** [comment]
Thanks for the information. 

Sounds to me, we need an invisible bottom sheet (iframe) and a button on the page which can trigger the iframe. The iframe will have 'position:fixed' and stick to the bottom of the page. Is that right? Is it possible to delay the initialization of the iframe only after the user click on the button? 
Though designed for different purposes, this sounds very similar to the `<amp-consent>` UI flow. Which provides a `prompt` action, and the consent dialog iframe. 

>Assist.js will import multiple iframes, inter-frame communications, backend calls and dom manipulating.

A few more questions.
1. Would one iframe be enough, I'm assuming we won't need inter-frame communications either in that case.
2. What kind of DOM manipulation?

**Comment by LichaoYin** [comment]
> Sounds to me, we need an invisible bottom sheet (iframe) and a button on the page which can trigger the iframe. The iframe will have 'position:fixed' and stick to the bottom of the page. Is that right? Is it possible to delay the initialization of the iframe only after the user click on the button?

The invisible iframe currently doesn't have any position style with it. 
Any particular reason to delay the initialization?

> Though designed for different purposes, this sounds very similar to the `<amp-consent>` UI flow. Which provides a `prompt` action, and the consent dialog iframe.
Thanks for the pointer. Let me take a look.

> 1. Would one iframe be enough, I'm assuming we won't need inter-frame communications either in that case.
Unfortunately no.
 
Basically, we have two kinds of iframes: widget buttons and bottom sheet. 
- Each widget has its own iframe with its rendering and initialization. We are thinking to implement as amp component \<amp-assistjs-widget-1\>, \<amp-assistjs-widget-2\> and etc, like \<google-assistant-link-group\> and \<google-assistant-link\> [here](https://developers.google.com/assistant/engagement/assistant-links#proactive_triggering).
- Bottom sheet is a separate iframe and initially invisible. It is loaded by the \<amp-assistjs\> tag and serves as the assistant dialog plate. 

The \<amp-assistjs\> is equivalent to the [deployment](https://developers.google.com/assistant/engagement/assistant-links#deployment) step in the above demo, that clients specify the server address and project information to download the script. The downloaded script, called assist.js runtime, will stay at third-party site scope and initialize the widgets and bottom sheet.

Once everything is set up, when users click the widget, it communicates with the runtime and runtime will pop up the bottom sheet and talk to the corresponding assistant backend to get data. We are considering to optimize the runtime to better fit the amp use case.

> 2. What kind of DOM manipulation?

Basically, load and manipulate the iframe inside, like attaching different views on the bottom sheets

**Comment by samouri** [comment]
@LichaoYin: is there a design document you can attach?

**Comment by LichaoYin** [comment]
Do we need a version for external? we have a internal one

**Comment by ychsieh** [comment]
Design doc: go/assistjs-amp-integration-design

**Comment by alanorozco** [comment]
@ychsieh Please make design doc public.

**Comment by ychsieh** [comment]
Right now we only have an internal one. Will update with a public one with Google-specific stuff removed. Thanks for the reminder.

**Comment by alanorozco** [comment]
@ychsieh @LichaoYin 

During design review a number of `amp-assistant-*` extensions and components were mentioned. [Per third-party naming guidelines](https://github.com/ampproject/amphtml/blob/master/spec/amp-3p-naming.md) these should be renamed to `amp-google-assistant-*`.

**Comment by ychsieh** [comment]
Public design doc: https://docs.google.com/document/d/1yGICsN6uVxpkXTtZ1g3NqqmNq7H-zwU38xXkYDbj-B4/edit?usp=sharing

Alan, thanks for the reminder. Just added a comment for the naming in the design doc.

**Comment by samouri** [comment]
I'd like to point out that there is some amount of overlap with the new proposed "amp read aloud" component: https://docs.google.com/document/d/1611ectDq_S3RXhrNVjk4w6BYPYqKIg69NVdx49TdMOA/edit

**Comment by LichaoYin** [comment]
It is good to know they are also working on open-sourcing their codes!
Assist.js readaloud feature is actually using their technology underneath.

**Comment by ychsieh** [comment]
Closing this issue since we are no longer pursuing assistjs extension.
