### ISSUE TITLE
computeInMasterFrame not working as expected

### ISSUE THREAD

**Issue by renebaudisch** [ampproject/amphtml#30640]
One of our customers wanted to use our amp-ad type="springAds" within amp-carousel.
A demopage ca be found [here](http://398-review-ml-1668-ne-7nklmn.sport1.it/article/5566841)

The amp-ad frames get invoked properly but inside it context.isMaster always return false and so
the queue gets more and more functions that will never be processed:

![image](https://user-images.githubusercontent.com/15980546/95890938-b3e67080-0d84-11eb-9196-0e38f58cec69.png)

I opened a pull request (#30637) to remove computeInMasterFrame inspringAds integration, so if this get's merged you will no longer see the bug on the testsite.

**Comment by renebaudisch** [comment]
#25791

**Comment by renebaudisch** [comment]
What's left? I hoped to be merged before release freeze...

**Comment by calebcordry** [comment]
to/ @ampproject/wg-monetization
