### ISSUE TITLE
🚨 Error: [error message] AMP HTML file can't render because https://cdn.ampproject.org/robots.txt set to disallow

### ISSUE THREAD

**Issue by jnathansdm** [ampproject/amphtml#30654]
Googlebot is blocked by file robots.txt
Type: Image
https://static-cnews-fr.cdn.ampproject.org/ii/w1000/s/static.cnews.fr/sites/default/files/2020_redaction/0-2-1-taille640_5f7f3b2db22ff.jpg

Googlebot is blocked by file robots.txt
Type: Image
https://static-cnews-fr.cdn.ampproject.org/ii/w1000/s/static.cnews.fr/sites/default/files/2020_redaction/joel_and_iphone_photog_2019_john_martin_photo-taille640_5f7f3c64253d5.jpg

Googlebot is blocked by file robots.txt
Type: Image
https://static-cnews-fr.cdn.ampproject.org/ii/w1000/s/static.cnews.fr/sites/default/files/styles/image_375_210/public/balle-tennis-afp.jpg?itok=XIaywzw8

Googlebot is blocked by file robots.txt
Type: Image
https://static-cnews-fr.cdn.ampproject.org/ii/w1000/s/static.cnews.fr/sites/default/files/styles/image_880_495/public/final_rg_20184-1_5f7f3a38637f7_0.jpg?itok=gAa_OaGI

Hi, for each AMP url from our side we have few ressources blocked for Googlebot in the file robots.txt (here the main image cover and few fonts)
https://static-cnews-fr.cdn.ampproject.org/robots.txt

**Error report:** url amp test : https://www.cnews.fr/culture/2020-10-08/le-peintre-joel-blanc-devoile-ses-stars-de-roland-garros-paris-1006213?amp
**First seen:** One week
-->
**Frequency:** ~ For each article published 

You can track each ressource blocked here : 
https://search.google.com/test/rich-results?view=fetch-info&id=pnR5Qx-5ZG2tNq82qYaKbQ

![Capture d’écran 2020-10-14 à 12 42 51](https://user-images.githubusercontent.com/72863758/95979084-610bc800-0e1b-11eb-9566-6e8d117a3586.png)
![Capture d’écran 2020-10-14 à 12 42 56](https://user-images.githubusercontent.com/72863758/95979086-623cf500-0e1b-11eb-83a4-16d78f7ec4bf.png)

If needed, our CDN is Cloudflare. 

Thanks for your help

/cc @ampproject/release-on-duty

**Comment by esginmurat** [comment]
i have same problem
