### ISSUE TITLE
I2I: Server-side render every <amp-img>

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#30650]
`<amp-img>` was historically created to schedule the insertion and load of `<img>` tags. With [`loading="lazy"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading), native `<img>` elements can now be scheduled directly by the browser in a similar way to the AMP runtime.

The AMP runtime already understands how to take static (e.g. server-side-rendered) images that are optimized in cache and in origin when annotated with `data-hero` (#28954).

### Goal

Enable `<img>` SSR transformation for every `amp-img`, except annotating `loading=lazy`:

```js
if (!ampImg.hasAttribute('data-hero')) {
  img.setAttribute('loading', 'lazy');
}
```

When enabling this transformation, [LCP](https://web.dev/lcp) improves for a random distribution of URLs ([dataset](https://docs.google.com/spreadsheets/d/1x3QqGK1KLg9cgfF8_g2_VBklIR3DBO8H7Pbe78PlrR8/edit?usp=sharing), [methodology](https://github.com/alanorozco/amp-img-vs-img)):

![image](https://user-images.githubusercontent.com/254946/95930814-54846280-0d7c-11eb-9df1-555e48fa1caf.png)

Since images are still inside an `<amp-img>` container, [CLS](https://web.dev/cls) remains stable.

### Non-goals

- Allow `<img>` directly.
- Enabling `<amp-img>` SSR in Stories documents (as [excluded in current transform.](https://github.com/ampproject/amp-toolbox/blob/72ac57e0b3d1a57fff3a083abc8b2f6aef7babb3/packages/optimizer/lib/transformers/PreloadHeroImage.js#L81-L83))

/cc @ampproject/wg-performance @jridgewell @rebeccanthomas

**Comment by newmuis** [comment]
I think the heuristic is different depending on the AMP format.  The one you've specified makes sense for AMP websites, but should be different for stories (and, I assume, ads, but I'm not certain)

**Comment by kristoferbaxter** [comment]
My take for stories is we should test the behavior with the goal of removing the usage of amp-img in the long term.

If there are good reasons to continue using it for now, we should create proposals for how we can ultimately resolve these problems in the underlying HTMLImageElement.

**Comment by newmuis** [comment]
Sorry, yes, the goal of removing amp-img and SSRing imgs instead seems viable; the specific heuristic of `if (!ampImg.hasAttribute('data-hero')) { img.setAttribute('loading', 'lazy') }` seems like it might be overly simplistic.  But, SSR definitely seems tractable, just perhaps not in a format-agnostic way.
