### ISSUE TITLE
De-flake or fix skipped tests in `test-amp-carousel.js`

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#30661]
File: https://github.com/ampproject/amphtml/blob/master/test/integration/test-amp-carousel.js
Currently skipped: 6 tests
Related issues: #29783

Some of these tests have been skipped for quite a while. If it's possible to run them, they should be unskipped. If the test can no longer pass, it should be removed.

@ampproject/wg-components could you take a look at these when you have a chance please?

**Comment by samouri** [comment]
I think I just missed that somehow. made a new pr to unskip that test
