### ISSUE TITLE
De-flake or fix skipped tests in `test-amp-user-notification.js`

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#30666]
File: https://github.com/ampproject/amphtml/blob/master/extensions/amp-user-notification/0.1/test/test-amp-user-notification.js
Currently skipped: 13 (out of 44)

None of these skipped tests have a TODO with an associated Flaky Tests issue. If it's possible to run them, they should be unskipped. If the test can no longer pass, it should be removed.

@erwinmombay I see you're an owner of this component. Are you familiar with these tests?

**Comment by rcebulko** [comment]
@erwinmombay Do you think you'll have time to take a look at this in the next week or so?

**Comment by erwinmombay** [comment]
@rcebulko yes thanks for bringing it up again. Ill prioritize this into my sprint. Thanks
