### ISSUE TITLE
AMP Cache with 404 Error on Fonts

### ISSUE THREAD

**Issue by Mich-es** [ampproject/amphtml#30679]
I asked in the Google AMP-Forum:
https://support.google.com/webmasters/thread/76687977?hl=en#

## What's the issue?
i want to implement 3 Font-Styles: Roboto, Oswald 400 & Oswald 500
I do that with custom css like this:

![grafik](https://user-images.githubusercontent.com/58422824/96103602-36337980-0ed8-11eb-8be7-dcbc3d47dfe8.png)

I check the site, everything is fine - the Fonts are loaded. But if i check this on Google, i saw a 404 error on the font.

it makes no difference whether the @font-face with url or without url

## How do we reproduce the issue?

It works:
https://www.wetterprognose-wettervorhersage.de/meldungen/9014-warum-die-winter-so-warm-geworden-sind-und-woran-warme-winter-fruehzeitig-zu-erkennen-sind.amp.html

404 Error in Googles AMP Cache:
https://www-wetterprognose--wettervorhersage-de.cdn.ampproject.org/v/s/www.wetterprognose-wettervorhersage.de/meldungen/9014-warum-die-winter-so-warm-geworden-sind-und-woran-warme-winter-fruehzeitig-zu-erkennen-sind.amp.html?amp_js_v=0.1

![grafik](https://user-images.githubusercontent.com/58422824/96103699-4fd4c100-0ed8-11eb-8556-a1f12d4c02c0.png)

**Comment by willydavid1** [comment]
Hi

> Fonts included via @font-face must be fetched via the HTTP or HTTPS scheme.

https://stackoverflow.com/questions/51150187/amp-font-face-not-working
