### ISSUE TITLE
[Story 360] Resolve "activate" button and video "play" and "eq" graphics

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#30671]
When this happens the ui looks broken.
<img width="425" alt="Screen Shot 2020-10-15 at 3 19 36 PM" src="https://user-images.githubusercontent.com/3860311/96176241-17de7580-0efa-11eb-9ae0-fa088e3399a7.png">

cc @ampproject/wg-stories @hongcatlover

**Comment by newmuis** [comment]
Is that the right fix?  A video is not necessarily does not always just go from loading to loaded.  It can go from loading to loaded and back again multiple times.

**Comment by processprocess** [comment]
Good point. I revised the comment. 
It also overlaps the eq.
