### ISSUE TITLE
Add wg-bento to extensions/ OWNERS

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#30672]
Some of the former wg-ui-and-a11y members no longer are OWNERS for changes in `/extensions` as a consequence of not being formally part of @ampproject/wg-components. Can we add @ampproject/wg-bento as owners to this subtree, too, so we can make changes on `1.0` components as well as help out with reviews during the transition? 

cc @kristoferbaxter

**Comment by kristoferbaxter** [comment]
Happy to fix this, apologies for the confusion during our wg structural changes.
