### ISSUE TITLE
🌸 Cherry-pick request for #30730 into #30741 (Approved)

### ISSUE THREAD

**Issue by powerivq** [ampproject/amphtml#30740]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #<_ISSUE_NUMBER_> | #30730 |     YES     | NO | NO | #30741                                                             |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

https://github.com/ampproject/amphtml/pull/30426 caused a behavior change so that amp-sticky-ad is no longer properly querying the ads. Google Ads team reported the issue, and we had https://github.com/ampproject/amphtml/pull/30730 fixing the problem. Due to this bug affecting almost all usages of amp-sticky-ad, it needs to be fixed before launched.

## Why is a Beta / Experimental cherry-pick not needed?

Needed.

## Why is an LTS cherry-pick needed?

Not needed.

## List the steps to manually verify the changes in this cherry-pick

1. Go to an AMP page with sticky ad (eg, https://www-tomsguide-com.cdn.ampproject.org/c/s/www.tomsguide.com/amp/news/iphone-12-mini-everything-we-know-about-the-smallest-new-iphone)
2. See if the sticky ad loads

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by jridgewell** [comment]
I approve.
