### ISSUE TITLE
amp-fx-collection animate count to X number

### ISSUE THREAD

**Issue by austintude** [ampproject/amphtml#30758]
I'd love to see an amp-fx-collection addition to the group that animated a counting mechanism starting from 0 and progressively increasing the count up to a designated number.

In theory, this should be simple to accomplish with CSS and HTML, but it is currently not supported in AMP.

Ideally, I'd like to see something like this:
@property --num {
    syntax: "<integer>";
    initial-value: 0;
    inherits: false;
  }

 .numberBlock .countMe {
    counter-set: num var(--num);
  }
 .numberBlock .countMe::after {
    content: counter(num);
  }
 .numberBlock .countMe:hover {
    --num: 13492;
  }

And HTML thus:
\<div class="" amp-fx="count" data-to="num" data-speed="1500"\>\</div\>

**Comment by zhouyx** [comment]
@alanorozco I'm not familiar with amp-fx-collection at all. Does the FR make sense to you?
