### ISSUE TITLE
Implement media-based attributes via stylesheet

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#3077]
(Spun off from #1428)

Media-based attributes include: `media`, `sizes` and `heights`.

The handling of `sizes` attribute would look like this:

```
sizes="(max-width: 639px) calc(100vw - 30px), calc(50vw - 15px)"
```

=>

```
#elementId { width: calc(50vw - 15px) !important; }
@media (max-width: 639px) {
    #elementId { width: calc(100vw - 30px) !important; }
}
```

However, the `media` attribute is more problematic. If we follow the previous example, we'd have this:

```
media="(min-width: 400px)"
```

=>

```
#elementId { display: none !important; }
@media (max-width: 639px) {
    #elementId { display: ???? !important; }
}
```

And here's the problem - we can't reset display to any specific value since that can break the layout. In other words, there's no good value to set for `????` above. So far I didn't find a way to inverse this expression either given the limitations with `not` and `or` in media queries.

**Comment by dvoytenko** [comment]
Would really like this, but no solution currently. Dropping to backlog.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please verify first whether the feature proposal is still relevant.

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
