### ISSUE TITLE
Make consent type available for 3p ad iframes

### ISSUE THREAD

**Issue by ruizb** [ampproject/amphtml#30786]
## Describe the new feature or change to an existing feature you'd like to see

Hello, I'd like to get the _consent type_ (TCF v1, v2, CCPA...) value when using `window.context.getConsentState` in a third-party ad iframe, i.e. in a `amp-ad` component.

## Describe alternatives you've considered

There's no alternative to my knowledge since the `getConsentMetadata` function is not available in a 3p ad iframe.

**Comment by renebaudisch** [comment]
Wouldn't this be obsolete when going towards IAB implementation as mentioned here #30385 which is intented to implement?
