### ISSUE TITLE
Reimplement `isReadyToBuild` callback inside of AMP Runtime

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#3081]
Currently, AMP Runtime relies on `isReadyToBuild` callback to decide when the element can be built. Ideally, an `<amp-element>` should be built as soon as `</amp-element>` is parsed. However, there's no callback of this kind available to us. Instead, we want to rely on the "next element parsed" signal. It will work as following:

1. On resource add (`Resources.add()` method) we will NOT call `Resource.build()`, but instead we will push the resource to the `openElements[]` buffer.
2. On resource add (`Resources.add()`) we will scan all elements in the `openElements[]` buffer to see if they have the next element in the document order. "Next element in the document order" is defined as: (a) the element itself has the `nextSibling`, (b) the parent has the `nextSibling`, (c) the parent of parent (and so on) has the `nextSibling`. If we see the "next element in the document order", we remove this element from the `openElements` buffer and call `build()` callback on it.
3. On `DOMReady`, we call `build()` on all remaining elements in the `openElements[]` buffer and no longer buffer new elements. All post-`DOMReady` added resources will be built immediately (as is the case today).
4. Thus we will immediately stop using `BaseElement.isReadyToBuild()` callback and eventually drop it from the `BaseElement` class and its sub-classes.

**Comment by ericlindley-g** [comment]
Slotting in the backlog, but let me know if this has a more specific target (next couple of sprints, or in short term)

**Comment by dvoytenko** [comment]
This should go to the next milestone.

**Comment by mkhatib** [comment]
@dvoytenko thanks for the great writeup! One question for now: Why check "Next element in the document order" instead of just if the element itself have a nextSibling? Why do we need to traverse toward the parent as well?

It seems that checking the element.nextSibling itself should be enough no?

**Comment by mkhatib** [comment]
Ah I might know why. Is it to avoid elements being laid that actually belongs to a parent element that wants to control their layouting schedule? Without the "next element in the document order" check these elements might end up being laid out before the parent element even being built, no? I am not entirely sure this is why we need this, do we even layout before the `documentready`?

**Comment by cramforce** [comment]
@mkhatib If a `nextSibling` exists that is, indeed, enough. But if it does not exist you do not know whether:

- There is no next sibling (which would be super common).
- Or whether it has not been parsed yet.

**Comment by dvoytenko** [comment]
@mkhatib What @cramforce said. Basically, we can consider an element (and its contents) to be fully parsed if the next element in the document order has been parsed or when the whole document has been parsed. Consider this example:
```
<parent1>
  <child1_1></child1_1>
  <amp1>
   <amp1_child1></amp1_child1>
  </amp1>
</parent1>
<parent2>
</parent2>
```

You only really 100% confident that `amp1` has been fully parsed (up to `</amp1>`) when you see `parent2` element in the DOM model. 

Does it make sense?

**Comment by mkhatib** [comment]
Yes absolutely, thanks for the explanation will update the PR.
