### ISSUE TITLE
<iframe> elements do not have a title in Lighthouse

### ISSUE THREAD

**Issue by Zabi09** [ampproject/amphtml#30813]
Added just a youtube video on one of my posts- https://monosnap.com/file/XIXggJgslnAxcMnNLBtHpwA3LXJluT and I am getting this error inside the amp-youtube tag that `<iframe>` elements do not have a title in Lighthouse - https://monosnap.com/file/0R4ehteXwmLk517l2sp0yKq2vNQw1E

**Comment by nainar** [comment]
@zhouyx @realPrimoh was this addressed in the Fixit last week?

**Comment by realPrimoh** [comment]
> @zhouyx @realPrimoh was this addressed in the Fixit last week?

Yes, it just has to be merged. https://github.com/ampproject/amphtml/pull/30834

**Comment by realPrimoh** [comment]
@Zabi09 Hi there, this should be fixed now (after this PR: https://github.com/ampproject/amphtml/pull/30834)
