### ISSUE TITLE
AMP Ima Video pause upon scrolling page

### ISSUE THREAD

**Issue by sultanboss** [ampproject/amphtml#30818]
Hi,

I have implemented APM Ima Video and it is working great. The only problem is when you scroll thru half of the page, the video automatically pauses. If you return back to the top half, video auto-resume. 

How can I make it play all the time without pausing?

Thanks!

**Comment by spormeon** [comment]
i'm a +1 on this,  my video is in a slide rail, so basically always viewable but it still pauses after scroll, i need it to continue playing on scroll

**Comment by micajuine-ho** [comment]
Hi @sultanboss thank you for submitting this issue. Could you or @spormeon  please provide example code that exemplifies this behavior?

**Comment by spormeon** [comment]
i think its quite simply this thats doing it: https://cdn.ampproject.org/v0/amp-ima-video-0.1.js

**Comment by spormeon** [comment]
i can send you a demo page, but dont want to put it in a public forum, how can i send it to you?

**Comment by sultanboss** [comment]
Hi @micajuine-ho thanks for your response. 

This is happening with a fixed positioned video setup. For example:

`<amp-ima-video id="content_video" style="width: 366px; height: 206px; position: fixed; left: 100px; bottom: 100px;" width="640" height="360" layout="responsive" data-tag="tagUrl..." data-src="sourceUrl..." data-delay-ad-request="false" autoplay data-ad-label="Adverts (%s of %s)"></amp-ima-video>`

As you can see I am trying to make it float bottom left corner with fixed position CSS. Also, I have enabled `autoplay`. Now, this seems falling under the initial view area (under autoplay rule) and whenever you scroll down the bottom, it stops pauses the video.

You can check this issue as well. https://github.com/ampproject/amphtml/issues/30471

**Comment by samouri** [comment]
This may be solved as a side-effect of https://github.com/ampproject/amphtml/pull/30647

**Comment by micajuine-ho** [comment]
Awesome, thanks Jake!

**Comment by spormeon** [comment]
its still doing it  when i tested it this morning, this is fixed for amp-ima-video?  as testing this file the behaviour is still there:
//cdn.ampproject.org/v0/amp-ima-video-0.1.js

**Comment by samouri** [comment]
@spormeon: the fix can be verified if you do a build at HEAD. All AMP deployments are paused right now and won't resume until the [election freeze](https://github.com/ampproject/meta-tsc/issues/51) is over.

**Comment by spormeon** [comment]
I think someone just pushed some changes about an hour ago, when everything is meant to be freezed until after elections?  it gives me a break in this:  we basically hacked the amp-ima-video file to work for our need and host the file ourselves but this error started occurring now and no player show on page in effect.
![DevTools_-_ads_vsvl_co_uk_pub000018_scripts_AMPTEST_html_and_CloudWatch_Management_Console](https://user-images.githubusercontent.com/8503167/97640180-223f5a00-1a38-11eb-8ad5-d49479c5d6d9.png)

**Comment by samouri** [comment]
@spormeon: I'm not sure whats going on to produce [that error](https://github.com/ampproject/amphtml/blob/246b09c4f8c80a621289d3b9dcb67436af94a291/src/service/extensions-impl.js#L244-L271). If you think there is an AMP bug, can you file a separate issue with full details for reproduction?
