### ISSUE TITLE
amp-sidebar not opening in the viewer in FF

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#30819]
Trying to open the `amp-sidebar` in an AMP doc opened in the viewer from the Google Search results page results in a failure. The opacity of the story is decreased (expected) but no sidebar is opened (unexpected).

A suspicious warning also appears when clicking the sidebar:
```
[FixedLayer] In order to improve scrolling performance in Safari, we now move the element to a fixed positioning layer: 
<amp-sidebar id="story-sb" class="style-1 i-amphtml-layout…idebar i-amphtml-layout" i-amphtml-layout="nodisplay" layout="nodisplay" side="right" role="menu" tabindex="-1" i-amphtml-fixedid="F0" style="pointer-events: initial; top: calc(0px);" open="">
```

Steps to repro:
1. In firefox mobile emulation, search "fun things to do in nyc"
2. scroll down until you find the corresponding story. (https://www.google.com/amp/story/s/travel.visualstories.com/fun-things-to-do-in-nyc)
3. try opening the sidebar 

![image](https://user-images.githubusercontent.com/5449100/96893596-dea58880-1458-11eb-83bf-50b80d706e16.png)

**Comment by gmajoulet** [comment]
Is it a Story specific or AMP bug? Did you try the feature in a regular AMP document?

**Comment by Ichigo3d** [comment]
the Side bar feature works properly in the amp page

**Comment by Ichigo3d** [comment]
![Uploading Screen Shot 2020-10-22 at 8.30.44 AM.png…]()

**Comment by Ichigo3d** [comment]
<img width="1149" alt="Screen Shot 2020-10-22 at 8 31 42 AM" src="https://user-images.githubusercontent.com/37351864/96895220-0b4da600-1441-11eb-91c8-8f032fc40bb0.png">

**Comment by Enriqe** [comment]
I think that screenshot is from Chrome, and doesn't look like it's opened from the viewer, though? Could we confirm this in an AMP document opened in FF in a viewer please @Ichigo3d ?

**Comment by Ichigo3d** [comment]
Yes, sure. <img width="1671" alt="Screen Shot 2020-10-22 at 8 34 43 AM" src="https://user-images.githubusercontent.com/37351864/96895621-71d2c400-1441-11eb-9289-f138c02d18f8.png">

**Comment by Enriqe** [comment]
I think we'd need to try it on an AMP page opened in the google viewer, I don't thing the amp.dev sample is opened in one.

**Comment by Enriqe** [comment]
Searching for [balance-positivo-para-el-segundo-fin-de-semana-con-salidas-recreativas-en-carlos-paz] and opening the AMP doc in FF yields the same results. This is an amp-sidebar bug. @ampproject/wg-components 

![image](https://user-images.githubusercontent.com/5449100/96897131-4f01d900-145c-11eb-954c-6b89e15ccb71.png)

**Comment by kevinkimball** [comment]
We identified that this was due to an error with the testing environment (Firefox tests were using a iOS 12 user-agent, should be using modern UA that does not use FixedLayer).
