### ISSUE TITLE
Web Vitals: not triggering with timer

### ISSUE THREAD

**Issue by eduardcotmrf** [ampproject/amphtml#30810]
## What's the issue?

I create an amp-analytics with a timer to send the CLS, LCP and FID it doesn't behave like a timer until, i assume, it has all variables calculated. This breaks the timer approach, what I expected is that if at the time of the timer it doesn't have some web vital calculated it just sends a null in that property.

Creating an amp-analytics like:
```
"triggers": {
          "webVitals-all": {
            "on": "timer",
            "timerSpec": {
              "interval": 5,
              "maxTimerLength": 120
            },
             "request":"event"
          }
        },
```

Works fine and sends every five seconds a ping to my request url. But if I add the extraUrlParams of web vitals it changes its behavior:

```
"triggers": {
          "webVitals-all": {
            "on": "timer",
            "timerSpec": {
              "interval": 5,
              "maxTimerLength": 120
            },
             "request":"event",
             "extraUrlParams":{
                "cls":"${cumulativeLayoutShift}",
                "lcp":"${largestContentfulPaint}",
                "fid":"${firstInputDelay}"
             }
          }
```

## How do we reproduce the issue?

1. Go to here: https://codepen.io/trombonecot/pen/wvWoqrg
2. Open network tab and filter by fake.com
3. Try removing the extraUrlParams and reload the page without interacting with it -> You should be seeing calls to fake.com
4. Put back again the extraUrlParams and reload without interacting -> No call sended
5. If you interact, change tab and come back -> starts working

## What browsers are affected?

Tryied with chrome 86.

## Which AMP version is affected?

Current version

**Comment by zhouyx** [comment]
This is expected behavior. 
Requests with variables that resolve asynchronously will only be sent out once those variables has been resolved. It is recommended that we collect those variables separately, not with timer request. 

We should probably document the recommended use case.

**Comment by kevinkimball** [comment]
Yes, what @zhouyx said. Specifically, FID only resolves after user interaction with the page, and CLS/LCP are only resolved after the page becomes hidden/inactive. I think in the case of CLS/LCP it may make sense to also add a timeout (say, send these metrics after 5 seconds) to aid in metrics collection on origin.

**Comment by eduardcotmrf** [comment]
Ok, thanks

**Comment by eduardcotmrf** [comment]
Even though @zhouyx should be calculated with a timer, as the result is accumulative during all the session of the pageview. So if I put a trigger on visible, the normal result could be 0, but after some time, when the user has scrolled, loaded ads, etc... could be bigger. How can I retreive that accumulative measure without a timer?

**Comment by kevinkimball** [comment]
So right now, only the accumulative score is exposed (which is why it waits until the page state changes to hidden). If you setup a separate event on: visible, that only tracked the CLS and LCP metrics, that would be sent when the page changed to hidden. I think zhouyx suggestion is just not to mix those variables into other triggers with other metrics you want collected.

**Comment by eduardcotmrf** [comment]
Ok, I understand then that when the page is inactive that's the CLS it's sended. Thanks!

**Comment by eduardcotmrf** [comment]
One last question, another option that maybe makes sense in order to use web vitals in timers, could be to make the $IF statement in analytics to resolve to false on pending results. So we could do:

```
        "lcp": "$IF(\${largestContentfulPaint}, \${largestContentfulPaint}, 0)"
```

What do you think?

**Comment by kevinkimball** [comment]
@eduardcotmrf The whole if statement would not be evaluated until after largestContentfulPaint is resolved.

**Comment by inakivb** [comment]
It will be awesome that $DEFAULT or $IF evaluate the variables that are deferred to the default or false value, it will alow much simpler implementations

**Comment by zhouyx** [comment]
One proposal was to introduce synchronously resolving version of those macros. cc @micajuine-ho

**Comment by micajuine-ho** [comment]
I do remember this proposal. Are there any other variables we would like to create synchronous version of? I assume the web vitals would be the main focus (except for CLS).
