### ISSUE TITLE
Documentation: Validation table for amp-social-share

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#3082]
When validation rules are in place for amp-social-share, we'll want to clearly communicate these rules in the .md file for debugging. @powdercloud: are you the best person to get these in when ready?

Example validation table can be found at the bottom of the [amp-accordion.md](https://github.com/ampproject/amphtml/blob/master/extensions/amp-accordion/amp-accordion.md)

/cc @mkhatib

**Comment by powdercloud** [comment]
Sure.

**Comment by Gregable** [comment]
We've decided to remove these validation tables. See https://github.com/ampproject/amphtml/pull/3201
