### ISSUE TITLE
I2I: change how storyProgress analytics metric is computed

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#30821]
## Summary

The `storyProgress` is exposed as an `amp-analytics` variable and is meant to let publishers know how much of a story a user has seen, cf its [documentation](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/amp-story-analytics.md#storyprogress).
It is documented as being a value `[0, 1]` but in practice it is `[0, 1[` and never goes to 1. This is problematic as publishers can never figure out if a user has seen all the pages of a story. For a 10 pages story, the first page would have a progress of `0`, and the last page a progress of `0.9`. But if the story had 20 pages, then the last page progress would be `0.95`.

We would like to change this so the `storyProgress` actually is `[0, 1]`.

## Design document

Current implementation to compute `storyProgress`: `currentPageIndex / totalPages`
New implementation to compute `storyProgress`: `currentPageIndex / (totalPages - 1)`, with first page always `0` and last page always `1`.

Examples:

4 pages |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Before | 0 | 0.25 | 0.5 | 0.75 |   |   |   |   |   |  
After | 0 | 0.3333333333 | 0.6666666667 | 1 |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |  
10 pages |   |   |   |   |   |   |   |   |   |  
Before | 0 | 0.1 | 0.2 | 0.3 | 0.4 | 0.5 | 0.6 | 0.6 | 0.8 | 0.9
After | 0 | 0.1111111111 | 0.2222222222 | 0.3333333333 | 0.4444444444 | 0.5555555556 | 0.6666666667 | 0.7777777778 | 0.8888888889 | 1

## Motivation

- More accurate `storyProgress` numbers. As of today it is always off by a page and gives more pessimistic metrics.
- Offers a reliable and easy way (no post processing) to know when users completed the story, and saw all its pages. Progress would be `1`.

## Additional context

This is technically a breaking change and everybody's `storyProgress` analytics would go slightly up. 

/cc @ampproject/wg-approvers @ampproject/wg-stories

**Comment by raxsha** [comment]
Why is the first page 0 instead of a >0 value? I think it would be useful to have a different value when the first page is viewed compared to a story not being viewed at all. ie. If you see the cover page, you've seen a part of the story, not none of the story.

So my proposed change would be: (currentPageIndex + 1) / totalPages 

Before 
0    | 0.25 |  0.5  | 0.75
After 
0.25  |   0.5  | 0.75 | 1

What do you think?

**Comment by gmajoulet** [comment]
Fixed by https://github.com/ampproject/amphtml/pull/31024
