### ISSUE TITLE
AMP broken in IE11

### ISSUE THREAD

**Issue by hungfu** [ampproject/amphtml#30822]
## What's the issue?

AMP pages are not fully functional in Internet Explorer v11

## How do we reproduce the issue?

1. View https://amp.dev/ in Internet Explorer v11
2. Open the console and refresh the page
3. The console will show this SyntaxError:
```
SCRIPT5022: SyntaxError
v0.js (56,392)
```
or this error:
```
SCRIPT5022: SyntaxError
promise.mjs (174,3)
```
4. Click on the search icon next to the language selector in the top right
5. Nothing will happen and it will throw an error in the console
```
SCRIPT438: Object doesn't support property or method 'hasAttribute'
action-impl.js (794,11)
```

## What browsers are affected?

Internet Explorer v11

## Which AMP version is affected?

Discovered this issue today while viewing an AMP page with Internet Explorer v11

**Comment by sidor1989** [comment]
`SCRIPT5022: SyntaxError
v0.js (56,392)`
The same problem.
