### ISSUE TITLE
[amp-story] Navigational safe zones are not respected in desktop 3 panels UI

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#30825]
On our helper to check if a tap was on the edges of the screen, we don't account for the desktop case where the page could be in the middle of the screen.

Here is the piece of code that needs to be fixed:

https://github.com/ampproject/amphtml/blob/7785e940fbac13bb0314d78a2a270d6219c84b66/extensions/amp-story/1.0/page-advancement.js#L548-L560

@ampproject/wg-stories

**Comment by gmajoulet** [comment]
Closed by #31065
