### ISSUE TITLE
amp-facebook not working on firefox

### ISSUE THREAD

**Issue by HelaGone** [ampproject/amphtml#30833]
## What's the issue?
The amp-facebook component does not load anything on Firefox browser mobile and desktop altogether.

Briefly describe the bug.
When using amp-facebook to display a video or post on any website it works fine on most browsers except for Firefox (desktop & mobile)

## How do we reproduce the issue?
Use the amp-facebook component to display any video or post from facebook and try to visualize it on Firefox. 
Easier option: open this [page](https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-facebook&format=websites&_gl=1*nk07nk*_ga*YW1wLXF1U3dZLWExZzVLVjlpZWEtQU9VYlE.) on Firefox  and notice how nothing is displaying

1. Step 1 to reproduce: Generate a valid AMP html page
2. Step 2 to reproduce: use amp-facebook and asign some valid facebook url for a video or post to its data-href attribute
3. Step 3 to reproduce: Open the webpage on Firefox and notice how the component does not load any facebook content

## What browsers are affected?
Firefox mobile & Firefox Desktop

What device type?
Smartphone, Laptop, PC, 

## Which AMP version is affected?
Version 2010132225002

Is this a new issue? Or was it always broken? Paste the version of AMP where you saw this issue. (You can find the version printed in your browser's console.)
Recently noticed: Version 2010132225002

**Comment by eduardogoncalves** [comment]
It's working on v81.0.2 
![image](https://user-images.githubusercontent.com/4308648/97240281-4135b600-17c4-11eb-92fa-7872c1d754a0.png)

**Comment by HelaGone** [comment]
Well this is weird.. I'm Using that same version of FF and it doesn't seem like its working.
<img width="2396" alt="Screen Shot 2020-10-27 at 12 03 05" src="https://user-images.githubusercontent.com/5982932/97342911-771e7d00-184c-11eb-98f1-8e99c48ee741.png">

Also, If I follow the validator url that appears in the dev tools I got this:
<img width="2400" alt="Screen Shot 2020-10-27 at 12 06 55" src="https://user-images.githubusercontent.com/5982932/97352749-acc96300-1858-11eb-9b25-88f8eef01c22.png">
