### ISSUE TITLE
Support amp-list in amp-sidebar

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#3083]
This entails at least two tasks:

1) Implement sidebar resizing to accommodate amp-list contents
2) Whitelist amp-list in validator for amp-sidebar (after [1] is complete)

/cc @powdercloud @sebastianbenz

**Comment by Gregable** [comment]
@zhouyx , @sriramkrish85 Is this ready for validation?

**Comment by sriramkrish85** [comment]
the only thing pending is the whitelisting - seems to be working without any changes needed. 
#3876

**Comment by Gregable** [comment]
This will be live in an hour or so in amp validator.
