### ISSUE TITLE
Investigate layout scheduling inside of amp-sidebar

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#3084]
`amp-sidebar` maintains its own scrollbar. AMP-elements inside of amp-sidebar might not be scheduled correctly and never render because they would be outside the main viewport. `amp-sidebar` probably needs to own the elements inside it and manually schedule them for layout and update its in-viewport properties.

**Comment by mkhatib** [comment]
@sriramkrish85 feel free to move this, just wanted a bug to track what we talked about during our deep dive meeting. Basically this is related to `amp-sidebar` having its own scrolling and AMP will probably not schedule resources for layouting outside the first few viewports of sidebar scrollbar.

**Comment by juliantoledo** [comment]
Now at (https://abe-stage.firebaseapp.com/), the close icon image is missing and when I open the sidebar I get:
`base-element.js:585 Uncaught TypeError: this.c.scheduleLayout is not a functionJSCompiler_prototypeAlias.scheduleLayout @ base-element.js:585(anonymous function) @ amp-sidebar.js:153`
And when I close it:
`base-element.js:593 Uncaught TypeError: this.c.schedulePause is not a functionJSCompiler_prototypeAlias.schedulePause @ base-element.js:593(anonymous function) @ amp-sidebar.js:179JSCompiler_prototypeAlias.Wd @ vsync-impl.js:335`

**Comment by jridgewell** [comment]
Yup.

**Comment by camelburrito** [comment]
With layers this will become obsolete - closing this
