### ISSUE TITLE
amp-facebook component leave blank space below when loaded in landscape mode and changed to portrait mode

### ISSUE THREAD

**Issue by nikhilambre** [ampproject/amphtml#30857]
## What's the issue?

amp-facebook component leave blank space below when loaded in landscape mode and changed to portrait mode. Same way it leave blank space on right side when loaded in portrait mode and changed to landscape. Blank space examples below. It' appears large on actual devices.

No such issue with twitter, youtube and instagram components.

![image](https://user-images.githubusercontent.com/19549131/97172631-4b03ed00-17b5-11eb-9ce7-b02978390c08.png)

![image](https://user-images.githubusercontent.com/19549131/97172691-64a53480-17b5-11eb-9d6e-afd2ec21de19.png)

## How do we reproduce the issue?
Need to load page in ipad or ipad pro and change landscape to portrait or portrait to lanscape.

## What browsers are affected?
All browsers on iPad and iPad Pro

## Which AMP version is affected?
Powered by AMP ⚡ HTML – Version 2010132225002
It could be present with previous versions as well.

**Comment by zhouyx** [comment]
Since this is not an issue with twitter, youtube or instagram components. I wonder if this is related to the facebook implementation within the iframe.

**Comment by kristoferbaxter** [comment]
Another option, this is using attemptResize based on orientation change but is denied since it's in the viewport.

**Comment by nikhilambre** [comment]
Even if element is not in view port and you scroll to it, It doesn't resize on on orientation changed, blank space will be there.
