### ISSUE TITLE
[amp-story] Video playback not working in some players

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#30853]
Something really odd is going on:

(1) find a video in a story
(2) while the video is playing, swipe to next
(3) swipe back
(4) hold to pause

Result: The video won't pause (although the system layer goes away, so I know the runtime is handling the event)

(5) swipe to next
(6) swipe back

Result: Video won't play.  No amount of swiping will fix; only tapping to next and back.

Assuming this is a format bug, but not 100% certain.  Not sure if this is related to touch events, document visibility state, video lifecycle, or something else.

Tested in Google's player in their [web stories experience on Discover](https://blog.google/web-creators/web-stories-discover-search/) on Android.

**Comment by newmuis** [comment]
Could potentially be an interesting data point to try this in the open source player and see if it is reproducible

**Comment by gmajoulet** [comment]
One Google Discover engineer complained about this bug as well and it appears to be isolated to this viewer. They spent quite some time trying to debug it. I'll double check that it doesn't happen in other players before closing.

cc @ampproject/wg-stories
