### ISSUE TITLE
Tracking multiple Video Elements in one Configuration

### ISSUE THREAD

**Issue by dritter** [ampproject/amphtml#30860]
Hi there,

we have a hard time optimizing our tracking configuration. Especially the video tracking configuration is vast, because we have to write a special configuration for every video. It is not possible write a configuration for all players that handles an event. If we do this, only the first player is tracked.

For [reproduction in Playground](https://playground.amp.dev/#share=PCFkb2N0eXBlIGh0bWw+CjxodG1sIOKaoT4KPGhlYWQ+CjxtZXRhIGNoYXJzZXQ9InV0Zi04Ij4KICA8dGl0bGU+YW1wLWJyaWdodGNvdmU8L3RpdGxlPgogIDxzY3JpcHQgYXN5bmMgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC5qcyI+PC9zY3JpcHQ+CiAgPHNjcmlwdCBhc3luYyBjdXN0b20tZWxlbWVudD0iYW1wLWxpZ2h0Ym94IiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1saWdodGJveC0wLjEuanMiPjwvc2NyaXB0PgogIDwhLS0gIyMgU2V0dXAgLS0+CiAgPCEtLSBJbXBvcnQgdGhlIEJyaWdodGNvdmUgY29tcG9uZW50IGluIHRoZSBoZWFkZXIuIC0tPgogIDxzY3JpcHQgYXN5bmMgY3VzdG9tLWVsZW1lbnQ9ImFtcC1icmlnaHRjb3ZlIiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1icmlnaHRjb3ZlLTAuMS5qcyI+PC9zY3JpcHQ+CiAgPHNjcmlwdCBhc3luYyBjdXN0b20tZWxlbWVudD0iYW1wLWFuYWx5dGljcyIgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC9hbXAtYW5hbHl0aWNzLTAuMS5qcyI+PC9zY3JpcHQ+CiAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCxtaW5pbXVtLXNjYWxlPTEsaW5pdGlhbC1zY2FsZT0xIj4KICA8bGluayByZWw9ImNhbm9uaWNhbCIgaHJlZj0iaHR0cHM6Ly9hbXAuZGV2L2RvY3VtZW50YXRpb24vZXhhbXBsZXMvY29tcG9uZW50cy9hbXAtYnJpZ2h0Y292ZS9pbmRleC5odG1sIj4KICA8c3R5bGUgYW1wLWJvaWxlcnBsYXRlPmJvZHl7LXdlYmtpdC1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDstbW96LWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoOy1tcy1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDthbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aH1ALXdlYmtpdC1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1tb3ota2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtbXMta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtby1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QGtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX08L3N0eWxlPjxub3NjcmlwdD48c3R5bGUgYW1wLWJvaWxlcnBsYXRlPmJvZHl7LXdlYmtpdC1hbmltYXRpb246bm9uZTstbW96LWFuaW1hdGlvbjpub25lOy1tcy1hbmltYXRpb246bm9uZTthbmltYXRpb246bm9uZX08L3N0eWxlPjwvbm9zY3JpcHQ+CjwvaGVhZD4KPGJvZHk+CgogIDxwPgogICAgT3BlbiB0aGUgRGV2VG9vbHMgYW5kIGZpbHRlciBmb3IgImNvbGxlY3QiLiBZb3UnbGwgc2VlIG9ubHkgb25lIHBsYXliYWNrIGZvciB0aGUKICAgIGZpcnN0IHZpZGVvLiBCdXQgbm90IGZvciB0aGUgc2Vjb25kIG9yIHRoZSBvbmUgaW4gdGhlIGxpZ2h0Ym94LiBUaGlzIGlzIG5vdAogICAgbGltaXRlZCB0byB0aGUgYnJpZ2h0Y292ZSBwbGF5ZXIsIGJ1dCBhbGwgdmlkZW8gcGxheWVycy4KICA8L3A+CiAgPGJ1dHRvbiBvbj0idGFwOmxpZ2h0Ym94Lm9wZW47bGlnaHRib3hPcGVuOnZpZGVvLTMucGxheSI+CiAgICBPcGVuIExpZ2h0Ym94CiAgPC9idXR0b24+CiAgICA8YW1wLWJyaWdodGNvdmUgaWQ9InZpZGVvLTEiIGRhdGEtYWNjb3VudD0iOTA2MDQzMDQwMDAxIiBkYXRhLXZhcnMtdmlkZW8taWQ9InZpZGVvLTEiIGRhdGEtdmlkZW8taWQ9IjE0MDExNjk0OTAwMDEiIGRhdGEtcGxheWVyLWlkPSIxODBhNTY1OC04YmU4LTRmMzMtOGViYS1kNTYyYWI0MWI0MGMiIGxheW91dD0icmVzcG9uc2l2ZSIgd2lkdGg9IjQ4MCIgaGVpZ2h0PSIyNzAiPgogIAk8L2FtcC1icmlnaHRjb3ZlPgogICAgPGFtcC1icmlnaHRjb3ZlIGlkPSJ2aWRlby0yIiBkYXRhLWFjY291bnQ9IjkwNjA0MzA0MDAwMSIgZGF0YS12YXJzLXZpZGVvLWlkPSJ2aWRlby0yIiBkYXRhLXZpZGVvLWlkPSIxNDAxMTY5NDkwMDAxIiBkYXRhLXBsYXllci1pZD0iMTgwYTU2NTgtOGJlOC00ZjMzLThlYmEtZDU2MmFiNDFiNDBjIiBsYXlvdXQ9InJlc3BvbnNpdmUiIHdpZHRoPSI0ODAiIGhlaWdodD0iMjcwIj4KICAJPC9hbXAtYnJpZ2h0Y292ZT4KCiAgPGFtcC1saWdodGJveCBpZD0ibGlnaHRib3giIGxheW91dD0ibm9kaXNwbGF5Ij4KICAgIDxhbXAtYnJpZ2h0Y292ZSBpZD0idmlkZW8tMyIgZGF0YS1hY2NvdW50PSI5MDYwNDMwNDAwMDEiIGRhdGEtdmFycy12aWRlby1pZD0idmlkZW8tMyIgZGF0YS12aWRlby1pZD0iMTQwMTE2OTQ5MDAwMSIgZGF0YS1wbGF5ZXItaWQ9IjE4MGE1NjU4LThiZTgtNGYzMy04ZWJhLWQ1NjJhYjQxYjQwYyIgbGF5b3V0PSJyZXNwb25zaXZlIiB3aWR0aD0iNDgwIiBoZWlnaHQ9IjI3MCI+CiAgCTwvYW1wLWJyaWdodGNvdmU+CiAgICA8YnV0dG9uIG9uPSJ0YXA6bGlnaHRib3guY2xvc2UiPmNsb3NlIGxpZ2h0Ym94PC9idXR0b24+CiAgPC9hbXAtbGlnaHRib3g+CiAgPGFtcC1hbmFseXRpY3MgdHlwZT0iZ29vZ2xlYW5hbHl0aWNzIj4KICAgICAgICAgICAgPHNjcmlwdCB0eXBlPSJhcHBsaWNhdGlvbi9qc29uIj4KICAgICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICAgICAidmFycyI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgImFjY291bnQiOiAiVUEtWFhYWFhYLTEiCiAgICAgICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICAgICAidHJpZ2dlcnMiOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJ0cmFja1BsYXkiOiB7CgkJCSAgICJvbiI6ICJ2aWRlby1wbGF5IiwKICAgICAgICAgICAgICAgICJyZXF1ZXN0IjogImV2ZW50IiwKICAgICAgICAgICAgICAgICJzZWxlY3RvciI6ICJhbXAtYnJpZ2h0Y292ZSIsCiAgICAgICAgICAgICAgICAidmFycyI6IHsKICAgICAgICAgICAgICAgICAgICAiZXZlbnRDYXRlZ29yeSI6ICJ2aWRlbyBwbGF5ZXIiLAogICAgICAgICAgICAgICAgICAgICJldmVudEFjdGlvbiI6ICJzdGFydCIsCgkJICAgImV2ZW50TGFiZWwiOiAiJHt2aWRlb0lkfSIKICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgPC9zY3JpcHQ+CiAgICAgICAgPC9hbXAtYW5hbHl0aWNzPgo8L2JvZHk+PC9odG1sPg==) open the Network Tab in the Dev Console and filter for `collect`. If you click on the several videos, the Play Event is tracked only on the first player.

The workaround, as said is to define a special configuration for every player, but that leads quickly to a big config.

Expected behavior:
It should be sufficient to write the tracking configuration only once per Event.

I have [a working fix for this](https://github.com/ampproject/amphtml/compare/master...dritter:fix-video-analytics--multiple-selectors), but I am not sure if I did everything right. Especially tests are missing right now. :( I would be glad if someone could guide me through that..

Related Issue: #11380

**Comment by micajuine-ho** [comment]
Hi @dritter thank you for submitting this issue. Amp-analytics currently does not support multi-selctor capabilities for video analytics. This seems like a good idea, especially if it leads to a large reduction in config size for vendors and publishers.

Can you describe or share what a typical config would look like to track multiple videos? 


> Related Issue: #11380

This issue is for multiple selectors for visibility trigger.

**Comment by dritter** [comment]
> This issue is for multiple selectors for visibility trigger.

Ha. I missed that condition. :)

> Can you describe or share what a typical config would look like to track multiple videos?

You mean the workaround I was talking about? Sure. [Here it is](https://playground.amp.dev/#share=PCFkb2N0eXBlIGh0bWw+CjxodG1sIOKaoT4KPGhlYWQ+CjxtZXRhIGNoYXJzZXQ9InV0Zi04Ij4KICA8dGl0bGU+YW1wLWJyaWdodGNvdmU8L3RpdGxlPgogIDxzY3JpcHQgYXN5bmMgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC5qcyI+PC9zY3JpcHQ+CiAgPHNjcmlwdCBhc3luYyBjdXN0b20tZWxlbWVudD0iYW1wLWxpZ2h0Ym94IiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1saWdodGJveC0wLjEuanMiPjwvc2NyaXB0PgogIDwhLS0gIyMgU2V0dXAgLS0+CiAgPCEtLSBJbXBvcnQgdGhlIEJyaWdodGNvdmUgY29tcG9uZW50IGluIHRoZSBoZWFkZXIuIC0tPgogIDxzY3JpcHQgYXN5bmMgY3VzdG9tLWVsZW1lbnQ9ImFtcC1icmlnaHRjb3ZlIiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1icmlnaHRjb3ZlLTAuMS5qcyI+PC9zY3JpcHQ+CiAgPHNjcmlwdCBhc3luYyBjdXN0b20tZWxlbWVudD0iYW1wLWFuYWx5dGljcyIgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC9hbXAtYW5hbHl0aWNzLTAuMS5qcyI+PC9zY3JpcHQ+CiAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCxtaW5pbXVtLXNjYWxlPTEsaW5pdGlhbC1zY2FsZT0xIj4KICA8bGluayByZWw9ImNhbm9uaWNhbCIgaHJlZj0iaHR0cHM6Ly9hbXAuZGV2L2RvY3VtZW50YXRpb24vZXhhbXBsZXMvY29tcG9uZW50cy9hbXAtYnJpZ2h0Y292ZS9pbmRleC5odG1sIj4KICA8c3R5bGUgYW1wLWJvaWxlcnBsYXRlPmJvZHl7LXdlYmtpdC1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDstbW96LWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoOy1tcy1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDthbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aH1ALXdlYmtpdC1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1tb3ota2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtbXMta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtby1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QGtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX08L3N0eWxlPjxub3NjcmlwdD48c3R5bGUgYW1wLWJvaWxlcnBsYXRlPmJvZHl7LXdlYmtpdC1hbmltYXRpb246bm9uZTstbW96LWFuaW1hdGlvbjpub25lOy1tcy1hbmltYXRpb246bm9uZTthbmltYXRpb246bm9uZX08L3N0eWxlPjwvbm9zY3JpcHQ+CjwvaGVhZD4KPGJvZHk+CgogIDxwPgogICAgT3BlbiB0aGUgRGV2VG9vbHMgYW5kIGZpbHRlciBmb3IgImNvbGxlY3QiLiBZb3UnbGwgc2VlIG9ubHkgb25lIHBsYXliYWNrIGZvciB0aGUKICAgIGZpcnN0IHZpZGVvLiBCdXQgbm90IGZvciB0aGUgc2Vjb25kIG9yIHRoZSBvbmUgaW4gdGhlIGxpZ2h0Ym94LiBUaGlzIGlzIG5vdAogICAgbGltaXRlZCB0byB0aGUgYnJpZ2h0Y292ZSBwbGF5ZXIsIGJ1dCBhbGwgdmlkZW8gcGxheWVycy4KICA8L3A+CiAgPGJ1dHRvbiBvbj0idGFwOmxpZ2h0Ym94Lm9wZW47bGlnaHRib3hPcGVuOnZpZGVvLTMucGxheSI+CiAgICBPcGVuIExpZ2h0Ym94CiAgPC9idXR0b24+CiAgICA8YW1wLWJyaWdodGNvdmUgaWQ9InZpZGVvLTEiIGRhdGEtYWNjb3VudD0iOTA2MDQzMDQwMDAxIiBkYXRhLXZhcnMtdmlkZW8taWQ9InZpZGVvLTEiIGRhdGEtdmlkZW8taWQ9IjE0MDExNjk0OTAwMDEiIGRhdGEtcGxheWVyLWlkPSIxODBhNTY1OC04YmU4LTRmMzMtOGViYS1kNTYyYWI0MWI0MGMiIGxheW91dD0icmVzcG9uc2l2ZSIgd2lkdGg9IjQ4MCIgaGVpZ2h0PSIyNzAiPgogIAk8L2FtcC1icmlnaHRjb3ZlPgogICAgPGFtcC1icmlnaHRjb3ZlIGlkPSJ2aWRlby0yIiBkYXRhLWFjY291bnQ9IjkwNjA0MzA0MDAwMSIgZGF0YS12YXJzLXZpZGVvLWlkPSJ2aWRlby0yIiBkYXRhLXZpZGVvLWlkPSIxNDAxMTY5NDkwMDAxIiBkYXRhLXBsYXllci1pZD0iMTgwYTU2NTgtOGJlOC00ZjMzLThlYmEtZDU2MmFiNDFiNDBjIiBsYXlvdXQ9InJlc3BvbnNpdmUiIHdpZHRoPSI0ODAiIGhlaWdodD0iMjcwIj4KICAJPC9hbXAtYnJpZ2h0Y292ZT4KCiAgPGFtcC1saWdodGJveCBpZD0ibGlnaHRib3giIGxheW91dD0ibm9kaXNwbGF5Ij4KICAgIDxhbXAtYnJpZ2h0Y292ZSBpZD0idmlkZW8tMyIgZGF0YS1hY2NvdW50PSI5MDYwNDMwNDAwMDEiIGRhdGEtdmFycy12aWRlby1pZD0idmlkZW8tMyIgZGF0YS12aWRlby1pZD0iMTQwMTE2OTQ5MDAwMSIgZGF0YS1wbGF5ZXItaWQ9IjE4MGE1NjU4LThiZTgtNGYzMy04ZWJhLWQ1NjJhYjQxYjQwYyIgbGF5b3V0PSJyZXNwb25zaXZlIiB3aWR0aD0iNDgwIiBoZWlnaHQ9IjI3MCI+CiAgCTwvYW1wLWJyaWdodGNvdmU+CiAgICA8YnV0dG9uIG9uPSJ0YXA6bGlnaHRib3guY2xvc2UiPmNsb3NlIGxpZ2h0Ym94PC9idXR0b24+CiAgPC9hbXAtbGlnaHRib3g+CiAgPGFtcC1hbmFseXRpY3MgdHlwZT0iZ29vZ2xlYW5hbHl0aWNzIj4KICAgICAgICAgICAgPHNjcmlwdCB0eXBlPSJhcHBsaWNhdGlvbi9qc29uIj4KICAgICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICAgICAidmFycyI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgImFjY291bnQiOiAiVUEtWFhYWFhYLTEiCiAgICAgICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICAgICAidHJpZ2dlcnMiOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJ0cmFja1BsYXlWaWRlbzEiOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJvbiI6ICJ2aWRlby1wbGF5IiwKICAgICAgICAgICAgICAgICAgICAgICAgInJlcXVlc3QiOiAiZXZlbnQiLAogICAgICAgICAgICAgICAgICAgICAgICAic2VsZWN0b3IiOiAiYW1wLWJyaWdodGNvdmUjdmlkZW8tMSIsCiAgICAgICAgICAgICAgICAgICAgICAgICJ2YXJzIjogewogICAgICAgICAgICAgICAgICAgICAgICAgICAgImV2ZW50Q2F0ZWdvcnkiOiAidmlkZW8gcGxheWVyIiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICJldmVudEFjdGlvbiI6ICJzdGFydCIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAiZXZlbnRMYWJlbCI6ICIke3ZpZGVvSWR9IgogICAgICAgICAgICAgICAgICAgICAgICAJfQogICAgICAgICAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgICAgICAgICAidHJhY2tQbGF5VmlkZW8yIjogewogICAgICAgICAgICAgICAgICAgICAgICAib24iOiAidmlkZW8tcGxheSIsCiAgICAgICAgICAgICAgICAgICAgICAgICJyZXF1ZXN0IjogImV2ZW50IiwKICAgICAgICAgICAgICAgICAgICAgICAgInNlbGVjdG9yIjogImFtcC1icmlnaHRjb3ZlI3ZpZGVvLTIiLAogICAgICAgICAgICAgICAgICAgICAgICAidmFycyI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgICAgICJldmVudENhdGVnb3J5IjogInZpZGVvIHBsYXllciIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAiZXZlbnRBY3Rpb24iOiAic3RhcnQiLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgImV2ZW50TGFiZWwiOiAiJHt2aWRlb0lkfSIKICAgICAgICAgICAgICAgICAgICAgICAgCX0KICAgICAgICAgICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICAgICAgICAgInRyYWNrUGxheVZpZGVvMyI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgIm9uIjogInZpZGVvLXBsYXkiLAogICAgICAgICAgICAgICAgICAgICAgICAicmVxdWVzdCI6ICJldmVudCIsCiAgICAgICAgICAgICAgICAgICAgICAgICJzZWxlY3RvciI6ICJhbXAtYnJpZ2h0Y292ZSN2aWRlby0zIiwKICAgICAgICAgICAgICAgICAgICAgICAgInZhcnMiOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAiZXZlbnRDYXRlZ29yeSI6ICJ2aWRlbyBwbGF5ZXIiLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgImV2ZW50QWN0aW9uIjogInN0YXJ0IiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICJldmVudExhYmVsIjogIiR7dmlkZW9JZH0iCiAgICAgICAgICAgICAgICAgICAgICAgIAl9CiAgICAgICAgICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgIDwvc2NyaXB0PgogICAgICAgIDwvYW1wLWFuYWx5dGljcz4KPC9ib2R5PjwvaHRtbD4=).

In our case we sometimes have two different players on the page with 7 different Videos, tracking all different kinds of Video Events. And us being lazy just generated the config for all players, which leads to around 70kb of unnecessary config..

**Comment by micajuine-ho** [comment]
Looking at your example, it seems that each video element on your page has a unique identifier, and thus you'd want an API along the following lines:

```
triggers: {
   on: video-played,
   request: event,
   selector: ['#video-id-1', '#video-id-2', '#video-id-3'] **OR**
   selectors: ['#video-id-1', '#video-id-2', '#video-id-3'] 
}
```

An alternative and/or addition to this could be to let each selector in the array map to multiple elements instead of just one: 

```
triggers: {
   on: video-played,
   request: event,
   selector: ['.video-youtube-class, 'ima-video-class']
}
```

I would lean towards the first option; where we extend the `selector` API to allow arrays and each selector in the array would map to a single element. This ensures that videos have some sort of unique identifier (hopefully ID), that they could utilize in their request:

```
requests: {
   videoEvent: https://server-endpoint?vid=${id}
}
```

As for the implementation, it seems to be decently straightforward. Each time the observable fires, we check all the elements that are found from the array selector and then fire the analytics event for that specific element:
```
add(...) {
  const selector = config['selector'];
  const targetReadyPromise = this.root.getElements(selector);
  ...
  return this.sessionObservable_.add((event) => {
    ...
    targetReadyPromise.then((elements) => {
      const element = elements.find((e) => e === event.target);
      listener(element,...);
    }
  });
}
```

Publishers would have to change their config (since array selector is currently invalid for `selector`),  but that also means that we don't have to worry about breaking existing functionality. Additionally, this closely mirrors the visibility-trigger improvements we made earlier in the year. 

/cc @zhouyx Thoughts?

**Comment by dritter** [comment]
I may misread [the code](https://github.com/ampproject/amphtml/blob/68dfea1c94bffeaa9d68d7391cd5240c4617e6b7/extensions/amp-analytics/0.1/analytics-root.js#L357-L361), but IMHO `this.root.getElements` is not ready in its current form. It returns an array of a single element (probably the first found; exception is if feature flag `visibility-trigger-improvements` is set). That is [why I went with `this.root.getElementsByQuerySelectorAll_` instead](https://github.com/ampproject/amphtml/compare/master...dritter:fix-video-analytics--multiple-selectors#diff-207df6f01ba92a0c9c65da02c4de913c26b7972c08480374ab075d8038165152R1283) (knowing that `getElements` should be the right interface).

> [...] This ensures that videos have some sort of unique identifier [...]

Is that mandatory?

Regarding the selector style:
I tend towards the comma separated list of selectors. For me it was long time not clear that this is _not_ a CSS Selector, but a custom subset. Hence I think the selector should move back in that direction. Other events (like `click` AFAIK work already this way).

**Comment by zhouyx** [comment]
This makes sense to me. Can we expand the multi selector support so it works just like the visibility selector.

**Comment by micajuine-ho** [comment]
@dritter 
> That is [why I went with `this.root.getElementsByQuerySelectorAll_` instead](https://github.com/ampproject/amphtml/compare/master...dritter:fix-video-analytics--multiple-selectors#diff-207df6f01ba92a0c9c65da02c4de913c26b7972c08480374ab075d8038165152R1283) (knowing that `getElements` should be the right interface).

Yes this is correct, however, we should use `getElements` and then guard this new feature under a different experiment flag as part of our rollout plan. 

> Is that mandatory?

I would say that the video elements have some sort of unique identifier, weather it be an ID or a `data-vars-*` attribute (like we require with the multi-selector visibility trigger), so that each request made can be unique (so that you can determine which video the analytics event was triggered on server-side).   

@zhouyx Yes, I think this is the way to go, for feature parity in addition to all the benefits we stated when we made the initial decision for the multi-selector visibility trigger (backwards compat, clear code paths, easy rollout with experiment flag, etc...).

To clarify, the design will be to expand the `selector` API for video trigger to allow an array of selectors. Each selector can map to multiple video elements. Elements must have `data-vars-*` attribute (for reasons stated above and performance reasons).  

```
triggers: {
   on: video-played,
   request: event,
   selector: ['.video-youtube-class, '#video-id-1']
}
```

This will not apply to special selectors (:root, etc).

The changes will be guarded under an experiment flag.

**Comment by zhouyx** [comment]
I'm not sure about the `data-vars-*` attribute requirement. Because each video already has an id.

**Comment by micajuine-ho** [comment]
Assigned to @kalemuw

**Comment by micajuine-ho** [comment]
Closed in https://github.com/ampproject/amphtml/pull/34841
