### ISSUE TITLE
`amp-user-notification` visual diff test is flaky

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#30868]
I've seen this test flake more often than usual in the past few days. From the [snapshot](https://percy.io/ampproject/amphtml/builds/7428747/view/423992155/400?mode=diff&browser=firefox&snapshot=423992155), it seems to be due to a non-static ad loading animation.

Any way to freeze that element before diffing?

**Comment by rsimha** [comment]
Assigning to @zhouyx for triage.

/cc @danielrozenberg in case my hunch is wrong, and this needs an infra level fix.

**Comment by danielrozenberg** [comment]
How are loaders animated? If they use CSS or built-in JS animations, Percy should be disabling the animation, in which case this is a Percy-side issue that we should report. If we do it in some custom way, maybe it should be disabled when AMP_CONFIG is set to test mode

**Comment by zhouyx** [comment]
@alanorozco to comment on how the loader is built. 

I like disabling the loader in test for good. If not maybe I can replace the test with a static placeholder.
