### ISSUE TITLE
I2I: Expand LocalStorage Usage when Storage API is not used

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#30872]
## Summary

Today AMP restricts localStorage usage to limited [cases](https://github.com/ampproject/amphtml/blob/master/spec/amp-localstorage.md#current-usage). The reason is that such stored value needs to be passed to AMP Viewer to be stored. 

The proposal is to expand the localStorage usage to all AMP components when the Storage is not applied. 

## Design document

Expand the existing `storageForDoc()` service to provide a local version, where value will be stored to the document's domain. 

The exception is that: When the doc is served in an iframe => LocalStorage will behave like sessionStorage
AMP expects developers to understand the tradeoff here

## Motivation

While AMP can't expand the Storage API usage for privacy and technical challenge. Developers should be given access to the LocalStorage to improve performance. 

## Additional context

Such exception has been applied to `<amp-consent>` already to stored consent string. 

Other requests
https://github.com/ampproject/amphtml/issues/30193#issuecomment-707184359

/cc @ampproject/wg-approvers

**Comment by dvoytenko** [comment]
I don't see a reason why we shouldn't allow extensions to use `localStorage` for more use cases. However, I'd not use `storageForDoc` service for that and instead allow direct access to the `localStorage` and `sessionStorage`.
