### ISSUE TITLE
<amp-base-carousel>: buggy when advance-count = 1 and visible-count > 1

### ISSUE THREAD

**Issue by dero** [ampproject/amphtml#30905]
## What's the issue?

See this pen in a desktop browser: https://codepen.io/iamdero/pen/bGeLPqy

1. Click the next button and observe the carousel animation to advance by one slide to slide nr. 2 (correct)
2. ... but then immediately advance again with no animation to slide nr. 3 (incorrect).
3. Click the next button, the carousel will not advance (incorrect).
4. Click the next button yet again, it will advance by two slides (incorrect).
5. Click the back button, carousel will go back by two slides (incorrect)
6. ... and then immediately swap the slides so that the final result is as if it only went back by one slide (correct).

## What browsers are affected?

Desktop browsers, tested in latest Chrome and Firefox.

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 2010132225002

**Comment by micajuine-ho** [comment]
Hi @dero, I am testing this locally but I am unable to reproduce this error. Are you able to reproduce this outside of codepen.io environment?

**Comment by dero** [comment]
Hi @micajuine-ho – thanks for the quick reply!

Yes, I've encountered the issue on a project I'm working on and the issue is still there. The project is not live yet and is not shareable ATM, but the issue is identical to what the pen shows.

I've also taken the code and ran it on a local webserver and the issue is still there.

> I am unable to reproduce this error.

Are you able to verify and reproduce the issue on codepen?

Any chance you're using newer / dev version of `amp-base-carousel` where this issue might already be fixed? The currently live version – https://cdn.ampproject.org/v0/amp-base-carousel-0.1.js – seems to be still suffering from this issue.
