### ISSUE TITLE
🌸 Cherry-pick request for #30651 into #30741 (Approved)

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#30909]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #30651 | #30652 |     **NO**     | **YES** | **NO** | #30741                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

The story loading experience looks very broken when the first page has a video.

## Why is a Beta / Experimental cherry-pick not needed?

The fix is already in beta/experimental.

## List the steps to manually verify the changes in this cherry-pick

It's hard to repro consistently in the wild as you never know how fast the poster or video will load. Here are some steps:

1. Clear your cache or go in private navigation. You will need to clear the cache or open a new private navigation window every single time, otherwise the video will be loaded from the browser cache and you won't see the poster image
2. Open https://www.gstatic.com/amphtml/stamp/qa/video.htm
3. BAD: Before the video loads you might see the poster image completely stretched out, looking very visually broken
4. EXPECTED: Before the video loads you might see the poster image correctly positioned and not stretched out

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by gmajoulet** [comment]
FYI @ampproject/wg-stories

**Comment by cramforce** [comment]
This is a pretty big change for a cherry-pick, but it has gotten significant beta-testing already (Would have been released this week if it wasn't for the freeze).

Given the severity of the bug, I think this is worth doing.

But I'd like to get an independent review from @dvoytenko or @kristoferbaxter

**Comment by dvoytenko** [comment]
Why is Beta CP not needed?

**Comment by cramforce** [comment]
Because it is in Beta already.

**Comment by dvoytenko** [comment]
Approved

**Comment by rsimha** [comment]
@gmajoulet can you please fill in the manual verification steps? I'd like to make sure @Ichigo3d has a chance to test this out before a potential cherry-pick.

**Comment by gmajoulet** [comment]
It's hard to repro consistently in the wild as you never know how fast the poster or video will load. Here are some steps:

1. Clear your cache or go in private navigation. You will need to clear the cache or open a new private navigation window every single time, otherwise the video will be loaded from the browser cache and you won't see the poster image
2. Open https://www.gstatic.com/amphtml/stamp/qa/video.htm
3. BAD: Before the video loads you might see the poster image completely stretched out, looking very visually broken
3. EXPECTED: Before the video loads you might see the poster image correctly positioned and not stretched out

**Comment by cramforce** [comment]
Approved

**Comment by jridgewell** [comment]
Why isn't LTS affected?

**Comment by kristoferbaxter** [comment]
I did a review of the change, and it looks good to me.

In the future, we should enhance test coverage for this so we do not regress.

**Comment by rsimha** [comment]
_[Cleaning up old CP issues]_ Can this be closed?
