### ISSUE TITLE
I2I: Dock audio players

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#30916]
## Summary

This allows [docking (pinning to a corner on scroll)](https://go.amp.dev/c/amp-video-docking) audio player components rather than just video. 

### Player components

1. The `VideoInterface` should be supported by these audio players like a video player would. The name for the interface is inappropriate, but the contract for effective operations (play/pause, mute/unmute, etc.) is the same.

2. When rendering an iframe, it should be annotated with an attribute so that the `-docking.js` extension handles it like audio: `<iframe data-is-audio>`

**Non-goal:** The `VideoInterface`/`VideoManager` can be split into parts later.

### amp-video-docking

The general `VideoManager` doesn't need to be changed, since video-only features (`autoplay`, `rotate-to-fullscreen`) are not relevant nor exposed as valid attributes on audio players.

[Docking](https://go.amp.dev/c/amp-video-docking) is changed to support `<audio>` (for `amp-audio`) and `<iframe data-is-audio>` (for any 3p player). When docking one of these element types, the extension handles them slightly differently:

1. The docking extension does *not* draw its own playback controls when docked. Instead, it should delegate to  the `audio` element's native controls, or those drawn inside the `iframe`. 

2. The element-to-viewport width limit is either a) ignored or b) based on area % instead of width. An _audio player box_ is assumed to have a rather wide aspect ratio (like 5:1 or wider), instead of more square-ish dimensions (like standard widescreen video, 16:9), which would allow us to maintain the player in its initial scale when docked, or shrink it by a small amount only e.g. `transform: scale(0.95)`. This way, the controls drawn by the player extension remain in usable dimensions.

We could possibly alias `amp-video-docking.js` as `amp-docking.js`, but that's only a cosmetic/communication change. The shipped code would remain the same.

/cc @ampproject/wg-approvers

**Comment by dvoytenko** [comment]
This sounds very interesting and appropriate. It sounds like we may want a MediaInterface/MediaManager to correspond to the `HTMLMediaElement` interface (it also supports `autoplay`, btw). But I think we can continue to track for video docking and figure out how to reactor it to general MediaInterface once we figure the interfaces there?
