### ISSUE TITLE
"load more" option on amp-instagram component

### ISSUE THREAD

**Issue by joshcp** [ampproject/amphtml#30924]
## Describe the new feature or change to an existing feature you'd like to see

It would be nice to have a "Load More" config option available in the amp-instagram component

## Describe alternatives you've considered

Possibly incorporate amp-list and amp-bind to create a load more link?

**Comment by zhouyx** [comment]
amp-instagram loads the instagram iframe. Is the load more link a link to expand the iframe instead?
