### ISSUE TITLE
🚨 Error: [amp-instagram] This endpoint is deprecated.

### ISSUE THREAD

**Issue by arunvc** [ampproject/amphtml#30938]
Amp instagram  throws error in browser console, any alternative solution

```
<amp-instagram
                data-shortcode="CG_v_NFpreN"          
                width="400"
                height="400"
                layout="responsive"
                >
```
![image](https://user-images.githubusercontent.com/9069988/97777271-0f8e6780-1b95-11eb-842c-5eeed7a65a5f.png)

On click of url https://www.instagram.com/p/CG_v_NFpreN/media/?size=l
```
This endpoint is deprecated. Please read https://developers.facebook.com/docs/instagram/oembed to learn how to migrate your endpoint.
```

Stack trace
```
	f/f.createPlaceholderCallback/<
amp-instagram.js:121:8
(Async: promise callback) f/f.createPlaceholderCallback
amp-instagram.js:118:4
zi/b.prototype.createPlaceholder
custom-element.js:1007:13
zi/b.prototype.build/this.cc<
custom-element.js:517:32
(Async: promise callback) zi/b.prototype.build
custom-element.js:477:38
f.build
resource.js:342:11
Gj
resources-impl.js:581:20
Ej
resources-impl.js:516:6
f.upgraded
resources-impl.js:633:4
zi/b.prototype.xd
custom-element.js:386:6
zi/b.prototype.jg
custom-element.js:890:8
zi/b.prototype.upgrade
custom-element.js:357:8
Ci
custom-element-registry.js:89:4
am
custom-element-registry.js:73:6
$l/<
extensions-impl.js:352:40
Se
style-installer.js:71:9
$l
extensions-impl.js:348:6
f.addElement/<
extensions-impl.js:334:27
f.addDocFactory
extensions-impl.js:419:8
f.addElement
extensions-impl.js:333:4
f/<
amp-instagram.js:250:2
f
amp-instagram.js:249
f.registerExtension
extensions-impl.js:154:6
b/<
runtime.js:189:10
(Async: promise callback) b
runtime.js:185:6
qi
chunk.js:200:6
mi.prototype.jf
chunk.js:419:6
ti/<
chunk.js:474:6
(Async: promise callback) ti
chunk.js:473:4
mi.prototype.va
chunk.js:492:6
mi.prototype.jf/<
chunk.js:445:10
(Async: promise callback) mi.prototype.jf
chunk.js:425:6
mi/<
chunk.js:332:8
(Async: EventListener.handleEvent) mi
chunk.js:330:4
qc
service.js:362:12
wc
service.js:213:9
li
chunk.js:47:9
ni
chunk.js:68:37
<anonymous>
amp.js:141:15
<anonymous>
amp.js:116:28

```

/cc @ampproject/release-on-duty

**Comment by ro-hitr** [comment]
I encountered the exact same issue but still am looking for a fix. Apparently Facebook made some changes to Instagram's API which replaces the legacy 'oEmbed' with their new version. A GET request is now required to fetch the image/vid which includes a unique access token (probably to track/security reasons).
More on this on their official website: [https://developers.facebook.com/docs/instagram/oembed](https://developers.facebook.com/docs/instagram/oembed)

**Comment by asphub** [comment]
You can see the same error in browser console while accessing the example

[https://amp.dev/documentation/examples/components/amp-instagram/?format=websites](https://amp.dev/documentation/examples/components/amp-instagram/?format=websites)

**Comment by kristoferbaxter** [comment]
Filed an intent to remove for the `0.1` component, it's going to design review today and the PR is out for the implementation.

https://github.com/ampproject/amphtml/issues/32322
