### ISSUE TITLE
Bento: custom-element/Preact binding

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#30952]
The binding rules are documented [here](https://docs.google.com/document/d/1mOjmA56HNZGfTtLH51kFpZXSadpk0YYoEikxe6TJA_0/edit?pli=1#heading=h.mhuayjp9i9sl).

TODO:

- [x] Standard wrappers for size-defined vs content elements
- [x] Light DOM and Shadow DOM rules
- [x] Detached DOM model
- [x] Install shadow stylesheets
- [x] Simple attribute types
- [x] Boolean attribute types
- [x] Attribute prefix -> map mapping
- [x] Media attributes
- [x] Template support
- [x] Preact context propagation via DOM tree.
- [x] Custom element lifecycle support: build/connect/disconnect/load/unload.
- [x] Refactor passthrough and children options to allow both.
- [x] Shadow DOM polyfill

See also renderable/playable/loadable API in https://github.com/ampproject/amphtml/issues/30283.

**Comment by samouri** [comment]
all todo items are done! is this closable?

**Comment by dvoytenko** [comment]
I'll keep it as a palceholder for a bit longer. The binding questions popup and it's easier to track them from the same bug #

**Comment by samouri** [comment]
Do we need to handle `adoptedCallback`?

**Comment by dvoytenko** [comment]
So far we didn't need to, no. But definitely a possibility at some point.
