### ISSUE TITLE
iOS 14.1: Offscreen images are not loaded correctly after scrolling to viewport

### ISSUE THREAD

**Issue by nainar** [ampproject/amphtml#30957]
Search "Bed Bath and Beyond" on Google Search, and click the first AMP page that leads to the homepage.

This opens up the AMP viewer. Scroll down to the "Make your office work for you" section, which contains a few horizontal cards.

Scroll right to show the third card. You'll see the third card remain blank like below:

The same issue happens on Chrome and Safari on iOS 14.1 (Tested on an iPhone 6s and iPhone 11)
Chrome:

Safari: 

I checked the network tab in the developer tools, that it never requests for the third image. Is this a known bug, or any similar issue?

Also confirming I'm seeing this issue only on cache and not on origin.

**Comment by nainar** [comment]
This seems to be a regression on iOS in 14.1. 

@Ichigo3d to confirm

**Comment by jonchenn** [comment]
Thanks for filing this issue @nainar. I'm attaching the screenshot for the issue of offscreen image:

- The `<amp-img>` is missing the `<img>` tag, hence the blank image in the 3rd card in the carousel-like horizontal section.

![image (5)](https://user-images.githubusercontent.com/1644724/97922597-bbb58700-1d2a-11eb-88c5-ff53e41e2d38.png)

- Screenshot
![AMP iOS 14 issue](https://user-images.githubusercontent.com/1644724/97922513-99bc0480-1d2a-11eb-9b71-4f01f87614e3.png)
