### ISSUE TITLE
absolute lengths should be allowed in sizes `lengths`

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#3095]
https://www.w3.org/TR/css3-values/#absolute-lengths should be allowed, currently banned through https://github.com/ampproject/amphtml/blob/master/src/layout.js#L172

**Comment by ericlindley-g** [comment]
Slotting in backlog, but feel free to let me know or update directly if there's a more specific target for a fix (or if the bug is severe enough to prioritize in the short term)

**Comment by dvoytenko** [comment]
moving to this milestone to fix asap.
