### ISSUE TITLE
Modify various extensions to support the use of native `img` as a descendent 

### ISSUE THREAD

**Issue by rebeccanthomas** [ampproject/amphtml#30958]
## Describe the new feature or change to an existing feature you'd like to see
This change is part of the umbrella of changes which make up the `amp-img` deprecation: #30442
This change will also follow the implementation of: #30956 which will allow the use of native `img` tags in valid AMP documents. 

The following components will require changes to support native `img` as children. 
- Amp-auto-lightbox.js
- Amp-image-lightbox.js
- Amp-image-slider.js
- Amp-image-slider-validator.js
- Amp-image-viewer.js
- Amp-lightbox-gallery.js
- Lightbox-manager-impl.js

Additionally,  `amp-consent` will require changes to allow images to be blocked on consent, `amp-analytics` will need to be updated to track changes to native `img` tags and  the `amp-bind` validator will need to be updated in order to be used with native `img`. 

Additionally, a change to the validator, which currently disallows native `img` as a child of any `amp-*` component except `amp-img` will need to be made to permit these changes. 

## Additional context

For additional documents see this document about [`amp-img` deprecation](https://docs.google.com/document/d/1tLqmz3g0a8PCOWwsQuPZ3Sx0MuqL8ly78I7eA-xOj-Q/edit?usp=sharing), and this document about [allowing native  #`img`](https://docs.google.com/document/d/135fsDOw-OfVNZbqr-aOY3ZVNKTzwCLcf8z6Dang2ygY/edit?usp=sharing) in valid amp documents.

**Comment by Gregable** [comment]
My understanding from #30442 is that this work has been completed.
