### ISSUE TITLE
AMP story player: cannot programmatically control the player

### ISSUE THREAD

**Issue by rnkimani** [ampproject/amphtml#30967]
## What's the issue?
- With the latest player versions(v0 and v1), every time I try to programmatically control the player, the stories don't show.
- It could also be handy if the docs are updated on how to use it with the recent versions. 

## How do we reproduce the issue?
- Try using the new API as documented [here](https://github.com/ampproject/amphtml/issues/28416)

## What browsers are affected?
- All

## Which AMP version is affected?
- Latest

cc @Enriqe

**Comment by rnkimani** [comment]
Reproduced [here](https://svelte.dev/repl/22524365295644adbf4f154436af1724?version=3.29.4)

**Comment by Enriqe** [comment]
I think you forgot to import the player CSS in your `<head>`. 

```
	<link href="https://cdn.ampproject.org/amp-story-player-v0.css" rel="stylesheet" type="text/css">
```

more info:
https://github.com/ampproject/amphtml/blob/master/spec/amp-story-player.md#-amp-story-player

We will be sending new updates and documentation for the player today. Will link it here as well.
