### ISSUE TITLE
getComputedStyle returns null on firefox inside iframe with display:none

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#3096]
`f is null` error in this code: https://gist.github.com/erwinmombay/889e83a7cdc65605c51b2a0c262a8ac0#file-f-js-L15

caused by firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=548397

seems to have been introduced in 1460655576651

**Comment by ericlindley-g** [comment]
Slotting in backlog, but feel free to let me know or update directly if there's a more specific target for a fix (or if the bug is severe enough to prioritize in the short term)

**Comment by dvoytenko** [comment]
Moving to current milestone for asap fix.
