### ISSUE TITLE
Failed to integrate amp-analytics with Firebase Analytics

### ISSUE THREAD

**Issue by gerardorn** [ampproject/amphtml#31009]
## What's the issue?

When integrating AMP with Firebase Analytics no information is registered

## How do we reproduce the issue?

1. Create a firebase project with a new Analytics Account in the Firebase Console
2. Register a web application with Firebase Hosting enabled
3. Initialize a local Firebase Project with the Firebase CLI with Hosting integration
4. Create a simple AMP page using the amp-analytics element inside the public directory
5. Configure the amp-analytics tag to reference the Firebase Analytics measurementId
6. Serve localy the firebase project with firebase serve
7. Visit the localhost url to the AMP page
8. Review there's no information registered in Firebase Analytics

According to the Firebase Analytics documentation, the firebase SDK and the Firebase Analytics library must be referenced via <script> elements in the code:
```JavaScript
<!-- The core Firebase JS SDK is always required and must be listed first -->
<script src="https://www.gstatic.com/firebasejs/8.0.0/firebase-app.js"></script>

<!-- TODO: Add SDKs for Firebase products that you want to use
     https://firebase.google.com/docs/web/setup#available-libraries -->
<script src="https://www.gstatic.com/firebasejs/8.0.0/firebase-analytics.js"></script>
```
 before calling:

```JavaScript
firebase.initializeApp(firebaseConfig);
firebase.analytics()
```
Doing this invalidates the AMP page.

Maybe Firebase should be a provider for amp-analytics. Passing the required information about the project, the amp-analytics tag could initialize the application and the analytics product so the events are registered successfully

### Tips on Rendering Bugs

Not required (?)

## What browsers are affected?
Used Chrome while developing but it's not related to the browser

## Which AMP version is affected?
The console prints: Powered by AMP ⚡ HTML – Version 2010132225003

**Comment by micajuine-ho** [comment]
Hi @gerardorn , thank you for your issue.

Firebase currently does not have an integration with `amp-analytics`. For a list of vendors that do integrate with `amp-analytics`, please see [here](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/configure-analytics/analytics-vendors/).

**Comment by gerardorn** [comment]
Hey @micajuine-ho 
Thanks for the reply

It would be nice to have or maybe an example of how to integrate them if thats possible

**Comment by gerardorn** [comment]
I've found an issue that might be related
https://github.com/ampproject/amphtml/issues/30903#issue-731978373

Thanks @micajuine-ho
