### ISSUE TITLE
Webp image with fallback/child and "auto-advance-after" causes incorrect work in AMP Story

### ISSUE THREAD

**Issue by Vint7r** [ampproject/amphtml#31000]
## What's the issue?

When I use _.webp_ image with _fallback/child_ image (for not supported browsers) with "_auto-advance-after"_ my AMP Story breaks: lagged scrolling, no auto-sliding.
[Example](https://examples.webstoryz.com/test_story/story2.html)

I tried all documented methods to use _.webp_ and _fallback/child_ image, but nothins works with _"auto-advance-after"_

When I delete _"auto-advance-after"_ it works fine.

## How do we reproduce the issue?
**[Example](https://examples.webstoryz.com/test_story/story2.html)**

1. Use _.webp_ with _fallback/child_ image
2. Add _auto-advance-after="15s"_

## What browsers are affected?

**All**

## Which AMP version is affected?

It's a new issue, AMP version is **2010132225003**

**Comment by yarbogach77** [comment]
Guys, fix it please..
web Story do not working
