### ISSUE TITLE
🌸 Cherry-pick request for #30937 into #30974 (Approved)

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#31004]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #30937 | #30937 |     **YES**     | **NO** | **NO** | #30974                                                            |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

Ever since `intersect-resources` experiment went live there have been layouting issues in Dynamic Mail with varying levels of severity. The affected surfaces are Safari, Android and iOS since they all use a similar iframe embedding method.

With various levels of reproducibility, this can cause:
- amp-img with margin not to layout: `b/170491750`
- amp-list never to have its `layoutCallback()` fire: `b/170538870`, `b/169596105`
- potentially more unreported issues.

By CPing this to Beta, we can verify the fix sooner as well as if successful then they can fix prod sooner. If the fix is unsuccessful that means we can get a head start on investigation.

## List the steps to manually verify the changes in this cherry-pick

DM me for instructions.
We unfortunately don't have an open source reproducible test case (yet).

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

AMP viewport size changes that occur in between the time of an InOb "premeasure" and the time that the measure is applied in a resources pass leads to invalid measurements being used all without the Runtime realizing that the elements need to be remeasured. Incorrect measurement is a problem if that measurement is "0", since we rely on nonzero size to enable layout.

## Impact

- <_Which users were affected? Roughly how many?_>
- <_How were users affected? E.g. partial or complete loss of functionality?_>

## Action Items

- new unit test merged
- TODO: think of more ways to ensure it doesn't happen again.
  - integ test? doesn't seem easy to write. because the resizes need to happen precisely in the race condition window.
  - create a viewer that more closely mimics Dynamic Mail viewer behavior?

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by jridgewell** [comment]
Approved.

**Comment by samouri** [comment]
@alanorozco: I think you are the current release eng.
Please let me know when you're able to CP this into Beta!

**Comment by alanorozco** [comment]
@samouri  2010302236001 has been available as opt-in as of yesterday, 2:41:42 PM GMT-8.
