### ISSUE TITLE
xhr native and polyfill flake

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#3101]
```
Chromium 45.0.2454 (Ubuntu 0.0.0) XHR Native should do simple JSON fetch FAILED
	Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
Chromium 45.0.2454 (Ubuntu 0.0.0): Executed 1377 of 1991 (1 FAILED) (0 secs / 13.411 secs)
```

```
Chromium 45.0.2454 (Ubuntu 0.0.0) XHR Polyfill should do simple JSON fetch FAILED
	Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
Chromium 45.0.2454 (Ubuntu 0.0.0): Executed 1400 of 1991 (2 FAILED) (0 secs / 18.802 secs)
```

https://travis-ci.org/ampproject/amphtml/builds/127920478

**Comment by cramforce** [comment]
We filed this before. The fix is to get rid of that non-hermetic external dep and replace it with a local server.

**Comment by mkhatib** [comment]
By local server are you suggesting we actually run a node server for these tests or just rely on sinon fake server?

I took a quick look yesterday at this and found few things:

* Sinon Fake Server [doesn't mock fetch API requests](https://github.com/sinonjs/sinon/issues/727)
* The flakey tests seem more than unit tests, we need to mock all these calls.
* Mocking [window.fetch is possible](https://rjzaworski.com/2015/06/testing-api-requests-from-window-fetch) though not sure how straight forward mocking redirects and CORS will be.

I can experiment with mocking these calls, unless your idea is to actually run a local server and write responses for the tests. Let me know.

**Comment by mkhatib** [comment]
Ok, so most tests should be mockable. The ones that @dvoytenko tests CORS stuff pointed to seems to be really testing a browser functionality rather than our implementation.

I suggest we drop these tests in favor for something that focus on testing the implementation, for example, instead of doing this:
```javascript
      it('should succeed CORS setting cookies with credentials', () => {
        const cookieName = 'TEST_CORS_' + Math.round(Math.random() * 10000);
        const url = 'https://httpbin.org/cookies/set?' + cookieName + '=v1';
        return xhr.fetchJson(url, {credentials: 'include'}).then(res => {
          expect(res).to.exist;
          expect(res['cookies'][cookieName]).to.equal('v1');
        });
      });
```

We do something like this:
```javascript
      beforeEach(setupMockXhr); // we can also mock fetch API ourselves.
      it('should succeed CORS setting cookies with credentials', () => {
        const promise = xhr.fetchJson(url, {credentials: 'include'}).then(res => {
          expect(xhr.open.calledWith('GET', url, true)).to.be.true;
        });
        requests[0].respond(200);
        return promise;
      });
```

The other approach is what Malte and Dima suggested on the other bug which running a local server - I am experimenting with this now and trying to figure out best way to do this.

**Comment by dvoytenko** [comment]
The explicit goal here is to make sure that whatever invocations we do with XHR is equivalent and correct binding to the newer `fetch` protocol where we have to polyfill it. The initial goal was also to understand the fetch/CORS better. So, at this time, we can certainly switch to basic unit testing, imho. The only real goal is to ensure that XHR is correctly configured for any type of request. These tests did help us to catch the issue with preflight before. But in all honestly, this happened not because we implemented something wrong, but because the remote service didn't fully implement preflight :)

**Comment by cramforce** [comment]
@mkhatib Welcome back from vacation. Fixing this would be super valuable. Otherwise even our SC tests look good now :)

**Comment by mkhatib** [comment]
@cramforce not even back yet 😄 . I did mostly experimentation in this, if anyone want to take this over  or I can take a look when I get back.

**Comment by cramforce** [comment]
Get back to your vacation! I meant for you to read this after!

**Comment by mrsufgi** [comment]
Hey, I've been working on some tests for our components, we use a xhrFor on layoutCallback for fetching some data from our servers. For some reason every 2-3 refreshes I'm getting the same timeout notice, should I ignore those till this get reworked?

**Comment by jridgewell** [comment]
If you're getting those errors while running the tests, than this is (unfortunately) expected flake. If you're getting timeout warnings while running the code locally (as in, not using the `npm test` or `gulp test`), than this is likely an issue with your server not responding quickly enough.
