### ISSUE TITLE
[Story Content layout] I2I: Remove viewport warning

### ISSUE THREAD

**Issue by mszylkowski** [ampproject/amphtml#31034]
## Summary

We want to remove the warning that prevents stories from being shown in all devices and experiences, and improve the experience in unconventional devices by removing the warning "Expand width/height of the window to view the story".

![image](https://user-images.githubusercontent.com/22420856/98404240-38e94080-2038-11eb-814b-264174b57631.png)

## Design document

When removing the warning, there will still be 2 UI types allowed on browsers, but they might change to some extent:
- Desktop panels: Used to trigger when viewports were not 1024x516px in size. Now they trigger if the aspect-ratio is more than 1, meaning width ≥ height, which is independent of the screen size. We will make the system layer scale-responsive to make this layout work on smaller screens / split screens.
- Mobile: Used to trigger when viewports were smaller than the dimensions for desktop panels. Now it triggers when the aspect-ratio is less than 1, meaning height > width. In order to accommodate stories in more square-ish screens, it optionally adds letterboxing to the sides by setting the max-width of the page to 67vh (2:3 ratio). This layout can show side arrows if they have space, but clicking on the margins should navigate as expected.

**Comment by processprocess** [comment]
Viewport warnings have been removed as part of #35267
