### ISSUE TITLE
Amp-list gets rendered twice sometimes in the browser from google cache

### ISSUE THREAD

**Issue by cw-ashish-sharma** [ampproject/amphtml#31049]
At times our amp-list is getting rendered twice.
I noticed when tracking were fired twice for a unique element
url: https://www.google.com/amp/s/www.carwale.com/amp/used/cars-in-navi-mumbai/

example: 
![image](https://user-images.githubusercontent.com/49865803/98574201-a5d13480-22dd-11eb-979c-7e04bf7fd4ae.png)
as you can see the element is present 4 times but is should be present only 2 times
1 for the the html element and 1 for tracking

but it gets repeated.

here it is rendered only twice
![image](https://user-images.githubusercontent.com/49865803/98574754-54757500-22de-11eb-8ab1-f96a8e9e51b1.png)
though the urls are different we render the same page with different data

**Comment by cw-ashish-sharma** [comment]
@choumx  can you please help me

**Comment by cw-ashish-sharma** [comment]
@dvoytenko can you please help me out

**Comment by samouri** [comment]
@cw-ashish-sharma: are you able to provide a small reproduction of the bug? That would greatly help us get to the root of the issue. A good tool for doing that is http://glitch.me/. Thanks!

**Comment by cw-ashish-sharma** [comment]
@samouri I will get you the snippet but may I know how will it help to fix the caching in google Because locally even I see the list rendered only once.

**Comment by cw-ashish-sharma** [comment]
@samouri  any updates?

**Comment by cw-ashish-sharma** [comment]
@dvoytenko @samouri  any updates?

**Comment by samouri** [comment]
@cw-ashish-sharma: This error can also be detected on origin when you include all of the query parameters that end up in the URL.

See: https://www.carwale.com/amp/used/cars-in-navi-mumbai/?usqp=mq331AQFKAGwASA%3D&amp_js_v=0.1#aoh=16055865866799&origin=https://www.google.com&cid=1&prerenderSize=1&visibilityState=visible&paddingTop=32&history=1&p2r=0&csi=1&storage=1&viewerUrl=https://www.google.com/amp/s/www.carwale.com/amp/used/cars-in-navi-mumbai/&cap=navigateTo,fragment,handshakepoll,cid,replaceUrl,fullReplaceHistory

On that page there are duplicates within the HTML, well before AMP code takes any action.

**Comment by cw-ashish-sharma** [comment]
@samouri  will it be possible for you to tell me how did you come to know about this? as we use the same page for other cities and  I didnt get duplicate code over there?
for example the second image which I had attached has url: https://www.google.com/amp/s/www.carwale.com/amp/used/cars-in-mumbai/
here I could see the html only once?

**Comment by samouri** [comment]
The page you [linked](https://www.google.com/amp/s/www.carwale.com/amp/used/cars-in-mumbai/) has an `iframe` within it. The iframe `src` points to the amp cache at: https://www-carwale-com.cdn.ampproject.org/v/s/www.carwale.com/amp/used/cars-in-mumbai/?usqp=mq331AQFKAGwASA%3D&amp_js_v=0.1#aoh=16055905343439&origin=https://www.google.com&cid=1&prerenderSize=1&visibilityState=visible&paddingTop=32&history=1&p2r=0&csi=1&storage=1&viewerUrl=https://www.google.com/amp/s/www.carwale.com/amp/used/cars-in-mumbai/&cap=navigateTo,fragment,handshakepoll,cid,replaceUrl,fullReplaceHistory

That URL is equivalent to: www.carwale.com/amp/used/cars-in-mumbai/?usqp=mq331AQFKAGwASA%3D&amp_js_v=0.1#aoh=16055905343439&origin=https://www.google.com&cid=1&prerenderSize=1&visibilityState=visible&paddingTop=32&history=1&p2r=0&csi=1&storage=1&viewerUrl=https://www.google.com/amp/s/www.carwale.com/amp/used/cars-in-mumbai/&cap=navigateTo,fragment,handshakepoll,cid,replaceUrl,fullReplaceHistory

See image below:
<img width="739" alt="Screen Shot 2020-11-17 at 12 22 57 AM" src="https://user-images.githubusercontent.com/4656974/99349904-1393d800-286b-11eb-9eb1-017bf906a9ac.png">

**Comment by samouri** [comment]
cc @honeybadgerdontcare, since I'm not confident about the actual URL query params used when crawling sites for an AMP Cache.

Either way, the [URL](http://www.carwale.com/amp/used/cars-in-mumbai/?usqp=mq331AQFKAGwASA%3D&amp_js_v=0.1#aoh=16055905343439&origin=https://www.google.com&cid=1&prerenderSize=1&visibilityState=visible&paddingTop=32&history=1&p2r=0&csi=1&storage=1&viewerUrl=https://www.google.com/amp/s/www.carwale.com/amp/used/cars-in-mumbai/&cap=navigateTo,fragment,handshakepoll,cid,replaceUrl,fullReplaceHistory) I posted earlier does show that the origin `carwale.com` is serving HTML with duplicate content, so I think you'll need to debug there.
