### ISSUE TITLE
amp-analytics (gtag) incompatibility with Google Analytics 4

### ISSUE THREAD

**Issue by zarzosa** [ampproject/amphtml#31045]
## What's the issue?

Google recently released GA4, and it does not have AMP support.
https://support.google.com/analytics/answer/9964640?hl=en

When inserting an ID that contains the format G-XXXXXXXXXX, the following error is obtained in the console:
[AmpAnalytics <unknown id>] No triggers were found in the config. No analytics data will be sent.

## How do we reproduce the issue?

I have left the error running on my site so it can be analyzed: https://topic.com.ar/ (see console)

The code involved is the following:

```
<amp-analytics type="gtag" data-credentials="include">
  <script type="application/json">
  {
    "vars" : {
      "gtag_id": "G-RC3CEG0HLQ",
      "config" : {
        "G-RC3CEG0HLQ": {}
      }
    },
```

The measurement works normally when using Universal Analytics (UA-XXXXXXXXXX).

## What browsers are affected?

All browsers.

## Which AMP version is affected?

New issue (amp-analytics works fine, but GA4 support is required).

**Comment by micajuine-ho** [comment]
Hi @zarzosa , thanks for this issue. As of now, Google Analytics 4 does not support AMP. I'm not sure if they are planning to support AMP in the near future; perhaps you could file an issue with them as for AMP support. 

If you need Google Analytics with AMP, you can use a previous version of GA.

**Comment by robin-scott** [comment]
Since Google Analytics is sunsetting all versions below Google Analytics 4 next year, is there any way to work on a solution for this?

**Comment by thyngster** [comment]
While it's not the official expected support this may help at some point:  https://github.com/analytics-debugger/google-analytics-4-for-amp
