### ISSUE TITLE
DFP Ad not displaying

### ISSUE THREAD

**Issue by umashankar2015** [ampproject/amphtml#3105]
Hi 

I am using DFP Ad in AMP. It's showing random behaviour in display. Sometimes Ad displaying othertime its not. I can't say if we are loading a page 10 times then then Ad will display in x times.

I have check Ad implementation and its right. Here is the code I am using:

``` html
<amp-ad
     width="300"
     height="250"
     type="doubleclick"
     data-slot="/xxx/yyy">
   </amp-ad>
```

Please help to sort out this issue.

**Comment by michaelkleber** [comment]
Please post a public URL and ideally post a reduced test case.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
