### ISSUE TITLE
amp-consent is not working on IE11

### ISSUE THREAD

**Issue by nicobatalla** [ampproject/amphtml#31075]
## What's the issue?

If you try to use amp-consent with any supported CMP's you will get a `SyntaxError` in the  v0.js file (which is coming from AMP's CDN)

## How do we reproduce the issue?

JSBin example: https://output.jsbin.com/tiyiwasafu/1
In the JSBin example, I'm using Quantcast CMP, but you can switch to any other CMP provider and the result will be the same.

Steps to reproduce:
1) Try to use an amp-consent component with any of the supported CMP's on IE11

## What browsers are affected?

Internet Explorer 11
![image](https://user-images.githubusercontent.com/25337921/98746516-66b1ea80-2394-11eb-99a6-652152458101.png)

**Comment by micajuine-ho** [comment]
Hi @nicobatalla, I cannot repro this issue on IE11 (Version 11.1139.18362.0). Are you still experiencing this problem?

**Comment by nicobatalla** [comment]
Hi @micajuine-ho.  Yeah, it's not throwing that error anymore but the CMP is not rendered anyway. It happens with every CMP for me, it seems to load but no CMP is rendered and also there's no error in the console.

**Comment by nicobatalla** [comment]
These two CMP seems to get in the DOM without any errors whatsoever, but it's still not loading on IE (working fine on other browsers):

OpenCMP: https://output.jsbin.com/bidalibosu/1
Quantcast: https://output.jsbin.com/tiyiwasafu/1

These two throws errors but I think it's related to their iframe code:

Didomi: https://output.jsbin.com/mohipelixa/1
Usercentrics: https://output.jsbin.com/sayuguxulo/1

None gets rendered in Internet Explorer version 11.572.19041.0

@micajuine-ho Do you manage to see any CMP at all?

**Comment by micajuine-ho** [comment]
Within IE11, I followed he code path and saw that we're receiving the correct info from the `checkConsentHref` as well as the `promptUiSrc` endpoints. However, I still don't see any of the UI being displayed. 

I feel like this could be a IE11 specific CSS issue? Are you doing any browser specific styling within your iframe?

**Comment by nicobatalla** [comment]
@micajuine-ho I'm not sure about the other CMP's but I know for sure that Quantcast works fine on IE11 when it's used outside of the amp-consent context. And we use the same CMP code on the `promptUiSrc` iframe,  so it's not coming from our side.

You can check Quantcast CMP here: https://quantcast.mgr.consensu.org/tcfv2/index.html (this is the regular CMP, which is what the `promptUiSrc` iframe ends up using). If you open that link on IE11, you will see that it works fine.

I suspect that the styles that the amp-consent component is using for the iframe are not compatible with IE11, and that's why we can't see the UI of any CMP, even the ones that seem to be getting the correct info.

**Comment by samouri** [comment]
Closing as we've officially deprecated IE11. https://github.com/ampproject/amphtml/issues/34453
