### ISSUE TITLE
Application Insights missing from analytics vendors

### ISSUE THREAD

**Issue by jkusela** [ampproject/amphtml#31082]
As the title already says, MS Azure / Application Insights client side tracking is missing from the amp analytics vendors. Application Insights is used a lot and would be really great to get implementation for AMP analytics for that too.

**Comment by micajuine-ho** [comment]
Hi @jkusela, thanks for your feature request. We would love to integrate Application Insights into `amp-analytics`. Is this something that you'd like to contribute? 

Please see the [documentation here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/integrating-analytics.md) on how to integrate a new analytics vendor.
