### ISSUE TITLE
[Story] Expand the tap safety zone on large devices

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#31107]
The tap safety zones that ignores a link and navigates to the next page on the vertical edges of the screen should be expanded.
They should be a % of the page width, with a minimum of 48px.

cc @ampproject/wg-stories

**Comment by raxsha** [comment]
Currently 15%, but may be too large on larger devices. TBD-- Hong is testing 10-12%.

**Comment by hongcatlover** [comment]
Final! 12% of the screen width with the minimal number of 48.  If the result number is lower than 48 we always fall back to 48 as the minimal. TY TY!
