### ISSUE TITLE
[Story] Ignore full page links that prevent story page navigation

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#31108]
Some publishers have been creating links that cover the full page and act as click shields, preventing users from navigating to the next page.
When the event target takes more than 80% of the page area, we should ignore it and navigate to the next page.

cc @ampproject/wg-stories

**Comment by raxsha** [comment]
Log when we block a link for this reason.

ex. user().error(TAG, `Duplicate amp-story-page ID ${pageIds[i]}`);

**Comment by raxsha** [comment]
TO DO: add QA testing file & manual process.
