### ISSUE TITLE
[amp-story-360] jank in page transitions, even on pages with no 360 component

### ISSUE THREAD

**Issue by t0mg** [ampproject/amphtml#31117]
On a mid-range device I'm getting consistent jank when transitioning from page to page, with a 300-600ms freeze of the progress bar and any other animation, including but not limited to cases where neither the current nor the next page contain a 360 component (however both the previous and the N+2 ones do).

Running Chrome's profiling tool though USB debugging on a Pixel 3a, I see a very long task of 204ms for Animation Frame Fired which is initiated by [this raf](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story-360/0.1/amp-story-360.js#L821) inside of the animate_ function. It's quite strange that this function gets called at all while viewing a page that has no 360 component in it.

cc @ampproject/wg-stories @processprocess

**Comment by processprocess** [comment]
#31123 might help fix this.

This might be from handling context on page transition.
<img width="479" alt="Screen Shot 2020-11-12 at 2 20 45 PM" src="https://user-images.githubusercontent.com/3860311/98988534-cc69b800-24f5-11eb-89a7-6795ae6151a7.png">
