### ISSUE TITLE
amp-story-player triggering amp-pixel during prerender instead of when showing the story

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#31118]
## What's the issue?

Currently the `amp-story-player` triggers the `amp-pixel` in a story when the page is pre-rendered, not when it is shown.
An example can be found here: https://tappable.co. If you check the network requests, `/pixel` is called immediately on story player initialisation, instead of when the story is shown by clicking on the circle at the bottom of the page. This leads to skewed analytics.

Ideally the `amp-pixel` is fired at the same time as the `amp-img` images are loaded, ie. when the story is made visible.

## How do we reproduce the issue?

1. Go to https://tappable.co
2. Check the network requests for `/pixel`
3. See that the request is made before the story is made visible by user action (click on the story circle at the bottom of the page)

**Comment by cpauwels** [comment]
@Enriqe any ideas on how to prevent the pixel from firing on preloaded stories? Our story view analytics are completely wrong  due to this...

**Comment by Enriqe** [comment]
I think this will be solved by #31305, where we will only switch from pre-render to visible once the story is visible in the viewport. I verified that by loading the story provided as example with `visibilityState=prerender` will not trigger `amp-pixel`.

/cc @ampproject/wg-stories
