### ISSUE TITLE
AMP-bind giving inconsistent calculations.

### ISSUE THREAD

**Issue by M-J-Robbins** [ampproject/amphtml#31120]
## What's the issue?
Using amp bind to increment a number, sometimes `1+1=2` sometimes `1+1=11`.

## How do we reproduce the issue?

Code here https://codepen.io/M_J_Robbins/pen/a0efa9a6ff489bea3fea17f887d5a892

1. Open the above link to see an example
2. Use either number input or range input to change the number
3. Click "next page" button
4. 1 is placed after the number rather than added to it

The "previous" button it subtracts from the number as expected.
When clicking the "next" button as the first interaction, or after using the "previous" button it adds to the number as expected.

## What browsers are affected?

Tested in Chrome 86.0.4240.193, Firefox 82.0.3 and Safari 14.0 on mac 10.15.7 and I see same experience in all of them.

## Which AMP version is affected?

Version 2010302236001
Initially I was testing this for AMP for Email, I've also checked in AMP HTML and have the same issue.

**Comment by M-J-Robbins** [comment]
As a work around I can change `tap:AMP.setState({ page: page + 1 })` to `tap:AMP.setState({ page: (page * 1) + 1 })` and it's treated as a number and that works as expected.

**Comment by kristoferbaxter** [comment]
@M-J-Robbins I replicated this example but used a slightly different pattern.

`input-throttled:AMP.setState({ page: event.valueAsNumber })`

Now the event value is not a `String`, and other interpretations work as expected with it.

I'm going to mark this as resolved and closed, but feel free to re-open if there are other ideas you'd like us to persue.
