### ISSUE TITLE
amp-ima-video play button is pause button on click ad

### ISSUE THREAD

**Issue by spormeon** [ampproject/amphtml#31125]
After clicking an ad, being taken to a new tab, then coming back to page.  The play button is set on a pause button, should be a play button?  The "big Play" button is set on play:

If you click the pause button, it turns into a play button but hasn't started playing, click the now new play button and it starts playing again.

Once playing the play button is still in the control bar, not turned to a pause.  If you click the play button, turns to a pause button but not paused, click pause again and pauses

![Culinary_School_Discussions___ChefTalk_png](https://user-images.githubusercontent.com/8503167/98984724-7f4c0d00-251a-11eb-9b71-ac78f9372abc.png)

Details
---

| Metric                  | Field data  | Lab data    |
|-------------------------|-------------|-------------|
| LCP                     | <pass/fail> | <pass/fail> |
| FID                     | <pass/fail> | <pass/fail> |
| CLS                     | <pass/fail> | <pass/fail> |
| HTTPS                   | <pass/fail> | <pass/fail> |
| Safe browsing           | <pass/fail> | <pass/fail> |
| Mobile-friendliness     | <pass/fail> | <pass/fail> |
| Intrusive Interstitials | <pass/fail> | <pass/fail> |

Notes
---

Components in use: 

/cc @ampproject/wg-performance

**Comment by micajuine-ho** [comment]
Can you share an example test page or a link a page that can reproduce the issue?

**Comment by spormeon** [comment]
i can if you give me some way to contact you?, i'm not into putting my code in an open forum

**Comment by micajuine-ho** [comment]
Sure, my email is micajuineho@google.com

**Comment by micajuine-ho** [comment]
Hi @spormeon , `amp-ima-video` (and all the other integrated video players), installs an iframe that displays the video and ad (as well as the controls). It is up to the iframe to handle the UI of these controls as well as the video being paused/unpaused. 

All AMP does in this case is receive signals sent from the iframe. 

Please let me know if you need any more assistance.

**Comment by spormeon** [comment]
who's setting the iframe then? surely thats amp-ima-video?

**Comment by micajuine-ho** [comment]
Yes, amp-ima-video just loads the iframe that loads the `src` set by the publisher.

**Comment by spormeon** [comment]
so its a problem in amp-ima-video then surely?

**Comment by spormeon** [comment]
and this is using GAM by the way, so if its GAM setting the iframe , its over to you google guys again?

**Comment by micajuine-ho** [comment]
Sorry, to be more specific, AMP creates the iframe on the doc and then loads the `src` set by publisher inside that iframe. AMP has no control over what the iframe does or shows.

**Comment by micajuine-ho** [comment]
Hi @spormeon, after syncing with @alanorozco (our resident video expert), I actually do think that we can fix this behavior. I will take on the work.
