### ISSUE TITLE
Enable responsive attributes generally in AMP?

### ISSUE THREAD

**Issue by dmanek** [ampproject/amphtml#31122]
#### Summary

`amp-base-carousel` uses `ResponsiveAttributes` to respond to media queries and invoke callbacks when the matching media query changes. While fixing #31042, we realized that this service is potentially useful, as might be the case with other extensions that need to react to media query changes. Should we look at enabling this generally in AMP?

**Comment by dvoytenko** [comment]
Done. Available via `MediaQueryProps` utility.
