### ISSUE TITLE
🌸 Cherry-pick request for #31121 into #31085 (Pending)

### ISSUE THREAD

**Issue by t0mg** [ampproject/amphtml#31130]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #31121 | #31123 |     **YES**     | **YES** | **NO** | #31085                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

This issue affects the first stories debuting the new amp-story-360 component this week by causing jank during page transition (several hundred ms on every page) on mid-range devices and lower as well as UX inconsistencies (flaky animations) on all device types. The situation therefore matches the following 2 criteria:
- break existing AMP web pages in a significant way
- would otherwise cause a significant harm to AMP's reputation if left unresolved

## List the steps to manually verify the changes in this cherry-pick

- use a Pixel 3a, iPhone 5 or similarly powered device
- open [this story](https://www.google.com/search/static/gs/museum/m0d3c49.html), tap slowly to go all the way to the end
- go back all the way to the cover, then repeat a few times

Before the fix, the transitions will jank and some animations should skip. After the fix, animations on each page should never lose sync (ie they restart on focus, and play entirely at consistent speed). Jank is also much reduced (except one hiccup shortly after each page transition, which will addressed in a separate PR).

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

<_1-2 sentences summarizing the problem and root causes._>

## Impact

- <_Which users were affected? Roughly how many?_>
- <_How were users affected? E.g. partial or complete loss of functionality?_>

## Action Items

- #<_ISSUE_NUMBER_>: <_Add unit/integration/end-to-end test_>
- #<_ISSUE_NUMBER_>: <_Add monitoring for edge case via error logging_>
- #<_ISSUE_NUMBER_>: <_Refactor an easily misused API_>

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by kristoferbaxter** [comment]
The change looks minor to me and timely.

Approved.
