### ISSUE TITLE
amp-base-carousel loop feature only works on one item display

### ISSUE THREAD

**Issue by MKDavids** [ampproject/amphtml#31134]
Hi, 
I am trying to add an amp-base-carousel but while setting it up and testing it to see if it functions correctly I ran into what appears to be a bug, a few weird occurrences with the loop feature, this only happens when using the loop="true" feature. I am using at least 4 items, but I have increased the amount of items for testing purposes. I had this on stackoverflow but after further testing this started to react more like a bug

**1. When the carousel displays more than one image the loop doesn't function:**

- When I am trying to scroll through the items, and hit the last item and click on the arrow to continue it stops functioning. When viewing the source I noticed that the button becomes disabled
`<button class="i-amphtml-base-carousel-arrow" aria-label="Next item in carousel" disabled="">`

- The same happens on the prev button, it displays on the page but once clicked nothing happens as with the above statement it also gets marked with disabled
`<button class="i-amphtml-base-carousel-arrow" aria-label="Previous item in carousel" disabled="">`

- But once I have the page displaying only one image, be it with the visible-count or by testing responsive behaviour then the looping works fine. (Almost like amp-carousel type="slides")

Steps taken:
1. set visible count to any number higher than 1, min-width can also be used for easier testing
2. load page with amp-base-carousel 
3. click on arrows either prev or click to last image and noticed no functionality
3. change to one image and notice functionality is there

**2. On chrome when clicking the prev arrow the slide transition doesn't function properly**

- When using the prev arrow there is no slide transition. It jumps to the next item Where as clicking on next smooth slide transition. test this in firefox as well and the transition was smooth

Steps taken:
1. Test in chrome 
2. Set visible-count to one or adjust to mobile sized screen
3. click on prev arrow 

**3. Arrows disable themselves. This was addressed in the following job:** https://github.com/ampproject/amphtml/issues/27403

- As mentioned in the first job the buttons become disabled
- When the next button has had interaction with on the last item the prev button stops working
- This is issue has been addressed in the link above. But it doesn't appear to be working on my end unless
- Only work around for this is when I set the advance-count ="3"

Steps taken:
1. Click on prev button 
2. Navigate to last item and click on next button 

**Browsers tested**
FireFox - 82.0.3 (64-bit)
Chrome - Version 86.0.4240.198 (Official Build) (x86_64)

**OS**
MacOS Catalina V10.15.7

**Which AMP version is affected?**
amp-version="2010302236001"

**Code used**
https://jsfiddle.net/c8gwd1yh/9/

**Comment by micajuine-ho** [comment]
Hi @MKDavids , thanks for the issue report. 

> 1. When the carousel displays more than one image the loop doesn't function

In the scenario where you only have 4 items and `loop=true`, the looping feature doesn't actually occur because the number of slides needs to be at least 3x the visible count:
https://github.com/ampproject/amphtml/blob/3fd9a24e6b879317646db572898acc6e086491a2/extensions/amp-base-carousel/0.1/carousel.js#L469-L471
This is not documented, so I can update that.

> 2. On chrome when clicking the prev arrow the slide transition doesn't function properly

Again, the same issue applies here; the number of slides is not at least 3x the visible count, therefore the looping feature does not apply.

Please let me know if you need any other help.
