### ISSUE TITLE
Add Polling Helper

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#3114]
Spun off of https://github.com/ampproject/amphtml/pull/3112#discussion_r62236468. We should make a polling helper that will wait until some `predicate` passes, or `opt_maxWait` has passed. Then, call the `callback`. Should probably go on `Timer`...

**Comment by dvoytenko** [comment]
Also, `callback` should probably return some form of continue/stop condition. We have something similar in `vsync.runAnimMutateSeries`.

**Comment by ericlindley-g** [comment]
Putting into the Fixit milestone, but feel free to put elsewhere if there's a more specific target

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
