### ISSUE TITLE
this.isEmbedded_ is false in a WebView

### ISSUE THREAD

**Issue by ericfs** [ampproject/amphtml#3117]
https://github.com/ampproject/amphtml/blob/master/src/service/viewer-impl.js#L144

In a WebView, there is no win.parent so the above check is false.

## What browsers are affected?

WebView

## Which AMP version is affected?

All

**Comment by jridgewell** [comment]
To expand, the `window.parent` is actually `window`, even though the WebView is a managed viewer context. We'll need a bit more to determine if we are inside a viewer, though the `win.parent === win` is a good check for other environments.

**Comment by dvoytenko** [comment]
`Viewer.isEmbedded()` is a bad name. It should be `isIframed()` - most of code that uses it actually cares whether or not the page is in iframe. I suggest we renamed `isEmbedded` to `isIframed` and then we can start using `isEmbedded` for viewer-based things.

**Comment by cramforce** [comment]
+1

**Comment by ericlindley-g** [comment]
Putting this in the backlog, but please feel free to change if there's a task here with a more specific target

**Comment by dvoytenko** [comment]
Already in review.
