### ISSUE TITLE
Visual test `amphtml-ads: inabox static (page view)` is flaky

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#31199]
This flaky test is resulting in the need for manual reviews for several in-flight PRs. The problem appears to be a dynamic logo in the carousel ad image.

https://percy.io/ampproject/amphtml/builds/7718092/view/439579433/1400?mode=diff&browser=firefox&snapshot=439579433

**Comment by rsimha** [comment]
@ampproject/wg-ads-reviewers for triage
@ampproject/build-cop to skip this test if required

**Comment by powerivq** [comment]
@rsimha Thank you. We noticed it and was on it.
