### ISSUE TITLE
[Story Player] Swipe animation appears to be broken on some integrations

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#31193]
See here: https://h8ufz.csb.app/

1. Swipe to navigate forward only translates the next story. On touch release the current story flies away super fast
2. Swipe to navigate backward has no touch feedback (Story doesn't follow the finger). On touch release the two stories appear to be overlapping once they animate

cc @ampproject/wg-stories

**Comment by Enriqe** [comment]
@edoudou I'm having trouble debugging this, could you share the JS code that you used in this sample for the player please?

**Comment by gmajoulet** [comment]
Have you tried starting with an empty configuration and then using `add()` and `show()`?

**Comment by Enriqe** [comment]
Yep

**Comment by edoudou** [comment]
I'm trying to find a way to send you a public sample of my code but tbh it doesn't seems to have the same comportement.

It may have something to do with the fact that in my component i am inside a web component (with shadow root) ?

I'll try to have something working for you.

**Comment by Enriqe** [comment]
@edoudou are you still seeing this, or is this good to close?

**Comment by gmajoulet** [comment]
@edoudou please re-open if you're still experiencing this. We changed so much in the Player code and the way things are positioned / transitioned that the issue is likely gone.
