### ISSUE TITLE
🌸 Cherry pick request for #31197 into 2011140244000(Approved)

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#31203]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #31201 | #31197 |     **YES**     | **NO** | **NO** | #[Release issue not yet created]|

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

This will print a console error for all inabox ads that are not served to stories. This best fits with "otherwise cause a significant harm to AMP's reputation if left unresolved" as many publishers will see this error and assume that something is broken. 

# Mini-postmortem

This is not a stable cherry pick. Only affects inabox runtime for not-yet-created RC.

## Summary
Story ads require additional metadata. In the non-inabox case we throw an error when the ad does not have the correct metadata. When implementing this feature we shared the rendering logic, but we should not throw an error if we are inabox because we could be in a non-story context.

We ran this launch as an inabox experiment, monitoring ads metrics, but did not catch the console errors until the launch hit our nightly channel. Luckily we did catch it as soon as it hit nightly.

## Impact

All inabox ads that are not served to amp stories.

## Action Items

- #31202: Update ads RTV docs to help prevent this same mistake

**Comment by calebcordry** [comment]
to @kristoferbaxter for approval

cc/ @rcebulko @ampproject/wg-monetization @jeffkaufman

**Comment by kristoferbaxter** [comment]
Approved. Thanks for catching this before it got out to a wider audience!

**Comment by jeffkaufman** [comment]
Thanks for the quick fix!

**Comment by rcebulko** [comment]
This cherry-pick is in 2011140244001 (recently promoted to opt-in). There's a follow-up cherry-pick #31232 as well. See above linked release tracking issue for details.
