### ISSUE TITLE
Fixed layer: Chrome 52 switched to yield calculated getComputedStyle values, now auto

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#3121]
Starting v52 it appears Chrome has switched to using `getComputedStyle` more inline with Firefox by resolving `auto` values to the actual calculated values.

See https://bugs.chromium.org/p/chromium/issues/detail?id=589347 for more details.

E.g. the following example (see http://jsbin.com/wowowu/edit?html,css,js,output):
```
<div id=fixed></div>
<style>
#fixed {
  position: fixed;
  bottom: 10px;
  height: 100px;
  background: red;
  left: 10px;
  right: 10px;
}
</style>
```

And running this code:
```
window.getComputedStyle(fixed, null)['top']
```

This will yield `auto` in Chrome 49 and (e.g.) `400px` in Chrome 52.

**Comment by mkhatib** [comment]
What part of amp will this affect? the fixed position hack?

**Comment by dvoytenko** [comment]
Fixed Layer, but not the hack part. We have an option to offset `top: X` CSS definitions via `top: calc(paddingTop + X)`. We only do it when `top != auto`, of course.
