### ISSUE TITLE
[amp-story-360] Smooth motion sensor signal

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#31215]
Smooth the motion sensor signal instead of rendering raw sensor data.
This will improve the gyroscope UX with a subtle steadycam effect.

The delta between previous and next values could be averaged with a factor between 0 and 1.

Snippet from @t0mg 
> this.smoothValue = sensorValue * reactionSpeed + this.smoothValue * (1 - reactionSpeed); 

cc @ampproject/wg-stories

**Comment by t0mg** [comment]
Note: I guess at the first render the value might need to be initialized with the raw sensor value, to avoid a "drift" on start
