### ISSUE TITLE
[Story Player] Improve player build/layout strategy

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#31225]
Opening most pages using a player ([example](https://www.greenschemetv.net/gluten-free-cream-cheese-brownies/)) with a very fast computer/network speed, I'd expect the story to be loaded before it gets in the viewport. We should consider making our build/layout strategy more aggressive.

cc @ampproject/wg-stories

**Comment by Enriqe** [comment]
As discussed offline, we will start loading the player when it's further away from the viewport. But we will also place the first story in prerender mode and only set it to visible once it's in the viewport, to handle situations like https://github.com/ampproject/amphtml/issues/29798
