### ISSUE TITLE
Resource management of analytics

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#3122]
This is more of a hypothetical, but I'm wondering if our resource download algo might do a bad job on pages that have many `amp-analytics` and `amp-pixel` tags. Right now we load them after content but before ads, and we have them participate as part of normal scheduling. They are, however, essentially free in terms of bandwidth, so I'm wondering if we should treat them somehow specially.

One simple way would be to change the `amp-analytics/pixel` implementations to return a resolved promise from `layoutCallback`.

CC @dvoytenko @avimehta

**Comment by avimehta** [comment]
How would this affect amp-analytics and how would this affect the scheduling? Will this result in analytics pings being sent  even later?

**Comment by cramforce** [comment]
It would send them at the same time or earlier (Because all would be sent at the same time, as opposed to only N at a time). This would only affect the start time of us loading resources that get prioritized after analytics (which are ads and other resources that are further away from the viewport).

**Comment by dvoytenko** [comment]
Generally, for page-wide functionality as in `amp-analytics` (and probably `amp-pixel` as well), I don't see much point in relying on layout callbacks of general element infrastructure. I think, the services should simply rely on viewer visibility events and do their work independently of the main resource manager.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
