### ISSUE TITLE
Separate FIE resource manager from the main doc

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#31246]
TODO:

- [x] Create an experiment
- [x] Try to reuse inabox resource manager for FIE
- [x] Implement FIE lifecycle methods: pause, resume, and unload
- [x] Support FIE service disposal and ignore adopted services
- [x] Resolve in-viewport callbacks
- [x] Define a4a experiment branches
- [x] Launch "fie-resources"
- [ ] ~Re-launch "intersect-resources"~
- [x] Cleanup "fie-resources"
- [x] Cleanup "fie-resources" flags
- [x] Launch visibility tracker in the `InaboxResources` for inabox (INABOX_VISIBILITY_RESOURCES).
- [x] Cleanup INABOX_VISIBILITY_RESOURCES
- [ ] ~Implement `updateOrEnqueueMutateTask` API in inabox-resources?~

/cc @ampproject/wg-monetization

**Comment by dvoytenko** [comment]
Launch: 0.5% opt-in, 5% stable.

**Comment by samouri** [comment]
@dvoytenko: whats the status of this?

**Comment by dvoytenko** [comment]
I sent the final cleanup in #32746.
