### ISSUE TITLE
Implement a flying carpet visual effect for AMP - applicable to any amp-element in general but specifically for Ads

### ISSUE THREAD

**Issue by kashyapnitin** [ampproject/amphtml#3126]
**Primary objective:**
Allow publishers to be able to show <amp-ads> as flying carpets
Illustrative (but not necessarily final mock) here
![fc-mock](https://cloud.githubusercontent.com/assets/14791037/15071029/879969b8-1380-11e6-914c-7526e061c35d.gif)

**Secondary objective:**
Make it really easy in AMP to give the same visual treatment

**Rationale:**

- It’s a nice visual format 
- It’s traditionally not easy to do and would require special treatments / JS in the creative itself
- AMP can make it really easy to give this treatment to any amp-element not just ads, and do so in a performance compliant way
- It is also principally not against any of AMP rules around knowing size and placement of amp-elements in advance
- It can be a good differentiator / pull factor for amp pages
- When used for ads it is likely to generate higher viewability and CTRs (To be verified)

**Requirements:**

- Publisher should be able to specify that they want AMP runtime to render / layout an <amp-ad> or any eligible <amp-element> using the flying carpet layout
- Publisher should be able to pass in an any additional information needed to render / layout the given amp-element as a flying carpet - such as max size of the flying carpet, its position in the page and its position relative to the viewport (when the flying carpet is fully visible)
- Clicks, taps and swipes etc. within the flying carpet window should work as expected
- The flying carpet window should never be larger than the device viewport 
- The element that is shown within the flying carpet window is always center aligned

**Comment by ericlindley-g** [comment]
@jridgewell , passing to you (feel free to correct if you're not the primary Eng owner)—do you have a milestone target for this? (will put in "pending..." for now)

**Comment by jridgewell** [comment]
Closed by https://github.com/ampproject/amphtml/pull/3118.
