### ISSUE TITLE
Intent-to-Deprecate-and-Remove: <amp-google-vrview-image>

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#31268]
## Summary

This issue is being filed for awareness and discussion as a formality, however as clarified in #25573, this is not strictly necessary to go forward with removal.

`<amp-google-vrview-image>` displays mono and stereo 360 images via [Google VR View](https://developers.google.com/vr/develop/web/vrview-web). See [reference documentation](https://amp.dev/documentation/examples/components/amp-google-vrview-image/). It is not and was never valid AMP, so this is a proposal to remove the component. 

Removal plan: Unregister the component, remove associated documentation from codebase. This removal does not impact valid AMP usage, but does involve removing any amp.dev content that references this component, namely [the associated example page ](https://amp.dev/documentation/examples/components/amp-google-vrview-image/)which contains no valid examples.

## Motivation

No one is currently using it as it is not valid AMP. It does respect an experiment flag, which will enable the feature on invalid AMP pages.

## Impact on existing users

None

## Alternative implementation suggestion for developers using AMP

For publishers implementing Web Stories, `<amp-story-360>` is the recommended alternative. For publishers in other formats, there are not recommended alternatives, however this should not impact the existing developer experience. If there is interest in the feature, we could alternatively launch `amp-google-vrview-image` as is or file a master issue for an updated version (for instance, the Google VR View documentation now recommends using alternatives such as [Cardboard SDK](https://developers.google.com/cardboard)).

## Additional context

/cc @ampproject/wg-approvers @ampproject/wg-components

**Comment by dvoytenko** [comment]
Since it was never launched, I don't think we need to follow the normal deprecation procedure.

**Comment by kristoferbaxter** [comment]
Approved to remove, let's move forward since there is no usage.
