### ISSUE TITLE
Errors in bodymovin.min.js using "amp-bodymovin-animation"

### ISSUE THREAD

**Issue by GhufranShahid** [ampproject/amphtml#31275]
## What's the issue?
I am using JSON created on Adobe After Effects in "amp-bodymovin-animation" but it is giving errors in browser console in bodymovin.min.js file.

## How do we reproduce the issue?
Use the JSON mentioned below in your amp-bodymovin-animation code you can check error in browser console.
https://www.ppcexpo.com//Content/images/Chartexpo/chartexpo_v3gzip.json
This same JSON is running perfectly using lottie.js you can preview it on
https://www.ppcexpo.com/ChartExpo/ppc-charts
 
## What browsers are affected?

All browsers.

## Which AMP version is affected?
I am using <script async custom-element="amp-bodymovin-animation" src="https://cdn.ampproject.org/v0/amp-bodymovin-animation-0.1.js"></script>

**Comment by micajuine-ho** [comment]
Hi @GhufranShahid  can you share an example webpage the demonstrates this error (you can host it on [jsbin](https://jsbin.com/?html,css,js,output))? Can you also specify what type of error you are getting?

**Comment by GhufranShahid** [comment]
@micajuine-ho thanks for your reply.

![image](https://user-images.githubusercontent.com/37533270/99962458-08343580-2db2-11eb-8913-42f31ccf27d4.png)
Errors are shown in above screenshot.

You can view the example on following link
https://apps.polyvista.com/amp/amptest.html

You can also see our code in following zip file
[test.zip](https://github.com/ampproject/amphtml/files/5583014/test.zip)

**Comment by micajuine-ho** [comment]
Hi @GhufranShahid the error is coming from a 3p script that we load:

https://github.com/ampproject/amphtml/blob/85b486ea4083978ec74313693c7ce04956a845c7/extensions/amp-bodymovin-animation/0.1/amp-bodymovin-animation.js#L73-L81

@nainar Do you know why we install these scripts?

**Comment by micajuine-ho** [comment]
Seems like the player is out of date: 

https://cdnjs.com/libraries/bodymovin

Maybe we should think of a solution to always have the most up to date version?

**Comment by GhufranShahid** [comment]
How can I use the most up to date version using "amp-bodymovin-animation"?

**Comment by micajuine-ho** [comment]
Closed via #32315
