### ISSUE TITLE
Webmaster tool reporting "Prohibited or invalid use of HTML Tag"

### ISSUE THREAD

**Issue by gkteck** [ampproject/amphtml#3127]
Hi,
My Webmaster tool is showing close to 200  page errors with the above type.

All these 200 pages are successfully validated by using #development=1

Here is a sample page.

goo.gl/8oBpJL

**Comment by Gregable** [comment]
Looking into it. This will likely resolve itself when the page is recrawled, but there may be a larger issue. Thanks for the report.

**Comment by Gregable** [comment]
This is out of date and fixed. Closing. Some corrupt data made it's way into search console reports for a small number of pages.
