### ISSUE TITLE
amp-carousel: make it possible to reveal specific slides

### ISSUE THREAD

**Issue by borisf** [ampproject/amphtml#3128]
A common feature of retail websites are image carousels in which each slide can be triggered via a user action, e.g. via link or thumbnail picture ([example](http://www.allsaints.com/women/denim/style,any/colour,any/size,any/?view=all)). 

Here is what a solution could look like:

```
<amp-carousel id="my-carousel" type="slides">
  <div id="slide1"> ... </div>
  <div id="slide2"> ... </div>
</amp-carousel>

<a on='tap:my-carousel.slide1.reveal'>show slide 1</a>
<a on='tap:my-carousel.slide2.reveal'>show slide 2</a>
```

The idea is to add a `on="tap"` action which reveals slides in an amp-carousel. Slides and carousel are identified via `id`. This might even make sense not only for slides, but also the default mode.

//cc @sebastianbenz @ericlindley-g

**Comment by jridgewell** [comment]
Related to https://github.com/ampproject/amphtml/issues/1532?

**Comment by ericlindley-g** [comment]
Like #1532, this is a good suggestion. We're looking into carousel enhancements now, and this kind of thing may get easier with some of the work needed to make those improvements

/cc @sriramkrish85 @dvoytenko

**Comment by adelinamart** [comment]
@ericlindley-g I think this can be closed?

**Comment by jridgewell** [comment]
Yup. https://github.com/ampproject/amphtml/blob/master/extensions/amp-carousel/amp-carousel.md#advancing-amp-carouseltypeslides-to-a-specific-slide

**Comment by ericlindley-g** [comment]
Yep—thanks! @borisf  (and others interested), you can find an example of this in action [here](https://ampbyexample.com/advanced/image_galleries_with_amp-carousel/) (in the "image galleries with previews" section)
