### ISSUE TITLE
`amp-fit-text` doesn't consistently ellipsize depending on its initial width

### ISSUE THREAD

**Issue by TomerAberbach** [ampproject/amphtml#31287]
## What's the issue?

Under certain circumstances, `amp-fit-text` doesn't consistently ellipsize its contents depending on its initial width.

## How do we reproduce the issue?

Visit [this AMP playground link](https://playground.amp.dev/?runtime=amp4email#share=PCFkb2N0eXBlIGh0bWw+CjxodG1sIOKaoTRlbWFpbD4KPGhlYWQ+CiAgPG1ldGEgY2hhcnNldD0idXRmLTgiPgogIDxzY3JpcHQgYXN5bmMgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC5qcyI+PC9zY3JpcHQ+CiAgPHNjcmlwdCBhc3luYyBjdXN0b20tZWxlbWVudD0iYW1wLWZpdC10ZXh0IiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1maXQtdGV4dC0wLjEuanMiPjwvc2NyaXB0PgogIDxzdHlsZSBhbXA0ZW1haWwtYm9pbGVycGxhdGU+Ym9keXt2aXNpYmlsaXR5OmhpZGRlbn08L3N0eWxlPgo8L2hlYWQ+Cjxib2R5PgogIDxkaXYgc3R5bGU9ImZvbnQtc2l6ZTogMTRweDsgbGluZS1oZWlnaHQ6IDE4cHg7Ij4KICAgIDxkaXYgc3R5bGU9InBvc2l0aW9uOiByZWxhdGl2ZTsgbWF4LWhlaWdodDogMzZweDsiPgogICAgICA8ZGl2IHN0eWxlPSJ2aXNpYmlsaXR5OiBoaWRkZW47IG92ZXJmbG93OiBoaWRkZW47Ij5UZXh0IFRoYXQgSXMgUmVhbGx5IExvbmcgQW5kIEtlZXBzIEdvaW5nIEZvciBhIFdoaWxlIERlc3BpdGUgTWFueSBBdHRlbXB0cyBUbyBNYWtlIEl0IE11Y2ggU2hvcnRlcjwvZGl2PgogICAgICA8YW1wLWZpdC10ZXh0IGlkPSJhbXAtZml0LXRleHQiIGxheW91dD0iZml4ZWQtaGVpZ2h0IiBoZWlnaHQ9IjM2IiBtaW4tZm9udC1zaXplPSIxNCIgbWF4LWZvbnQtc2l6ZT0iMTQiIHN0eWxlPSJwb3NpdGlvbjogYWJzb2x1dGU7IHdpZHRoOiAxMDAlOyB0b3A6IDA7IGxlZnQ6IDA7IHJpZ2h0OiAwOyBib3R0b206IDA7Ij5UZXh0IFRoYXQgSXMgUmVhbGx5IExvbmcgQW5kIEtlZXBzIEdvaW5nIEZvciBhIFdoaWxlIERlc3BpdGUgTWFueSBBdHRlbXB0cyBUbyBNYWtlIEl0IE11Y2ggU2hvcnRlcjwvYW1wLWZpdC10ZXh0PgogICAgPC9kaXY+CiAgPC9kaXY+CjwvYm9keT4KPC9odG1sPg==) and notice that `amp-fit-text` ellipsizes correctly for the entire session if its initial width should result in ellipsizing, but that it does not correctly ellipsize otherwise. See the [video in this ZIP file](https://github.com/ampproject/amphtml/files/5575722/Screen.Recording.2020-11-20.at.2.31.48.PM.zip) of the issue (GitHub didn't let me upload the unzipped video file).

Note that the playground code is a real-world use case. The purpose of the code in the playground is to ellipsize after a certain number of lines (2 in this case), but prevent the text from taking up the height of two lines when the height of one line is sufficient to contain the text (this is done by having an additional `div`, with `visibility: hidden;` and containing the same text, determine the height of the outer `div`).

## What browsers are affected?

I noticed this issue in Chrome, Firefox, and Safari (these are the browsers I have installed on my Mac). I suspect it occurs in every browser.

## Which AMP version is affected?

The version printed in the console was 2011070101001. I don't know how long this bug has been around.

**Comment by caroqliu** [comment]
@TomerAberbach Thanks for filing this issue! I can reproduce in the email and web formats. 

Please note also: This issue cannot be reproduced in `amp-fit-text:1.0` (in development).

**Comment by micajuine-ho** [comment]
@rebeccanthomas Is this related to your `fit-text`issue?

**Comment by caroqliu** [comment]
Neither @TomerAberbach nor I can reproduce the original issue anymore. It looks to be fixed in or before `2012301722001`, which oddly enough does not appear to contain #31317. Closing the issue.
