### ISSUE TITLE
amp-carousel not showing images with layout="responsive" and type="carousel"

### ISSUE THREAD

**Issue by morsssss** [ampproject/amphtml#31304]
## What's the issue?

I ran across this while teaching an AMP workshop. It seems that, for an `<amp-carousel layout="responsive" type="carousel">` that contains only `<amp-img>`'s with `layout="responsive"`, the images are not displayed in Chrome on Mac OS.

This use case seemed so basic that I assumed the project's CSS or other factors were at fault. But even when I removed all the other elements from the page and all of the custom CSS, the issue still existed.

## How do we reproduce the issue?

This HTML is sufficient:

```html
  <body>
    <main>
      <amp-carousel width="412" height="309" layout="responsive" type="carousel">
        <amp-img width="412" height="309" layout="responsive" src="https://cdn.glitch.com/d7f46a57-0ca4-4cca-ab0f-69068dec6631%2Fcheddar-chaser.jpg?1540228205366">
        </amp-img>
        <amp-img width="412" height="309" layout="responsive" src="https://cdn.glitch.com/d7f46a57-0ca4-4cca-ab0f-69068dec6631%2Fcheese.jpg?1540228223785">
        </amp-img>
        <amp-img width="412" height="309" layout="responsive" src="https://cdn.glitch.com/d7f46a57-0ca4-4cca-ab0f-69068dec6631%2Fmouse.jpg?1540228223963">
        </amp-img>
      </amp-carousel>
    </main>
  </body>
```

You can try this at https://amp-carousel-bug.glitch.me/ . The code is at http://glitch.com/~amp-carousel-bug .

It seems that the sizer `<div>` takes up most of the height. What remains for the `<div class="i-amphtml-carousel-content">` is only 18px high. Each `<amp-img>` is 0x0.

If I change the carousel to `type="slides"`, it works perfectly.

**Comment by caroqliu** [comment]
Thanks for filing this! I was able to reproduce. One difference I am seeing is that the `.i-amphtml-carousel-content` element that you pointed out has an overridden `position: static` for `:not([type=slides)` - if we disable this, the lower specificity `position: absolute` restores it to the full expected size of the sizer rather than the static `18px`. This however does not solve the issue with the 0x0 `amp-img` elements.

**Comment by morsssss** [comment]
I'm glad you could reproduce this!

I believe the `amp-img` elements are 0x0 because none of them contains an actual `<img>` - so they lack dimensions. If we change the carousel to `type="slides"`, the images are loaded.

Otherwise, all each `<amp-img>` contains is the sizer element:

```html
<amp-img width="412" height="309" layout="responsive" src="https://cdn.glitch.com/d7f46a57-0ca4-4cca-ab0f-69068dec6631%2Fcheddar-chaser.jpg?1540228205366" class="i-amphtml-element i-amphtml-layout-responsive i-amphtml-layout-size-defined i-amphtml-built amp-carousel-slide amp-scrollable-carousel-slide" i-amphtml-layout="responsive" role="listitem" aria-hidden="false" style="scroll-snap-align: start; transform: translate(0px, 0px); --content-transform:translate(0px, 0px) !important;">
  <i-amphtml-sizer slot="i-amphtml-svc" style="padding-top: 75%;"></i-amphtml-sizer>
</amp-img>
```

@rebeccanthomas , thanks for taking a look at this!

**Comment by morsssss** [comment]
Thanks for the rapid fix @micajuine-ho !

One more question: are we still maintaining `amp-carousel-0.1`? Because the bug occurs in that version too. And I'm sure the installed base of v0.1 is quite extensive....

**Comment by micajuine-ho** [comment]
I think we probably should fix this in 0.1 but would like to confirm with @nainar first.

**Comment by morsssss** [comment]
Makes sense. @nainar , it strikes me that either we should fix bugs like this one in 0.1 or we should document that 0.1 is no longer maintained, and that people should migrate to 0.2.

**Comment by frederico-neto** [comment]
Hey guys ... the way this was fixed introduced a new bug ... it added a width 100% to the slides making it impossible to have 3 "cards" in on slide in caroucel ... it is still possible in version 0.1 .. but not in 0.2 .. i can gice exemples .. we made the effort to migrate to 0.2 .. and now is broken in our use case ...

**Comment by frederico-neto** [comment]
the width in ok .. just don't use !important ...

**Comment by micajuine-ho** [comment]
With the roll back in https://github.com/ampproject/amphtml/pull/31514, we'll need to tackle this again-- proabably with a more specific ruleset for the CSS.
