### ISSUE TITLE
amp-youtube loads slowly inside amp-lightbox

### ISSUE THREAD

**Issue by borisf** [ampproject/amphtml#3131]
## Description
When we embed amp-youtube inside amp-lightbox, it takes too long until the video embed is loaded.

## Steps

The [page] (https://amp-by-example-staging.appspot.com/sample_amps/product_sample/) to reproduce. Here is the code sample

```
    <a on="tap:watch-video-lightbox"
        role="button"
        class="button button-secondary play"
        tabindex="0">
      Show Video
    </a>

    <amp-lightbox id="watch-video-lightbox"
        layout="nodisplay">
      <div class="amp-youtube-container">
        <div class="video">
          <a on="tap:watch-video-lightbox.close"
              role="button"
              tabindex="0">
            Close
          </a>
          <amp-youtube width="480"
              height="270"
              layout=responsive
              data-videoid="4cAHL4LMNlY">
          </amp-youtube>
        </div>
      </div>
    </amp-lightbox>
```
## What browsers are affected?
Chrome and Chrome on Android

**Comment by borisf** [comment]
cc @sebastianbenz

**Comment by cramforce** [comment]
I think that happens is that we fail to either call `viewportCallback` or to schedule layouts upon opening.

CC @dvoytenko @mkhatib

**Comment by dvoytenko** [comment]
We definitely do both. @mkhatib could you PTAL?

/cc @jridgewell

**Comment by mkhatib** [comment]
Quick debugging, the `updateInViewport` call seems to fail to actually set elements in viewport because the parent lightbox `setInViewport` is never called because its `isDisplayed` return false because its `layoutBox` width and height are both 0.

Will need to do some more debugging to see why that is the case.

**Comment by dvoytenko** [comment]
@mkhatib That most likely means that we need to call `Resource.requestMeasure()` or force remeasure of the lightbox element in some other way. Ideally we should switch to `mutateElement` API.

**Comment by mkhatib** [comment]
Yeah. Doing this quickly force remeasuring and allows discoverWork to set the parent lightbox in viewport before updating the children viewports:
```javascript
  updateInViewportForSubresources_(parentResource, subElements, inLocalViewport) {
    parentResource.measure();
    this.discoverWork_();
    ...
}
```

I somehow realize doing the above is kinda of bad (?) so thanks for the comment on `mutateElement`, just realized that it does much more than I thought initially. So doing this in lightbox through the `mutateElement` API fixes the problem!

```javascript
    this.mutateElement(() => {
      this.element.style.display = '';
      this.element.style.opacity = 0;
      // TODO(dvoytenko): use new animations support instead.
      this.element.style.transition = 'opacity 0.1s ease-in';
      requestAnimationFrame(() => {
        this.element.style.opacity = '';
      });
    }).then(() => {
      this.updateInViewport(this.container_, true);
      this.scheduleLayout(this.container_);
    });
```

This is the right way to do this, correct? Sending a PR right now.

**Comment by dvoytenko** [comment]
@mkhatib I have one concern with this approach - specifically that `mutateElement` will not know when the mutation itself is done, while it normally should. There's an easy way to "fix" that by providing a variation to this API that allows the callback to return a promise (or via `done` callback).

```
this.mutateElement(() => {
  ...
  return promise;
})
```

Ping me to discuss this in a bit more detail.
