### ISSUE TITLE
amp-list没有执行数据加载请求

### ISSUE THREAD

**Issue by qing179** [ampproject/amphtml#31327]
书写的方法是没有问题的，数据单独请求也是正常的，但是放到这个里面就没有执行了，不知道是否amp有进行版本的更新
<amp-list src="/amp/indexProduct" layout="fill" id="list_id">
                {{literal}}
                    <template type="amp-mustache">
                        <a class="index-item" href="{{url}}?amp" role="button" tabindex>
                            <amp-img layout="responsive" width="200" height="200" src="{{c_img}}"></amp-img>
                            <p>{{c_name}}</p>
                        </a>
                    </template>
                {{/literal}}
            </amp-list>

**Comment by krdwan** [comment]
@qing179 - Using google translate, I understood your problem as the following:

```
There is no problem with the writing method. It is normal to request the data separately, but it will not be executed if it is placed in this. I don't know if the amp has been updated.
```

However, we do not have any chinese readers on the team.  Can you provide some examples or maybe an english description?  Thanks so much!

**Comment by qing179** [comment]
找到原因了，amp-list中layout="fill"设置了这个属性，当数据还没加载过来的时候，列表就无法自适应高度导致了内容加载不出来，但是之前用这个属性设置是没问题的，不知道你们内部文档是否有做过调整呢，目前暂时把layout="fixed"设置成fixed，但是这个不能自适应，能否有什么更好的办法处理呢， @krdwan [https://www.getnamenecklace.com/?amp](url)这是我们的页面地址，麻烦帮忙看下哈，谢谢
