### ISSUE TITLE
[amp-story-player] Exception when player is not in viewport when loading

### ISSUE THREAD

**Issue by pshihn** [ampproject/amphtml#31333]
## What's the issue?

When amp-story-player is added down the page, when the page loads, it is not in view. After some time it throws na exception:

```
log.js:710 Uncaught Error: Render timeout waiting for service amp-story-render to be ready.​​​
    at gb (log.js:710)
    at cb.f.createError (log.js:359)
    at timer-impl.js:142
    at timer-impl.js:83
```

## How do we reproduce the issue?

Create a web page with lots of content before `amp-story-player ` is added. 
Load the page, look at the console. 

## What browsers are affected?

Saw it on Chrome but likely happens everywhere

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 2011070101001

**Comment by gmajoulet** [comment]
Thanks for filing this ticket! Could you confirm that you're seeing the error but the Story is working as intended? We should reduce the severity of this log, down from Error to Warning or something.

#31305 and its usage of the `prerender` mode will improve this by a lot in the meantime.

**Comment by pshihn** [comment]
The story does still work unless you call `pause()` on the player when it's not in the viewport. Then story fails to load.

**Comment by gmajoulet** [comment]
Sounds good thank you for confirming, @Enriqe will look into this `pause()` issue separately, we'll cc you on a new dedicated ticket

**Comment by pshihn** [comment]
Created https://github.com/ampproject/amphtml/issues/31392 for the `pause()` issue
