### ISSUE TITLE
[amp-story-player] should have events when a story page is paused/played

### ISSUE THREAD

**Issue by pshihn** [ampproject/amphtml#31335]
## Describe the new feature or change to an existing feature you'd like to see

I'd like to know when story page is paused/played so i can update my custom controls accordingly. 

## Additional context

There is no play/pause button in certain cases (https://github.com/ampproject/amphtml/issues/31332) so one needs to create their own. It may also be useful in updating other stuff on the page when a story is paused/played.

**Comment by gmajoulet** [comment]
Closing this one as it would be addressed in https://github.com/ampproject/amphtml/issues/31332. You correctly mentioned that the Story should render its own play/pause button as they have all the required information + better placement for the button.

If there are additional things you'd like to build using the paused/play state feel free to reopen!
