### ISSUE TITLE
[AMP story Ads] Request to Enable programmatic demand , direct sold ads in AMP story (Beta) via Admanager (DFP)

### ISSUE THREAD

**Issue by hugoteam-demo** [ampproject/amphtml#31345]
Hi AMP team. We interested in the beta of AMP story ads via Ad manager (DFP). We are using Google adsense on our websites, everything is running fine. The amp-auto-ads feature is best choice for our AMP posts. However, we want to promote AMP story more and more.
Can you enable this beta feature (e.g, Programmatic ads, Direct sold) to we use Ad manager & serve ads within our AMP story? AMP story is too cute.
Thanks.

**Comment by muratkalenderoglu** [comment]
https://github.com/ampproject/amphtml/issues/31345#issue-752820178

**Comment by hugoteam-demo** [comment]
Update for new visitor, 
on Dec 10, AMP dev team published new article for AMP story Ads - Adsense & Admanager. Details more: https://blog.amp.dev/2020/12/10/google-launches-programmatic-ads-for-web-stories/
Some points:  
+/ in 2018, we have to register for beta of AMP story ads & in 2020, we don't, right?
+/ _"The new programmatic capabilities, currently in an open beta, are available for all publishers that use Ad Manager and AdSense, and will start off by leveraging multiple types of mobile demand from Google Display Ads, with more demand sources coming soon."_
+/ example, Adsense: 
```
<amp-story-auto-ads>
<script type="application/json">
{
  "ad-attributes": {
    "type": "adsense",
    "data-ad-client": "ca-pub-0000000000000000",
    "data-ad-slot": "00000000"
  }
}
</script>
</amp-story-auto-ads>
```
+/ We tried to putted code in [this amp story post](https://bottlend.com/story/hunter-biden-docs-photos-clips-chatlogs-emails/). 
However, seems like it didn't display Ads, did it? Can Anyone re-check? Thx
* Checked AMP test tools. Its ok.
* Set Ad unit for Adsense: Display ads & Responsive.
* Set amp-story-auto-ads above.
* Our story containing > 7 pages
