### ISSUE TITLE
amp-ad DFP serving Taboola - possible?

### ISSUE THREAD

**Issue by antipath** [ampproject/amphtml#3136]
Hello,

Is it currently possible to serve taboola ads via the amp-ad using type "doubleclicks"?

I know there is the amp-embed which supports taboola itself, but ads there aren't served via DFP that way.

Thanks,
Vince

**Comment by jridgewell** [comment]
Assigning to @bobcassels, though I'm not sure if there's someone better suited to answer.

**Comment by bobcassels** [comment]
I'm not sure I understand the question. Have you looked at the documentation for [amp-embed](https://github.com/ampproject/amphtml/blob/master/builtins/amp-embed.md) and specifically [taboola](https://github.com/ampproject/amphtml/blob/master/ads/taboola.md)?

**Comment by jasti** [comment]
hi @antipath, how do you currently do this in a non-amp environment? Do you have a link to a DFP lineitem?

**Comment by antipath** [comment]
@bobcassels,

"For now you could certainly serve a regular HTML taboola unit from DFP." -> any examples of how you can embed a taboola ad within the DFP amp-ad component?

Thanks,
Vince

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please verify first whether the feature proposal is still relevant.

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
