### ISSUE TITLE
AMP and new law GDPR 2020

### ISSUE THREAD

**Issue by mandril888** [ampproject/amphtml#31361]
## Describe the new feature or change to an existing feature you'd like to see

With the new law, it must be possible to select the different tracking possibilities, such as advertisements, analyze the user, etc.

## Describe alternatives you've considered

There ara no alternatives, AMP only allows <amp-consent>, and it is impossible to manage diferents options.

**Comment by micajuine-ho** [comment]
Hi @mandril888 , it sounds like https://github.com/ampproject/amphtml/issues/31607 should be able to help satisfy this requirement. Please let me know what you think.

**Comment by morsssss** [comment]
I concur - #31607 is designed to provide exactly the sort of granular consent that I believe you're looking for!

Please reopen this if you think we're missing anything.
