### ISSUE TITLE
Google AMP can not Scrolling in on real IPhone (iOS 12) when click result of search Google

### ISSUE THREAD

**Issue by ducnguyenphanhoai** [ampproject/amphtml#31364]
## What's the issue?

I was have test case with my website and Google AMP not work. I was tested on android version and some difficult version IOS new. 
When I search my website on google is thefunkyball.com and after that I was click on my website and see AMP version. It can't scroll down to see content. It useful when test on PC and some different device, but IOS 12 not work, I was read some post have the same error but have no question to fix that. Have anyone help me detail to fix this? I very need that resolved. Have any error about javascript or html or css?

## How do we reproduce the issue?

I was test case with my website. I use my mobile and test a lot of version AMP is work but with my site it don't:

1. I searching on google my website thefunkyball.com.
2. I click on search result.
3. I can't scrolling on my apple phone ios 12. But it work when I test with android.
4. I was try research have some same issue but it can't resolved.
5. I was try add code into style.css like this:

```
    html {
         position: fixed;
         outline: 0;
    }

```
And this:

```
    html {
        -webkit-overflow-scrolling: touch !important;
    	position: fixed;
    }    
```
	
6. But it don't work

## What browsers are affected?

IOS 12. On browser Safari

## Which AMP version is affected?

Current version. I was update on newest version AMP on Wordpress website.

I was chat and support in this link but not useful: https://github.com/ampproject/amphtml/pull/23538#issuecomment-732491937
This is clip I was testing: https://bit.ly/2JqXljx

**Comment by ericfs** [comment]
Thank for the report. Filed internal issue b/178405438
I'm sharing with the team

**Comment by ericfs** [comment]
@jridgewell @dvoytenko for your iOS scrolling expertise

**Comment by cyface** [comment]
Confirmed I am also getting this behavior as well; only on AMP links clicked from Google Search results.  This happens very aggressively in embedded browsers like the Google App and Google News App to the point where AMP pages are totally stuck for up to 45 seconds before they are scrollable.

**Comment by ericfs** [comment]
Thanks for the additional report. I am able to reproduce the issue for the document you noted in the Google Search App. It looks like there is a double scroll bar.

![724E1B86-E947-443D-9244-7037D52A8546](https://user-images.githubusercontent.com/851850/105910668-44288880-5ff7-11eb-9691-f4eec5047c94.png)

**Comment by jridgewell** [comment]
@cyface: We're addressing your issue with #32232, but this is unrelated to the issue bug (which only happens on iOS 12 in Safari).

**Comment by samouri** [comment]
@jridgewell: can this be closed now?
