### ISSUE TITLE
🌸 Cherry-pick request for #31371 into #31314 (Complete)

### ISSUE THREAD

**Issue by powerivq** [ampproject/amphtml#31374]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #31371 | #31371 |     **YES*    | **YES** | **NO** | #31314                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

Ads made a PR to log ad network usages on amp error reporting (https://github.com/ampproject/amphtml/pull/30992). The traffic was too large on prod so that the error reporting project was overloaded. CP so that we can recover the error reporting.

## List the steps to manually verify the changes in this cherry-pick

<_TEST_STEPS_>

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

Inadequate traffic estimate for logging.

## Impact

- No direct end user impact
- However, error reporting being unusable might mask some real issues

## Action Items

In the future, infra will be consulted to assess the log traffic.

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by kristoferbaxter** [comment]
Approved. Thanks for moving quickly.

**Comment by rsimha** [comment]
The code has been cherry-picked to this week's [stable channel](https://github.com/ampproject/amphtml/releases/tag/2011200012001) and to this week's beta channel (opt-in), which will go to stable next week.

Assigning back to @powerivq for post-mortem and close out.

**Comment by Enriqe** [comment]
[Cleaning up old CP issues] Can this be closed?
