### ISSUE TITLE
[amp-story-player] Bookend does not show up when playing the story in amp-story-player

### ISSUE THREAD

**Issue by pshihn** [ampproject/amphtml#31380]
## What's the issue?

A web story has a bookend, but it does not show up when playing the story in the amp-story-player

If you have another story queued up, it makes sense to not have a bookend and play the next story, but if it's the only story - the bookend should show. 

Alternative is to show the full bookend when the share button is clicked.

**Comment by Beethoven** [comment]
There's a noNextStory Event
Dispatched when there is no next story. 

But not an event that shows the bookend

https://github.com/ampproject/amphtml/blob/master/spec/amp-story-player.md#nonextstory

**Comment by pshihn** [comment]
Yep that event doesn't help really. 
I just want to see the bookend. It's part of the story document and it never shows in the player.

**Comment by Enriqe** [comment]
The bookend is being deprecated #26957

What we recommend is creating your own "bookend" and displaying that when you get the `noNextStory` event as @Beethoven suggested.
