### ISSUE TITLE
Need to implement the LGPD for the AMP

### ISSUE THREAD

**Issue by akashagrjsr** [ampproject/amphtml#31382]
## What's the issue?

We are not able to see any scripts related to the LGPD support in the AMP HTML. 

We want to implement the LGPD support in the "AMP FOR WP" plugin.  So, please add the support for the LGPD in the AMP.

**Comment by micajuine-ho** [comment]
Hi @akashagrjsr, from my understanding, the features we have added to [amp-consent](https://amp.dev/documentation/components/amp-consent/) to support other regulations (such as GDPR in EU), should also be able to support LGPD. 

If you provide more detail on the specific kind of support you need, I can help make sure that your amp-consent component is working properly.

**Comment by akashagrjsr** [comment]
Thanks for the response. As you told me that the LGDP support already added in the amp-consent, so we are starting the implementation of it. If we need any help from your end we will reopen the ticket and let you know. Currently, I am closing this ticket.
