### ISSUE TITLE
Support for "do-not-track" flag in AmpVimeo Component

### ISSUE THREAD

**Issue by frj** [ampproject/amphtml#31384]
## Describe the new feature or change to an existing feature you'd like to see

The Vimeo player used to embed Vimeo content in other websites supports a feature that allows the disabling of "tracking session data" by the Vimeo component.

For more details see the documentation for embedding Vimeo videos: https://developer.vimeo.com/api/oembed/videos

The feature is enabled by adding the dnt=1 attribute to the src url of the Vimeo players iframe.

This is a request for a feature that allows disabling tracking by Vimeo videos when using the AmpVimeo component which does not currently allow you to do so. 

Something along the lines of:

```
<amp-vimeo
  data-videoid="27246366"
  layout="responsive"
  width="500"
  height="281"
  do-not-track
></amp-vimeo>
```

## Describe alternatives you've considered

An alternative would be to duplicate the AmpVimeo component, implement this feature in that code and serve it ourselves.

**Comment by frj** [comment]
I can pick this up, i'll raise a PR.

**Comment by kristoferbaxter** [comment]
Looks like this has been addressed.
