### ISSUE TITLE
Support <amp-story-player> [amp version] on <amp-lightbox>

### ISSUE THREAD

**Issue by Beethoven** [ampproject/amphtml#31389]
Support amp-story-player [amp version] on amp-lightbox
Inside amp-lightbox the player just show the first Story

The amp-story-player doesn’t work on amp-lightbox [ just play the first story]
But works perfect on a “div lightbox”. [ show and hide an div ]

Reason to work with amp-lightbox to use back and esc button to close lightbox

[See Demo](https://webstories.page/player.html)

**Comment by swissspidy** [comment]
@Enriqe This still seems to be an issue. The player doesn't load and closing the lightbox causes JS errors. Any chance this could be prioritized?

With the latest version of the Web Stories WordPress plugin, which uses amp-story-player within amp-lightbox on AMP sites, this usage is increasingly more common.

Unfortunately we didn't spot this during development, which means this is now already in production on many sites. Thus, it would be great if it could be solved as soon as possible.

Please let me know if there's anything I can help with.

**Comment by Enriqe** [comment]
@swissspidy do you have a sample to repro in? The [sample here](https://webstories.page/player.html) seems to be working. More info with repro steps would be helpful. Thanks!

**Comment by swissspidy** [comment]
Huh, that's very strange! When I tested that sample 8 hours ago it was not working. Now it does.

Will test again...

**Comment by swissspidy** [comment]
Can confirm that this was broken in the previous release (`2104170104001`), but in the current stable release (`2104240357000`) it works again.

So, all good now! Sorry for the false alarm. This can be closed now :-)
