### ISSUE TITLE
[amp-story-player] calling `pause` on the player when the player is offscreen throws and story doesn't load properly

### ISSUE THREAD

**Issue by pshihn** [ampproject/amphtml#31392]
## What's the issue?

If you call `pause` on the player when it's still off screen, story does not load - only loads the first page. 

Likely related to https://github.com/ampproject/amphtml/issues/31333 (told to track this as a separate issue)

## How do we reproduce the issue?

Create an amp-story-player that is down the page, after a lot of content. Call pause on it when loaded. When you scroll down to the player, it only loads the first page and throws exception when navigating to next page

**Comment by Enriqe** [comment]
Thanks for the report, i'll take a look.

**Comment by Enriqe** [comment]
@pshihn we recently added an autoplay API to only play the story when desired (#32414) will this solve your use case described here?
