### ISSUE TITLE
[amp-story-player] Expose the restart story button in the player

### ISSUE THREAD

**Issue by pshihn** [ampproject/amphtml#31390]
## Describe the new feature or change to an existing feature you'd like to see

When a story is embedded in an amp-story-player, there is no way to restart it. You have to hit back a bunch of times. 
When not embedded, there's at least a restart button at the end of the story.

## Describe alternatives you've considered

I could create my own custom button, but not sure if that's feasible with the API amo-story-player exposes.

**Comment by gmajoulet** [comment]
We now expose a way to add custom buttons within a Story ([cf documentation](https://github.com/ampproject/amphtml/blob/master/spec/amp-story-player.md#customizing-position--visibility-of-story-ui-controls)). Once we expose a rewind/restart method, tracked in https://github.com/ampproject/amphtml/issues/31424, you could use both to create your own rewind/restart button.
