### ISSUE TITLE
SVG images giving 404 error

### ISSUE THREAD

**Issue by kevalteknopoint** [ampproject/amphtml#31405]
Hi,
We are facing an issue while loading the amp page from CDN. The SVG images giving 404 error while loading page from CDN, whereas it working find when amp pages load directly without google CDN
Google CDN amp page link:
https://www.google.com/amp/s/www.iffcotokio.co.in/health-insurance/amp
Normal page link:
https://www.iffcotokio.co.in/health-insurance/amp

SVG image which gives error:
Google CDN path
https://www-iffcotokio-co-in.cdn.ampproject.org/content/dam/iffcotokio/iffco-images/sprite-sheet.svg
Without Google CDN image path
https://www.iffcotokio.co.in/content/dam/iffcotokio/iffco-images/sprite-sheet.svg

Any resolution for this issue.

**Comment by honeybadgerdontcare** [comment]
@kevalteknopoint the URL used in your issue for `Google CDN path` is not a valid AMP cache URL. The documentation for [AMP Cache URL Format](https://amp.dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cache-urls/) goes into detail what a valid path is.

Given this URL:
https://www.iffcotokio.co.in/content/dam/iffcotokio/iffco-images/sprite-sheet.svg
The AMP Cache URL would be:
https://www-iffcotokio-co-in.cdn.ampproject.org/c/s/www.iffcotokio.co.in/content/dam/iffcotokio/iffco-images/sprite-sheet.svg

When the AMP Cache encounters an error with a URL it'll redirect to the origin's URL, in this case the given URL (https://www.iffcotokio.co.in/content/dam/iffcotokio/iffco-images/sprite-sheet.svg). Note that even the origin URL does not render and devtools shows several errors on the console.
