### ISSUE TITLE
Only Run Tests that actually changed when --watch

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#3141]
Currently `gulp test --watch` re-run ALL the tests in AMP making incremental test changes very difficult and requires the use of `only` blocks to get this to work properly. It'd be nice if watch was smart to only run the test files that actually changed.

**Comment by cramforce** [comment]
This would, indeed, be nice. Unfortunately it does not solve reruns triggered by non-test code changes.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please verify first whether the feature proposal is still relevant.

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
