### ISSUE TITLE
[amp-story-player] No documented way to change the story or remove a story from the player

### ISSUE THREAD

**Issue by pshihn** [ampproject/amphtml#31412]
## Describe the new feature or change to an existing feature you'd like to see

I'd like to replace the current story in the player with another one. Also when showing a set of stories, I'd like to remove one from the set. 

The docs only mention **adding** stories to the player. No mention of replacing the story or removing a story from the playlist. 

## Describe alternatives you've considered

For replacing the story, I could create a separate player, but that's just ugly.

**Comment by tarun7886** [comment]
@pshihn 
Any luck with removing the loaded stories? I too want to remove the viewed stories.

**Comment by gmajoulet** [comment]
With the new internal architecture the player has, adding a `remove(storyArray)` method should be very straightforward.

**Comment by gmajoulet** [comment]
cc @ampproject/wg-stories
