### ISSUE TITLE
[amp-story-player] When adding multiple stories to the player using anchors, it can shift the story down

### ISSUE THREAD

**Issue by pshihn** [ampproject/amphtml#31419]
See https://jsfiddle.net/t4j7z0yv/3/

Notice that the story is shifted down because the anchors have set `visibility:hidden` but they are still part of the layout.
I have drawn a border around amp-story-player to see this issue.

**Comment by newmuis** [comment]
@Enriqe can we just add `display: block; height: 0` on `amp-story-player a:not(:first-of-type)`?

**Comment by Enriqe** [comment]
Is that better than just applying `display: none;` to all `amp-story-player.i-amphtml-story-player-loaded a` ?

**Comment by newmuis** [comment]
Sorry, just saw this now.  My only concern is whether prerender would still work of the iframe is display: none.

**Comment by Enriqe** [comment]
Not sure I understand, the iframe shouldn't be affected since we are targeting the `<a>` tags.
