### ISSUE TITLE
[amp-story-player] Introduce rewindStory() API

### ISSUE THREAD

**Issue by pshihn** [ampproject/amphtml#31424]
When the story player moves to a new story, I want it to start from the first page. 

So one way that was suggested was to call `player.go(0, -9999)` when a story changes. It does not work though. 
I listen to the `navigation` event and call the `go` method but nothing happens. 

See: https://jsfiddle.net/9x327jep/9/

On the first story o the second page, click on 'Third Story' to go to another story. Let it run to page 3 of this story. 
Hit 'First Story' again and 'Third Story' again. It continues from the page it left on.

**Comment by Enriqe** [comment]
Is this something you cannot do by only using `go(delta, delta)`?

By using `go(storyDelta, -9999)` the player will know in what order to perform the actions internally.

**Comment by pshihn** [comment]
There are two scenarios. 

1) I want to go to the story of a specific URL. In this case 'show` method does not let me provide an index. I can track what index of the story matches with the URL and then compute the deltas for `go`. And as you suggested it should work in that case

2) When the user taps on the last page of a story, they navigate to the next story - which does not play from the first page. I am not the one calling `go`  in this case. 

Also, I think since you are already letting me set the page by providing a delta, It would be easy to specify a way to go to specific index.

**Comment by Enriqe** [comment]
Those are good points. Thanks for the feedback and demos @pshihn ! 

I will rephrase this feature request to introduce a `player.rewindStory()`, which when called (could be after each navigation) would rewind the story to the first page. Would that work for you?

**Comment by pshihn** [comment]
`rewindStory` will work for this case.

**Comment by edoudou** [comment]
@Enriqe Is there any advancement on this FR ? 

It should be possible to rewind a story you are not currently on, so you could rewind the story on a `navigation` event if the user have already completed it.

Maybe using `player.rewindStory(storyUrl)`.

**Comment by gmajoulet** [comment]
+1 to `rewind(storyUrl)`or to be consistent with the other methods such as `show(storyUrl)` or `prerender(storyUrl)`.

Under the hood, the story code is already written under the `replay_()` method:

https://github.com/ampproject/amphtml/blob/839bf12bd36e5ece81f8c9698cd3e377f232fc31/extensions/amp-story/1.0/amp-story.js#L2734-L2757

**Comment by pshihn** [comment]
@Enriqe When can we expect this to show up in "https://cdn.ampproject.org/amp-story-player-v0.js"?

**Comment by Enriqe** [comment]
@pshihn this should be in the `nightly` by tonight, in `beta` next Tuesday, and in `stable` the Tuesday after that (March 9th).

https://amp.dev/documentation/guides-and-tutorials/learn/spec/release-schedule/
