### ISSUE TITLE
[amp-story-player] `#ignoreLocalStorageHistory=true` does not work when showing multiple stories in a player

### ISSUE THREAD

**Issue by pshihn** [ampproject/amphtml#31423]
Say you are on page 3 of a story, and then you navigate to another story. And now if you come back to the previous story, you are still on page 3. 

Here's a demo: https://jsfiddle.net/dcyLn56w/5/
Click on `Third Story` to go to the third story, let it move to page 3 of the story. 
Click on `First Story` to go back to the first story. 
Click on `Third Story` again and you're still on page 3.

**Comment by Enriqe** [comment]
See https://github.com/ampproject/amphtml/issues/31391#issuecomment-738339153
