### ISSUE TITLE
[amp-story-player] Transitioning from one story to another affects the top page's history 

### ISSUE THREAD

**Issue by pshihn** [ampproject/amphtml#31431]
When the player transitions from one story to another, it adds a record to the top page's history. Causing the 'back' button to not work until `n+1` clicks, where `n` is the number of story transitions. 

This is because iframes affect the browser history. This could be avoided if inside the iframe, the location is changed using `location.replace()` 

This seems really bad for UX on a page that uses the amp-story-player.

**Comment by gmajoulet** [comment]
Tracked here: https://github.com/ampproject/amphtml/issues/31010
