### ISSUE TITLE
I2I: Add Analytics Vendor Black Crow AI

### ISSUE THREAD

**Issue by raymondborkowski** [ampproject/amphtml#31449]
Hi!

We'd like to add Black Crow AI to the amp-analytics vendor's list to help our customers integrating our services in their amp pages.

cc @ampproject/wg-approvers
cc @ampproject/wg-analytics

PR: https://github.com/ampproject/amphtml/pull/31451

**Comment by raymondborkowski** [comment]
https://github.com/ampproject/amphtml/pull/31451

**Comment by micajuine-ho** [comment]
Hi @raymondborkowski Thanks for your issue. Please tag the @ampproject/wg-components  when you have create a pull request with the integration and link this issue as well!

**Comment by micajuine-ho** [comment]
Closed via #31451
