### ISSUE TITLE
amp-bind is broken on IE 11

### ISSUE THREAD

**Issue by ka2jun8** [ampproject/amphtml#31466]
## What's the issue?

amp-bind (amp-state, AMP.setState) does not work on IE11.

I do not know detail reason, but I found this error about 'String.prototype.startsWIth'.

<img width="691" alt="スクリーンショット 2020-12-04 19 30 20" src="https://user-images.githubusercontent.com/12580072/101316830-9a533800-38a0-11eb-929f-4768c3213242.png">

## How do we reproduce the issue?

1. visit to [the example page of amp-bind](https://amp.dev/documentation/examples/components/amp-bind/)
2. click "Show greeting"
3. "Hello World" is not shown

## What browsers are affected?

IE11

## Which AMP version is affected?

```
ampRuntimeVersion: "012011200012001",
ltsRuntimeVersion: "012010132225003",
```

**Comment by samouri** [comment]
We have a polyfill for `String.prototype.startsWith`, but it looks like we didn't also install it for the WebWorker.
