### ISSUE TITLE
Port amp-instagram test to be hermetic

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#3146]
Use `doNotLoadExternalResourcesInTest` introduced in #3132 to avoid loading actual images/iframes in the test.

**Comment by ericlindley-g** [comment]
Putting in backlog, pending a specific target

**Comment by mkhatib** [comment]
Is it ok if we up this to the current milestone? Would love to get the tests more stable. 

Also, this would probably be useful in `amp-twitter`, `amp-brightcove`, `amp-bird-player`, `amp-dailymotion`, `amp-jwplayer`, `amp-kaltura`, `amp-reach-player`, `amp-soundcloud`, `amp-springboard-player`, `amp-vimeo`, `amp-vine`.

**Comment by ericlindley-g** [comment]
From my perspective, absolutely (moving to the 5/12 milestone now, but defer to @muxin to gauge feasibility for completing by then)

**Comment by ericlindley-g** [comment]
And defer to Eng broadly (cc @cramforce) for the right milestone on this kind of task

**Comment by cramforce** [comment]
This is @muxin's next task.

**Comment by muxin** [comment]
Created #3194 to fix similar problem in other extensions.
