### ISSUE TITLE
[amp-instagram] Placeholder not loading - The Instagram endpoint (for embed) is deprecated

### ISSUE THREAD

**Issue by Beethoven** [ampproject/amphtml#31474]
## What's the issue?
Image of placeholder not loading.
The Instagram endpoint (for embed) is deprecated, please go to https://developers.facebook.com/docs/instagram/oembed to learn how to migrate the endpoint.

The endpoints were deprecated on October 24, 2020 

## How do we reproduce the issue?
See line 123 of amp-instagram.js

**Comment by Beethoven** [comment]
@krdwan Any news?

**Comment by krdwan** [comment]
@Beethoven Thanks for the follow up, this is currently in our backlog of issues.

cc: @ampproject/wg-components if anyone has a chance to take a look

**Comment by Beethoven** [comment]
I saw here, In 1.0 there´s no image in placeholder.
And no problem in loading.
It´s ok for me.

**Comment by kristoferbaxter** [comment]
Closing for https://github.com/ampproject/amphtml/issues/32322.
