### ISSUE TITLE
amp-base-carousel not setting loop=false attribute 

### ISSUE THREAD

**Issue by micajuine-ho** [ampproject/amphtml#31488]
This issue manifests itself when a carousel does not have `loop=false` as an attribute and so should be looping (b/c default is true), but we internally reject this because looping is only valid when we have at least 3 times the amount of visible slides. So, UI attributes that depend on loop=false do no get updated even though the behavior reflects loop=false.

Can repro with `test/manual/amp-base-carousel/non-looping.amp.html` (control) vs `test/manual/amp-base-carousel/multi-visible-single-advance.amp.html` (exp)
 
Thanks @caroqliu for drawing attention to this unusual case :D

**Comment by caroqliu** [comment]
Note that the carousel should default to `loop=false` due to omission, even though the documentation says otherwise. See #28661

**Comment by micajuine-ho** [comment]
Closed via #31541
