### ISSUE TITLE
Feature request: intersection triggers for amp-analytics.

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#3149]
We'd like to be able to track if users read to the bottom of article text and what % of users go beyond that.  The current `amp-analytics` model of using scroll %'s as triggers doesn't give the needed info.  (it's not practical to know what % of the page every article represents on every screen geometry).

We'd like to be able to have intersection triggers such that we could specify a dom object and have an analytics trigger fire when it comes into or leaves the viewport.  I'd just fake this with an iframe but AMP makes this hard due to the restrictions on analytics iframes, in particular the fact they are removed automatically.

Adding this feature would also make it possible to track ad viewability independent of the iframe containing the ad.  For those using multiple ad platforms this would be very helpful.

Any chance of getting it added to `amp-analytics`?

**Comment by avimehta** [comment]
/cc @rudygalfi 

@jpettitt Does scrolled past ~90% of the page not convey similar state? I know it is not as accurate. cc'ing Rudy to figure out priority.

**Comment by jpettitt** [comment]
The 90% solution doesn't cut it.  Examples: 

https://fresnobee.relaymedia.com/amp/news/local/education/article61889207.html Text ends at 79% on an iPhone 4

https://kansascity.relaymedia.com/amp/news/local/crime/article76157292.html Text ends at 61% on an iPhone 4

What we're specifically trying to measure is do certain elements, eg particular ad unit types, form a road block to scrolling.   For example does a 320x50 give a better overall revenue per visit becasue the reader is less likely to bounce than say a 300x250 or a Taboola unit.  To do this we need fine grain scroll data.

**Comment by ericlindley-g** [comment]
Putting in the backlog for now

**Comment by avimehta** [comment]
@jpettitt While this is in the queue, I had another question: Will #1297 help with this case? It can send a ping if and when an ad comes into view and can also measure how much of it is in view. 

Currently it does not support vanilla html elements so you can't use it with the article body but i think modifying it to address this usecase would be fair.

**Comment by rudygalfi** [comment]
Yes, I think #1297 is the solution to this. As @avimehta points out, it's currently restricted to only amp-* elements, but if we provide some way to handle vanilla elements (at least in a way broad enough to handle this use case), then this is covered.

**Comment by jpettitt** [comment]
Agree, a generalized version of  #1297 would do it.   Will #1297 as designed work for an empty `amp-fit-text` (or any other null action AMP element) as that would let us do what we want with #1297 as specified.

**Comment by rudygalfi** [comment]
I think so, but we should really figure out a way to do this that doesn't require using amp-fit-text as essentially a dummy element.

**Comment by avimehta** [comment]
ack. After my last post, I thought about it a bit more and I realized it does not work in it's current state. In the current state, the spec only looks at the part of the content that is on screen. Since the content is likely larger than the screen size, the content with 100% visibility just means that it covers the screen not that **all** of the content was seen.

**Comment by jpettitt** [comment]
@avimehta or you just track that the block after came into view.

**Comment by avimehta** [comment]
@jpettitt That is correct. I think this request can be closed. Please reopen if you think otherwise or have any other questions.
