### ISSUE TITLE
🌸 Cherry-pick request for #31510 into #31501 (Approved)

### ISSUE THREAD

**Issue by micajuine-ho** [ampproject/amphtml#31516]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #31510 | #31514 |     **YES**     | **YES** | **NO** | #31501                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

Breaks amp-carousel-0.2 for carousels that want to set their own widths. 

## List the steps to manually verify the changes in this cherry-pick

Test with 
```
  <amp-carousel type="carousel" layout="responsive" height="3" width="4">
    <div>Tag 1</div>
    <div>Tag 2</div>
    <div>Long Tag 3</div>
    <div>Tag 4</div>
    <div>Tag 5</div>
    <div>Tag 6</div>
    <div>Tag 7</div>
    <div>Tag 8</div>
  </amp-carousel>
```

and verify that the each div does not take up the whole screen width.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

Change impacted publishers custom styling to carousel slides.

## Impact

- <_Which users were affected? Roughly how many?_>
- <_How were users affected? E.g. partial or complete loss of functionality?_>

## Action Items

- #<_ISSUE_NUMBER_>: <_Add unit/integration/end-to-end test_>
- #<_ISSUE_NUMBER_>: <_Add monitoring for edge case via error logging_>
- #<_ISSUE_NUMBER_>: <_Refactor an easily misused API_>

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by dvoytenko** [comment]
Is this just a clean rollback?

**Comment by micajuine-ho** [comment]
Yes

**Comment by dvoytenko** [comment]
Approved

**Comment by estherkim** [comment]
Stable and Beta (opt-in) have been CP'ed.
