### ISSUE TITLE
amp-carousel styles is overriding my styles

### ISSUE THREAD

**Issue by HelaGone** [ampproject/amphtml#31510]
## What's the issue?
The styles that were added to the amp-component 13 days ago are overriding my styles and therefore messing up my entire layout. 

here is the link to the [commit](https://github.com/ampproject/amphtml/commit/85b486ea4083978ec74313693c7ce04956a845c7#diff-39fcba39875a34d4f1945a1915ec64616e400d5ad57813ffc48f5dc6b3397420)

Briefly describe the bug.
When using amp-carousel with type carousel the image takes the entire width of the carousel no matter if I gave it a defined width by adding styles to the slides by its class `.amp-carousel-slide` as shown in the documentation. 

The problem is on the line 30 on the file `extensions/amp-carousel/0.2/amp-carousel.css` wich introduces a `width:100%!important;`. 

This commit `85b486ea4083978ec74313693c7ce04956a845c7` is where the bug was introduced.

## How do we reproduce the issue?
1. Visit my site at https://codigoespagueti.com/ and scroll down to RESEÑAS section and inspect one of the slides (`amp-scrollable-carousel-slide`) on the `amp-carousel` 
2. Go to the computed tab in dev tools and search for `width`
3. click on the little arrow next to the width in pixels (1280px). This action shold take you to the actual class that is setting the width for each slide on the carousel. 
4. Turn off the width declaration by pressing the little check mark and see how the slides on the carousel takes the specified width declared by my styles. 

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

https://codigoespagueti.com/

1. Visit my site at https://codigoespagueti.com/ and scroll down to RESEÑAS section and inspect one of the slides (`amp-scrollable-carousel-slide`) on the `amp-carousel` 
2. Go to the computed tab in dev tools and search for `width`
3. click on the little arrow next to the width in pixels (1280px). This action shold take you to the actual class that is setting the width for each slide on the carrousel. 
4. Turn off the width declaration by pressing the little check mark and see how the slides on the carousel takes the specified width declared by my styles. 

## What browsers are affected?
All of them and all devices

## Which AMP version is affected?
0.2 

Is this a new issue? Or was it always broken? Paste the version of AMP where you saw this issue. (You can find the version printed in your browser's console.)
<img width="1515" alt="Screen Shot 2020-12-08 at 18 54 21" src="https://user-images.githubusercontent.com/5982932/101559541-f2fd0080-3986-11eb-84af-cca2078d8f6c.png">
<img width="313" alt="Screen Shot 2020-12-08 at 18 54 38" src="https://user-images.githubusercontent.com/5982932/101559549-f5f7f100-3986-11eb-81ee-5ee05e54140d.png">
<img width="237" alt="Screen Shot 2020-12-08 at 18 54 53" src="https://user-images.githubusercontent.com/5982932/101559550-f6908780-3986-11eb-9c69-35180243daef.png">
<img width="1383" alt="Screen Shot 2020-12-08 at 18 54 59" src="https://user-images.githubusercontent.com/5982932/101559551-f6908780-3986-11eb-85c2-d7ee2afc2edc.png">

The issue started today, not only in this site bus in several of my websites

**Comment by dritter** [comment]
We have the same issue. [Here is a reproducer in the amp playground](https://playground.amp.dev/#share=PCFkb2N0eXBlIGh0bWw+CjxodG1sIOKaoT4KPGhlYWQ+CiAgPG1ldGEgY2hhcnNldD0idXRmLTgiPgogIDx0aXRsZT5NeSBBTVAgUGFnZTwvdGl0bGU+CiAgPGxpbmsgcmVsPSJjYW5vbmljYWwiIGhyZWY9InNlbGYuaHRtbCIgLz4KICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLG1pbmltdW0tc2NhbGU9MSxpbml0aWFsLXNjYWxlPTEiPgogIDxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoOy1tb3otYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1zLWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoO2FuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RofUAtd2Via2l0LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1vei1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1tcy1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1vLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1Aa2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fTwvc3R5bGU+PG5vc2NyaXB0PjxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjpub25lOy1tb3otYW5pbWF0aW9uOm5vbmU7LW1zLWFuaW1hdGlvbjpub25lO2FuaW1hdGlvbjpub25lfTwvc3R5bGU+PC9ub3NjcmlwdD4KICA8c2NyaXB0IGFzeW5jIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAuanMiPjwvc2NyaXB0PgogIDxzY3JpcHQgYXN5bmMgY3VzdG9tLWVsZW1lbnQ9ImFtcC1jYXJvdXNlbCIgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC9hbXAtY2Fyb3VzZWwtMC4yLmpzIj48L3NjcmlwdD4KICA8c3R5bGUgYW1wLWN1c3RvbT4KICAgIGgxIHsKICAgICAgbWFyZ2luOiAxcmVtOwogICAgfQogIDwvc3R5bGU+CjwvaGVhZD4KPGJvZHk+CiAgPGgxPkhlbGxvIEFNUEhUTUwgV29ybGQhPC9oMT4KICA8YW1wLWNhcm91c2VsIHR5cGU9ImNhcm91c2VsIiBsYXlvdXQ9InJlc3BvbnNpdmUiIGhlaWdodD0iMyIgd2lkdGg9IjQiPgogICAgPGRpdj4KICAgICAgPGFtcC1pbWcKICBzcmM9Imh0dHBzOi8vcGxhY2Vob2xkLml0LzEwMHgzMDAiCiAgd2lkdGg9IjEwMCIKICBoZWlnaHQ9IjMwMCIKICBsYXlvdXQ9ImZpeGVkIgo+CjwvYW1wLWltZz4KICAgIDwvZGl2PgogICAgPGRpdj4KICAgICAgPGFtcC1pbWcKICBzcmM9Imh0dHBzOi8vcGxhY2Vob2xkLml0LzEwMHgzMDAiCiAgd2lkdGg9IjEwMCIKICBoZWlnaHQ9IjMwMCIKICBsYXlvdXQ9ImZpeGVkIgo+CjwvYW1wLWltZz4KICAgIDwvZGl2PgogICAgPGRpdj4KICAgICAgPGFtcC1pbWcKICBzcmM9Imh0dHBzOi8vcGxhY2Vob2xkLml0LzEwMHgzMDAiCiAgd2lkdGg9IjEwMCIKICBoZWlnaHQ9IjMwMCIKICBsYXlvdXQ9ImZpeGVkIgo+CjwvYW1wLWltZz4KICAgIDwvZGl2PgogICAgPGRpdj4KICAgICAgPGFtcC1pbWcKICBzcmM9Imh0dHBzOi8vcGxhY2Vob2xkLml0LzEwMHgzMDAiCiAgd2lkdGg9IjEwMCIKICBoZWlnaHQ9IjMwMCIKICBsYXlvdXQ9ImZpeGVkIgo+CjwvYW1wLWltZz4KICAgIDwvZGl2PgogICAgCiAgPC9hbXAtY2Fyb3VzZWw+CjwvYm9keT4KPC9odG1sPgo=).
This happens with the amp-carousel 0.2, but not with 0.1. The affected AMP-Version is 2011252111001.

We found a workaround by using `max-width`.

**Comment by HelaGone** [comment]
Thanks I'll try that. But it feels like that width at 100% is wrong. Idunno..

**Comment by betosg** [comment]
Hi guys, I've seen that the issue is closed but i'm still having this problem using amp-carousel 0.2...

**Comment by dritter** [comment]
@betosg The Cherry-Pick is still in process. See https://github.com/ampproject/amphtml/issues/31516

**Comment by micajuine-ho** [comment]
Thanks for your patience guys. The CP got approved and we are cutting a new release now.
