### ISSUE TITLE
I2I: Top sticky ads

### ISSUE THREAD

**Issue by powerivq** [ampproject/amphtml#31513]
## Summary

Following https://github.com/ampproject/amphtml/issues/30659, this issue is used to track the visual design elements of a top-sticky ads.

## Design document

Similar to the existing sticky ad, the tag scheme will be:

```
<amp-ad width=300 height=50
        sticky=top
        type="_ping_"
        data-url='https://lh3.googleusercontent.com/pSECrJ82R7-AqeBCOEPGPM9iG9OEIQ_QXcbubWIOdkY=w400-h300-no-n'
        data-valid='true'
        data-ad-width=300
        data-ad-height=50>
    </amp-ad>
```

The ad unit will stick to the top when `sticky=top` is set.

Top sticky ads has one unique problem: it could block the content it overlaps on top. Therefore, we propose the following solution:

1. Page loads
2. When scrolling occurs, the top sticky ads loads (similar to bottom sticky ads)
3. Once scrolling back to 50px from top of page, set body element's padding-top to the height of the sticky ad unit (if the sticky ad unit is still expanded)

## Motivation

Today, we have amp-sticky-ad supporting bottom-sticky ads (https://amp.dev/documentation/components/amp-sticky-ad/). We also want to support ads sticky to the top of the page.

Top sticky ad is sought after by a few publisher advocate groups and is desirable because it is less likely to have invalid clicks, compared to bottom sticky ads. 

Limitations: same as bottom sticky ads. In addition, there cannot be both bottom and top sticky ads on the same page. Only one will prevail.

## Launch tracker

/cc @ampproject/wg-approvers

**Comment by cramforce** [comment]
My recollection of the research is that top-sticky ads are preferred by users on desktop while bottom is preferred on mobile.

Should the availability of the position be a function of screen resolution?

**Comment by lannka** [comment]
According to the research from betterads.org, top sticky is actually preferred over bottom sticky on mobile phone, . @cramforce which research were you referring to?

![image](https://user-images.githubusercontent.com/8496897/101663825-ff716f80-39ff-11eb-9fb4-f66370b8767f.png)

**Comment by cramforce** [comment]
This research. I might have misremembered. Go on then 👍

**Comment by powerivq** [comment]
![Screen Shot 2021-05-17 at 8 29 33 AM](https://user-images.githubusercontent.com/1321403/118515358-e667aa00-b767-11eb-9659-e5ecc1c29e79.jpg)

This is the profiling results. Performance does not seem like the biggest issue, however, there still is CLS. DevTools still count it as a CLS. I can see two ways forward:

1. Accept the CLS and continue on adjusting padding top;
2. Do not adjust the padding top, so there is no CLS violation and leave it upon the publisher to leave enough space for its content on top not to be covered by the top sticky ad.

Given that 
1. this is a new format, and the publisher has the option of changing its css when implementing the feature;
2. Cross browser uncertainty for trying to adjust the padding top for the publisher;
I am now leaning towards option 2. @kristoferbaxter @jridgewell

**Comment by powerivq** [comment]
The alternative option is to hide (or close) the top sticky ad when scrolled back to the top of the page. It avoids overlapping with the content on top while not causing CLS.

**Comment by jridgewell** [comment]
That sounds OK with me.

**Comment by powerivq** [comment]
![Screen Shot 2021-06-08 at 2 54 25 AM](https://user-images.githubusercontent.com/1321403/121165207-ac7b5680-c882-11eb-8878-a58914fdbf97.jpg)

Attached the profiling from a Nokia device. The long tasks appear to be the ads itself, not the sticky ad framework.
