### ISSUE TITLE
Don't show "loading" animation if resource doesn't exist

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#3153]
Feature Request : Don't show the "loading" animation if AMP knows that a resource doesn't exist and will never load. See below.
![loading](https://cloud.githubusercontent.com/assets/2366341/15099740/18f6ca0c-152c-11e6-994e-6b0e746084de.png)
The above image was found on [TechCrunch](http://techcrunch.com/2010/10/20/a-compact-death/amp/
).
Instead, consider showing some delightful placeholder content.

**Comment by erwinmombay** [comment]
possibly related to https://github.com/ampproject/amphtml/issues/2585

@jasti just want to confirm the image never loads cause theres an error fetching it right? (doesnt exist on server, network issue etc)

**Comment by jasti** [comment]
@erwinmombay yes, perfect. Closing.
