### ISSUE TITLE
Enhancement: Allow non https content delived from same origin

### ISSUE THREAD

**Issue by rodryquintero** [ampproject/amphtml#3154]
I am trying to include some content using `<iframe-amp>` from the same web server I am serving my content but I do not have SSL enabled, and probably won't be able to use it.

I am requesting that you allow non SSL content when it is delivered from the same origin/site using `<ifram-amp>`

For example:

```
<amp-iframe width=300 height=300
    sandbox="allow-scripts allow-same-origin"
    layout="responsive"
    frameborder="0"
    src="iframe-content.html">
</amp-iframe>
```

**Comment by dvoytenko** [comment]
@rodryquintero The intent behind requiring https is to ensure that the document can be proxied and embedded in most of typical embedding scenarios. Relaxing this rule will create a problem: it will make document functional in one cases, but not in most of others where "https" will be required. Thus we can't relax it here.

If you are looking to simplify testing - we currently allow `http://localhost` origins for testing.

(I'll close the bug, but please feel free to re-open if you have more questions)
