### ISSUE TITLE
Adding support for Google Analytics's Core Web Vitals `amp-web-vitals`

### ISSUE THREAD

**Issue by MrCsabaToth** [ampproject/amphtml#31557]
## Describe the new feature or change to an existing feature you'd like to see

There's a lot of buzz happening about Core Web Vitals these days (for example Chrome Dev Summit). Google added Core Web Vitals support to Analytics, it'd require adding JS parts to my AMP site: https://github.com/GoogleChrome/web-vitals/
I'd be great to have an `amp-web-vitals` or `amp-ga-web-vitals` or similar AMP component. Preferably some zero configuration (other than the GTM tag) defaults.

## Describe alternatives you've considered

Haven't considered alternatives yet. Since I'm hosting with CloudFlare (AMP Real URL) and they also have Core Web Vitals support, so if they had their own AMP Core Web Vitals solution I'd consider that. In AMP land my hands are tied, although for a while we can introduce limited amounts of custom JS. But a native AMP component would be the best.

**Comment by kristoferbaxter** [comment]
The three core metrics for Core Web Vitals are made available via `amp-analytics`. @micajuine-ho will followup with an example.

**Comment by micajuine-ho** [comment]
Hi @MrCsabaToth, thanks for your bug report. You can use [`amp-analytics`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md) to track the 3 Core Web Vital metrics and send them to your server endpoint.

The three CWV are: 
- ${cumulativeLayoutShift}
- ${firstInputDelay}
- ${largestContentfulPaint}

These [macros](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#performance) are available in amp-analytics:
```
<amp-analytics>
  <script type="application/json">
    {
        "requests": {
          "endpoint": "https://myEndpoint.com/analytics?"
        },
        "triggers": {
            "pageview": {
                "on": "visible",
                "request": "endpoint"
            }
        },
        "extraUrlParams": {
            "lcp": "${largestContentfulPaint}",
            "cls": "${cumulativeLayoutShift}",
            "fid": "${firstInputDelay}"
        },
        "transport": {
          "beacon": false,
          "xhrpost": false,
          "image": true
        }
      }
  </script>
</amp-analytics>
```

In this example, amp-analytics will send the request to your endpoint with the CWV attached as URL parameters, when the page is first visible. 

Please let me know if this satisfies your need.

**Comment by kristoferbaxter** [comment]
Closing this issue as an example was added to `amp.dev` and provided here in the issue.

**Comment by micajuine-ho** [comment]
Link to `amp.dev` PR: https://github.com/ampproject/amp.dev/pull/5268

**Comment by MrCsabaToth** [comment]
> ```
> endpoint
> ```

What should I set the `endpoint` to if I'd like to see these CWVs in Google Analytics and the Google Search Console Page Insights / CWV?

**Comment by micajuine-ho** [comment]
You can set it to `event` https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/vendors/googleanalytics.json#L15

**Comment by MrCsabaToth** [comment]
> You can set it to `event` https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/vendors/googleanalytics.json#L15

Thanks for the pointer. If my site is a static blog would I need that whole JSON, or is there anything I can cut off in your opinion? Thanks again.

**Comment by micajuine-ho** [comment]
Have you seen this: https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md#integrated-analytics-vendors?

You should integrate with GA by utilizing their vendor json via `type='googleanalytics'`

**Comment by MrCsabaToth** [comment]
> Have you seen this: https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md#integrated-analytics-vendors?
> 
> You should integrate with GA by utilizing their vendor json via `type='googleanalytics'`

Originally I followed this guide: https://developers.google.com/analytics/devguides/collection/amp-analytics
so right now I use `type='gtag'`. (https://gitlab.com/MrCsabaToth/mrcsabatoth.gitlab.io/-/blob/master/_layouts/default.html#L10)

```
    <amp-analytics data-block-on-consent type="gtag" data-credentials="include">
      <script type="application/json">
        {
          "vars" : {
            "gtag_id": "{{ site.ga }}",
            "config" : {
              "{{ site.ga }}": { "groups": "default" }
            }
          }
        }
      </script>
    </amp-analytics>
```

Currently my JSON is https://gitlab.com/MrCsabaToth/mrcsabatoth.gitlab.io/-/blob/master/_includes/analytics.json
```
{
  "vars": {
    "account": "{{ site.ga }}"
  },
  "triggers": {
    "trackPageview": {
      "on": "visible",
      "request": "pageview"
    }
  }
}
```

On top of that my GA property is old enough to be an UA. I suspect I'd need upgrade GA4?

**Comment by micajuine-ho** [comment]
Ah my mistake, I thought you were using `type='googleanalytics'` and not gtag. In this case you can use event `uaEvent` from https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/vendors/gtag.json#L33 that gets pulled in.

**Comment by MrCsabaToth** [comment]
> > Have you seen this: https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md#integrated-analytics-vendors?
> > You should integrate with GA by utilizing their vendor json via `type='googleanalytics'`
> 
> Originally I followed this guide: https://developers.google.com/analytics/devguides/collection/amp-analytics
> so right now I use `type='gtag'`. (https://gitlab.com/MrCsabaToth/mrcsabatoth.gitlab.io/-/blob/master/_layouts/default.html#L10)
> ...
> 
> Currently my JSON is https://gitlab.com/MrCsabaToth/mrcsabatoth.gitlab.io/-/blob/master/_includes/analytics.json
> ...
> 
> On top of that my GA property is old enough to be an UA. I suspect I'd need upgrade GA4?

Sorry, the `analytics.json` above is not used right now, it didn't work when I plugged it in and the https://developers.google.com/analytics/devguides/collection/amp-analytics also pointed to `gtag` instead. BTW the Google Analytics section under https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/configure-analytics/analytics-vendors/?format=websites right above GTAG also refers to https://developers.google.com/analytics/devguides/collection/amp-analytics which in turn shows `gtag`. My use-case is quite basic: I have a static blog site and I have a GA property and I'd want a basic JSON which captures page views + the CWV measurements.

**Comment by MrCsabaToth** [comment]
> Ah my mistake, I thought you were using `type='googleanalytics'` and not gtag. In this case you can use event `uaEvent` from https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/vendors/gtag.json#L33 that gets pulled in.

Interesting. I only set up GTAG because of https://developers.google.com/analytics/devguides/collection/amp-analytics and it was bumpy because my GTAG workspace wasn't live and it wasn't straight forward anywhere that was the reason I didn't receive data. I'd be happy to forget tag manager since my setup is super simple. However those JSONs you linked look quite extensive, I'll study them a little further. All I need is the page views and CWV (the latter is only nice to have).
