### ISSUE TITLE
[amp-story-player] Improve pre-rendering scenarios

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#31560]
Following up from #31305

* We should be able to further optimize by only pre-render the first story **only if** the player is not hidden (this will highly benefit use cases like carousels).

* Avoid pre-render if player is below the viewport (but close enough to trigger a pre-render w/ current logic) if user hasn't scrolled yet. We think this could help by reducing LCP.

/cc @ampproject/wg-stories

**Comment by gmajoulet** [comment]
> We should be able to further optimize by only pre-render the first story only if the player is not hidden (this will highly benefit use cases like carousels).

This will be so hard to enforce, we will likely get it wrong, eg: `opacity: 0`, `visibility: hidden`, or `transform: scale(0)`. Instead, we should tell publishers who want to control the prerendering experience to use the `add()` API and not add any <a> links in the `<amp-story-player>` tag. We should expose a `prerender` method so they can fully control what and how many stories they want to prerender.

**Comment by Enriqe** [comment]
Closed by #32341
