### ISSUE TITLE
What's the recommended setup with COOP and COEP with AMP-HTML

### ISSUE THREAD

**Issue by ayumi-cloud** [ampproject/amphtml#31579]
Testing out COOP and COEP and see the following error in dev-tools:

![image](https://user-images.githubusercontent.com/57409060/102018383-e00e7580-3d64-11eb-9b6e-d9b525da343c.png)

All the other extensions work fine except these two.

Have done some searching and can't find any documentation with setting up COOP and/or COEP with AMP-HTML.

More info: https://web.dev/coop-coep/

**Comment by jridgewell** [comment]
This should be a very easy fix on our end. We design all of these scripts to be embedded anywhere, so we can use the permissive `CORP: cross-origin` response header.

**Comment by jridgewell** [comment]
The change has been made on our servers, and I now see `cross-origin-resource-policy: cross-origin` on all of our JS responses.
