### ISSUE TITLE
[amp-story-player] Fire an event when a link in the story is clicked

### ISSUE THREAD

**Issue by pshihn** [ampproject/amphtml#31599]
## Describe the new feature or change to an existing feature you'd like to see

I'd like to get notified when a link or call to action inside the story player is clicked/tapped. This could be used for tracking and performing other side effects. 

## Describe alternatives you've considered

None

**Comment by gmajoulet** [comment]
Please use amp-analytics for any tracking: https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/amp-story-analytics.md#tooltip-focus-trigger-on-story-focus
