### ISSUE TITLE
Amp-analytics type="krux" issue

### ISSUE THREAD

**Issue by enzo-giancola** [ampproject/amphtml#3160]
Hi,

we have a strange behaviour with amp-analytics type="krux".

Let me explain:

1)
For examples, the following URL:

http://www.repubblica.it/politica/2016/05/04/news/renzi_-139044411/amp#development=1

has the following tag:

```
<amp-analytics type="krux" config="https://cdn.krxd.net/controltag/amp/JW5KTbNq.json">
<script type="application/json">
{
    "extraUrlParams": {
        "page.pagetype": "dettaglio_content",
        "page.wt_logged_service": "repubblica.it",
        "page.keywords": "Rtl;Matteo Renzi;simone uggetti",
        "page.pubday": "04",
        "page.pubmonth": "05",
        "page.pubyear": "2016",
        "page.wt_map_tree": "\/repubblica\/politica",
        "page.wt_map_tree1": "repubblica",
        "page.wt_map_tree2": "politica"
    }
}
</script>
</amp-analytics>
```

2)
When the content is delivered by Google, the URL is:

https://cdn.ampproject.org/c/www.repubblica.it/politica/2016/05/04/news/renzi_-139044411/amp#development=1

the browser's console shows the following error messages:

- Fetch API cannot load https://cdn.krxd.net/controltag/amp/JW5KTbNq.json?__amp_source_origin=http%3A%2F%2Fwww.repubblica.it. The 'Access-Control-Allow-Origin' header has a value 'http://www.repubblica.it' that is not equal to the supplied origin. Origin 'https://cdn.ampproject.org' is therefore not allowed access. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

- log.js:133 1156 "[AmpAnalytics AMP_23]" "Error loading remote config: " "https://cdn.krxd.net/controltag/amp/JW5KTbNq.json" Error: Fetch failed https://cdn.krxd.net/controltag/amp/JW5KTbNq.json?__amp_source_origin=http%3A%2F%2Fwww.repubblica.it: Failed to fetch​​​(…)n.msg_ @ log.js:133n.error @ log.js:187(anonymous function) @ amp-analytics.js:205

- log.js:133 1180 "[AmpAnalytics AMP_23]" "No triggers were found in the config. No analytics data will be sent."

3)
Here you are the request done to Krux:
https://cdn.krxd.net/controltag/amp/JW5KTbNq.json?__amp_source_origin=http%3A%2F%2Fwww.repubblica.it

Response Headers:

Access-Control-Allow-Origin:http://www.repubblica.it
Access-Control-Expose-Headers:AMP-Access-Control-Allow-Source-Origin
AMP-Access-Control-Allow-Source-Origin:http://www.repubblica.it

Request Headers:

Origin:https://cdn.ampproject.org
Referer:https://cdn.ampproject.org/c/www.repubblica.it/politica/2016/05/04/news/renzi_-139044411/amp

Query String Parameters:

__amp_source_origin:http://www.repubblica.it

4)
The 'Access-Control-Allow-Origin' header has a value 'http://www.repubblica.it' that is not equal to the supplied origin.

5)
Due to this error we aren't tracking on Krux the usage of AMP pages. 

Wath do you suggest to solve the issue?

Best Regards,
Enzo Giancola

**Comment by dvoytenko** [comment]
@enzo-giancola Based on CORS spec, the `Access-Control-Allow-Origin` has to echo back the requests's `Origin` header (if it allows it, of course). Instead it returns back `Access-Control-Allow-Origin:http://www.repubblica.it`, which is rather strange.

/to @rudygalfi Could you please reach to Krux to get this fixed?

**Comment by rudygalfi** [comment]
cc @sethyates could you take a look?

**Comment by sethyates** [comment]
Looking

**Comment by sethyates** [comment]
@enzo-giancola this should be fixed now on the server side.  Can you please try again?

**Comment by sethyates** [comment]
```
$ curl -v -H 'Origin: http://cdn.ampproject.org/' https://cdn.krxd.net/controltag/amp/JW5KTbNq.json\?__amp_source_origin\=http%3A%2F%2Fwww.repubblica.it
*   Trying 103.245.222.175...
* Connected to cdn.krxd.net (103.245.222.175) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.c.ssl.fastly.net
* Server certificate: GlobalSign CloudSSL CA - SHA256 - G3
* Server certificate: GlobalSign Root CA
> GET /controltag/amp/JW5KTbNq.json?__amp_source_origin=http%3A%2F%2Fwww.repubblica.it HTTP/1.1
> Host: cdn.krxd.net
> User-Agent: curl/7.43.0
> Accept: */*
> Origin: http://cdn.ampproject.org/
>
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: http://cdn.ampproject.org/
< Access-Control-Expose-Headers: AMP-Access-Control-Allow-Source-Origin
< AMP-Access-Control-Allow-Source-Origin: http://www.repubblica.it
< Cache-Control: public, max-age=1200
< Content-Type: application/json; charset=utf-8
< X-Age: 0
< X-Config-Source: current
< X-Request-Backend: krux_scala_config_webservice
< X-Response-Time: 15
< X-CDN-Backend: 4FrRTvEr9h480D4BywjehZ--F_Config_Service_V3
< Via: 1.1 varnish
< Fastly-Debug-Digest: b4502d7b3abdca49f1b27faa0a7f9cf809ff83984bc3077a3684b3ab367e9c42
< X-Do-Esi: esi
< Content-Length: 454
< Accept-Ranges: bytes
< Date: Wed, 11 May 2016 01:46:07 GMT
< Via: 1.1 varnish
< Age: 0
< Connection: keep-alive
< X-Served-By: config-service-a003.krxd.net, cache-iad2138-IAD, cache-mel6523-MEL
< X-Cache: MISS, MISS, MISS
< X-Cache-Hits: 0, 0, 0
< Vary: Origin, Accept-Encoding
```

**Comment by enzo-giancola** [comment]
Hi,

the issue is fixed, for examples:

1)
https://cdn.krxd.net/controltag/amp/JW5KTbNq.json?__amp_source_origin=http%3A%2F%2Filcentro.gelocal.it

Request URL:
        https://cdn.krxd.net/controltag/amp/JW5KTbNq.json?__amp_source_origin=http%3A%2F%2Filcentro.gelocal.it
        Request Method:
        GET
        Status Code:
        200 OK
        Remote Address:
        185.31.17.175:443
Response Headers
        Accept-Ranges:
        bytes
        Access-Control-Allow-Origin:
        https://cdn.ampproject.org
        Access-Control-Expose-Headers:
        AMP-Access-Control-Allow-Source-Origin
        Age:
        123
        AMP-Access-Control-Allow-Source-Origin:
        http://ilcentro.gelocal.it
        Cache-Control:
        public, max-age=1200
        Connection:
        keep-alive
        Content-Encoding:
        gzip
        Content-Length:
        282
        Content-Type:
        application/json; charset=utf-8
        Date:
        Wed, 11 May 2016 07:26:37 GMT
        Fastly-Debug-Digest:
        21b299902dbc557e39a9fd5fa8bd047111909c7a34005e82d9be1b4abfd335cd
        Vary:
        Origin,Accept-Encoding
        Via:
        1.1 varnish
        Via:
        1.1 varnish
        X-Age:
        0
        X-Cache:
        MISS, MISS, HIT
        X-Cache-Hits:
        0, 0, 1
        X-CDN-Backend:
        4FrRTvEr9h480D4BywjehZ--F_Config_Service_V3
        X-Config-Source:
        current
        X-Do-Esi:
        esi
        X-Request-Backend:
        krux_scala_config_webservice
        X-Response-Time:
        0
        X-Served-By:
        config-service-a005.krxd.net, cache-iad2131-IAD, cache-fra1245-FRA
Request Headers
        accept:
        application/json
        Accept-Encoding:
        gzip, deflate, sdch
        Accept-Language:
        it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4
        Connection:
        keep-alive
        Host:
        cdn.krxd.net
        Origin:
        https://cdn.ampproject.org
        Referer:
        https://cdn.ampproject.org/v/ilcentro.gelocal.it/regione/2016/05/11/news/l-abruzzo-cresce-il-lavoro-no-1.13453388/amp/?amp_js_v=5
        User-Agent:
        Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1
Query String Parameters
        __amp_source_origin:
        http://ilcentro.gelocal.it


2)
https://cdn.krxd.net/controltag/amp/JW5KTbNq.json?__amp_source_origin=http%3A%2F%2Fwww.repubblica.it

Request URL:
        https://cdn.krxd.net/controltag/amp/JW5KTbNq.json?__amp_source_origin=http%3A%2F%2Fwww.repubblica.it
        Request Method:
        GET
        Status Code:
        200 OK
        Remote Address:
        185.31.17.175:443
Response Headers
        Accept-Ranges:
        bytes
        Access-Control-Allow-Origin:
        https://cdn.ampproject.org
        Access-Control-Expose-Headers:
        AMP-Access-Control-Allow-Source-Origin
        Age:
        1113
        AMP-Access-Control-Allow-Source-Origin:
        http://www.repubblica.it
        Cache-Control:
        public, max-age=1200
        Connection:
        keep-alive
        Content-Encoding:
        gzip
        Content-Length:
        282
        Content-Type:
        application/json; charset=utf-8
        Date:
        Wed, 11 May 2016 07:23:08 GMT
        Fastly-Debug-Digest:
        b4502d7b3abdca49f1b27faa0a7f9cf809ff83984bc3077a3684b3ab367e9c42
        Vary:
        Origin,Accept-Encoding
        Via:
        1.1 varnish
        Via:
        1.1 varnish
        X-Age:
        0
        X-Cache:
        MISS, MISS, HIT
        X-Cache-Hits:
        0, 0, 5
        X-CDN-Backend:
        4FrRTvEr9h480D4BywjehZ--F_Config_Service_V3
        X-Config-Source:
        current
        X-Do-Esi:
        esi
        X-Request-Backend:
        krux_scala_config_webservice
        X-Response-Time:
        1
        X-Served-By:
        config-service-a005.krxd.net, cache-iad2124-IAD, cache-fra1245-FRA
Request Headers
        accept:
        application/json
        Accept-Encoding:
        gzip, deflate, sdch
        Accept-Language:
        it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4
        Connection:
        keep-alive
        Host:
        cdn.krxd.net
        Origin:
        https://cdn.ampproject.org
        Referer:
        https://cdn.ampproject.org/v/www.repubblica.it/politica/2016/05/11/news/matteo_renzi_la_sinistra_e_l_europa_immaginata_da_francesco-139542308/amp/?amp_js_v=5
        User-Agent:
        Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1
Query String Parameters
        __amp_source_origin:
        http://www.repubblica.it


Best Regards,
Enzo
