### ISSUE TITLE
Research popular App Custom Protocols that should be whitelisted in AMP

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#3165]
Cureently we only support a bunch of Protocols (whatsapp and viber), we're adding Instagram and Snapchat. But we'd like to have a large enough coverage of what publishers are already using to whitelist in both anchors and amp-social-share

**Comment by mkhatib** [comment]
This could be a useful link to look at some of the app protocols http://www.mrlacey.com/2014/03/1192-windows-phone-apps-that-have.html?m=1

**Comment by startef** [comment]
I would like to add threema to the whitelist regarding custom protocols. Reference: https://github.com/ampproject/amphtml/issues/3727

**Comment by Gregable** [comment]
When selecting the current list, I looked at a large sample of amp docs to find what was being used in amp links in the wild and basically whitelisted everything. So, in some ways, this was already done.

I didn't see `threema:` in use at that time. I have no problem adding anything that we see usage for in amp documents, but it's not scalable to add every protocol imaginable either. The reason for whitelist, btw, is a risk that a browser natively implements a new protocol later which introduces a security risk, something equivalent to `javascript:`or `vbscript:`
