### ISSUE TITLE
🌸 Cherry-pick request for #31580 into #31617 (Pending)

### ISSUE THREAD

**Issue by micajuine-ho** [ampproject/amphtml#31701]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #31580 | #31708|     **YES**     | **YES** | **YES** | #31617                                                             |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

Publisher are unable to collect consent from users (for pages served in a viewer, when user scrolls before consent prompt loads), and the page is blocked. 

## Why is an LTS cherry-pick needed?

LTS (2012112254000) has this issue as well. This issue might be affecting pubs rely on LTS. 

## List the steps to manually verify the changes in this cherry-pick

![image](https://user-images.githubusercontent.com/30711678/102913154-377ea680-4433-11eb-8800-35203f86a387.png)

Visit https://www.google.com/amp/s/www.dailymail.co.uk/tvshowbiz/article-9003291/amp/Madonna-gives-fans-rare-look-six-children-family-holiday-photos.html

Load page on a EU geo in incognito mode (or normally, without having consented; clear storage after consenting)
Start scrolling up and down as soon as possible and keep doing so until the amp-consent overlay blocks the screen

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

<_1-2 sentences summarizing the problem and root causes._>

## Impact

- <_Which users were affected? Roughly how many?_>
- <_How were users affected? E.g. partial or complete loss of functionality?_>

## Action Items

- #<_ISSUE_NUMBER_>: <_Add unit/integration/end-to-end test_>
- #<_ISSUE_NUMBER_>: <_Add monitoring for edge case via error logging_>
- #<_ISSUE_NUMBER_>: <_Refactor an easily misused API_>

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by lannka** [comment]
> the page is blocked

Does that mean the user cannot read? Seems a severe issue that requires a prod cherrypick if so.

**Comment by micajuine-ho** [comment]
> Does that mean the user cannot read?

Yes, the user can't read b/c the page is scroll locked.

**Comment by lannka** [comment]
Discussed with @micajuine-ho  offline, I suggest we get this cherrypicked to prod today.

Steps:
1. the current fix relies on an existing CSS class and the use of CSS var. A cleaner fix will be introducing a new css class. @micajuine-ho will get a new fix PR.
2. we can cherrypick it into opt-in and immediately verify the new fix.
3. we then promote the fix to prod. hopefully by today, which leaves us one more day before holiday.
4. The current RC (beta) is in a bit weird state after the ads bisection. To not introduce further confusion, we should just trash the current RC. The next release eng should be notified.

**Comment by dvoytenko** [comment]
approved

**Comment by lannka** [comment]
@micajuine-ho is the bug in LTS? I saw the issue has issue label "LTS" but not in the issue description.

**Comment by morsssss** [comment]
Just wanted to note the misspelling in `--i-amphtml-consent-iframe-tranform`...

**Comment by micajuine-ho** [comment]
@lannka Yes, just confirmed that it is in LTS. Should we also cherry pick to LTS?

**Comment by lannka** [comment]
yes. it looks to the that the current LTS and stable are the same. we can probably use the same binary. (not familiar with LTS promotion though).
