### ISSUE TITLE
How to reduce the LCP indicator to 2с in PageSpeed Insights

### ISSUE THREAD

**Issue by RicoFenix** [ampproject/amphtml#31737]
Hello all,

I can't get LCP less than 2.5 s
amp pages use advertising and Analytics
how can I make the LCP indicator less than 2.3 s

**Comment by kristoferbaxter** [comment]
Have you tried using the Page Experience tool [here](https://amp.dev/page-experience/)?

This will provide a clear set of guidance regarding Core Web Vitals and AMP.
