### ISSUE TITLE
Branching navigation breaks stories

### ISSUE THREAD

**Issue by brianpetro** [ampproject/amphtml#31744]
## What's the issue?

[Branching](https://amp.dev/documentation/components/amp-story/#branching) feature breaks amp-story:

1. Page attachment fails to render after navigating via branching.
2. Page fails to appear when "navigating back" via branching.
3. Page attachment "href" attribute is unable to utilize branching, renders blank (white) screen.

## How do we reproduce the issue?

Using the demo at this jsbin https://jsbin.com/varawovutu/1/edit?html,output

1. On page-1, open the page-attachment, use the contained link to navigate from page-1 to page-3. The page-attachment on page-3 fails to appear.
2. Using the "Tap Here for More", go to page-3. Open the page attachment and click the link to navigate to page-1. This time, the page-1 attachment should still be visible. Open the page-1 page-attachment and click the link to navigate back to page-3. The page now appears to be blank (black). This looks similar to [issue 31586](https://github.com/ampproject/amphtml/issues/31586).
3. Using the "Tap Here for More", navigate to page-2. Use the page-attachment to navigate to page-4. The screen goes completely blank (white).

## What browsers are affected?

Tested on:

- Chrome 87
- Firefox 74
- Android 7: Chrome 87

## Which AMP version is affected?

2011252111003

**Comment by ychsieh** [comment]
This is similar to #38622. Both should be fixed after branching hash navigation is enabled in #39556.
