### ISSUE TITLE
amp-story error messages

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#31742]
We have pages with both `page attachment` and `cta layer`

We see these error messages:

`Tag 'amp-story-cta-layer', if present, must be the last child of tag 'amp-story-page'.`

`Tag 'amp-story-page-attachment', if present, must be the last child of tag 'amp-story-page'.`

How to resolve?

**Comment by brianpetro** [comment]
Not a bug. A page cannot contain both the page-attachment and cta-layer since the spec requires both to "be the last child tag of the tag 'amp-story-page'."

**Comment by jaygray0919** [comment]
Where did I miss that in the documentation?

**Comment by CrystalOnScript** [comment]
Both component reference documents specify they must be the last child of the `amp-story-page` tag. But I've added a note that specifies only one may be used per page. Sorry for any confusion!
