### ISSUE TITLE
customize amp story attachment icon

### ISSUE THREAD

**Issue by ghost** [ampproject/amphtml#31760]
i would like to know is there a way to use custom css for `.i-amphtml-story-page-open-attachment-icon:after` like shown in the pic

![image](https://user-images.githubusercontent.com/42892061/103296524-40b3d880-4a1c-11eb-87be-baef32d0226f.png)

**Comment by newmuis** [comment]
This UI is likely to change soon anyway, but when it does, it will allow for some degree of both color and icon customization.

**Comment by ychsieh** [comment]
amp-story-page-attachment does allow such customization now.
