### ISSUE TITLE
<amp-next-page> next-page-hide attribute does not work when a page is opened from google

### ISSUE THREAD

**Issue by carlosestevezmrf** [ampproject/amphtml#31775]
## What's the issue?
I can only reproduce this in AMP documents loaded inside the Google Search results AMP viewer.

This can be reproduced If an amp page has  `<amp-next-page>` tag  and an element with`next-page-hide ` attribute.

The expected behaviour is to hide the HTML element with `next-page-hide` attribute.

## How do we reproduce the issue?

1. Open [this](https://www.google.com/search?q=areajugones&prmd=niv&source=lnms&tbm=nws&sa=X&ved=2ahUKEwiF-4-96fbtAhVKGFkFHSp6CKEQ_AUoAXoECAMQAQ&biw=360&bih=640) URL in a cellphone. 
2. Open the first article of google results.
3. Scroll down in order to see the `<amp-next-page>` tag.
4. Scroll to the header of the page.
5. You will see two menu element, the first one have the `next-page-hide` attribute.

Here is a video of how to reproduce the issue:
https://gyazo.com/05818b6d4d726b15725ab6072e4381f7

The same document loaded from the original URL works correctly.
https://areajugones.sport.es/videojuegos/el-primer-dlc-de-cyberpunk-2077-llegara-a-principios-de-2021/amp/

**Comment by kristoferbaxter** [comment]
Closing issue in favor of #31951.

The Google team has temporarily rolled back a release of module scripts from the Google AMP Cache, we'll use #31951 to track fixing the underlying issue.
