### ISSUE TITLE
AMP update-cache not clearing the cached content

### ISSUE THREAD

**Issue by amrithakrishnan** [ampproject/amphtml#31794]
I set up the update-cache setup as per the [documentation](https://developers.google.com/amp/cache/update-cache). Hitting the update-cache API returns an OK response. However, the content remains unchanged (tried multiple times as well)
Here are the screenshots of the response.

Browser:
<img width="1152" alt="Screenshot 2021-01-05 at 11 48 45 AM" src="https://user-images.githubusercontent.com/10302887/103613412-89075500-4f4c-11eb-892e-af2236f8ff92.png">

Network:
<img width="936" alt="Screenshot 2021-01-05 at 11 50 45 AM" src="https://user-images.githubusercontent.com/10302887/103613395-81e04700-4f4c-11eb-9d85-5c5aaca6c026.png">

The key is publicly accessible at `/.well-known/amphtml/apikey.pub`. I'm generating the URL using an NPM package called `amp-toolbox-update-cache`. Since the response is OK, the setup done for this is fine, right?

I found a similar issue [here](https://github.com/ampproject/amphtml/issues/25264), but that seems to be a dead thread.

**Comment by honeybadgerdontcare** [comment]
@amrithakrishnan thank you for the report. It's unfortunate that you have encountered this. Hopefully it's been resolved for you by now. We're tracking related issues internally with b/148181766.
