### ISSUE TITLE
amp-embed can become stuck in the loading state after an amp-consent choice is made

### ISSUE THREAD

**Issue by hrkhal** [ampproject/amphtml#31801]
## What's the issue?

An `amp-embed` element behind a `data-block-on-consent` attribute can fail to load following a choice being made in amp-consent. The element will hang with the spinning icon and no `iframe` is inserted into `amp-embed` element. 

On occasion when this happens it will affect all elements behind `data-block-on-consent` including `amp-ad`.

It happens most often with `amp-embed` and was seen on the Google CDN by a client. When it does happen the affected elements are left in a perpetual loading state. 

In the instances where only `amp-embed` is affected we can see that `amp-consent` correctly passes on the consent details as we can see the consent string value in DFP calls for `amp-ad` elements.

[Here is a video](http://cdn.metro.co.uk/base/amp-embed-stuck-post-consent.mov) using iOS simulator that displays the issue with just the `amp-embed` failing after making a consent choice. 

Note that this only happens on the first visit as a new user, once refreshed everything works as expected and that we see no issues with `amp-embed` loading.

## How do we reproduce the issue?

The original internal reporter spotted it on the Google CDN but as a team we haven't been able to recreate it by happenstance. We can however recreate it on occasion using a private/incognito tab on an iOS device.

https://www.google.com/amp/s/www.dailymail.co.uk/sport/football/article-9110445/amp/William-Saliba-set-join-Nice-loan-end-season.html

1. Visit the above article on the Google CDN in iOS safari with a new incognito/private tab. You'll need to be using an EU connection for amp-consent 
2. Hit the the green `Got it` button.
3. Once the overlay has disappeared scroll down to the end of the article after the social sharing bar and comments block to the taboola amp-embed.
4. Note on occasion that the `amp-embed` will just hang with the amp loading icon.

## What browsers are affected?

iOS safari/chrome

## Which AMP version is affected?

2011252111003

**Comment by mhattersley** [comment]
Adding original reporters video (iPhone/Safari using incognito to reproduce)


https://user-images.githubusercontent.com/6448979/103764611-ae12cb00-5013-11eb-8c2d-6ba21d08b284.mp4

**Comment by mhattersley** [comment]
Adding original reporters video (iPhone/Safari using incognito to reproduce)

[Video](https://cdn.metro.co.uk/base/RPReplay_Final1608554960.MP4)

**Comment by micajuine-ho** [comment]
Looking at the video linked above, it seems like the placeholder for the ad gets stuck and continuously loads. Does anyone from the @ampproject/wg-monetization have any idea?

**Comment by hrkhal** [comment]
@micajuine-ho This is no longer reproducible by our term in version 2012232217000, which is on the Google CDN currently. Any thoughts as to what may have fixed the issue?

**Comment by micajuine-ho** [comment]
No recent consent changes come to mind. Would be interested to see if this issue pops up again in the near future.

**Comment by micajuine-ho** [comment]
I will close this issue for now, but please reopen if it crops up again.
