### ISSUE TITLE
Fluid amp-ad not visible when ad loading in viewport, "Cannot resize element" warning message

### ISSUE THREAD

**Issue by analyticbastard** [ampproject/amphtml#31823]
## What's the issue?

Our first amp-ad (which is fluid) is not visible if the user scrolls down quickly (in less than ~1 or ~1.5 secs) or when we reload the page and the ad is within the viewport. This started to happen in December near the end of 2020.

message in console

```
[CustomElement] Cannot resize element and overflow is not available <amp-ad rtc-config=​...
```

## How do we reproduce the issue?

Please see the first ad here (right after text `it will not be able to carry forth any plan of destruction, any plan of harm.'`):

https://www.dailymail.co.uk/news/article-7933365/amp/Donald-Trumps-spiritual-adviser-Paula-White-calls-satanic-pregnancies-miscarry.html

If page is left to load for ~1 sec, the ad will show.

The ad itself seems to load, it is just not visible.

## What browsers are affected?

Reproduced on Chrome and Safari

## Which AMP version is affected?

As stated, it was first spotted at around Christmas day 2020. We haven't introduced changes in that area for several weeks.

**Comment by calebcordry** [comment]
@powerivq is this related to your changes?

**Comment by calebcordry** [comment]
Read more closely and realized this is the impression spike we saw and the revert. @ampproject/wg-monetization @jeffkaufman

**Comment by lannka** [comment]
@analyticbastard according to your description, this is working as intended to avoid a page layout jump. AMP does not allow an ad slot to resize when it is already in viewport.

when you scroll fast, the ad slot enters the viewport before the ad response so its resize attempt gets rejected. Also note that this behavior is not new. It has been like this since day 1 of AMP.

**Comment by powerivq** [comment]
Have confirmed that the RTC PR revert does not affect this directly, but it might have some unintended affects due to slot being loaded earlier or later.

**Comment by analyticbastard** [comment]
@lannka @powerivq thanks for looking into this, it came as a surprise since it fails in Metro and Daily Mail with two parallel dev/QA pipelines and changes to fluid were signed off. We'll need to come up with a workaround. I'll close the ticket.
