### ISSUE TITLE
I2I: Video Intelligence Player extension

### ISSUE THREAD

**Issue by cosmin-vi** [ampproject/amphtml#31824]
## Summary
We want to create an AMP component that embeds the contextual video player unit from vi (video intelligence, www.vi.ai).

## Motivation
vi provides contextually matched videos through a proprietary contextual video unit to more than 1000 publishers. We want to offer a solid solution also for AMP to these publishers, through this new amp component. Several of our major publishers are using AMP and want to implement this.
Motivation for creating a new component vs using some existing (like e.g. amp-iframe) is:
- We need the option for users of the component to easily specify multiple configuration parameters needed by the player
- The player needs to get some information from the page for the contextual matching, such as page title and page language
- The player needs immediate access to the TCF consent string (iframe offers it only on request)

Regarding the naming, we suggest to name it `amp-vi-player`. vi has the following registration https://tsdr.uspto.gov/#caseNumber=79224084&caseType=SERIAL_NO&searchType=statusSearch

## Additional context
Example:
```html
<amp-vi-player
  data-publisher-id="test_amp_vi_player"
  data-channel-id="test_channel"
  layout="responsive"
  width="480"
  height="270"
>
</amp-vi-player>
```

Parameter | Description
------------ | -------------
`data-publisher-id` | Video Intelligence publisher id
`data-channel-id` | Video Intelligence channel id

For more configuration parameters, please check [https://docs.vi.ai/general/integrations/amp-vi-player](https://docs.vi.ai/general/integrations/amp-vi-player/).

## 
/cc @ampproject/wg-approvers @alanorozco

**Comment by alanorozco** [comment]
Thanks for this I2I.

> We need the option for users of the component to easily specify multiple configuration parameters needed by the player

Per the [third-party video policy:](https://github.com/ampproject/amphtml/blob/master/spec/amp-3p-video.md) How about `amp-video-iframe`? That way you could do something like this [out of the box:](https://amp.dev/documentation/components/amp-video-iframe/#third-party-video-vendors)

```jsx
<amp-video-iframe
  src="https://player.vi.ai/amp" // I made up this URL
  data-param-publisher-id="aaa"
  data-param-channel-id="bbb"
 ></amp-video-iframe>
```

`amp-video-iframe` does not pass consent but **it should**. (#31826)

In the interest of avoiding custom service code, I believe this should be the way to go. 

> The player needs to get some information from the page for the contextual matching, such as page title and page language

These appear to be:

```js
        dict({
          'viTitle': document.title,
          'viPageLanguage': win.document.documentElement.lang,
        })
```

I can see the need for these, but maybe these should be part of the standard `amp-video-iframe` set or you could get them some other way:

- `document.title` should probably be passed as part of [`amp-video-iframe` metadata](https://amp.dev/documentation/components/amp-video-iframe/#getmetadata()), so I'll get a change going for that.

- `documentElement.lang` seems a bit more niche. [`amp-video-iframe` metadata](https://amp.dev/documentation/components/amp-video-iframe/#getmetadata()) gives you a `sourceUrl`. You could fetch and parse that inside the iframe.

> The player needs immediate access to the TCF consent string (iframe offers it only on request)

What's the material difference of getting immediate access vs. requesting it from the frame? On a [different thread](https://github.com/ampproject/amphtml/pull/30526#issuecomment-755438993) you mention running in-stream ads, but I don't understand how this matters for the implementation.

**Comment by cosmin-vi** [comment]
Hi @alanorozco ,

Considering the changes you suggested (i.e. consent + title + lang in amp-video-iframe), we'll be able to use amp-video-iframe instead of our own component.
Do you have any estimation when these changes will be deployed to production ?
Is there any chance to include more metadata ? Description or access to other structured data is useful to us for our contextual matching.

Thank you,
Cosmin

**Comment by alanorozco** [comment]
@cosmin-vi The changes to `amp-video-iframe` have been merged. [They should be on the beta channel by next Tuesday, and on stable the week after.](https://amp.dev/documentation/guides-and-tutorials/learn/spec/release-schedule/)

**Comment by cosmin-vi** [comment]
Thank you @alanorozco 
We will try them on the stable build.
