### ISSUE TITLE
Inquiry for official AMP support in Taboola Newsroom

### ISSUE THREAD

**Issue by netslayer** [ampproject/amphtml#31834]
We're looking to become an official AMP vendor for analytics for our Newsroom application at Taboola. Taboola Newsroom provides real time and historic analytics for publisher newsrooms (https://www.taboola.com/newsroom). Can you please outline the process for onboarding? Thank you

**Comment by kristoferbaxter** [comment]
@micajuine-ho and @zhouyx if we don't already have documentation for this process, can we create it?

**Comment by micajuine-ho** [comment]
Hi @netslayer, thank you for your issue report. Are you looking to integrate Taboola Newsroom as an Analytics Vendor into `amp-analytics`?

If so, the following documentation will outline the steps required:
https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/integrating-analytics.md

**Comment by netslayer** [comment]
awesome, yes, thank you. Exactly what I was looking for.
