### ISSUE TITLE
Iframe content sometimes isn't loading

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#3184]
This might be limited to Chrome 52.

Example page https://ampbyexample.com/advanced/how_to_create_interactive_amp_pages/

It is not 100% reproducible. When it fails the iframe itself is never requested.

**Comment by cramforce** [comment]
Also happens on Chrome 50

**Comment by cramforce** [comment]
This is a race condition that happens when all the elements are cached.

**Comment by cramforce** [comment]
CC @dvoytenko

**Comment by cramforce** [comment]
This is a race that happens when everything is cached and `v0.js` comes first.

**Comment by cramforce** [comment]
The race is that the element classes are stubbed, but the elements aren't yet in stubbedElements.

**Comment by cramforce** [comment]
Oh, wow, the code assumes that by the time the upgrade happens, all elements have been seen.

**Comment by dvoytenko** [comment]
Hmm. It shouldn't. The newly discovered elements just supposed to upgrade right away.
