### ISSUE TITLE
amp-twitter doesn't display well in Chrome

### ISSUE THREAD

**Issue by okeul** [ampproject/amphtml#3185]
`amp-twitter` doesn't display well in Chrome but it works Firefox. 

Chrome (Version 49.0.2623.112) :
![amp-twitter_chrome](https://cloud.githubusercontent.com/assets/6248074/15187027/b95a9f3a-179f-11e6-8ccd-0050ba488025.png)

Firefox (Version 45.0)
![amp-twitter_firefox](https://cloud.githubusercontent.com/assets/6248074/15187033/c28853b8-179f-11e6-92db-1a8c9628e8a5.png)

Example : 
http://jsbin.com/jekobu/1/edit?html,output

**Comment by jridgewell** [comment]
Thanks for the bug report, and even more for providing a jsbin! I'm looking into this now.

**Comment by jridgewell** [comment]
Tracked this down to Twitter's new [Shadow DOM rendering](https://twittercommunity.com/t/upcoming-change-to-embedded-tweet-display-on-web/66215). In the old code, we are trying to [resize the iframe](https://github.com/ampproject/amphtml/blob/master/3p/twitter.js#L54-L65) they create. Well, the Shadow DOM rendering doesn't create an iframe...

For reference, here's the new [generated HTML](https://gist.github.com/jridgewell/1abe24266d9206fa4ce212817701bad6) in the embedded tweet. Passing this off to @cramforce to fix.

**Comment by ericlindley-g** [comment]
Looks like the fix is merged—@cramforce, can we close this issue?

**Comment by jridgewell** [comment]
This'll be hitting production tomorrow.

**Comment by okeul** [comment]
Thanks guys !
