### ISSUE TITLE
[amp-base-carousel] The attribute 'controls' may not appear in tag 'amp-base-carousel'.

### ISSUE THREAD

**Issue by Notebit** [ampproject/amphtml#31872]
According to the documentation https://amp.dev/documentation/components/amp-base-carousel/?format=websites
amp-base-carousel supports the "controls" attribute.
So I added controls="never" to my amp-base-carousel but I get a validator error
"The attribute 'controls' may not appear in tag 'amp-base-carousel'."

Except for the validator error, it seems to work correctly. Am I missing anything or the validator needs to be fixed?

## How do we reproduce the issue?

You can reproduce the issue just adding controls="never" or controls="always" to your amp-base-carousel tag

<amp-base-carousel
  attr-name="attr value"
  attr-name="attr value"
  attr-name="attr value"
controls="never"
></amp-base-carousel>

**Comment by honeybadgerdontcare** [comment]
@ampproject/wg-components the example in the [docs](https://amp.dev/documentation/components/amp-base-carousel/?format=websites) under `Media Queries` is invalid for `attr-name`. Could you diagnose the issue here and submit a fix if necessary.

Here's my full code snippet which shows both `attr-name` and `controls` as invalid:

```
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <link rel="canonical" href="self.html">
  <meta name="viewport" content="width=device-width,minimum-scale=1">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script async custom-element="amp-base-carousel" src="https://cdn.ampproject.org/v0/amp-base-carousel-0.1.js"></script>
</head>
<body>
<amp-base-carousel layout=fixed width=1 height=1 controls=never attr-name="(min-width: 1000px) valueOne, (min-width: 600px) valueTwo, defaultValue"></amp-base-carousel>
</body>
</html>
```

@Notebit sorry you've encountered this issue. It would be helpful if you could provide a full snippet where only the portion that is problematic being the issue. If you have one we'd appreciate it. Feel free to remove any identifying items. The example included has issues around `attr-name`.

**Comment by Notebit** [comment]
@honeybadgerdontcare no problem it is not a big issue, I think it just needs a small update to the validator
for example this code is taken from the official playground, I just added controls=never and i get the validator error

<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <title>amp-inline-gallery - Example 1</title>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script custom-element="amp-inline-gallery" src="https://cdn.ampproject.org/v0/amp-inline-gallery-0.1.js" async></script>
  <script custom-element="amp-base-carousel" src="https://cdn.ampproject.org/v0/amp-base-carousel-0.1.js" async></script>
  <script custom-element="amp-lightbox-gallery" src="https://cdn.ampproject.org/v0/amp-lightbox-gallery-0.1.js" async></script>
  <link rel="canonical" href="https://preview.amp.dev/documentation/components/amp-inline-gallery.example.1.html">
  <meta name="viewport" content="width=device-width">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
</head>
<body>

<amp-inline-gallery layout="container">
  <amp-base-carousel
    class="gallery"
    layout="responsive"
    width="3.6"
    height="2"
    controls=never
    snap-align="center"
    loop="true"
    visible-count="1.2"
    lightbox
  >
    <amp-img
      src="/static/inline-examples/images/image1.jpg"
      layout="responsive"
      width="450"
      height="300"
    ></amp-img>
    <amp-img
      src="/static/inline-examples/images/image2.jpg"
      layout="responsive"
      width="450"
      height="300"
    ></amp-img>
    <amp-img
      src="/static/inline-examples/images/image3.jpg"
      layout="responsive"
      width="450"
      height="300"
    ></amp-img>
  </amp-base-carousel>
  <amp-inline-gallery-pagination layout="nodisplay" inset>
  </amp-inline-gallery-pagination>
</amp-inline-gallery>
</body>
</html>

**Comment by Notebit** [comment]
@honeybadgerdontcare btw I think attr-name is not a real attribute, it is just a generic name for describing any attribute, so I think that if the validator considers "attr-name" as invalid it is correct.

**Comment by caroqliu** [comment]
To add some context here, amp-base-carousel recently updated the documentation to say that the [`controls`](https://amp.dev/documentation/components/amp-base-carousel/#controls) attribute can be used with `never|always|auto`, defaulting to `auto` - the validator rules should reflect this, and my apologies for not catching it sooner.

**Comment by caroqliu** [comment]
Note it should also support [media query based attributes,](https://amp.dev/documentation/components/amp-base-carousel/#media-queries) which all of the other attributes on `amp-base-carousel` should allow via validation already. Something like `controls="(pointer: fine) auto, never"`, for example, should be valid.

**Comment by michalestyle** [comment]
My [Bearing Model](https://www.bearingmodel.com) website also encountered this problem, https://www.bearingmodel.com but I have solved it.
