### ISSUE TITLE
[amp-base-carousel] loop=true snap=true and jittering transitions between slides

### ISSUE THREAD

**Issue by Notebit** [ampproject/amphtml#31875]
## What's the issue?
amp-base-carousel supports loop=true and snap=true but if both are enabled then we get something wrong with the slide transitions and the user experience isn't the best.
for example in the following code the next button changes the slide with an easing, but the previous button changes the slide without any easing
```
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <title>amp-inline-gallery - Example 1</title>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script custom-element="amp-inline-gallery" src="https://cdn.ampproject.org/v0/amp-inline-gallery-0.1.js" async></script>
  <script custom-element="amp-base-carousel" src="https://cdn.ampproject.org/v0/amp-base-carousel-0.1.js" async></script>
  <script custom-element="amp-lightbox-gallery" src="https://cdn.ampproject.org/v0/amp-lightbox-gallery-0.1.js" async></script>
  <link rel="canonical" href="https://preview.amp.dev/documentation/components/amp-inline-gallery.example.1.html">
  <meta name="viewport" content="width=device-width">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
</head>
<body>

<amp-inline-gallery layout="container">
  <amp-base-carousel
    id="carousel1"
    class="gallery"
    layout="responsive"
    width="3.6"
    height="2"
    snap-align="start"
    loop="true"
                     snap=true
                     mixed-length=false
    lightbox
  >
    <amp-img
      src="/static/inline-examples/images/image1.jpg"
      layout="responsive"
      width="450"
      height="300"
    ></amp-img>
    <amp-img
      src="/static/inline-examples/images/image2.jpg"
      layout="responsive"
      width="450"
      height="300"
    ></amp-img>
    <amp-img
      src="/static/inline-examples/images/image3.jpg"
      layout="responsive"
      width="450"
      height="300"
    ></amp-img>
 
  </amp-base-carousel>

  <amp-inline-gallery-pagination layout="nodisplay" inset>
  </amp-inline-gallery-pagination>
</amp-inline-gallery>
    <button on="tap:carousel1.prev()">Previous</button>
  <button on="tap:carousel1.next()">Next</button>
</body>
</html>
```

if you change to snap-align=center, then you get a very fast easing to next and to previous slides if you click on the Next and Previous buttons, but if you just swipe with your finger on the slides for moving to next one or previous one, then you get jittering and a broken user experience.
Moving back to snap-align=start solves the swipe issue but then you lose the easing if you click on the Previous button.

Update: I don't see the issue in Firefox, so maybe it's a browser related issue. I see the issue in Chrome both on desktop and on mobile.

For reproducing the issue you can open this experiment in the AMP playground
[playground](https://playground.amp.dev/?format=websites#share=PCFkb2N0eXBlIGh0bWw+CjxodG1sIOKaoT4KPGhlYWQ+CiAgPG1ldGEgY2hhcnNldD0idXRmLTgiPgogIDx0aXRsZT5hbXAtaW5saW5lLWdhbGxlcnkgLSBFeGFtcGxlIDE8L3RpdGxlPgogIDxzY3JpcHQgYXN5bmMgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC5qcyI+PC9zY3JpcHQ+CiAgPHNjcmlwdCBjdXN0b20tZWxlbWVudD0iYW1wLWlubGluZS1nYWxsZXJ5IiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1pbmxpbmUtZ2FsbGVyeS0wLjEuanMiIGFzeW5jPjwvc2NyaXB0PgogIDxzY3JpcHQgY3VzdG9tLWVsZW1lbnQ9ImFtcC1iYXNlLWNhcm91c2VsIiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1iYXNlLWNhcm91c2VsLTAuMS5qcyIgYXN5bmM+PC9zY3JpcHQ+CiAgPHNjcmlwdCBjdXN0b20tZWxlbWVudD0iYW1wLWxpZ2h0Ym94LWdhbGxlcnkiIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAvYW1wLWxpZ2h0Ym94LWdhbGxlcnktMC4xLmpzIiBhc3luYz48L3NjcmlwdD4KICA8bGluayByZWw9ImNhbm9uaWNhbCIgaHJlZj0iaHR0cHM6Ly9wcmV2aWV3LmFtcC5kZXYvZG9jdW1lbnRhdGlvbi9jb21wb25lbnRzL2FtcC1pbmxpbmUtZ2FsbGVyeS5leGFtcGxlLjEuaHRtbCI+CiAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCI+CiAgPHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1vei1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDstbXMtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7YW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGh9QC13ZWJraXQta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtbW96LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1zLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW8ta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUBrZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19PC9zdHlsZT48bm9zY3JpcHQ+PHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOm5vbmU7LW1vei1hbmltYXRpb246bm9uZTstbXMtYW5pbWF0aW9uOm5vbmU7YW5pbWF0aW9uOm5vbmV9PC9zdHlsZT48L25vc2NyaXB0Pgo8L2hlYWQ+Cjxib2R5PgoKPGFtcC1pbmxpbmUtZ2FsbGVyeSBsYXlvdXQ9ImNvbnRhaW5lciI+CiAgPGFtcC1iYXNlLWNhcm91c2VsCiAgICBpZD0iY2Fyb3VzZWwxIgogICAgY2xhc3M9ImdhbGxlcnkiCiAgICBsYXlvdXQ9InJlc3BvbnNpdmUiCiAgICB3aWR0aD0iMy42IgogICAgaGVpZ2h0PSIyIgogICAgc25hcC1hbGlnbj0ic3RhcnQiCiAgICBsb29wPSJ0cnVlIgogICAgICAgICAgICAgICAgICAgICBzbmFwPXRydWUKICAgICAgICAgICAgICAgICAgICAgbWl4ZWQtbGVuZ3RoPWZhbHNlCiAgICBsaWdodGJveAogID4KICAgIDxhbXAtaW1nCiAgICAgIHNyYz0iL3N0YXRpYy9pbmxpbmUtZXhhbXBsZXMvaW1hZ2VzL2ltYWdlMS5qcGciCiAgICAgIGxheW91dD0icmVzcG9uc2l2ZSIKICAgICAgd2lkdGg9IjQ1MCIKICAgICAgaGVpZ2h0PSIzMDAiCiAgICA+PC9hbXAtaW1nPgogICAgPGFtcC1pbWcKICAgICAgc3JjPSIvc3RhdGljL2lubGluZS1leGFtcGxlcy9pbWFnZXMvaW1hZ2UyLmpwZyIKICAgICAgbGF5b3V0PSJyZXNwb25zaXZlIgogICAgICB3aWR0aD0iNDUwIgogICAgICBoZWlnaHQ9IjMwMCIKICAgID48L2FtcC1pbWc+CiAgICA8YW1wLWltZwogICAgICBzcmM9Ii9zdGF0aWMvaW5saW5lLWV4YW1wbGVzL2ltYWdlcy9pbWFnZTMuanBnIgogICAgICBsYXlvdXQ9InJlc3BvbnNpdmUiCiAgICAgIHdpZHRoPSI0NTAiCiAgICAgIGhlaWdodD0iMzAwIgogICAgPjwvYW1wLWltZz4KIAogIDwvYW1wLWJhc2UtY2Fyb3VzZWw+CgogIDxhbXAtaW5saW5lLWdhbGxlcnktcGFnaW5hdGlvbiBsYXlvdXQ9Im5vZGlzcGxheSIgaW5zZXQ+CiAgPC9hbXAtaW5saW5lLWdhbGxlcnktcGFnaW5hdGlvbj4KPC9hbXAtaW5saW5lLWdhbGxlcnk+CiAgICA8YnV0dG9uIG9uPSJ0YXA6Y2Fyb3VzZWwxLnByZXYoKSI+UHJldmlvdXM8L2J1dHRvbj4KICA8YnV0dG9uIG9uPSJ0YXA6Y2Fyb3VzZWwxLm5leHQoKSI+TmV4dDwvYnV0dG9uPgo8L2JvZHk+CjwvaHRtbD4=)

**Comment by micajuine-ho** [comment]
This was fixed in https://github.com/ampproject/amphtml/pull/31536 (verified). 

Should be merged into stable next week.
