### ISSUE TITLE
[AMP Validator Link] The web interface of AMP Validator link throws an error of 503: Over Quota 

### ISSUE THREAD

**Issue by kamblenavnath** [ampproject/amphtml#31871]
## What's the issue?

A provided link i.e [AMP Validator](https://validator.ampproject.org/) is not working. It is throwing an error **503**. Continuously saying that, _the application is temporarily over its serving quota. Please try again later_.

## How do we reproduce the issue?

Hit the link [validator.ampproject.org](https://validator.ampproject.org/) on  any browser.

## What browsers are affected?

All browsers

**Comment by honeybadgerdontcare** [comment]
@kamblenavnath thank you for the report. We're aware of the issue and are actively working to mitigate it. It is up right now and we'll continue to monitor it. Feel free to reopen if you find it unavailable.
