### ISSUE TITLE
I2I: amp-consent/pubtech #31902

### ISSUE THREAD

**Issue by MProntera** [ampproject/amphtml#31901]
## Summary
Pubtech provides its publishers with an IAB validated CMP.
I will create a PR to introduce the integration of the Pubtech CMP configuration in the amp-consent component.

I'll add the PR link here.

/cc @ampproject/wg-approvers

**Comment by MProntera** [comment]
Link PR: [https://github.com/ampproject/amphtml/pull/31902](url)

**Comment by micajuine-ho** [comment]
Hi @MProntera, is the PR ready for review?

**Comment by MProntera** [comment]
Yes, the PR is ready. https://github.com/ampproject/amphtml/pull/31902

**Comment by micajuine-ho** [comment]
Closed via #31902
