### ISSUE TITLE
[amp-story-player] Going back to the first page with video causes the video to not load sometimes. 

### ISSUE THREAD

**Issue by pshihn** [ampproject/amphtml#31908]
If the first first page is a video, and you are now on the last page. If you call `player.go()` to go back to the first page, sometimes the video does not load on the first page. 

![unnamed](https://user-images.githubusercontent.com/833927/104350080-98405280-54b8-11eb-872f-125f102202f3.png)

This only started happening recently. I suspect it's due to other optimizations that went in recently to prevent off-screen playing. 

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 2012232217000

**Comment by processprocess** [comment]
cc @Enriqe for story-player context.

**Comment by Enriqe** [comment]
What platform / OS are you using? I haven't been able to repro but I'll keep monitoring.

**Comment by pshihn** [comment]
Chrome on MacOS 
Also seen on Safari on iOS 
It doesn't happen all the time but sometimes but does happen if you keep at it. There may be some timing issue about whether the video has played completely or not when moving back to it. I'll see if there's a particular story where it happens more frequently

**Comment by Enriqe** [comment]
Could you share the story / player you are using? Even a codepen or something similar would be helpful.

**Comment by gmajoulet** [comment]
We fixed many bugs through video and Player refactorings, this issue likely went away. Please re-open this ticket if you see it happening again, and consider switching to the `replay()` method that we will introduce, that has been working around some of the issues you're facing in the past: https://github.com/ampproject/amphtml/issues/31424
