### ISSUE TITLE
First tap on any <a> element on iOS >=13 doesn't work when using <amp-carousel>

### ISSUE THREAD

**Issue by bartesn** [ampproject/amphtml#31926]
## What's the issue?

When entering the website for the first time in a session (typing an address directly / going from search results) on iPhone (iOS 13.x, 14.x), a first tap on any <a> does not result in going to a page from the link. The tap results only in a standard visual confirmation that element was taped (iOS short link "blink").
A second tap on the same <a> element or any other anchor works as expected, redirecting to the page from link. From that moment links start to work normally during the session. After leaving and re-entering the website (for example by closing the tab), the situation repeats itself from the beginning.
The problem is somehow caused by `<amp-carousel>`- removing the carousel from the page solves the problem.

## How do we reproduce the issue?

1. Go to https://codepen.io/bartesn/full/BaLqqQz on iPhone / XCode iPhone simulator iOS 13.x, 14.x
2. Wait until an arrow button in a carousel (grey box with "Slide 1") disappears - everything works fine if that button is visible
3. Tap on "AMP" link above the carousel
4. Link only "blinks" confirming a tap, does not redirect to a new page; the arrow button in the carousel appears
5. Tap the link once again - link works as expected, redirecting to a new page

## Screen capture on iOS simulator

https://user-images.githubusercontent.com/9989233/104425617-2e3fb000-5581-11eb-90bb-c4887019c17b.mov

## What browsers are affected?

- Browser: Safari & Chrome
- Device: every iPhone & XCode iPhone simulator with iOS >= 13

## Which AMP version is affected?

The issue seems to have been present for some time, at least a few months, unfortunately I don't know if it has always been present.

**Comment by bartesn** [comment]
The issue seems to be similar to https://github.com/ampproject/amphtml/issues/30838

**Comment by caroqliu** [comment]
I'm able to reproduce this as well. I noticed that your code sample uses amp-carousel version 0.1 - does the problem resolve when upgrading to 0.2?

**Comment by bartesn** [comment]
@caroqliu I created another test codepen with `<amp-carousel>` **v2** and the update seems to fix the problem: https://codepen.io/bartesn/full/abmQJww
However, it seems that v2 has lost the slide animation on Safari on Mac, it just replaces carousel items on a button click. Is this what should happen?

**Comment by caroqliu** [comment]
@bartesn Thanks for trying out the new version! Glad to hear it fixed the first problem. :) 

As for the smooth scrolling behavior, the v2 carousel uses `scroll-behavior: smooth` CSS, which looks like it has to be turned on by the user in Safari 14: https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior#browser_compatibility

It looks like for v1, we animate it manually with JS instead of relying solely on CSS, hence the interaction difference you noticed: https://github.com/ampproject/amphtml/blob/5d30af46b9f0f0c2acdd2aab51605976c80a5551/extensions/amp-carousel/0.1/slidescroll.js#L818-L835

**Comment by bartesn** [comment]
@caroqliu Thank you for the answer. Either way we are staying with the v2 version as the lack of animation on MacOS Safari is less of a problem than the previously not working links on iOS. Thank you for your help, in my opinion the issue can be closed.
