### ISSUE TITLE
🌸 Cherry-pick request for #31911 into #31929 #31930 (Approved)

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#31921]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #31911 | #31916 |     YES     | YES | NO | #31929 #31930                                                             |

## Why does this issue meet the [cherry-pick criteria]
Unmuted autoplay is broken on iOS 14.2 and 14.3
Unmuted autoplay is core functionality of our format.

## List the steps to manually verify the changes in this cherry-pick

- Open a story with audio and autoplay such as [this story](https://www.vice.com/stories/making-20k-a-month-selling-street-cocktails/)
- unmute story and let autoplay trigger navigation through entire story

If audio is playing on all pages and unmute is tapped, the change is verified.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

A browser bug in iOS 14.2 and 14.3 requires video to play before being unmuted. This bug does only appears after navigating 3 pages or more. It was not found in our manual tests 

## Impact

- iOS 14.2 and 14.3 users viewing stories with unmuted auto advance would not hear audio after navigating 3+ pages without manually muting and unmuting again.
- Stories that depend on unmuted auto advance for their experience were effected.

## Action Items

- We've added a `devices and OS` to our manual tests document to be sure our team covers testing on a variety of devices and OS.

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by gmajoulet** [comment]
After debugging deeper, we found that the audio experience on iOS is broken for iOS 14.2 and above, regardless of auto-advance or manual advance.

This is a Safari regression where an unmuted video (muted: false) has its audio NOT playing. The bug seems to only happen if you set `muted = false;` before calling `play()`. We should investigate further and file a bug report against WebKit, but given the severity we'd like to get this workaround cherrypicked ASAP.

**Comment by cramforce** [comment]
Approved

**Comment by kristoferbaxter** [comment]
Approved.

**Comment by Enriqe** [comment]
CPs completed for stable (2012301722001) and new beta (2101090132001). Off to @processprocess for closing this issue once PM & action items are completed.
