### ISSUE TITLE
[amp-story-player] cannot read property then of undefined.

### ISSUE THREAD

**Issue by saurabh230197** [ampproject/amphtml#31925]
## What's the issue?

I have a carousel of stories whenever I click on a story amp-story-player gets visible and I called player.show(url) to show that clicked story. everything works fine but sometime when I have 30 stories in a carousel and I click on a story following error appears in console and shown story doesn't load.

Cannot read property 'then' of undefined\n    at V (https://cdn.ampproject.org/amp-story-player-v0.js:79:404)\n    at Gb (https://cdn.ampproject.org/amp-story-player-v0.js:56:407)\n    at Eb.k.play (https://cdn.ampproject.org/amp-story-player-v0.js:56:345)

## What browsers are affected?

All browsers

**Comment by processprocess** [comment]
cc @Enriqe

**Comment by Enriqe** [comment]
Closed by #32153
