### ISSUE TITLE
Avoid loading external resources in tests

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#3194]
Use `doNotLoadExternalResourcesInTest` introduced in #3132 to avoid loading actual images/iframes in the test.

**Comment by mkhatib** [comment]
Thanks for filing 😄

**Comment by muxin** [comment]
Fix tests in for `amp-twitter`, `amp-brightcove`, `amp-bird-player`, `amp-dailymotion`, `amp-jwplayer`, `amp-kaltura`, `amp-reach-player`, `amp-soundcloud`, `amp-springboard-player`, `amp-vimeo`, `amp-vine`
