### ISSUE TITLE
Explore adding data-params-* to iframe-based 3rd party embeds

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#3195]
Follow up to #3188 to explore and possibly add this functionality to other extensions.

Research and see if these services already allow configuration through parameters and if allowing publishers to pass extra parameters to configure them would be useful:
- amp-dailymotion
- amp-instagram
- amp-soundcloud
- amp-vimeo
- amp-vine

Maybe:
- amp-facebook
- amp-twitter

**Comment by cramforce** [comment]
I think we should discuss whether exposing the leaky abstraction that there is an iframe and we should copy these into the URL is something we want to hard code in our API. It would prohibit future changes of the implementation.

I'm not sure on this. Maybe a good topic for format review.
