### ISSUE TITLE
Prefetch visible links on an AMP page as user scrolls

### ISSUE THREAD

**Issue by neerajklite** [ampproject/amphtml#31987]
### Prefetch visible links on an AMP page as user scrolls

Prefetching visible links on the viewport automatically would drastically improve experience resulting is increased engagement with the website and user satisfaction.

### Alternatives

Currently AMP supports prefetch but only when its specifically mentioned in the head for that element on the page. It does not do it for all the links.

### Additional context

Some javascript frameworks like Gatsby do it by default using the library [quicklink](https://github.com/GoogleChromeLabs/quicklink). One important consideration would be the increased server requests. So there has to be a way to filter out only the required links for prefetch , perhaps by using a link attribute of some sort.

**Comment by kristoferbaxter** [comment]
Unfortunately this is not possible without a ServiceWorker with AMP, unless I am mistaken.

The Analytics systems depend on rewriting links when a user intends to navigate. These rewrites during navigation cause the navigated to page to change it's URL, meaning the user-agent cannot use the preloaded response for the now updated URL.

**Comment by kristoferbaxter** [comment]
Closing this issue, since it appears to solve the question.
