### ISSUE TITLE
🌸 Cherry-pick request for #31988 into #31929 (Complete)

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#31989]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| https://github.com/ampproject/error-reporting/issues/36 | #31988 |    **YES**     | **NO** | **NO** | #31930                                                             
| https://github.com/ampproject/error-reporting/issues/36 | #31988 |    **NO**     | **YES** | **NO** | #31929                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?
This meets the cherry pick criteria as `amp-date-picker` can break on esm builds, used by the Google AMP Cache.

## List the steps to manually verify the changes in this cherry-pick
1.  Load https://jsbin.com/nosakit
2. A datepicker should appear

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

A previous fix to the module build sourcemaps required us adding a `;` preamble to correct line numbers. This had a side effect of adding a bug in the amp-date-picker build as it had custom code that infixed the third party library it depends on. The append code instead prefixed the the third library code instead of wrapping it inside the compile wrappers.

## Impact

- All users of `amp-date-picker` are affected but since the bug is a race condition (race on which `AMP` the third party library adds the `AMP.require` function to), it sometimes works and all depends on the ordering of the script tags loading
- fully broken amp-date-picker on some instances

## Action Items

- #31988: <_Add unit/integration/end-to-end test_>
- Fix append code to be more resilient by using something like babel + infix marker instead of `indexOf` + substringing.
- add amp-next-page visual diff test
- add a manual test entry for amp-next-page

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by kristoferbaxter** [comment]
Approved.

**Comment by Enriqe** [comment]
Performing CP to beta & stable.

**Comment by erwinmombay** [comment]
added some action items

**Comment by samouri** [comment]
CP to stable is complete

**Comment by Enriqe** [comment]
/to @erwinmombay for closing when PM / action items are completed
