### ISSUE TITLE
🌸 Cherry pick request for #31978 into #31929 (Complete)

### ISSUE THREAD

**Issue by dmanek** [ampproject/amphtml#31980]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #31951 | #31978 |     **YES**     | **NO** | **NO** | #31930 (beta)                                                             |
| #31951 | #31978 |     **NO**     | **YES** | **NO** | #31929 (prod)                                                             |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?
Publishers are seeing several rendering issues in pages loaded via amp-next-page and use amp-ad and amp-img due to module experiment eliminating CSS from the runtime code.

## List the steps to manually verify the changes in this cherry-pick

1. Use dev tools to emulate mobile device. Go to google.com and search for "cnet airpods 549 znet things you could buy instead"
2. Open the cnet amp page on SERP.
3. Scroll down to allow amp-next-page to load additional pages to allow an infinite scroll like experience.
4. Verify that ads and images render as expected.

# Mini-postmortem

## Summary

On the AMP viewer, pages loaded via amp-next-page that contained amp-ad and amp-img were having rendering issue due to module experiment eliminating CSS from the runtime code.

## Impact

Module experiment is only enabled on the AMP viewer, thus, all pages viewed within the viewer that loaded additional content via the amp-next-page and containing amp-img and amp-ad were impacted.

## Action Items

- add amp-next-page visual diff test
- add a manual test entry for amp-next-page to @Ichigo3d test release check list

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by kristoferbaxter** [comment]
Approved.

**Comment by samouri** [comment]
As described in more depth in https://github.com/ampproject/amphtml/issues/31930, the CP to beta was cancelled in favor of cutting a new beta from master.

**Comment by samouri** [comment]
CP to stable is complete
