### ISSUE TITLE
Kill the tests if the port is busy

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#3199]
Karma automatically increment the port number if it's busy and just output an easily ignorable warning that the port was busy. A lot of the tests will fail if Karma ran on a different port - not entirely sure why but I believe we hardcode some of the ports somewhere.

@erwinmombay suggested one easy way to do this is to allow the `gulp test` task to check if anything is running on that port and die if something is busy on that port with a clear error to kill processes running on that port before running tests.

Otherwise, one (not me of course, just anyone) could waste a lot of time trying to figure out why their change is breaking tests while the tests are broken because of port changes.

/cc @zhouyx

**Comment by cramforce** [comment]
It would also be possible to make the tests pass on different ports, but I'm super cool with just dying.

**Comment by rsimha-amp** [comment]
This is fixed. Try running `gulp serve` twice with the same port.
