### ISSUE TITLE
[amp-ad A4A] Pass in `additionalConsent` from `consentMetdata` to ad request URL

### ISSUE THREAD

**Issue by micajuine-ho** [ampproject/amphtml#31998]
Some publishers would like to pass their `additionalConsent` string (collected from `amp-consent` in `consentMetadata`) to doubleclick & adSesne as a URL parameter in the ad request URL.

Currently, doubleclick does accept the `addtl_consent` url parameter in the ad request URL (https://support.google.com/admanager/answer/9681920?hl=en), however in AMP we are not sending it https://github.com/ampproject/amphtml/blob/78dfc030908c5a1ae78b171cf0604d27660c3f98/extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js#L641-L656

/cc @ampproject/wg-monetization

**Comment by JacopoBassan** [comment]
As `amp-consent` supports it, and in our CMP we are using that feature for Google’s Additional Consent, we would like too to have that parameter passed to `amp-ad`.

**Comment by mxdvl** [comment]
We’ve noticed that this `addtlConsent` is missing from the saved local store, even though it comes through a remote `amp-consent`’s `window.postMessage`’s payload as `consentMetadata`.

**Comment by micajuine-ho** [comment]
@mxdvl Can you file a new issue? I want to keep this thread separate.

**Comment by jeffkaufman** [comment]
Passing the additional consent as a URL parameter makes sense to me
