### ISSUE TITLE
AMP playground throws error for valid AMP4Email markup

### ISSUE THREAD

**Issue by esafwan** [ampproject/amphtml#32037]
## What's the issue?
`<input type=file>` is listed under allowed input type in the [official documentation](https://amp.dev/documentation/components/amp-form/?format=email). However, both AMP Playground and Gmail AMP for Email playground throws validation error as below:

> The attribute 'type' in tag 'input' is set to the invalid value 'file'. 

## How do we reproduce the issue?
Run below markup in AMP playground with email as format:

```
<!doctype html>
<html ⚡4email data-css-strict>
<head>
  <meta charset="utf-8">
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script async custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js"></script>
  <style amp4email-boilerplate>body{visibility:hidden}</style>
  <style amp-custom>
    h1 {
      margin: 1rem;
    }
  </style>
</head>
<body>
<div class="container">    
  <h1>Hello, I am an AMP EMAIL!</h1>
	<form method=POST action-xhr="https://firstudr.tridz.in/">
    <input type="file" name="upload" >
    <input type="submit" value="Upload">
  </form>
</div>
</body>
</html>
```

## Which AMP version is affected?

Latest provided by default in examples of the documentation.

```
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script async custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js"></script> 
```

**Comment by kristoferbaxter** [comment]
@honeybadgerdontcare Can you clarify if this is a documentation issue?

https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii#L3515

**Comment by honeybadgerdontcare** [comment]
@kristoferbaxter I don't think it's a documentation issue but an oversight that the AMP4EMAIL html format was not included for that tagspec. Especially since certain attributes are disabled by that format. I'll confirm the with the email team and respond back.

**Comment by honeybadgerdontcare** [comment]
@esafwan This is a documentation issue and both type=file and type=password are not allowed in AMP4EMAIL.

@CrystalOnScript for triaging documentation.

This is listed under allowed:
`<input type=password> and <input type=file> inside of <form method=POST action-xhr>`
but should be under not allowed as:
`<input type=password> and <input type=file>`

**Comment by zhangsu** [comment]
Send #32055 to fix the incorrect documentation.

**Comment by esafwan** [comment]
@honeybadgerdontcare Thanks for the clarification. 

1. Is there a roadmap or something where we can see what features are in pipeline for future releases? And is there any chance for file upload to be included in allowed input types? 

2. In cases of user onboarding process for certain critical services, such as in financial services we need to collect  ID and external links are resulting in 60 drop in conversion.

**Comment by honeybadgerdontcare** [comment]
I'm unaware of a feature pipeline for AMP4EMAIL. @zhangsu do you have any that you can share?

The [documentation](https://amp.dev/documentation/components/amp-form/?format=email) mentions:

(Relaxing some of these rules might be reconsidered in the future - [please let us know](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#make-a-suggestion) if you require these and provide use cases).

In essence submit a specific type of [issue for feature request](https://github.com/ampproject/amphtml/issues/new?assignees=&labels=Type%3A+Feature+Request&template=feature_request.md&title=). In that you can also reference this issue.

**Comment by zhangsu** [comment]
@nainar for the question on roadmap.
