### ISSUE TITLE
"Can't open page" error when accessing story via Google AMP Cache

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amphtml#32038]
## What's the issue?

I'm getting a "Can't open page" error when viewing a story in Google AMP Cache and trying to navigate to the canonical URL.

Originally noticed at https://github.com/HTTPArchive/almanac.httparchive.org/issues/1571#issuecomment-762404247

Similar to https://github.com/ampproject/amphtml/issues/12266

## How do we reproduce the issue?

1. On your iPhone, search for any web story on Google, e.g. by using `inurl:https://almanac.httparchive.org/en/2020/stories/` (but also works for others!)
2. Click on one of the results
3. When viewing the story, click on the "i" icon and then the canonical URL being displayed
3. See `Can't open page' error  
  ![image](https://user-images.githubusercontent.com/10931297/104950017-d86f6b80-59b7-11eb-96a6-bf714a719e18.png)

## What browsers are affected?

Only tested with Safari on iOS so far.

## Which AMP version is affected?

2012301722001

**Comment by gmajoulet** [comment]
@swissspidy can you still repro? It seems to be working for me today.

**Comment by bazzadp** [comment]
I can't repo this now either. Neither in Chrome mobile emulation on desktop, nor on iOS. I was previously able to repo in both.

(I was the one that notice this and reported to @swissspidy btw)

**Comment by swissspidy** [comment]
I can still reproduce it. Even with all possible content blockers disabled.

Tried with the steps above but also by searching for a story from "wp.stories.google" and then going from there.

Using Safari on iOS 14.4

**Comment by bazzadp** [comment]
Actually you're right.

There's two issues:
1. Get that error and error screen. This seems intermittent. Can reproduce on iOS again now quite consistently, but not mobile emulator on Chrome desktop.
2. Get no error but canonical URL does not open and page stays on Google domain. Can reproduce this on iOS and the Chrome mobile emulator on Chrome desktop.
