### ISSUE TITLE
amp-analytics linkers config not working on all web stories links

### ISSUE THREAD

**Issue by travisj** [ampproject/amphtml#32060]
## What's the issue?

I'm trying to share `CLIENT_ID` from amp cache pages to our primary domain. I believe this is the intended use-case for setting `linkers` in the `amp-analytics` config. We have our own analytics package and not using google analytics.

outbound links in the lower 20% of the `amp-story-page` seem to work correctly and the linker id values set in the config work. any links not in the lower 20% that require a click confirmation, however, do not include the linker id data.

## How do we reproduce the issue?

I have only been able to reproduce this with pages served from the amp cache since, i believe, `linkers` only works there.

1. Visit https://www-jumprope-com.cdn.ampproject.org/c/s/www.jumprope.com/g/most-amazing-street-art-in-san-francisco-/IRYTeNmx
2. On the first page, click on "View my profile" at the bottom and see that the linkers data is added to the url on the destination
3. Go back to the first page and click on the username, "thenextsomewhere" in the upper right (it should be the exact same url as the "view my profile link"), but see that once you click the confirmation and go to the user profile page on jumprope.com, the linkers data was not added.
4. Similar behavior happens on the last card, as well.

## What browsers are affected?

i tried on a few different browsers and saw the issue on all i tried:

* chrome mac os
* safari mac os
* safari ios
* google app ios

## Which AMP version is affected?

`2012301722001`

I just implemented `linkers` today, so i'm not sure how long this has been an issue.

**Comment by micajuine-ho** [comment]
Hi @travisj, I see that you have the "linkers" module in the amp-analytics tag, however, you will also need the "cookies" module to read the LINKER_PARAM on origin and write the CID to cookies.

See here for more details: https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/linker-id-receiving.md

**Comment by travisj** [comment]
hi @micajuine-ho, thanks for the response. in some cases these links from our web stories are going to non-amp pages, so i've chosen to parse the `linker` querystring param on the server and use a `set-cookie` header. i have not deployed that to our origin server yet since i am not seeing the `linker` querystring param set on all outbound links from web story pages in amp cache.

**Comment by micajuine-ho** [comment]
@travisj Thanks for the explanation. I'm able to repro the problem now.

It looks like the problem here is that the `<a>` within a shadow doc isn't getting picked up by the navigation service. 

@ampproject/wg-performance Should the navigation service be able to work on `<a>` elements within a shadow doc?

https://github.com/ampproject/amphtml/blob/e2ac9d9b6f98486281d5a25207e10b3b1584127a/extensions/amp-analytics/0.1/linker-manager.js#L124-L134

**Comment by Enriqe** [comment]
Hi @travisj thanks for the report, and thanks @micajuine-ho for chiming in.

We actually have a separate trigger for tooltip clicks called `story-click-through`. Is this what you were looking for?

Read more in the story analytics page: https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/amp-story-analytics.md#tooltip-click-through-trigger-on-story-click-through

**Comment by travisj** [comment]
Hi @Enriqe thanks for looking in to this. I read through the documentation you provided above and I don't think it is what we need. 

If I understand the page correctly, it documents how to trigger events to our analytics when certain story events happen. For example, if we wanted to track how many clicks the `Get App` tooltip on the top of the story received, we could set up our config to trigger on `story-click-though`. the user would go to the link we provided in the `<a>` tag and we'd receive an http request to the url defined in the `request` section. if this is correct, then this is not exactly what we are looking for.

the issue we are facing is that when we set up `linkers` in our `amp-analytics` config, we are not seeing the linkers ids added to outgoing tooltip links. for instance, on [this example page](https://www-jumprope-com.cdn.ampproject.org/c/s/www.jumprope.com/g/most-amazing-street-art-in-san-francisco-/IRYTeNmx), we have two links on the first page that go to the same location. The username at the top of the page and the "view my profile" link at the bottom of the page. If you click on the link at the bottom of the page, you will see that the page you land on has the linkers ids in the querystring. if you click on the username at the top of the page, the tooltip opens and then if you click on that link, you do not get the linkers ids on the following page.

here's a video of the differences in the landing pages when clicking on the two links:

https://user-images.githubusercontent.com/24953/105282933-6779b080-5b7d-11eb-9f35-915626874f9f.mov

**Comment by Enriqe** [comment]
Gotcha, thanks for the detailed description!

Then yes, I believe the story-specific analytics code isn't configured correctly to use the navigation service, like @micajuine-ho was mentioning. I'll take a look at this.

**Comment by gmajoulet** [comment]
> @ampproject/wg-stories Would you be able to forward the <a> or the <a> click to the parent doc?

How does the linker-manager code you linked work and know which links to intercept/apply the linker to? Two questions:
- If we change the navigation to happen programmatically from the JavaScript, will it intercept it and apply the linker?
- If we create a <a> tag on the fly and programmatically trigger it (ie: dispatch ClickEvent), will it intercept it and apply the linker?

Side note: We can only open a link with a `target=_blank` from a trusted user interaction (mostly just `click`). I'm not sure if triggering the navigation programmatically upon that trusted user interaction will work, but it's worth trying.

**Comment by gmajoulet** [comment]
Chatting with @Enriqe, a tentative fix could look like:

1. Listen for click events on the tooltip link in the shadow DOM
2. Create a new <a> tag in the light DOM
3. Trigger a programmatic click on that new <a>
4. Look at if it's intercepted by the linker code
5. Check that it works on Chrome AND Safari (cf target=blank comment I added)

**Comment by micajuine-ho** [comment]
> If we create a tag on the fly and programmatically trigger it (ie: dispatch ClickEvent), will it intercept it and apply the linker?

This was the fix I was thinking of. I think the navigation service should be able to pick up the programmatic click on  new light  tag in the light DOM, and thus trigger the analytics linker callback.

**Comment by gmajoulet** [comment]
Sounds good. We need to make sure it is still considered a trusted user interaction and is not blocked by any browser.
@mszylkowski will look into this soon.
