### ISSUE TITLE
Feature request: Setting the AMP version to a previous release

### ISSUE THREAD

**Issue by devnullzero** [ampproject/amphtml#3208]
I was working on an AMP template when the extension I was using started to trigger errors. It seems that in the meantime, the CDN was serving a new AMP release. I searched for a way the set the script to the previous version to be sure that it wasn't my fault, but didn't find a simple way.

Feature requested: If this isn't already possible, it would be nice to be able to set the release version in the URL to any previous release (https://github.com/ampproject/amphtml/releases), with something like that:

> https://cdn.ampproject.org/v0.js?v=1463071969513

and via the console with something like that:

> AMP.toggleExperiment('1463071969513')

**Comment by cramforce** [comment]
We will not do this, because it facilitates downgrade attacks and if people do it in production, will reduce cache hit rate.

**Comment by cramforce** [comment]
There are other ways to address the: Did this break with the new version question. We should definitely solve that problem.

**Comment by devnullzero** [comment]
A twofold problem:
- Development: Helping finding the reason / bug ... 
- Production: AMP pages don't work anymore. During the window of noticing / reporting / fixing the bug, what should we do?  (Could be quite critical)

We need a roll back feature of some sort. May be the previously released versions could be available for two weeks to a month. In my case (#3207), the change / bug would have rendered the navigation interface completely unusable. 

Also, how to get notified of new warnings / errors on AMP pages. The code isn't under the developers control, so a new version could completely break a web site for a reason or an other.  I don't see myself visiting every web sites and testing each and every features to make sure they are working with the new version... We need a notification system to get developers aware of any problem.

- Any way to get warning / errors directed to an URL for automatic reporting / logging / tracking?
- Google could integrate a reporting tool to Google Webmaster Tools.

**Comment by cramforce** [comment]
Definitely enabling error reporting to the publisher side is a great idea. This would not go through Google Webmaster Tools (AMP is independent from Google).

AMP is making the dev channel available a week before it is pushed and tries it out on 1% of pages. Currently testing can happen in that week. Breakages block the release. Our goal is very much to NOT break existing docs.

If it turns out that the weekly release cycle is too aggressive this could be slowed down, but so far we have not been getting feedback in that direction.
