### ISSUE TITLE
[amp-story-player] Overriding default autoplay behavior on the player

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#32101]
Currently the player decides when to pause / play the first story: it first prerenders it and when it shows up in the viewport it plays it (#31305). We decided on this to improve performance metrics (mainly LCP), and the fact that the player was playing off-screen would mean that users would be missing content by the time they saw the player #29798

We've received several requests to be able to pause the story in the player and only play it when a user clicks on the story or when `play()` is called. https://github.com/ampproject/amphtml/issues/28009#issuecomment-714810375 #31392 #31332 

We should decide what is the best way to support these use cases into an API or consider changing the default behavior.

/cc @ampproject/wg-stories /cc @gmajoulet

**Comment by gmajoulet** [comment]
Good point. We could try to mimick the HTMLMediaElement `autoplay` attribute, but keeping it true by default. Publishers could opt-out by specifying `autoplay="false"`.

**Comment by edoudou** [comment]
As I told @Enriqe on slack, correct me if I am wrong but I understood that the player uses the visible state to pause and play the story. In my opinion, both state should be treated differently, even if they will impact the story in a similar way.

Enriqe told me it was for performance issues, but I am having trouble imagining how this could be so impactful on performance that we prefer to keep a behavior that could (and already have) lead to bugs.

**Comment by edoudou** [comment]
Do you think it is possible to prioritize this ?

Right now, the lack of a good way to disable the autoplay through the player makes it almost unusable for most of our case, as most of the time, our clients prefer to have autoplay on everycard to remind of instagram

**Comment by gmajoulet** [comment]
Of course.

To clarify, the current behavior is:

1. Story is prerendered and not playing on page load
2. When the story gets visible in the viewport, it starts playing
3. If you scroll further and the Story is no longer visible, it's still playing

From what you said, you're okay with (1) and (2), but would want to get more control over (3)?

**Comment by Enriqe** [comment]
Talking with @edoudou through Slack I think the desired behavior is controlling (2), since they use a modal that is visible in the viewport but with `opacity: 0`. So even if the player is "hidden", it is still considered `visible` and will be playing.

They would like to control (2) to only play the story whenever they call `play()` explicitly. 

As a workaround, I suggested applying a `translate3d(0, 100vh, 0)` to move the player just outside the viewport and then just remove the translate to start playing. But after #32115 and #32153 get merged, I think it will be quite easy to add support for this API quite easily.

**Comment by edoudou** [comment]
As @Enriqe said, we used a workaround that work for our main integration right now.

But ideally, it could be great to have a way to prevent (2) as well. 

We are working on an integration where the story can be visible but not the focus of the user yet. It is a not fullscreen iframe that display the story. When the user click on it, it goes fullscreen and start to play. when the user close it, it goes back in the layout of the page and pause itself. 

But right now, even if the user did not interect with the story, it still start playing when entering in the viewport.

**Comment by gmajoulet** [comment]
Thank you both for explaining the use case :)) The API described above should work then, Enrique's plan SGTM
