### ISSUE TITLE
🌸 Cherry-pick request for #32087 into #31929 (Done)

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#32111]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #32087 | #32087 |     **NO**     | **YES** | **NO** | #31929                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

- The PR https://github.com/ampproject/amphtml/pull/31693 is currently in Stable. It replaces our manually computed `IntersectionObserverEntry` with one provided by an actual InOb. Turns out it wasn't backwards compatible.
- When in a x-origin iframe (Viewer), `rootBounds` is always null (https://github.com/w3c/IntersectionObserver/issues/79). Any iframes depending on rootBounds (many ads) will break.
- Some folks have already reached out on Slack.

## Why is a Beta / Experimental cherry-pick not needed?

We are promoting a new 1% Beta that doesn't have the issue.

## Why is an LTS cherry-pick needed?

Bug is not in LTS.

## List the steps to manually verify the changes in this cherry-pick

- Ensure no errors on this page: https://www.google.com/amp/s/amp.usatoday.com/amp/4219616001. Currently getting this:
<img width="519" alt="Screen Shot 2021-01-21 at 4 31 04 PM" src="https://user-images.githubusercontent.com/4656974/105414877-1530a200-5c06-11eb-8e43-49d59b2c200f.png">

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

A switch to using implicit root IntersectionObserver for calculating intersection within LegacyAdIntersectionObserverHost yielded backwards incompatible behavior because of a nuance in the InOb spec. Technically the InOb should have been `root:document` instead of `root:null` so that rootBounds were never null.  Since this wasn't the case, rootBounds were null, which threw exceptions.

## Impact

- All Taboola ads. Ads still rendered, but some 3p analytics code within it was throwing errors when trying to access rootBounds.

## Action Items

- We need ads integ tests here. They should be include viewer. We should ensure the viewer tests are also 3p iframes since those are the most restrictive (and occur on SRP as well). https://github.com/ampproject/amphtml/issues/32222 

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by jridgewell** [comment]
Approved.
