### ISSUE TITLE
amp-sidebar: toggles error out with method not found error

### ISSUE THREAD

**Issue by jmadler** [ampproject/amphtml#3211]
Sample: https://gist.github.com/jmadler/1362e8f66de65add720fe200a0ec7cda

Reproduction steps:

1. Click on "open" button
2. Click on "close" button
3. Click on "toggle" button

Expected behavior:

Menu opens, closes, opens.

Actual behavior:

Nothing.  Console shows errors of "Uncaught Error: Action execution failed: AMP-SIDEBAR toggle: Method not found: toggle" (also open, close)

## What browsers are affected?

Tested on latest Chrome Stable on OSX

## Which AMP version is affected?

Current as of May 12th in dev channel with amp-sidebar experiment enabled

**Comment by erwinmombay** [comment]
thanks for this, i saw this spike last night. was looking into what it was

**Comment by ericlindley-g** [comment]
I can reproduce this bug if I manually toggle the experiment in the console using: "AMP.toggleExperiment('amp-sidebar')" to "false", but it goes away if I toggle back to "true" using the same command

@jmadler is this the case for you, too?

If so, we may just need clearer docs for manually toggling experiments in the console—or a way to avoid having to do the console bit altogether

**Comment by amphtml-team** [comment]
Yup some one is using this on prod while we still have it experimental.
Eric can we pull it out of experimental?

**Comment by ericlindley-g** [comment]
From my perspective, absolutely—I was hoping that it would go out with this week's release. @sriramkrish85, is there anything left to do before this can go out?

**Comment by ericlindley-g** [comment]
Do we know who is using it in prod?

**Comment by sriramkrish85** [comment]
Erwin is flipping the flag to open up the experiment as we speak. This will be a non issue soon !
