### ISSUE TITLE
Refactor placeholder creation by using createPlaceholderCallback

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#3212]
Now that we have #2846 in place. All (except of `amp-youtube` due to a hack that can't be avoided currently) should start using a similar method of `amp-instagram` to create their dynamic placeholders using `createPlaceholderCallback`.

This includes `amp-brid-player`, `amp-jwplayer`, `amp-kaltura-player` and `amp-springboard-player`.

**Comment by dvoytenko** [comment]
@mkhatib Do we have a separate bug tracking YouTube? It'd be great to see the status of our conversations with YouTube to address it in one place.

**Comment by mkhatib** [comment]
@dvoytenko filed #3216 for `amp-youtube`. Will reach out to some of the folks in that conversation and see if we can get a timeline on some of the ideas they shared.
