### ISSUE TITLE
User is sent back to the top of the first article when next page loads

### ISSUE THREAD

**Issue by dmanek** [ampproject/amphtml#32165]
Issue:
When I approach the end of the first article and the start of the amp-next-page article, the user is sent back to the top of the first article.

To reproduce:

Search "CNET" in Google, click on an AMP page from SERP
Scroll to near end of article and into amp-next-page.
Notice that you are thrown back to top of the first article
Demo:

Via iPhone Safari browser: https://drive.google.com/file/d/1WrT03HMOhQ0Oaw2BMbjbtVWyiiKByRxT/view?usp=sharing
Via Chrome Emulator: https://drive.google.com/file/d/1xqu3BaJRXhGr3fT-zuFVT2VrdvZiXCsV/view?usp=sharing

(copies from https://github.com/ampproject/amphtml/issues/31951#issuecomment-760386354)

**Comment by lucamago** [comment]
Hi, this also happens to my sites, any update about this issue?

**Comment by dmanek** [comment]
I spent some time investigating this today. And while I'm able to consistently repro on at least a couple of pages in Chrome & Safari (emulating the mobile view), I'm not able to pinpoint what's causing this. @Cauchon @lucamago would appreciate if you've noticed anything that may help me debug this issue? One thing I've noticed is this only happens once, scrolling after the initial jump does not cause this issue.

**Comment by adops-tcs** [comment]
Hello, this is impacting user experience on our AMP sites.  Is this a new bug? What is the ETA on the fix?  Thank you!

**Comment by Cauchon** [comment]
Hi @dmanek, I haven't noticed anything that might help debug the issue on my end. Have you had any further luck?

**Comment by dmanek** [comment]
Hi @adops-tcs can you share the URL of your site? Also any details to help me debug this issue would be appreciated.

**Comment by adops-tcs** [comment]
@dmanek , here is an example URL: https://www.google.com/amp/s/www.sportscasting.com/kansas-city-chiefs-encouraging-news-patrick-mahomes-health/%3famp

It only happens on the articles on google.com/amp domain. 

It doesn't happen if you go to the same AMP article directly on our site:
https://www.sportscasting.com/kansas-city-chiefs-encouraging-news-patrick-mahomes-health/?amp

Also, it only happens on iOS devices.  thank you!

**Comment by Cauchon** [comment]
Hi @dmanek, we are still seeing the issue after the fix. Seems 100% reproducible on iPhone when viewed from the AMP cache.

**Comment by jridgewell** [comment]
The fix hasn't been deployed yet, it just landed on the master branch.

**Comment by lucamago** [comment]
Hi, when does this fix will become live?

**Comment by paologuarcello8913** [comment]
Hi, this also happens to my sites too. Please solve it.

**Comment by antoyosh** [comment]
Hi, I'm also waiting this fix ASAP, it's hurting our user experience so bad, so please let us know when it will be deployed, thanks!

**Comment by dmanek** [comment]
This should be in the next stable release, expected to completed by EOD tomorrow. Release tracking issue #33224.
