### ISSUE TITLE
Refactor amp-youtube placeholder fallback mechanism

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#3216]
Currently `amp-youtube` can't use the new recommendation of using `createPlaceholderCallback` - see #2846 for some discussion on that.

This is to keep track of this issue because eventually we'd like to get rid of the hack and rely on `createPlaceholderCallback`.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please verify first whether the feature proposal is still relevant.

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)

**Comment by jridgewell** [comment]
This should be possible now with `signals`:

```js
ampImg.signals().whenSignal(CommonSignals.LOAD_END).catch(() => {
  // handle it.
});

**Comment by kristoferbaxter** [comment]
This functionality was moved to `createPlaceholderCallback` in #31822. It continues to use a standard HTMLImageElement given the intent to deprecate `amp-img`.
