### ISSUE TITLE
Cannot get access to the article url for shadow docs

### ISSUE THREAD

**Issue by hjjinnie** [ampproject/amphtml#32188]
## What's the issue?

For publishers using amp-smartlinks and amp-next-page, API requests from the first article are successful, but requests from succeeding pages (which are shadow docs) are failing.

## How do we reproduce the issue?

1. Go to this example publisher page: https://www-purewow-com.cdn.ampproject.org/c/s/www.purewow.com/fashion/leggings-with-pockets?amphtml=true
2. Filter the network requests by "narrativ"
3. Refresh the page
4. You'll see network requests are successful on the first article, but API requests on following articles are failing

## What browsers are affected?

All browsers

## Which AMP version is affected?

The latest version

**Comment by hjjinnie** [comment]
Putting up a PR in the next couple days!

**Comment by micajuine-ho** [comment]
@hjjinnie Thanks for your bug report (and future contribution)! Please tag the @ampproject/wg-components when you submit your PR :D
