### ISSUE TITLE
🌸 Cherry-pick request for #32180 into #32065 (Done)

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#32192]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #32155 | #32180 |     **YES**     | **NO** | **NO** | #32065                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

This is a very isolated fix needed for Bento launch.

## Why is an LTS cherry-pick needed?

It's a Beta cherry-pick and as such will go into Stable and LTS at the natural schedule.

## List the steps to manually verify the changes in this cherry-pick

The https://cdn.ampproject.org/v0/amp-base-carousel-1.0.css is available.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

<_1-2 sentences summarizing the problem and root causes._>

## Impact

- <_Which users were affected? Roughly how many?_>
- <_How were users affected? E.g. partial or complete loss of functionality?_>

## Action Items

- #<_ISSUE_NUMBER_>: <_Add unit/integration/end-to-end test_>
- #<_ISSUE_NUMBER_>: <_Add monitoring for edge case via error logging_>
- #<_ISSUE_NUMBER_>: <_Refactor an easily misused API_>

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by kristoferbaxter** [comment]
Approved.

**Comment by dvoytenko** [comment]
This can now be done. Please do before the Stable release.

**Comment by krdwan** [comment]
Completed!
