### ISSUE TITLE
Rename "master" branch to "main"

### ISSUE THREAD

**Issue by baconjulie** [ampproject/amphtml#32195]
Following up on our discussion in the 1/25 AMP AC Meeting to rename the `master` branch to `main` or a similar name.

**Comment by rsimha** [comment]
Thanks for filing this issue @baconjulie, and for transferring it to `amphtml`, @kristoferbaxter.

I see the renaming guide at https://github.com/github/renaming. This is useful.

Right now, there are a few hundred references to `master` in `amphtml`'s build-system code and our custom app repo `amp-github-apps` combined. In addition, there are O(1000) references in various `amphtml` files. Moreover, our internal release system that works on `amphtml` has a few references too.

While it is possible to change these (and I fully support the sentiment behind making this change), doing so will involve several intricately coordinated steps. Happy to put this on our team's backlog.

@kristoferbaxter Can you comment on the priority this move should get? Would we like to see this happen within days? weeks? a couple months? the end of the year?

**Comment by kristoferbaxter** [comment]
For clarity, the default branch name for `ampproject` at the org level is `main`. This was changed after both `amphtml` and `meta-ac` were created though.

<img width="765" alt="Screen Shot 2021-01-25 at 3 56 12 PM" src="https://user-images.githubusercontent.com/61764/105780715-ec6e1c80-5f25-11eb-9e50-21bb61765749.png">

@rsimha If this was complete within a quarter I'd consider it a success given the different moving pieces. We've held off on doing it too long.

**Comment by rsimha** [comment]
This work has begun, and we are in the process of planning / coordinating updates to the various moving parts. (See [this doc](https://docs.google.com/document/d/1BN8CkM3b2nydENRI2X1tE6nCxcaeVliUIaC2e-mXZbg/edit#).) I'll post a final update here when the transition is complete.

**Comment by tobie** [comment]
Love the design doc!

Do you mind if I share it with the other OpenJSF projects?

**Comment by rsimha** [comment]
> Do you mind if I share it with the other OpenJSF projects?

Not at all. Feel free to share. (The plan is still being reviewed, any necessary updates will be made in the next few days.)

**Comment by rsimha** [comment]
Closing out this top-level issue now that the default branch of `amphtml` and almost every other repo under `amppproject` have been renamed. There are two or three repos left, and their issues are linked above.

**Comment by tobie** [comment]
Amazing. Congrats.
