### ISSUE TITLE
Twitter widgets don't render sometimes

### ISSUE THREAD

**Issue by indianburger** [ampproject/amphtml#3220]
Malte [pinged us on Twitter ](https://twitter.com/cramforce/status/730922514294013952) about Twitter embeds not rendering sometimes - http://output.jsbin.com/zajaxe This I was able to reproduce more reliably (~10%) in mobile safari on the simulator and very very rarely on Chrome Canary. Haven't seen in at all in production Chrome (49), FF (44).

I'm an engineer at Twitter on the widgets team, so I was able to dig in with our source code. Here are my observations and guesses.

It seems to me that it the problem stems from some layout invalidations* not happening. The place in our code where the promise stalls is waiting for the browser to fire onload on a css <link> element. onload doesn't fire because, this is my guess, browser isn't doing a layout invalidation. When you scroll or do other random operations, browser eventually does a layout at some point, which resumes the promise rendering and everything finishes as expected after that (you don't need any mutation observers that in the code).

I have never reproduced this with twitter widgets without the AMP code, so I'm not entirely certain this is something we can fix in twitter widgets code. I'll dig more when I get more time to do this, but I'm open to suggestions. 

* layout invalidations is probably the incorrect term. But you get the idea.

**Comment by cramforce** [comment]
@indianburger just clarifying: You are waiting for onload on `<link rel=stylesheet>` and it doesn't fire?

**Comment by indianburger** [comment]
That's correct. It usually fires, but once in a few times it doesn't. Don't know why.

**Comment by esprehn** [comment]
Please file a bug at crbug.com and we'll follow up. :)

**Comment by cramforce** [comment]
@indianburger Would you mind to file and cc malteubl  at google.com

**Comment by cramforce** [comment]
I found out that if you turn off cross iframe script sharing that the problem goes away

**Comment by cramforce** [comment]
@indianburger I found out what is causing this in Chrome. AMP uses the same Twitter `platform.js` across multiple frames and it just so happens that Chrome throttles the frame that loads it (which is basically a random tweet on the page).

One thing Twitter could do to be more robust about this, is to always be explicit what window to use.

E.g. instead of `document.createElement` do `tweet.ownerDocument.createElement` and instead of `setTimeout` to `tweet.ownerDocument.defaultView.setTimeout`

**Comment by cramforce** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=612272 against Chrome.

This might (or might not) be entirely different from Mobile Safari issue.

**Comment by cramforce** [comment]
Working in AMP was pushed to prod and the Chrome team already landed a fix on their side. We might need to keep the workaround, because Safari has the same bug.
@dvoytenko Could you file a webkit bug?

**Comment by indianburger** [comment]
Forgot to update here. I have filed a Twitter bug internally to use the target node's ownerDocument. There are a lot of references, so it'll take some time to get this out.
