### ISSUE TITLE
 the link in the amp-story-grid-layer  cannot be clicked near the edge of the page

### ISSUE THREAD

**Issue by normanfan** [ampproject/amphtml#32239]
today, I found that I cannot click the link in the red area. How can I solve it. I remember there was no problem long ago!

Is it because of any update that caused this error？

[image](https://user-images.githubusercontent.com/14563140/105984582-4a8d3200-60d5-11eb-922a-dbfbda198c10.png)

 my code like this (this is the example code on the dev documentation)
``` js
<amp-story-page id="vertical-template-thirds">
  <amp-story-grid-layer template="thirds">
    <div class="content" grid-area="upper-third">Paragraph 1</div>
    <div class="content" grid-area="middle-third">Paragraph 2</div>
    <div class="content" grid-area="lower-third">Paragraph 3</div>
  </amp-story-grid-layer>
  <amp-story-cta-layer>
    <a href="https://www.ampproject.org" class="button">Outlink here!</a>
  </amp-story-cta-layer>
</amp-story-page>
```

**Comment by normanfan** [comment]
All click areas close to the edge of the page cannot be clicked

**Comment by normanfan** [comment]
https://github.com/ampproject/amphtml/blob/master/examples/amp-story/cta-layer-outlink.html
the link of this example also cannot be clicked near the left edge of the page

**Comment by Enriqe** [comment]
Hey @normanfan, we actually reserve those areas on the edge of the screen for navigation. This way users won't ever be trapped by buttons if they just want to keep navigating through the story.

Closing this issue, but let us know if you have any other questions.

@ampproject/wg-stories

**Comment by normanfan** [comment]
Can you tell me the exact distance?

**Comment by gmajoulet** [comment]
The `max(48px, 12vw)` distance on each side of the screen is protected and will navigate to the next story page even if there is a link. The area of the link not in the protected zone will still work and trigger the link tooltip though.
This is however not a new behavior, we made the zone a bit larger on tablets (or very large phones), but it's been working this way on mobile phones from the day links were launched.
