### ISSUE TITLE
🌸 Cherry-pick request for #31364 into #32229 (Done)

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#32235]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #31364 | #32232 |     **YES**     | **NO** | **NO** | #32229                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

This is a Beta-only cherrypick. It addresses a long-standing issue for a specific environment (WebView) where testing is complicated. We'd like to test it sooner via Beta channel. It'd go to Stable/LTS via normal rules.

## List the steps to manually verify the changes in this cherry-pick

See #31364.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

<_1-2 sentences summarizing the problem and root causes._>

## Impact

- <_Which users were affected? Roughly how many?_>
- <_How were users affected? E.g. partial or complete loss of functionality?_>

## Action Items

- #<_ISSUE_NUMBER_>: <_Add unit/integration/end-to-end test_>
- #<_ISSUE_NUMBER_>: <_Add monitoring for edge case via error logging_>
- #<_ISSUE_NUMBER_>: <_Refactor an easily misused API_>

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by jridgewell** [comment]
Approved into Beta

**Comment by krdwan** [comment]
Completed!
