### ISSUE TITLE
[amp-story] amp-story-cta layer is not restricted to the bottom 20%

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#32258]
There's a way to circumvent our bottom 20% limits with the `amp-story-cta-layer` by applying `transform: translateY(-Xpx)` and `height`. 

Example: Navigate to the last page of https://www.tiktok.com/amp/tag/salaamalaikum

Expected: `amp-story-cta-layer` should only be in the 20% percent of the screen
Actual: `amp-story-cta-layer` can be in the middle of the screen

/cc @ampproject/wg-stories

**Comment by gmajoulet** [comment]
If we enforce `height` we also need to enforce, from the top of my head: `max-height`, `min-height`, `margin`, `padding`, `border`. Resetting `translate` should be enough to avoid any transform or change width + rotate hack

**Comment by makusnikomi** [comment]
Resetting translate will also conflict with our own animations (e.g. `animate-in="fly-in-bottom"`.

WDYT about, separately from actually enforcing the size, transforming any `<a>` tags to have `show-tooltip="auto"` (or changing the code that intercepts link clicks for that feature to also select `amp-story-cta-layer a`)?

**Comment by gmajoulet** [comment]
Can you add a `animate-in` on the `<amp-story-cta-layer` TAG today?

**Comment by newmuis** [comment]
Yes: https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/validator-amp-story.protoascii#L496

**Comment by newmuis** [comment]
Let's just make amp-story-cta-layer reuse [isInScreenBottom](https://github.com/ampproject/amphtml/blob/558da27cc31ff066f4f3f6da45e331b838ed92ed/extensions/amp-story/1.0/page-advancement.js#L564-L567) or similar.
