### ISSUE TITLE
🌸 Cherry-pick request for #32250 into #32065 and #32229 (Done)

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#32251]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #32246 | #32250 |     **NO**     | **YES** | **NO** | #32065                                                              |
| #32246 | #32250 |     **YES**     | **NO** | **NO** | #32229                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

Critical error: a wrong media query parser was used and now needs to be restored.

## Why is an LTS cherry-pick needed?

I don't think the affected Stable/Beta are in LTS

## List the steps to manually verify the changes in this cherry-pick

This page shows it: https://output.jsbin.com/tideceh. If the page is resized under 500px, the image disappears incorrectly.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

<_1-2 sentences summarizing the problem and root causes._>

## Impact

- <_Which users were affected? Roughly how many?_>
- <_How were users affected? E.g. partial or complete loss of functionality?_>

## Action Items

- #<_ISSUE_NUMBER_>: <_Add unit/integration/end-to-end test_>
- #<_ISSUE_NUMBER_>: <_Add monitoring for edge case via error logging_>
- #<_ISSUE_NUMBER_>: <_Refactor an easily misused API_>

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by kristoferbaxter** [comment]
Approved.

**Comment by dvoytenko** [comment]
PR merged.

**Comment by krdwan** [comment]
Completed!
