### ISSUE TITLE
Create Transformer for AMP Caches and Optimizers defaulting to font-display: optional

### ISSUE THREAD

**Issue by kristoferbaxter** [ampproject/amphtml#32277]
## Describe the new feature or change to an existing feature you'd like to see

1. By default make Google Font usage (since it doesn't contain icon fonts) leverage `optional` font-display.
2. If not specified by page authors, convert font loading to `font-display: optional`.

## Describe alternatives you've considered

Ignore #2 since there is a higher chance of accidentally causing icon fonts to use `font-display: optional`.

**Comment by kristoferbaxter** [comment]
From @cramforce "also consider this"

```
<link href="https://fonts.googleapis.com/css2?family=Montserrat&display=optional" 
    rel="preload" 
    as="style"
    onload="this.rel='stylesheet';
 ```

**Comment by kristoferbaxter** [comment]
Additional thoughts:
1. Move to inline all Google Fonts resources, instead of using `link` with preload conditions.
2. Use `preload` + `onload` configuration for other allowlisted properties.
3. Only configure fonts loaded from Google Fonts as `font-display: optional` since these will never be icon fonts.

**Comment by Gregable** [comment]
I think the first part of this (adding `&display=optional` to Google Fonts) would be a nice Fixit week project. @kristoferbaxter , do you think this is safe to just do or would we need a user experiment to evaluate impact? If the latter, this is probably larger than a fixit week project.

**Comment by honeybadgerdontcare** [comment]
Do we want this to also apply to [Early Access Google Fonts](https://fonts.google.com/earlyaccess)?

These have URLs like: `https://fonts.googleapis.com/earlyaccess/notosansdevanagari.css`

**Comment by honeybadgerdontcare** [comment]
The first part of adding `&display=optional to Google Fonts [/css? and /css2?] is completed in cl/359793844.

**Comment by honeybadgerdontcare** [comment]
Early Access Google Fonts currently do not [support](https://fonts.googleapis.com/earlyaccess/notosansdevanagari.css?display=optional) `display=optional`.

This leaves the other considerations and thoughts. Perhaps those should be broken into individual feature requests with their own priorities.

**Comment by kristoferbaxter** [comment]
Looks like early access fonts do not support any display values.

https://fonts.googleapis.com/earlyaccess/notosansdevanagari.css?display=swap

Perhaps this is a bug on the Google Font API side?

**Comment by honeybadgerdontcare** [comment]
Filed b/181603843 asking.

**Comment by Gregable** [comment]
Dropped priority as all fonts except for early-access are resolved.
