### ISSUE TITLE
Public RSA key returns 404 in AMP

### ISSUE THREAD

**Issue by paraboloidas** [ampproject/amphtml#32272]
## What's the issue?
Yesterday I created a new RSA key and uploaded it into my website:
https://lottodraw.com.au/.well-known/amphtml/apikey.pub

When I'am trying request to update my key in here:
https://lottodraw-com-au.cdn.ampproject.org/r/s/lottodraw.com.au/.well-known/amphtml/apikey.pub
It returns 404 error:

> The requested URL /r/s/lottodraw.com.au/.well-known/amphtml/apikey.pub was not found on this server.

Do I have to wait longer for Google crawler to fetch my key or it might be some server-side problems?

## How do we reproduce the issue?

1. AMP version: https://lottodraw-com-au.cdn.ampproject.org/r/s/lottodraw.com.au/.well-known/amphtml/apikey.pub
2. Key in website: https://lottodraw.com.au/.well-known/amphtml/apikey.pub

## What browsers are affected?

All browsers and all devices.

**Comment by honeybadgerdontcare** [comment]
@paraboloidas The AMP cache serves AMP documents and their related images and videos. It is not expected to serve public keys.

For updating the AMP cache see documentation for [update-cache](https://developers.google.com/amp/cache/update-cache).
