### ISSUE TITLE
Simulate various load order race conditions

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#3228]
The task is to implement **multiple variants** a simple integration test that loads one or two simple extensions (ideally extensions that do not depend on external resources such as `amp-fit-text` or `amp-iframe` with a `srcdoc`) and tests that rendering works as expected. The test should be as simple (and thus stable as possible), but needs to ensure that elements are properly upgraded.

The variants of the test should be different HTML fixtures where each of them differs only in the order they load the JS. JS load order is enforced by using non-async script tags, so that their execution is blocking and order can be controlled.

We need the following variants:

- scripts in header
- scripts in footer (behind all content)
- v0.js loads first
- extension loads first
- v0.js in header, extension in footer

Lets also ensure that this would have caught #3184.

CC @dvoytenko

**Comment by rudygalfi** [comment]
Adding to Backlog
