### ISSUE TITLE
Translate referrer from CCT's new format

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#3229]
Starting M50, CCT reports referrer in the following format:

```
android-app://package-name
```

We may want to translate it into a more canonical URL. E.g. for `com.google.android.googlequicksearchbox` it's `www.google.com`.

**Comment by cramforce** [comment]
I think its enough for the viewer to handle this since they have a mechanism to override the referrer.

**Comment by dvoytenko** [comment]
And if an AMP page is opened in a CCT directly from `cdn.ampproject.org`, are we ok to just passing through `android-app://package-name`?

**Comment by cramforce** [comment]
Yeah. I think that is a feature.
