### ISSUE TITLE
`amp-instagram` placeholder image does not load. 

### ISSUE THREAD

**Issue by rebeccanthomas** [ampproject/amphtml#32309]
## What's the issue?

The placeholder image in the `amp-instagram` component does not load because that endpoint is deprecated. 

## How do we reproduce the issue?

https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-instagram&format=websites&_gl=1*jby4u0*_ga*YW1wLWgxZ0dlRDJjZWk5emRoTmZta3o5U0E.

This issue can be reproduced in the amp playground.
When reloading the page, before the instagram component loads, rather than the placeholder image the following can be seen: 
![image](https://user-images.githubusercontent.com/64608436/106323694-a918f400-622c-11eb-9934-4628a2621939.png)

If this is not initially visible, it should display with a slower network speed. 

Additionally when attempting to reach the placeholder endpoint directly through this link: https://www.instagram.com/p/fBwFP/media/?size=l
The following error can be seen. 
![image](https://user-images.githubusercontent.com/64608436/106324556-3577e680-622e-11eb-8eb1-e889f4c302d8.png)

## Which AMP version is affected?
This issue affects Version 2101211748002 of AMP, it seems to be new since facebook has now deprecated the endpoint we were using before.

**Comment by Beethoven** [comment]
Same as [amp-instagram] Placeholder not loading - The Instagram endpoint (for embed) is deprecated #31474
