### ISSUE TITLE
PR deploy subdomains 

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#32326]
Pull requests are optionally built and uploaded to an accessible endpoint so that reviewers can test/demo a particular change. This serves the built `.js` files in addition to every file under `examples/` and `test/manual`:

```
https://storage.googleapis.com/amp-test-website-1/amp_dist_${BUILD_NUMBER}/examples/
```

This endpoint scheme problematic since it breaks relative paths that are absolute to origin, which would otherwise work on a local server:

```html
<img src="/examples/my-image.png" />

<!-- ✅ OK  http://localhost:8000/examples/my-image.png -->
<!-- 🚫 404 https://storage.googleapis.com/examples/my-image.png -->
```

As a result, a large subset of `/examples` and `/test/manual` pages don't work at all when uploaded by the PR deploy bot.

This proposes **providing every PR build its own subdomain**, eliminating this issue:

```
https://${BUILD_NUMBER}.pr.amp.dev/
```

## Implementation

PR deploys are currently stored on a Google Cloud bucket. Subfolders cannot be accessed by wildcard subdomains, but we may be able to provide an independent frontend:

1. Store build on Google Cloud as done currently. 

2. Set up a wildcard domain (`*.pr.amp.dev`) somewhere ([e.g. a Vercel app](https://vercel.com/blog/wildcard-domains)). This will serve the stored files by build number reference: 

    `https://` **`a1b2c3`** `.pr.amp.dev/` **`file.html`**
    → `https://storage.googleapis.com/amp-test-website-1/amp_dist_` **`a1b2c3`** `/` **`file.html`**

### Fix path references instead

`*.html` files on examples could instead use only relative paths that are not absolute to origin (no leading `/`).

This could be enforced by some form of linter, but that would cause false negatives that are hard to pinpoint:

*   It needs a list of known attributes, like `src` or `data-src`. If a new attribute that references a file is introduced, the checker would let it through incorrectly.

*   References in HTML files may not only occur in attributes but also in custom formats, like an inline `<script>` containing JSON data. Each of these custom formats would need to be known by the check tool.

*   References to files don't only occur in HTML markup. Detecting paths in e.g. JS files would be significantly more difficult than finding attributes in HTML.

It's simpler and less error-prone to provide unique subdomains.

/cc @ampproject/wg-infra

**Comment by alanorozco** [comment]
https://storage.googleapis.com/amp-test-website-1/amp_nomodule_c6d4238865ef15a27b4276d8bf840a248a427e6d/examples/amp-script/todomvc.amp.html


https://amp--nomodule--c6d4238865ef15a27b4276d8bf840a248a427e6d.guava.bar/examples/amp-script/todomvc.amp.html

**Comment by alanorozco** [comment]
An adjacent issue is that `/dist/rtv` is not present on uploaded files, so scripts loaded by the runtime will 404 in any case.

https://storage.googleapis.com/amp-test-website-1/amp_nomodule_c6d4238865ef15a27b4276d8bf840a248a427e6d/examples/amp-script/todomvc.amp.html

![image](https://user-images.githubusercontent.com/254946/106530654-99eeac00-64a1-11eb-9a76-80f9728f0893.png)

https://amp--nomodule--c6d4238865ef15a27b4276d8bf840a248a427e6d.guava.bar/examples/amp-script/todomvc.amp.html

![image](https://user-images.githubusercontent.com/254946/106530607-804d6480-64a1-11eb-9d38-8a7daefb5400.png)

**Comment by caroqliu** [comment]
Could this approach also make it possible to host [server endpoints](https://github.com/ampproject/amphtml/blob/74ddeabaa3e0f545984c0e092059c1c06752bb7a/build-system/server/app.js)? Demos that rely on these don't currently work as PR deploy bot does not actually listen for requests.

**Comment by rcebulko** [comment]
/cc @estherkim directly as she's the Deploy Bot czarina
I think part of the simplicity of the PR bot deployment is that it's essentially just dumping a bunch of files into storage bucket, which keeps retention and deletion and access all extremely simple. Once we want a real server/backend, we have to start thinking about provisioning instances, deploying actual servers, figuring out routing subdomains etc.

I wonder if there's a way to instead have PR Deploy Bot spit out a `gulp serve` command with some flag (ex. `--pr_deployment=amp_nomodule_c6d4...7e6d`) and then have the server
 auto-proxy requests through to those files (I think we do something like this in Storybook). Slightly more work on the part of the reviewer, but would allow almost all server functionality (rewrites, various stubs) without having to change the simple structure of PR Deploy Bot

**Comment by alanorozco** [comment]
> and then have the server
auto-proxy requests through to those files (I think we do something like this in Storybook).

Storybook outputs a bunch of static files and puts them on `examples/`, it doesn't do anything special like proxying.

**Comment by alanorozco** [comment]
@caroqliu I keep going back and forth on server endpoints on my head. This is out of scope for this issue but there are two options:

1. **Host as serverless funcs** somewhere; this requires refactoring the local server somewhat so it works locally and as deployed lambdas but it should be achievable.

2. **Decouple so that server is not required with PR**; obviously you cannot make live changes to server endpoints, but this can be simplified greatly. Either:

    a. Always get results from `localhost`, or
    b. Host the server functions somewhere else to be fetched from localhost or PR deploys.
