### ISSUE TITLE
Intent-to-Remove: Placeholder for amp-instagram

### ISSUE THREAD

**Issue by kristoferbaxter** [ampproject/amphtml#32322]
## Summary

The placeholder image element for `amp-instagram` supports loading a preview image of an instagram post from Facebook's servers. However, on October 24, 2020 the Facebook team stopped supporting the necessary feature to support this.

https://developers.facebook.com/docs/instagram/oembed-legacy

As a result, all placeholder elements currently 404 in the `0.1` version of `amp-instagram`.

## Motivation

The deprecation of the `oembed-legacy` api makes it impossible to support network level requests for placeholder image requests without a per domain access token. See: https://developers.facebook.com/docs/instagram/oembed#getting-thumbnails

## Impact on existing users

Current implementations are already broken on all `0.1` pages using a placeholder, there is no change beyond the broken behaviour added on October 24, 2020 by the API change on Facebook's servers.

## Alternative implementation suggestion for developers using AMP

We can consider using the updated API in `1.0` and allowing document authors to provide an access token. This access token could be used to generate a valid request for a placeholder image. Or even better we could allow document authors to specify their own placeholders for `amp-instagram` in `1.0` and use the updated API on their own server layer.

/cc @ampproject/wg-approvers

**Comment by caroqliu** [comment]
Thanks for filing, Kris! A few notes:
- Should this also be I2R since we will be removing the feature?
- I believe this impacts all instances of `amp-instagram`, since it is not an attribute enabled behavior nor documented in the component behavior on amp.dev. 
- Does the 2-week discussion period still apply if the current behavior of the placeholder is broken anyway? (404 in `0.1`, unimplemented in `1.0`)
- Another approach worth considering could be to use loaders instead of or in the interim before supporting the new API for placeholders? #20237 suggests one was made for Instagram.

**Comment by jridgewell** [comment]
> Does the 2-week discussion period still apply if the current behavior of the placeholder is broken anyway?

I think at this point, removing immediately is acceptable. The feature is completely broken, and wastes network resources trying to load something that won't work.

**Comment by kristoferbaxter** [comment]
Changed title to `Intent to Remove`.

**Comment by Beethoven** [comment]
When can we use new 1.0? Schedule to leave experimental.

**Comment by kristoferbaxter** [comment]
@Beethoven `1.0` is a Bento component, and is available for developer preview. We'd love to hear feedback about how it works for you!

As for when it's available in valid AMP documents? This timeline isn't certain yet.

**Comment by kristoferbaxter** [comment]
This item was discussed at design review and we'll proceed as planned.
