### ISSUE TITLE
`amp-pinterest` expects JSON from Pinterest, gets JSONP, fails

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#32333]
These failures can be seen in the `examples/pinterest.amp.html` example file (also `test/manual/amp-pinterest.amp.html`). It's likely be because the example file is very old (5 years) and most of it hasn't been updated recently. This is likely to be one source of #31463

**Comment by rcebulko** [comment]
![image](https://user-images.githubusercontent.com/6694512/106515022-0d44ed80-64a3-11eb-875e-7be739d9ca94.png)

**Comment by rcebulko** [comment]
Checked amp.dev, it looks like we are still listing this as valid Flickr usage:
![image](https://user-images.githubusercontent.com/6694512/106515388-9d833280-64a3-11eb-9953-5fc97444d611.png)

**Comment by kristoferbaxter** [comment]
@kentbrew This endpoint seems to have changed.

`https://widgets.pinterest.com/v1/urls/count.json?return_jsonp=false&url=http%3A%2F%2Fwww.flickr.com%2Fphotos%2Fkentbrew%2F6851755809%2F&__amp_source_origin=http%3A%2F%2Flocalhost%3A8000`

The `return_jsonp` parameter no longer seems to be respected. Is there an updated endpoint?

**Comment by kristoferbaxter** [comment]
Pinterest was able to fix the issue on their endpoint.
