### ISSUE TITLE
error while using "conrtorls" and "slide" in amp-base-carousel 

### ISSUE THREAD

**Issue by tanyaMel** [ampproject/amphtml#32382]
## What's the issue?

When I try to set prop "controls" in tag amp-base-carousel, amphtml-validator shows `The attribute 'controls' may not appear in tag 'amp-base-carousel'`. This prop exist in [documentation](https://amp.dev/documentation/components/amp-base-carousel/#controls) and in [github](https://github.com/ampproject/amphtml/blob/master/extensions/amp-base-carousel/validator-amp-base-carousel.protoascii).
![image](https://user-images.githubusercontent.com/41072223/106698385-e4d80300-660a-11eb-908f-0e59ae2fbdcf.png)
![image](https://user-images.githubusercontent.com/41072223/106699267-bce99f00-660c-11eb-8ded-bf8b173cf603.png)

Also when I try setting the initial slide using prop "slide" it doesn't work at all:

```
  <amp-base-carousel slide=1 ....>
               .....
  </amp-base-carousel>
```

And with using amp-bind it works not for initial slide but when state value changes:
```
 <amp-state id="initSlide"><script type="application/json">1</script>
</amp-state>
      <button on="tap:AMP.pushState({ initSlide: initSlide + 1 })">Increase count</button>
  <amp-base-carousel [slide]="initSlide" ....>
               .....
  </amp-base-carousel>
```

Could you fix it, please? ^_^

## How do we reproduce the issue?

Just try adding prop  "controls" in tag amp-base-carousel and check amp-page with [any amp-validator](https://amp.dev/documentation/guides-and-tutorials/learn/validation-workflow/validate_amp/).

## What browsers are affected?

All

## Which AMP version is affected?

1.0.34

**Comment by honeybadgerdontcare** [comment]
@tanyaMel while `controls` was added in #31873 that does not make it instantly live. It will be going live some time tomorrow. Validator releases on a weekly basis, typically Tuesday or Wednesday.

If it is still not working for you by Thursday then please reopen.

**Comment by honeybadgerdontcare** [comment]
I'll update this issue when it is live.

**Comment by honeybadgerdontcare** [comment]
This is now live.

Tested on http://validator.amp.dev with

```
<amp-base-carousel
    controls="(min-width: 1000px) always, (min-width: 600px) never, always"
    layout="responsive"
    width="3"
    height="1"
    heights="(min-width: 600px) calc(100% * 4 * 3 / 2), calc(100% * 3 * 3 / 2)"
    visible-count="(min-width: 600px) 4, 3"
    advance-count="(min-width: 600px) 4, 3">
  <amp-img layout="flex-item" src="…"></amp-img>
</amp-base-carousel>
```
