### ISSUE TITLE
Blurry placeholders hides ssr'd hero images

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#32387]
I was wondering why blurry placeholders delay rendering ssr'd hero images. Turns out, placeholder images hide server-side rendered images on load as they define ` z-index: 1;`.

```
.i-amphtml-layout-size-defined>[placeholder] {
    position: absolute!important;
    top: 0!important;
    left: 0!important;
    right: 0!important;
    bottom: 0!important;
    z-index: 1;
}
``` 

Is the z-index really needed here?

Example: https://toolbox-optimizer.glitch.me/blurry-hero.html

```html
<amp-img src="https://unsplash.it/640/480.jpg" width="640" height="480" layout="intrinsic" data-hero="" i-amphtml-ssr="" class="i-amphtml-layout-intrinsic i-amphtml-layout-size-defined" i-amphtml-layout="intrinsic" noloading="">
    <i-amphtml-sizer class="i-amphtml-sizer">
    <img alt="" aria-hidden="true" class="i-amphtml-intrinsic-sizer" role="presentation" src="data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9IjQ4MCIgd2lkdGg9IjY0MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB2ZXJzaW9uPSIxLjEiLz4="></i-amphtml-sizer>
    
    <img class="i-amphtml-blurry-placeholder" placeholder="" src="data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http%3A//www.w3.org/2000/svg' xmlns%3Axlink='http%3A//www.w3.org/1999/xlink' viewBox='0 0 9 7'%3E%3Cfilter id='b' color-interpolation-filters='sRGB'%3E%3CfeGaussianBlur stdDeviation='.5'%3E%3C/feGaussianBlur%3E%3CfeComponentTransfer%3E%3CfeFuncA type='discrete' tableValues='1 1'%3E%3C/feFuncA%3E%3C/feComponentTransfer%3E%3C/filter%3E%3Cimage filter='url(%23b)' x='0' y='0' height='100%25' width='100%25' xlink%3Ahref='data%3Aimage/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAHCAYAAADam2dgAAAA70lEQVR4AQXBu0rDUACA4T/hJNYKFi8YLbhI56LvUHUQcawERMXB53F1cxcHcRRxlLooOimkFWLVUJKStLnnHL9Pe/jzlYFiwQBdgUIjqyRC16mUpCoLxO3VBbLK8bwAy1pmo9WiZs6SpxNkEVEWOSKYjjANg2keMVdfobnahFJjkI5Jy4rhcIywD2xUKXl86tHp7PDrh6jcY62xRN1a5/7uEhHGMUma8PLcI3EHREnMTxjx/fnFyfkx+3u7iFEYkmcZ7a0279c3yCJm87DL6VEXUEjnFSHigKqQ+P0+22c25kwNmU5wXYfG/CLO2wf/O+F28iKls2IAAAAASUVORK5CYII='%3E%3C/image%3E%3C/svg%3E" alt="">
    <img class="i-amphtml-fill-content i-amphtml-replaced-content" decoding="async" src="https://unsplash.it/640/480.jpg">
  </amp-img>
```

//cc @jridgewell

**Comment by jridgewell** [comment]
What do you mean delay here? As soon as the `<img>` loads, we should be transitioning out of the placeholder.

**Comment by sebastianbenz** [comment]
Yes, but that's currently not the case: the placeholder is hidden once runtime has been loaded. You can easily reproduce this by loading the demo page with JS disabled.

**Comment by jridgewell** [comment]
Ahh, see https://output.jsbin.com/bipuvaj (which disables runtime and modifies the CSS rules a bit).

We could either:
1. Disable z-index for `.i-amphtml-blurry-placeholder`
2. Update the format to use `background-image` like https://www.industrialempathy.com/posts/image-optimizations/#blurry-placeholder
   - This is actually necessary for the eventual `<amp-img>` deprecation

**Comment by kristoferbaxter** [comment]
Can we do both?

- 1 quickly to fix the issue as seen.
- 2 within a month or so to not derail the `amp-img` deprecation?

**Comment by jridgewell** [comment]
Currently, we have a transition when the image loads:

https://github.com/ampproject/amphtml/blob/4a434785df9d89fce6ba3a5f725dd3dda475ea39/css/ampshared.css#L35-L38

When image loads, we set `opacity: 0` on the blurry placeholder, and it fades to the real image. If we eliminate the `z-index`, we'll lose the fade. Is that acceptable? If so, I'll make the change to remove it all.

**Comment by sebastianbenz** [comment]
Can we target the animation in a way that only enables it if there's no ssr'd `img`?

**Comment by jridgewell** [comment]
Sure, I'll open a PR.
