### ISSUE TITLE
TcseMotion_AMP Vendor Not available in Ads Vendor

### ISSUE THREAD

**Issue by TcsEmotion** [ampproject/amphtml#32428]
Hi Team,

We developed AMP adapter for TcsEmotion and submitted.We got approved by AMP and added as official vendor.

But our adserver  TcsEmotion not available here https://amp.dev/support/faq/platform-and-vendor-partners/?referrer=ampproject.org. 

Let us know the details we need to modify anything in adapter and submit again.

**Comment by kristoferbaxter** [comment]
@powerivq Is this a timing issue or is there a missing component to automatically add new vendors into the output on `amp.dev`?

**Comment by powerivq** [comment]
@kristoferbaxter It's a manual process right now (https://github.com/ampproject/amp.dev/blob/2c7be2541118b0d4832fcaa85c518db86b653322/pages/shared/data/faq.yaml#L73). I can update it for now and opened another issue (https://github.com/ampproject/amp.dev/issues/5322) to automate it.

**Comment by TcsEmotion** [comment]
Hi @sebastianbenz @powerivq ,
Let us know, anything pending in our side?
Thanks

**Comment by powerivq** [comment]
@TcsEmotion The site has been updated. Closing this issue.
