### ISSUE TITLE
Validator errors, no idea why or how to fix

### ISSUE THREAD

**Issue by polohero** [ampproject/amphtml#3243]
I'm getting the below errors when I run the validator against my website. "http://www.baby-stats.com/homeamp.html#development=1". 

For testing, I've commented out everything in the body so it's just a blank body without anything and it still failed. I've also tried removing everything just in case the comments were causing the issue and still no go. So, I don't believe it to be anything in my page that's causing the issue. But, if it is would anyone be able to tell my why? I'm using Chrome Version 50.0.2661.102 m.

I've copied the boilerplate tags there, so they are exactly as it looks like it's supposed to be as far as I can tell.

Powered by AMP ⚡ HTML – Version 1462999126709
validator.js:351 AMP validation had errors:WB @ validator.js:351(anonymous function) @ validator.js:402f.Sa @ validator.js:335uB @ validator.js:338jB.md @ validator.js:338iB @ validator.js:333
validator.js:351 http://www.baby-stats.com/homeamp.html:11:4 The mandatory text (CDATA) inside tag 'head > style : boilerplate' is missing or incorrect. (see https://www.ampproject.org/docs/reference/spec.html#required-markup)WB @ validator.js:351(anonymous function) @ validator.js:403f.Sa @ validator.js:335uB @ validator.js:338jB.md @ validator.js:338iB @ validator.js:333
validator.js:351 http://www.baby-stats.com/homeamp.html:11:669 The mandatory text (CDATA) inside tag 'noscript > style : boilerplate' is missing or incorrect. (see https://www.ampproject.org/docs/reference/spec.html#required-markup)

**Comment by Gregable** [comment]
The contents of your boilerplate `<style>` tags are slightly incorrect. If you copy the string from here:
https://github.com/ampproject/amphtml/blob/master/spec/amp-boilerplate.md
It'll validate.

Some variants in whitespace and such from the above work, but we are currently stricter than we need to be. There is a separate issue tracking this: https://github.com/ampproject/amphtml/issues/1877
