### ISSUE TITLE
AMP version for LiveBlog article does not update as quickly as the non-AMP version.

### ISSUE THREAD

**Issue by DayneRich** [ampproject/amphtml#32430]
## What's the issue?

Our AMP cache is not updating when Google revisits the page (Even when we manually requesting re-indexing via Google search console and the update cache endpoint). 
o	Ex: When we click through to AMP on Mobile, our Article content isn’t matching the non-AMP mobile experience

## How do we reproduce the issue?

1. Visit our non-AMP instance: https://www.forbes.com/sites/jackbrewster/2021/01/13/trump-impeachment-vote-live-updates/
2. Visit our AMP instance (accessible on Mobile only): https://www.forbes.com/sites/jackbrewster/2021/01/13/trump-impeachment-vote-live-updates/amp/
3. Compare content and time stamps

Important to note that this example is relatively old now so they may show the same content.

## What browsers are affected?

All browsers

## Which AMP version is affected?

This is a new issue

**Comment by honeybadgerdontcare** [comment]
@DayneRich The AMP version shows four validation errors around `style` for `amp-keyframes`. The AMP cache won't serve the current version if it's invalid and if it has an older valid version will serve that honoring expiry headers. Currently the AMP cache is redirecting to the forbes.com origin version.

**Comment by DayneRich** [comment]
Thanks @honeybadgerdontcare !

It looks like at some point these started throwing those errors.
Will let you know if fixing this resolves.
