### ISSUE TITLE
Do not restrict the "form" attribute on inputs inside a form tag

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#32447]
Per - https://amp.dev/documentation/components/amp-form/#not-allowed - the form attribute seems to be restricted
```
<input type=button>, <input type=image> - Most of the form-related attributes on inputs including: form, formaction, formtarget, formmethod and others.

(Relaxing some of these rules might be reconsidered in the future - please let us know if you require these and provide use cases).
```

Usecase

if i have inputs on my form on desktop and use amp-sidebar's toolbar to put it elsewhere on the page at different breakpoints, 
ill need the form to consider these as it's own inputs at all breakpoints. 

(in my site , i am doing some massive filters and they are under one form on desktop and split across 3 sidebars on mobile , they use the toolbar feature to make the inputs and all functioning mechanisms non-redundant)

I think enabling the `form` attribute is not going to cause any content shifts (since developers normally dont target it in their CSS)

**Comment by Gregable** [comment]
I can't imagine any reason allow-listing the `form` attribute on `<input>` elements would be a problem.

I think the correct change would be to add this to the `"input-common-attr"` list [here](https://github.com/ampproject/amphtml/blob/a6e5faf2636fbc157137aaf6be14f5ce24a6d91f/validator/validator-main.protoascii#L2575) as well as add a test.

**Comment by alanorozco** [comment]
This requires additional work to function as expected given behavior implemented in `amp-form`:

Some things [I tried](https://playground.amp.dev/#share=PCFET0NUWVBFIGh0bWw+CjxodG1sIOKaoT4KPGhlYWQ+CiAgPG1ldGEgY2hhcnNldD0idXRmLTgiIC8+CiAgPHRpdGxlPmlucHV0W2Zvcm1dPC90aXRsZT4KICA8bGluayByZWw9ImNhbm9uaWNhbCIgaHJlZj0ic2VsZi5odG1sIiAvPgogIDxtZXRhIG5hbWU9InZpZXdwb3J0IiBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgiIC8+CiAgPHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1vei1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDstbXMtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7YW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGh9QC13ZWJraXQta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtbW96LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1zLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW8ta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUBrZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19PC9zdHlsZT48bm9zY3JpcHQ+PHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOm5vbmU7LW1vei1hbmltYXRpb246bm9uZTstbXMtYW5pbWF0aW9uOm5vbmU7YW5pbWF0aW9uOm5vbmV9PC9zdHlsZT48L25vc2NyaXB0PgogIDxzY3JpcHQgYXN5bmMgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC5qcyI+PC9zY3JpcHQ+CiAgPHNjcmlwdCBhc3luYyBjdXN0b20tdGVtcGxhdGU9ImFtcC1tdXN0YWNoZSIgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC9hbXAtbXVzdGFjaGUtMC4yLmpzIj48L3NjcmlwdD4KICA8c2NyaXB0IGFzeW5jIGN1c3RvbS1lbGVtZW50PSJhbXAtZm9ybSIgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC9hbXAtZm9ybS0wLjEuanMiPjwvc2NyaXB0PgogIDxzdHlsZSBhbXAtY3VzdG9tPgogICAgaDEgewogICAgICBtYXJnaW46IDFyZW07CiAgICB9CiAgICBmb3JtIHsKICAgICAgYm9yZGVyOiAxcHggc29saWQgI2NjYzsKICAgIH0KICAgIHAsIGZvcm0gewogICAgICBtYXJnaW46IDEwcHg7CiAgICAgIH0KICAgIGlucHV0IHsKICAgICAgYm9yZGVyOiAxcHggc29saWQgI2NjYzsKICAgIH0KICAgIGlucHV0LnVzZXItaW52YWxpZCB7CiAgICAgIGJvcmRlcjogMXB4IHNvbGlkIHJlZDsKICAgICAgb3V0bGluZTogMnB4IHNvbGlkIHJlZDsKICAgIH0KICA8L3N0eWxlPgo8L2hlYWQ+Cjxib2R5PgogIDxpbnB1dCBmb3JtPSJteS1mb3JtIiB0eXBlPSJoaWRkZW4iIHZhbHVlPSJSQU5ET00iIGRhdGEtYW1wLXJlcGxhY2U9IlJBTkRPTSIgbmFtZT0icmVwbGFjZS1vdXRzaWRlLWZvcm0iPgogIDxwPgogICAgdmFsdWUtb3V0c2lkZS1mb3JtOiA8aW5wdXQgZm9ybT0ibXktZm9ybSIgbmFtZT0idmFsdWUtb3V0c2lkZS1mb3JtIj4KICA8L3A+CiAgPHA+CiAgICBvbmx5LW51bWJlcnMtb3V0c2lkZS1mb3JtOiA8aW5wdXQgZm9ybT0ibXktZm9ybSIgbmFtZT0ib25seS1udW1iZXJzLW91dHNpZGUtZm9ybSIgdmFsdWU9IjEyMyIgcGF0dGVybj0iWzAtOV0iPgogIDwvcD4KICA8Zm9ybSBpZD0ibXktZm9ybSIgbWV0aG9kPSJwb3N0IiBhY3Rpb24teGhyPSIvZG9jdW1lbnRhdGlvbi9leGFtcGxlcy9hcGkvc3VibWl0LWZvcm0taW5wdXQtdGV4dC14aHIiIHRhcmdldD0iX3RvcCI+CiAgICA8aW5wdXQgdHlwZT0iaGlkZGVuIiB2YWx1ZT0iUkFORE9NIiBkYXRhLWFtcC1yZXBsYWNlPSJSQU5ET00iIG5hbWU9InJlcGxhY2UtaW5zaWRlLWZvcm0iPgogICAgPHA+CiAgICAgIHZhbHVlLWluc2lkZS1mb3JtOiA8aW5wdXQgbmFtZT0idmFsdWUtaW5zaWRlLWZvcm0iPgogICAgPC9wPgogICAgPHA+CiAgICAgIG9ubHktbnVtYmVycy1pbnNpZGUtZm9ybTogPGlucHV0IG5hbWU9Im9ubHktbnVtYmVycy1pbnNpZGUtZm9ybSIgdmFsdWU9IjEyMyIgcGF0dGVybj0iWzAtOV0iPgogICAgPC9wPgogICAgPHA+CiAgICAgIDxidXR0b24gdHlwZT0ic3VibWl0Ij4KICAgICAgICBTdWJtaXQKICAgICAgPC9idXR0b24+CiAgICA8L3A+CiAgPC9mb3JtPgo8L2JvZHk+CjwvaHRtbD4=) on `<input>` elements outside a `<form>` element:

- ✅  Values get collected and serialized for `action-xhr`
- ❌  `data-amp-replace` does not work
- ❌  `.user-valid`/`.user-invalid` classnames are not set

**Comment by Gregable** [comment]
Ah, I didn't realize this would involve more than just a caching change. @alanorozco would this be a runtime wg thing then?

**Comment by alanorozco** [comment]
Likely @ampproject/wg-components

**Comment by camelburrito** [comment]
isn't `data-amp-replace` tied to the input element itself (rather than the form)?

**Comment by alanorozco** [comment]
@camelburrito They probably should be, but they're not at the moment:

https://github.com/ampproject/amphtml/blob/ca438adeefff4e5e53e05a1f052661db70745411/extensions/amp-form/0.1/amp-form.js#L696-L699

There are other selectors that derive from the instance form that cause these issue, my instinct is that they should all probably work by scoping to root and then comparing form id.

**Comment by micajuine-ho** [comment]
> isn't data-amp-replace tied to the input element itself (rather than the form)?

No, `amp-form` finds the input elements that have `type=hidden` and `data-amp-replace`, and then does url substitution. 

I imagine for this to work, we would need a query selector on the document to find all the input elements that are connected to the `amp-form`. Additionally, we might need to consider shadow doc case, for dynamically added elements (via `amp-list` , etc).

Will sync with @alanorozco today to figure out a plan.

**Comment by camelburrito** [comment]
https://github.com/ampproject/amphtml/blob/a6e5faf2636fbc157137aaf6be14f5ce24a6d91f/extensions/amp-form/0.1/amp-form.js#L205 - This already has all inputs in and out of the form , this is probably why the form submission works without a problem.

**Comment by micajuine-ho** [comment]
> - This already has all inputs in and out of the form , this is probably why the form submission works without a problem.

Didn't know about this!

After chatting with Alan, we will plan to support `<input type=form>` elements outside of an `<amp-form>` (which will require a validation change). For `amp-form`, this means that we'll have to find these elements (either using form.elements or query selector on the root). We don't think that shadow doc case should be something to be considered right now. We'll also have to add listeners to these inputs outside of the form and listen for changes on them. We will also take steps to optimize performance by creating a listener delegator that will manage all the listeners and their events for all the `amp-forms` on the page.

We also decided that for now, we will not support `<amp-selector>` outside an `<amp-form>`.

**Comment by camelburrito** [comment]
not supporting for `amp-selector` is fine. but if you eventually want to support it , it should be no harder than piping the `form` attribute to the `<input type="hidden">` here https://github.com/ampproject/amphtml/blob/a6e5faf2636fbc157137aaf6be14f5ce24a6d91f/extensions/amp-selector/0.1/amp-selector.js#L341


But it looks like `amp-selector` takes in a `form` attribute and pipes it in :)

**Comment by camelburrito** [comment]
@micajuine-ho any updates on when we should expect this to launch ?

**Comment by micajuine-ho** [comment]
Just recently got some free cycles, working on it soon.

**Comment by camelburrito** [comment]
any idea when we can expect this PR to be merged  ?
