### ISSUE TITLE
Closure compiler: forbid use of un-imported global functions

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#3244]
This would remove a common case of failure when an import is missed. I don't believe we ever use global functions anyway, instead referencing them off `window` object. If we do need them sometimes, we can define a single externs file with them. This is a very typical and hard-to-catch bug.

**Comment by erwinmombay** [comment]
@cramforce we're probably going to need the externs you wrote in https://github.com/ampproject/amphtml/pull/3223/files to get this working right?

**Comment by cramforce** [comment]
I find it somewhat surprising that this doesn't break yet :)

**Comment by rudygalfi** [comment]
Putting in Backlog, but please change if being worked on now / soon.

**Comment by erwinmombay** [comment]
should be fixed through https://github.com/ampproject/amphtml/pull/3606
