### ISSUE TITLE
amp-iframe content disappear after tab change when using amp-consent 

### ISSUE THREAD

**Issue by lucas-rds** [ampproject/amphtml#32449]
## What's the issue?

When using amp-consent with a amp-iframe inside it (External User Consent Flow), when changing browser tab and focusing the amp page again, the amp-iframe content will dissapear and never show again.

## How do we reproduce the issue?

The bug is reproducible through the playground demo "External User Consent Flow", here: https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fuser-consent%2Fexternal_user_consent_flow

1. Go to playground
2. Select External User Consent Flow
3. Open another tab in your browser
4. Go back into the playground tab
5. Iframe content is missing, never comes back

![](https://github.com/lucas-rds/files/blob/main/playground-amp-bug.gif?raw=true)

Also created a page on jsbin https://jsbin.com/zakazis/1/edit?html,output, steps:

1. Open the page, a map will show ( its not a consent prompt, but the content of the iframe src does not matter, the bug happens with any content ) 
2. Open another tab in your browser
3. Go back into the jsbin page
4. Iframe content is missing, never comes back

![](https://github.com/lucas-rds/files/blob/main/jsbin-amp-bug.gif?raw=true)

## What browsers are affected?

All browsers

## Which AMP version is affected?

All version after 2101211748002. This is the last version without this bug, all versions after that have the bug, which are at the moment of this report:

2102040529000
2101230412003
2102020357000
2101300534001
2101300534000
2101290559000
2101280515000
2101270209000
2101230412002

**Comment by alanorozco** [comment]
This appears to be working properly on 4937457ff before change #31976
