### ISSUE TITLE
amp-social-share custom width / height

### ISSUE THREAD

**Issue by Preen** [ampproject/amphtml#3245]
Is there a reason why it's not possible to set a custom width / height of the amp-social-share? it always defaults to 60x44.

**Comment by erwinmombay** [comment]
to: @mkhatib

**Comment by dvoytenko** [comment]
Definitely sounds like a bug.

**Comment by mkhatib** [comment]
@Preen do you have an example page where this is happening? This example page for [example shows different layout with different width/height](https://amp-mk-1.herokuapp.com/examples.build/social-share.amp.max.html).

**Comment by mkhatib** [comment]
Closing this issue, can't repro.

**Comment by FoxCouncil** [comment]
For people coming to this thread and finding that the example link is broken;

[https://github.com/ampproject/amphtml/blob/master/examples/social-share.amp.html](url)

To get custom dimensions, specify the width and height as attributes to the `amp-social-share` tag eg:
 `<amp-social-share width="42" height="42" ...></amp-social-share>`
