### ISSUE TITLE
amp-story-bookend: Error fetching bookend configuration

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amphtml#32490]
## What's the issue?

With a bookend configuration like follows I'll get console errors like this:

> [amp-story-bookend] Error fetching bookend configuration Cannot read property 'reduce' of undefined

Markup (transformed AMP):

```html
<amp-story-bookend layout="nodisplay" class="i-amphtml-layout-nodisplay" hidden="hidden" i-amphtml-layout="nodisplay">
	  <script type="application/json">
	  {
		    "bookendVersion":"v1.0",
		    "shareProviders":[
			      {"provider":"facebook"},
			      {"provider":"twitter"},
			      {"provider":"linkedin"},
			      {"provider":"email"},
			      {"provider":"system"}
		    ]
	  }
	  </script>
</amp-story-bookend>
```

Related, but with different error message: #15669

## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. Visit [this story](https://wp.stories.google/stories/intro-to-web-stories-storytime/)
2. Go to last page
3. See console error

## What browsers are affected?

All browsers

## Which AMP version is affected?

2101230412005

**Comment by Enriqe** [comment]
Just checked and this is caused by not having a `"components"` property in the config, adding an empty array of `"components": []` should fix it.

We can use this issue to provide a better error message.

**Comment by gmajoulet** [comment]
Downgrading to P3 as the bookend is deprecated.
