### ISSUE TITLE
amp-sticky-ad maximum height

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#3250]
The current amp-sticky-ad max-height does not take viewport height into calculation and is set to 100px all the time. 
When orientation changes, the current amp-sticky-ad max-height doesn't change. Is it supposed to work like this? 
>>The height can be specified as long as it is less than 1/6th of the viewport (in portrait mode) or 100 pixels (whichever is smaller).

**Comment by rudygalfi** [comment]
Putting in Backlog for now, but please update if being worked on now/soon.
