### ISSUE TITLE
Tracking issue for Bento component performance analysis on AMP documents

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#32523]
## Summary

This is a tracking issue for `experimentC` channel in `experiment-config.json` to measure the performance impact of Bento components on valid AMP documents. 

## Background

[Bento](https://amp.dev/documentation/guides-and-tutorials/start/bento_guide/?format=websites) is an experimental AMP feature which aims to extricate AMP components from the AMP runtime. A couple corollaries of this effort include:
- Bento components should be self-contained and independent of the runtime.
- Bento components will be usable in a larger set of environments, including non-AMP HTML documents and Preact/React development contexts. 

Currently there are [16 Bento components](https://amp.dev/documentation/guides-and-tutorials/start/bento_guide/?format=websites#available-bento-components) available in dev preview, and in the short term they still rely on v0.js. This experiment seeks to answer:
- What is the expected performance of an AMP page with a Bento component on it?
- How does the performance of an AMP page with a Bento component compare against an AMP page with that component's 0.1 (classical AMP) counterpart?

## Potential uses for Experiment channel

Note: All such changes will be exclusive to the web format and will not impact browsers which do not support shadow DOM.

- Auto upgrade 0.5% of instances of a Bento component's 0.1 counterpart to its Bento 1.0 version to extrapolate an expected performance impact of version-bumping the average Bento component.
- Inject an unused Bento component into a 0.5% of AMP documents to extrapolate an upper bound of potential performance degradation. We will not be using the channel to do this at this time since it is expected to only have a negative impact on AMP document performance.

## Candidates for auto upgrade

  - `amp-fit-text` is a good average case candidate and has a straight forward upgrade path. 
  -  Carousels are the largest of the Bento components so far and would provide a good worse-case-scenario understanding of impact for version upgrades. However the [upgrade path is non trivial](https://docs.google.com/document/d/1M2QtxqybIW4j8j3mMBRPs3uqDl9YbUYyYns5TZxyLm0/edit?usp=sharing&resourcekey=0-wbp8H_tF9WMnug7RPrXIkw) depending on the version and component so will not be pursued out of an abundance of caution.
  - Lightbox and Sidebar are not good candidates for this experiment given their lack of history manipulation conformance in the new versions.

## Next steps
- [x] Claim `experimentC` channel in `experiments-config.json`
- [x] Define `upgradeCallback` in `amp-fit-text:0.1` to instantiate `amp-fit-text:1.0` if the experiment is enabled and shadow DOM is supported.

**Comment by dvoytenko** [comment]
Approved on behalf of @ampproject/wg-approvers for RTV experiment.

**Comment by caroqliu** [comment]
Update: Exp. C is now available to compare to Experimental and Beta (1% traffic) as `122102130314001`
