### ISSUE TITLE
Validator is not supporting amp-sticky-ad

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#3253]
The AMP Validator is not supporting amp-sticky-ad that was added from [here](https://github.com/ampproject/amphtml/pull/3119)

## How do we reproduce the issue?

https://github.com/ampproject/amp-by-example/blob/sticky-ads/src/20_Components/amp-ad.html
When running the page with #development=1 I get the validation error. (The tag 'amp-sticky-ad' is disallowed.)

## What browsers are affected?

Chrome

## Which AMP version is affected?

1463506087793

**Comment by Gregable** [comment]
@erwinmombay , is this spec ready for validation?

**Comment by cramforce** [comment]
Yes, @zhouyx for details.

**Comment by Gregable** [comment]
It would be best if someone could draft some documentation for this one: https://github.com/ampproject/amphtml/blob/master/extensions/amp-sticky-ad/amp-sticky-ad.md

**Comment by zhouyx** [comment]
will work on that

**Comment by Gregable** [comment]
Thanks!

**Comment by jridgewell** [comment]
Closed by #3547.
