### ISSUE TITLE
🌸 Cherry-pick request for #32323 into #32408 (Pending)

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#32562]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #32323 | #32355 |     **YES**     | **NO** | *NO** | #32408                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

Breaks video playback in stories.

## Why is a Stable/LTS cherry-pick needed?

This was already cherrypicked to stable in #32360

## List the steps to manually verify the changes in this cherry-pick

<_TEST_STEPS_>

1. Make the change of #32355 in amp-video
2. Go to a story with more than 8+ videos (https://www.vice.com/stories/making-20k-a-month-selling-street-cocktails/ or http://localhost:8000/examples/amp-story/videos.html
3. Verify the 9th video plays.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

<_1-2 sentences summarizing the problem and root causes._>

## Impact

- <_Which users were affected? Roughly how many?_>
- <_How were users affected? E.g. partial or complete loss of functionality?_>

## Action Items

- #<_ISSUE_NUMBER_>: <_Add unit/integration/end-to-end test_>
- #<_ISSUE_NUMBER_>: <_Add monitoring for edge case via error logging_>
- #<_ISSUE_NUMBER_>: <_Refactor an easily misused API_>

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by kristoferbaxter** [comment]
Approved.

**Comment by micajuine-ho** [comment]
CP is complete.
