### ISSUE TITLE
Save additional consent string to AMP-STORE

### ISSUE THREAD

**Issue by mxdvl** [ampproject/amphtml#32588]
## What's the issue?

We’ve noticed that the `addtlConsent` is missing from `consentMetadata` in the saved local storage, even though it comes through the `window.postMessage.payload` from an `amp-consent` configured with remote.

We think it might be related to #31998.

## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. Navigate to https://amp.theguardian.com/stage/2018/aug/07/user-not-found-review-traverse-jeelie-piece-cafe-edinburgh in Europe, so you’re in the TCFv2 framework
2. Accept all cookies purposes by clicking “Yes, I’m happy”
3. Inspect console to see `-- AMP Posting Message --`, which contains the `consentMetaData`.
4. Inspect the local storage (`atob(localStorage['amp-store:https://amp.theguardian.com'])`) to see `consentMetaData` is missing.

## What browsers are affected?

Tested in: 

- Chrome 88
- Safari 14
- Firefox 86 (Developer Edition)

## Which AMP version is affected?

It’s never worked. We’ve started looking into it since early January 2020.

cc. @guardian/commercial-dev

**Comment by micajuine-ho** [comment]
@mxdvl Would you mind doing a screen recording of the issue and posting here?

**Comment by mxdvl** [comment]
Here‘s a screen recording:

https://user-images.githubusercontent.com/76776/107700449-7f78b780-6c85-11eb-9999-92af274b38a7.mp4

**Comment by micajuine-ho** [comment]
What is the value in that local storage key before you 'accept' the consent UI?

**Comment by mxdvl** [comment]
This is done from an incognito window, so `localStorage` is completely empty. Clicking “accept” is what triggers it. It doesn’t change from that point on.

**Comment by micajuine-ho** [comment]
I see. Would it be possible to create a demo page, where consent is always required, rather than just in EU?

**Comment by mxdvl** [comment]
Sure, here’s that demo page: https://guardian-amp-tests.netlify.app/stage/2018/aug/07/user-not-found-review-traverse-jeelie-piece-cafe-edinburgh

**Comment by micajuine-ho** [comment]
Hi, the problem here is that you are passing `addtlConsent` in the `metadata` object instead of `additionalConsent` https://github.com/ampproject/amphtml/blob/master/extensions/amp-consent/integrating-consent.md#consentmetadata

Should work after that fix.
