### ISSUE TITLE
Encourage AMP Email usage of data-css-strict

### ISSUE THREAD

**Issue by honeybadgerdontcare** [ampproject/amphtml#32587]
Currently the AMP Email format is permissive on it's CSS usage. However, email providers will restrict CSS usage for various privacy and security reasons including those that are allowed by the validator. As a result, AMP Email document creators may be including CSS that will not work when received by email providers.

To remedy this a new restricted usage of CSS was put in place when the attribute `data-css-strict` is on the `html` tag. AMP Email document creators are not necessarily using this new attribute to ensure they're using allowed CSS. To encourage that usage there will be a warning for AMP Email documents without the `data-css-strict` attribute. This warning is stated as follows:

`Tag 'html' marked with attribute 'amp4email' is missing the corresponding attribute 'data-css-strict' for enabling strict CSS validation. This may become an error in the future.`

/cc @ampproject/wg-amp4email @ampproject/wg-caching 

See cl/356542320.

**Comment by Gregable** [comment]
@ampproject/wg-amp4email 

This exists as a warning already. It seems there is an amp.dev documentation issue outstanding, but what would be the next steps. From the validator, we can only make it an error (or not). If we'd like to leave this as a warning indefinitely, then perhaps we can just close this remaining github issue. If we want to make it an error, I'd like to know what pre-steps we should take: is there an announcement list, a date, etc?

**Comment by zhangsu** [comment]
SGTM to close this and leaving it as a warning, as there's another issue tracking the documentation.
