### ISSUE TITLE
[amp-story-player] Add swipe down to close the player

### ISSUE THREAD

**Issue by edoudou** [ampproject/amphtml#32580]
## Being able to allow swipe down to close the story
As on instagram, the user should be able to close the story through a Swipe down gesture.

We should implement events to allow this :
- an event that triggers when swipe down starts (like a `touchStart` event)
- an event that triggers when the swipe moves, with data about the progression of the swipe (like a `touchMove` event)
- an event that triggers when the swipe ends, with a `shouldClose` boolean set to true if the swipe was bigger than a certain threshold. (like a `touchEnd` event)

That way editors could implement their own animation based on the data they get from those events

## Additional context

Attention points :
- Swipe down should be an option, as it makes no sense if the player is integrated in the page layout and not as a modal.
- If swipe down is activated, touchEvents should not scroll the page behind.
- The close threshold could be configurable.

**Comment by newmuis** [comment]
AFAIK this should already work in viewers that provide the `#cap=swipe` fragment parameter on the story URL.  It's documented [here](https://github.com/ampproject/amphtml/blob/06123ab062b2be8d04bdb3e232c7c02a8cffe09b/extensions/amp-viewer-integration/CAPABILITIES.md).

@Enriqe can you check if that's true by manually adding that param to stories in a player?

If so, we should:

1. Document this (and other?) capabilities in the player documentation
2. Provide a way for the player to specify a list of capabilities through our DOM or JSON API, so that you don't need to manually append viewer params to the story URLs.

**Comment by Enriqe** [comment]
@newmuis yeah, the `<amp-story-player>` adds the `#cap=swipe` to each story url that it contains. We actually already use these events for swiping / scrolling.

The problem is that the touch events are only passed from the story document to the player via the messaging library (post messages), so they still need to be propagated from the player to the DOM.

**Comment by edoudou** [comment]
The touch events are indeed passed through, I already tried using them to create a swipe down in our code base, and I was confronted to 2 major problems :

- There are not formatted by the player and so are concurrent to the swipe to next feature : Once the swipe down is detected, swipe to next/previous should be disable. When the swipe to next/previous is detected, swipe down should be disabled ?
I managed to overcome the problem using thresholds to know when to start or not the swipe down, but as it is not coming from the player, which mean if there is a change to the swipe in the player it might not work as well.

- The second problem is that when you swipe down on a story that is in an overlay in fixed position, it scrolls the page behind (and it even scroll faster than usual). I don't have the time to make you a code sandbox with our code base (but I could take the time if the following isn't enough), but here is a simulation : https://ho0xf.csb.app/ . Try opening it on a phone and swiping up and down.

If you have solutions for both this problems, I agree with you that we already have all the keys in our hands.

**Comment by edoudou** [comment]
For the scroll issue, we currently lock the scroll in the page behind to the top, as it is not visible while the story is open, but we can't do that is we want to display the page behind the story during the swipe down animation.

**Comment by Enriqe** [comment]
Yep, you are right. The player has a mechanism which scrolls the page when a vertical swipe is detected. This way users don't get stuck when scrolling through a page that embeds a player. 

Summing up these points I think we could make this FR work by:
* Introducing an option to disable page scrolling.
  * Vertical swipes would still disable swipe-to-next/previous actions.
* Dispatch the touch events (`touchmove/start/end`) as DOM events for consistency with other player events and easier parsing & documenting.

Would this work for your case @edoudou ?

**Comment by edoudou** [comment]
@Enriqe ok, I understand best why there is this scroll behavior.

An option to disable this scroll behavior could indeed fix our problem.

For the 2nd part, I'm not sure how this would help, however it would make the events more consistent. IMO we would need an event to be fire when a swipe (or a `touchMove`) is being detected as a vertical swipe (and used for swipe to next/previous) or when it is detected as an horizontal swipe (and so will not be used for swipe to next/previous). That way we can be sure a swipe will not be used as a swipe next and a swipe down as the same time.

I noticed you tagged it as a P2, would it be possible to make it a P1 ? If the amp-story-player code base refactor is ended and the codebase ready for those features, we might be able to make a PR.

**Comment by edoudou** [comment]
For the swipeEvent, I think you already have everything you need in the codebase.

There is already a state that track this : `touchEventState_.isSwipeX`

If I understand correctly the code, we would just need a event to notify when this state is set as `true` or `false`. Could you confirm this @Enriqe ? Maybe the event could also notice when the state goes back to `null`, but this is not required as we can track the `touchEnd` event.

**Comment by Enriqe** [comment]
To my second point, if we sent these events as DOM events, we could attach extra information that is useful for developers using the player. e.g. we could attach the `isNavigationalSwipe` (`isSwipeX`) to the DOM event, which you could use to know whether you should use a `touchmove` event for the swipe down or ignore it.

An example would look like this:

```javascript
playerEl.addEventListener('touchmove', (event) => {
  if (event.detail.isNavigationalSwipe) {
    // Ignore when swiping to next story.
    return;
  }

  // Start closing the player.

});
```

I have a working demo here https://temp-player.web.app/examples/amp-story/player-touchevents.html

if you add the following event listeners to the player element:
```javascript
playerEl.addEventListener('touchstart', (event) => {console.log('touchstart', event);});
playerEl.addEventListener('touchmove', (event) => {console.log('touchmove', event);});
playerEl.addEventListener('touchend', (event) => {console.log('touchend', event);});
```
you'll start receiving the events and the page won't scroll (page scrolling is off for this demo). 

Is this something that would work for you? if so i have some working code I could send out soon.

**Comment by edoudou** [comment]
Ok, I am taking a look

**Comment by edoudou** [comment]
Ok so in a general this seems great !!

The no scroll behavior is perfect.

For the `isNavigationalSwipe` details, it is working well, just a little trick : 
I changed your code a bit to : 

```js
player.addEventListener("touchmove", (event) => {
    if (
      event.detail.isNavigationalSwipe ||
      event.detail.isNavigationalSwipe === null
    ) {
      // Ignore when swiping to next story.
      return;
    }

    // Start closing the player.
    
});
```

as touchMove trigger once with `event.detail.isNavigationalSwipe`, when it is not clear if it is navigation or not yet.

**Comment by edoudou** [comment]
I tested in a codesandbox, I'll test with our codebase to be sure.

Here is the codesanbox : https://codesandbox.io/s/festive-taussig-vvh5o?file=/index.html:602-927

**Comment by edoudou** [comment]
@Enriqe everything LGTM.

I manage to have a working demo of our swipe down, even on a scrollable page : https://jyujv.csb.app/

It is still a WIP but it proves we have everything we need if we can disable scrolling + get information on the swipeNavigation State.

When do you think this features could be available in stable ?

**Comment by TheWizardofWikacy** [comment]
Thanks for this.  I was able to use it with a neat animation:)

https://bookboostpro.magicbooks.io/
