### ISSUE TITLE
AMP-Form - type email validated with wrong format

### ISSUE THREAD

**Issue by greghuet** [ampproject/amphtml#32633]
Hi,

Using AMP Form, I have found that if you enter a wrong format email address (missing the domain extension), AMP does not return an alert. To test go to:
https://amp.dev/documentation/examples/components/amp-form/

In the test form, enter the email address testtesttest@gmail without .com at the end.

Hope you'll find a fix.

**Comment by micajuine-ho** [comment]
Hi @greghuet, thank you for your issue report. 

However, in this case amp-form is following the MDN standard of what constitutes a valid email: 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email#value

If you'd like to see a change made, I'd recommend reaching out to standard committee to try to change this validation, or add a `pattern` field in your input element https://amp.dev/documentation/components/amp-form/#verification.
