### ISSUE TITLE
Observe Intersection and nested AMP documents.

### ISSUE THREAD

**Issue by JoelRegus** [ampproject/amphtml#3265]
If an amp-ad element exists within an AMP page that is served within an iframe, the data returned from observeIntersection will be relative to the iframe, not the parent document.

This makes sense, however it posses an issue when measuring viewability.

For example, the ad on this page is always going to be in view:

http://dfp-amp-testing-1185.appspot.com/amp_tests/dfp-image-layouts-fixed.html

Is there a way for the amp-ad element to know if it is being served within a nested AMP environment? This could help us decide if we should use the data returned from observeIntersection when making our viewability calculations.

**Comment by cramforce** [comment]
Good point. As we formalize the viewer API we will need to require viewers to supply their own change records down to us. The current viewport implementations should, to some extend handle this already.

CC @dvoytenko

**Comment by dvoytenko** [comment]
Right now we require AMP to be sized to the whole viewport (`top = 0; left = 0; right = 0; bottom = 0`) and provide offsets in the form of padding. This however, is purely the initial implementation choice and we will likely add more API to support more complicated cases.

**Comment by jasti** [comment]
@chenshay, is this something the viewer API already passes down to the ad? Just trying to understand priority.

**Comment by jasti** [comment]
Ping @chenshay

**Comment by lannka** [comment]
we already supports a window.context API to track view-ability: https://github.com/ampproject/amphtml/blob/master/ads/README.md#ad-viewability
