### ISSUE TITLE
amp-story-auto-ads not Showing AdSense Ads in Desktop & iOS

### ISSUE THREAD

**Issue by abhiz10** [ampproject/amphtml#32653]
I can't see the Adsense Ads in Desktop view. I have implemented the code as per the guidelines given in [Monetize your Web Stories](https://support.google.com/adsense/answer/10175505) 
Please the implementation once ~ https://travel.visualstories.com/canada-fun-interesting-facts

and also after Implementing AdSense getting a warning in the console [#31606 ](https://github.com/ampproject/amphtml/issues/31606) please check this concern too.

**Comment by abhiz10** [comment]
@processprocess Is there any update on the above concern?

**Comment by Enriqe** [comment]
@calebcordry can you take a look please?

**Comment by calebcordry** [comment]
Hi @abhiz10 as this is a new product there is limited demand right now, and as you are seeing it is mostly for mobile android. If you are seeing android ads thats good, it should mean you have everything set up correctly. I also saw an ad on your demo page. We should have more demand online soon that will help fill ios & desktop, but for now I think everything is WAI. Feel free to reopen if I missed something.

**Comment by abhiz10** [comment]
@calebcordry Thanks for the Update.

**Comment by abhiz10** [comment]
@calebcordry I hope this is the same issues we discussed https://github.com/ampproject/amphtml/issues/34115
