### ISSUE TITLE
amp-story-player: Loader visible after story is loaded

### ISSUE THREAD

**Issue by rnkimani** [ampproject/amphtml#32666]
## What's the issue?
- Loader is still visible after story is rendered.

## How do we reproduce the issue?
- Inspect [here](https://tappable-sdk.web.app/test.html)

- My current approach: So what's happening there is the story is being served as an iframe in a web component. 
So it's rendering something like

```javascript
<web-component>
    #shadowroot 
  <iframe src="url with amp player config" >
      #document  
       ....
      <amp-story-player >
         ....
        <a href="" />
        ....
      </amp-story-player>
   ....
   </iframe>
</web-component>
````

## What browsers are affected?
- all 
## Which AMP version is affected?
- latest
cc @Enriqe

**Comment by nickFalcone** [comment]
Hi @rnkimani, I can see this behavior on the link you shared. 

However, I wasn't able to reproduce with `<amp-story-player>` alone. I made a quick [demo](https://raspy-faint-hub.glitch.me/) including an embedded AMP story (source https://glitch.com/edit/#!/raspy-faint-hub).

It looks like the spinner visibility is set by [amp-story-player.css](https://github.com/ampproject/amphtml/blob/a6fe54bce399d39a66a68016b7f7db0d7c9f6626/css/amp-story-player.css#L39). 

In both of our pages, I see `<amp-story-player class="i-amphtml-story-player-loaded">`. This class should hide the spinner.

```css
.i-amphtml-story-player-loaded::after {
  visibility: hidden;
}
```

I am not familiar with Tappable, but I saw an Olympic logo on their [product page](https://tappable.co/product) which displays an AMP Story. The spinner was hidden as expected. 

Perhaps someone from Tappable or the [AMP Stories Working Group](https://amp.dev/community/working-groups/stories/) could offer more insight?

**Comment by rnkimani** [comment]
Yeah. I'm working on the Tappable end.

**Comment by Enriqe** [comment]
Are you importing the right CSS script for the player? I inspected the CSS you're using in your demo and it doesn't match the [required script](https://github.com/ampproject/amphtml/blob/master/spec/amp-story-player.md#-amp-story-player).

Your demo's CSS:
![image](https://user-images.githubusercontent.com/5449100/108274803-653a5000-7143-11eb-810e-fd1eda37b712.png)


As @nickFalcone mentioned, the CSS is responsible for hiding the spinner once the player is loaded. This part is missing from your stylesheets for some reason:
https://github.com/ampproject/amphtml/blob/6196c72e4eab7b4baad682e94c7f6c3ef7131676/css/amp-story-player.css#L68-L70

**Comment by rnkimani** [comment]
Yes. It was being purged. Thanks :)
