### ISSUE TITLE
Empty Cookie issue

### ISSUE THREAD

**Issue by footpathsfaded** [ampproject/amphtml#32670]
Hello team,

I am not an expert at code, so I need a simple answer.

I believed until today that your AMP plugin does not use cookies.

On Chrome when I opened the link (https://topelectricsuv.com/news/hyundai/hyundai-bayon-gdi-engine-amt/amp/) and in the address bar when I clicked on the Lock symbol, I get (1 in use) next to Cookies, and when I explored that, I find that there is “Local Storage” option and within it my website URL. But when I click on it, it appears empty (please do test this in your own Chrome browser).

When I load the same page in the non-AMP mode (just removing the /amp from the URL) you can see that the site does not use any cookies.

We haven’t enabled any special options exclusively for the AMP page, only changed the stylesheet to change the font style and colours. We have also tried disabling all plugins and switching to the Default AMP theme and still the '1 Cookie' won't disappear.

I contacted the Plugin Support team in Wordpress site, and they said "The empty cookie may be added by AMP script or component" Here's the response - https://wordpress.org/support/topic/about-local-storage/#post-14053567

Could you please provide me what the problem here is?

**Comment by alanorozco** [comment]
Hi @footpathsfaded 

AMP may use Local Storage for features like navigation history management, paywalls and analytics, for example. [Most usages are listed on this search result page.](https://github.com/ampproject/amphtml/search?q=storage.setItem)

Your website doesn't appear to use any of these features, but AMP may try reading (non-existent) Local Storage values to detect them. By only trying to read (`getItem()`) [a Local Storage entry is created](https://output.jsbin.com/yezojimovo) (thus empty).
