### ISSUE TITLE
FR: Search AMPs.

### ISSUE THREAD

**Issue by hemanth** [ampproject/amphtml#3267]
It would be great to have a place where I can search all the AMP components, I am more than happy to do a PR ;)

**Comment by jridgewell** [comment]
What exactly do you mean? We do have all our components on in https://github.com/ampproject/amphtml/tree/master/extensions (hopefully with a description in the README there).

**Comment by hemanth** [comment]
@jridgewell Something like [this](http://yeoman.io/generators/)

**Comment by cramforce** [comment]
CC @pbakaus @sebastianbenz

**Comment by pbakaus** [comment]
yep I think that'd be awesome! A PR on the docs repo (https://github.com/ampproject/docs) would be pretty sweet. Have a look how things are setup and let me know if there are any questions.

@cramforce not sure if there's a way to move an issue? Or should we reopen one in the docs repo?

**Comment by cramforce** [comment]
New issue and just reference them each other.
