### ISSUE TITLE
[Story responsiveness] Set overflow to visible on preset layers

### ISSUE THREAD

**Issue by mszylkowski** [ampproject/amphtml#32678]
Currently on grid-layers, the CSS is set to overflowing elements are hidden. With presets, we want to encourage publishers to position items partially outside the preset layer so it can fill the margins properly.

We can consider setting `overflow: visible` on only preset layers or all layers, which will impact all stories but could be benefitial in most cases.

https://github.com/ampproject/amphtml/blob/6b91fcb8e4aa86fa863b06651b9c23d9a6e77cdb/extensions/amp-story/1.0/amp-story-user-overridable.css#L21-L23

@ampproject/wg-stories

**Comment by gmajoulet** [comment]
Can you link to the code that sets `overflow: hidden;` on the `grid-layer`s?
My understanding of our code was that `amp-story-page` had `overflow: hidden;`, but not `grid-layer`, for the very reason you mentioned. I think people from the WordPress tool asked for this a while ago but it was already how it works.

**Comment by mszylkowski** [comment]
It's in user-overrideable which is a good idea that others can override, but we shouldn't have that as the default on `preset` layers for the reasons mentioned above (and maybe on all layers?). Linked the code in the description of the PR.
