### ISSUE TITLE
amp-story-ads.md out of date

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#32680]
This seems out of date:

> Google AdSense coming soon

https://amp.dev/documentation/guides-and-tutorials/develop/advertise_amp_stories/

Pointed out by WP support rep Lucky.

/cc @ampproject/wg-stories

**Comment by gmajoulet** [comment]
cc @calebcordry could you help us with some actionable steps to fix this? Thanks!

**Comment by calebcordry** [comment]
Thanks for the catch!
