### ISSUE TITLE
❄️ Fix flaky visual diff test `amp-story: basic`

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#32685]
e.g., https://percy.io/ampproject/amphtml/builds/8876280/changed/503548953

**Comment by danielrozenberg** [comment]
@ampproject/wg-stories

**Comment by gmajoulet** [comment]
It looks like the issue is related to the image not loading, which would be a Percy issue more than a "amp-story: basic" test issue? Do we have a ticket to track images loading issues? That might be more actionable.

**Comment by danielrozenberg** [comment]
Yep! You're right, should've looked deeper into this before opening an issue. I emailed Percy support for help
