### ISSUE TITLE
RTC not firing in the new release 2102060044001

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#32715]
Received 2 reports in Slack.

PRs in this release: https://github.com/ampproject/amphtml/compare/2101300534005...2102060044001

This one touches RTC code: https://github.com/ampproject/amphtml/pull/32386

**Comment by lannka** [comment]
Some repro links provided by pubs:
https://www.google.co.uk/amp/s/www.telegraph.co.uk/football/2021/02/17/everton-vs-manchester-city-premier-league-live-score-latest/amp/
https://www.google.co.uk/amp/s/www.mirror.co.uk/sport/football/news/thierry-henry-explaining-gets-tired-23518899.amp

**Comment by lannka** [comment]
Likely we need an immediate rollback of the release. @erwinmombay

**Comment by lannka** [comment]
thanks @AskRupert-DM who just provided some valuable insights from debugging the issue.
#32713

**Comment by AskRupert-DM** [comment]
> thanks @AskRupert-DM who just provided some valuable insights from debugging the issue (including detailed repro instruction)
> #32713

Thanks - can't take credit for the debugging that came from @monis0395 

Has the release been reverted? Can see those pages behaving as expected/the RTC calls going out

**Comment by lannka** [comment]
woops. my mistake. yes, the release has been rolled back. we will be further investigating into this issue. and provide a real fix.

**Comment by AskRupert-DM** [comment]
Cool can see things looking normal / behaving as expected following the rollback - thanks for jumping on it & getting it rolled back so quick

**Comment by powerivq** [comment]
Root cause has been identified and the feature is being reworked.
