### ISSUE TITLE
[Page attachments] [Outlink] Theme attribute

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#32716]
Use a `theme` attribute to switch `light` and `dark` color scheme.

Style updates such as up arrow, chip and font can also be included in this PR.

<img width="728" alt="Screen Shot 2021-02-17 at 4 56 19 PM" src="https://user-images.githubusercontent.com/3860311/108273086-18ee1080-7141-11eb-858e-734ff595cb88.png">

@ampproject/wg-stories

**Comment by gmajoulet** [comment]
Can we create a different ticket to move the existing implementation to a Shadow DOM? It's not that straightforward and definitely deserves its own PR. Also, I think we should extract the open attachment UI to its own file, it's getting pretty big.

**Comment by processprocess** [comment]
Shadow DOM PR #32734

>I think we should extract the open attachment UI to its own file, it's getting pretty big.
Currently attachment logic is in amp-story-page [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/1.0/amp-story-page.js#L1751-L1802) and [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/1.0/amp-story-page.js#L165-L179)
It's also in [amp-story-page-attachment](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/1.0/amp-story-page-attachment.js#L142-L166)

Would it make sense to move all of the logic in `amp-story-page` into `amp-story-page-attachment` rather than making a new file?

**Comment by processprocess** [comment]
Looks like this broke before merging. Re-opening.
<img width="413" alt="Screen Shot 2021-04-21 at 9 33 53 AM" src="https://user-images.githubusercontent.com/3860311/115562768-d225af80-a284-11eb-909d-70bce024a866.png">
