### ISSUE TITLE
New amp-ad extension needs a .md doc file

### ISSUE THREAD

**Issue by tdrl** [ampproject/amphtml#3271]
In the refactor from a builtin to an extension, amp-ad docs got left behind.  I can see rationale for that, since the lazy script loading allows publishers to treat it as a builtin.  But there should be at least some docs in extensions/amp-ad.

@zhouyx ?

**Comment by zhouyx** [comment]
Working on that. But basically no feature changed and the amp-ad docs in builtin already got updated. It seems to me adding docs to extensions/amp-ad would simply be adding a duplicate docs file there?

**Comment by rudygalfi** [comment]
This is about updating https://github.com/ampproject/amphtml/blob/master/extensions/amp-sticky-ad/amp-sticky-ad.md, right?

I think we should have some content here. It should have the table that other extensions have with listings for Description, Availability, Required Script, Supported Layouts, and Examples. However, where it makes sense, it can heavily reference and make use of the documentation in amp-ad. For example, there should be a Behavior section defining how the sticky ad behaves and then it should hand off to amp-ad documentation to cover other topics.

**Comment by zhouyx** [comment]
I believe this is about adding new amp-ad.md because it's moved to extension . 
For the amp-sticky-ad.md, The pull request is #3280. Thanks for the comment I will add the reference to amp-ad there.

**Comment by zhouyx** [comment]
@erwinmombay 
So we want to redirect amp-ad docs from builtins to extensions?

**Comment by erwinmombay** [comment]
yes we have to do it for www.ampproject.org/docs/* since we can do redirects there

**Comment by rudygalfi** [comment]
Putting into Current milestone assuming this is getting actively worked on...

**Comment by zhouyx** [comment]
Thanks to @lannka, this should be closed by #4761 and #5026
