### ISSUE TITLE
3P: computeInMasterFrame order

### ISSUE THREAD

**Issue by parisholley** [ampproject/amphtml#3272]
According to the documentation, contributions for amp-ad can use computeInMasterFrame() to bundle HTTP requests for placements on an AMP page. I have tried implementing such behavior but it does not appear that the framework will guarantee the order of execution?

For example, say my page looks likes this:

``` html
<amp-ad id="1" />
...
<amp-ad id="2" />
...
<amp-ad id="3" />
```

I would expect that each 3P ad provider could register computeInMasterFrame() on page load, and send a single request to their ad server for all three placements.

Instead, one of those amp-ad tags are designated master (at random?), and if it happens to be the first in the bunch to get executed, none of the other placements will have invoked computeInMasterFrame() in time to bundle the request.

Is there a step I am missing in here? My assumption is AMP is delaying the load of content down the page until it is needed, so the concept behind computeInMasterFrame() would never work?

**Comment by jridgewell** [comment]
Assigning to @cramforce to give you a proper answer.

**Comment by cramforce** [comment]
@parisholley Your assessment is correct. The master is assigned by which ever loads first and it isn't aware of the configuration of other not-yet-rendered frames.

What is your exact use case?

**Comment by parisholley** [comment]
@cramforce When publishers use our tags direct normally, we scan for all placements on the page then make a single HTTP request for ads to fill each spot. This allows us to optimize by reducing duplications, bid across multiple placements, properly enforce frequency capping, etc. In DFP, this would be considered "Single Request Mode".

To work around this right now, I have to write a "lock" to the master frame (or session storage) and use a timeout to ensure that only one tag is requesting ads at a time. 

Ideally, AMP would pick a frame to act as master, then invoke all other frames first. The order isn't relevant or if it was delayed that would be fine. If instantiating each amp-ad unit early was to expensive, simply passing the metadata of each to the master would suffice, as once the others are loaded, it can call the master frame for the data.

**Comment by cramforce** [comment]
Makes sense. One thing that has been discussed before is to make the configuration for all sibling frames available to the master. We definitely don't want to eagerly create the siblings, but the master could have all the meta info about them.

**Comment by parisholley** [comment]
@cramforce If that is a design the AMP team is ok with, I'd be happy to provide a pull for the implementation. Haven't dug around the code yet, but I assume it would be simple enough to perhaps ad a "slaves" parameter to the context of the master?

**Comment by cramforce** [comment]
Feel free to give it a shot!

I think you may need to use `postMessage` to request the info from the parent page as otherwise URLs could get super large.

**Comment by jasti** [comment]
@parisholley Did you get a chance to send a PR for this? @cramforce would be good to prioritize for ads.

**Comment by parisholley** [comment]
@jasti no, I haven't looked into it yet.

**Comment by jasti** [comment]
@parisholley thanks. Any chance you could in the next couple of weeks? Lot of publishers would benefits from this!

**Comment by parisholley** [comment]
@jasti o why not :) i'll see what I get knocked out tonight

**Comment by jasti** [comment]
Thank you monsieur!

**Comment by jasti** [comment]
ping ping @parisholley. Any progress?

**Comment by parisholley** [comment]
@jasti no, i haven't been able to write a line of code in weeks. someone feel free to pick this up, otherwise have to wait till I get in the mood again :x

**Comment by jasti** [comment]
ok, un-assigning you for now but do let us know if you get in the mood again :)

**Comment by jasti** [comment]
@keithwrightbos I know you've been looking into supporting SRA, so wanted to put this on your radar in case we can arrive at a solution within AMP that any ad network can re-use.
FYI @michaelkleber.

**Comment by jasti** [comment]
Closing since we are moving away from using remote.html
