### ISSUE TITLE
🌸 Cherry-pick request for #32713 into #32592 (Pending)

### ISSUE THREAD

**Issue by powerivq** [ampproject/amphtml#32724]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #32713 | #32723 |     **YES**     | **YES** | **NO** | #32592                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

It is breaking some publishers using RTC. Some of RTC vendor calls are being blocked.

## Why is a Beta / Experimental cherry-pick not needed?

N/A

## Why is an LTS cherry-pick needed?

N/A

## List the steps to manually verify the changes in this cherry-pick

Build locally, go to http://localhost:8000/proxy/s/www.foxnews.com/tech/election-meddling-by-iran-russia-china-to-amp-up-prior-to-presidential-election.amp

The following error does not appear.
```
RTC callout to xxxxxx caused 7
```

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

<_1-2 sentences summarizing the problem and root causes._>

## Impact

- <_Which users were affected? Roughly how many?_>
- <_How were users affected? E.g. partial or complete loss of functionality?_>

## Action Items

- #<_ISSUE_NUMBER_>: <_Add unit/integration/end-to-end test_>
- #<_ISSUE_NUMBER_>: <_Add monitoring for edge case via error logging_>
- #<_ISSUE_NUMBER_>: <_Refactor an easily misused API_>

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers @ampproject/wg-monetization

**Comment by kristoferbaxter** [comment]
Approved.
