### ISSUE TITLE
[Page attachments] [Outlink]  Extract open attachment UI to its own file

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#32736]
Currently page attachment logic is in `amp-story-page` [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/1.0/amp-story-page.js#L1751-L1802) and [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/1.0/amp-story-page.js#L165-L179)

This can be extracted into its own file.

@ampproject/wg-stories

**Comment by raxsha** [comment]
Fixed #33042
