### ISSUE TITLE
Form is submitted when textarea fields are a patternMismatch

### ISSUE THREAD

**Issue by eliotharper** [ampproject/amphtml#32745]
## What's the issue?

Form is automatically submitted when textarea fields are a patternMismatch

## How do we reproduce the issue?

I'm using AMP for Email, but the same issue occurs on AMP websites.

1. [Load AMP HTML in AMP Playground](https://playground.amp.dev/?mode=Responsive&runtime=amp4email#share=PCFkb2N0eXBlIGh0bWw+CjxodG1sIOKaoTRlbWFpbCBkYXRhLWNzcy1zdHJpY3Q+CjxoZWFkPgogIDxtZXRhIGNoYXJzZXQ9InV0Zi04Ij4KICA8c2NyaXB0IGFzeW5jIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAuanMiPjwvc2NyaXB0PgogIDxzY3JpcHQgYXN5bmMgY3VzdG9tLWVsZW1lbnQ9ImFtcC1mb3JtIiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1mb3JtLTAuMS5qcyI+PC9zY3JpcHQ+CiAgPHN0eWxlIGFtcDRlbWFpbC1ib2lsZXJwbGF0ZT5ib2R5e3Zpc2liaWxpdHk6aGlkZGVufTwvc3R5bGU+CiAgICA8c3R5bGUgYW1wLWN1c3RvbT4KICAgICAgYm9keSB7CiAgICAgICAgcGFkZGluZy10b3A6IDV2aDsKICAgICAgICBmb250LXN0eWxlOiBub3JtYWw7CiAgICAgIH0KCiAgICAgIGJvZHksCiAgICAgIHRleHRhcmVhIHsKICAgICAgICBmb250LWZhbWlseTogSGVsdmV0aWNhLCBBcmlhbCwgc2Fucy1zZXJpZjsKICAgICAgfQoKICAgICAgaDIgewogICAgICAgIGNvbG9yOiAjNGNhZjUwOwogICAgICB9CgogICAgICBmb3JtIHsKICAgICAgICBtYXJnaW46IGF1dG87CiAgICAgICAgd2lkdGg6IDQwdnc7CiAgICAgIH0KCiAgICAgIHRleHRhcmVhLAogICAgICBpbnB1dFt0eXBlPXRleHRdLAogICAgICBzZWxlY3QgewogICAgICAgIHdpZHRoOiAxMDAlOwogICAgICAgIHBhZGRpbmc6IDEycHggMjBweDsKICAgICAgICBtYXJnaW46IDhweCAwOwogICAgICAgIGRpc3BsYXk6IGlubGluZS1ibG9jazsKICAgICAgICBib3JkZXI6IDFweCBzb2xpZCAjY2NjOwogICAgICAgIGJvcmRlci1yYWRpdXM6IDRweDsKICAgICAgICBib3gtc2l6aW5nOiBib3JkZXItYm94OwogICAgICB9CgogICAgICBpbnB1dFt0eXBlPXN1Ym1pdF0gewogICAgICAgIHdpZHRoOiAxMDAlOwogICAgICAgIGJhY2tncm91bmQtY29sb3I6ICM0Y2FmNTA7CiAgICAgICAgY29sb3I6IHdoaXRlOwogICAgICAgIHBhZGRpbmc6IDE0cHggMjBweDsKICAgICAgICBtYXJnaW46IDhweCAwOwogICAgICAgIGJvcmRlcjogbm9uZTsKICAgICAgICBib3JkZXItcmFkaXVzOiA0cHg7CiAgICAgICAgZm9udC1zaXplOiAxZW07CiAgICAgIH0KCiAgICAgIGlucHV0W3R5cGU9c3VibWl0XTpob3ZlciB7CiAgICAgICAgYmFja2dyb3VuZC1jb2xvcjogIzQ1YTA0OTsKICAgICAgfQoKICAgICAgZm9ybSNzYW1wbGUtZm9ybS5hbXAtZm9ybS1zdWJtaXQtc3VjY2VzcyBpbnB1dCwKICAgICAgZm9ybSNzYW1wbGUtZm9ybS5hbXAtZm9ybS1zdWJtaXQtc3VjY2VzcyB0ZXh0YXJlYSB7CiAgICAgICAgYmFja2dyb3VuZC1jb2xvcjogI2VlZTsKICAgICAgICBvdXRsaW5lOiAwOwogICAgICAgIGNvbG9yOiAjY2NjOwogICAgICB9CgogICAgICBzcGFuIHsKICAgICAgICBmb250LXNpemU6IDAuOGVtOwogICAgICB9CiAgICA8L3N0eWxlPgo8L2hlYWQ+Cgo8Ym9keT4KCiAgPGZvcm0gaWQ9InNhbXBsZS1mb3JtIgogICAgbWV0aG9kPSJwb3N0IgogICAgYWN0aW9uLXhocj0iaHR0cHM6Ly9wdWIuczExLmV4YWN0dGFyZ2V0LmNvbS9ocW5heW5tejR3MSIKICAgIGN1c3RvbS12YWxpZGF0aW9uLXJlcG9ydGluZz0ic2hvdy1hbGwtb24tc3VibWl0Ij4KCiAgICA8aW5wdXQgdHlwZT0idGV4dCIKICAgICAgaWQ9InNob3ctYWxsLW9uLXN1Ym1pdC1uYW1lIgogICAgICBuYW1lPSJuYW1lIgogICAgICB0YWJpbmRleD0iMSIgCiAgICAgIHBsYWNlaG9sZGVyPSJFbnRlciB5b3VyIGZpcnN0IG5hbWUiCiAgICAgIHJlcXVpcmVkPgogICAgPHNwYW4gdmlzaWJsZS13aGVuLWludmFsaWQ9InZhbHVlTWlzc2luZyIKICAgICAgdmFsaWRhdGlvbi1mb3I9InNob3ctYWxsLW9uLXN1Ym1pdC1uYW1lIj5UaGlzIGlzIGEgcmVxdWlyZWQgZmllbGQ8L3NwYW4+CgogICAgIDx0ZXh0YXJlYSBjbGFzcz0icmV2aWV3LWZpZWxkIiAKICAgICAgICAgcm93cz0iNSIgCiAgICAgICAgIG5hbWU9InRleHQiCiAgICAgICAgIGlkPSJsaWZlLXN0b3J5IiAKICAgICAgICAgcm9sZT0idGV4dGJveCIgCiAgICAgICAgIHRhYmluZGV4PSIyIiAKICAgICAgICAgcGxhY2Vob2xkZXI9IkVudGVyIHlvdXIgbGlmZSBzdG9yeSIKICAgICAgICAgcmVxdWlyZWQKICAgICAgICAgcGF0dGVybj0iXi57NSx9JCIKICAgICAgICAgPjwvdGV4dGFyZWE+CiAgICA8c3BhbiB2aXNpYmxlLXdoZW4taW52YWxpZD0idmFsdWVNaXNzaW5nIgogICAgICB2YWxpZGF0aW9uLWZvcj0ibGlmZS1zdG9yeSI+VGhpcyBpcyBhIHJlcXVpcmVkIGZpZWxkPC9zcGFuPgogICAgPHNwYW4gdmlzaWJsZS13aGVuLWludmFsaWQ9InBhdHRlcm5NaXNtYXRjaCIKICAgICAgdmFsaWRhdGlvbi1mb3I9ImxpZmUtc3RvcnkiPkZpdmUgb3IgbW9yZSBjaGFyYWN0ZXJzIGFyZSByZXF1aXJlZDwvc3Bhbj4KICAgICAgICAgIAogICAgPGlucHV0IHR5cGU9InN1Ym1pdCIKICAgICAgICAgICB0YWJpbmRleD0iMyIgCiAgICAgICAgICAgdmFsdWU9IlN1Ym1pdCI+CgogICAgPGRpdiBzdWJtaXQtc3VjY2Vzcz4KICAgICAgICA8aDI+Rm9ybSBzdWJtaXR0ZWQgc3VjY2Vzc2Z1bGx5ITwvaDI+CiAgICA8L2Rpdj4KCiAgICA8ZGl2IHN1Ym1pdC1lcnJvcj4KICAgICAgICA8aDI+U29tZXRoaW5nIHdlbnQgd3JvbmcuPC9oMj4KICAgIDwvZGl2PgoKICA8L2Zvcm0+CiAgPC9ib2R5Pgo8L2h0bWw+Cg==)
2. Enter value in input field
3. Enter value in textarea field with **less than 5 characters**
4. Click Submit (returns pattern match error)
5. Wait 3 seconds

## Additional Info

The bug only seems to occur on first validation. So if you follow these steps, the form is not submitted:

1. Enter value in first input field
2. Submit the form (surfaces required validation for text area)
3.  Enter value in textarea field with **less than 5 characters**
4. Submit the form (surfaces pattern match validation for text area)

## What browsers are affected?

Tested in Chrome and Firefox

## Which AMP version is affected?

2102060044003

**Comment by micajuine-ho** [comment]
Hi @eliotharper, HTML5 does not support pattern on `<textarea>` elements within a form. 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

As such, AMP does not add this functionality. Perhaps you can change the textarea to an input element. 
https://amp.dev/documentation/components/amp-form/#verification.
