### ISSUE TITLE
Link to release calendar from release-schedule doc

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#32755]
Link: https://amp-release-calendar.appspot.com/
Release schedule doc: https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md
Corresponding AMP.dev page: https://amp.dev/documentation/guides-and-tutorials/learn/spec/release-schedule/

**Comment by rsimha** [comment]
Related: https://github.com/ampproject/amp-github-apps/issues/985

**Comment by rsimha** [comment]
_[Infra triage]_ This is still a useful idea. Closing this issue as a duplicate of ampproject/amp-github-apps/issues/985, which has since been transferred to `amphtml`.
