### ISSUE TITLE
[Page attachments] [Inline] Open to max of 80% of screen

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#32760]
Open to max of 80% of screen.
Open to size of content if less than 80%.

Tapping the story in background should dismiss the attachment.

Scrolling the content will open it to 100%.

<img width="388" alt="Screen Shot 2021-02-19 at 4 47 59 PM" src="https://user-images.githubusercontent.com/3860311/108565174-41f1db00-72d2-11eb-9dc7-45b6bb50d1c9.png">
<img width="430" alt="Screen Shot 2021-02-19 at 4 48 35 PM" src="https://user-images.githubusercontent.com/3860311/108565258-60f06d00-72d2-11eb-9871-59b7af1dffcb.png">

@ampproject/wg-stories

**Comment by nterol** [comment]
Will it be still possible to open the attachment to 100% of screen ?

**Comment by processprocess** [comment]
> Will it be still possible to open the attachment to 100% of screen ?

Hi @nterol :) 
Yes, swiping up will open the attachment to 100%

**Comment by nterol** [comment]
> > Will it be still possible to open the attachment to 100% of screen ?
> 
> Hi @nterol :)
> Yes, swiping up will open the attachment to 100%

Thank you for your answer

Do you mean this will be the default behavior of the page attachment once this PR is merged ? Or will it be a behavior one can choose ?

**Comment by processprocess** [comment]
For sure!
It will be default, like the bookend but it will have a [close button](https://github.com/ampproject/amphtml/issues/32765) at the top as an additional dismissal affordance.
![Mar-17-2021 10-27-39](https://user-images.githubusercontent.com/3860311/111483998-b8380080-870b-11eb-890e-abe58f63c098.gif)

We're making this change to give users additional context that they are still viewing content within a story.

**Comment by nterol** [comment]
So there will not be a possibility to skip this 80% preview then. 

I'm asking this because I'm currently doing the opposite : I'm forcing the attachment to show a 10~20% preview so that users understand the attachment is present, and can then be extended to 100%.

**Comment by processprocess** [comment]
@nterol thanks for the feedback and sharing this concept. 
It's an interesting idea to display a preview of the attachment content. 

Currently taps on page attachments block navigation.
Page navigation is core UX of the experience and we need to prioritize it.

I'd be happy to see explorations/examples of this concept.
I'm on the AMP slack channel btw, feel free to ping me any time!
