### ISSUE TITLE
[Story Player] Fix script import path to local build

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#32781]
Loading a local build of the Player in a development environment should work like any other extension.

We should be able to specify:
```
  <script async src="https://cdn.ampproject.org/amp-story-player-v0.js"></script>
```

But instead this fails and loads the production build.

Today, we need to specifically write `<script async src="../../dist/amp-story-player.js"></script>`, which is unlike other extensions and brings confusion in local development.

cc @ampproject/wg-stories

**Comment by Enriqe** [comment]
Dupe of https://github.com/ampproject/amphtml/issues/30817 (my bad for not labeling it correctly)
