### ISSUE TITLE
Amp-form autofill is flickering

### ISSUE THREAD

**Issue by YuriyBishko** [ampproject/amphtml#32787]
## What's the issue?

Amp-form autofill is flickering when `amp-bind` script loaded

## How do we reproduce the issue?

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

1. Go to (https://bluecarrot.io/)
2. Scroll down to the footer
3. Click on the Name or Email field

## What browsers are affected?

Chrome

**Comment by caroqliu** [comment]
Hi @YuriyBishko, thanks for filing an issue! I'm able to see the issue you are describing - on focus, the autofill flickers as in flashes visible then invisible. At first glance, It's not obvious why this is. I tried [creating a minimal sample](https://playground.amp.dev/?format=websites&_gl=1*x8570f*_ga*YW1wLTVrcDR1bGNQYlJRZ0VkTHVaT2JiRUE.#share=PCFkb2N0eXBlIGh0bWw+CjxodG1sIOKaoT4KPGhlYWQ+CiAgPG1ldGEgY2hhcnNldD0idXRmLTgiPgogIDx0aXRsZT5hbXAtZm9ybSAtIEV4YW1wbGUgMjwvdGl0bGU+CiAgPHNjcmlwdCBhc3luYyBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwLmpzIj48L3NjcmlwdD4KICA8c2NyaXB0IGN1c3RvbS1lbGVtZW50PSJhbXAtZm9ybSIgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC9hbXAtZm9ybS0wLjEuanMiIGFzeW5jPjwvc2NyaXB0PgogIDxsaW5rIHJlbD0iY2Fub25pY2FsIiBocmVmPSJodHRwczovL3ByZXZpZXcuYW1wLmRldi9kb2N1bWVudGF0aW9uL2NvbXBvbmVudHMvYW1wLWZvcm0uZXhhbXBsZS4yLmh0bWwiPgogIDxtZXRhIG5hbWU9InZpZXdwb3J0IiBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgiPgogIDxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoOy1tb3otYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1zLWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoO2FuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RofUAtd2Via2l0LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1vei1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1tcy1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1vLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1Aa2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fTwvc3R5bGU+PG5vc2NyaXB0PjxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjpub25lOy1tb3otYW5pbWF0aW9uOm5vbmU7LW1zLWFuaW1hdGlvbjpub25lO2FuaW1hdGlvbjpub25lfTwvc3R5bGU+PC9ub3NjcmlwdD4KPC9oZWFkPgo8Ym9keT4KCjxmb3JtIG1ldGhvZD0icG9zdCIKICAgIGFjdGlvbi14aHI9Imh0dHBzOi8vZXhhbXBsZS5jb20vc3Vic2NyaWJlIgogICAgY3VzdG9tLXZhbGlkYXRpb24tcmVwb3J0aW5nPSJhcy15b3UtZ28iIHRhcmdldD0iX2JsYW5rIgogICAgICBvbj0idmFsaWQ6QU1QLnNldFN0YXRlKHt2aXNpYmxlOiB0cnVlfSk7aW52YWxpZDpBTVAuc2V0U3RhdGUoe3Zpc2libGU6IGZhbHNlfSkiPgogICAgICA8ZGl2IGNsYXNzPSJncm91cCI+CiAgICAgICAgPGlucHV0IHR5cGU9InRleHQiIGlkPSJhcy15b3UtZ28tbmFtZSIgbmFtZT0ibmFtZSIgcmVxdWlyZWQ+CiAgICAgICAgPGxhYmVsIGNsYXNzPSJmQy1sYWJlbCIgZm9yPSJuYW1lIj5OYW1lPC9sYWJlbD4KICAgICAgPC9kaXY+CiAgICAgIDxkaXYgY2xhc3M9Imdyb3VwIj4KICAgICAgICA8aW5wdXQgdHlwZT0iZW1haWwiIGlkPSJhcy15b3UtZ28tZW1haWwiIG5hbWU9ImVtYWlsIiByZXF1aXJlZD4KICAgICAgICA8bGFiZWwgY2xhc3M9ImZDLWxhYmVsIiBmb3I9ImVtYWlscyI+RW1haWw8L2xhYmVsPgogICAgICA8L2Rpdj4KICAgICAgPGlucHV0IHR5cGU9InN1Ym1pdCIKICAgICAgICB2YWx1ZT0iU3Vic2NyaWJlIj4KICA8L2Zvcm0+CjwvYm9keT4KPC9odG1sPg==) from your markup, but am not able to reproduce the issue on that example. Can you share more about how the `visible` AMP state variable is being used? Maybe that is the part I am missing here.

**Comment by YuriyBishko** [comment]
Hi @caroqliu, I have found the real problem of this issue.

If we have a parent block with `on="tap"` attribute the autofill is flickering.
In my case it was div element with`on="tap: AMP.setState({showPurposeMenu: false, showNicheMenu: false, showTechniqMenu: false})"`.

I have refactored my code to get rid of it, and now it works.
You can test it on my test server: (https://beta.bluecarrot.io/)

Thanks for your help!

**Comment by caroqliu** [comment]
Oh great, nice job identifying this. Looks good!
