### ISSUE TITLE
Add iBILLBOARD Adserver in AMP

### ISSUE THREAD

**Issue by Internet-BillBoard** [ampproject/amphtml#3278]
Hi,
According to the technical specifications we're able to implement iBILLBOARD AdServer to the AMP registered subjects, and so we want to proceed with it.
Can we move on to signature of the CLA, or is there some further information required?

**Comment by rudygalfi** [comment]
@Internet-BillBoard If you are planning to contribute an implementation according to https://github.com/ampproject/amphtml/blob/master/ads/integration-guide.md, then please submit a pull request. You can sign the CLA and the travis check on the pull request should go green once you've signed.

/cc @kashyapnitin

**Comment by jasti** [comment]
Dupe of #4628. closing.
