### ISSUE TITLE
The script tag contains invalid JSON that cannot be parsed.

### ISSUE THREAD

**Issue by kleverk-Designs** [ampproject/amphtml#32854]
## What's the issue?

The script tag contains invalid JSON that cannot be parsed.

Briefly describe the bug/feature request.
The website page is passing AMP validation @ [validator.ampproject.org](https://validator.ampproject.org/#url=https%3A%2F%2Fphpstack-359858-1775447.cloudwaysapps.com%2Ftemplates%2Fblog%2Fhow-to%2Favoid-these-ten-mistakes-that-everyone-makes-in-interior-design.amp.html) but keeps giving Warning " The script tag contains invalid JSON that cannot be parsed." [Link to the page](https://phpstack-359858-1775447.cloudwaysapps.com/templates/blog/how-to/avoid-these-ten-mistakes-that-everyone-makes-in-interior-design.amp.html) When we test the schema markup in structure data testing tool there is no error
## How do we reproduce the issue?
Pls click the [link](https://validator.ampproject.org/#url=https%3A%2F%2Fphpstack-359858-1775447.cloudwaysapps.com%2Ftemplates%2Fblog%2Fhow-to%2Favoid-these-ten-mistakes-that-everyone-makes-in-interior-design.amp.html) to reproduce the error
If this is a bug please provide a public URL and ideally a reduced test case (e.g. on jsbin.com, codepen.io, or glitch.com) that exhibits only your issue and nothing else. Then provide step-by-step instructions for reproducing the issue:

## Which AMP version is affected?
Json
Is this a new issue? Or was it always broken? Paste your AMP version. You can find it in the browser dev tools.
Made on starter AMP template land and sea

**Comment by honeybadgerdontcare** [comment]
The warning states that the issue is in the JSON blob starting on line 47. Putting that in a JSON validator shows that there is indeed an error on line 119. Note line 119 starts a string but ends in a newline and continues on 120. I tested removing the newline at the end of 119 and combing line 120 with it. It now passes JSON parsing.

**Comment by kleverk-Designs** [comment]
Thank you for your advice it helped. One last favor please this will help me a lot.

[The URL ](https://validator.ampproject.org/#url=https%3A%2F%2Fphpstack-359858-1775447.cloudwaysapps.com%2Ftemplates%2Fblog%2Fhow-to%2Fbest-interior-designers-in-mumbai.amp.html) when tested on AMP gives the same error and when tested on structure data provides ZERO error. 
Could you please help me with this one more time? 

Will appreciate the same. Thank you.
