### ISSUE TITLE
Closure compiler: fail on some warnings

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#32868]
Some Closure warnings are errors in AMP's context. Failing compilation for these warnings would help us avoid "obvious" bugs. These include:

- JSC_TYPE_MISMATCH
- JSC_HIDDEN_SUPERCLASS_PROPERTY_MISMATCH
- JSC_UNKNOWN_OVERRIDE
- JSC_UNRECOGNIZED_TYPE_ERROR

An example: https://github.com/ampproject/amphtml/pull/32869

/cc @ampproject/wg-infra

**Comment by samouri** [comment]
We no longer use Closure and this is no longer relevant. Closing
