### ISSUE TITLE
Bookend issue with google amp cache version

### ISSUE THREAD

**Issue by Avdhoot05** [ampproject/amphtml#32860]
When I opened https://animals-visualstories-com.cdn.ampproject.org/c/s/animals.visualstories.com/quizzes/a-challenging-javan-rhinoceros-quiz?usqp=mq331AQCCAE=#origin=https://visualstories.com&cap=swipe

It gives bookend issue with amp-cache version.

and https://animals.visualstories.com/quizzes/a-challenging-javan-rhinoceros-quiz is working fine.
![bookend-issue](https://user-images.githubusercontent.com/46551690/109024178-7a832180-76e3-11eb-971a-0fc844c0cd7d.PNG)

**Comment by Avdhoot05** [comment]
@newmuis  Any update ?

**Comment by newmuis** [comment]
Your bookend endpoint likely does not support cross-origin requests.  See [Why do I need CORS for my own origin?
](https://amp.dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cors-requests/#why-do-i-need-cors-for-my-own-origin?).

Also note that the bookend is [deprecated](https://github.com/ampproject/amphtml/issues/26957), and we will begin the removal process (with appropriate communication/notification) shortly.
