### ISSUE TITLE
Add multiple side of amp-sidebar

### ISSUE THREAD

**Issue by slivorezka** [ampproject/amphtml#3287]
HI guys!
So we can  set open side of `amp-sidebar` by `body ` tag’s dir attribute (ltr => left , rtl => right’).
But if I have two `amp-sidebar` and I need use first menu open from left side
and last menu open from right side?
Can we implement a rule for open sidebar left / right by tag side=right / side=right inside `amp-sidebar` tag?
For example:

```
<amp-sidebar id='sidebar1' layout='nodisplay' side='left'>
  <ul>
    <li> Bla - bla 1</li>
    <li> Bla - bla 2</li>
  </ul>
</amp-sidebar>
```
```
<amp-sidebar id='sidebar2' layout='nodisplay' side='right'>
  <ul>
    <li> Bla - bla 1</li>
    <li> Bla - bla 2</li>
  </ul>
</amp-sidebar>
```
Thanks!

**Comment by sriramkrish85** [comment]
@slivorezka just curious - what is the use-case for this ?
Although 2 sidebars are not recommended it is possible to do what you described.
Given that you should also note that we do have a UX bug (https://github.com/ampproject/amphtml/issues/3320) that will be fixed. And make your plans accordingly.

You are also welcome to help fix this bug :)

**Comment by heiwen** [comment]
Just stumbled upon this, a user case from an e-commerce perspective is to show the main navigation menu in the left side bar and a filter experience in the right side bar.

**Comment by rudygalfi** [comment]
@heiwen Great feedback. I've observed that as well.

**Comment by camelburrito** [comment]
@heiwen - FYI  - https://github.com/ampproject/amphtml/issues/3320 -
