### ISSUE TITLE
I2I: Saving metering state for amp-subscriptions

### ISSUE THREAD

**Issue by ChrisAntaki** [ampproject/amphtml#32913]
## Summary

The SwG team wants to save metering state to localStorage, to support the Google News Showcase within AMP
https://blog.google/outreach-initiatives/google-news-initiative/google-news-showcase/

## Motivation

SwG wants to speed up pageloads by caching metering state to localStorage. Without this caching, users would have to wait longer before we could check if they were entitled to free reads as part of the Google News Showcase project

## Additional context

Here's a PR that implements the feature:
https://github.com/ampproject/amphtml/pull/33010

The PR uses AMP's `setNonBoolean` storage API to save JSON received from publishers
https://github.com/ampproject/amphtml/blob/88e51bc61ed614e4a00435e541ba1a06120d588e/extensions/amp-subscriptions/0.1/metering.js#L104

## Launch tracker

@jpettitt 
@dvoytenko 

/cc @ampproject/wg-approvers

**Comment by jpettitt** [comment]
@ChrisAntaki can you add a sample of what's being saved / pointer to the code so folks don't have to wade through the entire PR to find it?

**Comment by ChrisAntaki** [comment]
Good call! Here's a sample of what the PR is saving to localStorage

```json
{
  "vv": {
    "amp-subscriptions:metering-store": {
      "v": "{\"id\":\"ppid22171274\",\"standardAttributes\":{\"registered_user\":{\"timestamp\":1614237965}}}",
      "t": 1614267965264
    }
  }
}
```
