### ISSUE TITLE
[amp-story-player] Add support for rewinding stories in the background

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#32941]
Follow up for #31424

Currently it is only possible to rewind the current story. We'd like to rewind other stories in the background as well.

**Comment by edoudou** [comment]
@Enriqe When do you think this feature will be dealt with, and when should we except to see it live ?

**Comment by Enriqe** [comment]
@edoudou the last PR has been merged, it should be in the nightly channel by tomorrow, in the beta channel next Tuesday, and in stable a week after that.
