### ISSUE TITLE
[amp-story] Drop bookend when possible

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#32955]
Part of #26957

As a step in the deprecation, we should drop the bookend from stories that don't use the `<amp-story-bookend>` tag.

/cc @ampproject/wg-stories

**Comment by gmajoulet** [comment]
As per the AMP removal process, we will have to wait some time before being able to remove anything. Once that period is over, we should remove all bookends altogether, I don't see removing the bookend only sometimes as a viable option if we want to follow the AMP process.

It should look like this:
- Provide a bookend replacement for some features (sharing options)
- File an intent to remove and trigger validation warnings with instructions to move to the replacement if needed
- Wait for the amount of time defined by AMP
- Remove bookends in all scenarios

We have an internal doc describing this, we should get to it really soon.

**Comment by gmajoulet** [comment]
No strong opinions here, but if it was up to me I'd rather focus 100% of our energy on removing the bookend altogether given we're so close from doing it (6 weeks).

**Comment by newmuis** [comment]
Makes sense!  Closing, since I was actually the original requester
