### ISSUE TITLE
FR: generator-amp

### ISSUE THREAD

**Issue by hemanth** [ampproject/amphtml#3297]
Hello Folks, 

Do checkout [generator-amp](https://github.com/hemanth/generator-amp) it's still in `v0.0.1` and all it does for now is the below: 

![amp](https://cloud.githubusercontent.com/assets/18315/15487954/44a18d64-2106-11e6-8aa3-de081d3f44ee.gif)

If some of you have some time we can make this stable and live soon, let me know what you think of this.

**Comment by rudygalfi** [comment]
Can you be more specific about the request? What change is needed to AMP?

**Comment by hemanth** [comment]
@rudygalfi I was looking for boilerplate codes, was planning to use the same that's in the examples dir.

**Comment by ericlindley-g** [comment]
Checking back in on this: there are a bunch of single-component templates at [AMP by Example](https://ampbyexample.com/), and soon to be more templates at [AMP Start](https://github.com/ampproject/ampstart). 

@camelburrito  — have you checked out this generator? Would it be useful in the context of the AMP Start work you're doing?

**Comment by camelburrito** [comment]
I guess this generates the head tag based on which amp- components are used on the page. I am not sure how we could make use of it.

**Comment by rudygalfi** [comment]
Going to close this since there hasn't been much follow-on discussion, but if there are new updates planned with this project let us know.

**Comment by hemanth** [comment]
Phew, Oki.
