### ISSUE TITLE
Latest release Breaks amp-youtube,amp-img on an amp-list inside an lightbox

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#32978]
**Please only file reports about bugs in AMP here.**

## What's the issue?
Previously working functionality broken
Latest release Breaks amp-youtube,amp-img on an amp-list inside an lightbox

Briefly describe the bug.

Images and videos inside an amp-list in a lightbox dont load anymore. 

## How do we reproduce the issue?
1. go to https://storywall-staging.firebaseapp.com/storywall
2. click on any thumbnail , it makes a successful network call and  but the lightbox fails to load the image. 
## What browsers are affected?
All

## Which AMP version is affected?
This is brand new this week. Version: 2102130314001

**Comment by kristoferbaxter** [comment]
Marked P1, but this might be P0.

@samouri and @dmanek can you take a look?

**Comment by kristoferbaxter** [comment]
We've rolled back the release that caused this issue, and will start to investigate on Monday.

**Comment by camelburrito** [comment]
Thank you!

**Comment by kristoferbaxter** [comment]
Adding @dvoytenko, this appears to be the issue from rough a rough glance: https://github.com/ampproject/amphtml/issues/32978

**Comment by camelburrito** [comment]
Can confirm that the issue does not exist in 2101300534005 (tested it out). The rollback fixed it !

**Comment by erwinmombay** [comment]
thank you @camelburrito !

**Comment by dvoytenko** [comment]
I think I see the reason for the error. It's a bit obscure. Worth discussing. I have a fix almost ready, but this part is a bit fragile.

**Comment by dvoytenko** [comment]
The fix and cherrypick for Stable/Beta are #32980 and #32981. The fix for the HEAD is #32979.

**Comment by camelburrito** [comment]
@dvoytenko - the cherry pick seems to be working for most cases , here is one case it is still broken, if the lightbox scrolls the amp-images below are not loaded

How to reproduce

Use chrome simulator , choose iphoneX (or a real phone)
go to - https://concussionstorywall.org/storywall?filter-person=2
select the cause of injury filer to "Diving", select any thumbnail  named "Cindy"

If you scroll down the lightbox, the images dont load (this was working fine before)

![image](https://user-images.githubusercontent.com/1037311/109920477-30fc7e80-7c6f-11eb-9450-9f1308182cd1.png)

**Comment by dvoytenko** [comment]
Looking

**Comment by dvoytenko** [comment]
@camelburrito I took a look at this case, but it's quite different reason. The issue there is that a scrollable lightbox is used, but within it there's a separate scrollable box that independently scrolls. The lightbox currently doesn't support this very well. More specifically, it doesn't see the scroll events within this other scroller and also cannot compute the correct offsets. I'd say that if it worked before it was probably more due an accident than anything that might have changed. I think supporting this kind of mode would be possible, but not sure what it could possibly take. Do you think it'd be possible for you to use the native lightbox scrolling feature?

**Comment by camelburrito** [comment]
@dvoytenko , that makes sense. Ill try to work around that

The lightbox by default is completely unstyled and has no frame or anything so i made some stuff for making it look like a lightbox, hence had to add the scroll container. here is what happened if i remove the `overflow-y: scroll` on the container 

![image](https://user-images.githubusercontent.com/1037311/109938886-5b593680-7c85-11eb-8af2-ba2ce89ecf3f.png)

Do you know if the lightbox is supposed to be barebones without any style, modal/backpanel etc ? or is that a bug ?

**Comment by dvoytenko** [comment]
@camelburrito the low initial styling is definitely intended. However, the backdrop can definitely be added and it should be relatively easy to do. The lightbox already allows specifying `max-width/height` and `margin:auto`, so making it smaller and centered is possible already. That only makes the backdrop missing for your use case, right?
