### ISSUE TITLE
amp-script nodom has no access to amp-state

### ISSUE THREAD

**Issue by dritter** [ampproject/amphtml#32984]
Hi there,

TBH, I am not sure if this is a Bug, or on purpose (and not [documented](https://amp.dev/documentation/components/amp-script/#referencing-amp-state)). I noticed that `amp-script` with `nodom` attribute has no access to `amp-state`.
The [documentation about `nodom`](https://amp.dev/documentation/components/amp-script/#nodom) says that with `nodom` it is not allowed to make DOM _modifications_, but in my Case I just wanted to read out the current state (so no modification). If this is on purpose, it should be clearly documented.

[Testcase in Playground](https://playground.amp.dev/#share=PCFET0NUWVBFIGh0bWw+CjxodG1sIOKaoT4KPGhlYWQ+CiAgICA8bWV0YSBjaGFyc2V0PSJ1dGYtOCIgLz4KICAgIDx0aXRsZT5NeSBBTVAgUGFnZTwvdGl0bGU+CiAgICA8bGluayByZWw9ImNhbm9uaWNhbCIgaHJlZj0ic2VsZi5odG1sIiAvPgogICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCIgLz4KICAgIDxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoOy1tb3otYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1zLWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoO2FuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RofUAtd2Via2l0LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1vei1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1tcy1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1vLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1Aa2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fTwvc3R5bGU+PG5vc2NyaXB0PjxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjpub25lOy1tb3otYW5pbWF0aW9uOm5vbmU7LW1zLWFuaW1hdGlvbjpub25lO2FuaW1hdGlvbjpub25lfTwvc3R5bGU+PC9ub3NjcmlwdD4KICAgIDxzY3JpcHQgYXN5bmMgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC5qcyI+PC9zY3JpcHQ+CiAgICA8c2NyaXB0IGFzeW5jIGN1c3RvbS1lbGVtZW50PSJhbXAtc2NyaXB0IiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1zY3JpcHQtMC4xLmpzIj48L3NjcmlwdD4KICAgIDxzY3JpcHQgYXN5bmMgY3VzdG9tLWVsZW1lbnQ9ImFtcC1iaW5kIiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1iaW5kLTAuMS5qcyI+PC9zY3JpcHQ+CiAgICA8c3R5bGUgYW1wLWN1c3RvbT4KICAgICAgICBoMSB7CiAgICAgICAgICAgIG1hcmdpbjogMXJlbTsKICAgICAgICB9CiAgICA8L3N0eWxlPgoKICA8bWV0YSBuYW1lPSJhbXAtc2NyaXB0LXNyYyIgY29udGVudD0ic2hhMzg0LThCeEo2R2t3UXhaSkd5em1CMnQzbHA2X2dyQk5ueEotd3hWcjFqOFFyREZxaHh1UGpZUEdFT21sbXBfS3JVTjYgc2hhMzg0LTJLbU9GQVB3dFRRVE03OURmcGE1YkJaY0FpYjNEd2xBSUJGSzJReHl5eGdGMEJaZndDR1dRTzlxZjFIc1N0VTggc2hhMzg0LWU4dmxiZHoybElkZENXSl93WkNLZHYwUGZra2ZZWXFxRmRwc1ROdWVoaVlmVDRFMWIwanJudWdBblJwOUZWOXEgc2hhMzg0LTRITkV0MUlwUHdwVEpZbmF6dEhrZ2s4S04wREN0VFBGN204WHQxZmR3QmJTbklfTldISUtxb2M5WEJ3SDk3bDYgIj4KPC9oZWFkPgo8Ym9keT4KPGgxPkhlbGxvIEFNUEhUTUwgV29ybGQhPC9oMT4KPHA+SGF2ZSBhIGxvb2sgYXQgeW91ciBjb25zb2xlITwvcD4KPGFtcC1zdGF0ZSBpZD0idGVzdCI+CiAgICA8c2NyaXB0IHR5cGU9ImFwcGxpY2F0aW9uL2pzb24iPgogICAgICAgIHsKICAgICAgICAgICAgInZhbHVlIjogMTIzNAogICAgICAgIH0KICAgIDwvc2NyaXB0Pgo8L2FtcC1zdGF0ZT4KCjxhbXAtc2NyaXB0IHNjcmlwdD0iZG9tU2NyaXB0VG9wIiB3aWR0aD0xIGhlaWdodD0xPjwvYW1wLXNjcmlwdD4KPHNjcmlwdCBpZD0iZG9tU2NyaXB0VG9wIiB0eXBlPSJ0ZXh0L3BsYWluIiB0YXJnZXQ9ImFtcC1zY3JpcHQiPgogICAgICBBTVAuZ2V0U3RhdGUoJ3Rlc3QnKS50aGVuKChyYXdTdGF0ZSkgPT4gewogICAgICAgIGNvbnNvbGUubG9nKGBTY3JpcHQgVGFnICVjYWJvdmUlYyB0aGUgZm9sZCAlY3dpdGglYyBET00gYWNjZXNzIHNheXMgJHtyYXdTdGF0ZX1gLCBgY29sb3I6ICNlNjdlMjI7YCwgYGNvbG9yOiBibGFjaztgLCBgY29sb3I6ICMyOTgwYjk7YCwgYGNvbG9yOiBibGFjaztgKTsKICAgICAgfSkKICAgIDwvc2NyaXB0PgoKPGFtcC1zY3JpcHQgc2NyaXB0PSJub2RvbVNjcmlwdFRvcCIgbm9kb20+PC9hbXAtc2NyaXB0Pgo8c2NyaXB0IGlkPSJub2RvbVNjcmlwdFRvcCIgdHlwZT0idGV4dC9wbGFpbiIgdGFyZ2V0PSJhbXAtc2NyaXB0Ij4KICAgICAgQU1QLmdldFN0YXRlKCd0ZXN0JykudGhlbigocmF3U3RhdGUpID0+IHsKICAgICAgICBjb25zb2xlLmxvZyhgU2NyaXB0IFRhZyAlY2Fib3ZlJWMgdGhlIGZvbGQgJWN3aXRob3V0JWMgRE9NIGFjY2VzcyBzYXlzICR7SlNPTi5wYXJzZShyYXdTdGF0ZSl9YCwgYGNvbG9yOiAjZTY3ZTIyO2AsIGBjb2xvcjogYmxhY2s7YCwgYGNvbG9yOiAjMmVjYzcxO2AsIGBjb2xvcjogYmxhY2s7YCk7CiAgICAgIH0pCiAgICA8L3NjcmlwdD4KCjxkaXYgc3R5bGU9ImhlaWdodDogMjUwdmgiPgoKPC9kaXY+Cgo8YW1wLXNjcmlwdCBzY3JpcHQ9ImRvbVNjcmlwdEJvdHRvbSIgd2lkdGg9MSBoZWlnaHQ9MT48L2FtcC1zY3JpcHQ+CjxzY3JpcHQgaWQ9ImRvbVNjcmlwdEJvdHRvbSIgdHlwZT0idGV4dC9wbGFpbiIgdGFyZ2V0PSJhbXAtc2NyaXB0Ij4KICAgICAgQU1QLmdldFN0YXRlKCd0ZXN0JykudGhlbigocmF3U3RhdGUpID0+IHsKICAgICAgICBjb25zb2xlLmxvZyhgU2NyaXB0IFRhZyAlY2JlbG93JWMgdGhlIGZvbGQgJWN3aXRoJWMgRE9NIGFjY2VzcyBzYXlzICR7cmF3U3RhdGV9YCwgYGNvbG9yOiAjOWI1OWI2O2AsIGBjb2xvcjogYmxhY2s7YCwgYGNvbG9yOiAjMjk4MGI5O2AsIGBjb2xvcjogYmxhY2s7YCk7CiAgICAgIH0pCiAgICA8L3NjcmlwdD4KCjxhbXAtc2NyaXB0IHNjcmlwdD0ibm9kb21TY3JpcHRCb3R0b20iIG5vZG9tPjwvYW1wLXNjcmlwdD4KPHNjcmlwdCBpZD0ibm9kb21TY3JpcHRCb3R0b20iIHR5cGU9InRleHQvcGxhaW4iIHRhcmdldD0iYW1wLXNjcmlwdCI+CiAgICAgIEFNUC5nZXRTdGF0ZSgndGVzdCcpLnRoZW4oKHJhd1N0YXRlKSA9PiB7CiAgICAgICAgY29uc29sZS5sb2coYFNjcmlwdCBUYWcgJWNiZWxvdyVjIHRoZSBmb2xkICVjd2l0aG91dCVjIERPTSBhY2Nlc3Mgc2F5cyAke0pTT04ucGFyc2UocmF3U3RhdGUpfWAsIGBjb2xvcjogIzliNTliNjtgLCBgY29sb3I6IGJsYWNrO2AsIGBjb2xvcjogIzJlY2M3MTtgLCBgY29sb3I6IGJsYWNrO2ApOwogICAgICB9KQogICAgPC9zY3JpcHQ+CjwvYm9keT4KPC9odG1sPgo=). Just open your dev console, and you'll see that the scripts with `nodom` cannot access the `amp-state`.

![image](https://user-images.githubusercontent.com/1544760/109475075-8ec57680-7a75-11eb-8c19-2b70410c02ef.png)

## Which AMP version is affected?
At least `2101300534005`, but probably all versions are affected.

**Comment by samouri** [comment]
Thank you @dritter for the report and the minimal reproduction! We definitely intend for `nodom` amp-script's to have access to `amp-state`, so this is indeed a bug. Will fix this asap

**Comment by samouri** [comment]
There must be a race condition during hydration. 

If you call `AMP.getState` within the outer scope, you experience the highlighted behavior (`state=null`). All future calls will also result in a null state.

If the first call to AMP.getState occurs in the next macrotask, it then behaves as expected. E.g.

```js
setTimeout(() => {
  AMP.getState("test").then(s => console.error(s)); 
}, 0)
```

**Comment by samouri** [comment]
@dritter: for some reason I no longer have access to the repro case you put here.
I did notice a separate but though: `AMP.getState()` is broken when used 0-arg. It is meant to have the same behavior as `AMP.getState('.')`. Working on a fix for that now

**Comment by dritter** [comment]
Ha! It looks like decoding the base64 payload of the link doesn't work anymore...

My reproduction case is:
```html
<!DOCTYPE html>
<html ⚡>
<head>
    <meta charset="utf-8" />
    <title>My AMP Page</title>
    <link rel="canonical" href="self.html" />
    <meta name="viewport" content="width=device-width" />
    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
    <script async src="https://cdn.ampproject.org/v0.js"></script>
    <script async custom-element="amp-script" src="https://cdn.ampproject.org/v0/amp-script-0.1.js"></script>
    <script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>
    <style amp-custom>
        h1 {
            margin: 1rem;
        }
    </style>

  <meta name="amp-script-src" content="sha384-8BxJ6GkwQxZJGyzmB2t3lp6_grBNnxJ-wxVr1j8QrDFqhxuPjYPGEOmlmp_KrUN6 sha384-2KmOFAPwtTQTM79Dfpa5bBZcAib3DwlAIBFK2QxyyxgF0BZfwCGWQO9qf1HsStU8 sha384-e8vlbdz2lIddCWJ_wZCKdv0PfkkfYYqqFdpsTNuehiYfT4E1b0jrnugAnRp9FV9q sha384-4HNEt1IpPwpTJYnaztHkgk8KN0DCtTPF7m8Xt1fdwBbSnI_NWHIKqoc9XBwH97l6 ">
</head>
<body>
<h1>Hello AMPHTML World!</h1>
<p>Have a look at your console!</p>
<amp-state id="test">
    <script type="application/json">
        {
            "value": 1234
        }
    </script>
</amp-state>

<amp-script script="domScriptTop" width=1 height=1></amp-script>
<script id="domScriptTop" type="text/plain" target="amp-script">
      AMP.getState('test').then((rawState) => {
        console.log(`Script Tag %cabove%c the fold %cwith%c DOM access says ${rawState}`, `color: #e67e22;`, `color: black;`, `color: #2980b9;`, `color: black;`);
      })
    </script>

<amp-script script="nodomScriptTop" nodom></amp-script>
<script id="nodomScriptTop" type="text/plain" target="amp-script">
      AMP.getState('test').then((rawState) => {
        console.log(`Script Tag %cabove%c the fold %cwithout%c DOM access says ${JSON.parse(rawState)}`, `color: #e67e22;`, `color: black;`, `color: #2ecc71;`, `color: black;`);
      })
    </script>

<div style="height: 250vh">

</div>

<amp-script script="domScriptBottom" width=1 height=1></amp-script>
<script id="domScriptBottom" type="text/plain" target="amp-script">
      AMP.getState('test').then((rawState) => {
        console.log(`Script Tag %cbelow%c the fold %cwith%c DOM access says ${rawState}`, `color: #9b59b6;`, `color: black;`, `color: #2980b9;`, `color: black;`);
      })
    </script>

<amp-script script="nodomScriptBottom" nodom></amp-script>
<script id="nodomScriptBottom" type="text/plain" target="amp-script">
      AMP.getState('test').then((rawState) => {
        console.log(`Script Tag %cbelow%c the fold %cwithout%c DOM access says ${JSON.parse(rawState)}`, `color: #9b59b6;`, `color: black;`, `color: #2ecc71;`, `color: black;`);
      })
    </script>
</body>
</html>
```

> I did notice a separate bug that could be the cause: AMP.getState() is broken when used 0-arg. It is meant to have the same behavior as AMP.getState('.'). Working on a fix for that now

Awesome! Thank you.

**Comment by samouri** [comment]
Found a second bug. If the `stateKey` is the very first string passed to main-thread, worker-dom goofs up. Have a couple fixes coming up.
