### ISSUE TITLE
`amp-accordion` is not returning to its previous state in the case of coming back to a page

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#3298]

**Comment by cramforce** [comment]
@sriramkrish85 Are we tracking this already?
This should be fixed by storing the state in `sessionStorage`

**Comment by sriramkrish85** [comment]
@cramforce no we are not - and yes we are fixing with sessionStorage,

**Comment by rudygalfi** [comment]
Looks like work is in progress for this in #3300 so putting into Current.

**Comment by itsmsc** [comment]
The change of the functionality on a stable component without backward compatibility mode is not a good idea...  While using amp-accordion as a navigation element, i will not return to the previous state. How can i prevent store the state?

**Comment by ericlindley-g** [comment]
Good point—there's no way to prevent the storage of state right now, but I've opened a new issue as a feature request [here](https://github.com/ampproject/amphtml/issues/3813)

**Comment by sriramkrish85** [comment]
@itsmsc the state retention is only for that particular session (if you kill and open another window/session expires then state would be gone). The state is not retained for ever.

**Comment by cramforce** [comment]
It is also only for a particular URL. Every other page won't have the state
memorized. The primary use case is that a mobile browser reloads a page
after it ran out of memory and it still looks the same.

**Comment by itsmsc** [comment]
Thank you @ericlindley-g for opening the new issue.

@sriramkrish85 / @ cramforce: I'm undestand the intention and functionality of this change. But i'm working the last weeks on an project to deliver a whole website with AMP-Pages (Unfortunately not public yet). The TopLevel-Navigation (Burger-Style) and other navigation-elements on Subpages using amp-accordion. A expanded Navigation-element on return to the previous page looks like a failure. To prevent the expanding on return to the page, actually im using a small script to delete the session-storage on each page. But this is not AMP-conform and can only be a temporary fix.
