### ISSUE TITLE
🌸 Cherry-pick request for #32978 into #32757 (Approved)

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#32981]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #32978 | #32980 |     **NO**     | **YES** | **NO** | #32757                                                              |
| #32978 | #32980 |     **YES**     | **NO** | **NO** | #32874                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

See #32978.

## List the steps to manually verify the changes in this cherry-pick

See #32978.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

<_1-2 sentences summarizing the problem and root causes._>

## Impact

- <_Which users were affected? Roughly how many?_>
- <_How were users affected? E.g. partial or complete loss of functionality?_>

## Action Items

- #<_ISSUE_NUMBER_>: <_Add unit/integration/end-to-end test_>
- #<_ISSUE_NUMBER_>: <_Add monitoring for edge case via error logging_>
- #<_ISSUE_NUMBER_>: <_Refactor an easily misused API_>

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by alanorozco** [comment]
@dvoytenko Is #32980 ok to merge to proceed with cherry pick?

**Comment by dvoytenko** [comment]
@alanorozco still waiting for approvals on PRs. But hopefully soon.

**Comment by kristoferbaxter** [comment]
Approved. Left some additional notes on the PR around test coverage.

**Comment by jridgewell** [comment]
I do not believe LTS is involved in this.
