### ISSUE TITLE
Gulp Dev Server < 1s

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#33011]
**summary**
There are various tasks that happen as part of the default `gulp` lazy dev server which slow down startup time. We should speed them up.

- We build all CSS files in the whole project. They should be built per extension as they are requested instead of frontloading (4 seconds --> 0).
- We build all Jison parsers for the whole project. They too should be lazily built as part of `buildExtension`.
- We use `esbuild` for unminified builds and babel for transpilation. Without babel, `amp.js` only takes 87ms to build, and with it 5000ms. We should either cache the results to disk or figure out a way to live without babel in dev mode.

Once these 3 tasks are complete, we should be able to have the lazy dev server boot within 1s.

cc @rsimha

**Comment by samouri** [comment]
@rsimha: what is the difference between new server and old server? 

I noticed we are calling tsc during gulp startup for building the directory in `new-server/transforms/dist`, should we use esbuild instead?

**Comment by rsimha** [comment]
> @rsimha: what is the difference between new server and old server? 

It's the set of transforms that is meant to replace the old app.js. @erwinmombay  is in the process of building it out for ESM.

**Comment by samouri** [comment]
With the changes to:
1. Use esbuild
2. Lazily build jison parsers
3. Cache css and babel transforms

I'm happy to report that dev server startup times (cached) are now 1s!!

**Comment by rsimha** [comment]
These are excellent results. I just ran the server on my 2016 Macbook with a warm cache, and am indeed seeing a 1s startup time. Thanks for driving this effort, @samouri!
