### ISSUE TITLE
Support multiple extension versions between main and FIE docs

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#33020]
FIE (a4a) and main document have to allow version isolation. I.e. the main doc and a FIE doc should be able to include different versions of the same extension without conflicting with each other.

- [x] Propagate version info in the binaries
- [x] Enable `version` argument for all extension APIs
- [x] Modify FIE code to accept versions
- [x] Modify A4A to propagate versions to FIE
- [ ] Stretch goal: resolve custom element implementation classes from the ampdoc, not window.

**Comment by samouri** [comment]
What happens today if a4a and main doc have different versions?

**Comment by dvoytenko** [comment]
> What happens today if a4a and main doc have different versions?

First one wins 😨
