### ISSUE TITLE
Video buffering/scrubber may affect visual tests

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#33040]
From real world pages:

![image](https://user-images.githubusercontent.com/254946/109862743-a3d90b80-7c15-11eb-9677-f25b90831481.png)

![image](https://user-images.githubusercontent.com/254946/109862853-c66b2480-7c15-11eb-881f-ad9ebd1c65a0.png)

**Comment by alanorozco** [comment]
This may be related to video controls in general, just [hit this one](https://percy.io/ampproject/amphtml/builds/9178043/changed/519588754?browser=chrome&browser_ids=16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=360&widths=360): (mute icon changes 🔈 / 🔇)

![image](https://user-images.githubusercontent.com/254946/110007540-a4ce7380-7ccf-11eb-89ed-eed1d80e60ab.png)

**Comment by danielrozenberg** [comment]
Fixed by @Enriqe in #33878
