### ISSUE TITLE
US privacy string support for amp-ad doubleclick

### ISSUE THREAD

**Issue by apansa** [ampproject/amphtml#33046]
Right now the amp-ad tag for doubleclick ads is not setting the right tag parameter when reading US privacy strings from the amp-consent component.

For instance, considering a publisher with this configuration for amp-consent:

``` 
<amp-geo class=i-amphtml-layout-nodisplay hidden=hidden i-amphtml-layout=nodisplay layout=nodisplay><script type=application/json>{
    "ISOCountryGroups": {
        "eea": [
            "preset-eea"
        ],
        "usca": [
            "preset-us-ca"
        ]
    }
}</script></amp-geo><amp-consent class=i-amphtml-layout-nodisplay hidden=hidden i-amphtml-layout=nodisplay id=myUserConsent layout=nodisplay>
	<script type=application/json>
	{
		"consentInstanceId": "world-wide-consent",
		"consentRequired": false,
		"geoOverride": {
			"eea": {
				"consentRequired": "remote",
				"checkConsentHref": "/x/amp-consent-ccpa"
			},
			"usca": {
				"consentRequired": "remote",
				"checkConsentHref": "/x/amp-consent-ccpa"
			}
		}
	}
	</script>
</amp-consent>
```

When the the amp-consent response as define [here](https://amp.dev/documentation/components/amp-consent/#response). The us privacy string is being set on the gdpr_consent query string parameter.

For instance, when the response is like this:

```
{
	"consentRequired": true,
	"consentStateValue": "accepted",
	"consentString": "1YN",
	"expireCache": false
}
```

Then the ad request is being generated with `gdpr_consent=1YN` which is unexpected, per Ad Manager [documentation](https://support.google.com/admanager/answer/9603027?hl=en).

Given that amp-consent does not implement a way to identify the type of consent string, the doubleclick implementation will probably need to implement a way to detect it. [Here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js#L647) is where I believe the relevant code is.

**Comment by micajuine-ho** [comment]
Related to discussion https://github.com/ampproject/amphtml/issues/32712

**Comment by micajuine-ho** [comment]
Thank you for filing a detailed error report.

>  "checkConsentHref": "/x/amp-consent-ccpa"
> 
> "checkConsentHref": "/x/amp-consent-ccpa"

It would seem that the publisher is using geoOverride (amp-consent's built in geoLocation solution), to differentiate between CCPA and GDPR jurisdiction. However, they are are hitting the same endpoint. Therefore, I do not see how doing this would be helpful for them.

Instead, I would suggest that they do something like this:
```
		"geoOverride": {
			"eea": {
				"consentRequired": "remote",
				"checkConsentHref": "/x/amp-consent-ccpa?eea=1"
			},
			"usca": {
				"consentRequired": "remote",
				"checkConsentHref": "/x/amp-consent-ccpa?usca=1"
			}
		}
```

Adding on these identifying parameters will help the send amp-consent the right consent string and metadata.

The response from the `checkConsentHref`  for `ccpa` should be something like:
```
{
	"consentRequired": true,
	"consentStateValue": "accepted",
	"consentString": "IFZwEIADAALgAlgBeAGAANQAggBiAECAJkAYAA1wBwAEZAJhAV4BXwCzAFzANMAbgA34B9gECAIpARYAkuBMgEygJygUgBSICmQFSAKsgVcBV8CsgKz", // Example TCF v2 String
         "consentMetadata": {"consentStringType": 2, "gdprApplies": true} 
	"expireCache": false
}
```

The response from the `checkConsentHref`  for `eea` should be something like:
```
{
	"consentRequired": true,
	"consentStateValue": "accepted",
	"consentString": "Y1N", // Example US Privacy String
         "consentMetadata": {"consentStringType": 3, "gdprApplies": false} 
	"expireCache": false
}
```


The main difference here is that 
1.) the publishers' servers know when the request is coming from different geo locations
2.) the publisher is returning consent metadata associated with the user and user's location

This way doubleclick can get the parameter `gpdr=false` and ignore the `gdpr_consent`.
