### ISSUE TITLE
AMP validation Had errors:

### ISSUE THREAD

**Issue by willy182** [ampproject/amphtml#3304]
anybody knows where the problem is??
how do I fix it?

![error](https://cloud.githubusercontent.com/assets/15019686/15501694/0aa9bc0c-21d9-11e6-8002-e530c5dfd181.jpg)

**Comment by Meggin** [comment]
This doc should help:
https://www.ampproject.org/docs/reference/validation_errors.html

**Comment by jridgewell** [comment]
We're pretty clear with the error messages.

- Your `amp-custom` inline stylesheet is too long. You're allowed at most 50kb.
- Only `https` is allowed for sources
- `<img>` is an invalid tag in AMP, use `<amp-img>`. (`<img>` _is_ allowed under a `<noscript>`)
- You have a `;` attribute in your `<a>`? Not sure how that happened.
- `<form>` is an invalid tag in AMP. (We're [working](https://github.com/ampproject/amphtml/pull/3251) on it).
