### ISSUE TITLE
Intent to implement: O2Player embed

### ISSUE THREAD

**Issue by yevheniiminin** [ampproject/amphtml#3306]
This proposed amp-o2player component would embed a responsive O2Player in an iframe. This single component would support publishers using AOL O2Player.

Example:

<amp-o2player
    data-vid="57029f58e4b09a9cae6cc82f"
    width="480" height="270">
</amp-o2player>
The above would yield http://delivery.vidible.tv/htmlembed/57029f58e4b09a9cae6cc82f.html.

The component supports a pause postMessage event to pause the video.

**Comment by yevheniiminin** [comment]
#3305

**Comment by adelinamart** [comment]
What's the status here? Thanks

**Comment by jridgewell** [comment]
Closed by https://github.com/ampproject/amphtml/pull/3305.
