### ISSUE TITLE
hasNextNodeInDocumentOrder causes infinite loop

### ISSUE THREAD

**Issue by ericfs** [ampproject/amphtml#3309]
It always sets currentElement = element.parentNode instead of currentElement.parentNode
https://github.com/ampproject/amphtml/blob/master/src/dom.js#L402

**Comment by erwinmombay** [comment]
@mkhatib assigned to you

**Comment by erwinmombay** [comment]
introduced in https://github.com/ampproject/amphtml/pull/3174 which is currently in this weeks opt-in canary

**Comment by dvoytenko** [comment]
Is this already in PROD?

**Comment by jridgewell** [comment]
Closed by #3310.
