### ISSUE TITLE
I2I: overflow button

### ISSUE THREAD

**Issue by pkolenic** [ampproject/amphtml#33168]
## Summary

Create a new component that wraps the html for an overflow snippet and allows customizing the color and text of the included button

## Design document

@TODO

## Motivation

We provide an ad network that serves ads to multiple websites.  As part of our integration we suggest that they include an overflow element to encourage site visitors to engage with and expand our ads to their full size when amp determines that they should not be rendered full size initially.

Our current overflow snippet is:
```html
<div overflow="" tabindex="0" role="button" aria-label="Read more" style="width: 100%; top: 0; height: 100%;">
   <div class="wrapper" style="display: flex; flex-flow: column; height: 100%; background-color: rgba(255,255,255,0.75);">
      <div class="content-show" style="flex: 1 1 auto; background-color: transparent"></div>
      <div class="button-wrapper" style="flex: 0 1 48px; background-color: #fff; justify-content: center; display: flex;">
         <button style="background-color: transparent; color: #0058FF; border: 2px solid #0058FF; border-radius: .25rem;
              font-size: 16px; font-weight: 700; letter-spacing: .1rem; padding: 10px 35px; text-align: center; 
              font-family: 'Roboto', 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif;"
         >
            See more
         </button>
      </div>
   </div>
</div>
```

This proposed component would allow calling with a custom **color** and **cta**, but also have a default **color** and **cta**:
```html
<amp-ad height="150" type="myfinance" data-ad-type="widget" data-test="true">
  <amp-overflow-button overflow> </amp-overflow-button>
</amp-ad>
```
<img width="245" alt="default_color_cta" src="https://user-images.githubusercontent.com/1160003/112868243-11dbeb80-9079-11eb-89c2-01486edb995c.png">

```html
<amp-ad height="150" type="myfinance" data-ad-type="widget" data-test="true">
  <amp-overflow-button overflow color="#B80000" cta="Show more"> </amp-overflow-button>
</amp-ad>_
```
<img width="245" alt="custom_color_cta" src="https://user-images.githubusercontent.com/1160003/112868254-143e4580-9079-11eb-9105-dcad9e2b1f22.png">

/cc @ampproject/wg-approvers
/cc @ampproject/wg-ads

**Comment by alanorozco** [comment]
**This I2I must go through design review.**

@pkolenic Please clarify the motivation for this change. I don't see why we would need to wrap CSS in a component.

@ampproject/wg-monetization Do you have any context on this?

**Comment by pkolenic** [comment]
Our Ad Network is utilized across several internal and external teams.  Having the overflow as a multiple element template is a deterrent for some additional teams integrating our Ad Network into their AMP content.  This purposed component reduces the overhead into a single element, while allowing the easy of setting the color and text for the overflow.

As this component does not introduce any new functionality, only wraps a more complex template, I didn't think that it would constitute as a Significant Change and therefore warrant a formal design review.

**Comment by calebcordry** [comment]
I tend to agree with @alanorozco that this seems like overkill for the use case. Would it be possible to move the button creation logic to your js implementation? Something like `requestResize().catch(() => createButtonInsideFrame)`  I dont think this needs to be in the parent doc, and you could potentially have greater control.

cc/ @powerivq who is the 3p expert. Does this sound reasonable to you, or any thoughts?

**Comment by alanorozco** [comment]
> As this component does not introduce any new functionality, only wraps a more complex template, I didn't think that it would constitute as a Significant Change and therefore warrant a formal design review.

All new components require design review. Maybe we need to clarify in docs if not present.

**Comment by pkolenic** [comment]
> I tend to agree with @alanorozco that this seems like overkill for the use case. Would it be possible to move the button creation logic to your js implementation? Something like `requestResize().catch(() => createButtonInsideFrame)` I dont think this needs to be in the parent doc, and you could potentially have greater control.
> 
> cc/ @powerivq who is the 3p expert. Does this sound reasonable to you, or any thoughts?

If we were to investigate this approach ... what is the callback mechanism for the ad to know it has been interacted with so it can then hide the overflow button?

**Comment by pkolenic** [comment]
@alanorozco @calebcordry 
I managed to figure out how to work the .catch() and .then() for `window.context.requestResize()`.
Other than not being able to allow for custom button text (which we could always add later as a parameter for our ad-network) we appear good on our end to close this I2I and the accompanying PR

**Comment by calebcordry** [comment]
Glad you were able to find a solution!
