### ISSUE TITLE
[Story video] Looping videos could get downgraded due to nontrivialWait

### ISSUE THREAD

**Issue by mszylkowski** [ampproject/amphtml#33169]
When a video is looped, it will send a `waiting` event followed by a `playing` event. This could cause a `onNontrivialWait` (my tests are that this wait is around 70ms so not enough to trigger the delay of 100ms) but conceptually we need to prevent triggering a downgrade in this case.

Possible solutions:
- Do not downgrade if the video that requested the downgrade is fully loaded.
- Do not downgrade when there is a time change (might have other consequences)
- Do not downgrade when the video time is 0 or the duration of the video (should be able to check the value)

cc/ @ampproject/wg-stories

**Comment by gmajoulet** [comment]
> Do not downgrade when the video time is 0 or the duration of the video (should be able to check the value)

This one sounds right, if `currentTime` is consistently 0 (or equal to `duration`) when the `waiting` event is dispatched.

**Comment by newmuis** [comment]
Wait, wouldn't that mean not being able to downgrade on really poor connections?  If I'm on 2G or something, I'd be forced to load enough frames for playback to begin before downgrading to a lower quality?

**Comment by mszylkowski** [comment]
So I've tested the `video.currentTime` and it's never 0 when it gets replayed (the value is around `0.001s`). Luckily enough, I've previously implemented a `getBufferedPercentage` that already doesn't downgrade any videos that are loaded, but this doesn't prevent the current video from downgrading other videos that are not loaded yet. Therefore, we should check that the buffer is not full for the current video before downgrading. The rule that we can implement would be: **"Do not cause a downgrade of other videos if the current video is completely loaded and there's a nontrivial wait"**, because the nontrivial wait could not be possibly caused by a networking lag (since the video is fully buffered, it must be due to the video reloading).
