### ISSUE TITLE
🌸 Cherry pick request for #33181 into #32874 #33053 (Pending)

### ISSUE THREAD

**Issue by mszylkowski** [ampproject/amphtml#33172]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #33171 | #33181 |     Yes     | Yes | No | #32874 #33053                                                               |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

The bug "break existing AMP web pages in a significant way" meaning that all stories served from the cache have a high chance of failing to load the videos, causing the videos to flash while they get in a loop calling `video.load()` nonstop.

## List the steps to manually verify the changes in this cherry-pick

Without the fix, on Chrome Incognito + Slow 3g Network + Disable Cache the videos don't load (but will blink nonstop) for the story `examples/amp-story/videos-cdn.html`. When disabling the experiment, the video will load roperly

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

Videos can send a `waiting` event followed by a `playing` event when first loaded, and this can force a bitrate downgrade because the flexible bitrate algorithm thinks it's a rebuffering. When the downgrade happens directly to the original source (because the connection is too slow for any of the cached bitrates), it will think that the current bitrate is infinity, which breaks the loading and causes a loop of loads

## Impact

- Stories with cached videos flash, while the story shows "Video failed to load"

## Action Items

- Added test to prevent downgrades when the video failed before loading

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by jridgewell** [comment]
Approved.

**Comment by newmuis** [comment]
@mszylkowski can you populate which release this needs to go into?

**Comment by lannka** [comment]
please update here when the PR is merged

**Comment by lannka** [comment]
i noticed that the "Release issue" box is filled with 2 releases. one is LTS built on 2021-02-20. is that also affected?

**Comment by mszylkowski** [comment]
I assume stable is also LTS for this release, so yes. Also, just merged the PR
