### ISSUE TITLE
Research and make a decision on whether `body` needs `width: 100%`

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#3318]
AMP exercises a great control over `body` element at this time, e.g. by forcing `overflow-x: hidden` on it and other CSS properties. We may also want to add `body {width: 100%}`. Some reasons why this may be needed:
1. The general goal is to ensure that the content properly fist within the visible viewport horizontally. This matters on mobile since we allow horizontal swipe to navigate between documents.
2. To reconcile differences between different embedding modes, such as iframes vs standalone. E.g. currently on iOS we implicitly have `width = 100%`.
3. It might be better due to `overflow-x: hidden`.

If necessary to experiment with this, this work should proceed via an experiment.

**Comment by rudygalfi** [comment]
Putting in Backlog for now. @jridgewell, if you plan to work on soon, please change to Current or Next as appropriate. Thanks!

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
