### ISSUE TITLE
Web Stories - Allow first slide CTAs to link to disclosures/legal docs at the end of the story

### ISSUE THREAD

**Issue by Dbrown910** [ampproject/amphtml#33191]
## Describe the new feature or change to an existing feature you'd like to see
Allowing the `<amp-story-cta-layer>` component to be used on the first slide so users can go to legal disclosures within the story in one click. It is disabled on the first slide of Web Stories as seen in its code on [line 59](https://github.com/ampproject/amphtml/blob/master/examples/visual-tests/amp-story/amp-story-cta-layer.html)

## Describe alternatives you've considered
Currently using a tooltip which achieves the desired result, but it takes two clicks (one to open the tooltip and another to trigger navigation)

## Additional context
[Demo Story](https://www-amp.bankofamerica.com/amp-stories/gender-lens-investing/)

**Comment by newmuis** [comment]
@Dbrown910 can you use `<amp-story-consent>` for your use case?  See https://amp.dev/documentation/examples/user-consent/story_user_consent/#implementing-user-consent-inside-an-amp-story
