### ISSUE TITLE
Poll and Quiz : text-align issue for the text options

### ISSUE THREAD

**Issue by lougea** [ampproject/amphtml#33206]
## What's the issue?

Text-align in poll and quiz options

When the string option is too long, the text-align is center.

![Screenshot from 2021-03-11 17-22-14](https://user-images.githubusercontent.com/45533830/110821856-c5c73380-8290-11eb-8676-c9c1dc644d74.png)

## How do we reproduce the issue?

[https://report.tappable-dev.link/poll-and-quizz-text-align-issue?story](url)

## What browsers are affected?

For Chrome, edge, opera : quiz and poll have the issue
For mozilla , safari : poll had the issue

**Comment by mszylkowski** [comment]
Thanks for reporting the bug, seems like this is beacuse we recently changed the options to use `<button>` tags for accessibility, and buttons by default have text centered instead of the initial alignment.
