### ISSUE TITLE
🌸 Cherry-pick request for #33207 into #33053 (Pending)

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#33221]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #33207 | #33207 |     **NO**     | **YES** | **NO** | #33053                                                             |
| #33207 | #33207 |     **YES**     | **NO** | **NO** | #33224                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

Data suggests some CLS violations are occurring either before FCP, before iframe visibility, or both. We need to investigate this on a global level on the whole corpus so we can report to the appropriate channels or fix it ourselves.

## Why is an LTS cherry-pick needed?

<_YOUR_REASONS_>

## List the steps to manually verify the changes in this cherry-pick

<_TEST_STEPS_>

# Mini-postmortem

N/A

## Summary

Data suggests some CLS violations are occurring either before FCP, before iframe visibility, or both. We need to investigate this on a global level on the whole corpus so we can report to the appropriate channels or fix it ourselves.
## Impact

N/A

## Action Items

N/A

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by erwinmombay** [comment]
cc @kristoferbaxter

**Comment by kristoferbaxter** [comment]
Approved.

**Comment by rcebulko** [comment]
Was this every CP'd into the release?

**Comment by erwinmombay** [comment]
yes. closing
