### ISSUE TITLE
Duplicate "more" icon on Web Stories social sharing config 

### ISSUE THREAD

**Issue by LuckynaSan** [ampproject/amphtml#33220]
## What's the issue?

One 1 "more" icon should be configured.

## How do we reproduce the issue?

1. Open a Web Story ([example story URL](https://sgsite.cmsdevrel.com/web-stories/example-story-1/)) on BrowserStack or on any of the following devices: iPhone 11, iPhone 12, Galaxy S9
2. Wait until the last slide to see social sharing options pop up. Notice duplicate "more" icon.

## What browsers are affected?
Tested in Safari, Chrome on mobile devices such as iPhone 11, iPhone 12, Galaxy S9

## Screenshots
![image](https://user-images.githubusercontent.com/66372350/110856626-e0e07600-8285-11eb-934c-ff603976f773.png)
![image](https://user-images.githubusercontent.com/66372350/110856631-e473fd00-8285-11eb-870b-bcceb857fea7.png)

**Comment by ychsieh** [comment]
Not reproducible.
