### ISSUE TITLE
Add support for viewers scrolling away UI during document consumption

### ISSUE THREAD

**Issue by ericfs** [ampproject/amphtml#3323]
E.g. a viewer might show the origin of the doc and may want to hide that as the user scrolls down, but show it again when they scroll up.

Event should be send on `scroll` event and contain `scrollTop` and potentially the cached `scrollHeight`

**Comment by cramforce** [comment]
@ericfs Tuned your description a bit :)

Assigned to @muxin

**Comment by jridgewell** [comment]
The converse of this would enable "tap scrollbar to scroll to top" in iOS. If a user does, it'll trigger a scroll event (if the viewer is not already at the top) in the viewer window. If we send down that scroll event, we can scroll to the top of the AMP doc as well.

**Comment by rudygalfi** [comment]
Putting in Backlog for now. @muxin, if you plan to work on soon, please change to Current or Next as appropriate. Thanks!

**Comment by ericfs** [comment]
Thanks for taking this. It looks like only scrollTop is sent and not scrollHeight. Is it possible to get the height too?

**Comment by cramforce** [comment]
Hmm, when @muxin and I looked at this, it seemed we sent this already, but now I can't find it. We certainly can.

@dvoytenko ScrollHeight is currently not cached. Could we start only recalculating it when we mutated the doc or the viewport changed?

**Comment by dvoytenko** [comment]
@cramforce We used to do it and I asked it to be removed (/cc @jridgewell) due to some problems in the way we implemented it. We can bring this back if it's really necessary, but we need to see how. We used to do it in each runtime pass and that was fairly expensive. I think, a better option might be to do it for scroll events specifically, but only calculate `scrollHeight` once for scroll series.

**Comment by ericfs** [comment]
scrollHeight would be helpful, if it's available, particularly to know when the scroll reaches the bottom, but I think we can manage without it.

**Comment by dvoytenko** [comment]
@ericfs but what would be the most applicable target message for this info? `scroll` message?

**Comment by ericfs** [comment]
Yes, that would be fine.

**Comment by jridgewell** [comment]
Re: https://github.com/ampproject/amphtml/issues/3515. If we do reintroduce it, we need to cache.

**Comment by cramforce** [comment]
Can we update scroll height:

- after we build an element
- after resize
- after mutate

Are there other situations where it might change?

**Comment by cramforce** [comment]
@ericfs Do you need a precise value?

**Comment by ericfs** [comment]
I think it would be preferable, but I think I can work with whatever you can provide. Ideally a Viewer would know when the page is scrolled to the bottom, but an estimate may be ok.
