### ISSUE TITLE
🌸 Cherry-pick request for #33275 into #33276 (Pending)

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#33277]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #33274 | #33275 |     **YES**     | **NO** | **NO** | #33276                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

The launch of this feature breaks partner ad networks that are relying on  properties of the `<body>` element to animate creatives. 

## List the steps to manually verify the changes in this cherry-pick

- Go to https://amp-ads-perf.glitch.me/single-img.html
- Open devtools 
- Inspect the value of the `srcdoc` attribute of `amp-ad>iframe` and ensure that in the string the body has content.

Bad:
![image](https://user-images.githubusercontent.com/16087874/111218341-d2e76980-8593-11eb-9c3d-fbc785e31281.png)
Good:
![image](https://user-images.githubusercontent.com/16087874/111218586-2a85d500-8594-11eb-9a0e-1afc1118165a.png)

# Mini-postmortem

No cherry pick to stable necessary.

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by rcebulko** [comment]
@calebcordry Could you clarify if this does or does not need to be CP'd into Stable? The table at the top of the issue says it does, but the Mini-postmortem section does not. Want to make sure before promoting

**Comment by calebcordry** [comment]
Sorry, no stable pick necessary. Corrected the table.

**Comment by rsimha** [comment]
Closing now that this is a part of https://github.com/ampproject/amphtml/commits/2103122145002 and all fields have been filled out.
