### ISSUE TITLE
Allow use amp-iframe inside amp-sidebar

### ISSUE THREAD

**Issue by slivorezka** [ampproject/amphtml#3328]
Hi guys!
Can we allow use `apm-iframe` inside `amp-sidebar`?
I seen in the [amp-iframe rules](https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/0.1/validator-amp-iframe.protoascii) 
... `disallowed_ancestor: "amp-sidebar"` ...

So why we have this disallow rule?

Tahaks!

**Comment by sriramkrish85** [comment]
@slivorezka what is the use-case? 

CC @ericlindley-g @rudygalfi

**Comment by slivorezka** [comment]
@sriramkrish85 
For example some forms, search form, etc by iframe inside `amp-sidebar`
I think it is necessary functionality.

**Comment by rudygalfi** [comment]
There is work for forms tracked by #1286 with initial implementation in #3251. Direct support rather than via amp-iframe will be the way to go here.
