### ISSUE TITLE
[amp-carousel]control buttons are out of sync with the slide numbers in the amp-carousel

### ISSUE THREAD

**Issue by otsuky** [ampproject/amphtml#33287]
## What's the issue?

When amp-carousel is used inside amp-lightbox, left and right arrow buttons are out of sync with the slide numbers in the carousel.

I expect the following behavior from amp-carousel, but it doesn't seem to work that way if I use amp-carousel inside amp-lightbox.
- when the first slide is displayed in amp-carousel, only the right button to be displayed
- when the last slide is displayed in amp-carousel, only the left button to be displayed
- In other cases, both left and right buttons will be displayed

## How do we reproduce the issue?

1. open [my playground](https://playground.amp.dev/#share=PCFET0NUWVBFIGh0bWw+CjxodG1sIOKaoT4KICA8aGVhZD4KICAgIDxtZXRhIGNoYXJzZXQ9InV0Zi04IiAvPgogICAgPHRpdGxlPmFtcC1saWdodGJveC1jYXJvdXNlbDwvdGl0bGU+CiAgICA8bGluayByZWw9ImNhbm9uaWNhbCIgaHJlZj0iYW1wcy5odG1sIiAvPgogICAgPG1ldGEKICAgICAgbmFtZT0idmlld3BvcnQiCiAgICAgIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCxtaW5pbXVtLXNjYWxlPTEsaW5pdGlhbC1zY2FsZT0xIgogICAgLz4KICAgIDxzY3JpcHQKICAgICAgYXN5bmMKICAgICAgY3VzdG9tLWVsZW1lbnQ9ImFtcC1saWdodGJveCIKICAgICAgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC9hbXAtbGlnaHRib3gtMC4xLmpzIgogICAgPjwvc2NyaXB0PgogICAgPHNjcmlwdAogICAgICBhc3luYwogICAgICBjdXN0b20tZWxlbWVudD0iYW1wLWNhcm91c2VsIgogICAgICBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1jYXJvdXNlbC0wLjIuanMiCiAgICA+PC9zY3JpcHQ+CiAgICA8c2NyaXB0CiAgICAgIGFzeW5jCiAgICAgIGN1c3RvbS1lbGVtZW50PSJhbXAtc2VsZWN0b3IiCiAgICAgIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAvYW1wLXNlbGVjdG9yLTAuMS5qcyIKICAgID48L3NjcmlwdD4KICAgIDxzdHlsZSBhbXAtY3VzdG9tPgogICAgICBib2R5IHsKICAgICAgICBwYWRkaW5nOiAxMHB4OwogICAgICB9CiAgICAgIC5pbm5lciB7CiAgICAgICAgZGlzcGxheTogZmxleDsKICAgICAgICBnYXA6IDEwcHg7CiAgICAgIH0KICAgICAgLmltYWdlIHsKICAgICAgICB3aWR0aDogMzAwcHg7CiAgICAgIH0KICAgICAgLmltYWdlICsgLmltYWdlIHsKICAgICAgICBtYXJnaW4tbGVmdDogMTBweDsKICAgICAgfQogICAgICAubGlnaHRib3ggewogICAgICAgIGJhY2tncm91bmQtY29sb3I6IGJsYWNrOwogICAgICB9CiAgICAgIC5jbG9zZS1idXR0b24gewogICAgICAgIHBvc2l0aW9uOiBhYnNvbHV0ZTsKICAgICAgICB6LWluZGV4OiAxOwogICAgICB9CiAgICA8L3N0eWxlPgogICAgPHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1vei1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDstbXMtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7YW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGh9QC13ZWJraXQta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtbW96LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1zLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW8ta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUBrZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19PC9zdHlsZT48bm9zY3JpcHQ+PHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOm5vbmU7LW1vei1hbmltYXRpb246bm9uZTstbXMtYW5pbWF0aW9uOm5vbmU7YW5pbWF0aW9uOm5vbmV9PC9zdHlsZT48L25vc2NyaXB0PgogICAgPHNjcmlwdCBhc3luYyBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwLmpzIj48L3NjcmlwdD4KICA8L2hlYWQ+CiAgPGJvZHk+CiAgICA8aDI+YW1wLWxpZ2h0Ym94LWNhcm91c2VsPC9oMj4KICAgIDxhbXAtc2VsZWN0b3IKICAgICAgaWQ9InNlbGVjdG9yMSIKICAgICAgb249InNlbGVjdDpjYXJvdXNlbDEuZ29Ub1NsaWRlKGluZGV4PWV2ZW50LnRhcmdldE9wdGlvbiksIGxpZ2h0Ym94MSIKICAgID4KICAgICAgPGRpdiBjbGFzcz0iaW5uZXIiPgogICAgICAgIDxhbXAtaW1nCiAgICAgICAgICBjbGFzcz0iaW1hZ2UiCiAgICAgICAgICBzcmM9Imh0dHA6Ly9wbGFjZWtpdHRlbi5jb20vNDUwLzMwMD9pbWFnZT0xIgogICAgICAgICAgb3B0aW9uPSIwIgogICAgICAgICAgbGF5b3V0PSJyZXNwb25zaXZlIgogICAgICAgICAgd2lkdGg9IjQ1MCIKICAgICAgICAgIGhlaWdodD0iMzAwIgogICAgICAgID48L2FtcC1pbWc+CiAgICAgICAgPGFtcC1pbWcKICAgICAgICAgIGNsYXNzPSJpbWFnZSIKICAgICAgICAgIHNyYz0iaHR0cDovL3BsYWNla2l0dGVuLmNvbS80NTAvMzAwP2ltYWdlPTIiCiAgICAgICAgICBsYXlvdXQ9InJlc3BvbnNpdmUiCiAgICAgICAgICBvcHRpb249IjEiCiAgICAgICAgICB3aWR0aD0iNDUwIgogICAgICAgICAgaGVpZ2h0PSIzMDAiCiAgICAgICAgPjwvYW1wLWltZz4KICAgICAgICA8YW1wLWltZwogICAgICAgICAgY2xhc3M9ImltYWdlIgogICAgICAgICAgc3JjPSJodHRwOi8vcGxhY2VraXR0ZW4uY29tLzQ1MC8zMDA/aW1hZ2U9MyIKICAgICAgICAgIGxheW91dD0icmVzcG9uc2l2ZSIKICAgICAgICAgIG9wdGlvbj0iMiIKICAgICAgICAgIHdpZHRoPSI0NTAiCiAgICAgICAgICBoZWlnaHQ9IjMwMCIKICAgICAgICA+PC9hbXAtaW1nPgogICAgICAgIDxhbXAtaW1nCiAgICAgICAgICBjbGFzcz0iaW1hZ2UiCiAgICAgICAgICBzcmM9Imh0dHA6Ly9wbGFjZWtpdHRlbi5jb20vNDUwLzMwMD9pbWFnZT00IgogICAgICAgICAgbGF5b3V0PSJyZXNwb25zaXZlIgogICAgICAgICAgb3B0aW9uPSIzIgogICAgICAgICAgd2lkdGg9IjQ1MCIKICAgICAgICAgIGhlaWdodD0iMzAwIgogICAgICAgID48L2FtcC1pbWc+CiAgICAgIDwvZGl2PgogICAgPC9hbXAtc2VsZWN0b3I+CiAgICA8YW1wLWxpZ2h0Ym94IGlkPSJsaWdodGJveDEiIGNsYXNzPSJsaWdodGJveCIgbGF5b3V0PSJub2Rpc3BsYXkiPgogICAgICA8YnV0dG9uIGNsYXNzPSJjbG9zZS1idXR0b24iIG9uPSJ0YXA6bGlnaHRib3gxLmNsb3NlIj5jbG9zZTwvYnV0dG9uPgogICAgICA8YW1wLWNhcm91c2VsCiAgICAgICAgaWQ9ImNhcm91c2VsMSIKICAgICAgICB3aWR0aD0iOTAwIgogICAgICAgIGhlaWdodD0iNjAwIgogICAgICAgIGxheW91dD0iZmlsbCIKICAgICAgICB0eXBlPSJzbGlkZXMiCiAgICAgICAgb249InNsaWRlQ2hhbmdlOnNlbGVjdG9yMS50b2dnbGUoaW5kZXg9ZXZlbnQuaW5kZXgsIHZhbHVlPXRydWUpIgogICAgICA+CiAgICAgICAgPGFtcC1pbWcKICAgICAgICAgIHNyYz0iaHR0cDovL3BsYWNla2l0dGVuLmNvbS85MDAvNjAwP2ltYWdlPTEiCiAgICAgICAgICBsYXlvdXQ9InJlc3BvbnNpdmUiCiAgICAgICAgICB3aWR0aD0iOTAwIgogICAgICAgICAgaGVpZ2h0PSI2MDAiCiAgICAgICAgPjwvYW1wLWltZz4KICAgICAgICA8YW1wLWltZwogICAgICAgICAgc3JjPSJodHRwOi8vcGxhY2VraXR0ZW4uY29tLzkwMC82MDA/aW1hZ2U9MiIKICAgICAgICAgIGxheW91dD0icmVzcG9uc2l2ZSIKICAgICAgICAgIHdpZHRoPSI5MDAiCiAgICAgICAgICBoZWlnaHQ9IjYwMCIKICAgICAgICA+PC9hbXAtaW1nPgogICAgICAgIDxhbXAtaW1nCiAgICAgICAgICBzcmM9Imh0dHA6Ly9wbGFjZWtpdHRlbi5jb20vOTAwLzYwMD9pbWFnZT0zIgogICAgICAgICAgbGF5b3V0PSJyZXNwb25zaXZlIgogICAgICAgICAgd2lkdGg9IjkwMCIKICAgICAgICAgIGhlaWdodD0iNjAwIgogICAgICAgID48L2FtcC1pbWc+CiAgICAgICAgPGFtcC1pbWcKICAgICAgICAgIHNyYz0iaHR0cDovL3BsYWNla2l0dGVuLmNvbS85MDAvNjAwP2ltYWdlPTQiCiAgICAgICAgICBsYXlvdXQ9InJlc3BvbnNpdmUiCiAgICAgICAgICB3aWR0aD0iOTAwIgogICAgICAgICAgaGVpZ2h0PSI2MDAiCiAgICAgICAgPjwvYW1wLWltZz4KICAgICAgPC9hbXAtY2Fyb3VzZWw+CiAgICA8L2FtcC1saWdodGJveD4KICA8L2JvZHk+CjwvaHRtbD4K).
2. click the second image.
![スクリーンショット 2021-03-16 13 45 08](https://user-images.githubusercontent.com/26247828/111257230-1b6b5980-865e-11eb-8006-dd24f2928613.png)

3. the lightbox will open and the second image will be displayed, but you can see that only the right  button is displayed, the left button is not.
<img width="400" src="https://user-images.githubusercontent.com/26247828/111257463-8a48b280-865e-11eb-9782-73de7064b8ee.png" />

## What browsers are affected?
All browsers.

## Which AMP version is affected?
- LTS version of amp
- amp-carousel v0.2
- amp-lightbox v0.1
- amp-selector v0.1

**Comment by otsuky** [comment]
This problem does not occur in amp-carousel v0.1, but it does in v0.2.

**Comment by micajuine-ho** [comment]
This issue seems to be fixed now.
