### ISSUE TITLE
Intent-to-Remove: amp-sidebar in amp-story

### ISSUE THREAD

**Issue by mszylkowski** [ampproject/amphtml#33293]
## Summary

I2D: #26958

The `<amp-sidebar>` feature in stories has not achieved scale, but is creating an inconsistent user experience. It has also been brought up that the feature is an anomaly, as it's not one that's generally supported in story platforms. This has been demonstrated by the low adoption since launch, as compared to other features.

## Rollout plan

After a period of 6 weeks (so at least May 11), we will deprecate the feature by removing its documentation and making its markup a no-op (documents will remain valid AMP).

This will make stories that have sidebar to not show the sidebar icon any more, so the sidebar cannot be triggered. The story itself will remain unchanged, and the pages are not affected by this removal.

## Alternative implementation suggestion for developers using AMP

Rather than using links within a sidebar, publishers can look to these following suggestions:

1.  Publishers can use `<a>` tags directly within their [`<amp-story-grid-layer>`](https://amp.dev/documentation/components/amp-story/?format=stories#links-in-amp-story-grid-layer) or [`<amp-story-cta-layer>`](https://amp.dev/documentation/components/amp-story-cta-layer/) tags
1.  Publishers may load additional context in [`<amp-story-page-attachment>`](https://amp.dev/documentation/components/amp-story-page-attachment/)
1.  Publishers can use [`<amp-story-player>`](https://github.com/ampproject/amphtml/blob/master/spec/amp-story-player.md) to embed their story in another page, containing custom UI to present this data. Check a demo of this at https://codepen.io/mszylkowski/pen/dyOLKgE

## Additional context

/cc @ampproject/wg-approvers

**Comment by kristoferbaxter** [comment]
Can you elaborate on 'We will trigger warnings to inform publishers of the deprecation on a wider scale.'?

**Comment by mszylkowski** [comment]
@kristoferbaxter  It's talking about triggering the deprecation warnings on validation, refer to #33328.

**Comment by kristoferbaxter** [comment]
For clarification this is how I understand 'We will trigger warnings to inform publishers of the deprecation on a wider scale.'

a. Console warnings for developers building Web Stories appear for deprecated components.
b. Validation issues warnings for deprecated components, which also are available via Google Search Console and similar tools.
c. Authors of Web Stories editors are proactively informed giving them time to complete changes within the 6 week window.

**Comment by gmajoulet** [comment]
This is correct. At the end of the 6 weeks window, amp-sidebar within a Story will simply be ignored. Users won't have any UI/UX affordance to open it, but the rest of the document will still be working just like before. Documents will remain valid AMP.

friendly ping @Gregable @kristoferbaxter

**Comment by Gregable** [comment]
Approval from me. The feature appears to be very infrequently used.

**Comment by kristoferbaxter** [comment]
Approved here too. Thanks for the clarification!

**Comment by newmuis** [comment]
Approved!

**Comment by gmajoulet** [comment]
Last item before closing this ticket: let's remove the dead code.
