### ISSUE TITLE
amp-ad-custom broken in latest release

### ISSUE THREAD

**Issue by dianomi-mjs** [ampproject/amphtml#33317]
Hi

amp-ad-custom appears to have suddenly stopped working over the last few hours.

An example test is here:

https://www.marketviews.com/dianomi/amp-demo/?amp

which gives javascript errors for an element not found in the template (it is there)

I've removed the analytics section for testing purposes and then I get no errors, but no content either

https://www.dianomi.com/mjs/amp/demo.epl?smartad_id=6369

The template looks fine, but for some reason refuses to render.

I've reverted to RTV 012103020156003 and this makes the above work again. So it appears something has broken for us in the latest versions. Can you please address this as soon as possible?

cc: @jasti @lannka

**Comment by dianomi-mjs** [comment]
cc: @micajuine-ho

**Comment by micajuine-ho** [comment]
> I've removed the analytics section for testing purposes and then I get no errors, but no content either

The error is coming from analytics, stating that the element is not found, so when you remove analytics it makes sense that the error disappears, but nothing else happens. 

Adding the @ampproject/wg-monetization  for ideas on why the `amp-ad-custom` isn't rendering.

**Comment by michael-stevens** [comment]
The javascript error we see is:

Element "#dianomi-amp-ad" not found:  null
Cf @ error.js:205
(anonymous) @ error.js:133
g.assert @ log.js:426
jb @ log.js:628
g.assertElement @ log.js:445
(anonymous) @ analytics-root.js:241
Promise.then (async)
push.f.l.getElement @ analytics-root.js:220
push.f.l.getElements @ analytics-root.js:357
push.f.l.add @ events.js:1517
c @ analytics-group.js:97
push.f.ge.addTrigger @ analytics-group.js:110
mf @ amp-analytics.js:429
(anonymous) @ amp-analytics.js:388
Promise.then (async)
(anonymous) @ amp-analytics.js:386
Promise.then (async)
push.f.l.hd @ amp-analytics.js:364
Promise.then (async)
ef @ amp-analytics.js:252
push.f.l.layoutCallback @ amp-analytics.js:156
(anonymous) @ custom-element.js:1409
(anonymous) @ promise.js:75
sb @ promise.js:74
Pi.b.layoutCallback @ custom-element.js:1409
(anonymous) @ resource.js:955
fm @ vsync-impl.js:469
g.Dh @ vsync-impl.js:426
bj.Lc @ pass.js:109
wg @ pass.js:55
(anonymous) @ timer-impl.js:86
setTimeout (async)
g.delay @ timer-impl.js:92
bj.schedule @ pass.js:94
dm @ vsync-impl.js:395
g.Aa @ vsync-impl.js:386
g.run @ vsync-impl.js:188
g.mutate @ vsync-impl.js:228
(anonymous) @ resource.js:952
push.f.h.startLayout @ resource.js:951
(anonymous) @ inabox-resources.js:230
push.f.h.zb @ inabox-resources.js:223
push.f.ae.pa @ pass.js:109
vb @ pass.js:55
(anonymous) @ timer-impl.js:86
setTimeout (async)
push.f.h.delay @ timer-impl.js:92
push.f.ae.schedule @ pass.js:94
push.f.h.schedulePass @ inabox-resources.js:169
(anonymous) @ inabox-resources.js:252
Promise.then (async)
push.f.h.Xa @ inabox-resources.js:252
push.f.h.upgraded @ inabox-resources.js:143
Pi.b.zd @ custom-element.js:379
Pi.b.ig @ custom-element.js:1105
Pi.b.Ae @ custom-element.js:1043
Pi.b.upgrade @ custom-element.js:350
Ui @ custom-element-registry.js:103
Si @ custom-element-registry.js:46
om @ extensions-impl.js:367
nm @ extensions-impl.js:355
(anonymous) @ extensions-impl.js:317
(anonymous) @ extensions-impl.js:473
(anonymous) @ extensions-impl.js:471
Promise.then (async)
g.installExtensionInDoc @ extensions-impl.js:469
(anonymous) @ extensions-impl.js:223
Promise.then (async)
g.installExtensionForDoc @ extensions-impl.js:223
Pi.b.connectedCallback @ custom-element.js:969
Vi @ custom-element-registry.js:175
Xi @ custom-element-registry.js:148
(anonymous) @ extensions-impl.js:440
g.preinstallEmbed @ extensions-impl.js:436
(anonymous) @ friendly-iframe-embed.js:819
Promise.then (async)
wf @ friendly-iframe-embed.js:815
(anonymous) @ friendly-iframe-embed.js:273
Promise.then (async)
sf @ friendly-iframe-embed.js:260
Bf @ friendly-frame-util.js:69
push.f.Cf.render @ template-renderer.js:64
Zb @ amp-ad-network-base.js:196
(anonymous) @ amp-ad-network-base.js:83
Promise.then (async)
push.f.h.layoutCallback @ amp-ad-network-base.js:83
(anonymous) @ custom-element.js:1409
(anonymous) @ promise.js:75
sb @ promise.js:74
Pi.b.layoutCallback @ custom-element.js:1409
(anonymous) @ resource.js:955
fm @ vsync-impl.js:469
g.Dh @ vsync-impl.js:426
bj.Lc @ pass.js:109
wg @ pass.js:55
(anonymous) @ timer-impl.js:86
setTimeout (async)
g.delay @ timer-impl.js:92
bj.schedule @ pass.js:94
dm @ vsync-impl.js:393
g.Aa @ vsync-impl.js:386
g.run @ vsync-impl.js:188
g.measure @ vsync-impl.js:251
mutate @ mutator-impl.js:257
fm @ vsync-impl.js:469
g.Dh @ vsync-impl.js:426
requestAnimationFrame (async)
dm @ vsync-impl.js:392
g.Aa @ vsync-impl.js:386
g.run @ vsync-impl.js:188
g.runPromise @ vsync-impl.js:203
pj @ mutator-impl.js:215
g.measureMutateElement @ mutator-impl.js:172
g.measureMutateElement @ base-element.js:994
g.mutateElement @ base-element.js:974
(anonymous) @ amp-geo.js:510
Promise.then (async)
da @ amp-geo.js:477
push.f.U.buildCallback @ amp-geo.js:144
(anonymous) @ custom-element.js:516
Promise.then (async)
Pi.b.buildInternal @ custom-element.js:515
g.build @ resource.js:344
Wj @ resources-impl.js:548
Vj @ resources-impl.js:483
g.upgraded @ resources-impl.js:604
Pi.b.zd @ custom-element.js:379
Pi.b.ig @ custom-element.js:1105
Pi.b.Ae @ custom-element.js:1043
Pi.b.upgrade @ custom-element.js:350
Ui @ custom-element-registry.js:103
Si @ custom-element-registry.js:46
om @ extensions-impl.js:367
nm @ extensions-impl.js:355
(anonymous) @ extensions-impl.js:317
g.addDocFactory @ extensions-impl.js:416
g.addElement @ extensions-impl.js:316
(anonymous) @ amp-geo.js:596
f @ amp-geo.js:594
g.registerExtension @ extensions-impl.js:141
(anonymous) @ runtime.js:186
Promise.then (async)
amp-geo @ runtime.js:182
Gi @ chunk.js:200
Ci.rf @ chunk.js:419
(anonymous) @ chunk.js:474
Promise.then (async)
Ji @ chunk.js:473
Ci.Aa @ chunk.js:492
(anonymous) @ chunk.js:445
Promise.then (async)
Ci.rf @ chunk.js:434
(anonymous) @ chunk.js:474
Promise.then (async)
Ji @ chunk.js:473
Ci.Aa @ chunk.js:492
(anonymous) @ chunk.js:445
Promise.then (async)
Ci.rf @ chunk.js:434
(anonymous) @ chunk.js:474
Promise.then (async)
Ji @ chunk.js:473
Ci.Aa @ chunk.js:492
Ci.runForStartup @ chunk.js:378
Di @ chunk.js:69
um @ runtime.js:318
b @ runtime.js:199
(anonymous) @ runtime.js:241
(anonymous) @ timer-impl.js:86
setTimeout (async)
g.delay @ timer-impl.js:92
wm @ runtime.js:510
sm @ runtime.js:223
xm @ runtime.js:347
(anonymous) @ amp.js:70
Gi @ chunk.js:200
Ci.rf @ chunk.js:419
(anonymous) @ chunk.js:474
Promise.then (async)
Ji @ chunk.js:473
Ci.Aa @ chunk.js:492
(anonymous) @ chunk.js:445
Promise.then (async)
Ci.rf @ chunk.js:434
(anonymous) @ chunk.js:474
Promise.then (async)
Ji @ chunk.js:473
Ci.Aa @ chunk.js:492
(anonymous) @ chunk.js:445
Promise.then (async)
Ci.rf @ chunk.js:434
(anonymous) @ chunk.js:474
Promise.then (async)
Ji @ chunk.js:473
Ci.Aa @ chunk.js:492
Ci.runForStartup @ chunk.js:378
Di @ chunk.js:69
(anonymous) @ amp.js:127
(anonymous) @ amp.js:169
log.js:420 Uncaught (in promise) Error: Element "#dianomi-amp-ad" not found: null​​​
    at db.g.assert (log.js:420)
    at jb (log.js:628)
    at db.g.assertElement (log.js:445)
    at analytics-root.js:241

**Comment by dianomi-mjs** [comment]
the element that's giving the error is in the template

```
      {{#track_viewability}}
      <amp-img data-vars-dianomi-device-type="{{ device_type }}" data-vars-dianomi-impression-id="{{ impression_id }}" data-vars-dianomi-smartad-id="{{ id }}" data-vars-dianomi-track-viewability=1 height=1 id=dianomi-amp-ad src="https://www.dianomi.com/cgi-bin/pixeltrack.pl?type=amp&amp;initial_load=true&amp;impression_id={{ impression_id }}&amp;device_type={{ device_type }}&amp;smartad_id={{ id }}" width=1></amp-img>
      {{/track_viewability}}
      {{^track_viewability}}
      <amp-img height=1 id=dianomi-amp-ad src=https://www.dianomi.com/img/1x1.png width=1></amp-img>
      {{/track_viewability}}

```

Earlier versions of AMP were happy with this.

Obviously the not showing of content is more important than this though

**Comment by lannka** [comment]
we found the root cause https://github.com/ampproject/amphtml/pull/32976
thanks @samouri @powerivq for the quick investigation

**Comment by lannka** [comment]
FYI we're rolling back stable shortly. 

/cc @rcebulko

**Comment by samouri** [comment]
FYI For those working on a fix-forward here are some repro steps:

1. Start the dev server: `gulp`
2. Load the demo URL in the proxy: https://www.marketviews.com/dianomi/amp-demo/?amp
