### ISSUE TITLE
🌸 Cherry-pick request for #33317 into #33224 and #33276 (Complete)

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#33325]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #33317 | #33333 |     **NO**     | **YES** | **NO** | #33224                                                              |
| #33317 | #33324 |     **YES**     | **NO** | **NO** | #33276                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

The bug is due to `amp-ad-custom` resolving a template implementation against the main document instead of an embed itself. When templates are not available in the main document the embed is unable to render.

## Why is an LTS cherry-pick needed?

Not in LTS

## List the steps to manually verify the changes in this cherry-pick

See the repro steps described in the #33317.

# Mini-postmortem

## Summary

The problem was due to the `amp-ad-custom` resolving a template via the parent doc. The stable release was rolled back, the issue has been corrected, and rolled forward. The tests have been modified to catch this kind of issue for templates.

## Impact

- For ~22hr the `amp-ad-custom` were affected.
- There are relatively few `amp-ad-custom` impressions overall. And the actual number of failures was smaller because many parent pages have templates installed.

## Action Items

- Besides disruption to the `amp-ad-custom` element itself, the parent page had no disruptions. This is because this kind of failure with templates service is benign to the parent page. It could have been worse for a more sensitive service. The embeds should not be allowed to access parent services at all. We don't have a mechanism to prevent this fully at this time.
- We added more tests for this specific failure. The issue was easy enough to spot with a test manually installing the templates service for the parent page. Ideally we'd disable manual service installation in tests and instead rely on either `realWin({extensions: [...]})` structure or `env.installExtension()` - both of which install services automatically and correctly.
- We could have caught this error way before it came to stable if the system errored when the templates service was not available. Instead, the template request simply hanged on an unresolved promise. We now have a new `ampdoc.declaresExtension()` API that could allow us to throw an error if an extension has not been previously declared, which would show up quickly in nightly/beta logs. This would need to be done carefully to avoid race conditions.

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by kristoferbaxter** [comment]
Approved.

**Comment by jridgewell** [comment]
I don't think we need to cherry pick into https://github.com/ampproject/amphtml/issues/33053 (the old stable). Just fixing https://github.com/ampproject/amphtml/issues/33224 (which was in stable but we just rolled back) and promoting that to stable should be enough.

**Comment by dvoytenko** [comment]
The PR is merged and CP is ready. Once it's done the Stable can be rolled forward.

**Comment by rsimha** [comment]
Assigning back to @dvoytenko for post-mortem and close out.

**Comment by dvoytenko** [comment]
I updated the postmortem. I think the last point I made is a realistic option for us to support with a relatively small effort:

> We could have caught this error way before it came to stable if the system errored when the templates service was not available. Instead, the template request simply hanged on an unresolved promise. We now have a new ampdoc.declaresExtension() API that could allow us to throw an error if an extension has not been previously declared, which would show up quickly in nightly/beta logs. This would need to be done carefully to avoid race conditions.

This would force this and similar cases to show up much faster in error logs and avoid issues on stable.
