### ISSUE TITLE
compensate for scroll position when doing an amp-live-list replace/tombstone

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#3332]
the tombstone and replace operations are batched with the insert operation which required a user interaction wherein we scroll to the top of the component after insertion to display the new items, this makes the sizing of component itself not obvious and is not surprising to the reader as it required a user interaction. when there is a tombstone or replace operation requested but NO insert operation and it resizes the component it can be quite jarring and annoying to the reader if we don't keep scroll position intact.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
