### ISSUE TITLE
Feature request - allow amp-list in amp-sidebar

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#3333]
I'd like to be able to use `amp-list` in `amp-sidebar` elements.

The use case is to create dynamic, user or geo specific,  menu items, show breaking news etc.

**Comment by rudygalfi** [comment]
/to @ericlindley-g and @sriramkrish85 

I know we were conservative on the initial whitelist... Did we consider amp-list?

**Comment by dvoytenko** [comment]
I think it'd be fine, but it will initially be broken due to resize rules and thus these rules will have to be adjusted for the sidebar use-case.

**Comment by ericlindley-g** [comment]
Duping to the [existing bug](https://github.com/ampproject/amphtml/issues/3083)
