### ISSUE TITLE
[amp-story] [publisher identity] Add publisher identity in the system layer

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#33355]
Part of #33353

On the amp-story side, check for the presence of a URL parameter and modify the system layer layout to accommodate the logo + publisher name + create link (and make sure it works correctly with RTL).

@ampproject/wg-stories

**Comment by gmajoulet** [comment]
The identity needs to be part of the initial Story render. Using a URL parameter over a viewer message sounds more appropriate.

**Comment by Enriqe** [comment]
Agreed, had planned to add that in the next PRs. Will update the original comment.

**Comment by Enriqe** [comment]
Closed by #33489
