### ISSUE TITLE
amp-list dynamic height based on item

### ISSUE THREAD

**Issue by sharadvpal** [ampproject/amphtml#33363]
Hello,

I am using an amp-list to get dynamic data but amp-list height isn't updated automatically as per amp-list item list.

I have using below code for this:
<form>
	<input type="text" name="txtsearchreview" placeholder="Search Store Reviews" autocomplete="off" on="input-throttled:AMP.setState({searchmydata:event.value,openpopupreview: 1})" id="txtsearchreview" class="clsseachreview" />
	<button class="clssearchbtn" name="search-button" type="submit" >Search</button>

	<div class="clsamplistbox" [class]="(openpopupreview==1)?'clsamplistbox clsopenpopupreview':'clsamplistbox'">
		<div class="clsmerchantlabel">Merchants</div>
		<amp-list id="searchList" class="clsstorereviewlist"  [src]="'<?php echo site_url() .'/wp-admin/admin-ajax.php?action=get_askme_search_reviews&searchtopbox=';?>'+searchmydata"
			width="auto"
				 height="15"
			  layout="fixed-height">
							<template type="amp-mustache" id="amp-template-custom-review">
					<a on="tap:AMP.navigateTo(url='{{link}}')" class="clssearch_review_link">{{title}}<span class="clsarrowright">&#8594;</span></a>   
					</template>
		</amp-list>
		<a href="<?php site_url();?>" class="clsallresults"><span>Show all results</span> <span class="clsarrowrightall">&#8594;</span></a> 
	</div>
</form> 

Thanks.

**Comment by caroqliu** [comment]
Closing to continue discussion in #33401
