### ISSUE TITLE
amp-fx-flying-carpet library returns 404

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#3336]
## Short description of your issue:
https://cdn.ampproject.org/v0/amp-fx-flying-carpet-0.1.js  returns 404

## How do we reproduce the issue?

Open in a browser https://cdn.ampproject.org/v0/amp-fx-flying-carpet-0.1.js.
I was trying to create an example [here](https://github.com/kul3r4/amp-by-example/blob/amp-flying-carpet/src/20_Components/amp-flying-carpet.html) but the call returns 404

## What browsers are affected?

Chrome

**Comment by kul3r4** [comment]
Hi,
this is happening again. Is there anything we can check?

**Comment by erwinmombay** [comment]
@kul3r4 hello, it looks like this javascript file is currently just in our dev channel and not yet in our prod.
you will need to opt-in to our dev channel here https://cdn.ampproject.org/experiments.html . let me know if you need any more help.

**Comment by kul3r4** [comment]
Hi, I opted in and it works ok. The problem is that sometimes it returns 404.
This also happen if you just try to curl the URL, for example:

curl https://cdn.ampproject.org/v0/amp-flying-carpet-0.1.js

<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  **<p>The requested URL <code>/v0/amp-flying-carpet-0.1.js</code> was not found on this server.**  <ins>That’s all we know.</ins>

**Comment by erwinmombay** [comment]
right, curl'ing it would definitely be currently a 404 since i believe the opt-in is through a cookie. We should have the flying carpet js file in our prod environment by tomorrow if you are able to wait. thursday is our normal release but we weren't able to release last week because of some critical bugs

**Comment by jridgewell** [comment]
Yup, you've got to send the `AMP_CANARY=1` cookie if you want to get the file.

```bash
curl --cookie AMP_CANARY=1 https://cdn.ampproject.org/v0/amp-fx-flying-carpet-0.1.js
```

(also, we renamed it to amp-*fx*-flying-carpet, which still trips me up too)

**Comment by kul3r4** [comment]
Thank you very much for explaining.
