### ISSUE TITLE
Intent to Implement: Nielsen analytics

### ISSUE THREAD

**Issue by uniquelygeneric** [ampproject/amphtml#3337]

**Comment by adelinamart** [comment]
What's the status here? Thanks

**Comment by jridgewell** [comment]
Stalled in #3511.

**Comment by singuyen** [comment]
any progress on this?

**Comment by uniquelygeneric** [comment]
We are rolling out a solution this month and hope to have support soon.

**Comment by rudygalfi** [comment]
We can close this out because #9356 covered this, right?

Also, can you make sure to add content to the linked documentation page (https://engineeringportal.nielsen.com/wiki/DCR_Static_-_Google_AMP)?

**Comment by uniquelygeneric** [comment]
Yes, we should be able to close this out. My apologies, we've changed the URL for the documentation. I've commented the change on the amp docs PR

https://engineeringportal.nielsen.com/wiki/DCR_Static_Google_AMP_Cloud_API

**Comment by rudygalfi** [comment]
Excellent - thanks!
