### ISSUE TITLE
Cannot use multiple amp-script-src tags at the same time.

### ISSUE THREAD

**Issue by nguyendev** [ampproject/amphtml#33402]
## What's the issue?

Cannot use multiple "meta name =" amp-script-src "tags at the same time.

## How do we reproduce the issue?

1. Access at https://sosanhgiakhoahoc.com/bai-viet/khoa-hoc-dinh-duong-online
2. load from the top and enable debug mode

![image](https://user-images.githubusercontent.com/10234503/111867202-1cc1bc80-89a5-11eb-94c4-01f2cbb30bd3.png)
![image](https://user-images.githubusercontent.com/10234503/111867210-2814e800-89a5-11eb-81e6-41d272912969.png)
![image](https://user-images.githubusercontent.com/10234503/111867216-33681380-89a5-11eb-8a97-feeec3c43263.png)
![image](https://user-images.githubusercontent.com/10234503/111867224-44188980-89a5-11eb-8549-590393eadf72.png)

## What browsers are affected?

All browsers

## Which AMP version is affected?

All version

**Comment by rcebulko** [comment]
Howdy Nguyễn,

I've attempted to reproduce this issue in Chrome with DevTools open, but I've been unable to replicate the error. I see three `amp-script` tags, all properly populated. I did notice from your screenshots that some of the stacktraces and refererrer URLs indicate you're testing this page on `localhost`, and the browser seems to have a handful of Chrome extensions running.

If you access the browser in [Incognito Mode](https://support.google.com/chrome/answer/95464) (which will exclude your extensions) and on the `https://sosanhgiakhoahoc.com/` domain rather than `localhost`, are you still able to reproduce this issue? Knowing this will help us identify what might be causing the issue

**Comment by nguyendev** [comment]
Hi @rcebulko.

This is capture from `https://sosanhgiakhoahoc.com/bai-viet/khoa-hoc-dinh-duong-online` in Incognito Mode.
You can see different with two picture.
![image](https://user-images.githubusercontent.com/10234503/113114645-bf93f980-9235-11eb-98b6-861406004fea.png)
![image](https://user-images.githubusercontent.com/10234503/113114728-d76b7d80-9235-11eb-9c37-d51bb3216c71.png)

I think, may be amp-script can not support multiple in the same page

**Comment by rcebulko** [comment]
Howdy,

Thanks for the clarification! I was able to reproduce and dig in a bit. What's happening here is that the AMP logic ([lives here](https://github.com/ampproject/amphtml/blob/master/src/service/ampdoc-impl.js#L387)) which fetches `<meta>` tag values only keeps a single value per `name`:
https://github.com/ampproject/amphtml/blob/e36bcd1cd7a3591b8d057d90312f1e84ef710644/src/service/ampdoc-impl.js#L387-L390

. When `amp-script` tries to look up the "known" script hashes, it's only getting the first one. The script hashes in the other two `<meta>` tags are never seen!

It appears to me that the `amp-script` code is expecting/allowing space-delimited script hashes in a single `<meta name='amp-script-src'>` tag:
https://github.com/ampproject/amphtml/blob/e36bcd1cd7a3591b8d057d90312f1e84ef710644/extensions/amp-script/0.1/amp-script.js#L550-L557

Including multiple script hashes in a single tag should work. As far as I can tell, this is not documented on AMP.dev or anywhere else immediately discoverable. 

I see two paths forward:
1. Document this requirement on AMP.dev for use cases requiring multiple `<amp-script>` tags
2. Modify `amp-script.js` to potentially query for multiple meta tags

/cc @dvoytenko @samouri for opinions as the last two committers to `amp-script.js`

**Comment by nguyendev** [comment]
Hi @rcebulko, @dvoytenko  @samouri,

Thank you for your help.
I hope you will have it done soon.
This will be very useful for use on more complex websites
when you finish it, can you tell me?

**Comment by kristoferbaxter** [comment]
We should move forward with documenting the space delimited nature of it if possible. This is similar to other DOMTokenList approaches like ClassList.

**Comment by rcebulko** [comment]
> Thank you for your help.
> I hope you will have it done soon.
> This will be very useful for use on more complex websites
> when you finish it, can you tell me?

Using space-delimited list of hashes as described above should provide a solution for your needs. In the case of `https://sosanhgiakhoahoc.com/bai-viet/khoa-hoc-dinh-duong-online`, I believe it would look something like:

```html
<meta name="amp-script-src" content="sha384-iipRZNU0FVvjLKrSje6XwLGm6FRE6Kb9vv9J2Rpt2nX8zubhznLsBwdBbqLx1DOa sha384-L9oFf1PvVg9VHBWVRLC-C8u8qDMvoN1brre4URWT3PESKGI7aj30cFsYYJ6LS-_9 sha384-5PKv1H5x4Np5xHG65ifBCjpcGOlI2WGH0tMExOGtU70eScXFXvTOBrr3Uc1LmYfo">
```

> We should move forward with documenting the space delimited nature of it if possible. This is similar to other DOMTokenList approaches like ClassList.

I'll see if I can find docs for similar features and follow up with a first-pass at updating them, then pull in Jake and maybe either Naina or Crystal

**Comment by samouri** [comment]
> We should move forward with documenting the space delimited nature of it if possible. This is similar to other DOMTokenList approaches like ClassList.

I agree with this. Thank you @rcebulko for taking it on!

**Comment by rcebulko** [comment]
@nguyendev As mentioned above, space-delimited script-hashes should solve your issue and are already supported. #33902 includes documentation updates and support for newline-delimited hashes as well; that change should roll out to production in about two weeks time.

**Comment by samouri** [comment]
Closing as the fix has been merged (and is on its way to production)

**Comment by nguyendev** [comment]
This is a good solution. Thank you
