### ISSUE TITLE
🌸 Cherry-pick request for #33381 into #33276 (Complete)

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#33409]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| - | #33381 |     **YES**     | **NO** | **NO** | #33276                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?
userAsserts are being removed during compilation, leading to uncaught errors
Attempted to get this in all day Friday but repeated rebases and reruns were no match for a motivated CI bug :)

## List the steps to manually verify the changes in this cherry-pick

<_TEST_STEPS_>

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

<_1-2 sentences summarizing the problem and root causes._>

## Impact

- <_Which users were affected? Roughly how many?_>
- <_How were users affected? E.g. partial or complete loss of functionality?_>

## Action Items

- #<_ISSUE_NUMBER_>: <_Add unit/integration/end-to-end test_>
- #<_ISSUE_NUMBER_>: <_Add monitoring for edge case via error logging_>
- #<_ISSUE_NUMBER_>: <_Refactor an easily misused API_>

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by dvoytenko** [comment]
Has this been done?

**Comment by rsimha** [comment]
> Has this been done?

No, because I was initially waiting on an approval for this. Can do tomorrow morning if you approve.

**Comment by dvoytenko** [comment]
I see. Wasn't sure the CP was ready. It had TBD in the release info. Approved. /cc @rcebulko, but AFAIU this is a critical fix for Beta.

**Comment by rcebulko** [comment]
> I see. Wasn't sure the CP was ready. It had TBD in the release info. Approved. /cc @rcebulko, but AFAIU this is a critical fix for Beta.

This is correct. I thought I remembered seeing approval on it, but I must have been mixing it up with another of the CPs from last week.

**Comment by rsimha** [comment]
This was CP'd to beta, which has since been promoted to stable. https://github.com/ampproject/amphtml/commits/2103122145004

Back to @rcebulko in case you have anything to add to the post-mortem section.
