### ISSUE TITLE
border-top-width on body element causes incorrect display of lightbox in iOS Safari in Viewer

### ISSUE THREAD

**Issue by ericfs** [ampproject/amphtml#3340]
Example page with issue:
https://www.google.com/amp/mashable-amphtml.googleusercontent.com/amphtml/pages/CAIiEAkT4PrPGjd0a1zZrN_xpVQqIggEKhoIACIQd3d3Lm1hc2hhYmxlLmNvbSoECAowCDCBmB4#

Tap the image to open the lightbox

## What browsers are affected?
iOS Safari

## Which AMP version is affected?
1463506087793

Is this a new issue? Or was it always broken? Paste your AMP version. You can find it in the browser dev tools.
I believe this is regression, but I'm not sure and I don't know when it first happened.

![amp_bug_2](https://cloud.githubusercontent.com/assets/851850/15584423/8fcff9d0-2348-11e6-9bad-5bea5a01d107.PNG)

**Comment by erwinmombay** [comment]
/to @dvoytenko , feel free to reassign
