### ISSUE TITLE
Poll and Quiz : Still text-align issue for the text options 

### ISSUE THREAD

**Issue by lougea** [ampproject/amphtml#33428]
What's the issue?
Text-align in poll and quiz options

Each text option is aligned when the text is too long

![Screenshot_2021-03-23 Issue - text option align-center Louise](https://user-images.githubusercontent.com/45533830/112126378-ae5b4500-8bc4-11eb-9503-4cac52084754.jpg)

Same issue : https://github.com/ampproject/amphtml/issues/33206

How do we reproduce the issue?
[https://testlouise.tappable.link/issue-text-option-align-center?story](url)

What browsers are affected?
For Chrome, edge, opera : quiz and poll have the issue
For mozilla , safari : poll had the issue

**Comment by newmuis** [comment]
@lougea can you check again?  I believe the code to fix #33206 had just not rolled out into the production build when you filed this issue, but it no longer seems to appear for me.

**Comment by lougea** [comment]
it's working like expected. Thanks !
