### ISSUE TITLE
Intent-to-Implement: Clicky Web Analytics

### ISSUE THREAD

**Issue by avclicky** [ampproject/amphtml#3345]
Hello,

Proposal to add simple support for Clicky Web Analytics. The development has occurred already, on a separate branch in a separate fork [0], and is entirely contained within one commit [1].

We are working on getting the CLA processed.

avclicky

[0] https://github.com/avclicky/amphtml/tree/clicky-support
[1] 11c5f2526431b940ab377c9e39c4817e6bcbbb22

**Comment by dvoytenko** [comment]
Sounds good

/cc @rudygalfi @avimehta

**Comment by avclicky** [comment]
The CLA appears to have been processed and PR #3346 has passed the CI mechanism. Might we have any work left to do on our end?
