### ISSUE TITLE
Validator: Allowing Forms and Inputs

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#3348]
AMP will start supporting forms - see #3343, filing this to get discussion going and to start on the validator part in parallel.

* Allow usage of `form`, `input`, `textarea`, `select`, `option` tags in AMP Docs.
* Must include amp-form extension script if document uses form/input/select/textarea tags.
* Must use inputs tags inside form tag.
* Form must have at least one `<input type=submit>`
* Form must have action=”absolute non-cdn https url”
* Form must have target=”_top|_blank”
* `<input type=”file|password|image|button”>` are invalid
  * This might be revised later on.
* Other than normal form attributes, allowed attributes include:
  * `action-xhr` - Optional - to enable a submission flow through XHR. Also has same validation as `action` attr (absolute, non-cdn link and https) except not required.

cc/ @powdercloud @Gregable @rudygalfi

**Comment by dvoytenko** [comment]
This would be good to discuss if we can do this behind the experiment in validator.

**Comment by mkhatib** [comment]
@powdercloud when can we get this into the validator?

**Comment by mkhatib** [comment]
@powdercloud any update on when can we get the validation stuff in for forms?

**Comment by Gregable** [comment]
How important is the "at least one `<input type=submit>` child" constraint. We noticed that forms could be submitted even without a submit button, such as a text input field and pressing `<enter>`.

**Comment by mkhatib** [comment]
Not very important. This was mainly trying to make sure publishers include a submit button (specially on mobile). We can do with runtime error or warning for now.

**Comment by honeybadgerdontcare** [comment]
Are all other* [input attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) optional?

What about [textarea](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea), [select](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) and [option](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option)?

*everything except type=”file|password|image|button”

**Comment by honeybadgerdontcare** [comment]
I noticed in the [amp-form documentation](https://github.com/ampproject/amphtml/blob/master/extensions/amp-form/amp-form.md) that the example includes `fieldset` and `label`. We currently do not allow these. Are we intending to allow them here only as children of `form` and only if `amp-form` extension is included?

**Comment by honeybadgerdontcare** [comment]
Added `fieldset` and `label` as required children of `form` and only if `amp-form` extension is included.
Added all attributes for `input` except type="file|password|image|button" and those related to type="image" such as "src" and "usemap". Added all attributes for `textarea`, `select` and `option`. Let me know if we should exclude any others.

**Comment by Gregable** [comment]
Resolved, but still waiting to deploy to cdn.ampproject.org.

**Comment by mkhatib** [comment]
Thanks so much! 

> Added fieldset and label as required children of form

This doesn't mean that publishers have to have label and fieldset inside form? It only means that if they use them in their AMP Doc they must be a descendant of form, right?

**Comment by honeybadgerdontcare** [comment]
Yes, that's correct. If `label` or `fieldset` appear in the doc, then they must be a descendant of `form` and also include the amp-form extension script.

**Comment by Gregable** [comment]
This has now been deployed everywhere.

**Comment by niutech** [comment]
@mkhatib Why are `<input type="password">` and `<input type="button">` not allowed in AMP? How can I make a login form or add any buttons except for submit/reset? Please reconsider allowing them.
