### ISSUE TITLE
(lint) comma dangle lint settings (object literals and array literals)

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#335]
```js
var foo = {
    bar: "baz",
    qux: "quux",
};
```

Yea or Nay?

@cramforce @dvoytenko

i think i've seen @cramforce (correct me if i'm wrong) do it, so just want to come to a consensus. 

details:
http://eslint.org/docs/rules/comma-dangle

**Comment by rudygalfi** [comment]
I think we've decided we're comma danglers around here. :) Closing this.

**Comment by cramforce** [comment]
@rudygalfi Great PM work :shipit:

**Comment by jridgewell** [comment]
We still need the ESLint rule...

**Comment by erwinmombay** [comment]
haha honestly i held off on making this change because of how huge the delta on the code base was going to be! lol

**Comment by jridgewell** [comment]
PR: https://github.com/ampproject/amphtml/pull/1738. Adding a `fixer` to the ESLint plugin made this surprisingly easy.

**Comment by ericlindley-g** [comment]
FYI, @jridgewell , I bumped this to Feb 13

**Comment by jridgewell** [comment]
Closed by #1738.
