### ISSUE TITLE
Syntax guide for using fonts already on the device

### ISSUE THREAD

**Issue by JoeArizona** [ampproject/amphtml#3350]
Enhancement request:

It would be extremely helpful to have a guide specifying the correct syntax for using locally installed fonts. With AMP there's still a presumption that we're making the user download fonts, which I'd like to avoid with some caveats.

What we need – and what I haven't found on Android dev docs – is an accurate list of exactly which fonts are installed on Android devices. It seems to be based on Android version, but the details have never been provided. By details, I mean things like styles and weights of Droid Sans, Droid Serif, Roboto, etc. that we can choose from by Android version. iOS has a ton of installed fonts, and there are lots of resources on how to use them, but Android's font situation is hazy. (Relatedly, is Roboto Mono installed on Android? I have no idea. It's a great font and we'd love to use it for code boxes.)

By "correct syntax", I just mean the exact terms to use for the font families and so forth. This sometimes becomes a problem when a system font called, say, Fantastic Serif is actually named something not quite the same, like Fantastic-Serif-Adb, for application purposes.

A cross-platform AMP local/system fonts guide would be awesome, and promoting the use of local fonts obviously advances AMP's goals.

**Comment by cramforce** [comment]
I think this is a good suggestion, but not really AMP specific, is it? That'd be a great resource for the web.

**Comment by sriramkrish85** [comment]
Definitely a nice to have - here is the list i was able to find for IOS 

http://iosfonts.com/

Android seems to require some testing (no such list is available for android.)

@cramforce would this be be something to work on during a fixit?

**Comment by cramforce** [comment]
@sriramkrish85 Sure, or during commercial breaks of NBA finals :)

**Comment by sriramkrish85** [comment]
I am starting to collect this list - 
Posting URLs that would help with it. 
https://www.w3.org/Style/Examples/007/fonts.en.html
http://www.upsdell.com/BrowserNews/res_fontsamp.htm
http://web.mit.edu/jmorzins/www/fonts.html
http://iosfonts.com/

I will build a table with these fonts in mind and share them soon.

**Comment by sriramkrish85** [comment]
@cramforce @JoeArizona @dvoytenko  - i created this JS bin that would tell what fonts are available on a device on a browser (when this page is loaded). 
http://jsbin.com/koceci

I will use this and make a useful table and publish it soon.

**Comment by JoeArizona** [comment]
@sriramkrish85 Thank you! Is it using an OS heuristic to generate the list? It doesn't seem to be listing all the fonts actually installed on my machine (I have no idea how to make JS do that). For example, I have Open Sans, Roboto, Inconsolata, Source Code Pro, and Linux Libertine installed, among others, but they aren't listed. (Chrome 51 64-bit, Windows 10).

**Comment by sriramkrish85** [comment]
@JoeArizona i hand curated the list from the sources i mentioned above, it would only show fonts that are available by default on your device (may be not all of them - but i think the list is pretty comprehensive). You can find the list here - https://gist.github.com/anonymous/019afa8f2a3a9aae458760e435ef63e1#file-index-html-L2297

**Comment by abeck000** [comment]
@camelburrito - I'm confused about why Apple's ios font San Francisco isn't on this list...

**Comment by camelburrito** [comment]
@abeck000 - the list we check against is a hand curated list - meaning - you will have to add the font to the list before checking this - 
Here is the list that is being used in my JS bin
https://gist.github.com/anonymous/019afa8f2a3a9aae458760e435ef63e1#file-index-html-L2297


If you want to add more to this , you can clone the JS bin and add them yourself (or send me the list of fonts that needs to be added ill add it to the JS bin)
