### ISSUE TITLE
Automatically restart a Web Story

### ISSUE THREAD

**Issue by LuckynaSan** [ampproject/amphtml#33527]
## Describe the new feature or change to an existing feature you'd like to see
A user of the Web Stories for WordPress plugin requested a way to make a Web Story loop. User can use the button to go back to start, but there’s no functionality to automatically do that.  Submitting this as a feature request to have amp story player consider adding support for looping a story.

## Describe alternatives you've considered
N/A

## Additional context
Related topic in the Web Stories WordPress support forum:
https://wordpress.org/support/topic/webstory-loop/
https://wordpress.org/support/topic/shortcode-in-web-stories/

**Comment by MeiPR** [comment]
Looking for a way to create a Web Story loop, I came accross this issue. We also would really love this feature...!

**Comment by ychsieh** [comment]
looks like the duplicate of #34414
