### ISSUE TITLE
amp-consent: trim spaces between purpose types

### ISSUE THREAD

**Issue by morsssss** [ampproject/amphtml#33528]
The new `data-block-on-consent-purposes` attribute in `amp-consent` accepts multiple purposes. As in, this would specify that a component requires purposes called `purpose-marketing` and `purpose-analytics`:

```html
<amp-xxx data-block-on-consent-purposes="purpose-marketing, purpose-analytics">
```

However, spaces break this. So, the example above wouldn't work because there's a space after the comma.

My proposal is to ignore such spaces. I won't state an opinion about trimming out all spaces, permitting, for example,

```html
<amp-xxx data-block-on-consent-purposes="   purpose-marketing, purpose-analytics ">
```

/cc @micajuine-ho 

Also see https://github.com/ampproject/amphtml/issues/31607, https://github.com/ampproject/amphtml/issues/26735

**Comment by kristoferbaxter** [comment]
Is there a reason to use a comma separated list here instead of the more common (and DOM specced) DOMTokenList?

https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList

**Comment by micajuine-ho** [comment]
We wanted to keep it similar to the `<meta name="amp-consent-blocking">` feature that developers are familiar with in terms of which components/purposes are blocked by consent. 

I think it should not be a problem to accept either a DOMTokenList or a comma separated list.
