### ISSUE TITLE
🌸 Cherry-pick request for #33546 into #33542 & #33461 (Completed)

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#33562]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #33546 | #33564 |     **YES**     | **YES** | **NO** | #33542 & #33461                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#Cherry-picks)?

The AMP-version `amp-story-player` is not being displayed in these versions.

## List the steps to manually verify the changes in this cherry-pick

1.  `git revert f2b85d9aa7e57188a16d7807d2c6f5969b2f3b3b`
2. Load `http://localhost:8000/examples/amp-story/player-amp.html`
3. Story displays correctly.

# Mini-postmortem

> **TODO:** This postmortem will be written after the cherry-pick deployment and before this issue is closed. Delete this TODO when the postmortem is ready.

## Summary

<_1-2 sentences summarizing the problem and root causes._>

## Impact

- <_Which users were affected? Roughly how many?_>
- <_How were users affected? E.g. partial or complete loss of functionality?_>

## Action Items

- #33576: Introduce visual diff tests so that issues like these are caught in time.
- Adding manual QA test for AMP version.

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by kristoferbaxter** [comment]
Approved.

**Comment by danielrozenberg** [comment]
This cherry-pick has been performed and released. Reassigning to @Enriqe for post-mortem

**Comment by Enriqe** [comment]
Visual diff and manual QA tests added 

/cc @newmuis
