### ISSUE TITLE
Re-attached elements are being built again

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#3356]
Follow up to #3354 

We sometimes re-parent children to wrap them in a container (e.g. Carousel, Lightbox). But those children may have already been built. But since we fire another `attachedCallback`, we'll add them to the unbuilts again, and try to build again. It's cool to add them to the list again, but we should make sure they're really unbuilt before trying to #build them again.

I believe we're already doing this in `ElementProto.build` method.

```javascript
  ElementProto.build = function() {
   // ...
    if (this.isBuilt()) {
      return;
    }
   // ...
  }
```

@jridgewell should this be enough? or were you suggesting avoid adding them to the pool all together?

**Comment by mkhatib** [comment]
It doesn't seem we reset `this.built_` in the detached callback so I think this should do it. Worth looking more into it.

**Comment by jridgewell** [comment]
Oh why do we have `Resource` and `ElementProto`. :sigh:

So looks like there's an issue further up in `Resources#add`. We shouldn't be pushing the element into the `resources_` array if it already has an associated `Resource` in the array.

**Comment by dvoytenko** [comment]
We should not be resetting `this.built_` ever (though there might be exceptions). The element should be built the first time it's added to DOM and stay built until it's destroyed.

However, we may want to reset `element[RESOURCE_PROP_]` when resource is removed in `Resources.remove`. That would be my preference. It should work correctly right away, I believe - the Resource instance already initializes itself into "built" state when `ElementProto.isBuilt()` is "true".

**Comment by dvoytenko** [comment]
I filed #3366 for `element[RESOURCE_PROP_]`

**Comment by mkhatib** [comment]
> So looks like there's an issue further up in Resources#add. We shouldn't be pushing the element into the resources_ array if it already has an associated Resource in the array.

@jridgewell for re-attached elements the detach-flow would remove it from `resources_` and then the attach would re-add it to `resources_`.

**Comment by jridgewell** [comment]
Whoot, sweet. In that case, we can just optimize `Resource#build` to return early if it's already built.

**Comment by mkhatib** [comment]
Like a check for the state?
```javascript
if (this.state_ != ResourceState_.NOT_BUILT) {
  return;
}
```

I guess that would avoid another call stack to the `element.build`, don't know how much of optimization that would do but I am cool with doing this.

**Comment by jridgewell** [comment]
We do essentially that all over `Resource`.

**Comment by jridgewell** [comment]
Fixed by https://github.com/ampproject/amphtml/pull/3355.
