### ISSUE TITLE
I2I: Extend amp-ads to support waiting for audience targeting data from an <amp-script>

### ISSUE THREAD

**Issue by joshfg** [ampproject/amphtml#33581]
## Summary

We have a use case for passing targeting key-values from an `<amp-script>` to `<amp-ad>` components on the page.

This I2I is a proposal to extend the `<amp-ad>` component to support retrieving targeting key-values from an `<amp-script>`, in a similar fashion to how AMP RTC allows retrieving targeting key-values from a remote API.

## Design document

![High-level design proposal](https://user-images.githubusercontent.com/5942539/113286060-96ca3d80-92e3-11eb-81ed-4c4feb5c6939.png)

TODO — Hoping to get some initial ideas as we start to flesh out a design proposal.

## Motivation

To support a new use case for AMP — processing and decisioning on analytics data on device, without this analytics data necessarily needing to be sent to the cloud.

## Additional context

Permutive is a Data Management Platform (DMP) for publishers. We have a strong focus on privacy and first-party data: enabling publishers to use their data to power advertising and personalization in real-time, across every device, browser and environment, while respecting user privacy.

One of the essential capabilities we provide publishers is the ability to dynamically target their ads, based on a user's behaviour. We want to provide publishers with this capability in AMP, to the same standard as we do on standard Web pages. 

This I2I describes an AMP change we've identified as a requirement to achieve this, following [our original I2I](https://github.com/ampproject/amphtml/issues/28095) to implement a component for Permutive in AMP. After a lengthy discussion with the AMP team, we have decided to use `<amp-script>` for our use case, rather than a custom component. The ability to pass targeting key-values from `<amp-script>` to `<amp-ad>` is required to support our use case.

/cc @ampproject/wg-approvers @samouri

**Comment by samouri** [comment]
cc @ampproject/wg-monetization

**Comment by samouri** [comment]
After discussions with @joshfg and @ampproject/wg-monetization, we've discussed scoping this down from all `amp-ad` support, to just RTC (fast fetch ads).
