### ISSUE TITLE
Test/verify that devAsserts are DCE'd properly

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#33609]
Several bugs have been introduced while tweaking assertion code where dev assertions were not getting DCE'd (when they should be) or where user assertions were getting DCE'd (when they should not be). We want to validate this. Because the result depends on logic in AMP code itself, a babel unit test by itself will not suffice.

## Plan

Within `pureDevAssert`, include an impossible-to-reach branch that would not be DCE'd:
```javascript
export function pureDevAssert(
  shouldBeTruthy,
  opt_message,
  opt_1,
  opt_2,
  opt_3,
  opt_4,
  opt_5,
  opt_6,
  opt_7,
  opt_8,
  opt_9
) {
  if (isMinifiedMode()) {
    return shouldBeTruthy;
  }

  if (window.__thisVariableDoesNotExist) {
    // This will never execute regardless, but will be included on unminified
    // builds. It will be DCE'd away from minified builds, and so can be used to
    // validate that Babel is properly removing dev assertions in minified
    // builds.
    console.log('devAssert sentinel string for testing');
  }

  return assertion(
    Error,
    shouldBeTruthy,
    opt_message,
    opt_1,
    opt_2,
    opt_3,
    opt_4,
    opt_5,
    opt_6,
    opt_7,
    opt_8,
    opt_9
  );
}
```
This would never run, even when included. A dedicated gulp/amp task could then grep:
- `dist/amp.js`: it should be present
- `dist/v0.js`: it should not be present

We could take a similar approach for the `'Assertion failed'` string to provide some confidence that user assertions are not being removed (if they were, all the assertion code including the default assertion error message would be DCE'd as well). WDYT?

/cc @ampproject/wg-performance

**Comment by samouri** [comment]
Plan LGTM
