### ISSUE TITLE
amp-analytics does not load sometimes

### ISSUE THREAD

**Issue by pdufour** [ampproject/amphtml#3364]
## Short description of your issue:

I will provide more information as I can get it, but I've noticed times where the analytics code will not fire at all. There aren't any network issues like the scripts not loading or anything, so I think there must be some sort of race condition within the AMP code. Maybe something with how the "visible" trigger works?

## How do we reproduce the issue?

1. Refresh on an amp-enabled page with amp-analytics installed with GA configuration
2. Look in network requests
3. Every once in a while the GA pixel will not get sent.

## What browsers are affected?

Chrome is what I've tested on

## Which AMP version is affected?

Latest

**Comment by pdufour** [comment]
I have a tab open now where GA & the other pixels never loaded. Is there any sort of debug information I can provide?

**Comment by erwinmombay** [comment]
@cramforce who should this be triaged to?

**Comment by cramforce** [comment]
@pdufour thanks for the report!
@avimehta could you try to reproduce?

**Comment by avimehta** [comment]
@pdufour I have not been able to reproduce it so far. Does it happen on slow/flaky internet connection? Is there a test page you have been looking at? curious about the chrome version. also, just to double check, you don't see anything in realtime dashboard?

**Comment by pdufour** [comment]
Pretty stable internet connection. Have an email I can send the test page too? Not public-facing atm.

Chrome Version 51.0.2704.63 (64-bit), Mac.

Also may have been able to track down the issue. I'm pretty sure this is not how it's supposed to behave.

1. Open page with AMP enabled
1. Scroll down the page fast
1. See that now GA pixel has loaded
1. Scroll back to the top of the page, GA pixel loads.

![google_analytics](https://cloud.githubusercontent.com/assets/1239145/15631399/ceb606c2-251d-11e6-83ed-9905b154c969.gif)

**Comment by avimehta** [comment]
Hi @pdufour, please send the example to <github account>@google.com. I tried to copy the analytics example to https://jsfiddle.net/cL6zr6hy/2/ (see full page version at http://fiddle.jshell.net/cL6zr6hy/1/show/light/). I was not able to reproduce it there or locally.

**Comment by avimehta** [comment]
@cramforce I am not completely sure why this isn't working but I think I can repro the issue. Sometimes, when I reload the page, the analytics hit is not sent. Executing `AMP.resources.resources_.forEach(x => {console.log(x.debugid + "   " + x.state_)})` in console gives:

```
amp-img#1   4
amp-img#2   2
amp-img#3   2
amp-img#4   2
amp-img#5   2
amp-img#6   2
amp-img#7   2
amp-img#8   2
amp-img#9   2
amp-img#10   2
amp-img#11   4
amp-img#12   4
amp-analytics#13   2
amp-analytics#14   2
```

When I scroll all the way to the top, the element lays out. And obviously the output for the same command changes to

```
amp-img#1   4
amp-img#2   4
amp-img#3   4
amp-img#4   4
amp-img#5   4
amp-img#6   4
amp-img#7   4
amp-img#8   4
amp-img#9   4
amp-img#10   4
amp-img#11   4
amp-img#12   4
amp-analytics#13   4
amp-analytics#14   4
```

Given this, it looks like resources service is somehow 'forgetting' to layout amp-analytics. Any idea what might be going on?

(aside: Will https://github.com/ampproject/amphtml/issues/1082 fix this? If it will, I can prioritize that.)

**Comment by cramforce** [comment]
Ha. So, the scroll down fast part is important. Very interesting.

I have a better repro URL here
http://output.jsbin.com/polorufage/quiet

**Comment by cramforce** [comment]
CC @dvoytenko 

I think this is a bug where we, for fixed positioned elements, think we can calculate their intersection with the viewport based on the originally measured layout box offset by `scrollTop`. Which is wrong.

**Comment by cramforce** [comment]
Yep, so if you trigger the bug and then resize the window (causing full re-measure) the layout is successfully executed.

**Comment by avimehta** [comment]
Scrolling to the top also triggers the relay out I think.

**Comment by cramforce** [comment]
@avimehta AMP just treats the element as being at the top, so slightly different case. We have to fix this for many reasons :)

**Comment by cramforce** [comment]
The correct fix here (I think) is to change `overlaps` in `Resource` to check `isFixed` (which doesn't exist yet), if that is true make the comparison with a viewport rect rooted at `0, 0`.

**Comment by cramforce** [comment]
I leave it to @dvoytenko to know what the best way to implement `isFixed`. `FixedLayer` might be able to provide the answer. The naive way would be to call `getComputedStyle` on the element and all parent elements.

**Comment by dvoytenko** [comment]
I'll take care of this.
