### ISSUE TITLE
Do not build a cloned node twice

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#3365]
To repro create a document with e.g. an `amp-carousel` element. Wait for it to build (`buildCallback` is called) and run the following code on this element:

```
element.parentElement.appendChild(element.cloneNode(true));
```

You will see that the cloned node will be built again and thus will have duplicate built artifacts such as container, slides, arrows, etc.

We can solve it by setting state on the built node that will survive cloning: a class or an attribute. Then this class/attribute can be checked by `ElementProto.createdCallback` to immediately initialize the element in the built state.

**Comment by jridgewell** [comment]
This is a bit more in-depth because we'll need to get make a `cells_` array and the `container_`, etc. Might be better to make a `Element#clone` and a `clone` helper to do all of this for us and forbid using `element.cloneNode` directly.

**Comment by dvoytenko** [comment]
@jridgewell good point. Definitely needs to be thought through.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please verify first whether the feature proposal is still relevant.

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
