### ISSUE TITLE
Reset `element[RESOURCE_PROP_]` when the resource is removed from resource manager

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#3366]
`Resources.remove(element)` should reset `element[RESOURCE_PROP_]` since we can consider that resource no longer exists.

**Comment by jridgewell** [comment]
Per https://github.com/ampproject/amphtml/issues/3356#issuecomment-222217540, I'm not sure this is the case when moving or cloning an element.

Yes we can solve the cloning issue with something like https://github.com/ampproject/amphtml/issues/3365#issuecomment-222219602 (we should definitely do this), but that won't help for moving into a wrapper. I think instead leaving the resource attached to the element and reusing it if the element is reattached is the better approach.
