### ISSUE TITLE
Local server is no longer watching amp-story-player.js for changes

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#33664]
The auto compile in the local server stopped working for me at some point saving a file under `/src/*`. 

e.g. if I save `src/amp-story-player/amp-story-player-impl.js`, I will only get this on the local server:
```
[15:03:09] Compiled amp.js (187 ms)
[15:03:09] Applied AMP config (prod, localDev) to amp.js
```

But it won't recompile the `amp-story-player-impl.js` file. I have to restart the local server for it to pick up the new changes

@rsimha pointed me to https://github.com/ampproject/amphtml/pull/32835, which watches all files under `src/` as if they were part of `amp.js` and nothing else, so it misses to watch `src/amp-story-player/*` for changes.

**Comment by rsimha** [comment]
@Enriqe Did you actually load a document that fetches the story viewer? If you didn't, that's likely the problem.

The reason you're seeing `amp.js` being built is because it's the only file that is automatically pre-built. Once you trigger the lazy builder for story viewer, you'll see it being built as well. 

Meanwhile, let's keep this issue open until we refine the watcher mechanism for `amp.js`.

**Comment by Enriqe** [comment]
Yep, I did try e.g. with this file: 

https://github.com/ampproject/amphtml/blob/bb29e93a6d1836b10f55cdeb59f638015c7bfc6a/examples/amp-story/player-local-stories.html#L1-L6

Note that we import the compiled player code from `dist/`. This is because of a different issue (#30817), where the local server won't rewrite the CDN url to the local build.

**Comment by rsimha** [comment]
Okay, thanks for confirming. I tried reproing this and see that while `amp-story-player.js` is indeed being lazily-built on demand, it is not being watched correctly.

![image](https://user-images.githubusercontent.com/26553114/113900486-dc7f7e00-979b-11eb-83dd-6d2e86b3d70f.png)

My suspicion is that #32879 broke watch mode for a subset of our JS targets that don't live under `extensions/`. Will let @samouri take an initial look when time permits, happy to help if more hands are needed on deck.

**Comment by samouri** [comment]
Can take a peek later this week, but I'm a bit swamped with other work right now and don't have the spare cycles to really dive in. If it can wait a few weeks I can likely take this on

**Comment by Enriqe** [comment]
Given that this is a regression and that it slows down development for the `amp-story-player` I'd prefer if it gets prioritized and not left stale for weeks @samouri

**Comment by gmajoulet** [comment]
That makes our eng cycles extremely slow and painful and significantly hurt velocity. Do we have a way to work around this before landing a longer term fix? If not, we should consider making this a P0.

**Comment by alanorozco** [comment]
@gmajoulet I don't know if you've considered this, but you could potentially run an inside of `amp` alongside a separate watcher like `fswatch` that triggers `amp build --extensions=amp-story-player`

**Comment by alanorozco** [comment]
(Apologies for accidentally closing this earlier.)

@gmajoulet @Enriqe It's not ideal, but have you considered running `amp` (for every other file/serve) and a separate instance of a watcher like `fswatch` to trigger `amp build --extensions=amp-story-player`? It's a bit slower than it could be, but should likely work?

**Comment by samouri** [comment]
Thank you for being patient! Almost ready with a fix over at https://github.com/ampproject/amphtml/pull/33840, will hopefully have it done before EOD

**Comment by Enriqe** [comment]
Thank you @samouri, @rsimha, and @alanorozco for the help on this, it's a big improvement for us :)
