### ISSUE TITLE
amp-story-page-attachment weird behaviour on iOS

### ISSUE THREAD

**Issue by nterol** [ampproject/amphtml#33675]
## What's the issue?

This only happens on safari ios. When loading multiple stories with multiple pages each in the `amp-story-player` each with an `amp-story-page-attachment`, opening/closing of the attachments eventually becomes erratic. 

https://user-images.githubusercontent.com/24438131/113898690-66473f80-97cc-11eb-858b-8a0362b6f77e.mov

When the bug occurs on the last story of the player, it triggers a history.goBack in the browser. 

Error trace points to  the file `history-impl.js` line 289. 

<img width="1000" alt="Screenshot 2021-04-07 at 18 04 46" src="https://user-images.githubusercontent.com/24438131/113898053-cc7f9280-97cb-11eb-991d-45117860a077.png">

## How do we reproduce the issue?

Set up an amp-story-player with at least two stories each with two pages with an attachment. 
Open the player on Safari iOS (any version), scroll through the stories and swipe up/

down on the attachments. 

## What browsers are affected?

Safari iOS

## Which AMP version is affected?

Current version.

**Comment by FranceJ** [comment]
I'm experiencing this issue as well, but with a different context. I am embedding an amp story (for an editor preview) in another page via an iframe on a react SPA. Opening the attachment and clicking off the attachment works as expected until you have to tear down the component and create a new iframe with new data. As soon as you have created a new iframe opening the attachment will work as expected, but clicking off to close will at first have no affect and then will either refresh the page or navigate back to the last history value for the global page context.
