### ISSUE TITLE
Add @raxsha to @ampproject/reviewers-amphtml 

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#33747]
@raxsha from @ampproject/wg-stories has 25 merged PRs, including some complex/high quality ones (#33039, #33142, #31229) and should be added to @ampproject/reviewers-amphtml so she can tag/review/merge/triage issues and pull requests.

cf: https://github.com/ampproject/amphtml/pulls/raxsha

**Comment by rsimha** [comment]
👍 ✅
