### ISSUE TITLE
Fix flaky visual diff tests

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#33758]
The following visual diff tests are flaky and have been disabled #33759:
* `amp-story: bot rendering`
* `amp-story-player AMP version`

**Comment by gmajoulet** [comment]
Thank you for fixing the Player one @Enriqe, do you think you could look into the bot rendering one as well? If we break it that could be very bad for our publishers, and that test is our only safeguard. I believe it's ok to cut corners and remove/hide whatever was flaky on the test, enabling it back is important though.

**Comment by Enriqe** [comment]
Yep, I can take a look today.
