### ISSUE TITLE
Intent to implement: Alternate resizing for amp-twitter

### ISSUE THREAD

**Issue by indianburger** [ampproject/amphtml#3377]
Hello,

I'm an engineer on the Twitter widgets team. I was looking at the source code for amp-twitter and I thought I'll suggest a slightly different implementation which doesn't involve looking for iframes and setting up mutation observers. Relevant documentation for resize is [here](https://dev.twitter.com/web/javascript/events#event-resize).

The part of the code I am talking about is [here](https://github.com/ampproject/amphtml/blob/master/3p/twitter.js#L58)

Here's my implementation of it:
```javascript
getTwttr(global, function(twttr) {
    // Dimensions are given by the parent frame.
    delete data.width;
    delete data.height;

    let twitterWidgetSandbox;
    twttr.events.bind('resize', (event) => {
      if (twitterWidgetSandbox === event.target) {
        resize(event.target);
      }
    });

    twttr.widgets.createTweet(data.tweetid, tweet, data).then((el) => {
      if (el) {
        // Not a deleted tweet
        twitterWidgetSandbox = el;
        resize(twitterWidgetSandbox);
      }
    });
  });

  function resize(container) {
  ...
```

Thoughts?

**Comment by mkhatib** [comment]
Hey @indianburger thanks for filing this! You should know better the best way to implement this and this sounds like a much better solution! 

Would this work for both the old iframe based implementation and the shadow dom implementation of the tweet embed? If yes then this LGTM.

**Comment by indianburger** [comment]
> Would this work for both the old iframe based implementation and the shadow dom implementation of the tweet embed?
Yes. The element returned by createTweet could be an iframe or shadow dom, but AMP doesn't need to know. 

What kind of testing do you recommend? I plan to do manual tests on the twitter examples on various browsers. I'll try to write automated tests (which don't exist now I believe) but I haven't looked into them.

**Comment by mkhatib** [comment]
@muxin is working on adding tests to twitter in #2536 

@cramforce was talking about maybe creating an integration test for tweets since it's pretty important to make sure it works, but our integration tests are still flakey so not sure.

**Comment by cramforce** [comment]
Ugh, duh :) Please send PR!!!!
LGTM
