### ISSUE TITLE
Story auto analytics send a lot of story page count pings

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#33784]
While investigating #33783 I noticed that we send a `story_page_count` ping on every story page view. Is this the desired behavior?

It might be that this is intentional in case the story changes length? If so please close as WAI, if not switching to something like the `pageview` (note: not `story-page-view`) should fix.

Repro @ `examples/amp-story/auto-analytics.html` 

to/ @ampproject/wg-stories

**Comment by mszylkowski** [comment]
The config file sets `repeat: false` on the page count [here](https://github.com/ampproject/amphtml/blob/main/extensions/amp-story-auto-analytics/0.1/auto-analytics-configs.js#L40-L42) but that seems to only prevent events when you visit a page you've seen already. We should only fire the event once per story, for which the suggestion to change to `pageview` sounds good.

**Comment by Enriqe** [comment]
In the case of live stories, publishers might want to monitor metrics as new pages are added. But since that case is the exception rather than the general case, using `pageview` as a default SGTM. @mszylkowski do you want to take this on?
