### ISSUE TITLE
[auto-ads] Potential CLS improvements 

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#33803]
The `auto-ads` extension is causing layout shift by injecting ads above the scroll position when scroll pos != 0.

from @kristoferbaxter perhaps we could modify `placeAd()` 
```js
    return this.getEstimatedPosition().then((yPosition) => {
      if (scrollY > yPosition) {
        this.state_ = PlacementState.UNUSED;
        return this.state_;
      }
```

However, this would exclude ads from being placed above the current scroll pos. Perhaps we can ensure slots above the scroll pos reserve their space correctly. 

Currently we add the ad and scroll to offset. We need to investigate if this is affecting CLS/UX and should be improved.

@ampproject/wg-monetization

**Comment by kristoferbaxter** [comment]
@powerivq I've marked this as P1 since any document using auto-ads fails to meet CLS scores in the good category in the wild right now.

**Comment by powerivq** [comment]
https://github.com/ampproject/amphtml/pull/33867

**Comment by powerivq** [comment]
amp-auto-ads currently rely on amp-a4a responsive to changeSize, therefore it does not do `scroll` after insertion. Therefore the CLS won't affect ad resizing. We will be running a holdback experiment to examine the monetary affect of the fix.
