### ISSUE TITLE
[Page attachments] [Outlink] Opening Transition State

### ISSUE THREAD

**Issue by raxsha** [ampproject/amphtml#33812]
Transition state (showing link address) already exists when outlinks are clicked, but now need to show when swiped as well. See mock:

<img width="835" alt="Screen Shot 2021-04-14 at 11 14 20 AM" src="https://user-images.githubusercontent.com/10503669/114734976-be24ff80-9d12-11eb-9051-721caba6c8f9.png">

@ampproject/wg-stories

**Comment by raxsha** [comment]
Test with swiping on the phone

**Comment by processprocess** [comment]
note:
This should follow theme of the CTA.
