### ISSUE TITLE
Remove developers who changed teams from WG GitHub teams

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#33815]
These are used for both Owners Bot and Bundle Size Bot, so they are still getting added to PRs. The ones that come to mind are `@cathyxz , @zhouyx , @wassgha, and @kevinkimball` (though I'm almost certainly missing some).

We should also update OWNERS files where they are listed explicitly. I'll create a PR for this once @mrjoro sees this and possibly alerts me to others who've left AMP that I'm missing

**Comment by kristoferbaxter** [comment]
I'm happy to help with this. Let's review tomorrow.

**Comment by kristoferbaxter** [comment]
Made necessary changes.

**Comment by mrjoro** [comment]
Thanks!  I completely missed this one...
