### ISSUE TITLE
amp-ad DFP rendering issue

### ISSUE THREAD

**Issue by antipath** [ampproject/amphtml#3381]
Hey guys,

ads served via DFP using amp-ad tags seems to create a random issue where the body of the ad would get a margin:8px by default from the browser causing the ad to be mis-aligned with others.

please see screenshot for example.
![screen shot 2016-05-30 at 11 08 23 am](https://cloud.githubusercontent.com/assets/17549718/15653263/e5a5a206-2659-11e6-8d94-81804cfb0236.png)

Since i can't override it with CSS from the parent frame, it might need to be done on your end?

Thanks,
Vince

**Comment by michaelkleber** [comment]
Thanks for the bug report -- quite right, looks like we have a serving path is failing to override the browser-default styling.  We'll look into it.

**Comment by jridgewell** [comment]
@michaelkleber: Is this an AMP specific issue, or is there another place better suited to track this?

**Comment by cramforce** [comment]
I think this might be a Glade issue. @nekodo

**Comment by michaelkleber** [comment]
It's a Glade problem, a fix will not involve touching AMP code, and tracking would be Google-internal.

**Comment by monteduro** [comment]
i'm having this problem too. 

<img src="http://s32.postimg.org/8u6fbb9dh/Schermata_2016_06_07_alle_14_28_55.jpg">

**Comment by mlb7687** [comment]
Fixed

**Comment by adgad** [comment]
Has this been fixed in Glade? Still seeing the same issue in AMP, and just with Glade http://output.jsbin.com/xulivucuso/2

**Comment by mlb7687** [comment]
adgad@, it looks like this is a bad interaction with the creative wrapper header/footer. We can investigate, but the most immediate fix for you would be to have the creative wrapper result in a full html doc where you specify no margin on the body. I'll re-open while we investigate.

**Comment by mlb7687** [comment]
The fix for this is now live. Closing this issue.
