### ISSUE TITLE
Adsense amp-auto-ads, The response does not contain placements object

### ISSUE THREAD

**Issue by hugoteam-demo** [ampproject/amphtml#33823]
Is it an AdSense server side regression or a pub account issue?  
Before amp-auto-ads run fine. about 7 days ago, amp-auto-ads was not okie. although amp-ad run fine on another page. Error:  
- No placements in config
- Unable to fulfill ad strategy

Checked:
- AMP page. Okie, amp-auto-ads added
- Adsense account: the AMP auto option is ON & tested ads settings preview tool, its okie with max 8 ads in-page.

Here is [post link](https://bottlend.com/telegram/pedophile-hunting/), please check. Thanks

**Comment by nainar** [comment]
Hi @hugoteam-demo. I am closing this issue as the example provided relates to sensitive content. Could you please reopen this issue with another example?
