### ISSUE TITLE
Issue when setting up AMP project

### ISSUE THREAD

**Issue by vetri02** [ampproject/amphtml#3382]
Am getting the following error when installing the amp project

when I run 'npm i' getting the following error. PFA the log file

[npm-debug.log.zip](https://github.com/ampproject/amphtml/files/290011/npm-debug.log.zip)

**Comment by erwinmombay** [comment]
@vetri02 just want to clarify, did you clone https://github.com/ampproject/amphtml repo or was it https://github.com/ampproject/amp-by-example ? i see a lot of amp-by-example reference in the logs

**Comment by vetri02** [comment]
sorry this should go to https://github.com/ampproject/amp-by-example

**Comment by erwinmombay** [comment]
@vetri02 its no problem! 👍
