### ISSUE TITLE
Trailing whitespaces are not checked in pull requests

### ISSUE THREAD

**Issue by antiphoton** [ampproject/amphtml#33843]
Although we have a rule in [.editorconfig](https://github.com/ampproject/amphtml/blob/d9fb7104c038c182dc72efba5df5711d83ce613e/.editorconfig) to trim trailing whitespaces, not all editors are using `.editorconfig`. This allows creating and merging pull requests with trailing whitespaces.

It would be nice if we can have some extra checks of trailing whitespaces in pull requests.

**Comment by antiphoton** [comment]
cc @Gregable

**Comment by Gregable** [comment]
@rsimha , is there an easy way to set pull requests for `.protoascii` files to include a trailing whitespace check?

In particular, this bites us when merging these commits into Google's codebase which has the extra linter requirements. It would save a lot of work to do this upfront in the original PR.

**Comment by rsimha** [comment]
One possible approach towards solving this is to include a CI check for all protoascii files using [`prototool`](https://github.com/uber/prototool#prototool). Can I ask someone from @ampproject/wg-caching to take a look at the [linter documentation](https://github.com/uber/prototool/blob/dev/docs/lint.md) and let me know if this will work for you? (Are the right rules in there? If not, what are they? Do you know of other open-source tools that can do this?)

**Comment by Gregable** [comment]
@antiphoton to take a look

**Comment by antiphoton** [comment]
[protocol](https://github.com/uber/prototool) and [buf](https://docs.buf.build/tour-3/) are too much more than what we need. The current issue is Critique is rejecting changes with trailing whitespaces, hence I propose we something like `git diff main -g \ $` in pull request checks.

**Comment by rsimha** [comment]
Can you provide a pointer to the linter being used by Critique to validate `.protoascii` files? If there's an open-source version of it, we can create an `amp` task that runs it against all validator changes. (If that's too much as well, I'm open to creating a task that does what you suggest for `.protoascii` files.)

**Comment by antiphoton** [comment]
The linter rule is declared [here](http://google3/third_party/javascript/amp_validator/METADATA?l=42-44&rcl=367704706), which links to some google3 internal tools.

**Comment by rsimha** [comment]
> I propose we something like `git diff main -G \ $` in pull request checks

I've sent out a more generic solution for this problem that uses the built-in invalid whitespace detection in [`git diff --check`](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---check). This can be applied on any file-types we choose. Let me know what you think of #33926.

Also, could someone in @ampproject/wg-caching comment on what effect this will have on the existing validator tests? Do the outputs need to be updated via `--update_tests`? How does one use this? (I'm on macOS, and wasn't able to install its dependencies.)
