### ISSUE TITLE
🌸 Cherry-pick request for #33709 into #33809 (Pending)

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#33862]
# Cherry-pick request

|       Issue       |       PR       | Beta / Experimental? |   Stable?    |     LTS?     | [Release issue](https://github.com/ampproject/amphtml/labels/Type%3A%20Release) |
| :---------------: | :------------: | :------------------: | :----------: | :----------: | ------------------------------------------------------------------------------- |
| #33709 | #33656 |     **YES**     | **NO** | **NO** | #33809                                                              |

## Why does this issue meet the [cherry-pick criteria](https://github.com/ampproject/amphtml/blob/main/contributing/contributing-code.md#Cherry-picks)?

- Remote page attachments in stories are broken on iOS webviews, including the Google iOS app and Discover
- FYI it appears this is not a recent regression but is now putting a related launch at risk

## List the steps to manually verify the changes in this cherry-pick

- The fix has already been verified by Google iOS engs (`b/182581278#comment10`)

---

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers @ampproject/wg-stories

**Comment by choumx** [comment]
Hello 👋  haven't made one of these in awhile, thoughts? :)

**Comment by estherkim** [comment]
Looks ok, will wait for PR to land and an approval from wg-approvers. Confirming this request is just for Beta and not Stable or LTS?

**Comment by kristoferbaxter** [comment]
Approved!

**Comment by choumx** [comment]
Correct, just beta. Thanks!!

**Comment by choumx** [comment]
#33656 is now merged.

**Comment by estherkim** [comment]
Cherry-picked into beta (opt-in and 1%).

**Comment by choumx** [comment]
Thank you!
