### ISSUE TITLE
amp-ad without amp-ad script is not working. 

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#3394]
<img width="1034" alt="screen shot 2016-05-31 at 6 21 04 pm" src="https://cloud.githubusercontent.com/assets/5419904/15695506/b80d11e0-275c-11e6-862f-0846c86fcc6b.png">
Seems relative to #3363

**Comment by dvoytenko** [comment]
@zhouyx is this in canary or prod?

**Comment by zhouyx** [comment]
I found in local using .max.html
