### ISSUE TITLE
AMP-IMA-Video "origin trial controlled feature not enabled"

### ISSUE THREAD

**Issue by spormeon** [ampproject/amphtml#33945]
This has started appearing in the last few days, anyone got any idea what it is/ why its happening?  I cant tell at the moment if it actually breaks anything or not but it cant be a good thing?

![DevTools_-_cheftalk_com_ads_final_-4](https://user-images.githubusercontent.com/8503167/115673781-e6c97c80-a344-11eb-9b9d-76bfee29e99e.png)

**Comment by alanorozco** [comment]
@spormeon This is a warning, not an error. It doesn't appear you need to worry about it.

It also seems to come from IMA's side, [as you'll see that this message cannot be found in this repository](https://github.com/ampproject/amphtml/search?q=trust-token-redemption).
