### ISSUE TITLE
I2I: <your change/update>

### ISSUE THREAD

**Issue by adp-developer** [ampproject/amphtml#33947]
## Summary

Ad.Player.Pro module provides an ability to play, control video ads in a different ways on AMP pages

## Design document

[AMP & AdPlayer.Pro_ Design document.pdf](https://github.com/ampproject/amphtml/files/6356751/AMP.AdPlayer.Pro_.Design.document.pdf)

## Motivation

A lot of users are using Ad.Player.Pro as an advertising solution and most of these publishers have AMP pages and require using adplayer.pro solution to improve their revenues. 
Comparing to existing AMP elements our solution provides an option to control (through control buttons) not only instream video ads but outstream as well, a lot of our clients want to have a feature to hide player and we also are going to give them that chance by means of extra controls. Additionally, amp-adplayer-pro allows users to run video ads and display ads as a fallback ad at the same time. Also, amp-adplayer-pro can RSS content as ads. Everything is possible to set up and tune through publishers' dashboard at adplayer.pro, hence no changes on publesher's AMP pages required. 

There are some video modules, as well as amp-video-iframe, but sometimes for better User Experience of maximising revenue it requires to use amp-ad, which is not so flexible as amp-adplayer-pro can be.

/cc @ampproject/wg-approvers
@alanorozco @caroqliu @jridgewell

**Comment by alanorozco** [comment]
Please do not create a second I2I. Add link to #33947
