### ISSUE TITLE
[Page attachments] Add component for `amp-story-page-outlink`

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#33955]
`amp-story-page-attachment` covers two different UX patterns (inline and outlink) and isn't semantic.
A new component name for outlinks will help communicate function.

The new name will be: `amp-story-page-outlink`

`amp-story-page-outlink` will point to the code in `amp-story-page-attachment` for backwards compatibility.

To do this:
1. Register element in `amp-story.js`
2. Create validation rules (can copy paste most validation from `amp-story-page-attachment`)

@ampproject/wg-stories

**Comment by gmajoulet** [comment]
Just a nit, the name can stay `amp-story-page-attachment` for the inline one.

**Comment by processprocess** [comment]
> Just a nit, the name can stay `amp-story-page-attachment` for the inline one.

Got it. Description updated.
