### ISSUE TITLE
Shall we consolidate all repo-level documentation in `amphtml` in one place?

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#33964]
Today, the repo-level documentation in `amphtml` lives in two locations:

```
AMP_MODULE_BUILD.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
GOVERNANCE.md
METRICS.md
README.md
SUPPORT.md
contributing/CODE_OWNERSHIP.md
contributing/DESIGN_PRINCIPLES.md
contributing/DEVELOPING.md
contributing/ORIGIN_TRIALS.md
contributing/TESTING.md
contributing/build-on-duty.md
contributing/building-a-bento-amp-extension.md
contributing/building-an-amp-extension.md
contributing/component-validator-rules.md
contributing/contributing-code.md
contributing/creating-a-welcoming-community.md
contributing/creating-good-first-issues.md
contributing/design-reviews.md
contributing/getting-started-e2e.md
contributing/getting-started-quick.md
contributing/good-first-issues-template.md
contributing/issue-priorities.md
contributing/lts-release.md
contributing/release-schedule.md
contributing/running-server-side-experiment.md
contributing/validator-release-schedule.md
contributing/web-standards-related-to-amp.md
contributing/writing-css.md
```

**Two issues:**
- Other than `README.md` and `CODE_OF_CONDUCT.md` (the two default doc files for all GitHub repos), it's not clear why some files are in the root dir and some are in `contributing/`.
- The choice between all-caps and lower-case names seems arbitrary.

@ampproject/wg-outreach I recognize that renaming / moving these files could have effects on the contents of amp.dev. Do you have thoughts or guidance on whether / how we can consolidate these files and standardize their names?

**Comment by kristoferbaxter** [comment]
Don't see any compelling reason to preserve what we have today. If you believe this can make things easier in some way, please move things as you find helpful.

**Comment by patrickkettner** [comment]
SGTM! Let me know when. you want to proceed and I can coordinate a PR for amp.dev to go out

**Comment by rsimha** [comment]
This is done. All repo-level docs now live under https://github.com/ampproject/amphtml/tree/main/docs. The `amp.dev` repo has been updated with the new locations, and the document import workflow [has been verified](https://github.com/ampproject/amp.dev/pull/5843#issuecomment-842355362) as working.
