### ISSUE TITLE
<amp-iframe embeds another iframe with no width or height attribute?

### ISSUE THREAD

**Issue by Vatsalya123** [ampproject/amphtml#33977]
unable to find the root where the <amp-iframe attribute gets added, also the code is not present when we do a view source(initial page load)

Briefly describe the bug.
<amp-iframe embeds another iframe with no width or height attribute which leads to amp error>

## How do we reproduce the issue?

https://www.nasdaq.com/articles/markets-work%3A-how-bolsa-de-valores-de-colombia-is-navigating-covid-19-2020-05-05?amp
https://www.nasdaq.com/articles/3-favorite-stocks-spiritual-billionaire-guru-2014-05-22?amp
 

Please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else. Provide step-by-step instructions for reproducing the issue:

Hit the below provided url and open developer console on chrome
Can see the error on amp plugin
The <amp-iframe code which is injected is not present when we do a view source on initial  load.

## What browsers are affected? Chrome 

All browsers? Some specific browser? What device type?

## Which AMP version is affected?  Not sure

Is this a new issue? Or was it always broken? Paste the version of AMP where you saw this issue. (You can find the version printed in your browser's console.)
 This issue started once we added one <amp-iframe into the page>
 also encapsulates itself with the next sibling and behaves as a child of the first <amp-iframe> 
 

![Screenshot 2021-04-23 at 6 14 45 PM](https://user-images.githubusercontent.com/83075145/115876051-7d8c5b00-a463-11eb-8604-579e3908d7c1.png)

**Comment by alanorozco** [comment]
Your code is wrong. I can see the amp-iframe on view-source: https://www.nasdaq.com/articles/3-favorite-stocks-spiritual-billionaire-guru-2014-05-22?amp on line 885:

```html
  <amp-iframe width="1" title="User Sync"
height="1"
sandbox="allow-scripts"
frameborder="0"
src="https://ads.rubiconproject.com/prebid/load-cookie.html?endpoint=rubicon&max_sync_count=5&args=account:22692">
<amp-img layout="fill" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" placeholder>
</amp-image>
<amp-iframe> 
```

See that the last `</amp-image>` + `<amp-iframe>` is wrong: you want `amp-img` and you want to close the `<amp-iframe>`, not open it. In combination, that's why you get an incorrect nested frame.

```diff
  <amp-iframe width="1" title="User Sync"
height="1"
sandbox="allow-scripts"
frameborder="0"
src="https://ads.rubiconproject.com/prebid/load-cookie.html?endpoint=rubicon&max_sync_count=5&args=account:22692">
<amp-img layout="fill" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" placeholder>
- </amp-image>
- <amp-iframe>
+ </amp-img> 
+ </amp-iframe> 
```
