### ISSUE TITLE
I2I: rcmwidget extension for amp-ad

### ISSUE THREAD

**Issue by yulya9060** [ampproject/amphtml#33976]
### Summary
Hi. 
I added support for amp-ad type=rcmwidget

Widget is used to place dynamic blocks with the most relevant materials on Rambler sites.

/cc @ampproject/wg-approvers

**Comment by yulya9060** [comment]
https://github.com/ampproject/amphtml/pull/33888

**Comment by alanorozco** [comment]
cc @ampproject/wg-monetization

**Comment by calebcordry** [comment]
Hi @yulya9060 could you please give some more details about this widget? This sounds like it might be different that a normal ad implementation? If so, what information does it need? What sort of api calls will it make? Thanks

**Comment by powerivq** [comment]
@calebcordry It's not different. I'm reviewing their PR>

**Comment by calebcordry** [comment]
Oh, never mind then :)
