### ISSUE TITLE
amp-story-player snippets on docs are incorrect

### ISSUE THREAD

**Issue by goonydev** [ampproject/amphtml#33975]
## What's the issue?

Sorry if this is the wrong place. I would like to point out some errors in the doc that make it more difficult for us to use.

Documentation I am reffering to:

https://github.com/ampproject/amphtml/blob/main/spec/amp-story-player.md

**1. Many examples like this one will cause Javascript errors:**

```
player.addEventListener('amp-story-player-touchstart', (event) => {
  console.log('Coordinates:' event.detail.coordinates);
})
```

-> There has to be a concatenate sign "+" between the variables and the strings:

```
player.addEventListener('amp-story-player-touchstart', (event) => {
  console.log('Coordinates:'+event.detail.coordinates);
})

```

**2. The following property does not seem to exist (at least when using an iPhone emulator on Chrome for Windows):**

`player.addEventListener('amp-story-player-touchmove', (event) => {
  console.log('Coordinates:' event.detail.coordinates);
})`

event.detail.coordinates is not there

**3. The following properties paths seem wrong:**  

```
player.addEventListener('storyNavigation', (event) => {
  console.log('User navigated from one page to the other.');
  console.log('Current page id:' event.pageId); // page-2
  console.log('Story progress:' event.progress); // Number from 0 to 1.
})
```

-> this works:

```
player.addEventListener('storyNavigation', (event) => {
  console.log('User navigated from one page to the other.');
  console.log('Current page id:' +event.detail.pageId); // page-2
  console.log('Story progress:' +event.detail.progress); // Number from 0 to 1.
})
```

**4. This example has a lot of problems:**

```
player.addEventListener('navigation', (event) => {
  console.log('Navigated from story 0 to story 1 of 3');
  console.log('Current story:' event.index); // 1
  console.log('Current story:' event.remaining); // 1
})
```

-> This is all I could find to improve it:

```
player.addEventListener('navigation', (event) => {
    console.log('Navigated from story '+(event.detail.index)+' to story '+(event.detail.index+1)+' of '+(event.detail.index+1+event.detail.remaining));
    console.log('Current story:'+(event.detail.index+1));
    console.log('Remaining stories:'+event.detail.remaining);
  })
```

Still, this improved version has flaws.  The first log ("Navitaged from a to b") only works if we navigate forward. It will be wrong if we navigate backwards or rewind from the last story to the first. But the event provided does not have any property that could let us know if we are in any of those cases.

## What browsers are affected?

I tested all these code lines on Chrome for Windows.

**Comment by alanorozco** [comment]
My 2c is that we probably want a comma instead of concatenating.

```diff
- console.log('Coordinates:' event.detail.coordinates);
+ console.log('Coordinates:', event.detail.coordinates);
```

For the incorrect functionality of the snippets, I'll let @Enriqe or @gmajoulet comment.

**Comment by gmajoulet** [comment]
This is all great feedback, thank you @goonydev for taking the time to file an issue!
@Enriqe should be able to take this on :))
