### ISSUE TITLE
Safe zone support to simplify cropping and letterboxing

### ISSUE THREAD

**Issue by alankent** [ampproject/amphtml#33998]
## Describe the new feature or change to an existing feature you'd like to see

Proposal: Add "safe zone" support to making sizing of images and videos easier in web stories to make them cover as much of the screen as possible with a guarantee that "essential" content (e.g. text) is never cropped.

This is not a problem for text layers in a story - it is only a problem when the text or similar is inside an image or video.

The video industry has the concept of "safe zones" near the middle of the screen where it is safe to place text (it will never be cropped due to displaying the video on different sized displays). These zones appear in many video editing packages where the creator is responsible to make sure critical content (like text) does not appear outside that area, and the viewing tools are responsible to make sure that area is always displayed.

Web stories have the same problem. There is a big variation in the aspect ratio of mobile devices - e.g. using Developer mode in Chrome has a drop down list of different devices. iPad and Pixel 2 XL are two extreme size examples (iPad is wide, Pixel 2 XL is tall).

The request is to have support for safe zones in web stories so content can be scaled appropriately with confidence text in the images / videos is always readable.

* One approach is to define a standard "safe zone" like the video industry. No code changes are required, just documentation that "if you want text in images or video to be always be visible, restrict it to this "safe" region of the video.
* Another approach is to allow the safe zone to be defined on a grid layer. Image scaling then takes the safe zone and the image/video size into account to cover the maximal amount of screen possible, while guaranteeing the safe zone is always on the screen.

## Describe alternatives you've considered

The following is not reliable:

      amp-story-page {
        background-color: #fff;
      }
      amp-story-grid-layer {
        padding: 0;
      }

      <amp-story-page id="001-01-9x16">
        <amp-story-grid-layer  template="fill">
          <amp-img src="001-01-9x16.png" width="720" height="1280" layout="responsive"></amp-img>
        </amp-story-grid-layer>
      </amp-story-page>

The above will stretch the image on wide displays. This is fixed with the aspect-ratio attribute

      <amp-story-page id="001-01-9x16">
        <amp-story-grid-layer aspect-ratio="9:16" template="fill">
          <amp-img src="001-01-9x16.png" width="720" height="1280" layout="responsive"></amp-img>
        </amp-story-grid-layer>
      </amp-story-page>

Letterboxing can be achieved using

      <amp-story-page id="001-01-9x16-vertical">
        <amp-story-grid-layer template="vertical">
          <amp-img src="001-01-9x16.png" width="720" height="1280" layout="responsive"></amp-img>
        </amp-story-grid-layer>
      </amp-story-page>

But what is desired is a mode that takes into account the mobile display size as part of the resize calculation, rather than go to one extreme or the other (letterbox or crop).

Another option is to try and remove textual content from images and videos, but this is not always possible. Sometimes text is merged into the image by the graphic designer. E.g. speech bubbles in a comic, or magazine titles that are merged into the other graphics of the page (e.g. might appear behind the character on the page) but must never be cropped for brand quality reasons.

## Additional context

The idea is to avoid letterboxing as much as possible by scaling and cropping unimportant parts of the image, but use letterboxing when necessary to avoid the safe zone from being cropped.

This is particularly important for images such as comics or similar where text is embedded inside the image as speech bubbles. Advanced graphic design also can put text inside the artwork. Allowing the safe zone to be specified per layer allows each layer to work out the bounding box for "must see" content on the layer.

At the moment the content creator has to either guess the safe zone (e.g. use the iPad and Pixel 2 XL dimensions as opposite extremes of dimensions), or use letterboxing which does not look as nice.

**Comment by processprocess** [comment]
cc @mszylkowski for context

**Comment by mszylkowski** [comment]
Actually this might be already implemented with these new [responsiveness presets](https://amp.dev/documentation/components/amp-story-grid-layer/#modern-aspect-ratio). They optimize the layers' aspect-ratio for mobile devices and the background layer crops or letterbox, but can only crop up to 7.1% of the background image on each side (so the safe zone is the center 85.8%). The guarantee of these presets is that the background layers won't need to be letterboxed on any modern phones, but will be cropped either horizontally or vertically to fit the safe zone in the screen. Foreground layers can be used to place text or other foreground elements inside the safe zone while ensuring the positioning will be exact with respect to the background.

**Comment by alankent** [comment]
I don't fully understand the rules from the description (never letterboxes, but max cropped off), but it does sound like what I was after. Thanks!

**Comment by alankent** [comment]
Ah, I am going to suggest a doc change. It does letterbox if it crops more than 7%. Just needs some tweaking to the wording.
