### ISSUE TITLE
[amp-analytics] Session analytics in AMP

### ISSUE THREAD

**Issue by micajuine-ho** [ampproject/amphtml#33990]
To support GA4 in AMP (#24621), AMP will create the idea of a sessions per user per domain per vendor.
We will support the following session related information (see below). We can transmit this data via macros (information is in regards to the session) within our analytics requests. Session information should be able to be linked on navigation from Cache to Origin. 

Goal is to create these macros in a generic and have them persist for the given session length (and until the next session).
 
- [x] Session_id: a low entropy value persisted for 30 minutes per domain per vendor
- [x] Session Creation Timestamp: a timestamp is seconds since epoch when the current session started
- [x] Session Count: starts at 1 and is incremented each time a new session starts
- [x] Engaged:  0 if there has not yet been user engagement and 1 once user engagement is achieved (signaling that this is not a bounced session)
- [x] last-event-timestamp:  a timestamp in seconds since epoch when the most recent event was generated

With this support, GA4 should be able to receive the necessary data from AMP pages regarding user sessions. 

[Design doc](https://docs.google.com/document/d/13JlMTKSHwjWdMLD09Du3ZDaQaPMQJOJg1gYMaY2UCE8/edit?usp=sharing)

**Comment by Francisco-AM** [comment]
The arrival of ga4 would be incredible, does it have a date?
