### ISSUE TITLE
I2I: support for controlled experiment launches

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amphtml#34013]
## Summary

Add runtime support for deploying AMP experiment configuration updates faster, via the CDN and cache pages.

## Motivation

An AMP experiment configuration update takes an average of two weeks to be deployed and reach end users.

An experiment controlled launch to 1%, looking at metrics, and then 10%, 100%, would take a minimum of 6 weeks to complete.

Unlaunching a buggy feature requires a production cherry-pick and can’t be done with an experiment configuration change.

### Goals

* Make experiments work for developers workflow and allow them testing in production environment before launching, without hurting their productivity or delaying projects launches
* Support AMP experiment controlled launches, where a working group can ramp up an experiment launch, eg: 1%, 10%, 100%
* Allow unlaunching a feature with a P0 bug without requesting a cherry-pick

### Experiments with Cache-served pages

We have a hard requirement that the versioned JS files be immutable. But, the experiment configuration can be injected directly onto the page before the `<script src="https://cdn.ampproject.org/rtv/.../v0.js">` script element. E.g., we could have:

```js
<script language=text/json id=__AMP_EXP>{
  "experiments": [
    {
      "name": "foo-exp",
      "percentage": 1.0
    }
    {
      "name": "bento",
      "percentage": 0
    }
    {
      "name": "bar-exp",
      "percentage": 0.5
    }
  }
</script>
```

With a small change in [experiments.js](https://github.com/ampproject/amphtml/blob/main/src/experiments.js), we can check if `AMP_EXP` is defined, and merge with the regular `AMP_CONFIG` (which exists inline in `v0.js`) experiment definitions. This additional `<script>` tag is invalid AMP, however the HTML served from cache does not need to be valid AMP, and can be varied per request.

A server-side configuration file can then live inside the cache server, and the server can dynamically add the above `<script>` tag. Implementation of this feature is up to the cache. A cached page that does not include this script tag will use the default `AMP_CONFIG` object that was added to `v0.js` during compilation.

Note that this solution would not work for origin pages, since the HTML on those pages is controlled by publisher and manually adding this `<script>` tag makes this an invalid AMP page.

### Experiments with origin pages

Origin pages pose a different challenge, as mentioned before, due to the immutability requirement of the served JS files. The unversioned v0.js file has a short max-age cache (10m). We can leverage the short cache and dynamically prepend a different `AMP_EXP` with the active experiments configuration, directly onto the served `v0.js`:

Without controlled experiments (current behavior) | With controlled experiments (proposed)
--- | ---
`self.AMP_CONFIG={"v":"012104081613001","type":"production",…` | **`self.AMP_EXP={"foo-exp":1,"bento":0,"bar-exp":.5};`**`self.AMP_CONFIG={"v":"012104081613001","type":"production",…`

Note that this solution would not work for cached pages, as those get rewritten to include a _versioned_ `v0.js` file and the versioned files are immutable.

#### `AMP_EXP` or `AMP_CONFIG`?

Instead of creating a new `window` global const, we can instead rewrite the `AMP_CONFIG` field, or even completely remove the `AMP_CONFIG`. By rewriting `AMP_CONFIG` will help keep the file size smaller (although the savings will probably stay in the low-hundred bytes range) and keep the initialization logic of the runtime simpler (although support for processing existing `window.AMP_EXP` would still need to be implemented to support cached pages)

### Have the runtime request an experiments config

The runtime can request an experiments config JSON file (e.g., `https://cdn.ampproject.org/experiments-config.json`) with a short lived `max-age` cache but a much longer `stale-while-revalidate` cache. If this config JSON is not already cache, the runtime will only perform this request after the page finishes loading and rendering. In followup requests the end-user’s browser will have this file cached, and can merge the config early.

Performing the experiments config request can be gated/throttled using the hard-coded `AMP_CONFIG` config, if we don’t want every end-user to receive experimental flags.

#### Why was this idea rejected?

By delaying the first request, this avoids slowing down page loads. However, even checking for cached resources is async. To avoid blocking rendering experiments’ values have to have a default value if the cache check isn’t finished yet, which is not ideal.

/cc @ampproject/wg-stories @ampproject/wg-monetization @ampproject/wg-infra @ampproject/wg-caching

**Comment by gmajoulet** [comment]
cc @ampproject/wg-stories it's happening 😍

**Comment by danielrozenberg** [comment]
Summary of design review discussions:

* Feature is a go
* Ideally we should be able to make these configuration changes directly into the repo and have it affect the CDN within ~minutes. This might be difficult or even impossible to implement - we'll explore this option
  * I can implement this feature initially on the CDN only and later attempt to implement configs on GitHub
* `AMP_EXP` is preferred over rewriting `AMP_CONFIG`, due to the simplicity of the implementation
* Order of config preference: `AMP_CONFIG` value < `AMP_EXP` value < values set via console
* We should come up with a way to specify which experiments can be overridden via `AMP_EXP` and which ones cannot; similarly, we need to figure out a way to test and validate experiment config (since we are taking them out of lock-step from the code)
  * Followup question: how do we determine this for the existing configs?
* Should we exempt LTS from these changes? Should we have a separate config file for LTS?
  * Overriding the same experiment(s) for stable and LTS when they are at different code versions can be problematic. We should figure out some kind of compatibility check to make sure an experiment override will actually work with the code it is overriding

Participants: @kristoferbaxter @jridgewell @rsimha @newmuis @rcebulko @mszylkowski (apologies if I missed someone!)

**Comment by gmajoulet** [comment]
> Should we exempt LTS from these changes? Should we have a separate config file for LTS?

Two points to keep LTS exempt from these quick experiment changes:
1. One of the key point is for us to be able to launch/test things fast, so having to wait 1 month for the code to get to LTS is a deal breaker
2. LTS is meant to be more stable, so it makes sense to keep them exempt to these newer experimental experiences that can potentially break. LTS publishers will get the experiences once we know they're stable and fully launched

Thank you for driving this Daniel!

**Comment by danielrozenberg** [comment]
I agree with @gmajoulet on these points. In addition, adding these experiments to LTS complicates things in terms of implementation, and the added value isn't worth the potential dangers it can introduce

**Comment by danielrozenberg** [comment]
This feature has been live for ~2 weeks, see the configs readme file for instructions on how to use it: https://github.com/ampproject/amphtml/blob/main/build-system/global-configs/README.md#client-side-experiments-configjson
