### ISSUE TITLE
`amp-story` swipe up doesn't escape `amp-story-player`

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#34024]
## What's the issue?

When swiping up on a story that is embedded in an amp-story-player, the destination used to "escape" the player and redirect the user. Now the amp-story-player shows the destination within the player itself.

## How do we reproduce the issue?

Here's an example: https://codepen.io/capauwels/full/KKaEEjN
To reproduce, simply add a story containing a swipe up in an amp-story-player

## What browsers are affected?

All browsers

## Which AMP version is affected?

This is a new issue, so I'm guessing it's a breaking change in the latest release of the amp-story-player

**Comment by kristoferbaxter** [comment]
This appears to be a regression, adding @Enriqe to investigate.

**Comment by Enriqe** [comment]
Thanks for the report @cpauwels, we recently made some changes to how the `amp-story-page-attachment` navigates inside the `amp-story` format, which might explain the change in behavior. I'm taking a look.

/cc @ampproject/wg-stories

**Comment by Enriqe** [comment]
My quick initial investigation thinks this is caused by https://github.com/ampproject/amphtml/pull/33656, which is an important fix for another bug. Going to confirm before thinking of next steps.

**Comment by Enriqe** [comment]
Confirmed that reverting f19ff64c6316d369d3a26845a969861f170a5b6d fixes this particular issue. Going to discuss with the team what the best path forward is.

**Comment by gmajoulet** [comment]
Good catch Enrique, the target was `_top` and has been switched to `_self`. The fix should be easy, but let's test it on Safari before shipping it, to make sure that a navigation using `_top` doesn't require a trusted user gesture, which "swipe up" is not.
