### ISSUE TITLE
Autocomplete support for textbox field in AMP forms

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#3403]
As a follow on to #3343, which will introduce support for form fields, including text box, let's also consider how to add autocomplete support.

/cc @mkhatib

**Comment by Sungodragon** [comment]
Guys what can we do for this in search for products

**Comment by rudygalfi** [comment]
@Sungodragon Supporting features like product search is a use case envisioned for a feature like this.

**Comment by heiwen** [comment]
+1

**Comment by aghassemi** [comment]
closing as duplicate of #6625
