### ISSUE TITLE
amp list and mustache

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#3405]
There are several examples of `amp-list` that also use `mustache`.

For example:

```
<ul>
  <amp-list width=auto height=100 layout=fixed-height
      src="https://ampbyexample.com/json/examples.json">
    <template type="amp-mustache" id="amp-template-id">
      <li><a href={{url}}>{{title}}</a></li>
    </template>
  </amp-list>
</ul>
```
However, none of these examples work WRT the mustache substitution.

Is the reason that this url [(https://ampbyexample.com/json/examples.json)] is not CORS-enabled?

Using the test CORS site [(http://test-cors.org/)] the XHR staus is 200 and status text is OK. The site appears to be CORS-enabled.

We also have activated amp-live-list on [(https://cdn.ampproject.org/experiments.html)].

What additions or corrections are needed to activate these list-mustache examples?

What are we missing?

**Comment by jridgewell** [comment]
CC @kul3r4.

**Comment by jaygray0919** [comment]
An update here. My default browser is Firefox. My AMP testing has been done there. Just before sending a snarky email to someone about my issues with amp-mustache, I thought I'd take one last shot and test my URL in Chrome. The amp-mustache examples work in Chrome, but not in Firefox. I've now also tested in Edge and Safari; both work as Chrome works. What information should I be looking for that would explain why the amp-mustache examples work in Chrome-Edge-Safari but not Firefox (46.0.1)?

**Comment by jridgewell** [comment]
The error logs would be helpful. Or, can you make a jsbin that shows the problem?

**Comment by jaygray0919** [comment]
Here is one example: [https://cdn.ampproject.org/c/ontomatica.com/amp_test/amp_list_mustache_6/index.html]
Works in Chrome; fails in Firefox.
We have others that are not as messy (i.e. reading smaller JSON files), but the above illos the issue.

**Comment by jridgewell** [comment]
Seems to be an issue with our XHR service:

```
Error: task failed: amp-list#1#L amp-list#1: Fetch failed https://dl.dropboxusercontent.com/u/3094317/json_avec_items_.json?__amp_source_origin=http%3A%2F%2Fontomatica.com: 'credentials' member of RequestInit 'null' is not a valid value for enumeration RequestCredentials.​​​ _reported_
n.prototype.assert()
 v0.js:7
me.prototype.fetchAmpCors_/<()
 v0.js:268
 v0.js:7:342
```

**Comment by jridgewell** [comment]
CC @dvoytenko

**Comment by dvoytenko** [comment]
Looks like Firefox started implementation of `fetch` and have some issues. I'll work it around, or will try.

**Comment by jaygray0919** [comment]
TY. It's beyond my ability to debug this issue much less fix it. FYI, I have another issue with FF. The Google AMP documents use `word-break: break-word`. FF does not support `word-break: break-word` (using `word-wrap: break-word`). As a result, the AMP docs break on letters, not words. These browsers are diverging in very subtle but troublesome ways.

**Comment by dvoytenko** [comment]
@jaygray0919 Thanks! The issue with CORS calls and Fetch API discrepancies are easy to fix and we'll make sure we cover this by regression tests. However, I don't understand the issue with `word-break`. AMP itself doesn't use this style anywhere nor mandate it in any way. Where are you running into issues with it?

**Comment by jaygray0919** [comment]
First, view this document in Chrome: [https://www.ampproject.org/docs/get_started/about-amp.html]
Then take a look at it in Firefox (I'm running 46.0.1). For me in FF, the right margin breaks on letters. In Chrome, the right margin breaks on a word. IMHO, the reason is that the AMP doc uses `word-break:break-word` which is not on the MDN valid value list. If I replace `word-break:break-word` with `word-wrap:break-word` the breaks in Chrome and FF are identical and break on words. When you have a moment, please confirm or reject my example. There may be other things 'going-on' that could be causing this scenario. For example, I shared my reported case with a Google Webmaster moderator. She told me that the `amp-list amp-mustache` URL works correctly on FF running on her iPhone. Go figure ...

**Comment by jaygray0919** [comment]
As an aside, AMP is a fantastic project. Irrespective of its laudable goals for mobile, it serves to rein-in highly irregular HTML/JS programming. I speak from a managerial perspective where issues of consistency, maintainability and access to 'normal programmers' are more important than exotic menus and complex UX services. Also collision among JS libraries is a serious problem and few can debug the collisions.

I'll insert one modest request here that you might tuck away. Hoping that you will allow JSONP in the future. Many large content publishers (e.g. US NIH) don't support (won't support) CORS but do support JSONP. It's a very light-weight method to publish/subscribe to data.

**Comment by dvoytenko** [comment]
Ok. The Firefox issue with CORS requests is fixed and it will be in canary in a couple of hours.

We considered opening up JSONP format, but decided against it due to a set of security issues associated with it in the past and also due to additional CSP requirements that we'd like to support. The most basic form of CORS is very minimal and should be supportable with a great ease. More complicated scenarios such as credentials propagation are optional and generally not needed for most of use cases.

The word break thing looks like a bug in that particular page. I filed https://github.com/ampproject/docs/issues/114 against that project to fix. That, however, is not really related to AMP, but rather CSS issue in general.

**Comment by nzeeshan** [comment]
I am using amp-mustache to render a list of links on my amp page. It works fine on Android devices, however on Safari iOS, it doesn't work. Here's a [screenshot](http://imgur.com/a/ClqJb) of what I get when accessing the page through Safari.

[AMP page URL](https://www.bnymellon.com/us/en/our-thinking/amp/swimming-against-the-tide.jsp)
[JSON URL](https://www.bnymellon.com/us/en/our-thinking/amp/frances.json)

I am using full paths, not even relative paths and not sure how to resolve this. What am I doing wrong and why does it only work on Android?

**Comment by dvoytenko** [comment]
@nzeeshan Thanks for the report. I moved it into #10195 and referenced you from that issue.
