### ISSUE TITLE
[amp-story] Animation does not work on IOS 14

### ISSUE THREAD

**Issue by goonydev** [ampproject/amphtml#34062]
## What's the issue?

My web story works everywhere I had a chance to test it except on an iphone 12 with ios V14.4.2
Only the image of each page shows but not the text. But when I remove the animation (fly-in) it seems to work.

Here is a test page, where I alternate pages with and without the animation:

https://www.topspeed.com/stories/motorcycles/motorcycle-reviews/triumph/2018-triumph-speed-triple-ar179704.amp.html

There are texts on all pages, but I put the animations on even pages only. It works on all devices even iPhone 6 with IOS V12, but the pages with the animation won't work on my iphone 12.

## How do we reproduce the issue?

Use the following code to define animations in your elements like this:

animate-in="fly-in-right" animate-in-duration="0.7s" animate-in-delay="1s"

## What browsers are affected?

Safari and Chrome on Iphone 12 with IOS 14.4.2

**Comment by processprocess** [comment]
Thanks for filing this @goonydev 
Just to clarify, which ios are you seeing this on?
Under `What's the issue`, `14.4.2` is stated. Under `what browsers are effected`, `12.4.2` is stated.

**Comment by goonydev** [comment]
Sorry for the typo. The problem occurs on IOS 14.4.2

Just edited it.

**Comment by processprocess** [comment]
cc @alanorozco for context.

**Comment by processprocess** [comment]
This test story has examples of all of the animation presets:
https://preview.amp.dev/documentation/examples/visual-effects/amp_story_animations

When viewing the test story on your iphone 12, do the animations run?

**Comment by goonydev** [comment]
Nothing from the test page works on the iPhone 12:

https://www.youtube.com/watch?v=IgdoRb_CG5A&ab_channel=PhilippeDaix

**Comment by processprocess** [comment]
Interesting. Can you confirm that `reduced motion` on your device is `off`?
https://support.apple.com/en-us/HT202655

**Comment by alanorozco** [comment]
@goonydev The animation preset (like `fly-in`) sets up some styling before starting the animation.

In this case, it hides it off-page before animating it. If the browser refuses animations, it will stay hidden. **We should detect animation support, and bail out from styling if so.**
