### ISSUE TITLE
Update `<amp-consent>` component to use CSRF protection as it's sending a POST request

### ISSUE THREAD

**Issue by summercms** [ampproject/amphtml#34084]
Update `<amp-consent>` component to use CSRF protection as it's sending a POST request.

Link to previous conversation: https://github.com/ampproject/amphtml/issues/13716#issuecomment-828669021

@micajuine-ho 

Thanks.

**Comment by micajuine-ho** [comment]
What sort of CSRF protection do you have in mind?

**Comment by summercms** [comment]
Going to close this issue, since I last tested this component over a year ago, it seems to not be sending a post request anymore when updating the consent options and so no csrf protection is needed.
