### ISSUE TITLE
🐞 <amp-facebook> stop working

### ISSUE THREAD

**Issue by Beethoven** [ampproject/amphtml#34138]
## What's the issue?

<amp-facebook> stop working

## How do we reproduce the issue?

Go to https://amp.dev/documentation/components/amp-facebook/
none of the examples works

## What browsers are affected?

MacOs Catalina
Google Chrome - Version 90.0.4430.93 (Official Build) (x86_64)
Safari - Version 14.0.3

**Comment by caroqliu** [comment]
Re-opening this issue to provide context in case others are experiencing this same issue -- looks like FB is having an outage affecting `amp-facebook-*` components.

https://developers.facebook.com/status/issues/492652922187445/

**Comment by kristoferbaxter** [comment]
Thanks Caroline! Closing again since Facebook has resolved the outage on their end.

If there are other issues, please re-open or create a new ticket.
