### ISSUE TITLE
Consider adopting Bazel Closure Rules

### ISSUE THREAD

**Issue by jart** [ampproject/amphtml#3414]
Greetings. I noticed you're using the Closure Compiler for this project. In that case, you may want to consider adopting [Closure Rules for Bazel](https://github.com/bazelbuild/rules_closure) as your build system. This is an effort to open source the build system Google uses internally for JavaScript. Since you're already writing JavaScript in a very Googley way, you have the most to benefit from Closure Rules.

As maintainer of the Closure Rules project, I would be greatly honored if amphtml considered adopting it. I want you to know that I will do everything in my power to help your migration be successful.

Is migrating something you would consider?

**Comment by cramforce** [comment]
We have an explicit goal to use the most mainstream way of building things, to make the project as accessible to developers as possible.
