### ISSUE TITLE
window.context not available in ad iframe 

### ISSUE THREAD

**Issue by guyra1** [ampproject/amphtml#3415]
window.context not available in ad iframe 

when adding amp-ad the ad is served in side and iframe created by amp. it looks something like this:
https://d-1540743224269529284.ampproject.net/1463506087793/frame.html
this frame contains amp api under window.context

inside this iframe there may be the ad iframe which may look as follows
https://securepubads.g.doubleclick.net/gampad/ads?gdfp_req=1&glade_req=1&gl…

this iframe does not contain amp api, window.context is undefined

this makes it impossible to use amp api from inside the ad iframe, for example window.context.observeIntersection

**Comment by cramforce** [comment]
Right. It is only available in the layer AMP controls. Deeper iframes do not get access.

@nekodo is working on allowing deeper frames to get access in #3019
