### ISSUE TITLE
Microsoft Edge redirection mistakenly considered as HTTP protocol

### ISSUE THREAD

**Issue by PHCCorso** [ampproject/amphtml#34167]
## What's the issue?

Similar to: https://github.com/ampproject/amphtml/issues/26061

I get a validation error when I'm trying to redirect the user to Microsoft Edge, like in the example below:

```html
<a href="microsoft-edge:https://www.google.com">Link</a>
```

**Comment by alanorozco** [comment]
cc @ampproject/wg-caching

**Comment by Gregable** [comment]
@PHCCorso can you provide a link to official documentation / spec for this protocol? It would be helpful to add that to the comments in your PR as well.

**Comment by twifkak** [comment]
I'm not @PHCCorso but I was curious so I did some quick digging. LMK what I missed (probably a lot :).

Here's some [Windows-specific documentation](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-default-app#microsoft-edge-uri-scheme).

On iOS, it apparently doesn't work; the alternative is [`microsoft-edge-https://`](https://stackoverflow.com/questions/51025950/is-there-a-url-scheme-to-open-a-website-in-microsoft-edge-on-ios).

I see some reference that it [works on Android](https://stackoverflow.com/questions/59846066/url-scheme-to-call-the-microsoft-edge-app), but the official recommendation seems to be to [use intent URIs](https://developer.chrome.com/docs/multidevice/android/intents/).

Some other docs I found along the way:
- https://gist.github.com/felquis/a08ee196747f71689dcb
- https://dynamics.mittermair.pro/2019/01/29/browser-url-schemes/

**Comment by Gregable** [comment]
I'd be happy with your first link. This doesn't look like it'll work most of the time, but it won't be a security risk either. I'll add the comment in the PR review as well.

**Comment by PHCCorso** [comment]
> I'm not @PHCCorso but I was curious so I did some quick digging. LMK what I missed (probably a lot :).
> 
> Here's some [Windows-specific documentation](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-default-app#microsoft-edge-uri-scheme).
> 
> On iOS, it apparently doesn't work; the alternative is [`microsoft-edge-https://`](https://stackoverflow.com/questions/51025950/is-there-a-url-scheme-to-open-a-website-in-microsoft-edge-on-ios).
> 
> I see some reference that it [works on Android](https://stackoverflow.com/questions/59846066/url-scheme-to-call-the-microsoft-edge-app), but the official recommendation seems to be to [use intent URIs](https://developer.chrome.com/docs/multidevice/android/intents/).
> 
> Some other docs I found along the way:
> 
>     * https://gist.github.com/felquis/a08ee196747f71689dcb
> 
>     * https://dynamics.mittermair.pro/2019/01/29/browser-url-schemes/

Thanks!
