### ISSUE TITLE
Flying Carpets should collapse when in first or last viewport

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#3416]
This is something intrinsic to the "flying carpet" effect. If you're in the first viewport, you'll never see the bottom of the content inside. And if you're in the last viewport, you'll never see the top of the content.

So when we are inside the first or last viewport, we should instead collapse the flying carpet.

Related to https://github.com/ampproject/amphtml/issues/3338.

**Comment by jridgewell** [comment]
CC @kashyapnitin @jasti

Alternatively, we can:

- Relatively easy to accomplish:
  - Collapse Flying Carpet
  - Render without the effect (essentially, turn `<amp-fx-flying-carpet>` into a normal `<div>`)
  - Render with partial effect (top or bottom of the content will never be shown, but effect works)
- **Very** hard to accomplish:
  - Parallax scrolling (ie, scrolling the carpet at a different speed than the viewport)

**Comment by jasti** [comment]
@jridgewell My preference is to 'Collapse Flying Carpet' and we are super clear about placement in docs. Motivation behind this is to fail fast and get the right behavior vs hope that the alternate is palatable. Also we should prob never not show content :)

Also as discussed, can we collapse when there is no ad returned and no placeholder?

**Comment by jridgewell** [comment]
> Also we should prob never not show content

But that's what I mean by "collapse flying carpet". We plan on making it have `height = 0`, so that it does't disrupt the reader.

> can we collapse when there is no ad returned and no placeholder

https://github.com/ampproject/amphtml/issues/3338

**Comment by jasti** [comment]
👍 My comment :
> Also we should prob never not show content
was specifically regarding your option 
> Render with partial effect (top or bottom of the content will never be shown, but effect works)

We are good!
