### ISSUE TITLE
Intent-to-Implement: segment

### ISSUE THREAD

**Issue by yields** [ampproject/amphtml#3418]
We would love to add [Segment](https://segment.com) as an amp-analytics plugin, we already shipped query string support to our APIs and have the [plugin](https://github.com/segmentio/amphtml/tree/add-segment) ready in our fork.

A simple example that sends a pageview:

```html
<amp-analytics type="segment">
<script type="application/json">
  {
    "vars": {
      "writeKey": "<key>",
    }
  }
...
```

Cheers!

**Comment by cramforce** [comment]
Awesome to have you on board!

LGTM

**Comment by cramforce** [comment]
CC @rudygalfi

**Comment by calvinfo** [comment]
Thanks guys! We've tested and deployed AMP tracking on our side of things–is there anything else we have to do to be included? Appreciate the reviews here.

**Comment by calvinfo** [comment]
Whoop, totally missed that this is an issue–not a PR. Once we PR is there anything we need to do before merging?

**Comment by jridgewell** [comment]
We just need to review the PR to make sure it's following all of our conventions. It usually goes very quickly.

**Comment by calvinfo** [comment]
Got it, thanks @jridgewell!
