### ISSUE TITLE
I2I: Make pageViewId64 variable available for delayed fetch amp-ad

### ISSUE THREAD

**Issue by oliverfernandez** [ampproject/amphtml#34190]
## Summary

Both `pageViewId` and `pageViewId64` are available for fast-fetch ad networks. However only `pageViewId` is available for delayed-fetch ad networks.

I'd like to make `pageViewId64` also available for delayed-fetch ad networks that render inside a 3p frame.

## Motivation

`pageViewId64` has a higher entropy, and it's very useful for ad serving on sites that may have  thousands of page views per user, where `pageViewId` as a high risk of collision. Actually, this collision is already happening to us, and it's the main motivation to implement this.

`pageViewId64 ` already available in fast-fetch ad networks, like DoubleClick or Adsense.

/cc @ampproject/wg-approvers @ampproject/wg-ads-reviewers @ampproject/wg-components

**Comment by alanorozco** [comment]
cc @ampproject/wg-monetization 

Did this go through Design Review?

**Comment by oliverfernandez** [comment]
I didn't go through a Design Review, because it seems a small change, and it's something already available for ad networks implemented via fast-fetch.

I'm really sorry if I should have gone through it

**Comment by alanorozco** [comment]
@oliverfernandez It's no problem, I'm only keeping track. I'll let @ampproject/wg-monetization weigh in to whether it needs a review.

**Comment by oliverfernandez** [comment]
Any news on this? @ampproject/wg-monetization
