### ISSUE TITLE
Add src/config attribute to amp-story-auto-ads element

### ISSUE THREAD

**Issue by WagneRaz18** [ampproject/amphtml#34192]
As a developer I want to pass the JSON configuration object as an external path.
For example:
**instead of** 
```
<amp-story-auto-ads>
		<script type="application/json">
			{  
                         "ad-attributes": {
                                "type": "doubleclick",
                                "data-slot": "MY DATA SLOT"
                                 }
                        }
		</script>
</amp-story-auto-ads>
```

**I want to be able to write**
```
<amp-story-auto-ads src=URL_TO_JSON>
</amp-story-auto-ads>
```

Just like amp-analytics element have a `config` attribute

```
<amp-analytics
  config="https://example.com/analytics.account.config.json"
></amp-analytics>
```

**Comment by alanorozco** [comment]
cc @ampproject/wg-monetization

**Comment by calebcordry** [comment]
Thanks for filing!  Is this because it's easier for you all to update this endpoint than to rewrite the documents? Or are you envisioning that a third party might offer this service?

Either way I can bring it up in this weeks monetization team sync.

**Comment by WagneRaz18** [comment]
The first option. It's much easier to update this endpoint the html itself.
Thank you very much!

**Comment by calebcordry** [comment]
@WagneRaz18 : @jshamble has added this functionality. You can start testing in tomorrow's nightly if you like. It should hit prod in ~2 weeks. Please let us know if you have any issues.
