### ISSUE TITLE
Consider introducing --debug flag for gulp test command

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#3423]
So with #3313 we started removing the test iframes after the test is run. Sometimes it's useful to keep them around to debug the DOM structure that was generated during tests. I suggest we enable this kind of behavior with a `--debug` flag or something more specific like `--nocleanup`.

@jridgewell suggested to make this the default behavior when one passes `--watch`. I think it'll be useful to keep the behavior of cleaning up even when watching, since watching is used sometimes for really just watching and re-running tests while editing code or tests, not removing iframes in watch mode might cause a lot of tests to timeout because of the memory issues.

cc/ @sriramkrish85 @jridgewell

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
