### ISSUE TITLE
Render timeout waiting for service amp-story-render to be ready

### ISSUE THREAD

**Issue by Enriqe** [ampproject/amphtml#34271]
We still see `Uncaught Error: Render timeout waiting for service amp-story-render to be ready.` in certain cases with the web player. We tried to mitigate them with #22774 but it seems like it's not enough. We should try to either change these to warnings or at least allow developers using the `amp-story-player` to catch them. 

/cc @ampproject/wg-stories

**Comment by gmajoulet** [comment]
Do you know how to repro this?

**Comment by tejesh0** [comment]
@gmajoulet Codepen demo which fails to open the webstory in lightbox with same console error: https://codepen.io/maenrique/pen/rNLyqXg

**Comment by swissspidy** [comment]
Also reported at #35712

**Comment by adamdunnage** [comment]
We have a new report of this in the Web Stories support forums which you can find here: https://wordpress.org/support/topic/webstories-not-displaying-in-sidebar-via-shortcode/#post-15350186.

The user is trying to add the Web Stories embed code to the 'sidebar' of their page. The story isn't displaying on the page and I can see the following console errors on the page.

`Uncaught Error: Render timeout waiting for service amp-story-render to be ready`

&

`Uncaught (in promise) Error: No messaging channel: initMessagingChannel timeout`

**Comment by gmajoulet** [comment]
We just removed this `amp-story-render` service entirely so the error will go away in the next 2 weeks. Closing this ticket.

However I think the issue you're seeing is completely unrelated and that error log is just a consequence of some other issue. I couldn't repro following the bug report in your ticket, can you open another ticket and cc me on it? I'll help look into it.

**Comment by swissspidy** [comment]
@gmajoulet new ticket was created here: #37642

I doubt it's an issue with the player though because of all these other JS errors on that user's page.

**Comment by lovetonature** [comment]
Hi there, I seemed to have the same issue. https://wordpress.org/support/topic/cant-see-webstories-only-on-click/ I changed to https, i suppose there is another issue? if i should n ot comment here, please let me know i delete then.

**Comment by lovetonature** [comment]
I sorted it. it was a short code issue? could that be? I changed it to "[Recent-stories column="3" show-button="yes" show-no-of-story="all" button-text="Default view" order="DESC" btn-color="#8BCDA0" btn-text-color="#000"]"

I deleted the other short code, but i got it from the plugin i assume. 

> Hi there, I seemed to have the same issue. https://wordpress.org/support/topic/cant-see-webstories-only-on-click/ I changed to https, i suppose there is another issue? I have the same issue.. only on click i can see the reel. if i should n ot comment here, please let me know i delete then.
