### ISSUE TITLE
[amp-story-player] Scrolling away from a web story player is very laggy.

### ISSUE THREAD

**Issue by goonydev** [ampproject/amphtml#34272]
## What's the issue?

Including a web story using the amp-story-player disrupts the scrolling through the main page on mobiles for me. If I ignore the web story at the first place and scroll down passed it everything's fine. If I try to use the player and move through the story, then try to scroll up or down to move on to the rest of the parent page, it gets very laggy. The viewport vibrates up and down, sometimes it will wait a second, then jump to a position of the page that is far. It is quite irritating as a visitor. I suspect there are so many events attached to the player that it takes time to give the focus back to the parent page.

Here is a test page, you can see the web story player (after the first paragraph of the article):
 
https://www.topspeed.com/motorcycles/motorcycle-reviews/triumph/2018-2020-triumph-speed-triple-s-rs-ar183973.html

## How do we reproduce the issue?

Check a web-story-player on iphones. Tap the story to move to another slide then try to scroll up or down to get out of the web story and move to the rest of the page.

## What browsers are affected?

Chrome/Safari on IOS 12.X (iPhone 6) and 14.X (iPhone 12)

**Comment by ychsieh** [comment]
Not reproducible
