### ISSUE TITLE
[Page attachments] CSS code cleanup

### ISSUE THREAD

**Issue by raxsha** [ampproject/amphtml#34316]
Code cleanup:
Duplicating the files instead of overriding the CSS as we have today.

**Comment by processprocess** [comment]
The demo story in [this PR](https://github.com/ampproject/amphtml/compare/main...processprocess:cta-demo-story?expand=1) Has use-cases of each configuration and can be used for cleanup.
It's the files from the [cta demo story](https://wsdemos.uc.r.appspot.com/cta-buttons)
