### ISSUE TITLE
amp-list and flexibility when targeting a JSON object

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#3432]
amp-list and amp-mustache expects a JSON object containing an array property "items".
The official AMP example is:

```
{
  "items": [
    {
      "title": "amp-carousel",
      "url": "https://ampbyexample.com/components/amp-carousel"
    },
    ...
  ]
}
```
Is it possible with AMP to navigate a JSON object by specifying an alternative JSON key for "items"?
For example, in the JSON object below, specify that "Properties" is a substitute for "items"?

```
{
  "PropertyTable": {
    "Properties": [
      {
        "CID": 2244,
        "MolecularFormula": "C9H8O4"
      }
    ]
  }
}
```

A mustache template would look like this:
```
  <template type="amp-mustache" id="amp-template-id">
    <li>Identifier: {{CID}}</li>
    <li>Chemical formula: {{MolecularFormula}}</li>
  </template>
```

**Comment by erwinmombay** [comment]
/to @dvoytenko for discussion and reasoning of why "items" was chosen

**Comment by dvoytenko** [comment]
@jaygray0919 I can certainly see expanding this format to allow to specify the path to the items array. We'd welcome a pull request on this.

**Comment by jaygray0919** [comment]
Please see: https://github.com/ampproject/amphtml/issues/3554
Should have added the above there.

**Comment by dvoytenko** [comment]
De-dupping to #3554 since most of the discussion is taking place there.
