### ISSUE TITLE
Make it easier to determine what went to prod when

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#3433]
We have two main issues right now we should fix:
1. When we patch a release, the release notes do not point to the original release. We should have a link to the release it is based on.
2. We should make a note in the release notes for when they go to 1%, full production, etc. including date and time.

This will make it easier to track bugs to specific releases.

**Comment by rudygalfi** [comment]
Did #3435 and #3439 completely resolve this, or still more to do? Is Current still a good milestone?

**Comment by erwinmombay** [comment]
not yet, theres some internal work left to be done to put in the percentage when we transition from opt-in to percentage and change of percentage value.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)

**Comment by cramforce** [comment]
@

**Comment by cramforce** [comment]
Can we close this?

**Comment by erwinmombay** [comment]
@cramforce dont think so. we don't do the 1% update yet

**Comment by erwinmombay** [comment]
closed by https://github.com/ampproject/amphtml/pull/8560
