### ISSUE TITLE
amp-list breaks on large SVG

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#34357]
Here is reference SVG-1
link: SVG-1
https://afdsi.com/_amp-issues/list/pizza_1_1.svg

**Success**: using `amp-list`, `amp-state` and `template` as a data source
link: AMP-1
https://afdsi.com/_amp-issues/list/pizza_1_2.html

Here is reference SVG-2
link: SVG-2
https://afdsi.com/_amp-issues/list/pizza_2_1.svg

*Failure*: using `amp-list`, `amp-state` and `template` as a data source
link: AMP-2
https://afdsi.com/_amp-issues/list/pizza_2_2.html

Analysis:
AMP-1 and AMP-2 are valid AMP
SVG-2 is larger than SVG-1
AMP-1 and AMP-2 have identical configurations; only difference is size of SVG and number of items mapped to SVG from `amp-state`

We've submitted SVG-related issues before and have changed our approach accordingly.
Example from @kristoferbaxter:
https://github.com/ampproject/amphtml/issues/31818#issuecomment-756429494
We are not repeating that mistake.

We've tried different techniques, and technique combinations such as:
avec/sans (with/without) `items="."`
avec/sans `{{#items}}` `{{/items}}`
Different `height` values for `amp-list`
Moved `amp-list` after `</body>`

None is successful.

Are we doing something wrong, or is there some interaction between `amp-list` and `SVG` that is causing the error?

/jay gray

**Comment by alanorozco** [comment]
You're doing something wrong.

Your working example references keys without quotes: `{{101}}`.

**Comment by alanorozco** [comment]
It's not the SVG.

- Your working example references keys without quotes: `{{101}}`.
- Your failing example adds quotes: `{{"101"}}`.

Remove the quotes, [it works fine.](https://amphtml-issue-34048.glitch.me)

**Comment by jaygray0919** [comment]
@alanorozco am humiliated. thank you for the quick analysis.

**Comment by alanorozco** [comment]
Happy to help. All I did was compare the docs side by side.
