### ISSUE TITLE
Wrong LargestContentfulPaint for direct page visits

### ISSUE THREAD

**Issue by diasflack** [ampproject/amphtml#34383]
## What's the issue?

 LCP metric for directly visited AMP pages is entirely wrong.

## How do we reproduce the issue?

1. Open /test/manual/amp-analytics/core-web-vitals.html from this project
2. Open dev tools performance tab
3. Reload the page with profiling
4. Make tab inactive, then active (to send metric)
5. Look at the network requests; you'll find something like this - 'https://fake.com/webvital?pid=MAYpDqjet6d1giVjjemcfQ&host=localhost&lcp=966.719970703125'
6. Compare performance tab LCP metric and value sent in the request
7. They will be different
* And sometimes request LCP will be equal to 0

![image](https://user-images.githubusercontent.com/5046498/118283367-f6695a80-b4d7-11eb-93e5-54e045a4f8eb.png)
![image](https://user-images.githubusercontent.com/5046498/118283425-03864980-b4d8-11eb-8ab8-52f374d0bbec.png)

## What browsers are affected?

I use Chrome for Mac (ver 90)
But I think it's broken pretty much everywhere

## Which AMP version is affected?

2105121154000

**Comment by diasflack** [comment]
I looked at the performance-impl module code and found some strange things from my perspective.

**LCP metric uses by default LoadTime, not RenderTime**

I can't say that I understand why it is done like this. I think it is connected to the main use case of AMP pages as embedded in google search, but it definitely should work another way for direct AMP pages.

renderTime is prioritized in LargestContetfulPaint documentation and is used as the main value in the web-vitals js library. 

**LCP metric is calculated from firstVisibleTime, not from navigationStart or timeOrigin**

I think this is the main issue why values are so different. 

For embedded pages, it may be suitable because you need to calculate metric when the page is visible, but for direct links, it is visible from the start.

And the difference between timeOrigin and visibility change could be enormous. It creates a gap in values, lowering the LCP metric, sometimes to 0.

**It takes into account only first LargestContentfulPaint**

I think this is a bug connected to the usage of the loadTime and not the renderTime.

For example, we have 2 LCP objects in perfomanceObserver. Second can have loadTime = 0, and first not 0, then first LCP event will be used, although they both have not 0 renderTime.

It happens a lot on the /test/manual/amp-analytics/core-web-vitals.html page.

**Finally**

I think that the problem is that the module was created especially for Embedded AMP pages and not suitable for Direct AMP pages.

Maybe, the solution will be to design slightly different logic for not Embedded pages.

Unfortunately, there are many direct AMP pages at the google search console, and their values are not so good. 

To fix that, we need reliable metrics that instantly react to the changes.

Let me know what you think about that, and also, if you need spare hands, I will be glad to contribute. 

If so, I will be very grateful if you point me where to go next.

**Comment by kristoferbaxter** [comment]
@erwinmombay can you take a look at this and help to drive to a resolution?

**Comment by erwinmombay** [comment]
Update on this, I'm going to add the `Timing-Allow-Origin` on image subresources. This should give us the opportunity to switch over to render time while we are on the Google AMP cache

**Comment by samouri** [comment]
I think [this PR](https://github.com/ampproject/amphtml/pull/35070) will fix the issue

**Comment by samouri** [comment]
I tested locally, and the linked PR only partially fixed the issue. 

The LCP value sent to analytics is actually our custom `LARGEST_CONTENTFUL_PAINT_VISIBLE`. I don't have great context for why we do that, but I assume it is to account for prerendering viewer behavior.

An issue is that even for origin page visits without a viewer, the "since visible" will still reduce the LCP value by a significant amount corresponding to when the `FIRST_VISIBLE` signal is fired: 
https://github.com/ampproject/amphtml/blob/1459825bf48958006a8f99b326ce47102c4b5df8/src/service/ampdoc-impl.js#L644

**Comment by samouri** [comment]
cc @alanorozco
