### ISSUE TITLE
Reduce size of v0.mjs

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#34386]
**summary**
Writing this issue to capture reasonable steps we could take to further reduce the size of the primary binary, `v0.mjs`.  When measuring locally, the size goes from 61kb --> 48kb (20% drop).

1. Move `HistoryBindingVirtual` from v0.mjs to viewer-integration: 2kb saving.
2. Move `Performance` and `Viewer` services to viewer-integration: 3kb savings.
3. Completely migrate from `R0` to `R1` for all 0.1 components: at least 6kb savings, and likely significant runtime speedup.
4. Enabling `ADVANCED_OPTS` in Closure when we are fully type checked: 2kb savings.

**Comment by xiaolongg02** [comment]
Hi, samouri, I am confused about 'migrate from R0 to R1 for all 0.1 components', Does it mean upgrade components with preact? will it benifit performance and how?  I looking forward to your answer.BWTY

**Comment by samouri** [comment]
Hey @xiaolongg02, it does not mean that. Its converting all of our components to using the R1 Resources System which was created as part of https://github.com/ampproject/amphtml/issues/31915. By default all components use R0.

https://github.com/ampproject/amphtml/blob/27a4ef3c53b21044d82973b20891a95179d1075f/src/base-element.js#L108-L124
