### ISSUE TITLE
🖍 Styles from `ampcustom.css` can apply unexpectedly to `img` elements on “pre-valid” AMP pages

### ISSUE THREAD

**Issue by westonruter** [ampproject/amphtml#34402]
### Description

In two cases recently, users of the AMP plugin for WordPress have reported issues with `ampshared.css` applying `position:relative` to `img` elements in part unexpectedly, although also expectedly since the pages are not valid AMP. However, the pages are using `img` elements in a way that they should _eventually_ be valid once https://github.com/ampproject/amphtml/issues/30442 is realized and `img` is valid AMP.

<h2>
      SSR'ed <code>amp-img &gt; img</code> which has <code>width</code> &amp; <code>height</code>
</h2>

An `amp-img > img` element gets a `fill` layout with absolute positioning inside of its statically-sized container. As such, the `img` does not need a `width` or `height`. When AMP Optimizer does SSR, the `img` may be prerendered as a hero, in which case the page will have the `img` in the original markup without waiting for the AMP runtime to create it lazily. A problem arises when optimization layers like Mod_Pagespeed may see such `img` elements and automatically add `width` and `height` attributes in a well-intentioned attempt to reduce CLS (see https://github.com/apache/incubator-pagespeed-mod/issues/2067). This causes two problems in AMP:

<ol>
	<li>The validator doesn't allow <code>width</code> and <code>height</code> attributes on SSR'ed hero <code>img</code> elements, resulting in an invalid AMP page.</li>
	<li>The <code>ampshared.css</code> stylesheet has <a href="https://github.com/ampproject/amphtml/blob/adfe2d4f8d53214d3c12e17dca27332fadf0f007/css/ampshared.css#L69-L76">two</a>
		<a href="https://github.com/ampproject/amphtml/blob/2297f1e6116de2b3264af8803b15669aec7de2a1/css/ampshared.css#L279-L291">rules</a> with selectors containing <code>[width][height][sizes]</code>
		which inadvertently gives the element <code>position:relative</code>, which has the effect of hiding the image when intrinsic layout is applied since the sizer pushes it into the overflow.</li>
</ol>

![issue1](https://user-images.githubusercontent.com/134745/118343011-1bab9800-b4db-11eb-89ba-48e301749713.jpg)

<h2>
	Native non-AMP <code>img</code> elements with <code>width</code>, <code>height</code>, and <code>sizes</code> attributes
</h2>

<p>
	Similarly to the above, when a non-AMP <code>img</code> is used on the page and it has <code>width</code>, <code>height</code>, and <code>sizes</code> attributes
	then the aforementioned <a href="https://github.com/ampproject/amphtml/blob/adfe2d4f8d53214d3c12e17dca27332fadf0f007/css/ampshared.css#L69-L76">CSS</a>
	<a href="https://github.com/ampproject/amphtml/blob/2297f1e6116de2b3264af8803b15669aec7de2a1/css/ampshared.css#L279-L291">rules</a> will
	give the element <code>positoin:relative</code> when it may be needing absolute positioning. This issue will become more and more common once <code>amp-img</code>
	is <a href="https://github.com/ampproject/amphtml/issues/30442">deprecated</a>, as <code>img[loading=lazy][decoding=async][width][height][sizes]</code> elements
	will start appearing on AMP pages much more often.
</p>

<p>
	For example, consider the Cover Block in WordPress which has an image
	positioned absolutely with a fill layout and some text overlaying it. In the following example, the fill layout is broken because relative positioning is being applied.
</p>

![issue2](https://user-images.githubusercontent.com/134745/118343012-21a17900-b4db-11eb-8096-f8410fbbded2.jpg)

## Conclusion

The two problematic CSS selectors in `ampshared.css` are:

* `[width][height][sizes]:not([layout]):not(.i-amphtml-element)`
* `[width][height][sizes]:not([layout]):not(.i-amphtml-layout-responsive)`

The latter was introduced in #28115 while the former is much older, originating in #12077.

### Reproduction Steps

See test case: https://ampshared-img-styling-issues.glitch.me/

### Browser(s) Affected

Chrome, Firefox, Safari, Edge, UC Browser

### AMP Version Affected

2104302228000

**Comment by westonruter** [comment]
cc @jridgewell

**Comment by westonruter** [comment]
cc @dkoo who has some more examples from Newspack

**Comment by kristoferbaxter** [comment]
Thanks for sharing Weston, we'll try to get this resolved as we add official support for HTMLImageElements.

**Comment by jridgewell** [comment]
We could add `width`/`height` support for validator, and add `:not(img)` to the selectors.
