### ISSUE TITLE
CORB error

### ISSUE THREAD

**Issue by EMamichev** [ampproject/amphtml#34419]
### Description

https://github.com/ampproject/amphtml/blob/main/ads/vendors/zen.md

this block doesn't render and shows warning

![image](https://user-images.githubusercontent.com/51496906/118555723-a7d3ee80-b76b-11eb-8171-e6f56bc2b05d.png)

### Reproduction Steps

add block to playgroung or any amp page

### Browser(s) Affected

Chrome

### AMP Version Affected

latest

**Comment by jridgewell** [comment]
We do not control the URL `https://zen.yandex.ru/widget-loader`, so  it's impossible for us to fix this. I'd suggest reaching out to your contact at Zen to have them fix the problem.
