### ISSUE TITLE
Amp Story Desktop One Panel I2I

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#34479]
### Summary

Desktop panels mode was initially created as a visually rich UI to display stories on large landscape screens. Since then we’ve introduced new features such as the [`amp-story-player`](https://amp.dev/documentation/components/amp-story-player/?format=stories), [amp story animations](https://amp.dev/documentation/examples/visual-effects/amp_story_animations/?format=stories) and [`amp-story-panning-media`](https://amp.dev/documentation/components/amp-story-panning-media/?format=stories) which rely on a one panel view. These new features either do not work in the desktop panels mode or look broken. This leads to design compromises, fragmented UX and technical debt.

In the effort to modernize, futureproof and accelerate innovation on the Web Stories format we are implementing a one panel desktop experience to put focus on a primary UI type that can support immersive experiences consistently on all displays. 

This change does not impact desktop full-bleed ([supports-landscape](https://amp.dev/documentation/components/amp-story/?format=stories#landscape-orientation-and-full-bleed-desktop-experience-opt-in)) stories.

### Motivation

We are currently maintaining 2 different UX display types. Refactoring this to 1 will fix bugs that arise from trying to fit our experience into the desktop panels display. It also unlocks opportunities currently infeasible due to desktop panels, such as page transitions or a desktop player carousel.

Any story that is viewed on a landscape display that is not full-bleed ([`supports-landscape`](https://amp.dev/documentation/components/amp-story/?format=stories#landscape-orientation-and-full-bleed-desktop-experience-opt-in)) will look different. These stories will now appear as one panel. 

The aspect ratio in the one panel desktop experience will be 69 x 116 which is slightly wider than the three panel desktop display (3 x 5). 

Large landscape screens:
<img width="681" alt="Screen Shot 2021-05-21 at 1 40 30 PM" src="https://user-images.githubusercontent.com/3860311/119177303-21a0fc00-ba3a-11eb-8f2e-fc2deb63def3.png">

Small landscape screens:
<img width="496" alt="Screen Shot 2021-05-21 at 1 42 07 PM" src="https://user-images.githubusercontent.com/3860311/119177464-5c0a9900-ba3a-11eb-9893-ae563f46cddf.png">

The inline-page-attachment content will display as a drawer within the desktop UI:
<img width="681" alt="Screen Shot 2021-05-21 at 1 41 15 PM" src="https://user-images.githubusercontent.com/3860311/119177369-38dfe980-ba3a-11eb-9e46-84a7b0d702ee.png">

As a result:
- All screen sizes and ratios will be supported [#32503](https://github.com/ampproject/amphtml/issues/32503) [#32500](https://github.com/ampproject/amphtml/issues/32500) [#31034](https://github.com/ampproject/amphtml/issues/31034) [#30294](https://github.com/ampproject/amphtml/issues/30294)
- Animations will be consistent on all displays [#29753](https://github.com/ampproject/amphtml/issues/29753)

### Alternative Solutions

The desktop one panel mode will be developed behind an experiment allowing the feature to be previewed with any existing story. In this way any context that is currently relying on the panel layout will be able to preview the new desktop UI. 

Once the code is complete the feature will be rolled out behind an experiment to catch any edge cases, then launched to 100%. At that time the desktop panels UI will be removed in favor of the desktop one panel UI.

### Additional context

This is in an effort to support the experience of Web Stories on all screen sizes and ratios, and display immersive content consistently. 

As a follow up we intend to implement a performant **background blur** for a more visually rich experience:
<img width="680" alt="Screen Shot 2021-05-21 at 1 43 32 PM" src="https://user-images.githubusercontent.com/3860311/119177601-8a887400-ba3a-11eb-9d21-f4a7fd913514.png">

This also paves the way for a **desktop carousel player** player so users can more easily access other publisher’s content or related stories (Design WIP):
<img width="680" alt="Screen Shot 2021-05-21 at 1 43 50 PM" src="https://user-images.githubusercontent.com/3860311/119177661-a12ecb00-ba3a-11eb-86a0-d35b4fb436fe.png">

### Launch Tracker

[Dashboard](https://github.com/ampproject/amphtml/projects/128)

### Notifications

/cc @ampproject/wg-approvers

**Comment by kristoferbaxter** [comment]
Discussed during design review today and there was agreement for going down this path. Thank you for presenting!
