### ISSUE TITLE
<amp-consent> user's preference not saving in local storage.

### ISSUE THREAD

**Issue by jpolanco91** [ampproject/amphtml#34471]
### Description

Hi folks, I have a GDPR consent flow set up with `<amp-consent>` which is set up with a `consentRequired: ‘remote’` and an API endpoint to handle the consent in the `checkConsentHref`, and as the docs say if the user either accept or reject consent, the user’s preference should be stored on local storage. However, when on prod, we have the following scenarios:

- On Chrome (Android 9 and iOS 14.1): The banner shows up for GDPR-eligible users, but when you either accept, reject or dismiss the banner stays there and nothing happens.
- On Safari (iOS 14.1): The banner shows up for GDPR-eligible users, but when you either accept, reject or dismiss the banner disappears as expected. But in the particular case where you either accept or reject, the user’s decision isn’t saved into local storage as amp docs say (with a key in amp-{xxx} format where xxx is the current page domain, and a value with a base64 format that represents the user’s pref). After 2 reloads and having expressed your preference  you get the banner shown up again.

What could be happening in this case ? Is it something that could be fixed on `<amp-consent>` config ?

### Reproduction Steps

On a mobile phone navigate from any European country (can use a VPN or proxy for that) to this url: https://www.nytimes.com/2021/04/27/opinion/biden-palestine-israel-the-present.amp.html, the cookie banner will pop-up. Then click `accept` or `reject`, then monitor the local storage, it is supposed that either preference should be saved in the local storage but you'll notice that it's actually not doing it.

### Browser(s) Affected

Chrome, Safari

### AMP Version Affected

latest

**Comment by micajuine-ho** [comment]
Hi @jpolanco91 is it possible to create a test site where this behavior is present always (without having to VPN)?

**Comment by jpolanco91** [comment]
@micajuine-ho do you mean a test site in prod (this is visible to the entire world) ? If that's the case I'm not sure if we're able to do this.

**Comment by micajuine-ho** [comment]
What is the payload that `checkConsentHref ` is returning on both Chrome (Android 9 and iOS 14.1) and Safari (iOS 14.1)?

**Comment by micajuine-ho** [comment]
Additionally, are you in a viewer setting? Or on your origin?

**Comment by jpolanco91** [comment]
On Android 9 I was unable to get the payload, however in Safari (iOS 14.1) I get this:

Before expressing a preference (accept or reject):

```
{
    "consentRequired": true,
    "consentStateValue": "unknown",
    "consentString": "",
    "expireCache": false
}
```

After expressing a preference (accept):

```
{
    "consentRequired": true,
    "consentStateValue": "unknown",
    "consentString": "",
    "expireCache": false
}
```

And the consent prompt shows up again.

About the viewer setting, I didn't understood what you mean there

**Comment by micajuine-ho** [comment]
An AMP viewer is a page that can bring up multiple ampdocs, i.e. the Google AMP viewer accessible from google.com, i.e. search for a NYT article and then click on an AMP link and then the Google AMP Viewer will display the AMP doc in an iframe.

> @micajuine-ho On Android 9 and Chrome I was unable to get the payload, however in Safari (iOS 14.1) I get this:

This is the payload your are getting from on your endpoint form the  `checkConsentHref` request?

**Comment by jpolanco91** [comment]
@micajuine-ho yes this is the payload I get from our endpoint on the `checkConsentHref`

**Comment by jpolanco91** [comment]
@micajuine-ho btw I confirmed that the article that is shown in my phone (iOS) is shown on a google amp viewer.

**Comment by micajuine-ho** [comment]
I'm able to repro now, strangely it doesn't occur when I'm in incognito. Investigating futher.

**Comment by jpolanco91** [comment]
@micajuine-ho So this means that the issue where the cookie banner appears after 2 reloads (even if before the second reload the user expressed its consent/preference) it's more a Safari related issue (new features for enforcing user privacy) ? My other question is, in the case the viewer evicts the stale information (and causes the issue seen on the 2 reloads) is this only supposed to happen when the expireCache flag is true or this is a new feature from the storage API ?

**Comment by micajuine-ho** [comment]
`expireCache` is a built in mechanism to `amp-consent` for developers who don't want to cache any of the consent information. If `false` then it won't be expired by amp-consent. 

The viewer's expiration policy is separate from `amp`, and also take precedence. 

```
Before expressing a preference (accept or reject):

{
    "consentRequired": true,
    "consentStateValue": "unknown",
    "consentString": "",
    "expireCache": false
}
After expressing a preference (accept):

{
    "consentRequired": true,
    "consentStateValue": "unknown",
    "consentString": "",
    "expireCache": false
}

```
Looking into it some more, I think the problem here is that you are always returning `unknown` in your response from your `checkConsentHref`. 

Again, looking at the documentation here: https://github.com/ampproject/amphtml/blob/main/extensions/amp-consent/amp-consent.md#response
we can see that providing a `consentStateValue` or `consentString` will cause the client to cache the information. If you pass it `unknown`, that will trigger 1.) the client cache to clear itself and 2.) the prompt to show (since `consentRequired` is also true). 

In this case, I believe you're desired behavior is caching on the client and using that cached consent decision. In this case your `checkConsentHref` response should be: 
```
{
    "consentRequired": true
}
```

**Comment by micajuine-ho** [comment]
Closing now.
