### ISSUE TITLE
Allow non-HTTPS amp-list JSON

### ISSUE THREAD

**Issue by alfiehanssen** [ampproject/amphtml#3448]
The docs indicate that the JSON file that contains the "items" list must be available via HTTPS. 

For my one page personal website this isn't practical, it forces me to pay for a cert to achieve a level of security that isn't really necessary for my server / content. 

Is it possible to use HTTP instead / is this something you would consider?

**Comment by cramforce** [comment]
No. AMP only supports HTTPS. Among many other reasons, because it relies on HTTP 2.

You can get a free cert for your personal site from https://letsencrypt.org/
