### ISSUE TITLE
amp-video does not work on Internet Explorer 11 when using host relative urls

### ISSUE THREAD

**Issue by talawahdotnet** [ampproject/amphtml#3449]
HTML5 video embedded using amp-video does not play on IE 11 if the src url is host-relative (i.e. starts with a single forward slash). When you load the page with the console open you see the following error:

> source must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: /static/video/amp-phone.mp4

This is a false positive since in this case the url is relative (/static/video/amp-phone.mp4) and is being served over https.

#### Steps to reproduce

1. Visit https://www.ampproject.org/ using IE 11. The embedded video in the "Seamless, simplified publishing" section doesn't play, you just see the poster.

#### Browsers are affected

I tested IE 11, but nothing lower. MS Edge, Chrome and Firefox are **not affected**.

#### AMP version is affected

AMP ⚡ HTML – Version 1464393900473

#### Workaround

If an absolute url is used it works fine.

**Comment by dvoytenko** [comment]
This cannot be related to the video itself - something has to be off with the URL resolution on IE11. We need to look into this sooner.

**Comment by cramforce** [comment]
@lannka Could you take a look? Thanks!

**Comment by jridgewell** [comment]
Removing Fixit label then.

**Comment by lannka** [comment]
Sure, will take a look.
