### ISSUE TITLE
[Story Interactive] Use `index`property in backend response to show responses

### ISSUE THREAD

**Issue by mszylkowski** [ampproject/amphtml#34511]
### Description

If the backend responds with `[{index: 2, count: 5, selected: true}]` it will mark as selected the first option instead of the third option. When some option indices are missing, the results don't get properly matched to the options.

### Reproduction Steps

Set up a server that answers `[{index: 2, count: 5, selected: true}]`
Connect interactive component to backend
Component will highlight the first element instead of the third

### Browser(s) Affected

Chrome, Firefox, Safari

### AMP Version Affected

latest

**Comment by Brandons42** [comment]
I can work on this since it's a good first issue
