### ISSUE TITLE
AMP homepage rendering bugs on mobile

### ISSUE THREAD

**Issue by JoeArizona** [ampproject/amphtml#3451]
Hi AMP team,

I noticed some rendering glitches with the AMP homepage. I've collected three screenshots on [imgur here](http://imgur.com/a/6cbn5).

##### Highlights:

1. Title heading of the spec page is broken in Firefox.
2. The AMP logo loses its padding on the homepage, but renders with correct padding/positioning on every subsidiary page I've tested.

##### What browsers are affected?

Firefox 46 on Samsung GS7 for the title heading, all browsers so far for the logo issue. Browsers tested so far include Chrome 51, Opera 36, Opera Mini 16, Firefox 46, and Samsung's built-in browser called Internet, v 4.0.

There's explanatory text with each of the screenshots on imgur.

Cheers,

Joe

**Comment by erwinmombay** [comment]
@JoeArizona thanks, looking into this

**Comment by erwinmombay** [comment]
this should be obsolete because of the large redesign.
