### ISSUE TITLE
[amp-story] Replay button disappears after finished story is returned to

### ISSUE THREAD

**Issue by ewagstaff** [ampproject/amphtml#34527]
### Description

Expected behavior:

When a user finishes a Web Story and navigates away using a link in the bookend.json, clicking a link back to the Web Story should return them to the bookend page with a replay button.

Actual behavior:

When a user finishes a Web Story and navigates away using a link in the bookend.json, clicking a link back to the Web Story returns them to the bookend page, however the replay button is a non-functional right arrow. The user is stuck on this page.

![Screen Shot 2021-05-25 at 9 55 39 AM](https://user-images.githubusercontent.com/2423322/119537914-66c97480-bd3f-11eb-8686-6b022fb36c1c.jpg)

### Reproduction Steps

Example project: https://www.sfchronicle.com/projects/2021/visuals/floyd/

Step 1: Finish the Web Story 
Step 2: Click the link back the sfchronicle.com from the bookend
Step 3: Click the link back to the "visual essay" from the homepage

You'll see the broken replay button. It is fixed by a cache clear.

### Browser(s) Affected

Chrome, Safari

### OS(s) Affected

Windows, Mac OSX

### Device(s) Affected

Laptops, PCs

### AMP Version Affected

Latest

**Comment by ychsieh** [comment]
IIRC the bookend no longer exist in stories.
