### ISSUE TITLE
Supported Retargeting Companies?

### ISSUE THREAD

**Issue by Polylike** [ampproject/amphtml#3456]
Hey,

is there any official solution for retargeting like adroll, criteo and co.? 

Most of the companys didn't work with noscipt pixels so that amp-pixel is no solution. 

Quick and dirty: Load the script via amp-iframe on the bottom of the page?

Thanks!

**Comment by Polylike** [comment]
Hey, i have ask criteo, adroll, perfectaudience etc. The problem: The support doenst know what AMP is and everywhere the same answer: No AMP Support/ didn't know AMP.  Is there a AMP Lobby to get these companys on board? 150 Mio AMP Documents in the Index without a Retargeting Vendor? hm :'-(

**Comment by jasti** [comment]
@nicolastruchi (from Criteo). Thoughts on how Criteo plans to support retargeting?

**Comment by jasti** [comment]
@Polylike Can you explain the exact problem here? AFAIK Criteo has an amp-ad extension the re-targeting use-case should work - https://github.com/ampproject/amphtml/blob/master/ads/criteo.md. Please reach out to Criteo support about it. Thanks.

**Comment by Polylike** [comment]
The problem is the step where you can set the retargeting pixel/cookies to the user. I dont wont to place a criteo ad via amp-ad on my site.  

There a commercial landingpage for generating leads. This landingpage is in amp html only page and works fine.

The "normal" way without amp html: As a advertiser you register a account on retargeting companies like criteo. Then you have to place a Javascipt Code on your site. This code set the cookies to your site visitors, so that criteo find the users on other websites and can retargeting this users.

With AMP HTML as a advertiser i carn't place this Javascript on my site. There are no solution to place the javascript code from retargeting companies on a amp html page.  Maybe with 1x1px iframe but thats no good solution.

Looks like there is actually no way for commercial amp website to mark users with retargeting cookies?

**Comment by jasti** [comment]
@lannka what do we expect companies like Criteo/ Adroll to do in this case? A separate extension that drops cookies in advertiser landing page domains or amp-iframe does sound like a reasonable solution to me.

**Comment by jasti** [comment]
@Polylike  spoke to Criteo about this and they said they'll be able to support your use case to set cookies on advertiser AMP pages. Recommend reaching out to Criteo.

**Comment by jasti** [comment]
@nicolastruchi ping again. Specifically spoke to Mike O from Criteo about this.

**Comment by jasti** [comment]
From AMP's perspective, there is nothing stopping re-targeters to set cookies using amp-pixel on the advertiser page. Please reach out to Criteo and let us know if you have any issues.
