### ISSUE TITLE
CircleCI failed unit test reports a noisy test name

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#34580]
### Description

The failed test name looks off, like it's nested in some `describe` blocks it should not be into:

![image](https://user-images.githubusercontent.com/1492044/119845435-3fa5ab00-bed7-11eb-9712-ccc014ee1154.png)

cc @ampproject/wg-infra 

### Reproduction Steps

https://app.circleci.com/pipelines/github/ampproject/amphtml/10027/workflows/ce0ac44b-2c61-40d9-b114-5250fa1286ce/jobs/155926

**Comment by rsimha** [comment]
> The failed test name looks off, like it's nested in some `describe` blocks it should not be into:

This could be due to how `testing/describes.js` keeps track of suite / test names as it wraps and sandboxes inner `describe` blocks. Assigning to @rileyajones to see if this theory makes sense. (Happy to provide more context offline.)

**Comment by rsimha** [comment]
Another report of the same issue can be found in #34642.
