### ISSUE TITLE
🌸 Cherry-pick request for #34597 into #34565 (Complete)

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#34599]
### Issue (P0 Bug)

#34597

### Pull Request(s)

#34598

### Release Tracker(s)

#34565

### Channels

Beta / Experimental

### Justification

Time based auto advancement is broken on all Stories.

Repro steps:
- opt-in into beta from https://cdn.ampproject.org/experiments.html
- https://www.gstatic.com/amphtml/stamp/qa/navigation.html#page=page7 will not auto advance

### Verification Steps

https://www.gstatic.com/amphtml/stamp/qa/navigation.html#page=page7 will auto advance after 3 seconds

### Cherry-Pick Progress

To be updated by @ampproject/release-on-duty as each stage is completed.
- [x] Cherry-pick request created
- [x] Cherry-pick request approved
- [x] New version released to Beta / Experimental channels
- [ ] New version released to Stable channel
- [ ] New version released to LTS channel
- [x] Release tracker updated
- [x] Cherry-pick completed

### Notifications

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by kristoferbaxter** [comment]
Approved. Thanks for adding in testing.
