### ISSUE TITLE
🌸 Cherry-pick request for #34595 into #34565 (Complete)

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#34596]
### Issue (P0 Bug)

#34595

### Pull Request(s)

#34593

### Release Tracker(s)

#34565

### Channels

Beta / Experimental

### Justification

Ads created with google web designer using animation will not animate, leading to broken appearance. 

### Verification Steps

https://output.jsbin.com/jabosaxusa should render ad like this
![image](https://user-images.githubusercontent.com/16087874/119890201-65897a80-beec-11eb-9f75-fcda392c18f2.png)

### Summary

Google side integration tests for amphtml ads were incorrectly using the inabox version number, so this was only caught after inabox promote. They ideally should use nightly, or at the least amp prod.

### Action Items

Move these tests to use nightly so we catch this regression the next day.

### Cherry-Pick Progress

To be updated by @ampproject/release-on-duty as each stage is completed.
- [x] Cherry-pick request created
- [x] Cherry-pick request approved
- [x] New version released to Beta / Experimental channels
- [ ] New version released to Stable channel
- [ ] New version released to LTS channel
- [x] Release tracker updated
- [x] Cherry-pick completed

### Notifications

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by kristoferbaxter** [comment]
Approved.
