### ISSUE TITLE
[Validator] Template attribute values in `data-*` attributes not validated

### ISSUE THREAD

**Issue by sidkshatriya** [ampproject/amphtml#3460]
The following template attribute values correctly generate validation errors:

```html
<template type="amp-mustache">
  <!-- validation error: UNESCAPED_TEMPLATE_IN_ATTR_VALUE -->
  <div class="{{{ hello }}}"></div>
  <!-- validation error: TEMPLATE_PARTIAL_IN_ATTR_VALUE -->
  <p class="{{ >testing }}}"></p>
</template>
```

These errors are triggered by the `validateAttrValueBelowTemplateTag()`

Interestingly, the following _will not_ trigger any validation error:
```html
<template type="amp-mustache">
  <!-- no validation error -->
  <div data-message="{{{ hello }}}"></div>
  <!-- no validation error -->
  <p data-message="{{ >testing }}}"></p>
</template>
```

This is because all `data-*` attribute values are not validated at all. (`data-*` attribute _names_ are validated though). (see `validateAttrNotFoundInSpec()`)

Is this behaviour correct? Should we not check `data-*` values also whether they have a correct value if they are underneath template tags?

This seems to contradict the comment "We disallow these in attribute values" (see below)

```javascript
static valueHasUnescapedTemplateSyntax(value) {
    // Mustache (https://mustache.github.io/mustache.5.html), our template
    // system, supports {{{unescaped}}} or {{{&unescaped}}} and there can
    // be whitespace after the 2nd '{'. We disallow these in attribute Values.
    const unescapedOpenTag = new RegExp('{{\\s*[&{]');
    return unescapedOpenTag.test(value);
  }
```

Another contradiction: "We disallow partials in attribute values" as partials are allowed in `data-*` (see below)

```javascript 
static valueHasPartialsTemplateSyntax(value) {
    // Mustache (https://mustache.github.io/mustache.5.html), our template
    // system, supports 'partials' which include other Mustache templates
    // in the format of {{>partial}} and there can be whitespace after the {{.
    // We disallow partials in attribute values.
    const partialsTag = new RegExp('{{\\s*>');
    return partialsTag.test(value);
  }

**Comment by dvoytenko** [comment]
/to @Gregable 

I'd indeed expect the same partial/unescaping rules to apply to data attributes as well.

That being said, the validation of templates is mainly aimed to "inform" of potential pitfalls when using templates. The results of template execution are still pushed via HTML sanitizer as well.

**Comment by Gregable** [comment]
This is a legitimate bug, the data-* attributes take a slightly different code path through the validator due to being 'wildcard' attribute names, and aren't getting run through the template validation.

As Dima said though, our primary goal in validation is to make sure that the pre-mustache-rendered document doesn't break amp validation rules. The post-mustache-rendered doc will be validated separately (currently via a runtime sanitizer) and also needs to be valid amp. The unescaped/partials logic is there to provide developer hints.

**Comment by ericlindley-g** [comment]
@Gregable   Slotting in backlog, but feel free to correct/update the milestone as needed

**Comment by Gregable** [comment]
Resolved. This will be deployed to cdn.ampproject.org next week.
