### ISSUE TITLE
`amp-date-display` v1.0 (Bento) is shown as default version on amp.dev, but `latestVersion` in `bundles.config.extensions.json` is still 0.1

### ISSUE THREAD

**Issue by westonruter** [ampproject/amphtml#34600]
### Description

On the docs page for `amp-date-display` at  https://amp.dev/documentation/components/amp-date-display/ the Bento version is shown as the default (stable) version:

![image](https://user-images.githubusercontent.com/134745/119897044-ba30f380-bef4-11eb-9f5c-d5d7542f5d51.png)

Nevertheless, the `latestVersion` is still `0.1`:

https://github.com/ampproject/amphtml/blob/5f85683a58fbad62272d8ac78e819de256a7feca/build-system/compile/bundles.config.extensions.json#L160-L172

https://cdn.ampproject.org/v0/amp-date-display-latest.js === https://cdn.ampproject.org/v0/amp-date-display-0.1.js
https://cdn.ampproject.org/v0/amp-date-display-latest.js !== https://cdn.ampproject.org/v0/amp-date-display-1.0.js

Is amp.dev wrong to use the Bento version as default/stable? Or does the `latestVersion` need to be updated to 1.0 as well?

cc @ampproject/wg-components 

### Reproduction Steps

Compare version shown on https://amp.dev/documentation/components/amp-date-display/ vs version shown at https://github.com/ampproject/amphtml/blob/5f85683a58fbad62272d8ac78e819de256a7feca/build-system/compile/bundles.config.extensions.json#L160-L172

**Comment by caroqliu** [comment]
The `latestVersion` for `amp-date-display` **should be 0.1** given that `amp-date-display:1.0` is not yet launched (and still in experimental mode). 

Regardless of which version is displayed by default on amp.dev, the `1.0` version of `amp-date-display` should have the experimental label on it. Would that clear things up in the documentation? Or does "default" imply "stable" in all cases?

**Comment by westonruter** [comment]
I think default implies stable. That's the way it has been historically for other components as I recall. Maybe the Bento version is being shown as the default because it lacks `experimental` being `true` in this file: https://amp.dev/static/bento-components.json

**Comment by caroqliu** [comment]
cc/ @sebastianbenz @CrystalOnScript
