### ISSUE TITLE
Bento: components fail to hide `placeholder` content once loaded

### ISSUE THREAD

**Issue by westonruter** [ampproject/amphtml#34616]
### Description

When using `amp-twitter` 1.0 (Bento) with `placeholder` content as follows:

```html
<amp-twitter width="600" height="480" layout="responsive" data-tweetid="1397995435386679302" class="twitter-tweet" data-width="550" data-dnt="true">
  <blockquote class="twitter-tweet" data-width="550" data-dnt="true" placeholder="">
    <p lang="en" dir="ltr">
      ⛺🔥
      Fun fact: cAMPfire stories are the best stories.<br>
      <a href="https://twitter.com/CrystalOnScript?ref_src=twsrc%5Etfw">@CrystalOnScript</a>,
      <a href="https://twitter.com/nainar92?ref_src=twsrc%5Etfw">@nainar92</a>, and Caroline Liu gather around to
      unbox the Bento developer preview, which allows you to use AMP ⚡
      components everywhere!<br> <br>
      📺
      Tune in → <a href="https://t.co/RViEFP4AR9">https://t.co/RViEFP4AR9</a> <a href="https://t.co/Ni8B5VNZVz">pic.twitter.com/Ni8B5VNZVz</a>
    </p>
    — AMP Project (@AMPhtml) <a href="https://twitter.com/AMPhtml/status/1397995435386679302?ref_src=twsrc%5Etfw">May
    27, 2021</a>
  </blockquote>
</amp-twitter>
```

The placeholder content fails to be hidden when the component initializes, causing overlapping text:

![image](https://user-images.githubusercontent.com/134745/120093755-249e8b00-c0d1-11eb-80ac-d8cb575de85e.png)

See [example on playground](https://playground.amp.dev/#share=PCFET0NUWVBFIGh0bWw+CjxodG1sIGFtcCBkYXRhLWFtcGRldm1vZGU+CiAgPGhlYWQ+CiAgICA8bWV0YSBjaGFyc2V0PSJ1dGYtOCIgLz4KICAgIDx0aXRsZT5NeSBBTVAgUGFnZTwvdGl0bGU+CiAgICA8bGluayByZWw9ImNhbm9uaWNhbCIgaHJlZj0ic2VsZi5odG1sIiAvPgogICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCIgLz4KICAgIDxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoOy1tb3otYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1zLWFuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RoO2FuaW1hdGlvbjotYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsZW5kKSAwcyAxIG5vcm1hbCBib3RofUAtd2Via2l0LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1vei1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1tcy1rZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19QC1vLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1Aa2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fTwvc3R5bGU+PG5vc2NyaXB0PjxzdHlsZSBhbXAtYm9pbGVycGxhdGU+Ym9keXstd2Via2l0LWFuaW1hdGlvbjpub25lOy1tb3otYW5pbWF0aW9uOm5vbmU7LW1zLWFuaW1hdGlvbjpub25lO2FuaW1hdGlvbjpub25lfTwvc3R5bGU+PC9ub3NjcmlwdD4KICAgIDxzY3JpcHQgYXN5bmMgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC5qcyI+PC9zY3JpcHQ+CiAgICA8c2NyaXB0IGFzeW5jIGN1c3RvbS1lbGVtZW50PSJhbXAtdHdpdHRlciIgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC9hbXAtdHdpdHRlci0xLjAuanMiIGRhdGEtYW1wZGV2bW9kZT48L3NjcmlwdD4KCTxsaW5rIHJlbD0ic3R5bGVzaGVldCIgaHJlZj0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAvYW1wLWZpdC10ZXh0LTEuMC5jc3MiIGRhdGEtYW1wZGV2bW9kZT4KICAgIDxzY3JpcHQgZGF0YS1hbXBkZXZtb2RlPgogICAgICAoc2VsZi5BTVAgPSBzZWxmLkFNUCB8fCBbXSkucHVzaChmdW5jdGlvbiAoQU1QKSB7CiAgICAgICAgQU1QLnRvZ2dsZUV4cGVyaW1lbnQoJ2JlbnRvJywgdHJ1ZSk7CiAgICAgIH0pOwogICAgPC9zY3JpcHQ+CiAgPC9oZWFkPgogIDxib2R5PgogICAgPGFtcC10d2l0dGVyIHdpZHRoPSI2MDAiIGhlaWdodD0iNDgwIiBsYXlvdXQ9InJlc3BvbnNpdmUiIGRhdGEtdHdlZXRpZD0iMTM5Nzk5NTQzNTM4NjY3OTMwMiIgY2xhc3M9InR3aXR0ZXItdHdlZXQiIGRhdGEtd2lkdGg9IjU1MCIgZGF0YS1kbnQ9InRydWUiPgogICAgICA8YmxvY2txdW90ZSBwbGFjZWhvbGRlcj0iIiBjbGFzcz0idHdpdHRlci10d2VldCIgZGF0YS13aWR0aD0iNTUwIiBkYXRhLWRudD0idHJ1ZSI+CiAgICAgICAgPHAgbGFuZz0iZW4iIGRpcj0ibHRyIj4KICAgICAgICAgIOKbuvCflKUKICAgICAgICAgIEZ1biBmYWN0OiBjQU1QZmlyZSBzdG9yaWVzIGFyZSB0aGUgYmVzdCBzdG9yaWVzLjxicj4KICAgICAgICAgIDxhIGhyZWY9Imh0dHBzOi8vdHdpdHRlci5jb20vQ3J5c3RhbE9uU2NyaXB0P3JlZl9zcmM9dHdzcmMlNUV0ZnciPkBDcnlzdGFsT25TY3JpcHQ8L2E+LAogICAgICAgICAgPGEgaHJlZj0iaHR0cHM6Ly90d2l0dGVyLmNvbS9uYWluYXI5Mj9yZWZfc3JjPXR3c3JjJTVFdGZ3Ij5AbmFpbmFyOTI8L2E+LCBhbmQgQ2Fyb2xpbmUgTGl1IGdhdGhlciBhcm91bmQgdG8KICAgICAgICAgIHVuYm94IHRoZSBCZW50byBkZXZlbG9wZXIgcHJldmlldywgd2hpY2ggYWxsb3dzIHlvdSB0byB1c2UgQU1QIOKaoQogICAgICAgICAgY29tcG9uZW50cyBldmVyeXdoZXJlITxicj4gPGJyPgogICAgICAgICAg8J+TugogICAgICAgICAgVHVuZSBpbiDihpIgPGEgaHJlZj0iaHR0cHM6Ly90LmNvL1JWaUVGUDRBUjkiPmh0dHBzOi8vdC5jby9SVmlFRlA0QVI5PC9hPiA8YSBocmVmPSJodHRwczovL3QuY28vTmk4QjVWTlpWeiI+cGljLnR3aXR0ZXIuY29tL05pOEI1Vk5aVno8L2E+CiAgICAgICAgPC9wPgogICAgICAgIOKAlCBBTVAgUHJvamVjdCAoQEFNUGh0bWwpIDxhIGhyZWY9Imh0dHBzOi8vdHdpdHRlci5jb20vQU1QaHRtbC9zdGF0dXMvMTM5Nzk5NTQzNTM4NjY3OTMwMj9yZWZfc3JjPXR3c3JjJTVFdGZ3Ij5NYXkKICAgICAgICAyNywgMjAyMTwvYT4KICAgICAgPC9ibG9ja3F1b3RlPgogICAgPC9hbXAtdHdpdHRlcj4KICA8L2JvZHk+CjwvaHRtbD4K).

### Reproduction Steps

Add `amp-twitter` 1.0 with `placeholder` content.

### AMP Version Affected

2105150310000

**Comment by samouri** [comment]
@kvchari: now that https://github.com/ampproject/amphtml/pull/35821 has merged, can this be closed?

**Comment by kvchari** [comment]
@samouri yes this should be closed. Going forward, all bento components with dynamic content will need to invoke the callbacks provided in BaseElement (`onLoading`/`onLoad`/`onError`) to ensure each component supports placeholders properly
