### ISSUE TITLE
Unsecured code found in plugin

### ISSUE THREAD

**Issue by pandeytom** [ampproject/amphtml#34615]
### Description

When I login to my wordpress site on mobile is shown an error, where as when I open it on desktop or laptop its working fine.
error shown on mobile is "Your submission failed. The server responded with (code ). Please contact the developer of this form processor to improve this message. Learn More"

### Reproduction Steps

1. open on mobile https://citysuperfast.com
2. click on menu 
3. then login
4. write user name and password for my site 
5. shown 
6. Your submission failed. The server responded with (code ). Please contact the developer of this form processor to improve this message. Learn More

### Relevant Logs

```shell
https://privatebin.support-tools.com/?ae37366080c5825f#6+qr7DBpDIWYYJX9beE3v4fu7KDdbYEdBf2eV16eUEM=
```

**Comment by kristoferbaxter** [comment]
@westonruter should we auto transfer issues like this to the AMP Wordpress Plugin?

**Comment by westonruter** [comment]
Yes, although this will be resolved by https://github.com/ampproject/amp-wp/issues/4191.

**Comment by westonruter** [comment]
It's not an issue with unsecured code. The issue is the endpoint is not sending back JSON nor an an `AMP-Redirect-To` response header. The form submission proxy in the plugin will make sure one or the other is sent back.

**Comment by westonruter** [comment]
@pandeytom actually, the error message which appears when the form is submitted has a Learn More link:

![image](https://user-images.githubusercontent.com/134745/120433172-c3c0be00-c32f-11eb-96e4-b79bfa7e62d3.png)

This is pointing to https://amp-wp.org/documentation/playbooks/handling-form-submissions/

When looking at the network log, I can see the server is responding with a 406 status code. This indicates likely that you have ModSecurity blocking requests that have the `__amp_source_origin` query parameter set. For example, you can see the 406 response by going to https://citysuperfast.com/?__amp_source_origin=https%3A%2F%2Fcitysuperfast.com

We have more documentation on this ModSecurity issue at https://amp-wp.org/documentation/playbooks/handling-form-submissions/#dealing-with-modsecurity-failures

You'll have to reach out to your host's support to remove the `__amp_source_origin` query parameter from the denylist.

**Comment by pandeytom** [comment]
How to solve it... And if possible please send update...

**Comment by pandeytom** [comment]
How to solve it... And if possible please send update...

**Comment by westonruter** [comment]
> How to solve it... And if possible please send update...

As I said above, please see https://amp-wp.org/documentation/playbooks/handling-form-submissions/#dealing-with-modsecurity-failures

You have to contact your host.

**Comment by pandeytom** [comment]
I am not developer, it will be more helpful for me to give update, after
running update on site problem solve .

**Comment by westonruter** [comment]
Sorry, we cannot help you further. Your host host to make the required change to not block requests with the `__amp_source_origin` query parameter. Please reach out to your website hosting company's support.
