### ISSUE TITLE
Allow visibility-states test to work with compiled JS

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#3461]
This is currently deactivated
https://github.com/ampproject/amphtml/blob/master/test/integration/test-visibility-states.js#L32

because the test stubs out private properties of production code which no longer works, due to #3223.

**Comment by ericlindley-g** [comment]
@jridgewell   Slotting in backlog, but feel free to correct/update the milestone as needed

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
