### ISSUE TITLE
Tracking Core Web Vitals in AMP using Google Analytics doesn't work

### ISSUE THREAD

**Issue by scaledrop** [ampproject/amphtml#34623]
### Description

I added web vitals tracking in code but since then page-views tracking stopped working. 
Created a test page, please let me know where the issue is.

https://m.economictimes.com/amp_test.cms **(PV tracking working)**
https://m.economictimes.com/amp_test.cms?web_vital=1 **(PV tracking not working)**

The only difference in the second url is, extraUrlParams has been added to track core web vitals tracking along with page views body as suggested by [amp.dev](https://amp.dev/documentation/examples/advertising-analytics/tracking_core_web_vitals/?format=websites)

```
"extraUrlParams": {
    "lcp": "${largestContentfulPaint}",
    "cls": "${cumulativeLayoutShift}",
    "fid": "${firstInputDelay}"
 }
```

### Reproduction Steps

Please check network log of analytics for the given [url](https://m.economictimes.com/amp_test.cms?web_vital=1). Page views are not getting logged.

### Browser(s) Affected

Chrome

### OS(s) Affected

Android 11

### AMP Version Affected

012105150310000

**Comment by abhiz10** [comment]
@scaledrop Hi... 
When you hit this URL
>https://m.economictimes.com/amp_test.cms?web_vital=1

**Reproduction Steps**
If you go to another tab and then come back to your original tab analytics data is present in Dev Tool> Network
v=1&_v=a1&ds=AMP&aip&_s=1&dt=%7B%7Btitle%7D%7D&sr=320x568&_utmht=1622481493821&cid=amp-QHLBUAD9Q3EAOfz7PnLBYw&tid=&dl=https%3A%2F%2Fm.economictimes.com%2Famp_test.cms%3Fweb_vital%3D1&dr=&sd=24&ul=en-us&de=UTF-8&t=pageview&jid=0.0021677142480029943&_r=1&a=7210&z=0.9754394625957776&lcp=88.800048828125&cls=0&fid=4

https://amp.dev/documentation/components/amp-analytics/#vars
>Variables are resolved asynchronously and can delay the request until they are fulfilled. For example, some metrics such as Cumulative Layout Shift and Largest Contentful Paint are calculated after the page is hidden. For First Input Delay, it is resolved after the user interacts with the page. For this reason these metrics might not be suitable for use with all triggers (for example, on timer or visible).

**Comment by micajuine-ho** [comment]
Hi, I would recommend splitting up these CWV tracking into separate requests, i.e. create a new request for each CWV. This is because FID is only tracked once user input has been detected, so it can stall the whole request being sent.

**Comment by scaledrop** [comment]
@micajuine-ho Tried to do that, still getting fired after user switches tab. Let me know the issue in the following snippet.
```
{
  "vars": {
      "gtag_id": "GA-ID",
      "config": {
        "GA-ID": {
          "groups": "default"
        }
      }
  },
  "triggers": {
    "default pageview": {
      "on": "visible",
      "request": "pageview",
      "vars": {
        "title": "{{title}}"
      }
      
      ,
      "extraUrlParams": {
        "lcp": "${largestContentfulPaint}"
      }
    },
    "trackWebVital" : {
    "on": "visible",
    "selector": "#myele",
    "request": "event",
    "vars": {
      "eventCategory": "webVitalTracking",
          "eventAction": "visible",
          "eventLabel": ""
    },
    "extraUrlParams": {
        "lcp": "${largestContentfulPaint}",
        "cls": "${cumulativeLayoutShift}",
        "fid": "${firstInputDelay}"
      }
  }
  }
}
```

**Comment by micajuine-ho** [comment]
in this example, you've only moved out LCP to a different trigger. Since `${firstInputDelay}` is still in the `extraUrlParams` for the second trigger, the request will wait to be sent until the FID score is calculated. 

From https://web.dev/fid/:
```
FID measures the time from when a user first interacts with a page (i.e. when they click a link, tap on a button, or use a custom, JavaScript-powered control) to the time when the browser is actually able to begin processing event handlers in response to that interaction.
```

therefore there has to be user interaction for a FID score to be calculated (and thus the request to be sent).

**Comment by scaledrop** [comment]
@micajuine-ho I added another use case where we are sending the ga event on user action "Click" still there is no event getting triggered on click, but when we switch back to tab there are as many many events getting triggered as number of clicks on button "My Element 2"
Please check the [updated url](https://m.economictimes.com/amp_test.cms?web_vital=2).
Can you please share a change in snippet which you're referring?

**Comment by micajuine-ho** [comment]
```
{
  "vars": {
      "gtag_id": "GA-ID",
      "config": {
        "GA-ID": {
          "groups": "default"
        }
      }
  },
  "triggers": {
    "default pageview": {
      "on": "visible",
      "request": "pageview",
      "vars": {
        "title": "{{title}}"
      }
      
      ,
      "extraUrlParams": {
        "lcp": "${largestContentfulPaint}"
      }
    },
  "default pageviewFID": {
      "on": "visible",
      "request": "pageview",
      "extraUrlParams": {
        "fid": "${firstInputDelay}"
      }
    },
    "trackWebVitalWithoutFID" : {
    "on": "visible",
    "selector": "#myele",
    "request": "event",
    "vars": {
      "eventCategory": "webVitalTracking",
          "eventAction": "visible",
          "eventLabel": ""
    },
    "extraUrlParams": {
        "lcp": "${largestContentfulPaint}",
        "cls": "${cumulativeLayoutShift}"
      }
  }
  }
}
```

**Comment by amitinsan** [comment]
@micajuine-ho Thanks for the update.
But with the above code snippet, the issue is same. 
PV event gets initiated after user interaction and seconds event goes only in case of user tab switch back to the current page.
[Sample Link](https://m.economictimes.com/amp_test.cms?web_vital=4)

**Comment by micajuine-ho** [comment]
This is due to the CLS metric being calculated by `The aggregate layout shift score when the user leaves the page (navigation, tab switching, dismissing application) for the first time`.

https://wicg.github.io/layout-instability/#cumulative-layout-shift

Again, I recommend splitting out the CLS metric into it's one trigger if you don't want the current trigger to be bottlenecked by it.
