### ISSUE TITLE
[amp-story] reset amp-anim/gif when we go back to a page.

### ISSUE THREAD

**Issue by goonydev** [ampproject/amphtml#34626]
### Description

When we have an animated gif in a web story using the amp-anim tag, it would be nice if the gif could reset everytime we go back to the page. The web story waits for us to reach the page to start playing the gif, which is nice, but when we leave the page, and go back to that page, we are:

- stuck with a still image if the gif is meant to play once.
- not seeing the gif anymore, if it is meant to play once with an empty last frame
- seeing the gif playing from a random timestamp of it's loop, if the gif is meant to loop.

With gifs, the timing is often important, and so is the consistency of the page. I think it would be very helpful if we could play gifs from the start of their animation every time we view the page. I have so many cool ideas with animated gifs but I can't figure a proper way to implement them.

### Alternatives Considered

I believe you could use an alternative "data-src" attribute, and only fill the proper "src" when the page is active. This way we guarantee the gif won't be running in the background and also that it will start over every time we show the page.

I noticed that if I reach the last page of my web story, then go back to the page with the gif, it does reset, so there might be something happening there that could be reproduced when we leave the page with the gif, instead of reaching the last page.

**Comment by newmuis** [comment]
This will have substantial performance implications.

Could you instead [replace the gif with a video](https://web.dev/replace-gifs-with-videos/)?  They're way better.

**Comment by processprocess** [comment]
Just for reference, stories that use `amp-anim` will not pass validation.  `amp-img` can be used for gifs but the limitations are the same. 
+1 to @newmuis comment about using video if playback control is desired.

**Comment by goonydev** [comment]
I use videos as much as possible. Can't have the transparent background on a video though. So I know you are going to tell me I should put my elements together first and make a video out of it. But that's a lot of work. I understand gifs are heavy and lame. I guess I'll just forget about it.

**Comment by processprocess** [comment]
Gifs are cool! They're typically heavier than video and do have playback limitations which makes them not ideal sometimes.
Putting all content in a video is bad for SEO. We don't recommend doing that!

We're doing our best to build a format that can be used in lots of different ways and cover as many use-cases as possible while being lean and fast. 
We appreciate your suggestions a lot @goonydev!

**Comment by goonydev** [comment]
Let me give you an example of what I was trying to do:

The page of the story was referring to a confusing situation. So, I have my background picture as well as my text illustrating this. But as a little extra I wanted to try having John Travolta walking in the frame, looking around, like in Pulp Fiction (you know, that famous meme).

I still don't know Google's position on popular memes usage, but you get the broad idea of the kind of things we could do. Now for more playback control, I could indeed try to make a video out of this. I would have to play my web story on my computer while recording my screen, and without the text (important). Then I would have to edit the video correctly. Now instead of a jpg+gif combo I would use a mp4 as the background, and still be able to use a separate text on my page. 

Advantages of the video version:

- it validates
- it uses smaller files
- it resets when we enter the page
- good responsiveness, which is a nightmare to deal with using gifs


Disadvantages of the video version:

- more work
- no more image to present for indexation (if that even matters)
- might have cropping issues on some devices, as I use desktop-fullbleed

I am developing tools in our CMS backend to allow our staff to create web stories easily. The video conversion is too much and would require them to figure out too much stuff outside of the CMS, while just adding a gif to the page would allow me to figure things out programmatically. I don't even know if our staff would ever need this, but I wanted to make it possible.
