### ISSUE TITLE
Intent to Implement: Modifications to adtech amp-ad code

### ISSUE THREAD

**Issue by lisamayo** [ampproject/amphtml#3462]
AOL will make a pull request for review; we need to modify the existing adtech ad type to include support for additional parameters which were not part of the inital setup that was not done by us.  

The modified code will not alter what is there already and that will continue to work, however, we need to allow publishers to use our internal ad call methodology and also include optional variables for tracking and targeting purposes.

My fork can be found here (will be updating with the latest amphtml code shortly): https://github.com/aol/amphtml

**Comment by cramforce** [comment]
SGTM

**Comment by adelinamart** [comment]
Seems PR was merged. Closing it, but if there's still work to do, feel free to re-open. Thanks.
