### ISSUE TITLE
[Story tooltip] Pointer events don't get triggered if upper grid-layer covers page

### ISSUE THREAD

**Issue by mszylkowski** [ampproject/amphtml#34632]
### Description

Introduced in #18945 there is a CSS rule that should allow clicking on a grid-layer that's not first in the stack of layers on a page. However, if the foreground layer has anything (eg: a `div`) covering the whole page, then it will block the clicks, even if that element should not be clickable. The properties have `!important` so they cannot be overriden by publishers.

```css
amp-story-grid-layer {
  pointer-events: none !important;
}
amp-story-grid-layer * {
  pointer-events: auto !important;
}
```

```html
<amp-story-grid-layer>
  <div class="full-page center-div">
    <a href="https://clickonbackgroundlayer.com"><p>Cannot be clicked</p></a>
  </div>
</amp-story-grid-layer>
<amp-story-grid-layer layout="fill">
  <div style="width:100%;height:100%;position:absolute;left:0;top:0">
    <a href="https://clickonforegroundlayer.com"><p>Can be clicked</p></a>
  </div>
</amp-story-grid-layer>
```

### Potential fixes

- **[Preferred]** We can set `pointer-events: auto` to only the elements that are interactive (tooltips, amp-twitter, amp-story-interactive). This will involve removing the rule `amp-story-gid-layer * {pointer-events: auto !important}` but adding `pointer-events: auto` on the elements that are supposed to be clickable.
- We can make the CSS rule not `!important` so it can be overriden

**Comment by newmuis** [comment]
FWIW, it should also be possible to work around this by not wrapping the elements in `div` tags, but rather directly having the `a` tags as children of the `amp-story-grid-layer`.

It would be quite difficult (impossible?) for us to tell what stories will break if we remove the `!important` from `amp-story-grid-layer * { pointer-events: auto !important }`.  I don't think we should need to remove the `!important` from `amp-story-grid-layer { pointer-events: none !important }`.

**Comment by mszylkowski** [comment]
> FWIW, it should also be possible to work around this by not wrapping the elements in `div` tags, but rather directly having the `a` tags as children of the `amp-story-grid-layer`.

Given how most of the storymaking tools use a lot of divs to surround the elements (for positioning / creating layouts), I don't think that asking them to remove all the divs is a feasible solution in the short term. Also, the problem is not with the `a` tags themselves but with all the layers that could go on top of them. Removing the divs would mean that it could be impossible to create any layout with a surrounding div (for instance to center elements on a page), with the fear that it could obstruct an `a` tag on a layer beneath, so this doesn't sound like a good solution.

> I don't actually think this will fix the problem, unless you mean we also add a selector like `* { pointer-events: none !important }`, then override it for the specific set of interactive elements you mention above. The problem here is the div, not the amp-story-grid-layer.

100%, something like that would be required to make only the interactive elements clickable. This seems to me the best solution. However, we don't need the `* { pointer-events: none !important }` rule, removing the `amp-story-grid-layer * { pointer-events: auto !important }` rule will work if we override the `pointer-events` for the clickable elements.

> It would be quite difficult (impossible?) for us to tell what stories will break if we remove the !important from `amp-story-grid-layer * { pointer-events: auto !important }`. I don't think we should need to remove the `!important` from `amp-story-grid-layer { pointer-events: none !important }`.

My guess is that this should not break stories since the attribute doesn't affect the layout, just affects the click handling logic. However, it's a valid concern and we could test it. My vote is still towards only enabling clicks on clickable elements and not setting `pointer-events: auto` on all elements of a page.

**Comment by newmuis** [comment]
> 100%, something like that would be required to make only the interactive elements clickable. This seems to me the best solution. However, we don't need the `* { pointer-events: none !important }` rule, removing the `amp-story-grid-layer * { pointer-events: auto !important }` rule will work if we override the `pointer-events` for the clickable elements.

Agree it's the most promising solution so far, but I still am not certain this would work without additional considerations.  Assume you added the following to the example you provided in the initial report:

```css
.center-div a {
  pointer-events: auto !important
}
```

This anchor will still not be clickable if obscured by the `div` in the foreground layer, as that `div` will _also_ have `pointer-events: auto`, due to this rule:

```css
amp-story-grid-layer * {
  pointer-events: auto !important;
}
```

**Comment by mszylkowski** [comment]
There are 2 problems that we'd need to solve. One of them is that any div/element currently blocks the clicks to elements behind (which is solved by removing the snippet you referenced `amp-story-grid-layer * {pointer-events: auto !important;}`) and the other problem is that we need to set `pointer-events: auto/all` on elements that should be clickable (because removing the rule we're mentioning will also make all items not clickable).

That's what I meant by "removing the amp-story-grid-layer * { pointer-events: auto !important } rule will work if we override the pointer-events for the clickable elements.". For that solution to work, we need to disable click on all items, but re-enable click on the items that are clickable. I can update the issue description to explain this better

**Comment by newmuis** [comment]
+1.

But, I don't think that it's sufficient to remove this block...

```css
amp-story-grid-layer * {
  pointer-events: auto !important;
}
```

...since the [initial value is `auto`](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events).  So, most cases (including this `div`), will need to be explicitly set not to receive pointer events (e.g. `* { pointer-events: none }`).

**Comment by mszylkowski** [comment]
That is set on `amp-story-grid-layer {pointer-events: none !important}`, I can check if that attribute is not propagated

**Comment by edoudou** [comment]
Any news on this subject ?

What are the next steps ?

**Comment by gmajoulet** [comment]
@edoudou can you clarify why this is a Story specific problem, over a web platform problem? Can you provide examples of things you absolutely cannot achieve in Stories because of it? Code samples would be highly appreciated.

**Comment by edoudou** [comment]
@gmajoulet Here is an exemple of a story where this is causing troubles : https://join-dev.my.join-stories.com/test-oy0Btw2Mn/?t=703
As you can see, you can't click on the start because of the pointer event on the div in the Layer above.

We are using div's as main child in the layer to help use place Items (even if it might not be that usefull in this case), but it is a downer that we can't prevent click on this div as, as you can see, it prevent for clicking on elements of other layers.

**Comment by mszylkowski** [comment]
I'll also add that this affects any type of tappable component (quizzes, polls, amp-twitter, tooltips, etc).

So this could fail if you have a story with a centered component and an anchored component, independently of the order:

```html
<amp-story-page>
 <!-- Link below quiz, link will not be tappable -->
  <amp-story-grid-layer layout="fill" preset="2021-foreground" anchor="top">
    <div class="align-top">
      <a href="...">Link to our instagram account</a>
    </div>
  <amp-story-grid-layer>
  <amp-story-grid-layer layout="fill" preset="2021-foreground">
    <div class="center">
      <amp-story-interactive-quiz ...></amp-story-interactive-quiz
    </div>
  <amp-story-grid-layer>
</amp-story-page>
```

or 

```html
<amp-story-page>
 <!-- Quiz below link, quiz will not be tappable -->
  <amp-story-grid-layer layout="fill" preset="2021-foreground">
    <div class="center">
      <amp-story-interactive-quiz ...></amp-story-interactive-quiz
    </div>
  <amp-story-grid-layer>
  <amp-story-grid-layer layout="fill" preset="2021-foreground" anchor="top">
    <div class="align-top">
      <a href="...">Link to our instagram account</a>
    </div>
  <amp-story-grid-layer>
</amp-story-page>
```
both fail.

**Comment by gmajoulet** [comment]
Can you double check your example @edoudou plz? I don't have any problem clicking the button on the one you sent

**Comment by edoudou** [comment]
Sorry forgot to explain the case. The start has a tooltip on, but the layer of the button prevent us to click on it

**Comment by edoudou** [comment]
Hi @gmajoulet ,

Is my example more coherent to you knowing that the star should have a tooltip ?

We are waiting to see how this issue is elvolving in order to fix some bug on our side.

**Comment by gmajoulet** [comment]
Why do you need this extra `div` layer that's just height/width: 100%? You should be able to position items within the `-grid-layer`, right?

**Comment by edoudou** [comment]
Because whatever template attribute I am using on the grid layer, I can't manage to position my items as their position are overwritten :
With template="fill" : https://join-dev.my.join-stories.com/story-amp-do-delete-xjDjbvE/?t=353
With template="vertical" : https://join-dev.my.join-stories.com/amp-do-not-delete-2-69I0rmg/?t=966

Or maybe their is just another kind of template not documented ?

**Comment by gmajoulet** [comment]
There isn't, but shipping a new template that lets you do anything you want is much much easier and safer than making changes to pointer-events. Would that work for you?

**Comment by edoudou** [comment]
I need to check if this solution is ok for us, but I don't see any evident reason why not.

I'll try to get back to you with an answer before the end of the day.

**Comment by edoudou** [comment]
Sorry for the tardiness of my response.

I don't think it is acceptable, as we are using divs to position other elements, so those divs will still be in the way :
For example, in this story, we use a div to make sure our border is always inside the screen, but never overflows outside the bleedzone : https://join-test.my.join-stories.com/bug-amp-do-not-change-OauFxLz/?t=072

What would be the other options to considere ?

**Comment by edoudou** [comment]
Hi guys,

Any more ideas to consider so we can move on on this issue ?

**Comment by mszylkowski** [comment]
> There isn't, but shipping a new template that lets you do anything you want is much much easier and safer than making changes to pointer-events. Would that work for you?

I'd recommend if necessary to not add an entire new template but just an opt-out from the rule `pointer-events: auto !important` by doing sth like `amp-story-grid-layer[non-clickable]` (instead of `amp-story-grid-layer[template="non-clickable"]`). This way, creation tools can override the CSS styles with their preferred `pointer-events` value.

**Comment by edoudou** [comment]
That would be a solution we can work with !

**Comment by gmajoulet** [comment]
I think a new template vs the attribute you're describing would be roughly equivalent as they're just CSS anyway. I'd rather have the new template so it doesn't cover the entire screen, vs expecting creation tools to get the `pointer-events` rules exactly right (difficult).

**Comment by mszylkowski** [comment]
I'm working on a solution to automatically set the correct pointer-events to the correct values, given the small number of valid elements that are clickable in a grid-layer (they are: interactive components, links, shopping tags, amp-twitter).
