### ISSUE TITLE
amp-sticky-ad (experimental) sometimes does not show

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#3464]
## Short description of your issue:

I was trying to create an example for amp-sticky-ad [here](https://amptest-fed77.firebaseapp.com/.) I enabled the example in [here](https://cdn.ampproject.org/experiments.html) and I run AMP.toggleExperiment('amp-sticky-ad'). The issue is that sometimes the ad is showing up, and sometimes not. I noticed that, when I have the developer console open, the ad is always showing but I am not sure that is a pattern. 

## How do we reproduce the issue?

Run https://amptest-fed77.firebaseapp.com.

## What browsers are affected?

Chrome

## Which AMP version is affected?
1464987951323

**Comment by zhouyx** [comment]
ad is loaded correctly, but its content are blocked. I set ads border to better display the layout. 
<img width="858" alt="screen shot 2016-06-06 at 10 56 44 am" src="https://cloud.githubusercontent.com/assets/5419904/15832098/82c2e500-2bd5-11e6-9373-32c9bc3c7edf.png">
Looks like ad loading or blocking issue to me. I changed the example ad type and can't reproduce the issue.

**Comment by kul3r4** [comment]
Hi, 
could you update the example code?
