### ISSUE TITLE
AMP feature of the STAMP - bookend doesn't work on 2105210438003

### ISSUE THREAD

**Issue by Ichigo3d** [ampproject/amphtml#34668]
### Description

Bookend should appear after tapping on the last slide, but on 2105210438003 it doesn't appear. Production version 2105150310000 is not affected.

### Reproduction Steps

1) Go to https://www.google.com/search/static/gs/animal/m096mb.html or https://www.gstatic.com/amphtml/stamp/qa/bookend.html
2) go to the last slide
3) tap again 

Actual result: After tapping on the last slide, bookend doesn't appear.
<img width="1314" alt="Screen Shot 2021-06-03 at 4 18 05 AM" src="https://user-images.githubusercontent.com/37351864/120636687-c51ee300-c422-11eb-979f-2bb02181390f.png">

Expected result: After tapping on the last slide, bookend should appear.

<img width="510" alt="Screen Shot 2021-06-03 at 4 17 44 AM" src="https://user-images.githubusercontent.com/37351864/120636723-d2d46880-c422-11eb-8746-865beaff4861.png">

### Browser(s) Affected

Chrome, Firefox, Safari

### AMP Version Affected

2105210438003

**Comment by newmuis** [comment]
This is expected, add the bookend has been [removed](https://github.com/ampproject/amphtml/issues/33218).
