### ISSUE TITLE
[amp-iframe] iframe height is being miscalculated

### ISSUE THREAD

**Issue by dmanek** [ampproject/amphtml#34664]
### Description

On https://www.google.com/amp/s/www.nytimes.com/2021/04/20/us/black-history-continued-events.amp.html the iframe height is miscalculated, causing content to be chopped off. 

Additional context: https://amphtml.slack.com/archives/C9HPA6HGB/p1622575649072900

### Reproduction Steps

1. Go to https://www.google.com/amp/s/www.nytimes.com/2021/04/20/us/black-history-continued-events.amp.html
2. Notice content is chopped off at the bottom of the iframe. See screenshot"
![Screen Shot 2021-06-02 at 9 36 40 PM](https://user-images.githubusercontent.com/506183/120587661-a270d800-c3ea-11eb-829f-753fa458ca89.png)
3. Another issue is following console error: `Uncaught DOMException: Failed to set the 'domain' property on 'Document': Assignment is forbidden for sandboxed iframes.`

### Browser(s) Affected

Chrome, Firefox

**Comment by dmanek** [comment]
The console error only occurs on the AMP viewer due to the page trying to set `document.domain`, which is only allowed for [same or parent domain](https://developer.mozilla.org/en-US/docs/Web/API/Document/domain#:~:text=It%20can%20only%20be%20set%20to%20the%20same%20or%20a%20parent%20domain.). It does not occur when accessing the page directly.

**Comment by dmanek** [comment]
After debugging the amp-iframe code, the `updateSize_` callback receives `height` argument that is smaller than what is required for the iframe. I believe this is coming from the runtime. Any ideas @jridgewell?

**Comment by jridgewell** [comment]
The iframe is responsible for requesting a size, and we're just granting it. It's not our responsibility to guess the correct size of the iframe.

**Comment by dmanek** [comment]
Thanks @jridgewell. Looks like the postMessage to resize the iframe is sending the wrong height. @callihiggins check out https://amp.dev/documentation/components/amp-iframe/#iframe-resizing and retry with a larger height?

**Comment by dmanek** [comment]
Closing this issue since it's not on AMP.
