### ISSUE TITLE
Error reporting isn't testable

### ISSUE THREAD

**Issue by taymonbeal** [ampproject/amphtml#3466]
Currently, when writing an extension that needs to do error reporting, there's no practical way to write a unit test that verifies that reportError is called when it should be. Spying on reportError with Sinon doesn't work because it's exposed as an ES6 module export rather than as a property of an object that can be monkeypatched.

One possible approach I can think of to fix this would be to introduce a singleton ErrorReporter object, whose prototype methods could then be spied on with Sinon. Do the maintainers think this is a good idea? I'd be happy to submit a pull request if so.

**Comment by dvoytenko** [comment]
@taymonbeal I'd be happy to look into PR. We typically mock/stub `user.error` and other methods from `log.js` module to test user facing errors. `dev` instance from the same module can be used for non-user facing errors, but that's not a requirement to test.

**Comment by taymonbeal** [comment]
To clarify, this is about reporting errors to the server via `error.js`, not about making them visible in the console. The use case is that we have the ability to recover from an unexpected error by falling back to a different approach, so the error won't propagate to the top level, but we still want to know about it. As far as I can tell `log.js` doesn't make any network requests.

Also, since this seems to have been marked "Pending 3P implementation", I'd like to clarify that I'm on the Publisher Tagging team at Google and this is needed for A4A (#3133).

**Comment by dvoytenko** [comment]
If we don't want it in console, you can use `dev.error`. `log.js` errors are directed via `error.js` via the same `reportError`.

**Comment by taymonbeal** [comment]
Ok, will use `dev.error` for this instead of modifying `error.js`.
