### ISSUE TITLE
Amp Stories Generated Programmatically

### ISSUE THREAD

**Issue by tahanzania** [ampproject/amphtml#34699]
Hi Amp team, can amp-web stories be generated programmatically using existing content?

**Comment by newmuis** [comment]
Hi @tahanzania!  Yes, web stories can definitely be generated programmatically, and I've seen multiple examples of folks over the years who have done so.  Ultimately, the story is "just" an HTML document, so you're free to use whatever data you like for the content.

Hope this helps!  Please feel free to reopen this issue with any further questions you may have.

**Comment by tahanzania** [comment]
Thanks @newmuis
