### ISSUE TITLE
Add @ChrisAntaki to @ampproject/reviewers-amphtml

### ISSUE THREAD

**Issue by ChrisAntaki** [ampproject/amphtml#34690]
I would like to apply as a member of @ampproject/reviewers-amphtml

After working with AMP for two years, I feel pretty confident in my abilities to review my team's AMP PRs, for our `amp-subscriptions` and `amp-subscriptions-google` extensions

Of my AMP PRs, I think these 18 are the best examples:
https://github.com/ampproject/amphtml/pull/32590
https://github.com/ampproject/amphtml/pull/27631
https://github.com/ampproject/amphtml/pull/27556
https://github.com/ampproject/amphtml/pull/27328
https://github.com/ampproject/amphtml/pull/23163
https://github.com/ampproject/amphtml/pull/32532
https://github.com/ampproject/amphtml/pull/32522
https://github.com/ampproject/amphtml/pull/30106
https://github.com/ampproject/amphtml/pull/30100
https://github.com/ampproject/amphtml/pull/28683
https://github.com/ampproject/amphtml/pull/28644
https://github.com/ampproject/amphtml/pull/28603
https://github.com/ampproject/amphtml/pull/27309
https://github.com/ampproject/amphtml/pull/27293
https://github.com/ampproject/amphtml/pull/27218
https://github.com/ampproject/amphtml/pull/23269
https://github.com/ampproject/amphtml/pull/23256
https://github.com/ampproject/amphtml/pull/23212

**Comment by jridgewell** [comment]
Approval

**Comment by mrjoro** [comment]
Added!

**Comment by ChrisAntaki** [comment]
Thanks!
