### ISSUE TITLE
Broken Link in README.md

### ISSUE THREAD

**Issue by Brandons42** [ampproject/amphtml#34706]
### Description

On the main README for the repository, the link to AMP's governance under "Other useful information" leads to https://github.com/ampproject/meta/blob/main/docs/governance.md, which gives a 404 error. I believe it should be changed to  https://github.com/ampproject/meta/blob/main/GOVERNANCE.md. I'll be fixing this issue.

### Reproduction Steps

Navigate to the repository's main README and click the AMP's governance link towards the bottom.

**Comment by dmanek** [comment]
Thanks in advance for fixing this issue.
