### ISSUE TITLE
✨[amp-a4a] Enable `attribution-reporting` for 3p fallback

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#34719]
### Description

While working on #32603 it was determined that we should probably also allow attribution reporting for 3p ad frames as the feature roles out.

This involves adding `attribution-reporting 'src'` to any nameframe or safeframe created by A4A

@ampproject/wg-monetization we may eventually need to consider how to add this attribute to ad networks not using fast-fetch, but for now only the fast fetch networks have requested this feature. 

### Alternatives Considered

n/a

### Additional Context

https://web.dev/using-conversion-measurement/

**Comment by calebcordry** [comment]
cc/ @jshamble

**Comment by inidaname** [comment]
Hello @calebcordry I will love to take a go at this, will be happy if you could point me to the right file

**Comment by calebcordry** [comment]
@inidaname Sorry I missed this. Happy to help you find a new issue if you would like to start contributing to AMP.

**Comment by calebcordry** [comment]
Closed by #35388
