### ISSUE TITLE
Provide an issue template for "Bento tracking issue"

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#34739]
### Description

It would be very helpful to @ampproject/wg-bento contributors to have a "Bento tracking issue" template. We already have many existing such issues following identical templates which are manually filled in and filed. 

## Template requirements
- Title in the format of `[amp-component-name:version] Bento tracking issue`
- High-level requirements
  This is a matrix of considerations that the component must address. There are three columns: `Consideration`, `Ready when`, and `Status`. This ideally contains links specific to the `amp-component-name`'s documentation on amp.dev and existing accessibility issues filed with that component's label (if existent).
- Component compatibility
  - Feature checklist, such as existing attributes, actions, events, and analytics events that exist in the classic version and whether/how they are supported in the new Bento version. This may need to be manually copied from the existing component `md` file.
  - Migration notes - If there are any API changes that prevents document authors from upgrading a classic version to the new Bento version without checking anything else, that should go in this section.
- Open tasks
  - Check list for issue author or code reviewers to maintain

## Example issues
#28281, #31366, #30443, or anything in https://github.com/ampproject/amphtml/projects/100

### Alternatives Considered

- We could continue manually creating these issues, but given there are dozens of components to convert, we'd get a lot out of being able to remove some overhead with this template.
- We could [create a link to file an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/about-automation-for-issues-and-pull-requests-with-query-parameters) and use query parameters to fills the issue body with content. A downside to this is that it's not officially findable via "Create an issue" in `amphtml`, but perhaps this could also be an upside given that this type of issue may be more niche and could be linked from @ampproject/wg-bento or onboarding docs instead.

### Additional Context

I unfortunately can't do it myself since I don't have access to the alpha feature 😅  Relevant to #34400 cc/ @rsimha

**Comment by rsimha** [comment]
New issue template is available for use [here](https://github.com/ampproject/amphtml/issues/new?assignees=&labels=WG%3A+bento&template=bento-component-tracker.yml&title=%F0%9F%8D%B1+%5Bamp-component-name%3Aversion%5D+Bento+tracking+issue).
