### ISSUE TITLE
🌸 Cherry-pick request for #34589 into #34641, #34705

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#34740]
### Issue (P0 Bug)

https://github.com/ampproject/error-reporting/issues/90

### Pull Request(s)

#34589

### Release Tracker(s)

#34641, #34705

### Channels

Beta / Experimental, Stable

### Justification

errors related amp-img-gallery have increased.

see `Error: b.signals is not a function` errors. we should patch prod and experimental as soon as possible.
Also see https://github.com/ampproject/error-reporting/issues/90

### Verification Steps

- go to  https://www-ofuxico-com-br.cdn.ampproject.org/v/s/www.ofuxico.com.br/noticias-sobre-famosos/ana-maria-braga-te-ensina-como-arrasar-com-oculos-de-grau/2021/06/06-404686.amp.html?amp_gsa=1&amp_js_v=a6&usqp=mq331AQFKAGwASA%3D#ampshare=https%3A%2F%2Fwww.ofuxico.com.br%2Fnoticias-sobre-famosos%2Fana-maria-braga-te-ensina-como-arrasar-com-oculos-de-grau%2F2021%2F06%2F06-404686.html
- click on the main hero image which would trigger the following error on the console
```
Uncaught (in promise) TypeError: b.signals is not a function
    at hb.push.f.g.layoutCallback (amp-image-viewer-0.1.js:49)
    at v0.js:276
    at v0.js:6
    at new Promise (<anonymous>)
    at qa (v0.js:6)
    at HTMLElement.Ui.b.layoutCallback (v0.js:276)
    at v0.js:229
    at fm (v0.js:478)
    at bm.g.zh (v0.js:477)
```

### Summary
A revert that was necessary to remove the `img` support did not land into the latest stable which is currently causing errors to increase in stable/beta/experimental

### Impact

errors related to amp-image-gallery

### Action Items

N/A

### Cherry-Pick Progress

To be updated by @ampproject/release-on-duty as each stage is completed.
- [x] Cherry-pick request created
- [x] Cherry-pick request approved
- [ ] New version released to Beta / Experimental channels
- [ ] New version released to Stable channel
- [ ] New version released to LTS channel
- [ ] Release tracker updated
- [ ] Cherry-pick completed

### Notifications

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by kristoferbaxter** [comment]
Cherry pick approved. Let's also (and this is on me) ensure we add additional tests coverage for the revert of this revert.

Confusing, but important.

**Comment by erwinmombay** [comment]
we promoted the latest experimental branch which already had the fix to stable to fix the lightbox-gallery issue.
went ahead and stopped the cherry pick process.
