### ISSUE TITLE
Bug: amp-live-list content shifts position on update

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#3474]
To reproduce:

Open staged version of amp-live-list
Get enough updates that you can scroll the viewport so the top-most update is no longer in view

Observe: when the next update comes in (when the top-most update is scrolled out of view), the existing updates on the page are bumped down (instead, they should stay in place as updates are inserted above, without a "get updates" button)

**Comment by ericlindley-g** [comment]
Can't reproduce in most recent testing. Will re-open if this issue pops up again

**Comment by erwinmombay** [comment]
i think this still exists, since i think the order of operation should be that the scroll should happen first before pruning the number of items. I haven't had a chance to replicate yet

**Comment by ericlindley-g** [comment]
This issue was for a weird UX issue I was seeing, but can't repro anymore—I'm tracking the order of operations bug here: https://github.com/ampproject/amphtml/issues/4332  Does that seem right?

**Comment by erwinmombay** [comment]
@ericlindley-g that sgtm
