### ISSUE TITLE
Pages that use AMP trigger a security warning on Android 2.x and in IE and Safari on XP

### ISSUE THREAD

**Issue by talawahdotnet** [ampproject/amphtml#3476]
IE/Safari on XP and the Android browser on 2.x doesn't support SNI. It would appear that whenever an AMP page tries to fetch the amp js files from the CDN infrastructure, a default SSL certificate is returned which does not include *.ampproject.org in the list of SANs. This triggers a security warning.

##### Steps to reproduce
1. Visit https://www.ampproject.org/ using Internet Explorer 8 on Windows XP
2. Note the security warning and click "Continue to this website (not recommended)."
3. View the SSL certificate an note that *.ampproject.org is not in the list of Subject Alternative Names

##### Browsers affected
IE 6 - 8 and Safari 5.1 on Windows XP. Browser on Android 2.x

**Comment by dvoytenko** [comment]
@talawahdotnet WAI since these devices are too old.
