### ISSUE TITLE
[Validator feature tests] Repeated id for `<circle>` in `svg.html`

### ISSUE THREAD

**Issue by sidkshatriya** [ampproject/amphtml#3477]
There is a very minor issue in https://github.com/ampproject/amphtml/blob/3dbfefbaa346dc2eaf2e86ebb9be7bbffa7b7b96/validator/testdata/feature_tests/svg.html

The `id="svg_3"` is repeated. id's should be unique.  See line number 58 and 68.

**Comment by Gregable** [comment]
This is fixed (https://github.com/ampproject/amphtml/blob/master/validator/testdata/feature_tests/svg.html)
