### ISSUE TITLE
AMP plugin settings button suddenly disappeared 

### ISSUE THREAD

**Issue by vornet84** [ampproject/amphtml#34783]
### Description

AMP plugin suddenly disappeared from my dashboard and I can only find it in plugins list. I cannot also find the button to enable/disable AMP between articles. I cannot change settings for AMP plugin, this is not on my left list on Dashboard. It had just disappeared.

### Reproduction Steps

https://www.bet3.gr/

**Comment by alanorozco** [comment]
Bugs related to the [AMP WordPress Plugin](https://wordpress.org/plugins/amp/) can be reported at the [support forum](https://wordpress.org/support/plugin/amp/) or at the [`amp-wp`](https://github.com/ampproject/amp-wp/issues) repository.

cc @westonruter
