### ISSUE TITLE
[amp-analytics] Potential Issues with pageVisible events

### ISSUE THREAD

**Issue by rishnarang** [ampproject/amphtml#34795]
### Description

Suspected issue with amp analytics tags with GA. 

Story URL: https://stories.wnba.com/games-staging/1042000403.html

1. In the live report, the page visible events are not logged several times, even when we move within pages on this URL. 

![2021-06-09](https://user-images.githubusercontent.com/82465478/121419562-f155ca80-c920-11eb-90e6-ae9afcc609f5.png)

2. Another thing that raises suspicion for an issue is on Behavior \ Events \ Pages. 

We have many views for the first page (page 0) - 1140 but just 15 views for Page 1 and 9 views for page 2. If we look at the full picture we see that many users got to the last page.

![image](https://user-images.githubusercontent.com/82465478/121417389-b18de380-c91e-11eb-969f-5c30ada816f0.png)

Not sure if there is an issue on the event tracking side or something in the pipeline to GA. Could you help me debug this, please?

### Reproduction Steps

Story URL: https://stories.wnba.com/games-staging/1042000403.html

**Comment by gmajoulet** [comment]
We've been checking the configuration and that the events are sent correctly (they are) so we're out of options to debug this.

Can someone from @ampproject/wg-analytics help us investigate?

**Comment by micajuine-ho** [comment]
@rishnarang Are you using GA Universal Analytics?

**Comment by rishnarang** [comment]
@micajuine-ho The partner using this set up uses GA Universal Analytics.

**Comment by micajuine-ho** [comment]
One question I have is why do you have two amp-analytics elements on the page?

**Comment by heydarkatz** [comment]
@micajuine-ho 

Hi. The issue posted here happens to us. 

We have two separate UA accounts per story as we put our tracking and our clients tracking in the story. 
The events don't appear in both accounts. 

Let me know if you want me to add any more information to help identify the issue here.

**Comment by rishnarang** [comment]
Thanks @heydarkatz 

@micajuine-ho does the previous comment help? Appreciate any help on this.

**Comment by gmajoulet** [comment]
@micajuine-ho could you assign a new owner for this please? This is an important issue for us

**Comment by micajuine-ho** [comment]
@heydarkatz Thanks for explaining the context, that helps a lot.

@rishnarang or @heydarkatz do either of you have a minimal reproducible case? i.e. something in Jsbin?

@gmajoulet I'll keep working on it and assign a new owner if it is not solved by the time I depart.

**Comment by heydarkatz** [comment]
@micajuine-ho 
https://stories.wnba.com/games/1022100092.html

**Comment by micajuine-ho** [comment]
@zikas Do you you think you could take a look at this?

@gmajoulet  and I have confirmed that the `Page Visible events` are being sent from the client, but it seems like they aren't being picked up by GA. Do you have any idea why this might happen?

**Comment by heydarkatz** [comment]
@zikas @gmajoulet @micajuine-ho could you please help us understand the source of the issue and if it is on GA side, how can we trace and fix the issue? 

Thank you!

**Comment by gmajoulet** [comment]
We're working with GA internally to try to understand what is happening.

**Comment by heydarkatz** [comment]
@gmajoulet @micajuine-ho 
Hi folks, did you get any new information from GA? 

Thanks!

**Comment by gmajoulet** [comment]
Fixed by using `amp-story-auto-analytics` and the updated configuration (adding `groups: "default"` option).
