### ISSUE TITLE
It looks like the error is due to the fact that there is no element with the id `carouselPreview` on the page. Do you perhaps mean to use `carouselWithPreview`? If so, that should be unnecessary to do given it is in response to the carousel `slideChange` event (meaning, i.e. if the carousel transitions to slide `2` and fires the event, this action would then `goToSlide` of index `2` in response, which would be noop since that is already the current slide state). You should be able to remove the `carouselPreview.goToSlide(index=event.index)` line and the error will go away. this issue was still there

### ISSUE THREAD

**Issue by naveen-iiit** [ampproject/amphtml#34807]
It looks like the error is due to the fact that there is no element with the id `carouselPreview` on the page. Do you perhaps mean to use `carouselWithPreview`? If so, that should be unnecessary to do given it is in response to the carousel `slideChange` event (meaning, i.e. if the carousel transitions to slide `2` and fires the event, this action would then `goToSlide` of index `2` in response, which would be noop since that is already the current slide state). You should be able to remove the `carouselPreview.goToSlide(index=event.index)` line and the error will go away.

_Originally posted by @caroqliu in https://github.com/ampproject/amphtml/issues/34700#issuecomment-855926642_

**Comment by caroqliu** [comment]
Closing to continue the thread in #34700
