### ISSUE TITLE
news.google.com scrolling in ios 8.1 safari is broken

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#3481]
Please walk through the following steps for reporting an issue about AMP:
## Short description of your issue:

vertical scrolling on first article clicked on news.google.com on ios 8 safari is broken

works on standalone AMP article link without being under news.google.com

carousel + click interaction is OK on the news carousel in google.com (not same article)
## How do we reproduce the issue?
1. open news.google.com on ios 8.1 safari (used ios simulator)
2. click on the first AMP article on the headline carousel (the link below was the article i clicked on)
   - https://cdn.ampproject.org/v/s/amp.cnn.com/cnn/2016/06/05/politics/gop-fears-donald-trump-judge-attack/index.html?amp_js_v=5#origin=http%3A%2F%2Fnews.google.com&channelid=0&prerenderSize=1&viewportType=natural&visibilityState=prerender&paddingTop=54&history=1&p2r=0&horizontalScrolling=0&storage=1

All browsers? Some specific browser? What device type?

ios 8.1 safari

**Comment by ericlindley-g** [comment]
@dvoytenko   Slotting in current, as it looks like you're working on this, but feel free to correct/update the milestone as needed

**Comment by erwinmombay** [comment]
@dvoytenko you happen to remember what happened to this?

**Comment by dvoytenko** [comment]
This is what I just fixed :)

**Comment by jridgewell** [comment]
https://github.com/ampproject/amphtml/pull/7018? Can we close then?

**Comment by dvoytenko** [comment]
@erwinmombay Could you confirm?

**Comment by erwinmombay** [comment]
can't replicate anymore
