### ISSUE TITLE
Intent-to-Remove: <amp-viz-vega>

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#34839]
### Summary

`<amp-viz-vega>` displays visualizations created by using Vega visualization grammar. See the [reference documentation](https://github.com/ampproject/amphtml/blob/main/extensions/amp-viz-vega/amp-viz-vega.md). 

This issue is a proposal to remove the component given the following:
- The component is not and was never valid AMP.
- There has not been interest in the component for ~1.5 years.
- There is a prior removal issue #18705 which has since been closed for staleness. I created a new issue rather than reopening the original one for greater chance of visibility and discussion.

### Intent-to-Deprecate (I2D) Issue

This issue is being filed for awareness and discussion as a formality, however as clarified in #25573, this is not strictly necessary to go forward with removal.

### Rollout Plan

Given this removal does not impact valid AMP usage, the the removal plan is to unregister the component and remove associated documentation from `amphtml` upon approval given no indication of interest for continuing to go forward with component launch.

### Alternative Implementation

- `amp-script` is the recommended way to use libraries such as Vega in valid AMP, noting that `amp-script` limits how large the library being used can be.
- If there is renewed interest in the feature as a standalone component, we could work with product to either go forward with the launch of `amp-viz-vega` in #26642 instead of its removal, another visualization component such as Google Charts in #18830, or explore other possibilities. 

### Additional Context

Impact on existing users: No one is currently using it as it is not valid AMP. It does respect an experiment flag, which will enable the feature on invalid AMP pages.

### Notifications

/cc @ampproject/wg-approvers @ampproject/wg-components

**Comment by cramforce** [comment]
Approved

**Comment by jridgewell** [comment]
Approved.

**Comment by dvoytenko** [comment]
Approved
