### ISSUE TITLE
AMP Moustache variables for image is adding 404 link to all page

### ISSUE THREAD

**Issue by askmeoffers** [ampproject/amphtml#34874]
### Description

Hi Team,

First of all, thank you for providing us such a robust framework for speeding up the website.

So we are using amp-mustache with amp-list to render search results, and by default, also we display some data on the search window on your site. 
Example : [Aliexpress Coupon Store](https://askmeoffers.com/aliexpress-coupons/)

So how we will image in the search result is using triple brackets as below but when we run site audit it throws 404 error on all pages 

So what is happening when there is no data-filled amp-img src="{{image}}" will contain junk link and it's causing broken page link on all pages as its presence in the site header .

We tried fixing this but unable to 

Our template code is 

&lt;template type="amp-mustache" id="amp-template-custom"&gt;
--
&nbsp; | {{#hotstore}}
&nbsp; | &lt;div class="lt-content"&gt;&lt;p class="hotstores"&gt;Hot Stores&lt;/p&gt;&lt;/div&gt;
&nbsp; | {{/hotstore}}
&nbsp; | {{#topcat}}
&nbsp; | &lt;a class="headingf"&gt;Top Categories&lt;/a&gt;
&nbsp; | {{/topcat}}
&nbsp; | {{#is_store}}
&nbsp; | &lt;a on="tap:AMP.navigateTo(url='{{link}}')" class="search-res autocomplete-link" role="button" tabindex="0"&gt;&lt;amp-img src="{{image}}" height="59" width="143" class="amp-wp-enforced-sizes" layout="intrinsic"&gt;&lt;noscript&gt;&lt;img src="{{image}}" height="59" width="143"&gt;&lt;/noscript&gt;&lt;/amp-img&gt;&lt;p&gt;
&nbsp; | {{title}}
&nbsp; | &lt;/p&gt;&lt;/a&gt;
&nbsp; | {{/is_store}}
&nbsp; | {{#is_first}}
&nbsp; | &lt;hr data-amp-original-style="width:100%;" class="amp-wp-8588e44"&gt;
&nbsp; | &lt;strong&gt;
&nbsp; | "{{serdata}}" in Categories
&nbsp; | &lt;/strong&gt;
&nbsp; | {{/is_first}}
&nbsp; | {{#is_category}}
&nbsp; | &nbsp;
&nbsp; | &lt;a on="tap:AMP.navigateTo(url='{{link}}')" class="search-res-cat autocomplete-link" role="button" tabindex="0"&gt;&lt;p&gt;
&nbsp; | {{title}}
&nbsp; | &lt;/p&gt;&lt;/a&gt;
&nbsp; | {{/is_category}}
&nbsp; | &nbsp;
&nbsp; | &lt;/template&gt;

@caroqliu  please help me

Please help and guide us.

Team - https://askmeoffers.com/

### Reproduction Steps

Steps to reproduce this issue 
1) Visit our [Aliexpress Coupon Store](https://askmeoffers.com/aliexpress-coupons/)
2 Click on View Source view-source:https://askmeoffers.com/aliexpress-coupons/
3) Search from {{image}} in HTML

**Comment by askmeoffers** [comment]
Hi @caroqliu  Thank you for the quick revert we used https://ahrefs.com site audit 

and as you see below images our site health score is zero as this is present on all pages 

![A4ECDC02-7FBE-4DC2-8D03-6516A403AE61_1_105_c](https://user-images.githubusercontent.com/55142548/122101794-5bdf9c80-ce32-11eb-8bb0-02e63a76de0a.jpeg)

![FD498E3D-B240-4CD8-B005-C2BE2365A001_1_105_c](https://user-images.githubusercontent.com/55142548/122101830-61d57d80-ce32-11eb-9a50-9bf928d190cf.jpeg)

Let me know if you need access to https://ahrefs.com or any further information to analyze this  issue

Thanks
AskmeOffers

**Comment by caroqliu** [comment]
It looks like your audit tool is identifying an issue with the `img` tag inside your `amp-img`: `<noscript><img src="{{image}}" height="59" width="143"></noscript>`. 

Does removing the `noscript`/`img` tags resolve the issue? If not, an alternative option could be to provide your template via a [`<script type="text/plain" template="amp-mustache">`](https://amp.dev/documentation/components/amp-mustache/#usage) tag instead of a `<template>` tag so that your site audit tool can (presumably) skip inspecting the markup inside.

**Comment by askmeoffers** [comment]
Hi, @caroqliu, I added the below code in the dev environment as you suggested, and it worked perfectly, and I see there is no more 404 broken link issue Thanks a ton for this !!!
<script type="text/plain" template="amp-mustache">

Also, It will be beneficial if you can give your input on one question we have since along. 

Can we defer the amp-list and amp-mustache library loading until the user has clicked or opened our search bar?
https://askmeoffers.com/ 

As we use amp-list and amp-mustache only for our site search feature and we want to load these libraries when the user clicks or open or search bar but in the present scenario whenever page loads there libraries are loaded by default 
as seen in waterfall TAB of below gtmetrix report
https://gtmetrix.com/reports/askmeoffers.com/A9slR4XO/


The intention to avoid loading libraries as much as possible to boost page speed 

Thanks again 
Team - Askmeoffers

**Comment by samouri** [comment]
delaying certain extension scripts is something [we are exploring](https://github.com/ampproject/amphtml/issues/33689) but are not yet convinced about the relative performance gains vs. other initiatives we are pursuing.

**Comment by caroqliu** [comment]
Closing this issue as resolved; feel free to follow up in the issue linked above!
