### ISSUE TITLE
amp-embedly-card not working 

### ISSUE THREAD

**Issue by cormacncheese** [ampproject/amphtml#34881]
### Description

I'm using the amp-embedly-card to embed tik tok videos in my website. It was working a few months ago however now nothing shows up on the page.

### Reproduction Steps

```
 <amp-embedly-key value="EMBEDLY_KEY" layout="nodisplay">
 </amp-embedly-key>


<amp-embedly-card
                  data-url="https://www.tiktok.com/@smackinsunflowerseeds/video/6973695530194996486?lang=en&is_copy_url=1&is_from_webapp=v1"
                  layout="responsive"
                  width="100"
                  height="400"
                  >
</amp-embedly-card>

<script async custom-element="amp-embedly-card" src="https://cdn.ampproject.org/v0/amp-embedly-card-0.1.js"></script>
```

**Comment by caroqliu** [comment]
Hello, I copied your code snippet into the [AMP playground](https://playground.amp.dev/#share=PCFET0NUWVBFIGh0bWw+CjxodG1sIOKaoT4KICA8aGVhZD4KICAgIDxtZXRhIGNoYXJzZXQ9InV0Zi04IiAvPgogICAgPHRpdGxlPk15IEFNUCBQYWdlPC90aXRsZT4KICAgIDxsaW5rIHJlbD0iY2Fub25pY2FsIiBocmVmPSJzZWxmLmh0bWwiIC8+CiAgICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoIiAvPgogICAgPHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1vei1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDstbXMtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7YW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGh9QC13ZWJraXQta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtbW96LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1zLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW8ta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUBrZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19PC9zdHlsZT48bm9zY3JpcHQ+PHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOm5vbmU7LW1vei1hbmltYXRpb246bm9uZTstbXMtYW5pbWF0aW9uOm5vbmU7YW5pbWF0aW9uOm5vbmV9PC9zdHlsZT48L25vc2NyaXB0PgogICAgPHNjcmlwdCBhc3luYyBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwLmpzIj48L3NjcmlwdD4KICAgIDxzY3JpcHQgYXN5bmMgY3VzdG9tLWVsZW1lbnQ9ImFtcC1lbWJlZGx5LWNhcmQiIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAvYW1wLWVtYmVkbHktY2FyZC0wLjEuanMiPjwvc2NyaXB0PgogICAgPHN0eWxlIGFtcC1jdXN0b20+CiAgICAgIGgxIHsKICAgICAgICBtYXJnaW46IDFyZW07CiAgICAgIH0KICAgIDwvc3R5bGU+CiAgPC9oZWFkPgogIDxib2R5PgogICAgPGFtcC1lbWJlZGx5LWNhcmQKICAgICAgICAgICAgICAgICAgZGF0YS11cmw9Imh0dHBzOi8vd3d3LnRpa3Rvay5jb20vQHNtYWNraW5zdW5mbG93ZXJzZWVkcy92aWRlby82OTczNjk1NTMwMTk0OTk2NDg2P2xhbmc9ZW4maXNfY29weV91cmw9MSZpc19mcm9tX3dlYmFwcD12MSIKICAgICAgICAgICAgICAgICAgbGF5b3V0PSJyZXNwb25zaXZlIgogICAgICAgICAgICAgICAgICB3aWR0aD0iMTAwIgogICAgICAgICAgICAgICAgICBoZWlnaHQ9IjQwMCIKICAgICAgICAgICAgICAgICAgPgogICAgPC9hbXAtZW1iZWRseS1jYXJkPgogIDwvYm9keT4KPC9odG1sPgo=) and it appears to work:
<img width="1373" alt="Screen Shot 2021-06-16 at 9 58 33 AM" src="https://user-images.githubusercontent.com/10456171/122232849-8f014a80-ce89-11eb-8fe0-e54b2743f8bd.png">

I'm going to go ahead and close this issue, please comment and provide more information if there is something left unaddressed.
