### ISSUE TITLE
amp-live-list: investigate if we need to do a replace for the tombstone'd amp-element

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#3489]
if a tombstone'd item is an `amp-element` of some sort and we tombstone and empty out its subtree the element might still do some operation that might cause an error (timeout operation on its children w/c is now gone etc). we might need to replace it with a dummy empty div and transfer the id and data-tombstone property.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
