### ISSUE TITLE
Add a list of known client identifiers to documentation

### ISSUE THREAD

**Issue by niallkennedy** [ampproject/amphtml#349]
Create a documentation or wiki page detailing containing details about supporting or in-development AMP clients. Specify User-Agent components (header and robots.txt) and IP ranges to be used to identify incoming requests from these clients.

Expected use: a publisher would like to allow or deny access to content for AMP clients.

Example robotstxt database entry:
http://www.robotstxt.org/db/googlebot.html

**Comment by cramforce** [comment]
This is now exposed as CSS via the `amp-dynamic-css-classes` extension.
