### ISSUE TITLE
Local test-amp-ad render an ad fails

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#3492]
This seems to be similar to why `test-element-stub` was failing earlier. After debugging it seemed that the `iframe.onload` never fires for the first test block but fires for the rest!!! I am not entirely sure if this is a new chrome bug or what is happening. 

cc/ @muxin @dvoytenko, Yuxi mentioned you folks debugged this and this was your conclusion as well. Any idea what's happening?

**Comment by muxin** [comment]
#3616 is the same issue and is closed.
