### ISSUE TITLE
Page attachment feature doesn't work on mobile device under IOS15 and IOS14

### ISSUE THREAD

**Issue by Ichigo3d** [ampproject/amphtml#34928]
### Description

Page attachment feature doesn't work on real device on IOS 15.  Issue affects Safari and Chrome 
PS: devices on IOS14.6 aren't affected this issue

### Reproduction Steps

1) go to https://www.gstatic.com/amphtml/stamp/qa/page-attachment.html
2) swipe from bottom to top
3) observe result

Actual result: Page attachment doesn't start after swipe.
This issue appear on Chrome and Safari browsers on IOS 15 under 2106120107000.
Under production 2106072053000 feature works well.
https://user-images.githubusercontent.com/37351864/122610321-4639c500-d034-11eb-9d58-83b4534fcd27.mov

 

### Browser(s) Affected

Chrome, Safari

### OS(s) Affected

IOS 15

### Device(s) Affected

Iphone Xr

### AMP Version Affected

2106120107000

**Comment by gmajoulet** [comment]
cc @ampproject/wg-stories

**Comment by Ichigo3d** [comment]
I've checked it on mobile views of desktop browsers and this feature doesn't work

**Comment by processprocess** [comment]
Hi Matvei, thank you for testing and reporting this.

The page-attachment is working as expected. 
The page-attachment now opens to the max height of the content.
In this example there is one line of text so the attachment only opens a small amount.
We will update the example story to explain this behavior.
