### ISSUE TITLE
Analytics vendor to be added to AMP Project

### ISSUE THREAD

**Issue by SantoshDhanjal** [ampproject/amphtml#3494]
Hi,

We currently use IBM Digital Analytics (DA) for our web reporting. DA have not yet integrated with amp project, I have contacted them. Please can I request to add this vendor to the list of analytics that the amp project supports. I have followed the guideline stated in : https://www.ampproject.org/docs/guides/analytics_amp.html  

Thanks
Santosh
Johnston Press Publishing

**Comment by rudygalfi** [comment]
IBM would need to add a vendor configuration, so you've done the right thing by contacting them. Perhaps you could reference this issue in your communications with them.

**Comment by SantoshDhanjal** [comment]
Hi - I just need to tell IBM to add a vendor configuration? Are there any links I should give them. I think they have been on contact with amp project.

**Comment by rudygalfi** [comment]
Best thing would be if they could just reply here.

**Comment by rudygalfi** [comment]
I think this is a duplicate of #5447.
