### ISSUE TITLE
I2D: Remove examiner.js (#development=2 mode).

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#34951]
### Summary

**summary**
In https://github.com/ampproject/amphtml/pull/9260, we introduced a utility for easily seeing Long Tasks initiated by 3p frames. By adding `#development=2` to the address bar, we run the  "Examiner" script. It logs all of the Long Tasks occurring on 3p frames.

See removal draft here: https://github.com/ampproject/amphtml/pull/34941#issuecomment-865296448

### Motivation

- All of this knowledge can be gleaned equally well via browser Dev Tools.
- AFAIK, nobody is currently using this feature.
- It slightly slows and complicates our build process.

### Impact on Existing Users

As far as I can tell, nobody is going to notice this removal. I'd be pretty surprised if anyone outside of AMP Core even knew this undocumented feature existed.

### Alternative Implementation

Multiple ways:
- The Performance tooling within Dev Tools [exposes this info](https://web.dev/long-tasks-devtools/).
- Directly writing code into the console using `PerformanceObserver`. Likely a ~30 LOC snippet that could be copy/pasted.

### Notifications

/cc @ampproject/wg-approvers

**Comment by cramforce** [comment]
Approved

**Comment by honeybadgerdontcare** [comment]
Do it.

**Comment by kristoferbaxter** [comment]
Great idea, let's move forward.

**Comment by samouri** [comment]
Closed via #34941
