### ISSUE TITLE
wg-components Office Hours 2021-07-20 18:00 UTC / 11:00 PST

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#34977]
Time: [18:00 UTC / 11:00 PST](https://www.timeanddate.com/worldclock/meeting.html?year=2021&month=05&day=18&iv=0) ([add to Google Calendar](http://www.google.com/calendar/event?action=TEMPLATE&text=AMP%20Office%20Hours%20(wg-components)&dates=20210518T180000Z/20210518T18.50000Z&details=https%3A%2F%2Fmeet.google.com%2Fspd-oowj-ndo))
Location: [Video conference via Google Meet](https://meet.google.com/spd-oowj-ndo)

Office Hours are an opportunity for the community to engage with AMP working groups. You are invited to join!

@ampproject/wg-components will be hosting this session to address questions regarding the AMP component library.

**Comment by newmuis** [comment]
(nit: should this be in the https://github.com/ampproject/wg-components repo?)
