### ISSUE TITLE
Self-hosted AMP using CDN version of ww.js

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#34971]
### Description

When on self-hosted AMP, the Runtime should use the self-hosted version of `ww.js` instead of deferring to the CDN

### Reproduction Steps

1. Create a test page
2. Set Runtime host via `<meta name="runtime-host">`

**Comment by samouri** [comment]
@MadisonMiner: do you have any sample documents to help me reproduce this issue?
I just created one locally and am seeing `ww.js` get requested from example.com as expected (yes, using shadow-v0.js as well).

![Screen Shot 2021-06-22 at 6 38 24 PM](https://user-images.githubusercontent.com/4656974/123008555-13236880-d389-11eb-833b-8c736ce17dd8.png)

Note: the reason it is a `307` on my machine is because I have set an extension to redirect all requests to `example.org` back to the CDN

**Comment by MadisonMiner** [comment]
@samouri,  here is a sample page:
https://www.bedbathandbeyond.com/

![image](https://user-images.githubusercontent.com/13069628/123014601-74443f80-d37b-11eb-8828-26ecc98d033d.png)

**Comment by MadisonMiner** [comment]
@samouri, also, I should mention that ww.js being served from the cache is new. Not sure when it started, but was not happening in v 011911062056110.

**Comment by samouri** [comment]
@MadisonMiner, is this happening on all of your apps or just this one specifically?

After some debugging, I noticed an issue in how bedbathbeyond.com loads. As the `shadow-v0.js` script executes, the `<meta name=runtime-host ...>` node is present. By the time `amp-bind-0.js` executes, it appears as if the `<head>` has been modified and the meta tag is missing. I'm not sure which JS on the page is doing that, but my instinct is that it isn't the AMP code. Can you speak more to how the PWA is loaded?

The reason that some of the scripts correctly load the specified host and others load incorrectly from the CDN is related to some implementation nuances we have and how it is interacting with the race happening in `head` I described above. The Runtime script as well as the extension scripts each calculate their own value for `cdn`.  In order to ensure consistency (and reduce binary sizes!) we could make it so that only the Runtime script calculates the value and all of the other binaries reuse it.

I'll implement that fix, although I still highly recommend doing some digging on your end as to why the `<head>` is changing between these two points in time.

**Comment by MadisonMiner** [comment]
@samouri, thank you for pointing out that race condition. We will investigate.

**Comment by MadisonMiner** [comment]
@samouri, thanks again for pointing our the race condition. We've ensured the `meta name=runtime-host` tag is always present and that fixed the issue!

**Comment by samouri** [comment]
Glad to hear it :). I'll close this now, since I wouldn't quite call the current behavior a bug -- but instead it is veering into an area with undefined behavior. I'll continue to followup with aligning all the extensions with the version of `cdn` decided by shadow-v0.js in https://github.com/ampproject/amphtml/pull/34980
