### ISSUE TITLE
Changes to `forbidden-terms.js` now get checked during `check-owners --local_changes` and fail

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#34986]
![image](https://user-images.githubusercontent.com/6694512/123120901-b2407280-d412-11eb-9260-db5c8762dbc0.png)
Link: https://app.circleci.com/pipelines/github/ampproject/amphtml/11859/workflows/1e993bd7-06fe-4004-88fd-d7125f23fd85/jobs/188124

/cc @ampproject/wg-infra

**Comment by rsimha** [comment]
Looks like the `forbidden-terms.js` logic should live in `lint.js` and not in the helper function.

Assigning to @rileyajones.
