### ISSUE TITLE
AMP-carousel v 0.2 and 0.1 doesn't slide while user try to swipe it on IOS15

### ISSUE THREAD

**Issue by Ichigo3d** [ampproject/amphtml#34990]
### Description

When user try to swipe slides in any the left or the right directions, carousel works unstable: sometimes user have to swipe from edge to edge the screen, or carousel try to switch to next slide but unexpectedly coming back on previous slide.   On IOS 14.6, this behavior doesn't appear.

### Reproduction Steps

1) go to https://www.sfgate.com/warriors/amp/Klay-Thompson-D-Angelo-Russell-Draymond-Green-IG-14483595.php
2) try to swipe to the right
3) observe result

https://user-images.githubusercontent.com/37351864/123129263-ac419600-d400-11eb-9cd6-cadd9942bb0e.mov

### Browser(s) Affected

Chrome, Safari

### OS(s) Affected

IOS 15

### Device(s) Affected

Iphone Xr

### AMP Version Affected

all versions

**Comment by alanorozco** [comment]
This was caused by [a regression in iOS 15 regarding CSS Scroll Snap](https://bugs.webkit.org/show_bug.cgi?id=226816).

I can confirm that as of [iOS 15 Beta 3 (19A5297e)](https://developer.apple.com/news/releases/?id=07142021d) the bug is no longer present.

**Comment by kristoferbaxter** [comment]
That's great news! Can we confirm with each beta release manually until iOS 15 is final?

**Comment by alanorozco** [comment]
The first Public Beta was available on June 7th, and the 2nd Beta on June 30th. Beta 3 is only available as a Developer Beta currently. 

I'll be reporting back on Friday next week, and roughly every two weeks after to attempt to match the release cadence. I'll keep this issue closed unless it regresses again.

**Comment by alanorozco** [comment]
No new betas yet. I'll come back on August 6.

**Comment by alanorozco** [comment]
Public Beta 4 is out, @rebeccanthomas will try it out on a real device and provide an update.

**Comment by alanorozco** [comment]
Public Beta 4 is out, @rebeccanthomas will try it out on a real device and provide an update.

**Comment by rebeccanthomas** [comment]
Verified on a physical device that the the bug does not show up in Public Beta 4.
