### ISSUE TITLE
[Amp story] [Animation presets] pan-down, pan-up portrait ratio image position not displaying correctly

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#35016]
### Description

This appears to be happening with portrait images with `layout="responsive"` for the `pan-up` and `pan-down` presets.

[Demo story](https://stories.nws.ai/amp/1288491817/test-pan-effect-adrian/#page=201c9eb1-9347-4ad2-92f7-f4833fb61984
<img width="490" alt="Screen Shot 2021-06-24 at 8 46 23 AM" src="https://user-images.githubusercontent.com/3860311/123265153-bdee7080-d4c8-11eb-87e1-41679ee61e53.png">
)

### Reproduction Steps

Create a `amp-img` with the `animate-in="pan-down"` `layout="responsive"` attributes in a `template="fill"` grid layer.
Be sure the image is a portrait aspect ratio image.

```    
<amp-story-page id="pan-down">
  <amp-story-grid-layer template="fill">
    <amp-img animate-in-duration=".8s"  animate-in="pan-down" layout="responsive" src=<portrait image> width="1200" height="1601">
    </amp-img>
  </amp-story-grid-layer>
</amp-story-page>
```

**Comment by danielstockton** [comment]
Do we think this might be fixable any time soon? It's a fairly serious issue that many of our users are frequently coming up against.

**Comment by mszylkowski** [comment]
Even horizontal images are not properly placed (in the screenshot below the triangular structure is in the middle of the image, so only the right half is showing here)
![image](https://user-images.githubusercontent.com/22420856/161793989-1389e76d-707b-4c15-943d-2a8033f2d566.png)

I'm trying to fix this, but I worry a bit that the layout of stories are correcting this with user styles (which is not ideal but has happened before for other things). Also need to account for `pan-scaling-factor` now, that we support it. Will update this if I manage to fix it.
