### ISSUE TITLE
Intent-to-Remove: assistjs extension

### ISSUE THREAD

**Issue by ychsieh** [ampproject/amphtml#35024]
### Summary

We've been running an experiment for the assist.js project and based on the results have recently decided not to move forward with it. At this point we're starting to turn things down.

See details of this feature in I2I:  #30631

### Intent-to-Deprecate (I2D) Issue

The issue is never launched or used.

### Rollout Plan

Should be okay to do a one-time removal for all relevant code.

### Alternative Implementation

There's no any usage at all for this feature.

### Notifications

/cc @ampproject/wg-approvers

**Comment by kristoferbaxter** [comment]
Approved.

**Comment by ychsieh** [comment]
The removal PR is merged. Closing this.
