### ISSUE TITLE
facebook pre-configuration in amp-social-share is wrong

### ISSUE THREAD

**Issue by ruz** [ampproject/amphtml#3508]
https://github.com/ampproject/amphtml/blob/master/extensions/amp-social-share/0.1/amp-social-share-config.js#L37

Argument named "url", while it is "href". See "URL Redirection" on the following page:

https://developers.facebook.com/docs/sharing/reference/share-dialog

**Comment by ericlindley-g** [comment]
Passing to @mkhatib
