### ISSUE TITLE
Unable to push code from local to remote Repository

### ISSUE THREAD

**Issue by ColombiaOnline** [ampproject/amphtml#35117]
### Description

Unable to push code from local to remote Repository. Facing permission denied as below :-

Username for 'https://github.com': adtech.appservices@timesinternet.in
Password for 'https://adtech.appservices@timesinternet.in@github.com': 
remote: Permission to ampproject/amphtml.git denied to ColombiaOnline.
fatal: unable to access 'https://github.com/ampproject/amphtml.git/': The requested URL returned error: 403

It seems write access is not enabled for the mentioned user.

### Reproduction Steps

Same as description.

### Relevant Logs

```shell
geet@TILLT05409:~/DMP/amphtml$ git push origin Dmp-Analytics
Username for 'https://github.com': adtech.appservices@timesinternet.in
Password for 'https://adtech.appservices@timesinternet.in@github.com': 
remote: Permission to ampproject/amphtml.git denied to ColombiaOnline.
fatal: unable to access 'https://github.com/ampproject/amphtml.git/': The requested URL returned error: 403
```

### OS(s) Affected

NA

### Device(s) Affected

NA

**Comment by ColombiaOnline** [comment]
Gentle reminder . Please share updates.

**Comment by processprocess** [comment]
Hi @columbiaonline, thank you for following up.

From the logs it appears the commit is attempting to push to the [core repo](https://github.com/ampproject/amphtml). 
Please be sure to commit to a branch on [your forked repo](https://github.com/ColombiaOnline/amphtml).

Our [quick start guide](https://github.com/ampproject/amphtml/blob/main/docs/getting-started-quick.md) is a good resource for setup.

We recommend going through the [getting started end to end](https://github.com/ampproject/amphtml/blob/main/docs/getting-started-e2e.md) guide to learn about the lifecycle of a contribution. It might seem like a lot but once it's set up it's easy to test things locally and submit PRs smoothly.

We're excited to review community contributions!
