### ISSUE TITLE
[Story interactive] Add RTL support for sliders

### ISSUE THREAD

**Issue by mszylkowski** [ampproject/amphtml#35114]
### Description

Sliders need to be RTL compliant by filling the correct side of the thumb, having the bubble in the correct place, alternate the size increase of the bubble depending on the direction, and have the min and max on the correct size.

**Comment by processprocess** [comment]
Check out this [Logical Properties](https://web.dev/learn/css/logical-properties/) article.
It has some great information and concepts regarding the differences between "physical" properties such as "left" and "right" and "logical" properties such as "start" and "end". These can be very helpful when thinking about RTL support.
