### ISSUE TITLE
[Story interactive] Make image components RTL compliant

### ISSUE THREAD

**Issue by mszylkowski** [ampproject/amphtml#35110]
### Description

We will need to update the ABCD circles and margins to make the component work well with RTL layouts

### Alternatives Considered

-

**Comment by processprocess** [comment]
Check out this [Logical Properties](https://web.dev/learn/css/logical-properties/) article.
It has some great information and concepts regarding the differences between "physical" properties such as "left" and "right" and "logical" properties such as "start" and "end". These can be very helpful when thinking about RTL support.
