### ISSUE TITLE
🌸 Cherry-pick request for #35154 into #2107030008000

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#35155]
### Issue (P0 Bug)

#35154

### Pull Request(s)

#35146

### Release Tracker(s)

N/A I will create the release tracker once the beta is promoted.

### Channels

Beta / Experimental

### Formats

Websites

### Justification

Document renders incorrectly with overlapping content.

### Verification Steps

1. Start dev server
2. Run [this story](https://www.axios.com/border-democrats-migrants-vaccinated-44abf3d7-10ad-43b6-82b2-e0443df80db5.html) through the proxy
3. Content should not overlap:
<img width="479" alt="Screen Shot 2021-07-08 at 11 43 56 AM" src="https://user-images.githubusercontent.com/3860311/124951924-caeb8380-dfe1-11eb-815b-b68ec59291fd.png">

### Summary

Copied from #35146: 

```
The root cause of the issue was that parseLayout is not equivalent to this.getLayout().

parseLayout() just ensures the input layout type is valid and returns a Layout
this.getLayout() would use the "effective layout" calculated by calling applyStaticLayout.
```

### Impact

This was caught by visual diff testing and was not user-visible.

### Action Items

Write tests for `amp-layout` #35157

### Notifications

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by kristoferbaxter** [comment]
Approved.
