### ISSUE TITLE
Resources Performance

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#3515]
I'm doing some profiling for iOS scrolling. On some frames, we spend around 5.3ms running the [`Resource doPass`](https://github.com/ampproject/amphtml/blob/master/src/service/resources-impl.js#L1456-L1476).

25% of that time is [spent](https://github.com/ampproject/amphtml/blob/master/src/service/resources-impl.js#L1472) (1.4ms) trying to determine if the [`Body#scrollHeight`](https://github.com/ampproject/amphtml/blob/master/src/service/resources-impl.js#L320-L330) has changed. What's worse, on iOS, that won't even work!

Why are we doing this, and do we need to keep doing it? If we do, this needs to call [`Viewport#getScrollHeight`](https://github.com/ampproject/amphtml/blob/master/src/service/viewport-impl.js#L235-L242).

**Comment by dvoytenko** [comment]
`getScrollHeight` in `Resources` is completely useless and should be removed. Leftover of the old viewport experiment.

**Comment by cramforce** [comment]
Great find. Lets fix!!!
