### ISSUE TITLE
Enable `capture` attribute for `<input type="file">`

### ISSUE THREAD

**Issue by hollowaykeanho** [ampproject/amphtml#35177]
### Description

As `amp-form` is using the conventional `<form>` syntax, `<input type="file"`> with `capture` attribute designate the use of capturing devices (See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#capture) which is a sub-function on its own.

There is no reason why it is prohibited since it is part of the input and not altering the form attributes like `formmethod=` attribute in `<input type="submit">`.

Also, it is too small to spin a new module like `<amp-camera>`. It would be funny but it will be very hard for us CSS component designers to cope with these custom stuffs.

### Alternatives Considered

No alternatives available except breaking the user experience.

### Additional Context

![screenshot-2021-07-11-12-36-16](https://user-images.githubusercontent.com/7259572/125182907-a5aa7f80-e244-11eb-9ecf-9a4177efbe91.png)

Note:
1. Ignore the `form action=` error because the Hugo engine generator is still having tough time generating multiple output format (as in Vanilla HTML5 and AMPHTML) at the same time.

**Comment by honeybadgerdontcare** [comment]
@ampproject/wg-amp4email should this be added for the AMP Email format?

@ampproject/wg-monetization should this be added for the AMP Ad format?

**Comment by zhangsu** [comment]
> @ampproject/wg-amp4email should this be added for the AMP Email format?

No. `<input type=file>` is banned in AMP for Email for security and privacy reasons.

**Comment by powerivq** [comment]
Ads does not use form, so it won't be very useful for ads.

**Comment by honeybadgerdontcare** [comment]
Ah, thank you both. I was indeed looking at the wrong tagspec and missed the disallowed value regex.
