### ISSUE TITLE
the process of accepting a PR by an analytics vendor

### ISSUE THREAD

**Issue by fredsh2k** [ampproject/amphtml#35200]
### Description

We are an analytics vendor and would like to add ourselves as vendor to amp-analytics component.
We looked into this guide https://amp.dev/documentation/guides-and-tutorials/contribute/integrate-your-analytics-tools/
The process to add ourselves as an analytics vendor is to open an Intent-to-implement issue and a PR with the analytics.json config. We have some questions regarding that:

1. What's the process of accepting a PR to change amp-analytics vendor config?
2. Is there a verification step that the person is actually representing the analytics vendor company?
3. How much time approximately does it take to accept a PR? 

Thanks
(I was forwarded here to ask the maintainers of the project instead of slack/stackoverflow)

### Alternatives Considered

N/a

**Comment by dmanek** [comment]
@alanorozco can you please answer the questions above?

**Comment by alanorozco** [comment]
> What's the process of accepting a PR to change amp-analytics vendor config?

You only need to file the PR. A bot will assign a reviewer for you.

> Is there a verification step that the person is actually representing the analytics vendor company?

We don't have an initial verification process since we assume good faith.

If you'd like to limit collaborations to known people in your company, we can add an OWNERS file that limits changes. Of course, if the people in the OWNERS file leave the company they have to approve a change to point to a new contact.

> How much time approximately does it take to accept a PR?

We don't have an SLA (please bear with us!), but we try to review incoming Pull Requests within the next two working days.

**Comment by fredsh2k** [comment]
thanks @alanorozco 

can you please guide me through the process of using an OWNERS file?  
should I just send you a list of my team's emails?

specifically, I created this PR 
https://github.com/ampproject/amphtml/pull/35220/files#diff-70c35c0ae2da511432de50d08de15dfe562bd3e2683d3c27684ab90018a500fbR6

should I add an OWNERS file to this PR? Where should I put it in the project?

**Comment by alanorozco** [comment]
@fredsh2k They should be github usernames.

Add `extensions/vendors/OWNERS` with following contents. Keep `ampproject/wg-components` in any case, and add any other entries with `name`.

```json5
// For an explanation of the OWNERS rules and syntax, see:
// https://github.com/ampproject/amp-github-apps/blob/main/owners/OWNERS.example
{
  rules: [
    {
      pattern: 'appsflyer.json',
      owners: [
        {name: 'ampproject/wg-components'},
        {name: 'fredsh2k'},
      ],
    },
  ],
}
```
