### ISSUE TITLE
test-ad-cid is flaky

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#3521]
Chromium 45.0.2454 (Ubuntu 0.0.0) ad-cid-embed cid-ad support provides null if cid service not available FAILED
	Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

Seems to be a timeout of an external resource loading. Is it a convention to load "https://schema.org" in amp-ad btw :-).

**Comment by lannka** [comment]
#3503

**Comment by cramforce** [comment]
Are you sure that URL is being requested? Where?

**Comment by lannka** [comment]
https://github.com/ampproject/amphtml/blob/master/test/functional/test-ad-cid.js#L150

```
      it('provides null if cid service not available', () => {
        clientIdScope['with_cid'] = cidScope;
        return getAd({
          width: 300,
          height: 250,
          type: 'with_cid',
          src: 'testsrc',
        }, 'https://schema.org', function(ad) {
          setCookie(window, cidScope, 'XXX',
              new Date().getTime() + 5000);
          return ad;
        }).then(ad => {
          expect(ad.getAttribute('ampcid')).to.be.null;
        });
      });
```

**Comment by cramforce** [comment]
That does not actually request that URL (I think :). It only provides a
canonical URL to the ad.

**Comment by ericlindley-g** [comment]
@lannka   Slotting in backlog, but feel free to correct/update the milestone as needed
