### ISSUE TITLE
investigate using --checks-only flag for the type checking task

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#3523]
Related to https://github.com/ampproject/amphtml/pull/3506

tried using --checks-only, usually get an error that its looking for the build/cc/*\* files which don't get generated when --checks-only is on (makes sense since it suppresses output). best guess right now is its trying to create the source maps.

**Comment by ericlindley-g** [comment]
@erwinmombay   Slotting in backlog, but feel free to correct/update the milestone as needed
