### ISSUE TITLE
I2D: `test-status` checks

### ISSUE THREAD

**Issue by rileyajones** [ampproject/amphtml#35247]
### Summary

After tests run in CI they report a status to our custom `test-status` bot which then shows a message on the PR.
![image](https://user-images.githubusercontent.com/78179109/125856751-5d8ff896-c252-4a6f-ae00-77c299e72e7c.png)

This information is redundant with the information displayed by the CircleCI checks while requiring the maintenance of both the bot and integration with it.
![image](https://user-images.githubusercontent.com/78179109/125856983-275e188e-ae90-46f4-8267-9a375d9ac97c.png)

### Motivation

CircleCI provides a lot more information about tests and their statuses in a cleaner way without requiring as much of a maintenance burden.

### Impact on Existing Users

Realistically none. Some developers may need to discover failed tests differently.

### Alternative Implementation

Do not remove the bot and work to reduce the tech debt it contains.

### Notifications

/cc @ampproject/wg-approvers

**Comment by kristoferbaxter** [comment]
Approved!

**Comment by rsimha** [comment]
+1, approved 👍
