### ISSUE TITLE
Amp Story Desktop One Panel I2S

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#35267]
### Summary

We are migrating away from the 3 panel desktop UI to a more simplified UI that focuses on the page being viewed. This change enables us to deliver a consistent user experience across phones, tablets and desktops and enables rich effects (like page transitions) to work well on desktops. We've also added an effect to enliven the space around the Story page on desktops.

https://user-images.githubusercontent.com/3860311/125990887-47c55678-8d08-42cc-8968-0beebd84db57.mp4

This update:
- Removes viewport warnings (All screen sizes will now render stories)
<img width="424" alt="Screen Shot 2021-07-16 at 1 54 37 PM" src="https://user-images.githubusercontent.com/3860311/125989428-27c620f4-ad70-4dca-a670-25e9d98b82f8.png">
- Removes the desktop-panels UI mode
<img width="442" alt="Screen Shot 2021-07-16 at 1 54 07 PM" src="https://user-images.githubusercontent.com/3860311/125989409-442cec01-2414-450e-9511-9e7bdadfcb0f.png">
- Adds a blur overlay which selects the largest image or video on the current page.
<img width="569" alt="Screen Shot 2021-07-16 at 1 56 05 PM" src="https://user-images.githubusercontent.com/3860311/125989522-921f19e2-2daf-455d-8756-f1c374da49cc.png">
- Player support with next and previous story buttons
<img width="1172" alt="Screen Shot 2021-07-16 at 2 18 38 PM" src="https://user-images.githubusercontent.com/3860311/125991852-6f11e45e-d867-4b2a-ba49-2630e4dd0f72.png">

### Intent-to-Implement (I2I) Issue

#34479

### Experiment(s) to Enable

`amp-story-desktop-one-panel`

### Release Tracking Issue

The story one-panel and blur code is part of
[2107240354000](https://github.com/ampproject/amphtml/issues/35415)  

The amp-story-player update is not yet in a release and pending merge of [#35423](https://github.com/ampproject/amphtml/pull/35423)

### Demo Instructions

[Demo link](https://discovery-ec239.web.app/examples/amp-story/homewarrior/index.html)

### Rollout details

The `amp-story` updates (panel and blur) will be activated prior to the `amp-story-player` updates. 
This ensures the new player UI updates position correctly on the new panel experience.

### Notifications

/cc @ampproject/wg-approvers

**Comment by gmajoulet** [comment]
cc @ampproject/wg-approvers can you please take a look? @processprocess will present this at design review to give the opportunity for more people to chime in, but we'd be happy to get some approvals ahead of time as this is a very straightforward UX win.

**Comment by newmuis** [comment]
The I2I was actually already presented at the [2021-06-02 design review](https://github.com/ampproject/amphtml/issues/34335).  Are there additional insights we're hoping to gain?  There was [general agreement](https://github.com/ampproject/amphtml/issues/34479#issuecomment-853388791) at that time.

**Comment by newmuis** [comment]
Approved!

**Comment by kristoferbaxter** [comment]
Approved, thanks again for being so thorough.

**Comment by rsimha** [comment]
+1, approved.
