### ISSUE TITLE
amp-video elements not loading with v1.0

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amphtml#35277]
### Description

When using `<amp-video>` elements and loading v1.0 of the `amp-video` extension, the elements don't fully load and are thus not visible on the page. 

They'll have `i-amphtml-notbuilt amp-notbuilt` class names too.

Is v1.0 not ready yet and should not be used?

### Reproduction Steps

1. Open AMP playground
2. Add `<amp-video>` element    
```html
<amp-video autoplay loop
    width="720"
    height="960"
    poster="https://amp.dev/static/samples/img/story_video_dog_cover.jpg"
    layout="responsive">
    <source src="https://amp.dev/static/samples/video/story_video_dog.mp4" type="video/mp4">
</amp-video>
```
3. Change script src to `https://cdn.ampproject.org/v0/amp-video-1.0.js`

### Relevant Logs

```shell
expected global "bento" or specific "bento-video" experiment to be enabled​​​
Uncaught (in promise) Error: expected global "bento" or specific "bento-video" experiment to be enabled​​​
```

### Browser(s) Affected

Chrome

### OS(s) Affected

macOS

### AMP Version Affected

2107030008001

**Comment by westonruter** [comment]
The 1.0 version is Bento and still requires the Bento experiment to be enabled. The `latestVersion` is still `0.1` so it should be used instead. See https://github.com/ampproject/amphtml/blob/31db64d03ff34e2ec4fc640f177ab13fe62c638e/build-system/compile/bundles.config.extensions.json#L1157-L1170

**Comment by swissspidy** [comment]
Looks like I can close this then! Thanks!
