### ISSUE TITLE
AMP Adsense Code Height value (and allowed Modifications)

### ISSUE THREAD

**Issue by user631** [ampproject/amphtml#35275]
Observing a strange issue in Adsense Ad setup.

When generating AMP Ads (non-auto ones) : 

AMP Ads -> "Create New Ad" -> "Ad Unit" - >"Display Ads" and keeping the option as "Responsive", there are three choices available - SQUARE, HORIZONTAL and VERTICAL.
The Square option shows a square ad sample with height 300, Horizontal option shows sample ad with height 90, and vertical one shows sample ad with height 600.
However, irrespective of which option a user selects (SQUARE, HORIZONTAL and VERTICAL), the height of AMP ad code generated is always fixed at "320". (Width as "100vw" is fine because it is AMP responsive ad.)

```
<amp-ad width="100vw" height="**320**"
     type="adsense"
     data-ad-client="ca-pub-xxxxxx"
     data-ad-slot="xxxxxxx"
     data-auto-format="rspv"
     data-full-width="">
  <div overflow=""></div>
</amp-ad>
```

1) Is the code that gets generated incorrect because it always has (height="320") irrespective of which option a user selects (SQUARE, HORIZONTAL and VERTICAL). Shouldn't it be 300, 90 and 600 respectively? Is this a bug in adsense code generator?

2) Are we allowed to change this height attribute for the best fit? to say the standard ad heights like 300, 90, or 600, or will it be a violation???

**Comment by alanorozco** [comment]
This looks like an issue with a specific generator tool. I'm closing this issue since it's not related to the AMP framework itself.

@calebcordry Is there a way to triage this? Do we have an answer to this question?

**Comment by calebcordry** [comment]
@user631 How are you generating these ads? Is it through the adsense UI?

**Comment by user631** [comment]
Thanks @alanorozco and @calebcordry 

> @user631 How are you generating these ads? Is it through the adsense UI?


Its through the standard "https://www.google.com/adsense/" login.

When generating AMP Ads (non-auto ones) :

AMP Ads -> "Create New Ad" -> "Ad Unit" - >"Display Ads" and keeping the option as "Responsive", there are three choices available - SQUARE, HORIZONTAL and VERTICAL.
However, irrespective of which option a user selects (SQUARE, HORIZONTAL and VERTICAL), the height of AMP ad code generated is always fixed at "320". (Width as "100vw" is fine because it is AMP responsive ad.)
