### ISSUE TITLE
`amp-story-desktop-one-panel` `background-blur` blur sometimes empty from video when re-playing story

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#35270]
Blur sometimes renders an empty frame when blurring from a video on re-playing a story.
![Jul-16-2021 15-27-31](https://user-images.githubusercontent.com/3860311/125999165-ffe2211d-b841-44ea-97dc-bbfb635684c0.gif)

Could be fixed as part of the work in #35282

**Comment by ychsieh** [comment]
not reproducible
