### ISSUE TITLE
currentContinuousVisibleTime variable for visibilitySpec in amp-analytics

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#3528]
#3512 follow up: It would be nice to have a currentContinuousVisibleTime variable that emits the continuous visibility time of the element (as opposed to max or min).

**Comment by avimehta** [comment]
@rudygalfi this should be easy to implement. Should I do this?

**Comment by rudygalfi** [comment]
Yeah, that would be great.

**Comment by lannka** [comment]
I believe we already had this:
https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#max-continuous-visible-time
