### ISSUE TITLE
🐛installExtensionForDoc not working in local dev server

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#35325]
### Description

Elements installed using `installExtensionForDoc` will have the wrong `src` path in our local dev server causing 404.
![image](https://user-images.githubusercontent.com/16087874/126408323-2e351e25-ea11-4af1-907a-024e83f4e7de.png)

Story ads install the `amp-ad` element using https://github.com/ampproject/amphtml/blob/f0a90fae17c7224f83f40dddb6583aef4e7d96d1/src/service/extensions-impl.js#L246
Eventually this calls `createExtensionScript` which passes the result of `getMode().localDev` https://github.com/ampproject/amphtml/blob/f0a90fae17c7224f83f40dddb6583aef4e7d96d1/src/service/extension-script.js#L155

I think this is the root of our problem. This is `false` should be `true`?  Hardcoding `true` fixes the issue.

### Reproduction Steps

visit `/examples/amp-story/story-ad-remote-config.html` and look at network tab or console

**Comment by calebcordry** [comment]
@rcebulko I think you may have been making changes that might affect this? If not could you point me the right direction please?

cc/ @jshamble

**Comment by rcebulko** [comment]
@calebcordry when did this start? I did update some `getMode` code, but not in the past couple of weeks. @samouri could this be related to any of your recent work? (I'm not sure what has/hasn't been submitted of the PRs I've reviewed these past two weeks)

**Comment by calebcordry** [comment]
I noticed last week but forgot to file the issue. Not sure exactly when, but a couple weeks seems possible.

**Comment by samouri** [comment]
@calebcordry: which command are you running? Just a bare `amp`?

**Comment by calebcordry** [comment]
yep just `amp`

**Comment by samouri** [comment]
Thanks for the help Caleb! This was indeed my fault 🙃 . Fix located here: https://github.com/ampproject/amphtml/pull/35335
