### ISSUE TITLE
getMode().localDev is false when running dev server

### ISSUE THREAD

**Issue by powerivq** [ampproject/amphtml#35344]
### Description

localDev environment variable is returning false when running `amp`

### Reproduction Steps

1. Run `amp`
2. `getMode(win).localDev` returns false
3. `window.__AMP_MODE` also returns localDev=false
4. amp.js (compiled bundle) correctly reflects localDev=true

**Comment by samouri** [comment]
Have you rebased since this was merged 2 hours ago? https://github.com/ampproject/amphtml/pull/35335

**Comment by powerivq** [comment]
@samouri It worked. Thanks! Closing this issue.
