### ISSUE TITLE
[Amp Story] [iOS] Olympics 2020 stories in iGA, Safari browser, and Chrome browser are laggy.

### ISSUE THREAD

**Issue by jingfei** [ampproject/amphtml#35374]
### Description

The stories are laggy while opening in iPhone: next / previous buttons are not very responsive, for example there's ~1s delay to switch to the next page after tapping.

The issue is observed from the following devices:
- iOS 14.6 Iphone X
- iOS 14.6 iphone 11 pro max
- iOS 14.5 iphone 11
- iOS 14.7 iphone 11

It happens in all the following player:
- iGA Discover tab
- Chrome browser
- Safari browser

Example stories:
- https://www.google.com/search/static/gs/live/og2020/en-US/latest/
- https://www.google.com/search/static/gs/live/og2020/hi-IN/latest/
- https://www.google.com/search/static/gs/live/og2020/id-ID/latest/
and more

### Reproduction Steps

1. Open Olympics 2020 stories from iGA Discover tab, Chrome browser, or Safari browser in iOS device.
2. Navigate through story pages.
3. The UI is laggy, for example there's ~1s delay to switch to the next page after tapping.

Example stories:
- https://www.google.com/search/static/gs/live/og2020/en-US/latest/
- https://www.google.com/search/static/gs/live/og2020/hi-IN/latest/
- https://www.google.com/search/static/gs/live/og2020/id-ID/latest/
and more

### Browser(s) Affected

Chrome, Safari

### OS(s) Affected

iOS 14

### Device(s) Affected

iPhone X, iPhone 11

**Comment by newmuis** [comment]
After syncing with @gmajoulet and @mszylkowski, there are a few things that could be done on the publisher side to make these stories more performant:

1. The images used in the stories are quite large.  These should be downsampled to a reasonable size (e.g. the image for [this page](https://user-images.githubusercontent.com/1651960/126819421-9eb84497-69f5-43ce-b395-4367a1bd6b9a.png) is 2395x2894px; it should likely be more like 1060x1280 at most).
2. Each page of the story has a background image with a CSS `filter: blur(40px)` applied.  This will cause an undue burden on the GPU to calculate the blur at runtime.  Instead, if possible, the background image should be blurred before it is served.

There are also some format-level changes we can make to improve the iOS performance, such as https://github.com/ampproject/amphtml/issues/29508, but ideally it could make sense to optimize both in parallel.

**Comment by jingfei** [comment]
Thanks for the suggestions. I will file bugs to the team for the improvement!

**Comment by gmajoulet** [comment]
+1 to everything Jon said you should get meaningful improvements following these steps. On top of the image resolution, you can also improve how they're compressed. You should be able to save 40 to 60% of the file size without seeing a visual drop in image quality. Pretty sure you have access to better tools but you can test it with online things like https://tinyjpg.com/

**Comment by jingfei** [comment]
Update: We test the same device again in [story](https://www.google.com/search/static/gs/live/og2020/en-US/2021-07-23/#page=cover) that doesn't use blur effect, and we don't see the issue!

We are working on using the background with only 1-2 colors extracted from image as the temporary fix. At the same time, looking to query downscaled image from the source.

**Comment by jingfei** [comment]
The issue is resolved by extracting colors from image as the background for iOS device.
