### ISSUE TITLE
Bento: TypeError when using React.Fragment

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amphtml#35412]
### Description

I am running into issues with `React.Fragment` usage in `@ampproject/amp-base-carousel/react`.

AMP defines the type interfaces for the Preact APIs like so:

https://github.com/ampproject/amphtml/blob/d4c1cebb15b09bb607a36b0724c16bb5e2ab11eb/src/preact/index.js#L25-L33

https://github.com/ampproject/amphtml/blob/d4c1cebb15b09bb607a36b0724c16bb5e2ab11eb/src/preact/index.js#L62-L68

In the React version, `preact` basically simply points to `require('react')`, otherwise it appears to be the same.

The bug here is with the `preact.Fragment` bit. While `Fragment` appears to be a function in Preact, it isn't in _React_. This causes JavaScript errors when running the application, saying that `preact.Fragment` is not a function.

In React, a `Fragment` needs to be created with `React.createElement` like any other element, e.g. `React.createElement(React.Fragment, props, ...children)`

The compiled Bento React components contain code like this (with `preact` actually pointing to the `react` package):

```js

function createElement2(unusedType, unusedProps, var_args) {
	return preact.createElement.apply(void 0, arguments);
}

// ...

function Fragment2(props) {
  // TypeError: preact.Fragment is not a function
  return preact.Fragment(props);
}
```

Changing it to this fixed the issue for me:

```js
function Fragment2(props) {
  return createElement2(preact.Fragment, props, ...children);
}
```

### Reproduction Steps

I am basically doing this:

```js
import { BaseCarousel } from '@ampproject/amp-base-carousel/react';

function SomeComponent() {
	  return (
		    <BaseCarousel
		    autoAdvance={ true }
		    loop={ true }
		    snap={ true }
		    >
	  );
}
```

### Relevant Logs

```shell
TypeError: preact.Fragment is not a function
```

### AMP Version Affected

2107092322000

**Comment by caroqliu** [comment]
FYI @jridgewell @developit
