### ISSUE TITLE
📕 Write docs for story ad remote config

### ISSUE THREAD

**Issue by calebcordry** [ampproject/amphtml#35425]
### Description

Feature introduced in #35256

Existing docs at
https://github.com/ampproject/amphtml/blob/main/extensions/amp-story-auto-ads/amp-story-auto-ads.md#configuration

### Alternatives Considered

none

**Comment by Mstafamhamadmhamad** [comment]
> ### Description
> Feature introduced in #35256
> 
> Existing docs at
> https://github.com/ampproject/amphtml/blob/main/extensions/amp-story-auto-ads/amp-story-auto-ads.md#configuration
> 
> ### Alternatives Considered
> none
> 
> ### Additional Context
> _No response_

**Comment by Mstafamhamadmhamad** [comment]
@processprocess

**Comment by Mstafamhamadmhamad** [comment]
#34671

**Comment by Mstafamhamadmhamad** [comment]
@Mstafamhamadmhamad

**Comment by Mstafamhamadmhamad** [comment]
Duplicate of #
