### ISSUE TITLE
Binding a URL from the remote json through parsing error

### ISSUE THREAD

**Issue by gskaushal92** [ampproject/amphtml#35451]
### Description

1.  I have json data obj as follows:
`{
  "Obj": [
    {
      "Address1": "test",
      "Url": "/atm/atms-in-bangalore/epip/floor-tcs-A0002.page"
    }
  ]
}`
2. I am using amp-list and template-mustache to bind this data to my page.
3. But while binding url with href attribute of anchor tag, i am getting parsing error as below

`a.ic-more.i-amphtml-error %s amp-bind: Expression compile error in "/atm/atms-in-bangalore/epip/floor-tcs-A0002.page". Parse error on line 1:
/atm/atms-in
^
Expecting 'EOF', '(', '!', '-', '+', 'NAME', '[', 'STRING', 'NUMBER', 'TRUE', 'FALSE', 'NULL', '{', got '/'​​​`

4. If try binding url: https://www.google.com from json. It is giving me parsing error as for the above url.

How I can fix this issue?  I need to bind this url in my current project.

### Reproduction Steps

1.  I have json data obj as follows:
`{
  "Obj": [
    {
      "Address1": "test",
      "Url": "/atm/atms-in-bangalore/epip/floor-tcs-A0002.page"
    }
  ]
}`
2. I am using amp-list and template-mustache to bind this data to my page.
3. But while binding url with href attribute of anchor tag, i am getting parsing error as below

`a.ic-more.i-amphtml-error %s amp-bind: Expression compile error in "/atm/atms-in-bangalore/epip/floor-tcs-A0002.page". Parse error on line 1:
/atm/atms-in
^
Expecting 'EOF', '(', '!', '-', '+', 'NAME', '[', 'STRING', 'NUMBER', 'TRUE', 'FALSE', 'NULL', '{', got '/'​​​`

### Relevant Logs

```shell
`a.ic-more.i-amphtml-error %s amp-bind: Expression compile error in "/atm/atms-in-bangalore/epip/floor-tcs-A0002.page". Parse error on line 1:
/atm/atms-in
^
Expecting 'EOF', '(', '!', '-', '+', 'NAME', '[', 'STRING', 'NUMBER', 'TRUE', 'FALSE', 'NULL', '{', got '/'​​​`
```

### Browser(s) Affected

Chrome, Firefox, Safari, Edge

**Comment by caroqliu** [comment]
The following code snippet works for me [in the playground](https://playground.amp.dev/#share=PCFET0NUWVBFIGh0bWw+CjxodG1sIOKaoT4KICA8aGVhZD4KICAgIDxtZXRhIGNoYXJzZXQ9InV0Zi04IiAvPgogICAgPHRpdGxlPk15IEFNUCBQYWdlPC90aXRsZT4KICAgIDxsaW5rIHJlbD0iY2Fub25pY2FsIiBocmVmPSJzZWxmLmh0bWwiIC8+CiAgICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoIiAvPgogICAgPHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1vei1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDstbXMtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7YW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGh9QC13ZWJraXQta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtbW96LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1zLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW8ta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUBrZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19PC9zdHlsZT48bm9zY3JpcHQ+PHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOm5vbmU7LW1vei1hbmltYXRpb246bm9uZTstbXMtYW5pbWF0aW9uOm5vbmU7YW5pbWF0aW9uOm5vbmV9PC9zdHlsZT48L25vc2NyaXB0PgogICAgPHNjcmlwdCBhc3luYyBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwLmpzIj48L3NjcmlwdD4KICAgIDxzY3JpcHQgYXN5bmMgY3VzdG9tLWVsZW1lbnQ9ImFtcC1iaW5kIiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1iaW5kLTAuMS5qcyI+PC9zY3JpcHQ+CiAgICA8c2NyaXB0IGFzeW5jIGN1c3RvbS1lbGVtZW50PSJhbXAtbGlzdCIgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC9hbXAtbGlzdC0wLjEuanMiPjwvc2NyaXB0PgogICAgPHNjcmlwdCBhc3luYyBjdXN0b20tdGVtcGxhdGU9ImFtcC1tdXN0YWNoZSIgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC9hbXAtbXVzdGFjaGUtMC4yLmpzIj48L3NjcmlwdD4KICAgIDxtZXRhIG5hbWU9ImFtcC1zY3JpcHQtc3JjIiBjb250ZW50PSJzaGEzODQtY1VSSTNJZWJwaEtkdGhlbDV4OWlaVlJrbUROV1EtaWxpWXA4Ql83QjdWeDlvNEZuVEQ0NklmaDJGUFM0dUgySyAiPgogIDwvaGVhZD4KPGJvZHk+CjxhbXAtc3RhdGUgaWQ9ImxvY2FsU3RhdGUiPgogIDxzY3JpcHQgdHlwZT0iYXBwbGljYXRpb24vanNvbiI+CiAgICB7CiAgICAgICJPYmoiOiBbeyJBZGRyZXNzMSI6ICJ0ZXN0IiwgIlVybCI6ICIvYXRtL2F0bXMtaW4tYmFuZ2Fsb3JlL2VwaXAvZmxvb3ItdGNzLUEwMDAyLnBhZ2UifV0KICAgIH0KICA8L3NjcmlwdD4KPC9hbXAtc3RhdGU+CjxhbXAtbGlzdCBsYXlvdXQ9ImZpeGVkLWhlaWdodCIgaXRlbXM9Ik9iaiIgaGVpZ2h0PSIzMDAwIiBzcmM9ImFtcC1zdGF0ZTpsb2NhbFN0YXRlIj4KICA8dGVtcGxhdGUgdHlwZT0iYW1wLW11c3RhY2hlIj4KICAgIDxhIGhyZWY9e3tVcmx9fT57e0FkZHJlc3MxfX08L2E+CiAgPC90ZW1wbGF0ZT4KPC9hbXAtbGlzdD4KPC9ib2R5Pgo8L2h0bWw+Cg==):
```html
<amp-state id="localState">
  <script type="application/json">
    {
      "Obj": [{"Address1": "test", "Url": "/atm/atms-in-bangalore/epip/floor-tcs-A0002.page"}]
    }
  </script>
</amp-state>
<amp-list layout="fixed-height" items="Obj" height="3000" src="amp-state:localState">
  <template type="amp-mustache">
    <a href={{Url}}>{{Address1}}</a>
  </template>
</amp-list>
```

Can you tell me more about the issue? Maybe I am misunderstanding?

**Comment by gskaushal92** [comment]
I have not used amp-state because I need to perform some operation on my json data. 
So I have used ` exportFunction('dummyFunc', function(){});` to fetch the data. After that when I try to bind the url
`<a href="{{url}}" class="ic-more">know more</a>` I ma getting parse error as described above.

**Comment by caroqliu** [comment]
Can you please send me the full code you are having issues with in a playground.amp.dev link?

**Comment by gskaushal92** [comment]
Sorry That is confidential code and data. Can not share on playground. But they way you tried, I also tried at my local it is working fine with the following binding 
`<div class="button-group">
                                    <a href="{{dirUrl}}" class="ic-btn"
                                      >Get Directions</a
                                    >
                                    <a href="{{url}}" class="ic-more"
                                      >know more</a
                                    >
                                  </div>` .
 But When I move this component to AEM.  then this is coming as 
 `<div class="button-group">
                                Get Directions
                                Know More
                              </div>` without the anchor tag and link url. 

But When I am using [href] binding `<div class="button-group">
                                    <a [href]="{{dirUrl}}" class="ic-btn"
                                      >Get Directions</a
                                    >
                                    <a [href]="{{url}}" class="ic-more"
                                      >know more</a
                                    >
                                  </div>` 
Then i am getting parsing error.

**Comment by gskaushal92** [comment]
My issue is fixed using following code. href was not binding with dirUrl on page load. But when I tried with div and navigateTo event it is working fine. 
`<div  class="ic-btn"  on="tap:AMP.navigateTo(url='{{dirUrl}}', target='_blank')" > Get Direction </div>`

But I am still not sure why it is not working with href.

But anyway thanks for quick reply and looking into my issue.
