### ISSUE TITLE
Images doesn't loading after 3.image

### ISSUE THREAD

**Issue by g-u-r-k-a-n** [ampproject/amphtml#35471]
### Description

I have a carousel that I created with [splide.js](https://github.com/Splidejs/splide). I have about 80 images and they seem randomly. Images are loading up to 2.index but strangely subsequent indexes are not loading. Something is blocking the images but I can't find it, I don't see any 200 OK or HTTP status code related to the images and also I don't see any error or warning messages. If I change to the normal "<img" tag, everything is fine. So `<amp-img` tag doesn't load images after 3.image. I know it's weird but that's exactly the case :) Are there any limits or something for `<amp-img`? 

![carousel](https://i.stack.imgur.com/lczLB.gif)

### Reproduction Steps

https://gurkantuna.com

### Relevant Logs

```shell
I have no any error or warning message.
```

### Browser(s) Affected

Chrome

### AMP Version Affected

2107170150000

**Comment by caroqliu** [comment]
It looks like `splide.js` is custom javascript and the page you are using it on is not valid AMP. Given the above the fact that `amp-img` only works on valid AMP documents and `<img>` is the preferred non-AMP alternative by Bento, this is considered to be outside the scope of `amp-img`'s intended use. Please feel free to update if you have any trouble using amp-img on a valid AMP page. I'll be closing the issue for now.

**Comment by g-u-r-k-a-n** [comment]
> It looks like `splide.js` is custom javascript and the page you are using it on is not valid AMP. Given the above the fact that `amp-img` only works on valid AMP documents and `<img>` is the preferred non-AMP alternative by Bento, this is considered to be outside the scope of `amp-img`'s intended use. Please feel free to update if you have any trouble using amp-img on a valid AMP page. I'll be closing the issue for now.

That's why I specifically mentioned another `amp-img` pictures are appearing perfectly except `splide.js`. But people use many 3.party libraries. If you wnat the truth AMP doesn't allow any custom spec. I have no concerne about valid for AMP. I mean this is a 'real' issue but it's ok you can close this issue. Thanks anyway.
