### ISSUE TITLE
<amp-analytics> is not providing client id in the next page using <amp-next-page> on google amp viewer

### ISSUE THREAD

**Issue by deprantik** [ampproject/amphtml#35488]
### Description

Hi anyone, I have an issue with clientId(<cookieName>) method in amp-analytics.
So, whenever I am opening our amp page in google amp viewer (i.e. from the google carousel / top stories), the first analytics call is providing clientId. But when we go to the next page in infinite scroll, it’s not providing the clientId anymore, leading to failure of analytics call.
This issue is not happening when we open the amp page on our website.

For further info please dm on Slack.

### Reproduction Steps

- Search for yourstory in mobile / mobile-size google.
- Select any article from the carousel
- 1st page analytics call is a success.
- Now scroll to the next page
- Now the next page amp-analytics call fails due to lack of client id.

**Comment by deprantik** [comment]
Hey @kristoferbaxter 

Any news on this issue? Our pageviews are getting affected. It'll  be awesome if this issue can be expedited.
Or if any temporary solution can be provided for now.

**Comment by dmanek** [comment]
@deprantik thanks for reaching out. Will investigate soon & update when I have something.

**Comment by deprantik** [comment]
When should we expect this fix to reflect on production or is there any change needed from our side?
