### ISSUE TITLE
Can we customize google map in amp.

### ISSUE THREAD

**Issue by gskaushal92** [ampproject/amphtml#35519]
### Description

I have following requirement:
1. I want to load google map inside amp page.
2. On page load I will query json data and get multiple dynamic marker location.
3. I want to pin these marker to there location.
4. I want to draw a custom radius of xKM around my markers.
5. I want to add custom resize functionality for the circle.
6. Then on some user action, update the markers.
7. Drag and drop circle to any location and pin marker inside the circle.
 Similarly I have few more use cases, But I want to know, if and all these implementations are achievable using amp? 

### Reproduction Steps

I have following requirement:
1. I want to load google map inside amp page.
2. On page load I will query json data and get multiple dynamic marker location.
3. I want to pin these marker to there location.
4. I want to draw a custom radius of xKM around my markers.
5. I want to add custom resize functionality for the circle.
6. Then on some user action, update the markers.
7. Drag and drop circle to any location and pin marker inside the circle.
 Similarly I have few more use cases, But I want to know, if and all these implementations are achievable using amp?

**Comment by alanorozco** [comment]
If possible, you should render the widget inside an `amp-iframe`. Inside the loaded document, you can do whatever you want without using AMP, including loading the [Google Maps JS API](https://developers.google.com/maps/documentation/javascript/overview).

**Comment by gskaushal92** [comment]
ok. Thanks.
