### ISSUE TITLE
Error: An AMP component 'amp-lightbox-gallery' is using an invalid version. Use a valid version of this AMP component.

### ISSUE THREAD

**Issue by merakmarey** [ampproject/amphtml#35516]
### Description

Google AMP Website validator reports error in page:
An AMP component 'amp-lightbox-gallery' is using an invalid version. Use a valid version of this AMP component.

Preface: The extension is declared but not used.

Two separated issues. Google Search Console reports the original error. Invalid version.
Google Search Online validator report the "correct" issue, declared but not used.

Main question/bug. Why if it not used, constitutes an "invalid" AMP?

If a lightbox is injected at a later time, it will still be classified as invalid amp page?

### Reproduction Steps

https://lr.trapichero.com/c/monrovia/montserrado/buy-or-sell/shoes-and-clothes

**Comment by honeybadgerdontcare** [comment]
This seems very similar to #35505 and marking as duplicate. Please continue any discussion there.
