### ISSUE TITLE
google adsense Page-level ads 

### ISSUE THREAD

**Issue by telmanik** [ampproject/amphtml#3553]
I'm not sure if we are missing something. Or if this is not supported yet. We are looking to get working google adsense Page-level ads 

What I have tried.
`<amp-ad 
    type="adsense"
    data-ad-client="ca-pub-XXXXXXX"
   enable_page_level_ads: true
</amp-ad>`

**Comment by tdrl** [comment]
Page level ads aren't supported in AMP (and won't be).  They require dynamic modifications to the DOM that aren't allowed under AMP.

What are you trying to achieve?  Is there a different way you can get there?

**Comment by jridgewell** [comment]
Marking closed per https://github.com/ampproject/amphtml/issues/3553#issuecomment-225608460. We can reopen later if we can work around the dynamic modifications.

**Comment by telmanik** [comment]
It was a new feature by adsense. I was told there was a higher rate when it comes to the amount being earned.

**Comment by dine1504** [comment]
Does this code works in your AMP page?
