### ISSUE TITLE
[Story performance] Not load all page attachment images when loading story

### ISSUE THREAD

**Issue by mszylkowski** [ampproject/amphtml#35534]
### Description

When loading a story with page attachments, all the images inside all page attachments (independently of distance) get loaded.

### Reproduction Steps

Open https://story.merdeka.com/2378675/volume-14

Check the network tab:
![image](https://user-images.githubusercontent.com/22420856/128245783-e15bbecd-d115-40af-bb8a-d2aee2d42297.png)
It contains all the images from all the page attachments

### Browser(s) Affected

Chrome

### OS(s) Affected

Mac OS, others

### AMP Version Affected

latest

**Comment by gmajoulet** [comment]
Content should not be built nor loaded until the page attachment is open by a user.

Our code claims ownership over the components here: https://github.com/ampproject/amphtml/blob/a62b451774b56838259583f983fa73580b519a3a/extensions/amp-story/1.0/amp-story-draggable-drawer.js#L189-L201
And only get built in the `open` method here: https://github.com/ampproject/amphtml/blob/a62b451774b56838259583f983fa73580b519a3a/extensions/amp-story/1.0/amp-story-draggable-drawer.js#L589-L591

we also have a few `toggle(container, bool)` to ensure that the content is hidden - thus not built - until it's needed.

**Comment by gmajoulet** [comment]
cc @ampproject/wg-stories

**Comment by mszylkowski** [comment]
I think it should only get built either when the page for the attachment is loaded, or when the user swipes up (starts the interaction). If users start to interact with the story, the LCP stops being recorded (which is good), while loading the page attachment after the page is loaded will ensure the active page takes precedence. Story pages have `LOADED` events dispatched that we can listen to.

**Comment by processprocess** [comment]
I want to confirm that this is a problem and not an edge case we're fixing for the example story.

Would implementing this significantly improve user experience and LCP?

**Comment by mszylkowski** [comment]
With the publisher https://story.merdeka.com/ seems like most of the stories contain around 50 images and get loaded, but I've checked other stories with page attachments and it wasn't consistent whether the images were loaded from the beginning or not. At least with that publisher (I lab tested with [that story](https://story.merdeka.com/2378675/volume-14)) there was an 18% gain in performance from not loading the page attachments from the beginning. Sth like this won't improve all stories, only the ones with heavy page attachments (we can use this info to prioritize this fix).

**Comment by gmajoulet** [comment]
Regardless of LCP issues, it's an overall performance / UX / waste of user resources issue. We're using way too much bandwidth and CPU before it's actually needed. Potentially prerendering the content of page attachments even.

Your point is valid @processprocess, but in this case I'd argue we should bias our implementation towards performance, and only build/layout/load resources when the page attachment opens. It's ok if it's empty as we swipe up, till we release it, that's how it was designed back then before this regression happens.
