### ISSUE TITLE
Is deep linking supported in AMP

### ISSUE THREAD

**Issue by gskaushal92** [ampproject/amphtml#35535]
### Description

I am trying to implement deep linking in AMP but could not get relevant documentation and solution. Could you please let me know if this is supported or not?

### Reproduction Steps

I am trying to implement deep linking in AMP but could not get relevant documentation and solution. Could you please let me know if this is supported or not?

**Comment by gskaushal92** [comment]
any update on this? its urgent requirement in my project. could you guys please let me know if this is possible in amp?

**Comment by alanorozco** [comment]
Hi @gskaushal92 

What are you trying to accomplish exactly? If you'd like the possibility to open a resource entity within a native application as launched by the AMP document, please look into the [`<amp-app-banner>` component](https://amp.dev/documentation/components/amp-app-banner/).

**Comment by gskaushal92** [comment]
Hi @alanorozco ,

Let me explain you my use case,

For the single anchor tag , I will have three URL's, one for iOS app, one for android app and one URL for the webbrowser. e.g
`<a href        ="..."
data-app-iOS  ="..."
data-app-android  ="...">`
 So now if I open my web application in a browser and click on the anchor tag, If device is iOS then it will redirect me to iOS app, if device is android device, then it will take me to android app. for the fallback scenario when app is not installed either it should take me to app store or the webbrowser URL.

**Comment by gskaushal92** [comment]
I will have multiple anchor tag  inside amp custom elements. I need to apply deep linking on all the anchor tags. So is this possible in amp?

**Comment by gskaushal92** [comment]
any update on this issue?

**Comment by swissspidy** [comment]
I suppose [`<amp-app-banner>`](https://amp.dev/documentation/components/amp-app-banner/) comes closest to this

**Comment by alanorozco** [comment]
@gskaushal92 You should use `<amp-app-banner>`

**Comment by gskaushal92** [comment]
@kristoferbaxter  Thanks. I have done it in the same way you have explained using amp-script. It is working fine.
