### ISSUE TITLE
Bento: React warnings about incorrect DOM attributes / unrecognized props

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amphtml#35553]
### Description

**Invalid DOM property**

When using a Bento component such as `amp-base-carousel` in React development mode, React will emit lots of console warnings about invalid DOM properties.

The reason for this is the [difference between Preact and React](https://preactjs.com/guide/v10/differences-to-react/#raw-html-attributeproperty-names) in how they treat HTML attribute/property names.

Example: while Preact allows you to write `<div class="foo" />` and `<path stroke-width="1px" />`, React requires `<div className="foo" />` and `<path strokeWidth="1px" />`.

Solution: when creating the React version of a component, such props need to be renamed.

**Unrecognized DOM property**

The `Arrow` component in `amp-base-carousel` uses the `outsetArrows` prop to determine which class name to use and passes it down to the passed `Comp` component (defaulting to `DefaultArrow`).

Due to blindly passing this prop and using `{...rest}` in `DefaultArrow`, this prop ends up in the DOM, so React complains about it being unrecognized.

https://github.com/ampproject/amphtml/blob/4d6c9fae9127c16ac3133cd11eafa49edc6a727e/extensions/amp-base-carousel/1.0/arrow.js#L56

https://github.com/ampproject/amphtml/blob/4d6c9fae9127c16ac3133cd11eafa49edc6a727e/extensions/amp-base-carousel/1.0/arrow.js#L76

Solution: don't leak these to the DOM

**Receiving `false` for non-boolean attributes**

React expects passing `rtl="false" ` / `rtl="true"` instead of `rtl={false}` / `rtl={true}`, or simply `rtl={rtl || undefined}`. Otherwise you will get `Received false for a non-boolean attribute` warnings, as you can see in the log below.

Props @westonruter for initially reporting this at https://github.com/swissspidy/gutenberg-bento/issues/4

### Reproduction Steps

1. Use the `BaseCarousel` React component in development mode
2. See lots of browser console warnings 

### Relevant Logs

```shell
* Warning: Invalid DOM property `stroke-width`. Did you mean `strokeWidth`?
* Warning: Invalid DOM property `stroke-linejoin`. Did you mean `strokeLinejoin`?
* Warning: Invalid DOM property `stroke-linecap`. Did you mean `strokeLinecap`?
* Warning: React does not recognize the `outsetArrows` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `outsetarrows` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
* Warning: Received `false` for a non-boolean attribute `rtl`. If you want to write it to the DOM, pass a string instead: `rtl="false"` or `rtl={value.toString()}`. If you used to conditionally omit it with `rtl={condition && value}`, pass `rtl={condition ? value : undefined}` instead.
* Warning: Invalid DOM property `class`. Did you mean `className`?
* Warning: Received `false` for a non-boolean attribute `group`. If you want to write it to the DOM, pass a string instead: `group="false"` or `group={value.toString()}`. If you used to conditionally omit it with `group={condition && value}`, pass `group={condition ? value : undefined}` instead.
* Warning: Invalid DOM property `tabindex`. Did you mean `tabIndex`?
```

### AMP Version Affected

2107240354000

**Comment by westonruter** [comment]
cc @caroqliu

**Comment by westonruter** [comment]
> React expects passing `rtl="false" ` / `rtl="true"` instead of `rtl={false}` / `rtl={true}`, or simply `rtl={rtl || undefined}`. Otherwise you will get `Received false for a non-boolean attribute` warnings, as you can see in the log below.

Possibly related to the `loop` attribute: https://github.com/swissspidy/gutenberg-bento/issues/1 and https://github.com/ampproject/amphtml/issues/35555.

**Comment by caroqliu** [comment]
`outsetArrows`, `tabIndex`, and `rtl` issues have been resolved. All that remain for warnings for `BentoBaseCarousel` in react mode are the svg elements, which require the build step described in #35678.

**Comment by caroqliu** [comment]
Checking other react packages for non svg-related or `className` warnings:
- [ ] BentoAccordion
![Screen Shot 2021-09-23 at 10 29 47 AM](https://user-images.githubusercontent.com/10456171/134526522-90824b26-1b2f-42ad-8671-e29850b17126.png)
- [x] BentoDateCountdown
- [ ] BentoDateDisplay
![Screen Shot 2021-09-23 at 10 32 37 AM](https://user-images.githubusercontent.com/10456171/134526905-8d013e03-a346-4d50-bc99-3b362ffb74e2.png)
- [ ] BentoEmbedlyCard
![Screen Shot 2021-09-23 at 10 34 17 AM](https://user-images.githubusercontent.com/10456171/134527295-4a3b2558-7c54-4b62-9317-97a3eb659415.png)
![Screen Shot 2021-09-23 at 10 34 22 AM](https://user-images.githubusercontent.com/10456171/134527319-b4f261be-dfdc-4c09-bcdc-ca6b2fc825cd.png)
- [ ] BentoFacebook
![Screen Shot 2021-09-23 at 10 39 32 AM](https://user-images.githubusercontent.com/10456171/134528146-00ff647d-c43c-4722-bbc3-3adb88bb0b98.png)
![Screen Shot 2021-09-23 at 10 40 12 AM](https://user-images.githubusercontent.com/10456171/134528284-c233aa19-a96b-4c1d-99e9-ab8b815d2509.png)

- [x] BentoFitText
- [ ] BentoInlineGallery
![Screen Shot 2021-09-23 at 10 45 22 AM](https://user-images.githubusercontent.com/10456171/134529266-e3cc2806-73a2-4f6c-83b3-732f7cb987c5.png)
- [ ] BentoInstagram
![Screen Shot 2021-09-23 at 10 54 54 AM](https://user-images.githubusercontent.com/10456171/134531025-3860f4c6-0811-4fba-87dd-9e0c8731a666.png)
![Screen Shot 2021-09-23 at 10 54 58 AM](https://user-images.githubusercontent.com/10456171/134531039-9775b7ed-df76-4457-ab27-e5481797f7be.png)
- [x] BentoLightbox
- [ ] BentoLightboxGallery
![Screen Shot 2021-09-23 at 10 59 51 AM](https://user-images.githubusercontent.com/10456171/134531969-8af04a5f-1b8f-4f76-9b56-48234dd1d951.png)

- [ ] BentoSelector
![Screen Shot 2021-09-23 at 11 01 24 AM](https://user-images.githubusercontent.com/10456171/134532293-f40ee11e-1c29-46c9-818b-6dceb78c4922.png)

- [x] BentoSidebar
- [x] BentoSocialShare
- [ ] BentoSoundcloud
![Screen Shot 2021-09-23 at 11 06 22 AM](https://user-images.githubusercontent.com/10456171/134533193-25aac939-cbf7-454d-bda6-c43b3f201d67.png)
![Screen Shot 2021-09-23 at 11 06 25 AM](https://user-images.githubusercontent.com/10456171/134533197-0859e14b-019d-492f-8be9-5171f6a7cd54.png)

- [ ] BentoStreamGallery
![Screen Shot 2021-09-23 at 10 49 12 AM](https://user-images.githubusercontent.com/10456171/134530008-6a91db7f-1506-490c-90b1-1b278d55cf07.png)
- [ ] BentoTimeago
![Screen Shot 2021-09-23 at 11 07 46 AM](https://user-images.githubusercontent.com/10456171/134533430-164bab4c-a1b6-4879-9a02-7ecf14620915.png)
- [ ] BentoTwitter
![Screen Shot 2021-09-23 at 11 08 42 AM](https://user-images.githubusercontent.com/10456171/134533602-8c489f1a-4759-4fd5-b9d6-154b4cf645cc.png)
![Screen Shot 2021-09-23 at 11 08 47 AM](https://user-images.githubusercontent.com/10456171/134533613-d9d18ca5-a03c-41e7-9eb8-acf268886bd7.png)
![Screen Shot 2021-09-23 at 11 08 38 AM](https://user-images.githubusercontent.com/10456171/134533654-25aa04d6-7051-455c-b676-34d1dd7c1262.png)
- [ ] BentoVideo
![Screen Shot 2021-09-23 at 11 10 09 AM](https://user-images.githubusercontent.com/10456171/134533928-1b0e9374-641c-46d6-af1e-fa8970cd259d.png)
- [ ] BentoVideoIframe
![Screen Shot 2021-09-23 at 11 11 24 AM](https://user-images.githubusercontent.com/10456171/134534166-2ed06f71-dd7f-4458-af1b-7ae92b31fe58.png)
![Screen Shot 2021-09-23 at 11 11 31 AM](https://user-images.githubusercontent.com/10456171/134534181-456d60a5-deaa-4106-85b0-ddc5e3b193f5.png)
- [ ] BentoVimeo
![Screen Shot 2021-09-23 at 11 12 27 AM](https://user-images.githubusercontent.com/10456171/134534353-107f3a45-33ea-4a97-bc7e-06597f415fde.png)
![Screen Shot 2021-09-23 at 11 12 33 AM](https://user-images.githubusercontent.com/10456171/134534367-757969c8-b51e-4d63-99f5-0fe6c15f89ef.png)
- [ ] BentoWordpressEmbed
![Screen Shot 2021-09-23 at 11 14 43 AM](https://user-images.githubusercontent.com/10456171/134534775-7990a8d4-0178-4cb7-b8a5-357798a751f7.png)
![Screen Shot 2021-09-23 at 11 14 47 AM](https://user-images.githubusercontent.com/10456171/134534780-7c4f314d-fd66-47d0-bdfb-9fb0c1dd75ab.png)

- [ ] BentoYoutube
![Screen Shot 2021-09-23 at 11 15 38 AM](https://user-images.githubusercontent.com/10456171/134534913-79be4d5f-41cf-4810-9c7f-2d4e59b7ed1d.png)
![Screen Shot 2021-09-23 at 11 15 40 AM](https://user-images.githubusercontent.com/10456171/134534926-e54597e9-62db-4f7c-a1bc-409ba2afced6.png)
