### ISSUE TITLE
Bento: Consider shipping custom elements via npm

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amphtml#35554]
### Description

While a Bento React/Preact component can be consumed via npm, the custom element version can be loaded from the CDN. For npm, one will be locked to a specific version as per the `package.json`/`package-lock.json` file, whereas the CDN version is evergreen.

When not updating the npm packages frequently, the two versions will get out of sync quickly.

Example: I am building [a WordPress plugin](https://github.com/swissspidy/gutenberg-bento) with a custom [Gutenberg](https://wordpress.org/gutenberg/) block with a carousel, using `@ampproject/amp-base-carousel`. If my users don't update the plugin in a very long time, the React component I ship with the plugin will become super old, but the web component on the frontend is up-to-date. There could be visual disparity or other differences between the two, which could cause confusion and perhaps even bugs.

Another issue is that some users don't want their components to be loaded from a CDN but instead want to load them from their own server.

For me as developer there's currently no easy way to offer that, because the custom element is not shipped via npm. If it were, then I can just bundle it with my plugin together with the React component.

### Alternatives Considered

Developers could manually download the JS&CSS from the CDN and put it in their code base and hope that it's the same version as the one they got from npm.

**Comment by kristoferbaxter** [comment]
As I understand it, this is currently planned but not yet shipped.

**Comment by caroqliu** [comment]
For reference, #34820 is the first step towards this effort.

**Comment by samouri** [comment]
@swissspidy, which format for CE distribution makes more sense from a Gutenberg block perspective:

**script exports installer function** 
This is the design @caroqliu describes above. It provides flexibility with choosing _when_ the element is installed.

**script automatically installs component**
```html
<head>
  <!-- Optionally include CE polyfill script -->
  <script async src="cdn-bento-carousel.js"></script>
</head>
<body>
  <bento-carousel>....</bento-carousel>
</body>
```

**Comment by swissspidy** [comment]
Great question! I thin option 1) makes most sense as it allows the block to install the element only when needed and makes it testable, too.

**Comment by westonruter** [comment]
Why not both? I can see both being useful. The first case would be useful especially when you may want to create a bundle with multiple components and have a build process set up to do so. The second case would be great for simple use cases or when there is no build process in place. Both would be used in the WordPress world.

**Comment by samouri** [comment]
> Why not both? 

Thats what we'll do then

**Comment by swissspidy** [comment]
Finally got around to do some testing and things appear to be working as expected!

In my [demo project](https://github.com/swissspidy/gutenberg-bento) I added an opt-in for self-hosting the Bento script. For that, I created a custom script that imports `web-component.js` and calls `defineElement()`. I then load the web component JS + CSS manually.

And when not self-hosting, I just load the https://cdn.ampproject.org/bento.js runtime plus the https://cdn.ampproject.org/v0/bento-base-carousel-1.0.js script

**Comment by kvchari** [comment]
@swissspidy please note that the npm package name has changed and your code/documentation may have to change accordingly. The new package names are in the format: `@bentoproject/foo` (as opposed to `@ampproject/amp-foo`). In your case, that'd be `@bentoproject/base-carousel`.

**Comment by swissspidy** [comment]
Sweet! I was looking forward to that change but didn't know the new namespace was already in place! Will update right away.
