### ISSUE TITLE
More Story amp-story-consent configuration 

### ISSUE THREAD

**Issue by justin-lagtapon-crowdriff** [ampproject/amphtml#35556]
### Description

Our team is looking to implement the amp-story-consent for stories however the default ux is not meeting our standards.  It's potentially forcing us to purchase a supported consent management software just to get the capabilitities.

1. Ability to change the logo on the default UI
2. Ability to not display a logo on the default UI
3. Ability to display more than 1 external link
4. Ability to change the background colours or fonts
5. Ability to add more buttons, such as to request have data removed or retrieved

### Alternatives Considered

advanced user consent flows did not work

**Comment by sanggonlee** [comment]
Just to add to this, even just an ability to hide the logo would be a huge win for us.

We can open a pull request if you don't mind a hand.

**Comment by newmuis** [comment]
It would be helpful to provide an [intent to implement](https://github.com/ampproject/amphtml/issues/new?assignees=&labels=INTENT+TO+IMPLEMENT&template=intent-to-implement.yml) before starting any implementation here.  We will likely need UX input on this, as it may have ecosystem implications.

The publisher logo is considered to be a signal to users as to who has published the story.  If you are able to, can you provide some insights as to why the displaying the publisher logo does not meet your needs?

/cc @ryanwarrender @hongcatlover

**Comment by justin-lagtapon-crowdriff** [comment]
The publisher logo in our instance is a bit misleading for out use case.  Our platform allows creators to create and publish stories on our domain.  Thus, the cookie consent our readers are giving consent is for our domain and not the publisher's.  ie: the publisher has no control over the cookie and privacy policy.  It's akin to going to instagram and seeing my logo on the instagram's privacy/cookie consent.

Ideally, we'd have the option to either not display the publisher logo OR change the logo to be our domain's logo.

**Comment by newmuis** [comment]
That makes sense, though we do already have this distinction in story metadata today.

Using the example that you have mentioned, Instagram should be considered the "publisher" of the story (the [`publisher`](https://amp.dev/documentation/components/amp-story/#publisher-(required)) and [`publisher-logo-src`](https://amp.dev/documentation/components/amp-story/#publisher-logo-src-(required)) metadata fields), and the individual user should be considered the "entity" for the story (the [`entity`](https://amp.dev/documentation/components/amp-story/#entity-(optional)), [`entity-logo-src`](https://amp.dev/documentation/components/amp-story/#entity-logo-src-(optional)), and [`entity-url`](https://amp.dev/documentation/components/amp-story/#entity-url-(optional))).

Does this make sense?

(also /cc @warrenders who I failed to cc last time)
