### ISSUE TITLE
I2I: Allow amp-form in Story Page Attachments

### ISSUE THREAD

**Issue by coreymasanto** [ampproject/amphtml#35569]
### Summary

We are expanding story page attachments to support forms so that readers can submit input fields.

Constraints:
1. To prevent form input from interfering with tappable interactions (e.g., story page navigation), forms will _only_ be allowed within story page attachments.
2. For security purposes, the publisher's domain will automatically be visible in the header of any page attachment that contains a form.

![forms_in_attachments_mock1](https://user-images.githubusercontent.com/2376601/128729507-967b0c7f-badc-4eed-8e5c-1885d09e0fa8.png)

### Motivation

The [amp-form](https://amp.dev/documentation/components/amp-form/) component is currently disallowed in stories, but its addition would allow creators to securely engage with and gather information from their users. Once allowed, forms will become the primary method of communication between creators and their users.

**Open Questions:**
All questions are currently resolved.

**Resolved Questions:**
1. Should we display the domain in the headers of all page attachments, or only page attachments containing forms?
_Only page attachments that contain forms should display the domain._

2. Should we require that the domain is an HTTPS URL, or is it sufficient that the form’s data is sent to an HTTPS URL? Or both/neither? And does the answer here mean that we should display the site’s protocol as well as it’s domain?
_We will not restrict this feature based on the publisher domain, and we will not display the protocol along with the domain._

3. How do we display domain names that are too long to fit in the header?
_We will fit the domain name on a single line, using an ellipsis to truncate names that are too long._

4. Should we redirect users to the next story page upon successful form submission?
_We should not redirect users to the next page. Instead, the expected flow is for users to swipe the page attachment down and then continue the story navigation themselves._

5. What will the UX be for the soft keyboards on mobile? Should the keyboard overlap the page attachment or push it upwards?
_The soft keyboard behavior is primarily system dependent: iOS keyboards push the page upwards whereas Android keyboards overlap the page._

6. Should we commit to showing the padlock icon to the left of HTTPS domains?
_We will not display the padlock icon because AMP forms are already required to send data to HTTPS endpoints. We do not yet have the UXR to support the inclusion of the padlock, and it would confuse users if we later decide to remove the padlock after initially including it. Conversely, we could always revisit the padlock idea and begin including it in the future._

7. Should form input be preserved or reset upon page attachment dismissal?
_The input will be preserved, to prevent cases where the user closes the page attachment with the intent to return to the form (e.g., the user accidentally closes the attachment or they close the attachment in order to briefly refer to information on the story page)._

8. Should publishers be able to specify the `submitting`, `submit-success`, and `submit-error` states for their attachment forms?
_For the initial release of this feature, we will provide default states that will be used by every page attachment form. These default states will be used in place of any submission response attribute element that the user has not included within the form._

### Launch Tracker

**Implementation Tasks**
- [x] Update amp-story-page-attachment.js to display the domain in its draggable drawer’s header, if it contains an amp-form child element
- [x] Update the domain display logic to account for domain names that are too long to fit within a single line of the header

**Testing Tasks**
- [x] Verify that amp-form’s many features (i.e., custom validations and attributes) work properly within the context of a story
- [x] Verify that unit tests and visual regression tests provide adequate coverage (and add more tests, if necessary)
- [x] Fix all launch-blocking bugs found during the previous testing steps
- [x] Implement V0 default success/failure validation states to appear beneath the form upon submission
- [x] Create new QA test for forms in stories

**Release Tasks**
- [x] Create an Intent to Ship for allowing forms within page attachments
- [x] Add `form` and related elements to the validator as an allowed descendant of page attachments

### Notifications

/cc @ampproject/wg-approvers
/cc @ampproject/wg-stories

**Comment by newmuis** [comment]
Looks like the cc didn't go through.

/cc @ampproject/wg-approvers
/cc @ampproject/wg-stories

**Comment by processprocess** [comment]
My 2cents:

> Should we redirect users to the next story page upon successful form submission?

I don't think so since it's unrelated to the user action.
I think showing the "Thank you" message in the attachment and letting the user close it manually is good.

> Should we commit to showing the padlock icon to the left of HTTPS domains?

I think it could help visually communicate a secure connection so I think it's okay. I wonder if we should show the http:// or https:// prefix in the preview URL also.

**Comment by gmajoulet** [comment]
@processprocess is it ok if the content of the page-attachment is dynamically resized? Will the page-attachment drawer height automatically adapt?

**Comment by processprocess** [comment]
> @processprocess is it ok if the content of the page-attachment is dynamically resized? Will the page-attachment drawer height automatically adapt?

It will adapt automatically:

https://user-images.githubusercontent.com/3860311/128920946-b202168d-41dd-4e74-885a-ec58644e2eba.mp4

**Comment by Shohelorg** [comment]
Hi

**Comment by newmuis** [comment]
Hey!
