### ISSUE TITLE
Error	Custom JavaScript is not allowed.

### ISSUE THREAD

**Issue by vaibhavsingh719** [ampproject/amphtml#35564]
### Description

no problem on my website but showing an error
Error	Custom JavaScript is not allowed.
check this [sheet](https://docs.google.com/spreadsheets/d/1X58Hw-JxsoiMuPqC2XYd3zp1xtOCMJeS9LGtr92lLSk/edit?usp=sharing)

### Reproduction Steps

https://docs.google.com/spreadsheets/d/1X58Hw-JxsoiMuPqC2XYd3zp1xtOCMJeS9LGtr92lLSk/edit?usp=sharing

### Relevant Logs

```shell
JavaScript console messages
3 messages

Info
30:09.000
Powered by AMP ⚡ HTML – Version 2107240354000 https://cricfobia.com/category/cricket/ipl-2020/?amp
https://cdn.ampproject.org/v0.mjs:6

Error
30:19.000
Access to fetch at 'https://pagead2.googlesyndication.com/getconfig/ama?client=ca-pub-2480932303445617&plah=cricfobia.com&ama_t=amp&url=https%3A%2F%2Fcricfobia.com%2Fcategory%2Fcricket%2Fipl-2020%2F&__amp_source_origin=https%3A%2F%2Fcricfobia.com' from origin 'https://cricfobia.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
https://cricfobia.com/category/cricket/ipl-2020/?amp:0

Error
30:19.000
[amp-auto-ads] amp-auto-ads config xhr failed: Error: XHR Failed fetching (https://pagead2.googlesyndication.com/...): Failed to fetch​​​
https://cdn.ampproject.org/v0.mjs:2
```

### OS(s) Affected

linux 

### Device(s) Affected

website

### AMP Version Affected

2.1.3

**Comment by swissspidy** [comment]
Hi there, for questions related to the AMP WordPress Plugin, please ask in the [support forums](https://wordpress.org/support/plugin/amp/) or at the [amp-wp](https://github.com/ampproject/amp-wp) repository.

Note that custom JavaScript is not allowed in AMP, so you would need to remove that.

**Comment by kristoferbaxter** [comment]
Tried testing this URL for validation and it appears valid: did something change?

https://search.google.com/test/amp/result?id=1sGD1KmPGsZKU4F71OR-EQ

Will close this issue for now, but please reopen or comment if there is more here.
