### ISSUE TITLE
Incomplete test files being found during CI

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#35580]
### Description

https://github.com/ampproject/amphtml/pull/35500 renamed the `removeAutoplay` to `removeAutoplay_`. In the same commit, there exists https://github.com/samouri/amphtml/blob/363f2bbad12f74d5699451350685e9e6479dfc66/extensions/amp-carousel/0.1/test/test-slidescroll.js, which still references `removeAuotplay` and tries to stub it. This causes a test failure.

The only thing I can think of is that `extensions/amp-carousel/0.1/test/test-slidescroll.js` was not found by the test grep, and so it didn't fail.

### Reproduction Steps

1. `git checkout 6c7a2f0` (the squash commit)
2. npx amp unit --files 'extensions/amp-carousel/0.1/test/test-slidescroll.js'

### Relevant Logs

```shell
TypeError: Attempted to wrap undefined property removeAutoplay as function
    at wrapMethod (home/circleci/project/node_modules/sinon/lib/sinon/util/core/wrap-method.js:114:21)
    at Function.spy (home/circleci/project/node_modules/sinon/lib/sinon/spy.js:180:16)
    at Sandbox.spy (home/circleci/project/node_modules/sinon/lib/sinon/sandbox.js:383:35)
    at _callee22$ (home/circleci/project/extensions/amp-carousel/0.1/test/test-slidescroll.js:918:47)
    at tryCatch (home/circleci/project/node_modules/fetch-mock/es5/client-bundle.js:1291:52)
    at Generator.invoke [as _invoke] (home/circleci/project/node_modules/fetch-mock/es5/client-bundle.js:1521:34)
    at Generator.next (home/circleci/project/node_modules/fetch-mock/es5/client-bundle.js:1346:33)
    at asyncGeneratorStep (home/circleci/project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:20)
    at _next (home/circleci/project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
```

**Comment by jridgewell** [comment]
> Could it be that when all unit tests are run, test-slidescroll.js doesn't fail as expected? (This is a problem, but it's a different problem from the one stated in this issue.)

No, because it's failing in https://github.com/ampproject/amphtml/pull/35572's [All Unit Tests](https://app.circleci.com/pipelines/github/ampproject/amphtml/14347/workflows/e99aad2f-b276-47df-aa33-0cbc5400eef9/jobs/240377).

I notice that we're using a filelist filter, which makes me think the file isn't being properly found.

**Comment by rsimha** [comment]
> The only thing I can think of is that `extensions/amp-carousel/0.1/test/test-slidescroll.js` was not found by the test grep, and so it didn't fail.

This is the grep we use for unit tests. Line 104 should've caught both files, right?

https://github.com/ampproject/amphtml/blob/fe9f94ef3174f384ca412f7ea336db71f576ab49/build-system/test-configs/config.js#L100-L106

**Comment by jridgewell** [comment]
Yes.

**Comment by jridgewell** [comment]
It might be the `describe.only` in https://github.com/ampproject/amphtml/pull/35572/files#diff-9b3676d9c25334e20415c30c03e719b39f4dd075021dea5fc9202bf79432a8fdR906

**Comment by jridgewell** [comment]
Confirmed, removing the `.only` when running the test steps properly fails the test. We've been running only the amp-video test suite for over 2 weeks.

**Comment by rsimha** [comment]
> It might be the `describe.only` in [#35572 (files)](https://github.com/ampproject/amphtml/pull/35572/files#diff-9b3676d9c25334e20415c30c03e719b39f4dd075021dea5fc9202bf79432a8fdR906)

Oh yes, can confirm this is the cause. We normally have ~12,000 unit tests run across 6 shards of approximately 2000 tests each. The PR build for #35500 ran only ~10,000 tests, with one shard running only [three tests](https://app.circleci.com/pipelines/github/ampproject/amphtml/14137/workflows/7add8090-a32f-4f0e-9b4d-5fd431705dfb/jobs/234990/parallel-runs/5?filterBy=ALL&invite=true#step-114-61), which presumably are the same three tests in the `describe.only` block.

**Comment by jridgewell** [comment]
This is fixed now that #35572 is merged. I'll leave for you to close given https://github.com/ampproject/amphtml/issues/35580#issuecomment-895587167

**Comment by rsimha** [comment]
Glad this is fixed. I can take care of https://github.com/ampproject/amphtml/issues/35580#issuecomment-895587167 separately.

**Comment by samouri** [comment]
Don't we have an eslint rule against merging a `only`? If we don't, should we?

**Comment by rsimha** [comment]
Thanks for poking this thread, @samouri. Not tracking separately, but will send out a PR today to persist the filelist as a test artifact.
