### ISSUE TITLE
amp-story-social-share doesn't quite render the correct amp-social-share

### ISSUE THREAD

**Issue by giovanniiskandar** [ampproject/amphtml#35590]
### Description

the `sharedProviders` that's being passed trough `amp-story-social-share` won't be translated quite expectedly in case if we have a non-configured providers in it with `data-share-endpoint` defined.

### Reproduction Steps

`
{
    "bookendVersion":"v1.0",
    "shareProviders":[
      "twitter",
      "pinterest",
      "linkedin",
      "tumblr",
      "email",
      "sms",
      {
        "provider": "test",
        "data-share-endpoint": "https://www.google.com",
        "image": "https://amp.dev/static/samples/img/story_dog2_portrait.jpg",
        "data-param-text": "test"
      }
    ]
  }
`
the json below will translate into this
![image](https://user-images.githubusercontent.com/49144361/128895495-fe960019-f648-4cbc-b00d-b6e963499e20.png)

i took a look at the respective line of code, i think the logic doesn't cover the requirement quite well. like if i had a `data-share-endpoint` with a non-configured providers passed from `amp-story-social-share`. it will translate to `data-param-data-share-endpoint` attribute for the respective `amp-social-share` element.

`extensions/amp-story/1.0/amp-story-share.js`
![image](https://user-images.githubusercontent.com/49144361/128895635-31a517f3-f440-46e4-bc41-105aa8641d97.png)

### Browser(s) Affected

Chrome

**Comment by gmajoulet** [comment]
We should support the following list of attributes: https://amp.dev/documentation/components/amp-social-share/#attributes

cc @ampproject/wg-stories

**Comment by giovanniiskandar** [comment]
guys, would you like to consider moving it up to like p1 or p2 at least? the reason is i can't find any work around for this issue if we're using `amp-story`. since the only way to have share functionality is through this `amp-story-social-share` alone.

in my case, we need to override the `data-share-endpoint` from `whatsapp` lets say. and since there's no way to override the `data-share-endpoint` of `pre-configured` type. my next option is creating a new `non-configured-type` (this won't work due to mandatory `data-share-endpoint`, and we couldn't set it due to this bug).

and even if i want to take a workaround by using custom modal with either utilizing `amp-lightbox` or `amp-bind`, i don't think it's allowed to do
![image](https://user-images.githubusercontent.com/49144361/128958394-a2636bd8-bf64-4038-9cf8-f3dd03416b76.png)

**Comment by giovanniiskandar** [comment]
ohh, the reason of why would i even need to override the whatsapp `shareEndpoint`, is this endpoint `'https://api.whatsapp.com/send'` won't work if my amp page is on webview. it will try to reach that url on the webview and won't reach the app on the phone

**Comment by newmuis** [comment]
I'm not certain how soon we'd be able to get around to this, but @giovanniiskandar if you're willing to contribute the code, it would certainly be welcome!  I suspect the code you've provided in the screenshot is correct, and you'd just need to check the attributes listed by @gmajoulet above.

If not, that's okay too; it will get picked up as part of our normal triage process, but that's certainly the fastest way to get it expedited.

**Comment by gmajoulet** [comment]
+1 to what @newmuis, happy to help you if you decide to write this code yourself. [This guide](https://github.com/ampproject/amphtml/blob/main/docs/contributing-code.md) is a good place to get started.

> the reason of why would i even need to override the whatsapp shareEndpoint, is this endpoint 'https://api.whatsapp.com/send' won't work if my amp page is on webview

You should be able to configure your webview to decide where URLs should open, if that solves your issue.

**Comment by giovanniiskandar** [comment]
understand @newmuis @gmajoulet  
sure, it seems like a minor adjustment, i'll give it a shot.
what should i do now? should we like mark this issue as in progress or something while i'm taking a look on the guide

**Comment by giovanniiskandar** [comment]
it doesn't quite completely explained here, for the pre-configured one, are the base attributes allowed to be overriden?
https://amp.dev/documentation/components/amp-social-share/#attributes
`
"shareProviders":[
      "twitter",
      {
        "provider": "whatsapp",
        "data-share-endpoint": "https://www.google.com"
      }
    ]`
    
let's say this is the JSON, should the `data-share-endpoint` override the default `data-share-endpoint` of the pre-configured type (whatsapp)?

**Comment by gmajoulet** [comment]
We should be consistent with what non Story AMP does. I don't really see a need to override the `data-share-endpoint` if it's already pre-configured though?

**Comment by giovanniiskandar** [comment]
hmm i see, i agree on that point. it need additional handler tho, cos on the initial implementation, it doesn't correctly generate attribute `data-share-endpoint` and generates `data-param-data-share-endpoint` instead. so this 'accidentaly' prevent the user to override `data-share-endpoint` from the JSON passed

**Comment by gmajoulet** [comment]
The PR you sent looks good to me : )) Let's address the one comment about backwards compatibility and move forward with it. Thank you for contributing! We really appreciate the help

**Comment by giovanniiskandar** [comment]
Hmm wait, i found another issue. now that we could provide the non-configured one and pass the `data-share-endpoint`, it's complaining about the custom type doesn't have any localized string id
![image](https://user-images.githubusercontent.com/49144361/129210060-46516342-f5e3-4aa2-99e9-83bdc76e4644.png)
![image](https://user-images.githubusercontent.com/49144361/129210120-29a81591-3faf-4dc1-bd93-be7f24a8160a.png)

**Comment by giovanniiskandar** [comment]
ohh i think i get it. i'll update the PR after getting my dinner

**Comment by giovanniiskandar** [comment]
i've updated the PR, it's now showing the non-configured one without error, yea
![image](https://user-images.githubusercontent.com/49144361/129217677-84385c2d-c439-4931-babe-d5ee661897fb.png)

**Comment by giovanniiskandar** [comment]
hi @gmajoulet, please remember to check my latest update on the PR when possible

**Comment by cantarino** [comment]
Hi there! I'm having a similar issue to the one described - has it been fixed?

**Comment by ychsieh** [comment]
The PR mentioned here(#35636) never gets merged and become obsolete. You can review the currently supported provider [here](https://github.com/ampproject/amphtml/blob/main/extensions/amp-story-share-menu/0.1/amp-story-share-menu.js#L46-L54). If you don't find the one you want, I believe the current best way to add a new provider is to send out a PR that:
1) sets the share text in different languages(follow instructions [here](https://github.com/ampproject/amphtml/blob/c02b605831642ea7aa0ec2b39791748faa3a723f/extensions/amp-story/1.0/_locales/README.md)) 
2) sets the share icon including background
3) sets the data-share-endpoint with other necessary data-param-* correctly

Closing this issue as this becomes obsolete. But feel free to send out the PR and we are happy to review it!
