### ISSUE TITLE
Validator: <amp-fx-flying-carpet>

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#3559]
https://github.com/ampproject/amphtml/pull/3118

**Comment by ericlindley-g** [comment]
@Gregable  Slotting in backlog, but feel free to correct/update the milestone as needed

**Comment by dvoytenko** [comment]
I'll upgrade to current since the component is otherwise ready, I believe.

**Comment by Gregable** [comment]
Ah, I hadn't seen this one yet. Documentation [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-fx-flying-carpet/amp-fx-flying-carpet.md) it seems.

**Comment by Gregable** [comment]
https://github.com/ampproject/amphtml/pull/3629 includes this. It'll be deployed soon.

**Comment by jridgewell** [comment]
@Gregable I don't see anything related to Flying Carpets in #3629.

**Comment by Gregable** [comment]
Good catch, looks like we messed up the commit, my bad. Johannes has a fix in https://github.com/ampproject/amphtml/pull/3664

**Comment by jridgewell** [comment]
Thanks guys!

**Comment by Gregable** [comment]
This change is now live on cdn.ampproject.org
