### ISSUE TITLE
carousel image does not bounce back into place after swiping out of bounds.

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#356]
port forwarded to my nexus 5. when i swipe on the new carousel with the updated gesture code it sometimes get into this state where i swipe on the last one (or first) and it gets stuck in the middle.
might be related to the horizontal scroll or emulation. feel free to close if not reproducible.

<img width="483" alt="screen shot 2015-09-29 at 4 37 34 pm" src="https://cloud.githubusercontent.com/assets/354746/10181197/dabdd69c-66c9-11e5-9aea-5ac75507e7d6.png">

**Comment by rudygalfi** [comment]
@erwinmombay Do you think you can reproduce this, or should we close this out?

**Comment by rudygalfi** [comment]
@erwinmombay Is this WIP, or should we bump from the Feb 19 milestone?

**Comment by erwinmombay** [comment]
@rudygalfi definitely bump this out. i wasn't able to reproduce the last time i checked.

**Comment by ericlindley-g** [comment]
Closing until we can reproduce the issue again
