### ISSUE TITLE
Deploy a nightly build server on Heroku

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#3560]
It should be pushed automatically with latest code everyday.

It serves the following purposes:

- View examples and conduct manual test against the latest code anywhere without a local build.
- Serves as HTTPS endpoints that are required by some of our manual tests/examples. (See discussions here: #3522 ).

Let me know if this sounds helpful.

- [ ] We probably want to have an official Heroku account.
- [ ] Needs a SSL certificate for that Heroku domain.

**Comment by erwinmombay** [comment]
this should be super easy with a cron job in one of our workstations

**Comment by lannka** [comment]
Maybe this is even better: https://devcenter.heroku.com/articles/scheduler ?

**Comment by cramforce** [comment]
Awesome idea!

**Comment by ericlindley-g** [comment]
Whoops—didn't notice that you had modified the milestone, @cramforce. Pulling it back out

**Comment by lannka** [comment]
Do we have an ampproject official account on Heroku? If not yet, what email should I use to register? How the form should be filled up ;-)? @cramforce 

![Heroku signup](https://cloud.githubusercontent.com/assets/8496897/16287345/3dd4ce4e-3897-11e6-94a0-71ade1b3cf6b.png)

**Comment by cramforce** [comment]
Use whatever email address and put the credentials into our credentials store.

**Comment by erwinmombay** [comment]
you can also use the admin@ampproject.org email which is in our credentials store

**Comment by lannka** [comment]
Nightly build [deployed](http://amphtml-nightly.herokuapp.com/examples/everything.amp.max.html)!
