### ISSUE TITLE
Consider renaming the `--compiled` flag used by AMP testing tasks

### ISSUE THREAD

**Issue by rsimha** [ampproject/amphtml#35704]
### Description

AMP's testing tasks that require a fully built runtime currently use the `--compiled` flag to indicate minified JS (vs. unminified). This is a relic of the early days of the project when the two modes were "closure-compiled" vs. "babel-transformed". Today, this distinction has lost most of its meaning because we run babel transforms for both flavors.

I propose that we rename the `--compiled` flag to `--minified`.

### Alternatives Considered

- `--minified`: This is unambiguous, and matches up with other uses of the word (e.g. `options.minified` during compilation)
- `--prod`: While this indicates a production build, it reintroduces the confusion between the `prod` and `canary` configurations, both of which are applied to minified JS, depending on whether we're releasing to the beta channel or experimental channel.
- Do nothing and leave it as `--compiled`: The confusion will remain, when it can easily be rectified and documented.

**Comment by samouri** [comment]
My vote is for `minified`, for all the reasons you listed.
