### ISSUE TITLE
Render timeout waiting for service amp-story-render to be ready

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amphtml#35712]
### Description

Previously: #30783

Originally reported here: https://github.com/google/web-stories-wp/issues/8718

A user of the Web Stories WordPress plugin reported issues with the loading of `amp-story-player` on their site.

Figured it might be an issue with the player itself and not the plugin, so reporting it here.

### Reproduction Steps

1. Go to teacherph.com
1. Right-click anywhere on the page and select Inspect then click Console
1. Scroll down to the bottom of the page
1. See errors (screenshot attached)

### Relevant Logs

```shell
timeout waiting for service amp-story-render to be ready
```

### AMP Version Affected

2108052321001

**Comment by tejesh0** [comment]
Codepen demo which fails to open the webstory in lightbox with same console error: https://codepen.io/maenrique/pen/rNLyqXg

**Comment by tejesh0** [comment]
@swissspidy  Duplicate of #34271 ?

**Comment by swissspidy** [comment]
Oh I missed that one! Yes looks like a duplicate.
