### ISSUE TITLE
amp-sidebar: browser back button breaks the sidebar functionality

### ISSUE THREAD

**Issue by juliantoledo** [ampproject/amphtml#3573]
## Short description of your issue:
When clicking on a link in an amp-sidebar the browser back button brakes the amp-sidebar functionality

## How do we reproduce the issue?
1. Create a page with amp-sidebar (http://localhost:8000/)
2. Click on a link in the amp-sidebar (http://localhost:8000/newpage/)
3. On the new page click on the browser's back button
4. The browser keeps the # for example (http://localhost:8000/#) and the amp-sidebar stays closed and it cannot be opened again.

## What browsers are affected?
Chrome, it works on Safari and Firefox.

## Which AMP version is affected?
https://github.com/ampproject/amp-by-example/pull/173

**Comment by ericlindley-g** [comment]
Passing to @sriramkrish85 to take a look

**Comment by sriramkrish85** [comment]
@juliantoledo
https://ampskrish.herokuapp.com/test/manual/amp-sidebar.amp.html

Tried here seems to work fine on iOS chrome. Are you seeing any error on the console?

**Comment by sriramkrish85** [comment]
Tried on localhost too, (desktop chrome), seems to be working fine.

**Comment by juliantoledo** [comment]
I found that we had  href="#" on the sidebar button and that was braking it.
