### ISSUE TITLE
Whitelist Medium fonts

### ISSUE THREAD

**Issue by polastre** [ampproject/amphtml#3576]
Medium uses custom designed and licensed fonts that have select spacing rules (which we encode in CSS for our web clients). The CSS and font files are served from:

```
https://cdn-static-1.medium.com
https://cdn-static-2.medium.com
```

Each revision of our fonts is fingerprinted into a CSS file, such as the following example:
https://cdn-static-1.medium.com/_/fp/css/fonts-base.by5Oi_VbnwEIvhnWIsuUjA.css

This is a request to whitelist Medium's CDN for serving fonts to AMP clients.

cc @julien51 @paul-matthews @adewale

**Comment by cramforce** [comment]
Unless you want to make these available to non-Medium sites, I think this will not scale. The URLs have to be whitelisted in our CSP, which would be very spammy to pages that do not use it.

Any chance you can use `@font-face` in inline CSS instead? That would require no whitelisting.

**Comment by polastre** [comment]
@cramforce The CSS fonts are a 254kb file (compressed to 187kb during transit). That's larger than the 50,000 bytes allowed for inline CSS.

**Comment by cramforce** [comment]
@polastre I meant to reference actual font URLs from a font face rule (not inline them).

Note, that in AMP, because there are only inline styles and the script tags are all async, the problem of late font downloads goes away and thus one does not need to use the base64-in-CSS-file delivery for good performance.

**Comment by polastre** [comment]
@cramforce thanks, we'll give it whirl.

**Comment by julien51** [comment]
@cramforce would it be possible to also use `data-url` but have them not be accounted toward the 50K limit for stylesheets?

**Comment by cramforce** [comment]
@julien51 actually inlining them in the doc would be really bad.

Any chance you could just upload the font files to your CDN?

**Comment by julien51** [comment]
Sure! We'll do that!

**Comment by polastre** [comment]
No longer necessary, thanks @cramforce!
