### ISSUE TITLE
AMP validator forbids "style" attribute in <stop> svg element. 

### ISSUE THREAD

**Issue by nbeloglazov** [ampproject/amphtml#3578]
Please walk through the following steps for reporting an issue about AMP:
- Please ask general questions about AMP over on stackoverflow under the AMP HTML tag: http://stackoverflow.com/questions/tagged/amp-html
- Please ask/post questions/problems related to Google Search in Google's AMP forum: https://goo.gl/utQ1KZ
## Short description of your issue:

AMP validator disallows "style" attribute in <stop> svg element. 

Error:
`The attribute 'style' may not appear in tag 'radialgradient > stop'. (see https://www.ampproject.org/docs/reference/spec.html#svg)`
## How do we reproduce the issue?

http://jsbin.com/karukoyoqi/edit?html,output
Open output in new window, add `#development=1` and refresh. 

According to https://www.ampproject.org/docs/reference/spec.html#svg 'style' attribute is allowed.
## What browsers are affected?

Validator issue. Probably all browsers? 
## Which AMP version is affected?

Version 1464987951323

**Comment by Gregable** [comment]
Good point. The spec also reads (https://www.ampproject.org/docs/reference/spec.html#html-attributes) that "The `style` attribute must not be used.". I'm guessing that the rule for svg elements trumps the rule for html attributes, but it would be good to get a confirmation on this. @cramforce @dvoytenko

**Comment by dvoytenko** [comment]
We have currently disallowed `style` on all elements: HTML/SVG. We have previously discussed that we may relax this rule for `SVG`. @cramforce any opinion on this?

**Comment by cramforce** [comment]
Could somebody point to a few example usages of style in SVG?

**Comment by nbeloglazov** [comment]
One example is what I already provided. Here is clearer version: http://jsbin.com/jamuyi/edit?html,output radialGradient creates shadow effect and <stop> used to control it.

**Comment by cramforce** [comment]
FMI: Is this subject to style CSP rules or independent?

On Tue, Jun 14, 2016 at 2:08 PM, Nikita Beloglazov <notifications@github.com

**Comment by dvoytenko** [comment]
FWICT the same CSP rules w.r.t. `style` attribute apply to SVGs. However, the argument here, I believe, is convenience. Most of SVG generators add `style` attributes to SVGs freely and refactoring them in classes is difficult at best.

**Comment by ericlindley-g** [comment]
@Gregable  Slotting in backlog, but feel free to correct/update the milestone as needed

**Comment by dvoytenko** [comment]
I'd like to make a decision on this in this milestone.

**Comment by nbeloglazov** [comment]
In our case we use svg as drop-in replacement for image icons as svg scale better. So they're pretty independent of the rest of the page and can be easily added/removed. Refactoring all styles to classes would be pretty painful indeed.

**Comment by Gregable** [comment]
Validation is trivial either way. If we don't change the validation rules, we should update the spec document.

There are plenty of html generators that generate snippets with inline styles for convenience. The same argument could also be made regarding html generated by any such tool. I don't mind allowing this, but it's definitely a pro: developer convenience, con: user experience.

**Comment by nbeloglazov** [comment]
btw, why style attributes are forbidden in HTML? Does it improve rendering performance when all styles are in one place in <head>?

**Comment by cramforce** [comment]
@nbeloglazov Reasons against style attribute

- Feasibility of using a CSP for styles without nonces (which can't be used in publicly cacheable docs)
- Can make doc very slow and bloated if overused
- No, good idea how to enforce limits of usage

Reasons pro:

- very convenient sometimes
- heavily used by SVG generation tools
- better semantic match for content dependent styles

**Comment by nbeloglazov** [comment]
> No, good idea how to enforce limits of usage
Can't you just calculate total size of style attributes in the doc? 

I see the reasons behind cacheability, but I think for some cases like [a4a](https://github.com/ampproject/amphtml/issues/3133) it doesn't matter as ad css is not extracted/cached on AMP servers?

**Comment by cramforce** [comment]
Alright. I'm not opposed to allowing style on SVG, because SVG is great and we want people to use it :)

**Comment by dvoytenko** [comment]
Sounds good. @Gregable can we do it then?

**Comment by Gregable** [comment]
NP

**Comment by Gregable** [comment]
One other concern. Is it possible to add CSS to an inline style tag which we wouldn't normally validate. For example, additional AT-Rules or http scheme URLs? If so, we may not want to allow this as we probably don't want the additional overhead of validating the CSS in every style attr on the page.

**Comment by dvoytenko** [comment]
No AT-Rules in inline styles. But http URLs might be possible. Let's dig a bit around SVG-specific CSS. I'll take a look. @Gregable please take a look as well.

**Comment by Gregable** [comment]
I took a read through https://www.w3.org/TR/SVG/styling.html#StylingWithCSS and didn't find anything referencing URLs in style attributes. Of course you can have a `<style>` tag in there, but we won't allow that anyway. @dvoytenko Have you found anything?

**Comment by cramforce** [comment]
`style="background: url(…)"` would definitely work. If we allow this, we'd have to apply the CSS rules here in the validator.

**Comment by Gregable** [comment]
I recommend not allowing this, considering.

**Comment by Gregable** [comment]
Closing for now as working-as-intended. Feel free to reopen if you disagree.

**Comment by nbeloglazov** [comment]
Sorry, I didn't get the final decision. Is "style" attribute allowed or not in svg?

**Comment by Gregable** [comment]
Not allowed.

**Comment by nbeloglazov** [comment]
:( I stopped paying close attention after https://github.com/ampproject/amphtml/issues/3578#issuecomment-227296112 

Is additional validation overhead is major concern here? I feel like you already parse everything and extracting and validating rare style attributes shouldn't be long? And I guess it's important only for a4a where validation must be done while ad being served.

**Comment by dvoytenko** [comment]
@Gregable @cramforce `style` in SVG containing an URL is not a very typical thing. I can't think of any SVG specific styles that do that. I think we should allow, but prohibit any sort of URLs in the `style`.

**Comment by cramforce** [comment]
Seems like a great compromise to me!

**Comment by tigt** [comment]
The `fill`/`stroke` attributes (among others) [can take external files](https://twitter.com/AmeliasBrain/status/760878586442059777), but using their relative-fragment form is the only way to apply patterns and gradients.

```html
<path style="fill: url(external.svg#id)"/>
```

...is equivalent to:

```html
<path fill="url(external.svg#id)"/>
```

**Comment by AmeliaBR** [comment]
If the concern is not having cross-links to HTTP URLs, disallowing the `style` attribute does not have any benefit.  As @tigt notes, most of the SVG-specific style properties can also be specified as attributes, and many of these take URLs.  Namely:

- filter
- mask
- clip-path
- fill
- stroke
- cursor
- marker and its longhands

That said, support for cross-file URLs in these properties (vs target fragments) is not universal, and support for cross-origin URLs is even more limited, so I suspect it would be very rare to link to URLs with different protocols.  But it is possible.

**Comment by nbeloglazov** [comment]
Any update on this bug?

**Comment by dvoytenko** [comment]
I'll assign it to the next milestone. @Gregable ping me directly if we need to discuss it more.

**Comment by Gregable** [comment]
I was on vacation for a couple weeks, but am now back. It sounds like we've concluded we want to allow the `style` attribute. It's unclear to me if we need to do extra work to disallow URLs in the attribute value or not. It sounds like the existing attributes already allow for URLs currently, so it may be a moot point to try to prevent them in the `style` attribute? On implementation: it's very straightforward to allow the `style` attribute, but a lot more tricky to check for all possible URL formats.

Please advise on the URL question. Thanks.

**Comment by dvoytenko** [comment]
I'd prefer if we could disallow URLs from style attributes here.

**Comment by AmeliaBR** [comment]
Would it really be that hard to implement the check for external references?

Basically, you are looking for any instance of `url(` that doesn't match `url([whitespace?quotationmark?]#`, in the `style` attribute or any of the SVG presentation attributes.

That's not a perfect parser: it could theoretically result in false positives like

- `content: "url(address)"` (not actually a URL, just a string); or

- `fill: url(this-document.html#gradient)`, where `this-document.html` is the file name for the current document, and so the property is actually equivalent to `fill: url(#gradient)` (a safe, same-document URL).

But those are rare enough that they wouldn't be major obstacles.  And the important point, for your security/performance concerns, is that you wouldn't get any false *negatives*.  If a URL starts with a #, it's going to be a same document cross-reference.

**Comment by Gregable** [comment]
I'm unsure if a regex test would be sufficient, but I'm not a CSS expert by any means. For example, would this succeed: ``` ur/* */l('http://example.com/') ```? or this: ```style="&#117;rl('http://example.com/')"```

We have a CSS parser in the validator already, that extracts URLs, so I think we should probably just use that on these fields. We just need to wire that code path in for these style attributes. 

It's a bit slow to run within javascript, as you might expect, so doing so will limit the places we can validate client-side. We may want to continue to disallow this within template sections and ads, for example, if we think we may want to validate either client-side in the future.

**Comment by AmeliaBR** [comment]
@Gregable Good points. If you've got a proper CSS parser test handling the URL testing, that is what you should use.  

You'll of course have to make a judgement call on the performance impacts of client-side validation. But either way, you should have the same rules for `style` attribute as for SVG presentation attributes.  There are also other attributes like `<use>` href that accept a URL.  Although in many cases they're currently restricted to same-origin, that may change in the future, and the browser may still create a fetch request to the other domain.

For reference, this is my best list of attributes defined in the SVG spec that reference a URL:

* https://svgwg.org/svg2-draft/linking.html#processingURL-validity

In addition, the `clip-path`, `mask`, and `cursor` properties, all now officially defined in other CSS specs, are available as [presentation attributes](https://svgwg.org/svg2-draft/styling.html#PresentationAttributes) in SVG.

**Comment by nbeloglazov** [comment]
Any update on this issue?

**Comment by Gregable** [comment]
not currently

**Comment by cramforce** [comment]
@dvoytenko and me discussed this. Anything to report here?

**Comment by dvoytenko** [comment]
@cramforce @nbeloglazov @Gregable The update here is that we will:

1. Update AMP Cache to rewrite URLs in `style` attributes. (b/34233580)
2. Then, we will allow `style` attribute in SVGs.

/cc @dknecht Depending on whether you do similar rewrites in the `<style amp-custom>`, you may also want to do the same.

**Comment by Gregable** [comment]
To clarify point 2, we will allow any attribute value for these `style` attributes.

**Comment by AmeliaBR** [comment]
For 

> Update AMP Cache to rewrite URLs in style attributes. (b/34233580)

Are you also able to rewrite the values of SVG presentation attributes?  (These should be run through the CSS parser/sanitizer as a CSS property value.)

**Comment by adelinamart** [comment]
@Gregable are we still considering this as an issue? Thanks

**Comment by dvoytenko** [comment]
Yes. Actively being developed right now.

**Comment by Gregable** [comment]
This is live in the most recent release.
