### ISSUE TITLE
Brightcove player (amp-brightcove) doesn't get resized properly on Android devices 

### ISSUE THREAD

**Issue by antseburova** [ampproject/amphtml#3579]
Hi guys,

Brightcove player (amp-brightcove) doesn't get resized properly on Android devices after changing views from portrait to landscape. I found the issue not only in my project, but on one of the Brightcove customers' sites as well: http://www.lastampa.it/2016/02/24/edizioni/vercelli/carcoforo-il-paese-con-abitanti-che-sopravvive-grazie-a-facebook-eOH6evfEIMTWMkUMLMO53N/amphtml/pagina.amp.html

So, to reproduce the issue, please follow the next steps:
1. Visit the above mentioned url using an Android device (portrait view)
2. Scroll to the brightcove video player 
3. Change the device orientation to landscape. 

As a result, you will be able to see that the black box stretched out to the available width, but the video itself remained the same width as it was on the portrait view. It happens due to the fact that the <body>'s width is not properly calculated.

So far I could see the described above issue on Android devices (Nexus 5X) via Chrome. It seems to be okay on iPhones.

Please let me know if you have any questions.

Thanks,
Mila
![landscape-view](https://cloud.githubusercontent.com/assets/5235176/16058284/c8a7127c-324b-11e6-9db7-82d43fd24e6c.png)
![portrait-view](https://cloud.githubusercontent.com/assets/5235176/16058285/c8ab691c-324b-11e6-84fc-d2b3db763ca1.png)

**Comment by dvoytenko** [comment]
@mister-ben I checked and it looks like the `amp-brightcove` itself and its iframe get the correct size after resize, but the `video` inside is not resized. Do you know why? Are you processing resize events?

**Comment by mister-ben** [comment]
Odd, the player is stretching to fill the height (as the controls are at the bottom of the frame), just not the width. I'll look into it.

**Comment by stevenmcdonald** [comment]
I'm also seeing this on Safari on iOS, but only after rotating once, then rotating back (i.e. start on portrait, go to landscape, then go back to portrait or vice versa). It looks like a `style="width:...` attribute is added to the `<body>` tag inside the iframe on first rotation, and never removed or modified on subsequent rotations.

**Comment by mister-ben** [comment]
If you have the [plugin in the Brightcove player's configuration](https://github.com/ampproject/amphtml/blob/master/extensions/amp-brightcove/amp-brightcove.md#player-configuration) and republish the player (in Video Cloud), this should be resolved.

**Comment by antseburova** [comment]
Republishing the player worked for me! Thank you very much!

**Comment by jridgewell** [comment]
Sweet.
