### ISSUE TITLE
amp-story-auto-analytics is not setting the "pageview" event for Google Analytics

### ISSUE THREAD

**Issue by edoardofelici** [ampproject/amphtml#35837]
### Description

Google Analytics is not showing the page title of the web stories in the Landing Pages section. 

Navigating to the dashboard at **Behaviour > Site Content > Landing Pages** shows all the traffic to stories with a landing page of "(not set)". 

![image](https://user-images.githubusercontent.com/25923450/131089620-2f6484a9-e7a2-483f-a111-7629cfe79804.png)

Google Analytics reports the following error:

` A pageview hit must precede event hits in order for the event hits to include the page that they fire from. When event hits aren't preceded by a pageview, Google Analytics doesn't have the page for the event hits, so their page is (not set).`

I suspect the amp-story-auto-analytics [default config](https://github.com/ampproject/amphtml/blob/main/extensions/amp-story-auto-analytics/0.1/auto-analytics-configs.js) is not setting the "pageview" event, possibly because of a missing attribute in the config. 

I noticed that our Google Analytics used to properly register the pageview events when our analytics configuration object contained the "config" attribute below. This "config" key is missing in the current default config that the extension is using:

```
  vars: {
     gtag_id: GOOGLE_ANALYTICS_ID,
     config: {
         [GOOGLE_ANALYTICS_ID]: { "groups": "default" }
     }
  },
```

### Reproduction Steps

1. Visit a web story you have access to analytics for.
2. Load Google Analytics and go to **Behaviour > Site Content > Landing Pages** 
3. The "Landing Page" column should give a "(not set)" reading for the the web story traffic.

**Comment by bethanylang** [comment]
Hi all! Checking in here as we've received [another report about this in the Web Stories forum](https://wordpress.org/support/topic/the-landing-pages-report-has-a-not-set-entry/).

**Comment by adamdunnage** [comment]
Hi everyone, another instance of this in the Web Stories support forums. [See here](https://wordpress.org/support/topic/google-web-stories-6/).

**Comment by gmajoulet** [comment]
We identified the issue and a way to fix it, we're working on it.

**Comment by bethanylang** [comment]
Awesome, thank you for the update, @gmajoulet!
