### ISSUE TITLE
CSS issue

### ISSUE THREAD

**Issue by bansalUdit** [ampproject/amphtml#3584]
I have created a simple HTML page using AMP guidelines, but when I check that page with google toolbar AUDIT button that show me unused AMP classes.

How can I remove those with static html without using any package or any other stuff
Please help to get rid out of this.

**Comment by jridgewell** [comment]
Hi @bansalUdit, these classes are included by the [default AMP CSS](https://github.com/ampproject/amphtml/blob/master/css/amp.css) or one of the various extensions CSSes. You don't need to worry about these classes being unused, the high cachability of the CSS files will more than make up for the few extra bytes.

**Comment by bansalUdit** [comment]
thanks @jridgewell
