### ISSUE TITLE
🌸 Cherry-pick request for #35895 into #35886 (Approved)

### ISSUE THREAD

**Issue by mszylkowski** [ampproject/amphtml#35892]
### Issue (P0 Bug)

https://github.com/ampproject/error-reporting/issues/103

### Pull Request(s)

#35895

### Release Tracker(s)

#35886

### Channels

Beta / Experimental

### Formats

Websites

### Justification

Breaks `amp-date-display` component by failing to build.

### Verification Steps

Test `amp-date-display` on one of the browsers that don't support `formatToParts` (check [here](https://caniuse.com/?search=formatToParts))

### Impact

`amp-date-display` is broken for all documents [where the browser does not support `formatToParts`](https://caniuse.com/?search=formatToParts)

### Notifications

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers
/cc @alanorozco

**Comment by alanorozco** [comment]
I support this cherry pick

**Comment by jridgewell** [comment]
Approving the [rollbacks](https://github.com/ampproject/amphtml/pull/35895) for cherry-pick.
