### ISSUE TITLE
Tests broken in Chrome 93

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#35898]
**summary**
11 tests broke once our CI systems updated to Chrome 93. We should address this in two stages:

1. Skip all of the newly failing tests to unblock new code from merging (including a CP we'd like to get through). https://github.com/ampproject/amphtml/pull/35900
2. Fix the broken tests and unskip them

**skipped tests**
- [X] (8) Highlight handler 
- [ ] (1) amp-pan-zoom
- [ ] (1) 3p ampcontext.js
- [ ] (1) iframe-transport-client

**Comment by samouri** [comment]
@dmanek: would you be interested in fixing all of the tests `Highlight handler` tests that failed as part of the Chrome 93 release? I started giving it a go in https://github.com/ampproject/amphtml/pull/35897/files, but think you may have better context.

I can take the rest

**Comment by dmanek** [comment]
Started looking into this, but seems like you have the highlight handlers tests covered in #35897.

**Comment by dmanek** [comment]
Highlight handler tests are fixed.
