### ISSUE TITLE
Input element is hidden behind page attachment header when focused

### ISSUE THREAD

**Issue by coreymasanto** [ampproject/amphtml#35896]
### Description

In a story, when an input element has focus and it has been scrolled beyond the top of the viewport, typing text into the soft keyboard results in the page attachment view jumping to a position where the focused input element is viewable at the top of the attachment. However, due to the fixed header at the top of the attachment, this focused element and its contents are hidden behind the header until the user scrolls downwards to see it.

### Reproduction Steps

- Once [this PR](https://github.com/ampproject/amphtml/pull/35798) has been merged, go to http://0.0.0.0:8000/examples/amp-story/attachment.html on a local server on an Android or iOS device.
- On the story page with the text "two forms within large attachment", open the attachment and tap the text inputs at the top of the page attachment. The soft keyboard should open.
- Scroll downwards so that the focused input element is no longer visible
- Begin typing some characters via the soft keyboard
- Observe how the focused input element is hidden behind the attachment header

Desired result:
<img src="https://user-images.githubusercontent.com/2376601/131585578-3b6b3cbd-928a-4dbe-befd-c2fd281b70d1.jpeg" width="200px">

Actual result:
<img src="https://user-images.githubusercontent.com/2376601/131585590-e65e28b1-cc06-43f9-a0e7-dff09955aa30.jpeg" width="200px">

### OS(s) Affected

Android, iOS

**Comment by ychsieh** [comment]
Interestingly enough that it is only reproducible when you try it with the mobile simulator in the browser. Not reproducible with real mobile mode like on iOS or Android. In sum, it is not a real bug that the user can see. Closing it now.
