### ISSUE TITLE
Cannot access localstorage from amp-script using sandboxed mode

### ISSUE THREAD

**Issue by zshnr** [ampproject/amphtml#35902]
### Description

Hey all, 

I've been trying to access LocalStorage using the new-ish `sandboxed` mode of amp-script (introduced in PR #33643). However, while it should support LS access I can't seem to access localStorage. I've tried both a src file and inline scripts. 

The error I get in console is:

`localStorage is not defined.`

cc: @samouri 

### Reproduction Steps

I made a small example in amp playground [here](https://playground.amp.dev/?format=websites&_gl=1*12224ox*_ga*YW1wLXMxVDN6alJ3SDJhQXBhX0NzOFpiYXc.#share=PCFkb2N0eXBlIGh0bWw+CjxodG1sIOKaoT4KPGhlYWQ+CjxtZXRhIGNoYXJzZXQ9InV0Zi04Ij4KICAgIDx0aXRsZT5hbXAtc2NyaXB0PC90aXRsZT4KICAgIDxsaW5rIHJlbD0iY2Fub25pY2FsIiBocmVmPSJzZWxmLmh0bWwiPgogICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCI+CiAgICA8c3R5bGUgYW1wLWJvaWxlcnBsYXRlPgogICAgICBib2R5IHsKICAgICAgICAtd2Via2l0LWFuaW1hdGlvbjogLWFtcC1zdGFydCA4cyBzdGVwcygxLCBlbmQpIDBzIDEgbm9ybWFsIGJvdGg7CiAgICAgICAgLW1vei1hbmltYXRpb246IC1hbXAtc3RhcnQgOHMgc3RlcHMoMSwgZW5kKSAwcyAxIG5vcm1hbCBib3RoOwogICAgICAgIC1tcy1hbmltYXRpb246IC1hbXAtc3RhcnQgOHMgc3RlcHMoMSwgZW5kKSAwcyAxIG5vcm1hbCBib3RoOwogICAgICAgIGFuaW1hdGlvbjogLWFtcC1zdGFydCA4cyBzdGVwcygxLCBlbmQpIDBzIDEgbm9ybWFsIGJvdGg7CiAgICAgIH0KICAgICAgQC13ZWJraXQta2V5ZnJhbWVzIC1hbXAtc3RhcnQgewogICAgICAgIGZyb20gewogICAgICAgICAgdmlzaWJpbGl0eTogaGlkZGVuOwogICAgICAgIH0KICAgICAgICB0byB7CiAgICAgICAgICB2aXNpYmlsaXR5OiB2aXNpYmxlOwogICAgICAgIH0KICAgICAgfQogICAgICBALW1vei1rZXlmcmFtZXMgLWFtcC1zdGFydCB7CiAgICAgICAgZnJvbSB7CiAgICAgICAgICB2aXNpYmlsaXR5OiBoaWRkZW47CiAgICAgICAgfQogICAgICAgIHRvIHsKICAgICAgICAgIHZpc2liaWxpdHk6IHZpc2libGU7CiAgICAgICAgfQogICAgICB9CiAgICAgIEAtbXMta2V5ZnJhbWVzIC1hbXAtc3RhcnQgewogICAgICAgIGZyb20gewogICAgICAgICAgdmlzaWJpbGl0eTogaGlkZGVuOwogICAgICAgIH0KICAgICAgICB0byB7CiAgICAgICAgICB2aXNpYmlsaXR5OiB2aXNpYmxlOwogICAgICAgIH0KICAgICAgfQogICAgICBALW8ta2V5ZnJhbWVzIC1hbXAtc3RhcnQgewogICAgICAgIGZyb20gewogICAgICAgICAgdmlzaWJpbGl0eTogaGlkZGVuOwogICAgICAgIH0KICAgICAgICB0byB7CiAgICAgICAgICB2aXNpYmlsaXR5OiB2aXNpYmxlOwogICAgICAgIH0KICAgICAgfQogICAgICBAa2V5ZnJhbWVzIC1hbXAtc3RhcnQgewogICAgICAgIGZyb20gewogICAgICAgICAgdmlzaWJpbGl0eTogaGlkZGVuOwogICAgICAgIH0KICAgICAgICB0byB7CiAgICAgICAgICB2aXNpYmlsaXR5OiB2aXNpYmxlOwogICAgICAgIH0KICAgICAgfQogICAgPC9zdHlsZT4KICAgIDxub3NjcmlwdD48c3R5bGUgYW1wLWJvaWxlcnBsYXRlPgogICAgICAgIGJvZHkgewogICAgICAgICAgLXdlYmtpdC1hbmltYXRpb246IG5vbmU7CiAgICAgICAgICAtbW96LWFuaW1hdGlvbjogbm9uZTsKICAgICAgICAgIC1tcy1hbmltYXRpb246IG5vbmU7CiAgICAgICAgICBhbmltYXRpb246IG5vbmU7CiAgICAgICAgfQogICAgICA8L3N0eWxlPjwvbm9zY3JpcHQ+CiAgICA8c2NyaXB0IGFzeW5jIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAuanMiPjwvc2NyaXB0PgogICAgPHNjcmlwdCBhc3luYyBjdXN0b20tZWxlbWVudD0iYW1wLXNjcmlwdCIgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC9hbXAtc2NyaXB0LTAuMS5qcyI+PC9zY3JpcHQ+Cgo8dGl0bGU+YW1wLXNjcmlwdCAvIDI0PC90aXRsZT4KPHN0eWxlIGFtcC1jdXN0b20+PC9zdHlsZT4KPG1ldGEgbmFtZT0icm9ib3RzIiBjb250ZW50PSJub2luZGV4LCBub2ZvbGxvdyI+CiAgPG1ldGEgbmFtZT0iYW1wLXNjcmlwdC1zcmMiIGNvbnRlbnQ9InNoYTM4NC1kRVhqcXAxNC1rRHBTUFZBWlBoV1lwVFRYWnMxclZNTS05OEpha2ZNVmlEZmdGWVdQZW9Vc0NzRkVCU0hrVG1TICI+CjwvaGVhZD4KPGJvZHk+CgogICAgPGRpdj4KICAgICAgPGFtcC1zY3JpcHQgc2NyaXB0PSJsb2NhbC1zdG9yYWdlLXNjcmlwdCIgc2FuZGJveGVkPgogICAgICA8L2FtcC1zY3JpcHQ+CiAgICAgIDxzY3JpcHQgaWQ9ImxvY2FsLXN0b3JhZ2Utc2NyaXB0IiB0eXBlPSJ0ZXh0L3BsYWluIiB0YXJnZXQ9ImFtcC1zY3JpcHQiPgogICAgICAgIGNvbnN0IG9sZFVzZXJuYW1lID0gbG9jYWxTdG9yYWdlLmdldEl0ZW0oJ3VzZXJuYW1lJyk7CiAgICAgICAgY29uc29sZS5sb2coJ3plZSB1c2VybmFtZScsIG9sZFVzZXJuYW1lKQogICAgICA8L3NjcmlwdD4KICAgIDwvZGl2Pgo8L2JvZHk+CjwvaHRtbD4=)

Run it / open it and check console for the error

### Relevant Logs

```shell
Uncaught ReferenceError: localStorage is not defined
    at amp-script[script="local-storage-script"].js:4
```

### AMP Version Affected

2108192119000

**Comment by samouri** [comment]
Thank you for reporting this @zshnr. You are correct! Looks like for the nodom worker I didn't assign `document.defaultView` to the actual global.

This means localStorage is actually accessible, but only via `document.defaultView.localStorage`. Fixing in https://github.com/ampproject/worker-dom/pull/1091
