### ISSUE TITLE
fix examples in ads

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#3592]
![image](https://cloud.githubusercontent.com/assets/354746/16094289/62f71702-32f4-11e6-908b-e756dedef140.png)

reduce noise in errors for better release testing confidence

bad or missing attributes

**Comment by erwinmombay** [comment]
@ColombiaOnline can you provide us a divid to use for the example?

@nmochizuki is https://github.com/ampproject/amphtml/blame/master/examples/ads.amp.html#L474 supposed to be valid?

**Comment by ericlindley-g** [comment]
@erwinmombay Slotting in backlog, but feel free to correct/update the milestone

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
