### ISSUE TITLE
amp-lightbox-gallery tap on any picture and shows the first

### ISSUE THREAD

**Issue by andresGarcia93** [ampproject/amphtml#35920]
### Description

amp-lightbox-gallery when clicked on any picture starts showing always the first one. That affects UX because users want to watch a picture on fullscreen mode but clicking there they should find their picture again expending time and losing interest.

### Reproduction Steps

first picture:
![image](https://user-images.githubusercontent.com/63422090/131749419-4c6bd0eb-339e-45f4-8996-c28ccb3f8315.png)

last picture:
![image](https://user-images.githubusercontent.com/63422090/131749444-63348a6e-2816-4a49-9984-30802e895c44.png)

last picture clicked and the first pictures showed:
![image](https://user-images.githubusercontent.com/63422090/131749470-4ca9f0fa-cff6-4b8d-a9f4-130837ba2489.png)

**Comment by goonydev** [comment]
Please address this. I have been frustrated by this for weeks and I decided I was going to post about it today when I found this ticket.

Even on the official example online it works that way:

https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-lightbox-gallery&format=websites&_gl=1*1t8x0ky*_ga*YW1wLXI2aVVENjMzcUFTOWNvSlFPaVZsNlE.
