### ISSUE TITLE
Request to add jshamble as AMP collaborator

### ISSUE THREAD

**Issue by jshamble** [ampproject/amphtml#35936]
### Description

jshamble would like to be added as a collaborator
 
### Additional Context

jshamble has contributed the following PRs so far
of significant technical complexity:

**CTA Migration Page Outlink**
https://github.com/ampproject/amphtml/pull/35867
**Logic Delay for Handling Resize Requests**
https://github.com/ampproject/amphtml/pull/35603
**Added remote JSON functionality for amp story ads config**
https://github.com/ampproject/amphtml/pull/35256

**Comment by calebcordry** [comment]
+1 from me, to @kristoferbaxter

**Comment by kristoferbaxter** [comment]
Done! Thank you.
