### ISSUE TITLE
[amp-story] Discover widget does not center it's cropping of story posters

### ISSUE THREAD

**Issue by goonydev** [ampproject/amphtml#35956]
### Description

It is more an inconvenience than a bug, but it seems that the web story widget in Google Discover crops the posters on one side instead of centering the crop. I noticed this on my Alcatel Tablet running on Android. We are given a 3:4 ratio recommendation from the documentation:

https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/discovery_web_stories/

However, this ratio still gets cropped when displayed on my Discover web story feed. Maybe the display ratio differs from one device to another, which I wouldn't mind. What I mind is how my poster is cropped on one side only. The story posters play an important part in our CTR and we put some time to design them and have a nice composition, which will take into consideration the publisher logo as well as the title of the story. It would be easier for us if the web story widget cropped those posters with a gravity towards the center. Many times have I designed posters with a symmetrical composition and it got messed up by the current crop. 

Here is an example of a 3:4 poster I made (720x960):

![2023-vauxhall-astra-e-23](https://user-images.githubusercontent.com/17790584/132158365-83853ffe-5c5e-43fc-b1fd-fd9cd27cb221.jpg)

And here is how it appeared on my Google Discover feed:

![Untitled-18](https://user-images.githubusercontent.com/17790584/132158470-e91b3731-a106-4dde-91c0-1d3f1af33026.jpg)

We can clearly see that only the left side of this poster got cut out. Now this doesn't seem like a big deal for this particular case. But it can get quite annoying, like for this example:

![Untitled-19](https://user-images.githubusercontent.com/17790584/132158677-d7815da8-87d6-49ad-b1a2-fb8875e3ff6d.jpg)

It just bothers me, and I don't even have OCD.

### Reproduction Steps

Create a poster and see how it appears on Discover.

### OS(s) Affected

Android

### Device(s) Affected

Alcatel Tablet

**Comment by newmuis** [comment]
This is very interesting.  We unfortunately only control what happens in the open source web stories library, but I reported this issue to the relevant folks at Google.  I too hope to see this fixed!

I'm going to close this issue here because there's nothing anyone can do in this repository, but if I do hear any updates from those folks, I'll be sure to post them back here.
