### ISSUE TITLE
[Amp story] [Background blur] CORS issue

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#36001]
background blur is throwing a CORS error on [this story](https://amp.travel/stories/83daf2dd-f13c-49ad-b558-8bce2361ff5f).
<img width="1030" alt="Screen Shot 2021-09-08 at 3 15 47 PM" src="https://user-images.githubusercontent.com/3860311/132571069-a23cba5e-b903-47da-a488-100c417c8b72.png">

**Comment by ychsieh** [comment]
Duplicate of #37299
