### ISSUE TITLE
Bento npm packages should be `bento-` prefixed

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amphtml#36028]
### Description

We currently release `<BentoBaseCarousel>` React and Preact components and have the intention to release the web component `<bento-base-carousel>` on npm as well (#35554). 

We have no intention of publishing `<amp-base-carousel>` on npm, so the [`@ampproject/amp-base-carousel`](https://www.npmjs.com/package/@ampproject/amp-base-carousel) should probably be renamed to `@ampproject/bento-base-carousel` to alleviate potential confusion.

This is the case with all Bento component packages on npm.

### Alternatives Considered

Keep the package names as they are, which may be confusing devX.

### Additional Context

cc/ @swissspidy @ampproject/wg-bento @ampproject/wg-infra @ampproject/wg-outreach

**Comment by swissspidy** [comment]
I suppose this can be closed now that `@bentoproject/base-carousel` is a thing

**Comment by estherkim** [comment]
Definitely.
