### ISSUE TITLE
amp-carousel: Scrolling on carousel is not smooth

### ISSUE THREAD

**Issue by rajkumarsrk** [ampproject/amphtml#3602]
Scrolling on amp-carousel is not smooth

Steps to reproduce:
1. Load [eBay AMP](https://cdn.ampproject.org/c/m.ebay.com/sch/amp/Camera-Drones/179697/bn_89951/i.html) on Android chrome browser 
2. Try to scroll through any of the following modules which uses amp-carousel
    a) Shop by brand
    b) Save on Camera Drones
    c) Sponsored listings

This is happening on all mobile browsers
AMP version: 1464987951323 
Is this a new issue: Nope. The carousel was not smooth from the beginning

**Comment by cramforce** [comment]
Noticed this yesterday as well. Pretty terrible.

@sriramkrish85 when does your work land? Can we merge this with a different bug?

**Comment by dvoytenko** [comment]
@sriramkrish85 Might be worth checking it our directly for non-iOS browsers since the scrollable will land there later.

**Comment by ericlindley-g** [comment]
@sriramkrish85 — putting this in current, as I believe you're working on related items right now, but please re-slot/dedupe as necessary

**Comment by dvoytenko** [comment]
@camelburrito this is fixed, right?

**Comment by camelburrito** [comment]
Yes this has been fixed
