### ISSUE TITLE
AMP Validator: no longer detecting missing mandatory tags

### ISSUE THREAD

**Issue by samhutchins** [ampproject/amphtml#36040]
### Description

The AMP validator seems to have stopped detecting missing mandatory tags in some cases, such as the `<script async src="https://cdn.ampproject.org/v0.js"></script>` tag.

### Reproduction Steps

Paste the following HTML into the [online validator](https://validator.ampproject.org):
```
<!--
     This is the minimum valid AMP HTML document. Type away
     here and the AMP Validator will re-check your document on the fly.
-->
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <link rel="canonical" href="self.html">
  <meta name="viewport" content="width=device-width,minimum-scale=1">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
  <!--
	<script async src="https://cdn.ampproject.org/v0.js"></script>
  -->
</head>
<body>Hello, AMP world.</body>
</html>
```

Note the commented out `<script async src="https://cdn.ampproject.org/v0.js"></script>` line. I'd expect this to fail, but it passes

**Comment by honeybadgerdontcare** [comment]
This is intended behavior. It was decided with issue #24232 to make documents without any JavaScript as Valid AMP. This was rolled out in PR #35885.

**Comment by honeybadgerdontcare** [comment]
@samhutchins reopening as the comment should be updated from:
`minimum valid AMP HTML document`
to
`minimum valid AMP HTML document using JavaScript`

**Comment by samhutchins** [comment]
@honeybadgerdontcare The documentation [here](https://amp.dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors/?format=websites) still lists the amp script as mandatory, could that be updated as well?

**Comment by honeybadgerdontcare** [comment]
> @honeybadgerdontcare The documentation [here](https://amp.dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors/?format=websites) still lists the amp script as mandatory, could that be updated as well?

I'm not confident that we would want to update that documentation as most developers reading it will want to use the AMP Runtime and that script is required for AMP Runtime. Could you file a separate [issue](https://github.com/ampproject/amp.dev/issues/new/choose) to [amp.dev repo](https://github.com/ampproject/amp.dev) for it? This issue will cover the validator related texts.

**Comment by honeybadgerdontcare** [comment]
https://validator.amp.dev/ now reflects the change
