### ISSUE TITLE
Allow `!important` qualifiers in `style[amp-noscript]`

### ISSUE THREAD

**Issue by westonruter** [ampproject/amphtml#36051]
### Description

This is a follow-up to #20609.

In order to ensure that `amp-accordion` sections are initially-expanded on a page in which the user has JS turned off, the following is needed:

```html
<noscript>
	<style amp-noscript>
		amp-accordion > section:not([expanded]) > :last-child {
			display: block !important;
		}
	</style>
</noscript>
```

Example: https://bento-amp-noscript-styles.glitch.me/
See: https://github.com/ampproject/amphtml/issues/20609#issuecomment-901426550

The `!important` is needed here in order to override this `!important` style from `ampshared.css`:

https://github.com/ampproject/amphtml/blob/22ff7ae97577bd1d0376d66ab0ca741cbdba4e50/css/ampshared.css#L567-L570

However, this is not currently feasible since the use of `!important` qualifiers is not allowed in `style[amp-noscript]`:

> Usage of the !important CSS qualifier is not allowed.

I propose that they be allowed in the same way they are allowed in `style[amp-runtime]`. 

Interestingly, `allow_important: true` doesn't appear in `style[amp-runtime]`:

https://github.com/ampproject/amphtml/blob/22ff7ae97577bd1d0376d66ab0ca741cbdba4e50/validator/validator-css.protoascii#L1317-L1339

Just as it doesn't appear in `style[amp-noscript]`:

https://github.com/ampproject/amphtml/blob/22ff7ae97577bd1d0376d66ab0ca741cbdba4e50/validator/validator-css.protoascii#L1341-L1448

Perhaps `allow_important` is only considered for rules that are `enabled_by: "transformed"`?

### Alternatives Considered

None.

**Comment by honeybadgerdontcare** [comment]
@westonruter for `<style amp-runtime ...>` note that there is no `cdata` set in the TagSpec. Basically anything can be in the cdata for that. This is permitted as AMP Caches will rewrite the `cdata` with the corresponding AMP CSS with the AMP Runtime version that is being served by that AMP Cache. Also the AMP Runtime will rewrite the AMP CSS if necessary.

So `allow_important` would need to be set to the `cdata` for `<style amp-noscript>` TagSpec.

**Comment by Gregable** [comment]
@westonruter I have no issues with adding `allow_important` to `noscript`. I think this is a simple change. Are there any blockers? 

Do you want to create the PR or shall I?

**Comment by westonruter** [comment]
@Gregable Great! Would you please?

**Comment by jcastilloa** [comment]
I agree, amp-toolbox-php (https://github.com/ampproject/amp-toolbox-php) fails in ssr transformation due to !important restrictions. All pages stop validating.

Any news about this?.

Thanks.

**Comment by Gregable** [comment]
I implemented this back in January, the issue was just never closed.

@jcastilloa you are probably running into issues around using `!important` in `<style>` tags outside of `<noscript>`, which is different and intended.

**Comment by schlessera** [comment]
@Gregable I opened a new issue regarding the above, for discussion: https://github.com/ampproject/amphtml/issues/37761
