### ISSUE TITLE
amp-consent forces iframe to load twice

### ISSUE THREAD

**Issue by janwinkler** [ampproject/amphtml#36063]
### Description

When amp-consent is used on a page, the content of the consent layer is displayed in an iframe. This Iframe is invisible first and then moved to a visible position in the page. Due to this move, the iframe is loaded twice and therefore cases the content of the iframe to also load twice (e.g. fireing counting pixels twice).

### Reproduction Steps

Example page:
https://www.google.com/amp/s/www.ruhr24.de/nrw/nrw-corona-3g-testpflicht-disko-diskotheken-eilantrag-betreiber-ruhrgebiet-ovg-schnelltest-90979227.amp.html

Consent layer is first loaded as this:
![grafik](https://user-images.githubusercontent.com/1705243/133266607-273c08ee-1d85-4e1a-b91e-031c74e6bc12.png)

and then immediatly moved to here:
![grafik](https://user-images.githubusercontent.com/1705243/133266882-4bd56782-3a37-413d-8af8-23089ef68108.png)

This causes the iframe to load twice.

Same issue can be found on other pages, e.g.:

https://www.google.com/amp/s/www.sueddeutsche.de/bayern/corona-bayern-aktuell-lollitest-kita-testpflicht-1.5402821!amp (loads https://consent-cdn.sueddeutsche.de/amp/index.html multiple times)

https://www.google.com/amp/s/amp.tagesspiegel.de/politik/furcht-vor-politischem-vakuum-so-blickt-die-welt-auf-die-bundestagswahl/27608470.html (loads https://cdn.privacy-mgmt.com/wrapper/tcfv2/v1/gdpr/native-message?requestUUID=... multiple times)

**Comment by alanorozco** [comment]
This happens only in the Viewer due to `FixedLayer` reparenting. A fix would involve ensuring that the iframe is not created until reparenting has occurred.

/invite @dethstrobe

**Comment by janwinkler** [comment]
@alanorozco, can you elaborate, what does that mean exactly? the CMP is not creating the iframe, it is AMP that creates it ...
