### ISSUE TITLE
amp-youtube error parameter

### ISSUE THREAD

**Issue by Francisco-AM** [ampproject/amphtml#36089]
### Description

When you want to use only videos from one channel, the camelcase won't let you because it incorrectly formats the url.

Solution?

### Reproduction Steps

![image](https://user-images.githubusercontent.com/69035383/133610666-9476179f-a160-4ed5-9c19-3ab651ff5afc.png)

![image](https://user-images.githubusercontent.com/69035383/133610738-7ca00eb4-014a-4f52-b47e-768c2b466a54.png)

![image](https://user-images.githubusercontent.com/69035383/133610777-fc5f545e-b12b-4199-a941-6f776c8e57f9.png)

**Comment by alanorozco** [comment]
@Francisco-AM Use `data-param-list-type`, with a dash between `list` and `type`. That will give you what you want.
