### ISSUE TITLE
[Validator feature tests] Typo in mandatory_dimensions.html 

### ISSUE THREAD

**Issue by sidkshatriya** [ampproject/amphtml#3609]
There is a very trivial issue in:
https://github.com/ampproject/amphtml/blob/e1aa24df8432963423ee6cec1ce4d57529767e6e/validator/testdata/feature_tests/mandatory_dimensions.html#L127

```html
<amp-anim width="42" height="42"></amp-anum>
```

The closing tag should be `</amp-anim>` and not `</amp-anum>` (spelling issue)

**Comment by powdercloud** [comment]
Thank you @sidkshatriya. I'll take care of it, we change this particular file internally and push it out here, so could take a little while.

**Comment by Gregable** [comment]
This change is now live on cdn.ampproject.org
