### ISSUE TITLE
Fixed position element has wrong position

### ISSUE THREAD

**Issue by nomve** [ampproject/amphtml#36097]
### Description

AMP apparently does something to adjust the position of fixed position elements once the AMP top bar moves out of view during user scroll. We have an issue that this is for unclear reasons not working on our page(s), so we get gaps or overlaps depending on what we do.

From looking at other pages where this issues does not exist, it seems AMP inserts e.g. `i-amphtml-fixedid="F0" style="top: calc(32px);"` on a fixed position element, but this is missing from our page.

### Reproduction Steps

1. open e.g. https://www.google.com/amp/s/www.nzz.ch/amp/feuilleton/afghanistan-der-autor-taqi-akhlaqi-blickt-auf-sein-land-ld.1644381
2. observe the overlap of the header and the movable top bar

there are no and were no issues on our actual AMP page, https://www.nzz.ch/amp/feuilleton/afghanistan-der-autor-taqi-akhlaqi-blickt-auf-sein-land-ld.1644381

previously we also had the opposite issue, where everything was initially ok, but after the bar was hidden, there was a gap in place of the bar. Example below.

![IMG_F7ADA3211E33-1](https://user-images.githubusercontent.com/9338645/133721165-33e81f17-f47d-4aa9-a07f-00d786596151.jpeg)

**Comment by jridgewell** [comment]
The fixed-position tracker is becoming confused, because there's a parent element that might also be `fixed`:

```html
<div class="ob nb"><!-- .ob can be fixed, but it's overridden by `.nb, .ob` -->
  <div>
    <div class="tb"><!-- this is actually fixed-position -->
```

Removing the `position: fixed` from the `.ob` style should fix this.

**Comment by nomve** [comment]
thanks a lot, this has fixed the issue.

**Comment by samouri** [comment]
@jridgewell: is there action for us to take here?
