### ISSUE TITLE
URL attribute for amp-(youtube|twitter|instagram)

### ISSUE THREAD

**Issue by mjangda** [ampproject/amphtml#361]
Raised this in the mailing list and was recommended to open an issue here.

It would be helpful if the service-specific components (YouTube, Twitter, Instagram) were oEmbed-like and accepted a URL so that publishers don't need to parse out the ID themselves (which can be tricky when you factor in many different URL formats that each service might have).

e.g.

```
<amp-twitter src=https://twitter.com/joemccann/status/640300967154597888></amp-twitter>

<amp-youtube src=https://www.youtube.com/watch?v=Z1q71gFeRqM></amp-youtube>

<amp-instagram src=https://instagram.com/p/fBwFP></amp-instagram>
```

**Comment by aghassemi** [comment]
Closing as dup in favour of https://github.com/ampproject/amphtml/issues/4367 (since it has more comments in the discussion)
