### ISSUE TITLE
Implement retry logic for integration tests

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#3610]
This is sad, because it increases test runtime, but likely needed.

Should be something like

`it.retry(2).`

**Comment by erwinmombay** [comment]
@cramforce isnt this already supported? in an `describe` or `it` block you can do `this.retries(4)` (w/o using arrow function)

**Comment by cramforce** [comment]
That might be all we need. Was going to to say: `or document how it works.`

**Comment by cramforce** [comment]
I think we might want to consider retries for all tests on saucelabs. How do people feel about that?

**Comment by erwinmombay** [comment]
@cramforce i asked this in the channel a month or so ago and people weren't turned off on the idea (especially with the tests that do network requests)

**Comment by erwinmombay** [comment]
if we need it to get tests green i'm all for it, there are other bottlenecks we can improve upon to make the travis runs a bit faster

**Comment by lannka** [comment]
Verified, mocha supports retry: https://mochajs.org/

```
describe('retries', function() {
  // Retry all tests in this suite up to 4 times
  this.retries(4);
  
  beforeEach(function () {
    browser.get('http://www.yahoo.com');
  });
  
  it('should succeed on the 3rd try', function () {
    // Specify this test to only retry up to 2 times
    this.retries(2);
    expect($('.foo').isDisplayed()).to.eventually.be.true;
  });
});
```

I will add documentation to [DEVELOPING.md](https://github.com/ampproject/amphtml/blob/master/DEVELOPING.md#build--test). Sounds good?

**Comment by cramforce** [comment]
Sounds good. Should we auto-retry all integration tests?

**Comment by lannka** [comment]
It might hide potential flaky bug. I think we should always try to fix flaky test first and Use retry as the last resort

**Comment by cramforce** [comment]
Absolutely!
