### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [ampproject/amphtml#36108]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by alanorozco** [comment]
cc @ampproject/wg-security-privacy

**Comment by honeybadgerdontcare** [comment]
@molnarg fyi

**Comment by ready-research** [comment]
@coreymasanto @newmuis @alanorozco Reported a security issue in huntr https://www.huntr.dev/bounties/36577e6a-67e2-4002-9586-007bdf8407d9/ long back, can you please validate this?

https://github.com/ampproject/amphtml/blob/3fe2ae4108e8ce4355c90640458d13cf81af160c/src/core/types/string/index.js#L92 is using regex which is vulnerable to ReDoS.

**Comment by jridgewell** [comment]
Hi @ready-research: That regex shouldn't be vulnerable. The `*` closes over a `[^}]` (anything but a `}`), which is disjoint with the required next `}`. Using the following, we would see a quadratic increase in timing if it were vulnerable:


```js
const regex = /\${([^}]*)}/;

function test(length) {
  const str = '${' + 'a'.repeat(length);
  const now = performance.now();
  regex.test(str);
  return performance.now() - now;
}

for (let i = 0; i < 500; i++) {
  console.log({ length: i, time: test(i) });
}
```

**Comment by ready-research** [comment]
Yeah, agrees with you it requires an extremely large string. Security is all about edge cases. So can you please raise a PR for this?

**Comment by ready-research** [comment]
@jridgewell Tested the above fix, I can confirm that this resolves the issue. Thanks for the quick response.

Can you please mark this huntr report
https://www.huntr.dev/bounties/36577e6a-67e2-4002-9586-007bdf8407d9/  as valid using `Mark as valid`? Thanks.

**Comment by JamieSlome** [comment]
@jridgewell - thanks for your support here ❤️ 

Are you able to mark the [report](https://www.huntr.dev/bounties/36577e6a-67e2-4002-9586-007bdf8407d9/) as fixed? You just need the commit SHA from the merge and the patched version.

You are welcome to take the reward for fixing it too!

**Comment by JamieSlome** [comment]
@jridgewell - we can only reward fixes to researchers if they submit patches via the report page. If you are not able to self-reward, you can select `no-one` as the fixer, and the funds will be returned back to the pool for your repositories future research incentives ❤️

**Comment by JamieSlome** [comment]
Just for your reference @jridgewell:

<img width="720" alt="Screenshot 2022-05-12 at 16 23 59" src="https://user-images.githubusercontent.com/55323451/168110998-13206fee-b5bb-4f05-b033-0e4ac8c58f34.png">
