### ISSUE TITLE
Flaky: Rendering of one ad with ad script

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#3611]
We should consider deleting this test or the other one if we have sufficient confidence.

Or write a specialized test. Copying the doubleclick test is bad, because it makes network requests and thus is flaky.

**Comment by zhouyx** [comment]
We could definite delete the test with script included. But would the left test still makes net requests and it's still flaky?

**Comment by cramforce** [comment]
This test is inherently flaky, but very valuable. We will need to live with it.

**Comment by zhouyx** [comment]
Should I also do this? 
not make network requests to actual ads  #3616

**Comment by cramforce** [comment]
@zhouyx That bug is about the unit test for ads. Feel free to take it.

**Comment by zhouyx** [comment]
So for integration test, we can't make a fake ad and will have to make network requests?

**Comment by cramforce** [comment]
@zhouyx This integration test is testing that actual ad rendering works. It must talk to doubleclick for that.

**Comment by zhouyx** [comment]
Got it.  Thanks ; )
