### ISSUE TITLE
Incorrect error code in WebAssembly validator

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amphtml#36112]
### Description

We’re working on migrating `validator.js` usage to the WASM version and I am running into a strange issue where I get a `STYLESHEET_AND_INLINE_STYLE_TOO_LONG` error for a blank web story when I should be getting `MISSING_URL` because of a missing story poster image.

It works fine on validator.amp.dev though.

### Reproduction Steps

CodePen: https://codepen.io/swissspidy/pen/OJgZJpY

### Relevant Logs

```shell
// Full error (see how it references poster-portrait-src, but the error code is wrong):

{
    "severity": "ERROR",
    "code": "STYLESHEET_AND_INLINE_STYLE_TOO_LONG",
    "line": 6,
    "col": 2864,
    "specUrl": "https://amp.dev/documentation/components/amp-story",
    "paramsList": [
        "poster-portrait-src",
        "amp-story"
    ],
    "params": [
        "poster-portrait-src",
        "amp-story"
    ]
}
```

**Comment by honeybadgerdontcare** [comment]
Thanks for reporting. Indeed the string representation is wrong. We're working on a fix.

**Comment by honeybadgerdontcare** [comment]
@swissspidy this is now fixed and deployed. Verified at validator.amp.dev.
