### ISSUE TITLE
🚄 Release 2109180035000

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#36128]
### AMP Version

[2109180035000](https://github.com/ampproject/amphtml/releases/tag/2109180035000)

### Promotions

- [x] 2109180035000 promoted to Experimental and Beta (opt-in) channels 
- [ ] 2109180035000 promoted to Experimental and Beta (1% traffic) channels 
- [ ] 2109180035000 promoted to Stable channel 

/cc @ampproject/release-on-duty

**Comment by samouri** [comment]
Closing, as promotion to `%` traffic was missed in an oversight
