### ISSUE TITLE
Flaky: Error: Timeout waiting for frame to load

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#3612]
This poll times out
https://github.com/ampproject/amphtml/blob/master/test/integration/test-amp-ad-doubleclick-with-script.js#L72

This is very early in the test; before network requests are made. Could this hit the iframe creation bug @dvoytenko was mentioning a week or so ago?

**Comment by dvoytenko** [comment]
Which browser does it falke out on? I tried Chrome 51 and 52 - can't get it to flake out.

It doesn't sound like the same bug though. The bug I mentioned - the iframe contents were available, but `load` event didn't fire.
