### ISSUE TITLE
Profile tests and make them go faster

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#3618]
:)

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)

**Comment by adelinamart** [comment]
@cramforce is this still an issue? Thanks

**Comment by cramforce** [comment]
Yes

**Comment by cramforce** [comment]
CC @rsimha-amp We should do this at some point. Not sure how much we can win.

**Comment by rsimha** [comment]
Several things have been done to optimize our tests on Travis. Most importantly, we have a new build matrix (#20811) and a refined way of determining which tests are run during PR checks (#22348).

Today, we run ~20000 tests against the runtime on Travis 20 or so minutes.

Closing this out.
