### ISSUE TITLE
🌸 Cherry-pick request for #36197 into 2109272305000

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#36199]
### Issue (P0 Bug)
https://github.com/ampproject/error-reporting/issues/106

### Pull Request(s)
https://github.com/ampproject/amphtml/pull/36197

### Release Tracker(s)

https://github.com/ampproject/amphtml/issues/36186

### Channels

Beta / Experimental

### Formats

Websites, Stories

### Justification

The bug causes an error to be thrown for all pages that emit layout-shift events before `Performance` service has fully initialized. AFAICT this shouldn't actually break UX of the page, and will only create noise. Judging by volume on Nightly, the amount of noise is incredibly high.

Therefore this is worth fixing in Beta, where the bar is lower for CPs

### Verification Steps

New unit test + the stacktrace in the error make it clear that it should be fixed.

### Impact

Noise in error logs on Beta channel.

### Action Items

N/A, all taken within the fix PR.

### Notifications

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by gmajoulet** [comment]
Would we have a drop in `layout-shift` events volume unless we CP?

**Comment by kristoferbaxter** [comment]
Approved. Thanks!

**Comment by samouri** [comment]
> Would we have a drop in layout-shift events volume unless we CP?

Still digging through the code now. I'm not sure if it will affect volume, but a side effect in the error path would be a reduced CLS ticked under `cls-1`

**Comment by rsimha** [comment]
> Judging by volume on Nightly, the amount of noise is incredibly high.
> Therefore this is worth fixing in Beta, where the bar is lower for CPs

I'm convinced by these two statements. Approved.
