### ISSUE TITLE
Requirements around end tags for amp components

### ISSUE THREAD

**Issue by mjangda** [ampproject/amphtml#362]
It would be nice if the documentation made it clear what the requirements are around end tags for amp components.

Looks like all the examples (except <a href="https://github.com/ampproject/amphtml/blob/f201cde9492142355de0a242c73512ec94567456/spec/amp-html-format.md#sample-document
">the sample document</a>) use end tags (i.e. `<amp-img></amp-img>`) but this doesn't seem to be explicitly stated as a requirement anywhere.

Not including the end tag can cause issues in some instances, like #360

**Comment by rudygalfi** [comment]
Sweeping old bugs: Is this still an issue?
cc @Gregable to speak to validator behavior

**Comment by Gregable** [comment]
The validator doesn't directly enforce requirements around end tags, mostly they all have to do with spec requirements about what tags can be inside of others. There was another request to disallow attributes in end tags, but we haven't done anything with that so far. I'm reasonably sure browsers ignore these, so it hasn't been a high priority.
