### ISSUE TITLE
Switch postMessage ping-pong tests to use fixture iframe.

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#3620]
In particular these files would be better loaded without a network request:
https://github.com/ampproject/amphtml/tree/master/test/fixtures/served

The existing fixture mechanism should enable that. It should become very easy to do the right thing in a test.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
