### ISSUE TITLE
Wrong URL in the upper drawer points to favicon instead of pointing to the content

### ISSUE THREAD

**Issue by kirisakow** [ampproject/amphtml#36216]
### Description

Wrong URL in the upper drawer points to favicon instead of pointing to the content

### Reproduction Steps

4 steps, 4 screenshots:
1. Launch Google Search query `Canada Richard Ford` ([https://ibb.co/qdSH6ms]()) 
2. Click on The Guardian June 3, 2012 article "Canada by Richard Ford — review" ([https://ibb.co/jZtfHrV]()) 
3. Once in the AMP view... ([https://ibb.co/0cqvQvG]()) 
4. ...open the upper drawer, see the wrong URL ([https://ibb.co/k9D9wdH]()) 

### Browser(s) Affected

Firefox

### OS(s) Affected

Android 10

### Device(s) Affected

Lenovo P2

**Comment by kirisakow** [comment]
Neither can I reproduce that anomaly. This is quite strange. 

My guess is there was probably some interference with, say, older browsing history of that specific tab, which probably resulted in a mess with variables in memory.

**Comment by kristoferbaxter** [comment]
I'll ask the team at Google in a followup, but will close this issue for now then.
