### ISSUE TITLE
Add @coreymasanto to @ampproject/reviewers-amphtml

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#36219]
### Description

@coreymasanto from @ampproject/wg-stories has over 10 merged PRs and few new open ones, including some complex/high quality ones (#35581, #35908, #35798) and should be added to @ampproject/reviewers-amphtml so he can tag/review/merge/triage issues and pull requests.

cf: https://github.com/ampproject/amphtml/pulls/coreymasanto

Thanks!

### Alternatives Considered

-

**Comment by rsimha** [comment]
Invite sent. Nice work @coreymasanto, and welcome to the reviewers group. 👍
