### ISSUE TITLE
Error Of " parent tag of tag 'html' "

### ISSUE THREAD

**Issue by Monikamanali** [ampproject/amphtml#36218]
### Description

getting this error is in my website when checking it with AMP Validator "The parent tag of tag 'html' is '$root', but it can only be '!doctype'

My site is build with PHP.

https://manalicallgirl.com

![screencapture-validator-ampproject-org-2021-09-30-04_31_39](https://user-images.githubusercontent.com/72122280/135468199-af0d515d-963e-471d-a476-27319f024f11.png)
."

### Reproduction Steps

Check The url on https://validator.ampproject.org/ 

### Browser(s) Affected

Chrome, Firefox, Edge

### AMP Version Affected

2109102127000

**Comment by honeybadgerdontcare** [comment]
@Monikamanali The server is responding with a [Byte Order Mark](https://en.wikipedia.org/wiki/Byte_order_mark) before the <`!doctype html>`. Looking at the content within the AMP Validator, notice the red dots. One can also use `curl` to fetch the document and look at the response returned by the server as well. The server will need to not respond with that character as it is not valid AMP.
