### ISSUE TITLE
test cases: amp-carousel slide count not updating

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#36253]
### Description

The "selected slide" index should update

### Reproduction Steps

1. Go to https://amp.dev/documentation/examples/multimedia-animations/image_galleries_with_amp-carousel/preview/?format=websites
2. Scroll down to the "Selected slide" text which uses <amp-bind>
3. Clicking the arrows for prev/forward will update the selected text, but swiping with pointer does not.

---

cc @JuliaTrubchyk  @ampproject/wg-components  (or maybe wg-performance if an amp-bind bug)

**Comment by dzarmanova** [comment]
This issue is flaky sometimes but still reproducible on all desktop and mobile environments (Chrome, Safari, Firefox)

**Comment by dzarmanova** [comment]
This issue is also reproducible on amp-script component https://photos.app.goo.gl/Vqo38UAxc6LC9w9h6
