### ISSUE TITLE
amp-next-page: Google cache problem

### ISSUE THREAD

**Issue by spinmar** [ampproject/amphtml#36339]
### Description

Hi,
we are experimenting some problem about amp-next-page. We introduced it to solve CLS problem in our amp pages but it seems that when the page is served by Google cache the tag amp-next-page has some problem. The request in the network panel is present but the response is not displayed.

### Reproduction Steps

To reproduce the problem follow the below instructions.
Our amp page is this:

https://sport.virgilio.it/milan-in-emergenza-trattativa-lampo-per-il-sostituto-di-maignan-715489/amp/

it is a valid amp page with amp-next-page at the end. If you scroll at the end you can see that we are serving the footer with an ad. All is ok.

If you try to see tha page with Google AMP cache:

https://sport-virgilio-it.cdn.ampproject.org/c/s/sport.virgilio.it/milan-in-emergenza-trattativa-lampo-per-il-sostituto-di-maignan-715489/amp/

and you scroll at the end the footer is not served. By network panel you can see the request but it is not displayed.

### Browser(s) Affected

Chrome, Safari

**Comment by dmanek** [comment]
Hi @spinmar thanks for reporting this issue. After looking at both inks, I don't see the footer defined within `amp-next-page`. Can you add the `footer` attribute as described at https://amp.dev/documentation/components/amp-next-page/#footer-elements?

**Comment by dmanek** [comment]
Closing since there is no update.
