### ISSUE TITLE
🌸 Cherry-pick request for #36361 into 2110082201000

### ISSUE THREAD

**Issue by coreymasanto** [ampproject/amphtml#36370]
### Issue (P0 Bug)

#36365

### Pull Request(s)

#36361

### Release Tracker(s)

#36332

### Channels

Beta / Experimental

### Formats

Stories

### Justification

As described in #36365:
> The consequence of no cherrypick is that H.264 video sources obtained via Monti would appear to be unplayable, causing the browser to instead request the video from the publisher, incurring a request traffic cost on publishers who depend upon Monti.

### Verification Steps

1. In beta/experimental, open a story with a video that has uses an H.264 source
2. Ensure that the source's `type` attribute does not include a `codecs=` string appended to its value (e.g., the value should look like `"video/mp4"` instead of `"video/mp4; codecs=h264"`)
3. Ensure that the video plays without issue
4. Ensure that, when calling `.canPlayType(mediaType)` on the H.264 source element (with `mediaType` being the string value of the source's `type` attribute), an empty string is not returned

### Notifications

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by jridgewell** [comment]
This just needs a Beta, approved.

**Comment by rsimha** [comment]
This was cherry-picked and released as [`2110082201001`](https://cdn.ampproject.org/rtv/002110082201001/v0.js).
