### ISSUE TITLE
Latest AMP release killing other event listeners

### ISSUE THREAD

**Issue by AaronMLB** [ampproject/amphtml#36423]
### Description

I am currently redeveloping an entire website with AMP (not just first, but solely, self-canonical).

Some pages are not cacheable/valid AMP, but still use the framework for its excellent components providing modern solutions like off-canvas slide-out mobile menus. Some of these pages also call in additional JavaScript; vanilla, jQuery, mixes thereof, etc.

Yesterday I discovered that one event listener is no longer firing on submission of a form. However, if I remove the first of AMP's three submit event listeners (2x v0.js, 1x amp-form), then it does fire correctly. All was well around a week ago and no other code around the event listener has changed: indeed, restoring code from previous Git commits makes no difference; it still doesn't fire.

The form in question is part of a payment system. The site uses PayPal's Braintree and its [Hosted Fields implementation](https://developer.paypal.com/braintree/docs/start/hosted-fields) to take credit card data. Specifically, this renders the most sensitive few fields as iframes on Braintree's own servers, then intercepts the form submit to verify the card and retrieve an authorisation nonce to return to the form, and then submits.

As I say, last week this was working correctly, tokenising the payment details then handing off to the event listener of `amp-form` in order to do all the AMP XHR, verification, etc.

The v0.js build I am currently receiving is 2110082201001, and this is that first AMP submit listener that seems to be causing the issue, at line 6229 of the re-formatted minified file:

```
            else if ("submit" == a)
                this.X.addEventListener(a, (function(e) {
                    b.trigger(e.target, a, e, 3)
                }
                ));
```

### Reproduction Steps

The JS to handle Braintree's processes looks something like this:
```
var methodForm = document.getElementById("methodForm");
var threeDSecure = null;

braintree.client.create(
  {
    authorization: $token,
  },
  function (err, client) {
    if (err) {
      console.error(err);
      return;
    }

    braintree.hostedFields.create(
      {
        client: client,
        fields: {
          number: {
            selector: "#card-number",
            placeholder: "•••• •••• •••• ••••",
          },
          cvv: {
            selector: "#cvv",
            placeholder: "123",
          },
          expirationMonth: {
            selector: "#expiration-month",
            placeholder: "Month",
            select: {
              options: [
                "01 - January",
                "02 - February",
                "03 - March",
                "04 - April",
                "05 - May",
                "06 - June",
                "07 - July",
                "08 - August",
                "09 - September",
                "10 - October",
                "11 - November",
                "12 - December",
              ],
            },
          },
          expirationYear: {
            selector: "#expiration-year",
            placeholder: "Year",
            select: true,
          },
        },
      },
      function (err, hostedFields) {
        if (err) {
          console.log("Error initialising payment fields..");
          return;
        }

        methodForm.addEventListener("submit", function (e) {
          e.preventDefault();

          if (
            document.querySelector('input[name="method"]').value != "paypal"
          ) {
            hostedFields.tokenize(function (tokenizeErr, payload) {
              if (tokenizeErr) {
                console.log(
                  "Card could not be tokenised: " +
                    tokenizeErr.message
                );
                return;
              }

              threeDSObj = {
                nonce: payload.nonce,
                bin: payload.details.bin,
                onLookupComplete: function (data, next) {
                  next();
                },
              };

              threeDSecure.verifyCard(threeDSObj, function (err, response) {
                if (err) {
                  console.log("Card could not be authorised.");
                  return false;
                }

                // If eligible for 3DS, check it didn't fail
                if (
                  response.liabilityShiftPossible &&
                  !response.liabilityShifted
                ) {
                  console.log("Security check failed.");
                  return false;
                }

                // Success! Submit the form
                document.querySelector('input[name="method"]').value = "card";
                document.querySelector('input[name="nonce"]').value =
                  response.nonce;
              });
            });
          }
          methodForm.submit();
        });
      }
    );

    // Set up the device data collector for security.
    braintree.dataCollector.create(
      {
        client: client,
        kount: true,
      },
      function (err, dataCollectorInstance) {
        if (err) {
          console.log("Data collector could not be created.");
          return;
        }
        var deviceData = dataCollectorInstance.deviceData;
        document.querySelector('input[name="device-data"]').value = deviceData;
      }
    );

    // Set up the 3DS support.
    braintree.threeDSecure.create(
      {
        client: client,
        version: 2,
      },
      function (err, threeDSecureInstance) {
        if (err) {
          console.log("3DS could not be initialised.");
          return;
        }

        threeDSecure = threeDSecureInstance;
      }
    );
  }
);
```

At this point we're getting far beyond my knowledge: as I say, the event listener is still registering, but suddenly not firing at all. Any assistance would be greatly appreciated.

### AMP Version Affected

2110082201001

**Comment by AaronMLB** [comment]
> @AaronMLB, the latest RTV is `012110082201001`. Can you manually specify the previous RTV `2110011758000` for all of your components and the runtime to see if the problem is resolved? That will isolate whether it was a recent AMP change, or potentially one elsewhere (i.e. w/ Braintree).
> 
> You can do this via:
> 
> ```
> <script async src="https://cdn.ampproject.org/rtv/012110011758000/v0.js"></script>
> ```
Thanks @samouri.

Not sure if you meant to change the component source URLs too, or whether they inherit directly from the v0.js runtime file? (If the former, I get 404s on all of the components so have reverted them to `/v0/`.)

Regardless, specifying that version for the runtime does not solve the problem. Which is perhaps unexpected, given my experience of it working last week?

> > Some pages are not cacheable/valid AMP
> 
> Have you heard of the [Bento project](https://blog.amp.dev/2021/01/28/bento/)? We are building a new set of components specifically meant to behave properly on not-fully AMP pages.

I had heard of it, but hadn't fully appreciated the scope of the project until reading that blog post now, thank you. It looks like it's not quite at the stage where I can use it for my purposes, but it's definitely very promising and I will be keeping an eye on its development.

**Comment by AaronMLB** [comment]
Hi again - I just wondered if anyone had had the time or opportunity to look into this at all? I'm still very much at a loss!

**Comment by samouri** [comment]
@AaronMLB, seeing as this is an explicitly unsupported usage of AMP, and the minimal reproduction you've created requires a nontrivial amount of effort to reproduce (It requires running a local PHP server, setting up BrainTree account, etc) this isn't something I have the bandwidth to look into.

If you were able to create a reproduction that only utilizes AMP code and a minimal inline JS script, it would be much less effort on our end to debug.  That said, its still possible we wouldn't be able to resolve it, because we may have use cases that require us to cancel a form submit.

**Comment by AaronMLB** [comment]
Okay. Thanks for your time anyway.
