### ISSUE TITLE
🌸 Cherry-pick request for #36433 into #36396

### ISSUE THREAD

**Issue by rcebulko** [ampproject/amphtml#36436]
### Issue (P0 Bug)

#36433

### Pull Request(s)

#36434

### Release Tracker(s)

#36396

### Channels

Beta / Experimental, Stable

### Formats

Websites

### Justification

Breaks placeholders in amp-twitter

### Verification Steps

See https://github.com/ampproject/amphtml/issues/36433

### Notifications

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by kristoferbaxter** [comment]
Approved.
