### ISSUE TITLE
iPad pro 15.0.2 Safari/Chrome positioning top nav bar wrong

### ISSUE THREAD

**Issue by alankent** [ampproject/amphtml#36450]
### Description

The navigation controls etc at the top of each page in a web story are positioned incorrectly (there is a gap above them) on my iPad Pro running iOS 15.0.2 (never recalled this problem previously, updated iPad recently). Happens on Chrome and Safari. Does not happen on my Mac laptop.

![image0 (2)](https://user-images.githubusercontent.com/5702163/138323242-81b943ae-76a5-4f98-bad8-7fd4bcbc7e0c.png)

### Reproduction Steps

I was accessing https://extra-ordinary-web-stories.web.app/ep1/ on my desktop (works fine) and and iPad Pro (15.0.2, with bug) and noticed the difference. The navigation controls at the top of the page are wrong for all pages in the story.

### Browser(s) Affected

Chrome, Safari

### OS(s) Affected

iOS 15.0.2

### Device(s) Affected

iPad Pro

**Comment by ychsieh** [comment]
Tried iPad simulators in Chrome and cannot be reproduced anymore.
