### ISSUE TITLE
Circular Progess bar

### ISSUE THREAD

**Issue by router-hub** [ampproject/amphtml#36482]
### Description

Hi team,
Is it possible to design a circular progress bar using an amp, I have not found any proper guidance for it. I will be very thankful if you will help me.

### Alternatives Considered

for reference:-
![image](https://user-images.githubusercontent.com/54014993/138760089-431b9e79-5b94-4456-8b02-74c1f10bbd61.png)

**Comment by alanorozco** [comment]
Hi. This can be done with CSS. You can write any kind of CSS on an AMP page. You can find [many tutorials](https://www.google.com/search?q=circular+progress+bar+css) online.

**Comment by router-hub** [comment]
> Hi. This can be done with CSS. You can write any kind of CSS on an AMP page. You can find [many tutorials](https://www.google.com/search?q=circular+progress+bar+css) online.

Hey thanks, but we need to put the dynamic value. So, only CSS will not work. Can you please suggest something else.
