### ISSUE TITLE
gulp dist fails

### ISSUE THREAD

**Issue by dknecht** [ampproject/amphtml#3649]
Running `gulp dist` on OS X El Capitan I am failing here:

`Minifying amp-login-done-0.1.max.js
Command failed: java -jar -XX:+TieredCompilation build-system/runner/dist/runner.jar --flagfile="/var/folders/2h/9l7nysd16sq7dtr3gm9sbjfw0000gn/T/4be74401-f6ad-49d8-aac5-5801f2157587" --compilation_level=SIMPLE_OPTIMIZATIONS --assume_function_wrapper=true --language_in=ECMASCRIPT6 --language_out=ECMASCRIPT5 --externs=build-system/amp.extern.js --externs=third_party/closure-compiler/externs/intersection_observer.js --js_module_root=node_modules/ --js_module_root=build/patched-module/ --js_module_root=build/fake-module/ --entry_point=./src/amp-babel.js --process_common_js_modules=true --only_closure_dependencies=true --output_wrapper=window.AMP_CONFIG||(window.AMP_CONFIG={"canary":false});/*AMP_CONFIG*/try{(function(){var process={env:{NODE_ENV:"production"}};%output%})()}catch(e){setTimeout(function(){var s=document.body.style;s.opacity=1;s.visibility="visible";s.animation="none";s.WebkitAnimation="none;"},1000);throw e};
//# sourceMappingURL=v0.js.map`

I am using git tag 1466185787499 

javac -version
javac 1.8.0_77

Any suggestions on how to debug?

**Comment by erwinmombay** [comment]
@dknecht is that all of the error log? did you run `gulp build` before running `gulp dist` (unfortunately they have a dependency)

**Comment by dknecht** [comment]
No i didn't.   That makes sense.   What commands are you using before you push to cdn.amprojrect.org.  I can't seem to replicate.  I am seeing the start of v0.js on cdn.amproject.org `window.AMP_CONFIG={"canary":false,"amp-sidebar":1,"amp-social-share":1,"v":"011466016447690"};`

vs `gulp dist`

`window.AMP_CONFIG||(window.AMP_CONFIG={"canary":false});`

**Comment by erwinmombay** [comment]
i run:

```bash
gulp clean
gulp build
gulp dist
```

**Comment by dknecht** [comment]
Then does the google amp cache server add "window.AMP_CONFIG={"canary":true,"amp-sidebar":1,"amp-social-share":1,"v":"001466185787499"};" ?

**Comment by erwinmombay** [comment]
@dknecht our internal release process adds those in. (mostly just flags for any new component)

**Comment by erwinmombay** [comment]
@dknecht closing. feel free to open if you have more questions :+1:
