### ISSUE TITLE
amp-analytics config parser chokes on JS-escaped value

### ISSUE THREAD

**Issue by lukebjerring** [ampproject/amphtml#3651]
[AmpAnalytics analytics]" "Analytics config could not be parsed. Is it in a valid JSON format?" SyntaxError: Unexpected token x in JSON at position 237(…)

## How do we reproduce the issue?
With this input:

```
<amp-analytics id='analytics'>
<script type='application/json'>
      {
        "vars": {
          "account": "UA-XXXXXXXX-X"
        },
        "triggers": {
          "trackPageview": {
            "on": "visible",
            "request": "pageview",
            "vars": {
              "title": "It\x27s not working...",
              "ampdocUrl": "http://foo.com/"
            }
          }
        }
      }
      </script>
</amp-analytics>
```

## What browsers are affected?

Def Chrome, probably all browsers.

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1466016447690

**Comment by avimehta** [comment]
Tested this in Chrome and Firefox and it reproduces in both the browsers. 

This is a weird error case. Officially, JSON RFC requires Unicode encoding. So the escape sequence should be `\u0027` or in this case, directly putting the `'` in the string is fine. Browsers however behave strangely for the config listed in the bug: `JSON.parse('{"title": "It\x27s not working..."}')` works without error. However, when I put that config in an HTML element as follows and then try to parse it, I get:

```
<script type="application/json">
      {
              "title": "It\x27s not working...",
      }
</script>
```

```
JSON.parse($0.textContent)
```
Result: 
```
Uncaught SyntaxError: Unexpected token x in JSON at position 36
```

Not sure what the correct fix would be here but here are workarounds for now:

```
<amp-analytics id='analytics'>
<script type='application/json'>
...
              "title": "It's working...",
...
</script>
</amp-analytics>
```

or 
```
<amp-analytics id='analytics'>
<script type='application/json'>
...
              "title": "It\u0027s working...",
...
</script>
</amp-analytics>
```

**Comment by avimehta** [comment]
Forgot to add links to previous section. RFC section is here: https://tools.ietf.org/html/rfc7159#section-7

Also, http://www.json.org/ shows what all characters need to be escaped.

I am inclined to mark this as working as intended. Please reopen the issue and chime in if(and why) this doesn't work for you.
