### ISSUE TITLE
Intent to implement: amp-analytics type: cxense

### ISSUE THREAD

**Issue by SteinHDanCxense** [ampproject/amphtml#3654]
We would like to contribute code to add support for Cxense Insight analytics to amp-analytics.

A pull request will be submitted shortly.

The CLA is already signed by me (stein.danielsen@cxense.com) on behalf of Cxense ASA

Best regards,
Stein H. Danielsen

**Comment by dandv** [comment]
For the record and SEO, [Cxense analytics docs](https://www.ampproject.org/docs/guides/analytics/analytics-vendors#cxense).
