### ISSUE TITLE
Carousel: clarify what to do with "loop" option

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#366]
Currently "loop" option is implemented by default in slides. We can make it turn on/off depending on "loop" attribute. But another thing to keep in mind - "loop" makes no sense to scrolling carousel.

**Comment by erwinmombay** [comment]
work being done on https://github.com/ampproject/amphtml/pull/555

**Comment by erwinmombay** [comment]
fixed via https://github.com/ampproject/amphtml/pull/555
