### ISSUE TITLE
Strategy for rendering from user-provided templates on Bento standalone

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#36619]
Components like `<bento-date-countdown>` don't support the `<template>` like the AMP layer does with Mustache.

We require a strategy to support HTML templates for `bento-date-countdown` and `bento-date-display`.

**Comment by dmanek** [comment]
Using this to track I2I for a [Bento Mustache service](https://docs.google.com/document/d/1HjXFO5jXXoQBQrXEt9sgf89vtBuNXntylgdj2KPhGH4/edit#).
