### ISSUE TITLE
[Story] Only run amp-story.rewriteStyles_() when needed

### ISSUE THREAD

**Issue by gmajoulet** [ampproject/amphtml#36660]
### Description

`amp-story.rewriteStyles_()` does not need to run in non one-panel-desktop contexts.

https://github.com/ampproject/amphtml/blob/f3a2396ebb56af80680f9460dc5f489b7b4f5c5e/extensions/amp-story/1.0/amp-story.js#L547-L561

cc @ampproject/wg-stories @Gregable 

### Alternatives Considered

-

**Comment by newmuis** [comment]
Don't we still need this in one panel desktop?  `100 * var(--story-page-vw)` should be the width of the panel, rather than the full viewport.

**Comment by gmajoulet** [comment]
Absolutely, sorry I made the initial sentence confusing with a double negation, it does only need to run in one panel desktop!
