### ISSUE TITLE
Ensure that JSON-response XHR fetchers require correct Content-Type in the response

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#3667]
It sounds like we do not currently check the response's content-type in `xhr-impl.js` before parsing the JSON. We should do it. But at this point, we need to be careful with publishers who may have not set it up correctly, so we may want to do it via an experiment and monitor errors.

**Comment by mkhatib** [comment]
Just chatted about this, basically we wanna look and see how the fetch API handles this currently and see how to act on it. If it fails we need to start reporting this in production to see if this is already being "misused" widely and figure out a way to address this.

**Comment by mkhatib** [comment]
@dvoytenko someone just ran into this inconsistency now between error and success responses. Our implementation now checks for json-type for error responses but we still lack on the success front. Not sure how we can do this without breaking existing implementations, any idea?

One thing we can do for now is to document this inconsistency somewhere.

**Comment by dvoytenko** [comment]
@mkhatib Well. That's a bummer. Anyway to estimate what we'd break?

**Comment by adelinamart** [comment]
@dvoytenko does this needs to be closed? Thanks

**Comment by dvoytenko** [comment]
Yeah. This looks like to late to change.
