### ISSUE TITLE
JS Parsing & initialization is taking more time which blocks amp-image

### ISSUE THREAD

**Issue by rajkumarsrk** [ampproject/amphtml#3668]
JS Parsing & initialization is taking more time (approximately 250ms on desktop and 500ms to 700ms on mobile devices). And this delays the image downloads on amp-image tag(above the fold), addressing this would speed up the pages. 

Steps to reproduce:
1) Load [eBay AMP](https://cdn.ampproject.org/c/m.ebay.com/sch/amp/Camera-Drones/179697/bn_89951/i.html) on chrome browser. 
2) Have the network tab on chrome browser enabled, for cache enabled case the JS files were resolved within 150ms and the image download starts only by 400ms.
3) Mobile simulated use case with chrome dev tools and good 3G n/w the delay increases to 500ms

What browsers are affected?
Chrome

AMP version: 1466016447690

Is this a new issue? Nope. This was there from the beginning on chrome

WebPageTest report:
http://www.webpagetest.org/result/160620_GC_7913c15b0904e9ea00d3b51abdc74a73/1/details/
http://www.webpagetest.org/result/160601_GB_d83c4b220c5b7d2e67771491f93410b3/

Simulated on Nexus 5X & Good 3G n/w settings (250ms delay on first image download)
<img width="1127" alt="screen shot 2016-06-20 at 1 06 10 pm" src="https://cloud.githubusercontent.com/assets/691176/16208739/7292ee50-36e8-11e6-84ac-db1877adbfbb.png">

On desktop chrome (250ms delay on first image download):
<img width="785" alt="screen shot 2016-06-20 at 12 26 18 pm" src="https://cloud.githubusercontent.com/assets/691176/16208773/9f7f0e76-36e8-11e6-99e6-33a1474c822b.png">

**Comment by cramforce** [comment]
This is, of course, to some extend working as intended, but we also really try to optimize this to be as short as possible.

I was playing with your example on my machine and was seeing better behavior. For this it is much better to use the Timeline view instead and activate network requests there (might not be in Stable yet).

**Comment by ericlindley-g** [comment]
@cramforce — slotting in backlog, but please correct/update as needed
