### ISSUE TITLE
SVGs not rendering within stories

### ISSUE THREAD

**Issue by coreymasanto** [ampproject/amphtml#36713]
### Description

The `layoutCallback` of `AmpStoryPageAttachment` is throwing an error at main, which is generally causing the page attachment and its button to not appear. The cause appears to be that the `this.element.querySelector('.i-amphtml-story-draggable-drawer-spacer')` call returns `null` in the `initializeListeners_()` method of `amp-story-draggable-drawer.js` [here](https://github.com/ampproject/amphtml/blob/5ebed6330d47628aa06e859c55010a93cef1bf09/extensions/amp-story/1.0/amp-story-draggable-drawer.js#L187-L189). Upon further inspection, all of the attachment's child elements are all absent from the attachment at this point in the execution.

Running `git bisect` between the latest commit on main and an old working PR (#36133) appears to show that PR #36682 is the first bad commit. Assigning to the author and CCing the reviewers.

/cc @gmajoulet  @processprocess @mszylkowski @jshamble 

### Reproduction Steps

1. Run a local AMP server at main
2. Go to http://0.0.0.0:8000/examples/amp-story/attachment.html
3. Observe that each page's attachment is broken

**Comment by processprocess** [comment]
This appears to still be an issue when commenting out `initializeListeners_`.

This may be related to the element not having a height since it looks like some pieces are building.

https://user-images.githubusercontent.com/3860311/139925293-7946715f-ef88-4762-a52e-958f089ff914.mp4

**Comment by processprocess** [comment]
re-starting the dev-server seems to resolve the issue.

**Comment by processprocess** [comment]
It looks like SVGs aren't rendering. [This code](https://github.com/ampproject/amphtml/blob/main/extensions/amp-story/1.0/amp-story-open-page-attachment.js#L73-L85) doesn't appear to be rendered:
<img width="35" alt="Screen Shot 2021-11-02 at 3 27 55 PM" src="https://user-images.githubusercontent.com/3860311/139940649-fc832e5d-9975-4e8e-9a58-73179396c916.png">

From page 7 of `examples/amp-story/attachment.html`

**Comment by coreymasanto** [comment]
Philip pointed out that the original issue of the broken attachments is resolved by restarting the dev server, and Alan suggested that it may have just been a babel cache issue. I'll rename this issue to reflect the pivot to the SVG rendering bug.
