### ISSUE TITLE
Facebook test still waits for FB code

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#3675]
The one test that doesn't use a fake iframe still waits for onload of the iframe which depends on the external resource.

**Comment by mkhatib** [comment]
This is the resize test right? I filed #3662 this morning - @muxin was working on this, Yuxi let me know if you want me to take this over?

**Comment by cramforce** [comment]
Yep

**Comment by mkhatib** [comment]
Closing this for #3662
