### ISSUE TITLE
[AMP Owners Bot] OWNERS cannot approve their own PRs

### ISSUE THREAD

**Issue by zvalmog** [ampproject/amphtml#36855]
### Description

OWNERS cannot approve their own PRs as demonstrated in https://github.com/ampproject/amphtml/pull/36833#issuecomment-963890165
#https://github.com/ampproject/amphtml/pull/36833

### Reproduction Steps

1. Fork project as a vendor
2. Become OWNER of vendor asset
3. Submit PR
4. Can't approve your own PR

**Comment by kristoferbaxter** [comment]
Approval for PRs still require another member of the owner group. This is intentional to ensure more than one person is viewing changes.
