### ISSUE TITLE
Meta I2D: Deprecate Periodic Asia/Oceania Design Reviews

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#36888]
### Context

The AMP Projects holds [public weekly design reviews](https://github.com/ampproject/amphtml/blob/main/docs/design-reviews.md#design-reviews) on Wednesdays.  In order to be inclusive of our global network of AMP Contributors, we cycle the timezone of the meeting between one convenient for Americas, Asia/Oceania, and Africa/Europe/western Asia.

We've historically had incredibly poor attendance for Asia/Oceania reviews. This is a problem because design reviews are only useful if we have a sizable number of folks to give guidance and help make decisions.

### Proposal

Remove the the Asia/Oceania design review from our weekly rotation as well as update the guidance in our documentation for how to create ad-hoc meetings.

Our current documentation says:

> If none of the design review times are convenient for you and you have a design you would like to discuss please reach out to mrjoro on Slack.

We should improve this s.t. we don't have a single point-of-contact.
We can create a `#design-review` channel on Slack for folks to reach out on. Through that channel we can schedule design reviews and ensure appropriate reviewers.

### Deprecation Plan

2. Created a dedicated slack channel for design review questions/requests.
2. Modify our design review documentation to recommend reaching out on the new channel.
3. Modify our scripts to stop generating Design Review issues for Asia/Oceania timezone.

### Notifications

@ampproject/wg-approvers

**Comment by kristoferbaxter** [comment]
Thanks for taking these notes @samouri. The updated approach looks great to me.

Can you work with @alanorozco to alter scripts to match?

**Comment by samouri** [comment]
> Can you work with @alanorozco to alter scripts to match?

Alan had completed the PR that updates the scripts before I had even finished presenting 😄

**Comment by kristoferbaxter** [comment]
Whoa! Amazing. Nice work @alanorozco!

**Comment by samouri** [comment]
Our documentation states I need at least 3 approval from @ampproject/wg-approvers for I2Ds.
Is that still true? If so I'll hold off until I have two more approvals.

**Comment by rsimha** [comment]
+1, I approve this change. Thanks for improving the usefulness of our design review meetings, @samouri and @alanorozco!

**Comment by jridgewell** [comment]
Approved

**Comment by samouri** [comment]
Closing as the timezone has been removed from the rotation after the 2nd cancelled one.
