### ISSUE TITLE
Default CDN URLs for Bento files should be Nightlies

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#36897]
Bento binaries are not in use in production, so releasing them on a more frequent basis is not risky.
Tying them to the AMP release process is preventing us from iterating quickly.

Where "base" urls currently would point to Stable, or a configured RTV, **if the path's basename starts with `bento`**, these should always point to the Nightly RTVs instead:

```
https://cdn.ampproject.org/bento.mjs
https://cdn.ampproject.org/v0/bento-accordion-1.0.mjs
```

**Comment by rsimha** [comment]
@alanorozco  Could you provide context for the relative urgency of this change?

Looping in @danielrozenberg and @estherkim  to comment on what it would take to implement.

**Comment by alanorozco** [comment]
@rsimha There are some changes that block Bento release which have already been merged on the repository but have not yet made it to Beta. Using the nightly releases of `bento*` files would unblock us.

**Comment by estherkim** [comment]
@alanorozco which nightly did those changes go out in? I can publish that as latest in order to unblock.

re: un-tying from the release cadence - let's discuss offline to figure out what would work.

**Comment by estherkim** [comment]
Following up here - we decided this would greatly affect the serving infrastructure, and would need an I2I + design review.

Lmk whether you'd like to continue or close.

**Comment by danielrozenberg** [comment]
Closing as outdated
