### ISSUE TITLE
Optimize the `bento.js` shared dependency bundle

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#36899]
**summary**
`bento.js` is a new binary containing dependencies which all of the bento extensions depend on ([1](https://github.com/ampproject/amphtml/pull/36432)). Things like Preact and PreactBaseElement. We should optimize this bundle to be as small as possible.

**source-map-explorer**
![image (1)](https://user-images.githubusercontent.com/4656974/141345170-22408f5f-c87d-4246-a5ec-0c3cd2a5960a.png)

**starting size**: 17.62 kb brotli, 54.93 kb uncompressed
**goal**: < 10 kb brotli

**opportunities**
- [x] (S) minimize cost of `preact/compt`: ~1.65
- [x] (S) parseProps
- [x] (S) CE Polyfill ~1.5
- [ ] (L) minimize or remove Context: ~3kb
- [ ] _your idea here_

cc @ampproject/wg-performance  / @ampproject/wg-bento / @ampproject/wg-components

**Comment by rcebulko** [comment]
Do we need the CE polyfill on all/most browsers?

**Comment by alanorozco** [comment]
@rcebulko It's stripped out from the module build.

**Comment by alanorozco** [comment]
We can split out `parse-props.js`:

- `{attrPrefix}` is trivial (#36947). This shaves about 120B compressed.
- `{selector}` is less trivial, but would have a bigger impact (~500B) since it would extract `<Slot>` as well.

**Comment by alanorozco** [comment]
> starting size: 17.62 kb brotli

`bento.mjs` is at 15.03 kb after recent changes to remove: 

- side-effects from including `forwardRef`
- `createPortal`

**Comment by samouri** [comment]
Current `bento.mjs` is currently at 14.5 kb

**Comment by samouri** [comment]
@alanorozco  / @kvchari  / @jridgewell: I believe we can remove AMP Context from the CDN's `bento.mjs` and `bento.core.module.js`

**Comment by rcebulko** [comment]
AMP context may be consumed by the log system, which might still be used by bento internals. Not sure, would have to look at binaries or dependency trees
