### ISSUE TITLE
Build system broken - stuck on bundle size and pr-deploy 

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#36893]
### Description

As of writing the bundle size and pr-deploy checks have been stuck for over 2 hrs on #36891 & #36890 (vs < 20 mins normally)

### Reproduction Steps

See #36891 & #36891

**Comment by kristoferbaxter** [comment]
Don’t see anything strange from mobile client, but can check on desktop when I’m back soon.

**Comment by kristoferbaxter** [comment]
Also adding @rsimha and @danielrozenberg.

**Comment by danielrozenberg** [comment]
Looks like both of those PRs had unrelated, transient errors.
@alanorozco fixed #36890 by pushing a new commit, which re-ran the bundle-size bot
I fixed #36894 (which replaced #36891) by pushing an empty commit to that branch which triggered a CircleCI job

I think it's safe to close this as a flake, but please reopen if you see this again!
