### ISSUE TITLE
Use crypto.subtle instead of closure's sha384 where available

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#3690]
And late load closure implementation when needed (none of the current major browsers).

The resulting strings must by byte-for-byte compatible.

CC @lannka

**Comment by ericlindley-g** [comment]
@cramforce — slotting in backlog, but please correct/update as needed

**Comment by lannka** [comment]
Did some experiments.

- Latest Chrome, FireFox, Edge, Opera have full support of `window.crypto.subtle.digest()`;
- Safari supports it with `window.crypto.webkitSubtle.digest`.
- IE11 supports it with `window.msCrypto.subtle.digest()`; however, `SHA-1` is not supported; and the return is not a `Promise`

Basically all browsers AMP supports have usable implementations except Android 4.x system browsers.

@cramforce Do you think it's still necessary to have the fallback of late loading closure implementation?

**Comment by cramforce** [comment]
What I think we should do is:

- create a `CryptoService` or similar
- use that across this, analytics, CID, etc.
- have it use builtin by default
- and late load closure otherwise.

**Comment by lannka** [comment]
The work is done except the lazy loading part. Can open a separate issue if wanted.

**Comment by jridgewell** [comment]
> Can open a separate issue if wanted.

Please.
