### ISSUE TITLE
[amp story shopping] Add Object typedef for shopping data

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#36911]
### Description

A typedef for `SHOPPING_DATA` will help developers/reviewers understand the code.

Check out the example for interactives in [component](https://github.com/ampproject/amphtml/blob/main/extensions/amp-story-interactive/0.1/amp-story-interactive-abstract.js#L62-L89) in store service [here](https://github.com/ampproject/amphtml/blob/main/extensions/amp-story/1.0/amp-story-store-service.js#L53-L70) and [here](https://github.com/ampproject/amphtml/blob/main/extensions/amp-story/1.0/amp-story-store-service.js#L91-L92).

This is a follow up to [this comment](https://github.com/ampproject/amphtml/pull/36757#discussion_r743655235).

**Comment by jshamble** [comment]
Closing this as I am solving it in #36699

**Comment by processprocess** [comment]
Re opening this. 
Please do not close issues before they are merged.
Please add "Closes #36911" to the description in #36699 that way it will automatically be closed when that code is merged.
