### ISSUE TITLE
AMP Cache URL NOT Updating from Reader/Transitional to Standard Mode 

### ISSUE THREAD

**Issue by kuknusads** [ampproject/amphtml#36922]
### Description

I run a free listing site on WordPress and all my pages are AMP enabled.
I am currently on Standard Template Mode: https://imgur.com/a/CWuovK5

Issue is this: AMP Cache is using legacy (/amp) (/?amp) urls to update content.

LIVE URL: https://kuknus.com/laptops/

[**NOT Updating**] Standard Mode AMP Cache URL: https://kuknus-com.cdn.ampproject.org/c/s/kuknus.com/laptops/

[Updating] Reader Mode/Legacy Mode: https://kuknus-com.cdn.ampproject.org/c/s/kuknus.com/laptops/amp/

I happen to change setting from Standard to Reader mode once & then from Reader to Standard immediately. There is some sort of bug which is keeping AMP Cache URL setting to be legacy URLs even after changing mode to Standard.

Please help!

### Reproduction Steps

AMP Page URL: https://kuknus.com/laptops/

[**NOT Updating**] Standard Mode AMP Cache URL: https://kuknus-com.cdn.ampproject.org/c/s/kuknus.com/laptops/

Premium Dummy Listing is NOT showing up on AMP Cache URL.

### Browser(s) Affected

Chrome

### OS(s) Affected

Android

### Device(s) Affected

Google Pixel

### AMP Version Affected

2.1.4

**Comment by twifkak** [comment]
Hi @kuknusads, so sorry for the delay. Is this still occurring? I see that https://kuknus.com/laptops/ and https://kuknus-com.cdn.ampproject.org/c/s/kuknus.com/laptops/ now look similar.
