### ISSUE TITLE
[amp story 360] Context not restoring on desktop Chrome

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#36944]
### Description

Context restoring is not working on desktop Chrome.

<img width="611" alt="Screen Shot 2021-11-16 at 11 56 26 AM" src="https://user-images.githubusercontent.com/3860311/142030040-102f91e3-63a9-4866-b508-71ea6e26775f.png">

Additional context.
Does not appear to be due to background blur, which creates context2d. 
Disabling background blur does not appear to effect the problem.

### Reproduction Steps

On Mac Chrome
Go to a 360 story like:https://wsdemos.uc.r.appspot.com/homewarrior
Go to page 9
Go back to page 8
360 component should appear not to render.

### Browser(s) Affected

Chrome

### Device(s) Affected

Macbook

**Comment by ychsieh** [comment]
Not reproducible.
