### ISSUE TITLE
I2I: Modernize amp-story system layer [WIP]

### ISSUE THREAD

**Issue by mszylkowski** [ampproject/amphtml#36951]
### Summary

We want to update the system layer of amp-story both in functionality and appearance.

The visual changes will mostly consist in updating the visuals to a modernized, rounded, outlined version of the icons and remove the material design icons we currently have.

In terms of functionality, we want to improve the sound icons with better signals and new toggles:
- The sound icon will now use the video cache `hasAudio` signal
- The CC (closed captions) icon will be added, and will toggle the captions on the story
- The equalizer will be removed since it's redundant and it collides with the "loading spinner" icon of buffering videos.

Other changes of the system layer:
- Icons that are not needed on a page will now disappear instead of being disabled with opacity (mute, CC, pause). We've ran a UXE and found out that on pages without audio, users get confused about the icons, so we can hide the unused icons.
- Improved the scrim gradient to be taller and have a smoother gradient.
- Define the icons' sizes in a responsive way so the system layer looks good in all sizes.

Explorations (not included in I2I):
- Group icons my functionality (eg: using translucent pills).
- Position icons vertically to improve reach with fingers while one-handed.

[Draft](https://github.com/ampproject/amphtml/pull/36920)

Screenshot:
![image](https://user-images.githubusercontent.com/22420856/142071727-eda430c6-015e-4d11-88f4-9d582e630bd2.png)

All icons:
![image](https://user-images.githubusercontent.com/22420856/142071880-3efc3758-0428-4db5-ae58-5f17316816ba.png)

### Motivation

The current icons are material design icons but don't fit the format properly. The new set of icons behave as expected, are less confusing and look better, adding visual richness and character to the experience.

### Notifications

/cc @ampproject/wg-approvers

**Comment by choumx** [comment]
+1 to the CC button. :) 

Would it be possible to allow authors to specify the default display state of captions? E.g. I'd like it to be on by default, but I believe that would require manually overriding browser defaults in JS (e.g. iOS browsers appear to use the `Settings > Accessibility` setting which is off by default).

**Comment by mszylkowski** [comment]
> Would it be possible to allow authors to specify the default display state of captions?

That's a good question not addressed in this I2I, as currently if authors want to show captions, they just add the captions to the story (we're assuming that users generally prefer to have captions if they are available). The current implementation we have in the demo follows the `<video>` element, which is to initially show the captions if they are available.

This model can be improved and it's sth we can add support independently of this I2I to honor user preferences (eg: if I disable captions on a story, to disable them for all future stories) or honor creator preferences (to allow them to disable them by default but provide them if users want).
