### ISSUE TITLE
Integration Saucelabs flakey test extensions

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#3695]
``` bash
Safari 9.0.0 (Mac OS X 10.11.0) test extensions loading in multiple orders one extension, v0 loads first, all scripts in header FAILED
    Timeout waiting for elements to start loading.
    /tmp/0d552ef2601c3d0c0364235627db66c3.browserify:29870:25 <- /home/travis/build/ampproject/amphtml/testing/iframe.js:128:25
........
Safari 9.0.0 (Mac OS X 10.11.0): Executed 46 of 81 (1 FAILED) (skipped 35) (27.124 secs / 16.169 secs)
21 06 2016 19:33:46.365:WARN [Safari 8.0.8 (Mac OS X 10.10.5)]: Disconnected (1 times), because no message in 240000 ms.
Safari 8.0.8 (Mac OS X 10.10.5): Executed 36 of 81 (skipped 14) DISCONNECTED (4 mins 37.896 secs / 8.019 secs)
21 06 2016 19:33:46.366:ERROR [reporter.sauce]: ✖ Test Disconnected
```

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
