### ISSUE TITLE
[amp-next-page]  AMP Client ID missing when scrolling through to amp-next-page in AMP Viewer

### ISSUE THREAD

**Issue by Alanhui** [ampproject/amphtml#36984]
### Description

The AMP Client ID (used in amp-analytics) is missing on scrolling into amp-next-page in an amp viewer (but not on publisher origin).

### Reproduction Steps

1. Go to https://www.google.com/amp/s/www.cnet.com/google-amp/news/nasa-curiosity-rover-snaps-dramatic-mars-selfie-at-scenic-mont-mercou/ in mobile emulator with network tab open in Devtools.

2. Scroll through and into the second article.

3. Search for "collect?" in the network tab. You should see two GA pageview records. the CID in second article is missing

Similar issue to: https://github.com/ampproject/amphtml/issues/32305

### Browser(s) Affected

Chrome, Safari

### AMP Version Affected

2111060251003

**Comment by kristoferbaxter** [comment]
@dmanek Can you take a look at this issue that appears related to `amp-next-page`?

**Comment by dmanek** [comment]
Taking a look.

**Comment by dmanek** [comment]
@alanorozco can you PTAL?
