### ISSUE TITLE
Validation error when adding cta-text attribute to the amp-story-page-outlink element

### ISSUE THREAD

**Issue by joaorafaelsantos** [ampproject/amphtml#36988]
### Description

Using the cta-text attribute in the amp-story-page-outlink generates the following error: "The attribute 'cta-text' may not appear in tag 'amp-story-page-outlink'".

Probably it's related with #36425.

### Reproduction Steps

Just add a cta-text attribute to the amp-story-page-outlink element.

[AMP Playground Example](https://playground.amp.dev/?format=websites#share=PCEtLQogICMjIEludHJvZHVjdGlvbgoKICBMZWFybiBob3cgdG8gY3JlYXRlIHlvdXIgZmlyc3QgQU1QIFN0b3J5LiBUaGUgW2BhbXAtc3RvcnlgXSgvY29udGVudC9hbXAtZGV2L2RvY3VtZW50YXRpb24vY29tcG9uZW50cy9yZWZlcmVuY2UvYW1wLXN0b3J5LXYxLjAubWQpIGV4dGVuc2lvbiBwcm92aWRlcyBhIG5ldyBmb3JtYXQgZm9yIGRpc3BsYXlpbmcgdmlzdWFsIGNvbnRlbnQuCi0tPgo8IS0tIC0tPgo8IWRvY3R5cGUgaHRtbD4KPGh0bWwgYW1wIGxhbmc9ImVuIj4KICA8aGVhZD4KICAgIDxtZXRhIGNoYXJzZXQ9InV0Zi04Ij4KICAgIDxzY3JpcHQgYXN5bmMgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC5qcyI+PC9zY3JpcHQ+CiAgICA8IS0tICMjIFNldHVwIC0tPgogICAgPCEtLSBBTVAgU3RvcmllcyBhcmUgd3JpdHRlbiB1c2luZyBBTVBIVE1MIGFuZCB0aGV5IHVzZSB0aGVpciBvd24gQU1QIGV4dGVuc2lvbjogYGFtcC1zdG9yeWAuIFRoZSBmaXJzdCBzdGVwIGlzIHRvIGltcG9ydCB0aGUgYGFtcC1zdG9yeWAgaW4gdGhlIGhlYWRlci4gLS0+CiAgICA8c2NyaXB0IGFzeW5jIGN1c3RvbS1lbGVtZW50PSJhbXAtc3RvcnkiIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAvYW1wLXN0b3J5LTEuMC5qcyI+PC9zY3JpcHQ+CiAgICA8IS0tIEFNUCBTdG9yaWVzIGNhbiBtYWtlIHVzZSBvZiBvdGhlciBBTVAgZXh0ZW5zaW9ucyBzdWNoIGFzIGBhbXAtdmlkZW9gLiBIb3dldmVyLCBBTVAgU3RvcmllcyBzdXBwb3J0IG9ubHkgYSBzdWJzZXQgb2YgdGhlIGF2YWlsYWJsZSBBTVAgZXh0ZW5zaW9ucy4gWW91IGNhbiBmaW5kIGEgZnVsbCBsaXN0IG9mIHRoZSBzdXBwb3J0ZWQgZXh0ZW5zaW9ucyBbaGVyZV0oL2NvbnRlbnQvYW1wLWRldi9kb2N1bWVudGF0aW9uL2NvbXBvbmVudHMvcmVmZXJlbmNlL2FtcC1zdG9yeS5tZCNjaGlsZHJlbi1vZi1hbXAtc3RvcnktZ3JpZC1sYXllcikuIC0tPgogICAgPHNjcmlwdCBhc3luYyBjdXN0b20tZWxlbWVudD0iYW1wLXZpZGVvIiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC12aWRlby0wLjEuanMiPjwvc2NyaXB0PgogICAgPHRpdGxlPlN0b3JpZXMgaW4gQU1QIC0gSGVsbG8gV29ybGQ8L3RpdGxlPgogICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCI+CiAgICA8bGluayByZWw9ImNhbm9uaWNhbCIgaHJlZj0iaHR0cHM6Ly9hbXAuZGV2L2RvY3VtZW50YXRpb24vZXhhbXBsZXMvaW50cm9kdWN0aW9uL3N0b3JpZXNfaW5fYW1wL2luZGV4Lmh0bWwiPgogICAgPHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1vei1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDstbXMtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7YW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGh9QC13ZWJraXQta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtbW96LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1zLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW8ta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUBrZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19PC9zdHlsZT48bm9zY3JpcHQ+PHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOm5vbmU7LW1vei1hbmltYXRpb246bm9uZTstbXMtYW5pbWF0aW9uOm5vbmU7YW5pbWF0aW9uOm5vbmV9PC9zdHlsZT48L25vc2NyaXB0PgogICAgPCEtLSBTdG9yaWVzIGNhbiBiZSBzdHlsZWQgdXNpbmcgQ1NTOiAtLT4KICAgIDxzdHlsZSBhbXAtY3VzdG9tPgogICAgICBhbXAtc3RvcnkgewogICAgICAgIGZvbnQtZmFtaWx5OiAtYXBwbGUtc3lzdGVtLCBCbGlua01hY1N5c3RlbUZvbnQsICJTZWdvZSBVSSAiLCBSb2JvdG8sIEhlbHZldGljYSwgQXJpYWwsIHNhbnMtc2VyaWYsICJBcHBsZSBDb2xvciBFbW9qaSAiLCAiU2Vnb2UgVUkgRW1vamkgIiwgIlNlZ29lIFVJIFN5bWJvbCAiOwogICAgICB9CiAgICAgIGFtcC1zdG9yeS1wYWdlICogewogICAgICAgIGNvbG9yOiB3aGl0ZTsKICAgICAgICB0ZXh0LWFsaWduOiBjZW50ZXI7CiAgICAgIH0KICAgICAgW3RlbXBsYXRlPXRoaXJkc10gewogICAgICAgIHBhZGRpbmc6IDA7CiAgICAgIH0KICAgIDwvc3R5bGU+CiAgPC9oZWFkPgoKICA8Ym9keT4KICAgIDwhLS0gIyMgV3JpdGluZyB0aGUgU3RvcnkgLS0+CiAgICA8IS0tIFN0b3JpZXMgYXJlIGRlY2xhcmVkIGluc2lkZSB0aGUgYGFtcC1zdG9yeWAgdGFnLiBTdG9yeS1sZXZlbCBtZXRhZGF0YSBpcyBwcm92aWRlZCB2aWEgYXR0cmlidXRlcy4gKFRoZSBmaXJzdCBmb3VyIGF0dHJpYnV0ZXMgYXJlIG1hbmRhdG9yeTsgdGhlIGZpbmFsIHR3byBhcmUgb3B0aW9uYWwsIGJ1dCByZWNvbW1lbmRlZC4pIE5vdGUgdGhhdCB0aGlzIG1ldGFkYXRhIGF1Z21lbnRzLCBidXQgZG9lcyBub3QgcmVwbGFjZSwgW1N0cnVjdHVyZWQgRGF0YV0oaHR0cHM6Ly9kZXZlbG9wZXJzLmdvb2dsZS5jb20vc2VhcmNoL2RvY3MvZGF0YS10eXBlcy9hcnRpY2xlI2FtcCkuIC0tPgogICAgPGFtcC1zdG9yeSBzdGFuZGFsb25lCiAgICAgIHRpdGxlPSJTdG9yaWVzIGluIEFNUCAtIEhlbGxvIFdvcmxkIgogICAgICBwdWJsaXNoZXI9IkFNUCBQcm9qZWN0IgogICAgICBwdWJsaXNoZXItbG9nby1zcmM9Imh0dHBzOi8vYW1wLmRldi9mYXZpY29ucy9jb2FzdC0yMjh4MjI4LnBuZyIKICAgICAgcG9zdGVyLXBvcnRyYWl0LXNyYz0iaHR0cHM6Ly9hbXAuZGV2L3N0YXRpYy9zYW1wbGVzL2ltZy9zdG9yeV9kb2cyX3BvcnRyYWl0LmpwZyIKICAgICAgcG9zdGVyLXNxdWFyZS1zcmM9Imh0dHBzOi8vYW1wLmRldi9zdGF0aWMvc2FtcGxlcy9pbWcvc3RvcnlfZG9nMl9zcXVhcmUuanBnIgogICAgICBwb3N0ZXItbGFuZHNjYXBlLXNyYz0iaHR0cHM6Ly9hbXAuZGV2L3N0YXRpYy9zYW1wbGVzL2ltZy9zdG9yeV9kb2cyX2xhbmRzY2FwZS5qcGciPgoKICAgICAgPCEtLSBBIHN0b3J5IGNvbnNpc3RzIG9mIG9uZSBvciBtb3JlIHBhZ2VzLiBFYWNoIHBhZ2UgaXMgZGVjbGFyZWQgYnkgYW4gYGFtcC1zdG9yeS1wYWdlYCBlbGVtZW50LiBQYWdlcyBhcmUgZGVzaWduZWQgYnkgbGF5ZXJpbmcgdmlkZW9zLCBpbWFnZXMgYW5kIHRleHQuIEhlcmUgd2UgaGF2ZSBhIHBhZ2UgdGhhdCB1c2VzIHR3byBsYXllcnMuIE9uZSBsYXllciBmaWxsaW5nIHRoZSBhdmFpbGFibGUgc3BhY2Ugd2l0aCBhbiBpbWFnZSBhbmQgb25lIHRleHQgbGF5ZXIgdGhhdCBzaG93cyBhIGhlYWRpbmcuIC0tPgogICAgICA8YW1wLXN0b3J5LXBhZ2UgaWQ9InBhZ2UtMSI+CiAgICAgICAgPGFtcC1zdG9yeS1ncmlkLWxheWVyIHRlbXBsYXRlPSJ2ZXJ0aWNhbCI+CiAgICAgICAgICA8aDE+SGVsbG8gV29ybGQ8L2gxPgogICAgICAgICAgPHA+VGhpcyBpcyBhbiBBTVAgU3RvcnkuPC9wPgogICAgICAgIDwvYW1wLXN0b3J5LWdyaWQtbGF5ZXI+CiAgICAgICAgPGFtcC1zdG9yeS1wYWdlLW91dGxpbmsgbGF5b3V0PSJub2Rpc3BsYXkiIGN0YS10ZXh0PSJTb21lIHRleHQiPgogICAgICAgICAgPGEgaHJlZj0iaHR0cHM6Ly93d3cuZ29vZ2xlLmNvbSI+PC9hPgoJCTwvYW1wLXN0b3J5LXBhZ2Utb3V0bGluaz4KICAgICAgPC9hbXAtc3RvcnktcGFnZT4KCiAgICA8L2FtcC1zdG9yeT4KICA8L2JvZHk+CjwvaHRtbD4=)

**Comment by mszylkowski** [comment]
The textContent of your `<a>` tag now takes precedence, like so:
```html
<amp-story-page-outlink>
    <a href="link.com">Text here!</a>
</amp-story-page-outlink>
```

The docs will be updated soon: https://github.com/ampproject/amphtml/pull/36426
