### ISSUE TITLE
Bundle size calculation changes too often

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#37014]
**summary**

I'm currently investigating root cause, but I believe our bundle size calculation is incorrect.
There are PRs displaying bundle size changes in our GH UI that display 0 diff when building locally. A good example is https://github.com/ampproject/amphtml/pull/37007.

When testing locally via the below command I see no diff on that commit and the one before it for any vendor builds.
```
npx amp dist --noconfig --version_override 0000000000000 && npx amp bundle-size --on_local_build
```

**Comment by samouri** [comment]
Latest thing I was planning on testing was to get the output from /tmp/dist.3p/current-min/vendor/sulvo.js on a CircleCI "Bundle Size" node to see if the RTV is being properly normalized in the output and/or what the config settings at the top are.

TIL I can't ssh into CircleCI nodes from corp :(

**Comment by jridgewell** [comment]
Current assumption is that our parallel builds are entering the minify step in different orders, and that's causing the property name mangling to change (since the mangled names are synchronized to all later minifications).
