### ISSUE TITLE
Bug: cdn.ampproject.org double-encoding characters

### ISSUE THREAD

**Issue by AaronMLB** [ampproject/amphtml#37011]
### Description

The AMP CDN cache at cdn.ampproject.org is encoding already-encoded characters.

For output of the hash character # I have already encoded it as `&num;` in my page's source code and this is rendered on my site correctly.

However, the same page from AMP's CDN double-encodes it to `&amp;num;`, resulting in `&num;` being visible to the user.

### Reproduction Steps

Real page: https://www.comedy.co.uk/quiz/

Cached page: https://www-comedy-co-uk.cdn.ampproject.org/v/s/www.comedy.co.uk/quiz/?amp_js_v=a6&_gsa=1&usqp=mq331AQKKAFQArABIIACAw%3D%3D

**Comment by Gregable** [comment]
@amaltas can you take a look at this? It sounds like it's probably an issue with the HTML parser not correctly recognizing the &num; as a valid entity.

**Comment by Gregable** [comment]
@AaronMLB - Thanks for the report. As a workaround in the meantime, you can use the `#` character directly.

**Comment by AaronMLB** [comment]
Thanks @Gregable.

As it's probably related somewhere deep in the AMP base logic: I discovered a similar issue with the PHP version of the AMP Optimizer. See https://github.com/ampproject/amp-toolbox-php/issues/409

**Comment by jridgewell** [comment]
It's a lot larger than just `&num;`, it seems it's missing a lot of the HTML entity names: https://spice--mousy--cannon-glitch-me.cdn.ampproject.org/c/s/spice-mousy-cannon.glitch.me (compare to https://spice-mousy-cannon.glitch.me/)

**Comment by amaltas** [comment]
We switched to new [htmlparser](https://github.com/ampproject/amphtml/blob/main/validator/cpp/htmlparser/strings.cc#L412) which unescapes entity names during parsing so <div>&amp;num;</div> becomes <div>&num;</div>.

I am making a change to fix this issue. It may take a few weeks for this change to go in production and fix this. Sorry for the inconvenience. I will update the issue once the change is checked in.

**Comment by amaltas** [comment]
This should be fixed in production. Please reopen if you still see double encoding in the cdn.
