### ISSUE TITLE
AMP 301/302 redirect causes the wrong site name to show up in the AMP viewer

### ISSUE THREAD

**Issue by omerr132** [ampproject/amphtml#37061]
### Description

We have a site where the amphtml tag refers to a page that does a 302 redirect to the actual location of the AMP page, which is on a different domain:

[Source HTML URL](https://www.idanbenor.co.il/link-building/prevent-negative-seo/).
[AMP URL](https://www.idanbenor.co.il/link-building/prevent-negative-seo/?ampify) which does a 302 redirect to the [AMP server](https://convert.ampify.io/5dd67785aa4ec80024cf8a7f?u=https://www.idanbenor.co.il/link-building/prevent-negative-seo/).

[A link to how it shows up in the search results (mobile)
](https://www.google.com/search?q=%D7%A2%D7%99%D7%93%D7%9F+%D7%91%D7%9F+%D7%90%D7%95%D7%A8+3+%D7%93%D7%A8%D7%9B%D7%99%D7%9D+%D7%9C%D7%96%D7%94%D7%95%D7%AA+%D7%A7%D7%99%D7%93%D7%95%D7%9D+%D7%90%D7%AA%D7%A8%D7%99%D7%9D+%D7%A9%D7%9C%D7%99%D7%9C%D7%99+%D7%95%D7%9C%D7%94%D7%9E%D7%A0%D7%A2+%D7%9E%D7%A2%D7%A0%D7%99%D7%A9%D7%94+%D7%99%D7%93%D7%A0%D7%99%D7%AA&oq=%D7%A2%D7%99%D7%93%D7%9F&aqs=chrome.0.69i59j69i57j69i59j35i39j0i512j69i61l3.711j0j4&sourceid=chrome&ie=UTF-8)

Now, in the search results, the AMP viewer shows the different-domain.com name at the top of the page, as the name of the page. The site.com still shows up correctly in the search results itself. Only when opening it, does the different-domain.com shows up as the name of the AMP page. 

The issue appears to happen mostly in the Android Google Search app, but not in Android Chrome, or iOs. Here's how it looks: https://prnt.sc/20xud7d

We've raised that issue on the [Google Search Forums](https://support.google.com/webmasters/thread/137539452/amp-301-redirect-causes-the-wrong-site-name-to-show-up-in-the-amp-viewer?hl=en), where we got an answer to try 302 and not 301. Both had the same issue. 

Why is that, and how can we fix it so that the amp server domain won't be visible?

I'll point out that we have to host the amp page on a different domain, and we can't use reverse proxy or http request to get the page content from the other domain.

### Reproduction Steps

**Using Android Chrome**: click the first result: [A link to how it shows up in the search results (mobile)
](https://www.google.com/search?q=%D7%A2%D7%99%D7%93%D7%9F+%D7%91%D7%9F+%D7%90%D7%95%D7%A8+3+%D7%93%D7%A8%D7%9B%D7%99%D7%9D+%D7%9C%D7%96%D7%94%D7%95%D7%AA+%D7%A7%D7%99%D7%93%D7%95%D7%9D+%D7%90%D7%AA%D7%A8%D7%99%D7%9D+%D7%A9%D7%9C%D7%99%D7%9C%D7%99+%D7%95%D7%9C%D7%94%D7%9E%D7%A0%D7%A2+%D7%9E%D7%A2%D7%A0%D7%99%D7%A9%D7%94+%D7%99%D7%93%D7%A0%D7%99%D7%AA&oq=%D7%A)

The site title, as seen in the AMP viewer is not Idanbenor, rather it's the server's - convert.ampify.io

**Android mobile app**: Search for "idanbenor penguin-update-will-be-in-2016" and click the first result. 
The 'from' subtitle will show the server name and not the site name. 

### Browser(s) Affected

Chrome

### Device(s) Affected

Android

**Comment by omerr132** [comment]
Anybody has any idea?

**Comment by Gregable** [comment]
This is by design. The AMP Cache will always display the URL at the end of the redirect chain, if there was any. This is the same behavior as if the user's browser had followed the redirect chain and also would display the final URL. There are security and phishing scenarios that come in to play if the cache were to show the intermediate URL.

**Comment by omerr132** [comment]
Hi @Gregable, 

1. This is happening only on the Android Search app, sometimes on Android Chrome, and never on iOs (See the [image](https://prnt.sc/20xud7d)). What's behind this inconsistency?
2. Based on its documentation, to identify the canonical URL Google uses signals. A 302 is an indication that the source is the canonical. Of course, the \<link rel="canonical"\> is also an indicator for the Canonical. And indeed, in the search results these pages are listed under the correct domain, across all devices and apps. However, the AMP cache is behaving differently. What guidelines should we follow in regards to the canonicalization of a page? Are Google search's different from its AMP cache?

(of course it would be easy if we could just host the AMP pages under our customers' domains, or do a reverse proxy. Unfortunately that's not an option)

**Comment by Gregable** [comment]
Your links don't work for me, can you attach the screenshots to the issue instead? I don't have a safari device to test with, but the AMP Cache always shows the final URL after redirects, this isn't a browser-specific behavior. If there is a difference in behavior, it is a bug in the iOS behavior that is failing to show the final URL.

Canonical is used for determining what search links to and how search deduplicates results. It has no effect on browser behavior and by design the cache emulates the browser behavior of following redirects and displaying the URL of the final page.

**Comment by omerr132** [comment]
Hi Greg, I'm not sure why the links don't work. Here they are in text:

**Source HTML page**: https://www.idanbenor.co.il/link-building/prevent-negative-seo/
**AMP URL**: https://www.idanbenor.co.il/link-building/prevent-negative-seo/?ampify
**Final URL (after 302)**: https://convert.ampify.io/5dd67785aa4ec80024cf8a7f?u=https://www.idanbenor.co.il/link-building/prevent-negative-seo/

**Mobile search results:** https://www.google.com/search?q=%D7%A2%D7%99%D7%93%D7%9F+%D7%91%D7%9F+%D7%90%D7%95%D7%A8+3+%D7%93%D7%A8%D7%9B%D7%99%D7%9D+%D7%9C%D7%96%D7%94%D7%95%D7%AA+%D7%A7%D7%99%D7%93%D7%95%D7%9D+%D7%90%D7%AA%D7%A8%D7%99%D7%9D+%D7%A9%D7%9C%D7%99%D7%9C%D7%99+%D7%95%D7%9C%D7%94%D7%9E%D7%A0%D7%A2+%D7%9E%D7%A2%D7%A0%D7%99%D7%A9%D7%94+%D7%99%D7%93%D7%A0%D7%99%D7%AA&oq=%D7%A2%D7%99%D7%93%D7%9F&aqs=chrome.0.69i59j69i57j69i59j35i39j0i512j69i61l3.711j0j4&sourceid=chrome&ie=UTF-8

**Google Search Forum thread on the same issue**: https://support.google.com/webmasters/thread/137539452/amp-301-redirect-causes-the-wrong-site-name-to-show-up-in-the-amp-viewer?hl=en

Here's how the page looks in the different devices and apps:
![OUZfHK7YRFu9oeWtucCPRw](https://user-images.githubusercontent.com/25805938/144312248-b43ffe7d-8e75-4cb2-a1ff-340c55ccf23e.png)
