### ISSUE TITLE
Development Server very slow on first load

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#3707]
It takes a *full 17 seconds to serve amp.js* file among other files. On subsequent reloads the load time is much better. Weirdly, I noticed that responses with HTTP statues 304 - Not Modified has the slowest response times! 

This might be related to the recent change of web server we're using in development.

![image](https://cloud.githubusercontent.com/assets/2647/16253221/90a6ac4a-37e9-11e6-80df-04c31f84ec52.png)

![image](https://cloud.githubusercontent.com/assets/2647/16253260/e9ead57e-37e9-11e6-8c0d-5d387109e5a9.png)

**Comment by lannka** [comment]
MK and I looked at it offline. It is actually not the server slow, but actually the build.
In pasted screenshot, the line "All current JS updates done." is after many GET request, meaning the first page load is before the build being completed.

We could file another bug to trace the slow build.
