### ISSUE TITLE
Consider Renaming style.js/styles.js files to reflect what they're about

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#3708]
I Always make the mistake of importing `setStyles` from `styles.js` and end up finding that it's in `style.js` This is very confusing as the `s` doesn't really communicate the idea behind each file.

I suggest `document-styles.js` or `styles-installer.js` instead `styles.js` and `element-style.js` or `style-helpers.js` instead of `style.js`.

Any other suggestions?

**Comment by dvoytenko** [comment]
I think style.js and style-installer.js would be good, or asking these
lines.
