### ISSUE TITLE
Resource scans happen in test iframes after they are removed

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#3709]
Because they get timed on the parent window.

They might just need to check whether the respective document still has a `defaultView`.

CC @muxin

**Comment by ericlindley-g** [comment]
@cramforce  — slotting this in the Fixit milestone, but please correct/update as needed

**Comment by cramforce** [comment]
Yeah, here is what happens:

- Resource manager is per window.
- but we have a single timer that we use across all windows.
- that timer in tests belongs to main iframe
- when test iframe gets removed, timers belonging to parent iframe still fire (because that wasn't removed)

Fixing might be as simple as giving resource manager its own timer. Likely the timer should just be a real per-window service.

CC @dvoytenko
