### ISSUE TITLE
Bento: React component error: Cannot read properties of undefined (reading '__b')

### ISSUE THREAD

**Issue by westonruter** [ampproject/amphtml#37111]
### Description

In https://github.com/swissspidy/gutenberg-bento/issues/36:

> I just tried doing a fresh `npm install` and `npm run start`. I'm seeing an error in the post editor:
> 
> ```
> Uncaught TypeError: Cannot read properties of undefined (reading '__b')
>     at Object../node_modules/@bentoproject/base-carousel/dist/component-react.module.js (component-react.module.js:1)
>     at __webpack_require__ (bootstrap:19)
>     at Object../src/carousel/edit.js (component-react.module.js:2)
>     at __webpack_require__ (bootstrap:19)
>     at make namespace object:7
>     at carousel.js?ver=8b97bc79604dbac2bf69eac81ef9c280:565
>     at carousel.js?ver=8b97bc79604dbac2bf69eac81ef9c280:566
> ```

### Reproduction Steps

Try installing the [gutenberg-bento](https://github.com/swissspidy/gutenberg-bento) WordPress plugin and try adding the carousel block to a post.

**Comment by westonruter** [comment]
I'm not getting this error anymore. But I am getting a different one:

```
TypeError: Cannot read properties of undefined (reading 'apply')
    at k (component-react.module.js:formatted:1155)
    at component-react.module.js:formatted:1155
    at Object.useMemo (react-dom.min.js?ver=17.0.1:220)
    at c.useMemo (react.min.js?ver=17.0.1:30)
    at M (component-react.module.js:formatted:1155)
    at component-react.module.js:formatted:1155
    at Le (react-dom.min.js?ver=17.0.1:100)
    at yh (react-dom.min.js?ver=17.0.1:110)
    at Pj (react-dom.min.js?ver=17.0.1:235)
    at di (react-dom.min.js?ver=17.0.1:168)
```

This is after @swissspidy updated `@bentoproject/base-carousel` to `^1.2112032204.0` in https://github.com/swissspidy/gutenberg-bento/commit/4d24b0af3ed802c224fd290713d47a7e017b8712.

**Comment by westonruter** [comment]
Is this live? I just tried with `1.2111242025.1` (published 11 hours ago) but I'm seeing the same error.

**Comment by jridgewell** [comment]
`1.2111242025.1` is a cherry pick of an older stable release. #37123 won't be picked up into stable until next week.
