### ISSUE TITLE
[amp story shopping] Currency i18n

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#37126]
### Description

The currency symbol and number formatting need to handle i18n.

<img width="209" alt="Screen Shot 2021-12-06 at 4 36 37 PM" src="https://user-images.githubusercontent.com/3860311/144926541-b0235ca4-189c-48c7-8387-88cdd81e0fd0.png">

Use [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) to enable language-sensitive number formatting.

Locale will need to be retrieved, [code example](https://github.com/ampproject/amphtml/blob/main/src/service/localization/index.js#L85).

A product-price-currency entry will need to be specified in the config to display the correct currency symbol:

```
product-price: 100,
product-price-currency: ‘USD’
```

Since the currency symbol's position is dynamic it will need to be the same size as the number.

cc @newmuis who may have more context on i18n.

### Alternatives Considered
product-price as a string that includes currency symbol and number formatting.
This makes validation and number formatting complex. 

### Additional Context
We do not want to support currency conversion - that would require a request to an API. 

_No response_

**Comment by newmuis** [comment]
Good catch!  I think we should likely separate them out semantically: the price (a Number, `100` in this example), and the currency (an enum, `USD` in this example).  We can then separately evaluate the currency to understand how to present it
