### ISSUE TITLE
Pages scroll horizontally in iOS Safari

### ISSUE THREAD

**Issue by ericfs** [ampproject/amphtml#3712]
Some pages have a small amount of horizontal scrolling. For example:
https://amp.businessinsider.com/obama-game-7-air-force-one-nba-finals-2016-6
It happens with some other publishers too.

This does not happen when the document is loaded in a web Viewer. In that case, it uses ViewportBindingNaturalIosEmbed_ and overflow-x:hidden is set on the body.

This is a problem for native AMP Viewer implementations that use WebViews since they will have the small horizontal scroll.

**Comment by jridgewell** [comment]
Re: https://github.com/ampproject/amphtml/issues/3318

**Comment by ericlindley-g** [comment]
@jridgewell   — adding this to the Backlog milestone; please correct/update as needed (not sure if this folded entirely into the "next" work in #3318)

**Comment by dvoytenko** [comment]
To be done only when `#webview=1`.
