### ISSUE TITLE
Missing components from extensions/README.md

### ISSUE THREAD

**Issue by jmadler** [ampproject/amphtml#3714]
amp-ad
amp-form
amp-live-list
amp-slides
amp-sticky-ad

**Comment by erwinmombay** [comment]
won't do amp-slides since its actually deprecated

**Comment by erwinmombay** [comment]
@zhouyx can you add amp-sticky-ad in https://github.com/ampproject/amphtml/blob/master/extensions/README.md 

think that is the only one left missing

**Comment by erwinmombay** [comment]
although in saying that we have newer extensions that probably arent on there again. will review
