### ISSUE TITLE
Facebook provider for amp-social-share does not default to rel=canonical URL

### ISSUE THREAD

**Issue by mikelax** [ampproject/amphtml#3716]
## Short description of your issue:

It appears the default Facebook provider is not reading the link `rel=canonical` value to use for the URL to share. According to the docs all default providers such as twitter, facebook, pinterest, etc should all use `rel=canonical` by default. 

## How do we reproduce the issue?

I noticed in the [test cases for amp-social-share](https://github.com/ampproject/amphtml/blob/master/extensions/amp-social-share/0.1/test/validator-amp-social-share.html) there is no test case covering facebook. 

1. Here is a [jsbin](http://jsbin.com/kanehagusi/edit?html,output) snippet showing the problem.

To work around this issue, we added the attribute `data-param-href` to `amp-social-share` to force it to use the correct URL. 

## What browsers are affected?

This was reproducible on Chrome.

## Which AMP version is affected?

We just added support for Facebook social share so this is the first I am seeing this error. 
Powered by AMP ⚡ HTML – Version 1466016447690

**Comment by mkhatib** [comment]
Hey @mikelax I believe this has been fixed in #3541 - The change should already be in Canary you can test it if you'd like by [opting into the Canary experiment](https://cdn.ampproject.org/experiments.html) and hard refreshing the demo page.

**Comment by mkhatib** [comment]
Please reopen if you're still seeing the issue.

**Comment by mikelax** [comment]
ahh, nice @mkhatib I saw that commit but must have missed the change in the config from url to href. 
As part of that change should [the documentation](https://github.com/ampproject/amphtml/blame/master/extensions/amp-social-share/amp-social-share.md#L98) be updated to use the correct attribute.

**Comment by mkhatib** [comment]
Yes. Forgot to update the docs, can you send a PR?
