### ISSUE TITLE
app_id not being included in Facebook amp-social-share component

### ISSUE THREAD

**Issue by poscar** [ampproject/amphtml#3719]
amp-social-share button does not work for Facebook. It is not picking up the `app_id` which is already specified in the document:

```
    <meta property="fb:app_id" content="12345678901234"></meta>
    <meta property="fb:pages" content="1234567890"></meta>
```

Clicking on the facebook share button results in the following dialog:
![screen shot 2016-06-22 at 3 04 13 pm](https://cloud.githubusercontent.com/assets/128726/16279816/b6d2eef0-388a-11e6-96ed-017c2aa748d7.png)
## How do we reproduce the issue?

jsbin: [here](http://jsbin.com/cuhogoxusa/)
## What browsers are affected?

All of them.
## Which AMP version is affected?

At least: `Powered by AMP ⚡ HTML – Version 1466016447690`
## Workaround

Add `data-param-app_id` parameter to the `<amp-social-share type="facebook" />` component.
## Remarks

Either documentation should be updated to mark `data-param-app_id` as required. Or the `<amp-social-share>` component should pick up the appId from the meta tags.

**Comment by mkhatib** [comment]
We haven't considered reading `fb:` meta tags as source of data before. Might be worth considering adding meta name as a config for the amp-social-share. The workaround that you mentioned is actually the correct intended usage of the `amp-social-share`.

The documentation should probably be updated to mention data-param-app_id as required for Facebook.

**Comment by poscar** [comment]
Thanks @mkhatib !

**Comment by poscar** [comment]
@mkhatib Actually looks like ```'data-param-href'``` is required, otherwise the dialog automatically closes itself. Maybe it's is not properly picking up canonical rel <link>?

**Comment by ericlindley-g** [comment]
I'm seeing an issue I think is related to this in prod — @dvoytenko @cramforce , is there a good person to look at this in the short term?

<img width="642" alt="screen shot 2016-07-20 at 2 34 39 pm" src="https://cloud.githubusercontent.com/assets/16807766/17003925/230911be-4e87-11e6-8b0f-ece372b5cf52.png">

**Comment by cramforce** [comment]
Maybe @paul-matthews could.

**Comment by mkhatib** [comment]
This is not a bug, it works as expected. However, putting the feature label on this. This would work correctly if user included `data-param-app_id` attribute in the `amp-social-share` tag.

Unfortunately this would complicate the config again, we specifically dropped a lot of the complex config logic we had for the `amp-social-share` and sticked with a simpler approach that relies on `data-param-` and Var Substitutions.

**Comment by ericlindley-g** [comment]
@mkhatib got it—that makes sense. We could change the documentation to spell this out more clearly: right now it says `app_id` is a required parameter for `type="facebook"`, but we may want to really make it clear that `data-param-app_id` is a required attribute. What do you think?

We may also want to issue validation warnings linking back to the docs for types that don't have their required attributes (and think about eventually issuing validation errors)

**Comment by ericlindley-g** [comment]
Passing to @bpaduch for the docs update (let me know if you want to chat for more context)

**Comment by 88kbbq** [comment]
You should add information on where to obtain the data-param-app_id and also remind users this social share links to your app, not your fan page. That's not the way I'd imagine this to work. Why and app_id? Why not a page id?

**Comment by bpaduch** [comment]
Added further info on facebook app_id to amp-social-share doc.  Regarding why app_id vs page id - @mkhatib - can you discuss?

**Comment by ericlindley-g** [comment]
Thanks @bpaduch!
/cc @aghassemi in lieu of @mkhatib
