### ISSUE TITLE
Infra FR: TypeScript Support

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#37200]
**summary**
We've recently begun using TypeScript for type checking various directories, like `src/compiler`, `src/core` and `extensions/amp-carousel/0.1`.

Our build-system (esbuild) TS compatible, but there are still at least two things that will break if we try to start writing .d.ts files:

- Prettier: I believe our globs are not searching for `*.tsx?`.
- ESLint: by default this is not TS Compatible. We should migrate to `typescript-eslint`.
- Anything else I haven't thought of can be discovered by friction in creating a `.ts` or `.tsx` file.

**alternatives Considered**
Continue using JSDoc types forever.

cc @rcebulko

**Comment by rsimha** [comment]
Tagging @ampproject/wg-infra for comment.

**Comment by samouri** [comment]
I'm taking this on

**Comment by samouri** [comment]
This is complete. Our build system fully supports TS now, and I've even merged some `.ts` code (https://github.com/ampproject/amphtml/pull/37370)
