### ISSUE TITLE
Validations returns status `PASS`, while expected to fail with `MANDATORY_TAG_ANCESTOR_WITH_HINT`

### ISSUE THREAD

**Issue by g-yonchev** [ampproject/amphtml#37232]
### Description

Hello,
`validator.validateString(html)` does not fail with `MANDATORY_TAG_ANCESTOR_WITH_HINT` error. Expected to be failing.

### Reproduction Steps

Snippet of the code: (npm module version `^1.0.34`)
```
const amphtmlValidator = require('amphtml-validator');
const html = '\n' +
'  <!doctype html>\n' +
'  <html ⚡>\n' +
'    <head>\n' +
'      <meta charset="utf-8">\n' +
'      <link rel="canonical" href="./has-amp-link" />\n' +
'      <meta name="viewport" content="width=device-width,minimum-scale=1">\n' +
'      <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>\n' +
'      <script async src="https://cdn.ampproject.org/v0.js"></script>\n' +
'    </head>\n' +
'    <body>\n' +
'      Hello, AMP world.\n' +
'      <img src="./some-image.png"/>\n' +
'    </body>\n' +
'  </html>\n';

(async function run () {
  const validator = await amphtmlValidator.getInstance();
  const result = validator.validateString(html);
})();
```
When logging the `result` it shows `{ status: 'PASS', errors: [] }`, but I would expect to fail with `MANDATORY_TAG_ANCESTOR_WITH_HINT` error. According to the docs if i read them correctly: https://amp.dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors/#mandatory-tag-ancestor-with-hint
this error happens when a `img` tag is not within `noscript`. In my code example indeed the `img` is not inside `noscript` and I would expect it to fail.

**Comment by honeybadgerdontcare** [comment]
Recently the native `img` tag was added so the documentation needs to be updated. See #30956.

The [amp.dev repo](https://github.com/ampproject/amp.dev/issues/new/choose) may be the best place to file an issue for it.

**Comment by g-yonchev** [comment]
@honeybadgerdontcare thanks for the explanation
