### ISSUE TITLE
Request for mmmicedcoffee to become a contributor

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#37230]
> A person may become a Collaborator after 2 merged PRs that are non-trivial (not only fixing typos, not only config changes) and a +1 from 1 current Reviewer. To request becoming a Collaborator file an issue in the repository in which you are requesting to be a Collaborator and cc a Reviewer in that repository.

> https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#roles

Relevant PRs: https://github.com/ampproject/amphtml/pulls?q=is%3Apr+author%3Ammmicedcoffee

/cc @mmmicedcoffee

**Comment by mrjoro** [comment]
I've added @mmmicedcoffee to the Collaborators team!
