### ISSUE TITLE
[i-amphtml-story-page-attachment-remote-title] CSS issue while clicking on page-outlink button

### ISSUE THREAD

**Issue by kamblenavnath** [ampproject/amphtml#37250]
### Description

While clicking on CTA button (i.e. amp-story-page-outlink) and before getting redirected to a other external link, we are facing this 
![CTA_Button_ClickAction_Issue](https://user-images.githubusercontent.com/24918880/146893481-0cb2fc45-70b4-40e1-abae-76df54750054.PNG)

It is being generated because of a CSS properties applied to a class: 'i-amphtml-story-page-attachment-remote-title'.

Please have a look into it and let us know once it is resolved.
 

### Reproduction Steps

1. Click on <amp-story-page-outlink> button
2. See a UI before redirecting to other webpage

**Comment by kamblenavnath** [comment]
@sebastianbenz Any updates?!

**Comment by processprocess** [comment]
Thank you for following up!
I'm unable to repro on mac Chrome, Safari and Firefox.

Please provide **Browser(s) Affected** and **Device(s) Affected** to help us repro.

**Comment by kamblenavnath** [comment]
@processprocess I am getting this issue on Google Chrome, Firefox. You might see this on slow internet connection.

**Comment by kamblenavnath** [comment]
@processprocess For reference [story example](https://ikea.visualstories.com/calling-all-dino-lovers)

**Comment by kamblenavnath** [comment]
@processprocess Is the issue resolved? I'm still facing that issue.

**Comment by processprocess** [comment]
> @processprocess Is the issue resolved? I'm still facing that issue.

It has been merged. It will take ~2 weeks to be in into stable following the [release schedule](https://amp.dev/documentation/guides-and-tutorials/learn/spec/release-schedule/#long-term-stable-lts).
