### ISSUE TITLE
Invalid URL protocol 'threema:' for attribute 'href' in tag 'a'.

### ISSUE THREAD

**Issue by startef** [ampproject/amphtml#3727]
The validator throws the following error when a share link for Threema, an alternativ to WhatsApp, is used on a page:

> Invalid URL protocol 'threema:' for attribute 'href' in tag 'a'.

Since "whatsapp:" is allowed, "threema:" should be considered valid as well. After all, it is basically the same thing.

The issue can be reproduced by simply testing the following two links in the validator:

`<a href="whatsapp://send?text=https%3A%2F%2Fvalidator.ampproject.org">AMP Validator</a>`

`<a href="threema://compose?text=https%3A%2F%2Fvalidator.ampproject.org">AMP Validator</a>`

The whatsapp: link is fine, the threema: link is throwing the mentioned protocol error.

Cheers,
JP

**Comment by Gregable** [comment]
@honeybadgerdontcare, can you add this protocol to our url lists where appropriate?

**Comment by Gregable** [comment]
Resolved. This will be deployed to cdn.ampproject.org next week.

**Comment by Gregable** [comment]
This change is now live on cdn.ampproject.org

**Comment by startef** [comment]
Confirmed. Thank you very much!
