### ISSUE TITLE
🌸 Cherry-pick request for #37314 into #37293

### ISSUE THREAD

**Issue by mszylkowski** [ampproject/amphtml#37315]
### Issue (P0 Bug)

#37314

### Pull Request(s)

#37314

### Release Tracker(s)

#37293

### Channels

Beta / Experimental

### Formats

Stories

### Justification

When the story only has background audio specified in the amp-story (example) the audio icon doesn't show due to the amp-story not reporting to the store service that the story element has background audio.

This breaks existing AMP web pages in a significant way.

### Verification Steps

On any story add in the `amp-story` tag the attribute `background-audio="audio.mp3"`. The audio icon should be visible again.

### Summary

Cleanup bug due to removing more code than what needed.

### Impact

We don't have metrics on how many stories have background audio, but all stories with background-audio are impacted.

### Action Items

Added unit test on `test-amp-story` to check the background audio is updated properly.

### Notifications

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by gmajoulet** [comment]
I could be wrong (please correct me) but I don't think any major Story creation tool supports `amp-story[background-audio]`. By definition, a background audio that's global to the story is not breaking the UX or critical path of the user journey.

Unless specific publishers complained about it, I think a cherry pick to experimental would be enough.

**Comment by mszylkowski** [comment]
Yes, plan is to CP only to beta/experimental, I think all the extra labels got added automatically and I forgot to remove them.

**Comment by kristoferbaxter** [comment]
Approved. Thanks for adding tests!
