### ISSUE TITLE
[Story embedded] Amp Twitter on Firefox doesn't show tooltip 

### ISSUE THREAD

**Issue by mszylkowski** [ampproject/amphtml#37339]
### Description

On Firefox the click catcher (`:after`) doesn't catch the clicks, so clicking on the Tweet will not show the tooltip and open the Tweet directly.

### Reproduction Steps

Enter https://www.gstatic.com/amphtml/stamp/qa/tooltip.html on Firefox

### Browser(s) Affected

Firefox

### OS(s) Affected

Desktop

### Device(s) Affected

Laptops

### AMP Version Affected

latest

**Comment by ychsieh** [comment]
working fine now.
