### ISSUE TITLE
I2I: Permutive's new AMP Analytics Vendor Configuration

### ISSUE THREAD

**Issue by zshnr** [ampproject/amphtml#37346]
### Summary

Permutive is already an AMP Analytics vendor. Our initial I2I was #19497 and the work was done in #19506. 
Our new AMP Analytics configuration is a breaking change from our old one and we would like to phase our customers over to the new one gradually.

Thus, we propose creating a new AMP Analytics configuration for Permutive with the name `permutive-amp-script` (open to suggestion for better names though).

This was initially discussed between myself and @alanorozco on the AMP slack [here](https://amphtml.slack.com/archives/C9HPA6HGB/p1628160681018200)

### Motivation

Initially, our SDK would run in an `amp-iframe` and would be torn down after 5 seconds on the page. Which is why, we had to rely on `amp-analytics` sending events to our API to make our solution work.

The new sandboxed mode in `amp-script` has given us the change to build a better SDK for our customers that runs like a first class citizen in an AMP environment. It runs in an `amp-script` so its on the page for the entire lifecycle of the page. And because our SDK is on the page, `amp-analytics` can now send events to the script itself, allowing our SDK to do its work behind the scenes before passing it on to our API.

We want to roll out this new SDK gradually to our customers, and so we need to keep both our old and new `amp-analytics` configurations live until they are all migrated to the new version.

### Alternative Solutions

We are not sure we have an alternative as there a few changes (for e.g. in the structure of the extraUrlParams) that are incompatible between versions.

They also rely on different transport mechanisms. The existing relies on `image`, the new relies on `amp-script`

### Notifications

/cc @ampproject/wg-components
/cc @samouri

**Comment by zshnr** [comment]
New vendor config merged in.

Thanks again @samouri @alanorozco !

**Comment by samouri** [comment]
Happy to help @zshnr ⚡
