### ISSUE TITLE
Story player replay button does not revert to next button

### ISSUE THREAD

**Issue by LuckynaSan** [ampproject/amphtml#37350]
### Description

A Web Stories user reported that after completing a story, the replay button restarts the story but does not change back to the forward/next button. This issue does not occur when the user is a logged-in user, but you will notice the behavior in an incognito window or when in a logged-out state.

Note the functionality is there even though the button does not display correctly.

<img width="916" alt="Screen Shot 2022-01-12 at 9 03 50 AM" src="https://user-images.githubusercontent.com/66372350/149157740-fb18fa8f-2682-4804-9f44-4e5ae0548e29.png">

### Reproduction Steps

View story to completion in a logged-out state, or incognito window.
Click on the replay button
Note the button remains that way after landing on the first page onward

original report: https://wordpress.org/support/topic/the-replay-icon-at-the-end-of-the-story-doesnt-disappear/
example story: https://testsite.cmsdevrel.com/web-stories/replay-story-test/

**Comment by mszylkowski** [comment]
I noticed it for the last release and @processprocess has fixed it on https://github.com/ampproject/amphtml/pull/37316. Closing as it's merged already

**Comment by LuckynaSan** [comment]
Thank you!!
