### ISSUE TITLE
Article from Top Stories not loading in AMP while the AMP URL exists

### ISSUE THREAD

**Issue by adops-tcs** [ampproject/amphtml#37363]
### Description

[Our article ](https://www.sportscasting.com/larry-bird-made-24-million-during-nba-career-claimed-he-was-perfectly-content-having-some-coke-some-beer-something-to-eat-nice-place-to-live/) is featured in the top stories.  We have an [AMP version ](https://www.google.com/amp/s/www.sportscasting.com/larry-bird-made-24-million-during-nba-career-claimed-he-was-perfectly-content-having-some-coke-some-beer-something-to-eat-nice-place-to-live/%3famp) of the article but Top Stories is not using that.

The same article as standalone result below 'Top Stories'  in SERP loads in AMP format.

We believe that this behavior is not limited to one article.   We noticed that our non-AMP URLs are getting traffic from Google Search and Google Discover while the AMP URLs for the same articles don't.   We are able to see this in Google Analytics as well as reproduce in Seach. 

### Reproduction Steps

Search for 'larry bird' on a mobile device or in Chrome dev tools emulating a mobile device.

SERP: https://www.google.com/search?q=larry+bird&oq=larry+bird&aqs=chrome..69i57j46i433i512j0i433i512j0i512j0i131i433i512j0i433i512j69i60l2.2031j0j7&sourceid=chrome&ie=UTF-8

screenshot attached showing different URLs used for the same article in the different sections of SERP.

![Screen Shot 2022-01-12 at 12 28 24 PM](https://user-images.githubusercontent.com/50155367/149212890-4b14f700-71dc-4fdc-8c59-a1d19b019eee.png)

**Comment by ychsieh** [comment]
Not reproducible.
