### ISSUE TITLE
Not a issue question - How we can restrict the AMP div based on custom cookies

### ISSUE THREAD

**Issue by Dinesh101041** [ampproject/amphtml#37377]
i need to render a one div based on custom cookie with condition

if the cookie value meets the condition i need to hide the div

```
<div class="sample-div" >
  <amp-sample-div class="sample-div" width="16" height="13"></amp-sample-div>
</div>
```

can any one help me how this be achieved  

P.S : Did not find any discussion forums for AMP html so i added a question  here

**Comment by jshamble** [comment]
We do have a slack channel where you are free to ask questions, feel free to join and re-post this question there:

https://amphtml.slack.com/
