### ISSUE TITLE
Rename bento-base-carousel --> bento-carousel

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#37380]
### Description

AMP has both an `amp-carousel` and an `amp-base-carousel` which supports extra customization.

Bento exclusively has a `bento-base-carousel`, and afaik there are no plans to make a separate constrained `bento-carousel`.  We should simplify the name to `bento-carousel`, b/c the current one implies a regular carousel....which doesn't exist.

### Alternatives Considered

Status quo

cc @ampproject/wg-bento

**Comment by erwinmombay** [comment]
closing as stale
