### ISSUE TITLE
Page experience issue

### ISSUE THREAD

**Issue by wamibola44** [ampproject/amphtml#37390]
How do we resolve this amp issue with cache[Amp](https://www.kemifilani.ng/hot-news/bolaji-amusan-aka-mr-latins-wife-marks/amp)  amp page[](https://www.kemifilani.ng/music)  on 
![Screenshot_20220114-191730](https://user-images.githubusercontent.com/91660068/149565556-88141801-ba9d-4126-8d6b-818a43b961f1.png)

https://amp.dev/page-experience/?url=https%3A%2F%2Fwww.kemifilani.ng%2Fhot-news%2Fbolaji-amusan-aka-mr-latins-wife-marks%2Famp&authuser=3

**Comment by twifkak** [comment]
Thanks for filing. For reference, this looks like a bug in the Page Experience Guide, but I'm not sure. I don't see any evidence that the cache URL is underperforming:

![image](https://user-images.githubusercontent.com/2893/150037213-12b60766-b44a-4774-b441-e4a7b7e85b7e.png)

![image](https://user-images.githubusercontent.com/2893/150037230-374dad20-0b3a-4aa5-a10a-6e60676fc127.png)

![image](https://user-images.githubusercontent.com/2893/150037360-7e1c3e8a-f024-478d-b75a-0248ed9b0a28.png)

I'm still looking for the current maintainer of the guide, but hopefully they see the `Type: Page experience` label in the meantime.

**Comment by twifkak** [comment]
@sebastianbenz Do you know who to assign PX Guide bugs?

**Comment by wamibola44** [comment]
>
