### ISSUE TITLE
mean of this benefit

### ISSUE THREAD

**Issue by bansalUdit** [ampproject/amphtml#3740]
I am brainstorming around AMP but not getting the mean of below Line

**In addition to this, Google SERPs have also started to display AMP content within visually dominating carousels that include large images**

**Comment by jridgewell** [comment]
![screen shot 2016-06-23 at 1 35 16 pm](https://cloud.githubusercontent.com/assets/112982/16313489/6ba3eeda-3947-11e6-88bb-c0edb3349cf7.png)

You can see the "visually dominating" AMP Carousel, vs a normal web result (the result under the carousel) when searching Google for [clinton].
