### ISSUE TITLE
Protected and Deleted tweets do not embed properly

### ISSUE THREAD

**Issue by poscar** [ampproject/amphtml#3743]
When using the `<amp-twitter>` component, if we embed a tweet that has been protected or deleted, nothing gets displayed. The component should be graceful and render a deleted/protected tweet message instead.
## How do we reproduce the issue?

http://jsbin.com/pefawakuru/
## What browsers are affected?

All browsers
## Which AMP version is affected?

At least: `Version 1466016447690`
## Remarks

I'm not sure if this should be handled by the placeholder that we can provide within the embed, or if the control itself should be more graceful for these cases.  Thoughts?

Thanks!

**Comment by jpettitt** [comment]
Adding to this if you do have a placeholder the element doesn't resize to hold it.

http://jsbin.com/wopayu/edit?html,output

**Comment by ericlindley-g** [comment]
@rudygalfi @dvoytenko  — adding this to the Backlog milestone; please correct/update as needed

**Comment by cramforce** [comment]
@indianburger could you take a look at this?

**Comment by indianburger** [comment]
Speaking as a Twitter engineer here but I'm guessing AMP's stance on this will be similar as it's a framework and will not make editorial decisions. 

Deleted tweets:
Twitter's javascript, which AMP pulls in here, will never render a deleted to respect the author's wish. However the common approach that publishers employ is to take on the editorial responsibility of whether to show the deleted tweet contents or not (I don't know what AMP's stance is in this situation). For a tweet that gets deleted later, publishers typically hit the [oembed endpoint](https://dev.twitter.com/rest/reference/get/statuses/oembed) and grab the blockquote with contents of the tweet which will serve as fallback content when the tweet is deleted. 

Protected tweets: They should never be embedded, so the link fallback that AMP does here seems appropriate to me.

**Comment by cramforce** [comment]
Can we signal to the parent that the tweet wasn't found? I think that is the main thing missing here. AMP would then switch to the fallback which is recommended like this:

```html
<amp-twitter width=486 height=657
    layout="responsive"
    data-tweetid="585110598171631616"
    data-cards="hidden">
    <blockquote placeholder fallback class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">The story how I became what some people would call a frontend engineer and an exploration into what that even means<a href="https://t.co/HrVz4cGMWG">https://t.co/HrVz4cGMWG</a></p>&mdash; Malte Ubl (@cramforce) <a href="https://twitter.com/cramforce/status/585110598171631616">April 6, 2015</a></blockquote>
</amp-twitter>
```

**Comment by cramforce** [comment]
I think the real bug here is:

We should keep showing the placeholder not until we render the iframe, but until we have an affirmative that tweet rendering succeeded.
@zhouyx is working on something similar for ads.

@indianburger Is there something like `twttr.events.bind('resize', …` we can listen to, to know when tweet render is complete and what the result was?

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
