### ISSUE TITLE
BISKO

### ISSUE THREAD

**Issue by blerinarrmoku** [ampproject/amphtml#37445]
### Summary

This feature is being implemented in order to be adding our analytics service's configuration to AMP HTML's runtime. cc @ampproject/wg-components 

### Design Document

To find out more on the implementation check our documentation http://docs.bisko.gjirafa.tech/

### Motivation

As a Developer, I have to implement AMP SDK, so that I can collect and track data across AMPs. 

### Alternative Solutions

Bisko is a data management platform by GjirafaTech that collects, manages, and provides insights on a vast amount of data from multiple sources. We are implementing this feature in order to enable data collection and track events though Accelerated Mobile Pages  

### Launch Tracker

[AMP Launch tracker Template (bit.ly_amp-launch-tracker).xlsx](https://github.com/ampproject/amphtml/files/7913693/AMP.Launch.tracker.Template.bit.ly_amp-launch-tracker.xlsx)

### Notifications

/cc @ampproject/wg-approvers

**Comment by erwinmombay** [comment]
Closing issue, but feel free to re-open if you still plan to implement
