### ISSUE TITLE
Allow input[type=image]

### ISSUE THREAD

**Issue by Gregable** [ampproject/amphtml#37443]
This issue tracks the `input[type=image]` part of #26364. 

Specifically, the request is for the validator to allow:

```
<input type=image src=http://site.example/foo.png>
```

This is currently invalid. This would not be allowed by amp email at this time, only AMP.

As a prerequisite, the AMP Cache needs to rewrite these URLs to cache-served URLs, tracked internally at Google as `b/148083520`. This prerequisite work is actually done, so the remaining work is just to add validator rules.

**Comment by twifkak** [comment]
@Gregable Are you planning on working on this or should we find another owner (e.g. westonruter)?

**Comment by Gregable** [comment]
If weston is volunteering, I have no concerns. However, assigning to me is fine. I haven't started yet.
