### ISSUE TITLE
Google Analytics pageview events are not being fired for web stories

### ISSUE THREAD

**Issue by coreymasanto** [ampproject/amphtml#37444]
### Description

The amp-story-auto-analytics [config](https://github.com/ampproject/amphtml/blob/292981b8069913b6ebcfe4388d7dc11efbe5904f/extensions/amp-story-auto-analytics/0.1/auto-analytics-configs.js#L21) is not currently set up to register `pageview` analytics events, resulting in Google Analytics not showing the story's page title in the Landing Pages section (i.e., *Behaviour > Site Content > Landing Pages*). A fix has been identified and is pending submission (see: #37438).

/cc @gmajoulet @mszylkowski 

### Reproduction Steps

1. Load Google Analytics for a web story whose analytics you can access, and go to Behaviour > Site Content > Landing Pages
2. The "Landing Page" column value should be "(not set)"

**Comment by gmajoulet** [comment]
#37438
