### ISSUE TITLE
🌸 Cherry-pick request for #37438 into #37405 (Approved)

### ISSUE THREAD

**Issue by coreymasanto** [ampproject/amphtml#37454]
### Issue (P0 Bug)

#37444

### Pull Request(s)

#37438

### Release Tracker(s)

#37405

### Channels

Beta / Experimental

### Formats

Stories

### Justification

We have partners that are severely affected by this bug, which causes them to be able to see event actions such as `story_pages_viewed` but with no associated landing page.

### Verification Steps

1. Load Google Analytics for a web story whose analytics you can access, and go to Behaviour > Site Content > Landing Pages
2. The "Landing Page" column value should show story's page title instead of "(not set)"

### Notifications

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers @mszylkowski

**Comment by newmuis** [comment]
Definitely approve cherrypicking this into beta.

**Comment by kristoferbaxter** [comment]
+1 to approval here.

**Comment by gma** [comment]
@coreymasanto I was cc'd in the original message, but not sure why. Any chance you could remove me? It's showing up in my to-do list. Thanks!
