### ISSUE TITLE
Amp Optimiser for Amp

### ISSUE THREAD

**Issue by IMMUKESHPATEL** [ampproject/amphtml#37461]
### Description

I m using Amp, but i can’t minify Amp pages for speed , i Don’t Know how to use Amp optimizer, is Amp plugin or Amp Optimiser is Same ? I m using Amp plugin, please reply , i need to optimise my amp pages, for page speed

Immmukeshpatel (emka.news)

### Alternatives Considered

How can I Use Amp Optimiser For Amp Pages , No Option In Amp Plugin, i m using Amp plugin.

### Additional Context

I m using Amp, but i can’t minify Amp pages for speed , i Don’t Know how to use Amp optimizer, is Amp plugin or Amp Optimiser is Same ? I m using Amp plugin, please reply , i need to optimise my amp pages, for page speed

How can I Use Amp Optimiser For Amp Pages , No Option In Amp Plugin, i m using Amp plugin.

Immmukeshpatel

**Comment by dethstrobe** [comment]
Hello, this repo is not the best spot to get tech support.

However, if you are using, an Amp plugin, like the one for [wordpress](https://wordpress.org/plugins/amp/). it should already be using Amp Optimizer, as described in the [documentation](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/amp-optimizer-guide/#cms-&-site-generators).

If you have other question, I might recommend using [stackoverflow's amp-html tag](https://stackoverflow.com/questions/tagged/amp-html) instead, where you can get help from the amp community a little easier.
