### ISSUE TITLE
Smart Adserver adcalls are not triggered

### ISSUE THREAD

**Issue by mlapeyre3** [ampproject/amphtml#37484]
### Description

With the release on the [<amp-ad> Smart Adserver extension](https://github.com/ampproject/amphtml/pull/36991) in version [2201071715001](https://github.com/ampproject/amphtml/releases/tag/2201071715001) (currently in _Stable_ release), no ad call is sent to the Smart Adserver backend anymore.

This critical issue impacts all our customers as **the monetization of their AMP inventory is down to 0.** 

The issue is fixed by [Get page domain #37483](https://github.com/ampproject/amphtml/pull/37483)

### Reproduction Steps

Here is a local sample page with replicates the issues due to the Cross-Domain-Origin error.
![Screenshot 2022-01-26 at 16 11 55](https://user-images.githubusercontent.com/19735493/151190463-7fe97679-02dd-4705-9c72-9b388005e44a.png)

### Relevant Logs

```shell
The error is
[amp-a4a] Error: Blocked a frame with origin "http://172.21.18.103:8080" from accessing a cross-origin frame at amp-ad-network-smartadserver-impl-0.1.js:1:185883
```

### Browser(s) Affected

Chrome, Firefox, Safari, Edge, UC Browser

### OS(s) Affected

All

### Device(s) Affected

All

### AMP Version Affected

2201071715001

**Comment by powerivq** [comment]
Closing as fixed. The cherry pick progress may be tracked on the cherry pick issue.
