### ISSUE TITLE
🌸 Cherry-pick request for #37484 into #37411

### ISSUE THREAD

**Issue by mlapeyre3** [ampproject/amphtml#37485]
### Issue (P0 Bug)

[37484](https://github.com/ampproject/amphtml/issues/37484)

### Pull Request(s)

[37483](https://github.com/ampproject/amphtml/pull/37483)

### Release Tracker(s)

[37411](https://github.com/ampproject/amphtml/issues/37411)

### Channels

Stable, ~LTS~

### Formats

Ads

### Justification

As described in the issue [37484](https://github.com/ampproject/amphtml/issues/37484), the regression of the <amp-ad> extension from Smart Adserver prevents any ad call to be sent by the AMP inventory of Smart's customers.
**The monetization of their AMP inventory is down to 0.**

The fix has been pushed in [37483](https://github.com/ampproject/amphtml/pull/37483) where you can see the change is related to how the <amp-ad> tag gets access to the domain of the page.

The change has flown into _Stable_ and is about to reach _LTS_ version. Hence, we kindly ask this cherry-pick for an urgent fix of the _Stable_ and _LTS_ versions (so that publishers who rollbacked on _LTS_ version benefit from the fix as well).

❓ In order to give some visibility to our customers, would you be able to tell us if the request can be accepted or not ASAP? Thank you very much. Please find below additional details.

### Verification Steps

In the file below we reproduced the situation where an AMP page "cached_page.html" is executed in a Google Cache frame (index.html). If you browse index.html on localhost:8080 domain, you will get the error with the Stable version
`Error: Blocked a frame with origin "http://127.0.0.1:8080" from accessing a cross-origin frame at amp-ad-network-smartadserver-impl-0.1.js:1:185883`

[AMP_cache.zip](https://github.com/ampproject/amphtml/files/7942944/AMP_cache.zip)

### Summary

**Bug:** no ad call are triggered from the <amp-ad> extension of Smart Adserver
**Cause:** the code tries to access `this.win.top.location.hostname` to add the page domain in the ad request.
**Solution:** the code now uses `Services.documentInfoForDoc(this.element).canonicalUrl`.

**Todo:** As the issue did not appear during our test phase, but only when the AMP page is executed in Google Cache for AMP, it might be interesting to know how we could reproduce this kind of integration on our local test page (or in a kind of Google Cache sandbox).

### Impact

All users from Smart Adserver customers are affected, for all OS and all devices when they browse an AMP page through Google Cache domain.
No ad call is sent, hence there is no advertising monetization for the publisher.

### Action Items

I think the main step we missed is the testing with a replica of the Google Cache for AMP integration.

### Notifications

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers
/cc helpful folks from [Slack channel](https://amphtml.slack.com/archives/C4NVAR0H3/p1643122843902329) @powerivq @erwinmombay @kristoferbaxter @calebcordry 🙏

**Comment by newmuis** [comment]
Approved for a cherry-pick to beta, experimental, stable.

This does not meet the bar for a cherry-pick to LTS (that said, it looks as if this entire extension is newer than this LTS build `2111242025001` which appears to have been promoted to LTS on 12/14/2021, so it is not applicable anyway).

**Comment by mlapeyre3** [comment]
Thank you @newmuis ! Would you mind telling me what would be the ETA in that case? I am pretty new to the whole AMP release cycle and I don't know if the on-duty engineer is able to work on it today.

It is evening here in Paris, and the beginning of the day in SF, but I am happy to assist you in any way in the next hours.

Thanks!

**Comment by newmuis** [comment]
I've just merged #37483, which means that we can begin the cherrypick process.

The cherrypick itself will take some time, as well as testing and verifying the new build, then subsequently releasing it.  The whole process will likely take several hours.  I don't have an exact ETA, but perhaps some time around the end of the day in the US Pacific time zone seems possible.

**Comment by mlapeyre3** [comment]
It is super clear thank you !

**Comment by newmuis** [comment]
This cherrypick has made it to beta/experimental and stable.

@mlapeyre3 can you help verify that the bug is no longer reproducible?

**Comment by mlapeyre3** [comment]
Hello @newmuis, @rsimha,
Thank you guys and sorry for the mess.

I tested the stable branch on my test page which reproduces a "Google AMP Cache powered" page and I see the bug is no longer there (ou <amp-ad> tag sends ad requests)
![image](https://user-images.githubusercontent.com/19735493/151323152-5442e201-7b84-4ece-a69b-01078b118aa6.png)

I also checked on a customer's page in production. It uses the stable version as well and now generates ad requests 💪
![image](https://user-images.githubusercontent.com/19735493/151323303-fd2c793a-7085-4962-bc14-3b8758469832.png)

PS: do you know how I could "force" or at least accurately reproduce using the Google AMP cache on my test pages? Or I need to publish a fully valid AMP page on production and wait for the bot to crawl my page?

Thanks!
