### ISSUE TITLE
Whitelist Typography.com fonts

### ISSUE THREAD

**Issue by arajay** [ampproject/amphtml#3749]
Typography.com is a custom font provider. Their basic licensing agreement prohibits the download of their custom fonts; the only option for font embedding (without paying a hefty licensing fee) is to link to their cloud hosted stylesheet. 

Example:
`<link rel="stylesheet" type="text/css" href="//cloud.typography.com/6256354/724768/css/fonts.css">
`

This is a request to whitelist Typography.com CDN for serving fonts to AMP clients. 

Is this possible? Or would it require each individual stylesheet URL to be whitelisted in the AMP CSP, as indicated by the response to [this request](https://github.com/ampproject/amphtml/issues/3576)?

**Comment by cramforce** [comment]
Absolutely possible. Steps:

- whitelist in validator
- update CSP

@arajay Are you with typography.com?

**Comment by arajay** [comment]
I do not work for typography.com but many of my clients use their CDN hosted fonts; in the meantime I have been using alternate web-safe fonts for my AMP pages instead.

**Comment by Gregable** [comment]
Do you know what the range of possible URLs here would be? 
Would `https://cloud\.typography\.com/[0-9]*/[0-9]*/css/fonts.css` work?

**Comment by arajay** [comment]
Affirmative @Gregable ; the stylesheet links for all my clients are formatted in that manner.

**Comment by cramforce** [comment]
@arajay Could you try to get somebody from typography.com to comment here. Many font providers do referrer checking which may require additional work for AMP.

**Comment by arajay** [comment]
"Sarah," a representative from Typography.com replied to my request with: "We do not allow for the white listing of domains."

**Comment by cramforce** [comment]
I'm not sure what that means :)

So, lets go ahead here.

@Gregable I think just going for the prefix `https://cloud.typography.com/`is fine.

**Comment by Gregable** [comment]
Closing, but will be a little while longer before it's released.

**Comment by cramforce** [comment]
I assume we still need to make the CSP change, right?

Sending you a CL.

**Comment by cramforce** [comment]
New CSP

`content-security-policy:default-src * data:; script-src https://cdn.ampproject.org/rtv/ https://cdn.ampproject.org/v0.js https://cdn.ampproject.org/v0/ https://cdn.ampproject.org/viewer/; object-src 'none'; style-src 'unsafe-inline' https://cloud.typography.com https://fast.fonts.net https://fonts.googleapis.com https://maxcdn.bootstrapcdn.com; report-uri https://csp-collector.appspot.com/csp/amp`

**Comment by Gregable** [comment]
This is now live everywhere.

**Comment by lannka** [comment]
We saw a bug that
cloud.typography.com is doing a 302 redirect to a different domain, and the css is then blocked by CSP.

See [example](
https://cdn.ampproject.org/v/heatst.com/entertainment/major-spoilers-the-entire-plot-of-game-of-thrones-season-7-may-have-been-leaked-on-reddit/amp/?amp_js_v=5).

It works fine on the canonical page, but has problem on CDN.
