### ISSUE TITLE
React e2e testing

### ISSUE THREAD

**Issue by dethstrobe** [ampproject/amphtml#37508]
### Summary

Implement e2e tests for the react bento components.

### Design Document

Since the e2e tests currently transpiles the react components anyway, all we should theoretically need to do it create a react environment and fixtures to render the react components.

We maybe able to leverage current e2e tests if the DOM structure is similar but only need to swap out the environment and fixtures. However this will probably not be the case, since for example the bento web-components use the shadowDOM while the preact and react versions will not be.

### Motivation

Currently the react components are not tested. There could be problems with transpiling from preact to react that causes unintended breaks in functionality.

#### Manual Testing
We could manually test components with storybook, probably not ideals and will eat up a lot of time.

#### Unit Testing
Figure out a way to write unit tests. This could be difficult since we need to transpile the cost from preact to react first, which the e2es already do. Also we'd need to possibly duplicate the preact unit tests to run in the react context, though there might be a way to avoid that with aliasing.

### Notifications

/cc @ampproject/wg-approvers

**Comment by dethstrobe** [comment]
# Initial investigation

I've tried to make a stand alone fixture file that can run a React SPA from a CDN copy of react.

This has proven to be unfruitful. It requires us to build the react components as ESmodules, which we do support. But also requires to remove the import statements from the component as the CDN copy of React is placed on the global namespace. Another problem is that JSX is not supported, and needing to write raw React to create the elements is cumbersome and not easily reusable compared to our other ways of writing fixtures.

It is possible to load babel in the browser to transpile JSX in to react, however it also transpiles import statements to use require. And loading require seems to have issues making network calls. It's possible this is all solvable, but I think it might be more consistent to use the currently existing build tools to transpile and bundle a react SPA for testing

## Example of React CDN SPA

### react-fixture.html
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Hello World</title>
    <script
      type="module"
      src="https://unpkg.com/react@17/umd/react.development.js"
    ></script>
    <script
      type="module"
      src="https://unpkg.com/react-dom@17/umd/react-dom.development.js"
    ></script>

    <!-- Don't use this in production: -->
    <!-- <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script> -->
    <script type="module" src="./react-fixture.js"></script>
    <link rel="stylesheet" href="../dist/styles.css" />
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>

```

### react-fixture.js
```js
import {
  BentoAccordion,
  BentoAccordionSection,
  BentoAccordionHeader,
  BentoAccordionContent,
} from '/extensions/amp-accordion/1.0/dist/component-react.max.module.js';

ReactDOM.render(
  React.createElement(
    BentoAccordion,
    null,
    React.createElement(
      BentoAccordionSection,
      null,
      React.createElement(BentoAccordionHeader, null, 'Header1'),
      React.createElement(BentoAccordionContent, null, 'Content 1')
    ),
    React.createElement(
      BentoAccordionSection,
      null,
      React.createElement(BentoAccordionHeader, null, 'Header2'),
      React.createElement(BentoAccordionContent, null, 'Content 2')
    ),
    React.createElement(
      BentoAccordionSection,
      null,
      React.createElement(BentoAccordionHeader, null, 'Header3'),
      React.createElement(BentoAccordionContent, null, 'Content 3')
    )
  ),
  document.getElementById('root')
);
```

**Comment by jridgewell** [comment]
How are we currently doing E2E for preact? It seems like we should be able to build a harness that swaps out preact for react when running the test?

**Comment by dethstrobe** [comment]
We don't test e2e with preact. We currently only e2e test the web component and AMP.

**Comment by jridgewell** [comment]
The approach with multiple test storybook test fixtures sounds good to me.

**Comment by dethstrobe** [comment]
# Final Implementation

After some discussion, it was decided to build the e2e bundles before each test. It requires a bit of extra configuration for the e2e tests, requiring that we add 2 keys in the testing options object. That being `bentoComponentName` which value will equal the name of the component being tested, and `testFor` which will either be preact or react.

The react bundle, takes a significantly longer time compared to the preact bundle, so a longer timeout set to 20 seconds was added for these tests. We might need to be extended the timeout again if we find more complex components take longer to build.
