### ISSUE TITLE
[Amp Story Player] Swiping from a story to another can leads to fully froze story

### ISSUE THREAD

**Issue by llccrr** [ampproject/amphtml#37511]
### Description

If you swipe from left to right several times, the player may enter a freeze state, and you cannot play your story anymore, No more events are taken into account. 
it seems to happen more often with the swipe to left than the swipe to Right.  
In the screenshot you can see it froze in a "middle state" between two Stories, it might also happen when you are completely on a story. 
![image](https://user-images.githubusercontent.com/15107671/151539948-6bf3068d-d5cf-46d0-96f8-b32b398727c7.png)

https://codesandbox.io/s/player-sound-bug-18nuk

### Reproduction Steps

Go to the last Story using swipe to right (which is a video) and try to swipe to left to the previous story

https://codesandbox.io/s/player-sound-bug-18nuk

**Comment by llccrr** [comment]
Any news ?

**Comment by gmajoulet** [comment]
Fixed by https://github.com/ampproject/amphtml/pull/37848
