### ISSUE TITLE
[Amp Story Player] Video audio playing when the story is already left

### ISSUE THREAD

**Issue by llccrr** [ampproject/amphtml#37512]
### Description

When you have a video in a story, most of the time the audio is buggy. 
You will still have the audio of the video, meanwhile you are already on the next story (swipe to right)
You can also reproduce the bug by using tap to next. 
https://codesandbox.io/s/player-sound-bug-18nuk

### Reproduction Steps

When the story start, active the sound, swipe slowly to the next story the sound might still play. 
You can reproduce kind of easily on Chrome by refreshing your page if the previous step did not work and try again.

**Comment by gmajoulet** [comment]
Fixed by https://github.com/ampproject/amphtml/pull/37848
