### ISSUE TITLE
Quality of life refactors for Bento

### ISSUE THREAD

**Issue by kvchari** [ampproject/amphtml#37538]
Below are a list of refactors that we should do eventually. They came from the [original refactor](https://github.com/ampproject/amphtml/pull/37309#issuecomment-1011222406) of the PBE class hierarchy. They're largely aimed at improving the readability of the code and removing any vestiges of amp patterns. 

- [ ] stop exporting define() functions for "sub components" of extensions (bento-facebook, bento-inline-gallery, bento-embedly-card all expose "sub coponents")
  * issue: this is technically a breaking change (although I guess it's not if we consider it a bug that they were exposed to begin with)
- [ ] rename classes representing Bento components from `BaseElement` -> `BentoFoo`
  * issue: currently standalone web components are built by generating a file with a `defineElement()` function for each extension. This generated file has the line: [`import {BaseElement} from '../base-element' `](https://github.com/ampproject/amphtml/blob/main/build-system/tasks/extension-helpers.js#L755). To ensure that this doesn't break we may need to export BentoFoo as well as a BaseElement alias for it. (`export class BentoFoo {...}` and an alias `export {BentoFoo as BaseElement}`). Or we can create that function in each base-element.js file directly and stop autogenerating this extra file.
- [ ] rename files containing Bento components from `base-element.js` -> `bento-foo.js`
  * Issue: currently autogenerated `bento-foo.js` files are used to publish standalone web component scripts, so there's a naming conflict here.
- [ ] change testing infra to allow tests to run with AMP runtime to support <bento-*> unit testing
  * issue: current amp testing infra pulls in the AMP runtime inadvertently. There are [workarounds](https://github.com/ampproject/amphtml/pull/37309/commits/0704b8ca00fccabbce96e7cd2d59967078913e0c) to this, but they conflict with the config that is necessary to run amp unit tests in CI. Need to work with infra to figure out way to decouple these tests
- [ ] refactor `setSuperClass` such that it doesn't return so that it doesn't give the illusion of being a pure function
  * note: see discussion [here](https://github.com/ampproject/amphtml/pull/37309#discussion_r779919449)

**Comment by erwinmombay** [comment]
closing issue as stale
