### ISSUE TITLE
Chrome Validator extension stops working if left idle

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#3753]
1. Open a page that is AMP enabled and then leave the tab for a period.
2. Continue doing other things in chrome with lots of tabs open.
3. Eventually chrome kills the background page belonging to the validator extension.
4. When you switch back to the tab with the original page and click the blue validator icon to get the AMP version nothing happens.

You can fix this by setting `"persistent": true` in the extension manifest.

**Comment by honeybadgerdontcare** [comment]
Thanks for the suggestion. The change is pushed in v.1.0.6 which is now live on the [Chrome Web Store](https://chrome.google.com/webstore/detail/amp-validator/nmoffdblmcmgeicmolmhobpoocbbmknc). Your extension should update automatically in time, or you can force an update by enabling Developer Mode at chrome://extensions and then clicking "Update extensions now."

**Comment by jpettitt** [comment]
Now that's a fast bug fix. Thx.
