### ISSUE TITLE
amp-bind e2e test flakiness

### ISSUE THREAD

**Issue by powerivq** [ampproject/amphtml#37532]
### Description

E2e test "should support binding to src" are routinely failing for timing out: see https://app.circleci.com/pipelines/github/ampproject/amphtml/22098/workflows/ea944bc5-0b7f-4b4e-893f-06f3444baf0e/jobs/435839/tests#failed-test-0

I would propose to disable these tests for now.

@ampproject/wg-amp4email 

### Reproduction Steps

Run e2e test

### Relevant Logs

```shell
amp-bind chrome Viewer environment "before each" hook for "should support binding to src"

"before each" hook for "should support binding to src"
/home/circleci/project/test/e2e/test-amp-bind-iframe.js
amp-bind chrome Viewer environment "after each" hook for "should support binding to src"

"after each" hook for "should support binding to src"
/home/circleci/project/test/e2e/test-amp-bind-iframe.js
```

**Comment by zhangsu** [comment]
I think the wrong WG (wg-amp4email) is tagged here - this isn't an email-specific issue.

**Comment by powerivq** [comment]
@zhangsu Not sure why but amp4email was listed as the owner of amp-bind. No worries.

**Comment by powerivq** [comment]
@samouri Not sure if there are better alternatives here. Maybe disable it on Chrome only? I see this is the only test for amp-bind, so I do not want to disable the only e2e test.

**Comment by samouri** [comment]
@powerivq: disabling for now seems like a good idea. I'm having trouble reproducing locally, since the ChromeDriver version is out of date.
