### ISSUE TITLE
Problem amp-consent blocks websites

### ISSUE THREAD

**Issue by Marco-Prontera** [ampproject/amphtml#37550]
### Description

Hi, I have a problem with implementing a new version of our CMP on AMP.

Running the amp project locally via `node amp.js` and changing the URL in the `cmps.js` file to this:

```
CMP_CONFIG ['pubtech'] = {
  'consentInstanceId': 'pubtech',
  'checkConsentHref': 'https://amp.pubtech.it/cmp-amp-check-consent',
  'promptUISrc': 'https://www.talksmedia.it/prova-rit/index.html',
};
```
then by going to the amp-consent example page and selecting my vendor everything works. But when I update the code in the server in the URL "promptUISrc" already used by amp in the various devices, the request that the amp-consent component makes to the index.html is pending and fails to start anything by blocking the sites. Also sometimes it loads but doesn't open which is strange as in amp local development everything works.

Here is a screenshot to show you an example of what happens on our customers' sites:
![Schermata 2022-02-02 alle 11 35 53](https://user-images.githubusercontent.com/50167854/152137916-a8c752ef-af34-44ab-a77c-19fdb57237c1.png)

### Reproduction Steps
Start amp project:
`node amp.js`
Replace configuration code for pubtech cmp in 
`amphtml/extensions/amp-consent/0.1/cmps.js`
with
`CMP_CONFIG ['pubtech'] = {
  'consentInstanceId': 'pubtech',
  'checkConsentHref': 'https://amp.pubtech.it/cmp-amp-check-consent',
  'promptUISrc': 'https://www.talksmedia.it/prova-rit/index.html',
};
`
Open Chrome browser and visit this URL
`http://0.0.0.0:8000/examples/amp-consent/cmp-vendors.amp.html?type=pubtech`

Result:
![Schermata 2022-02-02 alle 20 42 29](https://user-images.githubusercontent.com/50167854/152225263-9c292ce0-1058-42ca-ba75-8465b94a299f.png)

So far, so good.

If I replace the code of the page "https://cdn.pubtech.ai/amp/index.html" with what is found "https://www.talksmedia.it/prova-rit/index.html "the CMP stops working when it is visited from any device through the Google AMP viewer.
**And when the CMP is performed directly in some site, the CMP does not start or the HTTP request to the "promptUISrc" (https://cdn.pubtech.ai/amp/index.html) remains pending as in the screenshot attached above**
It seems that this bug only occurs when the user visits the website with Google AMP Viewer. How can you simulate this visualization? there's a way? How we can resolve this?
https://developers.google.com/search/docs/advanced/experience/about-amp#about-google-amp-viewer

**_Note: When I try to deploy the code on index.html I don't see any code errors, neither on the console nor on post-messages._**

### OS(s) Affected

All

### Device(s) Affected

All

**Comment by Marco-Prontera** [comment]
Bug solved

**Comment by xavierleune** [comment]
Hi @marco-prontera can you please share some details on how you resolved this bug ? We have the same symptoms and we don't really know what to do here... Thanks for your help
