### ISSUE TITLE
Create Bento component for "amp-nested-menu".

### ISSUE THREAD

**Issue by dhaval-parekh** [ampproject/amphtml#37574]
### Summary

Currently, To implement nesting menu with one or more layers of submenus in AMP [`amp-nested-menu`](https://amp.dev/documentation/components/amp-nested-menu/) is used with [`amp-sidebar`](https://amp.dev/documentation/components/amp-sidebar/). However, Since there is no bento version of `amp-nested-menu` component that is not possible in bento to implement the nesting menu.

### Motivation

To have the option to implement a nesting menu with bento component the same way it's currently possible in AMP.

### Alternative Solutions

Currently, there isn't an alternate solution.

### Notifications

/cc @ampproject/wg-approvers

**Comment by erwinmombay** [comment]
closing issue as stale but feel free to re-open if the work will be continued
