### ISSUE TITLE
AMP Playground not working

### ISSUE THREAD

**Issue by MaddyGitHub01** [ampproject/amphtml#37603]
### Description

Currently the amp playground(https://playground.amp.dev/) is not working properly. It is not showing any errors/issues even after entering the wrong code. I am experiencing this with the AMP email.

Kindly suggest or fix as i've already tried restarting, incognito, cookies removal etc..

### Reproduction Steps

https://user-images.githubusercontent.com/18568241/153050069-eecc5fe3-b26d-4b33-a52e-f9671ae551f4.png

**Comment by sebastianbenz** [comment]
Thanks for reporting this. Could you please share the URL you're using to access the playground. When I access the playground via https://playground.amp.dev/?runtime=amp4email everything works as expected.

**Comment by erwinmombay** [comment]
unable to reproduce. please re-open if there is additional information
