### ISSUE TITLE
[amp-story-player] Wrong storyContentLoaded data when using getStories method

### ISSUE THREAD

**Issue by edoudou** [ampproject/amphtml#37602]
### Description

It seems to be an error when using the `getStories` method. `storyContentLoaded` attributes this to be only filled for current story.

### Reproduction Steps

- Listen to the amp story messages on the window.
- When getting a "storyContentLoaded" message, check the status of the stories in the player using player.getStories() 
- open the first story
  2 storyContentLoaded message:
  - the first when the first story is loaded. Only the first story has an attribut storyContentLoaded
  - the second, I assume when the next story has loaded. But still only the first story has the attribute storyContentLoaded.
-  then try to open the second story, you'll never get an other storyContentLoaded message, as it already hapenned, but the key was not added to the story data.

I am linking a video showing theses steps : 
https://user-images.githubusercontent.com/4236706/153044481-889acd02-d26b-46d8-9132-1e3993183b53.mov

Discutting these issues with @mszylkowski he noticed : 

> You are right, in `amp-story-player-impl:859`  it only sets `storyContentLoaded`  for the first story, it never calls `initStoryContentLoadedPromise_`  for other stories in the player so the value is never set for them.

### Browser(s) Affected

Chrome, Firefox, Safari

**Comment by gmajoulet** [comment]
Fixed by https://github.com/ampproject/amphtml/pull/37848
