### ISSUE TITLE
🌸 Cherry-pick request for #37625 into #37547

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#37629]
### Issue (P0 Bug)

#37625

### Pull Request(s)

#37625

### AMP Version(s)

2201262038001

### Channels

Beta / Experimental

### Formats

Websites

### Justification
Nothing is _broken_.
This CP will allow us to test new cache-side code ~1 week earlier than otherwise.
No postmortem necessary.

### Notifications

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by jridgewell** [comment]
Approved

**Comment by estherkim** [comment]
Do you mean `2202042210000` for beta? `2201262038001` is stable

**Comment by rcebulko** [comment]
> Do you mean `2202042210000` for beta? `2201262038001` is stable

I believe this started out as a request to CP into Stable and LTS, but Justin noted (out-of-thread) it didn't meet the threshold for a Stable CP, so the labels were updated but the AMP version in the description was not

**Comment by samouri** [comment]
> > Do you mean `2202042210000` for beta? `2201262038001` is stable
> 
> I believe this started out as a request to CP into Stable and LTS, but Justin noted (out-of-thread) it didn't meet the threshold for a Stable CP, so the labels were updated but the AMP version in the description was not

Meant to do just Beta! so `2202042210000`
