### ISSUE TITLE
I2I AMP Optimizer:  Remove unused extensions from <head>

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#37620]
### Summary

While perusing AMP Documents in the wild, I noticed that many seem auto-generated from canonical docs. These generators/templates can be imprecise about which extension scripts are included in the head.  I've seen countless examples now of pages with extensions specified in the head that are unused within the document.

This incurs a silly cost. We can likely move the performance needle simply by performing a simple DCE of extensions in `<head>`. Ideally we could have a validator pass for this, but it is likely too late for that.

As examples:
1. `https://www.bournemouthecho.co.uk/news/19872232.amp/`: amp-instagram is unused
2. `https://sportstar.thehindu.com/kabaddi/pro-kabaddi-league-season-8-fixtures-schedule-covid-19-changes-match-timing-pkl-2022/article38320918.ece/amp/`: amp-carousel is unused

### Motivation

vroom

### Alternative Solutions

N/A

### Notifications

/cc @ampproject/wg-approvers @ampproject/wg-caching

**Comment by Gregable** [comment]
The AMP Validator does require usage if the extension is included, but certain extensions are exempted from this requirement. In the first example, if you replace `amp-instagram-0.1` with `amp-instagram-1.0`, you'll get a validation error:

```
The extension 'amp-instagram' was found on this page, but is unused. Please remove this extension.
```

Some extensions were implemented and added to the validator prior to support for requiring usage. In the interest of backwards compatibility, we do not return errors for those extensions. Newer extensions require usage to be in the document.

You can see how these rules are implemented in https://github.com/ampproject/amphtml/blob/main/extensions/amp-instagram/validator-amp-instagram.protoascii . The 0.1 version has a field:

```
requires_usage: EXEMPTED
```

While the 1.0 version does not. The default value is an error. The documentation of this field is [here](https://github.com/ampproject/amphtml/blob/main/validator/validator.proto#L510).

The AMP Cache also already removes unused extensions from the head when serving the document, including the exempted ones above. As does the [AMP Packager](https://github.com/ampproject/amppackager/blob/main/transformer/transformers/unusedextensions.go) for signed exchanges. I don't know about the optimizer, but it likely does as well.
