### ISSUE TITLE
Web Story not displaying using embed code displaying multiple console errors

### ISSUE THREAD

**Issue by adamdunnage** [ampproject/amphtml#37642]
### Description

@gmajoulet creating this new issue as suggested.

We have a new report in the Web Stories support forums which you can find here: https://wordpress.org/support/topic/webstories-not-displaying-in-sidebar-via-shortcode/#post-15350186.

The user is trying to add the Web Stories embed code to the 'sidebar' of their page. The story isn't displaying on the page and I can see the following console errors on the page.

`Uncaught Error: Render timeout waiting for service amp-story-render to be ready`
&
`Uncaught (in promise) Error: No messaging channel: initMessagingChannel timeout`

Suggested that the user try using this embed code: 
`[web_stories_embed url="https://nonfungibleownership.com/web-stories/theta-review/" title="theta-review" poster="https://nonfungibleownership.com/wp-content/uploads/THETA-3-poster-640x853.png" width="360" height="600" align="none"]`

This embed code did not work and no story is displayed on their [page](https://nonfungibleownership.com/theta/). 

### Reproduction Steps

1. User added embed code provided above to their page.
2. Publish page.
3. View page and no web story displayed.

**Comment by swissspidy** [comment]
Note that this embed code is WordPress-specific.

Reports in the amphtml repo would need to be generic enough so that they could be reproduced without the Web Stories WP plugin.

For anyone looking into this, the above shortcode gets turned into a simple `amp-story-player`

```html
<amp-story-player
	width="360"
	height="600"
	layout="intrinsic">
	<a href="https://nonfungibleownership.com/web-stories/theta-review/">
		<img
			src="https://nonfungibleownership.com/wp-content/uploads/THETA-3-poster-640x853.png"
			width="640"
			height="853"
			loading="lazy"
			data-amp-story-player-poster-img
			alt="theta-review"
		/>
	</a>
</amp-story-player>
```

**Comment by gmajoulet** [comment]
Thank you for sharing a repro link!
I'm not sure who's responsible for this CSS, but the `<amp-story-player` has a `display: none;` that prevents it from being visible. It looks like it'd get revealed with a `.entered` class, that never gets added.
Removing the `display: none;` correctly displays the story, so I believe it's just a CSS issue, independent from our implementation.

Hope it helps!

**Comment by swissspidy** [comment]
Thanks for checking.

That's definitely not coming from our plugin.

@adamdunnage Can you check with the user that they should fix their JS errors and try a different theme or disable other plugins?

This issue can be closed.

**Comment by edoudou** [comment]
@gmajoulet Do you know if there is any other css ca could prevent the story to start a communication ?

I get the same error (`Error: No messaging channel: initMessagingChannel timeout`), I indeed had a `display: none;`, but I removed it, I removed an `opacity : 0;`, I prevented the modal to be out of sight, I changed lots of things that I tought could be the issue up until this point : https://w4py9r.csb.app/

I have no idea what to change next ...

Also, it does not seems to be happening with every stories, any clues why ?

**Comment by gmajoulet** [comment]
Thank you for posting the demo, this is a completely different bug that is tied to your implementation. When you render the story as `visibilityState=inactive`, components do NOT render.
The extension responsible for answering these `initMessageChannel` is `amp-viewer-integration`, which gets lazy loaded when you have that `storyPlayer` parameter in the URL (which you do have), but the component that lazy loads it doesn't build in `inactive` mode.

You have two options:

1. Add the `amp-viewer-extension` script in ALL your documents
2. Only load stories in `prerender/preview/visible` visibilitystates

**Comment by edoudou** [comment]
Ok thanks, it seems to be working
