### ISSUE TITLE
[amp-story-player] Story may not open in some strange cases

### ISSUE THREAD

**Issue by edoudou** [ampproject/amphtml#37690]
### Description

When calling the show and play method in the player, it sometimes freezes on the current story.

### Reproduction Steps

Here is a codesandobox that could help you for our main problem :
https://ceuiq.csb.app/

Try to :
refresh the page
open the 3rd story
Wait for like a seconde or 2,
Close it and open the 2nd.
First, it take a lot of time to open the 2 one most of the time as I am watching the storyContentLoaded key to be updated, which sometimes is not (cf https://github.com/ampproject/amphtml/issues/37602)

Also, like 20% of the time on android, and way often on iphone it seems, the story shown is the 3rd one, but it is pause, and the entire iframe seems to be frozen.

### OS(s) Affected

Android 11, iOS 15

### Device(s) Affected

One plus 8, Iphone SE

### AMP Version Affected

2201262038001

**Comment by ychsieh** [comment]
Not reproducible
