### ISSUE TITLE
investigate error in amp accordion

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#3770]
Error: D@https://cdn.ampproject.org/rtv/011466185787499/v0/amp-accordion-0.1.js:12:287 buildCallback@https://cdn.ampproject.org/rtv/011466185787499/v0/amp-accordion-0.1.js:10:179 build@https://cdn.ampproject.org/rtv/011466185787499/v0.js:245:386 build@https://cdn.ampproject.org/rtv/011466185787499/v0.js:121:106 upgraded@https://cdn.ampproject.org/rtv/011466185787499/v0.js:182:440 upgrade@https://cdn.ampproject.org/rtv/011466185787499/v0.js:245:150 Wf@https://cdn.ampproject.org/rtv/011466185787499/v0.js:240:374 g@https://cdn.ampproject.org/rtv/011466185787499/v0.js:272:139 Yb@https://cdn.ampproject.org/rtv/011466185787499/v0.js:41:1208 registerElement@https://cdn.ampproject.org/rtv/011466185787499/v0.js:272:225 https://cdn.ampproject.org/rtv/011466185787499/v0/amp-accordion-0.1.js:13:392 https://cdn.ampproject.org/rtv/011466185787499/v0.js:273:370 Ea@https://cdn.ampproject.org/rtv/011466185787499/v0.js:14:130 Fa@https://cdn.ampproject.org/rtv/011466185787499/v0.js:14:383 push@https://cdn.ampproject.org/rtv/011466185787499/v0.js:273:346 global code@https://cdn.ampproject.org/rtv/011466185787499/v0/amp-accordion-0.1.js:1:37

**Comment by erwinmombay** [comment]
hmm looks like this is the sessionStorage issue

cc @zhouyx

**Comment by zhouyx** [comment]
#3797
