### ISSUE TITLE
🌸 Cherry-pick request for #37671,#37646 into 2202142035000

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#37715]
### Issue (P0 Bug)

N/A

### Pull Request(s)

https://github.com/ampproject/amphtml/pull/37671, #37646

### AMP Version(s)

2202142035000

### Channels

Beta / Experimental

### Formats

Websites

### Justification
Nothing is _broken_.
This CP will allow us to test new cache-side code ~1 week earlier than otherwise.
No postmortem necessary.

### Notifications

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by rcebulko** [comment]
approval

**Comment by jridgewell** [comment]
Approved for Beta
