### ISSUE TITLE
[amp story shopping] JSON schema

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#37746]
### Description

A [JSON schema](https://json-schema.org/specification.html) to spec the API for the shopping config and use for validation within tooling.

This file could be hosted on GitHub as part of the project but we do not want to include it in our bundle.

We will need to keep it in-sync with any config changes.

cc @calebcordry 

### Alternatives Considered

We could point a link to the validation javascript file, but that would require people to read through the component code. 
JSON schema is scalable and standardized which will help ease of integration into tooling.

### Additional Context

More context within discussion on [shopping validation I2I](https://github.com/ampproject/amphtml/issues/36460#issuecomment-1041430405).

**Comment by alanorozco** [comment]
I propose that instead of keeping the JSON schema in sync with the implementation code, we generate the code from schema instead.

We can use `ajv` to generate the code. See an implementation on #37794. Output size is small enough from what I've seen.

**Comment by newmuis** [comment]
@jshamble when you have bandwidth, can you try writing a JSON schema for the config JSON?  I think it should be fairly straightforward, given that the structure isn't very verbose.

Once we have a test schema based on https://github.com/ampproject/amphtml/issues/36460, it should be pretty easy to see the bundle size of the output concretely, which I know is a concern that @gmajoulet brought up.

I'd love to do this if we can keep bundle size small; thanks @alanorozco for investigating!

**Comment by newmuis** [comment]
Actually, I forgot I'd experimented with writing a JSON schema spec to represent an entire story (doesn't quite have feature parity, but it's a reasonable representation): https://github.com/newmuis/story-schema

I have a `compile-schema` script that does:

```bash
make-dir dist && ajv compile -s 'root.schema.json' -r 'schemas/**/*.schema.json' -o 'dist/story-validator.js' --spec=draft2020 --all-errors=true --messages=false --inline-refs=false --code-optimize=10
```

With the full story schema, it gets:

```bash
$ yarn run compile-schema && wc -c < ./dist/story-validator.js 
215807
```

Then I tried simplifying the schema to:

```json
{
  "$id": "https://github.com/newmuis/story-schema/root.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object"
}
```

This is one of the simplest schemas you can have AFAIK, and still:

```bash
$ yarn run compile-schema && wc -c < ./dist/story-validator.js 
955
```

I really love this idea, and would love to find a generalizable solution that works (like... I really want that a lot), or a way to use AJV's options to strip the output down further (admittedly, I didn't try that hard).  But, bounding this between `[955, 215807]` bytes isn't super promising ☹️

**Comment by newmuis** [comment]
Actually, while procrastinating from other things... I just threw together a quick schema.  @jshamble's outline in #36460 made it pretty easy, and I followed it pretty closely:

```json
{
  "$id": "https://github.com/newmuis/story-schema/test.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "items"
  ],
  "properties": {
    "items": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "productUrl",
          "productId",
          "productBrand",
          "productTitle",
          "productPrice",
          "productPriceCurrency",
          "productImages",
          "productDetails",
          "aggregateRating"
        ],
        "properties": {
          "productUrl": { "type": "string" },
          "productId": { "type": "string" },
          "productBrand": { "type": "string" },
          "productIcon": { "type": "string" },
          "productTitle": { "type": "string" },
          "productDetails": { "type": "string" },
          "productPrice": { "type": "number", "minimum": 0 },
          "productPriceCurrency": {
            "enum": [
              "AED",
              "AFN",
              /* like, 150+ more currencies */
              "ZMW",
              "ZWL"
            ]
          },
          "productImages": {
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": false,
              "required": [ "url", "altText" ],
              "properties": {
                "url": { "type": "string" },
                "altText": { "type": "string" }
              }
            }
          },
          "aggregateRating": {
            "type": "object",
            "additionalProperties": false,
            "required": [ "ratingValue", "ratingCount", "ratingUrl" ],
            "properties": {
              "ratingValue": { "type": "number", "minimum": 0 },
              "ratingCount": { "type": "number", "minimum": 0 },
              "ratingUrl": { "type": "string" }
            }
          }
        }
      }
    }
  }
}
```

Then I re-ran the same methodology as above:

```bash
$ yarn run compile-schema && wc -c < ./dist/story-validator.js 
3464
```

So, this is 0.33kB gzipped.  Of course, as the schema itself grows, as will the bundle size.  But, it could be a scalability win and a maintenance win.  We should not literally use the schema above, since we should probably e.g. verify that the URLs are URLs (if we care about that), verify that the IDs are HTML-ID-like, etc.  But I'm not sure those will substantially change the bundle size.

If we want to verify many things at runtime, we could also consider the method of shipping a minified version of `ajv` and running all the schemas against it at runtime, rather than compiling the separate validation functions.  I think that's a question for down the road, but this actually seems not too bad!

@alanorozco @calebcordry @gmajoulet for your thoughts on the bundle size

**Comment by calebcordry** [comment]
Thanks for the awesome analysis @newmuis ! 

It seems like the main question is if the extra 2.1 kB is worth the maintenance cost of manually keeping the schema in sync? I really like the idea of JSON Schema but unfortunately I think the 2.1kB might be too large of a price to pay (unless, as Jon mentioned, we might be missing some compiler optimizations). I believe @gmajoulet has data showing real impact on users making it to "story load" for a magnitude of ~3kB.

**Comment by gmajoulet** [comment]
About bundle size, as long as it is NOT in the critical loading path (e.g. v0/amp-story/amp-analytics...) it's acceptable.
Do we know for a fact that creation tools will use it? Have we heard complaints from creation tools about other components validation?

**Comment by newmuis** [comment]
Other components use regular AMP validation, do I think they get coverage that we won't here.  The only story features I can think of that use JSON thus far (ads, analytics, consent) do not change the narrative and can likely have a single setup per-tool, just plugging in a value or two.  This has many dimensions of configurability across tool, shopping vendor, and creator.  It probably benefits us to have a clear spec and a canonical validation flow so folks can make sure their getting it right

**Comment by gmajoulet** [comment]
My main point is that this has a strict negative impact on end users, just so we don't have to maintain and keep in sync custom validation + schema. DevX is great, but users experience should go first.
I'd rather solve this with a few unit tests running the configuration against both the JSON schema and the custom validation, than shipping extra kbs to our bundles.

Making the shopping bundle slightly heavier is fine as it is lazy loaded after the story is rendered, but that means we couldn't use it for anything part of the main bundles (as @newmuis mentioned, Ads, analytics, consent).

However I'm not going to be resistant to this change, as long as it doesn't impact the main bundles.

**Comment by newmuis** [comment]
Got it.  I think all I care about is that we have a distributable means of validation, but how we actually validate against it doesn't matter as much to me.  But it's actually quite important that we're sure that the validation used by tools and the validation used at runtime work the same way (down to the little nuances) -- as long as we can guarantee that, we're good 🙂

**Comment by jshamble** [comment]
@newmuis For the validate currency function,  I am in favor of using javascript's built in `Intl.NumberFormat` over the array of currency codes listed above, it will simply throw an error if a currency is unrecognized (which is what we want given the way our validation is setup). The complete list of currency codes I got from [here](https://datahub.io/core/currency-codes) minified and gzipped is around 7-8kb - not ideal compared to the one-liner below.

```
/**
 * Validates currency in shopping config attributes
 * @param {string} field
 * @param {?string=} curr
 */
export function validateCurrency(field, curr) {
  // This will throw an error on invalid currency codes.
  Intl.NumberFormat('en-EN', {currency: curr}).format(0);
}
```

**Comment by newmuis** [comment]
It's a tradeoff, I think.  This is undoubtedly easier and lighter when we only concern ourselves with JavaScript stacks.

But, if you imagine a stories creation tool written in anything other than JS (of which there are several.... It might actually be the majority of tools), they would then need to understand how to emulate the behavior of these JavaScript functions.

The nice thing about JSON schema is that it is guaranteed to be self-contained and has tooling support across [many languages](https://json-schema.org/implementations.html#validators).  It seems reasonably painful for tools to need to, on a field-by-field basis, understand JavaScript currency handling, date parsing, etc, especially given that the differences are often quite nuanced.

**Comment by processprocess** [comment]
To parse the core goals from this discussion to help guide our decision:
**1.** Distributable / scalable means of validation that works the same between runtime and tools (down to the nuances).
**2.** Does not impact critical loading path.

To achieve **1:** 
Following industry standards will create the most consistency. Maintaining custom validation that works the same down to the nuances may not be realistic. Technical debt can potentially compound as fields are added and edited.

To achieve **2:** 
Communicate to publishers to not use the shopping experience on the first page of a story as a best practice.
Communicate to tools to disable the ability to create the shopping feature on the first page of the story.

Unless we believe there are strong use-cases for shopping on the first page (like single page stories), JSON schema + ajv may be the most scalable and maintainable approach.

**Comment by jshamble** [comment]
After a conversation with @newmuis, for the shopping launch, we have decided to move forward with both solutions, i.e. [JSON schema + ajv](https://github.com/ampproject/amphtml/pull/37794) and JS [client-side validation](https://github.com/ampproject/amphtml/pull/37474). 

The main reason is that: What if validation on the tooling level fails? 
Especially for fields like URLs, any invalid / malformed URL could potentially fall though, posing a hazard to publishers, posing a security threat. Another level of validation would mitigate that risk.

**Comment by alanorozco** [comment]
We might not need to take the the size tradeoff of using `enum` for currency code vs. validating with `Intl`.

`ajv` allows extending syntax with [`addKeyword`](https://ajv.js.org/keywords.html), which allows us to define the output code.

With some [remapping](https://github.com/ampproject/amphtml/commit/ff0746535d51aee6c5dc94c41216117c30931f24), we can generate the ideal `Intl` code that avoids `enum`, while providing the enum for other systems that ingest the schema directly.

**Comment by swissspidy** [comment]
Is the new schema at https://github.com/ampproject/amphtml/blob/main/examples/amp-story/shopping/product.schema.json also accessible via some URL at amp.dev or so? Or are tools expected to grab it from GitHub for now?

**Comment by jshamble** [comment]
@swissspidy 

I don't think there currently is a URL at amp.dev which hosts the `product.schema.json`, but 'm happy to add a patch and host it there if that is convenient for tooling - let me know.

`$id` at the top level doesn't have a purpose if it's not referenced recursively

without a specified `$schema` ajv defaults to the most recent supported schema. All supported schemas are here: https://ajv.js.org/guide/schema-language.html 

VSCode does not support anything after draft-2020-12 yet, but we can still specify the `$schema` if needed, let me know.
