### ISSUE TITLE
Cannot opt-in to Beta on Safari

### ISSUE THREAD

**Issue by samouri** [ampproject/amphtml#37758]
### Description

Safari should be able to opt-in to the Beta channel and receive Beta RTVs when going to various pages.

### Reproduction Steps

1. Go to https://cdn.ampproject.org/experiments.html
2. Click opt-in to Beta
3. Go to https://amp.dev/documentation/examples/components/amp-fx-flying-carpet/preview/?format=websites
4. Notice that the stable channel (`01` prefix) is still used

### Browser(s) Affected

Safari

### Notifications

cc @ampproject/wg-caching, @JuliaTrubchyk

**Comment by MichaelRybak** [comment]
cc @ampproject/wg-infra

**Comment by jridgewell** [comment]
We resolved this recently by using the Requestly extension for Safari, and using [this Query Param Rewrite rule](https://app.requestly.io/rules/#sharedList/1644352217343-Justin-shared-list-2-8-2022) to add `?optin=beta` to any AMP JS requests
