### ISSUE TITLE
🍱 [amp-autocomplete:1.0] Convert AMP Autocomplete to Bento

### ISSUE THREAD

**Issue by becca-bailey** [ampproject/amphtml#37777]
### High-Level Requirements

_To be updated as information becomes available._

| Consideration           | Ready When                                 | Status  |
| ----------------------- | ------------------------------------------ | ------- |
| Component Compatibility | Feature checklist is covered               | ✅ / ✖️ |
| Testing                 | Unit tests and pre-existing e2e tests pass | ✅ / ✖️ |
| Internationalization    | <fill this out>                            | ✅ / ✖️ |
| Analytics               | <fill this out>                            | ✅ / ✖️ |
| Accessibility           | Audit performed                            | ✅ / ✖️ |
| Page Experience         | Audit performed                            | ✅ / ✖️ |
| Documentation           | Written                                    | ✅ / ✖️ |
| Storybook               | Samples written in Preact and AMP          | ✅ / ✖️ |

### Feature Checklist

_To be updated as information becomes available._

### Existing attributes
- [x] `filter`
- [x] `min-characters`
- [x] `src` (is this still necessary?)
- [x] `items`
- [x] `filter-value`
- [x] `inline`
- [x] `maxItems` (not documented)
- [ ] `maxEntries` (not documented)
- [x] `suggest-first` (not documented)

### Actions
TODO

### Events
- [ ] `onError`

### Analytics Events
TODO

### Migration Notes

I have questions around whether a src file and data in script tags is still necessary with Bento. For now, I am leaving it out and using component props instead. 

### Open Tasks

_To be updated as information becomes available._

- [ ] open task 1
- [ ] open task 2
- [ ] open task 3
- [ ] open task 4
- [ ] open task 5

### Notifications

/cc @ampproject/wg-bento

**Comment by fawaz34745** [comment]
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3533600136823939"
     crossorigin="anonymous"></script>
