### ISSUE TITLE
[Amp story shopping] Support newlines in productDescription

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#37787]
Add support for strings with `\n` such as:
`"productDetails": "Lorem \n ipsum dolor sit amet consectetur adipisicing elit. \n Facere error d..."`

**Comment by newmuis** [comment]
We should lightly process this in some way to avoid cases like `"Hello\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nWorld"`.  We could regex replace multiple newlines down to ~one newline, and/or split on newlines discarding whitespace-only substrings, and/or make `<p>`'s out of each paragraph and not show empty ones.
