### ISSUE TITLE
Amp Story Player - Video / Audio playback continues after navigating between stories 

### ISSUE THREAD

**Issue by Ryanhays** [ampproject/amphtml#37807]
### Description

**Expected:** 
When using the Amp Story Player to navigate between stories that contain video & audio, player should automatically pause playback of video and audio of previous story when navigation occurs. 

**Current:** 
When navigating between stories with audio / video, if the story isn't complete, the audio and video continues to play while viewing the next story. This can even cause multiple multiple streams of audio to be playing at once if the next story also features video. 

I have tested this with my own stories, and stories featured on the official amp stories website. Issue occurs consistently, particularly when cache is cleared or the first time loading a page. 

Pls note the audio & video pauses correctly when navigating story **pages** but not between stories. 

### Reproduction Steps

Test case uploaded here : http://testbed.boyintree.com/amp-story-player-issue/

1. Click on any of the cards to launch the player
2. Navigate through story to a page with audio / video 
3.  Unmute Audio
4.  Navigate to next story before current video ends 
5. Audio / Video will continue playing

### Browser(s) Affected

Chrome, Firefox, Safari

**Comment by gmajoulet** [comment]
Fixed by https://github.com/ampproject/amphtml/pull/37848
