### ISSUE TITLE
[amp story shopping] Remove multi line border radius code

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#37808]
### Description

Update:
Remove the multi line border radius code. It's creating motion inconsistency, giving uneven priority to the eye. It also does not provide utility, the two line text still renders with enough room.

Removing this will create visual consistency and remove code.
 
Spoke with @hongcatlover and they agree.

https://user-images.githubusercontent.com/3860311/156802833-49394d6d-e1c1-45a6-9e81-612a44252fe9.mp4

<s>
The border radius work in #37186 regressed. Using [git bisect](https://git-scm.com/docs/git-bisect), the regression was introduced in #37195. It looks like selectors were updated in CSS but not in JS of that PR.
Visual diff tests were down when this regression was introduced so a diff was not triggered.

The three css selectors in [`styleTagText_`](https://github.com/ampproject/amphtml/blob/main/extensions/amp-story-shopping/0.1/amp-story-shopping-tag.js#L177) do not match between [css](https://github.com/ampproject/amphtml/pull/37195/files#diff-4c64c85a36a44680116a976120dfb705a41b56b31fd28e9741777b9c65ebdd1aR91) and [JS](i-amphtml-amp-story-shopping-tag-pill-multi-line).
<img width="300" alt="Screen Shot 2022-03-02 at 9 22 59 AM" src="https://user-images.githubusercontent.com/3860311/156391828-634a8aa3-20e1-44dd-82b2-377dc5f3b468.png">

The [null checks](https://github.com/ampproject/amphtml/blob/main/extensions/amp-story-shopping/0.1/amp-story-shopping-tag.js#L186-L188) and [optional chaining](https://github.com/ampproject/amphtml/blob/main/extensions/amp-story-shopping/0.1/amp-story-shopping-tag.js#L178) can be removed since the work in #37793 runs this logic after the tag is created.

Multi-line border radius prior to regression:
<img width="191" alt="Screen Shot 2022-03-02 at 9 16 56 AM" src="https://user-images.githubusercontent.com/3860311/156390539-3dfa732e-2283-41d3-9615-e3dff59d15dd.png">

Current:
<img width="189" alt="Screen Shot 2022-03-02 at 9 17 54 AM" src="https://user-images.githubusercontent.com/3860311/156390686-93ea92d8-e24c-4930-b768-736b53bcae04.png">

</s>

**Comment by jshamble** [comment]
We will still need the null checks as the shadow root has not been created yet. If you can think of a workaround, let me know.
