### ISSUE TITLE
Update 3P/embed guidance docs

### ISSUE THREAD

**Issue by jmadler** [ampproject/amphtml#3780]
Update [3P/embed guidance](https://github.com/ampproject/amphtml/blob/master/3p/README.md) docs, specifically to:
- Use more concise language
- Clarify that semantic AMP tags for embeds are preferred over amp-iframe
- Provide guidance on creating an AMP tag API
- `<please suggest others>`

**Comment by cramforce** [comment]
I think the one thing we've learned is that we want

- concrete tags (e.g. a particular video player)
- but orthogonal semantics (it is a video player)

**Comment by ericlindley-g** [comment]
@jmadler:  I'm putting this in the Backlog milestone, but please correct/update as needed

**Comment by adelinamart** [comment]
@jmadler is there anything else left to be done for this issues? Thanks
