### ISSUE TITLE
🍱 [amp-sticky-ad:1.0] Convert amp-sticky-ad to Bento

### ISSUE THREAD

**Issue by dethstrobe** [ampproject/amphtml#37826]
### High-Level Requirements

_To be updated as information becomes available._

| Consideration           | Ready When                                 | Status  |
| ----------------------- | ------------------------------------------ | ------- |
| Component Compatibility | Feature checklist is covered               | ✅ / ✖️ |
| Testing                 | Unit tests and pre-existing e2e tests pass | ✅ / ✖️ |
| Internationalization    | <fill this out>                            | ✅ / ✖️ |
| Analytics               | <fill this out>                            | ✅ / ✖️ |
| Accessibility           | Audit performed                            | ✅ / ✖️ |
| Page Experience         | Audit performed                            | ✅ / ✖️ |
| Documentation           | Written                                    | ✅ / ✖️ |
| Storybook               | Samples written in Preact and AMP          | ✅ / ✖️ |

### Feature Checklist

_To be updated as information becomes available._

### Existing attributes
- [ ] `attribute 1`
- [ ] `attribute 2`
- [ ] `attribute 3`

### Actions
- [ ] `action 1`
- [ ] `action 2`
- [ ] `action 3`

### Events
- [ ] `event 1`
- [ ] `event 2`
- [ ] `event 3`

### Analytics Events
- [ ] `analytics event 1`
- [ ] `analytics event 2`
- [ ] `analytics event 3`

### Migration Notes

This component has a requirement of using `amp-ad`. It is possible both of these components might not be migrated.

[Docs](https://amp.dev/documentation/components/amp-sticky-ad/?format=websites)
[Source code](https://github.com/ampproject/amphtml/tree/main/extensions/amp-sticky-ad)
[Playground](https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-sticky-ad) (*this example doesn't appear to work?)

### Open Tasks

_To be updated as information becomes available._

- [ ] Add more stuff here

### Notifications

/cc @ampproject/wg-bento

**Comment by powerivq** [comment]
FYI. We are trying to migrate amp-sticky-ad to amp-ad. You can now serve sticky ads by using amp-ad with attribute `sticky`, and it will include all features in amp-sticky-ad.

**Comment by dethstrobe** [comment]
I like it. Less is more.
