### ISSUE TITLE
Confirm `on` action support multiple events and update docs

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#3783]
`amp-html-format.md` documents `on` attribute and actions. However, it omits the fact that mutliple events can be defined this way via `;` separator. Please confirm this is the case and update the docs.

**Comment by mkhatib** [comment]
haha - will try it, I actually tried `,` but that didn't work, didn't try `;`

**Comment by mkhatib** [comment]
Confirmed. Using `;` as a separator allows listening to multiple events.
