### ISSUE TITLE
[amp-story][amp-story-auto-ads] AdClick event doesn't trigger anymore when an ads is clicked

### ISSUE THREAD

**Issue by dcombe** [ampproject/amphtml#37831]
### Description

Absolutely no AdClick events are being sent since 15-16 February for all stories. Others events seems to be sent well, but not the click.. Which is a key metric.
Our config didn’t change, neither did the stories on our side.

Any idea why this problem suddenly comes up and how to fix it ?
If it can help, I’ve seen that trying to click the CTA of the ads on chrome with the console and the “mobile mode” (iphone SE or iPad Mini) enabled doesn’t work. It does the equivalent of a tap-next instead.
If I emulate the iphone 12 Pro or Pixel 5 instead, it seems to redirect well but doesn’t trigger the AdClick event.
Thanks for your help fixing this, I think I’m not the only one impacted.

### Reproduction Steps

Here is the trigger config used, with ads pointing to a server url.

```
 "storyAdClick": {
      "on": "story-ad-click",
      "request": "ads",
      "extraUrlParams": {
        "eventType": "storyAdClick",
        "cpAdViewTime": "${viewTime}",
        "cpAdClickTime": "${clickTime}",
        "cpAdPosition": "${position}"
      }
    },
```

### AMP Version Affected

2202230359001

**Comment by calebcordry** [comment]
Thanks for reporting. Taking a look.

**Comment by calebcordry** [comment]
Ok so unfortunately there was a bug introduced in Google ad serving where these ads were being treated as invalid AMPHTML creatives. A side effect of this is that these ads start getting served into x-domain iframes, and that breaks the ability for the parent page to know what is happening inside the creative, which causes these triggers not to fire. I created #37832 to explore if we would potentially want to make these triggers work for x-domain creatives. 

Good news is that we identified this bug in  ad serving and merged a fix last week. It should roll out in the next few days and you should see these events recover then.

Even though the page level analytics are broken this should not affect click tracking for the ad network. Please let me know if this is not the case and you are seeing click loss in your e.g. Google Ad Manager dash.

> If it can help, I’ve seen that trying to click the CTA of the ads on chrome with the console and the “mobile mode” (iphone SE or iPad Mini) enabled doesn’t work. It does the equivalent of a tap-next instead.

I have not been able to reproduce this, but I have seen weird bugs in devtools emulation causing similar issues. Unfortunately I do not have the real devices to test, but please let me know if you do and it is broken, I am happy to dig further.

**Comment by dcombe** [comment]
Thanks @calebcordry for having a look. Waiting for the fix to be live. I'll get back to you in 1 week if it still isn't fixed.
For the Chrome devTools, you may be right, I cannot reproduce on my device even if not the same screen size.
