### ISSUE TITLE
Lightbox Feature

### ISSUE THREAD

**Issue by ariopangarih** [ampproject/amphtml#37864]
Hello there, i appreciate the community of AMP here. I want to asks, how to make lightbox auto load when page loaded? can we add js or something code like $(document).ready here? Not found any article tell about auto load lightbox. I'm new with AMP.

Thanks for helping,

**Comment by comewithl** [comment]
这是来自洪俊贤的自动回复邮件。

**Comment by erwinmombay** [comment]
hello, because of AMP's security model we do not allow custom JavaScript

**Comment by comewithl** [comment]
这是来自洪俊贤的自动回复邮件。
