### ISSUE TITLE
Clarify Embed README documentation

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#3788]
Under Embed https://github.com/ampproject/amphtml/blob/master/3p/README.md#embeds, provide an example of developing direct iframe embeds instead of using amp's 3p iframe mechanism for embeds.

"Direct iframe embeds not using our 3p iframe mechanism (used e.g. for ads) are preferred."

This statement can be interpreted incorrectly to suggest using amp-iframe instead of amp-ad.

**Comment by ericlindley-g** [comment]
@jasti:  I'm putting this in the Backlog milestone, but please correct/update as needed

**Comment by jasti** [comment]
Should be a 2 second doc update. @cramforce, if you can quickly look or assign to someone for a quick update here.
