### ISSUE TITLE
[Amp story captions] Render video captions with `amp-story-captions` when in an `amp-story` doc and served from cache

### ISSUE THREAD

**Issue by processprocess** [ampproject/amphtml#37899]
### Description

`video` captions should render with the [`amp-story-captions`](https://amp.dev/documentation/components/amp-story-captions/?format=websites) component when provided from cache and in an `amp-story`.

By default they will:
- Use the "default" style preset added in #37900. 
- Be positioned relative to the video to follow expected default browser captions UX.

Captions [design doc](https://github.com/ampproject/amphtml/issues/34016)

**Comment by swissspidy** [comment]
Does that mean one would not have to manually include `<amp-story-captions>` anymore?

**Comment by processprocess** [comment]
> Does that mean one would not have to manually include `<amp-story-captions>` anymore?

The script wouldn't need to be imported in `head`.

The `amp-story-captions` element would be a child of `amp-video` by default - the publisher could define it manually as a child of `amp-story-page` if they want it in a specific area of the document.

**Comment by processprocess** [comment]
> Does that mean one would not have to manually include `<amp-story-captions>` anymore?

@swissspidy The scope of this work is only for captions provided from cache.
One will need to manually include `<amp-story-captions>` when using them inline. 
Just wanted to update you on this!
