### ISSUE TITLE
🍱 [amp-fx-collection:1.0] Convert amp-fx-collection to Bento

### ISSUE THREAD

**Issue by dethstrobe** [ampproject/amphtml#37946]
## High-Level Requirements

| Consideration           | Ready When                                 | Status  |
| ----------------------- | ------------------------------------------ | ------- |
| Component Compatibility | Feature checklist is covered               | ✅ / ✖️ |
| Testing                 | Unit tests and pre-existing e2e tests pass | ✅ / ✖️ |
| Accessibility           | Audit performed                            | ✅ / ✖️ |
| Page Experience         | Audit performed                            | ✅ / ✖️ |
| Documentation           | Written                                    | ✅ / ✖️ |
| Storybook               | Samples written in Preact and AMP          | ✅ / ✖️ |

## Feature Checklist

_To be updated as information becomes available._

### Existing attributes
- [ ] `parallax-factor`
- [ ] `fx`
- [ ] `duration`
- [ ] `easing`
- [ ] `margin-start`
- [ ] `margin-end`
- [ ] `repeat`
- [ ] `fly-in-distance`

## Migration Notes

We should probably rename it this component when porting it over to bento.

The amp version seem to work as an extra attribute on amp-img, I think we'll want the bento version to be a wrapper element the adds the animations to the child (children?) element.

- [Docs](https://amp.dev/documentation/components/amp-fx-collection/)
- [Example](https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-fx-collection&format=websites&_gl=1*1qjgtfk*_ga*YW1wLWlJNnZDcUVrZnoyVTlubnVkNUpvcFE.)
- [Source Code](https://github.com/ampproject/amphtml/tree/main/extensions/amp-fx-collection)

### Tests
- [ ] Preact unit tests
- [ ] Stand-alone unit tests
- [ ] Preact/react e2e tests
- [ ] Stand-alone e2e tests

### Documentation
- [ ] README

### Storybook
- [ ] Preact Storybook

## Notifications

/cc @ampproject/wg-bento

**Comment by 12csw1** [comment]
Should this issue be labeled as P3: When Possible?

We are doing research about “Issue Priority Prediction". We have developed a tool to automatically label the priority of an issue. The basic idea is to employ Bert model to encode the textual and code descriptions of the issue, and incorporate the issue’s attributes in the model, then apply multi-task learning to facilitate other information boosting the prediction performance.
We have conducted experiments on four GitHub projects with 21700 issues, and results show that [79 accuracy](https://github.com/ampproject/amphtml/issues/37985) can be achieved.

Our tool shows that this issue has a very large possibility to be labeled as P3: When Possible
Could you please tell us whether it should be labeled as P3: When Possible?
And if you have any comments or suggestions with this tool, could you please tell us?
Thank you so much.
