### ISSUE TITLE
Explain Amp Source code

### ISSUE THREAD

**Issue by RoshanTekno** [ampproject/amphtml#37966]
Hi, my name is Roshan. I'm really interested in how the AMP source code works. I know I'm in no position to ask this question. But it will really help if someone could explain it. So sometime in the future, I could also write code like this.
(I know that it's not an issue but I don't know how to contact someone.)

**Comment by jshamble** [comment]
Hi RoshanTekNo,

We have a slack channel, feel free to re-ask this question there
and perhaps someone there will be able to assist you.

https://amphtml.slack.com/messages/C4NVAR0H3/

**Comment by RoshanTekno** [comment]
Thank You
