### ISSUE TITLE
June 27 2016 Meeting Notes

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#3796]
## Google's AMP team weekly notes

2016-06-27
@cramforce
- Fixed regression in resource preloading with `<link rel=preload>` (was blocked by CSP)
- Build prototype for very deep linking. https://github.com/ampproject/amphtml/pull/3790
  - @jridgewell notes that he had to solve a similar question in his Google interview :)
- Build prototype for chunked rendering https://github.com/ampproject/amphtml/pull/3775 
- Implement A2A (AMP-to-AMP) navigation for ALP (AMP landing pages) https://github.com/ampproject/amphtml/pull/3711 
- Experimented with using the sandbox attribute on ad iframes https://github.com/ampproject/amphtml/issues/3759 

@muxin
  - Implemented skeleton code for share tracking extension. More work under way this week.

@ericlindley-g
- Finalizing AMP app install banner design.
- Checking out how third parties could integrate with amp-live-list

@zhouyx
- Release on duty this week.
- Struggling with iOS issue in amp-sticky-ad. Found a solution with `background-color: inherit`

@rudygalfi
- Working on [roadmap](https://www.ampproject.org/roadmap/) update

@mkhatib
- Working on exposing submit events to form support in AMP.
- Building polyfill for form validation and reporting. Currently debugging iOS issue (works in simulator but not device) .

@erwinmombay
- Sent PR for dead code elimination calls `getMode()` https://github.com/ampproject/amphtml/pull/3772 
- Added new live blog demo https://github.com/ampproject/amphtml/pull/3741 

@jridgewell
- Finalizing PR to allow `amp-fx-flying-carpet` collapse if contents turn out to be empty. https://github.com/ampproject/amphtml/pull/3721
- Investigating ServiceWorkers for AMP Cache

@sriramkrish85
- PR ready for amp-carousel based on snap points #3798 
- Next PR will polyfill snap points.

@dvoytenko
- Playing with a VR image component.
- Landed a bunch of PRs regarding PWA support in AMP https://github.com/ampproject/amphtml/issues/3742
- One thing of note is the use of slots (aka insertion points) to progressively enhance AMPs when displayed in a PWA.

misc:
[Erwin’s](https://github.com/erwinmombay) profile image is wonderful.

**Comment by jaygray0919** [comment]
very helpful.
