### ISSUE TITLE
Error: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#3797]
```
at Error (native)
at D (https://cdn.ampproject.org/rtv/001466185787499/v0/amp-accordion-0.1.js:12:287)
at B.buildCallback (https://cdn.ampproject.org/rtv/001466185787499/v0/amp-accordion-0.1.js:10:178)
at amp-accordion.d.build (https://cdn.ampproject.org/r
```

**Comment by zhouyx** [comment]
from `amp-accordion.js` line 102.
   ` try {
      const sessionStr = this.win_./*OK*/sessionStorage.getItem(this.id_);
      return JSON.parse(sessionStr);
    }`

**Comment by erwinmombay** [comment]
@zhouyx can you mark one as dupe and close the other one? we don't need to keep both

**Comment by zhouyx** [comment]
close #3770

**Comment by rudygalfi** [comment]
Putting in Current — assume this is in progress?

**Comment by zhouyx** [comment]
#3813

**Comment by jridgewell** [comment]
Closed by https://github.com/ampproject/amphtml/pull/5968.
