### ISSUE TITLE
Update AMP Validator to understand amp-ad as an extension

### ISSUE THREAD

**Issue by amans1690** [ampproject/amphtml#3802]
## Short description of your issue:
AMP Validator reporting Issue on `<script src="https://cdn.ampproject.org/v0/amp-ad-0.1.js" custom-element="amp-ad" async></script>`

The error message as reported by AMP Validator is 

> The tag 'script' is disallowed except in specific forms

.

## How do we reproduce the issue?
URL: http://m.timesofindia.com/amp_articleshow_test/52948167.cms#development=1
See the console tab in developer tools in chrome

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1466185787499

**Comment by Gregable** [comment]
I can't access the URL, but I suspect what is going on is that you have this tag in your HTML body, either explicitly, or by including a tag not allowed in the head before including this tag.

**Comment by amans1690** [comment]
@Gregable You can open the url on chrome 
1. for opening the url you have to first set the user agent in chrome dev tools to iphone4 or nexus4/5
2. Then try to access the url

I have already looked to the advice provided by in the previous issues but that wasn't the issue here. Please look into this.

FYI: I have included the `<script src="https://cdn.ampproject.org/v0/amp-ad-0.1.js" custom-element="amp-ad" async></script>` in the head. 
If I remove this piece of code the AMP Validator successfully validates the amp document.

**Comment by Gregable** [comment]
Ah, yes. The validator doesn't know about the amp ad extension. In the past, the code was built into the main runtime, but it appears that it was refactored recently into a separate file (https://github.com/ampproject/amphtml/pull/2902).

As a temporary workaround, removing the `<script src="https://cdn.ampproject.org/v0/amp-ad-0.1.js" custom-element="amp-ad" async></script>` for now should work. It would appear that the runtime will late load the extension anyway.

**Comment by Gregable** [comment]
This has been fixed in github, but not yet rolled out.

**Comment by weeblr** [comment]
Hi @Gregable 

Any estimate on when this should be rolled out? We are about to release a new version of our AMP extension (for Joomla) and would like to know if we should or should not include the ad script.

Cheers

**Comment by Gregable** [comment]
This is live in the AMP cache and Google search already and will rollout to the javascript validation (which is only for debugging) in an hour or two.

**Comment by weeblr** [comment]
Thanks. This is working now as expected.
