### ISSUE TITLE
AMP compatible code for Google Analytics 4

### ISSUE THREAD

**Issue by 99coder99** [ampproject/amphtml#38022]
### Description

The launch of Google Analytics 4 is becoming extremely problematic to use, and has literally opened a can of worms for site owners/webmasters.  I simply need the standard user tracking for my AMP website, but looks like Google Analytics 4 is not yet compatible with AMP.

For a new AMP (Accelerated Mobile Pages) site, I am trying to use the following tracking code to track the users, and it is making the AMP page non-AMP.

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-X4XX45XXXX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-X4XX45XXXX');
</script>
```

Tried to follow the instruction at https://developers.google.com/analytics/devguides/collection/amp-analytics and at https://stackoverflow.com/questions/69061534/google-analytics-on-amp-story and used the following modified AMP code as suggested:

```
<script async custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>
<amp-analytics type="gtag" data-credentials="include">
<script type="application/json">
{
  "vars" : {
    "gtag_id": "G-X4XX45XXXX",
    "config" : {
      "G-X4XX45XXXX": { "groups": "default" }
    }
  }
}
</script>
</amp-analytics>
```

However, the above modified code is AMP-compatible, but despite several site visits from across the globe no data is getting logged in Google Analytics 4 for me (webmaster) to see. It simply reports "0 visits, 0 users, & 0 everything"

**Is Google Analytics 4 not yet compatible with AMP (a bug)? or is there anything else that I must change in code to make this Analytics 4 code AMP compatible and recording data?**

### Reproduction Steps

Use both the above code snippets in AMP validator.

The first one will report the webpage as "Not an AMP page"

The second one will report "AMP page is valid" but nothing will get logged in the Google Analytics 4  portal for me (webmaster) to see. It simply reports "0 visits, 0 users, & 0 everything"

### OS(s) Affected

All

### Device(s) Affected

All

**Comment by swissspidy** [comment]
> Is Google Analytics 4 not yet compatible with AMP

Correct. Please see & follow #24621 for any updates.

**Comment by erwinmombay** [comment]
Closing this as GA4 integration is now supported. Let us know if you encounter any bugs
