### ISSUE TITLE
amp-facebook has a minimum-width of 350px, causing overflow issues on small devices

### ISSUE THREAD

**Issue by RossMcMillan92** [ampproject/amphtml#3803]
## Short description of your issue:

Text posts in an amp-facebook tag have a minimum-width of 350px applied to the iframe, causing overflow issues on small devices. This is regardless of what you manually set as the width on the amp-facebook tag.

## How do we reproduce the issue?

Visit the amp-facebook by example page and resize the browser to 350px and under. Notice MZ's text post is cut off at the side. https://ampbyexample.com/components/amp-facebook/

## What browsers are affected?

Devices with widths <350px

## Which AMP version is affected?

Current amp-facebook version (v0.1)

**Comment by mkhatib** [comment]
This is an issue with FB embeds limitations - the minimum width an embedded post can be rendered in is `350px` - see https://developers.facebook.com/docs/plugins/embedded-posts
