### ISSUE TITLE
amp-story-shopping page attachment wth remote URL page attachment open before shopping data is loaded

### ISSUE THREAD

**Issue by jshamble** [ampproject/amphtml#38040]
### Description

Expected: shopping data will load properly regardless if the page attachment opens first or not.

### Reproduction Steps

Intermittent bug: Open page attachment with a remote URL, then refresh the page while the page attachment is still open

**Comment by processprocess** [comment]
Please add logs to bug reports. 
<img width="1517" alt="Screen Shot 2022-04-08 at 9 31 36 AM" src="https://user-images.githubusercontent.com/3860311/162457263-8c66b5d9-3cc2-4aa2-8b0b-3270085f8f94.png">
