### ISSUE TITLE
404 images fail to terminate loading animation

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#3806]
See 
E.g. https://cdn.ampproject.org/c/s/www.yahoo.com/amphtml/style/uh-oh-did-luke-skywater-203831242.html
that has a bunch of images that 404 and continue to show the 3 dots. it should be clearly communicated to the user that something went wrong. I think just showing the default broken image is fine.

**Comment by jasti** [comment]
Same as #2585?

**Comment by erwinmombay** [comment]
@jasti yes. looking into this too since high priority
