### ISSUE TITLE
[amp-story-shopping] Make call to action case consistent

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#38082]
### Description

The current CTA text is `Shop Now` while the `amp-story-outlink` and `amp-story-attachment` CTAs are `Swipe up`.

Ideally `Shop Now` is renamed to `Shop now`

### Reproduction Steps

Add a shopping tag to a page

**Comment by processprocess** [comment]
Thanks for catching this @cpauwels :)

**Comment by 12csw1** [comment]
Should this issue be labeled as P3: When Possible?

We are doing research about “Issue Priority Prediction". We have developed a tool to automatically label the priority of an issue. The basic idea is to employ Bert model to encode the textual and code descriptions of the issue, and incorporate the issue’s attributes in the model, then apply multi-task learning to facilitate other information boosting the prediction performance. 
 We have conducted experiments on four GitHub projects with 21700 issues, and results show that [79 accuracy]() can be achieved.

Our tool shows that this issue has a very large possibility to be labeled as P3: When Possible 
Could you please tell us whether it should be labeled as P3: When Possible?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.
