### ISSUE TITLE
[amp-story-shopping] Allow for a dark theme

### ISSUE THREAD

**Issue by cpauwels** [ampproject/amphtml#38081]
### Description

Similar to the `amp-story-outlink` and `amp-story-attachment`, allow for setting an optional `theme="dark"` attribute.

### Alternatives Considered

None possible right now

**Comment by swissspidy** [comment]
I thought this already works? Or is only in validator spec but not functional yet?

https://github.com/ampproject/amphtml/blob/4a440b6a1cf00ae547b7519b6c6c4b0d2115c722/extensions/amp-story-shopping/validator-amp-story-shopping.protoascii#L39-L43

**Comment by cpauwels** [comment]
My bad, it is indeed already implemented!
