### ISSUE TITLE
Find a better animation for "Skip" button to show up

### ISSUE THREAD

**Issue by ychsieh** [ampproject/amphtml#38112]
### Description

![demo](https://user-images.githubusercontent.com/1697814/163591812-71ee4544-5ab9-44d7-89d4-c5699183d474.gif)
Quoted from comment in #38102: "As a rule, motion needs to inform UX. Fading in opacity does not inform anything other than bringing the eye to the button. Ideally this would give a sense of direction to relate to the moving of the story."

Demo link: https://amp-paywall-demo.web.app/examples/amp-story-subscriptions/amp-story-subscriptions-player.html

### Alternatives Considered

n/a

**Comment by processprocess** [comment]
I'm thinking something super simple like this:
- ease-out the motion curve
- translate the text and arrow subtly on the x axis

https://user-images.githubusercontent.com/3860311/164278451-908a1e8d-b2a6-4e3b-b1a2-69f93f0dea42.mp4
