### ISSUE TITLE
Fix Viewability for amp-fx-flying-carpet component

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#3812]
The problem with the current amp-fx-flying-carpet is that the viewability reported is that of the container and not the ad inside the container. 
CC @jridgewell @kashyapnitin

**Comment by rudygalfi** [comment]
Is this blocking to fix before amp-fx-flying-carpet goes out of experimental?

**Comment by jasti** [comment]
No, not blocking on beta. Technically it's not a bug and a FR because this format on non-AMP pages don't really report on viewability either.

**Comment by jasti** [comment]
Hey @jridgewell, is this one still on your radar for the current milestone? It sounds like some pubs want to use it for direct sold inventory.

**Comment by jridgewell** [comment]
This is pending https://github.com/ampproject/amphtml/pull/4307 for now. Once that's in, I can update our IntersectionObserver code pretty easily.

**Comment by jasti** [comment]
@jridgewell Can you please confirm that this is fully done?
