### ISSUE TITLE
Provide state-storage opt-out for amp-accordion

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#3813]
Provide attribute to opt out of preserving state of `amp-accordion`— currently collapsed/expanded state is preserved as the session level

Addresses issue identified in #3298

**Comment by zhouyx** [comment]
need the change for validator. #6368

**Comment by KosIsland** [comment]
Up to now the disable-session-states attibute does not work at my page. Which update may be necessary?

**Comment by camelburrito** [comment]
@KosIsland - right now the attribute is experimental, this will soon be made available for use without experiments.

**Comment by zhouyx** [comment]
Code live in PROD. @KosIsland let me know if it still doesn't work.

**Comment by KosIsland** [comment]
@zhouyx: Up to now it is working without any problem. Thank you for your help.
