### ISSUE TITLE
Error logs showing in ws console

### ISSUE THREAD

**Issue by emilrueh** [ampproject/amphtml#38140]
### Description

The below errors are showing when we click on a web story - see example 

amp-story.js:1157 Uncaught TypeError: Cannot read properties of null (reading 'next')
at As.pe (amp-story.js:1157:12)
at As.Vst (amp-story.js:1239:12)
at amp-story.js:651:12
at page-advancement.js:200:7
at Array.forEach ()
at Ko.onTapNavigation (page-advancement.js:199:34)
at Ko.pit (page-advancement.js:698:10)
pe @ amp-story.js:1157
Vst @ amp-story.js:1239
(anonymous) @ amp-story.js:651
(anonymous) @ page-advancement.js:200
onTapNavigation @ page-advancement.js:199
pit @ page-advancement.js:698
index.js:43 Uncaught (in promise) Error: No messaging channel: initMessagingChannel timeout
at l (index.js:43:13)
at _t.createError (log.js:295:45)
at timer-impl.js:130:23
at timer-impl.js:71:9
l @ index.js:43
createError @ log.js:295
(anonymous) @ timer-impl.js:130
(anonymous) @ timer-impl.js:71
Promise.then (async)
coreServicesAvailable @ performance-impl.js:333
(anonymous) @ amp.js:55
Ci @ chunk.js:190
ji @ chunk.js:409
(anonymous) @ chunk.js:322
postMessage (async)
Qi @ chunk.js:514
Wi @ chunk.js:503
Ki @ chunk.js:368
runForStartup @ chunk.js:357
Un @ chunk.js:59
nu @ amp.js:50
(anonymous) @ amp.js:130
Ci @ chunk.js:190
ji @ chunk.js:409
(anonymous) @ chunk.js:322
postMessage (async)
Qi @ chunk.js:514
Wi @ chunk.js:503
Ki @ chunk.js:368
runForStartup @ chunk.js:357
Un @ chunk.js:59
(anonymous) @ amp.js:117
(anonymous) @ version.js:11

### Reproduction Steps

https://nonfungibleownership.com/currencies/GHST/aavegotchi/

**Comment by DanielCryptoK** [comment]
Is there a date as to when this is going to be fixed as was reported in April and most of my websites pages are effected by this issue.

**Comment by ychsieh** [comment]
Duplicate of #12047.
