### ISSUE TITLE
AMP authorization delay

### ISSUE THREAD

**Issue by rmcorrea** [ampproject/amphtml#38180]
### Description

I'm experiencing a slowness in AMP when requesting the authorizarionUrl endpoint. The AMP HTML version of the content is taking about 20 seconds to request.

The effect of this for users is that they see all the barriers available, and after 20 seconds or so they see the correct barrier.

However, when the correct barrier is mounted, the AMP READER_ID and CLIENT_ID variables are not replaced with their actual values ​​that AMP Engine assembles.

Example of what it looks like in markup: [Markup AMP](https://i.stack.imgur.com/0CPRf.png)

Has anyone seen or is also seeing this problem currently?

### Reproduction Steps

1 - Request the URL: https://www.google.com/amp/s/blogs.oglobo.globo.com/malu-gaspar/post/amp/bolsonaro-provoca-desconforto-no-pl-ao-defender-auditoria-nas-urnas.html

2 - Open the network view and filter by executeAmp

3 - Wait for 20 seconds until the request appears.

### Relevant Logs

```shell
v0.mjs:2 Uncaught Error: No messaging channel: initMessagingChannel timeout
    at o (v0.mjs:2:982)
    at Et.createError (v0.mjs:2:202768)
    at v0.mjs:2:108592
    at v0.mjs:2:108281

error-reporting.js:205 Request channelOpen failed: invalid response from handler
bn @ error-reporting.js:205
(anonymous) @ error-reporting.js:293
messaging.js:452 Uncaught (in promise) Error: Request channelOpen failed: invalid response from handler
    at wt.v (messaging.js:452:11)
    at wt.R (messaging.js:305:12)
    at messaging.js:67:9
v @ messaging.js:452
R @ messaging.js:305
(anonymous) @ messaging.js:67
log.js:232 [AmpAnalytics <unknown id>] Inline or remote config should not overwrite vendor transport settings
```

**Comment by zoolyka** [comment]
I have a similar issue, now it takes ~20 seconds to load the amp-consent banner when a site is loaded from the amp cache. [Test URL.](https://www.google.com/amp/s/amp.prettifyjs.net/) Same errors in the console as above.

**Comment by eNoodle4711** [comment]
Similar issue on our site ([Test Url](https://www.google.com/amp/s/amp.netzwelt.de/news/189105-google-io-so-verfolgt-entwicklerkonferenz-live-stream.html)).

```
error-reporting.js:205: fetch entitlements failed for subscribe.google.com: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.​​​

index.js:13 Uncaught (in promise) Error: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
    at swg.js:17732:23
    at new Promise (<anonymous>)
    at Object.get (swg.js:17729:27)
    at Object.fetchEntitlementsWithCaching_ (swg.js:11854:21)
    at Object.getEntitlementsFlow_ (swg.js:11841:17)
    at Object.getEntitlements (swg.js:11636:36)
    at Ki.J8.constructor.getEntitlements (swg.js:18213:8)
    at amp-subscriptions-google.js:655:12
    
error-reporting.js:205 Request channelOpen failed: invalid response from handler

error-reporting.js:205 fetch entitlements failed for local: timeout​​​
```

resulting in several errors for initMesssagingChannel

```
index.js:43 Uncaught (in promise) Error: No messaging channel: initMessagingChannel timeout
    at o (index.js:43:13)
    at Et.createError (log.js:295:45)
    at timer-impl.js:130:23
    at timer-impl.js:71:9
```

**Comment by jridgewell** [comment]
Hi all, I'm looking into this now.

**Comment by jridgewell** [comment]
Tracked down the internal change that caused this, fixing and will escalate to rollout as quickly as we can.

**Comment by jridgewell** [comment]
The fix has been pushed.
