### ISSUE TITLE
🐛[AMP STORY SHOPPING] bug when using amp-story-shopping inside <amp-story-player>

### ISSUE THREAD

**Issue by Beethoven** [ampproject/amphtml#38193]
### Description

Using amp-story-shopping inside amp-story-player when trying to swipe the images carousel, the player changes to another Story.

### Reproduction Steps

Open on mobile
https://storiefi.web.app/ 

Open Amp story player
Go to second Story open Product Description Attachment and try to swipe on images carousel

Codepen from @Enriqe (https://codepen.io/maenrique/pen/vYyVjEB)
Change one story to https://wsdemos.uc.r.appspot.com/shopping

https://user-images.githubusercontent.com/81638/168187396-ce956e12-82bd-4fc6-a451-45a117da48c4.mov

**Comment by gmajoulet** [comment]
cc @processprocess @jshamble

**Comment by newmuis** [comment]
Can we disable the viewer swipe events when the page attachment is open (regardless of whether it's the shopping attachment or otherwise)?

**Comment by processprocess** [comment]
> Can we disable the viewer swipe events when the page attachment is open (regardless of whether it's the shopping attachment or otherwise)?

I think that makes sense since users could technically have other carousels in the attachment. Awesome idea. Thanks Jon!
