### ISSUE TITLE
Is it Possible to Prevent Amp use of illegal sites

### ISSUE THREAD

**Issue by alicantrk** [ampproject/amphtml#38200]
### Description

Hello,
I am Alican. I am an engineer who has been working on software security for 16 years. I wanted to share with you some of my thoughts.

Nowadays, I see some illegal sites (phishing, gambling, drugs, stream hate-violent contents etc.) that use AMP to hide themselves against possible IP penalties and blocks.

When I did research to report these sites that use Amp for their malicious purposes and what can be done to prevent this use, I couldn't find what I looking for. Search engines have some pages for spam report but this complaint only serves to remove the index.

What I am looking for is to somehow prevent these illegal sites from using AMP.  I think this is a need for some worst case scenarios. I would like to know your ideas too. If you want to review, I can send you some sample sites. Thanks all.

### Alternatives Considered

If you create a mail address like report@.. It can be useful.

**Comment by newmuis** [comment]
This is outside of the scope of the AMP JavaScript library, which is what is maintained in this repository.
