### ISSUE TITLE
Video on first page freezes on the poster

### ISSUE THREAD

**Issue by llccrr** [ampproject/amphtml#38227]
### Description

Video without cache="google" freezing on the first page of the Story, in the link in the Reproduction Steps the poster is a blackscreen. 

### Reproduction Steps

[https://join-test.my.join-stories.com/aa-xkts0Tq/#visibilityState=prerender&origin=https%3A%2F%2F[…].app&showStoryUrlInfo=0&storyPlayer=v0&cap=swipe](https://join-test.my.join-stories.com/aa-xkts0Tq/#visibilityState=prerender&origin=https%3A%2F%2Fij8gcr.csb.app&showStoryUrlInfo=0&storyPlayer=v0&cap=swipe)

https://vnz5b6.csb.app/

**Comment by mszylkowski** [comment]
I think the link is broken with the [...], it should be https://join-test.my.join-stories.com/aa-xkts0Tq/#visibilityState=prerender&cap=swipe

**Comment by mszylkowski** [comment]
More info: Story starts in prerender mode, you can render it by clicking on the left side of the story. The video should play but doesn't, and even when you advance to the next page and come back, the video still doesn't play (it errors). The back navigation to the first page also blocks in a weird way, and sometimes the sources inside the video get removed. I've also seen some sources not added to the `<video>` tag from `<amp-video>`, even though they should be moved inside the `<video>`

**Comment by coreymasanto** [comment]
> Story starts in prerender mode, you can render it by clicking on the left side of the story. The video should play but doesn't, and even when you advance to the next page and come back, the video still doesn't play (it errors).

I was able to repro this issue on a local server, though the behavior is inconsistent for me (sometimes tapping the left side of the story causes me to advance to the next page). The console error that I see is "layoutComplete race" which is thrown in resource.layoutComplete_() [here](https://github.com/ampproject/amphtml/blob/e2f9546e2689785f0d9b4ba72e61759323c45bef/src/service/resource.js#L916-L919).

Note that, although I also see a "Cannot play unregistered element" media-pool assertion error, I also see this error at times when the first page's video does play. The "layoutComplete race" error is the one that is logged when the video on the first page does not play.

**Comment by coreymasanto** [comment]
We suspected that [this PR](https://github.com/ampproject/amphtml/pull/38149) was responsible because of its video and media pool changes, but I'm still able to repro the same errors in my previous comment after reverting the PR (via `git revert 3fe2ae4108e8ce4355c90640458d13cf81af160c`). Additionally, most of the PR's changes require the story to be in the preview state, so it seems less likely to have caused a prerender issue

**Comment by llccrr** [comment]
II noticed the PR you were talking about has been merged 17 days old, we were already having the bug around April 25 if it can help

**Comment by mszylkowski** [comment]
I've noticed that what happens is that the first video on prerender mode sometimes won't send the signal `video.signals().signal('load-end')` but when done manually, the `waitForPlaybackMediaLayout_` call resolves properly, registering the videos on the mediapool and playing them properly (mediapool replaces the sources and everything works correctly). However, if the `LOAD_END` signal is not sent, the video doesn't get registered into the mediapool so it fails to play: `Cannot play unregistered element`

This means that the issue so far is that the first video does not send the LOAD_END signal after `layoutCallback` even though it should (layoutCallback seems to complete and resolve). I'm investigating why this might happen.

**Comment by mszylkowski** [comment]
I found a way to fix this but I'll post tomorrow the context.

On:

https://github.com/gmajoulet/amphtml/blob/55d83c93fd8a9d7757c3cf12700117e7ce0f4689/extensions/amp-story/1.0/amp-story.css#L376-L382

we can replace it with

`amp-story-page:not(.i-amphtml-layout) amp-video.i-amphtml-poolbound:not(.i-amphtml-layout)` (add the last `:not`) so that we don't interrupt the layoutCallback if it was already in motion. This will prevent `unmount` from being called.

**Comment by llccrr** [comment]
There is another bug with videos which is a bit different, it is also only appearing on iOS or Safari. 
The video is freezing on the first frame of the video, it seems different from the bug where the video is freezing on the poster image. 
With our Stories, one bug leads to a black screen whereas the other leads to a freeze after some milliseconds of playing
Have you noticed the difference between the two ?

**Comment by mszylkowski** [comment]
> There is another bug with videos which is a bit different, it is also only appearing on MacOS Safari.

Doesn't seem to be similar to this bug (and I haven't seen it before), can you file a new issue?

**Comment by llccrr** [comment]
New issue there : https://github.com/ampproject/amphtml/issues/37523
I mapped it a long time ago, it was happening in the AmpStory Player, but now it also occurs in our custom Player so I edited the issue.
