### ISSUE TITLE
🌸 Cherry-pick request for #38232 into Beta

### ISSUE THREAD

**Issue by mszylkowski** [ampproject/amphtml#38233]
### Issue (P0 Bug)

38231

### Pull Request(s)

#38232

### AMP Version(s)

2205191749000

### Channels

Beta / Experimental

### Formats

Stories

### Justification

The bug affects the performance of videos greatly by making videos try to download 4 sources that won't play (and each video must fail before the next one is tried). Also the video hosting costs of publishers would increase.

### Verification Steps

https://inline-preview.web.app/ fails to load cached sources. Check the Network tab, all the videos from the Google cache fail to play due to CORS.

### Notifications

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by jridgewell** [comment]
Approved

**Comment by mszylkowski** [comment]
The bug didn't make it to beta, closing this CP
