### ISSUE TITLE
AMP module build giving amp errors.

### ISSUE THREAD

**Issue by cw-rimal** [ampproject/amphtml#38243]
### Description

Amp validator gives following errors after including module scripts from https://github.com/ampproject/amphtml/blob/main/docs/amp-module-build.md and removing old script for v0.js:
`Custom JavaScript is not allowed.` for the included v0.mjs
And
`The tag 'amphtml javascript runtime (v0.js)' is missing or incorrect, but required by 'amp-img'`

### Reproduction Steps

Just trying out on local. Not hosted anywhere, we can host it in our staging environment if required.

**Comment by honeybadgerdontcare** [comment]
@cw-rimal Could you provide a reduced source code that emulates the issue you're facing?

**Comment by erwinmombay** [comment]
Closing as stale. feel free to re-open if you have additional information
