### ISSUE TITLE
remove `no-auth-in-prerender` flags and switches

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#3824]

**Comment by erwinmombay** [comment]
@dvoytenko can we unflag this?

**Comment by erwinmombay** [comment]
confirmed this can be removed, since we've forced this to be on

**Comment by dvoytenko** [comment]
Can be cleaned up, yes.

**Comment by jridgewell** [comment]
Ha, he [already removed](https://github.com/ampproject/amphtml/pull/5175) them.
