### ISSUE TITLE
Amp-form input submission containing semicolon is truncated in Gmail

### ISSUE THREAD

**Issue by princesslafayette** [ampproject/amphtml#38241]
### Description

There's an issue with submitting amp-forms from Gmail, where if an input within the form containing a semicolon is submitted, the form-data received from the Gmail Proxy is improperly formatted. The cause of the issue could be that form-data which is originally sent as `multipart/form-data` is converted by the Gmail proxy to` application/x-www-form-urlencoded` (see comments [here](https://github.com/ampproject/amphtml/issues/31612#issuecomment-1124365955) for more context). This issue only appears when the form is submitted through Gmail, as when the form specified below is submitted from the Gmail AMP for Email Playground, the form-data is is formatted correctly. Additionally I experienced this issue when parsing the form data via a server written in Go using the[ parseForm](https://pkg.go.dev/net/http#Request.ParseForm) standard library method.

### Reproduction Steps

1. Navigate to the [Gmail AMP for Email Playground](https://amp.gmail.dev/playground/). 
2. Add the following code to the playground. The form should render without validation errors as shown in the attached screenshot.

```
<!doctype html>
<html ⚡4email data-css-strict>
<head>
  <meta charset="utf-8">
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js" async></script>
  <style amp4email-boilerplate>body{visibility:hidden}</style>
</head>
<body>

<form method="post"
    action-xhr="https://ptsv2.com/t/ilxad-1653598305/post">
  <fieldset>
  <div>Type something below with a semicolon</div>
  <input type="text"
          name="name"
          required>
    <input type="submit"
        value="Submit" />
    </fieldset>
  </form>
</body>
</html>
```

3. Modify the address in`action-xhr`to POST to an endpoint of your choosing or leave the the address as is and see the results come through at this publicly-viewable [bin](http://ptsv2.com/t/ilxad-1653598305). Send the form as an email to yourself.
4. Open the form in Gmail and add text containing a semicolon to the input (eg. "this;has;semicolons") and click submit

**Expected** form data (this was sent from the playground) (seen [here](http://ptsv2.com/t/ilxad-1653598305/d/5665860521820160/json)):
`"FormValues":{"__amp_source_origin":["amp@gmail.dev"],"name":["this;has;semicolons"]}`

**Actual** (this was sent from Gmail) (view full log [here] or below (http://ptsv2.com/t/ilxad-1653598305/d/6156181303197696/json)): 
![gmail-amp-playgound](https://user-images.githubusercontent.com/88408744/170593611-acffe44a-f4c1-456e-8d98-b4b2ed0b19fa.png)

`"FormValues":{"__amp_source_origin":["amp@gmail.dev"],"has":[""],"name":["this"],"semicolons":[""]}`

### Relevant Logs

```shell
{"Timestamp":"2022-05-26T22:55:51.990311Z","Method":"POST","RemoteAddr":"127.0.0.1:23193","ID":6156181303197696,"Headers":{"Accept":["application/json"],"Accept-Encoding":["gzip, deflate, br"],"Amp-Email-Sender":["amp@gmail.dev"],"Amp4email-Proxy-Assertion":["eyJhbGciOiJSUzI1NiIsImtpZCI6ImRhZDIxM2QyOGI0MGMzMWQ4ZjQwNzBkM2RlNjE1NWEyMzA2MGE2MjkiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9nbWFpbC9hbXAvYW1wQGdtYWlsLmRldiIsImV4cCI6MTY1MzYwNzU4MSwiaWF0IjoxNjUzNjAzOTgxLCJpc3MiOiJnbWFpbEBzeXN0ZW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsInRhcmdldF9hdWRpZW5jZSI6Imh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL2dtYWlsL2FtcC9hbXBAZ21haWwuZGV2In0.KaGDUW661dE9keWQpy9zrCwh4z2GmEQOqP7RP5NL9nKL4UN9bVJF2Xrunlc-kq6t3oTNyBQdY1cXcOA1eGMnDxEHqRJgFXb0s6fhPuZKTFr1jiwitmOYPCrvOeiIJMgKt9uVipOT5qP-kDT2GgXFxTyVeg639YsuS_K5JBlk83OcUF_rmDx5ggzRBYueLiXWVRy1yiZHKwFINL-0DqvhUNLOcE2QbKY6DX3vWS5yn56k3OlC6uZ1UBbBMy5U4lzCmCEWAbJkEcfSqnSAu0GE23szoHSQ2chGcbfcHChDhNGWGMUoo3-Fst3aGevZX6WQliS3GQtwhPdJOSDWq6NGUA"],"Content-Length":["24"],"Content-Type":["application/x-www-form-urlencoded;charset=utf-8"],"Forwarded":["for=\"66.249.84.159\";proto=https"],"Origin":["https://mail.google.com"],"Traceparent":["00-f78ab763c7b8ec84a976911258f3e3cc-c459c35960344895-00"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/1.0 (KHTML, like Gecko; Gmail Actions)"],"X-Cloud-Trace-Context":["f78ab763c7b8ec84a976911258f3e3cc/14148554492994668693"],"X-Forwarded-For":["66.249.84.159, 169.254.1.1"],"X-Forwarded-Proto":["https"],"X-Google-Apps-Metadata":["domain=gmail.com,host=ptsv2.com"],"X-Google-Serverless-Node-Envoy-Nopod":[""]},"FormValues":{"__amp_source_origin":["amp@gmail.dev"],"has":[""],"name":["this"],"semicolons":[""]},"Body":"","Files":null,"MultipartValues":null}
```

**Comment by zhangsu** [comment]
This definitely looks like a bug in Gmail. I will take a look.

**Comment by zhangsu** [comment]
This should be fixed in Gmail now.

**Comment by princesslafayette** [comment]
> This should be fixed in Gmail now.

Much appreciated!!
