### ISSUE TITLE
Amp not working in latest chrome version getting error 

### ISSUE THREAD

**Issue by truckg2016** [ampproject/amphtml#38279]
### Description

![Screenshot_20220608-224118](https://user-images.githubusercontent.com/86769889/172678721-da35b291-167a-44fa-9aae-86be26cf0609.png)

### Reproduction Steps

Amp input error 

### Relevant Logs

```shell
Amp cached page error
```

### Browser(s) Affected

Chrome

### OS(s) Affected

Android 11

### Device(s) Affected

Motorola, OnePlus all

### AMP Version Affected

No Idea

**Comment by erwinmombay** [comment]
Closing as stale. do open if you are still seeing this issue
