### ISSUE TITLE
Add human-readable name/title attribute to amp-story-page

### ISSUE THREAD

**Issue by danielstockton** [ampproject/amphtml#38298]
### Description

Allow assigning a human-readable name/title to `amp-story-page`. This could make it easier to understand what you're looking at in analytics and also when using the `#page=` hash parameter for branching.

If choosing e.g. `name=` attribute then there should be an equivalent `${storyPageName}` macro and `#pageName=` hash parameter.

### Alternatives Considered

Currently this can be achieved by just using the `id` parameter.
However, we want to give each page a globally unique id and also human readable names may need to contain whitespace.

**Comment by newmuis** [comment]
If the human readable names may need whitespace, wouldn't that make it a poor fit for usage in a URL parameter?  It would need to be URL-encoded, which by definition makes it not human-readable (in my opinion)

**Comment by danielstockton** [comment]
That's a fair argument. What about a slug instead? This would be readable in the URL and allow e.g. `10-things-to-do-in-rome` which starts with a number and is not a valid HTML ID.

In the context of tooling, the aim is not so much to allow whitespace, but resolving the following conflict:

User - wants human readable identifier to appear in analytics
Tool/platform - wants control over the identifier to ensure uniqueness and design an analytics system with predictable performance characteristics

Any solution that allowed the coexistence of a user-defined and platform-defined identifier would be OK (as they have different requirements).

**Comment by mszylkowski** [comment]
> globally unique id and also human readable names

If you have a storyId (that you generate per story as a UUID), you could prepend the page ids with it:
```
story-id = "h712k46b6b7" (which you can enforce could always start with a letter so it's a valid ID)
page-id = "h712k46b6b7-cover-trips"
page-id = "h712k46b6b7-1st-trip-to-paris"
page-id = "h712k46b6b7-2nd-trip-to-rome"
```

**Comment by danielstockton** [comment]
I suppose that could work - we can just take the first 36 chars from the ID for our reporting purposes.
Third party analytics would get the full ID, but it meets the requirement of being human-readable.
