### ISSUE TITLE
Support serving A4A creatives in non-AMP pages 

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#3829]
#3133 AMP Ads for AMP Pages will have great performance for AMP ads in AMP Pages.

Can we get any performance benefits when serving AMP Ads to non-AMP pages?
Placeholder issue to explore.
CC @cramforce @michaelkleber

**Comment by michaelkleber** [comment]
Once we're ready to serve ads in AMP format, we will indeed run experiments with placing them on both AMP and non-AMP pages.

**Comment by lannka** [comment]
This is address in the amp-inabox project #5700
