### ISSUE TITLE
Switch loading animation from 3 dots to something else

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#3830]
Extensions like amp-img show '3 dots' animation when loading. We could have a better animation. Need UX guidance. This should also apply to all other extensions while loading, as well. 
CC @cramforce if there is more background.
CC @rudygalfi

**Comment by cramforce** [comment]
This is just my taste, but I find the default a bit weak. UX people should chime in.

**Comment by ericlindley-g** [comment]
@cramforce @jasti  — slotting this in Backlog, given this is under discussion, but please correct/update as needed

Adding @edlea-g for UX input

**Comment by aghassemi** [comment]
This is happening and tracked under https://github.com/ampproject/amphtml/issues/20237. Closing as dup
