### ISSUE TITLE
  Documentation for the component `amp-story-page-outlink` is missing

### ISSUE THREAD

**Issue by VeenaYemmiganur** [ampproject/amphtml#38304]
### Description

Please provide the  Documentation for the component `amp-story-page-outlink`

### Alternatives Considered

https://amp.dev/documentation/components/amp-story-page-outlink/

**Comment by newmuis** [comment]
The link that you've provided appears to work correctly; is there something that I'm missing?

**Comment by VeenaYemmiganur** [comment]
@newmuis documentation for `amp-story-page-outlink` was missing earlier , now I see the page. 
Thank you for the response.
