### ISSUE TITLE
<amp-story> Does not use passive listeners to improve scrolling performance (Lighthouse audit failed)

### ISSUE THREAD

**Issue by dougrhis** [ampproject/amphtml#38326]
### Description

Erro on audit

![image](https://user-images.githubusercontent.com/9891463/176732193-b4f2db34-e32d-4822-9c28-a9dd8a509587.png)

### Reproduction Steps

https://pagespeed.web.dev/report?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fintroduction%2Fstories_in_amp%23amp%3D1

### AMP Version Affected

2206101637000

**Comment by ychsieh** [comment]
[Scrolling is not allowed in stories.](https://github.com/ampproject/amphtml/blob/main/extensions/amp-story/1.0/amp-story.css#L35) So unfortunately this notice would always be there until there's a way for this notice to only show for elements that are scrollable based on CSS configs.
