### ISSUE TITLE
HubSpot blog Post showing amp page with message about domain for sale

### ISSUE THREAD

**Issue by stormhaus** [ampproject/amphtml#38320]
### Description

HubSpot blog Post showing amp page with message about domain for sale.  I disabled AMP in Hubspot to clear it up, but not sure why your URL is resolving that message about:

https://www-groupelite-com.cdn.ampproject.org/c/s/www.groupelite.com/blog/group-elite-awarded-for-verint-salesforce-plugin-and-verint-services-and-support-partner-of-the-year?hs_amp=true

<img width="404" alt="showing website for sale" src="https://user-images.githubusercontent.com/108410718/176445938-2ad1641f-d4ca-42a7-80b3-4a617d500763.png">
e

### Reproduction Steps

HubSpot blog Post showing amp page with message about domain for sale.  I disabled AMP in Hubspot to clear it up, but not sure why your URL is resolving that message about:

https://www-groupelite-com.cdn.ampproject.org/c/s/www.groupelite.com/blog/group-elite-awarded-for-verint-salesforce-plugin-and-verint-services-and-support-partner-of-the-year?hs_amp=true

<img width="404" alt="showing website for sale" src="https://user-images.githubusercontent.com/108410718/176445938-2ad1641f-d4ca-42a7-80b3-4a617d500763.png">
e

**Comment by newmuis** [comment]
Clicking this link does not reproduce the issue for me.  Is there another way to reproduce this?
