### ISSUE TITLE
Prevent links in standalone web apps opening Mobile Safari

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#3835]
The default behavior for iOS web apps in [standalone mode](https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html) to open links in mobile safari and leave the standalone modus. This is unwanted behavior for AMP sites in standalone mode. 
## How do we reproduce the issue?
1. Add https://ampbyexample.com to the homescreen on an iOS device
2. Launch the website from the homescreen 
3. Click on the Github link -> mobile safari opens (expected behavior)
4. Click on a ABE sample link -> mobile safari opens (unwanted behavior - we should stay in the standalone webapp mode)
## Suggestion

Detect iOS standalone mode and open links [via `document.location.href = ...`](https://gist.github.com/kylebarrow/1042026) if within the same domain. 
## Considerations

This might be unwanted behavior. We could make this optional by extracting this into a separate component (e.g. amp-web-app) + introducing an opt-out flag for links.

**Comment by cramforce** [comment]
Do we do anything special with these links right now?

**Comment by mkhatib** [comment]
I don't believe we are. The global document listener is only added on iframe'd documents. These don't look iframe'd. 

We're sure this is not Safari's default behavior with standalone web apps? Will test this out a bit and see what's happening.

**Comment by mkhatib** [comment]
Ok, just created this [jsbin to test this out](https://output.jsbin.com/kufigor/quiet) - try adding it to homescreen and open it from there. It does seem iOS opens links in Safari regardless (tried setting `target=_self` or `target=_top` but it still opens them in Safari when in standalone.

@sebastianbenz do you have an example where this is not happening and instead links are navigated in the standalone page?

**Comment by sebastianbenz** [comment]
This is actually the normal behavior on Safari. The [workaround](https://gist.github.com/kylebarrow/1042026) I've linked is a common approach to solve this problem.

**Comment by PaulKinlan** [comment]
I wrote this a short while ago to handle a lot of the edge cases for what iOS does in standalone mode. https://gist.github.com/PaulKinlan/d66f777f5bde04926f29fc5c7ff345e7

**Comment by mkhatib** [comment]
Ah I see. I totally misread this at first - rereading the issue clarify what you meant. Thanks both! We could definitely use the global click handler in AMP to make sure this happens. Thanks for the links.

@cramforce I think we should do this for sure for same-origin or relative links, let me know what do you think.

**Comment by cramforce** [comment]
SGTM

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)

**Comment by cramforce** [comment]
I suppose we can close in favor of #3861

**Comment by sebastianbenz** [comment]
@cramforce #3861 describes a related but different problem. Both require different fixes.

**Comment by adelinamart** [comment]
@sebastianbenz is this needed? Thanks.

**Comment by sebastianbenz** [comment]
Yes. This is still a problem.
Adelina <notifications@github.com> schrieb am Do. 22. Feb. 2018 um 21:25:
