### ISSUE TITLE
<amp-facebook> not working

### ISSUE THREAD

**Issue by htrex** [ampproject/amphtml#38368]
### Description

Have a look at https://amp.dev/documentation/components/amp-facebook/ with multiple browsers.

For me the only working example is the video embed with Chrome, the other samples are broken.
With Firefox and Edge nothing works.

### Reproduction Steps

open https://amp.dev/documentation/components/amp-facebook/ and notice the blank spaces where content should appear.

### Browser(s) Affected

Chrome, Firefox, Edge

### OS(s) Affected

Ubuntu 22.04, Windows 10, Android 12

**Comment by htrex** [comment]
A few more details about the issue, which doesn't always occur: 
24 hours later on Chrome (Version 103.0.5060.134 Official Build 64-bit, Ubuntu 22.04 + Windows 10) and Firefox (Version 103.0 64bit, Ubuntu 22.04 + Windows 10) the post and video embed work (1st and 2nd sample) while the comment embed doesn't (3rd sample).

**Comment by powerivq** [comment]
`Refused to display 'https://www.facebook.com/' in a frame because it set 'X-Frame-Options' to 'deny'.`

Upgrade to P1 since amp-facebook is completely broken.
