### ISSUE TITLE
Google AMP Viewer URL showing desktop version

### ISSUE THREAD

**Issue by natsl05164** [ampproject/amphtml#38365]
### Description

I have a AMP page that has mobile and desktop version. The mobile version is the 1 that is always cached and shown when using the AMP viewer.  ( https://www.google.com/amp/s/)

But recently, when opening AMP on the AMP viewer , it showing the desktop version .

May i know why this happened ?

### Reproduction Steps

Not able to simulate the issue

**Comment by erwinmombay** [comment]
Closing for now, but if you are reproducible url that we could test with, please re-open the issue
