### ISSUE TITLE
Custom Javascript component in AMP stories

### ISSUE THREAD

**Issue by pravinweb** [ampproject/amphtml#38373]
### Description

Amp documentation shows AMP script is not applicable for amp stories. Simple elements like button can not be used at all places (shows error in amp playground)

There are list of Amp components, but what if developer wants to create custom JavaScript feature or functionality?

For example - I want to create simple content which toggles on click of on/off switch. Also it should auto scroll when user taps on content.

With such restrictions what are the possible ways to create UI rich dynamic AMP stories assuming they are not available in AMP components

### Reproduction Steps

https://amp.dev/documentation/components/amp-script/?format=stories - shows warning Important: this documentation is not applicable to your currently selected format stories!

**Comment by newmuis** [comment]
This is not allowed within AMP's story format.  You may create this, if you like, by creating a story that is not valid AMP (e.g. by simply removing the ⚡ emoji from the HTML tag), but it is not something that is planned to be supported within AMP's story format.

**Comment by pravinweb** [comment]
Thank you @newmuis  for the update

**Comment by newmuis** [comment]
You're welcome!  Feel free to reopen this issue if you have any further comments or questions.
