### ISSUE TITLE
AMP supported email provider

### ISSUE THREAD

**Issue by srikantkota** [ampproject/amphtml#38375]
Hi, I work with Insider (https://useinsider.com). We have recently launched our support for AMP email on our platform. Our platform is currently used by 1000+ brands including companies like Singapore Airlines, CNN, Estee Lauder, Samsung, GAP and more. I wanted to understand the process to get listed in this page https://amp.dev/support/faq/email-support/ as a vendor who supports AMP email. 

Please let me know if there is another channel I need to be reaching out on.

**Comment by bodya244** [comment]
yes there are more channels, they are paid after payment is added there.

Чт, 28 июля 2022 г. в 05:37, srikantkota ***@***.***>:

**Comment by newmuis** [comment]
There is no payment involved.

Let me see what the process is for getting listed on this page, and circle back here.

**Comment by newmuis** [comment]
@srikantkota it looks like you can [file an issue with the appropriate template in the amp.dev repository](https://github.com/ampproject/amp.dev/issues/new?assignees=&labels=Status%3A+Pending+Triage%2C+Type%3A+New&template=tool.md&title=) to request that your tool be listed.

I'll close this issue as I believe this is resolved, but please feel free to reopen if necessary.
