### ISSUE TITLE
🌸 Cherry-pick request for #38383 into 2207281718000

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#38387]
### Issue (P0 Bug)
This is not a P0. but I need this so that i can start the experiment and to have the correct numbers
#38383

### Pull Request(s)

#38383

### AMP Version(s)

2207281718000

### Channels

Beta / Experimental

### Formats

Stories

### Justification

fix a build-system bug that deploys the amp-story-1.0.ssr-css.mjs/js WITH the CSS in it. the new ssr-css files should not have the CSS in them. This build system change turns on the feature for that amp-story binary. 

This also makes it so that the new binaries will be deployed to LTS next week

### Verification Steps

The amp-story-1.0.ssr-css.mjs file should have less bytes than amp-story-1.0.mjs

### Summary

N/A

### Impact

N/A

### Notifications

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by newmuis** [comment]
Approved
