### ISSUE TITLE
amp-timeago Slovenian localization

### ISSUE THREAD

**Issue by ZdejPoham** [ampproject/amphtml#38380]
### Description

For AMP page I'm working on, I need Slovenian localization in amp-timeago.

### Alternatives Considered

I have found no alternatives, as AMP does not allow custom JS.

**Comment by ZdejPoham** [comment]
Can somebody please point me to how can I do this myself since everyone is obviously too busy to bother with this request? I need this feature in less than a month from now.

**Comment by newmuis** [comment]
cc @alanorozco do you know if/how we could enable something like this?  How do the current localizations get shipped?  Does adding new ones mean increasing the bundle size for all pages using `amp-timeago`?

**Comment by ZdejPoham** [comment]
> cc @alanorozco do you know if/how we could enable something like this? How do the current localizations get shipped? Does adding new ones mean increasing the bundle size for all pages using `amp-timeago`?

I'm not against putting localization(s) I need somewhere in head as JSON, as to not affect the bundle size, I just need some pointers on how to do it.

**Comment by ZdejPoham** [comment]
Hello?
Is this project dead, or are some languages just too unimportant for you to even bother?
Why does using big corp. frameworks have to always be such a miserable experience?

**Comment by newmuis** [comment]
We do not currently have any mechanism for publisher-provided strings for a given AMP component.  We would likely need to follow the [process for significant changes](https://github.com/ampproject/amphtml/blob/main/docs/contributing-code.md#process-for-significant-changes) to determine how this could be implemented.

**Comment by ZdejPoham** [comment]
This is bad. So the only solution at the moment would be to include them in
the package, which would negatively impact other users... Is there a way
for me to self-host modified amp-timeago package for my needs?

**Comment by newmuis** [comment]
I believe @mdmower has some documentation on self-hosting AMP: https://github.com/mdmower/amphtml/blob/main/docs/spec/amp-framework-hosting.md

But, as far as I know, because of potential version skew between the binaries, you will need to self-host ALL of AMP, rather than one specific package like `amp-timeago`.

**Comment by ZdejPoham** [comment]
Thank you.
I am working on it.

**Comment by ZdejPoham** [comment]
Did experiment with self-hosted AMP.
Unfortunately it is not suitable for my needs as Google will not index and cache self-hosted AMP pages. I'm giving up on this issue, since it's obvious Slovenian language is unimportant in the greater scheme, and it would be too much hassle to enable/allow custom localizations. I am amazed at how bad this was thought through, especially for a Google backed project.

**Comment by newmuis** [comment]
We are an open development ecosystem, and we try our best to make improvements to the library.  We unfortunately can't prioritize every change in the short term, but the goal would be to help determine the right path forward.

Given that you've determined that self-hosting is not a good fit, we can return to the idea of following the [process for significant changes](https://github.com/ampproject/amphtml/blob/main/docs/contributing-code.md#process-for-significant-changes) to determine how we might allow for localizing strings in `amp-timeago` without increasing bundle size.

There's some precedent for exploring component-specific localization with amp-story, but it's unclear the degree to which that might extend to amp-timeago.

cc @erwinmombay who I think has a little context there.
