### ISSUE TITLE
Improve clarity of swipe affordance for <amp-carousel>

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#3840]
Given the plans to improve amp carousel UX as its own project later on, I favor a short-term stop-gap of just increasing the time that the affordance is shown before hiding it.

@sriramkrish85 currently, how long after coming into view is the arrow shown, before it hides?

**Comment by sriramkrish85** [comment]
The arrows are shown as soon as viewportCallback is triggered i.e as soon as the carousel is in viewport.
From when the arrow is show to when it is hidden - it is 1second (1s css animation on opacity + toggle visibility)

**Comment by ericlindley-g** [comment]
@edlea-g, do you have any opinions here? Tripling the time to 3 seconds seems to be about right, but it would be worth playing a range of values to test, before pushing to prod

**Comment by sriramkrish85** [comment]
Ping! @ericlindley-g @edlea-g

**Comment by ericlindley-g** [comment]
cc'ing @abeck000 for feedback — @sriramkrish85, is it easy for the two of you to run through a few different timings and see what feels right?

**Comment by sriramkrish85** [comment]
yeah, that is easy!
