### ISSUE TITLE
Auto-Advance to The Next Story

### ISSUE THREAD

**Issue by slavakurilyak** [ampproject/amphtml#38412]
### Description

It would be great to see `auto-advance-after-story` (or similar) which specifies when to auto-advance to the next story for a lean-back user experience. This feature request is not the same as the [auto-advance-after](https://amp.dev/documentation/components/amp-story-page/?format=stories#auto-advance-after-[optional]:~:text=the%20URL%20fragment.-,auto%2Dadvance%2Dafter%20%5Boptional%5D,-Specifies%20when%20to) attribute which specifies when to auto-advance to the next page.

My vision is to create a TikTok-like viewing experience that allows for a passive watching experience where one amp story plays after another without user interaction. This encourages viewers to watch one amp story after another without clicking on external links.

### Alternatives Considered

I considered encouraging viewers to click on an external link using [amp-story-page-outlink](https://amp.dev/documentation/components/amp-story-page-outlink/?format=stories).

### Additional Context

One idea worth considering is using the "right arrow" to advance from one story to another.

**Comment by gmajoulet** [comment]
Great suggestion! We actually shipped this feature through Players. If you use the amp-story-player and the last page of your story has an auto advance, the Player should automatically navigate to the next Story.
Hope this helps!

**Comment by newmuis** [comment]
Please feel free to reopen if the resolution above does not address your issue.
