### ISSUE TITLE
amp-sidebar: Allow display of sidebar content based on media query

### ISSUE THREAD

**Issue by pbakaus** [ampproject/amphtml#3842]
Currently, it's not possible to re-use the same markup within the sidebar and show the content on Desktop, then hide it and show it as sidebar on mobile.

This forces us on https://amproject.org/docs to replicate the menu content in two places in the markup.

Would be great to be able to hide/show the sidebar's content based on media queries.

**Comment by ericlindley-g** [comment]
Would be nice to figure out an approach that handles both mobile and desktop well, to avoid this duplication work when the developer wants the sidebar always to be visible. If we enable something like this, we'll also have to consider scrolling behavior (does the sidebar scroll with the rest of the page or not), and will have to disable the transparent scrim (and associated click behavior) over the page content when the sidebar is open.

(putting into the backlog for now)

**Comment by adelinamart** [comment]
@ericlindley-g is this still needed?

**Comment by ericlindley-g** [comment]
Yep—updated w/ priority and put in "New FRs"

**Comment by ericlindley-g** [comment]
I think this is fixed now with the features added to amp-sidebar, but please reopen or make a new bug with specific FRs if not—thanks!
