### ISSUE TITLE
Encountering issues with publisher logo/text attribution 

### ISSUE THREAD

**Issue by coreymasanto** [ampproject/amphtml#38422]
@adamshwa posted the following in https://github.com/ampproject/amphtml/issues/38329#issuecomment-1227355999

> After following these instructions:
> The data will come from the <amp-story>'s metadata attributes in the story's document, as described:
> 1. For the logo: the entity-logo-src attribute (if provided), otherwise the publisher-logo-src attribute.
> 2 .For the string of text: the entity attribute (if provided), otherwise the publisher attribute.
> 3. When the attribution is clicked, it will navigate the user to a URL. This will come from entity-url attribute if provided, otherwise it will use the story's canonical domain.
> 
> It failed to display both logo and text, can you please review if there is bug in the code?
> I tried to debug this area, and it never managed to add anything to src attr, although something was config.
> Even tried to add break points (screenshot) and it skipped them.
>
>
> ![Screen Shot 2022-08-25 at 17 43 39](https://user-images.githubusercontent.com/111682480/186696989-9f56aae8-ba60-446d-a72e-1ca460828de6.png)

**Comment by coreymasanto** [comment]
Hey @adamshwa, sorry to hear about your technical difficulties. I have a couple of question:
1. Do you have a link to this player/story that I could take a look at?
2. With your `maybeBuildAttribution_()` breakpoints, is the `return` statement at line 365 being hit?

**Comment by adamshwa** [comment]
Hi @coreymasanto, thanks for finding time to check this.
1. https://stories.wnba.com/games/19630-21-08-22-Seattle-Storm-vs-Washington-Mystics.html , it may have GEO restrictions, if so try to use US or IL.
2. no, it really to understand why, but 388 being hit without stopping on my breakpoints on 368,372,376 and 382.
I see there is an issue around `this.systemLayerEl_`, it returns null, so the following code fails to find the selector. 
wdyt?

**Comment by coreymasanto** [comment]
> https://stories.wnba.com/games/19630-21-08-22-Seattle-Storm-vs-Washington-Mystics.html

You've correctly specified the `publisher` and `publisher-logo-src` attributes on the `amp-story` element, so the attribution logo & text should be visible when your story is viewed on Google Search and Google Discover. The attribution is not expected to show when your story URL is accessed directly.

Is your concern that the story is not displaying in Search/Discover with the publisher logo & text attribution? If so, then I think that the attribution should already be displaying correctly on these Google surfaces and no further work should be required. @newmuis, please chime in here if I'm incorrect.

**Comment by newmuis** [comment]
Sorry, I've been out of the office for the past few days.

Attribution is intended to show up only in viewers that support the `attribution` feature.  It's unclear to me from this thread exactly which platforms are being targeted, but for the ones that have been mentioned:

- I actually do not believe that Google's viewers typically support this.  As such, you would not see this particular attribution UI element when viewing the story on Google surfaces (though Google does typically render its own attribution UI separately)
- As @coreymasanto mentioned, you will not see this attribution UI when navigating to the story's URL directly.
 
Despite this, there may be other viewers that do support viewing attribution (for example, you can [configure amp-story-player to display attribution](https://github.com/ampproject/amphtml/blob/main/docs/spec/amp-story-player.md#display-story-attribution) if you are using it on your own properties).
