### ISSUE TITLE
Support Dailyhunt Ad Network for web stories

### ISSUE THREAD

**Issue by montu1996** [ampproject/amphtml#38428]
Hello AMP Team,

i'm from dailyhunt team.

We want to support `dailyhunt` ad network for web stories. I go through below links.

https://github.com/ampproject/amphtml/issues/30769
https://amp.dev/documentation/guides-and-tutorials/contribute/adnetwork_integration/#creating-a-fast-fetch-integration
https://github.com/ampproject/amphtml/blob/main/ads/google/a4a/docs/Network-Impl-Guide.md

i did some code change to support but not able to test it in html.

can you please help ?

**Comment by montu1996** [comment]
Hello AMP Team,

Any update ?

**Comment by newmuis** [comment]
cc @ampproject/wg-monetization

**Comment by powerivq** [comment]
@montu1996 It looks like you have the correct documentation. You should be able to run it locally (https://github.com/ampproject/amphtml/blob/main/docs/getting-started-quick.md#test-amp). Does it not work?

**Comment by erwinmombay** [comment]
Closing issue for lack of response. Feel free to re-open if there is any additional information or progress
