### ISSUE TITLE
Redirecting AMP traffic when on desktop or tablet

### ISSUE THREAD

**Issue by mds202** [ampproject/amphtml#38420]
Hello I had a question about AMP and was directed to ask it here.

We've noticed traffic coming to our non-cached amp pages on desktop and tablet directly to the amp url on our website. The traffic is coming from a variety of channels.

We believe our responsive template is a better experience for those users as AMP is for mobile users not desktop/tablet. Would it be okay to identify those users and redirect them to the proper experience? It's the same content but the proper specs for the desktop/tablet experience. When it's a mobile user we would keep them on the appropriate AMP mobile experience.

Thank you.

**Comment by jshamble** [comment]
Please ask this question in the AMP slack channel:

https://amphtml.slack.com/

sign up here:

https://docs.google.com/forms/d/e/1FAIpQLSd83J2IZA6cdR6jPwABGsJE8YL4pkypAbKMGgUZZriU7Qu6Tg/viewform?fbzx=4406980310789882877
