### ISSUE TITLE
MUSM Secondary Application Website

### ISSUE THREAD

**Issue by gracektaylor1** [ampproject/amphtml#38435]
### Description

Good morning, AMP!

      I am facing technical difficulties with the MUSM secondaries website (https://mdapply.mercer.edu/applicant/Home.aspx), which uses AMP. Unfortunately, I am unable to modify, save, or complete my written responses on the secondary application page. In addition, I am unable to submit my application and check the box next to "I certify that the information..." paragraph.

      If I accidentally submitted my application early, this is not an issue, as my application is complete. However, if that is the case, I would love some confirmation.

      I am applying Early Decision, which is due today at 5 pm.
I have reached out to the school to request an extension, but any documentation of these technology issues would help greatly!

      Thank you!
      Grace Taylor
      7069510866
11003820@live.mercer.edu

### Reproduction Steps

https://mdapply.mercer.edu/applicant/Home.aspx

Attempt to modify, save, or complete the written responses on the Secondary Application page. Attempt to submit application and check the box next to "I certify that the information..." paragraph.

These features are not working for me.

### Browser(s) Affected

Chrome

### OS(s) Affected

MacOS High Sierra Version 10.13.6

### Device(s) Affected

MacBook (Retina, 12-inch, 2017)

**Comment by erwinmombay** [comment]
https://mdapply.mercer.edu/security/Login.aspx?ReturnUrl=%2fapplicant%2fHome.aspx does not seem to be an AMP page. closing issue but feel free to re-open if i am  mistaken or if you have additional information
