### ISSUE TITLE
Is there an Amp forum? (Gitter perhaps?)

### ISSUE THREAD

**Issue by SetTrend** [ampproject/amphtml#3845]
Please pardon me for being sort of off-topic (and then, not being off-topic again).

I can't find a link to a forum at https://www.ampproject.org/ nor here where to talk to Google staff to discuss the impact of utilizing AMP on my client's website.

Is there some forum for this?

Do I need to join a Google Hangout session?

**Comment by erwinmombay** [comment]
@SetTrend howdy, take a look at https://github.com/ampproject/amphtml/blob/master/DEVELOPING.md to join our mailing lists and/or join our slack channel.

@rudygalfi should we have a contact us page on the site?

closing this, feel free to open if you have more questions.

**Comment by cramforce** [comment]
https://groups.google.com/forum/#!forum/amphtml-discuss is great for this.

**Comment by SetTrend** [comment]
Thanks for all your valuable ansers.

@cramforce:
I wouldn't want to discuss my issues with users. I'm more interested in Google's point of view on utilizing AMP on commercial sites etc. in regard to ranking. There's some competition relevant issues I need to know about which I wouldn't want to be discussed with users.

**Comment by cramforce** [comment]
Ah, this is not a good place to ask Google related questions as AMP is an
independent project. Google does have a forum for AMP questions
https://goo.gl/utQ1KZ
