### ISSUE TITLE
SwiperJS and amp-img bug on slide

### ISSUE THREAD

**Issue by Jorrit076** [ampproject/amphtml#38472]
### Description

When some slides are out of the view and you swipe to the slides, the amp images won't load to the view. It keeps loading.
You can find a demo here: https://rb-framework-20.webshopapp.com/ 
underneath "Nieuwste producten". 

We use https://swiperjs.com/ for the slider. 

Can I add something to the amp-img to get it to appear on swipe, or can I trigger an event for it to load the image with JS?

### Reproduction Steps

Look at a demo: https://rb-framework-20.webshopapp.com/ underneath "Nieuwste producten"

### Browser(s) Affected

Chrome, Firefox, Safari, Edge, UC Browser

**Comment by newmuis** [comment]
I do not see AMP being used at all on this page -- can you provide a demo that reproduces the issue that you would like to see fixed?

**Comment by newmuis** [comment]
Closing this, as it's not actionable in its current state.  Please feel free to reopen if you have a repro case that shows the issue using both AMP and SwiperJS
