### ISSUE TITLE
Support multiple requests per trigger

### ISSUE THREAD

**Issue by benjamingram** [ampproject/amphtml#3847]
It would be nice to be able to fire multiple requests from a single trigger. One use case is registering a single click trigger as both a "click" and a "conversion".

One way to accomplish this would be to accept an array for the value of the "request" property of the trigger. For simple use cases and backwards compatibility, accepting a string literal should still be supported.

## Original (Still supported)
```javascript
"triggers": {
  "trackPageview": {
    "on": "visible",
    "request": "click"
  }
}
```

## New format (Functionally equivalent to Original)
```javascript
"triggers": {
  "trackPageview": {
    "on": "visible",
    "request": ["click"]
  }
}
```

## New format with multiple requests
```javascript
"triggers": {
  "trackPageview": {
    "on": "visible",
    "request": ["click", "conversion"]
  }
}
```

**Comment by rudygalfi** [comment]
It seems reasonable to me to be able to parse `request` as either a single value or an array of single values.
