### ISSUE TITLE
 Add/enable the poster attribute to the Brightcove plugin

### ISSUE THREAD

**Issue by BC-DavidAguilar** [ampproject/amphtml#38477]
### Description

Poster attribute:
https://amp.dev/documentation/components/amp-video/#poster

I'm looking to have this added, as customers using the BC-AMP plugin would like to be able to replicate the behavior of their non-AMP player where they are able to display the poster image before loading the video's first segment, so they can improve their Largest Contentful Paint.

### Alternatives Considered

None available.

### Additional Context

Brightcove poster API reference:
https://apis.support.brightcove.com/cms/references/cms-api-video-fields-reference.html#images

**Comment by newmuis** [comment]
Can AMP's global placeholder construct serve this purpose?

https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/placeholders/

**Comment by newmuis** [comment]
Closing this in the interim; please reopen if there are examples you'd expect to be served by `poster` that `placeholder` does not cover.

**Comment by BC-DavidAguilar** [comment]
Thank you Newmuis! This will work.

Appreciate it.
