### ISSUE TITLE
Adding email platform

### ISSUE THREAD

**Issue by KatyaKyaro** [ampproject/amphtml#38486]
Hello! 

My name Kyaro Katerina, I'm cross-marketing manager of Sendsay company. Sendsay is an email platform with AMP support. More features you can see on our website https://sendsay.com/ 

Tell me, please, how can we get on this list "Email Platforms and Service Providers" https://amp.dev/support/faq/email-support/ ?
 
Kind regards,

Katerina

**Comment by newmuis** [comment]
You should be able to file an issue [here](https://github.com/ampproject/amp.dev/issues/new?assignees=&labels=Status%3A+Pending+Triage%2C+Type%3A+New&template=tool.md&title=).

Please feel free to reopen this issue if further discussion is warranted.

**Comment by KatyaKyaro** [comment]
we want to get on this Destination https://amp.dev/support/faq/email-support/ 
But I don't see it in Step 4. 
Should I choose 4.1?

**Comment by newmuis** [comment]
Sorry about that.  I would recommend writing this in as an option for step 4.

**Comment by KatyaKyaro** [comment]
Hello! I have filled the form in

**Comment by newmuis** [comment]
Wonderful!  To be clear, we do not actually control what happens there -- this repository is for code changes to the amphtml repository, and is managed by a separate group of people.  You will need to wait for a response on the GitHub issue you've filed in that repository (https://github.com/ampproject/amp.dev/issues/6470).
