### ISSUE TITLE
Duplicated ads displayed in amp-ad with sticky option

### ISSUE THREAD

**Issue by ysfbsf** [ampproject/amphtml#38499]
### Description

`<amp-ad>` is showing duplicated ads when setting the `sticky` parameter. 

<img width="308" alt="image" src="https://user-images.githubusercontent.com/9834101/196071488-750a5e1c-e400-42c9-b1e0-a686bc6a5b28.png">

### Reproduction Steps

[Playground link](https://playground.amp.dev/?format=websites&_gl=1*1r48dg1*_ga*YW1wLXhCRlRmZGNxYWRWbXEtY050TFFZVHc.#share=PCEtLQogICMjIEludHJvZHVjdGlvbgoKICBbYGFtcC1zdGlja3ktYWRgXSgvY29udGVudC9hbXAtZGV2L2RvY3VtZW50YXRpb24vY29tcG9uZW50cy9yZWZlcmVuY2UvYW1wLXN0aWNreS1hZC12MS4wLm1kKSBhZGRzIHN1cHBvcnQgZm9yIGFkIHVuaXRzIHRoYXQgYWx3YXlzIHRha2UgYSBmaXhlZCBwbGFjZSBpbiB0aGUgdmlld3BvcnQgaW4geW91ciBBTVAgSFRNTCBmaWxlcy4KCiAgVGhlIHN0aWNreSBhZCB3aWxsIGFwcGVhciBhdCB0aGUgYm90dG9tIG9mIHRoZSBwYWdlLgogIC0tPjwhLS0gLS0+CjwhZG9jdHlwZSBodG1sPgo8aHRtbCDimqEgbGFuZz0iZW4iPgo8aGVhZD4KPG1ldGEgY2hhcnNldD0idXRmLTgiPgogIDx0aXRsZT5hbXAtc3RpY2t5LWFkPC90aXRsZT4KICA8c2NyaXB0IGFzeW5jIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAuanMiPjwvc2NyaXB0PgogIDwhLS0gIyMgQmFzaWMgdXNhZ2UgLS0+CiAgPCEtLQogICAgSW1wb3J0IHRoZSBgYW1wLXN0aWNreS1hZGAgY29tcG9uZW50IGluIHRoZSBoZWFkZXIuCiAgLS0+CiAgPHNjcmlwdCBhc3luYyBjdXN0b20tZWxlbWVudD0iYW1wLWFkIiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1hZC0wLjEuanMiPjwvc2NyaXB0PgogIDxsaW5rIHJlbD0iY2Fub25pY2FsIiBocmVmPSJodHRwczovL2FtcC5kZXYvZG9jdW1lbnRhdGlvbi9leGFtcGxlcy9jb21wb25lbnRzL2FtcC1zdGlja3ktYWQvaW5kZXguaHRtbCI+CiAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCI+CiAgPHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7LW1vei1hbmltYXRpb246LWFtcC1zdGFydCA4cyBzdGVwcygxLGVuZCkgMHMgMSBub3JtYWwgYm90aDstbXMtYW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGg7YW5pbWF0aW9uOi1hbXAtc3RhcnQgOHMgc3RlcHMoMSxlbmQpIDBzIDEgbm9ybWFsIGJvdGh9QC13ZWJraXQta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUAtbW96LWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW1zLWtleWZyYW1lcyAtYW1wLXN0YXJ0e2Zyb217dmlzaWJpbGl0eTpoaWRkZW59dG97dmlzaWJpbGl0eTp2aXNpYmxlfX1ALW8ta2V5ZnJhbWVzIC1hbXAtc3RhcnR7ZnJvbXt2aXNpYmlsaXR5OmhpZGRlbn10b3t2aXNpYmlsaXR5OnZpc2libGV9fUBrZXlmcmFtZXMgLWFtcC1zdGFydHtmcm9te3Zpc2liaWxpdHk6aGlkZGVufXRve3Zpc2liaWxpdHk6dmlzaWJsZX19PC9zdHlsZT48bm9zY3JpcHQ+PHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT5ib2R5ey13ZWJraXQtYW5pbWF0aW9uOm5vbmU7LW1vei1hbmltYXRpb246bm9uZTstbXMtYW5pbWF0aW9uOm5vbmU7YW5pbWF0aW9uOm5vbmV9PC9zdHlsZT48L25vc2NyaXB0PgogIDxzdHlsZSBhbXAtY3VzdG9tPgogICAgLmFtcC1zdGlja3ktYWQtY2xvc2UtYnV0dG9uIHsKICAgICAgbWluLXdpZHRoOiAwOwogICAgfQogICAgPC9zdHlsZT4KPC9oZWFkPgo8Ym9keT4KICA8IS0tCiAgICBVc2UgYW4gYGFtcC1hZGAgYXMgYSBkaXJlY3QgY2hpbGQgb2YgYGFtcC1zdGlja3ktYWRgLiBUaGUgaGVpZ2h0IG9mIHRoZSBgYW1wLXN0aWNreS1hZGAgd2lsbCBiZSBkZXRlcm1pbmVkIGJhc2VkIG9uIHRoZSBoZWlnaHQgb2YgdGhlIGBhbXAtYWRgIGNoaWxkLgogICAgVGhlIG1heC1oZWlnaHQgb2YgdGhlIHN0aWNreS1hZCBpcyAxMDBweCwgaWYgdGhlIGhlaWdodCBleGNlZWRzIDEwMHB4IHRoZW4gdGhlIGhlaWdodCB3b3VsZCBiZSAxMDBweCBhbmQgb3ZlcmZsb3cgY29udGVudCB3aWxsIGJlIGhpZGRlbi4KICAtLT4KCiAgPGFtcC1hZCBzdGlja3k9InRvcCIgd2lkdGg9IjMyMCIgaGVpZ2h0PSI1MCIgdHlwZT0iZG91YmxlY2xpY2siIGRhdGEtc2xvdD0iLzM1MDk2MzUzL2FtcHRlc3RpbmcvZm9ybWF0cy9zdGlja3kiPgogIDwvYW1wLWFkPgogIDwhLS0KICAgIGBhbXAtc3RpY2t5LWFkYCB3aWxsIGRpc3BsYXkgYWZ0ZXIgc2Nyb2xsIG9uZSB2aWV3cG9ydCBoZWlnaHQgZnJvbSB0b3AgcHJvdmlkZWQgdGhlcmUgaXMgYXQgbGVhc3Qgb25lIG1vcmUgdmlld3BvcnQgb2YgY29udGVudCBhdmFpbGFibGUuCgogICAgW3RpcCB0eXBlPSJub3RlIl0KICAgIFRoZSB0ZXh0IHRoYXQgZm9sbG93cyBpcyBpbnRlbnRpb25hbGx5ICpMb3JlbSBJcHN1bSogdG8gZW5zdXJlIHRoYXQgdGhlcmUgaXMgYW5vdGhlciB2aWV3cG9ydCBmcm9tIHRoZSBmaXJzdCBvbmUgb24gdG9wIHRvIGRlbW9uc3RyYXRlIGBhbXAtc3RpY2t5LWFkYC4KICAgIFsvdGlwXQogIC0tPgoKICAgIExvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0LCBjb25zZWN0ZXR1ciBhZGlwaXNjaW5nIGVsaXQuIER1aXMgdmVuZW5hdGlzLCBtZXR1cyBhIHRyaXN0aXF1ZSBhbGlxdWV0LCBlbmltIG5pYmggZWZmaWNpdHVyIHNlbSwgdXQgaWFjdWxpcyB1cm5hIGp1c3RvIGV1IGRpYW0uIE51bGxhbSBjdXJzdXMgc2FwaWVuIGV0IHNvZGFsZXMgcG9zdWVyZS4gVmVzdGlidWx1bSBhbnRlIGlwc3VtIHByaW1pcyBpbiBmYXVjaWJ1cyBvcmNpIGx1Y3R1cyBldCB1bHRyaWNlcyBwb3N1ZXJlIGN1YmlsaWEgQ3VyYWU7IFN1c3BlbmRpc3NlIHBvdGVudGkuIERvbmVjIHZpdGFlIG9ybmFyZSByaXN1cy4gTWFlY2VuYXMgZWxlaWZlbmQgYW50ZSB2ZWwgZHVpIGxhb3JlZXQsIGV0IHBvcnR0aXRvciBsaWJlcm8gcnV0cnVtLiBOYW0gYXJjdSBtaSwgdWxsYW1jb3JwZXIgYXQgcmlzdXMgZXQsIHB1bHZpbmFyIHVsdHJpY2VzIGVyYXQuIEluIHBlbGxlbnRlc3F1ZSBzZW0gdmVsIHB1cnVzIGF1Y3RvciwgdXQgdmVuZW5hdGlzIHRlbGx1cyB0cmlzdGlxdWUuIFBoYXNlbGx1cyBtb2xlc3RpZSBkaWFtIG9yY2ksIG5lYyBncmF2aWRhIHR1cnBpcyBiaWJlbmR1bSB1dC4gU2VkIHNhZ2l0dGlzIGFsaXF1ZXQgbG9yZW0gc2VkIGRpY3R1bS4KCgogICAgTG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQsIGNvbnNlY3RldHVyIGFkaXBpc2NpbmcgZWxpdC4gRHVpcyB2ZW5lbmF0aXMsIG1ldHVzIGEgdHJpc3RpcXVlIGFsaXF1ZXQsIGVuaW0gbmliaCBlZmZpY2l0dXIgc2VtLCB1dCBpYWN1bGlzIHVybmEganVzdG8gZXUgZGlhbS4gTnVsbGFtIGN1cnN1cyBzYXBpZW4gZXQgc29kYWxlcyBwb3N1ZXJlLiBWZXN0aWJ1bHVtIGFudGUgaXBzdW0gcHJpbWlzIGluIGZhdWNpYnVzIG9yY2kgbHVjdHVzIGV0IHVsdHJpY2VzIHBvc3VlcmUgY3ViaWxpYSBDdXJhZTsgU3VzcGVuZGlzc2UgcG90ZW50aS4gRG9uZWMgdml0YWUgb3JuYXJlIHJpc3VzLiBNYWVjZW5hcyBlbGVpZmVuZCBhbnRlIHZlbCBkdWkgbGFvcmVldCwgZXQgcG9ydHRpdG9yIGxpYmVybyBydXRydW0uIE5hbSBhcmN1IG1pLCB1bGxhbWNvcnBlciBhdCByaXN1cyBldCwgcHVsdmluYXIgdWx0cmljZXMgZXJhdC4gSW4gcGVsbGVudGVzcXVlIHNlbSB2ZWwgcHVydXMgYXVjdG9yLCB1dCB2ZW5lbmF0aXMgdGVsbHVzIHRyaXN0aXF1ZS4gUGhhc2VsbHVzIG1vbGVzdGllIGRpYW0gb3JjaSwgbmVjIGdyYXZpZGEgdHVycGlzIGJpYmVuZHVtIHV0LiBTZWQgc2FnaXR0aXMgYWxpcXVldCBsb3JlbSBzZWQgZGljdHVtLgogCiAgICBMb3JlbSBpcHN1bSBkb2xvciBzaXQgYW1ldCwgY29uc2VjdGV0dXIgYWRpcGlzY2luZyBlbGl0LiBEdWlzIHZlbmVuYXRpcywgbWV0dXMgYSB0cmlzdGlxdWUgYWxpcXVldCwgZW5pbSBuaWJoIGVmZmljaXR1ciBzZW0sIHV0IGlhY3VsaXMgdXJuYSBqdXN0byBldSBkaWFtLiBOdWxsYW0gY3Vyc3VzIHNhcGllbiBldCBzb2RhbGVzIHBvc3VlcmUuIFZlc3RpYnVsdW0gYW50ZSBpcHN1bSBwcmltaXMgaW4gZmF1Y2lidXMgb3JjaSBsdWN0dXMgZXQgdWx0cmljZXMgcG9zdWVyZSBjdWJpbGlhIEN1cmFlOyBTdXNwZW5kaXNzZSBwb3RlbnRpLiBEb25lYyB2aXRhZSBvcm5hcmUgcmlzdXMuIE1hZWNlbmFzIGVsZWlmZW5kIGFudGUgdmVsIGR1aSBsYW9yZWV0LCBldCBwb3J0dGl0b3IgbGliZXJvIHJ1dHJ1bS4gTmFtIGFyY3UgbWksIHVsbGFtY29ycGVyIGF0IHJpc3VzIGV0LCBwdWx2aW5hciB1bHRyaWNlcyBlcmF0LiBJbiBwZWxsZW50ZXNxdWUgc2VtIHZlbCBwdXJ1cyBhdWN0b3IsIHV0IHZlbmVuYXRpcyB0ZWxsdXMgdHJpc3RpcXVlLiBQaGFzZWxsdXMgbW9sZXN0aWUgZGlhbSBvcmNpLCBuZWMgZ3JhdmlkYSB0dXJwaXMgYmliZW5kdW0gdXQuIFNlZCBzYWdpdHRpcyBhbGlxdWV0IGxvcmVtIHNlZCBkaWN0dW0uCgogICAgTG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQsIGNvbnNlY3RldHVyIGFkaXBpc2NpbmcgZWxpdC4gRHVpcyB2ZW5lbmF0aXMsIG1ldHVzIGEgdHJpc3RpcXVlIGFsaXF1ZXQsIGVuaW0gbmliaCBlZmZpY2l0dXIgc2VtLCB1dCBpYWN1bGlzIHVybmEganVzdG8gZXUgZGlhbS4gTnVsbGFtIGN1cnN1cyBzYXBpZW4gZXQgc29kYWxlcyBwb3N1ZXJlLiBWZXN0aWJ1bHVtIGFudGUgaXBzdW0gcHJpbWlzIGluIGZhdWNpYnVzIG9yY2kgbHVjdHVzIGV0IHVsdHJpY2VzIHBvc3VlcmUgY3ViaWxpYSBDdXJhZTsgU3VzcGVuZGlzc2UgcG90ZW50aS4gRG9uZWMgdml0YWUgb3JuYXJlIHJpc3VzLiBNYWVjZW5hcyBlbGVpZmVuZCBhbnRlIHZlbCBkdWkgbGFvcmVldCwgZXQgcG9ydHRpdG9yIGxpYmVybyBydXRydW0uIE5hbSBhcmN1IG1pLCB1bGxhbWNvcnBlciBhdCByaXN1cyBldCwgcHVsdmluYXIgdWx0cmljZXMgZXJhdC4gSW4gcGVsbGVudGVzcXVlIHNlbSB2ZWwgcHVydXMgYXVjdG9yLCB1dCB2ZW5lbmF0aXMgdGVsbHVzIHRyaXN0aXF1ZS4gUGhhc2VsbHVzIG1vbGVzdGllIGRpYW0gb3JjaSwgbmVjIGdyYXZpZGEgdHVycGlzIGJpYmVuZHVtIHV0LiBTZWQgc2FnaXR0aXMgYWxpcXVldCBsb3JlbSBzZWQgZGljdHVtLgoKICAgIExvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0LCBjb25zZWN0ZXR1ciBhZGlwaXNjaW5nIGVsaXQuIER1aXMgdmVuZW5hdGlzLCBtZXR1cyBhIHRyaXN0aXF1ZSBhbGlxdWV0LCBlbmltIG5pYmggZWZmaWNpdHVyIHNlbSwgdXQgaWFjdWxpcyB1cm5hIGp1c3RvIGV1IGRpYW0uIE51bGxhbSBjdXJzdXMgc2FwaWVuIGV0IHNvZGFsZXMgcG9zdWVyZS4gVmVzdGlidWx1bSBhbnRlIGlwc3VtIHByaW1pcyBpbiBmYXVjaWJ1cyBvcmNpIGx1Y3R1cyBldCB1bHRyaWNlcyBwb3N1ZXJlIGN1YmlsaWEgQ3VyYWU7IFN1c3BlbmRpc3NlIHBvdGVudGkuIERvbmVjIHZpdGFlIG9ybmFyZSByaXN1cy4gTWFlY2VuYXMgZWxlaWZlbmQgYW50ZSB2ZWwgZHVpIGxhb3JlZXQsIGV0IHBvcnR0aXRvciBsaWJlcm8gcnV0cnVtLiBOYW0gYXJjdSBtaSwgdWxsYW1jb3JwZXIgYXQgcmlzdXMgZXQsIHB1bHZpbmFyIHVsdHJpY2VzIGVyYXQuIEluIHBlbGxlbnRlc3F1ZSBzZW0gdmVsIHB1cnVzIGF1Y3RvciwgdXQgdmVuZW5hdGlzIHRlbGx1cyB0cmlzdGlxdWUuIFBoYXNlbGx1cyBtb2xlc3RpZSBkaWFtIG9yY2ksIG5lYyBncmF2aWRhIHR1cnBpcyBiaWJlbmR1bSB1dC4gU2VkIHNhZ2l0dGlzIGFsaXF1ZXQgbG9yZW0gc2VkIGRpY3R1bS4KIAogICAgTG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQsIGNvbnNlY3RldHVyIGFkaXBpc2NpbmcgZWxpdC4gRHVpcyB2ZW5lbmF0aXMsIG1ldHVzIGEgdHJpc3RpcXVlIGFsaXF1ZXQsIGVuaW0gbmliaCBlZmZpY2l0dXIgc2VtLCB1dCBpYWN1bGlzIHVybmEganVzdG8gZXUgZGlhbS4gTnVsbGFtIGN1cnN1cyBzYXBpZW4gZXQgc29kYWxlcyBwb3N1ZXJlLiBWZXN0aWJ1bHVtIGFudGUgaXBzdW0gcHJpbWlzIGluIGZhdWNpYnVzIG9yY2kgbHVjdHVzIGV0IHVsdHJpY2VzIHBvc3VlcmUgY3ViaWxpYSBDdXJhZTsgU3VzcGVuZGlzc2UgcG90ZW50aS4gRG9uZWMgdml0YWUgb3JuYXJlIHJpc3VzLiBNYWVjZW5hcyBlbGVpZmVuZCBhbnRlIHZlbCBkdWkgbGFvcmVldCwgZXQgcG9ydHRpdG9yIGxpYmVybyBydXRydW0uIE5hbSBhcmN1IG1pLCB1bGxhbWNvcnBlciBhdCByaXN1cyBldCwgcHVsdmluYXIgdWx0cmljZXMgZXJhdC4gSW4gcGVsbGVudGVzcXVlIHNlbSB2ZWwgcHVydXMgYXVjdG9yLCB1dCB2ZW5lbmF0aXMgdGVsbHVzIHRyaXN0aXF1ZS4gUGhhc2VsbHVzIG1vbGVzdGllIGRpYW0gb3JjaSwgbmVjIGdyYXZpZGEgdHVycGlzIGJpYmVuZHVtIHV0LiBTZWQgc2FnaXR0aXMgYWxpcXVldCBsb3JlbSBzZWQgZGljdHVtLgogIDwhLS0KICAgIExvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0LCBjb25zZWN0ZXR1ciBhZGlwaXNjaW5nIGVsaXQuIER1aXMgdmVuZW5hdGlzLCBtZXR1cyBhIHRyaXN0aXF1ZSBhbGlxdWV0LCBlbmltIG5pYmggZWZmaWNpdHVyIHNlbSwgdXQgaWFjdWxpcyB1cm5hIGp1c3RvIGV1IGRpYW0uIE51bGxhbSBjdXJzdXMgc2FwaWVuIGV0IHNvZGFsZXMgcG9zdWVyZS4gVmVzdGlidWx1bSBhbnRlIGlwc3VtIHByaW1pcyBpbiBmYXVjaWJ1cyBvcmNpIGx1Y3R1cyBldCB1bHRyaWNlcyBwb3N1ZXJlIGN1YmlsaWEgQ3VyYWU7IFN1c3BlbmRpc3NlIHBvdGVudGkuIERvbmVjIHZpdGFlIG9ybmFyZSByaXN1cy4gTWFlY2VuYXMgZWxlaWZlbmQgYW50ZSB2ZWwgZHVpIGxhb3JlZXQsIGV0IHBvcnR0aXRvciBsaWJlcm8gcnV0cnVtLiBOYW0gYXJjdSBtaSwgdWxsYW1jb3JwZXIgYXQgcmlzdXMgZXQsIHB1bHZpbmFyIHVsdHJpY2VzIGVyYXQuIEluIHBlbGxlbnRlc3F1ZSBzZW0gdmVsIHB1cnVzIGF1Y3RvciwgdXQgdmVuZW5hdGlzIHRlbGx1cyB0cmlzdGlxdWUuIFBoYXNlbGx1cyBtb2xlc3RpZSBkaWFtIG9yY2ksIG5lYyBncmF2aWRhIHR1cnBpcyBiaWJlbmR1bSB1dC4gU2VkIHNhZ2l0dGlzIGFsaXF1ZXQgbG9yZW0gc2VkIGRpY3R1bS4KICAtLT4KICA8IS0tCiAgICBMb3JlbSBpcHN1bSBkb2xvciBzaXQgYW1ldCwgY29uc2VjdGV0dXIgYWRpcGlzY2luZyBlbGl0LiBEdWlzIHZlbmVuYXRpcywgbWV0dXMgYSB0cmlzdGlxdWUgYWxpcXVldCwgZW5pbSBuaWJoIGVmZmljaXR1ciBzZW0sIHV0IGlhY3VsaXMgdXJuYSBqdXN0byBldSBkaWFtLiBOdWxsYW0gY3Vyc3VzIHNhcGllbiBldCBzb2RhbGVzIHBvc3VlcmUuIFZlc3RpYnVsdW0gYW50ZSBpcHN1bSBwcmltaXMgaW4gZmF1Y2lidXMgb3JjaSBsdWN0dXMgZXQgdWx0cmljZXMgcG9zdWVyZSBjdWJpbGlhIEN1cmFlOyBTdXNwZW5kaXNzZSBwb3RlbnRpLiBEb25lYyB2aXRhZSBvcm5hcmUgcmlzdXMuIE1hZWNlbmFzIGVsZWlmZW5kIGFudGUgdmVsIGR1aSBsYW9yZWV0LCBldCBwb3J0dGl0b3IgbGliZXJvIHJ1dHJ1bS4gTmFtIGFyY3UgbWksIHVsbGFtY29ycGVyIGF0IHJpc3VzIGV0LCBwdWx2aW5hciB1bHRyaWNlcyBlcmF0LiBJbiBwZWxsZW50ZXNxdWUgc2VtIHZlbCBwdXJ1cyBhdWN0b3IsIHV0IHZlbmVuYXRpcyB0ZWxsdXMgdHJpc3RpcXVlLiBQaGFzZWxsdXMgbW9sZXN0aWUgZGlhbSBvcmNpLCBuZWMgZ3JhdmlkYSB0dXJwaXMgYmliZW5kdW0gdXQuIFNlZCBzYWdpdHRpcyBhbGlxdWV0IGxvcmVtIHNlZCBkaWN0dW0uCiAgLS0+CjwvYm9keT48L2h0bWw+)

Example:

`<amp-ad sticky="top" width="320" height="50" type="doubleclick" data-slot="/35096353/amptesting/formats/sticky"></amp-ad>`

### AMP Version Affected

2209142312000

**Comment by erwinmombay** [comment]
@powerivq @calebcordry could one of y'all take a look at this and prioritize

**Comment by powerivq** [comment]
Fixed.
