### ISSUE TITLE
amp-vimeo attribute do-not-track generate error in amp validator

### ISSUE THREAD

**Issue by markus-lutz-11880** [ampproject/amphtml#38494]
### Description

If i use attribute "do-not-track" in amp-vimeo, i get the error message "the attribute 'do-not-track' may not appear in tag 'amp-vimeo'" in amp validator.

https://amp.dev/documentation/components/amp-vimeo/

### Reproduction Steps

Use this url "https://www.11880.com/amp/branchenbuch/monheim-am-rhein/061920184B54294022/bf-service-gmbh.html" in amp validator tool.

### Browser(s) Affected

Chrome

**Comment by newmuis** [comment]
It looks like #31406 added the functionality, but not the validation.  #38495 proposes to add the validation.
