### ISSUE TITLE
amp-img with layout=responsive and float style disappears

### ISSUE THREAD

**Issue by mjangda** [ampproject/amphtml#385]
To reproduce add an `amp-img` with `layout=responsive` and a `class` that has `float` value set to `left` or `right`.

The amg-img ends up with 0x0 dimensions and is not visible.

If `layout=responsive` is removed, the image renders as expected.

Sample amp doc here: https://gist.github.com/mjangda/433bb2d9c2cceb20a171

**Comment by varshvpatil** [comment]
I was using display:flex for image div, which made image invisible, I had to use display:block to solve the problem, I hope you can make it work even if we use display:flex

**Comment by dvoytenko** [comment]
Indeed a raw `display:flex` on container and `layout=responsive` will not work together. There's not much that we can do by default given that this is CSS behavior: the `layout=responsive` takes the available to it width and the `display:flex` container reports that this width is 0. 

But you can instruct flexbox on how much space to give to the image by styling it with `flex-basis` like this: http://jsbin.com/korone/edit

**Comment by nzcage** [comment]
I think it's better to input `max-width:100%` to attribute `layout-responsive` in order to be easy for user to set `fixed width` (as in bootstrap
