### ISSUE TITLE
Intent To Implement: Kargo ad network for amp-ad

### ISSUE THREAD

**Issue by andyrusiecki** [ampproject/amphtml#3851]
# Overview

Adding support for the [Kargo](http://kargo.com) Ad Network to `<amp-ad>` elements.

## Comments

Kargo will submit a PR for a `kargo/amp-ad` branch from Kargo's `KargoGlobal/amphtml` fork.

**Comment by cramforce** [comment]
LGTM.

Looking forward to the PR!

**Comment by ericlindley-g** [comment]
@cramforce Can this be closed? (putting into "Pending 3P implementation" for now)
