### ISSUE TITLE
the tag 'amp-img' may not appear as a descendant of tag 'amp-story-player'.

### ISSUE THREAD

**Issue by jitenok** [ampproject/amphtml#38521]
my web story page is amp valid and article page also amp valid but when i embeded both this error comes in amp validator

**Comment by newmuis** [comment]
Can you share an example of the code and/or what you're trying to accomplish?  It is indeed correct that you are not able to use an `amp-img` within `amp-story-player`, as it is supposed to contain a collection of `<a>` tags linking to the web stories.

**Comment by jitenok** [comment]
i have job posting web site that was non amp . along with i am using google web stories plugin for web story thats why my web stories are amp valid but article pages are non amp . recently i installed apm for wp plugin to make my article pages amp valid.
now problen is my article pages are amp valid and web stories are also amp valid. but when i embed web story in article the artcle page convert in invalid amp pages with "**Linked AMP version is invalid**" this error with "**The tag 'amp-img' may not appear as a descendant of tag 'amp-story-player**" reason.
i am sharing my web site page that have error
https://nokaribajar.com/visionias-ae-private-limited-free-job-alert/

this is web story link
https://nokaribajar.com/web-stories/visionias-ae-private-limited-free-job-alert-2022-best-opportunity/
i dont now anything about coding
please help ......Thanks.

**Comment by jitenok** [comment]
hello everyone please Help me to solve problem

**Comment by jitenok** [comment]
very bad exprience

**Comment by jitenok** [comment]
I removed "Amp for wp" plugin From My Web Site The Problem Solved. But Now My Web Pages Are Non Amp And Web Stories Are Amp. But Now I Have Anothe Problem My 68 Web Stories In Core Web Vitals Error "LCP issue: longer than 4s (mobile)"
Like This
https://nokaribajar.com/web-stories/future-programming-languages-2025/
Please Solve My Problem

**Comment by gmajoulet** [comment]
Hello, if you're using the AMP for WordPress plugin, please file a ticket in their repository.
