### ISSUE TITLE
[amp-story] Firefox motioned elements bug

### ISSUE THREAD

**Issue by ThibC96** [ampproject/amphtml#38537]
### Description

Today we noticed various (all motioned?) elements not working as expected on Firefox
So far we had issues with animated text, outlink, caption

Firefox v106.0.3

https://join-test.my.join-stories.com/bug-EVVGxk6/?t=339

On chrome

https://user-images.githubusercontent.com/21277631/200906175-777b8753-d92b-4e0b-a4eb-3485ac3b4930.mov

On firefox

https://user-images.githubusercontent.com/21277631/200906246-0df5215c-130e-401a-b86f-bd0c8c326ac3.mov

### Reproduction Steps

none

### Browser(s) Affected

Firefox

### OS(s) Affected

Android 11, windows 10, MacOS Big Sur

**Comment by ychsieh** [comment]
Not reproducible. Should be fixed by #39400.
