### ISSUE TITLE
[amp-story] Glitch between two pages with videos

### ISSUE THREAD

**Issue by ThibC96** [ampproject/amphtml#38531]
### Description

We are experiencing issues between two pages with videos.

Some frames coming from the previous video and the next video are displayed. 

- Videos were already in cache
- All posters were replaced by a yellow image to ensure this is not any poster that we see

This issue doesn't always happen

On this story:
https://demo.join-stories.com/quartier-libre-paris-31YyXXa/index-debug-no-loop.html

What we expect:

https://user-images.githubusercontent.com/21277631/200027682-0c235547-b020-4fa6-8645-bf74f8f0bcf3.mov

What we sometimes got:

https://user-images.githubusercontent.com/21277631/200027567-aa0247f9-7523-469a-a5ef-9141fb9df0e3.mov

Both videos frame by frame

Expected

https://user-images.githubusercontent.com/21277631/200031722-f51c140f-541a-4950-884a-a7667327fc84.mov

Bug

https://user-images.githubusercontent.com/21277631/200031561-5fd8f83c-56f3-4f7b-97d7-da819b94e3e7.mov

We can notice two frames that shouldn't be there, here are the full videos:

previous video: 

https://user-images.githubusercontent.com/21277631/200032190-04a84df8-60f3-4444-a642-a17b2f6238e9.mp4

next video: 

https://user-images.githubusercontent.com/21277631/200032270-f60bea07-0b89-4b15-9b51-5d06d156e2a8.mp4

Now we can see that one of the frame is the first frame of the previous video

![comp-first-frame](https://user-images.githubusercontent.com/21277631/200032364-be356848-07eb-4c9b-9f44-3b04c05eca49.png)

And the second one is a frame at ~1s of the next video

<img width="1036" alt="comp-second-frame" src="https://user-images.githubusercontent.com/21277631/200032525-e10b9082-923d-466f-97bc-4882cfe4b83c.png">

### Reproduction Steps

No reproduction step so far

**Comment by coreymasanto** [comment]
My understanding of your issue is that, sometimes when you transition from page A to page B, two unexpected things occur:
1) a frame from the beginning of page A plays before page B's video plays
2) a frame from the middle of page B plays before page B's video properly plays from the beginning

Is this correct?

/cc @gmajoulet

**Comment by ThibC96** [comment]
This is correct

**Comment by erwinmombay** [comment]
@ThibC96 would you mind confirming if the fix worked or not?

**Comment by ThibC96** [comment]
@erwinmombay So far it seems to work, I'll let you know if I encounter the problem again
