### ISSUE TITLE
Web Stories `Cannot read properties of null (reading 'setState')`

### ISSUE THREAD

**Issue by DanielCryptoK** [ampproject/amphtml#38539]
### Description

Error below

amp-story.js:474

   Uncaught TypeError: Cannot read properties of null (reading 'setState')
at jn.Gb (amp-story.js:474:24)
at jn.Io (amp-story.js:1771:52)
at amp-story.js:792:53
at Es.fire (observable.js:63:7)
at zs.ai (ampdoc-impl.js:655:37)
at zs.overrideVisibilityState (ampdoc-impl.js:562:12)
at Object.tl (viewer-impl.js:535:17)
at Object.receiveMessage (viewer-impl.js:695:12)
at amp-viewer-integration.js:198:21
at wt.q (messaging.js:416:21)

### Reproduction Steps

Go to https://bitcoin-casino-no-deposit-bonus.com/web-stories/bc-game-review/ right click and see console errors

**Comment by newmuis** [comment]
Can you describe the user impact of this bug to help prioritization?  Is it solely a developer console error?  Or is there some user-facing behavior that does not work?

**Comment by DanielCryptoK** [comment]
I think it is just a developer console error, but it maybe impacting google bot crawling web stories.

The bug only shows on web stories.

**Comment by newmuis** [comment]
I can confirm this would not impact bots' ability to render, scrape, or ingest story content.  So, it seems it's just the error condition.

**Comment by ychsieh** [comment]
This should be fixed by #39350. Closing it.
