### ISSUE TITLE
amp-soundcloud embeds with secret tokens fail to validate.

### ISSUE THREAD

**Issue by poscar** [ampproject/amphtml#3854]
amp-soundcloud embeds that contain a secret token fail to validate even though they render correctly.

## How do we reproduce the issue?

http://jsbin.com/godizahapo#development=1

Validation produces the following:
```
validator.js:410 http://output.jsbin.com/godizahapo:26:2 The attribute 'data-trackid' in tag 'amp-soundcloud' is set to the invalid value '252220898?secret_token=s-CYqsZ'. (see https://www.ampproject.org/docs/reference/extended/amp-soundcloud.html)
```

## What browsers are affected?

All browsers

## Which AMP version is affected?

``` Powered by AMP ⚡ HTML – Version 1466185787499 ```

## Remarks
I believe the rules for validating amp-soundcloud tag's trackid attribute should be relaxed from:
```
value_regex: "[0-9]+"
```

to:

```
value_regex: "[0-9]+\?secret_token=[A-Za-z0-9_\-]+|[0-9]+"
```

or a ``` data-secrettoken ``` attribute added

Thanks!

**Comment by Gregable** [comment]
@mkhatib, the original request for this was in https://github.com/ampproject/amphtml/issues/1732 . Do you have a preference on how we validate this?

**Comment by mkhatib** [comment]
Thanks for filing. @poscar are their documentation in soundcloud of `?secret_token=s-CYqsZ` in their embedded player, couldn't find any. I'd prefer we expose a `data-secret-token` attribute and validate that separately instead.

**Comment by poscar** [comment]
@mkhatib no problem.  Yea, I guess it's not in their documentation, but the URL with secret token is produced if you try to embed a private track :/

**Comment by ericlindley-g** [comment]
@Gregable — can this be closed?

**Comment by poscar** [comment]
Was this really fixed? Specifying the data-secret-token attribute doesn't actually load the track....

http://jsbin.com/mikozuvuxo/

**Comment by jridgewell** [comment]
It might not be live on the

**Comment by poscar** [comment]
Any updates for this one?

We are specifying the secret token in the data-track-id attribute until the data-secret-token attribute actually works...

**Comment by Gregable** [comment]
I implemented validation of this new token (your doc validates), I think we still need to implement this in the `<amp-soundcloud>` runtime. Reassigning to @mkhatib

**Comment by jridgewell** [comment]
Took it from @mkhatib.

**Comment by jridgewell** [comment]
@poscar: The fix didn't make the canary this week, so it'll be two weeks before it's released into production. In the meantime, your original example is working (using `data-trackid="252220898?secret_token=s-CYqsZ"`) as a temporary hack. I can't guarantee it'll continue working, though.

**Comment by poscar** [comment]
@jridgewell Great, thank you!
