### ISSUE TITLE
Support for tracking visibility of elements not in the DOM yet

### ISSUE THREAD

**Issue by pdufour** [ampproject/amphtml#3855]
## Short description of your issue:

It would be great if you could add a visibility tracker for an element that is not in the DOM yet. Is this something that you see being added in the future?
## How do we reproduce the issue?
1. Add visibility-spec with selector for element not in DOM yet
2. Throws error.
## What browsers are affected?

All browsers
## Which AMP version is affected?

Latest

**Comment by ericlindley-g** [comment]
FYI @cramforce (+ @jridgewell, as I recall you've worked on visibility-related issues). Slotting in backlog for now, but please feel free to update/correct

**Comment by cramforce** [comment]
@ericlindley-g You don't really recall correctly with either of us :).

Over to @rudygalfi who has the most context!

**Comment by rudygalfi** [comment]
@pdufour Could you describe your use case here in more detail?

**Comment by rudygalfi** [comment]
Closing out since this needs a bit more detail. Please re-open if still needed and you can give some more context.
