### ISSUE TITLE
AMP is Not Working On Turkey

### ISSUE THREAD

**Issue by emrenogay** [ampproject/amphtml#38564]
### Description

I am a software developer who supports AMP technology and helps people in Turkey. 
As of December 1, websites using AMP stopped opening with the prefix google.com/amp/example.com when entered from the search results.

Although there are no errors in the AMP test tool, this situation exists on all websites using AMP in Turkey. What should we do, is there a study? AMP is in a very important position in my country. Please provide detailed information.

### Reproduction Steps

- Go to Google from a mobile device,
- Search for an amp compatible and indexed site.
- Click on the amp compatible site, and it logs in directly google

It used to log in with the suffix google.com/amp/example.com

### Browser(s) Affected

Chrome, Firefox, Safari, Edge, UC Browser

### OS(s) Affected

All mobile devices

### Device(s) Affected

All mobile devices

**Comment by KodaiNinja** [comment]
The same issues for Indonesia, inttermitten some of android phone works, i-phones not work.

**Comment by emrenogay** [comment]
> The same issues for Indonesia, inttermitten some of android phone works, i-phones not work.

I produced a solution for iPhone devices. But this is currently a problem regardless of browser.

**Comment by newmuis** [comment]
Google's AMP viewer is only used in contexts where they can detect browser support, but recent changes to webkit have made this no longer possible on iOS-based browsers.  This is not a breakage in AMP, though; the page should still function accordingly. It is just represented as a direct link to the AMP page on the publisher's site, rather than using Google's AMP viewer.

**Comment by emrenogay** [comment]
> Google's AMP viewer is only used in contexts where they can detect browser support, but recent changes to webkit have made this no longer possible on iOS-based browsers. This is not a breakage in AMP, though; the page should still function accordingly. It is just represented as a direct link to the AMP page on the publisher's site, rather than using Google's AMP viewer.

What would you recommend for us to at least enable the AMP viewer on Chrome? Currently, no AMP page in Turkey works with AMP viewer. This is a serious problem for us.

**Comment by newmuis** [comment]
Can you elaborate on what the problem is?  The end user should still navigate to the AMP page (directly, instead of in a viewer), and the page should still function as normal -- correct?

This repository is for the AMP JavaScript library used on AMP pages, so we don't actually control whether the viewer is used or not by Google or any other party.  But Google's decision to directly link to the AMP page (instead of in a viewer) seems like it should not change whether or not your page is working?

**Comment by emrenogay** [comment]
> Can you elaborate on what the problem is? The end user should still navigate to the AMP page (directly, instead of in a viewer), and the page should still function as normal -- correct?
> 
> This repository is for the AMP JavaScript library used on AMP pages, so we don't actually control whether the viewer is used or not by Google or any other party. But Google's decision to directly link to the AMP page (instead of in a viewer) seems like it should not change whether or not your page is working?

OK, here we go.  Both pages I left a picture of are valid AMP pages.  In the search results, when I click on the title, the page that opens should be number 1, but number 2 opens.

Before December 1, image number 1 was opening.  Me and other AMP users I represent want this should open like image #1, old functionality.

How can we get the AMP viewer in image #1 again?  Because it is much faster and safer.  The main reason we use AMP.

![FD403CD1-6F9C-4A25-A5C4-459694DDAC4F](https://user-images.githubusercontent.com/64332775/206034629-c3c50ea1-65eb-4e6a-89a9-03328055b4ae.jpeg)

![BAAA8E57-8A79-42BE-9468-65F5152D4CE0](https://user-images.githubusercontent.com/64332775/206034645-94599fd9-7f5f-4f1f-9043-e039ed0a8a95.jpeg)

**Comment by newmuis** [comment]
I understand that the behavior is different -- that's because Google has changed how they use AMP pages.  There is no way (as far as I know) for you to force Google to use your AMP page differently.

I'm wondering what practical difference this makes.  In both cases, the page works correctly, right?  Can you elaborate on why this difference matters to you?

Thanks!

**Comment by emrenogay** [comment]
> I understand that the behavior is different -- that's because Google has changed how they use AMP pages. There is no way (as far as I know) for you to force Google to use your AMP page differently.
> 
> I'm wondering what practical difference this makes. In both cases, the page works correctly, right? Can you elaborate on why this difference matters to you?
> 
> Thanks!

This is important to us because the AMP viewer is caching our site. It serves this cache to the user from the google.com domain. This is a sign of trust for users in Turkey.

Additionally, the cache is loaded very quickly from Google servers with the suffix google.com/amp/example.com/amp-url/. With the AMP viewer, pages load in under 1 second.

It's really sad to lose these features. I hope there is a way to open pages with AMP viewer.

**Comment by newmuis** [comment]
Got it.  Unfortunately, it is not something that publishers or the AMP project can control -- Google (or any other platform) can choose to link directly to AMP pages instead of using an AMP viewer if they want to.  My understanding is that it has been made infeasible to maintain an AMP viewer on iOS due to changes in WebKit.

**Comment by emrenogay** [comment]
> Got it. Unfortunately, it is not something that publishers or the AMP project can control -- Google (or any other platform) can choose to link directly to AMP pages instead of using an AMP viewer if they want to. My understanding is that it has been made infeasible to maintain an AMP viewer on iOS due to changes in WebKit.

Understood. Thank you, but this problem is not only for IOS. Valid for all popular browsers that support AMP. Chrome, Firefox, Safari etc... Now that the AMP viewer has been removed from all browsers, does this mean that AMP is slowly coming to an end?

**Comment by newmuis** [comment]
It should affect all browsers on iOS, right?  But not Android?  If you are seeing this behavior on Android, that is a bug, as far as I know.

This has nothing to do with AMP coming to an end, but changes to WebKit (which Apple mandates for all browsers on iOS) that makes this infeasible.  As far as I know, this is also only about Google Search's usage of AMP, and not the AMP JavaScript library, the AMP cache, or any other platform using AMP (even other Google products that use AMP do not seem to be changed at this time).

**Comment by emrenogay** [comment]
> It should affect all browsers on iOS, right? But not Android? If you are seeing this behavior on Android, that is a bug, as far as I know.
> 
> This has nothing to do with AMP coming to an end, but changes to WebKit (which Apple mandates for all browsers on iOS) that makes Google's AMP viewer infeasible on the web on iOS. As far as I know, this is also only about Google Search's usage of AMP, and not the AMP JavaScript library, the AMP cache, or any other platform using AMP (even other Google products that use AMP do not seem to be changed at this time).

AMP viewer does not work not only for IOS and safari, but also throughout Turkey, including Android, regardless of browser. The 2 images I left above are from the Chrome browser. I can also add a screen recording if you want.

AMP viewer not working on all websites, all browsers, all mobile devices. (only in Turkey)

When I open an AMP-compatible, indexed page by clicking the title in the search results, this is the sample page that should open: https://www.google.com/amp/example.com/slug/amp/

But this opens: https://example.com/slug/amp/

**Comment by emrenogay** [comment]
> It should affect all browsers on iOS, right? But not Android? If you are seeing this behavior on Android, that is a bug, as far as I know.
> 
> This has nothing to do with AMP coming to an end, but changes to WebKit (which Apple mandates for all browsers on iOS) that makes Google's AMP viewer infeasible on the web on iOS. As far as I know, this is also only about Google Search's usage of AMP, and not the AMP JavaScript library, the AMP cache, or any other platform using AMP (even other Google products that use AMP do not seem to be changed at this time).

I made a video to explain better. Would you please watch?

Keyword: Samsung, 84 Yıllık Tarihinin İlk Kadın Başkanını Açıkladı
Domain: webtekno.com
Self page url: https://www.webtekno.com/haber/amp/130322
Without AMP page url: https://www.webtekno.com/samsung-ilk-kadin-baskan-acikladi-h130322.html
Video I recorded: https://www.youtube.com/shorts/Ga1GjFHhwFs

My device: iPhone 13
Browser: Chrome last version

But this problem is present in android and all other browsers.

**Comment by emrenogay** [comment]
> It should affect all browsers on iOS, right? But not Android? If you are seeing this behavior on Android, that is a bug, as far as I know.
> 
> This has nothing to do with AMP coming to an end, but changes to WebKit (which Apple mandates for all browsers on iOS) that makes Google's AMP viewer infeasible on the web on iOS. As far as I know, this is also only about Google Search's usage of AMP, and not the AMP JavaScript library, the AMP cache, or any other platform using AMP (even other Google products that use AMP do not seem to be changed at this time).

Hello, any progress? @newmuis

**Comment by newmuis** [comment]
Thanks for the report.  It is still the case that this is an issue with Google's viewer, so all I can do is forward this issue along, which I have done.  It is up to each independent platform to choose how/when to enable their viewer behavior -- we don't control that to any degree.

**Comment by emrenogay** [comment]
> Thanks for the report. It is still the case that this is an issue with Google's viewer, so all I can do is forward this issue along, which I have done. It is up to each independent platform to choose how/when to enable their viewer behavior -- we don't control that to any degree.

Ok thanks for reporting this issue.

**Comment by newmuis** [comment]
In testing, it appears as if the AMP viewer still is working in Android Chrome in Turkey; if you are seeing otherwise, can you please provide Android-specific screenshots/recordings and steps to reproduce?

Thanks!

**Comment by emrenogay** [comment]
> In testing, it appears as if the AMP viewer still is working in Android Chrome in Turkey; if you are seeing otherwise, can you please provide Android-specific screenshots/recordings and steps to reproduce?
> 
> Thanks!


I just checked and the AMP viewer for Android OS is working. It wasn't working until yesterday. 
For now, we can only say that the AMP viewer does not work for the iOS.

**Comment by emrenogay** [comment]
> In testing, it appears as if the AMP viewer still is working in Android Chrome in Turkey; if you are seeing otherwise, can you please provide Android-specific screenshots/recordings and steps to reproduce?
> 
> Thanks!

What could be the reason for this not working only in Turkey? When changing country with VPN, AMP viewer works on iOS devices.

**Comment by newmuis** [comment]
As stated above, I believe the current state of Google's viewer in Google search is that it should work on Android (regardless of country), but not on iOS due to restrictions in the WebKit browser engine (regardless of country).
