### ISSUE TITLE
🌸 Cherry-pick request for #38591 into 2211302304001, 2212092023000, 2212151632000

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#38592]
### Issue (P0 Bug)

38531

### Pull Request(s)

38591

### AMP Version(s)

2211302304001, 2212092023000, 2212151632000

### Channels

Beta / Experimental, Stable, LTS

### Formats

Stories

### Justification

The previous cherry pick request https://github.com/ampproject/amphtml/issues/38578 introduced a 10ms delay to the rewinding of a amp-story page video that we are transitioning away from. This delay does not seem to be enough on some platforms, specifically iPhones 12 and up.

### Verification Steps

open https://demo.join-stories.com/quartier-libre-paris-31YyXXa/index-debug-no-loop.html in an iPhone 12 and up (or iOS simulator). glitching as described in the issue should not occur anymore

### Notifications

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by erwinmombay** [comment]
@newmuis PTAL when possible. thanks!

**Comment by newmuis** [comment]
Approved.

**Comment by erwinmombay** [comment]
closing issue. all channels and versions listed above. should be up to date. we've also verified with the bug reporters that the fix seems to be working.
