### ISSUE TITLE
The attribute 'src' in tag 'amphtml engine script' is set to the invalid value '/google_analytics_auto.js'.

### ISSUE THREAD

**Issue by rktv96** [ampproject/amphtml#38598]
### Description

The issue of "The attribute 'src' in tag 'amphtml engine script' is set to the invalid value '/google_analytics_auto.js'." shows in my wordpress blog www.telecomvibe.com. Please help me to resolve this issue. 

I am also sharing affected url as below, please inspect and provide a solution.

http://telecomvibe.com/best-fixed-wireless-lte-internet-in-usa/

### Reproduction Steps

http://telecomvibe.com/best-fixed-wireless-lte-internet-in-usa/

### Relevant Logs

```shell
http://telecomvibe.com/best-fixed-wireless-lte-internet-in-usa/
```

**Comment by erwinmombay** [comment]
hello non AMP JavaScript is not allowed to be loaded in AMP page so the warning is correct about `google_analytics_auto.js` . If you are OK with serving an invalid AMP though and do no want to be served into the AMP cache, then you can freely ignore the warning.
