### ISSUE TITLE
Why ads in Web Story are Not Clickable

### ISSUE THREAD

**Issue by naveeng413** [ampproject/amphtml#38590]
I am using google web stories plug in and my website is already monetized and ads are placing in web stories. but ads are not clickable

but when click on the any ad, its taking to next slide but not the ad page. Not getting revenue.

Please do needful.
Below is the one of the webstory from my website

https://walpencil.com/web-stories/10-home-remedies-to-get-rid-of-oily-skin/

**Comment by newmuis** [comment]
This is a bug in story ads.  It is currently being investigated in https://github.com/ampproject/amphtml/issues/38552.

**Comment by naveeng413** [comment]
But I see some web stories from other websites ads are clickable . why only with some websites having this kind of issue

**Comment by newmuis** [comment]
Can you please share examples of URLs that are working vs broken?  And note what browser and version you are testing with?

The issue certainly seems legitimate, but please provide details in #38552 so that we can keep all the information in one place.

**Comment by bestsaller1** [comment]
yes sir same website web story clickable but same not

**Comment by bestsaller1** [comment]
Same issue (not clickable )getting in my website .
