### ISSUE TITLE
amp-geo ISOSubdivision does not get populated

### ISSUE THREAD

**Issue by news-emil-davidkov** [ampproject/amphtml#38596]
### Description

Hey guys,
as more and more states introduce their type of CCPA/GDPR compliance, we have some projects that are AMP based and rely on amp-geo to provide the correct location for amp-consent and the CMP to do its thing.

In order to test that everything is mapped correctly, I've been using some VPN software (NordVPN) - pointing it to California, everything works as expected, amp-geo picks up the correct country and regionCode -
'{{AMP_ISO_COUNTRY_HOTPATCH}}' is being replaced as expected.
Whenever I try change my location to a different state(even with a different VPN), I cannot get the subdivision appear for the love of me - always is "us                          ".

This got me to wonder if it is some restriction in the CDN or am I going insane ?

### Reproduction Steps

https://www.thescottishsun.co.uk/fabulous/9894611/royal-family-sadness-harry-meghan-netflix/amp/

Point a VPN to California, check amp-geo response magic string {{AMP_ISO_COUNTRY_HOTPATCH}} replaced => "us us-ca"

Point a VPN to Virginia, check amp-geo response magic string {{AMP_ISO_COUNTRY_HOTPATCH}} replaced => "us "

PS. Tried with a machine in Virginia, same effect.

### Browser(s) Affected

Chrome

**Comment by taraschi-sp** [comment]
This may be more of a feature request than a bug since I think California is explicitly the only supported state, but having state granularity for the US moving forward will be important in supporting state-specific privacy legislations with the `amp-consent` component.

**Comment by erwinmombay** [comment]
@news-emil-davidkov thanks for the report. apologies for the delay as I missed this during the holiday season. we're prioritizing this

**Comment by news-emil-davidkov** [comment]
Hey guys,
happy new year, no worries!
The only "concerning" thing is that end of January the Virginia compliance comes into play :D no pressure :D

**Comment by erwinmombay** [comment]
Update on this. We're currently rolling out the code changes and our current tentative ETA of it landing the changes in production for VA detection is 01/23.

Will update further if anything changes.

**Comment by news-emil-davidkov** [comment]
Fantastic news, thank you!
I have a question thou.
Is it the case that you guys will follow up compliance on a state by state case - Virginia now, Colorado next, whichever state needs targeting after, or more in a general sense - where one can target an individual state in the US ?

**Comment by erwinmombay** [comment]
@news-emil-davidkov we are planning on a more generic solution so that we don't have to do one offs on a per state basis.

**Comment by news-emil-davidkov** [comment]
Woohoo
![Screenshot 2023-01-23 at 10 05 51](https://user-images.githubusercontent.com/99190267/214003989-71f40014-bc77-4fab-b7ef-76a7e67ef864.png)

**Comment by newmuis** [comment]
Dropping this to P2 to continue to track generalized state detection within AMP.

**Comment by erwinmombay** [comment]
sorry for the late reply. We have been working on implementing all the other states. Connecticut and Colorado have been supported since end of May. All the other states will be supported in a few weeks. Please see https://github.com/ampproject/amphtml/pull/39384 for tracking
