### ISSUE TITLE
Should I use amp or not

### ISSUE THREAD

**Issue by mmhdi** [ampproject/amphtml#38602]
Hello,
I have a website whose speed on mobile is 600ms and on PC is 190ms, and when I add AMP it becomes slower and its speed on mobile is 900ms and on PC is 360ms.

In general, should I use AMP, and in particular, should I use AMP to improve SEO and AdSense earnings? Is SEO and AdSense based on speed or AMP?

**Comment by newmuis** [comment]
As far as I'm aware, Google and other search engines do not use presence or absence of AMP as a ranking factor, but rather the underlying factors, such as page speed (as you mentioned).

If your page already performs better without AMP, there is no need to adopt AMP for other purposes.
