### ISSUE TITLE
🌸 Cherry-pick request for #38552 into #2212151632001 (Beta/Experimental)

### ISSUE THREAD

**Issue by mszylkowski** [ampproject/amphtml#38611]
### Issue (P0 Bug)

#38552

### Pull Request(s)

#38604

### AMP Version(s)

2212151632001

### Channels

Beta / Experimental

### Formats

Stories

### Justification

Currently XDomain ads are not clickable on stories, which can affect monetization options for story publishers that get served with 3P ads. This can be categorized as:
- cause an outage or critical production issue
- cause a significant harm to AMP's reputation if left unresolved

### Verification Steps

Trigger a XDomain ad (eg: [here](https://ayodhyanagar.com/web-stories/argentina-defeats-croatia-3-0-in-the-world-cup-final-and-lionel-messi-declares-it-to-be-his-final-world-cup-game-ever/)) and click on it. It should open the ad website.

### Summary

XDomain story ads are not clickable due to [another fix](https://github.com/ampproject/amphtml/pull/38377) not being tested on XDomain ads. We didn't have `example/amp-story` websites to test locally with XDomain ads so we should add an example for XDomain ads if possible (added this as action item). Xdomain ads get renders differently from 1P ads, which contributed to the difficulty of testing this behavior in the repo.

### Action Items

- Add XDomain ad story in `examples/amp-story`
- If possible, write integration test with XDomain ad clicked

### Notifications

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by newmuis** [comment]
Cherrypick approved.

Under the action items, is there a way we can add an integration test for this case?

**Comment by mszylkowski** [comment]
I'll add it to see if it's possible.

**Comment by estherkim** [comment]
2212151632002 has been deployed to beta opt-in and beta 1%
