### ISSUE TITLE
amp-sticky-ad should enforce style for close button

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#3862]
## Short description of your issue:

amp-sticky-ad generates a html button element to give the user the chance to close the ad. It should enforce min-width=0 !important on the class associated to the button otherwise it will not work when user has specific css for the button already defined.
## How do we reproduce the issue?

[Example](https://ampbyexample.com/components/amp-sticky-ad/). In this case I am setting min-width:64px for all the buttons in the css and it's breaking the amp component. So I had to override the style of the close button in order to fix it.
## What browsers are affected?

Chrome
## Which AMP version is affected?

amp-version="1466794223483"

**Comment by kul3r4** [comment]
@zhouyx @jasti

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
