### ISSUE TITLE
Allow TITLE and SOURCE_URL variable substitution in amp-ad RTC urls

### ISSUE THREAD

**Issue by zshnr** [ampproject/amphtml#38627]
### Description

Hello,

Would it be possible to add `TITLE` and `SOURCE_URL` to the list of allowed macros for RTC config?

If there is no issue with this, I am happy to create a PR to do so :)

Thanks!

### Alternatives Considered

We ask our customers to use whatever templating solution they use to do this there. But Ideally we wouldn't want to leave this up to the customer doing the right thing.

### Additional Context

These values will be extremely useful to return rich targeting information for our customers that use AMP for their web properties.

**Comment by erwinmombay** [comment]
@powerivq @calebcordry could y'all evaluate if there are no issues with adding these?

**Comment by calebcordry** [comment]
These seem safe to me, @powerivq any concern?

**Comment by powerivq** [comment]
I don't see problems with these.

**Comment by zshnr** [comment]
Thank you all so much! I'll create a PR in that case

**Comment by erwinmombay** [comment]
Closed by https://github.com/ampproject/amphtml/pull/38723
