### ISSUE TITLE
Animations disappear when linking to a specific Web Story page

### ISSUE THREAD

**Issue by adamdunnage** [ampproject/amphtml#38622]
### Description

When adding a link to a specific Web Story page using [branching](https://amp.dev/documentation/components/stories/amp-story?redirected#branching), any elements with animations will disappear from the page if navigating via the direct link to page. this will also break the Story controls to move between pages.

An example can be seen here:

https://user-images.githubusercontent.com/91896826/211827376-97876adc-e214-49c5-91c5-448dadf11e84.mp4

In the recording above you will see that on page 3 of the Story the block of text initially drops in. When navigating to page 5 and clicking the CTA to go back to page 3, the block of text no longer shows and some of the Story controls are not longer working. 

The link used in this example followed the documentation for branching and was as follows: 

https://suspectstocking.s4-tastewp.com/web-stories/food-template-test/#page=a378f919-785d-4ff2-8f8c-e7922a221cbf

this looks to be linked specifically to animations on the Web Storys as once they are removed this links to the page with all content displayed.

### Reproduction Steps

1. Create a Story using the [Web Stories](https://wordpress.org/plugins/web-stories/) plugin. 
2. Add animations to one of the pages.
3. Get the amp-story-page id from the source code for the page that you added animations to.
4. Add a CTA on a separate page of the story to link to the page with the animations using the the amp-story-page id gathered in the last step following the URL structure advised [here](https://amp.dev/documentation/components/stories/amp-story?redirected#branching:~:text=https%3A//www.mydomain.com/good%2Dstory/%23page%3D%3Cpage%2Did%3E).
5. Publish the story and try the CTA to the page with animations.

**Comment by banaag** [comment]
ACTION REQUIRED: size the investigation.
