### ISSUE TITLE
AMP version not working on Google App Browser

### ISSUE THREAD

**Issue by folktravel** [ampproject/amphtml#38631]
### Description

Hey Guys,
I can see when people is using the app “Google” and doing a search for example 
folk-travel drone voyage
When go on website, in adress bar we can see AMP version but website is not loading !
It’s the only browser that don’t show my AMP version .. Chrome, Safari, Search Console no problem

Can you help me ? I think many visitors are using google seach button on their mobile…

### Reproduction Steps

Go to Google App
[https://i.ibb.co/sHs2TKY/Image-2.jpg](url)

[https://i.ibb.co/gZvx9Sq/Image-3.jpg](url)

[https://i.ibb.co/MSmLGF9/Image-4.jpg](url)

### OS(s) Affected

ios , maybe android?

**Comment by erwinmombay** [comment]
Heya, unfortunately looks like the links you shared don't work. closing this for now as stale but feel free to re-open if you can provide additional information for us to reproduce the issue.
