### ISSUE TITLE
Listing PubLive as one of the AMP website building CMS platforms in the tools page

### ISSUE THREAD

**Issue by harmeetpublive** [ampproject/amphtml#38636]
### Description

[PubLive](https://thepublive.com/) is an **AMP first SAAS based CMS** which creates only AMP based content creator / publisher websites.

I wanted to understand the process of getting listed as one of the AMP based CMS tools for website creation, to be placed with our alternatives Rebelmouse and Quintype here:
https://amp.dev/documentation/tools

We went live with our first publisher website in May 2022, and as of today there are over 20 digital publisher websites that are powered by our CMS platform. Here are a couple of them:

- https://tice.news/
- https://newsdrum.in/
- https://hindi.shethepeople.tv/
- https://www.womenscriczone.com/
- https://30stades.com/

Hoping to get some direction for my requirement.

### Alternatives Considered

NA

**Comment by newmuis** [comment]
Please [file an issue on the amp.dev repository](https://github.com/ampproject/amp.dev/issues/new?assignees=&labels=Status%3A+Pending+Triage%2C+Type%3A+New&template=tool.md&title=).
