### ISSUE TITLE
 amp-animation failed to build: Found 0 <script> children. Expected 1.

### ISSUE THREAD

**Issue by danielleHerszfang** [ampproject/amphtml#38632]
### Description

Hey! I sometimes have this error on my page (not in every page load) although I always have a child script tag inside my amp-animation tags.
<img width="516" alt="Screenshot 2023-01-16 at 10 56 43" src="https://user-images.githubusercontent.com/88485591/212656847-5dccd40f-b8d8-4d6a-88c9-262ad789fb32.png">
<img width="522" alt="Screenshot 2023-01-16 at 10 58 16" src="https://user-images.githubusercontent.com/88485591/212656861-11f2b35b-ca91-4f39-906e-3da338a455a4.png">
<img width="710" alt="Screenshot 2023-01-16 at 11 53 01" src="https://user-images.githubusercontent.com/88485591/212656866-2d349dad-62e5-4735-9b14-2504f57759a2.png">

### Reproduction Steps

https://beststudentloancompanies.com/#monitoring=1 
refresh page until you'll see these amp-animation errors (Found 0 <script> children. Expected 1.) in dev tool's console.

### Relevant Logs

```shell
amp-animation-0.1.js:2 Uncaught (in promise) Resource: failed to build: amp-animation#5: Found 0 <script> children. Expected 1.
    at https://cdn.ampproject.org/rtv/012301031703000/v0/amp-animation-0.1.js:2:79635
    at r.buildCallback (https://cdn.ampproject.org/rtv/012301031703000/v0/amp-animation-0.1.js:2:80066)
    at https://cdn.ampproject.org/v0.js:2:86982
(anonymous)	@	amp-animation-0.1.js:2
r.buildCallback	@	amp-animation-0.1.js:2
(anonymous)	@	v0.js:2
Promise.then (async)		
i.Uh	@	v0.js:2
i.Lh	@	v0.js:2
i.Dh	@	v0.js:2
i.zh	@	v0.js:2
i.upgraded	@	v0.js:2
u.Ce	@	v0.js:2
u.Xe	@	v0.js:2
u.Ne	@	v0.js:2
u.connectedCallback	@	v0.js:2
```

### Browser(s) Affected

Chrome

### OS(s) Affected

macOS 13.1

### Device(s) Affected

MacBook Pro 2020

### AMP Version Affected

2301031703000

**Comment by erwinmombay** [comment]
taking a look right now

**Comment by erwinmombay** [comment]
@danielleHerszfang im having a bit of difficulty reproducing the issue, i hope you dont mind if i ask for some additional information.

* Do you use any extensions like adblockers when this occurs? or any chrome extensions/addons that could mutate the DOM?
* Around how many times do you have to load the page until the issue occurs? I've reloaded the page on chrome on macOS 13.1 around 30x and haven't gotten the issue to trigger yet.
* Does the issue only occur on your origin domain https://beststudentloancompanies.com/? does it also happen on the Google AMP cache domain url?
* Could you check if it still occurs on the latest `2301181928000` version.

thank you for any additional info!

**Comment by danielleHerszfang** [comment]
Hey @erwinmombay Thanks for your reply!
I also can't reproduce the problem currently, tried also specifically using amp version 2301031703000, 
but without success  will update if it occurs again.

**Comment by erwinmombay** [comment]
thanks for verifying @danielleHerszfang . im closing the issue but feel free to re-open if you can reproduce again.
