### ISSUE TITLE
Google Page Speed Reports AMP scripts are blocking main thread

### ISSUE THREAD

**Issue by jjxtra** [ampproject/amphtml#38642]
### Description

Since all the amp scripts are marked async I would expect the page rendering to proceed without them. This appears to not be the case. See this screenshot:

![image](https://user-images.githubusercontent.com/1271832/213880525-168f7020-4191-4ea9-af3f-1f2127a8a27f.png)

### Reproduction Steps

Run google page speed on an amp enabled url with amp scripts

### Browser(s) Affected

Chrome, Firefox, Safari, Edge, UC Browser

### OS(s) Affected

All

### Device(s) Affected

All

### AMP Version Affected

230121010101

**Comment by accepto** [comment]
![grafik](https://github.com/ampproject/amphtml/assets/225216/b6d0a2e4-1006-442d-b29e-1def43f532d4)
Addional: Remove large, duplicate JavaScript modules from bundles to reduce unnecessary bytes consumed by network activity.

**Comment by powerivq** [comment]
@jjxtra  AMP runtime is indeed required to render the page, so it is not unexpected. It also appears that this page is not fully AMP. 

@accepto I ran lighthouse on the page you provided and the result seems fine. Higher LCP but other metrics are okay.

Either way, let us know if you have any ideas on how to improve.
