### ISSUE TITLE
[AMP-STORY] Create ratio presets for desktop mode

### ISSUE THREAD

**Issue by edoudou** [ampproject/amphtml#38658]
### Description

Allow to change ratio in dektop mode.

Using a list of presets allow to keep the hand of the ratios available.

An important ratio to add would be 9/16 as a lots of people uses assets from Instagram.

### Alternatives Considered

Any way to customize desktop ratio for non-landscape stories.

**Comment by edoudou** [comment]
@newmuis any updates on this issue ? What would be for you the best way to implement it ?

**Comment by newmuis** [comment]
As mentioned in the meeting, we likely don't need the presets, but can just clamp the value between the minimum (1/2) and maximum (3/4) aspect ratios.

@ychsieh maybe this is a good one for you to look at next week?

**Comment by edoudou** [comment]
@newmuis @ychsieh any update on this issue ?

**Comment by ychsieh** [comment]
To make sure I understand the request, do you want to customize the ratio by feeding it through html code, e.g. an attribute like "aspect-ratio=9:16"?

I think it should be doable by retrieving that and assigning it to "--aspect-ratio". Then in amp-story.css we check if it's within the range [1/2, 3/4] [here](https://github.com/ampproject/amphtml/blob/f8cbfb0c4e4db6b8dea923c0afdf75aa7888e4b8/extensions/amp-story/1.0/amp-story.css#L409).

**Comment by edoudou** [comment]
The idea is indeed to allow to customizing the ratio of the desktop panel (in mobile, the ratio will stay true to the device). An attribut could indeed be a solution. 

I think that technically you just need to update the css variable `--i-amphtml-story-desktop-one-panel-ratio` (I think it is present in 2 files but I may be wrong : 
https://github.com/processprocess/amphtml/blob/main/extensions/amp-story/1.0/amp-story-desktop-one-panel.css and amp-story-player-shadow.css )
