### ISSUE TITLE
when enabling AMP only page, getting some problems

### ISSUE THREAD

**Issue by dhavalveera** [ampproject/amphtml#38657]
### Description

Hello,

I am using Nextjs v13 to build the website, and for UI Framework I'm using [MUI](https://mui.com/) and I'm rendering Navbar based on the following condition:

```js
const isSmUp = useMediaQuery(theme.breakpoints.down("sm"));

return isSmUp ? <MobileNavbar /> : <DesktopNavbar />
```

if the website is on Mobile Screen then I'm rendering a different Navbar, and the following code for Index Page:

```js
import React from "react";

// next component
import Head from "next/head";

// MUI Component
import { Box, Card, CardContent, Container, Grid } from "@mui/material";

// Navbar
import Navbar from "../layout/navbar.jsx";

export const config = { amp: true };

const Home = () => {
  return (
    <>
      <Head>
        <title>Demo</title>
      </Head>

      <Box component="main" sx={{ flexGrow: 1, py: 5 }}>
        <Container maxWidth="lg">
          <Box sx={{ mb: 4 }}>
            <Grid container justifyContent="space-between" spacing={3}>
              <Grid item md={4} lg={4} xs={12}></Grid>
              <Grid item md={8} lg={8} xs={12}>
                <Card sx={{ borderRadius: "12px" }}>
                  <CardContent>
                    <Grid
                      container
                      justifyContent="space-between"
                      alignItems="center"
                      spacing={3}
                    >
                      <Grid item></Grid>
                      <Grid item>
                        <Navbar />
                      </Grid>
                    </Grid>
                  </CardContent>
                </Card>
              </Grid>
            </Grid>
          </Box>
        </Container>
      </Box>
    </>
  );
};

export default Home;
```

and here I've added `amp: true` then my Navbar for Mobile Version isn't rendering at all, only the Desktop version Navbar is getting rendered.

in Reproduction Steps, I'm sharing the link to the Code 

### Reproduction Steps

https://codesandbox.io/p/sandbox/frosty-cherry-duktwc

### Browser(s) Affected

Chrome

### OS(s) Affected

Windows 11

### AMP Version Affected

2301112346000

**Comment by dhavalveera** [comment]
### without adding `export const config = { amp: true };`

![image](https://user-images.githubusercontent.com/32231977/215300251-a600c85b-8d8d-4e9a-811d-3b2b21edf498.png)
![image](https://user-images.githubusercontent.com/32231977/215300261-57d701e7-4893-40be-87b2-ccf9003190d2.png)


### after adding `export const config = { amp: true };`
![image](https://user-images.githubusercontent.com/32231977/215300251-a600c85b-8d8d-4e9a-811d-3b2b21edf498.png)
![image](https://user-images.githubusercontent.com/32231977/215300277-3fcf9205-f10b-4422-8360-df76e2f5ef03.png)



I have attached the screenshots of how Navbar is rendering on Desktop + Mobile when amp isn't enable & when it's enabled.

**Comment by dhavalveera** [comment]
any update on this issue?

**Comment by newmuis** [comment]
I'm not certain this is actually an issue with AMP rather than an issue with Next... Are you able to see the resulting AMPHTML markup?  Is it valid AMP?

**Comment by dhavalveera** [comment]
@newmuis  = when I give this `export const config = { amp: true };` then in the browser console, I am getting the AMP message with the version I guess.

but I don't think this is an issue with Nextjs but instead with AMP.

**Comment by newmuis** [comment]
Can you provide the generated AMP markup here?  Without the markup, it won't be possible for us to troubleshoot this issue.

**Comment by dhavalveera** [comment]
I've already provided the link of codesandboxx to check

**Comment by dhavalveera** [comment]
https://codesandbox.io/p/sandbox/frosty-cherry-duktwc

**Comment by newmuis** [comment]
This codesandbox link provides NextJS markup.  We support AMP, but not NextJS.  If you are using NextJS to generate AMP markup, that's fine, but in order to troubleshoot the issue, we will need to see the generated AMP-compliant HTML markup.
