### ISSUE TITLE
[amp-story-player] Story may not open in some strange cases

### ISSUE THREAD

**Issue by shivkumar1490** [ampproject/amphtml#38666]
### What's the issue?

When we get stories list from a server and creating player from JavaScript the player doesn't loads amp stories.

**What browsers are affected?**
All browsers

**Which AMP version is affected?**
ALL

### take a look at this screenshots:
![Screenshot (1732)](https://user-images.githubusercontent.com/124679555/217245504-391c4820-32ee-42e5-a156-00f0ad793099.png)

![amp-story-player-error](https://user-images.githubusercontent.com/124679555/217249831-f337303d-b640-41c9-aad4-769c13c74444.PNG)

[https://visualstories.com/?app=pwa](https://visualstories.com/?app=pwa)

### Relevant Logs

#31738

### Browser(s) Affected

All browsers

### Device(s) Affected

All device.

### AMP Version Affected

ALL

**Comment by coreymasanto** [comment]
Based on logs in the screenshot, it appears that the classlist property [here](https://github.com/ampproject/amphtml/blob/3bc005d52a01d397fe21113ad74d7b465261c7e0/src/amp-story-player/amp-story-player-impl.js#L809) can't be accessed on the player's `this.rootEl_` (which appears to be null). This root element is supposed to exist after being initialized in `initializeShadowRoot_()` [here](https://github.com/ampproject/amphtml/blob/3bc005d52a01d397fe21113ad74d7b465261c7e0/src/amp-story-player/amp-story-player-impl.js#L398). I haven't yet been able to repro this issue, but I'll try to determine what could be causing the root element to be null.

**Comment by coreymasanto** [comment]
Is this issue still occurring for you? I am still unable to reproduce it, but it would be helpful if you could show us how you're using JS to create the player. If helpful, you can view how to do so at the documentation [here](https://github.com/ampproject/amphtml/blob/main/docs/spec/amp-story-player.md#load).

**Comment by erwinmombay** [comment]
closing this issue as stale. feel free to re-open if you have additional information
