### ISSUE TITLE
AMP for Email: allow custom attribute for <a> tag  

### ISSUE THREAD

**Issue by average-html-enjoyer** [ampproject/amphtml#38679]
### Description

Hello,

Is there any possibility to add an attribute such as `x-do-link-relink=0` in tag `<a>`, so AMP email pass the validation? Right now it's forbidden.

Case:

We want to use smartlinks in AMP e-mails, so users could have the best experience:
• when open e-mail on desktop → open website;
• when open e-mail on mobile device → open app.

Without `x-do-link-relink=0` smartlinks on ios devices always open web 😥

Example:

We use 'x-do-link-relink=0' in HTML. This helps us to avoid tracking the link and allows users open our app on ios devices. Without that parameter ios users are forced to open web, which is a poor UX, especially if the app is installed.

```
<a href="SMARTLINK" x-do-link-relink=0 target="_blank" style="font-family:'San Francisco', Segoe, Roboto, Arial, Helvetica, sans-serif;display:inline-block;vertical-align:top;font-size:17px;line-height:24px;color:#333333;font-weight:normal;text-decoration:none;text-align:center;padding:16px 36px 16px;-webkit-border-radius:4px;-moz-border-radius:4px;-ms-border-radius:4px;border-radius:4px;-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;max-width:100%;">
  Button
</a>
```

### Alternatives Considered

We force our users sing in on web without that attribute, which lead to loss of engagement in our products:
• sing-in on app needs face id only or simple 4-number code;
• sing-in on web needs login, password, phone number and security code via SMS.

Not the best experience so far 🥲

### Additional Context

The ESP we rely on can only provide us with manual settings which allows to ignore link tracking (and allows ios users open app from email). So for every tag <a> we have to add that attribute.

It would be great to use `x-do-link-relink=0` in AMP Emails.

Thanks!

**Comment by newmuis** [comment]
Is it possible for this attribute to be expressed as a [`data-*` attribute](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes)?  These are not validated, as they do not carry a semantic meaning, pet the HTML or AMPHTML specifications.

**Comment by average-html-enjoyer** [comment]
> Is it possible for this attribute to be expressed as a [`data-*` attribute](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes)? These are not validated, as they do not carry a semantic meaning, pet the HTML or AMPHTML specifications.

that helps, thank you!
