### ISSUE TITLE
Custom JavaScript is not allowed

### ISSUE THREAD

**Issue by leob123** [ampproject/amphtml#38676]
### Description

The Google Console error reports: The parent tag of tag 'amphtml engine script' is 'body', but it can only be 'head'. However, the script is in the head. See log 

### Reproduction Steps

https://www.springworks.com/?amp=1
![amperror](https://user-images.githubusercontent.com/125535198/219278406-40467415-eee2-4cb5-ac8a-d83e1aca17e6.png)
![amperror1](https://user-images.githubusercontent.com/125535198/219278431-ed622bef-45b9-45f4-b55e-d2656b2f8bf8.png)
![amperror2](https://user-images.githubusercontent.com/125535198/219278451-8c5f7f53-5b3b-4258-ac7a-017f60e6cfa4.png)

### Relevant Logs

```shell
</head>

<body class="area-c skin-customer skin-crisp_white-customer skin-theme_tweaker-customer unauthorized target-main no-sidebars responsive-mobile">



<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-VLDWV5K98P"></script>
<script type="text/javascript" id="ga-init-script" data-settings='{&quot;sendPageview&quot;:true,&quot;currency&quot;:&quot;USD&quot;}'>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-VLDWV5K98P');
  </script>
```

**Comment by erwinmombay** [comment]
hey @leob123 would you mind clarifying a little bit what the issue is. i am not able to reproduce the issue on https://www.springworks.com/?amp=1

are you adding the GA script on an amp page?

**Comment by erwinmombay** [comment]
closing as stale. feel free to re-open if you have more information to add
