### ISSUE TITLE
How to use Javascript with AMP

### ISSUE THREAD

**Issue by richajain360** [ampproject/amphtml#38680]
### Description

I am using Site Speaker plugin which is not working with AMP. what can I do to active this plugin on mobile as well. Script are below:
<div id="ra-player" data-skin="https://assets.sitespeaker.link/embed/skins/default"><div class="ra-button" onclick="tap:readAloud(document.getElementById('ra-audio'), document.getElementById('ra-player'))"><img src="https://assets.sitespeaker.link/embed/skins/default/play-icon.png"> Listen to this article</div></div>

### Reproduction Steps

I set up website localy and configure plugin: https://wordpress.org/plugins/sitespeaker-widget/

**Comment by newmuis** [comment]
It is not feasible to use arbitrary JavaScript with AMP.
