### ISSUE TITLE
[amp-story] RTL: Scroll arrows not working correctly and they are not positioned correctly on their place

### ISSUE THREAD

**Issue by MMaKenZi** [ampproject/amphtml#38683]
### Description

In the RTL mode, the scrolling arrows are not positioned correctly in their place and not working correctly, I attached a video

https://user-images.githubusercontent.com/20024403/220620542-0f8ac664-36ba-4a09-9542-b200a8f11605.mp4

this bug was reported here:
https://github.com/GoogleForCreators/web-stories-wp/issues/12874
but they said, it's related to amphtml git
"This needs to be reported upstream at https://github.com/ampproject/amphtml because those arrows are added by the amp-story-player component."

I am not sure if this is related to AMP WordPress plugin or AMP core plugin

### Reproduction Steps

Try to use the web story template on RTL mode

**Comment by ychsieh** [comment]
Cannot reproduce this. Tried some template URLs locally and it works fine. Could you share the URLs you see this error?

**Comment by MMaKenZi** [comment]
@ychsieh 
sorry, didn't see your message, you can check it out on this website, right under the main slider
[https://abzarmag.com/](https://abzarmag.com/)
