### ISSUE TITLE
`amp-story-page-outlink` hides during video playback in Firefox

### ISSUE THREAD

**Issue by draeton** [ampproject/amphtml#38690]
### Description

I have a multi-page story, and each `amp-story-page` contains an `amp-video` and an `amp-story-page-outlink`. In Firefox, the outlink is visible when the page loads, but it become invisible after a short duration (~1 second).

### Reproduction Steps

This demo shows the issue happening with a single `amp-story-page` containing an `amp-video` and an `amp-story-page-outlink`. The video autoplays when the page loads, then the outlink disappears.

The `amp-video` source in the demo is only 3 seconds long, but the following screen capture shows the outlink reappears at the 16 second mark.

#### Demo screen capture

https://user-images.githubusercontent.com/284833/221880599-dcecefdd-9530-4e66-98c8-dd0441b93460.mp4

#### Demo URL

https://playground.amp.dev/?runtime=amp4stories&mode=iPhone+5%2FSE#share=PCFET0NUWVBFIGh0bWw+CjxodG1sIGFtcCBsYW5nPSJlbiI+CiAgPGhlYWQ+CiAgICA8bWV0YSBjaGFyc2V0PSJ1dGYtOCIgLz4KICAgIDxzY3JpcHQgYXN5bmMgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC5qcyI+PC9zY3JpcHQ+CiAgICA8c2NyaXB0CiAgICAgIGFzeW5jCiAgICAgIGN1c3RvbS1lbGVtZW50PSJhbXAtdmlkZW8iCiAgICAgIHNyYz0iaHR0cHM6Ly9jZG4uYW1wcHJvamVjdC5vcmcvdjAvYW1wLXZpZGVvLTAuMS5qcyIKICAgID48L3NjcmlwdD4KICAgIDxzY3JpcHQKICAgICAgYXN5bmMKICAgICAgY3VzdG9tLWVsZW1lbnQ9ImFtcC1zdG9yeSIKICAgICAgc3JjPSJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZy92MC9hbXAtc3RvcnktMS4wLmpzIgogICAgPjwvc2NyaXB0PgogICAgPHRpdGxlPk15IFN0b3J5PC90aXRsZT4KICAgIDxtZXRhCiAgICAgIG5hbWU9InZpZXdwb3J0IgogICAgICBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsbWluaW11bS1zY2FsZT0xLGluaXRpYWwtc2NhbGU9MSIKICAgIC8+CiAgICA8bGluayByZWw9ImNhbm9uaWNhbCIgaHJlZj0iaGVsbG93b3JsZC5odG1sIiAvPgogICAgPHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT4KICAgICAgYm9keSB7CiAgICAgICAgLXdlYmtpdC1hbmltYXRpb246IC1hbXAtc3RhcnQgOHMgc3RlcHMoMSwgZW5kKSAwcyAxIG5vcm1hbCBib3RoOwogICAgICAgIC1tb3otYW5pbWF0aW9uOiAtYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsIGVuZCkgMHMgMSBub3JtYWwgYm90aDsKICAgICAgICAtbXMtYW5pbWF0aW9uOiAtYW1wLXN0YXJ0IDhzIHN0ZXBzKDEsIGVuZCkgMHMgMSBub3JtYWwgYm90aDsKICAgICAgICBhbmltYXRpb246IC1hbXAtc3RhcnQgOHMgc3RlcHMoMSwgZW5kKSAwcyAxIG5vcm1hbCBib3RoOwogICAgICB9CiAgICAgIEAtd2Via2l0LWtleWZyYW1lcyAtYW1wLXN0YXJ0IHsKICAgICAgICBmcm9tIHsKICAgICAgICAgIHZpc2liaWxpdHk6IGhpZGRlbjsKICAgICAgICB9CiAgICAgICAgdG8gewogICAgICAgICAgdmlzaWJpbGl0eTogdmlzaWJsZTsKICAgICAgICB9CiAgICAgIH0KICAgICAgQC1tb3ota2V5ZnJhbWVzIC1hbXAtc3RhcnQgewogICAgICAgIGZyb20gewogICAgICAgICAgdmlzaWJpbGl0eTogaGlkZGVuOwogICAgICAgIH0KICAgICAgICB0byB7CiAgICAgICAgICB2aXNpYmlsaXR5OiB2aXNpYmxlOwogICAgICAgIH0KICAgICAgfQogICAgICBALW1zLWtleWZyYW1lcyAtYW1wLXN0YXJ0IHsKICAgICAgICBmcm9tIHsKICAgICAgICAgIHZpc2liaWxpdHk6IGhpZGRlbjsKICAgICAgICB9CiAgICAgICAgdG8gewogICAgICAgICAgdmlzaWJpbGl0eTogdmlzaWJsZTsKICAgICAgICB9CiAgICAgIH0KICAgICAgQC1vLWtleWZyYW1lcyAtYW1wLXN0YXJ0IHsKICAgICAgICBmcm9tIHsKICAgICAgICAgIHZpc2liaWxpdHk6IGhpZGRlbjsKICAgICAgICB9CiAgICAgICAgdG8gewogICAgICAgICAgdmlzaWJpbGl0eTogdmlzaWJsZTsKICAgICAgICB9CiAgICAgIH0KICAgICAgQGtleWZyYW1lcyAtYW1wLXN0YXJ0IHsKICAgICAgICBmcm9tIHsKICAgICAgICAgIHZpc2liaWxpdHk6IGhpZGRlbjsKICAgICAgICB9CiAgICAgICAgdG8gewogICAgICAgICAgdmlzaWJpbGl0eTogdmlzaWJsZTsKICAgICAgICB9CiAgICAgIH0KICAgIDwvc3R5bGU+CiAgICA8bm9zY3JpcHQKICAgICAgPjxzdHlsZSBhbXAtYm9pbGVycGxhdGU+CiAgICAgICAgYm9keSB7CiAgICAgICAgICAtd2Via2l0LWFuaW1hdGlvbjogbm9uZTsKICAgICAgICAgIC1tb3otYW5pbWF0aW9uOiBub25lOwogICAgICAgICAgLW1zLWFuaW1hdGlvbjogbm9uZTsKICAgICAgICAgIGFuaW1hdGlvbjogbm9uZTsKICAgICAgICB9CiAgICAgIDwvc3R5bGU+PC9ub3NjcmlwdAogICAgPgogICAgPHN0eWxlIGFtcC1jdXN0b20+CiAgICAgIGFtcC1zdG9yeS1wYWdlIHsKICAgICAgICBiYWNrZ3JvdW5kOiB3aGl0ZTsKICAgICAgfQogICAgICBoMSB7CiAgICAgICAgZm9udC1zaXplOiAyLjg3NWVtOwogICAgICAgIGZvbnQtd2VpZ2h0OiBub3JtYWw7CiAgICAgICAgbGluZS1oZWlnaHQ6IDEuMTc0OwogICAgICAgIHRleHQtdHJhbnNmb3JtOiB1cHBlcmNhc2U7CiAgICAgIH0KICAgIDwvc3R5bGU+CiAgPC9oZWFkPgoKICA8Ym9keT4KICAgIDxhbXAtc3RvcnkKICAgICAgc3RhbmRhbG9uZQogICAgICB0aXRsZT0iTG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQsIGNvbnNlY3RldHVyIGFkaXBpc2NpbmcgLSBQdWJsaXNoZXIiCiAgICAgIHB1Ymxpc2hlcj0iUHVibGlzaGVyIgogICAgICBwdWJsaXNoZXItbG9nby1zcmM9Imh0dHBzOi8vc3RvcmFnZS5nb29nbGVhcGlzLmNvbS9vcGVyYXRpbmctYW5hZ3JhbS04MjgwL2FwcGxlLXRvdWNoLWljb24ucG5nIgogICAgICBwb3N0ZXItcG9ydHJhaXQtc3JjPSJodHRwczovL3BsYWNlaG9sZC5qcC83MjB4OTYwLnBuZyIKICAgICAgcG9zdGVyLXNxdWFyZS1zcmM9Imh0dHBzOi8vcGxhY2Vob2xkLmpwLzcyMHg3MjAucG5nIgogICAgICBwb3N0ZXItbGFuZHNjYXBlLXNyYz0iaHR0cHM6Ly9wbGFjZWhvbGQuanAvOTYweDcyMC5wbmciCiAgICA+CiAgICAgIDxhbXAtc3RvcnktcGFnZSBpZD0icGFnZS0xIj4KICAgICAgICA8YW1wLXN0b3J5LWdyaWQtbGF5ZXIgdGVtcGxhdGU9ImZpbGwiPgogICAgICAgICAgPGFtcC12aWRlbwogICAgICAgICAgICBhdXRvcGxheQogICAgICAgICAgICBub2F1ZGlvCiAgICAgICAgICAgIHdpZHRoPSI3MjAiCiAgICAgICAgICAgIGhlaWdodD0iOTYwIgogICAgICAgICAgICBwb3N0ZXI9Imh0dHBzOi8vYW1wLmRldi9zdGF0aWMvc2FtcGxlcy9pbWcvc3RvcnlfdmlkZW9fZG9nX2NvdmVyLmpwZyIKICAgICAgICAgICAgdGl0bGU9IkxvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0LCBjb25zZWN0ZXR1ciBhZGlwaXNjaW5nIgogICAgICAgICAgICBsYXlvdXQ9InJlc3BvbnNpdmUiCiAgICAgICAgICA+CiAgICAgICAgICAgIDxzb3VyY2UKICAgICAgICAgICAgICBzcmM9Imh0dHBzOi8vYW1wLmRldi9zdGF0aWMvc2FtcGxlcy92aWRlby9zdG9yeV92aWRlb19kb2cubXA0IgogICAgICAgICAgICAgIHR5cGU9InZpZGVvL21wNCIKICAgICAgICAgICAgLz4KICAgICAgICAgIDwvYW1wLXZpZGVvPgogICAgICAgIDwvYW1wLXN0b3J5LWdyaWQtbGF5ZXI+CiAgICAgICAgPGFtcC1zdG9yeS1wYWdlLW91dGxpbmsKICAgICAgICAgIGxheW91dD0ibm9kaXNwbGF5IgogICAgICAgICAgdGhlbWU9ImN1c3RvbSIKICAgICAgICAgIGN0YS1hY2NlbnQtZWxlbWVudD0idGV4dCIKICAgICAgICAgIGN0YS1hY2NlbnQtY29sb3I9IiMyMDIxMjQiCiAgICAgICAgPgogICAgICAgICAgPGEKICAgICAgICAgICAgaHJlZj0iaHR0cHM6Ly9nb29nbGUuY29tIgogICAgICAgICAgICB0YXJnZXQ9Il9ibGFuayIKICAgICAgICAgICAgcmVsPSJub29wZW5lciBub3JlZmVycmVyIgogICAgICAgICAgPgogICAgICAgICAgICBDbGljayBtZQogICAgICAgICAgPC9hPgogICAgICAgIDwvYW1wLXN0b3J5LXBhZ2Utb3V0bGluaz4KICAgICAgPC9hbXAtc3RvcnktcGFnZT4KICAgIDwvYW1wLXN0b3J5PgogIDwvYm9keT4KPC9odG1sPgo=

### Relevant Logs

```shell
Powered by AMP ⚡ HTML – Version 2302031721000 https://playground.amp.dev/?runtime=amp4stories&mode=iPhone+5%2FSE# amp.js:147:32
[video-manager] This video is too short for `video-percentage-played`. Reports may be innacurate. For best results, use videos over 5 seconds long. 
<amp-video class="i-amphtml-element i-amph…-built i-amphtml-layout" autoplay="" noaudio="" width="720" height="960" poster="https://amp.dev/static/s…tory_video_dog_cover.jpg" title="Lorem ipsum dolor sit amet, consectetur adipiscing" layout="responsive" i-amphtml-layout="responsive">
log.js:232:7
[video-manager] This video is too short for `video-percentage-played`. Reports may be innacurate. For best results, use videos over 5 seconds long. 
<amp-video class="i-amphtml-element i-amph…-built i-amphtml-layout" autoplay="" noaudio="" width="720" height="960" poster="https://amp.dev/static/s…tory_video_dog_cover.jpg" title="Lorem ipsum dolor sit amet, consectetur adipiscing" layout="responsive" i-amphtml-layout="responsive" preload="auto">
log.js:232:7
[video-manager] This video is too short for `video-percentage-played`. Reports may be innacurate. For best results, use videos over 5 seconds long. 
<amp-video class="i-amphtml-element i-amph…-built i-amphtml-layout" autoplay="" noaudio="" width="720" height="960" poster="https://amp.dev/static/s…tory_video_dog_cover.jpg" title="Lorem ipsum dolor sit amet, consectetur adipiscing" layout="responsive" i-amphtml-layout="responsive" preload="auto">
log.js:232:7
```

### Browser(s) Affected

Firefox

### AMP Version Affected

2302031721000

**Comment by swissspidy** [comment]
Related: #38551
