### ISSUE TITLE
Fix unknown define warnings

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#3870]
```
unknown @define variable FORTESTING
unknown @define variable TYPECHECK_ONLY
```

See e.g. https://travis-ci.org/ampproject/amphtml/builds/141683450

These are, of course, harmless, but really annoying :)

**Comment by erwinmombay** [comment]
so this was the only way to pass in arguments w/o doing any additional work. I could splice this out of the arguments array before passing it into the base constructor call.

**Comment by erwinmombay** [comment]
will it also work if just create dummy vars in our codebase for it to swap out?

**Comment by cramforce** [comment]
Both sound good.

**Comment by erwinmombay** [comment]
fixed through https://github.com/ampproject/amphtml/pull/4174
