### ISSUE TITLE
amp ads units not showing up on non amp pages

### ISSUE THREAD

**Issue by tmleeek** [ampproject/amphtml#38713]
hello every . 

hope you are all good . 

i have applied amp ad units on my website , can you give me an idea what i am doing wrong . 

i have add it to normal html pages and replace the old adsense ad units  . 

please check : 
https://bit.ly/cmsamperror

i attach also picture and heiglhted the location of ad unit : 

<img width="1277" alt="Screenshot 2023-03-14 at 7 34 36 PM" src="https://user-images.githubusercontent.com/1878832/225075154-6e17e5b5-8224-4be1-abb6-a9e8f3bba3bd.png">

**Comment by powerivq** [comment]
I looked at the page. It is not an AMP page and is therefore not in scope for using amp-ad. If you want to offer ads written in AMP, you need to consult with your advertising partner. As there are no further actions needed, I am closing this now.

**Comment by tmleeek** [comment]
well , you kinda too late , i decide not to take amp route for the new version of the website , as its still have a lot of problems , seems like amp is dead
