### ISSUE TITLE
Font Awesome 6.3.0 

### ISSUE THREAD

**Issue by cosiek6** [ampproject/amphtml#38726]
### Description

Hi,
I am trying to put the source code for FontAwesome v6 in Header section in AMP:
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">`

The problem is that Google Search Console for AMP claims this is incorrect and I get error: _'The 'href' attribute in the 'link rel=stylesheet for fonts' tag is set to an invalid value 'https://cdnjs.cloudflare.com/ajax/libs/fon...'_

Therefore, I can see Font Awesome icons, but I am not fine with Google AMP standards.

I also tried to put in Header of AMP page below style amp-custom, but then I do not see the icons.

```
<style amp-custom>
@font-face {
font-family: "Font Awesome 6 Free";
src: url(https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css);}
body { font-family: "Font Awesome 6 Free";content="";}
</style>
```

Can you tell me if this is a bug on your side or if maybe I should correct something? 

Thanks for your help.
Jakub

### Reproduction Steps

1. Put in the Header section of AMP page below code:
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">`
2. Google Search Console throws error: _'The 'href' attribute in the 'link rel=stylesheet for fonts' tag is set to an invalid value 'https://cdnjs.cloudflare.com/ajax/libs/fon...'_

### Browser(s) Affected

Chrome, Firefox

**Comment by erwinmombay** [comment]
is that the usual font awesome cdn url? "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" ?

**Comment by cosiek6** [comment]
Yes, this is mentioned link.

**Comment by erwinmombay** [comment]
working on this, this sprint

**Comment by cosiek6** [comment]
> working on this, this sprint

Thank you for message.
Please let me know once fixed

**Comment by erwinmombay** [comment]
heya i've merged the changes in https://github.com/ampproject/amphtml/pull/39466 , but it might take a while to get to production, most likely 2 weeks

cc @banaag to correct me if i am wrong on timeline
