### ISSUE TITLE
Bubbles appear after the form for screenreader users

### ISSUE THREAD

**Issue by dmochak** [ampproject/amphtml#3872]
If a screen-reader user accesses the page, the bubble indicating that the form is valid or invalid appears after the form. If it appeared near the invalid field, it would be more clear which field is in error.

https://amp-mk-1.herokuapp.com/examples.build/forms.amp.max.html
1. Enter information into one or both of the edit fields on the page.
2. Navigate the page with a screen reader.
3. The information that everything looks good or that there is a problem appears below the form. Having it be located near the item that needs action--either an invalid field or the submit button if all fields are valid--will make it more clear which form control should be used next.

Discovered in Firefox but likely effects all browsers.
Powered by AMP ⚡ HTML – Version 1467182714735

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
