### ISSUE TITLE
Add Neodata Group vendor for amp analytics

### ISSUE THREAD

**Issue by nicshub** [ampproject/amphtml#38722]
### Summary

We are planning to integrate our solution exaudi 
https://www.neodatagroup.com/en/solutions/exaudi-audience-platform/
as amp-analytics vendor.

### Motivation

Our customer already include exaudi tags in web site, but currently they are missing amp traffic, so as a result they have a partial view of the audience analytics.

### Alternative Solutions

Direct request to tracker or use images, but very difficult to implement

### Notifications

/cc @ampproject/wg-approvers
/cc  @ampproject/wg-components

**Comment by erwinmombay** [comment]
@nicshub do y'all still plan to add the configuration?

**Comment by nicshub** [comment]
Hi @erwinmombay , yes it's on going, we have almost completed, we have planned to complete in this month

**Comment by nicshub** [comment]
Hi @erwinmombay we have committed the changes and created the PR https://github.com/ampproject/amphtml/pull/39064
it seems we need an approval, can you help ?

**Comment by erwinmombay** [comment]
@nicshub missed your message. taking a look

**Comment by erwinmombay** [comment]
@nicshub merged. thank you for your patience!
