### ISSUE TITLE
[amp-story] Custom animation prevents video from playing

### ISSUE THREAD

**Issue by danielstockton** [ampproject/amphtml#38733]
### Description

A custom animation will prevent an amp-video from rendering/playing:

https://preview.nws.ai/amp/1288492465/amp-fly-in/ (second page)

An image with the same animation has no problems rendering (third page).

### Reproduction Steps

Minimal test case:

https://preview.nws.ai/amp/1288492465/amp-fly-in/

**Comment by danielstockton** [comment]
I should also mention that the reason we have a custom animation here instead of the AMP fly-in animation is so that we can workaround this other issue: https://github.com/ampproject/amphtml/issues/30790

**Comment by ychsieh** [comment]
I played around with your site a little bit and found out that even without the custom animation, you current html/css code would render the `<amp-video>` with 0 height. Could you try assign a non-zero value to CSS height property of the container of `<amp-video>`? I tried it with your site and the animation works fine with video playing.

**Comment by danielstockton** [comment]
Hi @ychsieh 
It has `height: auto;` not `height: 0`. I've added an additional page at the end with the same video/same height, but without the animation. As you can see, the video renders fine on this page.

**Comment by danielstockton** [comment]
We found the problem, some CSS missing on our side. Sorry for the trouble.
