### ISSUE TITLE
Open redirection (reflected)

### ISSUE THREAD

**Issue by symbol90** [ampproject/amphtml#38731]
### Description

Open redirection vulnerabilities arise when an application incorporates user-controllable data into the target of a redirection in an unsafe way. An attacker can construct a URL within the application that causes a redirection to an arbitrary external domain. This behavior can be leveraged to facilitate phishing attacks against users of the application. The ability to use an authentic application URL, targeting the correct domain and with a valid SSL certificate (if SSL is used), lends credibility to the phishing attack because many users, even if they verify these features, will not notice the subsequent redirection to a different domain.

### Reproduction Steps

https://www-huntress-com.cdn.ampproject.org/c/s/www.huntress.com/blog/3cx-voip-software-compromise-supply-chain-threats?hs_amp=true If you type any site name after /c/s in this link, you will be redirected there directly. (for example https://www-huntress-com.cdn.ampproject.org/c/s/www.malicious.site) If this is not prevented, the attacker can use your domain to redirect the victim to a malicious website.
![1](https://user-images.githubusercontent.com/103177479/229071729-53f7b477-5892-460f-a875-6c9ec3e39fe5.png)
![2](https://user-images.githubusercontent.com/103177479/229071754-74b8c5cc-bf86-4da1-a256-d0bef9d7cc9d.png)
![3](https://user-images.githubusercontent.com/103177479/229071771-7cb7b75d-6053-46c6-b436-f5f89f8720d6.png)

### Relevant Logs

```shell
Remediation

If possible, applications should avoid incorporating user-controllable data into redirection targets. In many cases, this behavior can be avoided in two ways:
Remove the redirection function from the application, and replace links to it with direct links to the relevant target URLs.
Maintain a server-side list of all URLs that are permitted for redirection. Instead of passing the target URL as a parameter to the redirector, pass an index into this list.
If it is considered unavoidable for the redirection function to receive user-controllable input and incorporate this into the redirection target, one of the following measures should be used to minimize the risk of redirection attacks:

The application should use relative URLs in all of its redirects, and the redirection function should strictly validate that the URL received is a relative URL.
The application should use URLs relative to the web root for all of its redirects, and the redirection function should validate that the URL received starts with a slash character. It should then prepend http://yourdomainname.com to the URL before issuing the redirect.
The application should use absolute URLs for all of its redirects, and the redirection function should verify that the user-supplied URL begins with http://yourdomainname.com/ before issuing the redirect.

Reference 
https://cwe.mitre.org/data/definitions/601.html
```

### Browser(s) Affected

Chrome, Firefox

**Comment by banaag** [comment]
This is a duplicate of #38980

**Comment by symbol90** [comment]
You are right, but I reported it first
