### ISSUE TITLE
Urgent : Copy to clipboard not working on AMP cache URL's

### ISSUE THREAD

**Issue by askmeoffersglobal** [ampproject/amphtml#38756]
### Description

Hi , 

We have implemented copy to clipboard and its works fine on mobile and desktop but on AMP cache/viewer urls it does not work . 

Our code snippet : 

     <span on="tap:AMP.copy(text='<?php echo $coupon['ccode']; ?>'),AMP.setState({cp<?php echo $coupon['cid']; ?>:'copied',textcopied : '<?php echo $coupon['ccode']; ?>'}),AMP.navigateTo(url='<?php echo $coupon['coupon_permalink']; ?>&redeem=offer&redeempage=storeoffer')" data-code="<?php echo $coupon['ccode']; ?>" class="coupon-code maincoupon">              
  <span class="hidespan" [class]="textcopied == '<?php echo $coupon['ccode']; ?>'?'hidespan greenback':'hidespan'" [text]="(cp<?php echo $coupon['cid']; ?> == null  || textcopied != '<?php echo $coupon['ccode']; ?>') ?'copy':'copied'">
    Copy
  </span>
  <?php echo substr($coupon['ccode'], 0, 10); ?>
</span>

It works fine but on cache url like : https://www.google.com/amp/s/dev-lussacmediaglobalpvtltd.pantheonsite.io/oyo-coupons/ it does not work 

Please guide me how to fix this up

### Reproduction Steps

It works fine but on cache url like : https://www.google.com/amp/s/dev-lussacmediaglobalpvtltd.pantheonsite.io/oyo-coupons/ it does not work

**Comment by ychsieh** [comment]
The URL is not working. Could you share another URL for me to verify the issue?

**Comment by ychsieh** [comment]
Can't repro so closing this.
