### ISSUE TITLE
Non-XHR demo success page is untitled

### ISSUE THREAD

**Issue by dmochak** [ampproject/amphtml#3875]
https://amp-mk-1.herokuapp.com/examples.build/forms.amp.max.html

1. Fill out the Non-XHR demo (top of page) correctly.
2. select subscribe.
3. Observe that the title bar of the browser is empty.

repros in Firefox/Chrome, likely effects all browsers.

Powered by AMP ⚡ HTML – Version 1467182714735

**Comment by dmochak** [comment]
Whoops: you don't need a screenreader active for this one!

**Comment by rudygalfi** [comment]
Just a demo artifact and not forms specific.
