### ISSUE TITLE
Non-XHR demo success text is an H1 for no reason

### ISSUE THREAD

**Issue by dmochak** [ampproject/amphtml#3877]
https://amp-mk-1.herokuapp.com/form/html/post
 View source and  observe that "Thanks undefined!" is an H1. There is no practical reason for headings on a page this small.

Affects all browsers.
Powered by AMP ⚡ HTML – Version 1467182714735

**Comment by rudygalfi** [comment]
This is just a demo artifact and not specific to forms. A publisher would determine this on their own.
