### ISSUE TITLE
Minecraft Bedrock Smite feature

### ISSUE THREAD

**Issue by antonioLofe** [ampproject/amphtml#38825]
### Description

The bedrock version of the game allows player to have spaces (" ") in their usernames, when I tried to smite a player with spaces in their name it didn't work. I think this is fixable by adding single or double quotes (can't remember) to the player's name before running the command.

By inspecting the Smite button, I can tell that the module and function's name are the next ones: 

data-module="MinecraftModule"
data-method="SmiteByID"

### Reproduction Steps

(in a minecraft bedrock server amp installation) Go to the Console, select a player with spaces in his/her username. select the smite option.

**Comment by erwinmombay** [comment]
Hiya! i think you have the wrong repository
