### ISSUE TITLE
Analytics sampling has biases

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#3886]
See discussion [here](https://github.com/ampproject/amphtml/commit/558a176608421d60852fe33e44bdb5f7c40a40e2#commitcomment-18101814
).

The plan is to introduce a method in [CryptoService](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/crypto-impl.js) api: 
```
/**
 * Returns a uniform hashing of the given string as a float number in range of [0, 1).
 */
function uniform(str) {
  ...
}
```

It'll be shared by amp-analytics and amp-experiment.

@avimehta @cramforce @jridgewell

**Comment by jridgewell** [comment]
Hmm, I always hated statistics.

We can try treating the first four items as an integer in base 256:

```js
// (256 ^ 3), (256 ^ 2), (256 ^ 1), (256 ^ 0)
[          1,        12,         2,       111]
```

That's equivalent to `17,564,271` in decimal.

We can represent any 32bit interger with this, from [0, 4,294,967,295]. And, that's very close to being divisible by 100. So we have an almost perfect distribution with a <sup>1</sup>/<sub>1073741824</sub> (0.000000000931322574615478515625) skew.

**Comment by lannka** [comment]
Sounds good.

2 bytes might be actually enough for our use case. But not sure if there's any fast calculation for this kind of division (dividing a binary by a large decimal).

**Comment by avimehta** [comment]
if the number is going to be `[0, 1)`, how does `[0,255]/2.55` not result in a uniform distribution? Seems like we could go with the simpler and easier solution.

Analytics can multiply by 100 and do sampling while amp-experiment can multiply by 1000.

**Comment by lannka** [comment]
Ideally what we need is a continuously uniform distributed float.
Dividing a integer is a reasonable simulation, but the result is discrete. 255 doesn't provide enough granularity. We need a large number.

**Comment by jridgewell** [comment]
> But not sure if there's any fast calculation for this kind of division (dividing a binary by a large decimal).

What do you mean?

> if the number is going to be [0, 1), how does [0,255]/2.55 not result in a uniform distribution? 

I ignored the `[0, 1)` part because of floating point math. You can do `[1, 12, 2, 111] % 100 === 71` without any precision loss.

**Comment by amphtml-team** [comment]
On Fri, Jul 1, 2016 at 3:22 PM, Justin Ridgewell <notifications@github.com>
wrote:

> But not sure if there's any fast calculation for this kind of division
> (dividing a binary by a large decimal).
>
> What do you mean?
>
Ha, I think it is actually a problem of converting a binary fraction number
to decimal fraction number.

Assume we pick the 2  leading ints of the input, and try to normalize it to
a float in range [0, 1)

float = (256 * a + b) / (256 ^ 2)

This way, we convert everything from binary form to decimal before doing
the division. When number goes large, the division becomes costly (think
about if we want 4 ints).

A more efficient way is to perform the division in binary form (it's no
cost, just moving the fraction point), then convert the result binary
fraction to to decimal fraction.

**Comment by cramforce** [comment]
#GoogleInterviewQuestion
