### ISSUE TITLE
Lazy load closure sha384 lib when browser native Crypto API is not available

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#3888]
This is a further enhancement to #3690
It reduces binary size of amp-analytics by 9K under most of browsers.
As a trade-off, it introduces a HTTP round trip for some old browsers, such as IE11 and Android 4.x system browser.

Plan:
- Have a local implementation of base64()
- Strip out base64 code from closure sha384 lib
- Serve the closure lib in CDN (@cramforce any example how do we host such a file?)
- Lazy load it in CryptoService code

@jridgewell

**Comment by jridgewell** [comment]
😁🎆

**Comment by cramforce** [comment]
Steps:

- Build custom binary. See `function buildAlp` in gulpfile.js
- Write a more generic version of `calculateExtensionScriptUrl` to get the URL.
- Insert script and attach load handler.
- Ping @erwinmombay to smooth over the rollout issues we have every time we introduce a new file :)

Maybe we can still support IE11 directly with some extra work.

This is definitely worth the effort. `amp-analytics` is one of the most used extensions.

**Comment by ericlindley-g** [comment]
Slotting in backlog for now, but please correct/update as needed

**Comment by jridgewell** [comment]
Can we prioritize this for for next? This is a 9kb (4kb gzipped) savings for Safari and Chrome.

**Comment by rudygalfi** [comment]
Bumped into Next. @jridgewell assigned you.

**Comment by cramforce** [comment]
Assigned to @lannka. Lets to this as a "on the side" project. It'll be much easier after @dvoytenko's work for more direct late loading of JS lands.   #4025

**Comment by lannka** [comment]
Fixed by #7006
