### ISSUE TITLE
CSS only lightbox using :target

### ISSUE THREAD

**Issue by sriramkrish85** [ampproject/amphtml#3890]
Lets try 

https://developer.mozilla.org/en-US/docs/Web/CSS/%3Atarget

as a CSS only alternative for amp-lightbox

**Comment by sriramkrish85** [comment]
@cramforce @dvoytenko @jridgewell

**Comment by dvoytenko** [comment]
We enabled `:target` for this specific reason in the pre-sidebar days. But what's the reason for this now?

**Comment by sriramkrish85** [comment]
@dvoytenko if :target can do this , can we make lightbox take advantage of this? or may be anything that needs a mask?

**Comment by dvoytenko** [comment]
To take advantage of this we simply need to set hash string to the ID of the lightbox. That, however, will cause some jumps in iOS. Overall, there's no huge benefit from this. It might be more interesting to support a hash parameter in AMP to automatically open the lightbox. E.g. when `#target=lightbox1` is specified we may automatically open lightbox with `id=lightbox1`.
