### ISSUE TITLE
Unable to set the linkers flag to false in amp-analytics

### ISSUE THREAD

**Issue by devanshug** [ampproject/amphtml#38924]
### Description

WebEngage is an analytics vendor, and we've a build-in configuration in amp project - https://github.com/ampproject/amphtml/blob/main/extensions/amp-analytics/0.1/vendors/webengage.json
We've provided linkers in the configuration to allow cross domain syncing. In the linkers configuration, we've explicitly enabled the linker(Refer Script below) for all, who use WebEngage amp-analytics integration.
 ```
 "linkers": {
    "_we_linker": {
      "enabled": true,
      "ids": {
        "we_luid": "${clientId(we_luid)}"
      },
      "proxyOnly": false
    }
  },
```
But due to some requirement, one of our clients wanted to disable the linker for their websites.
(Please find details in the reproduction steps.)

By this, we anticipated that linkers would be disabled for that client but unfortunately, the linkers are still getting appended in their links. We want to confirm if this is the correct way of disabling all linkers or not. If not, then what is the correct way to disable the linkers if a vendor has explicitly enabled it in their configuration

### Reproduction Steps

Based on the documentation provided, we suggested them to override the enabled flag and set it for false as shown below
```
<amp-analytics type="webengage" id="webengage">
  <script type="application/json">
    {
      "linkers" : {
        "enabled": false
      }
    }
  </script>
</amp-analytics>
```

### Browser(s) Affected

Chrome, Firefox, Safari, Edge, UC Browser

**Comment by erwinmombay** [comment]
@devanshug do you happen to have a production site we can look at ?

**Comment by devanshug** [comment]
@erwinmombay 

Please check this site: https://www-hindustantimes-com.cdn.ampproject.org/v/s/www.hindustantimes.com/amp?amp_gsa=1&amp_js_v=a9&usqp=mq331AQIUAKwASCAAgM%3D
We have disabled the linkers as mentioned in the description and reproduction steps.

Once we click any link, we can see that we_linkers are attached in the URI: `_we_linker=1*r1h5xp*we_luid*V09CclhGWWU3TXZET3pZN0lhUFBYcjExZFpSaEFFN2t1ZkM4cXloeVVlOTQyOUxwNWJKelBYc2hnd2UySXVabw.. in query params`
![image](https://github.com/ampproject/amphtml/assets/4804497/386e41d7-8f3c-4a09-b87e-27e1204f2356)
