### ISSUE TITLE
[Accessibility issue] Numbers and Emoticons are accepted as valid values in name field

### ISSUE THREAD

**Issue by A11yravi** [ampproject/amphtml#3893]
![amp form name field bug](https://cloud.githubusercontent.com/assets/20249603/16536629/0e328460-3fa9-11e6-8b2f-18857d9bf25e.png)
## Short description of your issue:
Numbers and Emoticons are accepted as valid input values in Name field

Test URL: https://amp-mk-1.herokuapp.com/examples.build/forms.amp.max.html

Pre-requisite: Turn on Talkback from Settings >> Accessibility >>Talkback

## How do we reproduce the issue?

Steps to reproduce:
1. Logon to Nexus 9 and open chrome browser
2. Open test URL provided above
3. Linear navigate till your name editbox and double tap.
4. Input numbers and emoticons in name and navigate to email field

Actual results: 
Numbers and Emoticons are accepted as valid values in name field

Expected result: 
Numbers and Emoticons should not be accepted as valid values.

## What browsers are affected?
OS : Android 6.0
Device: Nexus 9 (tablet)
Browser: Chrome (Version 51.0.2704.81)

Please find attached snapshot for reference.

**Comment by rudygalfi** [comment]
@mkhatib should confirm, but I think this is OK since the validation logic is very simple and accepts these characters in the forms demo, so this is working as intended.

**Comment by mkhatib** [comment]
Yes. We don't really do anything special here so yes this works as intended.
