### ISSUE TITLE
`layoutCount_` and `layoutAttemptCount_` duplicate

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#3895]
To fix #3806, I introduce a `layoutAttemptCount_` value to custom-element. so that loading indicator will be turned off and disabled after `layoutCallback` being called regardless of success or failure.  #3821

However `layoutAttemptCount_` is somehow a duplicate of `layoutCount_`. The only reason that prevents me from adding `layoutCount_` by one after layout fails is that we need to check `layoutCount_ == 1` to call `firstLayoutCompleted()`. Can I have a `isFirstLayoutComplete` flag and merge `layoutCount_` `layoutAttemptCount_`? 

Also I find that we don't really care the exact value for `layoutCount_` when it's greater than 1. Can we change it to a boolean value like `isLayoutCalled` .

@dvoytenko @jridgewell

**Comment by dvoytenko** [comment]
@zhouyx I think the numeric value is better in this case and it's totally appropriate to have a boolean `isFirstLayoutComplete` flag.

**Comment by zhouyx** [comment]
#3821
