### ISSUE TITLE
Worker DOM integration is broken

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#39016]
### Description

There was a P0 detected as of last week when we upgraded worker dom (https://github.com/ampproject/amphtml/pull/38853). We need to fix the integration between the two projects.

### Reproduction Steps

Upgrade worker DOM to `0.34.0`. `AMP.getState` calls do not return the stored value.

Further info can be found in https://github.com/ampproject/amphtml/issues/38967

**Comment by erwinmombay** [comment]
possibly related https://github.com/ampproject/amphtml/issues/38979

**Comment by powerivq** [comment]
Can confirm https://github.com/ampproject/worker-dom/commit/a6bcd6f515de985c6dc48e013e57757eb6b8d962 is the culprit. Reverting this will make everything work. Need to dig further to figure out what went wrong in that PR.
