### ISSUE TITLE
shows error on my AMP page

### ISSUE THREAD

**Issue by eGuidezhan** [ampproject/amphtml#39026]
### Description

Google Dashboard shows error on my AMP page

### Reproduction Steps

It shows that the referenced AMP url is not AMP

I wonder why? how to solve this problem?

This is my website: https://www.tech-sparks.com/zigbee/

![image](https://github.com/ampproject/amphtml/assets/134616703/1606966e-b7e4-4ad3-b595-b41f1668070c)

Thanks

**Comment by erwinmombay** [comment]
@eGuidezhan would you mind checking again. there was a reported crawl issue for AMP pages and it seems to have been fixed based on https://twitter.com/JohnMu/status/1662169467843903492 this

**Comment by erwinmombay** [comment]
Closing this as this should be resolved and is out of scope for this repository. feel free to re-open for additional information and queries. thank you
