### ISSUE TITLE
Intent To Implement: NeodataGroup ad networks for amp-ads

### ISSUE THREAD

**Issue by neodatagroup** [ampproject/amphtml#3915]
Support for the Neodata Groups ad-networks (adagio, 4w, 4wppn) added to <amp-ad> elements.
Sent a pull request
https://github.com/ampproject/amphtml/pull/3914
Thanks,
Salvo Nicotra (CTO)

**Comment by adelinamart** [comment]
I see the PR for this was closed. Feel free to reopen if there's still work in progress. Thanks.
