### ISSUE TITLE
<amp-state> When Orange and Apple buttons are clicked, state variable's value is not set to an image URL.  

### ISSUE THREAD

**Issue by dzarmanova** [ampproject/amphtml#39166]
### Description

Script can use state variables and binding to affect the area outside the amp-script component. When a button is clicked, state variable's value should be set to an image URL. That state variable is bound to the src attribute of an amp-image. But in this case when Orange and Apple buttons are clicked, state variable's value is not set to an image URL.  

Note: on Desktop Chrome, Safari and FF in responsive design mode and on actual iphone/android devices switching to Orange image is possible but only after pressing Apple button. But you can't switch back to an Apple image.

### Reproduction Steps

1. Open the link https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-script&format=websites&_gl=1*1kgsbzt*_ga*YW1wLW83ZWlnQnRSNnV0d0lWS2dEWG1YSmc.&preview=true and scroll down till you see Apple and Orange buttons
2. Press Orange and Apple buttons back and force

Actual result: Sometimes buttons are not responsive. Switching to Orange image is still possible but only after pressing Apple button. But you can't switch back to an Apple image.
https://photos.app.goo.gl/bjrCiFBHsyPyVgTi9

This issue is not reproducible on Stable

Expected result: When buttons are clicked, state variable's value is set to an image URL

Environment:
Device: Macbook Pro, iPhone XR, Pixel 3a XL
Browser: Chrome, Safari, FF

### Browser(s) Affected

Chrome, Firefox, Safari

### AMP Version Affected

2306082008000

**Comment by powerivq** [comment]
Confirming that this is fixed by applying https://github.com/ampproject/worker-dom/pull/1146
