### ISSUE TITLE
deprecate and remove amp-redbull-player

### ISSUE THREAD

**Issue by Fazod** [ampproject/amphtml#39174]
### Summary
there is an open request to deprecate the amp-redbull-player at https://github.com/ampproject/amphtml/pull/38558

we've verified that only [www.redbull.com](http://www.redbull.com/) and amp.redbull.com are the only websites that use amp-redbull-player.

@wklopf is the one who opened the PR and is the owner of the component

### Motivation
redbull has decided to move away from the AMP approach and to remove the last fragment of this move (the actual component) from the repository

### Impact on Existing Users
None besides the redbull websites

### Intent-to-Deprecate (I2D) Issue

https://github.com/ampproject/amphtml/issues/38686

### Rollout Plan

As there are no active users of the feature (as confirmed in the linked PR's discussion), the feature can immediately be removed

### Alternative Implementation

as the original component seems to have been a specialized one off where the code is mostly analytics, this component can be reimplemented by amp-iframe or one of the video components.

### Notifications

/cc @ampproject/wg-approvers

**Comment by erwinmombay** [comment]
@Fazod sounds good. would y'all like to remove it?

**Comment by Fazod** [comment]
@erwinmombay yessir, can we reuse the linked PR for it?

**Comment by erwinmombay** [comment]
@Fazod yep. that sounds good. just need to make sure it is rebased from main to not get any conflicts

**Comment by erwinmombay** [comment]
@Fazod also. Just as a heads up, we will start with the deprecation process, then start with the removal process.

**Comment by Fazod** [comment]
> @Fazod yep. that sounds good. just need to make sure it is rebased from main to not get any conflicts

The PR was rebased @erwinmombay

**Comment by erwinmombay** [comment]
This issue should be resolved
