### ISSUE TITLE
<amp-story> share button is not responsive and share menu is not appearing on the screen

### ISSUE THREAD

**Issue by dzarmanova** [ampproject/amphtml#39181]
### Description

Share button is not responsive and the share menu is not appearing on the screen. Issue observed on Desktop Safari in Responsive design mode and on actual devices iPhone (safari browser) and Android (chrome browser)

### Reproduction Steps

1. Use test link https://000615502.deployed.codepen.website/ or playground link https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fguides-and-tutorials%2Fintegrate%2Fembed-stories.example.1.html%3Fformat%3Dwebsites&_gl=1*11kcbdb*_ga*YW1wLUNFRzJQOXdZN0VmSmlqYzBVMHZmc3c.
2. Tap on top right "Share" button

Actual result: Share button is not responsive 
https://photos.app.goo.gl/5qDe9jH4QvZaNt5RA

Expected result: When share button is tapped the share menu should appear on the screen

### Browser(s) Affected

Chrome, Safari

### Device(s) Affected

iPhone XR, Pixel 3a XL

**Comment by erwinmombay** [comment]
@ychsieh could you take a look at this when you get some time. thanks
