### ISSUE TITLE
About using the <amp-ad-custom> tag - Who can use it?

### ISSUE THREAD

**Issue by ChemicalDroid** [ampproject/amphtml#39192]
I recently came across the amp-ad-custom format. But there is not much documentation. If I understand correctly, the amp-ad-custom tag can be used to manage a custom ad network on a website, leveraging the speed capabilities of the AMP standard. By reading the documentation. I tried the following:

I need an endpoint that would be the ad server placed directly in the amp-ad-custom tag. If my server is https://seletronic.com.br/ad-server/, it would look something like this:

`<amp-ad-custom width="300" height="250" src="https://seletronic.com.br/ad-server/">`

This same https://seletronic.com.br/ad-server/ should respond with JSON containing the configurations and path to a valid AMP4ADS ad page. It should also include the required headers. Here's an example of the ad server response:

Example PHP header:

$origin = origin_validator();

```
header("Access-Control-Allow-Origin: $origin");
header("Access-Control-Expose-Headers: AMP-Access-Control-Allow-Source-Origin, AMP-Access-Control-Allow-Source-Origin, amp-ad-response-type, AMP-Ad-Template-Extension");
header("AMP-Access-Control-Allow-Source-Origin: $origin");
header("AMP-Ad-Response-Type: template");
header("AMP-Ad-Template-Extension: amp-mustache");
header("Content-Type: application/json; charset=utf-8");
```

Response from the page with the URL of the AMP4ADS ad page:

`{ "data": { "impression_id": "c9996325e618c7726496dc1eb79a23d7"},"templateUrl": "https:\/\/seletronic.com.br\/ad-server\/ad\/lanka.php" }`

Example of the ad page that the server points to, and its content, which is considered valid by the AMP4ADS validator:

```
<!doctype html>
<html ⚡4ads>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,minimum-scale=1">
  <style amp4ads-boilerplate>body{visibility:hidden}</style>
  <script async src="https://cdn.ampproject.org/amp4ads-v0.js"></script>
  <script async custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.2.js"></script>
  <script async custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>
</head>
<body>
  <div>Ad template example</div>
  <template type="amp-mustache">
    <amp-img src="https://validator.ampproject.org/logo-blue.svg" width="250px" height="150px" layout="responsive"></amp-img>
  </template>
  <amp-img src="https://validator.ampproject.org/logo-blue.svg" width="250px" height="150px" layout="responsive"></amp-img>
  <amp-analytics type="googleanalytics"></amp-analytics>
</body>
</html>
```

When checking the page where I install the <amp-ad-custom> tag, it makes a request to the ad server at https://seletronic.com.br/ad-server/, which shows the URL of the ad page. After that, it seems to attempt to load the cached version directly from the AMP cache servers, which returns a 404 error:

https://seletronic-com-br.cdn.ampproject.org/ad/s/seletronic.com.br/ad-server/ad/lanka.php

I want to know why AMP doesn't cache the ad and it doesn't load. Is this available to everyone, or just big advertising companies?

**Comment by erwinmombay** [comment]
@powerivq do you know much about amp-ad-custom?

**Comment by erwinmombay** [comment]
@powerivq friendly ping

**Comment by powerivq** [comment]
It is intended to be useable by anyone. I think you are doing it almost right. I note that https://seletronic.com.br/ad-server/ad/lanka.php returns the following headers:

`max-age: 0` and `expires: now`

I think they prevent AMP cache from caching your page. You need to fix these issues.

**Comment by ChemicalDroid** [comment]
@powerivq Thanks for the answer. I already changed the cache times to 1 day but it still doesn't work. In the console you can see that the AMP ad tag makes a request for the AMP cache ad, but it returns 404.

```
cache-control: max-age=86400, public
date: Wed, 19 Jul 2023 20:07:14 GMT
expires: Thu, 20 Jul 2023 20:07:14 GMT
```

**Comment by powerivq** [comment]
Actually, I think it is because of this
```
at this stage, domains need to be allowlisted manually in AMP Cache to experiment with the feature.
```

(see https://amp.dev/documentation/components/amp-ad-custom#amphtml-ad-template-creation)

Do you have your final domain name set? I can ask for including your domains.

**Comment by ChemicalDroid** [comment]
@powerivq Thank you very much.
My domains are:
```
seletronic.com
seletronic.com.br
```

**Comment by powerivq** [comment]
@banaag Can you help them allowlist these two domains?

**Comment by powerivq** [comment]
@ChemicalDroid We have checked the system. Unfortunately, due to not having any ad network onboard using this (since 2019), it is not really usable at its current state. We will suggest implementing a fast fetch extension (if amp4ads is important to you), or a regular ad integration.

**Comment by powerivq** [comment]
Closing this issue as alternative solution being provided.
