### ISSUE TITLE
<amp-analytics> gtag on AMP does not send custom dimensions

### ISSUE THREAD

**Issue by roberto-bon** [ampproject/amphtml#39195]
### Description

Hi,
since we used GTAG on the AMP pages everything works with the exception of the custom dimension. We noticed that AMP does not send custom dimensions. 

### Reproduction Steps

We are using the following code to define the variables on AMP pages.

```
<amp-analytics id="gtag" type="gtag" data-credentials="include">
	<script type="application/json">
		{
			"vars":{
				"gtag_id": "UA-XXXXXX-X",
				"config": {
					"UA-XXXXXX-X": {
						"groups": "default",
						"custom_map": {
							"dimension1": "xxxxxx",
							"dimension2": "xxxxxx"
						}
					}
				}
		         }
			"triggers": {
				...
                         }
		}
	</script>
</amp-analytics>

```

Here is an example: https://ricette.giallozafferano.it/Tiramisu-di-pandoro-e-frutti-di-bosco.html?google-amp=1

**Comment by grantlee75** [comment]
Hi @zikas ,
if i try your code i don't see the dimension's parameter in the payload of the call to collect.js.
Do you have a working demo to see?

Thanks a lot!

**Comment by zikas** [comment]
Here's an [amp playground link](https://playground.amp.dev/#share=PCEtLQogICMjIEludHJvZHVjdGlvbgoKVGhlIGBhbXAtYW5hbHl0aWNzYCBlbGVtZW50IGNhbiBiZSB1c2VkIHRvIG1lYXN1cmUgYWN0aXZpdHkgb24gYW4gQU1QIGRvY3VtZW50LiBDdXJyZW50bHksIGBhbXAtYW5hbHl0aWNzYCBzdXBwb3J0cyBkaWZmZXJlbnQga2luZHMgb2YgZXZlbnRzOgoKKiBQYWdldmlldwoqIEFuY2hvciBDbGlja3MKKiBUaW1lcgoqIFNjcm9sbGluZwoqIEFNUCBDYXJvdXNlbCBjaGFuZ2VzCiogRm9ybQoKVGhpcyBzYW1wbGUgZGVtb25zdHJhdGVzIHdoaWNoIGV2ZW50cyBjYW4gYmUgbWVhc3VyZWQgYW5kIGhvdyB0aGV5IGNhbiBiZSBjb25maWd1cmVkLiBGb3IgYSBjb21wbGV0ZSBvdmVydmlldyBvZiBhbGwgYXZhaWxhYmxlIG9wdGlvbnMgYW5kIHBhcmFtZXRlcnMsIGhhdmUgYSBsb29rIGF0IHRoZSBbb2ZmaWNpYWwgZG9jdW1lbnRhdGlvbl0oL2NvbnRlbnQvYW1wLWRldi9kb2N1bWVudGF0aW9uL2NvbXBvbmVudHMvcmVmZXJlbmNlL2FtcC1hbmFseXRpY3MtdjAuMS5tZCkuCi0tPjwhLS0gLS0+CjwhZG9jdHlwZSBodG1sPgo8aHRtbCDimqEgbGFuZz0iZW4iPgo8aGVhZD4KPG1ldGEgY2hhcnNldD0idXRmLTgiPgogICAgPHRpdGxlPmFtcC1hbmFseXRpY3M8L3RpdGxlPgogICAgPHNjcmlwdCBhc3luYyBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwLmpzIj48L3NjcmlwdD4KICAgIDwhLS0gIyMgU2V0dXAgLS0+CiAgICA8IS0tICBJbXBvcnQgdGhlIGBhbXAtYW5hbHl0aWNzYCBjb21wb25lbnQgaW4gdGhlIGhlYWRlci4gLS0+CiAgICA8c2NyaXB0IGFzeW5jIGN1c3RvbS1lbGVtZW50PSJhbXAtYW5hbHl0aWNzIiBzcmM9Imh0dHBzOi8vY2RuLmFtcHByb2plY3Qub3JnL3YwL2FtcC1hbmFseXRpY3MtMC4xLmpzIj48L3NjcmlwdD4KICAgIDwhLS0KICAgIFdlIG5lZWQgYGFtcC1pZnJhbWVgIHRvIGVtYmVkIGFuIGFuYWx5dGljcyBkYXNoYm9hcmQuCiAgLS0+CiAgICA8bGluayByZWw9ImNhbm9uaWNhbCIgaHJlZj0iaHR0cHM6Ly9hbXAuZGV2L2RvY3VtZW50YXRpb24vZXhhbXBsZXMvY29tcG9uZW50cy9hbXAtYW5hbHl0aWNzL2luZGV4Lmh0bWwiPgogICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCI+ICAgCiAgCTxzdHlsZSBhbXAtYm9pbGVycGxhdGU+PC9zdHlsZT4KICA8bm9zY3JpcHQ+PHN0eWxlIGFtcC1ib2lsZXJwbGF0ZT4KICAgICAgICBib2R5IHsKICAgICAgICAgIC13ZWJraXQtYW5pbWF0aW9uOiBub25lOwogICAgICAgICAgLW1vei1hbmltYXRpb246IG5vbmU7CiAgICAgICAgICAtbXMtYW5pbWF0aW9uOiBub25lOwogICAgICAgICAgYW5pbWF0aW9uOiBub25lOwogICAgICAgIH0KICAgICAgPC9zdHlsZT48L25vc2NyaXB0PgogIDwvaGVhZD4gIAogIDxib2R5PgogICAKICAKICAgCiAgICA8YW1wLWFuYWx5dGljcyB0eXBlPSJndGFnIiBkYXRhLWNyZWRlbnRpYWxzPSJpbmNsdWRlIj4KICAgICAgPHNjcmlwdCB0eXBlPSJhcHBsaWNhdGlvbi9qc29uIj4KICAgICAgICB7CiAgInZhcnMiOiB7CiAgICAiZ3RhZ19pZCI6ICJVQS0xMTExLTEiLAogICAgImNvbmZpZyI6IHsKICAgICAgIlVBLTExMTEtMSI6IHsKICAgICAgICAiY3VzdG9tX21hcCI6IHsKICAgICAgICAgICJkaW1lbnNpb24xIjogImNvbG9yIiwKICAgICAgICAgICJtZXRyaWMxIjogImFnZSIsCiAgICAgICAgICAiY29udGVudF9ncm91cDEiOiAic2l6ZSIKICAgICAgICB9LAogICAgICAgICJjb2xvciI6ICJncmVlbiIKICAgICAgfQogICAgfQogIH0sCiAgInRyaWdnZXJzIjogewogICAgInVhX2V2ZW50X2xldmVsIjogewogICAgICAib24iOiAidmlzaWJsZSIsCiAgICAgICJ2YXJzIjogewogICAgICAgICJhZ2UiOiAzMCwKICAgICAgICAiY29sb3IiOiAicmVkIiwKICAgICAgICAic2l6ZSI6ICJYTCIsCiAgICAgICAgImV2ZW50X25hbWUiOiAiY29udmVyc2lvbiIsCiAgICAgICAgImRpbWVuc2lvbjMiOiAidGVzdCIsCiAgICAgICAgInNlbmRfdG8iOiAiVUEtMTExMS0xIgogICAgICB9CiAgICB9CiAgfQp9CiAgICAgIDwvc2NyaXB0PgogICAgPC9hbXAtYW5hbHl0aWNzPgogIAo8L2JvZHk+PC9odG1sPg==) that shows different ways to send custom metrics and dimensions. 

Note, this is Universal Analytics, for GA4 the approach is slightly different

**Comment by grantlee75** [comment]
Ok, thank you, the playground it's fine.
What's the  the approach for dimensions in GA4?

**Comment by zikas** [comment]
I've updated the playground page to include GA4 configuration.
In short, there's no need for `custom_map` anymore. Any field (`color`, `size` in the example) will be automatically sent as custom parameters. 
Note that you need to make sure to define your custom dimensions and metric in the GA4 UI before you can start using them. More on this here https://support.google.com/analytics/answer/10075209?hl=en#zippy=

**Comment by erwinmombay** [comment]
closing issue. please feel free to open if you have more questions
