### ISSUE TITLE
🐛 Google Analytics 4 Related Bug: Where is the implementation?

### ISSUE THREAD

**Issue by savvyrobert** [ampproject/amphtml#39219]
### Description

Guys, it's the 11th hour and there has been no communication or meaningful guides. The work arounds are atrocious. 

Been on the verge of getting away from AMP. This might be the end. Google clearly doesn't even talk to Google.

### Reproduction Steps

amp-analytics does not support GA4

**Comment by th91vi** [comment]
They released the official tag for AMP pages last 28 of June. Some reported here: https://github.com/ampproject/amphtml/issues/24621#issuecomment-1610286610

They also released official docs: https://support.google.com/analytics/answer/13707678

**Comment by erwinmombay** [comment]
heya @savvyrobert `amp-analytics` with `type=gtag` should work out of the box and integrate with GA4.
