### ISSUE TITLE
Clicky Web Analytics transport issue

### ISSUE THREAD

**Issue by avclicky** [ampproject/amphtml#3922]
## Short description

Analytics data for Clicky users are sometimes being sent via the xhrpost machinery. Because the destination doesn't reply with the correct headers, it generates a CORS violation and the request fails.

## Proposed fix

Changing the object ANALYTICS_CONFIG in ./extensions/amp-analytics/0.1/vendors.js such that clicky.transport.xhrpost is set to false. It's currently set to true.

**Comment by rudygalfi** [comment]
Do you want to send a pull request for this fix?

**Comment by avclicky** [comment]
Yes, sorry, didn't see the notification of activity on this thread until now. The pull request is #4659.
