### ISSUE TITLE
 I2I: Allowing add data-json when premiumads type for amp-auto-ads

### ISSUE THREAD

**Issue by rochapablo** [ampproject/amphtml#39250]
### Summary

The tag `<amp-auto-ads type="premiumads"` needs allow the user to add data-json attribute.

### Motivation

Once `data-json` it's accepted by the `amp-auto-ads type="premiumads"`, the user will be able to track their pages.

### Alternative Solutions

Since `type="premiumads"` it's a specific type of setup for some users, there's no alternative solution.

### Notifications

/cc @ampproject/wg-approvers

**Comment by powerivq** [comment]
Feature was merged.
