### ISSUE TITLE
Screenshots in the readme file.

### ISSUE THREAD

**Issue by airfusion64** [ampproject/amphtml#39285]
### Description

There should be some screenshots in the readme file as it looks great to attach some screenshots of the website for anyone watching only the code on github.

### Alternatives Considered

No alternatives

**Comment by airfusion64** [comment]
Please assign this task to me and I will add screenshots and small gifs in the readme to make it more attractive.

**Comment by erwinmombay** [comment]
@airfusion64 could you elaborate more or provide an example of what you mean by screenshot in this case?

**Comment by erwinmombay** [comment]
closing for now but do reopen this when you can provide additional information
