### ISSUE TITLE
AMP Stories and WCAG 2.1 - Zooming disabled

### ISSUE THREAD

**Issue by Pateriack** [ampproject/amphtml#39289]
### Description

Amp story js scripts will automatically modify the viewport meta tag to add `user-scalable=no`.

When running stories through accessibility checking tools, I am consistently seeing this reported as a problem.

I understand that this would be useful to prevent the user from accidentally zooming in when trying to use gestures to control the story, but I am worried about the implications. Can we be open to lawsuits as a result of not being compliant?

Why is this necessary? Can we not allow zooming?

### Reproduction Steps

Run any amp story through an accessibility checker and you will see this issue.

For example: https://www.accessibilitychecker.org/audit/?website=https%3A%2F%2Flocalhood.com%2Fstories%2Fab32b880-22ca-4532-92e1-0786cc8a6e4a%2Ftest&flag=us

**Comment by ychsieh** [comment]
From eng perspective, enabling this would cause difficulties in recognizing other more important gestures, e.g. swipe to the next story, or swipe up to see page attachments.

From UX perspective, let me quote from our UX expert Hong here:
"the story reading experience is more like a native UX even in web environment. With a fullscreen content presentation up front, we don't really want to introduce gestures that intentionally getting the layout lost. If A11y is a top challenge, they can access the phone a11y setting to increase font size in general. Not sure pin-zoom for readability here is super efficient."
