### ISSUE TITLE
Image lightbox: allow swiping between images in the same lightbox

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#393]
All images for a specific lightbox can be found by running:
```
document.querySelector('[on=tap:$lightBoxId]')
```

These images can be stringed together into a simple slideshow.

**Comment by mkhatib** [comment]
@aghassemi has this been implemented through the new lightbox changes? Close this?

**Comment by aghassemi** [comment]
yeah it is the main point of lightbox 2.0, let's close in favour of #4152
