### ISSUE TITLE
IncrementX Vendor still not register in https://cdn.ampproject.org/v0/amp-ad-0.1.js CDN for <amp-ad>

### ISSUE THREAD

**Issue by Prebid-Vertoz** [ampproject/amphtml#39307]
### Description

Hello AMPHTML Team,
Our new vendor (**IncrementX**) is successfully merged into main branch but still IncrementX vendor not added into https://cdn.ampproject.org/v0/amp-ad-0.1.js CDN.So can you please tell us reason for  not added **IncrementX** vendor in CDN or something missing from our end.

### Reproduction Steps

Hello AMPHTML Team,
Our new vendor (**IncrementX**) is successfully merged into main branch but still IncrementX vendor not added into https://cdn.ampproject.org/v0/amp-ad-0.1.js CDN.So can you please tell us reason for  not added **IncrementX** vendor in CDN or something missing from our end.

**Comment by powerivq** [comment]
Checked the PR: https://github.com/ampproject/amphtml/pull/39237 It was merged last week, and therefore needs to wait for the release to happen (see https://amp.dev/documentation/guides-and-tutorials/learn/spec/release-schedule) That PR will also be labelled when pushed into beta/prod.
