### ISSUE TITLE
amp-story-shopping display issue

### ISSUE THREAD

**Issue by AutadeJS** [ampproject/amphtml#39309]
### Description

With amp-story-shopping, when product details are displayed in bottom sheet, if product title is longer than 14 characters, the price display is spoiled as shown in attached snapshot.
![amp-story-shopping-bug](https://github.com/ampproject/amphtml/assets/32076611/1e713198-1926-4f63-b6c8-f6e01fc30688)

### Reproduction Steps

Add a product with long title and check

**Comment by Paramjeet81** [comment]
****what is the GitHub?

**Comment by ychsieh** [comment]
If you build it using proper `amp-story-shopping-attachment` config, this shouldn't happen. The `font-size` of the title is defined in em [here](https://github.com/ampproject/amphtml/blob/main/extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.css#L124) so it should be responsive. I changed `examples/amp-story/amp-story-shopping.html` and you can see what it looks like with a narrow screen and a super long product title in PDP:
![image](https://github.com/ampproject/amphtml/assets/1697814/7a2de192-6f78-40a3-a2f9-90bce45495ea)
