### ISSUE TITLE
Google is caching the desktop page and not the AMP page

### ISSUE THREAD

**Issue by thinkdifferent** [ampproject/amphtml#39306]
### Description

Frequently but not always (there seems to be no pattern in this) Google is caching the desktop version of our page and not the amp version.
When this happens we noticed our news is not visible on Google news, we get a blank page

An example I collected 2 days ago: https://www.google.com/amp/s/www.ilmeteo.it/notizie/meteo-caldo-stop-e-in-arrivo-una-gran-rinfrescata-temperature-gi-anche-di-13c-gli-aggiornamenti-083238

Our amp pages have the same URL with /amp at the and, so the cache should have been:
https://www.google.com/amp/s/www.ilmeteo.it/notizie/meteo-caldo-stop-e-in-arrivo-una-gran-rinfrescata-temperature-gi-anche-di-13c-gli-aggiornamenti-083238/amp

A more recent example: 

 https://www-ilmeteo-it.cdn.ampproject.org/v/s/www.ilmeteo.it/notizie/meteo-agosto-sono-arrivate-le-previsioni-per-le-vacanze-guardate-cosa-pu-accadere-entro-ferragosto-133446?amp_js_v=0.1

### Reproduction Steps

https://www-ilmeteo-it.cdn.ampproject.org/v/s/www.ilmeteo.it/notizie/meteo-agosto-sono-arrivate-le-previsioni-per-le-vacanze-guardate-cosa-pu-accadere-entro-ferragosto-133446?amp_js_v=0.1

this is not visible on google news.

The cache page should have been the amp version, ending with /amp

### Browser(s) Affected

Chrome, Firefox, Safari

### OS(s) Affected

Bot Android and Iphone

**Comment by powerivq** [comment]
Looking at your page. I notice this

```
<link rel="alternate" media="only screen and (max-width: 640px)" href="https://www.ilmeteo.it/notizie/meteo-caldo-stop-e-in-arrivo-una-gran-rinfrescata-temperature-gi-anche-di-13c-gli-aggiornamenti-083238/amp" /> 
```

As a first step, you can change it or add another link, according to https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/discovery:

```
<link rel="amphtml"  href="https://www.ilmeteo.it/notizie/meteo-caldo-stop-e-in-arrivo-una-gran-rinfrescata-temperature-gi-anche-di-13c-gli-aggiornamenti-083238/amp" /> 
```

**Comment by thinkdifferent** [comment]
> Looking at your page. I notice this
> 
> ```
> <link rel="alternate" media="only screen and (max-width: 640px)" href="https://www.ilmeteo.it/notizie/meteo-caldo-stop-e-in-arrivo-una-gran-rinfrescata-temperature-gi-anche-di-13c-gli-aggiornamenti-083238/amp" /> 
> ```
> 
> As a first step, you can change it or add another link, according to https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/discovery:
> 
> ```
> <link rel="amphtml"  href="https://www.ilmeteo.it/notizie/meteo-caldo-stop-e-in-arrivo-una-gran-rinfrescata-temperature-gi-anche-di-13c-gli-aggiornamenti-083238/amp" /> 
> ```
> 
> This would inform search engines the link to the AMP version.

It was present, we tried to remove it to see if it could solve the problem.

**Comment by thinkdifferent** [comment]
We reinserted the amphtml metatag and the problem is still present.

But maybe we found the cause: it seems to be te javascript redirect from the desktop page to the amp page if the user agent is mobile.
Adding this redirect to other sections of our website caused the problem of desktop page cache by google also on that section.

**Comment by powerivq** [comment]
@thinkdifferent I am not familiar with how the search part works, but that is an interesting finding. Thank you for that report!
