### ISSUE TITLE
Use Crypto for CID Generation

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#3930]
Use `Crypto#getRandomBytes` to generate our CID instead of SHA-384. We can fallback to the old way if `Crypto` isn't available.

Ties in with https://github.com/ampproject/amphtml/issues/3888

**Comment by cramforce** [comment]
The current algorithm is here:
https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/cid-impl.js#L363

It is using `getRandomValues` if available. We could remove a single hashing in this case, but this only optimizes the creation path, not anything else. The hashing of the base id is required in the fallback path to destroy potential user data in fallback values.

**Comment by ericlindley-g** [comment]
Slotting in backlog for now, but please correct/update as needed

**Comment by cramforce** [comment]
Already implemented
