### ISSUE TITLE
Error: this.attemptChangeHeight is not a function

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#3933]
Get this error when trying to resize amp-ad
![image](https://cloud.githubusercontent.com/assets/5419904/16630156/00fd4eec-436e-11e6-9d1c-3c7d3f6ea420.png)

**Comment by cramforce** [comment]
Haven't checked, but that might be due to the new A4A code.

@tdrl @bobcassels @keithwrightbos
