### ISSUE TITLE
Make URLs configurable at runtime

### ISSUE THREAD

**Issue by jrf0110** [ampproject/amphtml#3934]
Notably:

* 3p.ampproject.net
* d-*.ampproject.net
* cdn.ampproject.org
* amp-error-reporting.appspot.com

This is following discussion from an email thread with @cramforce @erwinmombay @dknecht.

I suppose we could simply replace all of the URL strings sprinkled throughout the codebase with references to corresponding keys in `window.AMP_CONFIG`. I'm somewhat new to the codebase, but if that's the way forward, then I'd be happy to contribute.

**Comment by cramforce** [comment]
For implementation strategy:

Create an ES6 module that exposes these values and which itself reads from `window.AMP_CONFIG`.

**Comment by ericlindley-g** [comment]
@cramforce FYI: slotting in the Backlog for now, but please feel free to correct/update as needed

**Comment by cramforce** [comment]
@ericlindley-g @jrf0110 is already working on this. See PR above.

**Comment by ericlindley-g** [comment]
Thanks @cramforce  — slotting into Current

**Comment by ericlindley-g** [comment]
Scratch that—putting into "Pending 3P Implementation"
