### ISSUE TITLE
🐛 Google Analytics 4 Related Bug: 

### ISSUE THREAD

**Issue by si-deep** [ampproject/amphtml#39346]
### Description

We are facing issue:

Access to fetch at `'https://www.googletagmanager.com/gtag/amp?__amp_source_origin=<WEBSITE_URL>'` from origin `'<WEBSITE_URL>'` has been blocked by CORS policy: No `'Access-Control-Allow-Origin'` header is present on the requested resource. If an opaque response serves your needs, set the request's mode to `'no-cors'` to fetch the resource with CORS disabled.

This is because of the browser is sending `Sec-Fetch-Mode: cors` with POST Request sent by at the time of tracking initialization. As per our R&D, we found that we can't manipulate values of `Sec-*` headers (that browser sends). Tested in multiple browsers also. Same issue. Tracking is not working with GA4 in AMP. Only possible solution seems that as https://www.googletagmanager.com/gtag/amp is not having any such CORS headers, the POST request to this URL can be handled by setting header in AMP Framework `mode: no-cors` in POST request.

For tracking our sample request data in AMP page's source code is as follows:
`<amp-analytics type="gtag" data-credentials="include" id="ampAnalyticsHomePage"> <script type="application/json">{"vars":{"gtag_id":"<GA4_MEASUREMENT_ID>","config":{"<GA4_MEASUREMENT_ID>":{"groups":"default"}}},"triggers":{"trackAmpNavigationBuyNow":{"on":"click","selector":"a#trackAmpNavigationBuyNow","request":"event","vars":{"event_name":"buy_online_url","event_category":"home_page","event_action":"buy_online_url","event_label":"1422"}},"trackAmpWhatsappBusiness":{"on":"click","selector":"a#trackAmpWhatsappBusiness","request":"event","vars":{"event_name":"whatsapp_business","event_category":"home_page","event_action":"whatsapp_business","event_label":"1422"}},"trackAmpHeaderClickToCall":{"on":"click","selector":"a#trackAmpHeaderClickToCall","request":"event","vars":{"event_name":"click_to_call","event_category":"home_page","event_action":"click_to_call","event_label":"1422","event_value":"0"}},"trackAmpHeaderClickToCallCls":{"on":"click","selector":"a.trackAmpHeaderClickToCallMultiple","request":"event","vars":{"event_name":"click_to_call","event_category":"home_page","event_action":"click_to_call","event_label":"1422","event_value":"0"}}}}</script> </amp-analytics>`

### URL where we can debug and reproduce the problem

https://restaurants.pizzahut.co.in/amp/pizza-hut-ph-janpath-new-delhi-pizzerias-connaught-place-new-delhi-259252/Home

### Reproduction Steps

Just visit above URL and `inspect elements` and in `Console` tab you will see these errors.

### Relevant Logs

```shell
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.googletagmanager.com/gtag/amp?__amp_source_origin=https%3A%2F%2Frestaurants.pizzahut.co.in. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 400.

And

[AmpAnalytics ampAnalyticsHomePage] Error rewriting configuration:  https://www.googletagmanager.com/gtag/amp Error: XHR Failed fetching (https://www.googletagmanager.com/...): NetworkError when attempting to fetch resource.​​​
    l index.js:43
    m index.js:98
    createExpectedError log.js:304
    po xhr-impl.js:98
```

### Browser(s) Affected

Chrome, Firefox

**Comment by erwinmombay** [comment]
heya @si-deep so i checked with the Google Tagging team and this seems to be a known issue on their side. It seems there is a 10k limit currently on the payload as previously described in https://github.com/ampproject/amphtml/issues/32911 . I am not sure if the limit will be increased so I would advise reducing the payload for now
