### ISSUE TITLE
amp-ad: doesn't collapse when there's no content

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#3936]
`noContentHandler_` is called in `amp-ad-3p-impl.js`. 
When `amp-ad-3p-impl` collapse by calling `attemptChangeHeight`, it won't trigger a resize on its parent `amp-ad`. Thus `amp-ad` does not collapse correctly.

**Comment by cramforce** [comment]
CC @ampproject/a4a

Related to #3133

**Comment by michaelkleber** [comment]
@tdrl

**Comment by zhouyx** [comment]
My current approach is:
1. Set `<amp-ad-3p-impl>` with `layout=fill`.
2. replace current resize functions with parents' resize.

**Comment by zhouyx** [comment]
#3944

**Comment by zhouyx** [comment]
issue solved by #3962 @dvoytenko
