### ISSUE TITLE
Error thrown in chrome parsing `amp-worker.js`

### ISSUE THREAD

**Issue by dickie81** [ampproject/amphtml#39381]
### Description

We have just noticed an error while parsing `amp-worker.js` introduced in this commit https://github.com/ampproject/amphtml/commit/54c040015323502c18d65b31a03aec69b98dd0b3 specifically around line 101.

```
    if (self.trustedTypes && self.trustedTypes.createPolicy) {
      const policy = self.trustedTypes.createPolicy(
        'amp-worker#fetchUrl',
        policy
      );
    }
```   

As you can see just reading the code policy will be undefined.

![image](https://github.com/ampproject/amphtml/assets/2070959/232575c8-89ef-47f3-b096-53d2f036c855)

### Reproduction Steps

I can't list the site where this is occurring on as it is commercially sensitive. But if you paste the following code in the browser console it will demonstrate the general idea.
```
const x = 0;

if (true) {
  const x = alert(x);
}
```

### Browser(s) Affected

Chrome, Safari

### AMP Version Affected

2308042153000

**Comment by guitavano** [comment]
I have the same issue here, since today's morning.

**Comment by dickie81** [comment]
dupliclate of https://github.com/ampproject/amphtml/issues/39380
