### ISSUE TITLE
Elements built out of order on every reload

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#3939]
When we introduced the change of how we build "ready" elements, elements are not always being built in the exact order with every reload. This was brought up and we didn't see a clear problem of out of order element build. 

One issue that I am seeing now is with the automatically generated incremental IDs `AMP_${counter}` that resources assign to elements that doesn't have an ID.

Because of that different page loads might generate different element IDs. 

Before that change the order we build and assign these counter IDs was guaranteed to be the same on every load.

Does AMP make (or want to make) any guarantees of automatically generated IDs for elements across reloads?

This is problematic for elements that rely on a consistent ID across page reloads. For example, dismissal logic for `amp-user-notification` rely on the ID of the element if that ID changes AMP can't guarantee correct dismissal logic. This can be mitigated by enforcing publishers to provide an ID for these elements - which currently **tries** to enforce but fails to because the element is given a dynamic ID before build is called. This might be a different problem - enforcing publisher provided ID, filed a separate issue for this #3938.

**Comment by cramforce** [comment]
Maybe we should stop giving a dynamic ID or not name it `id`. We don't look these up using `document.getElementById`, do we?

**Comment by mkhatib** [comment]
I don't believe so, any idea why we assign dynamic IDs currently?

**Comment by cramforce** [comment]
Just to make debugging easier.

**Comment by dvoytenko** [comment]
I likewise believe this is only for debugging and should go.

**Comment by jridgewell** [comment]
Closed by #6132.
