### ISSUE TITLE
Missing "Tap to Next" Message on Swipe for Integrated Web Stories in AMP

### ISSUE THREAD

**Issue by ashmohd** [ampproject/amphtml#39401]
### Description

When using the Web Story format on the web, a "Tap to Next" message is displayed when users attempt to swipe through the story. This message indicates that swiping is not supported in Web Stories, and users need to tap on the screen to proceed to the next part of the story.

However, when the Web Story is integrated into a non-AMP Page, the "Tap to Next" message does not appear when users swipe. This behavior is inconsistent with the experience on the regular web and can confuse users who are accustomed to the "Tap to Next" prompt.

ref :https://amp.dev/documentation/guides-and-tutorials/integrate/embed-stories-nonamp

### Reproduction Steps

url1:https://www.mysmartprice.com/mobile/apple-iphone-15-plus-msp23034?version=B
Go to the section : Apple iPhone 15 Plus Review in Images
Try to swipe the image, there is no message.

Message appearing correctly here:
url2:https://www.mysmartprice.com/gear/web-stories/iphone-15-15-plus-may-get-huge-camera-upgrades/
Try to swipe the image it says "Tap next", "Tap back" 

### Browser(s) Affected

Chrome

### OS(s) Affected

Android, IOS

### Device(s) Affected

Many Devices checked

**Comment by ychsieh** [comment]
This is because swiping in a viewer means either swiping up to see page attachment or swiping left/right to see neighbor stories. See code here: https://github.com/ampproject/amphtml/blob/main/extensions/amp-story/1.0/amp-story.js#L916-L923. This is to not mess up with the gesture recognizers in viewer context.

Also the UX is fairly common across different platforms that offers story experiences, e.g. Snapchat, Instagram. It would be better to err on the side of ensuring the critical gestures work fine.

**Comment by newmuis** [comment]
Shouldn't it be possible to not have the `cap=swipe` capability defined on the viewer?  I think embedders can opt to just not include this, as the semantics are exactly what you described: horizontal swiping will go to another story.

**Comment by ashmohd** [comment]
> This is because swiping in a viewer means either swiping up to see page attachment or swiping left/right to see neighbor stories. See code here: https://github.com/ampproject/amphtml/blob/main/extensions/amp-story/1.0/amp-story.js#L916-L923. This is to not mess up with the gesture recognizers in viewer context.
> 
> Also the UX is fairly common across different platforms that offers story experiences, e.g. Snapchat, Instagram. It would be better to err on the side of ensuring the critical gestures work fine.

**Comment by ashmohd** [comment]
@ychsieh 
This feature should behave same on webstory integration pages as well.

In below example when user tried to swipe a Help Text is appearing.
https://github.com/ampproject/amphtml/assets/4936437/6aafafde-351a-4583-bf60-9ee8ba52753c

Second example when we have integrated this web story to other page, on swipe help text is not appearing, this behaviour may lead to confusion to user.
https://github.com/ampproject/amphtml/assets/4936437/7c17f118-4621-4853-8e46-4551d729dfe1
