### ISSUE TITLE
AMP Error using 2 amp-custom style tags in Next.js

### ISSUE THREAD

**Issue by divrawat2** [ampproject/amphtml#39449]
### Description

I am making web stories in next.js fetching data data from mongoDb. When I give the amp-custom style ie. <style amp-custom>CSS Here</style> then 2 <style amp-custom> tags are present in head tag of the page causing error that page is not AMP and because it has 2 <style amp-custom>. 

In short there is duplication of <style amp-custom> tags in head tag of Next.js page.

Although when I dont give any CSS using <style amp-custom> then there is no error but I can't apply styles to my web story. Also there is always an empty <style amp-custom></style> always present in the head tag of the page.

### Reproduction Steps

Probably in Next.js in the head tag of a page  there are 2 <style amp-custom>, out of which 1 is mine's styled tag with custom CSS defined and other is the empty one.

<head>

<style amp-custom>My CSS here </style>   //This is the tag from which I wrote the CSS
<style amp-custom> </style>               //Empty tag

</head>

You can also seethe problem there - https://github.com/vercel/next.js/issues/36105

### Relevant Logs

```shell
/web-stories/[slug]  error  

The tag 'style amp-custom' appears more than once in the document.  

https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml/#stylesheets
```

### Browser(s) Affected

All

### OS(s) Affected

All

### Device(s) Affected

All

### AMP Version Affected

2308242321000

**Comment by ychsieh** [comment]
This seems to be a next.js related issue.
