### ISSUE TITLE
Uncaught Error: Value of data-loading-strategy should be a float number in range of [0, 3], but got prefer-viewability​​​

### ISSUE THREAD

**Issue by Prebid-Vertoz** [ampproject/amphtml#39521]
### Description

When we set the attribute 'data-loading-strategy' is 'prefer-viewability' then it works correctly for Ad viewability.But it contineously shows the errors 'Uncaught Error: Value of data-loading-strategy should be a float number in range of [0, 3], but got prefer-viewability​​​'.
Can you please share the solution for Perfect Viewability.

![image](https://github.com/ampproject/amphtml/assets/23209608/95310cb6-4b04-4b1f-86b4-c42ffbc5788d)

### Reproduction Steps

When we set the attribute 'data-loading-strategy' is 'prefer-viewability' then it works correctly for Ad viewability.But it contineously shows the errors 'Uncaught Error: Value of data-loading-strategy should be a float number in range of [0, 3], but got prefer-viewability​​​'.
Can you please share the solution for Perfect Viewability.
![image](https://github.com/ampproject/amphtml/assets/23209608/4a05518e-f6d6-4b79-8c0f-3326a727667a)

**Comment by Prebid-Vertoz** [comment]
Hello AMP Team,
Any update on it?

**Comment by MrJithil** [comment]
As per the implementation, `data-loading-strategy` here for `amp-ad` will support either float values between from 0 to 3 or the `prefer-viewability-over-views` .
So, can we try with the value `prefer-viewability-over-views` instead of the one you tried?

**Comment by Prebid-Vertoz** [comment]
@MrJithil 
If we have used the **prefer-viewability-over-views** then it fetch the API calls before 2 feeds.
is there any attribute/solution available for API calling on same feed?

**Comment by MrJithil** [comment]
Can you try empty value?

**Comment by Prebid-Vertoz** [comment]
> Can you try empty value?

Yes we tried empty value but still Ad script is getting fire 2 calls before the Ad position.

**Comment by erwinmombay** [comment]
@powerivq can you triage this? thanks

**Comment by powerivq** [comment]
What does "perfect viewability" mean here? `prefer-viewability-over-views` does not mean firing the ads call upon page load. Is this what you are looking for?

**Comment by Prebid-Vertoz** [comment]
> What does "perfect viewability" mean here? `prefer-viewability-over-views` does not mean firing the ads call upon page load. Is this what you are looking for?

If we have use '**prefer-viewability**' attribute then ads call fire on perfect feed, but showing above errors.Is there any solution for firing ads call on perfect Ad feed?

**Comment by powerivq** [comment]
> > What does "perfect viewability" mean here? `prefer-viewability-over-views` does not mean firing the ads call upon page load. Is this what you are looking for?
> 
> If we have use '**prefer-viewability**' attribute then ads call fire on perfect feed, but showing above errors.Is there any solution for firing ads call on perfect Ad feed?

`prefer-viewability` isn't a valid value. I am confused as to what is not working if you set the value to `3`?

**Comment by Prebid-Vertoz** [comment]
> > > What does "perfect viewability" mean here? `prefer-viewability-over-views` does not mean firing the ads call upon page load. Is this what you are looking for?
> > 
> > 
> > If we have use '**prefer-viewability**' attribute then ads call fire on perfect feed, but showing above errors.Is there any solution for firing ads call on perfect Ad feed?
> 
> �`prefer-viewability` isn't a valid value. I am confused as to what is not working if you set the value to `3`?

As AMP fires Ads script before the Ad is been displayed , We just want a value which fires Ad script when the Ad page is viewed by the user

**Comment by powerivq** [comment]
@Prebid-Vertoz This is not supported, unless you use a fast fetch ads extension. Using a fast fetch extension would allow the ad requests to be made earlier in the pageload lifecycle.

**Comment by powerivq** [comment]
Closing this issue for now since no actions can be taken. Feel free to reopen if there is more info.
