### ISSUE TITLE
amp-ad: getting width and height directly from supplied attributes, not computed values

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#3953]
https://github.com/ampproject/amphtml/blob/master/src/3p-frame.js#L51

We are getting width and height directly from supplied attributes here. this won't work if a value is not provided by user, also we cannot ensure those are correct numbers . Should we use a computed value instead?

**Comment by zhouyx** [comment]
@cramforce @dvoytenko

**Comment by cramforce** [comment]
I believe those values should just not be set if they were not supplied.

**Comment by dvoytenko** [comment]
@cramforce To clarify, in a case of:
```
<amp-ad layout=responsive width="200" height="150">
```

The actual `width` and `height` at layout time could be different for the same aspect ratio. E.g. `400` and `300` respectively.

What's the expectation here? Should we forward `200,150` or `400,300`?

**Comment by cramforce** [comment]
This is what the user asked for. The inner iframe can measure its dimensions if it wants to know or just use responsive design.

**Comment by dvoytenko** [comment]
Sounds good. Then it's a non-action. Although, I'd still prefer not to send around `NaN` values. So, perhaps the fix is to just update `getLengthUnits` to return `undefined` instead? /to @zhouyx

**Comment by cramforce** [comment]
+1

**Comment by lannka** [comment]
Seems the work is done.
