### ISSUE TITLE
https://www.google.com/amp/s/hpdaasroi.ext.hp.com/SEMUTWIN/

### ISSUE THREAD

**Issue by sriwulan11** [ampproject/amphtml#39570]
### Description

This domain uses AMP and is being misused as a phishing site for other people to help get banned on this domain

### Reproduction Steps

https://www.google.com/amp/s/hpdaasroi.ext.hp.com/SEMUTWIN/

**Comment by erwinmombay** [comment]
dupe of https://github.com/ampproject/amphtml/issues/39572
