### ISSUE TITLE
🐛 Google Analytics 4 Related Bug: 

### ISSUE THREAD

**Issue by sriwulan11** [ampproject/amphtml#39571]
### Description

This domain uses AMP and is being misused as a phishing site for other people to help get banned on this domain

### URL where we can debug and reproduce the problem

https://www.google.com/amp/s/hpdaasroi.ext.hp.com/SEMUTWIN/

### Reproduction Steps

PLEASE REMOVE THIS AMP DOMAIN FROM GOGLE

### Browser(s) Affected

Chrome, Firefox, Safari, Edge, UC Browser

**Comment by erwinmombay** [comment]
duplicate.
