### ISSUE TITLE
AMP USED BY PHISING WEBSITE

### ISSUE THREAD

**Issue by sriwulan11** [ampproject/amphtml#39598]
### Description

This domain uses AMP and is being misused as a phishing site for other people to help get banned on this domain

Reproduction Steps
https://www.google.com/amp/s/www.lp-pao.go.th/Main60/webboard/assets/plupload/products/situs-judi-online

### Reproduction Steps

https://prnt.sc/N3sNYQY7XMBe

### Relevant Logs

```shell
https://www.google.com/amp/s/www.lp-pao.go.th/Main60/webboard/assets/plupload/products/situs-judi-online
```

### Browser(s) Affected

Chrome, Firefox, Safari, Edge, UC Browser

**Comment by powerivq** [comment]
It looks like you are trying to report a site. You can do it through https://safebrowsing.google.com/safebrowsing/report_phish/?hl=en and it is not controlled by AMP.
