### ISSUE TITLE
image layout = "responsive" causes massive width expansion

### ISSUE THREAD

**Issue by JustinPinner** [ampproject/amphtml#396]
When we specify an image with a width of 79 and height of 66 and _don't_ specify `layout = "responsive"` we see this;
![screen shot 2015-10-02 at 10 58 38](https://cloud.githubusercontent.com/assets/690395/10244179/745ac4fe-68f5-11e5-8411-e75d35fb71ec.png)

But when we add `layout = "responsive"`, it does this;
![screen shot 2015-10-02 at 11 04 20](https://cloud.githubusercontent.com/assets/690395/10244190/829f6448-68f5-11e5-97c7-bb137c01ca39.png)

It seems that img.-amp-fill-content is stretching out to 20058px x 66px

**Comment by erwinmombay** [comment]
hey @JustinPinner, just a friendly ping :)

we would love to take a closer look at your issue. do you mind sending us a direct link to the article or some sort of snippet/sample that replicates the issue? Thanks!

**Comment by JustinPinner** [comment]
Apologies. I need to track down the article this example came from, as only some have the contributor image shown this way. Will update when I find it (or another).

**Comment by erwinmombay** [comment]
@JustinPinner thanks!

**Comment by dvoytenko** [comment]
Let's close this for now and reopen if this resurfaces.
