### ISSUE TITLE
Provide a delegated upgrade approach for elements with mutliple implementations

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#3961]
/cc @cramforce @zhouyx @bobcassels

This approach is becoming more frequent with the following examples:

- amp-carousel splitting into slides and scroller
- amp-ad splitting into amp-ad-3p and amp-a4a
- a host of v2 implementations triggered by experiment

A better approach would be to support redirected implementation via a separate callback as part of the runtime. This way we'll avoid a number of patterns that are either hard to test or error-prone such as redirection via constructor or via build callback.

**Comment by cramforce** [comment]
CC @ampproject/a4a
