### ISSUE TITLE
🌸 Cherry-pick request for https://github.com/ampproject/amphtml/pull/39611 into 2311082010000

### ISSUE THREAD

**Issue by oyj9109** [ampproject/amphtml#39620]
### Issue (P0 Bug)

b/309402813

### Pull Request(s)

#39611 ([f85f4f7](https://github.com/ampproject/amphtml/commit/f85f4f72bd752af8a4fb541fcbca24556697fc3e))

### AMP Version(s)

2310301456000

### Channels

Beta / Experimental

### Formats

Websites

### Justification

Buyflow O2 is not supported for swg (subscriptions-project), so we needed to disable it by providing an additional url parameter. The fix within swg.js (https://github.com/subscriptions-project/swg-js/pull/3204) is not synced in amp, so our end-users coming through amp is experiencing errors in buyflow. This is not a P0 but we want to ship it out as soon as possible to minimize product impact.

### Verification Steps

1. Go to demo site: https://scenic-2017.appspot.com/1.amp
2. Click "Subscribe with Google" button at the bottom.
3. Select an offer to initiate buyflow
4. Confirm the presence of url parameter: "swg"

### Notifications

/cc @ampproject/release-on-duty @ampproject/wg-approvers @ampproject/cherry-pick-approvers

**Comment by thomaspan** [comment]
LGTM

**Comment by erwinmombay** [comment]
switching from version 2310301456000 to 2311082010000 since we about to promote 2310301456000 to production

**Comment by erwinmombay** [comment]
This fix was cherry picked to `2311082010000` and is our current 1%/optin experimental/beta
