### ISSUE TITLE
amp-analytics#13: 'undefined' is not a function (evaluating 'Number.isNaN(parseFloat(e))')"

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#3963]
https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/amp-analytics.js#L411

getting large number of errors of this, looked like somebody started using sampling.

looked at a few user agents and they seem to be on ios 7/8 which might not have these es2015 features yet.

/to @avimehta

**Comment by avimehta** [comment]
Looking into this.

**Comment by erwinmombay** [comment]
@avimehta let me know if you need more information

**Comment by erwinmombay** [comment]
`Number.isFinite` probably also needs to be polyfilled

**Comment by jridgewell** [comment]
Ooo, how'd that get through? There's `window.isNaN` and `window.isFinite` which are _almost_ the same as the `Number.*` variants (which are ES6 only), but the must be proceeded by a `typeof X === 'number'`.

**Comment by avimehta** [comment]
would that work on ios 7/8?

**Comment by avimehta** [comment]
@erwinmombay I can also remove usage of sampleOn from googleanalytics config if that will reduce the risk of this release getting through. lmk.

**Comment by erwinmombay** [comment]
not sure if that's necessary. do you know why this suddenly cropped up in yesterdays release when this code has existed for a while now? just trying to figure out how it got turned on suddenly

**Comment by avimehta** [comment]
I started using it in google analytics with #3744. Before this, no one used that config afaik.

**Comment by erwinmombay** [comment]
@avimehta that makes sense! thanks
