### ISSUE TITLE
LCP too high for Web Stories

### ISSUE THREAD

**Issue by AutadeJS** [ampproject/amphtml#39658]
### Description

Some Web Stories have too high LCP even though its being served from a CDN (Cloudflare). Examples: 

- https://www.collegedekho.com/stories/iim-amritsar-expected-cat-cutoff-2023
- https://www.collegedekho.com/stories/iim-udaipur-mba-average-salary-package

Please suggest a solution to improve Core Web Vitals values.

### Reproduction Steps

Test https://www.collegedekho.com/stories/iim-amritsar-expected-cat-cutoff-2023 in Core Web Vitals tool

**Comment by ychsieh** [comment]
Seems like the LCP is back to green?

**Comment by AutadeJS** [comment]
Testing on https://pagespeed.web.dev/ still shows it red.

**Comment by ychsieh** [comment]
I am still seeing green on LCP on the Web Vital extension: 
<img width="565" alt="Screenshot 2024-02-07 at 18 06 42" src="https://github.com/ampproject/amphtml/assets/1697814/117f7b5e-454e-444d-b73b-7b92aac3af49">

For https://pagespeed.web.dev/, seems like it falls back to all user data collected on your origin, but the LCP is still green.

**Comment by rodrigofglima** [comment]
For today, the LCP its red

https://pagespeed.web.dev/analysis/https-selectgame-gamehall-com-br-web-stories-god-of-war-veja-quanto-tempo-leva-pra-completar-os-jogos-da-serie/l4d67q4qfl?form_factor=mobile

The webstory its hard optimized in images, with webp and the first image (for example) have ONLY 20 kb.

https://selectgame.gamehall.com.br/web-stories/god-of-war-veja-quanto-tempo-leva-pra-completar-os-jogos-da-serie/

**Comment by ychsieh** [comment]
From pagespeed, it is showing aggregated web vitals for your entire origin, which indicates all of your pages have poor web vitals. I suspect it is more of the speed of the cdn you are using for all your assets. This isn't something that the AMP runtime can fix.
