### ISSUE TITLE
ValidationErrors with AMP 

### ISSUE THREAD

**Issue by Shahanfarid** [ampproject/amphtml#3966]
Hello, 
    Please help me to fix the following errors,
AMP validation had errors:
aD @ validator.js:412(anonymous function)
 @ validator.js:423
f.Aa @ validator.js:336
UB @ validator.js:339
JB.Ed @ validator.js:
339IB @ validator.js:334
validator.js:412

 http://www.football5star.com/berita/top-3-berita-bola-hari-ini-dwigol-griezmann-bawa-prancis-kalahkan-jerman/77884/amp/:87:0 The tag 'script' is disallowed except in specific 
forms.aD @ validator.js:412(anonymous function) @ validator.js:424
f.Aa @ validator.js:336
UB @ validator.js:339
JB.Ed @ validator.js:339
IB @ validator.js:334

Kindly assist me is sorting this out, as my webmaster tool is showing allot of errors. 
my url is www.football5star.com

Please walk through the following steps for reporting an issue about AMP:

**Comment by Gregable** [comment]
You have custom javascript (`<script>` tags) on your page, which is not valid AMP. Take a look at the [AMP docs](https://www.ampproject.org/docs/get_started/about-amp.html) to learn more.

**Comment by Shahanfarid** [comment]
Dear Sir,
   Thank you for your prompt response, I'm trying to figure it out but i've failed many times, could you kindly explain in more details, even AMP document isn't showing me clearly where am i doing wrong?
/amp shows no error
but when i do /amp/#development=1 i see the errors i've sent you.

Thank you once again.


Sent from Mailbird [http://www.getmailbird.com/?utm_source=Mailbird&amp;utm_medium=email&amp;utm_campaign=sent-from-mailbird]
On 07/09/16 12:36:08 AM, Greg Grothaus <notifications@github.com> wrote:
You have custom javascript (<script> tags) on your page, which is not valid AMP. Take a look at the AMP docs [https://www.ampproject.org/docs/get_started/about-amp.html] to learn more.

**Comment by Gregable** [comment]
The following script tag is at the bottom of your document:

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-67899169-1', 'auto');
  ga('send', 'pageview');

</script>
```

You'll need to remove that in order to validate.

**Comment by Shahanfarid** [comment]
Well noted. Thank you so much. 

I need to remove Google Analytics code then. 

I will do the required and revert back if i have any issue, thanks allot

Sent from Mailbird [http://www.getmailbird.com/?utm_source=Mailbird&utm_medium=email&utm_campaign=sent-from-mailbird]
On 07/09/16 12:43:09 AM, Greg Grothaus <notifications@github.com> wrote:
The following script tag is at the bottom of your document:
<script> (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){ (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m) })(window,document,'script','https://www.google-analytics.com/analytics.js','ga'); ga('create', 'UA-67899169-1', 'auto'); ga('send', 'pageview'); </script>
You'll need to remove that in order to validate.

**Comment by Shahanfarid** [comment]
Thank you. Your support has helped me to fix the issue. I do see allot of errors in Webmaster tools 

1. The attribute 'src' in tag 'amp-analytics extension .js script' is set to the invalid value 'https://cdn.ampproject.org/v0/amp-analytics-0.1.js' defer='defer'.


2. The tag 'script' is disallowed except in specific forms
.


3. The mandatory tag 'amphtml engine v0.js script' is missing or incorrect.




4.The tag 'amp-twitter extension .js script' is missing or incorrect, but required by 'amp-twitter'.

Is there anything i need to add in my html to fix these errors.

Thanks.




Sent from Mailbird [http://www.getmailbird.com/?utm_source=Mailbird&amp;utm_medium=email&amp;utm_campaign=sent-from-mailbird]
On 07/09/16 12:48:30 AM, Shahan Farid <shahan.farid@yahoo.com> wrote:
Well noted. Thank you so much. 

I need to remove Google Analytics code then. 

I will do the required and revert back if i have any issue, thanks allot

Sent from Mailbird [http://www.getmailbird.com/?utm_source=Mailbird&amp;utm_medium=email&amp;utm_campaign=sent-from-mailbird]
On 07/09/16 12:43:09 AM, Greg Grothaus <notifications@github.com> wrote:
The following script tag is at the bottom of your document:
<script> (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){ (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m) })(window,document,'script','https://www.google-analytics.com/analytics.js','ga'); ga('create', 'UA-67899169-1', 'auto'); ga('send', 'pageview'); </script>
You'll need to remove that in order to validate.

**Comment by Gregable** [comment]
Yes, these are validation errors. They will need to be addressed. If you are using the AMP Wordpress plugin (https://wordpress.org/plugins/amp/), you may want to raise issues at that URL rather than here. This is primarily for issues with AMP itself, not a support channel for developing with AMP. There is also some useful discussion over at [StackOverflow](stackoverflow.com/questions/tagged/amp-html)
