### ISSUE TITLE
Validator spec used in AMP Validator Chrome Extension is stale

### ISSUE THREAD

**Issue by westonruter** [ampproject/amphtml#39661]
### Description

Originally reported at https://github.com/ampproject/amp-wp/issues/7679, a user found that the AMP Validator extension for Chrome is flagging the use of `fetchpriority` on an `img`. This was added recently to the AMP spec. Nevertheless, attempting to validate the same URL via the AMP Playground finds no issues: https://playground.amp.dev/?url=https%3A%2F%2Fkhabarsatta.com%2Fmp-news%2Fmp-weather-update-rain-expected-in-18-districts-on-november-26-western-disturbance-active-over-iran%2F%3Famp

### Reproduction Steps

Add an `img` to an AMP document with `fetchpriority=high` attribute. Look at the AMP Validator extension in Chrome.

### Browser(s) Affected

Chrome

**Comment by erwinmombay** [comment]
@powerivq @banaag could one of y'all take a look at this

**Comment by powerivq** [comment]
Update pending store review.

**Comment by powerivq** [comment]
Verified new release on chrome web store.
