### ISSUE TITLE
Tag <amp-video-iframe> not works on Safari and Chrome in iOS (version 12.3 or higher)

### ISSUE THREAD

**Issue by efrensalado** [ampproject/amphtml#39676]
### Description

I am trying to implement amp-video-iframe like the example in the AMP documentation, on Android (Chrome) the example works correctly, but, on devices running iOS 12.3 and above, when the example is loaded, the video tries to load the resource, but it doesn't play the src video (as it can't be loaded) and the console shows some errors related to the amp-iframe.js file
![simulator_screenshot_E5C49C72-B373-4EB2-ABF1-1C2E9A4CCEAA](https://github.com/ampproject/amphtml/assets/39703278/41ffecec-44c5-4cc5-8e2e-962cfe938a9e)

Related issue: [issue closed](https://github.com/ampproject/amphtml/issues/22406)

### Reproduction Steps

[Example in official documentation](https://amp.dev/documentation/examples/components/amp-video-iframe/preview/)
Open in iOS (Chrome or Safari)

In debug mode, the file `amp-iframe.o.1.mjs` in the line 690, the code that is trying to set the attribute sandbox, is setting the value `allow-presentation`
<img width="1410" alt="screenshot-with-error" src="https://github.com/ampproject/amphtml/assets/39703278/858c72c3-29c2-4518-ba15-6f9931e9e734">

### Relevant Logs

```shell
Error while parsing the 'sandbox' attribute: 'allow-presentation' is an invalid sandbox flag.
amp-iframe.js:826
[Error] Not allowed to load local resource: blob://nullhttps//amp.dev/ww.mjs.map
[Error] Not allowed to request resource
[Error] Cannot load blob://nullhttps//amp.dev/ww.mjs.map due to access control checks.
[Error] Blocked a frame with origin "https://preview.amp.dev" from accessing a frame with origin "https://amp.dev". Protocols, domains, and ports must match.
	(anonymous function) (amp-intersection-observer-polyfill-0.1.js:2:6019)
	(anonymous function) (amp-intersection-observer-polyfill-0.1.js:2:6058)
	(anonymous function) (amp-intersection-observer-polyfill-0.1.js:2:14502)
	(anonymous function) (amp-intersection-observer-polyfill-0.1.js:2:5171)
	b (amp-intersection-observer-polyfill-0.1.js:2:5527)
	g (amp-intersection-observer-polyfill-0.1.js:2:4643)
	(función anónima) (amp-intersection-observer-polyfill-0.1.js:2:15405)
	f (amp-intersection-observer-polyfill-0.1.js:2:15411)
	(anonymous function) (v0.js:2:259520)
	(anonymous function) (v0.js:2:276140)
```

### Browser(s) Affected

Chrome, Safari

### OS(s) Affected

iOS

### Device(s) Affected

iPhone, iPad

### AMP Version Affected

2311212202000

**Comment by erwinmombay** [comment]
@powerivq would you mind triaging this?

**Comment by powerivq** [comment]
Tested https://preview.amp.dev/documentation/examples/components/amp-video-iframe#amp=1 on ios 17 and was not able to have the video played. Bumping priority up since this appears to affect a large audience.
