### ISSUE TITLE
Forbid ES6 Number things in Presubmit

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#3970]
They are not in every browser, and they're [causing](https://github.com/ampproject/amphtml/issues/3963) [errors](https://github.com/ampproject/amphtml/pull/3968#discussion_r70111258).

[Reference](http://www.2ality.com/2015/04/numbers-math-es6.html)

**Comment by lannka** [comment]
Shall we do a polyfill or presubmit check?

**Comment by jridgewell** [comment]
Most of them are available as `window.X`, so I think polyfilling them is overkill.
