### ISSUE TITLE
amp-story and image handling

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#39707]
### Description

issues with `amp-img` and `amp-selector` when used with `amp-story`

### Reproduction Steps

we've found several issues with `amp-img` and `amp-selector` when used with `amp-story`

example #1
https://afdsi.com/_google/attachment-tabs-sans-amp-selector/
selector works using `<img>`
but is invalid for using `<img>` rather than `<amp-ing>`
https://search.google.com/test/amp/result?id=h3VCui8BwFBUGurMaydD7g

example #2
https://afdsi.com/_google/attachment-tabs-avec-amp-img/
valid
https://search.google.com/test/amp/result?id=JzZ5VjQqheO7nJL05PN3_w
but selector from #1 fails when using `<amp-img>`
when a tab is selected and browser refreshed, image will load
but tab selection fails

example#3
https://afdsi.com/_google/amp-story-avec-list/
valid
https://search.google.com/test/amp/result?id=lKDabZSd5rZUBf3rcFQd6A
but the attachment with `amp-list` of images fails

here is verification that the examples works stand-alone:
https://afdsi.com/164189302300000061/index.html
using
https://afdsi.com/164189302300000061/data.json

### Browser(s) Affected

Chrome, Firefox, Safari

**Comment by erwinmombay** [comment]
assigning to @ychsieh to triage

**Comment by ychsieh** [comment]
I tried playing with it a little bit. But even with the <img> version(https://afdsi.com/_google/attachment-tabs-sans-amp-selector/), the tab selection would still be lost after refreshes.

For the amp-list inside the page-attachements, I do find this happened in other bugs reported long time ago. I am suspecting some optimization is done so images are not loaded at all in page-attachment. Would take another look at how amp-story-shopping avoid this.

**Comment by jaygray0919** [comment]
We also need a generalized amp-story-shopping solution. Let us know how to help deliver a two-for-one (twofer).

**Comment by ychsieh** [comment]
amp-story-shopping reads the shopping config about the URLs and make those URLs the CSS background of individual elements. Therefore, it won't work for standard usage of amp-list inside attachment, which is a customized layout instead of fixed layout like the shopping ones.

The fix is out: #39806. Basically layoutCallback never gets called.
