### ISSUE TITLE
Enable CONSENT_STATUS macro within amp-access component

### ISSUE THREAD

**Issue by ivanchuk** [ampproject/amphtml#39737]
### Description

CONSENT_STATUS is a variable that could be interesting to use in authorization request. Now in Spain we are deploying cookie walls due to new legal requirements. That could be useful in order to integrate consent value in our paywall systems

### Alternatives Considered

CONSENT_STATUS
or
${consentStatus}
or
window.context.consentSharedData
or whatever consent variable

### Additional Context

`<script id="amp-access" type="application/json">
  {
    "authorization": "https://www.example.es/acd/api/3.0/authorize/amp?articleId=1234abcd&consent=CONSENT_STATUS"
    ...
  }
</script>`

**Comment by ychsieh** [comment]
From the chat with our partner team, I think this is resolved given the fact that CONSENT_STATE is not usable with amp-access.

If you try to customize the cookie consent flow, you can use amp-consent(https://amp.dev/documentation/components/amp-consent), which is also the only component that maintains CONSENT_STATE macro that you want to use. If for amp-access, that's access restriction for content itself and not for cookies.
