### ISSUE TITLE
AMP Chronic Problem

### ISSUE THREAD

**Issue by wesley901** [ampproject/amphtml#39735]
### Description

Hi, I have a site where I use Wordpress, I created HTML AMP on it, but although my codes are correct, AMP frequently disconnects, meaning it redirects to my main site on mobile, not to AMP.
And this happens to me almost every day, and as a result, I don't get any errors etc.
Sometimes it happens for 3-4 days without any problems, then it goes back to the main site, not AMP.
There are no errors in the codes of my AMP site, I test it and I have a problem-free page. https://search.google.com/test/amp -> I test from here too, there is no error in AMP.
There is no error. There is no problem in the AMP section in Google WM Tools. It seems like they do not see AMP if they delete the AMP code.
I cannot share my site with you for security reasons.
I've done a lot of research, but I still haven't found a solution. It seems like a chronic problem.
I use this code in the header for AMP on my site:

<link rel="amphtml" href="https://ampsite.com/">
<link rel="canonical" href="https://mainsite.com/" />

In AMP, I use this code:
<link rel="canonical" href="https://mainsite.com/">

What can I do in such a problem, thank you.

### Reproduction Steps

Hi, I have a site where I use Wordpress, I created HTML AMP on it, but although my codes are correct, AMP frequently disconnects, meaning it redirects to my main site on mobile, not to AMP.
And this happens to me almost every day, and as a result, I don't get any errors etc.
Sometimes it happens for 3-4 days without any problems, then it goes back to the main site, not AMP.
There are no errors in the codes of my AMP site, I test it and I have a problem-free page. https://search.google.com/test/amp -> I test from here too, there is no error in AMP.
There is no error. There is no problem in the AMP section in Google WM Tools. It seems like they do not see AMP if they delete the AMP code.
I cannot share my site with you for security reasons.
I've done a lot of research, but I still haven't found a solution. It seems like a chronic problem.
I use this code in the header for AMP on my site:

<link rel="amphtml" href="https://ampsite.com/">
<link rel="canonical" href="https://mainsite.com/" />

In AMP, I use this code:
<link rel="canonical" href="https://mainsite.com/">

What can I do in such a problem, thank you.

**Comment by erwinmombay** [comment]
@wesley901 would you be able to share a sample document for us to test with? also does this occur on chrome or on safari?

**Comment by erwinmombay** [comment]
closing this out but feel free to re-open if you can give me a reproduction.
