### ISSUE TITLE
AMP validator VS AMP Extension

### ISSUE THREAD

**Issue by AlvaroO33** [ampproject/amphtml#39751]
### Description

I'm encountering some confusion regarding the discrepancy between the AMP validator (extension) vs https://validator.ampproject.org/ [The AMP Validator]. Specifically, the extension throws an error stating, 'The attribute 'fetchpriority' may not appear in tag 'img.' This issue was reportedly fixed by the AMP team around 5 months ago, as referenced here: https://github.com/ampproject/amphtml/issues/38715(https://github.com/ampproject/amphtml/issues/38715), In fact, I noticed that it has been added to the class AMP_Allowed_Tags_Generated 

I suspect there might be some sort of conflict... When I paste the source code from https://staging.foreverblueshirts.com/rangers-recall-kandre-miller-and-resiliency-on-full-display-in-vancouver/amp/ (viewed while logged out) in [The AMP Validator](https://validator.ampproject.org/) the valid status is PASS. I guess my question is which one is right?

### Reproduction Steps

Use the AMP validator Google extension in https://staging.foreverblueshirts.com/rangers-recall-kandre-miller-and-resiliency-on-full-display-in-vancouver/amp/ and then paste the source code in "https://validator.ampproject.org/" from the same link. The validator will trigger the error. But the online version will pass it.
<img width="954" alt="Screenshot 2024-01-12 at 8 23 53 AM" src="https://github.com/ampproject/amphtml/assets/138810155/d65998b2-ce8f-481b-9fd0-84b6ece41132">
![Screenshot 2024-01-17 at 6 05 05 AM](https://github.com/ampproject/amphtml/assets/138810155/80232d21-6abc-44b6-a3d7-cc8efbda4fab)

### Relevant Logs

```shell
No Logs
```

### Browser(s) Affected

Chrome

**Comment by erwinmombay** [comment]
we'll triage

**Comment by banaag** [comment]
I will close this bug for now, feel free to reopen if you are still seeing the issue. Thanks.
