### ISSUE TITLE
Update A4A to incorporate upgradeLayout

### ISSUE THREAD

**Issue by tdrl** [ampproject/amphtml#3976]
#3962  changes how delegation is handled in `amp-ad` for A4A.  The A4A code needs to be adapted to it.  Specifically, we need a mechanism to create an instance of a dynamically-loaded (from an extension) class within the `amp-ad.layoutCallback`.  (More precisely, a promise that resolves to an instance....)

**Comment by dvoytenko** [comment]
that is within `amp-ad.upgradeCallback`

**Comment by ericlindley-g** [comment]
@dvoytenko Slotting in backlog for now, but please update as needed
