### ISSUE TITLE
Provide a way for scripts to know whether there's a CMP on the page

### ISSUE THREAD

**Issue by bretg** [ampproject/amphtml#39843]
### Description

Prebid [provides two ways](https://docs.prebid.org/dev-docs/show-prebid-ads-on-amp-pages.html#user-sync) for AMP publishers to initiate a usersync:

- load-cookie.html
- load-cookie-with-consent.html

The reason the 'with-consent' version exists is that the code can't tell whether there's a Consent Management Platform (CMP) in the page. The design, as we understand it, is that the code has to listen on a message bus, so it can't tell whether (A) there's no CMP or (B) the CMP is slow or (C) the user hasn't submitted their values yet.

Since the code can't tell, Prebid pushes the responsibility on the publisher to use the special "with-consent" version of the file when appropriate. We would rather have just one version of the file to make things simpler for publishers. 

If there was a way for code to know whether listening on the message bus for a certain of time made sense (because there's a CMP on the page), we could deprecate the "with-cookie" version of this sync script.

In regular web pages, code can just sniff for the existence of the IAB-defined functions __tcf() and __gpp(). We would like something like this for AMP, or alternately, a guarantee that listening on the bus will get an answer quickly even if no CMP is on the page.

### Alternatives Considered

Any solution that allows scripts to quickly know whether there's a CMP in the page to wait for would be fine. We don't have an opinion about the implementation specifics.

**Comment by powerivq** [comment]
I would propose to add attributes here https://amp.dev/documentation/components/amp-iframe to indicate that no consent management platforms are present. WDYT? @bretg

**Comment by bretg** [comment]
@powerivq - are you suggesting that the publisher manually add an attribute defined by convention, or that the existence of a CMP would cause a standard attribute to be defined?

**Comment by powerivq** [comment]
@bretg Sorry that link was not clear. I meant a new attribute in the `send-consent-data ` message sent back

**Comment by dgirardi** [comment]
The need is to tell in advance whether `send-consent-data` will reply. I don't know if there's documentation I didn't find, but from what I can tell there's no guarantee that it will (the parent may not be using `amp-consent` at all), or when it does, we don't know if it's will at some point int he future ("The consent-data response may be delayed based on the selected policy").

**Comment by powerivq** [comment]
@dgirardi I meant to add an attribute to indicate that there are no CMPs on the page. That would imply that the message will be sent back without delay, otherwise it would be meaningless.

**Comment by dgirardi** [comment]
Yes, as long as I can expect a reply regardless of whether the parent did anything relating to consent (that is, it does not depend on the page setting up `amp-consent`).

**Comment by powerivq** [comment]
@bretg @dgirardi I just tested. I find that when you send a `send-consent-data` message, AMP will return immediately if no amp-consent is present with the following message:

```
{
  "sentinel": "amp",
  "type": "consent-data",
  "consentMetadata": null,
  "consentString": null,
  "consentPolicyState": null,
  "consentPolicySharedData": null
}
```

Please indicate if this is sufficient.

**Comment by dgirardi** [comment]
@powerivq that reply would be sufficient, but I can't get it from my testing. An example of an AMP page where my `send-consent-data` gets no reply is: https://www.comedy.co.uk/tv/news/7769/gavin-and-stacey-return-denied/

I also get no reply if I try to set up a minimal `amp-consent` page following [the docs](https://amp.dev/documentation/components/amp-consent) (but without setting up a CMP account, just copying the mock credentials in it): 

<details>
<summary>example</summary>

```
<!doctype html>
<html ⚡ lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
    <script>
        window.addEventListener('message', (e) => {
            console.log('MESSAGE', e);
        })
    </script>
    <script async src="https://cdn.ampproject.org/v0.js"></script>
    <script async custom-element="amp-ad" src="https://cdn.ampproject.org/v0/amp-ad-0.1.js"></script>
    <script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>
    <!-- required for the amp-consent component -->
    <script async="" src="https://cdn.ampproject.org/v0/amp-consent-0.1.js"></script>
    <!-- required to sync auth_id with publishers domain and Google.com domain -->
    <script async="" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>

    <title>AMP-RTC RP Test</title>
</head>
<body>
<amp-analytics>
    <script type=application/json>
        {
            "linkers": {
                "authId": {
                    "ids": {
                        "_a": "CLIENT_ID(AMP-CONSENT)"
                    },
                    "enabled": true,
                    "proxyOnly": false
                }
            },
            "cookies": {
                "enabled": true,
                "authId": {
                    "value": "LINKER_PARAM(authId, _a)"
                }
            }
        }
    </script>
</amp-analytics>
<amp-consent id="consent" layout="nodisplay">
    <script type="application/json">
        {
            "checkConsentHref": "https://cdn.privacy-mgmt.com/wrapper/tcfv2/v1/amp-v2?authId=CLIENT_ID",
            "consentRequired": "remote",
            "consentInstanceId": "sourcepoint",
            "postPromptUI": "consent-ui",
            "promptUISrc": "//cdn.privacy-mgmt.com/amp/unified/index.html?authId=CLIENT_ID&source_url=SOURCE_URL",
            "cookies": {
                "enabled": true,
                "AMP-CONSENT": {    "value": "LINKER_PARAM(authId, _a)" }
            },
            "clientConfig": {
                "accountId": 1732,
                "propertyHref": "https://amp.newscriptdemo.com",
                "targetingParams": {"darkmode":"true"},
                "stageCampaign": false,
                "pmTab": "purposes",
                "privacyManagerId": 547514,
                "initialHeight": 80,
                "authId": "xxx"
            }
        }
    </script>
</amp-consent>
<div id="consent-ui">
    <button on="tap:consent.prompt(consent=SourcePoint)">Privacy Settings</button>
</div>
<h2>AMP-RTC RP Test</h2>
<amp-ad width="300" height="50"
        type="doubleclick"
        data-slot="/112115922/amp_test"
        data-multi-size-validation="false"
        rtc-config='{"vendors": {"prebidrubicon": {"REQUEST_ID": "14062-amp-300x50"}}}'
        json='{ "targeting": {"visitor":{"age":"18-24","gender":"male"},"inventory":{"section":"amp"}}}';
</amp-ad>
<hr>
<h2>More content<h2>
    <iframe height="600" width="10"></iframe>
    The cookie sync iframe can't be within 600px from the top.
    <amp-iframe width="1" title="User Sync"
                height="1"
                sandbox="allow-scripts allow-same-origin"
                frameborder="0"
                src="https://acdn.adnxs.com/prebid/amp/user-sync/load-cookie-with-consent.html?endpoint=appnexus&max_sync_count=5&source=amp">
        <amp-img layout="fill" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" placeholder></amp-img>
    </amp-iframe>
</body>
</html>
```

</details>

what am I doing wrong?

**Comment by dgirardi** [comment]
I am realizing now that my testing method is likely the problem - I am using browser extensions to modify the contents of the iframe src; that does not preserve the origin, so my messages are probably failing some check and discarded. We can close this, I'll change my workflow and come back if I still have problems.

**Comment by powerivq** [comment]
@dgirardi Yes, AMP runtime does have origin check when sending/receiving messages. Glad it was figured out.

@bretg when you have time, maybe you can take a look at this. If it works for you, I will close this issue.

**Comment by bretg** [comment]
If @dgirardi 's happy, I'm happy.
