### ISSUE TITLE
Support vega visualizations in AMP

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#3991]
See https://vega.github.io/vega/

It should be relatively easy to build this component and provide super powerful native visualization capabilities for AMP.

Vega would need to be bundled with the `amp-viz-vega` component and then accept JSON config in our standard manner (similar to e.g. `amp-analytics`).

See the vega tutorial here: https://github.com/vega/vega/wiki/Tutorial

<details>
<summary>

`<amp-viz-vega …`</summary>

``` html
<amp-viz-vega width=400 height=200>
<script type="application/json">
{
  "width": 400,
  "height": 200,
  "padding": {"top": 10, "left": 30, "bottom": 20, "right": 10},

  "data": [
    {
      "name": "table",
      "values": [
        {"category":"A", "amount":28},
        {"category":"B", "amount":55},
        {"category":"C", "amount":43},
        {"category":"D", "amount":91},
        {"category":"E", "amount":81},
        {"category":"F", "amount":53},
        {"category":"G", "amount":19},
        {"category":"H", "amount":87},
        {"category":"I", "amount":52}
      ]
    }
  ],

  "signals": [
    {
      "name": "tooltip",
      "init": {},
      "streams": [
        {"type": "rect:mouseover", "expr": "datum"},
        {"type": "rect:mouseout", "expr": "{}"}
      ]
    }
  ],

  "predicates": [
    {
      "name": "tooltip", "type": "==", 
      "operands": [{"signal": "tooltip._id"}, {"arg": "id"}]
    }
  ],

  "scales": [
    { "name": "xscale", "type": "ordinal", "range": "width",
      "domain": {"data": "table", "field": "category"} },
    { "name": "yscale", "range": "height", "nice": true,
      "domain": {"data": "table", "field": "amount"} }
  ],

  "axes": [
    { "type": "x", "scale": "xscale" },
    { "type": "y", "scale": "yscale" }
  ],

  "marks": [
    {
      "type": "rect",
      "from": {"data":"table"},
      "properties": {
        "enter": {
          "x": {"scale": "xscale", "field": "category"},
          "width": {"scale": "xscale", "band": true, "offset": -1},
          "y": {"scale": "yscale", "field": "amount"},
          "y2": {"scale": "yscale", "value":0}
        },
        "update": { "fill": {"value": "steelblue"} },
        "hover": { "fill": {"value": "red"} }
      }
    },
    {
      "type": "text",
      "properties": {
        "enter": {
          "align": {"value": "center"},
          "fill": {"value": "#333"}
        },
        "update": {
          "x": {"scale": "xscale", "signal": "tooltip.category"},
          "dx": {"scale": "xscale", "band": true, "mult": 0.5},
          "y": {"scale": "yscale", "signal": "tooltip.amount", "offset": -5},
          "text": {"signal": "tooltip.amount"},
          "fillOpacity": {
            "rule": [
              {
                "predicate": {"name": "tooltip", "id": {"value": null}},
                "value": 0
              },
              {"value": 1}
            ]
          }
        }
      }
    }
  ]
}
</script>
</amp-viz-vega>
</details>
```

**Comment by erwinmombay** [comment]
@cramforce would we just need vega in our `third_party` folder?

**Comment by cramforce** [comment]
@erwinmombay yep.

**Comment by erwinmombay** [comment]
@cramforce taking this, unless its already assigned to somebody then feel free to reassign

**Comment by cramforce** [comment]
I thought it would have been a nice 1st component for @aghassemi to push through end-to-end, but we'll find another one.

**Comment by erwinmombay** [comment]
@cramforce gotcha, no that sounds great. assigning it to @aghassemi

**Comment by aghassemi** [comment]
:+1:

**Comment by pbakaus** [comment]
Can't wait to see this happen. I have a semi-working version of an amp-iframe variant at https://www.ampproject.org/metrics/ but it doesn't work due to the viewport limitation :(

**Comment by aghassemi** [comment]
@pbakaus this is ready for experimenting. https://github.com/ampproject/amphtml/blob/master/extensions/amp-viz-vega/amp-viz-vega.md should (hopefully) provide enough information to get started. Please feel free to ping me on hangout or schedule a meeting if you run into issues or have questions.

**Comment by pbakaus** [comment]
Excellent, I created a new issue to track, might not get around to doing it before my vacation starts end of this week: https://github.com/ampproject/docs/issues/176

**Comment by adelinamart** [comment]
Is this still valid? Thanks

**Comment by aghassemi** [comment]
@adelinamart Yes. It is pending a launch (or deletion). @ericlindley-g and I will discuss and come up with a decision

**Comment by aghassemi** [comment]
Note: If we keep it, we need to move JS to a 3P iframe (too many security issues with the Vega/3D Js library to keep it 1st party)

**Comment by ericlindley-g** [comment]
@aghassemi  Good to know — the use cases supported by D3 more generally are top-of-mind right now, so let's definitely chat soon to figure out best next steps.

**Comment by anatolyg** [comment]
@aghassemi this is great stuff -- do you guys have an update as to the availability of this component? Is it slated to come out of experimental?

**Comment by aghassemi** [comment]
@anatolyg It hasn't been on the radar recently but looks like there is interest. Will try to prioritize /cc @ericlindley-g

**Comment by anatolyg** [comment]
@aghassemi thank you! we are looking to use vega to offer in-line visualizations for our AMP pages.

**Comment by mrjoro** [comment]
Is this I2I still active?

**Comment by aghassemi** [comment]
@mrjoro experimental, launch of it is tracked under https://github.com/ampproject/amphtml/issues/18705 (there are JS bundle size concerns with launching it).
