### ISSUE TITLE
Please provide an opt-out

### ISSUE THREAD

**Issue by nardholio** [ampproject/amphtml#3992]
Please provide a way to opt out or disable AMP. My mobile browser of choice, Opera, already optimizes pages and provides me an easy way to switch to the full site if I want. It is also one of the few browsers to support forced pinch-zoom on Android ever since Google intentionally killed that feature in Chrome and the AOSP browser.

In short, AMP simply cannot provide the following things:
1. Choice of browser
2. Forced pinch-zoom
3. Easy way to switch to desktop site
4. Access to URL bar to bookmark site for later, share with friends, or browse to other pages on site at my leisure. And no, I don't consider the option to email a link to a friend an adequate substitute
5. User satisfaction. I hate AMP and for a product that claims to enhance my mobile browsing experience, not having an opt-out leaves me extremely unsatisfied and thus unenhanced.

**Comment by cramforce** [comment]
@nardholio AMP is a JavaScript library. You cannot make an opt out for it, just like you cannot make an opt out for jQuery, except by disabling JavaScript.

**Comment by benjamincox** [comment]
AMP is a JavaScript Library for content providers AND it's also a user interface for people searching for info via Google.

Your reply seems to indicate that this isn't the right place for end users to complain or request changes to the user experience. Okay, but all of Google's links on the AMP pages point here...
 
If not here, then whom should we petition for the ability to opt out of the poor user experience for those of us who just want to search the web and have our browsers work properly (see list of UX breaks in the OP)?

**Comment by jridgewell** [comment]
[Google's AMP forum](https://goo.gl/utQ1KZ). We are not related to Google Search's use of AMP, just the library for content providers.
