### ISSUE TITLE
amp [src]="imageUrl" not loading image but src="https://preview.amp.dev/static/inline-examples/images/image1.jpg" working fine in angular

### ISSUE THREAD

**Issue by Kanhaiya2909** [ampproject/amphtml#39945]
### Description

I am try to load image in angular :- https://preview.amp.dev/static/inline-examples/images/image1.jpg

My .ts file have imageUrl="https://preview.amp.dev/static/inline-examples/images/image1.jpg"

try 1 (Not loading image) :- <amp-img [src]="imageUrl" width="720" height="1280" layout="responsive"></amp-img>
 try 2 (Not loading image ):-<amp-img src="{{imageUrl}}" width="720" height="1280" layout="responsive"></amp-img>
        Try 3 (Working fine ):-<amp-img src="https://preview.amp.dev/static/inline-examples/images/image1.jpg" width="720" height="1280" layout="responsive"></amp-img>
        

### Reproduction Steps

This is in my localhost I just attached screenshot
<img width="1428" alt="Screenshot 2024-04-04 at 1 58 26 PM" src="https://github.com/ampproject/amphtml/assets/84491065/128ce9ad-01e2-4037-bc80-6d706dbed2e2">

**Comment by erwinmombay** [comment]
@Kanhaiya2909 can you clarify if this is about AMP or angular?

closing for now but feel free to re-open if you have more information
