### ISSUE TITLE
General Questions

### ISSUE THREAD

**Issue by BellaAnasastasya** [ampproject/amphtml#39958]
Where i can report AMP page that violating internet rule such as : 
- Phishing
- Hacking activity
- SPAM
- Doorway Spam

I really hope for a reply as soon as possible, thank you

**Comment by amanintech** [comment]
If i am not wrong, AMP pages are not moderated by the @amphtml-team. The framework if OpenSource and for anyone to use and deploy under the [Terms of Services ](https://images.prismic.io/openjsf/4efecb0b-cd01-4274-8cc5-1444f0413377_OpenJS-Foundation-Terms-of-Use-2019-11-15.pdf). If this is being done under the  impersonation of another brand, maybe its a good idea to reach out there.

**Comment by powerivq** [comment]
Thanks for the reply. @amanintech is correct. We only maintain the format and had no way of disconnecting an offending content, like any other website.
