### ISSUE TITLE
load data without user interaction with amp-script, amp-list and amp-mustache.

### ISSUE THREAD

**Issue by sayamalvi** [ampproject/amphtml#39952]
I am using amp-script to provide data for amp-list and render it with amp-mustache. But the story/data only gets populated when I hit the page reload. Earlier I was using a script which was linked with amp-script. I thought the issue might be related to the fetch api but now I am loading the data from local storage, still I have to hit the reload to make content visible on the screen. Need help regarding this.
![Screenshot 2024-04-09 165900](https://github.com/ampproject/amphtml/assets/52599441/cc7d6ec8-92d6-4c17-b943-9d569a146acc)
Initial render is showing a loader:
![Screenshot 2024-04-09 171215](https://github.com/ampproject/amphtml/assets/52599441/7b11aa60-411a-48f2-9d8c-63de01bbfe4a)
After hitting the page reload story is rendered: 
![Screenshot 2024-04-09 171126](https://github.com/ampproject/amphtml/assets/52599441/d24038c0-7869-4206-83d1-34dbfe6507bd)

**Comment by erwinmombay** [comment]
@sayamalvi can the issue be reproduced locally? do you happen to have a sample page we could use to debug? thanks

**Comment by sayamalvi** [comment]
This particular issues has been resolved. There was a script tag which was causing the issue. I removed that and now the page is loading fine.
<script async="" src="https://cdn.ampproject.org/v0.mjs" type="module" crossorigin="anonymous"></script>. This async="" was causing the issue probably. 
Should I close the issue from my end ?

**Comment by erwinmombay** [comment]
glad it got resolved. ill close the issue on my end.  thank you!
