### ISSUE TITLE
Check for available updates via SteamCMD not finding updates

### ISSUE THREAD

**Issue by MadCappedBeef** [ampproject/amphtml#40000]
### Description

The task `Check for available updates via SteamCMD` Should check for an update and if it finds one should activate the trigger `An update is available via SteamCMD`

The task `Check for available updates via SteamCMD` currently doesn't see any updates when I've confirmed an update has been pushed to steam for over an hour.

### Reproduction Steps

Have an update that has been pushed to steam

Have a trigger `An update is available via SteamCMD` with a task to send a message or update to know if its been triggered

Run the task `Check for available updates via SteamCMD` 

Await outcome

### Browser(s) Affected

Chrome

### AMP Version Affected

AMP Release "Callisto" v2.5.0.8, built 02/05/2024 04:53

**Comment by erwinmombay** [comment]
closing this one out, but if you have any additional information to give on why this pertains to AMP, please feel free to re-open and we can take a look. Thanks
