### ISSUE TITLE
remove `amp-access-server` experiment

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#4000]
remove experiment flags and guards

**Comment by jtangelder** [comment]
When will this experiment go to production? The company I work for has a lot of restricted content (lots of large newspapers and magazines) and the amp-access-server module is the only way for us to get started with AMP. Embedding the content with the amp-access-client setup is not an option for us.

**Comment by dvoytenko** [comment]
@jtangelder This has not launched yet. 

/to @rudygalfi to confirm the schedule.

**Comment by jtangelder** [comment]
Anyway for me to help finishing this feature?

**Comment by dvoytenko** [comment]
@jtangelder I think the implementation is done, but it's going through security reviews. But do please clarify what you have in mind and if the proposed protocol works well for you.
