### ISSUE TITLE
remove `amp-fx-flying-carpet` experiment

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#4003]
remove experiment flags and guards

**Comment by erwinmombay** [comment]
@jridgewell is flying carpet still in experiment?

**Comment by jridgewell** [comment]
Yup, we're now blocked by https://github.com/ampproject/amphtml/issues/5149.

**Comment by jridgewell** [comment]
Unblocked now, and live for everyone. Should clean this up in a week or two.
