### ISSUE TITLE
remove `amp-experiment` experiment

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#4004]
remove experiment flags and guards

**Comment by jpettitt** [comment]
Any ETA on when amp-experiment will be GA?  We'd like to use it for some A/B testing of the "prefer-vewability" amp-ad flag.

**Comment by erwinmombay** [comment]
@jpettitt i believe it currently is unflagged in production.

**Comment by rudygalfi** [comment]
Indeed it is: https://amphtml.wordpress.com/2016/08/24/optimize-your-amp-pages-with-amp-experiment/amp/
