### ISSUE TITLE
Sticky Ad showing as hidden

### ISSUE THREAD

**Issue by pankaj-2812** [ampproject/amphtml#40061]
### Description

I've recently integrated AMP sticky ad on our [website](https://www.ndtv.com/amp), but it's not rendering. Upon investigation, found the same with visibility property as hidden adding at runtime. Can you please help me what's getting missed.
<img width="1470" alt="12" src="https://github.com/ampproject/amphtml/assets/173475742/0cce60a3-44cc-45d3-8db8-afbcf90b97ad">

### Reproduction Steps

Open https://www.ndtv.com/amp

### Browser(s) Affected

Chrome

**Comment by jackoske** [comment]
![image](https://github.com/ampproject/amphtml/assets/117357252/a2d4896b-9696-461f-ba70-e2d2e648b464)

working for me in chromium private window (no ad block)

as of Friday, 21 June 2024, 18:44  (GMT+2)

**Comment by erwinmombay** [comment]
@powerivq do you have any insight on this?

**Comment by powerivq** [comment]
The unit remains hidden until the ad gets filled. You might want to check why that part failed. @pankaj-2812

**Comment by pankaj-2812** [comment]
> The unit remains hidden until the ad gets filled. You might want to check why that part failed. @pankaj-2812

Even the ad request is not triggering on the page. The setup is as per guidelines but still I'm getting this issue.

**Comment by pankaj-2812** [comment]
> > The unit remains hidden until the ad gets filled. You might want to check why that part failed. @pankaj-2812
> 
> Even the ad request is not triggering on the page. The setup is as per guidelines but still I'm getting this issue. Can you please help us understand what's missing on the page? @powerivq powerivq

Pls help with solution.

**Comment by powerivq** [comment]
@pankaj-2812 Looks like you are still using amp-sticky-ad element. You should probably switch to <amp-ad sticky=bottom> https://amp.dev/documentation/components/amp-ad

**Comment by erwinmombay** [comment]
closing the issue but feel free to re-open if theres any additional information
