### ISSUE TITLE
instanceof HTMLElement returns false incorrectly. This breaks Google Maps Javascript API

### ISSUE THREAD

**Issue by alek-womple** [ampproject/amphtml#40090]
### Description

We've been working around this for a while. Google AMP does not understand `instanceof HTMLElement`. It returns `false` when it should return `true`. 

Now there's a real problem with Google Maps, and we can't work around it. Starting with v3.55 of the Maps Javascript API, the infoWindow does not open on a map when clicking a marker. It fails silently, but through debugging we have determined that fault happens when the Javascript API script uses `instanceof HTMLElement` to test the "Close" button instead of `instanceof HTMLButtonElement`. See the attached screenshots.

We have reported this to the Google Maps Javascript API team via the Google Cloud Support, but they are not going to fix this on their end. Instead, they expect the Google AMP team to fix the `instanceof` issue.

Note that Google has scheduled to remove v3.55 of the Javascript API at the end of October. When this happens, that will be the end of working maps on Google AMP websites unless you fix this bug, or we find some other workaround.

Screenshots from debugging the Google Maps Javascript API script...
<img width="511" alt="Screenshot 2024-07-12 at 12 44 27 PM" src="https://github.com/user-attachments/assets/5a52594b-12a0-4e0d-9558-a6c6b4b413f2">

<img width="466" alt="Screenshot 2024-07-12 at 12 46 51 PM" src="https://github.com/user-attachments/assets/4b390e51-9e12-4c8f-b25d-97f0c252b19e">

<img width="500" alt="Screenshot 2024-07-12 at 12 47 03 PM" src="https://github.com/user-attachments/assets/0815e05d-691f-46bf-a6f8-5fc3aa1a3b93">

<img width="489" alt="Screenshot 2024-07-12 at 12 48 14 PM" src="https://github.com/user-attachments/assets/6a8cf255-3214-49f3-986f-c4e1ee204505">

<img width="499" alt="Screenshot 2024-07-12 at 12 48 55 PM" src="https://github.com/user-attachments/assets/3ba688f3-6f35-4a17-a91e-6839a93a2341">

Experiments in the Console prove that Google AMP doesn't properly handle `instanceof HTMLElement` on a button element...
<img width="203" alt="Screenshot 2024-07-12 at 12 45 23 PM" src="https://github.com/user-attachments/assets/0030770e-c3e0-4491-b475-8a6e6f677d67">

<img width="282" alt="Screenshot 2024-07-12 at 12 45 32 PM" src="https://github.com/user-attachments/assets/ac9a5c7e-0534-4ff9-889b-5a8b2c224aa1">

### Reproduction Steps

Use the working jsfiddle repro code from here: https://jsfiddle.net/alek_womple/wf80L2uj/

Apply it to your Google AMP project. 

You'll see that the infoWindows will not open in your Google AMP project, even though they open fine in JS Fiddle. If you trace the `Invalid Value Error` you see in the Console, you'll get to the code shown in the screenshots.

We found that Google AMP doesn't understand instanceof HTMLElement when we were updating our code for Typescript, but we worked around that using other type checks. In this case, the Google Maps Javascript API team could work around it for us if they added a fallback test for `HTMLButtonElement`, but they refuse. They demanded that we contact the Google AMP team to fix the `instanceof HTMLElement` test.

**Comment by erwinmombay** [comment]
thanks for the report @alek-womple . triaging this

**Comment by powerivq** [comment]
Hi @alek-womple 

I looked into your JSFiddle link and see you are using Google Maps SDK. Can you clarify how AMP is involved here? Are you using amp-iframe to a page like this?

**Comment by alek-womple** [comment]
The JSFiddle demo doesn't use amp. It's a minimum repro of our code, and it shows that the same code, when used outside of the Google AMP ecosystem, works just fine. When I use that code inside our AMP page things break. The problem of `instanceof HTMLElement` not being recognized by AMP was found when troubleshooting on our end. We are currently working around it by overwriting `window.HTMLElement` with `window.HTMLElementOrig` at the right timing. It's a genius hack that one of our devs figured out after studying the Google AMP project code. If you make `instanceof HTMLElement` work, then we won't need to do this.

**Comment by alek-womple** [comment]
I don't have time to build one, sorry. Just take any AMP project and add a map to it using the code from my JS Fiddle. It should fail as described in this ticket. The map and markers will appear, but the infoWindows will not open when the markers are clicked. You may also see an `Invalid Value Error` on the initial load, although this doesn't seem to stop the map from loading. But a simpler repro is just to try any code that expects `instanceof HTMLElement` to return `true`. Fix this in AMP, and you've solved the problem.

**Comment by powerivq** [comment]
@alek-womple I opened [amp.dev](https://amp.dev/) and picked a few elements (including button) and tested whether they are `instanceof HTMLElement`, and so far I have been getting `true`. Unless we have more info, it would be hard to find out what actually went wrong.

**Comment by alek-womple** [comment]
Hm. I see that amp.dev is loading `https://cdn.ampproject.org/v0.mjs` whereas our project is loading `https://cdn.ampproject.org/v0.js.` It looks like there is no `HTMLElementOrig` present in the mjs version. Was this possibly addressed in mjs?

**Comment by powerivq** [comment]
@alek-womple mjs was compiled with a higher browser requirement, therefore we do not need to use polyfill. For js, we support a wider range of browsers and polyfill HTMLElement.

It is not possible to do what you propose as long as polyfill is required: https://github.com/ampproject/amphtml/issues/26424

**Comment by alek-womple** [comment]
Thank you and yes, that's the issue: `instanceof HTMLElement` doesn't work with the polyfill in the js file. Any AMP pages using this script will not be able to work with the new Google Maps API. I'm not sure we're ready to switch to mjs because it seems like a big change. `HTMLElement` is widely supported by older browsers, so it seems that supporting very old browsers while not supporting current Google Maps code is not a great plan. Maybe a v1.1 of the js script could be released to fix this for those who would like just this update without switching to the module version?

**Comment by powerivq** [comment]
@alek-womple We recognize publishers may want to, but AMP does not officially support external JavaScript, and doing so will fail the AMP validation. What's more, adding another bundle to AMP's release process involves QA cost that probably is hard to justify given the situation.

I have the following recommendations on how you can solve your site-specific issue:
1. You can choose to compile AMP js bundle yourself, removing the polyfill.
2. Use map sdk in an iframe to have it isolated from the page.
3. Modify your button element to something like `a`. You can stylize it to make it look like a button.

Hope it helps.

**Comment by alek-womple** [comment]
1) We may end up doing that. Thank you!

2) Since our customer interact with the map pretty extensively using controls outside of the map, adding the Google Map via an iframe isn't going to work well (or at all) in our case.

3) It is not our button element but comes with the infoWindow on the map. It's built-in functionality from Google Maps. As such, the Google AMP js really is incompatible with the latest Google Maps JS API.

Thanks for your replies and again for your recommendations!

**Comment by powerivq** [comment]
Thank you. Let us know if there are issues wrt. compiling the runtime bundle. It should be easy with `amp dist` command line.
