### ISSUE TITLE
Intent To Implement: ZergNet Content Recommendation for amp-embed

### ISSUE THREAD

**Issue by zergnetjake** [ampproject/amphtml#4009]
# Overview

Adding support for the [ZergNet](http://www.zergnet.com) Content Recommendation unit to <amp-embed> elements.
## Comments

ZergNet will submit a pull request for a zergnet/amp-embed branch using the ZergNet fork from here: https://github.com/zergnetjake/amphtml

**Comment by cramforce** [comment]
![LGTM](https://camo.githubusercontent.com/c13eeb81b1485ccc0d2b248f19360c7ba2419167/687474703a2f2f6a756e6b796172642e64616d6f776d6f772e636f6d2f353633)

**Comment by zergnetjake** [comment]
There was an issue with the previous pull request, I had accidentally pushed some commits using my personal github information.

New pull request is here: https://github.com/ampproject/amphtml/pull/4108

**Comment by adelinamart** [comment]
I see the last PR mentioned here was merged. 
Closing this one, but if there's still work in progress, feel free to reopen. Thanks.
