### ISSUE TITLE
amp-story-player: prev and next story buttons are hidden on Chrome

### ISSUE THREAD

**Issue by MLB-Qwang** [ampproject/amphtml#40119]
### Description

**Expected**
Prev and next story buttons are visible in amp-story-player across all browsers (not full-bleed)

**Current**
Prev and next story buttons are hidden in Chrome

I'm looking at the CSS and it looks like Chrome is not respecting `:not(.i-amphtml-story-player-panel)`:
<img width="1913" alt="Screenshot 2024-08-15 at 2 28 11 PM" src="https://github.com/user-attachments/assets/8dae1335-bd3e-46d5-b850-8f00adf6d800">

### Reproduction Steps

Reproducible via this URL that loads multiple stories:

https://www.mlb.com/stories

### Browser(s) Affected

Chrome

### AMP Version Affected

2406131415000

**Comment by erwinmombay** [comment]
@ychsieh do you mind taking a look at this when you get a chance

**Comment by MLB-Qwang** [comment]
Hey guys, any updates on this?

**Comment by ychsieh** [comment]
@processprocess could you take a look at the quick fix: #40124? Thanks!

**Comment by ychsieh** [comment]
The PR is merged. Closing this for now.
