### ISSUE TITLE
link of websites-2021, stories, email, ads is not working 

### ISSUE THREAD

**Issue by Anonymous-hss** [ampproject/amphtml#40121]
### Description

links(not working):
[https://amp.dev/about/ads/](https://amp.dev/about/ads/)
[https://amp.dev/about/email/](https://amp.dev/about/email/)
[https://amp.dev/about/stories/](https://amp.dev/about/stories/)
[https://amp.dev/about/websites-2021/](https://amp.dev/about/websites-2021/)

### Reproduction Steps

Just simple go to website and try click on:

- [All about AMP Websites](https://amp.dev/about/websites)
- [All about Web Stories](https://amp.dev/about/stories)
- [All about AMP Emails](https://amp.dev/about/email)
- [All about AMP Ads](https://amp.dev/about/ads)

OR 

Simply navigate to about in navbar and try clicking there.

**Comment by erwinmombay** [comment]
@Anonymous-hss looks like the link works. feel free to open the issue if you have more information on how to reproduce
