### ISSUE TITLE
Add the merged pull request #40108 in the release

### ISSUE THREAD

**Issue by MaksymTeqBlaze** [ampproject/amphtml#40120]
I’m reaching out to ask if the merged pull request [#40108](https://github.com/ampproject/amphtml/pull/40108) can be included in the current LTS version or perhaps the next upcoming release. The last release was some time ago, and this is quite time-sensitive for us.

**Comment by erwinmombay** [comment]
@MaksymTeqBlaze heya our releases have been delayed the past few weeks. we'll make sure your PR is in the next release.

ill leave this issue open for now

**Comment by erwinmombay** [comment]
we've identified a bug (https://github.com/ampproject/cdn-configuration/pull/1309) in our release process and the changes should be in canary by next week i believe

**Comment by powerivq** [comment]
The relevant PR is now in stable. Closing this issue.
