### ISSUE TITLE
Increase timeout setting for authorzation endpoint

### ISSUE THREAD

**Issue by MrMuzik** [ampproject/amphtml#4013]
It would be very useful to increase the maximum time for an authorization request before timeout or to make this configurable as a part of the request. I currently have a valid request returning from an endpoint and authorization is failing due to timeout. If it can not be configurable as a part of the request I suggest a timeout of 6 seconds instead of the current 3 seconds.

**Comment by cramforce** [comment]
Since this is in the critical path to the user seeing the doc, the timeout must be low.

**Comment by MrMuzik** [comment]
@cramforce How high could we go without issue? 3 seconds is just too short.

**Comment by cramforce** [comment]
3 seconds is the established timeout for things like fonts on the web. Why would one need longer? We might be able to go a bit higher if the user is on 2G, but on 3G, LTE, WIFI 3 seconds is an eternity already. Typically servers should respond in about 100ms.

**Comment by MrMuzik** [comment]
I typically see my authorization response received around 3.14s - 3.56s. I don't have any other issues,the page validates, and all other assets load from 2ms - 410ms.

**Comment by cramforce** [comment]
Why does it take so long?

**Comment by MrMuzik** [comment]
Currently a mystery. I am exploring possible issues causing the slowdown internally though I am not seeing any issues so I opened this ticket to explore the possibility of an external issue.

**Comment by dvoytenko** [comment]
@MrMuzik Correct. The 3s timeout is currently selected to coincide with fonts. Industry-average we've seen is definitely much lower than this. What authorization service are you using? Could you go into more detail or possibly share some examples? Is this a PROD or DEV system?

**Comment by MrMuzik** [comment]
I do not have it on a production server anymore. I am doing the authorization through amp-access. Is there another option you would recommend @dvoytenko?

**Comment by dvoytenko** [comment]
@MrMuzik This is the only option in AMP. But I was asking what endpoint you use for authorization (`authorization` configuration parameter). The questions I asked are about this endpoint.

**Comment by MrMuzik** [comment]
Thanks for all the help. My issues appears to be completely internal and I am working on a fix. Thanks for helping me figure it out.

**Comment by kozlice** [comment]
It would be nice to have configurable timeout. In dev environment I have to use auth service which located on the other side of planet, accessible only via VPN. Pings and round trip timings are huge and response time is _never_ under 3s.

@cramforce Is there any workaround for such cases?
