### ISSUE TITLE
Rename Brid player to TargetVideo

### ISSUE THREAD

**Issue by danijel-ristic** [ampproject/amphtml#40130]
### Summary

Rename `amp-brid-player` to `amp-target-video-player`

### Motivation

Brid.tv got acquired by TargetVideo so we need to rename `amp-brid-player` to `amp-target-video-player`

### Alternative Solutions

Since we need to keep `amp-brid-player` working until we migrate all amp players to TargetVideo, I guess I need to create new TargetVideo player extension and after we migrate I need to create new PR to remove `amp-brid-player`, can anyone confirm if this is correct process for doing this.

### Notifications

/cc @ampproject/wg-approvers

**Comment by danijel-ristic** [comment]
cc @ampproject/wg-approvers

**Comment by powerivq** [comment]
@danijel-ristic Yes, you should move the extension to the new name, and set the old one as an alias.

**Comment by danijel-ristic** [comment]
@powerivq How would I alias old one to the new one, I tried to find examples, docs but I wasn't lucky. Could you point me in the right direction? Thanks in advance.

**Comment by powerivq** [comment]
@danijel-ristic https://github.com/ampproject/amphtml/blob/main/extensions/amp-ad/0.1/amp-ad.js#L127

For example, amp-embed is an alias of amp-ad.
