### ISSUE TITLE
Make `attemptChangeSize` `attemptChangeHeight` promises

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#4014]
Currently `attemptChangeSize` `attemptChangeHeight` only accept callback functions that get called when size changed successfully. There's no way to tell if `attemptChangeSize` fail. Making it a promise should be able to solve this.

**Comment by ericlindley-g** [comment]
@zhouyx  Assuming this is currently being worked on, but please correct/update as needed
