### ISSUE TITLE
Add `amp-pokemon-go` extended component

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#4017]
Allow for embedding and capturing Pokemon in AMP pages.

**Comment by erwinmombay** [comment]
💯 to celebrate I am changing my picture to this:

![13620816_10153516842152811_6805801261464515458_n](https://cloud.githubusercontent.com/assets/354746/16748377/9bc74262-4778-11e6-969e-9448f3589d02.jpg)

**Comment by jridgewell** [comment]
![y tho](https://cdn.meme.am/instances/500x/61561297.jpg)

**Comment by cramforce** [comment]
Would the component need to ship with an Android emulator?

**Comment by adelinamart** [comment]
Do we still need this?

**Comment by erwinmombay** [comment]
probably not lol

**Comment by choumx** [comment]
I pikachoose this issue.

**Comment by cramforce** [comment]
@erwinmombay Can you write a GitHub bot, though, that closes GitHub issues when apps fall below a certain app store rank?
