### ISSUE TITLE
Need to send multiple ad request in amp-ima-video for video ads

### ISSUE THREAD

**Issue by as5550** [ampproject/amphtml#40182]
### Description

i tried using 'amp-ima-video' for running a video player with google ima ad tags on amp pages, but in this ad request need to be specified in 'data-tag' attribute and that ad request will be sent only once but i want to send multiple ad requests and serve them i have already tried sending VMAP and XML ad request but only one request is sent.
Also 'loop' and 'dock' attributes are not working in 'amp-ima-video' but working in 'amp-video'.

### Alternatives Considered

I tried 'amp-video' as well 'loop' and 'dock' are working but can't send multiple ad request.
I also tried the example provided -> 
https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-ima-video&_gl=1*yujfzd*_ga*YW1wLV93WUJYcGxSZk5GTlF3WjRjenlOdGc.*_ga_TYM9BH1XCX*MTcyODQ1NjAyMC4xMy4xLjE3Mjg0NTYwODcuMC4wLjA.

and in here preroll, midroll and postroll ads are served (1 each).

### Additional Context

this is the code i am using you can check this as well

<amp-ima-video 
    id="myVideo" 
    width="640" 
    height="360" 
    layout="responsive" 
    data-tag="https://pubads.g.doubleclick.net/gampad/ads?iu=/21928950349/amp_video_test&description_url=[placeholder]&tfcd=0&npa=0&sz=640x360&gdfp_req=1&unviewed_position_start=1&output=vmap&env=vp&impl=s&ad_rule=1&correlator=&vid_d=12000" 
    data-poster="https://www.amitmerchant.com/cdn/custom-thumbnail-video-element.png"
    loop
    dock>
      <source src="https://unibots.b-cdn.net/aajtak.mp4" type="video/mp4">
  </amp-ima-video>

**Comment by erwinmombay** [comment]
@as5550 looks like the code wasnt posted?

@powerivq is multiple ad requests a feature that we support?

**Comment by erwinmombay** [comment]
@as5550 im not familiar with this space so this might be a dumb question, could you explain to me the scenario why you would want to send multiple ad requests? is this just a matter of optimization?

**Comment by powerivq** [comment]
@as5550 I suppose you wanted to do some form of header bidding? I do not believe it is available thru amp-ima-video right now.

**Comment by as5550** [comment]
yes the code didn't posted,
i am trying to send multiple ad requests to serve during the content play (video player)
and wasn't able to find any module for the same
but later i found that multiple requests can be served by adding multiple response in the ad tag itself, it can be done by the ADOPS person and it worked
so thanks anyway
you can close this issue now.
