### ISSUE TITLE
generate url link dukekatte

### ISSUE THREAD

**Issue by dukekatte** [ampproject/amphtml#40196]
generate google site url website link 
www.dukekatte.com   
send @ g mail link  url 
dukecbtm34101978@gmail.com
generate  my phone number link connect all social media 9004201732 
https://youtube.com/@dukekatte8586?si=80HwuIBHfMgIiokP

https://www.facebook.com/profile.php?id=61556380393259&mibextid=ZbWKwL

https://x.com/dukekatte?t=qUwoOO3ZegDGLVoLbgsjig&s=09

https://www.instagram.com/dukeinstanov2023?igsh=MXY0OTZzenhuMmJldg==

**Comment by erwinmombay** [comment]
closing. feel free to re-open if you have more information but this doesnt seem like a bug or feature request
