### ISSUE TITLE
Support low-res placeholder/preview for amp-img (progressive image loading)

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#4020]
A recent design pattern has been to support progressive image loading: Where an image will be presented on a page, a blurred lower-res version (consuming just 100s of bytes) is first displayed and then gracefully animated into the full-res version that's intended to show. This issue is tracking adding such a feature to AMP.

Key design questions:
- Markup and opt-in/out (i.e. is this a default behavior?)
- Can publisher specify the low-res version?
- What's the role of an AMP cache? Can the publisher specify to let the AMP cache automatically produce the lower-res version?

cc @cramforce @dvoytenko @ericlindley-g, who I've previously discussed this with.

**Comment by dvoytenko** [comment]
One approach we have is to do this automatically based on the `srcset`. `amp-img` will calculate two versions: optimal (as is now) and lowres. Two images will be created for both versions: lowres above optimal and both images are loaded. As soon as optimal is loaded, lowres is removed.

Expected issue: progressive images return "loaded" message often way before the image can be rendered in a meaningful way.

**Comment by cramforce** [comment]
First thing would be to support `lowsrc` (which is an actual thing) on `amp-img`

For this to be widely used we'd need to auto-populate it in the cache. It is then typically inlined into the document to avoid the HTTP request overhead.

**Comment by dvoytenko** [comment]
Oh. That's really cool. Should we to start enable `lowsrc` in the validator and propagate it to `img`?

**Comment by dknecht** [comment]
+1. 

CloudFlare did this in the past by using a few pixel image that gets stretched on canvas element and the replaced 

https://blog.cloudflare.com/mirage2-solving-mobile-speed/

**Comment by rudygalfi** [comment]
cc @alanorozco

**Comment by jpettitt** [comment]
You can do it on AMP with CSS.   We're doing it conditionally if we have CSS budget to hold the images.  It adds about 400 bytes of CSS per image.  We only do it on images greater than 50x50 pixels.

Turn off caching and throttle to 4g for the full effect.

http://amp.toofab.com/2017/06/07/the-only-5-buzzworthy-moments-from-the-2017-cmt-music-awards-video

**Comment by choumx** [comment]
This is now implemented with `.i-amphtml-blurry-placeholder`.
