### ISSUE TITLE
Scrolling jank - page is only scrollable a few pixels with gentle swipes

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#4031]
Please walk through the following steps for reporting an issue about AMP:

## Short description of your issue:

The following page exhibits scrolling jank: https://www.google.com/amp/www.dailymail.co.uk/tvshowbiz/article-3686840/amp/Adriana-Lima-sizzles-skimpy-red-bikini-lounges-Mykonos-beach-German-footballer-Sami-Khedira-following-team-s-disappointment-Euros.html#

If you try a gentle swipe to scroll, the page will only scroll a few pixels. If you do a more forceful scroll, then you can scroll the entire page as expected.

## How do we reproduce the issue?

Please post a public URL and ideally post a reduced test case. E.g. on jsbin.com that exhibits only your issue and nothing else.

1. Go to https://www.google.com/amp/www.dailymail.co.uk/tvshowbiz/article-3686840/amp/Adriana-Lima-sizzles-skimpy-red-bikini-lounges-Mykonos-beach-German-footballer-Sami-Khedira-following-team-s-disappointment-Euros.html# on a phone.
2. Gently scroll

Also reproduces on the standalone URL: www.dailymail.co.uk/tvshowbiz/article-3686840/amp/Adriana-Lima-sizzles-skimpy-red-bikini-lounges-Mykonos-beach-German-footballer-Sami-Khedira-following-team-s-disappointment-Euros.html

## What browsers are affected?

Reproducible on Android Chrome - Nexus 6P

## Which AMP version is affected?

1468017284333

Is this a new issue? Or was it always broken? Paste your AMP version. You can find it in the browser dev tools.

**Comment by cramforce** [comment]
Strange case. I collected a timeline and it looks clean, even though the page is super janky.

Removing the sticky ad doesn't make a difference.

**Comment by cramforce** [comment]
Trace https://drive.google.com/file/d/0B4IOxKkr6fGqWHQ0QTdqaVhOZ3c/view?usp=sharing

**Comment by dvoytenko** [comment]
The problem with the following CSS:
```
body {
  overflow-x: hidden;
}
```
This implicitly sets `overflow-y: auto`, which AMP doesn't allow, but misses this implicit case. The solution for us would be to override this value.

**Comment by dvoytenko** [comment]
@rudygalfi We will fix this on our side, but given the deployment cycle, please feel free to reach out to Daily Mail to fix as well.

**Comment by cramforce** [comment]
I pinged them on an existing thread, but we should generally fix it.

**Comment by RByers** [comment]
To clarify, the problem is not that this was "janky" but that there are two distinct scrollers involved - one nested in the other.  In Chrome and Safari, each touch gesture [scrolls at most one scroller](https://bugs.chromium.org/p/chromium/issues/detail?id=526462).

**Comment by cramforce** [comment]
Yep, well, but that is still jank, just for very different reasons from our day-to-day of business of finite speed CPUs and such :)
