### ISSUE TITLE
TypeError: c.win.postMessage is not a function. (In 'c.win.postMessage(d,c.origin)', 'c.win.postMessage' is undefined)

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#4034]
Version: 1467308799816
iOS 9.3.2

article: https://cdn.ampproject.org/v/www.dailymail.co.uk/news/article-3685252/amp/Jeb-says-Trump-never-build-Mexico-wall-believers-feel-betrayed-think-Donald-win-White-House.html?amp_js_v=5

user agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/51.0.2704.104 Mobile/13F69 Safari/601.1.46

error seems to be occurring here https://github.com/ampproject/amphtml/blob/master/src/iframe-helper.js#L350 from amp-ad.js usage

not sure if this still exists in canary/master HEAD as the ads code has changed significantly with the a4a changes.

**Comment by erwinmombay** [comment]
caused by https://github.com/ampproject/amphtml/issues/4035

**Comment by erwinmombay** [comment]
@zhouyx should this be fixed already? still seeing this in canary/prod

**Comment by zhouyx** [comment]
I honestly don't know. seems but there are other causes that I fail to find.

**Comment by erwinmombay** [comment]
im still seeing this in production

**Comment by jridgewell** [comment]
Is there a stack trace? It's either `#sendEmbedInfo_` or `#sendEmbedSizeResponse_` causing the issue.

**Comment by erwinmombay** [comment]
dont have a stack trace unfortunately, all the errors i saw were coming from ios + safari (i think)

**Comment by erwinmombay** [comment]
@jridgewell appreciate the fix, this was one of our main offenders in high error rates
