### ISSUE TITLE
Ability for amp-ad to refresh itself after declared time 

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#4038]
At the moment amp-ad doesn't have a way to refresh itself. Some ad servers would like the ability to refresh themselves after the user has stayed on the page for a certain time period. 
@cramforce

**Comment by lannka** [comment]
I suppose this is speaking about a4a? 

For the current amp-ad, it's up to the ad network's SDK to do periodical refresh.

**Comment by jasti** [comment]
No, don't mean A4A. 
At an amp-ad level, we should allow publishers to set how frequently they'd like an ad to refresh. So the runtime can take care of invoking this across any ad server. Any downsides?

**Comment by cramforce** [comment]
I think it makes sense to implement on the AMP level as this is something that could be implemented as a cross cutting thing, independent of the ad network.

It be interesting to know how many publishers would use it.

**Comment by ericlindley-g** [comment]
Slotting into the backlog for now, but please correct/update as needed

**Comment by jasti** [comment]
@ampproject/ads Adserver folks, looking for some input here.  Do you hear this feature request from publishers you support? Do publishers want to auto-refresh a slot on a page? if so, priority?

**Comment by Rooke** [comment]
The demand for this among publishers exists. Sortable had enough of these requests that we allowed the `data-ad-refresh="user 30s event 30s time 30s"` property to give publishers the ability to specify how they wanted to refresh ads. e.g. If the `data-ad-refresh` is set to a time (say 30s), the unit will automatically refresh after 30s in the viewport. I wouldn't call this a high priority issue though, not _that_ many pubs use this feature.

**Comment by yieldmo-rao** [comment]
Hello all,

From our end, we actually haven't had any requests for auto ad refreshes on
AMP pages. Just as an FYI, we have a couple publishers on regular mobile
web (that are on DFP) that use the DFP auto refresh feature, but even those
pubs are few, and haven't requested the same on AMP.

Best,

Rahul

**Comment by jasti** [comment]
Thanks @Rooke and @yieldmo-rao! We'll slot this into backlog unless any other adserver objects and work on higher priority things.

**Comment by jmheist** [comment]
@jasti, Meredith is looking for this feature, or a way to hack it ourselves. any chance this will move out of the backlog soon?

**Comment by jasti** [comment]
Hey @jmheist - I don't think this is being looked at as priority. We'd welcome if you are willing to implement the ability to refresh ads as a general functionality in amp-ad. 
Would you be interested? If so, could you please create an ITI?
Thanks!

**Comment by jasti** [comment]
Closing because of lack of priority.

**Comment by jasti** [comment]
Reopening because of request from the publisher working group.

**Comment by jmheist** [comment]
How do I become apart of this working group? I asked for this for Meredith
and got nothing.

**Comment by jasti** [comment]
Please join here: https://groups.google.com/forum/#!forum/amp-news-publishers-wg
We had a session this morning and slides from the session are posted to the group.

**Comment by jasti** [comment]
This can be split into 3 sub features:

- [ ] Ability to refresh a sticky ad
- [ ] Ability to refresh any ad
- [ ] Ability to refresh ad ad when a user scroll back or forward an that was already previously viewed as if the ad is being loaded for the first time.

**Comment by jerimiah-welch** [comment]
We have a client that just asked for this as well.
