### ISSUE TITLE
add srcdoc support to amp-iframe

### ISSUE THREAD

**Issue by johnduffell** [ampproject/amphtml#404]
https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md
needs to also allow srcdoc as per
https://developers.whatwg.org/the-iframe-element.html#attr-iframe-srcdoc

**Comment by cramforce** [comment]
I'm a bit scared about srcdoc, because it presents an XSS vector if there is a bug in sandbox enforcement.

Would you be happy with data-uri only support?

**Comment by cramforce** [comment]
Decided to implement it.

**Comment by johnduffell** [comment]
yep data uri is fine, either way is fine, thanks Malte

**Comment by cramforce** [comment]
Implemented srcdoc with a data uri for now, but also check for non-presence of allow-same-origin on sandbox attribute, so we can switch later to native srcdoc if there is a problem.
