### ISSUE TITLE
amp-sticky-ad: Need to handle cases when ad has no content

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#4041]
Currently if ad inside `amp-sticky-ad` collapse, the `body-borderBottom` would not be reset, and the close button would still be there at the very bottom of the page. 

One option: fix the size of `amp-sticky-ad` and not collapse with its child.
Another option: when ad collapse, reset `body-borderBottom` to 0, and remove close button.

I personally feel the second option is more optimal.

**Comment by zhouyx** [comment]
What would be a good way to detect `amp-ad` collapse?

**Comment by cramforce** [comment]
I think @jridgewell is handling this in flying carpet.

**Comment by zhouyx** [comment]
Found it to be in `collapsedCallback(child)`. However I am surprised that the `amp-ad` will collapse, because for a fix position, shouldn't it always be in viewport and `attemptChangeHeight(0)` should never succeed?

**Comment by cramforce** [comment]
@zhouyx I think it is because it is at the bottom of the screen, so no content is being pushed. @dvoytenko to confirm. I think allowing it here is correct.

**Comment by zhouyx** [comment]
I did some test, was able to reproduce the case where `amp-ad` collapse. However the measurement result was `elements above the viewport`. Looking into this

**Comment by zhouyx** [comment]
#4056
