### ISSUE TITLE
Safari Technology Preview displays no content for ~8 secs

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amphtml#4047]
On seemingly all AMP pages, the [Safari Technology Preview](https://developer.apple.com/safari/technology-preview/) browser displays a completely blank page for around 8 seconds. (Presumable content only becomes visible at all because the AMP boilerplate kicks in.)

For example:

- https://www.ampproject.org
- http://www.bbc.co.uk/news/amp/science-environment-36780756

Loading these pages with `#development=1` appended to the URL indicates that the pages are valid AMP.

**Comment by dvoytenko** [comment]
/to @erwinmombay could you please take a look?

**Comment by erwinmombay** [comment]
looking

**Comment by erwinmombay** [comment]
looks like safari is no longer respecting just doing:

`document.body.style.animation = 'none';`

you have to now explicitly also do:

`document.body.style.webkitAnimation = 'none';`

to overwrite the amp-boilerplate animation

**Comment by cramforce** [comment]
Wow, bizarre.

Lets add workaround, of course, but please file a https://webkit.org/reporting-bugs/ I think they probably want to fix this.

**Comment by erwinmombay** [comment]
webkit bug reported here https://bugs.webkit.org/show_bug.cgi?id=159791, working on work around in `style.js`

**Comment by erwinmombay** [comment]
@cramforce looks like its been fixed, do we still need to do the workaround?

**Comment by dvoytenko** [comment]
Depends on when next preview is out. If long time - we may want to fix it still. However, let's not do it in `style.js`. If it's a specific bug, let's just fix directly in `makeBodyVisible` by adding `webkitAnimation: none` statement to the setStyles.

**Comment by erwinmombay** [comment]
@dvoytenko that sounds good.
