### ISSUE TITLE
scroll issue in chrome ios emulation

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#4058]
## Short description of your issue:

Cannot scroll in localhost:8000/examples.build/ads.amp.min.html on iphone emulation. Most likely caused by https://github.com/ampproject/amphtml/pull/4039

**Comment by dvoytenko** [comment]
Does it work out of emulator?

**Comment by dvoytenko** [comment]
On an actual device?

**Comment by cramforce** [comment]
@dvoytenko this issue only affects using Chrome with a Safari user agent. No users are affected, but because this is annoying and confusing during development we should still fix it.

**Comment by erwinmombay** [comment]
closing since it is only chrome dev tools issue
