### ISSUE TITLE
Implement placeholder and fallback for amp-video

### ISSUE THREAD

**Issue by gustavopaes** [ampproject/amphtml#406]
Hello,

I am trying to use <amp-img placeholder inside <amp-video, but when I do it, I can't play the video (tap and click does not have effect).

Should this work?

```
<amp-video controls="" src="//video.m.mais.uol.com.br/15630857-9.mp4" width="320" height="200" layout="responsive">
    <amp-img placeholder width=400 height=300 layout="responsive" src="http://thumb.mais.uol.com.br/15630857.jpg?ver=1"></amp-img>
</amp-video>
```

http://codepen.io/anon/pen/QjpvWw

**Comment by dvoytenko** [comment]
`fallback` and `placeholder` uses have been cleaned up and also `poster` attribute is now allowed as well.

**Comment by dvoytenko** [comment]
The validator changes are still pending, so `fallback` and `poster` may show errors even if their usage is correct. I will separately send a notification as soon as the validator has been deployed.
