### ISSUE TITLE
Rename from prefetch to preload was not backward compatible.

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#4060]
Should we patch the current canary with a prefetch method that points at the new name?

Otherwise we run into problems outside the cache during rollout.

CC @erwinmombay

**Comment by erwinmombay** [comment]
@cramforce will do

**Comment by erwinmombay** [comment]
@cramforce can you confirm fix was in https://github.com/ampproject/amphtml/pull/3994 ?

**Comment by erwinmombay** [comment]
ah nevermind, just reread your statement, that makes sense for unversioned.

**Comment by erwinmombay** [comment]
see https://github.com/ampproject/amphtml/pull/4062

**Comment by cramforce** [comment]
@erwinmombay Can you merge this into the canary?

**Comment by erwinmombay** [comment]
@cramforce yes, i just started a build

**Comment by erwinmombay** [comment]
build here https://travis-ci.org/ampproject/amphtml/builds/144783302
