### ISSUE TITLE
add support for AMoAd to amp-ad

### ISSUE THREAD

**Issue by amoad-amoe** [ampproject/amphtml#4063]
Hi, 

We have an ad network service in Japan. (http://www.amoad.com/)
We'd like to add a support to your amp-ad.

Previously, our director contacted you, so we have the corporate CLA now. Can we send a pull-request from my github account anytime soon?

Our CLA name is "AMoAd, Inc.".

Best regards,
Amoe

**Comment by jridgewell** [comment]
Ping @cramforce.

**Comment by cramforce** [comment]
LGTM.

CLA looks good.

**Comment by amoad-amoe** [comment]
Thanks a lot!
I'm looking forward to see our Ads via amp-ad.

but, when can I...

**Comment by cramforce** [comment]
See https://github.com/ampproject/amphtml#releases

- Next Friday you can start testing.
- One week later everybody can use it.

**Comment by amoad-amoe** [comment]
I see. That's great!

**Comment by jridgewell** [comment]
Closed by #4084.
