### ISSUE TITLE
Mustache tags in docs interpreted by Mustache.js on ampproject.org

### ISSUE THREAD

**Issue by rowan-m** [ampproject/amphtml#4068]
## Short description of your issue:
Documentation is in Markdown, but when this is published to the site (where Mustache.js is included) the tags are interpreted and therefore don't show in the docs.

## How do we reproduce the issue?
https://www.ampproject.org/docs/reference/extended/amp-mustache.html
Should display:
```
Hello {{world}}!
```
Renders as:
```
Hello !
```

https://www.ampproject.org/docs/reference/extended/amp-access.html
Should display:
```
You are reading article {{views}} out of {{maxViews}}.
```

Renders as:
```
You are reading article  out of .
```

**Comment by rudygalfi** [comment]
cc @pbakaus

**Comment by pbakaus** [comment]
Just fixed it here, will be rolled out soon: https://github.com/ampproject/docs/commit/9116cc590787b68340aa29f7367ddf568ac3bd29 thanks for reporting!

**Comment by ericlindley-g** [comment]
@pbakaus Marking as closed, but please re-open if this resurfaces after the change is rolled out
