### ISSUE TITLE
amp-sidebar: Scrolling the sidebar, scrolls the main page

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#4073]
When sidebar is visible, one can not scroll the main page since it is masked but scrolling the sidebar will scroll the page when it reaches the end of sidebar scrolling area.

**Comment by dvoytenko** [comment]
Scrolling leaking is really hard to solve fully on iOS. Usually the cost is too high. If you find a way - definitely please share. But please keep one nuance in mind: in the iframed mode (our main mode) the scroll leaking shouldn't happen.

**Comment by cramforce** [comment]
In which browser does this happen?

**Comment by aghassemi** [comment]
Happens in Chrome, haven't tried others yet.

**Comment by aghassemi** [comment]
Thanks @dvoytenko. I was hoping this would be as simple as changing overflow to hidden on body while sidebar is open but yeah after reading your comment, found that doesn't work on iOS version of Safari because of https://bugs.webkit.org/show_bug.cgi?id=153852 :( 
We probably should not do anything crazy for this, maybe we just do the simple fix for non-iOS and wait hope for https://bugs.webkit.org/show_bug.cgi?id=153852 getting addressed.

**Comment by dvoytenko** [comment]
@aghassemi Correct. And there are many other issues, such as:

- In some browsers/versions the `scrollTop` is reset as soon as `overflow:hidden` is set.
- In some browsers/versions history restores scroll position because you try to manipulate as of these properties
- Setting `overflow:hidden` may actually cause full-page relayout.

**Comment by ericlindley-g** [comment]
This looks like it goes in the backlog, but @aghassemi please correct if you plan on work in either "current" or "next" timeframe

**Comment by aghassemi** [comment]
:+1:  for backlog

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)

**Comment by ericlindley-g** [comment]
Re-opening :)

**Comment by aghassemi** [comment]
Merged with a similar (technically duplicate) https://github.com/ampproject/amphtml/issues/4073 Closing this one since other one has more details and comments.

**Comment by ericlindley-g** [comment]
@aghassemi Double-checking: which bug did you dupe this one to?

**Comment by aghassemi** [comment]
Sorry updated the comment: #6487
