### ISSUE TITLE
Render delaying extensions should call resources.schedulePass() after DOM mutation

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#4075]
As pointed out by @cramforce and @dvoytenko here:
https://github.com/ampproject/amphtml/pull/3983/files/e25e1b372db0963379f08b9f84c37fc73d2cf8f1..91bfc574cd3ef180ebad3895f2a4e58d23f897e8#r70861329

**Comment by dvoytenko** [comment]
There's no API for this yet. And we should be careful opening it. It should definitely be restricted via presubmits. But here's what needs to be done in the `Resources` class:
```
this.relayoutAll_ = true;
this.schedulePass(1);
```

**Comment by ericlindley-g** [comment]
Based on discussion in #3983, it sounds like this should be in "Next", but I'm passing to @lannka to correct/update as needed.
