### ISSUE TITLE
SubtleCrypto available on secure origins only

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#4077]
There is a non-fatal error that occurs during our attempt to use SubtleCrypto whenever we want to use it outside of secure (which includes localhost) origins.

We should probably avoid the attempt to use the API under these circumstances and immediately fall back to the closure implementation.

This may affects the feasibility of late loading the closure implementation (#3888).

**Comment by lannka** [comment]
What is `secure origin`?

I found this [article](https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features) but not sure if that's relevant.

**Comment by cramforce** [comment]
https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features

**Comment by cramforce** [comment]
That is the right article. The error thrown points to that URL.

You can easily repro, by trying AMP on a non-secure origin.

**Comment by lannka** [comment]
Thanks god we catch all exceptions. :-)

**Comment by cramforce** [comment]
Yep :)
Not a high priority, but I prefer bailing out without exceptions. Otherwise they can obfuscate debugging.

**Comment by ericlindley-g** [comment]
Sounds like this goes in "Backlog" from the discussion, but @lannka, please update/correct as needed—thanks!

**Comment by cramforce** [comment]
Lets do it, since the fix should be super trivial and exception hygiene is important.

**Comment by lannka** [comment]
@cramforce should we just check if `UA == chrome && scheme == https` ?
I don't see a native API to test a secure origin.

**Comment by cramforce** [comment]
Has nothing to do with Chrome. Secure origin is basically: `scheme ==
'https' || hostname == 'localhost'`. Can be added to `url.js`

**Comment by lannka** [comment]
Currently seems only Chrome enforces this. Tried on FF it works fine.

**Comment by lannka** [comment]
@dvoytenko @jridgewell Not sure if you are aware that this restriction also applies to ServiceWorker:
http://www.html5rocks.com/en/tutorials/service-worker/introduction/#toc-before

**Comment by dvoytenko** [comment]
Correct. I've run into this in PWA as well.

**Comment by lannka** [comment]
As @cramforce suggested, I'll introduce a util method in `url.js` to test secure origin, so it can be reused.

For Crypto API, I will put the secure origin limitation on Chrome only, so other browsers can still be fully benefited with native API? Sounds good?

**Comment by cramforce** [comment]
I think the secure origin limitation is in the spec. For most crypto
operation doing them on a non-secure origin inherently doesn't make any
sense at all.

**Comment by lannka** [comment]
After discussion in another thread, we agree to not check secure origin ourselves. Instead, we'll just check the error message, and mute it if it contains pattern like "secure origin", since it's an expected fallback.

@cramforce pls correct me if I have misunderstanding.

**Comment by cramforce** [comment]
Sounds good.
