### ISSUE TITLE
Components outside of viewport on the x-axis still get scheduled

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#4080]
```
  <div style="transform:translateX(-900px)">
    <amp-img src="img/ampicon.png" width="15" height="15"></amp-img>
  </div>
```
gets scheduled but

```
  <div style="transform:translateY(-900px)">
    <amp-img src="img/ampicon.png" width="15" height="15"></amp-img>
  </div>
```
does not get scheduled.

I have a fix for this already but wanted to have discussion to make sure this is indeed a bug and not intentional. Also the fix for this will potentially break users who may have intentionally or unintentionally expected this behaviour ( e.g. putting their `amp-pixel` in an offscreen div for whatever reason).

**Details**
The issue is that `renderOutsideViewport()` in resource.js does not consider x-axis before declaring something is already in viewport. Just needs a `viewportBox.right < layoutBox.left || viewportBox.left > layoutBox.right` check.

@cramforce  @dvoytenko @jridgewell

**Comment by cramforce** [comment]
Yeah, I think we should fix it, since it is so simple.

**Comment by dvoytenko** [comment]
That's weird. Is transform misreported in the `getBoundingClientRect`? I'm pretty sure runtime checks on that.

**Comment by cramforce** [comment]
I believe we are simple not checking horizontal at all.

**Comment by dvoytenko** [comment]
We definitely do. But it could easily be a bug.

**Comment by jridgewell** [comment]
`-10000px` is used as a sentinel value for "unmeasured".

**Comment by aghassemi** [comment]
@jridgewell Not a special-case issue, exists with other values as well. Updated the description not to use 10000

**Comment by shimonenator** [comment]
Please see my comments on #4081 since this broke preloader for horizontal scrolling elements.
