### ISSUE TITLE
Optimize getMode()

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#4086]
Our `getMode()` function currently computes work that we know cannot be true (such as being in test mode). This code should be compiled away and replaced with simple `true`, `false`.

The function does come up in profiling.

**Comment by erwinmombay** [comment]
weird, this should be the case. checking for regression

**Comment by erwinmombay** [comment]
@cramforce did you use --fortesting? i currently suppress dce'ing them with the flag

**Comment by erwinmombay** [comment]
double checked again, and yes if i do the replace with --fortesting a few tests start breaking
https://travis-ci.org/ampproject/amphtml/builds/144914926

**Comment by cramforce** [comment]
Yeah, we should not DCE with `--fortesting`. Just wanted to make sure we are on the same page:

I want to make sure that this line:
https://github.com/ampproject/amphtml/blob/master/src/mode.js#L71

is being killed, because it is pretty expensive to evaluate.

**Comment by erwinmombay** [comment]
@cramforce checking

**Comment by erwinmombay** [comment]
looks like that line isnt killed, working on it
