### ISSUE TITLE
Optimize FixedLayer

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#4087]
Or get rid of it :)

It does take significant time in profiles. E.g. on this sample page
http://localhost:8000/min/m.huffpost.com/us/entry/us_5788012ce4b08608d333ca52/amp#prerender=1

**Comment by dvoytenko** [comment]
With transfer or w/o transfer? I.e. is it with Safari user agent emulation?

**Comment by cramforce** [comment]
I tested without

**Comment by dvoytenko** [comment]
In that case I assume most of cost is processing the stylesheet model and testing position:fixed.

**Comment by ericlindley-g** [comment]
@dvoytenko  Sounds like this goes into "Backlog", but please update/correct as needed

**Comment by adelinamart** [comment]
Is this still needed?

**Comment by dvoytenko** [comment]
There should be some opportunities to optimize with layers.

**Comment by adelinamart** [comment]
@jridgewell any updates here? Thanks

**Comment by jridgewell** [comment]
Need layers first.
