### ISSUE TITLE
The load time in AMP page is increased to 7 to 10 seconds

### ISSUE THREAD

**Issue by amans1690** [ampproject/amphtml#4093]
## Description of your issue:
Load time is increased 7 to 10 seconds.

## How do we reproduce the issue?
URL: http://m.timesofindia.com/sports/football/top-stories/Lionel-Messi-quits-international-football-after-Copa-loss/amp_articleshow/52933632.cms
You can open the url on chrome 
1. for opening the url you have to first set the user agent in chrome dev tools to iphone4 or nexus4/5
2. Then try to access the url

## Which AMP version is affected?
Powered by AMP ⚡ HTML – Version 1468521759997

**Comment by cramforce** [comment]
- What is your measuring methodology?
- Did this regress between 2 particular AMP versions?

Note that the `load` event is meaningless for AMP. Its results are pretty random, because the requests are counted towards it depend on network order.
