### ISSUE TITLE
Invalid URL protocol 'skype:' for attribute 'href' in tag 'a'.

### ISSUE THREAD

**Issue by mdziekon** [ampproject/amphtml#4094]
I've discovered that ``skype:`` URI protocol is not supported by the validator.  
It throws on hrefs like this:
> skype:myskypeuser?chat

with the following error:
> Invalid URL protocol 'skype:' for attribute 'href' in tag 'a'.

Since there was a similar request to support Threema, should the Skype URI API (described here: https://msdn.microsoft.com/en-us/library/office/dn745882.aspx) be supported as well?

**Comment by cramforce** [comment]
Yes, if we don't yet.

**Comment by ericlindley-g** [comment]
@honeybadgerdontcare I've temporarily put this into "pending triage", but please update with a more specific milestone when you have a sense of target. Thanks!

**Comment by Gregable** [comment]
Closing, but will be a little while longer before it's released.

**Comment by Gregable** [comment]
This is now live everywhere.
