### ISSUE TITLE
Update A4A to improve handling of amp-runtime style

### ISSUE THREAD

**Issue by tdrl** [ampproject/amphtml#4095]
It turns out that AMP uses the `amp-runtime` style tag to maintain critical element styling and lifecycle information _and_ that this information doesn't penetrate Shadow DOMs.  The consequence is that the A4A Shadow DOM rendering path breaks the lifecycle of AMP elements in ad creatives rendered in Shadow DOM.

#4070 introduces a short-term fix that clones the `amp-runtime` style from the host document.  However, AMP is working on a better approach.  This is a tracking bug to update the key parts of A4A code when the correct approach is available.  Key locations to update are:

https://github.com/ampproject/amphtml/pull/4070/files#diff-b139e3c4641f6d160f2832cba8be0761R548

and

https://github.com/ampproject/amphtml/pull/4070/files#diff-eb0a035b49b4b85814a07227e827e329R65

**Comment by ericlindley-g** [comment]
Passing to @dvoytenko to slot in the right milestone
