### ISSUE TITLE
Compiler: rewrite some instances of `serviceFor`

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#4096]
/cc @erwinmombay @cramforce 

Two instances I have in mind that will be the most sensitive: `extensionsFor` and `ampdocFor`. We can think about these services as "meta-services" - they are what makes other services work. I'm totally open to actually using a completely different API for them to make them inline-able to compiler/JIT. Suggestions welcome. The bottom line is that calling `ampdocFor` should become a completely trivial inlined expression. Whether it is `window.services.ampdoc.obj` or `window.AMPDOC_SERVICE` is less important to me. Currently, I'm pretty sure our version of `getServiceFor` is not very optimizable/inline-able.

**Comment by cramforce** [comment]
I think `getWin()` might be a better first target. Inlining makes sense, though.

`window.services.ampdoc.obj` is still 3 hash lookups.
