### ISSUE TITLE
"FLEX_ITEM" is not described in the online doc

### ISSUE THREAD

**Issue by klemy202** [ampproject/amphtml#4102]
## Short description of your issue:

On the [page of `amp-img.md`](https://github.com/ampproject/amphtml/blob/master/builtins/amp-img.md) we can find a `FLEX_ITEM` in the list of *Supported Layouts*, but It is not described in the [online documentation](https://www.ampproject.org/docs/guides/responsive/control_layout.html).

## How do we reproduce the issue?

Read the doc!

## What browsers are affected?

All browsers (I gess!).

## Which AMP version is affected?

Current website version, that is `1468521759997`.

**Comment by erwinmombay** [comment]
@klemy202 thanks for reporting! do you mind filing this issue against https://github.com/ampproject/docs/issues/new instead?

cc @Meggin

**Comment by ericlindley-g** [comment]
Copied to https://github.com/ampproject/docs/issues/142
