### ISSUE TITLE
amp-ad / onResizeDenied and onResizeSuccess not called anymore

### ISSUE THREAD

**Issue by RonanDrouglazet** [ampproject/amphtml#4109]
## Short description of your issue:

Hi AMP Team ! 

As we can see here https://github.com/ampproject/amphtml/tree/master/ads#ad-resizing
when an ad ask for a resize, they should get a response with onResizeDenied OR onResizeSuccess

It's not the case anymore since the July 14 Release (https://github.com/ampproject/amphtml/releases/tag/1468017284333)

## How do we reproduce the issue?

You can reproduce here http://amp.teads.tv/test/resize.html

This sample only load a little js in our amp-ad component in place of our production framework

```
document.body.style.background = "orange"

window.context.onResizeDenied(function() {
    document.body.style.background = "red"
})

window.context.onResizeSuccess(function() {
    document.body.style.background = "green"
})

var askResize = function() {
    window.context.requestResize(window.innerWidth, 200)
    setTimeout(askResize, 1000)
}

askResize()
```

As you can see, the background color has to change if we received a response

Currently in the sample, the resize seems to be accepted because our component is "open" (we start to height=1)

## What browsers are affected?

All browsers / devices 

## Which AMP version is affected?

Since 1468017284333

**Comment by sriramkrish85** [comment]
![screen shot 2016-07-18 at 11 07 28 am](https://cloud.githubusercontent.com/assets/1037311/16925177/d7d736c2-4cd7-11e6-9985-715e911cba65.png)

**Comment by sriramkrish85** [comment]
@RonanDrouglazet , Thanks for filing the bug.

 i am seeing the ad turn to red. (when  i inspect on chrome). But never seeing it turn green when below viewport.

I dont see any changes to the API in the said release. Will continue to investigate and check if this is really an issue.

**Comment by RonanDrouglazet** [comment]
Thanks for your time @sriramkrish85  ! Yes i know, i have checked the changelog but does not see anything related either

But if i use the previous release (July 7), everything is ok ! 

Also, we really don't have the same result with this sample page. I always have an orange ad, i tried on iphone / android / desktop (@work) and just now, at home, on a chrome desktop (mac os) and iPhone simulator, same, always orange (so no response at all)

But you, you have a response (denied) and i think it's normal, the little script loop on requestSize, even if we get a response (little mistake from my sample, fixed by tomorrow)

Still, why don't we have the same result at all ? I never have any response (color stay orange) @work & @home... really strange 

![capture d ecran 2016-07-18 a 22 43 10](https://cloud.githubusercontent.com/assets/4659372/16930307/e690c4f8-4d3b-11e6-8b6c-d08782e2e136.png)
![capture d ecran 2016-07-18 a 22 53 54](https://cloud.githubusercontent.com/assets/4659372/16930308/e6a28968-4d3b-11e6-8bd2-897a0bab1e26.png)

**Comment by RonanDrouglazet** [comment]
When i load this page on the top, no scroll, i never get any response from requestResize

When i load this page OVER our amp-ad component, resize is denied (normal) but as you can see in my attached screen record, i have a response ! Denied (red), but still, it's a response

So in the "classic" use case, it never work for me :( 

[amp-resize.mp4.zip](https://github.com/ampproject/amphtml/files/370163/amp-resize.mp4.zip)

**Comment by lannka** [comment]
Did the fix work? Is it time to close this issue?

**Comment by amphtml-team** [comment]
Yes

**Comment by RonanDrouglazet** [comment]
Yes it works perfectly !! Thanks a lot
