### ISSUE TITLE
Implement shared video interface for amp-video and youtube

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#4113]
Lets see how far we get with implementing #3945 against `amp-video` and `amp-youtube` as a blackbox.

This should help as a reference implementation for #3945 for other players.

**Comment by ericlindley-g** [comment]
From #3945 it sounds like "Next" is the right milestone for this, but please feel free to correct/update

**Comment by adelinamart** [comment]
Do we still need to work on this?

**Comment by aghassemi** [comment]
nope, both amp-video and youtube support the new video interface. Closing.
