### ISSUE TITLE
Implement extensive tests for amp-ad/amp-iframe resizing/IntersectionObserver

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#4119]
We should significantly improve test coverage for iframe resizing and `IntersectionObserver` in `amp-iframe`  and `amp-ad`.

These tests should make a real iframe and then make sure the right messages are being passed around.

CC @sriramkrish85

**Comment by ericlindley-g** [comment]
@muxin  — Slotting in "pending triage" for now. please update the milestone when you have a sense of when work will start. Thanks!

**Comment by muxin** [comment]
OK

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
