### ISSUE TITLE
Fix amp-carousel integration tests

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#412]
I disabled them for now. They fail near 100% on my local. Please advise.

**Comment by rudygalfi** [comment]
Sweeping old bugs: Is this still needed?

**Comment by erwinmombay** [comment]
@rudygalfi yes definitely, i will get to some carousel work by next week

**Comment by ericlindley-g** [comment]
FYI @erwinmombay , I moved this into the Feb 13 milestone

**Comment by erwinmombay** [comment]
consistently failing on chrome 48 locally. (not on remote 46?) opening again.

**Comment by mkhatib** [comment]
Just tried `gulp test --integration` locally after removing the `.skip` part and it seems to be passing.

**Comment by mkhatib** [comment]
Yup even with `gulp test` these seem to pass.

**Comment by adelinamart** [comment]
Is there anything else needed here?

**Comment by erwinmombay** [comment]
@adelinamart i'll work with the new SETI to fix this

**Comment by adelinamart** [comment]
@erwinmombay shall we assign this to Raghu?

**Comment by cathyxz** [comment]
This was done by @nainar in https://github.com/ampproject/amphtml/pull/18166.
