### ISSUE TITLE
404 status code while getting an image from CDN

### ISSUE THREAD

**Issue by aletorrado** [ampproject/amphtml#4123]
Hi, I'm getting a 404 status code on the images loaded through the ampproject's CDN, don't know exactly why.

Test URL: [http://www.diarioregistrado.com/amp/politica/milagro-sala-desde-la-carcel-tras-la-detencion-de-su-esposo---ya-somos-11-los-presos-politicos-_a578d1b20cfe4c87c72d791f4](http://www.diarioregistrado.com/amp/politica/milagro-sala-desde-la-carcel-tras-la-detencion-de-su-esposo---ya-somos-11-los-presos-politicos-_a578d1b20cfe4c87c72d791f4)

Any idea?

Thanks!

**Comment by erwinmombay** [comment]
@aletorrado can you specify what platform/device/version? quick glance at chrome web and i don't see any 404 errors on the network

**Comment by aletorrado** [comment]
The issue happens on the AMP Project's CDN: [link](https://cdn.ampproject.org/v/www.diarioregistrado.com/amp/deporte-registrado/la-seleccion-de-basquet-cayo-en-un-amistoso-ante-un-rival-de-los-juegos-olimpicos_a578d8901cfe4c87c72d79323?amp_js_v=5#origin=https%3A%2F%2Fwww.google.com.ar&channelid=0&cid=1&dialog=0&prerenderSize=1&viewportType=natural&visibilityState=hidden&paddingTop=54&history=1&p2r=0&horizontalScrolling=0&csi=0&referrer&storage=1&viewerUrl=https%3A%2F%2Fwww.google.com.ar%2Famp%2Fwww.diarioregistrado.com%2Famp%2Fdeporte-registrado%2Fla-seleccion-de-basquet-cayo-en-un-amistoso-ante-un-rival-de-los-juegos-olimpicos_a578d8901cfe4c87c72d79323). You can try through Google Search proxy as well.

**Comment by erwinmombay** [comment]
i see the 404 now

**Comment by erwinmombay** [comment]
@cramforce is this just a content-type issue when the cdn tries to cache the image? their server responds with Content-Type:application/octet-stream for their image assets

**Comment by cramforce** [comment]
Most likely. @aletorrado Could you switch to a correct mime type for images (something starting with `image/`?

@jmadler Did we ever discuss allowing octet-stream for images?

**Comment by cgreczkowski** [comment]
I've got a similar issue; here's an example
[https://www.google.ca/amp/s/chargehub.com/amp/en/countries/united-states/hawaii/waipahu.html](https://www.google.ca/amp/s/chargehub.com/amp/en/countries/united-states/hawaii/waipahu.html)

Strange, since half the images load and the other half are 404's. There isn't an obvious pattern; e.g. some images stored in the /images/ folder load, other don't. Same with the images that are hosted on ParseServer (ParseTFSS).

**Comment by cramforce** [comment]
@cgreczkowski The reason is that the images you serve from cloudfront have `application/octet-stream` as their mime type. Please fix that to a proper image mime type.

**Comment by cgreczkowski** [comment]
@cramforce when I try the same image e.g. [633_Image.png](https://chargehub.com/images/city_images/633_Image.png) our website, I see Content-Type:image/png

So the image is served correctly on our site, but incorrectly from the CDN. Any guesses?

**Comment by cramforce** [comment]
Try renaming to .jpg.

**Comment by cgreczkowski** [comment]
@cramforce Wow, that fixed it. Thank you so so much, this has been driving me crazy for over a week!

**Comment by adelinamart** [comment]
Seems issue is fixed. Feel free to open a new one if there are still any problems. Thanks.
