### ISSUE TITLE
Doubleclick Amp Ad wraps creative in friendly iframe; behavior not documented

### ISSUE THREAD

**Issue by patrickcbrady** [ampproject/amphtml#4128]
## Issue Description

While testing with an AMP ads tag using Doubleclick with the 'useSameDomainRenderingUntilDeprecated' set to 1, the creative that the adserver returned was wrapped inside of an IAB-compliant friendly iframe. This prevents the ad from accessing the Amp Ads "window.context" variable to retrieve information without first navigating up through the hierarchy of parent windows to find the one that contains the "context" object (in this case, the first parent). Is this expected behavior? It does not appear to be addressed in the documentation at https://github.com/ampproject/amphtml/blob/master/ads/README.md or at https://github.com/ampproject/amphtml/blob/master/ads/google/doubleclick.md

My issue is not necessarily with the behavior itself but with the lack of documentation. The only place where I have seen any mention of this behavior is in passing mention on other issues such as https://github.com/ampproject/amphtml/issues/2236

The Amp Ads documentation leads creative vendors to expect that their creatives should be able to find and access an object at "window.context" to retrieve the information outlined in that documentation. If there are specific cases where that is known to not be guaranteed, those cases should be included in the documentation.

## Reproduction

1. Visit the test page at https://dl.dropboxusercontent.com/s/2thb752piamzknt/amp-test.html
2. Open developer tools and reload the page
3. Execution will pause for debugging
4. In the console, type window.context and press return. The result will be undefined. 
5. In the console, type window.parent.context and press return. The result will be the AMP context object.

## Affected Browsers

This issue is present on all browsers

## Affected AMP version

1468883441627 is the first version I tested, but it seems from the discussion in https://github.com/ampproject/amphtml/issues/2236 that this issue has been present since at least February.

**Comment by jasti** [comment]
@patrickcbrady thanks for raising this.
@michaelkleber do you know if 'useSameDomainRenderingUntilDeprecated' has regressed?

**Comment by michaelkleber** [comment]
@patrickcbrady As the documentation for `ads` says, "Depending on the ad server / provider some methods of rendering ads involve a second iframe inside the AMP iframe. In these cases, the iframe sandbox methods and information will be unavailable to the ad. We are working on a creative level API that will enable this information to be accessible in such iframed cases and this README will be updated when that is available."

For useSameDomainRenderingUntilDeprecated users, the standard DoubleClick GPT tag is used to request and render ads.  Whether the ad ultimately renders directly inside the AMP-created iframe or nested within another layer of friendly iframing is a complex decision that depends on the creative type, the relevant line item's setup in the DFP front-end, and probably other things.  So I think "the ad might end up inside another layer of iframing" is unfortunately the appropriate level of precision.
