### ISSUE TITLE
Add warning in validator about the deprecation of using amp-ad without loading the extension

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#4140]
Is <script async custom-element="amp-ad" src="https://cdn.ampproject.org/v0/amp-ad-0.1.js"></script> required for running ads? I didn't think so because ads just work without it? e.g. http://dfp-amp-testing-1185.appspot.com/amp_tests/dfp-image-layouts-fixed-demo.html

If not, should we update the documentation here ? https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad/amp-ad.md#-amp-ad

**Comment by zhouyx** [comment]
It's not really required, but like all other extensions it would be good to include script to the page. 
I think we deliberately add that require for script line to the documentation to encourage users including script in future. @cramforce

**Comment by jasti** [comment]
Thanks @zhouyx! I think it was throwing off some folks as to how ads were working without the ads script :)  I'll send a tiny PR to clarify here.

**Comment by Gregable** [comment]
Initially the ad code was part of the main runtime, but was moved to a separate include. Ideally documents would add the include directly, which would speed up loading, however we don't want to break everyone.

Maybe we can leave this issue open as a TODO for the validator to emit warnings for pages that use `<amp-ad>`, but do not include `amp-ad-0.1.js`

**Comment by jasti** [comment]
Cool! I've clarified in a PR for doc. Assigning to you.

**Comment by Gregable** [comment]
Warning should be live in a couple hours.
