### ISSUE TITLE
one test in test-resources description misleading 

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#4145]
https://github.com/ampproject/amphtml/blob/master/test/functional/test-resources.js#L1015

I found here height diff is 0, but the description is 
> 'should NOT change size when below viewport, but decreases'

What is the purpose of this test case? 
@sriramkrish85  @dvoytenko

**Comment by dvoytenko** [comment]
It is confusing. From the looks of it - it doesn't call `changeSize` because the height actually doesn't change. In either case, even if the height decreases it should be allowed below the viewport.

**Comment by zhouyx** [comment]
Yes. What about we change the description to should NOT change size when the height doesn't change, since we already have one test about "should change size when below the viewport"

**Comment by zhouyx** [comment]
Also it would be super clear if we could make the test here match the 7 conditions we have for `attemptChangeSize` request in `resources-impl.js`

**Comment by sriramkrish85** [comment]
@zhouyx yes that would be great, we should also make sure there are tests for edgecases. Assigning this to you!

**Comment by ericlindley-g** [comment]
@zhouyx   — Slotting in "pending triage" for now. please update the milestone when you have a sense of when work will start. Thanks!
