### ISSUE TITLE
[Refactoring] Move all service factory code into one file

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#4147]
This will significantly reduce the number of files under `src/` and make code navigation easier.
Listing all available services in one file is also good for learning the code base.

**Comment by ericlindley-g** [comment]
@lannka   — Slotting in "pending triage" for now. please update the milestone when you have a sense of when work will start. Thanks!

**Comment by lannka** [comment]
this will be a big project. @cramforce @dvoytenko want to have you sign off before i start :-)

**Comment by cramforce** [comment]
![LGTM](https://camo.githubusercontent.com/c13eeb81b1485ccc0d2b248f19360c7ba2419167/687474703a2f2f6a756e6b796172642e64616d6f776d6f772e636f6d2f353633)
