### ISSUE TITLE
AMP Validator module engines constraint

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#4156]
We're [saying](https://github.com/ampproject/amphtml/blob/1c4e81d/validator/nodejs/package.json#L6) we only work on node versions `>=0.10.25 <0.11.0`.

**Comment by powdercloud** [comment]
I must have copy/pasted the ^ from somewhere, sorry. Should have read up on semver before. :-)

**Comment by ericlindley-g** [comment]
@powdercloud  — can this be closed?
