### ISSUE TITLE
amp-font not working on Safari

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#4168]
amp-font not working on Safari

## How do we reproduce the issue?

Use Chrome
Go to: [ampbyexample](https://ampbyexample.com/components/amp-font/)
First and third sentences on the example (left of the page) are red

Use Safari
Go to: [ampbyexample](https://ampbyexample.com/components/amp-font/)
First and third sentences on the example (left of the page) are black

## What browsers are affected?

Safari on Desktop, use Private Window to avoid any possible caching.

All browsers? Some specific browser? What device type?

## Which AMP version is affected?

1469143772973

**Comment by ericlindley-g** [comment]
@sriramkrish85   — Slotting in "pending triage" for now. please update the milestone when you have a sense of when work will start on a fix. Thanks!
