### ISSUE TITLE
remove `amp-viz-vega` experiment

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#4171]
Spec: https://github.com/ampproject/amphtml/issues/3824
- [ ] remove entry from `tools/experiments.js`
- [ ] remove `isExperimentOn` and related code in `amp-viz-vega.js`
- [ ] remove `Experimental` from the MD file `amp-viz-vega.md`
- [ ] remove Toggle Experiment button in `examples/viz-vega.amp.html`

**Comment by ericlindley-g** [comment]
@aghassemi   — Slotting in "pending triage" for now. please update the milestone when you have a sense of when work will start. Thanks!

**Comment by erwinmombay** [comment]
@aghassemi want to confirm, this should still be in experimental correct?

**Comment by aghassemi** [comment]
yes

**Comment by adelinamart** [comment]
What's still pending here? Thanks

**Comment by adelinamart** [comment]
@aghassemi I think some of the these can be cleaned up. Thanks

**Comment by aghassemi** [comment]
Still experimental feature and not shipped.

**Comment by eduardogoncalves** [comment]
Hi guys! Any update on this one?

**Comment by aghassemi** [comment]
dedup with https://github.com/ampproject/amphtml/issues/18705
