### ISSUE TITLE
<amp-ad> prints console error:  No messaging channel: timeout​​​

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#4183]
To reproduce:
Open [this](https://storage.googleapis.com/cfuertes/Joystick/Joystick.html) and wait about 20s, then check the console.

**Comment by cramforce** [comment]
@dvoytenko Do we have a way how we can avoid checking whether there is a viewer? I imagine that should be easy.

**Comment by dvoytenko** [comment]
I see. It's an Ad that is an AMP page in a iframe. Currently we assume that any iframed AMP could have a messaging bus. I believe all iframing viewers right now also include `#origin` hash parameter. We can use its presence to determine whether or not we try to establish the messaging channel.

**Comment by cramforce** [comment]
Didn't find `origin`, but lets find one that is always present and run with that.

**Comment by dvoytenko** [comment]
Yeah, it's not documented since the channel establishment is currently outside of AMP itself. But it's necessary for the handshake.

**Comment by cramforce** [comment]
Ah, right. We should really move that code :)

**Comment by ericlindley-g** [comment]
@dvoytenko   — Slotting in "pending triage" for now. please update the milestone when you have a sense of when work will start (or pass to the person doing the work, to update :)   Thanks!

**Comment by lannka** [comment]
This needs to be solved for `amp-inabox` (#5700) to work without console errors.

Here is an example of viewer URL:
```
https://cdn.ampproject.org/v/s/amp.cnn.com/cnn/2016/10/27/politics/obama-commutes-sentences-of-98-people/index.html?amp_js_v=5
#origin=https%3A%2F%2Fwww.google.com
  &exp=a4a%3A0
  &channelid=0
  &cid=1
  &dialog=0
  &prerenderSize=1
  &visibilityState=hidden
  &paddingTop=54
  &history=1
  &p2r=0
  &horizontalScrolling=0
  &csi=0&storage=1
  &viewerUrl=https%3A%2F%2Fwww.google.com%2Famp%2Fs%2Famp.cnn.com%2Fcnn%2F2016%2F10%2F27%2Fpolitics%2Fobama-commutes-sentences-of-98-people%2Findex.html
```

@dvoytenko @cramforce can you confirm **origin** always exists? How about **viewerUrl**? Sounds like more semantically correct, and less chance for false positive?

**Comment by cramforce** [comment]
I think so, but deferring to @dvoytenko

**Comment by lannka** [comment]
`channelid` will be a safer bet, which is included in every message sent to viewer for viewer to identify sender.

**Comment by cramforce** [comment]
I think `origin` is a bit better, because I don't know what channelid is :) I think that is very specific to their out-of-AMP communication layer.

**Comment by dvoytenko** [comment]
I believe currently `#origin` always exists. However, it's not documented anywhere in our code and not used anywhere in our code directly. It's set by a viewer and read by handshake code deployed from viewer. This is something that we will standardize as we move the messaging itself into AMP Runtime. I think overall, `#origin` is a good value. But one thing to emphasize: we'd normally never use it at face value. It must be confirmed through handshake before we can reliably say that the origin is what it says it is.

**Comment by cramforce** [comment]
Right, I think @lannka only cares about some sentinel to infer that there **might** be a viewer.

**Comment by dvoytenko** [comment]
Ok. Yes then. The `origin` should help then for iframe'd case. I don't think it's set in a webview case though. So please keep that in mind.

**Comment by jridgewell** [comment]
Would `visibilityState` be a good sentinel? By including it, you've guaranteed that you intend to control the AMP document with a viewer.
