### ISSUE TITLE
Trigger window.context.noContentAvailable from external ad script

### ISSUE THREAD

**Issue by antnativo** [ampproject/amphtml#4185]
Is it possible to trigger the window.context.noContentAvailable() from the external script loaded via loadScript() instead of adding it to the amp-ad code?  If there are not ads served, we would like to trigger this event on our script instead of updating the amp-ad js code.

**Comment by antnativo** [comment]
@cramforce Could you answer this?

**Comment by cramforce** [comment]
Yes, it is possible. I think when I reviewed your code originally I
recommended moving as much as possible into your late loaded package, so
you can avoid needing to make changes in the AMP repo.

**Comment by jridgewell** [comment]
Assigning this to @lannka since @cramforce is supposed (😛) to be on holiday.

**Comment by antnativo** [comment]
@cramforce  Thanks. I do remember you indicated that to me and I know our script is appended. But I just wanted to double. Thanks for you help while on Holiday.

**Comment by antnativo** [comment]
@jridgewell No need to reassign. Question was answered. You can close it
