### ISSUE TITLE
Presubmit task that checks that private vars follow closure styleguide

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#4189]
Unfortunately, we are following Closure styleguide for private vars. Unless/until we switch, we need an easy presubmit check that we are NOT using `_var` style.

(Eventually, I'd like to switch the whole repo to do this style, pending discussion)

**Comment by ericlindley-g** [comment]
@erwinmombay   — Slotting in "pending triage" for now. please update the milestone when you have a sense of when work will start. Thanks!

**Comment by erwinmombay** [comment]
@dvoytenko sorry didnt see this. should be easy to implement. could you point me to the style guide you are wanting to follow?

**Comment by dvoytenko** [comment]
See here: https://google.github.io/styleguide/javascriptguide.xml#Naming

"Private properties and methods should be named with a trailing underscore."

As much as I'd prefer the other way around, this is the common style right now in our repo. If we change it - we'll just do a global replace. As it stands, however, I believe we are using trailing underscore as an indication that the name can be obfuscated.
