### ISSUE TITLE
Add documentation for whitelisting AMP extension usage in amp-ad

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#4192]
Not all AMP extensions should be allowed in AMP documents that are ads. (for A4A). Create docs to 
a) highlight which ones are currently allowed
b) Methodolody behind why an extension is allowed/ denied
c) whitelisting process

**Comment by ericlindley-g** [comment]
@lannka   — Slotting in "pending triage" for now. please update the milestone when you have a sense of when work will start. Thanks!

**Comment by jasti** [comment]
Pretty well documented in https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/amp-a4a-format.md. Closing.
