### ISSUE TITLE
pause and resume callbacks should be called after layout finished.

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#4195]
Currently both `pauseCallback()` and `resumeCallback()` can be called anytime after `buildCallback()`, we should change that so they are only invoked after layout is complete. See [PR 4137](https://github.com/ampproject/amphtml/pull/4137/files/34544961928edc20595861ce08d4e9240b25e01a#r72133405) 

This involves:
- [ ] `resource.js`: `pause()` and `resume()` should check `ResourceState.LAYOUT_COMPLETE` instead of `ResourceState.NOT_BUILT`
- [ ] Ensure places that manually call `scheduleLayout()` and `scheduleResume()` (eg. sidebar) , chain them in order.
- [ ] Ensure components that override  `pauseCallback()` or `resumeCallback()` won't regress due to this change since now there is chance their  `pauseCallback()` is not called when it used to (e.g. AMP document is swiped away while a component is done building but not finished layout). Essentially we should make sure there is nothing that needs to be paused happening inside `buildCallback()`.

(also let's consider renaming resume to unpause? to be consistent with layout and unlayout)

**Comment by dvoytenko** [comment]
It'd be more complicated. Basically, a `pause` should most likely:
 - Ignore if not built
 - Ignore if not laid out and no layout is currently in progress
 - Wait for layout to complete if in progress and then call pause. Alternatively, it could interrupt layout and just go straight to pause state. The interruptions, though, pretty hard to do generically to avoid broken/unexpected state.

**Comment by ericlindley-g** [comment]
@aghassemi   — Slotting in "pending triage" for now. please update the milestone when you have a sense of when work will start. Thanks!

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
