### ISSUE TITLE
Aspact ratios in amp-carousel are breaking on Safari 7.0

### ISSUE THREAD

**Issue by ymotongpoo** [ampproject/amphtml#4207]
## Short description of your issue:

On Safari 7.0 on iOS 7, amp-carousel doesn't respect the aspect ratios of images in it. Even if amp-img is specifying attributes for sizes, it is expanded to fit the size of the frame of amp-carousel. Though technically Safari 7.0 is not supported as of today, just raising this issue for information.
## How do we reproduce the issue?
1. Access [sample of amp-carousel slide show](https://ampbyexample.com/advanced/image_galleries_with_amp-carousel/) with Safari 7.0
2. You will see expanded images of dogs like attached below.
   ![abe-safari7](https://cloud.githubusercontent.com/assets/145104/17126108/0e38b200-5335-11e6-96c2-fa4d9186c0ec.jpg)
## What browsers are affected?

Safari 7.0 only
## Which AMP version is affected?

https://github.com/ampproject/amphtml/releases/tag/1469143772973

**Comment by jridgewell** [comment]
@dvoytenko: I remember you worked with aspect ratios in `<amp-carousel>` before, right?

**Comment by dvoytenko** [comment]
No, haven't seen this case. Generally we only support Safari 8 and 9 (and 10). Do we have Safari 7 handy somewhere to test?

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
