### ISSUE TITLE
add support for AMoAd NativeAd to amp-ad

### ISSUE THREAD

**Issue by amoad-amoe** [ampproject/amphtml#4208]
Our ad support has just been added to amp-ad. https://github.com/ampproject/amphtml/pull/4084

We have also "native ad" service, so we'd like to enable it. So update the document and implementation is needed.

**Comment by lannka** [comment]
@amoad-amoe feel free to open another PR for "native ad" support. Let me know if you see things missing in AMP to support that.

**Comment by hashikell** [comment]
Sure. Thanks!

**Comment by amoad-amoe** [comment]
Thanks, @hashikell!
