### ISSUE TITLE
Allow <button formtarget="_blank/_top"> 

### ISSUE THREAD

**Issue by Gregable** [ampproject/amphtml#4216]
We allow `target=_blank/_top` on the enclosing `<form>` tag, so we should allow `formtarget on enclosed buttons as well.

**Comment by ericlindley-g** [comment]
@Gregable   — Slotting in "pending triage" for now. please update the milestone when you have a sense of when work will start. Thanks!

**Comment by Gregable** [comment]
Work is already done and will be in the next validator roll-up.

**Comment by Gregable** [comment]
This will be live in an hour or so in amp validator.
