### ISSUE TITLE
YouTube messages sometimes sends parsed data 

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#4218]
`event.data.indexOf` is throwing error in canary because `event.data` seems to be already parsed into an object.

cc/ @sriramkrish85

**Comment by sriramkrish85** [comment]
CC @erwinmombay

**Comment by mkhatib** [comment]
This error was happening because YouTube sometimes seem to be sending objects and some other times sending strings. Possibly hitting a YT Player experiment. Updated the code and test case to handle both cases.
