### ISSUE TITLE
Publisher/ Advertiser feedback for AMP Landing Pages

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#4220]
This is a place holder issue to consolidate all feedback about AMP Landing Pages.

**Comment by ericlindley-g** [comment]
@jasti Putting this in the Backlog to indicate that it's been triaged, which I think makes sense, since this gathers future work that isn't yet scheduled for the near term. Let me know if there's a better place for it :)

**Comment by roablep** [comment]
Is there an issue for time-spent tracking on landing pages?

**Comment by jasti** [comment]
@roablep Could you be more specific with the question? Are you looking for average time spent on pages tracking? If so, don't have that metric handy.

**Comment by dvoytenko** [comment]
/cc @avimehta @rudygalfi 

Analytics package should allow you to measure time spent.

**Comment by rudygalfi** [comment]
@dvoytenko is right: the [`timer` trigger](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md#timer-trigger-on-timer) should enable measuring time spent.

**Comment by OferL** [comment]
Hi, 

I have a question about AMP for PPC purposes.
Here is an example for a URL of an AMP page:
https://cdn.ampproject.org/c/searchenginland.com/example/amp

When you run a PPC campign for mobile users - can you use AMP URL such as the example described? Can you run a PPC campaign for a URL outside of your domain?

If not, does it mean that you only use amp-html tags, but the page loads from your domain?

Thanks,
Ofer.

**Comment by jasti** [comment]
@OferL There is no formal support in Adwords for AMP yet. AMP pages are just like regular web pages and therefore you are free to use it as the mobile URL, in which case the page will serve from your own domain. 
Recommend that you reach out to Adwords to confirm support.

**Comment by jasti** [comment]
Feedback received.
