### ISSUE TITLE
move getModeObject to getMode

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#4225]
currently the AmpPass DCE for getMode explicitly check that it is `mode.getMode`, the qualified name when invoked inside the mode module itself is different so it does not get optimized

**Comment by ericlindley-g** [comment]
@erwinmombay   — Slotting in "pending triage" for now. please update the milestone when you have a sense of when work will start. Thanks!

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
