### ISSUE TITLE
Intent to implement: signin protocol for AMP Access

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#4227]
A sign-in protocol is the protocol that will allow a viewer to potentially participate in sign-in operations for AMP Access login endpoint. This is a strictly user opt-in feature where a user may elect to use their viewer login to access AMP content.

**Comment by adelinamart** [comment]
Is this still needed? Thanks.

**Comment by dvoytenko** [comment]
Done. But not yet launched. This can be closed now.
