### ISSUE TITLE
Validator: Support "skype:" and other custom protocols

### ISSUE THREAD

**Issue by pbakaus** [ampproject/amphtml#4242]
```
<a href="skype:username?call" target="_blank" title="Skype" class="social-icon social-icon-skype"></a>
```

Is a link appearing on many pages (including mine), and the validator doesn't like it.

**Comment by Gregable** [comment]
Dupe of https://github.com/ampproject/amphtml/issues/4094 . The fix is in but not yet made it to release.

**Comment by pbakaus** [comment]
Ah great thanks!
