### ISSUE TITLE
Test resize postMessage is sent to ad

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#4256]
We have a bug in our resize implementation for ads. When the ad requests a resize, it will attempt to resize but never send a `#postMessage` back to the ad telling it whether the resize succeeded or failed.

The bug will be fixed with #4236, but we need a test.

Re: https://github.com/ampproject/amphtml/pull/4236#discussion_r72488228
Re: https://github.com/ampproject/amphtml/commit/31ebe77de14f5019bb250457e8aeead21457ea39#commitcomment-18433581

**Comment by zhouyx** [comment]
I am trying to understand the message flow here. Please correct me. 

1.  AmpAd calls `attemptChangeSize`
2. Resources determines to resize or not
3. If resize, AmpAd size changes, AmpAd.iframe size also changes and it will send `embed-size' data to AmpAd
4. AmpAd listen to `embed-size` and call `updateSize_` to `postMessage` to AmpAd window.

**Comment by jridgewell** [comment]
Hm?

`<amp-ad>`'s `<iframe>` should send `embed-size`. The iframe will then resize, and wait for the amp-ad to resize. Once the amp-ad resizes (or refuses), it sends an `embed-size-changed` or `embed-size-denied` to the iframe.

**Comment by zhouyx** [comment]
Much clear now. The test we want to add is see if amp-ad really sends the `embed-size-changed` or `embed-size-denied` message back to iframe after `updateSize_` is called

**Comment by jridgewell** [comment]
Yup.

**Comment by zhouyx** [comment]
Will work on this after #4236 is in
