### ISSUE TITLE
amp-form: Submit Form on Input Change

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#4272]
Currently forms require a separate submit button, would be great if it'd be possible to omit the submit button if the form contains a single checkbox. Each click on the checkbox would then trigger an XHR request.

This would enable implementing favorite/bookmark actions directly in AMPs with amp-form. 

Example:
```
  <form method="post" action-xhr="https://example.com/bookmark/12345" action="https://example.com/bookmark/12345" target="_top">   
    <input type="checkbox" id="favorite" checked>
  </form>
```

//cc @mkhatib

**Comment by mkhatib** [comment]
Thanks for filing. I can see how this is useful. Will look more into this and see how we can introduce this. 

I can see this might be also done by having two submit buttons and toggling visibility of each to favorite or remove from favorite. Any idea if a `checkbox` is what publishers are already using to implement a similar functionality?

**Comment by sebastianbenz** [comment]
I don't know any examples (haven't searched though) - but checkbox seems semantically to be the best element.

How would you toggle the visibility of two submit buttons?

**Comment by dvoytenko** [comment]
What do we think about `on="change:form.submit"` action?

**Comment by sebastianbenz** [comment]
sgtm. Should this work for other input types as well?

**Comment by dvoytenko** [comment]
I believe, yes, we can make it work on all other inputs. I'm personally always very confused about events that inputs sent, but, I think, `onchange` has become the most predictable one.

@mkhatib, do you know?

**Comment by mkhatib** [comment]
I like this approach. Thanks for the suggestion 👍 

Agreed that `change` probably the most predictable (need to do some testing there and make sure it works well), we might want to expose other events or debounce `change` events for elements that would fire it consequently like text inputs (to avoid rapid unnecessary submissions to the form).

**Comment by dvoytenko** [comment]
This is another thing I always get confused with text inputs. But text inputs do provide their own "auto submit" approach. Right?

**Comment by fletc3her** [comment]
I have a navigation control which is implemented as a select within a form. When the select is changed the form submits. If I could add on="change:myform.submit" to the select then I could use this same navigation control on my AMP pages.

**Comment by dandv** [comment]
This feature would make it much easier to implement favoriting indeed. I've realized that after hacking together [the sample linked above](https://github.com/ampproject/amp-by-example/issues/427): 

* submitting the form on the first input change is easy enough
* displaying the Submit button with a style that reflects the item/page was favorited/bookmarked requires hiding the submit button and drawing the same submit button as an input in the `<div submit-success>`
* making that newly styled input element (not the original Submit) *toggle* the favorite status seems impossible.

**Comment by mkhatib** [comment]
Just merged! Should be out in couple of weeks!

**Comment by sebastianbenz** [comment]
Nice! Thanks!

**Comment by dandv** [comment]
@mkhatib, @dvoytenko: is the submit-on-change behavior documented anywhere?

**Comment by dvoytenko** [comment]
@mkhatib Looks like, no. Not documented. Can we send PR for docs?

**Comment by mkhatib** [comment]
Yeah looks like. I'll open a bug for @bpaduch to update the docs.

**Comment by bpaduch** [comment]
@mkhatib  - As you're familiar with what that behavior is, can you document it, and I'll review it?

**Comment by mkhatib** [comment]
Yes will do.

**Comment by dandv** [comment]
For the record, this is documented under [Input events](https://www.ampproject.org/docs/reference/components/amp-form#input-events).

**Comment by umairansari02** [comment]
Anyone send me the complete AMP contact form (all related files which include in form) I have allaow access origion error
