### ISSUE TITLE
Document that 'amp-social-share' may appear as a descendant of tag 'amp-sidebar'.

### ISSUE THREAD

**Issue by keepitsimple** [ampproject/amphtml#4273]
Subj

**Comment by dvoytenko** [comment]
/cc @sriramkrish85 @mkhatib @powdercloud @Gregable 

Indeed. This seems like a very clear case to include social-share in a sidebar. Is this just a a change that needs to be done to validator?

**Comment by sriramkrish85** [comment]
@Gregable @powdercloud This already existed. This was broken at some point due to a bad merge from validator. 

@mkhatib - can you followup on this.

**Comment by Gregable** [comment]
Sure, it's an easy validator change. The diffs are a little confusing when trying to sort through the archaeology as to why this happened. On the plus side, we've beefed up our tooling for validator merges and this should be less likely in the future. Will get it fixed and add an explicit test to avoid regressing again.

**Comment by keepitsimple** [comment]
@dvoytenko It also looks very good in narrow right sidebar :)

**Comment by Gregable** [comment]
@honeybadgerdontcare noticed that we'll need to update docs as well:

https://www.ampproject.org/docs/reference/extended/amp-sidebar.html
Specifically:
`The may not contain any AMP Elements except for amp-accordion, amp-img and amp-fit-text.`

**Comment by Gregable** [comment]
Merged a change that will fix this, but it will take a couple weeks to roll out. Changing the subject line to reference that we still need to update docs.
