### ISSUE TITLE
amp-analytics `click` not picking up amp-video player controls

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#4279]
## Short description of your issue:

We are using the “adobeanalytics” template and setup to track the clicking of <amp-video> id=testvideo.
But the click tracking is not working the way we want.  The view screen (green area) click is tracked with our setup, but the view screen click doesn’t start the video.  We want to track the video control bar (red area) click, but we could not find a way to capture the click.  So we were wondering if you know a way to track that.

![amp-video-controls](https://cloud.githubusercontent.com/assets/3888212/17261142/277a9e76-5589-11e6-8b7e-382de385f08e.png)
## How do we reproduce the issue?

See snippets of code at end
## What browsers are affected?

Android, iOS both seem affected
## Which AMP version is affected?

All
## Code sample

```
<amp-analytics type="adobeanalytics">
<script type="application/json">
{
"requests": {
"myClick": "${click}&v1=${eVar1}"
},
"vars": {
"host": "smetrics.cnn.com",
"reportSuites": "cnn-adbp-domestic-dev",
"pageName": "turner amp-analytics video test page"
},
"triggers": {
"click": {
"on": "click",
"selector": "#testvideo",
"request": "myClick",
"vars": {
"eVar1": "amp player"
}
}
}
}
</script>
</amp-analytics>
 <amp-video

src="https://s.cdn.turner.com/cnn/big/world/2016/06/16/euro-2016-england-hooligans-football-fans-black-pkg.cnn_596300_768x432_1300k.mp4"

height="432"

width="768"

layout="responsive"

poster="https://ssl.cdn.turner.com/cnnnext/dam/assets/160611173341-marseille-clashes-4-super-169.jpg"

alt="article video"

controls="controls"

id="testvideo">
                        </amp-video>
```

**Comment by rudygalfi** [comment]
/to @avimehta 

Is this caused by video controls being in shadow DOM? If so, can we get at click events in spite of that?

**Comment by rudygalfi** [comment]
Ping @avimehta. Have you had a chance to look at this?

cc @dvoytenko as he might have some ideas.

**Comment by avimehta** [comment]
It looks like the click events on the video controls do not get sent to `amp-analytics`. Click events on the video itself do surface. 

I think the best way to track video clicks would be to add support to amp-video element to send  appropriate events to amp-analytics. @rudygalfi we had a discussion some time back about video analytics support and this is exactly what I was talking about. This is on our roadmap for this quarter. Lets talk about this a bit more and figure out how we can do it for all the video players.

@dvoytenko I might have missed something. Any ideas on why the click event never reaches the listener?

**Comment by dvoytenko** [comment]
It's very possible that a play button in a video doesn't propagate click event in some platforms. That would need some research to see whether or not propagation happens and how to infer it. Another option, of course, is to support video's play/pause events directly in AMP Analytics.

**Comment by avimehta** [comment]
I would really like to support first class video events in amp-analytics. Then we can have events like "saw this video for 60 seconds" "saw the video to the end", "pressed play/pause", "saw the ad" (if supported) and so on. Then we can also have video related variables that are available for use. This is the kind of thing I wanted to do this quarter. Once I can put the visibility stuff behind me, I'll look into spec-ing this out.

**Comment by adelinamart** [comment]
@avimehta are you still considering working on this issue? Thanks

**Comment by rudygalfi** [comment]
cc @aghassemi

**Comment by rudygalfi** [comment]
I think the best way to proceed is not to capture the specific click event mentioned in the bug, but to use video analytics (#9902).
