### ISSUE TITLE
Common Base64 encode/decode

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#4281]
We need a single reusable set of a APIs for dealing with base64 in AMP. All uses of `btoa` and `atob` should migrate this API, as well as a bunch of other self-made base64 routines.

The API:
 1. Should contain two methods to encode and decode base64 content.
 2. Support two char modes: classic and url-safe.
 3. Support two padding modes: padding and no-padding. I believe any self-respecting base64 decoder would support it out-of-the-box, but for encoder we may need to provide this option.

The exact implementation is up to us. Internally we can use `btoa/atob` or something like closure lib, but few things to keep in mind:
 - `string.replace(/-_./)` is probably fine for smaller strings, but likely less efficient for bigger strings, especially if the base64 implementation already crawls the string character by character. That being said, url-safe encoding maybe used less frequently and we may have some freedom.
 - Closure's base64 routines are already used in crypto. So, this becomes a bit entangled with crypto migration to core and late-loading. Obviously, all possible to resolve, but something to keep in mind.
 - Needless to say, we need to be very careful with migration to ensure we don't confuse classic and url-safe encodings.

Another note, we could combine these utils with other frequently used utils, e.g. for ArrayBuffer conversions.

/cc @jridgewell @lannka

**Comment by tdrl** [comment]
Just a heads-up that we have some base64 code in A4A.  It needs to be URL-safe, but we only have to handle a couple hundred bytes at a go (for crypto signatures).

**Comment by bobcassels** [comment]
PR #4340 is a step in this direction. So far, we only need base64url (without padding). (We were using regular base64 for signatures, but this PR changes that.)
