### ISSUE TITLE
Structured Data test tool thows error if no dateModified is set

### ISSUE THREAD

**Issue by weeblr** [ampproject/amphtml#4290]
## Short description of your issue:

An otherwise valid AMP page with a missing or empty dateModified field is flagged as having an error by the Google Structured data validator. This may make many pages fails validation, while being valid.

## How do we reproduce the issue?

Generate an AMP page with the _datePublished_ json+ld field missing or empty. Pass it through data tester. Result is an error with the following message:

> The dateModified field is recommended. Please provide a value if available.

This sounds more like a warning at worse, but is classified as an Error, thus probably making the whole amp page not being indexed as AMP, while it's entirely valid. The error is displayed whether the field is present with an empty value, or if it's missing entirely.

Please note that due to this, the current AMP [sample document provided in the AMP HTML specification](https://www.ampproject.org/docs/reference/spec.html) actually fails validation.

## Which AMP version is affected?

No idea. this was just reported to me.

**Comment by dvoytenko** [comment]
Assigning to @Gregable . But from what I understand, AMP does not require or impose any rules on JSON+LD manifest. This part is independent of AMP, and, likely, required by some other system.

/cc @rudygalfi

**Comment by Gregable** [comment]
I'll flag this for the SDTT folks, but it's not something the AMP validator can address. 

Note that this does not prevent the page from being indexed as AMP or placed in the AMP cache. It may (unsure) prevent the page from appearing in Google's news carousel.

**Comment by weeblr** [comment]
Hi

Thanks for looking into this. 

> It may (unsure) prevent the page from appearing in Google's news carousel.

Well, if AMP pages are not indexed and displayed by Google in their (yours) search results, that's a major drawback for most users, or to put otherwise, there is no point in adding AMP to a site if AMP pages don't show in search results. As per [today's announcement](https://webmasters.googleblog.com/2016/08/amp-your-content-preview-of-amped.html), showing up in SERP is the major selling point of AMP.

I do agree it's probably not something the validator can handle, but surely the SDTT people can fix that pretty quick.

Rgds

**Comment by weeblr** [comment]
As a side note, maybe you want to fix the AMP sample document I linked to in my OP (add a dateModified field), so that at least the official documentation for AMP HTML offers a sample document that validates?

Rgds

**Comment by weeblr** [comment]
Hi again,

I just checked again, and this has been fixed. The message now shows as a warning, as it should. Case closed I think.

**Comment by Gregable** [comment]
> Well, if AMP pages are not indexed and displayed by Google in their (yours) search results, that's a major drawback for most users, or to put otherwise, there is no point in adding AMP to a site if AMP pages don't show in search results. As per today's announcement, showing up in SERP is the major selling point of AMP.

FYI: The [announcement](https://googleblog.blogspot.com/2015/10/introducing-accelerated-mobile-pages.html) today of AMP results showing up on regular search results does not require structured data on the page at all, only AMP validity. The SD data is only necessary to get the associated metadata needed to render a news carousel item.

Glad it's working as intended now though!

**Comment by weeblr** [comment]
Hi Greg,

Indeed and thanks for making this clearer. It makes sense if the AMP page is just an alternate version of the regular HTML one, it shouldn't require more metadata than the original. The AMP doc actually states the very same, that SD are not needed for AMP. 
But as the carrousel/top stories were up until now the only way to have your AMP pages viewed, it was sort of a requirement anyway.
Still think it would be a "soft" requirement though, who would want to not have a chance to picked up for top stories?

Rgds
