### ISSUE TITLE
amp-carousel: tracking events

### ISSUE THREAD

**Issue by eike-hass** [ampproject/amphtml#4292]
We would like to track interactions with an amp-carousel. Specifically we would like to track a user-triggered navigation with the amp-analytics component using the "IVW"-provider.

Currently it would probably be possible to achieve this using the json event-tracking notation to track clicks on the `amp-carousel-button-next`-element. This would ignore swipe gestures on mobile though.

Would it instead be possible to expose a `carouselNavigation`-event (maybe with the id of carousel instance attached, similar to the amp-lightbox component like `carouselNavigation:my-carousel`) to access in the amp-analytics configuration? Do you see other possibilities?

**Comment by ericlindley-g** [comment]
This is something we've been thinking about—cc'ing some folks working on the carousel and analytics to think through how this might be done (I'm not sure if the new approach using native scroll would change the approach)

CC @sriramkrish85 @rudygalfi @avimehta

**Comment by dvoytenko** [comment]
It's totally reasonable to add `forward/back` or `prev/next` events events to carousel for analytics, it's also very easy to do.

The event definition in analytics should be able to supply `selector` to match different carousels, which would allow customization of analytics events.

**Comment by avimehta** [comment]
@dvoytenko Yes, that should be possible. You can define the variables you want to add support for. (`carouselId` and `carouselAction` makes sense to me) and then pass those values back to the listener [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/instrumentation.js#L174). [Visibility listener](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/instrumentation.js#L223) and [scroll listener](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/instrumentation.js#L346) do this to provide a bunch of variables. The variables are documented [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/analytics-vars.md#visibility-variables) and [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/analytics-vars.md#interaction)

**Comment by dvoytenko** [comment]
@avimehta cool!

@ericlindley-g please prioritize accordingly.

**Comment by rudygalfi** [comment]
It's a bit of a different trigger definition that we've been discussing, but I wonder if you can use `visibilitySpec` to do this (https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md#page-visible-trigger-on-visible). For instance, if you have a carousel of `amp-img`s then you could configure amp-analytics to watch the IDs within the carousel and fire hits when they become >1%, >10%, >50% visible (your choice).

@avimehta Would something like this work?

**Comment by ericlindley-g** [comment]
Putting into "next", as this would be nice to make some progress on soon

**Comment by rudygalfi** [comment]
@sriramkrish85 Could you take a look at this?

**Comment by sriramkrish85** [comment]
@rudygalfi - should the events be triggered for touch only or for both touch and button navigation? do we need to distinguish between touch and button nav?

**Comment by dvoytenko** [comment]
Any forward/backward nav in carousel should trigger analytics events.

**Comment by rudygalfi** [comment]
Agree - either one. I don't think the how is important to call out. I'm thinking:

- new trigger type for a carousel advancement of any kind
- contextual substitution variable to tell you about which slide was swiped to

@eike-hass for further feedback on needs

**Comment by cramforce** [comment]
We'll need something like `data-slide-id` that is being made available on the trigger.

**Comment by avimehta** [comment]
@sriramkrish85 https://github.com/ampproject/amphtml/issues/4292#issuecomment-236714336 should give you an idea of how to integrate with amp-analytics. Also see amp-access on how to define custom triggers.

**Comment by sriramkrish85** [comment]
@cramforce `data-slide-id` => would this be the index of the slide?

**Comment by dvoytenko** [comment]
I'd assume it'd be a author-set ID. We don't need `data-` attributes to send indexes :)

**Comment by sriramkrish85** [comment]
i meant when the author does not set it :) what do we do with this

**Comment by cramforce** [comment]
index seems like a reasonable default

**Comment by eike-hass** [comment]
sounds great! can we have a rough ETA?

**Comment by rudygalfi** [comment]
FYI: Documentation PR is here: #5724.

Is there anything left on this?

**Comment by sebastianbenz** [comment]
Update the sample on ABE.

**Comment by camelburrito** [comment]
Nope. This is all done!
