### ISSUE TITLE
Fix remaining hardcoded ampproject.net URLs in build

### ISSUE THREAD

**Issue by dknecht** [ampproject/amphtml#4293]
There are two remaining files that have hardcoded ampproject.net added during the production build process.
- frame.html
- amp-login-done-0.1.html

Related to #3934

**Comment by dknecht** [comment]
FYI @jrf0110 @erwinmombay @cramforce

**Comment by jrf0110** [comment]
Ideally, we'd want the gulpfile to be able to read from `src/config.js`. That means making it a commonJS module. It would also be ideal if the `src/config.js` module were configurable via environment variables. Depending on the environment (node or the browser) we could read initial configuration values from `window.AMP_CONFIG` or `process.env.AMP_CONFIG`

**Comment by erwinmombay** [comment]
testing the switch to commonjs (https://github.com/ampproject/amphtml/pull/4327) .
The latter might be slightly harder since we can do the process.env replace using babel/browserify but might be harder with closure compiler (not impossible but not as straight forward). currently `process.env` in the closure compiler build is actually [hardcoded](https://github.com/ampproject/amphtml/blob/master/build-system/tasks/compile.js#L96)

**Comment by lannka** [comment]
Do we consider [move gulp to ES6](https://markgoodyear.com/2015/06/using-es6-with-gulp/)?

**Comment by erwinmombay** [comment]
@lannka yes,we'd need to either do the transpilation or move to a higher node engine. we currently support 4>=

**Comment by dknecht** [comment]
Can we just change how these files gets the URLs and use the parent window AMP_CONFIG?  As a follow on to https://github.com/ampproject/amphtml/pull/4376

**Comment by dknecht** [comment]
@erwinmombay any chance you will still get to this?

**Comment by erwinmombay** [comment]
@dknecht thanks for the ping, ill prioritize

**Comment by dknecht** [comment]
@erwinmombay   there was one missed.  https://github.com/ampproject/amphtml/blob/master/gulpfile.js#L569

**Comment by erwinmombay** [comment]
@dknecht i think i rolled back that line actually. i believe its the string that is embedded in remote.html. Should it be replaced?

**Comment by dknecht** [comment]
@erwinmombay remote.html is another issue that I don't know how to solve.  This one is for frame.html.  See my pull.  I think you just missed it.

**Comment by erwinmombay** [comment]
@dknecht thanks
