### ISSUE TITLE
Consider allowing extensions to provide their own Loader animation

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#4299]
Currently there doesn't seem to be a way for extensions to provide their own loader animation. So [extensions like Apster](https://github.com/ampproject/amphtml/pull/4291/files#diff-b8f9686fbe618a8a1767815ebf2ae443R120) are (mis)using `createPlaceholderCallback` to provide their own gif animated image as a branded loader.

Maybe we can consider making the `-amp-loader` related CSS classes not private and allow extensions to override the animation. Or create a `createLoaderElementCallback` to allow extensions to provide their own.

**Comment by dandv** [comment]
Any progress on this?

Alternatively, can we [document](https://github.com/ampproject/amphtml/issues/4299) the current node structure and classes for displaying the loader?

```html
<div class="i-amphtml-loading-container i-amphtml-fill-content">
  <div class="i-amphtml-loader amp-active">
    <div class="i-amphtml-loader-dot"></div>
    <div class="i-amphtml-loader-dot"></div>
    <div class="i-amphtml-loader-dot"></div>
  </div>
</div>
```

**Comment by dvoytenko** [comment]
Extensions can provide their loading indicators. E.g. Apester does.

**Comment by rudygalfi** [comment]
So we can close?
