### ISSUE TITLE
Brid Player defeaultSnapshot image doesn't exist

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#4303]
The image placehlolder `amp-brid-player` is [falling back to](https://github.com/ampproject/amphtml/blob/master/extensions/amp-brid-player/0.1/amp-brid-player.js#L136) `https://services.brid.tv/ugc/default/defaultSnapshot.png`  doesn't actually exist. 

@DarXector Any idea what is the correct URL for default snapshot?

**Comment by DarXector** [comment]
Hi, 

there were some changes to Brid servers. I will update the repo with the latest URL as soon as possible.

-----Original Message-----
