### ISSUE TITLE
Add a form-level blur and keyup handlers instead of input-level ones

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#4305]
In `amp-form`.`reportInputValidity(input)` drop the `add/removeEventListener` calls and just install a form-level handlers for keyup and blur events.

See [discussion on this PR](https://github.com/ampproject/amphtml/pull/3823#discussion_r70005303).

**Comment by jridgewell** [comment]
Re: https://github.com/ampproject/amphtml/pull/3823#discussion_r70011152, also.
