### ISSUE TITLE
Error loading Comscore pixel

### ISSUE THREAD

**Issue by pdufour** [ampproject/amphtml#4313]
## Short description of your issue:

When I turn on AMP validation I noticed an error with the Comscore tracker. I think it's because it's returning a 204 but I'm not sure.

## How do we reproduce the issue?

1. Visit https://rawgit.com/ampproject/amphtml/master/examples/analytics.amp.html#development=1 which is a demo of the examples page from the amp repo.
1. See  "[amp-analytics.Transport]" "Failed to send image request" "https://sb.scorecardresearch.com/b?..` in the console

## What browsers are affected?

All

## Which AMP version is affected?

All

**Comment by BenDavidow** [comment]
I'd be interested to see what you guys find. We're facing the same issue. It looks like the analytics image is failing to decode though not sure.

**Comment by avimehta** [comment]
@pdufour is correct about the 204 response. The data is being correctly sent but the response is empty. Since the data is getting correctly sent/collected, I think this is a low pri bug. I'll try and see if I can remove the console warning for known 204 cases. Note that this only shows up when you set #development=1

**Comment by dvoytenko** [comment]
@avimehta @pdufour Unfortunately, the error cannot be removed - it's printed deep somewhere in Chrome. We typically just advise to return a tiny gif. I think the minimal possible gif size is around 30 bytes or so.

**Comment by avimehta** [comment]
@dvoytenko I think @pdufour is talking about https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/transport.js#L65. I am not sure if exact error can be detected but if it can be detected, I was planning to suppress the warning. Do you think that will work?

**Comment by pdufour** [comment]
@avimehta that's the one.

**Comment by avimehta** [comment]
I don't think it is possible to detect what kind of error occurred. I did not want to remove the warning altogether because there might be legitimate reasons for image request to fail. Therefore, I changed the wording and made the warning show up only in dev builds.

**Comment by dvoytenko** [comment]
@avimehta Detecting error is possible. Suppressing it is not. That's just how browsers log image errors - we can catch it but no way to hide it. Definitely feel free to check around and see if you can come up with something to suppress it, though - that'd be nice.

**Comment by avimehta** [comment]
discussed this with @dvoytenko and he explained how using `dev().warn()` is not desirable. The gist of the discussion is that it is okay to have false positive if the alternative is that the errors never get surfaced. An easy way to solve this would be for the vendor to serve a small gif image or start using sendBeacon.

**Comment by avimehta** [comment]
Note that the warning in console is not going to go away. Just the text has been changed to indicate that the response was unparseable and wasn't an image.
