### ISSUE TITLE
add support for AMoAd responsive layout to amp-ad

### ISSUE THREAD

**Issue by amoad-amoe** [ampproject/amphtml#4314]
Our ad supports responsive layout. Setting your layout attribute to responsive like below, we can scale the ad.

``` html
<amp-ad width="300" height="250"
  type="amoad"
  layout="responsive"
  data-sid="62056d310111552c951d19c06bfa71e16e615e39493eceff667912488bc576a6">
</amp-ad>
```

Some additional code will be needed. I'd like to implement after https://github.com/ampproject/amphtml/issues/4208 is merged.

under the AMoAd CLA.

**Comment by dvoytenko** [comment]
SGTM

**Comment by jasti** [comment]
Been open for a while. Please reopen or directly submit PR for review. Thanks.
