### ISSUE TITLE
AMP invalidation minified css boilerplate

### ISSUE THREAD

**Issue by gustavopaes** [ampproject/amphtml#4319]
AMP validation is invalidating our CSS Boilerplate because my server minify the css, transforming "0s" in just "0".

So, this [CSS Boilerplate](https://github.com/ampproject/amphtml/blob/master/spec/amp-boilerplate.md):

    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>

Transforms into:

    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0 1 normal both;animation:-amp-start 8s steps(1,end) 0 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>

I think both can be validate, because "0" and "0s" and "0ms" are same.

## How do we reproduce the issue?

Public example url: http://olimpiadas.uol.com.br/noticias/redacao/2016/07/18/hipismo-define-equipe-olimpica-com-rodrigo-pessoa-na-reserva.htm?app=amp#development=1

**Comment by powdercloud** [comment]
So I wondered why it wasn't dropping the 's' from '8s'. Then I realized that it's optimizing the special case, the '0something'. Cute. But then I tried to figure out whether that's allowed or not. Could this be relevant?

https://developer.mozilla.org/en-US/docs/Web/CSS/time

Even if all units represent the same time for the value 0, the unit may not be omitted in that case as it isn't a <length>: 0 is invalid and does not represent 0s, 0ms.

**Comment by gustavopaes** [comment]
Ok, can be wrong remove "0something" in this case, but the default "sass" output is:

```
body {
  -webkit-animation: -amp-start 8s steps(1, end) 0 1 normal both;
  -moz-animation: -amp-start 8s steps(1, end) 0 1 normal both;
  -ms-animation: -amp-start 8s steps(1, end) 0 1 normal both;
  animation: -amp-start 8s steps(1, end) 0 1 normal both; }
```

Maybe I can figure out here, but can be normal this question here again. Maybe some new message on AMP validator or just one NOTICE instead of WARN that invalidate all AMP page.

**Comment by ericlindley-g** [comment]
@gustavopaes  Looks like this can be closed — feel free to re-open if there are any unresolved questions/needs
