### ISSUE TITLE
Request to add page_URL as one of the supported parameter for DFP

### ISSUE THREAD

**Issue by kbnaik** [ampproject/amphtml#4326]
The request is precisely for AMP to be able to pass pageURL parameter in the query going to DFP for Doubleclick ad. 
(https://developers.google.com/doubleclick-gpt/adsense_attributes)

**Comment by rudygalfi** [comment]
Actually, this is for @jasti.

**Comment by jasti** [comment]
@michaelkleber, it looks like we don't support https://developers.google.com/doubleclick-gpt/reference#googletag.PubAdsService_set and instead just infer the canonical URL (https://github.com/ampproject/amphtml/blob/master/ads/google/doubleclick.js#L93). Is it worth updating dclk implementation to broadly allow any of these https://developers.google.com/doubleclick-gpt/adsense_attributes to be optionally set?

**Comment by michaelkleber** [comment]
The URL used for doubleclick ad targeting is the one provided in the document's `<link rel="canonical">`.  @kbnaik Do you have a use case where you want the ad targeting URL and the AMP canonical URL to be different?

**Comment by kbnaik** [comment]
I will update the same. This is a request from one of our publishers.

**Comment by jasti** [comment]
Sounds like canonical URL is what you wanted. Feel free to reopen if not.
