### ISSUE TITLE
Code/logic sharing between 3p-ad and a4a

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#4328]
"Don't forget a4a." We start to see this more and more often when we're making new features on 3p-ad, such as #4283 #3815. I'm wondering if "a common base class" would mitigate this problem and make code/logic sharing easier.

Right now, a4a imports some functions from 3p-ad as utils. This is not enough when we want to, for example, share some logic that involves internal states.

@bobcassels @tdrl 
/cc @michaelkleber @zhouyx @jridgewell

**Comment by tdrl** [comment]
Agreed -- we need a better plan for code sharing.

Adding @a4a-cam (new team name -- we'll see if it actually notifies all of us).

**Comment by tdrl** [comment]
The challenge, as I see it, is that we want UI-level behaviors to be the same (delay times, fallback and collapsing behaviors, etc.) but there are some significant differences in A4A vs 3p architectures (URL building w/in A4A network impl vs via delegated JS code; early fetch vs delayed fetch; etc.)  There are a lot of thorny interactions.  Conceptually, a "base class" makes sense, but I'm not sure that's literally the best way to implement this.  Encapsulation of shared helper classes (a la amp-ad-api-handler.js) feels better to me.

**Comment by zhouyx** [comment]
As discussed offline. We will keep the `apiHandler` class for cross domain iframe logic sharing. In the meanwhile, we will move UI related functionalities outside this `apiHandler` class and will import them as utility functions.

**Comment by zhouyx** [comment]
closed by #5356
