### ISSUE TITLE
AMP uses native app-like scroll inertia instead of UIWebView's default scroll inertia

### ISSUE THREAD

**Issue by booc0mtaco** [ampproject/amphtml#4330]
When viewing an AMP document on iOS/MobileSafari, the scroll inertia matches the native scroll inertia, and not the scroll inertia of normal web pages. For native apps, there's a lot less "friction" so the scroll proceeds at a faster pace, and for longer, while MobileSafari pages are 1/3 the speed, roughly.

## How do we reproduce the issue?

Please post a public URL and ideally post a reduced test case. E.g. on jsbin.com that exhibits only your issue and nothing else.

1. load <http://g.co/ampdemo>
2. type a simple search, such as `dog`
3. load the result page, and scroll. Take note of the inertia provided by MobileSafari (deep and shallow swipes to see speed falloff) on the google result page
4. in the "Top stories" section, click one of AMP-lified results (or any AMP result)
5. perform similar swipes to nr. 3, and take note of the intertia provided by the AMP page

The expectation is that the scroll inertia wouldn't change after clicking an AMP result, but it does. For many users, this would be unexpected behavior, as it doesn't match the behavior on the google result page they just navigated from. 

## What browsers are affected?

This would likely affect MobileSafari across all devices. Possibly Android browsers (if the same algorithm for scroll inertia is applied to the browser, and doesn't match native scroll inertia)

## Which AMP version is affected?

This affects the version being served currently at <http://g.co/ampdemo>. I couldn't find the version number, unfortunately.

**Comment by rudygalfi** [comment]
Thanks -- Closing this out here since I suspect this isn't related to the AMP JS library (which is what issues in this repo track), but I have passed along to some folks who may be able to look at this. We'll reopen if it does turn out there's an AMP library fix to make.

**Comment by booc0mtaco** [comment]
@rudygalfi thanks! I didn't see any special handlers for inertial scroll after perusing the code here, so it's probably within the AMP "engine" itself (whatever loads the AMP content after clicking the lightning bolt). Thanks for following up.

**Comment by jridgewell** [comment]
This is done only on iOS to enable scrolling.
