### ISSUE TITLE
Fix <amp-live-list> update/scrolling bug

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#4332]
Currently there is a bug where:
1. User is looking at a post that will exceed max-items-per-page with the next update
2. User taps notification that triggers updating the page
3. Scroll automatically begins to take user to the top of <amp-live-list>
4. Calculation is made to determine which <amp-live-list> items exceeding max-items-per-page based are below current viewport position
5. Items identified in (4) are hidden (but not removed entirely from DOM)

Because 4 is done after scrolling begins, sometimes the items that the user was looking at are hidden by the update

One fix is that step (4) is moved to before (3), so the calculation is made before scrolling begins

Passing to @erwinmombay to fix when possible (please update the milestone when you have a good sense of when you can make the fix). Thanks!

**Comment by adelinamart** [comment]
@erwinmombay @ericlindley-g is this still a P2 bug? Thanks

**Comment by ericlindley-g** [comment]
Good question—bumping to P3

**Comment by aghassemi** [comment]
closing as stale
