### ISSUE TITLE
Intent to implement: custom access authorization endpoint timeout

### ISSUE THREAD

**Issue by kozlice** [ampproject/amphtml#4344]
There was [a discussion](https://github.com/ampproject/amphtml/issues/4013) about possibility to extend access authorization endpoint timeout. Since it's hardcoded to 3s, I'm not able to use this feature in my dev environment. Due to networking problems the best I can get is 5s, so basically auth **never works**.

Configuring timeout could be useful not only in dev/test environments, but for production as well: some people might want to reduce this timeout.

**Comment by dvoytenko** [comment]
@kozlice One option we can do: we can double the timeout time for development mode, `#development=1`. This way you can debug with a bigger timeout. But we can't reduce it for PROD cases or customize, since we give a promise to applications that embed AMP that the authorization decisions will be made quickly.

**Comment by kozlice** [comment]
I got your point. As of production, I meant that somebody might want to make limit _even lower_, e.g. 1s. Anyway, here's how I've patched & built it on my machine just to have an ability to do something in dev mode:

https://github.com/ampproject/amphtml/compare/master...kozlice:access-authorization-timeout

Default is still 3s, might be worth to give people capability to configure it with a disclaimer.

**Comment by dvoytenko** [comment]
@kozlice Thanks. You can use this diff as a base for a PR and send it to me, but I will ask a number of changes. Such as:

1. The configured timeout can only be higher than the default one in development mode (`getMode().development`). E.g. in prod mode it'd be the `min(default, specified)`.
2. Update the amp-access.md

**Comment by kozlice** [comment]
Thanks, @dvoytenko. I've created a PR, but there is a small problem with test coverage for production mode behavior.
