### ISSUE TITLE
Support Dynamic CSS Classes for live-updating content

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#4346]
Currently, dynamic css classes are set on load, and not revisited for live-updating content like amp-live-list (or amp-fresh) when it is received on the client

This is a bug to update Dynamic CSS Classes so it works well with amp-live-list (and when available, amp-fresh), applying the right classes to content as it comes in

Passing to @jridgewell , as I believe you first implemented Dynamic CSS Classes — not sure if you would make this update or not

cc'ing @erwinmombay , for amp-live-list and amp-fresh

**Comment by jridgewell** [comment]
I'm confused, Dynamic CSS classes just set a class name on the body. Why wouldn't that apply to the live list?

**Comment by ericlindley-g** [comment]
Gotcha—in that case, I'm closing this for now. Thanks!
