### ISSUE TITLE
amp-experiment md file doesn't convert into docs format well

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#4350]
Take a look at https://www.ampproject.org/docs/reference/extended/amp-experiment.html.

There's a couple of issues I spotted:
- The table describing configuration squeezes the initial two columns. (photo below)
- There are validation issues, but the underlying problem is that it seems like the [sourcecode] block being used isn't properly getting escaped, which would cause a real amp-experiment to get run on the page.
- Also, the extended component listing page doesn't have amp-experiment: https://www.ampproject.org/docs/reference/extended.html. I think an entry should live under Analytics.

cc @pbakaus 

<img width="732" alt="screen shot 2016-08-03 at 12 41 25 pm" src="https://cloud.githubusercontent.com/assets/3888212/17379615/17235a98-5978-11e6-9033-656f994711e4.png">

**Comment by lannka** [comment]
hmmm.. Is there a tool I can test it locally?

**Comment by pbakaus** [comment]
Sure! Just follow the README here: https://github.com/ampproject/docs

**Comment by lannka** [comment]
Still some issues left.

**Comment by lannka** [comment]
@pbakaus I still see one little thing with the HTML block here:

![screenshot from 2016-08-15 15 39 05](https://cloud.githubusercontent.com/assets/8496897/17682125/79322342-62fe-11e6-855a-ffcf5c0c538e.png)

This is my markdown code:
![screenshot from 2016-08-15 15 51 13](https://cloud.githubusercontent.com/assets/8496897/17682398/20d88bee-6300-11e6-80c8-e222cc16fe14.png)

Can you suggest how to fix it?

**Comment by pbakaus** [comment]
There was a space or some other hidden character at the end of "```", I've removed it here, after which it should be all good: https://github.com/ampproject/amphtml/pull/4533

Will try to make the conversion more robust in the future!
