### ISSUE TITLE
Extension loading behavior differs for `.min` and `.max` versions of files.

### ISSUE THREAD

**Issue by tdrl** [ampproject/amphtml#4352]
When running in localhost dev mode, accessing `.max` examples causes extensions to be loaded from localhost, but `.min` examples still load extensions from `cdn.ampproject.org`.

## How do we reproduce the issue?

- Check out master
- `gulp clean`, `gulp build`, `gulp dist`, and `gulp`.
- Load http://localhost:8000/examples/a4a.amp.max.html?a4a=2
  - Note that `amp-ad-0.1.js` is loaded from `localhost` and that the code successfully branches to and loads `amp-ad-network-adsense-impl-0.1.js`, also from localhost.
- Load http://localhost:8000/examples/a4a.amp.min.html?a4a=2
  - Note that `amp-ad-0.1.js` is loaded from `cdn.ampproject.org` instead of localhost
  - The a4a branch is never taken and `amp-ad-network-adsense-impl` is never loaded

## What browsers are affected?

Noted in Chrome 50, but I suspect that it's browser-independent.

## Which AMP version is affected?

1470254621580 (compiled in local dev mode from e9b36699db52b58fe5ee55f78fc6b8f9b3c8e9d8 )

**Comment by zhouyx** [comment]
I tested. it seems for .min example, `getMode().localDev` is false. while this value is true for .max example

**Comment by jridgewell** [comment]
This is an issue with https://github.com/ampproject/amphtml/pull/4252/files#diff-dfb00ab52d06ff7a2c0193dc57ca92c5R321 replacing `.max` with `''`, making our detection think we're using production JS files.

**Comment by lannka** [comment]
@tdrl It does sound like my PR is suspicious. But I couldn't really reproduce the issue.
See what I got:

![screenshot from 2016-08-04 11 21 25](https://cloud.githubusercontent.com/assets/8496897/17413333/a307cfcc-5a35-11e6-8dab-ffa4a5181db6.png)

**Comment by tdrl** [comment]
Wait, @jridgewell  -- the issue is with `.min`, not `.max`.  Would the change you're talking about affect `.min` stuff as well?

**Comment by tdrl** [comment]
@lannka Ugh.  I hate non-reproducible errors.  :-P

I'll try again.  What branch are you sync'd to?

**Comment by lannka** [comment]
> I'll try again. What branch are you sync'd to?

I'm at `master`.

> Wait, @jridgewell -- the issue is with .min, not .max. Would the change you're talking about affect .min stuff as well?

That logic was copied over from `gulpfile.js` in that PR. I agree it's a bit hard to read, but I'm sure it's doing the right thing. I wanted to refactor a little bit, but gave up.

**Comment by jridgewell** [comment]
> But I couldn't really reproduce the issue. See what I got:

Should that say `amp-ad-01.min.js`?

**Comment by lannka** [comment]
No really.

```
12:07:20$ ls dist/v0/amp-ad-0.1*.js
dist/v0/amp-ad-0.1.js  dist/v0/amp-ad-0.1.max.js
```

**Comment by tdrl** [comment]
Yes, this reproduces for me, following precisely the steps in the original report.  Here's a screenshot.  Note that the page is served from `localhost:8000` and includes at `.min`, but the request URL for `amp-ad-0.1.js` is to `cdn.ampproject.org`.  (Not shown in this screenshot: request URL for `v0.js` is to localhost:8000.)

![screenshot from 2016-08-05 13 22 58](https://cloud.githubusercontent.com/assets/17705064/17444802/f9fd68ac-5b0f-11e6-95d5-a7f21e5115b4.png)

**Comment by lannka** [comment]
@tdrl could you help check if it also happened to `v0.js`?

**Comment by tdrl** [comment]
`v0.js` was loaded from `localhost:8000`, if that's what you're asking?

**Comment by lannka** [comment]
I reproduced the issue after running `gulp dist` (my mistake).

As @zhouyx has pointed out, the issue should be in [calculateExtensionScriptUrl](https://github.com/ampproject/amphtml/blob/master/src/service/extensions-impl.js#L464). `getMode().localDev` is false.

The minified JS somehow is different from the original one.

**Comment by erwinmombay** [comment]
@lannka did you run `gulp dist --fortesting`

**Comment by tldr** [comment]
Too late @erwinmombay, you already summoned me. How may I be of service?;)
By the way: interesting project. Thanks for mentioning me unintentionally.

**Comment by erwinmombay** [comment]
@tldr my apologies! 😅

**Comment by lannka** [comment]
@erwinmombay yep, `gulp dist --fortesting` was the trick. And I think I also found the reason why getMode() is different in the two cases: https://github.com/ampproject/amphtml/pull/3772/files#diff-f18967811153a13559c8de21a977db03R69 

@tdrl please give it a try and see if it works for you. meanwhile, I think you should in anyway explicitly add the amp-ad extension script in the header.

**Comment by erwinmombay** [comment]
correct we turn some of the getMode().property calls into booleans so that they can be DCE'd for the production build.

**Comment by erwinmombay** [comment]
apologies for not seeing this issue earlier, could have saved some peoples time. if we can improve on the docs on this (and where), let me know.

**Comment by lannka** [comment]
@erwinmombay it will be good to add some description to the `getMode()` function, to indicate the items that eventually got overridden and build time.

**Comment by tdrl** [comment]
Thanks for the diagnosis, everybody!  I think a note about requiring `gulp dist --fortesting` in the `DEVELOPING.md` file, where it talks about the document proxy, would be a big help.

**Comment by erwinmombay** [comment]
@lannka will keep open till i fix docs

**Comment by lannka** [comment]
Oh, that will be great. Thanks!
