### ISSUE TITLE
amp-ad not showing fallback for doubleclick 

### ISSUE THREAD

**Issue by daniel-obadia** [ampproject/amphtml#4353]
I'm including an amp-ad element to my page and would like the height of the ad to collapse to 0 in order to remove the whitespace where the ad would normally be loaded.

From the documentation, I see a fallback element exists. However, when trying this out and when an ad is not available, the fallback HTML element is not rendered and the original ad height is kept. 

Here's the code example I'm using : 
```
<amp-ad width="300"
      height="200"
      type="doubleclick"
      data-slot="/4119129/doesnt-exist">
    <div fallback>
      <p>Thank you for trying AMP!</p>
      <p>You got lucky! We have no ad to show to you!</p>
    </div>
  </amp-ad>
```

The fallback DIV seems to have the following CSS assigned to it : 
```
.-amp-element:not(.amp-notsupported)>[fallback] with display:none;
```

Does this mean that doubleclick doesn't support the fallback? Sorry but I couldn't find anything that confirmed this online. 

Thanks!

**Comment by lannka** [comment]
It works for me. Did you try the example at:
```
http://localhost:8000/examples/ads.amp.html#doubleclick
```

![screenshot from 2016-08-03 15 46 31](https://cloud.githubusercontent.com/assets/8496897/17384494/81be60fa-5991-11e6-85b8-e30ed869f06f.png)

**Comment by daniel-obadia** [comment]
Thanks @lannka in your screenshot, there still seems to be the space being taken up but the styles in the amp-ad. While using the exact example, I can in fact reproduce your screenshot where the fallback is shown. I see a class added "amp-notsupported" would this be the proper class to target a CSS 0px height? 

Also, could the fact that my data-slot is for ex : "/1234/12test/AMP" (as an example) be the cause of the fallback not working? 

Thanks

**Comment by daniel-obadia** [comment]
This works, no need to set the amp-notsupported CSS class to height 0px. The issue seems to be related to the data-slot that I was using (not a real one). With the real value, it seems to return that the ad is not available, thus hiding the entire component. 

Thanks for your help!
