### ISSUE TITLE
Crypto: Subtle Digest Alg not an Object

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#4354]
```
TypeError: Failed to execute 'digest' on 'SubtleCrypto': parameter 1 ('algorithm') is not an object.
at TypeError (native)
at Xb.push.f.Xb.sha384 (amp-analytics-0.1.js:95)
at Xb.push.f.Xb.sha384Base64 (amp-analytics-0.1.js:96)
at (https://cdn.ampproject.org/rtv/001469825155149/v0/amp-analytics-0.1.js:70)
```

The [WebCrypto API](https://www.w3.org/TR/WebCryptoAPI/#dfn-AlgorithmIdentifier) says the argument can be either a `DOMString` or an object `{ name: DOMString }`. Let's try using the object format, and see if anything doesn't support it.

**Comment by lannka** [comment]
> Mozilla/5.0 (Linux; Android 5.0.2; it-it; 6039K Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/38.0.2125.102 Mobile Safari/537.36 
> 
> Mozilla/5.0 (Linux; Android 5.1.1; Galaxy Nexus Build/LMY49J) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36 
> 

For a record, most errors are from those 2 user agents.
