### ISSUE TITLE
Intent-to-implement: Gfycat embed

### ISSUE THREAD

**Issue by koshka** [ampproject/amphtml#4355]
A Gfycat embed is a silent looping video with specified width and height, through a fixed size or responsive iframe.
A Gfycat URL consists of a base url and a GfyID: 
https://gfycat.com/UncommonUncommonHapuku

In the example above, the Gfycat identifier is UncommonUncommonHapuku. A Gfycat identifier is required to display the content.

Width/height ratio is expected to be arbitrary.

![screen shot 2016-08-03 at 1 59 23 pm](https://cloud.githubusercontent.com/assets/1185852/17381812/bca7be6e-5982-11e6-99e8-a3d38ab6ad17.png)
![screen shot 2016-08-03 at 2 00 10 pm](https://cloud.githubusercontent.com/assets/1185852/17381813/bca8833a-5982-11e6-9505-5497c22801f0.png)

**Comment by jridgewell** [comment]
LGTM. @rudygalfi, what is our image naming pattern?

**Comment by rudygalfi** [comment]
`gfycat-anim`?

**Comment by koshka** [comment]
Hi @rudygalfi, we'd like no name this component 'amp-gfycat' following the pattern 'amp-vine', 'amp-vimeo' and others.
Is it possible?

**Comment by koshka** [comment]
Initial implementation is done, please send me feedback

**Comment by rudygalfi** [comment]
This seems like it was closed by #4420.
