### ISSUE TITLE
Amp Sidebar: Skipped Platform tests

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#4358]
Part of #4261 [disabled](https://github.com/ampproject/amphtml/pull/4261/files#diff-31629dcb2c6aaf33f0f7f52a128e13d9R17) the platform (specifically, iOS) tests for `<amp-sidebar>`. This is because you can't mock platform code anymore, since they do not share the same reference. Platform will instead come from the iframe's context, not the test runner's context.

**Comment by ericlindley-g** [comment]
@sriramkrish85, can you set a more firm milestone when you have a sense of when you'll work on this? Thanks

**Comment by adelinamart** [comment]
@camelburrito @ericlindley-g is this still needed?

**Comment by aghassemi** [comment]
closing old unskip issues, we can find them in code and reports anyway.
