### ISSUE TITLE
History: Skipped tests

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#4359]
Part of #4261 [disabled](https://github.com/ampproject/amphtml/pull/4261/files#diff-3c019753bd44f1b04bf59505f15de227R45) the tests for `History`. I don't really understand what the tests are doing, let alone why they're failing.

**Comment by ericlindley-g** [comment]
@jridgewell Do you have a good sense of who should own this? I see that @sriramkrish85 unassigned

**Comment by jridgewell** [comment]
Oh, I thought @sriramkrish85 did the coding for History. @dvoytenko would be next in line, since @cramforce is out.

**Comment by dvoytenko** [comment]
Hmm. Would seem very odd that history test would have to be skipped b/c of this. Any indication at all what was an issue?

**Comment by choumx** [comment]
Hmm, the History tests are not failing for me.
