### ISSUE TITLE
Double Click Ad Integration Test

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#4360]
Part of #4261 [disabled](https://github.com/ampproject/amphtml/pull/4261/files#diff-c06f1811f3a8d8a540fda229bbf8b73eR52) our crazy Double Click Ad integration test. It works when testing locally, but fails Travis. Ugh.

**Comment by adelinamart** [comment]
Do we still need to fix this?

**Comment by jridgewell** [comment]
Yes.

**Comment by keithwrightbos** [comment]
@lannka I propose moving this to @taymonbeal 

cc/ @tdrl
