### ISSUE TITLE
Analytics Visibility: Skipped Test

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#4361]
Part of #4261 [disabled](https://github.com/ampproject/amphtml/pull/4261/files#diff-0136206f8c4de64d6fec0d8e6a2f8bcaR262) the `backgrounded_` tests.

**Comment by ericlindley-g** [comment]
@avimehta  Is this fixed?

**Comment by rudygalfi** [comment]
Fixed with #4265? @avimehta or @jridgewell Can you confirm?
