### ISSUE TITLE
amp-video in carousel slides shows blurred circle even though the video is not shown

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#4364]
## How do we reproduce the issue?

1. Open a page with `<amp-carousel type=slides>` that has `<amp-img>` and `<amp-video controls>` inside.
2. When staying at the image slide, we see a blurred circle in the center of the carousel slide which is caused by the amp-video

## What browsers are affected?

safari, chrome

## Solution
We might need to set `opacity: 0` on `amp-video` if it's not visible in carousel slide.

**Comment by dvoytenko** [comment]
/fyi @sriramkrish85 

This should be fixed with the new scrollable slides

**Comment by sriramkrish85** [comment]
Lets get slidescroll up and running soon and this is a non issue in slidescroll since we no longer use opacity there.

**Comment by sriramkrish85** [comment]
Scrollable slides is 100% now  and hence you should not see this issue any longer
