### ISSUE TITLE
this.baseElement_.getViewport is not a function 

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#4370]
<img width="945" alt="screen shot 2016-08-04 at 7 54 26 am" src="https://cloud.githubusercontent.com/assets/354746/17406547/b60220f4-5a18-11e6-8642-bba67f405b41.png">

**Comment by jridgewell** [comment]
Likely my changes. [1](https://github.com/ampproject/amphtml/pull/4261/files#diff-a6732048fba913700105cee586022c71L264), [2](https://github.com/ampproject/amphtml/pull/4261/files#diff-3c4bf787a28d6df5598c0b9db2a35a48L80).
