### ISSUE TITLE
buildCallback invoked when hasNextNodeInDocumentOrder is false

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#4397]
![screenshot from 2016-08-05 15 23 27](https://cloud.githubusercontent.com/assets/8496897/17452068/bc137426-5b20-11e6-827f-72ea7547b0b1.png)

It's a bit hard to reproduce but as you can see in the screenshot, the `buildCallback` of `<amp-experiment>` is invoked when the `children=[]`. `hasNextNodeInDocumentOrder` also returns `false`. A snapshot of the DOM is printed in the console. We can see at that point, `<amp-experiment>` is not fully ready yet.

To reproduce this locally, please patch the diff: #4399
You can set the same break point as me, and refresh the page a couple times. Normally you see it less than 10 refreshes.

The call stack (on the top right corner of the screenshot) shows the `build` was triggered via 

```
    this.visibilityStateMachine_.setState(
      this.viewer_.getVisibilityState()   // = visible
    );
```

@dvoytenko @mkhatib do you have any idea?

+@rudygalfi  this is what we met in the ABE amp-experiment article.

**Comment by rudygalfi** [comment]
@lannka thanks for the update!

**Comment by lannka** [comment]
The call stack (on the top right corner of the screenshot) shows the `build` was triggered via 

```
    this.visibilityStateMachine_.setState(
      this.viewer_.getVisibilityState()   // = true
    );
```

**Comment by lannka** [comment]
To reproduce this locally, please patch the diff: #4399

You can set the same break point as me, and refresh the page a couple times. Normally you see it less than 10 refreshes.

**Comment by dvoytenko** [comment]
@lannka No idea yet. But could you please replace `<script>` with a `div` and see if this still happens?

**Comment by lannka** [comment]
@dvoytenko I don't think it's because the DOM parsing has skipped the children. Rather, the `build()` was invoked in another code path, which bypassed the `hasNextNode()` check (as you can see, the function call to `hasNextNode()` does return `false` as we expected).

Do you think we should also check `hasNextNode()` here:
https://github.com/ampproject/amphtml/blob/master/src/service/resources-impl.js#L935

Or, is `discoverWork_()` supposed to be invoked before the whole document is ready?

**Comment by dvoytenko** [comment]
/to @mkhatib 

Nope. `discoverWork_` should not blankly call `build`. This is just a codepath that didn't get cleaned up the last time around. Needs to be fixed asap. I think just removing it there will be fine. We need to make sure, of course, the rest of the code doesn't get broken in that method.

**Comment by mkhatib** [comment]
I'll look at other places where `build` is invoked and see if that can be removed or need to do a `ready` check before building. Looking quickly in `resoruces` another place that we call `resource.build()` is in `upgraded` which might cause similar problems. 

@dvoytenko as you mentioned this can probably be removed. I just wanna understand the order of events that lead to the bug and why we didn't catch it earlier.

**Comment by mkhatib** [comment]
Thanks for the descriptive issue, patch and initial debugging. Sent out a fix, please take a look.

**Comment by rudygalfi** [comment]
@lannka Does this need to roll out before we should release amp-experiment?

**Comment by lannka** [comment]
@rudygalfi, yes let's wait. Otherwise page will break.

**Comment by mkhatib** [comment]
Unfortunately that fix broke a test, I reverted so now investigating and trying to fix it asap.
