### ISSUE TITLE
Page-level ads

### ISSUE THREAD

**Issue by gkteck** [ampproject/amphtml#4408]
How to add a Page-level ads using the amp-ad tag ?

<amp-ad width=300 height=250
 type="adsense"
data-ad-client="ca-pub-xxx"
data-ad-slot="???">

</amp-ad>

**Comment by lannka** [comment]
@gkteck have you tried [this](https://github.com/ampproject/amphtml/blob/master/ads/google/adsense.md)?

**Comment by jasti** [comment]
@gkteck Page Level tags are not supported in AMP at the moment. Can you show an example of a page where you have configured page-level adsense ads?

**Comment by jasti** [comment]
@gkteck Recommend reaching out to Adsense directly to add page level ad support to AMP. 
@konakk FYI.

**Comment by dine1504** [comment]
i have found something from the internet. im not yet checked. i hope it may works..

 `<amp-ad type="adsense" data-ad-client="ca-pub-XXXXXXX" enable_page_level_ads: true </amp-ad>`

**Comment by konakk** [comment]
Page level ad support like anchor ads using <amp-ad type="adsense"
data-ad-client="ca-pub-XXXXXXX" enable_page_level_ads: true </amp-ad> is
not enabled yet but coming soon.
This tag adds inline ads (Banner ads)  to a page which has possibility to
add more ads inline with ad density policies. I would suggest not adding
this tag yet as there are some known issues with this tag which are being
actively worked on.

**Comment by Sejiro-Hiko** [comment]
Hi @konakk , @jasti 
 
Is there any update on this?
