### ISSUE TITLE
amp-analytics does not send data if there is a space in UA ID

### ISSUE THREAD

**Issue by emirhan87** [ampproject/amphtml#4410]
amp-analytics does not send data when there is a space before/after UA ID. 

This works fine: 
"account": "UA-9876543-21"

These do not work:
"account": "UA-9876543-21 "
"account": " UA-9876543-21"
"account": " UA-9876543-21 "
1. Add a space before or after your UA ID in amp-analytics code.

Tried on amp-analytics ver 0.1

**Comment by rudygalfi** [comment]
Thanks for the report! cc @avimehta 

I'm wondering if there are any opportunities to validate the ID and/or make the GA ingestion more forgiving. This is GA-specific and in the non-validated JSON blob, so it makes it a bit hard to figure out where to catch this error.

**Comment by avimehta** [comment]
Trimming all variable substitution is an option but not sure if all the vendors would like that. We can have a config level trimming setting or a variable level trimming setting. variable level trimming is discussed in #2476 but it has not gotten much love so far.

**Comment by rudygalfi** [comment]
This is a good suggestion to make analytics configuration more robust, but I'm not seeing a great path for doing this due to the vendor rules we'd need to support and since we can't make assumptions about what kind of input vendors would generally expect.
