### ISSUE TITLE
Images with responsive layout don't appear in <amp-carousel layout='responsive'> (canary / slidescroll experiment)

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#4423]
To repro:

Toggle dev channel and amp-slidescroll on the [experiments page](https://cdn.ampproject.org/experiments.html)

Look at the carousels on the following pages:
[example 1] (https://cdn.ampproject.org/c/amp.usatoday.com/story/87534472/)
[example 2] (https://cdn.ampproject.org/c/www.ansa.it/amp/sito/notizie/tecnologia/internet_social/2016/08/05/facebook-guerra-ai-titoli-esca_21fa9d64-a600-44dc-b026-52958082f662.html)

Images do not appear (likely root cause: images are set to "responsive" layout)

**Comment by ericlindley-g** [comment]
Passing to @sriramkrish85  as part of the carousel enhancement work

**Comment by sriramkrish85** [comment]
Fixed
