### ISSUE TITLE
Pointing of desktop version to our AMP version or Google's CDN?

### ISSUE THREAD

**Issue by shaneleonard121** [ampproject/amphtml#4438]
Hi TeamAmp,

We've created AMP pages for every stock in the world, e.g. https://amp-api.stockflare.com/stock?ric=googl.o but are wondering where to we set the meta tags in our desktop version to point to.

Do we link the version to our AMP pages or to the CDN?

- i.e. to https://amp-api.stockflare.com/stock?ric=googl.o
- or https://cdn.ampproject.org/c/s/amp-api.stockflare.com/stock?ric=googl.o

Many thanks,

Shane

**Comment by rudygalfi** [comment]
Can you check out this page and let me know if it's helpful?

https://www.ampproject.org/docs/guides/discovery.html

**Comment by rudygalfi** [comment]
Ah, just read more closely: You wouldn't point at the CDN explicitly, so it would be the first link.

**Comment by shaneleonard121** [comment]
Ah, thanks a million @rudygalfi we went through it but concluded that we should point at the CDN :( Thanks for the pointer. Shane cc: @stratmm
