### ISSUE TITLE
No (lightening bolt) amp icon for amp content in search results

### ISSUE THREAD

**Issue by shaneleonard121** [ampproject/amphtml#4439]
Hi TeamAMP,

When I search for our amp content on Mobile Safari it says "mobile friendly" but there is no (lightening bolt) amp icon.

See screenshots here: http://imgur.com/a/lIku3

Are those icons for the Top Carousel only?

Thanks again for the insight.

Shane cc:@stratmm

**Comment by rudygalfi** [comment]
This will be a better place to surface issues to Google product teams: https://productforums.google.com/forum/#!topicsearchin/webmasters/category$3Aaccelerated-mobile-pages-amp%7Csort:relevance%7Cspell:false.

One quick thing that comes to mind: Are you using the special developer preview link that Google announced? Google's search results don't currently show AMPs by default but you can check out the preview experience at g.co/ampdemo. If that doesn't work, a second guess is that you need to wait a bit for the pages to be discovered and indexed by Google.

**Comment by shaneleonard121** [comment]
@rudygalfi @dvoytenko thanks a million for the help. Much appreciated.
