### ISSUE TITLE
Bug: lightbox with light scrim (instead of totally black layer) reveals pages jump on entry when in AMP viewer context

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#4440]
To repro:

On mobile device or mobile emulator: go to a site that implements a modal rather than full-page lightbox, displayed in an AMP viewer: [example](https://www.google.com/amp/m.ebay.com/sch/amp/Electronic-Components/182412/bn_2311295/i.html)

Tap info button in header for carousel at the top of the page—you can see that the pages jumps to adjust for the header on the AMP viewer

Not sure who to pass to, but starting off with @aghassemi , since you're working on the lightbox improvements.

+ @rudygalfi for visibility

**Comment by aghassemi** [comment]
👍 For the general lightbox 2.0 case which can lightbox anything in the page, it would be hard to hide changes to the page in the background (the obvious work-around is a solid background). In this case (or generally lightboxes that are just modal dialogs) however we should be able to eliminate any page jumps.

**Comment by ericlindley-g** [comment]
@aghassemi Is there a quick fix we can make in the meantime for this case?

**Comment by aghassemi** [comment]
@ericlindley-g I believe so, I will look into it soon.

**Comment by muxin** [comment]
@ericlindley-g Is this still reproducible?

**Comment by ericlindley-g** [comment]
Nope—this works perfectly now! (I'm closing the bug, but incidentally, do you know what fixed this?)

**Comment by muxin** [comment]
This might have something to do with the `border-top` change in viewport I recently made for hide/show viewer header but I'm not exactly sure.
