### ISSUE TITLE
Bug: Slidescroll carousel in lightbox sometimes gets stuck (swipe gesture has no effect)

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#4441]
Tap on hero image in [example page](https://cdn.ampproject.org/c/www.dailymail.co.uk/news/article-3727174/amp/French-gymnast-breaks-leg-horrific-snap-echoed-arena-stretchered-standing-ovation.html)

Swipe around—if I do this enough times, at some point the image jumps unexpectedly, and touch no longer seems to register on the image, so swipe stops navigating the carousel

**Comment by sriramkrish85** [comment]
fixed by #4424
