### ISSUE TITLE
Support ad-refresh in amp-carousel

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#4442]
Feature request to support ad-refresh in amp-carousel. That is:
1. User swipes to ad in carousel, which displays as normal
2. User swipes away from ad
3. When the ad is no longer visible via the carousel, the ad gets a message that it is no longer visible, at which point it can choose to do nothing, or to refresh with a different ad
4. When the user swipes back to the same slide that held the ad in (1), the user sees a different ad

I'm not sure we want this behavior for ads when they scroll out of the viewport generally, so the implementation may be a special case for the more general visibility message I believe ads are sent

cc @jasti , @sriramkrish85

**Comment by jasti** [comment]
This is quite similar to #4038 which we decided was low on priority, so leaving it in backlog for now.

**Comment by jasti** [comment]
Overall received feedback on https://github.com/ampproject/amphtml/issues/4038 that ability to refresh is not priority. Glad to re-evaluate if this comes up again.
