### ISSUE TITLE
Bug: slidescroll <amp-carousel> does not wrap captions in the same way as previous <amp-carousel>

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#4443]
To repro: Open lightbox by tapping on the top image at [the example](https://cdn.ampproject.org/c/www.dailymail.co.uk/news/article-3727174/amp/French-gymnast-breaks-leg-horrific-snap-echoed-arena-stretchered-standing-ovation.html)

Observe that the captions overflow when you are opted into amp-slidescroll experiment

**Comment by sriramkrish85** [comment]
fixed by #4424
