### ISSUE TITLE
Amp-fit-text Overflows Containing Box

### ISSUE THREAD

**Issue by jonbuckley33** [ampproject/amphtml#4444]
In certain scenarios, amp-fit-text makes its contained text too large: the text overflows the amp-fit-text's containing box in the horizontal direction. The scenarios that I've seen this happen in is "tall" containing boxes. Eg., 50px by 100px boxes.

You can see an example of this issue on this [JSBin page](http://jsbin.com/gevasesaka/edit?html,output).

Issue occurs in Chrome. AMP version 1470343175507 is affected.

**Comment by dvoytenko** [comment]
Thanks for filing!

Assigning /to @zhouyx
