### ISSUE TITLE
Remove the "/base" prefix in the file serving path of Karma tests

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#4452]
Right now, one difference between our test environment and local dev environment is the file serving path. Karma by default put a `/base` prefix to all the files.

For example, in test env:
```
http://localhost/base/dist.3p/current/integration.js
```

In local dev env:
```
http://localhost/dist.3p/current/integration.js
```

This discrepancy costs us some extra logic to handle the path. For example [here](https://github.com/ampproject/amphtml/blob/master/src/3p-frame.js#L209).

This can be eliminated by a simple change in Karma config:

```
proxies: {
  '/': '/base',
},
```

This change is quite safe and should not break anything, because the old path with `/base` would still work.

@erwinmombay do you think that will work?

**Comment by rudygalfi** [comment]
Putting in Current milestone as it looks like there's ongoing work. Please confirm or correct.
