### ISSUE TITLE
Amp-analytics Visibility Spec Doesn't Properly Track Amp-Lightboxes

### ISSUE THREAD

**Issue by jonbuckley33** [ampproject/amphtml#4454]
The amp-analytics component supports the ability to set up triggers that fire when an amp-component has been visible on screen for a defined amount of time. However, this feature is buggy when the trigger is set up on an amp-lightbox. 

When a visibility trigger is set up with the "selector" property pointing to an amp-lightbox, the trigger will correctly deduce when the lightbox becomes visible (when the user has caused the lightbox to open), but amp-analytics will not correctly deduce when the lightbox is closed.

For example, let's say you have a trigger set up on a lightbox that looks something like this: 

`"fiveSecondsHalfVisible": {
          "on": "visible",
          "request": "visibility",
          "visibilitySpec":  {
            "selector": "#lightbox",
            "visiblePercentageMin": 50,
            "totalTimeMin": 5000
      }
}`

Let's say after page load, there is no interaction for 10 seconds. Amp-analytics would correctly not fire the fiveSecondsHalfVisible trigger since the lightbox is closed. Then the user clicks a button that causes the lightbox to open. The user immediately closes the lightbox after opening it by clicking another button. At this time, the lightbox is again not visible. However, after 5 seconds, the fiveSecondsHalfVisible trigger will fire anyway.

You can play with an example of this bug at this [JSBin](http://jsbin.com/fepacukawa/19/edit?html,console,output).

Steps to reproduce:

1. Navigate to [JSBin page](http://jsbin.com/fepacukawa/19/edit?html,console,output).
2. Right click in the "output" pane and open Chrome Dev Tools. 
3. Go to the network tab.
4. Reload the page, keeping the Chrome Dev Tools open.
5. Click on the "Show Lightbox" button.
6. Immediately press the "Hide Lightbox" button.
7. Wait 10 seconds.
8. Observe that there are two requests to "is_visible.com", one for a 5 second event and one for a 10 second event.

The bug is found in AMP Version 1470677001097 and on Chrome.

**Comment by avimehta** [comment]
@dvoytenko Looks like  `getIntersectionChangeEntry()` returns non-zero values for lightbox even when it is not visible. Any ideas on what the right fix here would be?
