### ISSUE TITLE
Adsense google_ad_channel supporting

### ISSUE THREAD

**Issue by FabienU** [ampproject/amphtml#4464]
It is possible to add supporting of google_ad_channel property by amp-ad with type adsense?

**Comment by ericlindley-g** [comment]
Passing to @jasti , who focuses on Ads in AMP

**Comment by jasti** [comment]
Sorry about the delay. @bobcassels would you know?

**Comment by FabienU** [comment]
Hello, could you please left any feedback regarding possibility implementation of this feature?

**Comment by jasti** [comment]
@konakk Do you have an update on supporting google_ad_channel property is on the roadmap?
Thanks.

**Comment by konakk** [comment]
Channels can be set up using adsense UI without changing anything in the
tag. Support help center has a video showing how to do it.
https://support.google.com/adsense/answer/65083?hl=en-GB

**Comment by FabienU** [comment]
I think you wrongly understand me, I'll try to clarify my question.
For now I have already created google_ad_channel's in adsense,
and showing ads like below (I passing additionally google_ad_channel for tracking performance by this parameter):
$('#' + {{adContainer}}).html(
         '<ins class="adsbygoogle" style="display:block" data-ad-client="{{adClient}}" data-ad-slot="{{adSlot}}" data-ad-format="auto"></ins><script> (adsbygoogle = window.adsbygoogle || []).**push({params: { google_ad_channel: "{{chId}}" }});**<\/script>'
         );

And I looking for possibility of passing google_ad_channel with amp-ad tag with type adsense like below:
<amp-ad
            type="adsense"
            data-ad-client=""
            data-ad-slot=""
            **data-ad-customchannel=""**>
</amp-ad>

**Comment by FabienU** [comment]
Could you check my previous question?

**Comment by jridgewell** [comment]
> Could you check my previous question?

/cc @konakk

**Comment by konakk** [comment]
Supporting channel is not on the roadmap yet.

**Comment by bobcassels** [comment]
We will support it, as "data-ad-channel". I will add it to one of the branches I'm working on. So "real soon now."

**Comment by jridgewell** [comment]
@bobcassels: We got another request for this in #7286. Was this implemented?

**Comment by jasti** [comment]
Ping @michaelkleber as well, since I know Bob has moved to do other things.

**Comment by michaelkleber** [comment]
@glevitzky Can you handle this?  No problem adding data-ad-channel parallel to e.g. data-ad-client.

**Comment by glevitzky** [comment]
I'll gladly take a look. Can I get a little more context first? What exactly will it entail to "support" data-ad-channel? Is this just a data attribute that needs to be whitelisted for AdSense, or what?

**Comment by michaelkleber** [comment]
Whitelist it, and propagate its value through to the adsbygoogle ins in adsense.js, and into the &channel= ad request parameter in the a4a request flow.

**Comment by jasti** [comment]
@glevitzky is this something still on your radar? CC @keithwrightbos

**Comment by glevitzky** [comment]
Thanks for the reminder, Vamsee. I have a PR for this; I just need to clean it up a little and should have it out before our next cut.

**Comment by TamerMobarak** [comment]
Can this option be available soo ?
<amp-ad
            type="adsense"
            data-ad-client=""
            data-ad-slot=""
            data-ad-customchannel="">
</amp-ad>

**Comment by glevitzky** [comment]
PR is ready to merge, pending on one reviewer's comment.

**Comment by TamerMobarak** [comment]
How can I know when it is RELEASED ?! any link to follow ??

**Comment by TamerMobarak** [comment]
Can you please tell me, Is it ready now ?
Can I use the " data_ad_channel " ?

**Comment by glevitzky** [comment]
Sorry for the delay, Tamer. PR should be merged today and available in canary after next cut, and in production in the subsequent cut (~2 weeks from tomorrow).

**Comment by TamerMobarak** [comment]
Now,I need to know, Is this feature available now?
Meaning: Can I use such code in my AMP blogger template now?
<amp-ad
layout="fixed-height"
height="90"
type="adsense"
data-ad-client="ca-pub-1234567890123456"
data-ad-slot="1234567890">
google_ad_channel = &quot;XXXXXXXX&quot;;
</amp-ad>

**Comment by jasti** [comment]
Yes, but I don't see it being documented. @glevitzky is this documented?
