### ISSUE TITLE
amp-accordion: Tracking open events

### ISSUE THREAD

**Issue by eike-hass** [ampproject/amphtml#4465]
Similar to Issue #4292 we need to track interactions with the amp-accordion. Getting an interaction event (click/tab) would be ideal. Wold a common solution be possible?

**Comment by eike-hass** [comment]
I just noticed this could be easily achieved using the default click tracking. I guess this can be closed.

**Comment by rudygalfi** [comment]
Yes, the `click` trigger in amp-analytics should work.
