### ISSUE TITLE
Intent To Implement: Pubmine ad network for amp-ads

### ISSUE THREAD

**Issue by dbspringer** [ampproject/amphtml#4471]
Support for [WordAds/AdControl](https://wordads.co/) ad network hosted at pubmine to `amp-ad` elements.

**Comments**
Automattic will be submitting a PR via the `Automattic/amphtml` fork from the `add/ad-pubmine` branch. See: https://github.com/Automattic/amphtml/tree/add/ad-pubmine (work in progress)

Original thread: https://github.com/Automattic/amp-wp/issues/217

**Comment by rudygalfi** [comment]
cc @jasti @tomremo

**Comment by dbspringer** [comment]
PR: https://github.com/ampproject/amphtml/pull/4603

**Comment by dbspringer** [comment]
🙇
