### ISSUE TITLE
Missing </amp-img> tags

### ISSUE THREAD

**Issue by Gregable** [ampproject/amphtml#4477]
When replacing `<img>` tags with `<amp-img>` tags is fraught with a specific type of mistake. `<img>` tags are void tags in HTML5, meaning that they are self-closing. `<amp-img>` cannot be made to be self-closing without changing a browser's HTML parser.

Changing `<img ...>` to `<amp-img ...>` is a mistake.
Changing `<img ...>` to `<amp-img ...></amp-img ...>` is correct.

The mistake may not cause rendering issues in most cases, but can cause them in some subtle cases, where CSS depends on the DOM structure or in cases like `<amp-live-list>` children as described [here](https://github.com/ampproject/amphtml/issues/4074). Since this is very subtle, it could easily go unnoticed. We can imagine hypothetical cases where this would result in a broken looking document, but we haven't actually spotted any in the wild yet.

Validating that `<amp-img>` tags are followed by `</amp-img>` is not feasible at this stage due to the large fallout.

After discussing this with @powdercloud, we came up with two suggested recommendations:
1. Explicitly call out this potential issue in `<amp-img>` documentation.
2. AMP runtime should detect child nodes of `<amp-img>` without the `fallback` attribute and:
   1. Emit a runtime error to the dev console.
   2. Move all children of `<amp-img>` to be immediate siblings in the DOM instead.

**Comment by dvoytenko** [comment]
Can we just do it in validator? We can certainly do some of the warnings in development mode for `amp-img`, but it seems like validator can do them as easily?

> Move all children of <amp-img> to be immediate siblings in the DOM instead.

We certainly cannot do that.

**Comment by Gregable** [comment]
> Can we just do it in validator? We can certainly do some of the warnings in development mode for amp-img, but it seems like validator can do them as easily?

Too many pages will break to do this in validation at this point. If we make it a warning, we'll probably never be able to promote it to an error. We really want to avoid having permanent warnings in validation because it'll teach folks to ignore them. As a result, I think there are no good validation routes available.

> > Move all children of to be immediate siblings in the DOM instead.
>
> We certainly cannot do that.

Why not? This is **exactly** what would happen if the </amp-img> tag were in place.

**Comment by dvoytenko** [comment]
> Why not? This is exactly what would happen if the </amp-img> tag were in place.

The time when we normally operate, there might not be even siblings parsed yet.

**Comment by Gregable** [comment]
Maybe just restrict the scope of this issue to a runtime error plus some added documentation then.
