### ISSUE TITLE
Too many errors

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#4487]
we are just reporting too many errors right now to our reporting server. We need to stop sending out duplicate errors for a single page. for example a single page can fire over 10 "pause() called on an already paused resource" error for every time a page goes in active.

options:
- do sampling on go server code or in js
- add lookup table in js code to not report error's its reported for a page before

cc @dvoytenko @aghassemi

**Comment by dvoytenko** [comment]
Hmm. Calling pause on a paused resource shouldn't cause error. It's better to fix that than to suppress.

**Comment by aghassemi** [comment]
yeah https://github.com/ampproject/amphtml/pull/4489 will remove the error. It originally helped find bunch of problems but there are valid cases where pause is called on a paused resource and as you mentioned it should not generate errors.

**Comment by erwinmombay** [comment]
Great, SGTM.

**Comment by erwinmombay** [comment]
I'll patch production once that is merged

**Comment by aghassemi** [comment]
@erwinmombay Thanks! can we lower the priority or close this after it is merged?

**Comment by erwinmombay** [comment]
@aghassemi yep, good to close after that goes in. the pause() error is like 75% of our errors right now so it should be reduced significantly

**Comment by erwinmombay** [comment]
Closed by https://github.com/ampproject/amphtml/pull/4489
