### ISSUE TITLE
Change video in amp-youtube

### ISSUE THREAD

**Issue by devilbags** [ampproject/amphtml#4488]
Since AMP does not allow Javascript, How can I change the video-id of a existing amp-youtube component?

**Comment by rudygalfi** [comment]
@devilbags What use case do you have in mind for changing the video ID? For example, is it a user-initiated action like clicking to toggle between two videos?

**Comment by devilbags** [comment]
@rudygalfi Yes it is user initiated. For example, a list of related videos under the existing amp-youtube component.

**Comment by ericlindley-g** [comment]
Thanks @devilbags—there's currently no method to do this in AMP, but we can investigate options for this as a feature request.

**Comment by ericlindley-g** [comment]
Might be a good fit for amp-bind. @devilbags, can you point to an example web page that demonstrates the feature you'd like to have in AMP?

**Comment by kmh287** [comment]
[Here's an example](https://github.com/ampproject/amphtml/blob/master/examples/bind/video.amp.html#L46) of changing `amp-youtube`'s `data-videoid` attribute with bind. @ericlindley-g can we close this issue?

**Comment by ericlindley-g** [comment]
Yep—thanks @kmh287 !
