### ISSUE TITLE
Videos In Amp-Carousel In Amp Lightbox Don't Stop On Close

### ISSUE THREAD

**Issue by jonbuckley33** [ampproject/amphtml#4503]
On pages in which there is a video inside a carousel inside a lightbox, the videos are not automatically paused when the lightbox is closed. Conversely, If the videos are not inside a carousel, they are paused, so it seems to be an issue with the nesting of carousels and lightboxes that breaks the pause-on-close behavior.

You can reproduce this issue at this [JSBin page](http://jsbin.com/sewanarura/14/edit?html,output). 
1. Click the "open lightbox" button
2. Play the youtube video
3. Click the "close lightbox" button
4. Observe that the audio is still playing from the youtube video

Affects AMP version 1471018286527 running in Chrome.

**Comment by aghassemi** [comment]
We have fixed similar issues but this looks like a different type of bug: carousel - and possibly other amp elements that can contain amp elements - not propagating pause/resume/layout/unlayout, etc.. requests to their children.

I will look into it.

**Comment by adelinamart** [comment]
What is the latest update here? Thanks.

**Comment by aghassemi** [comment]
This might already be fixed, talk to @cathyxz  since `amp-lightbox-gallery` would have had this issue as well.

**Comment by alanorozco** [comment]
Taking this especifically for video.
