### ISSUE TITLE
Document analytics integrations for components

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#4508]
The idea is to illuminate how to use existing amp-analytics features to track certain components.

I see this being implemented as an "Analytics" section in the .md file of various amp-\* components (some but most certainly not all). There will be use-cases listed as subheadings with a code sample.

Here are the components where I think this applies today:
- amp-accordion
  - Track click on header to open
  - Track click on header to close
  - Track visibility of accordion
- amp-lightbox
  - Track click opening lightbox
  - Track click closing lightbox
  - Track visibility of thing that will show in lightbox
- amp-sidebar
  - Track open of sidebar
  - Track closing of sidebar
- amp-social-share
  - Track click on social share provider
- amp-sticky-ad
  - Track ad being displayed / visible
  - Track closing ad
- amp-user-notification
  - Track user notification being displayed / visible
  - Track dismissing user notification

Note that amp-carousel should likely have its own events, so #4292 will track that.

cc @avimehta @jmadler @sebastianbenz @ericlindley-g

**Comment by adelinamart** [comment]
@bpaduch what's the situation with this one? Thanks

**Comment by bpaduch** [comment]
Low priority, no action.

**Comment by bpaduch** [comment]
will look @ in: Q1/Q2

**Comment by bpaduch** [comment]
I suspect this will be part of a larger docs initiative for "analytics".

**Comment by CrystalOnScript** [comment]
@jeffjose @zhouyx @rudygalfi 
Can someone point to where we would be able to find component specific analytics triggers? Is there someone who has a list available?

**Comment by zhouyx** [comment]
Unfortunately we don't have such a place where all component specific analytics triggers are listed. Each component have documented their own custom triggers in different places.
