### ISSUE TITLE
SOURCE, AMP-VIDEO, AMP-AUDIO Tags don't support datauri

### ISSUE THREAD

**Issue by dknecht** [ampproject/amphtml#4516]
The AUDIO and VIDEO tags do support datauri.  Should these be consistent?

**Comment by Gregable** [comment]
@dvoytenko I don't recall any explicit reason. Would it be to avoid really large pages?

**Comment by dvoytenko** [comment]
It's definitely possible. I'll dig around a bit more to confirm.

**Comment by dknecht** [comment]
Agree they could create long pages. This was more a question of consistency.

**Comment by dvoytenko** [comment]
I'll close this for now. I asked around, but I didn't hear it to be a real use cases. Feel free to reopen if some good use cases are found.
