### ISSUE TITLE
amp-dailymotion problem

### ISSUE THREAD

**Issue by KayKayWhy** [ampproject/amphtml#4517]
amp-dailymotion video run perfectly in desktop. But, when you open the amp page with mobile device, the video cannot run with the error message "Whoops! Looks like we can't play this video in this browser."

The amp-dailymotion version used is https://cdn.ampproject.org/v0/amp-dailymotion-0.1.js

**Comment by ericlindley-g** [comment]
@zeno Are you the right person to take a look at this bug?

@KayKayWhy , in what device/browser do you see this bug? I'm able to repro at [this site](http://www.lexpress.fr/styles/vip/audrey-crespo-mara_1696707.amp.html) on desktop (where no video plays) and mobile emulator (where the ad pre-roll plays, but not the following video) in Chrome, but am not getting an issue on mobile devices for either Android (moto X in Chrome) or iOS (iPhone 6s in Chrome and Safari)

**Comment by KayKayWhy** [comment]
Hi @ericlindley-g, I think this happened due to I run my page by using Chrome's inspect element mobile view mode. I try it with my mobile devices and everything work fine. Thanks alot @ericlindley-g for the advice.
