### ISSUE TITLE
amp-user-notification validation and re-writes

### ISSUE THREAD

**Issue by dknecht** [ampproject/amphtml#4537]
Should amp-user-notification have any URL validation rules for data-*-href?  Cache doesn't currently re-write them to absolute and seeing example of below on publishers pages

<amp-user-notification data-dismiss-href="/setcookielaw" data-show-if-href="/cookielaw?timestamp=TIMESTAMP" id="amp-user-cookie" layout=nodisplay>

https://cdn.ampproject.org/c/s/www.express.co.uk/news/world/700398/north-korea-beer-festival-pyongyang-800-event-Choe-Yong-Nam-Taedonggang-Taedong/amp

**Comment by Gregable** [comment]
@dvoytenko

**Comment by erwinmombay** [comment]
are we currently rewriting data-*-href values? I dont think that should happen

**Comment by erwinmombay** [comment]
at the very least we definitely need to make the rules stricter on it so that it should be a absolute url.

@jmadler do we need to reach out to express.co.uk for them to fix?

**Comment by dknecht** [comment]
@erwinmombay Making them stricter sounds good.  There is currently no validation.

**Comment by Gregable** [comment]
@jmadler The other one to potentially reach out to would be businessonline (eg: http://amp.businessonline.it/news/34376/unico-2015-730-precompilato-e-cu-proroga-ufficiale-o-quasi-apre-a-proroga-tasi-e-imu-nuove-date.html). These are protocol relative, which are problematic if not tested carefully and in fact, these URLs don't work on https. We'll break these with validator changes.

Other than these two sites, I don't see much issue with making validation stricter.

**Comment by Gregable** [comment]
This is live everywhere.

**Comment by ithinkihaveacat** [comment]
FWIW, the validator now complains about relative URLs.

**Comment by jridgewell** [comment]
> FWIW, the validator now complains about relative URLs.

Opened https://github.com/ampproject/amphtml/issues/7289.
