### ISSUE TITLE
Facebook Likes & Gplus One

### ISSUE THREAD

**Issue by GangaNaresh** [ampproject/amphtml#4558]
How to implement AMP Facebook Likes & Gplus One?

**Comment by rudygalfi** [comment]
The Facebook Like button and Google+ +1 Button aren't currently supported, but you can use [amp-social-share](https://www.ampproject.org/docs/reference/extended/amp-social-share.html) for sharing capability. (I recognize these aren't equivalent.)

**Comment by cramforce** [comment]
We will most likely not support them, because they are pretty heavy weight. As Rudy mentions, the social share plugin is a better way to achieve similar results.

**Comment by ashrafpro** [comment]
https://www.ampproject.org/docs/reference/components/amp-facebook-like

this is working now (facebook like counts, share)
