### ISSUE TITLE
Can't set a specific mailto email address with the current amp-social-share email icon

### ISSUE THREAD

**Issue by riomyers** [ampproject/amphtml#4559]
## Short description of your issue:

There is not a way to set a specified `mailto` recipient with the current `amp-social-share` email icon
## How do we reproduce the issue?
1. Go to https://ampbyexample.com/components/amp-social-share/
2. Scroll down and click on the black email icon
3. this will open the default mail app with no recipient specified
## What browsers are affected?

All Browsers, All devices
## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1471018286527

**Comment by ericlindley-g** [comment]
@riomyers  I'm assuming this request isn't specifically for the social share use-case (where you'd be unlikely to predict who your users would share the site with : ), and instead is geared toward a "contact me"-type button, where users can send feedback or requests to the site-owner. Is that right?

If so, is there a reason you'd like to use `<amp-social-share>`, rather than defining your own mailto link?

**Comment by riomyers** [comment]
@ericlindley-g I suppose that makes more sense,  I was able to work around it easily using the `<amp-social-share>` as I ended up wrapping it in a mailto link, the interaction is supposed to share the users page which I understand but I wanted the email icon to be able to contact them directly, not allow them to share the page via email, since it's supposed to be used as a sharing page via email, it might be useful to at least grab the URL and pass it into the message data instead of just opening an empty send mail dialog as this is the what the current email icon interaction does

**Comment by ericlindley-g** [comment]
Thanks @riomyers—that makes sense: you're using the component to quickly get a nice styled icon for email, which you're wrapping in a custom mailto anchor.

W/r/t your second point: when I test the [AMP by Example for `<amp-social-share>`](https://ampbyexample.com/components/amp-social-share/), on Chrome, with gMail set as the default email client, I'm seeing that the email body is automatically populated with the canonical version of the page (this can be overridden with the attribute `data-param-body`). Do you have an example where that's not working?

**Comment by ericlindley-g** [comment]
Closing this for now, given that the existing method to implement a mailto: link might be simpler and more semantic than using the social share component. But please re-open if there's an angle I'm missing here. Thanks!

**Comment by jridgewell** [comment]
Reopening, because `mailto:` requires some special handling in iOS.

**Comment by ericlindley-g** [comment]
Thanks @jridgewell  — is anyone working on this, or just in the backlog? (putting at P3 for now)

**Comment by jridgewell** [comment]
Backlog. Could be a GFI.

**Comment by jridgewell** [comment]
Closing in favor of https://github.com/ampproject/amphtml/issues/10679.
