### ISSUE TITLE
fix assert function type inference

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#4560]
type inference on `assert` methods/functions is currently broken as closure compiler only checks if qualified name is equal to the current node in the AST's qualified name.

this means that our current assert functions which are invoked like so:

``` js
import {dev} from './src/log';

dev().assert()
```

does not have a qualified name. `dev` has a qualified name which is `dev$$module$src$log` but assert which is not a top level module function but a prototype method doesn't seem to have one on invocation. It was suggestted i try `new AssertionFunctionSpec("Log$$module$src$log.prototype.assert", JSType.TRUTHY)` but that also doesn't seem to work

The code below should be valid and should type check but it current does not:

``` js
/**
 * @param {?string} val
 * @return {string}
 */
function something(val) {
  dev().assert(val !== null); // we've asserted that it can't be null so the return type should be valid
  return val;
}
```

**Comment by ericlindley-g** [comment]
@erwinmombay  Please update the milestone when you have a sense of when work will start—thanks!

**Comment by adelinamart** [comment]
Is this still an issue? Thanks

**Comment by erwinmombay** [comment]
@adelinamart it is but super low priority but important enough to track

**Comment by rsimha** [comment]
This is fixed
