### ISSUE TITLE
"Experimental" status listing should point at consistent page

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#4569]
https://github.com/ampproject/amphtml/blob/master/tools/experiments/README.md is probably the most helpful.

Current issues are:
- amp-experiment points at https://cdn.ampproject.org/experiments.html, which doesn't shed light on the console method for enabling experiments that must be done on on pages that aren't served from the CDN.
- Other extensions like amp-form don't link to any help page.

**Comment by ericlindley-g** [comment]
Added to "Docs Updates..." — it's starting to feel like a good time to schedule another concerted docs effort
