### ISSUE TITLE
amp-iframe Internet Explorer 11

### ISSUE THREAD

**Issue by Polylike** [ampproject/amphtml#4570]
## Short description of your issue:

Some amp-iframes didn't load on Internet Explorer 11 Version 11.545.10586.0

## How do we reproduce the issue?

amp-iframe with Google Form or other Conent didn't work and the iframe didn't loading.
https://goo.gl/FihmG2 - iFrame on bottom
https://goo.gl/A52yjn - iFrame on middle

amp-iframe for Google Maps working fine:
https://goo.gl/krEljt

## What browsers are affected?

Internet Explorer 11 Version 11.545.10586.0

**Comment by mkhatib** [comment]
Can't reproduce this on `IE 11.0.14393.0`. iframes are rendering as expected.

I can see the version mentioned is larger, so will try to update to that version and see if I can reproduce.

**Comment by mkhatib** [comment]
@Polylike looks like [IE had a known-bug](https://support.microsoft.com/en-us/kb/3176757) in recent security updates with `iframe`.

Can you please update your IE and see if you're still seeing the issue? Please reopen if you do.

**Comment by Polylike** [comment]
After Update, everything works fine. Looks like the known IE Bug. Thanks a lot.
