### ISSUE TITLE
Viewer shares wrong article (possibly on stale page)

### ISSUE THREAD

**Issue by tdrl** [ampproject/amphtml#4571]
## Short description of your issue:

When viewing an article in the AMP viewer from the Google News & Weather app, clicking the "share" button yielded a share of the wrong article (an article different than the one I was looking at).  The viewed page was stale (~8 hours old) by the time I clicked "share", in case that's a factor.

## How do we reproduce the issue?

I was browsing news last night through the Google News & Weather app and selected an article from the AMP carousel at the top:

![image](https://cloud.githubusercontent.com/assets/17705064/17740372/60583cee-6466-11e6-844c-c7431ea9962c.png)

Then I went to bed.  This morning, I decided to "share" it via Inbox.  I was surprised to discover that, on hitting the "share" button, I got an email populated with the wrong article:

![image](https://cloud.githubusercontent.com/assets/17705064/17740449/a34260d4-6466-11e6-8af6-07a2403e5759.png)

So far, it's a one-off occurrence, so I'm not sure if it's reproducible.  :-(

Device: Android 5
Browser: Chrome

**Comment by rudygalfi** [comment]
Thanks for the report. I'll send this to the Google News team to see if they could investigate.
