### ISSUE TITLE
expose client-side storage with forms and live-list

### ISSUE THREAD

**Issue by eike-hass** [ampproject/amphtml#4572]
We need to implement a client-side bookmark solution. This would usually easily be solved by using localstorage or cookies. 
Because of the special nature of AMP a possible solution would be to expose the AMP internal storage implementation. This loosely relates to issue #4272, since a target for forms could be said storage.
Finally the `amp-live-list` could be used to implement the list of bookmarks read from the storage.
Would that be possible? Are there other client-side possibilities?

**Comment by ericlindley-g** [comment]
@eike-hass Thanks for reaching out—do you have an example page to get a better sense of your use-case? Why do you need a client-side solution in particular?

`<amp-live-list>` supports live-updating cases like live blogs, where the user wants to get updates as soon as they are available. Your bookmark use-case sounds more like something that would just be needed on the initial load, and maybe after a user action to add another bookmark. Is that right?

**Comment by cramforce** [comment]
I don't fully understand this use case. Is this like a favorite mechanism where one can mark articles that one would like to get back to.

**Comment by eike-hass** [comment]
@cramforce: yes, excactly

**Comment by cramforce** [comment]
Hmm, we currently only allow 8 bits of storage per site and given the distributed nature of AMP where this storage is per container (Google, Twitter, Nuzzel, Origin site), client side storage would lead to a very frustrating experience I believe.

This could already be done with the unfortunately named `amp-list` that can be used to update an area of the DOM based on a JSON request and client side render, but storage would be server side in that case.

**Comment by adelinamart** [comment]
Do we still need this? Thanks

**Comment by ericlindley-g** [comment]
Closing for now, but please feel free to re-open if @cramforce 's suggestion of `amp-list` doesn't fully address the issue.
