### ISSUE TITLE
amp-iframe: make client-ID accessible

### ISSUE THREAD

**Issue by eike-hass** [ampproject/amphtml#4573]
We want to display personalized content in an `amp-iframe`. Therefor we need to access the Client-ID in the embedded document. 
From my understanding this would be possible in iframes served from the same origin as the document by reading the cookie, but not if the document is delivered via the AMP-CDN. 
Would it be possible to solve this by enabling the "URL Variable Substitutions" for `amp-iframe`, or maybe by taking a similar approach to `amp-ad`?

**Comment by lannka** [comment]
URL substitution does sound a reasonable solution to me. 

What `amp-ad` approach were you talking about?

**Comment by eike-hass** [comment]
@lannka from what i understand the ad is able to access the ["AMP client id"](https://github.com/ampproject/amphtml/blob/master/builtins/amp-ad.md#data-consent-notification-id). Am i mistaken?

**Comment by sebastianbenz** [comment]
I've encountered the same problem when creating the [amp-analytics](https://ampbyexample.com/components/amp-analytics/) sample for ABE. Support for variable substitutions in iframes would've definitely helped.

**Comment by lannka** [comment]
@eike-hass I see what you mean. But that's probably not what you want. That gives you the `ad-cid`, which has its own scope per ad network.

**Comment by eike-hass** [comment]
@lannka gotcha. thank you for clearifying

**Comment by lannka** [comment]
@rudygalfi do you see any risk of exposing all runtime variables to iframe src? Otherwise I think it's something we can do.

**Comment by rudygalfi** [comment]
At first glance, I don't see concerns.

**Comment by cramforce** [comment]
We do not want to make variable substitution available to `amp-iframe`, because that opens up usage of it for undesired purposes such as ad serving and analytics.

**Comment by jridgewell** [comment]
Closing per https://github.com/ampproject/amphtml/issues/4573#issuecomment-243470304.

**Comment by sebastianbenz** [comment]
The initial request was to only make the CLIENT_ID available in iframes. Not necessarily all variable substitutions. Would this be viable?

iframes are often the only way to realise complex integrations. Being able to personalise their content is a common use case which AMP currently doesn't support.

**Comment by cramforce** [comment]
Basically we'd be more comfortable to allow everything but CLIENT_ID.

**Comment by AndrewKGuan** [comment]
why are ad serving and analytics undesired purposes?
