### ISSUE TITLE
Viewport with ; pass validation on cache and fails on JS

### ISSUE THREAD

**Issue by dknecht** [ampproject/amphtml#4577]
Should this be fixed in cache validator or JS validator?  There are pages out in the wild, but very few. 

`<meta name="viewport" content="width=device-width;minimum-scale=1">`

The cache has no issues.  

From JS

> The property 'width' in attribute 'content' in tag 'meta name=viewport' is set to 'device-width;minimum-scale', which is invalid. MANDATORY_AMP_TAG_MISSING_OR_INCORRECT
line 17, column 2
> The property 'minimum-scale' is missing from attribute 'content' in tag 'meta name=viewport'. MANDATORY_AMP_TAG_MISSING_OR_INCORRECT
line 17, column 2
> The mandatory tag 'meta name=viewport' is missing or incorrect. MANDATORY_AMP_TAG_MISSING_OR_INCORRECT
line 24, column 7

**Comment by Gregable** [comment]
@dvoytenko any preference on if this is valid or not?

**Comment by dknecht** [comment]
one more.  this passes on cache.  
`<meta name="viewport" content="width==device-width,minimum-scale=1">`

**Comment by dknecht** [comment]
I think the JS is wrong.  

https://drafts.csswg.org/css-device-adapt/#parsing-algorithm

```
The separator class contains the following characters (ascii), with comma as the preferred separator and semicolon as optional:

Comma (0x2c)
Semicolon (0x3b)
```

```
Parse-Content(S)
i ← 1
while i ≤ length[S]
    do while i ≤ length[S] and S[i] in [whitespace, separator, '=']
        do i ← i + 1
    if i ≤ length[S]
        then i ← Parse-Property(S, i)
```

**Comment by dvoytenko** [comment]
Looks like both separators are valid. We should fix inconsistency. We have another place where viewport meta is parsed in runtime so we should fix that as well.

/cc @zhouyx could you please take a look. It's in `viewport-impl.js` `parseViewportMeta` method.

**Comment by zhouyx** [comment]
looks like in `parseViewportMeta` we only split content by comma, not by semicolon.

**Comment by dvoytenko** [comment]
Thanks, @zhouyx for fixing this in runtime. Let's proceed and do the same in validators. Over to you @Gregable

**Comment by Gregable** [comment]
Fixed. Javascript changes should be live in a couple hours.
