### ISSUE TITLE
amp-img srcset does not allow both width based and retina images to be specified

### ISSUE THREAD

**Issue by riomyers** [ampproject/amphtml#4602]
## Short description of your issue:

I am trying to specify different images to load based on device width and also based on pixel ratio, however it seems that when I try to use both in an srcset the image will not load at all

## How do we reproduce the issue?

This works:
```
<amp-img
    src="space.jpg"
    srcset="space2.jpg 1x,space3.jpg 2x"
    width="2560"
    height="1440"
    layout="responsive"
    alt="an image">
</amp-img>
```

This works:
```
<amp-img
    src="space.jpg"
    srcset="space2.jpg 320w,space3.jpg 640w"
    width="2560"
    height="1440"
    layout="responsive"
    alt="an image">
</amp-img>
```

But this does not:
```
    <amp-img
    src="space.jpg"
    srcset="space2.jpg 1x,space3.jpg 2x,space4.jpg 320w,space5.jpg 640w"
    width="1600"
    height="900"
    layout="responsive"
    alt="an image" on="tap:caption1" role="button" tabindex="0">
</amp-img>
```

How can I specify both at the same time? For example some devices such as the iPad can have the same widths but one device supports retina and the other does not so I need to be able to provide a solution for both of those cases, however this doesn't seem to be possible? 

I even tried specifying multiple srcsets which works but it will only use the first one in the html order

Maybe you can allow something like this to support both cases:
```
    <amp-img
    src="space.jpg"
    srcset="space2.jpg 320w 1x,space3.jpg 320w 2x,space4.jpg 640w 1x,space5.jpg 640w 2x,"
    width="1600"
    height="900"
    layout="responsive"
    alt="an image" on="tap:caption1" role="button" tabindex="0">
</amp-img>
```
## What browsers are affected?

All browsers and All Devices

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1471018286527

**Comment by dvoytenko** [comment]
@riomyers This is not allowed by HTML spec:

https://w3c.github.io/html/semantics-embedded-content.html#element-attrdef-img-srcset

> If an image candidate string for a source or img element has the width descriptor specified, all other image candidate strings for that element must also have the width descriptor specified.

Further, the width specified is an intrinsic or natural width, not a context width. The context width can be specified via `sizes` attribute. We select the best quality image for the specified natural width and device's pixel ratio. So if you provide an srcset with widths `100px` and `300px` and given a context width of `100px` - we will pick 100px for dpr=1 and 300px for dpr=3.

**Comment by dvoytenko** [comment]
I'll close this for now, but please reopen if needed.
