### ISSUE TITLE
Make sure all absolute URLs in samples are functional

### ISSUE THREAD

**Issue by jmadler** [ampproject/amphtml#461]

**Comment by ericlindley-g** [comment]
@jmadler  Did #390 address this? Can it be closed?

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please verify first whether the feature proposal is still relevant.

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
