### ISSUE TITLE
Inconsistent usage of max-timer-length vs maxTimerLength in timerSpec

### ISSUE THREAD

**Issue by andyblackwell** [ampproject/amphtml#4611]
It looks like the correct one is `maxTimerLength`, but `max-timer-length` is used in an example, and in a couple analytics vendor implementations.

https://github.com/ampproject/amphtml/search?utf8=%E2%9C%93&q=maxTimerLength
https://github.com/ampproject/amphtml/search?utf8=%E2%9C%93&q=max-timer-length

https://github.com/ampproject/amphtml/blob/master/examples/analytics.amp.html
https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/vendors.js

**Comment by avimehta** [comment]
https://github.com/ampproject/amphtml/pull/4576 fixes the example. Will update vendor.js in that PR as well.
