### ISSUE TITLE
Colombia ad example broken

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#4613]
```
VM39918 integration.js:4920 Uncaught Error: Missing attribute for colombia: clmb_divid.​​​
```

Seems the example is missing mandatory fields. To reproduce, check [here](http://amphtml-nightly.herokuapp.com/examples/ads.amp.html#colombia).

@ColombiaOnline could you take a look?

**Comment by adelinamart** [comment]
Is this still broken? Thanks

**Comment by lannka** [comment]
I believe so. Needs their fix.

**Comment by adelinamart** [comment]
@lannka it seems @ColombiaOnline is not answering. Is there any otehr to reach them or shall we close this? Thanks

**Comment by lannka** [comment]
I will remove the example and close the bug.
