### ISSUE TITLE
SOVRN ad example is broken

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#4614]
```
yay positive response sovrn.amp.handleResponse({
  "id" : "342521",
  "seatbid" : [ ]
})
sovrn_ads.js:1 error is TypeError: Cannot read property 'bid' of undefined(…)
```

To reproduce, check [here](http://amphtml-nightly.herokuapp.com/examples/ads.amp.html#sovrn).
@mcofran could you please take a look?

**Comment by mcofran** [comment]
Thank you Hongfei.  I am working on getting this request into the appropriate hands.

Thanks,

Martha Cofran | Director of Engineering, AdTech
720-201-2691 Cell

mcofran@sovrn.com <mailto:mcofran@sovrn.com>
sovrn.com <http://sovrn.com/> | sovrn pubhub <http://pubhub.sovrn.com/> | @sovrnholdings <http://twitter.com/sovrnholdings>
 
 <http://www.sovrn.com/onscroll>

**Comment by sovrnoss** [comment]
@lannka 

Looks like that sovrn tag isn't returning responses.
Our team will create an account with a tag that always returns "test" creatives.

We will update this thread with the replacement tag once that's complete.

Thanks,
sovrn Support Team

**Comment by lannka** [comment]
@sovrnoss that will be awesome. thanks for looking into it.

**Comment by sovrnoss** [comment]
@lannka 

Thank you for being patient with us on this, we have a created a tag that will return a test creative, the id is 393900.  Please let us know if you need any additional information. 

Thanks,
sovrn Support Team

**Comment by sovrnoss** [comment]
@lannka 

Have you had a chance to evaluate our new ad tag? Can we close this issue or do you need additional information?

Thanks,
sovrn Support Team

**Comment by lannka** [comment]
sorry @sovrnoss I missed your previous reply.

unfortunately I still can't get it right with your new ID.

```
yay positive response sovrn.amp.handleResponse({
  "id" : "393900",
  "seatbid" : [ ]
})
sovrn_ads.js:1 error is TypeError: Cannot read property 'bid' of undefined(…)
```

**Comment by sovrnoss** [comment]
@lannka we've tested those zones on our end and they have been working, we're wondering what domain you ran your test on and if it needs to be whitelisted on our end. We whitelisted the http://amphtml-nightly.herokuapp.com/ domain, but any others will not receive a response from us. 

Thanks!
sovrn Support Team

**Comment by lannka** [comment]
@sovrnoss would it be possible for you to whitelist `localhost:8000`, for sake of manual test?

**Comment by sovrnoss** [comment]
@lannka localhost:8000 is now whitelisted and should be returning positive responses. Please confirm.

Thanks,
sovrn Support Team

**Comment by lannka** [comment]
@sovrnoss it works!
Thanks!
