### ISSUE TITLE
How does AMP-HTML page load javascript from rails/app/assets/javascript folder ?

### ISSUE THREAD

**Issue by tanaysh** [ampproject/amphtml#4623]
Before AMP I was using `JavaScript_include_tag 'application'` for including all js files but now after AMP implementation it shows error:

```ruby
The tag 'script' is disallowed except in specific forms
```
AMP supports async attribute and application/json+ld type in script tag , but I have to include js files from rails/app/assets/JavaScript folder

**Comment by aghassemi** [comment]
Hi @tanaysh,

AMP does not allow author written JavaScript beyond what is provided through the custom elements to reach its performance goals.

Please see the [AMP HTML spec](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md) for more details

**Comment by tanaysh** [comment]
I have a file at `rails/app/assets/javascripts/demo.js` , so is there any alternative to include this file without getting any error ?

**Comment by aghassemi** [comment]
@tanaysh No, you can not include JavaScript files in your AMP pages and that is by design.

**Comment by amphtml-team** [comment]
The only was to use your own JavaScript in AMP is to put what you need in
an iframe .
