### ISSUE TITLE
Invalid URL validator errors in JS

### ISSUE THREAD

**Issue by dknecht** [ampproject/amphtml#4625]
This example pass JS validator and fails the google cache validator.  

`  <a href="http://- www.example.com">Invalid URL</a>
`

`Malformed URL 'http://- www.example.com' for attribute 'href' in tag 'a'. (see https://www.ampproject.org/docs/reference/spec.html#links) [INVALID_URL]
`

Example of how go parses.
https://play.golang.org/p/fOlyzLqEFG

I think it probably makes sense to fix this in JS validator

**Comment by powdercloud** [comment]
I agree we should try to fix this.

**Comment by powdercloud** [comment]
Just added validator folks so it's on our radar screen.

Thank you for raising the issue.

**Comment by ericlindley-g** [comment]
@powdercloud Please update the milestone when you have a sense of when work will start—thanks!

**Comment by Gregable** [comment]
I'm working on porting our C++ URL parsing routines to javascript. I can't say for sure that it'll be identical to Go, but it'll probably be a lot closer.

**Comment by dknecht** [comment]
We aren't use go std one either.  It is too strict.

**Comment by Gregable** [comment]
The relevant parts of the C++ parser were ported over in https://github.com/ampproject/amphtml/pull/5274. This isn't live yet, but I'll close the bug for now. If you find other examples of parsing differences, let me know.

**Comment by Gregable** [comment]
This is now live.

**Comment by Gregable** [comment]
Scratch that, it is not yet live. Will update again later.
