### ISSUE TITLE
amp-access: login behavior on large screens

### ISSUE THREAD

**Issue by eike-hass** [ampproject/amphtml#4627]
Continuing the discussion from #2970: We feel that the current behavior of opening the login page in a browser dialog is not ideal in some cases. Would it be possible to display the login pages in a `amp-iframe`, possibly in a `amp-lightbox`?

**Comment by rudygalfi** [comment]
cc @ashwinlimaye

**Comment by ashwinlimaye** [comment]
We'll look into it, also feel free to suggest implementation tips if you've thought of it. One of the key considerations is this being able to work in a variety of contexts. esp. embedded in-app.

**Comment by dvoytenko** [comment]
@eike-hass The main question I have is how you currently approaching this in your own origin? If you currently use a redirect dance on your own origin - you can also continue using it with AMP - it's just that it's not available when proxying documents via CDNs. Otherwise, we are very interested in the case where iframe could be used for "inline" login purposes, so if you have implementation already, it'd be very good to see.

**Comment by eike-hass** [comment]
@dvoytenko the inline iframe would rely on `target="_parent"` to trigger a navigation on the parent window. I think for a "CDN-proof" solution there could be event similar to iframe resizing.

**Comment by dvoytenko** [comment]
@eike-hass I'd like to confirm few things:

1. Is an inline iframe actually your preferred solution? Or would you normally do something more classic such as "redirect to login page and back after login is done"?
2. Inline iframe is only limited to the login operation itself, right? I.e. it shows username/password form and such?
3. Are you planning to support social login? From what I normally observe, most of social logins don't fully work in iframes. This was the main motivation to open login dialog in the first place.

**Comment by eike-hass** [comment]
@dvoytenko:
1. Normally it would be a inline form, the iframe is the closest solution we could think of.
2. Login would be a easy win, but signup would definitely be a option to.
3. That is a good point. So far we don't require social logins though.
I think for this to work the most essential part would be the URL substitution (#4573) combined with a reliable way to redirect the parent window or possibly trigger a `apm-access` auth check without a reload.
