### ISSUE TITLE
Intent to implement support for iBILLBOARD AdServer

### ISSUE THREAD

**Issue by pbilik** [ampproject/amphtml#4628]
Hallo, our intent is implementing support for iBILLBOARD AdServer. We want to add support into amp-ad element.

CLA has been submitted. Corporation name: Internet BillBoard a.s.

**Comment by dvoytenko** [comment]
Sounds good. Looking forward to your PR.

**Comment by janpetkov** [comment]
Hi guys, 
we have build amp test page with new type="ibillboard",
is there any sandbox/way we could test it?

Regards
Jan

**Comment by pbilik** [comment]
related to https://github.com/ampproject/amphtml/pull/5392
