### ISSUE TITLE
Tick when the base CID is exchanged

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#4631]
/to @erwinmombay @lannka

**Comment by lannka** [comment]
If we `tick('get-cid')` for every page view, and `tick('store-cid')` when we create new base CID, will we have a good report on CSI that shows the percentage of `store-cid / get-cid`?

**Comment by dvoytenko** [comment]
What's the reference time for these? Is it the AMP Runtime start time? Viewer connection time? Or something else?

**Comment by dvoytenko** [comment]
Sorry, just realized that it says "if" :)

I think, yes, we could probably get the ratio in performance terms. Not sure how accurate it'll be given the sampling.

**Comment by lannka** [comment]
I think whatever reference time is fine, since we only care about the number of ticks, not the time latency.

**Comment by dvoytenko** [comment]
We definitely care about time as well. One of my concerns is that messaging pipe might take a little too long to be setup, thus I'd like to know. I'll also ping the viewer team - I believe they actually have better data on it since they are initiating the connection.

**Comment by ericlindley-g** [comment]
@lannka @erwinmombay Please update the milestone when you have a sense of when work will start—thanks!

**Comment by zhouyx** [comment]
@lannka is this still required? Feel free to reopen.
