### ISSUE TITLE
Webmaster Tools flags typography.com stylesheet as disallowed html

### ISSUE THREAD

**Issue by arajay** [ampproject/amphtml#4632]
Google search console and the AMP validator are giving me the following error: 
`<link rel="stylesheet" type="text/css" href="https://cloud.typography.com/6256354/724768/css/fonts.css">`
> The attribute 'rel' in tag 'link rel=' is set to the invalid value 'stylesheet'.

However the documentation shows that "typography.com" is a whitelisted provider for link tags:
https://www.ampproject.org/docs/reference/spec.html#custom-fonts

I think maybe the /webmasters/tools/ console needs to be updated to include the new whitelisted provider. I could not find a way to report this bug directly to the Search Console. Can someone point me in the right direction?

**Comment by powdercloud** [comment]
We have a test case for this:
https://validator.ampproject.org/#url=https%3A%2F%2Fraw.githubusercontent.com%2Fampproject%2Famphtml%2Fmaster%2Fvalidator%2Ftestdata%2Ffeature_tests%2Fregexps.html

So I am quite confident that at the moment, all current validator versions allow this typography.com font. This includes the validators we run in Google indexing and the AMP Cache.

I think the reason why you're seeing this error is that it's a stale error. It was probably generated with an older version of the validator. Once the page gets reprocessed, it should go away. Reprocessing time depends on the page, just like it does for anything in search console. Sorry for the lag.

But this particular error for the particular example is not something you should worry about. You may confirm that your page is alright by using validator.ampproject.org or any of the other choices at https://www.ampproject.org/docs/guides/validate.html. I'll take the liberty to close the bug but please feel free to reopen as you see fit. Thank you.

**Comment by powdercloud** [comment]
For later reference this was the Github issue when we added typography.com (not too long ago):
https://github.com/ampproject/amphtml/issues/3749
