### ISSUE TITLE
Add ViewportWidth/Height variables for AMP Analytics

### ISSUE THREAD

**Issue by j-e-shaw** [ampproject/amphtml#4635]
With more devices supporting split-screen (Android N provides it), the screen dimensions aren't as useful. Having the actual browser viewport dimensions available in analytics would better for viewability and verification purposes.

**Comment by rudygalfi** [comment]
Do `availableScreenHeight` and `availableScreenWidth` cover this request (https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/analytics-vars.md#device-and-browser)?

**Comment by j-e-shaw** [comment]
Aren't those just the size of the screen minus the toolbars?

If the browser is running split-screen on a mobile device, the screen dimensions shouldn't be changing but the viewport size of the browser would be smaller.

**Comment by dvoytenko** [comment]
Yes, viewport metrics should definitely be used for something like this. My quick search points to `VIEWPORT_HEIGHT` and `VIEWPORT_WIDTH` vars in https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#viewport_height

This is what you want, right?

**Comment by rudygalfi** [comment]
Ah, yes, somehow I missed those. Do the variables @dvoytenko mentioned work?

**Comment by j-e-shaw** [comment]
Yes, it looks like those should work. Are they currently available for analytics?

Thanks!

**Comment by dvoytenko** [comment]
@j-e-shaw Yes. As `${viewportHeight}` and `${viewportWidth}` vars.

**Comment by dvoytenko** [comment]
I'll close this at this time. But please re-open if needed.
