### ISSUE TITLE
Google AMP Cache 404 for images

### ISSUE THREAD

**Issue by Odoyle** [ampproject/amphtml#4645]
## Google AMP cache is not able to cache images from our content.

Visit https://cdn.ampproject.org/c/staging.laineygossip.com/Kristen-Stewart-says-relationship-with-Robert-Pattinson-made-into-product-wasnt-real-life-in-interview-with-T-Magazine-gushes-about-girlfriend-Alicia-Cargile/44681/amp

Expected: 
see the images

Actual
no images displayed - 404 in the console 

For example this returns a 404
https://cdn.ampproject.org/i/media.laineygossip.com.s3.amazonaws.com/thumbs/tmb_173x173_kstew-t-interview-17aug16.jpg

But the associated resource is online
http://media.laineygossip.com.s3.amazonaws.com/thumbs/tmb_173x173_kstew-t-interview-17aug16.jpg

## What browsers are affected?

All browsers

## Which AMP version is affected?
1471285991363

**Comment by ericlindley-g** [comment]
Thanks for reaching out, @Odoyle — I've escalated this for the Google AMP Cache team internally at b/31038413, and will update this bug with next steps

**Comment by ericlindley-g** [comment]
The team has discovered the issue: the images MIME type (JPEG) doesn't match the actual image content (PNG). I'll mark this issue as closed, but please reopen if you still see the issue after making the fix.
