### ISSUE TITLE
Move samples for extensions into their corresponding examples dir

### ISSUE THREAD

**Issue by jmadler** [ampproject/amphtml#465]

**Comment by cramforce** [comment]
We should really do this. It is getting crowded.

**Comment by bpaduch** [comment]
@jmadler - Is this still an issue?  All examples for components are in [Examples](https://github.com/ampproject/amphtml/tree/master/examples).  Are you suggesting moving each example into their own subdirectory?  So, the `brightcove.amp.html` example s/b in extensions/amp-brightcove?
