### ISSUE TITLE
Open P tag causes JS validator to fail and cache to pass.

### ISSUE THREAD

**Issue by dknecht** [ampproject/amphtml#4654]
This code fails JS validator and passes cache validator. Which is the correct behavior? 

```
<body>
<p>I am not closed!
<p>I am closed!</p>
<amp-sidebar id='sidebar' layout='nodisplay' side="right">
</amp-sidebar>
</body>
</html>
```

**Comment by dknecht** [comment]
and similarly...

This pass both of them. With the missing closing tag on <li> should it? 

```
<body>
<amp-sidebar id='sidebar' layout='nodisplay' side="right">
    <amp-accordion>
      <section>
        <h2>News</h2>
		<ul>
            <li><a href="http://example.com">Foo</a>
        </ul>
      </section>
    </amp-accordion>
</amp-sidebar>
</body>
```

**Comment by powdercloud** [comment]
I think the relevant snippet from https://www.w3.org/TR/html5/grouping-content.html#the-p-element is:

> A p element's end tag may be omitted if the p element is immediately followed by an address, article, aside, blockquote, div, dl, fieldset, footer, form, h1, h2, h3, h4, h5, h6, header, hgroup, hr, main, nav, ol, p, pre, section, table, or ul, element, or if there is no more content in the parent element and the parent element is not an a element.


And similar for `li`: https://www.w3.org/TR/html5/grouping-content.html#the-li-element
So I think the cache validator is correct and we may need to fix htmlparser.js to get the proper nesting for the first example (the amp-sidebar is a direct child of the body, but the parser thinks it's a child of the first p tag).
Thank you for the test case!

**Comment by Gregable** [comment]
This is fixed everywhere.
