### ISSUE TITLE
Browsi's platform & AMP

### ISSUE THREAD

**Issue by DavidBrowsi** [ampproject/amphtml#4660]
Hello,
Following this ticket: https://github.com/ampproject/amphtml/issues/4644
I'm contacting you on behalf of Browsi's team. we understand that we need to reach out the AMP team in order for our platform to be integrated in the AMP HTML project.
Can you please guide us through the approval process?

Thanks,
David

**Comment by rudygalfi** [comment]
New features go through the contribution process outlined here: https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#contributing-features

Things will start by posting an intent to implement of what functionality you would like to add to AMP.

Just one quick note having looked at your product briefly: AMP's format requires static declaration of ad positions, so it would not be possible to analyze the page on the fly to determine ad positions.

cc @jasti

**Comment by DavidBrowsi** [comment]
@rudygalfi @jasti 

Hello,
Its been a while since we contacted you.
Since then, we've changed our product significantly - our revised product now focuses on:

1. By analyzing the page while its loaded - we provide the publisher with optimal (and optional) positions, allowing the publisher to use with his current inventory.
2. The publisher will be in charge of handling the inventory (demand).
3. We will supply the publisher with analytical data and tools about the browsing session.
4. User experience: our product focuses on providing the publisher with fast/lazy loading - in order to improve the user experience.

Following the link you provided ( https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#contributing-features ) - I'm finding it difficult to understand under which category our product falls under.
We obviously don't fall into the 'fonts' category, so we can rule this one out. 
We will not be providing the ads, as the publisher will be responsible for their own demand - which makes the 'Ads' category obsolete.
Regarding the 'Embeds' category: we're not a unit added to the page (like a YouTube video, or a Twitter feed), but more of an engine that runs in the background of the mobile site and providing useful monetization/analytical information in real-time to the publisher while keeping the user experience optimal.

To the best of your knowledge, where do you imagine a product like Browsi best fits?
What should be out next steps in order to be AMP approved?

Thanks

**Comment by rudygalfi** [comment]
You're right that this doesn't seem to fit neatly into one of those categories. That's OK - much more complex and comprehensive integrations can be considered, but they just won't have the benefit of a well-worn path.

An integration would still stick to the [guidelines](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#contributing-features) you referenced, particularly starting with a detailed Intent to Implement describing what you want to change and how you propose to change it.

As I stated previously, a huge goal of AMP is performance and ensure that content (including ads) can be rendered with minimal latency. An on-the-fly approach to ad configuration seems like it could be challenging to accommodate, but we can certainly take a look once you've drafted an intent to implement.

**Comment by lannka** [comment]
@DavidBrowsi is your product more like the [amp-auto-ads](https://github.com/ampproject/amphtml/issues/6196) extension? It's still a work in progress, and it should be extensible to any 3rd parties. If that's something you are looking for, I suggest you have a conversation with @tlong2 .

**Comment by jasti** [comment]
@DavidBrowsi  Haven't heard back in a while. Closing, but please do discuss with @tlong2 if this is something you plan to pursue.
