### ISSUE TITLE
Defense in depth: ensure that templates do not generate `__amp_source_origin` to avoid CSRF

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#4661]
URLs are handled in templates outputs by `sanitizer.js` in `resolveUrlAttr`. This method need to assert that `__amp_source_origin` query parameter is not present since the template outputs cannot be run through the validator.

/cc @molnarg @Gregable

**Comment by mkhatib** [comment]
Should this throw errors or just strip the `__amp_source_origin`?
