### ISSUE TITLE
Come up with holiday freeze plan

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#4667]
How will the holidays affect release cycles / code reviews?

(Based on https://groups.google.com/d/msg/amphtml-discuss/xSpnp136aj4/jiF2OkciBwAJ)

**Comment by cramforce** [comment]
Very good question!

AMP ships every week and we only take short breaks. In particular we will not code freeze for the entire holiday season.

Most likely schedule is
Last prod release: Dec 15
First canary release: Jan 5.

**Comment by jasti** [comment]
@michaelkleber and @keithwrightbos, FYI from our conversation this morning.
@ampproject/a4a team FYI.

**Comment by tdrl** [comment]
So, to confirm, there will *not* be a code freeze around US Thanksgiving?  So you'll target a canary release and canary->prod promotion for Nov 24 (Thanksgiving itself)?

**Comment by cramforce** [comment]
We typically skip releases if they directly fall on a non-working day.
