### ISSUE TITLE
AMP Ads resize immediately

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#4672]
When the `embed-size` message is received, the `<amp-ad>` resizes [immediately](https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad/0.1/amp-ad-api-handler.js#L116) before ever calling `#attemptChangeSize`. Really, it should be updating the iframe's size (not the element's), calling `#attemptChangeSize` and waiting for that to change the element's size.

**Comment by lannka** [comment]
Good catch. Thanks!
