### ISSUE TITLE
Iframe's can fool isAdLike

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#4673]
`isAdLike` pulls the iframe's `width` and `height` attributes directly. But, if it's inside a wrapper element and uses percentage widths, they'll be like `100%`. That's not going to match any of our "ad like" sizes. We should instead get the bounding box of the iframe and doing the size comparisons with that.

```html
<!-- This fools isAdLike -->
<div width="300px" height="250px">
  <amp-ad layout="responsive" />
</div>
```

**Comment by jpettitt** [comment]
What's to stop people setting width to 301px or height to 251px?   This strikes me as a losing battle.

**Comment by jridgewell** [comment]
It's definitely a losing battle, but we're already doing it and can be a bit smarter about the detection without much work.

**Comment by dvoytenko** [comment]
The goal here is to make clear that the use of iframes for ads is not supported. Obviously it's easy to ignore this, but that'd be a conscious decision on the part of the editor.

**Comment by muxin** [comment]
The current logic to determine whether an iframe looks like an ad is kind of strange. I don't understand the logic that checks the size. Does it want to treat an iframe with some width-height ratio as an ad or an iframe with exact width value and height value as an ad. @cramforce

**Comment by jridgewell** [comment]
We don't care about the ratio, it's whether or not they are the same size as common ad formats.

**Comment by dvoytenko** [comment]
I believe the initial requirement from @cramforce was to look at the declared width/height. It was explicitly not to address hacking of an ad as an iframe, but to pick up the most obvious declarative mistakes and make it clear that we don't support such use cases. It's very unlikely that we can the full protection from this on runtime level - we just want to make it clear that it's not an intended use case.
