### ISSUE TITLE
Intent to implement: `amp-ad` type: Zucks

### ISSUE THREAD

**Issue by yang-wei** [ampproject/amphtml#4677]
Hi, we want to add our ad network into the supported ad network for amp-ad.
Our ad network: [Zucks, Inc.](http://zucks.co.jp/)

Our submitted CLA was voided for the reason `Please have an authorized executive sign this document.`

We would really appreciate if you can take a look at it :)

**Comment by dvoytenko** [comment]
@yang-wei Thanks! Looking forward to your pull request!

**Comment by yang-wei** [comment]
@dvoytenko 

Our corporate Contributor License Agreement was avoided =(
Can you take a look at it ?
Corporation Name: Zucks, Inc.

**Comment by dvoytenko** [comment]
What was the pull request #?

**Comment by yang-wei** [comment]
just sent them out https://github.com/ampproject/amphtml/pull/4681

**Comment by yang-wei** [comment]
We still have some review work for the pull request.

It would be really helpful if you can take a look at our CLA =)

**Comment by lannka** [comment]
@erwinmombay do you know the process of CLA signing for a corporation? I don't see Zucks, Inc is on the CLA list.

**Comment by dvoytenko** [comment]
I can confirm that "yang-wei" has signed the CLA - everything looks good there. However, I can't confirm it against the PR itself since it's already closed. Sometimes the robot is a bit slow and needs "I signed" comment to check again.

**Comment by yang-wei** [comment]
@lannka probably won't be on the list because our CLA was voided.

Also there is a field name "title" in the CLA form, what kind of information should be filled in. I wrote "Mr." though. but I don't think that make the application voided.

> I can confirm that "yang-wei" has signed the CLA

Thats my personal CLA. This time I am signing for my company `Zucks, Inc`

**Comment by adelinamart** [comment]
@yang-wei do we still need to keep this open? Thanks
