### ISSUE TITLE
Intent To Implement: AccessTrade for amp-ads

### ISSUE THREAD

**Issue by interspacejp** [ampproject/amphtml#4682]
Support for The Accesstrade ad-network to amp-ad elements.

AccessTrade will be submitting a PR via the interspacejp/amphtml fork and the accesstrade branch.

**Comment by rudygalfi** [comment]
cc @lannka

**Comment by jasti** [comment]
@interspacejp Thanks. Look forward to the PR.

**Comment by interspacejp** [comment]
Thanks!
