### ISSUE TITLE
When amp-ad is configured with layout=responsive, always center ad in iframe

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#4693]
When publishers use layout=responsive for amp-ad and the response is a fixed pixel creative, the creative ends up being left and top aligned. 
It should be vertically and horizontally centered regardless of the response.

You can see this in:
![screen shot 2016-08-24 at 4 47 06 pm](https://cloud.githubusercontent.com/assets/2366341/17947379/69f0ec10-6a1a-11e6-8b71-feb1fb6f6e93.png)

Live article : http://www.theatlantic.com/amp/article/497159/
Code snippet : http://output.jsbin.com/fehayafoso

## What browsers are affected?

I tested this in Safari on an iphone 6.

## Which AMP version is affected?

It was always this way.

**Comment by jasti** [comment]
@lannka thoughts?

**Comment by dvoytenko** [comment]
FWIW, this is what we do for embeds such as Twitter, so I don't see why we should not do it for ads as well.

**Comment by lannka** [comment]
I agree with @jasti that in this case align center will be a better UI treatment.

However, after taking a look at the creative, I noticed it's really out of AMP's control. The creative is in an nested iframe, and it should be the creative CSS to center align it.

Seems it's a doubleclick ad, do we let publisher configure alignment in DFP?

**Comment by jasti** [comment]
No, not really.
@mlb7687 for thoughts. Sounds like something that was served using Glade.

**Comment by mlb7687** [comment]
Looks like you get the same layout with both GPT and GPT Light. Seems like something that is fixable though. Since multi-size is not currently supported, we are still issuing the ad request with the defined size. So if we explicitly define the ad iframe size, we should be able to do the centering in doubleclick.js. Let me play around with it and see what I can come up with.

**Comment by jridgewell** [comment]
Should we close this issue?

**Comment by jasti** [comment]
@jridgewell  It sounds like we'll fix this along with https://github.com/ampproject/amphtml/issues/3176 which we are actively working on. @mlb7687 is looking into it.
So, if okay, would like to keep it open.

**Comment by mlb7687** [comment]
@jasti, this bug and #3176 are distinct issues fwiw. Getting around to looking at this closer now, but I'd expect a fix for this much sooner that multisize changes being in place.

**Comment by mlb7687** [comment]
PR for fix: https://github.com/ampproject/amphtml/pull/4735
If there are any objections to this approach, please let me know, happy to consider others.
Had to pass layout information into 3p frame somehow, so chose to add it onto window.context.

**Comment by omeryounus** [comment]
try to add the below in css.
      amp-ad{
                	direction: initial;
     }
