### ISSUE TITLE
Refactor amp-analytics transport to use promises and xhr-impl

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#4694]
Current setup construct their own `XMLHttpRequest` which AMP has a good wrapper implementation around it to support `fetch` and does some other stuff like (appending `__amp_source_origin` on CORS requests).

Current setup requires a sync fallback - so moving to xhr-impl (promise-based) would be a bit weird if other transports requests didn't move to promise-based as well.

``` javascript
export function sendRequest(win, request, transportOptions) {
  assertHttpsUrl(request);
  if (transportOptions['beacon'] &&
      Transport.sendRequestUsingBeacon(win, request)) {
    return;
  }
  if (transportOptions['xhrpost'] &&
      Transport.sendRequestUsingXhr(win, request)) {
    return;
  }
  if (transportOptions['image']) {
    Transport.sendRequestUsingImage(win, request);
    return;
  }
  user().warn(TAG_, 'Failed to send request', request, transportOptions);
}
```

**Comment by dvoytenko** [comment]
I think this was done by @btownsend . Maybe he still remembers the reason...

**Comment by avimehta** [comment]
I am fine with making this change. We might have just missed it when it was initially created. 

(aside: Is the __amp_source_origin really needed? I don't know how analytics vendors other then GA implement their systems and an unknown parameter might break stuff.)

**Comment by rudygalfi** [comment]
To @avimehta's comment, this wouldn't involve appending `__amp_source_origin` to requests unconditionally, would it? amp-analytics requests should have what the publisher's markup specifies -- nothing more, nothing less.

**Comment by mkhatib** [comment]
Currently all requests through the `xhr-impl` will have `__amp_source_origin` appended to them. If we anticipate adding an extra parameter might break things then maybe that's a good enough reason for sticking with analytics own XHR or introducing an optional parameter for `xhr-impl` to not append that parameter. (I'd prefer the later to centralize all xhr made by AMP but I'd understand if analytics is a special case).

**Comment by rudygalfi** [comment]
I think amp-analytics might be a special case in that the whole point of the request is the conveyance of precisely defined data rather than a request for the purposes of getting a response or changing server state.

**Comment by adelinamart** [comment]
@rudygalfi do we still need this? Thanks

**Comment by rudygalfi** [comment]
@aghassemi Could you help answer here? I'm not sure if this is still needed.

cc @cramforce since some of this seems related to a security review that was happening with forms and I'm not sure whether amp-analytics needed to be updated.

**Comment by cramforce** [comment]
I might be missing what is going on here, but I think this can just be closed.

Especially if no analytics vendor is asking for this param.

**Comment by aghassemi** [comment]
Reading through the comments, seems like this is a refactoring nice-to-have to remove code duplication. To be honest, this is one of those things that will just sit here until a better reason to do it comes up (e.g. the way analytics is doing xhr breaks in a browser update) or @jridgewell finds out about it :) 

I don't know what the best way to handle these code-clean up tasks is. Keeping them in Bug Backlog keeps the queues noisy. Closing them is essentially ignoring the need for clean code. I don't know, maybe a "Code Cleanup" milestone makes sense? Scheduling a week of "Cleanup Your Code" once in a while similar to "FixIt" might be good too. @adelinamart @mrjoro thoughts?

**Comment by cramforce** [comment]
Note, that the code in question here is super tiny since the analytics use case is so simple. Sometimes duplication makes a system simpler.

**Comment by adelinamart** [comment]
I think if we just create another label or milestone will not change very much the faith of this bug, which is will still be hanging somewhere with no action. 
This sounds to be more of a feature request rather than a bug, please correct if I'm wrong. 
The way you have to think about it is that if it's bringing any value to our product or users/developers, then added to the New FR milestone so it can be later prioritized against other new FRs. Otherwise, if it's just code refactoring, consider it adding it as part of a bigger refactoring project because solving them individually can bring more technical debt as mentioned above. 
We can talk more offline about this. Hope this helps.

**Comment by dvoytenko** [comment]
I'd vote to close this bug.

**Comment by jridgewell** [comment]
> I'd vote to close this bug.

👍

**Comment by aghassemi** [comment]
Closing this particular issue is fine, but we do have similar refactoring issues (e.g. https://github.com/ampproject/amphtml/issues/5294) which are in the same boat as this one. Sp let's deal with them individually based on criteria @adelinamart mentioned above and either close or treat them as FRs.
