### ISSUE TITLE
The test helper createIframePromise might build a same element twice

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#4698]
`createIframePromise` installs runtime service to the iframe window. Its `addElement` method calls `element.build()` and `element.layoutCallback()` for the element. As a result, resource manager will build the element once and `element.build()` will build another time.

Is that intentional?

**Comment by dvoytenko** [comment]
So, this is just the test code, right? If yes - I can see how it could be possible, but that's definitely avoidable and should be fixed. ElementProto and Resource objects maintain the full state for build/layout/etc.

**Comment by adelinamart** [comment]
@lannka do we still need this?

**Comment by lannka** [comment]
this is a bug. but all new tests should now use `describes`
