### ISSUE TITLE
There's chance 3p iframe amp-ad might create multiple child iframes

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#4699]
The current `layoutCallback` code is buggy:

```
  layoutCallback() {
    if (!this.iframe_) {
      user().assert(!this.isInFixedContainer_,
          '<amp-ad> is not allowed to be placed in elements with ' +
          'position:fixed: %s', this.element);
      incrementLoadingAds(this.win);
      return getAdCid(this).then(cid => {
        if (cid) {
          this.element.setAttribute('ampcid', cid);
        }
        this.iframe_ = getIframe(this.element.ownerDocument.defaultView,
            this.element);
        this.apiHandler_ = new AmpAdApiHandler(
            this, this.element, this.boundNoContentHandler_);
        return this.apiHandler_.startUp(this.iframe_, true);
      });
    }
    return loadPromise(this.iframe_);
  }
```

Because `this.iframe_` is assigned in a callback, checking the existence of `this.iframe_` will not prevent a 2nd iframe get created if a 2nd call of `layoutCallback` is called before the callback returns.

A fix will be to check `this.iframePromise_` instead.

On the other side, it's debatable that if we should simply throw if `layoutCallback` get called twice. But at this moment, we cannot do that because in the test we call it twice: #4698

**Comment by dvoytenko** [comment]
Hmm. Layout callback should never be called twice for an iframe in the normal runtime mode. How is it called twice now?

**Comment by lannka** [comment]
Right now the 2nd call has only been seen in test.

If `layoutCalllback` is guaranteed to be called only once, probably we can just throw on a 2nd call (the current code silently add a 2nd iframe is dangerous). And then we definitely need to fix the test first.

**Comment by dvoytenko** [comment]
This is where duplicative nature of `Resource` and `ElementProto` hurts us a bit. Ideally we'd switch test to call layout via `Resource.startLayout` which provides all of these protections and manages state fully.

**Comment by lannka** [comment]
Regardless to the test, the code here in the `layoutCallback` isn't doing things as expected.
I believe the `if (this.iframe_)` check is to prevent adding multiple child iframes, however the code doesn't achieve the purpose.

We should definitely fix that first. 

Regarding to whether we should throw on a 2nd call, probably not for now (i changed my mind). We can make it a no-op.

**Comment by cramforce** [comment]
Yes, please fix!

**Comment by zhouyx** [comment]
I am thinking about this. Have one question that's blocking me. 
`layoutCallback()` needs to return a promise. what do we return on the 2nd call?  
we return `loadPromise(this.iframe_)` now, but that could end up causing the 2nd `layoutCallback()` to be resolved earlier than the first one. (this could be a problem in tests, as we proceed testing after `layoutCallback`, but the real layoutCallback(first call) may not be resolved at that time).
