### ISSUE TITLE
Amp-analytics trigger timer with visibilitySpec

### ISSUE THREAD

**Issue by pdufour** [ampproject/amphtml#4708]
It'd be nice if you could trigger a timer with a visibility spec, so for instance if I wanted to track engagement within a certain element. Right now AFAIK you can do either one separately but not both together.

**Comment by rudygalfi** [comment]
Can you give a more specific example. I can imagine this being useful in theory but having trouble imagining the specific scenario where a visibility-based timer would be used. For example, what kinds of variables would be collected in concert with the timer?

As far as implementation, seems like defining a new trigger (visibilityTimer) and allowing for (requiring) both corresponding specs to be used would enable this.

**Comment by pdufour** [comment]
FWIW this example is not 'amp compliant' but waiting for https://github.com/ampproject/amphtml/issues/655 to be completed so we implemented some extra JS to do infinite scroll on AMP pages.

So the example is:
- Trigger timer on first article view to track engagement with simplereach
-  User scrolls to second article, trigger new engagement timer and cancel old one

**Comment by zhouyx** [comment]
Should be able to use `${totalVisibleTime}` to track engagement with certain element. https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#visibility
