### ISSUE TITLE
Investigate using `document-click` in the main amp document

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#4712]
`document-click` handles local navigation (i.e. anchors) without changing the Url fragment. It is currently used in iframes, let's also use it in the main document since we use Url fragment for other purposes and we don't want anchor links meant for location navigation to change it.

Related to https://github.com/ampproject/amphtml/issues/4184

**Comment by ericlindley-g** [comment]
@aghassemi I've put this in "Next", but please update the milestone when you have a sense of when work will start—thanks!

**Comment by cramforce** [comment]
I think we should definitely still update the URL fragment. People need to be able to share their current state. It is worth considering to use `replaceState` instead of assigning `location.hash`, though.

In any case it makes sense for these navigations to remove the sidebar-push from the history stack.

**Comment by aghassemi** [comment]
We can support ephemeral history pushes (https://github.com/ampproject/amphtml/issues/4713) independent of this to fix the sidebar issue. My worry with allowing local navigation to change fragment was possibility of overriding things like share tracking, amp-experiment overrides and other cases that we rely on the fragment for.

**Comment by dvoytenko** [comment]
I think share tracking is fine. If authors do local navigation to fragments - they have to content with the fact that they may break their sharetracking fragments. In other words - this should be up to the author.

**Comment by cramforce** [comment]
Yes, users win. Users need fragment links. All other use cases have to live with this not the other way around.

**Comment by aghassemi** [comment]
SGTM, I will close this then since https://github.com/ampproject/amphtml/issues/4713 implies we need some parts of `document-click` code to implement ephemeral history push.
