### ISSUE TITLE
Support ephemeral history push

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#4713]
Support pushing ephemeral routes to the history stack.
ephemeral routes are poped automatically when either navigation happens (including local anchor navigation using the fragment) or a new route is pushed to the stack.

possible API:
`history.push(...,{ephemeral: true})`
`history.push(...,{popOnNavigation: true})`
`history.pushEphemeral(...)`

Related to #4184, #4712

**Comment by ericlindley-g** [comment]
@aghassemi I've put this in "Next", but please update the milestone when you have a sense of when work will start—thanks!

**Comment by aghassemi** [comment]
handled by https://github.com/ampproject/amphtml/issues/9128
