### ISSUE TITLE
Image resizing in lightbox on click

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#4716]
*Originally reported as https://github.com/ampproject/amp-by-example/issues/340*

**Expected behavior:**

- As the user, I should be able to click the image, trigger the lightbox to make the image bigger, and the image should load once and keep the same proportions in the lightbox.

**Actual behavior:**

- As the user, I click the image, trigger the lightbox to make the image bigger, and the image that loads is vertically condensed, then the image reloads and adjusts itself to the correct proportions.
++ I'm not sure if this is an actual component issue or implementation on Amp by example issue....++

Link: https://ampbyexample.com/components/amp-image-lightbox/

FYI @sebastianbenz @aghassemi @ericlindley-g

**Comment by ericlindley-g** [comment]
@aghassemi Slotting into "Next" — might be nice to land a fix with the new lightbox release?

**Comment by Siton-Systems** [comment]
What about this issue?...its problem to use the lightbox for clients with this bug (its very outstanding on desktop).

![image](https://cloud.githubusercontent.com/assets/16711871/19554507/9d37d920-96c1-11e6-998d-608d3ea58cf3.png)

**Comment by aghassemi** [comment]
@Siton-Systems Fix is in review (https://github.com/ampproject/amphtml/pull/5717)
