### ISSUE TITLE
https://js.ad-stir.com/js/adstir_async.js 404

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#4718]
@tarofurukawa hello, we're seeing in our local testing that https://js.ad-stir.com/js/adstir_async.js results in a 404

cc @muxin

**Comment by erwinmombay** [comment]
@rudygalfi any way we can reach out to them?

**Comment by ericlindley-g** [comment]
Adding @tarofurukawa to the thread, who I believe initially implemented the component
Assigning to @jasti for followup

**Comment by tarofurukawa** [comment]
Sorry for my late response.
I was fixed the issue.

Then we'll investigate why the script was down, and check our monitoring system asap.

**Comment by erwinmombay** [comment]
@tarofurukawa thank you. issue should be resolved.
