### ISSUE TITLE
amp-form validation with required inputs

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#4723]
While reviewing a sample using a form, I noticed that the validation does not block the submit.
To reproduce this, go to the [sample](https://ampbyexample.com/components/amp-form/) and use the first form. The inputs are required, and when you click submit leaving the inputs blank, the validation popups quickly and then disappear showing the page pointed by the Submit button. Same behaviour happens in the second form of the sample, in this case, even if a XHR is specified, that is not called.

I was expecting the Submit button to be blocked if the inputs are not valid, I noticed that in the [code](https://github.com/ampproject/amphtml/blob/master/examples/forms.amp.html) "novalidate" is always added in order to allow AMP to create a "report", how does this work?

## What browsers are affected?

Chrome, Safari

## Which AMP version is affected?

1471559432224

@mkhatib @rowan-m @rudygalfi

**Comment by mkhatib** [comment]
@kul3r4 thanks for filing. I noticed this the other day. This is because we have two separate experiments to enable the flow of forms. Can you please add another Enable Experiment for the `form-submit` experiment name?

**Comment by kul3r4** [comment]
@mkhatib 
Hi,
I enabled also the form-submit experiment and tried again the sample [amp-form](https://ampbyexample.com/components/amp-form/). Still, it allows to submit the form without entering the email field correctly. Have you tried it?

**Comment by mkhatib** [comment]
I am unable to reproduce this, tried this on Chrome and Safari on Mac OS X and both block submissions when both `amp-form` and `form-submit` experiments are toggled on.

Do you see any errors in console? 

<img width="439" alt="screen shot 2016-08-30 at 4 41 25 pm" src="https://cloud.githubusercontent.com/assets/2647/18110989/cee2ae96-6ed0-11e6-8925-9efefcdba078.png">
<img width="495" alt="screen shot 2016-08-30 at 4 41 09 pm" src="https://cloud.githubusercontent.com/assets/2647/18110990/cee7b864-6ed0-11e6-9538-a4c00f56a203.png">

**Comment by kul3r4** [comment]
I got it working thanks!

**Comment by mkhatib** [comment]
Thanks for closing @kul3r4 let me know if there was an issue with forms other than mentioned earlier.
