### ISSUE TITLE
Validation fails on Google CDN, but passes on AMP page

### ISSUE THREAD

**Issue by AileenCGN** [ampproject/amphtml#4726]
When checking for validation errors on an "AMPified" post, using `#development=1` and/or https://validator.ampproject.org/, the validation passes. But when doing the same with a page, which is served on the Google AMP CDN, the validation fails and shows two errors (sometimes even more):
1. `The tag 'script' is disallowed except in specific forms.`, just between the boilerplate and the mandatory AMP script:
   ![image](https://cloud.githubusercontent.com/assets/8037602/18004184/83743f42-6b92-11e6-8707-fe5ee3e1dc67.png)
2. Naturally, because of error # 1 the second error is: `The mandatory tag 'amphtml engine v0.js script' is missing or incorrect.`

Maybe it is not bug or it doesn't matter, but I couldn't find anything, that would explain this behaviour.
## Ways to reproduce

Open AMP pages in browser with `#development=1` parameter:
1. Example pages: [Blog served with Ghost](https://ungeek.fr/retour-experience-openstack/amp/#development=1), [Hello World example on ambyexample](http://ampbyexample.com/g?value=Hello%20World#development=1), [Mashable Post](http://mashable.com/2016/08/25/facebook-whatsapp-opt-out.amp#development=1), [Techcrunch Post](https://techcrunch.com/2016/08/25/whatsapp-to-share-user-data-with-facebook-for-ad-targeting-heres-how-to-opt-out/amp/#development=1) and check the console in DevTools. They should all pass with max. warnings.
2. Open the same pages on `https://cdn.ampproject.org/c/(s/)`:  [Blog served with Ghost](https://cdn.ampproject.org/c/s/ungeek.fr/retour-experience-openstack/amp/#development=1), [Hello World example on ambyexample](https://cdn.ampproject.org/c/s/ampbyexample.com/g?value=Hello%20World#development=1), [Mashable Post](https://cdn.ampproject.org/c/mashable.com/2016/08/25/facebook-whatsapp-opt-out.amp#development=1), [Techcrunch Post](https://cdn.ampproject.org/c/s/techcrunch.com/2016/08/25/whatsapp-to-share-user-data-with-facebook-for-ad-targeting-heres-how-to-opt-out/amp/#development=1) and check the console in DevTools. They all error. Some have more errors than others, but all share the same error as mentioned above.
## What browsers are affected?

All on OS X 10.11.6
- Chrome 52.0.2743.116
- Firefox 47.0
- Safari
## Which AMP version is affected?
- Version 1471559432224

**Comment by dknecht** [comment]
Maybe we should update Js  validator to understand when a request is served from a cache.

**Comment by powdercloud** [comment]
@dknecht yes, I think we may need to make it so that when the validator is invoked on an AMP CDN URL, it either emits an error or it fetches the original source. If it's the error, it could indicate to do the original source. I think the Chrome extension may already have such a logic built into it, so we may want to be consistent with that.

**Comment by Gregable** [comment]
The chrome extension treats pages from cdn.ampproject.org by simply showing a link icon pointing at the rel=amphtml page, which is the original page.

Personally I'm fine with `development=1` showing the validator errors. There are pros and cons of course, though they are all minor. For example, I don't want someone copy/pasting the output of cdn.ampproject.org and then being confused when it doesn't work. The page is actually invalid.

In the long run, I think we can make all cache pages valid, once `stale-white-revalidate` is live everywhere. My recommendation is to mark this WAI.

**Comment by Gregable** [comment]
The main place that folks run into this was the chrome extension. That has been modified to always consider cdn URLs valid, so as to minimize confusion while browsing. If folks are explicitly choosing to validate the doc on the CDN, I think that hiding the errors is a bad idea. The cache output is not intended to be valid.

Closing.
