### ISSUE TITLE
Tracking interactions with amp-carousel

### ISSUE THREAD

**Issue by senthilp** [ampproject/amphtml#4727]
Using `amp-analytics` is there a way to track if an user interacted with `amp-carousel`? Like if they swiped on it to see the hidden items. We tried the [scroll trigger](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md#scroll-trigger-on-scroll) `horizontalBoundaries`, but the `scrollSpec` doesn't take a selector and only works on the overall page level. Will this be an enhancement to amp-analytics or is it possible to achieve it with any of the current analytic triggers?

**Comment by rudygalfi** [comment]
Duping over to #4292. See https://github.com/ampproject/amphtml/issues/4292#issuecomment-237094904 specifically, but, yes, specific support could be added. PRs would be welcome.

cc @avimehta
