### ISSUE TITLE
MediaSource APIs supported in amp-video?

### ISSUE THREAD

**Issue by johnluther** [ampproject/amphtml#473]
The amp-video.md doc states that "The amp-video component is only to be used for direct HTML5 video file embeds." Does this mean that the MediaSource extensions won't be supported in AMP?

**Comment by cramforce** [comment]
@jmadler 

I'm not sure actually, but that should be supportable.

**Comment by johnluther** [comment]
OK, fingers crossed. W/o MediaSource we won't be able to support adaptive video streaming, which would be Very Bad. :-\

**Comment by rudygalfi** [comment]
@mrjoro I think this needs review for whether it truly is a good first issue.

**Comment by adelinamart** [comment]
Assigning to Joey to review this first.

**Comment by aghassemi** [comment]
Closing this in favor of https://github.com/ampproject/amphtml/issues/7744 to support adaptive streaming. Just exposing MediaSource API would require page authors to still write JS which is not supported in AMP. https://github.com/ampproject/amphtml/issues/7744 should tackle this with a holistic approach.
