### ISSUE TITLE
Header accuracy on sizes.txt

### ISSUE THREAD

**Issue by jmadler** [ampproject/amphtml#4739]
Are the headers accurate in sizes.txt?  "min" seems like it might actually be "cur".

**Comment by erwinmombay** [comment]
hmm seems to be right, for example v0.js

| max     |         min        |        gzip      |   file |
|---|---|---|---|
| 758.3 kB   |   139.75 kB   |    44.09 kB   |   v0.js / amp.js |

could you point out what looks wrong?

**Comment by jridgewell** [comment]
@erwinmombay: We fixed this, right?

**Comment by erwinmombay** [comment]
@jridgewell yeah should be fixed
