### ISSUE TITLE
SwipeXRecognizer can leak `touchmove` events

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#4742]
Gestures stop propagation of events when a recognizer matches a gesture. For elements using `SwipeXRecognizer` this cancellation of `touchmove` events is crucial to ensure viewer does not see them to do a document swipe. `SwipeXRecognizer` can (rarely) leak `touchmove` events however with very fast swipes. This is most evident in carousel in iOS.

To reproduce:
- Visit http://goo.gl/FbR7pq in Safari and Chrome.
- In Safary, try swiping horizontally 10-20 times, you should be able to get he leaked count to at least a few.
- In Chrome, try the same, should be much harder but still you may be able to see one or two leaks.

The big issue is when _two_ `touchmove` events leak within a single swipe, normally the delta between them is big enough for the viewer to consider that a document swipe.

Can we always cancel these events until there is a recognizer match and replay a copy of them if no recognizer matched?

(FYI, not high-priority since as a work-around slidescroll carousel is canceling all touchmove events itself instead of using SwipeXRecognizer with a no-op callback)

CC/ @sriramkrish85

**Comment by dvoytenko** [comment]
I'll close this. This functionality is intentionally built around `preventDefault`. It was wrong for me to prescribe to disable `preventDefault` before.
