### ISSUE TITLE
Feature request: hide browser navigation chrome in reading view

### ISSUE THREAD

**Issue by nickpascucci** [ampproject/amphtml#475]
The current AMP demo (g.co/ampdemo) displays a blue header with a back button which takes up a large amount of screen real estate on mobile devices in addition to the browser chrome. When in reading mode, the browser chrome should be hidden when the user scrolls to recover as many pixels for content as possible while leaving the responsibility for navigation to the HTML header.

## Chrome (iPhone 5S)
![96d64abc-14c6-49b8-a435-779d1b56f269](https://cloud.githubusercontent.com/assets/636796/10342530/7cd3ccde-6ce7-11e5-895b-ec1c50f5c9e5.PNG)

## Safari (iPhone 5S)
![a66539a0-ea18-4c1c-bda4-a10aab78645c](https://cloud.githubusercontent.com/assets/636796/10342533/7e3221b6-6ce7-11e5-87e2-6a7f59edb6cc.PNG)

**Comment by NataliaLKB** [comment]
:+1:

**Comment by cramforce** [comment]
Yeah, don't mention this to @dvoytenko :)

It is so hard, but we'll do it. Not really an AMP thing, but rather up to Google Search.

**Comment by dvoytenko** [comment]
This is really up to the Viewer to do, but we will definitely enable Viewers to do so with some ease.

**Comment by cramforce** [comment]
This must be fixed by the Google search team. I believe they are on it.
