### ISSUE TITLE
Make some analytics call conditional

### ISSUE THREAD

**Issue by kushal** [ampproject/amphtml#4752]
It'd be useful to have a way to make analytics calls conditional on a value returned by amp:access, so that certain calls are only made for certain users.

Although analytics will wait for the result of an access call before firing if you include any variables from access, it does so even if the value is undefined. Would you ever consider making a given analytics call never fire if a particular amp:access returned undefined for a given variable?

i.e. `requests: { foo: 'http://foo.com?x=AUTHDATA(donuts)' }` would only make call foo if donuts was true or false but not if it was undefined.

**Comment by dvoytenko** [comment]
/cc @avimehta 

@kushal Do you have some specific event in mind? E.g. is this an Access specific event such as `access-authorization-received` or a generic event? The thing is that there are very many parameters potentially included in the analytics request and disabling it just b/c of one of them would be unclear.

@avimehta Do we have anything like this or what do you think about this format:

```
"triggers": {
  "accessAuthorizationReceived": {
    "enabled": "authdata(fieldA)",
    "on": "access-authorization-received",
    "request": "event"
  }
}
```

I.e. we'd have a `enabled` field that would turn on/off triggers based on var resolution?

**Comment by kushal** [comment]
@dvoytenko Yeah, I definitely see how this could lead to confusing behavior. In my particular case this is less about triggers and more about actually disabling a particular analytics provider based on the response to an amp:access call. Having a per-trigger enabled field would totally work, or even a top-level enabled field (or maybe even support an amp-access attribute on amp analytics blocks?)

**Comment by dvoytenko** [comment]
@avimehta What do you think for a two-level `enabled` attribute for triggers and analytics element in general?

**Comment by avimehta** [comment]
I am open to `enabled` attribute. 

When should the evaluation of attribute happen when it is at top level? I assume when the trigger fires and not when the amp-analytics tag is constructed. 

If the attribute is used at both trigger and tag level, should the trigger level override the tag level or should they both be evaluated?

What exactly does evaluation mean? Is checking for truthy/falsey value enough or do we need more fine-grained controls like `${variable} == 'abcd'`? I think we should start simple and then add functionality but open to suggestions.

/cc @rudygalfi

**Comment by dvoytenko** [comment]
I'd say:

1. Evaluated per request
2. Both trigger and tag should be evaluated if specified
3. Evaluation can be restricted to a simple empty test. E.g. `${variable1}${variable2}` - if empty, enabled = false.

**Comment by dvoytenko** [comment]
@rudygalfi let's schedule this?

**Comment by zikas** [comment]
@dvoytenko, @avimehta  I'm working on this issue, so would like to sum up the desired behavior so everybody's on the same page.

`"enabled"` attribute is introduced on tag and trigger level that allows a user to conditionally skip a call
  * if omitted call is enabled
  * if present then corresponding expression needs to be evaluated. Now it's enough to have the simplest expression support: _if value resolves to an empty string we skip a call_. For example 
    ``` 
    "triggers": {
      "myTrigger": {
        "enabled": "${condition}",
        "on": "visible",
        "request": "pageview",
      } 
    } 
    ``` 
    In this case if `"${condition}"` resolves to `""` trigger is not invoked.
  * If enabled is declared on both trigger and tag levels both will be applied `(enabled_on_tag_level && enabled_on_trigger_level)`

Does this sound good to you?

**Comment by dvoytenko** [comment]
@zikas Yes. This sounds good to me. I'd even apply the same `enabled` property/logic for top-level as well. E.g.

```
<amp-analytics id="analytics1">
<script type="application/json">
{
  "enabled": "${condition1}"
  "triggers": {
    "myTrigger": {
      "enabled": "${condition2}",
      "on": "visible",
      "request": "pageview",
    } 
  }
}
</script>
</amp-analytics>
```

Thus, the actual trigger enabled will be an AND of condition1 and condition2.

**Comment by zikas** [comment]
Great, thank you!

**Comment by dvoytenko** [comment]
Sorry, I'm confusing everyone. The work has already been started in #9061.

**Comment by dzuendorf** [comment]
Great feature I've been looking for for days, but it's not documented.
