### ISSUE TITLE
slidescroll and scollable-carousel should not cancel `touchmove` of vertical swipes

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#4754]
Related to https://github.com/ampproject/amphtml/pull/4743

Currently `slidescroll` and `scollable-carousel` stop propagation of all `touchmove` events so that viewer does not see them to scroll the page. Ideally however, we only cancel `touchmove` events from horizontal swipes. When we implement this, it is important to make sure we don't leak  `touchmove` events however. See #4742 for why leaking would be bad.

**Comment by adelinamart** [comment]
@ericlindley-g @aghassemi this might be good to have an update. Thanks

**Comment by aghassemi** [comment]
updated priority, still good todo for perf
