### ISSUE TITLE
Lightbox example broken

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#478]
The example for the amp-lightbox on GitHub fails amp validation. Moreover, it doesn't seem to actually work when pasted into the sample HTML found elsewhere in the docs.

https://github.com/ampproject/amphtml/blob/master/extensions/amp-lightbox/amp-lightbox.md

**Comment by powdercloud** [comment]
I was going to say this should mention that including the javascript is necessary in addition to copy/pasting, but while trying to find the incantation noticed that the script url provided here for another example isn't working (404):
https://github.com/ampproject/amphtml/tree/master/extensions

**Comment by cramforce** [comment]
@powdercloud Fixed that one.

**Comment by cramforce** [comment]
And a few others.

**Comment by dvoytenko** [comment]
Pull request for validation is here: https://github.com/ampproject/amphtml/pull/489

Not sure about "doesn't actually work" - tried it in everything.amp.html - looks fine.

**Comment by wnda** [comment]
When I try to include the `amp-lightbox` [as described here](https://github.com/ampproject/amphtml/extensions/amp-lightbox/amp-lightbox.md) I get validation errors regarding the `on=` attribute on a `button`

The `everything.amp.html` example does not demonstrate the `amp-lightbox` using a `button` element as the trigger, but rather an `amp-img`. Is this a mistake in the docs to say that a `button` is allowed?

**Comment by dvoytenko** [comment]
"on" on a button should be absolutely allowed. cc @Gregable

**Comment by wnda** [comment]
Seems that the `close` attribute also seems to throw the validator off, and the lightbox is still closed by tapping anywhere on the screen&mdash;regardless of the presence of a `close` attributed element.

Apart from that it works fine.

**Comment by dvoytenko** [comment]
I think we need to add `autoclose` attribute in the lightbox to turn off default behavior. As for `close` button - it's not implemented yet (or technically it is since clicking on anything would close lightbox :)), I have created #552 - I think `on` actions would work better.

**Comment by cramforce** [comment]
Is this fixed?

**Comment by dvoytenko** [comment]
Closing. Validator will error out for a little longer.
