### ISSUE TITLE
Custom href URI

### ISSUE THREAD

**Issue by echer** [ampproject/amphtml#4784]
I have the following code to send message to number in whatsapp, how to migrate this to amp? is possible?

`<a href="intent://send/5517xxxxxxxxx#Intent;scheme=smsto;package=com.whatsapp;action=android.intent.action.SENDTO;end">Send Whatsapp message</a>`

I have the following message in chrome console:

`Invalid URL protocol 'intent:' for attribute 'href' in tag 'a'`

**Comment by echer** [comment]
The code work to open whatsapp correctly, but i have this error in amp validation.

**Comment by jpettitt** [comment]
Given the large number of [URI schemes](http://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml) (and that's just the ones that are registered, a list that doesn't include `intent:`) perhaps a blacklist model would be more appropriate that the current whitelist model?

**Comment by cramforce** [comment]
@Gregable can give some context. A blacklist would be nice, but due to unexpected browser URI parsing it can be insecure.

Would still be nice if we could revisit.

**Comment by Gregable** [comment]
The issue with a blacklist model is that we can't know the behavior of every useragent past, present, and future creating a security issue if we miss something. The obvious no-no is, for example `javascript:`, but you also need to blacklist `script:`. You'd be forgiven if you forgot `vbscript:`. Auditing all browsers for these non-standard protocols isn't feasible, so we stick with a whitelist.

I'm fine to add `intent:` to the whitelist if that's something we want.

**Comment by cramforce** [comment]
`intent:` is fine. It should be secure as only a small number of apps opt into receiving intents from the web. CC @ericlindley-g because this type of platform specific thing might be tough in AMP today (as one would really need a custom protocol in iOS instead).

**Comment by adelinamart** [comment]
Is this still an open discussion? thanks

**Comment by jridgewell** [comment]
/to @Gregable https://github.com/ampproject/amphtml/issues/4784#issuecomment-245461660

**Comment by Gregable** [comment]
This has been fixed for some time.
