### ISSUE TITLE
Set maximum length for CID

### ISSUE THREAD

**Issue by georgecrawford** [ampproject/amphtml#4788]
I would like to propose that the AMP spec agrees a maximum length for a cookie value set automatically using a CID. There are occasions where AMP will generate a cookie value for us, and we use that cookie in perpetuity as a device identifier for analytics. 

For this reason, the length of the cookie value has quite an impact downstream - I have a database engineer wanting to know how long it’s likely to get, and severe performance implications if we make the field definition unnecessarily long. 

Is there any way that a contract could be agreed to define the maximum length of this string (ideally for all AMP viewers)?

**Comment by cramforce** [comment]
SGTM. Could you send a PR?

**Comment by cramforce** [comment]
Is this still needed?
