### ISSUE TITLE
Amp Carousel Content Sizing Issues

### ISSUE THREAD

**Issue by NayiLadki** [ampproject/amphtml#4790]
I am trying to use amp-carousel within which I need to divide each slide in two parts using col-md-6 and align images in one and content in other part. However, I am getting issue with amp-carousel's height and width settings as for different resolution of device width it is hiding a lot of content. In desktop mode, it's showing a lot of extra space. Also I wish to edit  i-amp-sizer, but not getting the right way. Apart from this, I want to remove -amp-layout-size-defined class which is occurring automatically.

**Comment by dvoytenko** [comment]
/cc @ericlindley-g 

@NayiLadki Do you think you could send a sample page?

**Comment by rudygalfi** [comment]
Closing for lack of sample pages
