### ISSUE TITLE
amp-youtube Validation Error

### ISSUE THREAD

**Issue by A-Au** [ampproject/amphtml#4791]
I tried to use the `<amp-youtube>` tag with the `src` attribute instead of `data-videoid` and received the validation error:
> The attribute 'data-videoid' in tag 'amp-youtube' is set to the invalid value 'https://www.youtube.com/embed/8ePDE4Q2_g8 

I only tried this because it said it would be fine in [here](https://www.ampproject.org/docs/reference/validation_errors.html). So, I think you will need to update that page.

**Comment by ericlindley-g** [comment]
@pbakaus How is this [.md file](https://github.com/ampproject/docs/blob/e20b653c7f608975be7e15bdba838261508f4f7e/content/docs/reference/validation_errors.md) generated? It's an easy change to jump in and erase the youtube examples in this context—as I believe `src` is not supported as an attribute itself or as a value for data-videoid (@aghassemi to correct if there have been any changes I'm not aware of as a result of the discussion in https://github.com/ampproject/amphtml/issues/4367)—but I want to make sure it won't get overwritten somehow.

**Comment by aghassemi** [comment]
yes, `src` is not supported yet. It was wrongly passing validation until fixed by https://github.com/ampproject/amphtml/pull/4381. I am also not sure how the `validation_errors.md` is generated either. Might be manual.

**Comment by pbakaus** [comment]
This doc isn't generated, but lives here: https://github.com/ampproject/docs/blob/master/content/docs/reference/validation_errors.md

Feel free to create a PR against it.

**Comment by jridgewell** [comment]
Maybe @bpaduch would like to take it on?

**Comment by aghassemi** [comment]
This is fixed by https://github.com/ampproject/docs/pull/192 already.
