### ISSUE TITLE
amp-analytics JS fatal loop on visibility triggers.

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#4792]
We have been seeing page lockups with the browser window non-responsive and the associated Chrome Helper at 100% cpu since we enabled visibility triggers in `amp-analytics`.  When this happens the only way out is to kill the window from Activity Monitor.  (Chrome 53 desktop, all emulation modes).  We've since disabled this in prod on our sites.

What we think triggers this is an ad unit that doesn't fill, we're still trying to confirm a solidly repeatable test case as it seems to take up to ~30 seconds before it happens.  The dev tools window shows no network activity and attempting to break the JS loop from devtools causes a window crash.  The browser window shows a "Waiting for securepubads.doublclick.net" tag bottom left.

Switching to incognito (no chrome extensions enabled) doesn't change the outcome.

Here is the amp analytics / google analytics trigger value we're using (one per ad unit)

```
    "amp-ad1": {
      "on": "visible",
      "request": "event",
      "visibilitySpec": {
        "selector": "#_rmAd1",
        "visiblePercentageMin": 50,
        "continuousTimeMin": 1000
      },
      "vars": {
        "eventLabel": "doubleclick-300x250",
        "eventCategory": "ad",
        "eventAction": "visible",
        "eventValue": 1
      }
    },
```

**Comment by jridgewell** [comment]
Do you have a link to a page which causes the lockup?

**Comment by avimehta** [comment]
@jpettitt What does `#_rmAd1` point to? Is it an `amp-ad` element? Trying to repro locally but a url that shows this will be nice.

**Comment by jpettitt** [comment]
I'm pushing to public facing server, will have a demo for you shortly.   // yes the `#_rmAd1 `points to the` amp-ad` tag

**Comment by jpettitt** [comment]
This one fails https://20160831t111043-dot-relay-beta.appspot.com/amp/www.poynter.org/2016/this-man-edits-three-vermont-papers-and-some-glossy-magazines-from-philadelphia/428160/?_rmdebug=2

This one doesn't 
http://cdn.relaymedia.com/amp/www.poynter.org/2016/this-man-edits-three-vermont-papers-and-some-glossy-magazines-from-philadelphia/428160/

**Comment by jridgewell** [comment]
I'm not able to reproduce. Is it still happening?

**Comment by jpettitt** [comment]
Yes - Chrome 53.0.2785.80 beta, incognito mode all plugins disabled.  Solid fail for me.

**Comment by avimehta** [comment]
I can repro it on my desktop now. Investigating. Thanks for the URL.

**Comment by avimehta** [comment]
@dvoytenko I think there might be a couple of issues at work here. First, there is an infinte loop here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/visibility-impl.js#L364. 

In visibility-impl.js I am doing something like following:

```
// function
  // Check if there are elements that have not loaded
    // if there are, add them to an array.
  // If the array is non-empty, wait for first element to load and then run the function again.
```
The above flow goes in a loop when an element says that it is **loaded but is not loaded**.

Now the second issue (maybe?):

I have following code in visibility-impl.js:
```
if (res.isLayoutPending()) {
  loadedPromises.push(res.loaded());
}
```

When I wrote this, I assumed that if `isLayoutPending()` returns true, `res.loaded()` will return a promise that is pending(in reality, it is returning a resolved promise and thus resulting in an infinite loop). Is this usage wrong? The documentation for `res.loaded()` says:

>    Returns a promise that is resolved when this resource is laid out for the first time and the resource was loaded.

**Comment by dvoytenko** [comment]
@avimehta 

> When I wrote this, I assumed that if isLayoutPending() returns true, res.loaded() will return a promise that is pending(in reality, it is returning a resolved promise and thus resulting in an infinite loop).

From what I can tell, this assumption is a valid one. Although, I'd prefer a direct check here and not a derived state. E.g. a state can be reset, e.g. to try to reload an element. That being said, I'd like to know exactly which element is behaving this way here.

The one thing I don't quite understand - why do you need an element to be loaded? Is that really necessary for the purposes of the analytics package?

**Comment by dvoytenko** [comment]
@avimehta The one thing I also want to clarify here: `res.loaded()` definitely looks correct to me - it returns what it describes - a promise that's resolved as soon as the element has been loaded. I think it's the `isLayoutPending` that's likely does things incorrectly.

**Comment by avimehta** [comment]
thanks for the comments @dvoytenko. Sent out a PR to fix this.

**Comment by erwinmombay** [comment]
qq should we get this in asap or can this go through normal process?

cc @dvoytenko @cramforce

**Comment by avimehta** [comment]
Info for informed decision:

I _think_ this has been broken for quite some time and was never noticed. This occurs whenever an amp-ad is unloaded and the triggers associated with it have not triggered.
The experience when it is broken is _very very_ bad because it hangs up the phone or desktop. (I have reproduced it on both my android chrome and chrome desktop.)

**Comment by jridgewell** [comment]
I'm for cutting another canary tomorrow.

**Comment by jpettitt** [comment]
What's the status on this?

**Comment by erwinmombay** [comment]
tomorrow is canary day, i just want to make sure we're don't need to expedite this into full production.

ping @cramforce

**Comment by cramforce** [comment]
We should definitely get this in for this canary.

I'm inclined to say we should change our prod schedule a bit next week (also due to unrelated reasons) and aim at shipping canary to prod on Monday.

**Comment by avimehta** [comment]
Cool. This PR is merged so good to go from my side.

**Comment by erwinmombay** [comment]
@cramforce OK, we'll shoot for canary Thursday (or even end of working day today if possible), 1% Friday for this weeks canary.

cc @lannka who is on duty
