### ISSUE TITLE
Storage service is installed by amp-analytics but used in amp-user-notification and amp-app-banner

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#4794]
Storage service is an element-level service that is owned and installed by `amp-analytics` but it is used by `amp-user-notification` and `amp-app-banner` (it is not even used by `amp-analytics` as far as I can tell)

`amp-user-notification` documents that it needs  `amp-analytics` as well but requiring `amp-analytics` for `amp-app-banner` doesn't make much sense.

We should either make storage a window-level service in core, or to support better code splitting, have non-core services have their own js files similar to extensions and have extensions declare their dependencies on services in a way that runtime can load and install the needed non-core services only once for all the extensions that need them.

**Comment by dvoytenko** [comment]
I think both `amp-user-notification` and `amp-banner` explicitly require `amp-analytics` dependency. It's indeed a bit ugly, but reduces number of cascades and simplifies our module loading system. FWIW, I think we could easily put storage service into core - it's rather small. Some other similar services might be harder to do so.
