### ISSUE TITLE
Supporting key-value pairs for amp-analytics to work with Google Analytics

### ISSUE THREAD

**Issue by jlaurito** [ampproject/amphtml#4798]
(note: while this sounds similar to https://github.com/ampproject/amphtml/issues/1701 it is a different issue)

`amp-experiments` supports human-readable [experiment and variable names](https://github.com/ampproject/amphtml/blob/master/examples/experiment.amp.html#L49). Unfortunately, most A/B testing frameworks, including Google Experiments/Google Analytics, don't allow for human readable experiment & variable names.

Specifically, Google Experiments requires a 0-indexed integer as an experiment id (`xvar`). So to get `amp-experiments` to pass events to Google Experiments, each variant needs to be named a 0-indexed integer instead of human-readable names. So instead of 

`"variants": {
            "yellow": 50,
            "green": 50
}`

I need

`"variants": {
            "0": 50,
            "1": 50
}`

If `amp-analytics` supported some mapping, ie `{"yellow":0,"green":0}` in `extraUrlParams`, we could retain human-readability in experiments and pass machine-readable params to Google Experiments.

**Comment by lannka** [comment]
This is a tricky problem. 

Say if a page wants to incorporate 2 analytics platforms that have contradictory naming constraints: 
A needs a number but B needs alphabetic string. Obviously no matter how you name your variants, one of them will fail.

@rudygalfi do you have any idea? We have to introduce a mapping, but I don't know where.

**Comment by rudygalfi** [comment]
Since we haven't acted on this in awhile, I'm going to close.

Please re-open if anyone is interested to continue discuss adding this.
