### ISSUE TITLE
CSS Selector restrictions: why?

### ISSUE THREAD

**Issue by bryanburgers** [ampproject/amphtml#480]
Why are the CSS Selector restrictions so tight? I was under the understanding that CSS Selector Performance is largely irrelevant.

If there is a reason to restrict the CSS Selectors so tightly, can it be documented somewhere?

http://calendar.perfplanet.com/2011/css-selector-performance-has-changed-for-the-better/
http://benfrain.com/css-performance-revisited-selectors-bloat-expensive-styles/
http://www.stevesouders.com/blog/2009/03/10/performance-impact-of-css-selectors/

**Comment by cramforce** [comment]
We might relax this a bit. Need a good corpus of docs to see. It is definitely is not irrelevant. Style recalc is O(number of DOM nodes * number of rules * their complexity)

**Comment by cramforce** [comment]
Removed most restrictions
