### ISSUE TITLE
trackId don't allow a comma

### ISSUE THREAD

**Issue by ireinhart** [ampproject/amphtml#4801]
We like to use webtrekk with 2 trackId's, but it seams, that the "," gets wrong encoded.

`<script async custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script><script async src="https://cdn.ampproject.org/v0.js"></script>`

and

`    <amp-analytics type="webtrekk">
        <script type="application/json">
            {
                "requests": {
                    "parameterPrefix": "?p=431,${contentId},1,${screenWidth}x${screenHeight},${screenColorDepth},1,${timestamp},${documentReferrer},${viewportWidth}x${viewportHeight},0&tz=${timezone}&eid=${clientId(amp-wt3-eid)}&la=${browserLanguage}"
                },
                "vars": {
                    "trackDomain": "q3.webtrekk.net",
                    "trackId": "886765640341113,511604217612660"
                }
                }
            }
        </script>
    </amp-analytics>`

produce a 404 at the webtrekk server.

The produced call is:
`https://q3.webtrekk.net/886765640341113%2C511604217612660/...`

but it must be:
`https://q3.webtrekk.net/886765640341113,511604217612660/...`

**Comment by aghassemi** [comment]
to @avimehta for triage. Percent encoding `,` as a url part seems reasonable. Not sure why q3.webtrekk.net does not handle both `%2C` and `,`

**Comment by rudygalfi** [comment]
cc @StephanGuenther

**Comment by avimehta** [comment]
@ireinhart Can you try specifying the trackId as follows:

```
"vars": {
  "trackDomain": "q3.webtrekk.net",
  "trackId": ["886765640341113" , "511604217612660"]
}
```

**Comment by StephanGuenther** [comment]
@ireinhart please use the following example:

```javascript
"vars": {
  "trackDomain": "q3.webtrekk.net",
  "trackId": ["886765640341113" , "511604217612660"]
}
```

I have change the examples in the dokumentation.

**Comment by ireinhart** [comment]
thx, the id's as array work 👍
