### ISSUE TITLE
A4A failing to turn off visibility:hidden for Doubleclick ads in some cases

### ISSUE THREAD

**Issue by tdrl** [ampproject/amphtml#4802]
According to a bug report by @jasti :

> 1. Something is odd. The A4A creative delivers fine in an non-amp page, but only rarely delivers when served from an AMP page. The creative does return according to Chrome developer tools, I just don't see it on the browser.

Repro case: http://jsbin.com/vocogumoqi/1/edit?html,output

Appears to be some variant of visibility:hidden being set and never unset.  This is serving in current AMP canary, at least.

**Comment by keithwrightbos** [comment]
Issue caused by underlying creative never sending render-start post message which never triggers visibility hidden to be removed.

**Comment by tdrl** [comment]
Verified that issue is in the way creative templates are being rendered, specifically for Glade tags.  That makes it a Google-specific backend issue.  Closing this GH issue and forwarding to Google to handle.
