### ISSUE TITLE
Document supported MIME types in AMP caches

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#4806]
Currently developers have issues where the wrong MIME type is specified, leading to errors fetching fonts (and subsequent delays in rendering)

Opening this issue to document accepted types—I think the right place for this is a list in `amp-font.md`, but it may be the cache docs instead.

**Comment by sriramkrish85** [comment]
@ericlindley-g - do you have a specific example?

**Comment by ericlindley-g** [comment]
Don't have a concrete example, but I got feedback from the cache team that this was happening, so I have a [PR pending feedback](https://github.com/ericlindley-g/amphtml/blob/master/cache/GUIDELINES.md) waiting in my personal repo for the docs.

No need for other folks to do anything at the moment, so I took you off the assignee list, but let me know if there's something you wanted/needed to do.

**Comment by sriramkrish85** [comment]
may be we should point to a browser support chart rather than making up our own list. I dont think we do anything special. This way we would not have to maintain this. I am sure we will be out of sync soon.

**Comment by ericlindley-g** [comment]
I should have been clearer—this is for supported MIME types in AMP caches

**Comment by mike-marcacci** [comment]
It would be quite nice to have clear guidance on this; for example, it would be nice to use a custom suffix (perhaps `text/html+amp`) but it's unclear to me without testing whether or not this is acceptable.

**Comment by ericlindley-g** [comment]
Looks like we checked in the documentation, but didn't update this thread—sorry about that, @mike-marcacci 

You can find the documented MIME types for fonts and images [here](https://github.com/ampproject/amphtml/blob/master/spec/amp-cache-guidelines.md#guidelines-accepted-mime-types)

**Comment by mike-marcacci** [comment]
Ah, quite useful! Thanks.
