### ISSUE TITLE
<amp-carousel> images stretched in slidescroll implementation on some pages

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#4811]
To repro:
Turn on slidescroll experiment and canary for pages served from cdn

Navigate to [sample page](https://cdn.ampproject.org/c/www.geektime.com/2016/08/30/alphabet-debuts-crowdsource-to-help-with-google-translate-and-maps/amp/)

Observe:
Images are stretched in the slide container

P1: We'll want to fix this before launching slidescroll implementation

cc @sriramkrish85

**Comment by jpettitt** [comment]
Also if you use slides that are` layout=responsive` to `100vw` it doesn't resize cleanly on orientation or screen size change like the current version - see example here 

https://cdn.ampproject.org/c/s/kansascity.relaymedia.com/amp/news/politics-government/article73988477.html

**Comment by sriramkrish85** [comment]
cc @dvoytenko , @zhouyx  - can you take a look at this.

**Comment by zhouyx** [comment]
I am looking into this. Looks to me the reason is `layout=responsive` resize element's height to the ration of `width` and `height`. In the example above it tries to expand the height of the image but fails because `amp-carousel` limits the height of the element. This makes image looks like it's stretched.

**Comment by zhouyx** [comment]
From our doc:
>>>
responsive: The width and height attributes must be present and are used to determine the aspect ratio of the component. The component is sized to the width of its container element while maintaining the height based on the aspect ratio.
