### ISSUE TITLE
Assorted problems with makeBodyVisible

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#4822]
1. `makeBodyVisible` should only do any work only once. This can be done by setting a property on `document` instance, e.g. `document.__AMP_VISIBLE` or such.
2. Performance reporting should be done when the actual visibility is set, e.g. in `set()` method of `makeBodyVisible` AFTER all other updates are done.
3. `makeBodyVisible` should assume that performance service might not have installed yet. Two ways to accomplish it are (1) by try/catch; (2) by propagating `dueToError` argument to `makeBodyVisible` method and completely avoiding reporting in case of error - it's not meaningful. Alternatively, there could be an argument `reportPerformance` and it will be passed only in one most expected case. See Appendix A. We could also try to use `waitForExtensions` argument for this, but then we need to check if it's used anywhere else and possibly rename it better.

Appendix A: The only "normal" call to makeBodyVisible that we need to report is amp.js with `waitForExtensions = true`:
```
      maybeValidate(self);
      makeBodyVisible(self.document, /* waitForExtensions */ true);
      installCacheServiceWorker(self);
```

**Comment by erwinmombay** [comment]
@dvoytenko with appendix a, do you mean the only time we need to do the perf reporting is when we wait for extensions?

**Comment by dvoytenko** [comment]
@erwinmombay Yes: that's the case right now. But would be worth checking of course.
