### ISSUE TITLE
Amp experiment throws on a zero %

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#4824]
I just tried to turn off an experiment while I was debugging something by setting the % to zero and got this rather contradictory error

`Uncaught Error: failed to build: amp-experiment#6: Invalid percentage expViewability:0. Has to be in range of (0,100)​​​ _reported_`

```
<amp-experiment>
  <script type="application/json">
    {
      "aExperiment": {
        "sticky":false,
        "variants":{
          "expViewability":0,
          "expStd":100
        }
     }
   }
 </script>
</amp-experiment>
```

**Comment by rudygalfi** [comment]
/ to @lannka

**Comment by lannka** [comment]
@jpettitt this is as intended. the error message is explaining: we don't allow variant with 0 traffic.

In your case, you should just remove the experiment. There's no point to keep it there to waste CPU cycles and bandwidth to load and run the code.

Please let me know if you have objection.

**Comment by jpettitt** [comment]
The it should say `Has to be in range of (1,100)​​​` not `Has to be in range of (0,100)​​​`

**Comment by jridgewell** [comment]
> not Has to be in range of (0,100)​​​

That's [math notation](http://stackoverflow.com/a/37171635/323767). We could be more explicit with "greater than 0 and less than 100".

**Comment by rudygalfi** [comment]
+1. Let's do it more explicitly.

**Comment by cpapazian** [comment]
looks like the error message was updated in #4871, but docs still:
>A name-to-percentage map where percentage is a float number in range (0, 100) that indicates the amount of traffic will be allocated to the variant. 

https://www.ampproject.org/docs/reference/components/amp-experiment

**Comment by jpettitt** [comment]
The notation (a, b) implies a < x < b see [intervals](https://en.wikipedia.org/wiki/Interval_(mathematics)#Including_or_excluding_endpoints).  Admittedly (0,100) is confusing at first (it got me, I filed the prior issue) but it is the correct notation (ISO 31-11)
