### ISSUE TITLE
Ads should still load if getting CID fails

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#4836]
We have had cases where a bug in the viewer causes the promise to get the CID fail/never resolve, which in turn is causing Ads to fail to load.

We should ensure Ads can still load if getting CID fails within `x` milliseconds to protect against these situations where a viewer bug breaks ads.

**Comment by cramforce** [comment]
Lets actually make this more general. The `baseCid` method in `viewer-impl.js` should be wrapped in a timeout promise. I think 3 seconds is reasonable. We need to make sure to throw a good error if this fails. The only real reason why a timeout might be hit is a major GC or localStorage stalling.

If this is too spammy we should increase the timeout to something like 10s and instead wrap `getAdCid` in a shorter timeout (like 1s).

**Comment by cramforce** [comment]
Thinking about it, lets do the second suggestion. This change is important for robustness against broken viewers.

**Comment by dvoytenko** [comment]
One quick nuance: sometimes it takes a bit to establish the connection with the viewer period. Currently we give viewer 20 seconds to establish the comms. So we need to keep this in mind if we want to require a lower timeout for CID. Or, we can stagger them.

**Comment by dvoytenko** [comment]
Sorry, by "stagger" I meant sequence them.

**Comment by cramforce** [comment]
Yeah, so lets go with 2 timeouts. One short one for ads (because their getting the CID is purely optional) and a long one for getting errors reported that point to problems with a specific viewer.

**Comment by cramforce** [comment]
Grabbing the issue for myself :)

**Comment by ericlindley-g** [comment]
Assuming this goes in "Current", but please correct/update as needed—thanks!
