### ISSUE TITLE
window.context.noContentAvailable no longer sets AMP-AD to display None

### ISSUE THREAD

**Issue by antnativo** [ampproject/amphtml#4841]
@cramforce @lannka @jridgewell I was once able to hide an AMP-AD if there was not content for the ad by using **window.context.noContentAvailable()**. However, I am not unable to collapse the ads using this function. What has changed and what is available that provides the same functionality without the use of a fallback tag.

below used to work: 
`        if (typeof resp.placements == "undefined" || !(resp.placements instanceof Array) || resp.placements.length == 0 ) {
            (this.ampMode && typeof window.context.noContentAvailable != "undefined") ? window.context.noContentAvailable() : null;
            return; // if the response doesn't have placements, there is nothing to be done as this is not a valid publication section.
        }`

**Comment by cramforce** [comment]
This is only expected to work if the ad is not currently being displayed. Did you test with an invisible ad?

**Comment by antnativo** [comment]
@cramforce 
Really? Cause in the ads.example.html, it was working for us and it was working on our customer sites. We didn't have to set the node to be invisible. Once our script was loaded and executed we retrieved ads from our server. Once we get the ads, if the length was zero, then we could use the  window.context.noContentAvailable() to set the display to none

**Comment by antnativo** [comment]
It was working on my local branch of AMP. Then I pulled latest from your master branch and now it doesnt work

**Comment by cramforce** [comment]
AMP does not allow resizing elements that are currently visible, because that would make the page jump around in front of the user which we do not want.

**Comment by antnativo** [comment]
@cramforce I used it based on the previous issue I presented to you: https://github.com/ampproject/amphtml/issues/4185

**Comment by cramforce** [comment]
In practice if an an is not in the initial viewport (e.g. at the bottom of the page), this should work just fine.

I realize this is a trade off, but users really hate those spontaenous resizes of the page.

**Comment by antnativo** [comment]
So If we place an AMP-AD, which has a specific size. And our script loads and tries to get ADS. If there is no ad available, we can't collapse or display none the ad?

**Comment by cramforce** [comment]
You can, but not if the ad slot is currently visible by the user. This has
not changed.

**Comment by antnativo** [comment]
huh. Because I watched the Placement of the example in my viewport show there area of the ad and then collapse

**Comment by cramforce** [comment]
Please validate that things are working as expected for ads that are not visible, but otherwise this is definitely the desired behavior.
