### ISSUE TITLE
Disallow some old SVG 1.1 elements that have been deprecated in SVG2

### ISSUE THREAD

**Issue by erikdahlstrom** [ampproject/amphtml#485]
The AMP docs (https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#svg documentation) says that it allows the deprecated  "glyph", "glyphRef", "tref", "hkern", "vkern" elements from SVG 1.1. I'd suggest not allowing these elements.

**Comment by jarek-foksa** [comment]
Yeah, that list doesn't make much sense. E.g. what's the point of including `<filter>` when there are no filter primitives listed. Below is a list that I created based on the current state of SVG 2 and HTML 5 specs and Chrome's deprecation plans.

```js
export const ALLOWED_SVG_ELEMENTS = [
  // Basic
  "path",
  "circle",
  "ellipse",
  "line",
  "rect",
  "polygon",
  "polyline",
  "image",
  "text",

  // Painting
  "solidColor",
  "linearGradient",
  "radialGradient",
  "pattern",
  "mesh",
  "meshRow",
  "meshPatch",
  "hatch",
  "hatchPath",
  "stop",

  // Filters
  "filter",
  "feBlend",
  "feColorMatrix",
  "feComponentTransfer",
  "feComposite",
  "feConvolveMatrix",
  "feDiffuseLighting",
  "feDisplacementMap",
  "feDistantLight",
  "feFlood",
  "feFuncA",
  "feFuncB",
  "feFuncG",
  "feFuncR",
  "feGaussianBlur",
  "feImage",
  "feMerge",
  "feMergeNode",
  "feMorphology",
  "feOffset",
  "fePointLight",
  "feSpecularLighting",
  "feSpotLight",
  "feTile",
  "feTurbulence",

  // Metadata
  "title",
  "desc",
  "metadata",

  // Other
  "svg",
  "defs",
  "g",
  "a",
  "symbol",
  "marker",
  "switch",
  "use",
  "view",
  "tspan",
  "textPath",
  "clipPath",
  "mask",
  "style",
];

export const FORBIDDEN_SVG_ELEMENTS = [
  // SVG Fonts - deprecated in SVG 2
  "font",
  "font-face",
  "font-face-format",
  "font-face-name",
  "font-face-src",
  "font-face-uri",
  "altGlyph",
  "altGlyphDef",
  "altGlyphItem",
  "glyph",
  "glyphRef",
  "missing-glyph",
  "hkern",
  "vkern",
  // SVG Animations - deprecated by Chrome, likely to be removed from SVG 2
  "set",
  "animate",
  "animateColor",
  "animateMotion",
  "animateTransform",
  "mpath",
  // Elements deprecated by HTML 5 - https://html.spec.whatwg.org/multipage/embedded-content.html#svg-0
  "cursor",
  "tref",
  // Elements deprecated by corresponding CSS properties in SVG 2
  "color-profile"
  // Potential trouble makers
  "foreignObject",
  "script"
];
```

**Comment by daniellmb** [comment]
:+1: for allowing ellipse

**Comment by bpaduch** [comment]
Will investigate.

**Comment by bpaduch** [comment]
@Gregable - Can you shed some light on this?

**Comment by Gregable** [comment]
@dvoytenko for decisions on what we want to allow or disallow.

**Comment by dvoytenko** [comment]
@Gregable but which of these we do not allow yet?

**Comment by Gregable** [comment]
@dvoytenko this issue is about *dis*allowing some of these.

**Comment by dvoytenko** [comment]
To confirm, @Gregable, do we indeed allow everything in the `ALLOWED_SVG_ELEMENTS`?

**Comment by Gregable** [comment]
You are correct. We do not currently validate:

- solidColor
- mesh
- meshRow
- meshPatch
- hatch
- hatchPath
- metadata
- switch
- style (tracked in #3578)
- Any of the filters, ie: starts with `fe`, however, we intend to whitelist the ones mentioned in #7392 

Other than the style special case, we should add all of these.

Still, unsure what to do about removing tags.

**Comment by jarek-foksa** [comment]
I would suggest asking SVG WG members whether those new elements will actually end up in  the final spec, recently there were some signal that this might be not the case http://tavmjong.free.fr/svg2_status.html

**Comment by dvoytenko** [comment]
Cool. Let's track style and filters separately. 

Let's postpone mesh and hatch - I don't believe they are supported anywhere.

`solidcolor` is indeed defined is lowercase (although all examples are in camelcase). Let's support. https://www.w3.org/TR/SVG2/pservers.html#SolidcolorElement

Let's support `metadata`: https://www.w3.org/TR/2016/CR-SVG2-20160915/struct.html#MetadataElement

Let's support `switch`: https://www.w3.org/TR/2016/CR-SVG2-20160915/struct.html#SwitchElement

Feel free to break into multiple issues.

**Comment by Gregable** [comment]
> `solidcolor` is indeed defined is lowercase

I'm unsure about SVG, but HTML is case-insensitive when it comes to tag names, thus the validator is as well.

**Comment by dvoytenko** [comment]
@Gregable Since SVG is XML it, in theory, is case-sensitive. We are obviously totally fine if we do our checks in a case-insensitive way since it's very unlikely that the same name would be reused in different case.

**Comment by honeybadgerdontcare** [comment]
`metadata`, `solidcolor` and `switch` are added in #7590

**Comment by honeybadgerdontcare** [comment]
Please open a new issue for any other ones (mesh, hash, etc).
