### ISSUE TITLE
Carousel can't be displayed, the style is broken on mobile and safari developer tool

### ISSUE THREAD

**Issue by pengyiwang** [ampproject/amphtml#4859]
## How do we reproduce the issue?

https://www.google.com.hk/amp/s/www.peachdish.com/menus/V7LsTygAAAqbo1pI/eggplant-caponata-with-toasted-ciabatta-arugula--parmesan%3fsource=amp
1. Go to chrome developer tools, then access the link, there is a carousel, but it can't be displayed because `<img>` element isn't generated under `<amp-img>`
2. Go to safari developer tools, then access the link, the style is broken, but I can see `<img>`
3. Access the link on your mobile, same result with safari.
## What browsers are affected?

safari on Mac, all browsers on mobile
## Which AMP version is affected?

The version is 1472690078859

**Comment by ericlindley-g** [comment]
I can't reproduce exactly this (no issues on Safari Desktop, Chrome iOS or Android), but am seeing strange behavior that might be related, on Mac Chrome Desktop. 

In the attached GIF, see that the carousel works on first load, then, after testing it out, I navigate forward in history (to the cdn-hosted version of the same page, which also has a working carousel), then I scroll up, then down, then navigate backward in the history, to the original page. There's a long pause in rendering. When the page finally renders, I scroll up to the carousel, and all of the captions are layered over one another, without an image or interactivity.

@pengyiwang — is this similar to what you're seeing?

![carousel-issue-2](https://cloud.githubusercontent.com/assets/16807766/18356076/35c6c748-75a0-11e6-953d-dbdf8586b866.gif)


cc/ @aghassemi, @muxin, (and @sriramkrish85 as FYI), who have been working on the carousel recently

**Comment by aghassemi** [comment]
I can reproduce this, investigating.

**Comment by pengyiwang** [comment]
Hi , @ericlindley-g , the screenshot on my device is attached, @aghassemi Thank you!
iphone5+chrome
![img_1807](https://cloud.githubusercontent.com/assets/13607061/18373485/1e3c11dc-7677-11e6-8986-e2bf5c332484.jpg)
mac book pro + safari
<img width="632" alt="eggplant_caponata_with_toasted_ciabatta__arugula___parmesan_ _airdrop" src="https://cloud.githubusercontent.com/assets/13607061/18373453/b4307544-7676-11e6-85ca-51e315b4b70c.png">

**Comment by pengyiwang** [comment]
Hi, @ericlindley-g @aghassemi , when can we expect this issue is fixed. 
I found there are some changes on the page, but the style is still messed up. It's really bad experience for our customers.
Besides, why only this page is displayed as amp page, actually we have a lot, but I only submit this page on google webmaster, I can see other page on webmaster, but they won't be displayed on search result.
If I remove the carousel, will it fix the issue? The localhost test page is different with production page, it's hard for us to figure out how to fix it, we need deploy it, then wait to see how it works.

Thank you!

<img width="250" src="https://cloud.githubusercontent.com/assets/13607061/18940411/85146f26-863a-11e6-8e82-9cdeb9ea2f16.jpg">

**Comment by ericlindley-g** [comment]
@aghassemi Did you learn anything about this issue? FYI @sriramkrish85 @cramforce 

I'm also escalating this internally at b/31813710 to rule out viewer issues

**Comment by sriramkrish85** [comment]
looking at what might have caused this (looks the same with and without `amp-slidescroll`)

**Comment by sriramkrish85** [comment]
```html
<amp-carousel height="667" layout="responsive" type="slides" width="1000" ></amp-carousel>
```
Looks like the height is not defined (plus a few layout issues in the html) should have caused this. 
The carousel remains almost hidden.

**Comment by sriramkrish85** [comment]
@pengyiwang please give a height to the `amp-carousel`

**Comment by pengyiwang** [comment]
@sriramkrish85 where should I put a height? it's already there: height="667", actually it's a copy of sample here: https://ampbyexample.com/samples_templates/recipe/preview/ ,there is no issues when I test it on chrome developer tool.

**Comment by pengyiwang** [comment]
![eggplant_caponata_with_toasted_ciabatta__arugula___parmesan](https://cloud.githubusercontent.com/assets/13607061/18942212/cf33d39e-8649-11e6-9a8e-b3d40855b5bc.png)

**Comment by sriramkrish85** [comment]
<img width="1192" alt="screen shot 2016-09-28 at 10 42 04 pm" src="https://cloud.githubusercontent.com/assets/1037311/18942307/e399e468-85cc-11e6-8476-8840831caf50.png">

**Comment by sriramkrish85** [comment]
@pengyiwang we will debug and update the bug.

**Comment by pengyiwang** [comment]
@sriramkrish85 thank you! It seems <img> element isn't generated, but if I don't add #development=1, it works.  Does carousel affect the whole style?
![_2016-09-29_ 1_40_00__2_](https://cloud.githubusercontent.com/assets/13607061/18942362/10002692-864b-11e6-895d-d767b89e0a30.png)

**Comment by pengyiwang** [comment]
@sriramkrish85 I mean it's totally different when you see this page on chrome developer tool and mobile production.
<img width="250" src="https://cloud.githubusercontent.com/assets/13607061/18940411/85146f26-863a-11e6-8e82-9cdeb9ea2f16.jpg">

**Comment by sriramkrish85** [comment]
yes - i believe the source of the problem is the same.

**Comment by sriramkrish85** [comment]
looks like the element is not being laid-out for some reason from 

https://www.google.com.hk/amp/s/www.peachdish.com/menus/V7LsTygAAAqbo1pI/eggplant-caponata-with-toasted-ciabatta-arugula--parmesan%3fsource=amp

but everything looks fine from 

https://cdn.ampproject.org/v/s/www.peachdish.com/menus/V7LsTygAAAqbo1pI/eggplant-caponata-with-toasted-ciabatta-arugula--parmesan?source=amp&amp_js_v=5#origin=https%3A%2F%2Fwww.google.com.hk&exp=a4a%3A0&channelid=0&cid=1&dialog=0&prerenderSize=1&visibilityState=hidden&paddingTop=54&history=1&p2r=0&horizontalScrolling=0&csi=0&referrer&storage=1&viewerUrl=https%3A%2F%2Fwww.google.com.hk%2Famp%2Fs%2Fwww.peachdish.com%2Fmenus%2FV7LsTygAAAqbo1pI%2Feggplant-caponata-with-toasted-ciabatta-arugula--parmesan%253fsource%3Damp

**Comment by sriramkrish85** [comment]
CC @dvoytenko

**Comment by sriramkrish85** [comment]
@pengyiwang - this breaks because of `display: flex` on the body (which is not supported by AMP) could you try removing it and may be set it on a container where it is required?

**Comment by pengyiwang** [comment]
@sriramkrish85 Awesome! it works now!
