### ISSUE TITLE
Allow h-entry as well as/instead of Schema.org CreativeWork

### ISSUE THREAD

**Issue by adactio** [ampproject/amphtml#486]
The h-entry microformat covers all the same use cases as schema.org/CreativeWork and is already in place on many sites. I think it would ease adoption to allow these classes to be used instead of (or as well as) the microdata metadata.

It should be fairly straightforward to map h-entry class names to CreativeWork item properties. I'm happy to help out with that mapping (and I'm sure many others in the microformats/indieweb community would be happy to help out too).

Cheers,

Jeremy

**Comment by aaronpk** [comment]
I submitted a pull request to add h-entry as an example: https://github.com/ampproject/amphtml/pull/499

**Comment by veganstraightedge** [comment]
:+1:

**Comment by cramforce** [comment]
As discussed in #499 we will only have a single metadata example with "commonly used metadata" whatever that is.
