### ISSUE TITLE
"Login flow" section does not exist in amp-access docs

### ISSUE THREAD

**Issue by trodrigues** [ampproject/amphtml#4860]
In the amp-access spec, under the ["Login Page"](https://github.com/ampproject/amphtml/blob/master/extensions/amp-access/amp-access.md#login-page) section, the following sentence can be found:

> See the “Login Flow” section for more details.

However this section doesn't seem to exist.

Is this a section that was forgotten? Or is the name that should be referred here wrong?

**Comment by ericlindley-g** [comment]
cc/ @ashwinlimaye @dvoytenko
