### ISSUE TITLE
Meeting notes for 2016-08-29

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#4861]
@cramforce
- Back from 5 weeks leave.
- jsconf iceland presentation on 3rd party javascript

@lannka
- Found viewport bugs
- 2 more ad networks on board: pubmine & accesstrade
- Fixed a gulp watcher bug for 3p
- 1st refactor PR for 3p ad network impl code
- Worked with @muxin, brought some changes to render-start API

@muxin
- Scroll sync meeting with @mkhatib
- Finished work on random generation of share tracking fragment
- Next work is to replace fragment to url

@aghassemi
- Basic feature sets for lightbox 2.0 submitted
- Fix ios bug around carousel and viewer
- First PR for video manager and common video API
- Provides muted autoplay for amp-video in supported browsers

@yuxuan
- Add race between no-content and render-start
- Object.freeze() issue in tests
- Youtube and brightcove api tests

@mkhatib
- Forms + security work and research
- Performance and animation research with @muxin
- scroll sync work

@jridgewell  
- Service worker work submitted, reduced to <1k
- Removed IndexedDB #4665
- Added Version Blacklist #4664
- Added Killswitch #4562
- Removed explicit width-height using fill-content #4674

@ericlindley-g
- Documentation for <amp-live-list> cache optimizations
- Identified approach for out-of-the-box AMP templates and styling

@erwinmombay
- Fixed config/AMP_CONFIG bugs
- Added new csi ticks
- Initial skeleton commit for amp-fresh

@vamsee
- Ads work

@willchou
- Some performance starter bugs

@dvoytenko
- Forms and security review
- PWA, dependency order work
- Work on polyfilling shadow DOM, iframe polyfill
- Alternative is css mangling on subtree
- Polyfilling service worker

**Comment by yuxuan** [comment]
Hey @erwinmombay, I think you @ the wrong yuxuan. And say welcome back to @cramforce for me please 😄

**Comment by erwinmombay** [comment]
@yuxuan thanks 😄 fixed
