### ISSUE TITLE
Dev console error: Unknown attribute for doubleclick: container

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#4862]
This is caused by the #4307 that adds "container" attribute when the `<amp-ad>` is inside `<amp-sticky-ad>`. The fix should be to whitelist such an attribute.

The bug will not block any ads loading, but increase false alarm error messages in our stack driver reporting.

To reproduce, turn on [canary](https://cdn.ampproject.org/experiments.html) and visit [this page]( https://cdn.ampproject.org/v/www.nydailynews.com/amp/news/national/shooter-alpine-high-school-texas-article-1.2783082?amp_js_v=5) then check dev console.

**Comment by zhouyx** [comment]
#4866

**Comment by zhouyx** [comment]
I also found in the page that if user add margin to sticky-ad, it will add gap between sticky-ad and bottom of the page. should I add a `margin: 0 !important` to force it to be at the bottom of the page?

**Comment by jridgewell** [comment]
> I also found in the page that if user add margin to sticky-ad

Separate issue, please. `margin-bottom: 0 !important` should be enough.

**Comment by zhouyx** [comment]
#4867

**Comment by jridgewell** [comment]
Did you mean to close this?
