### ISSUE TITLE
Allow any valid AMP markup in an amp-sticky-ad tag

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#4874]
We'd a bit more flexibility around that can be in an `amp-sticky-ad` tag.

Specifically we'd like to be able to include an `amp-carousel` and then include  native unit (eg nativo) as one of the carousel items.

See https://wsbtv.relaymedia.com/amp/news/local/several-serious-injuries-reported-in-head-on-crash/201144893 for an example of a fixed carousel layer.  Right now we can't put `amp-ad` in fixed layers and we can't put non ads in `amp-sticky-ad`.

**Comment by jasti** [comment]
@jpettitt `amp-sticky-ad` was designed with some UX friendly restrictions like - 
1. The max height can only be 1/6th of the viewport (in portrait mode) or 100 pixels (whichever is smaller).
2. Sticky ad itself will only appear after the user has scrolled beyond the first viewport. 
Will making amp-carousel work inside amp-sticky-ad still make sense with these restrictions?

@zhouyx and @lannka  FYI.

**Comment by jpettitt** [comment]
@jasti - yes that will work, in fact the viewport scroll feature is a plus - it means we can throw up a recirc element like a carousel as the user becomes engaged.

**Comment by jasti** [comment]
Sounds good to me from a product perspective. @lannka @zhouyx Can you think of reasons why we wouldn't allow valid AMP markup other than ads inside of amp-sticky?

**Comment by jasti** [comment]
@jpettitt I see that you've ended up using position:fixed with the carousel. Can this be closed?
<img width="363" alt="screen shot 2017-02-13 at 11 44 41 am" src="https://cloud.githubusercontent.com/assets/2366341/22900080/ee90b848-f1e1-11e6-94b9-e58f28cb3eec.png">

**Comment by jasti** [comment]
Please reopen is this is still an issue. Thanks.
