### ISSUE TITLE
Object.assign polyfill is missing in 3p iframe

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#4877]
Seeing lots of errors in prod that got hidden due to logging weirdness.

**Comment by lannka** [comment]
But I saw `openx.js` is the only one using Object.assign in 3P.

**Comment by lannka** [comment]
Wait, I thought errors in iframe is not reporting back?

**Comment by cramforce** [comment]
We do during initial execution (just a single try-catch), but not window.onerror

**Comment by cramforce** [comment]
Yeah, seems to be openx only.

**Comment by cramforce** [comment]
@caleb-sotelo can you take on fixing this. `Object.assign` is not yet everywhere
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

**Comment by jridgewell** [comment]
Submitted #4890 since @caleb-sotelo isn't a user on Github anymore.
