### ISSUE TITLE
Validator: action-xhr required when method=POST

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#4880]
Currently, `action-xhr` is optional. We want to make it conditionally required when `method=POST` on `<form>` and we want `action` to be invalid in that case. 

``` html
<!-- invalid: action attribute is invalid when method=POST -->
<form method="POST" action="..." action-xhr="..."></form>

<!-- invalid: action-xhr is required when method=POST -->
<form method="POST"></form>
```

Is this conditional possible in validator? 

This is part of changes to fix CORS and XSRF for forms.

cc/ @dvoytenko @cramforce @rudygalfi

**Comment by mkhatib** [comment]
This is probably has been fixed. @Gregable to confirm.

**Comment by Gregable** [comment]
Yes this is fixed, sorry for the lack of update.
