### ISSUE TITLE
404 page after a few views when page is served from AMP cache

### ISSUE THREAD

**Issue by kozlice** [ampproject/amphtml#4881]
I'm not sure if the question belongs here, but here's the problem: I've implemented an AMP version of page, which is not final version yet, but rolled out to production for internal preview/performance measurements. It passes validation. When I open `http://cdn.ampproject.org/c/s/MY_URL`, it's correctly displayed, but after a few refreshes I get 404 page (the one with sad phone). I can't understand the root of this problem. I've got two possible reasons:

- There's a bug in my impl of auth & pingback endpoints - wrong CORS headers, which doesn't affect validation, but throws an error in runtime
- Page has noindex in its meta (which is required for now)

Could they result to 404s? Would appreciate any hints.

**Comment by ericlindley-g** [comment]
@kozlice Do you have an example of a page having this issue?

**Comment by kozlice** [comment]
@ericlindley-g Please, disregard this one. The problem was with HTTP req/res transformer, which doesn't work properly and returns 404 to bot in some cases.

**Comment by ericlindley-g** [comment]
Got it—thanks for the update, @kozlice!
