### ISSUE TITLE
Disallow ES6 APIs

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#4883]
https://github.com/lukehoban/es6features#math--number--string--array--object-apis

Re: https://github.com/ampproject/amphtml/issues/4882

**Comment by adelinamart** [comment]
@jridgewell  referenced issues is closed. Anything else left to be done here? Thanks

**Comment by jridgewell** [comment]
Yup. For reference, this was done in several issues:

- https://github.com/ampproject/amphtml/issues/6551
- https://github.com/ampproject/amphtml/issues/6550
- https://github.com/ampproject/amphtml/issues/6549
- https://github.com/ampproject/amphtml/issues/6539
