### ISSUE TITLE
Change z-index on amp-sticky-ad to > 10

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#4888]
`amp-sticky-ad` is `z-index` 2 by default.  The buttons on `amp-carousel` are `z-index` 10 so they float over the ad.  It's an easy fix in our CSS but it would be nice to have it fixed in the defaults.

**Comment by zhouyx** [comment]
I see that `amp-banner` has z-index of 11 and 12. What's our preference on these two elements? I personally think `amp-banner` should be on top of `amp-sticky-ad`. @mkhatib

**Comment by mkhatib** [comment]
Yeah that sounds good for now. We need to work on a fixed elements manager for better managing what to show and when - for example `amp-user-notifications` probably should have the highest priority (or z-index) of showing on top of `amp-app-banner` and `amp-sticky-ad`.

Feel free to up `amp-app-banner` to get it on top of `amp-sticky-ad` for now. Mind also updating the `Z_INDEX.md`?

**Comment by sriramkrish85** [comment]
make sure this is lower than `amp-sidebar`

**Comment by zhouyx** [comment]
👌
