### ISSUE TITLE
Please add docs about "real life" issues - jquery, boostrap, foundation

### ISSUE THREAD

**Issue by Siton-Systems** [ampproject/amphtml#4889]
I want to use Jquery and some JS components carousel, lightbox ....(of boostrap, foundation, uiKit etc). 
What is the best way? 

Its valid - yes/no....You must spot this issue (Because 90% of the sites use some framework - not in general like today docs).

**Comment by kozlice** [comment]
You can't do that. 3rd party JS is not allowed on the page itself, only inside sandboxed iframes. This is stated in docs: https://www.ampproject.org/docs/get_started/technical_overview.html#keep-all-third-party-javascript-out-of-the-critical-path (although I should say that wording could be more straightforward there).

**Comment by Siton-Systems** [comment]
Thanks. 

And what about CSS? boostrap, and so on

**Comment by kozlice** [comment]
@Siton-Systems This is pretty much covered on the same doc page: styles are limited to 50KB and must be placed inside `<head>`, not in a separate file. You can embed framework's CSS there. Current Bootstrap version (3.3.7) is ~120Kb, which is above the limit, but you can make a custom build, containing only things you need, or use something more lightweight (e.g. Skeleton or grid960).

**Comment by Siton-Systems** [comment]
Thanks!...
