### ISSUE TITLE
Follow up with EasyPrivacy why our services are on their list

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#4896]
See https://easylist-downloads.adblockplus.org/easyprivacy.txt

The repo is: https://github.com/easylist/easylist/tree/master/easyprivacy

Currently it blacklists two of our services:
> /amp-analytics-
> amp-error-reporting.appspot.com^ 

Some background and issues with this:

"amp-error-reporting.appspot.com^" doesn't share identifiers of any kind and is purely there for troubleshooting. So it's not clear why it's there.

"/amp-analytics-" currently blocks AMP Access given that paywalls need some form of identification to function. We can possibly work it around, but it's currently blocked. Generally, blocking amp-analytics script seems to be unnecessary since the analytics services themselves are blocked and all actual analytics calls are delegated to these blocked services.

**Comment by cramforce** [comment]
Lets focus on `amp-analytics-`. We don't need to argue anything like the above. The facts are clear

- `amp-analytics-` currently provides vital functionality for non-analytics use cases. We can fix this, but not super quickly. Currently pages may be broken.
- It doesn't make any requests by itself. Blocking actual analytics request still works when it loads.

**Comment by lannka** [comment]
> amp-analytics- currently provides vital functionality for non-analytics use cases. We can fix this, but not super quickly. Currently pages may be broken.

This requires #3888 to be done, so that we can move CID and Crypto related code to core.

**Comment by rudygalfi** [comment]
This is partially resolved by https://github.com/easylist/easylist/commit/17e0447fb7c6df377a1081f730c5039c5396d0af. The rest won't be pursued.
