### ISSUE TITLE
Spellcheck the allowed svg elements list

### ISSUE THREAD

**Issue by erikdahlstrom** [ampproject/amphtml#490]
https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#svg

polygone -> polygon
lineGradient -> linearGradient
radialGrandient -> radialGradient

**Comment by erwinmombay** [comment]
those are some epic typo's! will fix :)

**Comment by erwinmombay** [comment]
fixed via https://github.com/ampproject/amphtml/pull/515

appreciate the bug report!
