### ISSUE TITLE
Slidescroll <amp-carousel> flips back to previous image after swipe

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#4904]
Just on certain implementations (example [here](https://cdn.ampproject.org/c/www.jn.pt/mundo/mundo-insolito/interior/amp/foto-de-perfil-no-facebook-vale-prisao-5374649.html) and [here](https://cdn.ampproject.org/c/roma.repubblica.it/cronaca/2016/08/29/news/mister_facebook_a_roma_tra_jogging_e_luiss_roma_ti_amo_-146822020/amp/)), the slidescroll implementation (when opted into the experiment, via pages served from the CDN) has the following issue:

On Android/Chrome or mobile emulator on Mac Chrome
1. Swipe to the second slide
2. Swipe back to the first slide
 — the carousel goes to the first slide for an instant, then goes back to the second slide. It becomes impossible to return to the first slide

Not sure how widespread this issue is (have only encountered it these two times so far)

cc @aghassemi @muxin @sriramkrish85

**Comment by ericlindley-g** [comment]
[Another example](https://cdn.ampproject.org/c/m.lavoz.com.ar/amp/ciudadanos/el-cordobes-que-le-gano-facebook).  Only happens with two-item carousels so far

**Comment by aghassemi** [comment]
Good find. I think `two-item` is the key here :) Will fix soon.

**Comment by aghassemi** [comment]
Also found a related bug which happens on all carousel, without a `loop` enabled, if one goes to slide 2 and then uses the "back control button", it does not work. Swiping works however. @ericlindley-g

**Comment by aghassemi** [comment]
Second bug is on all carousels regardless of number of items. Original bug is only on 2-item carousels. I spent some time on this but I am not familiar enough with code and the different edge cases it supports to fix it. Assigning to @sriramkrish85, feel free to assign back if you have higher priority stuff on your plate.

**Comment by sriramkrish85** [comment]
Ali this can happen because iOS scroll snap is flimsy with CSS changes. Can you confirm that this happens on Android as well and also check out reverting your latest CSS changes . I can come and sync up tomorrow

**Comment by aghassemi** [comment]
Original bug happens in all browsers with 2-item carousels. in iOS, swipe works but using the control button doesn't. In Chrome, neither swipe or using controls button work. There is some logic break-down with carousels that have 2 items that I could not pinpoint.

**Comment by ericlindley-g** [comment]
@sriramkrish85 — is this fix in canary? Still able to repro in Chrome emulator with the links in the first comment

**Comment by sriramkrish85** [comment]
@ericlindley-g i dont see the fixes on canary yet ! will let you know once it is there

**Comment by ericlindley-g** [comment]
No worries—thanks!

**Comment by ChrisHoman** [comment]
Still having this issue on iPhone

**Comment by ericlindley-g** [comment]
@ChrisHoman, is this on all pages, or just a specific one? And still just with 2-image carousels?

/cc @camelburrito

**Comment by ericlindley-g** [comment]
This may have already been closed with a recent fix. Please re-open if you're still seeing the issue. Thanks!
