### ISSUE TITLE
Build samples for other static content types

### ISSUE THREAD

**Issue by jmadler** [ampproject/amphtml#491]
e.g. Blog, Recipe, TechArticle

**Comment by Meggin** [comment]
I'm going to try and AMPify Addy's blog template: http://www.getmdl.io/templates/blog/index.html

**Comment by arturotena** [comment]
Pardon me if this is not ok to ask questions here. But, why AMP is being labeled for «static content» only? If the content is dynamically generated, I can't think of a reason why it couldn't be AMPified.

**Comment by erwinmombay** [comment]
@arturotena always feel free to ask questions :)

as for the term static content here, I may be wrong in the definition but my understanding is the backend here is free to generate the content `dynamically` however they want through cms/frameworks/templating but the final output is what we usually term as the static content which doesn't have any dynamic functionality or content on the page getting loaded dynamically (ajax, javascript).
