### ISSUE TITLE
Consider avoiding making preflight requests in xhr-impl JSON POST requests

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#4910]
`xhr-impl` current implementation uses `Content-Type: application/json` for POST requests by default, [forcing browsers to make preflight requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests).

From MDN:

> Unlike simple requests (discussed above), "preflighted" requests first send an HTTP request by the OPTIONS method to the resource on the other domain, in order to determine whether the actual request is safe to send.  Cross-site requests are preflighted like this since they may have implications to user data.  In particular, a request is preflighted if:
> 
> It uses methods other than GET, HEAD or POST.  Also, if **POST is used to send request data with a Content-Type other than application/x-www-form-urlencoded, multipart/form-data, or text/plain**, e.g. if the POST request sends an XML payload to the server using application/xml or text/xml, then the request is preflighted.
> It sets custom headers in the request (e.g. the request uses a header such as X-PINGOTHER)

This affects dismissal requests in `user-notifications` and possible `share-tracking`. Forms are not affected since `POST` requests use `application/x-www-form-urlencoded`. That's also seems to be the case for access where `x-www-form-urlencoded` is used to circumvent making preflight requests.

**Comment by dvoytenko** [comment]
/cc @erwinmombay 

I'm wondering how we can "carefully" do it w/o disturbing any existing implementations. Might be good to find out who uses this feature now.

**Comment by adelinamart** [comment]
@mkhatib do we still need this? Thanks

**Comment by mkhatib** [comment]
@dvoytenko is a better person to answer. But I am ok with closing this for now or moving it to backlog

**Comment by cramforce** [comment]
What is the status here? Are we triggering preflight? We definitely need to find a way to stop.

What is the list of services that do this under which conditions?

**Comment by pwdonald** [comment]
Does it always send the form data as multipart/form-data? It makes it hard to utilize this with the AWS API Gateway, no?

**Comment by cramforce** [comment]
@pwdonald Do you have a more concrete example?

**Comment by pwdonald** [comment]
@cramforce Perhaps this should be a separate issue but it does relate to the lack of configuration of the HTML form. 

So far anytime I use `method="POST`" and `action-xhr` the resulting request is `multipart/form-data` binary. I tried setting `enctype `to `application/x-www-form-urlencoded` but it was ignored. I was finally able to get this it to play nicely with AWS API Gateway but I had to write a somewhat hacky lambda function to decode the base64 string and parse the form values.

**Comment by cramforce** [comment]
@pwdonald yes, please file a separate issue. Being able to talk to arbitrary API endpoints is a non-goal, but we also don't want to make it hard.

**Comment by dvoytenko** [comment]
The directive here is as much as possible to use `application/x-www-form-urlencoded`. Un-launched extensions (`share-tracking`, cc @muxin) should switch right away. Launched extensions (`user-notification`, cc @erwinmombay) should add `enctype=application/x-www-form-urlencoded` to override the default `application/json`. Forms - I'll look at the new issue. But I believe we should be all good there.

**Comment by aghassemi** [comment]
new issue for forms is this one: https://github.com/ampproject/amphtml/issues/7607

**Comment by dvoytenko** [comment]
Spun off #7695 for `amp-user-notification`. Closing this bug.
