### ISSUE TITLE
Passing variables to `getIframe()` directly, w/o writing to HTML attribute

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#4912]
with `amp-ad` we have two things that we want to pass to `getIframe()`, cid and ad-container, our current solution is to write this info to HTML attribute first, and `getIframe()` will get info using `getAttribute()`.

The current method has potential security issue as we are writting `ampcid` to attribute directly. Also it is a waste to write the info to somewhere else and ask `getIframe` method to get it later. 
I would suggest we pass an `opt_context` obj to `getIframe()` function and avoid writing anything data to dom. 

@cramforce @lannka

**Comment by cramforce** [comment]
SGTM to change to explicit passing.

**Comment by zhouyx** [comment]
closed by #4929
