### ISSUE TITLE
The tests we run in Travis are too flakey.

### ISSUE THREAD

**Issue by powdercloud** [ampproject/amphtml#4917]
I'm trying to get a PR in, and I think it's been 3 times in a row that something in the test suite has failed. It's timeouts and things like this. I'm sure everyone contributing a bunch has run into it so I hope it's OK to keep the description of the problem vague.

Maybe we can do any of these?
- Increase some of the timeouts so the tests don't flake as often.
- Do something more principled to avoid relying on timeouts so much (maybe not possible with Javascript-based functional tests)?
- Add some more granularity, e.g., only run the large functional tests suite if X changes. I saw that something like this already happens for docs; but it may also help to kick of multiple Travis runs for different parts of the depot because retrying a partial run takes less time than retrying the whole thing.

I bet it's easy to come up with more and better ideas, which should be easier for people working on the runtime than it is for me. Anyhow, I think it'd be good to improve this a bit if possible. Thanks!

**Comment by cramforce** [comment]
@powdercloud Do you have a travis run with an example? We had a persistent failure all of Friday which we took too long to to disable (I did late Friday night, but you would have had to sync past that). Now it is fixed.

**Comment by powdercloud** [comment]
@cramforce I just reran the test. It failed again, this time probably due to flakiness:
https://travis-ci.org/ampproject/amphtml/builds/158873686
I had some hunch that the failure on Friday was persistent, but it took me quite a few trials to get that hunch.
Perhaps it should be possible to override the thing when the failure is clearly not related to what I'm checking into there.

**Comment by powdercloud** [comment]
OK this is even more puzzling. There's a failure in the middle of it, but the overall color is green.

```
Chromium 51.0.2704 (Ubuntu 0.0.0) IntersectionObserver "after each" hook for "should send more intersections" FAILED
	Error: Blocked a frame with origin "/tmp/cdba687bdf20235f80f927268a7e27d6.browserify:58076:28 <- node_modules/sinon/lib/sinon/util/core.js:154:0)
	    at each (/tmp/cdba687bdf20235f80f927268a7e27d6.browserify:55575:33 <- node_modules/sinon/lib/sinon/collection.js:34:0)
	    at Object.restore (/tmp/cdba687bdf20235f80f927268a7e27d6.browserify:55595:17 <- node_modules/sinon/lib/sinon/collection.js:54:0)
	    at Object.restore (/tmp/cdba687bdf20235f80f927268a7e27d6.browserify:56863:42 <- node_modules/sinon/lib/sinon/sandbox.js:96:0)
	    at Context.<anonymous> (/tmp/cdba687bdf20235f80f927268a7e27d6.browserify:102593:13 <- /home/travis/build/ampproject/amphtml/test/functional/test-intersection-observer.js:401:12)
Chromium 51.0.2704 (Ubuntu 0.0.0): Executed 685 of 2932 (1 FAILED) (skipped 1) (0 secs / 5.109 secs)
```

Will try to merge and see what goes. :-)

**Comment by powdercloud** [comment]
Merging worked.
@cramforce Also, thank you for fixing the breakage.

**Comment by cramforce** [comment]
This was a bit special, because we had a non-hermetic test that failed due to an external dependency. So there was nothing to roll back. I'm sorry we didn't take quicker action to skip the test.

I filed #4932 for your flake (which is curious in that apparently `afterEach` fails are not counted as real errors.
