### ISSUE TITLE
Microdata and RDFa in AMP

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#4919]
Microdata **is supported** in AMP but RDFa **is not**.
Here is the source of the mark-up below: [http://schema.org/CreativeWork]

Microdata:

```
<div itemscope itemtype="http://schema.org/CreativeWork">
<span itemprop="name">Resistance 3: Fall of Man</span>by 
<span itemprop="author">Sony</span>,Platform: Playstation 3 Rated:
<span itemprop="contentRating">Mature</span>
</div>

```

RDFa:

```
<div vocab="http://schema.org/" typeof="CreativeWork">
<span property="name">Resistance 3: Fall of Man</span> by 
<span property="author">Sony</span>, Platform: Playstation 3 Rated:
<span property="contentRating">Mature</span>
</div>
```

AMP validator throws the following errors on RDFa mark-up:

_The attribute 'vocab' may not appear in tag 'div'._
_The attribute 'property' may not appear in tag 'span'._

There are other RDFa object properties, such as `about`, `rel` and compact URIs (CURIE), that also are rejected. A CURIE is in the form `xmlns:owl`.

When `<amp-img>` is used in place of `<img>`, AMP validator rejects 'property' in both Microdata and RDFa mark-up.

Will the Google AMP team consider supporting RDFa mark-up in AMP documents?
Will you support Microdata and RDFa mark-up for AMP-specific elements such as `<amp-img>`

/jay gray

**Comment by jaygray0919** [comment]
May I ask if this was resolved in "Pending Triage milestone on Sep 14"?

We see the same errors as previously reported.

**Comment by jridgewell** [comment]
This hasn't been implemented. /cc @Gregable

**Comment by Gregable** [comment]
Marking closed in #6739 by @darobin.

Will be a few weeks before it goes live.

**Comment by honeybadgerdontcare** [comment]
This is now live in prod.

**Comment by jaygray0919** [comment]
Thank you for progress with RDFa support. From our perspective, there are two remaining issues:
support for `rel=""` and `rev=""`

Consider this structure:

```
<section id='Sponsor' about='[this:]' rel='dcterms:hasPart' rev='dcterms:isPartOf' resource='[this:#Sponsor]'>
  <h2 about='[this:#Sponsor]' property='dcterms:subject' rel='dcterms:contributor'>Sponsor</h2>
    <section id='Sponsor-name' about='[this:#Sponsor]' rel='dcterms:hasPart' resource='[this:#Sponsor-name]'>
      <div about='[this:#Sponsor-name]' typeof='foaf:Person' property='foaf:name'></div>
    </section>
</section>

```
According to the current validator, we can successfully declare `about=""`, `resource=""` and `property=""`.
That is good!
`rev=""` is not essential, but `rel=""` is very useful for building graphs of related terms.

Should we provide additional examples that demonstrate the importance of `rel=""`?
What else can we do to help here?

/jay gray

**Comment by honeybadgerdontcare** [comment]
@jaygray0919 We'll look into adding it. Please open a new issue for this request.
