### ISSUE TITLE
Allow :focus pseudo-class in CSS

### ISSUE THREAD

**Issue by adactio** [ampproject/amphtml#493]
The documentation on allowed CSS currently states:

"Pseudo selectors are generally forbidden and must be whitelisted 1 by 1. Initially we only allow :hover, :active and :visited with whitelisted CSS properties (For color and underlining)."

Please consider adding :focus to the whitelist to cater for users using a keyboard (rather than a mouse) to tab between links.

Cheers,

Jeremy

**Comment by cramforce** [comment]
+1

**Comment by cramforce** [comment]
Will add.

**Comment by adactio** [comment]
Sweet! Thank you.

**Comment by cramforce** [comment]
Done

**Comment by adactio** [comment]
:+1:
