### ISSUE TITLE
amp-fresh default visibility state

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#4930]
an `amp-fresh` component's content is "replaced" on a successful update which can cause a flash during replace. would the correct visual ux here be to hide the content by default and show it after a successful/failed update?

cc @ericlindley-g @dvoytenko (and abby, don't know her username yet)

**Comment by ericlindley-g** [comment]
cc/ @rudygalfi

**Comment by abeck000** [comment]
hm...lets talk about this...i have some ideas as this will also likely come up for the ad components.

**Comment by dvoytenko** [comment]
@ericlindley-g to confirm - the current implementation by default hides the content. A page author can change that and instead employ graying out or opacity.

**Comment by ericlindley-g** [comment]
to/ @rudygalfi  (though I'm happy to jump in as needed — the default as described by @dvoytenko  sounds good, though curious what other options there might be)

**Comment by dvoytenko** [comment]
Some options I see a publisher could use:

1. Reduce opacity of a block that needs refreshing. Or make color grey-ish to make it obvious that it's still in progress.
2. Show a loading indicator.
3. Hide/grey-out/hash-out sensitive datapoints that need updating the most. E.g. $price could be grey-ed out or replaced with `--` while we are loading fresher content.

**Comment by rudygalfi** [comment]
Is this obsolete now?

**Comment by erwinmombay** [comment]
@rudygalfi think we can close for now until we start working on the amp-fresh + amp-bind work.
