### ISSUE TITLE
Use proper svg element categories

### ISSUE THREAD

**Issue by erikdahlstrom** [ampproject/amphtml#494]
https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#svg groups elements into a couple of different categories. Some of these categories exist in the svg specification, but with different meaning. I'd suggest using the categories as they're defined in the svg spec, for clarity.

https://svgwg.org/svg2-draft/struct.html#TermContainerElement
https://svgwg.org/svg2-draft/struct.html#TermStructuralElement
https://svgwg.org/svg2-draft/struct.html#TermGraphicsElement
https://svgwg.org/svg2-draft/text.html#TermTextContentElement
https://svgwg.org/svg2-draft/painting.html#TermPaintServerElement
https://svgwg.org/svg2-draft/struct.html#TermDescriptiveElement

**Comment by kristoferbaxter** [comment]
Resolved with #31808.
