### ISSUE TITLE
Duplicated amp-ad README files 

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#4946]
Files `amp-ad.md` and `amp-embed.md` are in both folders: `builtins/` and `extensions/amp-ad/`.

Which is not only confusing both publishers and 3P contributors (some of them are still updating old place but not new place), but also becomes a blocker for us to improve the `amp-ad` documentation in general.

It was due to the migration of `amp-ad` from builtin to extension. However, `builtins/*` still exists because [amp-docs](https://github.com/ampproject/docs) is using them to generate web pages.

So we have to remove this dependency from amp-docs. However, the blocker is that `amp-embed` is such an outlier (it is not a real extension), which doesn't follow the pattern `/extensions/amp-abc/amp-abc.md` that amp-docs relies on to auto-generate the web pages. 

**Solutions**
1. Make a special case for `amp-embed` in amp-docs
2. Merge the content of `amp-embed.md` into `amp-ad.md`

I prefer 2 because:
* They are essentially the same thing, `amp-embed` is a pure alias of `amp-ad`
* Easy for amp-docs.

@jasti thoughts?

**Comment by jasti** [comment]
@lannka Totally makes sense to do 2. We have very few embed partners and we can simply give them a heads-up.
