### ISSUE TITLE
amp-fit-text layout=fill breaking parent element

### ISSUE THREAD

**Issue by jmadler** [ampproject/amphtml#4947]
This might be a misunderstanding on my part, but when amp-fit-text is called with layout=fill:

`<amp-fit-text width="300" height="200" layout="fill">foo</amp-fit-text>`

It seems to be exceeding the size of its parent element and filling its grandparent element instead.  My understanding is that it should fit to fill its parent element.

See this [gist](https://gist.github.com/jmadler/71f5a5fd7b822dd456a5c81720ed23ce) for a simple min-reproducible test case.

**Comment by jmadler** [comment]
This also applies to amp-img

**Comment by aghassemi** [comment]
see https://github.com/ampproject/amphtml/pull/5176

**Comment by aghassemi** [comment]
Closing as dup of https://github.com/ampproject/amphtml/issues/5177
