### ISSUE TITLE
amp-analytics swallowing errors

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#4948]
I noticed that `amp-analytics` uses `.warn` to emit user errors like here. https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/transport.js#L70

These are currently never really shown to anyone. Should we:
- Make these errors
- Or show warnings

?

I think the latter makes sense.

**Comment by dvoytenko** [comment]
/cc @avimehta 

@cramforce I believe this case  is special. This is where 204 is returned on image request and it was just too annoying to report it.

**Comment by avimehta** [comment]
This is usually a vendor config related error (not always but most of the time). Showing this to users will be noisy but might prompt vendors to fix their configs. Okay with whichever path you guys deem fit.

**Comment by cramforce** [comment]
Is there any way to disambiguate the 204 from a 404?

**Comment by dvoytenko** [comment]
@cramforce Unfortunately, we didn't find any...

**Comment by rudygalfi** [comment]
Making this P3 based on no action happening in 4-5 months.

**Comment by adelinamart** [comment]
Assigning it to @rudygalfi until we know when work on this should start.

**Comment by dvoytenko** [comment]
Closing as infeasible.
