### ISSUE TITLE
Consider stopping to transmit stack trace for user errors.

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#4949]
Capturing the stack is expensive and not needed for user errors.

**Comment by cramforce** [comment]
to @cvializ as a warm up project.

To implement

- open error.js
- save the `isUserErrorMessage(message)` expression into variable (already in there once).
- make the line that appends `'&s='` conditional on the error not being a user error.

**Comment by jridgewell** [comment]
Thanks for closing. For future reference, put explicitly either "Fixes #[issue]" or "Closes #[issue]` to have Github auto-close on merge.

**Comment by cvializ** [comment]
Ah cool. I was following the template for a new PR and it suggests "Implements" as a verb for what a PR does for an issue. Given that other contributors will read the template and might put "implements #[issue]", is there a way to add that to the auto-close, or is that hard-coded by GitHub and we should change the PR template?

> <img width="100%" alt="screen shot 2017-02-27 at 1 27 24 pm" src="https://cloud.githubusercontent.com/assets/2363700/23380675/961094bc-fcf0-11e6-8477-0b6f9fa00838.png">

**Comment by jridgewell** [comment]
It's hardcoded by Github, let's update the [PR template](https://github.com/ampproject/amphtml/blob/master/.github/PULL_REQUEST_TEMPLATE.md).
