### ISSUE TITLE
amp-social-share layout=flex-item not rendering

### ISSUE THREAD

**Issue by jmadler** [ampproject/amphtml#4953]
I can't seem to get amp-social-share working with layout=flex-item in a flex-box div.  See [this gist](https://gist.github.com/jmadler/15c17631841a9cef0d27e9b8050738ef) as a minimum reproducible test case.

**Comment by ericlindley-g** [comment]
Strange—and when you remove the `layout` attribute from any of the items, all of them flow in: http://jsbin.com/wuzamoziyo/edit?html,output

@mkhatib , do you know what's going on here?

**Comment by jmadler** [comment]
Post-Holidays Ping :)

**Comment by mkhatib** [comment]
@jmadler sorry for not getting back to this earlier. The buttons are rendering but they're getting height of 0. The fix is to simply give them a height either in CSS or with `height` attribute on each element.

```html
    <div class="social-share">
      <amp-social-share height="100px" type="email" layout="flex-item" class="social-share-email"></amp-social-share>
      <amp-social-share height="100px" type="gplus" layout="flex-item" class="social-share-gplus"></amp-social-share>
      <amp-social-share height="100px" type="twitter" layout="flex-item" class="social-share-twitter"></amp-social-share>
      <amp-social-share height="100px" type="pinterest" layout="flex-item" class="social-share-pinterest"></amp-social-share>
      <amp-social-share height="100px" type="linkedin" layout="flex-item" class="social-share-linkedin"></amp-social-share>
    </div>
```

Let me know if this is not what you expected.
