### ISSUE TITLE
Test coverage for components+layouts

### ISSUE THREAD

**Issue by jmadler** [ampproject/amphtml#4954]
I seemed to have a stumbled on a handful of cases where amp components don't behave as I'd expect with layouts other than responsive (#4947, #4953).  I suspect there may be more bugs in this vein.  

Would it make sense to review the testing suite and/or code review process for potential improvements to prevent these kinds of bugs?

**Comment by cramforce** [comment]
The only real solution is examples. Very hard to unit test.

Components definitely should not allow sizing to unsupported. Not 100% sure, though, that these 2 cases automatically mean there are more bugs. They may be special snow flakes.

**Comment by jmadler** [comment]
I've filed https://github.com/ampproject/amp-by-example/issues/359 to backfill component/layout combos as a means of functional testing.
