### ISSUE TITLE
Please add the most known pattern in mobile today for zoom images

### ISSUE THREAD

**Issue by Siton-Systems** [ampproject/amphtml#4955]
**FB, Android photobroswer, Behance, Booking app and so on.**

**Example:** Set of 5 images for in a slider. Swipe - swipe swipe ===> when you **click** on the image you get "lightbox" group. Than again you can swipe between images. 

When the user click "back" button its for "close" the modal and not for "go back in the url" (like today).

The lightbox today is **without "lightbox" group** its big practical problem (User cant click on each thumbnail  manually for zoom in - in photo galleries).

**Comment by ericlindley-g** [comment]
Thanks for the feedback, @Siton-Systems. It sounds like there are two feature requests here:

1) Browser "back" button should close lightbox
2) Enable lightbox grouping for amp-carousel

(2) is a part of [our current work on the lightbox](https://github.com/ampproject/amphtml/issues/4152)

Can you confirm that (1) is what you want? If you hit the "back" button on Facebook, for instance, the user goes back to the last picture, and doesn't exit the lightbox.

**Comment by Siton-Systems** [comment]
About (2) - sounds good (light box group on carousel). Also a lot of times you need this for thumbs gallery. 

About (1) - in Android when you click "back" you close the modal (Also in FB app + Behance App and other friendly modern app). I say this only because today only http://photoswipe.com/ react like this + amp lightbox for one image  (all other 9,999 lightbox libraries "go back in the url" ajax issue) - so i hope we keep this idea also in "lightbox group" :)

**Comment by ericlindley-g** [comment]
Apologies w/r/t point (1) above—you're absolutely right that facebook backs out of the entire lightbox on browser navigation back (I was testing the desktop web version, and not mobile :P 

I think there's an argument for both behaviors (browser-back goes to last photo, versus exits lightbox), and is worth a deeper dive to figure out what's best for users. Will definitely take your feedback as a vote in favor of the latter (and at least in terms of a first impression I'm inclined to agree)

cc/ @aghassemi

**Comment by Siton-Systems** [comment]
"BACK BUTTON" - in desktop is rare to use this when you are in lightbox mode (You click on the overlay to close the modal) - and click next-prev on the pic (50% area of next - 50% - back - FB use this pattern for 4-5 years until today).

In mobile - ANDROID itself use "back" to close images on the "native" photo browser. Also google by pics (In broswer). You go "to prev" image by swipe.

**Comment by rudygalfi** [comment]
I think this was unintentionally closed. Reopening.
