### ISSUE TITLE
Break dependency from amp-a4a to amp-ad-3p-impl

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#4957]
The common objects should be factored into a common dependency.

**Comment by cramforce** [comment]
Also, does `a4a` need to be an extension or can it be abstract?

**Comment by tdrl** [comment]
`a4a` itself is really intended to be abstract.  You shouldn't be able to load it directly -- only via one of the `*network-*-impl`s.  Is there a way to say that in JS?

**Comment by cramforce** [comment]
@tdrl I deleted the call that made it an "extension" from AMP's `gulpfile.js`. Adding `@abstract` to the class definition should work.

**Comment by tdrl** [comment]
Ah, nice.  I wasn't aware that we supported an `@abstract` qualifier.  Thanks!

**Comment by cramforce** [comment]
Note also, that we now (finally) support type checking extensions. Removing
the arg here
https://github.com/ampproject/amphtml/blob/master/gulpfile.js#L51 will turn
it on. We're working through all of them, but you could give it a shot.
