### ISSUE TITLE
Document which (if any) svg attributes are disallowed

### ISSUE THREAD

**Issue by erikdahlstrom** [ampproject/amphtml#496]
https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#svg

Are there any svg attributes that are disallowed, or handled in a limited way (apart from the already listed "xlink:href")?

**Comment by Gregable** [comment]
This is implemented as a white list, so essentially there are an infinite number of disallowed attributes. That said, there are definitely some that I can think of which we conceptually disallow:
 
* Any attribute starting with 'on'
* Any animation attributes (e.g. attributeType, begin, restart, keySplines, accumulate, etc)

Also xlink:href is allowed if the target starts with '#', so in other words is local to the document.

**Comment by erikdahlstrom** [comment]
Is the white list of attributes too long to list in the docs? If not, please add the list to the docs, and otherwise consider adding a link to the complete set of allowed attributes.

**Comment by dvoytenko** [comment]
No, not long. We'll do.

**Comment by dvoytenko** [comment]
But my ideal solution would be to merge the validation rules into Github very soon and build docs based on them automatically. This way we'll have rules and docs sync'd 100%. So, I'd prioritize doing that.

**Comment by erikdahlstrom** [comment]
Sounds good to me.

**Comment by cramforce** [comment]
Is there anything to do here?

**Comment by Gregable** [comment]
Nothing left to do here specific to the original issue. The [validator](https://github.com/ampproject/amphtml/blob/master/validator/validator.protoascii) is now available with all of the attribute lists in the spec file.

I think we can use Issue #994 to track auto-generated documentation.
