### ISSUE TITLE
Service registration should not create the service

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#4986]
Currently our `installFooService` methods all make an instance of the service. This was different originally, before we started to centrally install the services in their respective JS binary.

We should switch the registrations to be just that, so that we don't make instances until we have to.

**Comment by dvoytenko** [comment]
Agree. At least beyond 3-4 most important services.

**Comment by adelinamart** [comment]
@dvoytenko who will be the best person to work on this?

**Comment by dvoytenko** [comment]
@adelinamart Not necessarily :)

**Comment by jridgewell** [comment]
This is an easy starter bug. Maybe one of our new team members could take it?

**Comment by cramforce** [comment]
It is not all that easy. I spent 30 minutes on it and failed :)

But, yes. I was thinking maybe @kmh287?

**Comment by kmh287** [comment]
I'm not sure this can be done without a rather large refactor. Almost all of the install methods on each of the services returns the service. Some of these always have their return values ignored and those are easy enough to fix, but there are others that have assignments to their return values both in tests and in other parts of the code.

**Comment by dvoytenko** [comment]
I'd just move one-by-one tbh
