### ISSUE TITLE
URL encoding causes invalid pages and wrong URLs

### ISSUE THREAD

**Issue by Jeiwan** [ampproject/amphtml#4987]
Looks like URLs are additionally encoded in AMP Cache, and not decoded when shown to users.

To reproduce:
1. To go http://g.co/ampdemo on you mobile device
2. Search for "Bad vibes urbandictionary"
3. The first result should be a link to an AMP-enabled page on urbandictionary.com
4. Click the link and see a page saying this is an invalid AMP HTML page. If you click "Debug original page" link, the validator will say that the page passes. If you click "Click here to continue" button, you'll be redirected to a double-encoded URL (https://www.urbandictionary.com/define.php?term=Bad%2520vibes) resulting in a 404 page. You can visit https://www.urbandictionary.com/define.php?term=Bad%20vibes to see that the page actually exists.

You can repeat these steps for "pornament urbandictionary" search query and it'll succeed. The bug only happens when URL-encoding changes the URL, so all one-word queries will work and all multi-words queries will fail.

## What browsers are affected?

Tested in Chrome and Safari, but it doesn't seem to depend on a browser.

## Which AMP version is affected?

We noticed the bug on August 28, but it could've been there before that.
"Powered by AMP ⚡ HTML – Version 1472695982886"

**Comment by Jeiwan** [comment]
Could you recommend any workaround while this is not fixed? Google now shows AMP indicator on search results, and because of this bug many our pages will be shown as invalid and users won't be able to visit them.

**Comment by cramforce** [comment]
This is tracked at Google as b/31692108

We'll keep this open until the issue is resolved. In terms of a short term workaround it is currently being discussed to blacklist urban dictionary from showing as AMP result until the issue is resolved.

I'm sorry that this issue did not get escalated from the open source project to Google. The Google team independently discovered this today from log analysis.

**Comment by Jeiwan** [comment]
> it is currently being discussed to blacklist urban dictionary from showing as AMP result until the issue is resolved

This looks excessive, since the bug affects only some pages, not all of them. Could you not do this, please? Also, we're going to deploy a fix soon that disables URL encoding in 'amphtml' link tag. It looks like AMP Cache doesn't expect it to be encoded.

**Comment by cramforce** [comment]
Great! If you have a workaround that is great.

I (or I guess someone else since I technically have a vacation day tomorrow) will update when a fix is deployed.

**Comment by cramforce** [comment]
PS: If the workaround works, that is great. Note, that after Google fixes the underlying issue, these URLs will be requested as unencoded. This may lead to issues if you have query strings that require encoding (e.g. band names that contain `&`)

**Comment by cramforce** [comment]
Setting milestone to "Pending 3p implementation" since Google needs to fix this.

**Comment by rudygalfi** [comment]
The fix on the Google side has rolled out. Please try it and let us know if you continue to see a problem. 

Thanks again for the initial report.

**Comment by Jeiwan** [comment]
Thank you!
Yes, we confirm that the bug is fixed now.
