### ISSUE TITLE
a11y: Increase size of app banner close affordance tap target to 48x48

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#4994]
No need to change the size of the button itself

**Comment by mkhatib** [comment]
We're sure about this? 48px looks pretty big.

![localhost-8000-examples-viewer html chrome ios](https://cloud.githubusercontent.com/assets/2647/18538028/87e1af8e-7abe-11e6-8637-c4c675502c02.png)

**Comment by mkhatib** [comment]
Oh, I totally didn't see the comment about not increasing the size of button itself. Will fix.
