### ISSUE TITLE
Move viewer communication into AMP core

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#4997]
Currently AMP relies on "viewer supplied" JavaScript to communicate with the viewer. The intent was to be flexible in how that communication works. 

In turns out, that this makes it way too hard to build viewers, especially with the existing caches, so we want to move that (pretty simple) code into the core.

And then document the protocol :)

**Comment by cramforce** [comment]
Updates the description.

**Comment by rudygalfi** [comment]
Any estimate on when we could prioritize and work on this?

**Comment by cramforce** [comment]
I was thinking it would be a great second project for @chenshay
