### ISSUE TITLE
need to support triggering amp-sidebar in lightbox mode

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#4999]
As discussed here https://github.com/ampproject/amphtml/pull/4906#r78810434 and offline.
we should still support amp-sidebar in lightbox mode.

@aghassemi @sriramkrish85

**Comment by zhouyx** [comment]
Two possible bugs by setting amp-sidebar z-index greater than amp-lightbox-viewer.

1. When amp-sidebar contains a lightboxable item. User should enter full screen lightbox mode when they click on those items. But since amp-sidebar has higher z-index than lightbox viewer they will still have the sidebar on side. We should close sidebar manually in this special case.

2. When user is in lightbox gallery view and they open sidebar and continue to click on a lightboxable item inside sidebar. We should show them item in lightbox viewer. But since lightbox viewer has lower z-index than lightbox gallery viewer, we need to close gallery viewer manually before we enter lightbox viewer in this special case.

**Comment by sriramkrish85** [comment]
1) should close the sidebar
2) This should be a feature we support not a bug :)

**Comment by aghassemi** [comment]
Dup of https://github.com/ampproject/amphtml/issues/6712
