### ISSUE TITLE
Consider allowing multiple custom validators per form

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#5000]
As part of supporting custom validations I am working on now (PR not sent yet), the first pass will only allow one custom validator per form. 

This is a bug to discuss allowing multiple custom validators to be registered to a form. This allows for example a form to have as-you-go AND show-all-on-submit validators instead of having to stick with one.

cc/ @rudygalfi

**Comment by adelinamart** [comment]
@rudygalfi is this still up for discussion?

**Comment by mkhatib** [comment]
Closing this. This was mostly a look into current limit but I don't think in practice this makes sense.
