### ISSUE TITLE
amp analytics - Google Analytics - Event Tracking - nonInteraction

### ISSUE THREAD

**Issue by Polylike** [ampproject/amphtml#5018]
## Short description of your issue:

Is there a way to set amp analytics - Google Analytics - Event Tracking - nonInteraction = 1 so that the Event is a Non-Interaction Event in Google Analytics?
http://www.lunametrics.com/blog/2014/05/06/noninteraction-events-google-analytics/

I want to track a AMP Experiment. My idea: Fire a event with every pageview of the variant of the experiment and segment it later in analytics:

` "triggers": {
  	    "experiment-trigger": {
            "on": "visible",
            "request": "event",
            "vars": {
                "eventCategory": "Experiment",
                "eventAction": "VARIANT(my-test)",
		"nonInteraction": 1
            }`

Here are no key-value for nonInteraction https://developers.google.com/analytics/devguides/collection/amp-analytics/

Is nonInteraction supported by amp? I read the docs but i found no information. Actually with the setup above, the bouncerate is 0%

Thanks!

**Comment by avimehta** [comment]
please try adding the following snippet to the trigger that sends the event hit:

```
  "extraUrlParams": {
    "ni": 1
  }
```

https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#ni
