### ISSUE TITLE
Intent to implement: Billy Mobile adNetwork into amp-ad

### ISSUE THREAD

**Issue by aserrabl** [ampproject/amphtml#5019]
I intent to implement Billy Mobile adNetwork ads into amp-ad on behalf of the named company. We have already signed the corporate CLA as Billy Performance Network.

A PR will be made when the integration passes our internal tests.

Alex

**Comment by jasti** [comment]
@aserrabl do you have an update on this?

**Comment by aserrabl** [comment]
@jasti due to changes in our roadmap we won't me implementing AMP in the medium term. I'm closing the issue.
