### ISSUE TITLE
Implement a scrollable tab navigation

### ISSUE THREAD

**Issue by eike-hass** [ampproject/amphtml#5020]
We want to use a horizotally scrollable navigation for anchor and link navigation. With pure CSS we were able to get good results, but are missing features like highlighting of the link corresponding to the currently visible section (and the possibility to scroll the "active" link into the viewport).

Ideally we would have something similar to [polymers paper-tabs ](https://elements.polymer-project.org/elements/paper-tabs?view=demo:demo/index.html&active=paper-tabs) with `scrollable` attribute set. 

Could this maybe be implemented using the internal visibility spec and custom triggers on the links in the tab bar?

**Comment by cramforce** [comment]
+ @ericlindley-g who was looking into requirements for tabs.

This is definitely something we are planning to support. I'd like to learn more about where you'd want scrolling in the tab on mobile?

**Comment by ericlindley-g** [comment]
I had the same question as Malte—especially given the context many AMP viewers, which already have an action tied to the horizontal swipe gesture.

(Note on this issue: Possible duplicate of https://github.com/ampproject/amphtml/issues/4771, pending discussion)

**Comment by cramforce** [comment]
Is `scrollable` a vertical or horizontal thing?

**Comment by jaygray0919** [comment]
@cramforce We also have a requirement for horizontal scrollable navigation. The use case is a "wide" image that is a non-flex-item where we specify a width="6000" (exaggerated to make the point)  that is wider that the display. In our case, these would be stand-alone images, not ones we would include in a carousel.

**Comment by cramforce** [comment]
The viewer carousel isn't really relevant here. Things like `amp-carousel` can already take over horizontal gestures.

Not 100% sure I found the right thing on Medium, but I think you refer to what is basically a tab navigation where the tabs themselves are on a scrollable pane. Basically just `overflow: auto` on the tab row, right?

**Comment by eike-hass** [comment]
@cramforce exactly. We would like to extend that with highlighting of links to anchors on scroll.

**Comment by cramforce** [comment]
Seems like a very nice UI pattern for mobile!

**Comment by ericlindley-g** [comment]
One last clarification :)

Assuming that these anchor links just trigger naive page navigation (and that they don't update content on the current page, like the proposed [tabbed UI component](https://github.com/ampproject/amphtml/issues/4771)), then styling the link for the current page (bold, underline, etc, as in the Medium and Polymer examples) is already possible.

So the only feature needed here is the ability to, on load, trigger scrolling along the x-axis, in order to bring the menu item corresponding to the current page fully into view. Is that right?

**Comment by ericlindley-g** [comment]
FYI: given that the general ability to swipe-to-scroll is supported with `<amp-carousel type="carousel">`, the only outstanding item seems to be the ability to select an item in the carousel to be in view on page load. 

Likely something to enable with the binding protocol, but may be worth incorporating as a feature of `<amp-carousel>` directly, with an attribute like `index` that takes numerical values

cc/ @camelburrito @choumx @dvoytenko

**Comment by cramforce** [comment]
The binding work is for changing stuff at runtime. It won't even be allowed to make changes at page load time. This will need need to be added as a (very reasonable) feature to `amp-carousel`.

**Comment by eike-hass** [comment]
@ericlindley-g our current use case would be a navigation that consists of "classical" page links and anchor links on the same page. For the anchor links we would like to highlight the corresponding link on user scroll.

**Comment by ericlindley-g** [comment]
@eike-hass Ah, I see—thanks for clarifying. As the user scrolls down the page, the scrollable menu anchors to the top of the viewport, and as new sections come into view, the corresponding link to those sections is scrolled-to and highlighted in the menu. For this I think we'd need the bind protocol to trigger the "goto" behavior described in https://github.com/ampproject/amphtml/issues/5210, except for `amp-carousel[type="carousel"]`
