### ISSUE TITLE
Incapsula CDN adds analytics javascript to pages, breaks validation

### ISSUE THREAD

**Issue by weeblr** [ampproject/amphtml#5051]
As per @cramforce request, opening a new issue: one of our users reported validation issue on AMP pages. Turns out they are using Imperva Incapsula CDN, which adds a piece of javascript for tracking to all pages:
https://monosnap.com/file/YEGachNyT5bYelENvdJa3HgFrzyvdu

Should be noted that:
- I opened a support request with Incapsula 24hrs ago, no response yet
- user excluded URLs ending with /amp from caching, and that fixed the problem. Of a/this  prevents caching and b/ URL exclusion is only available on paid account

Most users have no clue why their pages do not vallidate, and when informed, some cannot disable caching per URL because they are on free accounts, so they must disable CDN entirely. That's an obstacle to adoption I think.

As a follow up to previous issue #2380 , maybe it would be good to contact CDN providers and inform them about the necessity to leave AMP pages alone and not inject stuff in them, like Cloudflare did?

Rgds

**Comment by weeblr** [comment]
FYI, Incapsuala replied to a question on tweeter with : 

> can be fixed upon request, working on automatic solution.

They should post here when automatic solution is active.

**Comment by Incaprules** [comment]
Thanks for opening this issue, I'm from Incapsula, will update here once we have a resolution

**Comment by kp25** [comment]
@Incaprules @rudygalfi what is the status of the issue ? any resolution so far ?

**Comment by ZigZagIL** [comment]
The solution was evaluated by a few customers, and is now being deployed globally.

**Comment by adelinamart** [comment]
What's the latest update on this? Thanks

**Comment by Incaprules** [comment]
Incapsula supports AMP pages for all websites since Nov 2016

**Comment by weeblr** [comment]
I assume this can be closed. So I am closing it.
