### ISSUE TITLE
Generic binding protocol (amp-bind)

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#5059]
Tracking issue for developing a generic binding protocol to enable a set inter-element behaviors in AMP

Potential behaviors:
- Carousel thumbnails update main carousel index (and visa-versa)
- [Tabbed UI](https://github.com/ampproject/amphtml/issues/4771)
- [Image thumbnails update main image display](https://github.com/ampproject/amphtml/issues/4500)
- [Toggle video src](https://github.com/ampproject/amphtml/issues/4852#issuecomment-245675169)
- Form field dependencies
- [Smart buttons](https://github.com/ampproject/amphtml/issues/3459)
- Element tap expands non-contiguous `<amp-accordion>`
- Composible `<amp-lightbox>` groups
- Tooltips
- Trigger CSS class and value changes on scroll (sticky headers, animations on scroll)
- Trigger attribute change on window width
- Custom video controls

cc/ @rudygalfi @cramforce @dvoytenko @aghassemi

**Comment by choumx** [comment]
Closing in favor of #6199.
