### ISSUE TITLE
Intent to Implement: Support for Reddit Comment and Post Embeds

### ISSUE THREAD

**Issue by samiamorwas** [ampproject/amphtml#5062]
It would be nice to have a way to support Reddit Post and Comment embeds. These seem to rely on external scripts, similar to Twitter embeds.

I've taken an initial pass at this, bootstrapping an iframe with the correct script (again basically following the Twitter implementation). A Post embed defers to a third party, Embedly, which inserts another iframe, causing each embed to create two iframes. I'm not sure if this raises any performance concerns. Comment embeds appear to not rely on Embedly.

**Comment by samiamorwas** [comment]
Resolved in https://github.com/ampproject/amphtml/pull/5283

**Comment by cramforce** [comment]
@samiamorwas are you affiliated with Reddit in any way? While this is totally not required to contribute this embed, it would be good to know.

**Comment by samiamorwas** [comment]
@cramforce I am not. My company is trying to get 100% AMP support for our articles, and Reddit embeds are just one of the last pieces of content that seem to be unsupported.

Someone from Reddit might have the knowledge to implement this in a better manner, so if there's anyone associated with them working on this project, it would be great to hear their thoughts.

**Comment by cramforce** [comment]
Great. @jmadler FYI. Maybe you could at let Reddit know and see if they want to pitch in or take on long term maintenance since @samiamorwas did all the work already.

**Comment by adelinamart** [comment]
@jmadler any updates here? Thanks

**Comment by jridgewell** [comment]
This can be closed, right?

**Comment by ericlindley-g** [comment]
Closing, but please re-open as needed
