### ISSUE TITLE
"How It Works" page misuses blockquote for h2

### ISSUE THREAD

**Issue by tabatkins** [ampproject/amphtml#507]
On <https://www.ampproject.org/how-it-works/>, the subheadings ("The page you are currently reading is an AMP HTML document.", "AMP HTML loves CSS!", etc) are, for some strange reason, marked up with `<blockquote>` rather than `<h2>`.  These are clearly headings, not pullquotes.

**Comment by cramforce** [comment]
Pushing fix.
