### ISSUE TITLE
Validator error when using custom URI schemes for href and data-share-endpoint

### ISSUE THREAD

**Issue by SergeySulzhenko** [ampproject/amphtml#5071]
This issue about custom url schemes, similar to  #4242, #4094 and #4784;

The validator throws the following error when a share link to Telegram app. Same error with links to Twitter app and intent:// scheme.

    Invalid URL protocol 'tg:' for attribute 'href' in tag 'a'.
    Invalid URL protocol 'twitter:' for attribute 'href' in tag 'a'.
    Invalid URL protocol 'intent:' for attribute 'href' in tag 'a'.

The issue can be reproduced by simply testing the following links in the validator:
`<a href="tg://msg?text=https%3A%2F%2Fvalidator.ampproject.org">AMP Validator</a>`

`<a href="twitter://post?message=https%3A%2F%2Fvalidator.ampproject.org">AMP Validator</a>`

`<a href="intent://post?message=https%3A%2F%2Fvalidator.ampproject.org#Intent;scheme=twitter;end">AMP Validator</a>`

This also applies to data-share-endpoint in amp-social-share component.

Is it possible to add to these schemes in the whitelist like other (fb-messenger::, whatsapp:, viber: and so on)?

**Comment by Gregable** [comment]
Definitely.

**Comment by SergeySulzhenko** [comment]
It's great, thanks!

**Comment by Gregable** [comment]
These were added over in https://github.com/ampproject/amphtml/pull/5274 . Marking closed, but will take a little while longer to roll out.

**Comment by Gregable** [comment]
This is live everywhere.
