### ISSUE TITLE
Intent-to-implement: Cxense analytics additional channel attribute

### ISSUE THREAD

**Issue by SteinHDanCxense** [ampproject/amphtml#5077]
Why: Customer's of Cxense analytics want to be able to filter AMP traffic in the Cxense analytics dashboards.

What: The coming pull request is adding a custom parameter that indicates that that particular analytics event came from an AMP page.

A CLA was signed for the initial implementation of Cxense analytics, so that should still be valid.

**Comment by avimehta** [comment]
merged.
