### ISSUE TITLE
Carousel - Slidescroll: has jitters on Linux

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#5092]
Visit http://ampskrish.herokuapp.com/test/manual/amp-slidescroll.amp.html in Chrome or Firefox on desktop. Enable the experiment and navigate between couple of slides.

On Chrome, notice there are jitters before the slide settles: (see video [here](https://screencast.googleplex.com/cast/NTEyMzY2ODM4NDQxNTc0NHwyZmNkNWJkZi04Yg))
On Firefox, the jitters never stop (see video [here]
(https://screencast.googleplex.com/cast/NTk2ODM5NTU3Mjg3MTE2OHxiYjdkNjY3ZS02Mg))

/cc @ericlindley-g

**Comment by ericlindley-g** [comment]
Can't repro—are you able to repro consistently? What OS are you on?

**Comment by sriramkrish85** [comment]
Cant repro at all!??? lets check versions

Chrome: Version 53.0.2785.116 (64-bit)
FF: 48.0.2

OS X - el capitan - 10.11.6 (15G31)

**Comment by aghassemi** [comment]
Interesting, seems to be Linux-only, can't repro on my Mac either with same Chrome/FF versions (well don't have Windows to test, will do later at home). It's been a long time since I've seen OS specific bugs like this :) anyway Desktop and Linux only probably makes this low priority.

**Comment by ericlindley-g** [comment]
Chrome: 52.0.2743.116
FF:  48.0
OS X - el capitan - 10.11.6

Lower priority, but still good to fix

**Comment by sriramkrish85** [comment]
Not sure what to fix! but yeah good to track this.

**Comment by camelburrito** [comment]
fixed ny #5435
