### ISSUE TITLE
AMP carousel improvements - The size of pictures not loading properly after rotation

### ISSUE THREAD

**Issue by gkamasheva** [ampproject/amphtml#5093]
## Short description of your issue:
The size of pictures is bigger then size of screen. It observed after rotation.  (landscape).

## How do we reproduce the issue?

1. Open Chrome Browser
2.  Enable "amp-slidescroll" and "amp-scrollable-carousel" experiments at https://cdn.ampproject.org/experiments.html
3. Open page that use amp-carousel on the AMP cache - go to cdn.ampproject.org/c/s/diversao.terra.com.br/amp/gente/ator-domingos-montagner-some-no-rio-sao-francisco,1afa977bf1fe49affbbe5fab0b859124d4i8mxrx.html
4.  Find  component on the page 
5. Tap on a photo from carousel.
6. Observe the size of photo after rotation.

## What browsers are affected?
Device: Galaxy S6 (OS version 6.0.1, Chrome Browser)

**Comment by sriramkrish85** [comment]
@gkamasheva - I see its working as intended (respecting aspect ratio). Also this is the same behavior without the experiment as well. Let me know if that is not the case.
