### ISSUE TITLE
Carousel arrows flash when scrolling down 

### ISSUE THREAD

**Issue by corvusinaloeCMENA** [ampproject/amphtml#5094]
Please walk through the following steps for reporting an issue about AMP:

 When scrolling down to the carousel arrow flashes once. If the user scrolls up and then back down the flashing happens again. 

URL used: cdn.ampproject.org/c/www.mundodeportivo.com/elotromundo/actualidad/20160915/41312869196/tiziana-cantone-italia-suicidio-video-porno-ex

1. Enable "amp-slidescroll" and "amp-scrollable-carousel" experiments at https://cdn.ampproject.org/experiments.html
2. Go to cdn.ampproject.org/c/www.mundodeportivo.com/elotromundo/actualidad/20160915/41312869196/tiziana-cantone-italia-suicidio-video-porno-ex
3. Scroll down at the bottom of the page to find the carousel
4. Review the arrow when scrolling 

Samsung Galaxy S5 Lolipop Chrome 52.0.27

**Comment by gkamasheva** [comment]
Same issue was observed for Galaxy Nexus (OS version 4.0.4, Chrome browser 42.0.2311.111)

**Comment by corvusinaloeCMENA** [comment]
Same issue found on:
Samsung Galaxy S5 Lolipop Stock  2.1.34

**Comment by sriramkrish85** [comment]
this is WAI - it acts a cue that this is a carousel and will stay till there is a better UX solution for this.
@ericlindley-g - could we work to get a better solution.

**Comment by ericlindley-g** [comment]
We have designs for a better solution for a UX update for the carousel at large. Stop-gap is to show the arrows for longer, tracked [here](https://github.com/ampproject/amphtml/issues/3840) (I believe @sriramkrish85 and @abeck000 can just run through a few different options to find the right timing for now. 3 sec might be a good starting place)

**Comment by ericlindley-g** [comment]
Closing, since this is tracked elsewhere
