### ISSUE TITLE
AMP carousel improvements - Observed two photos on the one slide after rotation (landscape orientation).

### ISSUE THREAD

**Issue by gkamasheva** [ampproject/amphtml#5096]
## Short description of your issue:
The Carousel does not rotate properly. Observed two photos on the one slide after rotation (see observed links).

## How do we reproduce the issue?
1. Open Chrome Browser
Enable "amp-slidescroll" and "amp-scrollable-carousel" experiments at https://cdn.ampproject.org/experiments.html
2. Open page that use amp-carousel on the AMP cache - go to cdn.ampproject.org/c/s/diversao.terra.com.br/amp/gente/ator-domingos-montagner-some-no-rio-sao-francisco,1afa977bf1fe49affbbe5fab0b859124d4i8mxrx.html
3. Find component on the page
4. Tap on a photo from carousel.
5. Swipe some slides back and forth 
6. Rotate screen and observe a picture. 

## What browsers are affected?
Device: Galaxy S6 (OS version 6.0.1, Chrome Browser)

**Comment by gkamasheva** [comment]
Same issue was observed for Galaxy Nexus (OS version 4.0.4, Chrome, Stock browser) but for portrait orientation

**Comment by corvusinaloeCMENA** [comment]
Same issue observed for Samsung Galaxy 5 Lolipop AGSA 6.5.5.21

**Comment by gkamasheva** [comment]
Same issue was observed for Galaxy Nexus (OS version 4.1.2, Chrome AGSA browsers)

**Comment by gkamasheva** [comment]
Same issue was observed for Samsung Galaxy S4 GT-I9500 (OS version 4.4.2, Chrome browser)

**Comment by corvusinaloeCMENA** [comment]
Same behavior present on Nexus 6P Nougat Chrome  51.0.27

**Comment by corvusinaloeCMENA** [comment]
Same behavior present on Nexus 6P Nougat AGSA 6.5.21
