### ISSUE TITLE
When scrolling left on the carousel, it gets stuck. 

### ISSUE THREAD

**Issue by corvusinaloeCMENA** [ampproject/amphtml#5098]
User has to tap twice on the left arrow to go back to the first option displayed, it gets stuck on the first try. 
URL used: cdn.ampproject.org/c/www.mundodeportivo.com/elotromundo/actualidad/20160915/41312869196/tiziana-cantone-italia-suicidio-video-porno-ex

1.Enable "amp-slidescroll" and "amp-scrollable-carousel" experiments at https://cdn.ampproject.org/experiments.html
2.Go to cdn.ampproject.org/c/www.mundodeportivo.com/elotromundo/actualidad/20160915/41312869196/tiziana-cantone-italia-suicidio-video-porno-ex
3.Scroll down at the bottom of the page to find the carousel
4.Inside the carousel tap on the right arrow to go to the second option and then tap on the left one. (the user has to tap twice)

Samsung Galaxy S5 Chrome 52.0.27

**Comment by corvusinaloeCMENA** [comment]
Same issue found on:
Samsung Galaxy S5 Lolipop Stock 2.1.34

**Comment by sriramkrish85** [comment]
fixed by #4982 and #5085

**Comment by ericlindley-g** [comment]
This is fixed on my Moto X — @sriramkrish85 , can you confirm this is fixed on Samsung devices?

**Comment by sriramkrish85** [comment]
This should be fixed now - please re-open if that is not the case
