### ISSUE TITLE
Linking to other pages

### ISSUE THREAD

**Issue by bryanburgers** [ampproject/amphtml#510]
Let's say I'm on a page `/article-1/amp`. This is the AMP-enabled page that corresponds to `/article-1`. On this page, I want to link to the second article.

From the AMP page, should I be linking to `/article-2/amp` or `/article-2`?

Or maybe the more general question is this: if the user follows a link, will they stay in AMP-world, or will a link from an AMP-enabled page typically lose the benefits of the AMP-embedder?

**Comment by cramforce** [comment]
This is a decision of the AMP embedder. By default that link just links wherever it links :)

**Comment by jmadler** [comment]
"embedder" in this case referring to the user-agent (i.e. browser), native app (i.e. Twitter), or web app (i.e. Google Search).

We should still clarify linking in the docs.  Our guidance should be to link to the canonical, whatever URL that may be.
