### ISSUE TITLE
AMP carousel improvements - The arrows are observed not for all slides of carousel

### ISSUE THREAD

**Issue by gkamasheva** [ampproject/amphtml#5101]
## Short description of your issue:

The arrows are observed not for all slides of carousel
## Short description of your issue:

The arrows are observed not for all slides of carousel (portrait and landscape orientations). See observed links.
## How do we reproduce the issue?
1. Open Stock Browser
2. Enable "amp-slidescroll" and "amp-scrollable-carousel" experiments at https://cdn.ampproject.org/experiments.html
3. Go to cdn.ampproject.org/c/s/diversao.terra.com.br/amp/gente/ator-domingos-montagner-some-no-rio-sao-francisco,1afa977bf1fe49affbbe5fab0b859124d4i8mxrx.html
4. Find component on the page
5. Observe the slide of carousel (see observed links).
6. Swipe some slides back and forth.
## What browsers are affected?

Galaxy Nexus (OS version 4.0.4, Stock  browser 4.0.4.-299849)

**Comment by sriramkrish85** [comment]
@gkamasheva - can you be more specific, You will not see arrows if there are no slides to navigate to in that particular direction. If this is not the case please attach some screenshots of possible.

**Comment by gkamasheva** [comment]
I can see arrows only on the 1, 3,5,7 slides

**Comment by sriramkrish85** [comment]
if you can upload a video and link it here would be great. Yeah feel free to send me an email.

**Comment by gkamasheva** [comment]
Same issue was observed for Galaxy Nexus (OS version 4.1.2, Stock)

**Comment by gkamasheva** [comment]
I can't do it here, my manager sad that I can't do it here because it is public place.

**Comment by sriramkrish85** [comment]
works fine on nexus 5 for me will get a samsung device and test.

**Comment by camelburrito** [comment]
This should have been fixed by the classlist polyfill change that went in couple of weeks ago.
