### ISSUE TITLE
AMP carousel improvements -  The slides in carousel are switching while scrolling down the page.

### ISSUE THREAD

**Issue by gkamasheva** [ampproject/amphtml#5103]
## Short description of your issue:
 The slides in carousel are switching while scrolling down the page.

## How do we reproduce the issue?
1. Open AGSA Browser
2. Enable "amp-slidescroll" and "amp-scrollable-carousel" experiments at https://cdn.ampproject.org/experiments.html
3. Go to www.usatoday.com
4. Find carousel on the page
5. Scroll page up and down.
6. Observe carousel  switching.

What browsers are affected?
Device: Galaxy S6 (OS version 6.0.1, Agsa Browser)

**Comment by sriramkrish85** [comment]
@gkamasheva - may be they have autoplay turned on? I tried on some usa today pages (the main site did not have a carousel). Please re-open if you think this is a bug.
