### ISSUE TITLE
Missing arrows for AMP Carousel on iOS

### ISSUE THREAD

**Issue by corvusinaloeCMENA** [ampproject/amphtml#5107]
When scrolling up and down the arrows for the image carousel only flash, but they do not remain displayed on the screen. Also when interacting with the carousel (swiping) the arrows are not displayed.

URL used: cdn.ampproject.org/c/s/9to5mac.com/2016/09/14/ios-10-how-to-hate-pressing-the-home-button-to-unlock-change-is-setting-on-touch-id-iphones-ipads/amp/

1.Enable "amp-slidescroll" and "amp-scrollable-carousel" experiments at https://cdn.ampproject.org/experiments.html
2.Go to cdn.ampproject.org/c/s/9to5mac.com/2016/09/14/ios-10-how-to-hate-pressing-the-home-button-to-unlock-change-is-setting-on-touch-id-iphones-ipads/amp/
3.Scroll down to find the carousel
4. On the carousel, scroll between images. 

Expected: The arrows should appear to hint the user that it is a carousel. 

Iphone 6s iOS9 Safari 9

**Comment by corvusinaloeCMENA** [comment]
Same issue found on Iphone 6s iOS9 Chrome 52.0.27

**Comment by sriramkrish85** [comment]
Working as intended.

**Comment by alex-moreno** [comment]
is it a bug, or can we make the arrows to be displayed? Is not just a bug in iphone, it happens in android too.

**Comment by alex-moreno** [comment]
what do you mean that works as intended @sriramkrish85 

Thanks.

**Comment by sriramkrish85** [comment]
You can use the controls attribute to make the arrows permanent . Else they will flash and disappear as a cue to indicate that this is a carousel

**Comment by alex-moreno** [comment]
Is there any specific attribute on those controls that I have to use?  I
couldn't find that in the docs.

Thanks a lot

**Comment by sriramkrish85** [comment]
The name of the attribute is 'controls' it is documented as the first thing under 'attributes' here https://github.com/ampproject/amphtml/blob/master/extensions/amp-carousel/amp-carousel.md

**Comment by alex-moreno** [comment]
right, sorry, I am an id*&**, I saw that page, but I couldn't understand
exactly how the attribute works. I'll open a PR with and example around
that  update that in case

just in case someone else reads this, it is as simple as:

<amp-carousel width="<?php echo $dims['width'] ?>" height="<?php echo
$dims['height'] ?>"
 controls
 layout="responsive" type="slides">

Simply controls being there should make that work.

**Comment by shekankode** [comment]
The amp-carousel navigation arrows are not visible all the time in mobile but on the desktop, arrows are always displayed unless only a single child is present (according to the official docs) https://www.ampproject.org/docs/reference/components/amp-carousel#controls-(optional). This is a bug which needs to be fixed.
