### ISSUE TITLE
iGSA swiping all the images in a carousel takes you to the next AMP article 

### ISSUE THREAD

**Issue by corvusinaloeCMENA** [ampproject/amphtml#5110]
When swiping in an image carousel contained on an AMP Carousel (lots of articles) and swiping right after the last image, the browser switches to the next AMP article. 
URL used: http://www.usatoday.com/story/sports/mlb/columnist/bob-nightengale/2016/09/19/tim-tebow-mets-workout/90702882/

1.Open Igsa and Enable "amp-slidescroll" and "amp-scrollable-carousel" experiments at https://cdn.ampproject.org/experiments.html
2.Go to http://www.usatoday.com/story/sports/mlb/columnist/bob-nightengale/2016/09/19/tim-tebow-mets-workout/90702882/
3.Scroll down to find the carousel
4. On the carousel, scroll right all the images until the end
5. See the result 

Expected: The arrows should appear to hint the user that it is a carousel.

Iphone 6s iOS9 IGSA 19.0.1

**Comment by sriramkrish85** [comment]
This is working as intended!

CC @ericlindley-g @rudygalfi
