### ISSUE TITLE
iGSA Ads take too much time to load on the carousel 

### ISSUE THREAD

**Issue by corvusinaloeCMENA** [ampproject/amphtml#5111]
ADS take a lot of time to load on AMP 
URL used: http://www.usatoday.com/story/sports/mlb/columnist/bob-nightengale/2016/09/19/tim-tebow-mets-workout/90702882/

1.Open Igsa and Enable "amp-slidescroll" and "amp-scrollable-carousel" experiments at https://cdn.ampproject.org/experiments.html
2.Go to http://www.usatoday.com/story/sports/mlb/columnist/bob-nightengale/2016/09/19/tim-tebow-mets-workout/90702882/
3.Scroll down to find the carousel
4. On the carousel, scroll right all the images until the end
5. See the result

Iphone 6s iOS9 IGSA 19.0.1

**Comment by ericlindley-g** [comment]
cc/ @sriramkrish85 @jasti

**Comment by jridgewell** [comment]
I wonder if this is because of https://github.com/ampproject/amphtml/pull/4081?

/cc @aghassemi

**Comment by aghassemi** [comment]
@jridgewell Don't think #4081 can affect this. Carousel does its own `scheduleLayout` for +/- 1 slides. Maybe instead of +/- 1 slide, carousel should honour the value of `renderOutsideViewport` (interpreting the value as number of slides) when scheduling its children. @sriramkrish85

**Comment by adelinamart** [comment]
Referenced issue is closed. Is this still reproducible? Thanks

**Comment by jridgewell** [comment]
Still happening.

**Comment by lannka** [comment]
The URL is now http://amp.usatoday.com/story/90702882/
I can no longer reproduce the issue. The ads load fine in the carousel. 
My test device is iPhone 6 / iOS10 / iGSA v24.1

Let me know if anyone can still see the problem.
