### ISSUE TITLE
JS error on document-click

### ISSUE THREAD

**Issue by sriramkrish85** [ampproject/amphtml#5113]
document-click.js:166 Uncaught TypeError: Cannot read property 'toUpperCase' of undefinedgetElementByTagNameFromEventShadowDomPath_ @ document-click.js:166onDocumentElementCapturedClick_ @ document-click.js:184handle_ @ document-click.js:152
cast_sender.js:89[0.687s] [yt.mdx.remote] LocalScreenService: Initializing with []

**Comment by keithwrightbos** [comment]
I will fix this as part of PR #5053

**Comment by keithwrightbos** [comment]
This was fixed in PR #5053 and can be closed.
