### ISSUE TITLE
DFP Ad's via Glade

### ISSUE THREAD

**Issue by RonanDrouglazet** [ampproject/amphtml#5116]
## Short description of your issue:

Hi guys,

Since a few weeks, more and more publishers are complaining about Teads's tag served by DFP on AMP who does not deliver anymore…

I took a look and saw that the ad was rendering in a double iframe. Then I saw in different other posts on internet people complaining about the exact same issue: It looks like a new version of DFP's ad rendering was released. Something called Glade (not sure about the wordings)

I looked on the DFP side and it seems that Glade is used everywhere now. So every ad, already served by a cross domain iframe (AMP) is now wrapped by a second cross domain iframe ...

So currently, we does not have access to the AMP context into it, and we can't go outside this context. Which prevent us to serve ads on AMP through DFP tags.

Do we have a way to not use Glade or any other way to get rid of that double safeFrame ? 
## How do we reproduce the issue?

load an Ad with amp-ad doubleclick tag
## What browsers are affected?

All browsers
## Which AMP version is affected?

Don't know exactly, since few weeks

Best,

Ronan

**Comment by mlb7687** [comment]
Hey Ronan,

Glade (now publicly called GPT Light: https://developers.google.com/doubleclick-gpt/gpt_light) is a new light weight ad tag. We currently have a way to opt out of using GPT Light while the issue with accessing AMP context is not solved. See here: https://github.com/ampproject/amphtml/blob/master/ads/google/doubleclick.md#temporary-use-of-usesamedomainrenderinguntildeprecated

GPT Light has been running in an A/B experiment fashion for some time (50% of requests were going to it since about May), but just a few weeks ago we ramped up to 90% which explains the increase in issues you have seen.

We are actively working on getting the AMP context APIs available in creatives loaded in nested iframes, at which point we will look to disable the opt out.

**Comment by jridgewell** [comment]
Should we be opting-in instead?

**Comment by mlb7687** [comment]
We originally noticed the issue when Glade was at a low traffic fraction (maybe 5%?), so the fact that we didn't catch these issues at 50% surprised me. At this point, it seems a bit late to make it opt-in. We are actively working on making AMP context available in cross domain iframes because it also blocks full A4A launch.

**Comment by RonanDrouglazet** [comment]
Hi @mlb7687 and thanks for your answer.

Ok we can use `useSameDomainRenderingUntilDeprecated` . 
We haven't done anything until now with this parameters because your README explicitly says 

>  This attribute will be deprecated by the end of August 2016, when the GPT Light tag will become the default, and all ads will always be rendered inside a second cross domain iframe

And ask to all of our AMP/DFP publisher to update our tag is very painful for everyone.
Did you have any ETA for this feature ? How can we be alerted ?

maybe by this idea ? --> https://github.com/ampproject/amphtml/issues/5160

**Comment by jasti** [comment]
Hey @RonanDrouglazet , if you are part of the @ampproject/ads team, we will announce the feature as soon as it's available.

@mlb7687, correct me but the publisher actually doesn't have to update the tag. It is Teads that will need to, if they'd like their creatives to have access to context APIs. 

FYI @michaelkleber

**Comment by michaelkleber** [comment]
@RonanDrouglazet Is your goal just access to the AMP window.context object, or something more than that?  What specific parts of window.context do you need?  In particular, will #3019 address everything you care about?

**Comment by michaelkleber** [comment]
(FYI @nekodo for postMessage API progress)

**Comment by mlb7687** [comment]
Also @glevitzky who is working on the JS Wrapper to tie the postMessage API together
@RonanDrouglazet, glevitzky is working on the last component of this. Perhaps he can put together a better timeline and answer questions related to how the API will look.

**Comment by schanami** [comment]
Any updates on the attribute "useSameDomainRenderingUntilDeprecated" being deprecated?  Much appreciated if you could update the date this attribute will be deprecated.

**Comment by keithwrightbos** [comment]
@bradfrizzell is working on a replacement API now (see i2i #6829)

**Comment by schanami** [comment]
@keithwrightbos Thanks for the update!  We are working with a vendor that requires us to use  the useSameDomainRenderingUntilDeprecated attribute.  Will using this attribute have any negative impact on other vendors running through AMP?

**Comment by keithwrightbos** [comment]
I'm sorry what do you mean by "vendors" in this context?  The biggest
impact is that the solution in progress will have a slightly different API
causing any creatives currently using the context library to be modified.

**Comment by schanami** [comment]
No worries, "vendors" as in 3rd party ad networks

**Comment by mlb7687** [comment]
The update to the tag will be that the opt out would no longer be respected after an acceptable period of time to change over. Instead, creatives will be expected to use the API @bradfrizzell is working on.

**Comment by harquail** [comment]
We'd also appreciate an update to the deprecation date in the doubleclick document: "This attribute will be deprecated by the end of August 2016, when the GPT Light tag will become the default, and all ads will always be rendered inside a second cross domain iframe".  This has caused confusion for some of our other publishers as well, who were concerned about using a deprecated feature.  Yieldmo will of course update to use the new API once it is available 😺 .

**Comment by jasti** [comment]
Please follow updates on https://github.com/ampproject/amphtml/issues/6829
