### ISSUE TITLE
<amp-app-banner> doesn't appear on Samsung or Nexus devices

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#5117]
Reported by test team

@mkhatib , can you take a look? What devices have you tested with? (I'm following up with QA to find out what devices in particular they were using—Nexus 6 was one)

I'm able to see the banner on Moto X

**Comment by ericlindley-g** [comment]
Issue reported on:

Nexus 6 (Marshmallow)
Samsung S5 (Lollipop)
Samsung Galaxy Note 5 (Marshmallow)
Samsung S4 (KitKat)

**Comment by ansalgado-gcorp** [comment]
Any updates to this issue?

**Comment by mkhatib** [comment]
@ericlindley-g were these reported on a non-Chrome browser? It is WAI if these are on a Chrome browser. Chrome supports a native app-banner so we don't show AMPs' in these cases. 

If this is not on Chrome, what browser was this on?

**Comment by ericlindley-g** [comment]
@mkhatib This issue is happening even inside of the viewer, where we should be showing the banner even in the Chrome + Android. I also believe it's in non-Chrome + Android combinations, but @ansalgado-gcorp can verify

**Comment by ansalgado-gcorp** [comment]
The issue is present on Chrome.

**Comment by ansalgado-gcorp** [comment]
Eric, any update on this.  We want to continue testing, and without the feature showing, we can't sign off on it.

**Comment by ericlindley-g** [comment]
Thanks @ansalgado-gcorp — to clarify, have you only tested this in Chrome, or have you tried other browsers on Android as well?

Also, can you try with a motorola device? I am able to get the banner on Moto X, on Chrome at the [...viewer.html link](https://amp-mk-3.herokuapp.com/examples/viewer.html), and if you can as well it could help narrow in on the issue.

@mkhatib — have you been able to look into this?

**Comment by mkhatib** [comment]
Also, make sure you're on the `https version of the viewer link, otherwise it will fail.

I just tried on Nexus 6P Chrome and got it working on `https`.

**Comment by ansalgado-gcorp** [comment]
I can confirm that the feature is working correctly on port 443(https).  
This is to update the bug and request clarification if the feature will be available to users accessing on port 80 rather that 443.

**Comment by mkhatib** [comment]
For Android, since we do a fetch to get the `manifest.json` file, this is done only if the link provided was on `https`. So this would work for document served on `http` as long as the manifest link was `https`. Meaning on `http` pages with relative manifest link, this wouldn't work.

**Comment by ericlindley-g** [comment]
Sounds like we should require an absolute https link for the manifest file to avoid any issues—will include in validation rules
