### ISSUE TITLE
Scroll inertia on iOS

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#5125]
I'm seeing people reporting that in viewers (Google Search, News), the scroll inertia feels off on iOS.

Is there anything we can do about that?
@dvoytenko

**Comment by dvoytenko** [comment]
@cramforce Any other pointers? Is it in doc-swipe carousel or blue links? The scroll momentum is definitely different due to `overflow-scroll: touch`. But it's not janky and appears to perform well.

**Comment by jridgewell** [comment]
> But it's not janky and appears to perform well.

Jank isn't the issue. It's not the normal page weight.

**Comment by michrome** [comment]
e.g. https://news.ycombinator.com/item?id=12542171

**Comment by cramforce** [comment]
Right, people perceive the page as "too light".

**Comment by dvoytenko** [comment]
Well, yeah, unfortunately iOS uses different algo for `body` and `div` scrolling.

**Comment by cramforce** [comment]
Is there a webkit bug for this?

**Comment by jridgewell** [comment]
Root issue is https://bugs.webkit.org/show_bug.cgi?id=149264. This prevents us from doing anything about Google Search's Viewer.

I'm not sure if this affects the Google Search App or News.

**Comment by dvoytenko** [comment]
Basically, it's this: https://medium.com/@dvoytenko/amp-ios-scrolling-and-position-fixed-b854a5a0d451

**Comment by cramforce** [comment]
The Google iOS search app should not have this issue.

What I meant is to ask webkit to allow setting scroll inertia via some
proprietary CSS attribute. That is likely easier for them, than fixing the
fundamental bug.

**Comment by dvoytenko** [comment]
Filed https://bugs.webkit.org/show_bug.cgi?id=162499

But I'd expect any iOS WebView to have the same problem as well. I believe the difference is specifically in how iOS Safari overrides root scroller.

**Comment by jridgewell** [comment]
@dvoytenko: Can you add to our Browser Bugs spreadsheet?

**Comment by dvoytenko** [comment]
@jridgewell Done.

**Comment by adelinamart** [comment]
Did anyone followed on the external bug lately? Thanks

**Comment by cramforce** [comment]
@adelinamart Uhm, yes :)

**Comment by adelinamart** [comment]
the referenced bug seems to be fixed :) @dvoytenko can we close this also? Thanks

**Comment by jridgewell** [comment]
Will waiting on the [clarification](https://bugs.webkit.org/show_bug.cgi?id=162499#c5).

**Comment by dvoytenko** [comment]
I did independently confirmed that this appears to be the direction that's being taken by iOS Safari.
