### ISSUE TITLE
Swipe to scroll over inline video initiates playback

### ISSUE THREAD

**Issue by bradleysepos** [ampproject/amphtml#5127]
Initiating a scroll via swipe on iOS Safari will play a video if the initial touch location is over a video element. Behavior is similar to the old school, "onmousedown is not onclick" issue.
## How do we reproduce the issue?
1. Visit news.google.com on a mobile device
2. Select a news item containing video
3. Initiate scrolling by swiping over the video
4. Unrequested silly thing will begin to play
## What browsers are affected?

Verified using Safari for iOS 9.3.x and 10.0.x on iPhone 6 and iPad 4th generation.
## Which AMP version is affected?

1474310684773

**Comment by jridgewell** [comment]
I thought we solved this with `overflow-touch: scroll`?

**Comment by bradleysepos** [comment]
CNN's article videos exhibited the behavior but none of them are loading at all for me at the moment (striked-out play button).

When was the supposed fix committed? If it was earlier than today, then perhaps I'm running into an issue with Safari caching the old code.

**Comment by jridgewell** [comment]
It's been in since the original demo launch.

**Comment by bradleysepos** [comment]
Ah. I've had this issue for a couple weeks at minimum, just now getting around to reporting.

**Comment by dvoytenko** [comment]
@aghassemi, could anything we recently changed have such an effect? Generally, I've no idea how we could even accomplish this. I don't think touchstart or touchmove would not be accepted for video playback...

**Comment by aghassemi** [comment]
Nothing I can think of. I can reproduce however. touch must start within the "play icon" safari overlays on the video and when lifting the finger ip, it must still be on the "play icon" but regardless of how much time/movement happened in between the `touchstart` and `touchend`, it considers it a tap and plays the video.

**Comment by bradleysepos** [comment]
This example exhibits the behavior regardless of finger position relative to the play icon: https://news.google.com/news/ampviewer?caurl=https%3A%2F%2Fwww.washingtonpost.com%2Famphtml%2Fnews%2Fmorning-mix%2Fwp%2F2016%2F09%2F21%2Fprotests-break-out-in-charlotte-after-police-fatally-shoot-man-they-say-wielded-firearm%2F#pt0-649308

**Comment by aghassemi** [comment]
yikes, yeah that WP video is an iframe to a custom player and touching anywhere starts the video.

Doesn't happen on WP's non-AMP page with the same player. Looks like we are somehow introducing this behaviour in AMP. Will report when I figure it out.

**Comment by aghassemi** [comment]
I can easily repro this in iOS without AMP using just a `video` tag. http://jsfiddle.net/aejhcyor/2/ 

I will file a bug and follow up with webkit/apple folks.

**Comment by aghassemi** [comment]
For reference: https://bugs.webkit.org/show_bug.cgi?id=162562

**Comment by ericlindley-g** [comment]
@aghassemi — is there anything that AMP can feasibly do to fix, or does a fix rely on webkit?

**Comment by aghassemi** [comment]
@ericlindley-g yes, work we need to do for https://github.com/ampproject/amphtml/issues/7030 will fix this issue.
