### ISSUE TITLE
<amp-iframe>: default frameborder to 0

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#5140]
For amp iframe, set frameborder to 0 if not specified by author.

Default UA css has value of 2px for iframe border, pretty much in vast majority of cases we want border to be 0 so that should be the default.

For instance, http://abcnews.go.com/amp/Politics/donald-trump-jrs-skittles-tweet-highlights-key-campaign/story?id=42218871 is not setting frameborder and you can notice the 2px gray left border on the video.

Also we should set `box-sizing` to `border-box` on the `iframe` inside `amp-iframe` otherwise setting any border will cause the `iframe` overflow the parent `i-amp-scroll-container` creating a few pixel scroll slack.

@sriramkrish85 Loosely related to #5137 but not the cause of #5137

**Comment by sriramkrish85** [comment]
I think this is the cause for the problem.

**Comment by aghassemi** [comment]
it is not

**Comment by sriramkrish85** [comment]
after syncing offline - @aghassemi confirmed it is :)

**Comment by cramforce** [comment]
I'm hugely in favor of this totally non-backward compatible change!
