### ISSUE TITLE
iOS Safari in viewer context not rendering on landscape

### ISSUE THREAD

**Issue by ansalgado-gcorp** [ampproject/amphtml#5141]
## Short description of your issue: 
When page is refreshed while on landscape mode, in viewer context does not render banner

## How do we reproduce the issue?
Test URL needs to be accessed with phone in landscape position.

1. Open Safari
2. Turn phone to landscape mode
3. Follow URL: https://amp-mk-3.herokuapp.com/examples/viewer.html

## What browsers are affected?
Safari

All browsers? Some specific browser? What device type?
iPhone (iOS 9)

**Comment by ansalgado-gcorp** [comment]
On Safari only.  Only a small portion of the banner shows at the bottom of the screen.  Task bar in the bottom does not allow user to tap on banner resource.

**Comment by ansalgado-gcorp** [comment]
Device: iPhone 5 
OS: iOS 9.2

**Comment by mkhatib** [comment]
This is a duplicate issue to #5239 - will work with @dvoytenko to figure out what is happening on that issue.
