### ISSUE TITLE
Adhesion ads render not aligned

### ISSUE THREAD

**Issue by dorzaidenberg** [ampproject/amphtml#5142]
Adhesion / sticky ads are rendering off centered.
Publisher needs to use a DFP creative wrapper with some hack stylesheet to put them in place

https://kansascity.relaymedia.com/amp/news/politics-government/article73988477.html?_rmversion=sticky

You can see the creative wrapper code fixing the alignement of the sticky ad:

<style>
body, #ad_wrapper {margin:0; padding:0;}
</style>

Start by deleting everything above this including this sentence :)

![0919-amp-adhesion-image-before-change-phone-capture](https://cloud.githubusercontent.com/assets/22310227/18721485/bf7b4938-7ffe-11e6-9cda-a4fc9120a1c9.JPG)

**Comment by jasti** [comment]
@zhouyx would you be able to take a look please? @mlb7687 as FYI incase this might be related to the recent Glade issue with px padding.

**Comment by mlb7687** [comment]
@dorzaidenberg, can you try testing this again with a fresh cache? I notice that the creative has a wrapper which had a bug that should be fixed as of a few hours ago. If you are using an old version of GPT Light (Glade), I might expect to see this. I have not been able to reproduce with the current production version of GPT Light.

**Comment by dorzaidenberg** [comment]
Trying, will keep you posted

**Comment by dorzaidenberg** [comment]
Looks like this issue is resolved!

**Comment by mlb7687** [comment]
Glad to hear it! Closing this issue.

**Comment by jpettitt** [comment]
It was an ad code issue.

**Comment by zhouyx** [comment]
Thanks @dorzaidenberg @mlb7687 for the update
