### ISSUE TITLE
Consider adding `box-sizing: border-box !important` to `-amp-fill-content`

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#5147]
Related to https://github.com/ampproject/amphtml/pull/5143 but risker so it should be tested properly. If we endup doing this, we can remove  `amp-iframe > iframe {box-sizing: border-box !important;}` introduced in https://github.com/ampproject/amphtml/pull/5143

Technically adding `box-sizing: border-box !important` to `-amp-fill-content` should only _affect_ cases where the element with `-amp-fill-content` has:
1- default padding/border from UA's builtin css (like iframe)
2- AMP css has set padding/border on it
3- page author has custom CSS for `amp-x > -amp-fill-content` or `amp-x > InnerElement` which sets padding/border.

If there are cases like above, they should already be behaving strangely as the element with `-amp-fill-content` should be overflowing its parent causing small scrolling slack (like the one found in #5137)

@cramforce @sriramkrish85 @jridgewell

**Comment by sriramkrish85** [comment]
> 2- AMP css has set padding/border on it
unlikely but good to check if we do

> 3- page author has custom CSS for amp-x > -amp-fill-content or amp-x > InnerElement which sets padding/border.
` amp-x > -amp-fill-content` is an invalid AMP
`amp-x > InnerElement ` this is valid in certain scenarios like `amp-accordion > H3`, `amp-sidebar > ~nav1` etc

**Comment by aghassemi** [comment]
Actually closing this one, we can reopen if it comes up again.

**Comment by josh-feinstein** [comment]
`!important` is disallowed in AMP style-custom elements. It will influence styling, but you will fail AMP validation.
