### ISSUE TITLE
Allow style of the amp-sticky-ad close button.

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#5152]
We used to be able to style the close button  - 
![image](https://cloud.githubusercontent.com/assets/524856/18730122/7ead3a28-8009-11e6-9632-dcdd6318d9b0.png) 

We had a nice close button the same size and the one adchoices uses and we had it to the right of the ad only moving up if the page was 320px wide using media queries.  It looked nice, it worked.

The latest code push seems to have broken all that by putting `!important` all over the place

Now we've got this ugly looking button we can't position and can't style.

![image](https://cloud.githubusercontent.com/assets/524856/18730194/df843586-8009-11e6-814f-b6b65eb6fac6.png)

It's looks terrible.   Why was this change made? It's pure UX, it's one thing to dictate that a close button must exist but to dictate how it looks?  This is just ugly.

**Comment by zhouyx** [comment]
changed by #5015. @mkhatib do we want `!important`

**Comment by jpettitt** [comment]
FYI the code does even prevent the button from being hidden - 
```
background: none;
    border: none;
```
makes it go away (please don't make them !important too)

I'd love to be able have more control so I can do things like this 

![image](https://cloud.githubusercontent.com/assets/524856/18730555/d2351a42-800b-11e6-8bfd-12e157d59c8c.png)

**Comment by jasti** [comment]
@jpettitt Separate from this breaking change, I do believe that AMP should have control of the size and placement of the close button. If you think this close button is ugly, let's discuss how to make it better. 
I can vet your suggestion with UX experts to see if we can implement it. Do you have other suggestions?

**Comment by jpettitt** [comment]
Hmm, may  ask why?  That's getting well outside the performance aspects of amp and into dictating site UX.  Things like close buttons are a very site specific feature.  

We did a few things in styling this - we made the amp-sticky-ad itself frame the ad unit and not  be full width.  We moved the close button to the right of the and frame rather than above except where the viewport was 320px when we used a media query to push the close button to the position you normally have it.  We also downsized it to match the ad-choices standard close button.

![image](https://cloud.githubusercontent.com/assets/524856/18735204/f03b2c5a-8030-11e6-9ad4-d8b1810af48d.png)

That's a bare minimum.

Beyond that it would be nice to be able to do things like

![image](https://cloud.githubusercontent.com/assets/524856/18735265/6d0c6ec4-8031-11e6-8a7d-40a577f5daad.png)

In the big picture I'm struggling to understand why AMP needs to control this.  Yes it makes sense to require a button. It's appearance is site UX and AMP seems to keep encroaching into UX decisions that have nothing to do with performance or even general usability (the width restriction on amp-sidebar is another example).   AMP has nothing to say about play buttons, allows styling of carousel button, allows arbitrary `amp-sidebar` triggers.  But for some reason this button is special?  Why? 

Should I be opening a discussion topic about the boundaries of AMP UX?  

Where there is an enforced UX decision at a minimum is should be explained, with supporting evidence, why it's better for users.  The more seemingly arbitrary UX choices AMP makes the less attractive it is and the more people start to question if it's really about performance or about Google imposing it's UX standards.

**Comment by mkhatib** [comment]
Sorry for the breaking change, I should've given it a bit more thought. Happy to roll this back if deemed necessary (defer to @dvoytenko @cramforce).

The reason I made this change is to try to avoid cases where the button is in-accessible to the user - either by on purpose abuse of hiding the close button (to not allow user to dismiss the sticky ad) or by accident (Small close button inaccessible on mobile). 

Admittedly there are of course many ways around this (you mentioned `transform` as one way). Not sure if it'll be possible to cover all cases. 

I think this is a really good discussion to have and whether these `!important` statements and whether it is possible to actually control this as needed.

**Comment by jpettitt** [comment]
Understood.  Personally I think it's going to be very hard to make the button such that it can't be removed.  With the current setting I could remove or visually change it with left:, `transform:, left:, margin:, background:, border: , opacity:, visibility:, display:` and probably a few more I can't think of right now.

Right now our prod version is this which I looks fine to me. 
![image](https://cloud.githubusercontent.com/assets/524856/18753373/f42a7c58-8099-11e6-8536-da4e37e5e7b7.png)

**Comment by dvoytenko** [comment]
@mkhatib I'd say we can live without `!important` here. Everyone is correct in saying that it's still too easy to hack the button off the screen.
