### ISSUE TITLE
amp-carousel autoplay not playing with 2 images

### ISSUE THREAD

**Issue by R3dRidle** [ampproject/amphtml#5164]
I am trying to implement an amp-carousel with autoplay. Yet it is not autoplaying.
I got the code from the examples.

Below is my code:

`<amp-carousel width="2000"
  height="403"
  layout="responsive"
  type="slides"
  autoplay
  delay="3500">
<amp-img src="http://www.webtondemo.nl/amptest/wp-content/uploads/WEBTON-belgie-01.jpg"
    width="2000"
    height="403"
    layout="responsive"></amp-img>
<amp-img src="http://www.webtondemo.nl/amptest/wp-content/uploads/WEBTON-belgie-02.jpg"
    width="2000"
    height="403"
    layout="responsive"></amp-img>
</amp-carousel>`

**Comment by R3dRidle** [comment]
Solved my issue by just adding more images, is there a minimum of images in the amp-carousel to have?

**Comment by sriramkrish85** [comment]
Yes - we need atleast 3 images for a loop and hence for autoplay. Will update the documentation.

**Comment by R3dRidle** [comment]
Shouldn't be 2 images possible too ?

**Comment by ericlindley-g** [comment]
It would be nice to support this. With 2 images we might just want to go back and forth (go right to second slide, return left to first slide, as opposed to looping in the same direction for carousels with 3+ slides)

**Comment by jpettitt** [comment]
+1 for wanting 2 images.  We're going to use this for the "alert bar" at the top of TV station sites which quite often only has 2 items.

**Comment by nainar** [comment]
### First Timers Only
We know figuring out the process for contributing to an open source project can be intimidating, so we created this issue as a way for you to learn the ropes.  (If you feel comfortable contributing to open source projects, please leave this issue for someone else.)

### What you will need to know
* Read up on the [amp-carousel markdown file](https://ampbyexample.com/components/amp-carousel/) to understand the basics of how the carousel works. You can also take a look at examples there. 

### Background
Autoplay looping should be enabled on 2 images to enable the same rich experience as >3 images. 

### The bug
Some of the files/functions you want to look at are:
- slidescroll.js - Particularly isLoopingEligible()
- base-slides.js

Some of the nuance will be in: Do you want to enable the same looping behaviour (i.e. proceed to the next slide?) or enable a special looping behaviour? (loop from slide 1 to slide 2 and then reverse loop to slide 1 from slide 2)

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.  (If you [join the AMP Project](https://goo.gl/forms/T65peVtfQfEoDWeD3) we'll be able to assign this issue to you after you've claimed it.)
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] [Sign the Contributor License Agreement](https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#contributor-license-agreement) before creating a Pull Request.  (If you are contributing code on behalf of a corporation start this process as early as possible.)
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork). 
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review).  Mention `closes Issue <this issue number>` in the description. I am happy to review the PR!
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

### Questions?
Feel free to ask questions on this bug.
If you have questions ask in this issue or on your Pull Request (if you've created one) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

**Comment by camelburrito** [comment]
The easiest way to do looping is to duplicate the 2 slides again making 4 slides in total and enable looping, but it might affect analytics and ads. 

A safe way to proceed with this is will be to special case autoplay for carousel with 2 slides and not touch looping

**Comment by nainar** [comment]
Let's go with the latter approach? Like you said much easier.

**Comment by cathyxz** [comment]
The duplicate slides approach may cause issues for lightbox because it will result in 4 thumbnail images in the lightbox gallery, and more breakage depending on when you actually insert the 4 slides, so +1 to special-casing.

**Comment by jridgewell** [comment]
I don't see why we can't autoplay with 2 images. Let's fix that instead of duplicating.

**Comment by nainar** [comment]
I'll take this on.
