### ISSUE TITLE
cleanup amp-app-banner experiment

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#5166]
@mkhatib can you confirm this is still in experiment?

**Comment by mkhatib** [comment]
Yes this is still an experiment. @ericlindley-g - do we have anything blocking launching this? (Other than docs, I'll send a PR by EOD).

**Comment by ericlindley-g** [comment]
The test team ran through this on ios, and has that blocker before they can test in Android (you're already taking a look, I think). We just have whatever comes up in that process, validation rules, docs, and one last Eng review before we can launch

**Comment by adelinamart** [comment]
@ericlindley-g @erwinmombay can this be cleaned? thanks
