### ISSUE TITLE
IntersectionObserver: Does it need every scroll event?

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#5173]
Right now, we listen two two events in IntersectionObservers:

1. Scroll event. This fires a _lot_.
2. "Change" event, aka every few scrolls or a resize event.

Do we need to keep listening to every `scroll` event if we get the `change` event?

/cc @sriramkrish85, @avimehta, @jasti

**Comment by sriramkrish85** [comment]
this should fire only when the element is in viewport. you mean to say that we fire IO for every scroll event?

Also dont we restrict the no of postmessages to 10 per second?

**Comment by jridgewell** [comment]
While in viewport, we get every scroll event.

> Also dont we restrict the no of postmessages to 10 per second?

Yup. Which goes to say, why do we need to get every scroll event when we can only accept one every 100ms. If we just listen for `changed`, we'll still get one every ~60ms.

**Comment by sriramkrish85** [comment]
what do you mean by `change` event? isnt that only on certain inputs?

**Comment by jridgewell** [comment]
It's a [throttled scroll](https://github.com/ampproject/amphtml/blob/master/src/service/viewport-impl.js#L617-L635) event and every [resize](https://github.com/ampproject/amphtml/blob/master/src/service/viewport-impl.js#L651-L660) event.

**Comment by cramforce** [comment]
For the ads use case we need to update within 100ms. That is basically the only restriction we have.

**Comment by jridgewell** [comment]
Looking into it, `changed` won't fire until after the scroll has stopped completely. That's no use for us.
