### ISSUE TITLE
Consolidate `fill` CSS code we have to be the same.

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#5177]
We have three different versions of fill css: 
 `.-amp-layout-fill` is different than `.-amp-fill-content` which is different than `.-amp-layout-size-defined .-amp-fill-content`

Some of them use position absolute, and some of them use width, height 100%. The ones using width, height, also don't set `box-sizing` to `border-box` that can cause overflows.

We need to consolidate all these into a single `fill` logic and test different cases. We may want to put whatever fix we come up with under an experiment and let is soak for a while.

Issues:
https://github.com/ampproject/amphtml/issues/5147
https://github.com/ampproject/amphtml/issues/4947
https://github.com/ampproject/amphtml/issues/5178

PRs:
https://github.com/ampproject/amphtml/pull/5143
https://github.com/ampproject/amphtml/pull/4977
https://github.com/ampproject/amphtml/pull/5176
https://github.com/ampproject/amphtml/pull/5170

**Comment by adelinamart** [comment]
@aghassemi is this something we are looking into? Thanks

**Comment by aghassemi** [comment]
not actively, but good to keep it. It is somewhat a high-risk change to make.

**Comment by adelinamart** [comment]
What are the risks and who else should be involved in this decision? Thanks

**Comment by bpaduch** [comment]
Just keeping this on the radar because the "fill" layout for amp-fit-text doesn't work as expected per  (https://github.com/ampproject/amphtml/issues/4947).  I wanted to add a "fill" example in the docs but didn't work as I expected.
