### ISSUE TITLE
-amp-fill-content height 100% breaks ad alignment in some cases.

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#5178]
This is a really weird edge case. I'm not sure whose bug it is, or even if it is a bug, it may just be a weird feature interaction.

We've been seeing this issue with `amp-sticky-ad`

![image](https://cloud.githubusercontent.com/assets/524856/18762854/89ad73c8-80bf-11e6-8f18-0057fb3f07ca.png)

Here is what was happening -

There is code (outside out control) in the ad iframe created by DFP to position the ad creative `div` centered horizontally and vertically.

```
{
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
}
```

That would be fine if the `iframe` was 50px tall but it sort-of isn’t.  Something in the ad creative is adding to the height I’ve seen 4px and 9px added, although by the time I look at the dom whatever element caused it has gone away - tracking code maybe? Not clear why the dom thinks the `iframe` page is still the larger size.)  When it does happen it's not 100% of the time.

That too would be fine because we have `height=50` on the `amp-ad` and in turn on the `iframe`.

Except that `-amp-fill-content` css sets the height to 100%.

Now for some reason, and only on a phone not in emulation, that causes the positioning code to use the larger height value, I’ve seen 54 px and 59px.  It doesn’t change the display size on the rendered page which is still 50px tall.

Net result is the ad is centered vertically in a slightly taller window leaving a space at the top and cropping the bottom.

I’ve overridden the height: 100% with a height: 50px and it now seems to be working consistently on our pages.

Seen on chrome and safari on iPhone.  Unable to reproduce in emulation on desktop.

**Comment by jasti** [comment]
@lannka @glevitzky PTAL

**Comment by jpettitt** [comment]
Update: Seeing the same issue on 300x250's - setting `height: 100%` definitely seems to be an issue.  The same fix (explicitly setting the unit height in CSS) worked.

**Comment by kevinlisota** [comment]
We are seeing this when using the sticky-ad on iPhone when version 1.0 of the sticky-ad script is used.

Everything appears normal in chrome iPhone emulation mode on desktop, but on the phone, the bottom of the ad is cropped.

We are using no custom styles, so the defaults styles of adding 4px padding/margin seems to be causing this. Not sure why the 4px was added in the new version of the script.

Reverting to 0.1 version of the sticky-ad script seems to resolve it.

**Comment by zhouyx** [comment]
@kevinlisota Do you still have this issue? Also You should be able to customize the padding height through CSS.

**Comment by jasti** [comment]
Closing since we've haven't heard back and there haven't been any reports in the last 2 months. 
Please reopen if necessary.
