### ISSUE TITLE
If JS doesn't load (On the train) then page is invisible

### ISSUE THREAD

**Issue by kevinmarks** [ampproject/amphtml#518]
that whole 
```
<style>body {opacity: 0}</style><noscript><style>body {opacity: 1}</style></noscript>
```
thing fails badly if js is turned on, but doesn't load.

**Comment by dvoytenko** [comment]
Yeah. We are in the process of redesigning this part. Stay amped!

**Comment by cramforce** [comment]
@dvoytenko Do you want to share your doc?

**Comment by dvoytenko** [comment]
It's documented here: #323.

**Comment by cramforce** [comment]
We'll track it there
