### ISSUE TITLE
Docs: Spec isn't rendering markdown links or code properly in some sections

### ISSUE THREAD

**Issue by kevinSuttle** [ampproject/amphtml#5186]
https://www.ampproject.org/docs/reference/spec.html
vs https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#boilerplate

> `contain the [AMP boilerplate code ('head > style[amp-boilerplate]' and 'noscript > style[amp-boilerplate]')](amp-boilerplate.md) in their head tag. 🔗`

===
https://www.ampproject.org/docs/reference/spec.html#common-attributes
vs https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#common-attributes

> The value for the syntax is a simple domain specific language of the form:
> `[sourcecode] eventName:targetId[.methodName[(arg1=value, arg2=value)]] [/sourcecode]`

**Comment by bpaduch** [comment]
cc: @pbakaus 

This appears to be an issue where if no language is specified for a codeblock, the grow sdk doesn't render the block as code format.  Happens in other [docs](https://www.ampproject.org/docs/reference/extended/amp-access.html#access-url-variables) that I found that I'll fix in this bug.
