### ISSUE TITLE
Lazy loading not working horizontally

### ISSUE THREAD

**Issue by Bobby0707** [ampproject/amphtml#5187]
Hi, I'm having an issue when I want to create a horizontally scrollable kind of image gallery. The issue is that the lazy loading doesen't seem to work and only the images which are in the viewport are loaded. I tried this vertically and it worked, but horizontally just won't. If I resize the browser however the images are loading, so maybe you could help me with this. 

## How do we reproduce the issue?

https://jsbin.com/lezuxaluje/edit?html,output
https://gist.github.com/anonymous/ba752a72cc721432acbba6516d699f18

When you scroll it horizontally, the images will not load, if you resize the browser, the images will load, only the images within the viewport seems to load.

## What browsers are affected?

I tested this on Google Chrome, Android device and iOS device.

## Which AMP version is affected?

AMP ⚡ HTML – Version 1474310684773

**Comment by dvoytenko** [comment]
@Bobby0707 `overflow: auto|scroll` are not allowed. Please use `<amp-carousel>` element instead.

**Comment by jridgewell** [comment]
Ha, I thought this was the `<amp-carousel>` ad's `prefer-viewability-over-views` issue reported in Slack. Whoops.
