### ISSUE TITLE
AMP-AD sandbox iframe

### ISSUE THREAD

**Issue by oliverfernandez** [ampproject/amphtml#5189]
When the AMP-AD tag creates a 3p IFRAME, I noticed that this IFRAME doesn't have any kind of sandbox. Among other things, this means that the content inside the IFRAME can do a top level navigation. Something like:

window.top.location.href = '...'

Since this is a behaviour that I have detected in ad networks, and considering that AMP documents can be loaded in Google search page, is there a reason why the 3P IFRAME is not sandboxed?

**Comment by cramforce** [comment]
As long as Safari doesn't support `allow-popups-to-escape-sandbox` it isn't really feasible to apply a sandbox to ads.

On the Google search page, ads are only loaded when articles are in full screen.

Chrome is currently launching an intervention where 3p iframes cannot navigate the top window without a user action. That will solve the issue.

**Comment by mchr3k** [comment]
@cramforce - Safari added support for allow-popups-to-escape-sandbox in 2017: https://bugs.webkit.org/show_bug.cgi?id=158875. The Chrome intervention only solves top level redirects for Chrome users.

Perhaps this issue should be re-opened?
