### ISSUE TITLE
Amp-carousel: delay load of amp-ad 

### ISSUE THREAD

**Issue by eyobebisrat** [ampproject/amphtml#5194]
In our app we have a (slides) amp carousel where we regularly embed amp-ads. There currently isn't a way to delay the ad load until it is scrolled in view in carousel. Setting the  data-loading-strategy attribute to "prefer-viewability-over-views" doesn’t seem to work in this case.

You can see this issue when you add an amp-ad to a list of elements in a amp-carousel so that to a amp-ad is not in initial viewport. The ad is still loaded even with the data-loading-strategy attribute set.

**Comment by sriramkrish85** [comment]
@eyobebisrat are you using `amp-carousel type="slides"` ?

**Comment by jridgewell** [comment]
Ah, here's the one from Slack.

/to @cramforce, @dvoytenko

**Comment by eyobebisrat** [comment]
@sriramkrish85 That is correct.

**Comment by dvoytenko** [comment]
@sriramkrish85 Is this fixed in scrollable carousel?

**Comment by sriramkrish85** [comment]
Yes ,  this is fixed With the slidescroll experiment

**Comment by dvoytenko** [comment]
@sriramkrish85 Cool. I'm assigning it to you then. Please close when scrollable carousel is launched.

**Comment by eyobebisrat** [comment]
Any ETA we can hope for launch of scrollable carousel?

**Comment by sriramkrish85** [comment]
@eyobebisrat end of this week. ill update the progress here #5199

**Comment by sriramkrish85** [comment]
The new scrollable carousel has been launched now  and hence you should not see this issue any longer
