### ISSUE TITLE
amp-ad inside amp-carousel overlays content in Safari

### ISSUE THREAD

**Issue by poscar** [ampproject/amphtml#5195]
## Short description of your issue:

In Safari, `amp-ad` components placed inside an `amp-carousel` overlay the content of the carousel.

### Example:
http://output.jsbin.com/yolopuqeve

- Observe the carousel at the bottom of the page, and change slides.

### Result:
Broken in `Safari 9.0.3`, ads display on top of content slides.

### Expected Result:
Work in all browsers.

### Screenshot:
<img width="665" alt="screen shot 2016-09-23 at 1 29 17 pm" src="https://cloud.githubusercontent.com/assets/128726/18795271/c6799458-8191-11e6-862f-52236e354a5d.png">

## What browsers are affected?

**Safari** both mobile (`iPhone 6 + iOS10`) and desktop (`9.0.3`).

## Which AMP version is affected?

`Powered by AMP ⚡ HTML – Version 1474310684773`

## Comments

I noticed `z-index: 0` is set on my ad figure as I move through the carousel. If I manually set this to `z-index: -1`, it displays correctly. I believe `amp-carousel` setting `z-index: 0` is causing the `amp-ad` iframe to overlay the content.

**Comment by sriramkrish85** [comment]
@poscar this will be fixed in our new implementation launching in a week (or 2). If you want to try it out you can opt in to our dev channel (https://cdn.ampproject.org/experiments.html) or try out the
`amp-slidescroll` experiment. Thanks for taking time to report the bug!

**Comment by poscar** [comment]
I could still reproduce with only `dev-channel` enabled, but confirmed I can't reproduce the issue with *BOTH*: `dev-channel` and `amp-slidescroll` enabled in https://cdn.ampproject.org/experiments.html.

**Comment by jridgewell** [comment]
@sriramkrish85 misspoke. You only need to enable the `amp-slidescroll` experiment, as it's in both prod and canary.

**Comment by sriramkrish85** [comment]
The new scrollable carousel has been launched now  and hence you should not see this issue any longer
