### ISSUE TITLE
Performance audits of amp.css and v0.js

### ISSUE THREAD

**Issue by kevinSuttle** [ampproject/amphtml#5203]
## How do we reproduce the issue?

Please post a public URL and ideally post a reduced test case. E.g. on jsbin.com that exhibits only your issue and nothing else.

1. Go to kevinsuttle.com
2. Open Chrome Devtools
3. Under Audits, check Network Utilization and Web Page Performance. 
4. Select Reload Page and Audit on Load

- Under **Network Utilzation: Leverage browser caching**, v0.js is mentioned as short-lived
- Under **Web Page Performance: Remove unused CSS rules**, amp.css is mostly unused on my site. Can we opt into it instead of having it fetched automatically?

## What browsers are affected?

> All browsers? Some specific browser? What device type?
Chrome 50.0.2661.86 (64-bit)
Mac OS 10.12
MacBook Pro (Retina, 15-inch, Early 2013)

## Which AMP version is affected?
Version 1474310684773

> Is this a new issue? Or was it always broken? Paste your AMP version. You can find it in the browser dev tools.

Version 1474310684773

**Comment by cramforce** [comment]
The CSS is tiny and not worth optimizing. The JS lifetime is a known trade off. When @jridgewell's foreign-fetch ServiceWorker work lands, this will be fixed for Chrome users.

**Comment by kevinSuttle** [comment]
Right on. Thanks.
