### ISSUE TITLE
Only allow variable CLIENT_ID replaced in HTTPS URLs

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#5205]

**Comment by jpettitt** [comment]
Are we talking amp-analytics targets or is this related to #4078

**Comment by cramforce** [comment]
For `amp-analytics` this is not a change as it only allows HTTPS in the 1st place.

Yes, this would be for #4078.

But I think this is only one of multiple rules we may need.

**Comment by cramforce** [comment]
Duplicate of #4078
