### ISSUE TITLE
amp-mustache: Partial templates

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#5206]
Allow rendering partials inside a mustache template. For example this can be used like the following:

``` html
<!-- Somewhere in the document -->
<template type="amp-mustache" partial-id="my-template-1">
  {{name}}...{{#interests}}{{name}}{{/interests}}
</template>
```

The above could also be introduced as it's own element (e.g. `amp-mustache-partial`) if we'd like to avoid lookup. 

``` html
<form>
  <div submit-success>
    <template type="amp-mustache">
        {{>my-template-1}}
    </template>
  </div>
</form>
```

AMP probably needs to read that template and pass the partials dictionary to the mustache `render` call.

cc/ @dvoytenko

**Comment by dvoytenko** [comment]
@mkhatib Could you elaborate on why this is a good idea? Our goal is to ensure that an AMP document is not turned into a client-side rendering engine...

**Comment by mkhatib** [comment]
To avoid repetitive exact sections of template code. For example this [experimental example template is repeated for every product listing](https://github.com/ampproject/amphtml/pull/5214/files#diff-fffecb019d2cfacd424fe215abff4347R69) - 3 times in the example.

**Comment by adelinamart** [comment]
Does this still needs to be prioritized for this year? Thanks

**Comment by ericlindley-g** [comment]
Slotting as P3 for now — I've been interested in more opportunities to offer encapsulation/abstraction, and though we should be careful with this when dealing with dynamic content (as Dima points out), I wonder if there's something we can offer that will generalize to non-dynamic cases as well (?)
