### ISSUE TITLE
Capture and Send the Submitter button when submitting a form

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#5213]
By default in non-JS form submission the request will include `name=value` for the submit button that made the submit request.

We should introduce the same mechanism to allow use cases like:

``` python
if params['create']:
  create()
else if params['update']:
  update()
```

**Comment by mkhatib** [comment]
Ok so it seems the way this is mostly implemented is by listening to click `events` on different submit elements and recording that before the `submit` event go through.

This works well for clicking/tapping a specific `submit` button. Problem we need to think about is when the form is submitted by hitting the return. It seems browsers have inconsistencies of how they treat this. 

The way I think this should work as I mentioned, **the first visible/enabled submit button should be the submitter** when `return` key is pressed. 

Chrome, Firefox and Edge doesn't respect visibility and always choose the first submit button as the submitter - even if it's `display:none`. Safari and IE ignore invisible submit buttons (which I do believe is a better UX to follow in polyfiling it in `amp-form`).

**Comment by mkhatib** [comment]
Looks like Chrome is [following the standards](https://html.spec.whatwg.org/multipage/forms.html#implicit-submission).

**Comment by adelinamart** [comment]
Is this still at discussion level? Thanks

**Comment by mkhatib** [comment]
I'll close this for now. This was a suggestion to allow multiple-submit buttons be identified on the server. This first came out in need for implementing add-to-cart flows, we've made a lot of progress there.

cc/ @rudygalfi if this is still needed.
