### ISSUE TITLE
Polymer | HTML5 Web Components

### ISSUE THREAD

**Issue by cekvenich** [ampproject/amphtml#5216]
Hi,
Is there a mail list or forum to discuss?

My main question is Polymer or HTML5 Web Components - it appears that neither would work w/ AMP.  Both require at least some .js.

Also minor question, how do I make SPA (Single Page App) w/ AMP? 
Normally you 'ajax' load another and replace innerHTML or such.

Cheers,
Vic

**Comment by cramforce** [comment]
Polymer is not supported.
Over here we are building a SPA that displays AMP content https://github.com/ampproject/amp-publisher-sample/pull/52

There is a similar project under way for Polymer!

**Comment by cekvenich** [comment]
What about HTML5 Web Components ?
From http://developers.google.com/web
you have http://developers.google.com/web/fundamentals/primers/customelements

React is not a standard and Custom Elements are a ratified standard - news? 
As a developer, can I have a way to have a site that is both AMP when needed and Custom Elements?

**Comment by cramforce** [comment]
AMP will not support custom elements not published as an AMP extension.

**Comment by cekvenich** [comment]
Clearly cramforce. But you show
https://github.com/ampproject/amphtml/issues/5216#issuecomment-249472180
a path from react components
Is there a path from standard components?

**Comment by cramforce** [comment]
@cekvenich We're using React to build an app that loads AMP documents. We don't use React in AMP documents.

**Comment by choumx** [comment]
> Also minor question, how do I make SPA (Single Page App) w/ AMP? 
Normally you 'ajax' load another and replace innerHTML or such.

The PR above and `examples/pwa` in the `amphtml` repository both use Shadow DOM for rendering an AMP doc within an HTML doc (React is not necessary). Check out the code to see how it works.

**Comment by cekvenich** [comment]
Thx Chamoux - I don't see 'the PR above' ( I don't even know what PR is).
Second example:
https://github.com/ampproject/amphtml/blob/master/examples/pwa/pwa.html
I see, but you are using .js!
You can't use .js in AMP, so ... 

Plz help (so you know it's worth it as I do document PWA, ex: http://masons-foundation.org/en/s_home/webComp/comp1 ) I want to post example of data binding and SPA - just simple hello world.

**Comment by jridgewell** [comment]
PR means Pull Request. He's talking about https://github.com/ampproject/amp-publisher-sample/pull/52.

**Comment by cekvenich** [comment]
Thx jridgewell  - so it's the same link/repo.

And what about .js? They are using it. And they are talking about shadow dom - and the only way I know how to do that is .js. 
Here is the example I think both link to:
https://github.com/ampproject/amphtml/blob/master/examples/pwa/pwa.html
Notice: it has .js. 

So it's not AMP, is it or I'm missing some jump? help plz.

**Comment by jridgewell** [comment]
The web app isn't AMP. It _loads_ the AMP docs (through a iframe, shadow dom, etc).

**Comment by cekvenich** [comment]
OK, got it. thx.
