### ISSUE TITLE
AMP Project issue  on Safari browser

### ISSUE THREAD

**Issue by YoavRheims** [ampproject/amphtml#5217]
## Short description of your issue:

The office AMP website is broken on Safari browser. 

## How do we reproduce the issue?

Just go to https://www.ampproject.org on Safari for Windows (5.1.7). It was tested on desktop PC.

## Which AMP version is affected?

Version 1474310684773

## Screenshot

![amp-safari](https://cloud.githubusercontent.com/assets/4377522/18813924/abb68134-8313-11e6-9cd2-525ed0b0df3e.png)

**Comment by erwinmombay** [comment]
@YoavRheims you mind if i move this over to https://github.com/ampproject/docs ?

**Comment by YoavRheims** [comment]
@erwinmombay No problem, you should probably move it (I have no idea how to do it yet).

**Comment by erwinmombay** [comment]
@YoavRheims was just going to copy your text and refer to this original post 😸

**Comment by YoavRheims** [comment]
Oh, got it ;)
