### ISSUE TITLE
AMP sites have stopped following AMP rules – has there been a change?

### ISSUE THREAD

**Issue by JoeArizona** [ampproject/amphtml#5218]
Hi team,

I noticed this weekend that every publisher I looked at is no longer following the AMP rules. I don't know when this happened, but it's dramatically different from the last time I checked out AMP pages for examples.

- No one is putting `amp` or ⚡ (U+26A1) in the HTML start tag. That struck me as most odd because it doesn't cost them anything, and everyone was doing it a couple of months ago.

- There's a ton of third-party JS now, both inlined in the head and downloaded separately. For example, Mashable has JS from Optimizely, Outbrain, Connatix, jwplatform, IMA SDK from googleapis.com, and amz.mashcdn.com. [Link.](https://www.google.com/amp/mashable.com/2016/09/24/justin-bieber-german-club.amp?client=ms-android-verizon)

- There's a ton of non-AMP CSS now, both inlined in the head and downloaded separately. Yahoo even has a bunch of styles and scripts inlined in the body. [Link.
](https://www.google.com/amp/s/www.yahoo.com/amphtml/music/elon-musk-soon-tell-world-020409570.html?client=ms-android-verizon)

Every site I looked at was like this, which is so odd. Popular Science, Fox News, Daily Mail, etc. Just Google Justin Bieber, or Mars. I tried it both in Chrome 53 on an Galaxy S7 using the VT View Source app, and on desktop using the Nexus 5X emulator in Chrome Dev Tools.

As I said, this is a stark change, so I figured I must have missed a major memo. I've never seen any of these rules broken before – it's night and day. I can't find anything in the docs or blog about this, so I thought I'd ask here. Is there a testing phase underway? Is this being caused by intermediaries or CDNs?

(I thought about asking on Stack, but it seems pointless to ask questions there – they just get downvoted and/or deleted half the time., though maybe the AMP channel is different.)

**Comment by YoavRheims** [comment]
Hi,

I don't see the issues you are describing, both websites pass the AMP validation:

1. https://validator.ampproject.org/#url=http%3A%2F%2Fmashable.com%2F2016%2F09%2F24%2Fjustin-bieber-german-club.amp
2. https://validator.ampproject.org/#url=https%3A%2F%2Fwww.yahoo.com%2Famphtml%2Ftech%2Felon-musk-soon-tell-world-020409570.html

Are you actually sure you are checking the AMP version or the normal HTML website?

**Comment by JoeArizona** [comment]
Well I see some amp traces in the source, like amp modules, in addition to all the other JS and CSS. It's possible the source I'm looking at isn't the source that was actually delivered to the browser, though this seems more likely with the Android view source app than in Dev Tools. Let me do some digging. Should an AMP page URL return the AMP page to all requesting user agents, or is it going to be user agent specific?

**Comment by rudygalfi** [comment]
@JoeArizona The URLs you linked to (e.g. https://www.google.com/amp/mashable.com/2016/09/24/justin-bieber-german-club.amp?client=ms-android-verizon) are URLs of Google Search's "AMP viewer", which essentially iframes AMP pages. In this case, the AMP page is http://mashable.com/2016/09/24/justin-bieber-german-club.amp, which is a valid AMP.

**Comment by JoeArizona** [comment]
Thanks Rudy. I should've thought of that. I'm still confused by all the different JS files I was seeing – it doesn't look like Google's code, but I'll dig into it some more.
