### ISSUE TITLE
amp page error

### ISSUE THREAD

**Issue by saurabhdixit123456** [ampproject/amphtml#5220]
hello 
i am using https://wordpress.org/plugins/amp/
 its  show Prohibited or invalid use of HTML Tag in google how we solve this issue
https://www.1mg.com/articles/how-to-effectively-handle-work-related-stress/amp/

**Comment by KempfCreative** [comment]
You have an invalid property on line 283 of that HTML document: kid_directed_site="false". 

Validating these issues is possible using a variety of automated techniques, but for one-off checks, you could try and use https://validator.ampproject.org/.

**Comment by saurabhdixit123456** [comment]
how can we solve this issue

**Comment by cramforce** [comment]
Try to find what is adding the `kid_directed_site` attribute and make it stop.

**Comment by saurabhdixit123456** [comment]
thanks
