### ISSUE TITLE
amp-img not loading outside viewport

### ISSUE THREAD

**Issue by sreekanthjnayar** [ampproject/amphtml#5226]
I had created a webpage which shows some images arranged as cards side by side using the amp-img tags. The image cards are wrapped in a horizontally scrollable container. I am using the normal amp-img tag and arranging them side by side. The images rendered outside the viewport doesn't load (checked the network tab for the image requests and could see that these images outside the viewport has not been requested). Is this something to do with the lazy loading of images in amp-img. Ideally they should be loaded, at least when they are scrolled into viewport.

**Comment by sriramkrish85** [comment]
@sreekanthjnayar - you will need to use `amp-carousel` if you need a scrollable pane elements in in it. This component would take care of loading resources for you. 

CC @dvoytenko

**Comment by shekankode** [comment]
Facing the same issue, for the same arrangement of the image cards in a container in a scrollable div and as seen in the network tab there are no image requests for images outside the viewport hence they are loaded on my webpage . Using carousel is the only option for such arrangement

**Comment by sreekanthjnayar** [comment]
Yes, that's how this issue can be rectified.

Sreekanth
