### ISSUE TITLE
CORS/REST Mustache

### ISSUE THREAD

**Issue by cekvenich** [ampproject/amphtml#5227]
Is there an example of Mustache AMP doing a REST/CORS call?

Or front end data binding?

**Comment by dvoytenko** [comment]
@cekvenich Templates themselves do not execute CORS, but elements that use them could. For instance, `amp-list` executes a CORS endpoint before executing a template. Could you explain your use case a bit so that we can discuss a recommendation?

**Comment by cekvenich** [comment]
Thx. The use case would be generic Read/Write, like reading or writing to
firebase http://masons-foundation.org/en/s_home/160703_fb-hello/story or
any other REST/CORS. I want to do master detail/click on a row and edit and
save the data.

**Comment by mkhatib** [comment]
@cekvenich If you can write the read/write functionality as a `<form>` submission, you should be able to render response you get from firebase in `submit-success` template. See [forms.amp.html](https://github.com/ampproject/amphtml/blob/master/examples/forms.amp.html#L106) example.

`amp-list` would be the automatic `read` part without user-interaction (a form submission).

**Comment by adelinamart** [comment]
@cekvenich anything else needed to be answered here?

**Comment by puppetmaster3** [comment]
Thx for help. I now don't recall my issue. Please close
