### ISSUE TITLE
Sometimes AMP element is missing implementation in the connected callback

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#5230]
```
Request 
https://cdn.ampproject.org/v/www.forbes.com/sites/brianmazique/2016/09/25/wwe-clash-of-champions-2016-winners-grades-and-top-performances/amp/?amp_js_v=5  
Referrer    
https://cdn.ampproject.org/v/www.forbes.com/sites/brianmazique/2016/09/25/wwe-clash-of-champions-2016-winners-grades-and-top-performances/amp/?amp_js_v=5 
User agent  
Mozilla/5.0 (Linux; Android 6.0.1; SM-G920P Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.124 Mobile Safari/537.36 
Service 
default-cdn-1p-canary 
Version 
default-cdn-1p-canary-1474310684773 
```

Here is the error log from canary

```
TypeError: Cannot read property 'isDeclaredFixed' of undefined
at amp-ad.f.isDeclaredFixed (v0.js:214)
at sf.f.measure (v0.js:182)
at jg (https://cdn.ampproject.org/rtv/001474310684773/v0.js:246)
at h (https://cdn.ampproject.org/rtv/001474310684773/v0.js:254)
at pf.setState (v0.js:176)
at Vf (https://cdn.ampproject.org/rtv/001474310684773/v0.js:242)
at Ed.Cd (https://cdn.ampproject.org/rtv/001474310684773/v0.js:232)
at Ed.ta (https://cdn.ampproject.org/rtv/001474310684773/v0.js:80)
at Ed.td (https://cdn.ampproject.org/rtv/001474310684773/v0.js:80)
at (https://cdn.ampproject.org/rtv/001474310684773/v0.js:39)
```

Other instances of the same error:
- "TypeError: Cannot read property 'isDeclaredFixed' of undefined"
- "TypeError: Cannot set property 'layout_' of undefined"
- ""

**Comment by jridgewell** [comment]
/cc @dvoytenko 

This looks to be an issue with `Viewport` (`f` is the viewport) not having a `FixedLayer` (the `undefined`). It's erroring [here](https://github.com/ampproject/amphtml/blob/master/src/service/viewport-impl.js#L327-L329).

**Comment by jridgewell** [comment]
Either that, or it's erroring because `Viewport` is `undefined`. But I think it's `FixedLayer` that is.

**Comment by dvoytenko** [comment]
@jridgewell I can't see either of these happening: `fixedLayer` is created in the constructor - it can't be `undefined`. How many errors of this kind are we seeing?

**Comment by dvoytenko** [comment]
And it's definitely `fixedLayer_`, not `viewport` - that code is not inlined (which I'm a bit surprised by).

**Comment by sriramkrish85** [comment]
@dvoytenko - this is one or 2 occurrences in the past 2 days on canary.

**Comment by dvoytenko** [comment]
Hmm. Should we go 5% and see if there are more logs on this?

**Comment by sriramkrish85** [comment]
I think we should , it would not hurt us. Also given that we have 2 weeks of code on canary , it would be useful to find if there are more errors

**Comment by dvoytenko** [comment]
Do we have new info on this?

@jridgewell What's "Nessy"?

**Comment by erwinmombay** [comment]
@dvoytenko it refers to the loch ness monster which is elusive and might not be even real

**Comment by erwinmombay** [comment]
these errors seem to happen to some random method/property every week and it always seems to be on samsung browser + phone combo

**Comment by dvoytenko** [comment]
@erwinmombay Got it. Personally would have preferred "ragnarok" :)

**Comment by erwinmombay** [comment]
@dvoytenko @jridgewell i would have preferred the [chupacabra](https://en.wikipedia.org/wiki/Chupacabra)

**Comment by adelinamart** [comment]
@dvoytenko @jridgewell is this still happening? Thanks

**Comment by jridgewell** [comment]
Nessy bugs are unsolvable. RIP `nessy` label.
