### ISSUE TITLE
<amp-live-list> deep-linking

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#5236]
Tracking bug for the request to deep link to specific <amp-live-list> entries.

Currently, developers have a few different ways to implement this (including a site.com/liveblog?e=entryID mechanic for the link). This bug is to track a) ways to make the use-case easier (maybe trivially easy) to implement in AMP, and b) better documentation for existing live blog deep-linking methods

cc/ @erwinmombay

**Comment by adelinamart** [comment]
@ericlindley-g is this FR prioritized?

**Comment by ericlindley-g** [comment]
It's not in the OKRs, so I think "New FRs" is the right place, though I've assigned a priority to it.

**Comment by aghassemi** [comment]
This should be doable with `#anchor` if each entry of the `live list` has it.
