### ISSUE TITLE
invalid CSS required to pass validation - -ms-animation

### ISSUE THREAD

**Issue by estelle** [ampproject/amphtml#5245]
## How do we reproduce the issue?

The validator needs to be updated to not require unneeded and invalid CSS.

My attempt to update the amp-by-example files to reduce the bytes sent to the user was unsuccessful at 

amp-by-example/src/30_Advanced/Image_Galleries_with_amp-carousel.html

-ms-animation has never been supported or necessary. -moz-animation and -o-animation aren't needed (though at one point they were supported). -webkit-animation is still needed for the UC browser and older android browser.

The changes below aren't accepted by the validator.

ORIGINAL:
`<style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>`

RECOMMENDED CHANGE:
`<style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps-end) both;animation:-amp-start 8s steps-end both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;animation:none}</style></noscript>`

COMMENTS: 
animation: name 0s steps(1,end) 1 0s normal both 
is the equivalent of 
animation: name step-end both
as iteration count defaults to 1, delay defaults to 0s, duration defaults to 0s, and direction defaults to normal. Using the shorthand, you get the defaults for undeclared values. step-end is a shorter way of writing steps(1, end)
We should be encouraging efficient use of JavaScript. The validator requires inefficient, unnecessary and even incorrect CSS.

**Comment by estelle** [comment]
Note that some of the code above disappeared as I didn't escape the "&lt;"

**Comment by Gregable** [comment]
Updated to add some escaping. @dvoytenko for the boilerplate.

**Comment by cramforce** [comment]
![LGTM](https://camo.githubusercontent.com/c13eeb81b1485ccc0d2b248f19360c7ba2419167/687474703a2f2f6a756e6b796172642e64616d6f776d6f772e636f6d2f353633)

**Comment by cramforce** [comment]
I'm all for a smaller boilerplate if it gives sufficient coverage. Since the worst case here is FOIC (right?), it is fine if we loose some older Fx coverage.

**Comment by Gregable** [comment]
Does it make sense to reduce coverage only to save a few tens of bytes?

**Comment by estelle** [comment]
-ms-animation was never supported. According to http://caniuse.com/#search=css%20animation, -o- was never necessary either.

**Comment by cramforce** [comment]
The primary benefit it less eye sore, I guess :)

**Comment by estelle** [comment]
@cramforce I think the other benefit is not demonstrating such code. People learn from project code examples. Wouldn't want anyone to think declaring all those animations and keyframes was necessary

**Comment by Gregable** [comment]
Sure, if something was never supported it's a no brainer. I'm asking about the cases that are there for older browsers. We could remove -ms-animation and leave -moz-animation / -o-animation, for example.

**Comment by cramforce** [comment]
@sriramkrish85 Could you re-do your original testing with the new snippet provided by @estelle?

**Comment by estelle** [comment]
IMHO, Best option is to allow but not require -o-, -moz- or even -webkit-

**Comment by dvoytenko** [comment]
This needs to be reviewed by @sriramkrish85 - he did a very extensive checking on all browsers.

**Comment by sriramkrish85** [comment]
@estelle thanks for filing the bug, ill take a look at this.

**Comment by sriramkrish85** [comment]
i think `-ms-animation` is needed for IE 10 per this- https://msdn.microsoft.com/library/hh673530.aspx

**Comment by camelburrito** [comment]
Dup of https://github.com/ampproject/amphtml/issues/6666
