### ISSUE TITLE
change lgtm/approval/needs review process

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#5246]
With the native github review system in place, one of the proposals we have is to get rid of the NEEDS REVIEW and LGTM labels moving forward and add a WIP label. This means everything by default "Needs a Review" unless "WIP" is added and of course LGTM is handled by the native github approval.

cc @ampproject/a4a @ampproject/amp-html-master-mergers @bpaduch @ampproject/docs @rudygalfi @ericlindley-g

**Comment by sriramkrish85** [comment]
+1  (yay no fiddling with labels :))

**Comment by cramforce** [comment]
Is it possible to filter PRs by approval status? Or even other stuff such as pending comments? By URL param?

**Comment by sriramkrish85** [comment]
@cramforce isn't PR state always binary (merged/not merged), do we really need approval status?

**Comment by cramforce** [comment]
Definitely not always binary. I keep forgetting to merge my LGed PRs :)

**Comment by erwinmombay** [comment]
@cramforce I'm having a hell of a time figuring out where the approval field is right now in the github PAI and i even tried querying with preview Accept headers like:

"Accept:application/vnd.github.polaris-preview"
"Accept:application/vnd.github.machine-man-preview+json"
"Accept:application/vnd.github.inertia-preview+json"

will test around a bit more and try and ping people on support/twitter 😸 or if anyone here knows, do let me know

**Comment by erwinmombay** [comment]
guessing it might not be exposed yet in the current API or even the announced preview API's

**Comment by cramforce** [comment]
Besides the API, I was mostly wondering about a query like
https://github.com/ampproject/amphtml/pulls?q=is%3Aopen+is%3Apr+author%3Acramforce+label%3ALGTM

I don't want to block this, though. Switching to approval-only is probably
a good idea.

**Comment by erwinmombay** [comment]
@cramforce yeah i'm not aware of a filter for it currently =/

**Comment by cramforce** [comment]
Yes, lets change it.

LGTM
