### ISSUE TITLE
YouTube size too big in IE11

### ISSUE THREAD

**Issue by simonferndriger** [ampproject/amphtml#5259]
1. Open https://www.ampproject.org/docs/get_started/about-amp.html in InternetExplorer 11 (Windows 10 Desktop)
2. You should see a way too big YouTube player (screenshot below)

![screenshot](https://cloud.githubusercontent.com/assets/1435963/18879686/8aa54804-84d5-11e6-9615-17f651e3cfcc.jpg)

**Comment by jridgewell** [comment]
Giving to @rudygalfi, delegate to whoever has IE 11 installed.

**Comment by mkhatib** [comment]
Will test this out.

**Comment by mkhatib** [comment]
This looks like a bug in how ampproject.org handles `<pre>` tags there. IE seems to take its full width as the content width, and since YT is responsive it expands it with that. Filed under ampproject/docs.
