### ISSUE TITLE
Amp HTML allows the attribute `content` only in the `meta` element

### ISSUE THREAD

**Issue by AlanDalton** [ampproject/amphtml#5265]
Could you allow the attribute `content` in other elements, and not just in the `meta` element, please?

I’m trying to create an Amp HTML version of a website that I made for a barber. When I try to create an Amp HTML version, the Amp HTML validator says that the attribute `content` may not appear in `tr` or `span`. This  [project’s metadata examples](https://github.com/ampproject/amphtml/tree/master/examples/metadata-examples) use the attribute `content` only in `meta` elements.

I’ve found that the attribute `content` is very useful for marking up things like opening hours:

```html
<tr itemprop="openingHours" content="Tu 09:30-18:00">
  <th scope="row">Tuesday
  <td><time datetime="09:30">9:30am</time>
  <td><time datetime="18:00"><strong>6</strong>:00pm</time>
```

…and prices:

```html
<tr itemprop="makesOffer" itemscope itemtype="http://schema.org/Offer">
  <th scope="row">
    <dfn itemprop="name">Student’s hair cut</dfn>
  <td>
    <span itemprop="priceCurrency" content="EUR">€</span><span itemprop="price">8</span>
```	

…and I think Amp HTML should allow that attribute on other elements, and not just the `meta` element.

To reproduce the issue, try this code in the validator:

```html
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <link rel="canonical" href="self.html" />
  <meta name="viewport" content="width=device-width,minimum-scale=1">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
</head>
<body>
  <meta itemprop="priceCurrency" content="EUR">
</body>
</html>
```
…and note that it passes validation. Then change the `meta` element to a `span` element:

```html
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <link rel="canonical" href="self.html" />
  <meta name="viewport" content="width=device-width,minimum-scale=1">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
</head>
<body>
  <span itemprop="priceCurrency" content="EUR">€</span>
</body>
</html>
```

…and note that it fails validation.

This affects the validator, not browsers or device types. This seems to apply to all versions of Amp-HTML. I think it has always been broken.

**Comment by Gregable** [comment]
`content` is not a legal HTML5 attribute for these tags. `<tr>` for example: [TR Element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tr)

It is also not one of the [global HTML attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes).

Can you use `data-content` instead? We allow `data-*` on all tags.

**Comment by AlanDalton** [comment]
Ah…I didn’t know that. I presumed that `content` was allowed on tags such as `span` and `tr`. [The HTML5 validator allows `content` on `span` and `tr` on a website I made](https://validator.w3.org/nu/?showsource=yes&doc=http%3A%2F%2Fwww.WarrenTheBarber.com), and some examples on [Schema.org’s “Offer”](https://schema.org/Offer) webpage use `content` on `span` and `div`.

Thanks for your suggestion. I [tested the webpage in the Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool#url=www.WarrenTheBarber.com) and changed some `content` attributes to `data-content`. That tool seems to interpret the `data-content` attribute the same way it interprets the `content` attribute. I’ll use that instead.

Thanks, @Gregable!
