### ISSUE TITLE
remove IE8 polyfills in `document-register-element`

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#5269]
we can probably make IE8 = false so the code paths can be DCE'd

**Comment by adelinamart** [comment]
@erwinmombay what's this topic about? Thanks

**Comment by erwinmombay** [comment]
this is to remove the IE8 code paths in the polyfill that we import. I'll have to retest it again if its possible since we are upgrading to a new version soon

**Comment by rsimha** [comment]
This is done
