### ISSUE TITLE
Support for Call Tracking Vendors

### ISSUE THREAD

**Issue by chrisdesrochers** [ampproject/amphtml#5276]
We utilize call tracking on our pages to track conversions that occur via phone. This is also a critical need for mobile landing pages. Current call tracking providers usually require the inclusion of an external JavaScript library which rewrite the phone numbers on a page with a unique tracking number. Requesting a component which standardizes call tracking implementation in AMP similar to how [amp-analytics](https://www.ampproject.org/docs/reference/extended/amp-analytics.html) is implemented. 

_Example providers:_ 
- [CallTrackingMetrics](https://www.calltrackingmetrics.com/)
- [CallRail](https://www.callrail.com)
- [DialogTech](http://www.dialogtech.com/)
- [Marchex](http://pages.marchex.com/)

**Comment by taf2** [comment]
It looks like the amp-analytics package might already be compatible with at least CallTrackingMetrics - working on this now to see if that's the case.

**Comment by taf2** [comment]
If anyone is interested I created a branch and started on adding support for CallTrackingMetrics.  I believe this is a generic enough start so the other vendors could use a similar approach and we'd still need to add some test coverage before this would probably be accepted.   Additionally, I hacked into the preconnect view code to inject our scripts this may or may not be okay.   

here's my initial work: https://github.com/taf2/amphtml/tree/master/extensions/amp-calltracking

If this looks good enough - I'm happy to turn this into a pull request as well.

**Comment by rudygalfi** [comment]
cc @cramforce @avimehta 

Looking at the design of the code, one concern I have is that this looks like it permits arbitrary 3P script execution, which is something that's now allowed in AMP except through sandboxed iframes. AMP must be able to have awareness of the performance characteristics of the scripts that run directly on the main page.

The design of amp-analytics enables an external request to fetch a config, but then AMP itself handles all of the instrumentation. Is there any way to achieve that here? I'm thinking that the `amp-calltracking` extension could take a config endpoint URL, which will return the transformations that need to be applied on the page. What HTML transformations are involved to achieve the tracking? E.g. is this updates to the values of certain <a> tags?

**Comment by taf2** [comment]
@rudygalfi - yeah that makes sense perhaps we could have call tracking providers publish a manifest of some sort that determines the page transformations to run?  The important thing to keep in mind is most vendors would have proprietary solutions.   They all generally work the same way - issue a unique tracking number given either a landing or referring URL pattern.    Some require an additional script or HTTP request to load after evaluating the page state to determine the (tracking) phone number to display.   Many of them will do a full DOM traversal to locate a specific (target) phone number to replace.   Others might provide a DOM hint to indicate which element contains the phone number.  In a lot of ways call tracking dynamic number insertion is similar to what services like Optimizely/VWO do by modifying the page dynamically.  It's possible it might work to more generally group a call tracking solution provider with general A/B testing software solutions like Optimizely and VWO...

It would IMO be very hard to generically cover these use cases without loading an additional third party script.

**Comment by rudygalfi** [comment]
Thanks for the details @taf2. Yeah, to get this working in AMP, it sounds like we'll definitely need to explore a new approach than what's used today.

Once a design is ready that doesn't involve 3p script execution on the main AMP page, I'd suggest moving this discussion to a new Intent to Implement issue so we can flesh out the finer points of the extension behavior.

**Comment by cramforce** [comment]
All sounds good.

Is the unique ID typically defined on the client side? If it is server
side, one could possibly just standardize the protocol that is used to talk
to the respective providers.

**Comment by lannka** [comment]
If ID is from server side, [amp-list](https://github.com/ampproject/amphtml/blob/master/extensions/amp-list/amp-list.md) can do the job. (we should rename `amp-list` to `amp-remote-render` or something).

**Comment by jasti** [comment]
@taf2 did you get a chance to open a new ITI/ approach without 3P JS execution on the AMP page? Thanks.

**Comment by taf2** [comment]
@jasti, sorry I'm not following can you elaborate on this?   Really I think to support Call Tracking in AMP pages we'll need AMP pages to support services such as Optimizely.   The methods we used to update phone numbers on a website is very similar to dynamic content changes... This might not be compatible with the design goals of AMP unfortunately...

**Comment by cramforce** [comment]
@taf2 Do you need anything besides:

- change a text string (aka the phone number)
- track clicks (to send analytics beacons on clicks onto `tel:` links?

**Comment by taf2** [comment]
@cramforce yes, i can attempt to summarize

- tracking page position
- tracking visibility of dom elements
- tracking text selection
- dom changes such as text color and visibility 
- alt, href attributes 
- there's more...

**Comment by cramforce** [comment]
@taf2 Should be either supported by amp-analytics or can be added as individual feature requests.

**Comment by jasti** [comment]
@rudygalfi are these FRs something you'd be able to help with for amp-analytics or should I take a crack?

**Comment by rudygalfi** [comment]
@jasti If you could file the individual FRs, that would be helpful.

**Comment by cramforce** [comment]
My proposal would be to build something like

```html
<amp-call-tracking config="https://vendor.com/call-tracking?user_id=123"><a href="tel:123-500-4568">123-500-4568</a></amp-call-tracking>
```

The vendor config would supply the replacement phone number and an `amp-analytics` config.

An alternative would be to just make this `amp-list` based. My intuition is that this is a frequent enough use case to warrant a special purpose extension. CC @dvoytenko

**Comment by cramforce** [comment]
I wrote up a design https://docs.google.com/document/d/1UDMYv0f2R9CvMUSBQhxjtkSnC4984t9dJeqwm_8WiAM/edit?usp=sharing

Feedback appreciated!

**Comment by cramforce** [comment]
Filed #7340 to track implementation.

**Comment by jridgewell** [comment]
Closed by #7377?

**Comment by alanorozco** [comment]
PR is #7493 and documentation is [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-call-tracking/amp-call-tracking.md).

**Comment by bpaduch** [comment]
@alanorozco  - Is this component still "in development"?  I tried to use it but the JS wasn't on the CDN.

**Comment by alanorozco** [comment]
@bpaduch Will update documentation once the component has made it into production, possibly within a couple of weeks :) Thanks.

**Comment by bpaduch** [comment]
@alanorozco - friendly ping; it's still not in the JS - validation fails.

**Comment by joshcp** [comment]
@chrisdesrochers did #7493 solve this for you? Specifically interested in implementing CallTrackingMetrics in AMP.

**Comment by taf2** [comment]
@joshcp,@chrisdesrochers  we have support now for AMP with CallTrackingMetrics

**Comment by ramu7765** [comment]
Ampproject Customer Care Number_ 9330189594 / 9337710197
Any problem support services number

**Comment by ramu7765** [comment]
Ampproject Customer Care Number_ 9330189594 / 9337710197
Any problem support services numbers

**Comment by ramu7765** [comment]
Ampproject Customer Care Number_ 9330189594 / 9337710197
Any problem support services number 
Ampproject Customer Care Number_ 9330189594 / 9337710197
Any problem support services numbers

**Comment by ramu7765** [comment]
Ampproject Customer Care Number_ 9330189594 / 9337710197
Any problem support services number is a good

**Comment by ramu7765** [comment]
Ampproject Customer Care Number_ 9330189594 / 9337710197
Any problem support services number. We are

**Comment by ramu7765** [comment]
Ampproject Customer Care Number_ 9330189594 / 9337710197
Any problem support services numbers are

**Comment by ramu7765** [comment]
Ampproject Customer Care Number_ 9330189594 / 9337710197
Any problem support services numbers are

**Comment by ramu7765** [comment]
Ampproject Customer Care Number_ 9330189594 / 9337710197
Any problem support services number is not

**Comment by ramu7765** [comment]
Ampproject Customer Care Number_ 9330189594 / 9337710197
Any problem support services number of the same

**Comment by ramu7765** [comment]
Ampproject Customer Care Number_ 9330189594 / 9337710197
Any problem support services numbered the other day and it

**Comment by ramu7765** [comment]
Ampproject Customer Care Number_ 9330189594 / 9337710197
Any problem support services numbered the other side of me call me for a while I have

**Comment by ramu7765** [comment]
Ampproject Customer Care Number_ 9330189594 / 9337710197
Any problem support services number % 9337710197

**Comment by ramu7765** [comment]
Ampproject Customer Care Number_ 9330189594 / 9337710197
Any problem support services number

**Comment by ramu7765** [comment]
Ampproject Customer Care Number_ 9330189594 / 9337710197
Any problem support services number

**Comment by ramu7765** [comment]
Ampproject Customer Care Number_ 9330189594 / 9337710197
Any problem support services numbered I

**Comment by ramu7765** [comment]
Ampproject Customer Care Number_ 9330189594 / 9337710197
Any problem support services number and I will

**Comment by ramu7765** [comment]
Ampproject Customer Care Number_ 9330189594 / 9337710197
Any problem support services numbered and it was

**Comment by ramu7765** [comment]
Ampproject Customer Care Number_ 9330189594 / 9337710197
Any problem support services numbers and I look forward to hearing back from the same
![Screenshot_20200723_194926](https://user-images.githubusercontent.com/68731565/88375158-b1453200-cdb8-11ea-9999-81f359d4edbd.jpg)

**Comment by cramforce** [comment]
Blocked ramu7765 and deleted their posts for spam.
