### ISSUE TITLE
iOS can only play 1 inline video at a time

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#5282]
Currently the autoplay UX breaks slightly on iOS if more than one autoplaying video is visible in the view port. This is because iOS can only play a single video at a time and automatically paused other videos. 

When a visible autoplay video is paused by iOS because another autoplay video becomes visible, we need to track it and when the other video goes out of view, we should resume the previous playing video.

**Comment by adelinamart** [comment]
@aghassemi can we triage this? Thanks

**Comment by aghassemi** [comment]
Closing in favor of https://github.com/ampproject/amphtml/issues/10879
