### ISSUE TITLE
newly generated changelog should contain all commits up to the last non pre-release tag

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#5293]
currently we generate only up to the last "tag" wherein that last tag could be another pre-release version. this makes it super confusing what the code is in canary/prod as you need to take the union of n number of versions to figure out what is rolled into the latest canary optin/percentage canary/prod

cc @tdrl @cramforce

**Comment by adelinamart** [comment]
@erwinmombay referenced issues is closed. Anything else to be done here? Thanks

**Comment by erwinmombay** [comment]
this is done.
