### ISSUE TITLE
Black border (left, right, bottom) added to body after lightbox closes on iOS Safari

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#5296]
Not sure if this is already in prod/canary. But it's in current master.

Repro:

1. Run local server
2. navigate to everything.amp.max.html example
3. Locate the Open Lightbox button
4. Click it
5. Click close dialog
6. Notice a visible black border appearing.

Computed styles for body changes as follow:
```css
/* Before Opening Dialog */
border-top-color: rgba(0, 0, 0, 0);
border-top-style: solid;
border-top-width: 0px;
height: 628px;
width: 414px;

/* After Opening Dialog */
border-bottom-style: none;
border-left-style: none;
border-right-style: none;
border-top-color: rgba(0, 0, 0, 0);
border-top-style: none;
border-top-width: 0px;
height: 628px;
width: 414px;

/* After closing dialog */
border-bottom-style: solid;
border-left-style: solid;
border-right-style: solid;
border-top-color: rgba(0, 0, 0, 0);
border-top-style: solid;
border-top-width: 0px;
```

<img width="578" alt="screen shot 2016-09-28 at 5 55 59 pm" src="https://cloud.githubusercontent.com/assets/2647/18937791/5b6a3b7a-85a8-11e6-8537-29dc288f73bb.png">

Seen on iOS 9.2

**Comment by erwinmombay** [comment]
@mkhatib can you checkout 1474310684773 and check if this bug is there?
