### ISSUE TITLE
Image lightbox jumps the image around when opened

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#5301]
Tested on iOS, though I think same thing happens on other browsers.

Image lightbox stretches the image to the right most of the page and then add a padding and the photo finally sits in its place.

**Comment by dvoytenko** [comment]
On every page? Or some specific example?

**Comment by ericlindley-g** [comment]
Possibly related: https://github.com/ampproject/amphtml/issues/4716

**Comment by muxin** [comment]
This might be related to the `border-top` added to body in ios mode. @mkhatib What example page were you testing?

**Comment by mkhatib** [comment]
I've seen this happen on the `everything.amp.html` example when you click the panorama photo to open it in a lightbox. @muxin might be what you mentioned.

**Comment by adelinamart** [comment]
@mkhatib is this still needed?

**Comment by mkhatib** [comment]
I think this was fixed. Closing.
