### ISSUE TITLE
Email sharing is not working iPhone 6 [OS : 10.0.1] Safari Browser.

### ISSUE THREAD

**Issue by amans1690** [ampproject/amphtml#5302]
Email sharing is not working iPhone 6 [OS : 10.0.1] Safari Browser.

## How do we reproduce the issue?

URL: https://www.google.co.in/amp/www.ahmedabadmirror.com/entertainment/bollywood/Krushna-Abhishek-Theres-leg-pulling-no-insulting-on-Comedy-Nights-Bachao/amp_articleshow/54578875.cms

1. Go to the above mention URL in Safari Browser of iOS 10.0.1 device.
2. Try sharing via email icon (next to g+ under the Heading of the page). Nothing happens.

FYI: In case debugging on laptop using developer tools, make sure to set the UA to a mobile device while accessing the above URL. 

## What browsers are affected?

iOS 10.0.1 Safari Browser

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1474310684773

**Comment by aghassemi** [comment]
Hi @amans1690 I can't reproduce on my iOS 10. Do you have the `Mail` app installed on the phone you are testing with? If `Mail` app is removed, `mailto:` links will not work on iOS.

Can you also try http://www.w3schools.com/html/tryit.asp?filename=tryhtml_mailto to see if it works on the same phone?

**Comment by amans1690** [comment]
Hi @aghassemi,
If I open the link http://www.ahmedabadmirror.com/entertainment/bollywood/Krushna-Abhishek-Theres-leg-pulling-no-insulting-on-Comedy-Nights-Bachao/amp_articleshow/54578875.cms then email share works fine in Safari Browser on iOS 10.0.1.
But it the same link is open using google search, on which the URL is https://www.google.co.in/amp/www.ahmedabadmirror.com/entertainment/bollywood/Krushna-Abhishek-Theres-leg-pulling-no-insulting-on-Comedy-Nights-Bachao/amp_articleshow/54578875.cms. Then the email share doesn't work.
FYI - I noticed that on email sharing on Chrome using Dev Tools the console prints a warning on email sharing 

> Mixed Content: The page at 'https://www.google.co.in/amp/www.ahmedabadmirror.com/entertainment/bollywoo…sulting-on-Comedy-Nights-Bachao/amp_articleshow/54578875.cms#development=1' was loaded over HTTPS, but requested an insecure resource 'mailto:?subject=Krushna%20Abhishek%3A%20There%27s%20leg%20pulling%2C%20no%20insulting%20on%20Comedy%20Nights%20Bachao%20-%20Ahmedabad%20Mirror&body=http%3A%2F%2Fwww.ahmedabadmirror.com%2Fentertainment%2Fbollywood%2FKrushna-Abhishek-Ther…-pulling-no-insulting-on-Comedy-Nights-Bachao%2Farticleshow%2F54578875.cms'. This content should also be served over HTTPS.

You can check the screen shot below for the warning.
![amp_email_share_error](https://cloud.githubusercontent.com/assets/10262551/18982699/bfb3ca3e-8705-11e6-9d01-a6971977cc1f.png)

**Comment by aghassemi** [comment]
@amans1690 Thanks. I can reproduce now. Fix coming soon.
