### ISSUE TITLE
Inside the form action is not accepting "http url or custom url" 

### ISSUE THREAD

**Issue by sandeepv10** [ampproject/amphtml#5304]
Hi Teams,

When we go to use the form but inside the form action is not accepting "http url or custom url" lilke below 

```html
<form method="get"
      action="http://example.com"   action-xhr="http://httpbin.org/response-headers"    target="_blank">
         <input type="search" name="term" required>
        <input type="submit" value="Search">
</form>
```
Acknowledge please.

Thanks 
Sandeep

**Comment by ericlindley-g** [comment]
cc/ @mkhatib @rudygalfi

**Comment by mkhatib** [comment]
@sandeepv10 Yes. AMP only accepts forms submissions to `https` endpoints. See [details in docs](https://github.com/ampproject/amphtml/blob/master/extensions/amp-form/amp-form.md#attributes).
