### ISSUE TITLE
cannot change .-amp-accordion-header background color 

### ISSUE THREAD

**Issue by sparks1975** [ampproject/amphtml#5305]
Background color of accordion header cannot be changed.  When background-color style is applied to the first child of the amp-accordion, it is overwritten by the .-amp-accordion-header style injected by the js.

**Comment by jpettitt** [comment]
Put an id on your `amp-accordion` then you can do `#accordionId .headerClass { background: red; }` and it will work becasue the Id has a higher specificity in the CSS. 

See the footer of https://fresnobee.relaymedia.com/amp/news/local/education/article61889207.html for a live example.  

This article explain CSS specificity really well https://css-tricks.com/specifics-on-css-specificity/

**Comment by erwinmombay** [comment]
feel like this is a bug on our end, but its a hard problem because of the injected styles which are delayed

**Comment by jpettitt** [comment]
@erwinmombay It's not really a bug, you're adding a class and you're injecting your CSS above the user CSS so it's trivial to override the default.  Pretty much the only way around this would be to not provide default styling, removing it at this stage would be a breaking change.

There is a good question here going forward about very careful review of default styling, particularly in -amp styles that can't be directly overridden, in new features before they are deployed.

**Comment by sparks1975** [comment]
@jpettitt Thank you for the solution.  It worked for what I was needing to do. It does seem odd to have a major style such as background color associated with a selector that cannot be directly overwritten.

**Comment by IamAlta** [comment]
Putting an id on the header doesn't work if you use dynamic coding where all ID's need to be in the style sheet. E.g., what if you had 3 or 4 accordions on a page? Each needs its own ID. You need to anticipate that and ensure they are all in the stylesheet. 

This should be a quickie for you to fix.
The styling for the <amp-accordion><header> is being overridden by the amp code styling, .i-amphtml-accordion-header.
Can you remove that and let us decide what is best for our styling?

**Comment by IamAlta** [comment]
Putting an id on the header doesn't really work if you use dynamic coding where all ID's need to be in the style sheet. E.g., what if you had 3, 4+ accordions on a page (which my client has)? Each needs its own ID. You need to anticipate that and ensure they are all in the style sheet.

This should be a quickie fix.
The styling for is being overridden by the amp code styling, .i-amphtml-accordion-header.
Can you remove that and let us decide what is best for what our graphic artists' design?
