### ISSUE TITLE
White empty bar displayed when scrolling vertically 

### ISSUE THREAD

**Issue by corvusinaloeCMENA** [ampproject/amphtml#5307]
When scrolling up and down, a white empty bar is displayed below the AMP carousel on immersive mode.   

1 In Chrome Go to opt into "pan-y" at https://cdn.ampproject.org/experiments.html 

2 In Chrome Go to opt into the "dev-channel" at https://cdn.ampproject.org/experiments.html

3  Go to www.google.com

4  Search for Hillary Clinton

5  When the AMP Carousel is displayed in the search results page, select one of the AMP articles to go into immersive mode. 

6 Scroll all the way up (try to force scroll to the top, then white bar is displayed). 

Chrome 52.0.27 for iOS 9 on iPhone 5c

**Comment by corvusinaloeCMENA** [comment]
This issue is also presente on iGSA 19.0.1 for iOS9 on Iphone 5c
![image1 3](https://cloud.githubusercontent.com/assets/22305326/18971891/af2b8036-864b-11e6-89ce-0d7e63f6ea55.PNG)

**Comment by ericfs** [comment]
Do you have a screenshot of this?

**Comment by ericfs** [comment]
b/31860236

**Comment by adelinamart** [comment]
Closing this one since it's being tracked internally.
