### ISSUE TITLE
(X) Close button not working on AMP Carousel immersive view 

### ISSUE THREAD

**Issue by corvusinaloeCMENA** [ampproject/amphtml#5308]
When on immersive AMP Carousel mode, the (X) button for closing and going back to Google search resuls is not working. 

1 In Chrome Go to opt into "pan-y" at https://cdn.ampproject.org/experiments.html 
2 In Chrome Go to opt into the "dev-channel" at https://cdn.ampproject.org/experiments.html
3 Go to www.google.com
4  Search for Hillary Clinton
5.  When the AMP Carousel is displayed in the search results page, select one of the AMP articles to go into immersive mode.
6  Tap on the (x) close button.

Expected: The AMP Carousel immersive view should be closed and the user should be returned to the Google Search Result page 

Chrome 52.0.27 for iOS 9 on iPhone 5c.

**Comment by ericfs** [comment]
Thanks. Tracking internally b/31859380

**Comment by ericfs** [comment]
Do you have a video or other demo of this? I cannot repro on Chrome 53.0.2785

**Comment by adelinamart** [comment]
Closing this one since it's being tracked internally.
