### ISSUE TITLE
Switching between landscape and portrait mode makes the screen incomplete 

### ISSUE THREAD

**Issue by corvusinaloeCMENA** [ampproject/amphtml#5313]
When on immersive AMP Carousel mode, switching between landscape and portrait modes makes the  article to be displayed in half or incomplete. When scrolling up and down the article gets broken and the user has to go back and reload to read the rest. 
1 In Safari Go to opt into "pan-y" at https://cdn.ampproject.org/experiments.html 
2 In Safari Go to opt into the "dev-channel" at https://cdn.ampproject.org/experiments.html
3 Go to www.google.com
4 Search for Hillary Clinton
5. When the AMP Carousel is displayed in the search results page, select one of the AMP articles to go into immersive mode.
6 Switch to landscape mode and review the result
7 Switch to portrait mode and review the result. 

Safari 9 for iOS 9 on iPhone 5c.

**Comment by sriramkrish85** [comment]
can you attach some video(s) or screenshots?

**Comment by sriramkrish85** [comment]
Also are you talking about the carousel on the google search page or an (image) carousel on a particular AMP page.

**Comment by corvusinaloeCMENA** [comment]
Screenshots added, I am talking about the carousel on the google search page. 
![image3](https://cloud.githubusercontent.com/assets/22305326/18970999/4d47af82-8648-11e6-978a-938bfa2dda8c.PNG)
![image2 1](https://cloud.githubusercontent.com/assets/22305326/18970998/4d464e94-8648-11e6-9510-1e2795d23023.PNG)

**Comment by ericlindley-g** [comment]
@corvusinaloeCMENA I can't repro on iPhone 6. Is this only on 5s? Also, does this happen only with the pan-y experiment enabled, or does this happen without that as well? If it happens without, we can escalate to the Google team working on the viewer on the search results page

**Comment by corvusinaloeCMENA** [comment]
This issue is also presente on iGSA 19.0.1 for iOS9 on Iphone 5c
![image1 3](https://cloud.githubusercontent.com/assets/22305326/18973122/e762cb12-8650-11e6-87ef-bea8d12fd092.PNG)

**Comment by ericlindley-g** [comment]
Escalated internally: b/31831214

**Comment by adelinamart** [comment]
This was fixed internally.
