### ISSUE TITLE
amp-analytics vars inside A4A.

### ISSUE THREAD

**Issue by avimehta** [ampproject/amphtml#5318]
Currently amp-analytics does not work inside A4A but with #5196, it will start working. Once it starts working, we need to figure out how different features will work for amp-analytics and amp-pixel. A few open questions are:
- What variable expansions should be supported wrt security/privacy issues. eg: document_referrer
- When the variables are expanded, will they be about the ads iframe or the parent document. eg: does canonical_url represent ad url or the amp document url?
- How do triggers fire? Does a scroll or visibility trigger fire relative to the ad or relative to the whole document?
- Is amp-analytics inside the ad allowed to measure things outside the ad?
- Should we provide some ad-only variables? like ad provider, loading time, rendering errors etc?

/cc @rudygalfi to answer some questions
/cc @dvoytenko @cramforce 

ps: I can open individual issues for each of the questions and keep this as the tracking bug if needed.

**Comment by cramforce** [comment]
It would be really nice to write this up as a design doc.

I think the direction should be

- whitelist what is available to ads
- introduce a scoping mechanism (CC @dvoytenko) where the same variable may have a different value

**Comment by avimehta** [comment]
Sounds good. Will start the doc and present for review.

**Comment by lannka** [comment]
@tdrl @keithwrightbos

**Comment by dvoytenko** [comment]
To start with, we need to go var-by-var and mark what should happen to each var for an embed. I'd assume the action would be one of: pass through unchanged, override, disable.

This would give us the best mode of action to scope these vars. But my guess is that this would be that we just need to add additional scoping to `UrlReplacements` class.

Further, we need to look at other questions related to boundary:
 1. Doc -> embed. E.g. can dock listen on visibility of an element inside an embed or other events? May be events are ok, but exact target should be retargetted to host?
 2. Embed -> doc. Make sure that the embed cannot reach into anything in the parent doc that is not allowed.

**Comment by tdrl** [comment]
Feature request:  In PR #5373 , we did a very quick/dirty implementation of some timing and instrumentation pings for A4A and 3p ads.  It would be much better to let Analytics handle this, though.  Independent of the ad content, we'd like to be able to measure properties like:

- Total number of ad slots on a page vs. number of ad slots that actually execute.
- Time from page load to ad start.  (Not necessarily the same as `layoutCallback`.)
- Round-trip time for ad fetch request.
- Time from ad render begin to end.
- Time for ad validation (crypto verification).
- Fraction of ads that render as A4A vs 3p.

Ultimately, we'd like to be able to waterfall-diagram times down different code paths and the number of requests that pass through / get dropped at each stage.

**Comment by rudygalfi** [comment]
Can anyone give a status update on this issue?

**Comment by jasti** [comment]
@michaelkleber @keithwrightbos  is this a must for implementing spam and external party viewability support? Will we need to use amp-analytics to collect the signals necessary and post message them to the requestor?
CC @lannka

**Comment by lannka** [comment]
I see 3 different FRs here:
- have `<amp-analytics>` inside AMP creative work in preferential rendering mode (in Avi's post). It is already done, @dvoytenko 
- have `amp-analytics` instrument the whole request/response lifecyle of A4A (in tdrl's post). This will be addressed in FR: #6417
- have `amp-analytics` collect extra signals for 3P fraud detection or viewability tracking (in jasti's post). do we have a design yet?

I suggest we can close this issue and open a separate I2I for the 3rd proposal if @dvoytenko can confirm all the amp-analytics features works for FIE AMP creative.

**Comment by rudygalfi** [comment]
@dvoytenko Can you confirm on @lannka's last comment and close this issue?

**Comment by dvoytenko** [comment]
@rudygalfi @lannka @avimehta I believe this bug refers specifically only to an ability to override/restrict variables for AMP. As such, I believe this has been completed long ago.
