### ISSUE TITLE
Investigate Brid.tv Dynamic Image placeholder

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#5321]
Dynamic Image Placeholders for brid.tv doesn't seem to work.

@DarXector do you happen to know if there's public documentation on this? Or an example where this works? The examples I've seen online seems to refer to different URL for the placeholders.

For example: 
This works and its what's used by the player code.
[https://cdn.brid.tv/live/partners/264/snapshot/shot2015.jpg](https://cdn.brid.tv/live/partners/264/snapshot/shot2015.jpg)

But the dynamically generated image placeholder in `buildImagePlaceholder_` 404s:
[https://cdn.brid.tv/live/partners/264/snapshot/13663.jpg](https://cdn.brid.tv/live/partners/264/snapshot/13663.jpg)

Any idea if the following is the correct syntax for generating that placeholder and whether there are any examples out there where I can see this working or documentation? Otherwise we should just drop that part and just fallback to the `defaultSnapshot` instead.
`https://cdn.brid.tv/live/partners/{partnerID}/snapshot/{videoId|playlistId}.jpg`

Let me know.

**Comment by DarXector** [comment]
Hi, this is the correct syntax. There was a change on the Brid.tv side for this player specifically. It was using a custom snapshot URL. This has been fixed now. 
There already is a fallback placeholder for these situations, but support for custom URL should probably bee added.

**Comment by mkhatib** [comment]
> There already is a fallback placeholder for these situations, but support for custom URL should probably bee added

Not sure what you mean here, but glad the fix is in, is the fix only work for videos and not playlists?

Anything else needs to be done here or should we close this issue?
