### ISSUE TITLE
Allow for AMP ad anchors to target _top

### ISSUE THREAD

**Issue by keithwrightbos** [ampproject/amphtml#5324]
## Short description of your issue:

Anchor links within an iframe that lead to itunes do not navigate on Safari iOS 9 however AMP validator does not allow target _top.

## How do we reproduce the issue?

1. browser is safari on ios 9
2. there is a link that leads to itunes
3. link is in iframe
4. link has target=_blank
5. click on link does not navigate

## What browsers are affected?

Safari iOS 9

## Which AMP version is affected?

All

## Proposed Fix

Allow for data-target=_top attribute on anchors within amp-ad which will have their target changed to _top via AMP runtime.

**Comment by cramforce** [comment]
@keithwrightbos We're tracking this in b/32003819. Could you take a look and see if this is a separate issue?

**Comment by keithwrightbos** [comment]
Change within validator is ideal and appears to be imminent so closing.

**Comment by Gregable** [comment]
Just to be sure I understand, this is a runtime-only change, not a validator change, correct?

**Comment by cramforce** [comment]
@Gregable We don't currently limit `target=_top`, right? I checked, but want to make sure. If we did not allow it, we should allow it now.

**Comment by Gregable** [comment]
For `<a>` tags and a few other places, we allow only `target=_self` and `target=_blank`. The original thread mentions `data-target`, which we do not constrain.

**Comment by cramforce** [comment]
I see. So, we'd like to extend validity to include target=_top.

**Comment by Gregable** [comment]
OK

**Comment by Gregable** [comment]
Fixed. Not live yet.

**Comment by nbeloglazov** [comment]
What's ETA of it being live?

**Comment by Gregable** [comment]
Next week.
