### ISSUE TITLE
JWPlayer Placeholder is invalid for playlists

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#5328]
The calculated URL for a playlist-based jwplayer generates a 404 placeholder image URL. 

@pablos1 do you know if there's a way to generate a thumbnail for the first video in the playlist? 

If there is no way, does JW Player have a default playlist thumbnail we can use?

**Comment by pablos1** [comment]
@mkhatib It is possible to upload a thumbnail via the JW Platform [API](https://developer.jwplayer.com/jw-platform/reference/v1/methods/channels/thumbnails/update.html).  However, a thumbnail is not created by default for each playlist, so `createPlaceholderCallback` would need to include some logic to gracefully handle a 404.

If a thumbnail does exist for a particular playlist ID, it would be located in the same location as for individual media.

**Comment by mkhatib** [comment]
Thanks @pablos1 for the response, this sounds good. Thanks for the clarification
