### ISSUE TITLE
Use NewTypeInference for type checking

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#5335]
We should switch to NTI as OTI is no longer supported and in particular [this bug](https://github.com/google/closure-compiler/issues/2050) is important to us as we like to ensure all properties are defined in the constructor so V8 can optimize types and create hidden classes for them. Currently this rule can't be enforced with ES6 classes due to https://github.com/google/closure-compiler/issues/2050.

To make it easier to upgrade, we can suppress new extra checks done by NTI by adding `newCheckTypesExtraChecks` to `jscomp_off` but even without the extra checks, there are currently 207 errors to fix at stage one and unknown number of errors to be fixed at stage two.

/cc @cramforce @erwinmombay I will give this couple of hours today and see how far we can go.

**Comment by cramforce** [comment]
Cool. Last time I tried it just crashed :)

**Comment by rsimha-amp** [comment]
Obsolete.
