### ISSUE TITLE
How to add Yandex Advertisement Network to AMP?

### ISSUE THREAD

**Issue by oleggromov** [ampproject/amphtml#5337]
Hello!

We at Yandex are about to give our partners (publishers) the ability to show our ads on their AMP-powered websites. In order to do this we give them scripts that use:

- Adding scripts to the page to load JS bundles, using JSONP for data requests.
- Global context sharing (all ads code is executed in the same `window`).
- Tracking visibility by accessing main page's `window.document` DOM nodes, methods and properties.
- Creating iframes for both showing rich media ads and invoking third-party visibility confirmation links.

The process goes through a few steps that are described below in more detail together with related questions.

## Loading

Currently we have embeddable JavaScript code that is placed on the page as inline script. This inline script is executed and then makes requests that can be synchronous (probably not the AMP case because of its blocking nature) or asynchronous:

- Load and execute initial loader script that deals with A/B testing. It is loaded with `script` tag.
- Load main code bundle that has all business logic and styles inside (inserting another `script` tag).
- Make a JSONP request to our backend (also a `script` tag is inserted into the page).

### Questions

- How can we make these inserted scripts work (both for the code itself and JSONP for data transferring)?
- We make only sequential requests for the data in order to filter already shown ads. This makes all our ads placed in separate slots aware of each other by sharing the same global context (`window` object). What's the simpliest way to do this?

## Showing ads

After the browser completes the JSONP data request, we proceed to the following steps:

- Show ads (consisting of text with image or rich media ads).
  - If we are to show rich media ad, we create an iframe and normally load it contents with another one request
  - Text ads, in turn, often have unpredictable height because of different texts and images (that are loaded by advertisers). We know the exact dimensions of the DOM element only after its rendering finishes.
- Start checking if shown ads are visible and are not overlayed with anything else on the page.

### Questions

- How can we deal with the unpredictable height of ad element?
- Again, it's convenient for us to use shared global context to check actual position of rendered elements relative to the viewport and other page elements. Is it possible?

## Additional requests and activity on the page

When the ads are shown we need to start additional processes in order to precisely track ads visibility and gather additional statistics both for our partner and ourselves.

- Once we're sure the needed ad part (50% for media, 1 pixel for textual) was visible for 2 seconds we send a few requests to confirm their visibility.
  - If we show rich media ads in iframe, then we also make those requests from an iframe (its url is freezed in order to make loading as faster as possible) by creating 'pixels' for them.
- We also gather some statistics by including Yandex.Metrika.

### Questions

- How can we track visibility directly?
- Can we leave these confirmation and statistics tracking and requests as is?

## Looking for your advice

We're looking forward for your advice on the best and the most straightforward way to implement all our features to fulfill our partners' needs. Thank you in advance!

**Comment by lannka** [comment]
@oleggromov please take a look the this [doc](https://github.com/ampproject/amphtml/blob/master/ads/README.md), and hopefully you will find most of your questions answered.

For example:
> How can we deal with the unpredictable height of ad element?

You can take a look at the "multi-size request" and "ad resizing" section.

> How can we track visibility directly?

There is the "ad viewability" section.

**Comment by oleggromov** [comment]
Thank you Hongfei!

If I understood you correctly, you recommend to implement custom `amp-ad` element, don't you? Unfortunately, switching to such tough environment with iframes, custom AMP API for communicating with other ads instances and the page itself is a rather expensive project - on the one hand. On the other hand it seems that we already have a lot of customers who want to show our ads on their AMP-powered sites. 

This issue with a lot of details was intended to ask if there is a more straightforward and simple way?

**Comment by oleggromov** [comment]
@lannka Can you please give me an answer?

**Comment by ericlindley-g** [comment]
@oleggromov I don't think there are other options being considered for Ads integrations right now (aside from AMP for Ads, where the ads themselves are implemented in AMP), but @jasti can confirm

**Comment by oleggromov** [comment]
@ericlindley-g Thanks.
@jasti please confirm.

**Comment by lannka** [comment]
@oleggromov adding support to `amp-ad` is right now the fastest way (we didn't tell you about [A4A](https://github.com/ampproject/amphtml/issues/3133) :-)). And there are already 60+ ad networks added their support. Please take a look at the [developer guidelines](https://github.com/ampproject/amphtml/blob/master/ads/README.md#developer-guidelines-for-a-pull-request), and we are ready to help if you have any questions.

**Comment by oleggromov** [comment]
@lannka We will look at A4A and use `amp-ad` for our integration. Thank you.
