### ISSUE TITLE
Support Subresource Integrity

### ISSUE THREAD

**Issue by alech** [ampproject/amphtml#534]
I think it would be a benefit if SRI (http://www.w3.org/TR/SRI/) was supported, i.e. the example should have an integrity attribute for the script tag and the CDN-server should be CORS-enabled in order to make the verification of the hash possible.

**Comment by dvoytenko** [comment]
That looks like a good idea. @cramforce wdyt? Generally we serve everything via HTTPS, but still...

**Comment by jridgewell** [comment]
HTTPS doesn't guarantee the integrity of the linked file. The Github Engineering Blog [explains](http://githubengineering.com/subresource-integrity/) why this is important now that everything is served via CDNs.

**Comment by mozfreddyb** [comment]
SRI spec editor here. Happy to help with whatever question you may have.

**Comment by cramforce** [comment]
I think for AMP's primary JS files this cannot be used as AMP changes over time and those changes cannot require changing documents.

I think the security benefits of not letting docs lock themselves into insecure versions of AMP outweigh the risk of insecure versions of AMP.

**Comment by fulldecent** [comment]
We are not concerned about insecure versions of amp; we are concerned with insecure versions of NOT amp. Integrity guarantees that something an author links to is the same thing a viewer gets.

**Comment by cramforce** [comment]
I understand, but against SRI is fundamentally incompatible with AMP. AMP, as it stands, cannot be used without trusting https://cdn.ampproject.org to deliver only official AMP versions.

I think what would make a lot of sense is to document how external parties can verify that the delivered sources are actually build from the open source repositiory.

**Comment by Gregable** [comment]
@cramforce, what do you think about allowing these for stylesheets, e.g.:

`<link rel=stylesheet href='https://fonts.googleapis.com/css?family=Lato|Bad+Script' integrity="...">`

**Comment by cramforce** [comment]
@Gregable we can definitely allow `integrity` on all non-JS resource elements. for `amp-img` and similar it would require a small JS change,

**Comment by Gregable** [comment]
Hm, I don't think this attribute exists except for `<link>` and `<script>`, at least not according to https://www.w3.org/TR/SRI/#elements

So, I don't think there is any reason to implement code for `<amp-img>`

**Comment by cramforce** [comment]
Definitely +1 on allowing it on `link`

**Comment by fulldecent** [comment]
To be clear: this is issue is concerned with AMP creating versioned and integrity-verified releases of AMP. Issues related to font CSS integrity are separate and I have created an issue https://github.com/ampproject/amphtml/issues/7060 to discuss that separately. Also that includes more specific action points to that issue.

**Comment by fulldecent** [comment]
Following is an action plan for correcting this instant issue of SRI for AMP.

 - [ ] Make a release NOW using a real version number.
    - Discussion: the latest version of this project is [1484265443309](https://github.com/ampproject/amphtml/releases/tag/1484265443309)
    - Recommendation: release https://cdn.ampproject.org/v0.js as https://cdn.ampproject.org/v0.0.1-1484265443309.js
 - [ ] Commit to permanently publishing versioned releases on CDN.
    - Discussion: this is the official policy of EVERY other CDN. One example: https://www.bootstrapcdn.com/ shows the current and all prior versions.
 - [ ] Create redirects to accomplish the current AMP project's workflow.
    - Discussion: Currently you can reference https://cdn.ampproject.org/v0.js and get the latest version of AMP, with updates being applied automatically. WE CAN KEEP THIS RECOMMENDED USE CASE. Simply create a redirect (303) from https://cdn.ampproject.org/v0.js to https://cdn.ampproject.org/v0.0.1-1484265443309.js
 - [ ] Update documentation to announce support for SRI and continue recommending to NOT use SRI.
   - Discussion: This note can be added: "We recommend that you link to the latest version of AMP by using https://cdn.ampproject.org/v0.js However, for application that require subresource integrity validation, you can link to a specific version, which is guaranteed not to change. An example with SRI is: <link ...>"

Following is additional related work to bring the AMP project in line with current best practices:

 - [ ] Officially adopt semantic versioning for this project.
     Discussion: because other developers will depend on this project and must build around it, then therefore this project has a public API. As other developers use this API, it is important for them to quickly understand if an updated version requires changing their usage of the API. Semantic versioning is a well-understood pattern to adhere to. See http://semver.org/
 - [ ] Release a version 1.0.0 or greater.
    - Discussion: semver.org answers the question [How do I know when to release 1.0.0?](http://semver.org/#how-do-i-know-when-to-release-100). Google is currently caching and serving AMP pages from its homepage, yes this counts as production use, so yes we are already at 1.0+

**Comment by cramforce** [comment]
AMP is an evergreen JavaScript library. We will not allow users to lock themselves into a particular release. Using an old version of AMP is bad for the same reason of using an old version of Chrome.

If link is covered in a separate issue we can close this.

**Comment by fulldecent** [comment]
@cramforce Could you please link to where this "evergreen JavaScript library" concept is documented as a best practice?

Please note that the work plan above does allow AMP to continue recommending that developers link to the always-latest version of the project, as is currently the case today.

**Comment by cramforce** [comment]
https://github.com/ampproject/amphtml/releases has all releases documented.

I should at some point write a retrospective on the evergreen JS library concept.

**Comment by fulldecent** [comment]
Just to clarify for anyone that does not know about SRI, [the main goal of SRI](https://www.w3.org/TR/SRI/) is that:

 > Compromise of a third-party service should not automatically mean compromise of every site which includes its scripts.

"Evergreen JS" is NOT compatible with SRI. Additionally, the [AMP specification](https://www.ampproject.org/docs/reference/spec) states that:

> The AMP runtime is loaded via the mandatory `<script src="https://cdn.ampproject.org/v0.js"></script>` tag

Therefore, **compromise of a third-party service would automatically mean compromise of every site using AMP**.

**Comment by cramforce** [comment]
That is correct.

Pages can, of course, choose to serve their own version of AMP. They won't be considered valid AMP, but otherwise can take advantage of all its features.

**Comment by fulldecent** [comment]
That would not count as AMP and does not solve the current issue.

Also, another note: Gary Illyes, Webmaster Trends Analyst at Google was present at SEJ Summit Chicago and [stated that](https://www.searchenginejournal.com/future-amp-gary-illyes-sejsummit-chicago/166677/):

 > "Currently, AMP is not a mobile ranking factor."

In other words, he failed to state that Google would not use AMP as a ranking signal.

----

In summary we have:

> Google has made a statement that they may feature websites less prominently unless they reduce their security and allow their websites to be vulnerable to a compromise of Google servers.

I know we are all engineers here, but perhaps a Google lawyer should be interpreting the implications of that statement above.

**Comment by cramforce** [comment]
For Google specific questions, please refer to the Google Search & AMP forum. https://goo.gl/utQ1KZ This is not a very good venue and nobody who works on Google Search regularly hangs out here.

Closing this. We'll put in the change for `link` tags.
