### ISSUE TITLE
Kill amp-carousel/0.1/slides.js

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#5343]
Now that slidescroll is the default carousel, let's 🔪 some dead code.

**Comment by sriramkrish85** [comment]
Lets make sure we dont have to rollback for another 2-3 days and kill! Thanks for filing the bug

**Comment by sriramkrish85** [comment]
will be dealt as a part of this.

https://github.com/ampproject/amphtml/issues/3997
