### ISSUE TITLE
remove TransitionDef signature in favor of TimeTransitionDef

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#5346]
@dvoytenko suggested to remove the "complete" param and rely on the `then`/`thenAlways` methods at the end of animation

**Comment by erwinmombay** [comment]
see https://github.com/ampproject/amphtml/pull/5339/files#r81376794 for previous discussion

**Comment by dvoytenko** [comment]
This can be closed now. Right?

**Comment by erwinmombay** [comment]
@dvoytenko probably, is it still a good idea to remove the "complete" param?
