### ISSUE TITLE
Clarify whether or not "amp" is permitted in the close </html> tag

### ISSUE THREAD

**Issue by jmadler** [ampproject/amphtml#535]

**Comment by jmadler** [comment]
The validator does not currently check for this.

**Comment by Gregable** [comment]
It's not valid HTML to have attributes in closing tags (except self-closing tags, but those are also open-tags, so it makes sense), so if you assume the fact that the spec claims that AMP is a subset of HTML, then the spec doesn't permit closing tag attributes, though I could maybe see making this explicit.

Ref: http://www.w3.org/html/wg/drafts/html/master/syntax.html#end-tags

The validator maybe should check for this, though I'm these are benign in a browser, so it's not that essential to do so maybe? Probably best to be strict. Not a high priority.

**Comment by jmadler** [comment]
Yep - let's also clarify in documentation

**Comment by cramforce** [comment]
I don't think this needs to be documented or checked.

**Comment by jmadler** [comment]
reopening as per previous conversation - conclusion: add to validator, not docs.

**Comment by dvoytenko** [comment]
Did this come up again? Can we close? I struggle to see how we can help here, this is really a pre-parser issue.

**Comment by amphtml-team** [comment]
OK to close

**Comment by Gregable** [comment]
Hm, this is still not checked in the validator as per @jmadler's request. Have we decided that we are no longer worried about this? It can be done if we want, but I hadn't given it high priority.
