### ISSUE TITLE
Amp Ads Untestable via Heroku due to Frame.html 404

### ISSUE THREAD

**Issue by devjsun** [ampproject/amphtml#5351]
I would like to use heroku to test new amp ads that are not available yet in production/release. It seems like there is a bug that prevents this. 
## How do we reproduce the issue?
1. Go to: http://amphtml-nightly.herokuapp.com/examples/ads.amp.max.html
2. Look at console and you see the errors like this: https://d-2518138595135783351.ampproject.net/1475185251892/frame.html 404 ()
## What browsers are affected?

Chrome, All
## Which AMP version is affected?

Current

**Comment by cramforce** [comment]
I think the fix is to override the config for `url.cdn` to point to the heroku name when running there. CC @erwinmombay

**Comment by erwinmombay** [comment]
@cramforce right that is the fix

**Comment by ericlindley-g** [comment]
@cramforce @erwinmombay  — can this be closed? Should we add documentation to amp-ad around this?

**Comment by cramforce** [comment]
It can't be closed yet. We need to fix our heroku deployment to do the right thing by default.

**Comment by dknecht** [comment]
I think this is related to our previous issue about the last few hard coded URLs.

**Comment by erwinmombay** [comment]
yeah, just need to add docs on how to override the configs i think. I'll test it out today

**Comment by megankj** [comment]
Are there any updates on this?

**Comment by cramforce** [comment]
I don't think so, but lets get it done!

**Comment by erwinmombay** [comment]
apologies. will work on it today

**Comment by megankj** [comment]
Any updates?  Eager to see this fixed. :)

**Comment by erwinmombay** [comment]
@megankj hoping to get a PR out by EOD. 💨

**Comment by megankj** [comment]
@erwinmombay Thanks!

**Comment by e2corporation** [comment]
@cramforce I am also encountering issues on Heroku and wanted to know if this is related, mainly with Safari and iOS w/ Safari. When using a custom v0.js Dist URL, Chrome and FF work fine, Safari on the other hand seems to hang at the placeholder "Loading...." and won't complete render.

The 3p-meta tag has been set to the Heroku URL, and the remote.html has a custom draw3p function with our network added. Any suggestions on what could be missing? Thanks.

**Comment by cramforce** [comment]
Doesn't ring a bell unfortunately. Never heard of that happening before.

**Comment by e2corporation** [comment]
@cramforce Here is the URL in question, [https://shogun-amp.herokuapp.com/examples/revcontent-theatlantic.min.html](https://shogun-amp.herokuapp.com/examples/revcontent-theatlantic.min.html)

Running it through the validation service the only errors shown refer to the use of the custom script sources.

**Comment by cramforce** [comment]
I looked into this and it is not clear to me why it is happening.
Unfortunately its hard to debug in Safari. Maybe ads are just broken in
Safari in general? Could you file a separate issue?

**Comment by e2corporation** [comment]
@cramforce Thanks Malte for checking into this, I have an open pull to get renderStart() implemented, with this release we are making updates on the service code on our end to resolve the broken status on the examples. I am delayed in staging as we cannot safely pass the test page when using iPhone devices with Chrome and Safari on a non-production endpoint.

Opening separate ticket for the issue.

**Comment by e2corporation** [comment]
@cramforce Issue #5948 Submitted.

**Comment by erwinmombay** [comment]
**here**: to get it to work on heroku you will need get the latest code and set `AMP_TESTING_HOST` environment variable with the hostname.

`heroku config:set AMP_TESTING_HOST=my-heroku-subdomain.herokuapp.com`

**Comment by megankj** [comment]
For some reason this only works if I remove "&& gulp dist --fortesting" from "heroku-postbuild" on line 22 in package.json.  Am I missing something?

**Comment by megankj** [comment]
Nevrmind, haven't updated that file, please ignore.

**Comment by megankj** [comment]
Now that I have the correct version of the files... this still isn't working.  It fails at heroku-postbuild again.  I have set the environment variable as stated but it still fails here:

npm run test-env-var && gulp clean && gulp build --fortesting && gulp dist --fortesting && npm run prepend-amp && npm run prepend-v0

Evne when I run this command, it says I haven't set the variable, but I definitely have.

**Comment by e2corporation** [comment]
@megankj I was able to get my heroku instance working with just the **config:set** after pulling the latest updates as suggested by @erwinmombay. How are you deploying to heroku? Is your setup based on the deploy guide? https://docs.google.com/document/d/1LOr8SEBEpLkqnFjzTNIZGi2VA8AC8_aKmDVux6co63U/edit?usp=sharing

**Comment by megankj** [comment]
I am indeed.  Latest code (+ the changes I need to add a new ad type) and I followed the directions.

If I run 

heroku config:get AMP_TESTING_HOST 

I get the right thing back, so it's definitely set...

**Comment by e2corporation** [comment]
@megankj Can you provide some of the build log near postbuild with the failure msg?

**Comment by megankj** [comment]
This is from npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test-env-var' ]
2 info using npm@2.15.9
3 info using node@v4.5.0
4 verbose run-script [ 'pretest-env-var', 'test-env-var', 'posttest-env-var' ]
5 info pretest-env-var amp-html@0.1.0
6 info test-env-var amp-html@0.1.0
7 verbose unsafe-perm in lifecycle true
8 info amp-html@0.1.0 Failed to exec test-env-var script
9 verbose stack Error: amp-html@0.1.0 test-env-var: `if [ -z "${AMP_TESTING_HOST}" ]; then echo "ERROR: Please set the 'AMP_TESTING_HOST' environment variable. If you are in heroku this can be set by executing 'heroku config:set AMP_TESTING_HOST=my-heroku-subdomain.herokuapp.com' on the command line."; exit 1; fi`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid amp-html@0.1.0
11 verbose cwd /Users/meganj/amphtml
12 error Darwin 15.6.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test-env-var"
14 error node v4.5.0
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error amp-html@0.1.0 test-env-var: `if [ -z "${AMP_TESTING_HOST}" ]; then echo "ERROR: Please set the 'AMP_TESTING_HOST' environment variable. If you are in heroku this can be set by executing 'heroku config:set AMP_TESTING_HOST=my-heroku-subdomain.herokuapp.com' on the command line."; exit 1; fi`
17 error Exit status 1
18 error Failed at the amp-html@0.1.0 test-env-var script 'if [ -z "${AMP_TESTING_HOST}" ]; then echo "ERROR: Please set the 'AMP_TESTING_HOST' environment variable. If you are in heroku this can be set by executing 'heroku config:set AMP_TESTING_HOST=my-heroku-subdomain.herokuapp.com' on the command line."; exit 1; fi'.
18 error This is most likely a problem with the amp-html package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     if [ -z "${AMP_TESTING_HOST}" ]; then echo "ERROR: Please set the 'AMP_TESTING_HOST' environment variable. If you are in heroku this can be set by executing 'heroku config:set AMP_TESTING_HOST=my-heroku-subdomain.herokuapp.com' on the command line."; exit 1; fi
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs amp-html
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls amp-html
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by e2corporation** [comment]
That looks like a local build operation, not a remote build on Heroku. Do you have AMP_TESTING_HOST defined as a local environment var? 

`amphtml]$  export AMP_TESTING_HOST=[heroku_url]`

**Comment by megankj** [comment]
That doesn't work either.  Attaching another build log.
[log.txt](https://github.com/ampproject/amphtml/files/570641/log.txt)

**Comment by megankj** [comment]
Turned out to be a compiler error which when fixed made everything work.  Thanks!

**Comment by megankj** [comment]
Is it expected that this won't let you test over HTTPS?

**Comment by jridgewell** [comment]
No, we should allow HTTPS as well.

**Comment by erwinmombay** [comment]
i'll take a look
