### ISSUE TITLE
Optimizing custom fonts loading

### ISSUE THREAD

**Issue by luboskmetko** [ampproject/amphtml#536]
Shouldn't you come up with a solution for optimized custom fonts loading? In your example at https://www.ampproject.org/how-it-works/ the PageSpeed Insight reports https://fonts.googleapis.com/css?family=Georgia|Open+Sans|Roboto as a render blocking resource.

**Comment by dvoytenko** [comment]
We are working on this. Some newer DOM APIs might give us enough tools and if not we eventually hope to involve service worker to assist. The idea is to get to "load for second viewing" workflow.

**Comment by cramforce** [comment]
Closing in favor of #136

Totally something we need to work on. There are some fonts that are critical (logos) and some that are not.
