### ISSUE TITLE
8s wait for fallback is too long

### ISSUE THREAD

**Issue by pierrefar** [ampproject/amphtml#5367]
From [chat on Twitter](https://twitter.com/cramforce/status/782042350893735936) with @cramforce.

## Short description of your issue:

Google's new blog.google website has AMPHTML alternate pages that were not loading AMP because of a CSP policy (I didn't look and I'm using Malte's diagnosis).

The problem is that 8 second wait with a blank screen waiting for AMP to load, then fail and use the fallback experience is too long. [Widely-cited research beginning from 1993](https://www.nngroup.com/articles/response-times-3-important-limits/) says after 1s people's attention is interrupted and they'll start dropping off. This research has held up in more recent (examples [1](https://www.thinkwithgoogle.com/articles/the-google-gospel-of-speed-urs-hoelzle.html), [2](https://research.googleblog.com/2009/06/speed-matters.html)). 

8s is pushing it, and it's close to the max anyone would wait.

There are several approaches to fixing this, including:

1. Lowering the 8s max wait. Based on my limited knowledge, this is my preferred approach, and without real-world data, I'd suggest a very aggressive 1s max wait with the view that if AMP doesn't load in 1s, something is wrong.
2. Better tooling so that this issue is flagged in development. How is a different question.

**Comment by cramforce** [comment]
The tooling flagged it clearly in development, so that wouldn't have helped. The developers of the blog programmed a bug. We can't protect against all possible bugs.

This is a very special variant of what the 8s is designed for. It typically triggers on extremely bad network conditions where users experience load times near the 99%ile around 10-100s and so 8s seems appropriate.

**Comment by cramforce** [comment]
It is also worth mentioning that a typical non-AMP page would likely have not loaded at all with the same delivery bug, so, I think, this is 100% working as intended.
