### ISSUE TITLE
Uncaught TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#5369]
super easy to replicate here: https://cdn.ampproject.org/v/iltirreno.gelocal.it/massa/cronaca/2016/10/01/news/la-casa-va-all-asta-imprenditore-si-toglie-la-vita-1.14185249/amp/?amp_js_v=5

its _context.clientId which seems to have a reference to `amp-user-notification`

**Comment by erwinmombay** [comment]
@lannka can you look at this?

**Comment by lannka** [comment]
Might be fixed by #5290
