### ISSUE TITLE
Currency caching on sites with currency set by cookie for AMP Product Pages

### ISSUE THREAD

**Issue by dom-devel** [ampproject/amphtml#5376]
## AMP Pages will be cached with the incorrect currency

As AMP is used for more types of pages, we will run into this potential problem with AMP product pages.

Googlebot (or whoever is caching AMP pages) will crawl and cache AMP pages from a single country. They will therefore serve a product page with a single currency. However for users from another country this could be very disorientating and perhaps prevent purchasing at all. (Seeing the price of products in dollars for UK customers for example.)

While sites with a page for each country won't run into this problem, sites with a single page, who use pop-ups and a cookie to switch currency, or IP detection, won't be able to solve this. 

I would suggest we need a way to deal with currency switching for AMP pages with prices on them.

(I can't work out how to add an enhancement label, could someone add one for me?)

**Comment by jridgewell** [comment]
/to @rudygalfi. I believe we're trying to solve this with `<amp-fresh>` or Geo detection features.

**Comment by ericlindley-g** [comment]
Enabling geo-variation would fix this, but it's still in early stages, with a lot of tricky details to work out. FWIW, I don't think `<amp-fresh>` would fix, because I believe the plan there is to just fetch updates to the same document from the host.

Workarounds until geo-variation is supported might include using `<amp-list>` to make a server call for price content on the first load, or to use `<amp-iframe>` (ideally with a placeholder) for just the part of the page that would show the price—though both of these have drawbacks, particularly if they're in the first viewport. @cramforce as FYI for any thoughts

@dom-devel, can you share details on how you implement changing currency based on geo on your canonical site?

**Comment by jridgewell** [comment]
> I don't think <amp-fresh> would fix, because I believe the plan there is to just fetch updates to the same document from the host.

And they can return the correct price?

**Comment by ericlindley-g** [comment]
@jridgewell True. I believe `<amp-fresh>` would return the correct price in whatever currency is already present in the document on the client (if the price had changed from $3.99 to $4.99 in the time between when the document was initially loaded on the client, and when `<amp-fresh>` requested the host document again, for instance), but I don't think there are plans to enable switching currency **based on user geo** via `<amp-fresh>` (for instance, if the price in the cache doc were $3.99, it wouldn't update to 3.56 euro for a user somewhere in the EU)

**Comment by jridgewell** [comment]
But it's arbitrary what the server can return? And it's just a request to their servers, so they can geo locate based on the IP?

**Comment by ericlindley-g** [comment]
@rudygalfi  and @erwinmombay would know more, but I thought `<amp-fresh>` was like `<amp-live-list>`, in that update requests are sent to the same host document (the cache, if the page on the client was originally requested from the cache). If the request always goes to the original publisher's servers, even when the original document is served from the cache, then what you're describing would be possible, regardless of where the page was originally served from.

**Comment by cramforce** [comment]
`amp-fresh` does not make direct requests to the origin. In any case, it would be wrong to use it.

Right now the misnamed `amp-list` is the only workable (but really bad) solution. Geo targeting would need to be implemented to do this well.

**Comment by erwinmombay** [comment]
can we add an alias for amp-list? (like amp-embed)

**Comment by cramforce** [comment]
Yeah, maybe amp-client-render. Might be better to make 2 extensions. A
direct one would have a more straight forward API.

**Comment by rudygalfi** [comment]
Routing to @ericlindley-g since he's been looking at geovariation.

**Comment by ericlindley-g** [comment]
Just a quick update that we're still working on this one — though will drop the label to P3 since the implementation may still take a bit more time

**Comment by ericlindley-g** [comment]
Closing this now that we have [amp-geo](https://www.ampproject.org/docs/reference/components/amp-geo), but please re-open if this doesn't address the need here.
