### ISSUE TITLE
Cleanup: Remove --nti flag from compiler when NTI is the default.

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#5379]
See https://github.com/ampproject/amphtml/pull/5378
- [ ] remove the `--nti` flag
- [ ] change `function(?)` to `function(*)` and `{function(new:T, ?)=}` to `{function(new:T, *)=}` in `service.js`
- [ ] remove `nti.extern.js` and `oti.extern.js` (merging `nti.extern.js`  to `amp.extern.js`)

**Comment by aghassemi** [comment]
related to https://github.com/ampproject/amphtml/issues/5335

**Comment by rsimha-amp** [comment]
Obsolete.
