### ISSUE TITLE
Video should go to fullscreen mode on orientation change into landscape

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#5380]
If a **visible** video with **landscape aspect ratio** is **playing** (autoplay or user-initiated) in the middle of the screen in **portrait** mode and user rotates device into **landscape**, it is a strong signal user wants immersive fullscreen and therefore video should automatically go into fullscreen mode.

We may want to put this behind a page-level config (ideally opt-out).

UX thoughts? @cramforce @rudygalfi @edlea-g

**Comment by aghassemi** [comment]
+ @abeck000

**Comment by cramforce** [comment]
Assuming the video is in portrait. We should do this only if major platforms such as FB and Snapchat do it.

**Comment by aghassemi** [comment]
Added the aspect ration requirement to the description.

FB (Native): Doesn't do this for autoplay videos, user-played videos always go to fullscreen mode anyway, so this is not applicable for non-autoplay videos. Same with twitter.

FB(Web): Unlike native, videos do play inline but orientation change does nothing. 

Snapchat(Native): All videos are immersive fullscreen to start with, so not applicable.

YouTube(Native): Does this in native app

YouTube(Web): Does NOT do it on mobile web (despite UI mimicking native)

Washington Post(Native): Landscape orientation change not event allowed.

so lots of different UX out there.

What we do here could be just an element-level attribute as well so authors can decide based on their content if it make sense to go to fullscreen on orientation change. Or we could just do this for `fixed hero` videos

**Comment by aghassemi** [comment]
Merged with **Hero** video requirements.
