### ISSUE TITLE
.-amp-sidebar-mask is included but hidden by default

### ISSUE THREAD

**Issue by jp26jp** [ampproject/amphtml#5394]
AMP Version: 1475106123549
Sidebar Version: 0.1

The sidebar mask that's supposed to become visible when the sidebar nav is toggled has a default `display` attribute of `none`. 

[Example](https://www.j-26.com/ampseo/essentials/webpages/)

**Comment by sriramkrish85** [comment]
This has been fixed on Friday! Will be available on prod soon ! Thanks for filing the bug!
