### ISSUE TITLE
AMP analytics per-request transport (and other) options. Make 'request' a proper object.

### ISSUE THREAD

**Issue by Gueorgi** [ampproject/amphtml#5401]
AMP analytics transport spec currently is stand-alone info affecting all request.

This means for example there is no way to use the new (and important) Yandex analytics setup with any other request but perhaps the GA since the Yandex request does not permit image protocol (it allows only for beacon & xhrpost) while the rest all require image protocol.

This hinders development of AMP analytics using remote JSON config with multiple request inside since all of these right now must use the same transport setup (till Yandex, that meant the lowest common denominator: image) thus not benefiting form vendors implementation of beacon/xhrpost support and in case of some like Yandex forfeiting their use altogether.

Request: make the amp-analytics an object that has transport property:
"requests": {
    "plainOldRequest":
      "foo.com?${foo}&${bar}",

```
"functionallyEquivalentNewRequest": {
  "url": "foo.com?${foo}&${bar}",
  "transport": { "beacon": false,
    "xhrpost": false, "image": true },
},
```

....
}

This also would allow in future to add additional features for the request like max hit count (i.e. don't send more the 1 or 2 hits) and be able to specify the body of post requests:

"requests": {
    "requestWithJSONBase64Encoded": {
      "url": "foo.com?${foo|base64}",
      "maxRequests": 1,
    },

```
"requestWithJSONBody": {
  "url": "foo.com?ac=${account_id}",
  "body": "${foo}"
}
```

...
}

**Comment by ericlindley-g** [comment]
cc / @rudygalfi

**Comment by lannka** [comment]
This is mainly for remote config use cases that return multiple vendor configs. The same transport config will be applied to all the vendors, and most likely end up with ` the lowest common denominator: image`.

I can see this being a problem for tag managers like GTM or OGT.

One solution is to introduce `request` or `trigger` level override, as proposed here by @Gueorgi. 
Another way to do this is to allow URL prefix filters in transport:

```
transport: {
  beacon: ["https://google-analytics.com"],
  image: true
}
```

**Comment by zhouyx** [comment]
Interesting, since we've already support request as an object. @lannka do you think if we can allow individual request to override the transport method?
