### ISSUE TITLE
CSS columns causing some images not to load in iOS

### ISSUE THREAD

**Issue by alisonkohl** [ampproject/amphtml#5409]
When using CSS columns, images not in the first column never load on iOS browsers (Safari and Chrome). Behavior seems fine in Chrome for desktop and Android and Safari on Desktop. It seems that because the first image in the second column is ordered after the last image in the first column, AMP is trying to load images in order as opposed to what is actually in view. Images attached below.

To repro:
Visit https://jsfiddle.net/q28zpgtb/ on an iOS device and run

Specifically occurring on Safari for iOS and Chrome for iOS.

observed on amp-version="1475106123549"

![img_0075](https://cloud.githubusercontent.com/assets/6353405/19091816/fc806a36-8a38-11e6-92c9-be6bdd67e8e8.PNG)
![img_0077](https://cloud.githubusercontent.com/assets/6353405/19091817/fc83825c-8a38-11e6-9c89-de08a59c7ba5.PNG)

**Comment by jridgewell** [comment]
This is the happiest bug report ever. 😄

**Comment by jridgewell** [comment]
Ok, so after debugging, this is not an AMP issue specifically: this is a problem with iOS shoddy CSS-GPU rendering.

[Here's a similar page](http://jsbin.com/leguto) (without AMP and extra content) that has the same problem. It appears to be some interaction with:

```css
.PinImage__link {
  border-radius: 6px 6px 0px 0px;
  overflow: hidden;
}

.PinImage__image {
  perspective: 1px;
}
```

Disabling any one of those three styles fixes the issue.

A horrible, no-good, hacky, you-really-shouldn't-do-this fix is to add:

```css
.PinImage__link {
  transform: translateZ(0); /* My GPU usage spiked! */
}

**Comment by jridgewell** [comment]
Oh, and thanks for the puppy filled day. 😁

**Comment by alisonkohl** [comment]
@jridgewell Thanks for looking into this and glad you enjoyed the puppies :)
