### ISSUE TITLE
Install error reporting in service worker

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#5411]
If possible, reuse this code,

https://github.com/ampproject/amphtml/blob/master/src/error.js#L102

…but the `new Image` probably doesn't work.

**Comment by jridgewell** [comment]
> new Image probably doesn't work.

Correct. Can we just do a GET request using `fetch`?

**Comment by cramforce** [comment]
Lets for a start, check if Image is available and use it, and fallback to
fetch otherwise.

**Comment by jridgewell** [comment]
Fixed by #6490.
