### ISSUE TITLE
amp-sidebar broken when using #development=1 in iOS devices

### ISSUE THREAD

**Issue by rohitverma007** [ampproject/amphtml#5413]
When using the AMP validator built into chrome browser, i.e, appending `#development=1` to an amp page, the sidebar is displayed behind the fixed header. This only happens on iOS devices, tested it via the built in simulator in chrome devtools as well as on an iPhone 5 (Safari) physical device. Sidebar works as expected when not in "validation mode", i.e., without the `#development=1` parameter.
## How do we reproduce the issue?

On Chrome (non-mobile):
Visit https://www.ampproject.org/#development=1 or https://ampbyexample.com/#development=1 and using chrome devtools simulate iPhone 6.

On iPhone:
Visit https://www.ampproject.org/#development=1 or https://ampbyexample.com/#development=1 on Safari

Expected behaviour:
![screen shot 2016-10-04 at 2 51 37 pm](https://cloud.githubusercontent.com/assets/3745109/19093918/20c1f0dc-8a42-11e6-8f05-8d3b04286016.png)

Actual behaviour:
![screen shot 2016-10-04 at 2 51 50 pm](https://cloud.githubusercontent.com/assets/3745109/19093923/24be539c-8a42-11e6-841b-8dfbca8ddbdb.png)
## What browsers are affected?

Safari browser on iOS devices.  
Works fine on chrome in iPhone 5 (possibly other iOS devices as well).
## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1475106123549

**Comment by sriramkrish85** [comment]
I see a inline z-indes on the header that is > that of the sidebar hence the issue. 

real issue is how z-index is getting added when there is a `#development=1`

@dvoytenko do you know of anything that might  cause this - i see a fixedlayer iframe being created only on `#development=1`

**Comment by dvoytenko** [comment]
@camelburrito It's possible that fixed transfer layer interferes here. `#development=1` turns it on iOS Safari to spot these issues easier. The onus is on the component to work correctly in both scenarios.

**Comment by camelburrito** [comment]
@dvoytenko - when there is a fixed layer - the header element gets a higher z-index - how does the component know what z-index is being added by the fixed layer?

**Comment by dvoytenko** [comment]
Sidebar should be in the fixed layer as well and thus should also get a higher z-index. Right? For a deeper answer - please see `fixed-layer.js`

**Comment by camelburrito** [comment]
![screen shot 2016-10-06 at 1 48 04 pm](https://cloud.githubusercontent.com/assets/1037311/19170037/a7417bf2-8bcb-11e6-82e2-446f89d75aac.png)

**Comment by camelburrito** [comment]
This happens only on development=1

fixedlayer recalculates style for header (since it is in the transferred layer), but does not do it for the sidebar (which is also in the fixed layer but not transferred). Will dig into it.

**Comment by dvoytenko** [comment]
This is not really because of `development=1`. This is a iOS iframe emulation mode. We simply trigger it with `development=1` so we can spot problems like this sooner. For example, this is currently a problem in production for Google Search on iOS Safari.

**Comment by camelburrito** [comment]
fixed by #6155
