### ISSUE TITLE
Video: Add integration tests that run on on Sauselab

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#5414]
See https://github.com/ampproject/amphtml/pull/5412

At minimum we should test `supportsAutoplay` on actual devices/browsers on Sauselab (simulator should be fine)

**Comment by cramforce** [comment]
Is this done?

**Comment by aghassemi** [comment]
Yes. [test/integration/test-video-player.js](https://github.com/ampproject/amphtml/blob/master/test/integration/test-video-players.js) do run on SauceLabs and since we have iOS 10 support in SauceLabs, autoplay logic does indeed get tested on real iOS.
