### ISSUE TITLE
ServiceWorker can't fetch new .js file that's not cached before

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#5416]
Thanks to @jridgewell for the explanation on how service worker will try to fetch the cached version. In the race condition where the same client try to fetch multiple files we will stick to the first version we get. I see one potential issue here in the case of a brand new file (or a renamed file) is being requested, and it's never cached.

Say we have `rtvV0` and `rtvV1`. where `rtvV0` has file `A.js` and `rtvV1` has a new file `New.js`. then there's a client id `client01`.  when the service worker fetches for file A.js, it will set `clientMap[client01] = rtvV0`. And when this same client tries to fetch `New.js`, it will fail because `rtvV0` doesn't contain `New.js`.  

The fact that a file will be there a week before it's in prod makes this issue less possible, but I think it is still quite possible. 

@cramforce @jridgewell

**Comment by cramforce** [comment]
This can definitely happen. We have a similar problem today, where we cannot do a canary diversion to files that do not exist in prod.

Similarly, you can get an old version of a file where the feature is still experiment guarded.

This isn't as nice as always getting the fresh version, but the benefits of never (asymptotically) having to wait for the network seem to outweigh it.
