### ISSUE TITLE
Add ability to "Add to calendar" on amp-socialshare ?

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#5418]
Add ability to "Add to calendar" on amp-socialshare ?

**Comment by camelburrito** [comment]
CC @mkhatib @dvoytenko

**Comment by cramforce** [comment]
Is there a common scheme for this?

**Comment by ericlindley-g** [comment]
I like this idea generally—add to calendar actions would be nice to support. I second Malte's question, and wonder, is amp-social-share the right place for this? The general mechanic for these is similar, but the semantics start to get a little muddy.

**Comment by camelburrito** [comment]
@ericlindley-g i am not very picky on where this lives - i think this might be light weight enough to put it here. I don't really feel we need a separate component for it. WDYT?

**Comment by Lillian-wang** [comment]
@camelburrito, how would this feature work? Would we give developers a list of the most calendars to choose from? e.g.:
<amp-social-share type="calendar" calendar="[google|ical|yahoo|outlook|outlook online]"></amp-social-share>

Addtocalendar.com supports google, ical, yahoo, outlook and outlook online, so we could follow that as an example.

**Comment by Lillian-wang** [comment]
Oops previous code sample didn't show up. I've added quotes it, so you can see it now.

**Comment by camelburrito** [comment]
you should use data-* like rest of the components i guess data-calendar-list. 

I also think we could either use a hcard format or may be the same format from Addtocalendar.com 

Could you do a small writeup of the format you are proposing (in this bug).
