### ISSUE TITLE
The carousel swipe / slide interaction is too fast

### ISSUE THREAD

**Issue by spacedino** [ampproject/amphtml#5427]
Actual behavior: As a user, when I go forward or backwards in the carousel, the image and text that transition happens too fast and looks jumpy at the end.

Intended behavior: As a user, when I go forward or backwards in the carousel, the image and text that transition should be smooth and barely noticeable. 

To reproduce: Use AMP by example template > news article. OR Use and example doc that I can point you to. 
- Swipe carousel to the left.
- Swipe carousel to the right. 

Browser: 
- chrome ios
- chrome desktop

Device type:
- mobile
- desktop

AMP version = 1475106123549

**Comment by ericlindley-g** [comment]
We tweaked this a bit before releasing, but I agree it's not ideal yet. Fixing the abrupt jump at the end would make particular impact. Slotting this in the backlog for now, though, as UX/feature work (e.g. visual indicators for progress through slides) may take priority over this polish (unless there's a quick win to be had)

**Comment by adelinamart** [comment]
@camelburrito is this still an issue?Thanks

**Comment by virgiltu** [comment]
For the love of god can you guys please fix this. They slide so fast to the point where I am not even using the module. Everyone is complaining about it. Y cant we have a transition speed just like the delay?

**Comment by aghassemi** [comment]
@virgiltu version 2 of `amp-carousel` (#20595)  is in full swing implementation and it uses CSS Snap Points which gets brings the platform native snapping. 

That being said, the current implementation is not supposed to be too fast and tries to mimic a natural swipe as much as possible. What browser are you using? could you share a GIF of what you are observing?

**Comment by virgiltu** [comment]
Please see my video here. This is a large slider. I was looking to make a section slider but that looks even worst. Even as a small slider things slide way to fast. 

http://somup.com/cqnInwnqRo

**Comment by aghassemi** [comment]
@virgiltu Thanks! I see what you mean now. that's just the timing for `autoplay`, we can certainly adjust that @nainar @andrewwatterson Some good feedback on timing for autoplay.

**Comment by aghassemi** [comment]
@virgiltu you can currently control the timing delay for autoplay using the `delay` attribute (e.g. `delay="3000"`). The animation between sides won't change but the time to advance to next one is controlled by this attribute.

**Comment by virgiltu** [comment]
@aghassemi Thank you, yes I use the delay as far as 8000. However that only delays the time between the slides, but not the transition time.  Would be nice to have more of a smooth transition.

**Comment by aghassemi** [comment]
@virgiltu, agree, that will come in carousel v2.

**Comment by virgiltu** [comment]
@aghassemi Thank you, I am looking forward to it.

**Comment by aghassemi** [comment]
carousel v2 handles this.

**Comment by virgiltu** [comment]
Can you post a link. I do not see it in the amp dev documentation

**Comment by aghassemi** [comment]
@virgiltu It is currently experimental and we are working on launching 2 additional higher-level carousel components for galleries on top. But you can check out the base version here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-base-carousel/amp-base-carousel.md

**Comment by amorphius** [comment]
> @virgiltu It is currently experimental and we are working on launching 2 additional higher-level carousel components for galleries on top. But you can check out the base version here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-base-carousel/amp-base-carousel.md

Is it implemented already? I'm having same issue but still don't see how can I make transition animation a bit slower in carousel v2.
