### ISSUE TITLE
amp-facebook video embed improvements

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#5433]
Facebook [provides few APIs](https://developers.facebook.com/docs/plugins/embedded-video-player/api) that we can use to improve `amp-facebook` video embeds. 
- Explose autoplay functionality
- Player state (playing, paused...) - Use a better event for load promise resolving
- Implement `pauseCallback`
- Use iframe-based embed (though this is not documented this is the code that is given to the user when clicking embed on the video dialog)
- Possibly dynamically generate placeholders using `https://graph.facebook.com/VIDEO_ID/picture?size=large`. This seems to only work for page-uploaded videos.

``` html
<iframe src="https://www.facebook.com/plugins/video.php?href=VIDEO_URL&show_text=0&width=560" width="560" height="315"></iframe>
```

This is possibly means we might want to create a `amp-facebook-player` instead of relying on the `amp-facebook[type=video]` current implementation.

**Comment by mkhatib** [comment]
Actually even post embedding seems to have iframe-based embedding now.

```html
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fzuck%2Fposts%2F10103152241294971&width=500" width="500" height="486" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
```

**Comment by seomaz** [comment]
what about amp-facebook with amp loader ? right now when the facebook video/post is loading the element does not have amp loader

**Comment by aghassemi** [comment]
@seomaz thanks for reporting. Created a separate issue for this: https://github.com/ampproject/amphtml/issues/13573

**Comment by cathyxz** [comment]
Feel free to file these issues separately
