### ISSUE TITLE
amp-sidebar remains open when tapping outside of it

### ISSUE THREAD

**Issue by derat** [ampproject/amphtml#5440]
AMP 1475106123549
Chrome Linux 53.0.2785.144, Chrome Android 53.0.2785.124

1. Load a page that uses amp-sidebar, e.g. https://ampbyexample.com/components/amp-sidebar/.
2. Open the sidebar.
3. Click on the document body outside of the sidebar.

Per https://github.com/ampproject/amphtml/blob/master/extensions/amp-sidebar/amp-sidebar.md, "Tapping back on the partially-visible main content area closes the sidebar."

However, the sidebar remains visible when I do this -- the only way to close it seems to be by clicking an element that explicitly toggles or hides it or by hitting Escape.

I believe that this is a fairly-recent regression and that I was seeing the documented behavior, with the sidebar closing automatically when I clicked outside of it, 2-3 weeks ago.

**Comment by camelburrito** [comment]
@derat Thanks for filing, we already found and have a fix merged. 
Dup of #5362

**Comment by derat** [comment]
Great, thanks! I unfortunately searched for [amp-sidebar] rather than [sidebar] when trying to see if this had already been reported. :-)

**Comment by camelburrito** [comment]
It's good to have bugs filed :) thanks for taking the time !
