### ISSUE TITLE
amp-ad tag with type "_ping_" deleting its iframe after loading

### ISSUE THREAD

**Issue by xgretsch** [ampproject/amphtml#5442]
## Short description of your issue:

&lt;amp-ad&gt; tag with type "\_ping\_" is loading everything correctly, but the ad never shows: the iframe inside the &lt;amp-ad&gt; is being deleted.

## How do we reproduce the issue?

https://bachtrack.com/amptest.html

Just load the file, and watch the Network tab on developer tools. You will see that the iframe is created, the source remotetest.html is loaded into it, that the console.log() statements in remotetest.html are all executed correctly, and that the ad image is fetched correctly by the browser.

If you set a breakpoint, you can verify that the iframe is there by looking in "Elements".

However, at the end of the run, the iframe has been deleted. The &lt;amp-ad&gt; tag is there, but the iframe is not.

## What browsers are affected?

I'm on OS X El Capitan 10.11.6: the problem happens on all of Chrome (v 53.0.2785.143), Safari, Firefox.

## Which AMP version is affected?

The AMP version is 1475106123549

This is a new problem - it was still all working on 28th September, and was broken yesterday (4th October).

**Comment by lannka** [comment]
@xgretsch `_ping_` is used for test only. The behavior is actually as expected, it timed out and ended up with a fallback with iframe removed.

Is there any specific reason you want to use type `_ping_`?

**Comment by xgretsch** [comment]
I used type {\_ping\_} because it seemed to be the only one that could be used with a custom  {amp-3p-iframe-src}, which, as I understand it, is the only way to serve ads from my own domain.

So if {\_ping_\} is for test only, can you please tell me what ad type I should be using, when I'm just serving my own ads and not using a third party ad network?

**Comment by lannka** [comment]
@jasti do you think we will add support to a custom ad server? I think if we allow this path, it will be eventually similar to have ads in `amp-iframe`.

**Comment by xgretsch** [comment]
@jasti Can I add my $0.02 worth? 

I do not think that it is proper for AMP to discriminate against small website publishers who want to sell their own ads, in favour of large ad networks.

So here's what I'm doing: I have done a pull (my first ever Github pull!) and just about finished implementing my own site as an ad network, following all the rules. Soon, I will push this, and expect it to be accepted since it's not doing anything that other ad networks don't do.

However, it's been a lot of work and it does seem to be adding unnecessary clutter to the 99.999% of AMP users who aren't going to buy ads from us.

I could make my "network" generally useful simply by having a `data-url` as part of the spec of the network and publishing sample source code for the ad server. I'm very happy to do this if you guys would like me to, in the interest of helping other small Internet businesses.

And by the way, I have no objection to obeying sensible rules on what ads can do. Ours are actually very simple - static images or animated gifs that don't ever spill outside the iframe boundary and don't need resizing.

**Comment by amphtml-team** [comment]
I don't think we have an issue as long as you use amp-ad to serve ads
instead of amp-iframe.

For now, we should keep your implementation separate, so we know who to
contact when there is an issue with an implementation.
@cramforce

**Comment by cramforce** [comment]
For what its worth, the reason this doesn't work, is because you need to call the callback that is passed as the second argument to the `draw3p` callback.

Note, that after you fix this, the code will be still broken, because one cannot use `document.write` in an async callback.

The implementation of an ad network will not be accepted if it is used by only one site.

If you see the ads yourself, why not just inline them into the document?

**Comment by xgretsch** [comment]
@cramforce The ads are selected randomly from a pool, so if I inline them, it would not be possible to cache the page. And that would lose one of the main points of using AMP.

I'm being told not to use `_ping_` except for testing. You're saying I can't set myself up as an ad network - so I can't use `amp-ad`. And I'm expressly forbidden from using `amp-iframe`.

So can you tell me what you're expecting me to do? Or are you saying that AMP refuses to support websites that serve their own ads? (which would seem terrifically unfair).

**Comment by cramforce** [comment]
I don't currently have a good answer for this, but we should probably discuss in an issue titled "Support for custom ad servers" or something like that. I think we should probably support it, as that is better than not-supporting it while I also having no way to precent it :)

**Comment by lannka** [comment]
It's probably a valid use case for "house ad" (your own ad).

However, my only concern is that it can become a corner cutter that publishers will use for new ad networks that haven't had a presence in AMP. Otherwise the requirements would go to the ad networks for an official AMP support.

That will lose all the benefits of having an official support in AMP (all those APIs). I think this is one of the reasons why we don't want publishers to use amp-iframe for ad.

**Comment by cramforce** [comment]
Definitely, but custom `amp-ad` is better than custom `amp-iframe`. Definitely has downsides in terms of long term ability to make updates. I'm not yet decided what the right way forward is.

**Comment by xgretsch** [comment]
I can suggest an alternative, that I'm willing to implement and which would give my users the best performance. I would implement a new add-in called something like `<amp-imagead>`. This would not use an iframe: at runtime, it would be filled by an `<img>` tag wrapped in an `<a>` tag. It would contain a parameter with the URL to be used for fetching the ad, but this would not fetch javascript: it would simply fetch the image, the target URL and (optionally) some parameters to be sent to Google Analytics `ga.send('event')`.

The advantage of this is that all ads on the page can be fetched by a single network request, so it's super-fast. The code at the server end can choose whether to serve the image as the URL of a file (more network requests, but cacheable) or a data URL (no additional network requests, but the files won't live on a CDN cache anywhere.

This solution would have lots of benefits:

(a) The best possible performance for self-serve ads

(b) No compromise to the rules on `<amp-ad>` or `<amp-iframe>`, and no need to bloat `amp-ad` with spurious ad networks

(c) Can be subject to the usual rules about "the size must be fixed", etc.

(d) No risk of abuse - the developer isn't getting the chance to run any of his own Javascript.

If I write such an extension, do you guys think it would be accepted?

**Comment by cramforce** [comment]
I would love this.

**Comment by xgretsch** [comment]
Great - watch this space (or, to be precise, the push requests). There may be screams for help in the Slack feed, as I have never, ever worked with any of these tools or libraries before!

**Comment by lannka** [comment]
Instead of making it a separate extension, what do you folks think about having it as a sepcial type in `amp-ad`?

`<amp-ad type="imagead">`

The logic will be exactly the same as @xgretsch described, instead of creating `iframe`, it creates `img`. Or if we don't like overload the type concept, we can introduce new attribute.

Keep them in same extension so that we don't need to keep a list of ads extensions, as we treat them  differently than other extensions.

**Comment by cramforce** [comment]
I fall this does is

```js
xhrFor(window).getJson(this.getAttribute('data-src')).then(obj => {
  const image = new Image();
  image.src = obj.imageSrc;
  var a = document.createElement('a');
  a.href = obj.href; // TODO: Sanitize
  a.appendChild(image;)
  this.element.appendChild(a);
});
```

then a new extension probably makes more sense :)

**Comment by lannka** [comment]
@cramforce not sure why 2-round trips are necessary here. Can't the ad server just return the image ad in a non-cachable response in the first round-trip?

**Comment by cramforce** [comment]
@lannka You could return the image with the JSON as a base64 payload. You probably want to retrieve image URL and click URL in the same request to avoid stateful servers.

**Comment by lannka** [comment]
@cramforce make sense.

Back to the separate extension discussion. If all you want is cleaner code separation, we can have the code in a separate element AmpImageAdElement, and let amp-ad upgrade to it when appropriate.

Or is the code size the actual concern?  I actually don't see too much code will be added.

Again, I just don't like to introduce another new extension for ad, we'll need to change many other things, such like amp-sticky-ad.

**Comment by cramforce** [comment]
Could this use the A4A implementation mechanism?

**Comment by lannka** [comment]
@cramforce yep, that is what I was thinking

**Comment by lannka** [comment]
Opened an "intent to implement": #5541. Let's have further conversation over there.
