### ISSUE TITLE
this.loadPromiseResolve_ is not a function errors

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#5446]
I am seeing bunch of `this.loadPromiseResolve_ is not a function errors` on HEAD (just load `everything.amp.max.html` and scroll a bit). Not seeing it on CDN (Prod or Canary).

Will investigate.

/cc @jridgewell @dvoytenko @erwinmombay FYI

**Comment by zhouyx** [comment]
this seems to be the reason #5398
