### ISSUE TITLE
Support for IBM Digital Analytics (Coremetrics)?

### ISSUE THREAD

**Issue by dblankenbaker** [ampproject/amphtml#5447]
Is anyone working on adding IBM Digital Analytics (Coremetrics)?

**Comment by rudygalfi** [comment]
AFAIK, nobody from IBM Digital Analytics has yet engaged with the AMP Project. @dblankenbaker Do you have any contacts there that you could point to this issue?

**Comment by dblankenbaker** [comment]
Yes--I'm at IBM and we'd like to engage.

**Comment by jridgewell** [comment]
@dblankenbaker: Either @rudygalfi or @ericlindley-g as our product managers, or @avimehta who oversees the analytics integrations in AMP.

**Comment by rudygalfi** [comment]
@dblankenbaker Do you have any questions about integrating IBM Digital Analytics with AMP?

The key thing to know is that AMP will not allow any JS to run on the main page, which means the instrumentation for analytics is handled by AMP and a [vendor config](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/vendors.js) can be defined to specify how hit requests should be formed and where the data should be sent (so you could have a `<amp-analytics type="ibmdigitalanalytics">...</amp-analytics>`.

Also check out this page if you haven't seen it yet, for more about how amp-analytics works from a developer perspective: https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md

**Comment by dblankenbaker** [comment]
Hi. I do have questions, but they are from a process perspective vs a development perspective. @rudygalfi --I sent you an invite to connect via LinkedIn, but couldn't include my email. It's dblanken@us.ibm.com. If you could send me a note via email, that would be great.

**Comment by rudygalfi** [comment]
Closing this for now since there hasn't been any activity. Please re-open if further discussion is needed or if there's a pull request.
