### ISSUE TITLE
amp-ad not centering with multi-size and layout=responsive

### ISSUE THREAD

**Issue by walia** [ampproject/amphtml#5448]
## Short description of your issue:
Having an issue with 300x250 ad not centering when within a multi-size ad.
![300x250](https://cloud.githubusercontent.com/assets/6536430/19164102/9d8e13d0-8bcc-11e6-905c-7b05ec64f535.png)

## How do we reproduce the issue?

code snippet: http://jsbin.com/yacejajume/edit?html,console,output

## What browsers are affected?
all

## Which AMP version is affected?
Version 1475106123549

**Comment by jasti** [comment]
@walia I can't seem to reproduce it consistently.  Works every time on my end. What device and browser are you using?

![screen shot 2016-10-06 at 2 52 46 pm](https://cloud.githubusercontent.com/assets/2366341/19166257/d79b2bfa-8bd4-11e6-8921-5c314a84bf8b.png)

@glevitzky @lannka FYI

**Comment by walia** [comment]
I have adjusted the code snippet. It needed more text so that the ad is below the viewport and can resize. I am using chrome on iOS.

![image](https://cloud.githubusercontent.com/assets/6536430/19167139/5cede4c0-8bd8-11e6-9601-457feb231fb3.png)

**Comment by jasti** [comment]
This is WAI. 
layout= responsive will always align the creative left to right. It expects a responsive image, but what's returned is a fixed size image.
Why not just center align the ad all the time?
http://jsbin.com/suhebuyoxo

**Comment by walia** [comment]
The `<center>` element is a deprecated tag. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center.

**Comment by jasti** [comment]
Was talking Brian Anderson on Slack. We think this can work with DFP creative wrappers. Good luck!

**Comment by banderson623** [comment]
Thanks for the support @jasti !
