### ISSUE TITLE
TypeError: Cannot read property 'amp-share-tracking' of undefined

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#5453]
We're seeing an issue were `window.ampExtendedElements`  is undefined possibly in `isElementScheduled` call inside `src/element-service.js`

```
TypeError: Cannot read property 'amp-share-tracking' of undefined
    at https://cdn.ampproject.org/rtv/001475174282386/v0.js:48:660

TypeError: Cannot read property 'amp-experiment' of undefined
    at https://cdn.ampproject.org/rtv/001475174282386/v0.js:48:660
```

**Comment by erwinmombay** [comment]
@jridgewell has a quick fix but we want to make sure this isn't an ampdoc related issue
cc @dvoytenko

**Comment by erwinmombay** [comment]
this doesnt seem to be in production but in the current canary that is about to go out

**Comment by jridgewell** [comment]
For more context, this is coming from:

1. [`UrlReplacements.constructor`](https://github.com/ampproject/amphtml/blob/1ba0160/src/service/url-replacements-impl.js#L82-L89)
  2. [`shareTrackingForOrNull`](https://github.com/ampproject/amphtml/blob/1ba0160/src/share-tracking-service.js#L28-L29)
    3. [`getElementServiceIfAvailable`](https://github.com/ampproject/amphtml/blob/1ba0160/src/element-service.js#L62)
      4. [`isElementScheduled`](https://github.com/ampproject/amphtml/blob/1ba0160/src/element-service.js#L84)

**Comment by dvoytenko** [comment]
@jridgewell Did you see if that document actually defined the share-tracking script? I have concerns that this fix will create false negatives, as in will report that service is not available when in fact it is. Perhaps a better (hacky) fix would be to instantiate `window.ampExtendedElements` in the bootstrap `amp.js`?

**Comment by jridgewell** [comment]
The [doc](https://cdn.ampproject.org/v/www.forbes.com/sites/scottmendelson/2016/01/19/tyler-perry-reteams-with-lionsgate-for-boo-a-madea-halloween/amp/?amp_js_v=5) does not include the share-tracking script, which is totally fine.

> Perhaps a better (hacky) fix would be to instantiate window.ampExtendedElements in the bootstrap amp.js?

Nah, that won't help. We'll run into the following case.

> as in will report that service is not available when in fact it is

I see. Currently, if the element service hasn't been scheduled yet, it'll wait until the body is available. Maybe we should change that to wait until the document is complete?
