### ISSUE TITLE
403 for remote CSS

### ISSUE THREAD

**Issue by AutoSponge** [ampproject/amphtml#546]
The demo page, https://www.ampproject.org/how-it-works/, returns a 403 for me on Chrome and Safari when trying to access `https://fonts.googleapis.com/css?family=Georgia|Open+Sans|Roboto`.

![screen shot 2015-10-08 at 4 51 24 pm](https://cloud.githubusercontent.com/assets/654530/10379761/1c058346-6dde-11e5-8dcf-6cc59230fec1.png)

**Comment by cramforce** [comment]
Fixing already.

**Comment by erwinmombay** [comment]
@AutoSponge thanks for bringing this up! we're fixing this. keeping this issue open until it actually is.

**Comment by erwinmombay** [comment]
fixed.

https://www.ampproject.org/how-it-works/
