### ISSUE TITLE
AMP Product page carouselstarted jumping/flickering & drawer/sidebar menu has stopped working

### ISSUE THREAD

**Issue by ScotsScripts** [ampproject/amphtml#5466]
I've been incorporating AMP into an ecommerce platform and everything was working fine when I took break to work on something else a week or two ago, but this morning when I came back to it the product carousel had started to flicker/vibrate/jump on every slide and the sidebar/drawer (hamburger menu) has stopped working.

Here is a sample product page. The last time I worked on it everything was working perfect:

https://dts2480.mivamerchantdev.com/mm5/merchant.mvc?Screen=PROD_AMP&Product_Code=p1

In firefox the image seems to vibrate. In chrome/canary it flickers/resizes/jumps. The drawer menu has stopped working altogether. 

Any ideas? Thanks!

**Comment by jridgewell** [comment]
I believe @camelburrito fixed this.

**Comment by camelburrito** [comment]
@ScotsScripts - The fliker happens with some desktops/laptops with older GPUs - and it has been fixed in and will be live next week (you can opt in to our dev channel to verify) - https://github.com/ampproject/amphtml/pull/5435

For the sidebar not showing up - remove the display: none here. 
``` css
#drawermenu {
    width: 320px;
    background-color: white;
    display: none;
}
```

**Comment by ScotsScripts** [comment]
Thanks for checking into this! I'm glad the flicker is going to go away. The drawermenu fix did not work for me. Was there a change in the drawermenu js/css recently that caused this? I'll look into pulling in the most recent CSS and see if that fixes it.

**Comment by camelburrito** [comment]
@ScotsScripts - we did cause and fix an unrelated issue (https://github.com/ampproject/amphtml/pull/5365) on amp-sidebar - let me know if you need more help with this.

**Comment by ScotsScripts** [comment]
I'm not super savvy here as far as where to find the update. I've been checking various links in this thread but see only snippets. Will you point me in the right direction? Thanks, I appreciate the help.

**Comment by camelburrito** [comment]
@ScotsScripts - You can checkout the fix for the jitter on our dev channel. 
https://cdn.ampproject.org/experiments.html  turn on dev channel here

**Comment by ScotsScripts** [comment]
Thanks! Now for a total github newbie question, after I turn on the dev channel where is it? I've been looking around but sometimes I miss the obvious.
