### ISSUE TITLE
Install Core Runtime Styles into Test Iframes

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#5476]

**Comment by dvoytenko** [comment]
Do you want to do it in all iframes? Or only fixtures?

**Comment by jridgewell** [comment]
@camelburrito?

**Comment by dvoytenko** [comment]
We should definitely do this in `describes.js`.

**Comment by jridgewell** [comment]
👍

**Comment by camelburrito** [comment]
@dvoytenko - all iframes :) hope this is not too late

**Comment by dvoytenko** [comment]
It's in all iframes now.
