### ISSUE TITLE
amp-sidebar mask issue

### ISSUE THREAD

**Issue by Arun1048576** [ampproject/amphtml#5477]
Please walk through the following steps for reporting an issue about AMP:

amp-sidebar has an issue. The amp-mask does not seem to get displayed when the sidebar opens. In the example given on ampbyexample.com, it seems amp-sidebar works fine when the code comes from the service worker, and on hard reload it doesn't. I think the service worker has cached a previous version of amp-sidebar and in the new version some code is missing. 

## How do we reproduce the issue?
1. Goto https://ampbyexample.com/components/amp-sidebar/
2. Do a hard reload so that amp-sidebar comes from CDN.
<img width="1279" alt="screen shot 2016-10-08 at 11 10 47 am" src="https://cloud.githubusercontent.com/assets/6386948/19210692/f1b4b668-8d47-11e6-9aaf-3d18318a78ea.png">
As we can see the code of amp-sidebar-0.1.js does not have the code to give amp-mask the display block property. Now the sidebar does not close on clicking outside.

3. Now try again and let the code now come from service worker
<img width="1276" alt="screen shot 2016-10-08 at 11 13 55 am" src="https://cloud.githubusercontent.com/assets/6386948/19210704/568babbe-8d48-11e6-953b-5fcba9617a14.png">
As we can see the code which comes from service worker is different from the one from CDN and now the sidebar closes on clicking outside.

**Comment by camelburrito** [comment]
This has been fixed and cherrypicked to prod . Just checked on an incognito tab works now

**Comment by Arun1048576** [comment]
@camelburrito Thanks !
