### ISSUE TITLE
Gzipped AMP JS files can be further reduced by ≈ 4%

### ISSUE THREAD

**Issue by JoeArizona** [ampproject/amphtml#5478]
Today's gzipped AMPv0.js file weighs in at 52,618 bytes. This can be reduced to approximately 50,800 bytes by using a better gzip compressor. I ran zopfli, libdeflate, and ECT on it, and they all deliver a file size in that sub-51K ballpark. Files like this should be maximally compressed in advance (I assume it isn't being gzipped on-the-fly by the Google AMP CDN servers, but was compressed once in advance, probably by zlib or GNU gzip).

I saw similar results for other AMP modules, like the ad js.

Note that employing better gzip compression upfront doesn't impose any costs for decompression on the client. gzip is pretty cool that way. Decompression rate (MB/sec) and CPU and RAM overhead are pretty constant regardless of compression level or compressor efficiency, so reducing the size of these files is a clean, albeit small, win.

**Comment by cramforce** [comment]
Yep, no need to track here, since this is just a function of support on the serving system side that is not part of the open source project, but we will start serving both `brotli` and slightly less likely `zopfli` payloads.
