### ISSUE TITLE
Strange flickering resize effect in amp carousel

### ISSUE THREAD

**Issue by Arnold85** [ampproject/amphtml#5479]
A few days ago a did not see this behaviour. Today the first amp-carousel on my website https://hpphysio.com/fortbildung-zum-heilpraktiker-physiotherapie/ has an anooying flickering resize effect. You can see it in chrome but much more in firefox.
Searching for a possible error I recognized that the same behaviour can be seen on https://ampbyexample.com/components/amp-carousel/ for the carousel with the food pictures. So it seems to be an error in a newer AMP-Version (which is now "1475796420615" on my desktop pc).

**Comment by Arnold85** [comment]
in the dev tools I can see the "amp-no-scroll" property on the <div class="amp-slides-container"> appear and disappear just as the picture resizes.

**Comment by Arnold85** [comment]
deleting the 	overflow-x:hidden!important from the class 
```
.-amp-slides-container.-amp-no-scroll {
	overflow-x:hidden!important
}
```
resolves the problem.

**Comment by camelburrito** [comment]
@arnold85 we have ready identified and fixed this issue (happens on some old model GPUs) the fix will be live with the next release
