### ISSUE TITLE
Replace CSS opacity reset with JavaScript

### ISSUE THREAD

**Issue by adactio** [ampproject/amphtml#548]
I'm concerned by this mandatory part of the spec:

    <style>body {opacity: 0}</style><noscript><style>body {opacity: 1}</style></noscript>

There's a conflation here between availability of JavaScript and a CSS declaration: there's an assumption that the JavaScript will always successfully overwrite something that has been set with CSS. It feels like crossing the streams. The noscript solution feels like a very fragile way of providing a fallback, that [won't work in many situations](http://kryogenix.org/code/browser/everyonehasjs.html).

How about setting the default opacity with JavaScript instead?

    <script>document.body.style.opacity=0</script>

It's shorter and has the same effect; if JavaScript isn't available, the CSS doesn't get applied—no need for a noscript element. This way, the opacity is always set with the *same* technology: JavaScript.

Caveat: I'm guessing that (because of the asynchrous loading of the ampproject JavaScript file), this script element that I'm suggesting (which, like the current style element, should be blocking) would need to be placed *before* the script element that calls the external file:

    <script>document.body.style.opacity=0</script>
    <script src="https://cdn.ampproject.org/v0.js" async></script>

**Comment by dvoytenko** [comment]
Thanks for the report. I'm closing this as a dupe #323, but could you please look at that solution and make your comments there if any?

**Comment by cramforce** [comment]
Love it! Very good proposal. Lets make sure we consider this in #323!!!
