### ISSUE TITLE
Badge for validator issues?

### ISSUE THREAD

**Issue by powdercloud** [ampproject/amphtml#549]
Is it possible to assign a label for things that need to be done about the validator? Basically like a hotlist?
I think this would help avoid that stuff falls through the cracks.
@cramforce @Gregable @dvoytenko

**Comment by erwinmombay** [comment]
we can definitely add a label for validator issues :+1:

**Comment by cramforce** [comment]
Done. And just for everyone's information: Github does not allow emojis in label names.

**Comment by powdercloud** [comment]
Awesome, thanks a lot!

**Comment by erwinmombay** [comment]
@cramforce out of curiosity what where you going to use? :dash:
