### ISSUE TITLE
Geolocation component

### ISSUE THREAD

**Issue by dandv** [ampproject/amphtml#5499]
An AMP extended component offering access to the [HTML5 Geolocation API](https://www.w3.org/TR/geolocation-API/) would enable publishers to offer geographically targeted information to users and improve monetization:

* links to local stores selling items featured in the article
* local discounts
* nearby events tickets and discovery
* route/transit information

**Comment by jridgewell** [comment]
Thanks for the issue! We're already tracking this as https://github.com/ampproject/amphtml/issues/826.
