### ISSUE TITLE
[A11Y] amp-by-examples: image-lightbox: set `alt` AND `title` on the images

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#5500]
https://ampbyexample.com/components/amp-image-lightbox/ needs to add:

```
      alt="Picture of a dog"
      title="Picture of a dog, view in lightbox"
```

 to the image.

The `alt` is for the image and the `title` is for the fact that this a button that opens the image in the lightbox. Both are needed since when in the lightbox, `title` does not apply anymore.

**Comment by adelinamart** [comment]
Are there any updates here?

**Comment by aghassemi** [comment]
moved to ABE repo: https://github.com/ampproject/amp-by-example/issues/618
