### ISSUE TITLE
Create documentation for using analytics on amp-carousel

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#5506]
Create documentation for using analytics on amp-carousel

(Also work on whitelisting `data-slide-id`)

**Comment by camelburrito** [comment]
@powdercloud could you help with whitelisting `data-slide-id` data attributes for direct siblings of `amp-carousel`

**Comment by rudygalfi** [comment]
@camelburrito @powdercloud We should track the validator update as a separate issue, no?

cc @avimehta

**Comment by powdercloud** [comment]
Usually, data- attributes are allowed by default. Are you seeing some validation error? Or are you looking to make such an attribute required? (From looking at the code, that doesn't seem to be the case but I could be wrong)

**Comment by camelburrito** [comment]
@powdercloud i was not sure about data- attrs. if that is the case no validation changes are needed. just documentation needs to be updated.
