### ISSUE TITLE
Inline `AMP.extension` call.

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#5507]
The format of this call is:

```
AMP.extension(`amp-extension`, function() {
  AMP.registerElement();
  AMP.registerService();
});
```

This call is functionally equivalent to `AMP.push()` that we use in PROD binaries. The goal is to remove `AMP.extension` call and inline the callback (second argument).

/cc @cramforce

**Comment by cramforce** [comment]
Ship it.
