### ISSUE TITLE
[A11Y] Deprecate `alt` on `<amp-instagram>`

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#5509]
currently `<amp-instagram>` is the only iframe-based component that has `alt` attribute. Unfortunately since we can not pass that alt value through the embed API to instagram, it is pretty useless. It is used as the title for `iframe` which unfortunately does not do anything in new screen-readers (iframes are not exposed to AT anymore) and also used as `alt` for the placeholder image which can be covered by https://github.com/ampproject/amphtml/issues/5508

**Comment by aghassemi** [comment]
/to @erwinmombay as well, can be part of #5508

**Comment by lisaychuang** [comment]
Hi @aghassemi @erwinmombay, I'll take this for today's codelab!

**Comment by lisaychuang** [comment]
Fixed in [PR 18332](https://github.com/ampproject/amphtml/pull/18332)

**Comment by caroqliu** [comment]
Closing as this is described as fixed above.
