### ISSUE TITLE
[A11Y] sticky-ad: aria-label for close button should say "Close this ad" not just "Close"

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#5518]
When user is just navigating between the button on the page, `Close` is meaningless without a context.

**Comment by aghassemi** [comment]
@lannka Since you like Ads, you get an extra one to fix :)

**Comment by lannka** [comment]
@aghassemi when you said everyone get one bug, I was about to say: "you can assign the bug you have demoed to me".

**Comment by aghassemi** [comment]
lol, I gave that to Malte since he didn't see the fix :)

**Comment by lannka** [comment]
Big challenge for him :).
