### ISSUE TITLE
Consider supporting moving `forward` in history

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#5521]
Embedded AMP docs rely on messages to communicate with the viewers and communicate changes in history both ways. Currently `forward` is not supported and is broken in embedded docs.

The rational was that `forward` is not easily invoked on mobile. This is partially true and subject to UX changes of the browsers. Almost all browsers on iOS for example has a back AND forward buttons exposed for the user to use (the exception being Chrome with no visible forward button).

**Comment by jridgewell** [comment]
Forward is a left swipe (from the edge), backwards is a right swipe. That's in all the iOS browsers.

**Comment by mkhatib** [comment]
Nice, also my comment about Chrome iOS being an exception for a forward button was wrong, it actually does have a Forward button that appears when there's history to go forward in.

So forward is actually a prominent action in mobile browsers. 

On Android Chrome the Forward button is hidden under the overflow menu but prominent in that menu to the top.
