### ISSUE TITLE
DFP ads incorrectly being resized to values of height/width overrides (again)

### ISSUE THREAD

**Issue by adentify** [ampproject/amphtml#5547]
Previously reported: https://github.com/ampproject/amphtml/issues/5156
This issue was fixed and closed. we are seeing this behaviour again

You can see this happening here:
http://www.telegraph.co.uk/news/2016/10/11/revealed-hard-brexit-will-cost-britain-66billion-per-year/amp/

![image](https://cloud.githubusercontent.com/assets/1849728/19311964/59ad36bc-9088-11e6-98e0-20f3f3407a3f.png)

This seems to be affecting all browser/OS instances that we have checked.

**Comment by glevitzky** [comment]
I'm not seeing a collapse to override values. Instead, if the ad is in the viewport, I see an empty rectangle with the primary dimensions, and if the ad is not in the viewport, then the runtime collapses it completely for me.

**Comment by jridgewell** [comment]
/to @lannka, @glevitzky (Who I can't assign since he's not in the Github org...)

**Comment by jasti** [comment]
As acknowledged in #5156, this is not an issue anymore. Closing.
