### ISSUE TITLE
Carousel is not preloading next slide

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#5549]
Example https://www.google.com/amp/s/www.washingtonpost.com/amphtml/business/clinton-proposes-closing-real-estate-loophole-not-trump/2016/10/12/5698d66a-9052-11e6-bc00-1a9756d4111b_story.html

When advancing in the carousel in Chrome, loading the next slide does not happen until after the animation is complete.

It should 

- most likely preload +1 (and -1 in case of non-default start or loop) whenever the current slide is done or just do it right away
- at the very least start loading when initiating an advance

**Comment by ericlindley-g** [comment]
Would be great to get a fix in— @camelburrito, is this low-effort enough to do in the short term without disrupting Kickstart work? (optimistically slotting in "Next")

**Comment by cramforce** [comment]
I think this is pretty high priority. The current behavior is pretty broken to me.

**Comment by camelburrito** [comment]
Looked into this. Preload is being called for all adjacent slides -- 

https://github.com/ampproject/amphtml/blob/master/extensions/amp-carousel/0.1/slidescroll.js#L463


Looks like this is preventing it 
https://github.com/ampproject/amphtml/blame/master/src/service/resources-impl.js#L1404


Should we render it outside the viewport or try and fix the schedulePreload?

**Comment by cramforce** [comment]
We should render outside the viewport.

**Comment by cramforce** [comment]
CC @dvoytenko

**Comment by dvoytenko** [comment]
We absolutely need to fix this. It might have regressed since we restricted horizontal overflow. Layers would ultimately resolve this by allowing preload as we do now for body. In the meantime, we need to enable it by hardcoding. E.g. we can extend intersection check left/right 50% of the viewport width.

**Comment by camelburrito** [comment]
@cramforce - 

> schedule by horizontal distance.

Seems to be a good idea - for loops - would we say `distance == min(left dist, right dist)` ?

**Comment by dvoytenko** [comment]
I'd not do loops yet. With the owner system, carousel already indicates very clearly what it wants to preload with the full knowledge of the structure of its DOM. We just need to make sure that (a) We call schedulePreload when runtime actually can preload; (b) runtime does not improperly vetoes preload.

**Comment by cramforce** [comment]
@camelburrito had an example that was working as expected, so this doesn't appear to be a fundamental issue.

The next slide (at least eventually) does have dimension, so it should definitely pass the `isDisplayed` check.

**Comment by cramforce** [comment]
This actual cause is that these resources fail this check https://github.com/ampproject/amphtml/blob/master/src/service/resource.js#L466

Possibly some carousels somehow make this by 1px. We definitely need to make this more liberal
CC @jridgewell

**Comment by cramforce** [comment]
Ah, this probably always happens if the carousel is as wide as the screen.

**Comment by jridgewell** [comment]
Looking into this now, I think I have a fix.
