### ISSUE TITLE
"Untrusted viewer url override" error emitted for every web view page load

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#5563]
This affects the iOS Google app.

We hit this line every time
https://github.com/ampproject/amphtml/blob/f28e1169aaf7732d26a17cab469cd377a0374265/src/service/viewer-impl.js#L373

Is that a problem? Should the severity go down?

I also noticed that there are no callers of the `getViewerUrl` method.

CC @erwinmombay @dvoytenko

**Comment by jridgewell** [comment]
At least some of these are because of `https://www.google.cat`, which won't pass our [`TRUSTED_ORIGIN_HOSTS` regex](https://github.com/ampproject/amphtml/blob/f28e1169aaf7732d26a17cab469cd377a0374265/src/service/viewer-impl.js#L87).

**Comment by dvoytenko** [comment]
@cramforce The issue is not with the logging level, but the fact that we actually deny setting `viewerUrl` in webview mode. That's likely cause some issues downstream. So, for now, the error in logs is good.

@jridgewell Do we know why it's a `www.google.cat`?

**Comment by jridgewell** [comment]
Does `viewerUrl` actually matter? I don't see it actually used anywhere.

Not setting `referrerUrl` might mess up some analytics, but doesn't seem like it'll break anything.

> Do we know why it's a www.google.cat?

I don't know if iGSA is using `google.cat` (I actually don't know what they use, I'd love to find out). I was just seeing related errors because our `TRUSTED_ORIGIN_HOSTS` regex is a bit too strict, and it may also be causing the iGSA error.

**Comment by dvoytenko** [comment]
To my knowledge, `viewerUrl` is currently mostly used for error identification on our end. E.g. to explain "this error happens in this environment". E.g. this is how we've been notifying clients that do not enable local storage.

`referrerUrl` is pretty serious - it affects analytics, but also access features such as FCF and metering.

I'll follow up with iGSA.

**Comment by jridgewell** [comment]
Issue is https://github.com/ampproject/amphtml/blob/f28e1169aaf7732d26a17cab469cd377a0374265/src/service/viewer-impl.js#L300. `ancestorOrigins` is present, and it's length is zero.

For webviews, we shouldn't check it. Maybe trust the origin set instead?

I have an iGSA dev investigating if this is new to iOS 10. Maybe 9 didn't have `ancestorOrigins` yet.

**Comment by dvoytenko** [comment]
Yes. We have to trust webview's origin set.  In a webview all bets are off, so we might as well trust what they tell us.
