### ISSUE TITLE
Use extra padding-top on body when creating space on top for header

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#5564]
Currently, to create a space on top for the viewer header, we use the following implementation:
- Android
  - CSS: nothing special
  - Initial setup: add `padding-top: Xpx` on **html document**
  - Hide header: do nothing
  - Show header: do nothing
- IOS
  - CSS: position absolute body
  - Initial setup: add `border-top: Xpx` on **body**
  - Hide header: set `border-top: ''` on **body** and add `padding-top: Xpx` on **body**
  - Show header: set `padding-top: ''` on **body** and add `border-top: Xpx` on **body**

The problem is, in ios case, there is a small delay and content jittering when hiding or showing the header. This is probably due to changing the css layout during scrolling. It would be great if we could find a way to avoid css layout change or make it happen very fast without being noticed.

I'm thinking about adding extra `padding-top` on **body** in IOS case
- IOS
  - CSS: position absolute body
  - Initial setup: add `padding-top: calc(Xpx + Ypx)` on **body** where `X` is the height of the top space for header and `Y` is the user-defined `padding-top` on `body`
  - Hide header: do nothing
  - Show header: do nothing

The reason for the proposed implementation is that in ios case, adding `padding-top`/`border-top`/`margin-top` on **html document** won't have any effect given the fact that we have position absolute body element inside the html document. Adding `border-top` or `margin-top` on **body** element will create a solid white bar that will take up the space for the content when hiding the viewer header but temporarily removing the `border-top` or `margin-top` will cause the jittering. However, if we add extra `padding-top` to the **body** element during setup, we can achieve three things at the same time:

1. Creating a top space for the viewer header (shifting the content downwards).
2. Not changing the css layout during hide/show header operations thus there will be no jittering.
3. Showing full content when the viewer header is hidden.

I'm currently testing out this solution. Please let me know whether you guys think this idea is reasonable or not.

**Comment by dvoytenko** [comment]
The issue with padding in top is that an element with style `{position: absolute; top: 0}` will be behind the header because reference box for `position:absolute` includes the padding box. And unlike a fixed element, it will be very hard to offset `top` of a `position:absolute` element.

I'd say let's start with margin - it's possible that margin would work faster than border. If not - we can also try to manipulate `top` of the `body` element since it's positioned absolute. The body itself is `overflow:auto`, so it's possible the engine will be smart enough to avoid full relayout in this case.

**Comment by muxin** [comment]
OK, I can try it out. But I still doubt that manipulating css properties on hide/show header operation will still make the content jitter a little bit.

**Comment by muxin** [comment]
I tried setting `top` instead of `border-top` on body but it's still behaving the same: when hide/show the header, the content jumps up and down a little bit.

**Comment by muxin** [comment]
OK, this proposal is not working. @dvoytenko is coming up with another possible solution that wraps the `body` inside a wrapper element and add `padding-top` to the wrapper element.
