### ISSUE TITLE
DocumentClick is broken for links with different querystrings

### ISSUE THREAD

**Issue by riking** [ampproject/amphtml#557]
Trivial example:

    // location = http://localhost/foo/view?page=2
    <a rel=next href="http://localhost/foo/view?page=3">→ Next</a>

Results in the following browser error:

    Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document': 'a[name=]' is not a valid selector.

**Comment by erwinmombay** [comment]
@riking thanks for reporting!

**Comment by erwinmombay** [comment]
this should be fixed, pending a release. thanks again for reporting :+1:

**Comment by dvoytenko** [comment]
Erwin, https://github.com/ampproject/amphtml/pull/558 is not sufficient to fix this. We need to do this:
```
let tgtHref = `${tgtLoc.origin}${tgtLoc.pathname}?${trLoc.query}`;
```

**Comment by erwinmombay** [comment]
thanks for catching!

**Comment by erwinmombay** [comment]
fixed on #568 keeping this open until we do a new release

**Comment by cramforce** [comment]
Let's close bugs when the commit is in. We can use milestones to track
releases or something like that.

**Comment by erwinmombay** [comment]
@cramforce done.

**Comment by erwinmombay** [comment]
@cramforce on that note, we should we start doing CHANGELOG? (which is kind of tricky without versioning)
