### ISSUE TITLE
Error log: seem to relate to slide carousel 

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#5571]
As tested on a firefox device. the carousel behavior is not desired. 

Request 
https://cdn.ampproject.org/v/mobile.reuters.com/article/amp/idUSKCN12C294?amp_js_v=5  

stack
 Ch@https://cdn.ampproject.org/rtv/021475798648076/v0.js:282:24
https://cdn.ampproject.org/rtv/021475798648076/v0.js:281:474
forEach@[native code]
uh@https://cdn.ampproject.org/rtv/021475798648076/v0.js:281:437
vh@https://cdn.ampproject.org/rtv/021475798648076/v0.js:281:367
updateInViewport@https://cdn.ampproject.org/rtv/021475798648076/v0.js:268:182
updateInViewport@https://cdn.ampproject.org/rtv/021475798648076/v0.js:101:171
W@https://cdn.ampproject.org/rtv/021475798648076/v0/amp-carousel-0.1.js:43:238
https://cdn.ampproject.org/rtv/021475798648076/v0/amp-carousel-0.1.js:42:97
Je@https://cdn.ampproject.org/rtv/021475798648076/v0.js:234:219
[native code]

![image](https://cloud.githubusercontent.com/assets/5419904/19332484/448c26e4-90a1-11e6-927b-192e5b889572.png)

**Comment by camelburrito** [comment]
does not seem to happen any more?
