### ISSUE TITLE
Clean up ads.extern.js file

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#5582]
I found that the file is getting super long. Also we are not documenting it anywhere so 3p ad developer don't know if they should update the file. 
I think the file is added to enable type check @cramforce Can you explain why we need the file?
And as @lannka suggest, we can at least get rid of all the `data.xxx` from this file and instead enforce  using `data['xxx']`. 
If we still need this file, we should also document it in ad readme.

**Comment by lannka** [comment]
It was to avoid those strings get minified/obfuscated. But as I remember from @erwinmombay, this is not necessary for most cases now as we don't obfuscate public variables?

**Comment by cramforce** [comment]
The compiler doesn't like unknown properties. This makes them known.

The alternative is for them to use `foo['name']` notation.

**Comment by zhouyx** [comment]
I would suggest using `foo['name']` notation to prevent this file from getting super long. Then we can also update our doc asking 3p ad contributor to stay with this notation.

**Comment by zhouyx** [comment]
Asked @erwinmombay about this. Now I don't have a preference. Since putting everything in `ads.extern.js` can help us to do type checking things easier.  If we decide to keep everything here I would suggest we organized it a little bit (group them by ad network?) and update our doc

**Comment by lannka** [comment]
Yep, we should just be consistent with `data['name']` pattern. Yuxuan, do you want to fix them in one shot? That will make our future PR review easier :-).

**Comment by zhouyx** [comment]
I can definitely do that. The question is that do we really want to do this way. I am kind persuaded by @erwinmombay that the other approach is better...

**Comment by cramforce** [comment]
I like the extern file, because it at least provides for some form of spell checking and networks could choose to add real types there.

**Comment by zhouyx** [comment]
OK! Let's keep extern file. But is there anyway to keep this file clean and more organized? 3p ad contributors get merge conflict on that file because everyone add new lines at the bottom of it. Also I found that we never check if there're duplicate variables. For example there are two `data.slot` in that file.

**Comment by cramforce** [comment]
It would be great if we (manually) alpha sorted it

**Comment by jasti** [comment]
Been a while. @zhouyx is this something you can look into?
