### ISSUE TITLE
Saucelab integration test flaky 

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#5587]
![image](https://cloud.githubusercontent.com/assets/5419904/19367009/3ea9b806-914e-11e6-96cc-ebce3f9beb5d.png)

**Comment by zhouyx** [comment]
Seen it multiple times today! 
https://travis-ci.org/ampproject/amphtml/builds/167749813

**Comment by aghassemi** [comment]
fixed by https://github.com/ampproject/amphtml/pull/5943 and related PRs
