### ISSUE TITLE
Chunked AMP startup

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#5599]
We will split AMP's startup phase (the code that runs when a page renders) into distinct chunks.

This will enable us to yield the UI thread. When rendering in background (into an invisible document), we can use this to reduce impact on the stuff that is actually visible.

Initial PR: #5536

Further optimizations:
- [ ] Wait for `requestIdleCallback` to produce a "long" available timeslot. The initial PR takes any idle callback
- [ ] Experiment with getting first paint to be faster by making the body visible and then yielding before installing any extensions.
- [ ] Add additional chunks

**Comment by ericlindley-g** [comment]
Might be best owned by @cramforce, unless there are product tradeoffs that it would be useful for me to help research and evaluate.

/to @cramforce for now, but feel free to assign back

**Comment by choumx** [comment]
This has been launched for awhile.

**Comment by JakobEichler** [comment]
Is there an example, explaining how to use this experiment?

**Comment by choumx** [comment]
It's a performance enhancement that's enabled by default, no need to opt-in.
