### ISSUE TITLE
Optimize: Defer amp-image-lightbox build

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#5601]
I think the `buildCallback` in `amp-image-lightbox` can be deferred until it is actually opened.

**Comment by tompere** [comment]
@adelinamart - I think this issue has been resolved already, [see here](https://github.com/ampproject/amphtml/commit/2f7199c0442f7ea2c7992fcd233a396623027cae).

**Comment by jridgewell** [comment]
Unfortunately, `<amp-lightbox>` and `<amp-image-lightbox>` are separate components. So, sill open.

**Comment by cramforce** [comment]
@tompere Any chance you are interested in providing a fix? It would be super similar to https://github.com/ampproject/amphtml/commit/2f7199c0442f7ea2c7992fcd233a396623027cae

**Comment by tompere** [comment]
how embarrassing... 😳 
@cramforce - I would be happy to do it.

**Comment by tompere** [comment]
@cramforce - can you please assign to me?

**Comment by cramforce** [comment]
@tompere Sent you invite for Org. Can assign when you accept.

**Comment by tompere** [comment]
@cramforce - accepted

**Comment by cramforce** [comment]
Woohoo! Thanks @tompere!
