### ISSUE TITLE
amp-form: omit target attribute for POST requests

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#5607]
POST requests are only allowed via XHR ([link](https://github.com/ampproject/amphtml/blob/553247b6a408a06e144e05eeb7dcfa96bfce0335/src/document-submit.js#L72). However, the validator still requires `action` and `target` to be set. 

=> If this is the intended (no JS fallback) behavior, we should make this explicit in the documentation (and samples). 
=> If this is not the intended behavior, we should update the validation rules.

//cc @mkhatib @Gregable 

Context: PR #5548

**Comment by dandv** [comment]
Ran into the same error - https://github.com/ampproject/amp-by-example/issues/426

It doesn't quite make sense to specify a `target` for XHR requests that update the same page.

**Comment by mkhatib** [comment]
Agreed. @Gregable I am not sure if we discussed this before, but would conditional requirement of an attribute be possible in the validator? So only require `target` for `method=GET`?

This also needs to be updated in runtime.

**Comment by mkhatib** [comment]
@cramforce does this make sense? I remember we wanted to enforce having target all the time at first, but since our implementation changed - do you mind if we just drop the requirement for target for xhr requests?

**Comment by cramforce** [comment]
@mkhatib no target seems fine, even better.

**Comment by mkhatib** [comment]
Ok so thinking of making `target` only required for non-XHR `GET` requests. So only if `action-xhr == undefined` and `method=GET`

**Comment by cramforce** [comment]
No target, just means target is _top. No need to make it explicit I think.

**Comment by drdamour** [comment]
i was confused by the docs on form because the example has method=POST but also has an action attribute which is defined as invalid, is the sample wrong?

**Comment by mkhatib** [comment]
Yes apologies for that, I think we had a PR to update the examples in the docs but was not followed up on, will go ahead and update the docs in another PR.

**Comment by mkhatib** [comment]
@Gregable this is in runtime now too - won't be in production until 2 weeks - so we can probably get started on this on the validator.

**Comment by Gregable** [comment]
Right now, if a form action is `GET`, then validation requires:

- target attribute with value of _blank or _top
- action attribute

Right now, if a form action is `POST`, then validation requires:

- target attribute with value of _blank or _top
- action-xhr attribute

I'm confused as to what, if anything, this still requires. It looks like the thread is requesting that for `GET` forms, `action` is always required but only one of `target` or `action-xhr` is required. Is that the correct intepretation?

@sebastianbenz , @cramforce

**Comment by Stefany93** [comment]
@Gregable I think `tagret` is no longer mandatory?

**Comment by Gregable** [comment]
@Stefany93, good catch. Closing this issue.
