### ISSUE TITLE
requestResize gives wrong dimensions

### ISSUE THREAD

**Issue by adtechnology** [ampproject/amphtml#5608]
RenderStart sets width of 300000 and height of 250000 by using values 300,250 on emulated desktop chrome

When I open an AMP page in actual desktop Chrome using emulation to iPhone and open e.g. [this](https://www.google.de/amp/www.bild.de/news/aktuelles/news-aktuell/zahl-der-hurrikantoten-in-haiti-steigt-auf-48282604,view=amp.bild.html) page, there is an adslot (first one) of 300x250.

In return of an ad global.context.renderStart is invoked using the dimensions 300x250 as you can see in the attached screenshot.

![image](https://cloud.githubusercontent.com/assets/8875101/19379408/1a20e9ce-91f2-11e6-8bb5-d179777599b1.png)

But in result the container gets the styles width: 300000px and height: 250000px;

![image](https://cloud.githubusercontent.com/assets/8875101/19379487/7cbeea7c-91f2-11e6-90f8-3e3c475ace2b.png)

**Comment by jridgewell** [comment]
This is working perfectly for me. @lannka?

**Comment by adtechnology** [comment]
The problem now also appears on iPhones, you can investigate this on [this domain](https://www-test.wieistmeineip.de/anbieter/telekom/amp/)

**Comment by evdoks** [comment]
I am experiencing similar issue. Often the ad is displayed as a huge grey rectangle making the page unreadable.
<img width="723" alt="screen shot 2016-10-21 at 16 12 39" src="https://cloud.githubusercontent.com/assets/1532773/19604242/b6e24240-97b4-11e6-8722-00554c80e009.png">

**Comment by cramforce** [comment]
CC @lannka @zhouyx

**Comment by zhouyx** [comment]
@adtechnology @evdoks I still can't reproduce this. @adtechnology I tried the page you gave me, it  looks good to me. @evdoks Can you also share the page you are testing with?
Does this happen all the time?

**Comment by cramforce** [comment]
I also tried reproing on iOS and Chrome and everything seemed to work fine.

**Comment by jridgewell** [comment]
They've turned off the ad campaign. @adtechnology said he'd get a test environment for me on Monday.

**Comment by cramforce** [comment]
I discovered what is going on. This happens when the ad requests to resize itself to a string :)

We then run code like this `250 + "250" - 250` which in JavaScript equals ` 25000`.

Advertisers can easily fix this on their side by sending numbers instead of strings, but we should probably run a `parseInt(…, 10)` on the incoming dimension to avoid this type of problem.
