### ISSUE TITLE
AMP enhancement when not running on mobile devices/AMP mode

### ISSUE THREAD

**Issue by mirceapiturca** [ampproject/amphtml#561]
Instead of having the AMP pages linked from my normal HTML page I wish to modify the AMPs when not viewed on mobile. CSS, JS and HTML features that are now allowed by AMP could be added if the AMP page is not viewed on mobile.

Is there a way to tell when the page is not running in AMP mode, accessed from a desktop? Any API for this?

**Comment by dvoytenko** [comment]
"Mobile" here is just a trending word. An AMP is a fully responsive web document - it can and should support whatever space and features different devices bring. Depending on a particular use case, of course, the host may choose to redirect to a more full-featured document.
