### ISSUE TITLE
gradientTransform attribute misspelled in validation

### ISSUE THREAD

**Issue by tcorley** [ampproject/amphtml#5615]
I'm looking to support SVGs in my AMP page and I'm seeing that I get a validation error:
`The attribute 'gradienttransform' may not appear in tag 'lineargradient'`

I'm no svg wizard, but I'm sure that's the correct attribute name (via https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/gradientTransform)

It looks like the attribute is misspelled in the validator as `gradientransform` https://github.com/ampproject/amphtml/blob/3eb745852fbe1e58e7ce9868b35892044a13379e/validator/validator-main.protoascii#L1865

**Comment by honeybadgerdontcare** [comment]
This is live.
