### ISSUE TITLE
Expand the documentation for "on" attributes / event handlers

### ISSUE THREAD

**Issue by dandv** [ampproject/amphtml#5617]
Arrived at https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#on from https://github.com/ampproject/amphtml/blob/master/extensions/amp-form/amp-form.md#events and was unable to figure out how to use events on the form submission.

Some questions:

1. What is the targetId? The id of a DOM element?
2. How are methods defined on the target?

Linking to [amp-lightbox](https://github.com/ampproject/amphtml/blob/master/extensions/amp-lightbox/amp-lightbox.md) would be a small step forward, though I don't see a `showLightbox` method there.

**Comment by mkhatib** [comment]
Thanks for filing @dandv will expand the docs but just to answer your questions. Yes target ID is be DOM ID of an element 

Each target define and expose its own methods. For example, amp-lightbox exposes activate and close methods that you can trigger. 

Each element should document the methods it exposes if you find any missing docs for undocumented methods please send a PR or just file an issue for us to update docs.

**Comment by dandv** [comment]
Thanks, will do. I was trying to get an `<amp-form>` to change the styling of a given `<div>` and the best I've come up with was to use the CSS hooks to [hide the submit button and show a the `submit-success` div](https://github.com/dandv/amp-by-example/blob/favorite/src/30_Advanced/favorite.html#L49-L93).

**Comment by mkhatib** [comment]
Yeah I think that's one way to do it.

You could also use the global method that should work on any element - `hide`. I have not tried this before so if you try it let me know if it works or not 😄 

```html
<form on="submit-success:favorite-btn.hide">
   <input type="submit" id="favorite-btn" value="❤️">
</form>
```

Not sure if we document the `.hide` method anywhere. Will get on documenting these now.

**Comment by dandv** [comment]
@mkhatib That did work, thanks!
