### ISSUE TITLE
amp-iframe support of allow-same-origin

### ISSUE THREAD

**Issue by justforfun** [ampproject/amphtml#562]
It seems that the support of allow-same-origin atttribute is not working
sandbox="allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox"

This is the error displayed
Origin of <amp-iframe> must not be equal to container  
when on this page 
https://justforfun.github.io/examples-amp/article.amp.html
this code is used
```<amp-iframe width="300" height="300" sandbox="allow-same-origin allow-popups" layout="responsive" frameborder="0" src="https://justforfun.github.io/examples-amp/video-iframe.html" class="-amp-element -amp-layout-responsive -amp-layout-size-defined -amp-error -amp-layout" id="AMP_7"><i-amp-sizer style="display: block; padding-top: 100%;"></i-amp-sizer>
      </amp-iframe>```

**Comment by cramforce** [comment]
Right, allow-same-origin is only allowed if the iframe is not on the same origin as the container.

This still allows the iframe to talk to sibling iframes on the same origin.

**Comment by cramforce** [comment]
Note, that this is not a security invariant. Because AMP files are meant to be distributed via cache domains one cannot expect that the origin would be the same eventually, so this prevents stuff to be working only sometimes.
