### ISSUE TITLE
False negatives with ampExtendedElements

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#5625]
This comes from discussion in #5453.

After #5454, we no longer assert that `ampExtendedElements` is already defined when checking if an element is scheduled.

Regardless of who creates the `ampExtendedElements`, we still have a race condition. When there's no scheduled element, we wait until the body is available (head has been parsed) then check again. However, there's no guarantee that an element has loaded and made AMP aware that it is loading.

A better solution may be to wait until the document is complete before the second check. At this point, we're guaranteed that the element has gotten into the loading phase.

**Comment by dvoytenko** [comment]
I made a comment on https://github.com/ampproject/amphtml/issues/5453. The right solution is to initialize `win.ampExtendedElements` immediately in the runtime. However, even if that's fixed, it's still not correct. The right approach would be remove `ampExtendedElements` completely and instead implement this check via `Extensions` service - it should be the only and final authority on which extensions are available and when.

**Comment by jridgewell** [comment]
That's no different than just checking if `win.ampExtendedElements` is present.

- If `win.ampExtendedElements` isn't present:
  - The element's script may not have downloaded yet
  - the element's script may not be present on the page at all
- If `win.ampExtendedElements` is present:
  - The element's script may not have downloaded yet
  - the element's script may not be present on the page at all

By initializing `win.ampExtendedElements` in the runtime immediately, we have:

- If `win.ampExtendedElements` is present:
  - The element's script may not have downloaded yet
  - the element's script may not be present on the page at all

**Comment by dvoytenko** [comment]
Correct. That's why we should just remove this property and move implementation into `Extensions` service.

**Comment by jridgewell** [comment]
> move implementation into Extensions service.

Could you explain? Do you mean doing DOM queries for the scripts from `Extensions`?

**Comment by dvoytenko** [comment]
Yes. `Extensions` contains the internal structures of loading state for all extensions. Thus, this should be a natural fit. Although it's fully async state as far as API concerned, as opposed to the sync `ampExtendedElements` semi-public variable.

**Comment by dvoytenko** [comment]
And whatever problems we may have with risk conditions, should be easily solvable behind `Extensions` service's API
