### ISSUE TITLE
google fill slot type of ad

### ISSUE THREAD

**Issue by qike74** [ampproject/amphtml#5634]
Hello, 
I'm trying to covert the following google ad type into AMP but either trying the adsense and the doubleclick versions I'm not able to get it work.
Any ideas how this should be converted into AMP?

Thanks

Standard script: 
`<script type='text/javascript'>
GA_googleFillSlot("viajablog-300-250");
</script>  
<script type='text/javascript'>
GA_googleFillSlot("viajablog-300-250");
</script>`

Adsense version into AMP:
`<amp-ad width=300 height=250
      type="adsense"
      data-ad-client="ca-pub-5077331059380037"
      data-ad-slot="viajablog-300-250">
 </amp-ad>`

Doubleclick version into AMP:
`<amp-ad width=300 height=250
    type="doubleclick" 
    data-slot="viajablog-300-250">
</amp-ad>`

**Comment by jasti** [comment]
AFAIK, Google Ad Manager isn't supported. If you have directly created adunits in Adsense or Doubleclick, they will work in AMP. Please do reach out directly to you existing support channels at Adsense and Doubleclick for more help.

**Comment by qike74** [comment]
Thanks Jasti. I will get in contact with them. Maybe I should use an updated code for this even in standard web
