### ISSUE TITLE
Allow referrerpolicy on AMP script tags.

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#5637]
We should allow the `referrerpolicy` attribute on the AMP JS. This way, pages can make sure that user traffic (if it doesn't hit the cache anyway) can be correlated to their page.

This might be allowed already, so just making sure :)

**Comment by Gregable** [comment]
This one slipped through the cracks.

Do you mean on a script tag, such as:
`<script async src="https://cdn.ampproject.org/v0.js" referrerpolicy=no-referrer></script>`

The W3C document (https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-delivery) doesn't suggest this is allowed:
```Via a referrerpolicy content attribute on an a, area, img, iframe, or link element.```

If you mean meta and/or link rel tags, these are already allowed.
