### ISSUE TITLE
Discussion: <html ⚡>

### ISSUE THREAD

**Issue by donohoe** [ampproject/amphtml#564]
While I think the lightning-bolt is awesome on a number of levels, it also appears to be impractical. 

It can't be typed for a normal keyboard with ease, and it isn't honored in most search engines if I'm looking for information on AMP. For example, I couldn't search easily to see if anyone else flagged this.

I would strongly suggest dropping this convention - or better understand the rational.

-Michael

**Comment by cramforce** [comment]
Closing in favor of #472
