### ISSUE TITLE
Report step timings in pr-check.js

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#5647]
It is very useful to be able to see how long each step takes, so we can optimize that over time.

**Comment by adelinamart** [comment]
not sure where this FR will fit.

**Comment by erwinmombay** [comment]
will take over this. should be a quick fix.

**Comment by adelinamart** [comment]
Awesome!

**Comment by rsimha-amp** [comment]
Working on it during this week's sprint.
