### ISSUE TITLE
Ability to put variables into hidden form fields

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#5654]
For XHR requests on a page with amp-form, have the ability to pass custom vars (using variable substitutions) via hidden input.

**Comment by drdamour** [comment]
where would the values come from?

**Comment by mkhatib** [comment]
@drdamour that's what this issue is referring to.

**Comment by jasti** [comment]
@mkhatib I see a PR out of this. Any ETA for it?

**Comment by rudygalfi** [comment]
Can you clarify if this proposal will support `GET` (i.e. replacements end up in the URL)?

**Comment by mkhatib** [comment]
The chat I had with @cramforce was basically we can support async-substitution for all xhr requests. and for GET non-XHR we can support only sync-substitution (this however, might include a pre-resolved cached CLIENT_ID if it has been resolved before)

**Comment by mkhatib** [comment]
And yes, for GET they'll end up in the URL.

**Comment by mkhatib** [comment]
@jasti for an ETA, I think I might get this in with an experiment guard in 2 weeks, that PR is not fully ready and we might need to refactor url-replacement to split out the var-sub part separately.

**Comment by jasti** [comment]
@mkhatib Thanks! I've given an advertiser this issue to follow. 2 weeks with a guard sounds good.

**Comment by mkhatib** [comment]
Merged under `amp-form-var-sub` experiment flag.
