### ISSUE TITLE
404 error on images when AMP pages are delivered by Amp project CDN

### ISSUE THREAD

**Issue by justforfun** [ampproject/amphtml#5659]
## How do we reproduce the issue?
When our AMP pages are delivered via AMP CDN images are not displayed due a 404 error.
You can find an example here:
https://cdn.ampproject.org/c/www.repubblica.it/esteri/2016/10/18/news/renzi_e_obama_alla_casa_bianca-150018863/amp#development=1
Where the main image of the article and all the images of the gallery fail to load:

error.js:75task failed: amp-img#4#L amp-img#4: Failed to load: https://cdn.ampproject.org/i/s/www.gelestatic.it/thimg/x9_rkt0Z1fTqmRiaxuOa…azionale/img/2016/10/18/155644903-775abbda-25f2-4c5a-880a-edfdbd8c6080.jpg​​​Dd @ error.js:75
log.js:384Uncaught Error: task failed: amp-img#4#L amp-img#4: Failed to load: https://cdn.ampproject.org/i/s/www.gelestatic.it/thimg/x9_rkt0Z1fTqmRiaxuOa…azionale/img/2016/10/18/155644903-775abbda-25f2-4c5a-880a-edfdbd8c6080.jpg​​​

Everything is working properly while AMP page is served by our site:
http://www.repubblica.it/esteri/2016/10/18/news/renzi_e_obama_alla_casa_bianca-150018863/amp

Every browser is affected by the problem

**Comment by cramforce** [comment]
Tracked at Google as b/32241988

**Comment by cramforce** [comment]
@justforfun This happens because you use a protocol relative URL for the image (Starting with `//`), but you fail to serve them on `https`. The easiest fix would be to prefix the URLs with an explicit `http:`
