### ISSUE TITLE
Non-resizable viewport a requirement?

### ISSUE THREAD

**Issue by patrickhlauke** [ampproject/amphtml#566]
In https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md it lists 

```
<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no,minimal-ui">
```

as a requirement. Any particular reason why, other than breaking accessibility right out of the box for users who do require zooming?

**Comment by erwinmombay** [comment]
howdy! do you mind taking the conversation to https://github.com/ampproject/amphtml/issues/481 ? feel free to open if you feel strongly in branching the discussion here :)

**Comment by dvoytenko** [comment]
This requirement has been removed as per #481.
