### ISSUE TITLE
Make form submission an amp-analytics trigger

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#5674]
Submitting a form and the success state of the submission should be amp-analytics triggers.

@rudygalfi probably has more requirements.

**Comment by rudygalfi** [comment]
cc @avimehta 

Will submit button clicks get tracked as amp-analytics `click` events? (I'm guessing no.)

Let's just start with something simple like a trigger for form submission and a variable that will tell whether it succeeded or failed.

How soon could we get to this?

**Comment by cramforce** [comment]
@mkhatib should be able to do this quickly. Similar to #5388 (But please refactor into a common utility to abstract away that async complicated).

Click tracking should work just fine really. And maybe that is what most people would use? I still think it makes sense to emit something like `form-submit-success` and `form-submit-failed` as more semantic events.
