### ISSUE TITLE
Implement automatic package sorting in gulp lint --fix

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#5681]
We enforce sorting packages in reviews which sometime can be a daunting task. Sorting is the kinda of thing that computers are good at 😄 we should automatically fix this for us.

**Comment by mkhatib** [comment]
Assigning this to @erwinmombay - feel free to re-assign

**Comment by erwinmombay** [comment]
lets close this, since import order matters an auto sort might cause some issues

**Comment by jridgewell** [comment]
> lets close this, since import order matters an auto sort might cause some issues

Do wah?
