### ISSUE TITLE
amp-twitter takes up large blank space before loading

### ISSUE THREAD

**Issue by ping** [ampproject/amphtml#5682]
The Twitter embed takes up a disproportional amount of space before it is loaded/rendered completely. This pushes content after the embed too far down and sometimes completely below the fold.

In the filmstrip below, you can see the content pushed almost beyond the bottom edge of the screen.
![image](https://cloud.githubusercontent.com/assets/104607/19506179/cf32357c-95fb-11e6-84d2-0b28eecf3bb8.png)

A non-amp Twitter embed does not have the same issue.

## How do we reproduce the issue?

Example url: https://rawgit.com/ping/b0cb5d64b6566c2d355d47c3c2c9f163/raw/eddb443e5e0aef9e827a6ef05b016653f5e75e1a/amp-twitter-embed.html
Google CDN Cache url: https://cdn.ampproject.org/c/s/rawgit.com/ping/b0cb5d64b6566c2d355d47c3c2c9f163/raw/eddb443e5e0aef9e827a6ef05b016653f5e75e1a/amp-twitter-embed.html

## What browsers are affected?
I've tested it on Chrome/Android5.

Also tested on webpagetest.org with videos demonstrating the problem.
Nexus7/Chrome screen recording: 
https://www.webpagetest.org/video/view.php?id=161019_48_77cfc3e93f4d49e1984a82f0b8086d07.1.1
iPhone6 screen recording: 
https://www.webpagetest.org/video/view.php?id=161019_23_ba6ef4c02ea0729585ed36b9485dfa25.1.1

## Which AMP version is affected?
Powered by AMP ⚡ HTML – Version 1475798648076

**Comment by cramforce** [comment]
This is because of the `width` and `height` you are providing together with `layout=responsive`. The values are used to reserve space prior to finding the real space.

Choosing more correct initial values (such as in http://output.jsbin.com/sudadet/quiet) prevents this from happening.

**Comment by ping** [comment]
@cramforce That indeed fixed the problem. I copied the values from the ampbyexample example code and didn't look carefully at those values. Thanks!
