### ISSUE TITLE
Amp-img attribute ”width” error on half of my post pages

### ISSUE THREAD

**Issue by davidfilat** [ampproject/amphtml#5684]
When I submitted my sitemap to Google Search Console and it started indexing my amp pages, more that half of them got this error: 

> The attribute 'width' in tag 'amp-img' is set to the invalid value ''.

Can it be fixed somehow? Thank you!  You are doing a great job!

**Comment by twins16** [comment]
the problme is with schema go to https://validator.ampproject.org/#url=https%3A%2F%2Fwww.cheri3a.com%2Fedu%2F4062-2%2Famp%2F


and go to data high lighter or code it 
https://search.google.com/structured-data/testing-tool?url=https%3A%2F%2Fwww.cheri3a.com%2Fedu%2Flessons-11-evel-3%2Famp%2F#url=https%3A%2F%2Fwww.cheri3a.com%2Fedu%2Flessons-11-evel-3%2Famp%2F



make shur your add some apm-img 
and test it 

hope you figure out

**Comment by jridgewell** [comment]
You need to set a specific width. See the [docs](https://www.ampproject.org/docs/guides/responsive_amp#layout-elements-responsively).
