### ISSUE TITLE
Offer a mechanism to collapse <amp-list>s with no items

### ISSUE THREAD

**Issue by dandv** [ampproject/amphtml#5686]
[`<amp-list>`](https://www.ampproject.org/docs/reference/components/amp-list) does not support `layout=container`, presumably so that dynamically rendered items don't cause reflow.

That has an unfortunate side effect: if the list is empty, the publisher has to provision vertical space anyway, which can't be hidden if the list turns out to be empty. I've played with all the possible layout combinations, and short of some hacky CSS I haven't yet been able to come up with, I'm not sure how to hide this vertical space when the CORS URL returns an array of zero items and there's nothing for the template to render.

Use case: a recipes site wants to display local offers for each ingredient of a recipe. If there are no local offers for an ingredient, the whitespace caused by defining a fixed height for the `<amp-list>` can't be removed:

![image](https://cloud.githubusercontent.com/assets/33569/19516644/b4ae44e2-95b1-11e6-9cf0-de698971b99c.png)

**Comment by erwinmombay** [comment]
@dvoytenko any easy fix for this?

**Comment by dvoytenko** [comment]
@dandv Why is vertical space has to be provisioned anyway? We normally stress that `amp-list`'s primary goal is NOT to provide a client-side rendering substitute. But rather to allow pages to bring in some auxiliary (possible 3p) content, such as related articles or products.

**Comment by dvoytenko** [comment]
For more context: collapsing empty space is as bad for UX as resizing non-empty space. Visible jumps in the viewport would be similarly disrupting.

**Comment by dandv** [comment]
@dvoytenko: in the use case illustrated by the screenshot, the partner wants to show auxiliary content (a list of 1+ local offers related to a recipe ingredient, determined by geolocating the user based on their IP address [for now](https://github.com/ampproject/amphtml/issues/5499)) - does this fit the purpose of amp-list, or is there a better mechanism?

With amp-list, sometimes there are no available local offers, and the published would like to not render anything, as opposed to vertical whitespace.

**Comment by dvoytenko** [comment]
@dandv I think the best option here is to start with minimal reserved space and grow the `amp-list` automatically when new data arrives, as it already does. If it fails to resize, it should be possible to have an `overflow` element inside the `amp-list` that will advise to "see related listings" or such.

Alternatively, we could look into some user-action behavior where a reader is asked to click to see "offers".

The bottom-line: I don't see why it'd be better to start with reserved space if it needs to be collapsed later.

**Comment by adelinamart** [comment]
Is there still a request here? Thanks

**Comment by ericlindley-g** [comment]
@dandv — were you able to solve this without an additional feature to collapse `amp-list` when it doesn't have any items?

**Comment by ericlindley-g** [comment]
Closing, but feel free to re-open if there's still a need here!
