### ISSUE TITLE
Experiment with relatively small scale screen shot diffing

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#569]
Lets experiment with loading AMP websites in the browser on Travis, taking a screenshot and then diffing the screenshot.

Maybe Travis isn't the right infra and we should use Google Compute Engine or Amazon.

Questions:
- Do we need local copies? Would make it faster. Also avoids generating traffic on the origin.
- We should at least send a specific user agent and or query string.
- Do we replace all ads / iframes with one standard URL for hermetic results?
- What happens if there is a failure? We need some way to approve diffs and submit them as golden files.
- Or instead we always run twice in tests: Once with last version, once with new version and diff. That would not require checking reference images into github.

We run the Chrome on Travis on xvfb
https://github.com/ampproject/amphtml/blob/master/.travis.yml#L11

Some resources on diffing
http://linuxboxadmin.com/micro-howtos/userland/screenshots-through-xvfb.html

I think @dvoytenko was already playing with image diffing tools in node.js

**Comment by erwinmombay** [comment]
@dvoytenko do you have the code somewhere? would love to see it

**Comment by dvoytenko** [comment]
In gerrit :) I'll look for it.

**Comment by dvoytenko** [comment]
Travis likewise supports Phantom. I will take a look what that really means.

**Comment by dvoytenko** [comment]
Here's the issue that tracks Phantom2 upgrade on Travis: https://github.com/travis-ci/travis-ci/issues/3225

**Comment by dvoytenko** [comment]
Another related issue on Travis: https://github.com/travis-ci/travis-ci/issues/2046

**Comment by dvoytenko** [comment]
Now we can run manual screenshot diffs using `gulp make-golden` and `gulp test-screenshots`.

Still working on Travis integration. It's currently blocked by https://github.com/ampproject/amphtml/pull/697 to switch to Ubuntu 14 and Phantom2.

The https://github.com/ampproject/amphtml/pull/685 demos how Travis integration can work but we still need to push results to the cloud (S3 or GCS). For that we'll likely have to use savage.

**Comment by rudygalfi** [comment]
Targeted to M2. Please unmark "Stale?" label if still needed; else close.

**Comment by cramforce** [comment]
We want to do this. @dvoytenko wanna add your super MVP to travis?

**Comment by dvoytenko** [comment]
I'd like to. However, the challenge is to be able to upload images somewhere in case of failure. Otherwise, this makes it impossible to debug. Any suggestions? Given Travis' limitations with secret keys this is difficult.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)

**Comment by erwinmombay** [comment]
reassigning to myself and will reassign when possible
