### ISSUE TITLE
Google AMP Cache 404 for PNG images

### ISSUE THREAD

**Issue by VictorVO** [ampproject/amphtml#5710]
## Google AMP cache is not able to cache some PNG images from our content.

Visit https://cdn.ampproject.org/c/www.tiendeo.com.co/amp/Tiendas/bogota/colsubsidio-cra-c/3438

Expected: see png logo image (below the red bar on the top)

Actual: This logo image is not being displayed, it is a png image of 15 kb

If we check it at https://cdn.ampproject.org/i/static300.tiendeo.com.co/upload_negocio/negocio_288/logo2.png
we get a 404 error.

We have another PNG images at the same AMP page, and they are showing correctly from google amp cache.

## What browsers are affected?

All browsers

## Which AMP version is affected?

1475798648076

**Comment by jridgewell** [comment]
I get the image? Did you change something on your end?
