### ISSUE TITLE
<amp-carousel>: <amp-image> with media attribute fails to load image

### ISSUE THREAD

**Issue by eike-hass** [ampproject/amphtml#5714]
We are building a `amp-carousel` with different aspect ratios on different breakpoints. We utilize the heights attribute on the `amp-carousel` and the media attribute on `amp-image` elements to load optimized images. 
When another breakpoint is triggered (e.g by switching from portrait to landscape) `amp-image` fails to load the image and stays blank. A carousel navigation fixes the issue. 
## How do we reproduce the issue?

We set up a jsbin to recreate the issue http://output.jsbin.com/wedewosavi
1. Jump over the 600px breakpoint
2. Find the slide empty
## What browsers are affected?

This seems to affect all tested browsers.
## Which AMP version is affected?

Version 1476486609642

**Comment by camelburrito** [comment]
@eike-hass - Thats cool :) Could you try using srcset attribute on the images instead - i think that would solve your issue .

**Comment by eike-hass** [comment]
@camelburrito We would like to have different aspect ratios for the images on certain breakpoints. Do you think that would be possible with srcset?

**Comment by camelburrito** [comment]
@eike-hass - i have not tried it myself - but i just read that you could use srcset with sizes and make this work with just one image 

http://ericportis.com/posts/2014/srcset-sizes/

Let me know how this goes.

**Comment by eike-hass** [comment]
@camelburrito as i see it the picture element would be the thing we are trying to go for. Is the current behavior intended?

**Comment by camelburrito** [comment]
@eike-hass - I think your usage is a super edge case (which i would still like to investigate). I was trying yo unblock you by suggesting alternatives. 

The problem might be more of a repaint not happening when a particular dimension is reached. (when one image is hidden and another is shown). Ill still try to investigate this.

**Comment by camelburrito** [comment]
@eike-hass -Your approach toggles display between two images which requires the runtime to pick up the change. i believe this is what you want 

```html
    <amp-img src="{{narrow-img}}" srcset="{{wide-img}} 1400w, {{narrow-img}} 640w" width="640" height="960" layout="responsive" class="" heights="(min-width:640px) 67%, 150%"></amp-img>
```

I have tried this and it works!
