### ISSUE TITLE
I2I: Rendering native/simple ads outside amp-ad iframe

### ISSUE THREAD

**Issue by src-code** [ampproject/amphtml#5721]
Carried over from discussion in PR #5122.

I'd like to implement a small but useful change to `amp-ad` which would allow native advertising rendered without a call to an ad network to still be managed by `amp-ad` with minimal effort.
## Problem

Currently `amp-ad` generally assumes that ad content will be rendered from an ad network call, which implies iframes and a network request.  It doesn't gracefully handle the case of native advertising where advertising data may be intermixed with content data in a feed, for instance in a feed of stories rendered on the client by `amp-list` where some stories are sponsored and some are not.  There's currently no graceful way to render such content, contextually taking advantage of the content's styling, while still having the ability to track viewability as `amp-ad` provides. 

`amp-ad` already supports `placeholder` and `fallback` ad content which renders outside of the iframe, but these content blocks are ephemeral or must be triggered by API call (or timeout), respectively, and they are not meant to be easily tracked for visibility.
## Design

Similar to `fallback` and `placeholder` content, I propose to add a 3rd option called `ad` (or alternatively, `content`).  Content passed in this container will be displayed immediately by `amp-ad` and will negate the use of `fallback` or `placeholder` content.  

Unlike with `fallback` content, `amp-ad` should not immediately destroy the backing iframe, which would be hidden behind the ad content, since visibility tracking would still take place within the plugin code executed within that iframe.  If desired, an API could be introduced to allow the ad plugin to trigger the self-destruction of the iframe once the ad plugin has successfully sent whatever beacons it may choose to send.

This would give us the best of both worlds, I think - the ability to track very simple AMP-based ad markup without the overhead of A4A or the need for an external ad server providing the content, while still allowing us to track and beacon the visibility of the content with the flexibility offered by the use of Javascript APIs provided by `amp-ad`.  
## Notes

PR #5541 tracks a somewhat similar desire for non-iframed ad content, but is more restrictive (only allows for a simple image to be rendered) and still requires a network call, and view tracking support is unclear.

In some ways, this pattern could be thought of as being non-ad specific, I suppose.  It could be used to layer complex tracking behaviors on any arbitrary piece of content, which I imagine would be discouraged.  But if not, I suppose this could be implemented as a new component rather than part of `amp-ad` (something akin to `amp-embed`, for semantics?), sharing a similar plugin model.  

cc @lannka @jasti @dvoytenko

**Comment by cramforce** [comment]
Is visibility tracking the only thing you need the backing iframe for? Any reason `amp-analytics` doesn't work for that?

**Comment by lannka** [comment]
This sounds great to me.
```
<amp-ad type="native" data-url="https://youradserver.com/getnativead">
  <div content>
    <template type="amp-mustache">
      <div>
        <amp-img src="{{imageUrl}}" width=50 height=50></amp-img>
          {{title}}
      </div>
    </template>
  </div>
  <div fallback>...</div>
  <div placeholder>...</div>
</amp-ad>
```

This can be our TRUE native solution @jasti

**Comment by cramforce** [comment]
I understood the original proposal to not want any type of special AMP think. Just any regular AMP markup. I'd like to avoid introduces concepts if possible.

If this would get away without the `amp-ad` that would have many benefits I imagine (in terms of blockability for example).

**Comment by lannka** [comment]
@cramforce I thought we want to unify the ad experience in AMP.

**Comment by jasti** [comment]
With @cramforce on this one. Details [here](https://github.com/ampproject/amphtml/pull/5122#issuecomment-254371749) but basically @src-code needs viewability for different sections inside of the main element. amp-analytics only provides element level viewability. 
@lannka there is no need for data-url because the "ad" is already there alongside content.

**Comment by lannka** [comment]
hm I'm actually thinking about something different, which does not really solve @src-code's problem. I wanted to expand the [imagead](https://github.com/ampproject/amphtml/issues/5541) concept to nativead. We let publisher to render a JSON response to an ads without an iframe. Implementation wise, it will be actually the very close to `amp-list`.

**Comment by src-code** [comment]
@cramforce There were a few problems I was seeing while playing with an `amp-analytics`-based approach, please correct me if I'm misunderstanding on any of these:

   * Only works with `amp-*` elements, so I'd likely still need something like `amp-ad` to wrap my ad content anyway.  But not clear what element I'd actually want to use (an `amp-ad` fallback most likely?)  Seems better to keep the tracking in one place (`amp-ad`) rather than spread across multiple components (`amp-ad` and `amp-analytics`), and not use `fallback` for something it wasn't intended for.
   * `amp-analytics` visibility tracking only allows selection based on id or tag name.  The former doesn't work because I don't know each ad position in advance (content is lazy loaded via `amp-list`), and the latter isn't specific enough to only select my ads of a particular type.  
   * Though even if class selectors are supported, it seems `amp-analytics` only will send one beacon per config entry, so not clear that we could actually track all elements matched by a classname selector?
   * Does `amp-analytics` visibility tracking work with lazy-loaded content ala `amp-list`?

This is what led me to think that what we really want is something like `fallback` content in `amp-ad`, but to keep the tracking contained within that component/plugin since it already works so well.

**Comment by src-code** [comment]
@lannka Yeah, I was envisioning something more like:

```html
<amp-ad type="yahoo-native">
  <div content>
      <div>
         <a><amp-img src="..." width=50 height=50></amp-img></a>
         <a>Sample title</a> - Sponsored
      </div>
  </div>
</amp-ad>
```

Or maybe you could go more generic on the plugin and have a `native` type, and let the developer link to their own JS for tracking or what-not:

```html
<amp-ad type="native" data-src="https://s.yimg.com/amp/native-tracking.js">
  <div content>
      <div>
         <a><amp-img src="..." width=50 height=50></amp-img></a>
         <a>Sample title</a> - Sponsored
      </div>
  </div>
</amp-ad>
```

**Comment by cramforce** [comment]
If something is just non-iframe markup I don't care.

**Comment by src-code** [comment]
@lannka I've taken a stab at a simplistic approach, which you can see here: 

https://github.com/src-code/amphtml/commit/3d1f3e66beaa151e477fba600ab38ac3443f3e54

Basically introducing support for `content` node similar to `fallback`, except when `no-content` is handled (thanks to the amp-ad plugin calling `context.noContentAvailable()`), I check for the presence of the `content` node and give preference to it, hiding any `fallback` node that might be present and keeping the backing iframe for tracking purposes. 

I thought about moving the display of the `content` node into the `LOADING` state so it displays sooner, and thus not requiring the ad plugin to call `context.noContentAvailable()` to make the ad appear, but then you may miss out on tracking the views since the scripts would still need to load inside the iframe. So in this case the ads appear a little later, but after the amp-ad plugin scripts have loaded, which is more reliable.  

Thinking there's really multiple ways to approach this, but wanted to at least get something simple implemented to start, to help illustrate this proposal.

**Comment by src-code** [comment]
@lannka @cramforce Any thoughts on the implementation I've proposed?  Would love to see this move forward in one form or another so we can begin monetizing our content with native ads more easily.

**Comment by jridgewell** [comment]
The code looks fine, but I'm curious why `imagead` can't handle this? The initial PR allows generic content (it's not really an image ad anymore), and if we allow specifying arbitrary inline JSON we could skip the XHR request.

**Comment by src-code** [comment]
@jridgewell Yeah, makes sense to me if the two merged should `imagead` be more flexible in content and transport.  Though I'd probably prefer not to have to pass JSON, to keep things cleaner (I'm already rendering in my use case from an amp-list template.)

**Comment by jridgewell** [comment]
We could probably skip the XHR request entirely if there's no `<template>`.

**Comment by lannka** [comment]
@src-code I mis-understood your original proposal. As @cramforce has mentioned, if the only thing missing is the visibility tracking, we should just expand amp-analytics to be able to select child element. Using amp-ad's iframe to do visibility tracking is not a good idea. It's costly (using iframe postMessage) and also less reliable.

**Comment by src-code** [comment]
@lannka Would we be able to send multiple beacons per selector from amp-analytics?  My understanding is this doesn't happen today for visibility tracking.  (Eg, I want to match all instances of my ad using a class selector, and send 1 beacon for each as they become visible.)  Also, will amp-analytics do visibility tracking for lazy-rendered content such as from amp-list?

**Comment by lannka** [comment]
I think currently we support neither of them. @avimehta to correct.

We might though, if there're solid use cases.

**Comment by avimehta** [comment]
@lannka is correct. We don't support multiple instances currently but I think it should be easy to do.

As for, amp-list, amp-analytics integration with amp-list has not happened but it is something that we should consider. @rudygalfi @ericlindley-g , we can have an event that gets triggered when all the content inside the list is loaded. This even can probably be supported by all extensions that support lazy loading. Can you open a bug for this and prioritize?

**Comment by rudygalfi** [comment]
Filed #6413 for the request to have an amp-list loaded trigger.

**Comment by src-code** [comment]
@avimehta @rudygalfi @ericlindley-g @lannka So as far as `amp-analytics` goes, am I right in understanding we would need to address these issues to make this work?

1. Make `amp-analytics` visibility tracaking fire a separate beacon for each item matched by a selector
1. Make `amp-analytics` visibility tracking support class selectors (does this work today?)
1. Initialize `amp-analytics` visibility tracking during `loading` event from `amp-list` and other similar components so that new content may be tracked

I can file issues for these items if the general sense is that such an approach would be preferable to the `amp-ad` approach I prototyped in this issue.  I'd love to move this forward one way or another though, as the lack of visibility tracking currently makes it difficult for us to monetize our `amp-list` content with native (Gemini) ads.

**Comment by src-code** [comment]
Checking in on this one, is there current plans to address some of the `amp-analytics` gaps mentioned in [the above comment](#issuecomment-266865283)?  (Or have they already been addressed and I just missed it?  Been away from AMP for a little bit...)  If not, I'll open some issues up to track the individual pieces.  (It sounds like PR #7312 will help make item 3 possible, is that right @dvoytenko?)

**Comment by lannka** [comment]
Yep, please open separate request for item 1. 
item 2, i think class selector should work. but there's probably a bug: "amp-img.clazzName" worked but ".className" does not. 
@dvoytenko is indeed working on your item 3.

**Comment by src-code** [comment]
@lannka Sounds good, I'll file an issue for each item!

**Comment by src-code** [comment]
Closing this in favor of #7654 and #7656
