### ISSUE TITLE
Increase or allow controlling timeout for hiding carousel controls hinting on mobile

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#5723]
Carousel controls disappear on mobile pretty quick (currently hard-coded to 1 second). This is not enough time for the user to pay attention to the side of the page most of the time. I rarely notice a carousel exists and usually just thinks its an image and scroll past it.

Can we increase the default (maybe 3-5s) and possibly allow overriding this through an attribute if the publishers choose?

**Comment by camelburrito** [comment]
5 seems pretty long, and it would actually lead to a broken UX (worse than existing) - 

Dup of https://github.com/ampproject/amphtml/issues/3840
