### ISSUE TITLE
Accelerated Mobile Pages for vBulletin

### ISSUE THREAD

**Issue by MsXLabs** [ampproject/amphtml#5725]
Hello, you can download AMP for vBulletin mod here: http://www.vbulletin.org/forum/showthread.php?t=323668

Ps. sorry, I couldn't find elsewhere to send this link

**Comment by ericlindley-g** [comment]
Glad to hear there's AMP support for vBulletin, @MsXLabs, though I'm closing this issue, as we generally don't promote third-party support through GitHub.
