### ISSUE TITLE
Add cross-reference and/or comparison between amp-analytics variables and HTML URL Variable Substitutions

### ISSUE THREAD

**Issue by dandv** [ampproject/amphtml#5748]
https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/analytics-vars.md

vs.

https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md

**Comment by avimehta** [comment]
The two are betting combined in near future. @bpaduch has a PR that I need to review.
