### ISSUE TITLE
Bring AMP cache origin checks in alignment with CORS spec

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#5754]
The AMP CORS spec requires that the AMP Cache origin may be either 'cdn.ampproject.org' or '*.cdn.ampproject.org'.

We need to change all places that check for the proxy origin (such as `isProxyOrigin`) to respect both patterns.

**Comment by muxin** [comment]
I only found `isProxyOrigin` implementing the checking logic of proxy origin.

**Comment by cramforce** [comment]
Excellent. Please send PR to fix.

**Comment by jridgewell** [comment]
These need to be investigated, too:

- https://github.com/ampproject/amphtml/blob/master/3p/integration.js#L524-L526
- https://github.com/ampproject/amphtml/blob/master/ads/alp/handler.js#L142
- https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad/0.1/a2a-listener.js#L79
- https://github.com/ampproject/amphtml/blob/master/extensions/amp-form/0.1/amp-form.js#L105
- https://github.com/ampproject/amphtml/blob/master/src/document-submit.js#L67
- https://github.com/ampproject/amphtml/blob/master/src/service/viewer-impl.js#L465
- https://github.com/ampproject/amphtml/blob/master/src/service-worker/install.js#L40

**Comment by cramforce** [comment]
Yep, all of these should be replaced with a function like `looksLikeProxyUrl` that centralizes the logic and does the domain suffix match.

**Comment by muxin** [comment]
@jridgewell Thanks a lot!! Working on it
