### ISSUE TITLE
Highlight how you can have a non-AMP and an AMP version of the same page.

### ISSUE THREAD

**Issue by commanderfun** [ampproject/amphtml#5756]
This is an issue I have with the AMP documentation. 

The information on the page below should be explained and highlighted "front and center" in the docs.  Right now it's kind of buried in the docs.

"In some cases, you might want to have both a non-AMP and an AMP version of the same page, for example, a news article. Consider this: If Google Search finds the non-AMP version of that page, how does it know there’s an AMP version of it?"

https://www.ampproject.org/docs/get_started/create/prepare_for_discovery

Initially it wasn't clear to me if AMP HTML replaces my current site or is an alternate version of it. In real life cases most folks will experiment with AMP by creating alternate version of their HTML.   

I think you should explain the use of this tag on the non-AMP page ...

&lt;link rel="amphtml" href="https://www.example.com/url/to/amp/document.html"&gt;

right on this page ...

https://www.ampproject.org/learn/about-amp/

**Comment by ericlindley-g** [comment]
cc/ @pbakaus

**Comment by rudygalfi** [comment]
cc @bpaduch
