### ISSUE TITLE
AMP should support valid HTML

### ISSUE THREAD

**Issue by shogun70** [ampproject/amphtml#576]
The main purpose of many AMP custom elements is lazy loading media resources. For example:  

    <amp-img src="image.jpg" alt="Image description"></amp-img>  
instead of  

    <img src="image.jpg" alt="Image description" />

But `<amp-img>` is both invalid HTML and useless without JS. 
It would be great if AMP could accept markup such as

    <a rel="embed image" href="image.jpg">Image description</a>
and transform it to `<amp-img>` during the AMP-script's initialization phase.

The AMP-specific attributes of `<amp-img>` could be read from `data-*` attributes, or inline JSON:

    <a rel="embed image" href="image.jpg">
        <script type="application/json">
        {
        "width": 300
        }
        </script>
        Image description
    </a>

Similarly it would be great if all the AMP custom-elements had valid HTML equivalents.

**Comment by cramforce** [comment]
Please escape HTML in your post.
You can do what you want today. Just nest the suggested markup in amp-img.

**Comment by shogun70** [comment]
That isn't valid HTML. And most page authors won't repeat `<a href>` inside `<amp-img src>`.

**Comment by cramforce** [comment]
Sure, it is valid. Custom elements are part of the web platform:
http://www.w3.org/TR/custom-elements/

**Comment by cramforce** [comment]
Element names with dashes are reserved for this use case in HTML5.

**Comment by shogun70** [comment]
That still seems pretty speculative.

http://www.w3.org/TR/#tr_Web_Components
http://caniuse.com/#feat=custom-elements
https://dev.modern.ie/platform/status/customelements/
http://jonrimmer.github.io/are-we-componentized-yet/

**Comment by cramforce** [comment]
Implemented in Chrome, Opera, Firefox. Edge and Safari announced. 2 high
quality polyfills available. Doesn't get better than that in modern web
standards.

**Comment by niutech** [comment]
Why not use `<img is="amp-img" ...>` instead of `<amp-img ...>`, which is allowed by the Custom Elements spec?

**Comment by cramforce** [comment]
My impression is that there is no consensus on the `is` attribute between
implementers. It would, indeed, be almost perfect. There are some issues
with the preload scanner that I will publish a blog post on soon.
