### ISSUE TITLE
Have GA set the same client ID as in non-AMP

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#5761]
Right now, GA sets the client ID as GA1.N.MMM.MMM (when loading AMP page from publisher domain) which is measured as a user being bounced even though the user lands on the same domain. This is because GA sets the client ID as  MMM.MMM on non-AMP pages.

Note that this is only applies to the case when using below in the GA config.
    'vars': {
      'clientId': 'CLIENT_ID(_ga)',
    },

CC @rudygalfi

**Comment by lannka** [comment]
Given the high priority of this bug, and that the "filter" support (#2198) hasn't landed yet, discussed with @dvoytenko, we'll go for a temporary fix first (hard code the logic to strip-off the leading prefix). 

Let us know if any concerns. Meantime, we hope this eventually could be solved at GA server side, @avimehta

**Comment by 1987yama3** [comment]
Good!

However, you should match the definition to a strict clientID in Google Analytics.
In Google Analytics, the cookie is saved in the format of "GAa.b-c.dddddd.eeeee".
(the lower case letters of the alphabet are actually numbers. Besides, "-c" is mostly omitted.)

"GAa.b-c." is not strictly a client ID, but metadata when saving to a cookie.


Therefore, after retrieving the value from the cookie, you need to send the deleted "GAa.b-c." as ClientID.
