### ISSUE TITLE
Share tracking fragment vs. fragment navigation

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#5766]
Share tracking feature and fragment navigation feature both use fragment in the url. It's not clear what we should do when they conflict with each other. There are several cases:
### Case 1

The url only contains one fragment such as `www.google.com/amp/some-publisher/some-page.html#ElementId` and the `ElementId` doesn't start with `.`
#### Option A

Disable the share tracking url generation (no share tracking fragment will be added to the url). The url won't be changed and the fragment navigation should work.
#### Option B

Generate new share tracking fragment `54321` and update the url to `www.google.com/amp/some-publisher/some-page.html#.54321&ElementId`
### Case 2

The url contains fragment with navigation fragment and several key-value pairs such as `www.google.com/amp/some-publisher/some-page.html#ElementId&key1=value1&key2=value2` and the `ElementId` doesn't start with `.`
#### Option A

Disable the share tracking url generation (no share tracking fragment will be added to the url). The url won't be changed and the fragment navigation should work, even with extra key-value pairs in fragment.
#### Option B

Disable the share tracking url generation (no share tracking fragment will be added to the url). The url is changed to `www.google.com/amp/some-publisher/some-page.html#ElementId` where the extra info in the fragment is removed.
#### Option C

Generate new share tracking fragment `54321` and update the url to `www.google.com/amp/some-publisher/some-page.html#.54321&ElementId&key1=value1&key2=value2`.
#### Option D

Generate new share tracking fragment `54321` and update the url to `www.google.com/amp/some-publisher/some-page.html#.54321&ElementId` where the extra info in the fragment is removed.

**Comment by rudygalfi** [comment]
I think we agreed on the policy that the user should win, meaning we shouldn't do anything that would break the user's experience. I had a few questions:

- Does 1B still enable the internal document navigation to work properly?
- It doesn't make sense to be what benefits 2B has. Can you clarify?

**Comment by jridgewell** [comment]
I don't see why we can't just detect the `ElementId` in each of

1. `#ElementId`
2. `#ElementId&key1=value1`
3. `#.share&ElementId` 
3. `#.share&ElementId&key1=value1` 

then scroll to `ElementId` element. We shouldn't have to disable share tracking to get the normal experience.

**Comment by muxin** [comment]
@rudygalfi 
- We can still scroll to the `ElementId` element. Instead of using the browser's default scrolling, we will scroll to it ourselves.
- For 2B, I'm just thinking that it might be easier for the browser to perform default scrolling to the `ElementId` element operation without extra work to be done.

**Comment by cramforce** [comment]
For now, lets keep it simple (we can make it more complicated bast on feedback):

- if incoming fragment is non-empty and doesn't start with dot, don't override it with an outgoing fragment
- when the user clicks a fragment link **always** update the outer URL to simple #fragmentValue

**Comment by rudygalfi** [comment]
@muxin Are we resolved on an approach here? Can this be closed?

**Comment by muxin** [comment]
Yes, will go with malte's suggestion.
