### ISSUE TITLE
YouTube does not dispatch a `pause` event after video ends (unlike HTML5 video)

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#5776]
This means the animation keeps playing after video ends.
YouTube might be dispatching a different event for video end that can help us fix this issue.

**Comment by mkhatib** [comment]
Yes that would be ENDED or STOPED

**Comment by adelinamart** [comment]
@aghassemi maybe consider this for next week FIXIT week? Thanks

**Comment by aghassemi** [comment]
Good idea. added

**Comment by aghassemi** [comment]
@wassgha 

To repro this:
- pick a very short youtube video and change http://localhost:8000/examples/amp-youtube.amp.html to use that video (the autoplaying one at least).
- note that we have an animated equalizer icon at bottom corner.
- that icon is supposed to only be animating when video is playing, manually pausing the video for instance pauses the animation, all is good so far.
- THE BUG: but if you let the autoplaying YT video finish, the icon does not pause at the end. That's because we only listen to YT's `pause` event but `YT` does not send a `pause` event when video ends, instead it probably sends an event with a different name (`ENDED` or `STOPED`, not sure)
- We dispatch a `VideoEvent.PAUSE` when we receive pause event messages from YT iframe. We need to also dispatch `VideoEvent.PAUSE` when we receive the ended message from YT iframe.
