### ISSUE TITLE
AmpAdApiHandler: opt_defaultVisible is always true

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#5777]
In both calls, `opt_defaultVisible` is set to true. We should remove the parameter.

**Comment by zhouyx** [comment]
We are not setting `opt_defaultVisible` for 3P ad case. 
https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad/0.1/amp-ad-3p-impl.js#L230
However with the new `opt_isA4A`, it's true that we can get rid of `opt_defaultVisible`. I'll remove it.

**Comment by zhouyx** [comment]
fixed by #5882
