### ISSUE TITLE
Create prominent link to technical project from main website

### ISSUE THREAD

**Issue by premasagar** [ampproject/amphtml#579]
I followed a link to ampproject.org and it took me a long time to discover actually what it is. I think that putting a link to the [technical introduction](https://www.ampproject.org/how-it-works/) near the top of the page would be helpful, as currently it is at the bottom (on mobile).

**Comment by erwinmombay** [comment]
will bring this up to to the people who work on the page internally, thanks for bringing it up!

**Comment by Meggin** [comment]
We just launched quite a bit of docs in ampproject.org, with a much clearer link to them in the menu. Hpe this is a bit better.
