### ISSUE TITLE
Audit of code that could be removed or moved from v0.js

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#5792]
- [ ] We could remove the definitions of the `assert*` functions. Might not be worth it and be dangerous.
- [x] Remove `var process =` boilerplate. We don't use `process` as far as I can see.
- [x] Replace usages of `(new Date).getTime()` with `Date.now()`. I think the latter is recognized as side effect free.
- [ ] There are IIFEs that should be inlined.
- [ ] Move XHR/URLReplacements out of core
- [x] We have two Object.assign/Math.sign polyfills
- [x] If we provided our own Object.keys polyfill we could kill the (big) closure compiler polyfill (or rather all closure polyfills).
- [ ] `getMode()` is compiled into extensions. Might even re-run.
- [ ] `3p-frame`'s use of services to get a single bootstrap URL leads to getting all that infra into the extension.

**Comment by erwinmombay** [comment]
is there a convenience method inside closure to do the iife inlining?

**Comment by cramforce** [comment]
@erwinmombay If I see it correctly it never inlines them. And it definitely doesn't inline functions that contain functions. For AMP it would be better to always inline them.

**Comment by cramforce** [comment]
Added a few more.

**Comment by erwinmombay** [comment]
ill work on removing process and getMode removal. For the getMode removal, do we go the install module route or the global route (similar to log)?

**Comment by cramforce** [comment]
@erwinmombay I think the log route applies here.

**Comment by jridgewell** [comment]
There shouldn't be any need for an `Object.keys` polyfill, every browser has it.

**Comment by cramforce** [comment]
Do you know which version of Android WebKit added it?

**Comment by jridgewell** [comment]
[Kangax](http://kangax.github.io/compat-table/es5/#test-Object_static_methods_Object.keys) reports at least Android 4.0 (Ice Cream Sandwich) had it. If we're worried about even older versions, it's extremely easy to sham (key sorting will be undefined).

**Comment by adelinamart** [comment]
What's the status here? What else needs to be done?

**Comment by cramforce** [comment]
Stale
