### ISSUE TITLE
Add support for native sharing via amp-social-share

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amphtml#5799]
The [`amp-social-share`](https://www.ampproject.org/docs/reference/components/amp-social-share#types) component supports a few different providers, but none of them make it easy to see or share the canonical URL. (This is an issue because in many cases the URL that appears in the browser alongside an AMP is not the canonical URL, so the systems provided by the browser for sharing URLs produce unexpected results.)

It would be useful if the component supported a "copy URL to clipboard" function and/or the upcoming [native share intent](https://developers.google.com/web/updates/2016/10/navigator-share) (on Chrome+Android).

Actual:

![actual](https://cloud.githubusercontent.com/assets/51244/19689071/0dab0c62-9ac4-11e6-873c-30fff1a883d1.png)

Expected:

![expected](https://cloud.githubusercontent.com/assets/51244/19689077/12ab0c80-9ac4-11e6-9a89-7bc6f33cc051.png)

or

![expected2](https://cloud.githubusercontent.com/assets/51244/19689297/ce936456-9ac4-11e6-9d65-40bad154b883.png)

/cc @adewale @PaulKinlan

**Comment by cramforce** [comment]
yes, please!!!!!!

**Comment by cramforce** [comment]
I think we should bump version number, and make this the only displayed option when available :)

**Comment by ithinkihaveacat** [comment]
[For searchers: this would involve the `navigator.share` API.]

**Comment by cramforce** [comment]
@thinkihaveacat are you working on this by any chance? :) Happy to guide through it. Should be straight forward.

**Comment by ithinkihaveacat** [comment]
I haven't been but sure, I'll have a look at it over the next few days.

**Comment by ithinkihaveacat** [comment]
@cramforce I did some hacking in #6688—does this look okay?

**Comment by adewale** [comment]
What's the current status of this issue?

**Comment by jridgewell** [comment]
@adewale: #6688 was submitted, but stalled. Pinged on that PR.

**Comment by ithinkihaveacat** [comment]
Making some progress on the PR.

One thing I'm wondering about is whether it's going to be difficult to [fulfill the requirements for enabling origin trials](https://github.com/jpchase/OriginTrials/blob/gh-pages/developer-guide.md#how-do-i-enable-an-experimental-feature-on-my-origin) on the various AMP origins and caches. Since `<meta http-equiv="">` is invalid AMP, `Origin-Trial:` headers need to be added to every request—is this going to be problematic? The tokens expire every month or so as well.

**Comment by jridgewell** [comment]
> it's going to be difficult to fulfill the requirements for enabling origin trials on the various AMP origins and caches. Since `<meta http-equiv="">` is invalid AMP, `Origin-Trial:` headers need to be added to every request

/cc @Gregable. Can we allow `<meta>`s in this case? Or, can the cache also send whatever `Origin-Trial` headers the source page sends?

**Comment by Gregable** [comment]
We allow some specific variants of `<meta http-equiv=...>`, but we can't blanket allow them. For example, you can change the document encoding to something other than utf-8 with an http-equiv parameter. Is there a more specific rule we can add?

**Comment by jridgewell** [comment]
Specifically, can we allow `<meta http-equiv="origin-trial" content="***">`.

If we want to be _really_ specific, we could decode the origin trial value (it's base64 encoded), parse the JSON, then assert the trial name is whitelisted.

**Comment by ithinkihaveacat** [comment]
I'm pretty sure the token is tied to an origin, so the cache needs to add its own token if and only if the AMP itself includes a token. (Which will be different.)

I don't think it's possible to include the token on all requests because a given trial is only supposed to be on 0.03% of all page loads or less 

https://github.com/jpchase/OriginTrials/blob/gh-pages/explainer.md

**Comment by jridgewell** [comment]
> I'm pretty sure the token is tied to an origin, so the cache needs to add its own token if and only if the AMP itself includes a token. (Which will be different.)

Ohh, yah. We could apply for our own share origin trail on the CDN, then strip the origin trails when we ingest.

> I don't think it's possible to include the token on all requests because a given trial is only supposed to be on 0.03% of all page loads or less

Hmm, I hadn't heard of that. Looks like it's across all (whole internet) pages, though?

**Comment by cramforce** [comment]
Lets definitely allow `<meta http-equiv="origin-trial" content="***">` in the validator.

**Comment by ithinkihaveacat** [comment]
Yeah, the `<meta>` approach seems superior if the validator can be changed to allow it.

Provided Chrome is fine with multiple tokens for the same trial on the same page (in the process of testing this), this would mean that the cache won't have to transform AMPs to make origin trials work, and it will also allow origins to control where the native share option appears (on origin, on cache(s), or on both), which seems like the right result.

This should also help keep page loads incorporating the token under the threshold, since they will only appear on AMPs that explicitly want to test `navigator.share`.

I filed #7122 for the validator issue.

**Comment by ithinkihaveacat** [comment]
I've verified that Chrome is fine with multiple tokens for the same trial, so theoretically developers can embed two or more tokens, one for the origin, and one for each cache they care about.

The token for `cdn.ampproject.org` is:

```
AjQkyiCgG5iPFdJnbc/BHOxiJXzCd8tS1qO2BPNmUcjPhqTAlpCqguyW04T5U5JUik+rrEV/zE5+dMa+k3KT5gYAAABneyJvcmlnaW4iOiJodHRwczovL2Nkbi5hbXBwcm9qZWN0Lm9yZzo0NDMiLCJmZWF0dXJlIjoiV2ViU2hhcmUiLCJleHBpcnkiOjE0ODg4MTA2NjQsImlzU3ViZG9tYWluIjp0cnVlfQ==
```

(It's supposed to work with subdomains too.)

**Comment by jridgewell** [comment]
Can people register for Origin Trials for arbitrary domains?! Ie, does the next person who wants native share on `cdn.ampproject.org` gets that same token? Craziness.

**Comment by cramforce** [comment]
Question for a follow up: What if we put the origin trial token into AMP, so that this automatically works everywhere without each and everyone having to register one? origin trial tokens aren't actually tied to origins, right?

**Comment by jridgewell** [comment]
> What if we put the origin trial token into AMP, so that this automatically works everywhere without each and everyone having to register one?

/cc @vitaliybl 

> origin trial tokens aren't actually tied to origins, right?

Hm?
