### ISSUE TITLE
Is amp-form avaliable?

### ISSUE THREAD

**Issue by gustavopaes** [ampproject/amphtml#58]
Hi,

I have found on [amp-html-components.md](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-components.md#-amp-form) a doc about forms.

I have tried to use the example, but the message DISALLOWED_TAG is showed.

Are `amp-input` and related tags avaliable?

```
DISALLOWED_TAG amp-form
    (anonymous function) @ amp.js:10139
    (anonymous function) @ amp.js:10138

DISALLOWED_TAG amp-email-input
    (anonymous function) @ amp.js:10139
    (anonymous function) @ amp.js:10138

DISALLOWED_TAG amp-on
    (anonymous function) @ amp.js:10139
    (anonymous function) @ amp.js:10138
```

**Comment by dandv** [comment]
[Forms are now supported in AMP](https://amphtml.wordpress.com/2016/10/31/forms-now-supported-in-amp/).
