### ISSUE TITLE
amp-sticky-ad: NOT allow background transparency. 

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#5809]
This is a note to sticky-ad UI improvement work.
Since there are multiple approaches here, I open an issue for #5432 for better discussion.
Approach 1

```
<amp-sticky-ad>
  <div id="extra"></div>
</amp-sticky-ad>
```

Approach 2

```
<amp-sticky-ad></amp-sticky-ad>
<div> </div>
```

Approach 3

```
<div id="extra">
   <amp-sticky-ad></amp-sticky-ad>
</div>
```

Approach 4
calculate background-color value for amp-sticky-ad during runtime.

**Comment by jpettitt** [comment]
I'm not following here. Are you suggesting the  `div#extra` be used to set the BG color of the ad unit?  

What's wrong with just going with whatever gets inherited and letting the page author override in CSS if they choose?

**Comment by zhouyx** [comment]
We decided to use approach 4. I believe there's a UX study about this. 
@jasti

**Comment by jasti** [comment]
Hey @jpettitt. UX research has suggested that having sticky ads that don't span the entire width of the device is bad user experience. Showing that there _could be_ content behind the ad is considered bad.
This will be a change to ensure that the sticky ad container always spans the entire width of the device even if the width of ad is smaller than the device width. 
Please expect an announcement on amphtml-announce@googlegroups.com following the process suggested here within the next week: https://github.com/ampproject/amphtml/issues/5160 We'll make sure to launch the changes guarding an experiment, so devs have enough time to test changes.

**Comment by jpettitt** [comment]
@jasti Hmm, when did AMP become the UX police?  While you may be right about the research surely that's a publisher call on how to render their content?  Is there a doc someplace that declares what is and isn't in scope for AMP? Might I suggest that at a minimum you link the supporting research for this breaking change?

**Comment by jasti** [comment]
@jpettitt I agree that publishers should have the freedom to decide how to render their content but should that be the case if it promotes bad experience to the user?
The research unfortunately is not going to be public until January, but will link it as soon as it is. The reason we suggest making the changes now, is so we group them with some other UX changes like improvements to the close button. Announcement and reasoning coming soon.

**Comment by jpettitt** [comment]
Understood, my concern is AMP is getting mixed press (see the recent WSJ article) and the more of an "opinionated framework" (to use @cramforce phrase) it appears to be, without data to backup the opinions the more pushback we get from publishers.  When changes are made based on unpublished, private, research it starts to look a lot like a dictatorship.

**Comment by cramforce** [comment]
I'd also prefer to publish the data. There are 2 changes here

1. Non-transparent background: This is strongly preferred by users.
2. Close button optics: Pubs can still override it, we are just making the default non-ugly, so that they don't have to.
