### ISSUE TITLE
Amp-ad for AdSense needs data-ad-format parameter

### ISSUE THREAD

**Issue by fletc3her** [ampproject/amphtml#5810]
## Short description of your issue:

Google AdSense "Ad Links" placements require an insert tag with a `data-ad-format="link"` parameter. This is not listed as supported by the amp-ad tag. Without the "format" parameter AdSense is unable to serve link units and instead places another text/image ad on the page.

AdSense documentation suggests code like this for an "Ad Links" placement:

```
<ins class="adsbygoogle"
     data-ad-client="ca-pub-12345"
     data-ad-slot="12345"
     data-ad-format="link"></ins>
```

This would translate into an amp-ad tag as follows:

```
<amp-ad width=436 height=15
      type="adsense"
      data-ad-client="ca-pub-12345"
      data-ad-slot="12345"
      data-ad-format="link">
 </amp-ad>
```
## What browsers are affected?

All browsers.
## Which AMP version is affected?

Tested on Version 1476486609642

**Comment by cherri-qubeos** [comment]
Hi. Do you have an ETA on introducing a data-ad-format on amp-ad for adsense ?

I am waiting for this update to publish AMP version of my website cause I rely so much on link ads. I really need this :) Thanks and keep the good work :)

**Comment by jasti** [comment]
Hi there, unfortunately link ads is not supported at the moment but I hear that it is being worked on by the Adsense team. I'd recommend that you make this request via your Adsense support channels as well. Thanks!
@konakk FYI
