### ISSUE TITLE
default Gulp task hitting an error

### ISSUE THREAD

**Issue by barrars** [ampproject/amphtml#582]
NPM install / gulp  then error:
                                                     
[09:24:53] Using gulpfile ~\amphtml\gulpfile.js                                           
[09:24:53] Starting 'watch'...                                                                                 
Bundling amp-anim                                                                                              
Bundling amp-audio                                                                                             
Bundling amp-carousel                                                                                          
Bundling amp-fit-text                                                                                          
Bundling amp-iframe                                                                                            
Bundling amp-image-lightbox                                                                                    
Bundling amp-instagram                                                                                         
Bundling amp-lightbox                                                                                          
Bundling amp-slides                                                                                            
Bundling amp-twitter                                                                                           
Bundling amp-youtube                                                                                           
Processing ads.amp.html                                                                                        
Processing article.amp.html                                                                                    
Processing article-metadata/json-ld.amp.html                                                                   
Processing article-metadata/microdata.amp.html                                                                 
Processing everything.amp.html                                                                                 
Processing instagram.amp.html                                                                                  
Processing released.amp.html                                                                                   
Processing twitter.amp.html                                                                                    
Recompiling CSS.                                                                                               
Processing 3p/frame.max.html                                                                                   
[09:24:53] Finished 'watch' after 215 ms                                                                       
[09:24:53] Starting 'default'...                                                                               
[09:24:53] Finished 'default' after 18 μs                                                                      
fs.js:848                                                                                                      
  return binding.symlink(preprocessSymlinkDestination(destination, type),                                      
                 ^                                                                                             
Error: EPERM, operation not permitted '\amphtml\dist.3p\current'            
    at Error (native)                                                                                          
    at Object.fs.symlinkSync (fs.js:848:18)                                                                    
    at DestroyableTransform.<anonymous> (\amphtml\gulpfile.js:293:12)       
    at DestroyableTransform.emit (events.js:129:20)                                                            
    at \amphtml\node_modules\gulp\node_modules\vinyl-fs\node_modules\through
2\node_modules\readable-stream\lib\_stream_readable.js:965:16                                                  
    at process._tickCallback (node.js:355:11)

**Comment by erwinmombay** [comment]
@barrars can you tell me the OS (and version) and node/npm version you have? Thanks!

**Comment by barrars** [comment]
Win8.1
node: 0.12.7
npm: 2.11.3
**<pre>npm install </pre> actually had some errors related to needing to install visual studios which I'm doing right now.

**Comment by erwinmombay** [comment]
@barrars thanks. i don't have convenient access to a windows machine right now, i'll try and get a VM up and running to investigate.

**Comment by barrars** [comment]
I updated to node 4.1.2 and re-ran everything.  I'm still getting an error about installing MS visual studio which is going slowly.  I'll let you know.

I also don't understand the directions to map the localhost ....

**Comment by erwinmombay** [comment]
hmm might not need to do that part, i didnt have to do that for mac osx either

**Comment by barrars** [comment]
still getting 
<pre>[11:33:35] Finished 'watch' after 221 ms                                                                                   
[11:33:35] Starting 'default'...                                                                                           
[11:33:35] Finished 'default' after 9.29 μs                                                                                
fs.js:902                                                                                                                  
  return binding.symlink(preprocessSymlinkDestination(destination, type, path),                                            
                 ^                                                                                                         
                                                                                                                           
Error: EPERM: operation not permitted, symlink '.\1444674815295' -> 'C:\Users\scott\Desktop\localProject\amphtm            
l\dist.3p\current'                                                                                                         
    at Error (native)                                                                                                      
    at Object.fs.symlinkSync (fs.js:902:18)                                                                                
    at DestroyableTransform.<anonymous> (C:\Users\scott\Desktop\localProject\amphtml\gulpfile.js:293:12)                   
    at emitNone (events.js:72:20)                                                                                          
    at DestroyableTransform.emit (events.js:166:7)                                                                         
    at C:\Users\scott\Desktop\localProject\amphtml\node_modules\gulp\node_modules\vinyl-fs\node_modules\through            </pre>

**Comment by erwinmombay** [comment]
probably related https://github.com/nodejs/node-v0.x-archive/issues/6342

**Comment by barrars** [comment]
Doh, running with admin seems to have fixed it.  Does  <pre> gulp </pre> start a localhost ?  here is my stdput.  It just says finished.

<pre>PS C:\Users\scott\Desktop\localProject\amphtml> gulp
[11:42:07] Using gulpfile ~\Desktop\localProject\amphtml\gulpfile.js
[11:42:07] Starting 'watch'...
Bundling amp-anim
Bundling amp-audio
Bundling amp-carousel
Bundling amp-fit-text
Bundling amp-iframe
Bundling amp-image-lightbox
Bundling amp-instagram
Bundling amp-lightbox
Bundling amp-slides
Bundling amp-twitter
Bundling amp-youtube
Processing ads.amp.html
Processing article.amp.html
Processing article-metadata/json-ld.amp.html
Processing article-metadata/microdata.amp.html
Processing everything.amp.html
Processing instagram.amp.html
Processing released.amp.html
Processing twitter.amp.html
Recompiling CSS.
Processing 3p/frame.max.html
[11:42:08] Finished 'watch' after 234 ms
[11:42:08] Starting 'default'...
[11:42:08] Finished 'default' after 7.82 µs </pre>

**Comment by barrars** [comment]
Update actually....I just ran tests  and it seems to have passed.  I can't run <pre> http-server -p 8000 -c-1 </pre> though.  The error says that task is not in the gulpfile.  How do I launch a server for demos?

**Comment by erwinmombay** [comment]
sorry, my reply got lost or something.

so you'll need to run `npm i -g http-server` to install http-server then you can run that comman

**Comment by erwinmombay** [comment]
thanks for being patient btw, i'll try and update the docs or feel free to submit a PR to fix the docs :)

**Comment by barrars** [comment]
Awesome, thank you sir.  I may include a little windows perspective later haha.

**Comment by erwinmombay** [comment]
@barrars yeah that would be terrific :dancers: if i can get my new gaming rig i can start testing on windows lol

**Comment by erwinmombay** [comment]
@barrars closing this, feel free to submit a PR!
