### ISSUE TITLE
<amp-carousel>: layout responsive and type slides breaks in some cases

### ISSUE THREAD

**Issue by eike-hass** [ampproject/amphtml#5828]
## Short description of your issue:

In some cases on pageload the `<amp-carousel>` fails to initialize with error `AMP-CAROUSEL# Layout not supported for: responsive` although the correct parameters are supplied.
## How do we reproduce the issue?

https://ampbyexample.com/components/amp-carousel/   
1. Load Page
2. Click on outgoing link
3. Use Browser "back"
4. Repeat until error surfaces
## What browsers are affected?

Seems to affect Chrome on OSX and Android
## Which AMP version is affected?

1476486609642

**Comment by camelburrito** [comment]
@eike-hass thanks for reporting - looking into this!

**Comment by cramforce** [comment]
@camelburrito Could you give an update on this one?

#5897 is likely a dupe, but that seems like it could happen all the time.

**Comment by camelburrito** [comment]
yes i think it is because of using constructor instead of upgradeCallback here https://github.com/ampproject/amphtml/blob/master/extensions/amp-carousel/0.1/amp-carousel.js#L25 - working on a fix now.

**Comment by cramforce** [comment]
@camelburrito I left a comment on the PR. It didn't fix the problem. My comment has the proposed fix.

**Comment by cramforce** [comment]
@lannka We need to merge @camelburrito's and @dvoytenko's changes into the current canary.

**Comment by jridgewell** [comment]
Fixed by #5899 and #5908.
