### ISSUE TITLE
Extend existing HTML elements instead of creating custom ones

### ISSUE THREAD

**Issue by niutech** [ampproject/amphtml#583]
Please replace custom tags:
`<amp-img>` with `<img is="amp-img">`,
`<amp-pixel>` with `<img is="amp-pixel">`,
`<amp-video>` with `<video is="amp-video">`,
`<amp-audio>` with `<audio is="amp-audio">`,
`<amp-iframe>` with `<iframe is="amp-iframe">`
as described in the [Custom Elements spec](http://w3c.github.io/webcomponents/spec/custom/#dfn-type-extension). This will allow custom tags to be backward compatible with browsers having JavaScript disabled or when the AMP JS library could not be loaded from the CDN.
For now, the `<amp-img>` will be completely invisible, unless the the AMP JS library is loaded.

**Comment by niutech** [comment]
This behavior is on par with e.g. [Google Web Designer Web Components](https://github.com/niutech/gwdcomponents)' `<gwd-iframe>` element:
`<iframe is="gwd-iframe" source="..." scrolling="yes"></iframe>`

**Comment by jmadler** [comment]
I think, but I could be wrong, that the issue with this is that it prevents the AMP library from overriding the browser's loading of external resources.

**Comment by cramforce** [comment]
There are issues with the preload scanner that I will explain in a post,
soon.

As commented on another thread there is no consensus on the `is` attribute
between implementers.

**Comment by niutech** [comment]
Interesting. Where will I be able to read your post? And how does the `is` attribute implementation vary? [Webcomponents.js](https://github.com/webcomponents/webcomponentsjs/blob/master/src/CustomElements/register.js) supports it well.

**Comment by cramforce** [comment]
We actually do not use Webcomponents.js but rather @WebReflection's document-register-element because of smaller payload and wider compatibility.

My understanding is that browser vendors are not currently implementing `is`.

**Comment by niutech** [comment]
It seems that at least [Chromium](http://src.chromium.org/viewvc/blink/trunk/Source/core/dom/custom/CustomElementRegistrationContext.cpp) natively supports `is` attribute.

**Comment by justincavery** [comment]
I think most content producers have great control over the surrounding template applied to the content itself, however when it comes to accessing and manipulating the content found within the content block itself it becomes more difficult to achieve.

To provide access to this approach it would be much simpler to include an `is` attribute to existing valid HTML within the content block itself, and if not `is` then perhaps a `<img amp-img='ampversion-image.jpg' />`.

Ideally it would be great to rely on using  `picture` or `srcset` to provide the best suited image (although this will not include a set width and height to work from).

**Comment by dvoytenko** [comment]
`<img amp-img='ampversion-image.jpg' />` will not give us the right performance since it would force aggressive DOM scanning.

`<img>` will also not allows us to use the existing placeholder/fallback system that we aim to apply all "loadable" content.

`<img>` would also make it hard to control prerendering of documents where we want to restrict downloads. We can start going down the path of adding `data-src` instead of `src` and `data-srcset` instead of `srcset` - but that would not be an improvement.

`srcset` is fully ready to be used. But I'm not sure how much `picture` element adds to the existing layout/srcset capabilities.

**Comment by niutech** [comment]
I do not get the hassle with `<img is="amp-img" src="...">`. Plain old `<img>` worked great since the beginning of the HTML. Now they're *passé* and they are changed into JS-only `<apm-img>` thingy, breaking backward compatibility.

Have a look at a random mobile [BBC news](http://news.bbc.co.uk/mobile/i/bbc_news/top_stories/800/80074/story8007440.shtml) from 2009. Just 9 requests, no JS, no custom HTML, but instead works everywhere, has great speed index and fast loading time. Why rely on JS when we can go back to the basics?

Finally, shouldn't the user agent be responsible for prioritizing rendering images above the fold? I think at least Chrome [does that](https://plus.google.com/+IlyaGrigorik/posts/8AwRUE7wqAE).

**Comment by cramforce** [comment]
@niutech See https://medium.com/@cramforce/why-amp-html-does-not-take-full-advantage-of-the-preload-scanner-7e7f788aa94e
