### ISSUE TITLE
Jumping/twitching/jittering carousel images

### ISSUE THREAD

**Issue by ScotsScripts** [ampproject/amphtml#5838]
I'm still getting jumping carousel images. I don't think it has anything to do with old GPU hardware because it happens on my surface pro 3 in all browsers to some extend and my nexus 5. Here's a live URL:

https://scotsscripts.com/SMS/amp/category/modules.html

Any ideas on how to get rid of the jitter? I'm trying to get a plugin for an ecommerce system I work with out. Everything else is working, but this is holding me up. Any help would be much appreciated!

Note- there was an old issue open for this but the solution was to "check the dev channel" which didn't help me fix the issue.

Thanks!

**Comment by camelburrito** [comment]
@ScotsScripts i just tested your site on nexus5/Chrome, iPhone 6s/Safari , Mac osx/chrome - no jitters (even tested the machines where we were able to reproduce jitters before). 


Could you may be record a video and give more specifics?

**Comment by ScotsScripts** [comment]
Here's a link: https://drive.google.com/open?id=0BzpRWT3TYZ-1TzhXWFp2M1FBZUU

Looks like it's just doing it in Chrome now, and it works in other browsers for me now, so maybe it's just  chrome thing. I had turned off/on hardware acceleration and in the last thread they mentioned there could be an issue in that area. Maybe a coincidence but one of my beta testers gets the "oh snap" page error in chrome (other browsers OK.)

**Comment by camelburrito** [comment]
@ScotsScripts - can you give us the the os & browser information and your graphics chipset information.

**Comment by ScotsScripts** [comment]
Windows 10, latest Chrome (also latest Canary), Surface pro 3, Intel(R) HD Graphics 5000. All system software should be up to date. I'm leaning towards an issue in my Chrome environment (this was working until around 4 weeks ago), but no luck tracking it down.

**Comment by camelburrito** [comment]
@ScotsScripts - is this solved for you ?
