### ISSUE TITLE
CSP error on cloud.typography.com fonts

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#5844]
We saw a bug that
cloud.typography.com is doing a 302 redirect to a different domain, and the css is then blocked by CSP.

See [example](https://cdn.ampproject.org/v/heatst.com/entertainment/major-spoilers-the-entire-plot-of-game-of-thrones-season-7-may-have-been-leaked-on-reddit/amp/?amp_js_v=5).

It works fine on the canonical page, but has problem on CDN.

**Comment by jridgewell** [comment]
Trying to spoil GoT?! :rage1:

**Comment by cramforce** [comment]
CC @arajay

**Comment by arajay** [comment]
Be sure the domain is properly whitelisted at typography.com, including the https version if it exists and any sub-domains. However I did not get the 302 when I checked your site, so maybe you've already resolved the issue.

**Comment by cramforce** [comment]
This definitely still repros on
https://cdn.ampproject.org/v/heatst.com/entertainment/major-spoilers-the-entire-plot-of-game-of-thrones-season-7-may-have-been-leaked-on-reddit/amp/?amp_js_v=5

Check the Chrome console for the CSP violation.

**Comment by arajay** [comment]
Usually I see this problem when a site has been changed to use https from http OR when a redirect is in place that conflicts with the whitelist on typography.com (e.g. redirecting to www, but on typography.com whitelist you have not included www). Be sure your domain is properly whitelisted with typography.com including https and any www/non-www instances. 

In any case this is not really an issue with the AMP plugin but with a cross-domain request being sent to typography.com.

**Comment by cramforce** [comment]
@arajay There is actually nobody here from the original site, I think. We'd just like typography.com to not issue these redirects if possible.

**Comment by lannka** [comment]
@arajay the [example](https://cdn.ampproject.org/v/heatst.com/entertainment/major-spoilers-the-entire-plot-of-game-of-thrones-season-7-may-have-been-leaked-on-reddit/amp/?amp_js_v=5) here causes a redirect to publisher's own domain:
302 https://cloud.typography.com/6585494/7054952/css/fonts.css
blocked:csp https://heatst.com/wp-content/themes/heatstreet/static/fonts/447427/B9F7943C510994129.css

Just wondering in what situation there will be such a redirect?

**Comment by dayervi** [comment]
All the time, this is how typography works.

> Delivery works as before, with your CSS Key pointing to the cloud, and your Delivery Agent responding from the nearest server. Identifying the type of browser that’s asking for fonts, it immediately redirects each request to the correct files on your server.

**Comment by lannka** [comment]
Thanks @dayervi. As I read in your link, so this redirect is for development purpose only? If so, I think it's probably less a problem. Do you have a way to warn the publisher that they're having development mode in production?

**Comment by dayervi** [comment]
Actually, it's the opposite.

**Development mode**
css file is provided by cloud.typography directly with bandwidth limitation by month. I don't think there is a way to know if a configuration is use on a production environment but if you approach the bandwidth limit, you will be notified by typography requesting to switch on production mode (or pay to increase the limitation). And if you exceed the limit, the font will be no longer provided.

**Production mode**
typography redirect any request to the css file on your server. They can "manage" each request from their clients for statistics purpose, deliver fonts for authorized domains... All that without hosting the files.

**Comment by lannka** [comment]
Oh, my mis-read. 

Do all cloud.typography.com fonts in production mode redirect? If so, I think we might want to disable cloud.typography.com fonts in AMP entirely.

**Comment by dayervi** [comment]
I guess, but you should probably ask them directly for a definitive answer.

They claim to be AMP compatible regarding their [FAQ](http://www.typography.com/faq/question.php?faqID=171), but I don't understand how it can be possible.

**Comment by lannka** [comment]
Adding extra CSP meta tag will not make it work. It can never loosen the restriction made by the response header.

I guess there's nobody in this thread directly work for typography.com. @rudygalfi are we able to talk to them and search for a solution? Otherwise, we have to ask them to take down the [FAQ](http://www.typography.com/faq/question.php?faqID=171) page.

**Comment by rudygalfi** [comment]
Seeing if I can find someone at typography.com to address this

**Comment by adelinamart** [comment]
Any updates here? Thanks

**Comment by cramforce** [comment]
We should probably remove typography.com from the docs since this doesn't
actually work.

**Comment by lannka** [comment]
@Gregable shall we also start to warn pub about using fonts from typography.com?

**Comment by cramforce** [comment]
No need. I'd really prefer to get Typography.com into a working state.
