### ISSUE TITLE
Let's not skip running tests for doc-only changes

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#5848]
Two problems:
1- Doc only changes will return 0 and make the master build green without actually running tests, despite build actually being red ( e.g. https://travis-ci.org/ampproject/amphtml/builds/170956232 )
2- Doc only changes can still fail tests! For instance there are tests that check validity of `example/*.amp.html` but presubmit is not run against changes in `example/*` (e.g. https://github.com/ampproject/amphtml/pull/5847)

**Comment by aghassemi** [comment]
assigning to @erwinmombay since he seems to know exactly what to change for this ;)

**Comment by jridgewell** [comment]
2) doesn't apply anymore after #5851.

I'd really like to keep this kind of mechanism to keep doc updates as simple as possible.

But, we have a bug with the `$TRAVIS_COMMIT_RANGE`. I guess I assumed it be something similar to `HEAD...master`, but apparently it's `HEAD...HEAD~` which is useless for our PR tests. We should alert the react and babel folks about this, too.
