### ISSUE TITLE
amp-sticky-ad fails with 'amp-sticky-ad must have a single amp-ad child' even if one ad is disabled with amp-experiment

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#5852]
If I create an `<amp-sticky-ad>` with two `<amp-ad>` tags controlled by an `<amp-experiment>` the `amp-sticky-ad` code sees them both as active and refuses to render.

Expected behavior: Only enabled tags should be counted.

This is preventing us from deploying `<amp-sticky-ad>` on several production sites.  Is there any workaround you can think of?

**Comment by jpettitt** [comment]
Update: putting the experiment on the `<amp-sticky-ad>`seems to work so this is no longer blocking us.

This fails
```
<amp-sticky-ad>
  <amp-ad class="exp1"></amp-ad>
  <amp-ad class="exp2"></amp-ad>
</amp-sticky-ad>
```

This works

```
<amp-sticky-ad class='exp1'>
  <amp-ad ></amp-ad>
</amp-sticky-ad>
<amp-sticky-ad class='exp2'>
  <amp-ad ></amp-ad>
</amp-sticky-ad>
```

**Comment by jridgewell** [comment]
`<amp-sticky-ad>` has very tight restrictions for now. I'd like to see it loosened to support arbitrary children. @zhouyx?

**Comment by jpettitt** [comment]
Arrg.  Spoke too soon.  The runtime validator accepts the solution with two `<amp-sticky-ad>` tags but the cdn one doesn't.  So I'm still blocked on this.

**Comment by jpettitt** [comment]
I'd call this a bug not a discussion.  Elements enabled/disabled by `<amp-experiment>` should work inside any other amp tag.

**Comment by zhouyx** [comment]
Interesting, so I assume validator checks that there must be only one `<amp-sticky-ad>`  in a page. 
Not supporting `amp-experiment` sounds like a bug to me. How would we like to fix this? Do we want to fix style one (2 ads in sticky-ad) or style two (2 sticky-ads)?

**Comment by ericlindley-g** [comment]
cc @rudygalfi as this relates to `amp-experiment`

**Comment by rudygalfi** [comment]
cc @lannka 

This is an interesting case. Will it be possible for the validator to discern how an experiment will affect visibility of elements? Even so, an experiment could be configured to attempt to show two items within an element that spec'd to permit just one, so it seems like this is something that's only enforceable at runtime.

The enforcement by the validator of how many elements can be nested within another element seems to be something that's not strictly necessary. For instance, assume an element takes just one nested element. We could, for instance, just ignore any of the nested elements beyond the first at runtime. Similarly, based on how an experiment is configured to show/hide some elements, possibly we could adapt this logic to ignore all but the first _visible_ one.

So, maybe there's a couple paths forward:
1. We loosen validation and document the behavior above.
2. We keep validation tight for the non-`amp-experiment` case, but we introduce something like a `variant` attribute you could add to elements to indicate that `amp-experiment` might be playing a role and to not enforce such strict validation, leaving the AMP to just drop anything that violates the spec at runtime.

**Comment by jpettitt** [comment]
In the case of sticky ad the validator constrains dimensions so limiting whats in the element seems excessive.  Example I'd like to be able to put a carousel of stories in a sicky ad with one or two native ad links.  Can't do that eight now becasue ads can't be in a fixed layer and stick only allows one ad.

**Comment by jpettitt** [comment]
see https://github.com/ampproject/amphtml/issues/4874

**Comment by jpettitt** [comment]
Nudge.  We'd really like to be able to use `amp-experiment` to manage multiple ad providers in an `amp-sticky-ad` without having to resort to doing it server side with DFP.  I seems to me that the "only one `amp-ad` in a sticky" rule is unneeded given the size restrictions of the sticky itself.

**Comment by jridgewell** [comment]
Closing this for #4874.
