### ISSUE TITLE
Misalignment on AMP carousel pictures

### ISSUE THREAD

**Issue by Wleyba** [ampproject/amphtml#5859]
Short description of your issue:
Misalignment on AMP carousel pictures for Android JB device. (See links)

How do we reproduce the issue? 
1. Turn on Opt ins
2. Open AGSA and query "Trump"
3. Observe AMP carousel

What browsers are affected?
AGSA version 6.5.35.16.arm
Android JB version 4.3

Which AMP version is affected?
"dev-channel" and "make-body-relative" AMP experiments

![ampjb1](https://cloud.githubusercontent.com/assets/23106386/19781513/664dc690-9c3e-11e6-81ce-7f23f2ed8bc4.png)

![ampjb2](https://cloud.githubusercontent.com/assets/23106386/19781520/6c8d1452-9c3e-11e6-8c55-fc839ae4e40a.png)

cc/ @ericlindley-g and @dvoytenko

**Comment by camelburrito** [comment]
This is a search issue not amp's

**Comment by jridgewell** [comment]
I couldn't see the picture... 😬

**Comment by ericlindley-g** [comment]
@Wleyba Is this issue present only with the "dev-channel" and "make-body-relative" experiments activated, or does it happen without, as well?

**Comment by dvoytenko** [comment]
Can't see a screenshot. Could you please repost?

**Comment by Wleyba** [comment]
Not sure why the screenshot is not uploading properly

**Comment by Wleyba** [comment]
I did notice this issue without the experiments activated so it might be a search issue and not AMP related

**Comment by camelburrito** [comment]
@Wleyba are you seeing in the search page ? Here ? 
![screen shot 2016-10-27 at 2 21 54 pm](https://cloud.githubusercontent.com/assets/1037311/19786023/c4443f06-9c50-11e6-9caa-b53faf763d46.png)

Or are you seeing it inside the actual page itself?

**Comment by Wleyba** [comment]
@camelburrito I see it on the search page

**Comment by camelburrito** [comment]
Cool - so ill close this issue here and @ericlindley-g will follow up on the bug with the search team.
