### ISSUE TITLE
Validator Error on Boilerplate: mandatory text (CDATA) inside tag 'head > style[amp-boilerplate]' is missing or incorrect.

### ISSUE THREAD

**Issue by kscoulter** [ampproject/amphtml#5860]
## Short description of your issue:
The validator throws an error `he mandatory text (CDATA) inside tag 'head > style[amp-boilerplate]' is missing or incorrect.` event though I copy/pasted from amp project.

Here's my amp-related code in the head:

```HTML    
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
    <script async src="https://cdn.ampproject.org/v0.js"></script>
    <script async custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js"></script>
    <script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>
    <style amp-custom>
      <%@ include file="amp.css" %>
    </style>

```
I looked at other issues with this validator message, but was not able to find anything that relates to my problem.

[Link to validator](https://validator.ampproject.org/#url=http%3A%2F%2Forigin-sandbox.infobae.arcpublishing.com%2Famp-article-page%2F%3FoutputType%3Damp-type%26).

**Comment by Gregable** [comment]
The example does not match the string here:
https://github.com/ampproject/amphtml/blob/master/spec/amp-boilerplate.md

In particular `0` is replaced by `0s` in several places.

**Comment by kscoulter** [comment]
@Gregable, not sure what you mean. When I copy and paste from the link you provided, my text editor tells me there is no difference between the "old" string and the new one (no new changes to commit).

**Comment by kscoulter** [comment]
@Gregable, fwiw this issue was caused by google CSS minifier. It removed the `s` characters for some reason.
