### ISSUE TITLE
update amp-live-list docs for publisher origin ajax response

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#5866]
right now most publishers are returning 200 even with no changes. This should be 304s and with the correct headers.

also need to double check how amp-live-list component will handle 304

**Comment by ericlindley-g** [comment]
FYI: Calling this a documentation bug for now

**Comment by erwinmombay** [comment]
@cramforce what should be the correct response headers here?

**Comment by ericlindley-g** [comment]
@erwinmombay  — just wanted to see if you were still blocked on getting info on the response headers

**Comment by bpaduch** [comment]
will look @ in: Q2

**Comment by bpaduch** [comment]
@erwinmombay - any further info on this?

**Comment by CrystalOnScript** [comment]
@erwinmombay - is this still an issue? Any suggested documentation updates to make this more clear for publishers?
