### ISSUE TITLE
A FORM element needs an input type=submit; uncaught console log error

### ISSUE THREAD

**Issue by jamescridland** [ampproject/amphtml#5871]
My AMP page validates, but on load has an uncaught error in the JavaScript console saying:

```
log.js:243Uncaught (in promise) Error: form requires at least one <input type=submit>: form​​​
    at xa.f.assert (https://cdn.ampproject.org/v0.js:11:342)
    at new ma (https://cdn.ampproject.org/v0/amp-form-0.1.js:17:5)
    at https://cdn.ampproject.org/v0/amp-form-0.1.js:26:75
    at Array.forEach (native)
    at https://cdn.ampproject.org/v0/amp-form-0.1.js:26:53
    at ea (https://cdn.ampproject.org/v0/amp-form-0.1.js:3:178)
    at da (https://cdn.ampproject.org/v0/amp-form-0.1.js:3:132)
    at ta (https://cdn.ampproject.org/v0/amp-form-0.1.js:26:16)
    at https://cdn.ampproject.org/v0/amp-form-0.1.js:26:191
    at fa (https://cdn.ampproject.org/v0/amp-form-0.1.js:4:42)
```

It is entirely correct. The form in question (the first FORM element in the page) has no INPUT TYPE=SUBMIT.

My expected behaviour is that this should have failed validation. Or, it should not have kicked up this error.

## How do we reproduce the issue?

When visiting https://media.info/radio/data/the-most-popular-radio-stations-in-the-uk this error should appear on load in the Javascript console.

I'm running ChromeOS Version 54.0.2840.79 beta
Platform 8743.76.0 (Official Build) beta-channel veyron_minnie 
Powered by AMP ⚡ HTML – Version 1477334765771 
and using https://cdn.ampproject.org/v0/amp-form-0.1.js

//j

**Comment by mkhatib** [comment]
Thanks for filing @jamescridland this is WAI, we didn't enforce this in the validator but kept it in runtime to make sure there's always a submit button.

However, this requirement will go away from runtime once #5707 is deployed. This allows you to not have a submit button and instead you can trigger `form.submit` action on any AMP-event you'd like. This will be deployed to production in 2 weeks. Keeping this open until that happen.
