### ISSUE TITLE
Misaligned amp-sticky-ad

### ISSUE THREAD

**Issue by wstovermdp** [ampproject/amphtml#5875]
## Short description of your issue:

Vertical centering misalignment inside the amp-sticky-ad iframe. We have seen low viewability numbers from this unit on iOS, where Andorid has no issues.
## How do we reproduce the issue?

https://www.google.com/amp/amp.parents.com/parenting/better-parenting/advice/ways-to-be-fantastic-parent/
With Safari on iOS 10.0.1, scroll down to trigger the sticky ad. Must be in-device and not with emulation.
## What browsers are affected?

Safari in iOS 10.0.1 
It looks OK on iOS 10.1
## Which AMP version is affected?

1477334765771

![image](https://cloud.githubusercontent.com/assets/9354217/19813304/c309e268-9cfe-11e6-8afa-42e8a89ba374.png)
![image](https://cloud.githubusercontent.com/assets/9354217/19813325/d76704de-9cfe-11e6-8071-1b977d2587c9.png)

**Comment by zhouyx** [comment]
@wstovermdp There's a known issue with sticky-ad that I am working on a fix for it. #5862. The low viewability numbers from iOS should come from that.
Otherwise I tested your page with 10.0.1 on device, and didn't see a mis-alignment issue with ad inside sticky-ad, seems to be the ad iframe itself is mis-aligned to me sometimes.

**Comment by wstovermdp** [comment]
Thanks for the response @zhouyx. Here is a little bit more information. I'm not sure if this will make a difference, but what device  did you test on? We have noticed the issue on the iPhone 6+ with iOS 10.0.x. 

Also, when I removed the positioning rules on `div#c`, the centering looked correct. This is what led me to believe the issue is inside the amp-ad iframe, and not related to any site CSS rules.

**Comment by ericlindley-g** [comment]
cc @jasti

**Comment by jasti** [comment]
@zhouyx, can you please confirm if this has been addressed with 1.0? Thanks.

**Comment by zhouyx** [comment]
This has been addressed both 0.1 and 1.0
