### ISSUE TITLE
Feature request: Optimize font loading

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#588]
Currently all custom fonts included in AMP documents are subject to the browser's default loading behavior.

Since there is only a single heuristic for all fonts, it cannot be good in all cases.

There are two primary types of fonts:

1. Logo fonts. You'd never want FOUT (unstyle text) with these, but FOIT (invisible text) would be fine
2. Content fonts. Here various different behaviors may be desirable:
  - Timeout after which fallback font is shown
  - FOUT
  - I'd argue that FOIT is not good in this case.

Whatever the solution is to achieve these goals, it should ideally not require a JavaScript download to initiate the font request.

**Comment by cramforce** [comment]
An extension to CSS for native support is under development
https://tabatkins.github.io/specs/css-font-display/

**Comment by bstell** [comment]
What is the timeframe and browser support AMP is interested in?

The proposed features in [CSS Font Rendering Controls Module Level 1](https://tabatkins.github.io/specs/css-font-display/) look interesting. This looks to build on [CSS Font Loading Module Level 3](https://drafts.csswg.org/css-font-loading/) which was first proposed [19 months ago](https://www.w3.org/standards/history/css-font-loading-3) and currently is still an editor's draft and not supported in [Safari/IE](http://caniuse.com/#feat=font-loading).

**Comment by cramforce** [comment]
We can't count on that being implemented for being fast. But ideally a solution would be super simple when that is available.

**Comment by KenjiBaheux** [comment]
We hope to be able to ship CSS font-display.

**Comment by cramforce** [comment]
Closing @sriramkrish85 implemented `amp-font` for this.
