### ISSUE TITLE
Validator UI: Detect when canonical URL submitted

### ISSUE THREAD

**Issue by mjangda** [ampproject/amphtml#5885]
Minor UX improvement.

If you put in the non-AMP canonical URL in the validator UI (https://validator.ampproject.org/), it correctly errors out since the page isn't valid AMP.

However, it would be nice if the validator could detect the `amphtml` meta inline and offer to validate that the AMP version of the page instead.

This is something that the AMP Bench tool does, e.g. https://ampbench.appspot.com/validate?url=https%3A%2F%2Famphtml.wordpress.com%2F2016%2F10%2F26%2Fdo-more-with-ads-on-amp%2F (automatically detects the AMP link and redirects to it instead).

**Comment by powdercloud** [comment]
Thank you for bringing this up. I think for now I'd like to pass on it. Reason being, I think it's something that the users can figure out by themselves and there's some complexities for doing this well. ampbench covers some things that are thus far beyond the scope of the validator, so it fits more easily there.
E.g., I think a solution should probably inform the user and perhaps be interactive, and not just redirect or issue two fetches. And perhaps we should solve this by changing the error messages from the validator - as opposed to a change in the UI, to do something reasonable on the command line and in other places as well. So I think any solution should come with some amount of consistency between these behaviors. I don't see something obvious and cheap to do right now that would be in proportion to the modest improvement in convenience we'd get out of it. Still open for suggestions, but til then I'll go for closing the bug. Please feel free to reopen as you see fit.
