### ISSUE TITLE
A4A: Should Signature Validation be a Failure

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#5889]
> Semantically validation failure is not an error. Should we keep it as Project.reject?
> - @lannka https://github.com/ampproject/amphtml/pull/5841/files/541bc43ef9ad7ebc1a9c569a0218707fbf4dd50d#r85465134

/cc @lannka @ampproject/a4a

**Comment by lannka** [comment]
It depends on if we want to report a validation failure as dev error and tracked in our error reporting.
@tdrl @keithwrightbos in what cases and how often do you see such a failure right now?

**Comment by keithwrightbos** [comment]
@tdrl can confirm but I believe recent analysis showed it to be very
infrequent

**Comment by jasti** [comment]
Ping. Is there a verdict, @jridgewell?
