### ISSUE TITLE
AMP throwing errors when scripts are higher than the CSS in <head>

### ISSUE THREAD

**Issue by pbakaus** [ampproject/amphtml#5897]
To reproduce:

1. Grab a copy of https://github.com/ampproject/docs and run it locally
2. In `views/partials/head.html`, move the `<style amp-custom>` block below the script inclusions
3. Emulate a "Normal 3G" connection in the Network panel in Chrome DevTools
3. Reload the homepage

You'll notice the following: 

1. Console shows `AMP-CAROUSEL# Layout not supported for: flex-item`
2. The "Publishers" carousel at the bottom stops working

Curiously, this must be some sort of race condition, as it does not happen on an unthrottled connection.

/cc @cramforce

**Comment by jridgewell** [comment]
@camelburrito: Related to https://github.com/ampproject/amphtml/issues/5828?

**Comment by cramforce** [comment]
yeah, I think this is the same bug.
