### ISSUE TITLE
amp-live-list docs: server-side filtering link broken

### ISSUE THREAD

**Issue by dandv** [ampproject/amphtml#5904]
At https://www.ampproject.org/docs/reference/components/amp-live-list#server-side-filtering, the link to `Server side filtering` is broken - https://www.ampproject.org/docs/reference/components/components/amp-live-list-server-side-filtering.html

However, the Markdown appears correct at https://github.com/ampproject/amphtml/blob/master/extensions/amp-live-list/amp-live-list.md#server-side-filtering.

How is that link generated?

**Comment by bpaduch** [comment]
This link is generated through the importing of reference docs into the ampproject.org via [import.js](https://github.com/ampproject/docs/blob/master/scripts/import_docs.js#L82).

I'll submit a fix to correct this link. I've checked the reference docs and this is the only occurrence using this pattern that got messed up.
