### ISSUE TITLE
Clarify which server is polled by amp-live-list

### ISSUE THREAD

**Issue by dandv** [ampproject/amphtml#5907]
The [amp-live-list docs](https://github.com/ampproject/amphtml/blob/master/extensions/amp-live-list/amp-live-list.md) (or the [server filtering section](https://github.com/ampproject/amphtml/blob/master/extensions/amp-live-list/amp-live-list-server-side-filtering.md)) should specify if the Google AMP cache stays involved when the server is polled for updates.

Scenario:
1. The AMP document is served from the cache
2. The publisher would like to serve geo-tailored live updates based on the location of the user (IP-geolocated [for now](https://github.com/ampproject/amphtml/issues/826))
3. It's unclear if the original Google AMP cache URL is polled, or if the publisher's endpoint is.

**Comment by bpaduch** [comment]
@danv - Can we close this now based on the changes Eric made?
