### ISSUE TITLE
Document that <link rel="amphtml"> must appear within X bytes of beginning of canonical file

### ISSUE THREAD

**Issue by derat** [ampproject/amphtml#5909]
I recently noticed that the AMP versions of my pages were no longer being returned as Google search results. Google's <a href="https://developers.google.com/amp/cache/reference/acceleratedmobilepageurl/rest/v1/ampUrls/batchGet">ampUrls.batchGet</a> API similarly reported not knowing about the AMP versions of my canonical URLs. This was confusing to me, as all of my AMP pages continued to validate successfully and be served by the AMP Cache.

I eventually realized that this was probably triggered when I added JSON-LD structured data near the tops of my canonical pages' &lt;head&gt; sections, above their &lt;link rel="amphtml"&gt; tags. Doing so made the &lt;link rel="amphtml"&gt; tags appear ~1300 bytes into the files. After moving them back to the top of the file, just below &lt;meta charset&gt;, the ampUrls.batchGet API soon reported the AMP versions of my pages again.

This is probably a Google-specific caveat, but it seems likely to me that other crawlers may also only read to some fixed offset within files looking for &lt;link rel="amphtml"&gt; tags. I'm wondering if it would make sense to provide guidance in the official docs that these tags ought to appear within X bytes of the beginning of canonical files. I also haven't done a very slow binary search to figure out what X is (1024?). :-)

<a href="https://stackoverflow.com/questions/40270659/amps-have-stopped-appearing-in-search-results-pages-how-to-remedy">This StackOverflow question describes a similar problem</a>, and I suspect it had the same cause &mdash; Google now returns the AMP version of the URL mentioned there, but that page now includes &lt;link rel="amphtml"&gt; near its top, while the version of the page present in Google's cache included it 4975 bytes into the file, even later than my pages did.

This may also be the cause of the problems reported in bug #2264.

**Comment by derat** [comment]
Specifically, https://www.ampproject.org/docs/guides/discovery doesn't say anything about where &lt;link rel="amphtml"&gt; needs to appear besides "in the &lt;head&gt;". https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#amp-document-discovery may also be a good place to mention this.

**Comment by derat** [comment]
And a few more examples of people hitting this:
https://productforums.google.com/forum/#!topic/webmasters/Y61R-w53yHE
https://productforums.google.com/forum/#!topic/webmasters/Wi2EkSEAXMI

**Comment by cramforce** [comment]
We can ping the team at Google. Maybe they have a bug. AMP has no placement
requirement for the link tag.

**Comment by cramforce** [comment]
Google is tracking this as b/32529163

I will close this issue, because the AMP Project GitHub is not a place to discuss Google specific questions, but will comment when that issue resolves.

**Comment by cramforce** [comment]
Feedback is that there is no such limit.

Note, that HTML5 is strict as to what elements can appear inside `<head>`. If you accidentally use an element that cannot be in `<head>`, then the head is implicitly closed and everything following it appears to the parser as part of the body.

**Comment by MadisonMiner** [comment]
cramforce, how can I find Google's tracking this as b/32529163? 

I'm experiencing the same issue. However, my amphtml tag is at the top of the page. Problem described here: 
https://groups.google.com/a/googleproductforums.com/d/msgid/webmasters/ea4b064c-7de7-40d4-a9ba-ff3ef4026d03%40googleproductforums.com?utm_medium=email&utm_source=footer

Thank you,

**Comment by cramforce** [comment]
@MadisonMiner Do you have a sample link? The most likely problem is that you have something in your `<head>` that is not allowed to be there per HTML spec (and which per HTML spec auto-closes the head.
