### ISSUE TITLE
Invalid content inside style[amp-boilerplate]

### ISSUE THREAD

**Issue by wafcio** [ampproject/amphtml#5912]
## Short description of your issue:

I have extracted `style[amp-boilerplate]` content to separated sass file. I use sass compiler to minify style. Difference between your `style[amp-boilerplate]` and minified by sass is only one:

Your code:

```
steps(1,end)
```

Sass compiler output:

```
steps(1, end)
```

I think is doesn't have big difference exists this extra space inside each step. But your validator says that it is invalid.

## How do we reproduce the issue?

I run it in ruby code:

```
root_node = ::Sass::SCSS::CssParser.new("CSS_STYLES", 'middleman-css-input', 1).parse
root_node.options = { style: :compressed }
root_node.render.strip
```

where CSS_STYLES contains any CSS.

## What browsers are affected?

It doesn't matter.

## Which AMP version is affected?

I checked it by the validator.

**Comment by Gregable** [comment]
There are an infinite number of functionally equivalent strings for the boilerplate. We eventually settled on allowing any amount of whitespace between parts of the string that require whitespace, and none otherwise. If you use the exact boilerplate provided in the spec, it will always work.
