### ISSUE TITLE
[amp-analytics] elementY is not really the Y coordinate

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#5916]
According to the spec, [elementY](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/analytics-vars.md#elementy) should be the Y coordinate of the element specified in visibility tracking. However, the code [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/visibility-impl.js#L495) calculates it as 

```
elementY = rootBounds.top + clientBounds.top
```
which is wrong because `rootBounds.top` is always 0. See [rootBounds](https://github.com/ampproject/amphtml/blob/master/src/intersection-observer.js#L102). 

rather, we should do
```
elementY = viewport.getScrollTop() + clientBounds.top
```

Same thing applies to `elementX`. I manually tested it, and it does produce the bug.

@avimehta could you confirm?

**Comment by avimehta** [comment]
looks like this might have broken on [Sept 22nd by #5131](https://github.com/ampproject/amphtml/pull/5131). Since there were no tests(or were they not testing the right thing?), this was never flagged. When you are fixing this, can you add tests for this?

Also, other variables/calculations might also have gotten screwed up because of that. We'll need to look at those as well.

/cc @jridgewell

**Comment by jridgewell** [comment]
#5131 actually fixed a bug I introduced two weeks prior in #4826.

When you say the Y coord of the element, which Y are you talking about? We can either give you the viewport-relative Y coord, or the absolute (from the top left corner of the document) Y coord. We're currently giving you the first one, which may not be "wrong". If you want the absolute coord, call `element.getLayoutBox()`.

**Comment by lannka** [comment]
@avimehta which `elementY` should it be? I suppose this is something also available in Google Analytics? We just need to be consistent then.

**Comment by avimehta** [comment]
I think we want the absolute value. The documentation (which I wrote) is not clear at all but the intent seems to say that I wanted to provide absolute values. That is another thing that'll need to fix.

@jridgewell Thanks for pointing it out. So were the rootbounds.{x,y} always 0? I am probably reading the code wrong but looks like the value of {x,y} was non-zero before [the change](https://github.com/ampproject/amphtml/pull/4826/files#diff-399e2f3a24140467433bc65e8419d706L42).

**Comment by jridgewell** [comment]
Maybe? 😬
