### ISSUE TITLE
Recursively un-cache Resource Owner

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#5917]
A follow up to https://github.com/ampproject/amphtml/pull/5898.

Imagine:

```html
<owner>
  <child>
    <grandchild>
```

When `<grandchild>` first check if it's "owned", it will cache the result on its `Resource`, as does `<child>`. When we mark `<owner>` as the owner of `<child>`, we update `<child>`'s cache owner (https://github.com/ampproject/amphtml/pull/5898). But, `<grandchild>` is unaware of this change, because it has cached a now-out-of-date ownership.

We cannot blindly change the ownership of `<grandchild>` to `<owner>`, since it may be directly owned by `<child>`. But, we can just removed the cached value, and let the logic figure out the correct ownership on the next request.

**Comment by zhouyx** [comment]
Are there real cases that we have two layers of ownership? remove cached value and figure out ownership info every time is  correct. But If we never have this kind of use cases (two layers of ownership), I feel it can be a waste of resources.

**Comment by jridgewell** [comment]
Neither case is very common (we only have a few owner extensions). I don't think this necessary to optimize yet.

**Comment by camelburrito** [comment]
From what i understand - elements should call setOwner on other elements they intend to own. 

i don`t understand the need for grandchild to be aware of its owner's owner. That should not affect anything right? 

What is the initial cached value for the grandchild?  shouldn't the child call setOwner on the grandChild?

**Comment by jridgewell** [comment]
Ownership is implicit in `Resources`, so `<grandchild>`'s owner is `<owner>` until `<child>` decides it wants to own it.
