### ISSUE TITLE
Improve amp-ad loading experience 

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#5918]
This is a tracker issue for related work on improving default ad loading experience.

- [x] Add experiment guard to the new UX
- [x] Add default placeholder/fallback, apply/remove at right time
- [x] Create ad tag
- [x] Create new loading indicator, animate/remove loading dot at right time.
- [x] Enable a way to customize ad tag
- [ ] Customize behavior for ad in special container
- [x] support i118

**Comment by abeck000** [comment]
@edlea-g

**Comment by lannka** [comment]
> Enable a way to customize ad tag
> support i118

The ad logo can be customized (e.g. for i18n purpose) via CSS.

> Customize behavior for ad in special container

I'm not sure what this means.

Otherwise, the work is all done. We can launch it by flipping the flag if it sounds good.
@jasti

**Comment by jasti** [comment]
I'm not sure myself. 
Sounds good to me to launch this week to canary. Thanks for the quick work on this!
CC @ericlindley-g

**Comment by ericlindley-g** [comment]
Excited to see this roll out! Personally I've really been enjoying the experience through the experiment :)  We can think about how to extend this to other lazy-loaded UI (images, videos, embeds, iframes) after getting feedback from this ads case.
