### ISSUE TITLE
Pinterest amp-social-share button does not work on iOS

### ISSUE THREAD

**Issue by poscar** [ampproject/amphtml#5919]
## Short description of your issue:

The `amp-social-share` Pinterest button does not work on iOS. Tapping the button opens the Pinterest app, but we're not able to share the content.

Tapping on Pinterest buttons on other regular sites (e.g. http://www.allure.com/story/real-men-exfoliate) allows us to share content without any issues.

## How do we reproduce the issue?

Try the Pinterest share button here: https://ampbyexample.com/components/amp-social-share/ on an iOS device (we tested on Safari under iOS10.1 with the Pinterest app installed).

Notice the Pinterest app shows the following:
![slack for ios upload png](https://cloud.githubusercontent.com/assets/128726/19866883/5435bc00-9f78-11e6-8ac8-816b75ed834d.jpeg)

But it should be showing something like the following:
![slack for ios upload-1 png](https://cloud.githubusercontent.com/assets/128726/19866888/5813a17a-9f78-11e6-829c-7181f36afcbe.jpeg)

Looks like it's unable to get an image for the content and/or share it.

## What browsers are affected?

Tested under Safari on iOS 10.1. Others might be affected.

## Which AMP version is affected?

`Powered by AMP ⚡ HTML – Version 1477334765771`

**Comment by sahandnayebaziz** [comment]
Can confirm that we are seeing the same thing on pages that validate perfectly on the [Pinterest Rich Pins Validator](https://developers.pinterest.com/tools/url-debugger/), including amp page is found and amp page is valid.

**Comment by mkhatib** [comment]
I am working on a PR that adds a default `description` parameter for `pinterest` but in general the `amp-social-share` provides convenient defaults to some attributes that it can. In this case AMP cannot fill a default pinterest `media` attribute, so when using it please provide a `data-param-media="url-to-media"` to allow pinterest sharing box to pick it up.

Let me know if this still doesn't work.
