### ISSUE TITLE
Intent to implement: Relax "viewport" to only require width and minimum-scale.

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#592]
In the #481 we established that from accessibility point of view it's best to not restrict `maximum-scale` and `user-scaleable`.

We will thus only require `width=device-width` and `minimum-scale=1`. All other properties will be left up to publisher and specific viewer implementation.

We still have to require `width` and `minimum-scale` to get GPU rasterization as described here: https://www.chromium.org/developers/design-documents/chromium-graphics/how-to-get-gpu-rasterization

**Comment by cramforce** [comment]
LGTM.
Ship it.

**Comment by adactio** [comment]
:+1:

**Comment by karlgroves** [comment]
WTG!
