### ISSUE TITLE
RTL bug: amp-carousel ->type="carousel". Please Add rtl support or "warning"

### ISSUE THREAD

**Issue by Siton-Systems** [ampproject/amphtml#5929]
**WHAT:** https://ampbyexample.com/components/amp-carousel/  || type="carousel"
**RTL bug:** white space / not work well.

I fix this by override my html style in specific spot : "`.some-div{direction:ltr;}`". but for other users please fix this (or add notes in the docs).

Also in general it would be nice to get RTL direction of this component.

See codepen bug example:
<a  target="_blank" title="codepen RTL bug example of amp-carousel" href="http://codepen.io/siton/pen/pEMyWd?editors=1000">codepen RTL bug example of amp-carousel ->type="carousel"</a>

**Comment by aghassemi** [comment]
/to @camelburrito RTL support for carousel and slides.

**Comment by camelburrito** [comment]
@muxin can you look at the type="carousel"

**Comment by muxin** [comment]
@Siton-Systems Currently we only support slides displayed from left to right according to our resource loading mechanism. I will create a feature request for RTL situation. For now, I can have a temporary fix to add `direction: ltr` on all carousel by default. Does this sound good?

**Comment by muxin** [comment]
OK, maybe it's not a good idea to force set the default direction to ltr. Let me add the support for rtl directly.

**Comment by camelburrito** [comment]
@Siton-Systems thanks a lot for filing the bug! 

what @muxin means is - "we will try and work on a fix" - meanwhile you can use dir="ltr" on your carousel (by adding it manually in your HTML for now).

**Comment by cramforce** [comment]
@mkhatib for additional LTR expertise.

**Comment by Siton-Systems** [comment]
Thanks :)!

**Comment by muxin** [comment]
See https://github.com/ampproject/amphtml/issues/5950 for the same task
