### ISSUE TITLE
[amp-analytics] the "visible" and "hidden" triggers are a bit confusing

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#5934]
By looking at the name, I would think that they're the opposite counterpart to each other. Especially, they share the same `VisibilitySpec` to select an element and specify the conditions to meet.

However, the "visible" trigger fires when the **selected element** enters viewport; but the "hidden" trigger fires when user leaves the **page** (vs selected element leaves viewport).

It will be more self-explained if we rename "hidden" to "pagehidden" (or something similar).

**Comment by lannka** [comment]
Further more, seems the `continuousTimeMax` & `totalTimeMax` conditions don't apply to "visible" trigger.  While `visiblePercentageMin` & `visiblePercentageMax` conditions don't apply to "hidden" trigger. @avimehta please correct me if I have any mis-understanding here.

**Comment by rudygalfi** [comment]
Let's deal with `visible` and `hidden` first. I don't think I understand why there's confusion. It's important to understand that these two triggers pull double duty. If they are specified without `visibilitySpec` then they will simply fire when the page becomes either visible or hidden, respectively. The naming in this case seems intuitive to me. @lannka I think you might have missed that you can have just a plain `visible` trigger that behaves as you'd expect (and the opposite of `hidden`).

**Comment by lannka** [comment]
The confusion comes with the 2nd duty.

```json
        "triggers": {
          "visibilityScope": {
            "on": "visible",
            "visibilitySpec": {
              "selector": "amp-img",
              "selectionMethod": "scope",
              "visiblePercentageMin": 10,
              "visiblePercentageMax": 90,
            },
          }
        }
```
The above config will trigger as soon as `amp-img` enters viewport (visible > 10). This is not hard to understand, except that I can argue `visiblePercentageMax` is probably useless in real world.

-------------------

The config below simply changed "on: vidible" to "on:hidden". The behavior is totally out of my expectation.

```json
        "triggers": {
          "visibilityScope": {
            "on": "hidden",
            "visibilitySpec": {
              "selector": "amp-img",
              "selectionMethod": "scope",
              "visiblePercentageMin": 10,
              "visiblePercentageMax": 90,
            },
          }
        }
```
A: triggers when amp-img leaves viewport (visible < 10 || visible > 90).
B: triggers when user leaves the page.

I will expect the behavior to be A, but the answer is B.

As I mentioned above, the confusion is from 2 parts:
- Adding the VisibilitySpec to the "visible" trigger changed the firing point from "page visible" to "element visible". However, adding VisibilitySpec to the "hidden" trigger will not have this effect.
- Not all fields of VisibilitySpec make sense to both triggering mechanism, e.g. `continuousTimeMax` & `totalTimeMax` conditions don't apply to "visible" trigger.  `visiblePercentageMin` & `visiblePercentageMax` conditions don't apply to "hidden" trigger. very misleading.

------------------

**Comment by rudygalfi** [comment]
Oh, I see the problem now. With `visible` it kind of makes sense to just fire things as soon as the visibility condition is reached. With `hidden` we wanted to introduce the idea of: watch this element during the whole page lifecycle and ping if it meets a particular set of conditions. So, to summarize, when we were discussing this [here](https://github.com/ampproject/amphtml/issues/2487#issuecomment-234357726) we didn't account for the use case of: tell me when an individual element is hidden immediately.

Is there any way to retrofit this use case into the current semantics?

We [introduced `immediate`](https://github.com/ampproject/amphtml/issues/4463#issuecomment-239777255) to the `timerSpec`. I wonder if we could do a similar thing here. Or I wonder if there's something about the additional `visibilitySpec` properties that are defined that we can say: "this causes the hit to fire immediately" or "this causes the hit to fire as late as possible"

**Comment by rudygalfi** [comment]
@lannka Can you close this if you think it was addressed by visibility v2 work (and link to a more specific issue)?

**Comment by lannka** [comment]
@dvoytenko <https://github.com/dvoytenko>  was proposing a new name for
the "hidden" trigger: "unload". Because that's when it gets triggered.

Regards,

Hongfei

**Comment by lannka** [comment]
It's still not too late the do the renaming. Only a handful domains are using the "hidden" trigger. We can keep both as valid, but change the doc to "unload".

@rudygalfi @dvoytenko thoughts?

**Comment by rudygalfi** [comment]
I'd be ok with that

**Comment by lannka** [comment]
@dvoytenko has opinion on the name "unload", since it's not really a page unload (leaving the page). how about "pagehidden" then?

**Comment by dvoytenko** [comment]
@rudygalfi  @lannka I like `pagehidden` better, but I still feel like it's not ideal. I think what we really try to do using `hidden + visibilitySpec` is to report total visibility numbers. So, I think perhaps it'd be better to add a field `totals: true` in the `visibilitySpec`? I think that would clearly communicate the intent: "I'm interested in visibility, but I'd like to know the total duration". A variant of this would be, when `totals: true` is specified, to first report as soon as `visibilitySpec` has been matched and then report again on page-hidden with total values.

WDYT?

**Comment by lannka** [comment]
Given the thread is already too long, and some discussion with @dvoytenko offline, let's move further discussion to #7651
