### ISSUE TITLE
Use CLIENT_ID inside amp form as hidden input field

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#5937]
A way to implement a shopping cart would be using amp-form. We should be able to do a POST with an hidden field containing the CLIENT_ID and add a shopping cart button where the href should be built based on the CLIENT_ID. By clicking on this button, the used should be redirected to his own shopping cart.
At the moment we can't use CLIENT_ID variable substitution as a value for an hidden field inside an amp form. 

@mkhatib @cramforce @rudygalfi @sebastianbenz @jasti: adding this issue to keep track of our conversation and get updates on the progress.

**Comment by cramforce** [comment]
Discussed this with @mkhatib the other day. For `POST` submissions we can support all variable substitutions on the values.

For GET we can run the existing code (under experiment) that I built for links.

Something like this should work then

`<input type=hidden value=CLIENT_ID>`

**Comment by mkhatib** [comment]
We've another issue to track this as well #5654 - closing this in favor of the other one.

I'll be starting work on this very soon
