### ISSUE TITLE
[amp-analytics] "hidden" trigger throws exception when visiblePercentageMin is configured

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#5939]
A sample configure as shown below can reproduce the issue. Try to switch browser tab and check console errors:

```
log.js:243 Uncaught Error: Number expected: undefined(…)
```

Root cause is at this [line of code](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/visibility-impl.js#L516), where `state[MIN_VISIBLE]` can be `undefined` if the element is never visible before user leaving the tab.

```html
  <div style="height: 120vh"></div>
  <a href="https://google.com" target="_blank">
    <amp-img width="300" height="200"
        src="https://lh3.googleusercontent.com/5rcQ32ml8E5ONp9f9-Rf78IofLb9QjS5_0mqsY1zEFc=w300-h200-no">
    </amp-img>
  </a>
  <div style="height: 120vh"></div>
  <amp-analytics>
    <script type="application/json">
      {
        "transport": {"beacon": false, "xhrpost": false},
        "requests": {
          "visibility": "http://localhost:8000/?${type}&RANDOM"
        },
        "triggers": {
          "visibilityScope": {
            "on": "hidden",
            "request": "visibility",
            "visibilitySpec": {
              "selector": "amp-img",
              "selectionMethod": "scope",
              "visiblePercentageMin": 20
            },
            "vars": { "type": "visible" }
          }
        }
      }
    </script>
  </amp-analytics>
```

A simple fix will be default `MIN_VISIBLE` and `MAX_VISIBLE` to 0.
```
dev().assertNumber(state[MIN_VISIBLE] || 0);
dev().assertNumber(state[MAX_VISIBLE] || 0);
```
@avimehta let me know if it makes sense.

**Comment by lannka** [comment]
The code [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/visibility-impl.js#L476-L477) also looks suspicious to me:
```
    s[MIN_VISIBLE] = s[MIN_VISIBLE] ? Math.min(s[MIN_VISIBLE], visible) : 101;
    s[MAX_VISIBLE] = s[MAX_VISIBLE] ? Math.max(s[MAX_VISIBLE], visible) : -1;
```
why didn't we set the first time value to `visible` instead of `101` and `-1`?

**Comment by avimehta** [comment]
the value of state[MIN_VISIBLE] can be undefined or a number. Using `log().assertNumber` causes the error message but it doesn't affect actual working of the code. Actual metrics are set to `0` or correct value based on what you are measuring.

Consider the modified configuration below:

```
  <div style="height: 120vh"></div>
  <a href="https://google.com" target="_blank">
    <amp-img width="300" height="200"
        src="https://lh3.googleusercontent.com/5rcQ32ml8E5ONp9f9-Rf78IofLb9QjS5_0mqsY1zEFc=w300-h200-no">
    </amp-img>
  </a>
  <div style="height: 120vh"></div>
  <amp-analytics>
    <script type="application/json">
      {
        "transport": {"beacon": false, "xhrpost": false},
        "requests": {
          "visibility": "http://localhost:8000/?${type}&RANDOM"
        },
        "triggers": {
          "visibilityScope": {
            "on": "hidden",
            "request": "visibility",
            "visibilitySpec": {
              "selector": "amp-img",
              "selectionMethod": "scope",
              "visiblePercentageMin": 20
            },
            "vars": { "type": "visible" }
          },
          "visibilityScope2": {
            "on": "hidden",
            "request": "visibility",
            "visibilitySpec": {
              "selector": "amp-ad",
              "selectionMethod": "scope"
            },
            "vars": { "type": "visible2" }
          }

        }
      }
    </script>
  </amp-analytics>
```

Note that when visible2 is fired, min, max visible are set to 0. When visible fires, the values are set to correct value (20 and whatever the max is).

If the min was set to `0` (initial value if visible in this example), it will always remain `0`. Setting max to `0` is okay since it can always increase from there.

A simple fix would be to remove assertNumber call and instead just coerce  the value to number. The value would NaN initially but it will be set to correct value when the trigger actually fires.
