### ISSUE TITLE
Extensions service sometimes creates wrong "rtv" URLs

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#5940]
For instance, this URL is missing a minor version: "https://cdn.ampproject.org/rtv/1477334765771/v0/amp-analytics-0.1.js"

**Comment by dvoytenko** [comment]
The reason is that the `shadow-v0.js` is not bootstrapped correctly with the `AMP_CONFIG`.

/to @erwinmombay to fix/deploy.

**Comment by pbakaus** [comment]
Note this has high prio from my side, as I the CDS talk is coming up next week.

**Comment by erwinmombay** [comment]
this should get fixed in prod and canary in the next hour or so

**Comment by dvoytenko** [comment]
I can confirm. It's fixed in Canary. Subject to browser cache.

**Comment by pbakaus** [comment]
Excellent, thanks Erwin and Dima!
