### ISSUE TITLE
[amp-analytics] problem of supporting minVisiblePercentage & maxVisiblePercentage

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#5942]
We plan to move the visibility tracking to IntersectionObserver based implementation (#5697). However, because [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) only fires at a list of pre-specified thresholds, metrics like [minVisiblePercentage](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/analytics-vars.md#minvisiblepercentage) and [maxVisiblePercentage](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/analytics-vars.md#maxvisiblepercentage) will not be available.

An approximate is achievable by specifying a fine grained list of thresholds, for example from 0 to 1 with step of 0.05. Is it something we should go for or we can stop supporting this anymore.

@avimehta @rudygalfi 

/cc @jasti @cramforce

**Comment by cramforce** [comment]
Using fine grained thresholds seems OK to me.

**Comment by lannka** [comment]
> Using fine grained thresholds seems OK to me.

Great. What granularity shall we start with. I'll go with 0.05 if no objection.

**Comment by lannka** [comment]
Closing for now, as we reached a consensus.
