### ISSUE TITLE
Consider supporting <datalist> and its related attributes in inputs

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#5947]
[datalist](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) allows publishers to define a pre-defined list of items to list in an input. This needs to whitelist it in validator as well as polyfill support in non-supporting browsers - Possibly Safari and IE.

**Comment by Gregable** [comment]
This is now allowed in validator, but the bug was never closed.
