### ISSUE TITLE
Safari Desktop and iOS Devices not loading amp-ads when using Development Builds

### ISSUE THREAD

**Issue by e2corporation** [ampproject/amphtml#5948]
This issue maybe partially related to #5351. When using a development build of AMP on a non-production endpoint, **Safari** fails at the "loading..." placeholder and does not complete render.

iOS/**iPhone** devices also experience the same issue when using Safari and sometimes Chrome. The test page below points to the amp rollup on the heroku instance, the amp-ad tag is also specified. 3p/remote.html has been updated to allow the network type with draw3p().

**AMPHTML Test URL**
https://shogun-amp.herokuapp.com/examples/revcontent-theatlantic.min.html

![bs_macelc_safari_9 1](https://cloud.githubusercontent.com/assets/1742233/19904410/ce79627a-a048-11e6-9401-5620fbbd081b.jpg)

**Comment by lannka** [comment]
@e2corporation sorry for replying late. Not sure I'm still seeing the same error as you did. I saw the ad request returned 404 from revcontent.com, which did gave me forever loading.

In your screenshot, you can ignore those 404s with `Do_not_worry_about` in the URL. it's our preconnect polyfill trying to preconnect the ad server using CORS XHR.

**Comment by lannka** [comment]
Closing it for now. Feel free to reopen if you saw other types of errors.
