### ISSUE TITLE
Race condition on initial fragment navigation

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#5949]
See https://www.ampproject.org/learn/who/#analytics

- sometimes this works fine and jumps to the analytics section.
- sometimes it jumps to the wrong place.

**Comment by cramforce** [comment]
@pbakaus I looked at this and it really appears to be a Chrome issue where the scroll position is calculated too early in the page lifecycle. This is likely an issue for many pages with web components.

I wonder what we should do? Manually call `scrollIntoView()` when we know it is safe to do so?

**Comment by cramforce** [comment]
@muxin I think you can fix this as follows

- we need to get the `scrollIntoView` for initial fragment anyway, when it is coming from the viewer.
- lets factor the "scroll to fragment" code from `document-click.js` into common utility
- and then just add something like this to the viewer:

```js
Promise.all([this.getFragment(), whenFirstBuilt(this.win)).then(data => {
  const fragment = data[0];
  if (fragment) {
    scrollToFragment(fragment);
  }
});
```

I'm not sure we have something like the `whenFirstBuilt` promise yet, but we need that. CC @dvoytenko

**Comment by muxin** [comment]
We want to put the history update inside the `scrollToFragment` logic, right?

**Comment by cramforce** [comment]
On initial fragment update there is never a history update. I think it is probably better to handle that separately, but I defer to @dvoytenko

**Comment by dvoytenko** [comment]
`whenFirstBuilt` is probably ok, but why? I'm pretty sure we just need to wait for `Promise.all` of:
 1. Fragment is known
 2. Document "ready" signal
 3. `makeBodyVisible` fired. Or rather _right_ before it's fired.

**Comment by cramforce** [comment]
Waiting for `makeBodyVisible` to have fired sounds good to me.

**Comment by cramforce** [comment]
I filed https://bugs.chromium.org/p/chromium/issues/detail?id=661359 to get this fixed in Chrome

**Comment by cramforce** [comment]
This was fixed in Chrome.
