### ISSUE TITLE
Support RTL (right-to-left) for amp-carousel

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#5950]
It would be nice to allow displaying slides in rtl mode.
Brought up in https://github.com/ampproject/amphtml/issues/5929

**Comment by camelburrito** [comment]
@muxin - explore `unicode-bidi` css property and see if we can leverage something from there without having to change code.

**Comment by jridgewell** [comment]
Upgrading to p2, due to #7670.

**Comment by camelburrito** [comment]
#7670 is not just RTL support, it really is some issue with IOS safari beta 2. We can still keep this P3

**Comment by djavet** [comment]
Any idea when the RTL without autoplay in carousel will be solved and ready to be used on prod?

**Comment by doradsoft** [comment]
@sparhami thanks man!

**Comment by aghassemi** [comment]
done for carousel v2 with #21994
