### ISSUE TITLE
No items in amp-list response throws non-user error

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#5962]
See this URL
https://cdn.ampproject.org/v/s/allrecipes.com/recipe/19165/creme-brulee/amp/?amp_js_v=5

I don't understand why this happens, as we do have a `user().assert` for this. Do we accidentally remove it?

CC @lannka @dvoytenko @erwinmombay

**Comment by cramforce** [comment]
This is the `null is not an object (evaluating 'c.items')` error

**Comment by erwinmombay** [comment]
double checked and the assert is definitely there. but yeah we do a `typeof null == "object" // true` and try to access the property

**Comment by erwinmombay** [comment]
<img width="975" alt="screen shot 2016-11-01 at 6 08 48 pm" src="https://cloud.githubusercontent.com/assets/354746/19913296/95af3eb8-a05e-11e6-9db8-6ea9211add71.png">
