### ISSUE TITLE
"No request strings defined. Analytics data will not be sent from this page." should be a user error

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#5963]
This is polluting our prod logs.

**Comment by rudygalfi** [comment]
I made this a P2, but let me know if this should be bumped up, down, or closed.

**Comment by calebcordry** [comment]
was checking GFI candidates, it looks like this was already fixed [here](https://github.com/ampproject/amphtml/pull/6187/files#diff-cb0347b1135d05dae7b0c034bca78900L357). Should I close this? 

to/ @lannka 
cc/ @rudygalfi

**Comment by rudygalfi** [comment]
Thanks! Will let @lannka make the final call.

**Comment by lannka** [comment]
Yep
