### ISSUE TITLE
Amp pages and html5 games

### ISSUE THREAD

**Issue by dejandex** [ampproject/amphtml#5966]
What about html5 games and iframe and amp pages 

In amp reference i see The 600px away from the top constraint can be avoided by adding a placeholder image.

 It does not make sense to me. Html5 games is for full screen like this one 

[http://m.fishinggames.us/lets-fish2.php](url)

How to make valid html5 iframe amp page?

**Comment by aghassemi** [comment]
@dejandex a single full-screen iframe page will not benefit from the performance optimizations that AMP  provides so AMP may not be the right tool for your case. Please see _"What type of content works best using Accelerated Mobile Pages?"_ on https://www.ampproject.org/support/faqs/
