### ISSUE TITLE
Clean up CustomElement#connectedCallback

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#5980]
Re: https://github.com/ampproject/amphtml/pull/5976#discussion_r86209297

`#connectedCallback` attempts to verify the layout type of the element. However, now that we can delay the upgrade, this seems wrong. Additionally, the upgrade itself verifies the layout type. So:

- Upgrade is sync
  - upgrade verified layout type, so `#connectedCallback` is duplication
- Upgrade is async
  - `#connectedCallback` can't verify the layout to begin with (because it depends on the upgraded implementation).

**Comment by dvoytenko** [comment]
Upgrade has been rebuilt around `connectedCallback`. I believe this closes this issue. Please reopen if needed.

**Comment by jridgewell** [comment]
Still an issue, but it's low priority.
