### ISSUE TITLE
Revive amp-slides

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#5981]
It should be the same as `<amp-carousel type=slides>`. Having the type turned out to be a terrible idea.

We should then stop documenting the `type` attribute and eventually make a new version of `amp-carousel` that no longer supports it.

**Comment by camelburrito** [comment]
does this mean we would have to increment the version of the carousel? - or should we just remove slides documentation from there and move it to amp-slides?

**Comment by cramforce** [comment]
For now we'd just remove the docs. `amp-carousel-0.1` will need to keep supporting `type=slides`. Version 1.0 can drop the support.

**Comment by Gregable** [comment]
The `<amp-slides>` tag was removed from validation in October 2015. I don't see any remaining usage of it in my sampling. For reasons I cannot seem to find, we did leave in validation of the javascript extension, for example: 

```
<script async custom-element='amp-slides' src='https://cdn.ampproject.org/v0/amp-slides-0.1.js'></script>
```

There is some usage of this script tag still on the web, though it's very small.

**Comment by camelburrito** [comment]
if amp-slides is invalid amp we should just delete it? 

CC @cramforce @dvoytenko

**Comment by cramforce** [comment]
I thought the decision was to

- undocument `<amp-carousel type=slides>`
- and make `amp-slides` to what the above does

?

**Comment by dvoytenko** [comment]
Correct. I believe we need to bring `amp-slides` back and deprecate `<amp-carousel type=slides>`

**Comment by aghassemi** [comment]
It's coming back as `amp-inline-gallery` (and `amp-stream-gallery` would be the scrolling one)
