### ISSUE TITLE
amp-accordion: getSessionState_ should not assert `sessionStr`

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#5988]
Currently `getSessionState_` asserts the `sessionStr` it gets from `sessionStorage` but it is not expected to have any value in session storage for an accordion until the header is clicked. This is causing unnecessary error logging (but is not causing a bug)

**Comment by kmh287** [comment]
I believe this was fixed in #6488 

[commit](https://github.com/ampproject/amphtml/commit/9b832f8bc2a8d02416cac85f1e9ffd7f34136223)
