### ISSUE TITLE
Video: good fallback for format not supported

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#599]
I seem to regularly (though rarely) run into a case where video is defined with a format that's not supported on my phones. Usually the behavior of the video player seems insufficient to me where it just shows up blank. I'm wondering if we can improve on this.

**Comment by kevinmarks** [comment]
This is a long-standing problem with both video and audio tags, as the spec doesn't show fallback content when the file is misparsed or missing. 
If you want to apply youtube's transcoding backend to the caching part of AMP, that could be interesting.

**Comment by dvoytenko** [comment]
Unfortunately it looks like video/audio elements themselves provide very few signals in APIs to indicate that playback is impossible. If anyone has a hint - please let me know. It's easy enough to check `source` tags, but when only `src` is specified things get a bit harder.

**Comment by patternseek** [comment]
amp-video supporting the codecs parameter in `<source>` would go a long way to alleviate this.

**Comment by dvoytenko** [comment]
@patternseek This issue is specifically for when video only has `src` attribute.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
