### ISSUE TITLE
Can we build an AMP compliant web application using custom components?

### ISSUE THREAD

**Issue by nelsonic** [ampproject/amphtml#601]
Hi @cramforce,
We :heart: the idea of faster loading pages on :iphone: 
We've read through all the spec for AMP and *understood* that no javascript or form/input elements are allowed in an AMP. 
So my question is, how can I build a custom component to add a comment form to a page with an AMP-compliant news article?

The spec for html components: 
https://github.com/ampproject/amphtml/blob/master/spec/amp-html-components.md
has not clarified how to write a 3rd party component...
We're happy to make all our code open source, we just want to know if this functionality is going to be *possible*...

Thanks!

**Comment by cramforce** [comment]
See https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md for contribution guidelines. This may be incomplete but it is a start.

CC @jmadler

**Comment by nelsonic** [comment]
Thanks @cramforce :+1:
