### ISSUE TITLE
Forbid multiple versions of same extension

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#6010]
Now that we have `<amp-sticky-ad>` v1, we need to forbid an author including both `v1` and `v0.1` at the same time.

**Comment by Gregable** [comment]
Also tracking at b/32628127

**Comment by Gregable** [comment]
This has been fixed, but was never closed. There are still some things to do around emitting a warning if 0.1 is present that suggests you should upgrade, but the specific bug of forbidding both versions is complete and live.
