### ISSUE TITLE
Consolidate and clarify templating documentation

### ISSUE THREAD

**Issue by dandv** [ampproject/amphtml#6018]
Thanks for the previous work on this.

Two more points:

1. Templates are often referred to as "extended templates". This may create the impression that there's a regular (or built-in) kind of templates as well. Should we clarify this terminology? What do "extended" templates actually mean? That the templating system is designed to run arbitrary templating languages (with Mustache being the only one currently implemented)? Can we drop "extended" or do we need to keep it to parallel ["extended components"](https://github.com/ampproject/amphtml/blob/master/extensions/README.md), which do have a built-in counterpart?

2. The [templates spec](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-templates.md) is actually less detailed than the [templates section in the HTML format spec](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#extended-templates). I was [improving the templates documentation](https://github.com/ampproject/amphtml/pull/6017) when I realized this.

**Comment by ericlindley-g** [comment]
@dandv, marking as "Current", on the assumption that you're working on this now, but please correct me if I'm wrong!

**Comment by ericlindley-g** [comment]
cc/ @bpaduch

**Comment by dandv** [comment]
@ericlindley-g, sorry, wasn't working on this and won't have cycles this week :(

**Comment by ericlindley-g** [comment]
No worries—I flagged it more as a way to convey information than to push a deadline. I'll just put to "backlog" for now
