### ISSUE TITLE
Scrolling through search-in-page results broken in mobile Safari

### ISSUE THREAD

**Issue by joshforman** [ampproject/amphtml#6022]
## Short description of your issue:

When opening an AMP page in mobile Safari and searching "On This Page", cycling through multiple search hits does not scroll the page to the search result.

## How do we reproduce the issue?

* On iOS 10.1.1 (I also found this issue in the most recent iOS version before 10.1.1 as well, but that's all I've tested)
* Using an iPhone 7
* Load https://www.google.com/amp/s/amp.cnn.com/money/2016/11/03/media/baseless-fox-news-indictment-report/index.html?client=safari (originally found by searching Google for "media refutes cnn" and clicking the CNN Money AMP result)
* In the URL bar, type "and" (without quotes) and scroll down to "On This Page (8 matches)", select "Find 'and'"
* Click the downward facing carat that cycles through search results.  Note that as you advance to results further down the page, the viewport does not scroll to the search result's location.  This does not happen on non-AMP pages.

Note that this repros for me with any search that appears off-screen on any domain I've tried.

## What browsers are affected?

I have only tested this on Mobile Safari

## Which AMP version is affected?

Unknown

**Comment by cramforce** [comment]
Lets make sure to file a webkit bug.

Its not completely broken. The first one scrolls correctly and I'm not even sure it never works on the second result. Overall the feature seems a fit wonky in Safari.

**Comment by dvoytenko** [comment]
I have an issue and a WebKit bug filed here: #5750. I'll close thus bug as a dupe.
