### ISSUE TITLE
AMP-analytics: Passing useragent is truncated due to getNameArgs method

### ISSUE THREAD

**Issue by gtrufitt** [ampproject/amphtml#6027]
If I pass a string value containing `()` to the vars property in the `<amp-analytics>` component, the string is truncated due to the regex in the `getNameArgs_` string method.

## How do we reproduce the issue?

Passing the user agent from the request headers, renders as so:

    "vars": {
         "userAgentHeader": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
    }

but will be passed in the analytics requests as `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4)`

This is because in [`encodeVars_`](https://github.com/ampproject/amphtml/blob/553492cf2c54e9c974ddea12b3c524a03b68de0b/extensions/amp-analytics/0.1/amp-analytics.js#L545) the raw value is passed to [`getNameArgs_`](https://github.com/ampproject/amphtml/blob/553492cf2c54e9c974ddea12b3c524a03b68de0b/extensions/amp-analytics/0.1/amp-analytics.js#L521) whose regex (`([^(]*)(\([^)]*\))?`) matches (`Mozilla/5.0` as first match and `(Macintosh; Intel Mac OS X 10_10_4)` as second)

Here is a [JSBin](http://output.jsbin.com/gucomexaro) - take a look at the request.

### Can't I encode it serverside?

The data needs to match on AMP and on the main site - so even though I could use the Java URLEncoder (UTF-8), which would encode the brackets, the equivalent JS encodeURIComponent() *does not encode brackets* therefore I would need to convert back. So the regex would still match on the equivalent encoding.

Using URLEncoder has this as the query param in the request (double encoding from the JavaURLEncoder *&* encodeURIComponent in JS):

`Mozilla%252F5.0%2B%2528Macintosh%253B%2BIntel%2BMac%2BOS%2BX%2B10_10_4%2529%2BAppleWebKit%252F537.36%2B%2528KHTML%252C%2Blike%2BGecko%2529%2BChrome%252F53.0.2785.116%2BSafari%252F537.36`

compared to this in a normal GA request:

`Mozilla%2F5.0%20(Macintosh%3B%20Intel%20Mac%20OS%20X%2010_10_4)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F53.0.2785.116%20Safari%2F537.36`

## What browsers are affected?

All browsers

## Which AMP version is affected?

Tested in AMP Version 1477334765771.

BTW [X-posting this from SO](http://stackoverflow.com/questions/40401729/amp-analytics-passing-useragent-is-truncated-due-to-getnameargs-method). I'll post an answer back there...

**Comment by jasti** [comment]
to @rudygalfi for analytics

**Comment by erwinmombay** [comment]
ping @avimehta

**Comment by jridgewell** [comment]
This is a pretty easy fix: `key.match(/([^(\s]*)(\([^)]*\))?/)` (no whitespace before the `(`).

**Comment by avimehta** [comment]
still looking for right regex here. Suggestion from https://github.com/ampproject/amphtml/issues/6027#issuecomment-261363525 doesn't work because it will truncate the value at first space. So the example value will just be `Mozilla/5.0%20` if the suggested regex is used.

**Comment by gtrufitt** [comment]
@avimehta

How about something like:

```javascript
['abc', 'clientId()', 'clientId(abc)', 'client id', 'client id()', 'client id (sjsj)'].forEach(val => { 
     let match = val.match(/^[^\s]+(\(.*\))|*); 
     console.log("VAR: ", match[1] && match[0].split('(')[0] || match[0],", ARGS: ", match[1]) 
} )
```

The `match[1] && match[0].split('(')[0] || match[0]` bit is a bit horrible, so I guess you could work out match group for everything before but maybe using a split is clearer. ❓ 

Tested:

```
VAR:  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36 , ARGS:  undefined
VAR:  abc , ARGS:  undefined
VAR:  clientId , ARGS:  ()
VAR:  clientId , ARGS:  (abc)
VAR:  client id , ARGS:  undefined
VAR:  client id() , ARGS:  undefined
VAR:  client id (sjsj) , ARGS:  undefined
```

**Comment by jridgewell** [comment]
> `VAR:  client id() , ARGS:  undefined`

Does that mean having a space precludes a key having any functions? 

```js
['abc', 'clientId()', 'clientId(abc)', 'client id', 'client id()', 'client id (sjsj)'].forEach(val => {
  let match = val.match(/^(?:((?:(?! ).)*)(\([^)]*\))$|.+)/);
  console.log("VAR: ", match[1] || match[0],", ARGS: ", match[2]);
});
```

```
VAR:  abc , ARGS:  undefined
VAR:  clientId , ARGS:  ()
VAR:  clientId , ARGS:  (abc)
VAR:  client id , ARGS:  undefined
VAR:  client id() , ARGS:  undefined
VAR:  client id (sjsj) , ARGS:  undefined
```

Playground: https://regex101.com/r/PSMIve/2

**Comment by avimehta** [comment]
> > VAR: client id() , ARGS: undefined
> 
> Does that mean having a space precludes a key having any functions?

at least so far. `url-replacements` uses `_` as separator and `amp-analytics` uses camelCase with no separators. I am okay with making this a rule since we don't break existing stuff and don't lose much freedom.

**Comment by jridgewell** [comment]
> but the regexp part needs deeper understanding of negative lookaheads

Hm? Are you talking about the repeated `?:` with a `?!`?

**Comment by jridgewell** [comment]
Lol, forgot to simplify it from my original (I was allowing the `id()` function in `client id()`). It should be:

```js
const regex = /^(?:([^ ]*)(\([^)]*\))|.+)$/;
['abc', 'clientId()', 'clientId(abc)', 'client id', 'client id()', 'client id (sjsj)'].forEach(val => {
  let match = val.match(regex);
  console.log("VAR: ", match[1] || match[0],", ARGS: ", match[2]);
});
```

**Comment by avimehta** [comment]
looks better. Will use this and update my PR. (need to add these test cases...)

**Comment by gtrufitt** [comment]
Hi there, how are we looking on this? Is it a part of #5621?

**Comment by jridgewell** [comment]
Yup, this is'll land with #5621.

**Comment by gtrufitt** [comment]
Super, thanks @jridgewell

**Comment by avimehta** [comment]
This should go out with next release...

**Comment by jridgewell** [comment]
Now landing as #6566.
