### ISSUE TITLE
Broken link resource

### ISSUE THREAD

**Issue by kbnaik** [ampproject/amphtml#6029]
## Short description of your issue:

Link for Ad Network documentation at this page is broken: https://github.com/ampproject/amphtml/blob/master/ads/google/adsense.md.

## How do we reproduce the issue?

1. Go to https://github.com/ampproject/amphtml/blob/master/ads/google/adsense.md
2. Click on hyperlinked text "ad network documentation"
3. Redirects to a broken AdSense help center page

## What browsers are affected?

Browser independent 

## Which AMP version is affected?

N/A

**Comment by jasti** [comment]
Updating with https://github.com/ampproject/amphtml/pull/6049
