### ISSUE TITLE
How do new implementations get added to https://www.ampproject.org ?

### ISSUE THREAD

**Issue by kevinmarks** [ampproject/amphtml#603]
Withknown shipped AMP support today in both the open source:

http://stream.withknown.com/2015/self-hosted-known-085-has-left-the-building---with-better

and hosted versions of their sites:

http://known.kevinmarks.com/2015/the-web-succeeded-because-its-open-its-easy-its-agnostic?_t=amp

How do they get added to the partners list on ampproject.org ?

**Comment by erwinmombay** [comment]
@jmadler

**Comment by cramforce** [comment]
By filling out https://www.ampproject.org/contact/

I don't think getting on that list should be something that everyone has to do. That process will likely not scale very well.

On the other hand, I think it'd be nice to have some kind of wiki page that has a more comprehensive list of AMP supporting technologies.
