### ISSUE TITLE
Change the IntersectionObserver polyfill to only fire when crossing threshold boundaries

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#6030]
The current `intersection-observer.js` fires on scroll events (rate limited to 10/s). 
The native InOb fires only when the intersection ratio get across of specified threshold (can be a list of thresholds).

The polyfill is right now used for [ad viewability tracking](https://github.com/ampproject/amphtml/blob/master/ads/README.md#ad-viewability). As you can see, it currently works without providing a threshold, because it fires on every scroll events. For backward compatibility, once we moved to threshold based triggering, we can by default use a fine grained list of thresholds like `[0, 0.05, 0.1, ..., 0.95, 1]` to approximate the same behavior.

Benefit:
- less postmessages to ads iframe
- this is a prerequisite of #5603
- the new IntersectionObserver polyfill can be reused in #5697
 
@cramforce @jridgewell thoughts?

/cc @zhouyx

**Comment by cramforce** [comment]
We need to make it somewhat compatible with how ads use it today.

**Comment by lannka** [comment]
Yep, that's why I proposed a default threshold:  `[0, 0.05, 0.1, ..., 0.95, 1]`. Sounds good?

**Comment by cramforce** [comment]
Yeah

**Comment by lannka** [comment]
Talked with @zhouyx , we plan to do:

- [ ] Create a InOb polyfill that fires at threshold.
- [ ] Re-implement the current API based on the above polyfill.
