### ISSUE TITLE
Intent to implement: URL rewrite protocol as a service workers fallback

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#6040]
AMP+PWA Shell pattern works like this:
 1. A “leaf” AMP document is opened.
 2. It installs a service worker, which installs a PWA shell (single-page web app).
 3. Navigating to a “in-shell” URL on the same site, such as a sibling AMP document, opens the installed PWA shell.
 4. The shell performs routing to show the target resource. E.g. it can open the target AMP document.
 5. All subsequent "in-shell" navigations are intercepted by the shell and implemented via its router.

[Sample implementation/Demo](https://github.com/ampproject/amp-publisher-sample/tree/master/amp-pwa)

The problem with this approach is that this aspect of service workers is virtually impossible to polyfill. The goal of this spec is to provide a way to support Shell pattern without service workers installed.

## Protocol
This approach relies on URL-link rewrite and directs user to navigate to the “shell” URLs instead of “leaf” AMP.

It works roughly like this:
 1. The document provides a configuration that explains how to navigate within the shell.
 2. AMP Runtime tries to install the service worker.
 3. If service worker is not installed (not installable), as a fallback AMP Runtime will preload the shell page via a hidden iframe.
 4. AMP Runtime will intercept the “in-shell” navigations (which will often be AMP-to-AMP navigations) and if the service worker is not running, rewrite the navigation URL to proceed to the “shell”-based URL.
 5. The shell will startup and run the requested navigation via its router. Typically the shell will immediately execute `history.replaceState(href)`.

## Configuration
The proposed configuration is:
```
<amp-install-serviceworker layout="nodisplay"
      src="https://www.your-domain.com/serviceworker.js"
      data-no-service-worker-fallback-url-match=".*\.amp.html"
      data-no-service-worker-fallback-shell-url="https://pub.com/shell">
</amp-install-serviceworker>
```

Here:
 1. `data-no-service-worker-fallback-shell-url` specifies the link for AMP+PWA shell. It's required to be on the source origin as the AMP document.
 2. `data-no-service-worker-fallback-url-match` regular expression describes how to match “in-shell” links vs non-in-shell links.

## URL rewrite
When `data-no-service-worker-fallback-*` attributes specified AMP Runtime will intercept navigations. If the URL matches the `data-fallback-url-match` regular expression, the URL is rewritten as following:
```
https://pub.com/shell#href={encodeURIComponent(target.href)}
```

Thus, the hash navigation is performed. There are few important reasons why this is a good idea:
 1. `https://pub.com/shell` request will hit cache as defined by “Shell Preload” section.
 2. Hash navigation is more similar with `AMP.attachShadowDoc` API. Assembling the shell+AMP payload server-side is complicated and we are better off focusing on delivering “shell” as fast as possible as described in (1).
 3. We can continue using the same URL namespace for both canonical and shell links. The shell can immediately run `history.replaceState($href)` to ensure a good top-level URL.

## Shell Preload
We want to show shell as quickly as possible and let it fetch AMP document. Since it’s very unlikely that a non-service-worker browser would support `link preload`, we are best served by preloading the shell document via a hidden iframe.
```
<iframe src="https://pub.com/shell#preload" hidden></iframe>
```
Here:
 - `hidden` to ensure that it’s not visible.
 - We may also employ some form of `sandbox` to ensure that the shell doesn’t do anything we don’t want it to do.

**Comment by rudygalfi** [comment]
cc @pbakaus

**Comment by cramforce** [comment]
I think it would be good to clarify that we already have `data-iframe-src` on `amp-install-serviceworker`. Given that `data-no-service-worker-fallback-url-rewrite` is probably better than `data-fallback-url-rewrite`

And instead of `-rewrite` I'd say 'shell-url'.

**Comment by dvoytenko** [comment]
@cramforce cool. I change to:
```
      data-no-service-worker-fallback-url-match=".*\.amp.html"
      data-no-service-worker-fallback-shell-url="https://pub.com/shell"
```

Works?

**Comment by pbakaus** [comment]
WFM.

Just an idea, we could also reuse our existing fallback system in some way (instead of attributes on the tag itself). But it'd be a little awkward because we'd need to create a new tag to add the fallback attribute (and some more attribs) to, or stick them on a div.

**Comment by cramforce** [comment]
@pbakaus Yeah, the `fallback` child has a very specific meaning in AMP that is controlled by the framework rather than the specific element (although it can take over)

**Comment by cramforce** [comment]
![LGTM](https://camo.githubusercontent.com/c13eeb81b1485ccc0d2b248f19360c7ba2419167/687474703a2f2f6a756e6b796172642e64616d6f776d6f772e636f6d2f353633)
