### ISSUE TITLE
Validation error when boilercode is indented

### ISSUE THREAD

**Issue by imak8414** [ampproject/amphtml#6052]
Hi,
I'm new to AMP and trying hands on the code. 

I added the boilercode snippet in my AMP HTML file, but when i indent the code into several lines to improve code readability (as its way to lengthy to read on a single line), the validation fails. 

This is the error i get:
The mandatory text (CDATA) inside tag 'head > style[amp-boilerplate]' is missing or incorrect.

Please suggest if i'm doing something wrong with following code:

```
      <style amp-boilerplate>
      body{
        -webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;
        -moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;
        -ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;
        animation:-amp-start 8s steps(1,end) 0s 1 normal both}
        @-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}
        @-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}
        @-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}
        @-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}
        @keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}
      </style>
      <noscript>
        <style amp-boilerplate>
          body{
            -webkit-animation:none;
            -moz-animation:none;
            -ms-animation:none;animation:none}
        </style>

```

Thanks
Adnan

**Comment by aghassemi** [comment]
@imak8414 Thanks for filing. Currently there are limitations on how much the boilerplate code can be mutated, please see https://github.com/ampproject/amphtml/blob/master/spec/amp-boilerplate.md talking about this issue.
