### ISSUE TITLE
Implement logging statements for use with GA Debug Chrome plugin.

### ISSUE THREAD

**Issue by commadelimited** [ampproject/amphtml#6055]
As a user of the GA Debug plugin, being able to see events being logged to the browser console is extremely helpful in determining if an event is being fired, and what it's payload is.

It appears that the amp-analytics version of GA does not implement these logging statements. This makes debugging very difficult.

Please see discussions from the Slack group here:
https://amphtml.slack.com/archives/general/p1478289995001340

and here:
https://amphtml.slack.com/archives/general/p1478528686001376

**Comment by jasti** [comment]
CC @rudygalfi for Analytics

**Comment by avimehta** [comment]
@commadelimited vendor specific debug integrations might be a little difficult to implement (and unmanageable). Would the [validation server ](https://developers.google.com/analytics/devguides/collection/protocol/v1/validating-hits) work for you? it gives some general hit validation related details. 

I'll keep this issue open to explore possible debugging features in experimental features.

**Comment by commadelimited** [comment]
@avimehta Do you see the approach for amp-analytics to be different than the approach for normal GA? If it's something as simple as a log statement that the GA Debug plugin picks up and displays, then why would there be an issue with vendor integration?

At Eventbrite we have QA machines which can talk to GA directly. I'm about 90% sure this code is correct. I'll simply use a testing account ID and push code to QA for testing.

**Comment by avimehta** [comment]
@commadelimited The way debugger works currently is by intercepting requests to ga.js and analytics.js and replacing those requests with _debug.js version. the _debug versions have the log statements while the vanilla version doesn't. AMP doesn't have debug and vanilla versions of the scripts but they do have a dev build. Maybe we can use that. Another missing piece for now is that ga.js and analytics.js understand what a hit means very intimately. amp-analytics is vendor agnostic and hence doesn't understand much for now. We'll need to add all that logic to amp-analytics.

/cc @bsbaker

**Comment by lannka** [comment]
That sounds a request to individual vendors. AMP would have no mean to create and maintain a browser plugin for GoogleAnalytics.
