### ISSUE TITLE
Scraping of AMP Cache

### ISSUE THREAD

**Issue by William-Harvey** [ampproject/amphtml#6056]
Hi AMP team,

Currently scrapers are able to reconstruct URLs to obtain the AMP cache of a webpage. There are many sites such as Coupons/Voucher sites that have a daily battle preventing scrapers from stealing their hard got coupon codes.

Google search offers a way to stop caching for its regular search with the page still indexed. 

Is there a way to stop scrapers from accessing AMP cached pages directly or is this something that's in the pipeline? Coupons is one sector but as we all know there are many other sectors that fight of scrapers daily.

Many thanks
William

**Comment by cramforce** [comment]
Since AMP is explicitly a distribution format, I don't think that there is much that can be done to support a use case that tries to obfuscate them.

One thing you could look at is to use a feature like `amp-list` to pull in the codes at runtime.

**Comment by William-Harvey** [comment]
So am I right in saying amp-list can be held on our server/cdn, i.e https://www.ourwebsite.com/coupon-list-12345.html?

If that's correct then is there a way to stipulate who can view our coupon html URL above? For example is there a list of AMP cache domains (*.Google.com etc) we can ping to verify before allowing access to the coupon content?

Let me know if I'm not making myself clear :)

**Comment by cramforce** [comment]
Yep, you can ping your own server. It is basically an Ajax request. You can authorize based on general environment info.

**Comment by jridgewell** [comment]
I think this one's solved, we can reopen if not.
