### ISSUE TITLE
[amp-ad] Uncaught Error: Unknown attribute for medianet: ampSlotIndex

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#6063]
This error occurs in the current canary for `amp-ad` of some specific ad networks (e.g., a9). It's introduced in #5837.

This error is harmless though, it will not affect ad rendering.

**Comment by lannka** [comment]
@glevitzky thinking twice, I think we probably should not introduce `ampSlotIndex` as a data attribute. Instead, we can pass it directly via `opt_context` [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad/0.1/amp-ad-3p-impl.js#L221).

**Comment by glevitzky** [comment]
Using opt_context was my initial hope. However, I don't think it'll be that simple. The ad slot index needs to be known as soon as the amp-ad element is created, which happens in amp-ad.js. The only way of carrying that information forward from amp-ad.js, that I can see, is by adding it as a data attribute, or polluting the global namespace. An alternative that would allow us to keep the data-amp-slot-index attribute might be to alter validateData in 3p.js to always consider "data-amp-slot-index" as a valid attribute.

**Comment by lannka** [comment]
i see. how about change it to `slot-index`, to not mess up with custom data attribute.

**Comment by glevitzky** [comment]
Change "data-amp-slot-index" to "data-slot-index" you mean? Or just "slot-index"?

**Comment by jridgewell** [comment]
>  The ad slot index needs to be known as soon as the amp-ad element is created, which happens in amp-ad.js. The only way of carrying that information forward from amp-ad.js, that I can see, is by adding it as a data attribute, or polluting the global namespace.

Isn't this the reason we created `context`?

**Comment by glevitzky** [comment]
@jridgewell I may be a little out of the loop here, what do you mean by `context`?

**Comment by jridgewell** [comment]
The `opt_context` @lannka linked to. We created it to specifically [get rid](https://github.com/ampproject/amphtml/issues/4912) of the `ampCid` attribute.

**Comment by oude3c** [comment]
[Price & details for tv box.---Dragonworth..pdf](https://github.com/ampproject/amphtml/files/576900/Price.details.for.tv.box.---Dragonworth.pdf)
[AmazonAdvertiseYourAppCaseStudyTwimler._V311133034_.pdf](https://github.com/ampproject/amphtml/files/576902/AmazonAdvertiseYourAppCaseStudyTwimler._V311133034_.pdf)
[AT&T M2X_ Develop - API Docs_ Device.pdf](https://github.com/ampproject/amphtml/files/576903/AT.T.M2X_.Develop.-.API.Docs_.Device.pdf)






[SEOquake analytics.pdf](https://github.com/ampproject/amphtml/files/576906/SEOquake.analytics.pdf)
[ama.docx](https://github.com/ampproject/amphtml/files/576908/ama.docx)

**Comment by glevitzky** [comment]
Okay. For that to work, I'll need to add the slot index as an instance variable to both AmpA4A and AmpAd3pImple, then set the variable before returning whichever instance in AmpAd. If that sounds reasonable to you, then I will have a PR out shortly (or early tomorrow morning at the worst).

**Comment by lannka** [comment]
that sounds good too. avoid passing data via attribute is a goal.

**Comment by oude3c** [comment]
[ama.docx](https://github.com/ampproject/amphtml/files/576928/ama.docx)



[SEOquake analytics.pdf](https://github.com/ampproject/amphtml/files/576930/SEOquake.analytics.pdf)
[proposal-lao-lgr-20oct16-en.pdf](https://github.com/ampproject/amphtml/files/576931/proposal-lao-lgr-20oct16-en.pdf)
[AmazonAdvertiseYourAppCaseStudyTwimler._V311133034_.pdf](https://github.com/ampproject/amphtml/files/576934/AmazonAdvertiseYourAppCaseStudyTwimler._V311133034_.pdf)
[AT&T M2X_ Develop - API Docs_ Device.pdf](https://github.com/ampproject/amphtml/files/576935/AT.T.M2X_.Develop.-.API.Docs_.Device.pdf)

**Comment by glevitzky** [comment]
On second thought, the simplest fix might be to keep the data attribute, but only add it if the type of the ad is "doubleclick" or "adsense", or if we're in the 3p case. Would this be an acceptable solution?

**Comment by glevitzky** [comment]
After further consideration, I remember now why we didn't originally go with the solution I proposed here. We need the slot index inside the AmpA4A subclass constructor, which would mean we would have to pass the index in as a constructor argument. This would require that other ad networks change their constructors' signatures, which is obviously undesirable. The cleanest approach I think is just to modify the validateData function to allow data-amp-slot-index, or whatever we decide to call it.
