### ISSUE TITLE
AMP documents in viewers sometimes load with no fragment

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#6070]
This is currently under investigation.

**Comment by muxin** [comment]
I believe we remove the fragment when amp document is embedded in viewer. What's the problem here? You mean the search viewer doesn't set the fragment correctly sometimes?

**Comment by cramforce** [comment]
@muxin we don't know. Here is what we know

- when the viewer loads there is no fragment on the URL
- we remove the fragment
- the referrer is Google Search
- their code is super simple and cannot lead to not having a fragment

One explanation would be a type of broken iframe restore after an out of memory exception of the browser.

**Comment by muxin** [comment]
I guess we should not use `window.history.replaceState` if amp is **embedded** because it will interrupt the global history.

**Comment by cramforce** [comment]
@muxin That is unrelated to this, but why would it do that?

**Comment by muxin** [comment]
My mistake, `window.history.replaceState` will only take effect on the iframe window, so it's unrelated.

**Comment by jridgewell** [comment]
We don't know the user agent?

**Comment by cramforce** [comment]
Wide range of UAs. Seems not UA dependent.

**Comment by adelinamart** [comment]
Is there anything else to be done here? Thanks
