### ISSUE TITLE
position: sticky

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#6073]
`position: sticky` is shipping in Chrome and is in Safari already.

Do we need to do anything in particular to support it in AMP? Can we support it well given Safari's issues?

**Comment by mister-ben** [comment]
Any thoughts around using `position: sticky`? It's appealing to use this for video players, to keep the video in view while the article is scrolled. An issue with simply applying `position: sticky` to a 16:9 full width player is while it works nicely in portrait orientation, it will cover the page in landscape  -- if a `:sticky` pseudoclass existed (it doesn't) I could use that to resize a "stuck" component. Are you considering adding some more complex support for sticky positioning as a layout option?

**Comment by cramforce** [comment]
Pinging @dvoytenko again.

**Comment by dvoytenko** [comment]
Duplicate issue is in https://bugs.chromium.org/p/chromium/issues/detail?id=687317

Working on this. `sticky` is not fully yet supported.
