### ISSUE TITLE
Google search not showing my AMPed articles

### ISSUE THREAD

**Issue by karltud123** [ampproject/amphtml#6075]
I have prepared my articles to have AMP ready but it is not showing on the google search?

I am sure there are no errors on the AMP page.
The normal article contains the amphtml meta tag.

Thank you and have a nice day.
Sample article:
http://news.asiaone.com/news/asia/china-moves-bar-hong-kong-activists-fears-grow-over-intervention

AMPed article:
http://news.asiaone.com/news/asia/china-moves-bar-hong-kong-activists-fears-grow-over-intervention?amp

**Comment by creativekimmi** [comment]
Hi karltud123,

Have you tried running Search Console AMP test tool?

The AMPed article appears to have couple of errors making them invalid AMP page.

Here is the Test result link:
https://search.google.com/search-console/amp?id=1-fGsNNRPJtxjZO7FYjXyg

Also, google web master forum might be a good place to ask google search related issues~

I hope this helps!

**Comment by aghassemi** [comment]
@karltud123 The AMP page you referenced does not pass validation. The offending error is trying to use "private" AMP Css claases in your Css namely ` .-amp-slides-container`. Also there is a `<script>` tag in your AMP document which is also not valid. (If you didn't add that script tag manually, it might have been injected by your web server, but regardless it is making your page invalid)

You can also use https://validator.ampproject.org/ to check the validation errors.

**Comment by karltud123** [comment]
Hi,

Sorry was out of network for a while. Thank you for you quick feedback.

Rgds,
Karl
