### ISSUE TITLE
Support JobPosting as a structured data type

### ISSUE THREAD

**Issue by jonnywyatt** [ampproject/amphtml#6077]
We have valid JobPosting LD+JSON structured data in our AMP pages, however we still get Info advisories in Google Search Console, and our AMP pages aren't surfaced in Google searches.

We noticed that jobs eg. JobPosting, aren't listed in the [AMP data types docs](https://developers.google.com/search/docs/data-types/data-type-selector). Is JobPosting supported? If not, can you confirm when it will be?

**Comment by ericlindley-g** [comment]
As @cramforce mentioned in a recent amphtml-discuss@googlegroups.com thread, the AMP component library isn't opinionated about structured data, and the presence or absence of LD+JSON structured data shouldn't have any effect on AMP validation for your pages.

A good forum for questions related to AMP in Google Search is [this one](https://goo.gl/utQ1KZ)

Closing this bug for now, on the assumption that the SD markup is not interfering with validation, but please feel free to re-open if it is.

**Comment by jonnywyatt** [comment]
Thanks have posted to the Google Search forum.
