### ISSUE TITLE
Does JS-injected <link rel=amphtml> trigger AMP document discovery?

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amphtml#6080]
https://www.ampproject.org/docs/reference/spec#amp-document-discovery explains that AMP documents are linked with their associated canonicals via the `<link rel="amphtml">` tag.

Can JS be used to dynamically inject this code? i.e. via something like:

```js
const e = document.createElement("link");
e.href = 'http://example.com/amp/something';
e.rel = 'amphtml';
document.head.appendChild(e);
```

(I assume the answer is no, but it might be worthwhile making it clear in the docs.)

**Comment by cramforce** [comment]
This depends entirely on the crawler. For some the answer will be that it
works and for some the answer will be that it doesn't work.

**Comment by jridgewell** [comment]
Should we clarify this?

**Comment by ithinkihaveacat** [comment]
Not holding @cramforce to this but I just discovered a previous related comment: "[Lets just decide that JS injection is not OK](https://github.com/ampproject/amphtml/issues/498#issuecomment-156228793)." (Nov 2015)

(And yes, I think some sort of clarification (even if it's "crawler-dependent but might work") would be useful.)

**Comment by cramforce** [comment]
@ithinkihaveacat Could you send a PR?

**Comment by ericlindley-g** [comment]
@ithinkihaveacat I think I can close this with the PR merged, but please reopen if there's outstanding work. Thanks!
