### ISSUE TITLE
Live List Embedded Component Scripts Not Loading

### ISSUE THREAD

**Issue by BenChirlin** [ampproject/amphtml#6088]
## Short description of your issue:

In an `amp-live-list` component, if an update poll returns an item with an AMP embed component (i.e. `amp-twitter` or `amp-instagram`) the component won't work correctly because the associated script is missing.

I might be missing something but I can't find any evidence of a way for the `amp-live-list` to be aware of new components coming in from update poll requests to then enqueue the requisite script. If this is the intended behavior let me know, the quick fix would simply be to include any component scripts that might be included in the live list though that seems to go against the AMP design pattern to me.

## How do we reproduce the issue?

1. Create an `amp-live-list` element
2. Add an item to it that contains an embed like an `amp-twitter` element
3. Observe if the embed renders correctly

## What browsers are affected?

All browsers as the component scripts are vital across all platforms and browsers.

## Which AMP version is affected?

I'm guessing this was always broken as the `amp-live-list` component is so new. I'm on `https://cdn.ampproject.org/v0.js`. Thanks!

**Comment by jridgewell** [comment]
How do we want to handle this?

**Comment by BenChirlin** [comment]
Would enqueuing the scripts dynamically, before the new list elements are appended, work?

**Comment by jridgewell** [comment]
We definitely can, but I'm more asking if we should.

**Comment by erwinmombay** [comment]
so we did have some discussion some time back that we would insert it but yeah i don't know if we should since this is also caught by the validator.

**Comment by cramforce** [comment]
I agree that it would be very nice to handle this. The Cache could just return all extensions with each delta. Registering would be no problem at all.

This will, however, take a while to implement. @BenChirlin I think for now the only option is unfortunately to include all possible extensions up front (and I feel ashamed about suggesting that :)

**Comment by BenChirlin** [comment]
@cramforce ok. For now I'll just include the component scripts manually (I think we only need two so it shouldn't be too bad). I'll keep an eye out for this enhancement.

**Comment by ericlindley-g** [comment]
Closing this issue (thanks for filing!) and tracking the feature that should solve this here: https://github.com/ampproject/amphtml/issues/7231
