### ISSUE TITLE
Forbid `map` static side-effect calls

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#6089]
Re: https://github.com/ampproject/amphtml/pull/5880#r86422794

These calls will not be DCE'd. The fix is to rewrite any static calls into runtime calls, initing them when needed. Then remove the linked special case.

**Comment by cvializ** [comment]
If I understand correctly, this task is to rewrite existing statements of the form...

[`3p/3p.js`](https://github.com/cvializ/amphtml/blob/master/3p/3p.js#L39)
```js
export const registrations = map();
```
in favor of...
```js
let registrations;
export function getMyMap() {
  return registrations || registrations = map();
}
```
and then add a build check to forbid the static form.

**Comment by cvializ** [comment]
If I understand correctly, this task will forbid and replace statements of the form...

```js
export const registrations = map();
```

in favor of...
```js
let registrations;
export function getRegistrations() {
  return registrations || registrations = map();
}
```
and add a build-time check to enforce it.

The linked special case is no longer available, or I am just having trouble seeing it. @jridgewell / (@cramforce ?) is my understanding correct, or is something missing?

**Comment by cvializ** [comment]
Oh I see, the special case is the boolean expression below the comment in [build-system/eslint-rules/no-export-side-effect.js:29](https://github.com/ampproject/amphtml/blob/d23c4fb/build-system/eslint-rules/no-export-side-effect.js#L29)

**Comment by jridgewell** [comment]
That's exactly it. The build-time checks are already in place, we just need to remove the exception for `map`.

Or, we can figure out why Closure Compiler doesn't respect the [`@nosideeffects`](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#nosideeffects-modifies-thisarguments) annotation.

**Comment by cvializ** [comment]
Great, thanks : ) I'll close this issue now since it's superseded by #8880 in the Great First Issue format
