### ISSUE TITLE
Sticky Ads Example on ampbyexample.com Throwing Error

### ISSUE THREAD

**Issue by ascherchen** [ampproject/amphtml#6096]
When navigating to https://ampbyexample.com/components/amp-sticky-ad/ although the example works the performance varies among each page refreshes. Sometime the ads show up really slow and sometime fast. The issue is that the page keeps throwing an error "[Error] Blocked a frame with origin "https://d-166548127613403226.ampproject.net" from accessing a frame with origin "https://ampbyexample.com". Protocols, domains, and ports must match." like below screenshot shown.

![unnamed 1](https://cloud.githubusercontent.com/assets/23347829/20122733/da87a000-a5ce-11e6-8e33-a32886daba5a.png)

Test done with real devices: iPhone6 plus + safari and Nexus 5x + Chrome

Why are these errors thrown?

**Comment by jasti** [comment]
to @zhouyx.

**Comment by Lith** [comment]
Hi, 

We have the same issue with our ad server ([Webediads](https://github.com/ampproject/amphtml/blob/master/ads/webediads.md)). 
Do you have any idea how to fix that ? It seems to be a CORS problem, but I'm not sure than this can be fixed on our side...

iOS devices are very restrictive, and we know Google et is not an Apple's best friend, but maybe you can help us to find a solution ?
No ad is working for now on all of our articles or recipes AMP with iOS devices.

![image](https://cloud.githubusercontent.com/assets/605495/21391550/7a0d8124-c78c-11e6-9507-947b7c61269c.png)

Thanks,

**Comment by jasti** [comment]
@zhouyx would you be able to look at this please?

**Comment by zhouyx** [comment]
@ascherchen The errors are expected. As the error message says it forbids an iframe from accessing a cross-origin iframe. Seems the ad script is trying to get info from the top window.

**Comment by ascherchen** [comment]
sorry to re-open but why is the error expected and why does this impact the performance of the sticky ad loading? And who can we speak to in the Amp-by-example page to get the x-origin iframe fixed? :)

**Comment by zhouyx** [comment]
It seems ad server script is trying to do something to the top window. Their scripts run in cross domain iframes, thus browser won't allow it and throw these error messages. The only fix I can think of now is to use an ad that doesn't try to do these kind of cross origin operation. 
These errors shouldn't impact the performance of sticky ad loading. At least I can't think of one. Do you have more info on why you think it is the reason?

**Comment by zhouyx** [comment]
@Lith As I mentioned the CORS errors are expected. 
However from your screenshot, I think the typeError(see last line) is the reason why your ad is not working on Safari.

**Comment by ascherchen** [comment]
@Yuxuan, thanks a lot.
@Vamsee: who owns the AMP by Example pages to fix the code for safari?

Alissa Scherchen
Partner Technology Manager

If you received this communication by mistake, please don't forward it to
anyone else (it may contain confidential or privileged information), please
erase all copies of it, including all attachments, and please let the
sender know it went to the wrong person. Thanks.

**Comment by jasti** [comment]
It's not ABE that's the issue. It is the way the ad itself is created - which being delivered from DFP. I think we should let this go because this is a niche case.
