### ISSUE TITLE
Using amp-sidebar more than once

### ISSUE THREAD

**Issue by cinemaxx** [ampproject/amphtml#6104]
We want to use the amp-sidebar more than once in our website. The first sidebar (from left to right) will be used to display the navigation of our website. The second sidebar we want to for switching between our local sites, so the user can select another cinema and will get the actual playtimes of the movie. Technically it is possible to use two different sidebars with two different ids. But the AMP-Validator gives an error, because the amp-sidebar is only allowed once. Are you planning to allow more than one sidebar in an amp-website?

We have made an example of our desired implementation: http://download.cinemaxx.de/download/web/amptest/kinoauswahl.html

**Comment by ericlindley-g** [comment]
@cinemaxx — are you planning to have the second sidebar open from the other side of the page, or the same side?

We might want to just relax the restriction to allow one on each side, though I'm not sure if that makes the validation too complex ( @Gregable ?)

On the other hand, we could remove the just-one-sidebar restriction entirely—unless that could cause other issues @camelburrito ?  I imagine we'd start to get into a little bit of trouble with both layering and dismissal of multiple sidebars, especially if they're on the same side (?)

**Comment by camelburrito** [comment]
We should fix #3320 and then relax it completely and not cap it . I also dont think there is a validation error for that @Gregable @powdercloud should be able to confirm

**Comment by MichaelNielsenDK** [comment]
Confirming validation error when using two sidebars
http://prntscr.com/d5eh7r 

Documentation also states that you can only have one
https://www.ampproject.org/docs/reference/components/amp-sidebar 

Multiple sidebars could be useful in a lot of scenarios, especially for e-commerce sites.

**Comment by cinemaxx** [comment]
Hey @ericlindley-g, 

thanks for your reply. We are planning to use the two sidebars from two different directions like on our website. The navigatzion would open from left to right, the cinema selection would open from right to left. Technically it is possible, just the validator says "not validate".

**Comment by powdercloud** [comment]
The validation part is easy, this is just the line "unique: true" in this file:
https://github.com/ampproject/amphtml/blob/master/extensions/amp-sidebar/0.1/validator-amp-sidebar.protoascii
Yes, it's currently an error to have more than one. And removing the "unique: true" will lift the constraint.

@camelburrito Is #3320 fixed? Should the limit in the validator be lifted?

**Comment by camelburrito** [comment]
@powdercloud not yet!

**Comment by mmicael1** [comment]
@camelburrito  any progress to use more than one sidebar ?

**Comment by camelburrito** [comment]
@ericlindley-g - can we prioritize this?

**Comment by elisei** [comment]
Also with validation error waiting for change and tracking.

**Comment by aghassemi** [comment]
Let's move ahead with this without https://github.com/ampproject/amphtml/issues/3320 first. See https://github.com/ampproject/amphtml/issues/3320#issuecomment-282048061 for reasoning.

**Comment by 8webdesign** [comment]
Any updates on this?
I'm still getting "The tag 'amp-sidebar' appears more than once in the document." error, 

But when I check https://ampbyexample.com/components/amp-sidebar/#development=1, they don't have any errors... why is the validation allowing them to have 2 sidebars, but not allowing me?

**Comment by aghassemi** [comment]
@8webdesign This is not done yet. ( I see the same validation error on https://ampbyexample.com/components/amp-sidebar/#development=1 so they are not exempt from it either)

@ericlindley-g @camelburrito Any objections with moving ahead with this without #3320 first?

**Comment by ktmn** [comment]
Any ETA for being able to use multiple sidebars?

**Comment by aghassemi** [comment]
This is fixed. Please allow 3-4 weeks for changes to show up in production.

**Comment by Gregable** [comment]
This is live in the most recent release.
