### ISSUE TITLE
Intent-To-Implement: embed Playbuzz interactive content with amp-playbuzz

### ISSUE THREAD

**Issue by buzzdan** [ampproject/amphtml#6106]
publishers and content creators use playbuzz to create an interactive and engaging content items.
developing amp-playbuzz extention will give them the ability to embed those items easily.

it should be easy to use:
```
<amp-playbuzz 
      item="/shaulolmert10/5-u-s-athletes-you-need-to-know-about-before-the-rio-olympics">
</amp-playbuzz>
```

few optional custom parameters can be supplied such as the display-item-info, display-share-buttons etc... :

```
<amp-playbuzz 
      item="/shaulolmert10/5-u-s-athletes-you-need-to-know-about-before-the-rio-olympics"
      display-item-info="true" 
      display-share-buttons="true">
</amp-playbuzz>
```

the markup above will use an iframe to load the content that looks something like that:

[![image](https://cloud.githubusercontent.com/assets/18007791/20140166/70f65b30-a692-11e6-9f8a-5294a780a131.png)](http://www.playbuzz.com/shaulolmert10/5-u-s-athletes-you-need-to-know-about-before-the-rio-olympics)

**Comment by camelburrito** [comment]
@buzzdan Thanks for filing! could you also expand a bit more on the advantages of creating this extension vs using amp-iframe

**Comment by ericlindley-g** [comment]
Also, @buzzdan, I'm curious how much of the content will be encapsulated by the component, is it:

* `amp-playbuzz` loads all of the meaningful page content of the page through `amp-iframe`? (I don't think this is a good use-case for AMP, as that means that the meaningful content of the page won't have the speed and UX benefits of AMP)
* `amp-playbuzz` embeds something like chunk of recommended content in the context of a larger article? (something like the cards listed on playbuzz.com)
* `amp-playbuzz` does something else? (It would be good to get more precise on what exactly is loaded inside of the `amp-iframe`)

**Comment by buzzdan** [comment]
@camelburrito @ericlindley-g thanks for the reply :)

Actually the example given in the discussion is inaccurate as it's from Playbuzz.com, but our AMP plugin is a solution for our publisher community.  

We currently work with 10K+ publishers, many of whom are major publications using AMP (think Sports Illustrated, CNBC, Daily Mail, Sky Sports etc) who embed our units on their site, as parts of their articles. 

Having the plug-in creates a friction free experience for our partners. It is important for us to control visual and functional elements in the iframe, and to streamline the event handling process which enables us to deliver important analytics to our partners.
The above simply won’t work well with amp-iframe.

The amount of content encapsulated by the component can be seen in the following examples, embedded inside different content pieces:

http://www.skysports.com/football/news/12016/10652658/vote-england-or-scotland-who-has-the-best-to-offer

http://www.si.com/mlb/2016/11/02/greatest-game-seven-moments-world-series-history

http://www.espn.com/sportsnation/story/_/id/17987314

http://www.refinery29.com/celebrity-salary-quiz

http://www.arsenal.com/news/news-archive/20161029/vote-for-your-sfcvafc-man-of-the-match

http://www.cnbc.com/2016/06/17/seeing-color-for-the-first-time-these-high-tech-lenses-can-cure-color-blindness.html?view=story&%24DEVICE%24=native-android-mobile

**Comment by ericlindley-g** [comment]
Ah, I see—thanks for the extra examples. For most of these the playbuzz element is a quiz/poll-type interaction, and for the other it's an interactive slideshow. With this context, these seem like a good fit for AMP. Do you have more details on why amp-iframe doesn't work?

**Comment by dvoytenko** [comment]
SGTM. Let's proceed with the implementation.

**Comment by buzzdan** [comment]
@ericlindley-g  yes, few things:
due to the items interactive nature, our formats are dependent on events to work (visually & functionality) and provide important analytics to our publishers, which is part of our core value.
Just a small example - we use scrolling events to expose certain visual elements as part of the UX. 

Additionally, using amp-iframe requires the publisher to add mandatory extra parameters manually which is error prone.  
Our intention of using the extension is to automatically create those parameters, easing the publishing process and preventing broken implementation

**Comment by ericlindley-g** [comment]
Thanks for the extra details, @buzzdan — I'll defer to folks like @dvoytenko regarding the mechanic for events in this context, as I'm not sure what the approach would be. If you haven't already, the next step is to submit a pull request where the core contributors can jump in and give feedback. Excited to see this in AMP!
