### ISSUE TITLE
AdTech magicNumber or placementId not being replaced properly inside the AMP script.

### ISSUE THREAD

**Issue by alexarvanitidismrf** [ampproject/amphtml#6109]
## Short description of your issue:

AdTech magicNumber or placementId not being replaced properly inside the AMP script.

## How do we reproduce the issue?

![screen shot 2016-11-09 at 17 33 29](https://cloud.githubusercontent.com/assets/18212860/20146058/af8f4f18-a6a2-11e6-8abd-4f5905098bb1.png)

My ```magic number/placementId ``` is 1234567 and inside the script URL, I don't see this ID. Instead I see the number ```221794```. 

Steps:
1) Add an adTech AMP tag
2) Change the magicNumber/placementId
3) No change inside the script. 

The value that should be changed by the placementId is the one in the following screenshot:
![screen shot 2016-11-09 at 17 36 53](https://cloud.githubusercontent.com/assets/18212860/20146198/39f2f6a0-a6a3-11e6-93ad-be99eafecc1c.png)

## What browsers are affected?

Probably all browsers

## Which AMP version is affected?

Version 1478272520861

**Comment by cramforce** [comment]
You will need to file this with AdTech support. The AMP team is unlikely to be able to help.

**Comment by jridgewell** [comment]
Yah, there's nothing we can do here. If you look in the `<iframe>` directly under the the `<amp-ad>`, you'll notice we set the `atwMN` as part of the JSON encoded hash fragment (in the `src` attribute).

**Comment by mbreinesberger** [comment]
Hello! I am new to AMP. 

Has this already been fixed? I tried to implement adtech, but the magic number is still not replaced and the banner is not displayed. If not, can the issue please be re-opened or what else could I do? Thanks.

**Comment by jasti** [comment]
@mbreinesberger could you please reach out to adtech directly as they control their AMP implementation? Thanks. 
CC @lisamayo
