### ISSUE TITLE
Move the postMessage rate limit logic to `SubscriptionApi` class.

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#6110]
When look at our `intersection-observer.js` I found we put limiting rate logic there because we want to send a maximum of 10 postMessages per second. I feel this part of the logic does not relate to `intersectionObserver` and should be moved to `SubscriptionApi`.

@cramforce @lannka @jridgewell thoughts?

**Comment by lannka** [comment]
Is this rate limit used other than InOb? Since we plan to make it trigger by threshold  #6030, so rate limit might not be needed anymore.

**Comment by jridgewell** [comment]
Rate limiting was added to avoid a ton of scroll events each sending an update to a their iframes. With threshold, this won't be needed any more.

**Comment by zhouyx** [comment]
Sounds good. Don't find other places where we limit postMessage rate. Close this issue
