### ISSUE TITLE
Docs: AMP JS as last element in the head

### ISSUE THREAD

**Issue by eddhannay** [ampproject/amphtml#612]
[The spec specifies](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#scrpt) that the script tag that includes the AMP JS library must be the last element in the head. [ampproject.org/how-it-works](https://www.ampproject.org/how-it-works/) does not follow this, but [in validation mode](https://www.ampproject.org/how-it-works/#development=1) it is not flagged up as an error. [The Everything example](https://github.com/ampproject/amphtml/blob/master/examples/everything.amp.html) also doesn't follow the spec. 

Is where the script appears in the head actually a requirement, or should the spec be relaxed?

**Comment by cramforce** [comment]
Yeah, we don't really care. Spec should be updated.

**Comment by sriramkrish85** [comment]
I think this has been fixed in https://github.com/ampproject/amphtml/pull/630. Closing
