### ISSUE TITLE
amp-form GET accepts non-HTTPs action

### ISSUE THREAD

**Issue by weeblr** [ampproject/amphtml#6123]
Hi

Working on a simple search form, using GET and an action attr:
````
<div id="search-form" class="wbamp-search-form">
	<form method="get" action="/products/wbamp/src/main/" target="_top">
	    <input type="search" placeholder="Search..." required="" name="q"></input>
            <input type="submit" value="OK" class="wbamp-button-search"></input>
</form>
</div>
````
Contrary to expectations based on [https://ampbyexample.com/components/amp-form/](example sitel) and [https://www.ampproject.org/docs/reference/components/amp-form](documentation), the form gets submitted even to an HTTP URL.
In addition:

- if action URL is fully qualified (`http://local.web/products/wpamp_dev/src/main/`) we get an error message in the console (Error form URL must start...), but only briefly as the form is submitted anyway
- if action URL is site-relative: `/products/wbamp/src/main/` (the site is 100% HTTP, not HTTPS), the form is submitted without even a message.

What do you think?

Rgds

**Comment by Gregable** [comment]
Hm, yes. We don't allow explicit http:, but we do allow relative. I assume that this is the wrong choice. @mkhatib, should we disallow relative URLs as well?

**Comment by mkhatib** [comment]
I believe yes we should only allow explicit https. @cramforce what do you think?

**Comment by weeblr** [comment]
Hi

Thanks. Shouldn't you allow relative URL if the page is secure already? ie if the browser will eventually resolve to GET the action URL in a secure way?

This would apply to relative URLs (eg action="search.html") and relative to host ((eg action="/search.html").

RGds

**Comment by cramforce** [comment]
The policy should be the same as for other HTTPS only resources such as
iframes and videos.

**Comment by Gregable** [comment]
Hm, well so `amp-iframe` and `amp-video` allow relative URLs because we'd be invalidating docs at this point. The rules actually read:

`allow_relative: true  # Will be set to false at a future date.`

So @cramforce, that's not terribly well defined.

@weeblr, we don't really want validation output to vary based on the document URL, since that can cause confusion when developing.

**Comment by cramforce** [comment]
@Gregable Do we allow protocol relative or true relative URLs?

Both `amp-iframe` and `amp-video` have runtime asserts that the effective URL is secure. `amp-form` is the same. It is probably OK to have them all validate the same inputs in that case.

**Comment by weeblr** [comment]
Hi

@Gregable Understand, however if you simply block anything that's not explicitely https (ie https://example.com/my-page.html), you will end up blocking forms that are posted to a perfectly valid target, fully secure ( ie posting to /my-page.hml on https://example.com)

The current situation is of course very confusing, where one can easily post a form to a non-secure origin, simply by using protocol-relative URL or relative URL.

@cramforce 

>  amp-form is the same.

This is not what I see happening. One can post a form to a non-secure origin, by using a protocol-relative action URL (can't test right now with a site relative URL -  /my-page.html)

Rgds

**Comment by cramforce** [comment]
@weeblr Yes, these checks do allow protocol relative URLs. AMP documents may sometimes render as HTTP, but the very same document can also render as HTTPS (e.g. when using the Google AMP Cache). In that case the protocol relative URL resolves to HTTPS.

We made the decision that using a protocol relative URL is an expression of intent that HTTPS should work. Maybe that was wrong, but that is where we are.

**Comment by weeblr** [comment]
@cramforce So HTTPs is not an hardcore requirement for sumitting a form, right. Fine with me, as long as this is the expected behavior and will keep being that way, for backward compatibility reasons.

**Comment by cramforce** [comment]
I'd be fine with changing it for forms if that still can be done without breakage.

**Comment by weeblr** [comment]
@cramforce TBH, I'm not sure what's the rationale behind selecting what can be done HTTPS/only and what can't. Restricting form submission to real-HTTPS only would certainly take out the little interactivity AMP pages can have, from a web site owner standpoint.

**Comment by cramforce** [comment]
Everything on an AMP page must work on HTTPS. The exceptions for resources that are allowed on HTTP are simple: It is resources that are proxied by AMP caches. AMP Caches can't really proxy iframes and forms (and currently don't proxy video). Hence the exceptions.

**Comment by weeblr** [comment]
ok, got it.

**Comment by Gregable** [comment]
@cramforce the validator does not distinguish between relative and protocol relative currently.

If runtime allows relative as long as the top level URL is secure, then validator will be more strict than runtime by disallowing relative.

**Comment by cramforce** [comment]
@Gregable understood.

**Comment by Gregable** [comment]
Approximately half of the documents on the web containing amp-form and found on an http URL would break if we disallowed `action` to be a relative URL. Unless we're willing to make a breaking change, at this point I don't think we can do anything here.

I would argue that we should not change the documentation either, as it's still best practice to make this an absolute https URL.
