### ISSUE TITLE
GET amp-form gets submitted even if invalid

### ISSUE THREAD

**Issue by weeblr** [ampproject/amphtml#6124]
Hi

Working on a simple search form, using GET and an action attr:
````
<div id="search-form" class="wbamp-search-form">
	<form method="get" action="/products/wbamp/src/main/" target="_top">
	    <input type="search" placeholder="Search..." required="" name="q"></input>
            <input type="submit" value="OK" class="wbamp-button-search"></input>
</form>
</div>
````
Contrary to expectations based on [https://ampbyexample.com/components/amp-form/](example sitel) and [https://www.ampproject.org/docs/reference/components/amp-form](documentation), the form gets submitted even if there are some invalid fields.

In this case, if one clicks on the search button while leaving the search input field empty, we briefly see the browser-generated "Please fill this field" message, but are redirected to the action URL.

I would expect the form to not be submitted in such case.

Rgds

**Comment by weeblr** [comment]
Please note that behavior is the same regardless of whether action URL is fully qualified, relative or relative to site (see #6123)

**Comment by mkhatib** [comment]
@weeblr which browser are you seeing this behavior in?

**Comment by mkhatib** [comment]
Do you also have a link where an example is exhibiting that behavior?

**Comment by mkhatib** [comment]
Nevermind, I am able to repro. This happens because of the exception we through for relative URLs. To avoid this for now, please use the full-https URL. 

Once we resolve #6123 relative URLs are either gonna be invalid for action or only allowed in HTTPs served pages.

**Comment by weeblr** [comment]
OK, going to test again, I thought I thought about this and already tested with fully qualified URLs.

**Comment by weeblr** [comment]
Hi again

So after trying again, here is the deal: the form gets submitted even if a "required" condition is not satisfied if:

- action URL is "relative" ie "/search.html" or "search.html"
- action is URL is fully qualified **but** HTTP ie "http://local.web/search.html"

If URL is HTTPS, there is no submisssion.

Rgds

**Comment by mkhatib** [comment]
This is the expected behavior, although maybe we should prevent submission before we throw the error to avoid this happening.

**Comment by weeblr-dev** [comment]
Hmm, I don't see how the form should be submitted if a required field is empty...

**Comment by weeblr** [comment]
FYI, I am now using a workaround: instead of http/https, I replace the action URL with a protocol-relative one (ie action="//domain.com/search.html")

- the action URL is accepted as valid
- the form is not submitted if invalid.

Note that as mentioned in #6123, this does allow the action URL to be, in effect, non HTTPS.

Rgds
