### ISSUE TITLE
[amp-analytics] Default empty selectors to `:root` in visibilitySpec

### ISSUE THREAD

**Issue by avimehta** [ampproject/amphtml#6128]
Context: https://github.com/ampproject/amphtml/pull/6008#discussion_r87285914

Things to do:
- Fix simple visible trigger in A4A: https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/instrumentation.js#L260

- Fix 3p case where selector=":root". https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/visibility-impl.js#L168

/cc @dvoytenko

**Comment by rudygalfi** [comment]
Any updates on this?

**Comment by dvoytenko** [comment]
WIP

**Comment by rudygalfi** [comment]
Dima is going to work on this during the upcoming sprint. Reassigning from @avimehta to @dvoytenko.

**Comment by rudygalfi** [comment]
@dvoytenko Is this going to finish within the sprint?
