### ISSUE TITLE
Change data type LayoutRect to DOMRect

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#6131]
`DOMRect` has two more redundant fields `x` and `y` than `LayoutRect`.
Unifying the data types helps us remove the [data conversions](https://github.com/ampproject/amphtml/blob/master/src/intersection-observer.js#L43).

**Comment by ericlindley-g** [comment]
Passing to @lannka to triage — not sure if this needs PM input, or what vertical it would go in

**Comment by lannka** [comment]
This is a code refactoring and clean up work. Not sure what is the right "type" to put. But most likely should fall into backlog now.

**Comment by adelinamart** [comment]
SGTM. I added a low priority for now.
