### ISSUE TITLE
Make utf8Encode  / utf8Decode synchronous.

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#6139]
`utf8Decode/utf8Encode` can be polyfilled with a different  approach when `TextEncoder` is not available to stay synchronous. 

For now we have two new methods in `bytes.js`, `utf8DecodeSync` and `utf8EncodeSync`, we should change all the places the old asynchronous `utf8Decode/utf8Encode` are used to use the sync version and then remove the old ones and rename the sync versions to be just `utf8Decode/utf8Encode`

**Comment by adelinamart** [comment]
@aghassemi @ericlindley-g I think we need to add this to your triage queue? Thanks

**Comment by aghassemi** [comment]
closed by https://github.com/ampproject/amphtml/pull/13091
