### ISSUE TITLE
AMP Social Share: Facebook button shares improper URL. 

### ISSUE THREAD

**Issue by sandiprb** [ampproject/amphtml#6145]
Following is my code for button.

```
<amp-social-share type="facebook"
        width="45"
        height="33"
        data-param-text="{{ page title }}"
        data-param-url="{{ page absolute url }}" <!-- (e.g. coverfox.com/post/1234) -->
        data-param-app_id="xxxxx"></amp-social-share>
```

While sharing the URL with social share, it posts wrong on Facebook.
The URL : https://coverfox.com/post/1234
URL Shared on fb : https://coverfox.com/post/1234/coverfox.com/post/1234

URL is repeated in the post.

**Comment by mkhatib** [comment]
@sandiprb the proper attribute for `type=facebook` for the URL to share is `href`. [Please refer to docs here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-social-share/amp-social-share.md#pre-configured-providers).

Another problem could be that your absolute url is not really absolute - in your example you gave `coverfox.com/post/1234` is not an absolute URL. Your URL needs to start with `http://`, `https://` or `//` to be absolute.

If this is still a problem, do you have a page where this is happening? Feel free to re-open.
