### ISSUE TITLE
Implement hashchange based mechanism to transition pages to visible

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#6147]
Some native apps would like to load pages with `visibilityState=hidden/prerender` and transition them to `visible` without JS injection.

Can we listen to `hashChange` and apply `visibilityState` updates based on that?

CC @dvoytenko @chenshay

**Comment by dvoytenko** [comment]
Certainly possible. We could probably support of a number of "initial" parameters this way.

**Comment by cramforce** [comment]
shalabi@ would like to have this. Please coordinate with him.

**Comment by dvoytenko** [comment]
We will first resolve issue with missingOrigin since that may force us to switch to `iframe.name`.

**Comment by ericlindley-g** [comment]
/to @dvoytenko  (let me know if it makes sense for me to be involved, e.g. w/ prioritization)

**Comment by cramforce** [comment]
We won't do this, right? Decided to use postMessage instead.

**Comment by dvoytenko** [comment]
Correct. Closing.
