### ISSUE TITLE
Change A4A validator to allow amp4ads-v0.js as runtime script

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#6154]
This is for #5700.

PR #6152 will change the A4A runtime script URL from `v0.js` to `amp4ads-v0.js`. Validator needs to get updated accordingly. We can let A4A validator allow either script for now (but not both), and be more strict when eventually launched amp-inabox.

@jasti

**Comment by Gregable** [comment]
Update: the new plan is to use `amp4ads-v0.js` for naming consistency elsewhere.

**Comment by lannka** [comment]
@Gregable is this already done?

**Comment by Gregable** [comment]
I'll close the issue, because yes it is done in github. The change is not live though.

**Comment by honeybadgerdontcare** [comment]
Change is now live.

**Comment by lannka** [comment]
@honeybadgerdontcare thanks for the update
