### ISSUE TITLE
Refactor viewer-impl and keep it simple. 

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#6159]
The `viewer-impl.js` is bloated. Any component that talks to the Search Viewer adds methods there. It doesn't just make the Viewer one-thousand line of code, it also had business logic scattered around.

We plan to bring back a slim `viewer-impl.js`, which should just provide basic methods like `receiveMessage` `sendMessage` `getParam` `hasCapability`.

We plan to move the methods to their own business components:
- [x] history related methods => `history-impl.js`
- [x] baseCid => `cid-impl.js`
- [x] overlay, getPaddingTop => `viewport-impl.js`
- [x] tick => `performance-impl.js`
- [x] postDocumentLoaded => `resources-impl.js`
etc.

A typical usage of the new viewer code will be like:
```
if (viewer.hasCapability('cid')) {
  viewer.sendMessage('cid', data).then(...);
}
```

**Comment by muxin** [comment]
- postScroll => `viewport-impl.js`
- postDocumentReady => `resources-impl.js`
- setFlushParams, flushTicks, prerenderComplete => `performance-impl.js`
- updateFragment, getFragment => stay in `viewer-impl.js`
