### ISSUE TITLE
A4A is likely failing on browsers that do not have native Fetch API

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#6160]
This is because A4A assumes the `response.headers` is https://developer.mozilla.org/en-US/docs/Web/API/Headers but our polyfill for headers miss a lot of what the native one has. (it actually only has `get`)

So far I noticed A4A code uses `headers.has` (in `google/ads/units/a4a.js`) which our polyfill does not have, so that would certainly failing on browsers that use the Fetch polyfil.

I recommend A4A code changes type annotations from `{Headers}` to the lowest common denominator `{FetchResponseHeaders}`

**Comment by aghassemi** [comment]
@ampproject/a4a Noticed this while trying to fix the tests for Safari. I will have a PR out soon for it.

**Comment by tdrl** [comment]
Just to check: Are you intending to do the type annotation changes, or are you asking us to?

**Comment by aghassemi** [comment]
@tdrl I wasn't planning to do the type annotation changes. Please plan with other A4A work.

**Comment by jridgewell** [comment]
Closed by #6161.
