### ISSUE TITLE
Focus ad blocker breaks loading AMP pages on Google Search

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#6163]
I received reports about this from users (See https://twitter.com/dwm189/status/797460628344541184 but it might affects other users)

This may, in particular, affect reddit pages, but maybe all pages.

To @choumx for debugging.

**Comment by cramforce** [comment]
Filed https://github.com/disconnectme/disconnect-tracking-protection/issues/9

**Comment by cramforce** [comment]
Also filed https://bugzilla.mozilla.org/show_bug.cgi?id=1317067

**Comment by choumx** [comment]
- Most news publishers unaffected
- All reddit AMP pages broken by `Block social trackers` setting
- All Forbes AMP pages broken by `Block ad trackers` setting
- `Block other content trackers` setting has no apparent effect, despite scary warning

**Comment by cramforce** [comment]
Gist with info from user https://gist.github.com/dmccown/2a300939844c87a5c2d787ae2a9a607b

**Comment by choumx** [comment]
I believe the problem is the way Focus builds the URL filtering regex from the `disconnect`'s blacklist JSON. Specifically, it creates Swift regexes for blacklisted domains that incorrectly match AMP CDN URLs. I'll add details on the Bugzilla entry that Malte filed above.

**Comment by choumx** [comment]
PR with my proposed fix: https://github.com/mozilla-mobile/focus/pull/26

**Comment by choumx** [comment]
PR is merged. Bug should be fixed on the next release of Focus.

**Comment by rudygalfi** [comment]
This might be happening again based on [reports on Reddit](https://www.reddit.com/r/apple/comments/5lnmfi/is_there_a_way_to_disable_google_amp_on_safari_ios/dbyceqi/). @choumx Do you have any status on when the fix went out (if it went out) and can you check again to see if you can reproduce?

**Comment by choumx** [comment]
Just tried and can't repro. The fix was released on November 17, 2016. That user may need to update the Firefox Focus app to v2.0+.

**Comment by cramforce** [comment]
@rudygalfi Apparently it isn't entirely trivial to get focus to update the ruleset. I do not have instructions, though.
