### ISSUE TITLE
Add open to clicked toggle item

### ISSUE THREAD

**Issue by MichaelNielsenDK** [ampproject/amphtml#6164]
Adding open to the clicked toggle button, and not only eg. sidebar, would allow to alter the appearance of the clicked item.

An example where this could be helpful, is that many are transforming the menu icon into a close icon, like these
https://codepen.io/designcouch/pen/Atyop

**Comment by jridgewell** [comment]
Dupe of #3501. We've been reluctant to add due to https://github.com/ampproject/amphtml/issues/3501#issuecomment-224892094.

**Comment by jridgewell** [comment]
On second thought, we could restrict this to just buttons or X approved element and only allow the element to toggle states on itself.

**Comment by MichaelNielsenDK** [comment]
Why the concern for ReadMore buttons as described in #3501? 

Would that be different than what already is possible with amp-accordion?

**Comment by jridgewell** [comment]
I don't have a good answer. 😅

**Comment by ericlindley-g** [comment]
@MichaelNielsenDK 
Back to the original intent of this feature request: do you just want to be able to add the "open" attribute (or class) to a button after it has been used to toggle open the sidebar (and then remove when the sidebar has been closed again)? This seems like a reasonable behavior to support.

@camelburrito, WDYT? Is there already a clever/easy way to do this with CSS selectors? Would it be better to support this through the binding protocol?

**Comment by camelburrito** [comment]
Binding would be the best ! Other workaround might be sibling selector if the open button is the adjacent sibling of the sidebar.

**Comment by MichaelNielsenDK** [comment]
@ericlindley-g Yes, that is exactly what I would like.

**Comment by ericlindley-g** [comment]
@MichaelNielsenDK 

Okay, the good news is that we're working on a [binding protocol](https://github.com/ampproject/amphtml/issues/6199) that may support this use-case (/cc @choumx  as FYI: this FR is to add a class or attribute to a button that toggles the sidebar, based on the sidebar's own open/close state).

For now, the fallback is to use CSS selectors, but of course that won't work for all cases.

**Comment by MichaelNielsenDK** [comment]
@ericlindley-g Great I'll keep my self updated as to the progess with the binding protocol. 

Could you elaborate on what you mean when you say _"the fallback is to use CSS selectors"_

**Comment by randallbpotter15** [comment]
@ericlindley-g  
I'm using a checkbox with ::before and ::after etc to change the display from hamburger to "X" on open and close.  When toggling open, then clicking back I'm stuck with the "X" icon as I have no class to CSS select off of?

cc: @MichaelNielsenDK

**Comment by camelburrito** [comment]
@randallbpotter15 will the css `:not` operator help?

**Comment by ericlindley-g** [comment]
@MichaelNielsenDK  — Sorry, that was a bit unclear on my part : )   By "the fallback is to use CSS selectors" I meant that developers could use CSS selectors to enable the behavior. For instance: since the sidebar is always a direct descendant of `<body>`, you could use a sibling selector to style a sidebar toggle button on the page, provided it is also a direct descendant of `<body>`. Of course, this limits flexibility in terms of where the toggle can be placed, so it's not ideal. A better solution in the future would be to support this behavior with the binding protocol (this protocol is currently in development).

**Comment by MichaelNielsenDK** [comment]
@ericlindley-g Thanks for the clarification. In my case however, the toggle button is not a sibling to the sidebar, but with a little hacking, it probably could be.

**Comment by ericlindley-g** [comment]
Closing this, since the use case will be supported through the [binding protocol](https://www.ampproject.org/docs/reference/components/amp-bind) currently in development — but please feel free to re-open or start a new issue for any additional features that need support.
