### ISSUE TITLE
Allow sidebar to be 100vw

### ISSUE THREAD

**Issue by MichaelNielsenDK** [ampproject/amphtml#6165]
Currently there's a max-width:80vw!important style on amp-sidebar. 

A sidebar could however contain many things, where you would like to take advantage of the full screen. But there is no way to override the style without breaking validation.

**Comment by camelburrito** [comment]
@MichaelNielsenDK - this is per design - if this is 100% then this becomes a lightbox - you could try using a light-box instead.
@ericlindley-g will be able to explain better.

**Comment by ericlindley-g** [comment]
@MichaelNielsenDK — we initially restricted the width to avoid bad user experience (full-screen ad takeovers, for instance). Do you have a particular use-case you want to enable?

**Comment by MichaelNielsenDK** [comment]
@camelburrito I feel that things like menus, small carts, filter options and other things should be in a sidebar, it just makes more sense, but thanks for the suggestion.

@ericlindley-g But a full screen ad could just be done with a lightbox, could it not? 

So I don't see an argument for not giving the control of the width to developers/designers. 

Regarding a use-case, then i only have this so far
http://oerskovtest2.shoporama.dk/thelma-shopping-taske?amp=1 

It's an e-commerce template, and I would like for my menu and small cart to cover the entire page (yes, I'm also holding out for multiple sidebars ;-)). I'll probably be needing another for filter options later on.

Other than being able to take full advantage of the screen real estate available, having it only 80vw gives a distraction in the side of the screen, The mobile conversion specialists I have spoken to, also recommends that sidebars and the like, should be full-width.

**Comment by bnku** [comment]
Is AMP an independent opens ource project, or an extension to the Material Design Guidelines?
I am fully confident that the designer should be able to fully manipulate the screen space!

**Comment by ericlindley-g** [comment]
Particularly given that a full-screen sidebar is possible through a number of other methods now, I don't see a problem removing the 80vw restriction. Will keep this bug closed because it is a duplicate of this issue: https://github.com/ampproject/amphtml/issues/10587
