### ISSUE TITLE
Intent-to-implement: Additional amp cache options

### ISSUE THREAD

**Issue by dknecht** [ampproject/amphtml#6167]
Cloudflare plans on offering several products for the AMP community.  As a precursor to launching we will need for publishers to add the Cloudflare AMP Cache  endpoint to their CORS settings and remote.html file to ensure all content will render correctly.  

We will be making a pull request to update documents to include the Cloudflare cache location of "*.amp.cloudflare.com".

**Comment by cramforce** [comment]
**Exciting! Welcome cloudflare!!!**

Lets start with a PR to update the cache documentation!
