### ISSUE TITLE
AMP Sticky Ads to collapse when unfilled

### ISSUE THREAD

**Issue by guillelamb** [ampproject/amphtml#6184]
AMP Sticky Ads currently leave an empty space when ad requests go unfilled.

Unlike other standard ad slots, collapsing these wouldn't cause reflow within the content, so it would make sense to do so and avoid having the blank space at the bottom of the browser.

As discussed with @jasti, tracking the issue here, which doesn't seem browser-specific or related to a particular device or AMP version.

**Comment by jasti** [comment]
Thanks for the issue!
@zhouyx @lannka - we should implement this for all ad networks that support 'no-content'. Thoughts?

**Comment by zhouyx** [comment]
Thanks for the issue @guillelamb. however collapsing is a feature that amp-sticky-ad support. 
Here's how it works. If the contained ad support `no-content` API, it will try to collapse itself in when it receives `no-content` msg. When collapse happens, it will call `collapsedCallback` of sticky-ad and the sticky-ad will set its display to none.
Two possible reasons I can think of for the case that sticky-ad doesn't collapse. 1. the ad doesn't call `no-content`. 2. The ad calls `no-content` too late, it tries to collapse after the ad is in viewport, thus it never successfully collapse or call sticky-ad `#collapsedCallback`. Two solutions I can think of now to this issue. One is to have all ad network support `render-start`/`no-content` API, the other is to force collapse for ad inside sticky-ad container.

**Comment by jasti** [comment]
huh, may I mis-guided @guillelamb. @guillelamb A test page would be super useful. Thanks.

**Comment by guillelamb** [comment]
Thanks both: I'll try to get a test page where this is happening tomorrow.

**Comment by jridgewell** [comment]
> The ad calls no-content too late, it tries to collapse after the ad is in viewport

We should allow ads to collapse at anytime when they are in a container.

**Comment by zhouyx** [comment]
SGTM.

**Comment by guillelamb** [comment]
In case it's still useful, here's a live page with such a sticky ad slot, which is not collapsing when unfilled:
https://www.google.es/amp/www.abc.es/sociedad/abci-espanoles-debemos-reconocer-intensa-labor-asistencial-iglesia-201611221350_noticia_amp.html

![sticky_amp](https://cloud.githubusercontent.com/assets/526468/20600691/1f62a9b2-b255-11e6-9d48-3aa5a29e2c91.png)
