### ISSUE TITLE
A4A use AmpAdUIHandler class

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#6185]
A4A can make use of the AmpAdUIHandler class to provide better placeholder/fallback behavior. `uiHandler` has already been created in A4A code,  A call to `this.uiHandler.setDisplayState(AdDisplayState.LOADED_NO_CONTENT)` will take care of the UI behavior by doing one of the following work: apply user provided fallback, try to collapse, apply default fallback. 
The key question here is when to call that function though

cc: @lannka @keithwrightbos

**Comment by glevitzky** [comment]
We already do this in amp-ad-xorigin-iframe-handler, so I'm not sure that this needs to be added to amp-a4a.js directly.

**Comment by zhouyx** [comment]
But in `xOriginIframeHandler` we never init the apis for A4A fallback ad. 
https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js#L103
For example a no-content ad in the A4A case will never be applied fallback or collapsed.

**Comment by glevitzky** [comment]
That's true. I think the best bet would be to do something like this: 

```
if (opt_isA4A) {
   // A4A writes creative frame directly to page therefore does not expect
   // post message to unset visibility hidden
  this.element_.appendChild(this.iframe);
  listenForOncePromise(this.iframe, 'no-content', true)
      .then(() => this.noContent_());
   return Promise.resolve();
}
```

Does that make sense? This doesn't solve the problem for X-domain iframes where the ad request doesn't return in time or returns malformed, but there's not much we can do for those cases in the A4A flow.

**Comment by zhouyx** [comment]
I guess this is the best we can do for now😢

**Comment by jasti** [comment]
Please reopen if this needs more discussion.
