### ISSUE TITLE
Should the style attribute be allowed on SVG?

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#619]

**Comment by Gregable** [comment]
What's the argument for it? We don't allow style anywhere else in the document? Just trying to understand.

**Comment by cramforce** [comment]
@Gregable Never mind, actually. I thought it had different semantics, but it doesn't. Closing.

**Comment by jarek-foksa** [comment]
Allowing all the presentational SVG attributes while not allowing the style attribute seems contradictory to me.
