### ISSUE TITLE
Intent to implement: "Adtype:Adverticum"

### ISSUE THREAD

**Issue by Adverticum** [ampproject/amphtml#6195]
Hello!

I intent to implement Adverticum adServer into amp-ad on behalf of the named company. We'll sign the corporate CLA as soon as possible. 
A pull request will be made when the integration is complete and passes our internal tests.

If i'm right after the CLA is sign i only need to follow these instructions: 
https://github.com/ampproject/amphtml/tree/master/ads#developer-guidelines-for-a-pull-request
Is that true? Do you have any more requirements or guides on this subject?

**Comment by lannka** [comment]
@Adverticum yes you're looking at the right guideline. As mentioned in the guideline, please consider implement render-start and no-content API.

**Comment by Adverticum** [comment]
We just signed the CLA!

**Comment by jasti** [comment]
@Adverticum Do you have an ETA for your PR?

**Comment by zhouyx** [comment]
I believe the PR is in #6493
Closed.
