### ISSUE TITLE
Intend to Implement: `play`, `pause`, `mute`, `unmute` AMP actions for any player that implements the video-interface

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#6198]
VideoManager should automatically add `pause` and `play` AMP actions to the components that register. Actions should also be smart enough to queue the requests and invoke them on the player when it is ready and loaded.

**Comment by aghassemi** [comment]
/cc @ericlindley-g @dvoytenko @cramforce 
this would expose `play`, `pause`, `mute`, `unmute` actions for video players than implement the video interface ( e.g. `amp-video`, `amp-youtube`)

**Comment by aghassemi** [comment]
@ericlindley-g This will allow custom video controls for play/pause and mute/unmute. The primary use-case for this is having a "Play Video" element somewhere else on the page. Hiding native controls and implementing custom ones is definitely discouraged but makes sense for certain cases (specially video ads)

**Comment by dvoytenko** [comment]
A note I made some time before: we need to think how to make this kind of actions to expose an interface that supports `isEnabled` API. E.g.
```
interface Action {
  isEnabled(): boolean;
  execute(args);
}
```

This way, supporting custom controls should be straightforward and can avoid most of event bindings - instead we can automatically update the state of the control and implement the action. This may or may not be part of binder.
