### ISSUE TITLE
Intent to implement: Bind

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#6199]
## Summary

Bind is a new AMP extension that allows elements to mutate in response to user actions or data changes via data binding and simple JS-like expressions.

This will allow publishers to build responsive UIs for use cases not covered by existing AMP extended components. See #5059 for possible use cases.

## Usage

In this example, the \<p\> element will have its `textContent` changed from "" to "Hello World". 

```
<amp-dataset id=”foo”>{ bar: “Hello World” }</amp-dataset>
<p [text]=”foo.bar”></p>
```

Syntax is subject to change.

## Details

Syntax discussion: #5760 
Design doc: [Link](https://docs.google.com/document/d/1MdeRkyK84hREMqIglAf3-MYaFSWV2uYbUnleJjC1bYw/pub)

**Comment by ericlindley-g** [comment]
@choumx  — does this make sense to put in the sprint kicking off today, since Bind is in progress?

**Comment by choumx** [comment]
@ericlindley-g Moving back to prioritized FRs since this is a top-level tracking issue.

**Comment by ericlindley-g** [comment]
Makes sense — thanks!

**Comment by adelinamart** [comment]
@choumx any updates here? Thanks.

**Comment by choumx** [comment]
Yes! Closing since this is launching in next release.
