### ISSUE TITLE
window.context.requestResize() behavior Inconsistent on iPhone

### ISSUE THREAD

**Issue by e2corporation** [ampproject/amphtml#6200]
In the example below, the resize requests are only submitted when our panel is outside viewport scope.

[https://shogun-amp.herokuapp.com/examples/revcontent-heavy.html](https://shogun-amp.herokuapp.com/examples/revcontent-heavy.html)

On **iPhone** the amp-ad tag resize request is never honored in **portrait orientation**, resulting in an amp-ad tag with no inline-height set, which then produces clipping and inside scrolling within the tag, the only visible portion is the value of i-amp-sizer's padding.

The BG is painted green upon a successful resize (works on Android devices, Galaxy S7).

Is there something missing in order to correct the behavior with iPhone? Please reference Ticket #6176 for additional information.

**Galaxy S7**
![screenshot-amphtml localhost-2016-11-15-13-54-22](https://cloud.githubusercontent.com/assets/1742233/20319180/23a230b8-ab3b-11e6-86fc-01e8c1ff7a04.png)

**iPhone 5**
![screenshot-amphtml localhost-2016-11-15-13-52-30](https://cloud.githubusercontent.com/assets/1742233/20319179/23a160ca-ab3b-11e6-8cf1-6ab785fe91d5.png)

**Comment by lannka** [comment]
@e2corporation I'm wondering if the issue persists with the latest code after the discussion in the other thread: #6176

**Comment by e2corporation** [comment]
This is good to close, the latest changes and ajustments made during
testing have resolved this part of the original issue. Thank you.
