### ISSUE TITLE
cdn.ampproject../**.js Cache Time ( PageSpeed )

### ISSUE THREAD

**Issue by PHCsys** [ampproject/amphtml#6206]
![screenshot from 2016-11-15 22 50 25](https://cloud.githubusercontent.com/assets/20255913/20325809/6d7df938-ab86-11e6-9c3e-d9b5924a10a6.png)

**Comment by jridgewell** [comment]
See https://github.com/ampproject/amphtml/issues/3454#issuecomment-223995830.
