### ISSUE TITLE
amp-youtube consumes a lot of bandwidth

### ISSUE THREAD

**Issue by winstonma** [ampproject/amphtml#6218]
First of all I assume all people are new comers so in Chrome I set 'Disable cache' before loading the website.

In my website I have 4 Youtube videos (at the middle of the screen). When I scroll down a bit it will process the first two video, download the base.js. When I scroll more it will download base.js again and process the next two video. Is it possible that it will only ask for base.js one time only?

Also when I refresh the webpage it will download the sddefault.jpg but when I scroll down to the video it will download the maxresdefault.jpg (without changing the screen size). Is that the expected ? I have 4 video on my webpage it already consumes 2MB of the bandwidth (without clicking the play button). Seems it is not network friendly.

Current I am using [lazyYT](https://github.com/Daugilas/lazyYT) it only consumes 100KB of data (without clicking the play button, they just load the sddefault.jpg) for 4 videos, which makes the page load pretty fast. I understand AMP is targeted for user experience so I wish amp-youtube can shrink the bandwidth requirement which makes the AMP page mobile friendly.

Thanks a lot

**Comment by jridgewell** [comment]
> When I scroll more it will download base.js again and process the next two video.

You likely have cache disabled when the devtools are open. Mine are served from cache (first request is not because I hard refreshed).

![screen shot 2016-11-17 at 3 47 29 pm](https://cloud.githubusercontent.com/assets/112982/20406951/6a362a68-acdd-11e6-9564-5ef23d78d808.png)

> Also when I refresh the webpage it will download the sddefault.jpg but when I scroll down to the video it will download the maxresdefault.jpg (without changing the screen size). Is that the expected ?

We attempt to use the `sddefault.jpg` as the default placeholder, but not all Youtube videos have one. For those, we fall back to `hqdefault.jpg`.

You can sidestep this entirely by providing your own placeholder image:

```html
<amp-youtube
  data-videoid="..."
  width="480" height="270">
  <amp-img
    placeholder
    width="480" height="270"
    layout="responsive"
    src="https://placehold.it/480x270?text=Custom Placeholder">
  </amp-img>
</amp-youtube>

**Comment by winstonma** [comment]
@jridgewell actually there are one more issues here.

Please follow my steps to take a look

1. In chrome, open Dev Tools. Toggle the Device toolbar and choose any of the mobile device. Then go to the Network Tab.

2. Open [My Web Site AMP page](http://goalaheadltd.com/amp)

3. On the filter, set `i.ytimg.com`

4. Scroll down to the video section

You will see that the I have four videos and they loaded 8 images. Each of the `sddefault` image was initially loaded (with the web page), but when you scroll down to the video section then you will see that base.js and the `maxresdefault` image will be loaded. So totally for each video it loaded two images before the play button is being clicked. What I would expect is the same image will be served.

Secondly I think that since it is a mobile device, serving the `maxresdefault` image (which is 200KB in size) is not necessary, it is a waste in bandwidth and leads to poor mobile experience.
