### ISSUE TITLE
Implement allowLinker property to enable crossdomain analytics

### ISSUE THREAD

**Issue by commadelimited** [ampproject/amphtml#6230]
I'm being asked to add the `allowLinker` property to our amp-analytics implementation. The documentation makes no mention of how to apply it. 

The default GA implementation looks like this:

```
ga('create', 'UA-XXXXXX-X', 'auto', {
  'allowLinker': true
});
```

from https://developers.google.com/analytics/devguides/collection/analyticsjs/linker

Our current amp-analytics block (with account-id redacted). Can the team offer input on whether this functionality is enabled, and if so how to implement it?

```
<amp-analytics type="googleanalytics" id="analytics1">
    <script type="application/json">
        {
          "vars": {
            "account": "ACCOUNT-ID"
          },
          "triggers": {
            "OpenTicketModal": {
              "on": "click",
              "request": "event",
              "vars": {
                "cd12": 18899306334,
                "eventAction": "OpenTicketModal",
                "eventCategory": "listing-amp"
              },
              "selector": ".amp-t-ticket-lightbox"
            },
            "ContactOrgCancel": {
              "on": "click",
              "request": "event",
              "vars": {
                "cd12": 18899306334,
                "eventAction": "ContactOrgCancel",
                "eventCategory": "listing-amp"
              },
              "selector": ".amp-t-org-lightbox-close"
            },
            "ContactOrgAttempt": {
              "on": "click",
              "request": "event",
              "vars": {
                "cd12": 18899306334,
                "eventAction": "ContactOrgAttempt",
                "eventCategory": "listing-amp"
              },
              "selector": ".amp-t-org-lightbox"
            },
            "Directions": {
              "on": "click",
              "request": "event",
              "vars": {
                "eventLabel": "bicycling",
                "cd12": 18899306334,
                "eventAction": "Directions",
                "eventCategory": "listing-amp"
              },
              "selector": ".amp-t-directions-bicycling"
            },
            "trackPageview": {
              "on": "visible",
              "request": "pageview",
              "vars": {
                "cd12": 18899306334,
                "eventAction": "trackPageview",
                "eventCategory": "listing-amp"
              }
            },
            "ViewOrgProfile": {
              "on": "click",
              "request": "event",
              "vars": {
                "cd12": 18899306334,
                "eventAction": "ViewOrgProfile",
                "eventCategory": "listing-amp"
              },
              "selector": ".amp-t-org-profile-view"
            }
          }
        }
    </script>
</amp-analytics>
```

**Comment by commadelimited** [comment]
Followup: searching the code, I find no mention of the allowLinker property, so it looks like it’s not functional at this time.

**Comment by avimehta** [comment]
`allowLinker` is not yet supported in public version. Once https://github.com/ampproject/amphtml/blob/master/tools/experiments/experiments.js#L173 is released to public, linker can be supported.

Keeping this open but won't be doing any work till the experiment launches.

**Comment by 1987yama3** [comment]
Hi

Does cross-domain tracking implemented in future release versions? I would like to see the implementation content. Please tell me the Pull Request, Issue or commit.

Thanks.

**Comment by 1987yama3** [comment]
/to @avimehta Please tell me that above things...

**Comment by jridgewell** [comment]
@1987yama3: This has not been added yet. See https://github.com/ampproject/amphtml/issues/6230#issuecomment-261391475.

**Comment by 1987yama3** [comment]
@jridgewell It is written that it is implemented, but just not releasing it. Is it wrong?

**Comment by jridgewell** [comment]
The work for allowLinker has not been done. Before we start it, amp-fresh has to be released out of experimental.

**Comment by 1987yama3** [comment]
@jridgewell  Thanks. I have read [this issue #4191](https://github.com/ampproject/amphtml/issues/4191). But I think that it is not need <amp-fresh>.

If you implement allowLinker, you'd use url-replacements-impl.js. Can I try to implement it?

**Comment by jridgewell** [comment]
@avimehta?

**Comment by rudygalfi** [comment]
Putting this in the Pending 3P Implementation milestone since I think this is specific to Google Analytics. Please let me know if that's not correct.

**Comment by commadelimited** [comment]
I'm following up on this functionality. I recently heard that allowLinker, or some other way of linking cross domain traffic, had been added to amp-analytics. Per @erwinmombay's [comment](https://github.com/ampproject/amphtml/issues/4715#issuecomment-338813969) he indicates that this has been implemented via amp-bind. I'm reading through the documentation for amp-bind and I'm not finding any indication that cross-domain linking is allowed or supported yet.

Can someone confirm that this is working, and if so offer a link to some documentation on how to implement? Please and thank you!

**Comment by erwinmombay** [comment]
@commadelimited just to clarify, what i commented on was on the "amp-fresh" functionality which does not solve the cross domain traffic issue. I'll let the people more knowledgeable than me on this topic answer on how to solve this issue.

**Comment by commadelimited** [comment]
@erwinmombay gotcha. Sorry that I misunderstood.

**Comment by commadelimited** [comment]
Hey @avimehta checking in on this functionality. You indicated on [Nov 17, 2016](https://github.com/ampproject/amphtml/issues/6230#issuecomment-261391475) that `allowLinker` would be functional when the `amp-fresh` experiment was live. But in #4715 the ff was removed by @erwinmombay. Could you offer an update on the status of the allowLinker functionality for amp-analytics? Eventbrite has a number of TLDs and not having this functionality is playing havoc with our tracking and preventing us from rolling out AMP more completely.

Cheers.

**Comment by noerjeffries** [comment]
Hi all!

I'm working on some AMP pages for BiteSquad.com and have a scenario where we need cross-domain analytics between an AMP and non-AMP page. I found this thread, and it sounds like that functionality was in the works. :) Any update here?

Thanks!
-Noah

**Comment by rudygalfi** [comment]
@noerjeffries - I believe @commadelimited's original use case as well as the one you just described is covered by the Google AMP Client ID API released by Google Analytics. You can find the documentation for it here: https://support.google.com/analytics/answer/7486764.
