### ISSUE TITLE
Feature Request: Provide SOURCE_URL value in API data accessible from the amp-ad tag

### ISSUE THREAD

**Issue by jlucero-contentad** [ampproject/amphtml#6231]
Please provide the SOURCE_URL value in AMP API response available to amp-ad iframes. This value will make it easier to validate that the requesting page is the same as the publisher we currently have on file for our 3rd party ad serving service.

Best case scenario, the current page's query string parameters would be appended to the SOURCE_URL value to improve ad serving, but not required for basic validation.

**Comment by erwinmombay** [comment]
/to @avimehta @lannka please assign to the appropriate person to work on this

**Comment by jasti** [comment]
@jlucero-contentad can you use `window.context.canonicalUrl` from https://github.com/ampproject/amphtml/blob/master/ads/README.md#available-information to verify?

**Comment by jlucero-contentad** [comment]
@jasti we were concerned that the canonical URL tag may not always be present in the parent document. After reading your suggestion above, I looked more closely at the spec, and I see that the canonical URL is required. 
https://www.ampproject.org/docs/reference/spec#canon

That said:
How can we be sure that the canonical URL is in fact the parent article page and not some other page that the AMP page's author wants to highlight, such as the site home, category, search, or some advertisement?

**Comment by jasti** [comment]
If you don't trust the host, I believe you can use window.context.location. @lannka to confirm.

**Comment by jlucero-contentad** [comment]
@jasti, @lannka we are currently using `window.context.location`. The issue we are facing is that the location node must be parsed to remove the AMP CDN and path that precedes the source url. Since the CDN and path are variable, a bit of processing must take place for each amp-ad before an ad can be requested. Providing the source_url or alternately assuring that the cannonicalURL is in fact the current AMP page's parent would prevent that processing. 

Please take a look at lines 35-44 in our ad js to see what I mean.
https://github.com/ampproject/amphtml/blob/master/ads/contentad.js

**Comment by lannka** [comment]
@jlucero-contentad I don't see any problem to do that. This is not exposing extra data, it's just to make the 3P code easier and less error.

**Comment by lannka** [comment]
@jlucero-contentad it's done. please consider make corresponding changes in the 3p code.

**Comment by jlucero-contentad** [comment]
Thank you @lannka. Do you know which release this change might go out with? We can schedule our 3p code update to go out after that release date.

**Comment by lannka** [comment]
@jlucero-contentad i think you can just go with the change right now. So that they'll be cut in the same release. Unless you're talking about changes at your side.

The next cut is this Wednesday. And will go live next Thursday.

**Comment by jlucero-contentad** [comment]
I'd like to test the new source_url value against our 3p code and our ad API. For that reason, I'd like to wait until next Wednesday so I can test against the updated data. I'm sure it will be fine, but after all of the error handling problems we've had with our 3p code on our side, I'd rather play it safe.

**Comment by lannka** [comment]
That's fine. Just FYI you can do testing on canary release, which is this Wednesday, by opt-in to the [dev-chanel](https://github.com/ampproject/amphtml/blob/master/README.md#amp-dev-channel).

You can check [here](https://github.com/ampproject/amphtml/releases) for status. You're good to go once the PR gets into pre-release.
