### ISSUE TITLE
Prevent amp-form double submissions

### ISSUE THREAD

**Issue by weeblr** [ampproject/amphtml#6233]
I have a POST amp-form to add stuff to the cart, similar to:
````
<form class="cart" method="post" 
action-xhr="//local.web/product-123-page/amp/?action=add-to-cart" 
target="_blank">
	<input type="number" name="quantity" value="1" title="Qty">
	<input type="hidden" name="product_id" value="123"
        <button type="submit" class="button">Add to cart</button>
</form>
````
(markup simplified for clarity)

This works very fine, but if one clicks twice rapidly on the submit button, the following happens:

1 - The XHR request is started, adding one product to the cart (and eventually causing the display of a success message)
2 - While the XHR request is happening, the second click is handled, and the form gets submitted **a second time**. 
In addition, due to the target="_blank" attribute, a new tab is opened by the browser to complete the request. This tabs display the original page, without a success/failure message (as there was no XHR request done there).

Is there a way to suppress clicks handling until first XHR request has terminated, whether success or failure?

Thanks

**Comment by weeblr** [comment]
OK, answering to myself: one needs to use an
````input type="submit"````

instead of a button!

**Comment by mkhatib** [comment]
Yeah we do disable all `input[type=submit]` when the form is being submitted. Will look into disable button[type=submit] and see preventing submission in these cases.

**Comment by weeblr** [comment]
Hi

Thanks for considering. When you say you disable "all" `input[type=submit]`, do you mean on the entire page? or just inside the `form` that is submitted?

Rgds

**Comment by mkhatib** [comment]
Sorry I meant on the form being submitted yes.
