### ISSUE TITLE
Question about Google ad correlator 

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#6240]
how much entropy does the google ad correlator need? i saw we are not using the CID's full entropy.

CID has entropy of 128bit, but you only kept the digits, so it's 
```
10/64 * 128 = 20bit
```

If that's already enough for your use case, why bother to use CID, you can just use your random number.
Otherwise, you'll want to use a better base64 to number conversion to keep all the entropy.

See previous discussion here:
https://github.com/ampproject/amphtml/pull/6220#issuecomment-261093742

**Comment by jasti** [comment]
Ping @tdrl

**Comment by jasti** [comment]
ping @ampproject/a4a

**Comment by michaelkleber** [comment]
We're content with a 10-digit / 32-bit random number, which we're getting now from a combination of the pageViewIdNumeric and some of the entropy from the clientId.

We could indeed just use our own random number, but we wrote the code originally thinking we ought to use the runtime-provided notion of a pageview when possible.  Is there any problem with the current code?

**Comment by tdrl** [comment]
Yeah, the current implementation is historic, but seems to be meeting the needs.  We'd really, really rather not tinker it until after launch.  But even then, is there incentive to change it?  What's the motivation of this issue?

**Comment by jasti** [comment]
@lannka, closing for now - Please reopen if need more details.
