### ISSUE TITLE
Tests aren't isolated from one another, break when running a subset

### ISSUE THREAD

**Issue by taymonbeal** [ampproject/amphtml#6244]
When you run the entire AMP test suite, it passes, but when you run only the `amp-ad` tests, some of them fail. This suggests that they are leaking mutable state into one another in problematic ways.

## How do we reproduce the issue?

    gulp test --files=extensions/amp-ad/0.1/test/*.js

## What browsers are affected?

Thus far I've only run this against Chrome 54.

## Which AMP version is affected?

Git commit [a871915c441e5eb92cfff5ad8b9a94b48c202342](https://github.com/ampproject/amphtml/tree/a871915c441e5eb92cfff5ad8b9a94b48c202342) (the current `master` as of this writing)

**Comment by lannka** [comment]
Thanks for reporting. I'll take a look.

**Comment by bradfrizzell** [comment]
Any update on this?

**Comment by lannka** [comment]
duplicated with #6670
