### ISSUE TITLE
Duplicated extension script inserted

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#6253]
```html
<html amp>
  <head>
    ...
  </head>
  <body>
    <script custom-element="amp-analytics" src="xxx"></script>
     ...
  </body>
</html>
```  

When AMP runtime tries to render the above HTML, another script for amp-analytics will be inserted into `<head>` section.

It's because the code [here](https://github.com/ampproject/amphtml/blob/master/src/custom-element.js#L156) scans whole document to find extensions in use. However, when it tries to add missing scripts for extensions in use, it only checks `<head>` ([code](https://github.com/ampproject/amphtml/blob/master/src/service/extensions-impl.js#L503)).

It's not necessarily considered as a bug, because such a doc with `<script>` inside `<body>` is invalid AMP. However, the consequence here is a bit weird so we should consider changing the code to always scan `<head>`.

@dvoytenko

**Comment by lannka** [comment]
This is related to #5700 . This causes problem when AMP document get rendered inside a SafeFrame implementation like [this one](http://output.jsbin.com/xehinez).

So to minimize the impact (duplicated script error), we might always scan whole document for extensions .

It will not solve any potential rendering issue though. If any extension script in body isn't parsed during our initial scan, the corresponding AMP element will not be rendered.

@dvoytenko thoughts?

**Comment by dvoytenko** [comment]
@lannka The situation is a bit complicated by the fact that even w/o scan, the extension will still self-register. In this SafeFrame case, is it unavoidable that an extension would be registered in the head? We can certainly expand script search to look throughout in the body, but I'd like to understand the source of the issue in general.

**Comment by lannka** [comment]
Discussed offline. The duplicated script bug can be fixed by always scan `head`.

Extensions inserted in `<body>` will still register themselves after loaded. The problem is that at the time of extension scanning (body load), we don't know those extensions are in use, hence will not layout them immediately. In worst case, it can cause UX problem such as a "page sudden jump". This has to be addressed at SafeFrame side.
