### ISSUE TITLE
Make checkbox-hack legal in amp html

### ISSUE THREAD

**Issue by Download** [ampproject/amphtml#6259]
I wonder whether you would consider making the checkbox hack a legal construct in amp?

The [checkbox-hack](https://css-tricks.com/the-checkbox-hack/) is a construct that enables pure css to style interactive elements such as drawers, popup menus, modals etc. Anything really that requires a toggle.

Currently i believe it is not possible to use this construct within amp because the checkbox is not legal to use. This is a shame as this technique is a powerful trick in the arsenal of devs trying to build progressive web apps. It serves the same kind of goals that amp strives for.

Would you consider allowing checkbox for this purpose?

**Comment by jridgewell** [comment]
I believe this falls into the same bucket as https://github.com/ampproject/amphtml/issues/1032.

**Comment by Gregable** [comment]
Also, the checkbox input type is legal. It wasn't in the past, and there was a period where it was only legal inside a `<form>` element, but now you should be able to use it in any context, which should allow you to use the CSS trick you describe. You can try it out on https://validator.ampproject.org/

**Comment by Download** [comment]
> Also, the checkbox input type is legal.

Woot woot!! That's great news! I was under the impression that it was a restricted element. Thanks!
