### ISSUE TITLE
amp-access div content is not showing after success login and authorization endpoint in android 4.4.2 system browser

### ISSUE THREAD

**Issue by boddukiran** [ampproject/amphtml#6260]
amp-access component authorization data is not displaying after successful login in android 4.4.2 system browser.  It is fine in Desktop.

**Comment by jridgewell** [comment]
Do you have a test page that we can use?

**Comment by boddukiran** [comment]
Please check this in android system browser 4.4.2 https://212.71.233.89/amp-access

Step 1: Go to https://212.71.233.89/amp-access
Step 2: Click on "Login" and type same "username" and "password" then click "login"

**Comment by dvoytenko** [comment]
@boddukiran Hmm. I tried a few times on stock browser in KitKat and everything worked as expected. One time I made a mistake and stayed on the page with `?logout=1` and that, of course, automatically logged me out. But every time I started on `/amp-access/` page, I went through a redirect dance and got on the correct state.

**Comment by boddukiran** [comment]
@dvoytenko I am having the same issue with google chrome browser, which i installed on android phone.  I am not sure it is due to android OS or anything.  I tested it in i-Ball andi.

**Comment by dvoytenko** [comment]
Are you sure that your backend always responds correctly with the authorization response post login? Are caches or eventual-consistency issues possible?

To avoid any possibility of the client cache, I'd recommend adding a random value to the authorization URL. E.g. `?...&_=RANDOM`

**Comment by boddukiran** [comment]
@dvoytenko you can give a try to check this https://ampbyexample.com/components/amp-access/ one.  I have same issue after i authenticate it redirects but i still see the login link instead of logout.

**Comment by dvoytenko** [comment]
Hi @sebastianbenz @andreban! I've had really hard time reproducing it on ampbyexample.com. Could you try?

**Comment by sebastianbenz** [comment]
@dvoytenko works for me as well
@boddukiran can you [debug Chrome on Android](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/) and check if there are any errors in the console.

**Comment by dvoytenko** [comment]
@sebastianbenz I think this is only the stock browser. Is it possible to connect DevTools to the stock browser?

**Comment by adelinamart** [comment]
Is this still an issue? Thanks.

**Comment by adelinamart** [comment]
@dvoytenko @sebastianbenz what's the latest status here? Thanks

**Comment by dvoytenko** [comment]
Not reproducible.

**Comment by dvoytenko** [comment]
Please re-open if repro case is found.
