### ISSUE TITLE
[AMP: make-body-relative] Scroll performance diminishes after device has been on standby mode

### ISSUE THREAD

**Issue by ansalgado-gcorp** [ampproject/amphtml#6264]
## Short description of your issue:
The performance of the scroll diminishes considerably if user returns to experience after phone has been on standby mode (resting).

## How do we reproduce the issue?

Open a URL on any of the covered browsers. Scroll a few times to activate the hiding header. Place the phone on standby, and return to the experience and scroll again.

URL: https://www.google.com/amp/retail.economictimes.indiatimes.com/amp/news/e-commerce/e-tailing/paytm-app-crosses-50-million-downloads-on-google-play-store/55428150

## What browsers are affected?

Chrome, AGSA

What device type?
Samsung S4, KitKat

**Comment by jridgewell** [comment]
This is likely a duplicate of https://github.com/ampproject/amphtml/issues/6263.

**Comment by dvoytenko** [comment]
YEs. Duplicate.
