### ISSUE TITLE
Google AMP: Header shows over Doc's Header

### ISSUE THREAD

**Issue by sadapala** [ampproject/amphtml#6267]
## Short description of your issue:
In stock  browser, Header is broken in AMP version and cannot see the header for AMP viewer version

## How do we reproduce the issue?
Open a URL on any of the stock browser. 
Header broken in AMP version
Cannot see any header for AMP viewer version

## What browsers are affected?
Stock browser

All browsers? Some specific browser? What device type?
Samsung galaxy noteII -JB 

## Which AMP version is affected?

Is this a new issue? Or was it always broken? Paste your AMP version. You can find it in the browser dev tools.

**Comment by sadapala** [comment]
[
![jb_amp_av](https://cloud.githubusercontent.com/assets/23534205/20497808/76db7070-afdf-11e6-9ff9-7fddc085a03b.png)
![jb_amp_avv](https://cloud.githubusercontent.com/assets/23534205/20497814/7c5ec04c-afdf-11e6-9144-c191dc58c378.png)

](url)

**Comment by ericlindley-g** [comment]
@sadapala Does this only happen when the make-body-relative experiment is enabled?

/to @dvoytenko

**Comment by jridgewell** [comment]
This one's very likely Google hide-a-header. I'll be assigning RJ as soon as he makes a Github account.

**Comment by sadapala** [comment]
I can see same with experiments enabled and disabled.

**Comment by jridgewell** [comment]
@rjsumi

**Comment by jridgewell** [comment]
> I can see same with experiments enabled and disabled.

I've updated the title, and assign @rjsumi.

**Comment by camelburrito** [comment]
@sadapala please file bugs against the experiment if it is broken only when the experiment is enabled.  You must file bugs for other broken things (do not mention experiments here). If an experiment is mentioned in a bug it might be easily overlooked, and we might miss an actual error you had caught on prod.

**Comment by adelinamart** [comment]
Is this something we still need to work on? Thanks

**Comment by jridgewell** [comment]
@muxin: I believe you worked with the Google Viewer header. This might be related to https://github.com/ampproject/amphtml/issues/7283.

**Comment by aghassemi** [comment]
Ran a quick test on Chrome/Android and ET Telecom articles do not repro this issue anymore, closing. Please feel free to reopen if my assessment is wrong.
