### ISSUE TITLE
AMP not working

### ISSUE THREAD

**Issue by Warond** [ampproject/amphtml#6272]
## How do we reproduce the issue?

www.fadeawayworld.com

http://fadeawayworld.com/2016/11/20/under-armour-loses-600-million-in-value-because-of-stephen-curry-basketball-shoes/

AMP worked until a few days ago. Now, new articles are not in the AMP.

## What browsers are affected?

Smartphone, any browser.

## Which AMP version is affected?

This is a new issues. Can you please check everything on my site: www.fadeawayworld.com

Kind Regards

**Comment by jridgewell** [comment]
This isn't an AMP issue. If you're not serving AMP documents, then there's nothing we can do.
