### ISSUE TITLE
[amp-analytics] loadTimeVisibility not working as expected

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#6279]
the current algorithm is:
```
initialIntersection = rectIntersection(
  [0, 0, viewport.width, viewport.height], 
  [intersect.left, intersect.top, element.width, element.height]
);
```

it's wrong because 
1) the `intersect.left` and `intersect.right` from an IntersectionObserverEntry is relative to viewport. But we here want relative to document.
2) To be more accurate, it should rather be `element.left` and `element.top`.

Probably the regression was introduced similarly as #5916.

@avimehta FYI

**Comment by jridgewell** [comment]
Why isn't it just using the `intersect` as is?

**Comment by lannka** [comment]
@jridgewell it was try to infer the initial intersection on pageload.

**Comment by avimehta** [comment]
hmm. We should fix that. To figure out what other regressions we might have introduced, is there some kind of test that would catch bugs like this. This is something that we should do for both visibility and visibility-v2.

**Comment by lannka** [comment]
@avimehta instead of calculating the initial intersection this way, can we just take the 1st intersection as the initial intersection if it's within 500ms of the page load?
