### ISSUE TITLE
Safari WebCrypto does not support `spki`

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#6292]
in `jwt.js` `isVerificationSupported` returns `true` for browsers that support the `subtle` API BUT the key format that `jwt` expect is `spki` which Safari does NOT support. So Ideally `isVerificationSupported` should have returned false in Safari. https://bugs.webkit.org/show_bug.cgi?id=129978

**Comment by aghassemi** [comment]
@dvoytenko We should be able to go from `PEM` to `jwk` instead of `spki` so we can use subtle API in safari as well right?

**Comment by dvoytenko** [comment]
What's the future Safari support looks like? This feature is needed for development only so it's low risk as it stands. But would be good to know what the future looks like for Safari in this regard. `spki` is in spec, I'm pretty sure.

**Comment by aghassemi** [comment]
Outlook is grim :) someone asked the same on https://bugs.webkit.org/show_bug.cgi?id=129978 few months ago, no reply. Bug has been open since 3/2014. I added a comment as well, maybe that triggers a response.

**Comment by aghassemi** [comment]
There is some activity on https://bugs.webkit.org/show_bug.cgi?id=129978  looks like it is happening: https://bugs.webkit.org/attachment.cgi?id=296223&action=diff maybe outlook was not so grim afterall!

**Comment by adelinamart** [comment]
Bug mentioned seems to be fixed. @aghassemi is there anything else to be done here? Thanks

**Comment by aghassemi** [comment]
@adelinamart, nothing I can think of. It should just work when that Safari bug fix makes it to a release ( if it hasn't already). Closing.
