### ISSUE TITLE
Add validation for amp-selector

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#6297]
https://github.com/ampproject/amphtml/blob/master/extensions/amp-selector/amp-selector.md#behavior

**Comment by camelburrito** [comment]
also we need to white list amp-selector inside forms

**Comment by camelburrito** [comment]
@mkhatib - amp selector can have any elements (including amp-extensions), is the same true with a form?

**Comment by Gregable** [comment]
The doc doesn't mention requiring a new extension file (ie: amp-selector-0.1.js). Is this going to be a built-in or will it require a javascript include?

**Comment by Gregable** [comment]
A few other questions: 

Will `amp-selector` be supported as an `AMP4ADS` format? 
Is `amp-selector` allowed inside an `amp-sidebar` element?
The spec mentions that all layouts are allowed. Is this really accurate? For example, `nodisplay` makes no sense.

**Comment by camelburrito** [comment]
This is not a built in - the doc will be updated. 

>> Will amp-selector be supported as an AMP4ADS format?
@lannka  can you answer this?

>> Is amp-selector allowed inside an amp-sidebar element?
I dont think we need to whitelist it now (Dont really see the use-case ), if needed we can whitelist it later.

>>The spec mentions that all layouts are allowed. Is this really accurate? For example, nodisplay makes no sense.

yes it allows all layouts - there is no upside to no letting nodisplay. I only see it as an additional overhead in validation.

**Comment by Gregable** [comment]
- We currently don't allow the `form` attribute for the `<select>` element, but it sounds like we would allow it for `<amp-selector>`. Should we also allow it for `<select>`.
- Should we allow `disabled`, `selected` attributes on any descendant element of `<amp-selector>` or only allow them if the `option` attribute is present?

**Comment by camelburrito** [comment]
>>We currently don't allow the form attribute for the <select> element, but it sounds like we would allow it for <amp-selector>. Should we also allow it for <select>.

@mkhatib why did we disallow the form attr on select?

>>Should we allow disabled, selected attributes on any descendant element of <amp-selector> or only allow them if the option attribute is present?

Only on ones with option attribute would be good - remember since selector can contain any html they might have some elements that are not selectable but have valid uses for `disabled` and `selected`

**Comment by Gregable** [comment]
Validation is in place in github, though not live yet.

**Comment by Gregable** [comment]
This should be live everywhere in an hour or two.
