### ISSUE TITLE
proof read amp-selector documentation and prepare for Docs launch

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#6298]
https://github.com/ampproject/amphtml/blob/master/extensions/amp-selector/amp-selector.md#behavior

**Comment by ericlindley-g** [comment]
Looks great—thanks @camelburrito and @bpaduch !

One thing: may want to change "All" in supported layouts to list each of them individually. This might be more future-proof if another layout type gets added that this doesn't support, and is in keeping with how other component list. Thoughts?

**Comment by bpaduch** [comment]
I thought about that too, but I wasn't sure if <amp-selector> was the "super" selector and would support ANY layout.  I'm cool with changing it to be consistent w/ other docs.

**Comment by rudygalfi** [comment]
Is there an AMP By Example update planned? @ericlindley-g

**Comment by camelburrito** [comment]
Already on ABE

**Comment by rudygalfi** [comment]
So it is! Somehow missed it earlier. Thanks for confirming.
