### ISSUE TITLE
Why try-catch in v0.js?

### ISSUE THREAD

**Issue by mathiasrw** [ampproject/amphtml#631]
What is the reason the frist 15Kb of v0.js is in a (big) try-catch structure?

its rare to see big chuncks of code in a try-catch constellation - as I expect amphtml to have been create by some pretty good minds I would like to learn the reasoning behind the choise.

**Comment by cramforce** [comment]
This is related to #323

The script needs to make sure that under all circumstances does it get to setting opacity on the body.

**Comment by mathiasrw** [comment]
:+1:
