### ISSUE TITLE
Integration tests failing in Safari 8 after #6227

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#6312]
`ReferenceError: Can't find variable: performance`

`performance` API does not exist in Safari 8. So you probably need to polyfill `time: performance.now(),` in `intersection-observer-polyfill.js` with `Date().now()`

/to @zhouyx 
/cc @jridgewell

**Comment by jridgewell** [comment]
Could just do `time: performance ? performance.now() : Date.now()`

**Comment by zhouyx** [comment]
But that would return the wrong value. Do we still want to polyfill performance.now()?

**Comment by aghassemi** [comment]
man, apparently `performance.now` is NOT a high-precision version of `Date.now`. It is elapsed time since navigation start...) ugh, horrible name...

**Comment by aghassemi** [comment]
oh and `time: performance ?` won't work and will through the same error. Needs to be `time: typeof performance !== 'undefined')`

**Comment by jridgewell** [comment]
Oh yah, forgot about the realative timestamp. Polufilling should be about 5 lines, lets go with that.

**Comment by lannka** [comment]
wondering when can we stop supporting Safari 8.... our official statement is to "support the latest 2 versions of a vendor browser"
