### ISSUE TITLE
Discussion on Origin mismatch in Url-replacement

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#6338]
`url-replacement` doesn't allow protocol to change during the replacement process, do we also need to enforce this for `origin`?

@jridgewell what was the reasoning behind enforcing the protocol mismatch and is it needed for origin?

**Comment by jridgewell** [comment]
Limiting the protocol is a security concern, the origin is not. IE, the validator forbids `javascript:` protocols, but if we allowed protocol changes we could easily use `url-replacements` to side-step.

**Comment by dvoytenko** [comment]
/to @cramforce Did we ever envision being able to update hostname with variables? Is that a valid use cases?

**Comment by cramforce** [comment]
Its actively done in `amp-analytics` for sure (page config provides host name to be used in otherwise vendor config provided URL). If there is concern, we could make it optional per use case.
