### ISSUE TITLE
[amp-analytics]  visiblePercentageMin in visibility spec does not default to 0

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#6339]
In the VisibilitySpec, if `visiblePercentageMin` not specified, visibility trigger fires as soon as the element laid out by runtime (not necessarily in viewport).

Is this a valid use case? Not sure if this metric (# of times an element get laid out) can be useful to pub, as this metric can suddenly change due to any change made in AMP runtime. For example, right now we lay out elements within 3 viewports. If we ever want to reduce this number, the metric will have a sudden drop.  
 
On the other hand, it's confusing because I would think `visiblePercentageMin` defaults to `0`. And I don't see it documented in the spec either.

Should we fix the behavior, or fix the doc?

**Comment by dvoytenko** [comment]
I agree. We should default it to `0`.

**Comment by lannka** [comment]
If everyone agrees that we should default to 0, I will make it in the VisibilityV2 impl.

I'll let @avimehta to decide if we want to fix the current impl.
