### ISSUE TITLE
[amp-live-list] don't test the value of data-sort-time

### ISSUE THREAD

**Issue by okeul** [ampproject/amphtml#6341]
Hello,

We can read in the documentation :

> **data-sort-time (Required)**
Timestamp used for sorting entries. Higher timestamps will be inserted before older entries. We recommend using Unix time (the number of seconds that have elapsed since Thursday, 1 January 1970).

But in [ampbyexample](https://ampbyexample.com/components/amp-live-list/), the format is not correct (it's not an unix time) :
> data-sort-time="20161123175121"

I try to put some random integer in this attribute and it works : http://output.jsbin.com/yadefeb#development=1

So it will be good to test if the value of data-sort-time attribute is a true unix time.

**Comment by ericlindley-g** [comment]
We made a recommendation in the docs, but have avoided being prescriptive w/r/t the date format. I'm inclined to keep it open (as-is) unless there's a problem that more restrictions would solve.

/cc @erwinmombay for thoughts

**Comment by erwinmombay** [comment]
hmm i don't feel very strongly having to validate it but if we were I'd rather we do it on the validator end

**Comment by ericlindley-g** [comment]
Closing this for now, but @okeul , let us know if the lack of validation causes an issue and we can think through the cost/benefit of validation.
