### ISSUE TITLE
Add phone number validation to forms

### ISSUE THREAD

**Issue by winstonma** [ampproject/amphtml#6345]
I went through the [AMP Example - Form](https://ampbyexample.com/components/amp-form/preview/) and try that on my PC. I found that in the phone section I can type any character and the submission is still success.

As when I open the page on phone it only allows me to use the numpad, I would assume the telephone field would only allows numbers.

**Comment by aghassemi** [comment]
/to @mkhatib we may want to default the `pattern` to `[0-9-+s()]*` if no pattern is specified.

@winstonma The `tel` input type does not really validate that the entered value is a valid phone number because phone number patterns vary by country. Your point about it not allowing letters is valid though. If you like to validate actual phone number patterns, please use the `pattern` attribute. Here are a few example regular expressions for phone number patterns in US, UK and France: http://html5pattern.com/Phones

**Comment by winstonma** [comment]
Thanks @aghassemi 

I guess very generic number-only checking already avoid lots of error.

**Comment by rudygalfi** [comment]
My understanding is that none of the form types (email, telephone, etc.) will cause validation to happen, they just vary the keyboard that's exposed on mobile. As @aghassemi stated, I think we want to leave validation to mechanisms like `pattern`, which can account for the complexity of validating various international telephone number patterns. We don't have any plans currently to build such logic into AMP.

**Comment by mkhatib** [comment]
@rudygalfi `type=email` does validate the input to look like an email. So you can't submit a form with an email input value `Hello`, it has to be something like `Hello@there` or `Hello@there.yo`

**Comment by rudygalfi** [comment]
@mkhatib Did you have to define those validations within AMP, or are they handled natively by the HTML element? If there's a standardized definition for a phone number that we could use to apply some validation, then I'd be comfortable with that. We just need to be careful that we don't introduce incorrect validation if we need to build it ourselves.

**Comment by mkhatib** [comment]
Natively. AMP does not define any validation rules. It just relies on the browser implementation to `checkValidity`.

**Comment by rudygalfi** [comment]
Thanks for clarifying. So there is a consistent story here, which is that AMP itself doesn't provide any validation logic (apart from a developer specified `pattern`). I'll leave this issue open to track whether we ever want to go this route, but I think the `pattern` approach is a good one for now.

**Comment by aghassemi** [comment]
number, regex and recent [server-side async validation](https://github.com/ampproject/amphtml/blob/master/extensions/amp-form/amp-form.md#verification-experimental) should cover this use-case fairly well. Closing.
