### ISSUE TITLE
Adding 3d party caching proxy to config.urls.cdnProxyRegex

### ISSUE THREAD

**Issue by cgorbit** [ampproject/amphtml#6355]
Hi!

Under what conditions 3d party caching proxy host can be added to cdnProxyRegex in https://github.com/ampproject/amphtml/blob/master/src/config.js#L35 ?

**Comment by cramforce** [comment]
@cgorbit The idea is that the cache serves its own version of AMP and changes these values itself.

**Comment by cgorbit** [comment]
But why there are so many places in code where cdn.ampproject.org host is hardcoded?

**Comment by dknecht** [comment]
We have removed almost all of them that matter?  Which ones are you referring to?  Also remember that you need to do server side validation and rewrites for a cache.

**Comment by cgorbit** [comment]
Sorry, I was wrong, they don't matter. Maybe only in validator*.protoascii (or you mean, that I must rewrite cdn.ampproject.org in html too while caching?)

**Comment by cramforce** [comment]
Correct. Validation requires `cdn.ampproject.org` URLs, but caches do not need to output valid AMP documents (they only need to ingest valid AMP documents)

**Comment by cgorbit** [comment]
Thank you!
