### ISSUE TITLE
Intent to Implement: <amp-addthis> Extension

### ISSUE THREAD

**Issue by jacobdfriedmann** [ampproject/amphtml#6360]
The goal is to create an extension for [AddThis](http://addthis.com) website tools (sharing buttons, follow buttons, related posts, etc). The tools are configurable on the AddThis dashboard and would be placed on an AMP page using an API that looks something like:

```
<amp-addthis
    height=100
    width=300
    pubId="ra-123456778"
    widgetId="12345"
>
</amp-addthis>
```

**Comment by cramforce** [comment]
I'd very strongly prefer if this could be implemented similar to https://github.com/ampproject/amphtml/blob/master/extensions/amp-social-share/amp-social-share.md without an iframe (and without iframes for certain share widgets).

I think the classic share stuff coming from desktop needs to be re-thought for mobile. 

Is there currently a "zero except some HTML overhead" version of AddThis? If not, could such a thing be build and used for AMP?

**Comment by jacobdfriedmann** [comment]
Dynamic configuration through the AddThis dashboard, auto-personalization of services, and analytics tracking are all key parts of the AddThis tools that would rely on an iframe/embed implementation.

There is not a "light" version of the AddThis client and for the reasons stated above, I'm not sure if it makes a lot of sense for us to create one at this time.

I'm of course interested in other points of view if there are things I'm not considering. Thanks!

**Comment by cramforce** [comment]
Do you allow iframe based share buttons? Could AddThis in AMP be limited to not allow those?

What is the overall size of the JS loaded into the AddThis iframe? How many milliseconds does it take to run it on a 2015 era Android phone?

**Comment by cramforce** [comment]
Note, that stuff like "dynamic configuration via a dashboard" is nice in terms of developer experience, but if it cannot be implemented efficiently it might violate this guideline https://github.com/ampproject/amphtml/blob/master/DESIGN_PRINCIPLES.md#user-experience--developer-experience--ease-of-implementation

**Comment by jacobdfriedmann** [comment]
One of our tools does allow iframe based sharing buttons, but that could potentially be disabled for the AMP version.

The total size is dependent on the tool being used, but it starts at around 130kb gzipped and we're always working to slim it down. I don't have the milliseconds to render on an Android device handy, but I'll dig that up for you.

Re: user experience > dev experience; That makes sense to me, I'm hopeful we can find a solution that does both.

**Comment by jacobdfriedmann** [comment]
Render time is around 600ms on 2015 Android device including configuration loading time and other assets (svgs primarily).

We've been working on a potential implementation here: https://github.com/jacobdfriedmann/amphtml/commit/ff53b8af396880f36a49b757457ff7295dee90e4

**Comment by ericlindley-g** [comment]
Thanks @jacobdfriedmann — Let us know when you're ready for feedback on your impl. Typically developers start a PR in this amphtml repo so the team can comment there.

**Comment by cramforce** [comment]
@jacobdfriedmann lets see how this goes. We will have to be careful with the performance impact. It seems that at least on Android `navigator.share` will be all that people would want. I've rarely seen a native app do anything else than that.

**Comment by jacobdfriedmann** [comment]
Hi @cramforce — Hope your 2017 is off to a nice start.

We’ve found publishers to be pretty drawn by the benefits AddThis share tools offer beyond navigator.share and the included buttons. The ability to personalize the look and feel of buttons, access to analytics, and influence over the sharing experience are a few meaningful features. Not to mention that we hope to eventually bring our whole suite of tools (related posts, follow tools, etc) to AMP. Some 15 million domains use AddThis tools, including ~15% of the top 10K sites (according to builtwith.com).

Still, we’re working on a much lighter version of our JS client specifically for AMP to ease some of the performance concerns. Hoping to have a PR ready to test soon.

**Comment by cramforce** [comment]
@jacobdfriedmann Sounds great!

**Comment by adelinamart** [comment]
@jacobdfriedmann any news here? Thanks

**Comment by jmrog** [comment]
Hi, everyone. It's been a while since much has happened on this issue, so I wanted to jump in and say that AddThis is hoping to finally submit a PR for it very soon. I'm actually the one intending to do that, since @jacobdfriedmann has (alas) moved on to other things.

Before I _do_ submit the PR, I wanted to make a couple of quick comments about two related things mentioned earlier in this thread:

1. @jacobdfriedmann mentioned at one point that the JS initially loaded into the AddThis iframe was around 130kb gzipped. I'm happy to report that, in the time since he said that, we've completed the necessary work on a lighter version of our JS client, such that the JS initially loaded into the iframe is now around only 38kb gzipped -- a big improvement.

2. @cramforce had some concerns about whether AddThis in AMP could be limited to not allow our iframe-based sharing buttons. I'm also happy to report that the lighter version of our JS client does not allow those buttons in the first place (even outside of AMP), so they will _ipso facto_ not be allowed here.

I hope this is helpful, and I hope to have the PR ready very soon.

**Comment by cramforce** [comment]
Awesome! Looking forward to the PR!

**Comment by mrjoro** [comment]
It looks like this was added in #11381.  Please reopen if there's anything left here.
