### ISSUE TITLE
Allow `amp-accordion` to have `disable-session-states` attribute

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#6368]
Need validator change for `amp-accordion` to support `disable-session-states` attribute.
The format will be
```
<amp-accordion disable-session-states>
   ...
</amp-accordion>
```

**Comment by honeybadgerdontcare** [comment]
The PR #3852 related to this is merged and closed already so I'll mention this here. I noticed the [markup](https://github.com/ampproject/amphtml/blob/master/extensions/amp-accordion/amp-accordion.md) file is not updated with the details of this attribute.

**Comment by zhouyx** [comment]
@honeybadgerdontcare aware of this. Will update the doc once the change and validator are alive in prod

**Comment by honeybadgerdontcare** [comment]
This is now on github, but isn't live in prod. #6391

**Comment by honeybadgerdontcare** [comment]
This is now live in prod.
