### ISSUE TITLE
Mitigating superfluous imports of extended components

### ISSUE THREAD

**Issue by jmadler** [ampproject/amphtml#637]
In some cases, AMP documents are importing extended components they're not actually using in the document.  Even though the async tag and caching are used, this can still negatively impact performance.

The simplest mitigation effort here is to add a validation rule to invalidate docs with these tags, but this can be hard to use in cases where templating engines use a "header" and "footer" files that are the same throughout the site.

Is there a way to request import of these extended components without actually making the network request unless the tag is used?

**Comment by cramforce** [comment]
Nope, not possible without performance impact. We could decide to take the performance hit. Would likely make extended components about 200-500ms slower.

The thing we can definitely do is allow insert the script tags anywhere in the document, so they do not have to go into the `<head>`

**Comment by jmadler** [comment]
That makes sense.  So we should modify the spec/validator/docs to reflect:

* <script> tags for extended component imports can be anywhere in the document.
* <script> tags for extended component imports are not allowed unless the extended component is found at least once in the document.
* Multiple <script> tags for the same extended component are disallowed.

**Comment by rudygalfi** [comment]
Closing since we won't prioritize at this time. cc @bpaduch
