### ISSUE TITLE
Support dynamic phone call conversion tracking 

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#6370]
Ability to dynamically replace an input phone number with a system generated phone number, in order to track phone (in the backend) call conversions driven from a specific campaign.

Two consumers so far: 
1. Adwords Call Conversion - https://support.google.com/adwords/answer/6331304
2. Inifinity Call Tracking - https://www.infinitycloud.com/call-tracking

**Comment by lannka** [comment]
@jasti are we talking about a phone number on an AMP creative or on an AMP document?

**Comment by jasti** [comment]
Document. Primarily for landing page conversions.

**Comment by rudygalfi** [comment]
How does this compare to #5276?

**Comment by jasti** [comment]
Dupe of #5276.
