### ISSUE TITLE
Google Analytics parameter "ni"(nonInteraction) support.

### ISSUE THREAD

**Issue by 1987yama3** [ampproject/amphtml#6372]
## Short description of your issue:
In [Google Analytics Field Reference](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference), there is exist "ni"(nonInteraction) parameter. But this parameter is not exist [vendors.js](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/vendors.js).

I think that it is a parameter to suppor in vendor.js.

## Which AMP version is affected?
version 0.1

## Example

```
'googleanalytics': {
  'vars': {
    ...
    'nonInteraction': '', // Add
  },
  'requests': {
    'host': 'https://www.google-analytics.com',
    'basePrefix': 'v=1&' +
        ...
        'de=${documentCharset}' +
        'ni=${nonInteraction}',   // Add
    'baseSuffix': '&a=${pageViewId}&' +
        'z=${random}',
    ...
},
```

**Comment by avimehta** [comment]
@1987yama3 You should be able to do this using following snippet:

```
'extraUrlParams': {
  'ni': 'true'
}
```

let me know if this works...
