### ISSUE TITLE
Remove amp-form-var-sub and amp-form-var-sub-for-post experiment

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#6377]
Cleanup issue for 
- [ ] amp-form-var-sub 
- [ ] amp-form-var-sub-for-post

**Comment by mkhatib** [comment]
Reopening to remember to clean the launch configs in couple weeks.

**Comment by aghassemi** [comment]
Putting in next sprint. Launched https://github.com/ampproject/amphtml/pull/7647
