### ISSUE TITLE
Amp-analytics & amp-ad (adsense) issue

### ISSUE THREAD

**Issue by dmitrymotorin** [ampproject/amphtml#6379]
Hey guys,
We've added amp-analytics to our amphtml pages. Also we've added amp-ad (adsense).
At "Google Analytics" account we receive pageviews stats but on the Publisher-Overview section we got zero stats. Is it something wrong with the amp-analytics?
Page example: http://womanitely.com/ecofeminism-change-world/amp-list/
Publisher-Overview section screenshot: 
<img width="1382" alt="screen shot 2016-11-29 at 1 26 57 pm" src="https://cloud.githubusercontent.com/assets/6582420/20709240/c2ac9b9c-b63c-11e6-98c4-9cf03be7c225.png">

**Comment by dmitrymotorin** [comment]
guys, are there some updates according this issue?

**Comment by jasti** [comment]
Ping @avimehta. 
@dmitrymotorin, think it would help reaching out directly to GA support for this. AFAIK, the GA reporting from amp-ad is all done in the adsense backend in an offline way.

**Comment by avimehta** [comment]
Update from GA side: Working on fixing this. Once the PR gets submitted, we will have to way up to 14 days for release.

**Comment by avimehta** [comment]
Note that although the bug is closed, it will take about 14 days to rollout globally.
