### ISSUE TITLE
Get data on the rough memory cost of an empty iframe

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#638]
On Android/Desktop Chrome and iOS.

Something make a sample page with 1-10 iframes that just load `about:blank`. Check system for total memory usage.

**Comment by jaboc83** [comment]
I don't have access to an iOS device currently, but I got some numbers on Chrome Desktop this morning: https://drive.google.com/file/d/0B3wnnHvwiclcZkNWS3VaRTVwUlE/view?usp=sharing

**Comment by dvoytenko** [comment]
Time wise I see a lot of references that IFrame creation takes about 100ms on mobile. This http://jsperf.com/iframe-creation-cost shows that creating an iframe is about 40-50 times slower than any other DOM element.

**Comment by rudygalfi** [comment]
If the data shared in this issue is sufficient, let's keep this closed. Else we can re-open for further investigation.

**Comment by cramforce** [comment]
I'd like to keep this open. @jaboc83's data is awesome, but I'd like to complete that with data from various mobile devices.

**Comment by adelinamart** [comment]
@cramforce @mrjoro are we still considering this as a candidate for a first issue? Thanks
