### ISSUE TITLE
Tumblr in amp-social-share gives "Banned" URL

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#6380]
When opening Tumblr, I get a page with link: https://www.tumblr.com/widgets/share/tool/banned?
Go to [sample](https://chiara-ampbyexample.appspot.com/components/amp-social-share/), click on the tumblr icon on the right.

## What browsers are affected?

Chrome

## Which AMP version is affected?

1478272520861

**Comment by jridgewell** [comment]
It's because of the canonical URL you're using (http://localhost:8080/components/amp-social-share/). Tumblr apparently bans that from being a share url.
