### ISSUE TITLE
A4A Cross Domained AMP Creatives Click URL Does Not Replace X/Y

### ISSUE THREAD

**Issue by keithwrightbos** [ampproject/amphtml#6385]
## Short description of your issue:

A4A dynamically replaced CLICK_X/CLICK_Y for any links within its friendly frame upon click for AMP creatives.  However, it is possible that AMP creatives can be cross domained if they could not be verified client-side (or failed server-side validation).  Need to ensure that CLICK_X/CLICK_Y occurs in this situation.

Original design placed CLICK_X/CLICK_Y replacement on document for all AMP documents but was moved into amp-a4a.js by @cramforce  We need it to exist in the cross domained AMP creative case as well (likely as part of amp-inabox effort).

**Comment by lannka** [comment]
@keithwrightbos so we want to make it available for the whole AMP document?

I saw the CLICK_X/Y are derived from mouseEvent.pageX/Y. For clicks inside an iframe, do you know if it's relative to the iframe doc or the host doc? would there be a discrepancy between xorigin iframe and friendly iframe?

**Comment by keithwrightbos** [comment]
Yes I believe so but only in the case that the document is a creative (e.g. amp-inabox case).  CLICK_X/CLICK_Y should be relative to the iframe, not the container page so pageX/Y should be sufficient 
(please double check).  In other words, it the click location within the creative.

**Comment by cramforce** [comment]
Logic should be the same as with the friendly iframe, so we can likely
install the very same handler (factored out).

**Comment by lannka** [comment]
Sounds like we agree to install the click handler to whole AMP document? Or is there a privacy or performance concern?

**Comment by keithwrightbos** [comment]
SGTM in the event we know the document is an AMP inabox creative.

**Comment by lannka** [comment]
Yes. Very likely I can just move the logic in `amp-a4a.js` to `amp-inabox.js`.

**Comment by jasti** [comment]
Ping @lannka for prioritization.

**Comment by lannka** [comment]
@jasti let's aim for the coming sprint
