### ISSUE TITLE
Feature request to add polling support to amp-list

### ISSUE THREAD

**Issue by robertkviby** [ampproject/amphtml#6386]
@cramforce @dvoytenko 

We see a user-case where we need to update certain information on a page, for example images and metadata such as headlines etc, without actually updating the source fil, but instead, using an amp-list, updating the json-data. For example:

a user comes to page.html. On that we have an image, a headline and link within an amp-list element. The values of these are fetched from a json through amp-list. And we have an interval of n seconds and we poll the json-file, and if that has changed, maybe there should be a data-update-time="123" key within the items[], the elements are updated in a similar fashion as with amp-live-list.

We think there could be use for a smaller interval than 15 seconds, maybe down to even 5 seconds.

If needed, we could contribute to this work.

**Comment by cramforce** [comment]
Chatted with @dvoytenko. He'll take a look.

**Comment by dvoytenko** [comment]
Generally, this SG. But let's discuss first the implication on the sizing. `amp-list` follows strict height limitations to avoid content jumping. So do we expect the `amp-list` to change size due to these re-fetches?

**Comment by robertkviby** [comment]
Hi, no, I would say that one of the restrictions could be that the height is the same.

**Comment by dvoytenko** [comment]
SG. Would you like to contribute the implementation?

**Comment by robertkviby** [comment]
I have not yet gone "in-depth" on how AMP is built on the back-end, what kind of skills are needed?:)

**Comment by dvoytenko** [comment]
JavaScript, CORS.

**Comment by robertkviby** [comment]
Ok! I would gladly contribute. With that said, I am more of a "generalist developer" (working in javascript, php and sometimes C#), than an expert in one language. So, for me to be able to judge if my javascript skills are at the right level for this, is there an implementation, for example of the current amp-list, that I can check out the source of? In either case, I can hopefully contribute with something and surely I will learn stuff a long the way:).

**Comment by dvoytenko** [comment]
Cool! Let's start with https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md and see how it goes. Ping us with any questions.

**Comment by robertkviby** [comment]
will do!

**Comment by aghassemi** [comment]
deduping with https://github.com/ampproject/amphtml/issues/15780
