### ISSUE TITLE
Do not report "Failed to load store" as prod error

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#6390]
This should probably go into its own category instead.

**Comment by erwinmombay** [comment]
@cramforce can i just user().error this instead? for timeouts we just create a raw Error object and throw it

**Comment by cramforce** [comment]
I think the idea was to put it into a new category of errors that can be graphed, but doesn't otherwise get shown. It isn't really a user (in this case AMP doc developer) error and would drown in the noise there.

**Comment by erwinmombay** [comment]
more or less that's what we did with the other errors (timeout, missing origin) we just dump it into `assert` error category and graph them through the error message string (in this case "Failed to load store:")

ill go ahead and create a new "system" error category, does the naming make sense?

**Comment by cramforce** [comment]
How about call the category "sometimesExpected". Can just be a method on
Log.

**Comment by erwinmombay** [comment]
@cramforce if its just a method on Log how would we filter it out though? (just through message string?) or do we lower severity on it?

my original thought was through application field which is the error type (would need new Log instance)

**Comment by cramforce** [comment]
I think I prefer a method on log. Could have expected errors in both dev
and users.

**Comment by adelinamart** [comment]
Is this still happening?

**Comment by jridgewell** [comment]
We added expected errors.
