### ISSUE TITLE
brightcove ads overlays do not work properly on Chrome/Android

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#6401]
Example page: http://amp.usatoday.com/story/94230182/ 

Notice the Ad and Video load at the same time, the video's sound keeps playing, while the Ad is frozen on the first frame.

Does not happen on Safari/iOS, only Chrome/Android

I have narrowed it down to this non-AMP iframe minimal-repro case:
```
<iframe frameborder="0" allowfullscreen="true"
src="https://players.brightcove.net/29906170001/4kr9zgwhe_default/index.html?videoId=5228688474001&amp;adUnit=7103%2Fusatoday_mobile%2Fmobileweb-amp_preroll%2Fnews%2Fpolitics" ></iframe>
```
where the issue still exists.

@mister-ben Has anything changed recently with Brightcove player to cause this?

**Comment by mister-ben** [comment]
This player has opted out of automatic updates and doesn't have the latest version of the Brightcove Player's ad integration. The version it's on is using an event to initialise IMA's Ads Manager that Android Chrome recently stopped considering to be user interaction, which prevents the ad playback. Republishing the player in Video Cloud Studio will update it. I'll reach out to their account team at Brightcove.

**Comment by aghassemi** [comment]
@mister-ben Thanks for looking into this! Could Brightcove please reach out to all customers with the old code? We also noticed the same problem on Fortune and TIME ( example: https://amp.timeinc.net/fortune/2016/11/24/target-black-friday-sales/?source=dam ). Thanks again for your help!

**Comment by aghassemi** [comment]
Issue has been resolved by Brightcove, Thanks!
