### ISSUE TITLE
<amp-app-banner>needs to allow for custom target URLs for solutions such as Firebase Dynamic Links

### ISSUE THREAD

**Issue by noahrs** [ampproject/amphtml#6411]
It looks like the new <amp-app-banner> generates the clickthrough URLs to Google Play and iTunes based off the app id meta on an article page. This probably satisfies some publishers, but many of us use custom campaign URLs generated from within iTunes and Play to track user installs and user retention. 

Accordingly, it would be great if <amp-app-banner> allowed for whatever target URL we wanted. If no URL provided, default back to the meta app id.

**Comment by mkhatib** [comment]
@noahrs thanks for filing, do you have documentation links to these custom target URLs? Or just examples of them so we can understand this use case better?

And if you have an example of how you're currently implementing this it would be great to link to it so we can evaluate implementing this in `amp-app-banner`.

Leaving it to @ericlindley-g for triaging

**Comment by ericlindley-g** [comment]
Would be great to get more details as @mkhatib describes, to hone in on the use-case (and current process, in case we can dovetail with that).

On a related note, the design for amp-deep-link is for developers to configure the links manually (not look to meta tag or manifest to populate these links), which should address both this issue and the amp-sticky-ad collision.

**Comment by noahrs** [comment]
You can generate campaign URLs inside iTunes:
![itunes-sources](https://cloud.githubusercontent.com/assets/8159649/20814061/29f068d8-b7e6-11e6-97c3-20183d454cb9.png)

You use these on various touch points where you tell users to download your app. This let's you measure 1) how effective the touchpoint is 2) track these users for their lifetime in the app to understand if they engage with the app differently based on the source.

![image](https://cloud.githubusercontent.com/assets/8159649/20814090/4694d096-b7e6-11e6-9fd9-a2b7998937e3.png)

The URL from iTunes campaign generator would look like: https://itunes.apple.com/app/apple-store/id384101264?pt=300983&ct=test-example&mt=8

You can do this for Google Play as well using UTMs.

The expectation would be that we can provide two URLs for <amp-app-banner>, one for the iTunes store and one for Play.

**Comment by ericlindley-g** [comment]
Thanks @noahrs  — how do you currently use this URL in the context of the app banner? For instance, with iOS banners it sounds like one approach is to add the attribute value "affiliate-data=at=[affiliate ID]&ct=[campaign name]" into the `<meta>` tag.

**Comment by noahrs** [comment]
We have custom app banners that run on our mobile web experience. If the users OS is iOS we make the click target the custom URL provided through iTunes. If the user OS is Android then we give them the Play UTM. Has nothing to do with any meta tag on site.

**Comment by kul3r4** [comment]
@mkhatib I was able to trigger the banner from http://www.dailymail.co.uk/ushome/index.html (in mobile mode) and took a look at the code.
The tag has id `div id="smartBanner"`
Then the implementation lives in [sync_bundle.js](http://scripts.dailymail.co.uk/static/electrostatic/1.7.0/js/sync_bundle.js).

@noahrs Could you confirm?

**Comment by noahrs** [comment]
@mkhatib yes, that's our custom implementation on mobile web. Detects if you're an Android or iOS user and serves up the right click target accordingly.

**Comment by ericlindley-g** [comment]
Following up — @mkhatib or @cramforce , is there a technical reason not to support manual URLs in amp-app-banner?

**Comment by mkhatib** [comment]
I believe the reasoning was to just encourage the usage of platform supported methods (meta on iOS and manifest for Android).

**Comment by rjaponte** [comment]
Hi all,
What's the current status for this? Can Firebase Dynamic Links be used yet?
