### ISSUE TITLE
amp-analytics: Support a new trigger for when amp-list content is loaded

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#6413]
This is tracking a FR to create an amp-analytics trigger that would fire when amp-list content has been loaded. Originally raised in https://github.com/ampproject/amphtml/issues/5721#issuecomment-263710416.

**Comment by lannka** [comment]
I think it's something different. The original request is asking for more than a "loaded trigger". It wants to select some child elements of `amp-list` once loaded, and trigger a ping when those elements become visible.

**Comment by avimehta** [comment]
I didn't realize that being `visible` was a requirement. I thought it would trigger when all the sub resources are loaded.

**Comment by src-code** [comment]
@lannka is correct - The original issue cited in #5721 is something different.  We'd like to be able to track the visibility of elements within an `amp-list`.  For example, native ads embedded within a list of content items.

**Comment by rudygalfi** [comment]
Per @dvoytenko during Sprint Planning, this should be covered by work in #7452, also happening in this sprint.

**Comment by dvoytenko** [comment]
The new analytics event [`ini-load`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md#initial-load-trigger-on-ini-load) has been added to support reporting load of `amp-list` and most of other components. Should be in canary this Thursday.
