### ISSUE TITLE
Validator: Variable Substitution in amp-forms

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#6421]
We just merged #6130 to allow variable substitutions in amp-form hidden fields. Can we update the validator to support it? Rules should be:

**I think the only thing that needs to be added is to allow an attribute called `default-value` to be added to inputs with value being anything that is allowed in normal `value` attribute, which is basically anything I believe** . 

We can also enforce `type=hidden` but this is fine to leave for runtime as we might introduce this later in other fields. Also runtime is querying only for hidden fields for now anyway and it won't try to var-sub other fields.

```html
    <input name="xxx" type="hidden" default-value="CLIENT_ID(poll)">
    <input name="xxx" type="hidden" default-value="CANONICAL_URL">
```

cc/ @Gregable @powdercloud 

cc/ @rudygalfi

**Comment by honeybadgerdontcare** [comment]
Allow `default-value=...` for `<input>` is now on github, but isn't live in prod yet. #6465

**Comment by honeybadgerdontcare** [comment]
This is now live in prod.
