### ISSUE TITLE
Consider polyfilling checkValidity for older browsers

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#6424]
Following up on [discussion here](https://github.com/ampproject/amphtml/pull/6419#pullrequestreview-10871077). Some old browsers might not have `input.checkValidity` APIs, do we care about polyfilling these?

http://caniuse.com/#search=checkValidity
https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/checkValidity#Browser_compatibility

**Comment by adelinamart** [comment]
Do we still need to have a discussion here? Thanks.

**Comment by mkhatib** [comment]
I doubt we'll do this, I'll defer to @rudygalfi but I think it's ok to close this one - closing it now - Rudy feel free to re-open if that's something we'd like to do.
