### ISSUE TITLE
Validator package on npmjs

### ISSUE THREAD

**Issue by dandv** [ampproject/amphtml#6432]
Is https://github.com/ampproject/amphtml/blob/master/validator/package.json still necessary after [moving the Node.js API into the subdir](https://github.com/ampproject/amphtml/commit/1c4e81dbf7ee88644a3bf319d6a6e14dfe06c7b1) (vs. https://github.com/ampproject/amphtml/blob/master/validator/nodejs/package.json), or can it be deleted?

The GitHub link at https://www.npmjs.com/package/amphtml-validator still points to https://github.com/ampproject/amphtml/blob/master/validator rather than https://github.com/ampproject/amphtml/tree/master/validator/nodejs.

**Comment by honeybadgerdontcare** [comment]
@powdercloud

**Comment by powdercloud** [comment]
Yes. build.py uses it to get the dependencies for the validator itself.

But link from npmjs should go to the subdirectory, that's a good point. I'll fix this. Sorry about the confusion.

**Comment by powdercloud** [comment]
Weird - the package.json in the nodejs subdir from which I publish this already points to the right place. So maybe the one in the parent directory is causing this confusion? Will need to experiment. We could put the one from the parent into the engine subdir for example.

**Comment by powdercloud** [comment]
Unfortunately it doesn't look like it's possible to update the link on the right side of the npmjs.com page (maybe a problem with npmjs.com itself), but my change did add a link to the source code prominently in the description. So I'll consider this closed for now - thanks much for reporting!
