### ISSUE TITLE
Remove dependency on Promise package in validator

### ISSUE THREAD

**Issue by dandv** [ampproject/amphtml#6433]
[The validator](https://github.com/ampproject/amphtml/blob/master/validator/nodejs/index.js) only uses Promise [features supplied by node v0.12 and up](http://kangax.github.io/compat-table/es6/#test-Promise).

Node v0.10 has reached [end of life](https://github.com/nodejs/LTS), and v0.12 will reach EOL on Dec 31. Seems we can [bump the required node version](https://github.com/ampproject/amphtml/blob/master/validator/nodejs/package.json#L7) and get rid of that dependency.

**Comment by honeybadgerdontcare** [comment]
@powdercloud

**Comment by powdercloud** [comment]
If you run Ubuntu 14.04, looks like v0.10 is the default install. So I think this should be supported until 14.04 is truly obsolete or until it's been upgraded or very few people use that version, to make the command line validator work fine out of the box. I looked here: http://packages.ubuntu.com/trusty/nodejs
I'll close this for simplicity, but plese feel free if there's grounds for disagreement. Thanks!
