### ISSUE TITLE
amp-carousel tests are failing locally

### ISSUE THREAD

**Issue by AaronCritchley** [ampproject/amphtml#644]
When running `gulp test` on Ubuntu 15.04 lots of the amp-carousel tests have been failing, I've tried on node v0.12.7 and v4.2.1 and the tests have the same result on both. Logs of the failing tests can be found  [in this gist.](https://gist.github.com/AaronCritchley/2db802df667039d00b4f)

[This pull requests skips the failing tests.](https://github.com/ampproject/amphtml/pull/643)

**Comment by erwinmombay** [comment]
will look into it

**Comment by erwinmombay** [comment]
https://github.com/ampproject/amphtml/pull/646 for ref

**Comment by mkhatib** [comment]
Closing for #412
