### ISSUE TITLE
Allow the SVG basic shape <ellipse>

### ISSUE THREAD

**Issue by tonyruscoe** [ampproject/amphtml#6444]
Issue #96 discussed adding SVG support for “all shapes” but omitted [`<ellipse>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/ellipse) from the list.

Please could that be whitelisted by the validator in the same way as other the SVG basic shapes?

**Comment by honeybadgerdontcare** [comment]
Done in #6461 but it will be a bit before it is deployed in production.

**Comment by tonyruscoe** [comment]
Thanks @honeybadgerdontcare!

**Comment by honeybadgerdontcare** [comment]
This is now live in prod.

**Comment by dvoytenko** [comment]
Reopening. Please update documentation.

**Comment by honeybadgerdontcare** [comment]
I'll update [this document](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md). Not sure if that'll automatically update [ampproject.org's document](https://www.ampproject.org/docs/reference/spec) and if not I'll file an issue with amphtml/docs for it.

**Comment by honeybadgerdontcare** [comment]
Fixed in #8861.
