### ISSUE TITLE
Add "Smartadtags" support on amp-ad

### ISSUE THREAD

**Issue by gonscenna** [ampproject/amphtml#6456]
## Description

I want to contribute to add support to Smartadtags network platform https://www.smartadtags.com/

We are one of the biggest ad networks and we want to support our ad tags in AMP language

Thank you

**Comment by dvoytenko** [comment]
LGTM. Please go ahead and send the pull request.

**Comment by jasti** [comment]
Hi there, do you have an ETA for the PR?
