### ISSUE TITLE
Report failed A4A validations

### ISSUE THREAD

**Issue by taymonbeal** [ampproject/amphtml#6481]
If none of the keys associated with an A4A ad network match the hash in an ad creative signature, an error should be reported to the console and to an error reporting server specified by the ad network.

**Comment by taymonbeal** [comment]
CC @ampproject/a4a

**Comment by dknecht** [comment]
Should it be to the ad network or signing authority?

**Comment by taymonbeal** [comment]
The ad network, I think. While a failure here could ultimately be caused by a misbehaving signing service, only the ad network is in a position to distinguish between a failure on their own end and one on the signing service's.

**Comment by keithwrightbos** [comment]
This is being done from A4AElement so closing.
