### ISSUE TITLE
jw-player, `pause` toggles the playing state instead of always pausing.

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#6483]
Apparently calling `pause` on JWPlayer will TOGGLE the playing state, not necessarily pause it (unless explicitly requested) according to https://developer.jwplayer.com/jw-player/docs/developer-guide/api/javascript_api_reference/ 

We need to change `pauseCallback` in `amp-jwplayer` to pass the explicit `don't toggle, really pause` flag.

**Comment by aghassemi** [comment]
@pablos1 We like to ask JWPlayer team to help with this bug. `<amp-jwplayer>`, as you know, sends `pause` messages through `postMessage` to the cloud player. That seems to `toggle` the state rather than always pausing it. The code I see that's handling the post messages (from https://content.jwplatform.com/players/BZ6tc0gy-uoIbMPm3.html ) is 
```
          window.addEventListener("message", function(evt) {
            switch (evt.data) {
              case "play":
                jwplayer().play();
                break;
              case "pause":
                jwplayer().pause();
                break;
            }
          });
```

however according to `https://developer.jwplayer.com/jw-player/docs/developer-guide/api/javascript_api_reference/` both `play()` and `pause()` `toggle` the state. Looks like the code needs to be changed to ` jwplayer().play(true);` and `jwplayer().pause(true);`

Is that something your team can fix quickly? (It is causing jwplayer videos in AMP pages to start playing when a user swipe to another AMP document as AMP runtime sends a `pause` event which actually ends up playing the video in the jwplayer's case. This is very confusing as the user is now on a totally different AMP page but hearing sound from a video in the previous AMP document).

**Comment by pablos1** [comment]
Sure, I'll put together a quick PR and shoot it over.

**Comment by aghassemi** [comment]
@pablos1 Thanks! however, unless I am mistaken, I don't think this is fixable only on the AMP component-side as I could not find a `postMessage`  API that accepts the boolean argument to `play` and `pause` methods (The code above is the only thing that handles postMessages to jwplayer cloud players and as you can see it does not allow passage of args into play and pause).

**Comment by pablos1** [comment]
@aghassemi Ah, you're right; I read through this too quickly.  I'll run this down the chain and see if we can get this together quickly.

**Comment by pablos1** [comment]
@aghassemi This should now be working on our end.   postMessage handler now looks like this:

```          /** Used to pass play/pause messages parent iframe via postMessage **/
          window.addEventListener("message", function(evt) {
            switch (evt.data) {
              case "play":
                jwplayer().play(true);
                break;
              case "pause":
                jwplayer().pause(true);
                break;
            }
          });
```

**Comment by aghassemi** [comment]
@pablos1 Perfect! Thanks for the quick turnaround. I will revert the temporary fix we put in place now.

**Comment by aghassemi** [comment]
Fixed
