### ISSUE TITLE
Scrolling the sidebar, lightbox (scrollable) scrolls the main page

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#6487]
When the `amp-lightbox` is open and it's a scrollable lightbox, if the user scrolls to the end of the lightbox and keeps scrolling, the background body will continue to scroll. We can make the `body` or `html` to be `overflow: hidden` temporarily to avoid body scrolling.

Also when sidebar is visible, one can not scroll the main page since it is masked but scrolling the sidebar will scroll the page when it reaches the end of sidebar scrolling area.

**Comment by adelinamart** [comment]
Is this still an issue?

**Comment by muxin** [comment]
Yes.
@dvoytenko Adding `overflow: hidden` **temporarily** should be OK, right?

**Comment by dvoytenko** [comment]
I'll leave it up to @aghassemi as he tried more things around it. My reservation is that `overflow:hidden` would reset the scrolling and it'd be very noticeable with the semi-transparent background.

**Comment by muxin** [comment]
I checked gmail and facebook's modal feature, for example when opening a picture in modal, the background is set to `overflow:hidden` and not scrollable. What do you mean by "noticeable"?

**Comment by dvoytenko** [comment]
The page jumps up from, e.g. `scrollTop = 1000` to `scrollTop = 0`.

**Comment by aghassemi** [comment]
@muxin if `overflow:hidden` does not reset scroll position (it doesn't in Chrome, not sure about Safari, needs to be tested) then that's fine. preventing default on `touchmove` is another possibility. Anyway, let's hold on working on this until it gets scheduled.

**Comment by muxin** [comment]
- Natural binding: setting and removing `overflow: hidden` on `html` works fine.
- NaturalIosEmbed binding: setting `overflow: hidden` on `body` stops the scroll but removing the `overflow: hidden` reset the `body`'s top position to 0, causing a page jump.
- IosEmbedWrapper binding: setting and removing`overflow: hidden !important` on `#i-amphtml-wrapper` works fine. `!important` is needed to override [this](https://github.com/ampproject/amphtml/blob/master/css/amp.css#L75)

We could go ahead and implement this for two types of bindings. @dvoytenko WDYT?

**Comment by aghassemi** [comment]
I think we should do it for the cases that work, specially considering when `IosEmbedWrapper` launches, this will cover most of users as `NaturalIosEmbed` will be only iOS 8 and 7 which is a tiny group.

**Comment by dvoytenko** [comment]
I agree. Let's only do this for natural and wrapper bindings.

**Comment by dvoytenko** [comment]
However, please also do provide the following info:

1. Please try it in a non-mobile emulation and report back how the UX is affected. E.g. are scrollbars removed? How much UI updates.
2. Considering the case with visible scrollbars and w/o - what is the amount of relayout/recalc/etc work the browser has to do?

**Comment by muxin** [comment]
In both mobile and desktop browsers, both safari and chrome, the scrollbar is not taking extra space on the page, instead, the scrollbar only appears when scrolling the page and is like floating above the page, not changing the page layout at all.
Adding overflow: hidden and removing overflow: hidden doesn't have impact on the layout of the page.

**Comment by dvoytenko** [comment]
Hmm. Ok. This is because all browsers on Mac and most of phones implement overlaying scrollbar. Would you also mind trying this on a Windows machine?

**Comment by muxin** [comment]
I tested it on surface edge, the scrollbar will disappear and reappear, but overall it looks fine.
