### ISSUE TITLE
Ctrl+F doesn't work on chrome for iOS

### ISSUE THREAD

**Issue by rufioh** [ampproject/amphtml#6492]
## Short description of your issue:

Find in page on chrome for iOS doesn't work

## How do we reproduce the issue?

use an iPhone 6s,
Have iOS 10
Open chrome for iOS 
Open a page that uses AMP
Try to "find in page" something you can already see is there
No results will be found

**Comment by rufioh** [comment]
Here's an example https://imgur.com/a/5dWiR

**Comment by rufioh** [comment]
As you can see in this image https://imgur.com/a/5dWiR, I searched for the first two words on the page and recieved zero results.

**Comment by jridgewell** [comment]
/to @dvoytenko 

I know we have a bug for this open already, but I can't seem to find it.

**Comment by dvoytenko** [comment]
Yes, this is dupe of #5750. Please ping on the associated webkit bug to improve chances of it being fixed sooner.
