### ISSUE TITLE
amp-pixel should allow for sending request immediately

### ISSUE THREAD

**Issue by keithwrightbos** [ampproject/amphtml#6497]
## Short description of your issue:

amp-pixel is used by A4A creatives for delayed impression tracking and so we want it sent as soon as the creative starts to render.  However, it currently has a priority of 1 causing it to be delayed at least 500ms.  

## How do we reproduce the issue?

Include amp-pixel...

## What browsers are affected?

All
## Which AMP version is affected?

All

**Comment by jasti** [comment]
@dvoytenko fixed this, yes?

**Comment by dvoytenko** [comment]
Closed by #6988.
