### ISSUE TITLE
Allow specifying the name of the `items` property for amp-list responses

### ISSUE THREAD

**Issue by dandv** [ampproject/amphtml#6507]
Currently, the response from a CORS endpoint supplying data for amp-list [must be a JSON object that contains an array property "items"](https://www.ampproject.org/docs/reference/components/amp-list#usage).

An unfortunate consequence of this is that a large number of public APIs are unusable, because they dont' return data wrapped in an `items` array. For [example](https://api.github.com/users/dandv/repos), GitHub's API returns directly an array of objects.

Here's a small `amp-list` sample trying to show a user's repos: https://jsbin.com/xekavu/edit?html,output

Proposal: add an attribute to `amp-list` allowing the developer to specify the name of the items property (default "items"):

```html
<amp-list 
    layout=fixed-height
    items=""    
    src="https://api.github.com/users/dandv/repos">
```

**Comment by ericlindley-g** [comment]
@dandv this seems intriguing — do you have a sense of what some of the most-used APIs are that would be supported by this change?

@dvoytenko — any concerns here?

**Comment by dvoytenko** [comment]
No concerns. We already have an API `getValueForExpr` that would help implement this.

Let's do this:
```
<amp-list root="path.to.array"></amp-list>
```

Where `root="."` will indicate that the response itself should be treated as an array.

**Comment by dandv** [comment]
> do you have a sense of what some of the most-used APIs are that would be supported by this change?

All APIs :) Highly dependent on the use case, from weather to currency conversion to current movies or whatnot.
