### ISSUE TITLE
Not clear in docs that 'submit-success' & 'submit-error' must be direct children of form.

### ISSUE THREAD

**Issue by paulisloud** [ampproject/amphtml#6516]
The [AMP Forms](https://ampbyexample.com/components/amp-form/) documentation recommends the following markup for rendering success / error states in form responses: 

  ```
<div submit-success>
      <template type="amp-mustache">
        Success! Thanks {{name}} for trying the
        <code>amp-form</code> demo! Try to insert the word "error" as a name input in the form to see how
        <code>amp-form</code> handles errors.
      </template>
    </div>
    <div submit-error>
      <template type="amp-mustache">
        Error! Thanks {{name}} for trying the
        <code>amp-form</code> demo with an error response.
      </template>
    </div>
```

This markup does not validate either when browsing the URL and appending `#development=1`, or when running a page through [https://validator.ampproject.org](https://validator.ampproject.org)

The response is `The attribute 'submit-success' may not appear in tag 'div'.` and `The attribute 'submit-error' may not appear in tag 'div'.`

## To reproduce the issue, simply include
``<script async custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js"></script>``
and 
``<script async="" custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.1.js"></script>``
in your head tag.

Then include the recommended markup from the the AMP Forms doc page mentioned above. It will consistently through an error.

True in at least Chrome, Firefox and Safari, AMP version: 1480633190770

**Comment by honeybadgerdontcare** [comment]
Those `<div>` tags must be children of a `<form>` tag as they are in the [amp-form by example](https://ampbyexample.com/components/amp-form/) documentation and on [ampproject.org](https://www.ampproject.org/docs/reference/components/amp-form).

```
    <form method="post"
      action-xhr="https://ampbyexample.com/components/amp-form/submit-form-input-text-xhr"
      target="_top">
    <input type="text"
        class="data-input"
        name="name"
        placeholder="Name..."
        required>
    <input type="email"
        class="data-input"
        name="email"
        placeholder="Email..."
        required>
    <input type="submit"
        value="Subscribe"
        class="button button-primary">
    <div submit-success>
      <template type="amp-mustache">
        Success! Thanks {{name}} for trying the
        <code>amp-form</code> demo! Try to insert the word "error" as a name input in the form to see how
        <code>amp-form</code> handles errors.
      </template>
    </div>
    <div submit-error>
      <template type="amp-mustache">
        Error! Thanks {{name}} for trying the
        <code>amp-form</code> demo with an error response.
      </template>
    </div>
  </form>
```

**Comment by paulisloud** [comment]
While I did have the submit-success / -error `<div>`s as children of the `<form>` element, they were nested inside `<fieldset>` tags as well.

Thanks for making the distinction about their needing to be direct children.

I've just gone and browsed the [AMP By Example](https://ampbyexample.com/components/amp-form/) and [AMP Project](https://www.ampproject.org/docs/reference/components/amp-form) doc pages again, and there is no mention of the direct descent requirement. Might it be worth updating these? It's not a necessarily intuitive requirement.

**Comment by honeybadgerdontcare** [comment]
@bpaduch I saw some of your comments on amp-form.md from a couple of days ago. I've created a PR #6562 to clean up that we do require `submit-(success|error)` to be direct children of `<form>` rather than any child of `<form>`. We should also make this clearer in the  [AMP By Example](https://ampbyexample.com/components/amp-form/) doc but I don't know where that's managed. Would you be able to follow up on that?

**Comment by bpaduch** [comment]
For any changes to AMP By Example, submit a PR to their repo - https://github.com/ampproject/amp-by-example/

**Comment by honeybadgerdontcare** [comment]
@paulisloud thanks for pointing out that this should be noted more clearly in the docs. The two PRs should help with that.

**Comment by IamAlta** [comment]
@honeybadgerdontcare
Can you kindly clarify the nesting for submit-error, submit-success to this page where they first show up under "Success"? The example shows it but it is not intuitive about the nesting. Thank you.
https://ampbyexample.com/components/amp-form/

**Comment by honeybadgerdontcare** [comment]
@IamAlta I'm not sure I understand what you're asking. AMP by Example explicitly states:

```
 The submit-success and submit-error elements must be direct children of form.
```

**Comment by IamAlta** [comment]
@ honeybadgerdontcare 
I see it now under "Form Submission with Page Update"
I was concentrating on XHR (XMLHttpRequest) form submissions and didn't look there.
Do you think putting it under "Setup" is more appropriate?

**Comment by honeybadgerdontcare** [comment]
@bpaduch thoughts?

**Comment by bpaduch** [comment]
I think putting that info under "setup" doesn't meet what "setup" is for these examples.  I feel it's adequately covered in the first example/usage of submit-success and submit-error.

**Comment by IamAlta** [comment]
@bpaduch
Then how about putting it under all scenarios. I missed it because I was working with another scenario and had no reason to read the one where it's cited. I spent a lot of time troubleshooting.

**Comment by bpaduch** [comment]
@IamAlta - I've submitted a PR to put information in the Intro section so it's first noticed.  Adding it to each example would require all the features in each example spelled out, but the flow of the document is such that each example calls out the unique parts.  I hope this is a good fit to the solution.

**Comment by IamAlta** [comment]
Thank you for understanding, Barb @bpaduch. You guys are doing such great work that we all appreciate.

**Comment by 88kbbq** [comment]
With this requirement, it's impossible to create responsive forms. Please axe this meaningly restriction.

**Comment by riham13** [comment]
is it allowed to have multiple "submit-error" under one form ?
