### ISSUE TITLE
Consider making the bundling of amp-shadow and amp-inabox optional

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#6517]
… for bare `gulp` builds. These take significant amounts of time and are rarely used during regular dev (I think).

**Comment by adelinamart** [comment]
Is this work prioritized for this year? Thanks.

**Comment by cramforce** [comment]
I was trying to find this :) Fixed by #7346

**Comment by adelinamart** [comment]
Great. I'll close this one.
