### ISSUE TITLE
amp-lightbox initial updateInViewport does not really work

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#6522]
Regardless of the new `scrollable` attribute, the initial `updateInViewport` in `activate` has never actually worked. This is because `updateInViewport(element, true)` does not actually _guarantee_ it will set `inViewport` for element to `true`. It only does it if the parent element is also `inViewport`. 

Now in the case of `amp-lightbox` we call `updateInViewport(container, true)` upon `activate` but runtime has not _yet_ detected that `amp-lightbox` (parent element) is also inViewport so `updateInViewport(container, true)` does nothing (due to this logic - which is correct - here: https://github.com/ampproject/amphtml/blob/fe4c03f75ac922884d645041df66f7fc5bb2feec/src/service/resources-impl.js#L1494)

I think we need to take out the calls to `updateInViewport` _out_ of activate method and use the `viewportCallback` instead. e.g something like

```
  /** @override */
  viewportCallback(inViewport) {
    if (!this.container_) {
      return;
    }
    // if not in viewport anymore (e.g. closed) update all children.
    if (!inViewport) {
      this.updateInViewport(this.container_, false);
      return;
    }

   // if in viewport and not scrollable, all children are also in viewport
    if (!this.isScrollable_) {
      this.updateInViewport(this.container_, true);
    } else {
     // if scrollable, update inViewport based on visibility.
      this.updateChildrenInViewport_(this.pos_, this.pos_);
    }
  }
```

**Comment by aghassemi** [comment]
@muxin Something to fix since you are in lightbox code already and writing tests for you.

**Comment by adelinamart** [comment]
@muxin @aghassemi what's the latest status here? Thanks

**Comment by aghassemi** [comment]
still a bug (low priority)
