### ISSUE TITLE
div in front of ad making it unable to click

### ISSUE THREAD

**Issue by nfepl** [ampproject/amphtml#6523]
A div is rendering inside the `amp-ad` tag, containing a script with `draw3p()`. This div make users unable to click the ad, and creates a blank space that's bigger than the size specified in the tag.

Most probably is something we're missing on our js, but I couldn't find it.

[Here's](http://m.lanueva.com/mobile/copa-davis-2016/886457/con-un-bahiense--argentina-busca-su-primera-ensaladera-de-plata.html) a real example of the issue.

**Comment by lannka** [comment]
@nfepl this is the container element. You should put your stuff in it.
```
  global.document.getElementById('c').appendChild(yourAd);
```

For example: https://github.com/ampproject/amphtml/blob/c44a48fbb1dbd0de0b5a9e20f8f69bb920705dde/ads/mantis.js#L33

**Comment by nfepl** [comment]
@lannka, thanks for the help, we'll update our js to reflect this change.
