### ISSUE TITLE
Integration tests failing on iOS Safari 8

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#6526]
Integration tests started failing on  iOS Safari 8 since https://github.com/ampproject/amphtml/pull/6508 with:
```
Mobile Safari 8.0.0 (iOS 8.4.0) released components with polyfills:  Rendering of released components "before each" hook FAILED
	Error: No messaging channel: undefined (http://localhost:9876/dist/v0.js:16)
```

@muxin Could you please take a look? Might be test related or may actually be discovering a bug. We can use SauceLabs locally to repro/verify the fix, I can help you get setup with SauceLabs if you are not already.

**Comment by muxin** [comment]
@lannka is fixing this in https://github.com/ampproject/amphtml/pull/6525
