### ISSUE TITLE
Provide document height to viewer

### ISSUE THREAD

**Issue by RJSumi** [ampproject/amphtml#6530]
The viewer needs the document height from the runtime.  I understand that this had some performance issues in the past.  When might this be made available again?

cc @dvoytenko

**Comment by RJSumi** [comment]
Is this likely to get any traction soon, or is this infeasible?

**Comment by jridgewell** [comment]
A few things this requires:

- [ ] Initial document heigh in `documentLoaded`
- [ ] A new ping every time an element resizes

Alternatively, we could allow the viewer to request the height, but it'd be a little less performant. @muxin or @chenshay, would you like to take this?

**Comment by cramforce** [comment]
@RJSumi Do you need resizes?

**Comment by muxin** [comment]
@jridgewell For the first bullet point, do you mean measuring the document height when we're about to send the `documentLoaded` message?

**Comment by jridgewell** [comment]
Yup, it should be available pretty early in `Viewport`.

**Comment by muxin** [comment]
So when we're about to send `documentLoaded` message, we should have built every element so it's a good time to measure the document height?

**Comment by jridgewell** [comment]
> we should have built every element so it's a good time to measure the document height?

No. But, AMP requires every these elements to have a defined width/height, so we should know how tall it is even if it's not built.

**Comment by muxin** [comment]
@jridgewell But there are other non-amp elements, we could also measure the heights of non-amp elements at that time?

**Comment by jridgewell** [comment]
They should already have there size by this time.

**Comment by muxin** [comment]
OK, thanks @jridgewell I can try to measure the document height for the initial height in `documentLoaded` and the updated height in every resizes.
@RJSumi In what message do you need the document height value?

**Comment by muxin** [comment]
Messaged with @RJSumi offline, will be sending 'documentHeight' message to viewer.

**Comment by dvoytenko** [comment]
Two challenges to keep in mind:

1. Performance is very much an issue. However, provided we can control when measurements are done and sent over, we should be able to optimize it on our side. We currently don't have 100% reliable "mutated" pings, but we have some signals that would help us to do these measurements less often. We can even try to measure height after each resources pass (with basic debouncing) and see how much performance affect it has.
2. `scrollHeight` could yield wrong values in some circumstances. I believe most of issues were around old iOS viewport (iOS <= 8) and should be now addressed for newer versions. However, testing is needed to confirm.

**Comment by muxin** [comment]
Talked with @RJSumi offline: when the content is not filling up the entire viewport, it would be nice to send the document height of the real content, which is less than the viewport height.
The `viewport.getScrollHeight` is returning the viewport height when the viewport is not filled up. So I'm creating another similar method `getDocHeight`

**Comment by muxin** [comment]
Closed via https://github.com/ampproject/amphtml/pull/7327
