### ISSUE TITLE
Forbid ES6 methods on Array

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#6539]
- `Array#includes`
- `Array#find`

https://github.com/ampproject/amphtml/issues/6538

**Comment by erwinmombay** [comment]
@jridgewell no exceptions right?

**Comment by jridgewell** [comment]
I don't know them off the top of my head.

**Comment by jridgewell** [comment]
`Array#find` is the only new one.

**Comment by jridgewell** [comment]
Sorry, and `#includes`.
