### ISSUE TITLE
Error getting substring of Element's id

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#6540]
```
TypeError: a.id.substring is not a function
    at Lf.f.installActionHandler (https://cdn.ampproject.org/rtv/001481049920709/v0.js:186:82)
    at new V (https://cdn.ampproject.org/rtv/001481049920709/v0/amp-form-0.1.js:21:346)
    at https://cdn.ampproject.org/rtv/001481049920709/v0/amp-form-0.1.js:31:75
    at Array.forEach (native)
    at https://cdn.ampproject.org/rtv/001481049920709/v0/amp-form-0.1.js:31:53
    at ra (https://cdn.ampproject.org/rtv/001481049920709/v0/amp-form-0.1.js:10:248)
    at qa (https://cdn.ampproject.org/rtv/001481049920709/v0/amp-form-0.1.js:10:202)
    at Da (https://cdn.ampproject.org/rtv/001481049920709/v0/amp-form-0.1.js:31:16)
    at https://cdn.ampproject.org/rtv/001481049920709/v0/amp-form-0.1.js:31:173
    at na (https://cdn.ampproject.org/rtv/001481049920709/v0/amp-form-0.1.js:9:42)
```

Relevant line is https://github.com/ampproject/amphtml/blob/0310284/src/service/action-impl.js#L182.

Something makes me think we're getting an `target` that's not an `Element`. Might be something to do with https://github.com/ampproject/amphtml/blob/2860c430a0de23ffea672685825fe54083d333c4/extensions/amp-access/0.1/amp-access.js#L83?

**Comment by jridgewell** [comment]
Or, it's AmpForms: https://github.com/ampproject/amphtml/blob/2860c430a0de23ffea672685825fe54083d333c4/extensions/amp-form/0.1/amp-form.js#L539-L541?

**Comment by dvoytenko** [comment]
Reassigning to @mkhatib . Looks like it's coming from forms. But looking at the action code, I actually do not see how this error could happen.

In addition, /cc @erwinmombay - the binary code is very very strange. Let's check if `dev.assert` removal is correct there. Basically,
```
    dev().assert((target.id && target.id.substring(0, 4) == 'amp-') ||
        target.tagName.toLowerCase() in ELEMENTS_ACTIONS_MAP_,
        'AMP element or a whitelisted target element is expected: %s', debugid);
```
got turned into
```
a.id&&"amp-"==a.id.substring(0,4)||a.tagName.toLowerCase();
```
That code obviously lacks side-effects, unless something is amiss.

**Comment by erwinmombay** [comment]
@dvoytenko are you saying the whole line should have been removed since there is a lack of side effect?

**Comment by jridgewell** [comment]
Yup. Also, it's DCE was totally incorrect because it removed the `in ELEMENTS_ACTIONS_MAP_`.

**Comment by dvoytenko** [comment]
`in ELEMENTS_ACTIONS_MAP_` definitely doesn't have side-effects. But, I'd guess, it either doesn't understand that `toLowerCase()` has no side effects, or doesn't recognize `tagName` as a string.

**Comment by dvoytenko** [comment]
@jridgewell That being said, there's still protection there against `null`/`undefined` `id` and it's  very hard to imagine that we got a non-element target with `id` field that is not a string...

**Comment by jridgewell** [comment]
> . But, I'd guess, it either doesn't understand that toLowerCase() has no side effects, or doesn't recognize tagName as a string.

Ohhh. Should be ban function calls inside the assertion?

**Comment by dvoytenko** [comment]
It'd be a hard one. `toLowerCase` is clearly marked as `@nosideeffects` in externs. So it should have been DCE'd. Let's first see why it wasn't.

**Comment by mkhatib** [comment]
Found the problem...

So `target` (or `a` minified) is the `FORM` element as expected. However, `a.id` is returning an `INPUT` element with the name `id`.

```html
<form>
  <input name="id"> <-- this is returned when accessing target.id
</form>
```

I guess we can add more checks here or use `getAttribute('id')` instead.

**Comment by mkhatib** [comment]
Closing this. @dvoytenko implemented `FormProxy` that should handle these cases and there are other issues to discuss banning special input names/ids.
