### ISSUE TITLE
Crazy errors with app-banner

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#6541]
The error message is always some big number.

```
7981376169795973511
https://cdn.ampproject.org/rtv/001481049920709/v0/amp-app-banner-0.1.js:4:940
```

Relavent line is https://github.com/ampproject/amphtml/blob/b652d1c/extensions/amp-app-banner/0.1/amp-app-banner.js#L84.

**Comment by mkhatib** [comment]
ha. Yeah this is related to #6454 - can you confirm the User Agent you're seeing this error on? It's on iOS only - no?

**Comment by jridgewell** [comment]
Always iOS.

**Comment by adelinamart** [comment]
@jridgewell seems issue referenced is fixed. is this still a problem?

**Comment by dvoytenko** [comment]
Still a problem intermittently.

**Comment by dvoytenko** [comment]
Closed in favor  of https://github.com/ampproject/amphtml/issues/8703
