### ISSUE TITLE
Forbid es6 and es7 String Methods

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#6549]
- `#padStart`
- `#padEnd`
- `#startsWith`
- `#endsWith`
- `#includes`
- `#repeat`

**Comment by erwinmombay** [comment]
also adding `#normalize`, `#codePointAt`, `String.raw`, `String.fromCodePoint`

**Comment by trodrigues** [comment]
Curious about what the reasoning behind this is. Browser support?

**Comment by jridgewell** [comment]
Yup, this is just to be on the safe side. We see a small amount of errors in our logs from dated browsers.
