### ISSUE TITLE
Forbid ES6 Structures

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#6551]
- `Map`
- `WeakMap`
- `Set`
- `WeakSet`
- `Symbol`

Unless we want to polyfill.

**Comment by xrav3nz** [comment]
Is it possible to revisit the list now, particularly `Set`? 

It looks like browser support [has caught up](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set#Browser_compatibility), but I am not sure what other metrics need to be factored in. My desired behaviour could be emulated with a plain JavaScript object (`{}`) though, just thought I'd ask!

Thanks!
