### ISSUE TITLE
Columbia ads: target of hyperlink is coming _top instead of _default

### ISSUE THREAD

**Issue by swatigoel1991** [ampproject/amphtml#6554]
![test](https://cloud.githubusercontent.com/assets/7466179/21001483/922a64c0-bd46-11e6-81c0-afec929d0315.png)
Right now ads are opening in the same page as application. Ideally ads should open in new tab, so target of hyperlink in html should be "_blank" but it is coming as "_top"

## How do we reproduce the issue?
Integrate the amp-ads with columbia

## What browsers are affected? 
ALL browsers

It is not a new issue, it has always been there.

**Comment by lannka** [comment]
@ColombiaOnline do you allow pub to customize this behavior?

**Comment by lannka** [comment]
@swatigoel1991 I suggest you contact Columbia ads support team. Currently there is not much we can do here.
