### ISSUE TITLE
Avoid blank screen during page transitions

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#6555]
It would be great if we could provide a way to avoid the blank screen when transitioning from one AMP  to another. This is relevant for websites using AMP as canonical and it's quite annoying once you've started noticing. 

Here is a sample:

![amp-screen-blank](https://cloud.githubusercontent.com/assets/380472/21009946/38c56f60-bd41-11e6-966f-287922c781c1.gif)

**Comment by cramforce** [comment]
Interesting problem! We will fix it on the cache soon by server side rendering the initial custom element setup phase.

@dglazkov Do you happen to be aware of a method to avoid "Flash of unstyled web components" in a way that prevents the browser from ever attempting to paint before resolved stage is reached?

CC @dvoytenko

**Comment by dknecht** [comment]
@cramforce can you point us to the discussion about server side rendering work?

**Comment by cramforce** [comment]
@dknecht no discussion. We're figuring out whether it works.

**Comment by dvoytenko** [comment]
We did discuss some aspects of this with @pbakaus about page-to-page transitioning. I'm not sure if there was a clear path to address this. @pbakaus do you recollect?

**Comment by cramforce** [comment]
I raised this with the chrome team and they basically consider it a bug on their side.

**Comment by cramforce** [comment]
There is also a new page transition web standard being discussed (without client side nav) that would likely fix this.

**Comment by dvoytenko** [comment]
@cramforce Correct. The transition web standard is what I'm thinking about. Do you have a link?

**Comment by sebastianbenz** [comment]
@jakearchibald recently wrote about this [here](https://github.com/jakearchibald/navigation-transitions)

**Comment by cramforce** [comment]
@sebastianbenz filed Chrome bug https://bugs.chromium.org/p/chromium/issues/detail?id=672837

**Comment by sebastianbenz** [comment]
I think we can actually close this bug as it is a issue with Chrome (Firefox doesn't show this behavior).
