### ISSUE TITLE
Windows 8.1 (Nokia Lumia 930) Not loading Ads

### ISSUE THREAD

**Issue by e2corporation** [ampproject/amphtml#6563]
On Browserstack, Ads are not loading on Windows Mobile 8.1 Mobile devices. Is this due to testing environment being on Heroku?

**Nokia Lumia 930** - Not Loading
[https://shogun-amp.herokuapp.com/examples/1.html](https://shogun-amp.herokuapp.com/examples/1.html)

**Comment by e2corporation** [comment]
Loading this test case on Windows + IE14 does not load on the first page load but only after 2nd refresh, is this also due to testing environment?

**Comment by mkhatib** [comment]
@e2corporation what is IE14 is this a version of edge?

**Comment by dvoytenko** [comment]
Good question. I thought IE only went as far as 11?

**Comment by e2corporation** [comment]
Below is a shot from browser stack showing IE14 under Windows 10.

![bstack](https://cloud.githubusercontent.com/assets/1742233/21058920/2d8dac2a-be0e-11e6-803c-0cfd682f0f1c.png)

**Comment by dvoytenko** [comment]
Ok. So it looks like it's Edge then.

**Comment by jasti** [comment]
Ping @lannka

**Comment by jasti** [comment]
Ping @lannka

**Comment by jasti** [comment]
Ping @lannka

**Comment by lannka** [comment]
I reproduced the issue on Edge. But I think it's more likely an ad targeting issue, because the `amp-ad`  is collapsed after receiving a "no-content" message from the creative iframe.  you might want to try the same ad slot in a non-AMP environment, and see if it loads ads in Edge.
