### ISSUE TITLE
Can we have explanatory comments at the top of all files as to what they are ?

### ISSUE THREAD

**Issue by AaronNGray** [ampproject/amphtml#6572]
I want to quickly see what a source file is, what its class(es)/component(s) are and what they do with out having to scroll down; why do I have to keep seeing the license on everything when I know what license everything is under anyway. Would it not be better to have the license at the bottom of files; it still stands anyway.

Like for example what is a 'chunk'; and anyway a 'chunk' is a silly overloaded name anyway !

**Comment by rudygalfi** [comment]
I don't think there's flexibility on the license bit. For the rest of the feedback routing this to @cramforce.

**Comment by cramforce** [comment]
Yeah, the license is not a fight worth fighting. I think AMP is decently well documented in source. Feel free to file bugs for individual items you'd like better commented.
