### ISSUE TITLE
Extend default click handlers to FIE

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#6578]
See #6414 for the APIs.

**Comment by mkhatib** [comment]
Does this include expanding `urlReplacement.maybeExpandLink` to work in embeds or that is out of scope? 

Also, do we want to also port the handling local-navigation links in embeds? If yes, `scrollToElement` depends on `viewport` does that mean we'd need to figure out a different way to do this?

**Comment by dvoytenko** [comment]
`maybeExpandLink` - yes. But it doesn't have to go via the same PR/bug. Feel free to split.

`scrollToElement` should work correctly via the global viewport, but ID lookup has to be done via the local document, of course. If viewport doesn't scroll as expected - we should fix that problem there. But I expect it to work right right away.

**Comment by adelinamart** [comment]
Is this still needed? Thanks

**Comment by dvoytenko** [comment]
Yes. I believe this hasn't been done yet.
