### ISSUE TITLE
Cannot read property '_AMP_content_0' of null

### ISSUE THREAD

**Issue by eruci** [ampproject/amphtml#6582]
I started to get these errors on http://sunrisebargrill.foodpages.ca/amp today, although nothing has changed on my code. (seems like the v0.js library was updated on the amp project and broke things)

http://sunrisebargrill.foodpages.ca/amp
error.js:82 AMP-ACCORDION# Cannot read property '_AMP_content_0' of nullmd @ error.js:82
v0.js:5 Uncaught TypeError: failed to build: amp-accordion#7: Cannot read property '_AMP_content_0' of null _reported_(…)
v0.js:5Uncaught TypeError: failed to build: amp-accordion#8: Cannot read property '_AMP_content_0' of null _reported_(…)

**Comment by erwinmombay** [comment]
thanks for reporting @eruci. i'll get this fixed w/in the hour. it looks we released the wrong version

**Comment by erwinmombay** [comment]
@eruci thanks for reporting this. should be fixed now
