### ISSUE TITLE
Carousel Arrow SVGs not being displayed on IE

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#6591]
Open a page with any carousel type on IE, when the controls are enabled the SVG arrows are not shown (we only see the background box instead).

**Comment by pranavbilurkar** [comment]
Is this already fixed? If yes, pleae do let me know.

**Comment by pranavbilurkar** [comment]
Any Update on this??

**Comment by pranavbilurkar** [comment]
@jridgewell Any Update on this issue as when it is going to get resolved.

**Comment by jskvishal** [comment]
I m new to amp lets do it

**Comment by torch2424** [comment]
Going to take this on, per request be @camelburrito
