### ISSUE TITLE
Validator error when using custom URI schemes for href and data-share-endpoint for Line and BBM

### ISSUE THREAD

**Issue by kangismet** [ampproject/amphtml#6600]
This issue about custom url schemes, similar to [#5071](https://github.com/ampproject/amphtml/issues/5071)

```
Invalid URL protocol 'line:' for attribute 'href' in tag 'a'.
Invalid URL protocol 'bbmi:' for attribute 'href' in tag 'a'.
```

This also getting error when applies to data-share-endpoint in amp-social-share component.

Is it possible to whitelist LINE and BBM tag?

**Comment by Gregable** [comment]
We rely on a whitelist model to avoid browser interactions such as `script:`. I have no problem adding these schemes to the whitelist. Can you point me to information on what these schemes are used for though? I couldn't find anything with a quick web search.

**Comment by kangismet** [comment]
thank you @Gregable 
The issue can be reproduced by simply testing the following links 

`<a href="line://msg/text/https%3A%2F%2Fvalidator.ampproject.org">Share via Line</a>`
`<a href="bbmi://api/share?message=https%3A%2F%2Fvalidator.ampproject.org">Share via BBM</a>`

**Comment by Gregable** [comment]
OK, So `bbmi` is Blackberry Messenger: http://devblog.blackberry.com/2015/02/cross-platform-sharing-with-bbm/
And `line` is Line Messenger: https://media.line.me/howto/en/

Definitely doable.

**Comment by kangismet** [comment]
OK, thanks! waiting for whitelist added

**Comment by Gregable** [comment]
Added this in github just now, but it'll be a few weeks before it goes live.

**Comment by kangismet** [comment]
OK. great.. thanks

**Comment by honeybadgerdontcare** [comment]
This is now live in prod.
