### ISSUE TITLE
link rel=serviceworker instead amp-install-serviceworker

### ISSUE THREAD

**Issue by Jxck** [ampproject/amphtml#6601]
## Short description of your issue:

support `<link rel=serviceworker>` instead `amp-install-serviceworker`.

## How do we reproduce the issue?

by adding Link HTTP header like `Link: </sw.js>; rel=\"serviceworker\""` to AMP HTML response,
chrome adds serviceworker to AMP Page.

`<link rel=serviceworker>` tag in HTML is equivalent semantics.
and if this HTML works as same as Link HTTP header,
amp-install-serviceworker is no more needed.

but currently, `<link rel=serviceworker>` is error like this.

```
The attribute 'rel' in tag 'link rel=' is set to the invalid value 'serviceworker'.
```

so, allow `serviceworker` to whitelist to rel value for link.

## What browsers are affected?

browser which supports <link rel=serviceworker>

## Which AMP version is affected?

this is opt in for new feature, so problem is when to deprecate amp-install-serviceworker.  

## Spec

https://w3c.github.io/ServiceWorker/#link-type-serviceworker

**Comment by cramforce** [comment]
I don't think we can support this. In particular for the cache fallback that uses iframes, the link header is insufficient. On non-cache responses, the header should work just fine.

Closing, but happy to reopen if I missed anything.
