### ISSUE TITLE
Amp-accordion open on hover instead of click

### ISSUE THREAD

**Issue by nsandberg79** [ampproject/amphtml#6602]
Hi was wondering if there was a way to open an Amp-accordion with hover instead of click? 

I recreated a drop down menu with the accordion, but user experience tests have asked for the menu to close on hover instead of clicking.

One other way would be to close the accordion by clicking off of the menu and not having to click the original heading.

**Comment by camelburrito** [comment]
@nsandberg79 As of now there is no way to do both of them (i can't think of a way). Accordion was not meant for that.

CC @ericlindley-g , we could consider building this as a custom form element (with amp-selector) and make the dropdown work with hover/touch/keyboard nav. Leaving it to you to prioritize.

**Comment by nsandberg79** [comment]
Thank you, I currently replaced a drop menu with an accordion to make a desktop site amp compatible.

**Comment by ericlindley-g** [comment]
@camelburrito  — just to explore our options: does this need a custom element, or would it be possible/advisable to do this with CSS, and then just make an templated example available for easy copy/paste in something like AMP Start?

**Comment by camelburrito** [comment]
@ericlindley-g - we might be able to do a CSS solution for a simple :hover non-nested menu dropdown with amp-selector - but i think it will behave like a dropdown and it might not work on click may be we can try :focus. We can give it a shot but i am not too optimistic.

**Comment by caroqliu** [comment]
Closing as hover to toggle is against accessibility best practice. Related resources:

- https://www.w3.org/TR/wai-aria-practices/#accordion
- https://www.accessibility-developer-guide.com/examples/widgets/accordion/
- https://www.accessibility-developer-guide.com/examples/widgets/tablists/
