### ISSUE TITLE
When an AMP extenstion is placed in a <p> tag element.getRealChildren() returns an empty Array

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#6603]
Carousels, accordions and other extensions broken when placed inside a `<p>` tag

http://jsbin.com/zunewa

**Comment by camelburrito** [comment]
@Gregable looks like extensions dont work when placed inside a <p> tag as per the HTML5 spec. We should be throwing a warning/error in such cases.

CC @cramforce

**Comment by cramforce** [comment]
I think the validator will have the same issue. Since it does HTML5 conformant parsing, it cannot see the state intended by the author. We've definitely discussed this before, but it hasn't come up recently.

**Comment by Gregable** [comment]
@cramforce is correct. We don't want the validator to treat two documents which are HTML5 parse equivalent as different (one valid and the other invalid). It would be hard to do this correctly.
