### ISSUE TITLE
Google AdX ads directly within an AMP page

### ISSUE THREAD

**Issue by BenErdos** [ampproject/amphtml#6604]
RE: [amphtml/ads/google/adsense.md](https://github.com/ampproject/amphtml/blob/master/ads/google/adsense.md)

Can this configuration also be used for implementing AdX (Google Ad Exchange) directly on the page?

If so should the type be changed to: 

`<amp-ad width=300 height=250
      type="adsense"
      data-ad-client="ca-pub-2005682797531342"
      data-ad-slot="7046626912">
 </amp-ad>`

**Comment by jasti** [comment]
Yes.

**Comment by BenErdos** [comment]
Thanks Jasti, sorry my comment got clipped. so the type remains adesnse? 

i.e. The only things to change are the data-ad-client and the data-ad-slot?

**Comment by jasti** [comment]
That's right. There is no specific type called AdX.

**Comment by BenErdos** [comment]
Great thanks!
