### ISSUE TITLE
AMP-carousel arrows disables in IE

### ISSUE THREAD

**Issue by pranavbilurkar** [ampproject/amphtml#6606]
Hi All,

I've a AMP page containing both the below controls -

1. amp-carousel
2. amp-accordion

**Issue** - amp-carousel arrow buttons disables when amp-accordion pane is expanded. And if not expanded the carousel arrows works as expected.

**Issue occurs on**- IE 11.

**Note** - The issue does not occur in FF and Chrome only occurs in IE.

When i looked into the DOM i got below difference [see highlighted bold] -

`<div class="amp-carousel-button amp-carousel-button-next" role="button" aria-label="next" aria-disabled="false"></div>` --- FF and Chrome

`<div class="amp-carousel-button amp-carousel-button-next amp-disabled" role="button" aria-label="next" aria-disabled="false" ></div>` -- IE 11

Per investigation, on IE browsers, AMP-Accordion is adding **amp-disabled class** on the AMP-Carousel arrow buttons.

Thanks,
Pranav

**Comment by jridgewell** [comment]
Closing as a dupe of #6591.

**Comment by pranavbilurkar** [comment]
Any update on this??

**Comment by camelburrito** [comment]
This is not a dupe. But this pr fixes the bug

https://github.com/ampproject/amphtml/pull/6400
