### ISSUE TITLE
PopIn's amp-ad plugin is not reflected

### ISSUE THREAD

**Issue by popinuser** [ampproject/amphtml#6607]
Hi,all.
6 days ago, we got popIn pull requests merged.
https://github.com/ampproject/amphtml/pull/6122

However, waiting for 6 days is not reflected in the direction of cdn.

https://cdn.ampproject.org/v0/amp-ad-0.1.js

As a possibility, we believe that there was some operational mistake due to manual merging.
Please support us as soon as possible.

**Comment by jridgewell** [comment]
We have a 1 week canary period, so PopIn's code is in the canary build (you can enable that through the "Dev Channel" switch https://cdn.ampproject.org/experiments.html).

**Comment by jridgewell** [comment]
Also, we'll ship this canary version to production on Thursday, barring any critical bugs.

**Comment by popinuser** [comment]
I was able to confirm that it was reflected. Thank you very much!
