### ISSUE TITLE
Add support for Alexa (analytics)

### ISSUE THREAD

**Issue by MaymanIKD** [ampproject/amphtml#6608]
Does google amp support alexa code

**Comment by rudygalfi** [comment]
Alexa isn't present supported as far as I know. We've attempted to get in touch with the Alexa team for AMP support, but no updates on that yet.

I'm going to rename this issue to make it a feature request.

**Comment by rudygalfi** [comment]
Closing this and adding to our 3P tracker: https://github.com/ampproject/amphtml/projects/15. If anyone at Alexa begins integration work, please re-open and use this to track the pull requests.

**Comment by eric30** [comment]
I worked with publishers in APAC. AMP support for Alexa is critical to pubs since that would be related to the price of their direct-sold inventories when bargaining with advertisers. It seems like a blocking issue for them to adopt AMP.

**Comment by erwinmombay** [comment]
We've had two large publishers in Indonesia mentioning Alexa as being a blocker

**Comment by irvin** [comment]
Yes Alexa is really important in APAC because advertisers and investors all using it as main reference for site traffic.

For now I'm using amp-pixel to send traffic to Alexa but I'd no idea if it's really work or not...

`<amp-pixel src="https://d5nxst8fruw4z.cloudfront.net/atrk.gif?account=_account_id_&randomVar=RANDOM"></amp-pixel>`

**Comment by aliefmaksum** [comment]
Thanks @erwinmombay , I hope there will be a positive update soon about the Alexa support.

**Comment by liangnanwu** [comment]
Alexa supports AMP now, and it has been merged at [ampproject/amphtml/issues/11966](https://github.com/ampproject/amphtml/issues/11966).

**Comment by liangnanwu** [comment]
@rudygalfi sorry, I didn't find this issue before starting the work.
