### ISSUE TITLE
Foreign Fetch SW requests fail

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#6618]
Easily reproably by triggering a foreign fetch request.

```
Uncaught TypeError: Failed to construct 'Request': The origin of 'https://amp.cnn.com/cnn/2016/12/12/politics/russia-hacking-election-senators-donald-trump-angus-king/index.html' should be same as 'https://cdn.ampproject.org'
    at w (core.js:165)
    at C (core.js:359)
    at core.js:423
```

The line that fails is `return new Request(urlWithVersion(url, version), request);`

**Comment by jridgewell** [comment]
Interestingly enough, it's the `referer` property that's causing it to throw. Is there a backup referer field (either a query param or header value) that will log correctly?

**Comment by cramforce** [comment]
Sorry, I don't get what you are saying. Which line is throwing? And why?

**Comment by jridgewell** [comment]
I'm essentially cloning the Request with a new URL: https://github.com/ampproject/amphtml/blob/master/src/service-worker/core.js#L164

```js
new Request(urlWithVersion(url, version), request);
```

The second parameter to `Request`'s constructor is the init param, taking a map of:

- headers
- method
- mode
- credentials
- cache
- redirect
- referrer
- integrity

Duplicating the request with the same `referer` is causing it to throw, for some referer masking reason. The SW (on origin `cdn.ampproject.org`) can't impersonate a request that came from `publisher.com`.

I can instead drop the referrer from the init params, but it'll end up being `about:client`. Or, we can set it to `cdn.ampproject.org/sw.js`, etc. But is there another field on the query string or a header we can set so our logging will correctly identify this request as coming from `publisher.com`?

**Comment by cramforce** [comment]
We actually don't even log the referrer on the server side. Overriding with `cdn.ampproject.org/sw.js` sounds good to me.
