### ISSUE TITLE
Allow user-redirect after form submission

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#6619]
This is a tracking issue for allowing server responses to redirect users after a successful submission. This could be throw expected header like `AMP-Redirect-To: http://...`, or a property on the JSON response `{"redirectTo": "http://..."}`.

**Comment by mastermunj** [comment]
This is very much required. In many cases a successful submission requires redirection to another page.

**Comment by shoxty** [comment]
+1

After submission we would like to redirect users to a "thank you page" that fires our conversion pixels. We would love to see this functionality as well.

**Comment by mkhatib** [comment]
Will start working on this.

Just FYI we do [expose events](https://github.com/ampproject/amphtml/blob/master/extensions/amp-form/amp-form.md#events) that you can hook to and do things like show a lightbox with a thank you message. We also expose [analytics triggers](https://github.com/ampproject/amphtml/blob/master/extensions/amp-form/amp-form.md#analytics-triggers) to allow you to do conversions tracking.

We still want to support redirect after submission but thought to mention these as they might be a better experience to use and cover some of the use cases you mentioned.
