### ISSUE TITLE
hardcoded thirdParty domain in frame.html

### ISSUE THREAD

**Issue by cgorbit** [ampproject/amphtml#6624]
Hi,

why domain is hardcoded in https://github.com/ampproject/amphtml/blob/master/gulpfile.js#L500? Is it better to get it from config.js?

**Comment by dknecht** [comment]
@cgorbit do you want to do a skype and can talk about amp cache?

**Comment by cgorbit** [comment]
I'm afraid, skype in English is hard for me. And my question assume short answer, as I understand.

**Comment by dknecht** [comment]
At Cloudflare we do the re-write as part of build process.

**Comment by cgorbit** [comment]
Okay, thank!
