### ISSUE TITLE
Autocomplete / suggestion field support in amp-form (enhancement)

### ISSUE THREAD

**Issue by fliptheweb** [ampproject/amphtml#6625]
## Short description of your issue:
Implementation of autocomplete field in AMP.

## Long description: 
My company tries to reimplement rich js form to AMP version.
We have a autocomplete field (like react-autocomplete, jquery UI autocomplete, whatever) and I want to use the same functionality in AMP version.
Features:
– fetch remote JSON by XHR;
– custom render with `amp-mustache`;
– standard HTML validation.

For example:
```js
<amp-autocomplete
    action-xhr="//api.com/search?term=search_term"
    name="origin"
    class="suggestions"
    placeholder="Choose your origin city"
    required />

<template type="amp-mustache">
  <div class="suggestions-item" amp-value="">{{text}} ({{iata}})</div>
</template>
```

Is it possible to implement autocomplete in AMP? Let's discuss.

**Comment by cramforce** [comment]
CC @rudygalfi 

Thanks for the report! This is definitely on our radar.

**Comment by rudygalfi** [comment]
We're definitely looking into this. We've also got #3403 open for autocomplete, but I appreciate the additional detail you specified in your request.

**Comment by Rahul007shah** [comment]
Hi Team,

This is Rahul Shah from Priceline.com. We want Typeahead functionality in our home page. User types destination, From, To etc. fields to search for location. **Autocomplete is show stopper** to go live with AMP version of Priceline.com. Autocomplete feature is must in e-commerce applications as a basic feature, which will be useful for e-commerce platform to come on AMP platform.

Thanks
Rahul

**Comment by aghassemi** [comment]
Hi @Rahul007shah. We have started working on supporting autocomplete. Please see and subscribe to #8824 #8825  
/cc @ericlindley-g

**Comment by Rahul007shah** [comment]
Hi @aghassemi Thanks for the update.

**Comment by adelinamart** [comment]
@aghassemi referenced issues are closed. Anything else to do here? Thanks

**Comment by aghassemi** [comment]
All the pieces are complete. Just needs a sample on AmpByExample, tracked under #9698 
@Rahul007shah there is already a sample for this under https://github.com/ampproject/amphtml/blob/master/examples/autosuggest.amp.html which can get you going with the implementation. A more comprehensive sample coming soon with #9698

**Comment by vikulksinghal** [comment]
HI 

I have try to create autocomplete during amp form

https://github.com/vikulksinghal/amp-autocomplete
check it and give mark me if my code help you
