### ISSUE TITLE
Adding margin support to attemptChangeSize

### ISSUE THREAD

**Issue by tlong2** [ampproject/amphtml#6626]
Unless there are any objections, I'd like to add the ability to specify new margin sizes to the attemptChangeSize function in resources-impl.js.

This would change it to something like:
/**
 * @param {!Element} element
 * @param {number|undefined} newHeight
 * @param {number|undefined} newWidth
 * @param {number|undefined} newMarginTop
 * @param {number|undefined} newMarginBottom
 * @return {!Promise}
 * @protected
 */
attemptChangeSize(element, newHeight, newWidth, newMarginTop, newMarginBottom) {
...
}

The mutateWork_() function would then include any margin changes in its calculation of the height increase and allow/disallow the size change and adjust any scrolling accordingly. This will probably require adding knowledge of margins to resource.js. They can be determined using window.getComputedStyle().

This will be useful for the <amp-auto-ads> feature: https://github.com/ampproject/amphtml/issues/6196

**Comment by dvoytenko** [comment]
@tlong2 Could you please clarify this? The 3p embed would ask for a new margin?

**Comment by dvoytenko** [comment]
@tlong2 sorry, just fully realized the scope of your request. I think, yes, we have to support this API. Although, I think we just should go ahead and add a single `opt_margin` attribute with all four sides for margin.

**Comment by dvoytenko** [comment]
@tlong2 This request is done, right?

**Comment by tlong2** [comment]
Yep sorry, forgot to close.
