### ISSUE TITLE
<amp-ooyala> should support autoplay

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#6628]
Related to PR https://github.com/ampproject/amphtml/pull/6466

https://github.com/ampproject/amphtml/pull/6466 implements the video interface for `<amp-ooyala>`, however due to changes needed in the 3P Ooyala player (see https://github.com/ampproject/amphtml/pull/6466#issuecomment-265611391 for details) autoplay does not work on _**mobile**_ yet.

After the 3P changes are launched by the Ooyala team, we need to bring back `autoplay` related documentation and tests:

- [ ] add autoplay to examples/ooyalaplayer.amp.html
- [ ] add autoplay attribute in validator-amp-ooyala-player.protoascii
- [ ] add autoplay documentation in amp-ooyala-player.md
- [ ] add video-interface tests to test/fixtures/video-players.html and test/integration/test-video-players.js

/cc @mityaha @spaddon Tracker for autoplay support. If you can, please update this issue when the required changes are launched in the Ooyala player, I can take care of updating the `amp-ooyala-player` component on the AMP side.

**Comment by mityaha** [comment]
@aghassemi , I made changes you requested.

**Comment by adelinamart** [comment]
Hi,
It seems some changes pending 3P were merged. Is this blocked? Thanks.

**Comment by aghassemi** [comment]
@mityaha @spaddon Any updates on this from your side? (see https://github.com/ampproject/amphtml/pull/6466#issuecomment-265611391 for a refresher of what Ooyala player needs to change before this get unblocked).

**Comment by spaddon** [comment]
Ali,

What needs to be changed is clear, but not clear what is currently Blocked
(and would be unblocked)?

The current situation is that we have found a lot of other holes that we
are doing in a batch release that many of our customers really need to make
the AMP implementation useful for them. The biggest one is that we need to
enable the Google IMA plugin, so they can monitize. We're working on adding
that along with the required items already identified.

-Steve Paddon

**Comment by aghassemi** [comment]
@spaddon `autoplay` for `amp-ooyala` on mobile platforms is currently blocked until the two items (e.g. `playsinline` attribute and `mute()` setting `muted` property instead of `volume=0`) mentioned in https://github.com/ampproject/amphtml/pull/6466#issuecomment-265611391

**Comment by aghassemi** [comment]
@mityaha @spaddon just a friendly ping to see if there has been any progress on https://github.com/ampproject/amphtml/pull/6466#issuecomment-266754781
