### ISSUE TITLE
[amp-analytics] continuousTimeMin in "hidden" trigger does not work as expected

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#6632]
It could be by design, but I found the behavior weird.

As a background, "hidden" trigger fires when user leaves the doc. Extra conditions can be specified via VisibliitySpec.

If `continuousTimeMin=1000` is specified, I would expect as long as the selected element has been visible continuously for more than 1s, no matter if it's still visible at the time user leaves the page, we should fire when user leaves page.

However, the [current implementation](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/visibility-impl.js#L554) does not work like that. The logic uses the current continuous visible time to compare with the criteria. The value is 0 if the element is not currently visible when user leaves the page. So it will not fire.

I think the fix should be to replace `state[CONTINUOUS_TIME]` by `state[MAX_CONTINUOUS_TIME]`.

@avimehta @dvoytenko thoughts?

**Comment by dvoytenko** [comment]
@lannka I agree.
