### ISSUE TITLE
this.visibilityObservable_ can be null

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#6644]
Missing null check [here](https://github.com/ampproject/amphtml/blob/43f624171de67d305e86197d51ef30e3a6f1ae9c/src/service/document-state.js#L120).

In fact, there might be other places missing null check due to PR #6496

**Comment by cramforce** [comment]
There were some follow up comments on #6496. Maybe should be rolled back and forward. 

Did this make the canary cut? CC @jridgewell

**Comment by cramforce** [comment]
Also CC @chenshay

**Comment by jridgewell** [comment]
This is in canary, but I've not seen an error for it yet.

**Comment by chenshay** [comment]
change reverted
