### ISSUE TITLE
Provide good helpers for URL security

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#665]
and audit code for them.
Should definitely filter out javascript: URLs and similar.

**Comment by rudygalfi** [comment]
Targeted to M2. Please unmark "Stale?" label if still needed; else close.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
