### ISSUE TITLE
Uncaught TypeError: Cannot read property 'width' of null

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#6652]
```
impl.237-RELEASE.js:7 Uncaught TypeError: Cannot read property 'width' of null(…)
TRCRBox.isAMPvisible	@	impl.237-RELEASE.js:7
TRCRBox.getEventVisibility	@	impl.237-RELEASE.js:7
(anonymous function)	@	impl.237-RELEASE.js:3
(anonymous function)	@	impl.237-RELEASE.js:3
(anonymous function)	@	impl.237-RELEASE.js:3
(anonymous function)	@	impl.237-RELEASE.js:3
f	@	impl.237-RELEASE.js:3
(anonymous function)	@	impl.237-RELEASE.js:3
(anonymous function)	@	impl.237-RELEASE.js:3
TRC.dispatch	@	impl.237-RELEASE.js:3
D	@	loader.js:2
C	@	loader.js:2
O	@	loader.js:2
(anonymous function)	@	loader.js:2
(anonymous function)	@	loader.js:2
window.IntersectionObserver.threshold	@	integration.js:446
```
Sample page: https://www.google.com/amp/parma.repubblica.it/sport/2016/10/31/news/dal_parma_al_pisa_corrado_riprova_la_scalata_nel_calcio-151014019/amp/

**Comment by muxin** [comment]
Might be related to https://github.com/ampproject/amphtml/pull/6503

**Comment by zhouyx** [comment]
they tried to read `var g=this.rootBounds.width,h=this.rootBounds.height;` here. But in native 
native IntersectionObserver `rootBound` is set to null for element in cross domain iframe. 
either they need to fix the code by not depending on `rootBound` or we cannot use native IntersectionObserver.

**Comment by zhouyx** [comment]
Close this issue by not using native IntersectionObserver at this time.
