### ISSUE TITLE
Internet Explorer Amp-carousel not working

### ISSUE THREAD

**Issue by nsandberg79** [ampproject/amphtml#6653]
Amp-Version 1481320064935

Internet Explorer 10 & 11

I have created an amp-carousel and upon testing, I have notice it does not move on IE 10 & 11. I have not found any other issues in searches as of yet. Would you like me to submit a code snippet?

As some of my carousels do work within the pages.

**Comment by camelburrito** [comment]
@nsandberg79 please share a link to your page (or a jsbin)

**Comment by nsandberg79** [comment]
http://192.169.154.82/shop/amp-cart.php?friendlyname=mats/foam-floor-mats.php

**Comment by camelburrito** [comment]
#6400 seems to have fixed it (its already on our dev channel) will go live sometime tomorrow.
I already verified on your page by opting into the dev channel. (cdn.ampproject.org/experiments.html)


Also - unrelated - IE complains of a few mismatched tags (i found one extra </li>) on your html. I think it might cause a few hiccups.
