### ISSUE TITLE
amp-pixel never fires with misconfigured amp-experiments

### ISSUE THREAD

**Issue by cpapazian** [ampproject/amphtml#6658]
When amp-experiment script is loaded, but no element is included in AMP HTML and amp-pixel includes variable substitution for `VARIANTS` or `VARIANT(...)`, it never fires. It appears to be waiting for the amp-experiment element to load, but it does not exist in AMP HTML.

see: https://output.jsbin.com/xokiduxaye

Notice that `https://www.ampproject.org/static/img/logo-blue.svg?foo=BAR` loads in the network tab, but https://www.ampproject.org/static/img/logo-blue.svg?experiments=...` does not. 

If the amp-experiment script tag is removed, the AMP pixel with VARIANTS does fire and there is a warning message in the console.

see: https://output.jsbin.com/tamaleqiqo

This is what I would expect when the amp-experiments tag is omitted.

**Comment by lannka** [comment]
Both examples you gave are working as intended.

The 2nd one actually gave you the right error message: you need to configure your `amp-experiment`. 

Please refer to the [spec](https://github.com/ampproject/amphtml/blob/master/extensions/amp-experiment/amp-experiment.md) for how to configure an experiment.
