### ISSUE TITLE
amp-carousel issue

### ISSUE THREAD

**Issue by sgnarola** [ampproject/amphtml#6660]
Please walk through the following steps for reporting an issue about AMP:
![carausel2](https://cloud.githubusercontent.com/assets/24565044/21178496/d0e289b2-c215-11e6-9f37-d2515a809eb9.png)
![carausel1](https://cloud.githubusercontent.com/assets/24565044/21178497/d0ef6e02-c215-11e6-8985-718a3af412ff.png)

- Please ask general questions about AMP over on stackoverflow under the AMP HTML tag: http://stackoverflow.com/questions/tagged/amp-html
- Please ask/post questions/problems related to Google Search in Google's AMP forum: https://goo.gl/utQ1KZ

## Short description of your issue:

Start by deleting everything above this including this sentence :)

## How do we reproduce the issue?

Please post a public URL and ideally post a reduced test case. E.g. on jsbin.com that exhibits only your issue and nothing else.

1. Step 1 to reproduce visit https://alternativeeconomics.co/minmedia/blogline/53414-oxford-university-joins-the-list-of-liberal-institutions-urging-gender-neutral-pronouns in chrome
2. whenever is visit this page, most of the time it shows me list of images in-place of carousel, i have followed the steps given by google to generate amp carousel. It works fine in firefox browser, but doesn't work well in chrome browser.

## What browsers are affected?

All browsers? Some specific browser? What device type?

## Which AMP version is affected?

Is this a new issue? Or was it always broken? Paste your AMP version. You can find it in the browser dev tools.

**Comment by jridgewell** [comment]
It's not a valid amp page.

**Comment by sgnarola** [comment]
On this site scripts are important, it shows validation error for js only. But why amp carousel is not working?
