### ISSUE TITLE
Standardize A4A signature header

### ISSUE THREAD

**Issue by dknecht** [ampproject/amphtml#6667]
The current proposal is to change it from `X-Ampadsignature` to  something more inline with the rest of the amp headers like `AMP-Ad-Signature` 
@taymonbeal @oliy @ipostelnik

**Comment by jasti** [comment]
@taymonbeal is this on your list? @keithwrightbos

**Comment by keithwrightbos** [comment]
Yes, we are finalizing the design and will start implementation soon.  Thx

**Comment by jasti** [comment]
I believe this is done, @taymonbeal ?

**Comment by jasti** [comment]
Ping @taymonbeal

**Comment by taymonbeal** [comment]
Sorry for the delays on this. Filed #7618.

**Comment by jridgewell** [comment]
Closing this for #7618.
