### ISSUE TITLE
test-amp-ad-3p-impl.js is failing when run alone

### ISSUE THREAD

**Issue by bradfrizzell** [ampproject/amphtml#6670]
## Descriptions
Currently, tests in test-amp-ad-3p-impl are not working. Getting:
` Uncaught TypeError: Cannot read property '__AMP_TOP' of undefined `
`Error: Uncaught TypeError: Cannot read property '__AMP_TOP' of undefined`

## How do we reproduce the issue?
On the master branch, run: 
`gulp test --files=extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js`

## What browsers are affected?
Tested on Chrome on Linux, on two different machines with separate up-to-date copies of the repo.

## Which AMP version is affected?
Current master branch

**Comment by mkhatib** [comment]
@bradfrizzell thanks for filing. Does running `gulp test` by itself have the same failure?

**Comment by bradfrizzell** [comment]
No, running `gulp test` by itself passes all tests.

**Comment by jasti** [comment]
Ping @lannka

**Comment by adelinamart** [comment]
@lannka any updates here? Thanks

**Comment by lannka** [comment]
We can prioritize it in next sprint.
