### ISSUE TITLE
dev warn if script for <amp-ad>, <amp-embed> and <amp-video> are not included.

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#6681]

**Comment by lannka** [comment]
FYI, validator now prints warning for `amp-ad` `amp-embed` while script is missing .

Why `amp-video`, `amp-video` is still builtin extension, no?

**Comment by aghassemi** [comment]
oh cool, is that done by `also_requires_tag_warning: "amp-ad extension .js script"`?

`amp-video` is moving out of core with https://github.com/ampproject/amphtml/pull/6671

**Comment by zhouyx** [comment]
oh! Good to know validator is printing warnings.

**Comment by lannka** [comment]
yep, I guess so you can do similar thing

**Comment by aghassemi** [comment]
cool! validator warning should be enough, don't think we need dev warning on top of that. Closing issue.
