### ISSUE TITLE
Can Anyone Help 

### ISSUE THREAD

**Issue by kingofkings25** [ampproject/amphtml#6689]
Can Anybody Help me,i am getting this issue:- The mandatory tag 'amphtml engine v0.js script' is missing or incorrect. Learn more.. I have tried all the methods mentioned here. My site is:- [http://www.noisygeek.com/](url)

**Comment by lannka** [comment]
@kingofkings25 Your page is not corretly AMPlified. (I see custom scripts). please follow the [tutorial](https://www.ampproject.org/docs/get_started/create/basic_markup).
