### ISSUE TITLE
gulp test executed more tests than there were...

### ISSUE THREAD

**Issue by bradfrizzell** [ampproject/amphtml#6690]
## Description
I was working on my feature branch running tests just now. I was running `gulp test --files=extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js --watch` while making changes, then checking the test output. Then, the test suite spit out the following: 
`Chrome 55.0.2883 (Linux 0.0.0): Executed 15 of 14 (5 FAILED) (22 secs / NaN secs)`

So... 15 out of 14 tests...? What? 

## How do we reproduce the issue?

I pushed a branch with exactly what the state of my branch was at the time. Branch = fifteen-of-fourteen
You can also check out the entire terminal output here: http://pastebin.com/5MryBFC2
Not sure if running the command again will make it happen, but this was the command: 
`gulp test --files=extensions/amp-ad/0.1/test/test-amp-ad-3p-impl.js --watch`

## What browsers are affected?
Ran this on Chrome on Linux

**Comment by lannka** [comment]
Can't reproduce. 
The test when ran alone fails with
```
Executed 8 of 14 (1 FAILED) 
```
which is tracked as another bug: #6670
