### ISSUE TITLE
Place arbitrary html in custom ads

### ISSUE THREAD

**Issue by orrybaram** [ampproject/amphtml#6694]
This is a continuation of https://github.com/ampproject/amphtml/issues/5541

We would like a method to test custom amp ads in a development environment. It would be ideal if we could add any arbitrary html to the `ad-amp` tag. The current [custom ad](https://github.com/ampproject/amphtml/blob/master/ads/custom.md) currently only supports passing in variables to a template via a remotely fetched json file. This works great for testing single image adds, but not ads with custom css animations / internal tracking. It would be nice if we could optional output an html file into ad as well. @cramforce Does this make sense? To answer your question about using doubleclick as an ad type. We could do that (and do in production) but development of ads would require the extra step of creating creatives for each ad and waiting for it to serve (which usually takes 10-15mins) which is not ideal.

**Comment by cramforce** [comment]
So this is for development only? I think just making an invalid AMP doc that has some JS to do what you want is the better solution then!

**Comment by orrybaram** [comment]
Yeah, this is what we currently do! Visually we can recreate the ads in any env. The big thing for us though is that each ad has a custom viewability tracking script that uses amp's parent.context in order to trigger certain events. Here's an example:
```js
window.parent.context.observeIntersection(function (changes) {
  changes.forEach(function (change) {
    if (window.innerHeight / 2 <= change.intersectionRect.height) {
      self.emit('in-viewport');
      $adWrapper.classList.add('in-viewport');
    } else {
      $adWrapper.classList.remove('in-viewport');
      self.emit('viewport-outside');
    }
  });
});
```
Previously we verified this worked by testing on live ads, but that workflow was awful!

**Comment by cramforce** [comment]
I think you can use this feature to do exactly what you need:
https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad/amp-ad.md#running-ads-from-a-custom-domain

**Comment by orrybaram** [comment]
This is what I originally tried, trying again now. Sorry to be a pain in the ass. Im kinda confused about the [remote.html](https://github.com/ampproject/amphtml/blob/master/3p/remote.html) file. Im serving it on a local node https server. When I go to the page, i get `amp-remote:21 Uncaught ReferenceError: draw3p is not defined(…)`. It looks like the script up top is looking for a search string with `<number>-canary`. When i add ?123-canary to the url the script gets added, but its an invalid link. Any idea what's going on here?

**Comment by orrybaram** [comment]
To clarify that ^ happens when I actually go to `https://localhost:9666/amp-remote`. 
I don't get the same error in the actual amp layout, but i do get errors about the type being invalid. Here's what simple version of the project:

#### remote.html
```html
<!-- ... -->
<script>
    draw3p(function () {
         // i assume this is where you fetch the ad? It's unclear.
        return 'Hello!'
     },
      ['allowed-ad-type1'],  ['localhost']);
  </script>

<!-- ... ---
```

#### amp.html
```html
<!-- ...  -->
<meta name="amp-3p-iframe-src" content="https://localhost:9666/amp-remote">
<!-- ... -->
<amp-ad width="300" height="250" type="allowed-ad-type1"></amp-ad>

```

#### errors
```
error.js:78Type "allowed-ad-type1" is not supported in amp-admd @ error.js:78b.build @ error.js:58f.build @ resource.js:268Ig @ resources-impl.js:372f.upgraded @ resources-impl.js:479b.Zb @ custom-element.js:615(anonymous function) @ custom-element.js:916
log.js:244
Uncaught Error: failed to build: amp-ad#2: Type "allowed-ad-type1" is not supported in amp-ad​​​ _reported_(…)
```

I think I'm missing a piece somewhere. Thanks for you help and patience!

**Comment by cramforce** [comment]
`allowed-ad-type1` should probably be `doubleclick` in your case.

You get `config` passed into the callback passed to `draw3p` and a `done` argument. When your code gets called, you can do whatever you want. Call done, if you want the default ad rendering to happen.

**Comment by orrybaram** [comment]
Thanks, think I'm getting closer to understanding. I've gotten the draw3p function working with the `doubleclick` ad type like you suggested. It seems like the callback lets me change up the config that gets sent to dfp. I'm still confused as to how I would actually render a custom ad to the page.

**Comment by orrybaram** [comment]
Ok man, on the home stretch theres just one more thing I can't figure out. If you look at the image below, you can see that the test div gets appended. But, the iframe gets the style `visibility: hidden` added to it and about ~10 seconds after page load the iframe gets removed


<img width="786" alt="screen shot 2016-12-15 at 3 35 30 pm" src="https://cloud.githubusercontent.com/assets/723579/21241143/5076fade-c2dc-11e6-9916-001aec24e69f.png">

### after 10s
<img width="836" alt="screen shot 2016-12-15 at 3 40 28 pm" src="https://cloud.githubusercontent.com/assets/723579/21241265/d5ae763c-c2dc-11e6-9b75-43ade85e784a.png">

**Comment by cramforce** [comment]
If you don't use an actual ad network to render the ad, you will have to
check out the ad network documentation. Note, that that might break under
you, which might be fine for testing. You will need to call a method on
context to let AMP know render is done.

**Comment by orrybaram** [comment]
@cramforce WOO! finally got it to work. Eventually what i did was create a test campaign in dfp, and then added this: 
```js
draw3p(function(config, done) {
      var iframe = document.createElement('iframe');
      iframe.src = '/iframe';
      document.body.appendChild(iframe);
      done(config)
    }
```
Which adds our own iframe with the iframe src we serve up locally.
Thanks for your help!!

**Comment by milesthedisch** [comment]
Hey @cramforce excuse my ignorance but Is it possible to add a `amp-ad` that supports srcdoc's? This would be particularly useful for developers like myself to test and debug amp-ad's. I understand there are security implementations for production environments and 3p ad scripts, but the workflow to get a amp-ad's working on a local build is quite indirect compared to the "old" way of appending a srcdoc to an friendly iframe. I know the `amp-iframe` allows srcdoc if given the correct sandbox attributes. Can we do the same with `amp-ad`

```html
<amp-ad
  type="test"
  sandbox="allow-scripts"
  srcdoc="<div id=\"content\">content</div><script>try{window.parent}catch(e){content.innerHtml="new content"}</script>" <!-- This should be escaped -->
>
</amp-ad>
```

**Comment by cramforce** [comment]
Could you explain your use case a bit more?

**Comment by jgladden** [comment]
This might be a beneficial approach for my issue as well, although I am looking for a production friendly solution. My client uses an ad network not yet supported by google amp. My initial approach was to use amp-iframe to iframe in the ads, but the documentation states this is not allowed. I am now considering using the draw3p createElement iframe src strategy mentioned above but ideally would prefer to just point to the ad iframe src as an attribute of the amp-ad tag.

**Comment by cramforce** [comment]
@jgladden Adding an ad network is super easy. That might be the simplest path. If interested we can guide you through the process.

**Comment by jgladden** [comment]
@cramforce That sounds great. I do not work for the ad network but would be happy to do it on their behalf if possible. They do not seem interested in doing it themselves. Even if I can not do it for them, if I could pass them clear instructions on how to do it themselves I might be able to get them to budge.

**Comment by cramforce** [comment]
@zhouyx @lannka Could you point @jgladden to the latest docs and sample PRs for a simple non-A4A ad network integration?
