### ISSUE TITLE
A4A Fake Impl Provide Key Fetch To Ensure Hermetic

### ISSUE THREAD

**Issue by keithwrightbos** [ampproject/amphtml#6696]
## Short description of your issue:

amp-ad-network-fake-impl includes creative and signature as part of its data however it fetches production public keys causing it to fail if/when the key set rotates.  Need to provide the keyset as part of the implementation in way that ensures it continues to no override base A4A behavior

**Comment by keithwrightbos** [comment]
Fake impl is currently failing likely because of key rotation.

**Comment by keithwrightbos** [comment]
Simplest solution would be to create a fake key provider that points to a localhost:8000 address which returns a fixed response.  Assigning to @tdrl to implement.

**Comment by adelinamart** [comment]
@tdrl any updates here? Thanks

**Comment by lannka** [comment]
Seems to be obsolete. Fake impl is working fine now.
