### ISSUE TITLE
Production bug - amp-sidebar z-index CSS conflicts with fixed layer code.

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#6705]
/extensions/amp-sidebar/0.1/amp-sidebar.css contains

`amp-sidebar { z-index: 9999!important }`

However the fixed layer migration code sets element level CSS on the `amp-sidebar` to 

`style="pointer-events: initial; z-index: 20003; top: calc(54px);"`

Which fails due to the `!important` in the sidebar css.

**Comment by jpettitt** [comment]
Not fixed: see https://www.google.com/amp/cdn.relaymedia.com/amp/www.civilbeat.org/2016/12/ige-hawaiis-food-sustainability-a-priority-in-his-budget-plan/#amph=1 and https://www.google.com/amp/amp.gospelherald.com/articles/68178/20161122/christian-forces-retake-ancient-monastery-from-isis-vow-to-rebuild-we-are-stronger-than-they-imaged.htm#amph=1 for examples of how the sidebar is obscured by the fixed header when in a viewer. We really need to get the !important removed from the sidebar z-index so we can make this choice ourselves.

**Comment by jridgewell** [comment]
Fix isn't in canary or prod yet, just on master. Looks like we'll be cutting another today to fix this.

**Comment by jridgewell** [comment]
Also, the issue you report in https://github.com/ampproject/amphtml/issues/6705#issuecomment-267664622 is fixed by https://github.com/ampproject/amphtml/pull/6706.

**Comment by jpettitt** [comment]
Ah I took closed to mean deployed
