### ISSUE TITLE
lightbox-viewer should close sidebars

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#6712]
sidebar's z-index is higher than lbv, we should ensure if lbv is opened from something in the sidebar, sidebar is closed. See https://github.com/ampproject/amphtml/pull/6711#issuecomment-267500147

**Comment by adelinamart** [comment]
@aghassemi are there any updates here? Thanks

**Comment by aghassemi** [comment]
just a low priority bug.
