### ISSUE TITLE
DMCA Request

### ISSUE THREAD

**Issue by lamaupin** [ampproject/amphtml#6713]
My name is Maria Alexander. Someone has provided my content to create an AMP project:

https://cdn.ampproject.org/v/s/mariaalexander.net/2013/06/14/why-i-hate-most-photos-and-drawings-of-women-with-swords/amp/?amp_js_v=6#origin=https%3A%2F%2Fwww.google.co.uk&exp=a4a%3A0&channelid=0&cid=1&dialog=0&prerenderSize=1&visibilityState=prerender&paddingTop=54&history=1&p2r=0&horizontalScrolling=0&csi=0&referrer=https%3A%2F%2Fwww.google.co.uk&storage=1&viewerUrl=https%3A%2F%2Fwww.google.co.uk%2Famp%2Fs%2Fmariaalexander.net%2F2013%2F06%2F14%2Fwhy-i-hate-most-photos-and-drawings-of-women-with-swords%2Famp%2F

Please take this down immediately. I didn't provide this content, and I'm the owner. Here's the original post:

https://mariaalexander.net/2013/06/14/why-i-hate-most-photos-and-drawings-of-women-with-swords/

Thank you!

Sincerely,

Maria Alexander

**Comment by uncompiled** [comment]
This is happening because your CMS (WordPress) has the AMP plugin enabled.

You can see this content at the source:
https://mariaalexander.net/2013/06/14/why-i-hate-most-photos-and-drawings-of-women-with-swords/amp/

If you disable the AMP plugin in WordPress, the content should eventually expire.
