### ISSUE TITLE
Missing parameters from amp-analytics Google Analytics request on certain accounts

### ISSUE THREAD

**Issue by xgretsch** [ampproject/amphtml#6714]
When a Google Analytics property is set up in a particular way, parameters such as "cd1" or "cg2" (custom dimensions or content groups) disappear from the "collect" call to Analytics and the information is not logged.

## How do we reproduce the issue?

See the code in [http://output.jsbin.com/hamazex], which is essentially the simplest possible code for `amp-analytics`, with the addition of a cd1 parameter.

Here is the relevant code:
```
<script async custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>
...
<amp-analytics type='googleanalytics' id='myamppage'>
<script type='application/json'>{"requests":{"pageviewWithCds":"${pageview}&cd1=MyCustomValue"},"vars":{"account":"UA-2993209-3"},"triggers":{"trackPageview":{"on":"visible","request":"pageviewWithCds"}}}</script>
</amp-analytics> 
```

Run it and observe the following call to Google Analytics:
```
https://stats.g.doubleclick.net/r/collect?v=1&aip=1&t=dc&_r=3&tid=UA-2993209-3&cid=amp-PKlrqV5acHC1a-VyvzS59ePh70Z16kVIBCLtI2Hwk68HenYqmMEJZcPYb_PNAZ9L&jid=0.49705940948446514&_v=a1&z=0.2638129200599211
```
Note the following:

1. Because of the settings on the account, this has gone to doubleclick.net, not to google-analytics.com
2. There is no cd1 parameter, in spite of this being specified in the markup.

If you use a GA account configured to go to google-analytics.com/collect, there is no problem: the parameters are included correctly.

Update: a newly created GA account, with no special features enabled, goes to google-analytics.com. It's switched to doubleclick by one of the following settings in Google Analytics Admin: "Enable Demographics and Interest Reports", "Remarketing" or "Advertising Reporting Features" - it's hard to tell which, because the system takes several hours to respond.

## What browsers are affected?

My test setup is Chrome / OS X. I very much doubt that it's browser-related.

## Which AMP version is affected?

Version 1481320064935

**Comment by jridgewell** [comment]
This is due to Chrome not showing redirected XHR requests in the Network DevTools. Testing in Firefox, I see two XHRs:

1. POST to www.google-analytics.com
  - Includes extra params
  - Returns 302 redirect to stats.g.doubleclick.net
2. GET to https://stats.g.doubleclick.net
  - No extra params

Is your data being logged incorrectly in doubleclick.net?

**Comment by jpettitt** [comment]
Chrome bug https://bugs.chromium.org/p/chromium/issues/detail?id=675789

**Comment by xgretsch** [comment]
Wow - didn't see that answer coming! My impression is that data was not being logged properly in doubleclick.net. However, it's difficult to tell precisely because of the time lags involved: it can sometimes take over a day before details become visible. When I'm back from leave, I'll investigate further: for now, I've moved the analytics for the AMP pages to a separate property, which is non-ideal but an adequate interim.

Thanks for checking this out.

**Comment by jpettitt** [comment]
The fix for the Chrome bug has been committed and was in the canary version 57.0.2979.0 as of 2017-01-12
