### ISSUE TITLE
Deprecate XHR requireAmpResponseSourceOrigin param

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#6716]
The new param `ampCors: boolean` introduced by #6637 should replace the existing `requireAmpResponseSourceOrigin`. 

No new code should specify `requireAmpResponseSourceOrigin`. Rather, they should use `ampCors: false` to turn off AMP CORS, which means no `__amp_source_origin` in XHR URL, and no check for AMP_SOURCE_ORIGIN response header.

We will make `ampCors` defaults to `true`. (Or false? @cramforce thoughts? Do we encourage people to enable AMP CORS?).

For backward compatibility, will change the existing code to include `requireAmpResponseSourceOrigin: false` explicitly if they still want the  `__amp_source_origin` in request, but no check for response.

**Comment by cramforce** [comment]
Correct. Turning it off should only be done with significant thought.
