### ISSUE TITLE
How to handle nonces in forms?

### ISSUE THREAD

**Issue by weeblr** [ampproject/amphtml#6717]
Hi

Working with Joomla and Wordpress, and adding AMP support to some plugins, I hit an issue where most of them use nonces, implemented as hidden input.

This works fine when the AMP pages are served from the source origin, but will fail when served from the CDN cache, as the nonce is invalid.

Is there a recommended way to handle this? how can amp-form be secured that way?

Thanks and regards

**Comment by mkhatib** [comment]
I am assuming this is to protect against XSRF, here's [AMP recommendation of how to protect against XSRF](https://github.com/ampproject/amphtml/blob/master/extensions/amp-form/amp-form.md#security-considerations).

If you'd still rather use the nonce approach, you **might** be able to use `amp-fresh` to pull new tokens and skip the cache for that part of your page. It might also be possible to use `amp-list` to achieve the same. 

Please re-open if this doesn't answer your question.
