### ISSUE TITLE
Are JSON-LD properties allowed to be set dynamically for amp-ad?

### ISSUE THREAD

**Issue by computapars** [ampproject/amphtml#6719]
Currently we use Doubleclick key/values to test ads. We have it set in the url with a query parameter if testing ads should be loaded.

Ex: http://www.foo.com/?dfp_test=on

We use inline JS to detect whether that pattern is true to initiate the ad call with that targeting option set. Since AMP doesn't allow any inline JS, are there other ways to dynamically set the AMP-AD Targeting attribute so that we can toggle the test settings on and off?

It looks like JSON-LD scripts can be added via Google Tag Manager but for Google Tag Manager Amp containers, no Tags are available that would do that. Appreciate any ideas on how others have solved this problem even if its targeting within Doubleclick line items.

**Comment by lannka** [comment]
@computapars do you own the server code? If so, I think this is something better handled in the server right?

**Comment by computapars** [comment]
@lannka we do. I'll talk to my BE team to see how we can process that. thanks for the suggestion.

**Comment by jeannieh** [comment]
Given that machine learning, AMP, and JSON-LT structured data are growing in importance for digital marketers, it will be very helpful to have this work for Google Tag Manager Amp containers.

**Comment by adelinamart** [comment]
@lannka is there any new FR we need to open here? Thanks.

**Comment by jridgewell** [comment]
Could this be handled with `<amp-experiment>`?

**Comment by lannka** [comment]
`amp-experiment` is currently only controls CSS styling.

@computapars @jeannieh I'm not sure I fully understand the requirements.
Do you want to pass a variable via page URL to your amp-ad, or do you want to have AMP to have Google Tag Manager support and pass down the data via GTM container?

If it's the former, I suggest a server side impl. If it's about GTM, we do have [some support](https://analytics.googleblog.com/2016/10/google-tag-manager-giving-mobile.html). @avimehta our expert on GTM.

**Comment by jasti** [comment]
Please reopen if this is still an issue.
