### ISSUE TITLE
The Ooyala component's JS is giving a 404 from the AMP CDN

### ISSUE THREAD

**Issue by tcmg** [ampproject/amphtml#6731]
## Short description of your issue:

The Ooyala player "required script" is giving a 404 from the AMP CDN.

## How do we reproduce the issue?

Read the documentation for the Ooyala component player here:

https://www.ampproject.org/docs/reference/components/amp-ooyala-player

1. Create a test page including the "Required Script" JavaScript component library for Ooyala. 
2. The page will fail to load the player because the script will 404.

**Alternatively**, just visit the Required Script URL here:

https://cdn.ampproject.org/v0/amp-ooyala-player-0.1.js

And you'll see the URL gives a 404.

## What browsers are affected?

All browsers.

## Which AMP version is affected?

I'm not aware of whether this is a new issue or if it was always broken. All versions of AMP are likely affected presently since this isn't a bug with AMP itself, it's a bug with loading the Ooyala player's script.

**Comment by jridgewell** [comment]
amp-ooyala has been merged into the codebase, but it's not been released yet. You can enable canary [here](https://cdn.ampproject.org/experiments.html) to test for now.
