### ISSUE TITLE
Make amp-img srcsets more closely fit the device resolution

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#6734]
As discussed on the AMP Slack:

Currently, on an iPhone 6 (native resolution 750x1334), amp-img selects the 900w version of an image instead of the 800w version. You can test with the sample at the bottom -> https://ampbyexample.com/components/amp-img/

//cc @dvoytenko

**Comment by dvoytenko** [comment]
See https://github.com/ampproject/amphtml/blob/master/src/srcset.js#L214-L216

**Comment by cramforce** [comment]
What does native srcset do?

**Comment by dvoytenko** [comment]
The spec is vague. 

> In a user agent-specific manner, choose one image source from source set.

Chrome returns strictly the mathematically closest. Safari always returns the next equal or higher.

I was looking to make a compromise here and return higher up to a point. I'm pretty sure I just miss a basic edge condition. Should be easy enough to fix.
