### ISSUE TITLE
Can't see images in AMP!

### ISSUE THREAD

**Issue by willsmith7** [ampproject/amphtml#6736]
Hello, i'm desperate! Images are not showing in my AMP pages of my Wordpress website, Empty white spaces are shown instead of images.

Example of page: https://goo.gl/jdSPNh
Here's a link of a random image: data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7

## What browsers are affected?

All browsers

## Which AMP version is affected?

I do use AMP plugin by Automattic for Wordpress, version 0.3.3. I also use Photon CDN and WP Fastest Cache Plugin integrated with Photon CDN.

**Comment by lannka** [comment]
This data URL is a 1x1 pixel GIF. Can you check if you had the right image on your page?

**Comment by jridgewell** [comment]
Checking the HTML source code of your page, you've somehow replaced every image with the same 1x1px transparent GIF, which is what AMP is rendering. This is likely some interaction with Photon.
