### ISSUE TITLE
Feature request: amp-accordion to add a flag so it only expand one section at a time.

### ISSUE THREAD

**Issue by stonezhong** [ampproject/amphtml#6737]
## Short description of your issue:
The amp-accordion allow expand multiple section at a time. I need a feature that an accordion to only expanding one section a time, for example, like the demo in https://jqueryui.com/accordion/#collapsible

## How do we reproduce the issue?
https://ampbyexample.com/components/amp-accordion/
Click section 1, and click section 2, you see both sections are expanded

## What browsers are affected?
All browsers

## Which AMP version is affected?
1.0

**Comment by zhouyx** [comment]
cc @ericlindley-g

**Comment by jpettitt** [comment]
This could lead to content jumps if a section above that's closing is shorter than the lower section that's opening, I know @cramforce has strong view on content jumping ...

**Comment by ericlindley-g** [comment]
Agreed w/ @jpettitt on the risk here, but generally this seems like a nice enhancement to the accordion, maybe configured via an attribute, so as not to disrupt current implementations, but allow for a developer option. 

User interaction is a pretty strong signal of the user's intent and focus, so maybe we can make sure the click-target (the header of the accordion that the user has tapped/clicked on) remains in the same position in the viewport before and after tap/click.

Will be curious to hear thoughts from @camelburrito

**Comment by camelburrito** [comment]
@jpettitt - right that is one of the reasons we did not want to do it in the first place. However we can see if there is a way to make sure we can do this without content jumping (the bind protocol which is under development will have to solve this. so looking forward to how we can address this.)

**Comment by cramforce** [comment]
I only have strong views on content jumping that were not triggered by a user interaction.

**Comment by ankur0890** [comment]
Also it creates problem when two accordians gets open together . Suppose one accordian is already opened and second one is at the bottom. When user open the bottom one, second accordion should get focus to middle of the screen or first one should get close. Right now its laying at the bottom only giving a dead expression to user that it has been opened constituting a bad UX.

**Comment by camelburrito** [comment]
This should be possible with amp-selector now.

**Comment by ericlindley-g** [comment]
Added a feature request for AMP by Example to demo this functionality: https://github.com/ampproject/amp-by-example/issues/726

**Comment by ankur0890** [comment]
Not able to use amp-selector on amp-accordian sections as section should be immediate child of amp-accordian. Small snippet or demo would be helpful. @camelburrito  @ericlindley-g

**Comment by camelburrito** [comment]
@ankur0890 - you could try putting the accordion in amp-selector - infact you might just use amp-selector and not need amp-accordion at all. You will need to write css to make this work. We will try and add an example to amp-by-example.

**Comment by ankur0890** [comment]
@camelburrito Thanks for the explanation. Yeah it would be great if you can create some snippet. Will try it my own also. Thanks :)

**Comment by AndrewKGuan** [comment]
Although there could be workarounds, it is not as intuitive as using accordion to do what accordions normally do.  It is a bit strange to advise not to use amp-accordion to make accordions but use amp-selector instead.
+1 to the original request to have a flag for amp-accordion.

**Comment by aghassemi** [comment]
Implemented by #13364
