### ISSUE TITLE
Question: The end goal for AMP and the Why?

### ISSUE THREAD

**Issue by kzap** [ampproject/amphtml#675]
Is the goal for AMP just to be fast pages which mobile apps can load if they want to?

Or is it to be a new standard of HTML which loads blazingly fast?

I can see the speed benefit but if noone loads AMP version of pages whats the point?

I'm trying to see if this will be like a special framework for those who want to put in the extra work for it or something that browsers will adapt one day when they realize this is how to make webpages load faster?

**Comment by cramforce** [comment]
@kzap I answered you on Twitter already I believe. This is a very open ended question, but lets stare with this: Google, Twitter, Pinterest Linkedin are planning to send users to AMP versions when available. Traffic should be there.

**Comment by kzap** [comment]
Hi, thanks, not sure though where to pose topics and questions as Stackoverflow doesnt like open ended questions.

Let me know if theres a better venue for discussion. or if this discussion is a repeat :)

- So if its the responsibility of the referrer to send users to the AMP, then only those sites/app who put in the effort to find AMP pages can deliver traffic?

- The majority of referral traffic to some publishers may come from these big sites but then visitors not from these referrers wont get sent to the AMP experience? I can imagine sites with AMP support employing a IF MOBILE { redirect AMP_URL; } kind of thing

- Trying to see the big picture that you guys see :)

**Comment by cramforce** [comment]
s/guys/folks please :)
StackOverflow works great!
AMP pages are just web pages. Everyone can send traffic. It doesn't always
have to be a choice: Maybe there is only an AMP version? Maybe all you know
is the AMP version? Its all just URLs.

**Comment by kzap** [comment]
ok thanks, maybe Quora :)
