### ISSUE TITLE
Adding the possibility to use Speed Report in GA also for AMP.

### ISSUE THREAD

**Issue by andreapernici** [ampproject/amphtml#6751]
It would be great to let AMP pages populate the Speed Report in Google Analytics?

https://support.google.com/analytics/answer/1205784?hl=en#PageTimings

And to extend the sample to 100.

https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#siteSpeedSampleRate

**Comment by jridgewell** [comment]
Also @cramforce

**Comment by cramforce** [comment]
Yeah, I think that would be awesome!

**Comment by avimehta** [comment]
This should already happen. (If it is not, please reopen this bug and provide a sample page where this doesn't happen). To increase the sample size, add the following code to your configuration:

```
    'triggers': {
      'performanceTiming': {
        'on': 'visible',
        'request': 'timing',
        'sampleSpec': {
          'sampleOn': '${clientId}',
          'threshold': 100,
        },
      },
    },
```

(Note that threshold value can be 0-100 and will change your sampling rate...)
