### ISSUE TITLE
Invalid AMP validation for amp-lightbox

### ISSUE THREAD

**Issue by akshaylive** [ampproject/amphtml#6754]
Recently, a new "scrollable" tag was added to amp lightbox ( https://github.com/ampproject/amphtml/pull/6398 ).

This is the latest "everything AMP" example
https://raw.githubusercontent.com/muxin/amphtml/361ec9e264b5bb7e8045c4677ceaf71fc714cc45/examples/everything.amp.html

However the validator considers it to be an invalid AMP. https://validator.ampproject.org/#url=https%3A%2F%2Fraw.githubusercontent.com%2Fmuxin%2Famphtml%2F361ec9e264b5bb7e8045c4677ceaf71fc714cc45%2Fexamples%2Feverything.amp.html

Specifically,
```
The attribute 'scrollable' may not appear in tag 'amp-lightbox'.
```

The AMP lightbox CDN version has the new code changes made in the PR, but it appears that the validator is not updated.

**Comment by Gregable** [comment]
It typically takes a few weeks for validator changes to roll out, with the holidays it's a big longer. I'll try to update this issue when it's live.

**Comment by ebbeck** [comment]
Has a date been set for this to roll out? Seems like there was a release last Thursday but this is still causing our AMP pages to be invalid.

**Comment by Gregable** [comment]
I anticipate releasing late this week, but cannot guarantee that of course.

**Comment by honeybadgerdontcare** [comment]
This is now live in prod.

**Comment by johnfisherman** [comment]
Hey guys, just a quick heads up to remind you this attribute is not yet included in [the official documentation](https://www.ampproject.org/docs/reference/components/amp-lightbox), online.

I needed this and had to google my way to the PR.

**Comment by aghassemi** [comment]
@johnfisherman Thanks, will update the docs soon.
