### ISSUE TITLE
Implement integration test for image lightbox

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#6756]
The test should

- load a page with an image that has the image lightbox attached
- click the image
- observe that lightbox is opened
- measure dimensions of lightbox to see that it has expected dimensions
- check content of lightbox
- close lightbox
- check that page is restored correctly

**Comment by adelinamart** [comment]
@dvoytenko do we still need this? Thanks.

**Comment by aghassemi** [comment]
technically image-lightbox will be folded into the new lightbox viewer @muxin is working on soon, so I am okay with closing this.
