### ISSUE TITLE
Implement integration test for sidebar

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#6757]
The test should

- load a page with a sidebar component
- click the element that opens the sidebar
- observe that sidebar is opened
- measure sidebar to see that it has expected dimensions
- check content of sidebar
- play through various mechanisms that can close the side bar (and observe that it is closed)
- observe changes to history stack

**Comment by randallbpotter15** [comment]
On the measuring phase can it detect if there is anything else influencing it's top position or if anything is masking it on the page via z-indexing?  Thinking of recent bugs.  Not sure which test suite is being used for this though.

Love that you are implementing this!!

**Comment by aghassemi** [comment]
good candidate for E2E. @cvializ
