### ISSUE TITLE
I2I: Require ampCors in custom ad

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#6758]
For better security, we want to enforce [AMP CORS](https://github.com/ampproject/amphtml/blob/master/spec/amp-cors-requests.md#cors-security-in-amp) in the XHR made in custom ad.

We will want to
- Turn [this](https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad/0.1/amp-ad-custom.js#L88) to true
- Update documentation.

Accordingly, we expect the custom ad servers to handle AMP CORS correctly.

@xgretsch can I assign this to you?

**Comment by xgretsch** [comment]
Sure - just be aware that it will be next week before I get to it.

**Comment by lannka** [comment]
@xgretsch are you still on this? It can be blocker to fully launch the custom ad feature, since it requires pub side change.

**Comment by xgretsch** [comment]
Sorry, this one slipped through the net. I've made the changes server side on my ad server and everything's fine, but I'll do a PR next week to get this into place.
