### ISSUE TITLE
Enable integration test for 3p ads

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#6763]
integration test for ads is skipped now https://github.com/ampproject/amphtml/blob/master/test/integration/test-amp-ad-doubleclick.js#L52.

I think we now need two integration tests for A4A and 3P ad respectively. I plan to change our old test (make use of our fake `_ping_` type instead of doubleclick, since doubleclick ad will render as A4A) to cover the case of 3p. 

I believe we will also need integration test for A4A, which I don't have a clue currently 😢 . @lannka @tdrl @keithwrightbos

**Comment by tdrl** [comment]
I wrote some preliminary tests for A4A that are intended to be integration-like, in the sense that they test client code end-to-end, but stub out servers: https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/0.1/test/test-a4a-integration.js

But I'm not sure that this functions as an 'integration test' in the sense that the other AMP tests do.  (E.g., doesn't just load a controlled test data page in an iframe).  What do you need in terms of integration tests?

**Comment by adelinamart** [comment]
@zhouyx to reply here. Thanks.

**Comment by zhouyx** [comment]
I agree it is hard to not stub server in this case.
However thought the current test is integrated, it is not strictly an "integration test". (As you said: load a controlled test page, and then check the eventually behavior or DOM). 
FYI: only an integration test in our integration test folder will run on saucelabs

**Comment by zhouyx** [comment]
closed by #6789
