### ISSUE TITLE
When loaded with AMP :Website is not rendered correctly and unable to scroll

### ISSUE THREAD

**Issue by Arnold85** [ampproject/amphtml#6769]
When I follow the link (that points to googles AMP cache) from the searchresults I can see the website, but it is not rendered correctly and much more important I does not scroll

## How do we reproduce the issue?

Just follow the link on chrome for android
https://www.google.de/url?sa=t&source=web&rct=j&url=/amp/s/hpphysio.com/voraussetzungen-und-anerkennung/&ved=0ahUKEwiPov6Q9YTRAhUEN1AKHRK5Bzw4ChAWCCYwBQ&usg=AFQjCNGFQCVjh71uQLsVJ8RoO8s1XPj4IA&sig2=AUWwVpBe-X_-LkM0artRCg

and compare to 

https://hpphysio.com/voraussetzungen-und-anerkennung/

## What browsers are affected?
Chrome for android. 
Firefox on android is redirected to the original website which is also AMP cause I dont have a Non-AMP-Version.

## Which AMP version is affected?
1481838084444

Is this a new issue? Or was it always broken? Paste your AMP version. You can find it in the browser dev tools.

**Comment by honeybadgerdontcare** [comment]
The AMP Cache is having an issue with the self closing div tag:
`<div class="green" id="topline"/>`

Try changing that to a non self closing div tag and put a closing `</div>` just before `</nav>`. I'll take a look to see if this can be also addressed on the AMP Cache side.

**Comment by honeybadgerdontcare** [comment]
Yes, that is the issue. `div` is not a void element, so in HTML5 it can not be self-closing.

**Comment by Arnold85** [comment]
Okay, thank you very much. 

 

Von: honeybadgerdontcare [mailto:notifications@github.com] 
Gesendet: Mittwoch, 21. Dezember 2016 20:17
An: ampproject/amphtml <amphtml@noreply.github.com>
Cc: Arnold85 <arne.broedel@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [ampproject/amphtml] When loaded with AMP :Website is not rendered correctly and unable to scroll (#6769)

 

Yes, that is the issue. div is not a void element, so in HTML5 it can not be self-closing.
