### ISSUE TITLE
Adjust CID strategy in presence of viewer

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#6770]
Right now we intermingle both localStorage retrieval and viewer based retrieval.

The new algorithm should disentangle that:

- If not iframed or viewer not trusted use localStorage
- Otherwise go through existing viewer strategy, but never read and write from localStorage.

**Comment by lannka** [comment]
What's the plan for our new CDN domain format? If we eventually will move to CDN domain like `www-example-com.cdn.ampproject.org`, then we can probably fully get rid of the baseCid stuff and move to a pure cookie based solution?

**Comment by cramforce** [comment]
@lannka Unfortunately with a viewer URL that isn't per publisher we cannot. We'd no longer need it for the local localStorage, though.

**Comment by cramforce** [comment]
Lets discuss how to move forward here, also considering #8215

I'd like to move to this algorithm:

- Always use our own storage
- Unless the viewer supplied a CID.

Lets discuss further in person.

**Comment by rudygalfi** [comment]
@cramforce @lannka Will this still be needed going forward?

**Comment by cramforce** [comment]
NO
