### ISSUE TITLE
master is red

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#6773]
https://travis-ci.org/ampproject/amphtml/builds/185645230

![image](https://cloud.githubusercontent.com/assets/5419904/21402923/9803d68c-c76f-11e6-8733-85c9e6532f55.png)

**Comment by erwinmombay** [comment]
@Gregable @honeybadgerdontcare @powdercloud any of you know what the issue is? looking into it but thought to ping you guys if you know at the top of your head

**Comment by erwinmombay** [comment]
looks like it is https://github.com/ampproject/amphtml/commit/edaada49213aefdba7fda0f6597d5271fa4dfb45 when i bisected

**Comment by Gregable** [comment]
I should probably make that error message indicate which tag is the problem.

You can fix this by adding

`also_requires_tag_warning: "amp-video"`

To the `<script>` TagSpec for `amp-video-0.1.js`

**Comment by honeybadgerdontcare** [comment]
amp-video is missing the also_requires_tag.

**Comment by zhouyx** [comment]
Thanks @erwinmombay  @Gregable @honeybadgerdontcare, i will make a quick fix

**Comment by zhouyx** [comment]
#6775
