### ISSUE TITLE
Error message for missing layout on amp-img is not helpful.

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#6776]
![Imgur](http://i.imgur.com/BMT30HX.png)

This is what you get for an `amp-img` that doesn't have a `layout` attribute. This is likely worth special casing in that the error should convey that the user should likely pick a layout instead of saying that the default layout is unsupported.

**Comment by Gregable** [comment]
As an alternative, should we bake in different defaults by tag, so that in this case we pick a default that is usable?

**Comment by cramforce** [comment]
@Gregable We'd like to avoid such centralized maps that would need to go into our main binary.

May be good to add similar error message as in #6777 for the empty case in the validator, though.
