### ISSUE TITLE
JS validator broken with SW

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#6778]
URL is https://cdn.ampproject.org/v0/validator.js

Trigger on any AMP page with `#development=1`

**Comment by jridgewell** [comment]
Ugh, this is another "special" file like `experiments.js`. What about rejecting anything that does not start with `amp-` in the v0 directory?

- Good
  - v0.js
  - v0/amp-component.js
  - v1.js
  - v1/amp-component.js
- Bad
  - v0/experiments.js
  - v0/validator.js
  - v1/experiments.js
  - v1/validator.js

**Comment by cramforce** [comment]
I think we want to stop using the `amp-` prefix on components at some point.

**Comment by jridgewell** [comment]
I can add another exception for "validator.js" then.
