### ISSUE TITLE
Feature request: amp-accordion to allow user to override collapsed section css

### ISSUE THREAD

**Issue by stonezhong** [ampproject/amphtml#6783]
amp-accordion to allow user to specify css for collapsed section

## How do we reproduce the issue?
go to https://ampbyexample.com/components/amp-accordion/, click "Show less"

Here is what happened:
When you click show less, the entire section "Id lacus amet. Aliquam eos nunc ut scelerisque lacinia, eu rutrum id, vestibulum aliqua vivamus luctus eu rhoncus ut, sodales id. Velit lacus, fermentum neque et sagittis, ac venenatis volutpat, dolore neque feugiat proin fermentum odio, odio arcu in eu wisi." becomes hidden.

Here is what I expect:
I want when "Show less" is clicked, the section is still visible, but let me to control the height of the section so for example, I can set overflow to hidden, I can calculate the height based on the font size to allow number of lines to be displayed when section is "collapsed".

## What browsers are affected?
All browsers?

## Which AMP version is affected?
1.0

**Comment by camelburrito** [comment]
i don't believe accordion is meant for such a use case. However this can be a feature or a new component.
CC @ericlindley-g

**Comment by ericlindley-g** [comment]
Agreed — amp-accordion doesn't directly support this, but we could work on ways to do so (re-opening this issue for tracking that feature request).

**Comment by camelburrito** [comment]
Closing this here - please re-open a new feature request for auto ellipsisng text.
