### ISSUE TITLE
Amp breaks reason.com

### ISSUE THREAD

**Issue by killerkalamari** [ampproject/amphtml#6786]
## Short description of your issue:
Trying to read the news via Google News & Weather, now I can't scroll pages properly because of AMP. It won't allow me to scroll to the right if there are images larger than my phone screen. 

## How do we reproduce the issue?
Open this page in Google Chrome on Android, try to look at the entire graph by scrolling to the right, and you can't (the graph goes to 2016): https://cdn.ampproject.org/c/reason.com/blog/2016/12/21/death-penalty-sentences-in-america-conti/amp

When the real site http://reason.com/blog/2016/12/21/death-penalty-sentences-in-america-conti is viewed, the graphic is properly resized smaller so the page fits. I then can use my pinch zoom to view the image. 

## What browsers are affected?
Google Chrome on Android, also the stock browser, I'm running 6.0.1. Also, Firefox 50.1.0 if you resize the website to less than the width of the graphic. The horizontal scrollbar is lost. 

## Which AMP version is affected?
No clue, not my problem. It's a news site website that is now broken because of the AMP software. I was just trying to read the news as an end user. Trying to do you guys a favor by reporting this.

**Comment by cramforce** [comment]
AMP is not automatically generated, so the AMP team cannot do anything about content. Do you have a way to contact reason.com and let them know to fix their site?

**Comment by killerkalamari** [comment]
They shouldn't have to change their site. If incompatible or broken HTML etc is detected, then AMP should back off so it doesn't break sites.

**Comment by cramforce** [comment]
This is not AMP's role. AMP is a JavaScript framework. It can be used to make broken web pages. Do you have a way to contact reason.com and let them know to fix their site?

**Comment by killerkalamari** [comment]
This is not a valid response. I now consider AMP to be web hostile software that breaks the web and doesn't care.

**Comment by killerkalamari** [comment]
Note that reason is an innocent bystander, it's being wrapped in the AMP trojan horse software by Google News.

**Comment by killerkalamari** [comment]
Coward! Stop breaking the web you dipshits!

**Comment by jridgewell** [comment]
This isn't AMP's fault, and it isn't Google News' either. Reason has published a page that with an image larger than the viewport. Open http://reason.com/blog/2016/12/21/death-penalty-sentences-in-america-conti/amp. Notice that's _not_ a cdn.ampproject.org page. Google News is just linking to a broken page, published directly by Reason.

**Comment by cramforce** [comment]
@killerkalamari Please refrain from further code of conduct violations or we will block you https://github.com/ampproject/amphtml/blob/master/CODE_OF_CONDUCT.md
