### ISSUE TITLE
amp-img structure limits images loading if JS fails

### ISSUE THREAD

**Issue by remy** [ampproject/amphtml#6790]
## Short description of your issue:

Fallback image is "invalid" and causes AMP error.

## How do we reproduce the issue?

URL: https://validator.ampproject.org/#url=https%3A%2F%2Fremysharp.com%2F2016%2F12%2F22%2Fcool-uris-dont-change%2Famp

I have the following markup (though simplified for this issue):

```html
<amp-img src="x.png" height="10" width="10">
  <div fallback><img src="x.png" height="10" width="10"></div>
</amp-img>
```

This reports this error: 

```text
The tag 'img' may only appear as a descendant of tag 'noscript'.
```

However, when JavaScript doesn't load (*not* JS disabled, so `noscript` doesn't apply here), the images won't appear at all, because the AMP JavaScript generates the nested `img` tag inside of the `amp-img`.

So I put an `img` directly inside the `amp-img` so that it would load the image even if the JavaScript didn't load, but then when the JS did load, it showed the image twice. So I wrapped it in `<div fallback>` (which meant I also was forced to move my image *outside* of the `p` tag it was nested inside of…which was fine for this particular page, but would break when using inline images).

Using the fallback renders one image correctly when JS doesn't load, and one image when the JS does load, but causes the validation error.

So either the validation is wrong *and* images are not supposed to load, or, *I think* the validation needs updating.

## What browsers are affected?

Chrome / validator

## Which AMP version is affected?

Filing as I think it's an error in validation and should be reconsidered.

**Comment by cramforce** [comment]
We are pretty unlikely to support this, I think. One problem would be that the preload scanner would pick up and load the image which we don't want https://medium.com/@cramforce/why-amp-html-does-not-take-full-advantage-of-the-preload-scanner-7e7f788aa94e

We try really hard to not fail the JS load, of course. If it does, it falls into the 8 second timeout. In practice this is extraordinarily rarely hit. The only place of concern are overzealous ad blockers that block AMP's JS. With the super wide deployment of AMP this now becomes rarer.

I think a better way to tackle the question is: what are web component based pages expected to do without JS? I think AMP does a comparatively good job, but certainly not a perfect one.

**Comment by remy** [comment]
What about (and I thought this would work out of the box), if the AMP JS finds `amp-img > img` it just adds the appropriate classes to the nested image, instead of adding the second `img` to the top level `amp-img`? Wouldn't that solve the problem entirely?

**Comment by cramforce** [comment]
The thing is that in pre-render mode (before user clicked on link) we don't
want to download images that aren't visible in the first viewport to save
bandwidth, and with such markup the browser would still download them.

**Comment by remy** [comment]
Okay, I see.

**Comment by cramforce** [comment]
CC @pbakaus
Just making sure that bringing back `lazyload` attribute on image (introduced by Microsoft many years ago, but abandoned in standardization) is on our list of W3C/WHATWG initiatives.

**Comment by pbakaus** [comment]
@ igrigorik has been fighting for lazy load on a lenghty W3C thread, and (I believe) lost. Ilya, can you quickly summarize?

**Comment by cramforce** [comment]
We'd go full circle if the argument was "People should just use custom elements" :)

**Comment by igrigorik** [comment]
> Just making sure that bringing back lazyload attribute on image (introduced by Microsoft many years ago, but abandoned in standardization) is on our list of W3C/WHATWG initiatives.

That attribute is deprecated. IE's implementation -- despite its name -- didn't actually lazyload anything, it simply lowered the fetch priority a bit.

See https://discourse.wicg.io/t/a-standard-way-to-lazy-load-images/1153/12?u=igrigorik.

**Comment by jridgewell** [comment]
Could we use a `noscript[fallback]`?

```html
<amp-img src="x.png" height="10" width="10">
  <noscript fallback><img src="x.png" height="10" width="10"></noscript>
</amp-img>
```

**Comment by remy** [comment]
JavaScript is enabled in the case I've raised.

**Comment by jridgewell** [comment]
> JavaScript is enabled in the case I've raised.

Yup. Take a look at http://output.jsbin.com/coqigum?quiet=true with JS enabled and disabled. And it's [valid AMP](https://validator.ampproject.org/#url=http%3A%2F%2Foutput.jsbin.com%2Fcoqigum%3Fquiet%3Dtrue).

**Comment by remy** [comment]
Please go ahead and re-read the issue. This isn't a JS enabled/disabled thread. It's about when JS fails to load, and visibility of images.

**Comment by jpettitt** [comment]
So the case is where the document (loaded from the amp cdn) loads but the JS (loaded from the amp cdn) doesn't?  The only case I can see where that happens is when the user has a blocker that's dumb or loading is borked by a plugin.  Given that mobile plugins are very limited (safari) or non-existent (chrome) this seems to be an edge case of an edge case.

**Comment by remy** [comment]
It happened when my network stalled.

I wouldn't be so quick to dismiss the case where js fails to load. I don't
have it to hand, but UK gov has some good data on this. It's not as much of
an edge case as you might think.

**Comment by cramforce** [comment]
It can definitely happen. However, with our ServiceWorker installed (https://cdn.ampproject.org/experiments.html select the serviceworker experiment and dev channel) it becomes very, very unlikely.

I think that AMP is really the wrong place to address "what happens to a custom element when the JS fails to load". That needs to be addressed in the standards committee for custom elements.

Unfortunately, custom elements v1 killed the `is` attribute which was exactly for cases like this.

**Comment by adelinamart** [comment]
Closing this since no new activity. @remy feel free to re-open if you have new feedback. Thank you!
