### ISSUE TITLE
amp-link component for amp to amp linking regressing to html

### ISSUE THREAD

**Issue by drdamour** [ampproject/amphtml#6798]
I was looking for an amp-link component that i could add to my <a> tags and it's function would be to look at the href and if it has an amp representation it would be rewritten to be a link to the amp rep from the amp cache.

Thus i could keep my users in amp for a while.

i couldn't find such a thing..has it been discussed?

It could just fallback to the existing href.

**Comment by jpettitt** [comment]
+1 for that, perhaps handled at the CDN level?  We're doing it server side when we render pages using the ampapi.

**Comment by jridgewell** [comment]
Actually, to @ericlindley-g since you've answered things this week.

**Comment by ericlindley-g** [comment]
We've been thinking about this kind of feature, so folks can stay on AMP pages if that's the best experience. Another option (aside from at runtime or in the cache) is to do this at the AMP Viewer level. This way, the viewer could potentially perform other optimizations (an example is pre-rendering, though there are so many low-click-probability anchor links, I'm not sure this would be the right thing to do), and avoid naively linking to a third-party cache. 

(Thanks for triaging, @jridgewell  — I think @rudygalfi is the most up-to-date on current discussions, so I'm passing back to him : )

**Comment by rudygalfi** [comment]
This is a duplicate of #2663.

**Comment by drdamour** [comment]
thanks i figured it was already asked for but didn't come across it.
