### ISSUE TITLE
About isDevChannel

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#6802]
```javascript
/**
 * Whether the scripts come from a dev channel.
 * @param {!Window} win
 * @return {boolean}
 */
export function isDevChannel(win) {
  if (isExperimentOn(win, CANARY_EXPERIMENT_ID)) {
    return true;
  }
  if (isDevChannelVersionDoNotUse_(win)) {
    return true;
  }
  return false;
}

/**
 * Whether the version corresponds to the dev-channel binary.
 * @param {!Window} win
 * @return {boolean}
 * @private Visible for testing only!
 */
export function isDevChannelVersionDoNotUse_(win) {
  return !!(win.AMP_CONFIG && win.AMP_CONFIG.canary);
}
```

The above code can be found [here](https://github.com/ampproject/amphtml/blob/master/src/experiments.js#L48).

It seems to me that the 2 functions will always give the same result. Because whoever turned on devChannel will get `v0.js` with `AMP_CONFIG.canary = true`.

Isn't it? @erwinmombay

**Comment by erwinmombay** [comment]
that makes sense. the question i still have though is should we make the assumption that AMP_CONFIG exists. (it does for google's amp cache, but what about other caches?)

**Comment by lannka** [comment]
how would other cache service do canary? I guess they have to provide AMP_CONFIG in binary as well?

**Comment by erwinmombay** [comment]
we don't really have that defined on how they would do canary or if they even need to. they could just rely on us to do canary and always just take our production version

cc @cramforce @dknecht

**Comment by lannka** [comment]
Nevertheless, I see `isDevChannel` is only used in tests, we can safely remove it.

**Comment by cramforce** [comment]
I think this was just a migration that wasn't cleaned up. The function should also be renamed to `isCanary` because this includes non-opt-in users. Can we just delete it, though?

**Comment by lannka** [comment]
@cramforce indeed. this is my PR #6803 PTAL

**Comment by erwinmombay** [comment]
the isDevChannel removal is good with me 👍 , still hesistant on bypassing the cookie read

**Comment by lannka** [comment]
that's why function name changed to `isCanary()`, which is exactly determined by AMP_CONFIG, not cookie.

**Comment by erwinmombay** [comment]
right, but AMP_CONFIG is not guaranteed to exist currently on non amp cache and it'll always just fallback to prod which is a sane default anyways

**Comment by lannka** [comment]
in that case, `isCanary()` should just return `false` no matter if the cookie is turned on or off, right?

**Comment by erwinmombay** [comment]
@lannka yeah i think that ok for now
