### ISSUE TITLE
Give support amp-ad to Smartadtags SaaS for AdNetworks

### ISSUE THREAD

**Issue by smartadtags** [ampproject/amphtml#6810]
I want to contribute to add support to Smartadtags network platform https://www.smartadtags.com/

We are one of the biggest ad networks and we want to support our ad tags in AMP language

Thank you

**Comment by jridgewell** [comment]
Please!

/to @zhouyx

**Comment by zhouyx** [comment]
@smartadtags It's great to know that you will be supporting AMP.  We have an instruction on how to integrate an ad network into AMP. https://github.com/ampproject/amphtml/blob/master/ads/README.md
Please let me know if you have any questions.

**Comment by zhouyx** [comment]
@smartadtags any update on the issue? Close for now, feel free to reopen it.
