### ISSUE TITLE
Allow playsinline attribute on video tag

### ISSUE THREAD

**Issue by koshka** [ampproject/amphtml#6811]
## Short description of your issue:
For users that have Javascript disabled, we have a `<noscript>` fallback to our video element that must play inline from a UX perspective.
However, the validator states:
The attribute 'playsinline' may not appear in tag 'video'.

## How do we reproduce the issue?

In Chrome dev tools, click Toggle Device Toolbar to mobile 
Go to:
https://gfycat.com/BareSecondaryFlamingo#development=1

**Comment by honeybadgerdontcare** [comment]
@jridgewell Is this applicable to `amp-video` as well or only `video`?

**Comment by jridgewell** [comment]
We automatically add `playsinline` to `<amp-video>`, so I don't think we need to add that.

**Comment by koshka** [comment]
hey @jridgewell `<amp-video>` works well for us with `playsinline` default
The issue we have happens when JS is disabled; in that case, we have to fallback in a `<noscript>` section to the `<video>` tag. So we need the validator to not complain in the <video> tag about `playsinline`

**Comment by Gregable** [comment]
Sounds good. It appears that this attribute is fairly new, which explains why it's missing. Happy to add it.

**Comment by honeybadgerdontcare** [comment]
This is now live in prod.
