### ISSUE TITLE
amp-access demo shows error

### ISSUE THREAD

**Issue by Chan4077** [ampproject/amphtml#6815]
## Short description of your issue:

The [comment section demo](https://ampbyexample.com/samples_templates/comment_section/preview/) shows this warning:

```
Uncaught Error: Authorization failed: : Response must contain the AMP-Access-Control-Allow-Source-Origin header​​
```

## How do we reproduce the issue?

https://ampbyexample.com/samples_templates/comment_section/preview/

## What browsers are affected?

Most probably all browsers.

## Which AMP version is affected?

Version on the site.

**Comment by adelinamart** [comment]
@pbakaus any updates here? Thank you!

**Comment by bpaduch** [comment]
@sebastianbenz - Can you confirm this is fixed?

**Comment by sebastianbenz** [comment]
@bpaduch yes - it's fixed.

**Comment by adelinamart** [comment]
Great. Marking this as closed. Thanks.
