### ISSUE TITLE
disallowed_domain

### ISSUE THREAD

**Issue by dknecht** [ampproject/amphtml#6827]
Should disallowed_domain be updated to check for *.cdn.ampproject.org?  

https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii#L2183

Also is it possible to put multiple disallowed_domains?

@Gregable

**Comment by Gregable** [comment]
Good catch. It should be updated. The field is repeated right now, but I don't think it supports domain suffixes. Will need to make some changes.

**Comment by dknecht** [comment]
Can you add in *.amp.cloudflare.com when you make change?

**Comment by Gregable** [comment]
Sure.

**Comment by rudygalfi** [comment]
@Gregable Can you update milestone to Current when you start working on this?

**Comment by honeybadgerdontcare** [comment]
This is now live in prod.
