### ISSUE TITLE
[amp-analytics] Deprecate visiblity v1 code

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#6828]
This is a follow up work of #5697

We'll need 
1. have a working IntersectionObserver polyfill to fill the gap when native one is not available
1. remove visibility v1 code.

**Comment by rudygalfi** [comment]
@lannka Any estimate on when this can be done? Or any notable dependencies?

**Comment by lannka** [comment]
@rudygalfi Right now it's blocked by the visibility-v2 launch. 
Bumped it up to P2, as we wanted to get this done ASAP so we don't need to maintain the v1 code. It's slowing done any new changes made to visibility tracking.
