### ISSUE TITLE
Add to cart (tracking FR)

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#6843]
Tracking FR for a fully-featured "add to cart" functionality

Related:
https://github.com/ampproject/amphtml/pull/5214
https://github.com/ampproject/amphtml/issues/5207
https://github.com/ampproject/amphtml/issues/5213
https://github.com/ampproject/amphtml/issues/5206

/to @mkhatib 
/cc @rudygalfi

**Comment by mkhatib** [comment]
Closing this. We already have a good parts of this implemented and there are possible implementations with the current setup.
