### ISSUE TITLE
Cant use amp-ad googleclick

### ISSUE THREAD

**Issue by splendidecreature** [ampproject/amphtml#6848]
Hi, I can't use ad doubleclick on this page:

http://www.infomotori.com/motorsport/le-quattro-peugeot-3008dkr-pronte-per-la-partenza-della-dakar-2017_124020/?amp=true#development=1

I get the error
Redirect at origin 'https://stats.g.doubleclick.net' has been blocked from loading by Cross-Origin Resource Sharing policy: A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://www.infomotori.com' is therefore not allowed access.

can you help me? I tried to change Cross-Origin to https://stats.g.doubleclick.net but it still does not work

thank you

**Comment by keithwrightbos** [comment]
I am unable to get the ad to fill using the above page.  Is there something special I need to do (e.g. particular browser, cookie, etc)?

**Comment by splendidecreature** [comment]
ehmm... that's my problem, I am unable to get the ad to fill . that's the ad:

<amp-ad width=300 height=250 layout="responsive"  
    type="doubleclick"
    data-slot="/2081496/INFOMOTORI_ROS_Box_300x250">
</amp-ad>

**Comment by splendidecreature** [comment]
<  amp-ad width=300 height=250 layout="responsive"  
    type="doubleclick"
    data-slot="/2081496/INFOMOTORI_ROS_Box_300x250">
<   /amp-ad>

**Comment by keithwrightbos** [comment]
I see no errors when attempting to reproduce (no request to stats.g.doubleclick.net).
@jasti could assist in determining why the reservation slot in question is not filling?

**Comment by jasti** [comment]
@splendidecreature  In DFP, I see two line items eligible to serve but both don't start delivery until Jan 9th. To be absolutely sure, you should create a comparable non-AMP pages and request the ad using GPT.
