### ISSUE TITLE
amp-social-share whatsapp does not show up the icon

### ISSUE THREAD

**Issue by shireeshaps** [ampproject/amphtml#6850]
Hi,

Amp social share which has whatsapp element does not render the icon.

Pasting the tag for your reference

```html
<amp-social-share type="whatsapp"
                layout="container"
                data-share-endpoint="whatsapp://send"
                data-param-text="Check out this article: TITLE - CANONICAL_URL">
    Share on Whatsapp
</amp-social-share>
```

-Regards,
Shireesha

**Comment by mkhatib** [comment]
`Whatsapp` didn't have default config so one would have to provide their own styling. I just sent a PR to add the default config.

**Comment by shireeshaps** [comment]
Whatsapp icon still not rendering like other social icons (twitter and facebook)

**Comment by jridgewell** [comment]
This hasn't been released to Production yet, only canary. The next production release will be on Thurs, so it should be live then.
