### ISSUE TITLE
amp-video need bitgravity

### ISSUE THREAD

**Issue by shireeshaps** [ampproject/amphtml#6851]
Hi,

Would like to know if any possibility to add Bitgravity player as a vendor http://player.bitgravity.com/10/simple/source.php

**Comment by aghassemi** [comment]
bitgravity does not look very mobile friendly. @shireeshaps Do you know if they actually have a HTML5 player that does not use Flash?

**Comment by shireeshaps** [comment]
They are using Adobe Flash. I am unable to find out if they have html5 player.

**Comment by aghassemi** [comment]
@shireeshaps We will not support flash video players because they don't work on mobile. Before we can consider supporting bitgravity, they need to implement a mobile-friendly video player. Closing the issue for now, feel free to reopen when bitgravity ditches Flash for HTML5.

**Comment by shireeshaps** [comment]
No issues
