### ISSUE TITLE
Need to fully specify origins on CORS documentation

### ISSUE THREAD

**Issue by xgretsch** [ampproject/amphtml#6854]
## How do we reproduce the issue?

Look at https://github.com/ampproject/amphtml/blob/master/spec/amp-cors-requests.md#cors-security-in-amp

Note the following text:

> CORS endpoints receive requesting origin via "Origin" HTTP header. This header has to be restricted to only allow the following origins:
> 
> *.ampproject.org
> *.amp.cloudflare.com
> The Publisher’s own origins

Now look at the spec for the "Origin" header (e.g. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin)

Note that it does not allow wild cards, other than as a single "*".

## Therefore:

To implement these CORS recommendations server side, one needs to know exactly which origins should be specified, listed individually. I only know of one example ([https://cdn.ampproject.org]), but there are presumably others (at least one on [cloudflare.com]).

They should all be listed individually in this document so that they can be placed in the HTTP headers.

## Which AMP version is affected?

This applies as of commit [https://github.com/ampproject/amphtml/commit/e92b6b6dff8b853fd5f48629b120a8cf9505f08b#diff-17c7a8b6a5fad241c4943d99aa106f19]

**Comment by jridgewell** [comment]
Those values aren't the literal values needed in the `Allow-Access-Origin` Header. Further, the subdomains of `cdn.ampproject.org` (eg mobile-nytimes-com.cdn.ampproject.org) are computed based on the Source URL's domain, so it'd be impossible to list all of them.

/cc @cramforce

**Comment by xgretsch** [comment]
If you can't list them all, would it be possible for the documentation to explain how to figure them out? Because the only way I made anything work was by trial and error, which left me worried that I'd missed one of the possibilities needed for me.

**Comment by cramforce** [comment]
@dvoytenko Do you want to take a shot. The trick is that one needs to echo back the origin, which isn't obvious. We should also directly document the new origin scheme, though.

**Comment by rudygalfi** [comment]
@dvoytenko Can you assign the milestone depending on when you'll work on this?

**Comment by mkhatib** [comment]
So one way people do this is by sitting the headers based on the request coming in itself. So when a page from `mobile-nytimes-com.cdn.ampproject.org` makes a request to your endpoint, your backend can say hey, does this match a regex that that we think we can allow - in this case yes, so the header is not set to the exact same Origin that sets it.

Here's some pseudo code for demonstrating how this might be implemented. **Please note the following code is not accurate and is just for demo and discussion purpose**

```python
# This is usually implemented as a middleware for all requests you're targeting
@endpoint('/submit')
def my_endpoint(req, resp):
  origin = req.headers.get('Origin')
  if is_trusted_origin(origin) && check_other_cors_rules(req):
    resp.headers.set('Access-Control-Allow-Origin', origin)


def is_trusted_origin(origin):
  # THIS IS JUST DUMMY CODE FOR DEMO PURPOSES ONLY
  return regex.match(origin, /^([\w-]\.cdn\.ampproject\.org|[\w-]\.amp\.cloudflare\.com)$/
```

I am not 100% sure this is the best way to do this, so I'll leave it for @dvoytenko to add some more to this. 

What AMP docs can do is probably provide regexes or a pseudo-process of how to check.

**Comment by dvoytenko** [comment]
I should get to this in a next week.

**Comment by xgretsch** [comment]
Latest on this one: I discovered today that my ads had stopped working (from domain https://bachtrack.com) because the Amp cache origin to https://bachtrack-com.cdn.ampproject.org when the ad is found directly from a Google search (it was fine when linked to from a URL beginning in cdn.ampproject.org. This is new behaviour - I have no idea how long ago it was changed.

It reinforces the need for someone to (a) document this behaviour properly, and (b) make sure that developers are told in good time if the AMP cache is changed in some way that will be incompatible with what's documented.

**Comment by cramforce** [comment]
@xgretsch I'm sorry you missed this. It was widely announced (e.g. here https://amphtml.wordpress.com/2016/12/05/amp-cache-updates/) and we did very significant acceptance testing by rendering AMP pages and looking for CORS errors.

**Comment by xgretsch** [comment]
@cramforce Thanks for the concern. The reality is that for me, AMP is a "fit-and-forget": there's only one of me and I have literally hundreds of other features that I'm dealing with - therefore I'm not continually monitoring blogs etc. If there was somewhere I could sign up for alerts on AMP backwards compatibility changes, that might help, otherwise, I'm inevitably going to be vulnerable to this kind of issue.

I still think this documentation page needs work - just as an example, it refers in several places to `Amp-Same-Origin`, but if you put that in your code, it will fail because the header actually sent is `amp-same-origin` in lower case. And surely the page should have been updated at the point the change in cache domain was made. I'd happily do a PR, except that I'm not confident that I wouldn't make mistakes.

**Comment by cramforce** [comment]
There is https://groups.google.com/forum/#!forum/amphtml-announce which we should use more.

I agree that the docs needs work.

CCing @bpaduch. We can keep this with @dvoytenko, but should give it some dedicated text writer time, as I've heard the feedback multiple times that this is a pain point for people.

**Comment by bpaduch** [comment]
Fixed in https://github.com/ampproject/amphtml/pull/9636.
