### ISSUE TITLE
Facebook social-share parameter `text` not valid

### ISSUE THREAD

**Issue by jalajc** [ampproject/amphtml#6856]
Facebook parameter `text` is not valid as per Facebook's official spec and has no intended impact if included in share config as mentioned in [AMP documentation](https://github.com/ampproject/amphtml/blob/master/extensions/amp-social-share/amp-social-share.md#pre-configured-providers)  

#### reproducing the issue?
1. Create a amp-social-share component with type = facebook (appended used component definition)
2. Assign value to `data-param-text`
3. Share on Facebook through amp-social-share for Facebook component
4. Notice no text appears.

#### AMP version?
1481838084444, however its a parameter from Third party social integration provider, so don't think its dependent on AMP version.

#### Fix?
I couldn't find a perfect `text` equivalent but `quote` (data-param-quote)[1] can be used as workaround (`quote` has a different fb-ui representation)

Additionally, hashtag (data-param-hashtag)[2] can also be used 

- [1] `tested:working`
- [2] `tested:working`

##### Used component definition
``<amp-social-share type="facebook" data-param-app_id="421431258017553" data-param-text="हां फिर कभी" data-param-href="https://suraurgeet.com/" data-param-attribution="Qamp" ></amp-social-share>``

**Comment by mkhatib** [comment]
I am dropping the documentation of the `text` parameter from the docs. @ericlindley-g do we wanna add a default config for the `quote` attribute?

**Comment by rudygalfi** [comment]
Did #6908 close this?

**Comment by mkhatib** [comment]
I removed the documentation of invalid `text` attribute, kept this open in case we want to document `quote` attribute or have a default value for it in the config - publishers can still use it without default config. I am ok with closing this

**Comment by ericlindley-g** [comment]
Thanks — I think documenting that folks can use would be good, but not high-priority. Doesn't seem like a good fit for a default value in the config.

**Comment by ericlindley-g** [comment]
Passing to @bpaduch as a small docs task (not high-priority)
