### ISSUE TITLE
[enhancement] amp-fx-flying-carpet communicate scroll values to amp-iframes and amp-ads

### ISSUE THREAD

**Issue by Miroku87** [ampproject/amphtml#6857]
Hello guys,
I have tried the `amp-fx-flying-carpet` and I find it very useful for ads.
It would be also useful if it could send informations through `postMessage` to `amp-ad` or `amp-iframe` child elements about the y-scroll value of the viewport.
In this way it would be possible to make animations such as parallax or more complex stuff inside the iframes or ads.
What do you think?

**Comment by jridgewell** [comment]
That information can be obtained through [send-intersections](https://github.com/ampproject/amphtml/blob/efc1f15b078850e9d45162008670ad3b1cfa3fef/extensions/amp-iframe/amp-iframe.md#iframe-viewability), right? The intersection you receive is effectively the y-scroll.

**Comment by Miroku87** [comment]
Thank you @jridgewell I will look into that!

**Comment by Miroku87** [comment]
@jridgewell I've tested `send-interactions` on both `amp-iframe` and `amp-ad` and it works just on `amp-iframe` for now.
Is there an equivalent for `amp-ad`?

Thank you!

**Comment by jridgewell** [comment]
https://github.com/ampproject/amphtml/tree/master/ads#position-in-viewport

**Comment by Miroku87** [comment]
Thank you. I will try it as soon as I can.

**Comment by rudygalfi** [comment]
Just reading through this quickly, it seems like there's a resolution and it needs to be checked. Can this be closed out?

**Comment by Miroku87** [comment]
I've checked what @jridgewell pointed me and it works ok for my needs.
It can be closed, thank you!

**Comment by Miroku87** [comment]
I've checked what @jridgewell pointed me and it works ok for my needs.
It can be closed, thank you!
