### ISSUE TITLE
I2I: introduce experiment toggle in document meta data

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#6869]
Currently, [AMP experiments](https://github.com/ampproject/amphtml/blob/master/tools/experiments/README.md) are controlled by [binary config](https://github.com/ampproject/amphtml/blob/master/build-system/global-configs/prod-config.json) and [cookie based user opt-in](https://cdn.ampproject.org/experiments.html). 

Here I propose an extra page level control using HTML meta data:
```html
<meta name="amp-experiments-opt-in" content="experiment-a,experiment-b">
```

The priority of the 3 control are:
*cookie (user opt-in/out) > meta (page level) > binary config (global)*

This new mechanism has 2 major usages:
- For publishers to opt-in new features. For example, with this new mechanism, we don't need to globally launch feature like [custom-ad](https://github.com/ampproject/amphtml/issues/5541) to allow more testing. Individual publishers can opt-in on their own will.
- For amp-inabox to control experiment at serving time. Ad server can dynamically turn on/off experiment per ad request for AMP creatives served on non-AMP page. (A little bit tricky for AMP creatives served on AMP pages, as they share the same experiment flags with runtime. To not complicate things, we can ignore this meta settings, just like how we remove all the header scripts and CSS boilerplate.)

@cramforce @michaelkleber @keithwrightbos thoughts?

**Comment by jridgewell** [comment]
I want to propose an alternative precedence:

cookie (user opt-in/out) > binary config (global) > meta (page level)

Importantly, this allows us to disable anything (ie, with a bug) for everyone, probably fixing the publisher's page without them ever realizing.

**Comment by lannka** [comment]
@jridgewell but the entire purpose of this is for publisher to be able to override our binary config, isn't it? If anything went wrong, they have to turn off by themselves. I would expect serious publishers will have a feature flag their side to control this.

**Comment by jridgewell** [comment]
They still can, as long as we don't override them. Publishers will be slow, and allowing them to override us (after we've disabled something because of a bug) is going to hurt them.

**Comment by lannka** [comment]
It might hurt the other way. 

Imagine we introduced a new extension protected with a flag. 
Then a bunch of pubs started to opt-in. 
Then we introduced a bug to the feature, which breaks some pubs (not all).
Then we turn off the feature completely.
All of sudden, all pubs using this feature break.

For a minimum damage, I'd rather pubs detect problems themselves and opt-out themselves individually. I also feel natural in that way, I chose opt-in, so I opt-out.

**Comment by cramforce** [comment]
This cannot be allowed for all experiments. One purpose of experiments is that they allow shipping code that hasn't been security reviewed yet. So experiments must opt into this (similar to the ones that opt into being triggerable by URL param).

I really don't see the publisher opt-in part. Why not launch it fully then? If doing opt-in, something like Chrome's origin-trial tokens makes more sense (because they expire).

I do understand the amp-in-a-box use case. I'd do that with a non-validating tag. That way only AMP caches can force on experiments for some users.

**Comment by lannka** [comment]
Another usage I didn't mention is for our own testing in production. For example, before fully launching our analytics visibility-v2 feature, we'd like to test in our site `ampproject.org` first to catch any regression (we have to test with real traffic and real data): https://github.com/ampproject/docs/issues/282

Maybe Chrome's origin-trial is an option for it?

**Comment by lannka** [comment]
@cramforce to work around your concern, how about restrict the set of experiments to the ones listed in prod-config.json (AMP_CONFIG)?

So for my above use case, we can add `"visibility-v2": 0` into `prod-config.json`, and allow pub to opt-in and override.

**Comment by cramforce** [comment]
Why not let experiments opt into such an override? We can use `AMP_CONFIG` to define the set of experiments for which such override is OK.

**Comment by lannka** [comment]
Sure. Will introduce a new field in `(prod|canary)-config.json`:

```
{
  "allow-page-opt-in": "visibility-v2,some-other-feature",

  "canary": 0,
  "amp-ios-overflow-x": 1,
  ...
}
```

Sounds good?

**Comment by cramforce** [comment]
SG
