### ISSUE TITLE
Is there any specific reason to disallow HTML <progress> Tag?

### ISSUE THREAD

**Issue by faelgabriel** [ampproject/amphtml#6870]
Is there any specific reason to disallow HTML `<progress>` Tag?
It's a HTML5 element, is there an issue to allow this tag?

**Comment by Gregable** [comment]
I don't see any reason why not. I'm unsure why it was missed. I'll add it.

**Comment by Gregable** [comment]
OK, now I see why it was originally left out. It's part of section 4.10 (forms) of the HTML5 spec. Forms weren't originally supported in AMP and so form related elements were also left out.

There is no reason not to add them in at this point. I'll also add `<meter>` and `<output>` while at it.

**Comment by jridgewell** [comment]
@Gregable: Remember to ban `<output>`s with [special name properties](https://github.com/ampproject/amphtml/issues/6579).

**Comment by Gregable** [comment]
Yep, @honeybadgerdontcare reminded me of this one as I was implementing. Change is simple, but it'll be a while before released.

**Comment by honeybadgerdontcare** [comment]
This is now live in prod.
