### ISSUE TITLE
Validator does not catch path traversal in whitelisted urls

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#6874]
This passes the validator, it does not load what the validator thinks it loads.

```<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/../bootstrap/3.3.7/css/bootstrap.min.css">```

**Comment by Gregable** [comment]
It would be nice if their server didn't implement this kind of traversal. Oh well, I can make the regex more strict.

**Comment by rudygalfi** [comment]
ping? @Gregable can you update the milestone depending on when you'll work on this?

**Comment by honeybadgerdontcare** [comment]
This is now live in prod.
