### ISSUE TITLE
Error: Use autoplay attribute instead of data-param-autoplay​​​

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#6877]
```
Error: Use autoplay attribute instead of data-param-autoplay​​​
    at Error (native)
    at ra (https://cdn.ampproject.org/rtv/011481838084444/v0.js:8:262)
    at ma.f.error (https://cdn.ampproject.org/rtv/011481838084444/v0.js:5:202)
    at A (https://cdn.ampproject.org/rtv/011481838084444/v0/amp-youtube-0.1.js:3:171)
    at z.push.f.f.preconnectCallback (https://cdn.ampproject.org/rtv/011481838084444/v0/amp-youtube-0.1.js:1:1744)
    at https://cdn.ampproject.org/rtv/011481838084444/v0.js:142:70
```
Sample page: https://cdn.ampproject.org/v/amp.androidcentral.com/how-galaxy-s7-and-s7-edge-perform-gear-vr?amp_js_v=6
This is a `user().error` in `preconnectCallback` but got reported to error logs. Couldn't figure out why. Mind having a look @cramforce ?

**Comment by jridgewell** [comment]
It's being logged, because it's [thrown](https://github.com/ampproject/amphtml/blob/master/src/custom-element.js#L672), then [caught](https://github.com/ampproject/amphtml/blob/master/src/custom-element.js#L676) and [reported](https://github.com/ampproject/amphtml/blob/master/src/custom-element.js#L677)

**Comment by muxin** [comment]
OK I see, but we don't really need to log this, right?

**Comment by jridgewell** [comment]
Nope.

**Comment by cramforce** [comment]
@muxin Does this show up as a non-user-error? If yes, then I don't yet understand why.

I don't think @jridgewell's observation is fully correct. The error should not be thrown at all. This is a log with an async throw.

**Comment by muxin** [comment]
I saw this error in the error report log `assert-cdn-1p`. Does `assert-cdn-1p` mean user error?

**Comment by jridgewell** [comment]
Oh, you're correct, it's async thrown.

**Comment by cramforce** [comment]
@muxin Right. Maybe we can make this clearer in that tool. I typically start from the error graphs that have a label.

Basically `assert` should have been named `user-error`. Could we put that into the onduty docs?

**Comment by muxin** [comment]
OK, I just sent out a CL for the onduty docs. @erwinmombay
