### ISSUE TITLE
amp-img tag to support retina display

### ISSUE THREAD

**Issue by stonezhong** [ampproject/amphtml#6879]
## amp-img tag with layout set responsive does not support retina display very well

If you look at the sample code at https://ampbyexample.com/components/amp-img/
```
 <amp-img src="/img/amp.jpg"
      srcset="/img/amp.jpg 1080w, /img/amp-900.jpg 900w, /img/amp-800.jpg 800w,
  /img/amp-700.jpg 700w, /img/amp-600.jpg 600w, /img/amp-500.jpg 500w, /img/amp-400.jpg 400w,
  /img/amp-300.jpg 300w, /img/amp-200.jpg 200w, /img/amp-100.jpg 100w"
      width="1080"
      height="610"
      layout="responsive"
      alt="an image"></amp-img>
```
you can choose different size of the picture for different container size. However, the logic to choose the picture is based on the container width, e.g., `600w` represent 600px, however, on retina display, 600px is roughly 1200 pixels (more than 600 pixels). 1px is 1/96 inch, not a physical pixel.

## How do we reproduce the issue?
step 1: assuming you have a retina display, goto https://ampbyexample.com/components/amp-img/
step 2: look at the example for 
```
 <amp-img src="/img/amp.jpg"
      srcset="/img/amp.jpg 1080w, /img/amp-900.jpg 900w, /img/amp-800.jpg 800w,
  /img/amp-700.jpg 700w, /img/amp-600.jpg 600w, /img/amp-500.jpg 500w, /img/amp-400.jpg 400w,
  /img/amp-300.jpg 300w, /img/amp-200.jpg 200w, /img/amp-100.jpg 100w"
      width="1080"
      height="610"
      layout="responsive"
      alt="an image"></amp-img>
```
step 3: if the image container width is 600px, it is choosing /img/amp-600.jpg, and the actual image width contains more than 600 pixels in width, which means not the best picture has been selected.

## What browsers are affected?

All browsers? Yes
What device type? Retina display

## Which AMP version is affected?
1.0

Is this a new issue? Yes

**Comment by stonezhong** [comment]
It seems `600w` means `600 pixels` not `600 px`. Pls close this issue if that is true and sorry for the false alarm.

**Comment by camelburrito** [comment]
@stonezhong , in this case you should be using the sizes attribute and set it to the appropriate value . Feel free to re-open if you have more questions.
