### ISSUE TITLE
amp-carousel: prev/next arrows are not displayed on IE11

### ISSUE THREAD

**Issue by eike-hass** [ampproject/amphtml#6886]
It seems the navigation arrows in a `amp-carousel` are not displayed on IE 11.

## How do we reproduce the issue?

1. open https://ampbyexample.com/components/amp-carousel/ with IE11
2. notice no white arrows on the navigation triggers

## What browsers are affected?

Edge, IE 11, maybe below

## Which AMP version is affected?

1482359659944, most likely not a new issue

**Comment by camelburrito** [comment]
Dup of #6591
