### ISSUE TITLE
Please add bottom-navigation Tag

### ISSUE THREAD

**Issue by jet10000** [ampproject/amphtml#6887]
Please add bottom-navigation Tag

https://material.io/guidelines/components/bottom-navigation.html

**Comment by ericlindley-g** [comment]
Thanks for getting in touch, @jet10000 — agreed that this is a nice mobile pattern to support.

@camelburrito: I think this basic pattern is already supported in AMP (correct me if there are missing pieces — I know scrolling of fixed elements on iOS has been an issue in the past). If that's the case, @jet10000, you can already build this UI.

However, we could make it easier to build out-of-the-box. This might make sense as a copy/paste HTML+CSS template in AMP Start. WDYT @camelburrito?  (someone could even build out a Material theme down the line that includes this)

/cc @abeck000 as FYI

**Comment by camelburrito** [comment]
@jet10000 you should be totally able to do it on your page with `position: fixed`. As component does not make any sense if there are only links that we can navigate to. I think this would make total sense if they are implemented as Tabs (@ericlindley-g  we should remember this use case when we build amp-tabs)

@ericlindley-g yes we could build a theme that showcases this on AMP start

**Comment by ericlindley-g** [comment]
@camelburrito Good point on remembering this when building amp-tabs ( /cc @chenshay for visibility)

**Comment by rudygalfi** [comment]
@ericlindley-g Can you shift this over to being an Amp By Example or AMP Start issue, and then close this?

**Comment by camelburrito** [comment]
@rudygalfi - may be amp start, probably not worth it in ABE.

**Comment by ericlindley-g** [comment]
Moved to the [AMP Start repo](https://github.com/ampproject/ampstart/issues/25) to track
