### ISSUE TITLE
Support for Shadow DOM v1 in AMP Shadow

### ISSUE THREAD

**Issue by oliverfernandez** [ampproject/amphtml#6893]
Currently, AMP Shadow uses Shadow DOM v0 API.

Since Safari in iOS 10 supports Shadow DOM v1, I've made the test to add both implementations (v0 and v1) in shadow-embed.js 

attachShadowDoc works fine, but the problem is that no extensions are being loaded inside the ampdoc.

I think that the problem  is that in Safari, Custom Elements is polyfilled using a MutableObserver, and this Mutable Observer does not realize when an HTMLElement has been added inside a shadow root.

Do you think there's a way to extend the Custom Elements polyfill, so it works with elements inside a shadow root?

Using native Shadow DOM means a huge performance gain for PWA that uses AMP Shadow. Two things that are a performance drain when Shadow DOM is polyfilled:

1. Scoping the CSS, both the runtime  and the custom ones
2. The fact that for every new amp doc, we are adding new CSS styles to the whole document

**Comment by dvoytenko** [comment]
Thanks for the report. We'll definitely add SD v1 soon.

**Comment by dvoytenko** [comment]
@oliverfernandez Thanks for reporting again. The issue is with the custom elements polyfill we use. I filed it in https://github.com/WebReflection/document-register-element/issues/96 and we'll try to work with the polyfill repo to address this.

This is why our original goal was to launch SD support on iOS when Safari supports both SD and CE APIs. My expectation is that this should happen in the upcoming Safari release and it's already in Safari Tech Preview.

**Comment by oliverfernandez** [comment]
Thanks @dvoytenko !

Yes, CE was landed past November in Webkit. If they follow the same pattern than they did with SD (which was landed in Webkit in November 2015, and released in Safari iOS 10), we can expect they release it the next Safari version for iOS 11.

However, I think it's worth giving the CE Polyfill a try. Right now iOS 10 is installed in around 75%. That means we'd need to wait around 1 year and a half to have native CE available in a significant percentage of iOS devices  

During my testings I almost had finished support for custom elements v1 in AMP (if I'm not mistaken, it only affects shadow-embed.js). If you think it makes sense, I can finish the work and do the PR

**Comment by dvoytenko** [comment]
@oliverfernandez If we can, for now, condition the PR to enable `attachShadow` only when native CE are present - we should definitely proceed. On our end, we are actively pursuing CE polyfill fix. When it's done, we can expand `attachShadow` to all platforms. How does this sound?

**Comment by oliverfernandez** [comment]
@dvoytenko 

I'm working on it right now!

**Comment by dvoytenko** [comment]
@oliverfernandez  Thanks!

**Comment by oliverfernandez** [comment]
@dvoytenko PR done
