### ISSUE TITLE
Feature request: need a amp-read-more widget

### ISSUE THREAD

**Issue by stonezhong** [ampproject/amphtml#6894]
This feature request is created per https://github.com/ampproject/amphtml/issues/6783

## Need a amp-read-more widget

It should have
a section for "short" text
a section for "long" text
a toggle button which user can toggle. When the button is toggled, either short text or long text will be visible.

User should have control to the style for short text, long text and the toggle button it self.

## What browsers are affected?

All browsers

## Which AMP version is affected?
1.0

**Comment by jpettitt** [comment]
95% of this exists - it's `amp-access` where the login url doesn't pop a dialog it just short circuits to the return url with 'success' .  In fact this would make a good extension to `amp-access` IMHO becasue then the ability to read more could be tied to metering and paywall.

**Comment by rudygalfi** [comment]
@ericlindley-g Could you explore if AMP Bind might address this? If so, an AMP By Example page demonstrating this would be great to have.

**Comment by ericlindley-g** [comment]
@stonezhong, would [the "show more" example on this page demo'ing amp-accordion](https://ampbyexample.com/components/amp-accordion/) address your use-case?

If not, let us know what's missing—I think AMP Bind will address this use-case, if more is needed.

**Comment by ericlindley-g** [comment]
Closing this tentatively, as I think the example above covers this use case, but please feel free to re-open if you have more feedback — thanks!
