### ISSUE TITLE
Disallow `<amp-ad>` within position:fixed elements

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#690]
This should be a runtime check, runtime error and deny rendering. Docs need to be updated.

This may be relaxed in the future, but we do not want full page over lays on AMP pages, because users don't like them.

**Comment by Gregable** [comment]
Would you mind adding the 'validator' label as well. This should *also* be a validator error, so that toolchains will eventually be able to notice this.

**Comment by dvoytenko** [comment]
@Gregable I don't think we can cover this via validator - style calculation is a client-specific task.

**Comment by Gregable** [comment]
Good point, we're probably a good ways off from computing the full style of each element in validation at this point. It's possible, but may not be worth the hassle.

I had originally interpreted Malte's 'deny rendering' as denying the rendering of the entire page which would be unfortunate to validate, but upon further reflection, I suppose he intends to deny the amp-ad element.

Consider my suggestion reverted.

**Comment by Miroku87** [comment]
I'm sorry for the late reply to this but I am concerned about one thing: is AMP about rendering as fast as it can or about what users like? I thought it was the first.
And, by the way, do you have a research to support what you are saying? Since we are talking about a major technology that will affect everyone in the world I would like to see proof before pulling such request. 
Why did the project owner not ask for the same?

**Comment by dvoytenko** [comment]
@Miroku87 This is a very old pull request. The main motivation was to avoid interstitial ads. There are a number of ways to achieve the same feature, e.g. via [amp-sticky-ad](https://github.com/ampproject/amphtml/blob/master/extensions/amp-sticky-ad/amp-sticky-ad.md).

RE:scheduling of rendering. The priority is given to the content elements currently in the viewport over other elements. We constantly working to reduce the latency of rendering: both with existing protocols and new protocols. However, some ads still have significant render-blocking issues.

**Comment by Miroku87** [comment]
Thank you for replying even if this was old. Is there a place where all amp-ad components are gathered? (apart from filtering them by the "ad" substring) 
Also I guess an amp-fullscreen is not yet present?

**Comment by dvoytenko** [comment]
@bpaduch, do we have all ad-related components groupped somewhere? I thought we might.

@Miroku87 There's `amp-lightbox` that might do what you need for the fullscreen functionality.

**Comment by Miroku87** [comment]
I will look into that thank you for your time!

**Comment by bpaduch** [comment]
There's a list of all components, and they're grouped.  Here's the ads-related ones: https://www.ampproject.org/docs/reference/components#ads-analytics-paywalls

**Comment by Miroku87** [comment]
Thank you very much @dvoytenko and @bpaduch
