### ISSUE TITLE
presubmit check fail to check `console` in test files

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#6901]
related line:
https://github.com/ampproject/amphtml/blob/master/build-system/tasks/presubmit-checks.js#L718

Any other forbiddenTerms with a whitelist will not be checked if the file is in test folder. I think this is desired but not for the case of `console`?

**Comment by muxin** [comment]
We don't check `forbiddenTerms` in test folders. I think it's legit to ban some terms in test files such as `console`

**Comment by jridgewell** [comment]
Closed by https://github.com/ampproject/amphtml/pull/7234.
