### ISSUE TITLE
VideoManager: isInteractive() can dynamically change now with amp-bind

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#6909]
video-manager needs to support `isInteractive()` changing at runtime since `controls` attribute can change with bind. It should become an observable.

**Comment by adelinamart** [comment]
@aghassemi referenced issues is closed. What's left to be done here? Thanks

**Comment by aghassemi** [comment]
Still applicable. Referenced issue is just related and does not solve the issue.
