### ISSUE TITLE
Please make amp-plugin for WebStorm or PyCharm.

### ISSUE THREAD

**Issue by jet10000** [ampproject/amphtml#6918]
Please make amp-plugin for WebStorm or PyCharm.

https://www.jetbrains.com/

https://www.jetbrains.com/webstorm/

https://www.jetbrains.com/pycharm/

**Comment by rudygalfi** [comment]
@ericlindley-g has been thinking a bit about IDEs and AMP development, so I'm going to shift him to being the sole assignee here. This would be a longer-term ambition, though, so just adding this to our general backlog.

**Comment by aghassemi** [comment]
Unlikely AMP Core team will create these components due to priorities and often need for changes on the platform code itself. We would be happy to see them contributed by the platform providers or the community.
