### ISSUE TITLE
Support basic validation rules on amp-selector

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#6930]
**Looking for a workaround for this feature?**
See couple of them [below](https://github.com/ampproject/amphtml/issues/6930#issuecomment-391127624) in the comments

----

The most basic one would be to support `required`.

This will probably require implementing the different validation/input interfaces the browser provides for built in inputs. For example, the following APIs are used on `input`:

* checkValidity():boolean
* validity:ValidityState
* validityMessage:string

These should probably already work on the current `amp-selector`.
* focus():void
* `blur` event

Extra bonus points to support:
* `min` and `max` for multiple selection limitation.

**Comment by IamAlta** [comment]
@aghassemi, @adelinamart 
Is there any action on having amp-selector to have one or more be required? (I see the original request was Jan 2017.)

If not, is there a clever way to check that one was selected (validated) before submitting the form?
We are about to go live and trying to think outside the box to make this happen.

Thank you all for your diligence in working on the AMP project. I appreciate your work.

**Comment by aghassemi** [comment]
@IamAlta There are couple of workarounds:

1- You can use `amp-bind` and a visually hidden `input` to sync the value of `amp-selector` with the `input` and use normal validation. See https://codepen.io/aghassemi/pen/PegPQp?editors=1001
2- you can use server-side validation using [form verification](https://www.ampproject.org/docs/reference/components/amp-form#verification)

**Comment by IamAlta** [comment]
@aghassemi,
Just a quick follow=up.
You're Swell! We got #1 working with ease!
Thank you.
And, enjoy the net neutrality that CA just passed :)

**Comment by IamAlta** [comment]
@aghassemi,
I found an issue with your nice solution: The message does not disappear when an option is selected.
I tried binding css to the message container but it doesn't work.

    <amp-selector on="select:AMP.setState({selectedItem: event.targetOption, vis:'hidden_input block' })"  layout="container">

Perhaps I'm using the wrong css — it seems to be dominated by

    [visible-when-invalid].visible {display: initial;}

so I used  display:block and that does not work.

See here
https://codepen.io/iamalta/pen/wXgNge

Do you or anyone have a spiffy solution for hiding the message when an option is selected?

**Comment by aghassemi** [comment]
dedup with https://github.com/ampproject/amphtml/issues/22750
