### ISSUE TITLE
Expose change event for amp-selector

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#6931]
This allows users to submit on selection change `on=change:form.submit`.

Not sure if using `amp-bind` would cover this already.

**Comment by camelburrito** [comment]
@choumx - does bind take care of this ?

**Comment by choumx** [comment]
Technically not amp-bind but a new [`select` event](https://github.com/ampproject/amphtml/blob/master/extensions/amp-selector/0.1/amp-selector.js#L204) for amp-selector exists now. Looks like the docs need to be updated.

`<amp-selector on="select:form.submit">` should work.
