### ISSUE TITLE
Easy way to view the non-AMP version of a page

### ISSUE THREAD

**Issue by thomaskuntzz** [ampproject/amphtml#6932]
Hi, it's just an idea of a feature (likely a button on the bar at the top of the page where there is the website URL) that allows to easily go to the non-AMP version of a page, because it's annoying when you're viewing an AMP page and you want the original one to manually edit the URL to find the original page.

You may find this stupid because I suppose you want people to use AMP, but there are really good reasons not to want to use AMP. Mine is that it's impossible to view an AMP page if you're offline.

So I think that it would be nice if users had the choice to view whichever version of the page they want to (at least while you perfect the AMP format so that it suits everyone's need).

**Comment by ericlindley-g** [comment]
Sorry for the delay on this, @thomaskuntzz — there's not much we can do within AMP, but the Google Search team is working on ways in their viewer header to make it easier to both share and access the canonical site while viewing an AMP page. I can't speak to specific UI, but I believe you'll be able to tap on an affordance to go directly to the canonical site.  Thanks for the feedback!

**Comment by thomaskuntzz** [comment]
Okay, thanks for the update and for caring, hope it'll be solved soon! ☺️
