### ISSUE TITLE
Make AMP pages viewable offline

### ISSUE THREAD

**Issue by thomaskuntzz** [ampproject/amphtml#6933]
As I explained it in #6932, the impossibility to view an AMP page offline may make users not want to use AMP versions of web pages. That's why I suggest making them viewable offline, so that we can benefit from a fast loading time, a non-cluttered web page and a lighter data usage even if we're not always connected to the Internet. 

Because - from my point of view at least - nobody cares that the page loads blazing-fast if it disappears as soon as you're offline.

So even if I'm absolutely not able to do anything to technically improve the AMP spec in order to solve this problem, I wanted to tell the maintainers that I think this is a crucial feature.

What do you think of it? :smiley:

**Comment by jridgewell** [comment]
There are two parts to this problem:

1. Publisher content needs to be accessible offline
2. AMP JavaScript needs to be accessible offline

**1** is entirely in the control of the publisher. We're already working to solve **2** using the experimental Cache Service Worker. Soon, it'll be enabled for all AMP documents, either served by the cache or served by the publisher.

**Comment by thomaskuntzz** [comment]
Right now an AMP page looks like this on my phone when I'm offline... You see the issue? 😄

![screenshot_2017-01-09-08-32-57](https://cloud.githubusercontent.com/assets/16361470/21778961/d662b91c-d6a5-11e6-885e-7104ad323686.png)

I think this introduction of [an article about offline first web applications on A List Apart](http://alistapart.com/article/offline-first) could be relevant:
 
> When it comes to building apps, we often assume our users are very much like us. We picture them with the latest devices, the most recent software, and the fastest connections. And while we may maintain a veritable zoo of older devices and browsers for testing, we spend most of our time building from the comfort of our modern, always-online desktop devices.
>
> For us, a connection failure or slow service is a temporary problem that warrants nothing more than an error message. From this perspective, it is tempting to think of connectivity, mobile or otherwise, as something that will solve itself over time, as we get more network coverage and faster service. And that works, as long as our users stay above ground in large, well-developed—but not overly crowded—cities.
>
> But what happens once they descend into the subway, board a plane, travel over land a bit, or go live in the countryside? Or when they stand in the wrong corner of a room or simply find themselves part of a huge crowd? Our carefully constructed app experiences become sources of frustration, because we rely so fully on that ephemeral link back to the servers.
>
> This reliance ignores a fundamental truth: Offline is simply a fact of life. If you’re mobile, you’ll be offline at some point. It’s okay, though. There are ways to deal with it.

**Comment by cramforce** [comment]
The above is a Google URL. We all agree that Google should make that work offline :)
