### ISSUE TITLE
Different top-level domain for 3rd party content in Cacher

### ISSUE THREAD

**Issue by cgorbit** [ampproject/amphtml#6942]
Hi!
Does custom AMP cachers must distribute content from domains which differs in top-level domain?

Or does scheme below meet all requirements?
(.+\.)?cdn.foobar.TLD
(d-\d+\.)?3p.foobar.TLD
(TLDs in both domains are the same)

**Comment by cgorbit** [comment]
?

**Comment by jridgewell** [comment]
I'm not sure I understand the question.

**Comment by cgorbit** [comment]
Google AMP Cache delivers content from cdn.ampproject.org and 3p.ampproject.net.
Why TLDs differ?
Do they differ because of 3p is commercial content or for technological reason (e. g. web-security)?

**Comment by jridgewell** [comment]
They're different due to security concerns. All third-party content goes through `3p.ampproject.net`, which prevents it from accessing data in `cdn.ampproject.org` (cross origin policy).

**Comment by cgorbit** [comment]
But {cdn,3p}.ampproject.org will be enough to be cross-domain (but Google use {cdn.ampproject.org, 3p.ampproject.net}).

The only thing I can imagine is the cookies set in ampproject.org with explicit domain (they will be seen in all subdomains, including 3p.ampproject.org).

**Comment by dknecht** [comment]
Cloudflare use amp.cloudflare.com and 3p(d-*).cloudflareamp.net for security reasons.

**Comment by jridgewell** [comment]
> The only thing I can imagine is the cookies set in ampproject.org with explicit domain (they will be seen in all subdomains, including 3p.ampproject.org).

Exactly. To prevent any data access, we put them on entirely separate origins.

**Comment by cgorbit** [comment]
> Exactly. To prevent any data access, we put them on entirely separate origins.
Thank you for the answer.
Could you clarify one me thing about domains in AMP? Why 3p.ampproject.net use random subdomains? After all, javascript in d-RANDOM.3p.ampproject.net could set/get cookies for 3p.ampproject.net.

**Comment by jridgewell** [comment]
The random subdomains prevents ad A from taking control of ad B. It they used the same domain (say, just `3p.ampproject.net`), they'd be able to communicate, redirect, etc.
