### ISSUE TITLE
Presubmit check being run on generated file

### ISSUE THREAD

**Issue by bradfrizzell** [ampproject/amphtml#6945]
## Description
Presubmits are being run on dist.3p/current/integration.js
Is this the desired behavior to run a presubmit on a generated file?

## How do we reproduce the issue?
https://travis-ci.org/ampproject/amphtml/builds/190334019
PR that fails travis (and is blocked) due to this: https://github.com/ampproject/amphtml/pull/6922/files

**Comment by erwinmombay** [comment]
@bradfrizzell this is actually intentional as we wanted to keep f.js as light as possible we make scan it again so that it doesn't bring in polyfills etc. You might just need to whitelist it in presubmit-checks.js
