### ISSUE TITLE
[Validator] data-amp-replace="space delimited tokens" on input[type=hidden]

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#6948]
Allow `data-amp-replace="Space delimited tokens"` param on `input[type=hidden]`.

This is a follow up to #6421 - as we updated the format to how to use variable substitutions in forms. Also drop `default-value` attribute from that rule - no longer supported.

cc/ @Gregable @honeybadgerdontcare @powdercloud

**Comment by honeybadgerdontcare** [comment]
Is it necessary to restrict to only `Space delimited tokens`? If so, what are those tokens comprised of? If not then we can just allow any value like we did in `default-value`.

**Comment by honeybadgerdontcare** [comment]
Code complete, but not live in prod yet.

**Comment by honeybadgerdontcare** [comment]
/facepalm. This is already live as `data-*` attributes are allowed by the validator. I'll create another PR to roll this back and just remove `default-value`
