### ISSUE TITLE
Why use AMP instead of a carefully crafted html/css page?

### ISSUE THREAD

**Issue by systemaddict** [ampproject/amphtml#695]
I'm about to embark on a pretty ambitious AMP project. As many others I'm thrilled with this initiative and I really feel there's some global traction that could make this project important.

However, I'm struggling with arguments against building the site using just native html/css (but extremely carefully crafted). Following the Google PageSpeed Insights 100% would make the site insanely fast and perhaps even faster than AMP.

What are the arguments against such a custom strategy compared to the strict standards of AMP?

**Comment by cramforce** [comment]
The big one is that platforms can easily reason about your AMP file and know it is cheap to prerender (see https://medium.com/@cramforce/why-amp-html-does-not-take-full-advantage-of-the-preload-scanner-7e7f788aa94e#.dqf3xvxnj)

This is impossible for general web content.

But generally you can optimize beyond what AMP does. The problem AMP is trying to solve is that a lot of sites don't.
