### ISSUE TITLE
iOS Safari delayed navigation broken for deep linked URLs

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#6953]
This is a tracking bug for a general problem when AMP docs are embedded. This is currently impacting providing a full implementation of the `amp-app-banner` as [noted on the docs](https://github.com/ampproject/amphtml/blob/master/extensions/amp-app-banner/amp-app-banner.md#dec-15-2016-note-we-have-discovered-an-issue-with-amp-app-banner-going-into-the-holiday-code-freeze-banner-links-are-not-forwarding-correctly-to-the-app-store-on-ios-inside-the-amp-viewer-context-we-have-issued-a-temporary-mitigation-to-hide-the-banner-in-ios-inside-the-amp-viewer-until-we-can-launch-a-proper-fix-after-the-code-freeze-thanks-for-your-patience).

This might also impact any future delayed redirection, namely, we're in the process of implementing redirection after submit in forms #6619. This will probably fail if the redirect URL was a deep-linked one (i.e. will launch an app instead of navigating to a web page).

We're still working on researching the best way to handle this.

[Webkit bug filed](https://bugs.webkit.org/show_bug.cgi?id=165627).

cc/ @ericlindley-g

**Comment by mkhatib** [comment]
Closing this. We decided to go with viewer integration solution.

**Comment by aghassemi** [comment]
@ericlindley-g I don't believe this is fixed. Reopening. 
/cc @muxin @cvializ @bpaduch

**Comment by cvializ** [comment]
If the fix was implemented by the viewer integration, are you observing broken behavior inside or outside the viewer for the repro?

**Comment by aghassemi** [comment]
I looked at the code it was not implemented using viewer approach (still does window.top instead of sending a navigateTo message to the viewer). Not all viewers support `navigateTo` yet. We should only do this issue after #9170 so we could detect if viewer supports `navigateTo` or not

**Comment by muxin** [comment]
@aghassemi This is fixed right?

**Comment by aghassemi** [comment]
not really, this is about normal deep links outside of app-banner. Dup of https://github.com/ampproject/amphtml/issues/5284 so closing.
Work done in #9533 and #8291 will unblock creating `amp-deep-link` now.
