### ISSUE TITLE
Create subdomain when deploying to heroku for cross-origin tests

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#6957]
Currently when testing on heroku, the bootstrapUrl generated for 3p ads is still same origin. We should create subdomain when deploying to heroku and override boostrapUrl when running in heroku environment. This way, we can see cross-origin behavior for ads when testing on heroku.

**Comment by erwinmombay** [comment]
hmm honestly dont know if this is possible on heroku without provisioning custom domains etc
