### ISSUE TITLE
Intent to Implement: qlitics as amp-analytics vendor.

### ISSUE THREAD

**Issue by serendipitist** [ampproject/amphtml#6963]
Intend to implement qlitics  as amp analytics vendor . Would like to know the procedure to configure.

**Comment by avimehta** [comment]
@shireeshaps Please follow instructions on https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/integrating-analytics.md to send out a PR. you can cc me and I'll review the PR.

**Comment by rudygalfi** [comment]
Any updates here?

**Comment by serendipitist** [comment]
you can close this ticket
