### ISSUE TITLE
Intent to implement: mywidget for amp-ad

### ISSUE THREAD

**Issue by abogdashkin** [ampproject/amphtml#6965]
# Overview
Provides support for amp-ad type=mywidget
It will be widget with content recommendations.

Project site https://widget.my.com/

MyWidget is a service for personalizing content and increasing user metrics.
Our NeuroClick technology uses behavioral data of eighty million users, collaborative filtering algorithms and neural networks. NeuroClick delivers the most relevant content to every user of the site.
myWidget is a free platform used by web publishers to improve metrics and audience loyalty.

We have amp-iframe implementation now.
example for mobile https://www.google.com.ua/amp/s/hi-tech.mail.ru/amp/news/iphone-6-specs-official/

It's can look like horizontal or vertical block
![amp_example](https://cloud.githubusercontent.com/assets/482246/21812226/3d231d28-d763-11e6-9894-b813fbb0675a.png)

# Usage
Component will have data-cid (campaign id) attribute
```
<amp-embed height=300
    type=mywidget
    data-cid=campaign_id>
</amp-embed>
```

**Comment by lannka** [comment]
@abogdashkin it mywidget a [Taboola](https://github.com/ampproject/amphtml/blob/master/ads/taboola.md) like service?

/cc @jasti

**Comment by abogdashkin** [comment]
@lannka differs in technologies and features

**Comment by abogdashkin** [comment]
We've looked at Taboola example and improved our decision.
Updated main post.
