### ISSUE TITLE
Consider delaying fixed layer by one frame

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#6981]
I was profiling a bit and found that we ran the fixed layer code before we painted.

Could we delay it by another measure block to avoid that? It is not critical to do this as absolutely early as possible, right? @dvoytenko

**Comment by dvoytenko** [comment]
It's pretty important to do it asap. Big part of what fixed layer does it offsets positions to be visible under the header. W/o early execution we risk the fixed elements jumping.
