### ISSUE TITLE
Closing sidebar crashes Android Google News App

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#6986]
Possibly related to document click or history.

repro:

Find a CNN article on Google News Android App, open the sidebar, close the sidebar by tapping outside the sidebar. App crashes..

Reproducible on version 2.9.2 of Google News.

**Comment by aghassemi** [comment]
b/34220171

**Comment by mkhatib** [comment]
Closing this one as it is being tracked internally and does not seem related to AMP runtime itself. I've tried to reproduce using a basic Android app with a webview and the crash doesn't seem to "leak" from the runtime.
