### ISSUE TITLE
amp-list being render twice from google cache

### ISSUE THREAD

**Issue by roderickhsiao** [ampproject/amphtml#6987]
Please walk through the following steps for reporting an issue about AMP:

## Short description of your issue:

Just notice recently, our amp-list being render twice via google cache

## How do we reproduce the issue?

1. Access https://www.google.com/amp/s/bookmate.app.link/foodcombining
1. Notice that there are *two* amp-list xhr fired and render twice amp list items.
1. Accessing directly via the link works fine https://bookmate.app.link/foodcombining

The `<template>` tag from the markup looks fine.

Also notice that if passing #development=1, we can see the same issues as well

## What browsers are affected?

All browsers? Some specific browser? What device type?
All browsers

## Which AMP version is affected?
`Powered by AMP ⚡ HTML – Version 1483661191373 `

The google cache issue happens just recently while the debug mode is always there.

**Comment by dvoytenko** [comment]
@roderickhsiao Thanks for the report!

This happens in the iOS or iOS emulation modes, right? It looks like we have a bug when `amp-list` is a `position:fixed` element. In some cases on iOS we reparent these elements to avoid janky scrolling and that causes re-load. We'll fix.

**Comment by roderickhsiao** [comment]
Thanks @dvoytenko, yes it happens on iOS.

Very good to know the janky implementation, thats really neat.
