### ISSUE TITLE
Turn AMP off for select posts

### ISSUE THREAD

**Issue by mterenzio** [ampproject/amphtml#700]
I'm implementing a way to turn AMP off for select posts. Default would be on, but a check that a meta value of 'amp_enabled' exists and that value is false will result in a pass. 

What do y'all think?

https://github.com/Automattic/amp-wp/compare/master...mterenzio:mterenzio-patch-1?expand=1

**Comment by mterenzio** [comment]
My bad. This was meant for the Automattic amp-wp project.

**Comment by erwinmombay** [comment]
@mterenzio np. closing.
