### ISSUE TITLE
hash hrefs become `undefined` on MS Edge

### ISSUE THREAD

**Issue by drukepple** [ampproject/amphtml#7002]
Utilizing hash locations in `<a href>` results in "undefined" location in MS Edge

## How do we reproduce the issue?

Create a simple AMP page (it seems to be enough to simply include the amp.js script and otherwise ignore the rest of the required elements) that uses `<a href="#something">` links

Bug is reproducible in MS Edge here:
http://common.bbcomcdn.com/target-amp.html

This page is identical to the above page, only without the amp.js script tag:
http://common.bbcomcdn.com/target-noamp.html

1. Use MS Edge
2. Create an amp page that utilizes a few `<a>` tags pointing to in-page # targets.
3. Click one of the # links
4. Note that the URL bar says something like `www.domain.com/undefined#something` -- the name of the page will be replaced by "undefined"
    * For example, after loading the target-amp page above, clicking on the "A" link will cause the URL to be "http://common.bbcomcdn.com/undefined#a"
5. Additionally, utilize `:target` styles to style various divs whos ids are named after the targets in the links.
6. Note that depending on the order clicked, the styles may or may not be applied correctly.
    * In the test page provided above, normally clicking on the "A" link will turn the "A" div a different color, then clicking on the "B" link will return the "A" div to its normal color while making the "B" div the different color.  In Edge, clicking "A" (in a freshly loaded page) will result in expected styles (although the "undefined" problem happens), but then clicking "B" will result in both the "A" and "B" divs having the different colors.

## What browsers are affected?

MS Edge, mobile (tested 20.10240.17113.0) as well as desktop (tested 20.10240.17146.0)

## Which AMP version is affected?

I've only been using AMP for a short time; only noticed this today after trying to do some `:target` styling. The AMP version from the console is `Version 1483661191373`

My suspicion is that there is something going on with the history API within AMP, and it's not playing nicely with Edge. I believe that clicking on a hash link will trigger a popstate event, but that's [not working in Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/3740423/).

**Comment by jridgewell** [comment]
@mkhatib: I believe you have a MS Edge install? Or @camelburrito?

**Comment by mkhatib** [comment]
I can take a look. Thanks for filing @drukepple

**Comment by camelburrito** [comment]
@mkhatib i think this is a P0 can you take a look ! (I have a windows machine you can borrow)

**Comment by mkhatib** [comment]
Looks like a bug in Edge history.pushState implementation. I filed a [bug for them here](https://github.com/Microsoft/ChakraCore/issues/2479) - will patch in our code to use the current page path internally to fix this.
