### ISSUE TITLE
Support server-rendered AMP pages.

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#7022]
Server-rendered here refers to an AMP cache that executes the initial transformations that AMP would otherwise apply to a document (such as element layout) on the server side.

**Comment by dknecht** [comment]
What types of transformation are you thinking?

**Comment by cramforce** [comment]
Mostly what we call "applying layout" (like `layout=responsive`) and inserting AMP's core CSS.

The goal is to be able to remove the "AMP boilerplate" CSS, so the document can be painted in a decent fashion without running JS.

**Comment by dknecht** [comment]
That makes sense.   Can you share design doc when ready?

**Comment by dvoytenko** [comment]
@dknecht Sure! In short right now though: everything in [`applyLayout` method](https://github.com/ampproject/amphtml/blob/9b66415b9fc290b74782b286621a8c69fee3b149/src/custom-element.js#L225-L339) does not depend on runtime capabilities at all. So, the idea is that server can port this code and execute it server-side, thus leaving less work to do for runtime. but more importantly - the document can be shown faster.

**Comment by dvoytenko** [comment]
/to @honeybadgerdontcare when you have design doc ready, could you please post it here?

**Comment by honeybadgerdontcare** [comment]
We don't have a design doc as we've been using the code in [`applyLayout` method](https://github.com/ampproject/amphtml/blob/9b66415b9fc290b74782b286621a8c69fee3b149/src/custom-element.js#L225-L339) as what needs to happen in AMP Cache. I can try to be more verbose than the code if that's helpful.

**Comment by dvoytenko** [comment]
@honeybadgerdontcare Perhaps let's add more description to this item with details, including `applyLayout` port?

**Comment by honeybadgerdontcare** [comment]
Sounds good.

**Comment by honeybadgerdontcare** [comment]
@dknecht and @dvoytenko here are the steps to apply the static layout to an AMP document. Let me know if something isn't clear or doesn't appear correct.

Static layout is [currently applied](https://github.com/ampproject/amphtml/blob/master/src/custom-element.js#L226) to the document by the AMP Runtime on the client. These changes apply that static layout within the AMP Cache and provide a signal to the AMP Runtime that the static layout was applied on the server side.

Steps

1. Apply static layout to custom-element tags (`<amp-…>`) per custom-element.js [applyLayout](https://github.com/ampproject/amphtml/blob/master/src/custom-element.js#L226), may also want to see [parseLayout](https://github.com/ampproject/amphtml/blob/master/validator/engine/validator.js#L2598) and [calculateLayout](https://github.com/ampproject/amphtml/blob/master/validator/engine/validator.js#L2719) in validator.js
   1. [Calculate](https://github.com/ampproject/amphtml/blob/master/src/custom-element.js#L262) the effective layout.  
      Note that [getNaturalDimensions](https://github.com/ampproject/amphtml/blob/master/src/layout.js#L247) assumes dimensions via [naturalDimensions_](https://github.com/ampproject/amphtml/blob/master/src/layout.js#L70) and AMP Cache differs here for `amp-audio` by setting `height=auto` and `width=auto`
   1. Add to the tag’s [`class` attribute](https://github.com/ampproject/amphtml/blob/master/src/custom-element.js#L315) the value of [getLayoutClass](https://github.com/ampproject/amphtml/blob/master/src/layout.js#L120)
   1. If [isLayoutSizeDefined](https://github.com/ampproject/amphtml/blob/master/src/layout.js#L130) then add to the tag’s [`class` attribute](https://github.com/ampproject/amphtml/blob/master/src/custom-element.js#L317) the value `i-amphtml-layout-size-defined`
   1. Add appropriate [styles](https://github.com/ampproject/amphtml/blob/master/src/custom-element.js#L319) to `style` attribute depending on the layout
   1. If [layout is responsive](https://github.com/ampproject/amphtml/blob/master/src/custom-element.js#L328) then create a [child tag](https://github.com/ampproject/amphtml/blob/master/src/custom-element.js#L329) `<i-amphtml-sizer style=...>` with appropriate [styles](https://github.com/ampproject/amphtml/blob/master/src/custom-element.js#L330)
1. Add attribute `i-amphtml-layout=”{calculated_layout}”` to custom-element tags that have static layout applied
1. Add `i-amphtml-layout` attribute to `<html>` tag
1. Insert placeholder `<style amp-runtime></style>` before `<style amp-custom>`
1. Remove boilerplate and add `i-amphtml-no-boilerplate` attribute to `<html>` tag iff:
   1. [These custom-elements](https://github.com/ampproject/amphtml/blob/master/src/render-delaying-services.js#L28) are not present in the document:
      1. Referrer CSS classes: `amp-dynamic-css-classes`
      1. Experiment control: `amp-experiment`
      1. Custom-elements that delay rendering: `amp-accordion`
   1. Attributes [`media`, `sizes`, and `heights`](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-layout.md) are not present in the document.

**Comment by dknecht** [comment]
@ampproject/cloudflare FYI

**Comment by dvoytenko** [comment]
To stress - these optimizations are just low-hanging-fruit optimizations that a cache server can do. They are optional (as long as AMP runtime knows to expect them) and we can likely add more and more such optimizations in the future. 

This is very experimental as we haven't yet measured the effect of such optimizations in the real world. But I expect it would be very meaningful.

**Comment by dknecht** [comment]
@dvoytenko Why was this closed?

**Comment by dvoytenko** [comment]
AMP Runtime now can ignore static layout transformations if applied on the Cache side. This was at the core of this issue. It's done [here](https://github.com/ampproject/amphtml/blob/1304c6cb81c6a87311226474a9265e4f657a9ccb/src/custom-element.js#L230). Not sure if we were tracking something else under this bug? If so, I'll be happy to reopen.

**Comment by dknecht** [comment]
Should the changes be documented in the amp cache modification doc?

**Comment by honeybadgerdontcare** [comment]
They will be once it is in use.

**Comment by dvoytenko** [comment]
@honeybadgerdontcare For posterity. Could you please file a bug on that? This issue was specific to runtime changes.

**Comment by honeybadgerdontcare** [comment]
Done in #8437.
