### ISSUE TITLE
Support show standard actions on all elements

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#7027]
Currently AMP supports `hide` on all elements as a [standard action](https://github.com/ampproject/amphtml/blob/master/spec/amp-actions-and-events.md).

I like to extend the standard actions to include `show` and `toggle` for all elements as well. Showing/hiding elements is already somewhat supported by using `amp-accordion` or CSS tricks such as using `:focused` pseudo-selector. `amp-bind` would be supporting this as well, therefore I do not see any fundamental issue with extending the standard actions to include `show` and `toggle`. 

@ericlindley-g @dvoytenko @cramforce

**Comment by dvoytenko** [comment]
This is only a matter of us supporting a more advanced layering system so that we can react to arbitrary UI changes.

Another thing we have to keep in mind - some actions use transitions, so we need to be ready to run our update/layer pipelines after transitions complete.

/cc @jridgewell

**Comment by aghassemi** [comment]
@dvoytenko is the advanced layering system is requirement before we support this? Looking at `amp-accordion`, it does nothing other than hiding/showing its container and waiting for the `pass` to do the proper scheduling. I assumed we can take the same approach as  `amp-accordion` for these actions.

**Comment by dvoytenko** [comment]
@aghassemi We can certainly do additional ad-hoc improvements and fixes to the current set of tools we employ - they can cover probably most of these actions. Some more serious issues will arise from above-the-element style changes and transitions.

**Comment by alanorozco** [comment]
If we support `show` and `toggle` it won't work when the `display: none` property is set via a CSS selector since the [internal implementation for `toggle`](https://github.com/ampproject/amphtml/blob/a8acbd2dac5f8d2835c934e3f7adccd62902941a/src/style.js#L139) will set `element.style.display` to empty. This means that it will default to the style defined previously, and the CSS rule that hides the element will remain valid.

This is presumably the original reason why only `hide` was implemented.

Alternatives:

A. **Support only inline `display: none`.**
B. **Use an AMP-specific classname** like `.amphtml-hidden` or something similar. 
C. **Set a default display value** (`block`?) for elements that have been dynamically shown.

IMO, option C should not be considered since it would cause a bunch of unintended presentation consequences.

Thoughts?

**Comment by aghassemi** [comment]
`A` is too restrictive since they can't have inline style, so it would only work for amp-elements that supports layout=nodisplay
`B` is a good approach but instead of a AMP specific class, let's just do it for the HTML5 `hidden` attribute (e.g. have show also remove hidden attr). Now for AMP elements, layout=nodisplay works and for non-AMP attribute `hidden` works.
`C` definitely not `block`. We could do `initial` but even that it has problems since inline style gets set overriding CSS styles a problem for when `amp-bind` allows switching class names. So let's not do C.

I recommend doing `B` using `hidden` attribute and documenting this with a big and shinny "Note:" section in the MD file (You probably don't need computed style anymore, we can just check `elem.style.display` AND existence of `hidden` attribute for toggle)

**Comment by alanorozco** [comment]
Using `hidden` sounds great.

Two things about `nodisplay` (unless I'm missing something):

1. Only a subset of AMP elements support `nodisplay`. We could allow `nodisplay` by default on all AMP elements, but even then...
2. What would the layout resulting from the `show` action default to?

**Comment by cramforce** [comment]
`hidden` should work just fine on elements, no?

**Comment by alanorozco** [comment]
@cramforce Should work fine on normal elements but I'm not sure about AMP elements since the attribute would presumably need to be whitelisted for all elements?

**Comment by aghassemi** [comment]
I guess we suffer from the same issue as html/css where layout and visibility are mixed making writing a generic `show(elem)` that works in all cases pretty much impossible. 

So to summarize:
- Looks like we can only support `show` properly for elements hidden either by 
  1. a previous call to `hide()`
  2. with `hidden` attribute on them
- `hidden` attribute is not supported on AMP elements ( https://github.com/ampproject/amphtml/issues/7753 o support ). For now work-around that should work in most cases is wrapping the AMP element in a `div` with `hidden` attribute. But hopefully we can get #7753 in soon.
- We need to document and/or print dev errors to make these restrictions clear. 

Does this capture everything?

We should still proceed with the PR but add better documentation and examples to make it clear when `show` and `toggle` work and what the cause is when they don't work.

**Comment by alanorozco** [comment]
Sounds great, thanks @aghassemi!

Updated #7658 to support standard elements. Follow-up PR will handle the `hidden` attribute on AMP elements.
