### ISSUE TITLE
Build fails on clean checkout

### ISSUE THREAD

**Issue by dknecht** [ampproject/amphtml#7039]
Checkout fresh repo checkout 1484259764365 and run:

```
gulp build --css-only

....

Cannot find module '../../build/css' from '/amphtml-deployer/amphtml/src/inabox'
Cannot find module '../build/css' from '/amphtml-deployer/amphtml/src'
Compiled kill.js
Compiled core.js
Cannot find module '../build/css' from '/amphtml-deployer/amphtml/src'
Cannot find module '../build/css' from '/amphtml-deployer/amphtml/src'
Cannot find module '../build/css' from '/amphtml-deployer/amphtml/src'
Compiled shell.js
Cannot find module '../../build/css' from '/amphtml-deployer/amphtml/src/service'
Compiled integration.js
Cannot find module '../../build/css' from '/amphtml-deployer/amphtml/src/service'
Cannot find module '../../build/css' from '/amphtml-deployer/amphtml/src/service'
Compiled install-alp.js
Compiled polyfills.js
Compiled ampcontext-lib.js
Compiled inabox-host.js
```

**Comment by aghassemi** [comment]
@dknecht An npm sub-dependency has introduced changes breaking any build without https://github.com/ampproject/amphtml/commit/c5d305c93bafb4ac273c49ddac761b3a30a6d1f1 . `1484259764365` does not include c5d305c93bafb4ac273c49ddac761b3a30a6d1f1, if you cherry pick c5d305c93bafb4ac273c49ddac761b3a30a6d1f1 and remove `node_modules` and do a `npm install`, problem should go away.

**Comment by dknecht** [comment]
So does that mean when we publish a tag versioned it could technically be different based on when we build?

**Comment by erwinmombay** [comment]
@dknecht i think its time we move to yarn so we can guarantee deterministic builds

**Comment by dknecht** [comment]
I am not a javascript guy so it just never occurred to me.

**Comment by dknecht** [comment]
/to @ipostelnik this is why the auto-deployer broke
