### ISSUE TITLE
How to ensure data continuity when deleted client identify?

### ISSUE THREAD

**Issue by wupengFEX** [ampproject/amphtml#7042]
When using authorization endpoint or pingback endpoint, I send data through client identify and save data in the publisher's database. After that i deleted local storage in browser, then the publisher data become useless. because when i browse the page again, the id will be re-created and is different from the previous id, so we can't update publisher id with current id, what should we do at this time?

**Comment by jridgewell** [comment]
This is actually on purpose for privacy, and functions the same as if you cleared all browser data (cookies, session storage, local storage) on a normal page. The way to update the `clientId` to the new value (and associate the old records to the new value) is to get the user to sign in so that you can verify "this is the same user with a new client id".

**Comment by wupengFEX** [comment]
@jridgewell Thanks very much for your reply, According to what you said, i know how to update clientId under login state, however what do AMP do when not login in, if deleted local storage, how to associate the old records to the new value? If amp can't do that, How to inform the publisher to delete the data which marked with previous clientId in the database, such as pingback data.

**Comment by jridgewell** [comment]
> however what do AMP do when not login in, if deleted local storage, how to associate the old records to the new value?

AMP can't do this, the same as a normal HTML page can't. If the user deletes all of their cookies on a normal HTML page, there's no way to identify them as the same user until they login.

> How to inform the publisher to delete the data which marked with previous clientId in the database, such as pingback data.

There's also no way to do this, which is the same as a normal HTML page.

**Comment by wupengFEX** [comment]
@jridgewell  Understand, this program is indeed difficult to solve and will result in more useless data in publisher's database, i think it's a good way to let publisher to organize the database after a period of time, clear data that has not been manipulated for a period of time, for example, one year!
