### ISSUE TITLE
Adsense for Search not clickable

### ISSUE THREAD

**Issue by gslsouza** [ampproject/amphtml#7047]
Ads generated by adsense for search, amp-ad type csa, 
are not clickable.

## How do we reproduce the issue?
In the demo the ads are not clickable:

http://google-ads-amp-demos.com/amp_tests/csa/afs-atf.html

## What browsers are affected?

All browsers I tested: chrome, canary, ios safari, firefox, android chrome

## Which AMP version is affected?

This is a new issue. AMP version 1484259764365

**Comment by lannka** [comment]
@megankj Hi Megan, do you want to take a look?

**Comment by megankj** [comment]
Thanks for catching this @gslsouza! FYI, the fix for this bug is now viewable in the dev-channel and will be fully live tomorrow.
