### ISSUE TITLE
-amp-slides-container

### ISSUE THREAD

**Issue by semiromid** [ampproject/amphtml#7056]
## Short description of your issue:

При использовании amp-carousel, будет добавляться в настольной версии отступ с низу.
/ 
When using the amp-carousel, will be added to the desktop version of the indentation from the bottom

Если мы используем мы используем в настольной версии браузера:
If we use, we use the desktop version of the browser:
http://imgur.com/a/QJ49e

Если мы используем мобильную версию браузера:
If we use a mobile version of your browser:
http://imgur.com/a/vjX1f

Возможно стоит заменить:
You may want to replace:
Maybe to replace:

это / it - `overflow-x: auto!important;` 
на это / on it -  `overflow-x:hidden !important;`
в классе / in class `-amp-slides-container`

## How do we reproduce the issue?

https://jsbin.com/dosazebule/edit?html,output

```
<!doctype html>
<html amp lang="ru">
  <head>
    <meta charset="utf-8">
    <title>Hello, AMPs</title>
    <link rel="canonical" href="http://example.ampproject.org/article-metadata.html" />
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">



    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>


    <style amp-custom>

      .conteiner-carousel{
        width: 100%;
        background-color: orange;
      }

      .test-7{
        width: 100%;
        height: 20px;
        background-color: blue;
      }

    </style>

    <!-- Скрипт загрузки amp -->
    <script async src="https://cdn.ampproject.org/v0.js"></script>
    <!-- Скрипт слайдер бара -->
    <script async custom-element="amp-sidebar" src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js"></script>
    <!-- Скрипт для карусели -->
    <script async custom-element="amp-carousel" src="https://cdn.ampproject.org/v0/amp-carousel-0.1.js"></script>
  
  </head>









  <body>

      <div class="conteiner-carousel">
          <amp-carousel height="56" layout="fixed-height" type="slides">

                            <amp-img
                                src="http://www.centrplitki.ru/image.html?f=Piazza_navona_56x56.jpg"
                                width="56"
                                height="56"
                                layout="responsive"
                                alt="monitor"></amp-img>



                            <amp-img
                                src="http://www.centrplitki.ru/image.html?f=Piazza_navona_56x56.jpg"
                                width="56"
                                height="56"
                                layout="responsive"
                                alt="monitor"></amp-img>                                                              
          </amp-carousel>
      </div>

      <div class="test-7">
        Test
      </div>


  </body>
</html>
```

## What browsers are affected?

 Chrome. Версия 55.0.2883.87 m

## Which AMP version is affected?

<script async src="https://cdn.ampproject.org/v0.js"></script>

**Comment by camelburrito** [comment]
@semiromid - i don't completely understand what the issue is here. I put your code in JS bin and tested it on Mac - chrome/safari and FF 

https://output.jsbin.com/vakumemevo/1/

I don't see the gap as you have specified in the image, could you please send us more details please.

**Comment by semiromid** [comment]
I use OC Windows 8.1
I use Chrome. v 55.0.2883.87 m


i use
[](https://jsbin.com/vakumemevo/1/edit?html,output)

Если мы используем мы используем в настольной версии браузера:
If we use, we use the desktop version of the browser:
http://imgur.com/a/JdqHl

Если мы используем мобильную версию браузера:
If we use a mobile version of your browser:
http://imgur.com/a/mcu8Z


You not see maybe you not reloaded browser page.
You do not see because you may not have restarted the browser page.
Вы не видите возможно потому что вы не перезагрузили страницу браузера.

**Comment by camelburrito** [comment]
Dupe of https://github.com/ampproject/amphtml/issues/6243

Fix should be live with tomorrow's release.
