### ISSUE TITLE
Support indexing related meta tags

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#7057]
I believe meta tags like `<meta name=robots content=noindex>` don't currently validate, but might be mistaken. If I am not, we should add support for them.

http://www.robotstxt.org/meta.html

**Comment by honeybadgerdontcare** [comment]
`<meta name=robots content=noindex>` is valid as are other combinations of `name` and `content`. https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii#L379

**Comment by Gregable** [comment]
wai

**Comment by cramforce** [comment]
Woot. Thanks!
