### ISSUE TITLE
Update guidelines to recommend SRI for custom fonts.

### ISSUE THREAD

**Issue by fulldecent** [ampproject/amphtml#7060]
Custom fonts are documented at:

> https://www.ampproject.org/docs/guides/responsive/style_pages#the-custom-fonts-exception

You CAN reference an external file for fonts.

The current example (link above) shows a link to a font style sheet:

>   <link href="https://fonts.googleapis.com/css?family=Roboto:200,300,400,500,700" rel="stylesheet" type="text/css">

Best practice for `<link>` is to use Subresource Integrity. SRI is documented at:

> https://www.w3.org/TR/SRI/

Therefore, the example should be updated to:

> `<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:200,300,400,500,700" integrity="sha384-kPC23LXBnM90mw9ntWjNWxvMZKlAYFEUjK6bS6TSSeBWU5S0GdcVib2uYrpffb2y" crossorigin="anonymous">`

**Comment by Gregable** [comment]
Allowed for stylesheets, live everywhere.

**Comment by Gregable** [comment]
Actually, I just realized that this is a request for documentation, not validation. Reassigning to @cramforce to see what he wants to do here.

**Comment by cramforce** [comment]
We don't really document how to include these fonts. Happy to add a link to a downstream provider who does support it where applicable.
