### ISSUE TITLE
Cleanup form proxy rewrite

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#7063]

**Comment by erwinmombay** [comment]
this is for the AST transformation correct? (if so ill assign to myself)

**Comment by dvoytenko** [comment]
No. This is cleanup after your work is done :)

**Comment by adelinamart** [comment]
@dvoytenko is there an issues related to the work that needs to be done for this to be cleaned up? Thanks

**Comment by dvoytenko** [comment]
This is still blocked by @erwinmombay 's work.

**Comment by rsimha** [comment]
@dvoytenko Is this issue still valid?
