### ISSUE TITLE
AMP Viewer causing CSS alterations in production

### ISSUE THREAD

**Issue by ryanpoplin** [ampproject/amphtml#7066]
## How do we reproduce the issue?

Steps for reproduction:

1. Go here: https://www.google.com/amp/s/amp.cnn.com/cnn/2016/07/15/world/live-blog-turkey/index.html (We're using latest Chrome via inspect mode)
2. You'll notice in the top right hand corner a hamburger icon is not visible in the header (there is a visible hamburger icon during local testing, however; not when it's within the 'AMP Viewer' in production, though)

## What browsers are affected?

We'd like to have this issue resolved in the context of the most popular browser and stable representation of the WebKit engine: Google Chrome via inspect mode (however, I'm seeing this on my iPhone 6s Plus via Safari and Firefox, too)

## Which AMP version is affected?

The version of AMP being used: 1484259764365, and this issue occurred about a week ago in production without our alterations of the CSS related to the icon.

## General

Is there an official way for us Developers to test our AMP articles in a AMP Viewer? I can at least speak for myself and fellow team members; we'd like to be able to see our entire experience in a sandbox env before pressing the deploy trigger (perhaps I'm missing this somewhere and it's available?)

**Comment by jridgewell** [comment]
This is because your using a `amp-sidebar ~ nav` CSS selector, and the amp-sidebar is being reparented to avoid a `position: fixed` bug.

**Comment by alf7** [comment]
If I understand Justin's comment correctly, I don't think this is something that can be fixed on the viewer side.

**Comment by jridgewell** [comment]
Yup. The general request has been moved to https://github.com/ampproject/amphtml/issues/7121.
