### ISSUE TITLE
Include all link relations in documentLoaded message to viewer

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#7086]
Viewers would like to display the correct favicon for a given page they display. For that we'd need to send up the `<link rel=icon>`.

I think it makes sense to generalize this and to just send up a map of relations that map all link tags to their `rel` value (split by space) and href.

CC @chenshay 

See b/34356674 for viewer changes at Google.

**Comment by ericfs** [comment]
Related #7058

**Comment by cramforce** [comment]
Ah :) @muxin: Did you already start working on this?

**Comment by jridgewell** [comment]
@cramforce: @muxin has https://github.com/ampproject/amphtml/pull/7078 already. @muxin, can you extend to support all link tags?

**Comment by muxin** [comment]
I'll start working on it by including the link tags map info into `document-info-impl.js`.

**Comment by muxin** [comment]
Would there be multiple `link[rel=prefetch]`, `link[rel=preload]`, `link[rel=preconnect]`? Do we really need to send these info up?

**Comment by muxin** [comment]
Or when the `documentLoaded` message is sent, those link tags haven't been added to the head?

**Comment by cramforce** [comment]
Lets filter these. It would be OK for them to be in the data, but because transfer isn't free we can drop them. Soon, there will be more of those in the doc from the server side.

**Comment by dknecht** [comment]
What is being added server side?

**Comment by cramforce** [comment]
@dknecht We will add `dns-prefetch/preconnect` for the sub resource domains like `randomcdn-com.cdn.ampproject.org`.

**Comment by muxin** [comment]
@cramforce OK.

**Comment by muxin** [comment]
@ericfs About the naming for the link tag map (key is the `rel` and value is the `href`), is `linkRels` OK? It will be like:
```
documentLoaded:
{
  title: 'foo',
  ...
  linkRels: {'canonical': 'foo.html', 'icon': 'foo.gif'}
}
```

**Comment by ericfs** [comment]
lgtm

**Comment by muxin** [comment]
@ericfs @cramforce Should all the link href be transformed to absolute path?

**Comment by cramforce** [comment]
Doesn't reading `.href` do that?

**Comment by muxin** [comment]
updated:
The `linkRels`'s value can be a string if there's only one href, or an array of string if there're multiple hrefs for the same `rel`
