### ISSUE TITLE
Status on Google Tag Manager implentation in AMP

### ISSUE THREAD

**Issue by gilbermudez** [ampproject/amphtml#7088]
Hello everyone.

I juts want to ask about implementantion of GTM in AMP.

If theres already an oficial way to implement it, could you share us an example or link. If it isn't, could you tell us how the progress is going or it will be integrated to the AMP-ANALYTICS tag?.

Thank you.

**Comment by cramforce** [comment]
It is supported. See announcement in https://analytics.googleblog.com/2016/10/google-tag-manager-giving-mobile.html

**Comment by lannka** [comment]
we should probably mention this in `amp-analytics.md` @avimehta @rudygalfi

**Comment by avimehta** [comment]
@gilbermudez You should see AMP as one of the options when you are creating a new account. 

Here are some docs for GTM/AMP: 
Start:
https://support.google.com/tagmanager/answer/7086920?hl=en . This page also has a bunch of other links for more info.

Setup:
https://support.google.com/tagmanager/answer/6103696

**Comment by jpettitt** [comment]
It should be pointed out that GTM for AMP and regular GTM are very different things.  The AMP version just lets you automate, in a rather limited way, other amp-analytics tags.  It doesn't allow 3p JS like the regular GTM.

**Comment by rudygalfi** [comment]
I think this thread has answered the core question. There is indeed support.

I've contacted the GTM team to propose some way to make support status / documentation more visible.
