### ISSUE TITLE
Whitelist fonts.com for link tag based inclusion and @font-face non-proxying

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#709]
Their prefix for font link tag and @font-face is https://fast.fonts.net.

Requires update of

- docs
- validator
- cache ingestion

**Comment by cramforce** [comment]
Validator change at Google ~~b/25215117~~
Cache change b/25214422

**Comment by Gregable** [comment]
This is live at Google and will be live in the amp runtime development more in an hour or so when the cache picks it up.
