### ISSUE TITLE
<amp-video> preroll

### ISSUE THREAD

**Issue by gcovato** [ampproject/amphtml#71]
Hi

According to the attached comment done by Taylor in the "Component Spec Document", would be possible to include the preroll attribute in the tag <amp-video>?

Thank you

Taylor Savage
Perfect. I'll add a `preroll` attribute to the spec for the simple, built-in case. For something like IMA a pretty straightforward Extended Component should be created to enable IMA ads directly, and similar Extended Components should be created for other media ad networks.

**Comment by rudygalfi** [comment]
#571 (amp-click-to-play) is potentially relevant here as a way to have an arbitrary video player

**Comment by sriramkrish85** [comment]
@gcovato - https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md#iframe-click-to-play this would help you.

**Comment by donohoe** [comment]
Just adding my 2 cents in support of this on behalf of The New Yorker. We'll try iframe approach in short-term but ability to indicate pre-roll with video is a big benefit.

**Comment by kashyapnitin** [comment]
it would be good to have a reference implementation of IMA SDK & Video ad support in the native amp-video tag too.. so that it saves lots of people doing all this custome work, while providing an efficient way of doing pre-roll video Ads

**Comment by jasti** [comment]
@gcovato, we won't be supporting preroll directly in amp-video but we will support it as part of a new player amp-ima-video. You can follow the implementation progress here: https://github.com/ampproject/amphtml/issues/5233 Please follow progress on that issue.
