### ISSUE TITLE
Amp Carousel slides mode awkward padding

### ISSUE THREAD

**Issue by jaspersorrio** [ampproject/amphtml#7100]
Amp Carousel has an awkward padding for images in slides mode in Chrome. This prevents the image from being full width. This effect is desired in mobile pages.

## How do we reproduce the issue?

1. Go to a Windows Computer & open Google Chrome
2. Go to https://ampbyexample.com/components/amp-carousel/
3. Go to type slides under basic usage
4. Image has unexplained border/padding.

## What browsers are affected?

Tested on:
Windows IE 11.0.96... 
Windows Chrome 55.0.2883.87  
Max Chrome 55.0.2883.95.

Works fine on IE & Mac Chrome.
Padding/Border on Windows Chrome. 

Works fine on all latest browsers on macOS Sierra v10.12.1

## Which AMP version is affected?

I'm not sure.

##Edit

This issue only exist on windows chrome. Carousel looks fine on mac chrome.

### Windows Chrome
<img width="100%" alt="screen shot 2017-01-21 at 12 33 44 pm" src="https://cloud.githubusercontent.com/assets/10573718/22171973/4550c1a0-dfd6-11e6-9aa5-15af0fcda1d7.png">

### Windows IE
<img width="100%" alt="screen shot 2017-01-21 at 12 34 49 pm" src="https://cloud.githubusercontent.com/assets/10573718/22171972/3dfb76ac-dfd6-11e6-8d40-211c05f30c50.png">

### Mac Chrome 
<img width="100%" alt="screen shot 2017-01-21 at 12 39 22 pm" src="https://cloud.githubusercontent.com/assets/10573718/22171982/ab36f1f6-dfd6-11e6-8162-6cff895203f1.png">

**Comment by jaspersorrio** [comment]
I found out why the images are not filling on chrome but on IE.

This is because [IE doesn't support object-fit](http://caniuse.com/#feat=object-fit). 

object-fit was added in this commit. c00ee3c66ed2127aaa8a52b4c9fcb06dff1ff30c

@amphtml-team May i ask, why do we add a default object-fit?

**Comment by camelburrito** [comment]
@jaspersorrio - did you try using layout=responsive on your slides (the individual slide elements)?

**Comment by jaspersorrio** [comment]
Yes i have tried using layout=responsive & layout=fill. 

I just realised that the bug only happened in Windows Chrome and Firefox. It works fine on a mac.

**Comment by camelburrito** [comment]
This is a dup of https://github.com/ampproject/amphtml/issues/6243
