### ISSUE TITLE
Does AMP support Angular2?

### ISSUE THREAD

**Issue by mubeentauni** [ampproject/amphtml#7102]
## Does AMP support Angular2 ?

I wanted to ask that i have a website build using Angular-2 cam AMP support websites build on angular 2 ? If Not, then is there any alternative out there for AMP ?

**Comment by jridgewell** [comment]
Do you mean directly on an AMP page? If so, no, AMP does not support using Angular or any other JS library.

**Comment by mubeentauni** [comment]
As you said directly i cant but can achieve this in some other way possible ? @jridgewell 
Thanks!

**Comment by jridgewell** [comment]
You can do a progressive web app, but that does not affect the AMP document itself. PWA essentially allows you to control the presentation of an iframe, and the iframe loads the AMP doc.
