### ISSUE TITLE
Intent to Implement: amp-analytics support for dynatrace

### ISSUE THREAD

**Issue by kamtschatka** [ampproject/amphtml#7104]
We are planning to implement amp-analytics support for dynatrace.

**Comment by rudygalfi** [comment]
Closing and adding to our 3P analytics project.

**Comment by rudygalfi** [comment]
Sorry ... Shouldn't have closed this. Any updates on this I2I?

**Comment by kamtschatka** [comment]
The patch is ready, but our infrastructure is not ready yet
