### ISSUE TITLE
(3 Things) 1. Question, 2. Error: On ampbyexample and 3 Suggestion

### ISSUE THREAD

**Issue by ayumihamsaki** [ampproject/amphtml#7105]
1. Question: Are we allowed to async loading fonts? For example:

Without async:
`<link href="https://fonts.googleapis.com/css?family=Noto+Sans:400,400i,700,700i" rel="stylesheet" type="text/css">`

With async:
`<link href="https://fonts.googleapis.com/css?family=Noto+Sans:400,400i,700,700i" rel="stylesheet" type="text/css" async>`

Because Google PageSpeed Insights says "Eliminate render-blocking JavaScript and CSS in above-the-fold content" for the link-font and async would fix it.

2. Error on ampbyexample website:

On this webpage the sidebar menu button does not work in the top left corner (due to AMP only allowing one amp-sidebar per page I am guessing)

https://ampbyexample.com/components/amp-sidebar/

3. Suggestion on https://www.ampproject.org/ website:

Is it possible to create and add a section called "tools" in the top navigation and then link it to a webpage with all your tools.

(Because it's a nightmare trying to find this link [below] and other tools)

https://validator.ampproject.org/

**Comment by Gregable** [comment]
The answer to the first question is: no, async is not allowed on external stylesheet tags. I don't know if this should be the case or not, however @cramforce 

Someone else will need to help out with the other two.

**Comment by jridgewell** [comment]
@ayumihamsaki: Opened https://github.com/ampproject/amp-by-example/issues/549 and https://github.com/ampproject/docs/issues/295 for your second and third questions.

**Comment by cramforce** [comment]
Unfortunately `async` on `<link>` isn't a thing yet. AMP actually forces async stylesheets at runtime, when they take longer than 3 seconds. If PageSpeed really means the link tag, it is simply wrong.

Having said that, @Gregable we can start allowing async on link. It is supposed to come to Chrome at some point in the future and certainly doesn't hurt.

**Comment by ayumihamsaki** [comment]
Many thanks for all your replies,...

I think everything is answered now with regards to these three things.

My conclusion to async <link> is to wait until it has been added to the spec, because it is displaying an error in the validator, see here:

![amp2](https://cloud.githubusercontent.com/assets/17784082/22159813/95a6b44e-df3a-11e6-8f42-a90ac753923f.png)

I think I will close this now.

**Comment by cramforce** [comment]
We can actually add it in AMP. It'll be a noop in browsers for now, though.

**Comment by Gregable** [comment]
Yes, we'll add the `async` attribute.

**Comment by Gregable** [comment]
The async attr is allowed, but will take a few weeks until it's released. We will update the issue again at that time.

**Comment by ayumihamsaki** [comment]
@Gregable This works now in the validator you can close this issue now if you like.
