### ISSUE TITLE
amp-facebook not working

### ISSUE THREAD

**Issue by Rashuoo7** [ampproject/amphtml#7109]
I can't find the solution to run this code present here by you [Here](https://github.com/ampproject/amp-by-example/blob/master/src/20_Components/amp-facebook.html) about amp-facebook tag. I found that this code is not working. Please help me find a solution regarding the issue. 
                                                       Thanks!

**Comment by jridgewell** [comment]
We need a page that produces the error to be able to help.

**Comment by camelburrito** [comment]
@Rashuoo7 - you can find good examples here 
https://ampbyexample.com/components/amp-facebook/

Let us know if that helps
