### ISSUE TITLE
Validation page does not mention CSE HTML Validator option

### ISSUE THREAD

**Issue by AlbertWiersch** [ampproject/amphtml#7115]
The validation page here:
https://www.ampproject.org/docs/guides/validate

Does not mention the CSE HTML Validator for Windows (https://www.htmlvalidator.com/) validation option. It would be good to mention that this validation tool is also available to validate and check AMP documents.

**Comment by Gregable** [comment]
Hi @AlbertWiersch

It's great to see more tools supporting AMP Validation. However, I don't see that doc as attempting to enumerate all such interfaces. It exists to provide references to a few such interfaces maintained as part of the AMP open source project.

**Comment by AlbertWiersch** [comment]
Hi @Gregable,

I'm not saying it needs to or even should enumerate everything, but I think it would still be helpful to both AMP developers and to tool creators (like my small software company) to mention CSE HTML Validator somewhere (even though it's not part of the AMP open source project) simply as another option available for checking the quality of AMP pages. I hope you will reconsider.
