### ISSUE TITLE
amp-form submission breaks in several browsers, including Edge 13, 14, IE 11, Safari 10

### ISSUE THREAD

**Issue by przemyslaw-piatek** [ampproject/amphtml#7119]
amp-form submission breaks in several browsers.

## How do we reproduce the issue?
Problem noticed on a private website, nevertheless it also exists on other amp-form powered websites, most prominently in the examples provided by the Project itself:
https://ampbyexample.com/components/amp-form/preview/

1. Submit the form in the bottom of the page.
2. Observe an error being thrown in the console:
```
InvalidStateError
v0.js (314,433)
```

## What browsers are affected?
At least Edge 13, 14, IE 11, Safari 10.
Latest Chrome, Firefox, Opera are not affected.

## Which AMP version is affected?
Never tested before, can't say if it's a new issue.
Version 1484769855829

**Comment by mkhatib** [comment]
This was broken by this change:
https://github.com/ampproject/amphtml/pull/6929/files#diff-4f7d7ef94609d4d079c3fde230f0d924R280


It looks like our `FetchResponse` implementation to polyfill Fetch API might be slightly off. 

Doing response.json() inside the success then block access the `responseText` which throws the `InvalidStateError` - still not sure exactly why.

**Comment by jridgewell** [comment]
Woo, not a prod bug then, just canary.

**Comment by jridgewell** [comment]
I stand corrected. Issue came from https://github.com/ampproject/amphtml/pull/6958, and we're rolling back to the previous prod version.
