### ISSUE TITLE
Default social share icons blocked.

### ISSUE THREAD

**Issue by nhstephan** [ampproject/amphtml#7120]
The default social share icons are blocked by the content-security-policy over https: 

`Refused to load the image 'data:image/svg+xml;charset=utf8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org…%20344.2zM384.4%20307.8l-64.4-64.4%2064.4-49.3V307.8z%22%2F%3E%3C%2Fsvg%3E' because it violates the following Content Security Policy directive: "img-src *".`

**Comment by jridgewell** [comment]
You have to add the `data:` scheme to your CSP:

```
img-src * data:
```

Or, you can set the `default-src`:

```
default-src * data:
```
