### ISSUE TITLE
Unable to test AMP Viewer in Pre-Production

### ISSUE THREAD

**Issue by ryanpoplin** [ampproject/amphtml#7121]
## Short description of your issue:

Currently, there's not way for developers working with Google AMP to test their articles in pre-production within an AMP Viewer. 

## Summary of issue:

Respectfully, this tool (to my current knowledge and please correct me if I am incorrect) is not available to developers: a local testing sandbox for viewing AMP articles pre-production within an AMP Viewer sandbox environment.

With that above statement in mind, here's a link to an issue created by me for AMP which will highlight a core pain point with the tool not being available to us; #7066. We were not able to see a CSS bug in pre-production in the AMP Viewer environment and as a result; this bug manifested in production negatively affecting our design, user experience and business. 

## Specific Questions:
- Are there plans to release such a tool for developers on Google's Developer Roadmap for AMP? 
- If this is not a tool we can expect to gain in the near future, referring to #7066; should we have a process to involve UI/UX validation with Google's AMP team for debugging pre-production?

## Interested Developers:
- @randallbpotter15
- @jpettitt

**Comment by cramforce** [comment]
There is https://search.google.com/search-console/amp

We're looking at extending it to work with non-indexable content.

I'd definitely be in favor of providing a slightly lower fidelity option (not actually the Google Search viewer) that works locally. We actually have something like that in the repo, would just need to polish it up a bit.

**Comment by ryanpoplin** [comment]
Yes, non-indexable content testing on AMP would be fantastic.

**Comment by randallbpotter15** [comment]
@cramforce Non-indexable meaning behind a firewall aka "not publicly accessible?"
That's what we are after.  Our lower environments wouldn't be available without a VPN and we wouldn't spin up a "pseudo-prod."

Our main goal is to have a sandbox viewer option that we can run code against that is an exact 1 to 1 match for the viewer that will be production.  Meaning that all of the styles, re-parenting, layer management would be fully operational in this test viewer.

If it's something we can clone down and run locally that would be ideal.

How soon could we have something like that?

**Comment by cramforce** [comment]
@randallbpotter15 https://search.google.com/search-console/amp will require the file to be on the internet.

@rudygalfi @dvoytenko lets look at making a local viewer available using our demo code.

**Comment by dvoytenko** [comment]
@cramforce Yes, local viewer is possible. To stress though - our current sample viewer is far from full-featured. Testing against a fully-featured, PROD-level viewer would be a lot better.

**Comment by cramforce** [comment]
@dvoytenko I know :)

But tough to mix local resources with production code. The team is looking at a Chrome extensions, but with most bugs being mobile Safari specific that doesn't help much.

Open sourcing much of the viewer code is totally possible, we just won't be able to get that done quickly.

**Comment by markbigault** [comment]
Thanks @cramforce Do you have any kind of timeline you can share on the prod-level viewer (open source or otherwise)?

**Comment by cramforce** [comment]
@markbigault Preview for non-indexable content is coming soon. No timeline yet for viewer that supports non-internet content.

**Comment by rudygalfi** [comment]
We've prepared a guide for testing non-indexable content here: https://developers.google.com/search/docs/guides/debug#testing-firewalled-pages.

Please check it out and let us know any feedback.
