### ISSUE TITLE
"Learn more" link in the AMP Conf banner is hard to click

### ISSUE THREAD

**Issue by dandv** [ampproject/amphtml#7141]
The "Learn more" button in 
![image](https://cloud.githubusercontent.com/assets/33569/22169518/849713d0-df29-11e6-86dd-647e1ce277d7.png) actually contains a link, and the link's clickable area is about 1px vertically.

Chrome 55 on Ubuntu.

**Comment by rosariomg** [comment]
This was fixed by @erwinmombay on https://github.com/ampproject/docs/pull/296
