### ISSUE TITLE
Flexbox align-items breaks amp-image

### ISSUE THREAD

**Issue by jaspersorrio** [ampproject/amphtml#7144]
## Short description of your issue:

Using the css property align-items in a flexbox column breaks the amp-image.
Why is this happening?

## How do we reproduce the issue?

1. Go to https://jsbin.com/kuhatoyoye/edit?html,output
2. Go to section Layout column, Align: center(x) center(y)
3. amp-image disappears.

## What browsers are affected?

Only tested on: 
Mac Safari Version 10.0.1 (12602.2.14.0.7) 
Mac Chrome 55.0.2883.95

## Which AMP version is affected?

I am not sure when was it broken.
Powered by AMP ⚡ HTML – Version 1484769855829 

Edit: I removed all browser prefixes as they didn't affect the results.

**Comment by jpettitt** [comment]
Similar things happen if you float an `amp-img` that is set `layout=responsive`

**Comment by jridgewell** [comment]
@jpettitt: Is this an AMP bug then? Or the @jaspersorrio's CSS?

**Comment by dvoytenko** [comment]
`layout=responsive` is specified to work as this: take the width allocated to the element by the parent and calculate the height in proportion specified by `width:height` attributes. If the parent allocates no space (as with flex and float) then the starting width will be 0 and thus resulting height is also 0. So this is rather how flex CSS works.

There are numerous ways to address this, e.g. using `min-width` or `stretch` justification or `object-fit`.

I'll close this for now, but please feel free to re-open.

**Comment by jridgewell** [comment]
Thanks for the answer @dvoytenko. Would adding the following to our default CSS work for a general case?

```css
[layout="responsive"] {
  width: 100%;
}
```

**Comment by dvoytenko** [comment]
@jridgewell Unfortunately that would override the existing margins and thus almost never what's desired. We do have `layout="flex-item"` and combined with `object-fit: contain` would likely produce the best result. I think it'd make sense for us to automatically add `object-fit: contain` to all `flex-item` images automatically.

**Comment by jpettitt** [comment]
It would be nice if `amp-img`, when set to  `layout=responsive` behaved as if they had intrinsic height/width like real `img` tags do.  (or maybe a new `layout=responsiveimg` since a change like that would be breaking)

**Comment by dvoytenko** [comment]
@jpettitt That would force the resize after the image has loaded which is what we are trying to avoid.
