### ISSUE TITLE
https://ampbyexample.com/components/amp-mustache/  -- 404 PAGE NOT FOUND

### ISSUE THREAD

**Issue by bhansa** [ampproject/amphtml#7149]
[amp-mustache](https://ampbyexample.com/components/amp-mustache/) link is broken 

## What browsers are affected?

All browsers

**Comment by bpaduch** [comment]
Found two references to that link and I've submitted a pull request the docs repo - [PR 300](https://github.com/ampproject/docs/pull/300).
