### ISSUE TITLE
Add integration test for XHR form submission

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#7154]
Or alternatively: Whitelist the XHR unit test (which is really an integration test since it talks to a real server) to also run in our extended browser suite.

Should have detected #7119

@aghassemi Thoughts on extending multi-browser to some unit tests?

**Comment by aghassemi** [comment]
Getting all unit tests pass on all SauceLab environments will be a lot of work but the whitelist approach is sensible and doable. Two things we should do:

1- Whitelist of unit tests that pass on all SauceLab environments.
2- Whitelist of SauceLab environments where all unit tests pass (https://github.com/ampproject/amphtml/issues/6039)

**Comment by cramforce** [comment]
@aghassemi I think we can do

1. Make it so we can have a whitelist
2. Start selectively whitelisting
3. See how things go
4. Switch to blacklist

**Comment by aghassemi** [comment]
sgtm

**Comment by mkhatib** [comment]
So for form itself, would it be enough to write similar unit (really integration) test cases similar to what we did with `test-xhr` itself against our `test-server.js`?

**Comment by mkhatib** [comment]
Chatted with @cramforce we'll be writing tests against `test-server.js` - and whitelist them to run on Safari and mobile. We could potentially change all the current tests to NOT mock the actual fetch-requests and instead hit `test-server.js`

**Comment by cramforce** [comment]
For now we can just add a few (1) specific test file to this glob to get them to run cross browser: https://github.com/ampproject/amphtml/blob/master/build-system/config.js#L59

**Comment by jridgewell** [comment]
Why aren't we using [`sinon.fakeServer`](http://sinonjs.org/docs/#fakeServer)?

**Comment by cramforce** [comment]
The point is to not use it. We want coverage for differences in browser
CORS implementations that would be hidden by faking the communication.
