### ISSUE TITLE
AMP cache is changing the sprite image dimensions

### ISSUE THREAD

**Issue by faelgabriel** [ampproject/amphtml#7158]
AMP cache is changing the sprite image dimensions.
I searched and did not find any related problems, also I did not find any documentation related.

Original image: https://www.reservationcounter.com/application/themes/twig_theme/default/images/global.png

AMP cache image: https://cdn.ampproject.org/i/s/www.reservationcounter.com/application/themes/twig_theme/default/images/global.png

That image is only used as css "background-image" and not in amp-img.

I am aware that our sprite is large and we are working on it, but at the moment I needed to use that image.
Is there any size limit or dimension limit that is causing the cache to change it?

Thanks, Rafael.

**Comment by jridgewell** [comment]
Internally tracking at b/34625483.

**Comment by adelinamart** [comment]
Closing this one and following up internally.

**Comment by Download** [comment]
> Original image
That sprite! Transparent pixels are actually pretty 'expensive' in PNG...

**Comment by adelinamart** [comment]
Thank you for the comment. The issue is still being tracked internally.
