### ISSUE TITLE
AMP HTML Design Flaw

### ISSUE THREAD

**Issue by ayumihamsaki** [ampproject/amphtml#7161]
Hi everyone,

I have a real issue with amp html and want some advice.

I have a PWA website for my Desktop and Tablets Users and I am halfway through building a custom AMP website for my Mobile Users.

Call me old fashioned if you like. But I value User Experience a lot! I really don't think it's a good idea to have a user on a mobile device load your AMP website and then click a link which moves on to your Main website. The reason I think it's a bad idea is that that whole template is different. I want my Mobile Users to stay on the AMP website and not move across to the PWA website at all. I have full trust in PWA and both AMP-HTML projects.

The trouble is I can not do this because of some rules Google has made?!

Below is a screenshot of Google Rules:

![amp-schema](https://cloud.githubusercontent.com/assets/17784082/22220607/39d959fe-e1a7-11e6-9eea-f95e853dd569.png)

Please see Rule 4.

I am using schema.org to mark up both PWA and AMP-HTML and my issue is using JSON-LD "BreadcrumbList" to mark-up my navigation links. If I follow this crazy rule I have to make all my links on my AMP-HTML point to my PWA. Basically I will have this setup for all my links:

AMP Page > PWA > 303 Redirect to New AMP Page

The problem is for every new webpage the user selects they are going to have 2 hops (instead of one). To me this is a design flaw, because I just want this setup:

AMP Page> New AMP Page

With all these extra hops the loading of the New AMP Page will be slowed down and put extra pressure on my server to process all these extra hops.

If anyone from Google is listening can't you change rule 4 to be "Rich Cards Only" and not all schema markup.

Anyway, I would love to hear what the experts here have to say about adding links to an AMP Page. Should we link them to Main Website (in my case PWA) or can I just link AMP to AMP?

Thanks in advance.

**Comment by jridgewell** [comment]
@cramforce or @choumx?

**Comment by cramforce** [comment]
Unfortunately this is really not a good place to ask Google Search specific questions. I have literally no idea what rich cards even are, and I don't think anyone here does. The forum at https://goo.gl/utQ1KZ is a better place.

I think my general advice would be: Do whatever you think makes sense for good UX and try to let the smart robots at Google figure it out. If you want people to stay in the AMP experience, you should definitely link to your AMP pages.

By the way: Have you seen the AMP-PWA support? Might not fit in your case, but might be relevant.

**Comment by ayumihamsaki** [comment]
@cramforce Thanks for your reply and the forum info, do you have a link for the AMP-PWA support. I don't mind doing as much research as possible.

I really wasn't sure where the right place was to ask this question/discussion being so Google specific to AMP, so can I leave you guys to close this issue when the time is right?

~Maybe some more developers might write some suggestions...? I think I will write a post in the Google forum and link it to this issue.

**Comment by cramforce** [comment]
@ayumihamsaki on the AMP and PWA story, check out

- Check out @pbakaus' article https://www.smashingmagazine.com/2016/12/progressive-web-amps/ 
- And our sample code https://github.com/ampproject/amp-publisher-sample/tree/master/amp-pwa

Closing for now, but happy to give more input!
