### ISSUE TITLE
How to specify DFP responsive ad sizes

### ISSUE THREAD

**Issue by bjalford** [ampproject/amphtml#7163]
Trying to find documentation or an example of how to implement an amp-ad component so that it bring in the correct sizes for a given viewport size (728x90 on desktop and small sizes when less than 728px wide (I'm testing AMP across mobile and desktop). Any pointers?

**Comment by jasti** [comment]
@lannka can you add media queries to only trigger a certain amp-ad wxh depending on the device?

**Comment by bjalford** [comment]
Thanks. That worked!
