### ISSUE TITLE
amp-bind can't be enabled as experiment

### ISSUE THREAD

**Issue by sap1ens** [ampproject/amphtml#7166]
## Short description of your issue:

I simply can't run amp-bind extension because I can't enable it as an experiment :-/

## How do we reproduce the issue?

1. Save https://github.com/ampproject/amphtml/blob/master/extensions/amp-bind/0.1/test/validator-amp-bind.html
2. `python -m SimpleHTTPServer`
3. Open http://localhost:8000/validator-amp-bind.html
4. Try to toggle the experiment. You'll see `Uncaught (in promise) Error: Experiment "AMP-BIND" is disabled.​​​` error message in every attempt.

## What browsers are affected?

Only tried Chrome + OS X 

## Which AMP version is affected?

1484769855829

**Comment by choumx** [comment]
Thanks for the report! This was fixed by #7157 and will be available next week.

To workaround, you can use `AMP.toggleExperiment` as described here: https://www.ampproject.org/docs/reference/experimental

**Comment by sap1ens** [comment]
`AMP.toggleExperiment` didn't work either, but after seeing #7157 I know why - I needed to use uppercased name, `AMP-BIND`
