### ISSUE TITLE
Google Search results on Desktop shows AMP pages

### ISSUE THREAD

**Issue by atjegan** [ampproject/amphtml#7174]
Search for a article on Desktop browser, Google results shows shows both AMP and non AMP pages.
No validation error in the AMP Test. It has the canonical tags.

## How do we reproduce the issue?

Affected site:  tamil.boldsky.com

1. Search for "Health benefits of roots and tubers boldsky" or copy paste this URL https://www.google.com/#q=Health+benefits+of+roots+and+tubers+boldsky
 2. The first result is non AMP (desktop) page and the second result is AMP page.

## What browsers are affected?

All Browsers

## Which AMP version is affected?

New Issue. 
Version : https://cdn.ampproject.org/v0.js

**Comment by jridgewell** [comment]
Internally tracked at b/34666647.

**Comment by cramforce** [comment]
Not clear this is a bug (it doesn't currently repro). It is not necessarily undesired to show AMP pages on desktop. It is often temporary, though.
