### ISSUE TITLE
Amp ads served on http/https

### ISSUE THREAD

**Issue by Adverticum** [ampproject/amphtml#7175]
Hello!

We just finished our adserver integration with the amp project a few weeks ago. Our changes went live with the previous week release. 
In our js file that integrates the invocation logic we are calling our invocation helper javascript. 
That call is done by your writeScript method: writeScript(global, 'http://ad.adverticum.net/g3.js');
Now, the method described above is obviously not working if the site that displays the banner uses https instead of http.

So if i use the script likeso: writeScript(global, '//ad.adverticum.net/g3.js'); should it work? Or is there any way to support both http and https sites?

**Comment by nickveenhof** [comment]
If you explicitly make your URL https in your configuration (where the info is being sent to), it should work as expected. xhr https requests from within a http/https page will work. xhr http requests from within a https page will not not work.

**Comment by jridgewell** [comment]
@Adverticum: You should use `writeScript(global, 'https://ad.adverticum.net/g3.js');`
