### ISSUE TITLE
Update amp-form docs to reflect stable status of custom validation

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#7186]
Once new release is out with experiment launched the docs should reflect stable for custom validation. 

Launch PR #7185

**Comment by bpaduch** [comment]
To clarify,"launching an experiment" means that the feature is no longer "experimental"?

**Comment by mkhatib** [comment]
Yes - the PR is merged but most likely would be in prod next week

**Comment by mkhatib** [comment]
Custom validation is launched
