### ISSUE TITLE
JSON addressing and caching in fetch service.

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#7194]
@mkhatib and I were discussing a scheme like that, which may be useful in more places:

1. Change fetch/XHR service to support fragment URLs on JSON GET requests. In particular `https://example.com/service.json#key.subkey` fetches the URL, but then returns `actualJSON.key.subKey` to the caller.
2. Cache (using a TBD strategy) the return value for `https://example.com/service.json` (ignoring the fragment), so that multiple things on the page can be backed by the same JSON request.

- Does this make sense?
- What should the caching strategy be? Options: Cache GET responses for page life time (would sometimes be a memory leak), cache N responses, cache requests with fragment, don't cache, but coalesce requests started within N milliseconds.

CC @choumx @dvoytenko

**Comment by choumx** [comment]
Another option (I mentioned briefly in the meeting) is to split `amp-state` out of `amp-bind` into its own component:

- Currently, an `amp-form` can update the JSON data within an `amp-state` with its XHR response. 
- We add ability for `amp-form` to reference data in `amp-state` and only execute the XHR if that data is missing.
- This differs from `amp-bind` in that `amp-form` won't receive updates if the `amp-state` changes (only pull, no push).

This is similar to "cache GET responses for page lifetime" but avoids introducing a new syntax to reference JSON data. Downside is it requires accessing DOM when there isn't a strict need.

**Comment by dvoytenko** [comment]
It makes sense. But I'd rather have it in a separate service. E.g. `DataSource`, which would use `XHR` service as needed.

**Comment by cramforce** [comment]
@dvoytenko makes sense.

**Comment by cramforce** [comment]
Closing in favor of #7463
