### ISSUE TITLE
Use requestAnimationFrame in vsync

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#7214]
Instead of scheduling a pass every 16ms in vsync, what about use the browser API [window.requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame), and let browser call us on the next paint? 

Potential benefits are:
- Better aligned with browser paint (might slightly improve performance?)
- callback is only executed when the page is visible. So we can simplify some logic in vsync-impl.
- We can track the latency between the request and the callback. If it's bigger than a predefined threshold (say 30ms), then we know the page was janky. We can even setup a counter and make it available to analytics, as a good performance indicator.

window.requestAnimationFrame is quite [well supported](http://caniuse.com/#feat=requestanimationframe) by browsers. 

@cramforce @dvoytenko thoughts?

**Comment by cramforce** [comment]
@lannka I'm slightly puzzled what you are talking about. 

- Are you talking about using rAF in `pass.js`. Do we schedule it at 16ms periods anywhere?
- What is the simplification in vsync you are talking about?
- tracking latency between rAFs works, but we don't schedule them all that often and there are many cases where we care about framerate (scrolling with CSS animation running) where we don't call it. For a while we had `framerate.js` (See history of project) to measure framerate based on rAF, but it uses a lot of battery to call rAF when you have nothing to paint, and so we stopped.

**Comment by jridgewell** [comment]
We already use rAF in `VSync`? Likely, we could cut all the `Pass` stuff out, since it is well supported.

**Comment by lannka** [comment]
Took a closer look at the code, let's forget about the first 2 points.
I did some local experiment with my 3rd point. I will create a separate issue to talk about.

**Comment by dvoytenko** [comment]
`Pass` in vsync is necessary. It's used when rAF stops when page goes to background. Note that we disallow animations in that case, but still allow singular measures and mutates.
