### ISSUE TITLE
amp-form on=submit event not firing

### ISSUE THREAD

**Issue by JakePou** [ampproject/amphtml#7245]
Without any changes to the client side code, this started happening on 1/27/2017.

submit-success -> fires
submit-error -> fires
submit -> does NOT fire,

Code:
`<form method="post" action-xhr="https://www.roboform.com/filling-test-all-fields" target="_top" on="submit:success-lightbox;submit-success:success-lightbox.close;">...</form>`

**Comment by camelburrito** [comment]
@mkhatib This seems to be happening from the last release - could you take a look now may be we need to cherrypick/rollback

**Comment by jridgewell** [comment]
Ping

**Comment by mkhatib** [comment]
Hey @JakePou this won't be in production until couple weeks - it'll be in canary this week.

**Comment by JakePou** [comment]
ahh i see @mkhatib - thank you for the clarification.
