### ISSUE TITLE
Cross site caching for AMP components?

### ISSUE THREAD

**Issue by thomaskuntzz** [ampproject/amphtml#7248]
Hi, this is mainly a question and I hope it's the right place to post it. The other places mentioned in the issue template didn't seem appropriate...

I'm wondering if there is any caching mechanism for the AMP components – I mainly think of the scripts used across many if not all AMP pages – that allows not to download the AMP scripts AMP pages use every time a user visits one.

So my two main questions are : Is there anything of this sort? Why?

Sorry if I posted at the wrong place, just tell me where I can get an answer...

**Comment by cramforce** [comment]
I don't fully understand the question. The component implementation
JavaScript files are certainly cached between site visits. That is an
important part of AMP. If the Washington Post, the NY Times, Buzzfee, and
my blog all have an amp-carousel, they all use the exact same JS downloaded
from the same URL.

**Comment by thomaskuntzz** [comment]
Okay, my question was maybe stupid, but it was in this case : Will "the exact same JS" be downloaded for each site or is it cached and reused? 

Maybe this has nothing to do with the AMP Project – if so I'm sorry for having posted here – and the caching is handled by the browser, but I don't know and I couldn't find out so that's why I'm asking here...

**Comment by cramforce** [comment]
Ok, yeah, I think that the thing you were asking for is exactly what is
happening :)

Not a stupid question, but rather a question worthy of a blog post!
