### ISSUE TITLE
Blank page after browser history manipulations

### ISSUE THREAD

**Issue by Jeiwan** [ampproject/amphtml#7250]
Browser history manipulations (back, forward, page refresh) result in a blank AMP page.

## Case 1:
1. Go to google.com (or g.co/ampdemo) on a mobile device
2. Search "Trump"
3. Open any AMP enabled link
4. After the page is loaded, press Back in the browser
5. Press Forward to see a blank page.

## Case 2:
1. Go to google.com (or g.co/ampdemo) on a mobile device
2. Search "urbandictionary fleek"
3. Open a related AMP page from the results
4. After the page is loaded, press Refresh in the browser
5. Correct page content will be shown for a moment, then it disappears.

(Browser history clearing might be required to reproduce the bug)

Here's a video demonstrating the bug: https://cl.ly/400O1y2X1g0r

Also, Case 1 is reproducible in the desktop Chrome after enabling the Device Mode. Case 2 only appears on UrbanDictionary, maybe because of iframes. Also, after refreshing a page, if you wait for a couple of seconds, the page content will appear for a moment and then disappear.

## What browsers are affected?

Mobile Chrome 55.0.2883.79 (iOS)
Mobile Firefox 6.0 (iOS)
Mobile Safari (latest version)
Desktop Chrome 55.0.2883.95 (in the Device Mode)

## Which AMP version is affected?

Version 1485231782273, but the bug is not likely to be caused by the AMP code.

**Comment by muxin** [comment]
@Jeiwan Thanks for reporting this! This bug is tracked internally b/33049693 and is being fixed.

**Comment by jridgewell** [comment]
Should be fixed now, rolling out shortly.
