### ISSUE TITLE
Ability to quickly jump to live page

### ISSUE THREAD

**Issue by epheterson** [ampproject/amphtml#7251]
I noticed AMP links appearing in my results and, while it's nice to have a cached version load quickly, sometimes I want the actual link. 

Unfortunately, there is no easy way to get the actual link of the cached content. The only way is removing google.com/amp from the URL. 

Please implement some way to load the original link, for example by tapping the existing domain header on cached pages which currently has no action.

**Comment by jridgewell** [comment]
Duplicate of https://github.com/ampproject/amphtml/issues/6210.

Short answer: This has to do with Google's implementation of AMP in Search, not AMP itself. They're actively working on providing a way to get the canonical link.

**Comment by epheterson** [comment]
Thanks for the dupe, glad to hear they're working on it.
