### ISSUE TITLE
Intent to Implement: Swoop support for amp-ad

### ISSUE THREAD

**Issue by mbell697** [ampproject/amphtml#7253]
We'd like to provide support for swoop via the `amp-ad` tag, more on swoop here: https://www.swoop.com/

Fork: https://github.com/swoop-inc/amphtml branch will be `mb_swoop_integration`

**Comment by lannka** [comment]
That's great. And make sure you read the [help doc](https://github.com/ampproject/amphtml/blob/master/ads/README.md#developer-guidelines-for-a-pull-request).
