### ISSUE TITLE
Intent to implement: SlimCut Media ad network into amp-ad

### ISSUE THREAD

**Issue by m1ck43l** [ampproject/amphtml#7254]
I intent to implement SlimCut Media ads support into amp-ad. We have already signed the corporate CLA as SlimCut Media.

I will open the PR right after we have the code working locally.

Mickael

**Comment by lannka** [comment]
That's great. And make sure you read the [help doc](https://github.com/ampproject/amphtml/blob/master/ads/README.md#developer-guidelines-for-a-pull-request).

**Comment by adelinamart** [comment]
Is this fixed by the PR?
@m1ck43l for closing issues might be useful to use https://help.github.com/articles/closing-issues-via-commit-messages/
