### ISSUE TITLE
Improve amp-bind debuggability

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#7257]
- [x] Report syntax/expression errors through `error.js#reportError`.
- [x] Add fine-level logging for state and component updates, etc.
- [x] Output warning for undefined variables, improve error message specificity

Related to #6199.

/cc @kul3r4

**Comment by cramforce** [comment]
Is this currently integrated with "element level" exceptions that highlight elements that have a problem. E.g. if an expression associated with them has an exception?

**Comment by choumx** [comment]
Hmm, not sure which exceptions you're referring to.

Currently, on page load:
- `user().error` on expression parse failure or invalid binding
- If dev mode, user().error when initial state != expression result

TODO: 
- If `#log=4`, `dev().fine` on data flow steps to aid in bug reporting

**Comment by cramforce** [comment]
I meant this code pass: https://github.com/ampproject/amphtml/blob/master/src/error.js#L104

**Comment by choumx** [comment]
Ah, no it doesn't; added to list above. Thanks for the reference.

**Comment by kul3r4** [comment]
@choumx What is the solution for developer when debugging amp-bind variables?

**Comment by cramforce** [comment]
Would be great to have a way to dump the global state in the console. We could then later wrap it in a Chrome DevTools Extension.

**Comment by choumx** [comment]
@kul3r4 You can create elements with `[text]` bindings to the expression you want to debug, e.g.
```
<p [text]="myState.foo + 123">Debug here</p>
```
I think that may be more convenient than repeatedly running "print expression" commands in dev console. Let me know if that doesn't work for you.

@cramforce Good idea, will track this in the next sprint.

**Comment by kul3r4** [comment]
I understand I can use `[text]` bindings but this requires to redeploy a new version of the page just for debugging. I think it would be good to have a way to dump the global state in the console.
