### ISSUE TITLE
Where are creative agencies supposed to reach out regarding the amp ads exactly?

### ISSUE THREAD

**Issue by kitsunde** [ampproject/amphtml#7261]
On https://github.com/ampproject/amphtml/blob/master/ads/google/a4a/docs/a4a-readme.md it says:

> If you are a creative agency, please reach out to us via Github so we can put you in touch with publishers and advertisers who are interested in developing AMP ads.

Is the expectation here for each agency to create a GitHub issue?

**Comment by jridgewell** [comment]
> Is the expectation here for each agency to create a GitHub issue?

Yup.

/cc @jasti, @lannka

**Comment by jasti** [comment]
@kitsunde, it's really just a way to gather interest. Are you from a creative agency? Are you interested in creating AMP ads?

**Comment by kitsunde** [comment]
@jasti I'm the CTO of a digital agency and our main work is supporting creative agencies here in Singapore. AMP ads is definitely something we're interested in exploring, either directly or together with one of our partners.

**Comment by jasti** [comment]
@kitsunde Could you please express interest in this form and we will reach out to you with more information. Thanks!
https://goo.gl/forms/P2zpQT3aIEU1UsWj2

**Comment by jasti** [comment]
Closing in favor of https://github.com/ampproject/amphtml/pull/7687
