### ISSUE TITLE
Teads implementation doubts

### ISSUE THREAD

**Issue by gilbermudez** [ampproject/amphtml#7266]
Hi everybody.

We are trying to implement Teads in our post contents but we are having an error appearing in Google developer tool:

- GET https://a.teads.tv/page/"ID"/tag .......................  3p.js:100

The  ID that we are using is the same as the one we have in our normal site.

Is necessary that the tag needs a unique ID or we can use the ID of our normal site?

<amp-ad width=300 height=1 type="teads" data-pid="ID" layout="responsive"></amp-ad>

This is the example that exists in the documentation.
Exists another parameter or thats it?

Greeting. Thanks

**Comment by jpettitt** [comment]
FWIW we have teads running on multiple customer sites and in each case we got an AMP specific ID from them.

**Comment by gilbermudez** [comment]
Can you share us a link of AMP page with teads ?

**Comment by jpettitt** [comment]
It's on all Miami Herald and all Daily Dot AMP pages amoungst others https://miamiherald.relaymedia.com/amp/news/local/community/miami-dade/article129759604.html

**Comment by jridgewell** [comment]
Closing with https://github.com/ampproject/amphtml/issues/7266#issuecomment-276468389.
