### ISSUE TITLE
Origin is null in the request headers for amp-iframe

### ISSUE THREAD

**Issue by beastafk** [ampproject/amphtml#7269]
As stated here: [https://github.com/ampproject/amphtml/blob/master/spec/amp-cors-requests.md#cors-security-in-amp](https://github.com/ampproject/amphtml/blob/master/spec/amp-cors-requests.md#cors-security-in-amp), when CORS is used, the response should include the _AMP-Access-Control-Allow-Source-Origin_ header. The problem is that the request header Origin is always null.

In the page that will be loaded with the **amp-iframe** component I have:
```
xmlhttp = new XMLHttpRequest();
xmlhttp.withCredentials = true;
xmlhttp.open("POST", url, true);
xmlhttp.onreadystatechange = function() { ... };
xmlhttp.send();
```
Then every time that a request is sent from the amp page, the Origin is **null**. My idea was to submit it manually like this:

```
xmlhttp.setRequestHeader('Access-Control-Allow-Origin', 'my-origin');
```

It also didn't work. This makes it difficult to return the correct response, as the browser returns this error:
```
The 'Access-Control-Allow-Origin' header has a value 'whatever-I-have-put-here' that is not equal to the supplied origin. Origin 'null' is therefore not allowed access.
```

The _AMP-Same-Origin_ is also never set. That's why I assume it's a bug as the validation of AMP page is otherwise successful. Also if normal iframe element is used (just for test), the origin is set correctly.

## What browsers are affected?

This happens both with Chromium (55.0) and FF (50.1).

## Which AMP version is affected?

amp-version="1485231782273"

**Comment by jridgewell** [comment]
You shouldn't need CORS inside your own iframe? It's only necessary when you're sending non-GET requests from the AMP document to your site, not from your own iframe (on your site) to your own site.

Additionally, the `Access-Control-Allow-Origin` is a response header, not a request header.

Finally, are you using a `srcdoc`? If so, you can't have an origin (we make sure it's `null`), so that's why you keep getting it.

**Comment by beastafk** [comment]
Seem like you didn't understand me or I didn't write it clear enough. I am sending a non-GET request from the AMP document to my site. The request happens by clicking on a button, which is loaded with the amp-iframe component. And I am not using the `srcdoc`.

To make things clear, here is the AMP document

```
///https://my-url-here/amp-page

......
<amp-iframe 
        width=375 
        height=60
        sandbox="allow-scripts"
        allowfullscreen
        layout="responsive"
        frameborder="0"
        src="https://my-url-here/page-to-be-included-with-iframe">
</amp-iframe>
```

and this is the page I want to include with **amp-iframe**

````
//https://my-url-here/page-to-be-included-with-iframe


someButton.addEventListener("click", function () {
.....
xmlhttp = new XMLHttpRequest();
xmlhttp.withCredentials = true;
xmlhttp.open("POST", url, true);
xmlhttp.onreadystatechange = function() { ... };
xmlhttp.send();
````

Clicking on the button in the iframe from the AMP-Document, results in an error in the console (error is mentioned in the first post). The reason is that Origin is always **null**  on this POST request.

**Comment by lannka** [comment]
i guess the problem is the `sandbox` attribute? Does it work when you remove it?

**Comment by jridgewell** [comment]
I've done my own testing using your posted code, and everything works as expected. Can you put up a live page where we can test?

**Comment by beastafk** [comment]
I cannot really provide a live page for testing, and removing the `sandbox` attribute breaks the functionality of the amp-iframe. 

For me it's also inconvenient to create new domain for my AMP page, so I am using the same one.

So in my case I am using the same same domain [domain-x] for everything:

- serving the AMP page [domain-x/amp/....]
- `amp-iframe` has the src=[domain-x/iframe-page] for page on the same domain
- Clicking a button in the iframe creates XHR request towards the same domain [domain-x/here-goest-the-request]

I want to make use of the cookies associated with this domain. At the moment a workaround is instead of making a XHR request, to use a `<form>` inside the frame and on submit to refresh the whole page in the frame.

**Comment by jridgewell** [comment]
> For me it's also inconvenient to create new domain for my AMP page, so I am using the same one.

Ahh, that's what I needed. Posting to your own origin in an iframe that disables "allow-same-origin" (through its omission from `sandbox`) will cause the iframe's origin to be "null".

To support this kind of pattern, you need to specifically allow a null origin in the response headers:

```text
Access-Control-Allow-Origin: null
