### ISSUE TITLE
Implement Media Session API for video-interface

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#7272]
Chrome 57 is releasing the [Media Session API](https://developers.google.com/web/updates/2017/02/media-session) which allows customization of the media notifications. 

We should implement this API for any player than implements the video-interface.

![](https://developers.google.com/web/updates/images/2017/02/tldr.png)

Few Notes:
- [x] We should make `artwork` and `title` configurable but we can also provide **reasonable defaults**: (p1)
  - [x] `artwork` can default to `poster`
  - [x] `title` can default to one of `title`, `aria-label`, `aria-describedby`. YouTube and other platforms might have APIs to get the `title` as well.
- [ ] Lightbox 2.0 work discovers different elements (including media) in the page, we can implement the (p3) `album` feature ( e.g. `next`, `previous` based on the same functionality )
- [ ] We can do `seek` after we add `seek` to `video-interface` (p3)

/cc @dvoytenko (Thanks for sending the link) @rudygalfi @ericlindley-g

**Comment by dvoytenko** [comment]
👍 . A lot of video-playlists (sports, music) fit here very well.

**Comment by aghassemi** [comment]
5

**Comment by dvoytenko** [comment]
I think this is the part of demo I missed the last time. Can I see it?
