### ISSUE TITLE
Detect swipe and trigger click

### ISSUE THREAD

**Issue by bjalford** [ampproject/amphtml#7284]
Is it possible to detect swipe action and use that to trigger a link click to trigger a new page load? 

I've also seen this which is specifically about next/previous page functionality  but was wondering if this isn't implemented whether a custom version could be built using just the swipe: https://github.com/ampproject/amphtml/issues/655

**Comment by jridgewell** [comment]
> Is it possible to detect swipe action and use that to trigger a link click to trigger a new page load?

No it's not possible.

> I've also seen this which is specifically about next/previous page functionality but was wondering if this isn't implemented whether a custom version could be built using just the swipe: #655

This seems like it could be a feature of the next/prev button component. Let's move the discussion to #655.
