### ISSUE TITLE
Validator forbids relative amp-user-notification hrefs

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#7289]
Example: https://validator.ampproject.org/#url=https%3A%2F%2Foutput.jsbin.com%2Fnibomo%2Fquiet

```html
<amp-user-notification data-dismiss-href="/setcookielaw" data-show-if-href="/cookielaw?timestamp=TIMESTAMP" id="amp-user-cookie" layout=nodisplay>
</amp-user-notification>
```

**Comment by Gregable** [comment]
I think this is intentional. The AMP cache doesn't rewrite these, so they are broken if absolute.

**Comment by Gregable** [comment]
For example: https://github.com/ampproject/amphtml/blob/master/extensions/amp-user-notification/0.1/validator-amp-user-notification.protoascii#L70

**Comment by jridgewell** [comment]
Whoops, this was the whole point of #4537. 🤦‍♂️
