### ISSUE TITLE
Consider renaming goToSlide event to slidechanged

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#7298]
[`goToSlide` event](https://github.com/ampproject/amphtml/blob/master/spec/amp-actions-and-events.md#element-specific-events) is confusing and sounds like an action rather than an event. Adds to the confusion is that there's also an action called `goToSlide`.

**Comment by camelburrito** [comment]
This is a bind event - it is named to match goToSlide action on amp-slides - also this should say that this is specific to type="slides"

**Comment by choumx** [comment]
Fixed by #7387.
