### ISSUE TITLE
Adsense link ad not working in AMP mode?

### ISSUE THREAD

**Issue by evivz** [ampproject/amphtml#7326]
When I put adsense link ad unit id in ad it still shows up as normal ad not as link ad.

**Comment by jasti** [comment]
Link ads are not supported in AMP at the moment. The feedback has already been passed along to the team and they are working on it, but feel free to also reach Adsense via your support channels and ask for support.

Thanks.

**Comment by YomeshAdPushup** [comment]
@jridgewell  @jasti Hello, Does AMP support Link ad units now? 
I couldn't find any reference in AMP documentation or anything concrete on web around this.

**Comment by jasti** [comment]
I've pinged the AdSense team again about it. It might be best to reach out in your usual AdSense support channels to request this feature as well.
