### ISSUE TITLE
amp-bind console error

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#7329]
After the latest canary release (1486066183733), [amp-bind sample](https://ampbyexample.com/components/amp-bind/preview/) gives the following error:
chunk.js:351 Uncaught (in promise) TypeError: Cannot read property 'enqueue' of undefined
    at lb (chunk.js:351)
    at jb (chunk.js:331)
    at chunk.js:72
    at Tb (bind-impl.js:188)
    at Rb (bind-impl.js:137)
    at bind-impl.js:101

@choumx @ericlindley-g

**Comment by choumx** [comment]
Can't repro this on current canary 1486153081489. Please reopen if you still see this.

**Comment by choumx** [comment]
Seeing this on canary 1486166232176.

**Comment by choumx** [comment]
This is caused by the `Chunks` service being installed twice and only appears on min builds.
