### ISSUE TITLE
optout property is only available to vendor config. pd @ error.js:113 - Google Analytics / GTM

### ISSUE THREAD

**Issue by Polylike** [ampproject/amphtml#7330]
Hello,

since today Google Analytics (via GTM) tracking nothing and no changes made on my AMP site!?!

I take o look to the console and there are a new message:

optout property is only available to vendor config.
pd @ error.js:113

Website:
https://goo.gl/8LA2lx

Bug or how can i handle this?

Best,
Daniel

**Comment by killerbishop** [comment]
We are experiencing this issue as well.

**Comment by jridgewell** [comment]
Fixed by #7318. We're working on getting this fix out.
