### ISSUE TITLE
How the amp-access metering work in Private Window(Incognito)?

### ISSUE THREAD

**Issue by jalajc** [ampproject/amphtml#7332]
While implementing metering with amp-access: I found that since RID (amp-access id) is different in private window (Incognito), I am not able to contain the page views within limit maxView limits (RID being the only reliable parameter).

- Is there a signal for private window that can be used to control access?
- If not 
 -- request to add feature to know if page is in private window or 
 -- may be amphtml doc itself restricts with a message like "this page is access controlled, you cannot view in private window" or sort

**Comment by jridgewell** [comment]
The problem is there's no way to tell the difference between a first time user and a private browser. Even if we could, it'd be a privacy violation.

> Is there a signal for private window that can be used to control access?

The only reliable way is to have the user log in. That way, you're able to always tell who the user is and how many times they've viewed the site.
