### ISSUE TITLE
update SERVING.MD

### ISSUE THREAD

**Issue by dknecht** [ampproject/amphtml#7336]
Ensure SERVING.MD is up to date. 

> "you're right, ill update it and probably update prepend-global. do you mind filing an issue for that for me?" @erwinmombay

**Comment by dknecht** [comment]
@erwinmombay ping

**Comment by erwinmombay** [comment]
sorry, amp-conf got in the way there. will look into it in next sprint. adding to prioritized FR milestone.

**Comment by rsimha-amp** [comment]
Let's make sure `SERVING.md` is updated once more.

**Comment by rsimha** [comment]
This is being tracked by #22384
