### ISSUE TITLE
Carousel doesn't fire goToSlide event when users change slide with the goToSlide action

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#7337]
This could be an intended behavior but thought I'd start a discussion. 

Basically, `goToSlide` event is only fired when users explicitly change the slide by interacting with the slides themselves (clicking next/prev button, or swiping left/right).

The event is not fired in `autoplay` changes or slide change through the `goToSlide` action. 

It's worth mentioning firing the event in response to `goToSlide` action might cause a recursive infinite loop if not properly handled or caught by the action-impl. This is [relevant to the discussion on this PR](https://github.com/ampproject/amphtml/pull/7278#issuecomment-276741339).

**Comment by dvoytenko** [comment]
Bumping to P1. PTAL as soon as possible.

**Comment by camelburrito** [comment]
@mkhatib  what do you mean by `goToSlide` event? is it a bind event? (I am not aware of any such events apart from an action)

**Comment by mkhatib** [comment]
Here's some guidelines because this is a bit confusing:

* When I refer to `goToSlide` action - I refer to `this.registerAction('goToSlide')` - which is what users can use in the action clause of the on-syntax like: `on=tap:**slides.goToSlide**`.

* When I refer to `goToSlide` event - I refer to `this.action_.trigger` call inside `showSlideAndTriggerAction_` - which is what users can use in the event-clause of the on-syntax like: `on=**goToSlide**:otherTarget.hide`.

AFAIK the `goToSlide` event was introduced for `amp-bind` but this can still be used through the on-syntax. I'll stick to discussing it through the on-syntax but everything should apply similarly to bind I believe.

Does this make sense? 

The `registerAction('goToSlide')` handler calls `showSlide_` directly which does not fire the `goToSlide` event (again firing it here need to be carefully planned to avoid recursiveness).

**Comment by camelburrito** [comment]
@choumx do you have some time to look at this ?

**Comment by choumx** [comment]
In my opinion this is WAI but agree that it can be confusing. Perhaps the event and action shouldn't have the same name. Is it too late to change this?

**Comment by mkhatib** [comment]
Changing the naming I think is a good start, but doesn't address the inconsistencies of **when** the event is fired and might cause some use-cases to not work-as-expected.

**Comment by camelburrito** [comment]
if bind in experimental we should change the name now
