### ISSUE TITLE
Does data-iframe-src on Serviceworkers need validation? 

### ISSUE THREAD

**Issue by dknecht** [ampproject/amphtml#7338]
It doesn't look like it is currently validated.

**Comment by honeybadgerdontcare** [comment]
The validator automatically allows any `data-` attribute. It is possible to add additional restrictions if necessary. See [amp-youtube](https://github.com/ampproject/amphtml/blob/master/extensions/amp-youtube/0.1/validator-amp-youtube.protoascii#L62) as an example.

**Comment by Gregable** [comment]
@dknecht , is there anything more that we need to do here? Validation just blanket whitelists all attributes starting with `data-` as @honeybadgerdontcare mentions, so even though it's not listed in the rules, it's still valid.

**Comment by Gregable** [comment]
Let's add validation for it, same rules as src (except optional of course)

**Comment by honeybadgerdontcare** [comment]
Addressed in #7590
