### ISSUE TITLE
Intent to implement: Call tracking in AMP

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#7340]
Call tracking allows advertisers to track phone calls originated from phone numbers displayed on their pages. This project aims to make call tracking available to AMP pages.

Design https://docs.google.com/document/d/1UDMYv0f2R9CvMUSBQhxjtkSnC4984t9dJeqwm_8WiAM/edit?usp=sharing

For feature request see #5276

**Comment by rudygalfi** [comment]
Is this waiting on anything or is it fully released? If fully released, then the documentation page should be updated to stable (currently says in development).

**Comment by alanorozco** [comment]
@rudygalfi Not yet released. Will update once that happens.

**Comment by erwinmombay** [comment]
@alanorozco make sure @aghassemi gets your PR fix in

**Comment by aghassemi** [comment]
@alanorozco @erwinmombay Saw it merged. Will make it to Canary
