### ISSUE TITLE
Cache validator doesn't support IPv6 URLs

### ISSUE THREAD

**Issue by dknecht** [ampproject/amphtml#7350]
This will fail the cache validator:
`<a href="https://[2001:0db8:85a3]/">IPv6 URL</a>
`

**Comment by Gregable** [comment]
Thanks for the report.

**Comment by Gregable** [comment]
I _think_ that the cache is actually correct here and javascript needs to be more strict. Specifically, there are not enough bits here. Note that the cache does accept `<a href="https://[2001:0db8::85a3]/">IPv6 URL</a>`. Note the `::` collapsing syntax. My browser (chrome) seems to agree, treating `https://[2001:0db8:85a3]/` as a query and `https://[2001:0db8::85a3]/` as an URL.

**Comment by Gregable** [comment]
Closing, this change is live everywhere.
