### ISSUE TITLE
Generify Cloudflare ad-network implementation

### ISSUE THREAD

**Issue by oliy** [ampproject/amphtml#7351]
This is an intent to implement:

To reduce the burden of ad-networks in integrating a4a, we want to expand the cloudflare ad-network implementation to serve as a base reusable implementation.  The cloudflare implementation will still handle signature extraction and aid in passing contextual information to the ad server.

**Comment by dknecht** [comment]
Why was this labeled a P3?

**Comment by jasti** [comment]
Updated.
