### ISSUE TITLE
Wrap stack entry points for error reporting

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#7353]
Due to https://blog.sentry.io/2016/05/17/what-is-script-error.html we get bad error reports in many cases.

While we will do the CORS based workaround, but that does not work in Safari. 

For Safari we would need to do stack entry point instrumentation to be able to use try-catch. In particular for Promises this would, however, be really slow.

**Comment by cramforce** [comment]
See b/35002808 tracking CORS changes.

**Comment by dknecht** [comment]
Cc: @ampproject/cloudflare 
We will need to update also.

**Comment by dknecht** [comment]
@cramforce will this require cache level CORS changes

**Comment by cramforce** [comment]
@dknecht yeah, 2 things

1. Serve CORS response header with `*` in JS responses
2. Insert `crossorigin` attribute into script tags on document responses (to trigger CORS request). The value can be either `anonymous` or `with-credentials` (or whatever that value is). We need to use the latter to be able to support cookie based dev channel opt-in.

**Comment by cramforce** [comment]
@dknecht This will be needed for #7566

**Comment by cramforce** [comment]
Change on Google's JS delivery side rolled out.

**Comment by cramforce** [comment]
Calling this done
