### ISSUE TITLE
Make viewport getScrollLeft return 0 instead of accessing dom

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#7355]
Since we don't allow scroll horizontally on the document by setting `overflow-x: hidden` on `html` and `#i-amphtml-wrapper`, the `viewport.getScrollLeft()` in different viewport binding will always return `0`.

I see we are using `viewport.getScrollLeft` only in [analytics](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/instrumentation.js#L260) and [here](https://github.com/ampproject/amphtml/blob/master/src/service/resource.js#L389). It's basically useless and always returns 0. We could either remove the method or simply return 0 without accessing the dom.

To minimize the change, I suggest we always return 0 in `viewport.getScrollLeft`

@dvoytenko @jridgewell

**Comment by dvoytenko** [comment]
We need to check if this is ever possible in-a-box cases. And we also need to check on pinch-zoom cases which we explicitly allow.

**Comment by muxin** [comment]
According to @lannka the content is not scrollable in in-a-box case, so the scrollLeft should be 0 as well.
Is the pinch-zoom in ios only or android too? I tried to zoom in viewer in ios and it's totally broken (The page layout is ). Even in zoom case we still have `overflow-x: hidden` so it has `0` scrollLeft anyway.

**Comment by dvoytenko** [comment]
Pinch-zoom is available in both Android and iOS. Could you please clarify what you mean by broken?

If scrollLeft is 0 - we can go ahead and set it as a const.

**Comment by muxin** [comment]
I couldn't zoom in android. In ios 10, just open any search viewer, after trying zooming in and swiping left and right, the page would be totally broken.

![img_9142](https://cloud.githubusercontent.com/assets/3897214/22710020/a72c536e-ed30-11e6-8227-28b1f0d9b8d2.PNG)


But even in that case, the `scrollLeft` is still `0`.

**Comment by dvoytenko** [comment]
You are trying to zoom Google Search, which doesn't allow you to do that at this point, which is up to each app. Please try directly on a unembedded AMP page. I.e. open cdn.ampproject.org/... page directly.

**Comment by muxin** [comment]
Tested in unembedded amp page, the scrollLeft is always 0. I'll go ahead and return constant, PR coming.
