### ISSUE TITLE
Implement stable livestream URLs in amp-youtube

### ISSUE THREAD

**Issue by csculley** [ampproject/amphtml#7357]
While it is possible to use youtube.com/live_stream?channel=channel-id/ with amp-youtube, this URL will only display live events, and not scheduled streams. This means that going to the URL could display "stream offline" while a scheduled stream was playing on that channel.

However, there is also youtube.com/c/channel-name/live, which should go to both scheduled streams or live events, or just the user's videos if there is no current stream, but there's no way to implement that into amp-youtube.

Sorry if this is the wrong place to post this.

**Comment by aghassemi** [comment]
@csculley From what I can find, YouTube Live Videos get their own `VideoId` (https://www.youtube.com/watch?v=s8SwlaqDrdM) which should be embedable via `amp-youtube`. Is what you have in mind a different case @csculley ?

**Comment by aghassemi** [comment]
@csculley please see previous comment. Closing the issue, please feel free to reopen if previous answer is not satisfactory.

**Comment by aghassemi** [comment]
Verified this works: https://codepen.io/aghassemi/pen/PJrpvd?editors=1000

**Comment by csculley** [comment]
Yeah, what I was looking for would have to be implemented by youtube itself. Thanks anyways!

**Comment by abazeed** [comment]
Hello @aghassemi, I'm trying to use the static live streaming URL of our youtube channel with amp-youtube, but it is not working.
I've tried to use it with the following formats, but none has worked:

* youtube.com/live_stream?channel=UCqFCFEIqqh35HXvkl58CERw
* live_stream?channel=UCqFCFEIqqh35HXvkl58CERw
* alaantube/live

I know that I can use the video id, but it keeps changing from time to time.
Now we are using the amp-iframe, but the autoplay option is not working even if you pass it as a parameter in the URL `autoplay=1`.

Is it currently possible to use amp-youtube with live stream static URLs or not? and if not, is it planned to?

**Comment by abazeed** [comment]
One more note that could help:

When I set the video id to `live_stream?channel=UCqFCFEIqqh35HXvkl58CERw`, the generated iframe URL inside the amp-youtube tag was:

`https://www.youtube.com/embed/live_stream%3Fchannel%3DUCqFCFEIqqh35HXvkl58CERw?enablejsapi=1&playsinline=1&iv_load_policy=3`

There are 2 problems with this URL:
* Escaping the unsafe characters of `?` and `=` to be `%3F` and `%3D`
* Having 2 question marks `?` here:
  * One in the provided URL `live_stream?...`
  * And one before the parameters that amp added after the provided URL `?enablejsapi=1...`

See:
`https://www.youtube.com/embed/live_stream`__`%3F`__`channel`__`%3D`__`UCqFCFEIqqh35HXvkl58CERw`__`?`__`enablejsapi=1&playsinline=1&iv_load_policy=3`

This URL could work if:
* You disabled escaping unsafe characters
* You or the user added an `&` after the provided URL to overcome the problem of duplicated `?`

The final URL will be something like this:

`https://www.youtube.com/embed/live_stream`__`?`__`channel`__`=`__`UCqFCFEIqqh35HXvkl58CERw`__`&?`__`enablejsapi=1&playsinline=1&iv_load_policy=3`

**Comment by aghassemi** [comment]
@abazeed you are right livestream channels is not supported yet. Reopening the issue.

regarding autoplay with `iframe`, YT does not support it natively yet on mobile, only AMP does.

**Comment by csculley** [comment]
@abazeed As a side note, I was implementing static live stream values before this change with `data-videoid="live_stream" data-param-channel="channelid"`

The original issue I had with youtube (which I mistakenly opened as an issue with AMP) is that while one can go to [(https://www.youtube.com/embed/live_stream?channel=UCzZe-zMu-YgVFQfDmsFG_VQ)](this live_stream?channel="" link], the link will show the live stream as "offline", even though the[https://www.youtube.com/channel/UCzZe-zMu-YgVFQfDmsFG_VQ](channel page) shows a current livestream. This is because youtube separates their "stream now" livestreams, and their scheduled streams into two different systems. I've asked [https://www.reddit.com/r/youtubegaming/comments/79xzt8/youtube_live_improvements_making_live_events_even/dpllmbg/](on Reddit), and they seem to be planning on merging these two systems together in the future, although I'm not sure on the timeline of this happening.

I'm glad my mistaken issue led to a beneficial change!
