### ISSUE TITLE
Intent to implement: Time ago component

### ISSUE THREAD

**Issue by bjalford** [ampproject/amphtml#7364]
We're (Bright Sites) keen to get involved in contributing to the AMP project. A component that would be useful for sites we work on (The Independent, Evening Standard) is one that displays a time and date as "time ago".

One option could be to implement the moment js script (https://momentjs.com/) It's slightly heavy in size. What are your views?

**Comment by rudygalfi** [comment]
cc @cramforce for feedback

**Comment by cramforce** [comment]
So, …, I think that this would be great in general. We have largely avoided i18n baked into AMP components, so it would be not completely clear how that would be done here.

Moment.js would definitely be a pretty big gun for this specialized use case. What does it weigh in at?

**Comment by bjalford** [comment]
Just over 20k - 60k with locales. We think that we will do something custom that fits the exact use case.

**Comment by cramforce** [comment]
SG @bjalford how do you handle i18n?

**Comment by bjalford** [comment]
This has now been committed to master.
