### ISSUE TITLE
AMP accordian

### ISSUE THREAD

**Issue by pooja1016** [ampproject/amphtml#7365]
1. If we have more than one accordion in a page if i click on first section of the first accordion then if i refresh that page it will open all accordion's first section

2. Same thing if i close the second accordion's second section then if i refresh the page it will close all the second section accordion's

**Comment by camelburrito** [comment]
@pooja1016 please paste a url (or a jsbin) to help debug

CC @zhouyx

**Comment by pooja1016** [comment]
https://ampbyexample.com/components/amp-accordion/

1. Open this example provided by you only
2. Click on 1st accordion second section and then refresh the page
3. Then check third accordion second section. It will expand automatically

**Comment by camelburrito** [comment]
Looks like the issue here is amp-accordion does not have any id attached to it hence the effect. Not sure why the runtime stopped generating ids

@dvoytenko , @jridgewell

**Comment by pooja1016** [comment]
Okay how can I resolve this ?

**Comment by camelburrito** [comment]
As a workaround try giving ids to all your accordions

**Comment by pooja1016** [comment]
If i give id's how that will resolve this? 

by the way if you fix this issue from your end it will effect for all right because for this accordion we are using your cdn

**Comment by camelburrito** [comment]
I meant that as a workaround .

Yes we will be fixing it in the amp library itself. This workaround should not cause any breakage even after our fix goes live

**Comment by pooja1016** [comment]
Tried giving different id's and it's working fine now

Thank you:)

**Comment by dvoytenko** [comment]
@camelburrito The runtime has stopped auto-generating IDs a very long time ago (/cc @lannka). If you need some form of identifier, the extension has two choices: either auto-gen an ID or a separate internal attribute that can be referenced by the extension.

**Comment by camelburrito** [comment]
@zhouyx - can you please take a look and fix this.

**Comment by zhouyx** [comment]
will take a look
