### ISSUE TITLE
amp-bind: Integration tests

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#7369]
Currently, amp-bind and each component that amp-bind interfaces with (e.g. amp-carousel) have individual unit tests. It'd be good to have an integration test for each `(amp-bind, <other component>)` tuple to prevent regressions across this interface.

/cc @kul3r4 @kmh287

**Comment by adelinamart** [comment]
@choumx is this a prioritized FR?

**Comment by choumx** [comment]
@cramforce:

> I think something super simple should work like:
>
> - load page with image
> - click button
> - observe that image source changed to new value
> 
> This should give us some confidence that things are working end to end while details are tested in unit tests.

**Comment by kmh287** [comment]
We now have integration tests for all currently supported components.
