### ISSUE TITLE
amp-ad.css is loaded twice

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#7372]
![screenshot from 2017-02-06 11 23 24](https://cloud.githubusercontent.com/assets/8496897/22662718/cd86c666-ec5e-11e6-9d3d-fc51e46e7cc0.png)

**Comment by zhouyx** [comment]
The reason that the CSS is applied twice is we call `#AMP.registerElement` with the same CSS class twice. A very straightforward fix would be do not register `amp-embed` with `amp-ad` CSS. This somehow overlap with #7752 and I would suggest not making that a GFI, but fix it right away so we avoid applying CSS that doesn't belong to `amp-embed`
@lannka @alanorozco

**Comment by lannka** [comment]
Sounds good. Thanks for looking into it.
