### ISSUE TITLE
Support elements w/ bindings in amp-mustache

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#7376]
Currently, amp-bind supports updating local bindable state with the JSON results of an [amp-form](https://www.ampproject.org/docs/reference/components/amp-form) XHR. We should support elements with bindings in a form's submit `<template>`. This probably means amp-mustache should ask `bind-impl.js` to scan its children for bindings after templating completes.

**Comment by kmh287** [comment]
Closed by #7602
