### ISSUE TITLE
Add support for Array.includes to amp-bind

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#7378]
In order to get code readability, we could add Array.contain to amp-bind. At the moment you could achieve the same behaviour by using Array.indexOf() but makes the expressions more complex.
For example, 
myArray[index].values.indexOf(anotherIndex) >= 0 ? doSomething : doSomethingElse
could become
myArray[index].values.contains(anotherIndex) ? doSomething : doSomethingElse

@choumx

**Comment by choumx** [comment]
Thanks for filing this issue! Agree this is would be nice.

**Comment by kul3r4** [comment]
@choumx What is the reason behind the decision to include some Javascript function and some not? Is there a process to add a new one if it's needed?

**Comment by choumx** [comment]
For context, `Array.includes` used to be whitelisted but was removed in https://github.com/ampproject/amphtml/pull/6459 due to lack of cross-browser support. I think we can either add a simple polyfill, either generally or for `BindExpression`.

**Comment by kmh287** [comment]
Is there a good reason not to add the polyfill?

**Comment by kmh287** [comment]
#7517

**Comment by jridgewell** [comment]
Closed by https://github.com/ampproject/amphtml/pull/7401.
