### ISSUE TITLE
Create a "Known Issues" doc

### ISSUE THREAD

**Issue by jmadler** [ampproject/amphtml#738]

**Comment by jmadler** [comment]
See also #737 and possibly others

**Comment by rudygalfi** [comment]
Targeted to M1. Would be great to get some ideas flowing on which known issues we can cite.

**Comment by Meggin** [comment]
Hey, Rudy

Do we still want to pull something together in time for launch?

Even if we just pulled together a simple list of the big ones, I can create the markdown, and get it in.

**Comment by rudygalfi** [comment]
@jmadler Which known issues do you think are most important to highlight?

/cc @cramforce

**Comment by Meggin** [comment]
If this list is succinct, we could put it in the README (amphtml), last
section. And we'll need to make sure there's an attached issue tracking it.

Meggin

**Comment by bpaduch** [comment]
Can we close this issue?  KIs can be found in GitHub issues.
