### ISSUE TITLE
amp-notsupported for amp-ads is misleading

### ISSUE THREAD

**Issue by JamesIves** [ampproject/amphtml#7388]
The wording for the class `amp-notsupported` on the amp-ad element is not consistent with the real problem when an ad fails to load, and rather mileading. For example if an advert was loaded via DFP and DFP has no ads to show, the class `amp-notsupported` gets added to the amp-ad element. However this is the same class that gets added if Google AMP decides it cannot show the ad due to the creative not being supported.

This can be problematic as the Google DFP console does not work with AMP, so it makes troubleshooting adverts rather difficult. 

## How do we reproduce the issue?

Create an amp-ad element for a non-existant advert account. Or connect it to an advert account but limit it so it doesn't serve a creative. 

## What browsers are affected?

All browsers

## Which AMP version is affected?

Latest CDN version

**Comment by jasti** [comment]
@lannka would you please look at how the "no ad" situation can be more developer friendly?

**Comment by lannka** [comment]
@JamesIves I don't fully understand what is misleading here.
We have a couple of AMP elements (`amp-img`, `amp-ad`, `amp-video`) allow user to define a `fallback` as placeholder in case of load failure, and `amp-notsupported` is added in that case.

@dvoytenko any reason why it's named `amp-notsupported` instead of `i-amphtml-fallback-displayed`, which seems to be more consistent with other CSS class naming in AMP?

**Comment by dvoytenko** [comment]
I agree that naming is a bit confusing for that class and I'm ok if we change. It can't be `i-amphtml-` prefixed though since this is a public class. That also means that we should preserve it for backwards compatibility unless we strip away class-based customization in this case.

**Comment by lannka** [comment]
If we have to preserve the old name for backwards compatibility, I guess it will not address the "misleading" concern @JamesIves had. So I think for now we will just stay with it, until we think it's worth to start a formal process of deprecating `amp-notsupported` and introducing new class name.
