### ISSUE TITLE
Disallowed SVG tags 

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#7392]
Not sure why we dis-allow certain svg tags.
https://validator.ampproject.org/#url=http%3A%2F%2Foutput.jsbin.com%2Frenepir%2Fquiet

Here is how i got this asset, our UXDesigner used sketch to download an image as svg (export)

and i optimized it on http://petercollingridge.appspot.com/svg-optimiser. 

I think we should revisit this and whitelist tags that are generated by popular image creating software.

**Comment by dvoytenko** [comment]
@camelburrito Let's check what those tags are and if they are documented. If so - I don't see a reason not to whitelist them.

**Comment by Gregable** [comment]
We whitelisted tags using this list in the past (https://developer.mozilla.org/en-US/docs/Web/SVG/Element). The ones flagged here were not on that list on the last pass, so I presume they are new. Looking at compatibility lists, it's unclear if they are supported by all mobile browsers currently, though I don't have a good way to test. Would browser compatibility be a criteria for supporting?

**Comment by camelburrito** [comment]
Here is the list - and details

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feOffset

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/fegaussianblur

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/fecomposite

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/fecolormatrix

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/femerge

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/femergenode

Also Why do we whitelist tags here and not blacklist (i have no idea why we have these restrictions in SVG)

**Comment by Gregable** [comment]
We always whitelist tags. This is so that a new browser change cannot cause harm before we become aware and blacklist it.

**Comment by Gregable** [comment]
Let me know what you think about my concerns of compatibility. If you want all of these, I'll get them implemented.

**Comment by dvoytenko** [comment]
We always whitelist. Let's add these tags.

**Comment by dvoytenko** [comment]
I double-checked. All of these are still preserved in SVG2 so we should definitely whitelist.

See https://www.w3.org/TR/filter-effects/

**Comment by honeybadgerdontcare** [comment]
Addressed in #7590
