### ISSUE TITLE
Let certain form elements to be outside the form

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#7393]
With bind, we should be totally be able to put tags like `<select>`, `<input type='radio'>`, `<input type='checkbox'>` to some good use outside of forms (imagine applications like credit card recommendations/ showing hotel menu  etc,)

**Comment by dvoytenko** [comment]
We don't allow `<select>` outside forms right now? If so, we should just whitelist, as we do `button` already.

**Comment by camelburrito** [comment]
@dvoytenko - updated the list above, pl take a look again

**Comment by Gregable** [comment]
The tags we disallow outside forms are:

- select
- datalist
- option
- textarea

`input` is already allowed outside.

**Comment by Gregable** [comment]
Should all of those be allowed anywhere in the body?

**Comment by mkhatib** [comment]
@Gregable I believe so, I can't find a reason why not to.

**Comment by camelburrito** [comment]
also `<input type='range'>` (anything that can be used for something else on the page)

**Comment by honeybadgerdontcare** [comment]
Addressed in #7590
