### ISSUE TITLE
Give preference to collapsing an ad slot even with a configured placeholder

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#7395]
At the moment, if a publisher configures a placeholder as part of amp-ad, we always display the placeholder even when we can collapse it (when the ad is not in the current viewport). 
We should go ahead and collapse the slot whenever we can when the ad returns 'no-content'.

We prefer this approach because the user has an ad free experience, where possible, without losing any publisher revenue. 

CC @cramforce

**Comment by cramforce** [comment]
I'm onboard with this, but you mentioned that stuff like "house ads" fallbacks might not want this behavior.

Would be good to get some publisher feedback. CC @jpettitt

**Comment by jpettitt** [comment]
I'm onboard with this.

**Comment by jasti** [comment]
@cramforce  The thing I learned was that even the "house ads" are configured via the adserver. So no configuration on the amp-ad itself.
We'll of course provide an opt out if we hear differently.

**Comment by zhouyx** [comment]
@jasti Sounds fair to me.
To be clear:
Once we decide an ad is `no-content`, the order would be:
Make a one time attempt to collapse ad => apply user provided fallback placeholder => apply default fallback placeholder.
We will not provide opt out unless required later

**Comment by jasti** [comment]
@zhouyx Correct.
