### ISSUE TITLE
AMP Pages Syntax Error

### ISSUE THREAD

**Issue by yogeshkhetani** [ampproject/amphtml#7396]
Hello,

This AMP pages are working better but correct standards need to be followed. I know about common AMP errors like AMP markup missing, Content mismatch and others but today on my blog I found a new AMP error. It's the error of **Syntax Error** and its something that I should be worried because Google Search Console detects it as **Critical error**.

For reference, this error happened on the following URLs on my blog -

https://technosamigos.com/product/htc-10-lifestyle/
AMP URL - https://technosamigos.com/product/htc-10-lifestyle/amp/

https://technosamigos.com/product/huawei-p9-plus/
AMP URL - https://technosamigos.com/product/huawei-p9-plus/amp

Installed AMP version is 0.4.2 and I am using Chrome browser.

Please help me to fix this issue.

**Comment by Gregable** [comment]
The validation error you are seeing is pointing out that you have not set a valid width on your `<amp-ad>` tags. The documentation on AMP-AD is here: https://www.ampproject.org/docs/reference/components/amp-ad

You can play with these issues more quickly in the AMP Validator than Search Console if it helps. See
https://validator.ampproject.org/#url=https%3A%2F%2Ftechnosamigos.com%2Fproduct%2Fhuawei-p9-plus%2Famp
