### ISSUE TITLE
Extension for embedding Google+ posts

### ISSUE THREAD

**Issue by timsueberkrueb** [ampproject/amphtml#7397]
## Short description of your issue:

While it is possible to embed posts from many [other social networks](https://github.com/ampproject/amphtml/tree/master/extensions#social), there is no way (correct me if I'm wrong) to embed a Google+ post in an AMP page, yet. This would be a very useful addition to me.

## What browsers are affected?

All browsers.

## Which AMP version is affected?

All versions (correct me if I'm wrong).

**Comment by cramforce** [comment]
I've not seen such an embed in a while. Last time I looked they were extremely heavy; basically embed the full old G+ legacy site in a little iframe, but that might have changed since.

If this example is correct a typical post weighs in at about 1MB http://output.jsbin.com/suhuha/quiet

**Comment by cathyxz** [comment]
Duplicate with https://github.com/ampproject/amphtml/issues/16578.
