### ISSUE TITLE
amp-bind can't set state for variables inside amp-state

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#7399]
At the moment it's only possible to set the values for global variables via AMP.setState but not for variables declared inside amp-state.

Example:
`AMP.setState(foo=123)` -> is working

`AMP.setState(myAmpState.foo=123) `
where 
```
<amp-state id="myAmpState">
      <script type="application/json">
      {
          "foo": "234"
      }
.....
```
is not working.
Current workaround is setting default variables.

@choumx @ericlindley-g

**Comment by choumx** [comment]
Chatted with Chiara and agree that it would be nice to use `amp-state` to set default values for state variables like `myAmpState.selectedColor` rather than using `selectedColor || <default-value>` everywhere. We'd need to add support to the parser in `action-impl.js`. 

A couple thoughts:
- `AMP.setState(myAmpState.foo=bar)` seems better than `AMP.setState(myAmpState={foo: bar})`
- Actions parser also currently doesn't support object or array literals. If we want them, perhaps we should use a parser generator rather than current hand-coded solution?

/cc @dvoytenko

**Comment by dvoytenko** [comment]
`myAmpState.foo` sounds good. An alternative to `AMP.setState()` we could expand grammar with `{}` like this:

```
<button on="tap:{myAmpState.foo = bar}"
```

That way we could keep state and actions in separate grammars since functional calls normally not the same as state manipulation.

RE: grammar: by all means. The only question is the size. Last time I tried, I got 9K minified JavaScript and decided to go down the manual path. With `amp-bind` we have an alternative approach, though. We can queue up `{}` expressions in actions until `amp-bind` has been downloaded and installed and have `amp-bind` parse them. That could let us be expressive in grammar w/o blowing up core binary size.

**Comment by kul3r4** [comment]
More than setting variables, I also noticed that inside AMP.setState it's not possible:

- Access anything declared in the amp-state. 
Scenario
There are 2 amp-selector: amp-selector1 and amp-selector2. When you select 'a' from amp-selector1 you want select something on amp-selector2 based on a rule defined in the amp-state json. In a real scenario, amp-selector-1 is a color selector and amp-selector2 is a size selector and you have 2 global variables called selectedSize and selectedColor. When you select color green, you would like to preselect size M, then switch select color yellow and you would like to preselect size L. Notice that you are never clicking on the size selector, so even if you have `on="select:AMP.setState(selectedSize=event.targetOption)"` the global variable selectedSize is never set. Using defaults doesn't help here: you can use a default for evaluating an expression, for example `[selected] = selectedSize || 'green'` but this will only help setting the `selected` attribute and not the selectedSize global variable. You can potentially end up in a state where there is inconsistency between what is the value of `selected` and what is the value of selectedSize.
In order to provide a workaround from the above problem, you could set the `selectedSize` whenever you select a color. Something like:
`on="select:AMP.setState(selectedColor=event.targetOption, selectedSlide=0, selectedColor == 'green' ? selectedSize='M' : selectedSize = 'S’"` this would duplicate the logic that could easily live in a json amp-state but given you can't access them, it would help but here it comes the second limitation (see below)

- Use conditions inside AMP.setState
If you use conditions like == :? inside AMP.setState you get an error, so the only way to solve the above problem is to set a defaultSize in the expression which is equal for all colors, simply:
`on="select:AMP.setState(selectedColor=event.targetOption, selectedSlide=0, selectedSize = 'S')"`,
this restricts what you can achieve using amp-bind at the moment.

@choumx @ericlindley-g

**Comment by kul3r4** [comment]
@ithinkihaveacat FYI

**Comment by choumx** [comment]
@kul3r4 Interesting, do you have any suggestions beyond fixing this issue? I'll take a closer look at the example once it's live.

**Comment by choumx** [comment]
Oops.

**Comment by kul3r4** [comment]
You can set the value of a (binded) variable by  using`AMP.setState` inside `on=` action. This requires you to know all the information about the variable, but it's not possible to do any encapsulation. 

Let's take the following example:
`
    <amp-state id="product">
      <script type="application/json">
      {
          "green": {
            "sizes": {
        			"S": "$5.99",
        			"M": "$5.99",
              "L": "unavailable"
        		},
        		"defaultSize": "S"
        },
        "golden": {
          "sizes": {
            "S": "$9.99",
            "M": "unavailable",
            "L": "$9.99"
          },
          "defaultSize": "S"
        },
        "red": {
          "sizes": {
            "S": "$7.99",
            "M": "$7.99",
            "L": "$7.99"
          },
          "defaultSize": "S"
        }
      }
    </script>
  </amp-state>
 
<amp-selector name="color" layout="container" [selected]="selectedColor" on="select:AMP.setState(selectedColor=event.targetOption, selectedSlide=0)")>
            <ul>
              <li>
                <amp-img option="green" selected src="/img/green_apple_1_60x40.jpg" width="60" height="40"></amp-img>
              </li>
              <li>
                <amp-img option="golden" src="/img/product1_alt1_60x40.jpg" width="60" height="40"></amp-img>
              </li>
              <li>
                <amp-img option="red" src="/img/red_apple_1_60x40.jpg" width="60" height="40"></amp-img>
              </li>
            </ul>
          </amp-selector>
        </div>
          <label for="size">Size:</label>
          <amp-selector name="size" layout="container" on="select:AMP.setState(selectedSize=event.targetOption)" [selected]="product[selectedColor || 'green'].sizes[selectedSize || 'S'] != 'unavailable' ? selectedSize : product[selectedColor || 'green'].defaultSize">
            <ul>
              <li option="S" class='' [class]="product[selectedColor || 'green'].sizes['S'] != 'unavailable' ? '' : 'unavailable'">S</li>
              <li option="M" class='' selected [class]="product[selectedColor || 'green'].sizes['M'] != 'unavailable' ? '' : 'unavailable'">M</li>
              <li option="L" class="unavailable" [class]="product[selectedColor || 'green'].sizes['L'] != 'unavailable' ? '' : 'unavailable'">L</li>
            </ul>
          </amp-selector>`

You click on green. Each color has a rule where it can decide which is the selectedSize: for example when you click on green you always want S to be selected or when you click on yellow you always want M to be selected. This is expressed by `selectedSize : product[selectedColor]` In the scenario above, who is gonna set the variable selectedSize? The ideal would be size selector itself doing it but because there is no action on it, it can't call `AMP.setState(selectedSize=...)`. The only thing that changes for the select size selector is the binded variable [selected], so what about being able to setState there? Something similar to `[selected] = var selectedSizeResult=expression, AMP.setState(selectedSize=selectedSizeResult), selectedSize`; 

this means that in the end `[selected]` will be set to the result of an expression and at the same time we are also setting the global variable selectedSize to the same value.

**Comment by ericlindley-g** [comment]
I'll let @choumx speak to the technical limitations and opportunities with the mechanic above, but just as a word on the user-facing functionality, as an aside:

In a real-world example, when a user selects a new color, I don't think we'd want to select a new size automatically. We'd probably want to keep whatever size selection was made, unless the size were unavailable in the new color, in which case that size selection becomes disabled and de-selected. The reason for this is that the user might proceed through checkout without noticing that a new size has been selected.

I know this doesn't solve the larger question of how to offer better encapsulation in amp-bind, but may simplify the task at hand.

**Comment by kul3r4** [comment]
Thanks @ericlindley-g, that's a valuable point!
In this scenario, 

> unless the size were unavailable in the new color, in which case that size selection becomes disabled and de-selected. 

if we wanted to keep a global variable `selectedSize` we would still need a way to set it to null or empty when switching between colors. It's true that we can style the selector in order to deselect all the sizes, but the state of the page will not be consistent with what the page is showing. Which component is gonna set it?

**Comment by ericlindley-g** [comment]
Ah! Good point—sounds like it's the same problem :)  I'll defer to @choumx on the best strategy for that.

**Comment by choumx** [comment]
Hmm, I see. So in the case of resorting to the "default" size, `selectedSize` will have a value inconsistent with what's displayed on the page. 

Question: do you *need* `selectedSize` to always be consistent with the page's display state? For this page, a form can submit using the `amp-selector#size`'s value instead of the `selectedSize` variable.

I can see how this would be useful though. One way would could support this is to support more powerful syntax in `AMP.setState` as Chiara suggests. Instead of having the logic for setting default size in `amp-selector#size`, move it into `AMP.setState`:
```
<amp-selector name="color" [selected]="selectedColor" 
on="select:AMP.setState(
    selectedColor=event.targetOption,
    selectedSize=product[event.targetOption].sizes.includes(selectedSize)
        ? selectedSize 
        : product[event.targetOption].defaultSize
")>
```
To support this, I like Dima's suggestion to allow `amp-bind` to parse these expressions with a special syntax for `AMP.setState`. Perhaps:
```
on="tap:AMP.setState({
    selectedColor: event.targetOption,
    selectedSize: product[event.targetOption].sizes.includes(selectedSize)
        ? selectedSize 
        : product[event.targetOption].defaultSize
})"
This allows multiple variable assignment and makes it clear that the special syntax only works for the `AMP.setState` action.

**Comment by rajatgupta1993** [comment]
I need to make a dynamic string based on same amp-states. How can I do that? I have tried following :

1. `src="https://google.com/search?language=en&locales[]=en&query=" +(form.query)`
2. `src="https://google.com/search?language=en&locales[]=en&query=" +{{form.query}}`
3. `src="https://google.com/search?language=en&locales[]=en&query=form.query"`

but none of these work. How can I achieve this?
