### ISSUE TITLE
amp-iframe scroll in iOS not working

### ISSUE THREAD

**Issue by erickbosco** [ampproject/amphtml#7400]
The scrolling of amp-iframe in iOS not working, Safari and Chrome.
I'm using the currently AMP version.

The code is simple:
```
<!doctype html>
<html amp>
        <head>
                <meta charset="utf-8">
                <script async src="https://cdn.ampproject.org/v0.js"></script>
                <script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>
        </head>
        <body>
                <amp-iframe width=300 height=300 scrolling=yes
                   layout="responsive"
                   sandbox="allow-scripts allow-same-origin"
                   src="https://www.tripadvisor.it/WidgetEmbed-cdspropertydetail?display=true&partnerId=B8CB2C91EEE24F6DB9EA2EDA050D7B85&lang=en_US&locationId=206650">
                 <amp-img layout="fill" src="/application/themes/twig_theme/default/images/loading.gif" placeholder></amp-img>
                </amp-iframe>
        </body>
</html>
```

**More details:**
Device: iPhone 6
OS: iOS 10.2
Chrome: 55.0.2883.79

The same code working fine on Android.

**Comment by erwinmombay** [comment]
not sure how to gauge priority on this @dvoytenko

**Comment by muxin** [comment]
When the doc is not iframed and in ios, the `getViewportType` returns `NATURAL`. ([code](https://github.com/ampproject/amphtml/blob/master/src/service/viewport-impl.js#L1779)). Is this desired?

**Comment by jridgewell** [comment]
> When the doc is not iframed and in ios, the getViewportType returns NATURAL

Yes. This skips all the fixed position, scroll, body reparenting hacks that we have to use when the page is embedded.

**Comment by dvoytenko** [comment]
@cramforce 

I see `makeIOsScrollable` code in the `amp-iframe.js` that sets `overflow-auto`, but not `-webkit-overflow-scrolling: touch`. Even with that, I'm not sure if it ever was meant to scroll? Would it expect resize even to make the actual iframe bigger and let the parent page scroll it?

**Comment by icakis05** [comment]
You have to reopen the issue, it is not working anymore with "-webkit-overflow-scrolling: touch". Check your example (http://output.jsbin.com/sopuji/quiet) on iPhone 7/8 (iOS 12).

**Comment by ducnguyenphanhoai** [comment]
I have problem same that! But I can't fix that I was try two day and my test was try add this code:
```
    html {
         position: fixed;
         outline: 0;
    }
```
And afteer that I was try add:
```
    html {
        -webkit-overflow-scrolling: touch !important;
    	position: fixed;
    }
```
But all not useful. Have any body was resolved that? Can help me. I was test with IOS 12 and my website is thefunkyball.com
