### ISSUE TITLE
Optimize the runtime performance of the validator.

### ISSUE THREAD

**Issue by powdercloud** [ampproject/amphtml#7420]
This will serve as a summary issue for ongoing work to improve the runtime performance of the Javascript validator - that is, the (minified) code which we build from validator/engine/*.js. The objective is to make the validator tolerable in client-side applications, that is, in the browser on a user's cell phone; but there may also be benefits to better performance for server side applications. Some work has already been done, including efforts to lazily instantiate the ParsedTagSpec / ParsedAttrSpec. Additional work will focus around further reducing the number and size of objects that the validator runtime generates. Ideas are welcome, please feel free to just respond to this issue as you see fit. Thanks!

**Comment by honeybadgerdontcare** [comment]
#7590  mentions this issue.

**Comment by Gregable** [comment]
Closing this, as this is no longer a priority.
