### ISSUE TITLE
Google CDN validator accepts invalid unicode characters in data- attributes.

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#7422]
If a code snippet gets pasted from a pdf file the '`-`' characters, get mangled to unicode `e2 80 90.` If this makes it to a production web site the Google AMP CDN will accept the invalid attribute (the Cloudflare CDN and JS validator will correctly reject it).

I just noticed in in an `amp-ad` tag  `<amp-ad data-ix-id= ...` it may show up elsewhere.

tagging @dknecht

**Comment by cramforce** [comment]
CC @Gregable

**Comment by Gregable** [comment]
Do you have a specific document that you can paste somewhere?

**Comment by jpettitt** [comment]
Example sent to @Gregable via slack.

**Comment by Gregable** [comment]
Couldn't reproduce again when chatting over slack. Added some test cases to our cache to make sure this issue doesn't regress.
