### ISSUE TITLE
Intent to implement: AMP Hero Element

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#7423]
AMP Hero markup would allow a page author to specify which elements are most important on the page. This specification will be used by analytics and other components.

For details see https://docs.google.com/document/d/1RmQl9B_dzk481R9SR-tsOVV1tO2piDLgSZ7yuIZGBnw/edit#

**Comment by jasti** [comment]
Removed the ads categorization because this is specifically not meant for ads. Please change if necessary.

**Comment by aghassemi** [comment]
let's keep it as a normal feature request. removed I2I label.

**Comment by kristoferbaxter** [comment]
Closing this issue. We've introduced the `data-hero` attribute that covers the image loading case and can investigate additional complexity should the need arise.
