### ISSUE TITLE
Conditionally load component based on size of another

### ISSUE THREAD

**Issue by bjalford** [ampproject/amphtml#7431]
Got an odd one to try and work out how to do in AMP.

Let's say there is a container in a grid that is 600 pixels high.  The current 'web' behaviour I'm trying to match is:

An ad is loaded in the container. If the ad is is 600 pixels tall then nothing else happens as the area is filled.

If the ad is 300 pixels high then an additional call is made to bring in a second 300 pixels ad so that the container is full.

You can see the current implementation in the right of the top row on desktop here: http://www.independent.co.uk

**Comment by camelburrito** [comment]
@bjalford - did you try this - https://github.com/ampproject/amphtml/tree/master/ads#ad-resizing

**Comment by ericlindley-g** [comment]
Is there a non-ads use case for this? 

/cc @jasti

**Comment by jridgewell** [comment]
Could this be solved by `<amp-auto-ads>`?

**Comment by jasti** [comment]
@tlong2 for if this relates to `<amp-auto-ads>`.
@bjalford this is indeed an odd one. Do you plan to see this sort of thing happen in mobile? I don't know of any other publisher doing this/ wanting this, so will be low priority for the core team. Please feel free to send a PR though.

**Comment by tlong2** [comment]
I don't think `<amp-auto-ads>` will be particularly useful for this. Doesn't sound like what's being suggested here would ever need to resize the container. It would just need to shrink the first `<amp-ad>` to the size of it's contents and then insert a second `<amp-ad>` in the remaining space.

**Comment by jridgewell** [comment]
> Doesn't sound like what's being suggested here would ever need to resize the container. It would just need to shrink the first <amp-ad> to the size of it's contents and then insert a second <amp-ad> in the remaining space.

That's exactly what I mean. A call is made using `<amp-auto-ads>`, it decides it can fit 2 300px ads into this 600px container, it returns both ads.

**Comment by tlong2** [comment]
I guess it depends what is making the choice about how big the ad is. I assumed that @bjalford was talking about having a 600px <amp-ad> that makes a 600px-height request to the ad server. If the ad server choses to only fill it with a 300px ad, then something client side creates a second 300px ad to fill the space.

If my interpretation above is correct, then the sizing decision is not something `<amp-auto-ads>` could help with since all it's logic runs before any kind of ad request is made.

**Comment by bjalford** [comment]
Thanks - just a note to say I'll reply beginning of next week

**Comment by jasti** [comment]
Ping @bjalford
