### ISSUE TITLE
amp-form does not submit inside amp-live-list

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#7434]
Forms are not submitted if they are part of an amp-live-list once the live list has updated.

## How do we reproduce the issue?

1. Open https://amp-live-list-form.gomix.me/ [source](https://gomix.com/#!/project/amp-live-list-form)
2. Enter something into the form and press submit -> input is printed inside the doc
3. Wait until the time updates via amp-live-list (15s) 
4. Enter something into the form and press submit -> the form is not submitted

@mkhatib @erwinmombay

**Comment by erwinmombay** [comment]
so this is because amp-live-list replaces the amp form and no longer gets proxied.
I dont think amp-live-list should know anything about amp-form, amp-form or some other framework level service should detect this imo.

cc @dvoytenko @mkhatib

**Comment by dvoytenko** [comment]
We definitely need to find a way to pick up the implementation. Any ideas how do do this? Let's outline couple options available to us. This is pretty important. I'm gonna keep it at P1, but I'd like to have that discussion asap.

**Comment by erwinmombay** [comment]
@dvoytenko, @cramforce suggested to dispatch an event instead that the amp-form code can listen to when amp-live-list inserts or replaces so that the two components aren't tightly coupled through the service getter. WDYT?

**Comment by dvoytenko** [comment]
Event sounds ok. Let's try. Let's just make sure we add listener from amp-form handler before doing the initial scan. And re-entrant code is still needed.

**Comment by erwinmombay** [comment]
@sebastianbenz fix has been merged to master
