### ISSUE TITLE
Implement i18n for the "Ad" in the ad loading indicator

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#7445]
Although the 'Ad' part can be overridden programmatically, we should also have the ability to localize it based on the primary language on the page. 

![image](https://cloud.githubusercontent.com/assets/2366341/22769098/5d1d32f0-ee3b-11e6-957c-2f5d83bdd3b8.png)

**Comment by lannka** [comment]
@dvoytenko will there be a global effort to localize the whole AMP?

**Comment by dvoytenko** [comment]
Not yet. I'd say it's coming, but not for a set of 2-3 strings. We need a bit more before we can justify this.

**Comment by lannka** [comment]
#7665 should have made it better. closing it for now.
