### ISSUE TITLE
Analytics: update visibility processing to work per-root and observe top-level visibility

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#7457]

**Comment by lannka** [comment]
@dvoytenko I would suggest we postpone the work one sprint later after we launched visibility-v2 (should be in the coming sprint) and cleaned up the v1 code.

Unless you think you won't make too much change to `visibility-impl.js`

**Comment by dvoytenko** [comment]
@lannka It's possible that I will have to do that, yes. I will see how much code reuse vs refactor would be forced here.

**Comment by rudygalfi** [comment]
@dvoytenko Will this finish by the end of the sprint?

**Comment by dvoytenko** [comment]
No. Got blacked for V2 launch.
