### ISSUE TITLE
Add viewer integration script to runtime pages based on amp_js_v param

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#7461]
updated description:

When testing example pages against viewer, the page need to have viewer integration script such as `<script async src="https://cdn.ampproject.org/viewer/google/v7.js"></script>`. It would be nice to add the script programmatically instead of manually.

When we are serving pages with url like
- `http://yuxichen.herokuapp.com/examples/everything.amp.max.html&amp_js_v=7`
- `http://localhost:8000/examples/everything.amp.max.html&amp_js_v=1.0`

we could include an extra script tag `<script async src="https://cdn.ampproject.org/viewer/google/v7.js"></script>` or `<script async src="https://cdn.ampproject.org/v0/amp-viewer-integration-0.1.js" data-amp-report-test="viewer-integr.js"></script>`in the document `head`.

This way it's easier to test the example pages when embedded in viewer.

**Comment by muxin** [comment]
Maybe it's also helpful for `localhost` debugging against production viewer.

**Comment by muxin** [comment]
@cramforce I wonder what's the difference between `https://cdn.ampproject.org/viewer/google/v7.js` and `https://cdn.ampproject.org/v0/amp-viewer-integration-0.1.js` which @chenshay is working on. Who deploy the `https://cdn.ampproject.org/viewer/google/v7.js` file?

**Comment by dvoytenko** [comment]
It's best to change our `server.js` to accept `?amp_js_v=X` and based on that either insert `vX.js` from Google or our own `amp-viewer-integration-X.js`. The differentiation can be done based on, X:

- Integer value (e.g. 5) -> https://cdn.ampproject.org/viewer/google/v5.js
- A.B value (e.g. 0.1) -> base/dist/v0/amp-viewer-integration-0.1.js
