### ISSUE TITLE
Error: "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#7476]
A typical call stack is:
```
RangeError: Maximum call stack size exceeded
    at f (https://cdn.ampproject.org/rtv/021486153081489/v0/amp-iframe-0.1.js:28:386)
    at https://cdn.ampproject.org/rtv/021486153081489/v0.js:354:210
    at za (https://cdn.ampproject.org/rtv/021486153081489/v0.js:10:936)
    at Aa (https://cdn.ampproject.org/rtv/021486153081489/v0.js:10:1188)
    at c (https://cdn.ampproject.org/rtv/021486153081489/v0.js:354:102)
    at Ee (https://cdn.ampproject.org/rtv/021486153081489/v0.js:101:70)
    at De.$c (https://cdn.ampproject.org/rtv/021486153081489/v0.js:100:939)
```

The best I can tell is the top line is the `AMP.registerElement` call.

The problem has started on Jan 26th in PROD.

For more details, see https://pantheon.corp.google.com/errors/13800212223959452015?service=default-cdn-1p&time=P30D&refresh=off&project=amp-error-reporting (restricted access)

**Comment by dvoytenko** [comment]
Still debugging. The #7486 is not confirmed as a complete fix.

**Comment by adelinamart** [comment]
Since this is a P0, I'm adding it to the this Sprint queue.

**Comment by jridgewell** [comment]
@dvoytenko: I've gone though every conceivable code flow and still can't find the recursive bug (hell, I can't find _any_ recursion). I'm certain this is another nessy issue, like https://github.com/ampproject/amphtml/issues/3519 and https://github.com/ampproject/amphtml/issues/3795 that affects crappy Android webviews.

How the hell does a [`String#trim`](https://github.com/ampproject/amphtml/issues/3795#issuecomment-228886812) bust the call stack?!

**Comment by dvoytenko** [comment]
I'll monitor for 2 more days.

**Comment by jridgewell** [comment]
So I don't forget tomorrow: https://output.jsbin.com/qekuxe

**Comment by dvoytenko** [comment]
The errors are continuing at the same rate on canary. I'll drop the priority, but will keep the bug open for some time longer.

**Comment by jridgewell** [comment]
This is a nessy.
