### ISSUE TITLE
Cleanup "sticky-ad-early-load" experiment

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#7479]

**Comment by zhouyx** [comment]
@jasti Is it OK to remove the experimental flag now? What's our conclusion on sticky-ad early loading (load after first scroll)?

**Comment by jasti** [comment]
I thought we already launched this! :) Yes, please remove.

**Comment by zhouyx** [comment]
Yes we've launched this for a while. Just curious does the early load feature improves the visibility?  by how much?
