### ISSUE TITLE
Poor page layout causes AMP page to appear to load super slowly

### ISSUE THREAD

**Issue by bradfrizzell** [ampproject/amphtml#7483]
## Description

AMP page was displaying a full-page loading icon for image, when text content had actually already loaded. Thus, the page appeared to be taking a much longer time to load than it really was. This was observed while using a very slow internet connection yesterday. Publishers really should not be structuring their pages like this.

This is what the page looked like scrolled all the way to the top:
![img_2789](https://cloud.githubusercontent.com/assets/4276992/22842787/908e5730-efa4-11e6-8549-38b48159d086.PNG)

But as you can see, the text content had actually loaded:
![img_2790](https://cloud.githubusercontent.com/assets/4276992/22842796/9b38b6f8-efa4-11e6-8ed5-9ef0221f8229.PNG)

[Link to the page](https://www.google.com/amp/s/www.washingtonpost.com/amphtml/politics/conway-may-have-broken-key-ethics-rule-by-touting-ivanka-trumps-products-experts-say/2017/02/09/fd1cc64a-eeda-11e6-b4ff-ac2cf509efe5_story.html?client=safari) - Note that the content has changed and I have not been able to replicate it.

## What browsers are affected?
This was safari on iOS

**Comment by dvoytenko** [comment]
Hmm. They do have a placeholder. With that in mind, it's hard to require more. I will analyze it a bit deeper though.
