### ISSUE TITLE
Error Reporting should Record Experiments

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#7484]
Since we now allow various opt-ins, we should send the currently enabled experiments whenever an error happens.

/cc @cramforce, @dvoytenko

**Comment by dvoytenko** [comment]
+100

**Comment by cramforce** [comment]
!!!

**Comment by dvoytenko** [comment]
One important point. We should do the same with CSI

**Comment by cramforce** [comment]
There we have it planned already
