### ISSUE TITLE
Load 3p frame JS from cdn.ampproject.org

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#7487]
It currently loads from https://3p.ampproject.net/1486670309274/f.js
and should load from https://cdn.ampproject.org/3p/1486670309274/f.js

The original made sense when that was the frame domain, but since that is now per page view it causes extra DNS lookups.

**Comment by keithwrightbos** [comment]
@tdrl let's ensure nameframe for Fast Fetch moves as well

**Comment by cramforce** [comment]
@tdrl Where do you load nameframe from? Here we would continue to load the frame from the `.net` domain, but because we have random sub domains it makes sense to load the JS it loads from the standard JS domain.

**Comment by adelinamart** [comment]
@tdrl do you have any updates here? Thanks
