### ISSUE TITLE
amp img not loading in css input tabs but loads on browser resize

### ISSUE THREAD

**Issue by dignustech** [ampproject/amphtml#7501]
I have a site page where i want to load the news feed with a image and its text. I am using `amp-img` to load the images. The active tab loads the text and images fine, but when switching between the tabs, the content loads but `amp-img` does not. It loads when i resize the browser. 

I have also used a simple image with `img` attribute in between to check the tabs working.

Here is the working url - http://templatefort.com/projects/clubcall/25Jan/index.html

The tabs are named as - trending, transfer, latest at right panel.

Please suggest some solution. Thanks!

@mkhatib @dvoytenko

**Comment by dvoytenko** [comment]
@dignustech The example doesn't appear to be a valid AMP page. Is that a right example?

**Comment by ericlindley-g** [comment]
Closing this for now, since we don't have a valid AMP example, but please feel free to ping or re-open if you have an example of the issue on a valid AMP page.
