### ISSUE TITLE
amp-form: support auto-growing text input field

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#7506]
...similiar to how text input works when composing a text message in android (not sure of [this](http://alistapart.com/article/expanding-text-areas-made-elegant) approach is still up-to-date or if using contenteditable would be better).

Use Cases:

* comment input field
* review input field

**Comment by camelburrito** [comment]
@sebastianbenz please file on ampstart

**Comment by sebastianbenz** [comment]
@camelburrito can do - out of curiosity: how can ampstart solve this? I'd assumed that this is something that needs to be supported by the runtime?

**Comment by aghassemi** [comment]
@cvializ launched this recently 🎉 https://github.com/ampproject/amphtml/pull/20772
