### ISSUE TITLE
Add to homescreen event on AMP-Analytics

### ISSUE THREAD

**Issue by kadircanerergun** [ampproject/amphtml#7508]
I'm using pwa with amp and i want to track users who clicked to Add To Homescreen button. How can i do it ? I think there is "**beforeinstallprompt**" event on pwa but how can i use it on **AMP-ANALYTİCS** ?

**Comment by ahmedzidan** [comment]
Hello @rudygalfi , @ericlindley-g what is the progress of this Feature. 
We have the same issue, we want to track how many user clicked on the "add to homescreen" banner.
Is there anyway to do that?
If not we want to help if we can, so please guid us so we can open a pull request.

**Comment by rudygalfi** [comment]
cc @jeffjose - could you comment if we're planning to prioritize this soon? In light of @ahmedzidan's offer to help implement it, perhaps we could offer some design guidance so they can submit their own PR if we're not planning to take this on soon?

**Comment by lannka** [comment]
The plan is to combine all those requirements into one feature "DomEvent" trigger: https://github.com/ampproject/amphtml/issues/12494#issuecomment-451009869

@ahmedzidan glad you show interests to contribute to AMP. This is definitely a great feature to add in amp-analytics.

Here is a guideline for such a medium size change in AMP:
https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#process-for-significant-changes

@zhouyx and I can be your contact point.

**Comment by ahmedzidan** [comment]
Thanks @lannka , i will start working on that and if i need help will ask you

**Comment by lannka** [comment]
thanks @ahmedzidan . before PR please start with an "Intent To Implement" issue and talk about high level requirement and design. See [this guideline](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#process-for-significant-changes) for details.

**Comment by zhouyx** [comment]
Any update here? Thanks
