### ISSUE TITLE
ValidatorRulesMakeSense errors should be more verbose

### ISSUE THREAD

**Issue by honeybadgerdontcare** [ampproject/amphtml#7509]
From PR #6126, the two error messages didn't make it clear what the contributor needed to do to address them.

1) ValidatorRulesMakeSense extensions require an additional tag

This means there is a missing also_requires_tag. It would be good to explicitly state that and also mention which tag spec is offending here.

Possible rewording: ValidatorRulesMakeSense Tag Spec `{tagspec}` is missing the `also_requires_tag: {Tag Spec or Spec Name}`

2) ValidatorRulesMakeSense AMP-IZLESENE must be whitelisted for AMP4ADS

This means that this extension has not been accepted (whitelisted) for AMP4ADS creative format documents. This happens either because there is no explicit html_format or (as in this case) there is an explicit `html_format: AMP4ADS`. Since it's not whitelisted it must either apply to be whitelisted, add `html_format: AMP` or remove `html_format: AMP4ADS`.

Possible rewording: ValidatorRulesMakeSense Tag Spec `{tagspec}` has `html_format` either explicitly or implicitly set for `AMP4ADS` but `{tagspec}` is not whitelisted for `AMP4ADS`.

@Gregable @powdercloud thoughts?

**Comment by Gregable** [comment]
Sounds good to me.
