### ISSUE TITLE
Tracking: example for tabbed UI in AMP by Example

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#7512]
Tracking issue in this repo for the example here: https://github.com/ampproject/amp-by-example/issues/559

tentatively /to @aghassemi , to re-assign as needed

**Comment by MadisonMiner** [comment]
Hello, 

I created a simple tabbed UI in AMP example, I thought you might find this helpful: 
https://jsbin.com/pitalu/edit?html,output

Thank you,

**Comment by ericlindley-g** [comment]
Nice! Thanks for sharing — @sebastianbenz and @aghassemi, do you have any feedback on the route @MadisonMiner took? Is it a good candidate to shape into a PR? (may be best to follow up in [the issue in AMP by Example's repo](https://github.com/ampproject/amp-by-example/issues/559))

**Comment by ericlindley-g** [comment]
Closed w/ example here: https://ampbyexample.com/advanced/tab_panels_with_amp-selector/
