### ISSUE TITLE
amp-bind not working from today

### ISSUE THREAD

**Issue by pesho79** [ampproject/amphtml#7513]
I used amp-bind last week and it works, but today shows the following error. What is the problem?

Uncaught (in promise) TypeError: Cannot read property 'enqueue' of undefined
    at lb (chunk.js:351)
    at jb (chunk.js:331)
    at chunk.js:72
    at Tb (bind-impl.js:196)
    at Rb (bind-impl.js:138)
    at bind-impl.js:101

**Comment by cramforce** [comment]
This is fixed in the latest release. Opt into dev channel here https://cdn.ampproject.org/experiments.html
