### ISSUE TITLE
Bug: Failed to load store: incorrect origin

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#7519]
Stack:
```
Error: Failed to load store: incorrect origin
at pa (https://cdn.ampproject.org/rtv/001486166232176/v0.js:9)
at na.f.Ad (v0.js:5)
at na.f.expectedError (v0.js:5)
at (https://cdn.ampproject.org/rtv/001486166232176/v0.js:261)
```

This happens due to in-viewer redirect. To support this, viewer has to accept the new URL in handshake. See #7300 (internal b/34893702).

**Comment by jridgewell** [comment]
This is an expected error, so can this be closed?

**Comment by ericfs** [comment]
Do you have an example doc that causes this?

**Comment by dvoytenko** [comment]
I believe this is 99.9% caused by a bug in News, which @newmuis has fixed. I will monitor it for the next week and close it if confirmed.

**Comment by adelinamart** [comment]
@dvoytenko is this still an issue? Thanks

**Comment by dvoytenko** [comment]
Confirmed fix. Closing.
