### ISSUE TITLE
Three dots in my amp-img images

### ISSUE THREAD

**Issue by miguelcolomer** [ampproject/amphtml#752]
I have a " three-backgruond-dots" in the images where i'm using the ```<amp-img>``` tag. It's difficult to see it because it's like a "watermark" or something, but in my logo and in the footer images are alwas those Three dots... i don't know why.

Check it at this URL: http://goo.gl/BvdYzD

i don't know if i have those three dot in my CSS and i can't found them but they've appeared since i'm using amp.

Could you please help me to find them?

Thank you!

**Comment by erwinmombay** [comment]
@miguelcolomer you can add `noloading` on `amp-img` to remove the loader.

**Comment by miguelcolomer** [comment]
Excelent it's fixed!!!
