### ISSUE TITLE
getIntersectionElementLayoutBox API is unclear

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#7522]
Trying to figure out if we can clarify this a lot better:

```
  /**
   * Returns the layout rectangle of the element used for reporting this
   * element's intersection with the viewport.
   * @return {!./layout-rect.LayoutRectDef}
   */
  getIntersectionElementLayoutBox() {
    return this.getLayoutBox();
  }
```

The statement that this is "element's intersection with the viewport." and `return this.getLayoutBox()` reads to me like an oxymoron. Could someone please clarify what's the true intent of `getIntersectionElementLayoutBox`?

**Comment by lannka** [comment]
This is expected to be overridden by any extension that want to provide a different box. And I only found amp-iframe is doing so.

**Comment by dvoytenko** [comment]
Perhaps. But the default implementation seems to not do what the method promises at all.

**Comment by jridgewell** [comment]
> And I only found amp-iframe is doing so.

`<amp-ad>` also does.

> Perhaps. But the default implementation seems to not do what the method promises at all.

How not? By default, the box you want to intersect with is the element's box.

**Comment by dvoytenko** [comment]
`getLayoutBox` is the position/size in the document. `getIntersectionLayoutBox()` is documented as the intersection with viewport. Unless I'm misreading it and it's as simple as updating docs slightly.

**Comment by dvoytenko** [comment]
(this is, btw, I'm asking :))

**Comment by jridgewell** [comment]
It's `#getIntersectionLayoutBox`, not `#getIntersection`. This method is meant to get the box that we will use when we calculate the intersection.

Maybe a better wording is:

> Returns the layout rectangle used for when calculating this element's intersection with the viewport.

**Comment by dvoytenko** [comment]
Yeah. That wording is a lot clearer. If I'm the only one who found it confusing, we can skip. But if not - let's update.
