### ISSUE TITLE
Pagespeed and AMP

### ISSUE THREAD

**Issue by miguelcolomer** [ampproject/amphtml#753]
When using the Google's pagespeed insight service i have foud two minor-issues:

1) In the mobile scrennshot of the mobile analysis, the "image preview" with the mobile's screenshot it's unable to display my logo because i'm using amp-img for thay image.

2) As Pagespeed insisghts said: The https://cdn.ampproject.org/v0.js, could be save 720 B (2 % reduction) after the compression.

You can test it here: https://goo.gl/XaJrGD

Thank you very much.

**Comment by cramforce** [comment]
Not sure about #1. 
#2 is a constant concern for us. I believe PageSpeed is just plain wrong here, but we will soon significantly undercut those 720B.
