### ISSUE TITLE
amp-selector  - CSS Outline is too Specific

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#7534]
For example, in AMP start, I needed to make my selector like this to make the override possible.,

```css
body .www-component-anchors .www-component-anchor[option][selected]
```

 we should split up the selectors into smaller (less specific ones) to make it easier to override - we would need to follow the same principle in all our components to make overriding more simple.

**Comment by camelburrito** [comment]
CC @cramforce @aghassemi

**Comment by cramforce** [comment]
Would this change be backward compatible?

**Comment by camelburrito** [comment]
Yes

**Comment by aghassemi** [comment]
Question, why do we have the outline in the first place? I ran into this the other day and was surprised to see the outline, initially thought something with my CSS is broken until I inspected the element and noticed the outline is coming from the `amp-selector`.

My opinion is to remove the outline all together and keep `amp-selector` purely a behavior component without any style.

**Comment by camelburrito** [comment]
That was what I thought too , but UX + few others(while reviewing) wanted a default CSS to guide authors. Which is not a bad idea.

**Comment by dvoytenko** [comment]
All, TBH, it was me who insisted on the outline. And I still think it's the right thing to do, though would be happy to discuss. Obviously, CSS specificity is a pain and the only way I see it resolve would be via an internal class, as much as I'd hate that. A user would still be invited to override via `x[selected]` or such to preserve semantics.

**Comment by camelburrito** [comment]
@dvoytenko - I think @abeck000 and @ericlindley-g were on board with that too. Its probably not just you. 

I think specificity can be solved by writing simple selectors in this case (it was my mistake)

```css
amp-selector:not([disabled]) [option][selected]:not([disabled]) {
  outline: solid 1px rgba(0,0,0,0.7);
}
```

could have been 

```
amp-selector [option][selected] {
  outline: solid 1px rgba(0,0,0,0.7);
}

amp-selector [option][disabled],
amp-selector[disabled] {
  outline: none;
}
```
would have made it easier to override.

**Comment by ericlindley-g** [comment]
The case is somewhat ambiguous, I also still think the current visual styling is the right thing to do, but am happy to discuss. Agree that changes to make it easier to override would be good, given they're fully backward-compatible

**Comment by cramforce** [comment]
Ick, yes, lets simplify that selector.

**Comment by dvoytenko** [comment]
@camelburrito I think this is still too hard to override. Here's the goal, we need to have selectors that can be overridden as simply as:
```
.myoption[selected] {
  ...
}
.myoption[selected][disabled] {
  ...
}
```

**Comment by camelburrito** [comment]
correct it should be 
```CSS
amp-selector [option][selected] {
  outline: solid 1px rgba(0,0,0,0.7);
}

amp-selector [selected][disabled],
amp-selector[disabled] [selected] {
  outline: none;
}
```
