### ISSUE TITLE
How to pass data through amp-form?

### ISSUE THREAD

**Issue by ChuntheQhai** [ampproject/amphtml#7537]
I have user information form. The form is validated using custom validation amp-form. My xhr-action attributes was pointing to my API url. When I submit my form with POST, my api returns nothing because req.body shows empty. Previously I'm using normal form action is working fine.

`'/api/submit': {
 post: function(req, res){
   console.log(req.body);
 }
}` 

```
form(method="POST", action-xhr!='/api/submit/' + post_form_id + '?_csrf=' + csrf , target="_top", data-form-id=post_form_id, custom-validation-reporting="show-all-on-submit")

  input.form-control.name(
     type="text",
     title="Name is required (Maximum 20 characters only)",
     name="inputNameField",
     placeholder="Full name*",
     id="namefield"
     required,
     pattern="^[a-zA-Z \-\.\@\']{1,20}$")

  input(type="submit", value="Submit", class="btn btn-block btn-black")
```

**Comment by mkhatib** [comment]
Hey @ChuntheQhai thanks for filing, do you have a link where this is hosted and can be tested?

I am not clear on what is the exact problem your facing, is the submit request not happening? Or the submission is failing?

**Comment by xileftenurb** [comment]
I got the same problem until I fount amp-form send all data of xhr request in enctype="multipart/form-data". if the server is not properly configured, there is a good chance body will remain empty in this condition.

I hope this help.

**Comment by aghassemi** [comment]
Closing as it seems the bug is related to incorrect server-side implementation. Note that we are planning to support other `enctype`s for `amp-form` in https://github.com/ampproject/amphtml/issues/7607
