### ISSUE TITLE
Below the AMP-AD are a more "space" than with the standard ad

### ISSUE THREAD

**Issue by miguelcolomer** [ampproject/amphtml#754]
I'm using AMP-AD in my web and below them there are more "padding" or "margin-bottom" or "space" than the rest of the page. It happens with responsive and non-responsive AdSense's ADs.

You can see it here: http://goo.gl/8ecmHb

It's like the "ad iframe" take more space than needed.

**Comment by erwinmombay** [comment]
so you could add a `max-width` / `max-height` here. its probably growing because of `layout=responsive`.

**Comment by dvoytenko** [comment]
Only max-width. `layout=responsive` fixes the aspect ratio. For instance, `max-width: 320px` would instruct an element to be as small or as large as available space, but not larger than `320px`. At the same time height is automatically resized given the aspect ratio. This is often what one would want.

But there are other layouts as well. For instance, `layout=fixed-height` would fix the height and would resize the width to the available width. E.g. height could be `75px` and width would be as large as the container allows.
