### ISSUE TITLE
My website show black page for amp urls.

### ISSUE THREAD

**Issue by aashishpahwa** [ampproject/amphtml#7540]
Hi. 
It was working all fine before the update.

Now the website shows a blank white page for any amp query. Please fix this ASAP.

Website - feedough.com

**Comment by aashishpahwa** [comment]
Please fix this asap.

I don't want my rankings to suffer

**Comment by aghassemi** [comment]
@aashishpahwa Looking at http://www.feedough.com/amp/, that URL returns empty response instead of a valid AMP page. Likely something with your server configuration has changed.

**Comment by aashishpahwa** [comment]
Hi
This is why I opened this issue.

**Comment by aghassemi** [comment]
@aashishpahwa Unfortunately this is something that is not related to AMP runtime and a problem with your server configuration which is not something we control or have visibility to help debug.

**Comment by aghassemi** [comment]
if http://www.feedough.com/amp/ was returning some HTML and page was blank, we would have been happy to help figure out what is happening, but http://www.feedough.com/amp/ is simply not returning an HTTP response body.
