### ISSUE TITLE
v0 AMP not compatible with IE 11

### ISSUE THREAD

**Issue by unitydynamics** [ampproject/amphtml#7544]
Does AMP support IE 11?  I'm going to a lot of trouble to make sure my page AMP-validates and IE 11 is one of my test browsers.

Potentially two issues:
1) trimLeft is used exactly once in validator.js... something in my AMP page caused this code to try and execute.  IE 11 doesn't support trimLeft.

2) I'm getting a "IE media never resolved" error.  Not sure what to do with that.  No luck on Google / Stackoverflow.  Any help appreciated.  

I can post an example but chances are the person who knows the answers can dig right to the point of code I'm referring to in AMP.

**Comment by cramforce** [comment]
AMP itself should work in IE11. The validator may not (but do you really need that?), but could be fixed.

Where do you get the second error?

**Comment by unitydynamics** [comment]
Thank you for the prompt response... for the first item... yes the validator is probably more of a nice-to-have.  

The second item... came from log.js and I'm not sure where else to point you other than I'm using production AMP.  

File: v0.js, Line: 5, Column: 365

If you can guide me to how to debug AMP I will try to provide more information.  The error mean anything to anyone?

**Comment by cramforce** [comment]
Ah, yes #2577

CC @dvoytenko for insight what the error means. Wow, that is ugly :)

**Comment by jridgewell** [comment]
Promoting to a bug. This might be a new case that @dvoytenko media hack doesn't cover.

**Comment by unitydynamics** [comment]
Layout-wise I don't see any problems on the page.  My accordions are working fine.  Perhaps if we could change this from an error to a warning?  I'm speaking without knowledge of the root problem/fix.  Just throwing out a suggestion.

**Comment by dvoytenko** [comment]
This is a `dev` error so normally a publisher would never see it unless they increase log level to 2 (`#log=2`). Is this what happened here?

Generally, we are trying to confirm that `window.matchMedia` works on IE correctly. Unfortunately, sometimes it doesn't. @unitydynamics Are you saying that you are seeing this error every time? If so, could  you please describe how you are testing? I.e. platform/device/emulator.

**Comment by unitydynamics** [comment]
Developing / testing on Windows with my own local server http://localhost:8888/ (no fragment postfixes)
My own installation of IE 11
![image](https://cloud.githubusercontent.com/assets/14965930/22948428/8129d3c0-f2cc-11e6-8447-9ecc94433f53.png)




Seeing the error every time.  When IE dev tools is open it will halt all other javascript and open the debugger.  I don't see any easy options to log to a file like there is with Chrome.  Does this error even happen when dev tools is closed?  Like a tree falling in a forest without anyone there to see it?  Not sure.

**Comment by dvoytenko** [comment]
@unitydynamics Huh. This is very strange. This error is forwarded to us b/c we like to monitor browser API bugs. But it's extremely rare. We get about 0.001% on all IE11 impressions, so it seems really strange that you'd see it every time. I'll debug more here.

**Comment by unitydynamics** [comment]
As far as I can tell it's only an issue when dev tools is open.  That's not a huge concern for me.  I would de-prioritize this.  I'm new to AMP.  Just wanted to make sure I wasn't doing anything wrong.  Thanks for the responses.

**Comment by unitydynamics** [comment]
Quick update this does cause IE to simply crash.  AMP-Form elements I added to my page are not working in IE.

**Comment by dvoytenko** [comment]
Ok, I'm raising the priority.

**Comment by dvoytenko** [comment]
@unitydynamics Btw, can you export your sample page somewhere? E.g. jsbin?

**Comment by unitydynamics** [comment]
This is my page in development:
Here you are: https://jsbin.com/wawosebudi

**Comment by dvoytenko** [comment]
@unitydynamics Ok, I narrowed down the problem. As bizarre as it is, `min-width` filter is underreports by `1px` in IE11.
