### ISSUE TITLE
Multisize Ads not getting centered with layout=responsive

### ISSUE THREAD

**Issue by ajkim** [ampproject/amphtml#7548]
## Short description of your issue:
The multi-size feature for ads has a bug with the layout, in that it will not get centered responsively.

## How do we reproduce the issue?

http://stag.teenvogue.com/gallery/pictures-of-hillary-clinton-and-donald-trumps-election-2016-parties/amp

http://stag.teenvogue.com/story/young-hollywood-2016-meet-11-stars-you-need-to-know/amp

1. Load this url:  http://stag.teenvogue.com/gallery/pictures-of-hillary-clinton-and-donald-trumps-election-2016-parties/amp
2. Scroll down to see that some ads get centered, while others remain left-aligned.

## What browsers are affected?

Viewing this in mobile mode on any browser.

## Which AMP version is affected?

Is this a new issue? Or was it always broken? Paste your AMP version. You can find it in the browser dev tools.

**Comment by glevitzky** [comment]
We've already had an extensive discussion on this here: https://github.com/ampproject/amphtml/issues/6166. The solution there was for the pub to change their CSS. In this case, doing:

```
.ad {
    display: flex;
    align-items: center;
    flex-direction: column;
}
```

Will do the trick.

**Comment by codingdesigner** [comment]
The bug isn't that they're not being centered horizontally. It's that with multisize ads at a range of heights the reserved vertical space for the tallest ad leaves a lot of space for the shortest. 

For example on an add I see a attribute like: `data-multi-size="300x50,300x250,320x50"` and a height set to `height="250"` to accommodate the tallest. When that’s the case and we're served a 50px tall ad there's a 200px difference in ad heights.

**Comment by jridgewell** [comment]
@glevitzky: don't we resize the ad if we can?

**Comment by glevitzky** [comment]
We do resize the ad slot when we can. However, if the surrounding container is larger than the returned ad, and we have layout=responsive, then the tag will be styled with "display:block", and will try to align-left.
