### ISSUE TITLE
How can i disable the Chrome's console developer output?

### ISSUE THREAD

**Issue by miguelcolomer** [ampproject/amphtml#755]
Hi, i don't know if it's possible to disable the output to the Chrome developer's console or any browser... i don't know if this affects the performance and we can enable when we are making changes in the page and disable it when we publish the page for the rest of the people.

Thank you!

**Comment by amphtml-team** [comment]
Logging output is only on in dev mode. I.e. when you have a "development"
attribute on script or a "development=1" hash argument.

**Comment by Gregable** [comment]
Yes, only in development mode will you get most of the logging. Development mode should be disabled for your final pages as it does have a negative performance impact, although somewhat minor. 

Note that even in non-development mode, the AMP runtime will still log a little bit to the console, at a minumum, you'll see something like "Powered by AMP ⚡ HTML – Version 1445032534119"

**Comment by miguelcolomer** [comment]
Ok, i have this message: "Powered by AMP ⚡ HTML – Version 1445032534119" and the errors or warnings (for example if i use amp-img without height or width values). 

Is this the development mode?

I notice a little performance drop when i use amp-img or the adsense code (very little).

Thank You!

**Comment by Gregable** [comment]
You'll see the "Powered by AMP" message in development or not, but the errors/earnings that you mention mean you are in development mode.

You can trigger development mode in the browser in one of two ways. One is to append `#development=true` to your URL documented [here](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#amp-runtime). The other is to add the `development` attribute to your script tag, e.g: `<script src="https://cdn.ampproject.org/v0.js" development></script>` whose documentation was accidentally removed in a recent spec cleanup. I suspect you are doing this through the latter method.

**Comment by miguelcolomer** [comment]
Amazing, yes i'm doing that.  I'll continue applying amp changes to my blogger's blog. Thank you very much!
