### ISSUE TITLE
Validator unittest / build.py failing for Node.js v0.10.25

### ISSUE THREAD

**Issue by powdercloud** [ampproject/amphtml#7552]
When trying to run validator/build.py with this ancient node version there's two failures:
- engine/validator_test.js uses startsWith
- nodejs/index.js fails to report the proper exit status (since process.exitCode isn't supported)

This ancient Node.js version is what's on Ubuntu 14.04, so I think we still care a bit. I have fixes for both, just making a bug here to keep track.

**Comment by powdercloud** [comment]
https://github.com/ampproject/amphtml/pull/7558 fixed the second part.
I also made a fix for validator_test.js which will eventually get exported here.

**Comment by honeybadgerdontcare** [comment]
Addressed in #7590
