### ISSUE TITLE
Worker code must switch to fetch/blob based creation

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#7566]
Creation of web workers from cross origin sources is not allowed unfortunately.

We need to instead

- fetch the source via a CORS request
- create a blob
- launch the Worker with that.

See e.g. this example https://gist.github.com/roman01la/e7a7b879698574c45ca0

This requires the source itself to be CORS accessible, which, coincidentally I need to do anyway because of #7353. See cr/147554802 for that change.

**Comment by choumx** [comment]
Good catch. Looking into this now.

**Comment by cramforce** [comment]
Change on the JS delivery side rolled out.
