### ISSUE TITLE
Layout 3 isn't being recognized as AMP

### ISSUE THREAD

**Issue by aashishpahwa** [ampproject/amphtml#7567]
my amp website isn't being listed as amp in search results. 
website - feedough.com

**Comment by jridgewell** [comment]
Hi @aashishpahwa: Taking the first link I found (http://www.feedough.com/tinder-make-money-business-model/amp/). You have valid AMP, which is as far as the AMP Core team able to diagnose.

While it's a bit confusing, we're not in control of how AMP appears on Google Search. That's another team, unrelated to us. For any issues with appearing in AMP docs appearing Google Search, you have to ask on the Google Forums: https://goo.gl/utQ1KZ.
