### ISSUE TITLE
Let Valid AMP pages iframed inside an AMP page attempt change height(size)

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#7570]
Let AMP pages iframed inside an AMP page attempt change height(size)

**Comment by camelburrito** [comment]
CC @cramforce

**Comment by cramforce** [comment]
Please elaborate on the motivation. I think we are unlikely to do this.

**Comment by jpettitt** [comment]
I could see this as a way of providing a psudo endless amp.  An `amp-list` of `amp-iframes` each containing a link to a valid amp doc.  If the amp doc recognizes it's framed by another amp doc and requests a resize to it's full height. We could mimic something close to endless scroll ....

**Comment by cramforce** [comment]
Endless scrolling as a document feature should probably use shadow DOM, while iframe based endless scrolling would be more appropriate if the iframes are siblings which makes more sense for viewers.

**Comment by dvoytenko** [comment]
Is this the same as #655? I second SD - a much better tool for "infinite" use cases.

**Comment by camelburrito** [comment]
My particular usecase was to embed rendered AMP example code inside a page and have it automatically resize based on its need (as opposed to measuring manually and changing every time we make modifications).  If we let 3P iframes attempt change size why not let AMP ones do it?

**Comment by dvoytenko** [comment]
Yeah, that would probably be fine. We will have to allow AMP page to also react to denied resize requests.

**Comment by cramforce** [comment]
I can see this being important but would like to understand @camelburrito's concrete use case better. Happy to chat in person!
