### ISSUE TITLE
No ampdoc found for [object HTMLHtmlElement] error when including AMP Gallery in shadow root

### ISSUE THREAD

**Issue by edhollinghurst** [ampproject/amphtml#7577]
When using AMP Shadow we are are finding that an error is triggered if the fetched document contains an AMP Gallery.

An example of this can be seen here: https://www.edhollinghurst.com/amp-gallery/index.html

The following error is shown in the console:

error.js:117 No ampdoc found for [object HTMLHtmlElement]

**Comment by edhollinghurst** [comment]
Just to mention, this also appears to be an issue with AMP Ad and AMP Embed components.

Demos here:
https://www.edhollinghurst.com/amp-ad/index.html
https://www.edhollinghurst.com/amp-gallery/index.html

**Comment by dvoytenko** [comment]
Clearly a bug. Fixing...

**Comment by dvoytenko** [comment]
This has been fixed. It missed the canary cut off, so it will be in canary next Thursday. Sorry for the inconvenience.

**Comment by edhollinghurst** [comment]
Thanks Dima!
