### ISSUE TITLE
Only serve either max or min mode with one gulp server

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#7581]
The fact that we have min/max mode requires us to calculate the current mode in runtime. For example:
https://github.com/ampproject/amphtml/blob/master/src/service/extension-location.js#L49
It is confusing during developing and testing. We do get many questions asking about this piece of code.
Another annoying thing is that people fail to see local changes simply because they forget to add .max

When we run the gulp server, it is unlikely that we need the min mode. To avoid all the trouble, maybe we can adapt the same method that we already did with `gulp test`. Only serving one version of files (either max, or min. max by default). One can have two servers running if they need both. 

The proposed command format would look like:
`gulp` (gulp build + gulp serve)
`gulp  --compiled` (gulp dist + gulp serve --compiled)
`gulp --cdn` (gulp serve --cdn)

@dvoytenko @cramforce @lannka

**Comment by cramforce** [comment]
Yes, this is great. Thanks for pushing for this!!!

**Comment by dvoytenko** [comment]
Love it!

**Comment by zhouyx** [comment]
closed by #8559
