### ISSUE TITLE
Investigate whether we can make vsync reliable in the presence of throttling

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#7589]
E.g. we can see to always set a timeout for like 32ms and debounce that while rAFs fire.

This may be crucial for AMP in a box. CC @lannka, @dvoytenko 

#7482 is an example of how this can go wrong.

**Comment by dvoytenko** [comment]
Certainly possible. We clearly separate in vsync animation frames vs measure/mutate frames. The non-animation frames can be enforced to execute with the timeout. Unfortunately, that would take some performance hit to run the "just in case" timer.

**Comment by lannka** [comment]
@cramforce I understand this causes problems if rAF is not reliable. But can you explain what's special about the inabox case?

**Comment by dvoytenko** [comment]
in-a-box iframes can and very likely will be throttled by browsers. Which mostly means that `requestAnimationFrame` will be either slow or won't arrive at all. Since we rely on rAF for measures/mutates, this is a significant issue.

**Comment by lannka** [comment]
It can be throttled for a "good reason" or by a bug (at least weird behavior). I think we only worry about the bug cases, right? 

So we're worrying about that inabox is more likely to hit the bug (weird behavior)?

**Comment by dvoytenko** [comment]
It's not a bug - it's a browser feature. In-a-box is likely to hit it because it's likely to be out of viewport.

**Comment by cramforce** [comment]
I think the performance hit should be absolutely minimal
