### ISSUE TITLE
AMP CDN serves broken AMP if SVG used in CSS url (Formatting error)

### ISSUE THREAD

**Issue by falvhb** [ampproject/amphtml#7593]
## Short description of your issue:

A perfectly valid AMP page is accepted to the AMP CDN. However, by using SVG inside a CSS url, the AMP CDN does some wrong formatting and breakes the CSS, making it invalid.

```
<style amp-custom>background-image:url('data:image/svg+xml;utf8,<svg ... </svg>')}...
```
becomes
```
<style amp-custom>background-image:url('data:image/svg+xml;utf8,<svg ...

</svg>')}...
```

Big problem, because the original AMP page was validated and we did never had a chance to prevent this issue.

## How do we reproduce the issue?

1. Open the AMP CDN Url https://amp-handelsblatt-com.cdn.ampproject.org/v/amp.handelsblatt.com/populismus-in-europa-euro-austritte-als-horrorszenario-fuer-anleger/19395608.html?amp_js_v=7#origin=https%3A%2F%2Fwww.google.de&exp=a4a%3A0&channelid=0&cid=1&dialog=0&prerenderSize=1&visibilityState=visible&paddingTop=54&history=1&p2r=0&horizontalScrolling=0&csi=0&referrer&storage=1&viewerUrl=https%3A%2F%2Fwww.google.de%2Famp%2Famp.handelsblatt.com%2Fpopulismus-in-europa-euro-austritte-als-horrorszenario-fuer-anleger%2F19395608.html
2. The layout looks broken
3. Run in through the AMP Validator: https://validator.ampproject.org/#url=https%3A%2F%2Famp-handelsblatt-com.cdn.ampproject.org%2Fv%2Famp.handelsblatt.com%2Fpopulismus-in-europa-euro-austritte-als-horrorszenario-fuer-anleger%2F19395608.html%3Famp_js_v%3D7%23origin%3Dhttps%253A%252F%252Fwww.google.de%26exp%3Da4a%253A0%26channelid%3D0%26cid%3D1%26dialog%3D0%26prerenderSize%3D1%26visibilityState%3Dvisible%26paddingTop%3D54%26history%3D1%26p2r%3D0%26horizontalScrolling%3D0%26csi%3D0%26referrer%26storage%3D1%26viewerUrl%3Dhttps%253A%252F%252Fwww.google.de%252Famp%252Famp.handelsblatt.com%252Fpopulismus-in-europa-euro-austritte-als-horrorszenario-fuer-anleger%252F19395608.html
4. Errors found:
 
```
CSS syntax error in tag 'style amp-custom' - unterminated string. AUTHOR_STYLESHEET_PROBLEM
line 2, column 8968
```
This is caused by the added line breaks described above.

## What browsers are affected?

All

## Which AMP version is affected?

- AMP Version 1486670309274
- New issue
- Guess alloways broken. Nobody else did such crazy thing before.

**Comment by falvhb** [comment]
**Update**: If the bug is not visible anymore: I did replace the inline SVG with base64. Hope you can still reproduce it.

**Comment by honeybadgerdontcare** [comment]
Providing the actual svg would be helpful. This may be something we're tracking internally but without the svg I can't know for sure b/34882374.

**Comment by falvhb** [comment]
Sorry for the delay. Here is the CSS: https://gist.github.com/falvhb/1e9ddee9f82ff55e38f0827b2428fd21

**Comment by honeybadgerdontcare** [comment]
I'm unable to reproduce this issue using your CSS. Note that in the CSS you provided there is a newline inside the url(''). I removed that as that isn't valid.

Here's my test case:
Original: http://astute-city-159523.appspot.com/files/css.html
CDN: https://cdn.ampproject.org/c/astute-city-159523.appspot.com/files/css.html
