### ISSUE TITLE
amp-carousel preview not working as expected

### ISSUE THREAD

**Issue by weeblr** [ampproject/amphtml#7594]
Hi

Adding amp-carousel preview to existing carousel (using goToSlide), I run into a problem that the preview images are not displayed (inside their respective buttons).

I have done a barebone demo of this, with what I think is a straight copy of the demo:  [view it here](https://cdn.weeblr.net/tmp/carousel-preview.html).

- Carousel is displayed fine as usual
- buttons are displayed, and work fine. ie: clicking on a button advance to corresponding main carousel image
- BUT: images thumbnails are **not** displayed ([screenshot here](https://d1ro8r1rbfn3jf.cloudfront.net/ms_35433/M9yEvhNQztAVnlw3s5IZQcLt5PQUgr/weeblr-2017-02-16-12.32.57.png?Expires=1487331220&Signature=a~c8tFABHWTFF9WoR65MNS3aMZyQyz929fcZfCkLBRDbh1kh-6yVS2hM6AgmRIADkZpx~0b85DIO-qXqvur3eInylckZOqpF4wh77cSW6Q22vVTuAOaZWuLksx1Vx83Xk2QzIlrIubFRUS~MmTOSlZb~K2lC0L-yEPACwepJUE6KW2MBBMMy4DnaOYEgd-fhDOdeBBXuHzsLIctKLf3y8J8tGLpSXPFFtd8nQns1FywqATYKpAV0J3dBqdI9EQNHFVjXHs-GtxfmKhq~W~s8Mw8QlTxbecfCQusVthAe82sru8KCEcsRM1QwndXhlZxAYa8vkasz0C5gDMsnObjCwg__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA))

The raw HTML is:

````
<div>
    <amp-carousel id="carousel-with-preview" width="auto" height="400" layout="fixed-height" type="slides">
        <amp-img src="https://images.unsplash.com/photo-1473800447596-01729482b8eb?dpr=1&auto=format&fit=crop&w=600&h=400&q=80&cs=tinysrgb&crop=" width="600" height="400" layout="responsive"
                 alt="a sample image"></amp-img>
        <amp-img src="https://images.unsplash.com/photo-1478147427282-58a87a120781?dpr=1&auto=format&fit=crop&w=600&h=400&q=80&cs=tinysrgb&crop=" width="400" height="300" layout="responsive"
                 alt="a sample image"></amp-img>
    </amp-carousel>

    <div class="carousel-preview">
        <button on="tap:carousel-with-preview.goToSlide(index=0)">
            <amp-img src="https://images.unsplash.com/photo-1473800447596-01729482b8eb?dpr=1&auto=format&fit=crop&w=60&h=40&q=80&cs=tinysrgb&crop=" width="60" height="40" layout="responsive"
                     alt="a sample image"></amp-img>
        </button>
        <button on="tap:carousel-with-preview.goToSlide(index=1)">
            <amp-img src="https://images.unsplash.com/photo-1478147427282-58a87a120781?dpr=1&auto=format&fit=crop&w=60&h=40&q=80&cs=tinysrgb&crop=" width="60" height="40" layout="responsive"
                     alt="a sample image"></amp-img>
        </button>
    </div>
</div>
````

The amp-img for each image inside each button is there, but the actual img tag is not rendered by the runtime:

````
<button on="tap:carousel-with-preview.goToSlide(index=0)">
  <amp-img src="https://images.unsplash.com/photo-1473800447596-01729482b8eb?dpr=1&amp;auto=format&amp;fit=crop&amp;w=60&amp;h=40&amp;q=80&amp;cs=tinysrgb&amp;crop=" width="60" height="40" layout="responsive" alt="a sample image" class="i-amphtml-element i-amphtml-layout-responsive i-amphtml-layout-size-defined">
    <i-amphtml-sizer style="display: block; padding-top: 66.6667%;"></i-amphtml-sizer>
  </amp-img>
 </button>
````

What puzzles me is that this is working fine on [ampbyexample.com](https://ampbyexample.com/advanced/image_galleries_with_amp-carousel/), with the exact same version of the AMP runtime.

So surely I must be missing something here? or is this not rolled out just yet?

Thanks

**Comment by aghassemi** [comment]
@weeblr `button` by default won't resize to the size of the image inside. You need to specify a `width` and `height` (otherwise it would be 0). Adding a style like below ( which ampbyexample does as well) should fix your issue:

```
    <style amp-custom>
      button {
        width: 60px;
        height: 40px;
        -webkit-appearance: none;
        appearance: none;
        margin: 0;
        padding: 0;
        border: none;
      }
    </style>
```

Another option is not to use `<button>` and instead put the `on="tap:carousel-with-preview.goToSlide(index=0)"` on the `<amp-img>`. If you go with this route, please ensure you also put `role="button"` on the `<amp-img>` as well for accessibility.

**Comment by weeblr** [comment]
Thanks for your reply.

It was actually not the buttons, the button do resize as needed, when the img tag inside has a width/height.

The problem was using a "responsive" layout value for the amp-img.  Switching to "fixed" solves the problem right away.

Rgds
