### ISSUE TITLE
Prepopulate form fill from querystring

### ISSUE THREAD

**Issue by bjalford** [ampproject/amphtml#7600]
Is it possible to prepopulate a form field from a query string in URL?

**Comment by aghassemi** [comment]
@bjalford It is for `hidden` inputs only AFAIK (@rudygalfi @mkhatib please correct me if I am wrong). 
`hidden` inputs support variable substitution (See https://www.ampproject.org/docs/reference/components/amp-form and https://github.com/ampproject/amphtml/issues/6421) and query string params are supported as platform level variables `QUERY_PARAM(baz,biz)` (See https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md)

**Comment by bjalford** [comment]
Cool, thanks! That meets my use case. Happy for this to be closed unless anyone wants an answer on the non-hidden form fields.
