### ISSUE TITLE
Red Build on Master: Form integration tests failing on Edge, Safari

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#7603]
https://travis-ci.org/ampproject/amphtml/builds/202061328

/to @mkhatib 
/cc on-call @jridgewell please follow up until build is green (possible that other breaking changes have also gotten in after this) Thanks!

**Comment by mkhatib** [comment]
Working on this.

**Comment by jridgewell** [comment]
I've got a [fix](https://github.com/ampproject/amphtml/compare/master...jridgewell:amp-form-integration-tests?expand=1), just running it through saucelabs first.

**Comment by mkhatib** [comment]
Cool thanks for taking a look 👍 let me know if that didn't fix it

**Comment by jridgewell** [comment]
Ugh, still failing. Thanks @aghassemi

**Comment by aghassemi** [comment]
@mkhatib Your bugs queue is empty now!  :champagne:

**Comment by jridgewell** [comment]
Master is green. 😀
