### ISSUE TITLE
Modify 3p code path to build window.context from AmpContext

### ISSUE THREAD

**Issue by bradfrizzell** [ampproject/amphtml#7604]
AmpContext class was added to provide window.context functionality to x-domained iframes. Need to eliminate unnecessary code duplication due to 3p still using stale code to create window.context

**Comment by bradfrizzell** [comment]
I'm closing this as per https://github.com/ampproject/amphtml/pull/7841 unless that PR did not meet all the use cases. @lannka please confirm

**Comment by zhouyx** [comment]
@bradfrizzell any plan on using the new `#serializeMessage` function. Asking because #6873 is blocked by this. https://github.com/ampproject/amphtml/blob/master/src/iframe-helper.js#L360 current `#postMessageToWindows` doesn't contain rtv version number.

**Comment by lannka** [comment]
No worry, I will take care of the remaining stuff. As tracked separately here: #8087.
