### ISSUE TITLE
Question: Converting Brightcove embed urls to amp-brightcove without account id

### ISSUE THREAD

**Issue by src-code** [ampproject/amphtml#7608]
Currently the `amp-brightcove` player requires an account id, so I'm wondering what's the right way to convert an existing Brightcove embed url that doesn't require an account id?  For example:

https://link.brightcove.com/services/player/bcpid4608484704001/?bctid=ref:9185&secureConnections=true&secureHTMLConnections=true&autoStart=false&width=533&height=300

My understanding is that there's no account id being passed here, only a player id and video id, but correct me if I'm wrong.

Can the requirement for account id be removed from the Brightcove component?  Or do I need to have an account just to make these embeds work in AMP?

cc @mister-ben

**Comment by aghassemi** [comment]
I have to leave it for @mister-ben to answer.

**Comment by mister-ben** [comment]
`amp-brightcove` does need the Video Cloud account id to be able to load a player but the account id is is not part of that URL, which is for Brightcove's legacy player. You need the specific account id to which the video asset belongs.

What's complacting knowing the account to use - do you use multiple Video Cloud accounts?

**Comment by src-code** [comment]
@mister-ben These embeds are showing up in syndicated content, so we don't have access to the account id that the content provider used.

**Comment by src-code** [comment]
Also, since you mentioned this is a legacy player url - we see providers using this player currently in their content, so would migrating them to an up-to-date player embed provide us with the account id?  If so that may be something we could pursue with our partners for a long-term fix, though it wouldn't help us for previously ingested content.

**Comment by mister-ben** [comment]
I'd recommend reaching out to the Brightcove account owner from whom you're getting the syndicated content. The legacy player id (the number after bcpid in the URL) will correlate to exactly one Video Cloud account) -- you're presumably getting a small number of those player ids and could do a lookup once you know. You'll also need them to give you the player id of a new Brightcove Player to use in the AMP component.

Brightcove's new player embed does have the account id -- but you won't necessarily use the same id in AMP.

**Comment by src-code** [comment]
@mister-ben I'm not sure exactly how many partners we have that embed Brightcove, so I'll have to dig a bit and see if this is feasible.  This seems difficult to maintain in the long run anyway, since presumably partners could begin embedding Brightcove or change player ids without us knowing, which would lead to broken content.  It'd be very helpful if there was a way to adopt the AMP player without having to know special information in advance like this.

**Comment by src-code** [comment]
@mister-ben If you're at AMP Conf, let me know - would be great to meet up!

**Comment by mister-ben** [comment]
@src-code Yes, I'm here. I'm over near the editing desk in the same row as the camera.

**Comment by src-code** [comment]
Closing this one out.  No support for legacy players.
