### ISSUE TITLE
Allow allowpaymentrequest attribute on amp-iframe

### ISSUE THREAD

**Issue by MadisonMiner** [ampproject/amphtml#7623]
Starting with Chrome 57 the the `allowpaymentrequest` attribute on an iFrame will allow the PaymentRequestAPI to function inside an iFrame. Using the PaymentRequestAPI inside an iFrame would allow for single page eCommerce AMPs.

Currently the `allowpaymentrequest` attribute is not allowed on amp-iframe. This attribute should be allowed on amp-iframe and passed to the nested iFrame. 

Note from @aghassemi
-We would need to also set `allowpaymentrequest` on the viewer iframe's that embed AMP pages as  `allowpaymentrequest` on a nested iframe will not be honored if parent iframe does not have it.
-Not sure about WebViews and whether payments are allowed by default or need to be configured.

**Comment by ericlindley-g** [comment]
/cc @rudygalfi @jasti  as FYI — this sounds promising.

@aghassemi  Are there any risks with this in the context of AMP?

**Comment by aghassemi** [comment]
@ericlindley-g Can't think of anything specific to AMP that may prevent us from exposing this through `amp-iframe`. @cramforce ?

**Comment by MadisonMiner** [comment]
@aghassemi, you are correct, the `allowpaymentrequest` attribute is also required on AMP viewer iframe. Is this the correct forum to request changes to the viewer iframe? How I can I help push this forward?

For now, WebViews are less of a concern for us. 

If there is a good chance that eCommerce AMPs with the PaymentRequestAPI will be possible from web search results, when Chrome 57 is released, we will start developing the eCommerce AMPs now. 

I appreciate your help, thank you.

**Comment by cramforce** [comment]
Filed b/35582805 to track this for Google viewers. CC @dknecht for Cloudflare.

We should definitely allow this in AMP. Not a question. Validator change and propagation to iframe element.

**Comment by jridgewell** [comment]
Closing for https://github.com/ampproject/amphtml/issues/7701.

**Comment by aghassemi** [comment]
Let's keep this one open as a tracker for the whole feature (i.e. until  b/35582805 is done) without viewer part, feature won't be prod ready.

**Comment by aghassemi** [comment]
@MadisonMiner @ericlindley-g Google.com Viewer now also sets `allowpaymentrequest` on the iframe. 

@MadisonMiner The iframe approach for web payments should now work, please let us know if you run into issues.

**Comment by ericlindley-g** [comment]
Quick update—I don't think the validation for this is in. Should we leave this open until that gets updated?

**Comment by alanorozco** [comment]
There's also #7701 tracking this, but I think we should keep this open since *technically* we don't really allow the attribute until the validator has been updated on production.

**Comment by alanorozco** [comment]
Now supported.

**Comment by rudygalfi** [comment]
Awesome! Does anyone have a demo for this? I filed an AMP By Example request to incorporate on ABE: https://github.com/ampproject/amp-by-example/issues/713
