### ISSUE TITLE
Error "Cannot read property 'remove' of null" in disconnectedCallback

### ISSUE THREAD

**Issue by eduardcotmrf** [ampproject/amphtml#7625]
With chrome 55 or lower and this conditions:

- I have an amp-shadow-doc-loader, with an amp-carousel with some amp-images inside.
- the amp-shadow-doc-loader has visibility hidden and the visibility-managment manual

When the custom-element (in this case de amp-img inside the amp-carousel) it's in the connectedCallback and adds the class 'i-amphtml-element' the disconnectedCallback it's triggered.

![screen shot 2017-02-17 at 08 59 48](https://cloud.githubusercontent.com/assets/23262331/23057495/bfd20608-f4f0-11e6-868d-02b999177de3.png)

![screen shot 2017-02-17 at 09 00 20](https://cloud.githubusercontent.com/assets/23262331/23057511/c631e798-f4f0-11e6-8327-64b3f40b4179.png)

Then disconnectedCallback tries to get the getResources but nothing is there and I get the error "cannot remove from null". The amp-carousel has the expected behaviour and I cannot see anything broken, but the error is there.

In the lastest version of chrome I haven't been able to reproduce the problem.

Do you know what's going on? Why disconnectedCallback it's called while doing the connectedCallback?

**Comment by choumx** [comment]
@eduardcotmrf Strange, looking at the code it's not obvious to me why this would happen. Possibly a Chrome bug if it's fixed in 56+. Are you still having this issue? If so, can you share the document that exhibits this error? Thanks!

**Comment by eduardcotmrf** [comment]
No, it only happens in old versions of chrome.
