### ISSUE TITLE
Make it possible for AMPs to handle offline state

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#7628]
Make it possible for AMPs to handle offline state, e.g. by disabling certain actions. A first step could be to listen to changes in [connectivity](https://developer.mozilla.org/en/docs/Online_and_offline_events) and add a class `amp-offline` to the body tag `<body class="amp-offline ...">` if `navigator.onLine === false`. 

Then elements could be disabled via css: 

```
amp-offline button.disable-when-offline {
  pointer-events: none;
  ...
}
```

//cc @pbakaus @ericlindley-g

**Comment by SimonHogstromRonbol** [comment]
Hi, I was looking to this issue, as I wanted to be able add a class to the body tag, and i was looking into ways to solve this using amp-dynamic-css-classes, since it is already adding classes to the body tag based on certain things.

I added the following code to the existing extension, and figured it might solve the issue, any feedback would be appriciated.

```
/**
 * Adds a dynamic css class `amp-offline` if the navigator is offline.
 * @param {!../../../src/service/ampdoc-impl.AmpDoc} ampdoc
 */
function addOfflineClass(ampdoc) {
  const online = navigator.onLine;
  if (!online) {
    Services.vsyncFor(ampdoc.win).mutate(() => {
      addDynamicCssClasses(ampdoc, ['amp-offline']);
    });
  }
}


/**
 * @param {!../../../src/service/ampdoc-impl.AmpDoc} ampdoc
 */
function addRuntimeClasses(ampdoc) {
  addReferrerClasses(ampdoc);
  addViewerClass(ampdoc);
  addOfflineClass(ampdoc);
}
```

Full disclaimer, im very new at using git and github, and i was looking into how to contribute, and it said i could ask in the slackchat so i did, and Sebastian suggested that run it by this issue so here i am.

**Comment by aghassemi** [comment]
Hi @SimonHogstromRonbol, thanks for looking into this issue. Please find below some step-by-step instructions on how to turn your code into a Pull Request:

- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] Add the code you mentioned above.
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review).  Mention `closes Issue #7628` in the description.
- [ ] Assign @aghassemi as the reviewer
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

**Comment by westonruter** [comment]
It would be ideal if the online/offline detection could also account for the lie-fi state, that is, to show offline even though the WiFi is connected. This could conceivably be connected with the XHR service, yes? Any time that an `amp-list` or `amp-live-list` etc. tries to load content from the server, it could update some state as to whether requests are failing.

I wonder if having a new `amp-offline` body class would be enough? It would seem useful to me if there were `online` and `offline` events that could be triggered on some element. This would then allow the page to set some state to change the body class and make other changes for offline mode. This would be more powerful than just toggling the body class alone.

**Comment by aghassemi** [comment]
agree with the event as long as we make sure it does not happen on page load. So likely `on="onlineStatusChanged:act"` instead of `on="online:act, offline: act"`.

AMP trying to detect "real" onlineness is an interesting idea! I am just worried we may not be able to invalidate the state quickly enough without constantly polling an endpoint ( e.g. `amp-list` initially fails to connect and we set to `offline` but there isn't any other XHR from the page anymore and we never go back to `online` ) 

We should bring this up with WebPlafroms to see if they can improve accuracy of `navigator.onLine` based on real data.

**Comment by westonruter** [comment]
> agree with the event as long as we make sure it does not happen on page load. So likely `on="onlineStatusChanged:act"` instead of `on="online:act, offline: act"`.

@aghassemi What's the concern here, that the event happens _during_ page load and thus causes content shifting?

Something else that comes to mind is that it would be important to obtain the initial online/offline state on the page. For example, if a service worker is serving the page from cache but otherwise the user is offline, the page should be able to indicate this fact. With amp-script and similar logic for service workers (https://github.com/ampproject/amphtml/issues/18615#issuecomment-428006471) it would be possible in AMP to indicate which URLs on the page by having a worker query the cached URLs and sync those via state to the page.

Has there been a discussion in amp-bind for reserved state which is controlled by the runtime and is not mutatable by the user? For example, there could be some reserved `amp` state namespace which has a pre-populated `online` property which is then managed internally by AMP. This could then be used instead of an event. I suppose the `amp.online` state would have to always be initially `true` for the sake of unhydrated content so that it initially matches the state, for example:

```html
<p [text]="amp.online ? 'You are online!' : 'You are offline!'">You are online!</p>
``` 

> We should bring this up with WebPlafroms to see if they can improve accuracy of `navigator.onLine` based on real data.

Yeah, that would be best rather than having to reinvent the wheel each time.

**Comment by aghassemi** [comment]
@westonruter initial state is always a hard choice. It comes down to whether we want to block rendering (`amp-dynamic-css` does block rendering) or not. Initial state being exposed as a dynamic CSS class would be fine and we would have to block rendering anyway. Exposing an event that always runs as soon as page loads (whether online and offline) would allow `amp-bind` to run at load time which is something we have avoided. (For instance `<p [text]="amp.online ? 'You are online!' : 'You are offline!'">You are online!</p>` would never work at load time as bind never runs). Render-blocking on `amp-bind` is a lot worse than render blocking on `amp-dynamic-css`. amp-bind extension size is big and evaluating/executing expressions are expensive. 

We can put the initial (and updated) state in AMP bind state as you mentioned (`amp-geo` does something like this for instance).

So if we can most use-cases by:
1- `amp-dynamic-css` during load time.
2- combination of amp-bind and events after initial load

we would be in a good state.

**Comment by westonruter** [comment]
For https://github.com/ampproject/amphtml/issues/7628#issuecomment-335563955 a key change would seem to be adding an `online` event handler to remove the `amp-offline` body class if the user came back online later, no? Similarly there should be an `offline` event for restoring the body class.

Or would the body class added by `amp-dynamic-css-classes` be immutable and documents would need to be written to account for state changes later applied by `amp-bind`? I see a conflict possible when using `amp-bind` to manage the body `class`, as would it not clobber any classes added by `amp-dynamic-css-classes`? To prevent that there would seem to need to be some AMP helper for obtaining classes added by `amp-dynamic-css-classes` to use in bind expressions, for example:

```html
<body [class]="AMP.dynamicCssClasses().concat( isOnline ? [ 'online' ] : [] )">
```

Where the `isOnline` state would be set by `amp-bind`. CSS that is styling based on online/offline state would then need to take into account both of these classes:

```css
body.amp-offline:not(.online) .status { content: "Offline!" }
body.online .status { content: "Online!" }
```

That doesn't seem great, but it would be doable.

**Comment by sebastianbenz** [comment]
Completely different idea. How about making this more explicit by adding an amp-offline component that:

* introduces a new attribute `offlineaware` which inputs and buttons can use to indicate that they're disabled when the user is offline (this should cover most use cases for offline scenarios).
* shows a fixed snackbar at the bottom (which we control to avoid reflow).
* adds a "REFRESH" button the snackbar which will check the network connection and change the state of the document.

**Comment by westonruter** [comment]
This component would still need to be render-blocking the same way as `amp-dynamic-css-classes` is, right?

> introduces a new attribute `offlineaware` which inputs and buttons can use to indicate that they're disabled when the user is offline (this should cover most use cases for offline scenarios).

Would this be enough? I think, for example, that when a form is not available offline that there should be more displayed to the user than just inputs & buttons being disabled. For example there should be a message that is displayed below the form to inform them that they are offline and this is why the form is disabled. If we could set some `amp-state` in response to online/offline events then we'd have a lot more flexibility.

Also, what about links? For context I have in mind implementing what @surma [implemented](https://github.com/GoogleChromeLabs/ProgressiveWordPress/) where articles that are not available offline (ones not cached) are grayed out in the article list. Clearly what is being proposed in this offline issue is not sufficient in and of itself to implement this (as we'd need to also communicate via `amp-script` which articles are cached offline), but it would be one required component.

> adds a "REFRESH" button the snackbar which will check the network connection and change the state of the document.

If updating the state were limited to a user clicking the button, would this be sufficient for when the user goes from the online state to the offline state? Are you thinking that when the user is on a train and they go into a tunnel, and they are attempting to perform some offline action, that they would be alerted via the snackbar that they have gone offline and that they need to click the button to cause the submit buttons to become disabled? I should think that the document's updated state should apply automatically without having to click anything, though I realize that introduces the possibility of content shifting.

**Comment by sebastianbenz** [comment]
I think it'd be fine to not make the component render-blocking (this assumes that disabling inputs usually doesn't change the height). Good point about links, these could also support the `offlineaware` attribute. For example, the component could automatically query the cache status for all links with the offlineaware attribute. 

The snackbar should automatically appear once the user if offline. The refresh button will force the runtime to check if the offline state has changed, similar to what Gmail does (this used to be a common pattern, not sure of that still is needed). 

These are just rough ideas, but the important thing is that with AMP we have the chance to make it a lot easier to create an offline experience by creating good abstractions.
