### ISSUE TITLE
Add discussion of filtering for amp-live-list in the amp cache modifications doc

### ISSUE THREAD

**Issue by Gregable** [ampproject/amphtml#7638]
https://github.com/ampproject/amphtml/blob/master/spec/amp-cache-modifications.md should mention the filtering we do on refetches to amp-live-list documents.

**Comment by honeybadgerdontcare** [comment]
Done.
https://github.com/ampproject/amphtml/blob/master/spec/amp-cache-modifications.md#remove-amp-live-list-children-based-on-amp_latest_update_time-parameter
