### ISSUE TITLE
Shall we totally remove visiblitySpec from "hidden" trigger.

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#7651]
A "hidden" trigger with `visibilitySpec` will fire when page enters background and meantime all the conditions specified in the `visibilitySpec` is met.

Despite of the confusion I was complaining about in #5934, I found it's also hard to justify its usefulness given its ambiguity.

It allows you to trigger when page enters into background:
- meantime 50% of the selected element has been visible. 
- meantime the selected element has been visible for a total time of 1s.

However, in both cases, a "visible" trigger with same `visibilitySpec` does pretty much the same thing. 

I hear you say: "wait! the difference is the reported `maxVisiblePercentage` and `totalVisibleTime` values!". True, but the "hidden" trigger doesn't give you the real value you are thinking of either. That's because "hidden" is when page enters background (tap home button on an iPhone), meaning it can be brought back to foreground again, which could further increase `totalVisibleTime` and `maxVisiblePercentage`. And depending on the current user behavior and the spec you configured, the trigger can fire at either the first time it enters background, or the 2nd time, or 3rd time... It's non-deterministic. It's really hard to describe what `totalVisibleTime` you're collecting here.

@dvoytenko @rudygalfi @avimehta

**Comment by lannka** [comment]
To be even more radical, is "hidden" trigger useful in anyway?

**Comment by dvoytenko** [comment]
My recommendation is to get rid of `hidden` trigger and instead use `totals: true` flag in `visibilitySpec` to delay the analytics report until the total numbers are known.

And even then we still need to fully define what this means, e.g. what happens when the document becomes invisible for a short time and then becomes visible again.

**Comment by lannka** [comment]
Talked to ActiveView team. We will keep the "hidden" trigger functionality. As @dvoytenko proposed, we might change the syntax of the spec to reduce confusion.

**Comment by dvoytenko** [comment]
See #8315 for followup.
