### ISSUE TITLE
amp-analytics requires tag name even when selecting by classname

### ISSUE THREAD

**Issue by src-code** [ampproject/amphtml#7656]
Carryover from discussion in #5721 

The visibility spec for `amp-analytics` allows for a selector to be tag name or classname based, however in practice the selector is rejected if the selector does not begin with an `amp-*` tag name.  

I suspect this validation is in place because the feature only works with amp custom components, so it tries to be strict.  However, this prevents one from writing a selector that matches a heterogenous collection of amp components, so it'd be nice if the matcher could simply filter out or warn on non-amp components that match.

## How do we reproduce the issue?

Test case:
http://jsbin.com/qadezulini/1/edit?html,output

Note error in console:

```Visibility spec requires an id selector, a tag name starting with "amp-" or ":root"​​​```

## What browsers are affected?

All browsers

## Which AMP version is affected?

Has always been broken, AFAIK.
Tested with AMP version 1487358851767

**Comment by dvoytenko** [comment]
Fixed via #7655.
