### ISSUE TITLE
Cache modification guidelines for img tag in no script

### ISSUE THREAD

**Issue by dknecht** [ampproject/amphtml#7666]
Previously google re-wrote the img tag attribute of src to point to CDN and longdesc to always be absolute.  This appears no longer be the case.   Is the current behavior correct?

**Comment by honeybadgerdontcare** [comment]
I'm not seeing that the case with src, haven't checked longdesc. Could you point to an example?

**Comment by dknecht** [comment]
I had a test case back from last August.  What is the correct behavior?

**Comment by dknecht** [comment]
@honeybadgerdontcare Or more specifically for the two noscript tags video and img should their be any re-writes in the cache either to origin or to cache. 

* IMG
** src, srcset: re-write absolute to origin 
** longdesc: re-write absolute to origin

* Video
** src: already required to be absolute
** poster: re-write absolute to origin

**Comment by honeybadgerdontcare** [comment]
@dknecht I'm still looking into this and will let you know once I have a definitive answer.

**Comment by honeybadgerdontcare** [comment]
Here's an example of what we're currently doing: https://cdn.ampproject.org/c/astute-city-159523.appspot.com/files/urls.html

To answer your list:
- img
  - src, srcset: rewritten absolute
  - longdesc: currently not being rewritten though may change
- video
  - src: already required to be absolute
  - poster: currently not being rewritten though may change

Also note that `<audio>` and `<video>` can also have children `<source>` and `<track>`. `<source>`'s `src` attribute is being rewritten to absolute, while `<track>` is already required to be absolute.

I've opened an internal b/35679602 to figure out if we'll be changing `<img>`'s `longdesc` and `<video>`'s `poster`. There is also `<amp-facebook>`'s `data-href` and `<amp-user-notification>`'s `data-no-service-worker-fallback-shell-url` that aren't being rewritten either.

**Comment by honeybadgerdontcare** [comment]
We are in the process of changing `<img>`'s `longdesc` to be rewritten absolute. We are also in the process of point `<video>`'s `poster` to be rewritten as an AMP cache URL.

**Comment by honeybadgerdontcare** [comment]
In addition to to `<img>`'s `longdesc` and `<video>`'s `poster` we're also going to rewrite `<amp-install-serviceworker>`'s `data-no-service-worker-fallback-shell-url`. The guidelines are being updated to reflect this and the code to do this in AMP Cache is being submitted concurrently.

**Comment by honeybadgerdontcare** [comment]
For `<amp-facebook>`'s `data-href` the cache won't rewrite the URL.
