### ISSUE TITLE
FOUC amp-lightbox on safari (desktop and mobile)

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#7672]
Lightboxes flash through on page loads. 

Steps to reproduce:

1. Open a new private tab in desktop safari (or mobile safari
2. Load: https://amp-live-list-form.gomix.me/amp-lightbox-flicker.html
=> lightbox visible while page loads

![fouc-lightbox](https://cloud.githubusercontent.com/assets/380472/23116379/29e3cc72-f742-11e6-83f9-ef3f4e7041a9.gif)

**Comment by ericlindley-g** [comment]
Note: Replicable for amp-sidebar as well, so raising priority on this

**Comment by dvoytenko** [comment]
Huh. That's pretty bad. I'm bumping this to P1.

**Comment by camelburrito** [comment]
Happens with sidebar, accordions etc too.

**Comment by cramforce** [comment]
Wow. Filed https://bugs.webkit.org/show_bug.cgi?id=171883

**Comment by dvoytenko** [comment]
Ok. Closing this in preference of https://github.com/ampproject/amphtml/issues/9235. Please continue the discussion there.
