### ISSUE TITLE
amp iframe

### ISSUE THREAD

**Issue by ankit4794** [ampproject/amphtml#7677]
I want to solve this problem in AMP page,

This is the problem that I have:
error.js:120 Origin of <amp-iframe> must not be equal to container

This is my amp-iframe code in my xyz.html:

<amp-iframe
    width=100
    height=100
    layout="responsive"
    sandbox="allow-same-origin allow-forms allow-scripts"
    src="https://www.example.com/abc.php">
</amp-iframe>

why this error is coming?
if i remove allow-same-origin then javascript of abc.php is not working.
how to solve this problem?
please guide me...

**Comment by aghassemi** [comment]
Hi @ankit4794 

Your iframe `src` must be a different origin than your page. For instance if you page is served from `https://mydomain.com/amp/page.html` the `src`  for an iframe in that page **can not** be served from `https://mydomain.com/` and must be of a different origin (e.g. `https://subdomain.mydomain.com/` or `https://totallyDifferentDomain.com/`). 

Please see [Iframe origin policy](https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md) on why AMP enforces this.

Hope this clarifies it. Closing the issue, feel free to reopen if you have more questions.
