### ISSUE TITLE
Some images only load after resizing/rotating screen

### ISSUE THREAD

**Issue by Maeter** [ampproject/amphtml#7685]
When my page has several images (amp-img), a random number of images, starting always for the last one in the DOM, fail to load. The html keeps the amp-img tag, but it is not populated, so it ends up empty until I resize or rotate (on mobile) the screen.

This behaviour is more frequent in mobile browsers than in desktop.

## How do we reproduce the issue?

1. On mobile, Chrome or Safari go to this article: http://brandpunt.kro-ncrv.nl/brandpunt/op-eigen-kracht-henk-van-der-aa-duikt-onder-in-utrecht/

2.  On mobile, Chrome or Safari go to the AMP ready version of the same article: http://brandpunt.kro-ncrv.nl/brandpunt/amp/op-eigen-kracht-henk-van-der-aa-duikt-onder-in-utrecht/

3. You can see that the AMP ready version fails to load several images starting from the bottom of the page.

4. Rotate device, so the screen size changes. Now images are loaded just fine.

## What browsers are affected?

I have been able to reproduce this in both Safari and Chrome, mobile and desktop versions.

## Which AMP version is affected?

Version 1487358851767

**Comment by aghassemi** [comment]
@Maeter Do they never load? AMP prioritizes external resource loading. The images far from the viewport only start getting loaded as they come closer to the viewport (e.g as user scrolls down). I can see the last couple of images in http://brandpunt.kro-ncrv.nl/brandpunt/amp/op-eigen-kracht-henk-van-der-aa-duikt-onder-in-utrecht/ not loaded when I scroll fast to the end but they do eventually load.

**Comment by jridgewell** [comment]
Looks like this is due to the following CSS:

```css
@media (max-width: 1200px) {
  .main {
    height: 100vh;
    min-height: 100vh;
    overflow-y: scroll;
    -webkit-overflow-scrolling: touch;
  }
}
```

Specifically, disabling `overflow-y: scroll` makes pages load as we expect.

AMP doesn't really support scrolling boxes, yet. We plan to work on that this quarter as part of [AMP Layers](https://github.com/ampproject/amphtml/issues/3434).
