### ISSUE TITLE
A4A validator does not allow animation-timing-function property in CSS keyframes

### ISSUE THREAD

**Issue by lexandera** [ampproject/amphtml#7686]
In CSS animations it is useful to have different timing functions assigned to different keyframes in the animation - a bouncing ball animation might use the ease-in timing function on the way down, and ease-out as the ball bounces back up. This is done by specifying the timing function in the keyframe itself.

Because the A4A validator only only allows transform and opacity to be used in keyframes, this means that the only available option is to apply the same easing function to all keyframes, which reduces the ability to create natural looking animations. 

Since having different timing functions across keyframes should not affect rendering performance, it would make sense to add animation-timing-function to the list of allowed properties.

**Comment by dvoytenko** [comment]
/to @Gregable 

We definitely should allow `animation-timing-function` in keyframes. Looks like we just missed it.

**Comment by powdercloud** [comment]
Just to note, this is implemented but not pushed yet.
