### ISSUE TITLE
amp-list: overflow element position is overwritten

### ISSUE THREAD

**Issue by gustavpursche** [ampproject/amphtml#7689]
## Short description of your issue:

According to [the docs](https://www.ampproject.org/docs/reference/components/amp-list), it should be possible to place an overflow button at the end of the list with `position: absolute`. Due to [this change](https://github.com/ampproject/amphtml/pull/7061/files) we had to hack around the specificity, to achieve this, since the overflow-button inherits `position: relative` from `[overflow]` now.

## What browsers are affected?

All browsers

## Which AMP version is affected?

1487358851767

**Comment by aghassemi** [comment]
@gustavpursche Apologies for the non-backward compatible change. We do our best not to introduce breaking changes but sometimes it is hard to evaluate the scope of every change, specially CSS changes.

I will updates the documentation to reflect the need for the CSS override.

**Comment by aghassemi** [comment]
Closing the issue. Documentation is being updated in https://github.com/ampproject/amphtml/pull/7736. Apologies again for the breaking change.

**Comment by gustavpursche** [comment]
@aghassemi Thanks for fixing this so fast! <3
