### ISSUE TITLE
Upgrade document-register-element polyfill to 1.4.1

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#7692]
An important issue for AMP has been fixed in the polyfill version 1.4.1. See https://github.com/WebReflection/document-register-element/issues/96 for details.

**Comment by WebReflection** [comment]
It looks like your greenkeeper has issues with every single PR, not just this polyfill one.

Here the one for [version 1.4.1](https://github.com/ampproject/amphtml/pull/7683)

**Comment by erwinmombay** [comment]
ah darn, its our pr-check that requires a yarn.lock update. I might need to turn it off or patch manually.

**Comment by adelinamart** [comment]
@erwinmombay any updates here? Thanks.

**Comment by erwinmombay** [comment]
Closed by https://github.com/ampproject/amphtml/pull/9840
