### ISSUE TITLE
amp-user-notification: support enctype=application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#7695]
When `enctype=application/x-www-form-urlencoded` is specified, we will use `application/x-www-form-urlencoded` encoding and the appropriate content-type to avoid preflight. All of this scenarios should be initially re-tested however.

This issue is spun off from https://github.com/ampproject/amphtml/issues/4910.

**Comment by jridgewell** [comment]
@dvoytenko: The OP doesn't make sense. Did you mean "we still use `application/json`"?

**Comment by dvoytenko** [comment]
Currently, `amp-user-notification` POSTs with `application/json`, which likely causes the preflight. This default behavior is hard to change at this time, but we could add an attribute `encoding` that could help users switch to `application/x-www-form-urlencoded` and avoid preflight.

**Comment by jridgewell** [comment]
Lol, I kept reading "will" as "still". 😳

**Comment by prateekbh** [comment]
@dvdyakonov: Do we the body in this case to be `FormData` or just `URLEncodedParams` String?
Asking cuz currently allowed body type is either object or array:
https://github.com/ampproject/amphtml/blob/master/src/service/xhr-impl.js#L66
