### ISSUE TITLE
Resources: split main pass into two: complete pass and queue-only pass

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#77]
A lot of work can be avoided if we know that no layout/viewport info has changed.

**Comment by rudygalfi** [comment]
Added "Stale?" label. @dvoytenko Please advise on timeframe.

**Comment by ericlindley-g** [comment]
@dvoytenko Ping?

**Comment by dvoytenko** [comment]
A dupe of #1438.
