### ISSUE TITLE
documentation cleanup: amp-iframe allowpaymentrequest 

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#7701]
https://github.com/ampproject/amphtml/pull/7693 exposes the `allowpaymentrequest` attribute on `amp-iframe`, we should update the documentation in `amp-iframe` reflecting this when:
- [x] Validator changes for https://github.com/ampproject/amphtml/pull/7693 have made it to prod (~2 weeks or so)
- [x] Viewer also allows `allowpaymentrequest` b/35582805

@alanorozco Let's check on these in couple of weeks and see if we can update the documentation at that point.

/cc @ericlindley-g

**Comment by alanorozco** [comment]
lgtm

**Comment by alanorozco** [comment]
Actually, I'm not sure about the validator.

@honeybadgerdontcare?

**Comment by honeybadgerdontcare** [comment]
No this has not made it to production. Time frame is probably in two weeks, maybe three.
