### ISSUE TITLE
Support `layout=nodisplay` for all components

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#7706]
We have some inconsistencies, for instance `amp-anim` supports it while `amp-gfycat` doesn't or `amp-youtube` supports it but `amp-vimeo` doesn't.

I don't see any good reason not to support `layout=nodisplay` on every components, @dvoytenko, WDYT.

**Comment by dvoytenko** [comment]
@aghassemi Do you mean supported in code or validator? Code allows `layout=nodisplay` for all components automatically. Ideally, so would the validator.
