### ISSUE TITLE
Firefox returns null from getComputedStyle

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#7707]
```
TypeError: a.getComputedStyle(...) is null
.f/l.onLayoutMeasure https://cdn.ampproject.org/rtv/001487370849157/v0/amp-ad-0.1.js:72:106
	Tf/b.prototype.updateLayoutBox https://cdn.ampproject.org/rtv/001487370849157/v0.js:160:105
	f.measure https://cdn.ampproject.org/rtv/001487370849157/v0.js:227:104
	ih/< https://cdn.ampproject.org/rtv/001487370849157/v0.js:249:347
	f.measurePromise/</< https://cdn.ampproject.org/rtv/001487370849157/v0.js:241:95
	ah https://cdn.ampproject.org/rtv/001487370849157/v0.js:244:228
	f.gf https://cdn.ampproject.org/rtv/001487370849157/v0.js:243:182
	bound  self-hosted
	Ng.prototype.Ja https://cdn.ampproject.org/rtv/001487370849157/v0.js:221:624
	Ng/this.ve https://cdn.ampproject.org/rtv/001487370849157/v0.js:221:308
	f.delay/< https://cdn.ampproject.org/rtv/001487370849157/v0.js:237:675
```

This is coming from a Firefox browser masquerading as a mobile browser. For some reason, Firefox returns null from `getComputedStyle` inside the iframe (the AMP doc).

To reproduce:

1. Put Firefox into mobile mode with some mobile UserAgent
2. Search [[wikihow tie]](https://www.google.com/search?q=wikihow+tie&ie=utf-8&oe=utf-8)
3. DO NOT CLICK A RESULT
4. Watch error come in (there must be an `<amp-ad>` in the AMP doc, which is likely)

As Firefox isn't our target browser (mobile is, but desktop Firefox masquerading as mobile isn't), 1% should be able to continue.

We'll figure out some internal fix for this on the Google Viewer.

**Comment by jridgewell** [comment]
Tracked internally at b/35640566.

**Comment by adelinamart** [comment]
Adding this one to the hotlist of bugs related to AMP and tracked internally. I'm closing this one and if there are any questions, one can always re-open this.

**Comment by jridgewell** [comment]
Only canary.

**Comment by dvoytenko** [comment]
So, it's benign in PROD?
