### ISSUE TITLE
amphtml-validator don't display an <amp-iframe>'s URL error.

### ISSUE THREAD

**Issue by tea3** [ampproject/amphtml#7710]
I'm using [amphtml-validator@0.1.19](https://github.com/ampproject/amphtml/tree/master/validator/nodejs) .  

There is such an error in Chrome devtools , but it is not displayed in amphtml-validator.

```
Invalid <amp-iframe> src. Must start with https://. Found  

<amp-iframe frameborder=​"0" height=​"400" layout=​"fixed-height" sandbox=​"allow-scripts allow-same-origin allow-popups" src=​"/​/​codepen.io/​tea0828/​embed/​xEOOGQ?height=400&theme-id=light&slug-hash=xEOOGQ&default-tab=result" class=​"i-amphtml-element i-amphtml-layout-fixed-height i-amphtml-layout-size-defined i-amphtml-error i-amphtml-element-error" error-message=​"Invalid <amp-iframe> src. Must start with https:​/​/​. Found amp-iframe&#8203;​&#8203;​&#8203;​" style=​"height:​ 400px;​">​…​</amp-iframe>​
```

https://github.com/ampproject/amphtml/blob/0475c8f86773c52dcb13002daf2610be25faa11c/extensions/amp-iframe/0.1/amp-iframe.js#L67-L70

I think that [this verification function](https://github.com/ampproject/amphtml/blob/0475c8f86773c52dcb13002daf2610be25faa11c/extensions/amp-iframe/0.1/amp-iframe.js#L67-L70) is missing. Can amphtml-validator validate the URL ?

**Comment by Gregable** [comment]
The static validator allows relative URLs here, since it needs to be agnostic to the URL from which the content is served. Runtime can show an error however, because we are aware that the serving URL is over http.
