### ISSUE TITLE
amp-accordion: make it possible for accordion header to also be link

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#7712]
Currently the default behavior for anchor links is prevented when they are in the header of an accordion:

```html
    <amp-accordion>
      <section>
        <h4><a href="www.example.com">Section header</a></h4>
        <p>Bunch of content.</p>
      </section>
   </amp-accordion>
```

Would like to see if it's possible to enable these anchor links

**Comment by MtDalPizzol** [comment]
Any news on this?

**Comment by ericlindley-g** [comment]
Not yet — do you have a particular use case you'd like to make work?

**Comment by MtDalPizzol** [comment]
Well... I'd like to build a multi level navigation menu in which not every first level item have a sublevel and when clicked the page should be submitted..

**Comment by ericlindley-g** [comment]
Great—that exactly the use case we had in mind. Bumping the priority up on this slightly.

FYI: currently you can kind of hack around the limitation here, by absolute-positioning an anchor link on top of part of amp-accordion (so that clicking on the text hovering on top of amp-accordion acts as a link, but clicking elsewhere in the amp-accordion container expands the amp-accordion)
