### ISSUE TITLE
amp-youtube should free resources upon unlayout

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#7720]
### First Timers Only
We know figuring out the process for contributing to an open source project can be intimidating, so we created this issue as a way for you to learn the ropes.  (If you feel comfortable contributing to open source projects, please leave this issue for someone else.)

This particular starter issue is designed to familiarize you with the AMP Code Contribution process and to show-case one of the basic life-cycle events of an AMP component.

### Background
AMP runtime manages the life-cycle of components ensuring they are built, layed-out and garbage collected at the right time to provide stellar performance.

Each element implements their functionality for each life-cycle hook by overriding several `callback` methods such as:
 - `buildCallback`: Called when it is time to initialize a component. 
 - `layoutCallback`: Called when a component is about to come to view. This is where a component does most of its heavy work.
 - `unlayoutCallback`: Called when it is time to tear-down a component to free expensive resources.

A complete list of life-cycle hooks is documented in [Building an AMP Extension document](https://docs.google.com/document/d/19o7eDta6oqPGF4RQ17LvZ9CHVQN53whN-mCIeIMM8Qk).

### Motivation
Currently `amp-youtube` component does not override `unlayoutCallback`. This means resources (such as event listeners and the actual fairly-heavy YouTube iframe) are not freed back to the system.

### The bug
 `amp-youtube` should implement `unlayoutCallback` which:
- [ ] unlistens the `message` listener it registers on window
- [ ] removes the iframe element

`amp-instagram` component has a good implementation for its `unlayoutCallback` and can be used as a reference implementation for this issue.

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review).  Mention `closes Issue #7720` in the description.
- [ ] Assign @aghassemi as the reviewer
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

### Questions?

If you have questions ask in this issue or on your Pull Request (mentioning @aghassemi) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

**Comment by ldthorne** [comment]
Hoping to grab this one per my discussion with @aghassemi. Any objection?

**Comment by aghassemi** [comment]
@ldthorne Thanks!
