### ISSUE TITLE
Make sure amp-analytics is well scoped to embeded document

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#7724]
Sounds like we stepped on a bug: #7619
https://github.com/ampproject/amphtml/pull/7619#issuecomment-281684709

/cc @keithwrightbos

**Comment by rudygalfi** [comment]
@dvoytenko Do you plan to work on this in H1 March sprint?

**Comment by dvoytenko** [comment]
Not likely to be done in H1 March. Other things are more critical in analytics area.

**Comment by dvoytenko** [comment]
Also, how is this different from "extensions analytics" project?

**Comment by dvoytenko** [comment]
Ping on my questions above.
