### ISSUE TITLE
I2I: Introduce amp4ads-identifier as a new meta tag in AMP creative

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#7730]
It looks like:
```
<meta name="amp4ads-identifier" content="doubleclick:1234567">
```
which should be inserted before the script tag of `amp4ads-v0.js`.

It will be mainly used for debugging purpose (for AMP developer to reproduce any issues occurred in a AMP creative).

It could be also useful to get exposed to `amp-analytics` for ad network to collect.

@jasti @michaelkleber

**Comment by dknecht** [comment]
What type of issues is this designed to help debug?  Wouldn't this be available in amp-ad tag?

**Comment by michaelkleber** [comment]
I think the content= value is supposed to be a unique ID associated with this particular ad impression -- a join key to make it easier to correlate any errors with serving logs.

That means that provision of this unique ID wouldn't be done by the proxy (e.g. CouldFlare), but rather by the backend ad provider who chose the ad to serve (e.g. TripleLift), right?

Or maybe we need to allow for multiple of these IDs, in case both parties wanted their own identifier to help track down errors on either side?

**Comment by cramforce** [comment]
@dknecht The point here is that this can only be known after the ad request has returned. We support something like this for 3p ads already.

Love the proposal. Would be great to get this into the standard. Having a standard way to identify creatives would really help debugging and attribution.

**Comment by jasti** [comment]
@lannka  Is it possible to also dedicate a unique id to a creative in addition to an impression (this proposal)? 
Opens up a whole host of things we can optimize at a creative level.

**Comment by lannka** [comment]
@jasti Definitely. We could end up with something like:

```
<meta name="amp4ads-identifier" content="doubleclick-impr-id:xIsjdf921S">
<meta name="amp4ads-identifier" content="doubleclick-creative-id:12345679">
<meta name="amp4ads-identifier" content="some-3p-id:1234567abc">
```

And in amp-analytics we allow collect the ID by
```
https://some-remote-server.com/collect?ad-id=AMP4ADS_IDENTIFIER(doubleclick-creative-id)
```

**Comment by jasti** [comment]
Great. Update please :)
https://github.com/google/amphtml/blob/master/extensions/amp-a4a/amp-a4a-format.md
CC @ampproject/a4a

**Comment by honeybadgerdontcare** [comment]
@lannka why the requirement of it being `inserted before the script tag of amp4ads-v0.js`?

**Comment by lannka** [comment]
@honeybadgerdontcare this is to make sure amp4ads-v0.js can pick it up ASAP.

**Comment by lannka** [comment]
Talking about the format, after some discussions we came into this:
```
<meta name="amp4ads-id" content="doubleclick:impression-id:1234567">
```

Here the `content` attribute has the format of `${vendorName}:${idType}:${idString}`. The vars are all limited to URL Base64 charset.

As for the `${idType}`, we recommend all vendors to have at least two types: `impression-id`, `creative-id`. 

Note everything here is optional (opt-in basis). Having standard naming would enable AMP to provide better debugging infrastructure in future.

@michaelkleber @jasti thoughts?

**Comment by honeybadgerdontcare** [comment]
@Gregable FYI

**Comment by lannka** [comment]
@ampproject/a4a

**Comment by michaelkleber** [comment]
If you want a vendor, id type, and value, then why not just make them each their own field in the markup?  I don't see the benefit of taking three different fields and joining them with colons.  I guess the colon version makes it more optional, but you could just make the individual fields optional also.

**Comment by lannka** [comment]
Ideally we could have our own tag
```html
<head>
  <amp4ads-id vendor="doubleclick" type="impression-id" value="12345">
</head>
```

But having custom tag in `<head>` is invalid HTML5. Chrome browser will move it to `<body>` after parsing. So it does not work.

Sure we can have 
```
<head>
  <meta name="amp4ads-id" vendor="doubleclick" type="impression-id" value="12345">
</head>  
```
But it's sorta semantically incorrect.

I'm fine with either way though. Or you're thinking of other options?

**Comment by michaelkleber** [comment]
I was thinking of your second option.  But whichever syntax you prefer is fine; we can generate them all equally easily.

**Comment by lannka** [comment]
@Gregable @honeybadgerdontcare do you see any problem with the 2nd format? (to see if it fits the general AMP HTML format).

**Comment by honeybadgerdontcare** [comment]
The second format looks fine to me even though it may not be semantically correct. We can then more easily enforce possible values for those fields (e.g. type being either impression-id or creative-id).

Note that your PR #8277 references the first format.

**Comment by lannka** [comment]
Unfortunately, custom attributes in `meta` tag is considered invalid HTML according to [W3 validator](https://validator.w3.org/#validate_by_input). Though we don't necessary follow the standard, it's not a bad if we can.

@Gregable suggested to use the standard comma separated key-value pairs, which is already supported by the validator.
```html
<head>
  <meta name="amp4ads-id" content="vendor=doubleclick,type=impression-id,value=12345">
</head> 
```

I think it's a good idea, and I will just go with this approach.

**Comment by honeybadgerdontcare** [comment]
@lannka SGTM, and yes validator supports that format already: https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii#L443
