### ISSUE TITLE
amp-selector selection does not mutateElement

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#7746]
amp-selector selection does not mutateElement

Which means - any thing (ex amp-img) that is hidden in the selector that could be displayed after a selection has been made does not render on screen

**Comment by camelburrito** [comment]
CC @dvoytenko

**Comment by dvoytenko** [comment]
Sorry, I don't quite get it. Does amp-selector start hidden? Why would it be hidden?

**Comment by camelburrito** [comment]
so if we implement something like this

https://jsbin.com/xelayuyoc

 and the content has say some images (or any amp components), they don't get rendered.

I had to use visibility hidden on the tabcontent to overcome this.
Ideally every time a selection is made ampSelector will have to do the changes in a this.mutateElement.

**Comment by dvoytenko** [comment]
@camelburrito I'm getting 404 on this page. Can you please send an updated URL?

**Comment by camelburrito** [comment]
https://jsbin.com/xelayuyoci
