### ISSUE TITLE
amp-embed displays amp-ad loading placeholder

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#7752]
`amp-embed` is displaying the new `amp-ad` loading animation.  Since they are semantically different (`amp-embed` is theoretically not an ad) this is incorrect.

**Comment by lannka** [comment]
Good point. Let's get it fixed.

**Comment by jasti** [comment]
Actually disagree. 
At least all embed so far are technically advertising. (Any placement that an advertiser has paid for is considered an ad). The two embeds listed are paid embeds. https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad/amp-ad.md#supported-embed-types

Wouldn't want this to be a loophole :)

**Comment by jpettitt** [comment]
Embeds are a weird hybrid.  They behave like ads but sometimes contain internal link recirculation. It just seemed odd to me that amp goes to the trouble of calling them something different in the code for essentially political reasons and then applies a loading indicator that ignores that difference.

**Comment by jasti** [comment]
I think if there is ever a 3P submission which has a non-ad embed, we should consider removing the ad loading indicator. Just that, so far, the companies that have added support are all ads based. 
What was the political reason to add that distinction? @cramforce do you know?

**Comment by cramforce** [comment]
I think removing the indicator is fine.

We should not allow `amp-embed` for things that are really just ads. It is a whitelist. I know it is a grey area.

**Comment by jpettitt** [comment]
@jasti we have a 3p `amp-embed` in the works that will not be just an ad.
