### ISSUE TITLE
Support HTML5 `hidden` attribute globally on all amp elements. 

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#7753]
Currently validator does not allow HTML5 `hidden` attribute on AMP Elements. It should.

`hidden` attribute was added in HTML5 to separate layout (display) from visibility. Mixing `layout` and `visibility` has caused pain in the past making it very hard to write functions such as `show(elem)`. These problems arise from the fact that an element which is initially hidden with `display:none` can not specify its ultimate display layout anymore, so a generic method such as `show(elem)` can not work for all cases without requiring the caller to specify what layout to go to after removing `none` from `display`.

With the introduction of `hidden`, now an element can specify its display layout independent of its current visibility. Therefore a generic `show(elem)` becomes as simple as removing `hidden` attribute,

We should:
- [x] Add `hidden` as a globally white listed attribute similar to `class`
- [ ] Ensure runtime handles `hidden` properly (e.g. does not layout elements that have it)

Related to https://github.com/ampproject/amphtml/issues/7027

**Comment by dvoytenko** [comment]
@aghassemi Validator change is definitely good. But question: do we need to polyfill `hidden` attribute? Is it supported everywhere we need?

**Comment by aghassemi** [comment]
@dvoytenko I don't think we need to polyfill, [support](http://caniuse.com/#feat=hidden) is wide-spread.
