### ISSUE TITLE
Custom slider w/ amp-bind

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#7765]
Copied from thread:

So we already support the "change" event in AMP actions, we just need a bit extra to pass the slider value to amp-bind.

E.g. <input type="range" on="change:AMP.setState(myValue=event.value)">

`event.value` is the part that doesn't work yet, but should be straightforward to add.

/cc @choumx

**Comment by ericlindley-g** [comment]
passing to @choumx

**Comment by rudygalfi** [comment]
Where is the sample tracking happening? We got a request for this during AMP Roadshow Europe.

**Comment by ericlindley-g** [comment]
Here's the sample-tracking project: https://github.com/ampproject/amp-by-example/projects/1 — I've added a note to the specific request

/cc @lswang1618 for visibility
