### ISSUE TITLE
Provide remote.html type ad request enhancement for amp-ad when using fast fetch

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#7772]
In slow fetch 3P amp-ad request scenario, publishers used the remote.html approach to enhance ad requests with cookie information. Since fast fetch is all XHR based, this approach will not work.  This feature is to allow publishers to decorate an ad request typically for operations like reading their own cookies from another domain or the same domain and update the ad request before sending to the ad server.
CC @lannka

**Comment by dknecht** [comment]
Would non-fast fetch amp-ads still use remote.html?

**Comment by keithwrightbos** [comment]
For Adsense and Doubleclick, ideally no otherwise a publisher would need to
potentially maintain both remote.html and new the implementation in order
to ensure parity.

**Comment by jasti** [comment]
Assigning to @tdrl  & @keithwrightbos since they are leading the design.

**Comment by keithwrightbos** [comment]
See i2i: #8551
