### ISSUE TITLE
Scope Bind service for embeds

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#7779]
`Bind` service should implement `EmbeddableService` and provide scoping for embeds.

The goal is to isolate states and state mutations between a main document and an embed. E.g. an embed cannot read or mutate the state in the main doc or another embed.

Few services, such as `Action` and `StandardActions` support this kind of scoping.

**Comment by choumx** [comment]
- Test on `/a4a/`, e.g. http://localhost:8000/a4a/examples/article.amp.max.html
- Urgency depends on timeline of `amp-bind` in A4A

**Comment by choumx** [comment]
Bumping to backlog since `amp-bind` in A4A is non-urgent.
