### ISSUE TITLE
Amp access authentication request not fired when in PWA with shadowdom

### ISSUE THREAD

**Issue by bjalford** [ampproject/amphtml#7780]
When loading in an AMP doc which has amp-access in it into a PWA using shadowdom, the auth request isn't being fired and so the form doesn't render.

**Comment by dvoytenko** [comment]
Correct. We haven't yet enabled AMP Access in PWA. We'd like to get more information on the right embedding rules in this case. Typically, a PWA would have it's own access mechanisms and we'd like to make sure that we are not interfering with them.

@bjalford Could you describe your use case?

**Comment by bjalford** [comment]
@dvoytenko It's mainly for the comments which we use Gigya for. The idea was to build the auth using amp-access and then users would be logged in whether visiting AMP or PWAMP. For browsers that support service workers they will go from AMP to PWAMP, but other browsers are always get AMP for the first page of a session and then get PWA after first click.

**Comment by dvoytenko** [comment]
Does Gigya has its own identity system/login? Do you share it with them? Could you provide a bit more detail on this? Does it work more like Facebook comments?

**Comment by bjalford** [comment]
Yes it does. And an API. We've implemented it and it works well in AMP but not through the shadowdom as yet.

**Comment by dvoytenko** [comment]
I've scheduled it for Design Review tomorrow (#7903).

**Comment by dvoytenko** [comment]
@bjalford Please join if you can.

**Comment by bjalford** [comment]
Sorry managed to mess up my timings last week (facepalm) Can't make today either. Keen to discuss though. How can we move forward?

**Comment by dvoytenko** [comment]
Yes. We are moving forward with this.

**Comment by dvoytenko** [comment]
Just heads up. It looks like the fix is in PROD now. PTAL.
