### ISSUE TITLE
Multiauthor website with Adsense conditioned to author ID

### ISSUE THREAD

**Issue by Gurgusondo** [ampproject/amphtml#7782]
Hi,
We are having an issue implementing Adsense in the APM version of our website. We have a share revenue multiauthor website linked to an Adsense Channel (just one). And each author is identified with a different ID within the add. So each add block is conditioned to an author ID.
This is the script we use for Adsense in our website:

<?php
$author = get_the_author();
if ($author == "XXXXX"){ ?>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<ins class="adsbygoogle"
style="display:inline-block;width:320px;height:100px"
data-ad-client="ca-pub-000000000000"
data-ad-slot="0000000000"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
<?php } else if ($author == "XXXXXX") { ?>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<ins class="adsbygoogle"
style="display:block"
data-ad-client="ca-pub-XXXXXXXX"
data-ad-slot="XXXXXXXX"
data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
<?php } ?>

We wonder if there is any parameter in AMP we can add to have our Adsense adds conditioned to the author. The code we found for Adsense in AMP is the following one:

`<amp-ad
layout="fixed-height"
height=100
type="adsense"
data-ad-client="ca-pub-XXXXXXXXXXX"
data-ad-slot="XXXXXXXXX">
</amp-ad>`

But it doesn´t allow to have our Adsense ads conditioned to our authors.
How can we implement this conditioned parameter with AMP? We know there are other parameters likes:
- data-ad-host
- data-ad-test
- data-tag-origin

But we do not know if any of them can be used for this purpose or how.

Thank you

**Comment by jasti** [comment]
@konakk, can you take a look please?

**Comment by konakk** [comment]
Are you looking to add channel id? If you could have a field for channel id would that be enough for your use case?

**Comment by jasti** [comment]
Closing since there hasn't been a response in a while. Please reopen if you'd like to continue the discussion.
