### ISSUE TITLE
Expose navigation action

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#7786]
```
<button on="tap:AMP.navigateTo(url, opt_target)">
```

All the replacement rules and restrictions that happen to `href` on `a` should also apply here.

**Comment by aghassemi** [comment]
Closing in favour of https://github.com/ampproject/amphtml/issues/8515

**Comment by dandv** [comment]
See also [Support AMP.goToURL action](https://github.com/ampproject/amphtml/issues/8976)
