### ISSUE TITLE
Intent to implement: amp-graphiq

### ISSUE THREAD

**Issue by src-code** [ampproject/amphtml#7787]
I'm working on a new AMP component to support [Graphiq embeds](https://www.graphiq.com).  A sample embed looks like:

https://w.graphiq.com/w/dUuriXJo2qx?data-height=512&data-width=600

## Proposed API

```html 
<amp-graphiq
    data-widget-id="dUuriXJo2qx"
    data-href="https://example.com/more/details/url" 
    width="600"
    height="512"
    layout="responsive">
</amp-graphiq>
```  

The only required attribute will be `data-widget-id`.  

`height` and `width`, if provided, will be passed through to the widget url in order to set an initial dimension for the widget. (See above sample widget url.)  The widget will resize itself as necessary, however, and the component will auto-resize its height based on postMessages received from the embed's iframe.

Default value for `data-href` will be a link to the expanded view of the widget on Graphiq's site (eg https://www.graphiq.com/vlp/dUuriXJo2qx);  

(Note: I'm not working with Graphiq on this one, but just have a need to get these embeds supported in AMP.)

**Comment by ericlindley-g** [comment]
This looks great to me — @aghassemi , do you have any feedback on this plan? Really excited to get some nice data viz support in AMP.

And just a heads up, @src-code , that resize rules should work according to the general AMP approach for resizing: can resize only if it's outside of the current viewport or has been triggered by user interaction.

**Comment by aghassemi** [comment]
LGTM!

**Comment by src-code** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Great!  I've got this ready to go, and will submit a PR when I'm back from vacation.

**Comment by ericlindley-g** [comment]
Closing this based on activity in the PR, but feel free to re-open if anything changes, or if there's an alternate path forward
