### ISSUE TITLE
PROD - TypeError: undefined is not an object (evaluating 'id(a).renderStarted') (anonymous function)

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#7803]
Looks like this PR is causing the error,
Initial load analytics event (#7312)

Not sure of severity lower as needed.

MAC Os - Safari

**Comment by camelburrito** [comment]
<img width="1172" alt="screen shot 2017-02-26 at 12 51 56 am" src="https://cloud.githubusercontent.com/assets/1037311/23338384/5a2c2eb2-fbbe-11e6-9477-8f3d02f8b3d6.png">

**Comment by dvoytenko** [comment]
This looks like an unrelated error due to the same-origin iframes that are prohibited by `amp-iframe`.

**Comment by jridgewell** [comment]
Closed by #7821?

**Comment by amphtml-team** [comment]
No. Mostly unrelated...

**Comment by jridgewell** [comment]
Then is this a dupe of 7804?

**Comment by dvoytenko** [comment]
Agree. It's a dupe. I'll close this one.
