### ISSUE TITLE
about web font Resource validation

### ISSUE THREAD

**Issue by techhtml** [ampproject/amphtml#7805]
## web font resource validation
Now on days we can use `//fonts.googleapis.com/earlyaccess/notosanskr.css` link,
but AMP validation only allow `https://fonts.googleapis.com/earlyaccess/notosanskr.css`

If does not have any other reason, i think will can use `//fonts.googleapis.com/earlyaccess/notosanskr.css`.
Please take a look.

**Comment by aghassemi** [comment]
@techhtml AMP only loads external fonts from secure origins. Even if we supported scheme-relative, we would have still rewritten it to point to https version of the resource. For now, instead of rewriting, we require the urls to be https to be more explicit.
