### ISSUE TITLE
Add documentation for shadow API

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#7807]
To aid in the upcoming AMP Conf workshop about "PWAMP", we should have some simple documentation about `AMP.attachShadowDoc` and other APIs in `shadow-v0.js`.

/cc @bpaduch @dvoytenko

**Comment by bpaduch** [comment]
Already documented in new PWA Guide - https://www.ampproject.org/docs/guides/pwa-amp/amp-in-pwa#use-the-shadow-amp-api-to-render-a-page-inline
