### ISSUE TITLE
Regression in pre-render metrics

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#7815]
#7312 regressed our pre-render perf metrics (at least I think that is what happened).

Was this intended? Is there maybe a bug?

**Comment by dvoytenko** [comment]
It's not likely to be #7312. It'd more likely reduce time for prerender, not increase.

**Comment by cramforce** [comment]
Do you have an idea what in https://github.com/ampproject/amphtml/releases/tag/1487370849157 could cause it?

**Comment by cramforce** [comment]
We don't pass the in-prerender arg here https://github.com/ampproject/amphtml/blob/master/src/service/performance-impl.js#L199

The old code didn't do that either, though. In any case this is wrong.

**Comment by cramforce** [comment]
This, by the way, explains the differences in measurement volume, because many pages never resolve all the promises in prerender

**Comment by dvoytenko** [comment]
Not yet. Really not seeing how this could be affected in pre-rerender. And, you are right, the prerender flag is not passed and that's erroneous.

**Comment by cramforce** [comment]
CC @lannka @erwinmombay in case they have ideas.

**Comment by dvoytenko** [comment]
Regression has been fixed by ignoring non-prerenderable content.
