### ISSUE TITLE
AMP demo HTML code does not validate

### ISSUE THREAD

**Issue by nonproftechie** [ampproject/amphtml#782]
The HTML code provided on the front page of this project won't validate.

**Comment by nonproftechie** [comment]
![image](https://cloud.githubusercontent.com/assets/13720633/10807216/26ffa07e-7dab-11e5-9b89-080234432089.png)

**Comment by nonproftechie** [comment]
My source code, in case you need it.  I believe the only difference was the canonical tag:
```html
<!doctype html>
<html ⚡>
  <head>
    <meta charset="utf-8">
    <link rel="canonical" href="index.php" >
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <style>body {opacity: 0}</style><noscript><style>body {opacity: 1}</style></noscript>
    <script async src="https://cdn.ampproject.org/v0.js"></script>
  </head>
  <body>Hello World!</body>
</html>
```

**Comment by dvoytenko** [comment]
Thanks for the report! The validator is a bit behind. We recently relaxed viewport values here https://github.com/ampproject/amphtml/issues/592. This is the correct `viewport` value and it will be reported as such by the validator very soon.

**Comment by cramforce** [comment]
The JS error is, however, pretty worrying.

What Chrome version is this? Could you expand the stack trace?

**Comment by nonproftechie** [comment]
Thanks @dvoytenko!  I'm excited about this project!  @cramforce, I will give you the Chrome version and expanded stack trace momentarily.

**Comment by cramforce** [comment]
Also: We'll soon have public docs that won't trail the release validator. Its kind of temporary situation now :)

**Comment by nonproftechie** [comment]
@cramforce, here is the stack trace shown when I hit the expand arrow:  
![image](https://cloud.githubusercontent.com/assets/13720633/10807342/84082a6a-7dac-11e5-9720-8bd9bd89c6aa.png)

My Chrome version is 46.0.2490.80 (64-bit) running on Mac OS X El Capitan.

**Comment by erwinmombay** [comment]
content.js, doesnt seem like our script anyways.

**Comment by nonproftechie** [comment]
I think it's part of the WebKit engine in Chrome itself, but I may be wrong.

**Comment by cramforce** [comment]
Ah, some random Chrome extension likely. They are the root of all evil.
