### ISSUE TITLE
amp-form has to be in ampdoc level, not window

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#7823]
Currently, `amp-form` is instrumented on the window object. Instead, it should use `AMP.registerServiceForDoc()` and thus be declared on the ampdoc-level to avoid doc-to-doc collisions.

**Comment by aghassemi** [comment]
@cvializ @ericlindley-g Can this take over https://github.com/ampproject/amphtml/issues/6219 ?
