### ISSUE TITLE
Set history.scrollRestoration to manual

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#7835]
We set viewport `scrollTop` to adjust scroll due to size changes. However browser history scroll restoration api can also adjust scroll positions and mess up with our efforts to avoid page jump. 

> >>scroll positions are stored and then, more importantly, restored whenever you traverse the history. This often means unsightly jumps as the scroll position changes automatically, and especially so if your app does transitions, or changes the contents of the page in any way. Ultimately this leads to an horrible user experience.

from [https://developers.google.com/web/updates/2015/09/history-api-scroll-restoration](url)

As @dvoytenko suggested we can set `history.scrollRestoration` to `manual`. However I can't find where we are taking ownership of setting scroll position when traverse history. Is it safe to add `history.scrollRestoration = 'manual'`?
@dvoytenko

**Comment by amphtml-team** [comment]
It'd be fine to set it in the viewport constructor. But let's first confirm
if it works.

**Comment by zhouyx** [comment]
I tried setting it in viewport constructor. It fixed the unexpected page jump. However with `history.scrollRestoration = 'manual'`, scroll position will always be 0 when I refresh (go back/forward ...) the page. Is it fine to ignore the behavior change?

**Comment by dvoytenko** [comment]
We definitely cannot do this for single-doc case. But we should be ok to do this for iframe'd case.
