### ISSUE TITLE
Create A4A sample for ad with video

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#7840]
With https://github.com/ampproject/amphtml/issues/649, https://github.com/ampproject/amphtml/issues/7027 and https://github.com/ampproject/amphtml/issues/6198 now merged we should be able to create A4A ads that look and behave like this prototype: https://output.jsbin.com/fomotodeye 

We should cleanup and convert https://output.jsbin.com/fomotodeye to A4A and put it as a sample under https://ampbyexample.com/#amp_ads 

/cc @jasti @alanorozco @sebastianbenz

**Comment by aghassemi** [comment]
(probably with better media assets, image is NYC but video is Tokyo :smile:)

**Comment by jasti** [comment]
This is awesome!
Question: Are we able to overlay assets on top of the video asset? Something along the lines of "click here to learn the more" type of things which send user to landing page

**Comment by aghassemi** [comment]
@jasti yeah definitely. The X and pause/play buttons are custom overlays so similar to those a "learn more" can be overlayed on top as well.

**Comment by alanorozco** [comment]
https://github.com/ampproject/amp-by-example/pull/702
