### ISSUE TITLE
Carousel next/previous icons fade away on desktop and then reappear immediately

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#7845]
We don't hide the next/previous icons for carousel on Desktop by design but currently they first fade-away and then reappear immediately. 

Looks like a regression

**Comment by muxin** [comment]
@aghassemi What do you mean by reappear immediately? Does the reappearance happen when you scroll down the page and scroll up back to the carousel position?

**Comment by aghassemi** [comment]
@muxin They just start fading and after they are hidden, the become visible again. They should not fade at all in the first place.

(Updating to P3, don't really think this is P2)

**Comment by muxin** [comment]
According to @camelburrito, if there's no `controls` attribute in the `amp-carousel`, the arrows will only be shown for a short time for hinting purpose, indicating the carousel is swipable. Every time the carousel come into viewport, the arrows will show again for hinting, but will fade afterwards.

**Comment by muxin** [comment]
@aghassemi Are you saying the arrows reappear without swiped out and then in the viewport?

**Comment by aghassemi** [comment]
@muxin This issue is only about "**Desktop**". On desktop (where there is no swipe), next/prev should always be visible and should not fade away.
