### ISSUE TITLE
AMP_Img_Sanitizer, heavy query on wp_postmeta

### ISSUE THREAD

**Issue by DrLightman** [ampproject/amphtml#7847]
My database suffers a bit with this kind of query that it seems related to AMP_Img_Sanitizer:

`SELECT post_id FROM wp_postmeta WHERE meta_key = '_wp_attached_file' AND meta_value = '2001/01/foo.jpg' `

These queries are  frequent and take about half second on a 4mil rows table when my site is not on heavy traffic.

Do you think it could be somehow avoided?

**Comment by DrLightman** [comment]
Is this the correct way to remove the filters of the extractor that executs the heavy query?

```php
function amp_no_extract_image_dimensions()
{
    remove_filter('amp_extract_image_dimensions', array('AMP_Image_Dimension_Extractor', 'extract_from_attachment_metadata'));
    remove_filter('amp_extract_image_dimensions', array('AMP_Image_Dimension_Extractor', 'extract_by_downloading_image'));
}
add_action('amp_extract_image_dimensions_callbacks_registered', 'amp_no_extract_image_dimensions');
```

**Comment by jalajc** [comment]
@DrLightman Are you are referring to [Wordpress' plugin for generating AMP pages](https://github.com/Automattic/amp-wp) via php/mysql.

If this is the case indeed, you might want to raise this in [wordpress AMP repo](https://github.com/Automattic/amp-wp) to address your question appropriately by Automattic (wordpress author) team and close the

**Comment by DrLightman** [comment]
Oh sorry I posted in the wrong repo. :(
