### ISSUE TITLE
User error reported as dev error: base cid

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#7852]
Seeing this error happened in default-cdn-1p-canary error log. This is [timeout error for base cid](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/cid-impl.js#L327) from [`user.createError`](https://github.com/ampproject/amphtml/blob/master/src/service/timer-impl.js#L141). I thought this should be a user error. Maybe it's related to [this](https://github.com/ampproject/amphtml/pull/7726/files#diff-4f24bb7c46eda8f63690cb849ddb0f2dR390)?
```
Error: base cid
    at pa (https://cdn.ampproject.org/rtv/001487969065964/v0.js:9:358)
    at na.f.createError (https://cdn.ampproject.org/rtv/001487969065964/v0.js:6:36)
    at https://cdn.ampproject.org/rtv/001487969065964/v0.js:241:285
    at https://cdn.ampproject.org/rtv/001487969065964/v0.js:240:675
```

@dvoytenko

**Comment by muxin** [comment]
Seeing this in current [canary](https://github.com/ampproject/amphtml/releases/tag/1487969065964) only

**Comment by cramforce** [comment]
CC @lannka

**Comment by muxin** [comment]
```
return timerFor(ampdoc.win).timeoutPromise(10000, cidPromise, 'base cid')
        .catch(error => {
          dev().error(TAG_, error);
          return undefined;
        });
```
The code is dev error but for some reason it's not reported as dev error before. In the new canary this is reported as dev error, emerging in the error report.
But we should keep it as user error, not change the error type thrown from `timeoutPromise`.

**Comment by cramforce** [comment]
I think these should be expected dev errors, no? We want to see when they
go up in quantity.

**Comment by dvoytenko** [comment]
This was originally a user error that got re-classified accidentally as a dev error. Should be fixed now.

**Comment by jridgewell** [comment]
I think expected dev error, too.
