### ISSUE TITLE
Reflect AMP_CONFIG experiment state on experiments page

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#7890]
The page on https://cdn.ampproject.org/experiments.html should reflect the AMP_CONFIG based experiment configuration

- Download https://cdn.ampproject.org/v0.js
- parse out AMP_CONFIG
- mark default-on experiments as `on by default` and disable the button

CC @dvoytenko, @rudygalfi

**Comment by erwinmombay** [comment]
this makes sense.

also probably on the internal `promote` script when we flip flags the html would be stale as we don't rebuild experiments.html

**Comment by cramforce** [comment]
Was thinking to reflect the actual live state, independent of publishing the experiments file.

**Comment by erwinmombay** [comment]
@cramforce oh gotcha, so write some js to read and extract the actual live config.

**Comment by cramforce** [comment]
Yeah, exactly.

Results would also depend on whether you are in dev channel or not.
