### ISSUE TITLE
doubleclick JSON ad param categoryExclusions not copied when targeting param absent

### ISSUE THREAD

**Issue by crusaderstar** [ampproject/amphtml#7900]
[Here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad-network-doubleclick-impl/0.1/amp-ad-network-doubleclick-impl.js#L212) A4A declines to fill the "scp" param if the tag's JSON lacks the "targeting" param, without looking at the "categoryExclusions" param.  However, GPT documentation [here](https://developers.google.com/doubleclick-gpt/gpt_light) suggests that "categoryExclusions" can indeed be alone in the JSON.

The fix is to fill "scp" with "categoryExclusions" if it's present, even in "targeting" is absent.  This isn't a large issue since users are supposed to set category exclusions in the DFP UI as explained [here](https://support.google.com/dfp_premium/answer/3238504?hl=en).

**Comment by jridgewell** [comment]
Fixed by #7843.
