### ISSUE TITLE
Cached page loads as if scrolled to page bottom and scrolling is disabled

### ISSUE THREAD

**Issue by daveboehm** [ampproject/amphtml#7904]
Our landing page loads showing the footer as if the user had scrolled to the bottom of the page. You are unable to scroll up or down, however the few links that are visible still work. This is specific to Chrome on iOS. Emulators and all other browser/OS combinations do not reproduce the issue, including browserstack. Additionally, this only happens when visiting the cached page, not our hosted link. 

There are no console errors and AMP validation passes on our hosted link, but there is no way (that we're aware of at least) to inspect Chrome on iOS to verify if this is the case where we find the issue.

## How do we reproduce the issue?

1. On a physical iPhone using Chrome browser, visit https://www.google.com/amp/s/www.creditcards.com/amp/reviews/      (note again that browserstack and emulators do not reproduce this issue)

## What browsers are affected?

Chrome on iOS (tested in-house on iPhones 6 and 7)

## Which AMP version is affected? Is it a new issue?

We load:  https://cdn.ampproject.org/v0.js (unchanged since launch in early February)
We discovered this bug roughly 2 weeks ago (mid February 2017), but cannot confirm exactly how long it's existed.

Curious if anyone has experienced this before and/or has ideas how we can resolve it. Google AMP tech support directed us here, so it can't be a known or common fix unfortunately.

**Comment by aghassemi** [comment]
/to @muxin to investigate. iOS/Chrome scroll freeze issue.

**Comment by muxin** [comment]
@daveboehm It might be related to https://github.com/ampproject/amphtml/issues/7653. But I'm not entirely sure. Let me solve that bug first and test again.

**Comment by muxin** [comment]
I tested using the code from #7653 and it fixed the problem! @daveboehm Please wait for #7653 to be merged. Then normally it will be in canary in one week and in prod in two weeks.

**Comment by daveboehm** [comment]
Thank you @muxin this is great news!
