### ISSUE TITLE
Data fetch for amp-bind on page load

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#7907]
I think we should allow fetching fresh page data for amp-bind on page load.

This would **NOT** actually trigger an amp-bind render, but it would, for example, allow us to provide fresh availability once a user selects a size or a hotel room they'd like to book.

CC @ericlindley-g

**Comment by ericlindley-g** [comment]
This sounds really promising.

Just so I understand, let's say the feature means:

Implement a mechanism that fetches data from source (A) and uses the response to update document data (B)

Questions:

1.
Is the source (A) just the host document (cache if served from the cache, origin if served from the origin), or could it be configured to be any URL of the publisher's choosing? (i.e. fetch the latest data from origin, even when served from the cache, or even fetch from a JSON endpoint)

I believe the biggest benefit will be from getting fresh data from the origin, but I suppose that could also cause unwanted traffic to the origin even when there isn't new data. Maybe we make the default to fetch from the host document, with the option to configure an arbitrary URL as the endpoint (as long as we can be sure that the response couldn't violate validity expectations). Or a mechanic where it checks the age of the host document (if served from the cache), and hops to the origin if the host document is older than some threshold?

2.
What document data (B) would be open to update? Would this just be open to arbitrary content in the configuration in `amp-state`?

**Comment by cramforce** [comment]
I meant this to be only a request directly to the origin server that serves pure JSON. No document involved.

**Comment by cramforce** [comment]
@erwinmombay This is the issue we discussed yesterday.

**Comment by erwinmombay** [comment]
@cramforce thanks

**Comment by choumx** [comment]
#8322 suggests that the XHR mechanism should support the batching that was recently added to `amp-list`. We should share code where possible.
