### ISSUE TITLE
Viewer integration: rewrite error message to indicate request name

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#7909]
Currently, we do this for errors:

https://github.com/ampproject/amphtml/blob/master/extensions/amp-viewer-integration/0.1/messaging.js#L291

The request is to make the error message a bit more descriptive. I.e. 

```
Request "${request.name}" failed: ${error}
```

That does mean that `waitingForResponse_` should store request name.

**Comment by chenshay** [comment]
https://github.com/ampproject/amphtml/pull/7923
