### ISSUE TITLE
Expected width to be available and not equal to "auto":  null

### ISSUE THREAD

**Issue by cypherlou** [ampproject/amphtml#7915]
Hi, apologies if this has been raised. I've had a quick scan here and on SO without success.

I have an amp-carousel of `type="carousel" layout="fixed"`. This renders exactly as required, however, the element is reporting that `Expected height to be available:  null`. 

I see from the documentation that the height is required (although the component renders perfectly well without it) and adding an arbitrary `height="600"` results in the component rendering as before, i.e. the `height` attribute has no obvious effect on the component, which is agreeable.

This however, then results in and error saying `Expected width to be available and not equal to "auto":  null`, which is most unfortunate as the width of the component is not know at the time of rendering, setting it directly or with the use of media queries is suboptimal results and an undesirable outcome.
I note also that the documentation makes no mention of the fact that the width is required at any point, as far as I can make out.

**Outcome with width set.**
<img width="463" alt="test_page" src="https://cloud.githubusercontent.com/assets/6726981/23485399/2925fc36-fed3-11e6-9e90-e72a8d63f508.png">

**Outcome without width set.**
<img width="484" alt="test_page" src="https://cloud.githubusercontent.com/assets/6726981/23485436/515332f0-fed3-11e6-8fb2-9f1a62450a01.png">

The absence of the width results in the Google map drawing at the desired size as defined by the sourceset and the additional content to the right of the first entry is partially visible, encouraging the user to scroll the content left and right, as desired.

Ordinarily I might be tempted to leave this error as is as it is not having a material affect on the user experience, however, the client is insisting on a fully validated site.

Any support welcome.

**Comment by aghassemi** [comment]
@cypherlou If `width` is unknown, please use `layout=fixed-height` and only set `height` attribute. The `Expected width to be available and not equal to "auto": null` will go away when setting `layout=fixed-height` 

Hope this helps, closing the issue, feel free to reopen if you have follow up questions or run into other issues

**Comment by cypherlou** [comment]
@aghassemi, thanks for the feedback as it has removed the errors.
