### ISSUE TITLE
The mandatory text (CDATA) inside tag 'noscript > style[amp-boilerplate]' is missing or incorrect

### ISSUE THREAD

**Issue by phuduc88** [ampproject/amphtml#7919]
Hi all,
I have issue, when  i check html on https://validator.ampproject.org/
   `<script src="http://localhost:57658/Scripts/jquery.min.js"></script>`
show error : The tag 'script' is disallowed except in specific forms.

Please help me.

**Comment by bjalford** [comment]
A couple of things:

1) Have you included the AMP boilerplate CSS as specified in the docs - bottom of Required mark-up section here: https://www.ampproject.org/docs/get_started/create/basic_markup

2) Are you including the jquery script on the AMP page. This is not valid in AMP so you'll have to remove if you want the AMP page to pass validation.

**Comment by aghassemi** [comment]
@phuduc88 as @bjalford mentioned, AMP does not support custom JavaScript in the page. If you need widgets that require custom JavaScript, they must be hosted as separated pages and embedded with `amp-iframe`
