### ISSUE TITLE
Allow embeds to request AMP page to scroll to top

### ISSUE THREAD

**Issue by SnakeME** [ampproject/amphtml#7920]
We have embedded an iframe in our AMP site with an height which is larger than the screen size of the mobile device. When the user clicks on an button at the end of the iframe, the content at the top of the iframe changes. The content which is now displayed at the top of the iframe is invisible to the user because the viewport is still at the end of the iframe. Is it possible to send an event like the embed-size postmessage event to the parent to scroll at the top of the iframe?

Maybe something like:
window.parent.postMessage({
  sentinel: 'amp',
  type: 'embed-scroll',
  value: 'top'
}, '*');

**Comment by aghassemi** [comment]
@SnakeME Not a supported feature AFAIK. Changing your issue into a feature request.

/cc @ericlindley-g

**Comment by ericlindley-g** [comment]
@SnakeME This sounds reasonable, as long as it's triggered by user action — do you have an example page where this is being used, to get a sense of the use case?

**Comment by aghassemi** [comment]
We _might_ be able to detect that the request is tied to a user action and only honour it in such cases. @dvoytenko did some investigating into detecting user intent a while back and I know user intent carries over iframe boundaries via postMessage

**Comment by dvoytenko** [comment]
We are trying to solve this problem in browser spec via https://bugs.chromium.org/p/chromium/issues/detail?id=621631 and https://github.com/whatwg/html/issues/1983

We can polyfill this kind of check via copy/paste API, but it's, of course, very clunky and has a "less-than-ideal" UX.

**Comment by aghassemi** [comment]
https://github.com/ampproject/amphtml/issues/9074 would allow this. deduping.
