### ISSUE TITLE
Instructions for Integrating ad networks into AMP

### ISSUE THREAD

**Issue by klall33** [ampproject/amphtml#7935]
I am attempting to follow the developer guidelines below to create a new extension:
https://github.com/ampproject/amphtml/blob/master/ads/README.md#developer-guidelines-for-a-pull-request

I followed the steps and started a local gulp web server by running command gulp after creating my ad extension.

Then I visited http://localhost:8000/examples/ads.amp.max.html?type=33across

However, I always seem to get the following console message in Chrome:

```
Type "33across" is not supported in amp-ad
Ad @ error.js:128
f.assert @ log.js:301
push.f.l.buildCallback @ amp-ad-3p-impl.js:127
Xf.b.build @ custom-element.js:708
f.build @ resource.js:285
Gh @ resources-impl.js:470
f.upgraded @ resources-impl.js:581
Xf.b.ic @ custom-element.js:645
(anonymous) @ custom-element.js:996
```

The link to amp-ad-3p-impl.js seems to be pointing to the site: https://raw.githubusercontent.com/ampproject/amphtml/1487969065964/extensions/amp-ad/0.1/amp-ad-3p-impl.js

I suppose something is not pulling in my local config files at: ads/_config.js and 3p/integration.js. Perhaps I'm doing something silly but not sure what.

My changes in ads/_config.js are:
```
diff --git a/ads/_config.js b/ads/_config.js
index 7b44673..f6ea5ed 100644
--- a/ads/_config.js
+++ b/ads/_config.js
@@ -36,6 +36,12 @@
  * }
  */
 export const adConfig = {
+
+  '33across': {
+    clientIdScope: 'AMP_ECID_33ACROSS',
+    renderStartImplemented: true,
+  },
+
   _ping_: {
     renderStartImplemented: true,
   },

```
and in 3p/integration.js are:

```
diff --git a/3p/integration.js b/3p/integration.js
index 0e0638a..46d8af1 100644
--- a/3p/integration.js
+++ b/3p/integration.js
@@ -44,6 +44,7 @@ import {reddit} from './reddit';
 import {twitter} from './twitter';

 // 3P Ad Networks - please keep in alphabetic order
+import {_33across} from '../ads/33across';
 import {_ping_} from '../ads/_ping_';
 import {a9} from '../ads/a9';
 import {accesstrade} from '../ads/accesstrade';
@@ -194,6 +195,7 @@ if (getMode().test || getMode().localDev) {
 }

 // Keep the list in alphabetic order
+register('33across', _33across);
 register('a9', a9);
 register('accesstrade', accesstrade);
 register('adblade', adblade);
```

I tried to do a gulp build as well as gulp extensions with no luck either before running gulp with no luck.

A side minor thing is that I noticed that the link to DEVELOPING at:
https://github.com/ampproject/amphtml/blob/master/ads/README.md#developer-guidelines-for-a-pull-request

was invalid:
https://github.com/ampproject/amphtml/blob/master/ads/contributing/DEVELOPING.md

## How do we reproduce the issue?

With the steps above.

## What browsers are affected?
Chrome

## Which AMP version is affected?
AMP ⚡ HTML – Version 1487969065964

**Comment by dknecht** [comment]
@klall33 This isn't the right guide for the firebolt integration.  I just sent Bageshri an email about.

**Comment by klall33** [comment]
@dknecht I was actually simply running through the steps on the wiki for AMP Ads. I'm not actually working on AMP4ADS. 

We plan to in the near future be approved as an ad network for AMP ads.

**Comment by klall33** [comment]
Closing ticket for now to discuss further with the Cloudfare team.
