### ISSUE TITLE
Intent to Implement:  Custom variables support for OpenX amp-ads

### ISSUE THREAD

**Issue by rjvelicaria** [ampproject/amphtml#7937]
We plan to implement custom variables support for OpenX amp-ads.  The changes will be on https://github.com/openx/amphtml under a new branch called `custom-variables`.

Company Name: OpenX Technologies, Inc.

**Comment by rjvelicaria** [comment]
Are new implementations de-prioritized for the moment?  
Just wondering why there's no one looking into this.

**Comment by erwinmombay** [comment]
friendly ping for @lannka and @jasti 

@rjvelicaria apologies, with the first amp conference happening last week everybody schedule has just been backed up.

**Comment by rjvelicaria** [comment]
I see.  Thanks for the info, @erwinmombay !

**Comment by jasti** [comment]
@rjvelicaria Sorry about the delay.
Can you please explain what you specifically mean by custom variables? What purpose do they serve? Would this only impact the open x ad extension?

**Comment by rjvelicaria** [comment]
@jasti This only impacts the OpenX ad extension.  
I might've phrased the title wrong, but the intention is to have the OpenX ad extension support more features that the exchange provides via a normal tag.
Some publishers will want to have their own "settings"/ "configurations" passed in to the exchange and this provides them a way to do it within AMP.

**Comment by jasti** [comment]
Great, look forward to the PR.

**Comment by rjvelicaria** [comment]
We can close this.  This feature was successfully released at around 2017-03-31.
