### ISSUE TITLE
Closing lightbox will scroll page to hash position instead of the position before opening lighbox

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#7939]
Steps to reproduce:
1. In safari, open https://yuxichen.herokuapp.com/examples/everything.amp.max.html
2. Click on the **Image0** hash link and the page will jump to the hash element position
3. Scroll up a bit and open the lightbox
4. Close the lightbox
5. The lightbox is closed but the page jumps to the image position instead of the position before opening lightbox

This only happens in safari ios (android chrome and ios chrome works fine). The bug happens because when closing the lightbox, `history.go(-1)` will restore the position of the hash tag in safari.

Possible way to fix this:
- When opening up lightbox, inform our history class to
  - remember the current hash
  - temporarily remove the hash using `history.replaceState(null, '', '#')`
  - do `history.pushState` as before
- Later when closing lightbox, let the history class to
  - do `history.go(-1)` as before
  - the page will go back without changing position
  - restore the previous hash by `history.replaceState(null, '', '#hash')` without changing position

**Comment by letsila** [comment]
This bug doesn't occur anymore on the latest (Version: 1500510703681)
