### ISSUE TITLE
Make slidescroll carousel resume autoplay after user swipe ends

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#7970]
Currently for amp-carousel type slides (slidesscroll), we clear auto play after user touchmove event. It would be nice to resume autoplay after user ends touch event in a while.

/cc @camelburrito @aghassemi

**Comment by camelburrito** [comment]
This is the spec, we will need to increment version if we do this. Also this is not very easy to do as it is not easy to distinguish between user scroll vs autoscroll.

**Comment by muxin** [comment]
Closing this feature request since it's difficult to implement.

**Comment by grahamle** [comment]
Highly recommend amp-team to support this feature, after user's interaction.
