### ISSUE TITLE
In-a-box: consider removing viewport offset

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#7971]
I think we should seriously consider dropping offset from in-a-box viewport implementation. Instead we can connect them via intersection-observer polyfill. The current approach creates some notable risk conditions and confuses coordinate system.

Even if we decide to stick with the current approach, we should still move offset messaging to InOb polyfill and use it in the viewport instead.

**Comment by lannka** [comment]
@dvoytenko if we drop the viewport offset from inabox, then we can no long calculate the absolute position of an AMP element, which potentially could be helpful if later on we want to track if an ad is ATF etc.

Moving offset calculation from viewport to inOb will inverse the dependency. InOb depends on Viewport for scoll positions.

**Comment by dvoytenko** [comment]
@lannka In the current situation, we don't know the box of the in-a-box embed until the first post message. This we'll be source of risk conditions and bugs. 

What uses would we derive from absolute positioning? If it's visibility - it has to be driven by the InOb.

**Comment by lannka** [comment]
Due to the recent discussion, seems this was a mis-understanding of the current implementation.
@dvoytenko are you OK to close this?

**Comment by dvoytenko** [comment]
Yes, let's close.
