### ISSUE TITLE
Add a generic responsive container component to AMP

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#7972]
### Background
AMP HTML [supports various](https://www.ampproject.org/docs/guides/responsive/control_layout) `layout`s such as aspect-ratio-based responsive layout which is very useful. Other useful layouts such as [responsive-height ](https://github.com/ampproject/amphtml/issues/8531)are also in the works.

### Motivation 
Currently AMP layouts are only supported on AMP elements such a `amp-img`, `amp-carousel`, etc.. but these layouts can be useful on their own.

`amp-layout` component will bring the power of AMP `layout` attribute to a generic multi-purpose container element that can be used independent of other AMP elements.

For instance:
```
<amp-layout class="card" layout=responsive width=2 height=1>
   This card container will always maintain its 2x1 aspect ratio!
</amp-layout>

.card {
  background-color: red;
}
```
### Implementation strategy
- [ ] Create a new `amp-layout` extended component. Only allow `FIXED`, `FIXED_HEIGHT`, `RESPONSIVE`, `FILL`, `FLEX_ITEM` layouts (hint: `isLayoutSizeDefined`)
- [ ] Add validator file for validation rules.
- [ ] Add documentation
- [ ] Add example 

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] Read up on [How to build an AMP extension](https://docs.google.com/document/d/19o7eDta6oqPGF4RQ17LvZ9CHVQN53whN-mCIeIMM8Qk)
- [ ] Follow the **Implementation strategy** from above.
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review).  Mention `closes Issue #7972` in the description.
- [ ] Assign @aghassemi as the reviewer
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

### Questions?

If you have questions ask in this issue or on your Pull Request (mentioning @aghassemi) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

**Comment by dvoytenko** [comment]
Possible, e.g. via `<amp-layout>` element or such. This is not very ergonomic. It'd be much better to just rely on the same attributes we use, e.g. `layout`, etc. Unfortunately, there's no efficient way to scan for them in DOM and `attr` CSS is not supported for non-content anywhere yet.

Generally, CSS for responsive layout is tricky, but simple:

```
[layout="responsive"]::after {
  display: block;
  content: "";
  padding-top: 50%;
}
```

If we had full support of `attr`, we could do:
```
[layout="responsive"]::after {
  display: block;
  content: "";
  padding-top: calc(attr(width px) / attr(height px) * 100%);
}
```

We could also consider custom CSS vars and allow styles to customize them, e.g.
```
<div layout="responsive" style="--aspect-ratio: 80%"></div>

[layout="responsive"]::after {
  display: block;
  content: "";
  padding-top: var(--aspect-ratio);
}
```

In the absence of these tools, however, perhaps manual `:after/padding-top` trick or an `<amp-layout>` element could do the trick.

**Comment by aghassemi** [comment]
With https://github.com/ampproject/amphtml/issues/8531 , `<amp-layout>` may be the only option as we need to run JS to generate the SVG and a pure CSS implementation using `calc` and css-vars, `attr()` won't cut it anymore.

(Of course AMP Cache can still optimize this for all layouts same way it is planning to do so now by server-side rendering)

**Comment by aghassemi** [comment]
Chatted with @dvoytenko we decision is to go ahead with this component. Will turn it into a GFI.

**Comment by tassawarr** [comment]
`<amp sec>` / `<amp section>` may easy to use and it may easy to use and easy to understand . Rather then that we may use the bootstrap css according to this one.

**Comment by tassawarr** [comment]
@aghassemi layout seems to be the whole layout of the page. `<section>` may refer them in the best to understand and code. Rather then that it has a good understanding too using in css . 
What if we use

```
<amp section> 
<amp sec1> </amp sec1>
<amp sec2> </amp sec2>
<amp sec3> </amp sec3>
<amp sec4> </amp sec4>
</amp section>
```


or we may clasify them as 
```
<amp col class="amp-col-1" >amp-col-1</div>
<amp col class="amp-col-2">amp-col-2</div>
<amp col class="amp-col-3" >amp-col-3</div>
```
Which is easy to use, compelling and with an understanding nature. We're here to make amp easier and tend load faster then simple html. 

```
<amp style>
amp section {
display:block;
width:100%;
}

</amp style>
```

**Comment by tassawarr** [comment]
`<amp layout> </amp layout>` Seems to the main div like body or something like that in the beginning to end. We can think to classify them as below

`<div class="MAIN"></div>`

# SUGGESTIONS .


##  MAIN DIV START
`<amp layout> `

##  1st Section With Columns STARTS
  ```
<amp section> {width:100%;}
<amp sec1>  {width:20%;}</amp sec1>
  <amp sec2> {width:40%;}</amp sec2> 
    <amp sec3> {width:60%;}  </amp sec3>
      <amp sec4> {width:80%;} </amp sec4>
   </amp section>
```
##  1st Section END

##  2nd Section With Columns  STARTS
```
<amp section> {width:100%;}
<amp sec1>  {width:20%;}</amp sec1>
  <amp sec2> {width:40%;}</amp sec2> 
    <amp sec3> {width:60%;}  </amp sec3>
      <amp sec4> {width:80%;} </amp sec4>
   </amp section>
```
##  2nd Section ENDS

`</amp layout>`
##  MAIN DIV END

**Comment by duksh** [comment]
Does AMP use any sort of Grid system (for the css)? I understand that the styles are defined inline

**Comment by aghassemi** [comment]
@duksh  http://ampstart.com is AMP's CSS framework that also includes http://basscss.com/ (which similar to bootstrap has a Grid system for rows and columns, etc..) Please take a look there.

**Comment by cramforce** [comment]
@duksh But you can also use whatever you want. AMP Start is just one option.

**Comment by mrjoro** [comment]
Moved this over to issue 10018.
