### ISSUE TITLE
Allow target of amp-animation to be any CSS selector 

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#7981]
Ran into a case where I wanted to animate `img` inside of `amp-img`. I think we should allow `target` to be any CSS selector rather than just id.

**Comment by dvoytenko** [comment]
Generally, I'd rather keep the internal details of tags hidden. I'll keep it in mind though if we find a stronger need for this.

**Comment by alanorozco** [comment]
Expanding about [the ramifications of this here](https://docs.google.com/document/d/1-NXfuCB56-Mb-VrHp9AqTw6lo_t4zpWfim7ZbR_KnwU/edit#).

Open question is whether we will deprecate or fallback to the target ID behavior.

**Comment by aghassemi** [comment]
Since `amp-animation` is experimental and a point of experimental features is to allow for API changes, I prefer deprecation. How about:

- deprecate `target`, start throwing warnings.
- add `targetSelector` (to be consistent with `querySelector` in naming)
- error if both specified.
- remove `target` after a few weeks.

(`amp-bind` has done this sort of deprecation before)

**Comment by dvoytenko** [comment]
Yes, I think we'll move with `selector` in some form and deprecate `target`.

**Comment by aghassemi** [comment]
This has been implemented. `amp-animation` has `selector` which works with any CSS selector now.
