### ISSUE TITLE
Native Share Module - needs updating as no fallback URL

### ISSUE THREAD

**Issue by ayumihamsaki** [ampproject/amphtml#7982]
Hi, using this api on desktop on Google Canary everything working fine. However,...

Trying to add it to AMP is a bit of a problem. The information is found here: https://ampbyexample.com/components/amp-social-share/#native-share-dialog-chrome-on-android-

The biggest problem with it in AMP is that there is no fallback. I managed to get it working in Google Canary on an AMP page. But when I open the same webpage in Firefox Nightly the share button is missing.

My solution will require lots of extra coding to check if the user is using a Chrome or Android device and then either display the AMP code or my own code as a fallback.

This is not the best way and I think someone just needs to re-code and update the AMP Share Module Script to allow a fallback.

AMP has a "data-param-url" so if a developer/webmaster added this then surely it should load a fallback URL. At present doesn't do anything, so this module needs updating.

Also added my comment here: https://discourse.wicg.io/t/web-share-api-for-sharing-content-to-arbitrary-destination/1561/22

How it should work:

1. Web Share API to Android or Chrome Device.
2. If device is not Android/Chrome then Web Share API needs to use a fallback URL.

Issue: No way to add Fallback URL to this module (at present)

**Comment by aghassemi** [comment]
@ayumihamsaki you should be able to use a combination of `data-share-endpoint` and `data-mode="replace"` to achieve what you need.

You can have two `amp-social-share` items: one system and one custom fallback (using `data-share-endpoint` to specify the fallback URL).

Now using  `data-mode="replace"`  on the system one, will cause the custom fallback one to disappear on systems that support native share. For systems that don't support native share, system one will be hidden and the other one will be displayed.

See https://jsbin.com/gibepidape/edit?html,output for an example

Closing the issue, feel free to reopen if that solution does not work for your case.

**Comment by ayumihamsaki** [comment]
Have tested that jsbin and it worked fine, thanks.

**Comment by ayumihamsaki** [comment]
@aghassemi I spoke too soon. Your code doesn't work outside jsbin, when I tested it live in Firefox Nightly the Fallback displays but the URL link doesn't work. In Google Canary it works fine with the non-fallback URL. 

So the fallback URL is not working (just to let you know).

(For now I think I will stick with my version as working using this php class:  https://github.com/serbanghita/Mobile-Detect) ~ but many thank for your reply and help.

**Comment by aghassemi** [comment]
@ayumihamsaki note that the actual URL I used in that jsbin is fake (it is just `https://example.com/custom-url`)

**Comment by ayumihamsaki** [comment]
@aghassemi Sorry, I have put your script in a fresh new html webpage and works fine. I must have a strange conflict in my amp webpage. Will spend a few hours hunting down the problem. But your code seems to work fine. Sorry for confusion (my mistake) and thanks again for your code! I will spend the time making it work your way!
