### ISSUE TITLE
AMP Analytics: Make the "aip" parameter changeable to false

### ISSUE THREAD

**Issue by 1987yama3** [ampproject/amphtml#7983]
In [/extensions/amp/analytics/0.1/vendors.js](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/vendors.js), "aip" parameter of Google Analytics is constantly true.

This parameter indicates whether to anonymize the IP address. When set to true, the end of the IP address is recorded as 0.
The default value in analytics.js is false. But the default value in AMP Analytics is true.

Since the IP address is anonymized, it seems that IP address exclusion is not work properly at [amp-by-example: #665](https://github.com/ampproject/amp-by-example/issues/665).

Analytics Help: Exclude internal traffic.
https://support.google.com/analytics/answer/1034840?hl=en

I think that default should be set to false even in AMP. or you should be able to change it.

Thanks,

**Comment by lannka** [comment]
Sounds reasonable to provide an override. 
@avimehta can you confirm its default value in GA? Was it intentional to make it `true` in AMP?

**Comment by avimehta** [comment]
hi! We have a new team member who needs some startup tasks. Do you mind if I assign this to him?

**Comment by rudygalfi** [comment]
SGTM!

**Comment by avimehta** [comment]
@1987yama3 This should go out in production in a couple of weeks. As shown in the example, you can disable anonymizeIP by adding a variable to your config: 

`'anonymizeIP': ''`

**Comment by 1987yama3** [comment]
@avimehta @lannka 

I'm sorry for reply late.

I think that this PR is wrong.
If I setting to ```'anonymizeIP': ''```, the request parameter will be ```_v=a1&ds=AMP&&_s=something```(duplicate ampersand).

How about thinking that the code below is better?

```js
'vars': {
  'eventValue': '0',
  'documentLocation': 'SOURCE_URL',
  'clientId': 'CLIENT_ID(AMP_ECID_GOOGLE)',
  'dataSource': 'AMP',
  'anonymizeIP': 'true', // or false
},
```

```js
'basePrefix': 'v=1&' +
    '_v=a1&' +
    'ds=${dataSource}&' +
    'aip=${anonymizeIP}&' +
    '_s=${requestCount}&' +
    'dt=${title}&' +
```

**Comment by avimehta** [comment]
hi @1987yama3 GA anonymizes ip addresses event if you send `&aip=&`. The only way to not anonymize the ip addresses is to not specify the parameter. This is the reason the pull request was designed this way.

**Comment by 1987yama3** [comment]
Hi @avimehta

Thanks for your reply. 
I knew it for the first time. It is not a parameter to set with true/false.

Thanks.

> When present, the IP address of the sender will be anonymized. For example, the IP will be anonymized if any of the following parameters are present in the payload: &aip=, &aip=0, or &aip=1
https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters?hl=en#aip
