### ISSUE TITLE
amp-analytics: extend request parameters of snowplow tracker

### ISSUE THREAD

**Issue by ecoron** [ampproject/amphtml#7984]
Hi, 
this is a feature request for the current implementation for the snowplow tracking sdk, which  is very limited. It would be a helpful improvement if more possible request parameters are added to the request url of the tracker. Especially i miss some basic parameters which provides i.e the page.url, page.referrer or clientId.

- [current implementation amp-analytics](https://github.com/ampproject/amphtml/blob/00e53e2c7b797dbe40898ce20d3e9bb271dfd52f/extensions/amp-analytics/0.1/vendors.js#L960)
- [snowplow tracker protocol](https://github.com/snowplow/snowplow/wiki/snowplow-tracker-protocol)

**Comment by rudygalfi** [comment]
@ecoron Are you working on adding this?

**Comment by ecoron** [comment]
I created a pull request #8227 , maybe someone can check it.

**Comment by ecoron** [comment]
Hi, how goes it on? seems it's still in review...

**Comment by rudygalfi** [comment]
@lannka Can you take another look at the PR and complete the review?
