### ISSUE TITLE
Issues with amp-list nested inside amp-carousel

### ISSUE THREAD

**Issue by jalajc** [ampproject/amphtml#7985]
## amp-list when nested inside amp-carousal doesn't render perfectly.
 - list images doesn't load on ui, (though src url is fetched by mustache template)
 - error in console only sometime particularly on Mobile `"[CustomElement]" "Cannot resize element and overflow is not available" ` (yups I have not prescribed overflow for amp-list as enough space is available through parent element css config, but this behavior is erratic, appear only sometime) 

## Use case: 
For creating a _**Trending section**_ which gets a list of _n_ items of periodically updated (say every 6 hrs) data from CORS end point roled through carousal slides of different topic 
(Different than a amp-live-list)

## How do we reproduce the issue?
Step 1. Include required components, viz amp-carousal, amp-list, amp-mustache
Step 2. Use following snippet to test
Step 3. Include css as appropriate from [here](https://ampbyexample.com/samples_templates/news_article/preview/)
Code snippet for testing (passed over ampbyexample.com playground)
```
    <h2>Trending</h2>
  <amp-carousel height="450" width= "400"  type="slides">
    <div class="card"><h3>Sports</h3>
    	<amp-list width="400" height="450" layout="responsive" src="https://www.ampbyexample.com/json/related_articles.json">
    	<template id="amp-template-id" type="amp-mustache">
      		<a class="card related" href="{{url}}">
		        <amp-img width="101" height="75" src="{{thumbnail}}"></amp-img>
        		<span>{{title}}</span>
      		</a> 
    	</template>
    	</amp-list> 
    </div>
    <div class="card"><h3>Entertainment</h3>
    	<amp-list template="amp-template-id" width="400" height="450" layout="responsive" src="https://www.ampbyexample.com/json/related_articles.json">
    	</amp-list>
    </div>
  </amp-carousel>
```

What device type?
Desktop, Mobile both tested on Google chrome, not tested on other browsers

## Which AMP version is affected?
Version 1487969065964. Not tested on earlier versions.

**Comment by jalajc** [comment]
Looks similar to #6985 where amp-img is not loading inside amp-live-list

**Comment by aghassemi** [comment]
@camelburrito I assume all dynamic content generated after carousel is layedout won't work because carousel has taken ownership of its existing children and is not aware of new children being added to it to schedule them.?

/cc @jridgewell

**Comment by jridgewell** [comment]
Yup.

**Comment by ericlindley-g** [comment]
This is something we want to make work — tracking the issue [here](https://github.com/ampproject/amphtml/issues/4405), so closing this as a duplicate
