### ISSUE TITLE
InOb polyfill: should trigger automatically for new elements w/o ticks

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#7992]
See this unit test to repro: #7991.

Per spec, the last step for `IntersectionObserver.observe()` API is:
> Schedule an iteration of the event loop in the root's browsing context.

Further, I believe `tick` calls need to be **debounced**. In many cases `scroll` event is called way to rapidly to call measures immediately.

**Comment by dvoytenko** [comment]
From @lannka:

> what do you think if keep one last tick state, and reuse it here? If there isn't a tick yet, we can actually do nothing.

**Comment by dvoytenko** [comment]
@lannka, yes, I think this is a good idea in general. I'm not sure how much it "breaks" the current approaching to ticking.

**Comment by dvoytenko** [comment]
@lannka Alternative, to solve the "first pass" problem before the first tick, we can do one of the following: 
 1. Wait for the first tick. In essence it will work as a "start"
 2. Instead provide a callback in the polyfill's constructor to return the `viewport.getRect()`. Not sure what to do with `opt_iframe` argument though - I don't fully understand its meaning. But it could be provided similarly.

**Comment by lannka** [comment]
I think that is not a problem. If element is observed before the first tick, its intersection will be reported on first tick. 

We just need to make sure we always tick the InOb once after initialization.
