### ISSUE TITLE
Arrow links not working in side navbar

### ISSUE THREAD

**Issue by bhansa** [ampproject/amphtml#7997]
## Arrow links not working in side navigation bar

<img src="https://cloud.githubusercontent.com/assets/9723884/23621638/9c246b9a-02c1-11e7-88a3-b63422bf1b53.png" width="250" />

Not able to expand or collapse any of the categories.
Are they supposed to provide that feature?

**Comment by aghassemi** [comment]
@bhansa I am not able to reproduce on Chrome desktop, could you please provide details of the browser/platform you are seeing this issue on?

**Comment by bhansa** [comment]
Hi,

I just checked the website, seems like the issue has been resolved.
Previously when I checked there were no links or any other transition
between pages.

Thanks,
Bharat Saraswat

On 30 Jun 2017 11:14 am, "Ali Ghassemi" <notifications@github.com> wrote:

@bhansa <https://github.com/bhansa> I am not able to reproduce on Chrome
desktop, could you please provide details of the browser/platform you are
seeing this issue on?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ampproject/amphtml/issues/7997#issuecomment-312180505>,
or mute the thread
