### ISSUE TITLE
Implement infrastructure for golden file pixel-diff rendering tests

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#8]
@dvoytenko hacked something up based on phantom.

We should make this so that you can easily add samples and confirm that rendering stays the same as you make changes (with the option to approve diffs, of course)

**Comment by rudygalfi** [comment]
@erwinmombay Assigning this to you as the best possible assignee.

**Comment by rsimha-amp** [comment]
Basic infrastructure is in place. Tracking the addition of more tests via separate issues.

**Comment by cramforce** [comment]
I have a few questions that I'm not clear at:

- Are we blocking PRs yet on these tests succeeding?
- Can everyone see the diffs? I saw something about redacted secret tokens in the URL.

**Comment by rsimha-amp** [comment]
- We are not blocking PRs yet. I'm tracking that work via #9469.
- The free version of Percy doesn't appear to allow everyone to see the diffs. This has nothing to do with secret tokens (that's related to logs). I'm in the process of exploring a paid account on Percy to see if that will give us the ability to make diffs public.

**Comment by cramforce** [comment]
Did you make progress on "Can everyone see the diffs?"

I think they require an invite, right?

**Comment by rsimha-amp** [comment]
@cramforce, I've invited all internal commiters to view the diffs, so they should have access. Still exploring the possibility of giving blanket access to anyone logged in with a github account who also has access to the travis logs on `ampproject/amphtml`.

**Comment by cramforce** [comment]
@rsimha-amp Ideally they would be public. Logged in with GH account would be OK. As liberal as we can be.
