### ISSUE TITLE
Feature Request: amp-amp, AMP First Class Embeds 

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#8006]
Requirement.  Isolated embedded content that loads fast.  Dynamic content beyond the ability of AMP list, including ability to include all valid amp elements.  Example mixed related content widget that includes both ads and editorial. 

**Goals:** 

1. Loads with the AMP page (including pre-render?)
2. Isolated from the AMP page, own CSS 
3. Access to parent page CID, analytics variables.
4. Can including any AMP element (including ads).
5. Optional automatic resize if below fold.
6. Must be valid AMP.

**Why not AMP list?**

1. Does not allow CSS isolation.
2. Template structure too rigid limiting what can be implemented.
3. Can't include ads

**Straw man for discussion:**

Lightweight AMP page similar to a4a, can be loaded either from an AMP CDN or as a signed page (as a4a).   

Size constraints similar to a4a.

Ads in embed subject to same load penalty (if they are not a4a) as ads on main page (no incentive to use this to end run ad load delays).

Share AMP runtime if possible (as a4a).

See also https://github.com/ampproject/amphtml/issues/7570

cc @jasti @cramforce

**Comment by cramforce** [comment]
Question: Would this be explicitly for trusted content? As in: Do you need a security boundary between you and the content? Or is this more of a fancy content composition mechanism?

**Comment by jpettitt** [comment]
@cramforce good question.  Our use case is for trusted content, we're mostly looking for composition and CSS isolation.  However I can see uses cases where a stronger trust boundary would be helpful. I could live with a shadow dom based or an iframe based option.

**Comment by jasti** [comment]
My suggestion, if we choose to build it, is to make it a seperate component and not reuse A4A if the plan is to embed regular ads in them. We'd want to be fairly certain that whatever we call A4A is reasonably static. 

@michaelkleber @lannka for thoughts as well.
@jpettitt I'm sure you've thought of this, why not amp-iframe?

**Comment by cramforce** [comment]
Yeah, definitely no reuse of A4A. This could be a very simple mechanism really. My main question would be for how to do the signing, since we don't have any scalable (beyond a few ad networks) infra to do that really.

**Comment by jpettitt** [comment]
The reason to not do `amp-iframe` are sandboxing, not reloading the runtime and the load delay.  Although I could put an amp page in an `amp-iframe` it wouldn't get us the same CID, analytics substitutions etc.  Perhaps allow un-sandboxed iframes if the iframe url is a recognized amp cdn? (need to think that one through).  

Example of something I can't do with an iframe:  launch an amp lightbox that fills the screen.  Yes I could go will screen with the iframe but that would require JS meaning the iframe wouldn't be valid amp.  I could do amp-lite (no tag on html but still use the runtime) but that seems like a bit of a hack.

I'd be happy to do a hangout to kick ideas around if that makes sense, I could show you some of the non-public uses cases we have.

**Comment by jasti** [comment]
CC @dvoytenko

**Comment by dvoytenko** [comment]
Do we want SSI/streaming for this? I could imagine we automatically splice a referenced embed in a shadow root. Shadow roots are not streamable, but we can probably come up with some way to do this. I wonder what other UX parameters we have?

- Do we want it to be auto sizing? If so, SSI would help in Cache, but UI can jump on direct origin pages w/o SSI.
- We can also look feature-by-feature. It'd be relatively straightforward to allow iframes to open full-viewport lightbox, as long as we can confirm/approximate user action.

**Comment by jasti** [comment]
Ping @jpettitt

**Comment by jpettitt** [comment]
Missed the ping sorry.  We're trying to nail down exactly what we need and what else makes sense.  Standby.

**Comment by jasti** [comment]
Closing for now - please reopen once requirements are finalized.
