### ISSUE TITLE
Prepend AMP_CONFIG to local runtime binary

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#8008]
It can fix 2 problems:
- experiments enabled in prod right now are by default disabled in dev mode. sometimes causing confusion. or in worst case, release eng is not testing with the exact setup as prod, hence mis-catch bugs.
- many code relies on `mode.localDev`, which is calculated via [messy logic](https://github.com/ampproject/amphtml/blob/master/src/mode.js#L82) including checking if hostname equals `localhost`, hence failed on our [Heroku nightly server](amphtml-nightly.herokuapp.com/examples/). (/cc @alanorozco this is what you encountered)

**Solution A**
The reason we separate the prepending `AMP_CONFIG` task from the main binary building process, is because we want to change `AMP_CONFIG` without rebuilding the binary (keep the same version number). 

If we know it's for local build (by passing `--fortesting` flag), we automatically do `gulp prepend-global`.

**Solution B**
Let local gulp dev server to handle the prepend logic.

@erwinmombay what you think?

**Comment by lannka** [comment]
@erwinmombay @rsimha-amp 

wanted to raise this proposal again given that not testing locally with appropriate experiment flags caused real production issues.

what you guys think?

/cc @alanorozco

**Comment by rsimha-amp** [comment]
I think it's a good idea to run (at least a subset of) our tests with both prod and canary configs. There is precedent for this in the visual tests: See https://github.com/ampproject/amphtml/blob/master/build-system/tasks/visual-diff.rb#L135

Note that in https://github.com/ampproject/amphtml/pull/10732/files, I added a `--remove` flag to `gulp prepend-global`, so now, you can do things like add the prod config, run tests, remove the config, add the canary config, run tests again, etc. I'd imagine we can easily do something like this on Travis / master, and for local testing.

**Comment by lannka** [comment]
@rsimha-amp awesome. i think it makes sense to run all tests with default config the same as production.

beyond that, i think we should always preprend the config in local gulp build to mimic the real production. the motivation was to remove the logic that uses hostname == `localhost` to detect isLocalDev, which doesn't work when the gulp server is run on Heroku for example.

We can for example put `isLocalDev: true` in AMP_CONFIG, just like we have `isCanary: true`

**Comment by rsimha-amp** [comment]
@lannka, to conclude, I ended up going with a modified version of solution A and we now apply the prod (or canary) config after `gulp dist --fortesting` and `gulp build`, and before `gulp test`. We ended up having to restore the `localhost` logic in `src/mode.js` to allow for local development.
