### ISSUE TITLE
Add Joomla as a supported platform

### ISSUE THREAD

**Issue by weeblr** [ampproject/amphtml#8009]
Hi

Just checked out the supported paltform documentation page, and was surprised to find WordPress and Drupal listed, but not Joomla. #1 and #3 CMS but not #2?

Rgds

**Comment by adelinamart** [comment]
Thanks for the issues. Adding here @rudygalfi to see if it's something we are looking into it, if so to note down the request.

**Comment by rudygalfi** [comment]
Is there any officially-endorsed integration from Joomla?

**Comment by weeblr** [comment]
Hi

Nope, and unlikely to happen, the project does not endorse 3rd party plugins. There are currently 2 AMP joomla plugins (including ours).
Considering the market share of Joomla, I find it surprising that it is not listed, while obviously AMP support is available.

**Comment by rudygalfi** [comment]
Closing since there's been a lack of activity. In any case, Joomla support for AMP would be better tracked under the Joomla project.
