### ISSUE TITLE
amp-accordion triggers error with break on exception enabled

### ISSUE THREAD

**Issue by gilbox** [ampproject/amphtml#8011]
## Short description of your issue:

> Render timeout waiting for service amp-accordion to be ready.

![image](https://cloud.githubusercontent.com/assets/2136203/23677892/bbb2a812-0336-11e7-916d-bc2a8a90527a.png)

## How do we reproduce the issue?

- Create amp-accordion and enable _Break on Exception_
- reload page

## What browsers are affected?

chrome

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1488856674144

**Comment by jridgewell** [comment]
This is because `<amp-accordion>` is a render-delaying extension, and we're waiting for it to download before we "finish" rendering the page. Do you have an example URL with the issue?

**Comment by gilbox** [comment]
You can repro the bug in the example from the doc:

https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-accordion%2Fsource%2F
