### ISSUE TITLE
amp-sidebar bug

### ISSUE THREAD

**Issue by ayumihamsaki** [ampproject/amphtml#8016]
Hi,

I have seen this issue been raised a few times and people keep closing it and nothing getting fixed.

I would like to demo the problem with a video:

https://youtu.be/rnuaU43VH1s

This issue can get merged with this: https://github.com/ampproject/amphtml/issues/4073
(which is closed)

The problem is when a user scrolls the amp-sidebar doesn't work. It seems to only work clicking.

**Comment by levidurfee** [comment]
@ayumihamsaki can you provide me the code so I can try it?

**Comment by ayumihamsaki** [comment]
@levidurfee I can't provide you the website I am working on as I am currently investigating this issue and trying to find the source of the problem and ripping out bits of code right now...

But you can try and test the website: https://ampbyexample.com/

As that website has the exact same problems I have with the amp-sidebar module.

**Comment by ayumihamsaki** [comment]
@levidurfee I found the issue now, after a few hours it seems like you have to add this CSS to amp-sidebar. 

I think maybe someone should inject it into amp-sidebar to force the css to be delivered when using this module. 

Here is the code to make the amp-sidebar work for scrolling:

```
<style>
amp-sidebar {
    height: 100%;
    position: relative;
}
</style>

<amp-sidebar id='sidebar' side='right' layout='nodisplay'>
  <form action="/" target="_top">
    <button type="reset" class="close-button" id="menu-button" on='tap:sidebar.toggle'></button>
      <div>

        <!-- Sidebar code -->

      </div>
  </form>
</amp-sidebar>

```

**Comment by levidurfee** [comment]
Thank you @ayumihamsaki for getting that! Good job finding that CSS, so do you still think this is a bug? I can try this out this evening. :)

**Comment by levidurfee** [comment]
@ayumihamsaki you may also want to check the latest example usage on [ampbyexample.com](https://ampbyexample.com/components/amp-sidebar/)

Is there a specific reason you have a `<form>` inside your `<amp-sidebar>`? Also, your `<button>` will be hidden when the document loads.

https://ampbyexample.com/components/amp-sidebar/

**Comment by ayumihamsaki** [comment]
@levidurfee sorry for late reply, was seeing if I could recode a better javascript file for sidebar or not...

Ignore the `<form>` and `<button>` tags. I was comparing many websites with amp.

My final solution was this (I added the z-index as there was another problem on some websites), but this my simple conclusion for this:

```
<style>
amp-sidebar {
    height: 100%;
    position: relative;
    z-index: 9999;
}
</style>

<amp-sidebar side="left" layout="nodisplay" id="sidebar">
  <aside role="complementary">

        <!-- Sidebar code -->

  </aside>
</amp-sidebar>
```

**Comment by levidurfee** [comment]
Thanks @ayumihamsaki :)

Briefly looking at your final solution, it looks fairly straight forward and elegant. Unfortunately I won't have time to further look at it until Friday.

**Comment by levidurfee** [comment]
@ayumihamsaki do you experience the same issue with this [jsbin](http://output.jsbin.com/tudayijeru)?

Here is a [video recording](https://www.youtube.com/watch?v=1ASO8o3W420) of what happens when I attempt to recreate the issue.

In your video the nav had items collapsed, which may have something to do with it. Please let me know if that jsbin works for you. Then we can go from there :)

Also, I appreciate your patience!

**Comment by levidurfee** [comment]
hi @ayumihamsaki , have you had time to try that jsbin?

**Comment by ayumihamsaki** [comment]
hi @levidurfee, sorry for late reply,I thought I'd give you a few days before checking back on this issue. I have just tested your jsbin and seems to work fine in all browsers...

**Comment by levidurfee** [comment]
hi @ayumihamsaki :)

I'm glad your client websites are working without any problems!

I'm starting to think that his may be an isolated incident and not necessarily a bug. The live websites that were experience this issue may have extra CSS that could require your additional block of CSS to correct it. However, it appears the `<amp-sidebar>` works fine with minimal CSS/HTML.

**Comment by erwinmombay** [comment]
cc @camelburrito

**Comment by camelburrito** [comment]
Not sure what the problem here is. is it the fact that the page is scrolling when the sidebar finishes scrolling or does the sidebar not scroll at all? 

Also the suggestions to change the `position` and `z-index` will never take effect (not work) because the default styles for those are non-overridable. And changing the `height` to `100%` will not always work, the default value (`100vh`) is a better choice.

**Comment by muxin** [comment]
I had a PR https://github.com/ampproject/amphtml/pull/7792 several weeks ago to disable scroll of main page when opening up sidebar. Maybe that fixed the issue?

**Comment by levidurfee** [comment]
@ayumihamsaki can this issue be closed?

**Comment by ayumihamsaki** [comment]
@levidurfee sorry late reply, up to you.
