### ISSUE TITLE
Creating your first AMP Component Instructions error on slide 2

### ISSUE THREAD

**Issue by aylusltd** [ampproject/amphtml#8021]
https://codelabs.developers.google.com/codelabs/creating-your-first-amp-component/#1

```
git clone git://github.com/ampproject/amphtml.git
npm install
cd amphtml
git checkout -b amp-hello-world
```

should be:

```
git clone git://github.com/ampproject/amphtml.git
cd amphtml
git checkout -b amp-hello-world
npm install
```

can't `npm install` if there's no `package.json` in the directory

**Comment by erwinmombay** [comment]
thank you @aylusltd, fixing on the docs end!

**Comment by erwinmombay** [comment]
fixed and published. Thanks so much again!
