### ISSUE TITLE
Intent to Implement Prebid as <amp-embed> type

### ISSUE THREAD

**Issue by protonate** [ampproject/amphtml#8024]
We would like to integrate Prebid header bidding wrapper with AMP as an `<amp-embed>` type.

Prebid.js is a client side library implemented on publisher pages that wraps multiple advertising demand partners to request RTB bids, run an auction, set targeting and call the ad server.

More Prebid.js info is here: prebid.org

**Comment by jpettitt** [comment]
Prebid already has AMP support http://prebid.org/dev-docs/how-prebid-on-amp-works.html

**Comment by jasti** [comment]
@protonate, curious to hear how this is different than what @jpettitt already points to. Thanks.

**Comment by protonate** [comment]
Current support is dependent on a custom `remote.html` file on publisher domain, so the intention here is to provide an alternative.

**Comment by jpettitt** [comment]
Out of curiosity, @protonate how would you do that within the no 3p javascript rules on the main page that AMP enforces?

**Comment by protonate** [comment]
@jpettitt our thinking there was to communicate across iframes using postMessage so the Prebid <amp-embed-prebid> would contain the Prebid.js library and would hold the Prebid demand, and the <amp-ad-prebid> slots would have their targeting (e.g. Prebid auction winner keys) set via postMessage from the <amp-embed-prebid>.

Basically, the goal is to have the <amp-embed> serve the same purpose as remote.html.

However it seems that remote.html will be reliable enough for the short term, and we might prefer to just focus on the Prebid A4A integration in this case. If so then this issue could be closed.

**Comment by jasti** [comment]
It is up to the ad networks. DoubleClick is planning to retire support for non-A4A remote.html integration. A new design is under consideration but won't be ready for at least another quarter. Agree that it's prob best to focus on the A4A integration.
