### ISSUE TITLE
Javascript AMP Validator does not complain about unprintable characters before the body

### ISSUE THREAD

**Issue by Gregable** [ampproject/amphtml#8028]
Consider any valid AMP document. Now prefix ﻿'\xef\xbb\xbf\xef\xbb\xbf' to the document. This new document is invalid, however the javascript AMP validator considers it valid. The javascript validator should consider it invalid.

**Why is this document invalid?**
﻿'\xef\xbb\xbf' is non-whitespace text. Non-whitespace text is only allowed inside the HTML5 body element. HTML5 parsing rules mean that the body element is inserted before ﻿'\xef\xbb\xbf' and any elements found later are placed inside the body element. This means that elements such as `<script>` or `<title>` wind up inside the document body, which makes the document invalid.

The javascript validator does handle these parsing rules, which can be seen by prefixing '⚡' to the document. However, the javascript validator does not see ﻿'\xef\xbb\xbf' as text.

**Comment by adelinamart** [comment]
@Gregable any updates here? Thanks.

**Comment by Gregable** [comment]
nope

**Comment by Gregable** [comment]
One annoying problem is that nodejs appears to strip these characters when reading a test file, so validation passes because the characters are not present. Browsers do not, however.

**Comment by Gregable** [comment]
It appears that this doesn't fully work yet. There are contexts, such as the npm cli tool, where these characters are being stripped from the document.
