### ISSUE TITLE
toggleVisibility/show actions not working globally (on any html element) as stated in the docs.

### ISSUE THREAD

**Issue by rgembalik** [ampproject/amphtml#8035]
## How do we reproduce the issue?

1. create div with `id="my-element" hidden`
2. create button with `on="tap:my-element.toggleVisibility"` or `on="tap:my-element.toggleVisibility.show"`
3. Display the page and try clicking the button

According to [this docs](https://github.com/ampproject/amphtml/blob/master/spec/amp-actions-and-events.md#globally-defined-events-and-actions) and [this example](https://github.com/ampproject/amphtml/blob/master/examples/standard-actions.amp.html) those actions should show element. 

Instead there is an error in console
```
Action Error: Target element does not support provided action in [tap:my-element.toggleVisibility] on [[object HTMLDivElement]]​​​ _reported_
```
and
```
Error: Action Error: Target element does not support provided action in [tap:normal-element.show] on [[object HTMLDivElement]]​​​ _reported_
```

## What browsers are affected?

Tested on Chrome 56.0.2924.87

## Which AMP version is affected?

I've seen that error few weeks ago, but though it may be lib not up to the docs. For sure example provided in master version doesn't work.

**Comment by aghassemi** [comment]
Hi @rgembalik, we pushed the docs too early :) feature is coming in the next prod push (it is currently in Dev Channel). Look out for it sometime late this week or early next week!

**Comment by rgembalik** [comment]
Thank you very much for the information. I am looking forward to this update.
Cheers!

**Comment by ovidiugabriel** [comment]
Yes, it is `on="tap:my-element.toggleVisibility"` or `on="tap:my-element.show"`.
Because `on="tap:my-element.toggleVisibility.show"` is not going to work.

But how to specify a class instead of `my-element`? For example I want to hide all elements in a class then show only one. Something like this `on="tap:(elements-class.hide and one-element-id.show)"`. It is possible with AMP?

**Comment by aghassemi** [comment]
@ovidiugabriel [amp-bind](https://www.ampproject.org/docs/reference/components/amp-bind) is better suited to handle your use-case.

A few resources below to get started with amp-bind:
https://www.ampproject.org/docs/reference/components/amp-bind
https://codelabs.developers.google.com/codelabs/advanced-interactivity-in-amp/#0
https://ampbyexample.com/components/amp-bind

**Comment by ovidiugabriel** [comment]
I have already tried to use amp-bind, but just from the documentation I do not understand how this will work for my usecase.
@aghassemi do you know how to use amp-bind ?

**Comment by aghassemi** [comment]
@ovidiugabriel Could you send us a simple non-AMP version of what you are trying to do (a URL or on jsbin or codepen would do).

**Comment by ovidiugabriel** [comment]
Of course. Here it is: https://codepen.io/ovidiugabriel/pen/OjWBJw

**Comment by aghassemi** [comment]
@ovidiugabriel `amp-selector` can handle this use-case. Please see this sample on AmpByExample.com that is fairly similar to your case: https://ampbyexample.com/advanced/tab_panels_with_amp-selector/

**Comment by ovidiugabriel** [comment]
Thanks a lot! It works great!

What about pushing the state in the browser history? Is there any component that allows me to do that?

**Comment by aghassemi** [comment]
@ovidiugabriel Good timing on your question about history :) @choumx recently started working on support for history API in AMP. Please see #9128 for details. Feedback is welcome!
