### ISSUE TITLE
Send error report if AMP document is rendered into 0 dimensions container

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#8044]
We've now had at least 2 regressions where pre-render container rendered AMP into iframes that are `display:none` and hence have no dimensions. This breaks pre-rendering as we consider nothing to be in viewport.

We should throw an error (out of execution flow) if we discover this, so that we can quickly discover such regressions.

CC @dvoytenko

**Comment by dvoytenko** [comment]
Duplicate of #8926.
