### ISSUE TITLE
Code like document.querySelectorAll('link[rel= trigger presubmit against destructuring

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#806]

**Comment by erwinmombay** [comment]
@cramforce can you clarify what you mean here by `destructuring`? thanks

**Comment by cramforce** [comment]
[foo, bar] = fn()

**Comment by erwinmombay** [comment]
removed from presubmit regex rules via https://github.com/ampproject/amphtml/pull/809

actual fix tracked in https://github.com/ampproject/amphtml/issues/808
