### ISSUE TITLE
How Fix errors on your AMP pages 

### ISSUE THREAD

**Issue by leonessaarnaldo** [ampproject/amphtml#8065]
How Fix errors on your AMP pages 

I activated amp on my wordpress site here https://leonessaarnaldo.com/ some weeks back and it went well at first.

Then I got a message on search console that some of my pages do not meet the guidelines and won't show. I checked and I noticed that there was no page that needed fixing (see image attached titled "amp page")

Then it says "Add required structured data to your AMP pages"

I also checked to fix the errors and I saw this http://prntscr.com/e9vmvx

Why do I keep getting these messages?

I noticed a 404 page earlier today on my site - https://goo.gl/fsfIf3

What is wrong with my AMP pages?

**Comment by dangoldin** [comment]
You can validate a specific page by adding "#development=1" to the end of your URL. Then by going into the console you'll see what is causing the page to be invalid AMP.

Check out the docs for more: https://www.ampproject.org/docs/guides/debug/validate

**Comment by aghassemi** [comment]
@leonessaarnaldo https://validator.ampproject.org/ is another resource and I personally find the AMP's Chrome Extension ( https://chrome.google.com/webstore/detail/amp-validator/nmoffdblmcmgeicmolmhobpoocbbmknc?hl=en ) very useful as well for caching errors early on.

**Comment by adelinamart** [comment]
@leonessaarnaldo do you still have any other questions here? feel free to reopen if so.
