### ISSUE TITLE
suggestion: component to render json

### ISSUE THREAD

**Issue by gustavopaes** [ampproject/amphtml#8071]
Today we can make a JSON request and render the result using `amp-list`.

But not always the API returns an Array, required by `amp-list` .

Would be nice to have an component that could render some json (with no patterns) using `amp-mustache`.

**Comment by aghassemi** [comment]
Thanks @gustavopaes . We are working on providing more dynamic rendering functionalities such as https://github.com/ampproject/amphtml/issues/4191 and https://github.com/ampproject/amphtml/issues/7907. 

However a single-item `amp-list`  can actually cover this as a work-around for now. As you noted, data still needs to be a JSON array with one item in it, but in practice you can render an arbitrary template this way. 

Take a look at this talk from AMP Conf which shows how developers are using amp-list to render fresh data: https://youtu.be/E2_eXhv1Jhg?t=2h36m39s
