### ISSUE TITLE
Suggestion: Support for linked CSS/CSS caching

### ISSUE THREAD

**Issue by dangoldin** [ampproject/amphtml#8076]
I realize this is a pretty big change and contradicts the intent of AMP but I've been using it exclusively for my personal blog (http://dangoldin.com/) and in fact don't even keep a non-AMP version. It's been great and I'm a huge fan but one issue I've consistently been running into is the fact that if I need to make any change to the CSS each page needs to be rebuilt which takes a fair bit of time.

This forces my workflow to be a bit weird where I move the majority of my content to a temporary folder so I can iterate quickly and then move the content back when I'm done and ready to do a full build.

Is there a way to avoid this step since I suspect as more and more content gets developed using AMP it will cause these sorts of performance issues during development. It also contradicts the idea of separating content from styling and while I understand the motivation there should be a hybrid solution. What if we allow CSS linking but make it a unique AMP tag that must be loaded first before rendering is done? This would make a single additional HTTP request but if it's cached would be a no-op and would make it significantly easier to develop for AMP.

**Comment by aghassemi** [comment]
@dangoldin external CSS is not something we are considering to support at this point. Aside from the extra network request which blocks rendering, we also need to validate the CSS and externally hosted CSS can change at anytime making validation much harder.

For development, assuming your build process can not be optimized further, one approach is doing development with invalid AMP HTML and having your build process inline the CSS files for you to make it valid. For example, use `<link>`s to your externally served CSS files in your pre-built AMP page during development (making it invalid) but then have your build process inline the external CSS files' content and remove them making your page valid again.

**Comment by dangoldin** [comment]
Yea - I figured as much and that is very close to my current development process but the final build ends up taking a few minutes which I would love to speed up.

Thanks for the response.
