### ISSUE TITLE
Document overflow element

### ISSUE THREAD

**Issue by Nicola1976** [ampproject/amphtml#8085]
## Short description of your issue:

I have an permanently error on amp-ad resize API on Open AdStream (OAS) adserver. 

The error is:
_476 "[CustomElement]" "Cannot resize element and overflow is not available"_ 

Starting from this guide (https://github.com/ampproject/amphtml/blob/master/ads/README.md#ad-resizing) In my ad creative I wrote:
 
_window.context.requestResize(300, 600);_

Public URL to reproduce issue:

https://stadvtools.akamaized.net/xaxsis/common/googleAMP/AMP-AD/indexAmpDemo300600.html#development=1

**Comment by zhouyx** [comment]
This is happens when you doesn't provide `overflow` element and runtime fails to increase an ads size. Warning from:
https://github.com/ampproject/amphtml/blob/master/src/custom-element.js#L1642

Can we remove the warning here? As what I see very few overflow elements are being used. We should also document the oveflowCallback better I guess @camelburrito @dvoytenko

**Comment by jridgewell** [comment]
to @bpaduch to document the overflow element.

**Comment by dvoytenko** [comment]
Let's document. But let's not remove yet. I'd actually rather make it a user (or expected) error and monitor from our error logs how often this happens.

**Comment by bpaduch** [comment]
@zhouyx, @dvoytenko, @jridgewell 

Can you all clarify what is to be documented?

1) Is it the `overflowCallback` method?  If so, where should this be documented?  Do people who create custom elements expect to call that method, under what circumstances, etc.
2) Is it the `overflow` element?  If so, for what and where? Does it need to be clarified in [Ad resizing](https://github.com/ampproject/amphtml/blob/master/ads/README.md#ad-resizing)? Something like:

You can specify an overflow element that is only shown when a resize request is declined. When the user clicks the overflow element, the resize will pass the "interaction" rule and will resize.

```html
<amp-ad type="...">
  <div overflow>Click to resize</div>
  <!-- whatever else -->
</amp-ad>

**Comment by jridgewell** [comment]
Just the `overflow` element, `#overflowCallback` is an internal API. It should be mentioned for ads and iframes. You're example sounds perfect to me.

**Comment by priver** [comment]
And what if I want to create my own overflow element in window.context.onResizeDenied callback? Is there any way to get rid of this warning?

**Comment by jridgewell** [comment]
Is this for an ad?

**Comment by dvoytenko** [comment]
@priver I think it'd be certainly fine if 3p context decides to render overflow element itself and, indeed, we should forgo warning in this case. We only need it for legacy situations that do not expect this. So, we need to create an instrument how to communicate this back to the parent page that iframe can handle it. 

To double on @jridgewell 's question - which component is affected here? An ad? `amp-iframe`? Something else?

**Comment by priver** [comment]
@jridgewell @dvoytenko Yes, it is for`amp-ad/amp-embed`.

**Comment by dvoytenko** [comment]
@priver Yeah, I think we can remove warning in this case. What ad network is this?

**Comment by priver** [comment]
@dvoytenko This is for `<amp-embed type="mywidget">`.

Our widget recommends content from the same site it's installed ("Read more..." block), and it is typically placed below main content (outside initial viewport), so in most cases call to `window.context.requestResize` would be successful. In rare cases when resize is denied (e.g. main content is short) we want to create overflow element by ourself and not make our customers change their code. It is work as expected, but we get this warning in the console.

Changes with widget resizing is not yet released (we planning release on next week, and after that we also need to make PR to amphtml repo).

**Comment by dvoytenko** [comment]
@priver I see. I added this request: #11154. I think it can be done this way. Not yet sure how `context.requestResize` API will change, but we'll plan to update it soon.

**Comment by priver** [comment]
@dvoytenko Thanks!
