### ISSUE TITLE
Migrate 3P ads postMessage API to new format

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#8087]
#6829 introduced a new format for the window.context postMessage APIs. We will need to migrate existing 3P ads to the new format.

Remaining items:
- [x] clean up experiment flag: `sentinel-name-change`
- [x] serialize/deserialize messages sent/received by `integration.js` using the same function as ampcontext API does

/cc @bradfrizzell

**Comment by lannka** [comment]
Marked as P1, as it blocks a few other things.

**Comment by jasti** [comment]
@ampproject/a4a FYI

**Comment by bradfrizzell** [comment]
I will get this moving as fast as possible, but a heads up that I am at a conference this week, and then I am on vacation until 3/28. Not sure how much I'll get done on this before I get back. How badly is this blocking you?

**Comment by lannka** [comment]
@bradfrizzell no worry, I will take care of it

**Comment by alanorozco** [comment]
Taking over :)

**Comment by alanorozco** [comment]
Should be done. Need to enable feature flag for canary sometime in the future.
