### ISSUE TITLE
amp-ad : centering image in flying-carpet

### ISSUE THREAD

**Issue by coreybyrnes** [ampproject/amphtml#8097]
I'm trying to horizontally and vertically center a DFP ad in the flying-carpet component when the image in the ad is larger than the flying-carpet container. For my test case the ad size for my creative is 1600x1000 and I'm serving a 1600x1000 image. It looks like if I could somehow resize the <amp-ad> tag upon load from 1600x1000 to 100vw and 100vh it would sit perfectly centered in both portrait and landscape modes. From what I understand `requestResize` is only available upon user interaction. Is there any other way to manipulate the dimensions of the <amp-ad> tag at the time the ad loads so I can get this to work? Perhaps I have to do it through an 'amp-3p-iframe-src' js? Thanks!

To reproduce, simply modify the width and height of the <amp-ad> tag to 100vw and 100vh in the browser developer tools at the following test url:
http://rev.cbsi.com/corey/test/amp/amp_demo_flying-carpet_v2.html

**Comment by jasti** [comment]
@coreybyrnes requestResize is available even when the ad is away from the viewport, but obviously won't succeed all the time. 
@jridgewell This seems reasonable - any chance to center align and fit the creative regardless of actual size?

**Comment by coreybyrnes** [comment]
@jasti But doesn't `requestResize` require user interaction in order to execute? In order for an ad image to be centered when served inside the flying-carpet container the resize would have to occur upon load.

**Comment by jridgewell** [comment]
`requestResize` has [several factors](https://github.com/ampproject/amphtml/blob/master/ads/README.md#ad-resizing) that determine whether it will succeed.

1. Whether user interacted with ad (this always succeeds)
2. Ad position in relation to viewport (we don't resize things in the viewport)
3. Scroll speed (for ads that are above viewport)

We actually wanted to include a special exception for `<amp-fx-flying-carpet>` children (like your ad) to allow resize whenever. This is because the children are on a physically different layer than the scroll layer, so it can't affect the user scroll position at all. But, we never got around to coding this exception. 😳

For now, go ahead and do a `requestResize`. It may fail, and you can go through the overflow element process like the other ads to get the resize to succeed after the user interacts.

This'll be fixed implicitly by #3434 (scroll layers get resize exceptions, which means the flying carpet too). I'm actively working on it, with a ship date sometime in the next few months. Or we can codify the exception in the current system, but I'd rather not waist my time for now. /cc @jasti

**Comment by coreybyrnes** [comment]
@jridgewell Unfortunately `requestResize` doesn't allow me to set 100vw and 100vh for the size (hopefully will get implemented in #8095). And I can't find a way to obtain the exact viewport dimensions so I can use a px value when trying to call `requestResize`. Just to see if the resize will be successful I will try to call `requestResize` with some crazy large number like 3000,3000. But without setting the <amp-ad> to exactly the dimensions of the viewport, the ad asset will not be centered. So I guess I'll have to wait for #3434 to be in prod?

Also, can you explain this more please? Thanks!
> It may fail, and you can go through the overflow element process like the other ads to get the resize to succeed after the user interacts.

**Comment by jridgewell** [comment]
You can use `window.innerWidth` and `window.innerHeight` instead. Those return pixel numbers, which is what `requestResize` expects.

> Also, can you explain this more please? Thanks!

#8085. 😬

Bascially, we allow you to specify an overflow element that is only shown when a resize request is shown. When they click it, the resize will pass the "interaction" rule and will resize.

```html
<amp-ad type="...">
  <div overflow>Click to resize</div>
  <!-- whatever else -->
</amp-ad>

**Comment by jridgewell** [comment]
Ha, but `innerWidth` and `innerHeight` don't help here, because the iframe is already 1000x1600 px. Maybe @dvoytenko knows the right DOM API?

**Comment by coreybyrnes** [comment]
@jridgewell But from within a DFP ad the `window.innerWidth` and `window.innerHeight` will simply return the size of the iframe which is the size of the ad slot.

**Comment by jridgewell** [comment]
Speaking with @jasti, there's no way to specify 100vw and have an ad server know what width that means. Which means a lot of them fail to fill the request. I hate ad servers.

**Comment by dvoytenko** [comment]
I think the best option is to give the ad the full available width. The iframe's window will have the right width then (`window.innerWidth`). Then the Ad can serve the desired size and ad can request resize, which will be to the smaller size. Once updated to the smaller size, the ad can be centered in the flying carpet via flexbox CSS.

**Comment by coreybyrnes** [comment]
@dvoytenko And since we need we'd need the image to be centered vertically in addition to horizontally we'd need the `amp-ad` tag to have the full height. Please see my demo url in the first comment to reproduce the issue.

**Comment by jridgewell** [comment]
@dvoytenko Are you saying we should do centering logic in the AMP doc instead of inside the ad creative?

**Comment by dvoytenko** [comment]
@jridgewell I don't think creative itself can do that very well. I'm wondering if we can find a way for flying carpet component to do the right thing naturally.

**Comment by coreybyrnes** [comment]
@dvoytenko That would be great as well. I'm on the fence if it's best to allow this to be set at the creative level or as an attribute of <amp-ad> or <amp-fx-flying-carpet>. I would assume that most ads running in this slot would want to be vertically and horizontally centered relative to the viewport, but perhaps not so maybe having the option to set its position at the creative level is best. But in order to do that I believe the <amp-ad> tag has to be set to 100vw and 100vh. Then the <amp-fx-flying-carpet> container can be set to the actual height of the see-through "window". If you're worried about the height of the <amp-fx-flying-carpet> container being set to 100vh then that could become a restriction of the component - it won't serve if it's set to 100vh for example. Just trying to help think this all through.

**Comment by dvoytenko** [comment]
@coreybyrnes The concern I have specifically here is that Ad normally has very limited info how it's hosted, in what container. Thus, `100vw/100vh` would typically be overflowing in many cases, e.g. if flying carpet has a padding or another container is sized differently. The way I see it, the container has to somehow communicate to the Ad how much possible space it can get. Currently we do this by giving the Ad the maximum width. In this case, the Ad's width could hypothetically be reduced and the Ad's height could be reduced or increased. This, of course, is not always true. E.g. in case of flying carpet, the maximum height cannot realistically be more than `100vh`.

So, going back to the use cases, what I meant was:
```
<amp-fx-flying-carpet>
  <amp-ad width=300 height="200" ...></amp-ad>
</amp-fx-flying-carpet>
```

This should simply center the 300x200 ad in the viewport. The iframe's window would have `innerWidth=300` and `innerHeight=200`. The embed can then measure and allow height to increase/decrease. If height changes, the Ad should be re-centered.

If Ad is intrinsically responsive (which is rare), it's fine to use this markup:
```
<amp-fx-flying-carpet>
  <amp-ad layout="fill" ...></amp-ad>
</amp-fx-flying-carpet>
```

In this case, the iframe's window size will be viewportWidth x viewportHeight. In this case, the Ad would either be responsive enough to fill the space or center its main content. Or it can ask for smaller width/height, in which case flying carpet will do the centering.

If we want more control, we can think about how we can pass maxWidth/maxHeight to the Ad.

**Comment by coreybyrnes** [comment]
@dvoytenko Thanks for your continued dialogue - I'm determined to get this figured out because the flying-carpet is not really usable in its current form for us at CBS. 

So what about horizontally and vertically centering in the case of a creative that will almost always be larger than the viewport... like the test case I'm trying to solve for with a 1600x1000? My thought is that the flying-carpet component isn't a normal ad because the framework of it should be thought of as a "window" that allows you to see through to a full-screen background instead of simply occupying the space dictated by the ad size.

I tried `layout="fill"` (instead of `fixed`) and I see that it adopts the width and height of the parent so I set the parent `amp-fix-flying-carpet` element with 100vw and 100vh. With that the dynamically inserted `.-amp-fx-flying-carpet-container` element isn't assigned a height property so the ad doesn't have any real estate so the ad doesn't appear.

Again here's my test url: http://rev.cbsi.com/corey/test/amp/amp_demo_flying-carpet_v2.html

And here's the current flying-carpet/amp-ad html:
`<amp-fx-flying-carpet style="width:100vw; height:100vh;">
	<amp-ad width="1600" height="1000"
		layout="fill" 
		type="doubleclick" 
		data-slot="/7336/corey/amp-flying-carpet"
		json='{"useSameDomainRenderingUntilDeprecated":1}'
	></amp-ad>
</amp-fx-flying-carpet>`

**Comment by dvoytenko** [comment]
@coreybyrnes Thanks for an example! Let me play around with it and see what could be improved.

**Comment by coreybyrnes** [comment]
@dvoytenko Great. Let me know if you have any other questions for me as you dive into it or if it'd be helpful to have a g-hangout session to talk things through.

So as I see it there are two items for further discussion:

1. How to reduce the "window" height of the flying-carpet by setting a `height` and `overflow:hidden` on the parent element of the `amp-fx-flying-carpet` element.

2. Update the flying carpet component to set the height of the `.-amp-fx-flying-carpet-container` element to be the height of the viewport (the width is already being set to be the width of the viewport, just the height assignment is missing) when `layout=fill` on the `amp-ad` element.

**Comment by coreybyrnes** [comment]
@dvoytenko 

1. I don't have styles on the `.ad-wrap` element at the moment. But I _want_ to able to do so because I need to reduce the height of the "window" to be less than 100vh (to something like 200px for example). It's not working as I mentioned in item #1 [in this comment](https://github.com/ampproject/amphtml/issues/8097#issuecomment-288165607).

2. It looks like you also removed `100vw` from the `amp-fx-flying-carpet` element? Are we sure it doesn't need to be there? If `layout=fill` on the `amp-ad` element, doesn't it look to the parent element for a width and height?

3. Great to see that you'll be adding `height:100%` to the `.-amp-fx-flying-carpet-container` element! That will make it much more intuitive for other users. Thanks for implementing my suggestion!

4. Do you need the additional styles on `.-amp-fx-flying-carpet-container` element in order to center the content though? I don't have those styles and it's centering fine for me.

5. We don't want the image to scale. We want it to clip and we want to be able to serve whatever size asset in that space, large or small. It sounds like using the `layout` property of the `amp-ad` tag could provide that option though? I think if it's set to `fill` then the user does not want a scaled implementation.

6. On the last item you brought up, you must include a width and height on the `amp-ad` element because that's how the publishing platform (DFP) knows which ad size to serve. If you leave out the width and height or change it to something other than 1600x1000 then no ad will serve because none can be found.

**Comment by dvoytenko** [comment]
@coreybyrnes 

g-hangouts and/or Slack would work great. Ping me on slack.

> But I want to able to do so because I need to reduce the height of the "window" to be less than 100vh (to something like 200px for example).

I think I misunderstood what "window" means in this case. Could you describe this a bit more?

> It looks like you also removed 100vw from the amp-fx-flying-carpet element?

FC container always gets `100vw` by default. Defined [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-fx-flying-carpet/0.1/amp-fx-flying-carpet.css#L47). Thus `layout=fill` child will likewise get `100vw`.

> Do you need the additional styles on .-amp-fx-flying-carpet-container element in order to center the content though? I don't have those styles and it's centering fine for me.

The centering can be basically accomplished two ways: 
 1. Center the embed (iframe). E.g. iframe gets 300x150px as an example and centered.
 2. Make embed (iframe) full viewport size and let it center its content. E.g. iframe gets 100vw x 100vh (412x732) and then uses its own tools to center.

Both are fine. Obviously, it can be said that `layout=fill` embed that's resized on the full screen is also centered :)

> We don't want the image to scale. We want it to clip and we want to be able to serve whatever size asset in that space, large or small. It sounds like using the layout property of the amp-ad tag could provide that option though? I think if it's set to fill then the user does not want a scaled implementation.

I think it's what I did in the http://output.jsbin.com/lexileg/quiet, right? Or do we want more out of this case?

> On the last item you brought up, you must include a width and height on the amp-ad element because that's how the publishing platform (DFP) knows which ad size to serve. If you leave out the width and height or change it to something other than 1600x1000 then no ad will serve because none can be found.

So this is still the part I'm confused about. Do you want 1600x1000 to be passed to ad network? Or do you want the actual size passed (e.g. for iPhone 6 it'd be 375x667)? Or some other predefined size. It sounds like you want to do the actual size of the resized ad (layout=fill). But this is somewhat uncommon - most of ads are served for predefined set of sizes. Please clarify.

**Comment by coreybyrnes** [comment]
@dvoytenko  

I submitted a request to join the AMP Slack channel just now. Once I am accepted I will be able to reach out to you there.

The "window" is the container where you can see through to the image that is fixed in the background. Here's an example to more clearly demonstrate: https://jsfiddle.net/354xovo1/23/ Currently the "window" is 100vh because of `layout=fill` but we'd want to control the "window" height and set it to something like 50vh or 200px for example. That was why I included the `.ad-wrap` element as the parent of the `amp-fx-flying-carpet` element. I was hoping to be able to apply a `height:50vh` and `overflow:hidden` to that element. Unfortunately when I do that, the `amp-fx-flying-carpet` element is hidden by AMP with a `display:none` and it can't be overridden via css.

Correct, you are not scaling the image in your example and and that is exactly what we want.

The 1600x1000 in this case is simply the ad size in DFP. It could be 1x1 or it could be 100000x100000. That property of the `amp-ad` tag simply pulls in creatives of that size in the ad unit (data-slot property) in DFP. We want to be able to have an image of any dimension serve in that creative, be it a 1600x1000 or a 300x250 or a 1000000x1000000). We do this very often in a lot of our ad slots across our CBSi network of sites - the ad size according to DFP is not necessarily the creative size.

**Comment by coreybyrnes** [comment]
here's the final code that acheived the vertical and horizontal centering of an image that is larger than the flying carpet "window"

`<amp-fx-flying-carpet style="width:100vw; height:50vh;">
	<amp-ad width="1600" height="1000"
		layout="fill" 
		type="doubleclick" 
		data-slot="/7336/corey/amp-flying-carpet"
		json='{"useSameDomainRenderingUntilDeprecated":1}'
	></amp-ad>
</amp-fx-flying-carpet>`

**Comment by lannka** [comment]
> Speaking with @jasti, there's no way to specify 100vw and have an ad server know what width that means. Which means a lot of them fail to fill the request. I hate ad servers.

Not true for doubleclick anymore. you can use `data-override-width` to provide a different width.
see [documentation](https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad-network-doubleclick-impl/amp-ad-network-doubleclick-impl-internal.md#ad-size)
