### ISSUE TITLE
I get an error with 'amp-bind'

### ISSUE THREAD

**Issue by pearlwang1106** [ampproject/amphtml#8110]
When I visited the site: https://ampbyexample.com/advanced/image_galleries_with_amp-carousel/, an error showed as the picture:
![image](https://cloud.githubusercontent.com/assets/22272732/23882928/b18ce2cc-089e-11e7-8560-54ed5b60261e.png)

**Comment by kmh287** [comment]
Hi @pearlwang1106 ,

Are you still getting this error after toggling the experiment near the top of the page?

**Comment by jridgewell** [comment]
This is a cookie setting error with `toggleExperiment`. If you already have a cookie `AMP_EXP` with domain `ampbyexample.com`, it will create a new cookie (enabling amp-bind) using the domain `.ampbyexample.com`. But that's less specific, so we still get the old cookie without the experiment enabled.

**Comment by jridgewell** [comment]
Unfortunately, there's not a good solution to this. Cookies are kind of a shitty system made standard. And browsers each behave differently when updating, so there's no way to know which of the duplicate cookies is the "most updated".

This (`toggleExperiment`) is such a little used feature, I'm tempted to close as a cantfix. You can manually fix by deleting the `AMP_EXP` cookie in your browser. Defering to @cramforce

**Comment by cramforce** [comment]
This is a little unfortunate.
@sebastianbenz This may affects some of your most loyal users, but would also take a while to fix.

@pearlwang1106 Were you able to unbreak yourself? You can delete the `AMP_EXP` cookie with Chrome DevTools.

**Comment by pearlwang1106** [comment]
The error still exits when i deleted  the `AMP_EXP` cookie and refreshed the page:
![image](https://cloud.githubusercontent.com/assets/22272732/23978583/d2ecb19e-0a2f-11e7-8829-65a0bcf4eb31.png)

**Comment by cramforce** [comment]
@pearlwang1106 Sorry about that. You now need to press the "Enable experiment" button again.

Let me know if that works!

**Comment by pearlwang1106** [comment]
Thx, it works!

**Comment by jridgewell** [comment]
Assigning this to @sebastianbenz then.

**Comment by sebastianbenz** [comment]
When is the AMP_EXP cookie set without the dot at the beginning?

**Comment by jridgewell** [comment]
It's the old style, before we moved to CURLS. Everything is now set with the dot.

**Comment by cramforce** [comment]
It used to be set without a domain. Now the domain is set explicitly. The dot is added by Chrome for "visualization purposes", because the actual cookie syntax is crazy.

Unfortunately people who had the old cookie get to keep both, because they are technically different.

**Comment by sebastianbenz** [comment]
aah - now 'most loyal users' makes sense as well. Thanks for the explanation. I'd say 'Won't fix' for now - if this happens more often we can add a fix in the toggle experiment action. I don't have permission to change the bug status, so someone else needs to do it...
