### ISSUE TITLE
amp cache modifications should have amp-experiments-opt-in right after meta charset

### ISSUE THREAD

**Issue by dknecht** [ampproject/amphtml#8112]
`<meta content="experiment-a,experiment-b" name="amp-experiments-opt-in">`

**Comment by dknecht** [comment]
@Gregable @honeybadgerdontcare  I am pretty sure you google's amp cache already does this optimization.

**Comment by dknecht** [comment]
Looks like google cache just leaves it wherever it was originally.

**Comment by honeybadgerdontcare** [comment]
Yes, that is what we're currently doing. We'll move it to be before the AMP engine javascript, but after charset.

**Comment by honeybadgerdontcare** [comment]
PR #8421 addresses this for documentation: moving all `<meta>` tags as first children of `<head>`.
Google AMP Cache will start doing this shortly.
