### ISSUE TITLE
IFrame Resizing: allow resize to reduce height

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#812]
Currently we do not allow automatic resizing to reduce height. This is to avoid cases where iframes overshoot the height requirements to simply lower them later. We can explore when this can be done safely.

**Comment by dvoytenko** [comment]
The reduce-height case should work slightly differently vis-a-vis increase-heigh. E.g. when the bottom of the collapsing element is in viewport we should not allow it to collapse.

**Comment by cramforce** [comment]
Actually for the collapse case, we really don't want to allow this if the element is currently visible on the page I think. But I could be convinced otherwise. The 25% slack for the "bottom" rule is definitely too much.

**Comment by ericlindley-g** [comment]
amp-iframe documentation doesn't seem to indicate resize must only increase height—can you clarify if this restriction is still in place? (may need to update docs, cc @Meggin)

**Comment by dvoytenko** [comment]
All fixed already. Closing.
