### ISSUE TITLE
Post-reserialization mode for JavaScript validator

### ISSUE THREAD

**Issue by taymonbeal** [ampproject/amphtml#8120]
AMP caches are advised, and Fast Fetch signing services are required, to reserialize AMP documents that they process. The output of such a reserialization process obeys a stricter set of requirements than the AMP specification, such as [HTML sanitization](https://developers.google.com/amp/cache/overview#html-sanitization); in addition, the output is not itself valid AMP. For purposes of integration and regression testing by parties other than the AMP core team (both inside and outside Google), it would be useful for the JavaScript validator to have a mode which verifies that its input could have been the output of such a reserialization process.

**Comment by jridgewell** [comment]
Wouldn't this be easier as a set of fixtures to test on? I.e. a set of input docs with the proper outputs to verify conformance?

**Comment by Gregable** [comment]
@taymonbeal , I could implement such as { return true; }. It would help to understand, what are the use cases we are trying to catch here (the return false cases we'd like to see)? 

For example, one of the things that the cache does is add rtv values to all of the javascript files. This means that the validation pass would either need to allow any rtv value, thus being less strict than possible, or it would need to be updated along with the releases for javascript, which makes it more difficult to use.

**Comment by taymonbeal** [comment]
My immediate use case is black-box functional testing of Google's ad serving systems; I'd like to determine whether an ad is valid post-reserialization AMP HTML just by analyzing the HTML (and this is in a context where I can run JavaScript). In future, I anticipate this being used to verify that signing services are obeying their behavioral requirements, both by developers of those signing services in testing/debugging and by third parties in auditing.

The two most important things that I'd want to assert are:
* That the page is valid AMP except in those respects wherein the output of caches and signing services is allowed to differ from the AMP spec. For instance, it has the ⚡ attribute, it's well-formed UTF-8, it doesn't contain disallowed elements like non-AMP-runtime scripts, etc.
* That the HTML sanitization requirements are followed. For instance, no unclosed tags, no unescaped special characters, etc.

As for the rtv thing, the asserted behavior should be whatever the reserialization spec requires. If we're going to require, e.g., Cloudflare to always be serving the latest rtv from cdn.ampproject.org, then the post-reserialization validator should check for that (which would indeed require a weekly update). If the requirements we impose are not so strict, then the validator can similarly be more lax. I expect that some of this behavior is not currently unambiguously specified, in which case specifying it is a prerequisite. Indeed, one of the things I'm hoping to get out of this is a reserialization spec unambiguous enough that it can be implemented in code (even if that spec is just the open source validator implementation itself).

**Comment by Gregable** [comment]
To check, this sounds like you don't intend this code to be generally available to a publisher for instance? My point wouldn't be that it would be closed-source or anything, just that it need not be easy-to-use in all contexts like the current validator. For example, making a network request to determine from ampproject.org the current RTV value might be reasonable.

Another issue, I think a large part of this test would probably need to include the input document into this serving system. For a trivial example, a serving system shouldn't be able to pass the test by always serving [this file](https://github.com/ampproject/amphtml/blob/master/validator/testdata/feature_tests/minimum_valid_amp.html). A serving system would not be compliant if it always just stripped any HTML it couldn't handle.

**Comment by dknecht** [comment]
I think we are fine saying the RTV is (latest - 1) to give some flexibility in deployment requirements.

**Comment by taymonbeal** [comment]
Correct, publishers are not the target audience; the target audience is AMP caches, Fast Fetch signing services, and people doing ecosystem-audit-ish things, all of whom should be technically sophisticated enough to work with GitHub. A network request would be fine.

For my immediate use case, I won't have a pre-serialization document to compare to, so that provision would need to be optional (the requirement that the ad server not serve hello world.amp.html will instead be enforced with screenshot diffing). That said, including a feature to check that a reserialized document matches the original except where otherwise permitted by the spec sounds like a wonderful idea.

**Comment by Gregable** [comment]
As this isn't currently prioritized work, I thought I'd mention a workaround that will probably serve your needs.

Run the regular AMP validator over your output, and build a small whitelist of errors that you see on correct test cases. Examples would include RTV cases. I suspect this list is reasonably small, though I don't think I could enumerate them off the top of my head. For example, no cache is going to emit an `<applet>` tag into the page.

**Comment by Gregable** [comment]
Closing this issue as it's no longer a priority. Discussed offline with the issue author.
