### ISSUE TITLE
Variable substitution for whitelisted origins is not documented.

### ISSUE THREAD

**Issue by honeybadgerdontcare** [ampproject/amphtml#8132]
Issue #6141 brought this up and it was committed in #7344. This still needs to be documented as the only documentation right now is the issue itself.

Whitelisted origins are achieved by adding a meta tag like this: `<meta name='amp-link-variable-allowed-origin' content='https://www.othersite.org https://www.yetanothersite.com'>`

**Comment by cvializ** [comment]
There is documentation for this feature in [amphtml/spec/amp-var-substitutions.md](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#whitelisted-domains-for-link-substitution) and it was merged by #8234. Does it need to be documented elsewhere or is this technical spec sufficient to close this issue?

**Comment by rudygalfi** [comment]
I think the documentation I added should cover this. Closed by #8234
