### ISSUE TITLE
amp-bind: Improve error handling for mutatedAttributesCallback

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#8137]
/cc @jridgewell

**Comment by choumx** [comment]
This actually isn't an issue since we use closures for iteration. We should catch the error and wrap it in a user error and make the message more useful though.

**Comment by jridgewell** [comment]
> This actually isn't an issue since we use closures for iteration.

How does a closure help?

**Comment by choumx** [comment]
I misspoke, it's not an issue because the method invocation is the last action in the vsync task (via `mutateElement`) which is the bottom frame in the stack.
