### ISSUE TITLE
Implement iframe resizing for amp-ad

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#814]
Same behavior as amp-iframe. See #728

**Comment by jmadler** [comment]
Does this cover 3p embeds as well, or will we need a separate issue to track that?

**Comment by cramforce** [comment]
@jmadler Basically yes. For non-generic embeds there will be a small bit of code in the element implementation. Single function call should do it.

**Comment by cramforce** [comment]
@dvoytenko Can you take this on or should we redistribute?

**Comment by dvoytenko** [comment]
I'll assign to @sriramkrish85 . He just recently had to deal with it.
