### ISSUE TITLE
amp-instagram render scrollbar if the post is not square

### ISSUE THREAD

**Issue by arunnayak** [ampproject/amphtml#8144]
amp-Instagram render scrollbar if the post is not square

<amp-instagram
    data-shortcode="fBwFP"
    width="800"
    height="800"
    layout="responsive">
</amp-instagram>

when the Instagram post is not square, the scrollbar appears.
this is working fine with the posts which are square (1x1 )
is there any workaround to remove that scroll bar?

![capture](https://cloud.githubusercontent.com/assets/402973/23932087/0250f342-098a-11e7-90a8-45723c0c9d7b.PNG)

**Comment by aghassemi** [comment]
@arunnayak  what `width` and `height` values are you using for the embed?  These should be the actual width and height of the Instagram **_image_**

**Comment by arunnayak** [comment]
@aghassemi that widget is added from cms, we're using one amp-instagram partial to render all the instgram widget through the cms.

this is an issue only when the post (image) is not square.
diff post will have diff image sizes, therefore the 1x1 ratio doesn't work or vise verse.

**Comment by aghassemi** [comment]
@arunnayak so do you know what `width` and `height` values the CMS is adding to the `<amp-instagram>` component it creates? Cause that matters, if CMS is blindly putting `width=1` and `height=1` , it won't work for non-square images as you mentioned.

**Comment by jpettitt** [comment]
The instagram iframe messages its parent with a small json payload `"{"type":"MEASURE","details":{"height":528}}"` asking to be resized.  How hard would it be to make amp-instagram listen for that and do the right thing? (if somebody can point me to an example amp extension that receives messages I'll add it to `amp-instagram` and do a pr).

**Comment by aghassemi** [comment]
@jpettitt It already does (https://github.com/ampproject/amphtml/pull/7705). This change just went to prod few hours ago.

**Comment by aghassemi** [comment]
Closing since #7705 is in production now.
