### ISSUE TITLE
AMP forces sticky element to use top CSS property

### ISSUE THREAD

**Issue by eduardcotmrf** [ampproject/amphtml#8149]
AMP forces my sticky element to be 'top: calc(0px)'.

To reproduce:

1. create an element with the next css:
{
  position:sticky;
  bottom:0;
}

2. When I render in the browser AMP has added a top property to my element:

![screen shot 2017-03-15 at 11 24 16](https://cloud.githubusercontent.com/assets/23262331/23944095/f7f9b7ac-0971-11e7-8d8b-c0f3396ccb8b.png)

I understant that this behaviour is related to this fix https://github.com/ampproject/amphtml/pull/7767 , are you planing on implementing the bottom property as well when it's sticky?

Thanks,

**Comment by dvoytenko** [comment]
Definitely sounds like a bug. I will investigate. `top: auto` is relatively hard to detect, but I thought we had that covered.

**Comment by dvoytenko** [comment]
This is due to Chrome's bug: https://bugs.chromium.org/p/chromium/issues/detail?id=703816

I will see if we can work it around until it's fixed.

**Comment by dvoytenko** [comment]
PR #8303 is in review.

**Comment by eduardcotmrf** [comment]
Thanks for the fix @dvoytenko  and the quick response!

**Comment by dvoytenko** [comment]
@eduardcotmrf Thanks a lot for reporting. Should be in Canary today.
