### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by ankit4794** [ampproject/amphtml#8155]
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://cdn.ampproject.org' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

how to solve this error?

**Comment by aghassemi** [comment]
@ankit4794 https://github.com/ampproject/amphtml/blob/master/spec/amp-cors-requests.md has  detailed documentation on what you need to do on your endpoints to allow CORS requests from AMP. Please take a look and let us know if you still have questions.

Thanks!

**Comment by ankit4794** [comment]
i added "<IfModule mod_headers.c>
    Header set Access-Control-Allow-Origin https://cdn.ampproject.org  
    Header set Access-Control-Allow-Credentials true
</IfModule>"
in my root .htaccess file..

but still not working.

can i know how to solve this?
