### ISSUE TITLE
amp-ad-3p integration test fails locally

### ISSUE THREAD

**Issue by piotrwojtkowiakmrf** [ampproject/amphtml#8177]
Hey,

It seems that some tests are not perfectly isolated from each other, and because of that we're getting a lot of errors in CI and in the local environment when running `gulp test`.
Can we block PR if tests are failing? This could prevent the master branch from continuously failing in CI, and it would give us more reliable test results.

Thanks,
Piotr

**Comment by aghassemi** [comment]
Hi @piotrwojtkowiakmrf 

Our presubmit process for PR does run `gulp test` before allowing them to merge. Reason `master` is sometimes red is that master runs the tests in many more browsers using SauceLabs than the PR does and sometimes tests that are not compatible with older browsers get in.

How are you running the tests in your CI? I recommend the same setup as our CI:
```
gulp dist --fortesting
gulp test --nobuild --compiled
```

That being said, we do have bunch of work to do to make tests more stable and align PR and Master to run the same set of tests.

/to @erwinmombay

**Comment by piotrwojtkowiakmrf** [comment]
@aghassemi unfortunately it doesn't work, [here is the output](http://pastebin.com/RFYWbUq9).

These tests are passing if I run them in stand-alone mode, with one exception: *test/integration/test-amp-ad-3p*. This one is failing always.

From my point of view it looks like something is not isolated and because of that, it's causing an error in other places. Can You confirm if it works in your environment?

Thanks,
Piotr

**Comment by aghassemi** [comment]
@piotrwojtkowiakmrf  Some of those test are flaky in our environment as well, but not always failing. 
@erwinmombay Getting tests to be stable might be a good starter project for Raghu.

**Comment by choumx** [comment]
I can't repro this locally at HEAD anymore with either min or max build.
