### ISSUE TITLE
Move documentation about how owners works out of GOVERNANCE

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#8183]
Followup from github-owners-bot issue (https://github.com/google/github-owners-bot/issues/26), we should move the owners portion out of GOVERNANCE into its own doc in contributing/

cc @erwinmombay @cramforce

**Comment by cramforce** [comment]
Yes, maybe we can also have a succinct version in GOVERNANCE and a doc focused on how to use it in the contributing docs.
