### ISSUE TITLE
Create a presubmit to catch experiment cleanup mishaps

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#8188]
When cleaning up an experiment, the flag removals from the config files should happen up to 2 weeks after  the code clean up (the code needs to be in production before flags are removed).

One simple presubmit could ensure any PR with changes `*-config.json` ONLY includes changes to `*-config.json` and no other code file changes, with a warning explaining that code needs to make it to prod before the config is changed.

**Comment by aghassemi** [comment]
@erwinmombay @cramforce @dvoytenko An alternative approach is removing `--reread` and treating every flag change as a patch on prod (generating a completely new version number like other code patches). If the argument is this will make us slower in responding to P0 issues that can be fixed by flipping a flag, although true, the difference is really the time it takes to do a recompile vs copy/replace, the rest of the process is the same anyway. So 5-10 mins difference in response time?

**Comment by cramforce** [comment]
Flag change should not require a recompile. We want to be both fast and absolutely, positively guaranteed to change nothing but the flags.

I think this check is a good first step:

- list files in top commit if on master or files in diff from master
- see that they either only change these JSON files or change none of them.

**Comment by dvoytenko** [comment]
I agree with flag-only PRs. The only thing - we need to absolutely guarantee the JSON correctness. I.e. as a test, we need to run `JSON.parse()` on contents.

**Comment by erwinmombay** [comment]
### steps to fix

build-system/pr-check.js - this file executes commands depending on the file types contained in the Pull Request. 

- [ ] Add new target type in the `determineBuildTargets` function. Let's call it `FLAG_CONFIG`.
- [ ] Add a new predicate function called `isFlagConfig` in `pr-check.js` where it checks if the basename (you can use the `basename` method on the nodejs `path` module) of the path is one of `prod-config.json` or `canary-config.json`.
- [ ] Add a new `else if` block on the `determineBuildTargets` function checking whether if file path is `isFlagConfig` and adding the `FLAG_CONFIG` string to the `targetSet`.
- [ ] In the `main` function right after `determineBuildTargets(files)` is invoked we need to add a check where if `buildTargets` has `FLAG_CONFIG` then only `prod-config.json` or `canary-config.json` are in `files` and nothing else, print out an error to the console and exit out of the process.

**Comment by erwinmombay** [comment]
@rsimha-amp let me know if anything is unclear in the instructions I provided above.

**Comment by lannka** [comment]
@rsimha @aghassemi @erwinmombay can we remove this presubmit check as we've already removed the support of `--reread` ?

**Comment by aghassemi** [comment]
LGTM from me.

**Comment by rsimha** [comment]
> @rsimha @aghassemi @erwinmombay can we remove this presubmit check as we've already removed the support of `--reread` ?

@lannka Was there a recent PR that removed `--reread` and eliminated the need for the check? I was under the impression we still needed to separate code and config.  See https://github.com/ampproject/amphtml/pull/18608#issue-221232447 for example.

Trivia: #8448, which added the check, was my first PR on AMP 😃

**Comment by erwinmombay** [comment]
`--reread` was internal so there was no PR.

i do believe we still need this check

**Comment by lannka** [comment]
@erwinmombay what do you mean by "internal"? Are we still using it in anyway?

**Comment by lannka** [comment]
Erwin, could you elaborate why this check is still necessary?
The case we were to avoid is:

A feature 'abc' is 100% launched with `abc: 1` in our prod-config.json.
To clean up the feature flags:
Monday: a PR that removes isExperimentOn('abc') from code and removed `abc: 1` from prod|canary.config 
Tuesday: canary cut, both config change and isExperimentOn('abc')  is compiled into new binary. Which is expected.
Thursday: prod cut with `--reread` flag that picks up the config change. This is unexpected, because it unlaunched the feature!! as we still have the `isExperimentOn('abc')` check in prod binary.

That's why we introduced this check to make sure people are aware of the issue.
Given --reread is not a thing anymore, I think the check is not needed?

**Comment by erwinmombay** [comment]
good points @lannka, the only other real concern is actual configuration cherry picks. although its unlikely for a mismatch between code and configuration in that scenario, this check doesn't really help for that scenario.
