### ISSUE TITLE
Be able to compare ios minor version

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#8206]
Brought up in https://github.com/ampproject/amphtml/pull/7966#discussion_r106556099

Some bug fixes are only needed for ios version after a minor version or before a minor version, so there's a need to be able to compare ios minor version strings.

**Comment by aghassemi** [comment]
I am moving thing back to `New FR`. @muxin Is anything high-priority waiting for this?

**Comment by muxin** [comment]
If ios has new version 10.4 then I need to disable native snap point in slidescroll for versions later than 10.3 instead of just 10.3.

**Comment by aghassemi** [comment]
moving out of sprint

**Comment by muxin** [comment]
This is not needed now so closing it.
