### ISSUE TITLE
Getting preloaded Warning in amp

### ISSUE THREAD

**Issue by ColombiaOnline** [ampproject/amphtml#8213]
Hi ,
We are facing below warning when files are loaded.
"The resource https://static.clmbtech.com/ad/commons/js/colombia-amp.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing."

![amp_warning](https://cloud.githubusercontent.com/assets/18116684/24031787/8712b17a-0b0a-11e7-9c03-05433026cead.jpg)

**Comment by cramforce** [comment]
Yes, this is working as intended. We preload eagerly, but lazy loading of resources might be much later.
