### ISSUE TITLE
amp-list: amp-mustache removes svg

### ISSUE THREAD

**Issue by rowangray** [ampproject/amphtml#8214]
SVG inserted in the template markup are removed on amp-list output.

see: [https://jsbin.com/qucolisaja/1/edit?html,output]( https://jsbin.com/qucolisaja/1/edit?html,output)

**Comment by choumx** [comment]
SVG is temporarily blacklisted from `amp-mustache` which will be resolved with #1156. Marking as "blocked". Sorry about that!

/cc @dvoytenko

**Comment by dvoytenko** [comment]
Yeah, hard to imagine we can pick up all rules for validation of SVG w/o the actual validator.

**Comment by travishoki** [comment]
`amp-img`'s do not seam to be supported either. I tried both an `svg` and an `amp-img` and neither are rendering.

**Comment by dvoytenko** [comment]
`amp-img` are used a lot and should work just fine. Do you have an example where `amp-img` doesn't work?

**Comment by travishoki** [comment]
I tried using an `amp-img` in `amp-mustache` and couldn't get it to work. Not sure what the problem is, perhaps an error on my part. Our company decided to just remove the images all together opposed to letting me dedicate time to figuring it out.

**Comment by dvoytenko** [comment]
@travishoki If you have an example - please send it to us, now or later.

**Comment by javiergarzac** [comment]
Had the same issue. A work around I used was converting the `svg` to `base64` and assign it as background to my icon class using the good old `background: url('data: ...')`. Not ideal as I need to keep the css below 50kb, but its a workaround for now.

**Comment by command3r** [comment]
Had the same issue. This was confusing and time consuming, can a validation warning be thrown in the meantime? Ideally, anything that gets removed from the template should generate some feedback to the developer.

**Comment by sanjsanj** [comment]
Same for me and my team, luckily we stumbled upon this issue or we would've carried on debugging for even longer.

**Comment by choumx** [comment]
@command3r @sanjsanj Sorry about that! We just added an error for attribute sanitization in #13176 so it should be easy to add another for elements.

**Comment by jfallis** [comment]
@travishoki @dvoytenko - Was unable to pass AMP-IMG or SVG tags through amp-list/amp-mustache, however, you can render AMP-IMG using the standard HTML IMG tag.

**Comment by aghassemi** [comment]
Closing as dup of https://github.com/ampproject/amphtml/issues/15123 for SVG and dup of https://github.com/ampproject/amphtml/issues/15343 for `amp-img`

**Comment by tiagorangel2011** [comment]
Template is always hidded
