### ISSUE TITLE
Remove viewer dependency for storage API

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#8215]
The primary reason to have the viewer involved in the Storage API is this webkit bug https://bugs.webkit.org/show_bug.cgi?id=168631 that makes localStorage transient in partitioned 3p context.

As that bug revealed there is no such bug for IndexedDB, so we could switch storage to that (when available) and stop involving the viewer.

**Comment by dvoytenko** [comment]
We need to see if IndexDB available in private mode. A similar issue (https://bugs.webkit.org/show_bug.cgi?id=157010) has been fixed for LocalStorage in iOS10.

**Comment by cramforce** [comment]
Why is private mode relevant? I think being transient is fine in private mode.

**Comment by dvoytenko** [comment]
The concern if it completely fails in the iframe, which was the case with localStorage until very recently.

**Comment by cramforce** [comment]
@dvoytenko See comment on the bug:

- Safari has the notion of partitioned storage where the storage origin essentially becomes the concatenation of the origin plus all parent origins.
- `localStorage` has a bug where it uses transient storage instead of persistent storage on top of the above.
- They say that IndexedDB does not have this bug.

**Comment by lannka** [comment]
I got an IndexedDB error on latest desktop Safari (10.1) inside a xorigin iframe.
> SecurityError (DOM Exception 18): IDBFactory.open() called in an invalid security context

See [jsbin example](http://jsbin.com/lijagic/edit?html).

**Comment by cramforce** [comment]
:(

I updated https://bugs.webkit.org/show_bug.cgi?id=168631
Lets see what their feedback is.

**Comment by cramforce** [comment]
Maybe try WebSQL :)

**Comment by dvoytenko** [comment]
To @choumx to reprioritize.

**Comment by choumx** [comment]
Per the WebKit thread, looks like they've marked this behavior as WAI. Closing since postMessage remains necessary.
