### ISSUE TITLE
Short term improvements for performance measurements

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#8216]
- [x] Our current `pc` tick is broken for the prerender case, due to breakage with delta ticking. Need to fix.
- [x] Consider separating prerender/non-prerender into 2 actions. Due to chunking pre-render sometimes goes slow on purpose. I'm undecided on this one. Main benefit due to the above, would be that we could have continuity in the existing metric.
- [x] Remove any priority 2 and 3 items from `pc` metric. This is not what we are optimizing for and it skews the metric away from our action goals. #7789 covers the wider goal of optimizing all priority items.

**Comment by lannka** [comment]
the 2nd item is already done and in production.

**Comment by lannka** [comment]
Given we had (2), `pc` (prerenderComplete) is not a good name anymore. Since it's broken anyway, I suggest we deprecate it and introduce a new metric `fvr` (first viewport ready), which ticks when all P0 elements in first viewport are laid out.

**Comment by cramforce** [comment]
First item still needs an actual corresponding change on the viewer side, but code here is merged.
