### ISSUE TITLE
AMP cache modifications best practices and image URL rewrites

### ISSUE THREAD

**Issue by ericdreeves** [ampproject/amphtml#8223]
Hello,

I'd like to clarify the URL rewrite behavior for images as described in the [AMP cache modifications best practices](https://github.com/ampproject/amphtml/blob/master/spec/amp-cache-modifications.md#all-image-urls-are-rewritten-as-amp-cache-urls-except-those-in-amp-mustache-template) document.

In each of the four examples, none of the rewritten URLs contain the origin domain. Regardless of whether the rewritten AMP cache URL is absolute or relative, I'd expect the URI of the content to be fetched to contain the origin domain.

For example,

	<amp-img src=https://example.com/foo.png></amp-img>

would be rewritten per the document as:

	<amp-img src=/i/s/foo.png></amp-img>

My expectation is that the URL would actually be rewritten as:

	<amp-img src=/i/s/example.com/foo.png></amp-img>

Alternatively, it might also be rewritten according to the AMP Cache URL format descrbed
[here](https://developers.google.com/amp/cache/overview#amp-cache-url-format):

	<amp-img src="https://example-com.cdn.ampproject.org/i/s/example.com/foo.png"></amp-img>

Is this a typo in the the best practices document?

Thanks!

**Comment by dknecht** [comment]
@ericdreeves  This is typo.

**Comment by honeybadgerdontcare** [comment]
@ericdreeves yes, this is a typo as @dknecht pointed out. Fixing this in PR #8283.

Note that while your alternative is in effect true, that would only be true for the Google AMP Cache. We want these best practices to be for all AMP caches, not just a specific one.

**Comment by ericdreeves** [comment]
> Note that while your alternative is in effect true, that would only be true for the Google AMP Cache. We want these best practices to be for all AMP caches, not just a specific one.

Indeed. Thank you for making that clarification, as well as the quick response.

**Comment by honeybadgerdontcare** [comment]
This is now addressed in the document.
