### ISSUE TITLE
Layout not supported: fixed. (Adsense link unit issue)

### ISSUE THREAD

**Issue by MsXLabs** [ampproject/amphtml#8225]
Hello,

Today I noticed some error messages regarding my Adsense Link Units and Matched Content unit.

These are my ad unit codes:

Link units:
```
<div>
<amp-ad width="200" height="90" type="adsense" data-ad-client="ca-pub-xxx" data-ad-slot="xxx"></amp-ad>
</div>
```

Matched Content unit:
```
<div>
<amp-ad width="320" height="520"
 type="adsense"
 data-ad-client="ca-pub-xxx"
 data-ad-slot="xxx">
</amp-ad>
</div>
```

Screenshot: ![snap1](https://cloud.githubusercontent.com/assets/22967013/24060689/0c1b9c18-0b5d-11e7-8550-fe43a62d8524.png)

Test URL: https://www.msxlabs.org/forum/amp/199381.html#development=1

Other Adsense ad units (300x250) don't have this problem.

Did you update/change anything recently that may cause this issue?

Regards

**Comment by choumx** [comment]
@MsXLabs I can't repro on the test URL you gave above.

/to @lannka /cc @jasti

**Comment by MsXLabs** [comment]
The error messages dissapared a few hours later.

**Comment by jasti** [comment]
Please reopen if this is still an issue.
