### ISSUE TITLE
Implement gulp test for binary sizes control

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#823]
A new gulp test will check if any binary has a big change in size. It will work as following:

First: add `sizes.json` file which will list minified (not gzipped) binary sizes. E.g.:

``` javascript
{
  'amp.js': 123456,
  'amp-anim-0.1.js': 9456
}
```

Second: add `gulp check-sizes` task that will
1. Build all binaries
2. Calculate their minified sizes similar to how `gulp size` does it now - these are new sizes
3. Read `sizes.json` - these are old sizes
4. Compare the new size to the old size. If the `abs(%change)` is greater than 5%, report binary, old size, new size and %change to console.
5. If there were any binaries reported, fail the test

The %change is calculated as following:
1. If the old size is undefined (new binary), the `%change = 1000%`
2. Otherwise, `%change = (newSize - oldSize) / oldSize`

Third: the pull request author who gets the test failure will have to do the following:
1. If the size change is not expected, find a problem and fix.
2. If the size change is expected, update `sizes.json` with the new sizes reported in the console and include `sizes.json` in the same pull request.

Fourth: the reviewer will have to either agree or challenge the size change. E.g. the reviewer can ask to change the author to switch to lazy loading, different component composition, or use of different 3rd party libraries.

That's all.

Notice that in this system the 5% threshold could be exceeded via a simple incremental change. This is ok since the main goal is to catch big diffs. We can also, later, implement a periodic automatic size recalc/merge to reduce the probability of this happening.

**Comment by rahmanmustafa** [comment]
363636

**Comment by rahmanmustafa** [comment]
363636

**Comment by erwinmombay** [comment]
:+1:

**Comment by erwinmombay** [comment]
tasks:

- [x] output json instead of txt file. (#825)
- [ ] refactor `build` task to be fully async and have correct task completion
- [ ] refactor `dist` task to be fully async and have correct task completion
- [ ] add gulp `check-size` that applies the applies the recommendation from @dvoytenko above

**Comment by adelinamart** [comment]
What's the status of this one?

**Comment by dvoytenko** [comment]
Done
