### ISSUE TITLE
A4A autoplay

### ISSUE THREAD

**Issue by JamesIves** [ampproject/amphtml#8235]
The AMP4ADS spec draft mentions that `autoplay` is not allowed on amp-carousel but it doesn't cause an issue with the validator. It seems that this information is out of date.  (Article 5 on the linked document under the format rules) 

https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/amp-a4a-format.md#a4a-format-rules

**Comment by jasti** [comment]
@tdrl, could you confirm if we should fix the documentation or the validator? :) My preference would be to allow autoplay for carousels.

**Comment by jasti** [comment]
ping @tdrl

**Comment by tdrl** [comment]
We could do it either way, but I don't think I'm the authority on whether `autoplay` should be allowed in this case.  It feels like a user satisfaction/useability issue.  @jasti what would be the consequences if we disallow in validation?  Alternately, @cramforce are there performance/useability impacts to allowing it to be enabled by default for `amp-carousel` in ads?

**Comment by cramforce** [comment]
Fine with me on the carousel.

**Comment by jasti** [comment]
@tdrl Not a big consequence - just restricts creative expression for no reason.

**Comment by jasti** [comment]
@Gregable Can you please confirm if the validator disallows other forms of auto play as listed in the documentation?

**Comment by jasti** [comment]
Still had an open question for @Gregable.

**Comment by jasti** [comment]
Ping @Gregable
