### ISSUE TITLE
Experiment with alternate versions of the default ad placeholders

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#8238]
It's possible the current one sticks out way too much on a white background.

**Comment by ericlindley-g** [comment]
@jasti @spacedino Should we move this earlier, to the coming fixit week?

**Comment by jasti** [comment]
Sounds good! Moved.

**Comment by jasti** [comment]
@spacedino, could you upload the new designs here please?

**Comment by spacedino** [comment]
![19_ad_loader_new copy](https://cloud.githubusercontent.com/assets/7339798/24571847/e61d05ca-1628-11e7-80d2-61accac67acf.png)

![18_ad_loader_new](https://cloud.githubusercontent.com/assets/7339798/24571850/e876e548-1628-11e7-9ecc-224eae17ce23.png)

notes from email: we just want to double check it on a few devices to make sure its not over saturated. also not sure if the #000000, 1% will work on black but @lannka we figured it out last time so im assuming we can again :)

**Comment by lannka** [comment]
@spacedino could you actually apply the design on more background colors and paste them here?

**Comment by spacedino** [comment]
![image](https://cloud.githubusercontent.com/assets/7339798/24624386/930a282e-1860-11e7-94dc-b01dd62c425d.png)

![image](https://cloud.githubusercontent.com/assets/7339798/24624410/a33672ac-1860-11e7-9c96-645a28afee56.png)
 @lannka we might need to tweak this live
