### ISSUE TITLE
create module dependency graph with sizes

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#824]

**Comment by erwinmombay** [comment]
can help us make a decision if wether importing a module is not worth it. if it increases an extensions file size significantly for 1 helper function for example.

**Comment by erwinmombay** [comment]
@adelinamart related to internal cleanup/tooling

**Comment by adelinamart** [comment]
Do you still want to work on this, because is very old. Thanks.

**Comment by erwinmombay** [comment]
no. lets close.
