### ISSUE TITLE
Banner layout = fixed doesn't stick with the top of the window

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#8241]
Reproducible in iOS Chrome on Google Search canvas.

There is also considerable amount of 'bounce' in the fixed banner on page scroll - either up or down. 
https://www.google.com/amp/www.stevehuffphoto.com/2016/08/04/experiences-with-the-new-laowa-12mm-f2-8-zero-d-by-dierk-topp/amp/

![image](https://cloud.githubusercontent.com/assets/2366341/24082972/b3d116e8-0c8b-11e7-9f67-2e394bac031c.png)

**Comment by ericlindley-g** [comment]
@dvoytenko  — do you have an idea of why this is? I've notice issues with fixed elements (both at top and bottom of screen) not precisely lining up with the viewport. This leads to leaks behind the elements (the screenshot above is a particularly bad case, but there are subtler ones)

**Comment by dvoytenko** [comment]
@jasti @ericlindley-g This is because the page does not specify `top: 0;` for the header which is required for us to keep it anchored to the top. Auto-top fixed elements are not anchored. Please follow up with the page authors.

**Comment by dvoytenko** [comment]
Actually, I have an idea how we can address this particular special case. I see if I can do it automatically.

**Comment by jasti** [comment]
Thanks @dvoytenko!
