### ISSUE TITLE
Intent to implement: Instagram captions and styling.

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#8242]
I'd like to add caption support to the `amp-instagram` component.  This will involve adding an optional `data-captioned` attribute.  If the attribute is present the instagram `iframe` url will change from and the embed will include the caption.
`https://www.instagram.com/p/<shortcode>/embed/?v=4` to 
`https://www.instagram.com/p/<shortcode>/embed/captioned?v=4`.

At the same time I'd also like to add support for the instagram style messages.  When the instagram iframe loads it sends several messages to it's parent.  The `MEASURE` message is already handled by `amp-instagram`.  I'd like to add support for `MOUNTED` message.  This message contains styles to be applied to the iframe. 

Questions: 

1. Should this be gated by a `data-framestyle` attribute or should it default on? (my gut says gated to avoid a breaking  change)
2. Including the border attribute will require the iframe box-sizeing to be set to border-box to avoid a re-layout, does that makes sense?

Example `MOUNTED` message 
```
{
	"type": "MOUNTED",
	"details": {
		"styles": [
			["boxShadow", "none"],
			["border", "1px solid #dbdbdb"],
			["margin", "1px 1px 12px 1px"]
		]
	}
}
```

Doing this would make amp-instagram match the standard instagram styling and features.

cc @cramforce @dvoytenko  and @jridgewell as owners of amp-instagram.

**Comment by jpettitt** [comment]
On second thoughts the styling stuff is going to cause a re-layout due to the margin style so I'm going to skip that unless somebody has a good idea for how to handle it. (ignore the margin and only do the boxShadow and border?)

**Comment by cramforce** [comment]
@jpettitt Do you have a before-after screenshot of what those styles actually do? But yeah, I agree that applying styles on "mount" doesn't fit well into AMP.

**Comment by jpettitt** [comment]
Without styles 
![image](https://cloud.githubusercontent.com/assets/524856/24106310/b6c0f670-0d44-11e7-8f80-9bc74e084d56.png)

with styles

![image](https://cloud.githubusercontent.com/assets/524856/24106330/c69913f2-0d44-11e7-9274-38cf64b67750.png)

**Comment by aghassemi** [comment]
@jpettitt :+1: for `data-captioned` 

For the styling, as you mentioned, it should be guarded by an opt-in attribute since authors may have already styled the parent container with borders and shadow-box to mimic the native styling. 
As for re-layout, two options available:
1. Delay declaring layout finished until `MOUNTED` message is received. If Instagram sends the `MOUNTED` message reliably and relatively early on (i.e. within _nn_ ms of iframe load event firing), then we can change the `layoutCallback` to return a promise that won't resolve until styling is applied, delaying layout until then. Waiting for a post message before finishing layout is not unheard of (`amp-youtube` does it). 
2. Since we already listen for `MEASURE` and call `attemptChangeHeight`, we can piggy-back on the success of  `attemptChangeHeight` (e.g. if it succeeds, it means it is okay to relayout) to also apply the style. This unfortunately means style may not be applied sometimes which is not great, so I am leaning toward option 1, hoping Instagram sends that message early enough to make the delay hit acceptable.

**Comment by jpettitt** [comment]
@aghassemi Having look at the messaging it seems very consistent in what it requests.  I'm wondering if a better strategy might be to just set a default style that matches the one instagram uses and be done with it.

**Comment by aghassemi** [comment]
@jpettitt I will be fine with that. I can't find any information on whether an Instagram item owner can customize the style of their item for embedding.

**Comment by jpettitt** [comment]
@aghassemi I don't think they can customize it. The only config option I see is to enable/disable captions.  The default IG embed taks a blockquote with a placeholder loading image and replaces it with the iframe.  Obviously they could override in their CSS but there is no option on the IG end of things.

**Comment by cramforce** [comment]
Adding those styles would need to be opt-in, but I agree that this should
just be hardcoded in the extension.

**Comment by jpettitt** [comment]
Add the styles to the iframe?  the amp-instagram?  Create a CSS file and add a class to control it?  What is the preferred route here?

**Comment by cramforce** [comment]
I think yes, yes, yes. See amp-accordion for an extension with CSS.

amp-instagram has some styles in the base CSS (to avoid jumping). ideally
this would work together with that CSS.

**Comment by jpettitt** [comment]
OK I think I'll create a CSS file with a new class that add the margin and frame to the iframe and reduces the padding on `amp-instagram` from the default CSS by the same amount so nothing jumps.  Does `i-amp-instagram-framing` sound like a good class name?

**Comment by cramforce** [comment]
We want to make this something that users add as an opt-in, right? In that
case maybe amp-instagram-default-framing (Totally aware that this is an
opt-in to a default :)

**Comment by jpettitt** [comment]
This is turning out to be less simple than I thought :-)

Digging into this further the sizing is wrong and instagram embeds are now on v7 with a different layout.  The new ones look like this.  Unless I hear objections I'll update amp-instagram accordingly to use the new style (changing the query string on the embed and adjusting the CSS spacing to make the placeholder still work).  Doing this will also enable instagram slideshows.

![image](https://cloud.githubusercontent.com/assets/524856/24125139/48337576-0d84-11e7-82c5-07cc021eb54e.png)

**Comment by cramforce** [comment]
@jpettitt Yes, please.

CC @adewale regarding maybe nudging instagram of maintaining this themselves.

**Comment by jpettitt** [comment]
Since #8243 has been merged I'm closing this as complete.
