### ISSUE TITLE
amp-form: Support `pattern` on `<textarea>` for validation

### ISSUE THREAD

**Issue by jalajc** [ampproject/amphtml#8247]
## Validation pattern for custom validation in <textarea> is not working
To reduce meaningless submissions in textarea, I want to use custom validation patterns. Apparently, patterns are not working in <textarea>.

## How to reproduce?

1. add required amp-components for amp-form to work
2. Use the following sample snippet (modified form example [here](https://github.com/ampproject/amphtml/blob/1481752933947/examples/forms.amp.html) )

```
<h1>Custom Validations</h1>
<h4>Submit Feedback</h4>

<form id="textarea1" method="post"
      action-xhr="/form/echo-json/post"
      target="_blank"
      custom-validation-reporting="show-first-on-submit">
    <fieldset>
        <label>
            <span>Your name</span>
            <input type="text" name="name" id="name4" required pattern="\w+\s\w+">
            <span visible-when-invalid="valueMissing" validation-for="name4"></span>
            <span visible-when-invalid="patternMismatch" validation-for="name4">
                Please enter your first and last name separated by a space (e.g. Jane Miller)
            </span>
        </label>
        <label>
            <span>Your email</span>
            <input type="email" name="email" id="email4" required>
            <span visible-when-invalid="valueMissing" validation-for="email4"></span>
            <span visible-when-invalid="typeMismatch" validation-for="email4"></span>
        </label>
		<label>
		<span>Your Feedback</span>
		<textarea id="Q6" name="Q" value="" rows="5" cols="50" form="textarea1" required pattern="[\w\s\u0900-ॾ\ua8e0-\ua8fe]{10,50}"></textarea>
            <span visible-when-invalid="valueMissing" validation-for="Q6"></span>
            <span visible-when-invalid="patternMismatch" validation-for="Q6">
                Please enter minimum 10 characters and maximum 50 characters
            </span>
		</label>
        
		<input type="submit" value="Submit Feedback">
    </fieldset>
</form>
```
PS: regex pattern in JavaScript is working fine ( [see](https://regex101.com/r/ZLRH8w/6) ). Tried with other basic patterns too.

## What browsers are affected?
Chrome (Mobile), Chrome(desktop). Not tested on other browsers

## Which AMP version is affected?
Version: 1489777197505.

**Comment by aghassemi** [comment]
@jalajc `pattarn` on `textarea` is not supported by HTML standard (we piggy-back on browsers for validation).

AMP could start extending the HTML validation to allow for more use-cases however, so I will keep this open as a feature request.

**Comment by CemDemirkartal** [comment]
@aghassemi Do you believe amp`s structure is valid in HTML standarts?

By the way, it`s not Pattarn , it`s Pattern.

**Comment by aghassemi** [comment]
@CemDemirkartal Do you mean if AMP decides to support `pattern` on `textarea` while HTML standard doesn't, is that still valid? The answer is I don't know and it barely matters (technically all AngularJS apps would be invalid in that case since they all have attributes that are not part of HTML standard). If we want to be strict about validity, worse-case we would name it `data-pattern` instead of `pattern`

**Comment by CemDemirkartal** [comment]
I mean you can't decide while AMP is on invalid case by HTML standarts. Nobody can claim something is valid or not valid in HTML standarts while AMP is not. All simple and all connected to each other.

**Comment by aghassemi** [comment]
@CemDemirkartal Agreed. The `P3 - When Possible` label simply refers to our prioritization ranking and is not about "when possible in HTML".

**Comment by choumx** [comment]
FYI an internal FR for this: `b/113262842`. I think this might be an easy extension of the logic in `form-validators.js`. /cc @cvializ
