### ISSUE TITLE
includes is not available for amp-bind

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#8251]
amp-bind should support `includes` as part  of [7401](https://github.com/ampproject/amphtml/pull/7401), but I get:

> error.js:135 AMP.setState() failed with error: : includes is not a supported function.​​​
Dd @ error.js:135
f.error @ log.js:214
(anonymous) @ bind-impl.js:183

You can reproduce the issue by visiting:
[product sample](https://amp-by-example-staging.appspot.com/samples_templates/product/preview/)

@kmh287

**Comment by kul3r4** [comment]
As @kmh287 pointed, I didn't have a json array in the `amp-state` but an object and I was trying to use `includes` method. We could improve the error message to not get confused.

**Comment by choumx** [comment]
Thanks for the bug report!
