### ISSUE TITLE
amp-bind: Sanitizer issue

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#8252]
Internally tracked: `b/34499443#comment26`

- Make sure that `sanitizer.js` won't recognize elements like `<a data-&[xyz]="1+2">` as containing a bindable attribute `xyz`.

**Comment by dknecht** [comment]
What is issue here?  Can you add description?

**Comment by choumx** [comment]
@dknecht Edited the issue with a description.

**Comment by kmh287** [comment]
Just tested this:

`<a data-&[target]="_blank" data-&[href]="javascript:alert(0)"></a>`

is sanitized to

`<a data-="" target="_top" blank="" href="" javascript:alert=""></a>`

and

`<a data-[target]="_blank" data-[href]="javascript:alert(0)"></a>`

is sanitized to

`<a data-="" target="_top" blank="" href="" javascript:alert=""></a>`

neither of which contains a bind attribute for `target` nor for `href`.

**Comment by choumx** [comment]
Thanks for investigating. Fix is tracked in #8271.
