### ISSUE TITLE
Implement new version of ads placeholder

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#8261]
Once @spacedino's done with #8238 in the next sprint - implement the changes.

**Comment by zhouyx** [comment]
The new placeholder is alive in canary. Please goto [https://cdn.ampproject.org/experiments.html](url) opt into AMP dev channel, and opt into **either** 'ad-loader-v1' or 'ad-loader-v2' to see the new design.

**Comment by zhouyx** [comment]
The text "advertiser" is implemented by publisher

**Comment by jasti** [comment]
@zhouyx The implementation doesn't match the mocks. Specifically, the corner angles on the ad logo are more acute than in the mocks. 
See original
![original](https://cloud.githubusercontent.com/assets/2366341/25203437/216eb882-250e-11e7-8ce2-af78df87139f.png)

See Implementation
<img width="415" alt="screen shot 2017-04-19 at 2 37 17 pm" src="https://cloud.githubusercontent.com/assets/2366341/25203443/27d5efd8-250e-11e7-8479-8b658067754c.png">

CC @spacedino

**Comment by zhouyx** [comment]
I think @spacedino and I adjust the border-radius a little bit. I am very happy to adjust it.

**Comment by jasti** [comment]
@spacedino reasoning behind the change?

**Comment by zhouyx** [comment]
New design (Note: size may appear different due to different resolution):
![image](https://cloud.githubusercontent.com/assets/5419904/25410465/cbd60b74-29cb-11e7-8a5e-44cf0ee9a241.png)
The text is closer to top in Nexus 6p.  Can't center the text perfectly unless using svg : (
Or please go to [link](https://zhouyx.herokuapp.com/test/manual/fakead3p.amp.html) to see placeholder in real device.

**Comment by spacedino** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/7339798/25411001/f3333ac2-29ce-11e7-9dfc-484ca79812d0.png)
am i crazy? it looks like the word "Ad" is too light....

**Comment by zhouyx** [comment]
#9037

**Comment by zhouyx** [comment]
Close this issue for now. Will wait until the change hit canary and we choose which design to go with later.
