### ISSUE TITLE
Scroll-dependent header hiding/showing/docking

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#8268]
Tracking issue for general scroll-dependent header behaviors as a scoped version of the general scroll-bound CSS feature.

Feature 1: Header hides/shows as user scrolls down/up

Feature 2: Inline sub-heading for page section docks to header when it is scrolled to the top of the viewport, and sticks there until user scrolls back up, or is replaced by another docking/sticky header, or is removed (user scrolls below relevant section)

/cc @aghassemi @cvializ

**Comment by jpettitt** [comment]
Will this include unidirectional triggers?  IE when you scroll down the page no header but if you start to scroll back up the header appears? (the theory being that if you're going back up there is a higher probability you want the nav)

**Comment by ericlindley-g** [comment]
@jpettitt — Yep! The plan right now for feature 1 above is to support a behavior where the header gets out of the way when the user wants to consume the primary page content (when the user scrolls down), and comes back when the user's intent is more ambiguous, and may want navigation affordances (when the user scrolls back up)

**Comment by aghassemi** [comment]
@jpettitt I am imagining "feature 1" to pretty much mimic current AMP viewer header behavior (with a default animation curve that matches AMP viewer as well)

**Comment by asadkn** [comment]
It would be great if this was more generic and could be applied to other elements like a fixed "back to top" that becomes visible only at certain top / bottom position. 

Google itself had a back to top button recently: http://www.thesempost.com/google-testing-back-to-top-mobile-search-results/

**Comment by ericlindley-g** [comment]
Thanks for the feedback, @asadkn — I think the more general scrollbound amp-animation feature could be used to support this. @aghassemi , is that right?

**Comment by aghassemi** [comment]
#8411 should cover "back to top" (using a marker somewhere in the page to act as the trigger upon visibility). I will add it to the list of use-case to verify.

**Comment by SchnWalter** [comment]
I agree with @asadkn, a generic version of *Feature 2* would be great. And it would also be useful for a "docking" desktop sidebar ad, and people would like to pair this with AMP Ad refresh (#9535).

**Comment by RS-David** [comment]
Is the "Feature 1" version of this still planned, or did it get rolled into "scroll-bound amp-animation" (or some other shelved outcome)?

I think I might be able to replicate something of a basic scroll/hide fixed header, but given how common it seems to be as a design pattern I'd love to be able to use something relatively standardized.

**Comment by cvializ** [comment]
This feature is implemented, but we haven't made a simple demo example for it yet. An example site using it is [AliExpress on their mobile product page](https://m.aliexpress.com/item/32839936868.html?trace=wwwdetail2mobilesitedetail&productId=32839936868&productSubject=Home-Barbershop-Hair-Dryer-Bonnet-Caps-Soft-Hood-Attachment-Haircare-Women-Salon-Hairdressing-Hat-Perm-Helmet&spm=a2g01.11127473.layer-cwh3lk.2.243ec9c4iQ9yCI&scm=1007.13761.63301.0&scm_id=1007.13761.63301.0&scm-url=1007.13761.63301.0&pvid=0ac8a6ee-340b-4978-8af0-76a9b10ba8c1&_t=pvid:0ac8a6ee-340b-4978-8af0-76a9b10ba8c1,scm-url:1007.13761.63301.0) Make sure you view it in the DevTools mobile view.

**Comment by aghassemi** [comment]
@RS-David Another similar sample here: https://codepen.io/aghassemi/pen/GOEWEz (it does shrink/expand instead of hide/show but the fundamentals are the same)

**Comment by aghassemi** [comment]
The new `amp-fx-float-in-*` handles the reset of this FR. https://github.com/ampproject/amphtml/issues/20881
