### ISSUE TITLE
Error on "Beautiful, interactive, canonical AMP pages" code lab

### ISSUE THREAD

**Issue by alfredmyers** [ampproject/amphtml#8269]
On [step 8](https://codelabs.developers.google.com/codelabs/amp-beautiful-interactive-canonical/#7) of "Beautiful, interactive, canonical AMP pages" code lab

where read:

> 2) Turn on `amp-bind` experiment in your development setup.

should read:

>2) Turn on `amp-fx-parallax` and `amp-animation` experiments in your development setup.

PS.: I did a little search around the different ampproject repos, but I wasn't able to find the one where this code lab is stored. If you guys point me to the correct place, I can contribute a fix to the page.

**Comment by aghassemi** [comment]
@alfredmyers Thanks for the report! Fixed. (Codelab code is outside of the open-source repo)
