### ISSUE TITLE
Create a GitHub gist extension

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#829]
### Background
The AMP HTML library includes many [extended components](https://www.ampproject.org/docs/reference/components) that bring third-party functionality as first-class components in AMP. 

### Motivation 
We like to introduce a new component to integrate [Github gist](https://help.github.com/articles/about-gists/) in AMP. This would allow developers to include their code from Github in their AMP pages.

### Implementation strategy
- create `<amp-gist data-src="https://gist.github.com/cramforce/c5d8ae62be229291e421.js"></amp-gist>`.
- It will be very similar to amp-twitter
- This creates a 3p frame
- Then creates `3p/github.js` also very similar to `3p/twitter.js`. The JS loading can be simpler in the initial version (Just insert the script tag)
- Try to figure out when the document has the final height
- Then call

``` js
context.updateDimensions(
        body./*OK*/offsetWidth,
        body./*OK*/offsetHeight + /* margins */ 20);
```

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] Read up on [How to build an AMP extension](https://docs.google.com/document/d/19o7eDta6oqPGF4RQ17LvZ9CHVQN53whN-mCIeIMM8Qk)
- [ ] Follow the **Implementation strategy** from above.
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review).  Mention `closes Issue #829` in the description.
- [ ] Assign @aghassemi as the reviewer
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

### Questions?

If you have questions ask in this issue or on your Pull Request (mentioning @aghassemi) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

**Comment by niutech** [comment]
From what I see, the work has started in https://github.com/jmadler/amphtml/tree/amp-github

**Comment by rudygalfi** [comment]
@jmadler Can you give an update on the status of this?

**Comment by mkhatib** [comment]
@jmadler have you managed to get this to work?

**Comment by pbakaus** [comment]
Quick update, I just learned that you can append ".pibb" to any Gist url, which will render the contents directly in HTML (interestingly, without head but who cares). This makes it viable to use amp-iframe to insert Gists into a page, but we still don't know the resulting height. Thoughts?

**Comment by levidurfee** [comment]
Hey guys, is this up for grabs? If so, I would like to give it a shot :)

**Comment by pbakaus** [comment]
Go for it!
