### ISSUE TITLE
Clean up amp-app-banner bug warning in readme

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#8290]
Ensure the note `####(Dec. 15, 2016) Note: We have discovered an issue` is removed from https://github.com/ampproject/amphtml/blob/master/extensions/amp-app-banner/amp-app-banner.md

**Comment by aghassemi** [comment]
@muxin Could you please verify that iOS fix is live for `amp-app-banner` and update the doc if so?

**Comment by jridgewell** [comment]
Ping. There's a message in Slack.

**Comment by muxin** [comment]
The bug for embedded ios is fixed. But I just found out that non-embed chrome ios is not working. https://github.com/ampproject/amphtml/issues/9077

**Comment by aghassemi** [comment]
@muxin ok since the common case (Safari Ios embed) is fixed, I merged #8579
