### ISSUE TITLE
Make runtime more robust against adblockers

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#8311]
[uBlock origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en) (and possibly other ad blockers) block requests to:

`https://cdn.ampproject.org/v0/amp-analytics-0.1.js `

(for more background see [question on SO](http://stackoverflow.com/questions/42907284/ublock-blocking-amp-experiment/42946088#42946088)). This has two consequences:

1. AMP only renders after 5s when amp-analytics component times out
2. amp-experiments won't work and will show all experiments

I'm currently talking to the maintainers of [EasyList](https://easylist.to/easylist/easyprivacy.txt) to get amp-analytics removed. However, it might make sense to make the AMP runtime more robust against this kind of blocking, e.g. by:

* shorter time out specifically for amp-analytics (and amp-pixel)
* provide a fallback for amp-experiment

//cc @cramforce @rudygalfi

**Comment by cramforce** [comment]
We've discussed before to move CID generation into its own extension, which should remove all these dependencies.

@erwinmombay filed a bug against ublock I think. Could you paste it here?

**Comment by cramforce** [comment]
@sebastianbenz AMP analytics was removed from easylist before https://github.com/easylist/easylist/commit/17e0447fb7c6df377a1081f730c5039c5396d0af so this seems to be a regression.

**Comment by lannka** [comment]
CID service moved to core. so we have less dependencies to amp-analytics.

**Comment by adargit** [comment]
Hi
Since yesterday, amp-analytics and maybe other AMP scripts are blocked in EasyList.
Our websites stopped working for users with ad blockers.
Can you please ask them to remove it from their list?

Thanks

**Comment by sebastianbenz** [comment]
I've done this already: https://forums.lanik.us/viewtopic.php?f=64&t=43484

Please chime in on the thread.

>

**Comment by adargit** [comment]
Thank you sebastianbenz

It improved but I'm still getting this error with uBlock Origin:

GET https://cdn.ampproject.org/v0/amp-analytics-0.1.js net::ERR_BLOCKED_BY_CLIENT

**Comment by sebastianbenz** [comment]
@adargit Easylist still blocks amp-ad and amp-analytics. That is working as intended from their perspective. However, this should not affect the basic functionality of the page. If you discover anything (besides ads and analytics) that's not working, please file a bug.

**Comment by adargit** [comment]
OK
Thank you very much @sebastianbenz
