### ISSUE TITLE
Install context APIs to delayed rendering iframes 

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#8313]
Just like all 3p iframes, A4A delayed rendering iframes also needs context API to be installed on host.
This is part of #6829. Separated out because it's a blocker for inabox to work on AMP page.

@bradfrizzell let me know if you are still on it.

**Comment by bradfrizzell** [comment]
Still on this, just got back from vacation so apologies for the very late response. 

Currently for the A4A flow, rendering via direct cache or nameframe supports the creative including the context API if they so choose. Safeframe is the only one that is not supported yet.

**Comment by lannka** [comment]
Since we have changed our direction to implement safeframe, closing this now.
