### ISSUE TITLE
Analytics: implement "hidden" visibility reporting for V3

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#8315]
Spun off from #7651.

The recommended new form is:

```
{
  "on": "visibile",
  "visibilitySpec": {
     ...
    "reportWhen": "hidden"
  },
}
```

/cc @lannka @jasti

**Comment by dvoytenko** [comment]
@zhouyx Is this done via #8805?

**Comment by zhouyx** [comment]
#8805 add support on existing `on: hidden` trigger and makes it possible to expand the visibilitySpec to support `reportWhen`(or whatever naming) keyword. 
But I haven't started on supporting the new format or new values.

**Comment by dvoytenko** [comment]
Let's close this issue and re-open "new format" issue and put it in backlog.

**Comment by zhouyx** [comment]
sounds good.
