### ISSUE TITLE
url substitutions for amp-pixel use $ which isn't allowed in urls

### ISSUE THREAD

**Issue by johnduffell** [ampproject/amphtml#832]
According to the amp-pixel spec we should use $DOCUMENT_REFERRER in the url to put in the actual referrer.  Unfortunately $ is a reserved character in URLs, so [play](https://www.playframework.com/) automatically escapes it as %24 when I put it in the href - this then means that the amp pixel code doesn't find it.

Since it's not technically a link until the substitution is done, is it right to require the $ sign?  If so, this stops us using html templating engines easily.

**Comment by dvoytenko** [comment]
Good point @johnduffell . The tools would be in their right to escape '$' in these URLs. Let me see what's up there with tests. But looks great. Thanks a lot!

**Comment by johnduffell** [comment]
Just for anyone who comes across this later - $ is indeed reserved in URLs but actually it wasn't play escaping it, our code was url encoding the parameters.  However $ isn't required any more anyway.
