### ISSUE TITLE
Apply fetch and cache optimizations from #7463 to relevant amp-bind cases

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#8322]
#7463 details optimizations that reduce the number of calls that need to be made for batches of data that can be used in various parts of the page. @cramforce mentioned that these optimizations might also be applied to amp-bind XHRs

/to me
/cc @choumx  @cvializ

**Comment by choumx** [comment]
@ericlindley-g Is that the right issue number?

**Comment by ericlindley-g** [comment]
Good catch—just updated

**Comment by choumx** [comment]
AFAICT this is an implementation detail of #7907. Closing in favor of that issue.

**Comment by ericlindley-g** [comment]
Sounds good (/cc @cramforce to make sure we're not missing any other related opportunities w/ amp-bind)
