### ISSUE TITLE
Validator rejects hrefs with more than 2 slashes after protocol

### ISSUE THREAD

**Issue by src-code** [ampproject/amphtml#8330]
Currently a page will fail to validate if it contains an anchor tag with an href that includes more than 2 slashes between the protocol and host portions.  For example, this document:

https://www.yahoo.com/amphtml/news/kim-kardashian-live-blogs-her-152648523.html

Is invalid because it contains a link to:

http:///mashable.com/category/kim-kardashian/?utm_campaign=&utm_context=textlink&utm_source=

Note 3 slashes between the protocol and hostname.

To spec this link isn't a valid URL, so the validation is technically correct, but Chrome, Firefox and Safari for iOS navigate to such URLs anyway.  AFAIK only Safari on OS X (as of v10) fails to navigate.

Wondering, would it be reasonable to relax the validator to allow, or at least warn, on such URLs?  I'm personally of two minds about it, but wanted to raise the issue to see what others think.

(Perhaps this is just an extension of my previously raised issue about warning vs failing on invalid hrefs - issue #6378 - but unique in the sense that in this case the URLs are generally able to be navigated.)

## Which AMP version is affected?

1489777197505

**Comment by Gregable** [comment]
I'd rather not go too far down the route of validating specific technically invalid variants, as there are probably an infinite list of these. In cases like this, we'd also need to be sure that relative URL rewriting works consistently in all AMP cache implementations, so caches become a useragent to test against as well.

I'm OK with some of them, such as the empty URL case. Instead, we should just decide to remove invalid URLs in the cache and warn on them (ie #6378).

**Comment by src-code** [comment]
@Gregable Sounds reasonable to me.
