### ISSUE TITLE
Client behaviour when AMP page page is unavailable

### ISSUE THREAD

**Issue by edlea** [ampproject/amphtml#834]
I can't see anything in the specifications detailing what a client should do if an AMP page is unavailable for some reason.

For example, what should a client do if the request for AMP returns an HTTP status of 500 or 204?

**Comment by cramforce** [comment]
Sorry, missed this.

Are you asking for a client that tries to resolve from non-AMP to an AMP page? I'd say they should assume there is no-AMP page. Probably good to assume it is transient and try again next time the page is considered.

**Comment by edlea** [comment]
As a bit of extra background, I've been playing around with a tool to generate AMP pages automatically from regular content. It doesn't always find appropriate content though. Rather than having to manually review every page on a site, it would be nice to simply add a single tag to every page and if the page isn't AMP-ready return a status code to reflect that.

For example, here's a page that is correctly identified: https://api-cdn.something.gd/amp?http://uk.businessinsider.com/the-apple-platform-advantage-explained-2015-11

And one that isn't: https://api-cdn.something.gd/amp?https://github.com

**Comment by cramforce** [comment]
I think returning 404 would be appropriate.

Having said that, AMP is specifically not about automatic conversion (Not saying your project isn't interesting, useful, or awesome, just that the AMP tries to do optimize else). There are quite a few tools out there that do something like that (E.g. Safari Reader), but AMP provides similar speed while retaining publisher control of how the pages look.
