### ISSUE TITLE
amp-iframe: resize no longer working

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#8351]
## How do we reproduce the issue?

1. Go to https://vine-diamond.glitch.me
2. Click on 'Preview' 
3. The iframe is supposed to resize, but doesn't.

## What browsers are affected?

All browsers

## Which AMP version is affected?

This used to work, I've noticed that it stopped working with  AMP ⚡ HTML – Version 1489777197505

**Comment by jpettitt** [comment]
It's working for me on our prod pages.  Example http://amp.toofab.com/2017/03/10/pharrell-williams-makes-history-as-first-male-ever-to-appear-in-a-chanel-handbag-campaign-photos/ (the intagram embed is an iframe, pending the new `amp-instagram` version going live)

**Comment by sebastianbenz** [comment]
@jpettitt thanks - that was driving me crazy. 

Found out what my problem was:

* My sample stopped working because gomix.me started redirecting to glitch.me.
* In my other tests I didn't set `allow-same-origin` which is required.  Filed  #8365 as a result.

Also created a [proper sample](https://amp-by-example-staging.appspot.com/components/amp-iframe/#resizeable-iframes) to avoid this happening again...
