### ISSUE TITLE
Slidescroll doesn't update next slide when overscrolling in ios with custom snap

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#8352]
After https://github.com/ampproject/amphtml/issues/7670, we go with the solution to disable css snap point and use custom snap for slidescroll in ios beta. But the problem with custom snap in ios is the overscroll. When overscrolling, we currently don't update the slides state to load the next one, but only update slides when scroll ends.

/cc @camelburrito

**Comment by camelburrito** [comment]
This should not be a p2 (its definitely p1). prefer tracking this in #7670
