### ISSUE TITLE
LayoutCallback sometimes not called in amp-app-banner

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#8358]
The [layoutCallback](https://github.com/ampproject/amphtml/blob/master/extensions/amp-app-banner/0.1/amp-app-banner.js#L392) in `AmpAndroidAppBanner` is sometimes not called but `buildCallback` is called. It might has something to do with the bug @jridgewell mentioned about upgraded element?

I opened up https://amphtml-nightly.herokuapp.com/examples/article.amp.max.html#webview=1 and put a break point in the `layoutCallback`, the break point is sometimes hit sometimes not.

/cc @jridgewell

**Comment by ericlindley-g** [comment]
Agreed — I feel like this borders on a P0, since it's broken in production, but may be just slightly lower because of a lack of examples where it's actually being used (I suspect folks have tried it out and noticed the bug, which is also bad)

**Comment by jridgewell** [comment]
I'm not able to reproduce, it always calls `AmpAndroidAppBanner#layoutCallback` for me.

**Comment by muxin** [comment]
Strangely I cannot reproduce it anymore on https://amphtml-nightly.herokuapp.com/examples/article.amp.max.html#webview=1, but if I test in viewer sandbox using http://www.google.com/amp/embedded?ampdev=1#amp=https://amphtml-nightly.herokuapp.com/examples/article.amp.max.html?amp_js_v=8&ampidx=0, it still doesn't call `layoutCallback`.

**Comment by jridgewell** [comment]
Tracking it down, it's because the element does not have width and height when the initial measurement happens and is never re-measured. If it doesn't have width and height, we never call `#layoutCallback` (but we will call `#buildCallback`).

**Comment by jridgewell** [comment]
Ok, so maybe a framework issue and a little one with how `<amp-app-banner>` is coded (this affects both iOS and Android banners):

- Element is `layout = NODISPLAY`, meaning `display: none` is set
- Initial measure happens, box is (0, 0)
- `#buildCallback` is called, element is hidden but display is reset
- `#checkIfDismissed` eventually decides to reset visibility

If the initial measure happens _after_ the element is built, everything will work fine.

This affects all elements we set as `NODISPLAY` that later decide to actually display (I haven't confirmed that this will affect them all (do they have a `#layoutCallback`, does validator forbid `NODISPLAY`), just that they might be affected).

- amp-animation
- amp-ads
- amp-auto-ads
- amp-app-banner
- amp-analytics
- amp-pixel
- amp-image-lightbox
- amp-lightbox
- amp-selector
- amp-share-tracking
- amp-sidebar
- amp-social-share
- amp-sticky-ad

The fix here is to use the new `#expand` in `#checkIfDismissed`. But, we may want to fix this at the framework level by always requesting a remeasure after a `NODISPLAY` is built.

**Comment by muxin** [comment]
Closing this because cannot repro anymore

**Comment by muxin** [comment]
Still not fixed
