### ISSUE TITLE
Validation rules for CSS position: sticky elements?

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#8371]
What are the validation rules going to be for `position: sticky`, given that his could be used to pin an `<amp-ad>` ?

https://developer.mozilla.org/en-US/docs/Web/CSS/position

**Comment by techhtml** [comment]
`amp-ad` does not allowed stickiy and fixed position for UX implications of full page overlay ads.
https://www.ampproject.org/docs/reference/components/ads/amp-ad

but you can use `amp-sticky-ad`, if you want `position: stciky` for `amp-ad` then you can use it
https://www.ampproject.org/docs/reference/components/ads/amp-sticky-ad

**Comment by jpettitt** [comment]
Are there any other validation rules related to sticky?

**Comment by techhtml** [comment]
`amp-ad`'s validation code are here:
https://github.com/ampproject/amphtml/blob/master/validator/engine/amp4ads-parse-css.js#L114

other validation rules are seems not, here are css validation rules code:
https://github.com/ampproject/amphtml/blob/master/validator/engine/parse-css.js

**Comment by jpettitt** [comment]
That looks like the code for a4a, what about regular `<amp-ad>`?

**Comment by jpettitt** [comment]
Yes position sticky does work with amp-ad - that sounds like a validation bug to me.

**Comment by Gregable** [comment]
The mapping of CSS rules to specific tags for static validation is difficult to do in the general case, so we have not been making rules of that type to date.

**Comment by cramforce** [comment]
Assignee @lannka is correct. This needs to be fixed in the `isPositionFixed` function in `ad-helper.js`

**Comment by jpettitt** [comment]
@gregable I understand it's hard, amp-ad is forbidden in fixed layers (refuses to render) and this is a psudo fixed layer ...
