### ISSUE TITLE
Migrate amp ad hardcoded validation rules to rules file

### ISSUE THREAD

**Issue by dknecht** [ampproject/amphtml#8375]
One example is the CSS rules for amp ads:  https://github.com/ampproject/amphtml/blob/master/validator/engine/amp4ads-parse-css.js#L193

```
      const allowed =
          ['animation', 'opacity', 'transform', 'transition', 'visibility'];

```

**Comment by adelinamart** [comment]
I was wondering if we still consider working on this. Thank you.
