### ISSUE TITLE
Fix vsync issue when document is not visible.

### ISSUE THREAD

**Issue by sriramkrish85** [ampproject/amphtml#839]
-- better Title and desc to be provided for this bug.

**Comment by cramforce** [comment]
We need to decide what that means. Default vsync should **NOT** fire when the tab is invisible (including our pseudo invisibility.).

**Comment by dvoytenko** [comment]
Absolutely agree. This is just a reminder for me to review these cases and
make a decision on how to address it best. But we definitely won't be doing
RAF fallback.

**Comment by cramforce** [comment]
So @sriramkrish85 should not be using vsync in his case, because he wants these to fire.

**Comment by dvoytenko** [comment]
I think it's solvable in follow-up. But we can certainly address in the
current pull request.

**Comment by dvoytenko** [comment]
I'd like to keep this issue open a little longer. I'm still planning some review on this.
