### ISSUE TITLE
amp-bind: Make it easier to modify non-primitives

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#8394]
`AMP.setState` performs shallow merge via `Object.assign` which makes it difficult to modify Arrays and Object literals. Avoiding APIs that mutate existing objects was a security suggestion by @molnarg.

E.g. `/examples/bind/turing.amp.html` uses a horrific combo of `slice` and `concat`  to change the tape array:
```
T.cells.slice(0, T.head).concat(
    [ T.instructions[T.state][ T.cells[T.head] ].write ])
        .concat(T.cells.slice(T.head + 1)),
```
- The API for `Array.splice` could work if it returned a new array -- perhaps we should offer a custom variant?
- Full merge for `AMP.setState` would also make mutating Object literals easier (though deleting keys harder).

/cc @kmh287

**Comment by kmh287** [comment]
@choumx I was thinking of proposing the same thing. Do we have an issue where we discussed the security implications of mutating objects in bind's state?

**Comment by choumx** [comment]
@kmh287 I think we should add some more documentation about deep merging with some examples (including how to remove a key) in an "Appendix" section of amp-bind.md. Would you mind doing that as part of this issue?

Also, can you run do some casual perf testing of deep merge with large autogenerated JSON? I'm curious how expensive this is in practice. E.g. if it is very expensive, perhaps it's worthwhile creating a separate `AMP.mergeState` method.

**Comment by kmh287** [comment]
@choumx Both ideas sound good. :+1:

**Comment by kmh287** [comment]
@choumx I created a state with ten top level objects, each with ten object properties, each with ten object properties, each with ten string properties. (depth of 4 with 10 objects at the top layer and geometrically increasing at each layer). Evaluation of the expression took ~8ms on my machine (no throttling). Deep merging the object with itself (most expensive case) took about 9ms (also with no throttling).

**Comment by choumx** [comment]
Can you put your test file into a gist and link to it here?

**Comment by kmh287** [comment]
[Enjoy](https://gist.github.com/kmh287/621e88fe000c5bf7ebe6f3969e5af973)

**Comment by choumx** [comment]
Seems reasonable compared to parsing cost, but I'm not sure why parsing seems to be a lot slower now. Parsing the expression `{state: state}` should not take so long.

**Comment by kmh287** [comment]
How slow was parsing on your end?

**Comment by kmh287** [comment]
Arrays are difficult to work with if more than one element is being updated at once. See  https://github.com/ampproject/amphtml/pull/8729#discussion_r111408010. Maybe we should add a custom function that shallow or deep merges two arrays?

**Comment by kmh287** [comment]
Closing for now.
