### ISSUE TITLE
amp-mustache: Auto escaping of quote chars

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#8395]

**Comment by kmh287** [comment]
Is there a case this doesn't work for? I just tried:

```HTML
<p [text]="'&quot;' + sentence + '&quot;'"></p>
<button on="tap:AMP.setState({sentence: 'You have pressed &quot;the button&quot;'})">foobar</button>
```
Where pressing the button will change the p tag's text to: `"You have pressed "the button""`

**Comment by micyeung** [comment]
Hi - any update on this issue? Quote escaping is particularly important in e-commerce use cases where single / double quotes appear quite frequently.

**Comment by choumx** [comment]
Does @kmh287's workaround (above) work for those use cases?

**Comment by pbakaus** [comment]
For single quotes, would `&lsquo;` (left hand single quote) and `&rsquo;` (right hand single quote) work instead? They seem to be the ones that carry the right semantic meaning.

**Comment by leonalicious** [comment]
the workaround above is not fitting to all cases. The **Edit 1 is to escape double quote** and the **Edit 2 is to escape single quote**.  However, at our case, our contents will contain both Single quote & Double quote.
The figures below show if both if both single quote & double quote appear on the line.

![code](https://user-images.githubusercontent.com/4065175/34486723-0f261b92-f00c-11e7-8fcc-26a97f21377a.png)
<img width="973" alt="dingtalk20180102222441" src="https://user-images.githubusercontent.com/4065175/34486724-0f58fc1a-f00c-11e7-9198-275e021f0d68.png">

While dealing with this, I have come out a solution, which we can use the Edit 2 approach ( to escape single quote) by changing all the `double quote` with &Prime; `&Prime` to avoid the conflicting of double quote.

However, I am using `<amp-mustache>` for the templating and I am not too sure how it is not working. Please advise how this can be achieved inside `<amp-mustache>`, appreciate it.
![image](https://user-images.githubusercontent.com/4065175/34486376-9e350bb0-f00a-11e7-9e74-2bd789648289.png)

**Comment by choumx** [comment]
Not sure I fully understand. In your example above, it looks like the HTML is:
```html
<button class="btn" on="tap:AMP.setState({sentence: &quot;'Boot&apos;s Attributes is 3&quot; and above &quot;})">
```
Looks like the value of the `sentence` key is not quoted correctly:
```js
sentence: &quot;'Boot&apos;s Attributes is 3&quot; and above &quot;
```
What you probably want is this:
```js
sentence: 'Boot&apos;s Attributes is 3&quot; and above'
```

**Comment by leonalicious** [comment]
Hey William, thank you for the quick feedback, I have tried 

> What you probably want is this:
sentence: 'Boot&apos;s Attributes is 3&quot; and above'

and it is still not working, anyway, I have found a solution for this. Which is ：

1.  By changing all double quotes &quot; to Prime &Prime; before JSON is passed from our backend , to avoid conflicting with `<html>` double quotes, although there are some layout different but it is acceptable.
2.  This one is my mistake, I missed out and have reviewed back `<amp-mustache>` [documentation link here](https://www.ampproject.org/docs/reference/components/amp-mustache#restrictions) , by using triple curly braces`{{{attributes}}}` and now it is working fine ! case closed.

**Comment by leonalicious** [comment]
Quick update since January, triple curly braces of `amp-mustache` will not pass the amp-validator, so we moved the `Prime ″` to backend instead, rendered the character before it is passed to browser, let's close this issue.

**Comment by choumx** [comment]
Dev-ex would be improved if we can avoid the need for developers to change backend data (e.g. replace `'` with `′`). One idea is to allow a [mustache lambda](https://mustache.github.io/mustache.5.html) that can perform this specific replacement in sections of template code.

E.g. in the example below, rendering with the `bar` variable will generate a runtime error if it contains a single or double quote character.
```html
<template type="amp-mustache">
  <button on="tap:AMP.setState(foo: 'Templated {{bar}} needs quote escaping')">
  </button>
</template>
```

We can support a `quotable` lambda (name configurable) that does this replacement e.g.

```js
{
  bar: "This single-quote (') causes a runtime error",
  quotable: function() {
    return (text, render) => render(text.replace("'", "′"));
  }
}
```

```html
<template type="amp-mustache">
  <button on="tap:AMP.setState(foo: '{{#quotable}}{{bar}}{{/quotable}}')">
  </button>
</template>
```

**Comment by swindjam** [comment]
It's not quite the same issue, but this also happens when using amp-mustache templates in amp-bind.
E.g. `data-amp-bind-text=" '{{ offer.name }}' "` breaks if the value from the items in an amp-list includes a `'` such as `Microsoft Xbox One X Console, 1TB, with Wireless Controller, Black and PlayerUnknown's Battlegrounds Game Bundle`

We could replace the quote in our api but we don't want to do this to avoid causing edge cases.

Ideally we would just output the data from mustache and escape the strings, but that doesn't appear to be an option at present

**Comment by choumx** [comment]
New feature: If you use `<script type="text/plain" template="amp-mustache">` instead of a `<template type="amp-mustache">` to specify the mustache template string, you can use HTML char codes in the template (e.g. `&apos;` instead of `'`) and they will be preserved. 

See https://github.com/ampproject/amphtml/blob/master/extensions/amp-mustache/amp-mustache.md#usage for details.

This is probably preferable to the "auto-escaping" proposal above.

**Comment by choumx** [comment]
Closing as obsolete.
