### ISSUE TITLE
amp-carousel: IE/Edge + data-image without encoding

### ISSUE THREAD

**Issue by CemDemirkartal** [ampproject/amphtml#8401]
Internet Explorer do not show right and left arrow without base64 encoding on background-image 

Tested on Edge 14.

**Comment by CemDemirkartal** [comment]
Bootstrap v4 has similar but there are difference as on down.
It works well on Edge 14

Example from Bootstrap v4 Alpha 6

```css
background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23fff' viewBox='0 0 8 8'%3E%3Cpath d='M1.5 0l-1.5 1.5 2.5 2.5-2.5 2.5 1.5 1.5 4-4-4-4z'/%3E%3C/svg%3E");
```

**Comment by aghassemi** [comment]
related: https://github.com/ampproject/amphtml/pull/6920
