### ISSUE TITLE
lightbox don't open in AMP page from Safari and Chrome SERP

### ISSUE THREAD

**Issue by sameeh-harfoush** [ampproject/amphtml#8405]
## Short description of your issue:

I have an AMP version of my original pages:
Original: https://lb.brate.com/en/kababji-hamra-beirut-lebanon/b-661
AMP: https://lb.brate.com/en/amp/kababji-hamra-beirut-lebanon/b-661

The AMP page opens a lightbox when clicking on the "English" label at the footer of the page (a language selector)

The lightbox works well when opening the above AMP page directly from the browser. But when opening page from Google SERP from the below URL https://www.google.com.lb/amp/s/lb.brate.com/en/amp/kababji-hamra-beirut-lebanon/b-661 the page loads normally but the lightbox stops working. clicking multiple times gives the impression that the lightbox is opening and closing instantly

## How do we reproduce the issue?

1. open safari or chrome on mobile
2. go to google.com.lb
3. search for "kababji harm brate" 
4. click on the link ending with "Brate" from SERP
5. scroll to the end of the page
5. click on the "English" label

## Which AMP version is affected?
cdn.ampproject.org/v0.js
cdn.ampproject.org/v0/amp-lightbox-0.1.js

**Comment by fueledbymarvin** [comment]
I'm experiencing this issue. All it does is append the fragment `#amph=1`.

An easier reproduction is simply going to the demo here: https://www.google.com/amp/s/ampbyexample.com/components/amp-lightbox/

It works fine directly on the site (https://ampbyexample.com/components/amp-lightbox/) and via the amp project cdn (https://cdn.ampproject.org/c/s/ampbyexample.com/components/amp-lightbox/). It only fails on the google viewer.

**Comment by aghassemi** [comment]
All, apologies for the breaking change. This issue has the same root-cause as the P0  https://github.com/ampproject/amphtml/issues/8399 which we have a solution for and waiting for deployment to production.

**Comment by aghassemi** [comment]
The fix is in production and the issue has been resolved. Sorry for the inconvenience.

**Comment by sameeh-harfoush** [comment]
Thank you guys for the support.
Now i have another problem, Google SERP is serving AMP pages on desktop. (check https://www.google.com.lb/#q=kababji+hazmieh+inurl:amp&*)
Should i open the issue here?

**Comment by aghassemi** [comment]
@sameeh-harfoush For the SERP issue, could you please post to the [Webmaster Forum](https://productforums.google.com/forum/#!forum/webmasters)? Folks monitoring that forum are more knowledgeable on this topic than the open-source AMP group on Github.

**Comment by fueledbymarvin** [comment]
Thanks for the fix!
