### ISSUE TITLE
Blank Page for Non Fixed Layers

### ISSUE THREAD

**Issue by bryancolligan** [ampproject/amphtml#8418]
Description: 
create fixed layer in the top nav  google cache will process create a new dom in the fix layered script and add css '-webkit-overflow-scrolling: touch !important’.  
Non fixed layer initial load shows a blank page under the fixed nav and amp-sidebar once amp-sidebar menu is touched, page will show as normal.

url: https://www.google.com/amp/s/www.instapainting.com/pets-amp.html#development=1
Device: iphone 6 and safari browser
AMP: version 0

**Comment by jridgewell** [comment]
I'm not able to reproduce this anymore. Was there a fix on your side?
