### ISSUE TITLE
Lightboxed Slide Images Sometimes Never Load/Show

### ISSUE THREAD

**Issue by johnnyshankman** [ampproject/amphtml#8420]
Here is a video of the bug in action: http://recordit.co/QQRb4PDkR6

When putting an `<amp-carousel>`  of `<amp-img>`s within an `<amp-lightbox>` sometimes images within the carousel load indefinitely, even though their preview counterpart (same image URL) has already loaded and is showing on the page behind the lightbox.

I've noticed that switching slides and then returning back to the slide will "unstick" the loader + loading state. It seems that the presence of a placeholder has no difference on this bug.

## How do we reproduce the issue?

1. Create a lightbox
2. Attempt to nest an amp carousel of amp imgs within that carousel.
3. Get flaky loading behavior for images within the slideshow.
4. If the image loads indefinitely, you can get it to show up by going forward/back a slide and then returning the originally broken slide.

This JSBin is a watered down versions, so it's not exactly like what we have. It is not showing images at all and seems like it should be.

http://jsbin.com/fixunufine/edit?html,output

Seems like there's one` -i-amphtml-layout` class missing? I've tested both with and without the presence of custom placeholders and the behavior is still the same.

![screen shot 2017-03-27 at 4 05 32 pm](https://cloud.githubusercontent.com/assets/6632701/24376870/6900a8c8-130b-11e7-9ddc-855f4a7aaba6.png)

![screen shot 2017-03-27 at 4 06 26 pm](https://cloud.githubusercontent.com/assets/6632701/24376869/68fd9f70-130b-11e7-95e9-53cceb45961f.png)

## What browsers are affected?

All

## Which AMP version is affected?

1490234009582

**Comment by aghassemi** [comment]
@johnnyshankman, please use `layout=fill` for the carousel when inside the lightbox to solve your issue. Also since we have fill layout for images, we should control how the images are fit using css, otherwise they will get distorted ( I recommend `object-fit: contain` ). Here is a alternative version of your fiddle with these fixes applied: http://jsbin.com/seluvekoqe/1/edit?html,output

**Comment by johnnyshankman** [comment]
@aghassemi Thank you! I forgot to include the `object-fit: contain` code that we have in our CSS currently which explains why my jsbin was a little wonky. The `layout=fill` and then refactoring the CSS to have centering and height restrictions elsewhere got me exactly what I needed. 

Thank you!

**Comment by aghassemi** [comment]
@johnnyshankman Anytime! Glad that helped.
