### ISSUE TITLE
Intent-to-Implement: Rakam

### ISSUE THREAD

**Issue by buremba** [ampproject/amphtml#8442]
I would love to add Rakam as an amp-analytics plugin, the implementation is similar to Segment's PR and pretty straightforward.

A simple example that sends a page view:
```
<amp-analytics type="rakam">
<script type="application/json">
  {
    "vars": {
      "apiEndpoint": "<rakam api url>",
      "writeKey": "<key>",
    }
  }
...
```

**Comment by dvoytenko** [comment]
Hi @buremba! Thanks a lot for the issue. Is this just a config contribution? If so - yes, go ahead and send us the pull request. If you are looking for more features, please clarify.

**Comment by buremba** [comment]
Hey @dvoytenko! It's just the implementation for a new analytics provider, Rakam. I already have a pending PR here #8443.  It would be great if you can review it when you have time,
