### ISSUE TITLE
Cleanup uses of Array#indexOf to use Array#includes

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#8450]
### First Timers Only
We know figuring out the process for contributing to an open source project can be intimidating, so we created this issue as a way for you to learn the ropes.  (If you feel comfortable contributing to open source projects, please leave this issue for someone else.)

### What you will need to know
- Javascript

### Background

Recently, we introduced an [`Array#includes`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) polyfill to our codebase, so now everything in the core AMP code can use it. But, a lot of old code was written before this, so we have things like:

```js
// This is just Array#includes
if (array.indexOf(x) > -1) {
}
if (array.indexOf(x) >= 0) {
}
if (!(array.indexOf(x) == -1)) {
}

// Or this is array doesn't include
if (array.indexOf(x) == -1) {
}
if (array.indexOf(x) < 0) {
}
```

### Motivation

It'd be good to convert these over to just use `Array#includes` (or the not version).

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] Replace uses of `#indexOf`
  - Grep search for `"\.indexOf\("`
  - If the caller is definitely an Array instance, let's convert it over to `#includes`
  - The one exception is when the return index is actually needed (like a splice or something). Basically, only convert if we just need a boolean check
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review).  Mention `closes Issue <this issue number>` in the description.
  - CC Me (@jridgewell) and Kevin (@kmh287)
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/README.md#releases)!

Thanks, and we hope to see more contributions from you soon.

### Questions?

If you have questions ask in this issue or on your Pull Request (if you've created one) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.  Or ping @jridgewell.

**Comment by dhulwells** [comment]
I'll take this one on.

**Comment by nandosangenetto** [comment]
Can I take it? I could finish by tomorrow.

**Comment by dhulwells** [comment]
@nandosangenetto Yes sir, sorry got busy with work.

**Comment by nandosangenetto** [comment]
@dhulwells ok, thanks. I'm starting right now :)

**Comment by nandosangenetto** [comment]
@jridgewell should I change strings to use include as well? When the return might be true or false?
