### ISSUE TITLE
Momentum scroll stopped by "-amp-no-scroll" on iOS 10 Safari

### ISSUE THREAD

**Issue by p2er** [ampproject/amphtml#8476]
If scrollable content is placed inside a carousel slide and scrolled on iOS Safari the scrolling will feel native until a class is set to prevent horizontal scrolling. Works perfectly fine on Android Chrome, but stutters in the same way on iOS Chrome.

## How do we reproduce the issue?

Test With 3 scrollable articles inside the amp-carousel element: https://p2er.github.io/amp-articleslider/

1. Open in iOS (10.2) Safari
2. Scroll down and see momentum scroll
3. See scrolling stop during momentum speed decrease
4. Stops as soon as class "-amp-no-scroll" is toggled on div with class "-amp-slides-container"

## What browsers are affected?

Tested on iPhone 6s with Safari and Chrome 
Does not happen on iOS 10.3

## Which AMP version is affected?

All elements are embedded with version 0.1

**Comment by aghassemi** [comment]
/to @yuxi @camelburrito  https://github.com/ampproject/amphtml/pull/7966 may have broken momentum scrolling on iOS 10.2 (10.3 is fine)

**Comment by camelburrito** [comment]
This should also be a P0. I think the IOS version check is not working as expected I guess. @muxin can you take a look at what is going on

**Comment by aghassemi** [comment]
@camelburrito it is still functional, just the nice momentum animation is gone. Keeping it P1 but also I am looking at fixing it today.
