### ISSUE TITLE
WhatsApp social share not working iOS 10.3 Safari

### ISSUE THREAD

**Issue by ankur0890** [ampproject/amphtml#8477]
Amp social share buttons are not working on iOS 10.3 Safari. It's working fine on Google chrome and previous iOS versions. PFA the video also 
[iphone-ankur.mov.zip](https://github.com/ampproject/amphtml/files/878360/iphone-ankur.mov.zip)

In current problem its opening an blank web page. Can you please check the same and fix on priority.

Thanks
Ankur Aggarwal

**Comment by aghassemi** [comment]
@ankur0890 I have been unable to repro this on my iPhone 6s with 10.3 (not beta). Did you notice this on a real device or a simulator? Also do you have a URL other than ampbyexample that you have noticed this is happening on?

**Comment by ankur0890** [comment]
@aghassemi I have tested in iPhone 7 iOS 10.3. Problem comes in Safari only. Yes In the video i have attached I am using amp by example social only. Clicking on whatsapp icon and getting the issue.

**Comment by aghassemi** [comment]
@ankur0890 Thanks. Got it. I can repro with WhatsApp and will look into fixing it ASAP.  Other social shares seems to work fine though, could you please confirm that it is only happening for WhatsApp for you as well?

**Comment by ankur0890** [comment]
@aghassemi yes others are working fine. Checked it. Only whatsapp has the  problem.

**Comment by ankur0890** [comment]
@aghassemi  Thanks for resolving the issue on priority. Is it live as I am still getting the error?

**Comment by aghassemi** [comment]
@ankur0890 Not in prod yet, will be sometime later today

**Comment by ankur0890** [comment]
@aghassemi Working now. Thanks for quick fix :)
