### ISSUE TITLE
Alternative implementations of cache and/or components library

### ISSUE THREAD

**Issue by veged** [ampproject/amphtml#8478]
As we discussed at APM Conf with all current and potential «platforms» (i.e. third party cache and/or components library from Yandex, Baidu, Microsoft and etc.) we need to support and document them on the top level.

What may differ from platform to platform:
  - cacher ([related issue](https://github.com/ampproject/amphtml/issues/4793#issuecomment-289425730))
  - static CDN (most likely we need the same solution as with cacher)
  - components library:
    - may have slightly different implementations of same components
    - may have additional components (so we need changes in validation process to skip unknown tags and/or something like `<amp-alternatives>` for an ability to provide a prioritized list of tags, i.e. `<amp-popup>`, `<amp-img>`, to choose first implemented on current platform)

**Comment by rudygalfi** [comment]
@veged In your nomenclature, can you clarify what the difference between "cacher" and "static CDN" is?

**Comment by cramforce** [comment]
The 2 currently existing AMP Caches rewrite AMP JS URLs to their own CDN to be able to have fully qualified version URLs.

Regarding alternatives: The existing fallback mechanism can probably do that without new semantics. I could see to whitelist tags with a certain prefix in the validator. How would their implementation (Typically a JS file) get into the page?

**Comment by veged** [comment]
@rudygalfi «cacher» — for serving APM html
«static CDN» — for serving js/css

**Comment by veged** [comment]
@cramforce What do you mean by «existing fallback mechanism»?
I suppose alternative tags are coming with alternative js/css for platform.

**Comment by cramforce** [comment]
@veged Something like this works in AMP

```html
<amp-foo>
  <div fallback>Rendered if amp-foo fails to render</div>
</amp-foo>
```

So you can nest alternative implementations.

**Comment by veged** [comment]
@cramforce if it even works with `<amp-*>` (i.e. I can put `<amp-img>` inside `<amp-foo>`) tags it's exactly what we need!

**Comment by cramforce** [comment]
It does.

**Comment by rudygalfi** [comment]
It looks like this thread resolved, so I'm going to close. Please re-open if not.
