### ISSUE TITLE
iOS 10.3 amp-image-lightbox image does not resize on orientation change

### ISSUE THREAD

**Issue by mikeduarte** [ampproject/amphtml#8479]
On iOS 10.2 when I would open an image in an amp-image-lightbox in portrait then rotated the phone to landscape, the image would resize and fill the available space as well as get repositioned.  On iOS 10.3 the image doesn't resize or move. 

## How do we reproduce the issue?
1. Go here:  https://ampbyexample.com/components/amp-image-lightbox/
2. In portrait orientation, tap an image to open it in a lightbox
3. Rotate your phone to landscape.  Notice the image is stuck on the bottom left of screen.

## What browsers are affected?
Mobile Safari 10.3

## Which AMP version is affected?
- ampbyexample link above is running:  Version 1490652623650 of AMP.
- Use to work fine in 10.2

**Comment by kristianantov** [comment]
I fixed the problem for now ... it's not the best way but works ... on Orientationchange event I made these 2 methods : 
						    	      
lightBox.invalidateCurrItems();
								
lightBox.updateSize(true);

**Comment by aghassemi** [comment]
/to @muxin 

Take a look at this comments ( https://github.com/dimsemenov/PhotoSwipe/issues/1315#issuecomment-291897591 ) It explains what causes the bug in iOS 10.3. It also talks about a temp solution that we may need to do for 10.3 version and above.

**Comment by muxin** [comment]
@dvoytenko The bug happens because the [measurement of imageViewer](https://github.com/ampproject/amphtml/blob/master/extensions/amp-image-lightbox/0.1/amp-image-lightbox.js#L258) (invoked by [viewport resize event](https://github.com/ampproject/amphtml/blob/master/extensions/amp-image-lightbox/0.1/amp-image-lightbox.js#L801)) happens before orientation change takes place. I wonder what should be an appropriate time for the measurement to happen? (Simply adding vsync around measurement doesn't work)

**Comment by muxin** [comment]
OK, as the referenced issue suggested, adding a timeout could be a temp fix.

**Comment by dvoytenko** [comment]
Maybe we should listen for both? Resize events and orientation change events? That might be the most accurate and I hope that size is definitely updated for one of them.

**Comment by aghassemi** [comment]
Webkit bug here: https://bugs.webkit.org/show_bug.cgi?id=170595

**Comment by aghassemi** [comment]
@muxin Could you subscribe to https://bugs.webkit.org/show_bug.cgi?id=170595 so we can remove whatever hack we put in once it is fixed?

**Comment by muxin** [comment]
From the webkit bug description, it seems that it also provide wrong values during orientationchange event. So the temp fix could be the timeout.
