### ISSUE TITLE
CustomEvent is not defined

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#8495]
ReferenceError: CustomEvent is not defined
at ka (https://cdn.ampproject.org/rtv/001490719419065/v0/amp-carousel-0.1.js:29)
at (https://cdn.ampproject.org/rtv/001490719419065/v0/amp-carousel-0.1.js:27)
at Ni (https://cdn.ampproject.org/rtv/001490719419065/v0.js:351)
at Ji.f.qf (v0.js:350)

i know we guard against this so not sure why we're hitting this scenario.

https://github.com/ampproject/amphtml/blob/master/extensions/amp-carousel/0.1/slidescroll.js#L571
https://github.com/ampproject/amphtml/blob/master/src/event-helper.js#L32

sample user agents:
Mozilla/5.0 (Linux; U; Android 4.3; de-de; GT-I9300 Build/JSS15J) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30 

Mozilla/5.0 (Linux; U; Android 4.3; it-it; GT-I9300 Build/JSS15J) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30 [FB_IAB/FB4A;FBAV/117.0.0.18.47;]

**Comment by aghassemi** [comment]
@erwinmombay @choumx fixed this recently with https://github.com/ampproject/amphtml/pull/8345
