### ISSUE TITLE
Ensure AMP animations use zero CPU when off screen

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#8499]
Animations should be paused/ not started and never take up any CPU cycle when off screen.

**Comment by lannka** [comment]
Right now there're 2 ways to animate in AMP. CSS and `amp-animation`. 

For CSS animation, we don't have much control right now. Except that we do restrict CSS animation in ads. We planned to pause CSS animation in ads once out of viewport, see #7846.

For `amp-animation`, we currently don't pause animation. @aghassemi had some idea about triggering and pausing animation with visibility info.

**Comment by aghassemi** [comment]
The visibility conditions for `amp-animation` will be done as part of  https://github.com/ampproject/amphtml/issues/8411 . Haven't though about how this can/does related to CSS animations.

**Comment by jasti** [comment]
That sounds good. The CSS ones will be handled in #7846.

**Comment by lannka** [comment]
OK, sounds we have separate trackers for the 2. Closing this now.
