### ISSUE TITLE
Enhance host.js to listen for scroll bound animations for AMP in a box

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#8500]
We'd want to ensure #8411 works well when AMP ads use it and deliver to non-AMP pages. 
CC @ampproject/a4a

**Comment by lannka** [comment]
We will enable the Position API for Android (currently only enabled for iOS).

@keithwrightbos @bradfrizzell just want to confirm with you that ads tag side is not disabling host.js for Android.

**Comment by keithwrightbos** [comment]
Currently no, we will assume we should leave it in place going forward.

**Comment by lannka** [comment]
Closed by #8755
