### ISSUE TITLE
No adv request into amp carousel

### ISSUE THREAD

**Issue by MarkusDima** [ampproject/amphtml#8501]
Hi all,

thanks in advance to anyone for the support.

## Short description of your issue:

When I navigate into the amp corousel resulting from a google search, sometimes I can see the adv sometimes no.
The issue is random and It's hard for me to debug it.
The result that I expect is to see an OAS ads in the page (a box 300x250 px - OpenAdStream).
The problem is that randomly the ads request doesn't start and the placeholder is still visible (this the same behaviour when the cookie policy has not been accepted).

Example Adv request expected:
 https://oas.rcsadv.it/3/mobile.gazzetta.it/gazzanetamp/1979610380@Frame1?keyword=

To reproduce the issue you can do the following steps:

1. Navigate to google.com
2. Search "violanews"
3. Navigate into amp carousel 
4. Accept cookie policy
5. Navigate into the articles

If you see the placeholder it means that the adv request has not started

The library included into these kind of article is:
https://cdn.ampproject.org/rtv/021490652623650/v0/amp-ad-0.1.js
and the tag is amp-ad

Please do not hesitate to ask me further information about the issue.

Thanks,
Marco

**Comment by andscova** [comment]
Hi all,

I double Marco's request.
Thanks for taking a look into this.
Regards,

a.

**Comment by camelburrito** [comment]
CC @lannka @zhouyx @jridgewell

**Comment by MarkusDima** [comment]
Hi all, just an update about the issue above.
We can no longer reproduce the problem, all is working fine.
Have you fixed it?
In any case thank you!

Regards,
Marco

**Comment by jridgewell** [comment]
Not sure what the issue was, but if it's fixed great!
