### ISSUE TITLE
AmpContext should handle setting up from a context object or a nested context object. 

### ISSUE THREAD

**Issue by bradfrizzell** [ampproject/amphtml#8510]
Sometimes the setup object being used might look like 

`{"_context": {"location":...}}`

and sometimes it might look like 

{"location": ....} 

We need to handle both cases .

**Comment by adelinamart** [comment]
@bradfrizzell any updates here? Thank you.

**Comment by bradfrizzell** [comment]
I think we can close this. Currently, we handle if the setup object being passed on the name looks like 

```{"_context" : {"location":..."}}```
or 
```{"attributes": {"_context" : {"location":..."}}}```

I don't think we have any use case where we need this.
