### ISSUE TITLE
global is not defined

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#8514]
https://github.com/ampproject/amphtml/blob/master/ads/adhese.js#L59

**Comment by lannka** [comment]
@tiendt would you take a look at this? A good practice for chrome debugging.
The bug can be reproduced in your local server by visiting:
```
http://localhost:8000/examples/ads.amp.html?type=adhese
```

It's only reproducible with minified binary, so you will do 
```
gulp dist --fortesting
```
and visit
```
http://localhost:8000/serve_mode=compiled
```
to turn on minified binary in local server.

let me know if you have questions
