### ISSUE TITLE
amp-gist: fixed-height layout

### ISSUE THREAD

**Issue by levidurfee** [ampproject/amphtml#8523]
Instead of allowing any layout for `amp-gist`, the `fixed-height` layout seems to be the best option. This will prevent layout jumps.

The only real change in the code would be changing the `isLayoutSizeDefined()` call.

```javascript
/** @override */
isLayoutSupported(layout) {
    /* return isLayoutSizeDefined(layout); */
    return layout == Layout.FIXED_HEIGHT;
}
```

It would require the person adding the gist to inspect it on GitHub to find the actual height in pixels. Even though that is an extra step, it will result in a better experience for the people visiting their website.

I have the code written, updated examples, and I'm ready to create a pull request. Does anyone object to this change?

@sebastianbenz, @jpettitt, and I discussed this on my PR for [amp-by-example](https://github.com/ampproject/amp-by-example/pull/727).

/cc @aghassemi

**Comment by aghassemi** [comment]
SGTM. It is still going to be impossible to know the height in certain cases ( for instance if a gist file is `.md` or `.txt` gist rendering does width-dependent wrapping ) but for most cases where it is just code, wrapping does not happen so height is fixed. Anyway, resize takes care of the cases where given initial height was wrong. Good to force the initial height to be as close to the final height as possible anyway.
