### ISSUE TITLE
Remove bind event for amp-live-list receiving events (instead, require explicit user interaction)

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#8526]
Per: https://github.com/ampproject/amphtml/issues/7557#issuecomment-290586595

Make it so bind events aren't fired on update to amp-live-list content, but rather only on explicit user action (e.g. tapping the `update` button)

/cc @choumx

**Comment by choumx** [comment]
My mistake, the PR hasn't been merged yet. Closing and adding a comment on #8377.
