### ISSUE TITLE
Add a unit test for visibility trigger when the element is initially in viewport

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#8534]

**Comment by lannka** [comment]
will work on test after we cleaned up visibility v2 code and fully migrated to v3.

**Comment by rudygalfi** [comment]
@lannka To check if test exists. If so, close this. Otherwise, we will consider for next sprint.

**Comment by lannka** [comment]
@dvoytenko I don't find the test you mentioned in the meeting (was looking at test-visibility-manager.js). Could you confirm?

**Comment by dvoytenko** [comment]
I believe this test covers it: https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/test/test-visibility-manager.js#L479

And there are couple other tests that probe the same.
