### ISSUE TITLE
Amp Ads, Teads not loading when DOM is loaded.

### ISSUE THREAD

**Issue by arunchaitanyagyan** [ampproject/amphtml#8544]
I am working on Amp-ads , and i am using 

`<amp-ad
	width="300"
	height="1"
	type="teads"
	data-pid="{your pid here}">
</amp-ad>`

I figured out that, when i am using the above code directly in my php files, amp ad is rendering.

But then i am using the code via javascript or php DOM to add it in content,my Amp ads not rendering every time.

If i hard reload for 5 to 10 time, i am able to see 1 time hardly.

Process which i do while using the PHP DOM:

1. I have wp content for a post.
2. I am checking 6th paragraph of the content.
3. Appending the amp ad after the 6th paragraph using php DOM.
4. Link -> http://php.net/manual/en/domnode.insertbefore.php

Issues i am facing :-

1. Unable to load amp ad every time.
2. No console errors.
3. For 5 to 10 hard reload, i can see only one time.

I am new to AMP ADS, Can anyone tell me why it's happening.

**Comment by jasti** [comment]
@arunchaitanyagyan I'd recommend getting in touch with Teads support directly about this issue.
