### ISSUE TITLE
Relaxing no-same-origin-iframes restriction

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#8545]
AMP doesn't allow embedding iframes that are on the same origin as the document. 

This was done to prevent the risk of pages accidentally relying on the same-origin-ness, because the iframe would **not** be on the same origin when served from the cache.

There are, however, some downsides

- Some ads stuff is using `localStorage` on the publisher domain, and they typically want their access to their primary domain.
- This has led some to publish their AMP docs on an `amp.` sub domain, so they can load iframes from `www.`.

It should be noted that the `non-same-originness` is not a security feature. AMP only checks the very first URL. Pages can just redirect back to the same origin to circumvent the check. Again, this was done to prevent accidental mistakes, not as a security measure.

We actually allow same-origin when the `allow-same-origin` sandbox permission is **not** requested. However, this permission is needed for any reasonable page, since it is requires to have access to storage and Ajax requests.

I still consider the risk of accidental breakage as pretty high when allowing same origin access, but the `amp.` thing really sucks.  I wonder if

- we should just give up and allow same origin access.
- there is some other way how we could make the boundary hard. E.g. by convincing @mikewest to add `allow-same-origin-but-no-access-to-parent` (which I think what most people think would be the default for sandbox).

CC @pbakaus

**Comment by mikewest** [comment]
Based on the description in the issue, it's not at all clear to me what you're asking for in `allow-same-origin-but-no-access-to-parent`? What's the threat you're aiming to mitigate?

**Comment by mikewest** [comment]
(This is probably because I'm ignorant of the whole context. :) )

**Comment by cramforce** [comment]
@mikewest I think a pretty common invariant we and others would like to maintain is: 

> This iframe cannot mess with my DOM.

The current way to do this is to not grant `allow-same-origin`, but not giving that permission breaks all reasonable usage of `fetch`, storage access, etc. I've never seen a non-trivial iframe working without `allow-same-origin`.

**Comment by mikewest** [comment]
By "mess with my DOM", do you mean literally only that the child frame shouldn't be able to reach into the parent and poke at its DOM? Or do you want something more robust that would kill access to things like `window.parent.location`?

In other words, do you need something that would null out the `window.parent` reference entirely (what about `ancestorOrigins`, etc?), or would it be enough to do something that pretended that the windows weren't same-origin (similar to the behavior you'd get if one side set `document.domain` and the other didn't)?

**Comment by cramforce** [comment]
I think both options would work for me, but the second would be enough (Since `parent.location` is covered by other mechanisms).

**Comment by src-code** [comment]
👍  I've also noticed that `amp-iframe` won't honor `embed-size` messages received from same-origin content, which is frustrating... 

https://output.jsbin.com/repeqaf/

I'll open an issue to track this separately.
