### ISSUE TITLE
AdSense getAdUrl test failure at master

### ISSUE THREAD

**Issue by taymonbeal** [ampproject/amphtml#8558]
Example: https://travis-ci.org/ampproject/amphtml/builds/218181006

This has been affecting Travis builds at master for a while.

@ampproject/a4a

**Comment by zhouyx** [comment]
@taymonbeal The test is still failing locally. See #8602.

**Comment by taymonbeal** [comment]
#8602 appears to be unrelated to this issue. I will continue to investigate that bug.
