### ISSUE TITLE
AMP Directory & Conversion Tool

### ISSUE THREAD

**Issue by niutech** [ampproject/amphtml#858]
Is there a directory of Accelerated Mobile Pages, like [SpecificFeeds](http://www.specificfeeds.com) for RSS feeds? And is there a tool to convert HTML pages to AMP format, like [Feed43](http://feed43.com/) for HTML to RSS?

If not, are there any plans to do so?

**Comment by cramforce** [comment]
There is no directory and no plans to do that. AMP pages are just part of the open web.

With respect to conversion: Transcoding entire pages is a non-goal. What would be super helpful and nice is an independent tool that takes pure content HTML fragments (basically just text, images and video; the logical body of a web page) and turns them into AMP HTML which could then be put into an AMP specific header and footer.

The above is needed by many CMS systems. Wordpress is currently working on something like that, but it would be super nice to have as an independent reusable tool.

**Comment by niutech** [comment]
I think I can do that, but it would be much better combined with something like [Readability](https://github.com/mozilla/readability).

**Comment by olaes** [comment]
This actually needs to happen.  John Mueller has stated that using the AMP format should be a simple process much like adding an RSS feed or loading a 3rd party plugin for conventional CMS platforms.  If an AMP conversion tool isn't available, many enterprise-sized websites consisting of hundreds of thousands of pages cannot simply convert all of their pages into this new AMP format.

**Comment by ryanwarrender** [comment]
Any updates on a tool that can convert pages to AMP format in bulk?
