### ISSUE TITLE
What think about `amp-syntax` for syntax highlighting

### ISSUE THREAD

**Issue by techhtml** [ampproject/amphtml#8580]
I used AMP for my technical blogs but AMP does not have any syntax highlighter.
So i think if AMP will have syntax highlighter, it'll helpful for blogs.

**Comment by aghassemi** [comment]
Hi @techhtml,

There are a few options available for you:

1. You can do server-side syntax highlighting. https://ampstart.com and https://ampbyexample.com are both valid AMP websites and they use https://www.npmjs.com/package/highlights to do server-side syntax hightlighting. You can checkout their open-source repos on https://github.com/ampproject to see how they have integrated it.
2. You can use the newly created (still experimental) `amp-gist` to embed code from Github Gist (which has builtin syntax highlighting)

Hope this helps.

**Comment by techhtml** [comment]
I think i can use `amp-gist` for my job.
my blogs are serviced `github.io` and than `amp-gist` will helpful.

i'll use `amp-gist` and or `amp-iframe` for codepen.
Thanks!
