### ISSUE TITLE
Taboola throws error on type others

### ISSUE THREAD

**Issue by michaeld79** [ampproject/amphtml#8585]
## How do we reproduce the issue?
the taboola script does not support type "others" it supports "other" so when using data-other the taboola widget is not rendering. 
and returning an error other is not supported
[http://jsbin.com/zegafun/edit?html,output](http://jsbin.com/zegafun/edit?html,output)
reproduction is in the url or just use : 

`<amp-embed width=100 height=283
             type=taboola
             layout=responsive
             heights="(min-width:1907px) 39%, (min-width:1200px) 46%, (min-width:780px) 64%, (min-width:480px) 98%, (min-width:460px) 167%, 196%"
             data-publisher="amp-demo"
             data-mode="thumbnails-a"
             data-placement="Ads Example"
             data-other="auto">
  </amp-embed>`

## What browsers are affected?
All browsers affected

## Which AMP version is affected?
all versions affected.
this configuration was not used by anyone up till now that is why the issue surfaced

a fix was already submitted as a pull request a simple typo 
[https://github.com/ampproject/amphtml/pull/8308](https://github.com/ampproject/amphtml/pull/8308)

**Comment by michaeld79** [comment]
hi @zhouyx, i see you were assigned the issue. 

My name is Michael Dragatski and i work at Taboola.
i opened the issue because we have a client that is waiting for a fix that i caused by a typo in the taboola code in amp. as you can see from the pull request i added its not a logical bug just a single letter typo. 

i see that test fail on my branch and master is failing too, i was wondering if this is the reason why the fix is not merged? i so can you recommend of how to move forward on this issue ? 

thanks, 
michael dragatski

**Comment by zhouyx** [comment]
@michaeld79 I restarted travis build, the failing seems not related to your PR. Don't worry, I'll merge the PR once it is good.

**Comment by zhouyx** [comment]
closed by #8744
