### ISSUE TITLE
amp-gist shows error on "View Raw" link

### ISSUE THREAD

**Issue by rowan-m** [ampproject/amphtml#8587]
As shown on https://ampbyexample.com/components/amp-gist/ the initial Gist will display, but tapping the "View Raw" link results in a blank frame and the following errors:
```
(index):1 Refused to display 'https://gist.githubusercontent.com/levidurfee/b9bb35bc68df68259af94430f012425f/raw/d86044061fdd3b7db8b3ad51ff7ee52bc1970728/hello-world.html' in a frame because it set 'X-Frame-Options' to 'deny'.
gist.githubusercontent.com/levidurfee/b9bb35bc68df68259af94430f012425f/raw/d86044061fdd3b7db8b3ad51ff7ee52bc1970728/hello-world.html:1
GET https://gist.githubusercontent.com/levidurfee/b9bb35bc68df68259af94430f012425f/raw/d86044061fdd3b7db8b3ad51ff7ee52bc1970728/hello-world.html net::ERR_BLOCKED_BY_RESPONSE
```

## How do we reproduce the issue?

Please post a public URL and ideally post a reduced test case. E.g. on jsbin.com that exhibits only your issue and nothing else.
https://ampbyexample.com/components/amp-gist/

## What browsers are affected?
Looks like all browsers, tried Chrome on desktop, Samsung browser on mobile.

## Which AMP version is affected?
1491265141460

**Comment by sebastianbenz** [comment]
//cc @levidurfee

**Comment by levidurfee** [comment]
Thanks! I'll look into it later today.

**Comment by levidurfee** [comment]
@rowan-m thank you for your help! 

The default behavior of that link changes the page you are on. That doesn't seem ideal for this situation, we don't want people loading other pages in the iframe, so I think it might be best to have that link (and the two others) open in a new tab.

Would this be an acceptable solution?

**Comment by levidurfee** [comment]
Hi @rowan-m , I went ahead and created a pull request (#8603) that fixes this issue. 

When you have time, if you could please let us know if this is acceptable or not :)

Thanks again!
