### ISSUE TITLE
Dynamically insert content into anchor href on click

### ISSUE THREAD

**Issue by rajkumarsrk** [ampproject/amphtml#8594]
## Short description of your issue:
Dynamically insert content into anchor href on click

## How do we reproduce the issue?
IOS safari doesn't allow third part cookies to get set and because of this we are not able to stitch the session and get clear metrics on the source attribution & bounce rate. 

1. Visit https://www.google.com/amp/m.ebay.com/sch/amp/Digital-Cameras/31388/bn_779/i.html on IOS safari
2. Tracking call will be made on this page with endpoint "pulsar.ebay.com". This call takes care of setting the GUID on ebay.com domain. But in IOS safari this doesn't happen

## What browsers are affected?
IOS safari

## Which AMP version is affected?
It always broken

## Suggestion to fix the issue
Provide a way to attach dynamic content to anchor href click this can include 2 types of values

1. Static value that need to be appended to the URL like `_trksid=p2376289.m4213.l8401` 
2. Dynamic data like `gclinetId=CLIENT_ID` which would be the google client id

Prototype: https://s.codepen.io/boomerang/iFrameKey-ab729c71-f09f-b030-3156-c3b527089abc/index.html 
CodePen: https://codepen.io/rajkumarsrk/pen/GWxyoq

**Comment by rudygalfi** [comment]
Thanks for filing this issue based on our in-person discussion. Let me see if I can recall the context properly.

The types of substitutions you want to do are already possible in AMP. Specifically:
- Static data can just be appended as part of the href, i.e. `href="http://ebay.com/sch/Canon-Digital-Cameras/31388/bn_740/i.html?_trksid=p2376289.m4213.l8401"`
- Dynamic data liked CLIENT_ID can be handled via [link substitutions](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#variable-substitution-in-links), i.e. `href="http://ebay.com/sch/Canon-Digital-Cameras/31388/bn_740/i.html?gclinetId=CLIENT_ID"`

But, what's being requested here is a way to keep the href itself clean and just to do these kinds of attachments of content to the URL on the fly. Can you remind me of the motivation here? Was it to keep anchor links for sanitized for SEO or other reasons?

I'd like to loop in @cramforce here for feedback

**Comment by rajkumarsrk** [comment]
Yup for SEO reason we would like have the URL without these values

**Comment by cramforce** [comment]
That makes some sense to me. Something like `data-dynamic-params="id=CLIENT_ID(foo)"` would work.

@rajkumarsrk Would you be up for implementing? Should be a straight forward change somewhere here https://github.com/ampproject/amphtml/blob/master/src/service/url-replacements-impl.js#L787

**Comment by rajkumarsrk** [comment]
@cramforce Sure. I can take it up.

**Comment by rudygalfi** [comment]
@rajkumarsrk Can you provide any updates on this?

**Comment by rajkumarsrk** [comment]
@rudygalfi I should be able to send PR by tomorrow

**Comment by rajkumarsrk** [comment]
@rudygalfi The PR is available for review https://github.com/ampproject/amphtml/pull/9086
