### ISSUE TITLE
Hook up closure compiler

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#86]
Step 1: Get things to compile
Step 2: Use it for codegen. In particular for ES6 to ES(3) compilation.

**Comment by cramforce** [comment]
Well Step 2 is kinda still pending. Also need to use it for all compilation targets. Currently only hooked it up for amp.js.

**Comment by jridgewell** [comment]
If we're changing to closure to eliminate the browserify bloat, might I suggest using [rollup](http://rollupjs.org/) instead?

**Comment by erwinmombay** [comment]
yeah, rollup would be great to check out just to see the difference.

**Comment by cramforce** [comment]
It is worth a try if not too much work. We also want type checking, DCE,
etc.

The code rollup generates looks pretty good.
