### ISSUE TITLE
Handle `.amp-form-submitting [submitting]` elements the same as submit-success

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#8601]
It looks like a bug that [`.amp-form-submit-success [submit-success]` and `.amp-form-submit-error [submit-error]`](https://github.com/cvializ/amphtml/blame/master/extensions/amp-form/0.1/amp-form.css#L17) are hidden until the form encounters those states, but `.amp-form-submitting [submitting]` is not present in the `amp-form.css`. I believe this was unintentional and the submitting state should be handled the same as the success and error states.

**Comment by machadoug** [comment]
It looks like `form [submitting]` is also missing from [amp.css](https://github.com/ampproject/amphtml/blob/master/css/amp.css#L554).
