### ISSUE TITLE
AMP-access: URI components not encoded

### ISSUE THREAD

**Issue by Si0n** [ampproject/amphtml#8605]
## Short description of your issue:

The URI on login-sign-in AND login-sign-out have not encoded parameters which cause a problem:
![Error](https://i.gyazo.com/aba4fbe991bf3aff4b5e497dded21d0f.png)

![My settings for amp-access](https://i.gyazo.com/ea764682529030f400dfddb669da7a57.png)
`
    {
        "authorization": "https://f.home/amp-authorization/?rid=READER_ID&url=CANONICAL_URL&ref=DOCUMENT_REFERRER&_=RANDOM",
        "pingback": "https://f.home/amp-pingback/?rid=READER_ID&url=CANONICAL_URL&ref=DOCUMENT_REFERRER&_=RANDOM",
        "login": {
            "sign-in": "https://f.home/amp-sign-in/?rid=READER_ID&url=CANONICAL_URL",
            "sign-out": "https://f.home/amp-sign-out"
        },
        "authorizationFallbackResponse": {
            "error": true,
            "access": false
        }
    }`
>Also site is on my localhost
## How do we reproduce the issue?

1. Include amp-element **amp-access** on the page
2. Add settings as on the screenshot above
3. Buttons HTML : ![buttons](https://i.gyazo.com/ca5a8554c4b86f15296bf247714cbfbb.png)
4. Tap on a button

## What browsers are affected?
Tried on Chrome and Firefox. Broken for both.

## Which AMP version is affected?

> Powered by AMP ⚡ HTML – Version 1490899213109

## Is this a new issue? Or was it always broken? 
IDK, i have this problem from the beginning

**Comment by dvoytenko** [comment]
@Si0n AMP certainly encodes all query parameters including `url` and `return`. My best guess right now that somehow your server might redirect to the URL with unescaped values? If you could expose your demo pages somewhere where I can access them, I should be able to pinpoint the issue better.

**Comment by Si0n** [comment]
@dvoytenko https://e69c6e21.ngrok.io/amp here is my local site and example how to access sign-in/out buttons: https://i.gyazo.com/d74d79d97d1eb48bbc0a36d7f99a7a88.mp4

**Comment by Si0n** [comment]
@dvoytenko I can give you access via ngrok or can add your ip to allowed IP's on our development server

**Comment by dvoytenko** [comment]
@Si0n Yeah, ngrok would do.

**Comment by Si0n** [comment]
@dvoytenko 
Here it is https://ab735780.ngrok.io/amp and the path to acces login buttons on the video: https://i.gyazo.com/ff960104718c8a7fbc4adb590efdecd0.mp4 .

**Comment by Si0n** [comment]
Found the problem, it wasn't about the amp-access. Anyway thanks for answer.
