### ISSUE TITLE
Intent to implement: video-interface and autoplay for amp-brid-player.

### ISSUE THREAD

**Issue by DarXector** [ampproject/amphtml#8611]
The [video-interface](https://github.com/ampproject/amphtml/blob/master/src/video-interface.js) is a common API that AMP expects all video players to implement. This allows AMP to treat all video players the same and to use it to provide common UX across players such as autoplay, dockable videos, managing playback across players, etc...

The interface is fairly straightforward: common methods and events such as play, pause, mute, etc..

Should be similar to `amp-youtube`. 

It has mostly been implemented:
https://github.com/DarXector/amphtml/tree/master/extensions/amp-brid-player
Fixing tests right now.

**Comment by aghassemi** [comment]
Awesome! Thanks. Please CC me on the PR.

**Comment by aghassemi** [comment]
Closed by https://github.com/ampproject/amphtml/pull/8632
