### ISSUE TITLE
Registered/expected services should never resolve `null` from any of the methods

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#8616]
This appears to affect the following methods in service.js:
- `getServicePromiseOrNullInternal`
- `getExistingServiceForWindowOrNull`
- `getLocalExistingServiceForEmbedWinOrNull`
- might be more

And, of course, all methods that call them.

The bottom line: there's only one distinction: whether the service is registered/expected-to-be-registered or not. Initialization state should not matter.

Related to #7839.

**Comment by choumx** [comment]
Which services are affected by this?

**Comment by dvoytenko** [comment]
So far, the critical issue is only with performance. So I will drop this to P1. Some smaller issues with other services, but not as urgent.
