### ISSUE TITLE
A4A test "returns the right URL" is undebuggable

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#8635]
Lets rewrite it to not use a huge URL regex that gives no indication for what is wrong on failure. For now I will delete the test. See below for PR.

**Comment by keithwrightbos** [comment]
Will break into separate regexps for each parameter to test

**Comment by jasti** [comment]
@keithwrightbos What's the status on this? Can this be closed?

**Comment by glevitzky** [comment]
I think this is safe to close.
