### ISSUE TITLE
FR: dropdown menu with both hover and click support

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#8641]
Tracking bug for the support described in https://github.com/ampproject/amphtml/issues/7922#issuecomment-285734315, though not with amp-bind

/cc @camelburrito @aghassemi

**Comment by aghassemi** [comment]
related: https://github.com/ampproject/amphtml/issues/12619

**Comment by aghassemi** [comment]
actually let's dedup with #12619, menu is big part of #12619
