### ISSUE TITLE
amp-bind: Support e-commerce XHR use case

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#8648]
A common pattern on e-commerce sites is to perform XHRs when the user selects a SKU to fetch additional data.

/cc @ericlindley-g

**Comment by choumx** [comment]
I can imagine a few ways this can be done:

1. Use a hidden form to perform the XHR and `amp-bind` to set its inputs. Then, use an action chain e.g. `on="tap:AMP.setState({selection: event.targetOption}), myHiddenForm.submit`. This is more flexible but requires *changing actions to wait for previous actions to complete* (#8678). 

2. Allow binding to the `src` attribute of `<amp-state>`, e.g. `<amp-state [src]="'https://data.com/products?color=' + selectedColor + '&size=' + selectedSize">`. Applying a `[src]` binding triggers the XHR. This is less flexible than (1) since XHR data is merged under the `id` of the element and a little more confusing since `<amp-state>` has only been used to initialize data so far (rather than dynamically fetch multiple remote data).

3. Add a new action `AMP.fetchState()`, e.g. `on="select:AMP.fetchState(<url_expression>, <variable_path>)"`. This will cause a lot of duplication of the data URL.

IMO, (2) seems to be the nicest and consistent with our current planned solution for server-side sorting/filtering: https://github.com/ampproject/amphtml/issues/8368#issuecomment-291588864.

/cc @dvoytenko @aghassemi

**Comment by aghassemi** [comment]
I also like (2). We probably also need a `ampState.refresh()` action in cases where dev wants to refresh data but `src` does not change.
