### ISSUE TITLE
amp-bind error getDynamicElementContainers

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#8653]
When loading [product sample](https://ampbyexample.com/samples_templates/product/preview/)
I get:
bind-impl.js:399 Uncaught (in promise) TypeError: Cannot read property 'getDynamicElementContainers' of null
    at e (bind-impl.js:399)
    at bf.c [as oc] (bind-impl.js:440)
    at cf (chunk.js:179)
    at Ze.Gd (chunk.js:393)
    at chunk.js:408
e @ bind-impl.js:399
c @ bind-impl.js:440
cf @ chunk.js:179
Ze.Gd @ chunk.js:393
(anonymous) @ chunk.js:408

This doesn't always happens though.

@choumx @ericlindley-g

**Comment by choumx** [comment]
I think this is a dupe of #8647. /to @kmh287

**Comment by kmh287** [comment]
Yes, I think this is a duplicate. I'll have a PR out for this soon.

**Comment by kul3r4** [comment]
Thanks!

**Comment by kmh287** [comment]
Fixed by #8661

**Comment by ericlindley-g** [comment]
@kmh287  —  do you know if this is in canary?
