### ISSUE TITLE
Fire viewportCallback when document becomes invisible

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#866]
and the other way around.

The `viewer` object knows about document visibility (including iframes that are hidden). We need to combine that knowledge with whatever is firing viewportCallback.

CC @dvoytenko

**Comment by dvoytenko** [comment]
It should do so today - if not it must be a bug. I'll take a look. It also should fire `documentBecameInactive` callback.

**Comment by cramforce** [comment]
Nice. Didn't check!
