### ISSUE TITLE
amp-instagram embed header set to visibility:hidden.

### ISSUE THREAD

**Issue by threesided** [ampproject/amphtml#8688]
## Issue:

Some recent update to the `amp-instagram` extension has resulted in the embed header being hidden by default. 

## Short description of your issue:

Start by deleting everything above this including this sentence :)

## How do we reproduce the issue?
You can see it happening on your amp by example page: 

![screen shot 2017-04-10 at 4 49 16 pm](https://cloud.githubusercontent.com/assets/962344/24887033/ecf2a87c-1e0d-11e7-9192-4d3b486a2a28.png)

## What browsers are affected?

All browsers

## Which AMP version is affected?
This is a brand new issue as of whatever the most recent release is (as of April 10, 2017)

**Comment by levidurfee** [comment]
Thanks @threesided :)

I'll take a look at it.

**Comment by levidurfee** [comment]
It actually appears to be an issue with Instagram and not the AMP component.

If you look at [Instagram's Embedding](https://www.instagram.com/developer/embedding/) docs, you'll see it is also missing the header.

![screen shot 2017-04-10 at 9 19 55 pm](https://cloud.githubusercontent.com/assets/10798199/24888752/7b4f7256-1e33-11e7-8095-a65f8dedbbbf.png)

I'll see if I can get a response from them.

**Comment by levidurfee** [comment]
@threesided it appears this has been resolved by Instagram.

## Instagram page

![image](https://cloud.githubusercontent.com/assets/10798199/24929816/5316d688-1ed5-11e7-8dfb-4805b09cecf7.png)

## AMP By Example page

![image](https://cloud.githubusercontent.com/assets/10798199/24929808/489ddb02-1ed5-11e7-8e15-b0769b5f16c4.png)

Can you confirm you are no longer seeing this issue?

**Comment by levidurfee** [comment]
Hi @threesided , are you still having this issue?

**Comment by adelinamart** [comment]
Please reopen if the issue continues. Thanks.
