### ISSUE TITLE
For Google Amp-analytics events not captured in report if eventValue is string

### ISSUE THREAD

**Issue by jalajc** [ampproject/amphtml#8692]
## Observation: When eventValue is string Google Analytics doesn't show that event in reports 
Even though the network tabs display that analytics _collect_ ping is sent and is successful(200 OK), this event is not visible in Google analytics report.

On the same Google Analytics config, _scroll event_ which sends integer values is immediately visible in Google Analytics dashboard. _Social Interactions_ works fine too!

PS: I have also added some _custom dimensions_ for AMP. But they are all same for other triggers such as social, pageview and event.

## How do we reproduce the issue?
Aptly modified samples from [Adding Analytics to your AMP pages](https://developers.google.com/analytics/devguides/collection/amp-analytics/)
specifically at [outbound link tracking section](https://developers.google.com/analytics/devguides/collection/amp-analytics/#outbound_link_tracking)

**Comment by jalajc** [comment]
I discovered two conflicting documentation in this regard

- [Generic Analytics documentation-eventValue](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#eventValue)

> Field Name | Protocol Parameter | Value Type | Default Value | Max Length | Supported Hit Types
> **eventValue** | ev | **integer** | None | None | event

- [AMP Specific Analytics documentation-eventValue](https://developers.google.com/analytics/devguides/collection/amp-analytics/#event_tracking)

> Value | Type | Required | Description
> **eventValue** | **string** | no | **A numeric value associated with the event (e.g. 42). Defaults to 0.**
with string sample demonstrated [here](https://developers.google.com/analytics/devguides/collection/amp-analytics/#outbound_link_tracking)

**Comment by kschmidtdev** [comment]
You are correct, `eventValue` is an `integer` according to GA, so the amp-analytics docs and sample code need to be updated.

**Comment by joshcp** [comment]
Thanks @kschmidtdev for suggesting the use of `eventLabel` as a workaround for now.

**Comment by rudygalfi** [comment]
cc @avimehta

**Comment by bpaduch** [comment]
Docs corrected at https://developers.google.com/analytics/devguides/collection/amp-analytics/.
