### ISSUE TITLE
AMP-Filter

### ISSUE THREAD

**Issue by imparvez** [ampproject/amphtml#8693]
Hi All,

I have been using AMP for a long time now and there is one feature which I feel is missing is **Filter** in AMP pages.

So, I am requesting to AMP developers for a new feature which can filter out the relevant information from the long list of items.

## How it will work?
An AMP pages consisting the long list of items, which can become frustrating for the user to keep on scrolling.
What AMP-Filter can do is providing one search box which can show items from the long list based on the search box input.

For reference, we can use something like ngFilter's functionality in AngularJS.

**Comment by aghassemi** [comment]
@imparvez we are actually in the design phase for supporting sort/filter/pagination use-cases in AMP. Client-side and server-side approaches are fairly different so we are tracking them under different issues.

Please subscribe to https://github.com/ampproject/amphtml/issues/8368 for client-side filter support and to https://github.com/ampproject/amphtml/issues/6054 for server-side support.

Design doc for `amp-filter` (client-side) is coming out next week, I will make sure to CC you. We would love to get your feedback.

**Comment by imparvez** [comment]
Sure @aghassemi I would love to provide a feedback and looking forward to your email.
