### ISSUE TITLE
amp-ad: smartadserver plugin doesn't check if the server return empty banner or not

### ISSUE THREAD

**Issue by jansete** [ampproject/amphtml#8695]
SmartAdServer plugin doesn't checkif the server return empty banner or not

## Context
https://github.com/ampproject/amphtml/blob/master/ads/smartadserver.js doesn't use global.context.noContentAvailable();

The problem is if the server doesn't give us any advert we can't hide it or use any fallback.

## How do we reproduce the issue?
Using amp-ad with smartadserver type, if the format doesn't have any adverts.

**Comment by jasti** [comment]
@GoldenCrystal thoughts on supporting? 
Also, could you support render start if you haven't already? Thanks.

**Comment by GoldenCrystal** [comment]
Hello,

I confirmed that this is a regression on our side.
It will be fixed during our next deployment.

**Comment by gitfriend1** [comment]
what do about it

**Comment by jasti** [comment]
Closing since the issue seems to be on the smart ad server side. Please reopen if the issue persists.
