### ISSUE TITLE
TypeError: window.stop_youtube is not a function

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#8699]
A very common error:
```
TypeError: window.stop_youtube is not a function
    at <anonymous>:1:8
```

A sample page: https://amp-ibtimes-co-uk.cdn.ampproject.org/c/s/amp.ibtimes.co.uk/caitlyn-jenner-opens-about-guilty-oj-simpson-reasons-gender-reassignment-surgery-1616573

**Comment by aghassemi** [comment]
@dvoytenko Have you been able to repo the error locally? (I can't) @cramforce believes this error comes from a Chrome extension.

**Comment by dvoytenko** [comment]
I see it primarily on Android so extension seems unlikely. And, yes, it's not reproduceably easily.

**Comment by cramforce** [comment]
Do you have a UA string? Sure it isn't firefox?

How could this be anything but a browser extension?

**Comment by dvoytenko** [comment]
The most common user agent is:
```
Mozilla/5.0 (Linux; Android 4.4.2) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36
```

Not sure if we rethrow any errors from YouTube, e.g. via postMessage.

**Comment by aghassemi** [comment]
They all seem to be Chrome 30 too. Honestly my bet is that the error is coming from Chromecast related integration in old Chrome

**Comment by dvoytenko** [comment]
Ok. I'll drop to P3 and monitor it a bit more.
