### ISSUE TITLE
Improvements to preconnect

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#870]
- Add a method that elements can use to register what they **connected** to, so we don't preconnect after
- If we connected, don't preconnect ever again
- Let preconnects expire after 5s (Confirm)
- Move all preconnects into `BaseElement.preconnectCallback`
  - This should be called only when the doc is/becomes visible.
  - Should be called just after layoutCallback to parallelize requests.
- Once we support sharing the runtime across frames: Make preconnect a per-browser singleton.

Consider special casing preconnects to hosts that do not support HTTP2. At this point this likely only supplies to some ad networks.

**Comment by igrigorik** [comment]
> Move all preconnects into BaseElement.preconnectCallback
> - This should be called only when the doc is/becomes visible.
> - Should be called just after layoutCallback to parallelize requests.

Why do you want to defer preconnects until visible? If the page is being prerendered it still makes sense to preconnect early to accelerate the prerender itself. Also, not sure what you mean here by 'parallelize requests'?

> Once we support sharing the runtime across frames: Make preconnect a per-browser singleton.

I think you get this for free? All modern browsers maintain their own socket pools that are independent (modulo some corner cases on client auth) of any particular renderer (e.g. chrome://net-internals#sockets).

> Let preconnects expire after 5s

This is a bit more complicated than I indicated earlier.. digging up more data, stay tuned.

**Comment by cramforce** [comment]
@igrigorik Most of the above was in the context of there being a timeout for preconnect. If there is not we can keep having a simpler solution.

With "parallelize requests" what I mean is that, in particular for ads (but also for but also for tweets) we see a deep request waterfall. Since host names are predictable we try to preconnect concurrently, so that some of the costs of the waterfall gets amortized. Pretty standard.

One thing that happens often in AMP is that we lazy load some component. We preconnect (and prefetch) eagerly, but the actual load might be much later. That is why knowing the timeouts is important. If a preconnect might have timed out we should again preconnect to hosts deeper in the waterfall after issuing the real connect.

**Comment by igrigorik** [comment]
> One thing that happens often in AMP is that we lazy load some component. We preconnect (and prefetch) eagerly, but the actual load might be much later. That is why knowing the timeouts is important. If a preconnect might have timed out we should again preconnect to hosts deeper in the waterfall after issuing the real connect.

Right, makes sense. Here's the logic we have in Chrome (can't speak for other browsers.. /cc @mcmanus):

1. Unused socket timeout is [set to 10s](https://code.google.com/p/chromium/codesearch#chromium/src/net/socket/client_socket_pool.cc&q=unused%20file:%5Esrc/net/socket/&sq=package:chromium&type=cs&l=15)
1. Once socket is 'used' the timeout is [bumped to 300s](https://code.google.com/p/chromium/codesearch#chromium/src/net/socket/client_socket_pool.cc&q=unused%20file:%5Esrc/net/socket/&sq=package:chromium&type=cs&l=18)

(1) applies regardless of protocol and the one you care about most here.. 10s is a fairly short lifetime*, so it makes sense to combine knowledge of what's in the viewport + soon to enter to drive what you're (pre)connecting to.

_p.s. * it may well be the case that 10s is too aggressive and we might change that in the future.. if you have any data on this, let me know._
