### ISSUE TITLE
Risk condition in the ad resize code

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#8703]
A common PROD error:
```
TypeError: Cannot read property 'offsetHeight' of null
at (https://cdn.ampproject.org/rtv/001491864594241/v0/amp-ad-0.1.js:70)
at Ni (https://cdn.ampproject.org/rtv/001491864594241/v0.js:351)
at Ji.f.uf (v0.js:350)
```

Points to this line of code: https://github.com/ampproject/amphtml/blob/b38e4c973c00932a737e5ed6db7e0278a5419c8a/extensions/amp-ad/0.1/amp-ad-xorigin-iframe-handler.js#L305

It looks like a latent resize event arrives either after iframe has been destroyed or vsync arrives after iframe has been destroyed. 

If this is confirmed to be the case the simple fix would be simply to ignore mutates when iframe no longer exists.

**Comment by zhouyx** [comment]
closed by #8714
