### ISSUE TITLE
Wrong measurement in resize event in ios 10.3

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#8709]
Brought up in https://github.com/ampproject/amphtml/issues/8479
Related webkit bug: https://bugs.webkit.org/show_bug.cgi?id=170595
Figure out a way to measure the sizes correctly after resize/orientationchange event in 10.3

**Comment by muxin** [comment]
@dvoytenko I don't know which measurement methods are essential for key resource management while orientation changes. I checked `viewport.getSize()`, `viewport.getRect()`, `viewport.getScrollTop()` when orientationchange occurs and they all return the correct values. If those methods are fine, it seems that the bug is not affecting key resource management.

Strangely only `imageLightboxViewer./*OK*/getBoundingClientRect()` returns the wrong value. I still don't know under what situation ( or on what target) do we have a wrong measurement yet.

**Comment by aghassemi** [comment]
@dvoytenko So the only wrong measurement is for `block` elements that extends the full width. For us to fix this at a higher-level (like before triggering onChange) we probably need to measure `body` (or if `body` somehow reports correct values too, need a fake `div` to keep measuring). 

Moving this a level up has some cons however. It means we will delay sending `onChange` for ~500ms to **every component** although they might not have been impacted by this iOS bug at all (e.g. they are not measuring a `block` child)

**Comment by aghassemi** [comment]
I am removing this from April H1 sprint and lowering to P2 per previous comment.

**Comment by dvoytenko** [comment]
SG. I'm ok with P2. But one thing to confirm. Is this possible due to iOS issue on resize/orientationchange, that an AMP element (e.g. amp-img or amp-video) would be measured incorrectly by the scheduler pass?

**Comment by muxin** [comment]
I tested `amp-img` on ios 10.3 upon orientation change. The `layoutbox_` of `amp-img` is accurate.
