### ISSUE TITLE
amp-bind: [class] verification in dev mode broken

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#8716]
http://stackoverflow.com/questions/43331218/amp-bind-error-default-value-for-variable-does-not-match-first-expression-res

**Comment by croban** [comment]
Is this really fixed because I still get:
error.js:173 amp-bind: Default value for [class] does not match first expression result (container lageplan-1). This can result in unexpected behavior after the next state change.​​​

`<amp-state id="lageplanState">
        <script type="application/json">
        {
            "selected": "container lageplan-1"
        }
    </script>
    </amp-state>

    <div [class]="lageplanState.selected">...</div>`
