### ISSUE TITLE
amp-bind: Print state to console for debugging

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#8719]
Top-level `AMP.printState()` with a pretty-print of current state would be useful for debugging. Should handle circular references gracefully.

**Comment by kmh287** [comment]
How about something like this?: 

```js
function prettyPrint(x) {
  const seen = [];
  return JSON.stringify(x, function(key, value) {
    if (isObject(value)) {
      if (seen.includes(value)) {
        return 'Circular Reference...'
      } else {
        seen.push(value);
      }
    }
    return value;
  });
}
```
Granted, it doesn't provide any information about where the circular references lead.

**Comment by leonalicious** [comment]
May I know is this feature available already ?
