### ISSUE TITLE
AMP cache spec doesn't mention subdomains

### ISSUE THREAD

**Issue by src-code** [ampproject/amphtml#8733]
Currently the spec for 3rd party AMP caches makes no mention of the use of subdomains for isolating publisher origins.  It seems that Cloudflare is subdomaining in the same manner that  `cdn.ampproject.org` does, but this isn't called out explicitly in the spec, so it's not clear that future caches will use the same methodology.  Would be good to formalize this convention if it's expected to be consistent across caches.

Spec: https://github.com/ampproject/amphtml/blob/master/spec/amp-cache-guidelines.md

Blog post detailing subdomain pattern: https://developers.googleblog.com/2016/12/amp-cache-updates.html

**Comment by adelinamart** [comment]
@rudygalfi can you answer this one. Thanks.

**Comment by rudygalfi** [comment]
@cramforce Do you think we should make it a cache guideline to have subdomain separation on AMP caches?

**Comment by cramforce** [comment]
Yes!
