### ISSUE TITLE
Lightbox 2.0 — fullscreen carousel

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#8739]
piece of https://github.com/ampproject/amphtml/issues/4152

• Tap on image in carousel — goes into light-boxed version of carousel
• Includes swiping
• Does not include image-specific functionality (e.g. zoom)
• Just includes amp-img

**Comment by muxin** [comment]
Closed via https://github.com/ampproject/amphtml/pull/8865
