### ISSUE TITLE
Scroll position is not reported to ads embedded using inabox

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#8740]
Scroll-bound animation (#8411) and `amp-fx-parallax` (#1443) depend on scroll reporting.

A viewport binding exists for inabox that will request the scroll position from the top-level document. However, it was originally implemented only for observing object intersections, so it's been disabled (#6787) for cases in which a native `IntersectionObserver` can be used.

1. The position needs to be requested by the viewport binding for inabox always.
2. The top-level runtime (AMP runtime or the inabox host script) needs to send position messages only when the embed is inside the viewport.
3. The raw position is currently being parsed by the viewport binding to determine intersections. To be able to accomplish 2), we need to decouple intersection reporting from position reporting.

Ideally, when doing 3) the position reported to the frame won't reflect the real scroll position of the top-level document, but an offset range clamped to `[0..viewportHeight * 2]`.

A potential issue arises by modifying the range reported to the frame. #8708 introduces an API that 3p integrations can use to read position data. Currently, #8708 reports the raw position, so it's worth considering modifying the behavior of that API before it's enabled.

Additionally, viewport reporting in FIE would need to be modified to make the reported range match what's reported to 3p frames/inabox to ensure consistent behavior for the same embed in different host types.

/cc @zhouyx @lannka

**Comment by dvoytenko** [comment]
I still consider element position and scroll offset to be somewhat sensitive and would like to hear arguments why it's not. On the other hand, there's relatively little that the embed can do with the parent scroll info by itself - it does need to know it's relative position in viewport. So, what I suggest we explore first is the special "viewport position" (vp) value that will be reported to the embed whenever it overlaps with the viewport in any way. So, it's a sort of relative scroll coord system.

E.g. consider this:

(`o` == 100px, `-` = viewport boundary, `<-` = possible embed position)

o <- scroll pos = 0; embed vp pos = undefined
o <- scroll pos = 100; embed vp pos = undefined
-
o <- scroll pos = 200; embed vp pos = 0
o <- scroll pos = 300; embed vp pos = 100
o <- scroll pos = 400; embed vp pos = 200
o <- scroll pos = 500; embed vp pos = 300
-
o <- scroll pos = 600; embed vp pos = undefined
o <- scroll pos = 700; embed vp pos = undefined
o <- scroll pos = 800; embed vp pos = undefined

This system still needs to know the actual viewport height, which is ok. But the numbers are always relative to viewport height, so no other information is needed.

The same signal can be further used for InOb polyfill, so it'll be dual use. The only difference is sensitivity for delay. InOb is explicitly an async API and can tolerate almost any delay. While, scroll sync is near-sync. So, that might be the only extension we need to make. The embed asks for vp data and indicates the fidelity that it wants. The parent page accommodates.

**Comment by alanorozco** [comment]
@dvoytenko 

I agree that element position and scroll offset are sensitive. 

Your approach sounds good. It won't work for cases in which the integration needs to calculate behavior based on 1:1 pixel offsets. But if we're okay with that then I think that should be the way to go.

**Comment by zhouyx** [comment]
I agree that scroll offset is sensitive. How sensitive is element position to the doc? 

@dvoytenko In your example, are we sending raw scroll pos data?

**Comment by dvoytenko** [comment]
> How sensitive is element position to the doc?

Not too sensitive. It's expected that the element has a pretty good idea of what's going on in the page when it's in viewport. However, once it's out of viewport, the information stream should be restricted.

> In your example, are we sending raw scroll pos data?

In my example it's not - it's relative data. We could send the raw data, but we still need to restrict when we can send it.

**Comment by lannka** [comment]
I believe we have a solution and @zhouyx  is working right? Is this still an active tracker for that? Or we moved to somewhere else?

**Comment by lannka** [comment]
Resolved by #10813
