### ISSUE TITLE
Have scroll bound animations work for inabox 

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#8755]
For AMP ads in AMP pages and inabox cases

**Comment by jasti** [comment]
@alanorozco can you confirm status on this?

**Comment by alanorozco** [comment]
This should be working now.

**Comment by lannka** [comment]
@aghassemi do we have examples for scroll bound animations?

**Comment by aghassemi** [comment]
yes, http://localhost:8000/test/manual/amp-animation/scrollbound-embeds.amp.html which tests scrollbound animations in A4A in both FIE and 3p-fallback case.

https://ampbyexample.com/amp-ads/#amp-ads/experimental_ads has multiple scrollbound animations as well.

All of `amp-animation` (regardless of scrollbound or timebound) is still experimental however.

I am not sure if scrollbound stuff work in non-AMP hosts, `PositionObserver` is where the hook for non-AMP hosts needs to happen and then scrollbound stuff would just work. /cc @zhouyx

**Comment by zhouyx** [comment]
Would not work for non-AMP hosts at this time. @aghassemi We can sync offline sometime this week.

**Comment by zhouyx** [comment]
I rewrote the PositionObserver, so that inabox and ampdoc share the same implementation.  scroll bound animations support in inabox is added.
