### ISSUE TITLE
End allowing v0.js in validator rules for AMP4ADS html format

### ISSUE THREAD

**Issue by Gregable** [ampproject/amphtml#8765]
The current validator rules allow AMP4ADS format documents to contain either:

```<script async src="https://cdn.ampproject.org/v0.js"></script>```
-or-
```<script async src="https://cdn.ampproject.org/amp4ads-v0.js"></script>```

In the document head. We should retire the former from validator rules and allow only the latter. @lannka for making any necessary announcements.

**Comment by lannka** [comment]
I think this is obsolete, as we've already fully moved to `amp4ads-v0.js`.

**Comment by KarMurri** [comment]
Hi, i'm presenting this error on my localhost:
GET https://cdn.ampproject.org/amp4ads-v0.js net::ERR_BLOCKED_BY_CLIENT

Any guest? Am I doing something wrong?

**Comment by Gregable** [comment]
The resource is generally reachable from the internet. This looks like it would be your browser itself which is blocking the resource. Is it possible you are using some browser extension (such as an ad blocker) which is causing your browser to not request this resource?
