### ISSUE TITLE
Ensure ad request is not delayed on scroll when using amp-sticky-ad with Fast Fetch

### ISSUE THREAD

**Issue by keithwrightbos** [ampproject/amphtml#8768]
Fast Fetch enabled ad units within amp-sticky-ad elements are delaying their ad request until scroll.  Steps to reproduce:

- go to https://genius-com.cdn.ampproject.org/c/s/genius.com/amp/Ed-sheeran-shape-of-you-lyrics?#exp=a4a:2  Note that ad request is not made for slot within amp-sticky-ad element (it will contain "act" request parameter)
- scroll and request is made

Request should be made immediately and not dependent upon scroll for Fast Fetch (render should still be delayed by scrolling)

cc/ @ampproject/a4a

**Comment by zhouyx** [comment]
fixed by #8815
