### ISSUE TITLE
Create GFI - Sriram

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#8776]
As discussed, this one will be in AMPStart

**Comment by mrjoro** [comment]
Did you end up creating one in ampstart?  Should we create a Great First Issues milestone in ampstart or should we just track them here?

We want to make sure to have a variety of Great First Issues when people are interested in helping out, and there some upcoming events (like I/O) that might attract more new people.  If you haven't already, please try to get a new one in soon.

**Comment by camelburrito** [comment]
Yes i did - https://github.com/ampproject/ampstart/issues/354
