### ISSUE TITLE
Investigate possibility of duplicate triggers

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#8780]
Currently appears to be impossible. But some reports indicate that there might be occurrences.

/cc @keithwrightbos

**Comment by dvoytenko** [comment]
No duplicates this week. Will continue monitoring next week.

**Comment by rudygalfi** [comment]
@dvoytenko Do you want to keep looking at this during upcoming sprints? I think we should define some criteria for when we will close this if this is not actionable after some time and/or define some way to check to track this separately (i.e. outside GitHub sprint process).

**Comment by dvoytenko** [comment]
Ready to close
