### ISSUE TITLE
A4A: Add additional CSI pings

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#8784]
(Setting highest priority to ensure this makes the next canary)

We'd like additional pings to thoroughly investigate and understand all phases of embed instrumentation. I'd like these pings for both FIE and XOrigin cases (fast vs delayed).

Additional pings I'd like are:

1. Immediate 1% visibility ping regardless loading state: `{on: visible, visibilitySpec: {visiblePercentageMin: 1, waitFor: none}}`.
2. Immediate 1% visibility ping right after ini-load: `{on: visible, visibilitySpec: {visiblePercentageMin: 1, waitFor: ini-load}}`
3. Standard visibility filter that we apply as active view (50% + 1s?)
4. Possibly another like-standard, but for smaller %.

Among other things, I'd like to be able to estimate percentiles of "blank time" - the time between (1) and (2). That could give us insight if `ini-load` requirement is too aggressive and if it compares well with delayed case.

**Comment by dvoytenko** [comment]
The sample of how to use the visibility API can be found [here](https://github.com/ampproject/amphtml/pull/8788/files#diff-ba655557663735d2bb090f707f986bcc). It's somewhat manual, but also pretty extensible.

**Comment by keithwrightbos** [comment]
Re-assigning to @bradfrizzell.  The requirements are for Fast Fetch AdSense and Doubleclick we need to generate CSI beacons for the following.  The idea is to use these in comparison with our AMP Analytics based CSI pings to determine possible causes of signal loss.  As such, we should make sure we can easily compare across the two different methods and that pings exist for both methods of generation (CSI and AMP analytics).  This is a full list of pings:

- first visible
- ini-load
- load
- 50% visibility w/o ini load
- 50% visibility w/ ini load
- 50% visibility w/ini load and 1 second (matches AV definition)

All to be based on AMP ad element.

@dvoytenko - is there a way we could generate pings based on iframe (load and position on screen) as opposed to enclosing AMP ad element?  This would be closer to Delayed Fetch parity.

**Comment by bradfrizzell** [comment]
cc @glevitzky

**Comment by dvoytenko** [comment]
@keithwrightbos No way to do this for iframe at this time reliably. But it'd be better if we were to do a reverse - used the same APIs against `amp-ad` for delayed case as well.

**Comment by keithwrightbos** [comment]
Meaning somehow have delayed fetch visibility integration get load of the amp ad element?  Given its outside of the creative frame, how would we do that?

**Comment by dvoytenko** [comment]
Basically, I'm asking we do the exact same thing for both: FIE and XOrigin. Just as we do for `renderStart`.

**Comment by keithwrightbos** [comment]
sure that works for me

**Comment by jridgewell** [comment]
Fixed by #8796.
