### ISSUE TITLE
Possible bug in image display in carousel

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#8793]
See here http://www.sfgate.com/aboutsfgate/amp/Boy-8-drives-sister-4-to-McDonald-s-for-a-11068868.php

![screenshot_20170414-061927](https://cloud.githubusercontent.com/assets/89679/25073675/4f3e4504-22a0-11e7-8114-82a078783f51.png)

Removing the `overflow: hidden!important` from the container fixes it. I kind of assume this is WAI, but the article CSS does something weird. But what is it?

**Comment by camelburrito** [comment]
You mean the jitter ?

**Comment by cramforce** [comment]
No, that would be a different bug. See screenshot. Only the lower right 25% of the image is shown.

**Comment by camelburrito** [comment]
Not happening on latest chrome - (or other browsers)

**Comment by camelburrito** [comment]
Closing for now, feel free to re-open if required,
