### ISSUE TITLE
amp-iframe ignores AMP postmessages from same-origin content

### ISSUE THREAD

**Issue by src-code** [ampproject/amphtml#8819]
Same-origin content may be loaded into amp-iframes if the `allow-same-origin` sandbox flag is omitted.  However, any amp messages received from the iframe will be silently ignored by amp-iframe.

Perhaps relevant to issue #8545?

## How do we reproduce the issue?

**Demo:** https://output.jsbin.com/repeqaf/

## What browsers are affected?

All

## Which AMP version is affected?

Tested with v1492014732688

**Comment by ericlindley-g** [comment]
@aghassemi ,  I'm assuming this is a bug; is that right?

**Comment by aghassemi** [comment]
@ericlindley-g @src-code Well, without `allow-same-origin` the origin of the `resize` postMessage will be `null` and the receiver will ignore it. #8545 is really the solution to this

**Comment by ericlindley-g** [comment]
Closing as dupe of #8545, but please re-open if there's something not captured there
