### ISSUE TITLE
autocomplete: list overlay (design & impl)

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#8825]
breaking down: https://github.com/ampproject/amphtml/issues/6625

As user types, results of autocomplete show up as overlay that can be navigated by keyboard arrows and tap

**UX**
How does it close? 
Width?
etc...

uses amp-list behind the scenes

Should also think about caching (if requested from same source)

**Comment by aghassemi** [comment]
We should put this on AmpByExample.com, I believe composing the following AMP components should gives us a good autocomplete sample:

-`input-debounced` event ( #9277 )
-`amp-list` to render
-`amp-selector` for selection and keyboard support
- `amp-bind` to change `src` of `amp-list` when `input-debounced` triggers.

/cc @ericlindley-g Good candidate for next sprint?

/cc @cvializ

**Comment by cvializ** [comment]
Sample code, doesn't yet work with production AMP.  Small changes need to be made to `bind-impl.js` and `action-impl.js`. Additionally, some actions and events could be added to improve UX, e.g. focus, blur.

https://gist.github.com/cvializ/fe3640d14ec7e91596aae101a97bc383

**Comment by ericlindley-g** [comment]
Agreed that this is a great ABE candidate (pending the tweaks to make it work in production). (along with—per design review discussion—encapsulating a more opinionated behavior as a separate component)

**Comment by aghassemi** [comment]
Closing. Remaining work tracked under #9698
