### ISSUE TITLE
update multiple input elements based on autocomplete selection

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#8826]
enhancement on
https://github.com/ampproject/amphtml/issues/6625

**Comment by caroqliu** [comment]
Hi there,

It's now possible to respond to an autocomplete selection by listening to the `select` event on the newly launched dedicated `amp-autocomplete` component:
https://amp.dev/documentation/examples/components/amp-autocomplete/?format=websites

I'm going to go ahead and close this issue with the recommendation that you try out the new component and set the value of multiple input elements as you normally would through AMP actions and events. Please let us know if you're experiencing any further issues. Thanks!
