### ISSUE TITLE
<amp-youtube> is not being lazy loaded

### ISSUE THREAD

**Issue by pbakaus** [ampproject/amphtml#8828]
1. Go to https://www.ampproject.org/learn/overview/#video on a Desktop resolution
2. Scroll down
3. Observe that the three little loading dots appear, but the video is not loading

Now:

1. Reload the page with the scroll position on the video
2. Observe how the video now loads correctly

Looks like there's an ugly, urgent error here.

**Comment by aghassemi** [comment]
able to reproduce. looking.

**Comment by aghassemi** [comment]
@pbakaus fixed and prod patched already thanks to @erwinmombay and @zhouyx

**Comment by pbakaus** [comment]
@aghassemi excellent, thanks!
