### ISSUE TITLE
amp-video-ima: Support support `track` children for CC

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#8836]
```
<amp-video-ima>
   <track src="subtitles_en.vtt" kind="subtitles" srclang="en" label="English">
   <track src="subtitles_no.vtt" kind="subtitles" srclang="no" label="Norwegian">
</amp-video-ima>
```
should work.

Validation rules for `<track>` also need to be updated to allow `amp-video-ima` as parent. Rules live in `validator-main.protoascii`

**Comment by adelinamart** [comment]
@aghassemi any updates here? Thanks.

**Comment by shawnbuso** [comment]
This is next on my list after #8842 since it shares a lot of similarities. Once that's reviewed I'll know best practices for handling these child elements and I can apply the same things here.
