### ISSUE TITLE
AMP ads are partially displayed before ini-load

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#8838]
Ad placeholders have a subtle transparency, which is intended. However, A4A iframes are visible under the placeholder before ini-load, which means that the partially rendered elements bleed through.

**Comment by zhouyx** [comment]
For 3p ads iframe, we make them visible after `iframeLoadPromise/RenderStart/Timeout`. Should have similar feature for friendly iframe.

**Comment by keithwrightbos** [comment]
renderStart is sent by the ad tag and could easily be triggered well before the creative is fully loaded.  The argument for currently flow is that we unhide after renderStart in A4A. We need to be careful to not delay friendly frame causing a disadvantage.

**Comment by alanorozco** [comment]
@keithwrightbos This is merely a styling issue :)

**Comment by keithwrightbos** [comment]
FYI #9056 addresses this issue

**Comment by keithwrightbos** [comment]
Fixed by #9056
