### ISSUE TITLE
amp-ima-video: Support `source`

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#8842]
```
<amp-video-ima>
  <source src="forrest_gump.mp4" type="video/mp4">
  <source src="forrest_gump.ogg" type="video/ogg">
</amp-video-ima>
```
should work.

Validation rules for <source> also need to be updated to allow amp-video-ima as parent. Rules live in validator-main.protoascii

This means `data-src` no longer needs to be required either.

**Comment by shawnbuso** [comment]
Taking a look at this one and I've got a quick question - do I have access to the amp-ima-video element in imaVideo.js? If I only have access to it in amp-ima-video.js, when is the earliest that I can send a message to the code in imaVideo.js to let it know what the potential sources are?

**Comment by aghassemi** [comment]
@shawnbuso adding/changing `<source>` later __could__ be problematic ( see comment https://github.com/ampproject/amphtml/issues/9085#issuecomment-298497385 ) so I recommend against doing it with a `postMessage`. 

We could scan the sources in `amp-ima-video`'s `buildCallback` and serialize and put them as an attribute on the element, then when you create the 3P iframe, it would have access to that attribute same it it currently accesses the other ones.
