### ISSUE TITLE
amp-ima-video: Send `AD_START` , `AD_END` events

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#8843]
For `autoplay`, currently we put a "shim" div on top of the player to capture the first click to unmute the video. This does not work well during ad play as user's clicks should go to the ad.
We need to:
- [ ] Update video-manager to listen for two new `VideoEvents.AD_START` and `VideoEvents.AD_END` events.
- [ ] Video manger to remove the "shim" between AD_START and AD_END.
- [ ] Have `amp-ima-video` send those events during ad plays.

**Comment by shawnbuso** [comment]
For the case where a user sees a pod of ads (multiple ads in a row, like a TV commercial break) should I fire AD_START at the start of the pod and END at the end of the pod, or fire those events around each individual ad?

**Comment by aghassemi** [comment]
So we would use that signal only in `autoplay` case for now to remove the transparent overlay shim so taps during the Ad play are captured by the ad itself, in that sense it doesn't really matter, either would work.

**Comment by adelinamart** [comment]
@aghassemi any updates here? Thanks.

**Comment by aghassemi** [comment]
@adelinamart all of `amp-ima-video` P1s are P1 relative to the other `amp-ima-video` tasks but not globally a P1. Wasn't really sure what the best way is to track priority of items within a bucket which itself has a different (lower) priority. Any ideas?

**Comment by adelinamart** [comment]
@aghassemi if some of the tasks are P1s we should to provide updates for those if they are not tracked in a different issues. Thanks.

**Comment by aghassemi** [comment]
@shawnbuso @adelinamart I updated `amp-ima-video` bucket of issues: p1->p2 and p2->p3

**Comment by aghassemi** [comment]
closed by #10960

**Comment by shawnbuso** [comment]
FYI this is still open, even though it was resolved by #10960

**Comment by aghassemi** [comment]
closing for realz
