### ISSUE TITLE
Amp analytics visibility selector fires only once even though selector matches multiple items

### ISSUE THREAD

**Issue by sztojka** [ampproject/amphtml#8851]
I have a list of images, and I would like to track what images were actually seen by users. I added an "element-track" class to each image, then I use the following trigger:

```
"listElementVisible": {
    "request": "event",
    "visibilitySpec": {
        "selector": ".track-element",
        "visiblePercentageMin": 20,
        "continuousTimeMin": 200,
        "totalTimeMin": 500
    },
    "on": "visible"
}
```

Even though the selector matches all the elements, it only fires when the first one is seen. In an ideal world it should fire for every matched element when each individual element is first seen.

The only workaround is to make 25 triggers when I have 25 list elements on a page, which is not really ideal.

**Comment by rudygalfi** [comment]
I think this is the same as #7654. Marking as duplicate. /cc @avimehta @lannka
