### ISSUE TITLE
Unskip amp-pixel test

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#8853]
Need to fix the amp-pixel test and unskip integration test.
related to #8597  
Please fix change from #8862, #8859 .
https://travis-ci.org/ampproject/amphtml/builds/223723995
https://travis-ci.org/ampproject/amphtml/builds/224049453

**Comment by amphtml-team** [comment]
Thx Yuxuan. Would you skip the test for now? I'll fix that ASAP when I'm in
office.
