### ISSUE TITLE
create amp-soundcloud

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#886]

**Comment by cramforce** [comment]
Shortest INTENT TO IMPLEMENT ever :)

LGTM

**Comment by asap** [comment]
Would love to implement this for The Huffington Post.

Here's how we're using Soundcloud:
http://www.huffingtonpost.com/2015/04/01/amy-van-doran-love-tips_n_6984856.html
http://www.huffingtonpost.com/2015/07/02/sex-in-outer-space_n_7713562.html
http://www.huffingtonpost.com/news/huffpost-love-and-sex-podcast/

Apologies for the nature of the content, but it makes for an interesting issue. :sunglasses:

**Comment by cramforce** [comment]
@erwinmombay How far along are you with this?

**Comment by erwinmombay** [comment]
@cramforce not too far along, but i also don't think its hard to implement, so if @asap wants to work on it feel free!

**Comment by cramforce** [comment]
@asap Do you want to take this on?

**Comment by kesla** [comment]
@asap @cramforce Hey! I'd gladly implement this!

**Comment by asap** [comment]
@cramforce @kesla was interested in implementing this too. Let me know so we don't get in eachother's way.

**Comment by rudygalfi** [comment]
@asap Since you volunteered first, why don't you go for implementing this? If you don't think you'll have time soon, then just let us know and perhaps @kesla can take this one?

**Comment by asap** [comment]
@rudygalfi I already implemented, just going through the code review process.

**Comment by rudygalfi** [comment]
Ah, I missed #1584. Thanks for the update.

**Comment by asap** [comment]
@rudygalfi. I pushed my code up earlier today and saw that the build keeps failing, but I don't think it's for anything that I'm doing. Any advice?

**Comment by rudygalfi** [comment]
@cramforce Any advice here?

**Comment by erwinmombay** [comment]
the issue was probably part of the `gulp lint` errors. looking into this with @asap in slack

**Comment by asap** [comment]
@cramforce I'm ready for inspection!

**Comment by cramforce** [comment]
Note, that #1732 needs to be fixed before this can be used.
