### ISSUE TITLE
Binding to ensure element is fully in viewport

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#8863]
There are some use cases where it would be neat to have a binding that will automatically change the scroll position of some region of the page to ensure a subelement of that region is fully visible.

Inspiration for this is an amp-carousel with thumbnails. As you swipe through the carousel, the thumbnail selection changes (awesome!). However, if you go far enough without changing the scrollable thumbnails, then eventually, the selection is only partially visible:

<img width="409" alt="screen shot 2017-04-20 at 12 51 11" src="https://cloud.githubusercontent.com/assets/3888212/25249874/5d22d90c-25c8-11e7-8e5d-1fc2ebebf222.png">

Another use case would be a page with headings and a nav on the side that changes styling as you scroll through sections. When you get to a section that's off-screen the nav area could automatically scroll so that the active section's heading is visible.

**Comment by rudygalfi** [comment]
/ to @ericlindley-g @choumx

**Comment by aghassemi** [comment]
yeah #7626 is the right solution for this.

**Comment by ericlindley-g** [comment]
Will close as dupe of #7626 — which I'm excited is getting close to launch :)

@aghassemi Can you confirm that the .focus() method addresses the use cases that @rudygalfi outlines above?

**Comment by aghassemi** [comment]
yes, I will update the codelab when it is in prod.

**Comment by ericlindley-g** [comment]
Awesome — thanks! (closing this issue)
