### ISSUE TITLE
Problem with flex settings in .carousel-slide

### ISSUE THREAD

**Issue by ChrisHoman** [ampproject/amphtml#8872]
When I set .carousel-slide to the following css, the 'align-self' is causing a problem on mobile browsers (not desktop). 
.carousel-slide {
	display: flex;
	flex-wrap: wrap;
	justify-content: space-between;
	align-self: flex-start;
	height: initial;
}

![nearme1_jpeg-1](https://cloud.githubusercontent.com/assets/2571694/25269230/a931e742-2673-11e7-8a68-823a1e65bce1.jpg)
![nearme2_jpeg-1](https://cloud.githubusercontent.com/assets/2571694/25269235/b08af95c-2673-11e7-8bfb-a33784bb92b3.jpg)

When swiping the carousel, the second slide gets positioned off-center. Disabling the align-self setting will fix this problem.

The site (with align-self disabled in css) is here http://dev.red-tulip.co.uk/nearme/

Please note that we needed to set the align-self to overcome the issue that otherwise the slide contents get centered vertically which is not acceptable with varying content lengths (which will be the case when this site will go live).

**Comment by camelburrito** [comment]
@ChrisHoman - The issue here is `.carousel-slide {height:initial}`,in order have  smooth snapping and responsive behavior we would need to center the slides. This is why we made the slides default width and height 100%  you could use the slide as your base and then align items however you want inside of it. I guess in this case you would be able to solve it by enclosing your slide contents inside another div. Let me know if this helps!

**Comment by camelburrito** [comment]
Closing this for now , please feel free to re-open if needed.

**Comment by ChrisHoman** [comment]
Hi,

Unfortunately that doesn't seem to solve the problem. The issue still exists with the height:intial removed from css. What we try to accomplish is to have the flex items in the carousel slide align vertically to the top - regardless of height. Normally the following css should solve the problem (and does on desktop) but it fails on mobile:
`.carousel-slide {
	padding: 10px;
	display: flex;
	flex-wrap: wrap;
	justify-content: space-between;
    align-content: flex-start;
}`

Feel free to check it out here: http://dev.red-tulip.co.uk/nearme/#transportation

The screenshots from above still illustrate the problem correctly.

**Comment by camelburrito** [comment]
@ChrisHoman 
Just removing the height is not sufficient (as i had outlined above)

I have modified the code as i had mentioned, here is how it looks 

http://output.jsbin.com/nobison/quiet


The code can be found in. 
http://jsbin.com/nobison/5/edit?html,css,js,output

(let me know once you have taken a look at this i can delete the bin if you dont want it floating around)

**Comment by ChrisHoman** [comment]
@camelburrito 
I misinterpreted your earlier comment - thanks so much for your clarification. 
And yes, please delete the bin.
