### ISSUE TITLE
PHP Warning: Invalid argument supplied for foreach() in /home/user/public_html/wp-content/plugins/amp/includes/utils/class-amp-html-utils.php on line 11

### ISSUE THREAD

**Issue by riyaz95** [ampproject/amphtml#8873]
Hi
my error_log is growing with:
[19-Apr-2017 09:14:10 UTC] PHP Warning: Invalid argument supplied for foreach() in /home/user/public_html/wp-content/plugins/amp/includes/utils/class-amp-html-utils.php on line 11

I know it’s just a waring but it grow up every minute… 🙁

(I’m using PHP 7)

Thanks

PS: The error_log file is generated by the server

**Comment by jridgewell** [comment]
This is an issue with Wordpress's `amp-wp` plugin. I've cross posted the issue [here](https://github.com/Automattic/amp-wp/issues/687).
