### ISSUE TITLE
Double-click multiSize restrictions

### ISSUE THREAD

**Issue by eduardcotmrf** [ampproject/amphtml#8874]
Right now the amp-ad doubleclick implemention restricts multisize based on height and width, giving you an error in the console if the width it's bigger than the previous.

For example:

![screen shot 2017-04-21 at 16 55 20](https://cloud.githubusercontent.com/assets/23262331/25283230/5864e5fe-26b3-11e7-9ab2-b33bfd39bae1.png)

In our case it's very common to have configurations like 300x250,320x50 for example. The height it's always decreasing as especified in https://github.com/ampproject/amphtml/blob/master/ads/google/doubleclick.md but there are small fluctuations in the width. 

We think it would be interesting to support that in AMP, as the real problem in the user experience it's height fluctuation, but not width fluctuation.

We can prepare a PR for this change, do you think it would be interesting?

**Comment by jasti** [comment]
@eduardcotmrf have you considered setting the primary size to 320x250? if what's returned is a 300x250, it's just centered anyway?

**Comment by eduardcotmrf** [comment]
@jasti This is not possible as we are trying to get from adex ads in the standard sizes or the ones that generate more revenue for our clients. It's not the same requesting a 320x250 than a 300x250, as the last tag is more popular and mostly used within the industry.

**Comment by keithwrightbos** [comment]
cc/ @ampproject/a4a 
@eduardcotmrf to be clear, you're saying that you actually get less demand from AdX if you specify 320x250 than 300x250?

**Comment by eduardcotmrf** [comment]
I'm saying that asking for a 320x250 gets diferent advertisement than asking for a 300x250. You can see here that 320x250 it's not a standard size and 300x250 it's the top performer: https://support.google.com/adsense/answer/6002621?hl=en

**Comment by keithwrightbos** [comment]
Unfortunately, you cannot actually guarantee changing the width will not potentially trigger reflow because it is possible the publisher is using float for their layout.  However, I still don't understand why you cannot indicate a primary size of 320x250 with 300x250 as a possible multi-size?

**Comment by glevitzky** [comment]
As far as I am aware, the ad returned is not biased toward the primary dimensions. So setting the primary width and height to their largest respective values and adding the others to the multi-size attribute should accomplish what you're trying to do.

**Comment by eduardcotmrf** [comment]
The problem it's that I cannot have 300x250 and 320x50 in the same multisize array because one has bigger width and the other bigger height.

**Comment by michaelkleber** [comment]
@eduardcotmrf I think the suggestion is to use the artificial size 320x250 as the width/height of the ad unit (to reserve the full space needed for either ad), and then have both 300x250 and 320x50 in the data-multi-size array.

**Comment by eduardcotmrf** [comment]
Ok, thanks! Sorry I didn't undertand that. I'll try it and report back. Thanks!

**Comment by eduardcotmrf** [comment]
It Works setting the primary size with maxWidth and maxHeight and the array with the real sizes.

Thanks!
