### ISSUE TITLE
Invalid URL protocol 'file:' for attribute 'src' in tag 'amp-img'.

### ISSUE THREAD

**Issue by congyun** [ampproject/amphtml#8875]
Hello AMP team,

I've discovered that the validator currently doesn't allow `file:` URI schemes in the href tag, similar to #4242, #4094 and #4784;

> Invalid URL protocol 'file:' for attribute 'src' in tag 'amp-img'.

This can be reproduced by the below AMP HTML doc

```
<!doctype html>
<html ⚡4ads>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,minimum-scale=1">
  <style amp4ads-boilerplate>body{visibility:hidden}</style>
  <script async src="https://cdn.ampproject.org/amp4ads-v0.js"></script>
</head>
<body>
<a id="aw0" target="_top" href=%%CLICK_URL_UNESC%%%%DEST_URL%%>
  <amp-img src="FILE:JPG1"   width="300" height="250" alt="" class="img_ad"/>
  </a></body>
</html>
```

We are working on custom creative AMP ads in DRX, which is an important step for A4A. Could you please help us adding the `file:` ?

More info for our project can be found:  [here](https://goto.google.com/a4a-drx-custom-ad-fe)

Thanks!

**Comment by congyun** [comment]
Note that we are using the AMP4ADS spec instead of the regular AMP html spec, though this looks like a generic issue.

**Comment by jridgewell** [comment]
Is this just for local testing?

**Comment by congyun** [comment]
Sorry, didn't see the comment...Not really just for testing, it's a function we need on our Prod FE. We need to allow users to upload images, etc, as part of the AMP ads creative.

Happy to talk in GVC or provide more info if needed.

**Comment by jasti** [comment]
@powdercloud why do we disallow file:? CC @Gregable 
Is it possible to allow it?

**Comment by honeybadgerdontcare** [comment]
@jasti what is the use case for allowing it? AMP pages shouldn't be trying to load local files.

**Comment by jasti** [comment]
@honeybadgerdontcare  These are not pages, this is being used by an ad server to construct an AMP ads by fetching assets that reside locally.

**Comment by honeybadgerdontcare** [comment]
Understood. We don't want to allow `file:` as a protocol as that isn't a working AMP page or AMP Ad if given to a browser (e.g. the OP's html would not work on my computer). If this is being used as a placeholder in the ads frontend, then I recommend the ads frontend to do a best intended insertion of what the actual serving URL will be. So instead insert `https://{ads-server-best-guess}/` instead of `file:`. Another alternative is to use relative URLs instead of inserting `file:` where relative URLs are allowed (amp-img is one such case).

**Comment by congyun** [comment]
Thanks guys. I'll talk to our eng team to see if anyone of the two options is ok. Will ping this thread if more help is needed.

**Comment by Gregable** [comment]
You are essentially requesting that an internal intermediate format be valid by amp, but this is not the format that will be sent as an AMP document. This doesn't make much sense, please make the replacements before validating.
