### ISSUE TITLE
Forbid creating `map`s at module-load time

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#8880]
# Great First Issue: forbid creating `map`s at module-load time

## First Timers Only
We know figuring out the process for contributing to an open source project can be intimidating, so we created this issue as a way for you to learn the ropes.  (If you feel comfortable contributing to open source projects, please leave this issue for someone else.)

## What you will need to know

Basics:
- HTML5
- Javascript

Helpful:
- <abbr title="ECMAScript 6">ES6</abbr>
- Closure Compiler

## Background

These issues aren't required reading, but they provide some context for this task:
- [Issue \#4261: Remove side effect exports](https://github.com/ampproject/amphtml/pull/4261)
- [Issue \#5880: Introduce helper to make map-like objects](https://github.com/ampproject/amphtml/pull/5880#pullrequestreview-7083705)
- [Issue \#6089: Forbid `map` static side-effect calls](https://github.com/ampproject/amphtml/issues/6089)

For performance, consistency, and safety AMP uses a utility function called `map` to create map objects instead of using object literals. It improves performance by creating objects with a prototype chain shorter than an object literal's, so property lookups are faster. Consistency is increased with `map` because there is one clear API across the project to create simple key-value stores in memory. Safety is improved because `for-in` loops work as expected even if another library adds a property to `Object.prototype`.

AMP optimizes its Javascript code with Google Closure Compiler. Closure Compiler uses Dead Code Elimination at build-time to remove code from modules that aren't needed in the compiled code.

## Motivation

Static calls to `map` cannot be removed by Closure Compiler's DCE. This is because Closure Compiler cannot guarantee that `map` doesn't cause side effects that other code might depend on. When `map` is called only when needed, the Closure Compiler can do its job better.

AMP uses a linter rule to check for exports with side-effects, but currently there is a special-case that allows calls to `map`. This task removes the special case and fixes the locations that call `map` in a static context.

## The fix

Generally, this task will remove an exception to a build-step check and it will wrap offending `map` calls into functions. This will allow Closure Compiler to more effectively minify the AMP code.

## Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] Remove the special case check from `build-system/eslint-rules/no-export-side-effect.js:29` then run `gulp lint`. This will list the locations that need to be changed.

  ```diff
  -  return init && /(?:Call|New)Expression/.test(init.type)
  -      // Special case creating a map object from a literal.
  -      && init.callee.name != 'map';
  +  return init && /(?:Call|New)Expression/.test(init.type);
  ```
- [ ] Update those locations to be instantiated lazily. To see what correct usage looks like, try finding other places in the repo where `map` is used for a module-level variable.
- [ ] Make sure the tests pass when you run `gulp test --nobuild`. You can debug tests by also passing the `--watch` flag and using the browser inspector. If you want to run one test, or a glob of tests, you can pass `--files=path/to/test-*.js`
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review).  Mention `closes Issue <this issue number>` in the description.
- [ ] Add @cvializ and @jridgewell as reviewers
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

## Questions?

If you have questions ask in this issue or on your Pull Request (if you've created one) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

**Comment by yskoh** [comment]
Hi  
I'm looking for opportunity to contribute to open source for the very first time.
Can I work on this?

**Comment by cvializ** [comment]
Wonderful, we're glad to have you as a contributor. Yes, if you're interested and motivated to start in the next day or so, I'll assign the issue to you. Let us know if you have any questions. Happy coding : )

**Comment by yskoh** [comment]
okay! thanks!

**Comment by mrjoro** [comment]
Hi @yskoh; I invited you to join ampproject on GitHub.  Once you accept that we can assign this issue to you.  Thanks!

**Comment by aghassemi** [comment]
@yskoh Just following up to see if you are still interested in working on this issue.

**Comment by mrjoro** [comment]
@yskoh since we haven't heard from you in a while, we'll open this up to anyone else who wants to work on a GFI.

**Comment by goranmedic** [comment]
I'll do it.

**Comment by yskoh** [comment]
sorry for the late reply :(
okay great!

**Comment by thomasdane** [comment]
I am going to have a go at this, if that's okay. I am able to commit 1 hour twice per week. I can update in a few hours and again in a few days. If I'm not making fast enough progress I can release the issue.

**Comment by mrjoro** [comment]
Great!  Thanks @thomasdane.  I've sent you an invite to join the AMP Project on GitHub; once you accept that we can assign this issue to you.

**Comment by thomasdane** [comment]
@mrjoro done. I have AMP running locally now so will take a look at the issue.

**Comment by thomasdane** [comment]
I've removed the code https://github.com/thomasdane/amphtml/commit/b77fec18e318e0eeaa8c15593f505bc11484936b

I've run out of time for today. I'll fix the linting errors and try to complete the rest of this ticket in a few days time, if that's okay. Thanks for the awesome opportunity.

**Comment by mrjoro** [comment]
Thanks for letting us know @thomasdane.

**Comment by prateekbh** [comment]
Wanna claim this

**Comment by choumx** [comment]
Just saw this now, but 👍 .

Another issue with using `map()` at module-level is the possibility of module import order issues. Specifically, the `Object.assign` polyfill may be imported _after_ a dependency that uses `map()`.

**Comment by prateekbh** [comment]
so far only 2 instances of module-level `map` are there(found by basically disabling the custom lint rule). 
```
1. 3p.js line 39

2.  _a4a-config.js line 56
```

I'll try wrapping these in function calls
