### ISSUE TITLE
Add console warning for `googleanalytics-v2` config

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#8883]
Since we are not planning to support nor document this config, could we add a console error to notify developers that it may be deprecated at any time?

Also, we should consider to rename to something like `googleanalytics-alpha` instead. v2 implies next version, but since an in-place upgrade is the current plan, this is not accurate.

cc @avimehta

**Comment by lannka** [comment]
Can you think of the exact warning message you want to show to user?

**Comment by lannka** [comment]
@rudygalfi this will be a trivial change that I can make when we launch this new config. At that time, I'd also remove the current warning comment in the code.

So, this task is blocked by the Google Analytics side change.

**Comment by rudygalfi** [comment]
Assuming we change the name to `googleanalytics-alpha`, then I would make this the warning:

"amp-analytics: `googleanalytics-alpha` configuration is not planned to be supported long-term. Avoid use of this value for amp-analytics `config` attribute unless you plan to migrate before deprecation"

Feel free to reformat the message if there's a specific pattern that needs to be used. For instance, I did "amp-analytics:" at the beginning to indicate the relevant component; not sure if that's aligned with how we usual report messages.

**Comment by lannka** [comment]
@rudygalfi @honeybadgerdontcare do you think validator is a better place to surface such a warning message? 

So we don't add extra bytes to AMP binaries. And also in long term there is no urgent to remove such a warning message, which we should if it's in AMP runtime.

**Comment by honeybadgerdontcare** [comment]
Typically we try to avoid putting too many warnings in the validator as it lowers the value of such warnings as we add more. Not sure on which side this would fall on in that equation.

By `no urgent to remove such a warning message` is that a particular time frame? Having a date of removal would be good to assess putting it in the validator.

cc @Gregable @powdercloud for thoughts.

**Comment by honeybadgerdontcare** [comment]
@rudygalfi just to be clear, this would be a temporary value for `config` in `<amp-analytics config="..."></amp-analytics>`?

**Comment by rudygalfi** [comment]
Yes, it's intended to be temporary. This strikes me more as a runtime #development=1 message, though. It doesn't have to do with validity.

**Comment by lannka** [comment]
re: @rudygalfi #development=1 message will go to validator.

re: @honeybadgerdontcare I meant such a warning message probably cost less in validator than in runtime (mainly because of binary size). what you think?

**Comment by honeybadgerdontcare** [comment]
#development=1 means the validator would run and output it's results to console. Could the Runtime also output a warning message each time to console or even just when #development=1 is present?

**Comment by lannka** [comment]
Either runtime or validator prints a message will be enough. and i slightly prefer validator :-).

**Comment by honeybadgerdontcare** [comment]
If this config is relevant only to amp-analytics, shouldn't this belong there? :) That way when amp-analytics knows it's done with this config it can remove the warning at the same time. Then there is no need to coordinate validator and runtime releases.

As Rudy mentions this doesn't have to do with validity. Further the validator does not have an implementation to do this. All warnings currently have to do with deprecations and all deprecations are built around having something to replace it with (we don't do the "this is deprecated, the new thing isn't ready yet" dance).

I'd rather not make the validator a place for warnings about using certain alpha or beta items. That seems like it belongs in the component that is doing it or in amp-experiment. Yes, it makes the AMP Runtime or specific component larger, but that should only be temporary.
