### ISSUE TITLE
Disable multi-size ad requests when inside of a ad container - Sticky/ Flying Carpet

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#8891]
Since ad containers like sticky and flying carpet ads only perform well at certain sizes, we should avoid multi-size in these containers to prevent bad user experiences.

**Comment by keithwrightbos** [comment]
Assigning to @glevitzky for changes to Fast Fetch flow

**Comment by jasti** [comment]
@glevitzky can you please also take care of it for delayed fetch flow as well? Thanks.

**Comment by glevitzky** [comment]
Sorry, just noticed this. Will put something out for the next cut.

**Comment by glevitzky** [comment]
Closing this, as this requirement is now being forced through validation.
