### ISSUE TITLE
AMP Cache s-maxage header

### ISSUE THREAD

**Issue by oliverfernandez** [ampproject/amphtml#8894]
AMP Cache documentation says:

> It uses the origin's caching headers, such as Max-Age, as hints in deciding whether a particular document or resource is stale

Is header `s-maxage` (meant for shared caches) also used?

**Comment by vitaliybl** [comment]
Yes, Google AMP Cache will honor s-maxage when deciding when to refresh your document. I believe we don't send it to the client, though.

**Comment by oliverfernandez** [comment]
Thanks for the quick answer @vitaliybl 

After several tests, I agree with you that AMP Cache does not send the original cache headers to the client, but different ones (no s-maxage, and usually a Max-Age very small)
