### ISSUE TITLE
Errors: steady "string did not match pattern" errors

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#8917]
We are seeing a steady ~50K/day errors from iOS webviews. Most likely iGSA. 

The link to the error: p/2606060847449554900

The error typically looks like this:
```
The string did not match the expected pattern.
```

The stack looks like this:
```
matches@[native code]
Na@https://cdn.ampproject.org/rtv/011492571781980/v0/amp-analytics-0.1.js:15:332
https://cdn.ampproject.org/rtv/011492571781980/v0/amp-analytics-0.1.js:105:296
fire@https://cdn.ampproject.org/rtv/011492571781980/v0/amp-analytics-0.1.js:17:796
va@https://cdn.ampproject.org/rtv/011492571781980/v0/amp-analytics-0.1.js:109:389"
```

It appears that the code intends for this error to go into user channel here: https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/analytics-root.js#L445

Not clear yet why it does not.

**Comment by muxin** [comment]
Also appears as error
```
Error: Failed to execute 'matches' on 'Element': '#123' is not a valid selector.
```
in Android Chrome
See https://github.com/ampproject/amphtml/issues/9125
