### ISSUE TITLE
Service registration: clarify constructor-vs-factory instantiation

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#8922]
It appears that [Viewer](https://github.com/ampproject/amphtml/blob/6bf3259810c7d293e29f7afcd43e06b19b0c6dd4/src/service/viewer-impl.js#L958) registration the factory is passed in place of constructor. It looks like Viewport has the same issue and probably some others. Please clarify and address. Feel free to drop from P0 if cherry-pick is not needed into PROD. But if it is - please let us know ASAP.

(Related issue #8918).

**Comment by kmh287** [comment]
Viewer was changed over to the new service registration code path in #7896, but before that PR the service was also created via factory. I believe a factory is used here and in some of the other services in order to pass additional args into the service's constructor besides a window or ampdoc.

**Comment by kmh287** [comment]
#8923 #8927 

@dvoytenko can I close this issue?

**Comment by dvoytenko** [comment]
Yes
