### ISSUE TITLE
Preserve URLs when sending to Google Analytics via amp-analytics

### ISSUE THREAD

**Issue by joshcp** [ampproject/amphtml#8925]
## What's the issue?

We're using event tracking to capture the URL when a user clicks an outbound link. However, the data is urlencoded - which is a problem when trying to compare with non-urlencoded data from the primary (non-amp) property.

## How do we reproduce the issue?

Currently collecting event data as outlined in the [Google Analytics AMP documentation](https://developers.google.com/analytics/devguides/collection/amp-analytics/#outbound_link_tracking). (Note issue #8692 related to documentation error)

```html
<amp-analytics>
    <script type="application/json" type="googleanalytics">
        {
          "vars": {
            "account": "UA-XXXXXX-YY"
          },
          "triggers": {
            "trackPageview": {
              "on": "visible",
              "request": "pageview"
            }, 
            "trackOutboundClick": {
                "on": "click",
                "selector": "[href*='/offsite/']",
                "request": "event",
                "vars": {
                    "eventCategory": "outbound-link-aff", 
                    "eventAction": "${outboundLink}"
                }
            }
          }
        }
    </script>
</amp-analytics>
```
and
``` html
<a href="http://example.com/offsite/page" data-vars-outbound-link="http://example.com/offsite/page">Some link</a>
```

Data from `amp-analytics` shows up in Google Analytics as
`http%3A%2F%2Fexample.com%2Foffsite%2Fpage`

Data from standard analytics event tracking shows up as
`http://example.com/offsite/page`

## What browsers are affected?

Behavior seems to be consistent across browsers.

## Which AMP version is affected?

Currently using `AMP ⚡ HTML – Version 1492571781980`

**Comment by kschmidtdev** [comment]
We've been experiencing the same thing - `${outboundLink}` ends up url-encoded and if we send it as an `eventLabel` to GA, our data people are staring at not-human-friendly URLs 😆

**Comment by rudygalfi** [comment]
Do we know if this needs to be addressed at the AMP layer or the GA layer? Does the same encoding of the data go over the network from both pages but then it just get handled differently on the GA side for AMP vs. non-AMP?

cc @avimehta

**Comment by kschmidtdev** [comment]
It looks like the `amp-analytics` is url-encoding some parameters, but everything already gets url-encoded, so it's double-encoded. Illustrated here:
<img width="637" alt="screen shot 2017-04-25 at 4 56 41 pm" src="https://cloud.githubusercontent.com/assets/2383700/25412599/c8daf4d6-29d8-11e7-8b15-906391a6624c.png">

**Comment by lannka** [comment]
@avimehta should this be part of your "Filter" work?

**Comment by rudygalfi** [comment]
@lannka To take another look.

**Comment by lannka** [comment]
This is indeed a bug. It happens when a var is defined recursively:

```javascript
"vars": {
  "a": "${b}",
  "b": "${c}",
  "c": "https://google.com"
}
```

it gives:

```
a:https%253A%252F%252Fgoogle.com
b:https%3A%2F%2Fgoogle.com
c:https://google.com
```

I'm looking into a fix. 
/cc @avimehta
