### ISSUE TITLE
Attribute 'href' may not appear in tag 'use'

### ISSUE THREAD

**Issue by amedina** [ampproject/amphtml#8928]
## What's the issue?
HTML page with the following content fails to validate:
```
<div class="wrap">
    <a href="#content" class="menu-scroll-down">
        <svg class="icon icon-arrow-right" aria-hidden="true" role="img">
            <use href="#icon-arrow-right" xlink:href="#icon-arrow-right"></use>
        </svg><span class="screen-reader-text">Scroll down to content</span>
    </a>
</div>
```
Validation error:
<img width="941" alt="svg-validation-error" src="https://cloud.githubusercontent.com/assets/506089/25364132/f278433a-2914-11e7-8447-639d5d6a672f.png">

Could not find explanation/rationale for validation failure in docs; not sure if it is a bug or a feature. 

## What browsers are affected?
All browsers

## Which AMP version is affected?
AMP Version 1492571781980

**Comment by honeybadgerdontcare** [comment]
Thank you for the report. Looks like `xlink:href` (which is allowed) has been deprecated in favor of just `href`. We'll update the validation to allow `href` with local (within document) links where `xlink:href` is also allowed.

**Comment by honeybadgerdontcare** [comment]
This is checked in but it'll take up to 2 weeks to reach production.
