### ISSUE TITLE
amp-bind validator clashes with default styling with empty class

### ISSUE THREAD

**Issue by kul3r4** [ampproject/amphtml#8933]
I was trying to fix the validation errors that I get from [product page](https://ampbyexample.com/samples_templates/product_page/#development=1) in development mode as @rudygalfi noted that the page has a lot of errors. I pushed my changes [here](https://github.com/ampproject/amp-by-example/commit/cb29f109e4c37110c6592ec2f6b350f066b5836c). However I noticed that some errors are still there in case I want to use an empty class.
My code is:
`<li option="M" class="" selected
                  [class]="(product[product.selectedColor].sizes['M'] != 'unavailable')
                      ? ''
                      : 'unavailable'">M</li>`
and it becomes:
`<li option="M" class="i-amphtml-error i-amphtml-element-error" selected="" [class]="(product[product.selectedColor].sizes['M'] != 'unavailable')
                      ? ''
                      : 'unavailable'" role="option" aria-selected="true" tabindex="0" error-message="amp-bind: Default value for [class] does not match first expression result (). This can result in unexpected behavior after the next state change.​​​"`
What would be the best way to have an empty class? 
I also think, no matter if the class is empty or not, the fact that amp runtime adds class like `i-amphtml-error i-amphtml-element-error` is confusing the validator.
@kmh287 @choumx Could you help with this?

**Comment by kmh287** [comment]
@kul3r4 This looks like a bug on our end. Thanks for catching this! I'm looking into a solution now.
