### ISSUE TITLE
amp-ad-network-fake-impl is broken

### ISSUE THREAD

**Issue by jonkeller** [ampproject/amphtml#8935]
When including &lt;amp-ad type="fake" ...additonal attrs...&gt; it just doesn't work. With some CSS hackery and setting the src attribute to a file which ends with .json yet contains only HTML, you can make it work for testing purposes. But let's fix it so that it works as advertised.

**Comment by jonkeller** [comment]
Example of aforementioned hackery: https://github.com/ampproject/amphtml/pull/8887

**Comment by dvoytenko** [comment]
@jonkeller Can you try this: https://github.com/ampproject/amphtml/blob/master/contributing/DEVELOPING.md#a4a-envelope-a4a-a4a-3p

Basically, using this, you can essentially run any AMP doc as an embed. E.g. `http://localhost:8000/a4a/examples/article.amp.max.html`. Just don't try "nested embeds".

If that works and you want, e.g., test with multiple embeds - you can just copy the document generated by `/a4a/...` and modify it by hand.

**Comment by jonkeller** [comment]
Thanks, Dima.

I'm sure that would work. I would still like for the fake ad network to be
fixed, though, to make my amp-analytics documentation match up as closely
as possible with a real-world use case. I'm happy to do the work myself
since I'm the only "customer" that I'm aware of.

**Comment by dvoytenko** [comment]
sg

**Comment by jonkeller** [comment]
As I look at this more, I think I was just not using it properly. For instance, it was displaying the raw JSON enclosing the creative HTML, but that seems to be because I was using fakesig==true. Removing that seems to make it work. Although the documentation could stand to be improved to mention that, what the signature is used for, steps for generating the signature, etc.
I'm tempted to just kill the current issue, but enough other people have touched it by now that perhaps they have other findings that they want addressed by it. But if that is not the case, feel free to close it.
