### ISSUE TITLE
amp-bind: Cycles with amp-state's [src] binding 

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#8948]
### Issue

`amp-state`'s ability to trigger `setState` from a `[src]` binding causes a possible cycle:
```
<amp-state id="myState" [src]="'/myEndpoint?foo=' + myState.foo"></amp-state>
```
If the `/myEndpoint?foo=` XHR returns `{foo: <random number>}`, then the XHRs will trigger incessantly: `[src]` mutation -> `setState` -> `[src]` mutation 

Should only be an issue with `amp-state` since it's essential behavior is updating the state. Hitherto, no element calls `setState` via a bind mutation.

### A few possible solutions

1. Remove `[src]` binding for amp-state, instead use forms as described in https://github.com/ampproject/amphtml/issues/8648#issuecomment-293077744.
2. Change amp-state[src] XHR to only update state and *not* apply bindings, instead force use of a separate action `myAmpState.refresh`.
3. State change due to `amp-state[src]` will ignore mutations to `amp-state` elements.

Props to @kmh287 for pointing this out!

**Comment by jridgewell** [comment]
> Hitherto

👴

**Comment by kmh287** [comment]
For option 2, could a developer still combine refreshing the state into one action with

<foo on="event:AMP.setState({myAmpStateSrc=bar});myAmpState.refresh">

**Comment by jridgewell** [comment]
Could we restrict certain bindings to require user action?

**Comment by choumx** [comment]
> For option 2, could a developer still combine refreshing the state into one action

Yea, would require #8678.

**Comment by choumx** [comment]
I'm currently leaning towards option 3 which would most preserve the convenience of using the `src` attribute.
