### ISSUE TITLE
amp-ad not working on Safari

### ISSUE THREAD

**Issue by alfredmyers** [ampproject/amphtml#8950]
## What's the issue?

amp-ad does not show intermittently on Safari for macOS

## How do we reproduce the issue?

1. Navigate to https://alfredmyers.github.io/sampaguide/regioes/zona-central/centro/
2. Scroll to the end of the page.
3. Check if ad is shown at the bottom of the page.
4. Navigate randomly to another page
5. Goto step 2.

## What browsers are affected?

Works on Chrome on macOS and Android. Works on Safari and Chrome on a iPhone 4 with iOS 7.1.2
Does not work **randomly** on Safari for macOS Version 10.1 (12603.1.30.0.34).

## Which AMP version is affected?

1493083583453

**Comment by alfredmyers** [comment]
Navigated around a little bit.
It seems to be working intermittently.
Ads don't load randomly. When I refresh the page, it appears.

Here's a log taken from Safari's dev tools:

[Error] Origin https://alfredmyers.github.io is not allowed by Access-Control-Allow-Origin.
[Error] Failed to load resource: Origin https://alfredmyers.github.io is not allowed by Access-Control-Allow-Origin. (amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it, line 0)
[Error] XMLHttpRequest cannot load https://pagead2.googlesyndication.com/amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it?1493160840000 due to access control checks.
[Error] Origin https://alfredmyers.github.io is not allowed by Access-Control-Allow-Origin.
[Error] Failed to load resource: Origin https://alfredmyers.github.io is not allowed by Access-Control-Allow-Origin. (amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it, line 0)
[Error] XMLHttpRequest cannot load https://googleads.g.doubleclick.net/amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it?1493160840000 due to access control checks.
[Error] Origin https://alfredmyers.github.io is not allowed by Access-Control-Allow-Origin.
[Error] Failed to load resource: Origin https://alfredmyers.github.io is not allowed by Access-Control-Allow-Origin. (amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it, line 0)
[Error] XMLHttpRequest cannot load https://3p.ampproject.net/amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it?1493160840000 due to access control checks.
[Error] Origin https://alfredmyers.github.io is not allowed by Access-Control-Allow-Origin.
[Error] Failed to load resource: Origin https://alfredmyers.github.io is not allowed by Access-Control-Allow-Origin. (amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it, line 0)
[Error] XMLHttpRequest cannot load https://d-15004278783612922515.ampproject.net/amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it?1493160840000 due to access control checks.
[Error] Blocked a frame with origin "https://d-15004278783612922515.ampproject.net" from accessing a frame with origin "https://alfredmyers.github.io". Protocols, domains, and ports must match.
	lr (show_ads_impl.js:161:371)
	Gu (show_ads_impl.js:263:188)
	Su (show_ads_impl.js:276:403)
	(anonymous function) (show_ads_impl.js:289:375)
	pi (show_ads_impl.js:57:178)
	vi (show_ads_impl.js:61)
	(anonymous function) (show_ads_impl.js:282)
	Global Code (show_ads_impl.js:289:483)
	write
	(anonymous function) (adsbygoogle.js:56:350)
	B (adsbygoogle.js:54:249)
	J (adsbygoogle.js:53:97)
	pf (adsbygoogle.js:52:1637)
	zf (adsbygoogle.js:65)
	Af (adsbygoogle.js:58:172)
	(anonymous function) (adsbygoogle.js:66:263)
	Hc (adsbygoogle.js:18:155)
	Qc (adsbygoogle.js:22:210)
	If (adsbygoogle.js:66:242)
	Jf (adsbygoogle.js:65:475)
	Wf (adsbygoogle.js:81:115)
	(anonymous function) (adsbygoogle.js:77:320)
	Hc (adsbygoogle.js:18:155)
	Qc (adsbygoogle.js:22:210)
	Qf (adsbygoogle.js:77:299)
	Te (adsbygoogle.js:75:273)
	Xf (adsbygoogle.js:81:369)
	Hc (adsbygoogle.js:18)
	Qc (adsbygoogle.js:22:210)
	Rf (adsbygoogle.js:81:145)
	(anonymous function) (adsbygoogle.js:82)
	Global Code (adsbygoogle.js:82)
[Error] Blocked a frame with origin "https://d-15004278783612922515.ampproject.net" from accessing a frame with origin "https://alfredmyers.github.io". Protocols, domains, and ports must match.
	Gu (show_ads_impl.js:265)
	Su (show_ads_impl.js:276:403)
	(anonymous function) (show_ads_impl.js:289:375)
	pi (show_ads_impl.js:57:178)
	vi (show_ads_impl.js:61)
	(anonymous function) (show_ads_impl.js:282)
	Global Code (show_ads_impl.js:289:483)
	write
	(anonymous function) (adsbygoogle.js:56:350)
	B (adsbygoogle.js:54:249)
	J (adsbygoogle.js:53:97)
	pf (adsbygoogle.js:52:1637)
	zf (adsbygoogle.js:65)
	Af (adsbygoogle.js:58:172)
	(anonymous function) (adsbygoogle.js:66:263)
	Hc (adsbygoogle.js:18:155)
	Qc (adsbygoogle.js:22:210)
	If (adsbygoogle.js:66:242)
	Jf (adsbygoogle.js:65:475)
	Wf (adsbygoogle.js:81:115)
	(anonymous function) (adsbygoogle.js:77:320)
	Hc (adsbygoogle.js:18:155)
	Qc (adsbygoogle.js:22:210)
	Qf (adsbygoogle.js:77:299)
	Te (adsbygoogle.js:75:273)
	Xf (adsbygoogle.js:81:369)
	Hc (adsbygoogle.js:18)
	Qc (adsbygoogle.js:22:210)
	Rf (adsbygoogle.js:81:145)
	(anonymous function) (adsbygoogle.js:82)
	Global Code (adsbygoogle.js:82)
[Error] Blocked a frame with origin "https://d-15004278783612922515.ampproject.net" from accessing a frame with origin "https://alfredmyers.github.io". Protocols, domains, and ports must match.
	ae (osd.js:45:484)
	de (osd.js:45)
	(anonymous function) (osd.js:109:381)
	(anonymous function) (osd.js:18:389)
	cc (osd.js:18:97)
	(anonymous function) (osd.js:18:359)
	N (osd.js:109:388)
	Ef (osd.js:87:244)
	vg (osd.js:124:503)
	sg (osd.js:127)
	tg (osd.js:122:156)
	oh (osd.js:139:115)
	ph (osd.js:139)
	qh (osd.js:135:430)
	(anonymous function) (osd.js:18:389)
	cc (osd.js:18:97)
	(anonymous function) (osd.js:18:359)
[Error] Blocked a frame with origin "https://d-15004278783612922515.ampproject.net" from accessing a frame with origin "https://alfredmyers.github.io". Protocols, domains, and ports must match.
	ae (osd.js:45:484)
	de (osd.js:45)
	(anonymous function) (osd.js:109:381)
	(anonymous function) (osd.js:18:389)
	cc (osd.js:18:97)
	(anonymous function) (osd.js:18:359)
	N (osd.js:109:388)
	Ef (osd.js:87:244)
	vg (osd.js:124:503)
	(anonymous function) (osd.js:127:163)
	(anonymous function) (osd.js:18:389)
	cc (osd.js:18:97)
	(anonymous function) (osd.js:18:359)

**Comment by jridgewell** [comment]
This is an issue with your adsense ad filling, not with AMP inserting the ad. Verified by inspecting the contents of the ad (there's an iframe inside the `<amp-ad>` element that gets inserted).
