### ISSUE TITLE
Create a basic experiment system

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#897]
A basic experiment system will be comprised of:

1. experiments.html document
2. experiment control library for AMP runtime and extensions

Both parts will employ `amp-exp` cookie to toggle and control experiments.

**experiments.html**

This file will be hosted in the GitHub and deployed to AMP Project's CDN. It will list all available experiments with their descriptions and provide a button to toggle each experiment on and off.

The way the experiment will be toggled is by adding/removing a cookie in the form `exp.{experimentId}`. This will be done most likely via `document.cookie` API.

**experiment control library**

This library will have a very simple API:
```
isExperimentOn(experimentId):boolean
```

The library will read the experiment state from `document.cookie`.

How the runtime or extensions will choose to use this API is up to them. Few convenience methods could also be added such as `assertExperimentOn`, etc.

/cc @cramforce

**Comment by cramforce** [comment]
LGTM

**Comment by dvoytenko** [comment]
Launched. Available here:

https://cdn.ampproject.org/experiments.html

**Comment by rudygalfi** [comment]
Super-awesome to have this experiment infrastructure. :+1: Thanks!
