### ISSUE TITLE
Support AMP.navigateTo action

### ISSUE THREAD

**Issue by gilbox** [ampproject/amphtml#8976]
## What's the issue?

This is a feature request. We'd like to be able to have a drop-down menu that triggers going to a new URL as if you'd clicked on a link.

Here's the [non-AMP version](https://www.airbnb.com/s/sf/homes?s_tag=XWeKjiWv&allow_override%5B%5D=) of the page and the options (you must use small viewport to see them) are at the bottom of the page and they allow you to change the language and currency type.

The feature could look something like this:

```
<select on="change:AMP.goToURL(event.value)">
  <option value="https://www.airbnb.com/asdf">foo</option>
  <option value="https://www.airbnb.com/xyzw">bar</option>
</select>
```

This is a screenshot from our non-AMP page to illustrate the feature:

![image](https://cloud.githubusercontent.com/assets/2136203/25458722/ef8b45ba-2a8f-11e7-9a8f-d16940db0fe9.png)

**Comment by choumx** [comment]
Seems reasonable since anchor tags don't work inside `select` or `option`. We already have a [AMP.goBack](https://github.com/ampproject/amphtml/blob/master/spec/amp-actions-and-events.md#amp-target) action.

Changing title since this isn't really specific to `amp-bind`.

/cc @ericlindley-g @dvoytenko

**Comment by dvoytenko** [comment]
I can see this. @choumx is our user-action control strong enough however for this use case (asking because I have no idea)?

**Comment by choumx** [comment]
Fair point. Since navigation is such a big action, maybe we should restrict its usage to certain elements/events. I'll bring this up during next design review.

**Comment by jridgewell** [comment]
We have a second request for this #9206.

**Comment by aghassemi** [comment]
@choumx @jridgewell #8515 (`amp-exit`) would also handle this use-case (I personally don't mind having both, each has its own pros and cons. `amp-exit` is more flexible but less ergonomic than `goToUrl`)

since I am voicing my opinion, I slightly prefer `navigateTo` to `goTourl` for wording.

**Comment by choumx** [comment]
@aghassemi Thanks for the heads up. Though, `amp-exit` would share the same "trust" issue discussed in https://github.com/ampproject/amphtml/issues/8901#issuecomment-300612756 if it uses `on="tap:"`.

Good suggestion on `navigateTo()`.

**Comment by Rahul007shah** [comment]
Hi Team, Is there any update for the `navigateTo()` feature? Looking forward to embed this feature in Priceline.com Google-AMP conversion.

Thanks
Rahul

**Comment by choumx** [comment]
Hi Rahul, thanks for reaching out. It's on our radar and we're hoping to tackle the prerequisite "trust" feature in the next sprint, after which `navigateTo` will be a simple change.

**Comment by Rahul007shah** [comment]
Hi Team,

Please provide demo and documentation for AMP.navigateTo component.

Thanks,
Rahul

**Comment by aghassemi** [comment]
Hi @Rahul007shah 

Documentation is here: https://github.com/ampproject/amphtml/blob/master/spec/amp-actions-and-events.md#special-targets 

Example is here: https://github.com/ampproject/amphtml/blob/master/examples/standard-actions.amp.html

**Comment by wudizhuzhuxia** [comment]
Hi Team,I have a question about goBack?
<button on="tab:AMP.goBack">goBack</button>
Is that the correct example above? If it‘s not right.
Please provide demo and documentation for AMP.goBack component.
Thanks!

**Comment by wudizhuzhuxia** [comment]
Hi Team,I have a question about goBack?
`<button on="tab:AMP.goBack"></button>`
Is that the correct example above? If it‘s not right.
Please provide demo and documentation for AMP.goBack component.
Thanks!

**Comment by aghassemi** [comment]
@wudizhuzhuxia correct. documentation is here: https://github.com/ampproject/amphtml/blob/master/examples/standard-actions.amp.html
