### ISSUE TITLE
Produce a release file artifact for releases of the javascript AMP Validator

### ISSUE THREAD

**Issue by Gregable** [ampproject/amphtml#8978]
We should update a file with release information whenever a new amp validator version is released to cdn.ampproject.org, since these releases are not in sync with the state in github.

**Comment by Gregable** [comment]
See https://github.com/ampproject/amphtml/blob/master/validator/CHANGELOG.md

We'll update this on ever validator release from here out.

**Comment by diggy106** [comment]
Thanks!
