### ISSUE TITLE
amp-pixel referrerpolicy invalid

### ISSUE THREAD

**Issue by jmadler** [ampproject/amphtml#8979]
amp-pixel's docs claim that the tag supports referrerpolicy, but it is considered invalid in the validator.

**Comment by jridgewell** [comment]
`referrerpolicy` was just [added](https://github.com/ampproject/amphtml/pull/8597), but we forgot validator support.

**Comment by lannka** [comment]
ah, forgot that part. @honeybadgerdontcare could you help on that? see the [spec](https://github.com/ampproject/amphtml/blob/master/builtins/amp-pixel.md#attributes)

**Comment by honeybadgerdontcare** [comment]
Sure, I'll add it. Takes about two weeks for validation changes to make it to prod.

**Comment by honeybadgerdontcare** [comment]
Fixed, should be live in prod in about two weeks.
