### ISSUE TITLE
presubmit check fail on travis with unrelated error

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#9012]
See https://travis-ci.org/ampproject/amphtml/builds/225136538 from #8609 
presubmit check is complaining 

> "A pull request may not contain a mix of flag-config and non-flag-config files. Please make your changes in separate pull requests. First offending file: .github/ISSUE_TEMPLATE.md"

while #8609 only changes two non-config files. 

Not sure if it's a bug. cc @rsimha-amp

**Comment by rsimha-amp** [comment]
From the error message, check-pr.js seems to think your PR also contains the file .github/ISSUE_TEMPLATE.md. When was your branch last synced to master? The file in question was edited 3 days ago, so it's possible that an out of date branch would cause this.

Could you sync up and see if the error goes away?

**Comment by zhouyx** [comment]
Thanks @rsimha-amp I've asked the author to rebase.

**Comment by rsimha-amp** [comment]
With PR #9014, this issue is mitigated by printing the full list of files in the PR in case of a failure. The error message indicates that the developer's branch may be out of sync.
