### ISSUE TITLE
Intent to implement: Non-modal dismissable user notifications

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#902]
Implement a tag that can be shown conditionally for applicable users and that can be dismissed by users.

Usage
```html
<amp-user-notification 
    layout=nodisplay
    data-dialog-id="some-dialog"
    data-show-if-href="https://external-host.com/show-dialog"
    data-dismiss-href="https://external-host.com/confirm">
   …arbitrary HTML…
   <button on="tap:amp-user-notification.dismiss()">Got it</button>
</amp-user-notification>
```
## Showing the dialog
The new tag `amp-user-notification` always starts out in layout mode `nodisplay` (isn’t shown). Upon page load it makes a POST CORS XHR request to the URL given as `data-show-if-href`. It posts an `ExternalCID` that is specific for the string given as `data-dialog-id` as the POST argument “user_id”.

The POST request is expected to return a simple JSON document of the form
`{"show_dialog": true}`
or
`{"show_dialog": false}`

In case of the `true` response AMP switches the `<amp-user-notification>` tag to have `container` layout and displays it in a fixed positioned container at position (0, 0) and as wide as the screen.

## Closing the dialog
A button or similar tag inside of the notification can be designated with `on="tap:amp-user-notification.dismiss()"` to dismiss the notification.
If the user taps that button the `<amp-user-notification>` is again switched to `nodisplay` mode and AMP makes a POST CORS XHR request to the URL given as `data-dismiss-href`. It posts an `ExternalCID` that is specific for the string given as `data-dialog-id` as the POST argument “user_id”.

The above POST request presents an opportunity for the publisher to store for the given “user_id” as to whether it should return true next time a request to `data-show-if-href` is made.

**Comment by cramforce** [comment]
See #871 for one possible use of this.

**Comment by cramforce** [comment]
@erwinmombay Assigned you. OK?

**Comment by erwinmombay** [comment]
@cramforce :+1:

**Comment by rudygalfi** [comment]
Trying to get a handle on when various features will land. Any estimate on this one?

**Comment by erwinmombay** [comment]
@rudygalfi almost done (thursday or friday at worst), talking to @dvoytenko about some technical details on implementation (since he's also working on some alert stuff). I think he had some concerns on this specific component.

**Comment by rudygalfi** [comment]
:+1: thanks

**Comment by ericlindley-g** [comment]
@erwinmombay — can this be closed?

**Comment by erwinmombay** [comment]
@ericlindley-g i think we should be good here since we have issues for the follow ups. anyone feel free to reopen otherwise.
