### ISSUE TITLE
`attachShadowDoc` fails when reusing shadow root

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#9022]
Context: https://github.com/choumx/amp-pwa/issues/8

/cc @dvoytenko

**Comment by dvoytenko** [comment]
Let's see if we can reuse shadow root reuse. I'm actually not sure what's best here. I think the SD spec allows even multiple shadow attachments and that could work better?

**Comment by leonardorey1970** [comment]
Hi, we have the same problem, once a second banner appears the first one disappears, this cases occurs for Chrome browsers on Android devices.

**Comment by choumx** [comment]
@leonardorey1970 Sorry about that. You can workaround by creating a new root for every call of `attachShadowDoc`.

**Comment by leonardorey1970** [comment]
Thanks choux for your reply. I do not understand how to create a new root for each call of attachShadowDoc function. 

We are attaching the function used by us to inserting an external banner every 3x news, when this function is called the second time, the first banner that was inserted can not be displayed and opening again.
Could you tell me please, if our function could be updated to implement a workarround?

 _handleBannerResponse(event){
        var container = "#banner-content-"+event.currentTarget.elementIndex;
				try{				window.loadBannerAMP(this.shadowRoot.querySelector(container),event.detail.xhr.responseXML,event.currentTarget.url);
				}catch(e){
					alert("Error" + e);
				}
 }

Thanks!
Leonardo

**Comment by dvoytenko** [comment]
/cc @cvializ As I mentioned above, I'm not sure if root reuse is a good idea or not yet. We'd only want to reuse it for performance reasons, but I don't know if there's an actual impact. The code to create a new container could simple be:

```
const container = ...
const newHost = document.createElement('div');
container.appendChild(newHost);
AMP.attachShadowDoc(newHost, ...);
```

**Comment by leonardorey1970** [comment]
Hi all, thanks for your replies. 

I am attaching the url of our page to see the bug that occurs in chrome, when the users scroll down after the third news insert the first banner, then if the user scroll three more news appears the second banner, but if returns to the first one, this same dissapears.

Site url pre-pwa.ahora.com.ar

Cheers
Leonardo

**Comment by dvoytenko** [comment]
It'd seem that `shadowRoot.querySelector()` would definitely be a problem. `attachShadowDoc` API accepts the host element where it itself installs shadow root. Here's a small example: https://github.com/ampproject/amphtml/blob/master/examples/pwa/pwa.js#L245

**Comment by leonardorey1970** [comment]
Hi choumx how are you?, our implementation uses a different container each time that the banner is included, however when the second banner is printed the first one disappears.
Do you have any idea of another workarround that we can try to do it? can you guess if this bug will be included in their priorities to be solved soon?.

Sorry by my insistence, but we need to define this functionality, and any help is welcome.

Cheers
Leonardo
