### ISSUE TITLE
Refactor execOrDie in pr-check.js into a shared library

### ISSUE THREAD

**Issue by rsimha-amp** [ampproject/amphtml#9038]
We need to use execOrDie in build-system/tasks. Refactor execOrDie into its own js file that can be shared across directories.

**Comment by jridgewell** [comment]
@rsimha-amp Use (explicitly) "Fixes #ISSUE" or "Closes #ISSUE" to auto-close when merging.

**Comment by rsimha-amp** [comment]
@jridgewell I added an annotation to #9348, but the format was wrong.
