### ISSUE TITLE
amp-carousel: Dynamic slide content

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#9045]

**Comment by choumx** [comment]
Two things to do:
- [ ] Add support to `amp-carousel` to handle children with dynamic contents (e.g. `amp-list`, `template`)
- [ ] Add support to `template` to use bindable state as render data source

Context: [Design review doc](https://docs.google.com/document/d/1niL4oreE3GJHyqdpuCD7Zxb_zfNdScdHSFa2Z-AZ9gI/edit#), https://github.com/ampproject/amphtml/issues/8900#issuecomment-299038050

**Comment by choumx** [comment]
Moving to "New FRs" pending triage.

**Comment by aghassemi** [comment]
`amp-carousel v2` and `amp-script` are designed with this in mind.

**Comment by micajuine-ho** [comment]
This has been addressed in amp-carousel v2.
