### ISSUE TITLE
Check viewer visibility for CORS in xhr.js

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#9048]
- Would help catch privacy issues due to CORS XHR during prerender.

/cc @dvoytenko @jridgewell

**Comment by jridgewell** [comment]
I'd say P1?

**Comment by dvoytenko** [comment]
P1 would make sense. Updated. To clarify: this would be only a dev assert to start with. Specifically asserting any non-current requests.

E.g. for a x.cdn.ampproject.org, we can allow x.cdn.ampproject.org and cdn.ampproject.org. Etc.

**Comment by jridgewell** [comment]
Pulling this as my Fixit.
