### ISSUE TITLE
autoplaying video: using custom controls (e.g. play(), pause() actions) are not considered user interaction.

### ISSUE THREAD

**Issue by richardrabbat** [ampproject/amphtml#9055]
**Please only file bugs/feature requests for AMP here.**

## What's the issue?

Paused video with autoplay attribute starts playing after switching browser tabs, should stay 
paused according to docs:

“if the user has interacted with the video (e.g., mutes/unmutes, pauses/resumes, etc.), and the video is scrolled in or out of view, the state of the video remains as how the user left it. For example, if the user pauses the video, then scrolls the video out of view and returns to the video, the v..."

This behavior only affects video that has been set to autoplay

## How do we reproduce the issue?

1. add an amp-video that has autoplay
2. add custom control to pause it
3. it starts playback
4. click to pause it
5. go to a different tab, and come back to the tab where it was paused
6. it plays, expected: it should be paused

## What browsers are affected?

All browsers

## Which AMP version is affected?

We believe it was it broken. Using latest AMP version

**Comment by aghassemi** [comment]
@richardrabbat Thanks for reporting. Looks like currently using `custom controls` to interact with autoplaying video is not considered a user action (wrongly) same way tapping the video it. They should be however.
