### ISSUE TITLE
Web worker CSP errors on publisher domains

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#9057]
'web-worker' experiment can cause CSP errors for pages using `amp-bind` served on publisher domains. We should do either/both: 
- Instruct publishers using `amp-bind` to add `default-src: blob:` directive to their CSP policy, as AMP and Cloudflare caches currently do.
- Add fallback if web worker creation is blocked by CSP.

Note that [`worker-src` directive only works in Chrome](https://www.google.com/url?sa=D&q=https%3A%2F%2Fdeveloper.mozilla.org%2Fen-US%2Fdocs%2FWeb%2FHTTP%2FHeaders%2FContent-Security-Policy%2Fworker-src%23Browser_compatibility).

/cc @cramforce

**Comment by cramforce** [comment]
Since this is a new thing, putting a hint towards this into the docs seems best.
