### ISSUE TITLE
amp-app-banner: doesn't open in chrome ios

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#9077]
Repro:
open https://amphtml-nightly.herokuapp.com/examples/article.amp.html
clicking on the `Open in App` button doesn't open the deep link
/cc @ericlindley-g

**Comment by ericlindley-g** [comment]
Also may be repro'd on Firefox + Android

/cc @aghassemi

**Comment by muxin** [comment]
I'll create a separate issue for android firefox after verifying the repro.

**Comment by muxin** [comment]
FYI, I tested and verified that for android firefox, both the non-embedded and embedded cases work fine now.
