### ISSUE TITLE
Ads are sometimes unloaded immediately after loading

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#9082]
Reproducible when you scroll down fast and stop at the second ad. 
http://www.stanleycupofchowder.com/platform/amp/2017/4/26/15433196/bruce-cassidy-officially-named-head-coach-of-boston-bruins

Internal: b/37746311

**Comment by jasti** [comment]
CC @ampproject/a4a

**Comment by zhouyx** [comment]
Ad server hide themselves when get resize fail response.

**Comment by dvoytenko** [comment]
We research the reason. What happens is that a YieldMo ad is requesting a resize that's denied by AMP b/c the ad is in the viewport currently and cannot be resize w/o disruption. Based on that rejection, the ad hides itself. That by itself is WAI. However, the nuance here is that the ad actually asks to be resized to a smaller size, so the resize rejection appears to be benign and it could simply occupy a bigger space. Further, I believe, the ad requests a smaller size incorrectly. From what I can tell, the space it takes is correctly available, but it requests a somewhat smaller size.

The details: the given size is 500px. The ad's iframe is 482px and the menu iframe is 16px. The ad asks for 482px while ignoring its menu's height.

My recommendation would be for the ad to tolerate denied size changes if the available size is bigger than requested.

/cc yieldmo-rao

**Comment by jasti** [comment]
Actually CC @yieldmo-rao

**Comment by yieldmo-rao** [comment]
Cool! Thanks for the update and solution @jasti and @dvoytenko . @harquail , FYI.

**Comment by harquail** [comment]
@yieldmo-rao Making a Yieldmo ticket for the two issues: 1. format resize request does not account for adChoices iframe height.  2. We should not fail on rejected resize change if format's body fits within window.innerHeight and window.innerWidth is greater than the minimum format width.

It may be that we are accounting for format size + adChoices size + margin on resize failure, but only accounting for format size when requesting resize.

(internally FS-3318)

Thanks for bringing this to our attention!

**Comment by aghassemi** [comment]
I also investigated this before I saw this issue. Vast majority of Ads on ABC News disappear because of this. (I almost reverted our release thinking we are the cause). This seems fairly a high priority issue to fix, no?

**Comment by yieldmo-rao** [comment]
We've got a workaround on our end that is set to release tomorrow in the AM. I'll post here once that is done.

**Comment by yieldmo-rao** [comment]
@jasti @aghassemi this has been launched. Just spot checked on a few websites, and the ad renders within the larger space without flickering and disappearing. Please let me know if you folks see the same behavior (please note: cache invalidation on our end might take up to 30 mins).

**Comment by aghassemi** [comment]
Thanks! Verified
