### ISSUE TITLE
amp-bind does not replace the video when amp-bind is used to bind to <source>

### ISSUE THREAD

**Issue by richardrabbat** [ampproject/amphtml#9085]
**Please only file bugs/feature requests for AMP here.**

## What's the issue?

One of our video elements has multiple video sources (primary and fallback)
we want to use amp-bind to replace the video src in <source>
When we implement it, the video src is successfully replaced, but the video still displays the old video source and the new video is not loaded

Briefly describe the bug/feature request.

## How do we reproduce the issue?

1. create an amp-video with multiple sources
2. replace a src url with a new src url for the mp4
3. expect the new video to start playing 
4. result is that the old video keeps playing

## What browsers are affected?

Tested on Chrome

## Which AMP version is affected?

experimental version that has amp-bind support

Note that this bug is slightly different in the code example from https://github.com/ampproject/amphtml/issues/9055
because the amp-video src is replaced in that example, not the one from <source>

**Comment by choumx** [comment]
One more. 😄 

/to @kmh287 /cc @aghassemi

**Comment by aghassemi** [comment]
Haven't tests it but we may need to call `video.load()` after `src` change to fix this issue.

On a related now, we should never support bindable `src` on `<source>` per W3C:

> Dynamically modifying a source element and its attribute when the element is already inserted in a video or audio element will have no effect. To change what is playing, just use the src attribute on the media element directly, possibly making use of the canPlayType() method to pick from amongst available resources. Generally, manipulating source elements manually after the document has been parsed is an unncessarily[sic] complicated approach.

**Comment by kmh287** [comment]
@richardrabbat Are you changing the `src` on the `amp-video` element or on one of its `<source>` children?

**Comment by kmh287** [comment]
Some things we can do here: 

1. Forbid binding to `src` and `type` on `<source>` elements entirely and only allow changes to `amp-video`'s video source by mutations on its `src` attribute
2. Do everything in 1 AND  add support for canPlayType somehow in bind
3. Add special casing for `<source>` elements in to bind that figures out which `<source>` to use and notifies the parent element accordingly.

Thoughts, @choumx @aghassemi ?

**Comment by richardrabbat** [comment]
FYI, we have multiple sources of video. 
We prefer WebM, but allow fallback on MP4 for Safari for example. 
We also have an HD version of the video for people looking to play very high res (on newer devices)

Our need for amp-bind is for one of these 2 usecases on our page:
- we change the src to toggle the video source to either HD/non-HD 
- we toggle the mp4 to a video mp4 playing backwards

the HD state is in the cookie so we remember your bandwidth preference.
the reverse is not

we've been doing this in JS for a while
If we lose the ability to specify/replace src in <source>, we'll have to resort to JS

Feels like the W3C section is advisory

**Comment by aghassemi** [comment]
@richardrabbat I assume toggling `HD` has the additional requirement of seeking to the previous position in the timeline. To support these cases, we may need a different approach such as allowing several source groups and using bind to switch between them. 

Something like:
```
<amp-video source-group="sd-forward" [source-group]="isHD ? 'hd' : 'sd' + '-' + isBackward ? 'backward' : 'forward'" id="myVideo">

  <amp-video-source-group [keep-position]="keepPosition" id="sd-forward">
      <source src="sd-movie.mp4" type="video/mp4">
       <source src="sd-movie.ogg" type="video/ogg">
  </amp-video-source-group>

  <amp-video-source-group [keep-position]="keepPosition" id="hd-forward">
      <source src="hd-movie.mp4" type="video/mp4">
       <source src="hd-movie.ogg" type="video/ogg">
  </amp-video-source-group>

  <amp-video-source-group  [keep-position]="keepPosition" id="sd-backward">
      <source src="sd-backward-movie.mp4" type="video/mp4">
       <source src="sd-backward-movie.ogg" type="video/ogg">
  </amp-video-source-group>

  <amp-video-source-group [keep-position]="keepPosition" id="hd-backward">
      <source src="hd-backward-movie.mp4" type="video/mp4">
       <source src="hd-backward-movie.ogg" type="video/ogg">
  </amp-video-source-group>

</amp-video>

<input type=checkbox 
       on="change:AMP.setState({isHD: event.checked, keepPosition: true}})>HD</input>
<input type=checkbox 
       on="change:AMP.setState({isBackwards: event.checked, keepPosition: false}})>Play Backwards</input>
```

**Comment by richardrabbat** [comment]
this would be amazing. love it

**Comment by aghassemi** [comment]
@kmh287 @choumx  I am taking this issue to be part of video work. For now I recommend not allowing `src` changes on `source` via bind.

@ericlindley-g video related FR for prioritization.

**Comment by choumx** [comment]
There's a similar FR for dynamically changing the number of images in an `amp-carousel` (#8921, https://github.com/ampproject/amphtml/issues/4626#issuecomment-279108353). @camelburrito actually suggested a similar "grouping" markup for `amp-carousel`. 

One approach we discussed that may solve the general case is templating children (not necessarily with `amp-mustache`). Create `<source>` elements templated from some JSON (`amp-bind` state). This also has the benefit that we don't need to know the number of groups/children at page load.

**Comment by ericlindley-g** [comment]
FYI: Would be great to fix, but adjusting the priority on this for now, since it hasn't been addressed in a bit.

**Comment by krishhnaa** [comment]
It would be amazing if the issue is fixed

**Comment by TrekSoft** [comment]
What about for amp-audio? Doesn't seem like it is supported by amp-bind so I was hoping amp-bind on source would work for it.
