### ISSUE TITLE
RDFa in AMP

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#9091]
Comments below are an update to this issue:
https://github.com/ampproject/amphtml/issues/4919

Thank you @Gregable and @honeybadgerdontcare for progress with RDFa support.

From our perspective, there are two remaining issues: support for `rel=""` and `rev=""`

Consider this structure:
```
<section id='Sponsor' about='[this:]' rel='dcterms:hasPart' rev='dcterms:isPartOf' resource='[this:#Sponsor]'>
  <h2 about='[this:#Sponsor]' property='dcterms:subject' rel='dcterms:contributor'>Sponsor</h2>
    <section id='Sponsor-name' about='[this:#Sponsor]' rel='dcterms:hasPart' resource='[this:#Sponsor-name]'>
      <div about='[this:#Sponsor-name]' typeof='foaf:Person' property='foaf:name'></div>
    </section>
</section>
```

According to the current validator, we can successfully declare `about=""`, `resource=""` and `property=""`.

We also can declare types such as:
```
<body
   prefix='
     schema: http://schema.org/
     biblio: http://purl.org/net/biblio#
     bibo: http://purl.org/ontology/bibo/
     this: http://www.domain.com/public/organization/umsl/preso/linked-data#'
   about='[this:]' 
   typeof='
     foaf:Document
     sioc:Post
     biblio:Paper
     bibo:Document
     prov:Entity'
>
```
That is good!

`rev=""` is not essential, but `rel=""` is very useful for building graphs of related terms.

Should we provide additional examples that demonstrate the importance of `rel=""`?
What else can we do to help here?

/jay gray

**Comment by honeybadgerdontcare** [comment]
@Gregable  Per [comment](https://github.com/ampproject/amphtml/blob/master/validator/validator-main.protoascii#L1117) on `a` tag's `rel` attribute, we'll need to blacklist some values for `rel`. We should do a second review that we've covered all values that need to be blacklisted for other tags. I don't see any issues with allowing `rev`.

**Comment by jaygray0919** [comment]
@honeybadgerdontcare Can we help "white list" `rel` values?
Currently, all of our `rel` values are openly-defined ontologies, their `classes` and their `properties`.
One source we use extensively is Wikidata and roughly 200 of its properties.
We can a comprehensive list if helpful.

/jay

**Comment by Gregable** [comment]
Hi @jaygray0919, let's figure this out.

`rel=` attributes on `<link>` and `<a>` tags have been a challenge. 

They are commonly used for semantic-only annotations by a wide variety of various useragents and those usages are ignored by browsers. See [old validator rules](https://github.com/ampproject/amphtml/blob/ab51b551b38c4e26f8bcca5c979751d83168ddee/validator/validator.protoascii#L1100) for a snapshot in time where we were trying to build a whitelist of common uses. This whitelist turned out to be fairly expensive to maintain.

At the same time, browsers also use certain attribute values to have specific behavior. `<link rel=stylesheet>` for example. The set of all attribute values which browser have mapped to some behavior isn't terribly well documented, which makes a blacklist approach a little dangerous.

I'd prefer a whitelist approach as these are more strict, but only if the whitelist is reasonably maintainable.

As a strawman proposal, I'm wondering if perhaps we should continue to use a blacklist for `rel=` attributes on `<link>` and `<a>` tags, but a whitelist of these for all other tags. 

Alternatively, just using the existing blacklists for `rel` attributes globally would probably work.

**Comment by SchnWalter** [comment]
I think that a generic prefix white-list could solve the issue for rel and rev attributes, since they are allowed on all HTML5 elements:

> [HTML+RDFa 1.1 - Second Edition -- 4. Extensions to the HTML5 Syntax](https://www.w3.org/TR/rdfa-in-html/#extensions-to-the-html5-syntax)
> * For the avoidance of doubt, the following RDFa attributes are allowed on all elements in the HTML5 content model: `@vocab`, `@typeof`, `@property`, `@resource`, `@prefix`, `@content`, `@about`, `@rel`, `@rev`, `@datatype`, and `@inlist`. All other attributes that RDFa may process, such as `@href` and `@src`, are only allowed when consistent with the content model for that element, as defined in the HTML5 
  

For example, if you set `schema:` as a prefix for shema.org values:

    <html amp prefix="schema: http://schema.org/ ...">

you could then just use the RDFa rel and rev attributes like:

    <span rel="schema:author">{{ author_info }}</span>
    <div rel="schema:publisher">{{ publisher_info }}</div>

And then, a generic global prefix validator would be simple to implement and it would not need an exhausting white-list of possible values. It would just be an extra requirement:

    RDFa requires the use of prefixes for each vocabulary

Which I find more intuitive.

**Comment by Gregable** [comment]
So the proposal would be to allow a `prefix` attribute on `<html>` which can be any string prefixed with `schema:` and also allow a `rel` or `rev` attribute prefixed with `schema:` as well, correct?

That sounds pretty reasonable.

**Comment by SchnWalter** [comment]
Actually, RDFa can be used with any number of vocabularies. So as long as there is a `prefix` attribute on the HTML tag with defined vocabularies, then you could use any of those vocabularies for values of all RDFa attributes.

For example here we define 3 prefixes for 3 different vocabularies:
* `dc` for [Dublin Core Metadata Terms](http://purl.org/dc/terms/)
* `foaf` for the [Friend of a Friend Vocabulary](http://xmlns.com/foaf/0.1/)
* `og` for the [Facebook's Open Graph protocol](http://ogp.me/ns#)
* `schema` for the [The Schema.org vocabulary](http://schema.org/)
```
<html amp prefix="dc: http://purl.org/dc/terms/ foaf: http://xmlns.com/foaf/0.1/ og: http://ogp.me/ns# schema: http://schema.org/">
```
You can find more vocabularies here: https://www.w3.org/2011/rdfa-context/rdfa-1.1 (and probably many more, if you search the web)

And once you define a prefix, you just need to use it as prefix for attribute values, as in my previous example.

NOTE: The RDFa prefixes can be added to any element in the DOM and they are scoped, but this will only complicate the validation:
https://www.w3.org/TR/rdfa-syntax/#scoping-of-prefix-mappings

**Comment by honeybadgerdontcare** [comment]
If one was to select a number of prefixes to cover a wide range of uses, what set of prefixes would cover the majority of use cases? Is there any data available for what prefixes are used most often in the "wild"?

**Comment by Gregable** [comment]
I don't want this to become an RDFa validator as well, if we can help it. I want to implement just enough to support RDFa without attempting to catch all possible errors in RDFa.

If we were to go through the effort of generically parsing the `prefix` attribute vocabulary and then allowing `rel`/`rev` values with that prefix, we are effectively allowing any `rel`/`rev` containing the `:` character in every space-separated component of the attribute.

Let's do the following:

- Allow `prefix` attribute on `<html>` tag with any value.
- Allow `rev` attribute on any tag with any value.
- Take our blacklist currently used for `<a rel=` and `<link rel=` and use it globally to allow `rel` on any tag as long as the values don't match that blacklist which contains:

  - canonical
  - components
  - dns-prefetch
  - import
  - manifest
  - preconnect
  - prefetch
  - preload
  - prerender
  - serviceworker
  - stylesheet
  - subresource

**Comment by SchnWalter** [comment]
On the previously [linked page](https://www.w3.org/2011/rdfa-context/rdfa-1.1), you can find this list:

> Widely used Vocabulary prefixes based on the [vocabulary usage on the Semantic Web](/2010/02/rdfa/profile/data/)

| Prefix | URI | Description | For more details see |
| --- | --- | --- | --- |
| cc | http://creativecommons.org/ns# | ccREL | [ccREL: The Creative Commons Rights Expression Language](http://www.w3.org/Submission/2008/SUBM-ccREL-20080501/) |
| ctag | http://commontag.org/ns# | Common Tag Ontology | [Common Tag Specification](http://commontag.org/Specification) |
| dc | http://purl.org/dc/terms/ | Dublin Core Metadata Terms | [DCMI Metadata Terms](http://dublincore.org/documents/dcmi-terms/#H2) |
| dcterms | http://purl.org/dc/terms/ | Dublin Core Metadata Terms | [DCMI Metadata Terms](http://dublincore.org/documents/dcmi-terms/#H2) |
| dc11 | http://purl.org/dc/elements/1.1/ | Dublin Core Metadata Element Set, Version 1.1 | [Dublin Core Metadata Element Set, Version 1.1](http://purl.org/dc/elements/1.1/) |
| foaf | http://xmlns.com/foaf/0.1/ | FOAF | [FOAF Vocabulary Specification](http://xmlns.com/foaf/spec/) |
| gr | http://purl.org/goodrelations/v1# | GoodRelations Ontology | [GoodRelations Language Reference](http://www.heppnetz.de/ontologies/goodrelations/v1) |
| ical | http://www.w3.org/2002/12/cal/icaltzd# | iCalendar terms in RDF | [iCalendar terms in RDF](http://www.w3.org/2002/12/cal/icaltzd#) |
| og | http://ogp.me/ns# | Facebook's Open Graph protocol | [Open Graph Protocol](http://ogp.me/) |
| rev | http://purl.org/stuff/rev# | RDF Review Vocabulary | [RDF Review Vocabulary](http://vocab.org/review/terms.html) |
| sioc | http://rdfs.org/sioc/ns# | SIOC Core Ontology | [SIOC Core Ontology Specification](http://www.w3.org/Submission/2007/SUBM-sioc-spec-20070612/) |
| v | http://rdf.data-vocabulary.org/# | Google Rich Snippets' Vocabularies | [Rich snippets (microdata, microformats, and RDFa)](http://www.google.com/support/webmasters/bin/answer.py?answer=99170) |
| vcard | http://www.w3.org/2006/vcard/ns# | vCard in RDF | [Representing vCard Objects in RDF](http://www.w3.org/Submission/2010/SUBM-vcard-rdf-20100120/) |
| schema | http://schema.org/ | The Schema.org vocabulary | [Full Schema.org documentation](http://schema.org/docs/full.html) |

And the list looks good.

**Comment by SchnWalter** [comment]
Please note that most RDFa attributes use those prefixes, see [RDFa Core 1.1 - Third Edition -- 5. Attributes and Syntax](https://www.w3.org/TR/rdfa-core/#s_syntax)
* `about`
* `content`
* `datatype`
* `inlist`
* `property`
* `rel`
* `resource`
* `rev`
* `typeof`

These are excluded from the above list:
* `href` -- which only take resource identifiers as values (URIs/IRIs) as values
* `prefix`
* `src` -- which only take resource identifiers as values as values
* `vocab` -- which only take vocabulary resource identifiers as values as values

In the same section you can also find the syntax definition for the prefix attribute:
```
prefix
    a white space separated list of prefix-name IRI pairs of the form
        NCName ':' ' '+ xsd:anyURI
```

**Comment by Gregable** [comment]
@SchnWalter , how do you feel about my recommendation above to just move forward with a more relaxed set of rules here?

**Comment by jaygray0919** [comment]
We second the point that it's not AMP's job to validate RDFa (or JSON-LD). Google SDTT does that. IOHO (in our humble opinion) the change should be: allow `rel` and `rev` on an element. Our analysis indicates that `about`, `datatype`, `typeof`, `resource` and `content` are all AMP valid. Also, the AMP validator does not choke on vocabulary declarations, either in `<head>` or `<body>`

Also, we have no problem with @Gregable  **black list**

/jay

**Comment by SchnWalter** [comment]
@Gregable, I just realized that your suggestion works perfectly, and I can also confirm that jay's analysis regarding the other RDFa attributes being AMP valid.

So +1 for the allowing `rel` on any tag with a simple blacklist and just skip the parsing of the `prefix` attribute.

And I can also confirm that the vocabulary declarations, using either a `prefix` or `vocab` attribute, work on `<html>`, `<head>` or `<body>`

**Comment by Gregable** [comment]
Sounds like we have a plan then. The changes required are:

- [ ] Edit `validator/testdata/feature_tests/rdfa.html` to include some additional valid examples of `rel`/`rev`/`prefix`.
- Edit `validator/validator-main.protoascii` in two places:
  - [ ] For the tag `"html ⚡ for top-level html"`, add `attrs: { name: "prefix" }`
  - [ ] In the attr_list named `"$GLOBAL_ATTRS"`, add `attrs: { name: "rev" }` and an attr for `rel` with the additional parameter of `blacklisted_value_regex` set to: 

```
"(^|\\s)("  # Values are space separated.
"canonical|"
"components|"
"dns-prefetch|"
"import|"
"manifest|"
"preconnect|"
"preload|"
"prerender|"
"serviceworker|"
"stylesheet|"
"subresource|"
")(\\s|$)"
```

Myself or @honeybadgerdontcare would be happy to implement these changes. However @jaygray0919 , @SchnWalter , if you are interested, I'd like to invite either of you to contribute the pull request yourself. I'm happy to review the changes and help out in any way.

A few pointers to the [Getting Started Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) and the section on [How to run validator tests](https://github.com/ampproject/amphtml/blob/master/contributing/component-validator-rules.md#test-output-files)

**Comment by jaygray0919** [comment]
Thanks for the plan @Gregable and @honeybadgerdontcare . We'll defer to you on the update. We'll share back RDFa examples after the plan is implemented. If there are nay further issues, we can discuss how to resolve those specific issues. @SchnWalter also will probably be on the look-out.

**Comment by jaygray0919** [comment]
FYI - the use case here is to define items that cannot be defined easily using schema.org and JSON-LD. Example items are foods, drugs and human bioactivity (genes, proteins, enzymes, adverse events). We need to use domain-specific ontologies to define our target items. @Gregable previously was helpful by allowing JSON-LD in `<body>`. With RDFa support we can complement the JSON-LD with expressive RDFa. Harvesters will parse and interpret the meaning of information even when it's split between JSON-LD and RDFa (when `identifiers` are **properly** deployed).

**Comment by SchnWalter** [comment]
I'll have some time for this task next week, if nobody gets to work on this until then.

**Comment by Gregable** [comment]
Awesome. I noticed the `prefix` attribute was already present, so this is even easier than I initially thought. I've updated the required changes above.

If you don't find time, let me know and I'll knock it out.

**Comment by Gregable** [comment]
Thanks @SchnWalter . 

FYI, the issue is closed, but validator releases typically end up with about 2 weeks before this goes live. I'll update this issue when that occurs.

**Comment by SchnWalter** [comment]
Thanks, I'm in no hurry, we are actually making our whole website as an AMP website, and we haven't added the magical `amp` attribute on the HTML tag, yet. :D

P.S. AMP Rules!!! Thank you for a great job!!!

**Comment by Gregable** [comment]
This should be live everywhere within an hour.
