### ISSUE TITLE
Create `amp-oembed` 

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#9093]
- [ ] creates a 3p iframe based on the response of an oembed URL
  - Ideally If embed result's HTML is already an iframe, we can use `amp-iframe` instead of a `3p iframe` so we do't end up with iframe in 3p iframe.
- [ ] handles resizing automatically when possible.

/cc @jpettitt @ericlindley-g

**Comment by ericlindley-g** [comment]
@aghassemi :  looks promising—do you have more context on the use-cases for this?

**Comment by jpettitt** [comment]
There are a couple of services https://iframely.com/ and http://embed.ly/ that provide a uniform oembed based API for embedding 3rd party content.  `amp-oembed` would enable publishers to use these services easily on AMP pages.  Iframely already supports amp via `amp-iframe` (append &oembed=amp to their iframe url)

**Comment by gotwig** [comment]
I would also welcome this.

**Comment by SchnWalter** [comment]
The oEmbed websites publishes a list of providers in a [JSON](https://oembed.com/providers.json) file, which could be used to validate URLs. This file can be updated by submitting PRs, see:

>
>  **7. Implementations** - https://oembed.com/#section7
>    **7.1. Providers**
> 
>    Providers are available programatically as a json file: http://oembed.com/providers.json.
> 
>    To add new providers, please fork [this repo](https://github.com/iamcal/oembed) on GitHub and add/modify providers/*.yml.

**Comment by aghassemi** [comment]
we created `amp-embedly-card` which covers a lot of the use cases here.
