### ISSUE TITLE
Responsive amp-image not centering when max-width is set

### ISSUE THREAD

**Issue by paper1111** [ampproject/amphtml#9114]
## Issue

The `amp-img`'s `layout` property is set to `responsive`. As it makes the image too big when the browser is wide, a `max-width` is set on the image. The image is also centered with `text-align`. But, the image no longer centers.

## Reproduce

[Complete working code in jsbin](https://jsbin.com/luvenehipa/edit?html,output)

1. Create an `amp-img` whose `layout` property is set to `responsive`
2. Set the `max-width` property of the image
3. Set `text-align` to `center`
3. Drag the browser wider and it will still not center, only staying to the left

AMP Version 1493417419433

**Comment by jridgewell** [comment]
Use `margin: 0 auto` on the element you're setting `max-width` on. https://jsbin.com/lalovo/1/edit?html,output
