### ISSUE TITLE
Ability to request multiple ads on a single ad request

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#9115]
At the moment all amp-ad implementations are only able to make a single ad request per ad slot. Larger publishers often like to correlate ad slots for ad roadblocks or competitive exclusions. This feature request is to allow a way for ad networks to do that.

**Comment by dpetrieldn** [comment]
Hi @jasti , in terms of comparing this behaviour to an existing GPT implementation, would this just be keeping the correlator the same for each request, running with Single Request Architecture (SRA), or a mixture of both?

Thanks

**Comment by jasti** [comment]
@dpetrieldn , @keithwrightbos will be posting an ITI on this in the next week or two with details. 
This will be only for the 'Fast Fetch' flow - so it will be an implementation similar to GPT but will not use the underlying GPT.js library.

**Comment by keithwrightbos** [comment]
beta now available for SRA.  Note the backend code does not yet support per creative AMP creative validation meaning AMP creatives do not get preferential render (but do render correctly within xdomain frame).
