### ISSUE TITLE
Amp-analytics Failed to execute 'matches' on 'Element'

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#9125]
```
Error: Failed to execute 'matches' on 'Element': '#shopee8636781.115184959' is not a valid selector.
    at Ma (https://cdn.ampproject.org/rtv/001493770802531/v0/amp-analytics-0.1.js:13:328)
    at https://cdn.ampproject.org/rtv/001493770802531/v0/amp-analytics-0.1.js:104:294
    at Sa.push.f.h.fire (https://cdn.ampproject.org/rtv/001493770802531/v0/amp-analytics-0.1.js:15:796)
    at HTMLDocument.R.xa (https://cdn.ampproject.org/rtv/001493770802531/v0/amp-analytics-0.1.js:108:385)
```
Failed at https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/analytics-root.js#L443

When the selector is not valid in amp-analytics, the above error occurs. It seems it should be handled in the catch block as user error but somehow it reported as dev error.

Sample url: https://biggo-com-tw.cdn.ampproject.org/v/s/biggo.com.tw/a/%E8%9D%B6%E8%B1%86%E8%8A%B1+%E7%A8%AE%E5%AD%90/?amp_js_v=9

**Comment by muxin** [comment]
@dvoytenko Could you help take a look?

**Comment by jridgewell** [comment]
https://github.com/ampproject/amphtml/issues/8917.
