### ISSUE TITLE
FR/Bug: amp-state should not be required by amp-bind

### ISSUE THREAD

**Issue by gilbox** [ampproject/amphtml#9136]
## What's the issue?

If you use `amp-bind` without `amp-state` you get the error

> The tag 'amp-state' is missing or incorrect, but required by 'amp-bind extension .js script'.

... but this is a silly requirement since it's legit to use `amp-bind` without `amp-state`, we do that [here](https://www.airbnb.com/amp/s/sf), for example.

Currently we work around the error by including an empty `amp-state`

## What browsers are affected?

tested on chrome

## Which AMP version is affected?

> Powered by AMP ⚡ HTML – Version 1493855940942

**Comment by choumx** [comment]
@gilbox Thanks for the report!

**Comment by honeybadgerdontcare** [comment]
The code fix is checked in but will take two to three weeks to reach production.

**Comment by Gregable** [comment]
This is live in the most recent release.
