### ISSUE TITLE
amp-ima-video: does not support more than one per page

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#9142]
Currently we can not have more than one `amp-ima-video` per page.

**Comment by adelinamart** [comment]
@shawnbuso any updates here? Thanks.

**Comment by shawnbuso** [comment]
I haven't started work on this yet - I plan on starting this after I get #8841 resolved because that will greatly simplify the code base.

**Comment by shawnbuso** [comment]
After brief testing it looks like this actually "just works" today - I think because each player is created inside its own iframe, we don't run into the issues we normally run into with using more than one player on the same page.

**Comment by aghassemi** [comment]
Closing

**Comment by shawnbuso** [comment]
There's a small hiccup here, and I'm not sure if/how it will affect things in production - right now the example page has buttons for "Play", "Pause", "Mute", "Unmute", and "Fullscreen". If I put more than one player on a page and a set of those buttons for each player, the buttons only affect the first player on the page.

In further testing, if I add "autoplay" to each of the players they do work as expected - each player auto-plays, and audio for that player only starts if I interact with that specific player. e.g. interacting with the second player only unmutes the second player and does not unmute the first player.

**Comment by aghassemi** [comment]
@shawnbuso did you change the `id` for the second one? works fine for me: https://codepen.io/aghassemi/pen/ZJeEKX?editors=1011

**Comment by shawnbuso** [comment]
Aha, yep, that'll do it. Thanks!
