### ISSUE TITLE
More comprehensive documentation of AMP lifecycle methods

### ISSUE THREAD

**Issue by taymonbeal** [ampproject/amphtml#9155]
In the wake of #9066, it's clear that we need a better understanding of the API contracts offered by the AMP lifecycle methods. In particular, it'd be nice to have documentation of all the ordering guarantees: which methods can be called before, during, and after which other methods?

**Comment by aghassemi** [comment]
Is the close enough? https://github.com/ampproject/amphtml/blob/master/src/base-element.js#L27

**Comment by taymonbeal** [comment]
On reflection, it might be, so I'll close this for now. I may reopen it later if it turns out that we need any specific things that are missing.
