### ISSUE TITLE
AMP social-share opens a blank window/tab

### ISSUE THREAD

**Issue by hindsc52** [ampproject/amphtml#9157]
## What's the issue?
We are just looking into implementing the amp-social-share component, this looks pretty fitting for our needs however, I have noticed that wen using some of the share tools i.e. Whatsapp, email etc on a non mobile device that blank windows/tabs open when clicking the share icon.  We are soon to be redirecting users from the canonical page to the AMP version of that page and this means desktop users will start to see our AMP pages and this issue is present on any non-mobile device.

## How do we reproduce the issue?
This can be re-produced in the [AMP By Example Playground](https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fcomponents%2Famp-social-share%2Fsource%2F)
1. On a non-mobile device, click the email icon
2. On a non-mobile device, click the whatsapp icon

It looks like the share tools all open with a href and target value of `_blank` a suggestion would be to use `_self` which should stop the blank windows from opening. However this would need to configureable as for instance Facebook and twitter should still open the the new tab/window

## What browsers are affected?
All non-mobile devices, not browser specific

## Which AMP version is affected?

Version 1493923946479

**Comment by jridgewell** [comment]
I believe this was done because certain mobile browsers do not support opening the app using self links... But maybe it was just to keep the user on the page?

**Comment by aghassemi** [comment]
Correct. iOS has complicated rules for what the target needs be. For instance, for `mailto:` iOS only works if target is `_top` even `_blank` doesn't work in that case.

If we allow override for `_self` we would need to restrict it to only certain platforms.
/cc @ericlindley-g

**Comment by hindsc52** [comment]
So am I right in thinking that right now we cannot get around the blank tabs opening when on a non-mobile device?

**Comment by aghassemi** [comment]
@hindsc52 currently you can't. We would need to expose something like a `target` attribute so you can set it to `self` (and we would need to ignore `target` in iOS for certain types of links)
