### ISSUE TITLE
Enable Client-Hints by default?

### ISSUE THREAD

**Issue by igrigorik** [ampproject/amphtml#916]
If you provide the meta opt-in then we'll emit Width, DPR, and Viewport-Width headers that can be used by backends to optimize resources -- e.g. return scaled images based on specified width, etc.

More details: https://developers.google.com/web/updates/2015/09/automating-resource-selection-with-client-hints?hl=en

The opt-in is: `<meta http-equiv="Accept-CH" content="DPR, Viewport-Width, Width">`

**Comment by cramforce** [comment]
@jmarantz We discussed stuff like this yesterday. I suppose we'll go with a solution that works in Safari first.

**Comment by dvoytenko** [comment]
@cramforce @igrigorik But how much these hints will be proxy-able for AMP Cache? It seems this would be rather limited unless we also bake this into "Vary-By".

**Comment by cramforce** [comment]
The plan we discussed yesterday was to support

```html
<amp-img>
  <source type="image/webp" srcset="…">
  <source srcset="…">
</amp-img>
```

and let the client make the decision which one to download and have image URLs encode type and size.

We can also support `Vary-By`, though, for this case. Main issue is Safari non-support for the hints.

**Comment by dvoytenko** [comment]
If it's a client side solution - we can do this today. Client hits, I think, would be helpful if we did server-side/prescanner.

**Comment by igrigorik** [comment]
> But how much these hints will be proxy-able for AMP Cache? 

AMP cache should proxy the client hints down to the origin. Knowing the Width of the image resource on the server allows servers to deliver appropriately scaled images, etc. For other subresources (e.g. CSS) the server can elide unnecessary data based on advertised DPR, Viewport-Width. Lots of different use cases here. The server, in turn, responds with `Vary: <used hint>` to indicate that AMP cache should use said header's value as part of its cache key.

**Comment by adelinamart** [comment]
Hey,

The AMP community has been working nonstop to make AMP better, but somehow we've still managed to grow an enormous backlog of open issues.  This has made it difficult for the community to prioritize what we should work on next.

A new process is on the way and to give it a chance for success we will be closing issues that have not been updated in awhile.

If this issue still requires further attention, simply reopen it.  Please try to reproduce it with the latest version to ensure it gets proper attention!

We really appreciate the contribution! Thank you for bearing with us as we drag ourselves out of the issue abyss. :)
