### ISSUE TITLE
Consider some kind of dependency injection

### ISSUE THREAD

**Issue by taymonbeal** [ampproject/amphtml#9163]
Our (by which I mean A4A's) tests currently rely heavily on Sinon fakes of classes like `Xhr`. These tend to be fragile; a change to the internals of Fast Fetch (where it started calling `fetchJson` instead of `fetch`) meant rewriting all the tests to use new fakes. Also, some kinds of objects (like top-level functions and objects) are difficult or impossible to fake in this way. All of this makes test doubles really painful to work with.

Could it be feasible to have some kind of dependency-injection-esque setup instead? If a component depends on, say, `Xhr`, then in the real world it'd want to use the real `Xhr` service, but in tests it'd be desirable for the test author to be able to provide a test double, either from Sinon or a custom-written one for the test. As long as the test double conforms to a specified interface, the test should then be resistant to changes in the internal implementation details of the code under test.

**Comment by bradfrizzell** [comment]
+1

**Comment by aghassemi** [comment]
Dup of https://github.com/ampproject/amphtml/issues/5286 added your comments there.
