### ISSUE TITLE
Test doubles for the AMP lifecycle

### ISSUE THREAD

**Issue by taymonbeal** [ampproject/amphtml#9164]
Currently, our (A4A's) tests generally work by manually calling the AMP lifecycle methods of our components. Sometimes we get the invariants wrong. It would be a lot better if we had some kind of AMP test fixture that allowed us to create components of a specified type (and know what type they'd be; we've had a lot of difficulties with native elements where custom elements were expected) and to move to specified points in the AMP lifecycle (like layout time), calling any needed methods along the way.

**Comment by rsimha-amp** [comment]
Seems like something that automates the transitions between the states in https://github.com/ampproject/amphtml/blob/master/src/base-element.js might do the trick?

**Comment by rsimha** [comment]
Triage: This is worth keeping open.

**Comment by rsimha** [comment]
Unfortunately, Infra hasn't had the bandwidth to take this on thus far. Soliciting opinions from @ampproject/wg-runtime for whether a) this effort is still worthwhile and b) if one of y'all has better context for this and the cycles to implement it.

**Comment by choumx** [comment]
I think this is satisfied by an integration test with `runtimeOn: true`. My guess is a lot of early A4A tests were written as unit tests and manual invocation of lifecycle callbacks.

**Comment by rsimha** [comment]
> My guess is a lot of early A4A tests were written as unit tests and manual invocation of lifecycle callbacks.

Makes sense. Thanks for the context. Closing this out in favor of migrating existing unit tests to the correct test type: integration or E2E.
