### ISSUE TITLE
Support opt-out for native app banners in amp-app-banner

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#9168]
Passing on this request from developers to opt out of the native banner, and instead show custom UI for amp-app-banner in all contexts (including Safari on iOS and Chrome on Android).

Not sure what this would look like in practice (stripping meta tags at runtime after getting the relevant data?), but wanted to track this request either way.

/cc @muxin @aghassemi

**Comment by aghassemi** [comment]
deduping with https://github.com/ampproject/amphtml/issues/6411
