### ISSUE TITLE
amp-app-banner: detect `navigateTo` capability of the viewer before showing it on iOS

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#9170]
with https://github.com/ampproject/amphtml/pull/8291 we now expect viewer to support `navigateTo` so we can properly make `amp-app-banner` work in iOS embed case.

Not all viewers support `navigateTo` yet however, so we need to feature detect and not show the `app-banner` in iOS embed case if viewer does not support `navigateTo` (otherwise banner shows up and user tapping it does nothing which is not great)

b/35322742 is almost done which, when launched, would allow this.

@ericlindley-g Can we coordinate with other viewers to make sure when they add `navigateTo` they also add it to the list of capabilities?

/cc @muxin

**Comment by aghassemi** [comment]
b/35322742 likely will be in prod by May 17

**Comment by ericlindley-g** [comment]
@aghassemi  — absolutely: talking to other viewers now to add. May take a while, but the nice thing is that we won't be blocked on viewers releasing new features for a good chunk of them. (though this may break down in cases where you can't simply show/hide based on support — we may have to figure out more sophisticated fallbacks for future features :)

**Comment by aghassemi** [comment]
Verified that this is in prod now for SRP viewer
