### ISSUE TITLE
add ticks for when amp prerending is done and when user requests page to become visible

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/amphtml#918]
- [ ] tick when amp prerender is done (Generally tick when the first round of resource requests are done.)
- [ ] tick when user requests page to become visible
- [ ] tick 0 when user requests page to become visible and prerender is already done.
- [ ] otherwise tick when initial viewport is ready.

/cc @cramforce please correct any incorrect statements. thanks

**Comment by cramforce** [comment]
Made some edits to your comment. /creepy.
