### ISSUE TITLE
Validate amp-app-banner url in ios

### ISSUE THREAD

**Issue by muxin** [ampproject/amphtml#9180]
Validate the `app-argument` inside `<meta name="apple-itunes-app" ... >`

**Comment by aghassemi** [comment]
@muxin are you thinking runtime or validator?

**Comment by muxin** [comment]
runtime

**Comment by muxin** [comment]
Adding it to current sprint since it's trivial to implement

**Comment by aghassemi** [comment]
@muxin as discussed, we would definitely want the viewer to validate the Urls as a P1 (e.g. refuse to `nativeTo` potentially dangerous Urls), AMP runtime doing it should only be a secondary check (Still useful)
/cc @ericlindley-g @ericfs
