### ISSUE TITLE
Cleanup closed TODOs for videos

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#9184]
TODO(aghassemi, #5306) in /Users/dvoytenko/DNI/amphtml/css/amp.css
TODO(aghassemi, #4780) in /Users/dvoytenko/DNI/amphtml/src/service/video-manager-impl.js

**Comment by aghassemi** [comment]
I have a feeling you made an automated script to detect these?!  :)

**Comment by dvoytenko** [comment]
https://github.com/ampproject/amphtml/pull/9182
