### ISSUE TITLE
Cleanup closed TODOs related to in-a-box

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#9186]
TODO(lannka, #3449) in /Users/dvoytenko/DNI/amphtml/src/url.js
TODO(lannka, #6213) in /Users/dvoytenko/DNI/amphtml/src/service/viewport-impl.js

**Comment by lannka** [comment]
The 1st TODO is waiting for "not supporting IE11". Do we support IE11 still?
The 2nd TODO, did you add for me? Needs some clarification what needs to be done :-).

Is it really P1? I got many items in this sprint.

**Comment by lannka** [comment]
Downgraded to P2 and moved to next sprint

**Comment by dvoytenko** [comment]
IE11 is still supported. Next sprint is fine. But not further, since I'm trying to enable monitoring for everyone.

**Comment by lannka** [comment]
if we're going to support IE11 for a while, I will just remove the TODO and keep a comment.

**Comment by dvoytenko** [comment]
I agree. It's totally reasonable to state in comments that something is required due to IE11 support w/o any `TODO`. These are easy to find and correct once compatibility requirements change whether or not `TODO` is present :)

**Comment by lannka** [comment]
@dvoytenko can you clarify what needs to be done for the 2nd TODO?

**Comment by dvoytenko** [comment]
@lannka No idea :) Since neither of us knows, maybe it should just be removed?

**Comment by lannka** [comment]
happy to do :-)
