### ISSUE TITLE
Experiment "amp-bind" is disabled.

### ISSUE THREAD

**Issue by Traveller198** [ampproject/amphtml#9188]
When i tried using amp state it throws error that 'amp-bind' is disabled.Can anyone help me.Thnaks.

**Comment by aghassemi** [comment]
Hi @Traveller198 
`amp-bind` is an experimental feature and needs to be enabled before it works. You can do so by running `AMP.toggleExperiment('amp-bind')` on Browser Developer console. See https://www.ampproject.org/docs/reference/experimental for details about experimental features.

You can also signup for amp-bind origin trial for your site here: https://amphtml.wordpress.com/2017/04/19/test-amp-bind-on-your-site-with-an-origin-trial/
