### ISSUE TITLE
moderation of Facebook comments

### ISSUE THREAD

**Issue by littleMissAnstrengend** [ampproject/amphtml#9202]
## What's the issue?

I like to use the Facebook comments integration but without the possibility to use also moderate function i am not able to use it because we have no control about the comments on our website.
To use this function i need to connect my app id with the comments. 

## How do we reproduce the issue?

Without AMP you would the comments functions like this:

Integrate the SDK in body tag:

```
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
// here is already the app id
  js.src = "//connect.facebook.net/de_DE/sdk.js#xfbml=1&version=v2.9&appId=15199124547546675";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
```

code to place on the website:

`<div class="fb-comments" data-href="https://developers.facebook.com/docs/plugins/comments#configurator" data-numposts="5"></div>`

And to connect this comments with moderation function you only should add this code snippet in the head
`<meta property="fb:app_id" content="{YOUR_APP_ID}" />`

## Which AMP version is affected?

HTML – Version 1493855940942 h

**Comment by eduardogoncalves** [comment]
Here it's working:
Powered by AMP ⚡ HTML – Version 1493855940942 https://www.testesmegadivertidos.com.br/teste/23_megasena-quais-sao-meus-numeros-da-sorte-na-mega-sena.html

![Imgur](http://i.imgur.com/NbrigLt.png)

**Comment by littleMissAnstrengend** [comment]
And how you implemented it?

**Comment by eduardogoncalves** [comment]
Hi, are you already using [amp-facebook-comments](https://github.com/ampproject/amphtml/blob/master/extensions/amp-facebook-comments/amp-facebook-comments.md)?

I just have the **meta fb:app_id** in the `head`:
`<meta property="fb:app_id" content="1666669130310338"/>`
and load amp extension:
`<script async custom-element="amp-facebook-comments" src="https://cdn.ampproject.org/v0/amp-facebook-comments-0.1.js"></script>`

and in the body I have **amp-facebook-comments** component:
`<amp-facebook-comments width=300 height=200 layout="responsive" data-numposts="1" data-href="https://www.testesmegadivertidos.com.br/teste/23_megasena-quais-sao-meus-numeros-da-sorte-na-mega-sena.html">
</amp-facebook-comments>`

**Comment by littleMissAnstrengend** [comment]
Hi,

thank! Yes i use it already and it works fine. But then i tried to use the moderation tool and this didn't work for me. So i disabled the comments. I see no difference between your and my code. I am using siteleaf and jekyll, maybe it is an issue with this?

**Comment by jridgewell** [comment]
It looks like this might be better asked on StackOverflow, if it's working for @eduardogoncalves.
