### ISSUE TITLE
AMP PHP Contact Form Don't Redirect

### ISSUE THREAD

**Issue by cpacifico** [ampproject/amphtml#9206]
I have HTML form in AMP, with POST action; PHP file for emails use Sendgrid API. I was try headers response for Json redirect, but, don't works.

For this reason i applied JavaScript redirect (yes, i know, this generate error for AMP validation, but i need redirect to thanks page for track online conversions).

PHP file works fine, all emails are send it's, but whithout JavaScript redirect, only with div success or error for email send, only i see error for send email, but, contradictorily, all emails are send it's without problems LOL through Sendgrid API).

So, i need redirect the HTML contact form with correct PHP header Json response (without JavaScript), for track online conversions and validate correctly my AMP HTML source. In other case, i think to it's very useful make a correct redirect from PHP file after success submission (to i try redirect with header location in PHP, but, don't works...)

Any idea? I was posted the same issue (i don't know if it's a real issue or not, but i need help) in [Stackoverflow](http://stackoverflow.com/questions/43853357/amp-php-contact-form-dont-redirect-google-amp).

**Comment by jridgewell** [comment]
Hi @cpacifico: Looks like you're requesting a way to change the URL after user interaction. We have a request for just that in #8976, so I'm going to close this as a duplicate. Please feel free to comment in the other request.
