### ISSUE TITLE
Support for fallback poster and click-to-play behavior in amp-iframe

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/amphtml#921]
Discussed this with @cramforce: One issue I see with amp-iframe is that in the cases where it violates the positioning rules, it will break with no fallback. The request is to make amp-iframe behavior more predictable overall by being able to gracefully fall back to click-to-play behavior when it wouldn't show due to the position limitations.

For example, if amp-iframe won't show due to where it's positioned on the page, a fallback poster can be specified to show instead. Then, if the user clicks on this, the amp-iframe behaves more like the click-to-play element in that it can resize itself.

**Comment by cramforce** [comment]
Assigning to @sriramkrish85 as kind of a special case to click-to-play.

CC @dvoytenko as well. We need to discuss whether we want to implement this very important special case.
