### ISSUE TITLE
AMP DIV BLOCKS / SECTIONS

### ISSUE THREAD

**Issue by tassawarr** [ampproject/amphtml#9220]
AMP Sections/blocks could be a revolution in amp project. Like in bootstrap we use `<section></section>` tag . So i want to contribute to the `<amp sections >` .

**Comment by tassawarr** [comment]
@aghassemi I need your assistance about it.

**Comment by aghassemi** [comment]
@tassawarr could you please provide more details on what you have in mind? Is #7972 similar to you idea?

**Comment by tassawarr** [comment]
all i want to you see my idea (suggestion) and add the tag to amp html for the users to evaluate what their design :+1:  . My idea is about to have `sections` , `cards` and `columns` in `amp html` . Like the bootstrap has. Also i want to become the member of this organization too.

**Comment by aghassemi** [comment]
@tassawarr ampstart.com is AMP's CSS framework that also includes http://basscss.com/ (which similar to bootstrap has a Grid system for rows and columns, etc..) Please take a look there.

**Comment by tassawarr** [comment]
Sure i'll take a look in there.
