### ISSUE TITLE
copyAndSplice not available in the latest v0.1 of amp-bind

### ISSUE THREAD

**Issue by micyeung** [ampproject/amphtml#9222]
While using amp-bind, getting an error saying that copyAndSplice is not a supported function. See screenshots.
![laloynvj680cg80ema_1072_643](https://cloud.githubusercontent.com/assets/9668639/25854907/3bad3ec0-3504-11e7-894f-95de6db8c374.png)
![laloynvj2s0cfs0ema_1176_638](https://cloud.githubusercontent.com/assets/9668639/25854906/3ba9aa26-3504-11e7-83c1-5e76ed36a307.png)

## Which AMP version is affected?
1493855940942

**Comment by choumx** [comment]
/to @kmh287 Kevin can you take a look?
