### ISSUE TITLE
A4A Test Case silently failing

### ISSUE THREAD

**Issue by bradfrizzell** [ampproject/amphtml#9227]
```resumeCallback w/ measure required no onLayoutMeasure``` within test-amp-a4a.js never actually gets inside its then block. All the expects etc within are never executed. This includes the use of `.to.never.be.called`, which is not valid as `.never` is not a part of the framework.

**Comment by bradfrizzell** [comment]
I suspect that all of our tests that utilize a then block don't have any way of complaining if we never go inside the then block.

**Comment by jridgewell** [comment]
[Line 691](https://github.com/ampproject/amphtml/blob/master/extensions/amp-a4a/0.1/test/test-amp-a4a.js#L691) has to be returned.

**Comment by keithwrightbos** [comment]
Fixed in #9244
