### ISSUE TITLE
PushState support on scroll

### ISSUE THREAD

**Issue by shimonenator** [ampproject/amphtml#9251]
I've looked through the issues list and I couldn't find an existing implementation or feature request, but please point me in the right direction if it's already discussed somewhere. The closest I was able to find is #9128 but it solves another use case. 

I'd like to propose a feature that would allow you to update hash or page url on scroll or another similar action. Common examples could be scrolling through a sectioned document, and each section updating hash in the URL so when the URL is refreshed or shared, it would take you straight to that section. Another example is when multiple pages are lumped into a single page, and each section would update the page URL, for example when you scroll from the section about cats into the section about dogs the URL will be updated from `www.example.com/cats/` to `www.example.com/dogs/`.

**Comment by aghassemi** [comment]
related: https://github.com/ampproject/ampstart/issues/209 
@ericlindley-g we could create a small project around improving in-page navigation experience. (this issue, `.focus()`, navlink highlighting as user scroll) all sort of fit together.

**Comment by ericlindley-g** [comment]
Agreed — there's a nice set of features here that all circle in the same area (and are on the docket to take a closer look at soon). Thanks for the request, @shimonenator !

**Comment by aghassemi** [comment]
deduping with #10395
