### ISSUE TITLE
Design Review 2017-06-14 (video analytics, immersive video, amp-carousel iOS jitter)

### ISSUE THREAD

**Issue by mrjoro** [ampproject/amphtml#9256]
The AMP Project holds weekly engineering [design reviews](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md).  **We encourage everyone in the community to participate in these design reviews.**

Time: Wednesdays @ [1pm Pacific](https://www.google.com/?#q=1pm+pacific+in+local+time)
Location: [Video conference via Google Hangouts](https://hangouts.google.com/hangouts/_/google.com/amp-eng-desrev)

If you are interested in bringing your design to design review, read the [design review documentation](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md) and add a link to your design doc by the Monday before your design review.

When attending a design review please read through the designs *before* the design review starts.  This allows us to spend more time on discussion of the design.

If you are unable to make the 1pm Pacific time due to time zone issues but you have a design you would like to present please make a note of that and we will try to find a time that works.

**Comment by torch2424** [comment]
I'd like to present a design for: [Amp Sidebar v1](https://docs.google.com/a/google.com/document/d/13FNIL3YtF1GFn9Sl5ZuxnP4iA-kO61WNgIC_S4-5Kmk/edit?usp=sharing)

**Comment by aghassemi** [comment]
I like to talk about Video Analytics (Design in progress, will link to ITI here later today)

**Comment by wassgha** [comment]
I will share some updates on the immersive video project (will link to the slides)

**Comment by camelburrito** [comment]
I would like to talk about https://github.com/ampproject/amphtml/issues/9137 if we have time

**Comment by mrjoro** [comment]
Video Analytics

- maybe pause & ended can be combined into a single state enum vs. booleans
- there are some issues when using onunload events; we might have to live with analytics events not being triggered e.g. when the browser closes (a lot of stuff in this space works on a "best effort" basis)
- Malte would not build variables unless people are actually asking for them, e.g. video-seconds-played
- one reason it's valuable for 3P video players to implement this; video analytics lets you capture events in the scope of the entire page, which the current 3P video analytics may not be able to provide
- we should think about which of the analytics part are optional for the interface; we likely will need to because it might be very challenging for 3P video players to support certain parts of the interface but not others
- is session id PII?  no, it's just the video id and a random id

**Comment by mrjoro** [comment]
Immersive Video

- video placeholder
  - the main question is what to do when we exhaust all fallbacks
  - should we make the placeholder image part of the video interface?
  - take a canvas snapshot of the current frame when you start scrolling, maybe blur it?
- dismissing minimized video
  - is it a problem to show text indicating how to dismiss the video?  not a problem to add interface elements as long as we say this is how the docking feature works, though there are concerns about internationalization
  - dragging on AMP when it is shown in a viewer is a little bit weird because swiping is captured; can handle it like amp-carousel
  - swipe to dismiss is a common interaction so may be intuitive
  - either do what YouTube/other video providers do, or write a long description of why we think we know how video should be handled better than them (which we don't)

**Comment by mrjoro** [comment]
amp-carousel jitter on iOS

- Malte: the issue showing up on the home screen may be a red herring; new iOS is using WKWebView for home screen, current iOS is using UIWebView; so this may affect all apps using UIWebView
- Brave/FB/etc. use UIWebView (we think), so the new iOS version is not necessarily a fix for this issue
