### ISSUE TITLE
amp-ima-video: switch to `describes` for tests

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#9258]

**Comment by shawnbuso** [comment]
@aghassemi do you have any more info on what this means? I was looking for documentation on how to handle this but couldn't find anything - I see in the repo some instances of `describes.realWin` and `describes.sandboxed` but I'm not sure what the difference is or which should be used where.

**Comment by aghassemi** [comment]
I can take this one if you don't mind,I have a small project around the whole video tests.

**Comment by shawnbuso** [comment]
Sure, no prob - thanks!

**Comment by dvoytenko** [comment]
@aghassemi I will switch to describes as part of #10705. However, there are a lot of TODOs in tests and I have to skip 1-2 tests as well as I'm not sure how to make them work. The `imaVideo.js` uses `global` and `window` interchangeably and I think this is probably the issue. PTAL once I merge describes.
