### ISSUE TITLE
Facebook comments language

### ISSUE THREAD

**Issue by cvrlebg** [ampproject/amphtml#9263]
## What's the issue?

Hi, can you add new attribute for amp-facebook-comments, something like data-locale where we can add language code like on FB documentation page: [https://developers.facebook.com/docs/plugins/like-button#language](https://developers.facebook.com/docs/plugins/like-button#language)?

## How do we reproduce the issue?

This will be very useful for non-english sites.

Thanks!

**Comment by aghassemi** [comment]
Closing as dup of https://github.com/ampproject/amphtml/issues/9264
