### ISSUE TITLE
I will develop a component called amp-baidu-stats

### ISSUE THREAD

**Issue by pearlwang1106** [ampproject/amphtml#9265]
Dear AMPers:
I am a Baidu FE, today i received a demand to develop a component named amp-baidu-stats. 

amp-baidu-stats is a Baidu statistical component which is used to collect all kinds of business data that including communication's quantity, the number of clicks, conversion's number. The component will send the data to Baidu statistical open platform. After the users login, the data can be analyzed by customizing the report.

**Comment by rudygalfi** [comment]
Hello! We're interested to have support for Baidu stats in AMP. Have you looked at amp-analytics? This is the preferred approach for supporting page data collection. 

Cc @lannka

**Comment by lannka** [comment]
@pearlwang1106 pls take a look at [amp-analytics](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md). you're welcome to provide a configure for Baidu stats in [vendors.js](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/vendors.js)

**Comment by pearlwang1106** [comment]
#9363 When can AMP support baidu stats?

**Comment by jridgewell** [comment]
After merge, it will take roughly 2 weeks before it enters production.

**Comment by pearlwang1106** [comment]
2 weeks?!  A u kidding me? It's really too long.

**Comment by lannka** [comment]
@pearlwang1106 no kidding, since you just missed today's binary cut. So it will be in next Tuesday's cut, which will hit production one week after.

**Comment by pearlwang1106** [comment]
Too sad

**Comment by lannka** [comment]
@pearlwang1106 don't forget to get an item to this file: https://github.com/ampproject/docs/blob/master/content/docs/guides/analytics_amp/analytics-vendors.md

**Comment by pearlwang1106** [comment]
Got it @lannka

**Comment by pearlwang1106** [comment]
DONE see at: [https://github.com/ampproject/docs/pull/511](https://github.com/ampproject/docs/pull/511)
