### ISSUE TITLE
<amp-img> children of <amp-selector> don't load without user intervention

### ISSUE THREAD

**Issue by ruborg** [ampproject/amphtml#9267]
## What's the issue?

When an `amp-selector` container contains `amp-img` children, the images do not load until the user interacts with the page, for example with a tap, or by resizing the browser on desktop.

Furthermore, if the `amp-accordion` script is included in document head, even though it is not being used, then the problem does not occur, i.e. the images are loaded and rendered on page load.

## How to reproduce the issue?

See jsbin here: [http://jsbin.com/lumuvonanu/edit?html,output](http://jsbin.com/lumuvonanu/edit?html,output)

1. Load jsbin above
2. Observe images not loading
3. Resize browser
4. Observe images load and render
<br><br>
5. Reload jsbin above
6. Uncomment amp-accordion script so that it's included in page
7. Rerun jsbin 
8. Observe that image load and render

<br><br>
Note that the code is copied from this ampbyexample page, which contains the `amp-accordion` script, and so the issue does not occur on this page
https://ampbyexample.com/components/amp-selector/

## What browsers are affected?
Desktop: Chrome, Safari, Firefox, Opera on OSX
Mobile: Chrome, Opera, Firefox on Android

## Expected
1. `amp-img` inside `amp-selector `should load on page load
2. Inclusion of `amp-accordion` script should not affect the loading of any `amp-img` when no `amp-accordion` is used on page.

## Full code to reproduce
```
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <link rel="canonical" href="https://ampbyexample.com/components/amp-selector/">
  <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <!-- ## Setup -->
  <!--
    Import the amp-selector component.
  -->
  <script async custom-element="amp-selector" src="https://cdn.ampproject.org/v0/amp-selector-0.1.js"></script>
  <script async custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js"></script>
<!-- <script async custom-element="amp-accordion" src="https://cdn.ampproject.org/v0/amp-accordion-0.1.js"></script> -->
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
<style amp-custom>
amp-selector:not([disabled]) [option][selected]:not([disabled]) {
  outline-color: #b60845;
}
/* disables build-in browser highlights */
amp-selector *:focus {
  outline: none;
}
amp-selector[disabled],
amp-selector [disabled] {
  opacity: 0.5;
}
.divider {
  border-right: 2px solid #333;
  height: 40px;
}
</style>
</head>
<body>
  The <code>amp-img</code> images below should load when the page first page loads, but they don't, unless you interact with the page, for example if you
  <ol>
    <li>You resize browser/rotate device, OR</li>
    <li>Uncomment the amp-accordion script (which is otherwise unused) in the document head</li>
  </ol>
  
  <amp-selector layout="container">
    <amp-img src="https://ampbyexample.com/img/landscape_sea_300x199.jpg"  width="60" height="40" option="1"></amp-img>
    <amp-img src="https://ampbyexample.com/img/landscape_desert_300x200.jpg" width="60" height="40" option="2"></amp-img>
    <div class="divider inline-block mx1"></div>
    <amp-img src="https://ampbyexample.com/img/landscape_ship_300x200.jpg" width="60" height="40" option="3"></amp-img>
    <amp-img src="https://ampbyexample.com/img/landscape_village_300x200.jpg" width="60" height="40" option="4"></amp-img>
  </amp-selector>

</body>
</html>
```

**Comment by dvoytenko** [comment]
BREAK:
  works in : 011492571781980
  doesn't work: 011493083583453

**Comment by jridgewell** [comment]
This has been around since the initial version of `<amp-selector>` (and others). Downgrading to p1, with patch incoming tomorrow.

**Comment by dvoytenko** [comment]
I believe this example has been fixed and the fix is already in Canary.

**Comment by aghassemi** [comment]
Closing per:

> Correct (fixed by #9282), but the general fix is still pending.

**Comment by devignerforhire** [comment]
I see this is one is marked as fixed, but I'm getting the same behaviour as described in this issue. Amp-img loads fine on the default selected tab, but not on subsequent tabs. Once the browser is resized, the images are loaded. We're on amp 1901021931380.

**Comment by devignerforhire** [comment]
@aghassemi Hi Ali, can you confirm whether this has been fixed? We're experiencing the same issue as described above, using amp-accordion and amp-selector for our wip style guide (https://winefolly.staging.wpengine.com/style-guide/). If I can't get this working I'm going to have to remove the tabs/accordions and have everything stacked, which isn't ideal. TIA :)

**Comment by aghassemi** [comment]
@devignerforhire I can repro. Issue seems to be related to the `toggle` action only. Created https://github.com/ampproject/amphtml/issues/20640 to track. Meanwhile if you are blocked, you can use `amp-bind` to implement this and that does not suffer from this bug.

See https://ampbyexample.com/dynamic_amp/multi_page_flow/ for an example that's fairly close to what you want to do.

**Comment by vikasgupta011** [comment]
Nothing you have to do just change replacement amp js file.
