### ISSUE TITLE
Shall we generate cookie for Ad CID?

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#9268]
Code [here](https://github.com/ampproject/amphtml/blob/e00a3da988672d60fae47105c663793c1119e64a/src/ad-cid.js#L39) and [here](https://github.com/ampproject/amphtml/blob/e00a3da988672d60fae47105c663793c1119e64a/extensions/amp-analytics/0.1/cid-impl.js#L118) and [here](https://github.com/ampproject/amphtml/blob/e00a3da988672d60fae47105c663793c1119e64a/extensions/amp-analytics/0.1/cid-impl.js#L182) implies that we do not generate cookie for Ad CID. Is it a bug or working as intended?

@avimehta @cramforce @dvoytenko @rudygalfi

**Comment by avimehta** [comment]
WAI. The id is used for GA and Ads data joining and if there is no analytics tag on the page, Ads doesn't need to send it across.

**Comment by lannka** [comment]
Let amp-ad set cookie can potentially increase the linking coverage, imagine user visited pages without amp-analytics first. My understanding is that in non-AMP world, ads tag also write the cookie if it does not exist yet, right?

Also, I saw one other ad network is specifying a cookie scope: [AMP_ECID_EZOIC](https://github.com/ampproject/amphtml/blob/master/ads/_config.js#L259) which probably was an mis-understanding of this feature.

**Comment by lannka** [comment]
And if you read the [README](https://github.com/ampproject/amphtml/blob/master/ads/README.md#available-information), the `window.context.clientId` is something we persist for ad network.

@rudygalfi

**Comment by cramforce** [comment]
The current feature doesn't support writing a cookie. This could be changed, but the current user doesn't want it.

**Comment by lannka** [comment]
Then [README](https://github.com/ampproject/amphtml/blob/master/ads/README.md#available-information) is misleading.

> - `window.context.clientId` contains a unique id that is persistently the same for a given user and AMP origin site in their current browser until local data is deleted or the value expires (expiration is currently set to 1 year).
>   - Ad networks must register their cid scope in the variable `clientIdScope` in [_config.js](./_config.js). Use `clientIdCookieName` to provide a cookie name for non-proxy case, otherwise value of `clientIdScope` is used.
>   - Only available on pages that load `amp-analytics`. The clientId will be null if `amp-analytics` was not loaded on the given page.

**Comment by cramforce** [comment]
You mean to add a bullet point:

- A cookie if it is not present yet.

?

**Comment by lannka** [comment]
Or we can fix the behavior. Why don't we just write a cookie if it does not exist. I think it's valuable as ads in 3P frame will have problem to do cookie in safari.

Non-related finding: I saw we have 10 networks calling `context.clientId`, but only 3 configured `clientIdScope` in `_config.js`. Seems this is something few people doing right.

**Comment by cramforce** [comment]
I don't have a strong opinion. It would certainly be reasonable to change.

**Comment by lannka** [comment]
@rudygalfi @avimehta any opinion on this? The behavior is inconsistent on CDN and pub hosted domain, because on CDN ad network can always get an AdCID, but on pub hosted domain, it relies on a cookie written by amp-analytics, which is not always there.

**Comment by rudygalfi** [comment]
This can be restricted to just write cookies for ad networks that are used right (we don't write a 1P cookie for all ad networks unconditionally)?

**Comment by lannka** [comment]
we only write cookie if
- the ad network specified `clientIdScope`
- pub is using that ad network

**Comment by lannka** [comment]
@avimehta sounds good.

and we do plan to promote CID logic from amp-analytics into core #4898
