### ISSUE TITLE
PWA: url-replacements-impl.js:181 Uncaught TypeError: Cannot read property 'then' of null

### ISSUE THREAD

**Issue by bjalford** [ampproject/amphtml#9273]
When using amp shadowdom, we're seeing the error wnehn navigating around.

To replicate go to: https://www.standard.co.uk/news/london/cabaret-compere-told-she-deserves-to-be-raped-after-standing-up-to-vile-catcalling-at-white-city-a3536886.html?ines_tg=1
(note this will drop a cookie for ines_tg, you will want to delete after testing)

Click on a few links e.g. menu items and review consolw log. You'll see the following:

Id @ error.js:137
(anonymous) @ log.js:484
url-replacements-impl.js:181 Uncaught TypeError: Cannot read property 'then' of null
    at url-replacements-impl.js:181
    at url-replacements-impl.js:857
    at String.replace (<anonymous>)
    at Fe (url-replacements-impl.js:830)
    at re.f.expandUrlAsync (url-replacements-impl.js:660)
    at re.f.expandAsync (url-replacements-impl.js:598)
    at amp-analytics.js:567
    at <anonymous>

**Comment by bjalford** [comment]
//cc @choumx

**Comment by dvoytenko** [comment]
Fixed via #9284.
