### ISSUE TITLE
StringIndexOutOfBoundsException in Closure on Travis

### ISSUE THREAD

**Issue by taymonbeal** [ampproject/amphtml#9275]
The Travis build [failed](https://travis-ci.org/ampproject/amphtml/builds/231337393) on #9040 with a Java error.

**Comment by erwinmombay** [comment]
this is a closure compiler bug

see: http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Avar%2520test%2520%253D%2520%2560%250Ahello%255C0%250A%2560%253B%250Aconsole.log(test)%253B

**Comment by erwinmombay** [comment]
reported here: https://github.com/google/closure-compiler/issues/2488
