### ISSUE TITLE
No scrolling in iOS8 Safari

### ISSUE THREAD

**Issue by macstens** [ampproject/amphtml#9289]
## What's the issue?

When opening an amp site in Safari on iOS8 devices, there is no way to scroll down. This seems to affect all AMP sites and is not to be narrowed down to a single website.

## How do we reproduce the issue?

Open any desired amp website via the google search result list, for example:

[AMP Site 1](https://www.google.de/amp/s/www.11880.com/amp/branchenbuch/bonn/081645047Z3853372/stefan-grothues-steuerberater.html)

or

[AMP Site 2](https://www.google.de/amp/mobile.reuters.com/article/amp/idUSKBN1620FP)

Now try to scroll down - nothing happens. It's not affecting iOS9+ devices.

## What browsers are affected?

Only iOS8 (could not test previous versions) with Safari.

## Which AMP version is affected?

Cannot reproduce when this happened first. Affected version is 1494446565961

I managed to solve this behaviour with disabling following css rules in the developer tools (see attached screenshot):

```
html.i-amphtml-singledoc > body{
overflow: visible !important;
position: relative !important;
}

```
![amp-ios8-scrolling-bug](https://cloud.githubusercontent.com/assets/582506/25989041/dd3d087c-36fa-11e7-952a-f179e9a48bd7.png)

**Comment by jridgewell** [comment]
/to @dvoytenko, though I don't know if we specifically support iOS 8.

**Comment by dvoytenko** [comment]
With policy of N-2, indeed, AMP is not supposed to be launched on iOS8 anywhere. However, I do see it launched in Google Search. I'll discuss it with them. And I'll fix the bug as well for now.
