### ISSUE TITLE
gulp lint-fix command fails

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#930]
`Command failed: /bin/sh -c node_modules/eslint/bin/eslint.js {src,3p,ads,builtins,extensions,testing,test}/**/*.js gulpfile.js -c .eslintrc --fix --plugin google-camelcase`

Running it manually returns usage statement.

Lets run it on travis to avoid regressions.

**Comment by erwinmombay** [comment]
ack, yeah fixing it.
