### ISSUE TITLE
Keep travis log concise: hide successful link checks in travis log

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#9303]
We had effort to reduce the length of travis log: #6835 . 
We want to keep it short by only showing errors and summaries of passed tests.

Let's try to hide successful link checks, which is taking a lot spaces.
<img width="936" alt="screen shot 2017-05-12 at 9 40 06 am" src="https://cloud.githubusercontent.com/assets/8496897/26007820/ffe21f4c-36f6-11e7-925d-8790c159092b.png">

**Comment by jridgewell** [comment]
That's what I said. 😛

**Comment by rsimha-amp** [comment]
Okay! My assumption was that md file changes were rare, and this wouldn't affect most PRs. Happy to make the change.
