### ISSUE TITLE
Catalog actions and triggers to determine "trust" levels in AMP

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#9305]

**Comment by ericlindley-g** [comment]
Critical criteria for each action include the level of risk for bad UX associated with it, and for each event the associated "trust level" it should be given.

**Comment by cvializ** [comment]
Cataloged in this doc: https://docs.google.com/spreadsheets/d/1QnIxWMQLcNINaNGpHcMsSUt5_l9Q7_bvHVMwQfwyypg/edit#gid=0

**Comment by cramforce** [comment]
I think that submit and submit-success/error should inherit the intentionality of the event that triggered them. If the submit was caused by `tab` or a `keypress` then those events can also be high.
