### ISSUE TITLE
a4a: Provide ability to test creatives without running a local version of amphtml repo

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#9311]
It would be a useful feature for users to be able to test their A4A creatives without uploading them to DFP or running a local clone of amphtml repo, specially to test/demo experimental features which won't even validate (and therefore can not be submitted to DFP)

We should either allow  `<amp-ad type="fake" data-use-a4a="true">` work with prod binaries (but not validate as valid AMP) or come up with another mechanism .

**Comment by lannka** [comment]
@Gregable can we add a rule to disallow `<amp-ad type="fake">`? So that we can enable it in production but only for testing and demo purpose.

**Comment by aghassemi** [comment]
So I ended up with a custom build of binaries on firebase to be able to embed non-valid A4A creatives for demos on AMP-By-Example. Not planning to maintain that build however, hoping this feature can be added soon.

Few notes on how I think this should work based on this experience:

Let's assume a different format for this for simplicity:
`<amp-ad-fake-a4a src="Url">`

1. Whether Url is the same origin as parent or not, should make no difference.
2. Url should be able return HTML, not just JSON with creative/signature.
3. No signature needed, if there is a signature, validity is ignored.
4. As long as Url responses with `Access-Control-Allow-Origin` header, it should render as A4A. Only reason to fallback to x-origin should be `fetch` failing due to lack of `Access-Control-Allow-Origin`.
5. of course should never validate as valid AMP :)

**Comment by lannka** [comment]
Discussed with @aghassemi and @kul3r4 offline, we will introduce a AMP Ads Playground in ABE to address this #9966

**Comment by jasti** [comment]
Tracked separately.

**Comment by honeybadgerdontcare** [comment]
@lannka The validator already disallows any `id` attribute to begin with `i-ampthml-` as those are considered internal runtime `id`s. Perhaps you could reuse that for this case with something like `id=i-amphtml-fake-ad`.
