### ISSUE TITLE
Error compiling extensions/amp-sticky-ad/1.0/amp-sticky-ad.js

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#9325]
Build flaky:
```
Error compiling extensions/amp-sticky-ad/1.0/amp-sticky-ad.js
ENOENT: no such file or directory, open 'build/cc/extensions_amp-sticky-ad_1.0_amp-sticky-ad.js'
```

**Comment by zhouyx** [comment]
Should be related to #9042. I am thinking there's a race condition here on whether amp-sticky-ad-0.1 or amp-sticky-ad-1.0 gets built first. @erwinmombay Would you please take a look, I am pretty confused 😢

**Comment by zhouyx** [comment]
https://travis-ci.org/ampproject/amphtml/builds/231656087

**Comment by lannka** [comment]
We don't need to compile the same binary twice. Let's just copy 1.0 to 0.1 as an alias.

**Comment by rsimha-amp** [comment]
This issue is causing master to go red today. Taking a look.

**Comment by rsimha-amp** [comment]
Just noticed that @zhouyx is already working on this in #9587, so re-assigning.
