### ISSUE TITLE
Introduce examiner.js

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#9326]
Following discussion [here](https://github.com/ampproject/amphtml/pull/9260).

`examiner.js` is a js tool that's served at `https://cdn.ampproject.org/examiner.js` and executed when user turn on `#development=1` on an AMP page. 

It prints extra debug info to developers, in addition to `validator.js`, which prints format rules violations.

A main use case can be to leverage browser API [PerformanceObserver](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver) to monitor what 3P frames is exhausting resources and slowing things down.

@dvoytenko

**Comment by dvoytenko** [comment]
+1

I'd recommend maybe to load it under `#development=2` or such. Unless you believe it's a good info for page authors as well.

**Comment by lannka** [comment]
@dvoytenko my intention was to bring it up to content authors' attention. So they have an idea who are the 3Ps that are degrading theirs user experience.

**Comment by dvoytenko** [comment]
Cool. Then it looks great!
