### ISSUE TITLE
Support for time engaged since last timer trigger

### ISSUE THREAD

**Issue by msukmanowsky** [ampproject/amphtml#9337]
## What's the issue?

Hi @rudygalfi and team, we're looking to add engaged time support to the Parse.ly analytics tracker. Following #1296 and examples I'm seeing in the code, it seems that the recommended approach is to implement a timer trigger that uses a special request which appends `${totalEngagedTime}`.

Parse.ly's JavaScript tracker has an engaged time implementation that sends a "heartbeat" pixel every 10.5s which includes the total time engaged since page load and the amount of time engaged since the last heartbeat pixel. This greatly simplifies the server-side logic we have to do by allowing us to sum these increments.

In reviewing the analytics spec and available variable substitutions, I'm a stumped on how to reproduce "time engaged since last timer trigger" without a tricky server-side solution that tries to compute the delta between `totalTimeEngaged` on chronological pixels. Would you and the team have any suggestions on how to proceed?

**Comment by rudygalfi** [comment]
@msukmanowsky There's probably some syntax we could add to support this, but the question I have is whether that complexity in AMP would outweigh the server-side cost of getting an accumulated total and needing to compute differences. In other words, it seems like the data needed is available and it's just a question of how to get the derived data. Typically in AMP we prefer to take as much additional computation off the client side as possible.

In terms of a design, I'll outline some rough thoughts, although this would need a full design pass to be fully speced out.

One way you could approach this is to add a name to the `timerSpec`. Then, introduce a new variable that takes a parameter like `incrementalEngagedTime(timer-name)`. This variable would compute the delta according to the total being accumulated in `totalEngagedTime`, except that it would reset to zero with each timer pulse.

**Comment by msukmanowsky** [comment]
@rudygalfi completely understand the reluctance to place any additional computational effort on the client. We debated this internally at Parse.ly in our non-AMP design but decided that computing the deltas server-side would require some visitor + url state map across all our customers that wasn't worth the effort compared to clients maintaining this state on their own.

I think your initial proposal sounds great and is directly in-line with what we were hoping.

Thanks for the quick response and let us know if you need any other feedback.

**Comment by rudygalfi** [comment]
@msukmanowsky We're going to need to schedule this along with other things we have planned. I want to know if this is blocking you and if you'd be open to implementing this so that it happens faster?

**Comment by msukmanowsky** [comment]
Very open to that, @rudygalfi. I'll take a look at this next week and will ping if I have any questions.

**Comment by msukmanowsky** [comment]
Just a heads up @rudygalfi - on vacation this week and will be looking in on this next week (got my dates mixed up).

**Comment by akgilbert** [comment]
Hello from Slate!  I was reading the Parsely documentation about how different distribution platforms are counted and stumbled on this ticket.  I'm really happy to see that there is movement in getting Engaged Time tracked in Google Analytics.  Have there been any updates since June?

**Comment by rudygalfi** [comment]
As far as updates: Haven't had time to address this. @msukmanowsky any update on your end? Before we start developing code, we should validate the approach I outlined with @lannka. 

@akgilbert This issue isn't tracking engaged time for Google Analytics per se. AMP already supports a cumulative engaged time metric via [`${totalEngagedTime}`](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#total-engaged-time). If you're looking to integrate with Google Analytics, I think you'll need to figure out a way to stuff this variable into a custom dimension combined with an appropriate event. (Page exit would be the best event, but I don't believe Google Analytics transmits such an event.) In addition, Google Analytics also doesn't natively support a heartbeat event that transmits data on regular intervals. Have you developed your own version that integrates with Google Analytics? (If so, then maybe this issue could help, but we should discuss further.)

**Comment by msukmanowsky** [comment]
Haven't had time for this on our side. Going to try to shore up some people on our side in the next month or two.

**Comment by cwisecarver** [comment]
Hey @rudygalfi! I'm going to be picking this up from Mike. We had a chat about it this morning and I spent most of today looking through the AMP codebase to get familiar with the analytics code.

Outside of AMP our heartbeat requests that we use to track engaged time pass along a `tt` parameter which, I believe, is the equivalent of totalEngagedTime and an `inc` parameter which AMP Analytics doesn't seem to have an analog for at the moment. It represents the engaged time since the last heartbeat.

I believe it's possible to add a "heartbeat" trigger with a timerSpec and a heartbeat request that passes the `totalEngagedTime` variable with the existing AMP codebase.

It looks like the interval seconds is already being calculated in order to build the cumulative `totalEngaged` time in the `ActivityHistory` class. In the `push` function could we just expose the result of `findEngagedTimeBetween` as a variable accessible inside the vendors.js?

**Comment by cwisecarver** [comment]
@lannka @rudygalfi Just FYI, I got #12141 finished. The linter is passing and so is the test suite. We also got the CLA signed. It should resolve this issue and it's based on the approach discussed in the comment above. Please let me know if there's any changes you'd like me to make. Thanks!

**Comment by akgilbert** [comment]
Just commented on the PR.  Looks like this is moving along!  This will be a BIG help to Slate's reporting.  Thank you all who've been involved with this.

**Comment by msukmanowsky** [comment]
Sorry for the delay @akgilbert! Hopefully we'll be able to get this out soon with the help of the AMP team :).

**Comment by lannka** [comment]
An update: 

The implementation in #12141 have an [issue](https://github.com/ampproject/amphtml/pull/12141#discussion_r155675042) and will not work as expected when user has different analytics vendors on the page trying to read the increments.
To address that, we will need a much bigger change in amp-analytics. But before that, please allow me to revisit the original requirement, see if there is any chance to work around that.

> This greatly simplifies the server-side logic we have to do by allowing us to sum these increments.

Is this the major use of those increments? If you sum up to get the total engaged time, how about you send a ping like this instead:

```
&totalEngagedTime=${totalEngagedTime}
&currentTimestamp=${timestamp}
&pageViewId=${pageViewId}
&clientId=${clientId}
```

where `clientId` and `pageViewId` should uniquely identify the current page view.
at server side, after listing all the pings of the same page view, you can pick the one with latest `timestamp`, and use its `totalEngagedTime`.

You might probably discussed this approach, but would that work?

**Comment by cwisecarver** [comment]
@msukmanowsky What do you think? I could go back to @rudygalfi's [original suggestion](https://github.com/ampproject/amphtml/issues/9337#issuecomment-302148736) and try implementing that. It seems like that would solve all our problems.

**Comment by msukmanowsky** [comment]
@lannka the "delta" increments are something we require since we query for engaged time in buckets as small as 5 min and as large as 1 day. It's less important for us to know the total time spent on a URL and more important to know the time spent within as small a bucket as possible.

If we receive pixels that have no increment, but a cumulative total, we'd have to create a new service on our for Google AMP pixels only to convert cumulative sums to increments by maintaining some hash of `(clientId, pageview) -> latest totalEngagedTime`. It'd be a pretty significant effort on our part.

After discussing with @cwisecarver, perhaps a happy middle-ground here is to go with @rudygalfi's suggestion of letting `incrementalEngagedTimer` take a parameter, our value would probably be `parsely-js`. Another vendor could of course use that parameter as well, but considering vendor implementations are controlled here in the repo, I'm not sure that's a real issue.

**Comment by lannka** [comment]
An alternative is to leverage the new TimerSpec introduced in #11290, as it now accepts a "startEvent" and a "stopEvent".

The config will look like:
```
trigger: {
  requests: {
    engagementTimerRequest: '${baseUrl}/increment=${timerDuration}&total=${totalEngagedTime}'
  }
  video-play-timer: {
    on: timer,
    request: '${engagementTimerRequest}'
    timerSpec: {
      interval: 2,
      startSpec: {
        on: "user-activity-start",
        selector: ":root",
        request: '${engagementTimerRequest}'
      },
      stopSpec: {
        on: "user-activity-stop",
        selector: ":root",
        request: '${engagementTimerRequest}',
      }
    }
  }
}
```

The work to be done is to have `activity-impl.js` fire the corresponding "user-activity-start" and  "user-activity-stop" events.

@msukmanowsky does this works more close to your "heartbeats" logic?

**Comment by cwisecarver** [comment]
@lannka I updated the #12141 PR to implement the initial suggestion that @rudygalfi made above.

If I'm understanding your suggestion correctly it would send a heartbeat on every start and stop of every user interaction as well as one after the interval passed between the start and stop events. Our heartbeat logic works differently. It sends a heartbeat every `interval` and sends the engaged time that's accumulated since the last heartbeat. Please let me know what you think about #12141.

**Comment by cwisecarver** [comment]
@rudygalfi @lannka Any word on this now that the holidays are over? We're really looking forward to getting engaged time working on AMP for our customers.

**Comment by zhouyx** [comment]
hey @cwisecarver I replied to the PR thread. 

@msukmanowsky pointed out 
> After discussing with @cwisecarver, perhaps a happy middle-ground here is to go with @rudygalfi's suggestion of letting incrementalEngagedTimer take a parameter, our value would probably be parsely-js. Another vendor could of course use that parameter as well, but considering vendor implementations are controlled here in the repo, I'm not sure that's a real issue.

We need to think deeper on the parameter reuse here. It's not only another vendor could use that parameter. Inline config could also overwrite the parameter. A safer way would be not allowing vendor/inline config to specify the name parameter, but let AMP runtime maintains an id system for each analytics trigger. 

For example:
```
 {
    "triggers": {
         "trigger1": {
              "on": "timer",
              "request": "fake.com?int=${incremental_engaged_time}",
         }
      }
}
```
name could be assigned to `${amp-analytics id}_${triggerName}`
Request would be converted to "fake.com?int=INCREMENTAL_ENGAGED_TIME(1_trigger1)"

In this case, vendor won't need to think about assigning the correct name param to `INCREMENTAL_ENGAGED_TIME`. And it's always guaranteed that the param is unique to each trigger.

**Comment by cwisecarver** [comment]
I think this makes sense @zhouyx. I just don't know where, since `getIncrementalEngagedTime` will be called multiple times by the same vendor, to initialize and keep track of the amp-analytics-id. If I had the vendor type in scope that would be simple. I just don't know if I do inside of `getincrementalEngagedTime` in the `ActivityHistory` class.

**Comment by cwisecarver** [comment]
@msukmanowsky What do you think about this? Are you concerned that someone could implement a timer with the same name as ours and break our tracking? Or is it worth the risk to get this functionality out in the wild?

I think it's worth it. We can always revisit if we see a problem or want to improve it.

**Comment by cwisecarver** [comment]
@zhouyx Talked to @msukmanowsky offline and he said it sounds good. Thanks! Look forward to our customers getting to use this.

**Comment by zhouyx** [comment]
Great! Thanks @cwisecarver I left some comments on the PR. Generally the approach looks good!
