### ISSUE TITLE
Chunker blocks document's render-start until all already-received extensions are installed

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#9343]
This comes from https://github.com/ampproject/amphtml/blob/c3115c80aede8316949cb2880316c94fef9f4051/src/runtime.js#L303

This is unnecessary, b/c most of extensions do not really block rendering and those that do have special processing. Also, dependency on whether the extension has already been downloaded constitutes a race condition.

Can we find a reliable way to _always_ slow down extension installation until "render-start" chunk has been executed? I assume either some form of priority or actual explicit blocking might be needed here.

**Comment by jridgewell** [comment]
I'm not sure I follow.

**Comment by dvoytenko** [comment]
How about this: [this code](https://github.com/ampproject/amphtml/blob/c3115c80aede8316949cb2880316c94fef9f4051/src/runtime.js#L303) appears to block [this code](https://github.com/ampproject/amphtml/blob/1c23274890c590f550df5d37b5f51a94c620baf3/src/amp.js#L101) a lot of times, which is unnecessary.

**Comment by cramforce** [comment]
Does this code somehow now help in your case https://github.com/ampproject/amphtml/blob/c3115c80aede8316949cb2880316c94fef9f4051/src/runtime.js#L999
?

**Comment by dvoytenko** [comment]
I think the opposite - it may hurt. I.e. we always want any extension to be loaded after render-start.

**Comment by jridgewell** [comment]
Can't we make extensions low priority then? IE, use `chunk` and not `startupChunk`?

**Comment by dvoytenko** [comment]
Maybe. Whichever is the most appropriate here.

**Comment by cramforce** [comment]
The code I pointed to runs the extension installation after all chunks.

**Comment by dvoytenko** [comment]
Ok, let's double-check. I seemingly was able to get into the reverse very easily.

**Comment by choumx** [comment]
Tested this on everything.amp.html and I can't repro. I'm not even sure that `maybePumpEarlyFrame` makes a difference for this issue since the chunk that contains `makeBodyVisible` is already enqueued by the time `runtime.js#adopt` is invoked. Closing for now.

**Comment by cramforce** [comment]
This is the difference that `maybePumpEarlyFrame` is supposed to make:

Usually during visible render we execute all chunks in the same microtask phase. Hence the browser cannot paint in between. `maybePumpEarlyFrame` is supposed to delay non-critical work into a macro task, so that the browser can paint once in between.

Did you see that?

**Comment by dvoytenko** [comment]
@cramforce @choumx I'm a bit confused. Do we agree that the first render is fast enough here?

**Comment by cramforce** [comment]
My point is that this line of code
https://github.com/ampproject/amphtml/blob/8dcf8936b0c7c3f850ffffd721a4078fb0c9176f/src/runtime.js#L327

is supposed to always allow the browser to draw a frame before installing any extensions.

Is this not what you are seeing?

**Comment by dvoytenko** [comment]
I think I was observing (and filed the issue) when `pump-early-frame` wasn't launched yet. It looks like it's been fully launched now, so if no other concerns, I will close this bug. Please chime in.
