### ISSUE TITLE
Custom Post Type Support To WordPress AMP Pages

### ISSUE THREAD

**Issue by madocar** [ampproject/amphtml#9345]
Hi,

​I would like to ask you there is any possibility to help me.​
The thing is I have a lot of specific pages (taxomies) with no AMP functionality. 

​Look here:
http://www.foodfest.sk/jedla/obed/amp/
http://www.foodfest.sk/ingrediencie/vajcia/amp/

These pages are redirected to URL with no /amp/ at the end.​ 
I added this code to function.php but still no progress.

    function isa_amp_add_cpt() {

    add_post_type_support( recipe', AMP_QUERY_VAR );

It looks like It should be working but It does not (post_type=recipe, taxonomy=ingredient) 

​/wp-admin/term.php?taxonomy=ingredient&tag_ID=278&post_type=recipe&wp_http_referer=%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dingredient%26post_type%3Drecipe​ 

Is there any way to help me enable AMP.

Thanks for any help.

Martin

**Comment by jridgewell** [comment]
Hi @madocar: This is a repo for the open source AMP library, not for publishing AMP pages using wordpress. You'll likely get a much better answer on [StackOverflow](http://stackoverflow.com/questions/tagged/amp-html).
