### ISSUE TITLE
amp-twitter: support fallback

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amphtml#9355]
amp-twitter does not support fallback elements in case a tweet could not be loaded. It'd be great if we could support something like this:

```
  <amp-twitter width="390" height="330"
               layout="responsive"
               data-tweetid="doesn't not exist"
               data-cards="hidden">
    <div fallback>Tweet has been deleted</div>
  </amp-twitter>
```

Context: http://stackoverflow.com/questions/43975240/amp-twitter-fallback-when-tweet-deleted

**Comment by ericlindley-g** [comment]
Might be nice to generalize this to anything that requires a network request — would that be possible?

**Comment by aghassemi** [comment]
agreed. `fallback` is the right general solution for this and is already implemented for `amp-img` for instance (e.g. if image fails to load, element with `fallback` is displayed - https://codepen.io/aghassemi/pen/jmdPvZ ).

For `amp-twitter`, we should make sure it is not just network failure that triggers `fallback` but also deleted/misconfigured tweets.

**Comment by wassgha** [comment]
@aghassemi not sure I totally get this, are we replacing the `blockquote placeholder` by the `div fallback` behavior or are we keeping both?

**Comment by aghassemi** [comment]
so `blockquote` is irrelevant, anything can be a `placeholder` or `fallback` and we support both of these in AMP. essentially we want 

```
<amp-twitter>
  <div placeholder>
   Displayed while amp-twitter is loading ( this already works )
 </div>
 <div fallback>
  Displayed if loading fails ( to be fixed with this issue ). Now we need to decide when it makes sense to display fallback. Bad tweet id? Twitter API down? Tweet deleted? all make sense to be candidate for fallback IMO.
 </div>
</amp-twitter>
```

**Comment by wassgha** [comment]
@aghassemi So I believe my concern is whether the placeholder should disappear or not when the tweet has loaded (whether loading failed or succeeded). In the current behavior, I don't think the placeholder disappears and I don't think it makes sense to have both the placeholder and the fallback displayed in the case where a tweet doesn't exist for example.

**Comment by drewmcmillan** [comment]
@wassgha Hey, Looking at this amp-twitter fallback, is there a way to not make it huge in height when a fallback is there?
![image](https://user-images.githubusercontent.com/11341355/28663628-d1694ca8-72b5-11e7-8eb2-460b7f5aaa89.png)
