### ISSUE TITLE
AMP "More Info" feature Breaks the X-button

### ISSUE THREAD

**Issue by gilbox** [ampproject/amphtml#9378]
## What's the issue?

- Search google for "short term rentals new york"
- Click on the first airbnb AMP link
- Click the 3-dot button in the top-right and click "More Info"
- Click the browser back button
- Notice that the `X` button disappeared.

Maybe this is intended? Seems like a bug to me though.

## What browsers are affected?

iOS Safari

**Comment by jridgewell** [comment]
Tracking internally at b/38353314.

**Comment by ericfs** [comment]
Thanks for the report. Actually tracking at b/35339712.

**Comment by jridgewell** [comment]
Internally, this is working at intended. They're looking to change it, but don't have a timeline.
