### ISSUE TITLE
New components

### ISSUE THREAD

**Issue by mister-ben** [ampproject/amphtml#938]
What process should be followed for contributing new components for consideration? The [components documentation](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-components.md) and [third party services guide](https://github.com/ampproject/amphtml/tree/master/3p) states that there's a vetting procedure but does not detail the process.

Is a pull request into this repository enough to get the discussion started, or does this need to be discussed elsewhere?

**Comment by cramforce** [comment]
@mister-ben Let me know whether this helps
https://github.com/ampproject/amphtml/blob/master/CONTRIBUTING.md#contributing-features

We recommend to start the intent to implement issue first. Of course, you are free to do whatever you want :)

Our experience is that a quick discussion really helps with doing things the right way for AMP's long term direction. Also always feel free to hop onto our Slack for realtime feedback https://github.com/ampproject/amphtml/blob/master/DEVELOPING.md#slack-and-mailing-list

**Comment by jmadler** [comment]
I'll close this bug as we're looking to clean up the backlog.

@mister-ben, If you have any further feedback or questions, please let us know.
