### ISSUE TITLE
Error: race condition on customElement stubbing

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#9385]
has been reported several times. 

seems to be happening on Chrome 4x and SamsungBrowser only
/to @zhouyx

**Comment by jridgewell** [comment]
Any more details?

**Comment by aghassemi** [comment]
It's a signal @zhouyx has been monitoring for sticky ad , just wanted to inform her it is being seen.

**Comment by zhouyx** [comment]
duplicate of #9126

**Comment by zhouyx** [comment]
@aghassemi Thanks of let me know. Will remove in next sprint.
