### ISSUE TITLE
Reduce the travis build time

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#9387]
Right now it takes travis ~30m for a [pull request](https://travis-ci.org/ampproject/amphtml/builds/233030921) and ~40m for a [release build](https://travis-ci.org/ampproject/amphtml/builds/232917583). Let's speeeed it up!!

```
gulp.js lint. Total time: 0m 51s.
gulp.js check-types. Total time: 0m 47s.
gulp.js presubmit. Total time: 0m 25s.
gulp.js dep-check. Total time: 1m 46s.
gulp.js build. Total time: 2m 10s.
gulp.js dist --fortesting. Total time: 12m 22s.
gulp.js test --nobuild --compiled. Total time: 7m 33s.
gulp.js test --nobuild --saucelabs --integration --compiled. Total time: 7m 25s.
cd validator && python build.py. Total time: 1m 58s.
cd validator/webui && python build.py. Total time: 0m 16s.
```

Some ideas:
- [Parallelize jobs](https://docs.travis-ci.com/user/speeding-up-the-build/) on different VMs. All presubmit checks can be moved to a separate VM (~4min). Validator checks too (~2m). 
- skip `gulp build` (2m 10s), since we only test against `gulp dist` (caveat: we might need `gulp build --css-only` to get `gulp dist` running, or we should fix the deps)
- saucelabs tests do not consume local CPU, can be definitely parallelized. (7m 25s)
- Optimize our compiler, build all extensions in one shot (12m) (@cramforce is it still possible?)

**Comment by cramforce** [comment]
We will need to prioritize this.

Good news is that we do have a very significant speed up for the compilation part on the horizon. I believe this is on @erwinmombay's OKRs for this quarter. It does, however, require significant changes and will take a few months.

**Comment by lannka** [comment]
Besides the compiler script improvement, we can still get the low hanging fruit like [Parallelizing jobs](https://docs.travis-ci.com/user/speeding-up-the-build/) on different VMs.

**Comment by cramforce** [comment]
Absolutely!

**Comment by rsimha-amp** [comment]
Picking this up now.

**Comment by rsimha-amp** [comment]
@lannka: FYI, from a comment in pr-check.js, it appears that gulp dep-check does depend on gulp build having been run, so that one task cannot be run in a different VM. I'm testing a parallel run with the rest of the tasks you've marked in bold.

**Comment by lannka** [comment]
@rsimha-amp I'm not sure why the dependency exists ( @erwinmombay can you chime in?), but this works:
```bash
gulp build --css-only && gulp dep-check
```

**Comment by rsimha-amp** [comment]
@lannka, css files is precisely the reason. I think I can  do a css-only build and thereby separate out dep-check into a parallel task that's not on the main build task. Working on it.

**Comment by rsimha-amp** [comment]
From https://travis-ci.org/ampproject/amphtml/builds/233425954, it seems like Travis is running the shards one after another. I think we might need to enable concurrent builds for our project via the Travis settings. I'll look into doing that once I'm sure that the shards I've created are truly independent.

**Comment by lannka** [comment]
The result is promising: https://travis-ci.org/ampproject/amphtml/builds/233430708?utm_source=github_status&utm_medium=notification

The failed unit test seems to be integration tests which should be probably moved to `/integration` test.

I suggest we do a `gulp build` for unit test now, and create another issue for people to clean those tests up.

**Comment by rsimha-amp** [comment]
@lannka, change made. The sharded build was fully parallel this time, and the build time is down to ~16 mins. However, since the unit tests currently need a full dist build, and it's not possible to do two parallel dist builds on the same machine, we're going to first have to clean up the unit tests before merging this change.

**Comment by rsimha-amp** [comment]
We now have a parallel build, so this issue is fixed. Note that even though the time reported by Travis appears to have increased, it is a result of the total server time spent by all parallel jobs. (See https://github.com/travis-ci/travis-ci/issues/1486 for a discussion on this.) The actual wall clock time for a full build has gone down from ~40 minutes to ~25 minutes.

**Comment by lannka** [comment]
this is awesome. I suggest we can enable integration test for each pull request now.

**Comment by cramforce** [comment]
@lannka that is a separate issue. It is now possible with changes of how secrets work in Travis. @erwinmombay started work, but I think it got stuck. What is the status?

**Comment by lannka** [comment]
@cramforce i thought it will be a simple change in pr-check.js to enable integration test for pull requests, not just builds?

**Comment by cramforce** [comment]
Until recently saucelabs did not work in PRs because they could steal the
credentials. There is now a way to do it.

**Comment by rsimha-amp** [comment]
@cramforce, from reading https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions, I was under the impression that secure keys are not available to PRs because if they were, anyone could write a test that simply printed the env vars containing the keys. Am I missing something?

**Comment by cramforce** [comment]
That used to be true, but their own info is outdated. See https://docs.travis-ci.com/user/sauce-connect/ for the JWT based solution.

It would be super awesome to finally get that to work for PRs!

**Comment by rsimha-amp** [comment]
Cool, good to know. I'll look into JWT this week.
