### ISSUE TITLE
Add support for embeding imgur

### ISSUE THREAD

**Issue by techhtml** [ampproject/amphtml#9405]
## What's the issue?

`Imgur` is huge image community on the web,
They support embedding but that codes are 
```
<blockquote class="imgur-embed-pub" lang="en" data-id="Lwr47i3"><a href="//imgur.com/Lwr47i3">&quot;You&#39;re powered up, get in there!&quot;</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>
```

Proposed format:
```
<amp-imgur data-imgur-id="DYI27Yt" layout="responsive" width="1" height="1"></amp-imgur>
```

I think this can't embed using Iframes.

**Comment by aghassemi** [comment]
@techhtml Thanks for filing. 

Should be similar to `<amp-instagram>` embed (likely much lighter on the implementation).

Contributions are very welcomed! https://bit.ly/helpamp  if you are interested.

**Comment by techhtml** [comment]
@aghassemi I'll tried build that.
thanks :)

**Comment by cramforce** [comment]
Instead of the heavyweight embed, could we just load an image with some imgur branding and link it to the respective page on imgur?

**Comment by techhtml** [comment]
@cramforce I think it's not hard if they have only single images or videos(gif).
but when uploaded multiple images, it's quite harder because can't know how many images are loaded.

If having only support single images or videos(gif), it can do that.

**Comment by cramforce** [comment]
@techhtml Good point.
