### ISSUE TITLE
Reduce code duplication between runtime and extensions

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#941]
I think the right approach is to export functionality from the runtime (through a lightweight mechanism, not the manual runtime.js stuff) and then have little facades that expose these functions to extensions as regular typed imports.

**Comment by dvoytenko** [comment]
At this point, I think, we barely need any as is. We just need to switch them to services. The only meaningful "exports" that I see are registration and devmode exports. I'll start refactoring others one by one.

**Comment by cramforce** [comment]
Right, still e.g. viewer service could have a facade, so its implementation
never loads in the extension.

I suppose all we need to do is put the factory like `viewerFor` into its
own file and we're done.

**Comment by dvoytenko** [comment]
Yes. Somehow come up with a way to export services without creators.

**Comment by cramforce** [comment]
We're working on it by separating services and implementation.
