### ISSUE TITLE
Closing amp-lightbox causes popstate to be triggered

### ISSUE THREAD

**Issue by edhollinghurst** [ampproject/amphtml#9410]
We're finding that closing an amp-lightbox causes the popstate event to be triggered.

This is an issue for us when using amp documents within our Progressive Web App (using AMP Shadow). We have an event listener for popstate (that fires when the browser forward or back button is clicked) to load that appropriate document:

```
window.addEventListener('popstate', function(e) {
  if (e.state !== null) {
    loadDoc(window.location.href);
  }
});
```

However because the popstate event is also triggered when amp-lightbox is closed, it causes the page to reload.

An exampled of this can be seen in the London pollution gallery on this page:
https://www.standard.co.uk/lifestyle/london-life/hedges-can-soak-up-london-s-toxic-air-pollution-better-than-trees-a3541356.html?ines_tg=1 (you'll need to refresh the page to get the PWA).

Any advice on how to overcome this problem would be appreciated!

**Comment by bjalford** [comment]
Any update on this?

**Comment by choumx** [comment]
Missed this issue, sorry for the delay! `amp-lightbox` also uses the history API to exit on back button which probably won't change. 

Instead, you can try inspecting the [`state`](https://developer.mozilla.org/en-US/docs/Web/Events/popstate#Properties) property to infer the trigger of the `popstate` event. Specifically, existence of the `AMP.History` key in that object.

```js
window.addEventListener('popstate', function(e) {
  const isAmpEvent = 'AMP.History' in e.state;
  if (!isAmpEvent && e.state !== null) {
    loadDoc(window.location.href);
  }
});
```

/cc @aghassemi

**Comment by edhollinghurst** [comment]
Thanks @choumx

**Comment by bjalford** [comment]
Confirming this fixed the issue we were having.

**Comment by bjalford** [comment]
Actually, this fixes the carousel but breaks the back navigation as @edhollinghurst pointed out

**Comment by choumx** [comment]
How does it break back navigation? Can you provide an example?

**Comment by edhollinghurst** [comment]
Hi @choumx, sorry for the delay in coming back on this.

An example can be seen on the galleries at: https://article-swipe.standard.co.uk/news/uk/william-and-kate-to-walk-prince-george-through-playground-gates-when-he-starts-school-next-week-a3622456.html (Refresh to get to the PWA)

`'AMP.History' in e.state` evaluates to true when the browser forward or back buttons are clicked.

**Comment by choumx** [comment]
Ah I see. Actually, looks like `AMP.History` will always be present in history events on AMP pages -- my mistake.

What about comparing `window.location.href` with its previous value and only loading the doc if the it has changed?
