### ISSUE TITLE
Rename Keycodes enum to KeyCodes

### ISSUE THREAD

**Issue by kmh287** [ampproject/amphtml#9411]
### First Timers Only
We know figuring out the process for contributing to an open source project can be intimidating, so we created this issue as a way for you to learn the ropes.  (If you feel comfortable contributing to open source projects, please leave this issue for someone else.)

### What you will need to know

In order to prevent comparisons against "magic numbers" when responding to keyboard events, we added an enum, `Keycodes`, in [src/utils/keycodes.js](https://github.com/ampproject/amphtml/blob/master/src/utils/keycodes.js#L20). However, the name of the enum is inconsistent with the camel cased `event.keyCodes`.

### Background

AMP has support for users with keyboards to interact with AMP pages. When a user presses a button in a supported context, an event listener will receive the `keydown` event, check `event.keyCode` to determine which key the user pressed, and then respond appropriately.

### Motivation
Inconsistent casing introduces an unnecessary need to think about what the correct casing is. 

### The bug

In [src/utils/keycodes.js](https://github.com/ampproject/amphtml/blob/master/src/utils/keycodes.js#L20), there is an enum named `Keycodes`. It should be named `KeyCodes`.

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.

- [ ] Rename the `Keycodes` enum to `KeyCodes` anywhere it's used. Direct uses in code, imports, and tests will all need to be updated.
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).

- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review).  Mention `closes Issue #9411` in the description and add @kmh287 as a reviewer.
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

### Questions?

If you have questions ask in this issue or on your Pull Request (if you've created one) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide. Feel free to reach out to @kmh287 with any questions.

**Comment by droms** [comment]
I would like to give this issue ago if no one has claimed it yet

**Comment by droms** [comment]
I've updated all the occurrences of keycodes to KeyCodes.
I'm having trouble running the tests on my system getting multiple fails on both a fresh fork of the repository and with the changes. Any suggestions?

I'll create the pull request anyway but it hasn't been tested

**Comment by kmh287** [comment]
Are you seeing test failures in files changed by your PR?

**Comment by droms** [comment]
Doesn't look like it. The same tests are failing on the clean fork of the repository

**Comment by kmh287** [comment]
Fixed by #9437
