### ISSUE TITLE
pwa: combination of amp-ads and dfp ads

### ISSUE THREAD

**Issue by bjalford** [ampproject/amphtml#9414]
When building using the pwamp pattern (shadowdown amp doc into pwa) and using a combination of DFP ads for the leaderboard for example and then the rest of ads are in the amp doc, it's not possible to do SRA. 

One benefit would be to pass the correlator from the pwa to the amp doc through the ampshadow. That would help with non-guaranteed roadblocks.

**Comment by jasti** [comment]
There is an internal discussion going on regarding this. @keithwrightbos FYI who is already working on AMP only SRA.

**Comment by dvoytenko** [comment]
With PWA/shadow area: is this only related to ads inside shadow docs (e.g. `<amp-ad>`)? Or ads in the main shell page that are deployed via shadow slots?

**Comment by jasti** [comment]
@dvoytenko this is referring to correlating two ads in the same request. One regular GPT ad in the main shell page and one <amp-ad> that's inside of the shadow slot.
