### ISSUE TITLE
ITT: amp-timeago add cutoff time

### ISSUE THREAD

**Issue by bjalford** [ampproject/amphtml#9415]
We have a use case where we want the date to be formatted as time ago only for a defined time period e.g. if the time ago is over a week then display the date rather than X days ago.

This ITT is to add support for a cutoff property of the timeago component.

e.g.
<amp-timeago layout="fixed-height" height="20" datetime="2017-04-11T00:37:33.809Z" locale="en" **cutoff="604800000"**>Saturday 11 April 2017 00.37</amp-timeago>

So if the datetime was over the cutoff ago 604800000 milliseconds (1 week), it would not convert to timeago. 

@edhollinghurst FYI

**Comment by aghassemi** [comment]
SGTM!

**Comment by aghassemi** [comment]
Could cutoff be an ISO date similar to datetime attr instead is ms?

**Comment by bjalford** [comment]
@aghassemi the thinking behind a relative time was to cater for pages that are in caches including CDNs. I guess that can be calculated on the backend so yes maybe ISO date is better.

**Comment by jridgewell** [comment]
If we go with cutoff being a maximum diff, let's use seconds and not ms. Or, let's do an ISO date. Either is fine.
