### ISSUE TITLE
SVG Validation error on DEFS tag

### ISSUE THREAD

**Issue by age401** [ampproject/amphtml#9417]
## What's the issue?
Hi, I'm getting a validation error on an inline SVG graphic:

> The parent tag of tag 'head > style[amp-boilerplate] - old variant' is 'defs', but it can only be 'head'.

I understand that DEFS is supported, any ideas?

## How do we reproduce the issue?
1. The URL to check is: 
http://netbis.com.ar/ventas-online-inmobiliarias/dev-index-10.html

2. The SVG code is:
`<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 36 36"><defs><style>.cls-1{fill:none;}.cls-2{fill:gray;}</style></defs><rect class="cls-1" width="36" height="36"/><polygon class="cls-2" points="10.25 26 25.75 18 10.25 10 12.75 17 18.75 18 12.75 19 10.25 26"/></svg>`

3. The validation error:
https://validator.ampproject.org/#url=http%3A%2F%2Fwww.netbis.com.ar%2Fventas-online-inmobiliarias%2Fdev-index-10.html

## Which AMP version is affected?
Just began testing with: 
Version 1494957764037

**Comment by aghassemi** [comment]
to @ampproject/validator

**Comment by Gregable** [comment]
This is complaining about the `<style>` tag. The error could be better, but we are already tracking that. See https://www.ampproject.org/docs/guides/responsive/style_pages for more information.

**Comment by mikewest23** [comment]
I was able to get around this by exporting out of Adobe Illustrator with different settings that doesn't use defs and style tag by using the following exporting settings:

Style: Inline Style
Font: Convert To Outlines
Images: Embed
Object IDs: Minimal
Decimal: 2
Minify: Checked
Responsive: Checked

Then I clicked "Show Code" copied and pasted into my page, and it passed.
