### ISSUE TITLE
AMP carousels on 'Who is AMP for?' pages need navigational arrows so viewers on mobile or narrow viewport pages know to scroll for more content 

### ISSUE THREAD

**Issue by coryphwang** [ampproject/amphtml#9421]
## What's the issue?
When viewing three sub-pages to 'Who is AMP for?', I noticed that I missed some of the content in AMP carousels when viewing the pages from my mobile phone (Nexus 5X), or a Chrome browser window using a narrow viewport. 

It would be great if we could add the "controls" attribute per the docs: https://www.ampproject.org/docs/reference/components/amp-carousel#attributes

WORKING AS INTENDED: You can see that this Ad Tech Platform page has three sections in the carousel (i.e., Increase your reach, Maximize your rev, Build for a sustainable future). When the viewport of the browser is wide enough, viewers can see all of the content written. 
![screen shot 2017-05-18 at 11 59 07 am](https://cloud.githubusercontent.com/assets/28789188/26218861/6b084408-3bc1-11e7-9f7c-9e2b67845922.png)

MISSING CONTENT (on computer): When viewing from a narrow viewport on a browser window from a computer, users might not know that there is a third section (i.e., Build for a sustainable future). When the viewport is more narrow, the 2nd section goes away also. Users can toggle with the right / left arrow key, but that might not be intuitive.
![screen shot 2017-05-18 at 11 47 29 am](https://cloud.githubusercontent.com/assets/28789188/26218824/46bc10ca-3bc1-11e7-8391-ab1693dd71d9.png)

MISSING CONTENT (on mobile): When viewing from a mobile device, users only see the first box of the carousel, and most likely don't know there is more content to consume because there are no arrows or indicators to scroll to the right. 
![screenshot_20170518-120205](https://cloud.githubusercontent.com/assets/28789188/26218985/e35b5904-3bc1-11e7-80b7-5569c2dc5ba5.png)

## How do we reproduce the issue?
1. Visit one of the following pages on desktop or mobile, and scroll down to the sections with the AMP carousels. 
https://www.ampproject.org/learn/who-uses-amp/ad-tech-platforms/
https://www.ampproject.org/learn/who-uses-amp/publishers/
https://www.ampproject.org/learn/who-uses-amp/advertisers/

2. On desktop, make the viewport more narrow until you start seeing one or two sections in the carousel without an optional navigation arrow. Then, try to access the content that's hidden by using the right arrow. At this point, you'll notice that viewers of the content from this viewport won't notice that there is more content, and don't have a way to access it via arrow keys or mouse scrolling.

3. On mobile, you'll see that there aren't allow navigational arrows, but viewers of the content can swipe left and right to access the other sections in the carousel. You'll also notice that viewers will most likely not swipe left or right because they don't have any contextual clues that there is more content to read.

Feature Request: By adding navigational arrows via the "controls" attribute, we could definitely ensure that users can find the content in these AMP carousels. 

## What browsers are affected?
For me, it didn't work on Chrome, FireFox, and Safari browsers on my Macbook Pro, and it didn't work on my Chrome mobile browser for my Nexus 5X device.

## Which AMP version is affected?
For Chrome, the amp-version is 1494957764037. 

This seems like an issue based on design choice, but I wanted to make sure to bring it up just in case it wasn't the expected behavior for these AMP carousels.

**Comment by aghassemi** [comment]
@spacedino arrows vs dots decision

**Comment by bpaduch** [comment]
This was a stylistic design choice to not display prev/next arrows (see https://github.com/ampproject/docs/commit/29ba9493e8457d67b2439ffab7a305758bef3eca).

**Comment by aghassemi** [comment]
@bpaduch @spacedino Can we revisit this decision? The fact that these items are in a carousel and there is more than one to swipe through is completely unrecoverable. Even worse, on desktop there is actually no way to go to next item.

**Comment by bpaduch** [comment]
I'll re-open it and leave to Paul to work on.  I actually turned them on and the CSS is off, so it'll be a bit more work then turning them on.

**Comment by pbakaus** [comment]
Just confirmed that these arrows appear for me fine. @bpaduch can you confirm as well before I close this bug?

**Comment by bpaduch** [comment]
Yep, I fixed them in an update.

**Comment by pbakaus** [comment]
Woohoo, awesome :)
