### ISSUE TITLE
FR: Support collapsing <amp-list> parent element if amp-list call returns no data

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#9424]
Intended to support UI for Suggested products or articles, comments, and other dynamic data that may not exist (yet) for a given page.

Typically there's a parent container with text like "Comments" or "Recommended for you" that is not a part of amp-list, followed by amp-list content. Would be great if there were an easy way to collapse this contextual parent container if no data is returned by amp-list's server call.

Currently supported might be a method where the template includes the header for every list item, but only returns the actual header data in the first item in the list. However, that's potentially a lot of unnecessary duplicate code for a common behavior.

**Comment by kul3r4** [comment]
There was a similar discussion in #5686

**Comment by choumx** [comment]
Is this a dupe of #5686 (which appears to be closed as WAI)? Dima made good points in that issue that this probably shouldn't be allowed due to empty space and content jumping.

**Comment by ericlindley-g** [comment]
This issue is slightly different, but let me try to break down both issues:

Goal (1) (related: #5686)
Support use cases for amp-list where potentially no items will be returned

Current pain point: amp-list resizes based on best effort when it comes near the viewport. What it doesn't currently support (as far as I understand) is the following: starting with a size of "0" and resizing to take up space only when items are returned from the server call (and then, only to the amount of space needed for those items). This would support use-cases like customized ads served inline with related content (and only served if there are ads available for this related content).

Additional risk: Low
Rationale: amp-list already allows for resize of content based on the number of items returned by amp-list, so this just supports the case where items=0.

Though are there aspects of the issue that I'm not taking into account?


Goal 2 (related: #5686)
Have something like a comments section with the structure:
"Comments" headline
Comment 1
Comment 2
Comment 3
etc

When no comments are returned, want to hide the "Comments" headline

Pain point: no way to hide the "comments" headline currently, unless it's built into the repeated comments template (and has some cleverness so this headline isn't displayed in every instance of the template)

Potential solution 1:  allow amp-list to hide parent container if no items are returned
Issue: I agree with Dima that is is probably too risky in terms of page jumps

Potential solution 2: allow an optional div in amp-list that sets context for the repeated items (ie. "Comments", "Reviews", "Related articles", etc. This div doesn't show if no items are returned in the server call, but is displayed otherwise, and only once.

WDYT?

Since there's a workaround currently for Goal 2, I wouldn't necessarily consider this at the top of the priority list, but goal 1 is an issue that I'm not aware of a workaround for.

**Comment by ericlindley-g** [comment]
Just wanted to follow up on this, @choumx — do the cases I've outlined above make sense, or does it make sense to sync in real-time to better communicate what I'm thinking, here?

**Comment by choumx** [comment]
Sorry for the delay. 

- Is (1) not supported? In my testing, setting `height=0` to an amp-list still results in correct resizing (if it's out of viewport). Or do you mean changing width as well?

- Another way to do (2) without changing the JSON data is to use CSS `:first-child` pseudo-class. Would that suffice? 

```html
<style amp-custom>
    h3.comments {
      display: none;
    }
    /* amp-list wraps each rendered template item in a <div> */
    amp-list div:first-child > h3.comments {
      display: block;
    }
</style>

<amp-list width=400 height=100 layout=responsive src="/data.json">
  <template type="amp-mustache">
    <h3 class="comments">Comments</h3>
    <div>{{comment}}</div>
  </template>
</amp-list>
```

**Comment by ericlindley-g** [comment]
Thanks @choumx ! I think that we had developers running into an issue that they couldn't get around, but maybe they didn't try setting height=0 at the start. @dandv , do you know if the folks you were talking to that were using amp-list and geo-specific ads tried this approach?

And that's a great route for the other request! Much more simple than adding a new capability. I'll pass this on and see if it works well for the use case

**Comment by lsarni** [comment]
I have being struggling with this, since my list isn't out of the viewport so setting `height=0` doesn't resize the list it it has any elements. I can render a message using the mustache template but I'm left over with a bunch of blank space.

**Comment by ericlindley-g** [comment]
Thanks for the feedback @lsarni — /cc @cathyxz for visibility into this issue as well. @cathyxz , will this be addressed with the amp-list work you've been doing, or would it need to be addressed separately?
