### ISSUE TITLE
add "as-you-go-and-show-all-on-submit" for form "custom-validation-reporting"

### ISSUE THREAD

**Issue by xileftenurb** [ampproject/amphtml#9427]
I would like to have both reporting strategy ("as-you-go" ans "show-all-on-submit") for the same form.

so if the users interact with a input, the validation message will be visible right away, and if the user submit the form before touching required field, the "required" error show up.

right now, when I use "as-you-go", if there is some required field, nothing happen. there is no error showing the required field.

**Comment by ericlindley-g** [comment]
+1

Would be nice, in addition, if we could distinguish fields where the user has already made an attempt but hasn't made a valid entry, versus fields where they haven't made an attempt yet
