### ISSUE TITLE
Provide a clear way to log messages to developers (when development mode is on)

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#943]
Our logging isn't really the right tool. Nor is calling `console.foo` directly.

CC @dvoytenko

**Comment by dvoytenko** [comment]
I think our logging should be the right tool - I think most of messages are in this category today. Instead, we need to add a "prod" logger for non-dev issues.

**Comment by cramforce** [comment]
First we need to get our terminology right :)

When I said developers I meant people writing AMP docs. We should almost never show them a log message, except in rare circumstances.

**Comment by dvoytenko** [comment]
In that case - yes, definitely :)

**Comment by dvoytenko** [comment]
I think we can merge asserts via logs. E.g. let's say we have to logger instances: `devlog` and `publog`. And let's assume that `devlog` is removed for PROD/minified build. Then things should be rather clear:

This will be a dev-only assert that will be stripped:
```
devlog.assert(arg1, 'Arg1 must never be a NULL');
```

vs, this assert will be preserved:
```
publog.assert(isUrlSecure(url), 'An HTTPS URL must be provided', this.element, url);
```

**Comment by erwinmombay** [comment]
@dvoytenko one of the issues is that we do this sometimes:

```js
this.somePrivateProp_ = devlog.assert(arg1, 'Arg1 must never be a NULL');

// this.somePrivateProp_ is used somewhere else..
```

**Comment by erwinmombay** [comment]
which isnt a big deal, since i can skip it. but also i can do what closure compiler does where it will only DCE the assert and turn

```js
this.somePrivateProp_ = devlog.assert(arg1, 'Arg1 must never be a NULL');

// this.somePrivateProp_ is used somewhere else..
```

into:

```js
this.somePrivateProp_ = arg1;

// this.somePrivateProp_ is used somewhere else..
```

i haven't looked into implementing that yet though.

**Comment by dvoytenko** [comment]
As discussed, we can start by keeping asserts as they are. But if we decide to merge them with loggers, I think it'd be easy enough to remove assert, but keep the expression itself.

**Comment by adelinamart** [comment]
@erwinmombay is this still relevant?

**Comment by erwinmombay** [comment]
@adelinamart i dont believe so
