### ISSUE TITLE
Javascript Pollyfill

### ISSUE THREAD

**Issue by CemDemirkartal** [ampproject/amphtml#9435]
I have an script which runs after AMP project,

Mainly i use, (native) **closest** and  **querySelector with :scope**; On some browsers it gives error.

AMP uses same but,
- Does AMP provides pollyfill; or Does it selfish pollyfill?

**Comment by jridgewell** [comment]
We don't polyfill either, but we have helpers.

- [closest](https://github.com/ampproject/amphtml/blob/a3d4bd9d439786696a6c7a785dc2076b375b05aa/src/dom.js#L217-L231) (called closestBySelector, but it's the same)
- [querySelector](https://github.com/ampproject/amphtml/blob/a3d4bd9d439786696a6c7a785dc2076b375b05aa/src/dom.js#L416-L437)

**Comment by CemDemirkartal** [comment]
That mean's amp project is only for amp project.
There is no help for web designers / programmers.

People need heavy libraries to do pollyfill, which amp doesn't want it to be in HTML pages and amp doesn't share with in common.
