### ISSUE TITLE
amp-iframe documentation states the 'allowfullscreen' attribute is allowed, but AMP page becomes invalid if used

### ISSUE THREAD

**Issue by Cauchon** [ampproject/amphtml#9445]
## What's the issue?

allowfullscreen is listed as an allowed attribute in the documentation, but the AMP Validator throws the following error when used:

`The attribute 'allowfullscreen' in tag 'amp-iframe' is set to the invalid value 'true'.`

Documentation: https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md

## How do we reproduce the issue?

Example URL: https://www.cnet.com/google-amp/news/bill-gates-works-with-love-actually-cast-for-red-nose-day/#development=1

1. Go to the AMP page
2. Open console and refresh
3. Notice that the following error is thrown (only need to focus on this one error):
`The attribute 'allowfullscreen' in tag 'amp-iframe' is set to the invalid value 'true'. (see https://www.ampproject.org/docs/reference/components/amp-iframe)`

## What browsers are affected?

All browsers that support AMP

## Which AMP version is affected?

1495054386926

**Comment by jridgewell** [comment]
`allowfullscreen` shouldn't have a value, it's a naked attribute:

```html
<amp-iframe allowfullscreen src="..."></amp-iframe>

**Comment by jridgewell** [comment]
See https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-allowfullscreen, which defines `allowfullscreen` as a [boolean attribute](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attribute):

> A number of attributes are boolean attributes. The presence of a boolean attribute on an element represents the true value, and the absence of the attribute represents the false value.

All that's needed is the presence of the attribute

**Comment by Pocok256** [comment]
@jridgewell thank you for the clarification. 

And thanks the whatwg.org link.
