### ISSUE TITLE
After opening amp-lightbox in iphone safari browser it is removing uri part from the url. Any solution?

### ISSUE THREAD

**Issue by NithishReddy** [ampproject/amphtml#9453]
Ex:
initial url is www.example.com/abc/user/def-123
after opening amp-lightbox in this page, the url becomes www.example.com.

is there any solution for this issue?

**Comment by aghassemi** [comment]
That's shouldn't happen, likely a regression bug. We will investigate.

/cc @ericlindley-g

**Comment by aghassemi** [comment]
@NithishReddy Do you have a Url for a page that reproduced this issue? I have tried it with https://ampbyexample.com/components/amp-lightbox/ (in both origin and Google search viewer cases) and in both Url is unchanged after lightbox opens (Safari on / iOS 1.3.3)

**Comment by NithishReddy** [comment]
Hi Ali,

We are implementing AMP functionality for my project, that still in
development state only. while testing AMP pages, we have identified this
issue.

Testing device is iphone 6/6s.

is there any development mistake ???

any solution ???

--Nithish Reddy

--Nithish Reddy

**Comment by aghassemi** [comment]
@NithishReddy It is hard for me to tell without seeing it. What version of iOS do you have? Could you please try visiting `https://ampbyexample.com/components/amp-lightbox/` on your phone and see if the issue reproduces there as well?

**Comment by aghassemi** [comment]
@NithishReddy Please reopen the issue with more details on repro steps. I have not been able to repro as suggested.
