### ISSUE TITLE
amp-carousel: Attempting to access a non-existant slide

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#9467]
Have seen a few of these errors recently. (do a search in error reporting to see examples).
Not to many cases but something to investigate as there should be no legit code path to get to this error.

/to @camelburrito

**Comment by jridgewell** [comment]
Dupe of https://github.com/ampproject/amphtml/issues/8920?

**Comment by aghassemi** [comment]
I guess this is the 'extra logging' mentioned in #8920
