### ISSUE TITLE
35 Test Failures currently at head on master branch when testing locally

### ISSUE THREAD

**Issue by bradfrizzell** [ampproject/amphtml#9472]
Running `gulp test` locally right now is showing 35 test failures, while Travis is showing a green build. 

This has been reproduced by @jonkeller and @lannka 

This has been a recurring issue of the test suite running differently on Travis than locally (with the difference usually being that tests that fail locally pass on travis).

**Comment by choumx** [comment]
Sorry about that. `amp-bind` tests currently require `gulp dist --fortesting` first (which is what Travis runs). You can run that locally until #9404 is fixed. Closing as dupe.

**Comment by lannka** [comment]
@choumx I couldn't pass the test with:
```
gulp clean && gulp build && gulp dist --fortesting && gulp test --nobuild
```

**Comment by bradfrizzell** [comment]
+1, I also couldn't pass with that

**Comment by choumx** [comment]
Discussed this with @rsimha-amp and the local flakiness is due to a shorter timeout compared to Travis (configurable in `karma.conf.js`). The changes in #9404 should still fix these.

**Comment by rsimha-amp** [comment]
I can confirm that increasing the timeout from 2 seconds results in all the bind tests passing. I'm working on a PR to change the timeouts for local and travis runs. Stay tuned.
