### ISSUE TITLE
PWA: support shadow document streaming

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#9491]
Currently the shadow-doc API provides only a fully-loaded document API. However, waiting for the last byte to arrives creates a high perceived latency. To address this, it's possibly to incrementally construct the shadow doc while streaming HTML as described [here](https://jakearchibald.com/2016/fun-hacks-faster-content/)

/cc @bjalford

**Comment by comolongo** [comment]
Is the idea here that streaming pre-rendered DOM and putting it onto the page is quicker than generating it on the client side via JS? This reminds me of YouTube' use of soft page transitions: https://github.com/youtube/spfjs.

**Comment by dvoytenko** [comment]
This is slightly different. AMP itself intrinsically supports prerendering. This work is specifically to incrementally build DOM as it comes via HTTP.
