### ISSUE TITLE
XHR errors are reported incorrectly

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#9501]
Since the new errors are not an instance of an error object, when they are thrown by callers to the AMP error service, the service does not recognize them as a valid error. Possible fixes are returning to the mutated-error approach, or creating a custom error type decorated with the xhr data.

This error manifests itself as `Error: [Object object]` in the console.

**Comment by jridgewell** [comment]
Already working on it. https://github.com/ampproject/amphtml/pull/9448

**Comment by cvializ** [comment]
Cool

**Comment by jridgewell** [comment]
Don't have an issue for it, so I'm going to reopen this.

**Comment by jridgewell** [comment]
Fixed by https://github.com/ampproject/amphtml/pull/9574.
