### ISSUE TITLE
[amp-lightbox] Allow lightbox inside template tag

### ISSUE THREAD

**Issue by vydn** [ampproject/amphtml#9514]
After form submit success I want to show a lightbox to display the response but it could not find the target lightbox

```html
<div submit-success>
  <template type="amp-mustache">
    <amp-lightbox id="lightbox" layout="nodisplay">
      <p>Status: {{status}}</p>
    </amp-lightbox>
  </template>
</div>
```

**Comment by aghassemi** [comment]
/cc @cvializ @ericlindley-g 

sounds reasonable to be able to show a modal after `submit`, `submit-success` or `submit-error` events.

to handle this we need to:
1- Ensure `amp-mustache` can render `amp-lightbox` and that it is not invalid based on validation rules
2- Ensure templates are rendered before the actions defined on `submit` events are triggered so one can reference the `id` of the lightbox that was just rendered.

**Comment by cvializ** [comment]
I believe `amp-bind` might be a better solution for this task. You can use something like the following markup:

```html
<form on="submit-success:AMP.setState({status: response.status}),lightbox" ...>
<!-- ... -->
</form>
<amp-lightbox id="lightbox" layout="nodisplay">
  <p>Status: <span [text]="status"></p>
</amp-lightbox>
```

What do you think?

**Comment by aghassemi** [comment]
@cvializ I like that! @vydn wanna give that solution a try? Note that `amp-bind` is experimental feature but if you like to ship to production with it, you can sign up for origin trial: https://www.ampproject.org/latest/blog/test-amp-bind-on-your-site-with-an-origin-trial/

**Comment by vydn** [comment]
@cvializ @aghassemi `amp-bind` has been already used. But as @aghassemi  said it is experimental feature so I am quite worried about it, but it might be the best solution now.
In the other hand, thanks for your support and I think this issue can be closed.

**Comment by aghassemi** [comment]
reopening as this is still something we need to fix regardless of the workaround.
