### ISSUE TITLE
AMP Cache SSR breaks amp-sidebar

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#9531]
See hamburger menu on https://ampstart-com.cdn.ampproject.org/c/s/ampstart.com/ as an example.

**Comment by honeybadgerdontcare** [comment]
The Runtime isn't applying ` i-amphtml-display` to the `amp-sidebar` when the hamburger is clicked.

The following amp.css is still being applied because of that
```
[layout=nodisplay]:not(.i-amphtml-display) {
    /* display: none!important; */
}
```
Note this is the hamburger at the top of the page and not the one in the screenshot.

**Comment by cramforce** [comment]
OK, this code is super weird.
https://github.com/ampproject/amphtml/blob/master/src/custom-element.js#L331

Will need to talk to @dvoytenko to find out what is going on.

**Comment by cramforce** [comment]
Hmm, that was #9354. I don't understand why the class is adding `i-amphtml-display` when the intention is for that to be not added. Why is the `toggleLayoutDisplay` method created? Its comment seems wrong, but it is never called?

**Comment by honeybadgerdontcare** [comment]
Ahh thanks for finding that. It was introduced 9 days ago.

@dvoytenko #9354 introduced the new class attribute `i-amphtml-display` for layouts of `nodisplay`. Is this permanent? Should we update the [server-side rendering document](https://docs.google.com/document/d/1gViU1hxtGXwMSTNnum2zY_p9ZWvFwMKoachNdIRUgh0/edit#) that they also need to implement this or is `toggleLayoutDisplay` eventually going to replace it?

While comments can be ignored or overlooked, we might want to have one in that method asking to coordinate changes with server-side rendering, or in the least to function properly even if server-side rendering was applied.

**Comment by cramforce** [comment]
Yes, we should add a very big comment to this function. Dima created a fix for this case.
