### ISSUE TITLE
amp-bind: Some attributes on <input> are initial only, and won't update the input when the attribute is updated

### ISSUE THREAD

**Issue by kmh287** [ampproject/amphtml#9556]
For example. updating the `value` attribute on `<input type="text">` will not update the text in the input if the user has already typed something into the text input. 

/cc @cvializ @choumx @jridgewell

**Comment by cvializ** [comment]
Would the way [#9553 solves this problem](https://github.com/ampproject/amphtml/pull/9553/files#diff-6a804af8fcfeafe72321b2a9c0f8f050) be a good fix, or are there reasons that isn't the best fit?

**Comment by kmh287** [comment]
I think we can find a way to continue using the logic in the default block while still special casing these attributes. Another input attribute pair that acts this way is `<input type=checkbox>`. Setting the `checked` on the element after the user has clicked it does nothing. I'll have a PR up for this shortly. :smile:
