### ISSUE TITLE
amp-map element

### ISSUE THREAD

**Issue by mterenzio** [ampproject/amphtml#956]
Has support for an amp-map element been requested? If only the static map API? My search didn't see any requests yet. 
edit: I do see iframe as the way to go in the "everything" example. Perhaps there is no advantage to an extension.

**Comment by cramforce** [comment]
We're definitely looking into how one could make a more advanced maps experienced, but as you say maps work with `amp-iframe`, static maps should work great with `amp-img` and `amp-click-to-play` should make them work together really well, too.

CC @rudygalfi

**Comment by ericlindley-g** [comment]
Just wanted to ping this thread in the context of eCommerce. Would be useful in the context of listings or contact/directions pages for anything that has a physical location (home/apartment rentals, restaurants, etc).

**Comment by rudygalfi** [comment]
I think using amp-iframe is a good recommendation for this for now. If there's something more sophisticated that folks want here we can re-open and discuss on this issue or in a new issue.
