### ISSUE TITLE
AMP errors

### ISSUE THREAD

**Issue by ChetnaSingh23** [ampproject/amphtml#9579]
[https://www.ampproject.org/latest/blog/bringing-the-speed-of-amp-to-search-display-ads/](url)

AMP errors

![image](https://cloud.githubusercontent.com/assets/24791556/26484885/32d3e37e-4212-11e7-95ff-1c4b78f84fe0.png)

**Comment by honeybadgerdontcare** [comment]
@ChetnaSingh23 Thanks for the report! I've posted this to [ampproject/docs](https://github.com/ampproject/docs) which owns the ampproject website. https://github.com/ampproject/docs/issues/523
