### ISSUE TITLE
Support for pre-roll video ads

### ISSUE THREAD

**Issue by kashyapnitin** [ampproject/amphtml#958]
Can we allow integration of some Video SDKs like the IMA https://developers.google.com/interactive-media-ads/?csw=1 to allow for pre-roll / mid-roll Video ads?

May need changes to the existing amp-video component or a specific amp-video-with-ad component?

**Comment by cramforce** [comment]
I think we should definitely add support into existing `amp-video`. It might completely change the way it works. It might, however, be infeasible and we'd need `amp-ima-video`. To evaluate that we'd need to study other video/ad integrations and see how much they overlap.

**Comment by rudygalfi** [comment]
@jasti Can you put a priority on this? Do you want to move it to a Prioritized FR?

**Comment by jasti** [comment]
Closing in favor of https://github.com/ampproject/amphtml/issues/5233
