### ISSUE TITLE
Twitter component not displaying

### ISSUE THREAD

**Issue by mterenzio** [ampproject/amphtml#959]
Tested On Mac OS X 10.10.1 and 10.9.5 (via browserstack)
Using Firefox 42.0
The twitter components have a width and height being accounted for but are not rendering any content.
Verified this was not a local implementation issue by duplicating it with this production URL:

https://www.theguardian.com/science/2015/sep/28/nasa-water-mars-announcement-reactions/amp

**Comment by cramforce** [comment]
Thanks for the report.

This is an issue with the JSON-via-fragment transfer that appears to be limited to Firefox.

Limited repro case

https://3p.ampproject.net/1447372082206/frame.html#{"conversation":"none","​c​ards":"hidden","tweetid":"648527254725619713","width":486,"height":437,"initialWindowWidth":560,"initialWindowHeight":504,"type":"twitter","_context":{"referrer":"","canonicalUrl":"http://www.theguardian.com/science/2015/sep/28/nasa-water-mars-announcement-reactions","location":{"href":"https://www.theguardian.com/science/2015/sep/28/nasa-water-mars-announcement-reactions/amp"},"mode":{"development":false,"minified":false}}}
