### ISSUE TITLE
Polyfill Event constructor

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#9597]
### First Timers Only
We know figuring out the process for contributing to an open source project can be intimidating, so we created this issue as a way for you to learn the ropes.  (If you feel comfortable contributing to open source projects, please leave this issue for someone else.)

### What you will need to know
- Some familiarity with JavaScript

### Background
[Events](https://developer.mozilla.org/en-US/docs/Web/API/Event) are commonly used in JS and web development. In modern browsers, an `Event` object can be created via the constructor:
```
const event = new Event('myEvent');
```
However, some older browsers (cough, [Internet Explorer](https://developer.mozilla.org/en-US/docs/Web/API/Event/Event#Browser_compatibility)) don't support the Event constructor. On such browsers, events have to be created the ["old fashioned way"](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events#The_old-fashioned_way).

### Motivation
Across the AMP code base, events are created both ways. This means that current code that looks like `new Event()` may have issues for IE users. We should consolidate these usages and add a simple [polyfill](https://en.wikipedia.org/wiki/Polyfill) for the Event constructor. 

> A polyfill is code that implements a feature on web browsers that do not support the feature.

This will:

- Improve code consistency 
- Fix potential bugs due to use of Event constructor for older browsers

### Step by step
- [x] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.
- [x] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [x] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [x] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [x] Create a new file in `src/polyfills/` that polyfills the Event constructor for browsers that don't support it. Check out the other files in that directory as a template.
- [x] Import your new file in `src/polyfills.js` and call the installer function.
- [x] Search AMP codebase for Event creation with `document#createEvent`.
- [x] Replace these usages with our new polyfilled Event constructor.
- [x] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [x] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [x] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review) and request a code review from me (@choumx).  Mention `Fixes #9597` in the description.
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

### Questions?

If you have questions ask in this issue or on your Pull Request (if you've created one) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

**Comment by choumx** [comment]
Note: We currently have a helper that does something similar for `CustomEvent` in `src/event-helper.js`. Another approach is to replace all current usages of `Event` with this helper.

**Comment by mcaveniathor** [comment]
I would like to work on this!

**Comment by choumx** [comment]
@mcaveniathor Great!

**Comment by mrjoro** [comment]
Hi @mcaveniathor are you still planning on working on this issue?  If not we can open it up to others looking for Great First Issues.  Thanks!

**Comment by jongrim** [comment]
I'd like to take this on if available. I believe the [CustomEvent polyfill](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent) can be repurposed to work here.

**Comment by mrjoro** [comment]
Great!  I've added the GFI Claimed! label to let others know someone is working on this; I've also sent you an invite to join the ampproject so we can assign this issue to you.

@choumx can answer any questions you might have about this issue. :)

**Comment by jongrim** [comment]
@choumx I've replaced a usage of `document.createEvent` in `src/custom-element.js` but it seems to be causing 5 tests related to video player events to fail.

The prior call site looked like this:
```javascript
dispatchCustomEvent(name, opt_data) {
      const data = opt_data || {};
      // Constructors of events need to come from the correct window. Sigh.
      const win = this.ownerDocument.defaultView;
      const event = win.document.createEvent('Event');
      event.data = data;
      event.initEvent(name, /* bubbles */ true, /* cancelable */ true);
      this.dispatchEvent(event);
    }
```

I updated it to use the Event constructor, which would be backed by the polyfill I've added, so now it looks like this:
```javascript
dispatchCustomEvent(name, opt_data) {
      const data = opt_data || {};
      // Constructors of events need to come from the correct window. Sigh.
      const win = this.ownerDocument.defaultView;
      const event = new win.Event(name, {bubbles: true, cancelable: true});
      event.data = data;
      this.dispatchEvent(event);
    }
```

I believe this is the proper way to go from using `document.createEvent` to `new Event()` but perhaps I've missed something. Thoughts? Note that I'm running the tests in Chrome 59, so this wouldn't even be falling back to the polyfill.

Also - quick side note. This is the only usage I found of `document.createEvent` in the `src/` folder (which I'm assuming has the entirety of the codebase). The exception being the code in `src/event-helper.js` that you mentioned previously, but I didn't think that should be changed. Let me know if that's incorrect.

**Comment by choumx** [comment]
@jongrim Do you have a link to the test failures? I'd have to see the specific error message.

We do have code outside of the `src/` folder. Check `extensions/` and `test/` in particular, which contain AMP extensions and test code, respectively.

Thanks for working on this!

**Comment by jongrim** [comment]
No problem, I'm excited to contribute! [Here's the output of the 5 failing tests](https://gist.github.com/jongrim/f79895f8a37f824eae05e2cf8088a399).

**Comment by choumx** [comment]
@jongrim Hmm, looks like those failures might be relevant since [the tests](https://github.com/ampproject/amphtml/blob/92d78c29dbdb50d5e59175718b1dd8f181c54712/test/functional/test-video-manager.js#L88) listen for event dispatch. I can take a closer look -- did you create a PR yet?

**Comment by jongrim** [comment]
@choumx I just opened one, #10401. I wasn't able to add you as a reviewer myself, so I guess that has to be assigned separately.

I'll keep taking a look at it to see if I can make any progress, but if you can look deeper into what's causing these to fail that'd be great! Thanks.
