### ISSUE TITLE
Which Node versions are supported?

### ISSUE THREAD

**Issue by taymonbeal** [ampproject/amphtml#9619]
This question has now been raised multiple times on Slack without an answer determined. @erwinmombay and @jridgewell, at least, have said different things about it. I would like to get a canonical answer once and for all and then align the Travis settings with it.

Which version of Node do we officially support for the AMP build tooling?

**Comment by jridgewell** [comment]
Node v4. Validator supports back to v0.10 for archaic ubuntu reasons, but that's their decision.
