### ISSUE TITLE
Validator: allow additional amp-keyframes style

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/amphtml#9625]
The goal is to allow a bigger `<style>` aimed for animations. Animations are often bigger in size due to heavy use of vendor prefixes and due to high detail in mutations. On the plus side, however, keyframes animations do not affect the critical rendering path.

The format will be:
```
<style amp-keyframes>
</style>
```

The following rules will be applied to this tag:
 1. The `amp-keyframes` style will only be allowed to contain `@keyframes` and `@media`/`@supports` with `@keyframes` rules and their vendor-prefixed versions.
 2. The maximum allowed size for this style tag is 200K
 3. Must be at the bottom of the document. In other words, it should come after all content elements.

Thus, a valid markup could look something like this:
```
<style amp-keyframes>
@keyframes anim1 {
  0% {transform: translateX(-100%);}
  100% {transform: translateX(100%);}
}
@-webkit-keyframes anim1 {
  0% {transform: translateX(-100%);}
  100% {transform: translateX(100%);}
}
@media (min-width: 300px) {
  @keyframes anim1 {
    0% {transform: translateX(-200%);}
    100% {transform: translateX(200%);}
  }
}
@supports (offset-distance: 0) {
  @keyframes anim1 {
    0% {offset-distance: 0}
    100% {offset-distance: 100%}
  }
}
</style>
```

**Comment by Gregable** [comment]
Will this be allowed for Amp Ads documents?

**Comment by dvoytenko** [comment]
Yes. Primary use case, in fact.

**Comment by chenshay** [comment]
Also this: https://github.com/ampproject/amphtml/issues/11430

**Comment by Gregable** [comment]
This validator change is now live everywhere.
