### ISSUE TITLE
isSafari() is wrong in standalone mode (added to Homescreen in iOS) 

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#9627]
When a app-like page (e.g. with `<meta name="apple-mobile-web-app-capable" content="yes">`) is added to Homescreen in iOS, it opens in "standalone" mode (without addressbar, etc..).

The issue is, in that case the UA string does not have the word `safari` in it (otherwise it is identical). Our `isSafari` checks for `safari` text.'

Added to homescreen as standalone app (must be `apple-mobile-web-app-capable`)
```
Mozilla/5.0 (iPhone; CPU iPhone OS 8_1_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12B436
```

Normal in safari
```
Mozilla/5.0 (iPhone; CPU iPhone OS 8_1_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B436 Safari/600.1.4
```

**Comment by jridgewell** [comment]
Can you posts a sample UA?

**Comment by aghassemi** [comment]
added to description of the issue

**Comment by aghassemi** [comment]
Closed by https://github.com/ampproject/amphtml/issues/9934
