### ISSUE TITLE
check-links.js should allow for links that are within the PR

### ISSUE THREAD

**Issue by honeybadgerdontcare** [ampproject/amphtml#9628]
In #9434 a new component is introduced that includes the validator protoascii and the markdown describing how to use it. All component markdown files link to the validator protoascii for reference. However, [check-links.js](https://github.com/ampproject/amphtml/blob/master/build-system/tasks/check-links.js) is showing an error because that link doesn't exist. While technically correct it would be false once the PR is merged.

Potential solutions:
- change check-links to emit a warning instead of an error
- if a deadlink is suspected and it is for a link to `github.com/ampproject/amphtml/blob/master` then check to see if the file exists within the PR

Here's the error
```
[03:46:11] Checking links in extensions/amp-imgur/amp-imgur.md ...
[03:46:11] [✖] https://github.com/ampproject/amphtml/blob/master/extensions/amp-imgur/0.1/validator-amp-imgur.protoascii
[03:46:11] ERROR Possible dead link(s) found in extensions/amp-imgur/amp-imgur.md (please update, or whitelist in build-system/tasks/check-links.js).
[03:46:11] ERROR Possible dead link(s) found. Please update, or whitelist in build-system/tasks/check-links.js. extensions/amp-imgur/amp-imgur.md
```

Note that `extensions/amp-imgur/0.1/validator-amp-imgur.protoascii` is a new file within PR #9434.

**Comment by rsimha-amp** [comment]
@honeybadgerdontcare: interesting issue, thanks for filing it. We used to have check-links.js emit a warning instead of an error, but that ended up allowing bad links to slip through unnoticed.

I'm pretty sure it should be possible to implement an exception for links to new files being added in the same PR. Meanwhile, sorry you had to take the roundabout path of temporarily adding an exception to the whitelist.

**Comment by rsimha-amp** [comment]
@honeybadgerdontcare, note that the fix only checks for the base name of the file being added in the PR, and not the entire `github.com/ampproject/amphtml/blob/master` URL. This is to account for the case where an existing file `foo.md` adds a link to a file `bar.md` in the same directory, which is added by the same PR.

This may allow corner cases to slip through when they should fail (like adding a file `foo.md` and adding a broken link `foo-foo.md`), but I'd rather be conservative and let them through to be caught later, than block a genuine PR.

Let me know if you see anything awry in the future.

**Comment by rsimha-amp** [comment]
FYI @mrjoro, who frequently changes our documentation :)
