### ISSUE TITLE
Empty ad analytics event

### ISSUE THREAD

**Issue by bjalford** [ampproject/amphtml#9632]
Primarily to detect adblocking, would it be possible to fire an analytics event if the amp-ad doesn't get filled?

**Comment by rudygalfi** [comment]
Could you post more information about the kind of analytics event you would like to have fire (e.g. trigger type)?

**Comment by jasti** [comment]
@bjalford  Since amp-ads are served into cross domain iframes (most of the time), I doubt if we can detect such a thing consistently. This especially changes depending how the ad is being blocked, right? @lannka for confirmation.

**Comment by rudygalfi** [comment]
To @lannka to confirm

**Comment by lannka** [comment]
I did some experiments, ad blocker blocks HTTP requests, for which the errors are not catchable by javascript. So I don't see a way to detect such a block.

@bjalford Please advice if you have other idea for javascript to catch such a block.

**Comment by jasti** [comment]
@bjalford closing for now, but please reopen if you think there is a way to detect the ad blocker.
