### ISSUE TITLE
All common `gulp` commands should be able to run from a clean state

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#9640]
Currently it's necessary to run `gulp build --css-only` before `gulp dist` to avoid errors like:
```sh
Error compiling ./src/service-worker/kill.js
WARNING - Failed to load module "../../../build/amp-ad-0.1.css.js"
WARNING - Failed to load module "../../../build/amp-form-0.1.css.js"
0 error(s), 2 warning(s)
```
The issue is missing extension-specific CSS*, however `gulp build` also does a bunch of work in addition to that. We can speed up our builds by making sure that `compileCss()` and `buildExtensions()` (CSS only) are run before compiling entry points.

*Another option is to figure out why extension-specific CSS is necessary for building srcs like service-worker. First guess is the quirk that Closure compiler (compile.js) checks the existence of the list of source files to build.

/cc @rsimha-amp @erwinmombay

**Comment by choumx** [comment]
Turns out this is a bit more involved than I anticipated. 😅  

I have a PR that fixes a [related bug in compile()]( https://github.com/ampproject/amphtml/blame/fb78cfbcd0fa00dc3e45a319c49a1274df5caf1b/gulpfile.js#L205) that gets us going in the right direction. The rest I'll leave /to @rsimha-amp

**Comment by rsimha-amp** [comment]
One more piece of work needed before we eliminated the need for `gulp build` before `gulp dist`. Coming up in #9741
