### ISSUE TITLE
Validator smoke tests failing on master

### ISSUE THREAD

**Issue by rsimha-amp** [ampproject/amphtml#9653]
Error message: `Smoke test failed. returncode=1 stdout="" stderr="c.includes is not a function`

See https://travis-ci.org/ampproject/amphtml/jobs/238116751, for example

These tests pass locally.

**Comment by jridgewell** [comment]
- https://github.com/ampproject/amphtml/blob/8d71e34b6bebda8cca67ec6ae7accb153c591a53/validator/engine/validator.js#L840
- https://github.com/ampproject/amphtml/blob/8d71e34b6bebda8cca67ec6ae7accb153c591a53/validator/engine/validator.js#L862
- https://github.com/ampproject/amphtml/blob/8d71e34b6bebda8cca67ec6ae7accb153c591a53/validator/engine/validator.js#L2809
- https://github.com/ampproject/amphtml/blob/8d71e34b6bebda8cca67ec6ae7accb153c591a53/validator/engine/validator.js#L3299
- https://github.com/ampproject/amphtml/blob/8d71e34b6bebda8cca67ec6ae7accb153c591a53/validator/engine/validator.js#L3985

**Comment by rsimha-amp** [comment]
This is due to @jridgewell moving to Node v4 on Travis. Assigning to you :)
