### ISSUE TITLE
Do not allow <amp-iframe> pop ups.

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#9659]
Sample: https://amp-demo-5c971.firebaseapp.com/article.amp.html
We might consider allowing this on user interaction, but probably should only do that for whitelisted AMP components and not amp-iframe.

**Comment by zhouyx** [comment]
We do have `isAdLike` function that detect most common ad sizes `[[300, 250], [320, 50], [300, 50], [320, 100]]`. 
However in the given example the width and height are [320, 520] and we fail to detect it.

**Comment by lannka** [comment]
I read this as to either
a) build more heuristics to detect an ad like amp-iframe
or
b) disallow any fixed floating position of an amp-iframe

For a), we're relying on a naive "ad like sizes" check, which can be easily bypassed by developer if they spent a minute in our code base. Sure, we can still add [320, 520] to the list.

For b), would that kill existing valid use cases? We need a good thinking here.

@cramforce

**Comment by cramforce** [comment]
We certainly can't do b. We **might** be able to do it for a new version of `amp-iframe` (1.0), but I'm not convinced it is a good idea.

**Comment by jridgewell** [comment]
For a), looks do a slightly smarter check. Instead of `[320, 520]`, assert that it's not fixed-position and full screen (some arbitrary percentage, like `> 90%` width and height).

**Comment by lannka** [comment]
Agreed.

But overall, I don't feel we need to further hack around the size constraints. For this case, publisher intentionally wants floating ads, and we hardly can stop them.

**Comment by lannka** [comment]
@jasti what do you think? Can we close it for now?

**Comment by jasti** [comment]
"For this case, publisher intentionally wants floating ads, and we hardly can stop them."
@lannka not convinced with the reasoning. Checks that help with better user experience is the reason we have AMP!
I like @jridgewell's idea to check to check for  "full screen" size (some arbitrary percentage, like > 90% width and height). Is that feasible?

**Comment by lannka** [comment]
That means:
- pub can have floating ads of size < 90% of the screen
- pub cannot legitimate popups occupying > 90% of the screen.

Again, this will be a breaking behavior change.

**Comment by jasti** [comment]
Pub can have floating ads of size < 90% of the screen
 - This in addition with common ad sizes combined would make a pretty good coverage. 
pub cannot legitimate popups occupying > 90% of the screen.
- Is there a way to programmatically detect such usage? Worst case we can make it a 1.0 thing, but I have a feeling this pattern is not really common in AMP pages.

**Comment by lannka** [comment]
As discussed offline, will close this for now.
