### ISSUE TITLE
Support passing arbitrary messages into amp-iframe

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/amphtml#9663]
Primary goal from format perspective is to support more interactivity between parent page and iframed content. Would be useful for highly interactive journalism (scroll-driven storytelling, data visualizations toggled by page-level filters), but is expected to have a wide range of applications beyond that.

Might also consider taking arbitrary messages passed * out of * amp-iframe, but would need to make sure these aren't executed as code in any way that violates the assumptions of AMP

/cc @aghassemi @choumx   for thoughts

**Comment by aghassemi** [comment]
very similar to https://github.com/ampproject/amphtml/issues/9074 same approach can work for both use-cases.

**Comment by ericlindley-g** [comment]
Ah yes — I had seen that but forgot we were already tracking. Will close this as dupe

**Comment by aghassemi** [comment]
updated #9074 to include description of this as well as a goal.
