### ISSUE TITLE
Disable loading indicators inside embeds

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#9664]
Embeds (including ads) have a pre-display placeholders. Loading indicators are redundant in this case.

Issue partially in response to #7952

**Comment by jasti** [comment]
@alanorozco Not sure I understand. Can you point me to an Embed having a pre-display placeholder?

**Comment by alanorozco** [comment]
By a "pre-display placeholder" I mean the placeholder that says "Ad" on ad embeds, for example.
