### ISSUE TITLE
Remove input-debounced experiment

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#9670]
Chatted with Malte and we are comfortable launching this event.
We should remove it before doing the sample on AmpByExample (https://github.com/ampproject/amp-by-example/issues/852)

/to @cvializ 
/cc @ericlindley-g

**Comment by ericlindley-g** [comment]
Sounds good—excited to see this live

**Comment by cvializ** [comment]
Cool!  🎉🎉🎉
