### ISSUE TITLE
Option to add tracking parameters dynamically through data-amp-addparams for links on anchour tags

### ISSUE THREAD

**Issue by rajkumarsrk** [ampproject/amphtml#9673]
## What's the issue?
Providing option to add tracking data along with the destination URL for source attribution. This is a feature request on top of https://github.com/ampproject/amphtml/pull/9086

## How do we reproduce the issue?
With this PR https://github.com/ampproject/amphtml/pull/9086 we have provided option to add the query params dynamically provided `data-amp-replace` is present. But for case where we dont have `data-amp-replace`  and have only `data-amp-addparams` the additional parameters specificied under `data-amp-addparams` is not getting appended to the destination URL
Providing this support will help to get details on the source attribution as these parameters are manily for tracking purpose 

Example:
`<a href="https://www.ebay.com/b/Nike-Athletic-Shoes-for-Men/15709/bn_58800" data-amp-addparams="_trksid=p2376289.m4213.l8401">Nike</a>`

Destination URL will turned into https://www.ebay.com/b/Nike-Athletic-Shoes-for-Men/15709/bn_58800?_trksid=p2376289.m4213.l8401

**Comment by jridgewell** [comment]
Sounds fine, can you do this one too?

**Comment by rajkumarsrk** [comment]
Sure. I can take it

**Comment by rajkumarsrk** [comment]
@adelinamart The feature has been added and this issue can be resolved. 
https://github.com/ampproject/amphtml/pull/9684
