### ISSUE TITLE
Can we allow amp-list to accept object instead of arrays in the json?

### ISSUE THREAD

**Issue by jpettitt** [ampproject/amphtml#9687]
Right now `amp-list` is limited to handling responses that return an array somewhere in the json, it then iterates the array populating a template for each element.

Would it be possible to have it also accept non array values?  In the case where the response was not an array it would treat it as a single entry array and populate the template once. This might be as simple as when the target is not an array just wrapping it in one rather than throwing an error. 
 
This would greatly increase the use cases for amp-list with existing API endpoints.

**Comment by aghassemi** [comment]
@jpettitt sounds good to me.

after this change, it might be a good time to introduce an alias for `amp-list` to make this more semantic. Maybe:
1. `amp-template-renderer`?
2. `amp-mustache-renderer`?
3. `amp-partial` ?
4. `amp-remote-renderer`?

(this will be purely an alias, both amp-list and this will behave exactly the same. In documentation we will target them for different use-cases)

@cramforce opinions on naming?
/cc @ericlindley-g

**Comment by cramforce** [comment]
We cannot rename `amp-list` or I would lose me example for the worst named AMP extension :)

I'm all for this. `amp-partial` is great. I'm also happy to make that an alias and retrofit `amp-list` to support the non-list case.

**Comment by jpettitt** [comment]
I'm going to fix this one. I have an implementation question:

Should I silently convert non array values to array or should I add a flag to trigger the behavior?    

Silently converting has the potential to be a breaking change ...

**Comment by cramforce** [comment]
How do you want to disambiguate object-with-items-attribute as opposed to normal object?

**Comment by jpettitt** [comment]
In the silent fix scenario if the `items` elements exists and it's not an array wrap it in one.

In the explicit flag scenario add an attribute `single-result` that tells `amp-list` that whatever is specified by the `items` attribute is not an array (and internally wrap it in one)

I'm leaning towards the second option the more I think about it. I'm not attached to the flag name - suggestions?

**Comment by cramforce** [comment]
Me, too. We could tell the attribute `not-actually-a-list` :)

Or rake the plunge and make `amp-render`

**Comment by jpettitt** [comment]
`amp-render` seems like overkill and also invokes a risk of bike shedding what should be a very minor change.  I kinda like `not-actually-a-list` - I'll use that unless I hear otherwise.

**Comment by aghassemi** [comment]
Agree with attribute, but let's not call it 'not-actually-a-list' :) `single-result` sgtm.

**Comment by jpettitt** [comment]
Any objection to adding a `max-length` attribute too?  This would limit the number of list items rendered in the case where a much longer list is returned.  Again the issue here is making it easier to support existing endpoints.  The specific use case I have in mind is limiting to 1 item but it's easy enough to make int arbitrary.   It's 4 lines of code.

**Comment by aghassemi** [comment]
sgtm, maybe `max-items`?

**Comment by jpettitt** [comment]
@aghassemi I used max-length in the pull request - want me to change it?

**Comment by aghassemi** [comment]
given `items` is used throughout this component, `max-items` would be more consistent. Would appreciate if you could change it in the PR.

**Comment by jpettitt** [comment]
Change made.

![image](https://user-images.githubusercontent.com/524856/30230528-8e5865a4-949b-11e7-9535-caf1230bf4f0.png)

**Comment by mattwomple** [comment]
Does `single-result` work as expected in conjunction with `items="."` ? Given the following object:

    {
      "title":"mytitle",
      "iterable": [
        {
          "item1":"thing1",
          "item2":"thing2"
        }
      ]
    }

I expected `<amp-list single-origin items="." ...>` to process the following:

    [{
      "title":"mytitle",
      "iterable": [
        {
          "item1":"thing1",
          "item2":"thing2"
        }
      ]
    }]

Am I interpreting the combination of these attributes wrong?

**Comment by aghassemi** [comment]
@mattwomple will be in prod next Wednesday

**Comment by AndrewKGuan** [comment]
Hi all,
quick check on the status and documentation of this change, is it all ready?

**Comment by aghassemi** [comment]
@AndrewKGuan , yes. See `single-item` attribute on the documentation: https://www.ampproject.org/docs/reference/components/amp-list

**Comment by AndrewKGuan** [comment]
Thanks, Ali!
