### ISSUE TITLE
Pass page view id and a client identifier to ads, analytics, etc.

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#969]
We need a general variable available to amp-pixel, analytics, ads, that is "unique" (Just Math.random should be fine) per page view. So, just a random number we create once per page.

This is a change in
https://github.com/ampproject/amphtml/blob/master/src/url-replacements.js

Some ads require access to a CID. Create configuration per ad network for the fallbackCookieName. Will need to figure out how to get consent in this case.

CC @rudygalfi @kashyapnitin @avimehta

**Comment by veganjosh** [comment]
Is this intended to function only as a cachebuster? Math.random() isn't nearly high enough entropy, in our experience, to function as unique pageview ID (across hundreds of billions of pageviews)

**Comment by avimehta** [comment]
how about <timestamp>.<random>? Would that make uniqueness a little easier to achieve?

**Comment by cramforce** [comment]
Unique is a bit of a complicated concept :)

Anyway, good feedback. 

How much entropy do you need? Are 64bit enough or do you need 128bit?

**Comment by cramforce** [comment]
64bit should be enough for ultra-likely-unique-per-week :)

**Comment by cramforce** [comment]
Actually, shouldn't Math.random be completely sufficient? Its only needs to be unique per client identifier.

**Comment by avimehta** [comment]
@cramforce you are right. Client id + page id are probably going to be
enough uniqueness.

**Comment by veganjosh** [comment]
Being unique in combination with client ID is fine for our applications, this should just make sure to specify that this is _not_ unique on its own.

Just as a quick note for those who care, you start getting collisions in the low billions of items with 64 bits of entropy (https://en.wikipedia.org/wiki/Birthday_problem):
P(collision exists amongst n items getting getting hashed into d buckets) ~= 1 - exp(-n^2/2d)
So, for instance, if n = 8 billion (2^33) and d = 2^64, you have the probability of collision at:
1 - exp(- (2^33)^2 / (2*(2^64)) = 1 - exp(- (2^66) / (2^65)) ~= 86%

**Comment by cramforce** [comment]
Cool. Will make sure to document.

**Comment by rudygalfi** [comment]
[Renamed issue to reflect that this applies to cases other than just ads.]

**Comment by rudygalfi** [comment]
@cramforce What's the status/timing of completing this?

**Comment by cramforce** [comment]
#977 is out for review, but hasn't gotten any review love while I was on vacation :)

**Comment by cramforce** [comment]
Page view id landed.

Exposing the client identifier is next.

**Comment by cramforce** [comment]
Fixed by #1146
