### ISSUE TITLE
Upgrade to Babel 6

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#9695]
Babel 6 offers a number of features (bug fixes, and speedups, and more ES* compatibility), but really the biggest thing it offers is [babel-preset-env](https://github.com/babel/babel-preset-env).

Essentially, `babel-preset-env` allows us to tailor our development build to the browser we're running. Instead of compiling every ES6 feature down to ES5, we can run the ES6 features Chrome supports and compile just the ones that it doesn't. This leads to easier test debugger and smaller files since we'll be stepping over the _actual_ code we wrote.

When we're doing integration testing (or local testing on another browser), we'll need to be able to customize the browser support. So for Travis, we can do a full compile of every feature. And for local, we can just flip it to support Safari X, or whatever browser we want.

**Comment by erwinmombay** [comment]
ill take this. i have something working with webpack + babel6 but the build is slower than the current setup
