### ISSUE TITLE
autocomplete: ABE - Product browse page: Rich auto suggest integration

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#9698]
Bring ampproject/amphtml#9553 to AmpByExample by implementing an autocomplete feature for the Product browse page's search functionality.

Ideally the suggestion list is rich and includes additional details such as price, photo, etc.. of the matched items.

/to @cvializ
/cc @ericlindley-g

**Comment by ericlindley-g** [comment]
+1

Basic need here is for a set of broad search terms that are autocompleted (can come with bells and whistles like bolding of the portion of the word that is already filled out by the user). A key use-case for this is to get recommendations for broad types of items or categories that one would search for on a retail site. (e.g. "shoes" or "umbrella"). Once the user taps on such a term, it could automatically trigger the search for that term, or enter that term into the search box in full, so the user has an additional tap to actually trigger the search.  (ideal behavior is the option to do both, like the chrome autocomplete behavior, where tapping on the main body of the term will trigger search, but tapping on the arrow icon at far right will put the suggested term into the body of the form, for further refinement of the search)

Secondary need is auto-suggested results that could bypass the search mechanic entirely (I believe this is what @aghassemi describes). The user begins searching with a partial term like "sho". Then, not only are there auto-suggested search queries like "shoes", "hiking shoes", etc, but also rich auto-suggested results: for instance, a tappable item in the auto-suggest drop-down that includes a thumbnail image of the item, star rating, price, and availability.

We should definitely make the basic need happen (this is the primary request from developers), but the secondary need would be great to demo as well.

Does that square with what others are thinking, too? @cvializ  @aghassemi  ?

**Comment by aghassemi** [comment]
@ericlindley-g @cvializ Basic autocomplete with two triggers (one to trigger search and one to just put the suggestion in the input) sounds good to me and should be possible by bringing `amp-bind` into this mix. Highlighting the matched part is the only thing I am not sure is possible (might be by some creative use of `amp-bind`). FWIW native Android Google Search App does not highlight the letters matched in its autocomplete ( web version does ).

**Comment by aghassemi** [comment]
3

**Comment by cvializ** [comment]
Looks like it's shipped. https://ampbyexample.com/samples_templates/autosuggest/
Closing unless there was something missed in that example.

**Comment by ericlindley-g** [comment]
Awesome! 
 How easy would it be to make the following two tweaks?

- highlight autosuggest rows on hover

- dismiss suggestions by clicking outside of form?  (maybe by only showing suggestions when input is focused?)

**Comment by cvializ** [comment]
😀 Not too difficult. Also adding a tweak to make sure the browser default suggestions don't appear

**Comment by cvializ** [comment]
Dismissing the suggestions works in a standalone page, and when you click outside of the input and overlay, but not when clicking outside of the example box on ABE.

**Comment by cvializ** [comment]
Oh I misread this issue, this is for the product page. That is still pending

**Comment by ericlindley-g** [comment]
Ah—I misread too!  :P  Thanks either way (disable default suggestions is a good call)

**Comment by aghassemi** [comment]
asking ABE team to do the integration with product page: https://github.com/ampproject/amp-by-example/issues/936
