### ISSUE TITLE
How to magange of user notification time cookies

### ISSUE THREAD

**Issue by pachori01shubha** [ampproject/amphtml#9709]
Hi

Task  : I have to reopen user notification popup or we can say notification box after every 5 to 6 hours  .
Query : how to define time for cookies of google amp user notification box 
thanks
shubha

**Comment by erwinmombay** [comment]
@pachori01shubha couldnt you return `{ "showNotification": true }` from the endpoint or specifically do you mean when we store the value in local storage?

**Comment by jridgewell** [comment]
I think he's asking for after the user has already accepted the terms. Right now, we never show the notification again.

**Comment by shubha01** [comment]
actually i asking that how we generate user notification popup after every 5 to 6 hours

**Comment by shubha01** [comment]
hi i  am returning this { "showNotification": true }to frontend but my question is  amp-user-notification create cookies for a 1 year as it a default cookie time limit if i want to add cookies for less time suppose 1 month only how to do this

**Comment by rsimha** [comment]
@aghassemi Is this still worth doing?

**Comment by aghassemi** [comment]
Moved to UI, was misclasified

**Comment by aghassemi** [comment]
this has to be handled on the server endpoints. Using CID + storing a last displayed time on your own database is one way.
