### ISSUE TITLE
Missing external link from content

### ISSUE THREAD

**Issue by jamesek** [ampproject/amphtml#9711]
## What's the issue?

Missing external link in content.

## How do we reproduce the issue?

Compare two simple links:
https://rychlofky.wordpress.com/2017/06/02/slusni-lide-na-facebooku-analyzovani-josefem-slerkou/
https://rychlofky.wordpress.com/2017/06/02/slusni-lide-na-facebooku-analyzovani-josefem-slerkou/amp/

You can see missing first very important link.

<img width="268" alt="snimek obrazovky 2017-06-04 v 10 10 07" src="https://cloud.githubusercontent.com/assets/12596070/26760106/ce3bb364-4910-11e7-84c8-5254de4d83ea.png">
<img width="253" alt="snimek obrazovky 2017-06-04 v 10 09 39" src="https://cloud.githubusercontent.com/assets/12596070/26760105/cb5ae232-4910-11e7-8204-f01f83e74f58.png">

## What browsers are affected?

Founded on mobile safari, but confirm in mac safari too.

## Which AMP version is affected?

amp-version	1496245713200

**Comment by jridgewell** [comment]
This appears to have corrected itself.

**Comment by DanielDocekal** [comment]
No, i am sorry to say, it did not corrected itself. It still eats links in amp which are ok in normal page. Look at end of that paragraf.  Still needs to be fixed 

![2017-06-06 20_38_34-slusni lide na facebooku analyzovani josefem slerkou _ rychlofky](https://user-images.githubusercontent.com/29236775/26845876-3505aca6-4af8-11e7-9d25-abbfc528b205.png)

First link (at beginning of paragraph) will be ok in AMP version.
Second link (at end of paragraph) will disappear.

**Comment by jridgewell** [comment]
Moved to https://github.com/Automattic/amp-wp/issues/707. This is a WordPress output issue, not AMP's.

**Comment by justingoldberg** [comment]
Here's another url with no link to the original url.

https://www-vulture-com.cdn.ampproject.org/v/www.vulture.com/amp/2018/06/black-jeopardy-saturday-night-live-oral-history.html?amp_js_v=a2&amp_gsa=1#amp_tf=From%20%251%24s&ampshare=http%3A%2F%2Fwww.vulture.com%2F2018%2F06%2Fblack-jeopardy-saturday-night-live-oral-history.html
