### ISSUE TITLE
Disable loading of non-critical page content on very slow connections

### ISSUE THREAD

**Issue by SchnWalter** [ampproject/amphtml#9712]
## What's the issue?

It sometimes makes sense to put emphasis on the user experience by never loading certain resources, or loading them on request (a user clicks a "Play Video" button -- displayed inside the `fallback` content, with visibility controlled by an `on-load-add-class` attribute similar to how `amp-font` works)

For example, it would be nice to have the option to disable loading of Ads when the page is viewed on _very slow connections_, like in Third World Countries, where the bandwidth is narrow and expensive (and the bandwidth required to load an Ad, probably costs a lot more then the Ad could ever generate).

Currently, all AMP extensions (custom elements) need to be "defined" in the header so that the custom-elements can be [stubbed](https://github.com/ampproject/amphtml/blob/5ea68bce24d798ee0eedfba8bff51dace4cbfde6/src/custom-element.js#L162-L177). And instead of defining all elements in the html head tag using script tags, e.g.:
```
<script custom-element="amp-ad" src="https://cdn.ampproject.org/v0/amp-ad-0.1.js" async></script>
<script custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js" async></script>
<script custom-element="amp-font" src="https://cdn.ampproject.org/v0/amp-font-0.1.js" async></script>
<script custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js" async></script>
<script custom-element="amp-sidebar" src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js" async></script>
<script custom-element="amp-vimeo" src="https://cdn.ampproject.org/v0/amp-vimeo-0.1.js" async></script>
<script custom-element="amp-youtube" src="https://cdn.ampproject.org/v0/amp-youtube-0.1.js" async></script>
```
one could only define certain script tags and have others loaded upon certain conditions. For example:
```
<script type="application/json" custom-elements-definition>
{
  "amp-youtube": {
    "src": "https://cdn.ampproject.org/v0/amp-youtube-0.1.js",
    "optional": "true",
    "load-condition": "on-event:load-youtube-dependencies"
    "on-load-add-class": "amp-youtube-loaded",
    "on-load-remove-class": "amp-youtube-not-loaded"
  },
  "amp-vimeo": {
    "src": "https://cdn.ampproject.org/v0/amp-vimeo-0.1.js",
    "optional": "true",
    "load-condition": "on-event:DOMContentLoaded"
    "on-load-add-class": "amp-vimeo-loaded",
    "on-load-remove-class": "amp-vimeo-not-loaded"
  },
  "amp-ad": {
    "src": "https://cdn.ampproject.org/v0/amp-vimeo-0.1.js",
    "optional": "true",
    "load-condition": "ONLY_ON_FAST_CONNECTIONS"
  }
}
</script>
```

I see the phrase "_very slow connection_" defined as a very large delta between the first received byte and DOMContentLoaded event or something on those lines, or maybe another event.

The `ONLY_ON_FAST_CONNECTIONS` load-condition would be adjusted using a custom attribute, similar to how the `amp-font[timeout]` attribute works.

## How do we reproduce the issue?

1. Use a slow internet connection or simulate one in DevTools (or you can use _WebPageTest_ with a  connection set to _Emerging Markets 3G_)
2. Navigate to an AMP document, or just load one directly (by-passing the AMP cache)
3. Look at the requests and you will see that there are many resources that might not be considered "not essential" and could be deffered or disabled completely.

Here's an example of an AMP page from theguardian.com that is loaded using a simulated _Emerging Markets 3G_ connection. You can clearly see that a couple of tweaks on these lines could help improve the initial page load time by a lot: http://www.webpagetest.org/result/170604_G4_K6P/

## What browsers are affected?

All browsers on slow connections.

## Which AMP version is affected?

All, as of today (2017-06-04)

**Comment by SchnWalter** [comment]
The `<script type="application/json" custom-elements-definition>` could also be used just to stub elements in the header and then include the scripts in the body footer, this would make sure that main AMP script is always loaded before all other scripts.

**Comment by cramforce** [comment]
@SchnWalter We have plans to experiment with a variation of your proposal as an AMP Cache rewrite later this year.

Did you know that the AMP Cache supports a "lite" mode? It is currently used when linking to AMP pages from Google's lite search product.

**Comment by choumx** [comment]
Seems like the right layer to solve this is at the embedder (AMP viewer) or browser layer (e.g. Chrome data saver). Closing for now -- please reopen as desired.
