### ISSUE TITLE
Promote CID related code to core (out of amp-analytics)

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#9713]
### First Timers Only
We know figuring out the process for contributing to an open source project can be intimidating, so we created this issue as a way for you to learn the ropes.  (If you feel comfortable contributing to open source projects, please leave this issue for someone else.)

### What you will need to know
- Some familiarity with JavaScript

### Background
[What is CID?](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#client-id) 

### Motivation
When introduced, CID was only used in `amp-analytics`. So the corresponding logic is kept inside `amp-analytics` extension.
However, many extensions need CID, hence depend on amp-analyitcs to load. We could remove the dependencies once get CID promoted to core.
- amp-user-notification
- amp-ad
- amp-access
- Any place needs CLIENT_ID in URL substitution

See original issue #4898

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] Move [cid-impl.js](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/cid-impl.js) to `src/`, and update all the references.
- [ ] You might also move all its dependencies (if any) and tests over to corresponding place.
- [ ] Do some manual test and sanity check.
- [ ] Update the descriptions of those the extension who currently depend on amp-analytics to load. 
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review) and request a code review from me (@lannka).  Mention `Fixes #9713 ` in the description.
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

### Questions?

If you have questions ask in this issue or on your Pull Request (if you've created one) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

**Comment by ui-xp** [comment]
'First issuer' here, reporting for duty.

**Comment by ui-xp** [comment]
Pushed [here](https://github.com/ampproject/amphtml/pull/9760)

**Comment by mrjoro** [comment]
Thanks @ui-xp!  Welcome to the community. :)

**Comment by mrjoro** [comment]
@ui-xp I sent you an invitation to join ampproject on GitHub; once you accept we'll be able to assign this issue to you.  Thanks!

**Comment by ui-xp** [comment]
Done in https://github.com/ampproject/amphtml/pull/9911

**Comment by mrjoro** [comment]
Thanks for making your first contribution to AMP @ui-xp.  If you haven't already found your next project in AMP and want some help finding one let me know (you can send me a DM on Slack). :)
