### ISSUE TITLE
Support variable substitution for user agent

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#9722]
### First Timers Only
We know figuring out the process for contributing to an open source project can be intimidating, so we created this issue as a way for you to learn the ropes.  (If you feel comfortable contributing to open source projects, please leave this issue for someone else.)

### What you will need to know
- Some familiarity with JavaScript

### Background
[How AMP support variable substitutions in various features](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md)

### Motivation
When first implemented the variable substitution feature, we didn't add support to user agent, because it can be done with the user-agent header in every request. 

Some publishers however would like to collect the full user agent string as part of their analytics assessment. We are adding support to variable substitution for user agent.

Ref Issue #5050

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] Search for an existing substitute variable that we support.  (For example: [BROWSER_LANGUAGE](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md#browser-language)).  Follow the implementing strategy of it and find all files that needs to be changed. 
- [ ] Do some manual test and sanity check to make sure everything works.
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] You may also need to add unit test to `test-url-replacements.js`.
- [ ] Document the new supported variable to `amp-var-substitutions.md`.
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review) and request a code review from me (@zhouyx).  Mention `Fixes #9722 ` in the description.
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

### Questions?

If you have questions ask in this issue or on your Pull Request (if you've created one) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

**Comment by saqibnaveed** [comment]
Hello, I am a Jr. developer, I want to contribute to this issue.

Kindly guide me

**Comment by zhouyx** [comment]
@saqibnaveed Great!

**Comment by zhouyx** [comment]
@saqibnaveed Thanks for claiming this issue. Is there any update on this? Please let me know if you need any help.

**Comment by saqibnaveed** [comment]
@zhouyx , sorry for the delay. I got caught up with task at my workplace. I want to handle this issue, I will give you update by tomorrow
Thanks

**Comment by saqibnaveed** [comment]
I have found a way to add user_agent in the url-replacement-impl file. I will add and test it and will send a pull request. Thanks

**Comment by mrjoro** [comment]
Hi @saqibnaveed I sent you an invitation to join ampproject on GitHub; once you accept that you can assign this issue to yourself.  Thanks!

**Comment by saqibnaveed** [comment]
@mrjoro Thank you for the invitation and assigning the issue to me :)
