### ISSUE TITLE
Allowing whitelisted origins to have the data-amp-replace to work even if the URL is not secure

### ISSUE THREAD

**Issue by rajkumarsrk** [ampproject/amphtml#9732]
## What's the issue?
Support for `data-amp-replace` for non secure URL's of links if they are whitelisted through `amp-link-variable-allowed-origin`

Currently the `data-amp-replace` doesnt replace the URL values like `CLIENT_ID, QUERY_PARAM` when the destination link is on http (non secure). Can we enable this if these links are whitelisted through `amp-link-variable-allowed-origin`

Example:
Page Origin URL is `https://www.m.example.com`

`<meta name="amp-link-variable-allowed-origin" content="http://www.example.com">`

`<a class="b-tile" href="www.example.com/itm/Nike-Tennis-Classic-CS-Suede-Black-White-Mens-Casual-Retro-Shoe-Sz-10/311837389525?src=urllib" data-amp-addparams="&_trkparms=gclientid%3DCLIENT_ID(ebay)&_trksid=p2380231.m4334.l8656" data-amp-replace="CLIENT_ID">Nike Tennis Classic CS Suede Black/White Men's Casual/Retro Shoe Sz. 10</a>` 

https://github.com/ampproject/amphtml/blob/master/src/service/url-replacements-impl.js#L820

@cramforce

**Comment by cramforce** [comment]
Hmm, I like only providing powerful features to HTTPS pages :)

Why isn't the destination available on HTTPS?

**Comment by rajkumarsrk** [comment]
Some of our pages are yet to get migrated to `https` and it would take some more time and with this change we would like to see if the current session stitching solutions fixes the analytics gap that we have

**Comment by cramforce** [comment]
@rudygalfi This is probably OK.

**Comment by rudygalfi** [comment]
I will ask privacy reviewers to get their take and respond back here.

**Comment by rajkumarsrk** [comment]
Do we have any updates on this ?

**Comment by rudygalfi** [comment]
@rajkumarsrk Still discussing. I will try and finalize this over the next couple days.

**Comment by rudygalfi** [comment]
I think we could go ahead with allowing such URLs and whitelisting as follows:

`<meta name="amp-link-variable-allowed-insecure-origin" content="http://www.example.com">` (notice "insecure")

@cramforce Does this look OK to you or do you have alternate suggestions on how to do the whitelisting or the name?

**Comment by cramforce** [comment]
Works for me.
