### ISSUE TITLE
Amp carousel issue 

### ISSUE THREAD

**Issue by dagar07** [ampproject/amphtml#9736]
AMP Carousel is not showing , when it served from google cache.

google caching url in mobile is :- https://www.google.co.in/amp/s/www.lybrate.com/amp/delhi/sexologist 

And it's also not visible from cdn server:  https://www-lybrate-com.cdn.ampproject.org/v/s/www.lybrate.com/amp/delhi/sexologist?amp_js_v=0.1

while amp carousel visible on amp Cloudflare 
 https://www-lybrate-com.amp.cloudflare.com/c/s/www.lybrate.com/amp/delhi/sexologist
<img width="311" alt="screen shot 2017-06-06 at 6 26 02 pm" src="https://cloud.githubusercontent.com/assets/16610202/26830321/1dca20ba-4ae6-11e7-8586-004dc98ac95c.png">
<img width="576" alt="screen shot 2017-06-06 at 6 26 28 pm" src="https://cloud.githubusercontent.com/assets/16610202/26830330/2ca3d482-4ae6-11e7-9491-7a5604ac394b.png">

My Page amp link is as : 
https://www.lybrate.com/amp/delhi/sexologist

Plz help me out , what is wrong with this??

Images :

**Comment by aghassemi** [comment]
/to @honeybadgerdontcare Looking at the source ( view-source:https://www-lybrate-com.cdn.ampproject.org/v/s/www.lybrate.com/amp/delhi/sexologist?amp_js_v=0.1 ) all the `amp-carousel` instances are remove by cache for some reason.

**Comment by honeybadgerdontcare** [comment]
@aghassemi They're actually not being removed by the cache. The cache had the old version before there was an amp-carousel on the site. I did an update-ping and the amp-carousel is there now. 

@dagar07 The Google AMP Cache will serve the latest version it has and poll for newer copies (respecting host limits). To ask the AMP Cache to poll for a new version more quickly it's possible to use the [update-ping](https://developers.google.com/amp/cache/update-ping) mechanism.


https://www-lybrate-com.cdn.ampproject.org/c/s/www.lybrate.com/amp/delhi/sexologist?amp_js_v=0.1

**Comment by aghassemi** [comment]
@honeybadgerdontcare Got it. Thanks!

**Comment by dagar07** [comment]
@aghassemi thanks. But why it's only visible first time after update-ping not second time??

**Comment by aghassemi** [comment]
@honeybadgerdontcare Not sure what's happening. `update-ping` refreshes it for like a minute and then it goes back to the old version without carousel. thoughts?

**Comment by honeybadgerdontcare** [comment]
Hmmm, it did disappear again but with an update-ping it is back again.

@dagar07 Are you sure there isn't an instance of your site that may be serving an older version without the amp-carousel?

I've filed an internal issue for this b/62410881 to have a look on Google's end as well.

**Comment by dagar07** [comment]
@honeybadgerdontcare No, first of all I were trying to find issue on my side. But when i don't understand what is wrong then i raised issue for carousel. And it is showing my amp page url, but not on google cache url.

**Comment by honeybadgerdontcare** [comment]
@dagar07 Thank you for confirming that your site may not be serving older versions in some instances. We are looking into it.

**Comment by dagar07** [comment]
@honeybadgerdontcare  thanks

**Comment by dagar07** [comment]
@honeybadgerdontcare  any update on this???

**Comment by honeybadgerdontcare** [comment]
We're seeing two different versions of the page, one with and one without the amp-carousel. Not sure why, but the server the page is coming from might be responding differently for some user agents and/or IP blocks.
