### ISSUE TITLE
Enum for AMP events

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#9738]
### First Timers Only
We know figuring out the process for contributing to an open source project can be intimidating, so we created this issue as a way for you to learn the ropes.  (If you feel comfortable contributing to open source projects, please leave this issue for someone else.)

### What you will need to know

- Some familiarity with JavaScript.

### Background

The DOM has a [rich event model](https://developer.mozilla.org/en-US/docs/Web/API/Event), e.g. for handling user input. AMP also uses custom events for coordinating behavior across components and modules in the code base. These AMP events follow a naming convention being prefixed with `amp:`, e.g. [`amp:built`](https://github.com/ampproject/amphtml/search?utf8=%E2%9C%93&q=%22amp%3Abuilt%22&type=).

### Motivation

Most usages of `amp:` events today use the string literal directly, for example [on this line](https://github.com/ampproject/amphtml/blob/2699e24df5a1ea47dcc143779c7eadf4e95a3731/src/service/resource.js#L311).

```
this.element.dispatchCustomEvent('amp:built');
```

This is nice and simple, but it results in duplication of the `amp:built` string and has the risk of typos. A better way to do this is to define these events in an enum, like what [video-interface#VideoEvents](https://github.com/ampproject/amphtml/blob/2699e24df5a1ea47dcc143779c7eadf4e95a3731/src/video-interface.js#L154) does.

### The bug

Let's create a new file, `src/amp-events.js`, that contains an enum defining the commonly used events for AMP components. This will reduce duplication, eliminate the risk of typos, and improve readability of our code base.

### Step by step
- [x] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#building-amp-and-starting-a-local-server).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] Search the code base for AMP events (try searching for `'amp:`).
- [ ] Create the `src/amp-events.js` file with an object literal enumerating the events you've found in your search.
- [ ] Import your new file into files containing the existing string literal event names and replace them with a reference to your enum.
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review).  Mention `Fixes #9738` in the description and mention me (@choumx) to get a code review.
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

### Questions?

If you have questions ask in this issue or on your Pull Request (if you've created one) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide. Mention me (@choumx) so I can help!

**Comment by abc516** [comment]
Hi @choumx , I would like to claim this issue.

**Comment by abc516** [comment]
Hi @choumx . I made the changes as specified in the Pull Request. However, the changes I've made are making the Travis-CI build fail. 

It seems adding the src/amp-events.js file as a dependency to various files in the 3p/ and extensions/ folders is violating dependency injection rules. Is it ok if I whitelist these files in build-system/dep-check-config.js?

**Comment by choumx** [comment]
@abc516 That should be fine since it's just an enum. Thanks!

**Comment by mrjoro** [comment]
Hi @abc516; I sent you an invitation to join ampproject on GitHub; once you accept that I think we'll be able to assign this issue to you.  Thanks!

**Comment by abc516** [comment]
OK Joey, I just joined.

**Comment by mrjoro** [comment]
Thanks @abc516!

**Comment by abc516** [comment]
You are welcome, @mrjoro !
