### ISSUE TITLE
test/integration/test-visibility-states.js flaky on master

### ISSUE THREAD

**Issue by rsimha-amp** [ampproject/amphtml#9757]
The integration test `test/integration/test-visibility-states.js` relies on uncompiled JS. However, after recent build optimizations, `gulp dist` only generates minified JS.

Figure out if `test-visibility-states.js` can be made to run with just `gulp dist`, and if not, figure out a minimal addition to `gulp dist` to create compiled and minified versions of those specific files the test needs.

**Comment by jridgewell** [comment]
I'll need to revert https://github.com/ampproject/amphtml/pull/9758 after fixing.

**Comment by rsimha-amp** [comment]
Still red on master: https://travis-ci.org/ampproject/amphtml/jobs/240618920

**Comment by jridgewell** [comment]
Damn, my fault. I missed the private `#setVisibilityState_` when reviewing it.

**Comment by zhouyx** [comment]
I still see test-visibility-states fail on master. 
https://travis-ci.org/ampproject/amphtml/jobs/242105387
@jridgewell Could you take a look?


> Mobile Safari 9.0.0 (iOS 9.1.0) Viewer Visibility State Element Transitions "before each" hook for "calls layout when going to VISIBLE" FAILED
	timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
........................................
Mobile Safari 9.0.0 (iOS 9.1.0): Executed 119 of 216 (1 FAILED) (skipped 73) (1 min 2.153 secs / 36.182 secs)
..............................................................................
Mobile Safari 10.0.0 (iOS 10.0.0) Viewer Visibility State Element Transitions "before each" hook for "calls layout when going to VISIBLE" FAILED
	timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.

**Comment by rsimha-amp** [comment]
Seems like there's a common theme of `beforeEach()` timing out in all these failures. Let me know if there's any infra work that can go into making these tests more resilient.

**Comment by zhouyx** [comment]
Oh no! still get integration tests failed 😭 
https://travis-ci.org/ampproject/amphtml/jobs/242944862

**Comment by rsimha-amp** [comment]
@jridgewell, @camelburrito: These tests are particularly flaky. Can they not just be disabled while they're fixed?
