### ISSUE TITLE
amp-bind: <amp-form> integration test broken on Edge & Safari 9

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#9759]
Here is the travis build 
https://travis-ci.org/ampproject/amphtml/jobs/240195458

```
Edge 14.14393.0 (Windows 10 0.0.0) amp-bind with <amp-form> should NOT allow invalid bindings or values FAILED
	Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
................................
Safari 9.1.2 (Mac OS X 10.11.6) amp-bind with <amp-form> should NOT allow invalid bindings or values FAILED
	timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.

.......
Mobile Safari 9.0.0 (iOS 9.1.0) amp-bind with <amp-form> should NOT allow invalid bindings or values FAILED
	timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.


```

**Comment by camelburrito** [comment]
@choumx @cvializ - These tests are blocking the canary , please take a look and skip them if you think its ok to skip or submit fixes/revert them. I would like to make the master green and cut the canary

**Comment by choumx** [comment]
- This only affects Edge and Safari 9, but is fine on Chrome, Firefox and Safari 10. 
- Not caused by a race with `AmpFormService` registration. 
- The Travis logs don't show anything useful.

Reducing priority since master is green now.

**Comment by choumx** [comment]
Merging with #10053.
