### ISSUE TITLE
AMP-AD: doubleclick: Ads not loading ONLY on iOS (small platforms)

### ISSUE THREAD

**Issue by krcrawford** [ampproject/amphtml#9787]
## What's the issue?

Safari only. iOS platforms, are not displaying doubleclick amp-ads, but the same ads are displaying on other browsers.

My source code is as follows:
```
<amp-ad type="doubleclick"
    data-slot="/1004147/LTK_Beauty_Style_Makeup_Top"
    data-multi-size-validation="false"
    data-multi-size="320x50,300x50"
    id="ad-main-banner-0"
    class="ad-main-banner"
    width="320"
    height="50"
    layout="fixed"
    media="(min-width: 320px) and (max-width: 727px) and (min-height: 400px)">
</amp-ad>
```

## How do we reproduce the issue?

Try the desktop Safari in responsive design mode, and load any `300x50` or `320x50` doubleclick amp-ad

1. Using either Desktop Safari in responsive design mode or an iPhone of the version 6 variety, browse to http://makeup.lovetoknow.com/Beyonce's_Makeup.amp
2. Look for the main banner ad to load on a device of matching profile: `@media (max-width: 415px)`
3. View the console output, and the lack of loaded main banner ad, which should be either a `300x50` or `320x50`

## What browsers are affected?

Safari iOS 10 - iPhone (SE, 6s, 6s Plus)
Safari iOS 10 - iPod touch
Safari iOS 10 - iPad
These are all on Safari desktop in responsive design mode, emulating hardware.
My org has also received reports of lack of ad loading on actual iPhone devices, so its not limited to desktop emulation via user agents

## Which AMP version is affected?

Powered by AMP ⚡ HTML – Version 1496670637476

This is a new issue for my org, and AMP pages went live for the first time last night.
Issue is non-existent for Chrome versions and IE browsers

Console Output:
[Error] Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) (amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it, line 0) https://www.googletagservices.com/amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it?1496873700000

[Error] Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) (amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it, line 0) https://securepubads.g.doubleclick.net/amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it?1496873700000

[Error] Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) (amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it, line 0) https://tpc.googlesyndication.com/amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it?1496873700000

[Error] Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) (amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it, line 0) https://partner.googleadservices.com/amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it?1496873700000

[Error] Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) (amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it, line 0) https://pagead2.googlesyndication.com/amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it?1496873700000

[Error] Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) (amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it, line 0) https://googleads.g.doubleclick.net/amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it?1496873700000

**Comment by krcrawford** [comment]
Essentially, it seems that some URLS are getting malformed in the doubleclick API regarding iOS user agents?

**Comment by keithwrightbos** [comment]
Testing locally emulating iphone on safari, it appears that the ad request is sent without issue but does not fill.  Perhaps the slot is not configured correctly in DFP?  Are you sure you have an inventory unit matching /1004147/LTK_Beauty_Style_Makeup_Top?

**Comment by krcrawford** [comment]
We definitely have the inventory unit. Try to hit the same URL on chrome or some ither browser...it works just fine.
Try also the same URL without the `.amp` extension in the path, and the ad loads just fine.
We've had this site for years, and we have a dedicated specialist who does nothing but ad network massaging.
That being said, do you agree that the console errors provided above have malformed URLs?

**Comment by krcrawford** [comment]
Addendum:
URLS that end with the amp_preconnect_polyfill seem to be reserved for AMP resources. Here are two intermittent examples I received 200 for:
https://d-2633554710493860842.ampproject.net/amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it?1496929500000
https://3p.ampproject.net/amp_preconnect_polyfill_404_or_other_error_expected._Do_not_worry_about_it?1496929500000

Seemingly, perhaps a URL formation routine is mis-firing or a domain is not being set as part of a critical race condition, which results in something like: `http://<non-amp-domain>.com/<amp-uri>` instead of `http://<amp-domain>.com/<amp-uri>`. Maybe even a `*.src = '//amp_preconnect_pollyfill...` is intermittently causing the issue?

**Comment by cramforce** [comment]
The preload is a red-herring here and entirely unrelated. That is why the
URL says: 404_or_other_error_expected._Do_not_worry_about_it

Ads not rendering / filling must have a different reason.

**Comment by krcrawford** [comment]
Interesting. Not directly pointing at it, just considering possible culprits. One thing thats certainly consistent is the relationship between 404s for preconnect URLS and ad not loading. Not assigning fault specifically, just noting the behavior.

Essentially, I wouldn't worry about it if it didn't show up each and every time the ad did not load.

Anyway, must be OS|browser related as the ads load in a heartbeat on most other browser|OS combinations

**Comment by cramforce** [comment]
This preconnect polyfill only happens in WebKit, because other browsers
support it natively.

**Comment by keithwrightbos** [comment]
@krcrawford are you still seeing this issue?  I just tested on desktop safari emulating iphone 6s and all of the slots loaded without issue.

**Comment by keithwrightbos** [comment]
Also do you see the issue when running Fast Fetch (go to https://makeup-lovetoknow-com.cdn.ampproject.org/c/makeup.lovetoknow.com/Beyonce's_Makeup.amp?#exp=a4a:2)

**Comment by krcrawford** [comment]
Apologies for the late update, but it seems that there was an odd issue with AdX. Our organization pushed back to the marketing team with other issues, at which point they deactivated that network. Orthogonally, the ads began to display.
I'm comfortable with you guys closing this if you see fit, and apologies for the mislead.

**Comment by keithwrightbos** [comment]
No problem
