### ISSUE TITLE
FR: File upload

### ISSUE THREAD

**Issue by jarek-picanova** [ampproject/amphtml#9791]
An option that user is able to upload a file.  
Currently amp-form doesn't allow `<input type=file>`, neither `<input type=image>`.
perfect would be do define parameters like: size limit, allowed formats, etc.

**Comment by ericlindley-g** [comment]
@aghassemi, @rudygalfi  — do you know what kept us from doing this in the past?

**Comment by isphillips** [comment]
Any idea if/when this will be prioritized? We are extremely looking forward to having AMP enabled on our site but have forms for users to upload resumes when applying for jobs.

**Comment by ericlindley-g** [comment]
Thanks for the feedback, @isphillips — knowing your need here definitely helps in the prioritization process.

@cvializ , @aghassemi : how much effort do you think it would be to make a change like this? Half a sprint, or more involved? Is this something that an external developer could onramp easily onto to contribute?

**Comment by isphillips** [comment]
@ericlindley-g Awesome, appreciate the prompt reply! Will definitely be watching this ticket.

**Comment by cvializ** [comment]
@ericlindley-g By my estimate, I think that it would be about half a sprint. Possibly more if any unexpected security concerns arise.

**Comment by craigscott29** [comment]
The company I work for could definitely use this feature as well. We are nearing completion of our AMP implementation, and apart from our store locator (which will probably never be AMP valid), the only other hiccup we are experiencing is the inability to add an uploader for resumes to our application forms. We will probably add it for now and let those pages go as AMP invalid until this feature is implemented.

**Comment by craigscott29** [comment]
Hurts.

![2a0ebbfa](https://user-images.githubusercontent.com/33098508/32954216-dbc442c6-cb88-11e7-9729-04fdc2e98912.PNG)

**Comment by aghassemi** [comment]
@craigscott29, we are planning to add support for this soon.

**Comment by rudygalfi** [comment]
Recommendation is to only allow file inputs on forms with action-xhr.

**Comment by cvializ** [comment]
Looks like for secure XHR forms, we only need to modify the validator rules to allow `input[type="file"]` in POST XHR forms. I have a demo running of how a currently-invalid form can submit a file, but it would be valid after changing the validator.

Code: https://glitch.com/edit/#!/dramatic-star?
Demo: https://dramatic-star.glitch.me/
