### ISSUE TITLE
amp-ima-video: enable preloading

### ISSUE THREAD

**Issue by shawnbuso** [ampproject/amphtml#9793]
Use the [IMA SDK preloading APIs](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.AdsRenderingSettings.enablePreloading) to preload video ads.

I thought I could do the following after opening this but apparently I can't :/ Can someone

1. Label as FR.
2. Add category A/V.
3. Assign to me.
4. Add to IMA Launch project.
5. Mark as P1.

Thanks!

**Comment by aghassemi** [comment]
done and added to [IMA Launch project](https://github.com/ampproject/amphtml/projects/24). (Note: I am using only P2 and P3 for IMA tasks now to keep P1 reserved for anything we should ship in < 2 weeks in AMP)

**Comment by shawnbuso** [comment]
FYI I've started work on this but I hit what might be an IMA bug, or might be an implementation bug that I can't figure out. I'll be working with one of the IMA SWEs next Tues to debug and hopefully resolve.

Also, kinda a big caveat, but this will not work on iOS. That's an IMA limitation, not a limitation of my plugin - we re-use the content player for ads on iOS, so we can't pre-load because the content is using the player when we would be pre-loading.

**Comment by aghassemi** [comment]
Thanks for the update. I assume this will be an attribute similar to `amp-video`'s `preload`? For `amp-video` we default to `none` but authors can specify `metadata` or `auto` similar to HTML5 video

**Comment by shawnbuso** [comment]
I don't think IMA supports it at that granularity - it's either on or off. I should be able to make it an attribute of amp-ima-video if that's what makes the most sense - up to this point I've just been hardcoding it to test it out.

**Comment by torch2424** [comment]
Assigning to myself as I've been owning `amp-ima-video`. If anyone needs updates/desires this feature, feel free to mention me while this is in our backlog.
