### ISSUE TITLE
Add support for validator rule for RTC config in head

### ISSUE THREAD

**Issue by bradfrizzell** [ampproject/amphtml#9800]
As part of adding support for RTC, publishers will be asked to include a config in their head, formatted like the following example. We need validator support added for this. 

```
<script type="application/ld+json" id="amp-rtc">
  {
    "doubleclick": {
      "url": "https://pub.com/rtc-endpoint",
      "sendAdRequestOnFailure": true
    },
    "fake-network": {
      "url": "https://pub.com/rtc-endpoint-fake-network",
      "sendAdRequestOnFailure": false
    }
  }
</script>
```

- Keys of the object must be the name of an ad network that supports AMP RTC.
- The value of ‘url’ must be a valid url.
- ‘sendAdRequestOnFailure’ is an optional member of the inner objects. 
- The id of the script must be amp-rtc.
- The type of the script must be application/ld+json
- Script must be in head.

**Comment by Gregable** [comment]
If it's OK with you, we'll leave validation of the json contents up to the javascript library, rather than making it a requirement for the document to be valid AMP, thus we'll validate:

 - [ ] script element, in the head
 - [ ] type="application/json"
 - [ ] id="amp-rtc"

**Comment by jridgewell** [comment]
Why does it need an id?

**Comment by Gregable** [comment]
@bradfrizzell , I don't know the RTC reason.

For validation, it helps distinguish this from other script tags, for producing good errors. For example, if the user left off `type=application/json` by accident but included the id, we can produce an error that directs the user to correcting the type. Without the id, we'd just need to give a generic "javascript is not allowed" type error.

**Comment by bradfrizzell** [comment]
The ID, from our end, was so we can grab it with getElementById. Is there something else I should do instead? Is there an issue with requiring an ID?

**Comment by Gregable** [comment]
This is the exact same thing we do for `amp-access`, I think `id` is fine.

**Comment by Gregable** [comment]
The changes are committed in #9831, The `type` attribute will be `application/json`, not `application/ld+json` which is a separate thing. We will not validate the actual json contents - anything is allowed. That'll be a runtime issue. Let me know if there is anything more we need here.

Note that this won't be released for another 2 weeks or so.

**Comment by bradfrizzell** [comment]
Thanks!

**Comment by Gregable** [comment]
This change has been released to the validator and will be live within an hour.
