### ISSUE TITLE
A/B experimentation framework when page is delivered from an AMP cache

### ISSUE THREAD

**Issue by jasti** [ampproject/amphtml#9809]
This feature is especially useful for advertisers who want to test the efficacy of their AMP pages delivered via a cache vs non-AMP landing pages delivered via the advertiser's server. 

One possible option is to create an A/B framework that diverts 'B' traffic via a redirect from the cache to the advertiser's server.  A downside with this approach is the additional latency caused by the redirect.

**Comment by cramforce** [comment]
This should at least explain why `amp-experiment` is not good enough. I don't see we'll do redirects.

**Comment by jasti** [comment]
@cramforce `amp-experiment` helps A/B test two versions of an AMP page, but it doesn't allow testing an AMP page vs a non-AMP page, right?

Some advertisers wouldn't want to switch over to AMP without knowing that it performs better than their current non-AMP page.

**Comment by cramforce** [comment]
@jasti should be tested using an experiment system on the referral side.

**Comment by jasti** [comment]
Thanks.
