### ISSUE TITLE
isValidatorFile in pr-check.js is not catching all validator related changes

### ISSUE THREAD

**Issue by rsimha-amp** [ampproject/amphtml#9836]
See https://travis-ci.org/ampproject/amphtml/jobs/241356980

It should have detected the build target VALIDATOR, but did not.

**Comment by rsimha-amp** [comment]
Discovered via #9834, which should have gone through testing for its validator changes, but did not

**Comment by honeybadgerdontcare** [comment]
#9812 most likely fixes this but still working on it.

**Comment by rsimha-amp** [comment]
Assigning to @honeybadgerdontcare. Let us know if there's more to be done after #9812.

**Comment by honeybadgerdontcare** [comment]
This may have more to do with #9730 than with #9812. Components of v1.0 were introduced before validator was able to handle them. #9812 added them to their test suite but the validator itself is still not prep'd for versions other than 0.1 and work arounds are currently employed to make them "work". Validator team will introduce abilities to handle other versions in the near future so until then v1.0 will need to tread carefully.
