### ISSUE TITLE
AMP cached version of the page ignores "custom content based on user location"

### ISSUE THREAD

**Issue by MKDan** [ampproject/amphtml#9844]
Hi,
Some of my AMP pages displays content based on the user location. The user from the US will see a different block of content and the user from India will see a different block of content on a web page.

This works perfectly on the normal web page and in the AMP version of the web page. But on the AMP cached web page, all users are seeing only the content for the US. How can I fix this?

Is there a way to disable caching of those web pages or I have to disable AMP for those pages? Please provide me the solution.

**Comment by jridgewell** [comment]
See https://github.com/ampproject/amphtml/issues/826.
