### ISSUE TITLE
To be Ignored

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#9856]

**Comment by camelburrito** [comment]
- Release duty - Making the build Green!
- Sidebar 1.0 Design 
- Intern ramp-up
- Carousel fliker on homescreen debugging

**Comment by cramforce** [comment]
- Working on cross AMP-origin/AMP-cache analytics.
- Early design discussions for improving AMP URLs inside of viewers.
- Update to latest `link-rel-preload` spec.
