### ISSUE TITLE
"on" attribute on amp-list and amp-list specific events

### ISSUE THREAD

**Issue by hamousavi** [ampproject/amphtml#9862]
## What's the issue?

AMP provides a number of element specific events as listed on https://github.com/ampproject/amphtml/blob/master/spec/amp-actions-and-events.md#element-specific-events

Can we have an amp-list specific event that is triggered when the amp-list fetching is completed? 

## How do we reproduce the issue?

We are looking for something like the "load" event as outlined in the following example

`<amp-list on=”load:AMP.setState({some state : json response})” … >`

So that we can store the response in an AMP state.

**Comment by hamoon88** [comment]
This is awesome William. Thanks.

**Comment by alexlyeh** [comment]
Wouldn't this would only update the amp-list with the loaded state if AMP.setState() is called again somewhere else? I tried it out, and I couldn't get the amp-list to load unless I manually triggered a button that had on="tap:AMP.setState()". Is there a way to render the specified bindings automatically after the JSON loads?

**Comment by choumx** [comment]
@alexlyeh Correct! Though this is slightly different from the original FR. The concern with automatically triggering mutation after the XHR completes is that it could cause dramatic, unexpected changes to the document (e.g. page content shifting) so we try to restrict that direct user interaction.

One way to accomplish this now that we have trustful actions (#9824) is to add a new low-trust event `amp-state:fetch` and a low-trust action `amp-list.update` (similar to existing `amp-live-list.update`).  However, it's arguable that the fetch event should have **zero trust** since there's no user intentionality.
```html
<amp-state id="myState" src="<my-url>" on="fetch:myList.update"></amp-state>
<amp-list id="myList" [state]="myState"></amp-list>
```
Another way to do this is to delay render of `amp-list`:
```html
<!-- Detect if template has bindings. 
     If so, wait for bind eval before update (w/ timeout). -->
<amp-list id="myList" src="<my-url>">
  <template type="amp-mustache">
    <p [text]="foo.bar"></p>
  </template>
</amp-list>
```
Note that the latter won't update the local bindable state with the XHR response.

@ericlindley-g This is similar to @cramforce's `amp-fresh` component FR, modulo the placeholder.

**Comment by alexlyeh** [comment]
@choumx Thanks for the clarifications!

**Comment by hamousavi** [comment]
@choumx in you example src attribute is dropped from amp-list. How would one get away with not specifying the src attribute on amp-list? Is not src a required attribute?

**Comment by choumx** [comment]
@hamousavi Currently it is required -- my example is hypothetical. Is your use case the same as above?

**Comment by ericlindley-g** [comment]
@choumx  — this is interesting. Since developers could specify their own placeholder/loading indicator, this might fit the need nicely.

**Comment by hamousavi** [comment]
Agreed with @ericlindley-g . This will nicely fit our case.

**Comment by aadi1295** [comment]
@choumx 

Hi, can you look at this [question](https://productforums.google.com/forum/#!topic/webmasters/Mf_UPR4dty8;context-place=forum/webmasters) I am unable to update amp-state and amp-list with amp-bind. Thanks

**Comment by choumx** [comment]
@aadi1295 FYI you can also ask AMP questions on the [amphtml-discuss](https://groups.google.com/forum/#!forum/amphtml-discuss) group or on our Slack channel.

**Comment by leoshaw** [comment]
I'm getting this in the console when using [state]

 `[state] is deprecated, please use [src] instead.`

is this still the recommended way to update the list dynamically?  I've tried using [src] pointing to the name of the object in the state, but it complains:

`Default value for [src] does not match first expression result (null). This can result in unexpected behavior after the next state change.​​​`

**Comment by choumx** [comment]
Yes, please use `[src]` instead. We'll probably remove that warning since it's been a source of confusion.

**Comment by jukefr** [comment]
@JakobEichler 
```
[height]="someState.items.length * BASE_ITEM_SIZE_HERE"
```

**Comment by durr04** [comment]
I need to perform 2 things
1. Set the state to the variable on page load with input element value which is getting updated on page load through server side.
2. Pass the same value(using variable) to the amp-analytics,

I want to set `AMP.setState()` when the page is getting loaded where the value of input element get updated on page load. Is their any way to set the value of input field to the variable. I have to pass the same value to the amp-analytics.

**Comment by joakimkm** [comment]
> Thanks for the filling this issue.
> 
> For your use case, try using an `amp-state` element with a `src` attribute that will load your JSON from a CORS endpoint in combination with an `amp-list` element with a `[state]` binding to render the JSON data at the given expression value. For example:
> 
> ```
> <amp-state id="myState" src="<my-url>"></amp-state>
> <amp-list [state]="myState"></amp-list>
> ```
> 
> The latter is a relatively new feature -- we'll add documentation for it soon.
> 
> /cc @ericlindley-g

How to solve this with load-more="auto" attribute set? 
I need a way to access new automatic fetched JSON-data.
