### ISSUE TITLE
Calling 3P APIs from an AMP page

### ISSUE THREAD

**Issue by hamoon88** [ampproject/amphtml#9864]
## What's the issue?

It seems that amp-list is the only way one could call third-party APIs from inside an AMP page (see [this](https://stackoverflow.com/questions/44507714/calling-third-party-apis-from-an-amp-page)). 

Given that, could we have a mechanism in amp-list for sending oauth2's access tokens in HTTP authorization header? 

## How do we reproduce the issue?

Sending access token in query-string parameters is frowned upon as indicated in the following [quote](https://developers.google.com/identity/protocols/OAuth2)

"It is possible to send tokens as URI query-string parameters, but we don't recommend it, because URI parameters can end up in log files that are not completely secure."

**Comment by aghassemi** [comment]
@hamoon88 Similar to many other places that AMP does XHR, the endpoint for `amp-list` must also adhere to [AMP CORS requirement](https://github.com/ampproject/amphtml/blob/master/spec/amp-cors-requests.md) which 3p APIs won't support. You would need to proxy 3p API calls in your server instead.

**Comment by hamoon88** [comment]
I was under the wrong impression that amp-list could be used for api calls. Thanks a lot for clearing that out and also thanks for the quick response @aghassemi.
