### ISSUE TITLE
The last-child amp-img does not render when CSS changes from display: none to display:block 

### ISSUE THREAD

**Issue by medicalspanw** [ampproject/amphtml#9865]
## What's the issue?
Briefly describe the bug/feature request.
Attempting to display a different image when the mouse hovers over the base image. This works for regular images, not amp-img.

## How do we reproduce the issue?

If this is a bug please provide a public URL and ideally a reduced test case (e.g. on jsbin.com) that exhibits only your issue and nothing else.  Then provide step-by-step instructions for reproducing the issue:
Sample code is located at www.physmed.biz/bug.html

1. Step 1 to reproduce
Place cursor over the top Google. The top Google will correctly disappear. The browser will correctly reserve the space associated with the Android image. However the Android image does not render.
2. Step 2 to reproduce
Repeat with the bottom Google image. When the cursor hovers, the Google image is hidden and the Android image displays.

3. …

If this is a feature request you can use this section to point to a prototype/mockup that will help us understand the request.
No
## What browsers are affected?
Chromium on Linux
All browsers? Some specific browser? What device type?
?
## Which AMP version is affected?
?
Is this a new issue? Or was it always broken? Paste your AMP version. You can find it in the browser dev tools.

**Comment by jridgewell** [comment]
We don't support changing the visibility of an element through the `:hover` css selector yet. Instead, you can use the `hidden` attribute and the AMP `show()` action. See http://codepen.io/aghassemi/pen/JWmNoB
