### ISSUE TITLE
TypeError: Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#9870]
Request:
https://www-dailystar-co-uk.cdn.ampproject.org/v/s/www.dailystar.co.uk/showbiz-tv/hot-tv/621704/Geri-Horner-Rylan-Clark-Neal-This-Morning/amp?amp_js_v=0.1  

User agent:
Mozilla/5.0 (Linux; Android 5.1.1; SM-J500FN Build/LMY48B; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/58.0.3029.83 Mobile Safari/537.36 

TypeError: Cannot read property 'document' of undefined
    at HTMLElement.b.dispatchCustomEvent (https://cdn.ampproject.org/rtv/021496877433269/v0.js:178:451)
    at https://cdn.ampproject.org/rtv/021496877433269/v0.js:182:409

Looks like https://github.com/ampproject/amphtml/blob/master/src/custom-element.js#L1112

to @choumx @jridgewell to take a look.

**Comment by jridgewell** [comment]
Ooo, this is fun.

```
TypeError: Cannot read property 'document' of undefined
at HTMLElement.b.document (https://raw.githubusercontent.com/ampproject/amphtml/1496877433269/src/custom-element.js:1113:21)
at https://raw.githubusercontent.com/ampproject/amphtml/1496877433269/src/custom-element.js:1281:11
```

The issue is that we called `#layoutCallback`, which returns a promise. When then queue a `#then` block on top of it. Before that then block is called, something happens to the element that causes it to lose the `document` -> `window` -> `document` pointers.

**Comment by zhouyx** [comment]
#10401 should resolve this. Track error reporting after canary cut.

**Comment by zhouyx** [comment]
Seeing this again

TypeError: Cannot read property 'document' of undefined
    at HTMLElement.Dg.b.dispatchCustomEvent (https://cdn.ampproject.org/rtv/001504822256449/v0.js:191:256)
    at https://cdn.ampproject.org/rtv/001504822256449/v0.js:195:211
