### ISSUE TITLE
Flaky integration test: amp-pixel

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#9908]
```
Mobile Safari 9.0.0 (iOS 9.1.0) amp-pixel amp-pixel integration test   should keep referrer if no referrerpolicy specified FAILED
	timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
Mobile Safari 9.0.0 (iOS 9.1.0) amp-pixel amp-pixel integration test "before each" hook for "should remove referrer if referrerpolicy=no-referrer" FAILED
	timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.

**Comment by lannka** [comment]
@zhouyx The link isn't pointing to a failed test.

**Comment by zhouyx** [comment]
Sorry I did a rebuild incase to merge the PR. But the information is copied from previous travis failure on this flaky integration test.

**Comment by choumx** [comment]
One of the few remaining flaky tests on master. 

Looks like multiple browsers causing race conditions by running these tests concurrently (`/withdraw` waits for `/deposit`). Note the HTTP 500 failure at the bottom due to simultaneous withdrawal. 

> Edge 15.15063.0 (Windows 10 0.0.0) amp-pixel amp-pixel integration test   should keep referrer if no referrerpolicy specified FAILED
	Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.

> Firefox 54.0.0 (Windows 7 0.0.0) amp-pixel amp-pixel integration test   should keep referrer if no referrerpolicy specified FAILED
	timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.

> Mobile Safari 9.0.0 (iOS 9.1.0) amp-pixel amp-pixel integration test   should keep referrer if no referrerpolicy specified FAILED
	timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.

> Mobile Safari 10.0.0 (iOS 10.0.0) amp-pixel amp-pixel integration test   should keep referrer if no referrerpolicy specified FAILED
	HTTP error 500​​​
	xa@dist/v0.js:10:174
	createError@dist/v0.js:6:41
	dist/v0.js:380:99
	initializePromise@[native code]
	Promise@[native code]
	Wj@dist/v0.js:380:34
	dist/v0.js:377:77
	promiseReactionJob@[native code]

https://travis-ci.org/ampproject/amphtml/jobs/250880323

/cc @lannka FYI
