### ISSUE TITLE
Issue using amp-bind with Shadow DOM

### ISSUE THREAD

**Issue by edhollinghurst** [ampproject/amphtml#9916]
I'm having problems using amp-bind within a PWA that uses the Shadow DOM.

Steps to reproduce:

1. Go to the example I've created at: https://www.edhollinghurst.com/amp-bind-pwa/amp-bind-pwa.html
2. Observe that if you click an answer it is correctly bound to the element used to display the answer.
3. Refresh the page. This should move you across to the 'PWA' with the 'App Shell' header displayed.
4. Trying clicking an answer. Observe that it is no longer bound to the element used to display the answer.

@choumx FYI

**Comment by choumx** [comment]
Thanks for reporting this. We'll take a look soon.

**Comment by MadisonMiner** [comment]
I'm running in to the same problem. Do we know when the fix will be released to production?

**Comment by choumx** [comment]
Fix should land in production by mid next-week. Thanks for your patience!
