### ISSUE TITLE
Is there necessary to submit AMP website to google?

### ISSUE THREAD

**Issue by awsomedesigner** [ampproject/amphtml#9917]
I have created AMP for a website. Now I want to publish those pages as AMP. Is there a process regarding how to publish AMP? I have used canonical URL as per AMP's guideline to make pages discoverable and my amp is valid as per AMP's validation. Can someone share as to how to deploy AMP pages so that I can see then in mobile when I search in Google

**Comment by jridgewell** [comment]
If they're properly linked to using `rel="amphtml"` from the canonical, there's nothing you need to do. The next time Googlebot crawls your website, your AMP pages will be crawled, too.
