### ISSUE TITLE
Use css class to customize sticky ad top padding bar

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#9927]
**Reserved For write/speak/code event**

### Description
`<amp-sticky-ad>` has a top padding bar `amp-sticky-ad-top-padding` to make it looks better. However the element has a name start with `amp-*`, the name should be reserved for AMPElemnt only. 

We can't rename the element's name now because it can introduce a breaking change to existence pages. We can however provide an alternative way to customize the top padding bar by adding a css class to the element. 

Ref issue: #9283 

### The Fix

- Go to [/1.0/amp-sticky-ad.js](https://github.com/ampproject/amphtml/blob/master/extensions/amp-sticky-ad/1.0/amp-sticky-ad.js) file
- Find the `<amp-sticky-ad-top-padding>` element
- Add a css class to the element to enable customizing. 
- Test manually 
- Fix unit test. Make sure tests pass.
- Submit for review!

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

### Questions?

If you have questions ask in this issue or on your Pull Request see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

**Comment by kellyk** [comment]
I can take this one!

**Comment by mrjoro** [comment]
Hi @kellyk; I sent you an invite to join ampproject on GitHub.  Once you accept it we'll be able to assign this issue to you.  Thanks!

**Comment by mrjoro** [comment]
Thanks for your contribution @kellyk!
