### ISSUE TITLE
All doubleclick ads showing 404s

### ISSUE THREAD

**Issue by matcarey** [ampproject/amphtml#993]
Currently the `<amp-ad type=doubleclick></amp-ad>` tags show an iframe with a 404 in it.  The iframe URL is https://3p.ampproject.net/1446714374021/frame.html examples:

 - http://www.mirror.co.uk/news/uk-news/jeremy-corbyn-made-member-privy-6813946.amp
 - https://www.theguardian.com/world/2015/nov/23/cameron-visits-bataclan-with-hollande-paris-attacks/amp

**Comment by cramforce** [comment]
Ads work fine for me. The frame URL does, indeed, 404, but at this point a different URL is being loaded.

@erwinmombay Could you take a look when we loaded version 1446714374021 and see what happened here?

**Comment by erwinmombay** [comment]
looking into it

**Comment by erwinmombay** [comment]
@cramforce we never had a version 1446714374021

@matcarey can you tell me where you got 1446714374021/frame.html ? thanks

**Comment by matcarey** [comment]
It was shown on the two pages I linked to (and all other doubleclick ads I could see in AMP pages).  I've just checked again and the listed version is currently 1448058695548.  I was in the office, I'm now at home so a) it's not a totally fair repeat and b) I haven't got the screenshots I took.

We have just released an update (the mirror link in my original bug report) and this appeared while we were pre-release testing.  I navigated around to see whether it was an issue we'd caused, but it seemed to appear everywhere.  I'm pretty sure the version was 1446714374021 in the console logs, I have an `amp-validator --output json` in my terminal session on my machine in the office which will specify which version I was seeing - I'll check that in the morning to make sure.

Looks like it's back to normal now.

**Comment by erwinmombay** [comment]
@matcarey got it, i was also running into some caching issues myself on my work laptop. (had to press shift + refresh to get rid of it)

i'll leave this open for now for further follow up when you get to your workstation. I cant think of a reason how we could link to a version 1446714374021 though.

here are all the version we've ever released so far, including ones prior to us tagging and releasing on github:
1442366139917
1442435912979
1442541364553
1442927479524
1443461807979
1443616512921
1443643108418
1443786272274
1443884719453
1443917087201
1443989667484
1444015271366
1444069877326
1444082436762
1445032534119
1446138480833
1446489425908
1446675574301
1447372082206
1447960408860
1448045024150
1448058695548

**Comment by erwinmombay** [comment]
@matcarey out of curiosity, you dont happen to be using the chrome "local amp" plugin on your workstation do you?

**Comment by matcarey** [comment]
Nope, haven't heard of it.

**Comment by matcarey** [comment]
OK, the version hasn't changed since yesterday.  It was:

```
amp-validator https://www.theguardian.com/world/2015/nov/23/cameron-visits-bataclan-with-hollande-paris-attacks/amp -o json
{
  "https://www.theguardian.com/world/2015/nov/23/cameron-visits-bataclan-with-hollande-paris-attacks/amp": {
    "ampVersion": {
      "declared": "v0",
      "precise": 1448058695548,
      "releaseDate": "2015-11-20T22:31:35.548Z"
    },
    "errors": [],
    "success": true
  }
}
```

And the same today.  I'm not sure how that came up.  Doesn't seem to be a problem today.
