### ISSUE TITLE
Remove all .max usage in doc

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#9931]
### Description
.max.html and .min.html usage has been deprecated. However we fail to update them everywhere in our documentation and comment

Ref PR: #8559

### The Fix

- Search for `.max.html` in our code base. 
- Find deprecated usage of `localhost:8000/examples/***.max.html` and rename them to end with `.html`
- Submit for review!

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon](https://github.com/ampproject/amphtml/blob/master/contributing/release-schedule.md)!

Thanks, and we hope to see more contributions from you soon.

### Questions?

If you have questions ask in this issue or on your Pull Request see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

**Comment by anantoghosh** [comment]
I would like to work on this! @zhouyx

**Comment by zhouyx** [comment]
@anantoghosh Great!!! Please consider [join the AMP Project on GitHub](https://docs.google.com/forms/d/e/1FAIpQLSeF1PN4Ee7Ke5Hvn4uN_oznV3isr-tfFg7cFRLX2F2OJGhXpw/viewform?c=0&w=1) so we can assign this issue to you 😄 

Let me know if any help is needed!

**Comment by anantoghosh** [comment]
@zhouyx joined.

**Comment by zhouyx** [comment]
Thanks! Assigned the issue to you 😄

**Comment by anantoghosh** [comment]
@zhouyx I need a little help.
Trying to commit ads/README.md runs gulp check-links on the file which is failing
https://travis-ci.org/ampproject/amphtml/jobs/245967540
```
Starting 'check-links'...
[14:39:32] [✖] http://rawgit.com/slightlyoff/IntersectionObserver/master/index.html#intersectionobserverentry
[14:39:32] [✖] https://github.com/ampproject/amphtml/blob/master/src/3p.js
[14:39:33] [✖] https://sub-domain.nytimes.com
[14:39:34] [✖] ../CONTRIBUTIONG.md#contributing-code
[14:39:34] ERROR Possible dead link(s) found in ads/README.md (please update, or whitelist in build-system/tasks/ch
eck-links.js).
[14:39:34] ERROR Possible dead link(s) found in this PR. Please update ads/README.md or whitelist in build-system/t
asks/check-links.js
```
These links are separate and not related to my commit.
Should I leave this file?

**Comment by anantoghosh** [comment]
I have created a pr fixing the links ads/README.md https://github.com/ampproject/amphtml/pull/10124

**Comment by zhouyx** [comment]
@anantoghosh Thanks for fixing our readme bug while working on this GFI !!! 👍 🎉 🎉

**Comment by zhouyx** [comment]
Thanks @anantoghosh ! 🎉 🎉 🎉
