### ISSUE TITLE
Add isStandalone method to the AMP platform service

### ISSUE THREAD

**Issue by cvializ** [ampproject/amphtml#9934]
**Description**

iOS devices allow users to add web pages to the home screen and look like an app icon. When a user opens the page from the home screen, the page renders fullscreen in Safari. AMP needs a way to detect if an AMP document was opened from the iOS home screen.

**The Fix**

- [ ] Go to `platform-impl.js` file
- [ ] Add an `isStandalone` method. Research how to implement this behavior for iOS.
- [ ] Go to test-platform.js and update the tests to test the new function.
- [ ] Submit for review! Add @cvializ as a reviewer. Address reviewer feedback, if any.
- [ ] Once approved, your changes will be merged. ⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡ You'll be able to see it live across the web soon!

Thanks, and we hope to see more contributions from you soon.

**Questions?**

If you have questions ask in this issue or on your Pull Request see the How to get help section of the Getting Started guide.

**Comment by JensVerneuer** [comment]
i will work on this as my first issue :-)

**Comment by ethereal-sandeep** [comment]
Hi,
I'd love to work on this for my first contribution, has it been claimed yet?

**Comment by ethereal-sandeep** [comment]
Unable to add @cvializ as a reviewer. Does the process involve claiming the Issue first and then only one can add reviewers in pull request?

**Comment by cvializ** [comment]
Hey it looks like this issue was suddenly pretty popular! Sorry for any confusion. To add reviewers you must be a member of the ampproject GitHub team, but we've taken care of adding reviewers for you. Thanks for your interest and contribution!

**Comment by mrjoro** [comment]
@JensVerneuer sorry about the collision!  Please take a look at the other [unclaimed Great First Issues](http://bit.ly/helpamp-gfis).  If you don't find a good one there please let me know; you can [send me a DM](https://amphtml.slack.com/team/mrjoro/) on Slack after [signing up](https://docs.google.com/forms/d/e/1FAIpQLSd83J2IZA6cdR6jPwABGsJE8YL4pkypAbKMGgUZZriU7Qu6Tg/viewform?fbzx=4406980310789882877).

@ethereal-sandeep I've sent you an invite to join the AMP Project.  Once you accept we'll be able to assign this issue to you as well.
