### ISSUE TITLE
Clarify the documentation for allowed attributes

### ISSUE THREAD

**Issue by uncompiled** [ampproject/amphtml#994]
It would be helpful to clarify the allowed attributes for whitelisted elements.  This would help publishers avoid validation errors when transforming content from their content management systems.

There is already a HTML5 element whitelist in the [AMP Tag Addendum](https://github.com/ampproject/amphtml/blob/master/spec/amp-tag-addendum.md), but there isn't a clear reference for the attributes that are allowed vs. prohibited by the AMP spec.

There is some documentation in the form of the [validator](https://github.com/ampproject/amphtml/blob/master/validator/validator.protoascii), but the validator might not be the most accessible format for all users.

**Comment by Gregable** [comment]
I think what I'd like to do is generate some code which will take the validator's [spec](https://github.com/ampproject/amphtml/blob/master/validator/validator.protoascii) file and produce some markdown from it that is more human readable. 

For example, the section regarding the `<meta>` tag in the validator reads:
```
# 4.2.5 the meta element
# Charset must be utf8, and a specific viewport is required.
# Other meta elements not supported.
tags: {
  name: "meta"
  mandatory: true
  mandatory_parent: "head"
  unique: true
  detail: "charset utf-8 declaration"
  spec_url: "https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#chrs"
  attrs: {
    name: "charset"
    mandatory: true
    value: "utf-8"
  }
}
tags: {
  name: "meta"
  detail: "viewport declaration"
  mandatory: true
  mandatory_parent: "head"
  unique: true
  spec_url: "https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#vprt"
  attrs: {
    name: "name"
    mandatory: true
    value: "viewport"
  }
  attrs: {
    name: "content"
    mandatory: true
    value_properties: {
      properties: { name: "width" mandatory: true value: "device-width" }
      properties: { name: "height" }
      properties: { name: "initial-scale" }
      properties: { name: "minimum-scale" mandatory: true value_double: 1.0 }
      properties: { name: "maximum-scale" }
      properties: { name: "user-scalable" }
    }
  }
}
tags: {
  name: "meta"
  attrs: {
    name: "property"
    mandatory: true
  }
  attrs: {
    name: "content"
    mandatory: true
  }
}
# The validator accepts any name="..." content="..." attribute pair except
# for a few specific name values which have more specific rules above or
# are altogether disallowed.
tags: {
  name: "meta"
  attrs: {
    name: "name"
    mandatory: true
    blacklisted_value_regex: "viewport|content-disposition|revisit-after"
  }
  attrs: {
    name: "content"
    mandatory: true
  }
}
```

And could be converted to markdown to look something like:

>4.2.5 `<meta>` 
>
>There are 2 mandatory `meta` tags
>
>  1. charset utf-8 declaration
>    - mandatory attribute `charset`, value `utf-8`
>    - There may be only one of these tags.
>    - This tag's parent must be a `<head>` tag.
>    - [Spec Reference](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#chrs)
>  2. viewport declaration
>    -  mandatory attribute `name`, value `viewport`
>    -  mandatory attribute `content`, value is a list of properties:
>        - mandatory name `width`, value `device-width`
>        - mandatory name `maximum-scale`, value `1.0`
>        - optional name `height`, any value
>        - optional name `initial-scale`, any value
>        - optional name `maximum-scale`, any value
>        - optional name `user-scalable`, any value
>    - There may be only one of these tags.
>    - This tag's parent must be a `<head>` tag.
>    - [Spec Reference](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#vprt)
>
>There are 2 optional `meta` tags variants:
>
>  1. <unnamed>
>    - mandatory attribute `property`, any value
>    - mandatory attribute `content`, any value
>  2. <unnamed>
>    - mandatory attribute `name`, value must match the regex `viewport|content-disposition|revisit-after`
>    - mandatory attribute `content`, any value

This is currently just an example done by hand. The Tag addendum was an attempt to do the same (also by hand) before folks had access to the validator spec file. I think we should write some code to generate this automatically from the spec file, however.

**Comment by Meggin** [comment]
FYI, I've added quite a bit of validation documentation. The main new doc is here: https://www.ampproject.org/docs/reference/validation_errors.html. As well, each spec has a validation errors table. Check out a couple of examples to see what they look like: https://www.ampproject.org/docs/reference/amp-img.html, https://www.ampproject.org/docs/reference/extended/amp-iframe.html.

**Comment by erwinmombay** [comment]
@Gregable i can take on that work, im currently in the process of writing down some scripts for the docs site to pull the data from the protoascii.

**Comment by Gregable** [comment]
@erwinmombay , sync up with @honeybadgerdontcare as I think he had started on this as well.

**Comment by honeybadgerdontcare** [comment]
Yeah, let's chat. I am in the process of markdown generation from the protoascii.

**Comment by adelinamart** [comment]
Is this still relevant?

**Comment by uncompiled** [comment]
I think this ticket can be closed.  IMO, since this ticket was opened, the release of the AMP validator as a Chrome plugin and nodejs module provide enough information.
