### ISSUE TITLE
AmpAnalytics <unknown id> Failed to process trigger "ini-load": null is not an object

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#9944]
Request: https://www-thesun-co-uk.cdn.ampproject.org/c/s/www.thesun.co.uk/tvandshowbiz/3762742/victoria-beckham-gets-hilariously-trolled-by-son-romeo-as-he-mocks-her-carrot-outfit/amp/  
User agent: 	
Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) GSA/28.0.157793287 Mobile/14A456 Safari/602.1

**Comment by jridgewell** [comment]
Stack trace? Pantheon id?

**Comment by zhouyx** [comment]
no stack trace found.

**Comment by jridgewell** [comment]
What's the pantheon id?

**Comment by zhouyx** [comment]
don't know where to find it.... i'll ping you the link

**Comment by jridgewell** [comment]
Stack trace is:

```
Jc@https://cdn.ampproject.org/rtv/001496360274808/v0/amp-analytics-0.1.js:141:346
https://cdn.ampproject.org/rtv/001496360274808/v0/amp-analytics-0.1.js:141:201
promiseReactionJob@[native code]
```

**Comment by zhouyx** [comment]
I can no longer see the error in error reporting. Close for now.
