### ISSUE TITLE
Muted play should only require ActionTrust.LOW

### ISSUE THREAD

**Issue by choumx** [ampproject/amphtml#9953]
Splitting this task off of #9699.

- [ ] Add ability to query muted state in videos, e.g. `isMuted()` to `video-interface.js`.
- [ ] Change `BaseElement.activationTrust()` to `BaseElement.requiredTrustForAction(method)` to be able to specify variable trust for a single action.

Note that we don't have any low trust events (yet), so implementing this won't yield any change in functionality.

/to @ericlindley-g How should we prioritize this? It's not much work -- just want to check.

**Comment by jridgewell** [comment]
So a automatic slidechange would be able to unmute?

**Comment by choumx** [comment]
Oops, typo. Playing a muted video should only require low trust actions. We actually don't have any low trust events yet though.

**Comment by ericlindley-g** [comment]
I'd prioritize this as low until we actually have something concrete to link this to — like scroll events. Sound good?

**Comment by choumx** [comment]
This is no longer necessary with #10166 since all video events only require low trust.
