### ISSUE TITLE
AMP Variable "TIMESTAMP" Format

### ISSUE THREAD

**Issue by 1987yama3** [ampproject/amphtml#9959]
I suppose a feature that it possible to format AMP variable 'TIMESTAMP'.

This is for displaying data as a character string for users when sending data with AMP Analytics.

For example, I think following usages.

```
AMP Variable: timestamp(yyyy-MM-dd'T'HH:mm:ss.SSSZ)
```

The format will be based on other language datetime format function, too.

**Comment by lannka** [comment]
@1987yama3 can you justify the use case? Why is this kind of client formatting useful?

**Comment by 1987yama3** [comment]
@lannka It is depends on how to use the submited value.
If it is used by computer, we should send the UNIX time.
But if not, it is used by human at reports, we should send the formatted string.
Because human can't understand what day "1498043786639" represents.

**Comment by lannka** [comment]
@1987yama3 how can you send a ping to a human :-). Isn't the endpoint another computer? Or are you just talking about debugging in Chrome console?

**Comment by jridgewell** [comment]
I'm thinking these are used in some dashboard table...

**Comment by 1987yama3** [comment]
@lannka Of cource, the destination of the beacon is a server. However, if the report tool processes that value as a simple string, the timestamp will be displayed on the dashborad(I called it "used by human").

**Comment by rudygalfi** [comment]
Traditionally we prefer to not increase the library complexity if the capabilities that AMP already exposes can be manipulated on the server/consumer side. In this case, since there's already a step to process the input value as a string, could that logic be updated to format the string as needed?

**Comment by rudygalfi** [comment]
Let me know if that reasoning makes sense. For now, I'll close. But if there is more detail you can provide around needing to process the string on the client, please re-open to continue the discussion.

**Comment by 1987yama3** [comment]
@rudygalfi If we are a marketing tool developer, I should customize my tool. 

But it is diferrent.
Users of the tool can not change the movement of the marketing tools.
We need to enter data according to the specification of each tools.

**Comment by lannka** [comment]
@1987yama3 given the fact that client formatting is losing flexibility the usage I think is rare. I don't want to introduce too much client code into our analytics extension. As a compromise, are you OK if we only support the ISO standard time string:

`2017-06-29T20:01:47.932Z`

which is natively supported by javascript.

**Comment by 1987yama3** [comment]
@lannka It is no problem. But, I think that it is better to use the time that takes user's timezone.

**Comment by lannka** [comment]
OK, so we can introduce a new var `TIMESTAMP_FORMATTED`, which will prints`new Date().toLocaleString()`.

**Comment by lannka** [comment]
oh, `toLocaleString()` won't work, since you expect same formatting. we will have to format it manually

**Comment by lannka** [comment]
@tiendt would you take a  stab on this? What we've agreed is to introduce a new var TIMESTAMP_FORMATTED, which provide human readable timestamp in format of `2017-07-07 13:21:34`

@1987yama3 let me know if this does not sound right.

**Comment by 1987yama3** [comment]
@lannka LGTM!

**Comment by lannka** [comment]
@cramforce since you have [different opinion](https://github.com/ampproject/amphtml/pull/10407#discussion_r128531078) of supporting a formatted time in local timezone, can we address it here with the original feature requester? 

From analytics's perspective, I agree with @1987yama3 that local time is better so the developers can really dive into the user's behavior across timezone. (do users read our news in the morning or evening).

But again, the usage is also unclear to me. I'm not sure how the server can aggregate data using the formatted time string. Can you briefly share the real scenario where will you display the  formatted user local time? @1987yama3

**Comment by cramforce** [comment]
We provide `TIMESTAMP` and `TIMEZONE` (offset), so calculating the user's localtime is trivial server side.

If we do formatting, we should not just call it "formatted" since there are thousands of way to format a datetime. A sensible standard like SQL date times may make sense, but I don't see how that is better than epoch time + timezone offset.

**Comment by 1987yama3** [comment]
@lannka @cramforce 
Here are a few use cases that need this feature.

Case1: Google Analytics custom dimensions
It is common to include client IDs and timestamps in custom dimensions. This allows you 
to display the action flow for each user. There is no data type definition for custom dimensions.
In other words, in order to make the report page easier to view, it needs to be sent with a formatted string.

Case2: Extraction of remarketing list by daily or timely
When executing the remarketing tag, add timestamp as custom information.
For example, in Google Adwords, we can use "google_custom_params" to add strings to tags and 
use them for list conditions.

Then, we can create these remarketing list,

- User list including "2017/01/01" as the added parameter string
- User list including " 05:"(space literal + 05:) as the added parameter string(it means they saw early in the morning)

In addition, the conditions can be made afterwards.


The tool developer solves the feature by creating it. However, the tool user can not develop the feature.
Threrefore, it is necessary to follow the constraints of the function.


Thanks

**Comment by lannka** [comment]
I think those are valid use cases. @cramforce what you think?

**Comment by cramforce** [comment]
What I don't understand: Why can't one just do the formatting on the server side given the timestamp and the timezone?
In any case, we should not call it formatted, we should pick a standard format and implement that. But I also don't want to support 15 others formats. So, if we cannot decide on one we need to implement full on `printf` style date formatting.

**Comment by 1987yama3** [comment]
@cramforce Because I am NOT a tool vendor. I am a marketer using tools.
Marketer use a lot of tools. Even if I ask these tool venders for additional feature, there are a few tools to implement.

I propose that try changing the date part and the time part to different AMP variables. I think it is possible to concatenate with analytics-json. In addition, I think that usability is enhanced and it will be easier to implement a bit.

**Comment by cramforce** [comment]
@1987yama3 Asking vendors to change things is something we do all the time :)

I'm sympathetic, though. Has anyone proposed an ISO standard that we should format to? Have vendors agree on a standard? Or should we implement `printf`?

**Comment by 1987yama3** [comment]
@cramforce Is it a question to me?

**Comment by cramforce** [comment]
You could answer it.

We won't just randomly make up a date format. Either

- we can agree on some standard
- or we convince ourselves that we need `printf`.

**Comment by 1987yama3** [comment]
@cramforce Thanks.
It is possible to sort by time series, and if human can quickly judge the date and time, there is no problem with the standard format.

But I think it is correct to implement printf in general if it does not become complicated.

**Comment by lannka** [comment]
@1987yama3 I wanted to avoid increasing core AMP binary size for such a feature that seems to be rarely used.

But I think we can introduce this `printf` like date formatting as a separate AMP extension. And you're welcome to contribute a PR if you want to get it sooner.

On the other hand, as we proposed, TIMESTAMP_ISO is something free to have, let us know if you think that's helpful.

**Comment by 1987yama3** [comment]
@lannka Thanks for your reply. 
Is the issue is #10837 ? I looked at the issue. It is cool!
It seems to be difficult to implement by myself, but I am looking forward to it.

**Comment by lannka** [comment]
@1987yama3 i was thinking a different extension. #10837 is to introduce a widget that renders a date on the page. but you're looking for a formatting that can be used in URL.

@cramforce so we will go ahead to add support for `TIMESTAMP_ISO` (since it's cheap), and leave the `TIMESTAMP_FORMATTED("yyyy-MM-dd hh:mm:ss")` for an extension to implement. Does that sound good?
