### ISSUE TITLE
[Ads][Doubleclick] Allow multi-size reordering

### ISSUE THREAD

**Issue by patrick-mcdougle** [ampproject/amphtml#9964]
## What's the issue?

Currently `<amp-ad type="doubleclick" .../>` requires the larger size to be primary (even if using a size override). This is unnecessarily limiting. For example, a requirement was passed down to me to have the ad sizes in the ad request be smaller first, then larger (our ad-ops team claims this effects reporting). In order to achieve this, I would have expected the following amp tag to allow me to do this:
```
<amp-ad 
    type="doubleclick"
    width="320"
    height="150"
    data-override-width="320"
    data-override-height="50"
    data-multi-size="320x150"
    data-multi-size-validation="false"
    ...
></amp-ad>
```

Note: The width and height correspond to the largest extent that this ad could possibly get, the override is the first size that's in the ad request, and all the additional sizes come after that. When trying this, I get the following error:

>Error: Secondary height 150 can't be larger than the primary height.

I understand that the height and width attributes need to be the largest extend of all the possible ads, but I would have expected the above to work just fine.

## How do we reproduce the issue?

1. Create an amp-ad tag using the above as a template.

## What browsers are affected?

All browsers

## Which AMP version is affected?

Not sure.

If desired, I'd be willing to work on removing this unnecessary limitation, but I don't want to break ground unless I know such work would be accepted.

Thanks!

**Comment by jasti** [comment]
I think it's fine to remove this restriction when data-override-* is present but would like @glevitzky's opinion on it.

**Comment by glevitzky** [comment]
We currently ignore the width/height attributes if override-width/override-height are set. You should be able to accomplish what you want without removing any restrictions by doing:

```
<amp-ad 
    type="doubleclick"
    width="320"
    height="150"
    data-multi-size="320x50"
    data-multi-size-validation="false"
    ...
></amp-ad>
```

Does that satisfy your needs?

**Comment by patrick-mcdougle** [comment]
@glevitzky no. This does not work because the sizes in the ad request are not in the order that I need.

Referencing my original post:
> For example, a requirement was passed down to me to have the ad sizes in the ad request be smaller first, then larger

That is, 320x50 would come before 320x150 in the ad request to DFP.

**Comment by glevitzky** [comment]
In the example I gave, the sz attribute on the request would look like `sz=320x150|320x50`, as the primary size is always listed first.

However, if the issue is the actual order of the sizes in the request, I don't see any reason, from an amp-ad multi-size perspective, why we can't rearrange the sizes before issuing the ad request. My only concern is that I'm not sure how this affects things down stream (e.g. does the server give more preference to creatives matching the first given size? Will that affect publisher's expectations? Etc.).

**Comment by jasti** [comment]
@patrick-mcdougle we'd need more specifics around 'our ad-ops team claims this effects reporting' before we try switch what would be the natural thing to do - listing the primary size as the first size on the ad request.

**Comment by patrick-mcdougle** [comment]
@glevitzky @jasti 

From my Ad Ops Team:

> The DFP user interface only reports the first listed size in the ad request. For consistency in reporting we always have the primary size listed first. This is especially helpful for analysts so that they don't have to keep a running list of every alternative size we offer and remember to select each one. Instead they know the bases sizes and then report against them. ![dfp-report-screenshot](https://user-images.githubusercontent.com/1392496/27462046-dd5c6ecc-5772-11e7-8271-557f975157bd.png)

It seems that the Ad Request Size in this reporting interface is only the first size in the ad request.

Allowing what I have written in the original post would make my AdOps team's jobs easier, and since there's no real technical limitation, I'd like to see this be a possibility. I would be willing to work on a PR if such a PR would be merged.

Thanks,
Patrick

**Comment by glevitzky** [comment]
Unfortunately, after some internal consultation, I have to stand by my original assessment. The order of the sizes cannot be changed, because the backend expects them in the order currently given.

**Comment by patrick-mcdougle** [comment]
@glevitzky Which backend are you referring to? AMPs? DFPs? I'm a little confused.
