### ISSUE TITLE
Generate ClientID using ClientID API via Viewer

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#9967]
### Before
Right now AMP runtime generates base CID and pass to Viewer for storage. 
AMP runtime is responsible to generate “scoped CID” by hashing base CID with the scope string. Base CID is never sent over the wire.
 
Runtime communicates with Viewer using postMessage.
 
```js
sendMessage(‘cid’, opt_data);
```
Opt_data is an object:
```
{
  time: time,
  cid: string,
}
 ```

If `opt_data` is present, this is a SET
If `opt_data` is missing, this is a GET
 
### After
Pub base CID stored server side
1) In the CID API, we introduced a new concept called “pub base CID” in addition to the existing “global base CID”. 
global base CID: will still be persisted in browser, as a Viewer domain cookie, 
pub base CID: will be stored on a remote server, and exposed as an API.
 
2) The new design fully hide both base CIDs away from individual AMP document. In old design, AMP document reads base CID from Viewer, then hash it with a scope string to generate a “scoped CID”. In the new design, for sake of better security, AMP runtime will pass the scope string to Viewer, and Viewer is responsible to generate the “scoped CID”.
 
3) For backward compatibility, Viewer use URL fragment param `cap=cid,others,...` to inform AMP runtime to do the new approach  
 
The same messaging protocol will be used. opt_data will be redefined to hold the scope string, and it will be promoted to a required param going forward.

**Comment by jridgewell** [comment]
1. How does pub base CID affect the analytics CID?
2. How will runtime differentiate between compatible viewers? It'd be bad to use a v1 implementation (non-scoped CID) and assume it's a v2 (scoped CID).

**Comment by lannka** [comment]
> How does pub base CID affect the analytics CID?

Analytics CID, like any other scoped CID, is generated from Viewer by hashing the pub base CID with the scope string.

> How will runtime differentiate between compatible viewers? It'd be bad to use a v1 implementation (non-scoped CID) and assume it's a v2 (scoped CID).

All CIDs eventually get exposed to pub/3p are scoped. V1 gets base CID from Viewer and generate scoped CID in AMP runtime, while V2 gets the scoped CID directly from Viewer.

**Comment by jridgewell** [comment]
>  hashing the pub base CID with the scope string.

So pub base will replace the viewer's base?

> V1 gets base CID from Viewer and generate scoped CID in AMP runtime, while V2 gets the scoped CID directly from Viewer.

My issue is how do we tell which is which? If we keep the same `{ time: number, cid: string }` format, we'll never be able to tell if this is a scoped CID or a base.

**Comment by lannka** [comment]
> So pub base will replace the viewer's base?

Not exact replace. The original base CID concept is still there, stored as a cookie in Viewer. The per pub base CID is a new concept.

> My issue is how do we tell which is which? If we keep the same { time: number, cid: string } format, we'll never be able to tell if this is a scoped CID or a base.

It's returned by different function call:
```
if (viewerSupportsCid) {
  // expect new way
} else {
  // expect old way
}
```
