### ISSUE TITLE
Confirm need for intermediate container for amp-lightbox in A4A

### ISSUE THREAD

**Issue by alanorozco** [ampproject/amphtml#9972]

**Comment by lannka** [comment]
Confirmed with Alan offline that such a container is a thing already used by ad networks.
The decision is to use a `div` instead of introducing a specific tag name.

We can close this once the renaming is done.

**Comment by alanorozco** [comment]
Going for transparent body. Decided team-wise that this was the better choice. Will trigger a development warning to prevent author confusion.
