### ISSUE TITLE
Lightbox 2.0: transition animations

### ISSUE THREAD

**Issue by aghassemi** [ampproject/amphtml#9976]
Transition animation from/to opener similar to amp-image-lightbox

**Comment by aghassemi** [comment]
8

**Comment by cathyxz** [comment]
Basic implementation done in https://github.com/ampproject/amphtml/pull/12313. Need a proper exit animation, testing, and polish.

**Comment by cathyxz** [comment]
This has been done quite a bit ago. Follow up work tracked in https://github.com/ampproject/amphtml/issues/13039
