### ISSUE TITLE
[amp-sidebar 1.0][Toolbar] Add support for positioning the toolbar on the top or bottom

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#9983]
- [ ] Add support for positioning the toolbar on the top or bottom of the page, You will need to compensate the page for the toolbar height since we don't want any part of the page to become inaccessible (hint: use border/padding/margin hacks as needed). IOS might need special compensation (look at old sidebar code.)
- [ ] Make sure this works in the viewer

**Comment by torch2424** [comment]
Please Note, this will require some UX decisions, as we do not know if this should be placed at the end of the page, or if it is 'position: fixed' at the bottom of the page.

**Comment by torch2424** [comment]
For UX decisions / Edge cases on fixed vs. static:

Sidebar is already `position: fixed` by default. So I think we should assume the fixed route. Also, with #9982 , The user would be able to simply target an element in which the toolbar would be placed into. In that case, they are responsible for styling (We would remove our defaults), and could easily place at the bottom of the page statically. This would still fall in line with our original goal of allowing users to create toolbars without having to write duplicate code.

**Comment by torch2424** [comment]
After UX discussions, we decided that this should be handled by the developer using the [target attribute](https://github.com/ampproject/amphtml/issues/9982)

Made sure to mention this the [Amp By Exmaple issue](https://github.com/ampproject/amphtml/issues/9991)

Closing...
