### ISSUE TITLE
[amp-sidebar 1.0][Toolbar] Support Sidebar with only toolbar content

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#9984]
Will need ux / product decisions - we don't want to show empty sidebar if the sidebar only has toolbar contents

**Comment by torch2424** [comment]
During a UX review, we decided that we would have 3 cases:

1. All sidebar content becomes toolbar, and the toolbar button is clicked, and opens an empty toolbar.

2. All sidebar content becomes toolbar, and the toolbar button is clicked, and does nothing.

3. All sidebar content becomes toolbar, and all toolbar buttons that are tap-able are hidden.

We decided to go with one, as option 2 is equally as bad of an UX (slightly worse than option 1 in my opinion), and option 3 would be expensive and introduce many edge cases.

Option one requires no extra work from us. And if developers continually make the mistake, or propose a solution, then we can develop something for this edge case.

Closing...
