### ISSUE TITLE
Remove the 'development' attribute mechanism for triggering validation

### ISSUE THREAD

**Issue by Gregable** [ampproject/amphtml#999]
There are currently two ways of triggering AMP validation within the browser documented in the [AMP runtime section of the spec](https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#amp-runtime):

1. Appending `#development=1` to the URL of the page.
2. Adding the `development` attribute to the AMP runtime script tag, e.g. 
`<script src="https://cdn.ampproject.org/v0.js" development></script>`.

I'm considering removing the second option and looking for opinions.

Currently the attribute triggers validation which considers the development tag the one and only "production warning" reading `DEV_MODE_ENABLED development - please remove for prod`. This warning is emited to the javascript console but does not prevent the output from PASSing. This "production warning" seems to be a source of confusion. The idea is that we don't want validation to auto-fail due to triggering the validation itself, but we also don't want final published documents to contain this validation tag due to the performance hit. So, for development, we treat this as a warning, but in production, we treat this as an error.

The advantage of the development attribute is that it allows for CMS'es to automatically insert the tag when the developer views the page but remove it in user-facing contexts. However, now that the validator source is available, other options could be built for accomplishing the same thing. For example, the CMS could replace the AMP runtime script with a modified copy that always triggers validation, or validation could be performed server side.

**Comment by dvoytenko** [comment]
Yeah. With the ability to set `development=1` fragment, I also find `development` attribute redundant.

**Comment by matcarey** [comment]
I had some problems with the `#development=1` on headless browsers and found myself making use of the attribute hook.

I've released https://www.npmjs.com/package/amp-validator (a beta) to provide a command-line validator so that people don't have to hack around headless browsers themselves.  Implementing this change would not break `amp-validator`.

**Comment by Gregable** [comment]
Update, @powdercloud just issued https://github.com/ampproject/amphtml/pull/1051 which will make the development attribute a plain old development error instead of a "production warning". The attribute still does in fact trigger the validator, so the runtime is unaffected, but I'd like to remove that functionality too so as to make this as simple as possible.

**Comment by jmadler** [comment]
@cramforce OK to submit a PR to remove the 'development' attribute?

**Comment by cramforce** [comment]
Ship it.

**Comment by jmadler** [comment]
It turns out that one of our tests, test/integration/test-example-validation.js, uses development mode to test for validation errors.  It does so using XHR.open for a URI which previously used the development attr, but now must use '#development=1'

As far as I can tell [XHR.open does not pass](https://bugzilla.mozilla.org/show_bug.cgi?id=459456) the "anchor" component of the requested URI.

Possible Solutions:

1 - Find a different way to run the test harness
2 - Allow both #development=1 and ?development=1 (e.g. location.hash, location.search)

How would you like to proceed?

cc @erwinmombay

**Comment by Gregable** [comment]
Re option 1, in a test environment, it should be possible to just directly call the validator api with the document contents rather than triggering it via a specific URL. Happy to help out with that if it's not clear how to do so.

**Comment by jmadler** [comment]
As I understand it, this particular test is intended to test the error reporting itself, not specific given errors.  In that case, would using that API be an appropriate mechanism for the test?

cc @powdercloud

**Comment by cramforce** [comment]
@jmadler Are you that is the problematic test?  test/integration/test-example-validation.js calls the validator directly.

**Comment by cramforce** [comment]
I'm sending a PR to fix `test/fixtures/errors.html`

**Comment by mixonic** [comment]
Does the removal of the second method mean there is no way to trigger development mode on a document you have no URL for? I'm using an iframe and `srcdoc` to preview generated AMP documents and would like to trigger validation.

re: https://stackoverflow.com/questions/34799046/how-can-i-trigger-amp-development-mode-without-a-url

**Comment by Gregable** [comment]
You can directly import the validator and use it in your javascript code if you'd like. Here's a little demo:
https://jsfiddle.net/4yoxog13/5/

**Comment by mixonic** [comment]
Great, thank you @Gregable!

**Comment by dandv** [comment]
@Gregable: I see different results between the `AMP validation successful.` message and the gist of that JSFiddle, `amp.validator.validateString(document.head.innerHTML + document.body.innerHTML).status` (FAIL). For example, these URLs display `AMP validation successful.` in the console, but `amp.validator.validateString(document.head.innerHTML + document.body.innerHTML)` shows a failure with 50+ errors:

* http://www.forbes.com/sites/halsinger/2016/02/05/the-sketchy-stat-behind-the-fccs-unlock-the-box-campaign/amp/#development=1
* http://s.response.jp/article/2016/02/09/269442.amp.html#development=1

Similarly, when the console shows "AMP validation had errors", amp.validator.validateString(document.head.innerHTML + document.body.innerHTML).errors` has far more errors than those dumped to the console - e.g. 130 vs. 2 at http://www.lastampa.it/2016/02/05/esteri/il-corpo-di-regeni-domani-a-roma-per-lautopsia-bUQmA4aeAuLXyyVsI1NA8O/amphtml/pagina.amp.html#development=1
