### ISSUE TITLE
[amp-sidebar 1.0] Add an AmpByExample - Example

### ISSUE THREAD

**Issue by camelburrito** [ampproject/amphtml#9991]

**Comment by aghassemi** [comment]
June H2: 3

**Comment by torch2424** [comment]
We should try to add example for toolbar use cases such as [Bottom Toolbars](https://github.com/ampproject/amphtml/issues/9983), and multiple toolbars

**Comment by torch2424** [comment]
This is being done in https://github.com/ampproject/amp-by-example/pull/894 Closing...
